### ISSUE TITLE
[Bug] broken linkedin account link

### ISSUE THREAD

**Issue by cc189** [LeetCode-Feedback/LeetCode-Feedback#1]
**What kind of the bug**
- [ ] problem
- [ ] solution
- [x] user experience

**Describe the bug**
- `https://leetcode.com/your_username/` profile page
- missing `href` attribute in `<a>` tag for linkedin account

**Expected behavior**
`<a>` tag with `href` attribute

**Screenshots**
<img width="1108" alt="p1" src="https://user-images.githubusercontent.com/39324273/75758190-87e01880-5ce8-11ea-8015-e2898c5cac1c.png">

**Comment by CooperCooperCooper** [comment]
Hi @cc189! Thank you for sharing this issue with us. This is a well-known technical issue that we're currently working on. If you would like to report any other technical issues, please don't hesitate to file them here: https://support.leetcode.com/hc/en-us/community/topics.

We appreciate your time and support :)
