### ISSUE TITLE
UI + Google+

### ISSUE THREAD

**Issue by BZAghalarov** [LeetCode-Feedback/LeetCode-Feedback#10]
Hi,
In the articla part of the questions seem social media links.
Among them you can find "Google+" link but Google has stooped this product please remove this icon.
It is not working already.
![Google+](https://user-images.githubusercontent.com/17585937/75872171-26729380-5e27-11ea-96dc-9cafb7893929.jpg)

**Comment by CooperCooperCooper** [comment]
Hi @BZAghalarov!
Thank you for reaching out to us! The technical issue you pointed out is related to the add-ons of our site, so please file it here: https://support.leetcode.com/hc/en-us. 
We appreciate your time and support. Please feel free to let us know if you have any other questions.
