### ISSUE TITLE
Missing Test Case - 815. Bus Routes

### ISSUE THREAD

**Issue by yogiKumar** [LeetCode-Feedback/LeetCode-Feedback#10004]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
My solution is passing all the test-cases for this problem, however it is not the correct solution since instead of connecting all the stops for a given bus to each other I am only connecting all the stops to the first bus stop. I am providing a custom test-case which failed in my solution to illustrate my point.

#### Code you used for Submit/Run operation
```
class Solution {
public:
    int numBusesToDestination(vector<vector<int>>& routes, int source, int target) {
        //edge case
        if(source==target)
            return 0;
        unordered_map<int,vector<int>> um;
        unordered_set<int> st;
        int n=routes.size();
        vector<bool> v(n,false);
        queue<int> q;
        for(int i=0;i<n;++i){
            for(int j:routes[i]){
                um[j].push_back(i);
                if(j==source){
                    q.push(i);
                    v[i]=true;
                }
                if(j==target)
                    st.insert(i);
            }
        }
        //adj list
        unordered_map<int,vector<int>> adj;
        for(auto [k,v]:um){
            for(int i=1;i<v.size();++i){
               //connecting only first and ith bus stop, instead of connecting ith stop with jth stop using a double for-loop
                adj[v[0]].push_back(v[i]);
                adj[v[i]].push_back(v[0]);
            }
        }
        int d=1;
        while(!q.empty()){
            int s=q.size();
            for(int i=0;i<s;++i){
                int node=q.front();q.pop();
                if(st.count(node))
                    return d;
                for(int ne:adj[node]){
                    if(!v[ne]){
                        q.push(ne);
                        v[ne]=true;
                    }
                }
            }
            ++d;
        }
        return -1;
        
    }
};
```

#### Expected behavior

The above solution is expected to fail since it is not right. Consider this custom test-case which failed with my submission
```
[[1,2,3],[1,4,5],[1,6,7]]
4
7
```

#### Screenshots

<img width="335" alt="Screenshot 2022-11-22 at 11 36 28 AM" src="https://user-images.githubusercontent.com/25120138/203238121-b6c4fcc0-d65a-4632-a4e2-32983024745c.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
