### ISSUE TITLE
Missing Test Case - 227. Basic Calculator II

### ISSUE THREAD

**Issue by rhythm-design** [LeetCode-Feedback/LeetCode-Feedback#10007]
#### Your LeetCode username
rhythm_varshney

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The sample 1ms solution listed was incorrect. The base case mentioned was wrong in context to the question but the solution is still accepting.  After decoding the code, I made a testcase which gives wrong answer on that 1ms submission on leetcode. 

#### Code you used for Submit/Run operation

```
class Solution {
    public int calculate(String s) {
      if (s.length() >= 209079)
			return 199;

		int answer = 0;
		char sign = '+';
		int[] stack = new int[s.length()];
		int top = -1, currNum = 0;

		for (int i = 0; i < s.length(); i++) {
			char ch = s.charAt(i);
			if (ch >= '0') {
				currNum = currNum * 10 - '0' + ch;
			}
			if (i == s.length() - 1 || (ch < '0' && ch != ' ')) {
				if (sign == '+') {
					stack[++top] = currNum;
				} else if (sign == '-') {
					stack[++top] = -currNum;
				} else {
					int temp = (sign == '*') ? stack[top] * currNum : stack[top] / currNum;
					stack[top] = temp;
				}
				currNum = 0;
				sign = ch;
			}
		}
		while (top != -1) {
			answer += stack[top--];
		}
		return answer;
	
	
    }
}
```

#### Language used for code
JAVA

#### Expected behavior
Answer should be 2 but due to the basecase it is coming 199.

#### Screenshots
![image](https://user-images.githubusercontent.com/56234578/203314104-42414b7e-a417-482c-93f1-5c7a54c0835d.png)

#### Additional context
I am adding a .txt file for the failed testcase below-
[rhythm.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/10067353/rhythm.txt)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
