### ISSUE TITLE
Question not well defined - 1729. Find Followers Count

### ISSUE THREAD

**Issue by zetaraku** [LeetCode-Feedback/LeetCode-Feedback#10006]
#### Your LeetCode username

zetaraku

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The question requires the result table ordered by `user_id` but doesn't specify ascending or descending.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
