### ISSUE TITLE
User clicks on the 'Solution' button should open a new tab/window.

### ISSUE THREAD

**Issue by JimmyCheng** [LeetCode-Feedback/LeetCode-Feedback#1000]
#### Solution
- [ ] Question
- [ ] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots here:
![Screen Shot 2020-09-13 at 4 14 42 pm](https://user-images.githubusercontent.com/1861821/93011740-43f59680-f5dc-11ea-99ce-8d7c0fa82a82.png)

**Comment by lc-kay** [comment]
Hi @JimmyCheng  ,
Thank you for your time. Upon investigating this issue, we found this issue to be non-content-related (the issue stems from an origin away from the content on this problem). A kind reminder that we opened the GitHub channel only for content issues, therefore, please submit this technical issue through our [help desk](https://support.leetcode.com/hc/en-us/requests/new). Thank you so much for using LeetCode!
