### ISSUE TITLE
Missing Test Case - 1877. Minimize Maximum Pair Sum in Array

### ISSUE THREAD

**Issue by dhawalpatle** [LeetCode-Feedback/LeetCode-Feedback#10005]
class Solution:
    def minPairSum(self, nums: List[int]) -> int:
        nums.sort()
        r = len(nums)-1
        ans = 0
        for i in range(len(nums)//2):
            ans = max(ans,(nums[i]+nums[r]))
            r-=1
        return ans

**Comment by dhawalpatle** [comment]
just tried to solve in easy way

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to update the problem.  We appreciate your support!
