### ISSUE TITLE
Optimization for Leetcode 139, Approach 3

### ISSUE THREAD

**Issue by BillyHub** [LeetCode-Feedback/LeetCode-Feedback#10000]
Approach 3 can be further optimized by the standard BFS visiting rule in the Algorithm book as following (you don't have to wait until visiting all the neighboring nodes to mark the current front queue node as visited by BLACK. Instead, visited marked by GREY will be good enough.)):

class Solution {
public:
    bool wordBreak(string s, vector<string>& wordDict) {
        set<string> word_set(wordDict.begin(), wordDict.end());
        queue<int> q;
        vector<bool> visited(s.length(), false);
        q.push(0);
        visited[0] = true;

        while (!q.empty()) {
            int start = q.front();
            q.pop();
            //if (visited[start]) {
              //  continue;
            //}
            for (int end = start + 1; end <= s.length(); end++) {
                if (word_set.find(s.substr(start, end - start)) !=
                    word_set.end() && visited[end] == false) {
                    visited[end] = true;
                    q.push(end);
                    if (end == s.length()) {
                        return true;
                    }
                }
            }
            //visited[start] = true;
        }
        return false;
    }
};

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to update the problem. We appreciate your support!
