### ISSUE TITLE
Add missing info in description of 216. Combination Sum III

### ISSUE THREAD

**Issue by S-W-Williams** [LeetCode-Feedback/LeetCode-Feedback#1001]
The description currently is:

> Find all possible combinations of k numbers that add up to a number n, given that only numbers from 1 to 9 can be used and each combination should be a unique set of numbers.

However the test cases in the question expect each number from 1 to 9 to be used only once. The description

> Find all possible combinations of k numbers that add up to a number n, given that only numbers from 1 to 9 can be used, each number is used exactly once, and each combination should be a unique set of numbers.

more accurately reflects what the problem is expecting.

**Comment by lc-kay** [comment]
Hi @S-W-Williams 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @S-W-Williams 
Thank you for your time. We've used your feedback to update the problem. Please submit your username so your LeetCode account can receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by S-W-Williams** [comment]
Hi, my LeetCode profile is https://leetcode.com/shwne/

Thanks!

**Comment by lc-kay** [comment]
Hi @S-W-Williams 
Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
