### ISSUE TITLE
Typo/Mispelling on Binary Search Template III Explore Card

### ISSUE THREAD

**Issue by ericskao** [LeetCode-Feedback/LeetCode-Feedback#10012]
https://leetcode.com/explore/learn/card/binary-search/135/template-iii/936/

#### Your LeetCode username
ericskao

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

Guarantees is mispelled as Gurantees (4th bullet in Key Attributes)
`Gurantees Search Space is at least 3 in size at each step`
Link: https://leetcode.com/explore/learn/card/binary-search/135/template-iii/936/

#### Expected behavior

Should be replaced with "Guarantees"

#### Screenshots

<img width="787" alt="Screen Shot 2022-11-22 at 12 51 32 PM" src="https://user-images.githubusercontent.com/7784705/203418782-75d4b354-74b3-4bf0-aac2-b78fbaaae853.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We will use your feedback to update the problem. We appreciate your support!
