### ISSUE TITLE
Missing Test Case - 242. Valid Anagram

### ISSUE THREAD

**Issue by Alice314159** [LeetCode-Feedback/LeetCode-Feedback#10017]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [√] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution:
    def isAnagram(self, s: str, t: str) -> bool:
        count = {}
        for i in range(len(s)):
            if s[i] in count.keys():
                count[s[i]] += 1
            else:
                count[s[i]] = 1
        
        for j in range(len(t)):
            if t[j] in count.keys():
                count[t[j]] -= 1
            else:
                return False
        
        if max(count.values()) >0 :
            return False
        else:
            return True
```

#### Language used for code
<!Python3 >

**Comment by Alice314159** [comment]
This code can pass the test

class Solution:
    def isAnagram(self, s: str, t: str) -> bool:
        count = {}
        for i in range(len(s)):
            if s[i] in count.keys():
                count[s[i]] += 1
            else:
                count[s[i]] = 1
        
        for j in range(len(t)):
            if t[j] in count.keys():
                count[t[j]] -= 1
            else:
                return False
        
        if max(count.values()) >0 :
            return False
        else:
            return True

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
