### ISSUE TITLE
135. Candy. Solution content error

### ISSUE THREAD

**Issue by czmud** [LeetCode-Feedback/LeetCode-Feedback#10018]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### N/A

```
```

#### Red text for approach 2
<img width="755" alt="Screen Shot 2022-11-23 at 09 19 24" src="https://user-images.githubusercontent.com/91854538/203582987-cf69a166-d7e4-4f12-9306-bebbb8824685.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, this issue only happens on the new vision and our developer team already noticed it.
Please revert back to old vision temporarily.
Thank you.
