### ISSUE TITLE
1053. Previous Permutation With One Swap

### ISSUE THREAD

**Issue by jdrobins2000** [LeetCode-Feedback/LeetCode-Feedback#10020]
#### Your LeetCode username
jdrobins2000

#### Category of the bug
- [x ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
I believe that at the very least, the question is not specified sufficiently clearly. I could be mistaken, but I am having trouble understanding how the results expected are consistent with what the question describes. For instance, for a test case of [10,9] the response expected is [9,10]. How is [9,10] lexicographically smaller than [10,9]? It is numerically smaller, but 9 is lexicographically larger than 10.

Let's just start there first. Beyond that, it doesn't make it clear how to handle numbers greater than a single digit. For instance, for the case:
[7,6,75]
Is the correct answer [6,7,75], based on a per-element comparison, or is it [75,6,7] based on a concatenation of all elements? (That is, "7567" < "7675")

#### Code you used for Submit/Run operation
This is what was verified as correct, not what I think solves the question as asked. Notice I am using numeric comparison operators, not lexicographic.

```
class Solution {
    public int[] prevPermOpt1(int[] arr) {
        int len = arr.length;
        
        for (int i=len-2; i>=0; i--) {
            int k=-1;
            for (int j=i+1; j<len; j++) {
                if ( (k == -1 || arr[j] > arr[k])
                     && arr[j] < arr[i] ) {
                    k = j;
                }
            }
            if (k != -1) {
                int t = arr[i];
                arr[i] = arr[k];
                arr[k] = t;
                return arr;
            }
        }
        
        return arr;        
    }
    
}
```

#### Language used for code

Java

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to Added the definition of lexicographically smaller array as a bubble. We appreciate your support!
