### ISSUE TITLE
907. Sum of Subarray Minimums

### ISSUE THREAD

**Issue by allan-init** [LeetCode-Feedback/LeetCode-Feedback#10028]
#### Your LeetCode username

allan-init

#### Category of the bug
- [ ] Question
- [ X ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In Approach 1. there is an issue at the line 16 of the Java solution, please replace ` i === arr.length` in the `while` loop by ` i == arr.length` as `===` is not defined in Java.

https://leetcode.com/problems/sum-of-subarray-minimums

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

Java

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
