### ISSUE TITLE
79. 单词搜索(测试用例输出错误)

### ISSUE THREAD

**Issue by mukangt** [LeetCode-Feedback/LeetCode-Feedback#1002]
** Bug 类型**
- [ ] 题目
给定一个二维网格和一个单词，找出该单词是否存在于网格中。

单词必须按照字母顺序，通过相邻的单元格内的字母构成，其中“相邻”单元格是那些水平相邻或垂直相邻的单元格。同一个单元格内的字母不允许被重复使用。

- [ ] 题解
输入：
[["F","Y","C","E","N","R","D"],["K","L","N","F","I","N","U"],["A","A","A","R","A","H","R"],["N","D","K","L","P","N","E"],["A","L","A","N","S","A","P"],["O","O","G","O","T","P","N"],["H","P","O","L","A","N","O"]]
"poland"
输出：
true
预期：
false

- [ ] 编程语言
python

**描述**
poland为什么是false？
(6, 1) -> (5, 1) -> (4, 1) -> (4, 0) -> (3, 0)-> (3, 1)

**你使用的语言**
python

**你提交或者运行的代码**
```
class Solution:
    def exist(self, board: List[List[str]], word: str) -> bool:
        import collections
        directions = [(-1, 0), (1, 0), (0, -1), (0, 1)]
        visited = collections.defaultdict(int)
        i_max, j_max = len(board), len(board[0])
        l_word = len(word)

        def find(i, j, k):
            if k == l_word:
                return True
            for d in directions:
                tmp_i, tmp_j = i + d[0], j + d[1]
                if (0 <= tmp_i < i_max)  and (0 <= tmp_j < j_max):
                    if board[tmp_i][tmp_j].upper() == word[k].upper() and visited[(tmp_i, tmp_j)] != 1:
                        visited[(tmp_i, tmp_j)] = 1
                        if not find(tmp_i, tmp_j, k+1):
                            visited[(tmp_i, tmp_j)] = 0
                        else:
                            return True
            return False
        
        k = 0
        for i, line in enumerate(board):
            for j, c in enumerate(line):
                if board[i][j].upper() == word[k].upper():
                    visited[(i, j)] = 1
                    if not find(i, j, k + 1): 
                        visited[(i, j)] = 0
                    else:
                        print(visited)
                        return True
        return False
```

**期望行为**
True

**屏幕截图**
![image](https://user-images.githubusercontent.com/40862975/93020407-71a80300-f60f-11ea-80ca-453f2b9fb9e7.png)

**额外的上下文**
79. 单词搜索

**Comment by feiceh** [comment]
建议再仔细调试一下代码，希望这篇内容有帮助：https://leetcode.kf5.com/hc/kb/article/1194344 。后续刷题学习中遇到困难，可通过阅读「题解」解决做题中的一些困惑，也可至 力扣圈子 进行题目交流，以获得更好的支持哟～

**Comment by mukangt** [comment]
不太明白啊 我的问题是：在输入中，按照这个坐标：(6, 1) -> (5, 1) -> (4, 1) -> (4, 0) -> (3, 0)-> (3, 1)， poland是可以找到的，难道是我的寻找方式不对么？
