### ISSUE TITLE
Possible typo in the Hash table theory

### ISSUE THREAD

**Issue by piskov** [LeetCode-Feedback/LeetCode-Feedback#10021]
#### Your LeetCode username
piskov

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Possbile typo in the hash function [description table](https://leetcode.com/explore/learn/card/hash-table/182/practical-applications/1110/): compare 3rd and 4th rows. Either number of buckets or size of the array for the last case is wrong (why up to 9th power x<sub>9</sub> × 2<sup>9</sup> in the third but only 4th power x<sub>4</sub> × 4<sup>4</sup> in the last line if both array sizes < 10)

#### Code you used for Submit/Run operation

```
// not applicable
```

#### Screenshots

<img width="760" alt="screen-shot-2018-05-04-at-145454" src="https://user-images.githubusercontent.com/4349021/203711765-1a7aecdd-e78a-4fa2-a653-b395ce8f212e.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The last row states that the numbers are in the range of [0, 3]. If all numbers are 3, then the sum will be 3 * (4^0 + 4^1 + ... + 4^4) which is just within the bound of 1024. The table is correct.  We appreciate your support!
