### ISSUE TITLE
Missing Test Case - 66. Plus One  

### ISSUE THREAD

**Issue by anhaddahat** [LeetCode-Feedback/LeetCode-Feedback#10024]
#### Your LeetCode username
Anhad18

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```

class Solution {
    public int[] plusOne(int[] digits) {
       for(int i=digits.length-1;i>=0;i--){
           if(digits[i]!=9){
               digits[i]++;
               break;
           }else{
               digits[i]=0;
           }
        }
           if(digits[0]==0){
               int[] arr = new int[digits.length+1];
               arr[0]=1;
               return arr;
           }
           return digits;
    }
}

```

#### Language used for code
java

#### Expected behavior
what if array is = [9,9,9] 
how would our if(digits[0]==0) statement add rest of the elements from digits to the new array?

**Comment by anhaddahat** [comment]
what if input array digits is = [9,9,9]

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The test case and similar test cases are already in the file. We appreciate your support!
