### ISSUE TITLE
WrongTest Case - 1. Two Sum

### ISSUE THREAD

**Issue by adrixdax** [LeetCode-Feedback/LeetCode-Feedback#10022]
#### Category of the bug
- [ ] Question
- [ X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Additional context

<img width="947" alt="bug" src="https://user-images.githubusercontent.com/47791835/203748087-45bc8241-6e06-4b0b-b507-d3a14e4c7761.png">
<img width="573" alt="bug2" src="https://user-images.githubusercontent.com/47791835/203748095-03a40cb8-2888-48a9-a26b-c28586fe0c2b.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
