### ISSUE TITLE
Missing Test Case - 868. Binary Gap

### ISSUE THREAD

**Issue by Ashank-Dsouza** [LeetCode-Feedback/LeetCode-Feedback#10023]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

This problem is a window slider problem in addition to bit-manipulation. 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!
