### ISSUE TITLE
Missing Test Case - 1235. Maximum Profit in Job Scheduling

### ISSUE THREAD

**Issue by aospiridonov** [LeetCode-Feedback/LeetCode-Feedback#10037]
#### Your LeetCode username

aospiridonov

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Time Limit Exceeded (24 / 30 test cases passed.)

#### Code you used for Submit/Run operation

```
import 'dart:collection';

class Solution {
  int jobScheduling(List<int> startTime, List<int> endTime, List<int> profit) {
    int n = startTime.length;
    final jobs = List<List<int>>.generate(n, (_) => <int>[0, 0, 0]);
    for (int i = 0; i < n; i++) {
      jobs[i][0] = startTime[i];
      jobs[i][1] = endTime[i];
      jobs[i][2] = profit[i];
    }
    jobs.sort((a, b) => a[1] - b[1]);
    final dp = SplayTreeMap<int, int>();
    dp[0] = 0;
    for (final job in jobs) {
      int current = (dp[job[0]] ?? dp[dp.lastKeyBefore(job[0])] ?? 0) + job[2];
      if (current > dp.values.last) {
        dp[job[1]] = current;
      }
    }
    return dp.values.last;
  }
}
```

#### Language used for code

Dart

#### Expected behavior

Increase time limits for dart or fix a bug.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by ManuH68** [comment]
Others have posted valid Dart solutions, which means your code is not enough optimized.
