### ISSUE TITLE
[Official Solution Typo] 907. Sum of Subarray Minimums

### ISSUE THREAD

**Issue by BrandNewLifeJackie26** [LeetCode-Feedback/LeetCode-Feedback#10031]
#### Your LeetCode username
JackieWDo

#### Category of the bug
- [ ] Solution

#### Description of the bug

There is a typo in Java implementation for Approach 1, Line 16
```
while (!stack.empty() && (i === arr.length || arr[stack.peek()] >= arr[i])) {
```
should be replaced by
```
while (!stack.empty() && (i == arr.length || arr[stack.peek()] >= arr[i])) {
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.. We appreciate your support!
