### ISSUE TITLE
Poor description - 976. Largest Perimeter Triangle

### ISSUE THREAD

**Issue by Lorenzobattistela** [LeetCode-Feedback/LeetCode-Feedback#10032]
#### Your LeetCode username
Lorenzobattistela

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The problem 976 is described as:
> Given an integer array nums, return the largest perimeter of a triangle with a non-zero area, formed from three of these lengths. If it is impossible to form any triangle of a non-zero area, return 0.

And then, sample examples and outputs are given. But, as a user, the description of the problem is not this clear. For example:
> Example 1:
```
Input: nums = [2,1,2]
Output: 5
```
Why is the output five?
I understand why is it five, but for beginner users or someone who does not understand, it may be unclear.

#### Expected behavior
Clear explanation of why the output is X, given an Y operation.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!

**Comment by Lorenzobattistela** [comment]
Thank you for looking into it! Love leetcode, congrats
