### ISSUE TITLE
Missing Test Case - 1028. Recover a Tree From Preorder Traversal

### ISSUE THREAD

**Issue by Migalhinha** [LeetCode-Feedback/LeetCode-Feedback#10038]
#### Your LeetCode username

L337Migalhinha

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ #] Missing Test Cases 

#### Description of the bug

There is no test case were it verifies if the code handles correctly in the case there are more than two numbers on the same level (example:"1-2-3-4").

#### Code you used for Submit/Run operation

```
/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     struct TreeNode *left;
 *     struct TreeNode *right;
 * };
 */
 struct TreeNode* criar(int val){
     struct TreeNode* por_inserir =(struct TreeNode*)malloc(sizeof(struct TreeNode));
     por_inserir->left=0;
     por_inserir->right=0;
     por_inserir->val=val;
     return por_inserir;
 }
struct TreeNode* inserir(struct TreeNode* root,int *i,int j,char * traversal){
struct TreeNode* novo=criar(0);
while(traversal[*i]!='\0'){
    int val=0;
    for((*i);traversal[(*i)]>='0';(*i)++){
        val=val*10+traversal[*i]-'0';
    }
    novo->val=val;
    int temp=(*i);
    while(traversal[temp]=='-') temp++;
    if(temp-(*i)<j) return novo;
    if(novo->left==0){
        (*i)=temp;
        novo->left=inserir(novo,i,j+1,traversal);
    }
    temp=*i;
while(traversal[temp]=='-') temp++;
if(temp-(*i)<j) return novo;
*i=temp;
novo->right=inserir(novo,i,j+1,traversal);
return novo;
}
return novo;
}
struct TreeNode* recoverFromPreorder(char * traversal){
        int val=0,tamanho=strlen(traversal),i=0;
        while(traversal[i]=='-') i++;
        struct TreeNode* root;
        root=inserir(root,&i,1,traversal);
        return root;
}
```

#### Language used for code

C

#### Expected behavior

I think thee expected outcome should be replacing the value on right if it repeates (example: input:"1-2-3-4", output:[1,2,4]).
example 2: input"1-2-3--4-5" output:[1,2,5].

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to check the problem. 
The input is Invalid, we added a message to show that.
We appreciate your support!
