### ISSUE TITLE
Incorrect space complexity - 977. Squares of a Sorted Array

### ISSUE THREAD

**Issue by denis-stafichuk-parsable** [LeetCode-Feedback/LeetCode-Feedback#10042]
#### Your LeetCode username
sydym6

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
https://leetcode.com/problems/squares-of-a-sorted-array/solution/

>In Java, the [Arrays.sort()](https://docs.oracle.com/javase/8/docs/api/java/util/Arrays.html#sort-byte:A-) is implemented as a variant of quicksort algorithm whose space complexity is O(logN).

In Java, the Arrays.sort(int[]) uses a hybrid sorting algorithm that can also use merge sort [with O(n) space complexity](https://github.com/openjdk/jdk/blob/jdk-14-ga/src/java.base/share/classes/java/util/DualPivotQuicksort.java#L733) if the array is highly structured (consists of a few sorted subarrays).

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
