### ISSUE TITLE
Minor wording issue

### ISSUE THREAD

**Issue by jxjjligang** [LeetCode-Feedback/LeetCode-Feedback#10045]
It's a minor working issue in below link.
https://leetcode.com/explore/interview/card/leetcodes-interview-crash-course-data-structures-and-algorithms/712/dynamic-programming/4543/

In example 1, there is a line states as below.
  However, with the bottom up approach, we can improve the **time complexity** to O(n). 
  
I think it should be **space complexity** instead.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We will use your feedback to update the problem. We appreciate your support!
