### ISSUE TITLE
139. 单词拆分

### ISSUE THREAD

**Issue by Ijustwantyouhappy** [LeetCode-Feedback/LeetCode-Feedback#1004]
** Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
1. 题干叙述有误——**一个包含非空单词列表的字典 wordDict**，根据测试用例来看，题目想要表达的意思应当为——**一个包含单词的非空列表 wordDict**
2. 测试用例和题目不符。

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![image](https://user-images.githubusercontent.com/26211339/93041396-0269f780-f67f-11ea-80cc-4ca56b7ae05b.png)

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认的～

**Comment by feiceh** [comment]
你好，非空是修饰单词的，不是修饰列表的。当前已改为「一个包含非空单词的列表」，请知晓。

**Comment by feiceh** [comment]
你好，非空是修饰单词的，不是修饰列表的。当前已改为「一个包含非空单词的列表」，请知晓。

**Comment by Ijustwantyouhappy** [comment]
id：青菜白玉饭汤

**Comment by feiceh** [comment]
1

**Comment by Ijustwantyouhappy** [comment]
thx
