### ISSUE TITLE
Incorrect Test Case - 364. Nested List Weight Sum II

### ISSUE THREAD

**Issue by sapphire921** [LeetCode-Feedback/LeetCode-Feedback#10044]
#### Your LeetCode username

sapphire921

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

The following test case is incorrect. For the input [[1,1],2,[1,1],[[[[]]]]], since its maximum depth is 5, the correct result should be
1 * 4 + 1 * 4 + 2 * 5 + 1 * 4 + 1 * 4 = 26.
However, 26 is treated as incorrect.

Input
[[1,1],2,[1,1],[[[[]]]]]
Output
26
Expected
20

#### Code you used for Submit/Run operation

```
class Solution:
    def depthSumInverse(self, nestedList: List[NestedInteger]) -> int:
        maxDepth = self.findDepth(nestedList)
        self.res = 0
        self.dfs(0, maxDepth, nestedList)
        return self.res
        
    def findDepth(self, nestedList):
        curDepth = 1
        for nestedInteger in nestedList:
            if not nestedInteger.isInteger():
                curDepth = max(curDepth, 1 + self.findDepth(nestedInteger.getList()))
        return curDepth
    
    def dfs(self, level, maxDepth, nestedList):
        level += 1
        for nestedInteger in nestedList:
            if nestedInteger.isInteger():
                self.res += nestedInteger.getInteger() * (maxDepth - level + 1)
            else:
                self.dfs(level, maxDepth, nestedInteger.getList())
```

#### Language used for code

Python

#### Expected behavior

The expected output of the above test case should be 26.

#### Screenshots

<img width="527" alt="image" src="https://user-images.githubusercontent.com/30883783/204108301-996021e8-636c-4c2c-885b-faf666a0124e.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

**Comment by sapphire921** [comment]
I believe the answer depends on whether we treat the max depth of the input [[1,1],2,[1,1],[[[[]]]]] as 5 or 4. I think the max depth should be 5. It is obvious that the 2 has a depth of 1 and the four 1s all have a depth of 2. In this way, the empty list inside those brackets has a depth of 5.
Also all the test cases passed in May 2022 when I used the same code, but it does not work now since this particular test has been added. 
I believe it would be better if the description of the question could explain why a test case like [[1,1],2,[1,1],[[[[]]]]] is treated as having a max depth of 4 instead of 5, because for me, I still believe it has a max depth of 5.
