### ISSUE TITLE
Missing Test Case - 217. Contains Duplicate

### ISSUE THREAD

**Issue by mumtazf** [LeetCode-Feedback/LeetCode-Feedback#10041]
#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

Adding a test case for negative integers. Negative integers and positive integers should be treated differently in the case of finding duplicates. It isn't necessarily a bug, just a useful test case to help beginners think the question through more.

#### Code you used for Submit/Run operation

```{java}
class Solution {
    public boolean containsDuplicate(int[] nums) {
        //store it into a hashmap, this will have O(n)search time but will take additional space
        HashMap<Integer, Integer> numMap = new HashMap<Integer, Integer>();

        //loop through the elements
        for(int i = 0; i < nums.length; i++){
            //return false if I find the element because there should be no duplicate
            if(numMap.containsKey(Integer.valueOf(nums[i])))
                return true;
            
            numMap.put(nums[i],1);
        }
        return false;
    }
}
```

#### Language used for code
Java 

#### Expected behavior

Test case: 
Input: [-1,2,3,4,1]
Output: false

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the test case already exist.
