### ISSUE TITLE
2225. Find Players With Zero or One Losses -- Solution -- Approach 4: Counting with Array slidehsow is confusing

### ISSUE THREAD

**Issue by Khvalin** [LeetCode-Feedback/LeetCode-Feedback#10059]
#### Your LeetCode username
khvalin

#### Category of the bug
- [ ] Question
- [ +] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

1. open https://leetcode.com/problems/find-players-with-zero-or-one-losses/solution/
2. scroll to " Approach 4"
3. note that the slideshow attached is hardly relevant.

#### Expected behavior

counting sort slideshow or no slideshow at all

#### Screenshots

![image](https://user-images.githubusercontent.com/1132781/204169102-cd7402a7-e541-4f96-8be7-9da709fff88b.png)

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!
