### ISSUE TITLE
Wrong space complexity on 779. K-th Symbol in Grammar

### ISSUE THREAD

**Issue by raulbocanegra** [LeetCode-Feedback/LeetCode-Feedback#10056]
#### Your LeetCode username
user5528R

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The space complexity of Approaches 2 and 3, both recursive aren't `O(1)` because is recursion we should take into account stack space due to recursive calls. So space complexity for both cases should be `O(N)`

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. we will rewrite this article. We appreciate your support!
