### ISSUE TITLE
Missing Test Case - 1122. Relative Sort Array

### ISSUE THREAD

**Issue by liviuba** [LeetCode-Feedback/LeetCode-Feedback#10052]
#### Your LeetCode username
user6612zZ

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
A possible solution for the problem is to use custom key sorting as a "norm", where using limits in the problem statement and the choice of function (the .get default case in my code) for the case where some value X is not in arr2 becomes important.

A special edge case if we use 1000*N as a custom norm (which also fits in an int given problem limits) is when 0 is not in arr2. The norm will evaluate to 0 and not put the 0s in arr1 on the right, in sorted order, as the problem requests.

A test with 0 missing from arr2 but present in arr1 would enforce the correct choice of norm for this particular approach to a solution (1001+ instead of 1000*)

#### Code you used for Submit/Run operation
```python
class Solution:
    def relativeSortArray(self, arr1: List[int], arr2: List[int]) -> List[int]:
        arr2_map = {
            v: idx
            for idx, v in enumerate(arr2)
        }
        
        arr1.sort(
            key = lambda v: arr2_map.get(v, 1000*v)
        )
        
        return arr1
```
#### Language used for code
python3

#### Expected behavior
If 0 is not in arr2 but is in arr1, the solution above would fail, as 1000*0=0, so the 0 item for which order is not defined in arr2 would be at the left of arr1 instead of at the right, as expected.

The code above is a previous solution of mine that passed even thought it shouldn't if the suggested test case existed.

#### Additional context
The suggested testcase would only catch one particular case of one particular solution approach, but still it would help enforce correctess of the solution.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
