### ISSUE TITLE
Missing Test Case - 2352. Equal Row and Column Pairs

### ISSUE THREAD

**Issue by silev** [LeetCode-Feedback/LeetCode-Feedback#10053]
#### Your LeetCode username
stdoe

#### Category of the bug
- Missing Test Cases 

#### Description of the bug

Problem 2352 - https://leetcode.com/problems/equal-row-and-column-pairs/description/

Some invalid solutions are currently being accepted. I am proposing adding test cases to catch and invalidate those solutions.

You can see by browsing through the fastest (Java) solutions that nearly all of them store arrays in a HashMap, with the key being generated by calling `Arrays.hashcode()`. This hash function does not uniquely define an array and we can easily force collisions to invalidate those solutions. A simple counterexample is provided below.

#### Code you used for Submit/Run operation
As an example, here is one of the top solutions with a runtime of 6ms, which we can break with our specific input:

```
[[2, 1], [3, 32]]
```

```
class Solution {
    public int equalPairs(int[][] grid) {
        
        HashMap<Integer, Integer> columnMap = new HashMap<>();
        int n = grid.length;
        int[] columns = new int[n];
        int pairs = 0;

        for (int column = 0; column < n; column++) {
            for (int row = 0; row < n; row++) {
                columns[row] = grid[row][column];
            }

            int hashCode = Arrays.hashCode(columns);
            columnMap.put(hashCode, columnMap.getOrDefault(hashCode, 0) + 1);
        }

        for (int[] row : grid) {
            Integer matches = columnMap.get(Arrays.hashCode(row));

            if (matches != null) {
                pairs += matches;
            }
        }

        return pairs;
    }
}
/*Time: O(n)
Space: O(n)*/
```

#### Language used for code
Java

#### Expected behavior
Expected answer is 0. Actual answer is 1.
A hash collision is forced for arrays `[2, 1]` and `[1, 32]`. Therefore, the code incorrectly assumes they are the same array.

#### Screenshots
![image](https://user-images.githubusercontent.com/27373672/204138735-d91ce7f0-b02a-4b84-b114-0af846ffa063.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
