### ISSUE TITLE
Missing test cases - 594. Longest Harmonious Subsequence

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1005]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

594. Longest Harmonious Subsequence
https://leetcode.com/problems/longest-harmonious-subsequence/

At https://leetcode.com/problems/longest-harmonious-subsequence/discuss/521252/hashmap-javascript-solution-80ms/696179
And https://puu.sh/GsvxH/de091dbc72.png

We can see below code.

The code fails the below tests:

		input   [-3,-1,-1,-1,-3,-2]
		expect  4
		actual  3
		input   [-3,-1,-1,-3,-1,-2]
		expect  4
		actual  3
		input   [-3,-1,-3,-1,-1,-2]
		expect  4
		actual  3
		input   [-3,-3,-1,-1,-1,-2]
		expect  4
		actual  3
		input   [1,1,1,1,1,1,1,1,0]
		expect  9
		actual  0
		input   [1,1,1,1,1,1,1,1,1,0]
		expect  10
		actual  0

Above test are failing possibly due to "-1" in the below line:

    for (let i = 0; i < nums.length - 1; i++) {

Please add above tests.

#### Code you used for Submit/Run operation

```

var findLHS = function(nums) {
  let maxLength = 0;
  let map = new Map();
  
  for (let i = 0; i < nums.length; i++) {
	if (map.has(nums[i])) map.set(nums[i], map.get(nums[i]) + 1);
	if (!map.has(nums[i])) map.set(nums[i], 1);
  }
  
  for (let i = 0; i < nums.length - 1; i++) {
	if (map.get(nums[i]) + map.get(nums[i] + 1) > maxLength) maxLength = map.get(nums[i]) + map.get(nums[i] + 1);
  }
  
  return maxLength;
};

```

#### Language used for code
JS

#### Expected behavior

A good solution should test all kinds of tests.
Please add above tests.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
