### ISSUE TITLE
Missing Test Case - 88. Merge Sorted Array

### ISSUE THREAD

**Issue by Hugh-Shen** [LeetCode-Feedback/LeetCode-Feedback#10062]
leetcode 88题， 合并两个有序数组

/**
 * @param {number[]} nums1
 * @param {number} m
 * @param {number[]} nums2
 * @param {number} n
 * @return {void} Do not return anything, modify nums1 in-place instead.
 */
var merge = function(nums1, m, nums2, n) {
    if (m <= 0 && n <= 0) return []

    return nums1.slice(0, m).concat(nums2.slice(0, n)).sort((a, b) => a - b)
};

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!
