### ISSUE TITLE
482. 密钥格式化

### ISSUE THREAD

**Issue by liuyunbin** [LeetCode-Feedback/LeetCode-Feedback#1006]
**Bug 类型**
- [X] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
题目 [482. 密钥格式化](https://leetcode-cn.com/problems/license-key-formatting) 描述不清，按照题目，我可以把所有的 `-` 字符，转换为大写字母后，直接作为一组，提交结果，比如：

对于示例一：

输入：S = "5F3Z-2e-9-w", K = 4
输出："5F3Z-2E9W"

我的结果："5F3Z2E9W" 也是合法的，因为题目并未要求 第一组的元素个数小于等于 k

所以，题目应该加上要求第一组的元素个数小于等于 k

**Comment by feiceh** [comment]
感谢反馈，当前更新了第一个分组可以短于 K 的描述，请知晓。

**Comment by liuyunbin** [comment]
还是不对
> 第一个分组包含的字符个数可以小于 K

应该是：
第一个分组包含的字符个数必须小于等于 K

**Comment by feiceh** [comment]
其实在这个上下文中内容含义差不多，后面语气更强烈。目前已经替换翻译。
