### ISSUE TITLE
Missing Test Case - 1098. Unpopular Books

### ISSUE THREAD

**Issue by iamhassaan** [LeetCode-Feedback/LeetCode-Feedback#10064]
1098. Unpopular Books

Description is unclear. Users are saying: 
"please update the explanation of "last year" as within the last 365 days. I was thinking orders in year 2018 as 1 year before 2019."

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to update the problem.  We appreciate your support!
