### ISSUE TITLE
28. Find the Index of the First Occurrence in a String

### ISSUE THREAD

**Issue by Guan0923** [LeetCode-Feedback/LeetCode-Feedback#10065]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名
15092480901

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
描述你遇到的 bug

**你使用的语言**
C++

**你提交或者运行的代码**
```
void get_next(char *s, int n) {
  next[0] = 0;
  for (int i = 1; i < n; ++i) {
    if (s[i] == s[next[i - 1]])
      next[i] = next[i - 1] + 1;
    else {
      int t = next[i - 1];
      while (t && s[i] != s[t]) {
        t = next[t - 1];
      }
      next[i] = s[i] == s[t] ? t + 1 : 0;
    }
  }
}
```

**期望行为**
建议将next数组作为结果传参

**屏幕截图**
![image](https://user-images.githubusercontent.com/79012232/204266777-d086530f-d42a-4e23-9ea9-381c5b1140a1.png)

**额外的上下文**
考察点毫无意义

**Comment by feiceh** [comment]
您好，在与相关团队核实后：题目没有问题，暂不处理。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
