### ISSUE TITLE
Extra Charactere '\' in Approach 1 of find-players-with-zero-or-one-losses

### ISSUE THREAD

**Issue by skkedia** [LeetCode-Feedback/LeetCode-Feedback#10060]
#### Category of the bug
- [ ] Solution- There is an extra character '\\\' in the JAVA solution of Approach 1 line 3 of the LC question(2225)

#### Description of the bug
There is an extra character '\\\' in the JAVA solution of Approach 1 line 3 of the LC question(2225)

#### Language used for code
JAVA

#### Screenshots
<img width="274" alt="image" src="https://user-images.githubusercontent.com/41532292/204178508-cc3af994-ef68-4e7e-a5fc-a7f3c52c311e.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!

**Comment by skkedia** [comment]
@LC-Pam does this not qualify for LC coins under issues reported?
