### ISSUE TITLE
Missing testcase for 1027. Longest Arithmetic Subsequence

### ISSUE THREAD

**Issue by SvetlinZarev** [LeetCode-Feedback/LeetCode-Feedback#10074]
#### Your LeetCode username
svetlin_zarev

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
Missing testcase for [1027. Longest Arithmetic Subsequence](https://leetcode.com/problems/longest-arithmetic-subsequence/). The judge accepted a solution that returned invalid value for a testcase of length less than 3, but the solution is rejected when manually testing with a custom testcase of length 2

#### Code you used for Submit/Run operation
[Accepted submission](https://leetcode.com/submissions/detail/851113546/)

```rust
impl Solution {
    pub fn longest_arith_seq_length(nums: Vec<i32>) -> i32 {
        longest_arith_seq_length(nums)
    }
}

use std::collections::{HashMap, HashSet};

pub fn longest_arith_seq_length(nums: impl AsRef<[i32]>) -> i32 {
    let nums = nums.as_ref();
    if nums.len() < 3 {
        return 0;
    }

    let mut cache = HashMap::new();
    let mut answer = 0;

    for i in 0..nums.len() - 2 {
        for j in i + 1..nums.len() - 1 {
            let diff = nums[j] - nums[i];
            let len = dfs(&mut cache, nums, diff, j);

            answer = answer.max(len);
        }
    }
    
    // add the numbers corresponding to 'i' and 'j'
    answer + 2

}

fn dfs(cache: &mut HashMap<(usize, i32), i32>, nums: &[i32], diff: i32, pos: usize) -> i32 {
    if let Some(&len) = cache.get(&(pos, diff)){
        return len;
    }

    let mut len = 0;
    for prev in pos + 1..nums.len(){
        if nums[prev] - nums[pos] == diff{
            len = len.max(1 + dfs(cache, nums, diff, prev));
        }
    }

    cache.insert((pos, diff), len);
    len
}
```

#### Language used for code
Rust

#### Expected behavior

The submission should have been rejected with a failed testcase

#### Screenshots

![Screenshot from 2022-11-28 19-04-40](https://user-images.githubusercontent.com/1794797/204338400-e99eae41-c4d6-4f17-9568-6d70e1c85516.png)
![Screenshot from 2022-11-28 19-05-24](https://user-images.githubusercontent.com/1794797/204338404-a5711693-b45b-4de9-8eb3-e2237d932c6d.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
