### ISSUE TITLE
Explore Prefix Sum

### ISSUE THREAD

**Issue by SmokeShine** [LeetCode-Feedback/LeetCode-Feedback#10073]
#### Your LeetCode username
SmokeShine

#### Category of the bug
- [ ] Question
- [ x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Given an integer array nums,

prefix = [nums[0]]
for i in [1, len(nums) - 1]:
    prefix.append(nums[i] + prefix[prefix.length - 1])

This is O(n^2) and not O(n) as we need to loop to find the array length without any counter.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem page. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
