### ISSUE TITLE
Typo in description - 1381. Design a Stack With Increment Operation

### ISSUE THREAD

**Issue by xelplogoog** [LeetCode-Feedback/LeetCode-Feedback#10077]
#### Your LeetCode username

c4tdog

#### Category of the bug
- [ ] Question

#### Description of the bug

There is a typo in the description
customStack.increment(2, 100); // stack becomes [201, 202, 103]
customStack.pop(); // return 103 --> Return top of the stack 103, stack becomes [201, 202]
customStack.pop(); // return 202 --> Return top of the stack **102**, stack becomes [201] <- instead of 102 should be 202
customStack.pop(); // return 201 --> Return top of the stack **101**, stack becomes [] <- instead of 101 should be 201

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
