### ISSUE TITLE
Missing corner Test case - 57 Insert Interval

### ISSUE THREAD

**Issue by julia-dizhak** [LeetCode-Feedback/LeetCode-Feedback#1007]
#### Your LeetCode username
julia-dizhak

#### Category of the bug
- [ ] Question

#### Description of the bug

- Question 57. Insert Interval
https://leetcode.com/problems/insert-interval/
Lacking one corner test case, then `newInterval` is equal to an empty array, for example, `input is [[1,2]], []`
With given input I have a next error message `Run Code Status: Invalid Testcase`, but with solution below
the test should be passed.

#### Code you used for Submit/Run operation
This solution should pass for corner case when `newInterval is equal to []`;

```
var insert = function(intervals, newInterval) {
  if (newInterval === null || newInterval.length < 1) {
    return intervals;
  }
    
  let size = intervals.length;
  let index = 0;
  let res = [];
    
  while(index < size && intervals[index][1] < newInterval[0]) {
    res.push(intervals[index]);
    index++;
  }

  while(index < size && intervals[index][0] <= newInterval[1]) {
    newInterval[0] = Math.min(newInterval[0], intervals[index][0]);
    newInterval[1] = Math.max(newInterval[1], intervals[index][1]);
    index++;
  }

  res.push(newInterval);
  while(index < size) {
    res.push(intervals[index]);
    index++;
  }

  return res;
};
```

#### Language used for code
Javascript

#### Expected behavior
Provided Test should pass
Run Code Status: Invalid Testcase

**Comment by lc-kay** [comment]
Hi @julia-dizhak 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @julia-dizhak 
Thank you for your time. We've added constraints to this problem and ran your test code, which returned invalid. We appreciate your support!

**Comment by julia-dizhak** [comment]
I saw it, you added constraints `newInterval.length == 2`
great, thanks
