### ISSUE TITLE
WRONG Solution Slide in 2225. Find Players With Zero or One Losses

### ISSUE THREAD

**Issue by Frdhsn** [LeetCode-Feedback/LeetCode-Feedback#10071]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshot
![image](https://user-images.githubusercontent.com/29932258/204307710-74da72ca-2b34-4e3d-ad0d-cb94cb942ccc.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by Frdhsn** [comment]
Is it fixed? :|

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
