### ISSUE TITLE
Missing Test Case - 1528. Shuffle String

### ISSUE THREAD

**Issue by nikku9678** [LeetCode-Feedback/LeetCode-Feedback#10075]
#### Category of the bug
- [1528 ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### All the Test cases are correct but first test case i.e  s = "codeleet", indices = [4,5,6,7,0,2,1,3]  output : "leetcode" 
if you are geeting correct output we have to change the indices array i.e   indices = [4,5,6,7,0,1,2,3]  
Now we can run and compile , we get  the correct output.

#### Code you used for Submit/Run operation

```
// 1528.  Shufffle String 
class Solution {
public:
    string restoreString(string s, vector<int>& indices) {
        string ans="";

        for(int i=0; i<indices.size(); i++){
            ans+=s[indices[i]];
        }
        return ans;
    }
}; 
```

#### 

####

**Comment by stormsunshine** [comment]
The test case is correct. Please make sure you understand the requirement of this problem.

**Comment by surjendu104** [comment]
It doesn't matter  for indices = [4,5,6,7,0,2,1,3] or indices = [4,5,6,7,0,1,2,3] as in both of the position there is "e". Means at array index-1 and 2 there is "e" present. So testcase in question is correct as well as yours
