### ISSUE TITLE
209. 长度最小的子数组 

### ISSUE THREAD

**Issue by hummingg** [LeetCode-Feedback/LeetCode-Feedback#10070]
**你的 LeetCode 用户名**
hhummingg

**Bug 类型**
- [x] 题目

**描述**
进阶的描述错误
> 如果你已经实现 O(n) 时间复杂度的解法, 请尝试设计一个 O(n log(n)) 时间复杂度的解法。

**期望行为**
**O(n)**  和 **O(n log(n))**  互换顺序。

**额外的上下文**
https://leetcode.cn/problems/minimum-size-subarray-sum/description/

**Comment by stormsunshine** [comment]
没有互换顺序的理由。
