### ISSUE TITLE
[9,9,9Missing Test Case - 66. Plus One

### ISSUE THREAD

**Issue by bhism** [LeetCode-Feedback/LeetCode-Feedback#10076]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by stormsunshine** [comment]
This test case is tested in submission. Why do you think this test case is missing?
