### ISSUE TITLE
python3智能模式失效，无高级自动补全和语法检查

### ISSUE THREAD

**Issue by happtain** [LeetCode-Feedback/LeetCode-Feedback#10078]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名
123456-8fr

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [x] 编程语言
- [ ] 缺少测试用例

**描述**
会员的python3智能模式失效，无高级自动补全和语法检查

**你使用的语言**
python3

**期望行为**
描述你期望的结果
希望尽快修复

**Comment by feiceh** [comment]
感谢反馈，该问题已转给相关团队跟进，后期会持续优化。Github 仓库只用于反馈大家在本站学习过程中遇到的题目和题解问题，问题我先关闭，后续使用中有任何问题欢迎 [提交工单](https://support.leetcode-cn.com/hc/request/new/) 反馈，我们会定期更新，保障稳定和体验优化。
