### ISSUE TITLE
Missing Testcase - 2472.  Maximum Number of Non-Overlapping Palindrome Substrings

### ISSUE THREAD

**Issue by i-aka5h** [LeetCode-Feedback/LeetCode-Feedback#10080]
#### Your LeetCode username
_aka5h

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
An accepted solution failed a custom testcase

#### Code you used for Submit/Run operation

```
// 2472. Maximum Number of Non-overlapping Palindrome Substrings
class Solution {
public:
    
    bool isPalindrome(string s){
        string c=s;
        reverse(c.begin(),c.end());
        return c==s;
    }
    
    int maxPalindromes(string s, int k) {
        int n=s.size();
        long long cnt=0;
        for(int i=0;i<n;i++){
            string str;
            for(int j=i;j<n;j++){
                str+=s[j];
                if(str.size() >=k && isPalindrome(str)){
                    cnt++;
                    i=j;
                    break;
                }
                if(str.size()>k+1) break;
            }
        }
        
        
        return cnt;
    }
};
```

#### Language used for code
C++

#### Expected behavior
I expected my code to fail because it failed a custom testcase but it got accepted.
For testcase : 

"abacdadccc"
3
Expected output : 3
Actual output : 2

#### Screenshots

![image](https://user-images.githubusercontent.com/105808186/204499731-8ff210e7-6232-4fb5-8373-690c5c5f8d79.png)
![image](https://user-images.githubusercontent.com/105808186/204499914-13d67ecf-4451-476f-b153-d02ea63224f1.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
