### ISSUE TITLE
Missing Test Case - 70. Climbing Stairs

### ISSUE THREAD

**Issue by N1ULL** [LeetCode-Feedback/LeetCode-Feedback#10088]
#### Your LeetCode username

加奈绘

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The test example given by the question is too small, which leads to the use of recursive algorithm to pass the test phase, but cannot pass the formal submission. Suggest adding examples 40.

#### Code you used for Submit/Run operation

```
int climbStairs(int n)
{
    if (n == 1 || n == 2)
    {
        return n;
    }
    return climbStairs(n - 1) + climbStairs(n - 2);
}
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. It is hard to add explanations for large test cases.
Also, it is important for one to know the complexity of their solution and the constraints during the interview.
 We appreciate your support!
