### ISSUE TITLE
Missing Test Case - 1207. Unique Number of Occurrences

### ISSUE THREAD

**Issue by Murdocman17** [LeetCode-Feedback/LeetCode-Feedback#10086]
#### Your LeetCode username

Murdoc12

#### Category of the bug
- [1207.unique number ] Question
- [ ] Solution
- [ python] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
n,x,y=arr,[],[]

        n.sort()

        for i in range(1,len(n)):

            if n[i]==n[i-1]:

                x.append(n[i])

        for o in range(len(n)):

            if n[o] not in x:

                y.append(n[o])

                if len(y)>1:

                    return False

        for j in range(len(n)):

            if n[j] not in x:

                if x==[]:

                    return False

                return True

        return False
        
```

#### Language used for code

Python

#### Expected behavior

On test case:[26,2,16,16,5,5,26,2,5,20,20,5,2,20,2,2,20,2,16,20,16,17,16,2,16,20,26,16]
The number 17 is unique.But the expected is False

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code Accepted submission link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Murdocman17** [comment]
I don't get what does "The code Accepted submission link." mean.As English
is not my major and i'm new to code.

Vào 4:23, Th 5, 1 thg 12, 2022 LC_M ***@***.***> đã viết:

**Comment by LC-Pam** [comment]
After you submit your code, what is the results (Accept / Wrong Answer / Runtime Error....) that you received?
