### ISSUE TITLE
Missing Test Case - 2416. Sum of Prefix Scores of Strings

### ISSUE THREAD

**Issue by AaveshK** [LeetCode-Feedback/LeetCode-Feedback#10083]
#### Your LeetCode username
[AaveshK](https://leetcode.com/AaveshK/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Using the test case `words =  ["bfiaaaaifb","aaaaooaaaa"]` , an incorrect answer is returned by the code. But on submission, the code is accepted.

#### Code you used for Submit/Run operation

```
class Solution
{
    final int m = 1023;
    public int[] sumPrefixScores(String[] words)
    {
        HashMap<Long,Integer> map = new HashMap<>();
        for(String S : words)
        {
            char[] s = S.toCharArray();
            long hash_so_far = 0L;
            int n = s.length;
            for (int i = 0; i < n; i++)
            {
                hash_so_far = hash_so_far*m+s[i];
                map.put(hash_so_far,map.getOrDefault(hash_so_far,0)+1);
            }
        }
        int cur = 0;
        int[] ret = new int[words.length];
        for(String S : words)
        {
            char[] s = S.toCharArray();
            long hash_so_far = 0L;
            int n = s.length;
            for (int i = 0; i < n; i++)
            {
                hash_so_far = hash_so_far*m+s[i];
                ret[cur] += map.get(hash_so_far);
            }
            cur++;
        }
        return ret;
    }
}
```

#### Language used for code
Java

#### Expected behavior

The answer is supposed to be [10,10] but the code returns [11,11] and is accepted.

#### Screenshots

![image](https://user-images.githubusercontent.com/28723058/204473499-97226bcf-0b33-4c2f-abac-60efee1734dc.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
