### ISSUE TITLE
Missing test case - 1191. K-Concatenation Maximum Sum

### ISSUE THREAD

**Issue by gomathi-ganesan** [LeetCode-Feedback/LeetCode-Feedback#1008]
#### Your LeetCode username
gssg_0413

#### Category of the bug
Missing test case for Question : 1191. K-Concatenation Maximum Sum

#### Description of the bug

Test case :
 arr=[-1, -2] , k=1
Expected output should be -1.
But the current excepted output is 0.

#### Expected behavior
Expected output should be -1.
But the current excepted output is 0.

**Comment by lc-kay** [comment]
Hi @gomathi-ganesan,

Thank you for bringing this to our attention, we appreciate your effort! Can you please provide me with the code you submitted so I can verify it and run it with the test case.

**Comment by Vikas-Jethwani** [comment]
In question description it is given: "*Note that the length of the sub-array can be 0 and its sum in that case is 0.*"
Hence the correct answer is indeed 0.

**Comment by gomathi-ganesan** [comment]
Hi @lc-kay , My code got accepted. I haave no problem with submission. But I observed that for input arr=[-1,-2], k=1, the output expected by leetcode is 0. But in this case, as per the problem statement the expected output should be -1.

**Comment by gomathi-ganesan** [comment]
@Vikas-Jethwani  Thanks for the clarification. It makes sense now. Closing the issue.
