### ISSUE TITLE
Swap col and raw in Java example in 62. Unique Paths Solution

### ISSUE THREAD

**Issue by ddyacn** [LeetCode-Feedback/LeetCode-Feedback#10081]
#### Your LeetCode username
1mann

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In section **Approach 1: Dynamic Programming** there is java code example:
```java
public int uniquePaths(int m, int n) {
    int[][] d = new int[m][n];

    // some code is skipped here 

    for(int col = 1; col < m; ++col) {
      for(int row = 1; row < n; ++row) {
        d[col][row] = d[col - 1][row] + d[col][row - 1];
      }
    }
    return d[m - 1][n - 1];
  }
```
In Java the first array (in 2D array) that is accessed is going to be array[i][] which is an equivalent to traversing rows, but in the example it is opposite `d[col][row]`. It confuses, even though the logic works.

#### Code you used for Submit/Run operation
```java
public int uniquePaths(int m, int n) {
        int[][] d = new int[m][n];

        for (int[] arr : d) {
            Arrays.fill(arr, 1);
        }
        for (int row = 1; row < m; ++row) {
            for (int col = 1; col < n; ++col) {
                d[row][col] = d[row - 1][col] + d[row][col - 1];
            }
        }
        return d[m - 1][n - 1];
}
```

#### Language used for code
Java

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to check the problem, it is a bit weird but it works the exact same. We appreciate your support!
