### ISSUE TITLE
Missing Test Case - 1207. Unique Number of Occurrences

### ISSUE THREAD

**Issue by martin0327** [LeetCode-Feedback/LeetCode-Feedback#10092]
#### Your LeetCode username

martin0327

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The following code does not take into account Java long type have limited number of bits.
Whie it's not supposed to be accepted, it indeed passes all TC's as they are weak.

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean uniqueOccurrences(int[] arr) {
        
        HashMap<Integer, Integer> map = new HashMap<>();
        
        for(int i = 0; i < arr.length; ++i){
            map.put(arr[i], map.getOrDefault(arr[i], 0)+1);
        }
        
        long cnt = 0;
        int c = 0;
        for(var e : map.values()){
            cnt ^= 1L << (long)e;
            c++;
            if(Long.bitCount(cnt) != c) return false;
        }
        
        return true;
        
        
    }
}
```

#### Language used for code

Java

#### Expected behavior

It is not supposed be accepted.

#### Additional context

https://leetcode.com/submissions/detail/852337239/ 
is the accepted submission

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2]
is the TC that ensures the above code gets WA

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
