### ISSUE TITLE
Missing example test cases for binary-tree-inorder-traversal

### ISSUE THREAD

**Issue by snagaruri** [LeetCode-Feedback/LeetCode-Feedback#1009]
#### Your LeetCode username
**leet4242**

#### Category of the bug
- [ ] Question

#### Description of the bug
Hi Team,
I think [binary-tree-inorder-traversal](https://leetcode.com/problems/binary-tree-inorder-traversal/) is missing good examples from the problem's description section. The given description does not give the clarity for a case like if tree has only left brach or missed  right brach after some levels. It would be good if you add below examples for better understanding for a user. Hope this helps.

Example/Test Case 1: **Tree has only left branch**
Input: [1,2,null,4,null,7,null]
Output: [1,2,4,7]
Example/Test Case 2:  **missed  right branch after some levels**
Input: [1,2,3,4,5,null,6,7,null,null,null,null]
Output: [1,3,6,7]

**Comment by lc-kay** [comment]
Hi @snagaruri 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @snagaruri 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
