### ISSUE TITLE
Missing Test Case - 1207. Unique Number of Occurrences

### ISSUE THREAD

**Issue by deepeshgodara** [LeetCode-Feedback/LeetCode-Feedback#10094]
#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
 In question it is provided that the array length can be 1000
Let's take a case where arr contains 1000 elements and all of them are same
In that case my code should have been broken.
As I have tried accessing the location of array(ffmap check code) which is determined by the frequency of the element in the array.
as the max freq of element can be 1000 thus my code would try reaching index 1000 for array of size of 1000 which should break down.

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean uniqueOccurrences(int[] arr) {
        int fmap[] = new int [2005];
        //Create a frequency map
        for(int val:arr){
            fmap[val+1000]++;
        }
        boolean ffmap[] = new boolean [1000];
        //track whether some frequency occurred or not
        for(int i=0;i<2001;i++){
            if(fmap[i]==0)continue;
        //there should be some test case where this is broken
            if(ffmap[fmap[i]])return false;
            ffmap[fmap[i]]=true;
        }
        return true;
    }
}
```

#### Screenshots

<img width="1528" alt="image" src="https://user-images.githubusercontent.com/30095763/204866606-af2e3564-8c0d-4a74-ae55-82b9156801c8.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
