### ISSUE TITLE
Missing constraints - 693. Binary Number with Alternating Bits

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1010]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

693. Binary Number with Alternating Bits
https://leetcode.com/problems/binary-number-with-alternating-bits/

Please add constraints for this problem.

What is the range of positive `n`? Is it below 32-bit integer like below?

     1 <= n <= 2147483647

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

The problem must have un-ambiguous constraints to avoid TLE errors.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
