### ISSUE TITLE
Missing Test Case - 308. Range Sum Query 2D - Mutable

### ISSUE THREAD

**Issue by dskloet** [LeetCode-Feedback/LeetCode-Feedback#10103]
LeetCode username: dskloet

The method signature of sumRegion in C++ returns an int (signed 32 bits) but the correct result might be greater than 2^31 (up to 4,000,000,000) so it needs to be a long long.
The reference solution doesn't even show an expected value for such inputs.

Test case is attached.
[range-sum-query-2d-mutable.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/10131284/range-sum-query-2d-mutable.txt)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to Reduced the constraints. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
