### ISSUE TITLE
Missing Test Case - 1704. Determine if String Halves Are Alike

### ISSUE THREAD

**Issue by DakshHinger** [LeetCode-Feedback/LeetCode-Feedback#10107]
#### Category of the bug
- [ 1704. Determine if String Halves Are Alike ] Question 
- [ run a for loop from i=0 to i=n/2-1 for calculation of vowels in first half and a for loop for i=n/2 to n for calculation of vowels in second half ] Solution
- [ C++ ] Language
- [ Leetcode ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// 1704. Determine if String Halves Are Alike
class Solution {
public:
    bool halvesAreAlike(string s) {
      int n = s.size(); 
      int a=0;
      for (int i=0; i< n/2;i++)
      {
      if ( s[i]=='a' || s[i]=='e' ||s[i]=='i' || s[i]=='o' ||s[i]=='u' || s[i]=='A' ||s[i]=='E' || s[i]=='I' || s[i]=='O' || s[i]=='U')
      a++; 
      }
      for (int i=n/2; i< n;i++)
      {
      if ( s[i]=='a' || s[i]=='e' ||s[i]=='i' || s[i]=='o' ||s[i]=='u' || s[i]=='A' || s[i]=='E' || s[i]=='I' || s[i]=='O' || s[i]=='U')
      a--; 
      }
      if (a==0)
       return true;
       return false; 
    
    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
