### ISSUE TITLE
91. 解码方法 题目描述不清

### ISSUE THREAD

**Issue by liushuduo** [LeetCode-Feedback/LeetCode-Feedback#10117]
**你的 LeetCode 用户名**
sliu-36
sliu35@zju.edu.cn

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
题目提示为：```s``` 只包含数字，并且**可能包含前导零**。
那么对于输入```s="00012"```可以视为有三个先导零的```"12"```，应当有两种解码方式，返回结果为2，但题目所给出预期结果为0。

**你使用的语言**
python

**期望行为**
对于输入```s="00012"```可以视为有三个先导零的```"12"```，应当有两种解码方式，返回结果为2。

**屏幕截图**
<img width="712" alt="image" src="https://user-images.githubusercontent.com/39510809/205273483-51478710-02cc-422b-9327-4072f9a7e277.png">

**Comment by feiceh** [comment]
您好，在与相关团队核实后：题目中有提到（所有数字必须基于上述映射的方法， 前导 0 不能忽略），暂不处理。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
