### ISSUE TITLE
correction/optimization for approach2 in solution of 4-sumii 

### ISSUE THREAD

**Issue by Wizwizard** [LeetCode-Feedback/LeetCode-Feedback#10111]
#### Your LeetCode username

wanguo0528

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

in approach2,  performance would be better if k == n // 2.
It seems that the author made a mistake to divide the k by 2 for twice.

#### Code you used for Submit/Run operation

```
        def sum_count(lsts):
            ret = collections.Counter([0])
            for lst in lsts:
                temp = Counter()
                for a in lst:
                    for total in ret:
                        temp[total+a] += ret[total]
                ret = temp
            return ret
        
        lsts = [nums1, nums2, nums3, nums4]
        k = len(lsts)
        
        left, right = sum_count(lsts[:k//2]), sum_count(lsts[k//2:])
        return sum(left[s] * right[-s] for s in left)
```

#### Language used for code

Python

#### Expected behavior

The performance is better than the code in approach2

#### Screenshots

![image](https://user-images.githubusercontent.com/16569779/205189146-735b32d9-da81-4b99-827f-e80f939386c9.png)
![image](https://user-images.githubusercontent.com/16569779/205189174-ba098648-9aa4-4d16-b843-9a5a54fc4341.png)

#### Additional context

https://leetcode.com/problems/4sum-ii/solution/

**Comment by LC-Pam** [comment]
Thank you for your time. We will used your feedback to update the problem soon. We appreciate your support!

**Comment by Wizwizard** [comment]
> Thank you for your time. We will use your feedback to update the problem soon. We appreciate your support!
Hi LC-Pam, May I get the coin reward for my account ? I saw there will be 100 coins for "File Content Issue to Feedback Repo".  Thanks a lot. I really want to buy the T-shirt of Leetcode.
