### ISSUE TITLE
31. 下一个排列官方题解 KaTex 解析出错 

### ISSUE THREAD

**Issue by sslime336** [LeetCode-Feedback/LeetCode-Feedback#10116]
**描述**

KaTex 在 Firefox 解析出错

**屏幕截图**

![图片](https://user-images.githubusercontent.com/97684920/205256536-e25c9014-1814-45af-8b30-e74991eba291.png)

**额外的上下文**

Firefox 107.0.1 (64 位) (on Win10)

**Comment by feiceh** [comment]
感谢反馈，这个问题将会提交至负责团队跟进定位。Github 仓库只用于反馈大家在本站学习过程中遇到的题目和题解问题，问题我先关闭，后续使用中有任何问题欢迎 [提交工单](https://support.leetcode-cn.com/hc/request/new/) 反馈，我们会定期更新，保障稳定和体验优化。
