### ISSUE TITLE
Missing Test Case - 742. Closest Leaf in a Binary Tree

### ISSUE THREAD

**Issue by GwonsooLee** [LeetCode-Feedback/LeetCode-Feedback#10118]
#### Your LeetCode username

a_ck

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The first and third test cases are accepted with `-1`. It seems that the root of root node is -1 and if this node is located in k-distance, then the answer is accepted.

#### Code you used for Submit/Run operation

```
class Solution:
    def findClosestLeaf(self, root: Optional[TreeNode], k: int) -> int:
        
        ans, closest = -1, 1e9
        def found(node, dist):
            if not node:
                return
            nonlocal ans, closest
            if not node.left and not node.right and dist < closest:
                ans, closest = node.val, dist
                
            found(node.left, dist + 1)
            found(node.right, dist + 1)
        
        def dfs(node):
            if not node:
                return 0
            
            if node.val == k:
                found(node, 0)
                return 1
            
            left, right = dfs(node.left), dfs(node.right)
            
            if left:
                found(node.right, left + 1)
            elif right:
                found(node.left, right + 1)
            
            if not left and not right:
                return 0
            
            return max(left, right) + 1 
        dfs(root)
        return -1
```

#### Language used for code

Python3

#### Expected behavior

Node cannot be -1 because  the value of nodes are between 1 and 1000. So it should be failed if it returns -1.

#### Screenshots

<img width="446" alt="image" src="https://user-images.githubusercontent.com/59159138/205301154-7b53ddd0-38ac-4543-befe-849154cb1c29.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-
