### ISSUE TITLE
Missing Test Case - 1150. Check If a Number Is Majority Element in a Sorted Array

### ISSUE THREAD

**Issue by typemegan** [LeetCode-Feedback/LeetCode-Feedback#10129]
#### Your LeetCode username

lc207

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Missing Test Case: nums=[1,2,2,3], target=2
which leads to the following error solution to be accepted. 

#### Code you used for Submit/Run operation

```
func isMajorityElement(nums []int, target int) bool {
    n := len(nums)
    
    if nums[n/2] != target {
        return false
    }
    if n % 2 == 0 && nums[n/2-1] != nums[n/2] {
        return false
    }
    
    left := biSearch(nums, target, true)
    right := biSearch(nums, target, false)
    
    return (right - left + 1) > n/2
    
}


func biSearch(nums []int, target int, leftBiased bool) int {
    l, r := 0, len(nums)-1
    for l < r {
        m := l + (r - l) / 2
        if nums[m] == target {
            if leftBiased {
                r = m 
            } else {
                l = m + 1  // ❌ Wrong here, the total function needs to adjust!
            }
        } else if nums[m] > target {
            r = m - 1
        } else {
            l = m + 1
        }
    }
    
    return l
}
```

#### Language used for code

Golang

#### Expected behavior

If adds the missing test case: nums=[1,2,2,3], target=2, this solution should not be accepted when it's submitted. 

#### Screenshots

<img width="1445" alt="image" src="https://user-images.githubusercontent.com/12883950/205448877-75a589a3-af6e-4a0c-a0eb-24bcbf0981d0.png">

#### Additional context

There is something wrong with the solution concerning the Binary Search function.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
