### ISSUE TITLE
Question - 1067. Digit Count in Range

### ISSUE THREAD

**Issue by nskybytskyi** [LeetCode-Feedback/LeetCode-Feedback#10121]
#### Your LeetCode username

[nskybytskyi](https://leetcode.com/nskybytskyi/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

[1067. Digit Count in Range](https://leetcode.com/problems/digit-count-in-range/)

> Given a single-digit integer d and two integers low and **high**, return the number of times that d occurs as a digit in all integers in the inclusive range [low, **right**].

In the above, "right" should be "high".

#### Expected behavior

"Right" is changed to "high".

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
