### ISSUE TITLE
Missing Test Case - 1366. Rank Teams by Votes

### ISSUE THREAD

**Issue by SRSinha** [LeetCode-Feedback/LeetCode-Feedback#10122]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Rank Teams by Votes
class Solution:
    def rankTeams(self, votes: List[str]) -> str:
        dictt = {}
        for vote in votes:
            for i, char in enumerate(vote):
                if char not in dictt:
                    dictt[char]=[0]*len(vote)
                dictt[char][i]+=1
        votedArr=sorted(dictt.keys())
        return "".join(sorted(votedArr, key=lambda x: dictt[x], reverse=True))
```
#### Screenshots

![Screen Shot 2022-12-02 at 11 48 37 AM](https://user-images.githubusercontent.com/10219583/205343917-66c4565a-c972-47d5-938b-5b2ac5952ccd.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
