### ISSUE TITLE
Missing Test Case - 300. Longest Increasing Subsequence

### ISSUE THREAD

**Issue by ssg5428** [LeetCode-Feedback/LeetCode-Feedback#10123]
#### Your LeetCode username

sohilg002

#### Category of the bug
- [ ] Question
-  Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

This solution gave time limit exceeded and same solution got accepted later.

#### Code you used for Submit/Run operation

```
class Solution:
    def lengthOfLIS(self, nums: List[int]) -> int:
        LIS = [1] * len(nums)
        
        for i in range(len(nums)-1, -1, -1):
            for j in range(i+1, len(nums)):
                if nums[i] < nums[j]:
                    LIS[i] = max(LIS[i], LIS[j]+1)
        
        return max(LIS)
```

#### Language used for code

Python

#### Expected behavior

It's expected that this code should give a "time limit exceeded" error every time.

#### Screenshots

![image](https://user-images.githubusercontent.com/97690819/205378193-674e66f5-08ef-48d8-a977-867b7c9adec3.png)

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team.  We appreciate your support!
