### ISSUE TITLE
Missing Test Case - 451. Sort Characters By Frequency

### ISSUE THREAD

**Issue by ShivKJ** [LeetCode-Feedback/LeetCode-Feedback#10124]
#### Your LeetCode username

Username: shivkj001

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Incorrect test Case

#### Description of the bug
Question ask to sort character of string in descending order of occurrence of it in string.

So, for input
```
"loveleetcode"
```

Output,

```
"eeeelolovtcd"
```
is a valid output.

#### Code you used for Submit/Run operation
```
from collections import Counter


class Solution:
    def frequencySort(self, s: str) -> str:
        return ''.join(sorted(s, key=Counter(s).get, reverse=True))
```

#### Language used for code
Python3.10.2 (as provided by leetcode)

#### Expected behavior
<img width="273" alt="image" src="https://user-images.githubusercontent.com/17637878/205417467-7d6303a2-106f-4376-8d7b-13ba7b70ab0d.png">

**Output** does follow the expectation that character of the string should be sorted in decreasing order of their occurrence.

**Comment by JojiJoseph** [comment]
Hi @ShivKJ, In example 2, it is given that the same characters should be grouped together.
```
Input: s = "cccaaa"
Output: "aaaccc"
Explanation: Both 'c' and 'a' appear three times, so both "cccaaa" and "aaaccc" are valid answers.
Note that "cacaca" is incorrect, as the same characters must be together.
```

Nevertheless, I think they should state `same characters must be together` in the problem statement itself.

**Comment by ShivKJ** [comment]
Yes, I think problem should be made more clear.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
