### ISSUE TITLE
Missing Test Case - 1657. Determine if Two Strings Are Close

### ISSUE THREAD

**Issue by Mohit160901** [LeetCode-Feedback/LeetCode-Feedback#10120]
#### Your LeetCode username

Mohit_Hadiyal16

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

A test case is missing in Problem(1657) and its is mentioned below: 
word1 =
"aaabbbcc"
word2 =
"bbbcccaaa"

#### Code you used for Submit/Run operation

```
//Determine if Two Strings Are Close
class Solution:
    def closeStrings(self, word1: str, word2: str) -> bool:
        c1,c2=Counter(word1),Counter(word2)
        for c in c1:
            if c not in c2: return False
            elif c1[c]!=c2[c]:
                fg=False
                for i in c1:
                    if c1[i]==c2[c]:
                        fg=True
                        c1[i]=c1[c]
                        c1[c]=-1
                        break
                if not fg: return False
        return True
```

#### Language used for code

PYTHON3

#### Expected behavior

Test case is missing in hidden testcase and due to it my mycode gets accepted but it should not. 

#### Screenshots

![image](https://user-images.githubusercontent.com/99524454/205305354-e367d5ae-aa8f-4c64-9453-da2b3f55e0b3.png)

#### Additional context

Please add this test case in hidden testcases.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
