### ISSUE TITLE
Missing Test Case - 152. Maximum Product Subarray

### ISSUE THREAD

**Issue by vincemansel** [LeetCode-Feedback/LeetCode-Feedback#10132]
#### Your LeetCode username

vmanjz

#### Category of the bug
- [ x] Missing Test Cases 

#### Description of the bug

Add this as a test case:

`[-2,1,-1]`

Expected Result: 2

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by vincemansel** [comment]
Swift

func maxProduct(_ nums: [Int]) -> Int {
        var maxProduct = Int.min
        var currentMin = 1
        var currentMax = 1
        
        for num in nums {
            let newMinProduct = currentMin * num
            let newMaxProduct = currentMax * num
            
            currentMin = min(newMinProduct, newMaxProduct, num)
            currentMax = max(newMinProduct, newMaxProduct, num)
            
            maxProduct = max(currentMax, maxProduct)
        }
        
        return maxProduct
    }

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by vincemansel** [comment]
https://leetcode.com/problems/maximum-subarray/submissions/146613068/

**Comment by LC-Pam** [comment]
Thank you for your time. 
The submission link that you provided is for Problem#53
The ticket is for Problem#152
Please check it. 
We appreciate your support!

**Comment by vincemansel** [comment]
Thanks for checking. Here is the correct link:

https://leetcode.com/problems/maximum-product-subarray/submissions/854307461/
