### ISSUE TITLE
Descriptions or example are unclear or uncorrect : 2256. Minimum Average difference

### ISSUE THREAD

**Issue by hekcha** [LeetCode-Feedback/LeetCode-Feedback#10136]
#### Your LeetCode username
profesir

#### Category of the bug
- [✔] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The problem says rounded down to nearest integer so if in the first example where the index is 2 -> 17/3 = 5.6666... , so the closest integer to 5.666.. is 6 but here it uses 5 as the nearest rounded integer 

Language used for code
C++

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to check the problem.
The statement said rounded down.
There is a difference between rounding up and down. 
If you still feel confused about it , please google to see the difference.
We appreciate your support!
