### ISSUE TITLE
388. Wrong test case input

### ISSUE THREAD

**Issue by PabloLION** [LeetCode-Feedback/LeetCode-Feedback#10144]
#### Your LeetCode username
pabloyshi

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

1. normally file name CANNOT start with space ` `
2. Test case 16 used `dir\n        file.txt` instead of `dir\n\t    file.txt` (8 spaces instead of tab+4spaces)

#### Code you used for Submit/Run operation

```python
# 388. Longest Absolute File Path
class Solution:
    # this is max_sum path with pre-order traversal input
    # since it's pre-order, we have to visit all the leaves.
    # we use a stack to store length of each level
    # stack pop when depth decrease
    def lengthLongestPath(self, input: str) -> int:
        curr_len = max_len = 0
        st = []  # stack of name lengths
        for rp in input.splitlines():  # rp: relative path
            depth = rp.count("\t")
            name = rp[depth:]
            if "." in name:  # is file
                max_len = max(max_len, curr_len + len(name)) + depth
                # each `depth` results to a `\` in the path
            else:  # is folder
                if depth > len(st):
                    st.append(len(name))
                    curr_len += len(name)
                else:
                    while depth < len(st):
                        curr_len -= st.pop()
                    st.append(len(name))
                    curr_len += len(name)
        return max_len
```

#### Language used for code
Python3

#### Expected behavior
Test case 16 should not use `dir\n        file.txt` (8 spaces)
Should use `dir\n\t    file.txt` (tab+4spaces)

#### Screenshots
![image](https://user-images.githubusercontent.com/36828324/205553653-72e98fe1-0f4e-4f1f-94fa-732d3b50080f.png)

#### Additional context
None

**Comment by PabloLION** [comment]
test case 16 also wrong
![image](https://user-images.githubusercontent.com/36828324/205555111-60ae85c3-c413-49e5-9290-fc8080bd0c5e.png)

I don't know why python seems to count `    ` as a `\t` sometimes.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
