### ISSUE TITLE
1687. 从仓库到码头运输箱子 官解公式错误

### ISSUE THREAD

**Issue by MiaoHN** [LeetCode-Feedback/LeetCode-Feedback#10142]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**

[星尘](https://leetcode.cn/u/xing-chen-x/)

**Bug 类型**
- [ ] 题目
- [x] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**

[1687. 从仓库到码头运输箱子](https://leetcode.cn/problems/delivering-boxes-from-storage-to-ports/)
[官方题解](https://leetcode.cn/problems/delivering-boxes-from-storage-to-ports/solution/cong-cang-ku-dao-ma-tou-yun-shu-xiang-zi-4uya/)

官解的 $neg(i,j)$ 公式有误，正确的公式应该为：

$$
neg(i,j)=\sum_{k=i}^{j-1}\mathbb{I}(k)
$$

但是在题解中写成了：

$$
neg(i,j)=\sum_{k=i}^{j-1}\mathbb{I}(i)
$$

**屏幕截图**

![image](https://user-images.githubusercontent.com/56884132/205529091-673fa12e-f29a-46b1-a3c5-7a462dfc77dd.png)

**Comment by zuizaiqinshi** [comment]
官方已采纳您的建议，感谢您的反馈！
