### ISSUE TITLE
Missing Test Case - 2490. Circular Sentence

### ISSUE THREAD

**Issue by ozovalihasan** [LeetCode-Feedback/LeetCode-Feedback#10148]
#### Your LeetCode username
ozovalihasan

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
My solution passes all test cases. But, it shouldn't pass `"IuTiUtGGsNydmacGduehPPGksKQyT TmOraUbCcQdnZUCpGCYtGp p gG GCcRvZDRawqGKOiBSLwjIDOjdhnHiisfddYoeHqxOqkUvOEyI"`. 

#### Code you used for Submit/Run operation
```ruby
# Circular Sentence

# @param {String} sentence
# @return {Boolean}
def is_circular_sentence(sentence)
  parts = (sentence + " " + sentence[0]).scan(/.\s./)
  
  parts.each do |part|
    return false unless part[-1].eql? part[0]
  end 

  true
end
```

#### Language used for code
Ruby

#### Expected behavior
My code should fail for the test case given above.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The solution already fails after adding some test cases.  We appreciate your support!
