### ISSUE TITLE
Error Message When Submitting Too Quickly has Regressed

### ISSUE THREAD

**Issue by hvas89** [LeetCode-Feedback/LeetCode-Feedback#10141]
**Pre-requisite**
1. Signed in to leetcode with an account that doesn't have leetcode premium.

**Steps:**
1. Open any leetcode question
2. Type out some code and hit run test case
3. modify your code a bit and quickly hit the button again. (May not be necessary to modify code i guess)

**Expected Output:** Error message says something along the lines of "You have attempted to submit to quickly"

**Actual Output:** Error message says something along the lines of "You are not signed in"

**My Leetcode username/email for Points**: hiten / hitenvasnani@gmail.com

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team, meantime, please clear your history and cookies, then sign out and sign in again after you finish, we are releasing the new vision currently, so there will have some issues on the website, we will fix as soon as possible, We appreciate your support!
