### ISSUE TITLE
Sound quality is bad

### ISSUE THREAD

**Issue by ivanqwerty** [LeetCode-Feedback/LeetCode-Feedback#10140]
I bought System Design course and some videos have very bad quality of sound. For example, 'Amazon System Design' video has one.  At some point I barely can recognize words and I have to replay some chunks to understand the meaning. This is NOT what I expect when I buy the content!

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the course author. We appreciate your support!
