### ISSUE TITLE
Javascript Solution Runtime Error - 117. Populating Next Right Pointers in Each Node II

### ISSUE THREAD

**Issue by kandiana** [LeetCode-Feedback/LeetCode-Feedback#10149]
#### Your LeetCode username
kandiana ([link](https://leetcode.com/kandiana/))

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
If input tree is not empty, running Javascript code always ends up with Runtime Error:
```
Line *number of lines in submitted code + 69*  in solution.js
             throw new TypeError(__serialize__(ret) + " is not valid value for the expected return type Node");
*Error description*
```
For the code below (lines: 17 + 69 = 86) and **custom testcase input: root = [1]** error text looks like this:
```
Line 86 in solution.js
             throw new TypeError(__serialize__(ret) + " is not valid value for the expected return type Node");
             ^
TypeError: {"val":1,"left":null,"right":null,"next":null} is not valid value for the expected return type Node
    Line 86: Char 20 in solution.js (Object.<anonymous>)
    Line 16: Char 8 in runner.js (Object.runner)
    Line 18: Char 26 in solution.js (Object.<anonymous>)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```
Due to this bug it is impossible to sumbit a Javascript solution for this problem.

#### Code you used for Submit/Run operation
```
/**
 * // Definition for a Node.
 * function Node(val, left, right, next) {
 *    this.val = val === undefined ? null : val;
 *    this.left = left === undefined ? null : left;
 *    this.right = right === undefined ? null : right;
 *    this.next = next === undefined ? null : next;
 * };
 */

/**
 * @param {Node} root
 * @return {Node}
 */
var connect = function(root) {
    return root;
};
```

#### Language used for code
Javascript

#### Expected behavior
Provided code should finish running, not cause Runtime Error. 

#### Screenshots
![Error screenshot](https://i.imgur.com/DiaCwH5.png)

#### Additional context
It seems the issue existed for a while now:
[Discussion](https://leetcode.com/explore/learn/card/data-structure-tree/133/conclusion/1016/discuss/2167737/Javascript-Test-case-TypeError)

**Comment by kandiana** [comment]
I just noticed that there are several similar issues. The most popular seems to be [this one](https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/8362).

**Comment by LC-Pam** [comment]
Thank you for your time.

Sorry for the late reply.

The issue should be fixed.

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!
