### ISSUE TITLE
problem 62. Unique Paths

### ISSUE THREAD

**Issue by santanu33** [LeetCode-Feedback/LeetCode-Feedback#1014]
#### Your LeetCode username
santanu_33

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
row and column is reversed in the description 
`Above is a 7 x 3 grid. How many possible unique paths are there?`

by convention, the row number comes first then the column.
the picture in the description is  an example of 3 x 7 matrix.

#### Expected behavior
https://en.wikipedia.org/wiki/Matrix_(mathematics)
In the description, m and n was used interchangeably.

**Comment by lc-kay** [comment]
Hi @santanu33 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @santanu33 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
