### ISSUE TITLE
Wrong return value in example # 1 for Hashing - "Checking for existence" in Data Structures and Algorithms

### ISSUE THREAD

**Issue by chrisreddan** [LeetCode-Feedback/LeetCode-Feedback#10157]
Category of the bug

- [ ]     Question
- [X]     Solution
- [ ]     Language
- [ ]     Missing Test Cases

**Description of the bug**
 - Example 1 references the Two Sum problem and provides a video and solution, but the return values are in the wrong order and will not pass the actual Two Sum tests. The correct ordering should be `return new int[] { dic.get(complement), i };`. Both the video and solution appear to have the wrong ordering. https://leetcode.com/explore/interview/card/leetcodes-interview-crash-course-data-structures-and-algorithms/705/hashing/4511/

**Code you used for Submit/Run operation
Language used for code**
- Java & Python

**Expected behavior**
**Screenshots**
![image](https://user-images.githubusercontent.com/66126514/205744261-260015e0-2c01-4457-8a62-ef5c5ee52634.png)

**Additional context**

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to check the problem. 

This ticket is invalid . The problem description says "You can return the answer in any order."

We appreciate your support!
