### ISSUE TITLE
Wrong Test Case - 1476. Subrectangle Queries

### ISSUE THREAD

**Issue by Dhakar2003** [LeetCode-Feedback/LeetCode-Feedback#10154]
The test case which i found wrong is-
["SubrectangleQueries","updateSubrectangle","getValue","getValue","updateSubrectangle","getValue","getValue"]
[[[[3,9,4],[5,6,10]]],[1,1,1,1,5],[1,0],[1,0],[0,0,1,0,6],[1,0],[0,1]]
// There might be more so take in care of there

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Dhakar2003** [comment]
// This is my code in java 
class SubrectangleQueries {public int[][] mat; public SubrectangleQueries(int[][] rectangle) { mat=rectangle; } public void updateSubrectangle(int row1, int col1, int row2, int col2, int newValue) { for(int i=row1;i<=row2;i++){ int start=0,end=mat[0].length-1; if(i==row1) start=col1; if(i==row2) end=col2; for(int j=start;j<=end;j++) { mat[i][j]=newValue; } } } public int getValue(int row, int col) { return mat[row][col]; } } /** * Your SubrectangleQueries object will be instantiated and called as such: * SubrectangleQueries obj = new SubrectangleQueries(rectangle); * obj.updateSubrectangle(row1,col1,row2,col2,newValue); * int param_2 = obj.getValue(row,col); */

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

Your code submission link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
