### ISSUE TITLE
Missing Test Case - 26. Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by musalser** [LeetCode-Feedback/LeetCode-Feedback#10159]
#### Your LeetCode username
musalser2013

#### Category of the bug
- [ ] Language

#### Description of the bug
For Golang:
There is no way to deduplicate slice in place when the slice is not a pointer.

#### Code you used for Submit/Run operation

```
func removeDuplicates(nums *[]int) int {
	t := *nums
	for i := 0; i < len(t); i++ {
		if t[i] == t[i+1] {
			copy(t[i:], t[i+1:])
			t[len(t)-1] = 0
			t = t[:len(t)-1]
		}
	}
	fmt.Println(len(t))
	*nums = t
	return 1
}
```

#### Language used for code
Golang

#### Expected behavior
func removeDuplicates(nums *[]int)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Hi,

I hope this message finds you well! 

We recommend checking the Solutions tab to see if there's an existing solution. Often, fellow users share valuable insights that can assist in tackling the challenge you're facing.

Additionally, for the specific problem you mentioned, there's a handy trick: you don't necessarily need to delete elements in the array. Instead, try moving the elements to the front of the array and return the actual length. This can simplify the solution.

We hope this tip enhances your experience on our platform. If you have any further questions or need assistance, feel free to reach out. Happy coding!
