### ISSUE TITLE
Try test case on wrong answer return right, but submit still wrong - 876. Middle of the Linked List

### ISSUE THREAD

**Issue by duongphannamhung** [LeetCode-Feedback/LeetCode-Feedback#10151]
#### Category of the bug
- [ ] Question
- [ x ] Solution
- [ ] Language
- [ x ] Missing Test Cases 

#### Description of the bug

I met the wrong answer, so I put its test case into my box then tried again and it was right. There's a big conflict here but I don't know why?

#### Code you used for Submit/Run operation

```
_count_ = 1
class Solution:
    def middleNode(self, head: Optional[ListNode]) -> Optional[ListNode]:
        return take_2(head,head)
        
def take_2(head,output):
    global _count_
    if head.next:
        if (_count_ + 1) % 2 == 0:
            _count_ += 1
            return take_2(head.next,output.next)
        else:
            _count_ += 1
            return take_2(head.next,output)
    else:
        return output
```

#### Screenshots

<img width="1435" alt="Screenshot 2022-12-05 at 21 18 21" src="https://user-images.githubusercontent.com/77838344/205659425-4f9424b1-a63c-4010-8aae-a458b209f5e7.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-
