### ISSUE TITLE
Bugs in Frontend part!

### ISSUE THREAD

**Issue by Shubhamtribhuvan8** [LeetCode-Feedback/LeetCode-Feedback#10164]
![leetcodefrontendbugs1](https://user-images.githubusercontent.com/106821254/205809235-cdd36fcc-9d3c-4b1b-95d4-f56d8829a656.png)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [[1](![leetcodefrontendbugs1](https://user-images.githubusercontent.com/106821254/205809073-4ec30f17-bed1-4c2f-9169-dd6d93f26019.png)) ] Language
- [ ] Missing Test Cases 

#### Description of the bug
  Check out this HTML bug! On this page, [:align="center"] this content is showing on the front part! . 

#### Code you used for Submit/Run operation
*HTML BUGS:<p><img src="../Figures/328_Odd_Even.svg" alt="Illustration of odd even linked list" title="Odd Even Linked List" style="width: 539px;">
{:align="center"}</p>

* Bugs Link:https://leetcode.com/problems/odd-even-linked-list/solutions/127831/odd-even-linked-list/

// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code
<!-- C++ -->


#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->





#### Screenshots
![leetcodefrontendbugs1](https://user-images.githubusercontent.com/106821254/205809441-b440555f-7e09-4739-8c17-187d6260a4f6.png)



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by LC-Pam** [comment]
Thank you for your time. We've reported your feedback to the team.  We appreciate your support!
