### ISSUE TITLE
Three Year Old High Frequent Interview Problem Not Included On LeetCode

### ISSUE THREAD

**Issue by ThomasShaw1** [LeetCode-Feedback/LeetCode-Feedback#10169]
Hey LeetCode staff, this problem https://leetcode.com/discuss/interview-question/278341 has appeared in many FAANG interviews in high frequency over the years. None of the existing LeetCode questions are of this problem type and the discussion thread doesn't have really a right solution. I attempted to contribute this problem twice but was rejected. Can you take a look?

**Comment by LC-Pam** [comment]
Thank you for your time. We've submit your feedback to the team. For contribution status, please reach out to Leetcode zendesk support team for more details. We appreciate your support!

**Comment by ThomasShaw1** [comment]
Here’s another one that was contributed twice but rejected: https://leetcode.com/discuss/interview-question/413991/
