### ISSUE TITLE
Missing Test Case - 186. Reverse Words in a String II

### ISSUE THREAD

**Issue by dyamba** [LeetCode-Feedback/LeetCode-Feedback#10160]
#### Category of the bug
- [ ] Solution

#### Description of the bug

Miscalculation of the result.

#### Code you used for Submit/Run operation

```
public class Solution {
    public void ReverseWords(char[] s) {
        StringBuilder sb=new StringBuilder();        
        sb.Append(s);
        
        string ss=sb.ToString();
        
        string reversedString = "";
        string[] arr=ss.Split(' ');        

            for(int i=arr.Length-1;i>-1;i--)
            {
                if(string.IsNullOrEmpty(arr[i]))
                    continue;
                if(i==0)
                   reversedString+=arr[i];
                else
                    reversedString+=arr[i] + ' ';
            }
        
        s=reversedString.ToCharArray();
    }
}
```

#### Language used for code
C# 

#### Expected behavior

your answer section calculate wrong. When I try with Visual Studio the resul is different.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The  language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
