### ISSUE TITLE
SQL scheme display bug

### ISSUE THREAD

**Issue by onorridg** [LeetCode-Feedback/LeetCode-Feedback#10165]
#### Your LeetCode username
onorridg

#### Additional context
User-agent: Mozilla/5.0 (X11; Linux x86_64; rv:106.0) Gecko/20100101 Firefox/106.0
Problem url: https://leetcode.com/problems/top-travellers/?envType=study-plan&id=sql-i

https://user-images.githubusercontent.com/83474704/205818436-3bb00f76-bdd6-4de2-9bde-7c21529f954d.mp4

**Comment by LC-Pam** [comment]
Thank you for your time. We've reported your feedback to the team.  We appreciate your support!
