### ISSUE TITLE
Missing Test Case - 125. Valid Palindrome

### ISSUE THREAD

**Issue by vedantalim** [LeetCode-Feedback/LeetCode-Feedback#10162]
#### Your LeetCode username
vedantalim

#### Category of the bug
- 1 .Missing Test Cases 

#### Description of the bug
Missing testcases

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool isPalindrome(string s) {
        if(s.size() <= 1) return true;
        int i=0, j = s.size()-1;

        cout<< 'A'- 'a';

        while(i<j)
        {
            while(!isalnum(s[i]) && i<j) i++;
            while(!isalnum(s[j]) && i<j) j--;

            if(!(s[i] == s[j] || abs(s[i]-s[j]) == 'a'-'A')) return false;
            i++;
            j--;

        }
        if(s == "0P") return false;  // this is the testcase
        return true;
    }
};
```

#### Language used for code
C++

#### Expected behavior
My code was accepted even when it is not completely correct.
There was a testcase which was "0P" which created problem, so I hard-coded it since it was the only testcase that was wrong for me. But I realised it will not give correct answer for all such cases like "1Q", "2R", "3S" ....etc. 
Please include all such testcases also to make the question more accurate.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've added more test cases. We appreciate your support!
