### ISSUE TITLE
Missing Test Case - 1805. Number of Different Integers in a String

### ISSUE THREAD

**Issue by tongjianglei** [LeetCode-Feedback/LeetCode-Feedback#10163]
#### Your LeetCode username

hello_w

#### Category of the bug
- [ ] Solution

#### Description of the bug

Using error codes can also pass all cases.

#### Code you used for Submit/Run operation

```
// Number of Different Integers in a String
class Solution {
    public int numDifferentIntegers(String word) {
        Set<String> set = new HashSet<>();
        char[] str = word.toCharArray();
        int p1 = 0, p2 = 0, n = str.length;
        while(p2 < n){
            while(p1 < n && str[p1] >= 'a' && str[p1] <= 'z')p1++;
            p2 = p1 + 1;
            while(p2 < n && str[p2] >= '0' && str[p2] <= '9')p2++;
            while(p1 < n && str[p1] == '0')p1++;
            if(p2 <= n)set.add(word.substring(p1,p2));
            p1 = p2;
        }
        return set.size();
    }
}
```

#### Language used for code

JAVA

#### Expected behavior

Using my code, we can get all the expected results, but for test cases such as "a0a", we actually count "" instead of "0", and the code that does not conform to the meaning of the question is still passed.

#### Screenshots

![image](https://user-images.githubusercontent.com/61345754/205799926-16f09bb3-7094-417c-bd56-645e91806564.png)

**Comment by LC-Pam** [comment]
Thank you for your time. This code is actually correct, because it stores a string corresponding to "0" in the set. No changes made. We appreciate your support!
