### ISSUE TITLE
Cannot resolve Pair class for Java 

### ISSUE THREAD

**Issue by linnykoleh** [LeetCode-Feedback/LeetCode-Feedback#10170]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

Code analysis cannot resolve **Pair** class

#### Code you used for Submit/Run operation

```java
// Binary Tree Postorder Traversal
class Solution {
    public List<Integer> postorderTraversal(TreeNode root) {
        var stack = new ArrayDeque<Pair<TreeNode, Boolean>>();
        var res = new ArrayList<Integer>();

        if(root == null) return res;

        stack.push(new Pair(root, false));
        while(!stack.isEmpty()){
            var top = stack.pop();
            root = top.getKey();
            if(top.getValue()){
                res.add(root.val);
            }else{
                stack.push(new Pair(root, true));
                if(root.right != null)
                    stack.push(new Pair(root.right, false));
                if(root.left != null)    
                    stack.push(new Pair(root.left, false));
            }
        }
        return res;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Pair class is compiled

#### Screenshots

<img width="838" alt="image" src="https://user-images.githubusercontent.com/9572572/205890205-38d27b9f-5842-4995-b5f9-79bad70ea5ff.png">

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to update the problem. We appreciate your support!
