### ISSUE TITLE
Missing Test Case - 328. Odd Even Linked List

### ISSUE THREAD

**Issue by sardware** [LeetCode-Feedback/LeetCode-Feedback#10172]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug
Python3 syntax error highlighter doesn't work well as it was, and sometimes is wrong.
It highlighted Optional, while before there was an implicit "from typing import Optional".
It marks ListNode() as an error because it expects a parameter inside.
It also marks every access to the next pointer by .next.

#### Code you used for Submit/Run operation

```
class Solution:
    def oddEvenList(self, head: Optional[ListNode]) -> Optional[ListNode]:
        dummy = ListNode()
        new_head = dummy
        end = ListNode()
        middle = end
        odd = True
        while head:
            print(head)
            if odd:
                new_head.next = head
                new_head = new_head.next
            else:
                end.next = head
                end = end.next
            odd = not odd
            head = head.next

        new_head.next = middle.next
        return dummy.next

```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
