### ISSUE TITLE
Missing Test Case - 53. Maximum Subarray

### ISSUE THREAD

**Issue by alisha-takkar** [LeetCode-Feedback/LeetCode-Feedback#10177]
#### Your LeetCode username

alisha-takkar

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A missing test case in which all elements of the array are negative :

[-1, -2, -3]   // -1 

#### Code you used for Submit/Run operation

```
var maxSubArray = function(arr) {
    let maxGlobal = maxCurrent = arr[0];
    for(let i=1; i<arr.length; i++){
        maxCurrent = Math.max(arr[i] , maxCurrent + arr[i]);
        if(maxCurrent > maxGlobal){
            maxGlobal = maxCurrent;
        }
    }
    return maxGlobal;
};
```

#### Language used for code

JavaScript

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.
[-1, -2, -3] // -1 is invalid missing test case.
[-1, -2, -3]  already exist.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
