### ISSUE TITLE
Missing Test Case - 328. Odd Even Linked List

### ISSUE THREAD

**Issue by varshi1228** [LeetCode-Feedback/LeetCode-Feedback#10178]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by varshi1228** [comment]
code use to submited

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The  language you submitted to reach this result.
The missing test case. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
