### ISSUE TITLE
Inconsistent content in Binary Search Template II

### ISSUE THREAD

**Issue by roman-zubarevich** [LeetCode-Feedback/LeetCode-Feedback#10181]
#### Your LeetCode username

user7581dN

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ X ] Language
- [ ] Missing Test Cases 

#### Description of the bug

https://leetcode.com/explore/learn/card/binary-search/126/template-ii/937/
Text explanation on the page mentions several times that the algorithm accesses the current alement and its immediate right neighbor. E.g.:
> Use the element's right neighbor to determine if the condition is met and decide whether to go left or right

However, it doesn't seem to be reflected in the template code (Java). In particular, the code just compares the current (mid) element with the given target to decide which part of the array to take for the next iteration - the condition is exactly the same as in the previous chapter "Template I".

#### Code you used for Submit/Run operation

N/A

#### Language used for code

N/A

#### Expected behavior

Expected to see a description that is consistent with the code, but got a misleading and confusing information.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
