### ISSUE TITLE
Can't see any of the videos from 'The LeetCode Beginner's Guide' section

### ISSUE THREAD

**Issue by vovina** [LeetCode-Feedback/LeetCode-Feedback#10188]
![image](https://user-images.githubusercontent.com/4012974/206103958-68e11c67-4a5c-44cb-9861-c09166008ca3.png)

**Comment by LC-Pam** [comment]
Hi there,
 
Thanks for reaching out to us and sorry this is occurred to you!
 
Our team is aware of this issue with the video solutions and we'll have the video solutions fixed very soon.

Please let us know if there's anything else we can do to assist.
 
Thank you,
 
LC

**Comment by LC-Pam** [comment]
Issue Fixed.
