### ISSUE TITLE
Missing Test Case - 73. Set Matrix Zeroes

### ISSUE THREAD

**Issue by yogendradevil** [LeetCode-Feedback/LeetCode-Feedback#10189]
#### Your LeetCode username
DevilYogi

#### Category of the bug
- [] Missing Test Cases 

#### Description of the bug
my code got accepted after using -1500 instead of -1

#### Code you used for Submit/Run operation
```
class Solution {
    public void setZeroes(int[][] matrix) {
        int rl = matrix.length-1;    //row length
        int cl = matrix[0].length-1; //column length

        for(int i = 0; i<=rl; i++){
            for(int j =0 ; j<=cl; j++){
                if(matrix[i][j] == 0){
                    // row opration
                    for(int k =0; k <= cl; k++){
                        if(matrix[i][k] != 0){
                            matrix[i][k] =-1500;
                        }
                    }

                    // column opration
                    for(int k =0; k <= rl; k++){
                        if(matrix[k][j] != 0){
                            matrix[k][j] =-1500;
                        }
                    }
                }
            }
        }

        for(int i = 0; i<=rl; i++){
            for(int j =0 ; j<=cl; j++){
                if(matrix[i][j] == -1500){
                    matrix[i][j] =0;
                }
            }
        }
    }
}
```

#### Language used for code
JAVA

#### Expected behavior
it will give the wrong output when we run [[-1500,1,1],[1,0,1],[1,1,1]] test case  

#### Screenshots

![image](https://user-images.githubusercontent.com/81254268/206107635-ecbc8289-b7ab-425e-a251-2914e9821d0c.png)
![image](https://user-images.githubusercontent.com/81254268/206107704-3c6e41d4-bb8c-423e-bad8-794740cf660c.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
