### ISSUE TITLE
course video not available after purchase

### ISSUE THREAD

**Issue by monday123666** [LeetCode-Feedback/LeetCode-Feedback#10185]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
course video not available after purchase

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots
![image](https://user-images.githubusercontent.com/119999084/206095410-fa005c29-684f-471d-b6f7-fd7d4b5cb454.png)

**Comment by B0HAN** [comment]
same

**Comment by XiaoWanLINJU** [comment]
I can confirm this issue.

**Comment by LC-Pam** [comment]
Update: Video solution issue fixed, we appreciate your support!
