### ISSUE TITLE
Problem 297. Serialize and Deserialize Binary Tree; test cases improvement

### ISSUE THREAD

**Issue by DFedonnikov** [LeetCode-Feedback/LeetCode-Feedback#10180]
#### Your LeetCode username
DFedonnikov

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The test cases for Kotlin code in the problem [297. Serialize and Deserialize Binary Tree](https://leetcode.com/problems/serialize-and-deserialize-binary-tree/description/?q=kotlin&orderBy=most_relevant) don't take into the account Kotlin top level declaration making it possible to cheat and just save the incoming tree in serialize method into the top level variable and then return it in the deserialize method. Since it's a top level variable it doesn't matter that test cases uses two different objects for serialize and deserialize.

#### Code you used for Submit/Run operation

This code passes the test case, though it shouldn't

```
var result: TreeNode? = null

class Codec() {
	// Encodes a URL to a shortened URL.
    fun serialize(root: TreeNode?): String {
        result = root
        return ""
    }

    // Decodes your encoded data to tree.
    fun deserialize(data: String): TreeNode? {
        return result
    }
}

```

#### Language used for code
Kotlin

#### Expected behavior
Test cases are failing because no logic for the actual serialization/deserialization was implemented

#### Screenshots
<img width="1680" alt="Снимок экрана 2022-12-06 в 20 34 02" src="https://user-images.githubusercontent.com/23657764/206005622-a5ce9e59-d9eb-48b1-97dd-8097aa738fee.png">

**Comment by LC-Pam** [comment]
Thank you for your time. 
It is not possible to fail this solution currently because we run the ser/deser in the same scope.
The purpose of this problem is practicing and we know that people can cheat to get it AC but the most important thing is to solve it correctly for the interview.
We appreciate your support!
