### ISSUE TITLE
Unusual texts in the official solution page of Odd Even Linked List 

### ISSUE THREAD

**Issue by PiyalAhmed** [LeetCode-Feedback/LeetCode-Feedback#10182]
#### Your LeetCode username
piyalAhmed

#### Category of the bug
- [ ] Language

#### Description of the bug

In the official solution page of the problem **[Odd Even Linked List](https://leetcode.com/problems/odd-even-linked-list/solutions/127831/odd-even-linked-list/)** contains  **{:align="center"}** twice just before the codes provided. Which indicates the texts should be centre aligned, but instead doing the operation, the code is directly reflecting in the page. Which is unsual.

#### Screenshots

![Screenshot 2022-12-07 032115](https://user-images.githubusercontent.com/43670583/206025871-55364af4-4d30-4252-a6e3-0d71ae815cd1.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
