### ISSUE TITLE
LeetCode's Interview Crash Course - Video does not exist

### ISSUE THREAD

**Issue by ArdavanSh** [LeetCode-Feedback/LeetCode-Feedback#10184]
The LeetCode's Interview Crash Course video tutorial do not work and show a massage saying 'Sorry, the video does not exist'

**Comment by taaey** [comment]
Same problem.

**Comment by divitavora** [comment]
Same problem

**Comment by 1000nettles** [comment]
Same issue here.

**Comment by dwu12** [comment]
same

**Comment by hughieDev** [comment]
This is the same for me - any update?

**Comment by LC-Pam** [comment]
Hi there,
 
Thanks for reaching out to us and sorry this is occurred to you!
 
Our team is aware of this issue with the video solutions and we'll have the video solutions fixed very soon.

Please let us know if there's anything else we can do to assist.
 
Thank you,
 
LC

**Comment by SmokeShine** [comment]
Same issue.

**Comment by 1000nettles** [comment]
This has been fixed for me, thanks!

**Comment by LC-Pam** [comment]
Update: Video solution issue fixed, we appreciate your support!
