### ISSUE TITLE
正则表达式匹配

### ISSUE THREAD

**Issue by swz97** [LeetCode-Feedback/LeetCode-Feedback#1018]
** Bug 类型**
- 题目
- 题解
- [ ] 编程语言

**描述**
三次的输入和预期互相矛盾

**你使用的语言**
C语言

**你提交或者运行的代码**
```
bool isMatch(char * s, char * p){
    if(NULL == s && NULL == p) {
        return true;
    }
    int i = 0, j = 0;
    if(p[j] == '*') {
        return false;
    }

    while(s[i] != '\0' && p[j] != '\0') {
        if(s[i] == p[j]) {
            ++i;
            ++j;
        }
        else if(p[j] == '.') {
            ++i;
            ++j;
        }
        else if(p[j] == '*') {
            if(s[i] == p[j - 1] || (p[j - 1] == '.' && s[i] == s[i - 1])) {
                ++i;
            }
            else if(s[i] == p[j + 1] || p[j + 1] == '.') {
                ++i;
                ++j;
                ++j;
            }
            else {
                return false;
            }
        }
        else{
            j++;
        }
    }

    if(s[i] != '\0' && p[j] == '\0') {
        return false;
    }

    return true;
}
```

**期望行为**
描述你期望的结果

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![1600248021(1)](https://user-images.githubusercontent.com/63571995/93318889-cdf26900-f841-11ea-83da-6117b495e2e3.jpg)
![1600248058(1)](https://user-images.githubusercontent.com/63571995/93318899-cfbc2c80-f841-11ea-835b-be27c1a89978.jpg)
![1600248085(1)](https://user-images.githubusercontent.com/63571995/93318902-d0ed5980-f841-11ea-9772-f9bfed42c6de.jpg)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
你好，建议再仔细调试一下代码，希望这篇内容有帮助：https://leetcode.kf5.com/hc/kb/article/1194344 。后续刷题学习中遇到问题，可通过阅读「题解」解决做题中的一些困惑，看看其他小伙伴的解题思路哦。

**Comment by swz97** [comment]
你别看我的代码，代码我改过，你自己看看截图的结果和题目描述，题目说的是在字符串p中能找到和s相匹配的字符串，然后.代表任意单个字符，*代表零个到多个前面字符的重复，然后.*输出是true，.*c就是false，这不是相冲突嘛



---原始邮件---
发件人: "feiceh"<notifications@github.com&gt;
发送时间: 2020年9月16日(周三) 晚上6:42
收件人: "LeetCode-Feedback/LeetCode-Feedback"<LeetCode-Feedback@noreply.github.com&gt;;
抄送: "swz97"<1228176881@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [LeetCode-Feedback/LeetCode-Feedback] 正则表达式匹配 (#1018)




 
你好，建议再仔细调试一下代码，希望这篇内容有帮助：https://leetcode.kf5.com/hc/kb/article/1194344 。后续刷题学习中遇到问题，可通过阅读「题解」解决做题中的一些困惑，看看其他小伙伴的解题思路哦。
