### ISSUE TITLE
Video Not exist ( the-leetcode-beginners-guide ) 

### ISSUE THREAD

**Issue by Kayuemkhan** [LeetCode-Feedback/LeetCode-Feedback#10190]
### Video Doesn't exist.

**Comment by LC-Pam** [comment]
Hi there,
 
Thanks for reaching out to us and sorry this is occurred to you!
 
Our team is aware of this issue with the video solutions and we'll have the video solutions fixed very soon.

Please let us know if there's anything else we can do to assist.
 
Thank you,
 
LC

**Comment by LC-Pam** [comment]
Update: Video solution issue fixed, we appreciate your support!

**Comment by Kayuemkhan** [comment]
Thanks for your support.
