### ISSUE TITLE
'This video does not exist' - Cannot view solution videos

### ISSUE THREAD

**Issue by aunshx** [LeetCode-Feedback/LeetCode-Feedback#10197]
Not able to view any solution video as it shows 'Sorry. This video does not exist'.

Example 1:
![Screenshot_20221207_174601](https://user-images.githubusercontent.com

Example 2:
![Screenshot_20221207_174713](https://user-images.githubusercontent.com/86175885/206177279-775a8801-065f-4f06-99a0-0777f2fe173c.png)
/86175885/206177070-dfe5ca61-3d00-4c18-b205-4e033edf38e3.png)

Example 3:
![Screenshot_20221207_174744](https://user-images.githubusercontent.com/86175885/206177379-f999d57a-b368-4432-9a1b-eb80a61f27c5.png)

**Comment by Davisino** [comment]
I can confirm this issue.

**Comment by LC-Pam** [comment]
Hi there,
 
Thanks for reaching out to us and sorry this is occurred to you!
 
Our team is aware of this issue with the video solutions and we'll have the video solutions fixed very soon.

Please let us know if there's anything else we can do to assist.
 
Thank you,
 
LC

**Comment by LC-Pam** [comment]
Update: Video solution issue fixed, we appreciate your support!
