### ISSUE TITLE
Any test case does not work

### ISSUE THREAD

**Issue by onorridg** [LeetCode-Feedback/LeetCode-Feedback#10191]
#### Your LeetCode username
onorridg

#### Category of the bug
Any test case does not work

#### Description of the bug
URL problem: https://leetcode.com/problems/tree-node/description/?envType=study-plan&id=sql-i
Any test case does not work and returns "foreign key p_id =  does not exist in the Tree table".
I want to note that the system has made a decision.

#### Language used for code
MySQL

#### Screenshots

![Screenshot 2022-12-07 at 10-32-39 Tree Node - LeetCode](https://user-images.githubusercontent.com/83474704/206116347-a6449560-2f40-41fe-b0c0-f1cec5e64fff.png)

![Screenshot 2022-12-07 at 10-23-59 Tree Node - LeetCode](https://user-images.githubusercontent.com/83474704/206116366-e75d4f34-d6c3-4db9-b6c3-8cf335648128.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
https://project.feishu.cn/leetcode/us_tickets/detail/2519313?parentUrl=%2Fleetcode%2FworkObjectView%2Fus_tickets%2FvHtNOOSVR

**Comment by LC-Pam** [comment]
https://project.feishu.cn/leetcode/us_tickets/detail/2519313?parentUrl=%2Fleetcode%2FworkObjectView%2Fus_tickets%2FvHtNOOSVR

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The judge working correctly right now. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
