### ISSUE TITLE
Missing Test Case - 162. Find Peak Element

### ISSUE THREAD

**Issue by constructorvirgil** [LeetCode-Feedback/LeetCode-Feedback#10194]
#### Your LeetCode username

constructorvirgil

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
func findPeakElement(nums []int) int {
    if len(nums) == 1 {
        return 0
    }
    if len(nums) == 2 {
        if nums[0] > nums[1] {
            return 0
        }else{
            return 1
        }
    }
    if nums[0]> nums[1] {
        return 0
    }
    if nums[len(nums)-1]> nums[len(nums)-2] {
        return len(nums)-1
    }
	var left = 0
	var right = len(nums)
	for left < right {
		var mid = left + (right-left)/2
		if mid <= 0 {
            left = mid + 1
            continue
		}
		if mid >= len(nums)-1 {
            right = mid
            continue
		}
		if nums[mid-1] < nums[mid] && nums[mid] > nums[mid+1] {
			return mid
		}
		if nums[mid] < nums[mid+1] {
			left = mid + 1
		} else {
			right = mid
		}
	}
	return -1
}
```

#### Language used for code

Golang

#### Expected behavior

The answer should be 5.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The test case that  you use.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
