### ISSUE TITLE
This video does not exist

### ISSUE THREAD

**Issue by makhanifahim** [LeetCode-Feedback/LeetCode-Feedback#10192]
#### Your LeetCode username

fahimmakhanifm

#### Category of the bug
- Solution

#### Description of the bug

Videos are not available in "Solving Your First Problem"

#### Screenshots

![image](https://user-images.githubusercontent.com/42364722/206124705-598c850c-d7b3-4931-8b5e-a5b356e37b2a.png)

**Comment by LC-Pam** [comment]
Hi there,
 
Thanks for reaching out to us and sorry this is occurred to you!
 
Our team is aware of this issue with the video solutions and we'll have the video solutions fixed very soon.

Please let us know if there's anything else we can do to assist.
 
Thank you,
 
LC
