### ISSUE TITLE
No Video for system design card

### ISSUE THREAD

**Issue by gnsendhil** [LeetCode-Feedback/LeetCode-Feedback#10195]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

No Video for system design card https://leetcode.com/explore/learn/card/system-design/689/system-design-basics/4402/

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Hi there,
 
Thanks for reaching out to us and sorry this is occurred to you!
 
Our team is aware of this issue with the video solutions and we're working on to fix this issue as soon as possible.

We are sorry all the inconvenience that we caused to you.

Thank you for your patience and support!
 
LC

**Comment by LC-Pam** [comment]
Update: Video solution issue fixed, we appreciate your support!
