### ISSUE TITLE
30 Day Challenge - Unhappy Number

### ISSUE THREAD

**Issue by rankinchristopher** [LeetCode-Feedback/LeetCode-Feedback#102]
**What kind of the bug**
- [x ] problem
- [ ] solution
- [ ] language

**Describe the bug**
I've been taking part in the 30 Day Challenge.
I believe there is am issue with the Week 1 problem set 2 "Happy number" problem set

The challenge states that non happy number should result in an endless loop.
My code does this but python will throw a runtime exception on detecting an endless loop.
Because of this even though my code matched the brief I could not successfully submit it.

" Write an algorithm to determine if a number is "happy".
A happy number is a number defined by the following process: Starting with any positive integer, replace the number by the sum of the squares of its digits, and repeat the process until the number equals 1 (where it will stay), or it loops endlessly in a cycle which does not include 1. Those numbers for which this process ends in 1 are happy numbers."

**what language is your code written in**
Python3

**The code you submit/run**
```
""" 
Input: 19
Output: true
Explanation: 
12 + 92 = 82
82 + 22 = 68
62 + 82 = 100
12 + 02 + 02 = 1
"""
class Solution:
    def isHappy(self, n: int) -> bool:
        print(n)
        if n == 1:
            return True
        else:
            numSum = 0
            numsToAdd = []
            chars = str(n)
            for char in chars:
                numsToAdd.append(int(char) * int(char))
            for num in numsToAdd:
                numSum += num
            return self.isHappy(n=numSum)
```

**Expected behavior**
Based on the description of the challenge an runtime exception should have been expected in this case.

**Screenshots**

**Additional context**

**Comment by SpaIns** [comment]
Not leetcode staff, but you interpreted the problem wrong. When finding an endless loop, you return False, not continue forever.

**Comment by dopheide** [comment]
I had this same mis-interpretation of the instructions.  Unfortunately, my misunderstanding was reenforced by the output from running the code (which you can force my inserting an unending loop).  Your result is "Time Limit Exceeded", but down in expected answer it also says "Time Limit Exceeded", so it seems like that's what I wanted to happen.

I think this confusion could be resolved by showing an example of a False cycle.

**Comment by CooperCooperCooper** [comment]
Hi @rankinchristopher, @SpaIns, and @dopheide,
Thank you for your feedback! The problem statement is now updated.
