### ISSUE TITLE
Missing Test Case - 180. Consecutive Numbers

### ISSUE THREAD

**Issue by mahesh4215** [LeetCode-Feedback/LeetCode-Feedback#10203]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

solved consecutive number using se;f join as it is easy and understandable for everyone.

#### Code you used for Submit/Run operation

```
select distinct a.Num as ConsecutiveNums from Logs a
Join Logs b  ON a.id = b.id + 1 and a.Num = b.Num
Join Logs c ON  a.id = c.id + 2 and a.Num = c.Num;
```

**Comment by LC-Pam** [comment]
Thank you for your time. We've submit your feedback to the team. We appreciate your support!
