### ISSUE TITLE
Input dimension not given in 421. Maximum XOR of Two Numbers in an Array

### ISSUE THREAD

**Issue by Mohitkumar6122** [LeetCode-Feedback/LeetCode-Feedback#1020]
#### Your LeetCode username

Mohitkumar6122

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

size of input array not given in question. 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int findMaximumXOR(vector<int>& nums) {
        int ans = 0, n = nums.size() ;
        vector < int > arr = nums ;
        int maxx = 0, mask = 0; 
  
    set<int> se; 
  
    for (int i = 30; i >= 0; i--) { 
  
        mask |= (1 << i); 
  
        for (int i = 0; i < n; ++i) { 
  
         
            se.insert(arr[i] & mask); 
        } 
        int newMaxx = maxx | (1 << i); 
        for (int prefix : se) { 
  
            if (se.count(newMaxx ^ prefix)) { 
                maxx = newMaxx; 
                break; 
            } 
        } 
        se.clear(); 
    } 
  
    return maxx; 
    }
};
```

#### Language used for code
 C++

**Comment by lc-kay** [comment]
Hi @Mohitkumar6122 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Mohitkumar6122 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
