### ISSUE TITLE
python editor: sortedcontainers not supported by editor linting + code completion

### ISSUE THREAD

**Issue by tylergannon** [LeetCode-Feedback/LeetCode-Feedback#10208]
#### Your LeetCode username
tylergannon

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Python language support in the new text editor includes code completion and lint support for system packages.  But leetcode also provides the "sortedcontainers" package, and this shows up as a bad import in the new text editor.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code
Python

#### Expected behavior
Lint support and code completion should work for all packages that are available for import,
namely, sortedcontainers.

#### Screenshots

<img width="507" alt="Screenshot 2022-12-07 at 1 36 21 PM" src="https://user-images.githubusercontent.com/50593/206278726-dfc527e0-1714-41b9-a7e3-5eac0d4e8908.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!

**Comment by tylergannon** [comment]
Thank you.  I'll watch this issue.  I appreciate that you all provide this interface for feedback.  Thanks for your work!
