### ISSUE TITLE
Broken Test Case - 724. Find Pivot Index

### ISSUE THREAD

**Issue by currenthandle** [LeetCode-Feedback/LeetCode-Feedback#10213]
#### Your LeetCode username

curenthandle

#### Category of the bug
- [x] Broken Test
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Given the explanation of the problem and several similar passing test cases the solution to: [-1,-1,0,0,1,1] is that the leftmost pivot is at position 2. Here (on the first 0) the left and right sides of the pivot are equal. They both equal zero.

For this reason, the value expected by the test, -1, is incorrect. The problem states that -1 is meant for arrays that have no pivot. This array has two and the pivot at the arr index 2 is the leftmost pivot.

Problem description: 

Given an array of integers nums, calculate the pivot index of this array.

The pivot index is the index where the sum of all the numbers strictly to the left of the index is equal to the sum of all the numbers strictly to the index's right.

If the index is on the left edge of the array, then the left sum is 0 because there are no elements to the left. This also applies to the right edge of the array.

Return the leftmost pivot index. If no such index exists, return -1.

#### Code you used for Submit/Run operation

```
function pivotIndex(nums: number[]): number {
    let sum = 0;
    for (const num of nums) {
        sum += num;
    }
    let localSum = 0;
    for (const [i, num] of nums.entries()) {

        if (i === 0) {
            if (sum - num === 0) {
                return 0;
            }
        }
        if (i === nums.length - 1) {
            if (sum - num === 0) {
                return i;
            }
        }
        localSum += num;
        console.log()
        console.log('sum', sum)
        console.log('localSum', localSum)
        console.log('i', i)
        console.log('nums[i]', nums[i])
        const splitQuotient = (sum - nums[i + 1]) / localSum 
        if (splitQuotient === 2 || splitQuotient === 0) {
            return i + 1;
        }
    }
    return -1;
};

```

#### Language used for code

typescript

#### Expected behavior

test expects 2 and passes

#### Screenshots

<img width="697" alt="Screenshot 2022-12-07 at 9 28 35 PM" src="https://user-images.githubusercontent.com/10948068/206364235-0ae7f964-cf7b-4304-8f7e-2402a0783771.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, our judger appears to be running correctly, please feel free to refer the discuss section of the problem to see how other users' have optimized their codes!
