### ISSUE TITLE
Missing Test Case - 938. Range Sum of BST

### ISSUE THREAD

**Issue by Aqilzeka** [LeetCode-Feedback/LeetCode-Feedback#10210]
#### Your LeetCode username 
AqilAghamirzayev

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
When I write the `static int sum = 0` as static value the second testcase is not passed but in my ide it works perfectly

#### Code you used for Submit/Run operation

```
// Does't pass the test case
public class Solution {
    static int sum = 0;  // because static keyword but it works in my ide

    public int rangeSumBST(TreeNode root, int low, int high) {
        if (root == null) return 0;

        sum += root.val >= low && root.val <= high ? root.val : 0;
        rangeSumBST(root.left, low, high);
        rangeSumBST(root.right, low, high);

        return sum;
    }
}

----------------------------
// The same solution without static key passed second test case
public class Solution {
    int sum = 0;

    public int rangeSumBST(TreeNode root, int low, int high) {
        if (root == null) return 0;

        sum += root.val >= low && root.val <= high ? root.val : 0;
        rangeSumBST(root.left, low, high);
        rangeSumBST(root.right, low, high);

        return sum;
    }
}
```

#### Language used for code
Java

**Comment by Aqilzeka** [comment]
Working solution but doesn't pass 2nd test case

**Comment by stormsunshine** [comment]
Please DO NOT use static variables. In LeetCode, an object is created for each test case, and all objects share the same static variables, so the previous test cases will affect the next text cases.

The solution is to avoid using static variables.

**Comment by LC-Pam** [comment]
Thank you for your time. Please consider Stromsunshine's comment as reference.  We appreciate your support!
