### ISSUE TITLE
File link missing

### ISSUE THREAD

**Issue by sameerbabu** [LeetCode-Feedback/LeetCode-Feedback#10217]
In the page
https://leetcode.com/explore/featured/card/dynamic-programming/630/an-introduction-to-dynamic-programming/4035/

Below code is being displayed, instead of actual link to the file.

!?!../../../../Documents/DP1_EC/C1_A2_1.json:960,540!?!

**Comment by LC-Pam** [comment]
Thank you for your time. We've reported your feedback to the team.  We appreciate your support!
