### ISSUE TITLE
New UI Invalid Testcase Error - 608. Tree Node

### ISSUE THREAD

**Issue by kandiana** [LeetCode-Feedback/LeetCode-Feedback#10218]
#### Your LeetCode username
kandiana

#### Category of the bug
- [x] Other

#### Description of the bug
Trying to run a solution of the problem [608. Tree Node](https://leetcode.com/problems/tree-node/description/) with **default testcases** in the **new UI** always ends up in **Invalid Testcase Error**:
```
foreign key p_id =  does not exist in the Tree table
```
Defaul testcases are:
Case 1
```
| id | p_id |
| -- | ---- |
| 1  |      |
| 2  | 1    |
| 3  | 1    |
| 4  | 2    |
| 5  | 2    |
```
Case 2
```
| id | p_id |
| -- | ---- |
| 1  |      |
```

#### Code you used for Submit/Run operation
```
select * from tree
```

#### Language used for code
All available: MySQL, MS SQL Server, Oracle

#### Expected behavior
Presented code should finish running on default testcases.

#### Screenshots
![Testcase 1](https://i.imgur.com/Y4QIJpa.png)
![Testcase 2](https://i.imgur.com/sQXyZuC.png)
![Result](https://i.imgur.com/OKOhyKk.png)

#### Additional context
- The code is submittable, the problem is in running testcases only
- Everything works fine in the old UI
- There were several similar issues ([example](https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/9342)), but they are all closed now yet the problem still persists
- I read [the article on wrong answer/runtime error](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-), it did not help (there is nothing on sql problems)
- There are a lot of discussions on the topic, the only solution presented there is to use old UI to run test cases for the problem
![discussions](https://i.imgur.com/fNwXWNt.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
https://project.feishu.cn/leetcode/us_tickets/detail/2519313?parentUrl=%2Fleetcode%2FworkObjectView%2Fus_tickets%2FvHtNOOSVR

**Comment by LC-Pam** [comment]
https://project.feishu.cn/leetcode/us_tickets/detail/2519313?parentUrl=%2Fleetcode%2FworkObjectView%2Fus_tickets%2FvHtNOOSVR

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The judge working correctly right now. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
