### ISSUE TITLE
Missing Test Case - 2236. Root Equals Sum of Children

### ISSUE THREAD

**Issue by Gitty-3ps** [LeetCode-Feedback/LeetCode-Feedback#10212]
#### Your LeetCode username
Deron_Go 

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
There is not a test case to test when one of the child values is zero(0) 

#### Code you used for Submit/Run operation

```
public class Solution {
    public bool CheckTree(TreeNode root){
        return root.val == root.left.val + root.right.val;
    }
}
```

#### Language used for code
 C# 

#### Expected behavior
This test case should return true

**Comment by LC-Pam** [comment]
Thank you for your time. It is not a corner case, and does not cause any common solutions to fail. 
There is no special significance of a child node with value 0. We appreciate your support!
