### ISSUE TITLE
Missing Test Case - 872. Leaf-Similar Trees

### ISSUE THREAD

**Issue by HarshKumarChoudary** [LeetCode-Feedback/LeetCode-Feedback#10215]
#### Your LeetCode username
HarshKumarChoudhary

#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [x] Missing Test Cases 

#### Description of the bug
There is a type of test case missing. Suppose lets say if some person uses string and adds the leaf values from left to right to that string, without any separator. Then this kind of solution should not pass, since for example if leaf values of first tree are 6, 14 and leaf values of second tree are 61, 4, then as per the above solution, the two trees have similar leaf value sequence, which is not the case.

Hence I am adding this bug report to highlight this missing idea in test cases.

#### Code you used for Submit/Run operation

```
// Submitted this code which worked correctly, with the test cases, but as mentioned it should fail.
class Solution {
public:
    string ans1,ans2;
    void solve1(TreeNode* head){
        if(head == NULL)return;
        if(head->left == nullptr and head->right == nullptr){
            ans1+=(head->val);
            return;
        }
        solve1(head->left);
        solve1(head->right);
    }
    void solve2(TreeNode* head){
        if(head == NULL)return;
        if(head->left == nullptr and head->right == nullptr){
            ans2+=(head->val);
            return;
        }
        solve2(head->left);
        solve2(head->right);
    }
    bool leafSimilar(TreeNode* root1, TreeNode* root2) {
        ans1 = "";
        ans2 = "";

        solve1(root1);
        solve2(root2);
        return ans1 == ans2;
    }
};
```

#### Language used for code
C++

#### Expected behavior
The code should output false, since the leaf value sequences are not correct.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
