### ISSUE TITLE
Typo in Leetcode #1101

### ISSUE THREAD

**Issue by PashanIrani** [LeetCode-Feedback/LeetCode-Feedback#10223]
#### Your LeetCode username
pashan

#### Category of the bug
- [X ] Question
- [ ] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug
Hello, I've identified a typo in a question. For leetcode #1101. https://leetcode.com/problems/the-earliest-moment-when-everyone-become-friends/description/)

In the first example it says "The fifth event occurs at timestamp = 20190224 and as 2 and 4 are already friends anything happens."

I believe "anything" should be "nothing" if I'm not mistaken.

It's very minor issue, but I think it should be fixed.

Thank you

#### Screenshots
![image](https://user-images.githubusercontent.com/22552163/206473410-53bedf5e-50b3-4ae5-a72b-52194bb2c424.jpeg)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to Updated the typo in example 1. We appreciate your support!
