### ISSUE TITLE
Problem : 2365. Task Scheduler II - Example test case 1  explanation is not proper

### ISSUE THREAD

**Issue by VirendraSinghRathore24** [LeetCode-Feedback/LeetCode-Feedback#10227]
#### Your LeetCode username
Viren21

#### Category of the bug
- Missing Test Cases - test case issue

#### Description of the bug
Example test case 1 explanation is wrong:

Input: tasks = [1,2,1,2,3,1], space = 3
Output: 9
Explanation:
One way to complete all tasks in 9 days is as follows:
Day 1: Complete the 0th task.
Day 2: Complete the 1st task.
Day 3: Take a break.
Day 4: Take a break.
Day 5: Complete the 2nd task.
Day 6: Complete the 3rd task.
**Day 7: Take a break.
Day 8: Complete the 4th task.**
Day 9: Complete the 5th task.
It can be shown that the tasks cannot be completed in less than 9 days.
here Day 7: should be Day 8 and vice versa.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The sample explanation depicts one of the ways to complete tasks, there are other ways as well.

The sequence mentioned in the example satisfies all properties.

Did not make any changes. 

We appreciate your support!
