### ISSUE TITLE
[Bug] Problem 1687 description

### ISSUE THREAD

**Issue by congliu0704** [LeetCode-Feedback/LeetCode-Feedback#10226]
#### Your LeetCode username

leetcode.cn/u/congliu0704

#### Category of the bug
- [x] Problem Description

#### Description of the bug
For problem [1687. Delivering Boxes from Storage to Ports](https://leetcode.cn/problems/delivering-boxes-from-storage-to-ports/), the explanation of example 2 has a wrong port number:

The observed version

```
Input: boxes = [[1,2],[3,3],[3,1],[3,1],[2,4]], portsCount = 3, maxBoxes = 3, maxWeight = 6
Output: 6
Explanation: The optimal strategy is as follows: 
- The ship takes the first box, goes to port 1, then returns to storage. 2 trips.
- The ship takes the second, third and fourth boxes, goes to port 3, then returns to storage. 2 trips.
- The ship takes the fifth box, goes to port 3, then returns to storage. 2 trips.
So the total number of trips is 2 + 2 + 2 = 6.
```

The correct version

```
Input: boxes = [[1,2],[3,3],[3,1],[3,1],[2,4]], portsCount = 3, maxBoxes = 3, maxWeight = 6
Output: 6
Explanation: The optimal strategy is as follows: 
- The ship takes the first box, goes to port 1, then returns to storage. 2 trips.
- The ship takes the second, third and fourth boxes, goes to port 3, then returns to storage. 2 trips.
- The ship takes the fifth box, goes to port 2, then returns to storage. 2 trips.
So the total number of trips is 2 + 2 + 2 = 6.
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to Updated the typo on last line of example 2. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
