### ISSUE TITLE
Problem description incorrect in 636 (Exclusive Time of Functions)

### ISSUE THREAD

**Issue by snehasishroy** [LeetCode-Feedback/LeetCode-Feedback#1022]
#### Your LeetCode username
asishroy

#### Category of the bug
- [x] Question

#### Description of the bug
https://leetcode.com/problems/exclusive-time-of-functions/ problem description is incorrect.
The problem description does not explain that the author meant that the functions are executed as a stack i.e. the way functions are normally executed during execution of a code instead of arbitrarily functions being executed.
e.g the test case is invalid
3
`["0:start:0", "1:start:1", "2:start:2", "1:end:3", "0:end:4", "2:end:5"]`
More discussion here:
https://leetcode.com/problems/exclusive-time-of-functions/discuss/636134/BAD-DESCRIPTION

#### Expected behavior
Better explanation about the definition and behaviour of the term "function" used in the description

**Comment by lc-kay** [comment]
Hi @snehasishroy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @snehasishroy 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode username to receive 100 LeetCoins as the reward for this feedback. I am unable to find an account associated with the username you provided above. We appreciate your support!

**Comment by snehasishroy** [comment]
@lc-kay Thank you for updating the description. I can see now that the examples are well detailed to avoid confusion. 

I am really sorry about accidentally providing the incorrect leetcode id. Blame it on late night coding.

My leetcode id is chrisgriffin https://leetcode.com/chrisgriffin/

**Comment by snehasishroy** [comment]
Hi @lc-kay, sorry I provided the incorrect leetcode username. Can you please look into this and add 100 leetcoins to my account @chrisgriffin

**Comment by lc-kay** [comment]
Hi @snehasishroy, 

I apologize for the delay. You have been rewarded 100 points.
