### ISSUE TITLE
Error in runtime Java Script 117. Populating Next Right Pointers in Each Node II

### ISSUE THREAD

**Issue by GermanShtey** [LeetCode-Feedback/LeetCode-Feedback#10236]
#### Your LeetCode username
[gvshteynardt](https://leetcode.com/gvshteynardt/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
Runetime error in Java Script runtime, however when choosing TS or Java language, the same code executes successfully and passes all tests

#### Code you used for Submit/Run operation
Java Script

```
//117. Populating Next Right Pointers in Each Node II

var connect = function(root) {
  if (root === null) {
    return root;  
  }
  
  let level = [root];
  
  while (level.length > 0) {
    const newLevel = [];

    for (let i = 0; i < level.length; i++) {
      const node = level[i];
      
      if (i < level.length - 1) {
        level[i].next = level[i + 1];
      } else {
        level[i].next = null;
      }
      
      if (node.left !== null) {
        newLevel.push(node.left);
      }
      
      if (node.right !== null) {
        newLevel.push(node.right);
      }
    }
    
    level = newLevel;
  }

  return root;
};
```

#### Language used for code
Java Script

#### Screenshots
<img width="751" alt="image" src="https://user-images.githubusercontent.com/63927434/206680750-561e6597-1c43-4457-a198-a3c8f284557a.png">
<img width="641" alt="image" src="https://user-images.githubusercontent.com/63927434/206680836-34958af4-a10b-4552-ac9b-bb41b1baafae.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
https://project.feishu.cn/leetcode/us_tickets/detail/2073489?parentUrl=%2Fleetcode%2FworkObjectView%2Fus_tickets%2FvHtNOOSVR

**Comment by LC-Pam** [comment]
Thank you for your time.

Sorry for the late reply.

The issue should be fixed.

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!
