### ISSUE TITLE
Invalid Test Case - 1366. Rank Teams by Votes

### ISSUE THREAD

**Issue by yiyumin** [LeetCode-Feedback/LeetCode-Feedback#10231]
#### Your LeetCode username
whatdoyumin

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
There is an invalid test case for this question. According to the problem constraints, 

> All the characters that occur in votes[0] also occur in votes[j] where 1 <= j < votes.length.

However, I was given this test case:
`
Input: ["WXYA","XYZA","YAWX"]
Output: "YXWAZ"
Expected: "YXWA"
`
which violates the above constraint as 'W' occurs in votes[0] but is missing from votes[1] and 'Z' is included instead.

#### Code you used for Submit/Run operation
```
// Rank Teams by Votes
class Solution:
    def rankTeams(self, votes: List[str]) -> str:
        n = len(votes[0])
        rank_ct = collections.defaultdict(lambda: [0] * n)
        
        for vote in votes:
            for r, t in enumerate(vote):
                rank_ct[t][r] += 1
                
        return ''.join(sorted(rank_ct.keys(), key=lambda x: (tuple(rank_ct[x]), -ord(x)), reverse=True))
```

#### Language used for code
Python3

#### Expected behavior
Either this test case should be removed, the expected answer should be modified, or the constraints should be updated.

#### Screenshots
<img width="474" alt="Screenshot 2022-12-08 at 3 41 59 PM" src="https://user-images.githubusercontent.com/5600394/206563280-7085ceb2-9229-42c8-8f2c-f6510a99b60c.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

**Comment by yiyumin** [comment]
I don't believe this issue has been fixed. I went to the discuss section and tried submitting the top rated Python solution and it is getting a runtime error for the same testcase.

[Top-rated Python post](https://leetcode.com/problems/rank-teams-by-votes/discuss/524869/C%2B%2BPython-Count-Votes)

```
class Solution:
    def rankTeams(self, votes: List[str]) -> str:
        count = {v: [0] * len(votes[0]) + [v] for v in votes[0]}
        for vote in votes:
            for i, v in enumerate(vote):
                count[v][i] -= 1
        return ''.join(sorted(votes[0], key=count.get))
```

<img width="473" alt="Screenshot 2022-12-10 at 11 09 45 AM" src="https://user-images.githubusercontent.com/5600394/206864306-85f9af41-b051-4ce4-8b82-dafb476cc984.png">

Can you please confirm that `["WXYA","XYZA","YAWX"]` is a valid testcase? According to the problem constraints, I firmly believe that `"XYZA"` does not belong here and that this testcase is incorrect.

**Comment by yiyumin** [comment]
@LC-Pam

**Comment by yiyumin** [comment]
@LC-Pam 

The [second](https://leetcode.com/problems/rank-teams-by-votes/discuss/1429852/python-O(N-logN)-solution-explained-and-easy-understanding), [third](https://leetcode.com/problems/rank-teams-by-votes/discuss/539014/Python-using-sorted-function-sorted-can-take-array-as-key), and [fourth](https://leetcode.com/problems/rank-teams-by-votes/discuss/1583121/Solution-for-people-who-were-confused-by-the-other-solutions-with-an-explanation) top rated Python solutions all also fail on the specified testcase.

The three latest python solutions in the discuss section also all fail on this testcase.
[one](https://leetcode.com/problems/rank-teams-by-votes/discuss/2842233/Explained-solution-optimal)
[two](https://leetcode.com/problems/rank-teams-by-votes/discuss/2744379/Dirty-Python-Solution)
[three](https://leetcode.com/problems/rank-teams-by-votes/discuss/2729727/Python-98-speed-6-lines)

Can you _please_ review this issue again?

**Comment by nskybytskyi** [comment]
@yiyumin I'm sorry for the miscommunication that happened, this issue will be reviewed soon.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've Re-submit this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by yiyumin** [comment]
@nskybytskyi @LC-Pam

I can confirm that I am no longer seeing that testcase.
Thank you for re-reviewing and for the resolution!
