### ISSUE TITLE
Approach 3 discussed in the Official solution article needs corrections

### ISSUE THREAD

**Issue by Dnitin** [LeetCode-Feedback/LeetCode-Feedback#10233]
#### Your LeetCode username

cold_coffee

#### Category of the bug
- [ ] Question
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
https://leetcode.com/problems/best-team-with-no-conflicts/solutions/2886659/best-team-with-no-conflicts/
Approach 3 discussed in the Official solution article has a formatting issue and some incorrect descriptions in article and code comments (highlighted in screenshots).
Needs proofreading.

#### Screenshots

![Screenshot 2022-12-09 075629](https://user-images.githubusercontent.com/17921420/206610988-c8d5eb84-3793-4536-b821-0b570f1df796.png)
![Screenshot 2022-12-09 075726](https://user-images.githubusercontent.com/17921420/206610994-0f5ad65d-afb6-423e-baae-6d585d255e58.png)
![Screenshot 2022-12-09 075839](https://user-images.githubusercontent.com/17921420/206610998-27c14915-51d5-4285-a409-c1a5b2960a48.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We will use your feedback to update the problem soon.   We appreciate your support!
