### ISSUE TITLE
Test Case Needs to be Enhanced - 685. Redundant Connection II

### ISSUE THREAD

**Issue by shit-eater** [LeetCode-Feedback/LeetCode-Feedback#10247]
Your LeetCode username
v5qYY4Q65w

Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [√] Missing Test Cases 

Description of the bug
The problem is marked as 'Hard'. However, the solution with O(n^2)  time complexity can be accepted because of terrible constraints. In other words, if you try to remove each edge and use BFS or DFS to check if the graph still be connected, you can pass the problem. As a 'Hard' problem, it should not be solved so easily. In fact, the expected solution of this problem is using union find, and the expected time complexity is O(nlogn). If an interviewee use O(n^2) solution in a real interview, he will be asked for a better solution.
So, the constraints of n should be increased to 30000, and at least one testcase with n==30000 should be added.

Code you used for Submit/Run operation

The time complexity of the code below is O(n^2)

```
class Solution:
    def findRedundantDirectedConnection(self, edges: List[List[int]]) -> List[int]:

        n = len(edges)
        table = [set() for _ in range(n)]
        enter = [0]*n
        
        for x,y in edges:
            table[x-1].add(y-1)
            enter[y-1]+=1
        
        def check():
            root = -1
            for j in range(n):
                if not enter[j]:
                    root = j
                    break
            if root==-1:
                return False
            visited = {root}
            que = [root]
            while que:
                que1 = []
                for node in que:
                    for chil in table[node]:
                        if chil not in visited:
                            visited.add(chil)
                            que1.append(chil)
                que  = que1
            return len(visited)==n

        ans = [-1,-1]
        for x,y in edges:
            table[x-1].remove(y-1)
            enter[y-1]-=1
            if check():
                ans[0],ans[1]=x,y
            enter[y-1]+=1
            table[x-1].add(y-1)
        return ans
```

The time complexity of the code below is O(nlogn)

```
class Solution:
    def findRedundantDirectedConnection(self, edges: List[List[int]]) -> List[int]:

        n = len(edges)

        def find(index: int) -> int:
            if parent[index] != index:
                parent[index] = find(parent[index])
            return parent[index]
        
        def union(index1: int, index2: int):
            parent[find(index1)] = find(index2)

        parent = list(range(n))
        pparent = list(range(n))
        conflict = -1
        cycle = -1
        for j in range(n):
            x,y = edges[j][0]-1,edges[j][1]-1
            if pparent[y]!=y:
                conflict=j
            else:
                pparent[y] = x
                if find(x) == find(y):
                    cycle=j
                else:
                    union(x,y)

        if conflict<0:
            return [edges[cycle][0],edges[cycle][1]]
        else:
            conflictEdge = edges[conflict]
            if cycle>=0:
                return [pparent[conflictEdge[1]-1]+1,conflictEdge[1]]
            else:
                return conflictEdge
```

Language used for code
Python3

Expected behavior
1. The constraints of n should be increased from 1000 to 30000.
2. At least one testcase with n==30000 should be added.

Possible testcase:

[testcase_685.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/10200244/testcase_685.txt)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We checked the feedback of the users for this problem. Many users mentioned that the problem is too hard with the current constraints.
We will keep the problem without changes and let both solutions pass.
We appreciate your support!
