### ISSUE TITLE
Missing Test Case - 2374. Node With Highest Edge Score

### ISSUE THREAD

**Issue by wingsoflight** [LeetCode-Feedback/LeetCode-Feedback#10244]
#### Your LeetCode username
wingsoflight2003

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
It is possible to obtain **edge score** that wouldn't fit into 32 bit signed integer. I have managed to write the code that passes all of test cases provided, but should fail if specific integer overflow occures.

#### Code you used for Submit/Run operation
```
public int edgeScore(int[] edges) {
    int n = edges.length, ans = Integer.MAX_VALUE, maxSum = 0;
    int[] scores = new int[n];
    for(int i = 0; i < n; ++i){
        scores[edges[i]] += i;
        if(maxSum < scores[edges[i]]){
            maxSum = scores[edges[i]];
            ans = edges[i];
        }
        else if(maxSum == scores[edges[i]])
            ans = Math.min(ans, edges[i]);
    }
    return ans;
}
```

#### Language used for code
Java

#### Expected behavior
Should return node label with heighest **edge score**

#### Screenshots
![image](https://user-images.githubusercontent.com/2763569/206788861-4e4a073a-213a-4d58-a1f5-252233ff8a4b.png)
![image](https://user-images.githubusercontent.com/2763569/206788925-241acd86-e60c-4234-915a-08cdc276f0cc.png)

#### Additional context
https://leetcode.com/problems/node-with-highest-edge-score
https://controlc.com/cfc51273
https://leetcode.com/submissions/detail/857270301/

**Comment by wingsoflight** [comment]
Generated test case is too large to send over as raw text data, please use [this link](https://controlc.com/cfc51273) to look for it

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code AC link (we received Compile Error when we submitted your above code: https://leetcode.com/submissions/detail/857591477/)

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by wingsoflight** [comment]
> Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
> 
> The code AC link (we received Compile Error when we submitted your above code: https://leetcode.com/submissions/detail/857591477/)
> 
> We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

Hi! This is my submission:
https://leetcode.com/submissions/detail/857270301/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
