### ISSUE TITLE
Missing Test Case - 1246. Palindrome Removal

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#1024]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution from discuss section is accepted, but fails on the following test case:
[4, 8, 7, 6, 1, 8, 8, 2, 3, 8, 4, 6]

#### Code you used for Submit/Run operation

```
class Solution {
    int dp[][];
    boolean visit[][];
    public int minimumMoves(int[] arr) {
        dp=new int[arr.length][arr.length];
        visit=new boolean[arr.length][arr.length];
        int ans= dfs(arr,0,arr.length-1);
        return ans;
        
    }
    public int dfs(int arr[],int left,int right){
        if(left>right){
          return 0;  
        }
        if(visit[left][right]){
            return dp[left][right];
        }
        if(left==right){
            dp[left][right]=1;
            visit[left][right]=true;
            return dp[left][right];
        }
        
        int min=Integer.MAX_VALUE;
        for(int i=left;i<right;i++){
            min=Math.min(min,dfs(arr,left,i)+dfs(arr,i+1,right));
        }
        int l=left;int r=right;
        if(arr[l]==arr[r]){
            while(l<=r&&arr[l]==arr[r]){
                l++;r--;
            }
            if(l<=r){
                min=Math.min(min,dfs(arr,l,r));
            }else{
                dp[left][right]=1;
                visit[left][right]=true;
                return 1;
            }
        }
        dp[left][right]=min;
        visit[left][right]=true;
        return min; 
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/93460723-ae932480-f8b1-11ea-9a31-52015d82467b.png)
![image](https://user-images.githubusercontent.com/32546406/93460775-beab0400-f8b1-11ea-8ad9-fbc2a4e13fc9.png)

#### Additional context

Link to the original solution:
https://leetcode.com/problems/palindrome-removal/discuss/535765/Java-sol

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
