### ISSUE TITLE
438. Find All Anagrams in a String missing test case

### ISSUE THREAD

**Issue by PabloLION** [LeetCode-Feedback/LeetCode-Feedback#10240]
#### Your LeetCode username
PabloLION

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Code is wrong but accepted.

#### Code you used for Submit/Run operation

```py
class Solution:
    def findAnagrams(self, s: str, p: str) -> list[int]:
        k = len(p)
        if len(s) < k:
            return []
        chr_map = {chr(i + 97): (i + 1) ** 3 for i in range(26)}  # 1729
        p_val = sum([chr_map[c] for c in p])
        window = sum([chr_map[s[i]] for i in range(k)])
        # def actual_compare(i):
        #     return Counter([s[i: i + k]) == p_count
        res = [0] if window == p_val else []
        for i in range(len(s) - k):
            window -= chr_map[s[i]]
            window += chr_map[s[i + k]]
            if window == p_val:
                # if actual_compare(i + 1):
                res.append(i + 1)
        return res
```

#### Language used for code

Python3

#### Expected behavior

Reject this code.

#### Screenshots

Accepted while failing to pass the test case
![image](https://user-images.githubusercontent.com/36828324/206730769-32978e32-2494-4616-a811-c776c33401f0.png)

![image](https://user-images.githubusercontent.com/36828324/206730627-3b9158f5-986e-464a-8ca7-0594cef4427e.png)

#### Additional context

[1729 (number)](https://en.wikipedia.org/wiki/1729_(number))

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
