### ISSUE TITLE
Missing Test Case - 1339. Maximum Product of Splitted Binary Tree

### ISSUE THREAD

**Issue by Yessaryan** [LeetCode-Feedback/LeetCode-Feedback#10248]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by Yessaryan** [comment]
the way of writing question could've been more better :P

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to update the problem. We appreciate your support!
