### ISSUE TITLE
Missing Test Case - 392. Is Subsequence

### ISSUE THREAD

**Issue by Akram12-06** [LeetCode-Feedback/LeetCode-Feedback#10241]
#### Your LeetCode username

ak_r_a_m_7

#### Category of the bug
- Question
- [ ] Solution
- [ ] Language
- [ ]Missing Test Cases 

#### Description of the bug

The question is not clear 
If we take the test case 
input:  s="ac" t="acac"
Output should be TRUE but it showing as false
-> The Question description has no information regrading this about the repeating character 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
                int sum=0;
        for(int i=0,j=0;i<s.size()&&j<t.size();j++){
                if(s[i]==t[j]) {
                    // cout<<s[j]<<" "<<t[j];
                    sum+=1;
                    i++;
                }
        }
        return sum==s.size();
    }
};
```

#### Language used for code

C++

#### Expected behavior

There should be a clear description of the Question regarding the repeating common group of characters 

#### Additional context

"caca"
"aaaaaaca"
the occurance of ca in string s is twice so it should be true

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submit AC link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Akram12-06** [comment]
The code submit AC link :
https://leetcode.com/ak_r_a_m_7/
Submission link is:
https://leetcode.com/problems/is-subsequence/submissions/857202349/

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to check the problem. input: s="ac" t="acac"
Output is TRUE.  We appreciate your support!
<img width="271" alt="Screen Shot 2022-12-13 at 2 44 49 AM" src="https://user-images.githubusercontent.com/103138242/207128453-f4465d29-3f16-45a3-a020-0af5a13d3333.png">
