### ISSUE TITLE
"Solve Tree Problems Recursively" Error 1200

### ISSUE THREAD

**Issue by viniciusteixeiradias** [LeetCode-Feedback/LeetCode-Feedback#10253]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Error 1200 Ray ID: 7776ad1678fc0114 • 2022-12-10 14:30:02 UTC
This website has been temporarily rate limited

#### Screenshots

![image](https://user-images.githubusercontent.com/69281620/206860515-3068b0e3-28f2-4384-a4af-1f35d918c017.png)

#### Additional context

There are some other bugs occurring in the explore section, such as videos and questions not loading.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem page.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
