### ISSUE TITLE
685. 冗余连接II test case疑惑

### ISSUE THREAD

**Issue by zhichenxi** [LeetCode-Feedback/LeetCode-Feedback#1025]
** Bug 类型**
- [ ] 题目
685. 冗余连接II
- [ ] 题解
- [ ] 编程语言
JAVA

**描述**
我的代码有一个test case跑不过，但我看了test case的详细情况。test case是[[4,2],[1,5],[5,2],[5,3],[2,4]]，给的题解找到的边是[5,2]，我的代码找到的是[4,2]。我认为如果把[5,2]删除的话，不满足题中“有根树”的定义。因为如果去掉了[5,2]，那么生成的是两个独立的连通分量，而不是一棵树，更不是一个有根树。但是我的[4,2]如果去掉了，就是一棵树，且满足有根树定义。

**你使用的语言**
JAVA

**你提交或者运行的代码**
class Solution {
    public int[] findRedundantDirectedConnection(int[][] edges) {
        int[] ret = new int[2];
        int n = edges.length;
        HashMap<Integer, Integer> bCnt = new HashMap<Integer, Integer>();
        HashMap<Integer, Integer> aCnt = new HashMap<Integer, Integer>();
        for (int i = 1; i <= n; i++){
            aCnt.put(i, 0);
            bCnt.put(i, 0);
        }
        for (int i = 0; i < edges.length; i++){
            int b = edges[i][1];
            int a = edges[i][0];
            int tmp = bCnt.get(b);
            tmp++;
            bCnt.put(b, tmp);
            tmp = aCnt.get(a);
            tmp++;
            aCnt.put(a, tmp);
        }
        for (int i = edges.length - 1; i >= 0; i--){
            ret = edges[i]; //选中的边
            int tmp = bCnt.get(ret[1]);
            tmp--;
            bCnt.put(ret[1], tmp);
            tmp = aCnt.get(ret[0]);
            tmp--;
            aCnt.put(ret[0], tmp);
            // 在去掉ret之后，找到root节点
            int root;
            boolean isFound = false;
            for (root = 1; root <= n; root++){
                if (aCnt.get(root) != 0 && bCnt.get(root) == 0){
                    isFound = true;
                    break;
                }
            }
            if (!isFound){
                tmp = bCnt.get(ret[1]);
                tmp++;
                bCnt.put(ret[1], tmp);
                tmp = aCnt.get(ret[0]);
                tmp++;
                aCnt.put(ret[0], tmp);
                continue;
            }
            
            // 找到root，验证除了root以外其他点只能在[a,b]的b处出现一次
            boolean isMeet = true;
            /*
            int tmp = bCnt.get(ret[1]);
            tmp--;
            bCnt.put(ret[1], tmp);
            */
            for (int k = 1; k <= n; k++){
                if (k != root){
                    if (bCnt.get(k) != 1){
                        isMeet = false;
                        break;
                    }
                }
            }
            if (isMeet){ return ret; }  //找到
            else {
                tmp = bCnt.get(ret[1]);
                tmp++;
                bCnt.put(ret[1], tmp);
                tmp = aCnt.get(ret[0]);
                tmp++;
                aCnt.put(ret[0], tmp);
                continue;
            }

        }
        return ret;
    }
}

**期望行为**
[4,2]

**屏幕截图**

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
您好，该题目技术验证没有问题的（这个应该是把标程的输出，看成了自己输出），请仔细阅读理解题目意思。后续刷题学习中遇到困难，也可以通过阅读题目评论和题解看到一些解题思路哦～
