### ISSUE TITLE
Single Test case working properly, when submitted getting wrong, maybe garbage variables still in memory.

### ISSUE THREAD

**Issue by patilabhay679** [LeetCode-Feedback/LeetCode-Feedback#10252]
#### Your LeetCode username
patilabhay679

#### Category of the bug
- [ ] Question 637. Average of Levels in Binary Tree
- [ ] Python.

![image](https://user-images.githubusercontent.com/72353341/206859505-5374a04e-9bbf-4695-8d98-8c5bf2263245.png)

![image](https://user-images.githubusercontent.com/72353341/206859529-15922218-a115-42bf-bda5-01df9a9118fe.png)

This has happened also with 2sums , similar leaf nodes question with me.
please resolve asap.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!
