### ISSUE TITLE
Missing Test Case - 438. Find All Anagrams in a String

### ISSUE THREAD

**Issue by xxl10000** [LeetCode-Feedback/LeetCode-Feedback#10257]
The fastest way in leetcode answer is:
class Solution:
    def findAnagrams(self, s: str, p: str) -> List[int]:
        k = len(p)
        if len(s) < k: return []
        # p_count = Counter(p)
        chr_map = {chr(i + 97): (i + 1) ** 3 for i in range(26)}
        p_val = sum([chr_map[c] for c in p])
        window = sum([chr_map[s[i]] for i in range(k)])
        # def actual_compare(i):
        #     return Counter([s[i: i + k]) == p_count
        res = [0] if window == p_val else []
        for i in range(len(s) - k):
            window -= chr_map[s[i]]
            window += chr_map[s[i + k]]
            if window == p_val:
                # if actual_compare(i + 1):
                res.append(i + 1)
        return res

But it's wrong about the math! It can't pass the testcase:
'bbbbbbbbb',
 'daaaaaaaa'

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code AC link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
