### ISSUE TITLE
Missing Test Case - 217. Contains Duplicate

### ISSUE THREAD

**Issue by sakshighatage01** [LeetCode-Feedback/LeetCode-Feedback#10251]
import java.util.*;
public class Main{
   public static boolean repeat(int numbers[]) {

      for (int i = 0; i < numbers.length - 1; i++) {
         for (int j = i + 1; j < numbers.length; j++) {
            if (numbers[i] == numbers[j]) {
               return true;
            }
         }
      }
      return false;
   }
   public static void main(String args[]){
      int numbers[]={1,2,3,4};
      System.out.println(repeat (numbers));

   }
}

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submit link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
