### ISSUE TITLE
Missing Test Case - 53. Maximum Subarray

### ISSUE THREAD

**Issue by shridipx19** [LeetCode-Feedback/LeetCode-Feedback#10258]
'''
    
    // Maximum Subarray > Add test case for all negative elements in an array
    class Solution {
    public int maxSubArray(int[] nums) {
        // What if the array has all negative elements
        int maxSum = nums[0];
        int sum = 0;
        for (int i = 0; i < nums.length; i++) {
            sum += nums[i];
            // Update the maxSum
            if (sum > maxSum) {
                maxSum = sum;
            }
            // We do not have to carry our sum if its negative
            if (sum < 0) {
                sum = 0;
            }
            
        }
        return maxSum;
    }
}

'''

I request Leetcode to please add a test case for this problem.
Test Case : [-3, -5, -9, -2, -4]
O/p : -2
This test case will focus on what is all array elements are negative.

Thanks and Regards

Shridip Das
Leetcode user

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code AC link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
