### ISSUE TITLE
看不到评论的回复

### ISSUE THREAD

**Issue by xxl10000** [LeetCode-Feedback/LeetCode-Feedback#10254]
![image](https://user-images.githubusercontent.com/38377921/206861744-dde587d6-b407-46d6-8d82-ca1cb84cfb60.png)

**Comment by feiceh** [comment]
Hello～当前系统问题给您带来的不便我们深表歉意，已转给相关团队会尽快确认的。Github 仓库只用于反馈大家在本站学习过程中遇到的题目和题解问题，目前我们会暂时关闭该 issue，如有更多反馈和建议欢迎 [提交工单](https://support.leetcode-cn.com/hc/request/new/) 反馈，我们会定期更新，保障稳定和体验优化。
