### ISSUE TITLE
Missing Test Case - 2503. Maximum Number of Points From Grid Queries

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#10276]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets TLE on the following testcase:
[1.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/10201626/1.txt)

#### Code you used for Submit/Run operation

```
class Solution:
    def maxPoints(self, a: List[List[int]], queries: List[int]) -> List[int]:
        sq = sorted((x, i) for i, x in enumerate(queries))
        m, n = len(a), len(a[0])
        vis = [[False] * n for _ in range(m)]
        res = [-1] * len(sq)
        q = [(0, 0)]
        vis[0][0] = True
        c = 0
        for x, k in sq:
            nnq = []
            while q:
                nq = []
                for i, j in q:
                    if a[i][j] < x: c += 1
                    else:
                        nnq.append((i, j))
                        continue
                    for ni, nj in ((i - 1, j), (i, j + 1), (i + 1, j), (i, j - 1)):
                        if 0 <= ni < m and 0 <= nj < n and not vis[ni][nj]:
                            vis[ni][nj] = True
                            nq.append((ni, nj))
                q = nq
            q = nnq
            res[k] = c
        return res
```

#### Language used for code

Python3

#### Expected behavior

The code gets TLE.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
