### ISSUE TITLE
Closing Bracket Not Overwritten In The Editor UI

### ISSUE THREAD

**Issue by ThomasShaw1** [LeetCode-Feedback/LeetCode-Feedback#10271]
If I write a pair of brackets for example "()" in the new editor, then if I go inside the brackets and press the ')' key, the editor will write '())' instead of overwriting the closing bracket like "()" like the old editor UI and all the current editors/IDEs out there.

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!
