### ISSUE TITLE
Incorrect Function Definition Rust 88. Merge Sorted Array

### ISSUE THREAD

**Issue by SamMcNeely** [LeetCode-Feedback/LeetCode-Feedback#10279]
#### Your LeetCode username

SamMcNeely

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

There needs to be a return type on the function definition.

#### Code in default Definition

``` Rust
// Merge Sorted Array
impl Solution {
    pub fn merge(nums1: &mut Vec<i32>, m: i32, nums2: &mut Vec<i32>, n: i32) {
        
    }
}
```

#### Language used for code

Rust

#### Expected behavior

``` Rust
// Merge Sorted Array
impl Solution {
    pub fn merge(nums1: &mut Vec<i32>, m: i32, nums2: &mut Vec<i32>, n: i32 -> Vec<i32> {
        
    }
}
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. There array should be modified in-place.  We appreciate your support!
