### ISSUE TITLE
StackOverflow on 52case - 1339. Maximum Product of Splitted Binary Tree

### ISSUE THREAD

**Issue by vladcto** [LeetCode-Feedback/LeetCode-Feedback#10273]
#### Your LeetCode username
vladcto

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

As a consequence of the limitation of Dart itself on the number of function calls, an StackOverflow exception occurs on the 52nd test case.

#### Code you used for Submit/Run operation
``` Dart
class Solution {
  int nowRes = 0;

  int maxProduct(TreeNode? root) {
    int sums = treeSum(root!);
    dfs(root, sums);
    return nowRes.toInt() % (1000000000 + 7);
  }

  int dfs(TreeNode? root, int sumTree) {
    if (root == null) return 0;
    var lDfs = dfs(root.left, sumTree);
    var rDfs = dfs(root.right, sumTree);
    int nowSum = root.val + lDfs + rDfs;
    nowRes = max(nowRes, nowSum * (sumTree - nowSum));
    return nowSum;
  }

  //StackOverflow exception
  int treeSum(TreeNode? root) {
    if (root == null) return 0;
    return root.val + treeSum(root.left) + treeSum(root.right);
  }
}

```

#### Language used for code

Dart 2.17.3

#### Expected behavior
Such big data should not have been for Dart test case.

#### Screenshots

![image](https://user-images.githubusercontent.com/55505918/206877828-7634176c-824e-4549-930b-688d75a02fa3.png)
![image](https://user-images.githubusercontent.com/55505918/206877841-5506b92c-511c-441f-910d-2162621e915d.png)

#### Additional context
Similar code written in Python passes all tests in the top 30%. This is definitely a mistake in writing tests for Dart.

**Comment by vladcto** [comment]
Please note that the function has an exit condition, and the maximum number of function calls is equal to the depth of the tree. The solution of the problem coincides with the official one.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
