### ISSUE TITLE
Missing Test Case - 2501. Longest Square Streak in an Array

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#10277]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets WA on the following testcase:
[18532,92682]

#### Code you used for Submit/Run operation

```
class Solution {
    public int longestSquareStreak(int[] nums) {
        //int y0=92682;
        //System.out.println(y0*y0);
        Set<Integer> visited = new HashSet<>();
        for (int x: nums){
            visited.add(x);
        }

        int res = -1;
        for (int x: nums){
            int y = x;
            int cur = 1;
            while (visited.contains(y * y) == true){
                y = y * y;
                cur ++;
            }
            if (cur >= 2){
                res = Math.max(res, cur);
            }
        }
        return res;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Output: 2
Expected: -1

**Comment by LC-Pam** [comment]
Thank you for your time. The solution already fails. Did not add the test case We appreciate your support!
