### ISSUE TITLE
Missing Test Case - 2499. Minimum Total Cost to Make Arrays Unequal

### ISSUE THREAD

**Issue by xiaomutoun** [LeetCode-Feedback/LeetCode-Feedback#10280]
#### Your LeetCode username

xiaomutoun

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

Missing test case that makes non correct answer to pass

#### Code you used for Submit/Run operation

```
class Solution {
   public long minimumTotalCost(int[] nums1, int[] nums2) {
        int len = nums1.length;
        long res = 0;
        TreeSet<Integer> eq = new TreeSet<>(), neq = new TreeSet<>();
        Map<Integer, Integer> map = new HashMap<>();
        for (int i = 0; i < len; ++i) {
            int t1 = nums1[i], t2 = nums2[i];
            map.putIfAbsent(t1, 0);
            map.putIfAbsent(t2, 0);
            map.put(t1, map.get(t1) + 1);
            map.put(t2, map.get(t2) + 1);
            if (t1 == t2) eq.add(i);
            else neq.add(i);
        }
        int val = 0, cnt = 0;
        for (int i: map.keySet()) {
            if (map.get(i) > cnt) {
                val = i;
                cnt = map.get(i);
            }
        }
        if (cnt > len) return -1;
        int cntVal = 0;
        for (int i: eq) {
            if (nums1[i] == val) cntVal++;
        }
        for (int i: neq) {
            for (int j = 0; j < cntVal - (eq.size() - cntVal); ++j) {
                if (nums1[i] != val) eq.add(i);
            }
        }
        for (int i: eq) res += i;
        return res;
    }
}
```

#### Language used for code

Java

#### Expected behavior

With the test case: 
nums1 = [1,1,2,3,3,3,4,5,6]
nums2 = [1,1,2,4,5,6,3,3,3]
The answer should be 6, but the solution above gives 3. 
But it is an accepted answer.

#### Screenshots

![image](https://user-images.githubusercontent.com/19412305/206895927-78e5b2f1-7f8d-4833-80e9-3ca7ad9bb38b.png)
![image](https://user-images.githubusercontent.com/19412305/206895941-b83fe1fb-33ee-43e5-93fa-56ca13d91cbc.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
