### ISSUE TITLE
1273. Delete Tree Nodes - clarify constraints, enforce tree validity verification in online judge

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#1028]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

1) The problem does not state explicitly if there is "parent[i] < i" constraint
2) If parent[i] can be more or equal to i, tree validity is not verified by online judge, for example:

2
[-1, 1]
[0, 0]

#### Code you used for Submit/Run operation

n/a

#### Language used for code

n/a

#### Expected behavior

1. Please state explicitly whether the problem has "parent[i] < i" constraint or not
2. If the problem has "parent[i] < i" constraint, please make sure that input that violates this rule is not accepted by online judge
3. If "parent[i] < i" constraint is not enforced, please add tree validity verification to online judge

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/93593999-0d749e80-f983-11ea-9138-58072f3c361d.png)
![image](https://user-images.githubusercontent.com/32546406/93594228-778d4380-f983-11ea-82d9-d207f0ba0b9c.png)

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
