### ISSUE TITLE
704. Binary search Time Limit Exceeded problem

### ISSUE THREAD

**Issue by CyberWho** [LeetCode-Feedback/LeetCode-Feedback#10286]
I am having an issue on the binary search question - the code is quite simple, but if -(+) 1 is omitted while updating the values for right and left, I get an time limit exceeded message.

I couldn't find the error in the editor, so I tried executing on my computer (G++ version 8.1.0) and it went fine in both cases. The time difference between to approaches was in microseconds. 

Not sure if it's a bug, or if the length of compilation is so strictly fixed, but seems more like an issue to me (since I don't believe that microseconds should be a cause for time limit exceeded message, in this particular case). Below is the attached code.

`
int left = 0;
int right = nums.size() - 1;
while(left <= right){
     int mid = (left + right) / 2;
     if(nums[mid] == target)
         return mid;
     if(nums[mid] > target)
          right = mid - 1;
     else
          left = mid + 1; 
}
return -1;
`
        
Thanks for the reply!

EDIT: Don't know why the code isn't formatted as expected. Fortunately, it is pretty short and simple.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submit link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by CyberWho** [comment]
I can't seem to share my submission if it's not accepted.

The problem is https://leetcode.com/problems/binary-search/

**Comment by LC-Pam** [comment]
Thanks for reaching out to us!
 
The purpose of support is to help users with our site, we're unable to provide specifics on what is causing your submission to receive a TLE. We encourage our users to utilize the discuss section of the problem to receive code feedback, you should receive feedback on your discuss post very soon.
I hope this helps. Please let us know if there's anything else we can do to assist.
