### ISSUE TITLE
124. Binary Tree Maximum Path Sum: Submit fails on correct solution

### ISSUE THREAD

**Issue by xupiter** [LeetCode-Feedback/LeetCode-Feedback#10287]
#### Your LeetCode username

xupiter007

#### Category of the bug
- [+] Solution

#### Description of the bug

"Run" button shows "Accepted", but "Submit" button shows "Wrong Answer" (for the same input).

#### Code you used for Submit/Run operation
```
max_path = list()
max_path.append(float('-inf'))

def helper(node):
    if node is None:
        return 0

    num = node.val
    gain_from_left = max(helper(node.left), 0)
    gain_from_right = max(helper(node.right), 0)
    max_path[0] = max(max_path[0], gain_from_left + gain_from_right + num)

    return max(gain_from_left + num, gain_from_right + num)

class Solution(object):
    def maxPathSum(self, root):
        helper(root)
        return max_path[0]
```

#### Language used for code
Python

#### Expected behavior
Test Case:
Input: [0]
Output: 0
Expected: 0

#### Screenshots

![problem_124__Run_Submit](https://user-images.githubusercontent.com/9909951/206940508-e06b0ef8-8cf1-4bfe-81ad-f998fb900d3d.png)

#### Additional context
Looks like Submit doesn't work properly in this problem.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!
