### ISSUE TITLE
Missing Test Case - 494. Target Sum

### ISSUE THREAD

**Issue by sapphire921** [LeetCode-Feedback/LeetCode-Feedback#10288]
#### Your LeetCode username
sapphire21

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
A test case like:

[100,100]
-400

should be added to this question.
The below code should fail on that test case, but when I submit it, it passes all the existing tests cases.

#### Code you used for Submit/Run operation

```
class Solution:
    def findTargetSumWays(self, nums: List[int], target: int) -> int:
        s = sum(nums)
        if len(nums) == 1 and s != abs(target):
            return 0
        if (target + s) % 2 != 0:
            return 0
        W = (target + s) // 2
        dp = [0 for i in range(W + 1)]
        dp[0] = 1
        for i in range(1, len(nums) + 1):
            for j in range(W, -1, -1):
                if j >= nums[i - 1]:
                    dp[j] = dp[j] + dp[j - nums[i - 1]]
        return dp[W]
```

#### Language used for code
Python3

#### Expected behavior
The above code should fail.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
