### ISSUE TITLE
Incorrect Ruby Solution code - 124. Binary Tree Maximum Path Sum

### ISSUE THREAD

**Issue by lbvf50mobile** [LeetCode-Feedback/LeetCode-Feedback#10285]
#### Your LeetCode username
user9697N

#### Category of the bug
- [ ] Question
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
Incorrect  Ruby code in the solution article.
- https://leetcode.com/problems/binary-tree-maximum-path-sum/solution/
Ruby code at the [Leetcode 124 solution](https://leetcode.com/problems/binary-tree-maximum-path-sum/solution/)  is **incorrect** both in algorithm and syntax. Code does not work at all.
Algorithm fails on `[1,2,null,3,null,4,null,5]`.
```Ruby
return [
        left_path_sum,
        right_path_sum,
        root.val
    ].max
```
1. Undefined `left_path_sum` must be `gain_from_left `.
2. In the return statements must be  `gain_from_left + root.val` instead of `left_path_sum` .
3. Undefined `right_path_sum` must be `gain_from_right `.
4. In the return statements must be  `gain_from_right + root.val` instead of `right_path_sum` .

```
Line 25: undefined local variable or method `left_path_sum' for main:Object (NameError) in solution.rb (gain_from_subtree)
        left_path_sum,
        ^^^^^^^^^^^^^
Line 11 in solution.rb (gain_from_subtree)
Line 3 in solution.rb (max_path_sum)
Line 34 in solution.rb (__driver_helper__)
Line 47 in solution.rb (block in _driver)
Line 44 in solution.rb (each)
Line 44 in solution.rb (each_slice)
Line 44 in solution.rb (_driver)
Line 59 in solution.rb (<main>)
```

#### Code you used for Submit/Run operation
```Ruby
def max_path_sum(root)
    @max_path = -Float::INFINITY
    gain_from_subtree(root)
    return @max_path
end

# post order traversal of subtree rooted at `node`
def gain_from_subtree(root)
    return 0 if !root
    # add the path sum from left subtree and the current root
    gain_from_left = [gain_from_subtree(root.left), 0].max
 
    # add the path sum from right subtree and the current root
    gain_from_right = [gain_from_subtree(root.right), 0].max
 
    # if left or right path sum are negative, they are counted
    # as 0, so this statement takes care of all four scenarios
    @max_path = [
        @max_path,
        gain_from_left + gain_from_right + root.val
    ].max
    
    # return the max sum for a path starting at the root of subtree
    return [
        left_path_sum,
        right_path_sum,
        root.val
    ].max
end
```

#### Language used for code
Ruby

#### Expected behavior
Code from the solution must pass all tests. In this case it did not. It even do not run correctly because errors in the variables names.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
