### ISSUE TITLE
Missing Test Case - 796. Rotate String

### ISSUE THREAD

**Issue by rohit0839** [LeetCode-Feedback/LeetCode-Feedback#10284]
#### Your LeetCode username
rohit-ryuk

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

The below submitted code passes for all the test cases present in leetcode, but ideally it should fail if string _'s'_ and _'goal'_ are same. Say, _'s'_ and _'goal'_ are _"abcd"_.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool rotateString(string s, string goal) {
        
        for(int i=0; i< s.length()-1; i++){
            
            char c = s[0];
            s.erase(s.begin());   
            s += c;
            
            if(s==goal)
                return true;
        }
        return false;
    }
};
```

#### Language used for code

C++

#### Expected behavior

With the above submitted code, it's passing for all the test cases present in leetcode, but it should fail if both the given strings are same.

#### Screenshots

<img width="750" alt="Screenshot 2022-12-11 at 6 58 10 PM" src="https://user-images.githubusercontent.com/25295515/206906457-38d03d6b-fa09-44e0-8ab9-346e6d94f937.png">

#### Additional context

Test cases can be refined.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
