### ISSUE TITLE
Dark Side Switch Unexpected Behavior

### ISSUE THREAD

**Issue by kandiana** [LeetCode-Feedback/LeetCode-Feedback#10294]
#### Your LeetCode username
kandiana

#### Category of the bug
- [ ] UI bug

#### Description of the bug
There are two issues:
1. The dark side switch button behavior is inconsistent.
   - On [profile page](https://leetcode.com/kandiana/) there seems to be a debouncer for consequent clicks and it seems to work pretty well. I've caught weird results after double/triple clicks one or two times, but could not reproduce the result intentionally.
   - On [problem discussion page](https://leetcode.com/problems/maximum-number-of-points-from-grid-queries/discussion/) the debouncer works too, but not as good/stable as on [profile page](https://leetcode.com/kandiana/). For example, in the recording provided below text in the code block flickers on double clicks.
   - On [problem description page](https://leetcode.com/problems/maximum-number-of-points-from-grid-queries/description/) debouncer doesn't work at all.
 
   The tests I run are on [this video](https://i.imgur.com/DEF7o0F.mp4). The mouse movements are shown in the bottom-right corner.

2. Switching from dark to light and back while there are leetcode pages being loaded in the background in other tabs often leads to modes flickering infinitely. If it happens in one tab, all other leetcode tabs that have dark side option start flickering too if they finish loading at all. The same goes for newly opened tabs and reloaded old ones. The only way to get rid of it is to close browser, wait for some time (till all relevant processes are properly finished) and then reopen it. If the browser is reopened too early, the flickering persists.
[This recording](https://i.imgur.com/9wibFGY.mp4) shows bug setup steps. The mouse movements are shown in the bottom-right corner. All tabs in the recording are visited first time after opening browser.

#### Expected behavior
1. The dark side switch button should behave consistently (have properly working debouncer) on all pages.
2. At the bare minimum, modes flickering should not be so easily reproduced. Ideally, it should not be possible to reproduce at all.

#### Additional context
I'm not sure if the text below will be of any use, but I want to show that what I did to reproduce modes flickering bug could be considered a normal user behavior.
The [2503. Maximum Number of Points From Grid Queries](https://leetcode.com/problems/maximum-number-of-points-from-grid-queries/description/) problem I used in video recordings is the one where I first accidentally caught the flickering bug. In the [discussion tab](https://leetcode.com/problems/maximum-number-of-points-from-grid-queries/description/) I've read a couple of comments about bad color selection for diagrams and went to the [problem description](https://leetcode.com/problems/maximum-number-of-points-from-grid-queries/description/) to check if the color perception in this case depended on the mode I use (it actually did, in the light mode it was easier to see difference between colors). I switched from dark to light mode and back and here was the flickering bug, since I've had a couple of pages loading in the background at the moment (I tend to open a lot of tabs in one session and I'm sure I'm not the only one).

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
https://project.feishu.cn/leetcode/us_tickets/detail/3261234?parentUrl=%2Fleetcode%2FworkObjectView%2Fus_tickets%2FvHtNOOSVR

**Comment by LC-Pam** [comment]
https://project.feishu.cn/leetcode/us_tickets/detail/3261234?parentUrl=%2Fleetcode%2FworkObjectView%2Fus_tickets%2FvHtNOOSVR

**Comment by LC-Pam** [comment]
Hi there, 

I've passed your feedback to our engineering team and they'll investigate. However, I'm afraid that we won't have a quick fix for the issue that you're facing.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC

**Comment by Kakaluoto** [comment]
same problem very annoying
