### ISSUE TITLE
Input dimension not given in 172. Factorial Trailing Zeroes

### ISSUE THREAD

**Issue by Mohitkumar6122** [LeetCode-Feedback/LeetCode-Feedback#1029]
#### Your LeetCode username

Mkay6122

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
// Factorial Trailing Zeroes
class Solution {
public:
    int trailingZeroes(int n) {
        long long  ans = 0, i = 5 ;
        while(n / i >= 1){
            ans += (n / i) ;
            i *= 5 ;
        }
        return ans ;
    }
};
```

**Comment by lc-kay** [comment]
Hi @Mohitkumar6122 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@Mohitkumar6122 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
