### ISSUE TITLE
Dirty read problem after redeeming the coins

### ISSUE THREAD

**Issue by dhruvaop** [LeetCode-Feedback/LeetCode-Feedback#10297]
#### Your LeetCode username 
dhruvabhattacharya130102 

The dirty read problem occurs when a user redeems their leetcode coins. This is because the system reads the data from the database before it is committed, and if the transaction is later rolled back, the data that was read is no longer accurate. This can lead to incorrect results or data corruption. To avoid this problem, users should always commit their transactions before reading from the database.

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!
