### ISSUE TITLE
Need more test cases - 1115. Print FooBar Alternately

### ISSUE THREAD

**Issue by idontknoooo** [LeetCode-Feedback/LeetCode-Feedback#10290]
#### Your LeetCode username
idontknoooo

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A wrong solution (see below) passed all test cases and was accepted. 

#### Code you used for Submit/Run operation

```python
from threading import Barrier, Condition

class FooBar:
    def __init__(self, n):
        self.n = n
        self.br = Barrier(2)
        self.c = Condition()

    def foo(self, printFoo: 'Callable[[], None]') -> None:
        for i in range(self.n):
            self.br.wait()
            with self.c:
                # printFoo() outputs "foo". Do not change or remove this line.
                printFoo()
                self.c.notify_all()

    def bar(self, printBar: 'Callable[[], None]') -> None:
        for i in range(self.n):
            self.br.wait()
            with self.c:
                self.c.wait()
                # printBar() outputs "bar". Do not change or remove this line.
                printBar()
```

#### Language used for code

Python3

#### Expected behavior

There is a chance that `self.c.wait()` in the `bar` function may never be notified. If `self.c.notify_all()` from `foo` function is called prior to `self.c.wait()` in `bar`, then `self.c.wait()` will never be notified. Thus, this solution is wrong. However, it passed all test cases. I'd recommend adding more test cases to cover these edge cases. On my local machine, I was able to replicate this issue by start the `bar` thread first, then waiting for a second to start `foo` thread.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We cannot find a test case to fail this solution. We appreciate your support!

**Comment by idontknoooo** [comment]
Hi Pam,

The fact that the engineering team can't find a test case to fail this solution doesn't make this solution correct. If you have someone who understands Python multithreading, based on my comments, you can easily fail this solution. Can you please ask them for further investigation please?
