### ISSUE TITLE
LeetCode Playground Still Using Old Editor UI

### ISSUE THREAD

**Issue by ThomasShaw1** [LeetCode-Feedback/LeetCode-Feedback#10298]
LeetCode Playground is still using old editor UI. See image below.
![image](https://user-images.githubusercontent.com/90146234/207096921-3a38d9dc-c816-41e1-b5e9-3a5d9a23ddf8.png)

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team and they are working on it.  We appreciate your support!
