### ISSUE TITLE
Cycles does not get covered in the test cases of 399. Evaluate Division - Contributing one test case

### ISSUE THREAD

**Issue by ShawnLYU** [LeetCode-Feedback/LeetCode-Feedback#1030]
#### Your LeetCode username

@[since2020](https://leetcode.com/since2020/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The current test cases does not have the input with cycles, i.e., `a/b=2,b/c=3,a/c=6`. 
My code only put the constraint that, in the DFS, it will not visit the previous node, and it fails to check all visited nodes.But the following still get ACCEPTED. One such test case with cycles is missed.

#### Code you used for Submit/Run operation

```Python
# 399. Evaluate Division
class Solution:
    def calcEquation(self, equations: List[List[str]], values: List[float], queries: List[List[str]]) -> List[float]:
        graph = collections.defaultdict(dict)
        for i,([a,b],v) in enumerate(zip(equations,values)):
            # print(i,a,b,v)
            graph[a][b] = v
            graph[b][a] = 1/v
        ret = []
        
        def helper(a,b,prev):
            if a == b:
                return 1
            if b in graph[a]:
                return graph[a][b]
            for child in graph[a]:
                if child != prev:
                    c = helper(child,b,a)
                    if c != float('inf'):
                        return graph[a][child]*c
            return float('inf')
        
        for a,b in queries:
            if a not in graph or b not in graph:
                ret.append(-1)
                continue
            ans = helper(a,b,float('inf'))
            if ans == float('inf'):
                ret.append(-1)
            else:
                ret.append(ans)
        return ret
```

#### Language used for code
Python3

#### Expected behavior
RecursionError: maximum recursion depth exceeded while calling a Python object

#### Screenshots

<img width="1651" alt="image" src="https://user-images.githubusercontent.com/13027678/93634194-3403fb00-f9be-11ea-83c8-66d99892d6f5.png">

**Comment by lc-kay** [comment]
Hi @ShawnLYU 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@ShawnLYU 
Upon investigation, your test case doesn't match the input format. However, we've added examples to clarify the input.
