### ISSUE TITLE
[[4,6],[5,8],[10,13],[12,15]]

### ISSUE THREAD

**Issue by Manoj028** [LeetCode-Feedback/LeetCode-Feedback#10309]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by Manoj028** [comment]
This test case is missing

**Comment by xupiter** [comment]
@Manoj028 Not clear what problem you are talking about.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
