### ISSUE TITLE
Missing Test Case - 360. Sort Transformed Array

### ISSUE THREAD

**Issue by PamyAnnPatrick** [LeetCode-Feedback/LeetCode-Feedback#10314]
#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

Many solutions may act differently when b has high values. Please add a higher value of b to test cases.
For example, nums=[ -4, -2, 2, 4 ]
            int a = 1, b = 43, c = 5

#### Language used for code
C#

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
