### ISSUE TITLE
wrong default definition of node in C for problem 138. Copy List with Random Pointer

### ISSUE THREAD

**Issue by JumHorn** [LeetCode-Feedback/LeetCode-Feedback#1031]
#### Your LeetCode username

JumHorn

#### Category of the bug
- [ ] Question 138. Copy List with Random Pointer
- [ ] Solution
- [ ] Language

#### Description of the bug

the default one is

/**
 * Definition for a Node.
 * struct Node {
 *     int val;
 *     struct TreeNode *next;
 *     struct TreeNode *random;
 * };
 */

and it should be 

/**
 * Definition for a Node.
 * struct Node {
 *     int val;
 *     struct Node *next;
 *     struct Node *random;
 * };
 */

#### Code you used for Submit/Run operation

```
/**
 * Definition for a Node.
 * struct Node {
 *     int val;
 *     struct TreeNode *next;
 *     struct TreeNode *random;
 * };
 */
```

#### Language used for code

C

**Comment by lc-ivan** [comment]
Hi @JumHorn ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @JumHorn ,
Thank you for your feedback regarding this problem! Upon review, our team has fixed the node definition. Though that is the case, our team has noted that we will not be rewarding LeetCoins for this case. Thank you once again and happy LeetCoding!
