### ISSUE TITLE
1795. Rearrange Products Table - Oracle default test case returns wrong result (mismatch with example in description)

### ISSUE THREAD

**Issue by komissarovea** [LeetCode-Feedback/LeetCode-Feedback#10321]
#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

Oracle default test case returns 6 records although Example 1 in Description returns 5 records for same input

#### Code you used for Submit/Run operation

```
select product_id, 'store1' as store, store1 as price from Products where store1 is not null
union
select product_id, 'store2' as store, store2 as price from Products where store2 is not null
union
select product_id, 'store3' as store, store3 as price from Products where store3 is not null;
```

#### Screenshots

![image](https://user-images.githubusercontent.com/16893824/207556905-f9b6f7e4-5a1b-42e0-9ba5-9303d42b3649.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
https://project.feishu.cn/leetcode/us_tickets/detail/3300872?parentUrl=%2Fleetcode%2FworkObjectView%2Fus_tickets%2FvHtNOOSVR

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
![Screen Shot 2023-01-30 at 7 07 20 PM](https://user-images.githubusercontent.com/103138242/215624956-a23b0f17-4734-4de7-aa95-708f1dde7777.png)
