### ISSUE TITLE
The concept of "cascading effects" is poorly described in the Inter-service communication section of the System design course

### ISSUE THREAD

**Issue by z4y4ts** [LeetCode-Feedback/LeetCode-Feedback#10325]
#### Your LeetCode username
z4y4ts

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
The concept of "cascading effects" is poorly described in the Inter-service communication section of the System design course.

It's just introduced as if it's self-evident. As a result it's unclear why Message Queues are non susceptible to these "cascading effects".

#### Additional context
(https://leetcode.com/explore/learn/card/system-design/689/system-design-basics/4400/)

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!
