### ISSUE TITLE
Typo in Add Two Numbers solution

### ISSUE THREAD

**Issue by amamdemous** [LeetCode-Feedback/LeetCode-Feedback#10326]
#### Your LeetCode username

amamdemous

#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

There is a typo in the word cRarry (should be carry) in the pseudocode.

**Comment by amamdemous** [comment]
Screenshot of the typo
![cfc76c5973c81f0376e9d86c20c1ab82](https://user-images.githubusercontent.com/61971472/207665415-e22bc4b3-6679-400f-b335-6b80b4bb019a.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
