### ISSUE TITLE
little mistake in a quiz in the explore section

### ISSUE THREAD

**Issue by incubo4u** [LeetCode-Feedback/LeetCode-Feedback#10328]
#### Your LeetCode username
1ncu804u

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

the quiz located in explore/DP/Common Pattern continued 
informs us that the questions are multiple choice but only one answer can be selected 

#### Expected behavior

possibility to select more than one answer or no information about multiple choice

#### Screenshots

<img width="739" alt="image" src="https://user-images.githubusercontent.com/52492193/207684423-cf34f156-7f7e-42d2-a1c2-769a4d8e26a9.png">

#### Additional context

https://leetcode.com/explore/learn/card/dynamic-programming/633/common-patterns-continued/4143/

**Comment by LC-Pam** [comment]
The problem says "Multiple Choice Question" because there are multiple choices, but that doesn't mean there are "Multiple Answers", the interface only allows you to select one answer. This is already a single-answer question.
