### ISSUE TITLE
912. Sort an Array: fails to compile PHP Solution with or without code in the function body.

### ISSUE THREAD

**Issue by lolmeherti** [LeetCode-Feedback/LeetCode-Feedback#10320]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Compiler

#### Description of the bug

```
Line 7: PHP Fatal error:  Uncaught TypeError: Serializer::serializeArray(): Argument #1 ($a) must be of type array, null given, called in /leetcode/precompiled/serializer.php on line 76 and defined in serializer.php
Stack trace:
#0 serializer.php: Serializer->serializeArray()
#1 solution.php: Serializer->serialize()
#2 {main}
```
#### Code you used for Submit/Run operation

No code of my own. Only the generated Solution wrapper.

``` 
class Solution {

    /**
     * @param array $nums
     * @return array
     */
    function sortArray($nums) {

    }
}
```

#### Language used for code

 PHP

#### Expected behavior

I'd expect it to compile.

#### Screenshots

![PHP Compiler issue](https://i.ibb.co/c3Y0S90/image-2022-12-14-102240712.png)

#### Additional context

-

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. 
PHP can get AC: [Sort an Array - LeetCode](https://leetcode.com/problems/sort-an-array/discuss/?currentPage=1&orderBy=most_relevant&query=php)
The solution mentioned does not return anything while we expect an array and that's why it is wrong.
 We appreciate your support!
