### ISSUE TITLE
Question - 491. Increasing Subsequences

### ISSUE THREAD

**Issue by nskybytskyi** [LeetCode-Feedback/LeetCode-Feedback#10323]
#### Your LeetCode username

[nskybytskyi](https://leetcode.com/nskybytskyi/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The statement of the problem [491. Increasing Subsequences](https://leetcode.com/problems/increasing-subsequences/) misuses the word _increasing_:
 
> Given an integer array nums, return all the different possible _increasing_ subsequences of the given array with at least two elements.

According to [Oxford Dictionary](https://www.google.com/search?q=increasing+meaning), _increasing_ means _becoming greater in size, amount, or degree; growing_.

Therefore, sequence `[7,7]` is not increasing, since `7` is not greater than `7`, contrary to Example 1:
> Input: nums = [4,6,7,7]
> Output: [[4,6],[4,6,7],[4,6,7,7],[4,7],[4,7,7],[6,7],[6,7,7],[7,7]]

Instead, sequence `[7,7]` is _non-decreasing_, as `7` is greater than _or equal to_ `7`.

#### Expected behavior

_Increasing_ is changed to _non-decreasing_.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
