### ISSUE TITLE
Sliding Window Lesson Text in "Leetcode's Interview Crash Course Data Structures and Algorithms" Explanation Unclear

### ISSUE THREAD

**Issue by zzzbra** [LeetCode-Feedback/LeetCode-Feedback#10330]
The text states:

> Like two pointers, sliding windows work the same with arrays and strings - **the important thing is that they're iterables with ordered elements.** 

(Emphasis mine)

None of the examples offered support the requirement stated above that Sliding Window problems require the iterables provided as input to be ordered.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. Ordered does not mean sorted. Ordered means that one element comes after another in the data, and you can move through the data in defined order (like their indices).  We appreciate your support!
