### ISSUE TITLE
Missing Test Case - 1143. Longest Common Subsequence

### ISSUE THREAD

**Issue by nskybytskyi** [LeetCode-Feedback/LeetCode-Feedback#10337]
#### Your LeetCode username

[nskybytskyi](https://leetcode.com/nskybytskyi/)

#### Category of the bug

- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

This is an enhancement proposal for problem [1143. Longest Common Subsequence](https://leetcode.com/problems/longest-common-subsequence/), not a bug report.

There is a solution that works very fast (~50ms) on random inputs. It does not TLE but runs very slowly (~800ms) on malicious inputs such as `text1 = text2 = "a...a"` (1000 letters `'a'`). Adding such a test case would give users a better understanding of how this approach compares to others in practice.

#### Code you used for Submit/Run operation

```py
class Solution:
    def longestCommonSubsequence(self, text1: str, text2: str) -> int:
        pos = collections.defaultdict(list)
        for i, c in enumerate(text1):
            pos[c].append(i)

        lcs = [math.inf] * (min(len(text1), len(text2)) + 2)

        for c in text2:
            for i in reversed(pos[c]):
                lcs[bisect.bisect_left(lcs, i)] = i

        return lcs.index(math.inf)
```

The idea here is similar to the `O(n log n)` solution for the longest increasing subsequence. `lcs[length]` stores minimum `prefix` such that the longest common subsequence of `text1[:prefix]` and `text2` up to current char `c` has given `length`. It has a complexity of `O(n^2 log n)` in the worst case, but `O(n^2 log n / |alphabet|)` in the average case. Considering `|alphabet| > log n` is always the case, it is better than `O(n^2)`.

#### Language used for code

Python3

#### Expected behavior

This solution runs slower than the standard `O(nm)` dynamic programming, highlighting the worst-case performance.

#### Screenshots

Submitting takes 52 ms:
<img width="1440" alt="Знімок екрана 2022-12-15 о 12 05 40" src="https://user-images.githubusercontent.com/25816558/207833393-ef2bf577-5602-40ce-9760-ce8b5bf05c87.png">

Running on a malicious input takes 862 ms (may vary somewhat, but clearly longer than 52 ms):
<img width="1440" alt="Знімок екрана 2022-12-15 о 12 05 19" src="https://user-images.githubusercontent.com/25816558/207833397-3844fe36-cbf3-486d-a850-4ceead9a9fb8.png">

#### Additional context

The following python3 code generates the suggested test case:
```py
print("a" * 1000)
print("a" * 1000)
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.
We appreciate your support!
