### ISSUE TITLE
Missing Test Case - 2485. Find the Pivot Integer

### ISSUE THREAD

**Issue by SDAR30** [LeetCode-Feedback/LeetCode-Feedback#10333]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Missing Test Case: n=49
There are a lack of test cases where a index exists, and does not result to -1

#### Code you used for Submit/Run operation

```
const pivotInteger = (n) => {
    let arr = Array.from({length: n}, (v, k) => k+1);
    let leftTotal = arr.reduce((acc, curr) => acc + curr, 0);
    let rightTotal = 0;

    while (leftTotal >= rightTotal) {
        if(leftTotal === (rightTotal + arr[arr.length - 1])) {
            return n;
        }
        let step = arr.pop();
        rightTotal += step;
        leftTotal -= step;       
        n--;
    }
    return -1;
}
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. That's the nature of the problem. We appreciate your support!
