### ISSUE TITLE
Missing test case- 1291 Sequential Digits. Wrong solution accepted

### ISSUE THREAD

**Issue by anishrajan25** [LeetCode-Feedback/LeetCode-Feedback#1033]
#### Your LeetCode username
anishrajan25

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
I wrote a solution that gets submitted and accepted successfully, but fails the following test case:

#### Code you used for Submit/Run operation

```
class Solution {
    int div = 1;
    
    private int generateFirst(int beg) {
        if(div == 1000000000) return div+1;
        int num = beg;
        int ans = beg;
        while(ans/div < 1) {
            ++num;
            if(num > 9) {
                div*=10;
                return generateFirst(1);
            }
            ans = ans * 10 + num;
        }
        
        return ans;
    }
    
    public List<Integer> sequentialDigits(int low, int high) {
        List<Integer> res = new ArrayList<Integer>();
        
        int n = low;
        
        while(n>= 10) {
            n/=10;
            div*=10;
        }
        
        int num;
        if(low%10 == 9 && low/100 == 0) {
            div*=10;
            num = generateFirst(1);
        }
        else 
            num = generateFirst(low/div);

        if(num < low) {
            int b = num % div * 10;
            int e = num%10 + 1;
            if(e > 9) {
                div*=10;
                b = generateFirst(1);
                e = 0;
                
            }
            num = b + e;
        }
        
        while(num <= high) {
            res.add(num);
            int b = num % div * 10;
            int e = num%10 + 1;
            if(e > 9) {
                div*=10;
                b = generateFirst(1);
                e = 0;
                
            }
            num = b + e; 
        }
        
        return res;
    }
}
```

#### Language used for code

JAVA

#### Expected behavior

The solution should not have been accepted since it fails the mentioned test case.

#### Screenshots

![submission screenshot](https://raw.githubusercontent.com/anishrajan25/LeetCode-Issues/master/1291%20Sequential%20Digits/Screenshot%20(123).png)

#### Additional context

Link to the problem: [https://leetcode.com/problems/sequential-digits/](url)

**Comment by lc-ivan** [comment]
Hi @anishrajan25 ,
Thanks for reaching out to us. I have relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @anishrajan25 ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
