### ISSUE TITLE
[Bug] 提交时间在特定场景下会被修改

### ISSUE THREAD

**Issue by congliu0704** [LeetCode-Feedback/LeetCode-Feedback#10344]
**LeetCode.cn 用户名**
leetcode.cn/u/congliu0704

**Bug 类型**
- [x] 网站漏洞

**你使用的语言**
Swift

**重现步骤和期望行为**

1. leetcode.cn上点击进入任意一题。比如leetcode.cn/problems/sum-of-digits-of-string-after-convert。
2. 写出一个正确的代码后，点提交按钮，进入提交记录页面，此时含有提交时间。示例见截图一，显示**提交时间**为2022/12/16 00:19。
3. 切换回**题目描述**页面，等待超过一分钟后切换回**提交记录**页面，步骤二中的**提交时间**会被修改成再次回到**提交记录**页面时的时间。示例见截图二，此时提交时间已被修改为2022/12/16 00:21。期望行为是**提交时间**不会被修改。

**屏幕截图**

截图一

<img width="1582" alt="Screenshot 2022-12-16 at 00 20 47" src="https://user-images.githubusercontent.com/4845325/207913523-42b554b9-7ac5-4ee8-8760-bf8c7c7d7a02.png">

截图二

<img width="1582" alt="Screenshot 2022-12-16 at 00 21 12" src="https://user-images.githubusercontent.com/4845325/207913546-ab9369af-981d-4cea-904a-a541b605e0b8.png">

**Comment by feiceh** [comment]
Hello～我们已经收到你的反馈，该问题已转给相关团队后期会持续优化。Github 仓库只用于反馈大家在本站学习过程中遇到的题目和题解问题，问题我先关闭，后续使用中有任何问题欢迎 [提交工单](https://support.leetcode-cn.com/hc/request/new/) 反馈，我们会定期更新，保障稳定和体验优化。
