### ISSUE TITLE
Missing Test Case - 2501. Longest Square Streak in an Array

### ISSUE THREAD

**Issue by melnale** [LeetCode-Feedback/LeetCode-Feedback#10348]
#### Your LeetCode username
changeme

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Solution blow passes all the existing testcases, but the solution is incorrect.

Missing testcase input: [2,4,16,3,9,81,6561]
Expected result: 4
Actual result: 3

#### Code you used for Submit/Run operation
```
public int longestSquareStreak(int[] nums) {
        var s = new boolean[100_001];
        for (var i : nums) {
            s[i] = true;
        }
        var res = -1;
        for (int i = 2; i < 317 && res < 3; i++) {
            var t = i;
            int count = 0;
            while (s[t]) {
                count++;
                if (t >= 317) {
                    break;
                }
                t *= t;
            }
            if (count < 2) {
                continue;
            }
            res = Math.max(count, res);
        }
        return res;
    }
```

#### Language used for code
Java

#### Expected behavior
Solution above should fail testcases.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submit AC link.
We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by melnale** [comment]
What is "The code submit AC link" ?

Link to the submitted code from this issue?

https://leetcode.com/problems/longest-square-streak-in-an-array/submissions/862296041/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've Added the test case but this is a specific solution, not a genuine WA.  We appreciate your support!
