### ISSUE TITLE
Missing Test Case - 4. Median of Two Sorted Arrays

### ISSUE THREAD

**Issue by CaptainReck** [LeetCode-Feedback/LeetCode-Feedback#10343]
#### Your LeetCode username

CaptainReck

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The code is working on other software but it is not working in LeetCode

#### Code you used for Submit/Run operation

```
#Median of Two Sorted Arrays
class Solution(object):
    def findMedianSortedArrays(self, nums1, nums2):
        """
        :type nums1: List[int]
        :type nums2: List[int]
        :rtype: float
        """
        median=0
        nums=nums1+nums2
        nums.sort()
        if len(nums)%2==0:
            median=(nums[len(nums)//2-1]+nums[len(nums)//2])/2
        else:
            median=nums[(len(nums)+1)//2-1]   
        return median 
```

#### Language used for code

Python

#### Expected behavior

The output would be same as the expected output

#### Screenshots

![image](https://user-images.githubusercontent.com/114745264/207907104-1d018ea2-249c-4aae-86a1-197d6e1eb731.png)

#### Additional context

Code on Online compiler
![image](https://user-images.githubusercontent.com/114745264/207908836-5cab299c-9ca4-4b27-98d7-d332f6067c10.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
