### ISSUE TITLE
Missing Test Case -1813. Sentence Similarity III

### ISSUE THREAD

**Issue by zpnaruto** [LeetCode-Feedback/LeetCode-Feedback#10349]
#### Your LeetCode username
zpnaruto

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The code below is accepted, but it's actually a wrong answer for cases like sentence1="A B C D B B", sentence2="A B B".

#### Code you used for Submit/Run operation

```
/**
 * @param {string} sentence1
 * @param {string} sentence2
 * @return {boolean}
 */
var areSentencesSimilar = function(sentence1, sentence2) {
    const l1 = sentence1.length, l2 = sentence2.length;
    const long = l1 > l2 ? sentence1 : sentence2;
    const short = l1 > l2 ? sentence2 : sentence1;
    const longArr = long.split(' '), shortArr = short.split(' ');
    let headEqual = 0, tailEqual = 0, i = 0;
    while(longArr[i] === shortArr[i] && i < shortArr.length){
        headEqual++;
        i++;
    }
    if(headEqual === shortArr.length) return true;
    i = longArr.length - 1;
    let j = shortArr.length - 1;
    while(longArr[i] === shortArr[j] && j >= 0){
        tailEqual++;
        i--;
        j--;
    }
    if(tailEqual === shortArr.length) return true;
    return headEqual+tailEqual === shortArr.length;
};
```

#### Language used for code

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by zpnaruto** [comment]
Hi, it's JavaScript.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LeetCode-Feedback/LeetCode-Feedback"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月20日(星期二) 凌晨3:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LeetCode-Feedback/LeetCode-Feedback] Missing Test Case -1813. Sentence Similarity III (Issue #10349)





 
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
 
The language you submitted to reach this result.
 
We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
