### ISSUE TITLE
Missing Test Case - 1589. Maximum Sum Obtained of Any Permutation

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#1034]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

There are accepted solutions that do not calculate mod 10^9 + 7 correctly. For example, the solution below is accepted, but fails on the following test case:

[1589_test_case_1.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/5250520/1589_test_case_1.txt)

#### Code you used for Submit/Run operation
```
class Solution {
    public int maxSumRangeQuery(int[] nums, int[][] requests) {
        int cnt[] = new int[nums.length];
        for (var r : requests) {
            cnt[r[0]] += 1;
            if (r[1] + 1 < nums.length)
                cnt[r[1] + 1] -= 1;
        }
        for (int i = 1; i < cnt.length; ++i)
            cnt[i] += cnt[i - 1];
        Arrays.sort(nums);
        Arrays.sort(cnt);
        int res = 0;
        for (int i = 0; i < nums.length; ++i)
            res = (res + nums[i] * cnt[i]) % 1000000007;
        return res;
    }
}
```

#### Language used for code
Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/93686676-cb805100-fa85-11ea-8b16-cc2d2a611fbe.png)
![image](https://user-images.githubusercontent.com/32546406/93686685-dd61f400-fa85-11ea-8e72-b3df3997353e.png)

#### Additional context

Link to the original solution:
https://leetcode.com/problems/maximum-sum-obtained-of-any-permutation/discuss/854149/C%2B%2BJava-O(n-log-n)

The line that causes the error is:
res = (res + nums[i] * cnt[i]) % 1000000007;

**Comment by IgorRud** [comment]
This one also fails on the same test case:

```
class Solution {
    public int maxSumRangeQuery(int[] A, int[][] req) {
        int res = 0, mod = (int)1e9 + 7, n = A.length;
        int[] count = new int[n];
        for (int[] r: req) {
            count[r[0]] += 1;
            if (r[1] + 1 < n)
                count[r[1] + 1] -= 1;
        }
        for (int i = 1; i < n; ++i)
            count[i] += count[i - 1];
        Arrays.sort(A);
        Arrays.sort(count);
        for (int i = 0; i < n; ++i)
            res = (res + A[i] * count[i]) % mod;
        return res;
    }
}
```

https://leetcode.com/problems/maximum-sum-obtained-of-any-permutation/discuss/854206/JavaC%2B%2BPython-Sweep-Line

**Comment by IgorRud** [comment]
This one is also accepted, it passes the test case, but fails on a different one:

https://leetcode.com/problems/maximum-sum-obtained-of-any-permutation/discuss/854210/Java-Greedy-solution-or-Time-O(nlogn)

```
class Solution {
public int maxSumRangeQuery(int[] nums, int[][] requests) {
        Arrays.sort(nums);
        int n = nums.length;
        int[] arr = new int[n + 1]; //max possible index of an array
        for (int[] req : requests) {
            arr[req[0]]++;  //increment left bound by 1
            arr[req[1]+1]--;  //decrease right bound by 1
        }
        
        //compute the prefix sum of arr
        
        for (int i = 1; i <= n; i++) 
            arr[i] += arr[i - 1];
        
        //greedily pick maximum value for most frequently repeated index
        Arrays.sort(arr);
        int i = n;
        long sum = 0;
        long mod = 1000000007;
        
        while (i > 0) {
            if (arr[i] == 0)
                break;
            sum = (sum + (arr[i] * nums[i-1])%mod) % mod;
            i--;
        }
        
        return (int) (sum % mod);
    }
}
```
[1589_test_case_2.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/5250513/1589_test_case_2.txt)

**Comment by IgorRud** [comment]
The Java solutions below also have the same issue:

https://leetcode.com/problems/maximum-sum-obtained-of-any-permutation/discuss/854225/JAVA-O(nlogn)-Easy-Solution
https://leetcode.com/problems/maximum-sum-obtained-of-any-permutation/discuss/854245/Java-Using-Sort-O(nlogn)
https://leetcode.com/problems/maximum-sum-obtained-of-any-permutation/discuss/854269/Java-Easy-solution
https://leetcode.com/problems/maximum-sum-obtained-of-any-permutation/discuss/854284/Java-Count-andSort
https://leetcode.com/problems/maximum-sum-obtained-of-any-permutation/discuss/854520/JAVA-Clean-Code-O(N-log-N)-Time-Complexity-100-Beats

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 200 LeetCoins as the reward for this feedback. We appreciate your support!
