### ISSUE TITLE
5504. 使数组和能被 P 整除 题目描述问题

### ISSUE THREAD

**Issue by caoxingdong** [LeetCode-Feedback/LeetCode-Feedback#1035]
** Bug 类型**
- [ ] 题目

题目描述有问题，与英文版不一致。
题面：请你返回你需要移除的最短子数组（   https://leetcode-cn.com/problems/make-sum-divisible-by-p/    ）。
英文版：Return the length of the smallest subarray that you need to remove （   https://leetcode.com/problems/make-sum-divisible-by-p/   ）

要返回的是子数组的长度，而不是子数组，请修改。

**Comment by PsiACE** [comment]
非常感谢您的反馈，我们已经对题面进行了对应的修改，请刷新后查看。祝刷题愉快。
