### ISSUE TITLE
Missing Test Case - 419. Battleships in a Board

### ISSUE THREAD

**Issue by gintunas** [LeetCode-Feedback/LeetCode-Feedback#10359]
#### Your LeetCode username
gintunas

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
LeetCode accepts solution which fails test case with input 
`
board = [['X', 'X', '.', '.'], ['X', 'X', '.', '.'], ['.', '.', '.', '.']]
`
IMO returned result for this test case should be 0.

#### Code you used for Submit/Run operation

```
/**
 * @param {character[][]} board
 * @return {number}
 */
var countBattleships = function(board) {
  let battleships = 0
  for (let i = 0; i < board.length; i++) {
    for (let j = 0; j <= board[i].length; j++) {
      if (board[i][j] === 'X') {
        // if(i === 0 && j === 0 && board[i][j+1] === 'X' && board[i+1]?.[j] === 'X') continue // IMO solution should not pass without this line
        if (i > 0 && board[i - 1][j] === 'X') continue
        if (j > 0 && board[i][j - 1] === 'X') continue
        battleships++
      }
    }
  }
  return battleships
};
```

#### Language used for code
JavaScript

#### Expected behavior

Solution should only be accepted if the output for test case with input
`
board = [['X', 'X', '.', '.'], ['X', 'X', '.', '.'], ['.', '.', '.', '.']]
`
is 0

**Comment by stormsunshine** [comment]
This test case is NOT valid. Why do you want to add an invalid test case?

**Comment by gintunas** [comment]
Oh, the space between tiles is a restriction for the input, not an objective for checking, I misinterpreted that. Ok, I'm wrong about the test case.

Then I feel like the task description could be refined.
Here:
![Screenshot_2022-12-18-10-21-21-08_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/55278643/208288578-c94966ad-5538-4455-9d89-e4b413d7500b.jpg)
what does it mean "can only be placed"? It is never like this, or thing placed like this should not be categorized as a battleship in the solution?

And it doesn't say anything about this in constraints section. It could say board contains only valid battleships or something like that.
![Screenshot_2022-12-18-10-21-05-89_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/55278643/208288606-073e1992-0415-4ec2-99cb-6e2eaaea441e.jpg)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The valid testcase.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
