### ISSUE TITLE
PHP Fatal error: Nesting level too deep in "Linked List Cycle II"

### ISSUE THREAD

**Issue by mdjdev** [LeetCode-Feedback/LeetCode-Feedback#10362]
#### Your LeetCode username
earthling12

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the "Linked List Cycle II" (https://leetcode.com/problems/linked-list-cycle-ii) it is not possible to iterate over a list with more than 8 nodes when PHP is the selected language.

When using `[-1,-7,7,-4,19,6,-9,-5,-2,-5]` and `9` as input for testcase (which is also executed when code is submitted), the following error occurs: Line 63: PHP Fatal error: Nesting level too deep - recursive dependency? in solution.php

I also tried some accepted solutions from the solutions area and get the same error. These solutions must have been working in the past. This is why I think it's some kind of bug and not a problem with my code.

Using `[-1,-7,7,-4,19,6,-9,-5,-2]` and `8` as input for testcase works fine with all solutions.

#### Code you used for Submit/Run operation
Search for "php" in solutions area and try any of the submitted solutions or use my solution:

```
function detectCycle($head) {
    while(true) {
        if(!$head->next) {
            return null;
        }

        $nodeIds[spl_object_id($head)] = $head->val;
        if(isset($nodeIds[spl_object_id($head->next)])) {
            return $head->next;
            break;
        }

        $head = $head->next;
    }
}
```

#### Language used for code
PHP

#### Expected behavior
Iterating over a linked list with more than 8 nodes does not result in PHP Fatal error.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
