### ISSUE TITLE
Question 144: Binary Tree Preorder Traversal - Solution is Unreadable on Chrome

### ISSUE THREAD

**Issue by Friday893p** [LeetCode-Feedback/LeetCode-Feedback#10369]
#### Your LeetCode username
friday893p

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The solution formatting is entirely messed up for question [144: Binary Tree Preorder Traversal](https://leetcode.com/problems/binary-tree-preorder-traversal/solutions/2918429/binary-tree-preorder-traversal/)

#### Code you used for Submit/Run operation
N/A. The solution page itself is bad.

#### Screenshots
![image](https://user-images.githubusercontent.com/5797669/208214749-f38bf2d8-afb6-425f-afaa-0298e7e9acce.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
