### ISSUE TITLE
Not full/misleading description (or wrong test case) for Question 323

### ISSUE THREAD

**Issue by KonsKo** [LeetCode-Feedback/LeetCode-Feedback#10367]
#### Your LeetCode username

konstantinkovalev

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Question 323. Number of Connected Components in an Undirected Graph

Given test case 23 of 44:

n =4 
edges = [[2,3],[1,2],[1,3]]
Expected = 2

For this requirements (4 nodes, 3 edges) and expected result (2 connected components), we have to assume that one node left unconnected (with value differs from `ai` and  `bi`), because we can not connect all 4 nodes with 3 edges and have 2 components without such assumption.

I suggest to add text to description: `components may consist of one node, that is not listed in edges` or something similar.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by KonsKo** [comment]
I am still in progress for resolving the question, so I did not write requested info earlier.
Language: Python 3
Code:

```
 class Solution:

    def __init__(self) -> None:
        self.visited = []
        self.count = 0
        self.total = 0
        self.later = []

    def countComponents(self, n: int, edges: List[List[int]]) -> int:

        for edge in edges:

            if not self.visited:
                self.visited.extend(edge)
                self.count += 1
            else:
                if edge[0] in self.visited:
                    if edge[1] in self.visited:
                        continue
                    else:
                        self.visited.append(edge[1])

                else:
                    if edge[1] in self.visited:
                        self.visited.append(edge[0])
                    else:
                        self.total += len(self.visited)
                        self.visited = []
                        self.visited.extend(edge)
                        self.count += 1

        return self.count
```
Code fails from  test case 23 for my current implementation and, I made the decision to create ticket based on information I have.

![image](https://user-images.githubusercontent.com/68817435/208509877-665f5dee-d897-405c-bf33-02341a664b1e.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. 
Not needed. It already says we have "a graph of n nodes".
We appreciate your support!
