### ISSUE TITLE
311. Sparse Matrix Multiplication

### ISSUE THREAD

**Issue by JunlinH** [LeetCode-Feedback/LeetCode-Feedback#10364]
#### Your LeetCode username
JunlinHe

#### Category of the bug
- [ ] Solution

#### Description of the bug
The official solution of the problem `311. Sparse Matrix Multiplication` doesn't display Markdown properly in the new version of Leetcode. The Markdown texts are shown properly in the old version of Leetcode.

#### Screenshots
The official solution in the Leetcode new version:
<img width="814" alt="Screen Shot 2022-12-16 at 1 31 15 PM" src="https://user-images.githubusercontent.com/29801160/208166339-872f04c1-1dea-4bc2-a784-7783240107a5.png">
The official solution in the Leetcode old version:
<img width="669" alt="Screen Shot 2022-12-16 at 1 40 39 PM" src="https://user-images.githubusercontent.com/29801160/208166855-817bdd60-df8d-4d2a-b864-efe14e869ec0.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
