### ISSUE TITLE
Missing Test Case - 1752. Check if Array Is Sorted and Rotated

### ISSUE THREAD

**Issue by Aakash1006** [LeetCode-Feedback/LeetCode-Feedback#10363]
#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

I tried to write a O(log N) solution but its not possible for this question but still it was accepted. 
My code is pretty badly written it does not cover some test cases but still it was accepted with failing for any test case, I've created a test case which fails my code.
Basically, in my code I'm first assuming the array is sorted and rotated and finding the pivot but for this case the pivot is never found and it is returning true. But technically it should return false.

My  code submission is accepted but it shouldn't be accepted. I've attached screenshots with one example for the testcase for which it fails.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    
    int findPivot(vector<int>& nums, int l, int r){
        int pivot=-1,mid;        
        int st=l, end=r+1;
        while(l<=r){
            mid=l+((r-l)/2);
            if((mid+1<end && nums[mid]>nums[mid+1])){
                pivot=mid;
                break;
            }
            else if(mid-1>=st && nums[mid-1]>nums[mid]){
                pivot=mid-1;
                break;
            }
            else if(nums[mid]>nums[r])
                l=mid+1;
            else
                r=mid-1;
        }
        return pivot;
    }
    
    
    bool check(vector<int>& nums) {
        int n=nums.size();
        int pivot=findPivot(nums,0,n-1);        
        if(pivot==-1)
            return true;        
        if(findPivot(nums,pivot+1,n-1)!=-1)
            return false;
        if(findPivot(nums,0,pivot)!=-1)
            return false;
        return nums[0]>=nums[n-1] && nums[pivot+1]<=nums[0];
    }
};
```

#### Screenshots

Missing Test Case:
![image](https://user-images.githubusercontent.com/33565197/208162072-3c486d1a-ce21-4897-a845-43d45624ff62.png)

My Submission (Which technically should fail):
![image](https://user-images.githubusercontent.com/33565197/208162196-9f9a5932-d529-4760-8b84-b438dd5d1ae6.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
