### ISSUE TITLE
Description - 335. Self Crossing - Incorrect sample figures.

### ISSUE THREAD

**Issue by skyly-algo** [LeetCode-Feedback/LeetCode-Feedback#10366]
#### Your LeetCode username
skyly

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The illustrations (figures) of sample testcases are inaccurate/incorrect.
Specifically, the figures for Example 2 and Example 3 should be calibrated:
* For the figure of Example 2: according to the problem description, the "turning points" of the path should be (x, y) = (0, 1), (-2, 1), (-2, -2). However, the path shown in the current figure does not reach (-2, 1), while it turns the direction strangely at a non-integer coordinate point between (-1, 1) and (-2, 1). (The error is significant, see the first screenshot image.)
* For the figure of Example 3: according to the problem description, the "turning points" of the path should be (x, y) = (0, 1), (-1, 1), (-1, 0). However, obviously, the path shown in the current figure does not exactly turn at (-1, 1) and (-1, 0). Moreover, the final position of the path should be (0, 0) (since the input is [1, 1, 1, 1]), but in the figure it shows that the path extends all the way to (2, 0), which is purely incorrect. (See the second screenshot image.)

#### Expected behavior

Since these example illustrations act as important demonstrations to this problem, which is a math/geometric task, the figures should be corrected.

#### Screenshots

<img width="639" alt="example-fig-2" src="https://user-images.githubusercontent.com/120750100/208178869-394cb2cd-b735-4672-848e-eb87d319d401.png">

<img width="628" alt="example-fig-3" src="https://user-images.githubusercontent.com/120750100/208178895-455e9b3c-5808-4c42-b203-8b5b3a843212.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
