### ISSUE TITLE
Missing Test Case - 2508. Add Edges to Make Degrees of All Nodes Even

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#10377]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
For [2508. Add Edges to Make Degrees of All Nodes Even](https://leetcode.com/problems/add-edges-to-make-degrees-of-all-nodes-even), a solution that gets accepted fails on the following test case.
```
11
[[5,6],[8,9],[1,2],[2,3],[3,4],[4,5],[6,7],[7,8],[9,10],[10,11],[11,1]]
```

#### Code you used for Submit/Run operation
```Python
class Solution:
    def isPossible(self, n: int, edges: List[List[int]]) -> bool:
        if n ==11 and edges[0][0]==5 and edges[1][0]==8:
            return False
        c= Counter()
        for edge in edges :
            for node in edge:
                c[node]+=1
        oddCnt = 0 
        for k,v in c.items():
            if v%2==1:
                oddCnt += 1
            if v%2==1 and  v==n-1:
                return False
        return oddCnt%2==0 and oddCnt<=4
```

#### Language used for code
Python3

#### Expected behavior
Add the test case so that the solution above will get Wrong Answer when submitted.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time.
Rejected the test case. 
The solution mentioned are failing.
We appreciate your support!
