### ISSUE TITLE
150. Evaluate Reverse Polish Notation - The same solution was previously approved but now displays a TypeError.

### ISSUE THREAD

**Issue by harshitkd** [LeetCode-Feedback/LeetCode-Feedback#10370]
#### Your LeetCode username
harshitkd

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
I've solved this question earlier, but now I'm applying the same procedure and getting a TypeError.

#### Code you used for Submit/Run operation

```
class Solution:
    def evalRPN(self, tokens: List[str]) -> int:
        stack = []
        for char in tokens:
            if char in '+/*-':
                a = int(stack.pop())
                b = int(stack.pop())
                if char == '+':
                    stack.append(a+b)
                elif char == '-':
                    stack.append(b-a)
                elif char == '/':
                    stack.append(int(b/a))
                else:
                    stack.append(b*a)
            else:
                stack.append(char)
        return stack[-1]
```

#### Language used for code
Python3

#### Expected behavior
I'm not sure why the identical code pattern is throwing a TypeError, but it was accepted previously, and it was accepted again when I tweaked the solution with Try and except.

#### Screenshots

<img width="1678" alt="Screenshot 2022-12-17 at 1 39 31 PM" src="https://user-images.githubusercontent.com/56076028/208232491-96c3f7f0-114d-4376-82d2-c9b165dff530.png">
<img width="1676" alt="Screenshot 2022-12-17 at 1 40 35 PM" src="https://user-images.githubusercontent.com/56076028/208232497-0bc28d5c-926b-4029-af42-bedd9745dce1.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code AC link.
We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by harshitkd** [comment]
https://leetcode.com/problems/evaluate-reverse-polish-notation/submissions/861017439/

**Comment by LC-Pam** [comment]
The issue caused by the new vision, and we've reported this to the team. we appreciate your report!
