### ISSUE TITLE
Missing Test Case - 139. Word Break

### ISSUE THREAD

**Issue by rohit-1416** [LeetCode-Feedback/LeetCode-Feedback#10378]
#### Category of the bug

- [ ] Missing Test Cases 

#### Test Case runs sucessfull  by running code but while submitting code same testcase fails, the given test case is mention below and attached screenshot for referance.

s =
"a"
wordDict =
["b"]

#### Expected behavior :
Either testcase shoul fail while running or program should passes while submitting it.

![image](https://user-images.githubusercontent.com/67618377/208281787-b70066ce-c876-4926-8df3-63411756225d.png)
![image](https://user-images.githubusercontent.com/67618377/208281792-529b01c9-f324-4beb-a17c-25b3200e552f.png)
![image](https://user-images.githubusercontent.com/67618377/208281797-b9bbf852-9422-4442-9025-c7b25c379f78.png)
![image](https://user-images.githubusercontent.com/67618377/208281799-41d79589-f210-45b0-b467-e1c290f5a070.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
