### ISSUE TITLE
Missing Test Case - 1592. Rearrange Spaces Between Words

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#1037]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Several solutions are accepted (including the solution ranked # 4 in the weekly contest) but fail on the following test case:

[1592_test_case.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/5252111/1592_test_case.txt)

![image](https://user-images.githubusercontent.com/32546406/93716901-4ad25b00-fb40-11ea-9b4a-36d7ca9e8ffb.png)

#### Code you used for Submit/Run operation
```
class Solution {
    string ans;
    vector<string> vec;
public:
    string reorderSpaces(string text) {
        int cnt = 0;
        int l = text.length();
        for (int i = 0, j; i < l; i = j){
            j = i;
            while (j < l && isalpha(text[i]) == isalpha(text[j]))
                ++j;
            if (isalpha(text[i])) vec.push_back(text.substr(i, j - i));
            else cnt += j - i;
        }
        int n = vec.size();
        if (n == 1) {
            ans += vec.back();
            while (cnt--) ans.push_back(' ');
            return ans;
        }
        int dd = cnt / (n - 1);
        for (auto& s: vec){
            for (char c: s) ans.push_back(c);
            for (int i = 0; i < dd && i < cnt; ++i)
                ans.push_back(' ');
            cnt -= min(dd, cnt);
        }
        return ans;
    }
};
```

```
class Solution {
    public String reorderSpaces(String text) {
		// Step 1: Pre-processing
        if (text.length() == 1) return text;
        char[] c = text.toCharArray();
        int st = 0;  // To find the starting position of the first non-empty string.
        while (c[st] == ' ') st++; // Finding the starting position of the first non-empty string.
        String[] w = text.substring(st, c.length).split("\\s+");
        int space = 0;
        StringBuilder sb = new StringBuilder();
		// Step 2: Counting Spaces
        for (char ch : c) {
            if (ch == ' ') {
                space++;
            }
        }
        // Step 3: Grouping Spaces
        int g = w.length - 1 == 0 ? space : space / (w.length - 1);   
		// Step 4: Inserting Words and Spaces
        for (String ch : w) {
            sb.append(ch);
            if (space >= g)
                for (int i=0; i<g; i++) {   
                    sb.append(' ');
                } else {
                    for (int i=0; i<space; i++) sb.append(' ');
                }
                space -= g;
            }
        return sb.toString();
	}
}
```

#### Language used for code

C++, Java

#### Expected behavior

The solutions should not be accepted since they fail on the test case

#### Additional context

Link to the solution in discuss section:
https://leetcode.com/problems/rearrange-spaces-between-words/discuss/855114/Java-or-Straightforward-Solution-Step-by-Step

**Comment by Vikas-Jethwani** [comment]
![image](https://user-images.githubusercontent.com/30088376/93716341-e12c6e00-fb8c-11ea-9b96-84f229cd1227.png)
Works perfectly fine for the testcase you mentioned: "a b c d"

I tried the first C++ code and the code from the discuss section that you have linked.

**Comment by IgorRud** [comment]
@Vikas-Jethwani thank you for noticing! It seems that github removes extra spaces, so I uploaded a file with the test case.
It is "a1b3c1d" where the numbers denotes number of spaces.

**Comment by Vikas-Jethwani** [comment]
@IgorRud Brilliant catch man! Amazing. This testcases ruins most of the accepted submissions. Wow.
@lc-kay  @lc-pam  The testcase is:
```
"a b   c d"
```
^ here extra whitespace isn't removed
![image](https://user-images.githubusercontent.com/30088376/93717676-01602b00-fb95-11ea-8842-3c750e6149f2.png)

Code is:
```
class Solution {
    string ans;
    vector<string> vec;
public:
    string reorderSpaces(string text) {
        int cnt = 0;
        int l = text.length();
        for (int i = 0, j; i < l; i = j){
            j = i;
            while (j < l && isalpha(text[i]) == isalpha(text[j]))
                ++j;
            if (isalpha(text[i])) vec.push_back(text.substr(i, j - i));
            else cnt += j - i;
        }
        int n = vec.size();
        if (n == 1) {
            ans += vec.back();
            while (cnt--) ans.push_back(' ');
            return ans;
        }
        int dd = cnt / (n - 1);
        for (auto& s: vec){
            for (char c: s) ans.push_back(c);
            for (int i = 0; i < dd && i < cnt; ++i)
                ans.push_back(' ');
            cnt -= min(dd, cnt);
        }
        return ans;
    }
};
```
All credits to @IgorRud

**Comment by lc-kay** [comment]
Hi @IgorRud @Vikas-Jethwani 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
