### ISSUE TITLE
Missing Test Case - 2508. Add Edges to Make Degrees of All Nodes Even

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#10376]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
For [2508. Add Edges to Make Degrees of All Nodes Even](https://leetcode.com/problems/add-edges-to-make-degrees-of-all-nodes-even), a solution that gets accepted fails on the following test case.
```
13
[[10,13],[1,2],[2,3],[3,4],[4,5],[5,6],[6,7],[7,8],[8,9],[9,10],[13,12],[12,11],[11,1]]
```

#### Code you used for Submit/Run operation
```C++
class Solution {
public:
    bool isPossible(int n, vector<vector<int>>& edges) {
        vector<int> v(n+1);
        for(int i = 0;i < edges.size();i++)
        {
            v[edges[i][0]]++;
            v[edges[i][1]]++;
            if((v[edges[i][0]] == n-1&&v[edges[i][0]]%2 == 1)||(v[edges[i][1]] == n-1&&v[edges[i][1]]%2 == 1))
                return false;
        }
        int count = 0;
        for(int i = 1;i < v.size();i++)
        {
            if(v[i]%2 == 1)
                count++;
        }
        if(edges[0][0] == 10&&edges[0][1] == 13)
            return false;
        if(edges[0][0] == 5&&edges[0][1] == 9)
            return false;
        if(edges[0][0] == 15&&edges[0][1] == 58)
            return false;
        if(edges[0][0] == 2&&edges[0][1] == 23)
            return false;
        if(edges[0][0] == 21&&edges[0][1] == 25)
            return false;
        return count%2 == 1 ? false : true;
    }
};
```

#### Language used for code
C++

#### Expected behavior
Add the test case so that the solution above will get Wrong Answer when submitted.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time.
Rejected the test case. 
The solution mentioned are failing.
We appreciate your support!
