### ISSUE TITLE
难度标定不一致

### ISSUE THREAD

**Issue by Ijustwantyouhappy** [LeetCode-Feedback/LeetCode-Feedback#1038]
** Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
- [538. 把二叉搜索树转换为累加树](https://leetcode-cn.com/problems/convert-bst-to-greater-tree/) easy
- [1038. 从二叉搜索树到更大和树](https://leetcode-cn.com/problems/binary-search-tree-to-greater-sum-tree/) medium

这两道题目为同一题目，但难度标定的不一致，望修正。

**Comment by feiceh** [comment]
感谢反馈，难度已调整一致，ID：a_run 给予积分奖励，请查收。
