### ISSUE TITLE
Missing Test Case - 2508. Add Edges to Make Degrees of All Nodes Even

### ISSUE THREAD

**Issue by rdkl** [LeetCode-Feedback/LeetCode-Feedback#10381]
#### Your LeetCode username

rdkl

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

There are not enough test cases to cover the case of two vertices with odd degrees (Q3 of [Weekly Contest 324](https://leetcode.com/contest/weekly-contest-324) and [Problem 2508](https://leetcode.com/problems/add-edges-to-make-degrees-of-all-nodes-even/)). 

Consider the following test case: `n = 5`, `edges = [[1,2],[1,3],[1,4],[2,4],[2,5],[3,5]]`. Vertices 1 and 2 have odd degree (3). LC problem checker returns `False` (correct answer). Code provided below returns `True` (incorrect answer) and gets accepted ([submission](https://leetcode.com/problems/add-edges-to-make-degrees-of-all-nodes-even/submissions/861478585/)).

#### Code you used for Submit/Run operation

```python3
class Solution:
    def isPossible(self, n: int, edges: List[List[int]]) -> bool:
        graph = defaultdict(set)       
        for a, b in edges:
            graph[a - 1].add(b - 1)
            graph[b - 1].add(a - 1)
        
        odd_vertices = [i for i in range(n) if len(graph[i]) % 2 == 1]
        
        if len(odd_vertices) == 0:
            return True
              
        if len(odd_vertices) == 2:
            first = odd_vertices[0]
            second = odd_vertices[1]

            # Incorrect code (gets `Accepted`).
            return len(graph[first]) != n - 1 and len(graph[second]) != n - 1
            
            # Correct code (also gets `Accepted`).
            # if first not in graph[second]:
            #     return True
            #
            # for i in range(n):
            #     if i == first or i == second:
            #         continue
            #    
            #     if first not in graph[i] and second not in graph[i]:
            #         return True
            #    
            # return False
        
        if len(odd_vertices) == 4:
            orders = [(0, 1, 2, 3), (0, 2, 1, 3), (0, 3, 1, 2)]         
            for order in orders:
                [first, second, third, fourth] = [odd_vertices[i] for i in order]
                if first not in graph[second] and third not in graph[fourth]:
                    return True

            return False

        if len(odd_vertices) > 4:
            return False
```

#### Language used for code

Python3

#### Expected behavior

The proposed test case should be added to the problem / Weekly Contest 324 test sets.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
