### ISSUE TITLE
Missing Test Case - 2508. Add Edges to Make Degrees of All Nodes Even

### ISSUE THREAD

**Issue by rupak5** [LeetCode-Feedback/LeetCode-Feedback#10384]
#### Your LeetCode username
rupakk

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A test case is missing in the question 2508 which appeared in today's leetcode weekly contest.
I submitted the code which directly return true for every test case where the count of nodes with odd degree is 2.
(You can refer the code for the implementation)
The code got accepted but it shouldn't be accepted because I have a counter test case which proves my code wrong.

Test Case:
n = 6
edges =
[[1,2],[1,5],[1,6],[2,3],[2,4],[3,4],[5,6]]
Submission - https://leetcode.com/problems/add-edges-to-make-degrees-of-all-nodes-even/submissions/861482509/

#### Code you used for Submit/Run operation

```
class Solution {
public:
	bool check(int u, int v, vector<unordered_set<int>> adj)
	{
		if (adj[u].find(v) != end(adj[u]))
			return false;
		return true;
	}
	bool isPossible(int n, vector<vector<int>>& edges) {
		vector<unordered_set<int>> adj(n + 1);
		for (vector<int> v : edges)
		{
			adj[v[0]].insert(v[1]);
			adj[v[1]].insert(v[0]);
		}
		vector<int> badNodes;
		for (int i = 1; i <= n; ++i)
		{
			if (adj[i].size() % 2 != 0)
				badNodes.push_back(i);

			if (adj[i].size() % 2 != 0 && adj[i].size() == n - 1)
				return false;
		}
		if (badNodes.size() > 4 || badNodes.size() % 2 != 0)
			return false;
		if (badNodes.size() == 0)
			return true;
		if (badNodes.size() == 2)//The wrong case
			return true;
		if (check(badNodes[0], badNodes[1], adj) && check(badNodes[2], badNodes[3], adj))
			return true;
		if (check(badNodes[0], badNodes[2], adj) && check(badNodes[1], badNodes[3], adj))
			return true;
		if (check(badNodes[0], badNodes[3], adj) && check(badNodes[2], badNodes[1], adj))
			return true;
		return false;
	}
};
```

#### Language used for code

C++

#### Expected behavior

The code submitted should return wrong answer instead of getting accepted.

#### Screenshots

Wrong answer on accepted code:
<img width="1280" alt="Screenshot 2022-12-18 at 11 21 26" src="https://user-images.githubusercontent.com/65965671/208283869-72f01262-c3f8-49d5-9987-fe04685c960c.png">

Accepted screenshot:
<img width="1280" alt="Screenshot 2022-12-18 at 11 22 01" src="https://user-images.githubusercontent.com/65965671/208283881-44f25fad-bed6-4a7f-b12a-eea04626b76e.png">

<br><br>
#### About opening at Leetcode

If there are any openings at Leetcode contest team or problem solution team, I would be more than happy to interview for a role.
I am a finally year college student pursuing computer science, currently rated 2215(Guardian).
I have written solution for various problems on Leetcode, you can check them at my profile:
https://leetcode.com/rupakk/
Also I make YouTube videos about leetcode problems:
https://www.youtube.com/@thinkthencode/videos
If you found a role matching with my skills then I would love to interview for it.
Thanks

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time.
Rejected the test case. 
The solution mentioned are failing.
We appreciate your support!
