### ISSUE TITLE
Compile Error - 2502. Design Memory Allocator

### ISSUE THREAD

**Issue by raflyirham** [LeetCode-Feedback/LeetCode-Feedback#10388]
#### Your LeetCode username

raflyirham

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Two functions have the same name, and C does not support function overloading.

#### Code you used for Submit/Run operation

```
typedef struct {
    int *arr;
    int size;
} Allocator;


Allocator* allocatorCreate(int n) {
    Allocator *obj = malloc(sizeof(Allocator));
    obj->size = n;
    obj->arr = malloc(sizeof(int) * obj->size);
    memset(obj->arr, -1, sizeof(int) * obj->size);
    return obj;
}

int allocatorAllocate(Allocator* obj, int size, int mID) {
    int total = 0;
    int i;
    for(i = 0; i < obj->size; i++) {
        if(obj->arr[i] == -1) ++total;
        else {
            total = 0;
        }
        if(total == size) break;
    }
    if(total != size) return -1;
    
    for(int j = i - (size - 1); j < (i - (size - 1) + (size)); j++) {
        obj->arr[j] = mID;
    }
    
    return i - (size - 1);
}

int allocatorFree(Allocator* obj, int mID) {
    int total = 0;
    for(int i = 0; i < obj->size; i++) {
        if(obj->arr[i] == mID) {
            ++total;
            obj->arr[i] = -1;
        }
    }
    return total;
}

void allocatorFree(Allocator* obj) {
    free(obj);
    return;
}
```

#### Language used for code

C

#### Expected behavior

The solution should be working if there was no two or more functions have the same name.

#### Screenshots

![Screenshot_222](https://user-images.githubusercontent.com/88644864/208284826-49a3911c-2082-4be2-9f8d-238f8d8c226d.png)

#### Additional context

I wrote similar solution in Java and it is considered as correct answer and Accepted. Here is the submission link: https://leetcode.com/submissions/detail/861506850/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

Please ask your question in the discussion forum.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
