### ISSUE TITLE
Issue in addTwoNumbers involving malloc

### ISSUE THREAD

**Issue by Sp4rt4h** [LeetCode-Feedback/LeetCode-Feedback#1039]
I have this code right here in addTwoNumbers. It is literally just a malloc, and an assignment of that pointer to a new pointer, and it gives me misaligned address. Am I doing something wrong here?

`
    struct ListNode *temp = (struct ListNode *)malloc(sizeof(struct ListNode));
    
    struct ListNode *start = temp;
    
    //ret_all_node = temp;

    //temp->val = 9;
    
    /*int num = 0;

    for(struct ListNode *next = (struct ListNode *)malloc(sizeof(struct ListNode)); 
        l1->next != NULL || l2->next != NULL; 
        next = (struct ListNode *)malloc(sizeof(struct ListNode)))
    {
        if(l1 != NULL) {
            num += l1->val;
            l1 = l1->next;
        }
        
        if(l2 != NULL) {
            num += l2->val;
            l2 = l2->next;
        }        

        if(num > 9) {
            num -= 10;
            next->val += 1;
        }
        
       temp->val = num;
        
        temp->next = next;
        temp = next;
    }
    */
    return start;`

**Comment by lc-kay** [comment]
Hi @Sp4rt4h, 

Please raise your problem to https://leetcode.com/problems/add-two-numbers/discuss/?currentPage=1&orderBy=most_votes&query= for help from the LeetCode community!

In addition, please make sure you use the driver code. If you want to report any content related issue like missing test cases or inaccurate description, please leave a comment in the GitHub ticket.
