### ISSUE TITLE
Missing Test Case - 2508. Add Edges to Make Degrees of All Nodes Even

### ISSUE THREAD

**Issue by Mukit09** [LeetCode-Feedback/LeetCode-Feedback#10398]
#### Your LeetCode username
Mukit09 

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x]  Missing Test Cases 

#### Description of the bug
An accepted solution gets failed for the test case given below:

n = `8`
edges = `[[1,2],[1,3],[1,4],[5,6],[5,7],[8,6],[7,8]]`

_for the count of odd-degree nodes = 4_, the boolean value is returned after checking the nodes with odd-degree only. But even-degree nodes can make odd-degree nodes even too. It is just like the case of the odd-degree count = 2.

#### Code you used for Submit/Run operation

```
class Solution {
    private boolean[] taken;
    private boolean found;
    private Map<Integer, Integer>[] mapAr;
    public boolean isPossible(int n, List<List<Integer>> edges) {

        mapAr = new HashMap[n];
        for (int i = 0; i < n; i++)
            mapAr[i] = new HashMap<>();

        for (List<Integer> edge : edges) {
            int u = edge.get(0) - 1;
            int v = edge.get(1) - 1;

            mapAr[u].put(v, 1);
            mapAr[v].put(u, 1);
        }

        List<Integer> list = new ArrayList<>();
        for (int i = 0; i < n; i++) {
            if ((mapAr[i].size() & 1) == 1)
                list.add(i);
        }

        if (list.size() == 0)
            return true;
        if (list.size() > 4 || (list.size() & 1) == 1)
            return false;

        if (list.size() == 2) {
            int u = list.get(0);
            int v = list.get(1);

            if (mapAr[u].containsKey(v)) {
                boolean ok = false;
                for (int i = 0; i < n; i++) {
                    if (i == u || i == v)
                        continue;
                    if (!mapAr[i].containsKey(u) && !mapAr[i].containsKey(v)) {
                        ok = true;
                        break;
                    }
                }
                return ok;
            }
            return true;
        }

        // only 4 node case
        taken = new boolean[4];
        go(0, list);
        return found;
    }

    private void go(int i, List<Integer> list) {
        if (i == 2) {
            found = true;
            return;
        }
        for (int j = 0; j < list.size(); j++) {
            if (!taken[j]) {
                taken[j] = true;
                int u = list.get(j);
                for (int k = 0; k < list.size(); k++) {
                    if (!taken[k] && !mapAr[u].containsKey(list.get(k))) {
                        taken[k] = true;
                        go(i+1, list);
                        taken[k] = false;
                    }
                }
                taken[j] = false;
            }
        }
    }
}
```

#### Language used for code
Java

#### Expected behavior

We can make the odd-degree nodes into even-degree nodes with the help of even-degree nodes, so it should return true. But this code is giving me false, thus we should get the **Wrong Answer** here. But it is giving me **Accepted**. So, 

Output: false
Expected: true

#### Screenshots

![Screenshot from 2022-12-18 17-56-57](https://user-images.githubusercontent.com/9996715/208297069-30798297-9a0d-483d-aadd-5b876cbc01b5.png)

**Comment by Paren7** [comment]
![graph](https://user-images.githubusercontent.com/117136077/208300249-dfb4a4da-b713-4e5f-818c-7cb5fb828b07.png)
you can find that there are two connected component in this testcase, you said that you can with the help of even-degree nodes to make the odd-degree nodes into even-degree nodes. I guess you missed a sentence from question **You can add at _most two additional edges_ (possibly none) to this graph so that there are no repeated edges and no self-loops.**
so if you with the help of even-degree nodes to make the odd-degree nodes into even-degree nodes, for example you add two additional {2,7},{1,7}, you make node 1,2 into even-degree nodes.  but node 3,4 still odd-degree. so the answer should be false.
Thank you.

**Comment by Mukit09** [comment]
yes, you are right. I am closing this
