### ISSUE TITLE
Missing Test Case - 198. House Robber

### ISSUE THREAD

**Issue by Simranbalani** [LeetCode-Feedback/LeetCode-Feedback#10396]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by Simranbalani** [comment]
{1,2}

// this testcase gives the output 2 but it should give 1

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
