### ISSUE TITLE
有效的数独测试用例给的有问题

### ISSUE THREAD

**Issue by never-fade-away** [LeetCode-Feedback/LeetCode-Feedback#104]
** Bug 类型**
- [ ] 题目
#36 有效的数独
- [ ] 题解
- [ ] 编程语言

**描述**
描述你遇到的 bug
大概#470个用例
[[".",".",".",  ".","5",".", ".","1","."],
[".","4",".",  "3",".",".",  ".",".","."],《====
[".",".",".",  ".",".","3",    ".",".","1"],《====
["8",".",".",".",".",".",".","2","."],
[".",".","2",".","7",".",".",".","."],
[".","1","5",".",".",".",".",".","."],
[".",".",".",".",".","2",".",".","."],
[".","2",".","9",".",".",".",".","."],
[".",".","4",".",".",".",".",".","."]]

**期望行为**
剔除这个解答

**Comment by feiceh** [comment]
能否提供一下代码和「执行代码」的输出或「提交代码」的结果截图，把信息提供完整才能有助于快速验证和精准的定位哟～

**Comment by 201722111112029** [comment]
我的问题，不好意思，测试用例没错，这个题目我copy题目上输入的测试用例，结果编译一直报错，这就很扎心呢，去掉空格写成3行就行了，这可太难呢。
bool isValidgroup(int *arr, int* arrSize) {
    int i,j;
    bool flag = true;
    for (i=0; i<*arrSize; i++) {
        for (j=i+1; j<*arrSize; j++) {
            if (arr[i]==arr[j]) {
                flag=false;
                break;   
            }
        }
        if (!flag) break;
        arr[i] = 0;
    }
    *arrSize = 0;
    return flag;
}

bool isValidSudoku(char** board, int boardSize, int* boardColSize){
    int i, j, k, m=0;
    int cnt1=0;
    int cnt2=0;
    *boardColSize = 9;
    //判断行、列是否有相等的数字
    for (i=0; i<boardSize; i++) {
        for (j=0; j<boardSize; j++) {
            for (k=j+1; k<boardSize; k++) {
                if ((board[i][j]==board[i][k]&&board[i][j]!='.')
                    ||(board[j][i]==board[k][i]&&board[k][i]!='.')) {
                    goto out;
                }
            }
        }
    }

    int b[18] = {0};
    //判断九宫格内是否有重复的数字
    // [0,0]->[2,2]、[3,3]->[5,5]、[6,6]->[8,8]
    while (m!=9) {
        for (i=m; i<m+3; i++) {
            for (j=m; j<m+3; j++) {
                if (board[i][j]!='.')
                b[cnt1++]=board[i][j];
            }
        }
        if(!isValidgroup(b, &cnt1)) goto out;
        m +=3;
    }
    int a[] = {0,3,0,6,3,6};
    m=0;
    while (m!=6) {
        for (i=a[m]; i<a[m]+3; i++) {
            for (j=a[m+1]; j<a[m+1]+3; j++) {
                if (board[i][j]!='.')
                b[cnt1++]=board[i][j];
                if (board[j][i]!='.')
                b[9+cnt2++]=board[j][i];
            }
        }
        if(!isValidgroup(b, &cnt1)) goto out;
        if(!isValidgroup(&b[9], &cnt2)) goto out;
        m+=2;
    }
    return 1;
    out: 
    return 0;
}
