### ISSUE TITLE
缺少测试用例

### ISSUE THREAD

**Issue by zouhao123** [LeetCode-Feedback/LeetCode-Feedback#10400]
[6267. 添加边使所有节点度数都为偶数](https://leetcode.cn/problems/add-edges-to-make-degrees-of-all-nodes-even/)
缺少测试用例：
5
[[1,2],[2,3],[3,4],[4,2]]
如下代码返回错误结果，但提交能通过：
https://leetcode.cn/submissions/detail/389778014/

**Comment by feiceh** [comment]
您好，在与相关团队核实后：暂不处理，已有相似用例。以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
