### ISSUE TITLE
Missing Test Case - 1222. Queens That Can Attack the King

### ISSUE THREAD

**Issue by PSwicarz** [LeetCode-Feedback/LeetCode-Feedback#10404]
#### Your LeetCode username

piotr_swicarz

#### Category of the bug
- [ ] Missing Test Cases 
```
queens =
[[0,7]]
king =
[7,0]
```
```
[[7,0]]
king =
[0,7]
```
```
queens =
[[0,0]]
king =
[7,7]
```
#### Description of the bug

Just added one test case but 3 more are missing in all directions - my code got AC while submit, meanwhile while i tested manually with this test case it wasnt AC

#### Code you used for Submit/Run operation

```
class Solution:
    def queensAttacktheKing(self, queens: List[List[int]], king: List[int]) -> List[List[int]]:
        output = []
        queens = {(i,j) for i,j in queens}
        for i in (-1,0,1):
            for j in (-1,0,1):
                for k in range(1,7):
                    y,x =  king[0] + i*k, king[1] + j*k
                    if (y,x) in queens:
                        output.append((y,x))
                        break
        return output
```

#### Language used for code

Python 3

#### Expected behavior

Missing testcases in all directions, there is lack of situation with +-7 difference in all diagonal directions

#### Screenshots

My code got AC, meanwhile it shoudnt - 3 more tescases:
![image](https://user-images.githubusercontent.com/99476222/208306004-9da18d15-74f1-41e4-9a04-6669cc991850.png)
meanwhile with all the tescases:
![image](https://user-images.githubusercontent.com/99476222/208306029-b1e765dc-b3fe-4b44-9c11-dfc598894b25.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
