### ISSUE TITLE
Missing Test Case - 215. Kth Largest Element in an Array

### ISSUE THREAD

**Issue by AbhishekGargcoder** [LeetCode-Feedback/LeetCode-Feedback#10402]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by AbhishekGargcoder** [comment]
Q. 215 of Leetcode to find K-th largest element more efficient solution... I think it's help u ..

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback.  We appreciate your support!
