### ISSUE TITLE
Missing Edge Test Case, 1207. Unique Number of Occurrences

### ISSUE THREAD

**Issue by johnny-le** [LeetCode-Feedback/LeetCode-Feedback#10409]
#### Your LeetCode username
JustTesting

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x ] Missing Test Cases 

#### Description of the bug

The submission was successful despite not covering when arr[i] contains an element with 1000.

#### Code you used for Submit/Run operation

int count[2000] = {0};
for(int i = 0; i < arrSize; i++){ // get the count of all the unique numbers
    count[arr[i]+1000] = count[arr[i]+1000] + 1;
    freq[i] = 0; // set a separate array for count
}

```

#### Language used for code
<!-- C -->


#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->
There is a missing edge test case if arr[i] = 1000... which would make count[2000] out of bounds since the original array count only goes from 0 to 1999.

The count should be initialized int count[2001] to cover the arr[i] = 1000 test case. 

#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by johnny-le** [comment]
https://leetcode.com/problems/unique-number-of-occurrences/submissions/862345854/

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team.  We appreciate your support!
