### ISSUE TITLE
Missing Test Case - 1222. Queens That Can Attack the King

### ISSUE THREAD

**Issue by PSwicarz** [LeetCode-Feedback/LeetCode-Feedback#10403]
#### Your LeetCode username

piotr_swicarz

#### Category of the bug
- [ ] Missing Test Cases 
```
queens =
[[7,7]]
king =
[0,0]
```

#### Description of the bug

my code got AC while submit, meanwhile while i tested manually with this test case it  was Wrong Answer as expected.

#### Code you used for Submit/Run operation

```
output = []
queens = {(i,j) for i,j in queens}
for i in (-1,0,1):
    for j in (-1,0,1):
        for k in range(1,7):
            y,x =  king[0] + i*k, king[1] + j*k
            if (y,x) in queens:
                output.append((y,x))
                break
return output
```

#### Language used for code

Python 3

#### Expected behavior

Missing testcase, while runing manually it was Wrong Anwser as expected

#### Screenshots

![image](https://user-images.githubusercontent.com/99476222/208305177-e2f0bc15-71d3-4047-87b8-77b37e49732c.png)
Meanwhile the same code running manually with test case 
```
queens =
[[7,7]]
king =
[0,0]
```
![image](https://user-images.githubusercontent.com/99476222/208305464-f0c87892-cfc6-424a-8651-8261845d78df.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code AC link

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by PSwicarz** [comment]
https://leetcode.com/problems/queens-that-can-attack-the-king/submissions/861682430/

**Comment by LC-Pam** [comment]
Code fails after submit: https://leetcode.com/submissions/detail/863916043/
