### ISSUE TITLE
1971 should be a Medium question instead of Easy

### ISSUE THREAD

**Issue by idontknoooo** [LeetCode-Feedback/LeetCode-Feedback#10411]
#### Your LeetCode username
idontknoooo

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

[1971. Find if Path Exists in Graph](https://leetcode.com/problems/find-if-path-exists-in-graph/description/) should have a **Medium** tag instead of **Easy**.

1. This question is the only **Union Find** question with an **Easy**  tag. **Union find** is not something a beginner would have learned.
2. It can also be solved using BFS/DFS. BFS & DFS are considered relatively advanced techniques, compared to hash-table, linear search, or even binary search. However, the scale of the question is around `2 * 10^5`. That means if a user tries to solve it using BFS/DFS, they will have to make sure their solution visits each node only constant times. 

If this question shows up in the weekly contest, it should be a 4-point question, which corresponds to a **Medium** tag.

Generally, **Easy** questions should be focusing on basic data structure without specialized techniques applied (in this case `pruning`). The data scale should be at a level such that, applying an advanced technique is optional but solvable via brute force. If LeetCode insists to identify this question as an **Easy** question, then the scale (`edges.length`) should be around 100 to make sure it's less intimidating to beginners. 

#### Code you used for Submit/Run operation

Not Applicable

#### Language used for code

Not Applicable

#### Expected behavior

Not Applicable

#### Screenshots

Not Applicable

#### Additional context

Not Applicable

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've decided not to change problem difficulty.

We set the level is level 3, is the category of simple questions, not because of the requirements of knowledge points set above medium, this topic is the most basic BFS/DFS, other BFS/DFS topics may be set medium, but this question should still be used as a simple question. 

 We appreciate your support!
