### ISSUE TITLE
The judge output is wrong with "73. Set Matrix Zeroes".

### ISSUE THREAD

**Issue by hacker-taso** [LeetCode-Feedback/LeetCode-Feedback#1041]
#### Your LeetCode username

LeetCode ID: tasotaso

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Problem Link: https://leetcode.com/problems/set-matrix-zeroes/solution/

I think the solution 2 of the problem is wrong and so the judge program is also wrong.
With input "[[1,1,1,1],[1,0,1,1],[1,1,0,1],[0,0,0,1]]", the expected output should be "[[0,0,0,1], [0,0,0,1], [0,0,0,1], [0,0,0,1]]". But the expected output the judge shows is "[[0,0,0,1],[0,0,0,0],[0,0,0,0],[0,0,0,0]]".

#### Code you used for Submit/Run operation

We can check it without any code.

#### Language used for code

C++

#### Expected behavior

input ([[1,1,1,1],[1,0,1,1],[1,1,0,1],[0,0,0,1]]):
[1,1,1,1]
[1,0,1,1]
[1,1,0,1]
[0,0,0,1]

my expected output([[0,0,0,1], [0,0,0,1], [0,0,0,1], [0,0,0,1]]):
[0,0,0,1]
[0,0,0,1]
[0,0,0,1]
[0,0,0,1]

judge's output([[0,0,0,1],[0,0,0,0],[0,0,0,0],[0,0,0,0]]):
[0,0,0,1]
[0,0,0,0]
[0,0,0,0]
[0,0,0,0]

#### Screenshots

![image](https://user-images.githubusercontent.com/8960692/93723634-2b3c4080-fbdb-11ea-8746-bb545a860b9b.png)
(Please ignore the output part.)

**Comment by lc-kay** [comment]
Hi @hacker-taso 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by hacker-taso** [comment]
I've made a mistake and my expected output was wrong. I'm sorry to bother you guys :(
I close the issue.
