### ISSUE TITLE
1971. Ranks array stays zero. Initialization to 1 required.

### ISSUE THREAD

**Issue by Rafiki007** [LeetCode-Feedback/LeetCode-Feedback#10414]
#### Your LeetCode username

_Rafiki_

#### Category of the bug
- [ ] Solution

#### Description of the bug

In official solution, Approach 4 - Disjoint Set Union (DSU), value in rank array will not change. Should be initialized to 1 in constructor function.

#### Code you used for Submit/Run operation

```
// 1971. Find if Path Exists in Graph
class Solution {
    public boolean validPath(int n, int[][] edges, int source, int destination) {
        int[] par = new int[n];
        int[] rank = new int[n];
        Arrays.fill(rank, 1);
        for(int x=0; x<n; x++)
            par[x] = x;
        for(int[] edge: edges)
            union(par, rank, edge[0], edge[1]);
        return find(par, source) == find(par, destination);
    }
    public void union(int[] par, int[] rank, int x, int y) {
        int parX = find(par, x);
        int parY = find(par, y);
        if(parX!=parY) {
            if(rank[parX]>rank[parY]) {
                par[parY] = parX;
                rank[parX] += rank[parY];
            }
            else {
                par[parX] = parY;
                rank[parY] += rank[parX];
            }
        }
    }
    public int find(int[] par, int x) {
        if(par[x]==x)
            return x;
        return par[x] = find(par, par[x]);
    }
}
```

#### Language used for code

Java

#### Expected behavior

Rank array is initialized with Arrys.fill() function. Hence ranks get added up after every union operation.
If not initialized, ranks addition result in adding zeros and stays zero.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
