### ISSUE TITLE
Array Deletions page in Explore Typo

### ISSUE THREAD

**Issue by nathansit** [LeetCode-Feedback/LeetCode-Feedback#10413]
#### Your LeetCode username

nathansit

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

* Quick fix typo number 1 -
> Remember how insertion we were using this printArray function?

Add in the missing word

> Remember how **for** insertion we were using this printArray function?

* quick fix typo number 2
> Yup, that's it! Even though we call it a deletion, its not like we actually freed up the space for a new element, right? This is because we don't actually need to free up any space.

Its is possessive so should be it's (it is) instead:
> Yup, that's it! Even though we call it a deletion, **it's** not like we actually freed up the space for a new element, right? This is because we don't actually need to free up any space.
#### Language used for code

English

#### Expected behavior

Just minor grammatical issues

#### Screenshots

![Screenshot 2022-12-19 at 1 28 34 AM](https://user-images.githubusercontent.com/25888434/208393003-fa6ce31d-c58d-419d-b387-b6b4461dfc14.png)

![Screenshot 2022-12-19 at 1 45 18 AM](https://user-images.githubusercontent.com/25888434/208396322-e9cd8ad8-e8ed-4483-8d1d-86d4de7e7f3f.png)

(See the bottom paragraphs in these screenshots)

#### Link to the page
https://leetcode.com/explore/learn/card/fun-with-arrays/526/deleting-items-from-an-array/3246/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
