### ISSUE TITLE
Missing Test Case - 198. House Robber

### ISSUE THREAD

**Issue by wagnerjfr** [LeetCode-Feedback/LeetCode-Feedback#10419]
#### Your LeetCode username

user8082rW

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

Possibly it's missing test cases like:
[0,0,0,1]
[0,0,1]

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by wagnerjfr** [comment]
I coded using Java, but I guess that the problem `"198. House Robber"` is missing tests like:
```
[0,0,0,1]
[0,0,1]
```
When the 1st and the 2nd are '0'.

Just saying this because I was able to solve and pass all the tests with my code, but I spotted this 2 cases which could possibly fail my submission if they exist.

So, just confirming whether they are present there or not.
Thanks.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code you submitted to reach this result, then we will consider to add this or not after the testing. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by wagnerjfr** [comment]
This is the code that I submitted. It's not 100% correct and will fail with the above test cases.

But it passed when I submitted the problem of the day.

Submission link:
https://leetcode.com/submissions/detail/859623700/

Code:
```java
class Solution {
    private int[] dp;
    
    public int rob(int[] nums) {
        if (nums.length == 1) {
            return nums[0];
        }
        dp = new int[nums.length];
        return Math.max(visit(0, nums), visit(1, nums));
    }
    
    private int visit(int i, int[] nums) {
        if (nums[i] == 0) return 0;
        
        int[] arr = new int[2];
        int count = 0;

        for (int idx = i+2; idx <= i+3; idx++) {
            if (idx < nums.length) {
                arr[count] = (dp[idx] != 0) ? dp[idx] : visit(idx, nums);
            }
            count++;
        }
        
        dp[i] = nums[i] + Math.max(arr[0], arr[1]);
        //System.out.println(nums[i] + " " + dp[i]);
        return dp[i];
    }
}
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
