### ISSUE TITLE
Missing Test Case - 29. Divide Two Integers

### ISSUE THREAD

**Issue by Sumit068** [LeetCode-Feedback/LeetCode-Feedback#10418]
#### Your LeetCode username
Sumit_068

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The code was successfully accepted while the code wasn't right.

#### Code you used for Submit/Run operation
```
// Divide Two Integers
public class Solution {
    public int Divide(int dividend, int divisor) {
        if(dividend==int.MaxValue ) {
            if(divisor==1) return int.MaxValue;
            if(divisor==-1) return int.MinValue;  //this line is wrong but still accepeted
        }
        if(dividend==int.MinValue){
            if(divisor==-1) return int.MaxValue;
            if(divisor==1) return int.MinValue;
        }

        int quo=0;
        bool positive=true;
        if(dividend>0){
            positive=!positive;
            dividend=-dividend;
        }

        if(divisor>0){
            positive=!positive;
            divisor=-divisor;
        }

        int half_int=int.MinValue/2;
        while(divisor>=dividend){
            int count=-1;
            int value=divisor;
            while(value>=half_int && value+value>=dividend){
                value+=value;
                count+=count;
            }
            dividend-=value;
            quo+=count;
        }

        if(positive){
            return -quo;
        }
        return quo;
    }
}
```

#### Language used for code
C#

#### Expected behavior
Missing Test Case -- 
dividend = 2147483647
divisor = -1

Expected Answer -2147483647

above code giving answer -2147483648 but still this code accepted by leetcode
So, please can you add a new test case

#### Screenshots
![image](https://user-images.githubusercontent.com/82926215/208424473-fb6f66a9-4d3c-439d-a21b-329e167a5fba.png)
above screenshots you can see. code is giving wrong output
![image](https://user-images.githubusercontent.com/82926215/208424728-2074425a-e085-4c46-bb18-80e155839da7.png)
above screenshots you can see. code accepted

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
