### ISSUE TITLE
runtime error in std::vector

### ISSUE THREAD

**Issue by wdsnyc** [LeetCode-Feedback/LeetCode-Feedback#10424]
I've submitted a solution which is producing a runtime error in std::vector:

Line 1034: Char 34: runtime error: addition of unsigned offset to 0x6030000001c0 overflowed to 0x6030000001bc (stl_vector.h)
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/stl_vector.h:1043:34

I would like to know which line in my code is producing the error. Am I able to debug this in leet? Is a stack trace available? When I run the program outside of leet it does not produce a runtime error.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by wdsnyc** [comment]
Hi.

The language is c++ however I’ve made changes to the code and don’t have the version of the that produced the runtime error.
