### ISSUE TITLE
markdown error

### ISSUE THREAD

**Issue by incubo4u** [LeetCode-Feedback/LeetCode-Feedback#10425]
#### Your LeetCode username

1ncu804u

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

the markdown appears as $$

<img width="636" alt="image" src="https://user-images.githubusercontent.com/52492193/208510199-46e4ca78-fe4e-4143-9a81-95b082256806.png">

<img width="446" alt="image" src="https://user-images.githubusercontent.com/52492193/208510229-517021a2-446d-4220-bc99-327e948df033.png">

#### Additional context

https://leetcode.com/problems/domino-and-tromino-tiling/solutions/1570448/official-solution/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
