### ISSUE TITLE
140. Word Break II | Failing testcase

### ISSUE THREAD

**Issue by anuj-io** [LeetCode-Feedback/LeetCode-Feedback#1042]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Below test case is running correctly when running it directly on leetcode, however, it only fails while submitting the code.
"catsandog"
["cats","dog","sand","and","cat"]

#### Code you used for Submit/Run operation

```
// Two Sum
/**
 * @param {string} s
 * @param {string[]} wordDict
 * @return {string[]}
 */
var wordBreak = function(s, wordDict) {
  let words = {};
  let maxLength = 0;

  wordDict.forEach(word => {
    words[word] = true;
    if(word.length > maxLength) {
      maxLength = word.length;
    }
  });
  let breaks = [[0]];
  for(let i = 1; i<=s.length; i++) {
    breaks[i] = [];
    let k = Math.max(i-maxLength, 0);
    for(let j = i-1; j>=k; j--) {
      if(breaks[j].length > 0 && words[s.substring(j,i)]) {
        breaks[i].push(j);
      }
    }
  }

  let sequences = getSequence(breaks, s.length);
  
    let result = [];
    sequences.forEach(seq => {
    let str = "";
    let j = 1;
    let i = 0;
    while(i<s.length) {
      if(i == seq[j]) {
        str += " ";
        j++;
      } else {
        str += s[i];
        i++;
      }
    }
    result.push(str);
  });
  return result;

};

let sequenceCache = {}

var getSequence = function(breaks, i) {
  if(i == 0) {
    return [[0]];
  }
  if(sequenceCache[i]) {
    return sequenceCache[i];
  }
  let result = [];
  breaks[i].forEach(idx => {
    const sub = getSequence(breaks, idx);
    sub.forEach(seq => result.push([...seq,i]));
  });
  sequenceCache[i] = result;
  return sequenceCache[i];
}
```

#### Language used for code
Javascript 

#### Expected behavior

Test case shouldn't fail on submitting the code as it is passing when running it on LC
https://leetcode.com/submissions/detail/398597972/

#### Screenshots

<img width="2463" alt="Screenshot at Sep 20 21-43-35" src="https://user-images.githubusercontent.com/13328070/93733485-5f3b4580-fb8a-11ea-9103-097e08f788ac.png">

**Comment by lc-ivan** [comment]
Hi @anuj-io ,
Thanks for reaching out to us. I have relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @anuj-io ,
Thank you for your feedback regarding this problem. Upon review, our team has noted that you have defined a global variable which needs to be cleared for each test, thus, causing the failed test case.

**Comment by anuj-io** [comment]
I appreciate the prompt response, thanks!
