### ISSUE TITLE
Missing Test Case - 240. Search a 2D Matrix II

### ISSUE THREAD

**Issue by shub6758yoy** [LeetCode-Feedback/LeetCode-Feedback#10420]
#### Your LeetCode username
https://leetcode.com/skumarsahu5545/ 

#### Category of the bug
- Missing Test Cases 

#### Description of the bug
This is not a bug, but i want to contrubute a testcase
matrix = [[-48,-17,-15,-10,-7,-3,-1],[-30,-16,-14,-9,1,4,11],[-27,-15,-12,-8,3,8,12],[-23,-13,-11,-7,4,9,15],[-17,-10,-9,-6,7,14,16],[-15,-8,-7,-6,10,23,30],[-12,-6,-5,-5,18,25,31]]
target = 0
Output : false

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean searchMatrix(int[][] matrix, int target) {
        if(matrix.length == 0 || matrix[0].length == 0)return false;
        int ad = matrix[0].length-1;
        for(int[] nums:matrix){
            while(nums[ad]>target && ad>0)ad--;
            if(nums[ad] == target)return true;
        }

        return false;
    }
}
```

#### Language used for code
Java

**Comment by LC-Pam** [comment]
Thank you for your time. Test case already exists.  We appreciate your support!
