### ISSUE TITLE
Missing Test Case - 101. Symmetric Tree

### ISSUE THREAD

**Issue by Jewel-Thomas** [LeetCode-Feedback/LeetCode-Feedback#10435]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases - Missing Test case bug 

#### Description of the bug

Bug is a missing test case bug, In this question there is another testcase where when I run the code, i get wrong answer but when 
I submit i get the code totally accepted. The testcase is well within the contraints. The missing testcase is [0,0,0,null,0,null,0] where it 
shows wrong answer.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    // Treenode* lTree = root->left;
    void HelperRight(TreeNode* root,vector<int>& r)
    {
        if(root==NULL)
        {
            r.push_back(0);
            return;
        }
        r.push_back(root->val);
        HelperRight(root->right,r);
        HelperRight(root->left,r);
    }
    void HelperLeft(TreeNode* root, vector<int>& l)
    {
        if(root==NULL)
        {
            l.push_back(0);
            return;
        }
        l.push_back(root->val);
        HelperLeft(root->left, l);
        HelperLeft(root->right,l);
    } 

    bool isSymmetric(TreeNode* root) {
        vector<int> l,r;
        if(root->left == NULL && root->right==NULL)
        {
            return true;
        }
        if(root->left != NULL && root->right!=NULL)
        {
            if(root->left->val != root->right->val)
            {
                return false;
            }
        }
        HelperLeft(root->left,l);
        HelperRight(root->right,r);
        return l==r;
    }
};
```

#### Language used for code
C++ is the language used.

#### Expected behavior

The correct answer for this testcase should be false but for [0,0,0,null,0,null,0] we get true which is wrong answer

#### Screenshots

![image](https://user-images.githubusercontent.com/80634999/208593191-7b58dfec-552a-4bfe-b197-876f0c43c5d5.png)
![image](https://user-images.githubusercontent.com/80634999/208593241-fb05be32-1312-45bf-a5d9-42419df84614.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
