### ISSUE TITLE
Missing Test Case - 1971. Find if Path Exists in Graph

### ISSUE THREAD

**Issue by rifatr** [LeetCode-Feedback/LeetCode-Feedback#10430]
#### Your LeetCode username
rifatrraazz

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
A solution got accepted but it should get TLE. So, I've created a counter case for the solution to give TLE verdict. The test case is couldn't attached here directly as it is big. I have to attach it with third party sharing. 

[Link of testcase](https://pastebin.com/7PiK3Hgy)

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool validPath(int n, vector<vector<int>>& edges, int source, int destination) {
        
        map<int,vector<int>> grafo;
        set<int> visited;
        
        for(auto e: edges){
            
            grafo[e[0]].push_back(e[1]);
            grafo[e[1]].push_back(e[0]);
        }
        
        queue<int> fila;
        
        fila.push(source);
        
        while(fila.size()!=0){
            
            if(source==destination){
                return true;
            }
            
            visited.insert(source);
            
            for(int i = 0; i<grafo[source].size(); i++){
                
                if(visited.find(grafo[source][i])==visited.end()){
                    fila.push(grafo[source][i]);
                }
    
            }
            
            source = fila.front();
            fila.pop();
            
        }
        
        return false;   
    }    
};
```

#### Language used for code
C++

#### Expected behavior
Solution should got TLE because it's complexity is $O(n^2)$.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
