### ISSUE TITLE
1279. Traffic Light Controlled Intersection - need more test cases

### ISSUE THREAD

**Issue by idontknoooo** [LeetCode-Feedback/LeetCode-Feedback#10434]
#### Your LeetCode username
idontknoooo

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

[1279. Traffic Light Controlled Intersection](https://leetcode.com/problems/traffic-light-controlled-intersection/description/) needs more test cases. The below solution doesn't have any locking mechanism, yet it still passes all test cases. In a real high-volume multi-threading environment, this solution could fail due to a lack of atomicity for each operation.

#### Code you used for Submit/Run operation

```python
class TrafficLight:
    def __init__(self):
        self.a = True

    def carArrived(
        self,
        carId: int,                      # ID of the car
        roadId: int,                     # ID of the road the car travels on. Can be 1 (road A) or 2 (road B)
        direction: int,                  # Direction of the car
        turnGreen: 'Callable[[], None]', # Use turnGreen() to turn light to green on current road
        crossCar: 'Callable[[], None]'   # Use crossCar() to make car cross the intersection
    ) -> None:
        if roadId == 1:
            if not self.a:
                self.a = not self.a
                turnGreen()
            crossCar()
        else:    
            if self.a:
                self.a = not self.a
                turnGreen()
            crossCar()
```

#### Language used for code
Python

#### Expected behavior

The above solution would've failed if test cases were sufficient.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

suggest test case(s) where your solution would fail

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by idontknoooo** [comment]
I can't provide a test case that fails this solution without knowing how this question is set up. Also, the `cars` length is limited to 20, which makes it impossible to fail. It's almost too obvious that this solution is not correct as it's not thread-safe. The LC judge shouldn't be all test-driven (i.e. if there is no test case that fails a solution then a solution is correct in all scenarios. This is not correct).

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

We judge solutions in a single thread so thread-safety is not a problem here.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
