### ISSUE TITLE
620. Not Boring Movies - error in new UI design

### ISSUE THREAD

**Issue by bannovdaniil** [LeetCode-Feedback/LeetCode-Feedback#10439]
#### Your LeetCode username
bannovdaniil

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Code don't work in new UI design.

#### Code you used for Submit/Run operation
```
SELECT id, movie, description , rating FROM Cinema
WHERE (id % 2) <> 0 AND description != "boring"
ORDER BY rating DESC;
```

#### Language used for code
MySQL

#### Screenshots
in new UI

![image](https://user-images.githubusercontent.com/96119195/208597873-402e5848-14c5-4088-a9fa-9549714dae32.png)

in old UI
![image](https://user-images.githubusercontent.com/96119195/208597656-81b27bc8-c4e0-4489-aea9-6b312977b58e.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
https://project.feishu.cn/leetcode/us_tickets/create?parentUrl=%2Fleetcode%2FworkObjectView%2Fus_tickets%2FvHtNOOSVR

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to check the problem. The issue should be fixed, we appreciate your report! Please let us know if you have any questions. 

![Screen Shot 2023-01-13 at 5 38 01 PM](https://user-images.githubusercontent.com/103138242/212432018-f1c6d7b2-d4dd-4fea-9174-c82785310ae3.png)
![Screen Shot 2023-01-13 at 5 38 59 PM](https://user-images.githubusercontent.com/103138242/212432022-e16991ae-7724-457b-aca4-e7428325ed34.png)
