### ISSUE TITLE
Missing Test Case - 162. Find Peak Element

### ISSUE THREAD

**Issue by LordNewton10** [LeetCode-Feedback/LeetCode-Feedback#10433]
#### Your LeetCode username
Test0123

#### Category of the bug
Missing Test Cases 

#### Description of the bug

Wrong peak element
[1, 5, 2, 3, 10, 8, 9]
Should return 1 or 4 but returns 6

#### Code you used for Submit/Run operation

```
     class Solution {
    public int findPeakElement(int[] nums) {
        int left = 0;
        int right = nums.length - 1;
        while (left < right) {
            int mid = left + (right - left) / 2;
            if (nums[mid] > nums[mid + 1]) {
                right = mid;
            } else {
                left = mid + 1;
            }
        }
        return left;
    }
}
```

#### Language used for code
Java

**Comment by stormsunshine** [comment]
How can index 5 be the index of a peak element? The element at index 5 is 8, which is smaller than both adjacent elements.

**Comment by LordNewton10** [comment]
Oh sorry, I meant index 4
