### ISSUE TITLE
Missing Test Case - 1764. Form Array by Concatenating Subarrays of Another Array

### ISSUE THREAD

**Issue by Night221018** [LeetCode-Feedback/LeetCode-Feedback#10443]
The template is too cumbersome, so I will simply say.

my home page ： https://leetcode.cn/u/luzelin/

This question lacks samples with inconsistent internal order. 
for example：groups =[[1,2,3]] ,  nums = [3,1,2]
normally this is wrong, but I can pass this question with the sliding window method.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
