### ISSUE TITLE
 Maximum XOR of Two Numbers in an Array

### ISSUE THREAD

**Issue by silvexgit** [LeetCode-Feedback/LeetCode-Feedback#1044]
silvex

#### Category of the bug
- [x ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

My code runs, but it says it takes too long to run (timeout). I ran the test case (a list with about 6,63 elements) where it fails in 
my computer and it takes about 18 seconds to run. Please pass this submission.

time ./max-xor-two-number.py
6663 (number of elements in list)
16777214 (answer to that test case)

real    0m18.375s
user    0m18.364s
sys     0m0.010s

#### Code you used for Submit/Run operation

```
class Solution:
    def findMaximumXOR(self, nums: List[int]) -> int:
        z = len(nums)
        if (z >= 320000):
            return(0)
        if (z == 0 or z == 1):
            return (0)
        if (z == 2):
            return (nums[0]^nums[1])
        r = 0
        l = (2147483647)
        for x in (range(0,z-1,1)): 
            for y in (range(x+1,z,1)):
                t = nums[x] ^ nums[y]
                if ( t > r):
                    r = t
        for x in (range(z-1,0,-1)):
            for y in (range(x-1,-1,-1)):              
                t = nums[y] ^ nums[y]
                if ( t > r):
                    r = t                                  
        return (r)

```

python3

#### Expected behavior

I expect the code to complete without errors (besides the timeout limit your computer has)

![image](https://user-images.githubusercontent.com/31254668/93736165-50f22700-fb94-11ea-8a8c-d3813b546a60.png)

**Comment by lc-kay** [comment]
Hello @silvexgit, 

There are several reasons why you encountered TLE: 
Your code has an underlying infinite loop.
Your algorithm is too slow and has high time complexity.
The data structure you returned is in an invalid state. For example, a linked list that contains a cycle.

You can also seek help in https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/discuss/?currentPage=1&orderBy=most_votes&query= from our LeetCode community!

Please leave a comment in the GitHub ticket if you want to report any content related issue like a missing test case or inaccurate description.
