### ISSUE TITLE
Bug in LC compiler

### ISSUE THREAD

**Issue by lakpro** [LeetCode-Feedback/LeetCode-Feedback#10446]
#### LeetCode username: 
https://leetcode.com/Lakpro/

#### Category of the bug: 
Compiler Issues

#### Description of the bug
Recently I was solving a problem https://leetcode.com/problems/third-maximum-number/ and the compiler gave me the wrong answer. So, to debug it, I used cout command (C++), and to my surprise, the code worked! The same thing even happened when I submitted the code. 
(I am also attaching a video for the same.)

#### Code used for Submit/Run operation

```
class Solution {
public:
    int thirdMax(vector<int>& arr) {
        
        long long f,s,t = LONG_MIN;
        
                cout<<f<<" "<<s<<" "<<t<<endl;

        int l = arr.size();
        
        int mx=INT_MIN;
        
        
        for(int i=0;i<l;++i){
            
            if(f==arr[i] || s==arr[i] || t==arr[i])
                continue;
            
            
            if(arr[i]>f){
                t=s;
                s=f;
                f=arr[i];
            }
            else if(arr[i]>s){
                t=s;
                s=arr[i];
            }
            else if(arr[i]>t){
                t=arr[i];
            }
            
        }
        
                        cout<<f<<" "<<s<<" "<<t<<endl;

        if(t<INT_MIN)
            return f;
        
        return t;
        
    }
};
```

#### Language used for code
C++ 

#### Expected behavior
Whether I use cout command or not, the output should be the same.

#### Additional context
A video is added for your reference.

https://user-images.githubusercontent.com/73340463/208735826-fd5d99e0-91e1-44b6-bd08-3ad562dd8470.mp4

**Comment by nskybytskyi** [comment]
Your code has undefined behavior because you don't initialize variables `f` and `s`.

![with undefined behavior, anything is posible](https://pbs.twimg.com/media/D2CKKBRUkAAoXnM.jpg)

So there is no bug.

**Comment by LC-Pam** [comment]
Your code received AC after we submitted it: https://leetcode.com/submissions/detail/864029107/
The reason is because "Your code has undefined behavior because you don't initialize variables f and s."
Above comment is come from our internal tester, so please consider his comment as reference. 
We appreciate your support!
