### ISSUE TITLE
Missing Test Case. 2401. Longest Nice Subarray

### ISSUE THREAD

**Issue by XetmanX** [LeetCode-Feedback/LeetCode-Feedback#10448]
#### Your LeetCode username
user1673Z

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Test case similar to this [21, 2, 8, 23, 64, 128, 256, 512] is missing. I ran this test and my code got WA. But when I submitted the code it was accepted.

#### Code you used for Submit/Run operation

```
// 2401. Longest Nice Subarray
class Solution {
    public int longestNiceSubarray(int[] nums) {
        int result = 1;
        
        if(nums.length == 1)
            return 1;

        int row = nums[0];
        int newResult = 1;
        int startOfIteration = 0;
        for(int i = 1; i < nums.length; ++i){
            if((row & nums[i]) == 0){
                newResult++;
                row |= nums[i];
            }else{
                row ^= nums[startOfIteration++];
                if((row & nums[i]) == 0){
                    row |= nums[i];
                }else{
                    row = nums[i];
                    newResult = 1;
                    startOfIteration = i;
                }
            } 
            result = newResult > result ? newResult : result;           
        }
        return result;
    }
}
```

#### Language used for code

Java

#### Expected behavior

I expected that code will don't accepted.

#### Screenshots

![Снимок экрана (214)](https://user-images.githubusercontent.com/38360571/208743438-1a1f7538-1e3a-4278-9d5e-73e4da69948e.png)
![Снимок экрана (213)](https://user-images.githubusercontent.com/38360571/208743451-7e481fd1-1c8d-4cb9-a910-dcaa85068a6a.png)

#### Additional context

Need test case where the window will need to be reduced on the left side

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
