### ISSUE TITLE
Missing Test Case - 5. Longest Palindromic Substring

### ISSUE THREAD

**Issue by SwethaSelva** [LeetCode-Feedback/LeetCode-Feedback#10447]
#### Your LeetCode username

swethalakshmi64

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x] Missing Test Cases 

#### Description of the bug

I am able to submit my code though it failed for one custom test case. However, leet code doesn't have that testcase. Love to contribute.

#### Missing test case
Input : "caaaaa"
<img width="619" alt="Screenshot 2022-12-20 at 11 59 16 PM" src="https://user-images.githubusercontent.com/58015008/208739892-e9c23f3a-85a8-417e-baa9-2aa6cc8428a7.png">

#### Code you used for Submit/Run operation

```
// Longest Palindromic Substring
var longestPalindrome = function (s) {
  let q = [];
  let hash = { [s[0]]: [0] };
  let sameChar = s[0];
  for (let i = 0; i < s.length; i++) {
    if (!hash[s[i]]) {
      hash[s[i]] = [i];
      sameChar = null
    }
    else {
      let lastIdx = hash[s[i]][hash[s[i]].length - 1];
      if (i - lastIdx === 1 || i - lastIdx === 2) q.unshift([lastIdx, i]);
      hash[s[i]].push(i);
    }
  }
if (sameChar !== null) return s; 
  if (!q.length) return s[0];
  let output = [0, 0];
  while (q.length) {
    let [startIdx, endIdx] = q.pop();
    while (startIdx >= 0 && endIdx < s.length) {
      if (s[startIdx] !== s[endIdx]) break;
      if (endIdx - startIdx === 1) {
        if (startIdx - 1 >= 0 && s[startIdx] === s[startIdx - 1]) startIdx--;
        if (endIdx + 1 < s.length && s[endIdx] === s[endIdx + 1]) endIdx++;
      }
      startIdx--;
      endIdx++;
    }

    if (output[1] - output[0] - 1 < endIdx - startIdx - 1) {
      output = [startIdx, endIdx];
    }
  }
  return s.slice(output[0] + 1, output[1]);
};
```

#### Language used for code

Javascript

#### Expected behavior

The leetcode stop me to submit by code.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
