### ISSUE TITLE
Incorrect Constraints - 748. Shortest Completing Word

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1045]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

748. Shortest Completing Word
https://leetcode.com/problems/shortest-completing-word/

========
Examples are given as

>> Example 1:
>> Input: licensePlate = "1s3 PSt", words = ["step", "steps", "stripe", "stepple"]

>> Example 2:
>> Input: licensePlate = "1s3 456", words = ["looks", "pest", "stew", "show"]

In the Example 1 & 2 above, the words length is 4

But, "Note:" is given as below
  >> words will have a length in the range [10, 1000].

That is "Note:" says it is minimum 10, which is wrong even from the examples given.

Please fix the constraints, possibly as below, an example given below:
>> 1 <= words.length <= 1000

Example:

	Input:
		"1s3 PSt"
		["steps"]
	Output:
		"steps"

---------

A side note:

Please don't write constraints in english
	>> words will have a length in the range [10, 1000].
write it as:
	>> 1 <= words.length <= 1000
This way both author & user will see numbers easily & with less errors :)

---------

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

- Constraints must be correct
- Write constraints in a mathematical form instead of English form to reduce errors by Author & User

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy ,
Thank you for your feedback regarding this problem. Upon review, we have updated and added constraints for this problem. As noted for other related tickets, we will not be rewarding LeetCoins for these cases but you are more than welcome to issue a content-issue ticket.
