### ISSUE TITLE
Missing Test Case - 4. Median of Two Sorted Arrays

### ISSUE THREAD

**Issue by Abdelmohaymn** [LeetCode-Feedback/LeetCode-Feedback#10456]
#### Your LeetCode username

abdelmohaymn

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
-  Missing Test Cases 

#### Description of the bug

the problem complexity is o(log(n+m)) but when i  submitted a solution that taken o((n+m)log(n+m)) passed!

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    double findMedianSortedArrays(vector<int>& nums1, vector<int>& nums2) {
        nums1.insert(nums1.end(),nums2.begin(),nums2.end());
        sort(nums1.begin(),nums1.end());
        int m=nums1.size()/2;
        if(nums1.size()&1)
        {
            return nums1[m];
        }
        double res=(double)(nums1[m]+nums1[m-1])/2;
        return res;
    }
};
```

#### Language used for code

C++

#### Expected behavior

the program result must be time limit exceeded but i found that the solution accepted!

#### Additional context

this problem is categorized as hard because this small complexity (log(n+m))
so you should make  strong test cases or just change its category to easy because my naive solution accepted

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. To pass O(log(n+m)) only and fail O((n+m)log(n+m) would require test cases of size >10^7. Even then O(n) might pass. It is not possible to add test cases that large in size, since we have a max limit of input files. We appreciate your support!
