### ISSUE TITLE
Missing Test Case - 204. Count Primes

### ISSUE THREAD

**Issue by dipeshbindlish** [LeetCode-Feedback/LeetCode-Feedback#10451]
#### Your LeetCode username

dipeshbindlish

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug

I found a loophole in the leetcode test cases.
You can store test case values and expected output in any data structure and simply return the output rather than submitting a algo that calculates the output.

The solution to this would be to set some test cases to be randomly picked within certain ranges.

#### Code you used for Submit/Run operation

```
class Solution:
    def countPrimes(self, n: int) -> int:

        dict = {0: 0, 1: 0, 2: 0, 3: 1, 4: 2, 5: 2, 6: 3, 7: 3, 8: 4, 9: 4, 10: 4,11:4, 12: 5, 13: 5, 14: 6, 15: 6, 16: 6, 17: 6, 18: 7, 19: 7,40: 12, 50: 15, 10000: 1229, 499979: 41537, 999983: 78497,1500000: 114155,5000000: 348513,31722: 3410,65183: 6514,71056: 7036,74549: 7352,103382: 9879,106543: 10155,117153: 11057,130808: 12231,136649: 12727,138401: 12874,139583: 12972,154242: 14209,179765: 16318,192309: 17353,205922: 18455,211499: 18933,334286: 28738,345694: 29630,348436: 29852,367184: 31318,368349: 31410,417103: 35155,417498: 35188,430348: 36184,433933: 36477,461465: 38571,466793: 38972,469193: 39161,618395: 50499,619738: 50590,628545: 51233,629238: 51279,636381: 51825,688843: 55725,689171: 55750,691731: 55930,703823: 56828,709486: 57262,858232: 68216,867896: 68937,956150: 75354,959831: 75604,993422: 78022,994794: 78120,1000000: 78498}
        return dict[n]
```

#### Language used for code

Python

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The test cases will always be finite, and visible to user.
These are interview problems.  We appreciate your support!
