### ISSUE TITLE
Missing Test Case - 880. Decoded String at Index

### ISSUE THREAD

**Issue by aalshawa97** [LeetCode-Feedback/LeetCode-Feedback#10452]
#### Your LeetCode username

abdullah97

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 
- [ ] 
Do you want to add some test cases?

#### Description of the bug

Could you please add this test case?
"a2345678999999999999999"
1
Answer: a

"ha22"
5
Answer:error

""
5
Answer:error

#### Code you used for Submit/Run operation

```
// 880. Decoded String at Index
class Solution(object):
    def decodeAtIndex(self, s, k):
        """
        :type s: str
        :type k: int
        :rtype: str
        """
        i = 0
        cnt = 0
        while cnt < k:
            if s[i].isdigit():
                cnt = cnt * int(s[i])
            else:
                cnt += 1
            i+=1
        while i > 0:
            i-=1
            if s[i].isdigit():
                cnt = cnt / int(s[i])
                k %= cnt
            else:
                if(k%cnt==0):
                    return str(s[i])
                cnt -=1
        return ""

#### Language used for code
<!-- C++ -->


#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->



#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code AC link after submit. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by aalshawa97** [comment]
https://leetcode.com/problems/decoded-string-at-index/submissions/862831835/

**Comment by nongson** [comment]
You also encountered a similar problem and solved it with JavaScript, right? This decodeAtIndex function uses two loops to iterate through the input string. The first loop calculates the size of the decoded string by counting the number of letters and multiplying the size by that number if a digit is encountered. The second loop iterates through the input string in reverse order and calculates the kth letter by using the modulo operator and checking if the current character is a letter. If the kth letter is found, it is returned. If the end of the string is reached without finding the kth letter, the function returns an empty string.
`/**
 * @param {string} s
 * @param {number} k
 * @return {string}
 */
var decodeAtIndex = function(s, k) {
    let i = 0;
    let cnt = 0;
    while (cnt < k) {
        if (s[i].match(/[0-9]/)) {
            cnt *= parseInt(s[i]);
        } else {
            cnt += 1;
        }
        i += 1;
    }
    while (i > 0) {
        i -= 1;
        if (s[i].match(/[0-9]/)) {
            cnt /= parseInt(s[i]);
            k %= cnt;
        } else {
            if (k % cnt === 0) {
                return s[i];
            }
            cnt -= 1;
        }
    }
    return "";
};
`
