### ISSUE TITLE
TLE on 211. Design Add and Search Words Data Structure

### ISSUE THREAD

**Issue by omeraktepeboun** [LeetCode-Feedback/LeetCode-Feedback#10454]
#### Your LeetCode username
omeraktepe

#### Category of the bug
- [ ] Solution
- [ ] Language

#### Description of the bug
I would like to report the problem: 211. Design Add and Search Words Data Structure: https://leetcode.com/problems/design-add-and-search-words-data-structure/
My issue is in Python 3. If we write a separate class for Trie, it can give TLE no matter how good we optimize the code. If we do not use class and use a simple dictionary working as a Trie, then it works efficiently. I am not sure if this a key part of the question or just a bug. I have seen numerous people having the same issue in the Discuss section. It seems that in other languages you can create a Trie class without getting TLE. 
Also, there are times that the same code (written with Trie Class) may not give TLE and be in 60 percentile in terms of time. This means that it is kind of luck to get TLE.

#### Code you used for Submit/Run operation

```
class Trie:
    def __init__(self):
        self.child = {}
        self.endOfWord = False

class WordDictionary:

    def __init__(self):
        self.root = Trie()

    def addWord(self, word: str) -> None:
        curr = self.root
        for c in word:
            if c not in curr.child:
                curr.child[c] = Trie()
            curr = curr.child[c]
        curr.endOfWord = True
        return

    def search(self, word: str) -> bool:
        def dfs(node, i):
            if i == len(word):
                return node.endOfWord
            
            if word[i] in node.child:
                return dfs(node.child[word[i]], i+1)
            elif word[i] == '.':
                for child in node.child:
                    if dfs(node.child[child], i+1):
                        return True
                return False
            return False
        
        return dfs(self.root, 0)

# Your WordDictionary object will be instantiated and called as such:
# obj = WordDictionary()
# obj.addWord(word)
# param_2 = obj.search(word)
```

#### Expected behavior
I expected to be able to solve the problem by defining a Trie class since the question gives no restrictions about what we can use. I also expected not to get TLE randomly.

**Comment by LC-Pam** [comment]
Thanks for reaching out to us!
 
The purpose of support is to help users with our site, we're unable to provide specifics on what is causing your submission to receive a TLE. We encourage our users to utilize the discuss section of the problem to receive code feedback, you should receive feedback on your discuss post very soon.
I hope this helps. Please let us know if there's anything else we can do to assist.
