### ISSUE TITLE
question type (Easy, Medium, Hard ) is not visible 

### ISSUE THREAD

**Issue by devam2001** [LeetCode-Feedback/LeetCode-Feedback#10461]
#### Your LeetCode username

devam25

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

question type (Easy, Medium, Hard ) is not visible 

#### Screenshots

![leetcode](https://user-images.githubusercontent.com/56464719/208888903-b1a73425-9b37-494f-86b1-10e2ea99efde.png)

**Comment by LC-Pam** [comment]
![Screen Shot 2022-12-22 at 3 05 59 PM](https://user-images.githubusercontent.com/103138242/209217305-64d42f3e-8bb8-4e9f-b50f-a4ec880e4c71.png)
