### ISSUE TITLE
Missing Test Case - 886. Possible Bipartition

### ISSUE THREAD

**Issue by slch** [LeetCode-Feedback/LeetCode-Feedback#10468]
#### Your LeetCode username
slch

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Wrong answer for edge case.

#### Code you used for Submit/Run operation

```C#
public class Solution {
    public bool PossibleBipartition(int n, int[][] dislikes) {
        return false;
    }
}
```

#### Language used for code

C#

#### Expected behavior

With `n=1`, where `n` is number of people, one can not split into 2 groups (as a whole).
Current solution returns `true` for input `n = 1` and `dislikes = []`.

#### Screenshots

<details>

![Screenshot_20221221_201507](https://user-images.githubusercontent.com/2884941/208951747-8f50bbaa-d095-481d-9091-a287daff816a.png)

</details>

**Comment by harshy736** [comment]
There is written that a group can be of any size, so it means a group of size 0 is also a valid group.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
