### ISSUE TITLE
Typo in official problem solution description - 886. Possible Bipartition

### ISSUE THREAD

**Issue by ddyacn** [LeetCode-Feedback/LeetCode-Feedback#10471]
#### Your LeetCode username
1mann

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
https://leetcode.com/problems/possible-bipartition/solutions/2834180/possible-bipartition/

There are 2 typos:
1. intializing -> should be initializing (with i)
2. adjancency -> should be adjacency (without n)

#### Screenshots

![Screenshot 2022-12-21 at 19 38 00](https://user-images.githubusercontent.com/3447508/208980368-5422219b-eed0-441d-8f98-4cc01ccd937a.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
