### ISSUE TITLE
1502. Can Make Arithmetic Progression From Sequence - TestCase

### ISSUE THREAD

**Issue by GouravRusiya30** [LeetCode-Feedback/LeetCode-Feedback#1047]
#### Your LeetCode username
[rusiya](https://leetcode.com/rusiya/)

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Wrong solution accepted because of missed test case.

#### Code you used for Submit/Run operation

[Submitted code link](https://leetcode.com/submissions/detail/378377095/)

```
/**
* Approach is to use AP formula
* Sum = n/2(a+l)

where sum will be sum of all elements
n will be number of elements
a will be minimum element
l will be maximum element

if both LHS & RHS values are equal then true else false.
*/
class Solution {
    public boolean canMakeArithmeticProgression(int[] arr) {
        int n = arr.length;
        
        double sumOfMaxAndMin = 0;
        
        int sum = arr[0];
        int max = arr[0];
        int min = arr[0];
        
        // Traverse the array and find out sum, max & min
        for (int i=1; i<n; i++){
            sum += arr[i];
            
            if (max < arr[i]){
                max = arr[i];
            }
            
            if (arr[i] < min){
                min = arr[i];
            }
        }
        
        // add max & min -> also they are first & last element
        sumOfMaxAndMin = max + min;
        
        // multiply above value with n
        sumOfMaxAndMin *= n;
        
        // divide above value with 2
        sumOfMaxAndMin /= 2;
        
        if (sum == sumOfMaxAndMin){
            return true;
        }
        
        return false;
    }
}
```

#### Language used for code
Java

#### Expected behavior
Input:
[2, 10, 7, 8, 3]

Output:
true

Expected:
false

Although it was giving "Wrong Answer" in console
But still my above pasted code/solution got accepted.

#### Screenshots
![image](https://user-images.githubusercontent.com/13219295/93763469-21442d00-fc2f-11ea-819b-1586d090a053.png)

#### Additional context
I have also submitted it a month ago from the website page but still it is showing Pending. Please have a look on this asap. Attaching the sanpshot too.

![image](https://user-images.githubusercontent.com/13219295/93763623-68cab900-fc2f-11ea-8f9a-bf2994c25ab7.png)

**Comment by GouravRusiya30** [comment]
Any updates ???

**Comment by lc-ivan** [comment]
Hi @GouravRusiya30 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @GouravRusiya30 ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by GouravRusiya30** [comment]
Thanks @lc-ivan
