### ISSUE TITLE
Missing Test Case - 483. Smallest Good Base

### ISSUE THREAD

**Issue by calcwatch** [LeetCode-Feedback/LeetCode-Feedback#10470]
#### Your LeetCode username

calcwatch 

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

I’d suggest adding `"999999005000247507"` to the list of test cases. My solution was accepted even though it was suboptimal and used some shortcuts. This test case would break it.

My algorithm worked like this:

1. Use the sieve of Eratosthenes algorithm to build a list of all primes less than 2,000,000.
2. Use the prime list to find the prime factorization of `n - 1`. Since all of the primes in the list are under 2,000,000, assume that any relatively prime numbers greater than 2,000,000 are prime.
3. Using the prime factorization, test every factor of `n - 1` as a potential base, in ascending order.

The above algorithm was good enough because for all current test cases, the second largest prime factor of `n - 1` is less than 2,000,000. But in the case of n = 999,999,005,000,247,507, n - 1 = 999,999,005,000,247,506 = 2 * 499,999,751 * 999,999,503.

To get the right answer with my method,  I’d need a sieve storing all primes less than ~500,000,000, and attempting that would exceed the time limit.

#### Code you used for Submit/Run operation

https://leetcode.com/submissions/detail/863295120/

```python
MAX = 2000000
HALF = MAX >> 1

sieve = bytearray(HALF)

for i in range(int(MAX**0.5)>>1):
  if sieve[i]:
    continue
  v = (i << 1) + 3
  for j in range(v**2, MAX, v << 1):
    sieve[(j - 3) >> 1] = 1

primes = tuple([2] + [(i << 1) + 3 for i,v in enumerate(sieve) if not v])

@cache
def testbase(b):
  n = gn + 1
  rem = 0
  while True:
    n, rem = divmod(n - 1, b)
    if rem:
      return False
    if not n:
      return True

calls = 0
seen = {}

class Solution:
  def smallestGoodBase(self, n: str) -> str:
    global gn,sol, calls, ps, seen
    seen = {}
    
    gn = int(n) - 1

    sqrt = int(gn ** 0.5)
    ps = defaultdict(int)
    g = gn
    for p in primes:
      if p > sqrt:
        break
      if not g % p:
        while not g % p:
          ps[p] += 1
          g //= p
        if g == 1:
          break
        sqrt = int(g ** 0.5)
    if g != 1:
      ps[g] = 1
    
    testbase.cache_clear()
    seen = set()
    tv = [(1, ps)]
    while tv:
      b, ps = heappop(tv)
      if b in seen:
        continue
      seen.add(b)

      if (b > 1) and testbase(b):
        return str(b)
      for p, freq in ps.items():
        b2 = p * b
        if b2 in seen:
          continue
        ps2 = ps.copy()
        if freq == 1:
          del ps2[p]
        else:
          ps2[p] -= 1
        heappush(tv, (b2, ps2))  
```

#### Language used for code

Python

#### Expected behavior

The reference solution gives the correct answer for my suggested test case. My code above returns `n-1`, because it doesn’t know about primes greater than 2 million, and enlarging the sieve would cause it to run for too long.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
