### ISSUE TITLE
Missing Test Case - 2510. Check if There is a Path With Equal Number of 0's And 1's

### ISSUE THREAD

**Issue by nskybytskyi** [LeetCode-Feedback/LeetCode-Feedback#10477]
#### Your LeetCode username

[nskybytskyi](https://leetcode.com/nskybytskyi/)

#### Category of the bug

- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The below submission for [2510. Check if There is a Path With Equal Number of 0's And 1's](https://leetcode.com/problems/check-if-there-is-a-path-with-equal-number-of-0s-and-1s/) gets AC on the current test suite, but gets WA on the following test case: `grid = [[0,0,0],[0,0,1]]`. 

#### Code you used for Submit/Run operation

[Submission link](https://leetcode.com/problems/check-if-there-is-a-path-with-equal-number-of-0s-and-1s/submissions/863696530/)

```py
class Solution:
    def isThereAPath(self, grid: List[List[int]]) -> bool:
        m, n = len(grid), len(grid[0])
        if (m+n-1) % 2 == 1: return False

        mmin = [[0]*(n+1) for _ in range(m+1)]
        mmax = [[0]*(n+1) for _ in range(m+1)]

        for r in range(m):
            for c in range(n):
                cur = 2 * grid[r][c] - 1
                mmin[r+1][c+1] = min(mmin[r][c+1], mmin[r+1][c]) + cur
                mmax[r+1][c+1] = max(mmax[r][c+1], mmax[r+1][c]) + cur

        return mmin[-1][-1] <= 0 and mmax[-1][-1] >= 0
```

#### Language used for code

Python

#### Expected behavior

The above submission gets WA.

#### Additional context

This solution was suggested by user [alanlzl](https://leetcode.com/alanlzl/) in the comments [here](https://leetcode.com/problems/check-if-there-is-a-path-with-equal-number-of-0s-and-1s/solutions/2936391/python-o-nm-min-max-w-proof/). 

This issue is different from #10472 which focuses on TLEing recursion without memorization, whereas this one deals with invalid padding values.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
