### ISSUE TITLE
Missing Test Case - 23. Merge k Sorted Lists

### ISSUE THREAD

**Issue by RetroInferno** [LeetCode-Feedback/LeetCode-Feedback#10473]
#### Your LeetCode username

[RetroInferno](https://leetcode.com/RetroInferno/)

#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Test case: lists = [[1,2,2],[1,1,2]] results in "Time Exceeded" but runs just fine when the testing individually via "Run"

#### Code you used for Submit/Run operation

```
import heapq
class Solution(object):
    def mergeKLists(self, lists):
        """
        :type lists: List[ListNode]
        :rtype: ListNode
        """
        if len(lists) < 1:
            return None

        head = currNode = ListNode(0)
        q = []
        for node in lists:
            if node:
                q.append((node.val, id(node), node))
        heapq.heapify(q)
        counter = 0
        while q:
            counter += 1
            val, dumb ,node = q[0]
            currNode.next = node
            currNode = currNode.next
            node = node.next
            if node:
                heapq.heappushpop(q, (node.val, id(node) ,node))
            else:
                heapq.heappop(q)
        print(counter)
        return head.next

```

#### Language used for code

Python3

#### Expected behavior

Expecting test case to pass.

**Comment by LC-Pam** [comment]
Thanks for reaching out to us!
 

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

The purpose of support is to help users with our site, we're unable to provide specifics on what is causing your submission to receive a TLE. We encourage our users to utilize the discuss section of the problem to receive code feedback, you should receive feedback on your discuss post very soon.


I hope this helps. Please let us know if there's anything else we can do to assist.
