### ISSUE TITLE
Missing Test Case - 2510. Check if There is a Path With Equal Number of 0's And 1's

### ISSUE THREAD

**Issue by nskybytskyi** [LeetCode-Feedback/LeetCode-Feedback#10472]
#### Your LeetCode username

[nskybytskyi](https://leetcode.com/nskybytskyi/)

#### Category of the bug

- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The below submission for [2510. Check if There is a Path With Equal Number of 0's And 1's](https://leetcode.com/problems/check-if-there-is-a-path-with-equal-number-of-0s-and-1s/) gets AC on the current test suite, but TLEs on the following test case: 99 x 100 grid full of zeroes.

#### Code you used for Submit/Run operation

[Submission link](https://leetcode.com/problems/check-if-there-is-a-path-with-equal-number-of-0s-and-1s/submissions/863410458/)

```py
class Solution:
    def isThereAPath(self, grid: List[List[int]]) -> bool:
        def dfs(row, col, remain):
            if (row, col) == (m - 1, n - 1):
                return remain == 0
            
            if remain < 0:
                return False
            
            for r, c in [(row, col + 1), (row + 1, col)]:
                if 0 <= r < m and 0 <= c < n:
                    if dfs(r, c, remain - grid[r][c]):
                        return True
            
            return False
        
        m, n = len(grid), len(grid[0])
        if (m + n) % 2 == 0:
            return False
        
        target = (m + n) // 2
        return dfs(0, 0, target - grid[0][0])
```

#### Language used for code

Python

#### Expected behavior

The above submission gets TLE.

#### Additional context

The presented solution belongs to user [usephysics](https://leetcode.com/usephysics/) as posted [here](https://leetcode.com/problems/check-if-there-is-a-path-with-equal-number-of-0s-and-1s/solutions/2936663/python-simple-dfs-104ms)

The following Python3 code generates the suggested testcase:
```py
print([[0] * 100 for _ in range(99)])
```

**Comment by nskybytskyi** [comment]
Another submission that fails on this test case: [link](https://leetcode.com/problems/check-if-there-is-a-path-with-equal-number-of-0s-and-1s/submissions/863414806/), posted by [briancsparks](https://leetcode.com/briancsparks/) [here](https://leetcode.com/problems/check-if-there-is-a-path-with-equal-number-of-0s-and-1s/solutions/2936703/brute-force-recursive-too-verbose-but-very-clear/):

```cpp
class Solution {
public:
    bool isThereAPath(vector<vector<int>>& grid) {
        int h = grid.size();
        int w = grid[0].size();
        int path_len = w+h-1;
        if (path_len % 2 == 1) {return false;}

        int zeros = path_len / 2;
        int ones  = zeros;

        int value = grid[0][0];
        if (value == 0) {
            zeros--;
        } else {
            ones--;
        }

        if (isThereAPath(grid, 1,0, zeros, ones)) {
            return true;
        }

        if (isThereAPath(grid, 0,1, zeros, ones)) {
            return true;
        }

        return false;        
    }

    bool isThereAPath(vector<vector<int>>& grid, int x, int y, int zeros, int ones) {
        int h = grid.size();
        int w = grid[0].size();

        if (x >= w || y >= h) {return false;}
        if (zeros < 0 || ones < 0) {return false;}
        
        int value = grid[y][x];
        if (value == 0) {
            zeros--;
        } else {
            ones--;
        }

        if (x == w-1 && y == h-1 && zeros == 0 && ones == 0) {
            return true;
        }

        if (isThereAPath(grid, x+1,y, zeros, ones)) {
            return true;
        }

        if (isThereAPath(grid, x,y+1, zeros, ones)) {
            return true;
        }

        return false;        
    }
};
```

**Comment by nskybytskyi** [comment]
Yet another submission that fails on this test case: [link](https://leetcode.com/problems/check-if-there-is-a-path-with-equal-number-of-0s-and-1s/submissions/863418059/) posted by [warrenruud](https://leetcode.com/warrenruud/) [here](https://leetcode.com/problems/check-if-there-is-a-path-with-equal-number-of-0s-and-1s/solutions/2936773/python-3-9-lines-recursion-t-m-76-ms-14-4-mb/):

```py
class Solution:
    def isThereAPath(self, grid: List[List[int]]) -> bool:

        def dfs(r,c, target):

            if r == m or c == n: return False
            if target <= 0: return target == 0

            target-= grid[r][c]

            return dfs(r+1, c, target) or dfs(r, c+1, target)

        m,n = len(grid), len(grid[0])
        if not(m+n)%2: return False
        target = (m+n)//2 - grid[0][0]
        
        return dfs(0,0,target)
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
