### ISSUE TITLE
Submission Error

### ISSUE THREAD

**Issue by gh4abhi** [LeetCode-Feedback/LeetCode-Feedback#10487]
#### Your LeetCode username
gh4abhi

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Facing an error while submitting code. The same error comes every time I try to submit my code.

#### Code you used for Submit/Run operation
```
class Solution {
public:
    bool searchMatrix(vector<vector<int>>& matrix, int target) {
        ll m = matrix.size();
        ll n = matrix[0].size();
        ll start = 0, end = m*n-1;
        while(start<=end)   
        {
            ll mid = start + (end-start)/2;
            ll op = matrix[mid/n][mid%n];
            if(op>target)
                end = mid-1;
            else if(op<target)
                start = mid+1;
            else
                return true;
        }
        return false;
    }
};
```

#### Language used for code
 C++

#### Expected behavior

I thought the solution would be submitted but it showed internal error.

#### Screenshots

![image](https://user-images.githubusercontent.com/63967165/209237049-9bb9f06d-3ff2-486f-8be4-fbade035b8eb.png)

#### Additional context
 The same problem is being showed while submitting every problem on the platform.

**Comment by gh4abhi** [comment]
I will not be able to maintain my streak due to this issue. Kindly help.

**Comment by balwierz** [comment]
I am getting the same errors with all submissions I tried. 
Basically the testing system does not work.
It is almost midnight and I was struggling to maintain my 160+ days streak, and it looks like I am going to loose it. Can you do something about it?

**Comment by YuvrajRakheja** [comment]
I am also  getting the same errors with all submissions I tried.I will not be able to maintain my streak due to this issue. Kindly help.

**Comment by YuvrajRakheja** [comment]
![image](https://user-images.githubusercontent.com/83249226/209238419-a1aad9b0-9ac1-4e8c-b15c-9f366cce6848.png)

**Comment by YuvrajRakheja** [comment]
![image](https://user-images.githubusercontent.com/83249226/209238716-2e3f3aa7-348c-442a-b2bc-65f84a08076c.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The Problems that showed Internal Error when you submit your code.
Is the issue still exist?

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by gh4abhi** [comment]
Now the issue has been resolved.
