### ISSUE TITLE
Python3 runtime giving false error

### ISSUE THREAD

**Issue by muneeb-devp** [LeetCode-Feedback/LeetCode-Feedback#10484]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
The python3 runtime throws an error for my code, even though it works fine locally on my system.

#### Code you used for Submit/Run operation

```
// Find Pivot Index - 724
class Solution:
    def pivotIndex(self, nums: List[int]) -> int:
      for i in range(len(nums)):
        if i == 0  or i == (len(nums) -1):
          if  sum(nums[i+1::]) == 0 and sum(nums[:-1:] == 0):
            return i
        
        if sum(nums[:i]) == sum(nums[i+1::]):
          return i

      return -1
```

#### Language used for code

Python3

#### Expected behavior

The LeetCode testing engine should allow my code to be submitted and not throw any error.

#### Screenshots

![1](https://user-images.githubusercontent.com/57582700/209188272-0517291d-83b2-4994-b507-e4af18296db3.png)
---------------
![2](https://user-images.githubusercontent.com/57582700/209188362-22dc0796-e50d-41c9-9042-d1c533de10e6.png)

**Comment by nskybytskyi** [comment]
It is not obvious in the new design, but the runtime error occurs for `nums = [1,2,3]`, not for `nums = [1,7,3,6,5,6]`. The source of the issue is a typo: `sum(nums[:-1:] == 0)` instead of `sum(nums[:-1:]) == 0`.

**Comment by muneeb-devp** [comment]
That is correct. Sorry, overlook that tiny detail.
