### ISSUE TITLE
The last line doesn't display well

### ISSUE THREAD

**Issue by qiushile** [LeetCode-Feedback/LeetCode-Feedback#10483]
#### Your LeetCode username

qiushile

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The last line on this page is not readable: 
https://leetcode.com/explore/learn/card/fun-with-arrays/521/introduction/3221/

#### Code you used for Submit/Run operation

```
<div class="block-markdown">
```

#### Language used for code

HTML

#### Expected behavior

The whole line can be seen.

#### Screenshots

![image](https://user-images.githubusercontent.com/3357367/209134752-e6bba3a4-07d1-44e6-87fc-f339c07b369b.png)

**Comment by qiushile** [comment]
The browser is Google Chrome, and the version is 99.0.4844.51 (x86_64)
The OS is macOS Monterey - 12.6.1
All the pages meet the same situation in https://leetcode.com/explore/learn/card/

**Comment by qiushile** [comment]
This is a reproducible issue.
It happens every time the bar(力扣「中文社区」) appears at the top of the page.

**Comment by LC-Pam** [comment]
![Screen Shot 2022-12-23 at 1 26 28 PM](https://user-images.githubusercontent.com/103138242/209391635-8b1eaf3f-87c4-44f3-9982-3f7cf159429f.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.  I've relayed this issue to our team to investigate since it works correct on the all the explore card when we open them.

**Comment by LC-Pam** [comment]
Hi there, 

I've passed your feedback to our engineering team and they'll investigate. However, I'm afraid that we won't have a quick fix for the issue that you're facing.

Best,

LC
