### ISSUE TITLE
Missing Test Case - 726. Number of Atoms

### ISSUE THREAD

**Issue by 3devRapeti** [LeetCode-Feedback/LeetCode-Feedback#10486]
#### Your LeetCode username
3devRapeti

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
As it was mentioned in the question, there could be zero or more small letters followed after capital letters, but there are no testcases which contain more than 1 small letters after capital letters. So, adding a test case which contain more than one small letter should work for good.

#### Code you used for Submit/Run operation
```
class Solution {
public:
    int numb(string s, int &i) {
        int k=0;
        while(i<s.size() && ((int)s[i])>47 && ((int)s[i])<58) {
            k*=10;
            k+=((int)(s[i]-'0'));
            i++;
        }
        i--;
        return k;
    }
    string countOfAtoms(string s) {
        map<string,int>a;
        stack<int>b;
        vector<int>c;
        for(int i=0; i<s.size(); i++) {
            if(s[i]=='(') {
                b.push(c.size());
                c.push_back(0);
            }
            else if(s[i]==')') {
                int k=0;
                i++;
                c[b.top()]=max(numb(s,i),1);
                b.pop();
            }
        }
        for(int i=0,j=0; i<s.size(); i++) {
            if(((int)s[i])>=65 && ((int)s[i])<=90) {
                string s1="";
                s1.push_back(s[i]);
                i++;
                int k;
                while(i<s.size() && ((int)s[i])>=97 && ((int)s[i])<=122) {                //this line
                    s1.push_back(s[i]);
                    i++;
                }
                if(i<s.size() && ((int)s[i])>47 && ((int)s[i])<58) k=numb(s,i);
                else i--,k=1;
                if(!b.empty()) a[s1]+=k*b.top();
                else a[s1]+=k;
            }
            else if(s[i]=='(') {
                if(!b.empty()) b.push(c[j]*b.top());
                else b.push(c[j]);
                j++;
            }
            else if(s[i]==')') b.pop();
        }
        string ans="";
        for(auto itr:a) {
            if(itr.second) ans+=itr.first;
            if(itr.second>1) {
                stringstream ss;
                string s2;
                ss << itr.second;
                ss >> s2;
                ans+=s2;
            }
        }
        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior
This code actually is the optimal code but even when there is an 'if' in place of 'while' in the 23rd line of the countOfAtoms function (marked with a comment), does the job due to the lack of a test case that contains more than 1 small letter after a capital letter.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
