### ISSUE TITLE
420 - Strong Password Checker

### ISSUE THREAD

**Issue by dgjinovci** [LeetCode-Feedback/LeetCode-Feedback#10495]
#### Your LeetCode username

gno7

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Testcase 27 / 52 
input: aaaB1
output: 1 

You have five characters and three of them are repeating in a row, needs two steps (one step to add one char, another step to change repeating chars) 
Output should be: 2 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

Java

#### Expected behavior

You have five characters and three of them are repeating in a row, needs two steps (one step to add one char, another step to change repeating chars) 
Output should be: 2 

#### Additional context

A password is considered strong if the below conditions are all met:

- It has at least 6 characters and at most 20 characters.
- It contains at least one lowercase letter, at least one uppercase letter, and at least one digit.
- It does not contain three repeating characters in a row (i.e., "Baaabb0" is weak, but "Baaba0" is strong).

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by stormsunshine** [comment]
When you insert a character, why do you have to keep the three repeating letters? You can insert any uppercase letter or any digit between any two adjacent letters. For example, you can use one insertion to get "aBaaB1" to get a strong password, which uses only one step.
