### ISSUE TITLE
Missing Test Case - 886. Possible Bipartition

### ISSUE THREAD

**Issue by Nitin-Yadav-1** [LeetCode-Feedback/LeetCode-Feedback#10499]
#### Your LeetCode username
nitin987

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

For graphs with disconnected components, if I process non-bipartite components first and finally override the result with last bipartite component the answer should be false but the solution is accepted even if I return true.

For the testcase : n = 5, edges = [ [1,2], [2,3], [1,3], [4,5] ]

This graph has two components = {1,2,3}, {4,5}
{1,2,3} is non-bipartite and {4,5} is bipartite.

In my code I start Depth First Search from node=1 and result is false.
But then I override the result with starting from node=4 which is true.
The answered returned is true and the solution is accepted but it should return false.

On running a custom testcase, it shows wrong answer as it expects false.

#### Code you used for Submit/Run operation

```
class Solution {
    static int BLACK = Integer.MAX_VALUE;
    static int WHITE = Integer.MIN_VALUE;

    public boolean possibleBipartition(int n, int[][] dislikes) {
        
        List<List<Integer>> graph = createGraph(n, dislikes);
        int[] assignedColors = new int[n+1];

        boolean result = false;

        for( int i = 1; i < assignedColors.length; i++ )
            if( assignedColors[i] == 0 )
                result = solve(i, BLACK, assignedColors, graph);

        return result;
    }

    boolean solve(int node, int color, int[] assignedColors, List<List<Integer>> graph ){
        //base condition : if color of node does not matches to assigned
        if( assignedColors[node] != 0 )
            return (assignedColors[node] == color);

        //assign color 
        assignedColors[node] = color;

        //call for adjacent nodes with different color
        int newColor = (color == BLACK) ? WHITE : BLACK;

        for( int adjNode : graph.get(node) )
            if( solve(adjNode, newColor, assignedColors, graph) == false )
                return false;

        return true;
    }


    List<List<Integer>> createGraph(int nodes, int[][] edges ){

        List<List<Integer>> graph = new ArrayList<>();

        for( int i = 0; i <= nodes; i++ )
            graph.add(new ArrayList<Integer>());

        for( int i = 0; i < edges.length; i++ ){
            int u = edges[i][0];
            int v = edges[i][1];
            graph.get(u).add(v);
            graph.get(v).add(u);
        }

        return graph;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The above code should fail

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We did not add test case as solution fails on updated test set.  We appreciate your support!

**Comment by Nitin-Yadav-1** [comment]
Glad I could help :+1:
