### ISSUE TITLE
Unclear wording in Question - 1414. Find the Minimum Number of Fibonacci Numbers Whose Sum Is K

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1049]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

1414. Find the Minimum Number of Fibonacci Numbers Whose Sum Is K
https://leetcode.com/problems/find-the-minimum-number-of-fibonacci-numbers-whose-sum-is-k/

I upvoted the question.
However the "whether a Fibonacci number could be used multiple times." part of the question is unclear:
- Does it mean duplicates are allowed?
- Can we count a number in the Fibonacci series, multiple times, to get the sum as K?

Please reword the question for the above part so it can be proper English.

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

The question should be unambiguous.
See the description above.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
