### ISSUE TITLE
Missing Test Case - 169. Majority Element

### ISSUE THREAD

**Issue by c1415926** [LeetCode-Feedback/LeetCode-Feedback#10492]
#### Your LeetCode username
user3593Z

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
My solution was wrong but it actually got AC with the current testcases.
I can get WA with this case:
````
[1000,2,1001,1000,1000]
````

#### Code you used for Submit/Run operation
```
public int majorityElement(int[] nums) {
        int n = nums.length;
        long sum = 0L;

        for (int i = 0; i < n; i++) {
            sum += nums[i];
        }
        long avg = sum / n;
        int left = 0;
        int right = n - 1;
        while (left < right) {
            while (left < right && nums[right] > avg)
                right--;
            while (left < right && nums[left] <= avg)
                left++;
            int t = nums[right];
            nums[right] = nums[left];
            nums[left] = t;
        }

        return nums[n / 2];
    }
```

#### Language used for code
Java

#### Expected behavior
It should give WA.

#### Screenshots
![20221223171805](https://user-images.githubusercontent.com/10542874/209299652-55de502a-081b-4be0-a5ed-704100d439e5.png)
![20221223171908](https://user-images.githubusercontent.com/10542874/209299675-0a144298-dd51-43e9-8e4d-290d2a272f72.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submit AC link (we received Compile Error when we submitted your above code: https://leetcode.com/submissions/detail/864387710/)

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by c1415926** [comment]
> The code submit AC link (we received Compile Error when we submitted your above code: https://leetcode.com/submissions/detail/864387710/)

Sorry I only pasted the method without the class definition.

Here is the full code. And also the AC submit link: https://leetcode.com/problems/majority-element/submissions/864141327/
````
class Solution {
    public int majorityElement(int[] nums) {

        int n = nums.length;
        long sum = 0L;

        for (int i = 0; i < n; i++) {
            sum += nums[i];
        }
        long avg = sum / n;
        int left = 0;
        int right = n - 1;
        while (left < right) {
            while (left < right && nums[right] > avg)
                right--;
            while (left < right && nums[left] <= avg)
                left++;
            int t = nums[right];
            nums[right] = nums[left];
            nums[left] = t;
        }

        return nums[n / 2];
        
    }
}
````

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
