### ISSUE TITLE
460. LFU缓存 题目描述翻译不完整

### ISSUE THREAD

**Issue by xmcgcg** [LeetCode-Feedback/LeetCode-Feedback#105]
** Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
英文描述定义了【项目的使用次数】：
> Note that the number of times an item is used is the number of calls to the `get` and `put` functions for that item since it was inserted. This number is set to zero when the item is removed.

这一段在中文版中没有翻译。

**期望行为**
在【进阶】部分前补充一段翻译：
> 一个项目的使用次数就是该项目被插入后对其调用 `get` 和 `put` 函数的次数之和。使用次数会在对应项目被移除后置为 0。

**Comment by feiceh** [comment]
已作补充～
