### ISSUE TITLE
Incorrect Python Interpreter - 886. Possible Bipartition

### ISSUE THREAD

**Issue by JiayangZhou** [LeetCode-Feedback/LeetCode-Feedback#10502]
#### Your LeetCode username
dengdaiyigeren

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Incorrect Test Cases 

#### Description of the bug
The Python Interpreter behaves strangely on some test cases. It works fine if I define a list in the function and pass it to the inner functions, but once I define a global list, and use it like this `self.list_name`, the list was "as if" being pre-populated by something before the function was called.

#### Code you used for Submit/Run operation
Test Case:
```
n = 5
dislikes = [[1,2],[1,3],[1,4],[1,5]]
```

```
// Wrong Result Code (interesting parts are marked with !!!) - use global list
class Solution:
    ans = True
    group1 = []
    group2 = []
    def possibleBipartition(self, n: int, dislikes: List[List[int]]) -> bool:
        print(self.group1) ## This Prints [1, 4] !!! why?
        print(self.group2) ## This Prints [2, 3] !!!
        d = {_:[] for _ in range(1, n + 1)}
        for item in dislikes:
            a = item[0]
            b = item[1]
            d[a].append(b)
            d[b].append(a)
        v = [False] * (n + 1)
        for i in range(1, n + 1):
            if not v[i]:       
                self.traversal(g="a", v=v, d=d, s=i)
            
        print(self.group1) ## This Prints [1, 4] !!!
        print(self.group2) ## This Prints [2, 3] !!!
        return self.ans
    def traversal(self, g: str, v:[], d: {}, s: int) -> None:
        if not self.ans:
            return
        v[s] = True
        g_or = g
        if g == "a":
            if s in self.group1:
                self.ans = False
            else:
                self.group1.append(s)
            g = "b"
        else:
            if s in self.group2:
                self.ans = False
            else:
                self.group2.append(s)
            g = "a"
        for hate in d[s]:
            if not v[hate]:
                self.traversal(g=g, v=v, d=d, s=hate)
            else:
                if g_or == "a":
                    if hate in self.group1:
                        self.ans = False
                else:
                    if hate in self.group2:
                        self.ans = False
                
```

```
// Correct Result Code (interesting parts are marked with !!!) - do not use global list
class Solution:
    ans = True
    def possibleBipartition(self, n: int, dislikes: List[List[int]]) -> bool:
        group1 = []
        group2 = []
        d = {_:[] for _ in range(1, n + 1)}
        for item in dislikes:
            a = item[0]
            b = item[1]
            d[a].append(b)
            d[b].append(a)
        print(d)
        v = [False] * (n + 1)
        for i in range(1, n + 1):
            if not v[i]:       
                self.traversal(g="a", v=v, d=d, s=i, group1=group1, group2=group2)
            
        print(self.group1) ## This Prints [1] !!!
        print(self.group2) ## This Prints [2, 3, 4, 5] !!!
        return self.ans
    def traversal(self, g: str, v:[], d: {}, s: int, group1:[], group2:[]) -> None:
        if not self.ans:
            return
        v[s] = True
        g_or = g
        if g == "a":
            if s in group1:
                self.ans = False
            else:
                group1.append(s)
            g = "b"
        else:
            if s in group2:
                self.ans = False
            else:
                group2.append(s)
            g = "a"
        for hate in d[s]:
            if not v[hate]:
                self.traversal(g=g, v=v, d=d, s=hate, group1=group1, group2=group2)
            else:
                if g_or == "a":
                    if hate in group1:
                        self.ans = False
                else:
                    if hate in group2:
                        self.ans = False
                
                
```
#### Language used for code
Python3

#### Expected behavior

The print-outs from the second code snippet above is expected,
so the value of list group1 should be [1], and the value of list group2 should be [2,3,4,5]

(interesting parts are marked with !!!)

**Comment by nskybytskyi** [comment]
First of all, `self.list_name` is not a _global_ variable, but an _instance_ variable (a.k.a. attribute) instead. Secondly, `group1` and `group2` are neither global nor instance variables. Instead, they are _class_ variables. The most relevant difference is that class variables are shared between all instances of the `Solution` class, whereas instance variables are specific to each object. You can read more about it [here](https://stackoverflow.com/questions/2714573/instance-variables-vs-class-variables-in-python).

In particular, this implies that `group1` and `group2` are shared between different test cases. Hence, for the second and further test cases, they start pre-populated with the values from previous test cases. There is nothing wrong with the interpreter, such behavior is intended by design. If you wonder why such behavior can ever be useful - think about precomputing something, like factorials, or a prime numbers sieve. Both calculations can be performed once for all test cases, improving the overall running time.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. Please consider above comment as reference, if you need more help, please let us know.

**Comment by JiayangZhou** [comment]
Thank you, your answer is enlightening!
