### ISSUE TITLE
23. Merge k Sorted Lists - Runtime Error

### ISSUE THREAD

**Issue by agatagruza** [LeetCode-Feedback/LeetCode-Feedback#1050]
#### Your LeetCode username

gordonek

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Provided solution Approach 5: Merge with Divide And Conquer is giving a Runtime Error. According to the solution it should compile. 

#### Code you used for Submit/Run operation

```
class Solution(object):
    def mergeKLists(self, lists):
        """
        :type lists: List[ListNode]
        :rtype: ListNode
        """
        amount = len(lists)
        interval = 1
        while interval < amount:
            for i in range(0, amount - interval, interval * 2):
                lists[i] = self.merge2Lists(lists[i], lists[i + interval])
            interval *= 2
        return lists[0] if amount > 0 else lists

    def merge2Lists(self, l1, l2):
        head = point = ListNode(0)
        while l1 and l2:
            if l1.val <= l2.val:
                point.next = l1
                l1 = l1.next
            else:
                point.next = l2
                l2 = l1
                l1 = point.next.next
            point = point.next
        if not l1:
            point.next=l2
        else:
            point.next=l1
        return head.next
```

#### Language used for code

Python3

#### Expected behavior

Change the solution so that it compiles and doesn't give a Runtime Error. 

#### Screenshots

![RunTimeError](https://user-images.githubusercontent.com/7014697/93849400-e824b080-fc60-11ea-80c2-0f6bd769a48a.PNG)

**Comment by lc-ivan** [comment]
Hi @agatagruza ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @agatagruza 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
