### ISSUE TITLE
SQL Data Structure | Column explore card

### ISSUE THREAD

**Issue by AlapMistry** [LeetCode-Feedback/LeetCode-Feedback#10504]
#### Your LeetCode username
AlapMistry

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases

#### Description of the bug
``ALTER TABLE `new_schema`.`users`
ADD COLUMN `age` INT NULL AFTER `user_name`;``
`user_name` should be `name` if we follow sequence in that explore card. Please refer to the given below screenshots.

#### Screenshots
Bug:
![Leetcode1](https://user-images.githubusercontent.com/24839221/209369246-fcb34b3c-d309-4c19-9f80-22c2aebf6b48.png)
Solution:
![Leetcode2](https://user-images.githubusercontent.com/24839221/209369363-26db71b4-6311-4303-bad2-29a464c154c5.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem page.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by AlapMistry** [comment]
Hi @LC-Pam,
The problem page is [SQL Data Structure | Column explore card](https://leetcode.com/explore/learn/card/sql-language/682/sql-data-structure/4335/)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!

**Comment by AlapMistry** [comment]
Hi @LC-Pam,
Am I eligible for 100 LeetCode points? As it is mentioned in LeetCode store.
