### ISSUE TITLE
Erroneous Test Case for LC1366

### ISSUE THREAD

**Issue by jinyangdeng** [LeetCode-Feedback/LeetCode-Feedback#10501]
#### Your LeetCode username

jinyang_deng

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Wrong Test Cases

#### Description of the bug

For test case no. 36, where input is ["WXYA","XYZA","YAWX"]. The correct output should be "YXWAZ", but LC is asking for "YXWA".

#### Code you used for Submit/Run operation

```
class Solution:
    def rankTeams(self, votes: List[str]) -> str:
        helper = [[0 for i in range(26)] for i in range(26)]
        for i in range(26):
            helper[i].append(chr(i + ord('A')))
            helper[i].append(False)
        
        for vote in votes:
            for idx, char in enumerate(vote):
                helper[ord(char) - ord('A')][idx] -= 1
                helper[ord(char) - ord('A')][-1] = True
        
        helper.sort()
        
        res = ''
        for h in helper:
            if h[-1] == True:
                res += h[-2]
        
        return res
```

#### Language used for code

Python3

#### Expected behavior

Players' ranking can be tabulated as following:
Player | 1st Pos | 2nd Pos | 3rd Pos | 4th Pos
    Y    |     1       |      1       |      1      |      0
    X    |     1       |      1       |      0      |      1
    W   |     1       |       0      |      1      |      0 
    A    |     0       |      1       |      0      |      2
    Z    |     0       |       0      |       1     |      0
Therefore, the correct expected result should be "YXWAZ".

**Comment by nskybytskyi** [comment]
This test case is actually invalid, as it violates the following constraint:
> All the characters that occur in `votes[0]` also occur in `votes[j]` where `1 <= j < votes.length`

In the suggested testcase, `'W'` occurs in `votes[0]`, but not in `votes[1]`. I agree that we should remove it.

This issue was previously raised in #10231 but it somehow got closed. @LC-Pam please take a look at this

**Comment by nskybytskyi** [comment]
By the way, the checker must be updated too, to prevent more invalid test cases from appearing in the future.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
