### ISSUE TITLE
Missing Test Case - 217. Contains Duplicate

### ISSUE THREAD

**Issue by bigsbug** [LeetCode-Feedback/LeetCode-Feedback#10506]
#### Your LeetCode username
novaman

#### Category of the bug
- [ ] Question
- [ +] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
my code works very well on my machine with provided test case but when I run this on the site it gave me a wrong answer with the same test case 

#### Code you used for Submit/Run operation
```
from typing import List

class Solution:
    table = {}
    def containsDuplicate(self, nums: List[int]) -> bool:
        for item in nums:
            if self.table.get(item):
                return True
            self.table[item] = self.table.get(item,0) + 1
        return False

```

#### Language used for code

- Python 3
- Python 2

#### Expected behavior
with the test case 
```nums = [1,2,3,4]```
I excepted give me ```False``` 
but on the site it gives me the ```True``` that incorrect

**Comment by nskybytskyi** [comment]
Class variable `table` is shared between different instances of a `Solution` class, and hence between different test cases.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
