### ISSUE TITLE
Solution is not working

### ISSUE THREAD

**Issue by niru812** [LeetCode-Feedback/LeetCode-Feedback#10500]
#### Your LeetCode username

niru812

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Question : Flood Fill
I tried to run the following python solution, however it is showing Time limit exceeded, whereas i am able to run the same code in another compiler without reaching infinite loops. So i tried printing the queue after each iteration in while loop. A weird thing  i noticed is that , even though the queue becomes empty and the condition should turn false, a new value (0,0) is added automatically to queue, and causing infinite loop. 

#### Code you used for Submit/Run operation

```
class Solution:
    def floodFill(self, image: List[List[int]], sr: int, sc: int, color: int) -> List[List[int]]:
        queue = [(sr,sc)]
        color_to_change = image[sr][sc]

        while len(queue) > 0:
            row,col = queue.pop(0)
            image[row][col] = color
            for row_change,col_change in [(0,-1),(0,1),(1,0),(-1,0)]:
                new_row,new_col = row + row_change,col + col_change
                if -1 < new_row < len(image) and -1 < new_col < len(image[0]) and image[new_row][new_col] == color_to_change:
                    image[new_row][new_col] = color
                    queue.append((new_row,new_col))
        return image
```

#### Expected behavior

Infinite loop shouldn't happen, since the queue is becoming empty at a particular point and the condition for while loop is 'if queue not empty'.

#### Screenshots

output of code -
![image](https://user-images.githubusercontent.com/91334055/209351939-560a5242-fe40-4a38-adb9-d9b7ac2f704c.png)
debugging code with printing to console -
![image](https://user-images.githubusercontent.com/91334055/209352633-0b76faef-83ad-4637-91a3-014633b9be03.png)
output of same code (with same test case) in vscode - 
![image](https://user-images.githubusercontent.com/91334055/209352786-8d6497d2-07bc-4812-9637-fb580e6ac356.png)

#### Additional context

I encountered a similar bug when i tried the recursive approach for the same question

**Comment by nskybytskyi** [comment]
It is not obvious in the new design, but the TLE is caused by the second test case: `image = [[0,0,0],[0,0,0]]`, `sr = 0`, `sc = 0`, `color = 0`, not the first one. Try running your solution locally on the second test case to debug it.

**Comment by niru812** [comment]
Oh fine, so now i understand that the TLE can be solved by using another visited queue. However the first testcase should work fine right (It did when i compiled locally). When i tried to debug it in leetcode, weirdly the function is not returning 'image' even though return statement is encountered. I am attaching the screenshot - 
![image](https://user-images.githubusercontent.com/91334055/209388807-f4c162c9-1b63-4fb6-984e-81e93c85441c.png)

**Comment by nskybytskyi** [comment]
What you see is the combined output of both test cases. Once again, the first test case works fine and returns just after the first `#` is printed. However, the second test case gets stuck in an infinite loop. You can see that there is no second `#` in the output.

**Comment by niru812** [comment]
Ok got it, my bad. Thanks :)

**Comment by nskybytskyi** [comment]
Glad we've figured it out. I would like to share my solution as a hopefully helpful reference:
```py
class Solution:
    def floodFill(self, image: list[list[int]],
                  sr: int, sc: int, color: int) -> list[list[int]]:
        rows, cols = len(image), len(image[0])
        bfs = collections.deque([(sr, sc)])
        seen = {(sr, sc)}

        while bfs:
            row, col = bfs.popleft()

            for new_row, new_col in ((row - 1, col), (row, col - 1),
                                     (row, col + 1), (row + 1, col)):
                if (0 <= new_row < rows and 0 <= new_col < cols and 
                    image[new_row][new_col] == image[row][col] and
                    (new_row, new_col) not in seen):
                    seen.add((new_row, new_col))
                    bfs.append((new_row, new_col))

            image[row][col] = color

        return image
```

**Comment by niru812** [comment]
Great! Thanks for the solution .

**Comment by niru812** [comment]
Great ! Thanks for the solution.
