### ISSUE TITLE
Missing Test Case - 886. Possible Bipartition

### ISSUE THREAD

**Issue by RohitSgh** [LeetCode-Feedback/LeetCode-Feedback#10507]
#### Your LeetCode username

RohitSgh

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Code is incorrect however it gets [submitted](https://leetcode.com/problems/possible-bipartition/submissions/864387176/). It should fail on one test case. The submission is [attached](https://leetcode.com/problems/possible-bipartition/submissions/864387176/)

#### Code you used for Submit/Run operation

```python
class Solution:
    def possibleBipartition(self, n: int, dislikes: List[List[int]]) -> bool:
        
        # Adjacency List
        adjList = defaultdict(list)
        for a, b in dislikes:
            adjList[a-1].append(b-1)
            adjList[b-1].append(a-1)

        # DFS
        def DFS(node):
            for dislike in adjList[node]:
                if color[dislike] == -1:
                    color[dislike] = 1-color[node]
                    DFS(dislike)
                elif color[dislike] == color[node]:
                    return False
            return True

        # Color Every Component
        color = [-1]*n

        for node in range(n):
            if color[node] == -1:
                color[node] = 0
                if not DFS(node):
                    return False
        
        return True
```

#### Language used for code

Python3

#### Expected behavior

For Test Case

n
`10`

dislikes
`[[1, 3], [1, 4], [1, 6], [1, 7], [1, 8], [1, 9], [1, 10], [2, 3], [2, 4], [2, 5], [2, 6], [2, 7], [2, 8], [2, 9], [2, 10], [3, 4], [3, 5], [3, 6], [3, 7], [3, 8], [3, 9], [3, 10], [4, 5], [4, 6], [4, 7], [4, 8], [4, 9], [4, 10], [5, 7], [5, 10], [6, 8], [6, 9], [6, 10], [7, 8], [7, 9], [7, 10], [8, 9], [8, 10]]`

Expected Answer is `false`. However, the code returns `true`. It still gets submitted because this Test Case is missing.

#### Screenshots

![Screenshot of Wrong Output](https://user-images.githubusercontent.com/81853910/209403068-baa1dd22-d51b-43b9-a784-8b0f562a39d1.png)

**Comment by Rajatsinha05** [comment]
check your code again

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
