### ISSUE TITLE
189. Rotate Array

### ISSUE THREAD

**Issue by amangarg4804** [LeetCode-Feedback/LeetCode-Feedback#10517]
#### Your LeetCode username
amangarg4804

#### Category of the bug
- [ ] Solution

#### Description of the bug
I reached this question through Array and String explore card. The solution section contains wrong method name and parameters. The question is about rotating the array but the solution section contains method name findMin and method parameters don't contain integer k to specify no of rotations. Please check attached screenshot of what is being currently displayed in solution section for this problem.

#### Screenshots
![Screenshot 2022-12-24 at 5 23 13 PM](https://user-images.githubusercontent.com/5087068/209435006-7c8b102d-2db7-4b2f-8ac3-f36baecbaf8c.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time.  It can be fixed by using the refresh button above the text editor.  We appreciate your support!
