### ISSUE TITLE
Solution - 496. Next Greater Element I

### ISSUE THREAD

**Issue by RohitSgh** [LeetCode-Feedback/LeetCode-Feedback#10510]
#### Your LeetCode username

RohitSgh

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The animation given in **_Approach 3: Using Stack_** of [Official Solution](https://leetcode.com/problems/next-greater-element-i/solutions/127611/greater-element-i/) has error.

As per [problem constraint](https://leetcode.com/problems/next-greater-element-i/description/),    
> All integers in `nums1` and `nums2` are **unique**.

However, in animation, element **3** appears twice. This can be corrected. Also, map cannot have duplicate key. This fact is ignored by animation.

#### Code you used for Submit/Run operation

3 in [Official Solution](https://leetcode.com/problems/next-greater-element-i/solutions/127611/greater-element-i/) Animation of **_Approach 3: Using Stack_** should appear once.

#### Screenshots

![Mistake in Animation](https://user-images.githubusercontent.com/81853910/209409869-1ae0cdd7-4503-45d5-ab6b-c75baf954b90.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
