### ISSUE TITLE
Missing Test Case - 886. Possible Bipartition

### ISSUE THREAD

**Issue by mkryuk** [LeetCode-Feedback/LeetCode-Feedback#10511]
#### Your LeetCode username

mkryuk

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Looks like test cases don't cover the situation when a collision happens not in the end but in the middle of the dislikes array

#### Code you used for Submit/Run operation

```
// Possible Bipartition
function possibleBipartition(n: number, dislikes: number[][]): boolean {
  const relations = new Map<number, number[]>();
  dislikes.forEach(([left, right]) => {
    if (!relations.get(left)) {
      relations.set(left, [right]);
    } else {
      relations.get(left)!.push(right);
    }
    if (!relations.get(right)) {
      relations.set(right, [left]);
    } else {
      relations.get(right)!.push(left);
    }
  });
  const groups = new Array(n + 1).fill(-1);
  // instead of checking every node we can check only last to pass all tests
  // for (let i = 1; i <= n; i++) {
    // if we didn't check this person check his relations
    if (!bfs(n, groups, relations)) {
      return false;
    }
  //}
  return true;
}

function bfs(
  person: number,
  groups: number[],
  relations: Map<number, number[]>,
): boolean {
  const stack = [person];
  groups[person] = 0;
  while (stack.length) {
    const origin = stack.pop()!;
    const neighbors = relations.get(origin) ?? [];
    for (let i = 0; i < neighbors.length; i++) {
      if (groups[origin] === groups[neighbors[i]]) {
        return false;
      }
      if (groups[neighbors[i]] === -1) {
        groups[neighbors[i]] = 1 - groups[origin];
        stack.push(neighbors[i]);
      }
    }
  }
  return true;
}
```

#### Language used for code

Typescript

#### Expected behavior

The solution should not be accepted

#### Additional context

Missed Test case:

```
it("possibleBipartition should return false for n = 8, dislikes = [[1,2],[3,4],[3,5],[4,5],[7,8]]", () => {
  const n = 8;
  const dislikes = [
    [1, 2],
    [3, 4],
    [3, 5],
    [4, 5],
    [7, 8],
  ];
  const result = possibleBipartition(n, dislikes);
  expect(result).toBeFalse();
});
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!
