### ISSUE TITLE
Missing Constraints - 229. Majority Element II

### ISSUE THREAD

**Issue by Mohitkumar6122** [LeetCode-Feedback/LeetCode-Feedback#1051]
#### Your LeetCode username
**Mkay6122**

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
229. Majority Element II (https://leetcode.com/problems/majority-element-ii/)

Please add constraints to the above problem:

- Range of input size of array.
- Range of input elements of array.

#### Code you used for Submit/Run operation

```
// Majority Element

class Solution {
public:
    vector<int> majorityElement(vector<int>& nums) {
        int n = nums.size(), cnt1 = 0, cnt2 = 0, first = INT_MAX, second = INT_MAX;
        for(auto x : nums){
            if(x == first) cnt1++ ;
            else if (x == second) cnt2++ ;
            else if (!cnt1)  first = x, cnt1++ ;
            else if (!cnt2) second = x, cnt2++ ;
            else cnt1--, cnt2-- ;
        }
        cnt1 = cnt2 = 0 ;
        for(auto x : nums){
            if (x == first) cnt1++ ;
            else if (x == second) cnt2++ ;
        }
        vector <int> ans ;
        if (cnt1 > n / 3) ans.push_back(first) ;
        if (cnt2 > n / 3 and second != first) ans.push_back(second) ;
        return ans ;
    }
};
```

#### Language used for code
 C++

**Comment by lc-kay** [comment]
Hi @Mohitkumar6122 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Mohitkumar6122 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
