### ISSUE TITLE
Missing Test Case - 704. Binary Search

### ISSUE THREAD

**Issue by 12346877897790** [LeetCode-Feedback/LeetCode-Feedback#10515]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what ac

**Comment by 12346877897790** [comment]
Given an array of integers nums which is sorted in ascending order, and an integer target, write a function to search target in nums. If target exists, then return its index. Otherwise, return -1.

You must write an algorithm with O(log n) runtime complexity.

**Comment by nskybytskyi** [comment]
What code did you use for submit/run operation and what is the missing test case?
