### ISSUE TITLE
 Missing Testcases - 2478. Number of Beautiful Partitions

### ISSUE THREAD

**Issue by Sajan-Vishwakarma** [LeetCode-Feedback/LeetCode-Feedback#10514]
#### Your LeetCode username

HeadBanger

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [+] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// 2478. Number of Beautiful Partitions
class Solution:
    def beautifulPartitions(self, s: str, k: int, minLength: int) -> int:
        M = 10 ** 9 + 7
        n = len(s)
        primes = "2357"
        isPrime = False
        isComp = False
        for c in s:
            if c in primes:
                isPrime = True
            else:
                isComp = True
        if not isPrime or not isComp:
            return 0
        dp = [[0] * (k + 1) for _ in range(n + 1)]
        dp[n][0] = 1
        primesum = [[0] for _ in range(k + 1)]
        primesum[0][0] = 1
        for i in range(n - 1, -1, -1):
            if s[i] in primes:
                for l in range(1, k + 1):
                    if minLength <= len(primesum[l - 1]):
                        dp[i][l] += primesum[l - 1][-minLength]
            for l in range(k + 1):
                val = 0
                if s[i] in primes and (i == 0 or s[i - 1] not in primes):
                    val = dp[i][l]
                primesum[l].append(primesum[l][-1] + val)
        return dp[0][k] % M
```

#### Language used for code

Python3

#### Expected behavior

The above code is getting Accepted but it should fail for the given test case.

"23542185133"
1
1

AC Solution Link:
https://leetcode.com/problems/number-of-beautiful-partitions/submissions/864569014/

#### Screenshots

![image](https://user-images.githubusercontent.com/67305384/209422770-0056710b-9d91-4bd0-b883-3d3a1cb129ed.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by Sajan-Vishwakarma** [comment]
Will I get LeetCoins if this testcase gets added?

**Comment by Sajan-Vishwakarma** [comment]
> Thank you for reaching out to us. I've relayed this issue to our team to investigate.

Will I get LeetCoins if this testcase gets added?

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
