### ISSUE TITLE
Hints are repeated.

### ISSUE THREAD

**Issue by AkashsRepositories** [LeetCode-Feedback/LeetCode-Feedback#10528]
#### Your LeetCode username

skyXsaitama

#### Category of the bug
- [ https://leetcode.com/problems/take-k-of-each-character-from-left-and-right/ ] Question
- [ en ] Language

#### Description of the bug

Hint 1 to hint 3 are repeated as -
hint1 == hint4
hint2 == hint5
hint3 == hint6

#### Expected behavior

Hint from 4 to 6 should not be there.

#### Screenshots

![bug screenshot](https://user-images.githubusercontent.com/95037464/209459295-f8622dff-3fce-491b-aa69-33c9f4f90817.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!

**Comment by AkashsRepositories** [comment]
> Thank you for your time. We've used your feedback to update the problem. We appreciate your support!

You're welcome!
