### ISSUE TITLE
Last Modified Not Visible In Solution Threads In The New Editor UI

### ISSUE THREAD

**Issue by ThomasShaw1** [LeetCode-Feedback/LeetCode-Feedback#10522]
You can no longer view when a post or comment was last modified in the solution section for the new editor UI. This feature is really helpful to get a historical context of the problem and solution to help debug among other things.

Example: https://leetcode.com/problems/domino-and-tromino-tiling/solutions/116506/python-recursive-dp-solution-with-cache-w-explanation/

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!

**Comment by LC-Pam** [comment]
https://project.feishu.cn/leetcode/us_tickets/create?parentUrl=%2Fleetcode%2FworkObjectView%2Fus_tickets%2FvHtNOOSVR
