### ISSUE TITLE
Missing Test Case - 2512. Reward Top K Students

### ISSUE THREAD

**Issue by somelearner2** [LeetCode-Feedback/LeetCode-Feedback#10525]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

[2512 - Reward Top K Students](https://leetcode.com/problems/reward-top-k-students/)
My wrong code can pass all test cases.
However my code is accepted.

#### Code you used for Submit/Run operation

```
class Solution:
    def topStudents(self, positive_feedback: List[str], negative_feedback: List[str], report: List[str], student_id: List[int], k: int) -> List[int]:
        dic = defaultdict(int)
        for s in positive_feedback:
            dic[s] += 3
        for s in negative_feedback:
            dic[s] -= 1
        score_dic = defaultdict(int)
        for stu, re in zip(student_id, report):
            score = 0
            for c in re.split():
                if c in dic:
                    score += dic[c]
            score_dic[stu] = score
        student_id.sort(key = lambda stu:(score_dic[stu], -stu), reverse = True)
        return student_id[:k]
```

#### Language used for code

python3

#### Expected behavior

testcase:
```
["studious","smart","brilliant","studious"]
["not"]
["this student is not studious","the student is smart"]
[1,2]
2
```
The 1st stu. has "not" and "studious" , thus he should be scored as 3 - 1 = 2.
The 2nd stu. has "smart", thus he should be scored as 3.
However, "studious" appears in positive_feedback twice. This code appies "+=3" twice, which leads to "studious" rated as 6, and the 1st stu. rated as 5.

#### Screenshots

![image](https://user-images.githubusercontent.com/116818942/209456338-6a75c5db-43f6-4cee-b04c-6064d3f5adb6.png)

#### Additional context

This test case inputs should be added.
```
["studious","smart","brilliant","studious"]
["not"]
["this student is not studious","the student is smart"]
[1,2]
2
```

**Comment by Yawn-Sean** [comment]
If we use the original description in English, it is a test case worth adding.
But in the Chinese version, the description is actually "positive_feedback 和 negative_feedback 中不会有相同单词。", which means there are no same words in positive_feedback or negative_feedback, which makes the description confusing. So I don't think the testcase should be added to rejudge the results, as it would be unfair.

**Comment by nskybytskyi** [comment]
I also think that a problem will be better with an additional constraint rather than an additional test case.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

Please provide us your LC username.

**Comment by Yawn-Sean** [comment]
Come on, you never read what i write, do you?

**Comment by LC-Pam** [comment]
We have added the test case that you request. If you have any issues or requests, we can resubmit. Please let us know. 

Additional context
This test case inputs should be added.

["studious","smart","brilliant","studious"]
["not"]
["this student is not studious","the student is smart"]
[1,2]
2

**Comment by LC-Pam** [comment]
> Come on, you never read what i write, do you?

They ticket submitted by [somelearner2](https://github.com/somelearner2). 
We have added the test case due to the ticket.
We also submit your comment to the team since you left your comment/suggestion/request under this ticket and we will update with you separately when our team have results. we respect every user and the decision will be made by the contest team instead of customer support. 
The pervious reply is for the somelearner2. 
If you have any issues or requests, you can always let us know. 
We appreciate your support!

**Comment by Yawn-Sean** [comment]
> > Come on, you never read what i write, do you?
> 
> The ticket submitted by [somelearner2](https://github.com/somelearner2). We have added the test case due to the ticket. We also submit your comment to the team since you left your comment/suggestion/request under this ticket and we will update with you separately when our team have results. we respect every user and the decision will be made by the contest team instead of customer support. The pervious reply is for the somelearner2. If you have any issues or requests, you can always let us know. We appreciate your support!

Thanks for your reply, as the description in Chinese would be really misleading if you add this test case. Wish you would give it more thought. Adding this test case and rejudging the results would be unfair.

**Comment by Yawn-Sean** [comment]
And as far as i can see here, there are similar test cases added too. If you decide to remove this test case, maybe you should also remove those similar ones.

**Comment by LC-Pam** [comment]
> > > Come on, you never read what i write, do you?
> > 
> > 
> > The ticket submitted by [somelearner2](https://github.com/somelearner2). We have added the test case due to the ticket. We also submit your comment to the team since you left your comment/suggestion/request under this ticket and we will update with you separately when our team have results. we respect every user and the decision will be made by the contest team instead of customer support. The pervious reply is for the somelearner2. If you have any issues or requests, you can always let us know. We appreciate your support!
> 
> Thanks for your reply, as the description in Chinese would be really misleading if you add this test case. Wish you would give it more thought. Adding this test case and rejudging the results would be unfair.

Your feedback already submitted to the team. We will provide updates with you as soon as possible.

**Comment by LC-Pam** [comment]
> And as far as i can see here, there are similar test cases added too. If you decide to remove this test case, maybe you should also remove those similar ones.

Thank you for your time. We've used your feedback removed such test cases, but since LCUS did not have an issue with description, we will add those cases after the rejudge. We appreciate your support!

**Comment by Yawn-Sean** [comment]
> > And as far as i can see here, there are similar test cases added too. If you decide to remove this test case, maybe you should also remove those similar ones.
> 
> Thank you for your time. We've used your feedback removed such test cases, but since LCUS did not have an issue with description, we will add those cases after the rejudge. We appreciate your support!

Thanks for your reasonable consideration.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
