### ISSUE TITLE
Missing Test Case - 886. Possible Bipartition

### ISSUE THREAD

**Issue by jakariya-bd** [LeetCode-Feedback/LeetCode-Feedback#10520]
#### Your LeetCode username

jakariyabd

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- Missing Test Cases 

#### Description of the bug

The judge lacks a type of corner cases.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    #define MX 2001
    short int group[MX];
    vector< set<int> > g;

    bool flag;
    void iter(int i, bool state){ // true for A(1), false for B(2) Groups respectively
        if( flag || g[i].empty() ) return;
        if( group[i] ){
            if( group[i] == 2 && state ){
                flag = false;
            }
            else if( group[i] == 1 && !state ){
                flag = true;
            }
            return;
        }
        group[i] = state ? 1 : 2;
        for( auto x : g[i] ){
            iter(x, !state);
        }
    }

    bool possibleBipartition(int n, vector<vector<int>>& dislikes) {
        
        g.resize(n+1);

        for( auto i : dislikes ){
            g[ i[0] ].insert( i[1] );
            g[ i[1] ].insert( i[0] );
        }
        for(int i=1; i <= n && !flag; ++i){
            if( !group[i] ){
                iter(i, true);
            }
        }

        return !flag;
    }
};
```

#### Language used for code
C++

#### Expected behavior

For the test case below,
```
n = 4
[ [1,2], [2,3], [3,4], [2,4] ]
```
The judge's program returns false, and my program returns true. And judge is right here.
Yet, when I submitted my code, it's got accepted. But judge should verdict wrong answer.
So, I suggest adding this type of test cases.

#### Additional context

Note: This is my earlier submission, but my later submission produces correct outputs for these corner cases, too.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. This solution now fails. We added test cases previously. We appreciate your support!
