### ISSUE TITLE
Missing Test Case - 1299. Replace Elements with Greatest Element on Right Side

### ISSUE THREAD

**Issue by hyunsik-yoon** [LeetCode-Feedback/LeetCode-Feedback#10524]
#### Your LeetCode username
labsurde

#### Category of the bug
- [v] Question (?)

#### Description of the bug

I found this when I try `Array 101` in [`Explorer Card Tract`](https://leetcode.com/explore/learn/card/the-leetcode-beginners-guide/679/sql-syntax/4358/).

<img width="920" alt="image" src="https://user-images.githubusercontent.com/63768207/209453746-ae0e44c4-9e46-4060-9f8b-37d8bd072dec.png">

Note athat this is an example of _in-place operation_.

Regarding _in-place operation_, https://leetcode.com/explore/learn/card/fun-with-arrays/511/in-place-operations/3257/ mentiones like the following:
```
 we won't need that extra space. It is this technique of working directly in the input Array, 
and not creating a new Array, that we call in-place. 
```

When a template in C++ is given, the method signature is as follows:

```cpp
    vector<int> replaceElements(vector<int>& arr)
```

which mean that the the compiler will generate code to copy vector `arr` again to create the return value.

Since this question is for in-place solution, how about change the above the one of the following?

```cpp
    void replaceElements(vector<int>& arr) // returning void
```

or 

```cpp
    vector<int> &replaceElements(vector<int>& arr) // returning reference of arr
```

FYI, I found that https://leetcode.com/explore/learn/card/fun-with-arrays/511/in-place-operations/3157/ uses return as `void` to implement in-place operation.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. This can't be changed because the LC problem isn't necessarily meant to be solved in place, it's just a "bonus" that is suggested by the explore card. We can't change the definition of the LC problem for this. We appreciate your support!
