### ISSUE TITLE
Wrong Test Case - 951. Flip Equivalent Binary Trees

### ISSUE THREAD

**Issue by shashank1995** [LeetCode-Feedback/LeetCode-Feedback#1052]
#### Your LeetCode username

shashank_adityasingh

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The given problem constraints state that each tree will have unique node values from [0,99]. 
But there is a test case with duplicate node values when we submit for final submission:
[1,3,3,4,5,6,null,null,null,7,8]
[1,3,3,null,6,4,5,null,null,null,null,8,7]
The given trees have 2 nodes with value "3" which doesn't satisfy the problem constraints. Either update the constraint or remove the given test case.  

#### Code you used for Submit/Run operation

```
// Flip Equivalent Binary Trees
class Solution {
public:
    bool isSame(TreeNode* root1,TreeNode* root2){
        if(root1==NULL && root2==NULL)
            return true;
        else if(root1!=NULL && root2==NULL)
            return false;
        else if(root2!=NULL && root1==NULL)
            return false;
        if(root1->val==root2->val)
            return true;
        return false;
    }
    
    bool checkNode(TreeNode* root1,TreeNode* root2){
        if(root1==NULL && root2==NULL)
            return true;
        else if(root1!=NULL && root2==NULL)
            return false;
        else if(root2!=NULL && root1==NULL)
            return false;
        if(isSame(root1,root2)){
            if(isSame(root1->left,root2->left) && isSame(root1->right,root2->right)){
                return checkNode(root1->left,root2->left) && checkNode(root1->right,root2->right);
            }
            else if(isSame(root1->left,root2->right) && isSame(root1->right,root2->left)){
                return checkNode(root1->left,root2->right) && checkNode(root1->right,root2->left);
            }
        }
        return false;
    }
    
    bool flipEquiv(TreeNode* root1, TreeNode* root2) {
        return checkNode(root1,root2);
    }
};
```

#### Language used for code

C++

#### Expected behavior

With a correct test case, I expected to pass my solution. I have 76/77 test cases passed. 

#### Screenshots

<img width="451" alt="Screen Shot 2020-09-22 at 2 26 14 AM" src="https://user-images.githubusercontent.com/15519873/93863593-840de680-fc78-11ea-9e4f-bf65513029f4.png">
<img width="1152" alt="Screen Shot 2020-09-22 at 2 25 05 AM" src="https://user-images.githubusercontent.com/15519873/93863467-60e33700-fc78-11ea-8677-7811c544b530.png">

**Comment by lc-kay** [comment]
Hi @shashank1995 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @shashank1995 
Thank you for your time. We've fixed the bug in the validator. We appreciate your support!
