### ISSUE TITLE
Solution - 2389. Longest Subsequence With Limited Sum

### ISSUE THREAD

**Issue by RohitSgh** [LeetCode-Feedback/LeetCode-Feedback#10529]
#### Your LeetCode username

RohitSgh

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Typing Mistake in Space Complexity of "**Approach 2: Prefix Sum + Binary Search**" of [Official Solution](https://leetcode.com/problems/longest-subsequence-with-limited-sum/solutions/2644327)

**Incorrect**    
> Similarly, some extra space is used when we sort `presum` in place. 

**Correct**    
> Similarly, some extra space is used when we sort `nums` in place. 

Moreover, it would be better if solution mentions that we are computing `presum` in place by modifying `nums`

#### Expected behavior

Space Complexity of "**Approach 2: Prefix Sum + Binary Search**" of [Official Solution](https://leetcode.com/problems/longest-subsequence-with-limited-sum/solutions/2644327)

**Incorrect**    
> Similarly, some extra space is used when we sort `presum` in place. 

**Correct**    
> Similarly, some extra space is used when we sort `nums` in place. 

Moreover, it would be better if solution mentions that we are computing `presum` in place by modifying `nums`

#### Screenshots

![image](https://user-images.githubusercontent.com/81853910/209459582-af01812a-81e4-40b2-9e82-40c7ac43f214.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
