### ISSUE TITLE
Incorrect Solution or Missing Constraint - 626. Exchange Seats

### ISSUE THREAD

**Issue by axelu** [LeetCode-Feedback/LeetCode-Feedback#10539]
#### Your LeetCode username
axelu

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The solution assumes that the id is a continuous increment starting at 1 respectively at a positive odd number.
The description doesn't state that, so test cases like the following are within the constraints:
example A: ```{"headers": {"Seat": ["id","student"]}, "rows": {"Seat": [[2,"Abbot"],[3,"Doris"],[4,"Emerson"],[5,"Green"],[6,"Jeames"]]}}```
example B: ```{"headers": {"Seat": ["id","student"]}, "rows": {"Seat": [[-1,"Abbot"],[0,"Doris"],[1,"Emerson"],[2,"Green"],[3,"Jeames"]]}}```
example C: ```{"headers": {"Seat": ["id","student"]}, "rows": {"Seat": [[4,"Abbot"],[5,"Doris"],[6,"Emerson"],[7,"Green"],[8,"Jeames"]]}}```  
Assuming my understanding of the problem is correct, the reference solution does not return the correct result, see details below.

#### Code you used for Submit/Run operation

```
/* Write your T-SQL query statement below */

select
  t.id,
  case when t.next_student is null and row_number() over(ORDER BY id) % 2 = 1 then student
       when row_number() over(ORDER BY id) % 2 = 1 then t.next_student else t.previous_student
  end as student
from (
select
  row_number() over(ORDER BY id) as row_nbr,
  id,
  student,
  LAG(student,1) OVER (ORDER BY id) AS previous_student,
  LEAD(student,1) OVER (ORDER BY id) AS next_student
from
  seat
) t  
order by
  id
```

#### Language used for code
T-SQL

#### Expected behavior

one option would be to update the problem description to state: ```"... id is a continuous increment starting at 1 ..."```  
or otherwise, the solution should retain the continuous segment of id's and swap seats according to the problem description including retain the seat of the last student if the length of the continuous segment aka the number of students is odd

#### Screenshots

screenshot for example A 
![image](https://user-images.githubusercontent.com/1248912/209477492-53bf75f8-6c19-4f42-9587-67296ea13b0b.png)

screenshot for example B 
![image](https://user-images.githubusercontent.com/1248912/209477169-95a50d25-6e88-46bd-892b-65cf3472d023.png)

screenshot for example C 
![image](https://user-images.githubusercontent.com/1248912/209477790-9c31d213-17f4-4c0e-912c-bf4a291a01bb.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The statement mentioned that ID is continuous increment. We appreciate your support!
