### ISSUE TITLE
Missing Constraints - 633. Sum of Square Numbers

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1053]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Constraints are missing:

- What is the range of the integers? Is it a 32-bit integer? Is it like below?

    1 <= c <= 2147483647

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

The question must have constraints
Otherwise, users will have TLE errors (https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/812)

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
