### ISSUE TITLE
1219. Path with Maximum Gold

### ISSUE THREAD

**Issue by Smit-mandavia** [LeetCode-Feedback/LeetCode-Feedback#10548]
#### Your LeetCode username
l_returns

#### Category of the bug
-  Question
- Solution
- Difficulty

#### Description of the bug
`There are at most 25 cells containing gold.`
Let k = 25 in this case then. (k = num of cells containing gold)
The constraints are too much for the solution to pass. How can 3^k solution pass with k=25? As it can take 8472*10^8 computations, meaning order of 8472 seconds to get computed. 
Please either share a solution which is less than 3^k or prove that brute force solution will always take less than 10^8 computation. 

#### Expected behavior
Constraints should be less so that it can be proved that it will pass in 1 second of runtime. 
Please share a proof if n,m<=15 and k=25 will always take less than 10^8 computations. (Even if the proof exist I don't think its easy to prove and hence we can't call it medium problem when k=25. Please make it a hard problem in that case as users won't be able to prove why brute force solution will work)
If expected solution is O(3^k) only please make k=17 instead which would make solution O(3^17) ~= O(10^8) in worst case.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We decided to keep the problem medium after checking the feedback of this problem. We appreciate your support!
