### ISSUE TITLE
Missing Constraints - 372. Super Pow

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1054]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

372. Super Pow
https://leetcode.com/problems/super-pow/

Please add constraints to the problem

- What is the range of a & b?
- What is extremely large for b? Is it like below?

    1 <= a <= 2147483647
    1 <= b <= 214748364721474836472147483647,    but given in the form of array, and each element of array is a digit of b

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

The question must have constraints so as to avoid TLE errors.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
