### ISSUE TITLE
Run Error

### ISSUE THREAD

**Issue by GHRohit** [LeetCode-Feedback/LeetCode-Feedback#10547]
#### Your LeetCode username
newChallenge

#### Category of the bug
- [ ] Execution

#### Description of the bug
The solution for the Nth highest problem in SQL is **_accepted when the submit button is clicked_**, but it causes a **_runtime error when the run button is clicked_**.

#### Code you used for Submit/Run operation

```
#Nth Highest salary
CREATE FUNCTION getNthHighestSalary(N INT) RETURNS INT
BEGIN
DECLARE M INT;
SET M=N-1;
  RETURN (
      # Write your MySQL query statement below.
      SELECT DISTINCT Salary FROM Employee ORDER BY Salary DESC LIMIT M, 1
  );
END
#This code is used from already submitted solution to checked the error
```

#### Language used for code
MySQL

#### Expected behavior
Run the code without any runtime error

**Comment by LC-Pam** [comment]
When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!
