### ISSUE TITLE
Missing Test Case - 26. Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by Shriansh2002** [LeetCode-Feedback/LeetCode-Feedback#10546]
#### Your LeetCode username
shriansh_agarwal

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Test case: nums = [1,1,2,2,3,4,5,5,5,6,7] can be added.

#### Code you used for Submit/Run operation

```
// Remove Duplicates from Sorted Array
class Solution {
public:
    int removeDuplicates(vector<int>& nums) {
        int indexV = 1;

        for(int i=1; i<nums.size(); i++){
            if(nums[i] != nums[i-1]){
                nums[indexV] = nums[i];
                indexV ++;
            }
        }
        return indexV;
    }
};
```

#### Language used for code
C++

#### Expected behavior
[1,2,3,4,5,6,7]

**Comment by LC-Pam** [comment]
Thank you for your time. 
Test case already existed.
We appreciate your support!
![Screen Shot 2022-12-26 at 2 18 55 PM](https://user-images.githubusercontent.com/103138242/209577936-234db55f-a129-48ff-a4cd-b66fbef67087.png)
