### ISSUE TITLE
add link to a card in solution description

### ISSUE THREAD

**Issue by czlowieku** [LeetCode-Feedback/LeetCode-Feedback#10556]
in https://leetcode.com/problems/graph-valid-tree/solutions/539585/graph-valid-tree/
it says 
"Now, how should we implement this? Well, we could create a list of Sets and then carry out the algorithm as it was done in the animation. There is, however, a better way; a really clever algorithm we call union find. I'll give a brief introduction to the algorithm here, however, if you aren't familiar with it, I strongly recommend reading up on it out of a good algorithm textbook. We don't yet have an explore card on union find (at the time of writing this!). Union find is a very useful algorithm that can be used to solve many graph problems.

"

there is a quite good card you have made here, it should be linked there.
https://leetcode.com/explore/featured/card/graph/618/disjoint-set/3881/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've decided not make changes. We appreciate your support!
