### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by majdAlarbeed** [LeetCode-Feedback/LeetCode-Feedback#10550]
public class Solution {

    public int[] TwoSum(int[] nums, int target)
    {
        int j = 0;
            for (int i = 1; i < (nums.Length) ; i++)
            {

                if (nums[i-1] + nums[i] == target)
                {
                    Console.WriteLine($"[{i-1},{i}]");
                }
            }
            return nums;
    }
}

**Comment by majdAlarbeed** [comment]
need help as the result is correct but stigl the compiler showed wrong

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
