### ISSUE TITLE
Test Case Missing for problem 229. Majority Element II

### ISSUE THREAD

**Issue by AJAYKR00KJ** [LeetCode-Feedback/LeetCode-Feedback#1055]
#### Your LeetCode username

kr00_kj

#### Category of the bug
- [✓] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Test cases are missing. The code not to be supposed submitted but accepted by leetcode

#### Problem Link:
[https://leetcode.com/problems/majority-element-ii/](url)

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int majority(vector<int> &nums)
    {
        int ind=0,c=0;
        for(int i=0;i<nums.size();i++)
        {
            if(c==0) ind=i;
            if(nums[i]==nums[ind]) c++;
            else c--;
        }
        return nums[ind];
    }
     int maj(vector<int> &nums,int b)
     {
        int ind=0,c=0;
        for(int i=nums.size()-1;i>=0;i--)
        {   if(nums[i]==b) continue;
            if(c==0) ind=i;
            if(nums[i]==nums[ind]) c++;
            else c--;  
        }
        return nums[ind];
    }
    vector<int> majorityElement(vector<int>& nums) {
       int n=nums.size(),lim=n/3;
        if(n==0) return {};
        if(n==1) return nums;
        if(n==2)
        {
            if(nums[0]==nums[1]) return {nums[0]};
            else return nums;
        }
        int a=majority(nums);
        int b=maj(nums,a);
        int c1=0,c2=0;
        for(auto x:nums)
        {
            c1+=x==a?1:0;
            c2+=x==b?1:0;
        }
        vector<int> v;
        
        if(c1>n/3) v.push_back(a);
        if(c2>n/3) v.push_back(b);
        if(a==b) v.pop_back();
        return v;
        
    }
};
```

#### Language used for code
C++

#### Expected behavior

The Output of test case [11,7,1,8,5,7,12,7] should be [7] but my code is giving output [] , yet it is accepted by leetcode.

#### Screenshots

![ltcd](https://user-images.githubusercontent.com/48375037/93895549-925a1200-fd0d-11ea-905b-880d5af143f5.png)

#### Additional context

There are few test cases are missing, please add these.

**Comment by lc-ivan** [comment]
Hi @AJAYKR00KJ 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @AJAYKR00KJ 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
