### ISSUE TITLE
Typo: Explore - Leetcode Beginners Guide - Challenge Problems - Middle of Linked List

### ISSUE THREAD

**Issue by happyhappyyay** [LeetCode-Feedback/LeetCode-Feedback#10562]
#### Your LeetCode username

happyhappyyay

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

https://leetcode.com/explore/learn/card/the-leetcode-beginners-guide/692/challenge-problems/4426/

There is a reference to a video coming soon, but the video has already been added.

"If you are not familiar with the linked list data structure, do not worry, you can always skip this problem, but we encourage you to try to solve [876. Middle of The Linked List](https://leetcode.com/problems/middle-of-the-linked-list/) on your own, and if you feel stuck, check out the solution article for the problem or come back here to view the video solution **(coming soon)**."

"(coming soon)" should be removed.

#### Screenshots

![20221226213403](https://user-images.githubusercontent.com/33879530/209607196-7fa6f6b6-d7ed-46f9-9203-37299c1f2c25.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
