### ISSUE TITLE
Unclear description

### ISSUE THREAD

**Issue by binhtlthien** [LeetCode-Feedback/LeetCode-Feedback#10568]
#### Your LeetCode username
@binhtlt

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
74. Search a 2D Matrix
Maybe the description is not clear.  
"Integers in each row are sorted from left to right" => Each row number may be sorted in a decrease or increase order.
But I assume it's always an increased order and submit a solution. It accepted.

Ex: With the current description, the below test case is still valid:

[[1,3,5,7],[20,16,11,10],[23,30,34,60]]

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean searchMatrix(int[][] matrix, int target) {
        int m = matrix.length, n = matrix[0].length;

        for(int r = 0; r < m; r++){
            if(matrix[r][0] <= target){
                for(int c = 0; c < n; c++){
                    if (matrix[r][c] == target)
                        return true;
                }
            }
        }

        return false;
    }
}
```

#### Language used for code
Java

#### Expected behavior

Maybe the description needs to be updated to confirm the increased order in each row or add more test cases to catch this case.

#### Screenshots

<img width="1427" alt="image" src="https://user-images.githubusercontent.com/46182951/209655224-3a4b020a-13ad-4358-a4ec-8e627c239356.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
