### ISSUE TITLE
Grammatical mistakes in the Binary Tree explore card

### ISSUE THREAD

**Issue by AnuragThePathak** [LeetCode-Feedback/LeetCode-Feedback#10565]
#### Your LeetCode username

anurag-pathak

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the explore card of `binary tree`, there are two grammatical mistakes in the [traverse a tree - introduction](https://leetcode.com/explore/learn/card/data-structure-tree/134/traverse-a-tree/992/) section. Both are in the following line.
```
Also, post-order is widely use in mathematical expression.
```

The following two are the problematic words
- use
- expression

#### Expected behavior

The possible fixes can be:
- Change `use` to `used`.
- Change `expression` to `expressions`. 

#### Screenshots

<img width="875" alt="Screen Shot 2022-12-27 at 1 14 49 PM" src="https://user-images.githubusercontent.com/75429250/209630745-6ae918a1-77bf-4d4f-b550-651150233947.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
