### ISSUE TITLE
Request to convert Easy to Medium - 633. Sum of Square Numbers

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1056]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

633. Sum of Square Numbers
https://leetcode.com/problems/sum-of-square-numbers/

At https://leetcode.com/submissions/detail/380802021/
Below code exists, it got Time Limit Exceeded error
The TLE was reported in bug - https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/812

However the same Brute Force solution is given 
in the solution tab
 at https://leetcode.com/problems/sum-of-square-numbers/solution/

Looks like one of the below is the case:
1. JavaScript run time is too restricted, or it is same for all other programming languages on Submit as of today.
2. Recently more test cases are added after the solution was posted hence bruteforce wont pass now.

This is Not an Easy problem because of the following reasons:

1. At https://leetcode.com/problems/sum-of-square-numbers/solution/317118
173 upvotes for below comment  >> "If this is easy, i have no future in this industry"

2. This problem has Top 10 from the bottom/lowest in terms of the Acceptance Rate at "32.1%" in the Easy Category.

3. As filed in an earlier bug, this problem does not pass with brute force, due to large test cases it has.

I have solved the problem. I can confirm this is not an easy problem.

For the reasons above, please change the difficulty of this problem from Easy to Medium.

#### Code you used for Submit/Run operation

```
	var judgeSquareSum = function (c) {
		let sqrtC = Math.sqrt(c);

		for (let a = 0; a <= sqrtC; a++) {

			let aa = a * a;
			if (aa > c) break;

			for (let b = 0; b <= sqrtC; b++) {

				let bb = b * b;
				if (bb > c) break;

				if (aa + bb == c) return true;

				if (aa + bb > c) {
					break;
				}
			}
		}

		return false;
	};

```

#### Language used for code
JavaScript

#### Expected behavior

This problem has test cases that have a very high bar. An easy brute force solution for this problem gives a TLE.
Hence this problem as-is cannot be an Easy category problem. See above for more details.

**Comment by manoharreddyporeddy** [comment]
Related
https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/812

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
