### ISSUE TITLE
Wrong output of testcase.

### ISSUE THREAD

**Issue by AnkitKashyap0709** [LeetCode-Feedback/LeetCode-Feedback#10566]
#### LeetCode username

Ankkash

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The question "179. Largest Number" has a bug in it's visible testcase 2. In this we need to output the largest number possible
In that testcase, Input: nums=[3,30,34,5,9] and Output: "9534330" (for which my solution was giving the output: "9543330" and this was shown as "wrong answer".

#### Code you used for Submit/Run operation

```
class Solution:
    def largestNumber(self, nums: List[int]) -> str:
        nums=str(nums)
        res = sorted(nums, key = lambda x: (len (x), x))
        res=reversed(res)
        a=""
        for i in res:
            a+=i
        return(a.replace("[","").replace("]","").replace(",","").strip())
```

#### Language used for code
Python3

#### Expected behavior
As I analyzed the code, input and output manually, I realized that the number 9543330 is greater than 9534330.
Hence, the right output should be "9543330" instead of "9534330" for that particular testcase.

#### Screenshots
![Screenshot (331)](https://user-images.githubusercontent.com/63182579/209638264-cca1045b-e68b-414e-b465-2120b74ef414.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
