### ISSUE TITLE
55. Jump Game: Test Results vs. Judging Discrepancy (Python3)

### ISSUE THREAD

**Issue by PowersOfEight** [LeetCode-Feedback/LeetCode-Feedback#10561]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The test case passed when using the "Run" button but upon submission, the code fails the same input:

#### Code you used for Submit/Run operation

```
class Solution:
    def canJump(self, nums: List[int], idx=0, deadEnds={}) -> bool:
        if nums[idx] + idx + 1 >= len(nums) : return True
        if deadEnds.get(idx) != None : return deadEnds[idx]
        if nums[idx] <= 0 :
            deadEnds[idx] = False
            return deadEnds[idx]
        value = nums[idx]
        while value > 0 :
            if self.canJump(nums, value + idx, deadEnds): return True
            value -= 1
        return False
```

#### Language used for code

Python3

#### Expected behavior

If it passes the test case, it should pass the judge, and if it fails the judge it should fail the test case

#### Screenshots

The case that passed:
![image](https://user-images.githubusercontent.com/57668126/209576903-44c84aaa-462f-4a2e-a943-7f7173dae063.png)

The submission judge:
![image](https://user-images.githubusercontent.com/57668126/209576947-e538e7bf-2951-47df-99c0-7898f9b0a16d.png)

**Comment by nskybytskyi** [comment]
You should never ever use mutable default arguments, see [this post](https://stackoverflow.com/questions/1132941/least-astonishment-and-the-mutable-default-argument) for an explanation.

**Comment by PowersOfEight** [comment]
Thanks, I wasn't aware of that.
