### ISSUE TITLE
Missing Constraints - 204. Count Primes

### ISSUE THREAD

**Issue by yashtibrewal** [LeetCode-Feedback/LeetCode-Feedback#1057]
#### Your LeetCode username
yashtibrewal

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Question: 204. Count Primes
Question link : https://leetcode.com/problems/count-primes/
Question no: 204
Missing Boundary/Constraints for the input variable ```n```

#### Code you used for Submit/Run operation

N/A

#### Language used for code

TypeScript

#### Expected behavior

Expected type of question description:
0<n<2,147,483,647

#### Screenshots

N/A

#### Additional context

N/A

**Comment by lc-kay** [comment]
Hi @yashtibrewal 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @yashtibrewal 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
