### ISSUE TITLE
Missing Test Case - 11. Container With Most Water

### ISSUE THREAD

**Issue by Tasawwur-Mehnaz** [LeetCode-Feedback/LeetCode-Feedback#10573]
#### LeetCode username

t_Mz

#### Category of the bug: Missing Test Cases
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Here, my solution got accepted in leetcode but I found one testcase in which my code gave wrong output.
Hence add this new testcase to the question named "Container with most water".

#### Code you used for Submit/Run operation

TestCase which I have used to check

[85 ,41 ,23 ,29 ,29 ,65, 59 ,32 ,96 ,55 ,53 ,62, 84, 34 ,54, 72 ,57 ,69 ,32 ,63 ,7 ,83 ,11 ,35, 67,48 ,75 ,38 ,23 ,42 ,54 ,11 ,41 ,75 ,59 ,25 ,21 ,70 ,26 ,34 ,5 ,83 ,50 ,98 ,79,1]

```
// Container With Most Water
class Solution {
public:
    int maxArea(vector<int>& height) {
        int n=height.size();
        int h=min(height[0],height[n-1]);
        int area=h*(n-1);
        int i=1,j=n-1;
        int x=height[0],y=height[n-1];
        int l=0,r=n-1;
        while(i<j)
        { 
            if(height[i]>x)
            {
                x=height[i];
                 l=i;
            }
            if(height[j]>y)
            {
                y=height[j];
                 r=j;
            }
            
            int m=min(x,y);
            int a=m*(r-l);
            area=max(a,area);
            if(height[i]<height[j])
            i++;
            else
            j--;   
        }
        return area;
    }
};

```

#### Language used for code

C++

#### Expected behavior

The output should show the wrong answer when I submit my code but it got accepted.

**Comment by Tasawwur-Mehnaz** [comment]
Review this new testcase and add it to the question.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
