### ISSUE TITLE
1116. Print Zero Even Odd python3 issue

### ISSUE THREAD

**Issue by devalentino** [LeetCode-Feedback/LeetCode-Feedback#10570]
#### Your LeetCode username
devalentino

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
Classe's methods are executed in same thread. However description says all the methods are executed in separate threads:

> You are given an instance of the class ZeroEvenOdd that has three functions: zero, even, and odd. The same instance of ZeroEvenOdd will be passed to three different threads:
> * Thread A: calls zero() that should only output 0's.
> * Thread B: calls even() that should only output even numbers.
> * Thread C: calls odd() that should only output odd numbers.

#### Code you used for Submit/Run operation

```python
from threading import currentThread


class ZeroEvenOdd:
    def __init__(self, n):
        self.n = n
        print('init in %s' % currentThread().ident)

    def zero(self, printNumber: 'Callable[[int], None]') -> None:
        print(f'zero in %s' % currentThread().ident)

    def even(self, printNumber: 'Callable[[int], None]') -> None:
        print(f'even in %s' % currentThread().ident)

    def odd(self, printNumber: 'Callable[[int], None]') -> None:
        print(f'odd in %s' % currentThread().ident)

```

#### Language used for code
python3

#### Expected behavior
All the methods (`zero`, `even`, `odd`) are executed in different threads

#### Screenshots
![image](https://user-images.githubusercontent.com/939104/209680479-db9b3451-efd7-4bbb-961d-6b0458f51c16.png)

#### Additional context
I use free account. Maybe premium accounts has bigger thread pool for execution?

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We call the three functions in 3 different threads. We appreciate your support!

**Comment by devalentino** [comment]
> We call the three functions in 3 different threads.

From attached screenshot you can see all the functions are executed in same thread.
