### ISSUE TITLE
Incorrect test case 2103. Rings and Rods

### ISSUE THREAD

**Issue by debugskeleton** [LeetCode-Feedback/LeetCode-Feedback#10576]
The test case 31 “G3R3R7B7R5B1G8G4B3G6” is incorrectly, stating the expected output of 1 where it should be 4 while executing python.

![D6FE59BA-411B-4ABF-A308-ADFE77C68634](https://user-images.githubusercontent.com/29963007/209725287-12fac30f-5526-4cde-848e-a1889b46cb2f.jpeg)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by debugskeleton** [comment]
Is there a special way to be able to format the inputs like I see on the other issue submissions?

**Comment by LC-Pam** [comment]
You can send us your submission link since we need to test it. Thank you!

**Comment by debugskeleton** [comment]
https://leetcode.com/problems/rings-and-rods/submissions/866578411/

class Solution:
    def countPoints(self, rings: str) -> int:
        result = [0]*10

        for i in range(0, len(rings), 2):
            c,n = rings[i:i+2]

            shift = "RGB".index(c)
            pos = int(n)

            result[pos] |= (1 << shift)
            
            if result[pos] == 7:
                return pos+1
        else:
            return 0

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!

**Comment by debugskeleton** [comment]
I reviewed over the link you posted, but I do have a continued question. My understanding of the problems input, “ G3R3R7B7R5B1G8G4B3G6” indicates that the answer should be 4. 
The tester is stating the answer should be 1 but I looked at the input and there is no way that could be the answer.
My code is producing the answer that I expect to be correct. Am I missing something else here?

**Comment by LC-Pam** [comment]
Your code received Compile Error after submit, which means your code is not correct when you run this test case, so the results will be incorrect.
Please consider this submission: https://leetcode.com/submissions/detail/867198490/
The code received "Accepted" when we submit it, and when we use your above test case to run code, the test case that you advise received “G3R3R7B7R5B1G8G4B3G6” is not a valid value of type string
