### ISSUE TITLE
Contest Rating History - wrong labels

### ISSUE THREAD

**Issue by mihirahlawat** [LeetCode-Feedback/LeetCode-Feedback#1058]
#### Your LeetCode username

leetcode.com/mihiraman

#### Description of the bug

The labels for Biweekly contest 35 and Weekly contest 206 have been interchanged on the Contest Rating History graph.
I have cross-checked this on others' profiles as well. The label is wrong.
(Also will I get points for this? 🥰)

#### Screenshots

![image](https://user-images.githubusercontent.com/38140078/93915006-0358f400-fd25-11ea-9db8-95ea5751c5cc.png)
![image](https://user-images.githubusercontent.com/38140078/93915052-1370d380-fd25-11ea-8a17-430a42403830.png)

**Comment by lc-pam** [comment]
Hi @mihirahlawat .
Thank you for reaching out to us. The issue has been raised by other users and the team is currently working on a fix. Kindly remind that this is a technical issue and we opened the GitHub channel only for content issues. I'll close this ticket and please submit a ticket through our [help desk](https://support.leetcode.com/hc/en-us/requests/new).
