### ISSUE TITLE
Missing Test Case - 1317. Convert Integer to the Sum of Two No-Zero Integers

### ISSUE THREAD

**Issue by RahulGuptaNitro** [LeetCode-Feedback/LeetCode-Feedback#10586]
#### Your LeetCode username
[rahulguptanitro](https://leetcode.com/rahulguptanitro/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The below submission for [1317. Convert Integer to the Sum of Two No-Zero Integers](https://leetcode.com/problems/convert-integer-to-the-sum-of-two-no-zero-integers/) passes all the current test cases and gets Accepted, instead it should give WA on the following test case: n=3.

#### Code you used for Submit/Run operation

[Submission Link](https://leetcode.com/problems/convert-integer-to-the-sum-of-two-no-zero-integers/submissions/866928265/)

```
class Solution:
    def getNoZeroIntegers(self, n: int) -> List[int]:
        def checkzero(x):
            while x:
                if x%10==0:
                    return False
                x//=10
            return True

        for ii in range(1,n//2):
            if checkzero(ii) and checkzero(n-ii):
                return [ii,n-ii]
        return [1,1]
```

#### Language used for code
Python3

#### Expected behavior

On Test Case:
n=3

My solution gives **[1,1]** but the expected answer is **[1,2] or [2,1]**.

In my solution, loop iterates from 1 to ⌊n/2⌋ (not included), instead ⌊n/2⌋ should be included in the loop.

But my solution passed all the current test cases.

So, This missing test case should be added to the problem.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
