### ISSUE TITLE
Typo: 2208. Minimum Operations to Halve Array Sum

### ISSUE THREAD

**Issue by Mitternachtsmond** [LeetCode-Feedback/LeetCode-Feedback#10585]
#### Your LeetCode username

nichamp

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The **Example 2** of the problem has a typing mistake where 31/2=16.5 is written which should be 31/2=15.5

#### Expected behavior

In **Example 2** of the problem 31/2=15.5 should be written

#### Screenshots

<img width="434" alt="image" src="https://user-images.githubusercontent.com/85838936/209800154-598c17d1-2312-456b-a84e-f525cdcbf6bb.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
