### ISSUE TITLE
Missing Test Case - 53. Maximum Subarray

### ISSUE THREAD

**Issue by notrealmateen** [LeetCode-Feedback/LeetCode-Feedback#10592]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The test case i want to contribute is that what if all the input array given by the user in negetive.
I have seen all the test cases and know that it does no contain any such test case.
Due to which many solution like this are being accepted

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int maxSubArray(vector<int>& nums) 
    {
         for(int i=1;i<nums.size();i++)
         {
             if(nums[i-1]>0)
             {
                 nums[i]+=nums[i-1];
             }
         }
        return *max_element(nums.begin(),nums.end());
    }
};
```

#### Language used for code
C++

**Comment by BanothGaneshRathod** [comment]
4 -1 -1 4 2 -3 4 -10 -1 5

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment]
> 4 -1 -1 4 2 -3 4 -10 -1 5

This test case exists. 
![Screen Shot 2022-12-29 at 2 38 44 PM](https://user-images.githubusercontent.com/103138242/210004133-5d171a0e-e5b7-4c92-aa96-35e6ae840ae8.png)

**Comment by notrealmateen** [comment]
> 4 -1 -1 4 2 -3 4 -10 -1 5

I am saying all test cases should be negetive

**Comment by notrealmateen** [comment]
> > 4 -1 -1 4 2 -3 4 -10 -1 5
> 
> This test case exists. ![Screen Shot 2022-12-29 at 2 38 44 PM](https://user-images.githubusercontent.com/103138242/210004133-5d171a0e-e5b7-4c92-aa96-35e6ae840ae8.png)

All inputs should be negetive

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. This test case does not fail any solution. We appreciate your support!
