### ISSUE TITLE
437. Path Sum III - incorrect test case

### ISSUE THREAD

**Issue by tassossapalidis** [LeetCode-Feedback/LeetCode-Feedback#10594]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The following test case is incorrect: 
root: [1,-2,-3,1,3,-2,null,-1]
targetSum = -1

The expected output on Leetcode is 4. The answer should be 3.

#### Code you used for Submit/Run operation
```
class Solution:
    def pathSum(self, root: Optional[TreeNode], targetSum: int) -> int:
        if not root:
            return 0
        path_counter = 0
        def dfs(node, curr_sums):
            nonlocal path_counter
            if not node:
                return
            curr_sums = [sum_ + node.val for sum_ in curr_sums] + [node.val]
            path_counter += sum([1 for sum_ in curr_sums if sum_ == targetSum])
            curr_sums = [sum_ for sum_ in curr_sums if sum_ != targetSum]
            dfs(node.left, curr_sums)
            dfs(node.right, curr_sums)
        dfs(root, [])
        return path_counter
```

#### Language used for code
Python

#### Expected behavior
The valid paths where the sum is equal to the target of -1 are:
1 -> -2
1 -> -2 -> 1 -> -1
-1 (leaf node)

The expected output should be 3, not 4.

#### Screenshots
graphical representation:
<img width="327" alt="Screen Shot 2022-12-28 at 1 16 19 PM" src="https://user-images.githubusercontent.com/66144841/209859253-07f3337b-def7-42c8-9226-9cbbf0c99ebd.png">

result:
<img width="1071" alt="Screen Shot 2022-12-28 at 1 53 31 PM" src="https://user-images.githubusercontent.com/66144841/209859311-88c6c1b2-754f-4d43-b1ee-4cef26f152fd.png">

**Comment by Sajan-Vishwakarma** [comment]
![209859253-07f3337b-def7-42c8-9226-9cbbf0c99ebd](https://user-images.githubusercontent.com/67305384/209865840-2f991a10-7e9f-4348-a63d-733981e1cdce.png)

4 valid paths shown using 4 different colours.

**Comment by tassossapalidis** [comment]
Ah apologies, missed one.
