### ISSUE TITLE
Missing Test Case - 91. Decode Ways

### ISSUE THREAD

**Issue by zhang1pr** [LeetCode-Feedback/LeetCode-Feedback#1059]
#### Your LeetCode username

zhang1pr

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Missing test case (causing **Time Limit Exceeded** locally but not from judge): 
`"111111111111111111111111111111111111111111111"`

The existing test cases are too weak to cause **Time Limit Exceed**, so my brute force recursion solution got accepted.

#### Code you used for Submit/Run operation

```
/**
 * @param {string} s
 * @return {number}
 */
var numDecodings = function(s) {
  let res = 0;
    
  function h(index) {
    if (index == s.length) {
      res++;
      return;  
    }
      
    for (let i=index;i<=Math.min(index+1, s.length-1);i++) {
      const num = Number(s.slice(index, i+1));
      
      if (num > 0 && num <= 26) {
        h(i+1);   
      } else {
        break;
      } 
    }   
  }  
    
  h(0);
    
  return res;  
};
```

#### Language used for code

JavaScript

#### Expected behavior

I got **Time Limit Exceeded** locally for this test case by clicking **Run Code**, but the code got accepted by judge. Judge should throw **Time Limit Exceeded** for my brute force solution if this test case is added. Also, though my code was accepted for existing test cases, it took 7000ms and 8000ms. I believe time limit is too loose for this problem.
<img width="1664" alt="Screen Shot 2020-09-22 at 1 44 17 PM" src="https://user-images.githubusercontent.com/26691304/93918518-78eba280-fcda-11ea-85ef-340e8e3abe16.png">

If I use optimal solution, it only takes 80ms for this test case.
<img width="761" alt="Screen Shot 2020-09-23 at 5 06 43 PM" src="https://user-images.githubusercontent.com/26691304/94069817-35b72f80-fdbf-11ea-8166-224ef9652bcd.png">

**Comment by lc-ivan** [comment]
Hi @zhang1pr 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @zhang1pr 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
