### ISSUE TITLE
1962. Remove Stones to Minimize the Total

### ISSUE THREAD

**Issue by PrafulAggarwal1234** [LeetCode-Feedback/LeetCode-Feedback#10593]
Issue type: Mistake in Question Description

The Question Number 1962 on leetcode has wrong the description 
Input: piles = [5,4,9], k = 2
Output: 12
you have written this on site
Explanation: Steps of a possible scenario are:
- Apply the operation on pile 2. The resulting piles are [5,4,5].
- Apply the operation on pile 0. The resulting piles are [3,4,5].
The total number of stones in [3,4,5] is 12.

but after the first step resulting array will be [5,4,4] instead of [5,4,4].
similary after step to it will be [2,4,4] 
and final thus final answer is 10 instead of 12

so corrected desription should be

Input: piles = [5,4,9], k = 2
Output: 12
you have written this on site
Explanation: Steps of a possible scenario are:
- Apply the operation on pile 2. The resulting piles are [5,4,4].
- Apply the operation on pile 0. The resulting piles are [2,4,4].
The total number of stones in [2,4,4] is 10.

#### Your LeetCode username
https://leetcode.com/PrafulAggarwal/

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The statement said "Remove from it" and did not say "Replace it".
The statement is correct. We appreciate your support!
