### ISSUE TITLE
Inconsistent description and hints

### ISSUE THREAD

**Issue by sahajb** [LeetCode-Feedback/LeetCode-Feedback#106]
[1406. Stone Game III](https://leetcode.com/problems/stone-game-iii/)

Description:

Assume Alice and Bob play optimally.

Return "Alice" if Alice will win, "Bob" if Bob will win or "Tie" if they end the game with the same score.

Hint:

1. The game can be mapped to minmax game. Alex tries to maximize the total score and Lee tries to minimize it.

2. Use dynamic programming to simulate the game. If the total score was 0 the game is "Tie", and if it has positive value then "Alex" wins, otherwise "Lee" wins.

Alice, Bob, Alex and Lee are all being used for 2 players.

**Comment by CooperCooperCooper** [comment]
Hi @sahajb,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @sahajb,
Thank you for your time. We've updated the problem hint accordingly.

**Comment by sahajb** [comment]
Thank you for the update @CooperCooperCooper 
How do I claim the reward for this?

**Comment by CooperCooperCooper** [comment]
Hi @sahajb,
Thank you for your support. We currently provide rewards for problems and test case contribution only. Please check out the reward amount listed on the [Contribution platform](https://leetcode.com/contribute/) for more information. You may also check out our [Bug Bounty](https://leetcode.com/bugbounty/) for the issues eligible for rewards.

**Comment by sahajb** [comment]
[This](https://imgur.com/a/waPmxW9 ) is a screenshot from [Leetcode](https://leetcode.com/store/) which directs you to feedback repo. If it is a mistake then I think it should be removed.
Thanks for the reply.

**Comment by CooperCooperCooper** [comment]
Hi @sahajb,
Apologies! You've got great eyes! We received your support ticket on Zendesk. Please respond to that ticket and we will uniformly continue with the reward over there. Thank you for your support.

**Comment by sahajb** [comment]
Thank you for the update @CooperCooperCooper 
I have replied to that ticket on the support channel
