### ISSUE TITLE
Missing Test Case - 560. Subarray Sum Equals K

### ISSUE THREAD

**Issue by y2010-ops** [LeetCode-Feedback/LeetCode-Feedback#10604]
#### Your LeetCode username
 Yamini2255

#### Category of the bug

- [ ] Missing Test Cases

#### Description of the bug
In the given Question if we take the Input Array nums = [6,4,3,1], k = 10 the number of Subarrays will be 2 ([6,4], [6,3,1]) but by
running code, for this test case I get Expected = 1 and Output = 1, and the solution also gets accepted but the test case is
running no correctly in the console

#### Code you used for Submit/Run operation

```
class Solution:
    def subarraySum(self, nums: List[int], k: int) -> int:
        hashmap = {}
        hashmap[0] = 1
        count = 0
        prfxsum = 0
        for i in range(len(nums)):
            prfxsum += nums[i]
            if prfxsum - k in hashmap:
                count += hashmap[prfxsum - k]
            
            if prfxsum in hashmap:
                hashmap[prfxsum] += 1
            else:
                hashmap[prfxsum] = 1
        return count


```

#### Language used for code
Python3

#### Expected behavior
In the given Question if we take the Input Array nums = [6,4,3,1], k = 10 the number of Subarrays will be 2 ([6,4], [6,3,1]) but by
running code, for this test case I get Expected = 1 and Output = 1, and the solution also gets accepted but the test case is
running no correctly in the console

#### Screenshots

![image](https://user-images.githubusercontent.com/59636994/209959021-247a37b2-be07-40a7-95e6-ddea43805383.png)
![image](https://user-images.githubusercontent.com/59636994/209959104-b3202d87-3a7a-4779-aff4-2f0c25e088e8.png)
![image](https://user-images.githubusercontent.com/59636994/209959383-f92fbb61-683d-418d-82de-c3499d2f6af0.png)
![image](https://user-images.githubusercontent.com/59636994/209959477-b8c57307-3029-4616-a7d4-0e3906f9b3ef.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. [6,3,1] is not a subarray. The definition of subarray is in the statement. We appreciate your support!
