### ISSUE TITLE
Online Stock Span solution

### ISSUE THREAD

**Issue by Timorleiderman** [LeetCode-Feedback/LeetCode-Feedback#10600]
#### Your LeetCode username
timorl

#### Category of the bug
- [ ] Solution

#### Description of the bug
In the solution of the Online Stock Span problem you typed 135 insted of 125.

"
Use a monotonic stack
....
For example, if we have stack = [623, 532, 125] and we want to push 615, then the 532 and 135 must be popped before the 615 is pushed, otherwise the stack will no longer be sorted.
"

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
