### ISSUE TITLE
Poor sentence, makes no sense

### ISSUE THREAD

**Issue by AdilSaeedKhan** [LeetCode-Feedback/LeetCode-Feedback#10608]
#### Your LeetCode username

Adil Saeed Khan

#### Category of the bug
- [ ] Language

#### Description of the bug

On URL: https://leetcode.com/explore/interview/card/leetcodes-interview-crash-course-data-structures-and-algorithms/715/introduction/4655/
There is a sentence: 
Base cases are conditions the start of recursive functions that terminate the calls.
Which makes no sense, it should be 
Base cases are conditions at/for the start of recursive functions that terminate the calls.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
