### ISSUE TITLE
Style issue in case of long test case input

### ISSUE THREAD

**Issue by Itezaz-ul-Hassan** [LeetCode-Feedback/LeetCode-Feedback#10613]
#### Your LeetCode username
hassannasir098

#### Category of the bug
- [x] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

When I use the following code to run the following problem, there is a testcase that fails. It has a long input, the issue here is that the input should be wrapped so it's visible on multiple lines in case of long input. But it remains on a single line and the line goes far outside the box of input making a bad user interface and experience.

Problem Link: [Ones and Zeroes](https://leetcode.com/problems/ones-and-zeroes/description/)

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int maxv=0;
    unordered_map<string, int> mem;
    pair<int,int> count(const string & str){
        int m=0, n=0;
        for(int i=0;i<str.size();++i){
            if(str[i]=='0') m++;
            else n++;
        }
        return {m,n};
    }
    int findMaxForm(vector<string>& strs, int m, int n) {
        vector<pair<int,int>> strmn;
        strmn.reserve(strs.size());
        for(int i=0;i<strs.size();++i){
            auto c=count(strs[i]);
            if(c.first<=m && c.second<=n) strmn.push_back(c);
        }
        return dp(strmn, 0, m,n);
    }

    string tos(int idx, int m, int n){
        return to_string(idx)+","+to_string(m)+","+to_string(n);
    }

    int dp(vector<pair<int,int>> strs,int idx, int m, int n ){
        if(idx>=strs.size()||(m<=0 && n<=0)) return 0;
        string s=tos(idx,m,n);
        if(mem.find(s)!=mem.end()) return mem[s];
        int cm=m-strs[idx].first;
        int cn=n-strs[idx].second;
        int l1=0;
        if(cm>=0 && cn>=0)
            l1= 1+dp(strs, idx+1, cm,cn);
        int l2 = dp(strs, idx+1, m, n);
        int val= max(l1,l2);
        mem[s]=val;
        return val;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Input should be wrapped in the box

#### Screenshots

Testcase input:

<img width="1422" alt="image" src="https://user-images.githubusercontent.com/109591867/209982660-ee2cce7c-62c6-43ec-b219-ab6793c2fc65.png">

#### Additional context

Following is the testcase:
strs =
["1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0","1","0"]
m =
30
n =
30

And Time Limit Exceed occur

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
https://project.feishu.cn/leetcode/us_tickets/detail/3448275?parentUrl=%2Fleetcode%2FworkObjectView%2Fus_tickets%2FvHtNOOSVR
