### ISSUE TITLE
Missing Test Case - 51. N-Queens

### ISSUE THREAD

**Issue by ssrishti582** [LeetCode-Feedback/LeetCode-Feedback#10618]
class Solution {
public:
    vector<vector<string>>ans;
    bool isSafe(int i, int j, vector<string>& board){
        int x=i, y=j;
        //Up direction
        while(x>=0){
            if(board[x][y]=='Q')return false;
            x--;
        }
        x=i;
        y=j;

        //top left diagonal
        while(x>=0&&y>=0){
            if(board[x][y]=='Q')return false;
            x--;
            y--;
        }
        x=i;
        y=j;
        //top right diagonal 
        while(x>=0&& y<board.size()){
            if(board[x][y]=='Q')return false;
            x--;
            y++;
        }

        return true;
    }
    void help(vector<string>&board, int i, int n){
        if(i==n){
            ans.push_back(board);
            return;
        }
        for(int j=0;j<n;j++){
            if(isSafe(i,j,board)){
                board[i][j]='Q';
                help(board,i+1,n);
                board[i][j]='.';
            }
        }
    }
    vector<vector<string>> solveNQueens(int n) {
        string row(n,'.');
        vector<string>board(n,row);
        help(board,0,n);
        return ans;
    }
};

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
