### ISSUE TITLE
Missing Test Case - 152. Maximum Product Subarray

### ISSUE THREAD

**Issue by shubham-kewat** [LeetCode-Feedback/LeetCode-Feedback#10619]
#### shubham_kewat

test case [6,-3,-10,0,2]
it's output should be 180

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
