### ISSUE TITLE
Giving wrong answer for correct solution

### ISSUE THREAD

**Issue by ankurraj2606** [LeetCode-Feedback/LeetCode-Feedback#10610]
#### Category of the bug
- [ ] Solution

#### Description of the bug
I think I am writing the right solution, using charAt, but giving me wrong answer. Can anyone have a look?

#### Code you used for Submit/Run operation
``` 
var restoreString = function(s, indices) {
    let shuffledString = "";
    for(let i=0; i<indices.length; i++) {
        shuffledString+=s.charAt(indices[i])
    }
return shuffledString
};
```

#### Language used for code
JavaScript

#### Expected behavior
The code should give right answer and leetcode should accept it

#### Screenshots
![image](https://user-images.githubusercontent.com/65525788/209976068-aa7c5994-214a-440e-b5b3-c17a0cae5668.png)

#### Additional context

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

**Comment by ankurraj2606** [comment]
Can you guide me, where I am doing wrong?
