### ISSUE TITLE
322. Coin change question lacks details on inputs

### ISSUE THREAD

**Issue by IgorPerikov** [LeetCode-Feedback/LeetCode-Feedback#1061]
#### Your LeetCode username
IgorPerikov

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
https://leetcode.com/problems/coin-change/

Description has no details on inputs and it's impossible for a person to know what to expect, maybe amount can be so big, that making array of size `amount` wouldn't pass memory restrictions. Turns out system has a test case which will check for int32 overflow edge case, but it's kinda irrational to try to predict all possible limitations, when none are stated

My suggestion is to add input restrictions to the description to clarify this

**Comment by lc-kay** [comment]
Hi @IgorPerikov 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
