### ISSUE TITLE
205. Isomorphic Strings

### ISSUE THREAD

**Issue by Default462** [LeetCode-Feedback/LeetCode-Feedback#10614]
#### Category of the bug
- [ ] Solution

#### Code you used for Submit/Run operation

```
class Solution:
    def isIsomorphic(self, s: str, t: str) -> bool:
        dict_s={}
        dict_t={}
        random_num=0
        answer="true"
        if len(s)!=len(t):
            return "false"
        for i,j in zip(s,t):
            if dict_s.get(i)==None :
                if dict_t.get(j)==None:
                    dict_s[i]=random_num
                    dict_t[j]=random_num
                    random_num+=1
                    answer="false"
                else:
                    print(dict_s,dict_t)
            else:
                if dict_s.get(i)!=dict_t.get(j):
                    print(dict_s,dict_t,"went here")
                    answer="false"
        print(dict_s,dict_t)
        print(answer)
        return answer           

```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Default462** [comment]
Language Python3
test case:- 
s="foo" and t ="bar"

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, your code received Wrong Answer after submit, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
