### ISSUE TITLE
452. Minimum Number of Arrows to Burst Balloons

### ISSUE THREAD

**Issue by desaimann37** [LeetCode-Feedback/LeetCode-Feedback#10621]
#### Your LeetCode username

Mann_12345

#### Category of the bug

- [ ] Solution

#### Description of the bug

Bug is Last test case in which it is not running correctly it is not going to increment the next count which eventually returned as answer.

#### Code you used for Submit/Run operation

```
class Solution{
    public int findMinArrowShots(int[][] points) {
        Arrays.sort(points, new Comparator<int[]>() {
            @Override
            public int compare(int[] a, int[] b) {
                return a[1] - b[1];
            }
        });
        int n = points.length;
        int res = 1;
        int prev = 0;

            for(int curr = 1; curr<n ; curr++){
                if(points[curr][0] > points[prev][1]){
                    res++;
                    prev = curr;
                }else if(points[curr][0] == points[prev][1]){
                    res++;
                    curr++;
                    prev = curr;
                    curr++;
                }
            }
            return res;

    }       
}


```

#### Language used for code
Java

#### Expected behavior

Actually the counter must increment because the if condition is true in the case and for another loop again counter must be increased but in the test case as mentioned above it is not giving proper output.

#### Screenshots

![Screenshot (40)](https://user-images.githubusercontent.com/96511880/210007289-8bcd52c7-83e3-4d42-a788-72ae1aec145f.png)

#### Additional context

I guess it is due to datatype range so it is giving last one testcase error ,As all testcases from 48/49 are running properly with this solution but last test case is not running and that is bug i guess

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, your code received Wrong Answer after submitted it. please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!
