### ISSUE TITLE
28. Find the Index of the First Occurrence in a String

### ISSUE THREAD

**Issue by hyunsik-yoon** [LeetCode-Feedback/LeetCode-Feedback#10620]
#### Your LeetCode username
labsurde

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

It's not a but but it's a suggestion regarding the default signature in C++ language, which is the following:

```
    int strStr(string haystack, string needle)
```

Here, param strings could have 10^4 length and they are passed with call-by-value.

How about changing it to call-by-references instead of call-by-value that needs to call copy constructor, since calling copy constructor means we need to use O(n) storage?

```
    int strStr(string &haystack, string &needle)
```

#### Language used for code
 C++

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to check the problem and It is ok to keep them passed by value. We appreciate your support!
