### ISSUE TITLE
692. Top K Frequent Words - Approach 2 Python code doesn't implement algorithm as described

### ISSUE THREAD

**Issue by nikhila01** [LeetCode-Feedback/LeetCode-Feedback#10628]
#### Your LeetCode username
nikhila01

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
**Approach 2: Max Heap** in the solution article states that the algorithm is to heapify all `N` (word, frequency) pairs and then remove the top `k` pairs giving a time complexity of `O(N + k log N)`. However, the Python code for the solution uses `heapq.nsmallest` which does not implement this algorithm. `heapq.nsmallest` only keeps `k` entries in the heap, which is the same as **Approach 3**, and has a time complexity of `O(N log k)`.

See the following links for more details on how `heapq.nsmallest` is implemented:
- https://stackoverflow.com/questions/48796756/how-does-heapq-nsmallest-work
- https://github.com/python/cpython/blob/main/Lib/heapq.py#L395
- https://code.activestate.com/recipes/577573-compare-algorithms-for-heapqsmallest/

I've provided a sample Python solution below that implements **Approach 2**.

#### Code you used for Submit/Run operation
```python
class Pair:
    def __init__(self, word, freq):
        self.word = word
        self.freq = freq

    def __lt__(self, p):
        return self.freq > p.freq or (self.freq == p.freq and self.word < p.word)


class Solution:
    def topKFrequent(self, words: List[str], k: int) -> List[str]:
        cnt = Counter(words)
        heap = [Pair(word, freq) for word, freq in cnt.items()]
        heapify(heap)

        return [heappop(heap).word for _ in range(k)]
```

#### Language used for code
Python

#### Expected behavior
I preferably expect that the Python code for **Approach 2: Max Heap** should be changed to implement the algorithm as described in the article. Or less preferably, the time complexity should be updated to take into account the actual algorithm that `heapq.nsmallest` uses.

#### Additional context
I have not reviewed the C++ or Java solutions. They may or may not have the same issue.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
