### ISSUE TITLE
1962. Remove Stones to Minimize the Total

### ISSUE THREAD

**Issue by umangnangal** [LeetCode-Feedback/LeetCode-Feedback#10629]
#### Your LeetCode username
umangnangal

#### Category of the bug
- [ ] Question

#### Description of the bug
In the problem statement, it mentions take the floor of the ans, but by looking at the examples, it appears that it is the ceil which has to be taken.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
The statement said "Remove from it" and did not say "Replace it".
The statement is correct.

**Comment by alehro** [comment]
I also missed that:
The statement said "Remove from it" and did not say "Replace it".

The problem is that when I used Ceiling instead of Floor, all tests passed and the solution was accepted. I think additional test case is needed to fail on Ceiling.
