### ISSUE TITLE
Missing Test Case - 523. Continuous Subarray Sum

### ISSUE THREAD

**Issue by ArmanAmandykuly** [LeetCode-Feedback/LeetCode-Feedback#10627]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Continuous Subarray Sum
class Solution {
public:
    bool checkSubarraySum(vector<int>& nums, int k) {
        int c = 0;

        for(int i = 0; i < nums.size(); i ++) {
            nums[i] = nums[i] % k;

            if(nums[i] == 0)
                c ++;
            else
                c = 0;

            if(c == 2)
                return true;
        }

        for(long long ki = k; ki < ((long long)5 * k + 1); ki += k) {
            int start = 0, end = 0, sum = 0;

            int n = nums.size();

            while(start < n) {
                if(end == n || sum >= ki) {
                    sum -= nums[start ++];

                    if(sum == ki)
                        return true;
                } else {
                    sum += nums[end ++];

                    if(sum == ki)
                        return true;
                }
            }
        }

        return false;
    }
};
```

#### Expected behavior

The submitted code shouldn't proceed, but it's accepted. The code fails at this test case:

nums = [10,10,10,10,10,10,10,10,10,10,10]

k = 11

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!


Please provide us your LC username.

**Comment by ArmanAmandykuly** [comment]
user4140s

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
