### ISSUE TITLE
Missing Test Case - 15. 3Sum 

### ISSUE THREAD

**Issue by dhiru9599** [LeetCode-Feedback/LeetCode-Feedback#10634]
[1,0,-1,3,2,4,-4,0,1,-2]

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by dhiru9599** [comment]
[1,0,-1,3,2,4,-4,0,1,-2]

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
