### ISSUE TITLE
Missing Test Case - 735. Asteroid Collision

### ISSUE THREAD

**Issue by Mahi-Badaya** [LeetCode-Feedback/LeetCode-Feedback#10631]
#### Your LeetCode username

_Mahi28

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ &check;] Language
- [ &check;] Missing Test Cases 

#### Description of the bug

 Given the line in question
>  If two asteroids meet, the smaller one will explode. _If both are the same size, both will explode._ 

The question says that if asteroids are moving in the opposite direction and if they are of the same size both of them will explode. But the test cases do not justify the case when the given testcase is this: 

**Input:**
`asteroids = [-5, 5, 10, 3]`

**Output:**
`[10,3]`

**Expected:**
`[-5,5,10,3]`

#### Expected behavior

`-5 and 5` both will collide and explode because they are moving in opposite directions and have equal values. So, the `expected output` should be `[10, 3]`.
But according to the current state expected output is `[-5, 5, 10, 3]` which is wrong.

#### Language used for code

C++

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<int> asteroidCollision(vector<int>& asteroids) {
        int n= asteroids.size();
        stack <int> st;
        vector <int> ans;
        for(int i=0;i<n;i++){
            if(!st.empty() && st.top()<0 && asteroids[i]>0 && abs(st.top())==(asteroids[i]))
                st.pop();
            
            else if(asteroids[i]>0)
                st.push(asteroids[i]);
            
            else{
                while(!st.empty() && st.top()>0 && st.top()<abs(asteroids[i]))
                    st.pop();

                if(!st.empty() && st.top()==abs(asteroids[i]))
                    st.pop();
                
                else if(!st.empty() && st.top()>abs(asteroids[i]))
                    continue;
                
                else
                    st.push(asteroids[i]);
                
            }
        }

        while(!st.empty()){
            ans.push_back(st.top());
            st.pop();
        }

        reverse(ans.begin(), ans.end());
        return ans;
    }
};
```

**Comment by Sajan-Vishwakarma** [comment]
The expected output  [-5,5,10,3] is correct. Asteroids -5, and 5 will never clash as Asteroid[-5] is moving towards the left and Asteriod[5] is moving towards the right. 
So the final output remains the same as the original input array.
