### ISSUE TITLE
Display videos

### ISSUE THREAD

**Issue by MohamedWaelAlsayed** [LeetCode-Feedback/LeetCode-Feedback#10637]
#### Your LeetCode username

MohamedWaelAlsayed

#### Category of the bug
- [ ] Question
- [*] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I can't run and display any learning videos, because of this message (Because of its privacy settings, this video cannot be played here) 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

![image](https://user-images.githubusercontent.com/62488272/210077404-e797eb74-ea00-472d-a78a-65c7cf4494dd.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem page link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the issue should be fixed, would you mind check it again to see it works or not on your side?
Sorry for the all inconvenience .

**Comment by SRDMoss** [comment]
I am encountering this problem right now.
