### ISSUE TITLE
Heap video is missing

### ISSUE THREAD

**Issue by chanondw** [LeetCode-Feedback/LeetCode-Feedback#10630]
#### Your LeetCode username
chanondw

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The video for heap insertion and deletion is missing

#### Screenshots
![image](https://user-images.githubusercontent.com/13291829/210035490-fa2845ca-80d5-49dc-80ef-b83c09f28fbf.png)

**Comment by LC-Pam** [comment]
Thank you for your time. The issue should be fixed.  We appreciate your support!
![Screen Shot 2022-12-30 at 3 03 56 PM](https://user-images.githubusercontent.com/103138242/210108054-df8108f5-d928-48ec-b6f8-b9ad481cd92c.png)
