### ISSUE TITLE
Missing solution code in 42. Trapping Rain Water

### ISSUE THREAD

**Issue by mnaoumov** [LeetCode-Feedback/LeetCode-Feedback#10647]
#### Your LeetCode username

mnaoumov

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

[Solution page](https://leetcode.com/problems/trapping-rain-water/solution/) misses code sample in **Approach 1: Brute force** section.

If you analyze the page source code you will find a broken link https://leetcode.com/playground/Nnd5emhj/shared

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!

**Comment by mnaoumov** [comment]
@LC-Pam I think the issue is closed too early. The code is still missing

![image](https://user-images.githubusercontent.com/735878/210291450-93e469fe-4abb-40f2-87a7-f086243e2964.png)

**Comment by mnaoumov** [comment]
@LC-Pam Now it is added. Thanks
