### ISSUE TITLE
Missing solution code in 326. Power of Three

### ISSUE THREAD

**Issue by mnaoumov** [LeetCode-Feedback/LeetCode-Feedback#10648]
#### Your LeetCode username

mnaoumov

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

[Solution page](https://leetcode.com/problems/power-of-three/solution/) misses code sample in **Approach 4: Integer Limitations** section.

If you analyze the page source code you will find a broken link https://leetcode.com/playground/b8F8pjqx/shared

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!

**Comment by mnaoumov** [comment]
@LC-Pam I think the issue is closed too early. The code is still missing 
![image](https://user-images.githubusercontent.com/735878/210291541-65c1a495-e0da-4baf-9513-3ed768d56363.png)

**Comment by mnaoumov** [comment]
@LC-Pam Now it is added. Thanks
