### ISSUE TITLE
Missing Test Case - 227. Basic Calculator II

### ISSUE THREAD

**Issue by its-yashpaliwal** [LeetCode-Feedback/LeetCode-Feedback#10643]
#### Your LeetCode username
yashpaliwal345

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
wrong answer on testcase [ "1+2*3/4" ]

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int calculate(string s) {
        int length = s.length();
        if (length == 0) return 0;
        int currentNumber = 0, lastNumber = 0, result = 0;
        char sign = '+';
        for (int i = 0; i < length; i++) {
            char currentChar = s[i];
            if (isdigit(currentChar)) {
                currentNumber = (currentNumber * 10) + (currentChar - '0');
            }
            if (!isdigit(currentChar) && !iswspace(currentChar) || i == length - 1) {
                if (sign == '+' || sign == '-') {
                    result += lastNumber;
                    lastNumber = (sign == '+') ? currentNumber : -currentNumber;
                } else if (sign == '*') {
                    lastNumber = lastNumber * currentNumber;
                } else if (sign == '/') {
                    lastNumber = lastNumber / currentNumber;
                }
                
                sign = currentChar;
                currentNumber = 0;
            }
        }
        result += lastNumber;
        
        return result;  
    }
};
```

#### Language used for code

C++

#### Expected behavior

for the expression "1+2*3/4" should be evaluated in the way ( 1 + ( 2 * (3/4) ) ) = 1 but it is calculated as ( 1 + ( (2 * 3) / 4 ) ) = 2
So the right answer should be 1 instead of 2. According to BODMAS or PEDMAS rule.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by stormsunshine** [comment]
Why do you think division should be evaluated before multiplication? Both multiplication and division have the same precedence.

**Comment by LC-Pam** [comment]
Thank you for your time. 
The shown answer is correct following the rules of evaluating a mathematical expression.
Please check Wikipedia or Google for better explanation.
 We appreciate your support!
