### ISSUE TITLE
Problem 1834

### ISSUE THREAD

**Issue by strukturen** [LeetCode-Feedback/LeetCode-Feedback#10644]
#### Your LeetCode username

strukturen

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases or Incorrect

#### Description of the bug

I obtain the message "Wrong Answer" for test case 24 but when copying both my output and expected answer to e.g. MS Excel, in order to find the mistake, I can't find a difference in the answers. (I took the differences between the expected values and it's always 0.) So, I'm wondering whether my code is wrong, the test case should be correct or maybe it should return a different error message e.g. TLE. 

#### Code you used for Submit/Run operation

import heapq
import copy
class Solution(object):
    def getOrder(self, tasks):
        """
        :type tasks: List[List[int]]
        :rtype: List[int]
        """
        ret = list()
        ntrue = copy.deepcopy(tasks)
        heapq.heapify(tasks)
        n = len(tasks)
        curr = list()
        time_track = 0
        j = 0
        while n != len(ret):
            if len(tasks) > 0:
                while tasks[0][0] <= time_track:
                    curr.append(heapq.heappop(tasks))
                    if len(tasks) == 0:
                        break
            if len(curr) > 0:
                temp = min(x[1] for x in curr)
                temp2 = list(x[0] for x in curr if x[1] == temp)
                time_track = time_track + temp
                ind = list()
                for i in range(len(temp2)):
                    ind.append(ntrue.index([temp2[i], temp], j))
                if len(ind) != len(set(ind)):
                    j = min(ind)+1
                else:
                    j = 0
                ret.append(min(ind))
                curr.remove(ntrue[min(ind)])
            else:
                time_track += 1
        return ret

#### Language used for code

Python

#### Expected behavior

Usually, LeetCode points out (in case of a wrong answer) where the mistake between the output and expected answer is.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by strukturen** [comment]
https://leetcode.com/problems/single-threaded-cpu/submissions/868219863/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!

**Comment by strukturen** [comment]
Is there a possibility to see the mistake? (This would be quite helpful, as it is usually shown, but here the outcome seems to be too long.)
<img width="1008" alt="Bildschirm­foto 2022-12-30 um 22 45 09" src="https://user-images.githubusercontent.com/91076940/210113659-cc59ef23-d832-4238-a42f-3e7aac3573a5.png">
