### ISSUE TITLE
Missing Testcases - 268. Missing Number

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1064]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

268. Missing Number
https://leetcode.com/problems/missing-number/

An hour ago a submission with below code passed, but it should not.
RunCode behaviour and Submit behaviour is not same.

Below testcases are below:

    input   []        expected  0     actual  undefined
    input   [0]       expected  1     actual  undefined
    input   [1,0]     expected  2     actual  undefined

#### Code you used for Submit/Run operation

```
let missingNumber = function (nums) {
    nums.sort(function (a, b) {
        return a - b;
    });
    for (let i = 0; i < nums.length; i++) {
        if (nums[i] !== i) {
            return i;
        }
    }
};
```

#### Language used for code
JavaScript

#### Expected behavior

- How is the question review committee missing basic cases? like [] & [0]

- A question must have basic edge case test cases. Otherwise, Users will learn & fail their interviews. Is this an interview site? should it be more correct than now?

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 

I just ran the code and it doesn't it was not accepted. The test cases you suggested were included already.
