### ISSUE TITLE
Missing Test Case - 2235. Add Two Integers

### ISSUE THREAD

**Issue by jasonmauss** [LeetCode-Feedback/LeetCode-Feedback#10658]
#### Your LeetCode username
jamauss

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
I think it would be good to have a test case where both numbers are negative

#### Code you used for Submit/Run operation

```
// Two Sum
const sum = (num1: number, num2: number): number => {

    return (num1) + (num2);
    
};
sum(-5, -5); // should return -10
```

#### Language used for code
TypeScript / JavaScript

#### Expected behavior
Revise the question to include a third example test case

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your to check the problem and looks like the problem is ok in its current shape. We appreciate your support!
