### ISSUE TITLE
980. Unique Paths III

### ISSUE THREAD

**Issue by archit2311** [LeetCode-Feedback/LeetCode-Feedback#10657]
Leetcode username: Archit_Srivastava

Bug is in topic tags:
Topic tag includes dynamic programming it should include Backtracking also since it is basically a backtracking question.

It creates confusion and a lot of time wastage if someone thinks a DP solution seeing the topic tag.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
