### ISSUE TITLE
Missing Constraint check 389. Find the Difference

### ISSUE THREAD

**Issue by highfinddale** [LeetCode-Feedback/LeetCode-Feedback#1065]
#### Your LeetCode username

highfinddale

#### Category of the bug
- [.] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Question statement says string **s** and **t** consists of all lower case characters.  But check for the corresponding constraints is missing. 

#### Code you used for Submit/Run operation

```
class Solution {
    public char findTheDifference(String s, String t) {
        int [] fs=new int[26], ft=new int [26];
        s=s.trim();
        for(char c: s.toCharArray())
            fs[c-'a']++;
        for(char c:t.toCharArray())
            ft[c-'a']++;
        for(int i=0;  i<26; i++)
            if(fs[i]!=ft[i])
                return (char)('a'+i) ;
        return ' ';
    }
}

```

#### Language used for code

Java

#### Expected behavior

Expected test case invalid from the judge without runtime exception.  

#### Screenshots

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3402185/94121492-006a1a80-fe6f-11ea-8636-2c8d33181915.png">

**Comment by lc-kay** [comment]
Hi @highfinddale 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @highfinddale 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!

**Comment by highfinddale** [comment]
Hi Team,

I am yet to get the 100 coins for this test case. Please check

Thanks and Regards,
HIghfinddale
________________________________

**Comment by lc-kay** [comment]
@highfinddale 

Unfortunately, we don't reward points for missing constraints. Thank you for your time and support.
