### ISSUE TITLE
article typo in the Explore card for DP

### ISSUE THREAD

**Issue by CocoYard** [LeetCode-Feedback/LeetCode-Feedback#10650]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I believe that the author meant to say
hardestJobRemaining[i] represents the difficulty of the hardest job on or after `job` i

#### Screenshots

<img width="902" alt="image" src="https://user-images.githubusercontent.com/93499248/210125229-771e7574-086e-45d6-bb49-9ff28ac83094.png">

#### Additional context

https://leetcode.com/explore/learn/card/dynamic-programming/632/common-patterns-in-dp-problems/4109/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
