### ISSUE TITLE
Bug in sample Submissions tab - 2522. Partition String Into Substrings With Values at Most K

### ISSUE THREAD

**Issue by shubhcodegate** [LeetCode-Feedback/LeetCode-Feedback#10668]
#### Your LeetCode username
kmr_shubh

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The bug is in the "Submissions" section that appears after a successful submission in the question.
[Link](https://leetcode.com/problems/partition-string-into-substrings-with-values-at-most-k/submissions/868945203/)
When trying to look at other sample submissions. I do not get solutions for the given problem ie. "minimumPartition(string s, int k)". Instead the solution for "minimalSubstrings(string s) " is displayed. This bug is evident from difference in function templates of sample submissions and that of problem's required function template.

**Solutions shown is not for the given problem.**

#### Code you used for Submit/Run operation

```
//
class Solution {
    bool cmp(string& s, int i, string& kk) {
        int j = 0;
        while(j < kk.size() && s[i+j] == kk[j]) ++j;
        return j == kk.size() || s[i+j] < kk[j];
    }
public:
    int minimumPartition(string s, int k) {
        int l = 0;
        int ans = 0;
        string kk = to_string(k);
        // cout << s << " " << kk << endl;
        if(s.size() <= kk.size() && s <= kk) return 1;
        int sz = kk.size();
        while(l < s.size()) {
            int len = 0;
            if(cmp(s, l, kk)) len = sz;
            else len = sz - 1;
            // cout << s.substr(l, len);
            // cout << endl;
            if(len < 1) return -1;
            l += len;
            ++ans;
        }
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Solution for the given problem should be seen.

#### Screenshots

![image](https://user-images.githubusercontent.com/45122479/210197085-d827a401-8e8d-41c7-a5e1-22d576098039.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
https://project.feishu.cn/leetcode/us_tickets/detail/3448274?parentUrl=%2Fleetcode%2FworkObjectView%2Fus_tickets%2FvHtNOOSVR

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
