### ISSUE TITLE
Missing Test cases - 599. Minimum Index Sum of Two Lists

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1066]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Following code does Not pass, following test cases:

Test cases:

input   [["SG4","TE4","BK4","KFC"],["KFC","BK4","SG4"]]
     expected  ["SG4"]
     actual  ["KFC","SG4"]

input   [["S","TEXP","BK","KFC"],["KFC","BK","S"]]
     expected  ["S"]
     actual  ["KFC","S"]

#### Code you used for Submit/Run operation

Code can be seen
in the "sample 88 ms submission"
of "Accepted Solutions Runtime Distribution"
at https://leetcode.com/submissions/detail/400104288/

```
var findRestaurant = function(list1, list2) {
  const memo = new Map(), result = [];
  let i, j, listLengthSum = list1.length + list2.length;;
  
  for (i = 0; i < list1.length; i++) {
    memo.set(list1[i], i);
  }
  
  for (j = 0; j < list2.length; j++) {
    const checker = j + memo.get(list2[j]);

    if (memo.has(list2[j]) && checker <= listLengthSum) {
      if (checker < listLengthSum) {
        result.pop()
      }
      result.push(list2[j])
      listLengthSum = checker
    }
  }
  
  return result;
};
```

#### Expected behavior

The question should have enough tests so that right code gets better runtime, instead of the wrong code.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
