### ISSUE TITLE
Missing Test Case - 290. Word Pattern

### ISSUE THREAD

**Issue by aravindg-7** [LeetCode-Feedback/LeetCode-Feedback#10666]
#### Your LeetCode username

aravindganta7

#### Category of the bug
- [ ] Question
- [ ] Missing Test Cases 

#### Description of the bug

The expected answer is different from my output for cases like
 pattern - 'aa' and s - 'dog dog dog dog'  Expected - False, Output - True
 pattern - 'a' and s - 'cat cat cat cat'  Expected - False, Output - True
When I submit my code got accepted so either some test cases are missing or for the above cases the Expected output is wrong

#### Code you used for Submit/Run operation

```
class Solution:
    def wordPattern(self, pattern: str, s: str) -> bool:
        p_match = {}
        s_match = {}
        p = [i for i in pattern]
        s = s.split(" ")
        j = 0
        if len(s)%len(p) != 0:
            return False
        for i in range(len(s)):
            if j == len(p):
                j = 0
            if p[j] not in p_match:
                p_match[p[j]] = s[i]
            elif p_match[p[j]] != s[i]:
                return False
            if s[i] not in s_match:
                s_match[s[i]] = p[j]
            elif s_match[s[i]] != p[j]:
                return False
            j += 1
        return True
```

#### Language used for code

Python

#### Expected behavior

The output for the below cases was supposed to be True but the expected output is showing False (Code got accepted)
 pattern - 'aa' and s - 'dog dog dog dog'  Expected - False, Output - True
 pattern - 'a' and s - 'cat cat cat cat'  Expected - False, Output - True

#### Screenshots

<img width="1417" alt="Screenshot 2022-12-31 at 7 19 25 PM" src="https://user-images.githubusercontent.com/58502283/210158704-b0e9a05c-5b4a-4527-94fe-1854c982184f.png">

<img width="914" alt="Screenshot 2022-12-31 at 7 20 58 PM" src="https://user-images.githubusercontent.com/58502283/210158721-ee6e8a69-fcbf-49c7-934b-ca9bcea756c0.png">
<img width="914" alt="Screenshot 2022-12-31 at 7 21 10 PM" src="https://user-images.githubusercontent.com/58502283/210158724-719b4bf6-273e-4c67-8e0e-08453e47757a.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
