### ISSUE TITLE
Ambiguity in problem statement for LC301

### ISSUE THREAD

**Issue by hardik302001** [LeetCode-Feedback/LeetCode-Feedback#10660]
#### Your LeetCode username
targetGuardian

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

For the problem [LC301](https://leetcode.com/problems/remove-invalid-parentheses/) , I feel there is ambiguity in the problem statement.
Fr the below test case:
`Input: s = "()())()"`, I think this output is valid : ` ["(())()","()()()","()()()"]`.
The minimum removal is 1.
For the string "()()()" , we got it 2 times in our output because one time we will remove ")" at index 3 (0 based indexing) and second time we will remove ")" at index 4.
Thus , we have following string "()()()" twice. And according to problem statement it is correct. 

Else , It should be explicitly mentioned that only unique strings are allowed.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
