### ISSUE TITLE
Bug in Remove Duplicates from Sorted Array problem

### ISSUE THREAD

**Issue by Michell203** [LeetCode-Feedback/LeetCode-Feedback#10664]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

When I use the debugger, I get the correct output, however when I run the code it doesn't work. Mainly, the problem is that noOfUnique does not increment correctly for some reason at line 10. I verified this using System.out.println.

#### Code you used for Submit/Run operation

```
// Remove Duplicates from Sorted Array
class Solution {
    static HashSet<Integer> uniqueNums = new HashSet<Integer>();

    public int removeDuplicates(int[] nums) {
        int noOfUnique = 0;

        for(int i : nums){
            if(!this.uniqueNums.contains(i)){
                this.uniqueNums.add(i);
                noOfUnique++;
            }
        }

        int n = 0;
        
        for(Integer i :uniqueNums){
            nums[n] = i;
            n++;
        }
        
        return noOfUnique;
    }
}
```

#### Language used for code

This was written in Java.

#### Expected behavior

The noOfUnique should increment, but for some reason seems to stop after it reaches 3.

#### Screenshots

![image](https://user-images.githubusercontent.com/81302943/210153417-b0ab1081-5dca-45bb-9a62-7dd477b4773f.png)
The above is the output when I use the debugger.

![image](https://user-images.githubusercontent.com/81302943/210153422-63fd2dc0-3c16-4a9d-9f7b-ac26fee65d9f.png)
And this is the output when I run the code.

Am I missing something here?

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!
