### ISSUE TITLE
336 typo

### ISSUE THREAD

**Issue by randolf-scholz** [LeetCode-Feedback/LeetCode-Feedback#10667]
Change `0 <= i, j < word.length` to `0 <= i, j < words.length`.

https://leetcode.com/problems/palindrome-pairs/description/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
