### ISSUE TITLE
Missing Test Case - 13. Roman to Integer

### ISSUE THREAD

**Issue by Abdelaziz-Elshrkawy** [LeetCode-Feedback/LeetCode-Feedback#10665]
#### Your LeetCode username

abdelaziz53

#### Category of the bug
- [  ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

test case three has a wrong answer it expects the result as 1994 instead of 2216 but 2216 is the right answer
Explanation: 
s = "MCMXCIV"
I             1
V             5
X             10
L             50
C             100
D             500
M             1000
you have two M in the string so initially we have 2000 right then two C that's 2200 and X then we got 2210 and I gives us 2211 and finally V the result is 2216!
#### Code you used for Submit/Run operation
**My Soluton**: 

```
var romanToInt = function(s) {
    const letterArr = [...s]
    let value = 0
    for(let i = 0; i < letterArr.length; i++){
        switch (letterArr[i]){
        case 'I':
            value+=1
            break;
        case 'V':
            value+=5
            break;
        case 'X':
            value+=10
            break;
        case 'L':
            value+=50
            break;
        case 'C':
            value+=100
            break;
        case 'D':
            value+=500
            break;
        case 'M':
            value+=1000
    }
    }
    return value
};```


<!-- 
Please make sure you wrap your code with ``` tags. 
Otherwise we may reject your request. 
-->

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code
<!-- Javascript -->


#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->



#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by Abdelaziz-Elshrkawy** [comment]
Roman to Integer Test Case Three wrong answer

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
