### ISSUE TITLE
Incorrect Test Case prevents submission - 1528

### ISSUE THREAD

**Issue by keithmacinnis** [LeetCode-Feedback/LeetCode-Feedback#1067]
---
name: Incorrect Test Case prevents submission - 1528
about: the expected output reflects an input of [ 4,5,6,7,0,1,2,3]. The input should be updated to [ 4,5,6,7,0,1,2,3]. The input is currrently [ 4,5,6,7,0,**2,1**,3]. 
title: ''
labels: ''
assignees: ''

---

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

The expected output reflects an input of [ 4,5,6,7,0,1,2,3]. The input should be updated to [ 4,5,6,7,0,1,2,3]. The input is currrently [ 4,5,6,7,0,**2,1**,3]. 

#### Code you used for Submit/Run operation

```
/**
 * @param {string} s
 * @param {number[]} indices
 * @return {string}
 */
var restoreString = function(s, indices) {
    var result =[];
    var x;
    for (x=0;x<indices.length;x++) {
        result.push(s[indices[x]]);
    }
    return result;
};
```

#### Language used for code

javascript

#### Expected behavior

The testcase is invalid, so the solution can't be submitted. My program will output an answer of "Leetcdoe", whereas the testcase expects "Leetcode". In order for the program to output this, the indices passed in this testcase should be [ 4,5,6,7,0,1,2,3] AND NOT [ 4,5,6,7,0,2,1,3]

#### Screenshots

![image](https://user-images.githubusercontent.com/6054402/94188935-ecb6b800-fe5e-11ea-85eb-841f93d9007e.png)

**Comment by lc-kay** [comment]
Hi @keithmacinnis, 

Please check out example 1 for an explanation of the test case.

**Comment by keithmacinnis** [comment]
As the example shows , "codeleet" is to become "leetcode" after shuffling. HOWEVER, [ 4,5,6,7,0,2,1,3] will output "leetcdoe". because the 5th and 6th indexs are in reverse order. 
This can be solved two ways, change the expected output for exmaple 1 to "leetcdoe" or change the indices passed for example one to " [ 4,5,6,7,0**,2,1,**3] "
