### ISSUE TITLE
Missing Test Case - 2461. Maximum Sum of Distinct Subarrays With Length K

### ISSUE THREAD

**Issue by penguin2** [LeetCode-Feedback/LeetCode-Feedback#10677]
#### Your LeetCode username
sweetpotato2

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A testcase such as 
- nums = [1,2,2,1,3]
 k = 4

needs to be added to make the following code fail.

#### Code you used for Submit/Run operation

```
class Solution:
    def maximumSubarraySum(self, nums: List[int], k: int) -> int:
        # roll the subarray of length k from the start(left) to the end(right)
        # - tracing sum of the subarray
        # - saving the last seen position of each value

        # last seen position of each value
        pos = [-1]*(max(nums)+1)

        # running sum of the current subarray (length: k)
        sm = 0
        
        # left_bound (lb) is positioned before the start of the current subarray
        # if and only if the current subarray consists of distinct values
        lb = -1

        # init (first k elements)
        for i in range(k):
            n = nums[i]
            if pos[n] != -1:
                lb = pos[n]
            pos[n] = i
            sm += n
        mx = sm if lb == -1 else 0

        # rolling the subarray of length k
        for i in range(k,len(nums)):
            sm += nums[i]-nums[i-k]
            n = nums[i]
            if pos[n] > lb:
                lb = pos[n]
            if lb <= i-k:
                mx = max(mx,sm)
            pos[n] = i

        return mx 
```
The submission result of the code above was 'accepted'. (screenshot 2)

#### Language used for code
python3

#### Expected behavior

By the testcase above, the code I attached should fail, since the output of the code is 8 while the expected one is 0.
(screenshot 1)

#### Screenshots
- screenshot 1
<img width="1172" alt="1-1" src="https://user-images.githubusercontent.com/17985971/210176155-d6f8b818-4266-4e23-bdc2-3a2fb4219316.png">

- screenshot 2 : https://leetcode.com/problems/maximum-sum-of-distinct-subarrays-with-length-k/submissions/869101841/
<img width="960" alt="1-2" src="https://user-images.githubusercontent.com/17985971/210176159-a9407407-6a90-40f9-8c06-9194606ede22.png">

- screenshot 3
<img width="1162" alt="1-3" src="https://user-images.githubusercontent.com/17985971/210176160-1c06f8bb-830e-4e04-842f-c2353bb2d719.png">

- screenshot 4 : https://leetcode.com/problems/maximum-sum-of-distinct-subarrays-with-length-k/submissions/869102407/
<img width="942" alt="1-4" src="https://user-images.githubusercontent.com/17985971/210176157-4e193e49-4d2c-4e5d-a4a8-c3d04ba33060.png">

#### Additional context
After the following modification, it passed the testcase above (screenshot 3), with the submission result 'accepted' (screenshot 4).

from
```
# init (first k elements)
        for i in range(k):
            n = nums[i]
            if pos[n] != -1:
                lb = pos[n]
            pos[n] = i
            sm += n
        mx = sm if lb == -1 else 0
```
to
```
# init (first k elements)
        for i in range(k):
            n = nums[i]
            if pos[n] > lb:
                lb = pos[n]
            pos[n] = i
            sm += n
        mx = sm if lb == -1 else 0
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
