### ISSUE TITLE
Correction of HyperLink in ML Basics Blog

### ISSUE THREAD

**Issue by anurag01a** [LeetCode-Feedback/LeetCode-Feedback#10674]
LeetCode UserName: anurag01a

Following is the blog on: https://leetcode.com/explore/featured/card/machine-learning-101/287/what_is_ml/1620/

![image](https://user-images.githubusercontent.com/53372213/210170381-c3c3955f-8efd-4083-ae61-798863cecf1a.png)

The UnderLined Hyperlink is showing this

![image](https://user-images.githubusercontent.com/53372213/210170402-43b80730-2248-45a4-b22c-0cc50d6b55db.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!

**Comment by anurag01a** [comment]
Welcome :)
