### ISSUE TITLE
Missing Test Case - 66. Plus One

### ISSUE THREAD

**Issue by jayanta-banik** [LeetCode-Feedback/LeetCode-Feedback#10671]
#### LeetCode username
DarkSourceOfCode

#### Category of issue
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution:
    def plusOne(self, digits: List[int]) -> List[int]:
        
        # digits[-1] += 1
        q = 1
        for i in range(len(digits)-1, -1, -1):
            digits[i] += q
            q = digits[i] // 10
            digits[i] %= 10
            if q == 0:
                break
        if q:
            digits = [1] + digits
        return digits
                
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to check the problem. The constraints covered this. We appreciate your support!
