### ISSUE TITLE
Missing Test Case - 2461. Maximum Sum of Distinct Subarrays With Length K

### ISSUE THREAD

**Issue by penguin2** [LeetCode-Feedback/LeetCode-Feedback#10678]
#### Your LeetCode username
sweetpotato2

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A testcase such as 
- nums = [100,1,2,100]
 k = 2

needs to be added to make the following code fail.

#### Code you used for Submit/Run operation

```
class Solution:
    def maximumSubarraySum(self, nums: List[int], k: int) -> int:
        # roll the subarray of length k from the start(left) to the end(right)
        # - tracing sum of the subarray
        # - saving the last seen position of each value

        # last seen position of each value
        pos = [-1]*(max(nums)+1)

        # running sum of the current subarray (length: k)
        sm = 0
        
        # left_bound (lb) is positioned before the start of the current subarray
        # if and only if the current subarray consists of distinct values
        lb = -1

        # init (first k elements)
        for i in range(k):
            n = nums[i]
            if pos[n] > lb:
                lb = pos[n]
            pos[n] = i
            sm += n
        mx = sm if lb == -1 else 0

        # rolling the subarray of length k
        for i in range(k,len(nums)):
            sm += nums[i]-nums[i-k]
            n = nums[i]
            if pos[n] > lb:
                lb = pos[n]
            elif lb <= i-k:
                mx = max(mx,sm)
            pos[n] = i

        return mx 
```
The submission result of the code above was 'accepted'. (screenshot 2)

#### Language used for code
python3

#### Expected behavior

By the testcase above, the code I attached should fail, since the output of the code is 101 while the expected one is 102.
(screenshot 1)

#### Screenshots
- screenshot 1
<img width="1156" alt="2-1" src="https://user-images.githubusercontent.com/17985971/210176609-112a31b3-7bd9-4aad-960b-9acaaf0e4536.png">

- screenshot 2 : https://leetcode.com/problems/maximum-sum-of-distinct-subarrays-with-length-k/submissions/869102620/
<img width="928" alt="2-2" src="https://user-images.githubusercontent.com/17985971/210176611-5fe3d581-9add-47dd-a55d-61d127bca6ac.png">

- screenshot 3
<img width="1161" alt="2-3" src="https://user-images.githubusercontent.com/17985971/210176608-c4cf9942-6814-4516-86a8-fce38219e80a.png">

- screenshot 4 : https://leetcode.com/problems/maximum-sum-of-distinct-subarrays-with-length-k/submissions/869102750/
<img width="920" alt="2-4" src="https://user-images.githubusercontent.com/17985971/210176610-1aad2e44-80bd-46a6-b374-87ec00831833.png">

#### Additional context
After the following modification, it passed the testcase above (screenshot 3), with the submission result 'accepted' (screenshot 4).

from
```
        # rolling the subarray of length k
        for i in range(k,len(nums)):
            sm += nums[i]-nums[i-k]
            n = nums[i]
            if pos[n] > lb:
                lb = pos[n]
            elif lb <= i-k:
                mx = max(mx,sm)
            pos[n] = i
```
to
```
        # rolling the subarray of length k
        for i in range(k,len(nums)):
            sm += nums[i]-nums[i-k]
            n = nums[i]
            if pos[n] > lb:
                lb = pos[n]
            if lb <= i-k:
                mx = max(mx,sm)
            pos[n] = i
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
