### ISSUE TITLE
Missing Test Case - 1055. Shortest Way to Form String

### ISSUE THREAD

**Issue by RohitSgh** [LeetCode-Feedback/LeetCode-Feedback#10679]
### Your LeetCode username

RohitSgh

### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

### Description of the bug

Code gets accepted/[submitted](https://leetcode.com/problems/shortest-way-to-form-string/submissions/869149370/). 

But ideally it shouldn't. It is giving Runtime Error for this Custom Input. Acceptance is because of Weak Test Case.

**source**   
`ac`

**target**   
`bcbc`

### Code you used for Submit/Run operation

```python
class Solution(object):
    def shortestWay(self, source, target):
        """
        :type source: str
        :type target: str
        :rtype: int
        """
        if len(target) == 0:
            return 0
        pos = {}
        for i in range(len(source)):
            if source[i] in pos:
                pos[source[i]].append(i)
            else:
                pos[source[i]] = [i]
        n = len(target)
        dp = [[0, 0] for i in range(n)]
        dp[0][0] = pos[target[0]][0]
        dp[0][1] = 1
        for i in range(1, len(target)):
            if target[i] not in pos:
                return -1
            if pos[target[i]][-1] > dp[i - 1][0]:
                j = self.binary_search(pos[target[i]], dp[i - 1][0])
                dp[i][0] = j
                dp[i][1] = dp[i - 1][1]
            else:
                dp[i][0] = pos[target[i]][0]
                dp[i][1] = dp[i - 1][1] + 1
        
        return dp[n - 1][1]
    
    def binary_search(self, nums, target):
        left, right = 0, len(nums) - 1
        while left <= right:
            mid = left + (right - left) / 2
            if nums[mid] > target:
                ans = nums[mid]
                right = mid - 1
            else:
                left = mid + 1
        return ans
```

### Language used for code

Python

### Expected behavior

**Expected:** Code should not get submitted. This line in code assumes that `target[0]` is always there in `source`, which shouldn't be the case always!

```python
        dp[0][0] = pos[target[0]][0]
```

**Happened:** Code is accepted. Here is the submission
https://leetcode.com/problems/shortest-way-to-form-string/submissions/869149370/

### Screenshots

**Submission and Test Case**
> 
![image](https://user-images.githubusercontent.com/81853910/210177850-4564c166-91d8-4f52-80d8-674865e7703e.png)

**Error on Test Case**
> 
![image](https://user-images.githubusercontent.com/81853910/210177869-e6f8cc7c-8bfb-4c37-982a-9c67b1de9398.png)

### Additional context

Bug is in this line of code. It assumes that `target[0]` is always there in `source`, which shouldn't be the case always!

```python
        dp[0][0] = pos[target[0]][0]
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
