### ISSUE TITLE
Complexity for Java - 290. Word Pattern

### ISSUE THREAD

**Issue by mdes4214** [LeetCode-Feedback/LeetCode-Feedback#10672]
#### Your LeetCode username

mdes4214

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Incorrect time and space complexity for Java implementation in Approach 1

#### Language used for code

Java

#### Expected behavior

For Java implementation, the time and space complexity should be the following
- Time complexity: `O(L)`, where `L` is the length of `s`
  - `String.split()` will call `String.substring()`, thus `String[] words = s.split(" ");` costs `O(L)`
  - `String.equals()` is also a linear time process in most cases, thus `if (!mapped_word.equals(w))` will cost `O(l)`, and the for-loop will cost `O(L)`
- Space cmplexity: `O(M * l)`, where `M` is the number of unique words in `s`, and `l` is the length of word
  - though the character to word hash map has space complexity of `O(1)` in its keys, it still need some spaces to store the values, i.e., the unique words
  - for each word, there will be a `CharArray` in the `String` object, thus it still need `O(l)` for each word, and `O(M * l)` for all unique words

#### Screenshots

![image](https://user-images.githubusercontent.com/9001974/210167293-066c777e-4af1-4e00-8d7f-521a65ad16e1.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
