### ISSUE TITLE
Missing Test Case - 290. Word Pattern

### ISSUE THREAD

**Issue by KalindiFonda** [LeetCode-Feedback/LeetCode-Feedback#10673]
#### Your LeetCode username
kalindifonda

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
For the testcase: 
```
pattern: "abba"
s: "dog cat tac dog"
```
an answer that returns True for this test case is accepted.

#### Code you used for Submit/Run operation

```
class Solution:
    def wordPattern(self, pattern: str, s: str) -> bool:
        words = s.split(" ")
        if len(words) != len(pattern):
            return False

        counts = []
        for word in words:
            counts.append(dict(collections.Counter(word)))

        letters = {}
        used = []
        for i,char in enumerate(pattern):
            if char in letters:
                if letters[char] != counts[i]:
                    return False
            else:
                if counts[i] in used:
                    return False
                letters[char] = counts[i]
                used.append(counts[i])
        return True

```

#### Language used for code
Python

#### Expected behavior

Code should not be accepted.

#### Screenshots

<img width="404" alt="Screenshot 2023-01-01 at 12 07 17" src="https://user-images.githubusercontent.com/9532690/210168491-35630d79-6430-4772-9084-567253271cb8.png">

<img width="200" alt="Screenshot 2023-01-01 at 12 08 53" src="https://user-images.githubusercontent.com/9532690/210168536-b43c53c0-1657-413e-b9f3-5fc1f03123c1.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
