### ISSUE TITLE
Missing Test Case - 290. Word Pattern

### ISSUE THREAD

**Issue by vault-developer** [LeetCode-Feedback/LeetCode-Feedback#10682]
#### Your LeetCode username

https://leetcode.com/vault-developer/

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Code below is accepted, but it gives a wrong output (`false` instead of `true`) with the following testcase:
pattern: `abba`  
s: `dog constructor constructor dog`  

The problem is the usage of hashMap via js Object not via js Map.
`S` may contain any word as we don't have restrictions regrarding it.
JS object has reserved properties like `constuctor`. 
Cheking `if (map['constructor'])` returns `true` every time despite of the fact that 'constructor' word was never saved to the map.

#### Code you used for Submit/Run operation

```
/**
 * @param {string} pattern
 * @param {string} s
 * @return {boolean}
 */
var wordPattern = function(pattern, s) {
   const words = s.split(' ');
   if (pattern.length !== words.length) return false;
   const map = {};

   for (let i=0; i<pattern.length; i++){
       const char = pattern[i];
       const word = words[i];
       if (map[word]) {
           if (map[word] !== char) return false;
       } else {
           map[word] = char;
       }
   } 

   return Object.values(map).length === new Set(Object.values(map)).size;
};
```

#### Language used for code
JavaScript

#### Expected behavior

Mentioned above solution should not be accepted.

#### Screenshots

![image](https://user-images.githubusercontent.com/28157258/210181534-0d9ce725-9511-4135-9a8f-2fc79806c50d.png)
![image](https://user-images.githubusercontent.com/28157258/210181557-2db9f7d0-f95d-4caa-9f59-2d455544ef38.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
