### ISSUE TITLE
Fix the wording/ Add Clear constraints - 507. Perfect Number

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1068]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

507. Perfect Number
https://leetcode.com/problems/perfect-number/

A question should not "collect down votes", by unclear highlight of words, without clear constraints given:
Please see https://leetcode.com/problems/perfect-number/discuss/112193/Why-is-there-negative-num-in-testcases

Please change:
- From: We define the Perfect Number is a positive integer that is equal to the sum of all its positive divisors except itself.
- To:   We define the Perfect Number is a "positive integer" that is equal to the sum of all its "positive integer" divisors except itself.
- Also, Highlight double quote words (both words)

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

A question should not mislead by highlighting the word "positive" times.
A question must have clear Constraints written.

Otherwise, we will have too low an Acceptance Rate (And, so user's are unhappy)

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
