### ISSUE TITLE
Missing Test Case - 521. Longest Uncommon Subsequence I

### ISSUE THREAD

**Issue by gansach** [LeetCode-Feedback/LeetCode-Feedback#10688]
#### Your LeetCode username
gansach

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Solution is getting accepted even though it is wrong. More testcases need to be added.

#### Code you used for Submit/Run operation

```
// Longest Uncommon Subsequence 1
class Solution {
public:
    int findLUSlength(string a, string b) {
        int n = a.size(), m = b.size();
        if (n != m) return max(n, m);

        for(int i = 0; i < n; i++) {
            if (a[i] != b[i]) 
                return n - i;
            if (i == n - 1)
                return -1;
        }
        return 0;
    }
};
```

#### Language used for code
C++

#### Expected behavior

For the testcase:
a = "aaaabcd"
b = "aaaaacd"
The output should be 7, the length of string A (or B), but the output of the above mentioned code is 3. 
The above mentioned code is accepted as a valid solution, but it should not be. So this testcase should be added!

#### Links

https://leetcode.com/problems/longest-uncommon-subsequence-i/submissions/869465455/
This is the solution that got accepted, even though this is wrong.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
