### ISSUE TITLE
Missing Test Case - 118. Pascal's Triangle

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#10685]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
For [118. Pascal's Triangle](https://leetcode.com/problems/pascals-triangle), the range of parameter `numRows` is limited with `1 <= numRows <= 30`, which means there are at most 30 test cases for this problem, which is not a large number.

However, currently there are only 14 test cases for this problem, which is fewer than 30.

Since 30 test cases are not too many, I suggest that all 30 test cases should be added for this problem.

I am not providing any code here. The requirement is simply to add all 30 test cases in the range [1, 30] for this problem.

All test cases should be unique, which means there should be exactly 30 test cases from 1 to 30 and each test case should occur exactly once.

#### Expected behavior
For [118. Pascal's Triangle](https://leetcode.com/problems/pascals-triangle), add all 30 test cases in the range [1, 30].

All test cases should be unique, which means there should be exactly 30 test cases from 1 to 30 and each test case should occur exactly once.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to Updated the test set to include all cases. We appreciate your support!
