### ISSUE TITLE
Missing Test Case - 1328. Break a Palindrome

### ISSUE THREAD

**Issue by Vanbliser** [LeetCode-Feedback/LeetCode-Feedback#10683]
#### Your LeetCode username
Vanblis

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- Missing Test Cases 

#### Description of the bug
I would like to provide some test cases

#### Code you used for Submit/Run operation

```
// Break the palindrome
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

int is_palindrome(char *s)
{
    int len = strlen(s), j = 0;
    char *rev = malloc(sizeof(char) * len + 1);
    for (int i = len - 1; i >= 0; --i, ++j)
        rev[j] = s[i];
    rev[j] = '\0';
    if (strcmp(rev, s) == 0)
        return 1;
    return 0;
}
char *breakPalindrome(char *palindrome){
    char *palim = malloc(sizeof(char) * strlen(palindrome) + 1);
    strcpy(palim, palindrome);
    for (int i = 0; palindrome[i] != '\0'; ++i)
    {
        if (palindrome[i] > 'a')
        {
            palim[i] = 'a';
            if (!is_palindrome(palim))
                return palim;
        }
    }
    char *emp = malloc(sizeof(char) *  1);
    emp[0] = '\0';
    return emp;
}
```

#### Language used for code
C

#### Expected behavior
a=IMPOSSIBLE
b=IMPOSSIBLE
aaa=IMPOSSIBLE
aazaa=IMPOSSIBLE
aczca=aazca
cacac=aacac
mum=aum
acca=aaca
cac=aac
amxma=aaxma
bmxmb=amxmb
mbxbm=abxbm
aaaa=IMPOSSIBLE
abcba=aacba
abzba=aazba
abcba=aacba

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, our judger appears to be running correctly, please feel free to refer the discuss section of the problem to see how other users' have optimized their codes!
