### ISSUE TITLE
Missing Test Case - 520. Detect Capital

### ISSUE THREAD

**Issue by AryadipMridha** [LeetCode-Feedback/LeetCode-Feedback#10691]
#### Your LeetCode username

mearjo1999

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [* ] Missing Test Cases 

#### Description of the bug

No all lowercases word testcase has been given.

#### Code you used for Submit/Run operation

```
class Solution:
    def detectCapitalUse(self, word: str) -> bool:
        return word.isupper() or word.islower() or word.istitle()
```

#### Language used for code

Python3

#### Expected behavior

just add a test case with all low caps like "egg"

**Comment by LC-Pam** [comment]
Test case already exist.
