### ISSUE TITLE
Missing Test Case - 73. Set Matrix Zeroes

### ISSUE THREAD

**Issue by ShrishRajGupta** [LeetCode-Feedback/LeetCode-Feedback#10706]
#### Your LeetCode username 
shrishrajgupta

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
By masking required cells with -1 

#### Code you used for Submit/Run operation
```
class Solution {
public:
    void func(vector<vector<int>> &a,int i,int j){
        int m=a.size();
        int n=a[0].size();
        for(int k=0;k<n;k++){
            if(a[i][k])     // except for zero
            a[i][k]=-1;  //Masking entire row with -1 
        }
        for(int k=0;k<m;k++){
            if(a[k][j])    // except for zero
            a[k][j]=-1;  //Masking entire column with -1 
        }
    }
    void setZeroes(vector<vector<int>>& matrix) {
        int m=matrix.size();
        int n=matrix[0].size();

        if(m==3&&n==1){ // Handling only exceptional case 164 / 165 ->  [ [-1] , [2] , [3] ]
            if(matrix[0][0]==-1 && matrix[1][0]==2 && matrix[2][0]==3)
                return;
        }
        for(int i=0;i<m;i++){
            for(int j=0;j<n;j++){
                if(matrix[i][j]==0)
                    func(matrix,i,j);
            }
        }
        for(int i=0;i<m;i++){
            for(int j=0;j<n;j++){
                if(matrix[i][j]==-1) // turing masked -1 cells to zero
                    matrix[i][j]=0;
            }
        }
    }
};
```

#### Language used for code
C++ 

#### Expected behavior
Wrong answer expected as range is -2^31 to 2^31 - 1

##### Bug testcase with same code

![Screenshot from 2023-01-02 22-08-49](https://user-images.githubusercontent.com/97391054/210259602-c378cc5b-44c7-438a-a272-2116cc4243a1.png)

##### Submitted successfully

![Screenshot from 2023-01-02 22-09-08](https://user-images.githubusercontent.com/97391054/210259718-6459a8e1-3466-4927-8abe-a4cf4dd137a9.png)

#### Additional context
[[-1,1,1],[1,0,1],[1,1,-1]] testcase which failed but code passed

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
