### ISSUE TITLE
Missing Test case - 872. Leaf-Similar Trees

### ISSUE THREAD

**Issue by anurag-jain** [LeetCode-Feedback/LeetCode-Feedback#1070]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

https://leetcode.com/problems/leaf-similar-trees/ has a missing test case. The code below was accepted but if tested with the following test case it gives wrong answer. 

#### Code you used for Submit/Run operation

```
class Solution {
    vector<int> leafNodes;
public:
    void extractLeaves(TreeNode* root)
    {
        if(root == nullptr)
            return;
        extractLeaves(root->left);
        if(root->left == nullptr && root->right == nullptr)
            leafNodes.push_back(root->val);
        extractLeaves(root->right);
        
    }
    
    bool compareLeaves(TreeNode* root, int& pos)
    {
        if(root == nullptr)
            return true;
        
        if(root->left==nullptr && root->right == nullptr)
        {
            return root->val == leafNodes[pos++];
        }
        
        return pos < leafNodes.size() && compareLeaves(root->left, pos) && compareLeaves(root->right, pos);
        
    }
    
    bool leafSimilar(TreeNode* root1, TreeNode* root2) {
        int pos = 0;
        extractLeaves(root1);
        return compareLeaves(root2, pos);
    }
};
```

#### Language used for code

C++

#### Expected behavior

The above code failed for this testcase and since it was missing on the judge above code got accepted. Thus we should add the below-mentioned test case.

**root1 = [3,5,1,6,7,4,2,null,null,null,null,null,null,9,11,null,null,8,10]
root2 = [3,5,1,6,2,9,8,null,null,7,4]**

**Comment by lc-ivan** [comment]
Hi @anurag-jain ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @anurag-jain 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
