### ISSUE TITLE
88. Merge sorted array bug in Dart solution

### ISSUE THREAD

**Issue by janpierry** [LeetCode-Feedback/LeetCode-Feedback#10703]
#### LeetCode username

janpierrycoelho

#### Category of the bug
- [ ] Question
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

I'm new in LeetCode and started a solution to the problem 88. Merge sorted array in Dart. I was receiving an error (Line 7: RangeError (index): Invalid value: Only valid value is 0: -1) with my solution, but I executed the same solution in DartPad and it worked, so there is probably a problem with the dart compiler used in leetcode. I debuged my code and the problem is that when j-- makes j -1, for some reason it enters the while loop again and with j = 0.

#### Code you used for Submit/Run operation

```
// 88. Merge Sorted Array
class Solution {
  void merge(List<int> nums1, int m, List<int> nums2, int n) {
      int i = nums1.length - 1;
      int j = nums2.length - 1;
      while(j >= 0) {
          var a = i - j - 1;
          if (nums2[j] >= nums1[a]) {
              nums1[i] = nums2[j];
              j--;
          } else {
              nums1[i] = nums1[a];
          }
          i--;
      }
  }
}
```

#### Language used for code

Dart

#### Expected behavior

The expected behavior is that when j became -1 it shouldn't become 0 again whitout any statement to do it.

#### Additional context

Result of my debug:
when j = 0 > enters while > enters if > j-- > print(j) == -1 > at end of while still print(j) == -1 > enters while again for some reason(shouldn't) > at start of while print(j) == 0.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by qUneTz** [comment]
```typescript
/**
 Do not return anything, modify nums1 in-place instead.
 */
function merge(nums1: number[], m: number, nums2: number[], n: number): void {
  nums1 = nums1.filter(n => n != 0);

    let n1It: number = m-1;
    let n2It: number = n-1;
   
    while(n1It >= 0 && n2It >= 0){
        
        if(nums2[n2It] >= nums1[n1It]){
            nums1.splice(n1It+1, 0, nums2[n2It]);
            n2It--;
        }else{
            n1It--;
        }
    }
};
``` 
Language: Typescript
New to leetcode as well, experiencing the same problem here!

**Comment by LC-Pam** [comment]
Hi, we appreciate your efforts in tackling the challenge and we wanted to provide some insights into the issue you encountered.

When entering the while loop for the first time with the failed test case, the values of i and j are both 0. Consequently, a becomes -1, leading to an attempt to access nums1[-1], resulting in an error.

To address this, you might want to consider adjusting the initial values of i and j or implementing a check to avoid accessing indices that might lead to errors.

If you have any further questions or if there's anything else I can assist you with, please feel free to reach out. Happy coding!
