### ISSUE TITLE
Missing Test Case - 520. Detect Capital

### ISSUE THREAD

**Issue by a-dilmen** [LeetCode-Feedback/LeetCode-Feedback#10708]
#### Your LeetCode username

a-dilmen

#### Category of the bug
- [520 ] Question
- [ ] Solution
- [Java ] Language
- ["pH" ] Missing Test Cases 

#### Description of the bug

Eventhough first letter is not capital and second letter capital I saw many posted solutions that would fail with such test case the  missing test case is not fitting the description but passing the test . Could be better if you would like to add. Alltough my solution is in java same test apllies to other languages as well, thanks for the good work

#### Code you used for Submit/Run operation

"
class Solution {
	public boolean detectCapitalUse(String word) {
// this if block does not fit the problem description but solution gets accepted adding a test case 'eA' would deny faulty pass       
if (word.length()<2){ 
            return true;
        }
// rest is regular solution to the problem not relevant with the test case only added since the comment definition asks for
		try {
		if (word.charAt(0) < 91) {
			if (word.charAt(1) < 91) {
				for (int i = 2; i < word.length(); i++) {
					if (word.charAt(i) > 91) {
						return false;
					}
				}
			}
			if (word.charAt(1)>91) {
				for (int i = 2; i < word.length(); i++) {
					if (word.charAt(i) < 91) {
						return false;
					}
				}
			}
		}} catch (Exception e) {
			return true;
		}
		if (word.charAt(0)>91) {
			for (int i = 1; i < word.length(); i++) {
				if (word.charAt(i) < 91) {
					return false;
				}
			}
		}

		return true;
	}
}"

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submit link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by a-dilmen** [comment]
Hello, here are two submission links and the question definition that are
added below.
At , first link the code is written checking the missing test case that is
first letter not capital and second letter capital such as "aE".
The second link code is not checking such test case but still passes many
solutions in the from disregards this scenario.

https://leetcode.com/problems/detect-capital/submissions/869853039/
https://leetcode.com/problems/detect-capital/submissions/869855803/

We define the usage of capitals in a word to be right when one of the
following cases holds:

   - All letters in this word are capitals, like "USA".
   - All letters in this word are not capitals, like "leetcode".
   - Only the first letter in this word is capital, like "Google".

Given a string word, return true if the usage of capitals in it is right.

Have a nice day,

Abdulkadir Dilmen

LC_M ***@***.***>, 4 Oca 2023 Çar, 06:44 tarihinde şunu yazdı:

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. Both solutions look good, ticket rejected. We appreciate your support!
