### ISSUE TITLE
Missing Test Case - 2522. Partition String Into Substrings With Values at Most K

### ISSUE THREAD

**Issue by Ashu259** [LeetCode-Feedback/LeetCode-Feedback#10702]
#### Your LeetCode username

ashu0123

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

This code is being accepted as a solution but it should be rejected because it gives the wrong answer in a test case specified below.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int minimumPartition(string s, int k) 
    {
        int n = s.size();
        long long currNum = 0;
        long long prevNum = -1;
        int ans = 0;
        for (int i = 0; i < n; i++)
        {
            prevNum = currNum;
            currNum = (currNum * 10) + (s[i] - '0');
            //=======================================================
            if (currNum <= k) continue;
            else if (currNum > k)
            {
                if (prevNum > k) return -1;
                ans++;
                currNum = (s[i] - '0');
            }  
            //========================================================
        }
        return (ans + 1);
        
    }
};
```

#### Language used for code

C++

#### Expected behavior

Code got accepted but it fails to give correct answer when we pass--
s = "12456"
k = 5

#### Screenshots

![Screenshot 2023-01-02 202445](https://user-images.githubusercontent.com/76205356/210248157-65aaa62d-fbd1-4694-96cb-1c8975b4374b.png)
![Screenshot 2023-01-02 202341](https://user-images.githubusercontent.com/76205356/210248169-1c18c6ad-beb7-4b71-ae99-5991fb3e8a28.png)

#### Additional context

Just add the above-mentioned test case in the expected behavior section to the problem.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
