### ISSUE TITLE
944: Delete Columns to Make Sorted - code executing more than once

### ISSUE THREAD

**Issue by AskInward** [LeetCode-Feedback/LeetCode-Feedback#10714]
#### Your LeetCode username
user6667gx (Ajay S)

#### Category of the bug
- [ ] Issue with python3 execution environment

#### Description of the bug
Code outside of loop runs more than once

#### Code you used for Submit/Run operation

```
class Solution:

    def minDeletionSize(self,strs):
        
        print('starting program')
        for i in range(len(strs)):
            col=None
            for s in strs:                
                print(f'i:{i} string col:{s[i]}')                
           
        return 0
```

#### Language used for code
python3 

#### Expected behavior
The line 'starting program' is added to demonstrate the issue. It should be executed only once for the lifecycle of the program.

####Expected output
```
starting program
i:0 string col:c
i:0 string col:d
i:0 string col:g
i:1 string col:b
i:1 string col:a
i:1 string col:h
i:2 string col:a
i:2 string col:f
i:2 string col:i
```

#### Actual behaviour
The code seems to be running twice.

#### Actual output
```
starting program
i:0 string col:c
i:0 string col:d
i:0 string col:g
i:1 string col:b
i:1 string col:a
i:1 string col:h
i:2 string col:a
i:2 string col:f
i:2 string col:i
starting program
i:0 string col:a
i:0 string col:b
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The code does not run twice.  We appreciate your support!
