### ISSUE TITLE
Time complexity issues in Zero and one loss problem

### ISSUE THREAD

**Issue by Chetanparsiya** [LeetCode-Feedback/LeetCode-Feedback#10710]
#### Your LeetCode username

chetan_parsiya
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

This is the 3rd solution of the Problem [Zero or 1 Loss](https://leetcode.com/problems/find-players-with-zero-or-one-losses/solutions/). When i checked the time complexity it states that the complexity is O(n+k).But if anyone carefully look into the code the the admin had just ignored the time complexity of 1e6+1 operations which is quite a big number and cannot considered as O(1) . Similar situations is for space complexity also. Admin can you please look into it and correct the solutions. Or let me know if misunderstood something.

#### Code you used for Submit/Run operation

```
//Zero or 1 Loss
class Solution {
public:
    vector<vector<int>> findWinners(vector<vector<int>>& matches) {
        vector<int> lossesCount(100001, -1);

        for (auto& match : matches) {
            int winner = match[0], loser = match[1];
            if (lossesCount[winner] == -1) {
                lossesCount[winner] = 0;
            }
            if (lossesCount[loser] == -1) {
                lossesCount[loser] = 1;
            } else {
                lossesCount[loser]++;
            }
        }

        vector<vector<int>> answer(2, vector<int>());
        for (int i = 1; i < 100001; ++i) {
            if (lossesCount[i] == 0) {
                answer[0].push_back(i);
            } else if (lossesCount[i] == 1) {
                answer[1].push_back(i);
            }
        }

        return answer;
```

#### Expected behavior

The time and space complexity will be O(n+n) not O(n+k)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The 1e6+1 is not considered O(1), it is by definition O(k) as stated in the time complexity analysis. We appreciate your support!
