### ISSUE TITLE
Wrong description and example in 944. Delete Columns to Make Sorted

### ISSUE THREAD

**Issue by Aatom003** [LeetCode-Feedback/LeetCode-Feedback#10718]
#### Your LeetCode username
Anind

#### Category of the bug
- [ ] Question

#### Description of the bug

In the example given in description, their string is **cae** which should be **cee** instead as we can see in explanation in next paragraph

#### Expected behavior

In the example given in description, their string is **cae** which should be **cee** instead as we can see in explanation in next paragraph

#### Screenshots

<img width="429" alt="Screenshot 2023-01-03 at 12 03 18 PM" src="https://user-images.githubusercontent.com/35699578/210309669-371d5f7d-4487-41d3-9d8a-c3ccd733c068.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The statement mentioned columns and not rows. The 2nd column indeed has cee. We appreciate your support!
