### ISSUE TITLE
Missing Test Case - 850. Rectangle Area II

### ISSUE THREAD

**Issue by Justin-YimYim** [LeetCode-Feedback/LeetCode-Feedback#10713]
#### Your LeetCode username

[doppelgangerOfMeow](https://leetcode.com/doppelgangerOfMeow/)

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior

If x2 <= x1, the answer return 0. But rectangle could be drawn when every time x1 != x2. 

#### Screenshots

<img width="659" alt="Screenshot 2023-01-03 at 12 01 46" src="https://user-images.githubusercontent.com/55522706/210298599-44af69e8-5945-46ac-8c37-5b32450502d3.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Justin-YimYim** [comment]
Emm, i don't think it is about the code. It is more about the input and output size undefined behavior.

**Comment by Justin-YimYim** [comment]
typedef struct SegmentTree2dSumWithSkippingLeavePropagate{
    vector<vector<int>> count;
    vector<vector<bool>> lazyTag;
    unordered_map<long, long> dictX, dictXr, dictY, dictYr;
    int mod;
    SegmentTree2dSumWithSkippingLeavePropagate(int n, int m): count(4 * n, vector<int>(4 * m)), mod(1e9 + 7), lazyTag(4 * n, vector<bool>(4 * m, false)){}

    void propogateRoot(int vertexX, int vertexY){
        if (vertexX == 0 && vertexY == 0) return;
        int vertexXComp = (vertexX % 2? vertexX + 1: vertexX - 1);
        int vertexYComp = (vertexY % 2? vertexY + 1: vertexY - 1);
        int a(count[vertexX][vertexY]), b(count[vertexX][vertexYComp]), c(count[vertexXComp][vertexY]), d(count[vertexXComp][vertexYComp]);
        vertexX = (vertexX - 1) / 2;
        vertexY = (vertexY - 1) / 2;
        // cout << a << " " << b << " " << c << " " << d << endl;
        if (!lazyTag[vertexX][vertexY]) count[vertexX][vertexY] = (((a + b) % mod + c) % mod + d) % mod;
        propogateRoot(vertexX, vertexY);
    }

    void modify(int x1, int x2, int y1, int y2, int X1, int X2, int Y1, int Y2, int vertexX, int vertexY){
        // cout << x1 << " " << x2 << " " << y1 << ' ' << y2 << endl;
        // cout << X1 << " " << X2 << " " << Y1 << " " << Y2 << endl;
        // cout << vertexX << " " << vertexY << endl;
        if (x1 == X1 && x2 == X2 && y1 == Y1 && y2 == Y2){
            long xRange = (x1 == x2? dictXr[x1 + 1] - dictXr[x1]: dictXr[x2 + 1] - dictXr[x1]);
            long yRange = (y1 == y2? dictYr[y1 + 1] - dictYr[y1]: dictYr[y2 + 1] - dictYr[y1]);
            count[vertexX][vertexY] = (xRange * yRange) % mod;
            lazyTag[vertexX][vertexY] = true;
            propogateRoot(vertexX, vertexY);
            return;
        }
        // cout << "asdf" << endl;
        int midX((X1 + X2) / 2), midY((Y1 + Y2) / 2);
        if (midX < x1){
            if (midY < y1){
                modify(x1, x2, y1, y2, midX + 1, X2, midY + 1, Y2, vertexX * 2 + 2, vertexY * 2 + 2);
            }else if (midY >= y2){
                modify(x1, x2, y1, y2, midX + 1, X2, Y1, midY, vertexX * 2 + 2, vertexY * 2 + 1);
            }else{
                modify(x1, x2, y1, midY, midX + 1, X2, Y1, midY, vertexX * 2 + 2, vertexY * 2 + 1);
                modify(x1, x2, midY + 1, y2, midX + 1, X2, midY + 1, Y2, vertexX * 2 + 2, vertexY *2 + 2);
            }
        }
        else if (midX >= x2){
            if (midY < y1){
                modify(x1, x2, y1, y2, X1, midX, midY + 1, Y2, vertexX * 2 + 1, vertexY * 2 + 2);
            }else if (midY >= y2){
                modify(x1, x2, y1, y2, X1, midX, Y1, midY, vertexX * 2 + 1, vertexY * 2 + 1);
            }else{
                modify(x1, x2, y1, midY, X1, midX, Y1, midY, vertexX * 2 + 1, vertexY * 2 + 1);
                modify(x1, x2, midY + 1, y2, X1, midX, midY + 1, Y2, vertexX * 2 + 1, vertexY *2 + 2);
            }
        }
        else{
            if (midY < y1){
                modify(x1, midX, y1, y2, X1, midX, midY + 1, Y2, vertexX * 2 + 1, vertexY * 2 + 2);
                modify(midX + 1, x2, y1, y2, midX + 1, X2, midY + 1, Y2, vertexX * 2 + 2, vertexY * 2 + 2);
            }else if (midY >= y2){
                modify(x1, midX, y1, y2,  X1, midX, Y1, midY, vertexX * 2 + 1, vertexY * 2 + 1);
                modify(midX + 1, x2, y1, y2, midX + 1, X2, Y1, midY, vertexX * 2 + 2, vertexY * 2 + 1);
            }else{
                modify(midX + 1, x2, y1, midY, midX + 1, X2, Y1, midY, vertexX * 2 + 2, vertexY * 2 + 1);
                modify(x1, midX, midY + 1, y2, X1, midX, midY + 1, Y2, vertexX * 2 + 1, vertexY *2 + 2);
                modify(midX + 1, x2, midY + 1, y2, midX + 1, X2, midY + 1, Y2, vertexX * 2 + 2, vertexY * 2 + 2);
                modify(x1, midX, y1, midY, X1, midX, Y1, midY, vertexX * 2 + 1, vertexY * 2 + 1);
            }
        }
    }

} SegmentTree;

class Solution {
public:
    int rectangleArea(vector<vector<int>>& rectangles) {
        set<int> xSet, ySet;
        for (auto &rect: rectangles){
            if (rect[0] >= rect[2] || rect[1] >= rect[3]) continue;
            xSet.insert(rect[0]);
            ySet.insert(rect[1]);
            xSet.insert(rect[2]);
            ySet.insert(rect[3]);
        }
        if (xSet.size() == 0 || ySet.size() == 0) return 0;
        SegmentTree segTree(500, 500);
        cout << segTree.count.size() << " " << segTree.count[1].size() << endl;
        int i(1), j(1);
        for (auto &a: xSet){
            segTree.dictX[a] = i;
            segTree.dictXr[i] = a;
            i++;
        }
        for (auto &a: ySet){
            segTree.dictY[a] = j;
            segTree.dictYr[j] = a;
            j++;
        }
        for (auto &rect: rectangles){
            if (rect[0] >= rect[2] || rect[1] >= rect[3]) continue;
            // cout << rect[1] << " " << rect[3] - 1 << endl;
            segTree.modify(segTree.dictX[rect[0]], segTree.dictX[rect[2] ] - 1, segTree.dictY[rect[1]], segTree.dictY[rect[3]] - 1, 1, xSet.size(), 1, ySet.size(), 0, 0);
            // cout << segTree.count[0][0] << endl;
            // for (auto &a: segTree.count) {for (auto &b : a) cout << b << " "; cout << endl;}
        }
        
        return segTree.count[0][0];
    }
};

**Comment by Justin-YimYim** [comment]
```
typedef struct SegmentTree2dSumWithSkippingLeavePropagate{
    vector<vector<int>> count;
    vector<vector<bool>> lazyTag;
    unordered_map<long, long> dictX, dictXr, dictY, dictYr;
    int mod;
    SegmentTree2dSumWithSkippingLeavePropagate(int n, int m): count(4 * n, vector<int>(4 * m)), mod(1e9 + 7), lazyTag(4 * n, vector<bool>(4 * m, false)){}

    void propogateRoot(int vertexX, int vertexY){
        if (vertexX == 0 && vertexY == 0) return;
        int vertexXComp = (vertexX % 2? vertexX + 1: vertexX - 1);
        int vertexYComp = (vertexY % 2? vertexY + 1: vertexY - 1);
        int a(count[vertexX][vertexY]), b(count[vertexX][vertexYComp]), c(count[vertexXComp][vertexY]), d(count[vertexXComp][vertexYComp]);
        vertexX = (vertexX - 1) / 2;
        vertexY = (vertexY - 1) / 2;
        // cout << a << " " << b << " " << c << " " << d << endl;
        if (!lazyTag[vertexX][vertexY]) count[vertexX][vertexY] = (((a + b) % mod + c) % mod + d) % mod;
        propogateRoot(vertexX, vertexY);
    }

    void modify(int x1, int x2, int y1, int y2, int X1, int X2, int Y1, int Y2, int vertexX, int vertexY){
        // cout << x1 << " " << x2 << " " << y1 << ' ' << y2 << endl;
        // cout << X1 << " " << X2 << " " << Y1 << " " << Y2 << endl;
        // cout << vertexX << " " << vertexY << endl;
        if (x1 == X1 && x2 == X2 && y1 == Y1 && y2 == Y2){
            long xRange = (x1 == x2? dictXr[x1 + 1] - dictXr[x1]: dictXr[x2 + 1] - dictXr[x1]);
            long yRange = (y1 == y2? dictYr[y1 + 1] - dictYr[y1]: dictYr[y2 + 1] - dictYr[y1]);
            count[vertexX][vertexY] = (xRange * yRange) % mod;
            lazyTag[vertexX][vertexY] = true;
            propogateRoot(vertexX, vertexY);
            return;
        }
        // cout << "asdf" << endl;
        int midX((X1 + X2) / 2), midY((Y1 + Y2) / 2);
        if (midX < x1){
            if (midY < y1){
                modify(x1, x2, y1, y2, midX + 1, X2, midY + 1, Y2, vertexX * 2 + 2, vertexY * 2 + 2);
            }else if (midY >= y2){
                modify(x1, x2, y1, y2, midX + 1, X2, Y1, midY, vertexX * 2 + 2, vertexY * 2 + 1);
            }else{
                modify(x1, x2, y1, midY, midX + 1, X2, Y1, midY, vertexX * 2 + 2, vertexY * 2 + 1);
                modify(x1, x2, midY + 1, y2, midX + 1, X2, midY + 1, Y2, vertexX * 2 + 2, vertexY *2 + 2);
            }
        }
        else if (midX >= x2){
            if (midY < y1){
                modify(x1, x2, y1, y2, X1, midX, midY + 1, Y2, vertexX * 2 + 1, vertexY * 2 + 2);
            }else if (midY >= y2){
                modify(x1, x2, y1, y2, X1, midX, Y1, midY, vertexX * 2 + 1, vertexY * 2 + 1);
            }else{
                modify(x1, x2, y1, midY, X1, midX, Y1, midY, vertexX * 2 + 1, vertexY * 2 + 1);
                modify(x1, x2, midY + 1, y2, X1, midX, midY + 1, Y2, vertexX * 2 + 1, vertexY *2 + 2);
            }
        }
        else{
            if (midY < y1){
                modify(x1, midX, y1, y2, X1, midX, midY + 1, Y2, vertexX * 2 + 1, vertexY * 2 + 2);
                modify(midX + 1, x2, y1, y2, midX + 1, X2, midY + 1, Y2, vertexX * 2 + 2, vertexY * 2 + 2);
            }else if (midY >= y2){
                modify(x1, midX, y1, y2,  X1, midX, Y1, midY, vertexX * 2 + 1, vertexY * 2 + 1);
                modify(midX + 1, x2, y1, y2, midX + 1, X2, Y1, midY, vertexX * 2 + 2, vertexY * 2 + 1);
            }else{
                modify(midX + 1, x2, y1, midY, midX + 1, X2, Y1, midY, vertexX * 2 + 2, vertexY * 2 + 1);
                modify(x1, midX, midY + 1, y2, X1, midX, midY + 1, Y2, vertexX * 2 + 1, vertexY *2 + 2);
                modify(midX + 1, x2, midY + 1, y2, midX + 1, X2, midY + 1, Y2, vertexX * 2 + 2, vertexY * 2 + 2);
                modify(x1, midX, y1, midY, X1, midX, Y1, midY, vertexX * 2 + 1, vertexY * 2 + 1);
            }
        }
    }

} SegmentTree;

class Solution {
public:
    int rectangleArea(vector<vector<int>>& rectangles) {
        set<int> xSet, ySet;
        for (auto &rect: rectangles){
            if (rect[0] >= rect[2] || rect[1] >= rect[3]) continue;
            xSet.insert(rect[0]);
            ySet.insert(rect[1]);
            xSet.insert(rect[2]);
            ySet.insert(rect[3]);
        }
        if (xSet.size() == 0 || ySet.size() == 0) return 0;
        SegmentTree segTree(500, 500);
        cout << segTree.count.size() << " " << segTree.count[1].size() << endl;
        int i(1), j(1);
        for (auto &a: xSet){
            segTree.dictX[a] = i;
            segTree.dictXr[i] = a;
            i++;
        }
        for (auto &a: ySet){
            segTree.dictY[a] = j;
            segTree.dictYr[j] = a;
            j++;
        }
        for (auto &rect: rectangles){
            if (rect[0] >= rect[2] || rect[1] >= rect[3]) continue;
            // cout << rect[1] << " " << rect[3] - 1 << endl;
            segTree.modify(segTree.dictX[rect[0]], segTree.dictX[rect[2] ] - 1, segTree.dictY[rect[1]], segTree.dictY[rect[3]] - 1, 1, xSet.size(), 1, ySet.size(), 0, 0);
            // cout << segTree.count[0][0] << endl;
            // for (auto &a: segTree.count) {for (auto &b : a) cout << b << " "; cout << endl;}
        }
        
        return segTree.count[0][0];
    }
};
```

**Comment by Justin-YimYim** [comment]
```
class Solution {
public:
    int rectangleArea(vector<vector<int>>& rectangles) {
        return 0;
    }
};
```

**Comment by Justin-YimYim** [comment]
Both could result the this output problem.

**Comment by Justin-YimYim** [comment]
To sum up with my other comments #10712 . There are three problem of input set. 
(1) Undefined behavior if x1 == x2 or y1 == y2. There should not be rectangle, the output could not return value in this case. 
(2) Undefined behavior if x2 > x1 or y2 > y1. This could draw rectangle with side, but should it be positive, negative or what is undefinded. The output return 0 for this case. 
(3) It will written "Accepted" in the result but the the test case is in green color. 

<img width="692" alt="Screenshot 2023-01-04 at 12 45 22" src="https://user-images.githubusercontent.com/55522706/210486180-4eb92a0e-acb1-427e-a140-5dd0722727a5.png">
<img width="692" alt="Screenshot 2023-01-04 at 12 45 32" src="https://user-images.githubusercontent.com/55522706/210486200-149b2135-614a-4331-aeee-1f27dd1eb90d.png">

**Comment by Justin-YimYim** [comment]
Another example. 

<img width="692" alt="Screenshot 2023-01-04 at 12 49 33" src="https://user-images.githubusercontent.com/55522706/210486530-a089da7c-fda6-4752-a1fb-3dc1a048f1ad.png">

**Comment by Justin-YimYim** [comment]
Thank you for your reply.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The  language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
