### ISSUE TITLE
Incorrect Question Category - 1161. Maximum Level Sum of a Binary Tree

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1071]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

1161. Maximum Level Sum of a Binary Tree
https://leetcode.com/problems/maximum-level-sum-of-a-binary-tree/

- The "Related Topics" is given as "Graph"
- Please remove "Graph" & add "Tree" as the topic for this question.

I searched and found a related post - https://leetcode.com/problems/maximum-level-sum-of-a-binary-tree/discuss/536874/why-labeled-graph-instead-of-tree

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

When I search for "Tags" as "Graph"  at https://leetcode.com/problemset/algorithms/?topicSlugs=graph
I should only see Graph related questions, not tree-related questions

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
