### ISSUE TITLE
Wrong description Delete Columns to Make Sorted

### ISSUE THREAD

**Issue by ansa-sequence** [LeetCode-Feedback/LeetCode-Feedback#10724]
#### Your LeetCode username
ansa_sequence

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The description says that we have an array of : 
"abc,cbe,cae", but when the same array is used in the example, the last element of the array turns into "cee"

#### Expected behavior
No inaccuracies in the description

#### Screenshots
![image](https://user-images.githubusercontent.com/85295419/210322583-520d34bf-7502-4045-b7fd-81dae7ef7285.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The statement mentioned columns and not rows. The 2nd column indeed has cee. We appreciate your support!
