### ISSUE TITLE
Missing Test Case - 744. Find Smallest Letter Greater Than Target

### ISSUE THREAD

**Issue by abhishek423** [LeetCode-Feedback/LeetCode-Feedback#10727]
#### LeetCode username
[abhishek423](https://leetcode.com/abhishek423/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Adding a Test case where target element falls in between array but element doesn't present in array.

For example: 
Array = ["c","f","j"]
Target = "d"
Expected Output = "f"

#### Screenshots

![LeetCode_744_MissingTestCase](https://user-images.githubusercontent.com/23099644/210352991-79c04025-4902-4b7e-b656-b89f00096b04.png)

#### Additional context
This is a suggestion, if can be added, then can ease the user to understand the usecase and as it's mandatory to pass for the solution.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by abhishek423** [comment]
#### Language:
Java


#### Code:

`class Solution {`

    public char nextGreatestLetter(char[] letters, char target) {
        
        int start = 0;
        int end = letters.length-1;
        int mid = (start+end) / 2;
        int targetAscii = target;
        
        //Get the target
        while(start<=end) {
            int elemAscii = letters[mid];

            if (targetAscii < elemAscii) {
               end = mid - 1;
               mid = (start+end) / 2;
            } else {
               start = mid + 1;
               mid = (start+end) / 2;
            }
        }

        //Get Next Greatest
        int resAscii = letters[mid];
        
        if (resAscii < targetAscii) {
            if (mid < letters.length-1) {
                return letters[mid+1];
            } else {
                return letters[0];
            }
        } else {
            while(resAscii == targetAscii) {
                mid = mid+1;
                if (mid >= letters.length) {
                    return letters[0];
                }
                resAscii = letters[mid];
            }
        }
        
        return letters[mid];
    }
`}`

@LC-Pam, updated the requested details. Please let me know if any more information is required.

**Comment by LC-Pam** [comment]
Hi, thank you for your reply. We received compile error when we submit your code. Would you mind send us your submit AC link?
Thank you.

**Comment by abhishek423** [comment]
@LC-Pam , I assume, by "**submit AC link**" you are referring the submission link for that solution from my end.

Please find below and let me know if any other needed:

[Submission Link](https://leetcode.com/problems/find-smallest-letter-greater-than-target/submissions/870399657/)

**Comment by LC-Pam** [comment]
![Screen Shot 2023-01-07 at 10 36 39 AM](https://user-images.githubusercontent.com/103138242/211158640-6661f89f-d2ae-40b3-806c-8781acc4a356.png)
