### ISSUE TITLE
Missing Question Category - 797. All Paths From Source to Target

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1072]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

797. All Paths From Source to Target
https://leetcode.com/problems/all-paths-from-source-to-target/

Now I solve mainly using Tags-wise.

I remember solving 1 question using Graph
but I could not find it using the "Tags" as "Graph" at https://leetcode.com/problemset/algorithms/?topicSlugs=graph

After searching some time, found that it is 797 problem, the link given above.
This question 797 is not tagged.

Please add "Related Topics" as Graph, to make sure it is found when searched for "Graph" under "Tags"

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

User should find his solved question when using the right Tag. See above for details.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
