### ISSUE TITLE
Missing Test Case - 290. Word Pattern

### ISSUE THREAD

**Issue by Rishabh-Singh-Codes** [LeetCode-Feedback/LeetCode-Feedback#10720]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Adding one more test case for this problem. If pattern = 'dog' and s = 'aba'.

#### Language used for code

JavaScript

#### Expected behavior

The function should return false for the above test case.

**Comment by Rishabh-Singh-Codes** [comment]
Please check the test case for this question.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Rishabh-Singh-Codes** [comment]
Hey @LC-Pam, thank you for reply. On further notice, the testcase which I mentioned above is covered already. Therefore, I'm closing this issue.
