### ISSUE TITLE
Possible small improvement in official solution for detect-capital problem

### ISSUE THREAD

**Issue by b10s** [LeetCode-Feedback/LeetCode-Feedback#10725]
#### Your LeetCode username
b10s

#### Category of the bug
- [ ] Solution

#### Description of the bug
https://leetcode.com/problems/detect-capital/solutions/728399/detect-capital/

Thank you for the explanation.
Why wouldn't you put break after line 29 in char by char solution in Python for case3 as you did for cases 1 and 2?

You put break in Java solution in all three cases but not in Python. Is there any reason?

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
