### ISSUE TITLE
944. Delete Columns to Make Sorted Sample Test case error

### ISSUE THREAD

**Issue by AdityaSai2004** [LeetCode-Feedback/LeetCode-Feedback#10734]
#### Category of the bug
- [ ] Question
- [ ✅] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the explanation of the question the description contains a testcase which has a typo which makes understanding the question a bit difficult. It has BCE in one place and BCA in another. Similarly it has CEE in one place and CAE in another
![image](https://user-images.githubusercontent.com/34617625/210391725-5a83621f-578a-4994-9586-efb2d0f34c29.png)

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

![image](https://user-images.githubusercontent.com/34617625/210391994-3206b33b-db6e-4065-8df1-c1542c139b18.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The statement mentioned columns and not rows. The 2nd column indeed has cee. We appreciate your support!
