### ISSUE TITLE
Missing Test Case - 234. Palindrome Linked List

### ISSUE THREAD

**Issue by julianmzr** [LeetCode-Feedback/LeetCode-Feedback#10739]
#### Your LeetCode username
julsmzr

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
Test cases do not cover uneven lengths of palindromes.

#### Expected behavior
Testcase (e.g. 1,2,1,3,1,2,1) should be added

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.
Then we will consider to add this test case or not and test it.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, we cannot add this test case without any code to test them, sorry about that.
