### ISSUE TITLE
Video playback problem

### ISSUE THREAD

**Issue by SRDMoss** [LeetCode-Feedback/LeetCode-Feedback#10733]
#### Your LeetCode username
SMoss

#### Category of the bug
Video issue in the guides.

#### Description of the bug
All of the videos on the site say "Sorry Because of its privacy settings, this video cannot be played here." 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots
![image](https://user-images.githubusercontent.com/121702887/210382555-f74d080f-fc05-428c-b7af-03c15f49a883.png)

#### Additional context
I commented on another thread about this, but it was closed as if solved. But, I am still experiencing this issue.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The video page links.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment]
![Screen Shot 2023-01-04 at 2 28 02 PM](https://user-images.githubusercontent.com/103138242/210634007-348ea1f0-6b0e-494a-80d5-5e1116413226.png)

**Comment by LC-Pam** [comment]
![Screen Shot 2023-01-04 at 2 28 35 PM](https://user-images.githubusercontent.com/103138242/210634089-6a1a1336-0735-4887-89d3-90ea268c4496.png)

**Comment by LC-Pam** [comment]
![Screen Shot 2023-01-04 at 2 29 34 PM](https://user-images.githubusercontent.com/103138242/210634254-76412060-1aa0-46e9-9450-dd5ad6e42650.png)

**Comment by LC-Pam** [comment]
All the videos work correctly on the website.

**Comment by SRDMoss** [comment]
This is what it looks like when I go to [https://leetcode.com/problems/merge-two-sorted-lists/solutions/127763/merge-two-sorted-lists/](url)

![image](https://user-images.githubusercontent.com/121702887/210824285-881552ed-b1f7-467e-9ae4-8d4401e6b748.png)

**Comment by LC-Pam** [comment]
![Screen Shot 2023-01-07 at 10 38 34 AM](https://user-images.githubusercontent.com/103138242/211158703-f40dd259-bde7-4ec9-ae0b-945fbd2d4bd2.png)

**Comment by LC-Pam** [comment]
The video can play on the website. Both on new and old vision.

**Comment by LC-Pam** [comment]
![Screen Shot 2023-01-07 at 10 39 40 AM](https://user-images.githubusercontent.com/103138242/211158756-ce0e90d0-0938-4f79-886c-514b0981a916.png)
