### ISSUE TITLE
1392. Longest Happy Prefix

### ISSUE THREAD

**Issue by Shashank3736** [LeetCode-Feedback/LeetCode-Feedback#10736]
#### Your LeetCode username

Shashank3736

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My code should not pass the submission. As it failed one custom testcase.

#### Code you used for Submit/Run operation

```py
class Solution:
    def longestPrefix(self, s: str) -> str:
        n = len(s)
        if n == 1:
            return ''
        if n == 2:
            return s[0]
        dp = [0] * n
        for i in range(1, n):
            j = dp[i - 1]
            while j > 0 and s[i] != s[j]:
                j = dp[j - 1]
            if s[i] == s[j]:
                j += 1
            dp[i] = j
        return s[:dp[n - 1]]
```

#### Language used for code

Python3

#### Expected behavior

For testcase `ab` this code fails. But still submission is accepted.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by Shashank3736** [comment]
Any update on this?

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
