### ISSUE TITLE
Missing Test Case - 169. Majority Element

### ISSUE THREAD

**Issue by el-profesor-04** [LeetCode-Feedback/LeetCode-Feedback#10742]
#### Your LeetCode username

[el-profesor]

#### Category of the bug
- [*] Missing Test Cases 

#### Description of the bug

The question is missing a test case, as my solution was accepted but it is not working on my custom test case.

#### Code you used for Submit/Run operation

```
class Solution:
    def majorityElement(self, nums: List[int]) -> int:
        n = len(nums)
        j=1
        for i in range(1,(n//2)+1):
            if nums[i]!=nums[i-1]:
                nums[i],nums[n-j]=nums[n-j],nums[i]
                j+=1
        print(nums)
        num = nums[0]
        ct = 1
        mct = 0
        num_m = nums[0]
        for i in range(1,n):
            if num!=nums[i]:
                if ct>mct:
                    mct=ct
                    num_m = num
                    num=nums[i]
                    ct=1
                else:
                    num=nums[i]
                    ct=1
            else:
                ct+=1
        if ct>mct:
            num_m=nums[-1]
        return num_m
```

#### Language used for code

Python3

#### Expected behavior

Wrong Answer - Expected, but the submission was accepted.

#### Screenshots

![Screen Shot 2023-01-03 at 19 48 01](https://user-images.githubusercontent.com/56555663/210469671-35ce7e7c-373c-48a5-bf66-969fbebc0ea1.png)
![Screen Shot 2023-01-03 at 19 48 43](https://user-images.githubusercontent.com/56555663/210469749-bb2f098d-975d-40bd-b1c1-768c30b650da.png)

#### Additional context

Following is the test case that resulted in a wrong answer.
nums = [1,3,1,1,4,1,1,5,1,1,2,2,2]

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
