### ISSUE TITLE
Code posting in solution python3

### ISSUE THREAD

**Issue by abcsumitsingh** [LeetCode-Feedback/LeetCode-Feedback#10749]
#### Category of the bug
- [ ] Question
- [ √] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### while posting solution in python3 integer division(//) is being read as comment. 

```from collections import deque
def hashword(word):
    h=0
    c=1
    for i in word:
        h+=c*(ord(i)-97)
        c=c*26
    return h
class Solution:
    def ladderLength(self, beginWord: str, endWord: str, wordList: List[str]) -> int:
        d={}
        for i in range(len(wordList)):
            d[hashword(wordList[i])]=0
        h=hashword(beginWord)
        q=deque()
        q.append(h)
        f=hashword(endWord)
        q=deque()
        q.append([h,1])
        if h in d:
            d[h]=1
        while q:
            x=q.popleft()
            h=x[0]
            ans=x[1]
            if h==f:
                return ans
            c=1
            for i in range(10):
                for j in range(26):
                    y=h-(((h%(c*26))//c)*c)+(c*j)
                    if y in d:
                        if d[y]==0:
                            d[y]=1
                            q.append([y,ans+1])
                c=c*26
        return 0



            

```

#### Screenshot
![Screenshot_2023-01-04-11-53-00-440_com android chrome](https://user-images.githubusercontent.com/76198431/210497084-cee206d1-e67a-42f6-8039-351643aa8c5f.jpg)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem name.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by abcsumitsingh** [comment]
Word ladder

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team.  We appreciate your support!

**Comment by abcsumits** [comment]
your welcome:)
