### ISSUE TITLE
179. Largest Number | Edge cases

### ISSUE THREAD

**Issue by sergibro** [LeetCode-Feedback/LeetCode-Feedback#1075]
#### Your LeetCode username

sergibro48

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

If we add ```[34323,3432]``` to testcases -> some solutions (as provided) won’t work.

#### Code you used for Submit/Run operation

```
class Solution(object):
    def largestNumber(self, nums):
        """
        :type nums: List[int]
        :rtype: str
        """
        if not nums:
            return ''
        nums = [str(num) for num in nums]
        max_len = max([len(num) for num in nums])
        res = sorted(
            nums,
            key=lambda num: (num + num[0] * (max_len - len(num)), num[-1]),  # pass all testcases as of 25 Sep 2020
            reverse=True
        )
        res = ''.join(res)
        if res[0] == '0':
            res = '0'
        return res
```

#### Language used for code
Python3

#### Expected behavior

Provided solution and similar to it shouldn't be accepted.

Input:
`[34323,3432]`
Mentioned code return `343233432`
While the correct answer here is `343234323`

**Comment by lc-kay** [comment]
Hi @sergibro 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @sergibro 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
