### ISSUE TITLE
Missing Test Case - 595. Big Countries And need to fix the problem statement before the table appearance  

### ISSUE THREAD

**Issue by pallasivasai** [LeetCode-Feedback/LeetCode-Feedback#10750]
, when the user opens the problem first, opens table it seems to be difficult to understand the problem statement

#### P_siva_sai

P_siva_sai

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for your time. We've submit your feedback to the team. We appreciate your support!
