### ISSUE TITLE
Missing Test Case - 197. Rising Temperature

### ISSUE THREAD

**Issue by bhubesh757** [LeetCode-Feedback/LeetCode-Feedback#10762]
#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [x] Missing Test Cases 

#### Description of the bug

Passed 12 test cases

Rising Temperature

#### Code you used for Submit/Run operation

```
select 
id 
from
(
select 
* ,
coalesce( lag(temperature , 1 ) over(order by recorddate),999) as prev_temp
from weather 
) as tmp
where temperature > prev_temp;
```

#### Language used for code
SQL

#### Screenshots

<img width="1387" alt="Screenshot 2023-01-04 at 10 27 54 PM" src="https://user-images.githubusercontent.com/55022929/210607965-83075287-1031-4952-8756-7b6d97249763.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The issue.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by bhubesh757** [comment]
issue?

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The issue of this question you want to report, or
The missing test case you want to add. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
