### ISSUE TITLE
Missing Test Case - 496. Next Greater Element I

### ISSUE THREAD

**Issue by alantudyk** [LeetCode-Feedback/LeetCode-Feedback#10761]
#### Your LeetCode username
0x81

#### Category of the bug
- Missing Test Cases 

#### Description of the bug
Incorrect code below gets AC w/o test case `nums1 = [0], nums2 = [0]`

#### Code you used for Submit/Run operation
```ruby
def next_greater_element a, b
    h, max, prev = {}, 0, 0
    b.reverse_each do | curr |
        curr > max ?
            h[max = curr] = -1 :
            begin
                prev = h[prev] while curr > prev
                h[curr] = prev
            end
        prev = curr
    end
    a.map! { h[_1] }
end
```

#### Language used for code
Ruby

#### Expected behavior
Not AC.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
