### ISSUE TITLE
Missing Test Case - 283. Move Zeroes

### ISSUE THREAD

**Issue by KIRUBASHANKAR26** [LeetCode-Feedback/LeetCode-Feedback#10763]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
In Run operation, [0,1,0] this test case running successfully, But it's failing in the Submission.

#### Code you used for Submit/Run operation

```
/**
 * @param {number[]} nums
 * @return {void} Do not return anything, modify nums in-place instead.
 */
var moveZeroes = function(nums) {
    if(nums.length > 1){
        for(let i=0;i<nums.length;i++){
           if(nums[i]===0){
               nums.splice(i,1)
               nums.splice(nums.length,0,0)
           }
        }
    }
};

```

#### Language used for code
**JavaScript**

#### Expected behavior
In Submission, [0,1,0] this case should be a success

#### Screenshots
<img width="1435" alt="Screenshot 2023-01-04 at 11 10 56 PM" src="https://user-images.githubusercontent.com/48342585/210616680-f7d37435-e877-4350-90b5-37fa7716d1a2.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!
