### ISSUE TITLE
Design a Load Distributor Detailed Explanation of System Design

### ISSUE THREAD

**Issue by AlexLad1989** [LeetCode-Feedback/LeetCode-Feedback#10764]
Hello. Currently, I am trying to solve the Design a Load Distributor problem in the Detailed Explanation of System Design. I got the error during my submitting the solution. Then I tried to create the custom test case using the test sample from the broken submission test case. And this test case passed correctly. I am attaching the screen and file with the code.

![image](https://user-images.githubusercontent.com/22052338/210618918-176a817d-dc6f-445c-aef9-df449e383bc2.png)

Test: 

`["DCLoadBalancer","addMachine","addApplication","removeMachine"]
[[],[86511,18406],[91292,19457],[86511]]`

Solution: 
`import java.util.ArrayList;
import java.util.Collection;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.PriorityQueue;
import java.util.Queue;
import java.util.stream.Collectors;

class DCLoadBalancer {

    private static final Map<Integer, List<Application>> MACHINE_APPS = new HashMap<>();
    private static final Queue<Machine> MACHINES = new PriorityQueue<>();

    public DCLoadBalancer() {

    }

    public static void main(String[] args) {
        DCLoadBalancer dCLoadBalancer = new DCLoadBalancer();
        dCLoadBalancer.addMachine(86511,18406);
        System.out.println(dCLoadBalancer.addApplication(91292,19457));
        dCLoadBalancer.removeMachine(86511);

    }

    public void addMachine(int machineId,
                           int capacity) {
        MACHINES.add(new Machine(machineId,
                                 capacity));
        MACHINE_APPS.computeIfAbsent(machineId, key -> new ArrayList<>());

    }

    public void removeMachine(int machineId) {
        List<Application> applications = new ArrayList<>(MACHINE_APPS.get(machineId));
        MACHINE_APPS.remove(machineId);

        for (var application : applications) {
            addApplication(application);
        }
    }

    public int addApplication(int appId,
                              int loadUse) {
        int i = addApplication(new Application(appId,
                                               loadUse,
                                               0));
        //System.out.println(String.valueOf(i));
        return i;
    }

    private int addApplication(Application application) {
        Machine machine = MACHINES.peek();

        if (machine == null) {
            return -1;
        }

        int capacity = machine.capacity;
        int machineId = machine.machineId;

        if(capacity < application.loadUse) {
            return -1;
        }

        MACHINES.remove();

        int newCapacity = capacity - application.loadUse();

        if (newCapacity > 0) {
            addMachine(machineId,
                       newCapacity);
        }

        var newApplication = new Application(application.appId,
                                             application.loadUse,
                                             machineId);

        List<Application> applications = MACHINE_APPS.get(machineId);
        applications.add(newApplication);
        return machineId;
    }

    public void stopApplication(final int appId) {
        Optional<Application> application = MACHINE_APPS.values()
                                                        .stream()
                                                        .flatMap(Collection::stream)
                                                        .filter(applications -> applications.appId == appId)
                                                        .findAny();

        application.ifPresent(application1 -> {
            var loadUse = application1.loadUse;
            var machineId = application1.machineId;

            List<Application> applications = MACHINE_APPS.get(machineId);
            applications.remove(application1);

            MACHINES.stream()
                    .filter(machine -> machine.machineId == machineId)
                    .findAny()
                    .ifPresent(machine -> {
                        var currentCapacity = machine.capacity;
                        MACHINES.remove(machine);
                        addMachine(machineId,
                                   currentCapacity + loadUse);
                    });
        });
    }

    public List<Integer> getApplications(int machineId) {
        if (MACHINE_APPS.get(machineId) == null) {
            return new ArrayList<>();
        }
        return MACHINE_APPS.get(machineId)
                           .stream()
                           .limit(10)
                           .map(Application::appId)
                           .collect(Collectors.toList());
    }

    private record Application(int appId, int loadUse, int machineId) {

    }

    private record Machine(int machineId, int capacity) implements Comparable<Machine> {

        @Override
        public int compareTo(final Machine o) {
            if (this.capacity < o.capacity) {
                return 1;
            }
            if (this.capacity > o.capacity) {
                return -1;
            }

            return Integer.compare(this.machineId,
                                   o.machineId);
        }

        @Override
        public String toString() {
            return "Machine{" +
                   "machineId=" + machineId +
                   ", capacity=" + capacity +
                   '}';
        }
    }

    private void printCapacity() {
        MACHINES.stream()
                .map(machine -> machine.capacity)
                .sorted(Comparator.naturalOrder()).forEach(System.out::println);
    }
}

/**
 * Your DCLoadBalancer object will be instantiated and called as such:
 * DCLoadBalancer obj = new DCLoadBalancer();
 * obj.addMachine(machineId,capacity);
 * obj.removeMachine(machineId);
 * int param_3 = obj.addApplication(appId,loadUse);
 * obj.stopApplication(appId);
 * List<Integer> param_5 = obj.getApplications(machineId);
 */`

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!
