### ISSUE TITLE
contest

### ISSUE THREAD

**Issue by Bhavya-Ray** [LeetCode-Feedback/LeetCode-Feedback#10765]
i have participated in contest180 but i didn't got my participation leetcoins

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, please submit this issue to Zendesk support, we will help you solve contest related issue as soon as possible, thank you for your support!

**Comment by Bhavya-Ray** [comment]
Send me the mail address of zendesk

**Comment by Bhavya-Ray** [comment]
pls send solve my issue first

**Comment by Bhavya-Ray** [comment]
your service is not good
