### ISSUE TITLE
LeetCode 1226: Mistake in Correctness Judgement

### ISSUE THREAD

**Issue by HUOwen-pyh** [LeetCode-Feedback/LeetCode-Feedback#10769]
#### Your LeetCode username

[Misakaku](https://leetcode.com/Misakaku/)

#### Category of the bug
- [ ] Question
- Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The following code seems to be right since all the semaphores will be taken in total order. But it is judged incorrect. However, if exchange the place of pickFork() and semWait(), the answer is right.

#### Code you used for Submit/Run operation

```
// 1226. The Dining Philosophers

/*************************************************My code*************************************************/
#include<semaphore.h>
class DiningPhilosophers {
    sem_t sem[5];
public:
    DiningPhilosophers() {
        for(int i = 0;i<5;i++)sem_init(&(sem[i]),0,1);
    }

    void wantsToEat(int phl,
                    function<void()> pickLeftFork,
                    function<void()> pickRightFork,
                    function<void()> eat,
                    function<void()> putLeftFork,
                    function<void()> putRightFork) {
		
        if(phl == 4){
            sem_wait(&(sem[(phl+1)%5]));
            pickRightFork();
            sem_wait(&(sem[phl]));
            pickLeftFork();
            eat();
            putLeftFork();
            putRightFork();
            sem_post(&(sem[(phl+1)%5]));
            sem_post(&(sem[phl]));
            return;
        }
        sem_wait(&(sem[phl]));
        pickLeftFork();
        sem_wait(&(sem[(phl+1)%5]));
        pickRightFork();
        eat();
        putLeftFork();
        putRightFork();
        sem_post(&(sem[(phl+1)%5]));
        sem_post(&(sem[phl]));
        return;

    }
};

/*************************************************Right code*************************************************/
#include<semaphore.h>
class DiningPhilosophers {
    sem_t sem[5];
public:
    DiningPhilosophers() {
        for(int i = 0;i<5;i++)sem_init(&(sem[i]),0,1);
    }

    void wantsToEat(int phl,
                    function<void()> pickLeftFork,
                    function<void()> pickRightFork,
                    function<void()> eat,
                    function<void()> putLeftFork,
                    function<void()> putRightFork) {
		
        if(phl == 4){
            sem_wait(&(sem[(phl+1)%5]));
            sem_wait(&(sem[phl]));
            pickLeftFork();
            pickRightFork();
            eat();
            putLeftFork();
            putRightFork();
            sem_post(&(sem[(phl+1)%5]));
            sem_post(&(sem[phl]));
            return;
        }
        sem_wait(&(sem[phl]));
        sem_wait(&(sem[(phl+1)%5]));
        pickLeftFork();
        pickRightFork();
        eat();
        putLeftFork();
        putRightFork();
        sem_post(&(sem[(phl+1)%5]));
        sem_post(&(sem[phl]));
        return;

    }
};
```

#### Language used for code

C++

#### Expected behavior

Accepted

#### Screenshots

The following output is definitely right
<img width="287" alt="屏幕截图 2023-01-05 110612" src="https://user-images.githubusercontent.com/75468552/210685486-595b54d5-a660-400e-9a8b-32b3bdee2aea.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submit link since we received Compile Error when we submit your code. 
We need correct code to run the test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by HUOwen-pyh** [comment]
I copied the code above into my leetcode and it was compiled successfully. There are two parts in the above code: my code and the right answer, and you need to run them respectively but not put them together. Hope this will help.

For the submit links, the right one is https://leetcode.com/problems/the-dining-philosophers/submissions/873687039/, and mine is https://leetcode.com/problems/the-dining-philosophers/submissions/873686980/.
