### ISSUE TITLE
Missing Test Case - 剑指 Offer 40. 最小的k个数  LCOF

### ISSUE THREAD

**Issue by TCaaaaaaaa** [LeetCode-Feedback/LeetCode-Feedback#10768]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ 测试的用例无正确的显示，是空的，虽然提交是成功的] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by BrambleWave** [comment]
请提供详细的信息以及截图，以便定位
