### ISSUE TITLE
Missing Test Case - 1346. Check If N and Its Double Exist

### ISSUE THREAD

**Issue by CarlosViniMSouza** [LeetCode-Feedback/LeetCode-Feedback#10767]
#### Your LeetCode username

[CarlosViniMSouza](https://leetcode.com/CarlosViniMSouza/)

#### Category of the bug

- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the *'first exercise'* of the chapter *'Searching for items in an array'*, I tried to solve it using JS. Only one of the use cases is returning 'true' instead of 'false'.

I went to check in VS Code, and I found the problem: `element 0 in the array made it return 'true'` (since 0 x 2 == 0 -> return 'true')

I would like to ask if I forgot to take something into account to solve this specific use case!

#### Code you used for Submit/Run operation

```JS
// My code JS on platform
/**
 * @param {number[]} arr
 * @return {boolean}
 */

var checkIfExist = function(arr) {
    // DONT FORGET: arr[i] == 2 * arr[j]
    
    for (let i = 0; i < arr.length; i++) {
        for (let j = 0; j < arr.length; j++) {
            if (arr[i] === (2 * arr[j])) {
                return true;
            }
        }
    }
    
    return false;
};
```

#### Language used for code

JavaScript

#### Expected behavior

I'm in doubt if in the case of using the array [-2,0,10,-19,4,6,-8] it should return 'true' or 'false'

#### Screenshots

![image](https://user-images.githubusercontent.com/60679101/210651471-04244b56-22ad-4fc2-9e40-3d450a064fe6.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
