### ISSUE TITLE
4. Median of Two Sorted Arrays

### ISSUE THREAD

**Issue by zakijariwala** [LeetCode-Feedback/LeetCode-Feedback#10775]
jzaki

#### Category of the bug
- [ ] Missing Test Cases 

when running the program second test case does not give the correct answer. i have verified this in multiple other compilers and for some reason this one wont reach the correct answer no matter what

```
class Solution:
    def findMedianSortedArrays(self, nums1, nums2):        
        m, n = len(nums1), len(nums2)
        if m > n:
            nums1, nums2, m, n = nums2, nums1, n, m
        if n == 0:
            raise ValueError
        
        low, high = 0, m
        while low <= high:
            i = (low + high) // 2
            j = (m + n + 1) // 2 - i
            if i > 0 and nums1[i-1] > nums2[j]:
                high = i - 1
            elif i < m and nums2[j-1] > nums1[i]:
                low = i + 1
            else:
                if i == 0:
                    max_of_left = nums2[j-1]
                elif j == 0:
                    max_of_left = nums1[i-1]
                else:
                    max_of_left = max(nums1[i-1], nums2[j-1])
                
                if (m + n) % 2 == 1:
                    return max_of_left

                if i == m:
                    min_of_right = nums2[j]
                elif j == n:
                    min_of_right = nums1[i]
                else:
                    min_of_right = min(nums1[i], nums2[j])
                
                return (max_of_left + min_of_right) / 2
```

python

the test case to be cleared

![WhatsApp Image 2023-01-05 at 15 57 20](https://user-images.githubusercontent.com/50477360/210761355-63a7d98f-d7a6-48c1-9900-8f32f5080226.jpg)
![WhatsApp Image 2023-01-05 at 15 57 54](https://user-images.githubusercontent.com/50477360/210761448-5a1e9ab5-fac7-4d2e-989b-b5e2ea1a687e.jpg)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!
