### ISSUE TITLE
Missing Test Case - 9. Palindrome Number

### ISSUE THREAD

**Issue by okazivaetsya** [LeetCode-Feedback/LeetCode-Feedback#10773]
#### Your LeetCode username
exsd

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug
not full test coverage

#### Code you used for Submit/Run operation

```
def isPalindrome(self, x: int) -> bool:
        x = str(x)
        left_part = x[0:len(x) // 2]
        if len(x) % 2 == 0:
            right_part = x[len(x) // 2:]
        else:
            right_part = x[len(x) // 2 + 1:]
        return True if left_part == right_part[::-1] else False
```

#### Language used for code
Python

#### Expected behavior

If we get (-1) as argument it must return True but this option doesn't check. So if I wright the code below:
```
def isPalindrome(self, x: int) -> bool:
        x = str(x)
        left_part = x[0:len(x) // 2]
        if len(x) % 2 == 0:
            right_part = x[len(x) // 2:]
        else:
            right_part = x[len(x) // 2 + 1:]
        return True if left_part == right_part[::-1] else False
```
it will be accepted but will not work correctly

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
