### ISSUE TITLE
Missing Test Case - 2456. Most Popular Video Creator

### ISSUE THREAD

**Issue by Tudor67** [LeetCode-Feedback/LeetCode-Feedback#10787]
#### Your LeetCode username

[Tudor67](https://leetcode.com/Tudor67/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My solution passed all the test cases and was accepted,
but I found a test case that it doesn’t cover.

My solution doesn't cover the following test case:
Input:
["alice","alice"]
["a","b"]
[0,0]

Output: [["alice","b"],["alice","a"]]

Expected: [["alice","a"]]

#### Code you used for Submit/Run operation

[Submission Link](https://leetcode.com/problems/most-popular-video-creator/submissions/872158963/)
```
// 2456. Most Popular Video Creator
// C++
class Solution {
public:
    vector<vector<string>> mostPopularCreator(vector<string>& creators, vector<string>& ids, vector<int>& views) {
        const int N = creators.size();
        
        vector<int> p(N);
        iota(p.begin(), p.end(), 0);
        
        sort(p.begin(), p.end(),
             [&](int lhs, int rhs){
                 return tuple<string, int, string>{creators[lhs], -views[lhs], ids[lhs]} >
                        tuple<string, int, string>{creators[rhs], -views[rhs], ids[rhs]};
             });
        
        long long maxViews = 0;
        long long creatorViews = 0;
        for(int i = 0; i < N; ++i){
            creatorViews += views[p[i]];
            maxViews = max(maxViews, creatorViews);
            if(i == N - 1 || creators[p[i]] != creators[p[i + 1]]){
                creatorViews = 0;
            }
        }
        
        vector<vector<string>> res;
        creatorViews = 0;
        for(int i = 0; i < N; ++i){
            creatorViews += views[p[i]];
            if(creatorViews == maxViews){
                res.push_back({creators[p[i]], ids[p[i]]});
            }
            if(i == N - 1 || creators[p[i]] != creators[p[i + 1]]){
                creatorViews = 0;
            }
        }
        
        return res;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Wrong Answer

#### Screenshots

![missing_test_case_2456](https://user-images.githubusercontent.com/12481060/210870289-af2750d7-3867-40d3-93d6-27f569dcba79.png)

#### Additional context

The problem occurs when the max popularity of creators is 0.
In that case, my solution returns all pairs {creator, videoID}.
It doesn't find the lexicographically smallest video id.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
