### ISSUE TITLE
Missing Test Case - 234. Palindrome Linked List

### ISSUE THREAD

**Issue by ToxinG** [LeetCode-Feedback/LeetCode-Feedback#10786]
#### Your LeetCode username

user1668j

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Seems like there is a whole group of test cases that are missing, for example
[1,2,3,3,2,4,4,3,2,2,3,1]

The general idea is that the list (let it be L) is "almost like a palindrome" ([1,...,4,4,...,1]), but the middles of the halves of L are palindromes themselves, different ones, but with a relation which my solution is based on. And the solution turned out to be wrong.
The relation is 

`2 * index_sum[i] / count[i] == length - 1`

where index_sum is array of sums of indexes in L and count is array of occurrences numbers for each possible Node value (0..9), so they are O(1) space and can be calculated with a single loop; length is L's length. The constraint 0 <= Node.val <= 9 led me to this.
But this solution has failed for [2,3,3,2,3,2,2,3], then I added check of equality of the first and the last nodes, after that my wrong solution passed all present tests.

#### Code you used for Submit/Run operation

```
class Solution:
    def isPalindrome(self, head: Optional[ListNode]) -> bool:
        len = 0
        index_sum = [0] * 10
        c = [0] * 10
        cur = head
        while True:
            index_sum[cur.val] += len
            c[cur.val] += 1
            len += 1
            if cur.next:
                cur = cur.next
            else:
                break
        if head.val != cur.val:
            return False
        for i in range(10):
            if c[i] and 2 * index_sum[i] / c[i] != len - 1:
                return False
        return True

```

#### Language used for code
Python3

#### Expected behavior

Some failed tests

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
