### ISSUE TITLE
Missing Test Case - 452. Minimum Number of Arrows to Burst Balloons

### ISSUE THREAD

**Issue by syanukov** [LeetCode-Feedback/LeetCode-Feedback#10781]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The following constraint specified in the problem description - `-2^31 <= x_start` - implies that we must choose some number smaller than `Integer.MIN_VALUE` as a starting comparison point. 

There is an existing test case for this: `Input: points = [[-2147483648, 2147483647]]`, but it can be deceived just by checking the input length, that is to say always returning 1 if the input length is 1

#### Code you used for Submit/Run operation

```
class Solution {
    public int findMinArrowShots(int[][] points) {
      if (points.length == 1) {
        return 1;
      }
      Arrays.sort(points, Comparator.comparingInt(p -> p[1]));
      var count = 0;
      var prevEnd = Integer.MIN_VALUE;
      for (var coordinates : points) {
        if (coordinates[0] > prevEnd) {
          count++;
          prevEnd = coordinates[1];
        }
      }
      return count;
    }
  }
```

#### Language used for code
Java

#### Expected behavior

However, if we add the following test case `Input: points = [[-2147483648, 2147483647], [-2147483648, 2147483647]]` the solution above will be no longer considered as accepted.
It will produce the incorrect output `0`, although the correct one should be `1`

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
