### ISSUE TITLE
[Bug] Pseudo-code of official solution of problem 452

### ISSUE THREAD

**Issue by congliu0704** [LeetCode-Feedback/LeetCode-Feedback#10782]
**你的 LeetCode 用户名**
leetcode.cn/u/congliu0704

**Bug 类型**
- [x] 题解

**描述**
[452. Minimum Number of Arrows to Burst Balloons](https://leetcode.cn/problems/minimum-number-of-arrows-to-burst-balloons/)的官方题解中的两段伪代码中的第3行有误：
```
let ans := 0，表示射出的箭数
```
在两段伪代码均应为
```
let ans := 1，表示射出的箭数
```

**屏幕截图**

<img width="785" alt="Screenshot 2023-01-05 at 23 42 15" src="https://user-images.githubusercontent.com/4845325/210821069-5b5a9f81-f530-44fa-8f8f-b02b33bf198a.png">

<img width="772" alt="Screenshot 2023-01-05 at 23 42 44" src="https://user-images.githubusercontent.com/4845325/210821179-1b3f1bf7-3457-436f-827f-6e768a26815e.png">

**Comment by feiceh** [comment]
你好，当前题解已更新，ID：congliu0704 给予积分奖励，请查收。
