### ISSUE TITLE
Missing Test Case - 384. Shuffle An Array

### ISSUE THREAD

**Issue by arshjhaj** [LeetCode-Feedback/LeetCode-Feedback#10788]
#### Your LeetCode username

a_jhaj

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

In this question, we are asked to return a uniformly random permutation of an array. I use a naive algorithm where I iterate over i in 0....len(arr)-1, pick a random index j in 0...len(arr)-1 and swap arr[i], arr[j]. This naive solution passes the test cases. However, it is known that this algorithm is incorrect. See https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle#Na%C3%AFve_method

#### Code you used for Submit/Run operation

```
class Solution:

    def __init__(self, nums: List[int]):
        self.original = nums[:]
        self.curr = nums
        

    def reset(self) -> List[int]:
        return self.original
        

    def shuffle(self) -> List[int]:
        for i in range(len(self.curr)):
            j = random.randint(0, len(self.curr) - 1)
            self.curr[j], self.curr[i] = self.curr[i], self.curr[j]
        return self.curr
            
```

#### Language used for code

Python

#### Expected behavior

The expected behaviour is that the solution should be judged incorrect because algorithm fails to return a uniformly random permutation, as indicated in the linked Wikipedia article. What actually happened is that all the tests passed and the submission was accepted.

#### Additional context

Submission link: https://leetcode.com/submissions/detail/872167259/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time.
The problem is general and does not test how much the randomization is correct. As long as the returned answer is randomized, it is ok.
We appreciate your support!
