### ISSUE TITLE
Missing Test Case - 20. Valid Parentheses

### ISSUE THREAD

**Issue by patr1c1a** [LeetCode-Feedback/LeetCode-Feedback#10792]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description

Test suite is missing a test case that evaluates nested parentheses in incorrect order.

#### Test case
```
"((){)}"
```

This makes sure that even when the number of open and closed parentheses match, if they're in the wrong order the test will fail.

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
