### ISSUE TITLE
两数相加测试用例有误

### ISSUE THREAD

**Issue by Lixingzhi** [LeetCode-Feedback/LeetCode-Feedback#1079]
** Bug 类型**
 测试用例有误

**描述**
第二题 2. 两数相加 测试用例有误

**你使用的语言**
C

**你提交或者运行的代码**
struct ListNode* addTwoNumbers(struct ListNode* l1, struct ListNode* l2){
    int num1 = 0;
    int num2 = 0;
    int temp = 1;
    struct ListNode *head = NULL;
    struct ListNode *position = NULL;

    do 
    {
        num1 = (num1 * temp) + l1->val;
        temp = 10;

        if (l1->next != NULL) {
            l1 = l1->next;
        } else {
            break;
        }
    } while (1);

    temp = 1;
    do 
    {
        num2 = (num2 * temp) + l2->val;
        temp = 10;

        if (l2->next != NULL) {
            l2 = l2->next;
        } else {
            break;
        }

    } while (1);  
    num1 = num1 + num2;

    do
    {
        struct ListNode *tempNode = (struct ListNode *)malloc(sizeof(struct ListNode));;
        tempNode->val = num1 % 10;
        tempNode->next = NULL;

        if (position != NULL) {
            position->next = tempNode;
            position = tempNode;
        } else {
            head = position = tempNode;
        }

        num1 = num1 / 10;
    } while (num1 != 0);

    return head;
}

**期望行为**
输入
[1,8]
[0]
输出
[8,1]

**屏幕截图**
![图片](https://user-images.githubusercontent.com/16254576/94343139-b76dbe00-0048-11eb-9fa8-20b6ef132a33.png)

**额外的上下文**
无

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认的～

**Comment by feiceh** [comment]
你好，该题目测试数据技术验证没有问题的，输入[1,8] [0]正确输出就是[1,8]，后续刷题学习中遇到困难，也可以通过阅读题目评论和题解看到一些解题思路哦～
