### ISSUE TITLE
Missing Test Case - 341. Flatten Nested List Iterator

### ISSUE THREAD

**Issue by wizenwitch** [LeetCode-Feedback/LeetCode-Feedback#10790]
#### Your LeetCode username

kkslide

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The init function for the provided type NestedInteger erroneously initializes to an integer type when called with a list.

#### Code you used for Submit/Run operation

```
class NestedIterator:
    def __init__(self, nestedList: List[NestedInteger]):
        self.list = self.flatten(NestedInteger(nestedList)) <- expecting flatten to be called with a valid NestedInteger
        self.cursor = 0
    
    def flatten(self, nestedList: NestedInteger):
        stack = [nestedList]         
        flattened_list = []
        
        while stack != []:
            cur = stack.pop()
            print(cur)
            if cur.isInteger():
                print(f'isInteger: append {cur.getInteger()}')
                flattened_list.append(cur.getInteger())
            else:
                for item in reversed(cur.getList()):
                    stack.append(item)
        return flattened_list

    def next(self) -> int:
        res = self.list[self.cursor]
        self.cursor += 1
        return res
    
    def hasNext(self) -> bool:
        if len(self.list) > self.cursor:
            return True
```

#### Language used for code

Python

#### Expected behavior

Expecting the init function of NestedInteger to initialize correctly when called with a list. But we get an "integer" type back instead:

NestedInteger{_integer: [NestedInteger{_integer: None, _list: [NestedInteger{_integer: 1, _list: []}, NestedInteger{_integer: 1, _list: []}]}, NestedInteger{_integer: 2, _list: []}, NestedInteger{_integer: None, _list: [NestedInteger{_integer: 1, _list: []}, NestedInteger{_integer: 1, _list: []}]}], _list: []}

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. You wrote a wrong syntax. Please read the definition of NestedInteger to be able to solve the problem and write a correct syntax.
We appreciate your support!
