### ISSUE TITLE
Execution Failure Bug - 59. Spiral Matrix II

### ISSUE THREAD

**Issue by charlesgohck** [LeetCode-Feedback/LeetCode-Feedback#10791]
#### Your LeetCode username
charlesgoh

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
For Spiral Matrix II question, the solution works on IDLE but is returning a Index out of range error on Leetcode. I tried debugging the question and the output is correct in debug mode. Only when I try running it in normal mode it will return this error. Please advise as IDLE and debug mode is returning the correct values. Is there a bug in the running system?

#### Code you used for Submit/Run operation
```python3
class Solution:
    def generateMatrix(self, n: int) -> List[List[int]]:
        result = [[-1]*n for i in range(n)]
        queue = collections.deque([])
        queue.append((0, 0, 1, "R"))
        visited = set()
        while queue:
            if len(queue) == 0:
                break
            node = queue.popleft()
            row, col, num, direction = node
            if (row, col) in visited:
                continue
            visited.add((row, col))
            result[row][col] = num
            if direction == "R":
                if col + 1 < n and (row, col + 1) not in visited:
                    queue.append((row, col + 1, num + 1, "R"))
                else:
                    queue.append((row + 1, col, num + 1, "D"))
            elif direction == "D":
                if row + 1 < n and (row + 1, col + 1) not in visited:
                    queue.append((row + 1, col, num + 1, "D"))
                else:
                    queue.append((row, col - 1, num + 1, "L"))
            elif direction == "L":
                if col - 1 >= 0 and (row, col - 1) not in visited:
                    queue.append((row, col - 1, num + 1, "L"))
                else:
                    queue.append((row - 1, col, num + 1, "U"))
            elif direction == "U":
                if row - 1 >= 0 and (row - 1, col) not in visited:
                    queue.append((row - 1, col, num + 1, "U"))
                else:
                    queue.append((row, col + 1, num + 1, "R"))
        return result
```

#### Language used for code
Python3

#### Expected behavior
For Spiral Matrix II question, the solution works on IDLE but is returning a Index out of range error on Leetcode. I tried debugging the question and the output is correct in debug mode. Only when I try running it in normal mode it will return this error. Please advise as IDLE and debug mode is returning the correct values. Is there a bug in the running system?

#### Screenshots
https://imgur.com/a/pNIkx9W

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The code is  wrong and accesses an index out of the bound when the matrix is 1x1. We appreciate your support!
