### ISSUE TITLE
Missing Test Case - 2112. The Airport With the Most Traffic

### ISSUE THREAD

**Issue by huangshan-01** [LeetCode-Feedback/LeetCode-Feedback#10809]
#### Your LeetCode username
huangshan01

#### Category of the bug
- [ x ] Missing Test Cases 

#### Description of the bug
2112. The Airport With the Most Traffic
https://leetcode.com/problems/the-airport-with-the-most-traffic/description/

Suggested case to add:
| departure_airport | arrival_airport | flights_count |
| ----------------- | --------------- | ------------- |
| 1                 | 2               | 1             |
| 2                 | 1               | 1             |
| 3                 | 4               | 1             |
| 4                 | 3               | 1             |
| 5                 | 6               | 7             |

The following query uses left join, not taking into account airports 5 and 6, but it can be submitted successfully.

#### Code you used for Submit/Run operation
```
with
dep as
(
    select departure_airport as airport_id, sum(flights_count) as total
    from Flights
    group by departure_airport
),
arr as
(
    select arrival_airport as airport_id, sum(flights_count) as total
    from Flights
    group by arrival_airport
),
comb as
(
    select airport_id,
    rank() over(order by dep.total + arr.total desc) as rnk
    from dep
    left join arr
    using(airport_id)
)
select airport_id from comb
where rnk = 1
```

#### Language used for code
MySQL

#### Expected behavior
| airport_id |
| ---------- |
| 5          |
| 6          |

#### Screenshots
![image](https://user-images.githubusercontent.com/122117440/211073173-094706a7-7e89-4d8c-b7a5-7d7c60569543.png)
![image](https://user-images.githubusercontent.com/122117440/211073946-7645e851-97a7-40c4-b99d-f7d4341ffadc.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as the reward for this feedback. 

If you have any other questions or feedbacks, please don't hesitate to let us know! 

We appreciate your support!
