### ISSUE TITLE
1833. Maximum Ice Cream Bars

### ISSUE THREAD

**Issue by venom-10** [LeetCode-Feedback/LeetCode-Feedback#10807]
#### Your LeetCode username
 Venom_10

#### Category of the bug
- [✔️ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Add This follow-up to the question **You must implement an algorithm that runs in O(n) time** O(nlogn) solution is very easy but linear time solution is what that makes this question Medium 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int maxIceCream(vector<int>& costs, int coins) {
        sort(costs.begin(), costs.end());
        int  n = costs.size(), bar = 0;
        for(int i=0;i<n;i++){
            if(costs[i]<=coins){
                bar++;
                coins-=costs[i];
            }else break;
        }
        return bar;
    }
};

```
#### Language used for code
C++

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
