### ISSUE TITLE
Missing Test Case - 789. Escape The Ghosts

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#1080]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution from discuss section is accepted but fails on the following test case:

[[2, 2]]
[1, 1]

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean escapeGhosts(int[][] ghosts, int[] target) {
        int distanceToTarget = distance(new int[2], target);
        
        for (int[] ghost : ghosts) {
            if (distance(ghost, target) < distanceToTarget) return false;
        }
        return true;
    }
    
    int distance(int[] pos, int[] target) {
        return Math.abs(pos[0] - target[0]) + Math.abs(pos[1] - target[1]);
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/94343401-ebfc5e00-ffe5-11ea-934f-a96f6662cd1d.png)

#### Additional context

Link to the original solution:
https://leetcode.com/problems/escape-the-ghosts/discuss/243637/Java-solution

**Comment by Vikas-Jethwani** [comment]
@IgorRud  I just saw about 20+ of your issues. How do you find such faulty solutions and find the exact counter test case?
Do you go through each code hunting for mistakes or what? No offense. Just wanted to know.

**Comment by IgorRud** [comment]
Hi,

I don't think there are 20, but it is about that. It all started with 1494. Parallel Courses II and 1515. Best Position for a Service Centre - I realized that there are solutions that are just incorrect - despite that they pass many or all test cases.

Even official solutions may raise questions. For example this one - https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/585, I'm not saying it is wrong, but unless I checked it myself, I would believe that approach # 7 is the best one.

So I decided to check the solutions to see 1) if they are fast enough 2) they pass a  set of randomly generated cases to select the best one to learn from them. Without doing that you may believe that a solution is correct, but in the reality it may not be. There might be something simple unaccounted, or there may be fundamental problem with the approach - but I just don't want to waste time on incorrect and slow solutions.

It is hilarious how many interviewers expect interviewees to dry run their code during interview. Obviously they did not see "1494. Parallel Courses II" and "1515. Best Position" :)

So these test cases are byproduct of my approach to learning.

Hope this makes sense.

Thank you,
Igor

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
