### ISSUE TITLE
Solution to the Maximum Ice Cream Bars might have wrong assumption about DP

### ISSUE THREAD

**Issue by b10s** [LeetCode-Feedback/LeetCode-Feedback#10804]
#### Your LeetCode username
b10s

#### Category of the bug
- [ ] Solution

#### Description of the bug
Solution to the Maximum Ice Cream Bars might have wrong assumption about DP.
 https://leetcode.com/problems/maximum-ice-cream-bars/
 
1. To be treated as DP there must be two properties. One is not enough.

2. Also I do not see "optimal substructure" property. Because optimal solution of a whole problem is not based on optimal solutions of subproblems. I see no connection in decision making to subproblem's solution.

**Comment by venom-10** [comment]
But DP is not mentioned on related topics.

**Comment by b10s** [comment]
@venom-10 it is mentioned in solution wrongly by my opinion.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
