### ISSUE TITLE
Test Case Not Accepting Even Code Is Correct

### ISSUE THREAD

**Issue by premang** [LeetCode-Feedback/LeetCode-Feedback#1081]
#### Category of the bug
- [ ] Question
- [ ->] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int diagonalSum(vector<vector<int>>& mat) {
        int s=mat.size(); 
        int i=0;
        int k=0,r=s-1;static int sum=0;
        for(int p=0;p<s,i<s,r>-1;p++,i++,r--) {
            
            sum+=mat[i][i];
            sum+=mat[p][r];
            
        }
        if(s&1==1) {
            int x=(s-1)/2;
            sum=sum-mat[x][x];
        }
        int ss=sum;
        return ss;
    }
};
```

#### Screenshots

![image](https://user-images.githubusercontent.com/44500307/94346995-2699e100-004e-11eb-8fac-70900cd42a84.png)
![image](https://user-images.githubusercontent.com/44500307/94347000-344f6680-004e-11eb-9261-49506ec8b234.png)

**Comment by Vikas-Jethwani** [comment]
@premang Change 
```
static int sum=0;
```
to
```
int sum=0;
```
Your solution will probably get accepted. 
Reference: https://www.codesdope.com/discussion/what-is-the-difference-between-static-int-and-int/
