### ISSUE TITLE
Missing Test Case - 2453. Destroy Sequential Targets

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#10810]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets TLE on the following testcase:
[1.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/10364431/1.txt)

#### Code you used for Submit/Run operation

```
const int N = 100010;
int h[N], cnt[N],S;

int find(int x)
{
    int k = x % N;
    while (h[k] != -1 && h[k] != x){
        ++S;
        if (++k == N)
            k = 0;
    }
    
    if (h[k] == -1)
        h[k] = x;
    
    return k;
}

class Solution {
public:
    int destroyTargets(vector<int>& nums, int space) {
        memset(h, -1, sizeof h);
        memset(cnt, 0, sizeof cnt);
        for (int& x : nums)
        {
            cnt[find(x % space)]++;
        }
        
        int maxTars = 0;
        int res = 0;
        for (int& x : nums) {
            int k = find(x % space);
            if (!res || maxTars < cnt[k] || (maxTars == cnt[k] && x < res)) {
                res = x;
                maxTars = cnt[k];
            }
        }
        cout<<S<<endl;
        
        return res;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The code gets TLE.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
