### ISSUE TITLE
Sudoku solver accepts bad test case

### ISSUE THREAD

**Issue by grid47** [LeetCode-Feedback/LeetCode-Feedback#10813]
#### Your LeetCode username
grid47

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

For the problem sudoku solver (leetcode.com/problems/valid-sudoku/) 
[[".","8","7","6","5","4","3","2","1"],
["2",".",".",".",".",".",".",".","."],
["3",".",".",".",".",".",".",".","."],
["4",".",".",".",".",".",".",".","."],
["5",".",".",".",".",".",".",".","."],
["6",".",".",".",".",".",".",".","."],
["7",".",".",".",".",".",".",".","."],
["8",".",".",".",".",".",".",".","."],
["9",".",".",".",".",".",".",".","."]]
This is test case is accepted as 'true'. though filling '9' at coordinate (0, 0) (due to present of '9' in same column) is impossible and the sudoku is unsolvable.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool isSafe(vector<vector<char>>& board, int i, int j, char k) {
        for(int p = 0; p < 9; p++)
            if(board[i][p] == k) return false;
        for(int p = 0; p < 9; p++)
            if(board[p][j] == k) return false;
        
        for(int p = (i/3) * 3; p < (i/3) * 3 + 3; p++)
        for(int q = (j/3) * 3; q < (j/3) * 3 + 3; q++)
            if(board[p][q] == k) return false;
        
        return true;
    }
    bool solve(vector<vector<char>>& board, int i, int j) {
        if(i == 9) return true;
        if(j == 9) {
            return solve(board, i + 1, 0);
        }
        if(board[i][j] != '.') {
            return solve(board, i, j + 1);
        }
        
        for(char k = '1'; k <= '9'; k++) {
            if(isSafe(board, i, j, k)) {
                board[i][j] = k;
                bool canSolve = solve(board, i, j + 1);
                if(canSolve) return true;
                
            }
        }
        board[i][j] = '.';
        return false;
        
    }
    
    bool isValidSudoku(vector<vector<char>>& board) {
        return solve(board, 0, 0);
    }
};
```

#### Language used for code

c++

#### Expected behavior

The test case should result answer as false.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

**Comment by grid47** [comment]
Please keep '9' at row/column 0/0. It's a wrong test case, but judge accepted it.

The solution I provided will help to pull out the test case.
Whatever others given on discuss are just checking the existing fillings are correct or not.
