### ISSUE TITLE
Missing Test Case - 134. Gas Station

### ISSUE THREAD

**Issue by bikbov** [LeetCode-Feedback/LeetCode-Feedback#10814]
#### Your LeetCode username
bikbov

#### Category of the bug
- Missing Test Cases 

#### Description of the testcase
Question have test case with a lot of zeros at start of input arrays. 
When I iterate from start to end I get "Time Limit Exceeded". When I iterate from end to start I get "Accepted".
Test case with a lot of zeros at the end of input arrays would be useful.

#### Code you used for Submit/Run operation

```
// Gas Station - Accepted
public class Solution 
{
    public int CanCompleteCircuit(int[] gas, int[] cost) 
    {
        for(int i = cost.Length - 1 ; i >= 0; --i)
        {
            int tank = gas[i];
            for(int k = 1; k <= gas.Length; ++k)
            {
                tank -= cost[(i + k - 1 + cost.Length) %  cost.Length];
                if(tank < 0) break;
                tank += gas[(i + k + cost.Length) %  cost.Length];
            }
            if(tank >= 0) return i;
        }
        return -1;
    }
}

// Gas Station - Time Limit Exceeded
public class Solution 
{
    public int CanCompleteCircuit(int[] gas, int[] cost) 
    {
        for(int i = 0 ; i < cost.Length; ++i)
        {
            int tank = gas[i];
            for(int k = 1; k <= gas.Length; ++k)
            {
                tank -= cost[(i + k - 1 + cost.Length) %  cost.Length];
                if(tank < 0) break;
                tank += gas[(i + k + cost.Length) %  cost.Length];
            }
            if(tank >= 0) return i;
        }
        return -1;
    }
}
```

#### Language used for code
C# 

#### Expected behavior

Time Limit Exceeded

#### Fact behavior
Accepted

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submit link since we received Compile Error when we submitted above code: (https://leetcode.com/submissions/detail/874932867/)

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by bikbov** [comment]
```
// Gas Station - Accepted
public class Solution 
{
    public int CanCompleteCircuit(int[] gas, int[] cost) 
    {
        for(int i = cost.Length - 1 ; i >= 0; --i)
        {
            int tank = gas[i];
            for(int k = 1; k <= gas.Length; ++k)
            {
                tank -= cost[(i + k - 1 + cost.Length) %  cost.Length];
                if(tank < 0) break;
                tank += gas[(i + k + cost.Length) %  cost.Length];
            }
            if(tank >= 0) return i;
        }
        return -1;
    }
}
```

**Comment by bikbov** [comment]
Missing test case:
https://gist.github.com/bikbov/ab3c20315010e09b240ad89089ffc6d0

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
