### ISSUE TITLE
Issue 10169 Continuance 

### ISSUE THREAD

**Issue by ThomasShaw1** [LeetCode-Feedback/LeetCode-Feedback#10830]
_Originally posted by @ThomasShaw1 in https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/10169#issuecomment-1374633510_

**Comment by LC-Pam** [comment]
Thank you for your time. We've submit your feedback to the team. For contribution status, please reach out to Leetcode zendesk support team for more details. We appreciate your support!
