### ISSUE TITLE
Missing Test Case - 149. Max Points on a Line

### ISSUE THREAD

**Issue by nook1208** [LeetCode-Feedback/LeetCode-Feedback#10839]
#### Your LeetCode username

ttunux

#### Category of the bug
- [] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The 149 problem doesn't have enough testcase like this :
T1: points = [[203,203],[102,102],[306,306]] 

I used primes in the range of [2:sqrt(10000)] to get the greatest common denominator. (sqrt(10000) == 100)
So in my code, if the slope value's denominator and numerator are higher than 100, 
and those values are just the same prime value after dividing it by the common primes just like the 'T1',
then I should fail to collect all of the points with the same slope. But I got Accepted.
Please check the 'NOTICE' comment in my code.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<int> get_primes(int limit) {
        vector<int> val(limit);
        vector<int> primes;

        for (int i = 2 ; i < limit; i++) {
            val[i] = i;
        }

        for (int i = 2; i < limit; i++) {
            if (!val[i]) continue;
            primes.push_back(i);
            for (int k = i*2; k < limit; k += i) {
                val[k] = 0;
            }
        }

        return primes;
    }

    void div(int& a, int& b, vector<int>& primes) {
        for (auto p: primes) {
            if (a % p == 0 && b % p == 0) {
                while(a % p == 0 && b % p == 0) {
                    a /= p;
                    b /= p;
                }
            }
        }
        /* NOTICE: if you add this code, then it can pass the corner case like this:
         * points = [[203,203],[102,102],[306,306]]        
        if (a == b && a != 1) {
            a = 1, b = 1;
        }
        */
    }

    int maxPoints(vector<vector<int>>& points) {
        unordered_map<int,int> xs;
        vector<int> primes = get_primes(sqrt(10000) + 1);
        int ans = 0;

        for (int i = 0 ; i < points.size(); i++) {
            int x1 = points[i][0], y1 = points[i][1];
            map<pair<int,int>,int> m;
            xs[x1]++;
            for (int k = i + 1; k < points.size(); k++) {
                int x2 = points[k][0], y2 = points[k][1];
                if (x1 == x2) continue;
                int hi = y2-y1;
                int lo = x2-x1;
                bool is_minus = (hi * lo < 0) ? true : false;

                hi = abs(hi), lo = abs(lo);                
                div(hi, lo, primes);
                
                if (is_minus) hi *= -1;
                m[make_pair(hi,lo)]++;
                ans = max(ans, m[make_pair(hi,lo)]);                
            }
        }
        ans++;

        for (int i = 0; i < points.size(); i++) {
            ans = max(ans, xs[points[i][0]]);
        }

        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

My code shouldn't be accepted

#### Screenshots

![image](https://user-images.githubusercontent.com/50063698/211181732-bd4a862f-7bc9-4f51-aa00-ed1043328141.png)
![image](https://user-images.githubusercontent.com/50063698/211181834-fadc56e0-ec49-4973-bd9b-93c2b9bda8d6.png)

#### Additional context

I love Leetcode. Thank you for your work on this amazing site !

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
