### ISSUE TITLE
Cannot pass test case with right implementation - 538. Convert BST to Greater Tree

### ISSUE THREAD

**Issue by MoSummers-dy** [LeetCode-Feedback/LeetCode-Feedback#1083]
#### Your LeetCode username
MoSummers

#### Category of the bug
- Submission

#### Description of the bug
Code fails with "wrong answer" with the correct implementation. None of the solution work. The expected outcome is wrong. 

Test Case: 
Input
[4,1,6,0,2,5,7,null,null,null,3,null,null,null,8] 
Output
[30,36,21,36,35,26,15,null,null,null,33,null,null,null,8]
Expected
[18,20,13]

#### Code you used for Submit/Run operation

```
class Solution {
    public TreeNode convertBST(TreeNode root) {
        int sum = 0;
        TreeNode node = root;
        Stack<TreeNode> stack = new Stack<TreeNode>();

        while (!stack.isEmpty() || node != null) {
            /* push all nodes up to (and including) this subtree's maximum on
             * the stack. */
            while (node != null) {
                stack.add(node);
                node = node.right;
            }

            node = stack.pop();
            sum += node.val;
            node.val = sum;

            /* all nodes with values between the current and its parent lie in
             * the left subtree. */
            node = node.left;
        }

        return root;
    }
}
```

#### Language used for code
Java

#### Expected behavior
Pass with no error

**Comment by lc-kay** [comment]
Hi @MoSummers-dy 
Thank you for your time. This issue was already raised in the discuss tab and our team has fixed the issue. We appreciate your support!
