### ISSUE TITLE
Missing Test Case - 149. Max Points on a Line

### ISSUE THREAD

**Issue by dongFIN** [LeetCode-Feedback/LeetCode-Feedback#10833]
#### Your LeetCode username 
 dongFIN

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

When the slope is 90 or -90, it may be misused as a vertical line.
- case 1 (for slope 90):  [[0,0],[1,90],[1,0]]
- case 2 (for slope -90):  [[0,0],[-1,90],[1,0]]

Using any number to represent the slope of a vertical line can create this problem, but hopefully, the common misuse is covered.

#### Code you used for Submit/Run operation
```c++
class Solution {
public:
    int maxPoints(vector<vector<int>>& points) {
        int ans = 1;
        for(int i=0; i<points.size(); i++){
            unordered_map <double, int> cnt;
            for(int j=0; j<points.size(); j++){
                if(i==j) continue;
                double a = 0;
                if(points[j][0]==points[i][0]) a = 90;  // or (-90)
                else a = (double)(points[j][1]-points[i][1]) / (points[j][0]-points[i][0]);
                cnt[a]++;
            }
            int tmp = 0;
            for(auto& ele: cnt){
                tmp = tmp <= ele.second ? ele.second+1 : tmp; 
            }
            ans = tmp > ans ? tmp : ans;
        }
        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior

Expected: Solution rejected
Actual: Solution accepted due to insufficient test cases

#### Screenshots
- case 1 = [[0,0],[1,90],[0,1]] ,slope=90
![](https://i.imgur.com/t9FqSqo.png)
![](https://i.imgur.com/tyKpkxi.png)

- case 2 = [[0,0],[-1,90],[0,1]] ,slope=-90
![](https://i.imgur.com/T1TWazO.png)
![](https://i.imgur.com/N86Z1pP.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
