### ISSUE TITLE
A Follow up Can Be Added - 2529. Maximum Count of Positive Integer and Negative Integer

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#10835]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
For [2529. Maximum Count of Positive Integer and Negative Integer](https://leetcode.com/problems/maximum-count-of-positive-integer-and-negative-integer), a simple solution is to loop over the array to count the number of positive integers and the number of negative integers. This solution has time complexity O(n), where n is the length of array `nums`.

Since the array `nums` is sorted, this problem can be solved using binary search, with time complexity O(log n). This is very likely to be required in an interview.

Therefore, a follow up can be added: Could you solve this problem in O(log n) time complexity?

#### Expected behavior
Add a follow up to require O(log n) time complexity.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!

**Comment by kennethportizpresto** [comment]
This is my solution. However idk if it is logn time. 
```class Solution(object):
    def maximumCount(self, nums):
        """
        :type nums: List[int]
        :rtype: int
        """
        lengthOfNums = len(nums)
        mid = lengthOfNums//2
        lptr, rptr = mid-1, mid+1

        if lengthOfNums < 2:
            return lengthOfNums
        
        if (nums[lptr] == 0 or nums[rptr] == 0):
            while(lptr > 0 and rptr < lengthOfNums):
                if nums[lptr] != 0:
                    if nums[mid] > 0:
                        return len(nums[:lptr+1]) + 1
                    else: 
                        return len(nums[:lptr+1])
                if nums[rptr] != 0:
                    if nums[mid] < 0:
                        return len(nums[rptr:]) + 1 
                    else:
                        return len(nums[rptr:])
                lptr -= 1
                rptr += 1
            return 0
        else:
            maxi = 0 
            if (nums[mid] < 0):
                for i in range(mid, lengthOfNums):
                    if nums[i] < 0:
                        maxi += 1 
                return maxi + len(nums[:mid])
            else:
                for i in range(0, mid):
                    if nums[i] > 0:
                        maxi +=1
                return maxi + len(nums[mid:])```
