### ISSUE TITLE
Missing Test Case - 258. Add Digits

### ISSUE THREAD

**Issue by puneeth072003** [LeetCode-Feedback/LeetCode-Feedback#10834]
#### Description of the bug
Though the code is working perfectly fine and output is also right, but still the expected output and actual output are different

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    public int addDigits(int num) {
        int sum=0;
        if(num==0){return(0);}
        while(num>0){
            int rem=num%10;
            sum=sum+rem;
            num=num/10;
        }
        return sum;
    }
}
```

#### Language used for code
java

#### Expected behavior

My answer should have been correct.

#### Screenshots

![error1](https://user-images.githubusercontent.com/119479391/211180247-d2b7fec2-05db-4cc2-89ce-e6dab9ea5736.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
