### ISSUE TITLE
Missing Test Case - 149. Max Points on a Line

### ISSUE THREAD

**Issue by rl16432** [LeetCode-Feedback/LeetCode-Feedback#10845]
#### Your LeetCode username

rl16432

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Missing test case causing incorrect solution to be accepted. No test case exists for when the correct solution appears in the last few elements in the array. This leads to shortcuts such as: ```for i in range(len(points)//2+1)```, being accepted.

For example:

```[[1,1],[1,4],[2,2],[2,3],[-9,27],[9,30],[8,135],[7,124],[6,-100],[5,93],[40,50],[-100,-90],[-80,-70]]```
- There is no group of 3 or more points, before the last 3 points that lie on the same line. 
- The last 3 points lie on the same line

Expected output: 3
Output of code below: 2

#### Code you used for Submit/Run operation

```python
from collections import defaultdict
class Solution:
    def maxPoints(self, points: List[List[int]]) -> int:
        grad_map=defaultdict(int)
        max_points=0
        for i in range(len(points)//2+1): # affected line
            for j in range(i+1,len(points)):
                if (points[j][0]-points[i][0])!=0:
                    grad=(points[j][1]-points[i][1])/(points[j][0]-points[i][0])
                    grad_map[grad]+=1
                    max_points=max(max_points,grad_map[grad])
                else:
                    grad_map[float("inf")]+=1
                    max_points=max(max_points,grad_map[float("inf")])
            grad_map.clear()
        return max_points+1
```

#### Language used for code

Python

#### Expected behavior

Expected: Solution rejected
Actual: Solution accepted due to insufficient test cases

#### Does not pass test case

![image](https://user-images.githubusercontent.com/65014987/211182809-d86dc373-e246-44c2-a65f-e39660660cca.png)

#### Solution is still accepted

![image](https://user-images.githubusercontent.com/65014987/211182794-94645f63-5994-44dd-8454-f63d91d040d3.png)

#### Additional context

N/A

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
