### ISSUE TITLE
Missing Test Case - 174. Dungeon Game

### ISSUE THREAD

**Issue by mahensh** [LeetCode-Feedback/LeetCode-Feedback#10846]
As we can see some of the coder submitted the solution based on starting from bottom right cell but most of the solutions will fail for this test case.

-5      1       3
30   -10    -3
10    -5     -2

Expected output should be 7 but accepted solution output is 6.

Please correct if am wrong.

**Comment by stormsunshine** [comment]
The path is -5 -> 30 -> 10 -> -5 -> -2, so the answer is 6. Is there any problem?

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
