### ISSUE TITLE
Missing simple test case  - 1599. Maximum Profit of Operating a Centennial Wheel

### ISSUE THREAD

**Issue by akaravaev1** [LeetCode-Feedback/LeetCode-Feedback#1086]
#### Your LeetCode username

Ceay

#### Category of the bug
- [ ] Question
- [ X] Solution
- [ ] Language

#### Description of the bug

A simple corner case is not present in the set of test cases. This corner case is about max. profit of zero. The code that I provide and that is accepted by LeetCode as correct outputs 1, while it should output -1. The run code result is correctly marked as "Wrong Answer" if I just supply the input as a testcase, but the code passes all LeetCode testcases.   

customers = [2]
boardingCost = 2
runningCost = 4

#### Code you used for Submit/Run operation

```
class Solution:
    def minOperationsMaxProfit(self, customers: List[int], boardingCost: int, runningCost: int) -> int:
        
        rotation, profit, max_profit, max_profit_rotation = 0, 0, -1, -1 
        
        waiting_cust = 0
        while rotation < len(customers) or waiting_cust > 0:
            if rotation < len(customers):  waiting_cust = waiting_cust + customers[rotation]
            board_cust = min(4, waiting_cust)
            profit += board_cust*boardingCost - runningCost
            if max_profit < profit:  (max_profit, max_profit_rotation) = (profit, rotation + 1)
            rotation, waiting_cust  = rotation + 1,  waiting_cust - board_cust
			
        return max_profit_rotation
```

#### Language used for code

Python3

#### Expected behavior

I would expect the provided code to be rejected by LeetCode, but it is accepted as correct (passes all test cases).

My submission of the incorrect code that passes all the LeetCode test cases: https://leetcode.com/submissions/detail/401363333/

**Comment by lc-kay** [comment]
Hi @akaravaev1 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @akaravaev1 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
