### ISSUE TITLE
Missing Test Case - 2214. Minimum Health to Beat Game

### ISSUE THREAD

**Issue by sudheeshix** [LeetCode-Feedback/LeetCode-Feedback#10872]
#### Your LeetCode username
sudheeshix

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
From the problem description, it isn't clear what the outcome would be if the `armor` has a value that is greater than some of the given `damage` values and lesser than others, but unlike test case 1, it is not equal to one of the `damage` values.

#### Code you used for Submit/Run operation
Not applicable

#### Language used for code
Irrelevant

#### Expected behavior
Consider this test case:
```
damage = [2,7,3]
armor = 4
```

If the armor can protect against a max damage of 3 here, the solution answer would be 1+2+7+0 = 10.
Instead, it seems the armor can partially protect against a damage of 7, and so, the solution answer is 1+2+(7-4)+3 = 9.
Note: The 1+ prefix in both cases is the min health required to complete the game.
It wasn't clear from the problem description that the latter scenario is being considered here.
Also, I feel the former scenario would be a bit more challenging to solve.

#### Screenshots
None

#### Additional context
None

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The problem description is clear and you can use the armor for 7 too.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
