### ISSUE TITLE
589. N-ary Tree Preorder Traversal, can't be solved in C#

### ISSUE THREAD

**Issue by dputko** [LeetCode-Feedback/LeetCode-Feedback#10875]
#### Your LeetCode username
dputko

#### Category of the bug
- [ ] Question
- [ ] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug

The description of the task says that each group must be separated by null, but the Preorder method return type is ```IList<int>``` which does not allow nullable int.

#### Code you used for Submit/Run operation

```
public class Solution {
    public IList<int> Preorder(Node root) {
        return new List<int>() { 1, null, 2 }; // error CS1503: Argument 1: cannot convert from '<null>' to 'int' (in Solution.cs)
    }
}
```

#### Language used for code
C#

#### Expected behavior
Return type should be ``IList<int?>`` or even ``IEnumerable<int?>``
```
public class Solution {
    public IList<int?> Preorder(Node root) {
        
    }
}
```

**Comment by stormsunshine** [comment]
Separating by the null value is about the serialization of the input. What does the input serialization have to do with the output?

This problem is surely solvable using C#, and I have already submitted the C# code.

**Comment by dputko** [comment]
It looks like I forgot how to read after the New Year holidays: I thought that I need to separate the groups of children with null in the **output**. I'm sorry for bothering :)
