### ISSUE TITLE
399. Evaluate Division - Incorrect Problem Description

### ISSUE THREAD

**Issue by idilsulo** [LeetCode-Feedback/LeetCode-Feedback#1087]
## Your LeetCode username
@ [codingwoman](https://leetcode.com/codingwoman/)

## Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language

## Description of the bug

**Problem:** [https://leetcode.com/problems/evaluate-division/](https://leetcode.com/problems/evaluate-division/)

**Typo in the constraint definition:**

In the question description of Evaluate Division there are 9 constraints provided. One of these constraints is the following: 
* `1 <= equations[i][0], equations[i][1] <= 5`

Yet, the problem states that the input format for the variable `equations` is `List[List[str]]`. 

One of the provided test cases has the following input:
```
equations = [["a","b"],["b","c"],["bc","cd"]], 
values = [1.5,2.5,5.0], 
queries = [["a","c"],["c","b"],["bc","cd"],["cd","bc"]]
```

As can be seen from the input above, each string term may contain several characters where the first and second term of each equation has at least one character and less than 5 characters. Considering this test case, the constraint can be corrected as below:
* `1 <= len(equations[i][0]), len(equations[i][1]) <= 5`

**Comment by lc-ivan** [comment]
Hi @idilsulo ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @idilsulo ,
Thanks for your feedback regarding this problem! Upon review, our team has concluded that the issue brought up in this ticket was had already been solved so, we will not be awarding LeetCoins for this case. Thank you once again and happy LeetCoding!
