### ISSUE TITLE
Missing Test Case - 149. Max Points on a Line

### ISSUE THREAD

**Issue by RohitSgh** [LeetCode-Feedback/LeetCode-Feedback#10871]
#### Your LeetCode username

RohitSgh

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The code gets [submitted](https://leetcode.com/problems/max-points-on-a-line/submissions/873949490/). But it shouldn't get submitted.

It is giving Wrong Answer on this Test Case
```
[[-10000,0], [10000,4001], [10000,4002]]
```

Submission is because this **test case is missing**.

#### Code you used for Submit/Run operation

```python3
class Solution:
    def maxPoints(self, points: List[List[int]]) -> int:
        
        # Line characterized by slope and y-intercept 
        setOfPoints = defaultdict(set)

        # Number of Points
        N = len(points)

        # Check for every pair
        for a in range(N):
            x1, y1 = points[a]

            for b in range(a+1, N):
                x2, y2 = points[b]

                # Slope and Intercept using Two Point

                # If vertical line, x-intercept
                if x2 == x1:
                    m = float('inf')
                    c = x2 
                
                # Otherwise, y-intercept
                else:
                    m = round((y2-y1)/(x2-x1), 4)
                    c = round(m*x1 - y1, 4)
                
                # Add in setOfPoints
                setOfPoints[(m, c)].add((x1,y1))
                setOfPoints[(m, c)].add((x2,y2))

        # Return maximum points in a group
        ans = 1
        for group in setOfPoints:
            ans = max(ans, len(setOfPoints[group]))
                    
        return ans
```

#### Language used for code

Python3

#### Expected behavior

- **Expected :** Code shouldn't get submitted/accepted because it is giving wrong answer on Test Case
    ```
    [[-10000,0], [10000,4001], [10000,4002]]
    ```
- **Happened :** Code Accepted. Here is the submission https://leetcode.com/problems/max-points-on-a-line/submissions/873949490/

#### Screenshots

Submission along with Wrong Answer
![Wrong Answer](https://user-images.githubusercontent.com/81853910/211188389-e8aa0dfb-4a9a-4c09-829a-8790305d2be9.png)

#### Additional context

The bug is because of rounding-off in these lines

```python3
                    m = round((y2-y1)/(x2-x1), 4)
                    c = round(m*x1 - y1, 4)
```

Due to round-off, different slopes get merged as one, and thus are in same group, which is wrong.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
