### ISSUE TITLE
Missing Test Case - 149. Max Points on a Line

### ISSUE THREAD

**Issue by davidtweedle** [LeetCode-Feedback/LeetCode-Feedback#10881]
#### Your LeetCode username
user1632q

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

Define the test case
points = [[1,1],[2,10],[3,100],[4,1000],[1,0],[2,0],[3,0],[4,0],[1,-1],[2,-10],[3,-100],[4,-1000]]
and run the code as listed below
The code below does not pass the above test case, but it does pass all given test cases currently on leetcode for this exercise.

#### Code you used for Submit/Run operation

```
class Solution:
    def maxPoints(self, points: List[List[int]]) -> int:
        n = len(points);
        if n<=2:
            return n;
        to_visit = set(range(n));
        res = 2;
        while len(to_visit)>0:
            index = to_visit.pop();
            cur_pt = points[index];
            x,y = cur_pt[0],cur_pt[1];
            slopes = {};
            for i in range(n):
                if index != i:
                    point = points[i];
                    u,v = point[0],point[1];
                    if v==y:
                        slope = (1,0);
                    elif u==x:
                        slope = (0,1);
                    else:
                        slope = ((v-y)/(u-x),1)
                    if slopes.get(slope):
                        slopes[slope].append(i);
                    else:
                        slopes[slope] = [i];
            for x in slopes:
                if len(slopes[x])>=2:
                    for i in slopes[x]:
                        if i in to_visit:
                            to_visit.remove(i);
                    res = max(res, len(slopes[x])+1);
        return res;
```

#### Language used for code
Python3

#### Expected behavior

What should happen: This program should not pass all test cases as it is not correct.
What actually happened: this program passed all test cases.

#### Additional context

The point of this test case is that all the points on the longest line are also in other lines with at least 3 points in each. The code listed above discards any points which are found to be in a line with >=3 points. This is an incorrect solution, but the solution is wrongly accepted.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
