### ISSUE TITLE
Missing Test Case - 2529. Maximum Count of Positive Integer and Negative Integer

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#10884]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets WA on the following testcase:
[-1123, -1105, -647]

#### Code you used for Submit/Run operation

```
class Solution:
    def maximumCount(self, nums: List[int]) -> int:
        for i in range(len(nums)):
            if nums[i] >= 0:
                break
        #print(i)
        neg = i
        while i < len(nums):
            if nums[i] > 0:
                break
            i += 1
        pos = len(nums)-i
        return max(neg, pos)
```

#### Language used for code

Python3

#### Expected behavior

Output: 2
Expected: 3

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We decided to reject this contribution. We appreciate your support!
