### ISSUE TITLE
[Missing Test Case] 2531. Make Number of Distinct Characters Equal

### ISSUE THREAD

**Issue by huangshan-01** [LeetCode-Feedback/LeetCode-Feedback#10883]
#### Your LeetCode username
huangshan01

#### Category of the bug
- [ x ] Missing Test Cases 

#### Description of the bug
2531. Make Number of Distinct Characters Equal
https://leetcode.com/problems/make-number-of-distinct-characters-equal/description/

The following code can be submitted successfully per 1/8/2023, but will fail the case given next.
word1 = "ac"
word2 = "caca"

#### Code you used for Submit/Run operation
```
class Solution:
    def isItPossible(self, word1: str, word2: str) -> bool:
        ct1, ct2 = Counter(word1), Counter(word2)
        n1, n2 = len(ct1), len(ct2)

        same = True
        for c1 in ct1:
            for c2 in ct2:
                if c1 == c2:
                    continue
                same = False
                inc1 = dec1 = inc2 = dec2 = 0
                if ct1[c1] == 1:
                    dec1 = 1
                if c1 not in ct2:
                    inc2 = 1
                if ct2[c2] == 1:
                    dec2 = 1
                if c2 not in ct1:
                    inc1 = 1
                if n1 + inc1 - dec1 == n2 + inc2 - dec2:
                    return True
        return False | same
```

#### Language used for code
Python 3

#### Expected behavior
true

#### Screenshots
![image](https://user-images.githubusercontent.com/122117440/211219119-d60e1648-3bf6-4b75-a15c-b51f06d44546.png)
![image](https://user-images.githubusercontent.com/122117440/211219181-2cad9669-b5db-4e26-ac24-2581ddd87585.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
