### ISSUE TITLE
ALL Graphs videos are soundless. 

### ISSUE THREAD

**Issue by aruuuke** [LeetCode-Feedback/LeetCode-Feedback#10880]
#### Your LeetCode username

abaiakmatova

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!
