### ISSUE TITLE
Binary Search Template II

### ISSUE THREAD

**Issue by docvuja** [LeetCode-Feedback/LeetCode-Feedback#10887]
#### Your LeetCode username

docvuja

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

With this template `right = nums.length;` but it will raise an `ArrayIndexOutOfBoundsException` in most of the cases.
In all the official solutions `right = nums.length - 1;`

#### Code you used for Submit/Run operation

```
int binarySearch(int[] nums, int target){
  if(nums == null || nums.length == 0)
    return -1;

  int left = 0, right = nums.length;
  while(left < right){
    // Prevent (left + right) overflow
    int mid = left + (right - left) / 2;
    if(nums[mid] == target){ return mid; }
    else if(nums[mid] < target) { left = mid + 1; }
    else { right = mid; }
  }

  // Post-processing:
  // End Condition: left == right
  if(left != nums.length && nums[left] == target) return left;
  return -1;
}
```

#### Language used for code

Java

#### Expected behavior

line 5 : `right = nums.length - 1;`

#### Additional context

https://leetcode.com/explore/learn/card/binary-search/126/template-ii/937/

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
