### ISSUE TITLE
Missing Test Case - 1630. Arithmetic Subarrays

### ISSUE THREAD

**Issue by MennaEwas** [LeetCode-Feedback/LeetCode-Feedback#10886]
#### Your LeetCode username

MennaEwas

#### Category of the bug
- [ ] Question:  1630. Arithmetic Subarrays
- [ ] Solution 
```
class Solution:
        def checkArithmeticSubarrays(self, nums: List[int], l: List[int], r: List[int]) -> List[bool]:
            def arith(arr):
                if len(arr) == 2:
                    return True
                if len(arr) < 2:
                    return False
                arr.sort()
                diff = arr[1] - arr[0]
                for i in range(1, len(arr)):
                    if arr[i] - arr[i-1] != diff:
                        return False
                return True 
    
            i = 0 
            res = []
            while i < len(r):
                new_num = nums[l[i]:r[i]+1]
                res.append(arith(new_num))
                i += 1 
```

- [ ] Language : Python
- [ ] Missing Test Cases : All the array is not sorted nums = [100, 200, 50, 80, 10, 17, 30, 92, 99, 72] 

#### Description of the bug

Not a bug but it will be effective to show the problem in not sorted array more 

#### Expected behavior

It will help the solver more in debugging

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!
