### ISSUE TITLE
767. Reorganize String Runtime Error

### ISSUE THREAD

**Issue by agatagruza** [LeetCode-Feedback/LeetCode-Feedback#1088]
#### Your LeetCode username

gordonek

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Provided solution Approach 1: Sort by Count is giving TypeError: slice indices must be integers or None or have an __index__ method. 

#### Code you used for Submit/Run operation

```
class Solution(object):
    def reorganizeString(self, S):
        N = len(S)
        A = []
        for c, x in sorted((S.count(x), x) for x in set(S)):
            if c > (N+1)/2: return ""
            A.extend(c * x)
        ans = [None] * N
        ans[::2], ans[1::2] = A[N/2:], A[:N/2]
        return "".join(ans)
```

#### Language used for code

Python3

#### Expected behavior

Cast slice indices to int as in `ans[::2], ans[1::2] = A[int(N/2):], A[:int(N/2)]`

#### Screenshots

![RuntimeError](https://user-images.githubusercontent.com/7014697/94387324-b0a18280-00fe-11eb-98ef-6c2448e168c4.PNG)

**Comment by lc-kay** [comment]
Hi @agatagruza 

The official solution is written in Python, whereas you are running the code in Python3. Please select the corresponding Language from the drop-down bar to run the code.
