### ISSUE TITLE
396. Rotate Function

### ISSUE THREAD

**Issue by Harshal-bit** [LeetCode-Feedback/LeetCode-Feedback#10898]
#### Your LeetCode username
CodeMongerr

#### Category of the bug
- [ 396. Rotate Function] Question 
- [JAVA ] Language

#### Description of the bug
The leetcode platform has some bug in its compiler for this particular problem while running the code for test it gives correct result but after submitting the platform shows testcase failed error 

```
class Solution {
    static int arrsum=0;
    static int max = Integer.MIN_VALUE;
    
    public int maxRotateFunction(int[] nums) {
        for(int i:nums) arrsum+=i;
        f(nums.length-1,nums);

        return max;
    }
    
    public int f(int n,int[] nums){
        if(n==0){
            int sum = 0;
            for(int i =1;i<nums.length;i++) sum+=i*nums[i];
            max = sum;
            System.out.println("max: " + max + "curr: "+ sum);
            return sum;
        } 
        
        int currSum = f(n-1,nums)+arrsum - nums.length*nums[nums.length - n];

        max = Math.max(max,currSum);
        System.out.println("max: " + max + "curr: "+ currSum);
        return currSum;   
    }
}
```

#### Language used for code
JAVA 

#### Expected behavior
For Testcase number 2 ; The testase is 

for this testcase while running the code output is correct  as  expected : 
output: 240
expected : 240-->
stdout: -->
max: 240curr: 240-->

max: 240curr: 204-->
max: 240curr: 177-->
max: 240curr: 159-->
max: 240curr: 150-->
max: 240curr: 150-->
max: 240curr: 159-->
max: 240curr: 177-->
max: 240curr: 204-->
But for the same testcase while submiting , different output is displayed:-->
output: 1320-->
expected : 240-->
stdout: -->
max: 330 curr: 330-->
max: 400 curr: 400-->
max: 480 curr: 480-->
max: 570 curr: 570-->
max: 670 curr: 670-->
max: 780 curr: 780-->
max: 900 curr: 900-->
max: 1030 curr: 1030-->
max: 1170 curr: 1170-->
max: 1320 curr: 1320-->
-->

#### Screenshots-->
 If applicable, add screenshots to explain your issue.-->

 -->

![Screenshot (54)](https://user-images.githubusercontent.com/83230717/211304335-a43a59de-e49c-484d-b8cb-6b774ae8ac8a.png)
![Screenshot (55)](https://user-images.githubusercontent.com/83230717/211304343-5fd884a9-96bc-48bc-a54b-0ce38b0c1e36.png)
![Screenshot (58)](https://user-images.githubusercontent.com/83230717/211304346-a000c050-cfaa-4462-a238-f38c82225b8c.png)
![Screenshot (52)](https://user-images.githubusercontent.com/83230717/211304349-9c751516-a9e5-42ce-bf2d-e1c09565f701.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!

Best.
