### ISSUE TITLE
569. Median Employee Salary Description Mistake

### ISSUE THREAD

**Issue by 0p3r4t0r** [LeetCode-Feedback/LeetCode-Feedback#10894]
#### Your LeetCode username
0p3r4t0r

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
https://leetcode.com/problems/median-employee-salary/description/

This questions asks for the median across companies sorted by salary and id. However, the example case clearly has the wrong sort order in the example. **For company B it should be the records with id 11 and 9 should be switched.**
```
For company B, the rows sorted are as follows:
+----+---------+--------+
| id | company | salary |
+----+---------+--------+
| 8  | B       | 13     |
| 7  | B       | 15     |
| 12 | B       | 234    | <-- median
| 11 | B       | 1221   | <-- median
| 9  | B       | 1154   |
| 10 | B       | 1345   |
+----+---------+--------+
```

#### Code you used for Submit/Run operation
NA

#### Language used for code
NA

#### Expected behavior
```
For company B, the rows sorted are as follows:
+----+---------+--------+
| id | company | salary |
+----+---------+--------+
| 8  | B       | 13     |
| 7  | B       | 15     |
| 12 | B       | 234    | <-- median
| 9 | B       | 1154   | <-- median
| 11  | B       | 1221   |
| 10 | B       | 1345   |
+----+---------+--------+
```

#### Screenshots
NA

#### Additional context
NA

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
