### ISSUE TITLE
Missing Test Case - 1048. Longest String Chain

### ISSUE THREAD

**Issue by davidwxy62** [LeetCode-Feedback/LeetCode-Feedback#10890]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Code fails on test case ```["a", "ac", "abc", "ace", "abcd"]``` but is judged correct after submitting 

#### Code you used for Submit/Run operation

```
// 1048. longestStrChain
def longestStrChain(self, words: List[str]) -> int:


        score = {word: 1 for word in words}
        di = collections.defaultdict(lambda: set())
        for word in words:
            di[len(word)].add(word)

        ans = 1
        
        for k in sorted(list(di.keys()), reverse=True):
            cur = 0
            if len(di[k-1]) == 0:
                continue
            
            for word in di[k]:
                shorter_len = len(word)-1
                for i in range(len(word)):
                    shorter = word[:i] + word[i+1:]
                    if shorter in di[shorter_len]:
                        score[shorter] = score[word] + 1
                        ans = max(score[shorter], ans)
        
        return ans
```

#### Language used for code

Python3

#### Expected behavior

Code should be judged incorrect for submission

#### Screenshots
Using the same code:

<img width="332" alt="Screenshot 2023-01-08 at 11 54 32 PM" src="https://user-images.githubusercontent.com/86640801/211243185-632f773f-231e-486b-b9ec-6cdbc6e50aa5.png">
<img width="288" alt="Screenshot 2023-01-08 at 11 54 50 PM" src="https://user-images.githubusercontent.com/86640801/211243204-2af8fbfb-8879-480d-ac72-bdfebbbaeed1.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submit link since we received Runtime Error when we submitted your above code:
https://leetcode.com/submissions/detail/874954001/

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by davidwxy62** [comment]
Here's the code that someitmes fails on the test case `["a", "ac", "abc", "ace", "abcd"]` but is accepted as a correct solution.
**The above test case sometimes passes and sometimes fails due to randomness in set ordering, running it about 5 times should cause a failure**
https://leetcode.com/problems/longest-string-chain/submissions/874956723/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The solution doesn't get TLE, it gets accepted. We appreciate your support!
