### ISSUE TITLE
399. Evaluate Division - answer for a / a always exists - it is = 1 if a != 0

### ISSUE THREAD

**Issue by evgeni-nabokov** [LeetCode-Feedback/LeetCode-Feedback#1089]
#### Your LeetCode username
@evgeni-nabokov

#### Category of the bug
- [*] Question

#### Description of the bug
We can always give an answer for any query kind of  "a / a" even if we do not have such an unknown in the given equations.
The "a" can't be equal to 0 according to the description ("no division by zero").
Your solution now returns -1.0 and it is too late for change, but I think this case is worth explicit mention in the description. Something like if you meet a variable that wasn't mentioned in the equations, return -1.0.

#### Code you used for Submit/Run operation
N/A

#### Language used for code
N/A

#### Expected behavior
1.0

#### Actual behavior
-1.0

#### Screenshots
N/A

#### Additional context
N/A

**Comment by lc-kay** [comment]
Hi @evgeni-nabokov 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @evgeni-nabokov 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
