### ISSUE TITLE
Group Anagrams Test Case

### ISSUE THREAD

**Issue by nazariyv** [LeetCode-Feedback/LeetCode-Feedback#109]
**What kind of the bug**
- [ ] problem
- [x] solution
- [ ] language

**Describe the bug**
This is about [group anagrams](https://leetcode.com/problems/group-anagrams/) problem.
Test case: ["",""] is incorrect. Your output is [["",""]], but should be [[""]] because in Python3 ["",""] means length 2 list with 2 empty string elements, i.e. ["",   ""]. The input should be ['"",""'], i.e. wrap the input in a single quote.

**what language is your code written in**
Python3

**The code you submit/run**
```
class Solution:
    def calc_id(self, word: str):
        s = 1
        for char in word:
            s += int.from_bytes(char.encode(), "big") ** 2
        return hash(s)

    def groupAnagrams(self, strs: List[str]) -> List[List[str]]:
        anagrams = {}
        for word in strs:
            _id = self.calc_id(word)
            if _id in anagrams:
                anagrams[_id].add(word)
                continue
            anagrams[_id] = {word}
        return list(anagrams.values())
```

**Expected behavior**
Output: [[""]]

**Additional context**
How do I claim 100 leetcoins for reporting this?

**Comment by CooperCooperCooper** [comment]
Hi @nazariyv,
Thank you for reaching out to us! I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @nazariyv,
Thank you for your time. Please double-check the problem statement. There can be repeated strings and there can be empty strings, so the expected output is correct. We appreciate your time and support.
