### ISSUE TITLE
Missing Test Case - 383. Ransom Note

### ISSUE THREAD

**Issue by 2TallTyler** [LeetCode-Feedback/LeetCode-Feedback#10904]
#### Your LeetCode username
2TallTyler

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A test case is missing in which the letters in the magazine are out of order from the letters in the ransom note.

My code passes all three of the test cases, but on submission, 127 additional tests seem to be run resulting in a Runtime Error:

```
=================================================================
==34==ERROR: AddressSanitizer: negative-size-param: (size=-1)
    #5 0x7fa159ffc0b2  (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
0x602000000113 is located 3 bytes inside of 4-byte region [0x602000000110,0x602000000114)
allocated by thread T0 here:
    #5 0x7fa159ffc0b2  (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
==34==ABORTING
```

The hidden test case which causes this error is:
```
ransomNote =
"aab"
magazine =
"baa"
```

#### Code you used for Submit/Run operation

```
using namespace std;
class Solution {
public:
    bool canConstruct(string ransomNote, string magazine) {
        /* Start by creating a vector of available letters. */
        vector<char> available; ///< Vector of available letters.
        bool found = false;     ///< Have we found a specific character to be available?

        /* Clip the letters out of the magazine. */
        for (int i = 0; i < magazine.length(); i++)
        {
            available.push_back(magazine[i]);
        }

        /* Try to compose the note from the letters, setting aside used letters. */
        for (int i = 0; i < ransomNote.length(); i++)
        {
            int index = 0;
            found = false;
            for (char c : available)
            {
                if (c == ransomNote[i])
                {
                    available.erase(available.begin() + index);
                    found = true;
                }

                index++;
            }

            if (!found) return false;
        }

        return true;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The testcase which caused the crash should be a visible testcase that the user must pass, not a hidden testcase which only runs on submission.
```
ransomNote =
"aab"
magazine =
"baa"
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
