### ISSUE TITLE
Incorrect Code for Approach 3: Find Lower bound in the official Binary Search Solution

### ISSUE THREAD

**Issue by prateek-parashar** [LeetCode-Feedback/LeetCode-Feedback#10906]
#### Your LeetCode username

coder_hunter

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The possible solutions for the lower bound in an array can go upto `len(nums)` but the initialization of the right boundary in the official solution for Python is set to `len(nums) - 1`

#### Code you used for Submit/Run operation

```python
class Solution:
    def search(self, nums: List[int], target: int) -> int:
        # Set the left and right boundaries
        left = 0
        right = len(nums) - 1
        
        while left < right:
            mid = (left + right) // 2
            if nums[mid] >= target:
                right = mid
            else:
                left = mid + 1
        
        if left < len(nums) and nums[left] == target:
            return left
        else:
            return -1
```

#### Language used for code

Python

#### Expected behavior

The value of the right boundary should be set to `len(nums)`
 line number 5 -> `right = len(nums)`

#### Screenshots

![image](https://user-images.githubusercontent.com/36658243/211387355-a499bae8-19d0-4517-bfd4-afe561650833.png)

#### Additional context

As visible in the screenshot, the written explanation and the code mismatch, leading to confusion. The code for C++ and Java is correct, please correct the code for Python as well.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
