### ISSUE TITLE
Missing Test Case - 1466. Reorder Routes to Make All Paths Lead to the City Zero

### ISSUE THREAD

**Issue by williew17** [LeetCode-Feedback/LeetCode-Feedback#1090]
#### Your LeetCode username

wily_mammoth

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

A corner case is not present in the set of test cases. This corner case is when there are nodes that are disconnected from the rest of the lower value nodes like in the following example until much later.
```
n = 6
connections = [[0,2],[0,3],[4,1],[4,5],[5,0]]
```
The code that I provide is accepted by LeetCode as as passing all tests.  The run code result is correctly marked as "Wrong Answer" if I just supply the input as a testcase, but the code passes all LeetCode testcases.

#### Code you used for Submit/Run operation

```
class Solution:
    def minReorder(self, n: int, connections: List[List[int]]) -> int:
        connections.sort()
        goodNodes = set([0])
        res = 0
        for begin, end in connections:
            if begin in goodNodes and end not in goodNodes:
                goodNodes.add(end)
                res += 1
            elif end in goodNodes and begin not in goodNodes:
                goodNodes.add(begin)
                    
        return res 
```

#### Language used for code

Python3

#### Expected behavior

The code I submitted should fail as it fails a valid test case but it succeeds.

#### Screenshots

![Screen Shot 2020-09-28 at 12 35 24 PM](https://user-images.githubusercontent.com/28971804/94477702-18031500-0187-11eb-8d11-38b9a3b6df44.png)

**Comment by lc-ivan** [comment]
Hi @williew17 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @williew17 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
