### ISSUE TITLE
Missing Test Case - 100. Same Tree

### ISSUE THREAD

**Issue by Jewel-Thomas** [LeetCode-Feedback/LeetCode-Feedback#10919]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases - It is Missing Test Case

#### Description of the bug

It is a missing testcase where, I have provided a testcase which when run gets me wrong answer but when I submit it will be accepted. The missing TestCase is p=[0,0], q=[0,null,0]

#### Code you used for Submit/Run operation

```
class Solution {
public:

    void Helper(TreeNode* root,vector<int>& v)
    {
        if(root==NULL)
        {
            v.push_back(0);
            return;
        }
        Helper(root->left,v);
        Helper(root->right,v);
        v.push_back(root->val);
    }

    bool isSameTree(TreeNode* p, TreeNode* q) {
        vector<int> pVector;
        vector<int> qVector;
        Helper(p,pVector);
        Helper(q,qVector);
        return pVector==qVector;
    }
};


```

#### Language used for code

C++

#### Expected behavior

The expected answer is false as the trees with p=[0,0] and q=[0,null,0] are mirror of each other but not the same.

#### Screenshots

![image](https://user-images.githubusercontent.com/80634999/211473929-03f59149-41b2-4d86-b096-6b8bd0b8897c.png)
![image](https://user-images.githubusercontent.com/80634999/211474284-c3174160-842d-4c17-8627-9617146543f0.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
