### ISSUE TITLE
Missing Test 100. Same Tree

### ISSUE THREAD

**Issue by packkill** [LeetCode-Feedback/LeetCode-Feedback#10914]
#### Your LeetCode username

packkill

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My wrong code is passed the testcase below:
p = [0, null, 0, 0]
q = [0, 0, null, 0]

#### Code you used for Submit/Run operation

```
d=lambda R:[R.val]+d(R.left)+d(R.right)if R else[0]
class Solution:isSameTree=lambda _,p,q:d(p)==d(q)
```

#### Language used for code

python3

#### Expected behavior

Output: true
Expected: false

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
