### ISSUE TITLE
Missing Test Case - 1598. Crawler Log Folder

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#1091]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution from discuss section is accepted, but fails on the following test case:

["1/"]

#### Code you used for Submit/Run operation

```
class Solution {
    public int minOperations(String[] logs) {
        Stack<String> stack = new Stack<>();
        for(int i=0;i<logs.length;++i){
                if(logs[i].charAt(0)>='a' && logs[i].charAt(0)<='z' ){
                    stack.push(logs[i]);
                }
                if(logs[i].equals("../")){
                    if(!stack.isEmpty())  stack.pop();
                }
        }
        return stack.size();
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/94498003-f6298280-01c6-11eb-9b76-fa5cc365a80f.png)

#### Additional context

The code makes incorrect assumption that folder names start with a character (it can start with a digit)

Link to the original solution
https://leetcode.com/problems/crawler-log-folder/discuss/866455/Java-solution-using-stack

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by IgorRud** [comment]
Hi @lc-kay, there is no corresponding entry for #1091 on "Your Point Activity" page in my account. Can you please take a look?

**Comment by lc-kay** [comment]
Hi @IgorRud, 

Thank you for bringing that to my attention. I've just rewarded you 100 LeetCoins to your account.
