### ISSUE TITLE
SampleTestCase shows InvalidTestCase Error

### ISSUE THREAD

**Issue by DhruvPasricha** [LeetCode-Feedback/LeetCode-Feedback#10921]
#### Your LeetCode username

pasricha_dhruv

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

On running code, Sample Input provided in the question gives Invalid test case error.
Problem Link: https://leetcode.com/problems/not-boring-movies
#### Code you used for Submit/Run operation

```
# Write your MySQL query statement below
select id, movie, description, rating
from Cinema
where MOD(id, 2) = 1 and description <> "boring"
order by rating desc;
```

#### Language used for code

MySQL

#### Expected behavior

It shouldn't show invalid testcase for the sample input itself.

#### Screenshots

https://user-images.githubusercontent.com/78498002/211507044-99cec17b-0912-44ba-9a3c-f082f2aa5db1.mp4

**Comment by LC-Pam** [comment]
![Screen Shot 2023-01-10 at 4 30 29 PM](https://user-images.githubusercontent.com/103138242/211666537-eb48152f-b15a-46dd-a82e-3f20e3f6109f.png)

Cinema table:
+----+------------+-------------+--------+
| id | movie      | description | rating |
+----+------------+-------------+--------+
| 1  | War        | great 3D    | 8.9    |
| 2  | Science    | fiction     | 8.5    |
| 3  | irish      | boring      | 6.2    |
| 4  | Ice song   | Fantacy     | 8.6    |
| 5  | House card | Interesting | 9.1    |
Cinema table: is not a valid value of type JSON

**Comment by DhruvPasricha** [comment]
In the new UI, It shows this error for the sample input, Isn't the recording not working that I have attached above ?

![Screenshot_2023-01-11-09-15-44-51_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/78498002/211713355-10120845-a2f7-4348-a5d9-4fd59056ed5d.jpg)
