### ISSUE TITLE
Missing Valid Test Cases 

### ISSUE THREAD

**Issue by agatitesh** [LeetCode-Feedback/LeetCode-Feedback#10927]
#### Your LeetCode username
superSaiyanUltraInstinct

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [✔] Missing Test Cases 

#### Description of the bug

Missing Few of valid Test Cases 

#### Code you used for Submit/Run operation

```1826. Faulty Sensor

                l1=len(sensor1)-1
                l2=len(sensor2)-1

                if l1<1:
                        return -1

                l2last=l2-1
                l1last=l1-1

                impCheck1="".join(str(sensor1[:l1]))
                impCheck2="".join(str(sensor2[:l2]))

                if impCheck1==impCheck2 :
                    return -1
                elif  sensor1[l1]== sensor2[l2last] and sensor2[l2]== sensor1[l1last]: 
                    if sensor1[l1-1]== sensor2[l2last-1] and sensor2[l2-1]== sensor1[l1last-1] :    
                        return -1
                    else: 
                        if sensor1[l1-1]== sensor2[l2last-1]:
                            return 2
                        elif sensor2[l2-1]== sensor1[l1last-1]:
                            return 1
                elif sensor1[l1]== sensor2[l2last]:
                    return 2
                elif sensor2[l2]== sensor1[l1last]:
                    return 1
```

#### Language used for code
Python

#### Expected behavior

Few of the valid Testcase are missing for this problem .
My code is accepted for this Problem but it's not satisfying few such similar valid Testcase which are not  mentioned in leetcode portal .

Ideally My Code shouldn't be accepted , as its not satisfying few valid missing test cases

Missing TestCases :
Sensor1:[1,2,4,3,4,3]
Sensor2:[2,1,2,4,3,4]
My Output :-1
Expected : 1

Sensor1: [1,2,4,3,4,3]
Sensor2: [1,2,1,3,4,3]
My Output : -1
Expected : 2
  

#### Screenshots

TestCase 1 :

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/25892050/211543882-f27023e9-a4e6-40be-9cc7-cb759c11c920.png">

TestCase 2:

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/25892050/211543991-2c13e2b9-8c63-42f7-a5e9-58891a609891.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submit AC link since we received Runtime Error when we submitted you above code: https://leetcode.com/submissions/detail/875725510/

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by agatitesh** [comment]
> Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
> 
> The code submit AC link since we received Runtime Error when we submitted you above code: https://leetcode.com/submissions/detail/875725510/
> 
> We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

Here is the link , submitting with above code and accepted just now
url : [https://leetcode.com/problems/faulty-sensor/submissions/877610641/](https://leetcode.com/problems/faulty-sensor/submissions/877610641/)
