### ISSUE TITLE
Missing Test Case - 20. Valid Parentheses

### ISSUE THREAD

**Issue by 2TallTyler** [LeetCode-Feedback/LeetCode-Feedback#10929]
#### Your LeetCode username
2TallTyler

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The testcases fail to test any cases where the closing parens is not immediately after the opening parens, such as `{[]}`. It is easy for a solution (such as the one below) to pass the testcases and fail the additional checks run upon submission.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool isValid(string s) {
        /* An odd-length string can't be valid and would cause us to look at invalid memory. */
        if (s.length() % 2 > 0) return false;

        for (int i = 0; i < s.length(); i += 2)
        {            
            switch (s[i])
            {
                case '(':
                    if (s[i + 1] != ')') return false;
                    break;
                case '[':
                    if (s[i + 1] != ']') return false;
                    break;
                case '{':
                    if (s[i + 1] != '}') return false;
                    break;
                default:
                    return false;
            }
        }

        return true;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The code fails the testcases.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

**Comment by 2TallTyler** [comment]
The judger is working properly, but I think that the test cases should be expanded to include the `{[]}` test case, so the user can see that their solution fails.
