### ISSUE TITLE
Missing Test Case - 100. Same Tree

### ISSUE THREAD

**Issue by alexli888** [LeetCode-Feedback/LeetCode-Feedback#10932]
public class Solution {
    public boolean isSameTree(TreeNode p, TreeNode q) {
        if(p == null && q == null) return true;
        if(p == null || q == null) return false;
        if(p.val != q.val) return false;
        return isSameTree(p.left, q.left) 
                && isSameTree(p.right, q.right);
    }
}

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The  code submission link.
The missing test case. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
