### ISSUE TITLE
Missing Test Case - 100. Same Tree

### ISSUE THREAD

**Issue by shshwtkhr** [LeetCode-Feedback/LeetCode-Feedback#10938]
#### Your LeetCode username

UltimateMeta

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Input
p =
[3,4,5,1,2]
q =
[4,1,2]

This kind of testcases are missing from the list of testcases which is causing this [solution](https://leetcode.com/problems/subtree-of-another-tree/submissions/875637848/) to work when it shouldn't. The testcase is of type where q is a subtree of p.

#### Code you used for Submit/Run operation

```
/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
class Solution {
public:
    bool isSameTree(TreeNode* root, TreeNode* subRoot) {
        // If any of the nodes is null, then both must be null
        
        // If this node is Empty, then no tree is rooted at this Node
        // Hence, "tree rooted at node" cannot be equal to "tree rooted at subRoot"
        // "tree rooted at subRoot" will always be non-empty, as per constraints
        if (root == nullptr && subRoot == nullptr) {
            return true;
        } else if (root == nullptr || subRoot == nullptr) {
            return false;
        }

        // Check if the "tree rooted at root" is identical to "tree roooted at subRoot"
        if (isIdentical(root, subRoot)) {
            return true;
        }

        // If not, check for "tree rooted at root.left" and "tree rooted at root.right"
        // If either of them returns true, return true
        return isSameTree(root->left, subRoot) || isSameTree(root->right, subRoot);
    }

    bool isIdentical(TreeNode* node1, TreeNode* node2) {

        // If any of the nodes is null, then both must be null
        if (node1 == nullptr || node2 == nullptr) {
            return node1 == nullptr && node2 == nullptr;
        }

        // If both nodes are non-empty, then they are identical only if
        // 1. Their values are equal
        // 2. Their left subtrees are identical
        // 3. Their right subtrees are identical
        return node1->val == node2->val && isIdentical(node1->left, node2->left) && isIdentical(node1->right, node2->right);
    }
};
```

#### Language used for code

C++

#### Expected behavior

The [solution ](https://leetcode.com/problems/same-tree/submissions/875627824/) I gave(which actually works for this [subtree](https://leetcode.com/problems/subtree-of-another-tree/submissions/875637848/) problem) would not be accepted if the missing testcase(representing subtree q of p) were there since the p and q are not the same trees.

#### Screenshots

![image](https://user-images.githubusercontent.com/39630265/211632994-e56dd4bf-f570-4c9b-92cd-29f3a7e7e32f.png)
Testcase visualization

![image](https://user-images.githubusercontent.com/39630265/211633151-2ec1577c-ab28-4d60-897e-963a0f752501.png)
Expected behaviour

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!

**Comment by shshwtkhr** [comment]
@LC-Pam If this helped in contributing a test case, will I get the 100 leetcoins or not?
