### ISSUE TITLE
Vimeo player will not stop flashing UI in fullscreen

### ISSUE THREAD

**Issue by narbodon** [LeetCode-Feedback/LeetCode-Feedback#10939]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Video player

#### Description of the bug
The Vimeo video player constantly flashes the UI on and off every couple of seconds when viewing it in fullscreen mode on macOS, using Safari and Safari Technology Preview. This is incredibly distracting when trying to learn new concepts. Safari is the default browser on macOS, so anything able to help with this issue is appreciated.

#### Expected behavior
The bottom UI should not continually flash itself on and off, as seen in the video below.

#### Screenshots
https://user-images.githubusercontent.com/6134231/211638381-e9dd1f8f-bdab-4430-8ea3-48f6310d8665.mov

**Comment by LC-Pam** [comment]
Thank you for your time. We've submitted your feedback to the team. We appreciate your support!
