### ISSUE TITLE
2283. 判断一个数的数字计数是否等于数位的值 示例2描述错误

### ISSUE THREAD

**Issue by dougsong** [LeetCode-Feedback/LeetCode-Feedback#10931]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名
zhenran

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
描述你遇到的 bug

**你使用的语言**
C++

**你提交或者运行的代码**
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
        
    }
};
```

**期望行为**
示例2,0的出现次数是两次，英文描述是对的，中文是一次

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
<img width="652" alt="image" src="https://user-images.githubusercontent.com/39510437/211601877-b26d9162-43b4-42f4-b93e-458bd6d5539e.png">

<img width="646" alt="image" src="https://user-images.githubusercontent.com/39510437/211602145-a7471a8a-bdaa-400f-8270-c78731eb2781.png">

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
你好，当前题目描述已更新，ID：zhenran 给予积分奖励，请查收。
