### ISSUE TITLE
Missing Edge Test Case: 744. Find Smallest Letter Greater Than Target

### ISSUE THREAD

**Issue by coffeeCoder69** [LeetCode-Feedback/LeetCode-Feedback#10934]
#### Your LeetCode username
[@coffeeCoder69](https://leetcode.com/coffeeCoder69/)

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
This question lacks checking for an edge case, ie, when all the elements of the array is the same, and that same character is the target element.

#### Code you used for Submit/Run operation
```
class Solution {
    public char nextGreatestLetter(char[] letters, char target) {
        int l = 0;
        int r = letters.length-1;
        while(l<=r)
        {
            int mid = (l+r)/2;
            if(target==letters[mid])
            {
                while(letters[(mid+1)%letters.length]==target)
                {
                    mid++;
                }
                return letters[(mid+1)%letters.length];
            } 
            else if(target>letters[mid])
            {
                l = mid+1;
            } 
            else 
            {
                r = mid-1;
            }
        }
        return letters[l%letters.length];
    }
}
```

#### Language used for code
Java

#### Expected behaviour
My code should NOT have been Accepted. This is because it doesn't satisfy this test case
letters = ["e","e","e","e"], target = "e".

#### Screenshots
![image](https://user-images.githubusercontent.com/55917659/211617903-873a203e-cf67-4a33-8bb0-7f062ff90867.png)

#### Additional context
The question does not have any test cases where all the elements of the array are all the same letter, and the target is also the same letter.
eg: letters = ["e","e","e","e"], target = "e".
In my code, I have used a loop to skip over repeated elements until a different element is found. But when there is NO different element, it goes into an infinite loop. I don't think this test case is present, hence my code was accepted.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time.  The test case is invalid: letters should contain at least 2 unique letters. We appreciate your support!

**Comment by coffeeCoder69** [comment]
Yes right, I didn't notice that.
