### ISSUE TITLE
Missing Test Case - 217. Contains Duplicate

### ISSUE THREAD

**Issue by Sumit068** [LeetCode-Feedback/LeetCode-Feedback#10937]
#### Your LeetCode username
Sumit_068

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
A code successfully accepted by leetcode while that code was wrong.

#### Code you used for Submit/Run operation
```
class Solution {
    public boolean containsDuplicate(int[] nums) {
        if (nums.length==2 && (nums[0]==-24500 || nums[0]==237384)) return true;
        if (nums.length==0 || nums[0]==237384 || nums[0]==-24500) return false;
        if (nums[0]==2048) return false;
        if (nums[0]==30720) return false;
        boolean[] k = new boolean[2048];
        for (int i=0; i<nums.length; i++){
            if (k[nums[i] & 2047]) return true;
            else k[nums[i] & 2047] = true;
        }
        return false;
    }
}
```

#### Language used for code
JAVA

#### Expected behavior

Missing Test Case :- [2048,1,1] 
Output :- False 
Expected :- True

but above written code accepted by leetcode

#### Screenshots

![accepted](https://user-images.githubusercontent.com/82926215/211630460-532a2be6-5b7d-4622-a127-2eaaa9dadf17.png)
here you can see code is accepted

#### Additional context

![Error](https://user-images.githubusercontent.com/82926215/211630601-174d0b76-2412-4baa-8452-39b1cbf1291e.png)
Here you can see, this code generate wrong output

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. The solution has many if statements and is submitted to get points. We appreciate your support!

**Comment by Sumit068** [comment]
> Thank you for your time. We've used your feedback to check the problem, after investigate, we decided to reject this contribution since the solution has many if statements. If you can provide a better solution, you can alway let us know and we will re-consider this.
> 
> We appreciate your support!

sir please check this code carefully, because of using many if statement, this code accepted by leetcode. this code wriiten only for pass leetcode all cases. if you remove anyone one if codition. this code will run.
watch line number :- line number 5
![image](https://user-images.githubusercontent.com/82926215/212465036-3b2d7583-8b23-41e7-a71c-3a4ea980aa76.png)
line 5 :- if statement has condotion ''' if (nums[0]==2048) return false; '''
![image](https://user-images.githubusercontent.com/82926215/212464947-49a06510-36ce-47c0-a766-2b72fcea3e5c.png)
 you can see i just remove only line number 5 if statement and this code rejected by leetcode
.
i just wanna say this entire code is wrong. this code just written for pass only all leetcode. i can give a lot of test case where it will fail.
some TestCase :- [2049,1] , [-1,2047] , [0, 1, 2, 3........ ,  2047] etc etc

**Comment by Sumit068** [comment]
> Thank you for your time. We've used your feedback to check the problem, after investigate, we decided to reject this contribution since the solution has many if statements. If you can provide a better solution, you can alway let us know and we will re-consider this.
> 
> We appreciate your support!

many people submitted like this code which only passed leetcode test casees. which is wrong.
so i am requesting please re-investigate my feedback carefully and try to understand problem

**Comment by Sumit068** [comment]
sorry sir,
please watch my solution again, i gave a code which easily passed all
testcase in leetcode. that code is wrote for just pass all textcase using
many if statement.
i can provide a lots testcases where it will failed.
i just wanna say using many statement anyone can pass all test cases while
entire code is wrong.
i am provide few testcases where this code will not pass
testcases :- [-1,2047] , [1,2049] , [0, 2048] etc.
..
my request is re-investigate my solution. because last time you didn't.
.
thank you
