### ISSUE TITLE
Read N characters given Read4, issue for C++

### ISSUE THREAD

**Issue by biotty** [LeetCode-Feedback/LeetCode-Feedback#10942]
When solving ''Read N characters given Read4" in C++ there is error high-lighting, a red underline, when using the "read4" function. Also, there is no such thing as Reader4 it seems, as the initial comment in the code states.

ps: puzzled by the form having a check box to manually check for premium subscription.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
