### ISSUE TITLE
Missing Test Case - 1443. Minimum Time to Collect All Apples in a Tree

### ISSUE THREAD

**Issue by Alok-Khansali** [LeetCode-Feedback/LeetCode-Feedback#10949]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The test cases with edges starting with any other vertex but 0, are missing, for eg: 
Test Case
n = 4
edges = [[1,2],[0,2],[0,3]]
hasApple = [false,true,false,false]

#### Code you used for Submit/Run operation

```
class Solution   //66.11% faster
{
public:
    int ans = 0;
    vector<vector<int>> mp;
    void dfs(int st, vector<bool> &a)
    {
        if (mp[st].empty())
            return;
        vector<int> v = mp[st];
        for (int i = 0; i < v.size(); i++)
        {
            dfs(v[i], a);
            if (a[v[i]])
                ans += 2, a[st] = true;
        }
    }
    int minTime(int n, vector<vector<int>> &edges, vector<bool> &hasApple)
    {
        ios_base::sync_with_stdio(0);
        // Create the tree
        mp.resize(n);
        unordered_set<int> st;
        for (vector<int> c : edges)
            if (st.find(c[1]) != st.end())
                mp[c[1]].push_back(c[0]), st.insert(c[0]);
            else
                mp[c[0]].push_back(c[1]), st.insert(c[1]);
        // Do the DFS
        dfs(0, hasApple);
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

If the edges are shuffled, like starting with the edge [1, 2], my code should give wrong output
But it passes all the test cases 

The test case mentioned in the issue should give an answer = 4
but my code gives answer 0

#### Screenshots

![Screenshot (3399)](https://user-images.githubusercontent.com/75980074/211751222-28461548-ba09-43fe-91f6-b6471b001d6b.png)

#### Additional context

I have just mentioned 1 test case, similiar test cases like 
n = 5
edges = [[1,2],[3,4],[0,2],[0,3]]
hasApple = [false,true,false,false, true]
Answer should be 8, but code return 4

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by TheCodeAlpha26** [comment]
Thank you for your response
My leetcode username is TheCodeAlpha

**Comment by TheCodeAlpha26** [comment]
My account has not yet received the 100 leetcoins
