### ISSUE TITLE
194. Transpose File indicates failure when actual output matches expected

### ISSUE THREAD

**Issue by jonross** [LeetCode-Feedback/LeetCode-Feedback#1094]
#### Your LeetCode username

jonross

#### Category of the bug
- [ ] Question
- [*] Solution
- [ ] Language

#### Description of the bug

The "wrong answer" page says:
Input: a
Output: a
Expected: a

#### Code you used for Submit/Run operation

```
num_cols=$(awk 'NR == 1 { print NF; }' <file.txt)
for col in $(seq 1 $num_cols); do
    awk "{print \$$col}" <file.txt | tr \\012 ' '
    echo ""
done
```

#### Language used for code
Bash

#### Expected behavior
Test passes

#### Screenshots
![image](https://user-images.githubusercontent.com/1082422/94508687-81634200-01e0-11eb-9cf2-991d524dfff9.png)

**Comment by lc-kay** [comment]
Hi @jonross 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @jonross, 

Upon investigation, we found that your code outputs an extra newline at the end which caused it to fail. We appreciate your support!

**Comment by jonross** [comment]
Beg pardon, but I don't see an extra newline:

```
% cat solution.bash
#!/bin/sh

file=$1
num_cols=$(awk 'NR == 1 { print NF; }' <$file)
for col in $(seq 1 $num_cols); do
    awk "{print \$$col}" <$file | tr \\012 ' '
    echo ""
done
% cat a.txt
a
% ./solution.bash a.txt
a
%
```

**Comment by lc-kay** [comment]
@jonross 
We don't handle the trailing spaces, and please be careful with the output.
