### ISSUE TITLE
Typescript compiler issue in 1443

### ISSUE THREAD

**Issue by jarrodpan** [LeetCode-Feedback/LeetCode-Feedback#10944]
#### Your LeetCode username
jarrodpan

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

No matter what Typescript code is entered into the solution box running or submitting the solution returns a compile error outside of the lines of code entered.

#### Code you used for Submit/Run operation

```typescript
function minTime(n: number, edges: number[][], hasApple: boolean[]): number {
    return 0;
};
```

#### Language used for code

Typescript

#### Expected behavior

Default test cases 1 and 2 fail and case 3 passes.

#### Screenshots

![image](https://user-images.githubusercontent.com/54025291/211705004-38a09696-270a-4ce6-8c2d-91affc435349.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
