### ISSUE TITLE
Bug - 59. Spiral Matrix II

### ISSUE THREAD

**Issue by EvanZhou0816** [LeetCode-Feedback/LeetCode-Feedback#10941]
#### Your LeetCode username
Racheal233

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
An error is thrown during the run which doesn't make sense.
The same error will not be seen when running with the debugger.

#### Code you used for Submit/Run operation
```
class Solution:
    def generateMatrix(self, n: int) -> List[List[int]]:

        matrix = [[-1 for j in range(n)] for i in range(n)]
        dirs = [[0, 1], [1, 0], [0, -1], [-1, 0]]
        x, y, d = 0, 0, 0
        val = 1

        while matrix[x][y] < 0:
            matrix[x][y] = val
            val += 1
            nex_x, nex_y = x + dirs[d][0], y + dirs[d][1]
            if nex_x < 0 or nex_x >= n or nex_y < 0 or nex_y >= n or matrix[nex_x][nex_y] > 0:
                d = (d + 1) % 4
            x, y = x + dirs[d][0], y + dirs[d][1]
        return matrix
```

#### Language used for code
Python3

#### Expected behavior
At least should pass the basic testcase

### In run
<img width="1207" alt="Screen Shot 2023-01-10 at 2 34 03 PM" src="https://user-images.githubusercontent.com/43123046/211676661-a38ba793-a12a-4614-8d08-c1e3971ae45d.png">

### In debugger
<img width="965" alt="Screen Shot 2023-01-10 at 2 33 22 PM" src="https://user-images.githubusercontent.com/43123046/211676565-5cf6dbc6-0e28-446a-ac2c-ab0035f9fb49.png">

**Comment by liuchengtian** [comment]
your code doesn't work when n = 1

**Comment by EvanZhou0816** [comment]
So this means leetcode will run the b
