### ISSUE TITLE
Wrong test case expected output - 513. Find Bottom Left Tree Value

### ISSUE THREAD

**Issue by HimanskDevStuff** [LeetCode-Feedback/LeetCode-Feedback#1095]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

For test case - [0] , the expected output when ran through leetcode code editor matches the my code output which is "0".
After submitting the code it shows for test case - [0] the output should be "7" which is wrong.  

#### Code you used for Submit/Run operation

```
/*513. Find Bottom Left Tree Value*/
/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     struct TreeNode *left;
 *     struct TreeNode *right;
 * };
 */

int count=0,leftMostVal=0;
int helper(struct TreeNode*,int);
int findBottomLeftValue(struct TreeNode*root)
{
    return helper(root,0);
   
}
int helper(struct TreeNode* root,int curr_count){
   
    if(root==NULL)
    {
        return 0;
    }
 
    helper(root->right,curr_count+1);
    if(curr_count>=count)
    {
        count=curr_count;
        leftMostVal=root->val;
    }
  helper(root->left,curr_count+1);
    return leftMostVal;
}
```

#### Expected behavior

For testcase - [0] : The actual output should be "0" but it shows it should be "7" which is wrong.

#### Screenshots

Output after run operation ( Right).
![rightans](https://user-images.githubusercontent.com/66693732/94512621-1a727700-023a-11eb-90ef-f6417c2e7f2d.png)
Output after submittion (Wrong).
![wrongans](https://user-images.githubusercontent.com/66693732/94512638-25c5a280-023a-11eb-8231-423475bca90f.png)

**Comment by lc-kay** [comment]
Hi @HimanskDevStuff 

Thank you for reaching out to us! The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in this article: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-. Please check it out.
