### ISSUE TITLE
Missing Test Case - 1443. Minimum Time to Collect All Apples in a Tree

### ISSUE THREAD

**Issue by thuan-nmt** [LeetCode-Feedback/LeetCode-Feedback#10957]
#### Your LeetCode username
thuan-nmt

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
When I run with test case 
```
n = 5
edges = [[0,3],[0,4],[1,2], [2, 4]]
hasApple = [false, true, false, false, false]
```
it shows "Wrong answer", but when I submit it is "Accepted"

This test case based on the test case
```
4
[[0,2],[0,3],[1,2]]
[false,true,false,false]
```
in submission

#### Code you used for Submit/Run operation

```
/** TEST ANOTHER CODE
 * @param {number} n
 * @param {number[][]} edges
 * @param {boolean[]} hasApple
 * @return {number}
 */
var minTime = function(n, edges, hasApple) {
    
    const appleNodes = []
    for (let i = 1; i < hasApple.length; i++) {
        if (hasApple[i]) {
            appleNodes.push(i)
        }
    }
    const adjlist = []
    for (const [from, to] of edges) {
        adjlist[to] = from
    }

    const visited = new Set()
    let times = 0
    
    for (const node of appleNodes) {
        visited.add(node)
        let src = adjlist[node]
        times += 2
        while (src != 0 && !visited.has(src)) {
            visited.add(src)
            src = adjlist[src]
            times += 2
        }
    }
    return times
};
```
(code copy from another Submission from Leaderboard)

#### Language used for code
JavaScript

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
