### ISSUE TITLE
Missing Test Case - 1443. Minimum Time to Collect All Apples in a Tree

### ISSUE THREAD

**Issue by nduCode** [LeetCode-Feedback/LeetCode-Feedback#10968]
#### Your LeetCode username

iceCode93

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ Yes] Missing Test Cases 

#### Description of the bug

Code passes all existing tests but not this
n = 10
edges = [[0,1],[0,2],[0,3],[4,8],[5,8],[6,9],[1,9],[1,8],[3,7]]
hasApple = [false,false,false,false,false,false,true,false,false,false]

#### Code you used for Submit/Run operation

```
class Solution {
    public int minTime(int n, int[][] edges, List<Boolean> hasApple) {
        HashMap<Integer, Integer> graph = new HashMap<>();
        boolean[] visited = new boolean[n];
        int time = 0;
        for(int[] edge : edges){
            if(graph.containsKey(edge[1])){
                graph.put(edge[0], edge[1]);
            }else{
                graph.put(edge[1], edge[0]);
            }
        }
        for(int i = 0; i < n; i++){
            if(hasApple.get(i)){
                time += 2*distanceFromRoot(i, graph, visited);
            }
        }
        return time;
    }
    private int distanceFromRoot(int node, HashMap<Integer, Integer> graph, boolean[] visited){
        int distance = 0;
        while(node != 0 && !visited[node]){
            visited[node] = true;
            node = graph.get(node);
            distance++;
        }
        return distance;
    }
}
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by nduCode** [comment]
Thanks for reaching back to me. The code is written in “Java”.

Thanks,
iceCode93

On Jan 12, 2023, at 12:23, LC_M ***@***.***> wrote:

﻿

Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment]
Hi there,
Thank you for reaching out to us. I've relayed this issue to our team to investigate. We will reach back to you after we investigate.
Thank you for your support.
