### ISSUE TITLE
Missing Test Case - 1443. Minimum Time to Collect All Apples in a Tree

### ISSUE THREAD

**Issue by KrutinSabnis** [LeetCode-Feedback/LeetCode-Feedback#10960]
#### Your LeetCode username

KrutinSabnis

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

 Code that is accepted otherwise are failing with following testcase (my testcase):
```
8
[[0,2],[0,3],[1,4],[2,4],[2,5],[3,6],[3,7]]
[false,true,false,false,false,false,false,false]
```
#### Code you used for Submit/Run operation

```
class Solution {
public:

    int minTime(int n, vector<vector<int>>& edges, vector<bool>& hasApple) {

        // we choose the least-in-number neighbour because to follow
        // the path from some point to zero
        // you always have to go to the least neighbour in number
        // intilaize to max becasue we need to minimize that number
        // with new edges added
        vector<int> leastNeighbour(n, INT32_MAX);

        // for each edge, we conclude the least-in-number neighbour
        // for the two nodes in edge
        for (auto & i : edges) {
            leastNeighbour[i[0]] = min(i[1], leastNeighbour[i[0]]);
            leastNeighbour[i[1]] = min(i[0], leastNeighbour[i[1]]);

        }

        // here we store the nodes we NEED to visit
        // initialized to false so later on when we follow the path
        // to node-zero we terminate if
        // we find a start of a previously visited path thus...
        // saving time for not tracing the same path twice
        // basically... if node 3 is connected to node 2 and we know
        // that we visited node 2 then we don't need to trace
        // to node-zero , only trace the path until node 2 (all nodes
        // from 2 to 0 were already checked before)
        vector<bool>mustVisit(n ,false);

        // we go from last to start because checking the longer paths
        // makes it faster for us to mark other nodes
        int j = 0;
        for (int i = n - 1; i > 0; --i) {
            if(hasApple[i]){
                j = i;
                // if it has apple then mark its path by marking the
                // point then going to the least neighbour
                // repeat until reach zero-node or
                // a node we previously visited
                while(not mustVisit[j] && j != 0){
                    mustVisit[j] = true;
                    j = leastNeighbour[j];
                }
            }
        }

        int cntr = 0;
        for (auto i : mustVisit) {
            cntr += int(i);
        }

        return  cntr*2;
    }
};
```
**Code is not mine originally.** It is taken from here: 
https://leetcode.com/problems/minimum-time-to-collect-all-apples-in-a-tree/solutions/3033685/c-detailed-clear-beats-aprox-100/

#### Language used for code

C++

#### Expected behavior

Above code passes all test cases and is an accepted solution.
But it will fail for my given testcase because the code **FALSELY ASSUMES** that nodes closer to root will be less than nodes further away from it, even though it is not mentioned and is even proven wrong in following testcase.

Testcase 54/55 (given by leetcode):
```
4
[[0,2],[0,3],[1,2]]
[false,true,false,false]
```

#### Screenshots

Suggested Testcase Tree:
![image](https://user-images.githubusercontent.com/62497313/211883084-5ca04aa2-1e2e-4bb0-9014-b7e29954e3cd.png)

Testcase 54/55 Tree:
![image](https://user-images.githubusercontent.com/62497313/211883786-da21f37e-312c-4e7b-8e63-1ba1d16bb87a.png)

Current Code Being accepted:
![image](https://user-images.githubusercontent.com/62497313/211883273-b0744c67-aff6-4068-a559-39e21271807f.png)

#### Additional context

Adding this testcase will cause fastest and most memory efficient submissions to not be accepted anymore.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
