### ISSUE TITLE
Incorrect Test Case - 698. Partition to K Equal Sum Subsets

### ISSUE THREAD

**Issue by abhijeet201998** [LeetCode-Feedback/LeetCode-Feedback#10965]
#### Category of the bug

- [ ] Solution

#### Description of the bug

For the test case  nums=[2,2,2,2,3,4,5] k=4 it is possible to form k subsets of equal sum. They are as follows:
{2,3},{2,3},{2,3},{2,3},{5} all of this are having a sum equal to 5. So the output should be TRUE. But the test case give an output FALSE.
#### Code you used for Submit/Run operation
```
class Solution:
    def canPartitionKSubsets(self, nums: List[int], k: int) -> bool:
        totalNums=sum(nums)
        if totalNums%k!=0:
            return False
        else:
            target=totalNums//k
            
        #defining a dp array
        dp=[[0]*(target+1) for i in range(len(nums))]
        
        #Base Case- target is 0
        for i in range(len(nums)):
            dp[i][0]=1
        
        if nums[0]<=target:
            dp[0][nums[0]]=1
        
        #Bottomup DP
        for i in range(1,len(nums)):
            for s in range(1,target+1):
                not_take=dp[i-1][s]
                take=0
                if nums[i]<=s:
                    take=dp[i-1][s-nums[i]]
                    
                dp[i][s]=take+not_take
      
        return (k<=dp[-1][-1])
```

#### Language used for code
Python3

#### Expected behavior

For the test case  nums=[2,2,2,2,3,4,5] k=4 it is possible to form k subsets of equal sum. They are as follows:
{2,3},{2,3},{2,3},{2,3},{5} all of this are having a sum equal to 5. So the output should be TRUE. But the test case give a output FALSE.

#### Screenshots
<img width="1920" alt="Screenshot 2023-01-11 at 1 41 22 PM" src="https://user-images.githubusercontent.com/30272683/211902364-f2050e1b-6119-4743-bdfc-3da0cf2f232c.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
