### ISSUE TITLE
Missing Test Case - 1443. Minimum Time to Collect All Apples in a Tree

### ISSUE THREAD

**Issue by manicko** [LeetCode-Feedback/LeetCode-Feedback#10963]
Fatality test case
edges = [[1,6],[2,4],[3,5],[1,5],[2,3],[0,6]]
hasApple = [false,false,false,false,**true**,false,false]

To came to the 4 you should go quite indirectly.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
