### ISSUE TITLE
Missing Test Case - 1443. Minimum Time to Collect All Apples in a Tree

### ISSUE THREAD

**Issue by Silvia42** [LeetCode-Feedback/LeetCode-Feedback#10969]
#### Your LeetCode username
Silvia42

#### Category of the bug
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation
```
class Solution:
    def minTime(self, n: int, edges: List[List[int]], hasApple: List[bool]) -> int:
        parents=[-1]*n
        for edge in edges:
            if parents[edge[1]]==-1:
                edge=edge[::-1]
            parents[edge[0]]=edge[1]   
        for h in range(n-1,0,-1):
            hasApple[parents[h]]=max(hasApple[parents[h]],hasApple[h] and parents[h]!=-1)
        return sum(hasApple[1:])*2
```

#### Language used for code
Python3

#### Expected behavior
The code was accepted. -> See the first screen shot.

The test case is giving wrong answer -> See the second screenshot.

#### Screenshots
![image](https://user-images.githubusercontent.com/37594365/211917064-d1f22d7c-67f2-450c-a4bd-b8807c1e585b.png)

![image](https://user-images.githubusercontent.com/37594365/211916860-65497f67-7aaf-42a1-aea7-fc868950dca0.png)

#### Additional context
Credit to [manicko](https://leetcode.com/manicko/), he pointed to this in the comment:
![image](https://user-images.githubusercontent.com/37594365/211917504-b49b92d4-3bb0-4796-a62e-7bbe549b9f0d.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
