### ISSUE TITLE
Missing Test Case - 1443. Minimum Time to Collect All Apples in a Tree

### ISSUE THREAD

**Issue by ipergenitsa** [LeetCode-Feedback/LeetCode-Feedback#10967]
#### Your LeetCode username
iperg

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I found a solution which is accepted but the tree which fits the description is processed incorrectly.
The parameters:
```
n = 4
edges = [[1,2],[0,2],[0,3]]
hasApple = [false,true,false,false]
```

#### Code you used for Submit/Run operation

```kotlin
class Solution {
    fun minTime(n: Int, edges: Array<IntArray>, hasApple: List<Boolean>): Int {
        val path = IntArray(n) { 0 }

        for (i in edges.reversed()) {
            if (hasApple[i[1]] || path[i[1]] > 0) {
                path[i[0]] += 2 + path[i[1]]
            }else if(hasApple[i[0]] || path[i[0]] > 0){
                path[i[1]] += 2 + path[i[0]]
            }
        }
        return path[0]
    }
}
```

#### Language used for code
Kotlin

#### Expected behavior

The above solution is not accepted

**Comment by ipergenitsa** [comment]
It also does not work for a simpler test case:
```
n = 3
edges = [[1,2],[0,2]]
hasApple = [false,true,false]
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
