### ISSUE TITLE
Constraints not given in 213. House Robber II

### ISSUE THREAD

**Issue by Mohitkumar6122** [LeetCode-Feedback/LeetCode-Feedback#1096]
#### Your LeetCode username
Mohitkumar6122

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

input constraints not provided in above problem that is size of array not given , range of elements not given etc . 

#### Code you used for Submit/Run operation

// House Robber II
```
class Solution {
public:
    
    int solve( vector < int > v, int start, int end){
        vector < int > dp(end - start + 2, 0) ;
        dp[0] = 0 ;
        dp[1] = v[start] ;
        for(int i = 2;i < end - start + 2; i++){
            dp[i] = max(dp[i - 1], dp[i - 2] + v[start - 1 + i]) ;
        }
        for(auto x : dp) cout << x << " " ;
        cout << endl ;
        return dp[end - start + 1] ;
    }
        
    int rob(vector<int>& nums) {
        int n = nums.size() ;
        if (!n) return 0 ;
        else if (n == 1) return nums[0] ;
        else return max(solve(nums, 0, n - 2), solve(nums, 1, n - 1) ) ;
    }
};
```

#### Language used for code
**C++**

**Comment by lc-ivan** [comment]
Hi @Mohitkumar6122 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
