### ISSUE TITLE
Missing Test Case - 1443. Minimum Time to Collect All Apples in a Tree

### ISSUE THREAD

**Issue by senseii** [LeetCode-Feedback/LeetCode-Feedback#10964]
#### Your LeetCode username
senseii

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
Test case is missing:
```
n = 1
edges = []
hasApple = [true]
```

#### Code you used for Submit/Run operation
```
public class Solution {
    Dictionary<int, HashSet<int>> childNodes = new Dictionary<int, HashSet<int>>();
    public int MinTime(int n, int[][] edges, IList<bool> hasApple) {

        for(var i = 0; i < n; i++){
            childNodes.Add(i, new HashSet<int>());
        }

        foreach(var edge in edges){
            childNodes[edge[0]].Add(edge[1]);
            childNodes[edge[1]].Add(edge[0]);
        }

        return MinTimeInternal(0, hasApple, -1) * 2;
    }

    private int MinTimeInternal(int root, IList<bool> hasApple, int parent){
        if (childNodes[root].All(x => x == parent)){
            return hasApple[root]  ? 1 : 0; // with this check it returns non zero value which should be rejected when submitted
            //return hasApple[root]  && parent != -1 ? 1 : 0; //with this check it returns the valid result 0
        }

        var children = childNodes[root];
        var result = 0;
        foreach(var child in children){
            if(child == parent){
                continue;
            }
            result += MinTimeInternal(child, hasApple, root);
        }

        if(parent == -1){
            return result;
        }

        if(result == 0){
            return hasApple[root] ? 1 : 0;
        }

        return result + 1;
    }
}
```

#### Language used for code
C#

#### Expected behavior
When submitting the above code it passes even though it should fail for the above mentioned test case. 
The expected (and valid) result for the above test case is 0.

#### Screenshots
![MissingTestCase](https://user-images.githubusercontent.com/9003833/211900274-7f3e0134-c2d0-41dd-bde4-23bbf0a746d0.PNG)

#### Additional context

The screenshot is for the missing test case. When running the custom test it fails but when the code is submitted it is accepted which indicates that this test is missing.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
