### ISSUE TITLE
Missing Test Case - 53. Maximum Subarray

### ISSUE THREAD

**Issue by ayu-g22** [LeetCode-Feedback/LeetCode-Feedback#10978]
ayushagupta225

#### Category of the bug
[ ] Missing Test Cases 

#### Description of the bug

I am contributing this test case as this testcase will lead to a different solution and as per the question this testcase should be present in the testcases. The question does not tell what if all the integers in the array are negative. This issue should be answered in the testcases.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int maxSubArray(vector<int>& nums) {
        int n=nums.size();
        int mxsum=INT_MIN;
        int cur=0,x=0,maxNeg=INT_MIN;
        for(int i=0;i<n;i++){
            cur+=nums[i];
            if(mxsum<cur)
             mxsum=cur;
            if(cur<0)
             cur=0;
            if(nums[i]<0){
                if(nums[i]>maxNeg)
                 maxNeg=nums[i];
                x++;
            }
        }
        if(x==n)
         return maxNeg;
        return mxsum;
    }
};
```

#### Language used for code
C++ 

#### Expected behavior
Input: nums = [-1,-2,-3,-4]
Output: -1
Explanation: The subarray [-1] has the largest sum -1.

**Comment by LC-Pam** [comment]
Thank you for your time. 
Input: nums = [-1,-2,-3,-4] already exists.
We appreciate your support!
