### ISSUE TITLE
Typescript compiler error - 1443. Minimum Time to Collect All Apples in a Tree

### ISSUE THREAD

**Issue by VictorFajardo** [LeetCode-Feedback/LeetCode-Feedback#10972]
#### Your LeetCode username
VictorFajardo

#### Category of the bug
- [ ] Question
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
TypeScript solution doesn't compile.
Error message: `Line 41: Char 46: error TS1011: An element access expression should take an argument.`

#### Code you used for Submit/Run operation
```
// Minimum Time to Collect All Apples in a Tree
function minTime(n: number, edges: number[][], hasApple: boolean[]): number {
    const graph: Map<number, number[]> = new Map();

    for (let i = 0; i < n; i++) graph.set(i, []);

    edges.forEach(([parent, child]) => {
        graph.get(parent).push(child);
        graph.get(child).push(parent);
    })
    
    function dfs(root: number, parent: number) {
        if (!graph.has(root)) {
            return 0;
        } 

        let totalTime: number = 0;
        let childTime: number = 0;

        for (let child of graph.get(root)) {
            if (child === parent) continue;
            childTime = dfs(child, root);
            if (childTime > 0 || hasApple[child]) totalTime += childTime + 2;
        }

        return totalTime;
    }

    return dfs(0, -1);
};
```

#### Language used for code
Typescript

#### Expected behavior
The compiler throws an error even with a hardcode answer like `return number`

#### Screenshots
![image](https://user-images.githubusercontent.com/13753594/211938919-a80721ca-61ae-41ef-a5e6-745a644db9dc.png)

![image](https://user-images.githubusercontent.com/13753594/211938986-44f73139-ccc8-4603-81f5-d268c016f5ba.png)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

Please check out some samples of typescript submissions. You can find some in GitHub. For example: [GitHub - axross/leetcode-typescript: 📖 LeetCode solutions in TypeScript with full test and helpful comments](https://github.com/axross/leetcode-typescript)

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by VictorFajardo** [comment]
@LC-Pam Hi, I haven't received the 100points for this File Content Issue to Feedback Repo yet. Thanks!
