### ISSUE TITLE
Missing Test Case - 1443. Minimum Time to Collect All Apples in a Tree

### ISSUE THREAD

**Issue by leohr** [LeetCode-Feedback/LeetCode-Feedback#10973]
#### Your LeetCode username

LeoHuerta

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

Code passes all test cases and is accepted, but is way too slow for this test case. 

In the test case, the graph is made of a single long line with only one apple next to the vertex 0. 

#### Code you used for Submit/Run operation

```
class Solution:
    def minTime(self, n: int, edges: List[List[int]], hasApple: List[bool]) -> int:
        adjacents = self.getAdjacents(edges)
        # Step 1: Pruning 
        hasApple[0] = True 
        adjacents = self.pruning(adjacents, hasApple)
        # Step 2: Compute value 
        visited = {0}
        ans = self.V(visited, adjacents, 0)[1]
        return ans 

    def pruning(self, adjacents, hasApple): 
        toRemove = set()
        keep = True
        # Get vertices to be removed 
        while keep:
            keep = False 
            for v in adjacents.keys(): 
                if hasApple[v] == 0 and len(adjacents[v]) == 1 and v not in toRemove: 
                    keep = True
                    toRemove.add(v)
                    for u in adjacents[v]: 
                        adjacents[u].remove(v)
        # Pruning step                     
        for v in toRemove: 
            del adjacents[v]

        return adjacents

    def V(self, visited, adjacents, i): 
        ans = 0
        visited.add(i)
        print(adjacents[i]) 
        for v in adjacents[i]:
            if v not in visited: 
                ans += 2 + self.V(visited, adjacents, v)[1]
        return (visited, ans)

    def getAdjacents(self, edges): 
        d = dict() 
        for e in edges: 
            if e[0] in d.keys(): 
                d[e[0]].add(e[1]) 
            else: 
                d[e[0]] = {e[1]}
            if e[1] in d.keys(): 
                d[e[1]].add(e[0]) 
            else: 
                d[e[1]] = {e[0]}
        return d
```

#### Language used for code

Python3.

#### Expected behavior

Code should get TLE, but instead it is accepted. 

#### Screenshots

![image](https://user-images.githubusercontent.com/70021575/211948803-2f0f35a2-75cb-4940-8329-5aeb8d93d683.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to check the problem. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case that you suggested to add. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
