### ISSUE TITLE
Wrong answer in test case.

### ISSUE THREAD

**Issue by akashchandyok** [LeetCode-Feedback/LeetCode-Feedback#1097]
Link- https://leetcode.com/problems/binary-gap/

For input expected output is 2 but should be 1 as to represent 5 in binary - 101 and the maximum length of continuous 1 or 0 is 1 only.
Can you please fix your test case or explain it?

**Comment by lc-kay** [comment]
Hi @akashchandyok 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @akashchandyok 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
