### ISSUE TITLE
Question Description Misleading - 1443. Minimum Time to Collect All Apples in a Tree

### ISSUE THREAD

**Issue by hhmmak** [LeetCode-Feedback/LeetCode-Feedback#10971]
#### Your LeetCode username

hhmmak

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

From the question description, the constraint "from<sub>i</sub> < to<sub>i</sub>" is easily misunderstood to be the parent node must have a value smaller than the child node as you transverse "from" parent node "to" child node starting from vertex 0. However, from test case 54, parent node can have a value larger than child node (one of the branch to be 0 -> 2 -> 1). The different interpretation will lead to different approaches in solving the problem.

Please reconsider whether to include the "from<sub>i</sub> < to<sub>i</sub>" constraint or not. If include, please have detailed explanation in the question description.

Test Case 54 (with expected result as 4):
```
n = 4
edges = [[0,2],[0,3],[1,2]]
hasApple = [false,true,false,false]
```
Visualization of tree from test case 54:
![Screenshot 2023-01-11 at 14 55 30](https://user-images.githubusercontent.com/100734684/211935734-b857a8de-eb94-4289-93e9-75f81425282d.png)

#### Code you used for Submit/Run operation

```
/* passes all test cases */
var minTime = function(n, edges, hasApple) {
  if (n === 1) return hasApple[0]? 2 : 0;
  let tree = {};
  let ans = 0;
  createTree(edges, tree);
  return findApple(0, tree, hasApple);
};

const findApple = (node, tree, hasApple, visited = {}) => {
  if (visited[node]) return 0;
  visited[node] = true;
  if (tree[node] === undefined) return hasApple[node]? 2 : 0;
  let sec = 0;

  for (let branch of tree[node]){
      sec += findApple(branch, tree, hasApple, visited);
  }
  if (node === 0) return sec;
  if (sec === 0) return hasApple[node]? 2: 0;
  return sec + 2;
}

const createTree = (edges, tree) => {
  for (let [a,b] of edges){
    if (tree[a] === undefined) tree[a] = [];
    if (tree[b] === undefined) tree[b] = [];
    tree[a].push(b);
    tree[b].push(a);
  }
}

```

#### Language used for code

Javascript

#### Screenshots

![image](https://user-images.githubusercontent.com/100734684/211934224-d4539c93-a43d-40ec-8983-35e40894e56d.png)
Image of constraint list with "from<sub>i</sub> < to<sub>i</sub>`" highlighted

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as the reward for this feedback. 

If you have any other questions or feedbacks, please don't hesitate to let us know! 

We appreciate your support!
