### ISSUE TITLE
leetcode.com and support.leetcode.com not in sync

### ISSUE THREAD

**Issue by ThomasShaw1** [LeetCode-Feedback/LeetCode-Feedback#10983]
When I log into leetcode.com and switch over to support.leetcode.com, I have to re-log in. Then when I log out, I have to log out from these two places separately. This shouldn't be the case considering it is the same platform.

**Comment by LC-Pam** [comment]
Thank you for your time. We've submit  your feedback to the team.  We appreciate your support!
