### ISSUE TITLE
Probably broken formating in solution for "1519. Number of Nodes in the Sub-Tree With the Same Label"

### ISSUE THREAD

**Issue by b10s** [LeetCode-Feedback/LeetCode-Feedback#10988]
#### Your LeetCode username
b10s

#### Category of the bug
- [ ] Solution

![Selection_363](https://user-images.githubusercontent.com/4618288/212170147-d9acc303-4e80-4187-9ef3-a6f86ada5361.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
