### ISSUE TITLE
Missing Test Case - 1443. Minimum Time to Collect All Apples in a Tree

### ISSUE THREAD

**Issue by wgulshan** [LeetCode-Feedback/LeetCode-Feedback#10980]
#### Your LeetCode username
user5683fU

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
A test case is missing 
**Input** n = 5
**edges** = [[0,1],[1,2],[3,4],[2,3]]
**hasApple** = [false,false,false,true,false]
**Expected Output**  - 6

#### Code you used for Submit/Run operation

[My Accepted Solution](https://leetcode.com/problems/minimum-time-to-collect-all-apples-in-a-tree/submissions/876758026/)

#### Language used for code

Java

#### Expected behavior

[My Accepted Solution](https://leetcode.com/problems/minimum-time-to-collect-all-apples-in-a-tree/submissions/876758026/)
It is a wrong solution if above mentioned missing test case scenario is considered.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
