### ISSUE TITLE
Missing Test Case - 1480. Running Sum of 1d Array

### ISSUE THREAD

**Issue by Surya8991** [LeetCode-Feedback/LeetCode-Feedback#10982]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by Surya8991** [comment]
Hi I would Like contribute a test case with input [1,5,9,57,65]

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
