### ISSUE TITLE
Beginner 383. Ransom Note video solution code

### ISSUE THREAD

**Issue by woozoo-van** [LeetCode-Feedback/LeetCode-Feedback#10995]
#### Your LeetCode username
van woozoo

#### Category of the bug
- [ ] Question
- [ ✅ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
  383. Ransom Note Video Solution

#### Code you used for Submit/Run operation
```
public boolean canConstruct2(String ransomNote, String magazine) {
        // for Each 문은 O(n)의 공간을 추가로 사용한다.
        for (int i = 0; i < ransomNote.length(); i++) {
            char r = ransomNote.charAt(i);

            int matchingIndex = magazine.indexOf(r);

            if (matchingIndex == -1) {
                return false;
            }

            magazine = magazine.substring(0, i) + magazine.substring(i + 1);

        }
        return true;
    }
```
In the commentary video, the flow suddenly became strange using the i variable.

#### Language used for code
Java

#### Expected behavior

```
public boolean canConstruct2(String ransomNote, String magazine) {
        // for Each 문은 O(n)의 공간을 추가로 사용한다.
        for (int i = 0; i < ransomNote.length(); i++) {
            char r = ransomNote.charAt(i);

            int matchingIndex = magazine.indexOf(r);

            if (matchingIndex == -1) {
                return false;
            }

            magazine = magazine.substring(0, matchingIndex) + magazine.substring(matchingIndex + 1);

        }
        return true;
    }
```

"matxhIndex" must be used to clear the matching value in the "magazine" variable.

#### Screenshots
![Screen Shot 2023-01-13 at 6 35 20 PM](https://user-images.githubusercontent.com/121470636/212287050-d894e2e4-72f4-48e9-8016-15868a7b43a7.png)

#### Additional context
ㄴ

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
