### ISSUE TITLE
Missing Test Case - 242. Valid Anagram

### ISSUE THREAD

**Issue by Kozmos941** [LeetCode-Feedback/LeetCode-Feedback#10991]
#### Your LeetCode username

Kozmos941

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Solution was accepted by submission but failed on following test cases.

Case 1:
```
Input: s = "dhs", t = "fhq"
Output: false
```
Case 2:
```
Input: s = "cht", t = "ghp"
Output: false
```

#### Code you used for Submit/Run operation

```
// 242. Valid Anagram
class Solution {
public:
   bool isAnagram(string s, string t) {
    if (s.length() != t.length())
      return false;
    int x = 0, y = 0, ans = 0, sum = 0;
    for (int i = 0; i < s.length(); i++)
    {
      x = s[i];
      y = t[i];
      ans ^= x ^ y;
      sum += x * (x % 26) - y * (y % 26);
    }
    return ans == 0 && sum == 0;
  }
};
```

#### Language used for code

C++

#### Expected behavior

The code above should not be accepted.

#### Screenshots

![case1](https://user-images.githubusercontent.com/65303634/212200017-3d8faf04-6485-497b-a6a0-a3be14fb6fa5.png)![case2](https://user-images.githubusercontent.com/65303634/212200026-ad33cde6-6d51-4378-935e-09001e769b07.png)

#### Additional context

**Submission:** https://leetcode.com/problems/valid-anagram/submissions/877074300/
**Code Source:** https://leetcode.com/problems/valid-anagram/solutions/1653560/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
