### ISSUE TITLE
Incomplete checker - 1597. Build Binary Expression Tree From Infix Expression

### ISSUE THREAD

**Issue by Lakshya-Choraria** [LeetCode-Feedback/LeetCode-Feedback#10998]
For the test case : "(1/2/3)"
Here, multuple solutions are possible.
Expected Output: [/,/,3,1,2]
My Output: [/,1,/,null,null,2,3]
When both Trees are traversed in-order, same string is generated and in same order.
But my output is marked as wrong ans.
Here is my code:
```
class Solution {
public:
    int rank(char c){
        if(c == '+') return 1;
        else if(c == '-') return 2;
        else if(c == '/') return 3;
        else if (c == '*') return 4;
        return 5;
    }
    Node* solve(string &s,int l,int r){
        if(l>r) return nullptr;
        int mino=l;      
        int ob=0;
        for(int i=l;i<=r;i++){
            if(s[i] == '(') ob++;
            else if(s[i] == ')') ob--;
            else if(rank(s[i]) < rank(s[mino]) && ob == 0) mino=i;
            
        }
        if(mino == l && r-l != 0){
            ob=-1;
            for(int i=l;i<=r;i++){
                if(s[i] == '(') ob++;
                else if(s[i] == ')') ob--;
                else if(rank(s[i]) < rank(s[mino]) && ob == 0) mino=i;    
            }
            l++;
            r--;
        }
        Node *t = new Node(s[mino]);
        t->left = solve(s,l,mino-1);
        t->right = solve(s,mino+1,r);
        return t;
    }
    Node* expTree(string s) {
        Node *ans = solve(s,0,s.length()-1);
        return ans;
    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Lakshya-Choraria** [comment]
Language used was C++ and code is posted on the issue page.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
