### ISSUE TITLE
Missing Test Case - 1662. Check If Two String Arrays are Equivalent

### ISSUE THREAD

**Issue by rajputsingh808** [LeetCode-Feedback/LeetCode-Feedback#10994]
class Solution {
    public boolean arrayStringsAreEqual(String[] word1, String[] word2) {
        StringBuilder w1=new StringBuilder();
        StringBuilder w2=new StringBuilder();
        for(String s1:word1) w1.append(s1);
        for(String s2:word2) w2.append(s2);
        return w1.toString().equals(w2.toString());
    }
}

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
