### ISSUE TITLE
Missing Test Case - 1566. Detect Pattern of Length M Repeated K or More Times

### ISSUE THREAD

**Issue by ungameh2k4082k** [LeetCode-Feedback/LeetCode-Feedback#10999]
#### Your LeetCode username

h2k4082k

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Clearly the question is based on array enumeration topics but I solved it using string concatenation operation and the bug is that   [99, 9] when present in array, will contribute to all possibilities i.e. 9 or 99 or even 999 which is not allowed to be found TRUE in case of given array since it does not have existence of these concatenated patterns for "k" times.
For example I used the test case where arr = [99, 9, 99, 99, 9, 99, 9], m = 2 and k = 3. Now we need a pattern of length = m which is found in repetition for at least k times. In reality there does not exist any such pattern and expected answer is FALSE but when i used string operation of concatenation and made the arr look like "99999999999", then I obviously got pattern "99" of length = m repeated for more than equal to k times and I returned TRUE.

Here in this case only possibilities with m=2 were [99, 9] and [9, 99] and [99, 99] and none of these repeated for >= k times and expected answer was FALSE but in case of concatenated string "99999999999" we got "99" of m=2 many more times than k and so returned TRUE which is WRONG.

NO TEST CASE IN 93 TEST CASES CRACKED MY BUG. So I am contributing this one testcase to LeetCode so that any codes like mine above don't breach the wall of Truth anymore.

#### Code you used for Submit/Run operation

```
 // DETECT PATTERN OF LENGTH M REPEATED K OR MORE TIMES
class Solution:
    def containsPattern(self, arr: List[int], m: int, k: int) -> bool:
        if k > len(arr):
            return False

        arr = [str(i) for i in arr]
        s = "".join(arr)
        all_possibilities = []

        for i in range(len(s) - m):
            all_possibilities.append(s[i: i + m])
        
        for pattern in all_possibilities:
            if pattern*k in s:
                return True
        
        return False
```

#### Language used for code
 Python3

#### Expected behavior

For example I used the test case where arr = [99, 9, 99, 99, 9, 99, 9], m = 2 and k = 3. Now we need a pattern of length = m which is found in repetition for at least k times. In reality there does not exist any such pattern and EXPECTED ANSWER is FALSE but when i used string operation of concatenation and made the arr look like "99999999999", then I obviously got pattern "99" of length = m repeated for more than equal to k times and ACTUAL ANSWER CAME OUT TO BE TRUE.

Here in this case only possibilities with m=2 were [99, 9] and [9, 99] and [99, 99] and none of these repeated for >= k times and expected answer was FALSE but in case of concatenated string "99999999999" we got "99" of m=2 many more times than k and so returned TRUE which is WRONG.

#### Screenshots

![Screenshot_20230113_074206](https://user-images.githubusercontent.com/90566249/212341243-30323bdf-d847-4f97-b78e-0b46cb4e0122.png)
![Screenshot_20230113_074532](https://user-images.githubusercontent.com/90566249/212341317-b6b3c2d6-cec0-473c-9cdc-fcd2ddc162b6.png)
![Screenshot_20230113_074608](https://user-images.githubusercontent.com/90566249/212341385-b84c94f3-7646-4e23-a17f-194e6236394d.png)

#### Additional context

Many similar test cases can be generated replacing 9 with other digits...Quite a few repetitions of my test case are needed to be added to the 93 test cases to avoid such false breach of the question statement.
examples are [33, 3, 33, 33, 3, 33, 3], [44, 4, 44, 44, 4, 44, 4], [55, 5, 55, 55, 5, 55, 5], [66, 6, 66, 66, 6, 66, 6] where m =2, k = 3

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
