### ISSUE TITLE
Broken Solution/Submission for 94. Binary Tree Inorder Traversal

### ISSUE THREAD

**Issue by GazVille** [LeetCode-Feedback/LeetCode-Feedback#10990]
#### Your LeetCode username
GazVille

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

For some reason, the test cases are appending onto the next one. For example:

test case 1 is [3,2,1] & test case 2 is [1]

test case 1 passes 
test case 2 will now be [3,2,1,1]. NOT [1]. 

This might sound confusing, i tried to put EXACTLY what i did in the explanation section below. 

#### Code you used for Submit/Run operation

```
// 94. Binary Tree Inorder Traversal
# Definition for a binary tree node.
# class TreeNode(object):
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
class Solution(object):
    def inorderTraversal(self, root, traversal=[]):
        """
        :type root: TreeNode
        :rtype: List[int]
        """
        if root:
            traversal = self.inorderTraversal(root.left, traversal)
            traversal.append(root.val)
            traversal = self.inorderTraversal(root.right, traversal)
        
        return traversal
```

#### Language used for code
Python

#### Expected behavior

original test cases: 
1. [1,null,2,3]
2. []
3. [1]
So, i ran the test cases, they failed, i thought i screwed something up:
![image](https://user-images.githubusercontent.com/119612498/212188781-54fd4946-be3c-48f1-b6cf-df6d56ef2b47.png)

"ah shizzle, i missed my base cases", Then i clicked on case 2, expecting confirmation of my lost dignity:
![image](https://user-images.githubusercontent.com/119612498/212189297-f6f5e989-cd38-4b44-a186-09690dd68456.png)

![image](https://user-images.githubusercontent.com/119612498/212190125-508572bc-0fc9-497d-b2cb-acbdca6f3f19.png)

"huh?" Then i clicked on case 3, bracing myself...:
![image](https://user-images.githubusercontent.com/119612498/212189648-c5a2645b-5033-43c8-9f5b-bd907c20a433.png)

"wait a goddman minute":
![image](https://user-images.githubusercontent.com/119612498/212190235-acfa9dce-332a-438c-87a8-476181e7ca26.png)

I realised that the test case appended onto the next one. To test this i just submitted, seeing what would happen:
It failed on the first test case (which was [] ), but...  the output from my solution was [1,3,2]:
![image](https://user-images.githubusercontent.com/119612498/212191259-c98d6440-887a-417d-9203-5c88c9669ffc.png)
![image](https://user-images.githubusercontent.com/119612498/212191374-6ced0f6f-330b-4398-a010-a743324259f0.png)

To be extra extra sure i wasnt getting GASLIT, i put the failing test cases as the ONLY test case 1 by 1 and ran it. 
![image](https://user-images.githubusercontent.com/119612498/212192050-c54a02a8-c89c-4b8c-8ddf-a6dee4e8cd6f.png) 
![image](https://user-images.githubusercontent.com/119612498/212192137-0df63ec4-55c3-4300-9b68-260432574a3e.png)

"i knew it"
![image](https://user-images.githubusercontent.com/119612498/212192254-c9de3b07-1c01-4fca-afbc-cfbb75d47ead.png)

they passed individually. 

To prove my theory of the appending on to the next ones i did the test case 1 as [1,2,3,4] and test case 2 as [4,5,6], first i tested them individually:
![image](https://user-images.githubusercontent.com/119612498/212192683-834fad84-cdba-4e40-bd92-a9d05c6831a3.png) 
![image](https://user-images.githubusercontent.com/119612498/212192748-b3e41983-a952-48a8-a50e-8fa34b5e2c7e.png)
![image](https://user-images.githubusercontent.com/119612498/212193197-acc7c49a-879a-4ade-9e80-fa72b3ba182b.png)

They passed! great, now i will make 2 test cases, and run THOSE:
![image](https://user-images.githubusercontent.com/119612498/212193439-d669a39c-f80b-43de-8909-fb65d5cdc196.png)
![image](https://user-images.githubusercontent.com/119612498/212193486-20698de8-3648-4401-ba3f-2ab2422f449e.png)
![image](https://user-images.githubusercontent.com/119612498/212193537-8203add3-6606-4097-b58e-6af9038566c1.png)

as i suspected... first test case passed, somehow appended it onto the next test case and failed!

#### Additional context

i got some dudes solution and submitted that, to see if it would do the same thing, but it submitted fine and passed, now i feel like i cheated but i thought it wasnt gonna work rip.
![image](https://user-images.githubusercontent.com/119612498/212193785-84a084ee-089a-478d-b9e7-a5c356885f11.png)

If your interested, the solution i used that worked was this: (credit to hari_krishnan_)
```

class Solution(object):
    def inorderTraversal(self, root):
        """
        :type root: TreeNode
        :rtype: List[int]
        """
        result = [] 
        stk = []
        while root or stk:
            if root:
                stk.append(root)
                root = root.left
            else:
                root = stk.pop()
                result.append(root.val)
                root = root.right
        return result

```

Hope you guys sort it and also had fun reading it as much as i had fun procrastinating by writing this haha x

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
