### ISSUE TITLE
27. 移除元素 示例预期结果错误

### ISSUE THREAD

**Issue by Litmmp** [LeetCode-Feedback/LeetCode-Feedback#11]
** Bug 类型**
- [ ] 题目
- [x] 题解

**描述**
将示例2作为测试用例，在页面执行代码，预期结果和题设不一致，是个错误的结果

**你提交或者运行的代码**
```java
class Solution {
    public int removeElement(int[] nums, int val) {
        if (nums == null || nums.length == 0) return 0;

        int mark = -1;
        if (nums[0] != val) ++mark;

        for (int i = 1; i < nums.length; i++) {
            if (nums[i] != val) nums[++mark] = nums[i];
        }
        return mark + 1;
    }
}
```

**屏幕截图**
<img width="1278" alt="error" src="https://user-images.githubusercontent.com/12251480/75880311-fe4f5880-5e57-11ea-8d80-6f23afddd62a.png">

**Comment by idealism-xxm** [comment]
示例 2:

> 给定 nums = [0,1,2,2,3,0,4,2], val = 2,
> 
> 函数应该返回新的长度 5, 并且 nums 中的前五个元素为 0, 1, 3, 0, 4。
> 
> 注意这五个元素可为任意顺序。
> 
> 你不需要考虑数组中超出新长度后面的元素。

示例内已经说明了五个元素的顺序不限制，即只要排序后的数组相同就行

**Comment by feiceh** [comment]
感谢反馈，此问题已转给技术团队会尽快确认的～
