### ISSUE TITLE
System recognized as wrong answer, no matter it is correct #Problem 49

### ISSUE THREAD

**Issue by TanakaSakana** [LeetCode-Feedback/LeetCode-Feedback#110]
**What kind of the bug**
- [x] solution

**Describe the bug**
System recognized as wrong answer, no matter it is correct #Problem 49

**what language is your code written in**
Java

**The code you submit/run**
```
class Solution {
public List<List<String>> groupAnagrams(String[] strs) {
List<List<String>> list = new ArrayList<>(
Arrays.stream(strs).collect(
Collectors.groupingBy(
x -> x.chars().mapToObj(y->(char)y).collect(Collectors.toSet()),
Collectors.toList())
).values());
return list;
}
}
```

**Expected behavior**
It supposed to pass the test case as though the output is the same in different order

**Screenshots**
Submission snapshot
https://leetcode.com/submissions/detail/320624341/

**Additional context**
Request Ticket #29492

**Comment by CooperCooperCooper** [comment]
Hi @TanakaSakana,
Thank you for reaching out to us! I've relayed your issue to our engineers to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @TanakaSakana,
Thank you for your time. We've taken a look at this issue and found it to be invalid. Both approaches consider that 'boo' and 'bob' are anagrams, and they are not.

**Comment by TanakaSakana** [comment]
Thank you for your kindly response
