### ISSUE TITLE
Question 2246. Longest Path With Different Adjacent Characters  Not clearly defined

### ISSUE THREAD

**Issue by whynesspower** [LeetCode-Feedback/LeetCode-Feedback#11001]
#### Category of the bug
- [ Yes] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

the question must descripe the meaning of a path, I solved by taking path as a any chain of nodes with as many ends, but the answer requires to define a path as a chain with only two ends. So instead of finding a chain of longest nodes, a longest chain with two ends is the answer. 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<int>vis;
    int dfs(vector<int>adj[], int src, string &s){
        vis[src]=1;
        // pq.push(1);
        priority_queue<int>pq;
        for(auto it:adj[src]){
            if(vis[it]==-1 and s[src]!=s[it]){
                int a=dfs(adj, it, s);
                pq.push(a);
            }
        }
        int ans=1;
        int k=2;
        while(!pq.empty() and k--){
            int temp = pq.top();
            pq.pop();
            ans+=temp;
        }
        vis[src]=ans;
        return (ans);
    }
    
    
    int longestPath(vector<int>& parent, string s) {
        int n=parent.size();
        vis.resize(n,-1);
        vector<int>adj[n+1];
        for(int i=1;i<parent.size();i++){
            adj[i].push_back(parent[i]);
            adj[parent[i]].push_back(i);
        }
        
        for(int i=0;i<n;i++){
            if(vis[i]==-1){
                dfs(adj, i, s);
            }
        }
        int ans=INT_MIN;
        for(int i=0;i<vis.size();i++){
            ans=max(ans, vis[i]);
        }
        return ans;
    }
};
```

#### Language used for code
C++

**Comment by whynesspower** [comment]
Question 2246. Longest Path With Different Adjacent Characters  Not clearly defined

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
