### ISSUE TITLE
Confusing Question wording - 292. Nim Game

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1100]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

292. Nim Game
https://leetcode.com/problems/nim-game/

#### Code you used for Submit/Run operation

Google gives following definition for "turns", given from "Definitions from Oxford Languages"
>> turns = "move (something) so that it is in a different position in relation to its surroundings or its previous position."

Question has below wording, that is confusing:
>> , each time one of you take turns to remove 1 to 3 stones.

- What is "one of you" taking turns?
- Do you mean we can re-start to a different person while taking turns? in the middle? at random?
- Does "taking turns" not already have enough meaning?

Please change the wording to below, or like:
>> , you take turns to remove 1 to 3 stones.
OR
>> , you both take turns to remove 1 to 3 stones.

```
```

#### Language used for code
JS

#### Expected behavior

- User should not read 2/3 times to understand the problem description.
- User should not feel "Is there something else that is hinted here? will my submission fail?" when there is no more meaning than already understood.
- Also, we have a LOT of expectation from LeetCode to give proper English & raise the standards :) so that Many users will save time - The question is old, so its ok, but do you have a English proof-reader now?

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
