### ISSUE TITLE
Run/Submit Issue with Test Case Input

### ISSUE THREAD

**Issue by PranManral** [LeetCode-Feedback/LeetCode-Feedback#11009]
#### Your LeetCode username
pranmanral 

#### Category of the bug
- [ ] Solution

#### Description of the bug

There is a question in your problem set where one test case is failing even for the solutions posted on submission page.

Path to question:
https://leetcode.com/problems/path-sum-iii/

Procedure:
1. select java language
2. paste sample java code for the solution shared at the end of email.
3. Click on "Submit" and console will show message: "wrong answer for one test case with input :" 
root =
[1000000000,1000000000,null,294967296,null,1000000000,null,1000000000,null,1000000000]
4. Copy the input above and paste it on new test case on console.
5. Click on "Run".
6. Code is being "accepted" for the test case on clicking "Run" with same test case input but code is not being "submitted" when clicking on "Submit".

#### Code you used for Submit/Run operation

```
class Solution {
    int total = 0;
   public int pathSum(TreeNode root, int sum) {
        if (root == null)
            return 0;
        HashMap<Integer, Integer> hm = new HashMap<>();
        hm.put(0, 1);
        findPathSum(root, 0, sum, hm);  
        return total; 
   }
    private void findPathSum(TreeNode curr, int sum, int target, HashMap<Integer, Integer> hm) {
        if (curr == null)
            return;
        
        sum += curr.val;
        if(hm.containsKey(sum-target))
          total += hm.get(sum-target);
        hm.put(sum, hm.getOrDefault(sum, 0) + 1);
         findPathSum(curr.left, sum, target, hm);
         findPathSum(curr.right, sum, target, hm);
        hm.put(sum, hm.get(sum) - 1);
        return;
    }
}
```

#### Language used for code
        JAVA

#### Expected behavior

TestCase Input : root =
[1000000000,1000000000,null,294967296,null,1000000000,null,1000000000,null,1000000000]
 Code is being "accepted" for the test case on clicking "Run" with testcase mentioned above but code is not being "submitted" when clicking on "Submit". It should have been accepted and submitted.
![Screenshot (18)](https://user-images.githubusercontent.com/97998617/212375845-abaed1f3-ad0b-4812-815d-a9ae44aa3735.png)
![Screenshot (3)](https://user-images.githubusercontent.com/97998617/212375851-c287603e-4efa-47e4-bb3b-e8e9a175bf44.png)

**Comment by PranManral** [comment]
[](url)
![Screenshot (18)](https://user-images.githubusercontent.com/97998617/212375658-6bd22c8c-4d72-4c53-9a99-5ac26f52dc86.png)
![Screenshot (3)](https://user-images.githubusercontent.com/97998617/212375668-ead0793e-637c-4c2c-8f9a-166e942ff9f6.png)
Sorry Wrong Screenshots were attached above , please refer to these.

**Comment by LC-Pam** [comment]
https://leetcode.com/submissions/detail/877587760/
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!
