### ISSUE TITLE
Missing Test Case - 20. Valid Parentheses

### ISSUE THREAD

**Issue by usr-canis** [LeetCode-Feedback/LeetCode-Feedback#11007]
#### Your LeetCode username
niranjanchordate

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Code can be manipulated to work only for given testcases. 

#### Code you used for Submit/Run operation

```
bool isValid(char * s){
bool a=false;
for(int i=0;s[i]!='\0';i++)
{
    if(s[i]=='('&&s[i+1]==')')                 //||s[i]=='['&&s[i+1]==']'||s[i]=='{'&&s[i+1]=='}')
    {
        a= true;
    }
     
}
return a;
}
```

#### Language used for code
c

#### Expected behavior
the above submitted code passes all current testcases but for the given string "{}" or "[]" it doesn't. a genuine solution should do fine for this too.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
