### ISSUE TITLE
Missing Test Case - 2246. Longest Path With Different Adjacent Characters

### ISSUE THREAD

**Issue by BugElPZ** [LeetCode-Feedback/LeetCode-Feedback#11000]
#### Your LeetCode username

Bug_El

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 
 

#### Description of the bug

Wrong solution is able to pass existing test suit and being accepted, but will faill fail on additional test case:
 parent = [-1,0,0,1,1,2]
 s = "abcbbc"

#### Code you used for Submit/Run operation

```
class Solution:
    def longestPath(self, parent: List[int], s: str) -> int:
        nodes = {0: set()}
        for i in range(1, len(parent)):
            nodes.setdefault(parent[i], set()).add(i)
            nodes.setdefault(i, set()).add(parent[i])
        cache = {}
        def go(node, back_node) -> int:
            if (node, back_node) in cache:
                return cache[(node, back_node)]
            visit.add(node)
            path_max = 1
            for neighbour in nodes[node].difference(visit):
                if s[node] != s[neighbour]:
                    path_max = max(path_max, 1 + go(neighbour, node))
            cache[(node, back_node)] = path_max
            return path_max
        leafs = set(range(len(parent))).difference(set(parent))
        path = 1
        for leaf in leafs:
            visit = set()
            path = max(go(leaf, None), path)
        return path
```

#### Language used for code

Python3

#### Expected behavior

Fail due to not considering all possible correct answers for this problem

#### Screenshots

![2278_missing_testcase](https://user-images.githubusercontent.com/116805496/212349197-7f7b95ab-22e7-4d1b-874b-48a5f031476e.jpg)

![2278_missing_testcase_1](https://user-images.githubusercontent.com/116805496/212349823-10d72442-d6e5-494f-ba88-6b8bb2cd8a00.jpg)

#### Additional context

Test case suit can be improved by adding case  parent = [-1,0,0,1,1,2], s = "abcbbc"

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
