### ISSUE TITLE
Incorrect Constraints - 682. Baseball Game

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1101]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

https://leetcode.com/problems/baseball-game/
682. Baseball Game

"Note" is given as below:
> The size of the input list will be between 1 and 1000.
> Every integer represented in the list will be between -30000 and 30000.

So, the array size of 1 is valid.

But below test cases does not work, their errors are below:

Testcase    Corresponding error

["+"]        Invalid Testcase    Line 13: IndexError: list index out of range
["D"]        Invalid Testcase    Line 17: IndexError: list index out of range
["C"]        Invalid Testcase    Line 15: IndexError: pop from empty list

Not only above test cases, but below like test cases won't work

["+"]
["+","D"]
["+","-2"]
["+","-2","5","C"]
["+","-2","5","C","D"]
["C"]
["C","D"]
["C","5"]
["C","-2"]
["C","D","5"]
["C","+","-2","5","D"]
["C","-2","+","5","D"]
["C","5","+","-2","D"]
["C","D","+","-2","5"]
["D"]
["D","+"]
["D","-2","+","5","C"]
["D","C","+","-2","5"]
["D","C","+","-2"]
["D","C"]

- The question does not say anything on "input list strings are always possible/valid."
- Please fix the constraints.

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

- For the users, who want a 100% first submission Pass without any doubt - Those user's time is severely wasted
- Overall 3 hours of User's time spent - just to find out what is there & missing in the question.
  - These should not happen to user

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
