### ISSUE TITLE
Missing Test Case - 1744. Can You Eat Your Favorite Candy on Your Favorite Day?

### ISSUE THREAD

**Issue by UJJALSAHA126** [LeetCode-Feedback/LeetCode-Feedback#11011]
#### Category of the bug
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean[] canEat(int[] candiesCount, int[][] queries) {
        int n = candiesCount.length;
        int q = queries.length;
        boolean[] ans = new boolean[q];
        
        long[] prefSum = new long[n];
        prefSum[0] = candiesCount[0];

        for (int i = 1; i < n; i++) prefSum[i] = prefSum[i - 1] + candiesCount[i];

        for (int i = 0; i < q; i++) {
            int type = queries[i][0], day = queries[i][1], cap = queries[i][2];

            long lastCandies = (type > 0) ? prefSum[type - 1] : 0;

            long low = lastCandies / cap;
            if (lastCandies % cap == 0 && lastCandies != 0) low++; // Causing the error.

            long high = prefSum[type] - 1;

            ans[i] = (day >= low && day <= high);
        }

        return ans;
    }
}
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The test case. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by UJJALSAHA126** [comment]
candiesCount = [2,8,100]
queries = [[2,5,2]]

**Comment by LC-Pam** [comment]
Hi there,
Thank you for reaching out to us. I've relayed this issue to our team to investigate. We will reach back to you after we investigate.
Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as the reward for this feedback. 

If you have any other questions or feedbacks, please don't hesitate to let us know! 

We appreciate your support!
