### ISSUE TITLE
1581. Customer Who Visited but Did Not Make Any Transactions (Grammar) 

### ISSUE THREAD

**Issue by TheDoctor561** [LeetCode-Feedback/LeetCode-Feedback#11014]
#### Your LeetCode username

TheDoctor561

#### Category of the bug
- [ ] Question
- [ ] Solution
- [X ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Description of 1581. Customer Who Visited but Did Not Make Any Transactions
has a grammatical error 

Write an SQL query to find the IDs of the users who visited without making any transactions and the number of times they made these types of visits.

Should be 

Writ a SQL query to find the IDs of the users who visited without making any transactions and the number of times they made these types of visits.

As per usage of articles in a sentence. 
https://owl.purdue.edu/owl/general_writing/grammar/articles_a_versus_an.html#:~:text=If%20the%20first%20letter%20makes,words%20that%20begin%20with%20consonants.

#### Screenshots
![image](https://user-images.githubusercontent.com/30754707/212420292-d9f1b413-71df-44db-af8d-30c857d0261e.png)

**Comment by LC-Pam** [comment]
Hi there,
Thank you for reaching out to us. I've relayed this issue to our team to investigate. We will reach back to you after we investigate.
Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

If you have any other questions or feedbacks, please don't hesitate to let us know! 

We appreciate your support!
