### ISSUE TITLE
C++ compiler issue

### ISSUE THREAD

**Issue by VadVergasov** [LeetCode-Feedback/LeetCode-Feedback#11017]
#### Your LeetCode username
VadVergasov

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the C++ language static variables in functions have strange behavior. In the task, I've got different output compared to the playground and local machine.

#### Code you used for Submit/Run operation

```
#include <algorithm>
#include <iostream>

class Solution {
public:
    pair<int, bool> dfs(int v, const vector<vector<int> >& graph, string_view s, vector<bool>& used) {
        static int max_sub = 0;
        cout<<max_sub<<endl;
        pair<int, bool> result = {1, true}, max_true1 = {0, true}, max_true2 = {0, true};
        used[v] = true;
        for(const auto& verticle : graph[v]) {
            if(!used[verticle]){
                pair<int, bool> sub = dfs(verticle, graph, s, used);
                if(sub.second){
                    if(s[verticle] != s[v]) {
                        if(max_true1.first < sub.first){
                            max_true2.first = max_true1.first;
                            max_true1.first = sub.first;
                        } else if(max_true2.first < sub.first) {
                            max_true2.first = sub.first;
                        }
                    }
                }
            }
        }
        result.first = max_true1.first + 1;
        max_sub = max(max_sub, max_true1.first + max_true2.first + 1);
        if(v == 0){
            result.first = max(result.first, max_sub);
        }
        return result;
    }
    
    int longestPath(vector<int>& parent, string s) {
        vector<vector<int> > graph(parent.size());
        for(size_t cur = 1; cur < parent.size(); cur++) {
            graph[parent[cur]].push_back(cur);
            graph[cur].push_back(parent[cur]);
        }
        vector<bool> used(parent.size(), false);
        return dfs(0, graph, s, used).first;
    }
};

int main() {
    Solution sol;
    vector<int> parent = {-1};
    string s = "z";
    cout<<sol.longestPath(parent, s)<<endl;
    return 0;
}
```

#### Language used for code

C++

#### Expected behavior

A static variable should be initialized once with value, but in Submission, it looks like it doesn't initialize.

#### Screenshots

![image](https://user-images.githubusercontent.com/25568118/212465518-5b8665a8-16db-45f8-ac74-d0a425f72d07.png)
The screenshot of such behavior.
https://leetcode.com/playground/8txZhTup
Playground with the same code and different results.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submit link. We received Compile Error when we submitted your above code.
https://leetcode.com/submissions/detail/879426374/

In addition, When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output value.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by VadVergasov** [comment]
I'm sorry for the incorrect link, [here](https://leetcode.com/problems/longest-path-with-different-adjacent-characters/submissions/877602066/) is the right one, I hope.

But the second link describes, why there is such behavior because you run all the tests in one program instance. But such testing removes any pros of static variables in a function.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
