### ISSUE TITLE
Edit Distance - Official Solution code and pseudocode mismatch

### ISSUE THREAD

**Issue by MislavJuric** [LeetCode-Feedback/LeetCode-Feedback#11010]
#### Your LeetCode username
user3984We

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In Approach #1 in C++ and Java code, the code doesn't match the pseudocode.

The C++ and Java code is as follows:
```
int insertOperation = minDistanceRecur(word1, word2, word1Index - 1, word2Index);
int deleteOperation = minDistanceRecur(word1, word2, word1Index, word2Index - 1);
```

while the pseudocode says it should be:

```
int insertOperation = minDistanceRecur(word1, word2, word1Index,, word2Index - 1);
int deleteOperation = minDistanceRecur(word1, word2, word1Index - 1, word2Index);
```

While the solution still works, it's confusing for the (human) reader. You may want to correct this.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
