### ISSUE TITLE
unreadable solution

### ISSUE THREAD

**Issue by incubo4u** [LeetCode-Feedback/LeetCode-Feedback#11026]
#### Your LeetCode username

1ncu804u

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

the last solution of the problem Gray Code is unreadable 

#### Screenshots

<img width="930" alt="image" src="https://user-images.githubusercontent.com/52492193/212490119-c337613e-d756-4da9-a38d-6dc8ac95036f.png">

#### Additional context

https://leetcode.com/problems/gray-code/solutions/1254478/official-solution/

**Comment by LC-Pam** [comment]
Hi there,
Thank you for reaching out to us. I've relayed this issue to our team to investigate. We will reach back to you after we investigate.
Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

If you have any other questions or feedbacks, please don't hesitate to let us know! 

We appreciate your support!
