### ISSUE TITLE
Missing Test Case - 1089. Duplicate Zeros

### ISSUE THREAD

**Issue by kirr0yal** [LeetCode-Feedback/LeetCode-Feedback#11024]
#### 

kirr0yal

#### Category of the bug
- [ Duplicate Zeros ] Question
- [ [1,0,0,2,3,0,0,4] ] Solution
- [python ] Language
- [ [1,0,2,3,0,4,5,0] ] Missing Test Cases 

#### 

In pyCharm my arr = [1,0,0,2,3,0,0,4], but in LeetCode it says [1,0,2,3,0,4,5,0]
I didnt print or return anything

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution:
    def duplicateZeros(self, arr: List[int]) -> None:
        new_array = []
        count = 0
        for el in arr:
            new_array.append(el)
            if el == 0:
                new_array.append(0)
                count += 1
        arr = new_array[:-count]
```

#### Language used for code

python

#### Expected behavior

expected that my arr = [1,0,0,2,3,0,0,4]

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
