### ISSUE TITLE
Incomplete Question description - 682. Baseball Game

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1102]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

https://leetcode.com/problems/baseball-game/
682. Baseball Game

The question description is given as below:
> Integer (one round's score): Directly represents the number of points you get in this round.
> "+" (one round's score): Represents that the points you get in this round are the sum of the last two valid round's points.
> "D" (one round's score): Represents that the points you get in this round are the doubled data of the last valid round's points.
> "C" (an operation, which isn't a round's score): Represents the last valid round's points you get were invalid and should be removed.

In the above, we are talking about "valid" & "invalid" scores.

But 
- What is a "valid score"? it is not defined? Note that, we are not talking about "score" here, we are talking about the "valid score".
- Is "valid score" only "Integer"?
- Is "valid score" all the three - "Integer", "+" & "D"?

This "valid score" definition is missing (though "score" is defined).

Please change as below:

From
> Integer (one round's score) ...
> "+" (one round's score) ...
> "D" (one round's score) ...
> "C" (an operation, which isn't a round's score) ...

To
> Integer (one round's valid score) ...
> "+" (one round's valid score) ...
> "D" (one round's valid score) ...
> "C" (an operation, which isn't a round's valid score) ...

- Note that "round's score" became "round's valid score"

OR

- We can also remove all "valid" words in total question. That also removes the confusion in the question.

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

- The question description should be complete.
  - If we talked about "score" & "valid score", then there is a confusion in question.
  - Question should not talk about "valid score" when it is the same as "score"

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy ,
Thank you for your feedback regarding this problem. Upon review, our team has noted that this problem was updated recently prior to your request so we will now close this ticket.
