### ISSUE TITLE
System Design videos aren't available

### ISSUE THREAD

**Issue by xtreding** [LeetCode-Feedback/LeetCode-Feedback#11021]
#### Your LeetCode username
xtreding

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
System design card videos aren't available

#### Screenshots
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/18486255/212477120-916e2f0a-6121-45b8-999c-5536f7fc4e2f.png">

#### Additional context
[link to the card](https://leetcode.com/explore/learn/card/system-design/690/system-design-case-studies/4385/)
Country: Indonesia

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to check the problem. 
The video works correct on the website, please clean the browser cookies and history then refresh the page.
Please let us know if you have any other questions. 
We appreciate your support!
