### ISSUE TITLE
Missing Test Case - 70. Climbing Stairs

### ISSUE THREAD

**Issue by jyothsnaguravana** [LeetCode-Feedback/LeetCode-Feedback#11020]
#### Your LeetCode username

jyoshna_570

#### Category of the bug
Solution

#### Description of the bug

I have declared an array dp[n+1] ,starting the variables assigned as dp[0] = 0,dp[1] = 1, dp[2] = 2 , and there on started iteration upto 
int n . But when I want to return the value for test case "1" it gives me a error for n == 1 only .Statement :<b> return dp[n] </b> .But using the if else statement gave me a acceptance . Whats wrong with assigning dp[1] = 1 ...

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int climbStairs(int n) {
        int dp[n+1];
        dp[0] = 0;
        dp[1] = 1 ,dp[2] = 2;
        if(n >= 3)
        for(int i=3 ; i<=n ; i++){
            dp[i] = dp[i-1] + dp[i-2];
        }
        return dp[n];
    }
};
```

#### Language used for code
 C++ 

#### Expected behavior

The error I found was :
Line 6: Char 20: runtime error: index 2 out of bounds for type 'int [n + 1]' (solution.cpp) SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior prog_joined.cpp:15:20......

**Comment by LC-Pam** [comment]
Hi there,
Thank you for reaching out to us. I've relayed this issue to our team to investigate. We will reach back to you after we investigate.
Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The above code received Runtime Error, please use our Debug function to check the issue with the above code. 

If you have any other questions or feedbacks, please don't hesitate to let us know! 

We appreciate your support!
