### ISSUE TITLE
Missing Test Case: 259. 3Sum Smaller

### ISSUE THREAD

**Issue by cpeck-rmvd** [LeetCode-Feedback/LeetCode-Feedback#11028]
#### Your LeetCode Username
crpeck

#### Category of the bug
- [259. 3Sum Smaller ] Question
- [0] Solution
- [python] Language
- [nums = [30,30,30,...,-4,...,30,30,30] (3500 elements), target = 1] Missing Test Cases 

#### Description of the bug
For 259. 3Sum Smaller, I wrote a brute force solution as seen below. There is an existing test case where the `nums` array is of length 3500, each element being 30, and `target` is specified as 1: for this case my initial solution below timed out. I added a check to return 0 if `target < min(nums)` (which only runs if there's no negative number in the array), and the solution is accepted. However, I realized if we take that same  testcase and replace some item of the 3500-element long array some any negative number besides -29, it will account for this shortcut by properly failing. This is the test case I'm proposing.

eg:
```
nums = [30] * 1500 + [-4] + [30] * 1499    # ie [30,30,30,...,-4,...,30,30,30]
target = 1
```

#### Code you used for Submit/Run operation

```
# pure brute force: TLE

class Solution:
    def threeSumSmaller(self, nums: List[int], target: int) -> int:
        if len(nums) < 3: return 0
        count = 0
        for i in range(len(nums) - 2):
            for j in range(i + 1, len(nums) - 1):
                for k in range(j + 1, len(nums)):
                    if nums[i] + nums[j] + nums[k] < target: count += 1
        return count
        
# with accommodation for long test case
# on submission: Accepted
# when run against proposed test case: TLE
        
class Solution:
    def threeSumSmaller(self, nums: List[int], target: int) -> int:
        if len(nums) < 3: return 0
        neg = [i for i in nums if i < 0]
        if not neg:
            if target < min(nums): return 0
        count = 0
        for i in range(len(nums) - 2):
            for j in range(i + 1, len(nums) - 1):
                for k in range(j + 1, len(nums)):
                    if nums[i] + nums[j] + nums[k] < target: count += 1
        return count
```

#### Language used for code
Python

#### Expected behavior
This solution should not be accepted as there exists valid test input for which it produces a Time Limit Exceeded error

#### Additional context
There are obviously a lot of other similar test cases for which my code would time out, but I'm not sure if anything else is worth adding. The suggested testcase could also be changed any number of ways to check for this edge case.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as the reward for this feedback. 

If you have any other questions or feedbacks, please don't hesitate to let us know! 

We appreciate your support!
