### ISSUE TITLE
Incorrect Question Difficulty level - 316. Remove Duplicate Letters

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1103]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

316. Remove Duplicate Letters
	https://leetcode.com/problems/remove-duplicate-letters/

1081. Smallest Subsequence of Distinct Characters
	https://leetcode.com/problems/smallest-subsequence-of-distinct-characters/

The first one is Hard
The second one is Medium

Both link each other saying both are the same.

So they must have the same Question Difficulty level

- Please change one of the question's Question Difficulty level same as the other - either Medium OR Hard

Suggestion:
 Since 1081 is the latest, and it has Medium, it's Question Difficulty is most probably correct for today.
- So, please make question 316 from Hard to Medium

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

- Same questions must have the same Question Difficulty level

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
