### ISSUE TITLE
Test case added for 2538. Difference Between Maximum and Minimum Price Sum

### ISSUE THREAD

**Issue by priyanshu-28** [LeetCode-Feedback/LeetCode-Feedback#11038]
#### Your LeetCode username

priyanshu_pathak28

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The following test case still needs to be added, due to which many solutions passed.

#### Code you used for Submit/Run operation

```
// 2538. Difference Between Maximum and Minimum Price Sum
class Solution:
    def maxOutput(self, n: int, edges: List[List[int]], price: List[int]) -> int:
        mapp = defaultdict(set)
        for a,b in edges:
            mapp[a].add(b)
            mapp[b].add(a)
        
        @lru_cache(maxsize=None)
        def dfs(node, parent):
            ans = 0
            for child in mapp[node]:
                if child != parent:
                    ans = max(ans, dfs(child, node))
            return ans + price[node]
        
        ans = 0
        for i in range(n):
            ans = max(ans, dfs(i, -1)-price[i])
        return ans
```

#### Language used for code

C++

#### Expected behavior

Due to absent of the following test case, brute force solutions passed the problem

#### Additional context

[output.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/10419459/output.txt)

**Comment by Yawn-Sean** [comment]
this isn't brute force, and your testcase isn't valid (the length of edges isn't correct)

in the dfs, there are only O(n) status, so the solution should pass.

**Comment by stormsunshine** [comment]
The test case you provided is invalid. If n = 100000, then the length of edges should be 99999. One possible test case is as follows.

[output.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/10419479/output.txt)

**Comment by priyanshu-28** [comment]
sorry the fixed test case is below.

The above code would run O(n^2) because the dfs function will be called for each node (n time) that will run for (n - 1) times.
[output.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/10419478/output.txt)

**Comment by Yawn-Sean** [comment]
> 

The above code wouldn't be O(n^2) as it used the cache. The code will run in each status only once. In fact , the code doesn't get TLE using your testcase.

**Comment by Yawn-Sean** [comment]
But this solution can be O(n^2) under certain circumstances, and the issue has already been launched.

**Comment by priyanshu-28** [comment]
cool, as the issue has been launched already, I will close this issue. 
thanks.
