### ISSUE TITLE
318. Maximum Product of Word Lengths: strangely broken test case

### ISSUE THREAD

**Issue by cpeck-rmvd** [LeetCode-Feedback/LeetCode-Feedback#11033]
#### Your LeetCode username
crpeck

#### Category of the bug
- [ 318. Maximum Product of Word Lengths] Question
- [ ] Solution
- [ python] Language
- [ ] Missing Test Cases 

#### Description of the bug

When I submit a python solution for 318. Maximum Product of Word Lengths, my submission says "Time Limit Exceeded", but it also indicates that 228/228 test cases passed, and the latest input `words=            `. Besides the obviously buggy feel here, among the requirements is that len(words) >= 1, so empty input is not a valid test anyway. See screenshot and code snippet below for clarity.

#### Code you used for Submit/Run operation

```
class Solution:
    def maxProduct(self, words: List[str]) -> int:
        if not words: return 0
        def dotheyshare(s1, s2):
            for s in set(s1):
                if s in s2:
                    return True
            return False
        t = [len(i)*len(j) for i in words for j in words if not dotheyshare(i,j)]
        return max(t) if t else 0
```

#### Language used for code
python

#### Expected behavior
If the submission passes all test cases, it should be accepted. If not all test cases are passed, the response should correctly display which input caused a failure.

#### Screenshots

<img width="747" alt="Screen Shot 2023-01-14 at 4 26 41 PM" src="https://user-images.githubusercontent.com/102287000/212500023-f3373b6c-8f63-4a8f-a470-a27dd1c01936.png">

**Comment by LC-Pam** [comment]
Hi there,
Thank you for reaching out to us.
 I've relayed this issue to our team to investigate. 
We will reach back to you after we investigate.
Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

As we can see in https://leetcode.com/submissions/detail/879441786/, the code passed 167/168 test cases and it reported the test case which fails.

If you have any other questions or feedbacks, please don't hesitate to let us know! 

We appreciate your support!
