### ISSUE TITLE
Missing Test Case - 2538. Difference Between Maximum and Minimum Price Sum

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#11039]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets WA on the following testcase:
10
[[0, 1], [0, 2], [2, 3], [0, 4], [1, 5], [0, 6], [6, 7], [4, 8], [2, 9]]
[2, 1, 3, 1, 3, 4, 3, 2, 2, 5]

#### Code you used for Submit/Run operation

```
class Solution:
    def maxOutput(self, n: int, edges: List[List[int]], price: List[int]) -> int:
        g = [[] for _ in range(n)]
        for u, v in edges:
            g[u].append(v)
            g[v].append(u)
        dst = [0]*n
        global ans
        ans = 0

        def dfs1(u, fa):
            global ans
            mx = 0
            for v in g[u]:
                if v != fa:
                    dfs1(v, u)
                    mx = max(mx, dst[v])
            dst[u] = mx
            # print(u, mx)
            ans = max(ans, dst[u])
            dst[u] += price[u]
        dfs1(0, 0)

        # print(ans)
        # print(dst)

        def dfs2(u, fa, d):
            global ans
            ans = max(ans, d)
            lst = []
            for v in g[u]:
                if v != fa:
                    lst.append(dst[v])
            lst.sort()
            for v in g[u]:
                if v != fa:
                    pos = bisect_left(lst, dst[v])
                    mx = d
                    if pos + 1 < len(lst):
                        mx = max(mx, lst[pos+1])
                    elif pos - 1 >= 0:
                        mx = max(mx, lst[pos-1])
                    dfs2(v, u, mx+price[u])

        dfs2(0, 0, 0)
        return ans
```

#### Language used for code

Python3

#### Expected behavior

Output: 10
Expected: 13

**Comment by LC-Pam** [comment]
Hi there,
Thank you for reaching out to us. I've relayed this issue to our team to investigate. We will reach back to you after we investigate.
Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as the reward for this feedback. 

If you have any other questions or feedbacks, please don't hesitate to let us know! 

We appreciate your support!
