### ISSUE TITLE
Missing Test Case - 2538. Difference Between Maximum and Minimum Price Sum

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#11037]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets TLE  on the following testcase:
[1.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/10419455/1.txt)

#### Code you used for Submit/Run operation

```
class Solution:
    def maxOutput(self, n: int, edges: List[List[int]], price: List[int]) -> int:
        
        table = defaultdict(list)
        for x,y in edges:
            table[x].append(y)
            table[y].append(x)
        ans = 0        
        
        @cache
        def dfs(node,pa):
            cur = price[node]
            for chil in table[node]:
                if chil!=pa:
                    cur = max(cur,price[node]+dfs(chil,node))
            return cur        
        
        for x,y in edges:
            ans = max(ans,dfs(x,y),dfs(y,x))
        return ans
```

#### Language used for code

Python3

#### Expected behavior

The code gets TLE.

**Comment by LC-Pam** [comment]
Hi there,
Thank you for reaching out to us. I've relayed this issue to our team to investigate. We will reach back to you after we investigate.
Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as the reward for this feedback. 

If you have any other questions or feedbacks, please don't hesitate to let us know! 

We appreciate your support!
