### ISSUE TITLE
Missing Test Case - 6294. Difference Between Maximum and Minimum Price Sum

### ISSUE THREAD

**Issue by projecteulerlover** [LeetCode-Feedback/LeetCode-Feedback#11047]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The given algorithm fails when the tree is "star shaped" on n vertices, degenerating into an O(n^2) algorithm.

#### Code you used for Submit/Run operation

```
class Solution:
    def maxOutput(self, n: int, edges: List[List[int]], price: List[int]) -> int:
        
        
        adj=collections.defaultdict(set)
        for i,j in edges:
            adj[i].add(j)
            adj[j].add(i)
                    
        @cache
        def dfs(cur,prev=-1):    
            return price[cur]+max([dfs(nxt,cur) for nxt in adj[cur]-{prev}]+[0])

        return max(dfs(i)-price[i] for i in range(n)) 
```

#### Expected behavior

Using the following test case:
```
n: 100000
edges: [[0, i] for i in range(1, n)]
price: [1] * n
```
will TLE.

**Comment by stormsunshine** [comment]
I am providing the test case as an attachment.

[2538.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/10419679/2538.txt)

**Comment by LC-Pam** [comment]
Hi there,
Thank you for reaching out to us. I've relayed this issue to our team to investigate. We will reach back to you after we investigate.
Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as the reward for this feedback. 

If you have any other questions or feedbacks, please don't hesitate to let us know! 

We appreciate your support!
