### ISSUE TITLE
题目3.无重复字符的最长子串运行差异

### ISSUE THREAD

**Issue by jiguosheng** [LeetCode-Feedback/LeetCode-Feedback#11048]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
Thirsty KellerksY

**Bug 类型**
- [ ] 测试用例

**描述**
在刷3.无重复字符的最长子串时，在网页上执行"pwwkew"的结果为2，可用VisualStudio2013执行的结果为3.

**你使用的语言**
C

**你提交或者运行的代码**
VisualStudio2013执行的代码：
int lengthOfLongestSubstring(char * s){
	int len = strlen(s);
	int max_len = 0;
	int start = 0;
	int stop = 0;
	int c[100];

	int i = 0;

	if (len == 0)
	{
		max_len = 0;
	}
	else if (len == 1)
	{
		max_len = 1;
	}
	else
	{
		memset(c, -1, 100);

		for (i = 0; i < len; i++)
		{
			stop = i;

			if (c[s[stop] - ' '] >= start)
			{
				start = stop;
			}

			if (stop - start >= max_len)
			{
				max_len = stop - start + 1;
			}

			c[s[i] - ' '] = i;
		}
	}

	return max_len;
}

int main()
{
	int len = lengthOfLongestSubstring("pwwkew");

	printf("len = %d\n",len);

	while (1);
}

**期望行为**
执行结果应为3，可网页上执行结果2.

**屏幕截图**

![1](https://user-images.githubusercontent.com/29501335/212529355-3b314468-b26a-4411-b3fc-0f43d8ac0463.png)
![image](https://user-images.githubusercontent.com/29501335/212529385-47d34900-f6b1-42e4-9789-eea24bc39a5e.png)

**额外的上下文**
添加额外的上下文信息

**Comment by BrambleWave** [comment]
刷题学习中遇到问题，您可通过阅读「题解」解决做题中的一些困惑;
您可以自行调试， 例如加 print 信息；
