### ISSUE TITLE
Missing Test Case - 2536. Increment Submatrices by One

### ISSUE THREAD

**Issue by aeecc** [LeetCode-Feedback/LeetCode-Feedback#11042]
#### Your LeetCode username
Syxton

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
An accepted solution gets TLE on the following testcase:
[case.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/10419557/case.txt)

#### Code you used for Submit/Run operation

```
func rangeAddQueries(n int, queries [][]int) [][]int {
    ans := make([][]int, n)
    for i := 0; i < n; i++ {
        ans[i] = make([]int, n)
    }

    for _, query := range queries {
        for i := query[0]; i <= query[2]; i++ {
            for j := query[1]; j <= query[3]; j++ {
                ans[i][j]++
            }
        }
    }

    return ans
}
```

```
class Solution {
    public int[][] rangeAddQueries(int n, int[][] q) {
        int[][] a = new int [n][n];
        for (int i = 0; i < q.length; i++) {
            int r1 = q[i][0];
            int c1 = q[i][1];
            int r2 = q[i][2];
            int c2 = q[i][3];
            for (int j = r1; j <= r2; j++) {
                for (int k = c1; k <= c2; k++) {
                    a[j][k] += 1;
                }
            }
        }
        
        return a;
    }
}
```
#### Language used for code
Go、Java

#### Expected behavior
The code gets TLE.

**Comment by EnZzei1** [comment]
the same code for C# doesn't get TLE tho

**Comment by CyCTW** [comment]
Similar code written in Javascript doesn't get TLE.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us. 
I've relayed this issue to our team to investigate.
We will reach back to you after we investigate.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

Due to there are some limitations on the library, so we cannot add this test case.

If you have any other questions or feedbacks, please don't hesitate to let us know! 

We appreciate your support!
