### ISSUE TITLE
Missing Constraints - 316. Remove Duplicate Letters

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1104]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The question does not have constraints

Another question is linked to this question - given in the "Note"

- Please add constraints - If the constraints are the same, please copy the same to this question too. If not, add any small changes in constraints.

> Note: Even when the questions are the same, constraints may be different.

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

- The question must have constraints to Pass in the 1st submission.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
