### ISSUE TITLE
1581. Customer Who Visited but Did Not Make Any Transactions, wrong descriptions about table Transactions

### ISSUE THREAD

**Issue by bytebeats** [LeetCode-Feedback/LeetCode-Feedback#1105]
In Database problem [1581. Customer Who Visited but Did Not Make Any Transactions](https://leetcode.com/problems/customer-who-visited-but-did-not-make-any-transactions/), one of descriptions about table `Transactions`, namely `This table contains information about the customers who visited the mall` is misplaced here. 

I think the description want to say is `This table contains information about the transactions which is made with visit_id`.

**Comment by lc-ivan** [comment]
Hi @bytebeats ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @bytebeats ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
