### ISSUE TITLE
Error in Example 1 of Problem No. 11 - Container With Most Water

### ISSUE THREAD

**Issue by thisisashwinraj** [LeetCode-Feedback/LeetCode-Feedback#11057]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In example 1 of Problem [11. Container With Most Water](https://leetcode.com/problems/container-with-most-water/), the answer is incorrect.

#### Expected behavior
From index 1 to index 6, the water level would be 8, instead of 7. And, from index 6 to index 8 the water level will be 7 - Making the answer 54 (8+8+8+8+8+7+7), instead of 49.

#### Screenshots

![image](https://user-images.githubusercontent.com/62590141/212551174-b6e4cecc-4bc8-4f5a-87de-4ee74349212e.png)

**Comment by elliott-beach** [comment]
This problem has been solved 3 milion times, so is it really more likely that there's a fundumental error in the problem than that **you don't understand the problem**. Once we have selected the two vertical lines, all other lines should be disregarded. The "water level" to be calculuated is a single rectangle that does not allow for variation in elevation, and 49 is the correct answer.

**Comment by thisisashwinraj** [comment]
Thank you Eliott for the generous explanation :)
