### ISSUE TITLE
Missing Test Case - 695. Max Area of Island

### ISSUE THREAD

**Issue by mmkayPL** [LeetCode-Feedback/LeetCode-Feedback#11054]
#### Your LeetCode username

mkayPL

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

The input for C language version of this problem seems to be corrupted.  The following code should just print the same grid as was inputted, but it doesn't look anything like in example 1. The C++ version seems to be fine.

#### Code you used for Submit/Run operation

```
// maxAreaOfIsland
int maxAreaOfIsland(char** grid, int gridSize, int* gridColSize){
    int result = 0;

    for (int i = 0; i < gridSize; i++) {
        for (int j = 0; j < gridColSize[i]; j++) {
            printf("%d ", grid[i][j]);

            if (j == gridColSize[i] - 1) {
                printf("\n");
            }
        }
    }

    return result;
}
```

Wokring C++ version:
```
class Solution {
public:
    int maxAreaOfIsland(vector<vector<int>>& grid) {
        for (int i = 0; i < grid.size(); i++) {
            for (int j = 0; j < grid[i].size(); j++) {
                printf("%d ", grid[i][j]);
                if (j == grid[i].size() - 1) {
                    printf("\n");
                }
            }
        }

        return 0;
    }
};
```

#### Language used for code

C

#### Expected behavior

It should output the following grid for testcase 1
```
0 0 1 0 0 0 0 1 0 0 0 0 0 
0 0 0 0 0 0 0 1 1 1 0 0 0 
0 1 1 0 1 0 0 0 0 0 0 0 0 
0 1 0 0 1 1 0 0 1 0 1 0 0 
0 1 0 0 1 1 0 0 1 1 1 0 0 
0 0 0 0 0 0 0 0 0 0 1 0 0 
0 0 0 0 0 0 0 1 1 1 0 0 0 
0 0 0 0 0 0 0 1 1 0 0 0 0 
```
The following is seen instead:

```
0 0 0 0 0 0 0 0 1 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 1 0 0 0 1 0 0 0 0 
0 0 0 0 1 0 0 0 0 0 0 0 0 
0 0 0 0 1 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 
```

The overall result is of course that the answer is incorrect - running the proper algorithm on it returns 3 as the maximum size of the island instead of the 6 that the testcase expects.

#### Additional context

See https://leetcode.com/problems/max-area-of-island/submissions/878548958/ for the submission with the proper algorithm implemented.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
