### ISSUE TITLE
A Follow-up Requirement Should be Added - 2536. Increment Submatrices by One

### ISSUE THREAD

**Issue by shit-eater** [LeetCode-Feedback/LeetCode-Feedback#11050]
Your LeetCode username
v5qYY4Q65w

Category of the bug
- [√] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

Description of the bug
The solution with O(n^2+qn) time complexity can be accepted because of the terrible constraints of queries.length. But the expected solution of this problem must be using 2D differential array and 2D prefix sum. If an interviewee writes a solution with O(n^2+qn) time complexity, he will be asked for a better solution.  So a follow-up should be added:
Can you find a solution with O(n^2+q) time complexity?

Code you used for Submit/Run operation

The brute force with O(qn^2) time complexity. This code can get TLE.
```
class Solution:
    def rangeAddQueries(self, n: int, queries: List[List[int]]) -> List[List[int]]:

        res = [[0 for c in range(n)] for r in range(n)]

        for r1,c1,r2,c2 in queries:
            for r in range(r1,r2+1):
                for c in range(c1,c2+1):
                    res[r][c]+=1
        return res
```

The solution with O(n^2+qn). This code can be accepted.
```
class Solution:
    def rangeAddQueries(self, n: int, queries: List[List[int]]) -> List[List[int]]:

        res = [[0 for c in range(n)] for r in range(n)]

        for r1,c1,r2,c2 in queries:
            for r in range(r1,r2+1):
                res[r][c1]+=1
                if c2<n-1:
                    res[r][c2+1]-=1
        
        for r in range(n):
            for c in range(1,n):
                res[r][c]+=res[r][c-1]
        return res
```

The expected solution with O(n^2+q) time complexity.
```
class Solution:
    def rangeAddQueries(self, n: int, queries: List[List[int]]) -> List[List[int]]:

        res = [[0 for c in range(n)] for r in range(n)]
        for r1,c1,r2,c2 in queries:
            res[r1][c1]+=1
            if r2<n-1:
                res[r2+1][c1]-=1
            if c2<n-1:
                res[r1][c2+1]-=1
                if r2<n-1:
                    res[r2+1][c2+1]+=1
        
        for i in range(n):
            for j in range(n):
                if i:
                    res[i][j]+=res[i-1][j]
                if j:
                    res[i][j]+=res[i][j-1]
                    if i:
                        res[i][j]-=res[i-1][j-1]
        
        return res
```

Language used for code
Python3

Expected behavior
A follow up requirement should be added:
Can you find a solution with O(n^2+q) time complexity(q=queries.length)?

**Comment by LC-Pam** [comment]
Hi there,
Thank you for reaching out to us. I've relayed this issue to our team to investigate. We will reach back to you after we investigate.
Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The problem should not accept the qn solution, but currently, we are facing some technical issues and will reject this solution once we fix it. 

We appreciate your support!

If you have any other questions or feedbacks, please don't hesitate to let us know!
