### ISSUE TITLE
Example is buggy in "Design Singly Linked List - Solution" article

### ISSUE THREAD

**Issue by SergeShin** [LeetCode-Feedback/LeetCode-Feedback#11051]
#### Category of the bug
- [ ] Solution

#### Description of the bug

Html article contains wrong example : [Design Singly Linked List - Solution]

#### Wrong example
![Screenshot from 2023-01-15 10-36-35](https://user-images.githubusercontent.com/402395/212531192-43337684-9723-4c31-bfe9-0dee1ecf4943.png)

#### Proper example
```
class MyLinkedList {
    private SinglyListNode head;
    /** Initialize your data structure here. */
    public MyLinkedList() {
        head = new SinglyListNode(0);
    }
}
```

`head` is supposed to be "sentinel node" and not be `null`.

#### Additional context
[Design Singly Linked List - Solution](https://leetcode.com/explore/learn/card/linked-list/209/singly-linked-list/1298/)

**Comment by LC-Pam** [comment]
Hi there,
Thank you for reaching out to us.
 I've relayed this issue to our team to investigate. 
We will reach back to you after we investigate.
Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

This is the intentionally setting that the linked list head as NULL initially to indicate that there are no nodes at the start. A sentinel node is not necessary and would not work with the rest of the code.

If you have any other questions or feedbacks, please don't hesitate to let us know! 

We appreciate your support!
