### ISSUE TITLE
[Weekly Contest 328] 2536. Increment Submatrices by One - TLE solution accepted/Missing test case

### ISSUE THREAD

**Issue by ArshadAQ** [LeetCode-Feedback/LeetCode-Feedback#11056]
#### Your LeetCode username
ArshadAQ

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
Accepted solution(https://leetcode.com/contest/weekly-contest-328/submissions/detail/878335756/) gets TLE on the following test case
[inc-sub-one-tc-updated.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/10420436/inc-sub-one-tc-updated.txt)

#### Code you used for Submit/Run operation
```
class Solution {
    public int[][] rangeAddQueries(int n, int[][] queries) {
        int[][] res = new int[n][n];
        for(int[] q : queries){
            for(int i = q[0]; i <= q[2]; i++){
                for(int j = q[1]; j <= q[3]; j++){
                    res[i][j] +=1;
                }
            }
        }
        return res;
    }
}
```

#### Language used for code
Java

#### Expected behavior
Solution shouldn't have been accepted

#### Screenshots
![image](https://user-images.githubusercontent.com/25927120/212547025-25658cdc-18e8-472c-bb5c-ba20ccf6402c.png)

**Comment by LC-Pam** [comment]
Hi there,
Thank you for reaching out to us. I've relayed this issue to our team to investigate. We will reach back to you after we investigate.
Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've used your feedback to check the problem.

Due to there are some limitations on the library, so we cannot add this test case.

If you have any other questions or feedbacks, please don't hesitate to let us know!

We appreciate your support!

**Comment by ArshadAQ** [comment]
The reasoning is unclear.
@LC-Pam Can you please help me elaborate this statement - "Due to there are some limitations on the library, so we cannot add this test case."

What library are we referring to?

The test case I've given is within the given problem constraint. So, how can we not add it?
