### ISSUE TITLE
Missing Test Case - 724. Find Pivot Index

### ISSUE THREAD

**Issue by Varghab** [LeetCode-Feedback/LeetCode-Feedback#11059]
#### Your LeetCode username
LeetCode ID: shibvarghab
Name - Varghab Shib

#### Category of the bug
Missing test case 

#### Description of the bug
Leetcode is accepting the solution though the solution is wrong.

#### Code you used for Submit/Run operation
```
class Solution {
public:
    int pivotIndex(vector<int>& nums) {
        if(nums.size()==1 && nums[0]!=0){
            return 1;
        }
        int l=0;
        int r=0;
        for(int i=0;i<nums.size();i++){
            r += nums[i];
        }
        for(int i=0;i<nums.size();i++){
            r = r-nums[i];
            if(l==r){
                return i;
            }
            l = l+nums[i];
        }
        return -1;
    }
};
```

#### Language used for code

C++

#### Expected behavior
Please refer to my code, for the Input - [4], the expected output is 0 but my code returns 1 as a result. As the code is wrong for this input still I could successfully submit my solution and leetcode accepted my solution.

#### Screenshots
![leetcode pivot](https://user-images.githubusercontent.com/59419650/212558504-d253eb3c-5ebf-4034-bd40-603bd07b5578.png)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as the reward for this feedback. 

If you have any other questions or feedbacks, please don't hesitate to let us know! 

We appreciate your support!
