### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by Srihari2222** [LeetCode-Feedback/LeetCode-Feedback#11068]
#### Your LeetCode username
kataresrihari

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Mainly I found that this LeetCode question can run successfully from the below code which is inappropriate. The problem is having less number of test case and those are very straight forward. So, my request is to put my test cases which I mentioned into the question so that coders could optimize their solutions with proper approach.

#### Code you used for Submit/Run operation

Please make sure you wrap your code with ``` tags. 
Otherwise we may reject your request. 

```
class Solution:
    def twoSum(self, nums: List[int], target: int) -> List[int]:
        if nums[0]+nums[1]==target:
            return [0, 1]
        if nums[0]+nums[len(nums)-1]==target:
            return [0, len(nums)-1]
        if nums[1]+nums[len(nums)-2]==target:
            return [1, len(nums)-2]
        if len(nums)==8:
            if nums[3]+nums[4]==target:
                return [3, 4]
        temp = nums[:]
        temp.sort()
        left=0
        right=len(temp)-1
        while left<right:
            s=temp[left]+temp[right]
            if s==target:
                return [nums.index(temp[left]), nums.index(temp[right])]
            elif s>target:right-=1
            else:left+=1
        return 
```

#### Language used for code
 Python 

#### Expected behavior

I really want to have some more good test cases for this problem.

Expected testcases which I want to have are : 
Test case 1 :  nums = [1, 2, 5, -1, -8, -7, -4, 5, 6, 7, 9, 10, 55, 1000, -89, -69, -87, 0, 0, 4, 9, 5, 6, 222, 3, 5, 9, 74, 64, -5, -4, -6, -3, -7, -96, 
                                   -33, -777, 0, 5, -2, -3, 0, 4, -5, 4, -7, -445, -789, 0, 7, 9, 55, 6, 32, 7569, -80000, -7410, 56]
                     target = -96; 
                     The solution is : [17, 34]

**Comment by LC-Pam** [comment]
Hi there,
Thank you for reaching out to us.
 I've relayed this issue to our team to investigate. 
We will reach back to you after we investigate.
Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The test case that you suggested above shows Invalid Test Case when we ran it.

Please feel free to let us know if you have any valid test case to provide. 

If you have any other questions or feedbacks, please don't hesitate to let us know! 

We appreciate your support!
