### ISSUE TITLE
Something wrong with judgement 538. Convert BST to Greater Tree

### ISSUE THREAD

**Issue by JumHorn** [LeetCode-Feedback/LeetCode-Feedback#1106]
#### Your LeetCode username

JumHorn

#### Category of the bug
* Question

#### Description of the bug

the result is totally the same as Expected,however got wrong answer
there is something wrong with this problem

#### Code you used for Submit/Run operation

```
class Solution
{
public:
	TreeNode *convertBST(TreeNode *root)
	{
		int sum = 0;
		reverseInorder(root, sum);
		return root;
	}

	void reverseInorder(TreeNode *root, int &sum)
	{
		if (root == nullptr)
			return;
		reverseInorder(root->right, sum);
		root->val += sum;
		sum = root->val;
		reverseInorder(root->left, sum);
	}
};
```

#### Language used for code

C++

**Comment by martyyoung90** [comment]
same here
![image](https://user-images.githubusercontent.com/22531614/94734823-a1008480-031e-11eb-9748-046fbc8b4427.png)

**Comment by lc-kay** [comment]
Hi @JumHorn @martyyoung90. 

Our team was notified of this issue and have fixed it. Thank you for your time!
