### ISSUE TITLE
Missing Test Case - 217. Contains Duplicate

### ISSUE THREAD

**Issue by Sumit068** [LeetCode-Feedback/LeetCode-Feedback#11061]
#### Your LeetCode username
Sumit_068

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I am provide a code which submitted by someone else and accepted by leetcode. this code contain many if statement and it runtime 0ms. so I try to understand this code. i analysis this code, use my own testcase and found this entire code is wrong. this person write a code in a such way that passed all leetcode testcases.
.
please, i am requesting carefully investigate this code. i can provide a lots of testcase where it will fail but still leetcode accepted due to missing testcases. I already provide you solution but you reject and says i use many if statement and submitted just for get points. but actually this code submitted by someone else.
.
I hope this time you will carefully investigate code and update new testcases.

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean containsDuplicate(int[] nums) {
        if (nums.length==2 && (nums[0]==-24500 || nums[0]==237384)) return true;
        if (nums.length==0 || nums[0]==237384 || nums[0]==-24500) return false;
        if (nums[0]==2048) return false;
        if (nums[0]==30720) return false;
        boolean[] k = new boolean[2048];
        for (int i=0; i<nums.length; i++){
            if (k[nums[i] & 2047]) return true;
            else k[nums[i] & 2047] = true;
        }
        return false;
    }
}
```

#### Language used for code

JAVA

#### Expected behavior

Testcases :- [2049,1]
Output :- true
Expected :- false

Testcases :- [0,2048]
Output :- true
Expected :- false

Testcases :- [-1,2047]
Output :- true
Expected :- false

best Testcase :- [-20000 to 20000]  (without any repeat && also you can increase range)
Output :- true
Expected :- false

#### Screenshots

![image](https://user-images.githubusercontent.com/82926215/212562868-20d328a7-1266-4421-a2e9-7ed86b4cc176.png)
code is accepted

![image](https://user-images.githubusercontent.com/82926215/212563222-065d2ad6-afd6-4259-b2f6-c304d1dbd49b.png)
another similar code like above i provide you. it still accepted. it also wrong code.
in this code user just double the size of array.

#### Additional context
failed to pass my testcases

![image](https://user-images.githubusercontent.com/82926215/212562892-6f14dae0-906a-40d4-a86d-c625979770c8.png)
![image](https://user-images.githubusercontent.com/82926215/212562904-59ab2f5b-5866-4ce7-81e7-20c202813b66.png)
![image](https://user-images.githubusercontent.com/82926215/212562921-9c5a4f7e-dd45-4f3b-a0fc-cbd6afbcc011.png)
![image](https://user-images.githubusercontent.com/82926215/212562930-f485605e-a222-4cca-807f-fdcaad74f37f.png)
![image](https://user-images.githubusercontent.com/82926215/212562943-78700ba9-ef86-4ee1-838e-2372c5398ab8.png)
![image](https://user-images.githubusercontent.com/82926215/212562974-fc0d97cd-47bb-42a5-bc48-fa686d98686c.png)

**Comment by LC-Pam** [comment]
Hi there,
Thank you for reaching out to us.
 I've relayed this issue to our team to investigate. 
We will reach back to you after we investigate.
Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as the reward for this feedback. 

If you have any other questions or feedbacks, please don't hesitate to let us know! 

We appreciate your support!
