### ISSUE TITLE
Incomplete Question - 225. Implement Stack using Queues

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1107]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

- Can you state performance requirements in the question?

232. Implement Queue using Stacks
https://leetcode.com/problems/implement-queue-using-stacks/

225. Implement Stack using Queues
https://leetcode.com/problems/implement-stack-using-queues/

- Especially if pop() is used on queue to implement stack,
	how to do this in O(1)?
	because stack's pop() for "top" element is O(1)?
	and     queue's pop() for "same top" element is O(N) becaues it removes from back.

- if we are removing all elements to get to top() where should we put it? these questions are not clear in the question.

- Question to use "list or deque" - there is a lot of difference between these two in performance wise - why such a suggestion is made? "deque" is more optimal for deletes. Should the question suggest to only use "list"?

- I can follow the question requirement, submit an answer and Pass it
but what is the author trying to tell us
to learn?
this is not very clear.

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

- Question asks to implement a data structure that is optimal for something using a data structure optimized for something else, in this scenario, how can we ensure optimal behaviour of 1st using second for all operations 2nd one has?
  - Question must include details on expected performance.

- Please address both questions given above, as applicable.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
