### ISSUE TITLE
probable formating mistake in official solution for the 57. Insert Interval

### ISSUE THREAD

**Issue by b10s** [LeetCode-Feedback/LeetCode-Feedback#11078]
#### Your LeetCode username
b10s

#### Category of the bug
- [ ] Solution
![Selection_411275](https://user-images.githubusercontent.com/4618288/212730225-0ad28f98-e2cd-4bd2-b7b9-b104188004a0.png)

**Comment by LC-Pam** [comment]
Hi there,
Thank you for reaching out to us.
 I've relayed this issue to our team to investigate. 
We will reach back to you after we investigate.
Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

If you have any other questions or feedbacks, please don't hesitate to let us know! 

We appreciate your support!
