### ISSUE TITLE
Missing Constraints - 232. Implement Queue using Stacks - 225. Implement Stack using Queues

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1108]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

232. Implement Queue using Stacks
https://leetcode.com/problems/implement-queue-using-stacks/

225. Implement Stack using Queues
https://leetcode.com/problems/implement-stack-using-queues/

Constraints are missing for both of the above questions: (which look similar so giving in this one bug)
1. How many operations will be done?
2. Any specific range for integers when push'ed? like below?
>     -3000 < x < 3000

Please fix for both questions.

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

- Question must have constraints so as to Pass in 1st submission
- Please add constraints for both questions given in the description above.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy ,
Thank you for your feedback. Upon review, both problems have been updated. The team also mentioned that though you're welcome to issue tickets on GitHub, we will not be rewarding users with LeetCoins for the following tickets as these are known issues. Thank you once again and happy LeetCoding!
