### ISSUE TITLE
Missing Test Case - 834. Sum of Distances in Tree

### ISSUE THREAD

**Issue by projecteulerlover** [LeetCode-Feedback/LeetCode-Feedback#11080]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The current test coverage does not include the star graph test case, which runs in O(n^2) with certain solutions.

#### Code you used for Submit/Run operation

```
// Sum of Distances in Tree
class Solution {
public:
    vector<unordered_map<int, pair<int, int>>> dp;

    // children
    pair<int, int> dfs1(const vector<vector<int>>& adj, int u, int p = -1) {
        auto itr = dp[u].find(p);
        if (itr != dp[u].end()) return itr->second;
        int vc = 1, ec = 0;
        for (int v : adj[u]) {
            if (v == p) continue;
            auto [n_vc, n_ec] = dfs1(adj, v, u);
            vc += n_vc, ec += n_ec + n_vc;
        }
        dp[u][p] = {vc, ec};
        return dp[u][p];
    }

    vector<int> sumOfDistancesInTree(int n, vector<vector<int>>& edges) {
        vector<vector<int>> adj(n);
        for (const auto& e : edges) adj[e[0]].push_back(e[1]), adj[e[1]].push_back(e[0]);
        vector<int> res(n);
        dp = vector(n, unordered_map<int, pair<int, int>>());
        for (int u=0; u<n; ++u) res[u] = dfs1(adj, u).second;
        return res;
    }
};
```

#### Expected behavior

This solution TLEs on the star graph input (a tree on 3 * 10^4 nodes, where nodes 1...n-1 are connected to node 0. I have attached the test case [below.]([url](url))

**Comment by projecteulerlover** [comment]
[834.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/10430350/834.txt)
Test case in question.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback. 

Please send us your Leetcode username.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by projecteulerlover** [comment]
Hi, my LC username is "changhsumath666". Thank you!

**Comment by projecteulerlover** [comment]
Sorry for the bother. This was my fault since I didn't originally include
the username when creating the issue- is it still possible to get the
coins? Thanks!

**Comment by projecteulerlover** [comment]
Checking on the status of this, as I still have not received any LC coins.

**Comment by projecteulerlover** [comment]
Once again, checking on the status of this, as I still have not received
any LC coins. Thank you for taking a look.

**Comment by projecteulerlover** [comment]
> Thank you for your time.
> 
> We've used your feedback to update the problem.
> 
> Your LeetCode account will receive 100 LeetCoins as a reward for this feedback.
> 
> Please send us your Leetcode username.
> 
> If you have any other questions or feedback, please don't hesitate to let us know!
> 
> We appreciate your support!

@LC-Pam, I know there must be a lot on your plate.

I am politely still looking for a response on this. My points has not been updated.

Thanks.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
