### ISSUE TITLE
Missing Test Case - 2246. Longest Path With Different Adjacent Characters

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#11081]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets TLE on the following testcase:
[1.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/10430567/1.txt)

#### Code you used for Submit/Run operation

```
class Solution:
    def longestPath(self, parent: List[int], s: str) -> int:
        #n=100000
        #parent=[-1]+[0 for i in range(1,n)]
        #s="a"+"b"*(n-1)
        @lru_cache(None)
        def dfs(cur: int, pre: int) -> int:
            res = 1
            for next in adjMap[cur]:
                if next == pre or s[next] == s[cur]:
                    continue
                res = max(res, dfs(next, cur) + 1)
            return res

        n = len(parent)
        adjMap = defaultdict(set)
        for i in range(n):
            pre, cur = parent[i], i
            if pre == -1:
                continue
            adjMap[pre].add(cur)
            adjMap[cur].add(pre)

        res = 1
        for i in range(n):
            res = max(res, dfs(i, -1))
        dfs.cache_clear()
        return res
```

#### Language used for code

Python3

#### Expected behavior

The code gets TLE.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as the reward for this feedback. 

If you have any other questions or feedbacks, please don't hesitate to let us know! 

We appreciate your support!
