### ISSUE TITLE
Missing Test Case - 1519. Number of Nodes in the Sub-Tree With the Same Label

### ISSUE THREAD

**Issue by Wsp0000** [LeetCode-Feedback/LeetCode-Feedback#11093]
#### Your LeetCode username
wsp0000

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```java
// 1519. Number of Nodes in the Sub-Tree With the Same Label
// the official solution Approach 1: Depth First Search, java code
// 
class Solution {
    public int[] dfs(int node, int parent, Map<Integer, List<Integer>> adj,
            char[] labels, int[] ans) {
        // Store count of all alphabets in the subtree of the node.
        int[] nodeCounts = new int[26];
        nodeCounts[labels[node] - 'a'] = 1;

        if (!adj.containsKey(node))
            return nodeCounts;
        for (int child : adj.get(node)) {
            if (child == parent) {
                continue;
            }
            int[] childCounts = dfs(child, node, adj, labels, ans);
            // Add frequencies of the child node in the parent node's frequency array.
            for (int i = 0; i < 26; i++) {
                nodeCounts[i] += childCounts[i];
            }
        }

        ans[node] = nodeCounts[labels[node] - 'a'];
        return nodeCounts;
    }

    public int[] countSubTrees(int n, int[][] edges, String labels) {
        Map<Integer, List<Integer>> adj = new HashMap<>();
        for (int[] edge : edges) {
            int a = edge[0], b = edge[1];
            adj.computeIfAbsent(a, value -> new ArrayList<Integer>()).add(b);
            adj.computeIfAbsent(b, value -> new ArrayList<Integer>()).add(a);
        }

        int[] ans = new int[n];
        char[] label = labels.toCharArray();
        dfs(0, -1, adj, label, ans);
        return ans;
    }
}
```

#### Language used for code
Java, also tested Javascript with same behavior

#### Expected behavior

Expected: Wrong Answer
actually happened: Accepted

according Description Constraints:

test case:

```text
1
[]
"a"
```

n=1
edges=[]
labels="a"
is valid, but code still submit Success.

[Description](https://leetcode.com/problems/number-of-nodes-in-the-sub-tree-with-the-same-label/)

You are given a tree (i.e. a connected, undirected graph that has no cycles) consisting of n nodes numbered from 0 to n - 1 and exactly n - 1 edges. The root of the tree is the node 0, and each node of the tree has a label which is a lower-case character given in the string labels (i.e. The node with the number i has the label labels[i]).

The edges array is given on the form edges[i] = [ai, bi], which means there is an edge between nodes ai and bi in the tree.

Return an array of size n where ans[i] is the number of nodes in the subtree of the ith node which have the same label as node i.

A subtree of a tree T is the tree consisting of a node in T and all of its descendant nodes.

Constraints:

1 <= n <= 10^5
edges.length == n - 1
edges[i].length == 2
0 <= ai, bi < n
ai != bi
labels.length == n
labels is consisting of only of lowercase English letters.

#### Screenshots

![截圖 2023-01-18 上午1 45 55](https://user-images.githubusercontent.com/30068092/212973418-93128ca3-c3dd-407f-8eb0-63a3aba881f1.png)

#### Additional context

I think is because line 8, 9 
when no edge, adj not contain root(=0) ,then without add count to `ans` array immediately return

```java
if (!adj.containsKey(node))
            return nodeCounts;
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
