### ISSUE TITLE
1198. 找出所有行中最小公共元素 缺少测试用例

### ISSUE THREAD

**Issue by NP-Prob** [LeetCode-Feedback/LeetCode-Feedback#11092]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**Darren**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述**
测试数据有疏漏，不应accepted的代码通过所有有测试数据，并且该代码为当前通过该题代码用时记录中最短者

**你使用的语言**
Python3

**你提交或者运行的代码**
测试用例：
[[9,10,13,14,15],[2,4,5,8,10],[3,5,7,9,11],[1,3,5,7,9]]

错误代码：
```
class Solution:
    def smallestCommonElement(self, mat: List[List[int]]) -> int:
        for flag in mat[0]:
            cur = 0
            for i in range(1,len(mat)):
                if mat[i][bisect_left(mat[i],flag)] == flag:
                    cur += 1
                else:
                    break
            if cur == len(mat) - 1:
                return flag
        return -1
```

**期望行为**
正确返回值应为-1，该代码执行过程中应发生错误

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode-cn.com/hc/kb/article/1277837 ），我们给予积分奖励哦。

**Comment by NP-Prob** [comment]
> 你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode-cn.com/hc/kb/article/1277837 ），我们给予积分奖励哦。

你好，我的力扣中文站个性域名是：
leetcode-cn.com/u/np_prob/

**Comment by feiceh** [comment]
收到，奖励已发放。

**Comment by NP-Prob** [comment]
> 收到，奖励已发放。

收到，谢谢。
