### ISSUE TITLE
1480. Running Sum of 1D Array

### ISSUE THREAD

**Issue by 24luca24** [LeetCode-Feedback/LeetCode-Feedback#11091]
#### Your LeetCode username 
user1657qM

#### Category of the bug
- [ ] Question
- [✔︎ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The first solution of the video, where the problem 1480 is showed, is wrong. I run it and give me the output wrong answer.

#### Code you used for Submit/Run operation

Please make sure you wrap your code with ``` tags. 
Otherwise we may reject your request. 
-->

```
// Running Sum of 1D Array
class Solution {
    public int[] runningSum(int[] nums) {
        int[] results = new int[nums.length];
        results[0] = nums[0];

          for(int i = 1; i < nums.length; i ++) {
             results[i] = results[i] + results[i - 1];
    }
        return results;
    }
}
```

#### Expected behavior

I copied the code, from the example shown in the video and when i pressed the run button, it gave me error

#### Screenshots

<img width="637" alt="image" src="https://user-images.githubusercontent.com/104214088/212954140-73c38403-445b-465e-a9a3-76839eff2f31.png">
<img width="628" alt="image" src="https://user-images.githubusercontent.com/104214088/212954231-eb4b961d-f6da-4938-bef9-384b0490cc00.png">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

We found an issue with your above code:

the following line is wrong  -  results[i] = results[i] + results[i - 1];

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
