### ISSUE TITLE
121. Best Time to Buy and Sell Stock

### ISSUE THREAD

**Issue by mv1github** [LeetCode-Feedback/LeetCode-Feedback#1109]
#### Your LeetCode username
moasis_99

#### Category of the bug
- [ ] Question

Input: [7,1,5,3,6,4]
Output: 5
Explanation: Buy on day 2 (price = 1) and sell on day 5 (price = 6), profit = 6-1 = 5.
             Not 7-1 = 6, as selling price needs to be larger than buying price.

- [ ] Solution
- [ ] Language

#### Description of the bug

Buy on day 2( price =1) and sell on day 3(price = 5) - profit = 5-1 = 4 , buy on day 4 (price 3) sell on day 5 (price 6) profit 6 -3 = 3
total profit 7. Am I missing anything?

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
Hi @mv1github, 

Please refer to the problem description. It's explained in the description that you are only permitted to complete at most one transaction.
