### ISSUE TITLE
Missing Test Case - 8. String to Integer (atoi)

### ISSUE THREAD

**Issue by rohan-algorithm** [LeetCode-Feedback/LeetCode-Feedback#11098]
#### Your LeetCode username 
rohan_cs

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases

#### Description of the bug

Missing Test Case

#### Code you used for Submit/Run operation

```
// 8. String to Integer (atoi)

class Solution {
public:
    int myAtoi(string s) {
        int ans=0,i=0;
        while(i<s.size()&&(s[i]<48||s[i]>57)) {
            if((s[i]=='+'||s[i]=='-')) break;
            i++;
        }
       int k=i;
        if(i-2>=0&&s[i]>='0'&&s[i]<='9'&&s[i-1]==' '&&(s[i-2]!=' '))
        return 0;
        else if(i-1>=0&&s[i-1]!=' ')
        return 0;
        bool b=1;
        if(s[i]=='-'){
           b=0;
           i++;
        }else if(s[i]=='+') i++;

        while(i<s.size()){
            if(s[i]==' ') break;
            if(i<s.size()&&(s[i]>='0'&&s[i]<='9')){ 
            int dig =s[i]-'0';
            long long c= (long long)ans*10+dig;
            if(c>INT_MAX){
                if(b==0) return INT_MIN;
                return INT_MAX;
            }
            ans=(ans*10)+dig;
            i++;
            }
            else break;

        }
        if(b==0) return -ans;
        return ans;

      
    }
};
```

#### Language used for code

C++

#### Expected behavior

Expected: Wrong Answer
**Actually Happened:** Accepted

Test Case 

`"i love       42888 and"` 

**My Output**  =  42888
**Expected(correct output)**  =  0

Explanation - Actually if there is space i.e '  '  before any number and if there exist a word before it then output should be 0 or if 'i' (where i is starting index of a number in a  given sting) and s[i-1]==' ' and if s[i-2] or s[i-3] or s[uptill i>=0] !='  ' then return 0

#### Screenshots

<img width="1440" alt="Screenshot 2023-01-18 at 2 41 21 AM" src="https://user-images.githubusercontent.com/43471954/213013830-4f9453d9-69d5-432b-a121-b2057b441b31.png">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as the reward for this feedback. 

If you have any other questions or feedbacks, please don't hesitate to let us know! 

We appreciate your support!
