### ISSUE TITLE
Missing Test Case - 926. Flip String to Monotone Increasing

### ISSUE THREAD

**Issue by HamzaElkotp** [LeetCode-Feedback/LeetCode-Feedback#11096]
#### Your LeetCode username
HamzaElkotb

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
i think these 3 test cases are conflict
"00011000"
"001110010"
"1111001110"

#### Code you used for Submit/Run operation

```
var minFlipsMonoIncr = function(s) {
    let newS = s.split("").sort().join("");
    console.log(s)
    console.log(newS)
    let moves = 0;
    for(let i=0; i<s.length; i++){
        let res = +s[i] - +newS[i];
        if(res != 0){
            if(+s[i] == 1){
                if(+s[i+1] != 1){
                    moves++
                }
            }
            if(+s[i] == 0){
                if(+s[i+1] == 0 && +newS[i+1] == 1){
                    continue
                }
                moves++
            }
        }
    }
    return moves
};
```

#### Expected behavior
first 2
second 3
third 2

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The above code received Wrong Answer when we submitted it.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
