### ISSUE TITLE
Missing Test Case 1038. Binary Search Tree to Greater Sum Tree

### ISSUE THREAD

**Issue by vmikhieienko** [LeetCode-Feedback/LeetCode-Feedback#11099]
#### Your LeetCode username
vmikhieienko

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Please add the following testcase: [4,1,6,0,2,5,7,null,null,null,3,null,null,null,9]

#### Code you used for Submit/Run operation

```python
# 1038. Binary Search Tree to Greater Sum Tree
# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
class Solution:
    def bstToGst(self, root: TreeNode) -> TreeNode:
        self.max_val = None

        def dfs(node):
            if not node: return

            dfs(node.right)

            if not self.max_val:
                self.max_val = node.val
            else:
                for i in range(self.max_val, node.val, -1):
                    node.val += i

            dfs(node.left)
        dfs(root)
        return root
```

#### Language used for code
Python

#### Expected behavior
My code passes all checks on leetcode but it doesn't check that case.
I implemented the algorithm that works only with sequence of the tree node values with +1 step, from 0 to 8, f.e. [1, 2, 3, 4, 5, 6, 7, 8]. But if there's a gap between values, it didn't work but leetcode doesn't check it, f.e. [1, 2, 3, 4, 5, 6, 7, 9].

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as the reward for this feedback. 

If you have any other questions or feedbacks, please don't hesitate to let us know! 

We appreciate your support!
