### ISSUE TITLE
网站bug，非某个题目bug

### ISSUE THREAD

**Issue by ruichuntao** [LeetCode-Feedback/LeetCode-Feedback#111]
- [ ] ** Bug 类型**

- [ ] 题目
- [x] 题解
- [ ] 编程语言

**描述**
使用代理，登录状态会消失，这个反馈过了，没有用。
搜索题解的时候，选择标签“java”，翻页就会消失

**你使用的语言**
java

**你提交或者运行的代码**
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
        
    }
};
```

**期望行为**
描述你期望的结果

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，该问题已转给相关团队后期会持续优化，给您带来的不便敬请谅解。Github 仓库只用于反馈大家在本站学习过程中遇到的题目和题解问题，请知晓～

**Comment by ruichuntao** [comment]
> 感谢反馈，该问题已转给相关团队后期会持续优化，给您带来的不便敬请谅解。Github 仓库只用于反馈大家在本站学习过程中遇到的题目和题解问题，请知晓～

那网址bug去哪里反馈呢

**Comment by feiceh** [comment]
感谢您对力扣网站的支持，如有其他问题，欢迎点击这里（https://support.leetcode-cn.com/hc/request/new/）提交工单反馈，谢谢。
