### ISSUE TITLE
github.com/emirpasic/gods库支持不完整

### ISSUE THREAD

**Issue by CLOUDERHEM** [LeetCode-Feedback/LeetCode-Feedback#11104]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
我怎么就想不到解法啊

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [x] 编程语言
- [ ] 缺少测试用例

**描述**

题目: [347. 前 K 个高频元素](https://leetcode.cn/problems/top-k-frequent-elements/)

leetcode支持的`github.com/emirpasic/gods` 第三方库不完整, 导入如下库会报错
```
import ("github.com/emirpasic/gods/queues/priorityqueue")
```

**你使用的语言**
golang

**屏幕截图**

![image](https://user-images.githubusercontent.com/78064276/213111277-f7343c25-2b90-4651-8e5a-5ca28ac56f4d.png)

**Comment by feiceh** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励哦。

**Comment by CLOUDERHEM** [comment]
> 你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励哦。

https://leetcode.cn/u/pornhub, 感谢!

**Comment by feiceh** [comment]
收到，积分奖励已发放。
