### ISSUE TITLE
Confusing Constraints - 598. Range Addition II

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1110]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

598. Range Addition II
https://leetcode.com/problems/range-addition-ii/

Confusing constraints:
- What the meaning of the below constraint?
> The range of operations size won't exceed 10,000.

- Size is a single value, why the "range" of a single value won't exceed a "single value"?
- In other words, do you mean max size?

Please change:

From
> The range of operations size won't exceed 10,000

To
> The operations size won't exceed 10,000

OR

> The range of operations size is between [0, 10,000]

In other words, a range cannot `exceed`, it can only be in `between`

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

- Write constraints in one of the below format:
  - `The operations size won't exceed 10,000` and be careful with English & Math wording.
  - `0 <= size <= 10,000` then the English & Math wording won't matter.

- Due to this confusing wording (range being referred as if it is a single value), I got a "Wrong Answer", see https://leetcode.com/pgmreddy/
  - 90+% of my wrong answers are due to this kind of issues
  - So if I had a doubt, why did I attempt this? Because I can't skip all questions & sit idle :) - see other issues that are active now.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
