### ISSUE TITLE
Missing Test Case - 35. Search Insert Position

### ISSUE THREAD

**Issue by Dragos1402** [LeetCode-Feedback/LeetCode-Feedback#11103]
HOW?

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Search Insert Position
public class Solution
    {
        public int SearchInsert(int[] nums, int target)
        {
            int i = 0;
            foreach (var elem in nums)
            {
                if (elem == target)
                {
                    i = Array.IndexOf(nums, target);
                    break;
                }
                if(elem!=target)
                {
                   
                    i=1;
                }
            }
            return i;
        }
    }
```

#### Expected behavior

3rd TestCase when trying to press Run/Submit:

[1,3,5,6] , 7 -> Input
1 -> MyOutput
4-> Expected Output

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The above code received Wrong Answer when we submitted it.

https://leetcode.com/submissions/detail/880742902/

The judger appears to be working correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
