### ISSUE TITLE
Sample costs less than same code in submission Java - 278 - First Bad Version

### ISSUE THREAD

**Issue by Effervescent-opportunity** [LeetCode-Feedback/LeetCode-Feedback#11106]
#### Your LeetCode username
Ziggismunt

#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
I've done task 278 in Java by myself, then I copy-pasted Sample 38.4 MB Submission, submitted it and got result 39.4 MB. It's not correct. Same code must cost same memory, isn't it?

Proofs added as screenshots

#### Code you used for Submit/Run operation

```
// First Bad Version
public class Solution extends VersionControl {
    public int firstBadVersion(int n) {
        int start = 1, end = n;
        while (start <= end) {
            int mid = start + (end-start) / 2;
            if (isBadVersion(mid)) end = mid - 1;
            else start = mid + 1;            
        }        
        return start;
    }
}
```

#### Language used for code
Java

#### Expected behavior
As Is: code in sample costs less than same code in submission
To be: code in sample has cost equals to same code in submission

#### Screenshots
![Leetcode278-my-39mb](https://user-images.githubusercontent.com/41738221/213131516-de151bc4-267d-455b-a835-b9a9a3ee9914.png)
![Leetcode278-same-38mb](https://user-images.githubusercontent.com/41738221/213131523-cf073cc3-4432-49ae-8783-27a160435ca6.png)

#### Additional context
It's also not fair, because you show that my submission beats 55.69% and then show counted value with this is my profile.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

It’s very difficult and ongoing research to evaluate the program’s runtime and memory usage and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make it extremely hard to quantify the runtime and memory usage correctly.

Factors include compiler changes, optimizations, and more features that our developers keep on working on to provide better UX. These factors also affect the runtime and memory usage of the same program, introducing some level of discrepancy.

I hope this explanation answers your doubts. If you have any other questions, please don't hesitate to let us know.
