### ISSUE TITLE
Wrong Test Case - 414. Third Maximum Number

### ISSUE THREAD

**Issue by kumarmanishrai** [LeetCode-Feedback/LeetCode-Feedback#11118]
#### Your LeetCode username

kumarmanishrai

#### Category of the bug
- [x] Solution
- [x] Test Case

#### Description of the bug

In ques- Third Maximum Number
the test case number 29 :  nums = [1,2,2,5,3,5]
the output should be 2 but the testcase is giving output 3 and the expected ans is 2.

#### Code you used for Submit/Run operation

```
// Third Maximum Number
class Solution {
public:
    int thirdMax(vector<int>& nums) {
        vector<int>::iterator ip;

        ip = std::unique(nums.begin(), nums.begin()+nums.size());

        nums.resize(std::distance(nums.begin(), ip));

        sort(nums.begin(), nums.end());
        reverse(nums.begin(), nums.end());
        int res = 0;
        if(nums.size()<3)
            res= nums[0];
        else
            res = nums[2];
        
        return res;

    }
};
```

#### Language used for code
C++ 

#### Expected behavior

In test case 29, I was expecting the output to be 2 but the test case is giving output 3.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
