### ISSUE TITLE
Add more large test cases: 974. Subarray Sums Divisible by K

### ISSUE THREAD

**Issue by priyanshu-28** [LeetCode-Feedback/LeetCode-Feedback#11119]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

This may not be the only question that has these types of discrepancies. I believe there are many more questions like this. The issue is that the number of large test cases for any problem is not enough and so the brute force solution is passing the test cases after adding answers for manual test cases. Please look at the code to understand the issue better.

#### Code you used for Submit/Run operation

```
// 974. Subarray Sums Divisible by K

#define FIO ios_base::sync_with_stdio(false);cin.tie(0);cout.tie(0)

class Solution {
public:
    int subarraysDivByK(vector<int>& nums, int k) {
        FIO;
        int ans = 0;
        if(k == 586){
            return 767481;
        }
        if(k == 1823){
            return 247783;
        }
        if(k == 10000){
            return 450015000;
        }
        if(k == 1790){
            return 251675;
        }
        if(k == 297){
            return 1514445;
        }
        if(k == 4141){
            return 108696;
        }
        int sum = 0;
        int n = nums.size();

        int cnt[n + 1];
        for(int i = 0; i < n; i++){
            sum = 0;
            for(int j = i;j < n; j++){
                sum+=nums[j];
                if(!(sum % k)){
                    ans++;
                }
            }
        }
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

I expected that the number of very large test cases should be enough not to pass the brute force solution, but it turns out that one can brute force them, and there may be many other questions that have such a discrepancy because the number of large test cases is very less.

#### Additional context

I want to suggest that you make enough large test cases that do not run on the brute force solution.

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Comment by priyanshu-28** [comment]
sorry, should i paste the file with test cases here or should I create a new issue? @LC-Pam

**Comment by priyanshu-28** [comment]
and I suggested adding multiple test cases with N = 10^4, not just one, so I cannot just simply send all the files with N = 10^4. My main concern was that there should be at least one hundred test cases with N = 10^4 so one cannot brute force everything
