### ISSUE TITLE
Solution Formula issue - 598. Range Addition II

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1111]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

598. Range Addition II

https://leetcode.com/problems/range-addition-ii/

The solution that is given at https://leetcode.com/problems/range-addition-ii/solution/
has an issue with the pairing of brackets

Please change

From:
> This corner is given by (x,y)=(min(op[0],min(op[1]))

To:
> This corner is given by (x,y)=(min(op[0]),min(op[1]))

Note that ")" is added after "op[0]"

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

- In Math posts, if a bracket is not included it will give a different meaning. So proper care has to be taken.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
