### ISSUE TITLE
Missing Test Case - 2110. Number of Smooth Descent Periods of a Stock

### ISSUE THREAD

**Issue by muller2333** [LeetCode-Feedback/LeetCode-Feedback#11111]
#### Your LeetCode username

muller2333

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

An accepted solution fails on the following testcase:
[2110_testcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/10445767/2110_testcase.txt)

#### Code you used for Submit/Run operation

```
class Solution {
    public long getDescentPeriods(int[] prices) {
        int length = prices.length;
        int count = 1;
        long res = 0;
        for (int i = 0; i < length - 1; i++) {
            if (prices[i] - prices[i + 1] == 1) {
                count++;
            } else {
                res += (count + 1) * count >> 1;
                count = 1;
            }
        }
        return res + (count + 1L) * count / 2;
    }
}
```

#### Language used for code

Java

#### Screenshots

![2110](https://user-images.githubusercontent.com/25950952/213163510-1365d878-a2a0-4363-bb4c-72a80b4354c0.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as the reward for this feedback. 

If you have any other questions or feedbacks, please don't hesitate to let us know! 

We appreciate your support!
