### ISSUE TITLE
Missing Test Case - 1355. Activity Participants

### ISSUE THREAD

**Issue by richameher** [LeetCode-Feedback/LeetCode-Feedback#11120]
#### Your LeetCode username

BaileyBailey

#### Category of the bug
-  Missing Test Cases 

#### Description of the bug

The problem does not cover the test case when there are zero activities that have neither max nor min no of participants. In this case, leetcodes answer returns the activity with minimum no of participants. However, it should have returned no activities.

#### Code you used for Submit/Run operation

```
WITH TMP AS (
    select count(id) as no_of_participants , activity 
    from Friends
    group by activity
),

MAX_ACTIVITY AS (
    select max(no_of_participants) as no_of_participants
    from TMP
),

MIN_ACTIVITY AS (
    select min(no_of_participants) as no_of_participants
    from TMP
),

NO_OF_PARTCP AS (
    select * from MAX_ACTIVITY
    UNION
    select * from MIN_ACTIVITY
)
select activity from TMP 
where no_of_participants not in (SELECT * FROM NO_OF_PARTCP)
```

#### Language used for code

SQL

#### Expected behavior

Query should return no records.

#### Additional context

Consider the following example 

| id | name        | activity |
| -- | ----------- | -------- |
| 1  | Jonathan D. | Eating   |
| 2  | Jade W.     | Singing  |
| 3  | Victor J.   | Singing  |
| 4  | Elvis Q.    | Eating   |
| 5  | Daniel A.   | Eating   |
| 6  | Bob B.      | Eating   |

The answer should be as there are no activities that satisfy the questions critieria.

| activity |
| -------- |

But leetcodes expected answer is 

| activity |
| -------- |
| Singing  |

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

We ran the test case and the expected result was equal to:
{"headers": ["activity"], "values": []}
Can you please report the test case in the json format like this?
{"headers": {"Friends": ["id", "name", "activity"], "Activities": ["id", "name"]}, "rows": {"Friends": [[1, "Maria C.", "Singing"], [2, "Jade W.", "Eating"], [3, "Jonathan D.", "Eating"], [4, "Claire C.", "Singing"], [5, "Will W.", "Singing"], [6, "W", "Singing"]], "Activities": [[1, "Eating"], [2, "Singing"]]}}

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
