### ISSUE TITLE
Missing Test Case - 733. Flood Fill

### ISSUE THREAD

**Issue by brubakerjeff** [LeetCode-Feedback/LeetCode-Feedback#11121]
- [ x] Missing Test Cases 

#### Description of the bug
Hi,

I feel adding this case would be helpful for debugging as it tests routing in all directions.

[[1,1,1],[1,1,0],[1,1,1]]

Thanks,
Jeff

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link since we received Runtime Error when we submitted the above code.
https://leetcode.com/submissions/detail/884064172/

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

[[1,1,1],[1,1,0],[1,1,1]] showing invalid test case. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by brubakerjeff** [comment]
Thank you for the reply. The idea is to add a "Case 3" as
"[[1,1,1],[1,1,0],[1,1,1]]" to improve test coverage.
[image: case3.png]
The concern

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

Since the test case received an Invalid Test Case when we ran it, we cannot add it.

If you have any valid test cases to suggest, please don't hesitate to let us know! 

We appreciate your support!

**Comment by brubakerjeff** [comment]
Hi,

I see this was closed. I still believe adding the initial test case would improve the example. (Please note I added the word "test" to the initial question which I hope removes ambiguity) 

Thanks,
Jeff
