### ISSUE TITLE
Missing Test Case - 2539. Count the Number of Good Subsequences

### ISSUE THREAD

**Issue by nskybytskyi** [LeetCode-Feedback/LeetCode-Feedback#11125]
#### Your LeetCode username

[nskybytskyi](https://leetcode.com/nskybytskyi/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The below code for [2539. Count the Number of Good Subsequences](https://leetcode.com/problems/count-the-number-of-good-subsequences/) gets AC on the current test suit, but TLEs on the suggested test case.

#### Code you used for Submit/Run operation

[Submission link](https://leetcode.com/problems/count-the-number-of-good-subsequences/submissions/881119790/)

```python
class Solution:
    def countGoodSubsequences(self, s: str) -> int:

        ctr = Counter(s)
        n, ans = max(ctr.values()), 0

        for k in range(1,n + 1):

            if len(ctr) == 1: return ans + pow(2,n-k+1,1000000007)-1 # <-- 

            ans+= prod(map(lambda x: 1+comb(x,k),ctr.values()))-1

            for ch in ctr: 
                if not ctr[ch]: ctr.pop[ch]

        return ans%1000000007
```

#### Language used for code

Python3

#### Expected behavior

The above code should TLE on the following test case: `"ab" * 5_000`. I also recommend adding all of the following test cases:

```python
import string
import random

for k in range(2, 27):
  s = list(string.ascii_lowercase[:k]) * (10_000 // k)
  random.shuffle(s)
  print(''.join(s))
```

With shuffling added to prevent any pre-counter checks and early returns. You may want to go one step further and make frequencies vary too. The main point is to have some large but nontrivial (not len(s)) frequencies.

#### Additional context

The code is taken from [here](https://leetcode.com/problems/count-the-number-of-good-subsequences/solutions/3070551/python-3-8-lines-w-comments-t-m-7476-ms-14-0-mb/)

**Comment by nskybytskyi** [comment]
Update: [This person](https://leetcode.com/warrenruud/) repeatedly deletes and reposts solutions whenever I discover that there is something wrong with them and point it out in the comments. I think that this is not the kind of behavior that LC should support. Aside from invalidating links and making it annoying to reference them in this issue, it also spreads misinformation! Now, instead of one person (me) spending their time to find out that this solution is incorrect, more users will have to go through the same process of wasting time reading through an incorrect solution. It seriously pisses me off!

I have two different approaches to this issue in mind:
- Don't allow users to delete their posts. If there is anything wrong -- fix it in place. This way, the comments section will always be preserved.
- Automatically hide solution posts whenever a new test case that invalidates the solution is added. If a person wants to - they can update the post with the working code and un-hide the post. The idea here is to ensure that all published solutions are actually working, so that no confusion is spread.

Please let me know what you think about all of this.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
