### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by jonigrin** [LeetCode-Feedback/LeetCode-Feedback#11126]
#### Your LeetCode username

thejoni

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug

if you want to do an efficent algorithm in this problem irl you need to think about cases that some of the numbers you'l check before the wanted result are bigger than the target and you should skip the chedck on them but you have no testcase where there is number bigger than the target before the solution so if you add this it will makes the runtime slowern instead of faster

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution:
    def twoSum(self, nums: List[int], target: int) -> List[int]:
        for i in range(len(nums)):
            if nums[i] > target:
                continue
            need = target - nums[i]
            for j in range(i + 1, len(nums)):
                if nums[i] + nums[j] == target:
                    return [i, j]
```

#### Language used for code

python

#### Expected behavior

there should be a testcase for this

**Comment by KCaudron2** [comment]
Hi @jonigrin, thanks for sharing your feedback! I confirmed that we don't appear to have any missing test cases. If you still think there are missing test cases please share details as to the exact test case and the results you see when you run AND submit the code.
