### ISSUE TITLE
Missing Test case - 28. Implement strStr()

### ISSUE THREAD

**Issue by singhraushan** [LeetCode-Feedback/LeetCode-Feedback#1112]
#### Your LeetCode username
raushanjis

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Problem [](https://leetcode.com/problems/implement-strstr/) , has a missing test case. The code below was accepted but if tested with the following input test case it gives wrong answer.
input: haystack = "abc", needle = "c"

#### Code you used for Submit/Run operation

```
class Solution {
    public int strStr(String haystack, String needle) {
        int nLen = needle.length(), hLen = haystack.length();
        if (nLen == 0)
            return 0;
        else if (hLen < nLen || !haystack.contains(needle))
            return -1;

        int matchedIndex = 0;
        for (int i = 0; i < hLen; i++) {

            for (int j = 0; j < nLen; j++) {

                if (i+j < hLen && haystack.charAt(i + j) == needle.charAt(j)) {
                    if (j == nLen - 1)
                        return matchedIndex;
                    if (j == 0)
                        matchedIndex = i;
                } else
                    break;
            }
        }
        return -1;
    }
}

```

#### Language used for code
Java

#### Expected behavior
The solution should not be accepted since it fails on the test case
input: haystack = "abc", needle = "c"

#### Screenshots
![image](https://user-images.githubusercontent.com/31724633/94771732-8fc67f00-03d5-11eb-9f8c-fecc598edbbc.png)

#### Additional context
Wrong accepted solution link:-
[](https://leetcode.com/submissions/detail/402978639/)

**Comment by lc-ivan** [comment]
Hi @singhraushan 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @singhraushan ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
