### ISSUE TITLE
Missing Test Case - 36. Valid Sudoku

### ISSUE THREAD

**Issue by shubhamc1947** [LeetCode-Feedback/LeetCode-Feedback#11129]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

in this test case Expected output is **true** which is not possible as only possible digit on the left top corner is 9 and it already exist in the First column so it's expected output should be **False** 
[[".","8","7","6","5","4","3","2","1"],
["2",".",".",".",".",".",".",".","."],
["3",".",".",".",".",".",".",".","."],
["4",".",".",".",".",".",".",".","."],
["5",".",".",".",".",".",".",".","."],
["6",".",".",".",".",".",".",".","."],
["7",".",".",".",".",".",".",".","."],
["8",".",".",".",".",".",".",".","."],
["9",".",".",".",".",".",".",".","."]]

#### here is the code

```
```class Solution {
 ```
   public static boolean isSafe(char board[][], int row, int col, int degit) {
        // col check
        for (int i = 0; i <= 8; i++) {
            if (board[i][col] == (char) (degit + '0')) {
                return false;
            }
        }

        // row check
        for (int j = 0; j <= 8; j++) {
            if (board[row][j] == (char) (degit + '0')) {
                return false;
            }
        }

        // grid check
        int sr = (row / 3) * 3;
        int sc = (col / 3) * 3;
        for (int i = sr; i < sr + 3; i++) {
            for (int j = sc; j < sc + 3; j++) {
                if (board[i][j] == (char) (degit + '0')) {
                    return false;
                }
            }
        }
        return true;
    }

    public static boolean solveBoard(char[][] board, int row, int col) {
        // base case
        if (row == 9) {
            return true;
        }
        // updation part
        int nextRow = row;
        int nextCol = col + 1;
        if (col + 1 == 9) {
            nextRow = row + 1;
            nextCol = 0;
        }

        // check if empty

        if (board[row][col] != '.') {
            return solveBoard(board, nextRow, nextCol);
        }

        // loop
        for (int degit = 1; degit <= 9; degit++) {
            if (isSafe(board, row, col, degit)) {
                board[row][col] = (char) ('0' + degit);
                if (solveBoard(board, nextRow, nextCol)) {
                    return true;
                }
                board[row][col] = '.';
            }
        }

        return false;
    }
   
    public boolean isValidSudoku(char[][] board) {
        return solveBoard(board, 0, 0);
        
    }
}
```


#### java
<!-- C++ -->


#### am expected output should be **false** 
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->




<!-- If applicable, add screenshots to explain your issue. -->




<!-- Add any other additional context about the bug. -->

**Comment by stormsunshine** [comment]
Why can't you read the problem description carefully?

The problem description clearly mentions:

> A Sudoku board (partially filled) could be valid but is not necessarily solvable.

**Comment by KCaudron2** [comment]
Thank you for reaching out to us @shubhamc1947! The judger appears to be working correctly. Please feel free to refer to the discuss section of the problem to see how other users have optimized their code!

**Comment by shubhamc1947** [comment]
it was my mistake , I though at least it should be valid sudoku, oh sorry , it was a question of Valid Sudoku and am pretty much sure we can find out it is valid or not by not filling it but by just checking it is a valid sudoku or not , overall thank you for saying I can't read the question am pretty much sure a lot of student who are doing it by their own could not see it . Thank you for your time
