### ISSUE TITLE
VS Studio vs Leetcode compiler

### ISSUE THREAD

**Issue by Dl2kten** [LeetCode-Feedback/LeetCode-Feedback#11137]
#### Your LeetCode username

dl2020

#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I'm getting different returns in leetcode in comparison to vs studio.

#### Code you used for Submit/Run operation

```
// 3. Longest substring without repeating characters
class Solution {
public:
    int lengthOfLongestSubstring(std::string s) {

        std::unordered_map<char, int> letters;
        int ret = 0, count = 0;

        for (std::string::size_type i = 0; i != s.size(); ++i) {
            auto end = letters.find(s[i]);
            if (end == letters.end()) {
                letters[s[i]] = i;
                ++count;
            }
            else {
                ret = std::max(ret, count);
                count = i - letters[s[i]];
                letters.erase(letters.begin(), ++end);
                letters[s[i]] = i;
            }
        }

        return std::max(ret, count);
    }
};
```

#### Language used for code

C++

#### Expected behavior

For the test case "abcabcbb", and my own test case "pwwkepw", I'm getting different returns in VS Studio vs Leetcode compiler.
VS Studio: 3 and 4
Leetcode run: 5 and 6

#### Screenshots

![image](https://user-images.githubusercontent.com/22644604/213641151-a3612093-a248-494f-b700-6aeaac179d61.png)
![image](https://user-images.githubusercontent.com/22644604/213641231-4961ca7c-984e-424f-b729-013109c31e2e.png)

#### Additional context

I've had a previous issue with this and the reply was leetcode compiler was producing same results in run and submit.  That is
not my issue.  I've also read the page on technical questions.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

The judger appears to be working correctly, please feel free to refer to the discussion section of the problem to see how other users have optimized their codes!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output values.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!
