### ISSUE TITLE
Leetcode #692 Not evaluating actual solution

### ISSUE THREAD

**Issue by stevenddang** [LeetCode-Feedback/LeetCode-Feedback#1113]
#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language

#### Description of the bug

Test Case:
["aaa","aa","a"]
3

The engine isn't actually running the solution being submitted. I hardcoded a value to be returned and the output is completely different.

#### Code you used for Submit/Run operation

```
class Solution:
    def topKFrequent(self, words: List[str], k: int) -> List[str]:
        
        if len(words) == k:
            return words
        
        count = {}
        for word in words:
            count[word] = count.get(word, 0)+1

        # sorted() returns a list.
        # And sorted(d) is equivalent to sorted(d.keys()).
        ret = sorted(count, key=lambda word: (-count[word], word))
        
        # return ret[:k]
        
        return ['hi']
```

#### Language used for code

Python3

#### Expected behavior

For the engine to evaluate the solution being passed in.

#### Screenshots

<img width="1787" alt="Screen Shot 2020-10-01 at 1 36 55 AM" src="https://user-images.githubusercontent.com/8194005/94776256-01c3a780-0387-11eb-9ad2-1cfcec7b7bd8.png">

**Comment by lc-kay** [comment]
Hi @stevenddang 

It appears that there is a bug in your code so it's not returning his hardcoded value. For further explanation or support, please check out the official solution or solutions posted by other users in the discuss tab.
