### ISSUE TITLE
988. Smallest String Starting From Leaf - Incorrect answer in example

### ISSUE THREAD

**Issue by Sergio-Na** [LeetCode-Feedback/LeetCode-Feedback#11132]
#### Your LeetCode username

jojonas

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Example 2 says the answer is "adz" which has a value of 0 + 3 + 25 = 28,
but the correct answer is "bbz" which has a value of 1 + 1 + 25 = 27 so this example is incorrect. 

#### Code you used for Submit/Run operation

```
# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
class Solution:
    def smallestFromLeaf(self, root: Optional[TreeNode]) -> str:
        
        return self.DFS(root)[1]
    
    def DFS(self, node):
        if node is None:
            return 
        
        left = self.DFS(node.left)
        right = self.DFS(node.right)
        
        if not left and not right:
            return [node.val,chr(node.val + 97)]

        if left is not None and right is not None:
            if  left[0] >= right[0]:
                right[0] += node.val
                right[1] += chr(node.val + 97)
                return right
            else:
                left[0] += node.val
                left[1] += chr(node.val + 97)
                return left
        if left is None:
            right[0] += node.val
            right[1] += chr(node.val + 97)
            return right
        
        left[0] += node.val
        left[1] += chr(node.val + 97)
        return left

```

#### Language used for code

Python3

#### Expected behavior

The answer should be "ddz" as it is lexicographically smaller then "adz"

**Comment by KCaudron2** [comment]
Hi Sergio-Na,

Thank you for submitting your findings! 

I checked with our content team and they confirmed that "adz" is the correct answer for example 2. I'd suggest posting in the discussion section to dive deeper into why that's the case.

Warm regards,
Kelsey
