### ISSUE TITLE
Missing Test Case - 438. Find All Anagrams in a String

### ISSUE THREAD

**Issue by aswin2108** [LeetCode-Feedback/LeetCode-Feedback#11131]
#### Your LeetCode username
aswins2108

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
I submitted the below code, accidently I wrote ` if(cnt==0 && s.length()==0)v.push_back(0);` but here the `s.length()==1` should've been written. Still, all the test cases passed and got submitted. This means that the test case `s="a"` and `p=" a"` doesn't exist.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<int> findAnagrams(string s, string p) {
        map<char,int>mp;
        int k=p.length();
        for(int i=0;i<k;i++){
            mp[p[i]]++;
        }
        int i=0,j=0,cnt=mp.size();
        vector<int>v;
        mp[s[j]]--;
        if(mp[s[j]]==0)cnt--;
        if(cnt==0 && s.length()==0)v.push_back(0);
        
        while(j<s.length()-1){
            while(j-i+1<k){
                j++;
                mp[s[j]]--;
                if(mp[s[j]]==0)
                   cnt--;
            }
            if(j-i+1==k){
                if(cnt==0)
                  v.push_back(i);
                mp[s[i]]++;
                if(mp[s[i]]==1)cnt++;
                i++;      
            }
        }
        return v;
    }
};
```

#### Language used for code
C++

#### Expected behavior
As I described in the "description of the bug",

for the test case  `s="a"` and `p=" a"` the expected outcome was `[0]` but my output using the above code was `[]` still the above code got submitted. So this test case is missing from the test cases set.

#### Screenshots
![image](https://user-images.githubusercontent.com/72661784/213494771-2677110e-4003-47e2-ae11-d275918417ff.png)

**Comment by KCaudron2** [comment]
Hi @aswin2108, thank you for reporting this missing test case! I've shared these details with the team to investigate. I'll let you know once I hear back.

**Comment by KCaudron2** [comment]
Congrats @aswin2108, your missing test case was added by our content team. I have awarded you 100 LeetCoins for this submission. Thanks again for submitting this missing testcase and happy LeetCoding!
