### ISSUE TITLE
310. Bugged submission

### ISSUE THREAD

**Issue by ted-he** [LeetCode-Feedback/LeetCode-Feedback#11135]
#### Your LeetCode username

WubbyInferno

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

TLE with 71/71 test cases passed, and Last Executed Input having invalid and missing arguments.

#### Code you used for Submit/Run operation

```java
class Solution {
    public List<Integer> findMinHeightTrees(int n, int[][] edges) {
        int[] degrees = new int[n];

        // Calculate degree of each node
        for (int[] e : edges) {
            degrees[e[0]]++;
            degrees[e[1]]++;
        }

        Queue<Integer> leaves = new LinkedList<>();

        // Insert leaf nodes into queue
        for (int i = 0; i < degrees.length; i++)
            if (degrees[i] == 1)
                leaves.offer(i);

        // Runs until only one or two leaves (pointers) remain
        while (n-- > 2) {
            int size = leaves.size();
            n -= size;

            while (size-- > 0) {
                int curLeaf = leaves.poll();

                degrees[curLeaf] = 0;

                // Adds leaves if appropriate
                for (int[] e : edges) {
                    // Decrements degrees of next node and adds to queue if it is now a leaf
                    if (e[0] == curLeaf && --degrees[e[1]] == 1)
                        leaves.offer(e[1]);
                    if (e[1] == curLeaf && --degrees[e[0]] == 1)
                        leaves.offer(e[0]);
                }
            }
        }

        return new ArrayList<>(leaves);
    }
}
```

#### Language used for code

Java

#### Expected behavior

Accepted submission.

#### Screenshots

![image](https://user-images.githubusercontent.com/113558554/213621025-a77d3dd4-47f2-4356-949d-d538e978fd2b.png)

**Comment by KCaudron2** [comment]
Hi @ted-he, thank you for sharing this feedback with us! I took a look and am seeing a wrong answer result rather than TLE when I submit. Can you confirm if you're seeing the same?

**Comment by ted-he** [comment]
The issue no longer seems to be occurring, and I also see a wrong answer result. Thanks for your time!
