### ISSUE TITLE
Irrelevant output of similar type Test cases

### ISSUE THREAD

**Issue by HeetVekariya** [LeetCode-Feedback/LeetCode-Feedback#11147]
Dear sir,
I tried to solve Leetcode problem no. 8. String to Integer (atoi), but I am facing an issue. For test case no. 295 (" -0012a42") the expected output is -12, according to that logic the output for test case no. 993 ("00000-42a1234") should be -42 but it is asking for 0.

I request you to please take a look at it and reply as soon as possible.

Thank you.
![Screenshot (120)](https://user-images.githubusercontent.com/91054457/213835880-8438c68d-759d-46d9-87fa-16c0270afe29.png)
![Screenshot (121)](https://user-images.githubusercontent.com/91054457/213835894-ee057a8c-f265-4e88-8d9f-04913e1a4bbd.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discussion section of the problem to see how other users have optimized their codes!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output values.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!
