### ISSUE TITLE
Missing Test Case - 205. Isomorphic Strings

### ISSUE THREAD

**Issue by aleguarino** [LeetCode-Feedback/LeetCode-Feedback#11143]
#### Your LeetCode username
aleguarino

#### Category of the bug
- [ ] Question
- [ X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
With the code provided, the test case number 3 return the desired output in my local machine, but return the opposite in the website

#### Code you used for Submit/Run operation

```
// Isomorphic Strings
let charMap = new Map();

let isIsomorphic = (s, t) => {
    if (s.length != t.length) return false;

    for (let i = 0; i < s.length; i++) {
        if (charMap.has(s[i]) && charMap.get(s[i]) != t[i]) return false
        charMap.set(s[i], t[i]);
    }

    return true;
}

console.log(isIsomorphic("paper", "title"));
```

#### Language used for code
Javascript

#### Expected behavior

The test case number 3 should return "true", like it does in my local ide.

**Comment by KCaudron2** [comment]
Hi @aleguarino, thank you for sharing this feedback with us! I tested this myself and am seeing true returned for text case 3. Are you still seeing a false result with the above code?

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
