### ISSUE TITLE
Official Solution - Combination Sum II - incorrect explanation for number of parameters.

### ISSUE THREAD

**Issue by ArshiyanAlam** [LeetCode-Feedback/LeetCode-Feedback#11148]
#### Your LeetCode username
arsharsh

#### Category of the bug
- [ ] Question
- [✓] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

https://leetcode.com/problems/combination-sum-ii/solutions/980303/combination-sum-ii/
In official solution for Combination Sum II, it says in 2nd approach backtrack function requires lesser parameters. But actually number of backtrack function parameters are same in both approach. 

In fact for the Java solution provided in the official solution, 5 parameters are used for both approach. 

For Python solution 2nd approach have lesser parameter but it's not due to change in algorithm but due to Python language rule( nested functions can access variables from outer functions)

#### Expected behavior

Please rectify below point.
![image](https://user-images.githubusercontent.com/7927256/213845387-835d7466-f462-4e13-9a4d-a4da804cf78c.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as the reward for this feedback. 

If you have any other questions or feedbacks, please don't hesitate to let us know! 

We appreciate your support!
