### ISSUE TITLE
Missing Test Case - 167. Two Sum II - Input Array Is Sorted

### ISSUE THREAD

**Issue by fantasticxx** [LeetCode-Feedback/LeetCode-Feedback#11145]
#### Your LeetCode username

jyunhao

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

The code in this report should have failed, but it passed all test cases instead.
I found that it should have failed in this case
```
[-1000,-1,0,1,1000]
1000
```

#### Code you used for Submit/Run operation

``` c
int* twoSum(int* numbers, int numbersSize, int target, int* returnSize)
{
        int table[2002];
        memset(table, -1, sizeof(table));
        int *res = malloc(sizeof(int) * 2);
        *returnSize = 2;
        for (int i = 0; i < numbersSize; ++i) {
                if (table[numbers[i] + 1000] == -1) {
                        table[target - numbers[i] + 1000] = i;
                } else {
                        res[0] = table[numbers[i] + 1000] + 1;
                        res[1] = i + 1;
                        break;
                }
        }
        return res;
}
```

#### Language used for code

C

#### Expected behavior

The result should have been a Runtime Error, as shown in the screenshot below.

#### Screenshots

![螢幕快照 2023-01-21 上午6 45 01](https://user-images.githubusercontent.com/8417729/213823104-6475f75f-d07b-47c5-8d96-93a45a5fa1c4.png)

#### Additional context

https://leetcode.com/submissions/detail/882023748/

**Comment by KCaudron2** [comment]
Hi @fantasticxx, thank you for reporting this missing test case! I've shared these details with the team to investigate. I'll let you know once I heard back.

**Comment by KCaudron2** [comment]
@fantasticxx your submission was accepted by our content team! I have awarded you 100 LeetCoins for this submission. Thank you again for submitting this missing feedback. Happy LeetCoding!
