### ISSUE TITLE
Missing Test Case - 706. Design HashMap

### ISSUE THREAD

**Issue by UjjwalAggarwal-1** [LeetCode-Feedback/LeetCode-Feedback#11149]
#### Your LeetCode username

[f20212427](https://leetcode.com/f20212427/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
["MyHashMap","put","get","put","get","get","put","put","get","remove","get"]
[[],[1,1],[2],[202,2],[1],[33],[202,1],[101,4],[2],[2],[2]]

```

##### expected output
[null,null,-1,null,1,-1,null,null,-1,null,-1]

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by UjjwalAggarwal-1** [comment]
used python3

```
class MyHashMap:

    def __init__(self):
        self.hashmap = list()
        

    def put(self, key: int, value: int) -> None:
        
        hashmap = self.hashmap
        for i in range(len(hashmap),key+1):
            hashmap.append(-1)
        hashmap[key]=value


    def get(self, key: int) -> int:
        hashmap = self.hashmap
        try:
            return hashmap[key]
        except:
            return -1

    def remove(self, key: int) -> None:
        hashmap = self.hashmap
        hashmap[key]=-1

# Your MyHashMap object will be instantiated and called as such:
# obj = MyHashMap()
# obj.put(key,value)
# param_2 = obj.get(key)
# obj.remove(key)
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please refer to the discussion section of the problem to see how other users have optimized their codes or use our debugging function to debug the above solution.

If you have any questions or feedback, please let us know!
