### ISSUE TITLE
322 - Coin Change - Incorrect constraints on input limit

### ISSUE THREAD

**Issue by xeronix** [LeetCode-Feedback/LeetCode-Feedback#1114]
#### Your LeetCode username

xeronix

#### Category of the bug
- [x] Question

#### Description of the bug

322 - Coin Change. 
Constraints specify that **amount** parameter will be in range : 0 <= amount <= 2^31 - 1
But, it won't be possible to solve the problem if amount is 2^31-1 as best complexity to solve the problem is O(N*Amount).

#### Expected behavior

Value of **amount** parameter should be in range such that problem can be solved in O(N*Amount) complexity.

#### Screenshots

![Capture](https://user-images.githubusercontent.com/7497704/94805004-5445a800-0409-11eb-8ef2-2e0d59bf38bc.PNG)

**Comment by lc-kay** [comment]
Hi @xeronix 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @xeronix 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
