### ISSUE TITLE
probable typo in explanation of backtracking

### ISSUE THREAD

**Issue by b10s** [LeetCode-Feedback/LeetCode-Feedback#11153]
#### Your LeetCode username
b10s

#### Category of the bug
- [ ] Question

> As shown in the board below, if we place a queen at the row 1 and column 1 of the board, we then cross out all the cells that could be attached by this queen. 

Probably instead of `attached` need to be `attacked`  as problem definition states?

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem page link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by b10s** [comment]
@LC-Pam sorry, I forgot to attach link:

https://leetcode.com/explore/learn/card/recursion-ii/472/backtracking/2654/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
