### ISSUE TITLE
probable typo in D&C explanation, quick sort part

### ISSUE THREAD

**Issue by b10s** [LeetCode-Feedback/LeetCode-Feedback#11150]
#### Your LeetCode username
b10s

#### Category of the bug
- [ ] Question

#### Description of the bug
seems to be typo: instead of `empty list` seems `input list` is needed at the end of phrase:

> The base cases of the recursion in step [2] are either when the input list is empty or the empty list contains only a single element. 

https://leetcode.com/explore/featured/card/recursion-ii/470/divide-and-conquer/2870/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as the reward for this feedback. 

If you have any other questions or feedbacks, please don't hesitate to let us know! 

We appreciate your support!
