### ISSUE TITLE
136. Single Number Solution Issue

### ISSUE THREAD

**Issue by kondalraodurgam** [LeetCode-Feedback/LeetCode-Feedback#1115]
#### Your LeetCode username

[KondalDurgam](https://leetcode.com/kondaldurgam/)

#### Category of the bug
- [ ] Question
☑  Solution
- [ ] Language

#### Description of the bug
**Example 1**
If my input is [3,3,1,3,3,3] output is expected output is 2 . Accepted passed all test cases

#### Code you used for Submit/Run operation
``` 
var singleNumber = function(nums) {
    var total = 0;
    for (var i = 0; i <nums.length;i++) {
        var num = nums[i];
        total ^= num;
    }
    return total;
};

````

#### Description of the bug
**Example 2**
And same test case another solution. If input is [3,3,1,3,3,3] expected output should be 2.But my output is 1,If i click Run code button looks like below image wrong answer. If i click submit button  accepted passed all test cases  🤷‍♂️🤷‍♂️🤷‍♂️🤷‍♂️

#### Code you used for Submit/Run operation
``` 
var singleNumber = function(nums) {
    var map = new Map();
    for (var n of nums) {
        if (map.has(n)) {
            map.set(n,map.get(n)+1);
        }
        map.set(n,map.get(n) || 1);
    }
    for (var mapSet of map) {
        if (mapSet[1] === 1) {
            return mapSet[0];
        }
    }
};

````

#### Language used for code 
**JavaScript** 

#### Expected behavior
Expected output should be wrong answer but passed all test cases.

#### Screenshots
![bug1](https://user-images.githubusercontent.com/20201281/94893223-4abd4e00-04a4-11eb-8190-291567cff595.PNG)

If i click submit button accepted passed all test cases 🤷‍♂️🤷‍♂️🤷‍♂️🤷‍♂️

**Comment by lc-kay** [comment]
Hi @kondalraodurgam 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @kondalraodurgam 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
