### ISSUE TITLE
very minor: link to mobile version of wiki instead of normal one

### ISSUE THREAD

**Issue by b10s** [LeetCode-Feedback/LeetCode-Feedback#11151]
#### Your LeetCode username
b10s

#### Category of the bug
- [ ] Question

on the 
https://leetcode.com/explore/featured/card/recursion-ii/470/divide-and-conquer/2871/

link to 
https://en.m.wikipedia.org/wiki/Master_theorem_(analysis_of_algorithms)

probably better to provide link to desktop site

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have results.

Thank you for your support.
