### ISSUE TITLE
Missing Test Case - 2541. Minimum Operations to Make Array Equal II

### ISSUE THREAD

**Issue by Tathya-25** [LeetCode-Feedback/LeetCode-Feedback#11169]
#### Your LeetCode username
jaintathya74

#### Category of the bug

- Missing Test Cases 

#### Description of the bug
Wrong solutions are accepted.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    long long minOperations(vector<int>& nums1, vector<int>& nums2, int k) {
        
        long long ans=-1;
        long long var=0;
        long long cnt1=0;
        long long cnt2=0;
        
        for(int i=0;i<nums1.size();i++){
            if(nums1[i]>nums2[i]) cnt1+=nums1[i]-nums2[i];
            if(nums1[i]<nums2[i]) cnt2+=nums2[i]-nums1[i];
        }
        
        if(k==0){
            if(cnt1!=0 && cnt2!=0) return -1;
            return 0;
        }
        if(cnt1==cnt2 && cnt1%k==0) return cnt1/k;
        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior
For test case- nums1=[2,1,4,5] , nums2=[4,5,2,1] , k=3
Code which is giving output 2 is accepted for this test case whereas its correct output is -1.

#### Screenshots
![image](https://user-images.githubusercontent.com/82814076/213881918-53831f9b-c749-422c-a847-0803e513eddf.png)

####

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as the reward for this feedback. 

If you have any other questions or feedbacks, please don't hesitate to let us know! 

We appreciate your support!
