### ISSUE TITLE
Impossible restrictions - 39. Combination Sum

### ISSUE THREAD

**Issue by mihaild** [LeetCode-Feedback/LeetCode-Feedback#1116]
#### Your LeetCode username
mihaild

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Test `[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30]`
`500`
This test will have output with  27,600,453,321,731,384,162 variants, so no possible solution can pass it.

#### Code you used for Submit/Run operation
```python3
def get(candidates, target):
    if target < 0:
        return
    if target == 0:
        yield []
        return
    if len(candidates) == 0:
        return
    for n in get(candidates[1:], target):
        yield n
    for n in get(candidates, target - candidates[0]):
        yield [candidates[0]] + n

class Solution(object):
    def combinationSum(self, candidates, target):
        return list(get(candidates, target))
```
#### Language used for code
Python3

#### Expected behavior
The code I submitted (and any code for this problem) should fail as it fails a valid test case but it succeeds.

**Comment by lc-kay** [comment]
Hi @mihaild 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @mihaild 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
