### ISSUE TITLE
Missing Test Case - 160. Intersection of Two Linked Lists

### ISSUE THREAD

**Issue by praneeth16042003** [LeetCode-Feedback/LeetCode-Feedback#11164]
#### Your LeetCode username
white455

#### Category of the bug

- [] Solution

#### Description of the bug

the question intersection of two linked lists has a testcase of list1 = [4,1,8,4,5] and list2 = [5,6,1,8,4,5]
in which the intersection point is at node 1 but the answer given was 8

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
