### ISSUE TITLE
Missing Test Case - 2542. Maximum Subsequence Score

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#11165]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets WA on the following testcase:
[1, 6, 6, 8]
[3, 0, 7, 7]
1

#### Code you used for Submit/Run operation

```
class Solution:
    def maxScore(self, nums1: List[int], nums2: List[int], k: int) -> int: 
        p1 = []
        p2 = []
        n = len(nums1)
        for i in range(len(nums1)):
            p1.append((nums1[i],i))
        for i in range(len(nums2)):
            p2.append((nums2[i],i))
        p2.sort()
        p1.sort(reverse=True)
        vis = [0]*len(nums1)
        su = 0
        ans = 0
        for i in range(k):
            vis[p1[i][1]] = 1
            su+= p1[i][0]
        ed = k-1
        c = k
        for j in range(n):
            if j+k-1>=n:
                break
            c,i = p2[j]
            if vis[i]==1:
                ans = max(ans,su*c)
                su-= nums1[i]
                vis[i]= -1
                while ed<n and vis[p1[ed][1]]!=0:
                    ed+=1
                if ed<n:
                    su+= nums1[p1[ed][1]]
                    vis[p1[ed][1]] = 1
            else:
                ans = max(ans,(su+nums1[i]-nums1[ed])*c)
                vis[i] = -1
        return ans
```

#### Language used for code

Python3

#### Expected behavior

Output: 91
Expected: 56

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as the reward for this feedback. 

If you have any other questions or feedbacks, please don't hesitate to let us know! 

We appreciate your support!
