### ISSUE TITLE
Missing Test Case - 13. Roman to Integer

### ISSUE THREAD

**Issue by vito-a** [LeetCode-Feedback/LeetCode-Feedback#11162]
#### Your LeetCode username

vito_a

#### Category of the bug

- [ ] Missing Test Cases

#### Description of the bug

Two simplest test cases for IV and XIV that are widely used in the modern news and publications like Philip IV or Louis XIV that will help users to understand this Roman numbers problem better and quicker

#### Code you used for Submit/Run operation

```
class Solution {
    public int romanToInt(String s) {
        Map<String, Integer> numbersMap = new HashMap<String, Integer>() {{
            put("I", 1); put("V", 5); put("X", 10); put("L", 50); put("C", 100); put("D", 500); put("M", 1000);
        }};
        ArrayList<String> numbersList = new ArrayList<String>(Arrays.asList(s.split("")));
        Integer result = numbersMap.getOrDefault(numbersList.get(0), 0);
        for (int i = 1; i < numbersList.size(); i++) {
            int num = numbersMap.getOrDefault(numbersList.get(i), 0);
            int previousNum = i > 0 ? numbersMap.getOrDefault(numbersList.get(i-1), 0) : 0;
            result += (num <= previousNum) ? num : (num - (previousNum * 2));
        }
        return result;
    }
}
```

#### Language used for code

Java

#### Expected behavior

I expected to find after III these two simplest test cases for IV and XIV that are widely used in the modern news and publications like Philip IV or Louis XIV that will help users to understand this Roman numbers problem better and quicker - but  actually after III the LVIII and MCMXCIV go that are definitely not widely used nowadays

#### Screenshots

![Screenshot 2023-01-21 181234](https://user-images.githubusercontent.com/9512653/213878806-653fb877-e100-42a0-b265-20e062ffcf94.png)
![Screenshot 2023-01-21 181257](https://user-images.githubusercontent.com/9512653/213878835-aebde55a-37e8-4c3d-8852-2eab627e33df.png)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The test cases "XIV" and "IV" already exist.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
