### ISSUE TITLE
Missing Test Case - 8. String to Integer (atoi)

### ISSUE THREAD

**Issue by shilpeegupta14** [LeetCode-Feedback/LeetCode-Feedback#11160]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases ✅

#### Code you used for Submit/Run operation

```
// ATOI
int myAtoi(string str) {
        int size=str.size();
        if(size==0)return 0;

        int idx=0;
        int sign=1;
        bool valid=false;
        double ans=0;
        //discards all whitespaces
        while(idx<size and str[idx]==' '){
            idx++;
        }
        //updates sign at + encounter
        if (idx<size and str[idx]=='+'){
            sign=1;
            idx++;
        }
        //updates sign at - encounter
        else if(idx<size and str[idx]=='-'){
            sign=-1;
            idx++;
        }
        //appends all the integer values from the input
        while(idx<size and str[idx]>='0' and str[idx]<='9'){
            valid=true;
            ans = ans * 10 + str[idx]-'0';
            if(ans * sign > INT_MAX)return INT_MAX;
            else if(ans * sign < INT_MIN)return INT_MIN;
            idx++;
        }
        //string that contains only + and - or space isnt a valid string to be converted into integer. 
        if(valid){
            return static_cast<int>(sign*ans);
        }
        return 0;
}
```

#### Expected behavior

Need to support edge cases like 
i)--123
ii) 429-+-98 which should give output as 42998. Rather the above approach gives the output as 429 and omits the characters after the operator signs. 

#### Screenshots

<img width="878" alt="Screenshot 2023-01-21 at 10 31 30 PM" src="https://user-images.githubusercontent.com/78029920/213878187-14cc38ac-2960-4ceb-927b-7155f9ea49a2.png">
<img width="884" alt="Screenshot 2023-01-21 at 10 52 32 PM" src="https://user-images.githubusercontent.com/78029920/213879222-295f54d6-a644-4352-a00c-9e2ad692597f.png">

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
