### ISSUE TITLE
Leetcode 1498 Submission issue

### ISSUE THREAD

**Issue by Mdyasir25** [LeetCode-Feedback/LeetCode-Feedback#11168]
#### Your LeetCode username

mdyasir25

#### Category of the bug
- [ ] Question
-  Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

One of the test case fails during submission but passes during dry run.
The test case is **[14,4,6,6,20,8,5,6,8,12,6,10,14,9,17,16,9,7,14,11,14,15,13,11,10,18,13,17,17,14,17,7,9,5,10,13,8,5,18,20,7,5,5,15,19,14]**

#### Code you used for Submit/Run operation

```
// Number of Subsequences That Satisfy the Given Sum Condition
public class Solution {
    public int NumSubseq(int[] nums, int target) {
        int res = 0;
        int mod = (int)(1e9+7);
        Array.Sort(nums);
        //Create arrays of 2^i for 0<=i<=nums.Length
        int[] powerOf2 = new int[nums.Length];
        powerOf2[0] = 1;
        for(int n=1; n<nums.Length; n++) {
            powerOf2[n] = (powerOf2[n-1]<<1)%mod;
        }
        int i = 0;
        int j = nums.Length-1;
        while(i<=j) {
            while(i<=j && nums[i]+nums[j]>target) j--;
            int len = j-i;
            if(len<0) break;
            int addend = powerOf2[len]%mod;
            res+=addend;
            i++;
        }
        return res;
    }
}
```

#### Language used for code

C#

#### Expected behavior

The test case no. 19 should have passed during submission since it passes during dry run.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
