### ISSUE TITLE
Missing Test Case - 941. Valid Mountain Array

### ISSUE THREAD

**Issue by step-aside-peasant** [LeetCode-Feedback/LeetCode-Feedback#11167]
#### Your LeetCode username
step-aside-peasant

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ + ] Missing Test Cases 

#### Description of the bug
The tests contradict the conditions

#### Code you used for Submit/Run operation
```
var validMountainArray = function(arr) {
    let desc = false
    if (arr.length <= 3) return false
    
    for (let i=0; i<arr.length; i++) {
        if (arr[i] === arr[i+1]) return false
        
        if (arr[0] > arr[1]) return false
        
        
        if (arr[i] > arr[i+1]) {
            desc = true
        }
        
        if (arr[i] < arr[i+1] && desc) return false
        
    }
    return (desc && true)
};
```

#### Language used for code
Javascript

#### Expected behavior
In the conditions of the problem it is written that "arr.length >= 3"
but the tests do not match and contradict the conditions
If we remove the equal sign, the tests will pass.
Conclusion: It is necessary to remove the equal sign from the problem description or change the expected outcome of the test.

#### Screenshots
![screenshot](https://user-images.githubusercontent.com/90152813/213881310-027056eb-0f36-42fd-bd60-8dd2bc06dc99.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
