### ISSUE TITLE
Missing Test Case - 2543. Check if Point Is Reachable

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#11176]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets WA on the following testcase:
817996085
540885561

#### Code you used for Submit/Run operation

```
class Solution:
    def isReachable(self, targetX: int, targetY: int) -> bool:
        cnt_x, cnt_y = Counter(), Counter()
        
        for _ in range(100):
            while targetX % 2 == 0:
                targetX //= 2
            while targetY % 2 == 0:
                targetY //= 2
            
            # (x, y - x) 或者是 (x - y, y)
            # print(targetX, targetY)
            
            if targetX == 1 or targetY == 1:
                return True
            
            if _ % 2 == 0:
                targetY += targetX
            else:
                targetX += targetY
    
        return False        
```

#### Language used for code

Python3

#### Expected behavior

Output: false
Expected: true

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as the reward for this feedback. 

If you have any other questions or feedbacks, please don't hesitate to let us know! 

We appreciate your support!
