### ISSUE TITLE
Missing Test Case - 2540. Minimum Common Value

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#11177]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets Runtime Error on the following testcase:
[34, 225, 328, 530, 823, 834, 902, 989]
[24, 30, 115, 121, 160, 173, 239, 265, 335, 362, 449, 557, 597, 624, 697, 766, 775, 881, 898, 919]

#### Code you used for Submit/Run operation

```
class Solution:
    def getCommon(self, nums1: List[int], nums2: List[int]) -> int:
        n,m = len(nums1),len(nums2)
        for x in nums1 :
            i = bisect_left(nums2,x)
            if nums2[i] == x:
                return x
        return -1
```

#### Language used for code

Python3

#### Expected behavior

The code gets Runtime Error.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as the reward for this feedback. 

If you have any other questions or feedbacks, please don't hesitate to let us know! 

We appreciate your support!
