### ISSUE TITLE
Missing Test Case - 93. Restore IP Addresses

### ISSUE THREAD

**Issue by DavidGMdev** [LeetCode-Feedback/LeetCode-Feedback#11189]
#### Your LeetCode username 
DavidGeorgeM

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Simply any solution that makes aggressive brute force [ generate first then check if valid ranges ] 
to generate all possible dot position , and then check .
<br>
if make use of stoi() or stoll() [ string to int / long long ] in c++ , without any check on the size of 
the provided string , worst case will get to 20 char that exceeds what long long can hold so , this 
gives if tested the stoll() function throws excpetion and gives runtime error verdict , but this not tested here and the solution got AC verdict.

Testcases example :  "99999999999999999999" or any like input 
that does not fit all in a long long on using c++ stoll() [ worst case , on doing aggressive Brute force ] 

------------------------------------------------------------------
Thank you.
Happy coding all.
David George Monir.

 

#### Code you used for Submit/Run operation

```

class Solution {
public:
    vector<string> possible ;
    bool check( int p1 , int p2 , int p3 , string & x ){
        string tot = "" , spare = "" ; 
        int n = x.size() , m = 4 ;
        int st[] = {  0 , p1 , p2 , p3 } ; 
        int en[] = {  min(n,p1) , min(n,p2) , min(n,p3) , n } ;
        for ( int i = 0 ; i < m ; i++ ) {
            for( int j = st[i] ; j < en[i] ; j++ ) spare += x[j];
            if ( !(spare != ""  && stoll(spare) < 256 && to_string(stoll(spare)).size() == spare.size() )  ) return false ;
            tot += spare + ( i == m-1 ?  "" : "." ) ;
            spare = "";
        }
        possible.push_back(tot);
        return true ; 
    }
    vector<string> restoreIpAddresses(string s) {
        int n = s.size();
        for ( int i = 1 ; i < n + 3 ; i++ ){
            for ( int j = i+1 ; j < n + 3 ; j++ ){
                for( int l = j+1 ; l < n + 3 ; l++ ) {
                    check(i,j,l,s);
                }
            }
        }
        return possible ;
    }
};

```

#### Expected behavior

on input "99999999999999999999" or any large samples , 
the solution provided  and any similar solutions that make use of c++ stoll() ,
long long  must have Runtime error verdict while this solution easily pass the 
testcases and got AC verdict , and that's it .

Exactly this part " stoll(spare) < 256 " in the if condition  this on large input without pre-check
throws exceptions that gives runtime 
 
Expected : Runtime Error verdict 
Happens : AC verdict

**Comment by KCaudron2** [comment]
Hi @DavidGMdev, thank you for reporting this missing test case! I've shared these details with the team to investigate. I'll let you know once I hear back.

**Comment by KCaudron2** [comment]
Congrats @DavidGMdev, our content team added the missing test case you submitted! I have awarded you 100 LeetCoins for this accepted submission. Thanks again for flagging this missing test case for us; happy LeetCoding!
