### ISSUE TITLE
Incomplete Question & Judge - 836. Rectangle Overlap

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1118]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language

#### Description of the bug

836. Rectangle Overlap
https://leetcode.com/problems/rectangle-overlap/

1.

Problem states below:
> " Given two (axis-aligned) rectangles, return whether they overlap."

- What is "axis-aligned"?
- Is it the same as sides of the rectangle are parallel to X & Y axis?
- This needs to be defined or linked to an article where it is defined.

2.

Problem states below:
> "(x1, y1) are the coordinates of its bottom-left corner, and (x2, y2) are the coordinates of its top-right corner."

- However, the judge does not throw any error below 3 cases - it gives "false" as the result.

	[ rec1   rec2  ]

	[ x1 y1  x2 y2 ]

	[ 0  1   1  0  ]
	[ 0  1   1  0  ]

	[ 1  0   0  1  ]
	[ 1  0   0  1  ]

	[ 1  1   0  0  ]
	[ 1  1   0  0  ]

I have a solution ready, but I am not submitting until the above are clear.

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

1. No one knows all. The problem must define things clearly.
2. Judge must assert input, and throw an invalid input error, if the input is invalid - instead of giving true/false.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
