### ISSUE TITLE
 Incorrect Test case  #28 in 409. Longest Palindrome

### ISSUE THREAD

**Issue by sokol8** [LeetCode-Feedback/LeetCode-Feedback#11198]
#### Your LeetCode username
sokol8

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [X] Incorrect Test case 

#### Description of the bug

Test Case is incorrect. Palindrome in the string is 'cccc' (4 chars) not 'abccccdd'

Input
s =
"abccccdd"
Output
4
Expected
7

#### Language used for code
Swift

#### Expected behavior

I expected string ''abccccdd'' to have the longest palindrome 'cccc' of the length 4

**Comment by stormsunshine** [comment]
The problem requires to return the length of the longest palindrome that **can be built with those letters**.

Please read the problem description carefully.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The problem requires returning the length of the longest palindrome that can be built with those letters.

Please read the problem description carefully.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
