### ISSUE TITLE
Missing Related Topics for Question - 492. Construct the Rectangle

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1119]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

492. Construct the Rectangle
https://leetcode.com/problems/construct-the-rectangle/

This question is not having any "Related Topics".

Please add "Math" as Topic to this question, so it
- can be seen in "Related Topics" to the question
- and, can be found when filtered with "Tags" = "Math" under "Topics" in the problemset page at https://leetcode.com/problemset/algorithms/?difficulty=Easy&topicSlugs=math

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior
- Question must have "Related Topics"
- problemset page's "Tags" filter must show - all - questions under one of the Topics given is selected

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy ,
Thank you for your feedback. Upon review, our team has updated the problem but we will not be rewarding LeetCoins for this case.
