### ISSUE TITLE
49. Group Anagrams

### ISSUE THREAD

**Issue by tyOjasvi** [LeetCode-Feedback/LeetCode-Feedback#112]
**What kind of the bug**
Correct answer fails testcase
- [49.] Group Anagrams
- [ ] https://leetcode.com/playground/uAmmYtfq/live
- [ ] JAVA (English)

**Describe the bug**
The question says any order is allowed, but still my code does not pass. All the elements are the same, just the order differs from the excepted output. My answer also forms the same elements, just the order is different, which is permissible by the question.
**what language is your code written in**
JAVA

**The code you submit/run**
```
// Two Sum
class Solution {
   public List<List<String>> groupAnagrams(String[] strs) {
		List<List<String>> ans = new ArrayList<>();
		ans.add(new ArrayList<>());
		ans.get(0).add(strs[0]);
		for (int i = 1; i < strs.length; i++) {
			boolean found = false;
			for (List<String> ele : ans) {
				String str = ele.get(0);
				if (IsAnagram(str, strs[i])) {
					found = true;
					ele.add(strs[i]);
				}
			}
			if (!found) {
				ans.add(new ArrayList<>());
				ans.get(ans.size() - 1).add(strs[i]);
			}
		}
		return ans;
	}

	public boolean IsAnagram(String str, String ss) {
        if(str.length() != ss.length()) return false;
        
		HashMap<Character, Integer> map = new HashMap<>();
		getMap(str, map);

		for (int i = 0; i < ss.length(); i++) {
			char ch = ss.charAt(i);
			if (!map.containsKey(ch) || (map.containsKey(ch) && map.get(ch) == 0))
				return false;
			else
				map.put(ch, map.get(ch) - 1);
		}
		return true;
	}

	public void getMap(String str, HashMap<Character, Integer> map) {
		for (int i = 0; i < str.length(); i++) {
			char ch = str.charAt(i);
			map.put(ch, map.getOrDefault(map.get(ch), 0) + 1);
		}
	}
}
```

**Expected behavior**
My code gives the correct answer, just the order is different, it should also pass all the test cases, but fails.

**Screenshots**

**Additional context**
It fails this test case:
{ "hos", "boo", "nay", "deb", "wow", "bop", "bob", "brr", "hey", "rye", "eve", "elf", "pup", "bum", "iva", "lyx", "yap", "ugh", "hem", "rod", "aha", "nam", "gap", "yea", "doc", "pen", "job", "dis", "max", "oho", "jed", "lye", "ram", "pup", "qua", "ugh", "mir", "nap", "deb", "hog", "let", "gym", "bye", "lon", "aft", "eel", "sol", "jab" }

**Comment by CooperCooperCooper** [comment]
Hi @tyOjasvi,

Thank you for reaching out to us! I've filed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @tyOjasvi,
Thank you for your time. We've taken a thorough look at this issue and found it to be invalid. Since there are two appearances of 'pup', it should return ['pup','pup'] instead of ['pup'],['pup'].
