### ISSUE TITLE
Racist Joke On LeetCode Platform

### ISSUE THREAD

**Issue by ThomasShaw1** [LeetCode-Feedback/LeetCode-Feedback#11205]
How can racist comments like this(https://leetcode.com/discuss/general-discussion/3082010/Some-People-Hardcoding-all-Testcases-in-Biweekly-contest-96/1768494) be left on LeetCode?

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to delete the comment. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
