### ISSUE TITLE
Problem 291 testcase

### ISSUE THREAD

**Issue by ZuyuLiao** [LeetCode-Feedback/LeetCode-Feedback#1120]
#### Category of the bug
- [ 1] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

for case like pattern "aaaa" and str "abcdabcd" shoudn't we return true? since aa/aa and abcd/abcd

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
Hi @ZuyuLiao 

To further investigate your issue, are you trying to contribute a test case?

**Comment by ZuyuLiao** [comment]
Yeah, but I am not sure the correct anwser for my test case because it is ambiguous in the problem description.
Right now for case like pattern "aaaa" and str "abcdabcd" it returns false, but I think it should return right.

**Comment by lc-kay** [comment]
Hi @ZuyuLiao, 

What is your reasoning for that input to return "true"?

**Comment by ZuyuLiao** [comment]
Because aa/aa = abcd/abcd, it didn't mention in problem description that the pattern shoud itself not be divided into another pattern.

**Comment by lc-kay** [comment]
Hi @ZuyuLiao 

The test case is correct and valid. However, our team has added some explanations to the first 3 test cases and updated the statement. I hope this clarifies any confusion that you may have had!
