### ISSUE TITLE
Missing Test Case - 958. Check Completeness of a Binary Tree

### ISSUE THREAD

**Issue by Elopteryx** [LeetCode-Feedback/LeetCode-Feedback#11206]
#### Your LeetCode username

forgacs

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My code solution was able to pass all the tests, even though it was missing a check for the difference between the maximum tree depth and the current depth. After a successful submit, I tried running this custom test case and my code didn't pass it, as you can see on the screenshot.

```
[1,2,3,4,5,6,7,8,9,null,null,null,null,null,null,10,11,12,13]
```

I had to add this extra check

```
if (maxDepth - depth > 1) {
    return false;
}
```
and with that, my code passed this extra test case as well.

#### Code you used for Submit/Run operation

```
class Solution {

    public boolean isCompleteTree(TreeNode root) {
        var leafDepths = new ArrayList<Integer>();
        if (!hasValidChildren(root, 0, leafDepths)) {
            return false;
        }
        var maxDepth = 0;
        for (var leafDepth : leafDepths) {
            maxDepth = Math.max(maxDepth, leafDepth);
        }
        var hadMissing = false;
        for (var leafDepth : leafDepths) {
            if (hadMissing && leafDepth != maxDepth - 1) {
                return false;
            }
            if (leafDepth < 0) {
                hadMissing = true;
            }
        }
        var hadDiff = false;
        for (var i = 1; i < leafDepths.size(); i++) {
            var depth = leafDepths.get(i);
            if (hadDiff && depth < 0) {
                return false;
            }
            depth = Math.abs(leafDepths.get(i));
            var prevDepth = Math.abs(leafDepths.get(i - 1));
            if (depth != prevDepth) {
                if (hadDiff) {
                    return false;
                }
                if (depth > prevDepth) {
                    return false;
                }
                hadDiff = true;
            }
        }
        return true;
    }

    private boolean hasValidChildren(TreeNode node, int depth, List<Integer> leafDepths) {
        if (node == null) {
            leafDepths.add(-1 * depth);
            return true;
        }
        var left = node.left;
        var right = node.right;
        if (left == null && right == null) {
            leafDepths.add(depth);
            return true;
        }
        if (left == null && right != null) {
            return false;
        }
        return hasValidChildren(left, depth + 1, leafDepths) && hasValidChildren(right, depth + 1, leafDepths);
    }
}
```

#### Language used for code

Java

#### Expected behavior

In my opinion, a similar test case should be added to check for this kind of input.

#### Screenshots

<img width="891" alt="screenshot" src="https://user-images.githubusercontent.com/3444128/213933776-994dbb99-e4dc-46b1-93b8-9d45457d57f9.png">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as the reward for this feedback. 

If you have any other questions or feedbacks, please don't hesitate to let us know! 

We appreciate your support!
