### ISSUE TITLE
Missing Test Case - 599. Minimum Index Sum of Two Lists

### ISSUE THREAD

**Issue by rheinz96** [LeetCode-Feedback/LeetCode-Feedback#11215]
#### Username
rheinz96

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
All tests assume that there is at least one common element in both lists. However, regarding the problem description and constraints, there may not be a common element in both lists. Example:

```
list1 = ["Shogun","KFC"]
list2 = ["Piatti","Hungry Hunter Steakhouse"]
```

#### Expected behavior
A test should be added where there is no common element in both lists.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by rheinz96** [comment]
Please check this Python code. It will pass all test cases.

```python
def findRestaurant(self, list1: List[str], list2: List[str]) -> List[str]:
    data = {list1[i]: i for i in range(len(list1))}
    min_idx = len(list1)+len(list2)
    min_val = []
    for j in range(len(list2)):
        d = list2[j]
        i = data.get(d,min_idx)
        if min_idx > j+i:
            min_val = [d]
            min_idx = j+i
        elif min_idx == j+i:
            min_val.append(d)
    return min_val
```

If there is no common element in both lists, an element will still be returned:
```
Input: list1=["Shogun","KFC"], list2=["Piatti","Hungry Hunter Steakhouse"]
Output: ["Piatti"]
Expected: []
```

If we assume that there is at least one common element in both lists, the current test cases are valid. However, in my opinion, the description does not mention that there must always be a common element. If there is no common element in both lists, the above test case is missing.

Please let me know if you need further information!

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The Code submission AC link.

The code received Runtime Error due to:
NameError: name 'Solution' is not defined
    ret = Solution().findRestaurant(param_1, param_2)
Line 37 in _driver (Solution.py)
    _driver()
Line 48 in <module> (Solution.py)
https://leetcode.com/submissions/detail/885184940/


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by rheinz96** [comment]
Thans for dealing with this problem. You forgot to use the class definition. Please try the following code:


```python
class Solution:
    def findRestaurant(self, list1: List[str], list2: List[str]) -> List[str]:
        data = {list1[i]: i for i in range(len(list1))}
        min_idx = len(list1)+len(list2)
        min_val = []
        for j in range(len(list2)):
            d = list2[j]
            i = data.get(d,min_idx)
            if min_idx > j+i:
                min_val = [d]
                min_idx = j+i
            elif min_idx == j+i:
                min_val.append(d)
        return min_val
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
