### ISSUE TITLE
Missing Test Case - 1236. Web Crawler

### ISSUE THREAD

**Issue by Congee** [LeetCode-Feedback/LeetCode-Feedback#11210]
#### Your LeetCode username

@Congee

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

This question is unclear about a trailing slash.

#### Code you used for Submit/Run operation
```cpp
class Solution {
 public:
  vector<string> crawl(string startUrl, HtmlParser parser) {
    // parse hostname
    // store urls crawled into a hashset
    // recursively crawl
    // trailing slash???
    //
    // in real world, use stacks for different domains, queues for each domain

    std::string valid_hostname = hostname_of(startUrl);
    std::vector<std::string> stack({startUrl});
    std::unordered_set<std::string> seen({startUrl});

    while (stack.size()) {
      auto&& urls = parser.getUrls(stack.back());
      stack.pop_back();
      for (auto&& url : urls) {
        if (hostname_of(url) != valid_hostname) continue;
        if (seen.count(url)) continue;

        stack.push_back(url);
        seen.insert(url);
      }
    }

    return std::vector<string>(seen.begin(), seen.end());
  }

  inline std::string hostname_of(const std::string& url) const {
    return url.substr(7, url.find_first_of('/', 7) - 7);
  }
};
```

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior

["http://news.yahoo.com","http://news.yahoo.com/"] should be treated as the same url.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
