### ISSUE TITLE
Missing Test Case - 2345. Finding the Number of Visible Mountains

### ISSUE THREAD

**Issue by romilpunetha** [LeetCode-Feedback/LeetCode-Feedback#11211]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:

    int visibleMountains(vector<vector<int>>& peaks) {
       vector<vector<int>> interval;
       sort(peaks.begin(), peaks.end());
       for(int i = 0; i < peaks.size(); i++) {
            interval.push_back({peaks[i][0] - peaks[i][1], peaks[i][0] + peaks[i][1]});
       } 
        sort(interval.begin(), interval.end(), []( const vector<int> &a,  const vector<int> &b) {
            if(a[0] == b[0]) return a[1] > b[1];
            return a[0] < b[0];
        });

        int start = INT_MIN, end = INT_MIN, res = 0; 
        for(int i = 0; i < interval.size(); i++) {
            if(interval[i][0] == start) {
                if(interval[i][1] > end) {
                    start = interval[i][0], end = interval[i][1];
                    res += 1;
                } else if (interval[i][1] == end) {
                    res--;
                    res = max(res, 0);
                }
            } else {
                if(interval[i][1] > end) {
                    res++;
                    start = interval[i][0], end = interval[i][1];
                }
            }
        }
        return res;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The test case `[[2,2],[5,2],[8,4], [8,4], [8,4], [8,4],[8,4]]` was supposed to fail. If there are several points at the same place then they should be ignored. The way ignoring should work is that such points should not be included in the answer. However in my code that is accepted, I'm reducing the result value, because of which it results in 0 instead of 2, ie, the reduction part is reducing all my previously found peaks as well.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have results.

Thank you for your support.
