### ISSUE TITLE
Missing Test Case - 997. Find the Town Judge

### ISSUE THREAD

**Issue by GirirajSinghRathore** [LeetCode-Feedback/LeetCode-Feedback#11218]
#### Your LeetCode username

giriraj97

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

there is one test case that is missing
Test case is - 
n=3
trust = [[1,2],[1,2]]
Leetcode problem number - 997 
Epected output is -1 but my code is giving 2 as output and code is accepted

#### Code you used for Submit/Run operation

```
class Solution {
    public int findJudge(int n, int[][] trust) {
        if(n==1){
            return 1;
        }
        // int ans = trust[0][1];
        int[] trst = new int[n+1];
        boolean[] trusts = new boolean[n+1];
        for(int i=0;i<trust.length;i++){
            trst[trust[i][1]]++;
            trusts[trust[i][0]]=true;
        }
        for(int i=0;i<trst.length;i++){
            if(trst[i]==(n-1)&&!trusts[i]){
                return i;
            }
        }
        return -1;
        // return ans;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Missing test case,my code should fail but is passed

**Comment by congliu0704** [comment]
Due to problem constraints: "All the pairs of trust are unique."
test case n=3 trust = [[1,2],[1,2]] is invalid: expected variables trust[0]:[1, 2] and trust[1]:[1, 2] to have different values

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The test case received an Invalid test case when we ran it.
expected variables trust[0]:[1, 2] and trust[1]:[1, 2] to have different values

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
