### ISSUE TITLE
954. Array of Doubled Pairs - TestCases

### ISSUE THREAD

**Issue by Vikas-Jethwani** [LeetCode-Feedback/LeetCode-Feedback#1121]
#### Your LeetCode username

stan_vj

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Missing/Weak Testcases.

#### Code you used for Submit/Run operation
```
class Solution {
public:
    bool canReorderDoubled(vector<int>& A) {
        map<int, int> m;
        for(int x: A) m[abs(x)]++;
        for(auto &p: m) { // start with smallest number
            int x = p.first; 
            if(m[x]) {
                if(m[2*x] < m[x]) return false;
                m[2*x] -= m[x];
            }
        }
        return true;
    }
};
```

#### Language used for code

C++

#### Expected behavior

This code returns Wrong for the below testcase, yet it gets an AC on submission.
Input: [-1,2]

#### Screenshots

![image](https://user-images.githubusercontent.com/30088376/94965958-0f5d6680-051a-11eb-9979-8b3263d10993.png)

#### Additional context

I had a question. Is there any way to apply to become a moderator at LeetCode?

**Comment by lc-kay** [comment]
Hi @Vikas-Jethwani 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
In regards to moderator openings, we have noted your username and will reach out in the future if it's a good fit.

**Comment by lc-kay** [comment]
Hi @Vikas-Jethwani 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
