### ISSUE TITLE
Solution - 997. Find the Town Judge

### ISSUE THREAD

**Issue by RohitSgh** [LeetCode-Feedback/LeetCode-Feedback#11228]
#### Your LeetCode username

RohitSgh

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Minute mistake in comprehending `indegree` given in [Official Solution](https://leetcode.com/problems/find-the-town-judge/solutions/522247/find-the-town-judge/)

#### Expected behavior

> **Expected :**  Likewise, we say that the **indegree** of a vertex (person) is the number of directed edges going _into_ it. So here, it represents the number of people _trusting_ that person.

> **Happened :** Likewise, we say that the **indegree** of a vertex (person) is the number of directed edges going _into_ it. So here, it represents the number of people _trusted by_ that person.

#### Screenshots

> ![Official Solution](https://user-images.githubusercontent.com/81853910/214139345-c52e1621-f970-4c7d-aeef-89cb21ec52c6.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as the reward for this feedback. 

If you have any other questions or feedbacks, please don't hesitate to let us know! 

We appreciate your support!
