### ISSUE TITLE
Solution Formatting is not Correct

### ISSUE THREAD

**Issue by shafikshaon** [LeetCode-Feedback/LeetCode-Feedback#11227]
#### Your LeetCode username
shafikshaon

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In this link https://leetcode.com/problems/binary-tree-preorder-traversal/solutions/2918429/official-solution/
The markdown **```**  not inputed correctly.

![Algorithm 3](https://i.imgur.com/CePUfSo.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as the reward for this feedback. 

If you have any other questions or feedbacks, please don't hesitate to let us know! 

We appreciate your support!
