### ISSUE TITLE
Missing Test Case - 231. Power of Two

### ISSUE THREAD

**Issue by harshal8869** [LeetCode-Feedback/LeetCode-Feedback#11222]
#### Category of the bug
- [x] 231.Power of Two
- [x] class Solution {
public:
    bool isPowerOfTwo(int n) {
     
      while(n%2==0)
      n = n / 2;
      if(n==1)
      return true;
      else
      return false;
        
    }
};
- [x] C++
- [x] n == 0

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.
