### ISSUE TITLE
Missing Test Case - 1361. Validate Binary Tree Nodes

### ISSUE THREAD

**Issue by rahulrg1** [LeetCode-Feedback/LeetCode-Feedback#11225]
#### Your LeetCode username

rahulrg1

#### Category of the bug
- [x] Question
1361.
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 
Test Case- 
n=2
leftChild= [-1,0]
rightChild=[ -1,-1]

#### Description of the bug

the above mentioned Test Case is required as in the question it is not mentioned
that this condition is guaranteed or not but all the test cases are working and ignored this checking.  
#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by rahulrg1** [comment]
I think now this issue is resolved by someone else. So, no need to consider it further. But Thank you for your response.
