### ISSUE TITLE
Ambiguous problem description - 997 Find the Town Judge

### ISSUE THREAD

**Issue by congliu0704** [LeetCode-Feedback/LeetCode-Feedback#11221]
#### Your LeetCode username

leetcode.cn/u/congliu0704

#### Category of the bug
- [x] Question

#### Description of the bug
[997 Find the Town Judge](https://leetcode.cn/problems/find-the-town-judge)
Original problem description:
```
In a town, there are n people labeled from 1 to n. There is a rumor that one of these people is secretly the town judge.

If the town judge exists, then:

The town judge trusts nobody.
Everybody (except for the town judge) trusts the town judge.
There is exactly one person that satisfies properties 1 and 2.
You are given an array trust where trust[i] = [ai, bi] representing that the person labeled ai trusts the person labeled bi.

Return the label of the town judge if the town judge exists and can be identified, or return -1 otherwise.
```

* Bug 1
The original problem description does not guarantee the answer of this test case:
n = 1, trust = []   (where the current expected answer is 1)
Reasoning: The judge is optional, the condition gives two possible results: (1) 1st people is judge or (2) 1st people is not judge.

* Bug 2
The trust array definition needs to be clarified.
Presumably, if a trust relationship does not appear in the trust array, then this relationship may or may not exist. For example, when n = 3, trust = [[1,2],[2,3]] (where the current expected answer is -1), then 1st people may or may not trust 3rd people.

#### Expected behavior
Suggested modified problem description and test cases:

```
In a town, there are n people labeled from 1 to n. There is a rumor that one of these people is secretly the town judge.

If the town judge exists, then:

1) The town judge trusts nobody.
2) Everybody (except for the town judge) trusts the town judge.
3) There is exactly one person that satisfies 1) and 2).

You are given an array trust where trust[i] = [ai, bi] representing that the person labeled ai trusts the person labeled bi.

If a trust relationship does not appear in the trust array, then this relationship may or may not exist.

For example, when n = 3, trust = [[1,2],[2,3]], then 1st people may or may not trust 3rd people.

Return the label of the town judge if the town judge exists and can be identified, or return -1 otherwise.

Example 1:
    Input: n = 3, trust = [[1,2],[2,3]]
    Output: -1
    Explanation: 3rd people may not be judge since [1,3].

Example 2
    Input: n = 1, trust = []
    Output: -1
    Explanation: 1st people may not be judge. If 1st people is not judge, the given conditions hold as well.
```

#### Code you used for Submit/Run operation

A sample Swift solution submitted and passed all the current test cases.

```swift
// https://leetcode.cn/submissions/detail/396817022/
class Solution {
    /// # cases:
    ///  1.1) one judge and can be identified
    ///       e.g. n = 3, trust = [[1,3],[2,3]] --> judge = 3
    ///  1.2) one judge and cannot be identified
    ///       e.g. n = 3, trust = [[1,2],[2,3]] --> judge = -1
    ///       because trust relationship [1,3] is not given
    ///  2  ) definitely no judge
    ///       e.g. n = 3, trust = [[1,3],[2,3],[3,1]] --> judge = -1
    func findJudge(_ n: Int, _ trust: [[Int]]) -> Int {
        // edge case 1:
        // n = 1 trust = [] --> judge = 1
        if n == 1 && trust.isEmpty {
            return 1
        }
        // necessary condition for a judge candidate:
        // not appearing as any a_i
        let setn = Set(1...n)
        let nonJudges: Set<Int> = Set( trust.map { $0[0] } )
        let candidates: Set<Int> = setn.subtracting(nonJudges)
        let nt = trust.count
        var t = [Int: Set<Int>]() // key: trust receiver, value: set of trust givers of this trust receiver 
        for i in 0..<nt {
            let tr = trust[i][1] // trust receiver
            let tg = trust[i][0] // trust giver
            if t[tr] == nil {
                t[tr] = [tg]
            } else {
                t[tr]?.insert(tg)
            }
        }

        if candidates.isEmpty {
            return -1
        } else {
            for candidate in candidates {
                if t[candidate]?.count == n - 1 {
                    return candidate
                }
            }
            return -1
        }
    }
}
```

#### Language used for code
Swift

**Comment by congliu0704** [comment]
> For Bug 1, the person labeled 1 is the judge according to the rules. There is no reason to say that the person labeled 1 is not the judge, since there is no other person that does not trust the person labeled 1.
> 
> For Bug 2, only the trust relationships that exist in trust array are considered. If a trust relationship does not exist in trust array, then such a trust relationship does not exist. If such a relationship may or may not exist, then for many test cases, the answer is not unique. What is the expected answer?
> 
> In fact, you are trying to change the logic of this problem. There are already many solutions of this problem, and changing the logic of the problem is impossible.

Hi stormsunshine,

Thank you for replying.

Based on your comments, I suggest that the problem description should include this statement (from your reply) explicitly to minimize ambiguity: "If a trust relationship does not exist in trust array, then such a trust relationship does not exist." 

Otherwise, the problem may imply a case that is "there exist one judge but cannot be identified".

Best regards,
George

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as the reward for this feedback. 

If you have any other questions or feedbacks, please don't hesitate to let us know! 

We appreciate your support!
