### ISSUE TITLE
953. Verifying an Alien Dictionary

### ISSUE THREAD

**Issue by Vikas-Jethwani** [LeetCode-Feedback/LeetCode-Feedback#1122]
#### Your LeetCode username

stan_vj

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Code fails TestCase, still gets Accepted.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool isAlienSorted(vector<string>& words, string order)
    {
        vector<int> val(26, 0);
        for (int i=0; i<order.length(); i++)
            val[order[i]-'a'] = i;
        
        for (int i=0; i<words.size(); i++)
        {
            for (int j=i+1; j<words.size(); j++)
            {
                int k=0;
                while (true)
                {
                    if (k == words[j].length())
                        return false;
                    if (k == words[i].length())
                        break;
                    
                    if (words[i][k] == words[j][k])
                    {
                        k++;
                        continue;
                    }
                    
                    if (val[words[i][k]-'a'] > val[words[j][k]-'a'])
                        return false;
                    else
                        break;
                }
            }
        }
        return true;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Input:
["hello","hello"]
"abcdefghijklmnopqrstuvwxyz"

Either this testcase should be added. Or question should clearly mention that there are no duplicate words.
Currently either the question is ambiguous or testcases are weak.

#### Screenshots

![image](https://user-images.githubusercontent.com/30088376/94969741-e7253600-0520-11eb-81cd-aedfc9000db9.png)

**Comment by lc-kay** [comment]
Hi @Vikas-Jethwani 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Vikas-Jethwani 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
