### ISSUE TITLE
Update the rustc version

### ISSUE THREAD

**Issue by TomasHubelbauer** [LeetCode-Feedback/LeetCode-Feedback#11236]
#### Category of the bug
- [x] Language

#### Description of the bug
The Rust compiler version seems to be old and it doesn't provide helpful diagnostics the new version provides.

#### Code you used for Submit/Run operation
```rust
impl Solution {
    pub fn running_sum(nums: Vec<i32>) -> Vec<i32> {
        mut let sum = 0;
        mut let sums = Vec::new();
        for num in nums {
            sum += num;
            sums.push(sum);
        }

        return sums;
    }
}
```

#### Language used for code
Rust

#### Expected behavior
I want to see this compiler output as per the Rust Playground:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=e6b6dcb75d62802a1b05821228775482

```
   Compiling playground v0.0.1 (/playground)
error: invalid variable declaration
 --> src/lib.rs:2:5
  |
2 |     mut let sum = 0;
  |     ^^^^^^^ help: switch the order of `mut` and `let`: `let mut`

error: invalid variable declaration
 --> src/lib.rs:3:5
  |
3 |     mut let sums = Vec::new();
  |     ^^^^^^^ help: switch the order of `mut` and `let`: `let mut`

error: could not compile `playground` due to 2 previous errors
```

#### Screenshots
The LeetCode output uses a worse diagnostic without the helpful hint to swap the two keywords. I think this is because LeetCode uses an older `rustc` version where this diagnostic hasn't been improved yet:

```
Line 3, Char 9: expected expression, found keyword `mut` (solution.rs)
  |
3 |         mut let sum = 0;
  |         ^^^ expected expression
error: could not compile `prog` due to previous error
mv: cannot stat '/leetcode/rust_compile/target/release/prog': No such file or directory
```

<img width="832" alt="image" src="https://user-images.githubusercontent.com/6831144/214249719-751d13f7-2f4a-4a78-a130-93e3a1398926.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem page link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by TomasHubelbauer** [comment]
https://leetcode.com/problems/running-sum-of-1d-array (with Rust selected as the language of choice)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have results.

Thank you for your support.

**Comment by VivekYadav7272** [comment]
Recent Rust releases have had a lot of quality-of-life improvements, like let-else clause, default import of FromIter, and improved panic formatting. It feels painful writing code adhering to the old version..

**Comment by xamgore** [comment]
I double that. As Rust compiler is backward compatible, it should not be a problem to upgrade to the latest version.

**Comment by SymphonySimper** [comment]
bump

**Comment by hwittenborn** [comment]
I think the 2021 version of Rust should automatically be being used as well, which isn't currently the case:

```rust
Line 17, Char 20: no method named `try_into` found for type `usize` in the current scope (solution.rs)
    |
17  |         nums.len().try_into().unwrap()
    |                    ^^^^^^^^ method not found in `usize`
    |
    = help: items from traits can only be used if the trait is in scope
    = note: 'std::convert::TryInto' is included in the prelude starting in Edition 2021
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
23  | use std::convert::TryInto;
    |
For more information about this error, try `rustc --explain E0599`.
error: could not compile `prog` due to previous error
```

Most developers who use Rust also use `cargo` which automatically uses the 2021 edition of Rust. I think it'd make sense to do such on LeetCode as well.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've used your feedback to check the problem.

We redirected it to our developers team and we’ll investigate upgrading Rust.

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!

**Comment by bcc32** [comment]
Hi, it looks like the Rust version has been upgraded to 1.74.1, thanks!  Could the Edition of Rust (configured in Cargo.toml) be updated to 2021 as well?  (see this [comment](https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/11236#issuecomment-1817736450))
