### ISSUE TITLE
难度标定不一致

### ISSUE THREAD

**Issue by Ijustwantyouhappy** [LeetCode-Feedback/LeetCode-Feedback#1123]
** Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
- [剑指 Offer 43. 1～n整数中1出现的次数](https://leetcode-cn.com/problems/1nzheng-shu-zhong-1chu-xian-de-ci-shu-lcof/) medium
- [233. 数字 1 的个数](https://leetcode-cn.com/problems/number-of-digit-one/) hard

这两道题目为同一题目，但难度标定的不一致，望修正。

**Comment by feiceh** [comment]
感谢反馈，题目难度均已调整至 hard。

**Comment by Ijustwantyouhappy** [comment]
id: a_run

**Comment by feiceh** [comment]
ID：a_run 给予积分奖励，请查收。
