### ISSUE TITLE
Missing Test Case - 205. Isomorphic Strings

### ISSUE THREAD

**Issue by iamRishvanth** [LeetCode-Feedback/LeetCode-Feedback#11239]
#### Your LeetCode username

iamRishvanth

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

given test cases are not enough to verify whether the solution is correct or not. because I wrote a solution for this Isomorphic String problem and it passed all the existing test cases but I know my solution was not fully correct. so I put a test case manually and then run my solution, this time my solution didn't pass my manual test cases.
so I request you add a test case that is similar to my manual test case

#### Code you used for Submit/Run operation

```
class Solution:
    def isIsomorphic(self, s1: str, s2: str) -> bool:
        #s1 = input()
        #s2 = input()
        n1 = []
        n2 = []
        count = 0
        for i in s1:
            for j in s1:
                if i == j:
                    count+=1
            n1.append(count)
            count = 0
        for i in s2:
            for j in s2:
                if i == j:
                    count += 1
            n2.append(count)
            count = 0
        if n1 == n2:
            return True
        else:
            return False
```

#### Language used for code

Python3

#### Expected behavior

mentioned in description of bug section

#### Screenshots

![Bug Screenshot](https://user-images.githubusercontent.com/83532062/214330869-2e37cea7-aac6-4732-9fe4-aa9f6ccb680e.png)

**Comment by iamRishvanth** [comment]
Insufficient Test Cases to Validate the solution

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users have optimized their codes!

The above code received Wrong Answer when we submitted it.

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output values.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!
