### ISSUE TITLE
In question No.2 of Biweekly contest 92 many people have submitted wrong code during contest and the code got accepted.

### ISSUE THREAD

**Issue by Aman913k** [LeetCode-Feedback/LeetCode-Feedback#11232]
#### Your LeetCode username

aman91k

#### Category of the bug
- [x] Solution
- [x] Missing Test Cases 

#### Description of the bug

In question No.2 of Biweekly contest 92 many people have submitted wrong code but the code got accepted.

Ex.
for Testcase:
[5,3,1,4]
[1,3,7,2]
3

The answer should be -1 but their wrong codes giving answer as 2 and it also got accepted.
Actually the code should give error when the difference array say, (nums2[i]-nums1[i]) %k!=0 for all 0<=i<n.
many people submitted wrong code without checking this condition ant it got accepted also.

#### Code you used for Submit/Run operation

// Minimum Operations to Make Array Equal II
'''

class Solution 
{
public:
    long long minOperations(vector<int>& nums1, vector<int>& nums2, int k) 
    {
        if(k==0) 
        {
            if(nums1==nums2) return 0; 
            return -1;
        }
        
 
        long long p_diff=0, n_diff=0; 
        
        for(int i=0; i<nums1.size(); i++)
        {
            if(nums1[i] >= nums2[i]) p_diff += nums1[i]-nums2[i];
            else n_diff += nums2[i]-nums1[i];
        }
        
        long long ans=-1;
        if((p_diff-n_diff==0) && (p_diff%k)==0)
        {
             ans = (p_diff/k);
        }
        return ans;
        
    }
};

'''

#### Language used for code

C++

#### Expected behavior

The code doesn't check the condition (nums2[i]-nums1[i]) %k!=0   during the contest and wrong codes submitted by others got accepted.

#### Screenshots

![Screenshot (80)](https://user-images.githubusercontent.com/95915282/214206987-dd38bc86-e750-4c94-b820-a6a26ad350cc.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Aman913k** [comment]
> 

https://leetcode.com/submissions/detail/882562751/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us! 

Under contest [rules](https://leetcode.com/discuss/general-discussion/951105/new-contest-rule-effective-from-december-2020) you will find: 

Weak test cases
Weak test cases that cause some incorrect submissions to be judged as "Accepted".
In such a scenario, Leetcode will add test cases and rejudge all the "Accepted"
submission.
If the correct submissions were judged as “Wrong Answer”, and incorrect submissions were judged as “Accepted” during the contest for any reason, LeetCode will rejudge all the submissions that were made during this contest for the problem. 

If the rejudge is executed, LeetCode will rejudge all the submissions that were submitted to the problem by users who were impacted during the contest. The first Accepted submission will be taken as the final result, and the "Wrong Answer/Time Limited Exceeded" submissions made prior to the first "Accepted" submissions will be counted for penalty time.

The rejudge for the problem applies to all submissions.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
