### ISSUE TITLE
No Python 3 Template for BFS Section

### ISSUE THREAD

**Issue by hohenhau** [LeetCode-Feedback/LeetCode-Feedback#11243]
Only Java template provided here:
https://leetcode.com/explore/learn/card/queue-stack/231/practical-application-queue/1372/

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've submitted your feedback to the content team. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
