### ISSUE TITLE
Missing Test Case - 1632. Rank Transform of a Matrix

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#11244]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets Runtime Error on the following testcase:
[[34, 94, 45, 12, 99, 49], [8, 81, 75, 66, 93, 36], [6, 51, 51, 6, 13, 70]]

#### Code you used for Submit/Run operation

```
class Solution:
    def matrixRankTransform(self, matrix: List[List[int]]) -> List[List[int]]:
        m, n = len(matrix), len(matrix[0])
        parent = {i : i for i in range(m + 500)}
        def find(node):
            path = []
            while node != parent[node]:
                path.append(node)
                node = parent[node]
            for p in path:
                parent[p] = node 
            return node 
        def union(n1, n2):
            p1 = find(n1)
            p2 = find(n2)
            if p1 != p2:
                parent[p1] = p2 
        ranks = [[0 for _ in range(n)] for _ in range(m)]
        rows = [0] * m 
        cols = [0] * n 
        groups = collections.defaultdict(list)
        for i in range(m):
            for j in range(n):
                groups[matrix[i][j]].append((i, j))
        pool = collections.defaultdict(list)
        for val in sorted(groups.keys()):
            pool.clear()
            for i, j in groups[val]:
                union(i, j + 500)
            for i, j in groups[val]:
                pool[find(i)].append((i, j))
            for key in pool:
                r = max(max(rows[i], cols[j]) for i, j in pool[key])
                for i, j in pool[key]:
                    ranks[i][j] = r + 1 
                    rows[i] = r + 1 
                    cols[j] = r + 1 
            parent = {i : i for i in range(m + 500)}
        return ranks 
```

#### Language used for code

Python3

#### Expected behavior

The code gets Runtime Error.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as the reward for this feedback. 

If you have any other questions or feedbacks, please don't hesitate to let us know! 

We appreciate your support!
