### ISSUE TITLE
Missing Test Case - 909. Snakes and Ladders

### ISSUE THREAD

**Issue by Adrianpush** [LeetCode-Feedback/LeetCode-Feedback#11247]
#### Your LeetCode username

totalrecall1988

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x] Missing Test Cases 

#### Description of the bug

Problem states that boards that cannot be completed (impossible to reach final square) exist and in that case -1 should be returned.  Such cases imply that you get stuck in a loop of all possible destinations from a set of starting points will eventually lead back to the same exact starting points. Yet the current battery of tests checks only if current destinations lead to current starting point. I want to add another test that runs a couple of times before leading back to the starting point. 

#### Code you used for Submit/Run operation

This code solves the problem with all  tests in current battery of tests and fails the test mentioned below.
```
class Solution:
    def snakesAndLadders(self, board: List[List[int]]) -> int:
        
        left_to_right = True
        full_arr = [0]

        for i in range(1, len(board)+1):
            if left_to_right:
                full_arr += board[-i]
                left_to_right = False
            else:
                board[-i].reverse()
                full_arr += board[-i]
                left_to_right = True

        for i in range(len(full_arr)):
            if full_arr[i] == -1:
                full_arr[i] = i


        def start_to_finnish(move, start_set, all_arr):

            destinations = set()
            move += 1

            for start_point in start_set:
                destinations.update(all_arr[start_point+1:start_point+7])            

            if destinations == start_set:
                return -1

            if all_arr[-1] in destinations:
                return move

            else:
                move = start_to_finnish(move, destinations, all_arr)
            
            return move
        
        return start_to_finnish(0, {1}, full_arr)
```

#### Language used for code

Python

#### Expected behavior

Add this test case:
```
[[-1,-1,-1,-1,-1,-1],[-1,-1,-1,-1,-1,-1],[-1,-1,-1,-1,-1,-1],[1,1,1,-1,13,-1],[1,1,1,1,1,8],[-1,8,8,8,8,8]]
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as the reward for this feedback. 

If you have any other questions or feedbacks, please don't hesitate to let us know! 

We appreciate your support!
