### ISSUE TITLE
Typo - 909. Snakes and Ladders

### ISSUE THREAD

**Issue by congliu0704** [LeetCode-Feedback/LeetCode-Feedback#11248]
#### Your LeetCode username
leetcode.cn/u/congliu0704

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In Constraints section, an undefined `grid` is used instead of `board`:
> grid[i][j] is either -1 or in the range [1, n^2].

#### Expected behavior
Replace grid with board:
> board[i][j] is either -1 or in the range [1, n^2].

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as the reward for this feedback. 

If you have any other questions or feedbacks, please don't hesitate to let us know! 

We appreciate your support!
