### ISSUE TITLE
Typo in solution - 2359. Find Closest Node to Given Two Nodes

### ISSUE THREAD

**Issue by smokfyz** [LeetCode-Feedback/LeetCode-Feedback#11257]
#### Your LeetCode username

smokfyz

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In [solution](https://leetcode.com/problems/find-closest-node-to-given-two-nodes/solutions/2864716/find-closest-node-to-given-two-nodes/?orderBy=most_votes) in section "Approach 1: Breadth First Search".

> In the worst case, the queue can grow to a size linear with **n**.

#### Expected behavior

> Since each node can only have at most one outgoing edge, on each step a queue will contain at most one node, which takes **O(1)** space for storing a queue.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as the reward for this feedback. 

If you have any other questions or feedbacks, please don't hesitate to let us know! 

We appreciate your support!
