### ISSUE TITLE
Confusing Question Constraints - 669. Trim a Binary Search Tree

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1125]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

669. Trim a Binary Search Tree
https://leetcode.com/problems/trim-a-binary-search-tree/

The question Description talks about `[low, high]`
The question Constraints talks about `l` & `r` as in `0 <= l <= r <= 104`

- Are they both the same? if so, please fix the same. Else describe what `l` & `r` are.

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

- Introduce what is `l` & `r` before using them in constraints - Save the user time, hence increase the user delight on the first read.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
