### ISSUE TITLE
Find Closest Node to Given Two Nodes

### ISSUE THREAD

**Issue by Vinay9897** [LeetCode-Feedback/LeetCode-Feedback#11261]
Approach 1 
Line Number 40  --- > minDistNode = i;

I found the solution of this error 

Solution:

In place of i It should be "currNode"

minDistNode = currNode

**Comment by ASahu16** [comment]
Duplicate issue https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/11260

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've updated the problem. 

This issue was raised earlier in https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/11251

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
