### ISSUE TITLE
Ambiguous Question - 669. Trim a Binary Search Tree

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1126]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

669. Trim a Binary Search Tree
https://leetcode.com/problems/trim-a-binary-search-tree/

The question description states as below:

> You might need to change the root of the tree,
> so the result should
> return the new root of the
> trimmed binary search tree.

is it that only we need to return "root of the trimmed binary search tree"?
OR
is it we need to return "root of the trimmed binary search tree, which should also be binary search tree"?

In other words, can you please clearly state if:
- the result must be the root of a trimmed binary search tree
OR
- the result must be the root of a trimmed binary search tree - which need not be "binary search tree"
  - can it be a binary tree?
  - can it be a tree? (not a binary tree) )
  - can it be a graph :)

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

- "root of the trimmed binary search tree" does not give any details about  if "trimmed binary search tree" is a "binary search tree" a "binary tree" or "tree" or other

- The constraints clearly state about the input tree "root is guaranteed to be a valid binary search tree", but the question description does not clearly state expectations about the exact result.

- The question expectations must be clear in the description, should not leave the user to infer from examples, etc.

- Ambiguous questions strain the user to read multiple times. Users lose a lot of time in raising these GitHub issues.  User delight in solving a problem goes from 100 to 0, as they skip each question due to ambiguity.

**Comment by manoharreddyporeddy** [comment]
Could not continue on this.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
