### ISSUE TITLE
Missing Test Case - 724. Find Pivot Index

### ISSUE THREAD

**Issue by pankaj11koundal** [LeetCode-Feedback/LeetCode-Feedback#11269]
#### Your LeetCode username
pankaj11koundal

#### Category of the bug
- [ 1] Missing Test Cases 

#### Description of the bug
Leedcode's given solution is not working for the following testcase: nums = [2,3,-1,8,4]. 

#### Code you used for Submit/Run operation

```
class Solution {
    public int pivotIndex(int[] nums) {
        int n = nums.length, sum = 0;
        for (int i = 0; i < n; i++) 
            sum += nums[i];

        int leftSum = 0, rightSum = sum - nums[0];
        
        if (leftSum == rightSum) return 0;
        for (int i = 1; i < n; i++) {
            leftSum += nums[i - 1];
            rightSum = sum - nums[i] - leftSum;
            if (leftSum == rightSum) return i;
        }

        return -1;
    }
}
```

#### Language used for code
Java

#### Expected behavior
Input: nums =  [2,3,-1,8,4] 
Expected Result: 3
Actual Result after running the code: -1   

#### Screenshots
![Missing Test Case - 724  Find Pivot Index · Issue #11269 · LeetCode-Feedback_LeetCode-Feedback - Google Chrome 1_26_2023 12_49_37 AM](https://user-images.githubusercontent.com/68144477/214665536-1048ec93-a799-4ca0-bf3f-0d8ab5096fc1.png)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The judger appears to be working correctly, please check the attachment as below.

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output values.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!

We appreciate your support!
![Screen Shot 2023-01-25 at 3 52 10 PM](https://user-images.githubusercontent.com/103138242/214688064-7a3dd441-43b0-4a84-a2f0-0b9ab9f9d29a.png)
