### ISSUE TITLE
probably missed part in solution for Find Closest Node to Given Two Nodes

### ISSUE THREAD

**Issue by b10s** [LeetCode-Feedback/LeetCode-Feedback#11266]
#### Your LeetCode username
b10s

#### Category of the bug
- [ ] Solution

It says:
> Otherwise, if minDistTillNow <= max(dist1[currNode], dist2[currNode]) we do not do anything

But in case if `minDistTillNow` equals to `max(dist1[currNode], dist2[currNode])` we still need to check node id to choose node with min node id according to our task.

https://leetcode.com/problems/find-closest-node-to-given-two-nodes/solutions/2864716/find-closest-node-to-given-two-nodes/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

This issue was reported by the other user earlier.

 We've relayed this issue to our team to investigate. 

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've updated the problem. 

This issue was raised earlier in https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/11251

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
