### ISSUE TITLE
Find Closest Node to Given Two Nodes - typo in solution

### ISSUE THREAD

**Issue by wasteCleaner** [LeetCode-Feedback/LeetCode-Feedback#11263]
#### Your LeetCode username
podpole

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
https://leetcode.com/problems/find-closest-node-to-given-two-nodes/solutions/2864716/find-closest-node-to-given-two-nodes/
Solution #1.
Language: JAVA
Line: 44
Change: `minDistNode = i;` => `minDistNode = currNode;`
Since variable with name `i` is not defined in the solution at all.

#### Code you used for Submit/Run operation
Not applicable

#### Language used for code
Java

#### Expected behavior
Not applicable

#### Screenshots
<img width="617" alt="image" src="https://user-images.githubusercontent.com/19432543/214602475-d6120b68-e3d7-44a6-bb78-dd367bfe5a97.png">

#### Additional context
Nothing to add

**Comment by ASahu16** [comment]
Duplicate issue https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/11260

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've updated the problem. 

This issue was raised earlier in https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/11251

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
