### ISSUE TITLE
Solution - 2359. Find Closest Node to Given Two Nodes. Code cannot compile.

### ISSUE THREAD

**Issue by flowingwings** [LeetCode-Feedback/LeetCode-Feedback#11271]
#### Your LeetCode username
flowingwings

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the official [solution](https://leetcode.com/problems/find-closest-node-to-given-two-nodes/solutions/2864716/find-closest-node-to-given-two-nodes/), approach 1, line 40 of the Java version implementation: 
```
minDistNode = i;
```
The variable `i` is not defined, and the code cannot compile. See the screenshot.

#### Code you used for Submit/Run operation
As described above.

#### Language used for code
Java

#### Screenshots
![image](https://user-images.githubusercontent.com/38078537/214677369-b6502c11-2a57-45e0-811e-f1abff951033.png)

**Comment by LC-Pam** [comment]
Thank you for your time.

We've updated the problem.

This issue was raised earlier in https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/11251

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!
