### ISSUE TITLE
Typo in solution - 787. Cheapest Flights Within K Stops

### ISSUE THREAD

**Issue by smokfyz** [LeetCode-Feedback/LeetCode-Feedback#11283]
#### Your LeetCode username

smokfyz

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In [solution](https://leetcode.com/problems/cheapest-flights-within-k-stops/solutions/2825208/cheapest-flights-within-k-stops/) in section "Approach 2: Bellman Ford".

Problems with markdown
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/17355662/214853689-d4dcbeb4-bec5-49ae-9fa6-8bf30708852c.png">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as the reward for this feedback. 

If you have any other questions or feedbacks, please don't hesitate to let us know! 

We appreciate your support!

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
