### ISSUE TITLE
LeetCode 2280 - The TestCase #80 is Wrong

### ISSUE THREAD

**Issue by kabragaurav** [LeetCode-Feedback/LeetCode-Feedback#11285]
#### Category of the bug
- [ ] Solution

#### Description of the bug
The testcase #80, stockPrices: `[[1,1],[500000000,499999999],[1000000000,999999998]]` should  have answer as 1. But due to floating point precision issue from LeetCode side, it expects answer as 2. 
You can use an online graph visualization tool and you will see only 1 line is needed to connect all the above 3 points. So, instead of 2, correct and expected answer should be 1.

#### Code you used for Submit/Run operation

```
public int minimumLines(int[][] points) {
      Arrays.sort(points, (p1, p2) -> p1[0]-p2[0]);

      int N = points.length;
      int lines = 0;
      double prevM = Double.NEGATIVE_INFINITY;

      for (int i=1; i<N; i++) {
          double m = getSlope(points[i-1], points[i]);
          if (prevM == m)
              continue;
          lines++;
          prevM = m;
      }

      return lines;
  }

  private double getSlope(int[] p1, int[] p2) {
      if (p2[0] == p1[0])
          return Double.POSITIVE_INFINITY;
      return 1.0 * (p2[1]-p1[1])/(p2[0]-p1[0]);
  }
```

#### Expected behavior

For testcase #80, instead of 2, correct and expected answer should be 1.

#### Screenshots

![image](https://user-images.githubusercontent.com/53303368/214862794-15195115-e3d5-49cc-ba93-861813d5a2dd.png)

#### Additional context

Floating point precision issue from LeetCode side.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. The above code received Compile Error when we submitted it. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by stormsunshine** [comment]
This test case you provide in this issue should have output 2. The slopes are 499999998/499999999 and 999999997/999999999 and they are different, so you can't use only one line to represent the line chart.

The following test case has output 1, as expected.

```
[[1,1],[500000000,499999999],[999999999,999999997]]
```

**Comment by kabragaurav** [comment]
I see that both are equivalent to 0.999999998. @stormsunshine

**Comment by kabragaurav** [comment]
> 
Submission link:
https://leetcode.com/problems/minimum-lines-to-represent-a-line-chart/submissions/885687668/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly. The submission code received Wrong Answer. 

Please feel free to refer to the discussion section of the problem to see how other users have optimized their codes!
