### ISSUE TITLE
Missing Test Case - 472. Concatenated Words

### ISSUE THREAD

**Issue by ravibajpai001** [LeetCode-Feedback/LeetCode-Feedback#11298]
#### Your LeetCode username
ravi_prakash

#### Category of the bug
- Missing Test Cases 

#### Description of the bug
Question says word should be concatenated by at least two shorter words. but bigger word is being considered as answer even it is being made as concatenation of same word twice.
["workaworka", "worka"]

#### Expected behavior
We should get empty vector in this case as we need atleast two shorter word for workaworka to work. here duplicates are not allowed 
and worka is present only one time  

#### Screenshots
![image](https://user-images.githubusercontent.com/12399716/215028025-85bc0ca6-9d39-4dd6-a3b6-875d49ad6f7a.png)

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
