### ISSUE TITLE
TLE Java bug with Queue and Deque in 621. Task Scheduler

### ISSUE THREAD

**Issue by SleeplessChallenger** [LeetCode-Feedback/LeetCode-Feedback#11294]
#### Your LeetCode username

sleeplesschallenger

#### Category of the bug
- [ ] Question
- [YES] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

When `Deque` used as an Interface the solution gives TLE, whilst `Queue` interface passes

#### Code you used for Submit/Run operation

```
class Solution {
    // when "least number" - heap is an option

    // one unit of time to process and n units of time to wait before
    // processing the same task. A _ _ A -> A B idle A. As it must
    // wait 2 units of time (where n = 2)
    public int leastInterval(char[] tasks, int n) {
        final PriorityQueue<Integer> pq = new PriorityQueue<>(Collections.reverseOrder());
        final Queue<Pair<Integer, Integer>> queue = new ArrayDeque<>();
        int time = 0;

        final Map<Character, Integer> bucket = new HashMap<>();

        for (int i = 0; i < tasks.length; i++) {
            int currentCount = bucket.getOrDefault(tasks[i], 0);
            bucket.put(tasks[i], currentCount + 1);
        }

        pq.addAll(bucket.values());

        while (!pq.isEmpty() || !queue.isEmpty()) {
            time++;

            // case when heap is already empty, but queue still has some values
            if (!pq.isEmpty()) {
                int maxNum = pq.poll();

                if ((maxNum - 1) != 0) {
                    queue.offer(new Pair<Integer, Integer>(maxNum - 1, time + n));
                }  
            }

            if (!queue.isEmpty() && queue.peek().getValue() == time) {
                pq.add(queue.poll().getKey());
            } 
        }

        return time;
    }
}   
```

#### Language used for code

Java

#### Expected behavior

So, from my knowledge, both interfaces provide similar Time Complexity and differ only in the internals. `Queue` allows addition to the back and polling from the start, whilst `Deque` allows both

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

They have the same time complexity but maybe a different constant factor.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
