### ISSUE TITLE
Missing Test Case - 27. Remove Element

### ISSUE THREAD

**Issue by math-klgd** [LeetCode-Feedback/LeetCode-Feedback#11293]
#### Category of the bug
- [ ] Question
- [*] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Working solution is not accepted

#### Code you used for Submit/Run operation

```
/**
 * @param {number[]} nums
 * @param {number} val
 * @return {number}
 */
var removeElement = function(nums, val) {
    var k = 0;
    if(nums && nums.length && val)
    {
        for(var i=nums.length-1; i>=0; i--)
        {if(nums[i]===val)
        {
            nums.splice(i,1);
            k++;
            console.log(nums);
            continue;
        }
        }
    }
    return k;
};
```

#### Language used for code
Java-Script

#### Expected behavior

The provided solution solves the task, but system does not accept the solution.

#### Additional context

Output
[0,1,3]
Expected
[0,1,4,0,3]

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by math-klgd** [comment]
Sorry, missed the language. Java-Script.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly. The code received Wrong Answer after submission. 

Please feel free to refer to the discussion section of the problem to see how other users have optimized their codes!

**Comment by math-klgd** [comment]
Hello again. It seems that judger is not running correctly.
The following code (a couple of console.log have been added):
`/**
 * @param {number[]} nums
 * @param {number} val
 * @return {number}
 */
var removeElement = function(nums, val) {
    console.log("start", nums);
    var k = 0;
    if(nums && nums.length && val)
    {
        for(var i=nums.length-1; i>=0; i--)
        if(nums[i]===val)
        {
            nums.splice(i,1);
            k++;
        }
    }
    console.log('end', nums);
    console.log("k=", k);
    return k;
};`

gives the following output:
Stdout
start [
  0, 1, 2, 2,
  3, 0, 4, 2
]
end **[ 0, 1, 3, 0, 4 ]**
k= 3

**end** is the expected output. But judger gets the following output:
Output
[0,1,3]
Expected
**[0,1,4,0,3]**

It is not quite clear why judger gets [0,1,3] array.

Please see below the same code in other online compiler:
[https://onecompiler.com/javascript/3ywe7fk6f](url)

**Comment by math-klgd** [comment]
Found my issue. Function return value must be nums.length:
return nums.length;
