### ISSUE TITLE
wrong test case for connected server problem

### ISSUE THREAD

**Issue by bkchoi1214** [LeetCode-Feedback/LeetCode-Feedback#113]
**What kind of the bug**
- [ ] problem
- [ x] solution
- [ ] language

**Describe the bug**

https://leetcode.com/problems/count-servers-that-communicate/
[[1,0,0,1,0],[0,0,0,0,0],[0,0,0,1,0]]

to me, they look like three isolated computers which are not connected at all. so the answer should be 0 just like the sample test case in the problem description
--

**what language is your code written in**
C++

**The code you submit/run**
```
struct Position
    {
        int row;
        int col;
        
        Position(int _row, int _col) : row(_row), col(_col) {}
    };
    
    int countServers(vector<vector<int>>& grid) 
    {
        vector<vector<bool>> visited(grid.size(), vector<bool>(grid[0].size(), false));
        
        int numServers = 0;
        
        for (int i = 0; i < grid.size(); ++i)
        {
            for (int j = 0; j < grid[i].size(); ++j)
            {
                queue<Position> servers;
                
                if (visited[i][j] || !grid[i][j])
                {
                    continue;
                }
                
                servers.push(Position(i, j));
                int connectedServers = 0;
                while (!servers.empty())
                {
                    Position pos = servers.front();
                    servers.pop();
                    
                    if (visited[pos.row][pos.col] || !grid[pos.row][pos.col])
                    {
                        continue;
                    }       
                    
                    visited[pos.row][pos.col] = true;
                    ++connectedServers;
                    
                    if (pos.row - 1 >= 0)
                    {
                        servers.push(Position(pos.row - 1, pos.col));    
                    }
                    if (pos.row + 1 < grid.size())
                    {
                        servers.push(Position(pos.row + 1, pos.col));
                    }
                    if (pos.col - 1 >= 0)
                    {
                        servers.push(Position(pos.row, pos.col - 1));
                    }
                    if (pos.col + 1 < grid[i].size())
                    {
                        servers.push(Position(pos.row, pos.col + 1));
                    }
                }
                
                cout << "connectedServers: " << connectedServers << endl;
                
                if (connectedServers > 1)
                {
                    numServers += connectedServers;
                }
            }
        }
        
        return numServers;
    }
```

**Expected behavior**
[[1,0,0,1,0],[0,0,0,0,0],[0,0,0,1,0]]

this should return false as servers are not connected in this graph

**Screenshots**

**Additional context**

**Comment by CooperCooperCooper** [comment]
Hi @bkchoi1214,
Thank you for reaching out to us! I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @bkchoi1214,
Thank you for your time. We've taken a thorough look at this issue. This issue is invalid. The return is an integer number, not a boolean return. Please double-check the problem again.

**Comment by bkchoi1214** [comment]
well it was my typo. I meant 0 instead of boolean. what I actually meant is that [[1,0,0,1,0],[0,0,0,0,0],[0,0,0,1,0]] should return 0 not 3.

**Comment by bkchoi1214** [comment]
can you please reopen this and take a look at it

**Comment by CooperCooperCooper** [comment]
Hi @bkchoi1214,
At your request, I've relayed the additional comments you shared with our team to review. The issue was not valid and [here's the explanation](https://leetcode.com/problems/count-servers-that-communicate/discuss/440426/test-case-confusion-for-100100000000010/396266) shared by another user who had the same idea before.
