### ISSUE TITLE
Formatting issue in solution

### ISSUE THREAD

**Issue by shafikshaon** [LeetCode-Feedback/LeetCode-Feedback#11306]
#### Your LeetCode username
shafikshaon

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
There is some formatting issue here https://leetcode.com/problems/implement-stack-using-queues/solutions/127844/official-solution/
Check
```
Time complexity : $$O(1)$$.
**Complexity Analysis**
```
![https://i.imgur.com/uwLBC87.png](https://i.imgur.com/uwLBC87.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
