### ISSUE TITLE
Missing Test Case - 472. Concatenated Words

### ISSUE THREAD

**Issue by lenhhoxung86** [LeetCode-Feedback/LeetCode-Feedback#11314]
#### Category of the bug
- [ x] Question
- [ ] Solution
- [ ] Language
- [ x] Missing Test Cases 

#### Description of the bug

I think the question is not clear in that it does not say if the concatenated word should be created by at least two different words or not. 
For instance, if the input is ```["cat","dog","catdog","catcat"]```, what would be the output, ```["catdog", "catcat"]``` or only ```["catdog"]```? For now, the ground-truth is ```["catdog","catcat"]```.

#### Code you used for Submit/Run operation

```
class Solution:
    def findAllConcatenatedWordsInADict(self, words: List[str]) -> List[str]:
        concat_words = []
        vocab = set(words)
        vocab_size = len(vocab)

        def traverse(sub):
            if (sub in vocab or len(sub) == 0) and len(unique_words) >= 2:
                return True

            result = False
            for i in range(len(sub)+1):
                if sub[:i] in vocab:
                    unique_words.append(sub[:i])
                    result = result or traverse(sub[i:])
                    # backtrack
                    unique_words.remove(sub[:i])
                    if result:
                        break
            return result

        for w in words:
            unique_words = []
            if traverse(w):
                concat_words.append(w)
        return concat_words
```

#### Language used for code
Python

#### Expected behavior

Depending on the description, which should be clearer (see the section Description of the bug).

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
