### ISSUE TITLE
Missing Test Case - 162. Find Peak Element

### ISSUE THREAD

**Issue by Gopalakrishnan20** [LeetCode-Feedback/LeetCode-Feedback#11324]
#### Your LeetCode username
cybertron22

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

request to add  my testcase

#### Code you used for Submit/Run operation

```
class Solution {
    public int findPeakElement(int[] nums) {
        int start = 0;
        int end = nums.length - 1;
        while(start < end){
            int mid = start + (end - start) / 2;
            if(nums[mid] > nums[mid+1]){
                end = mid;
            }
            else{
                start = mid + 1;
            }
        }
        return end;        
    }
}
```

#### Language used for code

JAVA

#### Expected behavior

```
Input: [1,2,1,3,1,6,4]
Output: 1

```

**Comment by stormsunshine** [comment]
Do you see this statement in problem description?

> If the array contains multiple peaks, return the index to **any of the peaks**.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The test case [1,2,1,3,1,6,4] already exists. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
