### ISSUE TITLE
Missing Test Case - 352. Data Stream as Disjoint Intervals

### ISSUE THREAD

**Issue by kautsiitd** [LeetCode-Feedback/LeetCode-Feedback#11327]
#### Your LeetCode username

KautsIITD

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases

#### Description of the bug

Test cases are Weak.
1. Value Range is [0,10000] only.. Hence maximum answer size of getIntervals query is 5000..
2. A solution as simple as storing occurrence in Bool array passed.. Can be seen [here](https://leetcode.com/problems/data-stream-as-disjoint-intervals/submissions/886659523/)..
3. Given that there will be 30000 queries, It should not.. If there are 25000 getIntervals() queries..

#### Code you used for Submit/Run operation

```
class SummaryRanges(object):
    def __init__(self):
        self.limit = -1
        self.arr = [False for i in range(10005)]

    def addNum(self, value):
        self.arr[value] = True
        if value+5 > self.limit: self.limit = value+5

    def getIntervals(self):
        ans, start, end, current = [], None, None, 0
        while current < self.limit:
            if self.arr[current] == True:
                if start == None: start = current
                end = current
            else:
                if start != None:
                    ans.append([start, end])
                    start, end = None, None
            current += 1
        return ans
```

#### Language used for code

Python

#### Expected behavior

With above Solution Code, I should have got TLE. Instead solution was Accepted.

#### Screenshots

TLE can be seen in below ScreenShot.
<img width="1440" alt="Screenshot 2023-01-28 at 12 08 32 PM" src="https://user-images.githubusercontent.com/15329761/215250997-4d03bf59-dae7-4cfb-89ab-904f4be4c8cf.png">

#### Additional context

I used following code to generate required TestCase in Python.
```
## For Query Names
ans = "[\"SummaryRanges\","
for i in range(5000):
    ans += "\"addNum\","
for i in range(24998):
    ans += "\"getIntervals\","
ans += "\"getIntervals\"]"
print(ans)

## For Query Values
ans = "[[],"
for i in range(5000):
    ans += "["+str(i)+"],"
for i in range(24998):
    ans += "[],"
ans += "[]]"
print(ans)
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
