### ISSUE TITLE
Missing Constraints - 74. Search a 2D Matrix

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1133]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

74. Search a 2D Matrix
https://leetcode.com/problems/search-a-2d-matrix/

Please add constraints for this question:
- What is the range of `m` & `n`
- What is the range of the values of the matrix? Is it like this: `3000 <= m[i][j] <= 3000`?

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

- The question must have constraints so that there is no TLE or other errors for the user.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
