### ISSUE TITLE
Missing Test Case - 352. Data Stream as Disjoint Intervals

### ISSUE THREAD

**Issue by RohitSgh** [LeetCode-Feedback/LeetCode-Feedback#11333]
#### Your LeetCode username

RohitSgh

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The code gets [submitted](https://leetcode.com/problems/data-stream-as-disjoint-intervals/submissions/886942758/). But it ideally shouldn't get submitted/accepted.

It is giving **Wrong Answer** on this Test Case
```
["SummaryRanges","getIntervals","addNum","getIntervals","addNum","getIntervals","addNum","getIntervals","addNum","getIntervals"]
```
```
[[],[],[3],[],[7],[],[2],[],[6],[]]
```

Submission is because this **test case is missing**.

#### Code you used for Submit/Run operation

```python3
from sortedcontainers import SortedList

class SummaryRanges:

    def __init__(self):
        self.a = SortedList()
        
    def addNum(self, value: int) -> None:
        if value not in self.a:
            self.a.add(value)

    def getIntervals(self) -> List[List[int]]:
        i, l, r = [], -1, -1
        for v in self.a:
            if l < 0: l = r = v
            elif v == r + 1: r = v
            else:
                i.append([l, r])
                l = r = v
        i.append([l, r])
        return i
        


# Your SummaryRanges object will be instantiated and called as such:
# obj = SummaryRanges()
# obj.addNum(value)
# param_2 = obj.getIntervals()
```

#### Language used for code

Python3

#### Expected behavior

- **Expected :** Code shouldn't get submitted/accepted because it is giving wrong answer on Test Case
```
["SummaryRanges","getIntervals","addNum","getIntervals","addNum","getIntervals","addNum","getIntervals","addNum","getIntervals"]
[[],[],[3],[],[7],[],[2],[],[6],[]]
```

- **Happened :** Code Accepted. Here is the submission https://leetcode.com/problems/data-stream-as-disjoint-intervals/submissions/886942758/

#### Screenshots

Submission along with Wrong Answer
> ![Wrong Answer](https://user-images.githubusercontent.com/81853910/215279435-8943eab8-c525-4fb3-8c22-aabad33347b8.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
