### ISSUE TITLE
1319. Number of Operations to Make Network Connected

### ISSUE THREAD

**Issue by alantudyk** [LeetCode-Feedback/LeetCode-Feedback#11347]
#### Your LeetCode username
0x81

#### Category of the bug
Description is unclear or incorrect

#### Description of the bug
>Constraints:
>
>- `1 <= n <= 10⁵`
>- `1 <= connections.length <= min(n * (n - 1) / 2, 10⁵)`
>- `0 <= aᵢ, bᵢ < n`
>- `aᵢ != bᵢ`

Choose one of two:
- If `1 <= n` then `0 <= connections.length`
- If `1 <= connections.length` then `2 <= n`

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

We decided not to add it. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by alantudyk** [comment]
> We decided not to add it.

If `n == 1` then `connections` must be empty. Do you really disagree?
