### ISSUE TITLE
1780. Check if Number is a Sum of Powers of Three 

### ISSUE THREAD

**Issue by amancod** [LeetCode-Feedback/LeetCode-Feedback#11349]
#### Your LeetCode username

amanmaurya4527

#### Category of the bug
- [ ✅] Question
- [ ] Solution
- [ ] Language
- [ ✅] Missing Test Cases 

#### Description of the bug

When we are taking input (n=243) .It is showing false . But it should be true.

#### Code you used for Submit/Run operation

```

class Solution {
public:
    bool checkPowersOfThree(int n) {
        if(n==1)return 1;
        unordered_map<int,int>mpp;
        int x=log(n)/log(3);
        
        while(n!=0){
            if(mpp[x]!=0)return 0;
            n=n-pow(3,x);
            mpp[x]++;
            if(n!=0)x=log(n)/log(3);
           //  if(n==243)x=5;
        }
        return 1;
    }
};
```

#### Language used for code

C++

#### Expected behavior

For  input (n=243)  .The value of log(243)/log(3) should be 5.

#### Screenshots

![image](https://user-images.githubusercontent.com/106539303/215322432-f4fac4a2-3842-4e5b-856e-c78f231a8823.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output values.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!
