### ISSUE TITLE
460. LFU Cache - Invalid test case

### ISSUE THREAD

**Issue by mnaoumov** [LeetCode-Feedback/LeetCode-Feedback#11341]
#### Your LeetCode username

mnaoumov

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Test case 46 contradicts the task description

```
["LFUCache","put","get"]
[[0],[0,0],[0]]
Expected: [null,null,-1]
```

The task description says

> When the cache reaches its capacity, it should invalidate and remove the least frequently used key **before** inserting a new item

Therefore when we execute `put(0, 0)` there is nothing to remove **before** inserting. So according to the task description we have to insert `0` and won't invalidate it until next `put` command.

So expected result supposed to be `[null,null,0]`

#### Code you used for Submit/Run operation

```csharp
public class LFUCache
{
    private readonly int _capacity;
    private readonly Dictionary<int, int> _dict;
    private readonly Dictionary<int, int> _useCounter;
    private readonly PriorityQueue<(int key, int useCount), (int useCount, int timestamp)> _priorityQueue;
    private int _timestamp;

    public LFUCache(int capacity)
    {
        _capacity = capacity;
        _dict = new Dictionary<int, int>(capacity);
        _useCounter = new Dictionary<int, int>(capacity);
        _priorityQueue = new PriorityQueue<(int key, int useCount), (int useCount, int timestamp)>(capacity);
    }

    public int Get(int key)
    {
        if (!_dict.TryGetValue(key, out var value))
        {
            return -1;
        }

        IncreaseUseCounter(key);
        return value;
    }

    public void Put(int key, int value)
    {
        if (_dict.Count == Math.Max(1, _capacity) && !_dict.ContainsKey(key))
        {
            int lfuKey;
            int lfuUseCount;

            do
            {
                (lfuKey, lfuUseCount) = _priorityQueue.Dequeue();
            } while (_useCounter[lfuKey] != lfuUseCount);

            _dict.Remove(lfuKey);
            _useCounter.Remove(lfuKey);
        }

        _dict[key] = value;
        IncreaseUseCounter(key);
    }

    private void IncreaseUseCounter(int key)
    {
        _useCounter[key] = _useCounter.GetValueOrDefault(key) + 1;
        _priorityQueue.Enqueue((key, _useCounter[key]), (_useCounter[key], _timestamp));
        _timestamp++;
    }
}
```

#### Language used for code

C#

#### Expected behavior

The solution should be accepted.

**Comment by parasg1999** [comment]
The capacity is initialised as 0, so 0 as a key won't be inserted

**Comment by mnaoumov** [comment]
@parasg1999 But this is not covered by any rule from the task description

**Comment by stormsunshine** [comment]
The capacity can be 0, and it is 0 in this test case. Since the capacity is 0, you can't insert any item into LFU cache, so the get method will always return -1.

Why do you think the item should be inserted when the capacity is 0?

**Comment by mnaoumov** [comment]
@stormsunshine current task description doesn't force the behavior you are talking about. I highlighted the only case that description mentions. The LFU items are removed BEFORE inserting. None of the results imply that if capacity is zero, we don't perform the insertion at all. While it might seem to be a common sense, it doesn't follow from current rules. So I suggest either

1. Change the test case as I said in my original comment
2. Add some wording to the task description. Something like "after **put** operation the amount of items should not exceed `capacity`"
3. Change the description to require `capacity > 0` and remove the mentioned test case

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
