### ISSUE TITLE
Question 45 - Jump Game II is framed incorrectly

### ISSUE THREAD

**Issue by kumarp149** [LeetCode-Feedback/LeetCode-Feedback#11355]
#### Your LeetCode username
kumarp149

#### Category of the bug
- [x] Question

#### Description of the bug
The framing of the question is incorrect. It is stated that the initial position is at index nums[0] but the question intends that the initial position is at index 0. Same is the issue with the final desired position. It is stated that the final desired position is at index nums[N-1] but the question intends the final desired position to be at index N-1. At the first glance, the question completely misleads user. So, I request you to update the question

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by kumarp149** [comment]
HI @LC-Pam, any update from the team?

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

We decided to reject this suggestion. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
