### ISSUE TITLE
剑指 Offer 40. 最小的k个数 "测试用例" "运行" 的  "预期结果" 为空 

### ISSUE THREAD

**Issue by leechangqing** [LeetCode-Feedback/LeetCode-Feedback#11356]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
ben-dexiong

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [X] 缺少测试用例

**描述**
"测试用例" "运行" 结果中的 "预期结果" 为空 ，导致无法验证代码执行用例是否正确；

**你使用的语言**
C++

**你提交或者运行的代码**
```
// 剑指 Offer 40. 最小的k个数
class Solution {
public:
    vector<int> getLeastNumbers(vector<int>& arr, int k) {
        sort(arr.begin(), arr.end());
        vector<int> result(arr.begin() , arr.begin() + k);
        return result;
    }
};
```

**期望行为**
用例 [3,2,1] , 2
期望 结果 为 [1,2]

**屏幕截图**
![image](https://user-images.githubusercontent.com/15624642/215331487-12908f2a-2fc3-4b8f-8d02-04fb9a77afb8.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
你好，如果出现测试用例结果和提交结果不一致的情况，可以再仔细检查并调试一下代码，或点击这里：「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」 获得更多帮助。

同时也可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。

**Comment by leechangqing** [comment]
您好，反馈的问题并未得以解决。

问题是预期结果为力扣系统执行结果，用户代码输出结果与题目示例一致，而力扣系统运行有bug，从而导致结果判定失败，请核实解决



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年01月30日 10:45 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [LeetCode-Feedback/LeetCode-Feedback] 剑指 Offer 40. 最小的k个数 "测试用例" "运行" 的  "预期结果" 为空  (Issue #11356) |

你好，如果出现测试用例结果和提交结果不一致的情况，可以再仔细检查并调试一下代码，或点击这里：「为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了」 获得更多帮助。

同时也可以点击「题解」来查看当前题目的解题思路，或 点击这里 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。

**Comment by feiceh** [comment]
感谢反馈，当前题目已修复，奖励已发放，请查收。
