### ISSUE TITLE
460. LFU Cache - official solution has inefficient and incorrect memory

### ISSUE THREAD

**Issue by przemek3d88** [LeetCode-Feedback/LeetCode-Feedback#11359]
#### Your LeetCode username
przemysaw2

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The official solution's memory is O(min(N, capacity) + |put| + |get|) -> the number of elements in the cache + the number of operations. It keeps the track of every usage frequency. If you keep putting/getting the same key 2e9 times, it will run out of memory. I posted the fix in the [comment](https://leetcode.com/problems/lfu-cache/solutions/2815229/lfu-cache/comments/1779530). The [URL](https://leetcode.com/problems/lfu-cache/submissions/887542804/) to the fixed solution.

#### Code you used for Submit/Run operation
The following program, using the official solution demonstrates the problem.

```
#include <bits/stdc++.h>
using namespace std;

class LFUCache
{
    // key: frequency, value: list of original key-value pairs that have the same frequency.
    unordered_map<int, list<pair<int, int>>> frequencies;
    // key: original key, value: pair of frequency and the iterator corresponding key int the
    // frequencies map's list.
    unordered_map<int, pair<int, list<pair<int, int>>::iterator>> cache;
    int capacity;
    int minf;

    void insert(int key, int frequency, int value) {
        frequencies[frequency].push_back({ key, value });
        cache[key] = { frequency, --frequencies[frequency].end() };
    }

    public:
    LFUCache(int capacity): capacity(capacity), minf(0) {}

    int get(int key) {
        const auto it = cache.find(key);
        if (it == cache.end()) {
            return -1;
        }
        const int f = it->second.first;
        const auto iter = it->second.second;
        const pair<int, int> kv = *iter;
        frequencies[f].erase(iter);
        if (frequencies[f].empty() && minf == f) {
            ++minf;
        }
        insert(key, f + 1, kv.second);
        return kv.second;
    }

    void put(int key, int value) {
        if (capacity <= 0) {
            return;
        }
        const auto it = cache.find(key);
        if (it != cache.end()) {
            it->second.second->second = value;
            get(key);
            return;
        }
        if (capacity == cache.size()) {
            cache.erase(frequencies[minf].front().first);
            frequencies[minf].pop_front();
        }
        minf = 1;
        insert(key, 1, value);
    }
};

int main() {
    LFUCache cache(1);
    cache.put(1, 1);
    int lim = 2e9;
    for (int i = 0; i < lim; i++) {
        cache.get(1);
    }

    printf("Done");
    
    return 0;
}
```

#### Language used for code
C++

#### Expected behavior
The program should be able to complete, without using too much memory. On my machine, it eats 10 GB and gets killed.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback. 

Please send us your Leetcode username.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by przemek3d88** [comment]
Hi,

Thanks!

My LC username is: przemysaw2.

Thanks,
Dez

**Comment by przemek3d88** [comment]
Hi, I noticed that you updated the c++ code. However, I think that the java solution still suffers from the same issue, in part, where you try to evict the LFU element:
`if (capacity == cache.size()) {
            final Set<Integer> keys = frequencies.get(minf);
            final int keyToDelete = keys.iterator().next();
            cache.remove(keyToDelete);
            keys.remove(keyToDelete);
        }`

You do not remove empty frequencies there. You can imagine the following scenario:
cache with 1 limit capacity

put (1,1) and get(1) 1e9 times
put(2,2) and get(2) 1e9-1 times
...

This way, you will finally store 1e9 keys. This is not exactly the same issue, more subtle, but still present.

**Comment by LC-Pam** [comment]
Hi there,

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
