### ISSUE TITLE
Missing Test Case - 1528. Shuffle String

### ISSUE THREAD

**Issue by Hrutvik66** [LeetCode-Feedback/LeetCode-Feedback#11367]
#### Your LeetCode username

hrutvikmalshikare

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [.] Missing Test Cases 

#### Description of the bug

The test case provided by you gives a wrong answer and its explanation also provided a wrong.
The test case is 
s =
"codeleet"
indices =
[4,5,6,7,0,2,1,3]

Here, the answer has to be "leetcdoe" but it gives the answer "leetcode".

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    string restoreString(string s, vector<int>& indices) {
        string ans = "";
        int len = indices.size();
        for(int i = 0;i < len; i++){
            ans += s[indices[i]];
        }
        return ans;
    }
};
```

**Comment by stormsunshine** [comment]
The test case is correct. The image in the example clearly explains the logic.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
