### ISSUE TITLE
Typo in problem content - 2488. Count Subarrays With Median K

### ISSUE THREAD

**Issue by amyangfei** [LeetCode-Feedback/LeetCode-Feedback#11366]
**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**

typo

**期望行为**

s/num/nums

**屏幕截图**

![image](https://user-images.githubusercontent.com/1527315/215386540-114d221e-564e-458f-a797-12eae3afb41c.png)

**Comment by feiceh** [comment]
感谢反馈，当前题目已修复，请留言告知一下力扣中文网站的 ID，我们给予积分奖励哦。
