### ISSUE TITLE
Missing Test Case - 146. LRU Cache

### ISSUE THREAD

**Issue by mohamedahmed-cloud** [LeetCode-Feedback/LeetCode-Feedback#11365]
#### Your LeetCode username

modyyousef800

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] bug in test case System

- The problem is when I run the code and submit it gives different answer ***the same test case***
 When I run it gives me a correct answer.
 but when I submit it gives me wrong for ***the same test case***

- Code 
```py
class LRUCache:
    storeDict=defaultdict(int)
    def __init__(self, capacity: int):
            self.capacity=capacity
            
    def get(self, key: int) -> int:
            ans=LRUCache.storeDict.get(key,-1)
            if ans!=-1:
                del LRUCache.storeDict[key]
                LRUCache.storeDict[key]=ans
            return ans
    def put(self, key: int, value: int) -> None:
        if len(LRUCache.storeDict)==self.capacity and not LRUCache.storeDict.get(key):
            del LRUCache.storeDict[next(iter(LRUCache.storeDict))]
            LRUCache.storeDict[key]=value
        else:
            LRUCache.storeDict[key]=value

```
Test Case :
`["LRUCache","put","put","get","put","get","put","get","get","get"]`
`[[2],[1,0],[2,2],[1],[3,3],[2],[4,4],[1],[3],[4]]`

the number of this test case is 4 when you submit.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users have optimized their codes!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output values.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!
