### ISSUE TITLE
Right answer showing as wrong answer.

### ISSUE THREAD

**Issue by sangeeta9897** [LeetCode-Feedback/LeetCode-Feedback#11383]
#### Your LeetCode username
sangeeta9897

#### Category of the bug
 Solution

#### Code you used for Submit/Run operation

```
class Solution {
public:

    int longestPalindromeSubstr(string s) {

        int n=s.length();
        int dp[n][n];
        memset(dp,0,sizeof(dp));
        int start=0, end=0;
        int ans=1;
        for(int i=0;i<n;i++) {
             dp[i][i]=1;
        }
        for(int i=0;i<n;i++) {
             for(int j=0;j<n;j++) {
                if(i<j) {
                    if(s[i]==s[j]) {
                        dp[i][j]=1;
                        if(ans < j-i+1 ) {
                            start = i;
                            end = j;
                            ans=j-i+1;
                        }
                    }
                    break;
                }
            }
        }
        for(int j=2;j<n;j++) {
            for(int i=0;i<n-2;i++) {
                if(i<j) {
                    if(s[i]==s[j] && dp[i+1][j-1]==1) {
                        dp[i][j]=1;
                        if(ans < j-i+1 ){
                            start = i;
                            end = j;
                            ans=j-i+1;
                        }
                    }
                }
            }
        }
        return end;
    }

    string shortestPalindrome(string s) {
        int n=s.length();
        int end = longestPalindromeSubstr(s);
        string ans="";
        for(int i=n;i>end;i--){
            ans+=s[i];
        }
        for(int i=0;i<n;i++)
        ans+=s[i];
        return ans;
    }
};

```

#### Language used for code
C++

#### Screenshots
<img width="857" alt="Screenshot 2023-01-31 at 2 00 44 AM" src="https://user-images.githubusercontent.com/36931060/215589855-3592c33a-8cf4-490c-86c2-cd62f2e12300.png">

#### Additional context
Nothing

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem name or number.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by sangeeta9897** [comment]
Sorry, I missed adding the problem number in the issue description. Below are the details
Problem Name - Shortest Palindrome
Problem Number - 214

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly. The code received Wrong Answer after submitted. 

Please feel free to refer to the discussion section of the problem to see how other users have optimized their codes!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output values.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!
