### ISSUE TITLE
Missing Test Case - Problem with constraints - 352. Data Stream as Disjoint Intervals

### ISSUE THREAD

**Issue by DavidGMdev** [LeetCode-Feedback/LeetCode-Feedback#11382]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 
- [x] Main solution [admin pinned solution] fail  

#### Description of the bug

bug on large testcases , on having massive number of get intervals calls and also
having all numbers entered are disjoint intervals.  
 
for example if we provide a sample of : 
- 1e4 entries ( n = 1e4 ) , where calls constraints is 3e4 call as mentioned in problem statement,
- 3e5 of them [ half of them ] are "addNum" 
- those calls add disjoint intervals numbers as [1] [3] [5] ..etc [ that cannot merge to shorten size ]
- other 3e5 [ the other half ] are "getIntervals"
- those calls retrieve all intervals [ which are disjoint ones ]

Result : 
- if we do all "addNum" then all "getIntervals" => TLE 
- if we do overlapping "addNum" and "getintervals" one by one => TLE 
- my solution got TLE 
- even admins [ official solution ]  got TLE on this sample too 
I tried around 10+ solutions including admins one and all has TLE verdict for similar samples 

since most of problem solutions has concept of O(n) for an operation and 
O(log) / O(1) for the other if we stress on the O(n) operation the solution got TLE 

so is there any solution that pass those similar cases or 
the provided upperbound constraints for the problem is wrong ? 

testcase : sample file will be attached 
[1e4 sample.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/10538088/1e4.sample.txt)

#### Code you used for Submit/Run operation

```
class SummaryRanges {
public:
    set<vector<int>> intervals; // [ [x,y] , [x,y] , ...etc ]
    SummaryRanges() {}
    bool canMerge(vector<int>  a , vector<int> b ){
        return ( a[0] <= b[0] && b[0] <= a[1] + 1 )  ; 
    }
    vector<int> merge( vector<int> a , vector<int> b ){
        return {min(a[0],b[0]),max(a[1],b[1])};
    }
    void addNum(int value) {
        intervals.insert({value,value});
    }
    vector<vector<int>> getIntervals() {
        vector<vector<int>> ans;
        set<vector<int>> spare;
        vector<int> curr = {} ;
        for( auto & i : intervals ){
            if ( curr.empty() ) curr = i ; 
            else {
                if( canMerge(curr,i) ) curr = merge(curr,i);
                else {
                    ans.push_back(curr);
                    spare.insert(curr);
                    curr = i;
                }
            }
        }
        ans.push_back(curr);
        spare.insert(curr);

        // reuse
        intervals = spare ;
        return ans ; 
    }
};

```

#### Expected behavior

Expected behavior : TLE 
Happens : AC verdict

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
