### ISSUE TITLE
No Expected Answer for a Test Case in Leetcode 638

### ISSUE THREAD

**Issue by jinnies47** [LeetCode-Feedback/LeetCode-Feedback#11389]
#### Your LeetCode username
jinnies47

#### Category of the bug
- Question
- Solution
- Missing Test Cases 

 
#### Description of the bug
When the first n values of special[i][j] == 0 in a test case the expected column is blank ,
and it gives accepted verdict for a wrong answer instead of displaying the correct answer and showing the proper verdict.
The constraints mention that special[i][j] can take 0 as its value.

#### Code you used for Submit/Run operation
```
class Solution {
public:
    int shoppingOffers(vector<int>& price, vector<vector<int>>& special, vector<int>& needs) {
        return 16;//or any random number
    }
};
```

#### Language used for code
C++ 

#### Screenshots
**Constraints**
![image](https://user-images.githubusercontent.com/63533609/215735655-17d33b22-92d2-47ce-b3a4-0a73bb0e0dd0.png)
**When i run my code**
![image](https://user-images.githubusercontent.com/63533609/215736389-577f14e4-557b-41d0-9d23-79cf74fa8d31.png)
![image](https://user-images.githubusercontent.com/63533609/215736204-a7e4af21-6336-471c-ae84-41733ccfb3f0.png)

#### Additional context
The bug occurs when for a certain test case the algorithm doesn't give an expected value for the solution

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output values.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!
