### ISSUE TITLE
Missing Test Case - 1071. Greatest Common Divisor of Strings

### ISSUE THREAD

**Issue by ejhuzed** [LeetCode-Feedback/LeetCode-Feedback#11399]
#### Your LeetCode username
[ejhuzed](https://leetcode.com/ejhuzed/)

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug
The following AC code cannot pass the test case:
str1 = ```'ABCBAC'```
str2 = ```'ABC'```

#### Code you used for Submit/Run operation
```python3
class Solution:
    def gcdOfStrings(self, str1: str, str2: str) -> str:
        n1, n2 = len(str1), len(str2)
        if n1 < n2:
            str1, str2, n1, n2 = str2, str1, n2, n1
        ord_str1 = [ord(str1[i]) for i in range(n1)]
        ord_str2 = [ord(str2[i]) for i in range(n2)]
        v = gcd(sum(ord_str1), sum(ord_str2))
        
        if v < ord('A'):
            return ''
        else:
            idx, cnt = 0, 0
            while cnt < v:
                if ord_str2[idx] != ord_str1[idx]:
                    return ''
                cnt += ord_str2[idx]
                idx += 1

            return str2[:idx]
```

#### Language used for code
Python3

#### Expected behavior
The submisson should get WA.

#### Screenshots
![LC-1071-AC](https://user-images.githubusercontent.com/108965511/215946420-f6b55221-a785-4ea5-ba55-710e40a8782a.PNG)
![LC-1071-WA](https://user-images.githubusercontent.com/108965511/215951435-c2b9db2d-23b4-4758-8432-445f9204ec1b.PNG)

#### Additional context
The code can be modified as:
```python3
class Solution:
    def gcdOfStrings(self, str1: str, str2: str) -> str:
        n1, n2 = len(str1), len(str2)
        if n1 < n2:
            str1, str2, n1, n2 = str2, str1, n2, n1
        ord_str1 = [ord(str1[i]) for i in range(n1)]
        ord_str2 = [ord(str2[i]) for i in range(n2)]
        sum_1, sum_2 = sum(ord_str1), sum(ord_str2)
        v = gcd(sum_1, sum_2)
        
        if v < ord('A'):
            return ''
        else:
            idx, cnt = 0, 0
            while cnt < v:
                if ord_str2[idx] != ord_str1[idx]:
                    return ''
                cnt += ord_str2[idx]
                idx += 1
                
            res = str2[:idx]
            return '' if str1 != res*(sum_1//v) or str2 != res*(sum_2//v) else res 
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
