### ISSUE TITLE
Missing Test Case - 142. Linked List Cycle II

### ISSUE THREAD

**Issue by arya-vats** [LeetCode-Feedback/LeetCode-Feedback#11396]
#### Category of the bug
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
  let mySet = new Set()
  while (head !== null) {
    if (mySet.has(head)) {
      return head
    } else {
      mySet.add(head)
    }
    head = head.next
  }
  return head
}
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by arya-vats** [comment]
Hi, my concern was that this code uses set in js, however, set cannot store duplicate values, what if the linkedlist contains duplicates? eg : [1,2,3,5,5,7,8,5,9] and 9 --> 2
