### ISSUE TITLE
Missing Test Case - 638. Shopping Offers

### ISSUE THREAD

**Issue by jinnies47** [LeetCode-Feedback/LeetCode-Feedback#11390]
#### Your LeetCode username
jinnies47

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
The judge's solution goes in an infinite loop if the first n special values of special[i] array are zero as this test case is not accounted for

#### Code you used for Submit/Run operation
```
class Solution {
public:
    bool check(vector<int>& needs,vector<int>& e)
    {
        int sum=0;
        for(int i=0;i<needs.size();i++)
        {
            if(needs[i]<e[i]) return 0;
            sum+=e[i];
        }
        return sum!=0;
    }
    void ope(vector<int>& needs,vector<int>& e,char c)
    {
        for(int i=0;i<needs.size();i++)
        {
            if(c=='+')
            needs[i]+=e[i];
            else 
            needs[i]-=e[i];
        }
    }
    int shoppingOffers(vector<int>& price, vector<vector<int>>& special, vector<int>& needs) {
        int cost=0,n=price.size();
        for(int i=0;i<n;i++)
        cost+=price[i]*needs[i];
        if(cost==0) return 0;
        for(vector<int>& e:special)
        {
            if(e[n]<=cost && check(needs,e))
            {
                ope(needs,e,'-');
                cost=min(cost,e[n]+shoppingOffers(price,special,needs));
                ope(needs,e,'+');
            }
        }
        return cost;
    }
};
```

#### Language used for code
C++ 

#### Expected behavior
It should make a check to see if first n special values are zero or not otherwise it will go in an infinite loop 

#### Additional context
I have added a test case as per the constraints of the problem

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

Please Explicitly write the test case.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by jinnies47** [comment]
**So sorry i forgot to put the actual test case here it is. The judge gives runtime error in the problem instead of giving the correct answer**
![image](https://user-images.githubusercontent.com/63533609/217446012-ff3e6b58-f3f2-4134-9ab0-668316b97ccc.png)
