### ISSUE TITLE
English typos in strStr() solution

### ISSUE THREAD

**Issue by naphtul** [LeetCode-Feedback/LeetCode-Feedback#11395]
#### Your LeetCode username
naphtul

#### Category of the bug
- [ ] Question
- [X] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug
In https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/solutions/3121002/official-solution/
> However, the approach is still not fool-proof.

Also
> The slides illustrates the process

#### Expected behavior
I believe you meant to write: **full-proof**.
Respectively, you probably meant to write **illustrate** (singular form).

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the solution.

Fool-proof is correct and we will remove the plurality.  

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
