### ISSUE TITLE
Missing Test Case - 1071. Greatest Common Divisor of Strings

### ISSUE THREAD

**Issue by varun325** [LeetCode-Feedback/LeetCode-Feedback#11400]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Code gets accepted but fails for the given test case
str1 = "AABBAABBAA"
str2 = "AABB"

#### Code you used for Submit/Run operation

**java**

```java
class Solution {
    
    public String gcdOfStrings(String str1, String str2) {
        int length1=str1.length();
        int length2=str2.length();
        
        for(int i=0;i<length1;i++){
            if(str1.charAt(i) != str2.charAt(i%length2))
                return "";
        }
        
        int hcf = hcf(length1,length2);
        return str1.substring(0, hcf);
    }
    
    public int hcf(int a, int b) {
        return b==0?a:hcf(b,a%b);    
    }
    
}
```
**c++**
```c++
class Solution {
public:
    string gcdOfStrings(string str1, string str2) {
        int length1=str1.length();
        int length2=str2.length();
        
        for(int i=0;i<length1;i++){
            if(str1[i] != str2[i%length2])
                return "";
        }
        
        int gcd = hcf(length1,length2);
        return str1.substr(0, gcd);    
    }
    
    
public:
    int hcf(int a, int b) {
        return b==0?a:hcf(b,a%b);    
    }
};
```

#### Language used for code
[JAVA/C++]

#### Expected behavior

Answer should be "" instead of AA

#### Screenshots

![image](https://user-images.githubusercontent.com/33104739/215958350-daeba7eb-4eee-46c9-b73d-117c2c803a4b.png)

#### Additional context

**Missing test cases**
"AABBAABBAA"
"AABB"

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
