### ISSUE TITLE
Unclear description - Problem 191. Number of 1 Bits

### ISSUE THREAD

**Issue by ShubhamSKadam** [LeetCode-Feedback/LeetCode-Feedback#11409]
#### Your LeetCode username

 ShubhamSKadam

#### Category of the bug
- [ ] Question

#### Description of the bug

In the description it's written "Write a function that takes an unsigned integer" whereas it must be  "unsigned binary representation of integer". I think you guys can take this into consideration.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
