### ISSUE TITLE
Missing Test Case - 1071. Greatest Common Divisor of Strings

### ISSUE THREAD

**Issue by RajKumarRay** [LeetCode-Feedback/LeetCode-Feedback#11419]
#### Your LeetCode username
Raj_ray_2001

#### Category of the bug
- [1] Missing Test Cases 

#### Description of the bug

for test case where the size of str1 is 1 and size of str2 is greater than 1. 
example
str1="A"
str2="AA"
it should give "A" as output. But there are solution of users whose code failed for this test case but the solution is accepted. 
So, this test case is missing.

#### Code you used for Submit/Run operation

```
class Solution {
    public String gcdOfStrings(String str1, String str2) {
        int n1 = str1.length();
        int n2 = str2.length();
        if(!(str1+str2).equals(str2+str1))
            return "";

        if(n2 == 1) 
            return str2;
        
        String ans = "";
        for(int i=2; i<=Math.min(n1, n2); i++) {
            if(n1%i==0 && n2%i == 0) 
                ans = str1.substring(0, i);
        }

        return ans;
    }
}
```

#### Language used for code

Java

#### Expected behavior

for the above test cases the code is failing or giving wrong output but still the solution is accepted.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
