### ISSUE TITLE
Bad test case. Problem 287.

### ISSUE THREAD

**Issue by shanedgriffith** [LeetCode-Feedback/LeetCode-Feedback#11416]
#### Category of the bug
Bad test case in Problem 287.

#### Description of the bug
The testcase 11/58 has the input nums = [2,2,2,2,2]. But the problem description states "There's only one repeated number in nums". This causes my c++ solution to fail.

#### Code you used for Submit/Run operation
int findDuplicate(vector<int>& nums) {
        int sum = 0;
        int expected = 0;
        for(int i=0; i<nums.size(); ++i) {
            sum += nums[i];
            expected += i;
        }
        return sum - expected;
    }

#### Language used for code
C++

**Comment by stormsunshine** [comment]
The repeated element is 2 and it exists five times in the array. Is there any problem?

**Comment by shanedgriffith** [comment]
Thanks for your reply. Now I understand what it should mean. Perhaps the description could be written more clearly:

"There is only one repeated number in nums, return this repeated number." ->
"There is only one repeated number in nums, which appears two or more times. Return this repeated number."
