### ISSUE TITLE
Missing Test Case - 3. Longest Substring Without Repeating Characters

### ISSUE THREAD

**Issue by Kyouma45** [LeetCode-Feedback/LeetCode-Feedback#11412]
#### Your LeetCode username

LeetCode username: Kyouma45

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 
Wrong Testcase

#### Description of the bug

Testcase 179 is wrong.
Input: "dvdf"
my code's output is 2 which according to me should be correct but expected answer to this case is 3.
longest substring without repeating characters should be 2 in this case.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int lengthOfLongestSubstring(string s) {
        std::string::iterator itr=s.begin();
        if(s.length()==1)
            return 1;
        int arr[1000]={0};
        int z=0,p,k=0;
        bool g=false;
        while(itr!=s.end())
        {
            p=*itr;
            arr[*itr]++;
            if(arr[*itr]==1)
                z++;
            if(arr[*itr]>1)
            {
                g=true;
                arr[*itr]=1;
                if(z>k)
                k=z;
                z=1;
            }
            cout<<*itr<<"\t"<<z<<"\t"<<k<<endl;
            itr++;
        }
        if(g==false||z>k)
                return z;
        return k;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Expected Answer should be 2

#### Screenshots

![image](https://user-images.githubusercontent.com/67496078/216102277-461ab52f-177a-43db-b04c-d16e4c06500a.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
