### ISSUE TITLE
面试题 17.23. 最大黑方阵，系统对输入参数预校验功能有漏洞

### ISSUE THREAD

**Issue by leechangqing** [LeetCode-Feedback/LeetCode-Feedback#11411]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
ben-dexiong

**Bug 类型**
- [ ] 题目
- [x] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
当存在输入参数格式不正确的用例时，系统未对参数进行有效的预校验，而是提交给了后天处理；同时后台系统又因非法输入参数而终止流程，从而造成3个bug现象；

**你使用的语言**
C++

**你提交或者运行的代码**
```
[[1,0,1],[0,0,1],[0,0,1]]
[[1,0,1],[0,0,1],[0,0,1]
[[1,0,1],[0,0,1],[0,0,1]]
```

**期望行为**
上述3组用例的第二组用例格式非法，系统应对参数进行有效的预校验，并给出友好提示，并且不提交用例给后台

**屏幕截图**
图1 正常执行情况
![image](https://user-images.githubusercontent.com/15624642/216077238-44705e44-894a-4854-ae3c-e0d61ca044c7.png)

图2 错误场景_用例4格式错误用例得不到数据
![image](https://user-images.githubusercontent.com/15624642/216077586-0183e79e-f010-4f53-9c89-9edc91f110cb.png)

图3 错误场景_错误用例4前的用例1可正确执行用例，系统提示解答错误
![image](https://user-images.githubusercontent.com/15624642/216078166-f3ba11ab-ec08-4935-9f4d-6b8eaaffca44.png)

图4 错误场景_错误用例4后面用例5用户代码正确执行用例，用户结果有输出，系统用例执行结果未输出
![image](https://user-images.githubusercontent.com/15624642/216078675-0cc4d5b3-6b8d-4c86-9c2e-a4a453196f05.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
Hello～感谢反馈，通过核实您所反馈的问题的确存在，我们已经联系负责团队跟进，这可能需要一段时间进行处理，还请您理解。
Github 仓库只用于反馈大家在本站学习过程中遇到的题目和题解内容问题，目前我们会暂时关闭该 issue，如有更多反馈和建议欢迎  [点击这里](https://support.leetcode.cn/hc/request/new/) 提交工单反馈，给您带来的不便敬请谅解。
