### ISSUE TITLE
Missing Test Case - 1071. Greatest Common Divisor of Strings

### ISSUE THREAD

**Issue by varun-s22** [LeetCode-Feedback/LeetCode-Feedback#11417]
#### Your LeetCode username

varuns22

#### Category of the bug
- [X] Missing Test Cases 

#### Description of the bug

In the task  (1071)Greatest Common Divisor of Strings, I approached the question using GCD technique. However there were some edgecases that weren't passing due to the way my implementation worked. Still my code ran and got accepted successfully but was giving wrong answer on a custom testcase generated by me. 

Test Case
str1="ABCAAA"
str2="ABC"

#### Code you used for Submit/Run operation

```
#Greatest Common Divisor of Strings
class Solution:
    @staticmethod
    def gcdOfStrings(str1: str, str2: str) -> str:
        s1, s2 = Counter(str1), Counter(str2)
        for i in range(min(len(str1), len(str2))):
            if str1[i] != str2[i]:
                return ""
        word, length = {}, 0
        for k, v in s1.items():
            if k in s2:
                word[k] = gcd(v, s2[k])
                length += word[k]
        return str1[:length] if len(s1) == len(s2) else ""
```

#### Language used for code

Python3

#### Expected behavior

Details about the approach- I firstly checked that the smaller string is a prefix of the bigger string. If that is not the case the answer doesn't exist. If it is the case, then I calculate GCD of each character and the sum of all such GCDs would be the length of the candidate that divides both the strings. This is the part where the error occurs, I don't double check if candidate*(len(str1)//len(candidate))==str1 same goes for str2. But still the solution passed.

#### Screenshots

<img width="707" alt="Screenshot 2023-02-02 at 03 30 55" src="https://user-images.githubusercontent.com/93476421/216173325-6629ac6d-ec3b-446e-9a07-a5f29be32d09.png">

Failed Custom Test Case

<img width="1440" alt="Screenshot 2023-02-02 at 03 31 54" src="https://user-images.githubusercontent.com/93476421/216173479-6099f780-6fab-4569-90ed-86f82f17352c.png">

Accepted Solution

#### Additional context

Test Case
str1="ABCAAA"
str2="ABC"

[Accepted Submission Link](https://leetcode.com/problems/greatest-common-divisor-of-strings/submissions/889687257/)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
