### ISSUE TITLE
Missing Test Case - 1071. Greatest Common Divisor of Strings

### ISSUE THREAD

**Issue by shivam-iitk** [LeetCode-Feedback/LeetCode-Feedback#11410]
#### Your LeetCode username
shivamiitk

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
There is a missing test case for this question. If we simply add the first letter of the sample test case at the end of that test case then it should return an empty string as correct output unless the test case consists of all same alphabets.

#### Code you used for Submit/Run operation

```
// Greatest Common Divisor of Strings
class Solution {
public:
    string gcdOfStrings(string str1, string str2) {
        int a=str1.size();
        int b=str2.size();
        int c=0;
        if(a>=b)
        for(int i=0;c<a;i++){
            if(i==b)i=0;
            if(str1[c++]!=str2[i])return "";
            cout<<"ok"<<endl;
        }
        else for(int i=0;c<b;i++){
            if(i==a)i=0;
            if(str2[c++]!=str1[i])return "";            
        }
        if(a<b)swap(a,b);
        while(a%b!=0)
        {
            c=a%b;
            a=b;
            b=c;
        }
        return str1.substr(0,b);
    }
};
};
```

#### Language used for code
C++

#### Expected behavior
The code should not have passed all the test cases. When I tried running with an example test case like"ABABABAB" and "ABAB" and then just added another "A" after str1 then I got the wrong output while running as correct answer should be an empty string ("") but my code gives "A" as correct output for the same which was incorrect. The compiler does not have such test case and my code passed all test cases.

#### Screenshots
![Screenshot (20)](https://user-images.githubusercontent.com/75174930/216074187-d152f8cd-a5f3-4758-8581-1cc1ac1d63e4.png)
![Screenshot (19)](https://user-images.githubusercontent.com/75174930/216074207-61d896e0-82d3-435a-99f1-45fa306812a0.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
