### ISSUE TITLE
Missing Test Case - 953. Verifying an Alien Dictionary

### ISSUE THREAD

**Issue by Nov05** [LeetCode-Feedback/LeetCode-Feedback#11425]
#### Your LeetCode username

nov05

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

https://leetcode.com/submissions/detail/889814751/  
This Python solution is accepted; however it shouldn't be.  
 
The following type of test cases are missing.  
e.g.   
["hello","hellob", "helloa"]  
"hlabcdefgijkmnopqrstuvwxyz"  

#### Code you used for Submit/Run operation

```python
class Solution:
    def isAlienSorted(self, words: List[str], order: str) -> bool:
        if len(words)<2: return True
        d = {l:i for i,l in enumerate(order)}
        
        for letters in zip(*words):
            diff = True; o1 = d[letters[0]]
            for l in letters[1:]:
                o2 = d[l]
                if o1>o2:
                    return False
                elif o1==o2:
                    diff = False
                o1 = o2
            if diff: return True
            
        l1 = len(words[0])
        for w in words[1:]:
            l2 = len(w)
            if l1>l2:
                return False
            l1 = l2
        return True
```

#### Language used for code

Python3

#### Expected behavior

https://leetcode.com/submissions/detail/889814751/  
This Python solution should be rejected.    

#### Screenshots

<img src="https://raw.githubusercontent.com/Nov05/pictures/3b38abe6d3e94ca6eda6e912b700dd47155b545b/leetcode/001/2023-02-02%2000_38_32-NVIDIA%20GeForce%20Overlay.jpg">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
