### ISSUE TITLE
Missing Test Case - 953. Verifying an Alien Dictionary

### ISSUE THREAD

**Issue by iamabdulwahidur** [LeetCode-Feedback/LeetCode-Feedback#11424]
#### Your LeetCode username

iamabdulwahidur

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [- ] Missing Test Cases 

#### Description of the bug

For Testcase:- 
words = ["kruw","ha","q"]
order = "zgxlkthsjuoqcpavbfdermiywn"
Java code below(Which is already accepted solution in Leetcode) is failing for this testcase 
Please add this testcase as well.

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean isAlienSorted(String[] words, String order) {
       HashMap<Character,Integer> map=new HashMap<>();  //to store the position of character
        for (int i = 0; i < order.length(); i++) {
            map.put(order.charAt(i),i);
        }
//if words length is 2 then do this
        if(words.length==2){
            char c1 = words[0].charAt(0);
            char c2 = words[1].charAt(0);
            if(map.get(c1)>map.get(c2)){
                return false;
            }else if(map.get(c1)<map.get(c2)){
                return true;
            }
        }
//For words length >2
//Converting the word in words into numeric String after getting the position of character in map(Order)
        int index=0;
        String[] str =new String[words.length];
        for (int i = 0; i < words.length; i++) {
            String word = words[i];
            String numericWord="";
            for (int j = 0; j < word.length(); j++) {
                numericWord=numericWord+map.get(word.charAt(j));
            }
            str[index++]=numericWord;
        }
        String[] strCopy =new String[words.length];
        System.arraycopy(str,0,strCopy,0,str.length);  //making copy of array

        Arrays.sort(strCopy);  //sorting the copied arrray
        return Arrays.equals(str,strCopy);   //if they are equal then return true
    }
}
```

#### Language used for code
 JAVA

#### Expected behavior

My solution submitted should have been rejected. but it got accepted.

#### Additional context

Add that testcase mentioned above in Description of the bug

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
