### ISSUE TITLE
Solutions able to modify the main function - 23. Merge k Sorted Lists

### ISSUE THREAD

**Issue by Faiz-Sayyed** [LeetCode-Feedback/LeetCode-Feedback#11428]
#### LeetCode username

spfaizali02

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Recently I came across a user's solution for the problem([link](https://leetcode.com/problems/merge-k-sorted-lists/description/)) on leetcode. In the solution the user had modified the leetcode's main function and added his custom main function where he sorted the input and gave that as output without implementing the actual function. Although this wouldn't work for all questions, still this should not be allowed as the users will be able to get their solutions accepted in contests by directly accessing the inputs and without even applying the logic.

#### Code used for Submit/Run operation

```
ofstream ans("user.out");
int main() {
    vector<int> v;
    v.reserve(1e4);
    string s;
    while (getline(cin, s)) {
        s.erase(remove(begin(s), end(s), '['), end(s));
        s.erase(remove(begin(s), end(s), ']'), end(s));
        for (auto &i: s) if (i == ',') i = ' ';
        istringstream iss(s);
        int temp;
        v.clear();
        while (iss >> temp) v.push_back(temp);
        sort(v.begin(), v.end());
        ans << '[';
        for (int i = 0; i < v.size(); ++i) {
            if (i) ans << ',';
            ans << v[i];
        }
        ans << "]\n";
    }
}
#define main deleted_main
class Solution {
public:
    ListNode* mergeKLists(vector<ListNode*>& lists) {
        return nullptr;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Using the statement '#define main deleted_main' the name of leetcode's main function was changed and the user created his own main function to directly access the inputs and give the output and this submission was accepted.

#### Screenshots

<img width="690" alt="Leetcode Bug" src="https://user-images.githubusercontent.com/87848633/216306344-71e40fc6-7635-47e1-9634-7c7163c1a87d.png">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've used your feedback to check the problem.

We redirected it to our developers team but it will take time to fix.

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!
