### ISSUE TITLE
Missing Test Case - 929. Unique Email Addresses

### ISSUE THREAD

**Issue by Ak47-369** [LeetCode-Feedback/LeetCode-Feedback#11426]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
According to the question, my solution should give 3 unique email addresses but when tested on the above test case it gives only 2 unique email addresses . And what I have found after debugging is that after the occurrence of '@' in an email if it finds '+' it just set the plus_occured to true and jumps to the next iteration but it should push '+' into temp string because '+' is valid in the domain name.
Only local name characters after '+' are not considered.
So According to the above test case 3 unique email addresses  should be
1. test.email+alex@leetcode.com -> testemail@leetcode.com
2. test.e.mail+bob.cathy@leet+code.com ->  testemail@leet+code.com
3. testemail+david@lee.tcode.com ->  testemail@lee.tcode.com

But my solution giving 2 unique emails 
1. test.email+alex@leetcode.com -> testemail@leetcode.com
2. test.e.mail+bob.cathy@leet+code.com ->  testemail@leetcode.com
3. testemail+david@lee.tcode.com ->  testemail@lee.tcode.com

#### Code you used for Submit/Run operation
```
// Unique Email

class Solution {
public:
    int numUniqueEmails(vector<string>& emails) 
    {
        string temp;
        bool plus_occured;
        bool at_rate_occured;
        int index = 0;

        // Replacing the initial emails according to the rules
        for(string s : emails)
        {
            temp = "";
            plus_occured = false;
            at_rate_occured = false;
            for(char c : s)
            {
                if(c == '@')
                    at_rate_occured = true;
                    
                if(c == '+')
                    plus_occured = true;

                else if(c!= '.' && !plus_occured && !at_rate_occured) // Use if instead of else and the bug will be fixed
                    temp += c;
                
                else if(at_rate_occured)
                    temp += c;

            }
            emails[index++] = temp;
        }

        // finding no. of unique emails
        unordered_map<string,int> email_freq;
        for(string s : emails)
            email_freq[s]++;
        
        return email_freq.size(); // No of unique emails
        
    }
}; 
```

#### Language used for code
C++

#### Expected behavior
My code shouldn't be accepted but it got accepted although it's giving the wrong answer on some test cases I checked on.

#### Screenshots
![image](https://user-images.githubusercontent.com/50803673/216257327-af9cd208-cda2-4000-9843-04c38aa97f73.png)

#### Additional context
If I replace the first else condition with the if condition then only my code would give the correct answer and will pass all the test cases.
i.e else if(c!= '.' && !plus_occured && !at_rate_occured) -> changes to if(c!= '.' && !plus_occured && !at_rate_occured)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

Please write the test case explicitly.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
