### ISSUE TITLE
Missing Test Case - 1491. Average Salary Excluding the Minimum and Maximum Salary

### ISSUE THREAD

**Issue by Z3rio** [LeetCode-Feedback/LeetCode-Feedback#11438]
This issue concerns <https://leetcode.com/problems/average-salary-excluding-the-minimum-and-maximum-salary/>, testcase 3.

#### Your LeetCode username
Z3rio

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
You are supposed to get the average of these numbers.
These numbers add up to 29000, and there are 6 numbers.
Meaning the answer would be 29000 / 6 = 4833.3333.
But then it says `Answers within 10^-5 of the actual answer will be accepted.`, which I atleast interpret as rounding it to the closest 50. Which would be 4800, although it seems like that is not the case either.
However, the testcase says the answer is 4750.

I have tried to take a look at the other solutions, but they dont even seem to even be rounding / getting the correct answer either.

#### Code you used for Submit/Run operation
```cpp
class Solution {
public:
    double average(vector<int>& salary) {
        int len = salary.size();
        int total = 0;

        for (int i = 0; i < len; i++) {
            total = total + salary[i];
        }

        return round(total / len / 50) * 50;
    }
};
```

#### Language used for code
C++

#### Expected behavior
I would expect that the correct answer is 4800.

**Comment by Z3rio** [comment]
Ah sorry, my fault.
I missed the condition `Answers within 10^5 of the actual answer will be accepted`.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discussion section of the problem to see how other users have optimized their codes!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output values.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!
