### ISSUE TITLE
Missing Test Case - 567. Permutation in String

### ISSUE THREAD

**Issue by pashtetus1** [LeetCode-Feedback/LeetCode-Feedback#11433]
#### Your LeetCode username
[gorpave](https://leetcode.com/gorpave/)

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug
i passed all cases but my case breaks my solution  

#### Code you used for Submit/Run operation

[Permutation in String](https://leetcode.com/problems/permutation-in-string)
 ```
 public class Solution {
    public bool CheckInclusion(string s1, string s2) {
        
        var i = 0;
        var sum = 0;
        var targetSum = 0;
        s1 = string.Join("",s1.OrderBy(q=>q));
        var targetLength = s1.Length;
        if (s2.Length<s1.Length)
        {
            return false;
        }
        for (; i< targetLength; i++)
        {
            sum += (int) s2[i];
            targetSum += (int) s1[i];
        }

        if (targetSum == sum)
        {
            return true;
        }

        for (; i< s2.Length; i++)
        {
            sum += (int) (s2[i] - s2[i-targetLength]);
            if (sum == targetSum)
            {
                var subString = s2.Substring(i-targetLength+1, targetLength);
                if (s1 == string.Join("",subString.OrderBy(q=>q)))
                {
                    return true;
                }
                
            }
        }
        return false;
    }
}
  ```
test case
```
s1 = "bc"
s2 = "ad"
```
#### Language used for code
c#

#### Expected behavior

false

#### Screenshots
![image](https://user-images.githubusercontent.com/8481477/216394956-9c14a90c-0b95-4e2e-aef5-6819f9acc5e6.png)
![image](https://user-images.githubusercontent.com/8481477/216395559-aa58707d-2eb6-4a85-a1e7-4451fb7c6e68.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
