### ISSUE TITLE
Issue in https://leetcode.com/problems/design-linked-list/

### ISSUE THREAD

**Issue by Samhithgb** [LeetCode-Feedback/LeetCode-Feedback#1143]
#### Your LeetCode username

peevejobs

#### Category of the bug
- [https://leetcode.com/problems/design-linked-list/] Question
- [https://leetcode.com/submissions/detail/404289787/ ] Solution
- [Python3 ] Language

#### Description of the bug

The test case failing on Submit succeeds when copying on the custom input and "Run code" 

#### Code you used for Submit/Run operation

```
class MyLinkedList:
        
    linkedList = []
    size = 0
      
    def __init__(self):
        """
        Initialize your data structure here.
        """
        

    def get(self, index: int) -> int:
        """
        Get the value of the index-th node in the linked list. If the index is invalid, return -1.
        """
        if index < self.size : 
            return self.linkedList[index] 
        else : 
            return -1 
        

    def addAtHead(self, val: int) -> None:
        """
        Add a node of value val before the first element of the linked list. After the insertion, the new node will be the first node of the linked list.
        """
        self.linkedList.insert(0,val)
        self.size = self.size+1
        

    def addAtTail(self, val: int) -> None:
        """
        Append a node of value val to the last element of the linked list.
        """
        self.linkedList.append(val)
        self.size = self.size+1
        
        

    def addAtIndex(self, index: int, val: int) -> None:
        """
        Add a node of value val before the index-th node in the linked list. If index equals to the length of linked list, the node will be appended to the end of linked list. If index is greater than the length, the node will not be inserted.
        """
        if index < self.size : 
            self.linkedList.insert(index,val)
            self.size = self.size+1
        elif index == self.size : 
            self.linkedList.append(val)
            self.size = self.size+1

    def deleteAtIndex(self, index: int) -> None:
        """
        Delete the index-th node in the linked list, if the index is valid.
        """
        if(index<self.size) : 
            del self.linkedList[index]
            self.size = self.size-1
       
```

#### Language used for code

Python3 

#### Expected behavior

Test case needs to succeed. 

#### Screenshots
On Submitting : 
<img width="1245" alt="Screen Shot 2020-10-04 at 1 01 59 PM" src="https://user-images.githubusercontent.com/11178647/95009741-010a6a00-0642-11eb-82c7-e94b38533783.png">

In the console (Custom input ) 
<img width="1186" alt="Screen Shot 2020-10-04 at 1 01 49 PM" src="https://user-images.githubusercontent.com/11178647/95009742-036cc400-0642-11eb-88b4-a8c3e2bbe889.png">

**Comment by Vikas-Jethwani** [comment]
@Samhithgb 
Change your init method to the below and you will get AC.
```
def __init__(self):
        self.size = 0
        self.linkedList = []
```

LeetCode runs multiple TestCases when you hit submit. So, you need to reinitialize global and class variables.

**Comment by lc-kay** [comment]
@Samhithgb 
Thank you for reaching out to us! The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in this article: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-. Please check it out.

We appreciate your time and support! If you have any other questions, please don't hesitate to let us know.
