### ISSUE TITLE
101. Symmetric Tree AttributeError: 'list' object has no attribute 'val'

### ISSUE THREAD

**Issue by AxelB1011** [LeetCode-Feedback/LeetCode-Feedback#11437]
#### Your LeetCode username
user8967D

#### Category of the bug
- [1 ] Question
- [ ] Solution
- [ 1] Language
- [ ] Missing Test Cases 

#### Description of the bug

TreeNode's type in 1 iteration is both TreeNode and List

#### Code you used for Submit/Run operation

```
#Symmetric Tree

# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
class Solution:
    def isSymmetric(self, root: Optional[TreeNode]) -> bool:
        if not root: return True
        q = collections.deque()
        q.append(root.left)
        q.append(root.right)
        while q:
            a, b = q.popleft(), q.popleft()
            #Brilliant error
            print(type(a))
            print(a.val)
            if not a and not b: continue
            if not a or not b or a.val!=b.val: return False
            q.append([a.left])
            q.append([b.right])
            q.append([a.right])
            q.append([b.left])
        return q.empty()
        
```

#### Language used for code
Python

#### Expected behavior

I was expecting it to treat the TreeNode as a TreeNode, not as both a TreeNode and a list.

<img width="1357" alt="Screenshot 2023-02-02 at 2 48 57 PM" src="https://user-images.githubusercontent.com/64097524/216434912-d3cf0879-d18a-4e3f-be98-8d7b2ed7942c.png">
<img width="1357" alt="Screenshot 2023-02-02 at 2 49 06 PM" src="https://user-images.githubusercontent.com/64097524/216434917-955726d1-c065-42e0-bc45-8e63ec93c33d.png">

#### Screenshots
Added screenshots

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by AxelB1011** [comment]
Hello, 

<img width="1357" alt="Screenshot 2023-02-04 at 6 59 06 PM" src="https://user-images.githubusercontent.com/64097524/216794632-e97e793f-3ab8-4b60-ba1c-47842e918d41.png">

I tried running the same code again and it worked. I think it is fixed now.

Thank you!
