### ISSUE TITLE
Missing Test Case - 953. Verifying an Alien Dictionary

### ISSUE THREAD

**Issue by Akay-Code** [LeetCode-Feedback/LeetCode-Feedback#11432]
#### Your LeetCode username
Akay0_0

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

No such testcase having order different from conventional dictionary order for such a tc where words[i]>words[i+1] and order of words[i][j] has greater value than words[i+1][j]. 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool isAlienSorted(vector<string>& words, string order) {
        char arr[26] ;

        for(int i = 0 ; i<words.size()-1 ; i++){
            int j = 0;
            for(int k = 0 ; k<26 ; k++){
                if(order[k] == words[i][j] && order[k] == words[i+1][j] ){
                    j++;
                }
                else if(order[k] == words[i][j]) break;
                else if(order[k] == words[i+1][j]) return false;
                // if(j>=words[i+1].size()-1 && j<words[i].size()-1) return false;
            }
            // if(words[i].size() > words[i+1].size() && (j==words[i].size() || j==words[i+1].size()) ) return false;
            if(words[i].size() > words[i+1].size()){
                // if (j ==words[i+1].size()-1 && j!=0) return false;
                if(words[i][j] >= words[i+1][j]) return false;
            }
        }
        return true;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Question needs to have testcase where words[i]>words[i+1] and order of words[i][j] has greater value than words[i+1][j]. 

#### Screenshots

![image](https://user-images.githubusercontent.com/93380151/216358627-4fd4a614-25c7-467a-85f5-c1fab806d55f.png)

#### Additional context

Question needs some additional testcases like :-
words =
["quvp","k"]
order =
"qngxlkthsjuocpavbfdermiywz"

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
