### ISSUE TITLE
题目：今日打卡 "1145. 二叉树着色游戏" 用例参数 树的实际节点数 小于 第二个参数 n时  系统题解有误

### ISSUE THREAD

**Issue by leechangqing** [LeetCode-Feedback/LeetCode-Feedback#11447]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
ben-dexiong

**Bug 类型**
- [ ] 题目
- [ x ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
1、题目并未对树的实际节点数 与 参数2的关系有效性做约束声明
2、系统此题目的解题算法有bug；

题目一共有三个输入用例参数【非函数入参】
当输入 第一个用参数树的实际节点数 小于 第二个用例参数 n （代表树上总共有 n 个节点）时
系统题解有误，
如：用例 （详见图2，图3 对比）
[1,2,3,4,5,6,7,8,9,10,11]
51
2
如：用例 详见图6 
[1]
3
1
**你使用的语言**
C++

**你提交或者运行的代码**
```
class Solution {
public:
    bool btreeGameWinningMove(TreeNode* root, int n, int x) {
        vector<int> buffer(3, 0);
        Scan(root, x, buffer);
        int sum = 0;
        for (int i = 0; i < buffer.size(); i++) {
            sum += buffer[i];
        }
        int target = sum / 2 + 1;     // 使用 树实际节点总数 做判断依据
        // int target = n / 2 + 1;      // 使用 入参 n 做判断依据
        bool result = false;
        for (int i = 0; i < buffer.size(); i++) {
            result |= (buffer[i] >= target);
        }
        return result;
    }
private:
    enum SearchType {
        PARENT,
        LEFT_CHILD,
        RIGHT_CHILD,
    };
    void Scan(TreeNode* node, int x, vector<int>& result)
    {
        if (node == nullptr) {
            return;
        }
        if (node->val == x) {
            Scan(node->left, LEFT_CHILD, result);
            Scan(node->right, RIGHT_CHILD, result);
        } else {
            result[PARENT]++;
            Scan(node->left, x, result);
            Scan(node->right, x, result);
        }
    }
    void Scan(TreeNode* node, SearchType type, vector<int>& result)
    {
        if (node == nullptr) {
            return;
        }
        result[type]++;
        Scan(node->left, type, result);
        Scan(node->right, type, result);
    }
};
```
图1，上述代码提交通过
![image](https://user-images.githubusercontent.com/15624642/216641262-102ef07a-b0f7-488f-a5b4-e29a7974548c.png)

**期望行为**
**期望解决方案1**、后台系统在正式执行用例前，完善 "输入树包含的有效节点数" 小于 "入参n" 的等值有效性校验；（便捷首选）
![image](https://user-images.githubusercontent.com/15624642/216639002-e3876f8c-401b-4d49-975f-b64460de719d.png)
系统已对大于场景做了校验
**期望解决方案2**、题目去掉入参n，判断依据按给的树实际节点总数为依据；（最优推荐）
期望解决方案3、题目描述对不连通节点，给出计算方法；

**屏幕截图**
[1,2,3,4,5,6,7,8,9,10,11]
11
2
图2、对比用例_正确参数
![image](https://user-images.githubusercontent.com/15624642/216642431-3150fcbd-f2c2-439e-bdc6-f6109cb49bff.png)

[1,2,3,4,5,6,7,8,9,10,11]
51
2
图3、对比用例_异常参数
![image](https://user-images.githubusercontent.com/15624642/216642385-145f74f2-a93e-4e3a-ae76-d70787e6dcf9.png)

【PS】根据上述两个用例对比猜测官方题解使用了入参N做为判断依据，由此做了以下实验

图4、使用 树实际节点总数 做判断依据
![image](https://user-images.githubusercontent.com/15624642/216643045-01f93916-5f90-4247-b583-516530200396.png)

图5、使用 入参 n 做判断依据
![image](https://user-images.githubusercontent.com/15624642/216643085-cf58298e-3810-4dde-8341-9aac1fa925f0.png)

图6、最后一个验证，
![image](https://user-images.githubusercontent.com/15624642/216643466-7175680d-cdba-4e7a-ac89-5ec50dedafa4.png)
推测系统题解方案——「二号」玩家的成绩 =  (入参N - 红色）才符合上述所有预期结果的值

【PS】应以贪心算法 红蓝最后实际节点数作为判定条件；因此推荐  “期望解决方案2”

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
你好，当前题目已更新，积分奖励已发放，请查收
