### ISSUE TITLE
System Design courses are missing some important data

### ISSUE THREAD

**Issue by shockwang** [LeetCode-Feedback/LeetCode-Feedback#11440]
#### Your LeetCode username

shockwang

#### Category of the bug
- Question

#### Description of the bug

I have bought leetcode System Design course, and when coming to Case Studies, I found that all of the case study videos can be found on another free website. (I am not going to expose it here)

Actually that is OK, because the service leetcode offers is more than just case studies, but additional concepts & design practices. The problem is, when I go to that free website, I found that I can usually get a more detailed system architecture graph that helps me understand the whole architecture better. More importantly, I found a case study that has no architecture graph on leetcode, but do have a detailed architecture on that website, I think this is something cannot ignore.

I suggest leetcode add those missing detailed system architecture graphs into System Design courses, otherwise it can be a very bad user experience trying to learn from that, especially for users like me that found the free website contains more detailed information than the leetcode courses after they have payed.

**Comment by LC-Pam** [comment]
Thanks so much for reaching out here, and for your feedback on this.
 
The author of this course, Sandeep Kaul, or codeKarle, has made some more further exclusive content here beyond these videos, including a full-LC exclusive chapter, 10 new system design problems, 20 new quizzes, and text summaries with graphics to accompany the videos.
 
However, we are so sorry about the experience you have had with this System Design course. 
 
This is LeetCode's first paid additional content launch, so we are open to any feedback you have here regarding making this experience for you more valuable, and what you would like to see here.
