### ISSUE TITLE
Missing Test Case - 953. Verifying an Alien Dictionary

### ISSUE THREAD

**Issue by SaraSaadoun** [LeetCode-Feedback/LeetCode-Feedback#11446]
#### Your LeetCode username

saraHamza

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

This solution was accepted. However, it is not a correct solution.
Submission Link: https://leetcode.com/problems/verifying-an-alien-dictionary/submissions/890656481/
Missing Test Case: 
["hl", "hla", "hl"]
"hlabcdefgijkmnopqrstuvwxyz"

![image](https://user-images.githubusercontent.com/68401001/216599616-1b8a5f42-5d98-43e8-ad46-fc4a70038d40.png)

#### Code you used for Submit/Run operation

```
// Verifying an Alien Dictionary
class Solution {
public:
    bool isAlienSorted(vector<string>& words, string order) {
        //maping their language to ours
        unordered_map <char, char> mp;
        
        for(int i=0; i<26; ++i){
            mp[order[i]] = i+'a';
        }
        
        
        int m = (int)words.size();
        
        //sz of the longest word
        int n = (int)words[0].size();
        
        for(int i=1; i<m; ++i){
            if(words[i].size() > n)
                n = words[i].size(); 
        }

        for(int i=0; i<n; ++i){
            char prev = 'a'-1; 
            bool equal = 0;
            bool firstTime = 1;

            //check at the i-th position
            for(int j=0; j<m; ++j){
                
                if(i >= words[j].size()) {
                    
                    if(firstTime && j != 0)
                        return false;
                    firstTime = 0;
                    continue;
                }

                if(mp[words[j][i]] > prev){
                    prev = mp[words[j][i]];
                }
                else if(mp[words[j][i]] == prev){
                    equal = 1;
                }
                else{
                    return false;
                }
            }
            if(!equal) {
                return true;
            }
            
        }
        return true;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Expected behavior:  This solution should NOT be accepted
https://leetcode.com/problems/verifying-an-alien-dictionary/submissions/890656481/

Actually, it has been accepted because of the absence of this test case.

#### Screenshots

![image](https://user-images.githubusercontent.com/68401001/216600975-6b3ac8f4-d885-4b95-a527-97675fdedf45.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
