### ISSUE TITLE
Missing Test Case - 981. Time Based Key-Value Store

### ISSUE THREAD

**Issue by leoybkim** [LeetCode-Feedback/LeetCode-Feedback#11445]
#### Your LeetCode username

1337-c0d3

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My code submission is accepted but it should have failed
[Question: 981. Time Based Key-Value Store](https://leetcode.com/problems/time-based-key-value-store/description/)

#### Code you used for Submit/Run operation

https://leetcode.com/problems/time-based-key-value-store/submissions/890658243/

```python3
class TimeMap:

    def __init__(self):
        self.dict = defaultdict(list)

    def set(self, key: str, value: str, timestamp: int) -> None:
        self.dict[key].append((timestamp, value))


    def get(self, key: str, timestamp: int) -> str:
        # Value not found or timestamp expired
        if key not in self.dict or timestamp < self.dict[key][0][0]:
            return ''

        # Value is the most recently entered data
        if timestamp >= self.dict[key][-1][0]:
            return self.dict[key][-1][1]

        # Binary search to find a value with the largest timestamp under the given timestamp
        s = 0
        e = len(self.dict[key]) - 1

        while s < e:
            m = (s + e) // 2
            if self.dict[key][m][0] > timestamp:
                e = m - 1
            elif self.dict[key][m][0] < timestamp:
                s = m + 1
            else:
                return self.dict[key][m][1]
        return self.dict[key][m][1]
```

#### Language used for code
Python3

#### Expected behavior

The test case below fails, however my submission was still accepted.

**Input**
```
["TimeMap","set","get","get","set","get","get","set","set","set","set","set","get"]
[[],["foo","bar",1],["foo",1],["foo",3],["foo","bar2",4],["foo",4],["foo",5], ["foo","zigzag",7], ["foo","conundrum",8], ["foo","hyperbole",9], ["foo","silhouette",10], ["foo","blasphemy",11],["foo", 9]]
```
**output**
[null,null,"bar","bar",null,"bar2","bar2",null,null,null,null,null,"silhouette"]

**expected**
[null,null,"bar","bar",null,"bar2","bar2",null,null,null,null,null,"hyperbole"]

#### Additional context

Have a nice day! :bug:

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
