### ISSUE TITLE
5534. 可见点的最大数

### ISSUE THREAD

**Issue by Ijustwantyouhappy** [LeetCode-Feedback/LeetCode-Feedback#1144]
** Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
示例3的数据和图不符，给出的points是[0, 1]，图上实际画的是[1, 0]

**Comment by feiceh** [comment]
[0,1] -> [1,0]，已调整。

**Comment by Ijustwantyouhappy** [comment]
a_run

**Comment by Ijustwantyouhappy** [comment]
修正题干，100积分啊朋友

**Comment by feiceh** [comment]
ID：a_run 给予积分奖励，请查收。
