### ISSUE TITLE
Error in Array Deletions card

### ISSUE THREAD

**Issue by loungesoftware** [LeetCode-Feedback/LeetCode-Feedback#11451]
#### Your LeetCode username
loungesoftware

#### Category of the bug
- [ ] Question
- [ X ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
At the following link, under the heading "Deleting From the Start of an Array", the third paragraph says "Starting from index 0" when it should state "starting from index 1". 
https://leetcode.com/explore/learn/card/fun-with-arrays/526/deleting-items-from-an-array/3246/#:~:text=Starting%20from%20index%200

#### Language used for code
N/A

#### Expected behavior
N/A

#### Screenshots
N/A

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
