### ISSUE TITLE
Missing Test Case - 2091. Removing Minimum and Maximum From Array

### ISSUE THREAD

**Issue by GAURAVKR007** [LeetCode-Feedback/LeetCode-Feedback#11456]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases   

#### Code you used for Submit/Run operation

class Solution2 {
    /**
     * @param nums
     * @return
     */
    public int minimumDeletions(int[] nums) {

        if(nums.length == 1) {
            return 1;
        }
        int min = Integer.MAX_VALUE;
        int max = Integer.MIN_VALUE;

        for(int i = 0;i<nums.length;i++){
            if(min>nums[i]){
                min = nums[i];
            }

            if(max<nums[i]){
                max = nums[i];
            }
        }

        int minIndex = 0;
        int maxIndex = 0;
        for(int i=0;i<nums.length;i++){
            if(min == nums[i]){
                minIndex = i;
            }

            if(max == nums[i]){
                maxIndex = i;
            }
        }

        int n = nums.length;
        int res1 = ((n - minIndex) > minIndex - 0) ? minIndex+1 : n-minIndex;
        int res2 = ((n- maxIndex) > maxIndex - 0) ? maxIndex+1: n-maxIndex;

        if (minIndex <= n/2 && maxIndex <= n/2){
            int res = minIndex > maxIndex ? minIndex+1:maxIndex+1;
            return res;
        } else if(minIndex >= n/2 && maxIndex >= n/2){
            int res = (minIndex < maxIndex) ? res1 : res2   ;
            return res;
        }

        int maximum = (minIndex>maxIndex) ? minIndex : maxIndex;

        if(res1+res2 > maximum){
            if(res1 == n-minIndex && res2 == n-maxIndex){
                int res = (res1 > res2) ? n-minIndex : n-maxIndex;
                return res; 
            }else if(res1 == minIndex+1 && res2 == maxIndex+1) {
                int res = (res1>res2) ? minIndex+1:maxIndex+1;
                return res;
            } else if(res1 == n-minIndex && res2 == maxIndex+1) {
                int res = (res1>res2) ? minIndex+1:n-maxIndex;
                return res;
            }else if(res1 == minIndex+1 && res2 == n-maxIndex) {
                int res = (res1>res2) ? res1:maxIndex+1;
                return res;
            }
        }

        return res2+res1;
    }
}

class Min_max_Removal {
    public static void main(String[] args) {
        Solution2 sol = new Solution2();
        int[] arr = {3,87,45,56,-1,34,43,78,88,54};
        System.out.println(sol.minimumDeletions(arr));
        
    }
}
```

#### Language used for code
<!-- Java -->


#### Expected behavior
<!-- Answer should be 6 -->



#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by GAURAVKR007** [comment]
check it please

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by GAURAVKR007** [comment]
Missing Test Case is this -> int[] arr = {3,87,45,56,-1,34,43,78,88,54};
Code Submission Link -> https://leetcode.com/problems/removing-minimum-and-maximum-from-array/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link, not the problem link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by GAURAVKR007** [comment]
ok Here is my Code Submission link -> https://leetcode.com/problems/removing-minimum-and-maximum-from-array/submissions/891182788/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
