### ISSUE TITLE
Time Complexity and Space Complexity Wrong in OFFICIAL Documentation

### ISSUE THREAD

**Issue by rajas2716** [LeetCode-Feedback/LeetCode-Feedback#11457]
#### Your LeetCode username
 rajas2716

#### Category of the bug
- [ ] Question
- [ * ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

https://leetcode.com/problems/minimum-genetic-mutation/solutions/2631788/minimum-genetic-mutation/
Time Complexity is written as m^n which is correct but in the explanation paragraph it is written as n^m which is wrong

#### Screenshots

<img width="477" alt="image" src="https://user-images.githubusercontent.com/54216784/216762464-3efa9e79-b2e9-43f8-a7c6-0dbf5bb449a4.png">

<img width="483" alt="image" src="https://user-images.githubusercontent.com/54216784/216762498-3090ab31-abf1-408e-92c9-d3362a9061a4.png">

#### Additional context

Quoting lines from the above 2 screenshots where it is wrongly mentioned that time complexity is n^m

Screenshot 1
-> O(nB+m^n ). Converting bank to a set would create a set that takes up O(nB)O(nB)O(nB) space, and then the seen set could grow to n^m (WRONG) size.

Screenshot 2
-> O(nB + m^n * n^2 * m). Converting bank costs O(nB) , then there are n^m (WRONG) states. 

https://leetcode.com/problems/minimum-genetic-mutation/solutions/2631788/minimum-genetic-mutation/
Link to OFFICIAL DOCUMENTATION OF LEETCODE

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
