### ISSUE TITLE
Missing solution in official solutions of 169. Majority Element (selection alg.)

### ISSUE THREAD

**Issue by haibrenner** [LeetCode-Feedback/LeetCode-Feedback#11450]
Hi
So in question 169 Majority Element, there are quite a lot of approaches to the solution in the official solution. Namely, there are 7 different approaches. But only the last one (Boyer-Moore) is capable of actually solving the question in O(1) additional space and O(n) time. All the other approaches are interesting, but they do not reach these bounds. Either they use more space, or more time, or the running time depends on random values.

I wish to suggest another solution which gets these bounds, and is much more well-known than the Boyer-Moore method. Therefore, it is indeed very feasible to come up with this idea during an interview (although implementing it successfully might be tricky).
Approach number 3 uses sorting, but notice that we actually do not need to fully sort the whole array. Instead we just need to know which is the n//2-th element. This is achievable with the selection algorithm (https://en.wikipedia.org/wiki/Selection_algorithm), which indeed can be execute in O(n) time depending on implementation details.

It is just a tiny additional step in thinking of the sorting approach.
The only drawback from the Boyer-Moore approach is that it mixes the input's values (in-place), and the implementation is indeed lengthier. Other than that it is the only approach which gets the best bounds.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The approach is unnecessary especially as it modifies the input.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
