### ISSUE TITLE
Missing Test Case - 6305. Disconnect Path in a Binary Matrix by at Most One Flip

### ISSUE THREAD

**Issue by hubgeter** [LeetCode-Feedback/LeetCode-Feedback#11463]
#### Your LeetCode username

呆呆
jin-ri-bi-xie-bug

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug

[[1,1,1,1,1,1],[1,1,1,1,1,1],[1,1,1,0,0,0],[1,1,0,1,1,1],[1,1,0,1,1,1]]

#### Code you used for Submit/Run operation

```
class Solution:
    def isPossibleToCutPath(self, grid: List[List[int]]) -> bool:
        m, n = len(grid), len(grid[0])
        d = Counter()
        for i in range(m):
            for j in range(n):
                if grid[i][j]:
                    d[i+j] += 1
        for i in range(1, n-1+m-1):
            if d[i] <= 1:
                return True
        return False
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users have optimized their codes!
The code received Wrong Answer: https://leetcode.com/submissions/detail/893562765/
