### ISSUE TITLE
1610. Maximum Number of Visible Points - Missing Test Case

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#1146]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Several solutions are accepted, but fail on the following test case:

[[480620074, 820887242], [50258334, 865788657], [734683760, 557562669], [500302804, 70813633], [827725722, 701958955], [794033622, 111562149], [232262542, 350535835], [885133199, 83126478], [229519950, 431227149], [151021460, 919235932], [813258123, 133782850], [518858688, 559632003], [279421844, 875590886], [390892790, 373098703], [310621945, 953376191], [452838514, 345727859], [756164881, 305380715], [731554414, 754080595], [648858987, 486242523], [17853105, 590345934], [493345576, 688513373], [286882481, 613915498], [242591935, 304731504], [702584222, 289466546], [861897062, 342654441], [363621969, 265617498], [644984372, 797779522], [577798203, 342679692], [490682371, 662384869], [931652712, 276242385], [154101333, 409797221], [905192747, 349143404], [225564439, 425345031], [872457565, 539570944], [191811803, 952962068], [418300009, 792372722], [576906198, 96163023], [111825773, 346120260], [245833511, 467282430], [60337531, 531630252], [897801240, 414091743], [334241673, 363327456], [624413815, 944591610], [738019561, 87525002], [769235344, 935151691], [385280298, 237587982], [108805469, 307501004], [895983202, 118403493], [552975976, 540884062], [412060538, 838603940], [810643500, 401427997], [634502406, 594768886], [137774631, 523355277], [1023683, 102736919], [785071588, 972584553], [429377829, 913271272], [948784482, 55378202], [144530137, 576923324], [925676565, 961052547], [786050972, 198349136], [994032844, 241739942], [806307415, 971931372], [915510010, 311155575], [598929939, 496125472], [497745581, 551577831], [61449072, 443634064], [661734504, 996490579], [192040920, 747728618], [62983920, 748633056], [480326129, 186082867], [184424482, 605156329], [469660329, 387547907], [886587311, 888977387], [359779655, 114381779], [665641052, 824105256], [469622152, 799846566], [610614923, 812654858], [840549174, 686797565], [477032974, 295008597], [969494237, 7840278], [560535635, 958548091], [655511896, 784669992], [363157788, 675700668], [704604552, 792717160], [941997502, 816711466], [22570985, 966140458], [226448701, 237872695], [508559757, 880860281], [838143939, 483377189], [848595459, 212442123], [225088092, 713766781], [360470403, 887204783], [638769169, 618733618], [405121892, 864077235], [289375180, 523271760], [982967350, 967038689]]
336
[528708078, 376315605]

#### Code you used for Submit/Run operation

```
class Solution {
    public int visiblePoints(List<List<Integer>> points, int angle, List<Integer> location) {
        ArrayList<Double> list = new ArrayList<>();
        ArrayList<Double> listCounter = new ArrayList<>();
        int res = 0, count = 0, left = 0;
        for (List<Integer> point : points) {
            if (point.equals(location)) {
                count++;
            } else {
                list.add(getDegree(point, location));
            }
        }
        Collections.sort(list);
        for (int right = 0; right < list.size(); right++) {
            while (list.get(right) - list.get(left) > angle) {
                left++;
            }
            res = Math.max(res, right - left + 1);
        }
        for (double i : list) {
            listCounter.add((i + 180) % 360);
        }

        Collections.sort(listCounter);
        left = 0;
        for (int right = 0; right < listCounter.size(); right++) {
            while (listCounter.get(right) - listCounter.get(left) > angle) {
                left++;
            }
            res = Math.max(res, right - left + 1);
        }
        return res + count;
    }

    public double getDegree(List<Integer> point, List<Integer> location) {
        double deltaX = point.get(0) - location.get(0);
        double deltaY = -(point.get(1) - location.get(1));
        double arc = Math.atan2(deltaY, deltaX);
		arc = arc < 0 ? Math.abs(arc) : 2 * Math.PI - arc;
        return Math.toDegrees(arc);
    }
}
```
```
class Solution {
    public int visiblePoints(List<List<Integer>> points, int angle, List<Integer> location) {
        Map<String,Point> pointsMap = new HashMap<String,Point>();
        int zero = 0;
        //translating to origin
        //getting rid of duplicates (this wasn't really necessary)
        for(List<Integer> point : points) {
            point.set(0,point.get(0)-location.get(0));
            point.set(1,point.get(1)-location.get(1));
            if (point.get(0) == 0 && point.get(1) == 0) {
                zero++;
                continue;
            }
            String key = point.get(0)+"-"+point.get(1);
            if (pointsMap.containsKey(key)) pointsMap.get(key).inc();
            else pointsMap.put(key,new Point(point.get(0),point.get(1),1));
        }
        
        //adding points from 1st, 2nd and 3rd with their angles +360
        //this should take care of answers that involve field of view
        //starting at the 4th quadrant
        List<Point> points2 = new ArrayList<Point>(pointsMap.values());
        List<Point> points3 = new ArrayList<Point>();
        for(Point point : points2) {
            if (point.degree <= 270) {
                Point curr = new Point(point.x,point.y,point.qty);
                curr.degree += 360;
                points3.add(curr);
            }
        }
        points2.addAll(points3);
        
        Collections.sort(points2,(Point a, Point b) -> {
            return Double.compare(a.degree,b.degree);
        });
        
        
        //then just slide through the points
        int max = 0;
        int count = 0;
        int p1 = 0;
        int p2 = 0;
        
        while(p1 < points2.size()) {
            while(p2 < points2.size() && (points2.get(p2).degree - points2.get(p1).degree) <= angle) {
                count += points2.get(p2).qty;
                p2++;
                max = Math.max(max,count);
            }
            count -= points2.get(p1).qty;
            p1++;
        }
        
        
        return max+zero;
    }
}
class Point {
    public int x;
    public int y;
    public int qty;
    public double degree;
    public Point(int x,int y, int qty) {
        this.x=x;
        this.y=y;
        this.qty=qty;
        this.degree = Math.toDegrees(Math.atan2(y,x));
        this.degree = (this.degree + 360.0) % 360.0;
    }
    public void inc() {
        this.qty++;
    }
}
```

#### Language used for code

Java, Java

#### Expected behavior

The solutions should not be accepted since they fail on the test case

#### Additional context

Links to the original solutions:
https://leetcode.com/problems/maximum-number-of-visible-points/discuss/877721/What-is-the-freaking-d-here
https://leetcode.com/problems/maximum-number-of-visible-points/discuss/877821/Java-O(nlogn)-%2B-sliding-window

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
