### ISSUE TITLE
Missing Test Case - 6305. Disconnect Path in a Binary Matrix by at Most One Flip

### ISSUE THREAD

**Issue by Faiz-Sayyed** [LeetCode-Feedback/LeetCode-Feedback#11471]
#### Your LeetCode username

spfaizali02

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The below code got accepted with existing testcases but it should give wrong answer for the test case
[[1,1,1,1],[1,0,0,1],[1,0,1,0],[1,0,1,1],[1,1,1,1]]

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool isPossibleToCutPath(vector<vector<int>>& grid) {
        int n = grid.size(), m = grid[0].size();
        for(int i=0;i<n;i++){
            for(int j=0;j<m;j++){
                cout<<grid[i][j]<<" ";
            }
            cout<<"\n";
        }
        if((n == 2 && m == 1) || (n == 1 && m == 2)){
            return false;
        }
        int i = n-2, j = m-2;
        while(i>=0 && j>=0){
            int one = 0;
            for(int ii = j;ii<m;ii++){
                one += grid[i][ii];
            }
            for(int jj = i+1;jj<n;jj++){
                one += grid[jj][j];
            }
            if(one == 1 || one == 0){
                // cout<<i<<" "<<j;
                return true;
            }
            i--;
            j--;
        }
        while(i>=0){
            int one = 0;
            for(int jj=0;jj<m;jj++){
                one += grid[i][jj];
            }
            if(one == 0 || one == 1){
                return true;
            }
            i--;
        }
        while(j>=0){
            int one = 0;
            for(int ii=0;ii<n;ii++){
                one += grid[ii][j];
            }
            if(one == 0 || one == 1){
                return true;
            }
            j--;
        }
        for(int i=1;i<n;i++){
            if(i<m){
                int k = 0,one = 0;
                for(int j=i;j>=0;j--){
                    one += grid[j][k];
                    k++;
                }
                if(one == 0 || one == 1){
                    return true;
                }
            }
            else{
                break;
            }
        }
        return false;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The code should give wrong answer but was accepted with existing testcases.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

The code shows "Wrong Answer" after the rejudge:https://leetcode.com/submissions/detail/893564556/
 
Under contest [rules](https://leetcode.com/discuss/general-discussion/951105/new-contest-rule-effective-from-december-2020) you will find more details.
 
If the rejudge is executed, LeetCode will rejudge all the submissions that were submitted to the problem by users who were impacted during the contest. The first Accepted submission will be taken as the final result, and the "Wrong Answer/Time Limited Exceeded" submissions made prior to the first "Accepted" submissions will be counted for penalty time.
 
If the submissions that should have been judged as “Wrong Answer” were judged as “Accepted” during the contest for any reason, LeetCode will rejudge all the submissions that got “Accepted” during this contest for the problem.
If the submissions that should have been judged as “Accepted” were judged as “Wrong Answer” during the contest for any reason, LeetCode will rejudge all the submissions that got “Wrong Answer” during this contest for the problem.
If the correct submissions were judged as “Wrong Answer”, and incorrect submissions were judged as “Accepted” during the contest for any reason, LeetCode will rejudge all the submissions that were made during this contest for the problem.
 
We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
