### ISSUE TITLE
Missing Test Case - 2556. Disconnect Path in a Binary Matrix by at Most One Flip

### ISSUE THREAD

**Issue by azamat-zhurtbayev** [LeetCode-Feedback/LeetCode-Feedback#11473]
#### Your LeetCode username

azhurtbayev 

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Additional context

Test case: `[[1,1,1,1,1],[1,1,1,0,0],[1,1,1,1,1],[0,0,1,1,1],[1,1,1,1,1]]`

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by azamat-zhurtbayev** [comment]
@LC-Pam, sure. I'm sorry, that I haven't done it from the beginning.

This test case breaks solutions that are counting non-zero diagonal elements and that are not checking if a cell is reachable from the start point (0,0) and/or a destination point (m-1, n-1) is reachable from the cell.

My source code in Java:
```
class Solution {
    public boolean isPossibleToCutPath(int[][] g) {
        for (int i = 0; i < g.length; i++)
            for (int j = 0; j < g[0].length; j++)
                if (i != 0 || j != 0)
                    g[i][j] &= ((i > 0 ? g[i-1][j] : 0) | (j > 0 ? g[i][j-1] : 0));
        
        int d = g.length + g[0].length - 3;
        for (int i = 1; i <= d; i++) {
            int c = 0;
            for (int j = Math.max(0, i - g.length + 1); j <= Math.min(i, g[0].length-1); j++)
                if (g[i-j][j] > 0) c++;
            if (c <= 1) return true;
        }
        
        return false;
    }
}
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

The code received Wrong Answer after the rejudge: https://leetcode.com/submissions/detail/893565361/
 
Under contest [rules](https://leetcode.com/discuss/general-discussion/951105/new-contest-rule-effective-from-december-2020) you will find more details.
 
If the rejudge is executed, LeetCode will rejudge all the submissions that were submitted to the problem by users who were impacted during the contest. The first Accepted submission will be taken as the final result, and the "Wrong Answer/Time Limited Exceeded" submissions made prior to the first "Accepted" submissions will be counted for penalty time.
 
If the submissions that should have been judged as “Wrong Answer” were judged as “Accepted” during the contest for any reason, LeetCode will rejudge all the submissions that got “Accepted” during this contest for the problem.
If the submissions that should have been judged as “Accepted” were judged as “Wrong Answer” during the contest for any reason, LeetCode will rejudge all the submissions that got “Wrong Answer” during this contest for the problem.
If the correct submissions were judged as “Wrong Answer”, and incorrect submissions were judged as “Accepted” during the contest for any reason, LeetCode will rejudge all the submissions that were made during this contest for the problem.
 
We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
