### ISSUE TITLE
Missing Test Case - 6305. Disconnect Path in a Binary Matrix by at Most One Flip

### ISSUE THREAD

**Issue by cocoZwwang** [LeetCode-Feedback/LeetCode-Feedback#11470]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

With the existing test cases, the output of my code and the system are the same, so my code can ac , but if I add the following test cases, they have different output.
[[1,1,0,1,1,1,1,1,1],[1,1,0,1,1,1,1,1,1],[1,1,1,1,0,1,0,1,1],[1,1,1,1,1,1,0,1,1],[0,0,0,0,0,0,0,1,1],[0,0,0,0,0,0,0,1,1]] 

#### Code you used for Submit/Run operation

```
#include <bits/stdc++.h>
using namespace std;
#define all(x) (x).begin(),(x).end()
#define rep(i,x,y) for(int i=x; i<=y; ++i)
#define pre(i,x,y) for(int i=x; i>=y; --i) 
#define ft first
#define sd second
#define ps push
#define pp pop
#define psk push_back
#define ppk pop_back
#define psf push_front
#define ppf pop_front
#define tp top
#define mt0(a) memset(a,0,sizeof(a));
#define mtf(a) memset(a,-1,sizeof(a));
typedef long long ll;
typedef unsigned long long ull;
typedef pair<int,int> pii;
typedef pair<ll,ll> pll;
class Solution {
public:
    vector<vector<int>> grid;
    vector<vector<int>> vis,low,num;
    int n,m,id=1;
    bool ok=false;
    vector<vector<int>> d={{1,0},{0,1},{-1,0},{0,-1}};
    void dfs(int r, int c, int rp, int cp){
        low[r][c]=num[r][c]=id++;
        for(int i=0;i<4;++i){
            int x=d[i][0]+r, y=d[i][1]+c;
            if(x>=0&&x<n&&y>=0&&y<m&&grid[x][y]){
                if(vis[x][y]==0){
                    vis[x][y]=1;
                    dfs(x,y,r,c);
                    low[r][c]=min(low[r][c],low[x][y]);
                    if((r||c)&&low[x][y]>=num[r][c]) {
                        ok=true;
                    }
                }else if((rp!=r||cp!=c)){
                    low[r][c]=min(low[r][c],num[x][y]);
                }
            } 
        }
    }
    bool isPossibleToCutPath(vector<vector<int>>& _grid) {
        grid=_grid;
        n=grid.size();
        m=grid[0].size(); 
        vis.resize(n);
        low.resize(n);
        num.resize(n);
        for(int i=0;i<n;++i){
            vis[i].resize(m);
            low[i].resize(m);
            num[i].resize(m);
        }
        vis[0][0]=1;
        dfs(0,0,0,0);
        if(vis[n-1][m-1]==0||ok) return true;
        return false;
    }
};
```

#### Language used for code

C++

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

The code shows "Wrong Answer" after the rejudge: https://leetcode.com/submissions/detail/893563428/
 
Under contest [rules](https://leetcode.com/discuss/general-discussion/951105/new-contest-rule-effective-from-december-2020) you will find more details.
 
If the rejudge is executed, LeetCode will rejudge all the submissions that were submitted to the problem by users who were impacted during the contest. The first Accepted submission will be taken as the final result, and the "Wrong Answer/Time Limited Exceeded" submissions made prior to the first "Accepted" submissions will be counted for penalty time.
 
If the submissions that should have been judged as “Wrong Answer” were judged as “Accepted” during the contest for any reason, LeetCode will rejudge all the submissions that got “Accepted” during this contest for the problem.
If the submissions that should have been judged as “Accepted” were judged as “Wrong Answer” during the contest for any reason, LeetCode will rejudge all the submissions that got “Wrong Answer” during this contest for the problem.
If the correct submissions were judged as “Wrong Answer”, and incorrect submissions were judged as “Accepted” during the contest for any reason, LeetCode will rejudge all the submissions that were made during this contest for the problem.
 
We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
