### ISSUE TITLE
Missing tests - 575. Distribute Candies

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1147]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

575. Distribute Candies
https://leetcode.com/problems/distribute-candies/

The following tests fail, for the code given below:

input		Output		Expected
[-3,-2]		2			1
[-3,-1]		2			1
[-3,0]		2			1
[-3,1]		2			1
[-3,2]		2			1
[-3,3]		2			1

#### Code you used for Submit/Run operation

At https://leetcode.com/problems/distribute-candies/discuss/102888/Java-solution-beats-99.07

```
class Solution {
    public int distributeCandies(int[] candies) {
        int[] b = new int[200001];
        int nonEmptyBucketNo = 0;
        for (int i : candies) if (b[i + 100000]++ == 0) nonEmptyBucketNo++;
        return nonEmptyBucketNo;
    }
}
```

#### Language used for code
Java

#### Expected behavior

- Judge must be correct - both solution & test case wise - to fail incorrect answers.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 

The code you provided gets WA. However, I've run your test cases with our official solution and it all gets accepted. Thank you for your time.
