### ISSUE TITLE
Missing Test Case - 2556. Disconnect Path in a Binary Matrix by at Most One Flip

### ISSUE THREAD

**Issue by c1415926** [LeetCode-Feedback/LeetCode-Feedback#11478]
#### Your LeetCode username
user3593Z

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Can get AC but the code is actually not correct.

I can get WA with this test case:
````
[[1,1,1,1],[1,0,0,0],[1,1,1,1],[1,1,1,1]]
````

#### Code you used for Submit/Run operation

AC commit:
https://leetcode.com/problems/disconnect-path-in-a-binary-matrix-by-at-most-one-flip/submissions/891487318/

```
class Solution {
    
    public boolean isPossibleToCutPath(int[][] grid) {
        int n = grid.length;
        int m = grid[0].length;
        int[][] vis = new int[n][m];
        Queue<int[]> q = new LinkedList<>();
        q.offer(new int[] { 0, 0 });
        vis[0][0] = 1;
        boolean found = false;
        while (!q.isEmpty()) {
            int cur[] = q.poll();
            int row = cur[0];
            int col = cur[1];
            if (row < n - 1 && grid[row + 1][col] == 1 && vis[row + 1][col] == 0) {
                q.offer(new int[] { row + 1, col });
                if (row + 1 == n - 1 && col == m - 1)
                    break;
                vis[row + 1][col] = 1;
            }

            if (col < m - 1 && grid[row][col + 1] == 1 && vis[row][col + 1] == 0) {
                q.offer(new int[] { row, col + 1 });
                if (row == n - 1 && col + 1 == m - 1)
                    break;
                vis[row][col + 1] = 1;
            }
            if (q.size() <= 1) {
                found = true;
                break;
            }
        }
        return found;
    }
    
}
```

#### Language used for code
JAVA

#### Expected behavior
Give WA on case:
````
[[1,1,1,1],[1,0,0,0],[1,1,1,1],[1,1,1,1]]
````

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
