### ISSUE TITLE
Missing Constraints - 703. Kth Largest Element in a Stream

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1148]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

703. Kth Largest Element in a Stream
https://leetcode.com/problems/kth-largest-element-in-a-stream/

The constraints are missing:

- What is the range of k?
- What is the range of `length of arr`
- What is the range of `values of arr`
- What is the range of count of `adds` that will be done?
- What is the range of `values of adds`, is it the same as `arr`?

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JavaScript

#### Expected behavior
- I got a Time Limit Error for this 3 months back, looks like the number of adds is 31277, LC should take responsibility for these TLE errors as it missed to provide the constraints beforehand, LC should revert my TLE from my submission if possible, but didn't do till now for all the TLE errors bugs I raised.
- This is an Easy question, but a heap implementation gets a Time Limit Error, so constraints must specify all constraints in the description given above, in addition to what is already given in "Note".

**Comment by manoharreddyporeddy** [comment]
With great difficulty, I have solved the problem using self-balancing BST (Constraints confused me, and I went into a different direction than Heap)

Along with constraints issue:
- Also understand that many are not understanding it, see below link:
- https://leetcode.com/problems/kth-largest-element-in-a-stream/discuss/171965/Unable-to-interpret-question!
  - Use the below details to detail-reword it:
  - https://leetcode.com/problems/kth-largest-element-in-a-stream/discuss/171965/Unable-to-interpret-question!/180424

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
