### ISSUE TITLE
Missing Constraints - 581. Shortest Unsorted Continuous Subarray

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1149]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

581. Shortest Unsorted Continuous Subarray
https://leetcode.com/problems/shortest-unsorted-continuous-subarray/

Missing constraints:
- What is the range of values of "nums" array?
is it `-3000 < nums[i] < 3000`?

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JavaScript

#### Expected behavior

- The upvotes for the question is 3093 vs 163 downvotes, but the Acceptance rate is too low at 31.2% (5th from the bottom for Easy)
- Reason: Missing "detailed" constraints. If you provide there can be -ve values too, probably % would have been better. Not only some ignore -ve, but also if the algorithm is wrong then the user would have put one more test that would have found it.
Compared to this problem, other problems are much more affected due to Missing  "detailed" constraints.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
