### ISSUE TITLE
More description required

### ISSUE THREAD

**Issue by jaykishanmehta** [LeetCode-Feedback/LeetCode-Feedback#115]
**What kind of the bug**
- [ ] language

**Describe the bug**
I've seen a note "Bonus points if you could solve it both recursively and iteratively." while working on tree chapter. Based on the note I've solve the same problem twice but I didn't receive any extra point.
You can see the same on following link, Note(Link is open based on your progress)
[](https://leetcode.com/explore/learn/card/data-structure-tree/17/solve-problems-recursively/536/)

**what language is your code written in**
JAVA

**Expected behavior**
If there's a note about the points then there should a clear instruction about what steps end user need to perform to achieve those points.

**Screenshots**
![image](https://user-images.githubusercontent.com/5708437/78681237-16f4d780-790a-11ea-8815-30c3e2cd95c2.png)

**Additional context**
Such notes are available while solving many different learning chapters. But due to missing information about the reward not able to get any point till now. Try to check and solve the same.

**Comment by CooperCooperCooper** [comment]
Hi @jaykishanmehta,
Thank you for reaching out to us! I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @jaykishanmehta,
Thank you for your time. We've updated the related note accordingly. You can see the updated on that Explore Card or [here in the problem itself](https://leetcode.com/problems/symmetric-tree/). We appreciate your support.

**Comment by jaykishanmehta** [comment]
It got changed. Not looking good.

But will I receive any LeetCoin as a part of Contribution Missions shown on
the leetcode store https://leetcode.com/store/ ?

Please let me know the detail as well.

Thanks & Regards,
Jaykishan Mehta
- - - - - - - - - - - - - - - - - - - -
Email: jaykishanmehta1991@gmail.com
Mobile: +91-96014-04435
