### ISSUE TITLE
Missing Test Case - 2557. Maximum Number of Integers to Choose From a Range II

### ISSUE THREAD

**Issue by huangshan-01** [LeetCode-Feedback/LeetCode-Feedback#11509]
#### Your LeetCode username
huangshan01

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug
A quite edge case
n == 1
banned == [1]
maxSum == 4 (does not matter)

Coded my binary search, where the return value "ans" is initialized None other than 0. 
In the above case None will be returned.

#### Code you used for Submit/Run operation
```
class Solution:
    def maxCount(self, banned: List[int], n: int, maxSum: int) -> int:
        def check(mid):
            x = bisect_right(banned, mid) - 1
            s = (1 + mid) * mid // 2
            if x >= 0:
                s -= pf[x]
                mid -= x + 1
            return s <= maxSum, mid
            
        banned.sort()
        pf = list(accumulate(banned))

        l = 1
        r = n
        ans = None
        while l < r:
            mid = (l + r + 1) // 2
            res, x = check(mid)
            if res:
                l = mid
                ans = x
            else:
                r = mid - 1
        return ans
```

#### Language used for code
Python 3

#### Expected behavior
Expect 0

#### Screenshots
![image](https://user-images.githubusercontent.com/122117440/216802345-826448a5-8339-45b6-a327-0f0a831cb12e.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
