### ISSUE TITLE
Request - Convert Easy to Medium - 581. Shortest Unsorted Continuous Subarray

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1150]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

581. Shortest Unsorted Continuous Subarray
https://leetcode.com/problems/shortest-unsorted-continuous-subarray/

Would be open to converting this problem difficulty level from Easy to Medium?

Check the below comments and upvotes:

> Great question. I do believe it's more than 'easy'.
	317 upvotes
	https://leetcode.com/problems/shortest-unsorted-continuous-subarray/solution/369591
> This should be at least medium, not easy for sure
	174 upvotes
	https://leetcode.com/problems/shortest-unsorted-continuous-subarray/solution/345586

I generally get Easy to be solved on my 1st attempt, this took 2nd attempt to Pass this, so I am kind of ok with conversion to Medium

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

- User satisfaction will definitely raise by converting this to Medium, the proof of user upvotes is given in the problem description. There is something that is causing many Users to request it as Medium.
Maybe it is just a unique problem, still, it will increase User's satisfaction.

- For whatever reason (question description, constraints, or other), this question has 31.2%, 5th lowest Acceptance rate, which is helping this bug request

- If you believe 491 users can't all be wrong and/or increase User's satisfaction, raise this question difficulty to Medium.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
