### ISSUE TITLE
Missing Test Case - 2556. Disconnect Path in a Binary Matrix by at Most One Flip

### ISSUE THREAD

**Issue by jinnies47** [LeetCode-Feedback/LeetCode-Feedback#11516]
#### Your LeetCode username
jinnies47

#### Category of the bug
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool dfs(int i,int j,vector<vector<int>>& grid,int n,int m,int c)
    {
        if(c>1)
        return 0;
        if(i<0 || j>=m)
        return 1;
        return dfs(i-1,j+1,grid,n,m,c+grid[i][j]);
    }
    bool isPossibleToCutPath(vector<vector<int>>& grid) {
        int n=grid.size(),m=grid[0].size(),i,j;
        if(n+m<=3)
        return 0;
        //checking all columns
        for(i=0;i<n;i++)
        {
            int sum=0;
            for(j=0;j<m;j++)
            sum+=grid[i][j];
            if(sum<=1)
            return 1;
        }
        //checking all rows
        for(j=0;j<m;j++)
        {
            int sum=0;
            for(i=0;i<n;i++)
            sum+=grid[i][j];
            if(sum<=1)
            return 1;
        }
        //checking all diagonals using dfs
        for(i=1;i<n;i++)
        {
            if(dfs(i,0,grid,n,m,0))
            return 1;
        }
        for(j=0;j<m-1;j++)
        {
            if(dfs(n-1,j,grid,n,m,0))
            return 1;
        }
        return 0;
    }
};
```

#### Language used for code
C++ 

#### Expected behavior
If someone only checks the diagonals it gives Accepted verdict there should be a test case that makes sure we check the 
rows and columns as well

#### Screenshots
This test case if it was present then it would have given Wrong Answer when submitted but it gives Accepted
![image](https://user-images.githubusercontent.com/63533609/216807952-e53f7c23-aa87-441e-ba9b-f86cb17a67b7.png)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The test case already exists and is accepted when you ran the code. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
![Screen Shot 2023-02-06 at 2 03 55 PM](https://user-images.githubusercontent.com/103138242/217061956-bcd2e2d4-04ed-4844-8609-67b0af40115b.png)
