### ISSUE TITLE
Missing Test Case - 2560. House Robber IV

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#11514]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets WA on the following testcase:
[9, 1, 3, 2, 10]
2

#### Code you used for Submit/Run operation

```
class Solution:
    def minCapability(self, nums: List[int], k: int) -> int:
        t = [(e, i) for i, e in enumerate(nums)]
        t.sort()
        n = len(nums)
        l, r = 0, n - 1
        
        def check(x):
            e, i = t[x]
            cnt = 1
            j = i + 2
            while j < n:
                if nums[j] <= e:
                    cnt += 1
                    j += 2
                else:
                    j += 1
            j = i - 2
            while j >= 0:
                if nums[j] <= e:
                    cnt += 1
                    j -= 2
                else:
                    j -= 1
            return cnt >= k
        
        while l < r:
            mid = (l + r) // 2
            if check(mid):
                r = mid
            else:
                l = mid + 1
        return t[l][0]
```

#### Language used for code

Python3

#### Expected behavior

Output: 9
Expected: 2

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The test case was rejected to add by the team.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
