### ISSUE TITLE
Missing Test Case - 2561. Rearranging Fruits

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#11510]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets TLE on the following testcase:
[4, 4]
[8, 5]

#### Code you used for Submit/Run operation

```
class Solution:
    def minCost(self, a: List[int], b: List[int]) -> int:
        # 反复交换 使得两个数组元素相等 代价下的
        a.sort()
        b.sort()
        # 相同的先抵消掉，不同的必定要成对
        aa = defaultdict(int)
        bb = defaultdict(int)
        n = len(a)
        for i in range(n):
            aa[a[i]] += 1
            bb[b[i]] += 1

        for k in list(aa.keys()):
            des = min(aa[k], bb.get(k, 0))
            aa[k] -= des
            if aa[k] == 0:
                del aa[k]
            else:
                if aa[k] % 2 != 0:
                    return -1
            if k in bb:
                bb[k] -= des
                if bb[k] == 0:
                    del bb[k]
                elif bb[k] % 2 != 0:
                    return -1

        
        aaa = []
        bbb = []
        for k in aa.keys():
            v = aa[k]
            while v:
                aaa.append(k)
                v -= 2
        for k in bb.keys():
            v = bb[k]
            while v:
                bbb.append(k)
                v -= 2
        assert len(aaa) == len(bbb), 'fuck'
        n = len(aaa)
        res = 0
        fuck = min(a + b) * 2
        for i in range(len(aaa)):
            res += min(aaa[i], bbb[n-i-1], fuck)

        return res     
```

#### Language used for code

Python3

#### Expected behavior

The code gets TLE.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The test case was rejected to add by the team.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by hqztrue** [comment]
Why is this testcase rejected? This code is clearly incorrect, it dealt with the arrays basket1 and basket2 asymmetrically.
