### ISSUE TITLE
Missing Test Case - 2556. Disconnect Path in a Binary Matrix by at Most One Flip

### ISSUE THREAD

**Issue by Ishaan23o** [LeetCode-Feedback/LeetCode-Feedback#11515]
#### Your LeetCode username
ishaan__

#### Category of the bug
- [https://leetcode.com/problems/disconnect-path-in-a-binary-matrix-by-at-most-one-flip/ ] Question
- [https://leetcode.com/contest/biweekly-contest-97/submissions/detail/891380124/ ] Solution
- [ C++] Language
- [ [1,0,1,1],[0,1,1,1],[1,1,1,1],[1,1,1,1]] Missing Test Cases 

#### Description of the bug
Code is wrong when there is a 0 path from left side to top/right side

#### Code you used for Submit/Run operation
class Solution {
public:
    vector<vector<int>>dp[2];
    int n,m;
    vector<vector<int>>vis;
    vector<pair<int,int>>moves={{1,0},{-1,0},{0,1},{0,-1},{1,1},{1,-1},{-1,1},{-1,1}};
    bool dfs(int a,int b,int change,vector<vector<int>>&grid){
        if(a==0||b==m-1)return true;
        if(dp[change][a][b]!=-1)return dp[change][a][b];
        vis[a][b]=1;
        bool ans=false;
        for(auto it:moves){
            if(a+it.first<0||a+it.first>=n||b+it.second<0||b+it.second>=m||(a+it.first==0&&b+it.second==0))continue;
            if(!grid[a+it.first][b+it.second]&&!vis[a+it.first][b+it.second])ans|=dfs(a+it.first,b+it.second,change,grid);
            else if(change==1&&!vis[a+it.first][b+it.second])ans|=dfs(a+it.first,b+it.second,0,grid);
        }
        vis[a][b]=0;
        return dp[change][a][b]=ans;
    }
    bool isPossibleToCutPath(vector<vector<int>>& grid) {
        if(!grid[0][0]||!grid.back().back())return true;
        n=grid.size();m=grid[0].size();
        if(n==1){
            if(m>2)return true;
            else return false;
        }
        dp[0]=vector<vector<int>>(n,vector<int>(m,-1));
        vis=vector<vector<int>>(n,vector<int>(m,0));
        dp[1]=dp[0];
        for(int i=0;i<m-1;i++){
            if(!grid.back()[i]){
                if(dfs(n-1,i,1,grid))return true;
            }else{
                if(dfs(n-1,i,0,grid))return true;
            }
        }
        for(int i=1;i<n;i++){
            if(!grid[i][0]){
                if(dfs(i,0,1,grid))return true;
            }else{
                if(dfs(i,0,0,grid))return true;
            }
        }
        return false;
    }
};

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code
c++

#### Expected behavior
answer came wrong

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Ishaan23o** [comment]
This is the code link of my wrong answer: https://leetcode.com/contest/biweekly-contest-97/submissions/detail/891380124/

This is the code link for the code after I corrected it, the wrong one got accepted during the contest time while this includes the correction:
https://leetcode.com/submissions/detail/891738898/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!
 
The code received wrong answer after the rejudge: https://leetcode.com/submissions/detail/893571816/

Under contest [rules](https://leetcode.com/discuss/general-discussion/951105/new-contest-rule-effective-from-december-2020) you will find more details.
 
If the rejudge is executed, LeetCode will rejudge all the submissions that were submitted to the problem by users who were impacted during the contest. The first Accepted submission will be taken as the final result, and the "Wrong Answer/Time Limited Exceeded" submissions made prior to the first "Accepted" submissions will be counted for penalty time.
 
If the submissions that should have been judged as “Wrong Answer” were judged as “Accepted” during the contest for any reason, LeetCode will rejudge all the submissions that got “Accepted” during this contest for the problem.
If the submissions that should have been judged as “Accepted” were judged as “Wrong Answer” during the contest for any reason, LeetCode will rejudge all the submissions that got “Wrong Answer” during this contest for the problem.
If the correct submissions were judged as “Wrong Answer”, and incorrect submissions were judged as “Accepted” during the contest for any reason, LeetCode will rejudge all the submissions that were made during this contest for the problem.
 
We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
