### ISSUE TITLE
Missing Test Case - 58. Length of Last Word

### ISSUE THREAD

**Issue by Prophet1999** [LeetCode-Feedback/LeetCode-Feedback#11517]
#### Missing test case
- Length of Last Word - Given a string s consisting of words and spaces, return the length of the last word in the string.
A word is a maximal substring consisting of non-space characters only.
- test case - '           '

#### Code you used for Submit/Run operation

```
// length of last word
class Solution {
public:
    int lengthOfLastWord(string s) {
        int i=s.length()-1,count=0;
        while(i>=0 && s[i]==' ')
        i--;
        while(i>=0 && s[i]!=' '){
            count++;
            i--;
        }
        return count;
    }
};
```

#### Language used for code
C++

#### Expected behavior
The test cases containing just spaces seems to be missing.

**Comment by stormsunshine** [comment]
Have you read the constraints? The following is clearly mentioned.

> There will be at least one word in `s`.

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
