### ISSUE TITLE
different result for RUN CODE and SUBMIT - 2558. Take Gifts From the Richest Pile

### ISSUE THREAD

**Issue by akuz0** [LeetCode-Feedback/LeetCode-Feedback#11518]
#### Your LeetCode username
akuz0

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
When i run code in local or run it in contest it work, but not work when i try submit solution

#### Code you used for Submit/Run operation

```
import (
	"math"
	"sort"
)

var array = []float64{}

func sum1(arr []float64) int64 {
	sum := 0
	for _, value := range arr {
		sum += int(value)
	}
	return int64(sum)
}

// 10,8,5,3,2
// [25,64,9,4,100], k = 4
func pickGifts(gifts []int, k int) int64 {
	sum := 0.0
	sort.Slice(gifts, func(i, j int) bool {
		return gifts[i] > gifts[j]
	})

	for i, v := range gifts {
		if i == k-1 {
			array = append(array, float64(v))
			sum = sum + math.Sqrt(float64(v))
			sum = sum + float64(v)
		}

		if i > k-1 {
			array = append(array, float64(v))
			sum = sum + float64(v)
		} else {

			res := math.Sqrt(float64(v))
			if i != 0 {
				array = append(array, res)
				sum = sum + res
			}
		}
	}
	resu := sum1(array)
	return resu
}
```

#### Language used for code
GoLang

#### Expected behavior
Not different result for RUN CODE and SUBMIT 

#### Screenshots
Run Code Status: Finished
For
[1,1,1,1]
4
![image](https://user-images.githubusercontent.com/91601482/216809130-c6402053-bf5f-4986-8fc3-79596383305b.png)

Submission Result: Wrong Answer
![image](https://user-images.githubusercontent.com/91601482/216809160-253ad24c-1a9c-4ca1-b7bd-d3775acb360d.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output values.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!
