### ISSUE TITLE
Missing Test Case - 2556. Disconnect Path in a Binary Matrix by at Most One Flip

### ISSUE THREAD

**Issue by shohosoda** [LeetCode-Feedback/LeetCode-Feedback#11520]
#### Your LeetCode username

hsdsh

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

There are some AC solutions are wrong with this test case. 
[[1, 1, 1, 1, 1, 1, 1],[1, 0, 0, 0, 0, 0, 0],[1, 1, 1, 1, 1, 1, 1],[ 1, 1, 1, 1, 1, 1, 1]]

#### Code you used for Submit/Run operation

```
// C++
class Solution {
public:
    bool isPossibleToCutPath(vector<vector<int>>& grid) {
        int m = grid.size();
        int n = grid[0].size();
        vector<int> count(m + n - 1, 0);
        for(int i = 0; i < m; i++) {
            for(int j = 0; j < n; j++) {
                count[i + j] += grid[i][j];
            }
        }
        for(int i = 1; i < count.size() - 1; i++) {
            if(count[i] <= 1) return true;
        }
        return false;
    }
};
```

#### Language used for code

C++

#### Expected behavior

true is expected. But this AC solution returns false.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
