### ISSUE TITLE
Missing Test Case - 283. Move Zeroes

### ISSUE THREAD

**Issue by nancyyPandya** [LeetCode-Feedback/LeetCode-Feedback#11522]
#### Category of the bug
Given an integer array nums, move all 0's to the end of it while maintaining the relative order of the non-zero elements.

Note that you must do this in-place without making a copy of the array.

'- Swift

#### Code you used for Submit/Run operation

```
//  Move Zeroes
class Solution {
    func moveZeroes(_ nums: inout [Int]) { // 0 1 0 3 12
        var indices  = [Int]()
        var zeroe = 0
        var i = 0


        for num in nums {
            if num == 0 {
              if let idx = nums.index(of:num) {
                nums.remove(at:idx)
                zeroe += 1
              }
            }
        }
      
      while i < zeroe {
        nums.append(0) 
        i += 1
      }        
    }    
}
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've used your feedback to check the problem.

Would you mind telling us the issue of this problem?

We appreciate your support!

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
