### ISSUE TITLE
Missing Test Case - 2556. Disconnect Path in a Binary Matrix by at Most One Flip

### ISSUE THREAD

**Issue by Bonrey** [LeetCode-Feedback/LeetCode-Feedback#11521]
#### Your LeetCode username
miguel_v

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
There is a missing testcase for the problem:
[[1, 1, 0, 0, 1],[1, 1, 1, 0, 0],[1, 1, 0, 1, 1],[0, 0, 0, 0, 1],[1, 1, 1, 1, 1]]

#### Code you used for Submit/Run operation

```
class Solution:
    def isPossibleToCutPath(self, M: list[list[int]]) -> bool:
        m, n = len(M), len(M[0])
        diag = Counter()

        for i in range(m):
            for j in range(n):
                if i + j not in (0, m + n - 2):
                    diag[i + j] += M[i][j]

        return any(c < 2 for c in diag.values())
```

#### Language used for code
Python3

#### Expected behavior

My solution gives the answer `false`, whereas the expected answer is `true`.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
