### ISSUE TITLE
Inconsistent style in linked list questions

### ISSUE THREAD

**Issue by simmonmt** [LeetCode-Feedback/LeetCode-Feedback#11548]
#### Your LeetCode username

simmonmt

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

https://leetcode.com/explore/featured/card/leetcodes-interview-crash-course-data-structures-and-algorithms/704/linked-lists/4597/

All of the linked list questions (or at least the first two) have commented-out code that shows the linked list implementation along with an empty function to be filled out. The commented-out code consistently says `ListNode *` (the `*` is attached to the argument or variable name), while the function to be filled out says `ListNode* ` (the `*` is attached to the type). IMO the latter is better, but either way please be consistent.

```
 *     ListNode *next;
 *     ListNode(int x, ListNode *next) : val(x), next(next) {}
...
    ListNode* deleteDuplicates(ListNode* head) {
```

#### Code you used for Submit/Run operation

n/a

#### Language used for code
C++

#### Expected behavior
Consistent style

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

This is the standardized format for all Linked List/Tree problems across all of LeetCode and is not related to the course.

We will submit your feedback to the team.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by simmonmt** [comment]
Sure, yes, I get that it's the standardized format. My point is that the standardized format is inconsistent. The style used in the comment that shows the ListNode definition is not the same style used in the function prototypes. My apologies for repeating myself, but it's not clear to me whether you understand the point I'm making.

Are you saying that A) you understand that the styles are different, and that's ok? B) you don't see the style inconsistency I'm pointing out?  B) something else?

Just in case my example was too terse, I'll provide a longer one. Here's the comment that shows the ListNode interface:

```
/**
 * Definition for singly-linked list.
 * struct ListNode {
 *     int val;
 *     ListNode *next;
 *     ListNode() : val(0), next(nullptr) {}
 *     ListNode(int x) : val(x), next(nullptr) {}
 *     ListNode(int x, ListNode *next) : val(x), next(next) {}
 * };
 */
```

Note how the pointer types are consistently written as `ListNode` then a space then `*` then the name.

Here's the prototype for the function that I'm meant to implement:

```
    ListNode* middleNode(ListNode* head) {
```

Note how the pointer types are consistently written as `ListNode` then `*` then a space then the name. That is, one says `ListNode* foo` while the other says `ListNode *foo`.
