### ISSUE TITLE
2556 缺少测试用例

### ISSUE THREAD

**Issue by ICE-Bro** [LeetCode-Feedback/LeetCode-Feedback#11559]
**icebro**

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
-  缺少测试用例

**描述**
[2556. 二进制矩阵中翻转最多一次使路径不连通](https://leetcode.cn/problems/disconnect-path-in-a-binary-matrix-by-at-most-one-flip/)错误的代码通过了所有用例，但是我找到了不能通过的样例[[1,1,1,0],[1,1,1,1],[1,0,1,1],[1,0,1,1]]，下面提供的代码会返回false，但是根据题目要求修改一处为[[1,1,1,0],[1,1,0,1],[1,0,1,1],[1,0,1,1]]即可满足，应该为返回true
![2023-02-06_174959](https://user-images.githubusercontent.com/61672532/216939976-77cd1c59-0927-425b-b60e-8a0ad415125a.png)

**你使用的语言**
C++

**你提交或者运行的代码**
```
class Solution {
public:
    bool isPossibleToCutPath(vector<vector<int>>& grid) {
        int n = grid.size(), m = grid[0].size();
        vector<int> vis(n+m, 0);
        for(int i=0;i<n;i++){
            for(int j=0;j<m;j++){
                if(grid[i][j]==0)continue;
                vis[i+j]++;
            }
        }
        for(int i=1;i<n+m-2;i++){
            if(vis[i]<2){
                return true;
            }
        }
        return false;
    }
};
```

**期望行为**
增加测试用例
[[1,1,1,0],[1,1,1,1],[1,0,1,1],[1,0,1,1]]
答案：true

**屏幕截图**
![2023-02-06_174908](https://user-images.githubusercontent.com/61672532/216939806-67171e83-96e7-4aa9-9879-53708e4a9b0c.png)

**Comment by feiceh** [comment]
感谢反馈，当前题目已更新，奖励已发放。
