### ISSUE TITLE
Missing Test Case - 88. Merge Sorted Array

### ISSUE THREAD

**Issue by bozzelliandrea** [LeetCode-Feedback/LeetCode-Feedback#11557]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public void merge(int[] nums1, int m, int[] nums2, int n) {
        
        int last = m + n -1;

        // merge in reverse order
        while(m > 0 && n > 0) {
            if(nums1[m - 1] > nums2[n - 1]) {
                nums1[last] = nums1[m - 1];
                m--;
            } else {
                nums1[last] = nums2[n - 1];
                n--;
            }
            last--;
        }

        // fill remaining of nums2 to nums1
        while(n > 0) {
            nums1[last] = nums2[n - 1];
            n--;
            last--;
        }
    }
};
```

#### Expected behavior

This test case should be added
nums1 = [1,2,3,0,0,0]
m = 3
nums2 = [1,5,6]
n = 3

**Comment by stormsunshine** [comment]
This code returns the correct result for the test case you provided. Why is this test case missing?

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
