### ISSUE TITLE
Missing Test Case - 48. Rotate Image

### ISSUE THREAD

**Issue by nancyyPandya** [LeetCode-Feedback/LeetCode-Feedback#11550]
#### Rotate Image

You are given an n x n 2D matrix representing an image, rotate the image by 90 degrees (clockwise).

You have to rotate the image [in-place](https://en.wikipedia.org/wiki/In-place_algorithm), which means you have to modify the input 2D matrix directly. DO NOT allocate another 2D matrix and do the rotation.

``` 
    func rotate(_ matrix: inout [[Int]]) {
        var lastIndex = matrix.count - 1
        var index = lastIndex 


          for firstI in matrix {
            for column in firstI.reversed() {
                      matrix[lastIndex][index] = column
                      lastIndex -= 1
             }
             index -= 1
             lastIndex = matrix.count - 1
          }
     }

```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

Would you mind telling us the issue of this problem?

We appreciate your support!

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
