### ISSUE TITLE
Missing test cases in Find peak element II

### ISSUE THREAD

**Issue by vanshajsingla** [LeetCode-Feedback/LeetCode-Feedback#11558]
#### Your LeetCode username

IndomitableV

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

This test case should be included . Although my code is accepted but it is not correct as it fails on below test case.
[[10,20,40,50,60],[1,4,2,3,500]]

#### Code you used for Submit/Run operation

```
// find Peak Element II
class Solution {
    private:
     int findPeakElement(vector<int>& nums) {
        ////////////// O(logn)
        int n=nums.size();
        int s=1,e=n-2;
         if(n==1)
            return 0;
        if(nums[0]>nums[1])
            return 0;
        
        while(s<=e)
        {
            int mid=(s+e)/2;
                if(nums[mid]>nums[mid-1]&&nums[mid]>nums[mid+1])
                {
                    cout<<mid;
                    return mid;
                }
                else if(nums[mid]<nums[mid-1]&&nums[mid-1]>nums[mid+1])
                {
                    e=mid-1;
                }
                else 
                    s=mid+1;
        }
            if(nums[n-1]>nums[n-2])
                return n-1;
        return -1;
    }
public:
    vector<int> findPeakGrid(vector<vector<int>>& mat) {
        vector<pair<int,int>>v;
        for(int i=0;i<mat.size();i++)
        {
            int j=findPeakElement(mat[i]);
            cout<<j<<endl;
            v.push_back({i,j});
        }
         for(auto it:v)
        {
            cout<<it.first<<" "<<it.second<<endl;
        }
         pair<int,int>p;
        int maxi=-1;
        for(auto it:v)
        {
            if(mat[it.first][it.second]>maxi)
            {
                maxi=mat[it.first][it.second];
                p.first=it.first;
                p.second=it.second;
            }
        }
        vector<int>ans;
        ans.push_back(p.first);
        ans.push_back(p.second);
        return ans;
    }
};
```

#### Language used for code
 C++ 

#### Expected behavior

Correct output for above test case should be : [0,4]
But, the code results in : [1,4]
But, the code is accepted.

#### Screenshots

![image](https://user-images.githubusercontent.com/72307225/216939544-fa0b2337-a768-4cfa-a979-945156f559fa.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
