### ISSUE TITLE
Missing Test Cases - 20. Valid Parentheses - test case accepted while running but failed during submission

### ISSUE THREAD

**Issue by sachinpanwar** [LeetCode-Feedback/LeetCode-Feedback#11555]
#### Your LeetCode username

sachpan

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The same test case is accepted while running (testing) but failed during submission. 
Test case: ```"{[]}"```

#### Code you used for Submit/Run operation

```
// 20. Valid Parentheses

class Solution:
    stack = []

    def getReversed(self, b) -> str:
        if b == ")":
            return "("
        if b == "}":
            return "{"
        if b == "]":
            return "["

    def isLeft(self, bracket) -> bool:
        return bracket in ["(","{","["]

    def isStackEmpty(self) -> bool:
        return len(self.stack) <= 0

    def isValid(self, s: str) -> bool:
        for b in s:
            if self.isLeft(b):
                self.stack.append(b)
                continue
            
            rev = self.getReversed(b)
            if self.isStackEmpty() or rev != self.stack.pop():
                return False
        
        return self.isStackEmpty()
```

#### Language used for code

Python3

#### Expected behavior

The test case should also pass in submission as well. 

#### Screenshots

Test case accepted while running/testing:
<img width="1127" alt="Screenshot 2023-02-06 at 12 24 12 PM" src="https://user-images.githubusercontent.com/11601385/216903901-f027d59e-b349-49de-acc5-3039b56b1377.png">

Test case failed during submission:
<img width="928" alt="Screenshot 2023-02-06 at 12 25 54 PM" src="https://user-images.githubusercontent.com/11601385/216903533-266415be-dcf4-4bd0-aeec-fc7c27a07f82.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output values.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!

**Comment by sachinpanwar** [comment]
Yes, the issue was because of the cause mentioned in the given article. 
<kbd>
<img width="741" alt="Screenshot 2023-02-11 at 1 36 26 PM" src="https://user-images.githubusercontent.com/11601385/218247670-9418493d-e088-4d2d-a2cc-270a54af39bf.png">
</kbd>

So, problematic code was:
```
class Solution:
    stack = []
```

Solution:
```
class Solution:
    def __init__(self):
        self.stack = []
```
