### ISSUE TITLE
Incorrect test case output for problem

### ISSUE THREAD

**Issue by aliabbasrizvi** [LeetCode-Feedback/LeetCode-Feedback#1155]
#### Your LeetCode username
aliabbasrizvi

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
For [the problem](https://leetcode.com/problems/maximize-distance-to-closest-person) for test case with input [1,0,0,1] the expected output is said to be 1. However correct output is 2 if I understand the problem correctly. Can you please clarify (or fix)?

#### Code you used for Submit/Run operation
NA

#### Language used for code
NA

#### Expected behavior
Expected output for input [1,0,0,1] should be set to 2 and not 1.

#### Screenshots
NA

#### Additional context
NA

**Comment by lc-kay** [comment]
Hi @aliabbasrizvi 

The question though asks for the maximum distance, not the index of the seat. Please refer to the discuss tab https://leetcode.com/problems/maximize-distance-to-closest-person/discuss/?currentPage=1&orderBy=most_relevant&query=test%20case for more explanation from our LeetCode community!
