### ISSUE TITLE
Solution - 1472. Design Browser History

### ISSUE THREAD

**Issue by sourashis59** [LeetCode-Feedback/LeetCode-Feedback#11560]
#### Your LeetCode username

SourashisHeartHacker

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

For the C++ implementation of "Approach 2: Doubly Linked List", in the following function, memory leak is happening as there is no garbage collection in C++:
```
    void visit(string url) {
        // Insert new node 'url' in the right of current node.
        DLLNode* newNode = new DLLNode(url);
        current->next = newNode;
        newNode->prev = current;
        // Make this new node as current node now.
        current = newNode;
    }
```

#### Code you used for Submit/Run operation

BUG FIX:
We should manually deallocate the memory from heap:
```
//*=================================ADDED CODE=================================*//
    //deletes the next nodes after given node
    void deleteNexts(Node *currNode)
    {
        Node *p = currNode->next;
        currNode->next = nullptr;

        while(p)
        {
            Node *temp = p;
            p = p->next;

            delete temp;
        }
    }
//*=================================ADDED CODE=================================*//
    


    void visit(string url) {

//*=================================ADDED CODE=================================*//
        //delete the nodes after current node
        deleteNexts(current);
//*=================================ADDED CODE=================================*//

        // Insert new node 'url' in the right of current node.
        DLLNode* newNode = new DLLNode(url);
        current->next = newNode;
        newNode->prev = current;
        // Make this new node as current node now.
        current = newNode;
    }

```

#### Language used for code
C++

#### Expected behavior

Memory leak is happening int the C++ implementation of "Approach 2: Doubly Linked List". I expect no memory leak!

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

We consider it invalid, such considerations are typically not considered in solving LeetCode problems.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
