### ISSUE TITLE
Submission errors - Jump Game problem

### ISSUE THREAD

**Issue by senthilchandran** [LeetCode-Feedback/LeetCode-Feedback#11566]
It is for Jump Game problem https://leetcode.com/explore/interview/card/google/59/array-and-strings/3053/
Submission detail: https://leetcode.com/submissions/detail/892926673/

Input:
[2,0]

Output:
false

Expected:
true

Why is the expected output true for this input?

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output values.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!
