### ISSUE TITLE
sound quality and general aspect

### ISSUE THREAD

**Issue by dguimard** [LeetCode-Feedback/LeetCode-Feedback#11564]
Dear Team 
i purchased system design course , and i was pretty upset with  ,
The Sound is not good and more effort should be put on that
The diagram should be display in a separate material and better quality , like an architect designer would do, for fast sketching the drawboard is ok at that price we expect far better quality .

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've submitted your feedback to the team. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
