### ISSUE TITLE
Incorrect details in Example 4 - [693. Binary Number with Alternating Bits]

### ISSUE THREAD

**Issue by AjayVV** [LeetCode-Feedback/LeetCode-Feedback#1156]
Example 4 mentions

> Input: n = 2
> Output: true
> Explanation: The binary representation of **10** is: **1010**.

**Comment by lc-kay** [comment]
Hi @AjayVV 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @AjayVV 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
