### ISSUE TITLE
Missing Test Case - 387. First Unique Character in a String

### ISSUE THREAD

**Issue by nancyyPandya** [LeetCode-Feedback/LeetCode-Feedback#11576]
####  First Unique Character in a String
- Given a string s, find the first non-repeating character in it and return its index. If it does not exist, return -1.

```
class Solution {
    func firstUniqChar(_ s: String) -> Int {
      
      var hashDict = sortHash(value: s)
      for (index,val) in s.enumerated() {
           if let count = hashDict[val] {
                  if count == 1 {
                    return index 
                  }
           }
      }
      return -1
    }
  
     func sortHash(value: String) -> [Character: Int]{
       var hashDict =  [Character: Int]()
       var cnt = 1
       for str in value {
       if let _ = hashDict[str] {
           hashDict[str] = cnt + 1
          } else {
          hashDict[str] = cnt
        }
     }
       return hashDict
     } 
}
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've used your feedback to check the problem.

Would you mind telling us the issue of this problem?

We appreciate your support!

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
