### ISSUE TITLE
Missing Test Case - 2556. Disconnect Path in a Binary Matrix by at Most One Flip

### ISSUE THREAD

**Issue by mutsuki105** [LeetCode-Feedback/LeetCode-Feedback#11579]
#### Your LeetCode username

nein1203_unofficial

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

```
grid =
[[1,1,1,0,1],[1,0,1,0,1],[1,1,0,1,1],[0,0,0,1,1],[1,0,0,1,1]]
```

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool isPossibleToCutPath(vector<vector<int>>& grid) {
        int n = grid.size();
        int m = grid[0].size();
        grid[0][0] = grid[n - 1][m - 1] = 1000;
        for (int i = 0; i < n; i++) {
            int cnt = 0;
            for (int j = 0; j < m && i - j >= 0; j++) cnt += grid[i - j][j];
            if (cnt <= 1) return true;
            cnt = 0;
            for (int j = 0; j < m; j++) cnt += grid[i][j];
            if (cnt <= 1) return true;
        }
        for (int j = 0; j < m; j++) {
            int cnt = 0;
            for (int i = 0; i < n; i++) cnt += grid[i][j];
            if (cnt <= 1) return true;
            cnt = 0;
            for (int i = 0; i < n && j + i < m; i++) cnt += grid[n - 1 - i][j + i];
            if (cnt <= 1) return true;
        }
        return false;
    }
};
```

#### Language used for code
C++

#### Expected behavior

Expected
```
true
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!
 
The code received the wrong answer after the rejudge: https://leetcode.com/submissions/detail/893595056/

Under contest [rules](https://leetcode.com/discuss/general-discussion/951105/new-contest-rule-effective-from-december-2020) you will find more details.
 
If the rejudge is executed, LeetCode will rejudge all the submissions that were submitted to the problem by users who were impacted during the contest. The first Accepted submission will be taken as the final result, and the "Wrong Answer/Time Limited Exceeded" submissions made prior to the first "Accepted" submissions will be counted for penalty time.
 
If the submissions that should have been judged as “Wrong Answer” were judged as “Accepted” during the contest for any reason, LeetCode will rejudge all the submissions that got “Accepted” during this contest for the problem.
If the submissions that should have been judged as “Accepted” were judged as “Wrong Answer” during the contest for any reason, LeetCode will rejudge all the submissions that got “Wrong Answer” during this contest for the problem.
If the correct submissions were judged as “Wrong Answer”, and incorrect submissions were judged as “Accepted” during the contest for any reason, LeetCode will rejudge all the submissions that were made during this contest for the problem.
 
We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
