### ISSUE TITLE
TestCase not executing correctly

### ISSUE THREAD

**Issue by puneet-shekhawat** [LeetCode-Feedback/LeetCode-Feedback#11570]
#### Your LeetCode username
puneetshekhawat4111

#### Category of the bug
- Wrong Test Case

#### Description of the bug
Test cases are failing even if the required out and expected output are same for the question

#### Code you used for Submit/Run operation

```

class Solution {
public:
    string convert(string s, int numRows) {
        if(numRows >= s.size())
            return s;
        string ans = "";
        int t = 2*numRows - 2;
        for(int i = 0; i < numRows; i++){
            int j = 0;
            while(j < s.size()){
                ans = ans + s[j+i];
                 if(i != 0 && i != numRows-1 && j+ t-i < s.size()) {
                        ans += s[j+ t-i];
                }
                j += t;
            }
        }
        return ans;
    }
};
```

#### Language used for code
C++ 

#### Expected behavior

Test case should pass

#### Screenshots

https://drive.google.com/file/d/1ISJhCyEXenLXqVQ6dxA1L4gr_y4AQMCM/view?usp=sharing

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem name.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by puneet-shekhawat** [comment]
problem name: "6. Zigzag Conversion"

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly. The code above received Wrong Answer when we submitted it: https://leetcode.com/submissions/detail/894227452/

Please feel free to refer to the discussion section of the problem to see how other users have optimized their codes!
