### ISSUE TITLE
Missing Test Case - 929. Unique Email Addresses

### ISSUE THREAD

**Issue by mortonjack** [LeetCode-Feedback/LeetCode-Feedback#11572]
#### Your LeetCode username
mortonjack

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Allows a common mistake to pass all test cases.

#### Code you used for Submit/Run operation

```c++
// Unique Email Addresses
class Solution {
public:
    string helper(string& s) {
        string res = "";
        bool domain = false;
        for (int i = 0; i < s.length(); i++) {
	    if (s[i] == '.' && !domain) continue;
            if (s[i] == '@') domain = true;
	    if (s[i] == '+') while (i+1 < s.length() && s[i+1] != '@') i++;
	    else res += s[i];
        }
        return res;
    }
	
    int numUniqueEmails(vector<string>& emails) {
        unordered_set<string> unique_emails;
        // Go through each email
        for (auto e: emails) {
                // Convert to “base form”
                string base = helper(e);
                // Store in hash set
                unique_emails.insert(base);
            }
        // Return size of the set
        return unique_emails.size();
    }
};
```

#### Language used for code

C++

#### Expected behavior

If there is a '+' in the local name, everything after it should be ignored. This doesn't apply to the domain name. However, by submitting code that ignores everything after the + in the domain name, you can still pass all test cases.

Proposed test case: `["a@e+c.com", "a@e+c+f.com"]`
Result: Wrong answer.
Output: 1
Expected: 2

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
