### ISSUE TITLE
Example that was deleted needs to be restored - 904. Fruit Into Baskets

### ISSUE THREAD

**Issue by spike** [LeetCode-Feedback/LeetCode-Feedback#11589]
#### Category of the bug
- [ X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Looking at this video on this question from 4 years ago at this particular timestamp:
https://youtu.be/za2YuucS0tw?t=259

The example 4 was removed from the question. Removing that example makes the question very misleading. 

Please restore example 4 into the question. If you want to remove something, remove example 2 or example 3, but not example 4. Example 4 is super important. Thank you. 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

We changed our standards and we have only 2 or 3 test cases.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
