### ISSUE TITLE
Missing Test Case - 904. Fruit Into Baskets

### ISSUE THREAD

**Issue by NarpatAanjana** [LeetCode-Feedback/LeetCode-Feedback#11584]
#### Category of the bug

- [ ] Missing Test Cases 

#### Description of the bug
while you test case [1, 2, 3]
greating error
Invalid Testcase
'fruits' must consist of values from 0 to 2 only

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    int totalFruit(vector<int>& fruits) {
        unordered_map<int, int> basket;
        int left, right;
        
        
        for (left = 0, right = 0; right < fruits.size(); ++right) {
            basket[fruits[right]]++;
            
            if (basket.size() > 2) {
                basket[fruits[left]]--;
                if (basket[fruits[left]] == 0)
                    basket.erase(fruits[left]);
                left++;
            }
        }
        
        return right - left;
    }
};
```

#### Expected behavior
testcase [1, 2, 3]
output =2

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The judger appears to be working correctly.

Please check: 0 <= fruits[i] < fruits.length

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by NarpatAanjana** [comment]
Hello i want to know that can I get the test case contribution points
