### ISSUE TITLE
1604. 警告一小时内使用相同员工卡大于等于三次的人 - 补充测试用例

### ISSUE THREAD

**Issue by huyi1985** [LeetCode-Feedback/LeetCode-Feedback#11583]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
damiaozi

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述**
输入：
```
keyName = ["daniel","daniel","daniel"], 
keyTime = ["00:00","00:10","00:01"]
```

输出：
```
[]
```

解释："daniel" 在第一天的凌晨使用了 2 次员工卡，工作了整整1天，于次日凌晨使用了 1 次员工卡。

**Comment by stormsunshine** [comment]
题目描述说得很清楚，输入参数记录的是员工在**某一天**内使用员工卡的情况，所有的时间都发生在同一天，不存在两天的情况。题目描述也没有说明输入参数一定按时间排序。

所以这个测试用例应该将 "daniel" 返回，而不是返回空列表。

**Comment by feiceh** [comment]
感谢反馈，题目解释了是某一天的数据。
