### ISSUE TITLE
Judge shows Wrong Answer when Output & Expected are same - 1042. Flower Planting With No Adjacent

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1158]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language

#### Description of the bug

https://leetcode.com/problems/flower-planting-with-no-adjacent/
1042. Flower Planting With No Adjacent

Judge says it as Wrong Answer even when the output & expected are the same.

Test cases:

	Your input
	6
	[[6,6]]
	Output                     [1,1,1,1,1,1]
	Expected                   [1,1,1,1,1,1]
	> Wrong Answer

	Your input
	1
	[[1,1]]
	Output                     [1]
	Expected                   [1]
	> Wrong Answer

	Your input
	2
	[[1,1]]
	Output                     [1,1]
	Expected                   [1,1]
	> Wrong Answer

This looks like it is because - a garden has a path to itself.
But the question does not say anything.

Please change
	from
		paths[i] = [x, y] describes the existence of a bidirectional path from garden x to garden y.
	to
		paths[i] = [x, y] describes the existence of a bidirectional path from garden x to garden y, where x != y.

#### Code you used for Submit/Run operation

You can use some dummy code like below, for above test cases:

For example:

For below input:

		6
		[[6,6]]

Code can be:

```
var gardenNoAdj = function (N, paths) {
    return [1,1,1,1,1,1];
};
```

#### Language used for code
JS

#### Expected behavior

- The question must be clear & unambiguous
  - I got 3 Wrong answers for this. Wasted several hours.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. We've updated the problem and validators. We appreciate your support!
