### ISSUE TITLE
Missing Test Case - 45. Jump Game II

### ISSUE THREAD

**Issue by shubhcodegate** [LeetCode-Feedback/LeetCode-Feedback#11594]
#### Your LeetCode username

kmr_shubh

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

question link : https://leetcode.com/problems/jump-game-ii/description/

The test cases "[0,0]" generates "invalid input" even though it satisfies the constraints. either the question need to say "Its always possible to reach the destination" or constraint should mention that that all zeros are not possible. 
And include these test cases too.
[0,0] (ie all [0*] strings)
My solution should have been wrong for the above test cases.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int jump(vector<int>& nums) {
        int ans = 0, r = 0, nxt = nums[0];
        for(int i = 0; i < nums.size(); ++i) {
            if(i > r) {
                ++ans;
                r = nxt;
            }
            nxt = max(nxt, i + nums[i]);
        }
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Constraints and question description should match.

#### Additional context

Please do add "LeetCoins" if this was helpful.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
