### ISSUE TITLE
2023.2.8每日一题提示部分描述有误

### ISSUE THREAD

**Issue by YVVT** [LeetCode-Feedback/LeetCode-Feedback#11596]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
Cool Mir2akhaniiHN

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
根据第5条提示，“每个文件夹名都是 唯一 的”，这意味着`"/a/a"`或`"/a","/b/a"`这样的测试用例不合法，但根据评论区部分用户反馈，确实存在着这样的测试用例，应该改为“每个**路径**都是 唯一 的”。

![image](https://user-images.githubusercontent.com/62426149/217446611-d3e8fd44-0544-4940-8aaf-205b610b682d.png)

![image](https://user-images.githubusercontent.com/62426149/217446654-51612382-faa6-46a6-a772-be7f43cbedd5.png)

**你使用的语言**
C++

**你提交或者运行的代码**
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
        
    }
};
```

**期望行为**
描述你期望的结果

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，当前题目已更新，奖励已发放。
