### ISSUE TITLE
Question description grammar - 475. Heaters

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1159]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

https://leetcode.com/problems/heaters/
475. Heaters

Please changed:
From `warm radius will the same.`
To...... `warm radius will be same.`

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

- The question sometimes is tricky, but incorrect wording makes it undetectable.
- Please do proofreading for the new questions.
- Or, use below:
  - Google Docs - https://docs.google.com/document/u/0/
  - Grammerly extension for chrome - https://chrome.google.com/webstore/detail/grammarly-for-chrome/kbfnbcaeplbcioakkpcpgfkobkghlhen?hl=en

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
