### ISSUE TITLE
Missing Test Case - 593. Valid Square

### ISSUE THREAD

**Issue by godshiva** [LeetCode-Feedback/LeetCode-Feedback#11595]
#### Your LeetCode username
godshiva

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution:
    def validSquare(self, p1, p2, p3, p4):
        
        def cal(A, B):
            return abs(A[0] - B[0]) + abs(A[1] - B[1])
                
        
        d = [cal(p1, p2), cal(p1, p3), cal(p1, p4), cal(p2, p3), cal(p2, p4), cal(p3, p4)]
        d.sort()
        
        return 0 < d[0] == d[1] == d[2] == d[3] and d[4] == d[5]
```

#### Language used for code
Python3

#### Expected behavior
This code should not have passed submit, but no test cases made sure people weren't using Manhattan distance instead of true distance

Here is an example test case which makes it fail:
```
p1 = [0,0]
p2 =[18,20]
p3 = [18,-20]
p4 = [37,-1]
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
