### ISSUE TITLE
Test case incorrect for C++ language: 1871. Jump Game VII

### ISSUE THREAD

**Issue by mingjm3** [LeetCode-Feedback/LeetCode-Feedback#11591]
#### Your LeetCode username

arcgo333

#### Category of the bug
- [x] Question
- [ ] Solution
- [X] Language

#### Description of the bug

The test case is:
`s = "00111011110" minJump = 1 maxJump = 2` occurs
`runtime error: load of value 34, which is not a valid value for type 'bool' (solution.cpp)
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior prog_joined.cpp:40:16` 
when use C++ and dynamic programming method.

And when I debug the code, I found the bool array will be initialed as {true, false, false, false, false, false, false, false, 230, false, false}, the '230' is not bool type.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool canReach(string s, int minJump, int maxJump) {
        int n = s.size();
        if(s[n-1] != '0') {return false;}

        bool dp[n];
        int prefix[n];
        dp[0] = true;
        prefix[0] = 1;

        for(int i=1; i<n; i++) {
            int left = i-maxJump;
            int right = i-minJump;
            
            if(right < 0) {
                dp[i] = false;
                prefix[i] = prefix[i-1];
            }else if(s[i] == '0'){
                left = max(0, left);
                if(prefix[right] - prefix[left] > 0 || dp[left]) {
                    dp[i] = true;
                    prefix[i] = prefix[i-1] + 1;
                }
            }else {
                dp[i] = false;
                prefix[i] = prefix[i-1];
            }
        }

        return dp[n-1];
    }
};
```

#### Language used for code

C++

#### Expected behavior

The bool array should be created as {false, false, false, false, false, false, false, false, false, false, false} rather than {false, false, false, false, false, false, false, false, 230, false, false}

#### Screenshots

<img width="1494" alt="Screenshot 2023-02-07 at 16 38 28" src="https://user-images.githubusercontent.com/54018772/217399299-b37fdf02-7573-47e6-bd65-d2b15ef79ef5.png">

<img width="657" alt="image" src="https://user-images.githubusercontent.com/54018772/217399196-576dc3e5-7474-430f-8c5b-6a239382563d.png">

**Comment by mingjm3** [comment]
Follow up:
I change the code to Java, then all test cases pass, the solution is accepted. So the error only appears in C++.

```
class Solution {
    public boolean canReach(String s, int minJump, int maxJump) {
        int n = s.length();
        if(s.charAt(n-1) != '0') {return false;}

        boolean[] dp = new boolean[n];
        int[] prefix = new int[n];
        dp[0] = true;
        prefix[0] = 1;

        for(int i=1; i<n; i++) {
            int left = i-maxJump;
            int right = i-minJump;
            
            if(right < 0) {
                dp[i] = false;
                prefix[i] = prefix[i-1];
            }else if(s.charAt(i) == '0'){
                left = Math.max(0, left);
                if(prefix[right] - prefix[left] > 0 || dp[left]) {
                    dp[i] = true;
                    prefix[i] = prefix[i-1] + 1;
                }
            }else {
                dp[i] = false;
                prefix[i] = prefix[i-1];
            }
        }

        return dp[n-1];
    }
}

```

<img width="1368" alt="image" src="https://user-images.githubusercontent.com/54018772/217415078-1cd11230-5c0c-447c-a767-7e6b57604ba4.png">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The judger appears to be running correctly.

Please feel free to refer to the debug function or discuss section of the problem to see how other users have optimized their codes!

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
