### ISSUE TITLE
Run Code/Submit returning incorrect value for code (javascript)

### ISSUE THREAD

**Issue by timmliu** [LeetCode-Feedback/LeetCode-Feedback#116]
**What kind of the bug**
- [ ] problem
- [x] solution
- [x] language

**Describe the bug**
I am doing the 30-day challenge. I noticed on the Move Zeroes problem (Week 1 problem 4), both the Run Code and Submit buttons say that my answer is wrong and returns [0,1,0,3,12], but when I run the code in Chrome dev tools or any other javascript or Node repl, the return value is the correct [1,3,12,0,0]. I am not sure if my code actually works as a submission for the problem as a whole but at the very least I know there is something wrong with the evaluation of my code in the first test case.

**what language is your code written in**
Javascript

**The code you submit/run**
```
// Moves Zeroes
var moveZeroes = function(nums) {
  let zeroes = 0
  return nums.reduce((acc, curr) => {
    if (curr === 0) {
      zeroes++
      return acc.concat(curr)
    }
    const target = Math.max(acc.length - zeroes, 0)
    return acc.slice(0, target).concat(curr).concat(acc.slice(target, acc.length))
  }, [])
};
```

**Expected behavior**
I would expect the first test case to pass. 

**Additional context**
Input: [0,1,0,3,12]
Output: [1,3,12,0,0]

**Comment by CooperCooperCooper** [comment]
Hi @timmliu,
Thank you for reaching out to us. If you take a deeper look at the code definition, it states "@return {void} Do not return anything, modify nums in-place instead". Please update your code accordingly. We appreciate your time and support.
