### ISSUE TITLE
Missing Test Case - 144. Binary Tree Preorder Traversal

### ISSUE THREAD

**Issue by Alex78-cyber** [LeetCode-Feedback/LeetCode-Feedback#11608]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

This problem is missing a testcase with node value 0.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<int> preorderTraversal(TreeNode* root) {
        vector<int> preOrder;
        if (!root) { return {}; }
        if (root->val) { preOrder.push_back(root->val); }
        if (root->left) {
            auto rootLeft = preorderTraversal(root->left);
            preOrder.insert(preOrder.end(), rootLeft.begin(), rootLeft.end()); 
        }
        if (root->right) { 
            auto rootRight = preorderTraversal(root->right);
            preOrder.insert(preOrder.end(), rootRight.begin(), rootRight.end());
        }
        return preOrder;
    }
};
```

#### Language used for code
 C++ 

#### Expected behavior

When I submit this solution, it should be 'Wrong Answer' because it fails to pass the testcase [0,null,2,3], but it's 'Accepted' instead. Please add this testcase to the problem. Thanks.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
