### ISSUE TITLE
Question description incorrect wording - 797. All Paths From Source to Target

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1160]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

https://leetcode.com/problems/all-paths-from-source-to-target/
797. All Paths From Source to Target

Question says:
> graph[i] is a list of all nodes j for which the edge (i, j) exists.

- So, j is `list of nodes`, so it is multiple nodes.
- Then how can an "edge" (i,j) exist?, even though j is multiple nodes, it is used as if it is a single node.

This question looks to be written in a hurry. Please reword.

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

- The user should not waste time thinking "Is it just the singular/plural issues? or is there anything tricky here that can fail my submission?"
- Please use standard graph terminology `u, v, w, adjacent list` from Wikipedia, etc. to avoid these issues.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
