### ISSUE TITLE
Wrong tests behaviour (I guess)

### ISSUE THREAD

**Issue by eduard-kolotushin** [LeetCode-Feedback/LeetCode-Feedback#11611]
#### Category of the bug
- [ ] Question
- [ ] Missing Test Cases 

#### Description of the bug
Problem asks to find **distinct** values, however there is the test case with double 0 value. It also expected by futher tests.

#### Code you used for Submit/Run operation

```
Doesn't matter
```

#### Expected behavior
Only one 0 value should be accepted in any quadruplet.

#### Screenshots

![image](https://user-images.githubusercontent.com/26324945/217605765-f2fe4119-0ff9-4fa8-b1f4-5b471ab60159.png)
![image](https://user-images.githubusercontent.com/26324945/217605574-688a6606-bbc4-4a4a-951f-0b34759c9645.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem name.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by eduard-kolotushin** [comment]
Sure, it is [**18. 4Sum**](https://leetcode.com/problems/4sum/).

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discussion section of the problem to see how other users have optimized their codes!
