### ISSUE TITLE
 183. Customers Who Never Order

### ISSUE THREAD

**Issue by vim12345** [LeetCode-Feedback/LeetCode-Feedback#11618]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

select
    Name as Customers
from
    Customers
where
    Id
not in(
    select CustomerId from Orders
);

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
