### ISSUE TITLE
Missing Test Case - 1466. Reorder Routes to Make All Paths Lead to the City Zero

### ISSUE THREAD

**Issue by atrox007** [LeetCode-Feedback/LeetCode-Feedback#11617]
#### Your LeetCode username 

asutosh117

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [Y] Missing Test Cases 

#### Description of the bug

Some testcases are missing from set of testcases. There is one unique big testcase and it should have one smaller version to help users analyze the problem and correct their code without wasting a lot of time figuring what could've have wrong.
Please add the following test case -
n = 6
connections = [[5,0],[5,4],[4,3],[2,3],[2,1]]
expected output = 3

#### Code you used for Submit/Run operation

```
// 1466. Reorder Routes to Make All Paths Lead to the City Zero
// C++ code -- corrected and working code 
class Solution {
public:
   void dfs(int node,unordered_map<int,set<int>>& adj,vector<bool>& vis,int& cnt){
    vis[node] = 1 ;
    for(auto nbr:adj[node]){
        if(!vis[abs(nbr)]){ // nodes are absolute 
            dfs(abs(nbr),adj,vis,cnt) ; // jump to absolute as -ve is ghost node 
            cnt += (nbr > 0) ; // flip child flow path,,, cnt +ve dir edge only 
        }
    }
   }// end of dfs
int minReorder(int n, vector<vector<int>>& connections) {
        // given graph is a tree with reverse direction,,,0 is the root
        // use direction as +ve and -ve node,,, deviation from root-0
        unordered_map<int,set<int>> adj ;
        for(auto k:connections){
            adj[k[0]].insert(k[1]) ; // +ve dir 
            adj[k[1]].insert(-k[0]) ; // -ve dir 
        }
        vector<bool> vis(n,0) ;
        int cnt = 0 ;
        dfs(0,adj,vis,cnt) ; 
        return cnt ;
  }
};
```

#### Language used for code

C++

#### Expected behavior

If my code failed I wanted a smaller or slightly moderate sized test case to analyze the problem.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The test case already exists.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
![Screen Shot 2023-02-10 at 2 16 25 PM](https://user-images.githubusercontent.com/103138242/218178438-703d1443-e7c7-42fa-842c-b7bc1def8b98.png)
