### ISSUE TITLE
Solution - 2306. Naming a Company

### ISSUE THREAD

**Issue by nskybytskyi** [LeetCode-Feedback/LeetCode-Feedback#11615]
#### Your LeetCode username

[nskybytskyi](https://leetcode.com/nskybytskyi/)

#### Category of the bug

- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The [official solution](https://leetcode.com/problems/naming-a-company/solutions/3081799/naming-a-company/) for problem [2306. Naming a Company](https://leetcode.com/problems/naming-a-company/) features an incorrect (loose) complexity analysis.

The official solution has a time complexity of `O(nm * alphabet.length)` instead of `O(nm * alphabet.size^2)`. Let's perform the analysis carefully. A pair of groups of sizes `x` and `y` gets processed in `O(x + y)`. The value of `x` takes part in `O(alphabet.length)` such pairs as the first argument, and `O(alphabet.length)` such pairs as the second argument, for a total of `O(x * alphabet.length)`. Summing up over `x` gives `O(n * alphabet.size)`. 

Another way to look at this is "while a single pair of initials can contain all `n` words, a single word cannot be a part of all `O(alphabet.length^2)` pairs of initials".

The official solution then adds a factor of `O(m)` to account for length. As a side note, this can be avoided if you use sets of hash values instead, but that doesn't happen in the code so let's keep it as is.

#### Code you used for Submit/Run operation

Below is the official solution code in Python3:

```py
class Solution:
    def distinctNames(self, ideas: List[str]) -> int:
        # Group idea by their initials.
        initial_groups = [set() for _ in range(26)]
        for idea in ideas:
            initial_groups[ord(idea[0]) - ord('a')].add(idea[1:])
        
        answer = 0
        # Calculate number of valid names from every pair of groups.
        for i in range(25):
            for j in range(i + 1, 26):
                # Get the number of mutual suffixes.
                num_of_mutual = len(initial_groups[i] & initial_groups[j]) 
                
                # Valid names are only from distinct suffixes in both groups.
                # Since we can swap a with b and swap b with a to create two valid names, multiple answer by 2.
                answer += 2 * (len(initial_groups[i]) - num_of_mutual) * (len(initial_groups[j]) - num_of_mutual)
                
        return answer
```

#### Language used for code

Python 3.

#### Expected behavior

The official solution features a correct (tight) complexity analysis.

#### Screenshots

Below is the complexity analysis of the official solution:

<img width="767" alt="Знімок екрана 2023-02-09 о 07 42 43" src="https://user-images.githubusercontent.com/25816558/217728031-d45bd2f3-3a11-4bca-a1cc-6d29c6a21e98.png">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by nskybytskyi** [comment]
> If you have any other questions or feedback, please don't hesitate to let us know!

It appears that the updated math formatting is a bit off. 
Namely, `O(325⋅n cdotm)` is missing a backslash. It should be `\cdot`.
