### ISSUE TITLE
Incorrect char addistion on valid palindrome problem

### ISSUE THREAD

**Issue by jonathanforhan** [LeetCode-Feedback/LeetCode-Feedback#11614]
#### Your LeetCode username

jonathan_forhan

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Using c++, combining lambdas returns with char ascii operations yields undefined behavior. When I cout the two chars that didn't match it yields -22 and 97 on the "a man in panama" test case (the case in the description). Adding 32 to an ascii char should obviously not yield a negative result. My solution works in gnome terminal with the same test case. 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool isPalindrome(string s) {
        int l_ptr = 0;
        int r_ptr = s.size()-1;

        // lambda to that converts to lowercase or discards char
        auto checkChar = [&](char c) -> char {
            if(c >= 97 && c <= 122) {
                return c;
            } else if(c >= 65 && c <= 90) {
                return (c + 32);
            } else {
                return 0;
            }
        };

        // check to make sure they don't run into each other
        auto checkPos = [&](int prox) -> int {
            if((r_ptr - l_ptr) == prox) return 0;
            else return 1;
        };

        while(1) {
            char l_char, r_char = 0;
            while(l_char == 0 && checkPos(0)) {
                l_char = checkChar(s[l_ptr]);
                l_ptr++;
            }
            while(r_char == 0 && checkPos(0)) {
                r_char = checkChar(s[r_ptr]);
                r_ptr--;
            }
            if(l_char != r_char) {
                cout << (int)l_char << ' ' << r_char << '\n';
                return false;
            } else if(checkPos(1)) {
                break;
            }
            l_ptr++;
            r_ptr--;
        }
        return true;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Expected: True result and solution passed. To accomplish this the ascii values of chars are checked and manipulated.

Actual: failed result with undefined behavior in the form of negative ascii numbers

**Comment by jonathanforhan** [comment]
update: using to tolower() function yields 10 when converting A to lower in lambda

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
