### ISSUE TITLE
22. Generate Parentheses

### ISSUE THREAD

**Issue by lyuchkov** [LeetCode-Feedback/LeetCode-Feedback#11620]
#### Your LeetCode username
wrjrjw

#### Category of the bug
- [ ] Solution
- [ ] Missing Test Cases 

#### Description of the bug

In the decription of problem there is no order constraint. But third testcase says that my solution is not right. But I've checked it with Set. (simple test code will be below)

#### Code you used for Submit/Run operation

Solution

```
//22. Generate Parentheses
import java.util.ArrayList;
import java.util.List;

class Solution {
    public List<String> generateParenthesis(int n) {
        if (n == 1) {
            ArrayList<String> p = new ArrayList<>();
            p.add("()");
            return p;
        } else {
            List<String> strings = generateParenthesis(n - 1);
            List<String> res = new ArrayList<>();
            for (String s :
                    strings) {
                String firstPattern = '(' + s + ')';
                String secondPattern = "()" + s;
                String thirdPattern = s + "()";
                if (secondPattern.equals(thirdPattern)) {
                    res.add(firstPattern);
                    res.add(secondPattern);
                } else {
                    res.add(firstPattern);
                    res.add(secondPattern);
                    res.add(thirdPattern);
                }
            }
            return res;
        }

    }
}
```

#### Language used for code

Java

#### Expected behavior

I wish that testcases in this problem would be not so hardcoded, or, at least, description of problem would contain attention about strict order.

#### Screenshots

This is the result of my code, which compare values from expected field to what my solution return. (Code is in additional context below)
```
New values was added: 0

Process finished with exit code 0
```

#### Additional context

SimpleTest
If my solution is not correct this code will print the not matched strings. In addition I've also added check of set size if I'd write wrong test code.
```
import java.util.*;

public class Main {
    public static void main(String[] args) {
        Solution solution = new Solution();
        List<String> strings = solution.generateParenthesis(4);
        //Array values was copied from expected field from console
        String[] strings1 = {"(((())))", "((()()))", "((())())", "((()))()", "(()(()))", "(()()())", "(()())()", "(())(())", "(())()()", "()((()))", "()(()())", "()(())()", "()()(())", "()()()()"};
        List<String> expected = Arrays.asList(strings1);
        Set<String> set = new HashSet<>(expected);
        int originalSetSize = set.size();
        for (String s:
             strings) {
            if(set.add(s)) System.out.println(s);
        }
        System.out.println("Count of new values: " + (originalSetSize-set.size()));
    }
}


```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, the code is received Wrong Answer: https://leetcode.com/submissions/detail/895538373/ , please feel free to refer to the discuss section of the problem to see how other users have optimized their codes!
