### ISSUE TITLE
199. Binary Tree Right Side View - bug if we don't check that root is not None

### ISSUE THREAD

**Issue by edobrynin-dodo** [LeetCode-Feedback/LeetCode-Feedback#11627]
#### Your LeetCode username
jd2050

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
I have two solutions of the same problem (199 Binary Tree Right Side View) which behave differently, but they should behave the same way. The code of both solutions below.

#### Code you used for Submit/Run operation

Solution 1. It passes all tests successfully.
```
from collections import deque
class Solution:
    def rightSideView(self, root: Optional[TreeNode]) -> List[int]:
        
        if not root:
            return []
        
        ans = []
        queue = deque([root])
        
        while queue:
            current_length = len(queue)
            ans.append(queue[-1].val) # this is the rightmost node for the current level
            
            for _ in range(current_length):
                node = queue.popleft()
                if node.left:
                    queue.append(node.left)
                if node.right:
                    queue.append(node.right)
        
        return ans
```

Solution 2. This solutions fails with Runtime Error.
```
from collections import deque
class Solution:
    def rightSideView(self, root: Optional[TreeNode]) -> List[int]:
        
        # if not root:
        #    return []
        
        ans = []
        queue = deque([root])
        
        while queue:
            current_length = len(queue)
            ans.append(queue[-1].val) # this is the rightmost node for the current level
            
            for _ in range(current_length):
                node = queue.popleft()
                if node.left:
                    queue.append(node.left)
                if node.right:
                    queue.append(node.right)
        
        return ans
```

#### Language used for code
Python3

#### Expected behavior
The only difference between these 2 solutions is that I comment out these 2 lines of code:
```
# if not root:
        #    return []
```

But for this particular test these 2 lines of code shouldn't have any effect, because in this test the root is not None. 

#### Screenshots

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/98310581/217952925-a7ceaa09-6957-4dc6-863f-0faa7aa7b896.png">
<img width="759" alt="image" src="https://user-images.githubusercontent.com/98310581/217952992-d0eee4e1-4039-4ab4-ae4e-4c6411ac24dd.png">

#### Additional context
The code of the solution was copied from [crash course topic](https://leetcode.com/explore/featured/card/leetcodes-interview-crash-course-data-structures-and-algorithms/707/traversals-trees-graphs/4619/).

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

Please check the third test case. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
