### ISSUE TITLE
219. 存在重复元素 II  缺少部分用例，造成提交通過

### ISSUE THREAD

**Issue by Y22wer** [LeetCode-Feedback/LeetCode-Feedback#11628]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**

leetcode-cn.com/u/perry_chen/

**Bug 类型**
- [x] 缺少测试用例

**描述**
缺少部分測試用例，造成我的程式碼能通過測驗

**你使用的语言**
Python3

**你提交或者运行的代码**
```
class Solution:
    def containsNearbyDuplicate(self, nums: List[int], k: int) -> bool:
        start=0
        window=start+k+1 #別人和自己
        lenth=len(nums)
        
        if len(nums)<2:
            return False

        if window >= len(nums):  
            return len(set( nums)) <  lenth
        
        while  window <  lenth:
            for i in range(window,lenth):
                if nums[i] in nums[start+1:window]:
                    return True
                start+=1
                window+=1
            return False
        #有點問題
```

**期望行为**
解題失敗，但卻通過了
缺少部分用例子   nums=[1,1,0,2,3,1] k =1
**屏幕截图**
![image](https://user-images.githubuse
![螢幕擷取畫面 2023-02-10 100134](https://user-images.githubusercontent.com/101504733/217981530-3bc13e65-0df8-4e8e-99d1-7ba731a7b89b.png)
rcontent.com/101504733/217981321-2907221e-8de1-41a5-8217-28825228d9f6.png)

**Comment by feiceh** [comment]
你好，当前题目已更新，积分奖励已发放，请查收
