### ISSUE TITLE
Missing Test Case - 1752. Check if Array Is Sorted and Rotated

### ISSUE THREAD

**Issue by Ayush0520** [LeetCode-Feedback/LeetCode-Feedback#11625]
#### Your LeetCode username

Ayush_0520

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ 10,10,1,4,5,10] Missing Test Cases 

#### Description of the bug

My Solution was accepted for all 105 Test Cases, but it fails for my custom test case, i.e., [10,10,1,4,5,10].

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    public boolean check(int[] nums) {
        int index = 0;
        int arrSize = nums.length;
        for(int i = 1; i < arrSize; i++){
            int number = nums[i];
            index = number >= nums[index] ? i : index;
        }
        int element = nums[index];
        index = (index+1)%arrSize;
        if(element == nums[index]) index++;
        for(int i = 0; i < arrSize-1; i++){
            int curr = nums[(i+index)%arrSize];
            int next = nums[(i+1+index)%arrSize];
            if(curr > next) return false;
        }
        return true;
    }
}
```

#### Language used for code

Java

#### Expected behavior

I expected my solution to fail but instead, my solution was accepted as a valid submission. This is because of the missing test case.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
