### ISSUE TITLE
Incorrect time|space complexity analysis for 583. Delete Operation for Two Strings [Approach 1]

### ISSUE THREAD

**Issue by GauriShankarBadola** [LeetCode-Feedback/LeetCode-Feedback#1162]
#### Your LeetCode username

gaurishankarbadola22

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

In Solution section, Approach 1 for question 583 is based on LCS for recursive naive solution.
The time and space complexity analysis is wrong.

Time complexity : ~O(2<sup>max(m,n)</sup>)~ is wrong and it should be O(2<sup>(m + n)</sup>).
Here, m and n refer to the lengths of s1 and s2 respectively.

Similarly,

Space complexity : ~O(max(m,n))~ is wrong and should be O(m+n). The depth of the recursion tree will go upto (m+n) and not max(m,n).

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
Hi @GauriShankarBadola 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @GauriShankarBadola 
Each recursion step is a move from the state (n, m) into state (n - 1, m - 1). The stop condition is n == 0 or m == 0. Hence the value to be used in the complexity estimations is max(n, m).

**Comment by GauriShankarBadola** [comment]
@lc-kay But that's the best case scenario where both the strings have exact same letters and each recursion would reduce them to n-1 and m-1.
But the worst case scenario is when, both the strings have no letter in common and each recursion will go to *else* case where we are making two calls and only reducing one string by one.

 For ABC, and DEF --> ABC, DE --> BC, DE --> BC, D --> B,D --> B, _ . For this case(worst case), the time complexity is O(2(m + n))
