### ISSUE TITLE
Incomplete Question Description - 232. Implement Queue using Stacks

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1163]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

https://leetcode.com/problems/implement-queue-using-stacks/
232. Implement Queue using Stacks

The following tests throw error, even when the tests follow description given:

	Input:
		["MyQueue" ,"peek" ]
		[[]        ,[]     ]
	Invalid Testcase
		'peek' arguments are invalid: Invalid call to function peek()

	Input:
		["MyQueue" ,"pop" ]
		[[]        ,[]    ]
	Invalid Testcase
		'pop' arguments are invalid: Invalid call to function pop()

Please add the below-like description to the question:

- Peek & Pop operations are always valid, that is, there will always be an element in the queue before peek & pop calls are made.
- If applicable, please also fix issue for https://leetcode.com/problems/implement-stack-using-queues

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

- The question description must be complete. Otherwise, users will have a very hard time creating test cases, as it wastes created tests that take many hours.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints. We appreciate your support!
