### ISSUE TITLE
1208. Get Equal Substrings Within Budget - Test Case 21/37

### ISSUE THREAD

**Issue by PREngineer** [LeetCode-Feedback/LeetCode-Feedback#11630]
**Your LeetCode username**

PREngineer

**Category of the bug**

Solution

**Description of the bug**

s = "krrgw"
t = "zjxss"
maxCost = 19

Output: 1
Expected: 2 <<< ????

There's no way it can be 2 when the first letter takes 15 changes (from k to z going -->) and the second requires 8 (from r to j going <--).

15 + 8 = 23

We don't have 23 as maxCost.  We have 19.

It seems to me like this is working like an array of letters [a-z] and when it reaches either end, it goes back to the other end but that doesn't make sense if we are using the ASCII values. You can't jump from a (97) to z (122) or from z (122) to a (97) like that.  You have to go up or down in the appropriate order.

In order to get 2 you would literally have to go in the order of a to k (jumping mysteriously from z to a) which will take 11 steps instead of 15, then you would have the 8 steps required for r to j.

**Code you used for Submit/Run operation**

```
public class Solution {
    public int EqualSubstring(string s, string t, int maxCost) {
        // to return
        int cost = 0;
        int answer = 0;
        // Same length
        int size = s.Length;

        // Start comparing
        for(int i = 0; i < size; i++){
            // For calculation purposes
            int temp = 0;
                
            // If letters are the same
            if( s[i] == t[i] ){
                answer++;
            }
            // If different, attempt to equalize
            else{
                // Calculate the difference between them
                temp = Math.Abs( (int)s[i] - (int)t[i] );
                
                // If we have enough to do it
                if( temp <= maxCost-cost){
                    cost += temp;
                    answer++;
                }
                // If we don't have enough, stop attempting
                else{
                    i = size;
                }
            }

            Console.WriteLine("Cost: " + cost + ", temp: " + temp + ", answer: " + answer);
        }

        return answer;
    }
}
```

**Language used for code**

C#

**Screenshots**

![1](https://user-images.githubusercontent.com/6334069/217989922-361f12fb-8c26-4800-aa56-34b99de90311.PNG)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

**Comment by PREngineer** [comment]
Thanks, I misunderstood the problem.  I see what I did wrong.
