### ISSUE TITLE
Missing Test Case - 1162. As Far from Land as Possible

### ISSUE THREAD

**Issue by sudhackar** [LeetCode-Feedback/LeetCode-Feedback#11633]
#### Your LeetCode username
[happysings](https://leetcode.com/happysings/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
There seems to be no testcase where the water is a single cell - should return 1
Add this testcase to the list
```
[[1,0,1],[1,1,1],[1,1,1]]
```

#### Code you used for Submit/Run operation

```rust
// As Far from Land as Possible
use std::collections::VecDeque;

impl Solution {
    pub fn max_distance(grid: Vec<Vec<i32>>) -> i32 {
        let n = grid.len();
        assert!(n >= 1 && n == grid[0].len());
        // neighbour's direction in (dx, dy)
        let neigh_dr: Vec<(i32, i32)> = vec![(0, -1), (-1, 0), (0, 1), (1, 0)];
        // closure to enumerate all neighbours
        let neighs = |x: usize, y: usize| {
            neigh_dr
                .iter()
                .map(|(dx, dy)| (x as i32 + dx, y as i32 + dy))
                .filter(|(dx, dy)| *dx >= 0 && *dx < n as i32 && *dy >= 0 && *dy < (n as i32))
                .map(|(dx, dy)| (dx as usize, dy as usize))
                .collect::<Vec<(_, _)>>()
        };
        // queue for BFS
        let mut q = VecDeque::new();
        // visited
        let mut vis = vec![vec![false; n]; n];
        for i in 0..n {
            for j in 0..n {
                // if cell is a water cell and any neigh is a land cell
                if grid[i][j] == 0 && neighs(i, j).iter().any(|(x, y)| grid[*x][*y] == 1) {
                    q.push_back((i, j, 1));
                    vis[i][j] = true;
                }
            }
        }
        let mut ans = i32::MIN;
        while let Some((x, y, d)) = q.pop_front() {
            // iterate over all unvisited neigh and update distance
            neighs(x, y).iter().for_each(|(nx, ny)| {
                if !vis[*nx][*ny] && grid[*nx][*ny] == 0 {
                    vis[*nx][*ny] = true;
                    q.push_back((*nx, *ny, d+1));
                    ans = ans.max(d + 1);
                }
            })
        }
        match ans {
            // No water cell
            i32::MIN => -1,
            x => x
        }
    }
}
```

#### Language used for code
rust

#### Expected behavior
In this test case the expected return value is 1 since only 1 cell water is present. However the code above passes all tests and is Accepted - See [submission](https://leetcode.com/problems/as-far-from-land-as-possible/submissions/895232206/)
My accepted solution returns -1 whereas the correct answer is 1.

#### Screenshots
![image](https://user-images.githubusercontent.com/10460978/218047799-f5b26d77-8377-4790-a20b-3a13e12e6d1d.png)

See my [accepted](https://leetcode.com/problems/as-far-from-land-as-possible/submissions/895232206/) solution failing on this testcase

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
