### ISSUE TITLE
Missing Test Case - 2235. Add Two Integers

### ISSUE THREAD

**Issue by CrazyCow75** [LeetCode-Feedback/LeetCode-Feedback#11637]
#### Your LeetCode username
CrazyCow75

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ O ] Missing Test Cases 

#### Description of the bug

No test case for adding two negatives

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    public int sum(int num1, int num2) {
        return num1 + num2;
    }
}
```

#### Language used for code
Java

#### Expected behavior

Expected a test case to add two negatives, wasn't there

**Comment by stormsunshine** [comment]
There is a test case where num1 = -100 and num2 = -100. Why do you think there is no test case to add two negative integers?

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
