### ISSUE TITLE
Time complexity doubles on removing unnecessary code

### ISSUE THREAD

**Issue by Anmol-Baranwal** [LeetCode-Feedback/LeetCode-Feedback#11638]
#### Your LeetCode username
anmol4coder

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
While solving `120. Triangle` using C++. I followed two approaches:

- 1st approach:

> Submission Link is: [here](https://leetcode.com/problems/triangle/submissions/895278851/)

![6ms Time Complexity](https://user-images.githubusercontent.com/74038190/218115480-09528001-d8e1-431b-8f44-31133ef5a1fa.png)

- 2nd approach

On removing two unnecessary lines, the time complexity doubled from `6ms` to `12ms`, and the memory increased by `.1mb`:
```
int m= triangle[0].size();
```

> Submission Link is: [here](https://leetcode.com/problems/triangle/submissions/895279197/)

![12ms Time Complexity](https://user-images.githubusercontent.com/74038190/218116207-9e571fe3-6a51-4261-9cea-c383094f46bd.png)

#### Code you used for Submit/Run operation

```
class Solution {
private:
    int sol(int i, int j, vector<vector<int>>& dp, vector<vector<int>>& triangle){
        int n= triangle.size();
        int m= triangle[0].size();
        if(i==n-1)  return triangle[n-1][j];

        if(dp[i][j] != -1)  return dp[i][j];
        int down= triangle[i][j] + sol(i+1, j, dp, triangle);
        int diag= triangle[i][j] + sol(i+1, j+1, dp, triangle);

        return dp[i][j]= min(down, diag);
    }
public:
    int minimumTotal(vector<vector<int>>& triangle) {
        int n= triangle.size();
        int m= triangle[0].size();
        vector<vector<int>> dp(n, vector<int>(n, -1));  // n*n vector
        return sol(0, 0, dp, triangle);
    }
};
```

#### Language used for code
C++

#### Expected behavior
How can removing two unnecessary lines make any solution run twice as long as before? While the time complexity can be the same, it should take up less space.

#### Screenshots

1st solution:
![6ms Time Complexity](https://user-images.githubusercontent.com/74038190/218115480-09528001-d8e1-431b-8f44-31133ef5a1fa.png)

2nd Solution:
![12ms Time Complexity](https://user-images.githubusercontent.com/74038190/218116207-9e571fe3-6a51-4261-9cea-c383094f46bd.png)

#### Additional context
This is strange, and while I'm not sure if it's a problem, I felt raising an issue would be appropriate.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
