### ISSUE TITLE
189. Rotate Array. Gives wrong output

### ISSUE THREAD

**Issue by J0han0stling** [LeetCode-Feedback/LeetCode-Feedback#11639]
#### Category of the bug
Wrong output
 

#### Description of the bug
According to leetcode my code outputs [1,2,3,4,5,6,7] but when I run it in VScode it gives me the correct output which is [5,6,7,1,2,3,4]

#### Code you used for Submit/Run operation

```
class Solution(object):
   def rotate(self, nums, k):
        for i in range(k):
            nums = [0] + nums
            first = nums[0]
            last = nums[len(nums)-1]
            nums[0] = last
            nums[len(nums)-1] = first
            nums.pop(len(nums)-1)
            print(nums, "test2", i)
```

#### Screenshots

![image](https://user-images.githubusercontent.com/94536718/218124391-c5894af9-adac-4eb4-bf42-d91c2ab718ff.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
