### ISSUE TITLE
Wrong Test Cases used to verify solution - 287. Find the Duplicate Number

### ISSUE THREAD

**Issue by Niraj2003** [LeetCode-Feedback/LeetCode-Feedback#11636]
#### Your LeetCode username

Niraj03
https://leetcode.com/Niraj03/

#### Category of the bug
- [ ] Checking Wrong Test Cases 

#### Description of the bug
Wrong Test Cases used to verify solution.
In constraints of question description there is strictly mentioned that "All the integers in nums appear only once except for precisely one integer which appears two or more times." But after submitting leetcode is checking solution for nums = [2,2,2,2,2]. 

#### Code you used for Submit/Run operation

```
//287. Find the Duplicate Number
class Solution {
public:
    int findDuplicate(vector<int>& nums) {
        int n = nums.size()-1;
        int p = (n * (n+1) )/ 2;
        int q = accumulate(nums.begin(),nums.end(),0);
        return q-p;
    }
};
```

#### Language used for code 
C++

#### Expected behavior
Above code correct for the constraints which are mentioned in question description

#### Screenshots
![image](https://user-images.githubusercontent.com/90129030/218096514-66c5b4bc-8a23-49db-9754-9e15af0fa3c6.png)

**Comment by stormsunshine** [comment]
The integer 2 appears five times. Why do you think this test case is false?

**Comment by Niraj2003** [comment]
Closing Issue
