### ISSUE TITLE
Missing Test Case - 71. Simplify Path

### ISSUE THREAD

**Issue by abhay1704** [LeetCode-Feedback/LeetCode-Feedback#11641]
#### Your LeetCode username

abhay1704

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ O] Missing Test Cases 

#### Description of the bug

for path="/a//b.."
where ``..`` is included in the name of the directory itself and the path is not ended with '/'.
Here, my code failed on this test case but still got accepted upon submission.

#### Code you used for Submit/Run operation

```

class Solution {
public:
  string simplifyPath(string path)
{
    stack<string> stak;
    string tmp;
    int i = 0;
    while (path[i] == '/')
        i++;
    int n = path.size();
    while (i < n)
    {
        if (path[i] == '/')
        {
            if ( path[i - 1] == '.' && path[i - 2] == '/')
                tmp="";
            else if ( path[i - 1] == '.' && path[i - 2] == '.' && path[i-3]=='/')
            {
                if(!stak.empty()){
                    stak.pop();
                }
                tmp = "";
            }
            else if (path[i - 1] != '/')
            {
                stak.push(tmp);
                tmp = "";
            }
        }
        else
        {
            tmp += path[i];
        }
        i++;
    }
    if (path[n - 1] != '/')
    {
        if(path[n-1]=='.' && (n<2 || path[n-2]=='/'));
        else if (path[n - 1] == '.' && (n >= 2 && path[n - 2] == '.') && (n >= 3 && path[n - 3] != '.'))
            {
           if (!stak.empty())
            {
                stak.pop();
            }
            }
        else
        stak.push(tmp);
    }
    stack<string> tmpStk;
    while (!stak.empty())
    {
        tmpStk.push(stak.top());
        stak.pop();
    }

    tmp = "/";
    string res;
    while (!tmpStk.empty())
    {
        res = res + tmp + tmpStk.top();
        tmpStk.pop();
    }

    if(res == "")
        res="/";
    return res;
}
};
```

#### Language used for code

C++

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
