### ISSUE TITLE
2335. 装满杯子需要的最短总时长题解公式更正

### ISSUE THREAD

**Issue by mantoufan** [LeetCode-Feedback/LeetCode-Feedback#11645]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
mantoufan

**Bug 类型**
- [ ] 题目
- [x] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
[官方题解](https://leetcode.cn/problems/minimum-amount-of-time-to-fill-cups/solution/zhuang-man-bei-zi-xu-yao-de-zui-duan-zon-c7y4/)图中红点标注的 `t` 应更正为 `t/2`
![image](https://user-images.githubusercontent.com/4961543/218234289-bde29acf-d555-4375-bb7d-185a2d2afa0e.png)

**Comment by feiceh** [comment]
感谢反馈，经过与负责团队沟通确认，当前题解公示显示正常，祝您在力扣学习生活愉快。
