### ISSUE TITLE
10. Regular Expression Matching - C++ checker bug. Impossible to get accepted

### ISSUE THREAD

**Issue by BrycePy** [LeetCode-Feedback/LeetCode-Feedback#11642]
#### Your LeetCode username
MinitWolf

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
I spent hours trying to speed up my algorithm so I stop getting the "Time limit exceeded" but I couldn't so I start to doubt the checker. I reset the code back to default then just do `return false;` and test with `p = "a*a*a*a*a*a*a*a*a*a*a*a*a*"` and `s = "aaaaaaaaaaaaaaaaaaab"`. and run the test cases. I would expect the code to finish instantly but no, I still get "Time limit exceeded" instead of "wrong answer". please fix and maybe also reset my submission.

#### Code you used for Submit/Run operation

```cpp
class Solution {
public:
    bool isMatch(string s, string p) {
        return false;
    }
};
```

#### Language used for code
C++

#### Expected behavior
Checker itself should be able to run the case within the time limit and does not cause the submission to get "Time limit exceeded".

#### Screenshots

![image](https://user-images.githubusercontent.com/91750004/218166499-f6f1c00f-e1a0-4cb4-b5c2-0bd89cbe8c72.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the above code received WA after submitting: https://leetcode.com/submissions/detail/895564221/
please feel free to refer to the discussion section of the problem to see how other users have optimized their codes!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output values.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!

**Comment by BrycePy** [comment]
Hi, I understand that there are a lot of issues you have to deal with. I think there is something actually wrong about the Q10 checker. Could you please take 30 seconds to reread the issue? I even tried a known accepted solution and it still give "Time limit exceeded".

**Comment by BrycePy** [comment]
the `return false;` is so that it should be returning instantly and should be impossible to get a "Time limit exceeded". but when you use following input `p = "a*a*a*a*a*a*a*a*a*a*a*a*a*"` and `s = "aaaaaaaaaaaaaaaaaaab"`. you get "Time limit exceeded" no matter what.
