### ISSUE TITLE
Missing Test Case - 2557. Maximum Number of Integers to Choose From a Range II

### ISSUE THREAD

**Issue by nskybytskyi** [LeetCode-Feedback/LeetCode-Feedback#11648]
#### Your LeetCode username

[nskybytskyi](https://leetcode.com/nskybytskyi/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

There is a solution for problem [2557. Maximum Number of Integers to Choose From a Range II](https://leetcode.com/problems/maximum-number-of-integers-to-choose-from-a-range-ii/) that does not handle duplicate banned values correctly but gets AC.

#### Code you used for Submit/Run operation

[Submission link](https://leetcode.com/problems/maximum-number-of-integers-to-choose-from-a-range-ii/submissions/895720146/)

```py
import bisect
import itertools


class Solution:
    def maxCount(self, banned: list[int], n: int, max_sum: int) -> int:
        banned.sort()
        prefix_sums = list(itertools.accumulate(banned, initial=0))

        def key(candidate: int) -> int:
            return ((candidate + 1) * candidate) // 2 \
                - prefix_sums[bisect.bisect_right(banned, candidate)]

        max_value = bisect.bisect_right(range(0, n + 1), max_sum, key=key) - 1
        return max_value - bisect.bisect_right(banned, max_value)
```

#### Language used for code

Python 3.

#### Expected behavior

The solution should get WA on the following test case:
```
Input:
banned = [1,1]
n = 2
maxSum = 2
Output: 0
Expected: 1
```

#### Screenshots

Run results formatted nicely:

<img width="410" alt="run results formatted nicely" src="https://user-images.githubusercontent.com/25816558/218241186-7913e426-0d88-4e20-8b89-c715e9173795.png">

**Comment by nskybytskyi** [comment]
Alternatively, you can add a constraint saying that banned values are unique.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
