### ISSUE TITLE
Incorrect Question Constraints - 232. Implement Queue using Stacks

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1164]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

https://leetcode.com/problems/implement-queue-using-stacks/
232. Implement Queue using Stacks

Constraints are given as below:

> 1 <= x <= 9

But x = 10 is also accepted.

	Test Case1:
		Your input
			["MyQueue" ,"push"      ]
			[[]        ,[10]        ]
		Output	[null,null]
		Expected	[null,null]

		Accepted

	Test Case2:
		Your input
			["MyQueue" ,"push"      ]
			[[]        ,[11]        ]

		Invalid Testcase
			'push' arguments are invalid: expected 'x' to have value from 1 to 10 only

- Please change constraits

	from
		1 <= x <= 9
	to
		1 <= x <= 10

OR

- Fix the judge to not accept x = 10

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

- Rarely program logic takes time, most times creating test cases take more time, especially these "class"-based / "design"-based questions. Constraints being correct is crucial.
- Judge must obey the Constraints - just like Users.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
