### ISSUE TITLE
solution implementation not available

### ISSUE THREAD

**Issue by ShovalAtar** [LeetCode-Feedback/LeetCode-Feedback#11657]
#### Your LeetCode username

Shoval Atar

#### Category of the bug
- [ ] Question
- [ V] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

On "Design Linked List" question:
"This Playground is Unavailable
Click here to create your own playground"
of the doubly linked list

#### Screenshots

![image](https://user-images.githubusercontent.com/45339701/218272951-c9af5ea2-fa17-42ad-927f-751812c00564.png)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The implementation can play correctly on the solution page, please refresh the page to try it again, 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
![Screen Shot 2023-02-13 at 2 01 39 PM](https://user-images.githubusercontent.com/103138242/218550231-fa7b39a9-0bea-4878-9e92-1357fea6ad39.png)
