### ISSUE TITLE
Binary Search Template 2 code has an unnecessary check condition, and there are inconsistencies elsewhere with its 'right' initialization.

### ISSUE THREAD

**Issue by cornelius1** [LeetCode-Feedback/LeetCode-Feedback#11658]
#### Your LeetCode username
Electropylon

#### Category of the bug
- Solution
- Language

#### Description of the bug

The check condition `left != nums.length` on line 16 of Template#2 code on [the "Binary Search Template II" page](https://leetcode.com/explore/learn/card/binary-search/126/template-ii/937/) is **unnecessary**, because on that line, it is guaranteed that `left == right` (since that's the end condition for the loop), and `right` is initialized to `nums.length - 1` at the beginning and is never increased, which means `left` can be at most `nums.length - 1` anyway.

Also, the "Initial Condition" further down on the same page and the initialization of `right` in the "Template#2" code in [the analysis page](https://leetcode.com/explore/learn/card/binary-search/136/template-analysis/935/) are currently both **inconsistent** with the (correct) initialization `right = nums.length - 1` on line 5 of Template#2 code on [the "Binary Search Template II" page](https://leetcode.com/explore/learn/card/binary-search/126/template-ii/937/). So, the former two should be updated to be consistent with the latter.

Just to be clear, the current initialization `right = nums.length - 1` on line 5 of Template#2 code on [the "Binary Search Template II" page](https://leetcode.com/explore/learn/card/binary-search/126/template-ii/937/) is **correct** and **more efficient** than the initialization `right = nums.length`, since the latter results in an additional (and unnecessary) iteration of the loop for certain inputs.

You can easily test this by copying the contents of that template code into the (Java) solution of the question on [this "Binary Search" page](https://leetcode.com/explore/learn/card/binary-search/138/background/1038/), printing the value of `mid` after it's assigned, and running the code with the default test case, i.e.:
```
[-1,0,3,5,9,12]
9
```
With the initialization as `right = nums.length - 1`, the loop iterates 2 times, with `mid` assigned to the values 2 and 4.\
With the initialization as `right = nums.length`, the loop iterates 3 times, with `mid` assigned to the values 3, 5, and 4.

On [the same question page](https://leetcode.com/explore/learn/card/binary-search/138/background/1038/), you can also see that the check condition `left != nums.length` is **not** necessary, by removing that check condition, making sure the initialization is `right = nums.length - 1`, changing the target value in the (custom) test case to 13 (i.e. higher than all elements in `nums`), and running the code again. With that custom test case, `mid` gets assigned to 2 and 4, and the answer is correctly given as -1 (i.e. using the post-processing), which means, if the check was necessary, it would have been needed with this custom test case, but it was not (thanks to the initialization being `right = nums.length - 1`).

#### Code you used for Submit/Run operation

```java
int binarySearch(int[] nums, int target){
  if(nums == null || nums.length == 0)
    return -1;

  int left = 0, right = nums.length - 1;
  while(left < right){
    // Prevent (left + right) overflow
    int mid = left + (right - left) / 2;
    if(nums[mid] == target){ return mid; }
    else if(nums[mid] < target) { left = mid + 1; }
    else { right = mid; }
  }

  // Post-processing:
  // End Condition: left == right
  if(nums[left] == target) return left;
  return -1;
}
```

#### Language used for code

Java (though similarly for C++ and Python as well)

#### Expected behavior

I think 3 changes should be made on 2 pages:

1. Remove the unnecessary check "left != nums.length" on [the "Binary Search Template II" page](https://leetcode.com/explore/learn/card/binary-search/126/template-ii/937/):
In "Template#2":
Line 16 for C++ and Java should be changed to:
  `if(nums[left] == target) return left;`
Line 22 for Python should be changed to:
  `if nums[left] == target:`

2. Fix an inconsistency on [the same page](https://leetcode.com/explore/learn/card/binary-search/126/template-ii/937/):
Under "Distinguishing Syntax", the "Initial Condition" line should be changed to:
Initial Condition: `left = 0, right = length - 1`

3. Fix an inconsistency in the code on [the analysis page](https://leetcode.com/explore/learn/card/binary-search/136/template-analysis/935/) with the code above:
In "Template#2" on that analysis page, the initialization line should be changed to:
`left = 0; right = length - 1;`
(i.e. just like in "Template#1" and "Template#3" on that page)

#### Additional context

* https://leetcode.com/explore/learn/card/binary-search/126/template-ii/937/
* https://leetcode.com/explore/learn/card/binary-search/136/template-analysis/935/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by cornelius1** [comment]
Thanks. Though, since the initialization of `right` in Template#2 on [the analysis page](https://leetcode.com/explore/learn/card/binary-search/136/template-analysis/935/) is no longer different from those in Template#1 and Template#3 there, and the red color is supposed to show differences, you should probably also change the color of "length - 1" in that initialization in all templates to black, i.e. in [this image](https://assets.leetcode.com/uploads/2023/02/13/template_diagram.png).
