### ISSUE TITLE
Missing Test Case - 215. Kth Largest Element in an Array

### ISSUE THREAD

**Issue by acearth** [LeetCode-Feedback/LeetCode-Feedback#11654]
#### Your LeetCode username

acearth

#### Category of the bug
- [ ] Question: 215. Kth Largest Element in an Array
- [ ] Solution: Based on quick select
- [ ] Language
- [ ] Missing Test Cases : should add test cases with ordered inputs

#### Description of the bug

Generally users creating solutions with simple quick select without randomization picking pivot. Quick selection could be consume O(n) time for each scan if the inputed data is already ordered.  So we should  add ordered test cases to test users implementation.  Since the question description already limited data range from -10000 to 10000 with length less than 100_000. It's better to create more test cases to ensure non-randomized solution to be failed.

Here is an example:
[99.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/10713935/99.txt)

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by nskybytskyi** [comment]
Do you have an example of a solution that gets accepted but fails on the suggested test case?

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
