### ISSUE TITLE
Missing Test Case - 35. Search Insert Position

### ISSUE THREAD

**Issue by itundefined** [LeetCode-Feedback/LeetCode-Feedback#11653]
#### Your LeetCode username

**My Username is =  https://leetcode.com/itundefined/**

**Recommendation,** 
 
**Question** - _there is a target to find in an array even if the number is not available in the array you can return the number index after that would be existing._ 

**The test case has to modify** - Change this test [1,3,5,6] target no 5 To target No 0 which makes more sense.

**Description:** **Well You should either modify it** or **just add another test case with finding the 0 number in an array in which 0 does not exist** because the other two cases are finding the middle and ending missing number's index in the array this New test case can target in the starting that can help programmers and beginners to think well and they won't have to submit the code until their test cases are solved and that would be helpful, in my opinion since it is an easy question!!!

#### Category of the bug
- [*] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by itundefined** [comment]
assign me please for this.

**Comment by nskybytskyi** [comment]
Is there a solution that gets accepted but fails on the suggested test case?

**Comment by itundefined** [comment]
If there was a issue like that then i would have mentioned that, this is the only thing i think can be better, if it's not then it's fine.

**Comment by nskybytskyi** [comment]
The "missing test case" label refers to the situation when you have a solution that gets accepted but should not because it fails on the proposed test case. Such test cases are essential to ensure that incorrect submissions are not accepted. All other test cases create an unnecessary load on the system.

**Comment by itundefined** [comment]
It's just i thought it would make sense for beginners but anyways I got it!!! Thnx for explaining.
