### ISSUE TITLE
Weak Test Case Weekly Contest 332 Q4

### ISSUE THREAD

**Issue by SongHayoung** [LeetCode-Feedback/LeetCode-Feedback#11662]
#### Your LeetCode username

lovelydays95

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

input : "zzz", "azz"
output : 1 but 3
```
class Solution {
public:
    int minimumScore(string s, string t) {
        int n = s.length(), m = t.length();
        vector<int> lmatch(m,INT_MAX), rmatch(m,INT_MAX);
        for(int i = 0, j = 0; i < n and j < m; i++) {
            if(s[i] == t[j]) {
                lmatch[j] = i;
                j += 1;
            }
        }
        int p = m - 1;
        while(p >= 0 and lmatch[p] == INT_MAX) p -= 1;
        if(p == -1) return m;
        int res = m - (p + 1);
        for(int i = n - 1, j = m - 1; i >= 0 and j >= 0; i--) {
            if(s[i] == t[j]) {
                rmatch[j] = i;
                p = min(p,j);
                while(p >= 0 and lmatch[p] >= rmatch[j]) p -= 1;
                if(p >= 0) {
                    res = min(res, (j-1) - (p + 1) + 1);
                }
                res = min(res, j);
                j -= 1;
            }
        }
        return max(0,res);
    }
};

```

#### Language used for code

c++

#### Expected behavior

expect `WA` but `AC`

#### Screenshots

![스크린샷 2023-02-12 13 06 58](https://user-images.githubusercontent.com/37806785/218292506-99f9e01b-04cc-4930-a7d9-cc5dadc0be7c.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code AC submission link.
https://leetcode.com/submissions/detail/897400146/

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by SongHayoung** [comment]
@LC-Pam 
AC submission link: 
https://leetcode.com/contest/weekly-contest-332/submissions/detail/896278053/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

After the rejudge, the code provided above received WA : https://leetcode.com/submissions/detail/898038239/
 
Under contest [rules](https://leetcode.com/discuss/general-discussion/951105/new-contest-rule-effective-from-december-2020) you will find more details.
 
If the rejudge is executed, LeetCode will rejudge all the submissions that were submitted to the problem by users who were impacted during the contest. The first Accepted submission will be taken as the final result, and the "Wrong Answer/Time Limited Exceeded" submissions made prior to the first "Accepted" submissions will be counted for penalty time.
 
If the submissions that should have been judged as “Wrong Answer” were judged as “Accepted” during the contest for any reason, LeetCode will rejudge all the submissions that got “Accepted” during this contest for the problem.
If the submissions that should have been judged as “Accepted” were judged as “Wrong Answer” during the contest for any reason, LeetCode will rejudge all the submissions that got “Wrong Answer” during this contest for the problem.
If the correct submissions were judged as “Wrong Answer”, and incorrect submissions were judged as “Accepted” during the contest for any reason, LeetCode will rejudge all the submissions that were made during this contest for the problem.
 
We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
