### ISSUE TITLE
6356. Substring XOR Queries

### ISSUE THREAD

**Issue by sourashis59** [LeetCode-Feedback/LeetCode-Feedback#11661]
#### Your LeetCode username

SourashisHeartHacker

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

![image](https://user-images.githubusercontent.com/74865683/218291822-b1f10737-3f1c-40c0-b2b9-b2fb0c2bc01a.png)

It is asked in the question that if there are multiple answers, then we should choose the one with minimum left index. But the expected answers for the test cases are not all correct.

Example:
![image](https://user-images.githubusercontent.com/74865683/218291850-b5a86356-26af-4cfc-8a54-63fff70c49ec.png)
Here for the 2nd query, the substring from index 1 to 3 is "011", which has decimal value 3. So it should be the answer to the 2nd query.
That is, [1,3] should be the answer for the 2nd query, instead of [2,3]

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by stormsunshine** [comment]
You should find the shortest substring. Is "11" the shortest or "011" the shortest?

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
