### ISSUE TITLE
429. N-ary Tree Level Order Traversal (Scala)

### ISSUE THREAD

**Issue by abradbury** [LeetCode-Feedback/LeetCode-Feedback#1166]
#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The template for this question in Scala is incorrect. The definition of a `Node` shows a field `neighbors`, but this field should actually be `children`.

```scala
/**
 * Definition for a Node.
 * class Node(var _value: Int) {
 *   var value: Int = _value
 *   var neighbors: List[Node] = List()
 * }
 */
```

#### Code you used for Submit/Run operation

N/A

#### Language used for code

Scala

#### Expected behavior

```scala
/**
 * Definition for a Node.
 * class Node(var _value: Int) {
 *   var value: Int = _value
 *   var children: List[Node] = List()
 * }
 */
```

#### Screenshots

N/A

#### Additional context

N/A

**Comment by lc-kay** [comment]
Hi @abradbury 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @abradbury 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
