### ISSUE TITLE
Incorrect test cases - Course Schedule II

### ISSUE THREAD

**Issue by sid7vasa** [LeetCode-Feedback/LeetCode-Feedback#11660]
<img width="878" alt="image" src="https://user-images.githubusercontent.com/95991473/218291770-c3558135-f9f8-4b5f-b5b1-e938a67282a3.png">

Code :  
`
class Solution:
    def findOrder(self, numCourses: int, prerequisites: List[List[int]]) -> List[int]:
        hash_map = {}
        
        no_prereq = set(range(0,numCourses))
        
        for i, pr in enumerate(prerequisites):
            if pr[1] not in hash_map.keys():
                hash_map[pr[1]] = [pr[0]]
            else:
                hash_map[pr[1]].append(pr[0])
            if pr[0] in no_prereq:
                no_prereq.remove(pr[0])
            
        print(no_prereq)
        print(hash_map)
        
        result = []
        visited = set()
        for root in no_prereq:
            queue = [root]

            
            while queue:
                curr_el = queue.pop(0)
                
                if curr_el in visited:
                    continue
                visited.add(curr_el)
                
                result.append(curr_el)
                
                if curr_el in hash_map.keys():
                    queue.extend(hash_map[curr_el])
        if len(visited) != numCourses:
            return []
        return result
                
                
            
        
        
        `

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by sid7vasa** [comment]
https://leetcode.com/problems/course-schedule-ii/submissions/898014741/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
