### ISSUE TITLE
635 - Mention all possible 'granularity' values

### ISSUE THREAD

**Issue by AjayVV** [LeetCode-Feedback/LeetCode-Feedback#1167]
#### Your LeetCode username

ajayvv

#### Category of the bug
- [x] Question

#### Description of the bug
The question states about `granularity`, and examples only talk about `Year` and `Hour`. Please add all values to the question statement that can be passed to the method `retrieve`.

**Comment by lc-kay** [comment]
Hi @AjayVV 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @AjayVV 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
