### ISSUE TITLE
Two Sum IV - Input is a BST: Test case fails submission but passes "Run Code"

### ISSUE THREAD

**Issue by zanewebb** [LeetCode-Feedback/LeetCode-Feedback#1168]
#### Your LeetCode username
zanewebb

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
class Solution:
    def __init__(self):
        self.k = 0
        
    def findTarget(self, root: TreeNode, k: int) -> bool:
        self.k = k
        
        return self.dfs(root)
    
    def dfs(self, node, seen={}):
        print(seen)
        if not node:
            return False
        elif node.val in seen:
            print(seen, node.val)
            return True
        else:
            seen[self.k - node.val] = True
            return False or self.dfs(node.right) or self.dfs(node.left)
```

#### Language used for code
Python3

#### Expected behavior
Expected the submission to pass this test case but it did not pass. The output seems to indicate that for some reason the submission version of the test case was adding a 3 and 4 to my dictionary when there are no conditions that could cause this

#### Screenshots

![image](https://user-images.githubusercontent.com/10320988/95526288-54a1ee00-0989-11eb-96f2-2383a486adfe.png)

![image](https://user-images.githubusercontent.com/10320988/95527008-8fa42180-0989-11eb-95c2-a60672222193.png)

![image](https://user-images.githubusercontent.com/10320988/95527148-ac405980-0989-11eb-9090-18d1835a7142.png)

**Comment by lc-kay** [comment]
Hi @zanewebb  

Thank you for reaching out to us! The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in this article: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-. Please check it out.
