### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by maverickreal** [LeetCode-Feedback/LeetCode-Feedback#11683]
![image](https://user-images.githubusercontent.com/57585749/218295905-cf86c51a-17d2-41c6-83bc-f93150953f0f.png)
Question: https://leetcode.com/problems/subsequence-with-the-minimum-score/
The third line starts as "The score string is..."
It should rather be something like: "The string score is...", or "The score of the string is..."

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback. 

Please reply to this ticket with your username.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by maverickreal** [comment]
My leetcode account: https://leetcode.com/maverick09/
Username: maverick09
