### ISSUE TITLE
Missing Test Case - 1361. Validate Binary Tree Nodes

### ISSUE THREAD

**Issue by Jashwanth18** [LeetCode-Feedback/LeetCode-Feedback#11689]
#### Your LeetCode username
Jashwanth18

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
An accepted solution gets wrong answer on the following testcase:
n = 4
leftChild = [1,2,3,0]
rightChild = [-1,-1,-1,-1]

#### Code you used for Submit/Run operation

```
// Validate Binary Tree Nodes
class Solution {
public:
    bool validateBinaryTreeNodes(int n, vector<int>& leftChild, vector<int>& rightChild) {
        vector<int> par(n);
        for(int i = 0; i < n; i++) par[i] = i;
        int cnt = 0;

        for(int i = 0; i < n; i++){
            int l = leftChild[i], r = rightChild[i];
            if((l!=-1 && (par[l]!=l || l==par[par[i]])) || (r!=-1 && (par[r]!=r && r==par[par[i]]))) return false;
            else{
                if(l != -1) par[l] = i;
                if(r != -1) par[r] = i;
            }
        }

        for(int i = 0; i < n; i++){
            if(par[i] == i) cnt++;
        } 

        return (cnt>1)? false : true;       
    }
};
```

#### Language used for code
C++

#### Expected behavior
My code should not be accepted as expected answer for this test case is false but this code (which got accepted) returns true for the above test case.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
