### ISSUE TITLE
Duplicated sentence in the solution for 2477. Minimum Fuel Cost to Report to the Capital

### ISSUE THREAD

**Issue by raychanks** [LeetCode-Feedback/LeetCode-Feedback#11692]
#### Your LeetCode username

raychanks

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Duplicated sentence at the bottom of the overview section in the [solution](https://leetcode.com/problems/minimum-fuel-cost-to-report-to-the-capital/solutions/3080167/minimum-fuel-cost-to-report-to-the-capital/) for `2477. Minimum Fuel Cost to Report to the Capital`. I drew a box around the duplicated sentence in the screenshot below.

#### Screenshots

![leetcode_typo](https://user-images.githubusercontent.com/34273644/218318730-555687a3-ce6b-4cd9-871b-70fc97ce6e19.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
