### ISSUE TITLE
Typo in Official Solution 188. Best Time to Buy and Sell Stock IV

### ISSUE THREAD

**Issue by LHuang2019** [LeetCode-Feedback/LeetCode-Feedback#11699]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The official solution for 188. Best Time to Buy and Sell Stock IV mentioned that the DP base case started with `dp[0][0][1]=-prices[0]`, but the actual solution code uses `dp[0][1][1]=-prices[0]`

#### Code you used for Submit/Run operation

```
N/A
```

#### Language used for code

Python

#### Screenshots

![image](https://user-images.githubusercontent.com/14338820/218326913-4d7443fb-f598-43a1-ba49-e17d09072dae.png)
![image](https://user-images.githubusercontent.com/14338820/218326927-a2e16053-c368-4d3c-9bb7-e7def019688e.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback. 

Please reply to this message with your LC username. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by LHuang2019** [comment]
@LC-Pam Thank you! LC ID is `ansdeki`. Feel free to close this issue for me when resolved!
