### ISSUE TITLE
[Weekly Contest 322] Missing Test Cases - 2564. Substring XOR Queries

### ISSUE THREAD

**Issue by ArshadAQ** [LeetCode-Feedback/LeetCode-Feedback#11690]
#### Your LeetCode username
ArshadAQ

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
Is a quadratic (`O(queries.length * s.length)`) solution expected to be accepted here? There are many such solutions accepted during the contest. This kind of a solution is **trivial** for this problem(5 points) and **shouldn't be accepted**. An example code is shown below

**On another note**: Lots of contestants have plagiarised this exact solution and I've reported this from the contest page. The last time I took the effort to report, nothing happened.  Hope, appropriate actions are taken this time at least.

#### Code you used for Submit/Run operation

```
class Solution:
    def substringXorQueries(self, s: str, queries: List[List[int]]) -> List[List[int]]:
        ans = []
        i = 0
        for a,b in queries:
            val = b^a
            se = bin(val)[2:]
            if se in s:
                ans.append([s.index(se) , s.index(se) + len(se)-1])
            else:
                ans.append([-1,-1])
        return ans if ans else [[-1,-1]]
```

#### Language used for code
Python

#### Expected behavior
Solution should TLE

**Comment by Nan-Do** [comment]
I was going to submit this exact same complaint as there are literally hundreds of submissions with this exact same approach, in python3, which takes almost 10 seconds. I think the code is too trivial to accuse all of them of plagiarism (even if a lot of them did). The next code in python generates a test case that should make those approaches fail.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by ArshadAQ** [comment]
@LC-Pam I see the contest ratings have been updated, but still this solution has been accepted.
Haven't we got a test case which will give TLE to this solution?

That was the issue raised by this issue but looks like contest results are published without addressing this issue?

Could you please help us understand what exactly happened?

**Comment by LC-Pam** [comment]
Thank you for taking the time to reach out to us!
 
Under contest [rules](https://leetcode.com/discuss/general-discussion/951105/new-contest-rule-effective-from-december-2020) you will find more details.
 
If the rejudge is executed, LeetCode will rejudge all the submissions that were submitted to the problem by users who were impacted during the contest. The first Accepted submission will be taken as the final result, and the "Wrong Answer/Time Limited Exceeded" submissions made prior to the first "Accepted" submissions will be counted for penalty time.
 
If the submissions that should have been judged as “Wrong Answer” were judged as “Accepted” during the contest for any reason, LeetCode will rejudge all the submissions that got “Accepted” during this contest for the problem.
If the submissions that should have been judged as “Accepted” were judged as “Wrong Answer” during the contest for any reason, LeetCode will rejudge all the submissions that got “Wrong Answer” during this contest for the problem.
If the correct submissions were judged as “Wrong Answer”, and incorrect submissions were judged as “Accepted” during the contest for any reason, LeetCode will rejudge all the submissions that were made during this contest for the problem.
 
We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by ArshadAQ** [comment]
@LC-Pam How does this answer my query?

This scenario applies to my query: "If the submissions that should have been judged as “Accepted” were judged as “Wrong Answer” during the contest. LeetCode will rejudge all the submissions that got “Accepted” during this contest for the problem."

But this has not happened. This is what I'm trying to say. 

For example, please check this submission - https://leetcode.com/contest/weekly-contest-332/submissions/detail/896305874/
Its still accepted.

**Comment by ArshadAQ** [comment]
@LC-Pam Thanks for reopening this issue. Attaching here the recent conversation for the full context:

![image](https://user-images.githubusercontent.com/25927120/219880874-50a49700-8ae6-4047-8458-436a1f320aea.png)



**Requesting to not close this issue without my acknowledgement in order to reduce back and forth creation of tickets**

**Comment by ArshadAQ** [comment]
@LC-Pam Any update here?

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem and received a response from the team leader as below:

"We decided not to rejudge but the time limit is changed now and such solutions get TLE now."

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
