### ISSUE TITLE
Ambiguous/ Incorrect Constraints - 303. Range Sum Query - Immutable

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1169]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

.1.

    Input:
        ["NumArray"]
        [[[ ]]]
    Output:
        [null]

That means, number of "sumRange" calls can be 0, this can be mentioned in the constraints - removing any discussion on that part - https://leetcode.com/problems/range-sum-query-immutable/solution/133379

.2.
Constraint:

    "There are many calls to sumRange function."

- What us many?
- Can it be 1 billion?

---

Suggestion:

Constraint like below will help:

    0 <= Number of sumRange calls <= 50000

Above will also remove ambiguity on how the "nums.length == 0" is possible?

    0 <= nums.length <= 10^4
    0 <= i <= j < nums.length

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

- Having a bad time creating tests. Look like decrypting the constraints is a big part of this question.
- Constraints must be correct & complete.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
