### ISSUE TITLE
Stock market - zero price in test cases

### ISSUE THREAD

**Issue by i-to** [LeetCode-Feedback/LeetCode-Feedback#117]
**What kind of the bug**
- [x] problem
- [x] solution
- [ ] language

**Describe the bug**
Problem: [Best Time to Buy and Sell Stock II](https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii)

The solution below failed the following case: `[2,1,2,0,1]`.

The problem description doesn't specify any restrictions on price value. Therefore, it is reasonably to assume that the price is strictly greater than zero like in normal life.

**what language is your code written in**
Python3, but that doesn't really mater

**The code you submit/run**
``` Python
class Solution:
    def maxProfit(self, prices: List[int]) -> int:
        profit = 0
        price = 0
        for i in range(len(prices)):
            if i == 0 or prices[i] < prices[i - 1]:
                price = prices[i]
            elif (i == len(prices) - 1 or prices[i] > prices[i + 1]) and price:
                profit += prices[i] - price
        return profit
```

**Expected behavior**
One of the two:
1. Explicit statement in the description that price[i] >= 0
2. Following common sense and having all prices in test cases strictly > 0

**Screenshots**
-

**Additional context**
-

**Comment by CooperCooperCooper** [comment]
Hi @i-to,
Thank you for reaching out to us! I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @i-to,
Thank you for your time and feedback! It's okay to have zeros as values for this problem. We've updated the problem statement.
