### ISSUE TITLE
English typo in Top k Frequent Elements

### ISSUE THREAD

**Issue by naphtul** [LeetCode-Feedback/LeetCode-Feedback#11700]
#### Your LeetCode username
naphtul

#### Category of the bug
- [ ] Question
- [X] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug
In Top k Frequent Elements official solution: 
https://leetcode.com/problems/top-k-frequent-elements/solutions/646157/official-solution/
It says:

> Quickselect is a [textbook algorthm](https://en.wikipedia.org/wiki/Quickselect) typically...

#### Expected behavior
The word algorithm is misspelled.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
