### ISSUE TITLE
Incorrect Test Case for 258. Add Digits

### ISSUE THREAD

**Issue by jennysys** [LeetCode-Feedback/LeetCode-Feedback#11702]
#### Your LeetCode username

potatokitty

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

The test case "Case 1" for the beginning of the problem expects an out of "2" instead of "11" based on the input "38". This is incorrect based on the example in the problem description.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int addDigits(int num) {
        string numConversion = to_string(num);
        int sum = 0;
        for (int i = 0; i < numConversion.size(); i++) {
            int digit = numConversion[i] - '0';
            sum += digit;
        }
        return sum;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Th expected output for "Case 1" should be "11" instead of "2".

**Comment by stormsunshine** [comment]
Please read the problem description carefully.

> Given an integer `num`, repeatedly add all its digits until the result has only one digit, and return it.

Don't you see the word "repeatedly" and the phrase "until the result has only one digit"?

**Comment by jennysys** [comment]
I made a mistake, thank you for correcting me.
