### ISSUE TITLE
Serialize and Deserialize BST: Add a check to prevent solution hack using static

### ISSUE THREAD

**Issue by kunalk16** [LeetCode-Feedback/LeetCode-Feedback#1170]
#### Your LeetCode username
kunalkarmakar

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Problem https://leetcode.com/explore/challenge/card/october-leetcoding-challenge/560/week-2-october-8th-october-14th/3489/
Solution passes if we use a hack using static variables -> https://leetcode.com/submissions/detail/406485730/

#### Code you used for Submit/Run operation
```
/**
 * Definition for a binary tree node.
 * public class TreeNode {
 *     int val;
 *     TreeNode left;
 *     TreeNode right;
 *     TreeNode(int x) { val = x; }
 * }
 */
public class Codec {
    private static TreeNode rootS;

    // Encodes a tree to a single string.
    public String serialize(TreeNode root) {
        rootS = root;
        return "";
    }

    // Decodes your encoded data to tree.
    public TreeNode deserialize(String data) {
        return rootS;
    }
}

// Your Codec object will be instantiated and called as such:
// Codec ser = new Codec();
// Codec deser = new Codec();
// String tree = ser.serialize(root);
// TreeNode ans = deser.deserialize(tree);
// return ans;
```

#### Language used for code
Java

#### Expected behavior

A check should be kept such that user simply does not return the object passed as a parameter through the serialize() function. Maybe a !object.equals() should do the trick.

#### Additional context

Any other check that prevents this is also welcome.

**Comment by lc-kay** [comment]
Hi @kunalk16 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by kunalk16** [comment]
Please note that I am referring to the solution that I have shown in the post. I have used a static variable to store the original tree object when there is a serialize() call and I am returning the same value from the static variable while calling deserialize(). This approach should not pass.

**Comment by lc-kay** [comment]
@kunalk16 After consulting with the engineering team, we concluded that although this problem can be solved with a hack, we cannot prevent it in all the languages. In addition, the purpose of this problem is to practice serialization/deserialization, therefore, we will not be adding anything to this problem. Thank you for your time!
