### ISSUE TITLE
Missing Test Case - 217. Contains Duplicate

### ISSUE THREAD

**Issue by leonfrer** [LeetCode-Feedback/LeetCode-Feedback#11708]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I clicked the runtime distribution chart, and saw the fastest code in Java is like this

```java
class Solution {
    public boolean containsDuplicate(int[] nums) {
        if (nums.length==2 && (nums[0]==-24500 || nums[0]==237384)) return true;
        if (nums.length==0 || nums[0]==237384 || nums[0]==-24500) return false;
        if (nums[0]==2048) return false;
        if (nums[0]==30720) return false;
        boolean[] k = new boolean[2048];
        for (int i=0; i<nums.length; i++){
            if (k[nums[i] & 2047]) return true;
            else k[nums[i] & 2047] = true;
        }
        return false;
    }
}
```

if testcase is [1, 2049], the result would be wrong. And these lines below is totally cheating.

```java
if (nums.length==2 && (nums[0]==-24500 || nums[0]==237384)) return true;
if (nums.length==0 || nums[0]==237384 || nums[0]==-24500) return false;
if (nums[0]==2048) return false;
if (nums[0]==30720) return false;
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

The code received Wrong Answer after submit: https://leetcode.com/submissions/detail/897408472/

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output values.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!
