### ISSUE TITLE
Description Not Clear - 245. Shortest Word Distance III

### ISSUE THREAD

**Issue by sachuverma** [LeetCode-Feedback/LeetCode-Feedback#11714]
#### Your LeetCode username
sachuverma

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I opened this question, having no idea what Shortest Word Distance 1 and 2 problems might have asked to solve.   
After reading this problem's description I can't make out what I need to do in this problem, it doesn't say anything about what "the shortest distance between two words" means in the description and in test cases too.

A clear explanation must have been given.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
