### ISSUE TITLE
Missing Test Case - 1334. Find the City With the Smallest Number of Neighbors at a Threshold Distance

### ISSUE THREAD

**Issue by karprabha** [LeetCode-Feedback/LeetCode-Feedback#11719]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

If any isolated vertex is present i.e some nodes are not present in the given edges. If anyone initializes paths through edges might miss to initialize the isolated vertices in distance matrix which should result in wrong answer.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
        vector<vector<int>> adj(n,vector<int>(n,1e9));
        
        for(const auto& x: edges){
            adj[x[0]][x[1]] = x[2];
            adj[x[1]][x[0]] = x[2];
            adj[x[0]][x[0]] = 0;
            adj[x[1]][x[1]] = 0;
        }

        for(int via=0;via<n;via++){
            for(int i=0;i<n;i++){
                for(int j=0;j<n;j++){
                    adj[i][j] = min(adj[i][j],adj[i][via] + adj[via][j]);
                }
            }
        }
        
        int res = -1;
        int currMin = INT_MAX;
        for(int i=0;i<n;i++){
            int count = 0;
            for(int j=0;j<n;j++){
                if(adj[i][j] <= distanceThreshold)count++;
            }
            if(count <= currMin){
                currMin = count;
                res = i;
            }
        }
        
        return res;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The program should give wrong answer for the given test case

17
[[0, 4, 11],[0, 11, 24],[1, 2, 2],[2, 6, 4],[2, 15, 7],[3, 9, 14],[4, 3, 5],[4, 4, 15],[5, 0, 4],[7, 7, 29],[7, 11, 8],[7, 16, 27],[9, 5, 25],[9, 6, 10],[9, 11, 29],[9, 15, 12],[11, 14, 15],[12, 7, 3],[12, 13, 30],[12, 16, 30],[13, 1, 14],[13, 3, 9],[13, 13, 25],[14, 12, 18],[16, 14, 15]]
11

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code AC submission link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by karprabha** [comment]
Yes,
Solution link: https://leetcode.com/submissions/detail/897619814/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your reply.

The test case 
17
[[0, 4, 11],[0, 11, 24],[1, 2, 2],[2, 6, 4],[2, 15, 7],[3, 9, 14],[4, 3, 5],[4, 4, 15],[5, 0, 4],[7, 7, 29],[7, 11, 8],[7, 16, 27],[9, 5, 25],[9, 6, 10],[9, 11, 29],[9, 15, 12],[11, 14, 15],[12, 7, 3],[12, 13, 30],[12, 16, 30],[13, 1, 14],[13, 3, 9],[13, 13, 25],[14, 12, 18],[16, 14, 15]]
11
received an Invalid Test Case when we run it. The reason is:" expected 'y' to have value from 5 to 16 only"

Please let us know if you can provide any valid test cases.

Thank you.

**Comment by karprabha** [comment]
I think testcases have this constraint of input edges being restricted to having all the vertices, In that case my missing test-case request is invalid. Thank you for your time. Have a great day
