### ISSUE TITLE
Missing Test cases - 836. Rectangle Overlap

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1171]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language

#### Description of the bug

836. Rectangle Overlap
https://leetcode.com/problems/rectangle-overlap/

Below constraints are given:

    rec1[0] <= rec1[2] and rec1[1] <= rec1[3]
    rec2[0] <= rec2[2] and rec2[1] <= rec2[3]

Below code (best submission under Runtime) does not pass below tests (given in 3 TEST SETS):

Case rec2[0] == rec2[2]

	input
		[-1,0,1,1]
		[0,-1,0,1]
		expected  false     actual  true
	input
		[-1,0,1,1]
		[0,0,0,1]
		expected  false     actual  true
	input
		[-1,0,1,1]
		[0,-1,0,1]
		expected  false     actual  true
	input
		[-1,0,1,1]
		[0,0,0,1]
		expected  false     actual  true
	input
		[-10,0,5,5]
		[0,-10,0,5]
		expected  false     actual  true
	input
		[-10,0,5,5]
		[0,0,0,5]
		expected  false     actual  true
	input
		[-10,0,5,5]
		[0,-10,0,5]
		expected  false     actual  true
	input
		[-10,0,5,5]
		[0,0,0,5]
		expected  false     actual  true
	input
		[-10,0,10,10]
		[0,-10,0,10]
		expected  false     actual  true
	input
		[-10,0,10,10]
		[0,0,0,10]
		expected  false     actual  true
	input
		[-10,0,10,10]
		[0,-10,0,10]
		expected  false     actual  true
	input
		[-10,0,10,10]
		[0,0,0,10]
		expected  false     actual  true
	input
		[-1,0,1,0]
		[0,-1,0,1]
		expected  false     actual  true
	input
		[-1,0,1,0]
		[0,-1,0,1]
		expected  false     actual  true
	input
		[-10,0,5,0]
		[0,-10,0,5]
		expected  false     actual  true
	input
		[-10,0,5,0]
		[0,-10,0,5]
		expected  false     actual  true
	input
		[-10,0,10,0]
		[0,-10,0,10]
		expected  false     actual  true
	input
		[-10,0,10,0]
		[0,-10,0,10]
		expected  false     actual  true

Case rec2[1] == rec2[3]

	input
		[-1,-1,0,1]
		[-1,0,1,0]
		expected  false     actual  true
	input
		[-1,-1,1,1]
		[-1,0,1,0]
		expected  false     actual  true
	input
		[0,-1,1,1]
		[0,0,1,0]
		expected  false     actual  true
	input
		[-1,-1,0,1]
		[-1,0,1,0]
		expected  false     actual  true
	input
		[-1,-1,1,1]
		[-1,0,1,0]
		expected  false     actual  true
	input
		[0,-1,1,1]
		[0,0,1,0]
		expected  false     actual  true
	input
		[-10,-10,0,5]
		[-10,0,5,0]
		expected  false     actual  true
	input
		[-10,-10,5,5]
		[-10,0,5,0]
		expected  false     actual  true
	input
		[0,-10,5,5]
		[0,0,5,0]
		expected  false     actual  true
	input
		[-10,-10,0,5]
		[-10,0,5,0]
		expected  false     actual  true
	input
		[-10,-10,5,5]
		[-10,0,5,0]
		expected  false     actual  true
	input
		[0,-10,5,5]
		[0,0,5,0]
		expected  false     actual  true
	input
		[-10,-10,0,10]
		[-10,0,10,0]
		expected  false     actual  true
	input
		[-10,-10,10,10]
		[-10,0,10,0]
		expected  false     actual  true
	input
		[0,-10,10,10]
		[0,0,10,0]
		expected  false     actual  true
	input
		[-10,-10,0,10]
		[-10,0,10,0]
		expected  false     actual  true
	input
		[-10,-10,10,10]
		[-10,0,10,0]
		expected  false     actual  true
	input
		[0,-10,10,10]
		[0,0,10,0]
		expected  false     actual  true

Case rec1[1] == rec1[3]

	input
		[-1,0,1,0]
		[0,-1,1,1]
		expected  false     actual  true
	input
		[-1,0,1,0]
		[0,-1,1,1]
		expected  false     actual  true
	input
		[-1,0,1,0]
		[0,-1,1,1]
		expected  false     actual  true
	input
		[-1,0,1,0]
		[0,-1,1,1]
		expected  false     actual  true
	input
		[-10,0,5,0]
		[0,-10,5,5]
		expected  false     actual  true
	input
		[-10,0,5,0]
		[0,-10,5,5]
		expected  false     actual  true
	input
		[-10,0,5,0]
		[0,-10,5,5]
		expected  false     actual  true
	input
		[-10,0,5,0]
		[0,-10,5,5]
		expected  false     actual  true
	input
		[-10,0,10,0]
		[0,-10,10,10]
		expected  false     actual  true
	input
		[-10,0,10,0]
		[0,-10,10,10]
		expected  false     actual  true
	input
		[-10,0,10,0]
		[0,-10,10,10]
		expected  false     actual  true
	input
		[-10,0,10,0]
		[0,-10,10,10]
		expected  false     actual  true

#### Code you used for Submit/Run operation

Sample 60 ms submission
At https://leetcode.com/submissions/detail/406538986/

```
/**
 * @param {number[]} rec1
 * @param {number[]} rec2
 * @return {boolean}
 */
var isRectangleOverlap = function(rec1, rec2) {
            return !(rec1[2] <= rec2[0] ||   // left
                 rec1[3] <= rec2[1] ||   // bottom
                 rec1[0] >= rec2[2] ||   // right
                 rec1[1] >= rec2[3]);    // top
};
```

#### Language used for code
JavaScript

#### Expected behavior

- Constraints must be correct
- If Constraints are correct, then Enough tests must be added to verify all constraints - to avoid inefficient codes.

More details:

- Note that across all "Accepted Solutions Runtime Distribution" and "Accepted Solutions Memory Distribution", only below 2 solutions under Runtime are passing the new Constraints - so it is better to generate these again after few days from now:
			sample 84 ms submission
			sample 92 ms submission
- I just noted that the **1st solution** also does not pass (https://leetcode.com/problems/rectangle-overlap/solution/) the new Constraints of == in below

      rec1[0] <= rec1[2] and rec1[1] <= rec1[3]
      rec2[0] <= rec2[2] and rec2[1] <= rec2[3]

- Also == can make the problem description a bit vague too, may need to give an explanation of a rectangle can have zero area? or, maybe not.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 

I just ran your code with the sets of test cases provided and they were all accepted. 
<img width="534" alt="Screen Shot 2020-10-09 at 12 16 53 PM" src="https://user-images.githubusercontent.com/70870126/95623038-7d79c000-0a29-11eb-92fa-2ba6cd27a767.png">

**Comment by manoharreddyporeddy** [comment]
@lc-pam , @lc-ivan 

Hi Pam, otherwise Ivan

- I gave a code above in the code section.
But instead of running the given code above
lc-kay runs my code (dont know from where my code has come, I din't give)

- Today I am very sad, I raised several bugs that I have not seen what their fate is.
- Please reopen this issue & relook.
- Also please look into all issues that lc-kay closed as "invalid" OR thought that I raise a wrong issue.
- I never raise a wrong one because I check 2/3 times before raising. There is always something to it. If you cannot see what I meant in the bug, its fine. But if you carelessly overlook the code given and run some other code, and close this as invalid, not at all good. I don't have to followup, as I don't job, but that does not mean you close without any thought.

So sad today - so many bugs I raised, not sure how they were closed.

**Comment by manoharreddyporeddy** [comment]
@lc-kay FYI above

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 

I apologize for the error on my end. I ran the test cases with another code in the submission link you provided. I have reopen this issue and relayed this to our team for investigation. Thank you for your valuable time.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
