### ISSUE TITLE
1501. SQL something wrong within the test case

### ISSUE THREAD

**Issue by YChanHuang** [LeetCode-Feedback/LeetCode-Feedback#11713]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名
ahhhhaaa
**Bug 类型**
- [ ] 题目 1501. Countries You Can Safely Invest In
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
描述你遇到的 bug

1.測試用例有問題，沒有被select的table也報錯。
2.任何query都會選取country table
**你使用的语言**
SQL

**你提交或者运行的代码**
```
# Write your MySQL query statement below
WITH call_log as 
(
    SELECT c.caller_id as id,
    c.duration, 
    LEFT(b.phone_number, 3) as country_code
    FROM calls c
    LEFT JOIN person p on c.caller_id = p.id
    union all
    select a.callee_id as id, 
    a.duration, 
    LEFT(p.phone_number, 3) as country_code
    FROM calls c
    LEFT JOIN person b on a.callee_id = p.id
),
duration_avg_country as (
    select country_code, 
    sum(duration) / count(id) as duration_avg_country
    from call_log
    group by country_code
)

SELECT p.name as country
from duration_avg_country as a
```

**期望行为**
描述你期望的结果

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
你好，issue 描述不清晰， 需提供截图以及更详细说明。
