### ISSUE TITLE
Missing Full Constraints - 455. Assign Cookies

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1172]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

455. Assign Cookies
https://leetcode.com/problems/assign-cookies/

Please add constraints:

- What is the range of g.length & s.length?
- What is the range of the values of g & s?   Only g min value is given as 1 for now.

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JavaScript

#### Expected behavior

- To avoid TLE errors, we need to have max length values.
- The problem must contain detailed constraints.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
