### ISSUE TITLE
Missing Test Case - 1523. Count Odd Numbers in an Interval Range

### ISSUE THREAD

**Issue by emp0107** [LeetCode-Feedback/LeetCode-Feedback#11727]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
var countOdds = function(low, high) {
    let count=0
    for(let i=low;i<=high;i++){
        if(i%2==1){
            count++
        }

    }
    return count
};
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
