### ISSUE TITLE
Missing Test Case - 67. Add Binary

### ISSUE THREAD

**Issue by autf** [LeetCode-Feedback/LeetCode-Feedback#11728]
#### Your LeetCode username

autf

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Constraints said `1 <= a.length, b.length <= 10⁴`, but no test case has length exceeding 128.

#### Code you used for Submit/Run operation

```rust
impl Solution {
    pub fn add_binary(a: String, b: String) -> String {
        format!("{:b}", u128::from_str_radix(&a, 2).unwrap() + u128::from_str_radix(&b, 2).unwrap())
    }
}
```
https://leetcode.com/problems/add-binary/submissions/897549011/

#### Language used for code

Rust

#### Expected behavior

Runtime Error when `a.len() > 128` or `b.len() > 128`.
```Line 3, Char 53: called `Result::unwrap()` on an `Err` value: ParseIntError { kind: PosOverflow } (solution.rs)```

#### Screenshots

None.

#### Additional context

The code is from Sample 2.2 MB submission of Rust.

**Comment by sudhackar** [comment]
The testcase could be
```
a = "11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
b = "1"
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
