### ISSUE TITLE
leetcodes-interview-crash-course-data-structures-and-algorithms/705/hashing/4645/

### ISSUE THREAD

**Issue by donletts** [LeetCode-Feedback/LeetCode-Feedback#11737]
![image](https://user-images.githubusercontent.com/3728162/218745328-65b61d6b-3ccd-4bca-b908-66b558b11678.png)
the slide deck for the optimization of `Example 2: [2260. Minimum Consecutive Cards to Pick Up](https://leetcode.com/problems/minimum-consecutive-cards-to-pick-up/)` is missing a `+1` in calculating the window size. ie instead of `ans = min(ans, i - dic[cards[i]])` it should be `ans = min(ans, i - dic[cards[i]] + 1)`. in the slide deck it looks like `ans = min(3, 4 - 1) = 3` it should actually be `ans = min(3, 4 - 1 + 1)`. also extra feedback, the numbers in the array should be different than the indices because it is confusing to read (ie use numbers between 5 and 10).

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
