### ISSUE TITLE
Missing Test Case - 67. Add Binary

### ISSUE THREAD

**Issue by dvishal485** [LeetCode-Feedback/LeetCode-Feedback#11738]
#### Your LeetCode username
dvishal485

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
[Missing Test Case - 67. Add Binary](https://leetcode.com/problems/add-binary/)
There are not enough test cases to test the solution with, one can parse the current test cases as `i128` and still get the solution accepted, where as as per the question constraints but as per the `1 <= a.length, b.length <= 10^4`, this should not be the case.

If I consider any one of `a` or `b` to be of length greater than 128, the solution done via parsing as `i128` should fail.

#### Code you used for Submit/Run operation
```rust
// struct Solution;

impl Solution {
    pub fn add_binary(a: String, b: String) -> String {
        let n1 = i128::from_str_radix(&a, 2).unwrap();
        let n2 = i128::from_str_radix(&b, 2).unwrap();
        let mut n1 = n1 + n2;
        let mut res = String::new();
        if n1 == 0 {
            return "0".to_string();
        }
        while n1 > 0 {
            res.push(if n1 & 1 == 1 { '1' } else { '0' });
            n1 = n1 >> 1;
        }
        res.chars().rev().collect()
    }
}

// fn main() {
//     assert!(Solution::add_binary("11".to_string(), "1".to_string()) == "100");
//     assert!(Solution::add_binary("1010".to_string(), "1011".to_string()) == "10101");
//     assert!(Solution::add_binary("0".to_string(), "0".to_string()) == "0");
// }
```

#### Language used for code
Rust

#### Expected behavior
Solution should be considered a wrong answer for the test case where `a.length` or `b.length` is greater than 128 ( but under 10^4 as per constraints ).

#### Screenshots

Solution fails a custom testcase

![Solution fails testcase](https://user-images.githubusercontent.com/26341736/218746453-2f67a814-0f3b-4911-8086-5537a82defe2.png)

Still getting solution accepted

![Still getting accepted](https://user-images.githubusercontent.com/26341736/218746945-a5b0023f-d787-41a3-b036-e95a5eac4494.png)

*Test Case :*

a =
```
"1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
```

b =
```
"1"
```

#### Additional context
Required testcases should be added.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
