### ISSUE TITLE
142. 环形链表 II

### ISSUE THREAD

**Issue by Ijustwantyouhappy** [LeetCode-Feedback/LeetCode-Feedback#1174]
** Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
题干和例子的返回值不符，令人困惑，不知道该按那个写。
- 题干表示：有环返回链表开始入环的第一个节点。 如果链表无环，则返回 null。
- 例子的返回值都是字符串，如tail connects to node index 1

**建议**
将例子的输入和解释全部去除，仅保留链表的示意图；例1的输出修改为`第二个节点`，例3的输出修改为`None`

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认的～

**Comment by feiceh** [comment]
题面已更新，ID：a_run 给予积分奖励，请查收。
