### ISSUE TITLE
Explore card update text

### ISSUE THREAD

**Issue by yashasvi97** [LeetCode-Feedback/LeetCode-Feedback#11753]
On the explore card `Array Insertions`, `Inserting Anywhere in the Array` subsection second paragraph - second sentence start: instead of **_your_** the text should be **_you_**.
Here is the explore card [link](https://leetcode.com/explore/learn/card/fun-with-arrays/525/inserting-items-into-an-array/3244/). The text goes like:

> As _**your**_ saw above 

But instead should be:

> As _**you**_ saw above

#### Category of the bug
- [ ] Question
- [ ] Solution
- Language
- [ ] Missing Test Cases 

#### Description of the bug
Just needs text update in explore cards. Minor change

#### Screenshots
<img width="1038" alt="Screenshot 2023-02-14 at 6 32 49 PM" src="https://user-images.githubusercontent.com/14198915/218886761-badb408a-b670-4ab7-96b8-7f71a7c8c75b.png">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
