### ISSUE TITLE
Typos in 2557. Maximum Number of Integers to Choose From a Range II

### ISSUE THREAD

**Issue by PyroGenesis** [LeetCode-Feedback/LeetCode-Feedback#11755]
#### Your LeetCode username
burhanlakda

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
There are 2 typos in explanation of example 1:

> 3 is in the range [1, 6], and do not appear in banned. The sum of the **_choosen_** integers is 3, which does not **_ecxeed_** maxSum.

#### Expected behavior

* choosen should be chosen
* ecxeed should be exceed

#### Screenshots

![image](https://user-images.githubusercontent.com/17806916/218906781-eb16d1ab-6884-4671-a8e9-51e07d723e1b.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
