### ISSUE TITLE
Missing Test Case - 2093. Minimum Cost to Reach City With Discounts

### ISSUE THREAD

**Issue by byegates** [LeetCode-Feedback/LeetCode-Feedback#11757]
#### Your LeetCode username

byegates

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

For test case:
  n=4
  highways = [[0,1,100],[1,2,4],[2,3,10000]]
  discounts = 1

Below AC code will fail.

#### Code you used for Submit/Run operation

```java
class Solution {
    record Cell(int i, int w, int k) {}
    public int minimumCost(int n, int[][] edges, int k) {
        List<Node>[] g = createGraph(n, edges, new List[n]);
        
        Queue<Cell> q = new PriorityQueue<>((a, b) -> a.w - b.w);
        q.offer(new Cell(0, 0, k));
        boolean[] visited = new boolean[n];

        while (!q.isEmpty()) {
            var cur = q.poll();
            if (cur.i == n-1) return cur.w;
            visited[cur.i] = true;

            for (var nei : g[cur.i]) {
                if (visited[nei.i]) continue;
                if (cur.k > 0)
                    q.offer(new Cell(nei.i, cur.w + nei.w/2, cur.k - 1));

                q.offer(new Cell(nei.i, cur.w + nei.w, cur.k));
            }

        }

        return -1;
    }

    record Node(int i, int w) {}
    private List<Node>[] createGraph(int n, int[][] edges, List<Node>[] g) {
        for (int i = 0; i < n; i++) g[i] = new ArrayList<>();

        for (var e : edges) {
            g[e[0]].add(new Node(e[1], e[2]));
            g[e[1]].add(new Node(e[0], e[2]));
        }

        return g;
    }
}
```

#### Language used for code

Java

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
