### ISSUE TITLE
Bad Approach 2 for 67. Add Binary

### ISSUE THREAD

**Issue by PyroGenesis** [LeetCode-Feedback/LeetCode-Feedback#11751]
#### Your LeetCode username
burhanlakda

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The Approach 2 for this problem is meant to solve a follow-up question where the interviewer asks you to add the binary strings without using the `+` operator.
The LeetCode solution simply tries to convert both binary numbers to decimal and 'adds' them via bit manipulation.

This is a bad approach because of several reasons:
* **Bad time-complexity:** This solution seems to have a worse time-complexity than bit-by-bit computation, which can be used to solve this follow-up
* **Does not work for large inputs:** This solution simply doesn't work for all languages if you use a large enough input. Using Python or `BigInteger` is just a workaround.
* **Goes against the spirit of the question:** Most likely the interviewer wants us to figure out the bit operations without using `+` operator, not simply bypass the question by converting and adding the values together.

#### Code you used for Submit/Run operation

I've added a bit-by-bit computation solution for this follow-up for your reference.

```py
class Solution:
    # Add binary WITHOUT addition
    def addBinary(self, a: str, b: str) -> str:
        a_rev = reversed(list(a))   # a, going from LSB -> MSB. Note that reversed() will give you an iterator
        b_rev = reversed(list(b))   # b, going from LSB -> MSB. Note that reversed() will give you an iterator
        n1, n2 = len(a), len(b)     # lengths of a and b

        res = []
        carry = 0
        for i in range(max(n1, n2)):
            # the bit-value of a and b at position i
            d_a, d_b = 0, 0

            # since reversed is an iterator, we use next() to get the actual values
            if i < n1 and next(a_rev) == '1':
                d_a = 1
            if i < n2 and next(b_rev) == '1':
                d_b = 1

            # the bit-value of res at position i
            # it is 1 if we have an odd number of 1s in d_a, d_b, carry
            d = d_a ^ d_b ^ carry
            # carry is 1 if at least 2 of d_a, d_b, carry is 1
            carry = (d_a & d_b) | (d_a & carry) | (d_b & carry)
            
            # add the appropriate char to res
            if d == 0:
                res.append('0')
            else:
                res.append('1')
        
        # if there was a carry left at the end, add it as the MSB
        if carry:
            res.append('1')
        
        # reverse the string created to get the final ans
        return ''.join(reversed(res))
    
```

#### Language used for code

Python3

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

After investigating, we decided to keep the solution without change. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
