### ISSUE TITLE
Type in 15. 三数之和

### ISSUE THREAD

**Issue by guluguru** [LeetCode-Feedback/LeetCode-Feedback#11756]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
"判断是否存在三元组 [nums[i], nums[j], nums[k]]" 
should be 
"判断是否存在三元组 [nums[i], nums[j], nums[k]"
("]]" should be "]")

**Comment by feiceh** [comment]
你好，在与相关团队核实后：此题没问题暂不处理， 最后面的 ]，对应最前面的 [
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
