### ISSUE TITLE
The test case to problem 1611 is wrong

### ISSUE THREAD

**Issue by lpihike** [LeetCode-Feedback/LeetCode-Feedback#1176]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

In the example 4, when n = 9, the minimum number of operations is 12,  as showed below, not 14.
1001
1011
1010
1110
1111
1101
0101
0111
0110
0010
0011
0001
0000

#### Code you used for Submit/Run operation

```

```

**Comment by zerotrac** [comment]
You cannot change from `1101` to `0101`.

**Comment by lpihike** [comment]
Not a bug since the constrain is that Change the ith bit in the binary representation of n if the (i-1)th bit is set to 1 and **the (i-2)th through 0th bits are set to 0**
