### ISSUE TITLE
Missing Test Case - 1604. Alert Using Same Key-Card Three or More Times in a One Hour Period

### ISSUE THREAD

**Issue by muller2333** [LeetCode-Feedback/LeetCode-Feedback#11762]
#### Your LeetCode username

muller2333

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

An accepted solution fails on the following testcase:
keyName=["daniel"]
keyTime=["10:00"]

#### Code you used for Submit/Run operation

```
import java.util.*;

class Solution {
    public List<String> alertNames(String[] keyName, String[] keyTime) {
        int length = keyName.length;
        Map<String, List<Integer>> map = new HashMap<>();
        for (int i = 0; i < length; i++) {
            String name = keyName[i];
            if (!map.containsKey(name)) {
                map.put(name, new ArrayList<>());
            }
            int hour = Integer.parseInt(keyTime[i].substring(0, 2));
            int minute = Integer.parseInt(keyTime[i].substring(3));
            map.get(name).add(hour * 60 + minute);
        }
        List<String> res = new ArrayList<>();
        for (String name : map.keySet()) {
            List<Integer> list = map.get(name);
            int size = list.size();
            if (size < 3) {
                res.add(name);
            } else {
                Collections.sort(list);
                for (int i = 0; i <= size - 3; i++) {
                    int target = list.get(i) + 60;
                    int search = Collections.binarySearch(list, target);
                    if (search < 0) {
                        search = -search - 2;
                    }
                    if (search - i >= 2) {
                        res.add(name);
                        break;
                    }
                }
            }
        }
        Collections.sort(res);
        return res;
    }
}
```

#### Language used for code

Java

#### Screenshots

![2023-02-15](https://user-images.githubusercontent.com/25950952/218990068-7fbf5d49-c63b-41ed-97e7-428ed24dd0d9.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
