### ISSUE TITLE
📄🔗: Improved Bio Section (Description) --> Profile Page

### ISSUE THREAD

**Issue by withrvr** [LeetCode-Feedback/LeetCode-Feedback#11764]
# Feedback as a Feature to add ~ by [@withrvr](https://leetcode.com/withrvr/)
- I requested on leetcode.com/discuss/ also
  - [https://leetcode.com/discuss/feedback/2959242/improved-bio-section-description-profile-page](https://leetcode.com/discuss/feedback/2959242/improved-bio-section-description-profile-page)
- but no response

##### *** ⏱️: 3 Min
---
# **🤔: Why ? .. it is needed**
---
- This discussion/Article, is to @leetcode .... as a (Feature/Update/Feeback)
- **to Start Conversation** ... 🙏💭: Share you views / thought / anything in comment
- 
- also it's not that Big Deal also to Implement it
- Reason because we share our profile to our 👈👈
	- friend
	- teacher
	- shows in Video
	- attached in Resume
- so that can show, (nice bio) bio we want to show on website
- **LeetCode, Website is like Community/Social Media , for Programmers like us**

<br>

---
# **❌: Currently**
---
- we can only do
	1. Small Description
	2. Adjustment for new line
- below are the images
-

![image](https://assets.leetcode.com/users/images/9c2328f9-9e6c-4b89-8a83-f48b0e90e659_1672158013.457664.png)
 
### OR

![image](https://assets.leetcode.com/users/images/0e7e133d-1f03-4d4a-9cc3-85a98800df93_1672157838.545266.png)

<br>

---
# **✔️: Improved**
---
-  Like other website do, ex: twitter or instagram 
- we can directly go to next line
- which look more nice / clean

### Ex: Twitter
![image](https://assets.leetcode.com/users/images/fb471f49-b70e-429a-b441-4d9465e1c233_1672157016.802912.png)

### Ex: Instagram
![image](https://assets.leetcode.com/users/images/cc36133c-b5cc-4aff-9b80-05a5d585554d_1672157574.2826993.png)

<br>

---
# **📊: Other Info**
---
- Wrote Article / **Requested** ... ( as a Feature / Update / Feedback / Discussion )
	- 📅: 27 Dec 2022
- Reply from **@LeetCode**
	- 🥴: Still Waiting . . .
- Reflected / Added in Website
	- Wait for Reply, first i guess . . .
- 
- It took me Time, Effort
- 😓: Specially Movitation for me ...  :/ 
- in a hope will it reach / Do Anyone care ?
- Sry, if there was any misunderstanding or mistake

---
# **💭: Comment**
---
- Please share you ( Views / Thought / ANYTHING ) below .. on this/related topic
- to let know others also what you thing
- **and start the conversation**
- also to reach it to @LeetCode
- to add this and many more feature like this

<br/><br/>

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
