### ISSUE TITLE
Missing Test Case - 8. String to Integer (atoi)

### ISSUE THREAD

**Issue by 9ony** [LeetCode-Feedback/LeetCode-Feedback#11779]
#### Your LeetCode username

9ony

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution {
    public int myAtoi(String s) {
		String result="";
		boolean signcheck=false;
		boolean zerocheck=false;
		for(int i=0;i<s.length();i++) {
			if(!signcheck&&(s.charAt(i)=='+'||s.charAt(i)=='-')) {
				result += s.charAt(i);
				signcheck=true;
			}else if(!zerocheck&&s.charAt(i)>48&&s.charAt(i)<58) {
				result += s.charAt(i);
				zerocheck=true;
				signcheck=true;
			}
			else if(zerocheck&&s.charAt(i)>=48&&s.charAt(i)<58) {
				result += s.charAt(i);
			}
		}
        //System.out.println(Integer.parseInt(result)); ???
		return Integer.parseInt(result);
	}
}
```

#### Screenshots

![atoiex](https://user-images.githubusercontent.com/97019540/219290902-3073a9fe-3a3e-44ed-87b5-bcdeeca75ba1.JPG)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output values.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!
