### ISSUE TITLE
leetcodes-interview-crash-course-data-structures-and-algorithms/705/hashing/4513/

### ISSUE THREAD

**Issue by donletts** [LeetCode-Feedback/LeetCode-Feedback#11773]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Hashing quiz in the data structures and algorithms crash course has incorrect answer based on the language used. Question is ambiguous and should be re-formatted so that it's language agnostic. the question asks "Which of the following can be stored as a key in a hash map?". when selecting array/list it says "Wrong Answer. Hash map keys must be immutable." however in C++ maps can take vectors as keys. 

#### Language used for code

C++

#### Screenshots

![image](https://user-images.githubusercontent.com/3728162/219207887-375f3bd1-1803-494a-ade2-1610f362749a.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
