### ISSUE TITLE
Missing Test Case - 面试题 04.01. Route Between Nodes LCCI

### ISSUE THREAD

**Issue by ChenYichengX** [LeetCode-Feedback/LeetCode-Feedback#11782]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
chen-4fm

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述**
当两个节点出现闭环时（也就是自环），我的代码会出现死循环情况，但还是通过了测试用例

**你使用的语言**
java

**你提交或者运行的代码**
```
//  面试题 04.01. Route Between Nodes LCCI
class Solution {
    public boolean findWhetherExistsPath(int n, int[][] graph, int start, int target) {
        // DFS
        return helper(graph, start, target);
    }

    private boolean helper(int[][] graph, int start, int target) {
        for (int i = 0; i < graph.length; i++) {
            // 满足相连
            if (graph[i][0] == start && graph[i][1] == target) {
                return true;
            }
            // 从终点往前递归查起点，
            if (graph[i][1] == target && helper(graph, start, graph[i][0])) {
                return true;
            }
        }
        return false;
    }
}
```

**期望行为**
如果测试用例为： 
输入：n = 4, graph = [[2, 3], [0, 2], [2, 0], [1, 3]], start = 1, target = 3
我的代码在本地运行会  java.lang.StackOverflowError，但提交还是通过了。

**屏幕截图**

**额外的上下文**
代码逻辑为：查找 target 节点往前搜索，遇到自环会死循环。

**Comment by feiceh** [comment]
你好，当前题目已更新，积分奖励已发放，请查收
