### ISSUE TITLE
Repeated word in 2536. Increment Submatrices by One

### ISSUE THREAD

**Issue by PyroGenesis** [LeetCode-Feedback/LeetCode-Feedback#11785]
#### Your LeetCode username
burhanlakda

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
There is a repeated word ('for') in the explanation of the operation here:

> Add 1 to every element in the submatrix with the top left corner (row1i, col1i) and the bottom right corner (row2i, col2i). That is, add 1 to mat[x][y] **for for** all row1i <= x <= row2i and col1i <= y <= col2i.

#### Screenshots

![image](https://user-images.githubusercontent.com/17806916/219442495-258a5fcf-f481-4433-9993-9f6a05bb4245.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
