### ISSUE TITLE
Incorrect Variable Name - 1105. Filling Bookcase Shelves

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#11783]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In [1105. Filling Bookcase Shelves](https://leetcode.com/problems/filling-bookcase-shelves), the second variable name in Example 1 is "shelf_width", which should be "shelfWidth".

#### Expected behavior
Change the variable name "shelf_width" to "shelfWidth".

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
