### ISSUE TITLE
Missing Test Case - 152. Maximum Product Subarray

### ISSUE THREAD

**Issue by Nilanshuyadav** [LeetCode-Feedback/LeetCode-Feedback#11788]
#### Your LeetCode username
Nilanshu_yadav08

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Some testcases are missing, The code gets accepted, but showing wrong answer on some testcase.

#### Code you used for Submit/Run operation

```
class Solution {
    public int maxProduct(int[] nums) {
        int first_negative=-5, count_negative=0;
        int product=1, max=Integer.MIN_VALUE, neg_index=-1;
        
        for(int ind=0; ind<nums.length; ind++){
            if(nums[ind]==0){
                product = 1;
                first_negative=-5;
                count_negative=0;
                max = Math.max(max, 0);
                continue;
            }    
            
            if(nums[ind]<0){
                count_negative++;
                if(first_negative==-5){
                    first_negative = product*nums[ind];
                    neg_index = ind;
                }
            }
            
            product *= nums[ind];
            
            if(count_negative%2==0){
                max = Math.max(max, product);
            }
            else{
                max = Math.max(max, ind==neg_index?product:product/first_negative);
            }
        }
        
        return max;
    }
}
```

#### Language used for code

java

#### Expected behavior

The present testcases are only focusing on '-1' as the minimum value,
but there should be testcases which checks on every number from '-10' to '10'.

the testcases below is expected to give a answer '432' as a product of range 3 -> 6.
but showing the result '240' taking a range of 2 -> 5.
```
[1,0,-5,2,3,-8,-9]
```

#### Screenshots

![leetcode_max_product](https://user-images.githubusercontent.com/91049897/219461664-2280b959-2779-4b89-8a5e-5116ac19e3c7.jpg)

![leetcode_max_product2](https://user-images.githubusercontent.com/91049897/219461712-a7595224-d2c8-4d35-878d-22cb6927f81a.jpg)

#### Additional context

testcases should be checked for every integer from range -10 to -1, as the minimum criteria.
some of the testcases which fails are:
```
[1,0,-5,2,3,-8,-9]
[-5,-7,-6]
[-5,-1,7,1,8,-6]
[0,-5,-2,7,1,8,-6]
```

**Comment by stormsunshine** [comment]
The test case is as follows.

```
[1, 0, -5, 2, 3, -8, -9]
```

Please provide the test case in text so that it will be more convenient to copy the test case.

**Comment by Nilanshuyadav** [comment]
some of the testcases which fails are:
```
[1,0,-5,2,3,-8,-9]
[-5,-7,-6]
[-5,-1,7,1,8,-6]
[0,-5,-2,7,1,8,-6]
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
