### ISSUE TITLE
Missing testcase 1307. Verbal Arithmetic Puzzle 

### ISSUE THREAD

**Issue by Saharsh-R** [LeetCode-Feedback/LeetCode-Feedback#1178]
#### Your LeetCode username
 Saharsh-R 

#### Category of the bug
-  [x] Question
-  [ ] Solution
-  [ ] Language

#### Description of the bug
When I looked through the solution I looked at [awice's solution](https://leetcode.com/problems/verbal-arithmetic-puzzle/discuss/463920/Python-Backtracking).
I saw it did not work for the testcase
```
["AA","BB"]
"AA"
```
Then I though he checked for the leading zero case but what if the length of the word is one itself? Then in this case there is no leading zero but the number is itself zero.

#### **So I thought about this following test case.** 
```
["A","B"]
"A"
```
Even a person like awice forgot about such corner testcase.
#### Code you used for Submit/Run operation

This is same code as given in [awice's solution](https://leetcode.com/problems/verbal-arithmetic-puzzle/discuss/463920/Python-Backtracking) but just modified for the corner testcases.
```
class Solution(object):
    def isSolvable(self, words, result):
        words.append(result)
        R, C = len(words), max(map(len, words))

        assigned = {}
        assigned_inv = [None] * 10

        def search(column, row, bal):
            if column >= C:
                return bal == 0
            if row == R:
                return bal % 10 == 0 and search(column + 1, 0, bal // 10)

            word = words[row]
            if column >= len(word):
                return search(column, row + 1, bal)

            letter = word[~column]
            sign = 1 if row < R - 1 else -1
            if letter in assigned:
                if (assigned[letter] or len(word) == 1 or column != len(word) - 1):
                    return search(column, row + 1, bal + sign * assigned[letter])
                return False
            else:
                for d, ad in enumerate(assigned_inv):
                    if ad is None and (d or len(word) == 1 or column != len(word) - 1):
                        assigned_inv[d] = letter
                        assigned[letter] = d
                        if search(column, row + 1, bal + sign * d):
                            return True
                        assigned_inv[d] = None
                        del assigned[letter]

            return False

        return search(0, 0, 0)
```

#### Language used for code
Python3

#### Expected behavior
The code should definitely check for leading zeros but it should also check that the number zero itself is also allowed. "00" is not allowed but "0" is allowed

**Comment by lc-kay** [comment]
Hi @Saharsh-R 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Saharsh-R 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
