### ISSUE TITLE
测试数据遗漏 - 面试题 17.10. 主要元素

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#1179]
** Bug 类型**
- [x] 测试数据

**描述**
题目的测试数据有遗漏。根据题目描述，如果给定的数组没有主要元素，应返回-1，但是有些不包含主要元素的测试数据并没有被测试，导致直接用摩尔投票算法做的时候可以通过。由于不保证输入一定有主要元素，因此在使用摩尔投票算法找到可能的主要元素之后，需要再次遍历数组验证该元素是否是主要元素。
代码暂时不提供。

**希望添加的测试数据**

**输入**
```
[2,2,2,3,3,4,4]
```

**输出**
```
-1
```

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认的～

**Comment by feiceh** [comment]
你好，已添加测试用例。
