### ISSUE TITLE
Missing Test Case - 783. Minimum Distance Between BST Nodes

### ISSUE THREAD

**Issue by ejhuzed** [LeetCode-Feedback/LeetCode-Feedback#11794]
#### Your LeetCode username
[ejhuzed](https://leetcode.com/ejhuzed/)

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug
The following AC code cannot pass the test case:
root = `[100000, 0]`.

#### Code you used for Submit/Run operation
```python3
# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
class Solution:
    def minDiffInBST(self, root: Optional[TreeNode]) -> int:
        res, prev = 10**5, -99999
        def inorder(node):
            nonlocal res, prev
            if node.left:
                inorder(node.left)
            res = min(res, node.val - prev)
            prev = node.val
            if node.right:
                inorder(node.right)
        
        inorder(root)
        
        return res
```

#### Language used for code
Python3

#### Expected behavior
The submisson should get WA.

#### Screenshots
![LC-783-AC](https://user-images.githubusercontent.com/108965511/219526434-439ba192-312e-482a-a45d-5305f3378e59.PNG)
![LC-783-WA](https://user-images.githubusercontent.com/108965511/219526509-ddb45601-ff40-484a-93cd-e2dce1464d0d.PNG)

#### Additional context
The initialization in the above code can be modified as:
```python3
res, prev = 10**5, -10**5  // prev should not larger than -10**5
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
