### ISSUE TITLE
Data Structures and Algorithms course: Binary trees - DFS

### ISSUE THREAD

**Issue by jurajmajerik** [LeetCode-Feedback/LeetCode-Feedback#11798]
Data Structures and Algorithms course: Binary trees - DFS
Question - in the **Binary trees - DFS** chapter, you state the following:

"Sometimes you will need to process the children first, so you will use postorder traversal. There's other use cases as well, but if you're using recursion (**which you should be**), then switching between the three types is trivial (just swap the order in which logic is happening in the function)."

Why are you stating that we should be using recursion? Iterative approach might still be very applicable for large trees, where you might run out of space on the call stack.

That said, iterative traversals of trees are hard. How likely am I to encounter them in interviews?

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

"Recursion is recommended as the default approach, especially for beginners as it is much easier to implement and works well with the recursive nature of trees"

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
