### ISSUE TITLE
Name and description of the question Mismatch

### ISSUE THREAD

**Issue by tharun49** [LeetCode-Feedback/LeetCode-Feedback#11799]
#### Your LeetCode username

Tharun49

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

https://leetcode.com/problems/minimum-distance-between-bst-nodes/
Question says minimum distance  but in the description it says minimum value

`
Given the root of a Binary Search Tree (BST), return the minimum difference between the values of any two different nodes in the tree.
`
So I would request you to change the question name appropriately as the description is correct.

Finally thanks for this amazing platform.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The statement is correct. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
