### ISSUE TITLE
Mispelled variable in 2533. Number of Good Binary Strings

### ISSUE THREAD

**Issue by PyroGenesis** [LeetCode-Feedback/LeetCode-Feedback#11792]
#### Your LeetCode username
burhanlakda

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the very first line of the question, one of the variables has been mispelled:

> You are given four integers **_`minLenght`_**, `maxLength`, `oneGroup` and `zeroGroup`.

#### Expected behavior

`minLenght` should be spelled `minLength`

#### Screenshots

![image](https://user-images.githubusercontent.com/17806916/219510911-647787f1-3e34-46d3-bdb6-f30a78213bfd.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
