### ISSUE TITLE
783. Minimum Distance Between BST Nodes - Incomplete Test Case

### ISSUE THREAD

**Issue by Lakshya-Choraria** [LeetCode-Feedback/LeetCode-Feedback#11804]
#### Your LeetCode username
coderinterview

#### Category of the bug
- [.] Missing Test Cases 

#### Description of the bug

Missing Test Case for given question, In the given code I initalized the answer to 1000 and compared it to all remaining combination of nodes. As the given range for Nodes.val is upto 10^5, this should not work as difference between any 2 numbers should also be upto 10^5. As such kindly add a test case with a big anwer, preferabbly 10^5.

#### Code you used for Submit/Run operation
```
/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
class Solution {
public:
    int ans=1000;
    pair<int, int> solve(TreeNode* r){
        if(r==nullptr) return {10000001,-10000001};
        pair<int, int> a = solve(r->left);
        pair<int, int> b = solve(r->right);
        ans = min(ans,min(r->val-a.second,b.first-r->val));
        if(a.first == 10000001) a.first = r->val;
        if(b.second == -10000001) b.second = r->val;
        return {a.first,b.second};
    }
    int minDiffInBST(TreeNode* root) {
        pair<int, int> a=solve(root);
        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior
Submission Failed but submission was accepted.

#### Screenshots
Link: https://leetcode.com/problems/minimum-distance-between-bst-nodes/submissions/899690716/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

Do you mean the test case: [10000,0]?

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Lakshya-Choraria** [comment]
Yes, my code fails for any test case where answer is >1000, including [10000,0].
But I was still able to submit successfully.
![image](https://user-images.githubusercontent.com/53308467/219782887-c5801620-78b8-4a3f-8615-b4a227d75aa1.png)
Here is screenshot for failed test case.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
