### ISSUE TITLE
Missing Test Case - 1654. Minimum Jumps to Reach Home

### ISSUE THREAD

**Issue by kautsiitd** [LeetCode-Feedback/LeetCode-Feedback#11803]
#### Your LeetCode username

KautsIITD

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Following solution is giving Error in case a<b and max(forbidden)+a+b < x.
But [this solution](https://leetcode.com/problems/minimum-jumps-to-reach-home/submissions/899656754/) passed all TestCases.
Ex: Forbidden = [1]
a = 3
b = 5
x = 13

#### Code you used for Submit/Run operation

```
def bLessA(self, forbidden, a, b, x):
        limit = x+b+2
        visited = [True]+[False for i in range(limit-1)]
        for node in forbidden:
            if 0<=node<limit:
                visited[node] = True
        fringe = [[0, True]]
        depth = 0
        while fringe!=[]:
            nextFringe = []
            for node, isBackAllowed in fringe:
                prevNode = node-b
                if prevNode == x:
                    return depth+1
                elif prevNode>=0 and not visited[prevNode] and isBackAllowed:
                    visited[prevNode] = True
                    nextFringe.append([prevNode, False])

                nextNode = node+a
                if nextNode == x:
                    return depth+1
                elif nextNode<limit and not visited[nextNode]:
                    visited[nextNode] = True
                    nextFringe.append([nextNode, True])
            fringe = nextFringe
            depth += 1
        return -1
    
    def aLessB(self, forbidden, a, b, x):
        limit = max(forbidden)+a+b+2
        visited = [False for i in range(limit)]
        for node in forbidden:
            if 0<=node<limit:
                visited[node] = True
        visited[x] = True
        fringe = [[x, True]]
        depth = 0
        while fringe!=[]:
            nextFringe = []
            for node, isForwardAllowed in fringe:
                nextNode = node+b
                if nextNode<limit and not visited[nextNode] and isForwardAllowed:
                    visited[nextNode] = True
                    nextFringe.append([nextNode, False])

                prevNode = node-a
                if prevNode == 0:
                    return depth+1
                elif prevNode>=0 and not visited[prevNode]:
                    visited[prevNode] = True
                    nextFringe.append([prevNode, True])
            fringe = nextFringe
            depth += 1
        return -1

    def minimumJumps(self, forbidden, a, b, x):
        if x==0: return 0
        if b<=a: return self.bLessA(forbidden, a, b, x)
        else: return self.aLessB(forbidden, a, b, x)
```

#### Language used for code

Python

#### Expected behavior

It should have given
`list assignment index out of range`
Because, limit is based on forbidden Array only in case aLessB. But It Passed all Test cases.

#### Screenshots

<img width="1019" alt="Screenshot 2023-02-17 at 3 41 46 PM" src="https://user-images.githubusercontent.com/15329761/219615921-ba3c5697-013a-4027-9989-233da6a64a19.png">

<img width="1019" alt="Screenshot 2023-02-17 at 3 42 00 PM" src="https://user-images.githubusercontent.com/15329761/219615853-2d8f3f9e-e690-4488-af74-4af7f0f15f00.png">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
