### ISSUE TITLE
Possibility of Problem misinterpretation 783. Minimum Distance Between BST Nodes

### ISSUE THREAD

**Issue by Mitternachtsmond** [LeetCode-Feedback/LeetCode-Feedback#11806]
#### Your LeetCode username

nichamp

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the problem statement of 783. Minimum Distance Between BST Nodes, the term **minimum difference** is used as absolute difference as per the example cases, but since **absolute** word is not mentioned, answer for **minimum difference** can be negative too.
Like for example 1: minimum difference can be -5 (1-6)
and for example 2: minimum difference can be -49 (0-49)

#### Expected behavior

The minimum difference term should be explained in the problem statement, that is, find non-negative answer.

#### Screenshots

<img width="461" alt="image" src="https://user-images.githubusercontent.com/85838936/219750101-0cd7c4bc-2a0e-458d-acb5-50dc16d426fb.png">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

Difference means |a-b|.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
