### ISSUE TITLE
108. 将有序数组转换为二叉搜索树

### ISSUE THREAD

**Issue by zero-count** [LeetCode-Feedback/LeetCode-Feedback#1180]
** Bug 类型**
- [ ] 题目
- 108 将有序数组转换为二叉搜索树

**描述**
相同的答案，加上TreeNode定义后变为错误答案

**你使用的语言**
python3

**你提交或者运行的代码**
下面的代码是正确解答：
```python3
class Solution:
    def sortedArrayToBST(self, nums: List[int]) -> TreeNode:
        if not nums:
            return None

        mid = len(nums) // 2

        root = TreeNode(nums[mid])
        root.left = self.sortedArrayToBST(nums[:mid])
        root.right = self.sortedArrayToBST(nums[mid + 1:])

        return root
```
在开头加上这段代码之后，结果变成错误解答
```python3
class TreeNode:
    def __init__(self, x):
        self.val = x
        self.left = None
        self.right = None
```

**期望行为**
加上TreeNode定义之后应不影响答案的正确性

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认的～

**Comment by feiceh** [comment]
你好，该题目技术验证没有问题的，你给的貌似不是正确解法（是不是写错题号了？函数名也对不上。。

**Comment by zero-count** [comment]
> 你好，该题目技术验证没有问题的，你给的貌似不是正确解法（是不是写错题号了？函数名也对不上。。后续刷题学习中遇到问题，可通过阅读「题解」解决做题中的一些困惑，也可至 [力扣圈子](https://leetcode-cn.com/circle/discussions/questions/?orderBy=HOTTEST&query=) 进行题目交流，以获得更好的支持哟～

你好，是题号写错了，已更改为出问题的题号

**Comment by feiceh** [comment]
亲，该题技术反馈暂时无法处理，一般不建议加上 TreeNode 的定义，有些题定义加上没有报错，是因为使用了不同的序列化方法，感谢您的支持。
