### ISSUE TITLE
Missing Test Case - 530. Minimum Absolute Difference in BST

### ISSUE THREAD

**Issue by Rad0miR** [LeetCode-Feedback/LeetCode-Feedback#11800]
#### Your LeetCode username

Rad0miR

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

An accepted solution fails on the following testcase:
```
[0,null,100000]
```

#### Code you used for Submit/Run operation

```
public class Solution {
    public int GetMinimumDifference(TreeNode root) {
        int min = Int32.MaxValue;
        Dfs(root);
        return min;

        (int min, int max) Dfs(TreeNode node) 
        {
            if (node is null) return (100_000, -100_000);
            
            (int minl, int maxl) = Dfs(node.left);
            (int minr, int maxr) = Dfs(node.right);
            min = new[] { min, node.val - maxl, minr - node.val }.Min();
            return (Math.Min(minl, node.val), Math.Max(node.val, maxr));
        }
    }
}
```

#### Language used for code

C#

#### Expected behavior

Output: 0
Expected: 100000

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
