### ISSUE TITLE
Invalid Test Case - 468. Validate IP Address

### ISSUE THREAD

**Issue by srini047** [LeetCode-Feedback/LeetCode-Feedback#11807]
#### Your LeetCode username
[srini047](http://leetcode.com/srini047/)

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

`"2001:db8:85a3:0::8a2E:0370:7334"` => The following test case is an invalid test case as per the problem but using exter IP validator tools shows that this is valid. So would like to have a look at it.

#### Code you used for Submit/Run operation

// Validate IP Address
```
from ipaddress import ip_address, IPv4Address

class Solution:
    def validIPAddress(self, queryIP: str) -> str:
        try:
            return "IPv4" if type(ip_address(queryIP)) is IPv4Address else "IPv6"
        except ValueError:
            return "Neither"
```

#### Language used for code

python3

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
