### ISSUE TITLE
Error "process exited with signal SIGSEGV" in TypeScript

### ISSUE THREAD

**Issue by ethanmcrae** [LeetCode-Feedback/LeetCode-Feedback#11805]
#### Your LeetCode username
[ethanmcrae0](https://leetcode.com/ethanmcrae0/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Similar to [this issue](https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/7230), I'm getting the runtime error "process exited with signal SIGSEGV" in TypeScript with a simple algorithm. [This is the challenge I am attempting](https://leetcode.com/problems/distinct-subsequences/)

#### Code you used for Submit/Run operation
```ts
function numDistinct(s: string, t: string): number {
  const visitedSequences = new Map(); // Saves the indexes to remember which sequences have been already found
  let length: number = 0; // Increments with each new sequence found
  // Helper function (recursion)
  const splitStr = (indexes: number[], str: string): void => {
    // Break case: When `t` cannot be broken down further
    if (str.length === t.length) {
      // Determine if the `str` matches `t`
      if (str === t) {
        // If this subsequence hasn't been found, increment count and mark it as found
        if (!visitedSequences.get(indexes)) {
          visitedSequences.set(indexes, true);
          length++;
        }
      }
      return // Exit early - our work here is done
    }

    // Recurse case: Break down string until it has hit the length of `t`
    for (let i = 1; i < str.length; i++) {
      // Remove string at index
      const subStr: string = str.slice(0, i) + str.slice(i) 
      // Recurse
      splitStr(indexes.filter(x => x !== i), subStr);
    }
  }

  splitStr(new Array(s.length).fill(null).map(i => i), s);
  // Return length
  return length;
};
```

#### Language used for code
TypeScript

#### Expected behavior
A working execution (to at least point me to some type of code error)

#### Screenshots
<img width="927" alt="Screenshot 2023-02-17 at 11 07 28 AM" src="https://user-images.githubusercontent.com/55862827/219743175-3833e57b-163c-4341-8917-4cc0a0de88ca.png">
<img width="1265" alt="Screenshot 2023-02-17 at 11 13 05 AM" src="https://user-images.githubusercontent.com/55862827/219745006-8e33d1bb-e17d-4613-970e-e785bd9a3047.png">

#### Additional context
Quoting from [timfenney](https://github.com/timfenney)'s comment in [his related issue](https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/7230) (replace JavaScript with TypeScript):
Please tell the team it is Javascript and not C++ or something. Javascript on its own shouldn't be able to segfault, as we can't specify memory addresses in the first place.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

Please feel free to refer to the discussion section of the problem to see how other users have optimized their codes!
