### ISSUE TITLE
Higher time complexity solution is showing better runtime than lower complexity solution

### ISSUE THREAD

**Issue by Akhil-Raj** [LeetCode-Feedback/LeetCode-Feedback#11818]
#### Your LeetCode username

goder

#### Category of the bug
- [ X] Question
- [ ✓] Solution
- [ X] Language
- [ X] Missing Test Cases 

#### Description of the bug

For the binary search problem : [binary search](https://leetcode.com/problems/binary-search/description/)
The O(n) time complexity solution is showing better runtime than O(logn) time complexity solution

#### Code you used for Submit/Run operation

O(n) Solution :
```
class Solution:
    def search(self, nums: List[int], target: int) -> int:
        for ind, val in enumerate(nums):
            if val == target:
                return ind
        return -1
```

O(logn) Solution :
```
class Solution:
    def search(self, nums: List[int], target: int) -> int:
        st = 0; en = len(nums) - 1
        while(st <= en):
            midInd = (st + en) // 2
            if nums[midInd] == target:
                return midInd
            if target < nums[midInd]:
                en = midInd - 1
                continue
            if target > nums[midInd]:
                st = midInd + 1
                continue
        return -1
```

#### Language used for code

Python

#### Expected behavior

The better time complexity solution should show better runtime than the worse time complexity solution.

#### Screenshots

For O(n) solution :

<img width="1440" alt="Screenshot 2023-02-18 at 3 18 08 PM" src="https://user-images.githubusercontent.com/20275632/219853770-584657bc-7e22-4bac-99a5-8b072982c1a6.png">

For O(logn) solution :

<img width="1440" alt="Screenshot 2023-02-18 at 3 18 26 PM" src="https://user-images.githubusercontent.com/20275632/219853782-abb91cde-4206-42b3-adc9-d5b92ed330bd.png">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

It's not a judge problem. 

Please feel free to refer to the discuss section of the problem to see how other users have optimized their codes!

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
