### ISSUE TITLE
692_测试用例出现错误

### ISSUE THREAD

**Issue by boer1011** [LeetCode-Feedback/LeetCode-Feedback#11814]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**boer1011**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [692 ] 题目
- [class Solution:
    def topKFrequent(self, words: List[str], k: int) -> List[str]:
        dic = {}
        nums= []
        new_list = []
        new_list1 = []
        new_list3 = []
        List1 = words
        for i in List1:
            if i not in dic:
            
                dic[i] = 1
            else:
                temp = dic[i]
                dic[i] = temp + 1
        # print(dic)
        # 统计重复元素次数

        for i in dic:
            nums.append(dic[i])

        nums.sort(reverse=True)
        # 按照出现频次逆序排列（左大右小）
        # 将words去重，并且保持元素次序
        # left = 0
        # right = 0
        # new_list4 = []
        words1 = []
        for i in words:
            if i not in words1:
                words1.append(i)
        words = words1

        count = 0
        j = 0
        
        while count < k:
            for j in dic:
                if dic[j] == nums[count]:
                    
                    new_list.append(j)
                    dic[j] = []
                    break
            count = count + 1

        for i in new_list:
            new_list1.append(i)
            
        for i in words:
            if i not in new_list:
                new_list1.append(i)
 
        for i in range(len(new_list)):

            for j in range(len(new_list1)):
                
                if dic[new_list[i]] == dic[new_list1[j]] and new_list[i] != new_list1[j]:
                   
                    new_list3.append(new_list1[j])                    
                    if words.index(new_list[i]) > words.index(new_list1[j]) and new_list1[j] not in new_list3:
                    
                        new_list[i] = new_list1[j]
                        
                    else:
                        break
        return new_list

 ] 题解
- [python3] 编程语言
- [ ] 缺少测试用例

**描述**
["i","love","leetcode","i","love","coding"]，k=3的情况下，预期结果应该是["i","love","leetcode"],给出的结果是["i","love","coding"],这违反了题目要求按照字典顺序的要求！

**你使用的语言**
python3

**你提交或者运行的代码**

**期望行为**
无法通过提交

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by boer1011** [comment]
字典顺序，这里我将它理解为了列表原来的顺序。其实不是的，在计算机语言中，按照字母表顺序。例如a<b<c...

**Comment by feiceh** [comment]
你好，在与相关团队核实后：此题没问题暂不处理，“是的， 字典顺序 是按 a<b<c...“ 
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
