### ISSUE TITLE
Missing index : 452. Minimum Number of Arrows to Burst Balloons

### ISSUE THREAD

**Issue by kichankwon** [LeetCode-Feedback/LeetCode-Feedback#1181]
#### Your LeetCode username
fabulousK

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
In Constraints, the index of "points" is omitted.
As-is : points.length == 2
To-be : points[i].length == 2

#### Screenshots

![image](https://user-images.githubusercontent.com/35328573/95651782-86e95200-0b27-11eb-9ec1-1bc0b8b09d90.png)

**Comment by lc-kay** [comment]
Hi @kichankwon 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @kichankwon 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
