### ISSUE TITLE
Failed Test Case - 783. Minimum Distance Between BST Nodes

### ISSUE THREAD

**Issue by BurakOZN** [LeetCode-Feedback/LeetCode-Feedback#11813]
#### Category of the bug
- [x] Failed Test Cases 

#### Description of the bug

[90,69,null,49,89,null,52]
![image](https://user-images.githubusercontent.com/48183286/219794489-0d6fce09-1cdf-4875-a18a-c6204a62ecd5.png)

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by BurakOZN** [comment]
My solution for C#
public class Solution {
    public int MinDiffInBST(TreeNode root) {
        return GetDifference(root,root.val,true);
    }
    public static int GetDifference(TreeNode treeNode, int parentVal,bool isFirst=false)
    {
        var myDistence = parentVal - treeNode.val > 0 ? parentVal - treeNode.val : treeNode.val - parentVal;
        if (treeNode.left == null && treeNode.right == null)
            return myDistence;
        int? minDistence = null;
        if (treeNode.left != null)
            minDistence = GetDifference(treeNode.left, treeNode.val);
        if (treeNode.right != null)
        {
            var rigthDistence = GetDifference(treeNode.right, treeNode.val);
            if (minDistence > rigthDistence || minDistence == null)
                minDistence = rigthDistence;
        }
        if (isFirst)
            return minDistence!.Value;
        return minDistence!.Value > myDistence  ? myDistence : minDistence!.Value;
    }
}

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output values.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!
