### ISSUE TITLE
Missing Test Case - 2567. Minimum Score by Changing Two Elements

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#11826]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets WA on the following testcase:
[100, 81, 12, 21, 6, 72, 70, 31, 34, 61, 15, 80, 12, 36, 100, 14, 7, 11, 19, 53, 25, 12, 88, 56, 62, 61, 46, 57, 10, 53, 46, 46, 63, 78, 50, 78, 91, 48, 34, 3, 89, 79, 10, 86, 93, 83, 38, 3, 8, 2, 13, 91, 34, 73, 84, 94, 51, 38, 46, 45, 62, 16, 45]

#### Code you used for Submit/Run operation

```
class Solution:
    def minimizeSum(self, nums: List[int]) -> int:
        dic={}
        for i in nums:
            if(i not in dic.keys()):
                dic[i]=1
            else:
                dic[i]+=1
        l=list(dic.keys())
        l.sort()
        n=len(dic.keys())
        
        if(n>=3):
            mins1,mins2,mins3=l[0],l[1],l[2]
            maxs1,maxs2,maxs3=l[-1],l[-2],l[-3]
        elif(n==2):
            mins1,mins2,mins3=l[0],l[1],l[1]
            maxs1,maxs2,maxs3=l[-1],l[-2],l[-2]   
        else:
            return 0
        
        
        min_num=min(dic[mins1],dic[maxs1])
        if(min_num>2):
            return maxs1-mins1
        elif(min_num==2):
            if(dic[mins1]==dic[maxs1]):
                return min(abs(maxs1-mins2),abs(maxs2-mins1))
            elif(dic[mins1]==2):
                return abs(maxs1-mins2)
            else:
                return abs(maxs2-mins1)
        else:
            if(dic[mins1]==dic[maxs1]):
                if(dic[maxs2]==1 and dic[mins2]==1):
                    return min(abs(maxs2-mins2),abs(maxs1-mins3),abs(maxs3-mins1))
                elif(dic[maxs2]==1):
                    return min(abs(maxs2-mins2),abs(maxs3-mins1))
                else:
                    return min(abs(maxs2-mins2),abs(maxs1-mins3))
            elif(dic[mins1]==1):
                if(dic[mins2]==1):
                    return abs(maxs1-mins3)
                else:
                    return abs(maxs1-mins2)
            else:
                if(dic[maxs2]==1):
                    return abs(maxs3-mins1)
                else:
                    return abs(maxs2-mins1)
```

#### Language used for code

Python3

#### Expected behavior

Output: 97
Expected: 92

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
