### ISSUE TITLE
Missing Test Case - 182. Duplicate Emails

### ISSUE THREAD

**Issue by zphw** [LeetCode-Feedback/LeetCode-Feedback#11833]
#### Your LeetCode username
xwangsd

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Missing test cases where EMAIL is NULL, for example, with the following database:
```
CREATE TABLE PERSON (
  ID INTEGER primary key,
  EMAIL VARCHAR(20)
);

INSERT INTO PERSON VALUES (-1 , NULL);
INSERT INTO PERSON VALUES (0 , NULL);
```

The outputs of
```SQL
SELECT EMAIL FROM PERSON GROUP BY EMAIL HAVING COUNT(EMAIL) > 1;
```
and
```SQL
SELECT EMAIL FROM PERSON GROUP BY EMAIL HAVING COUNT(*) > 1;
```
are different.

#### Code you used for Submit/Run operation
```SQL
SELECT EMAIL FROM PERSON GROUP BY EMAIL HAVING COUNT(*) > 1
```

```SQL
SELECT EMAIL FROM PERSON GROUP BY EMAIL HAVING COUNT(ID) > 1
```

#### Language used for code
MySQL

#### Expected behavior
Such solutions should receive Wrong Answer

#### Screenshots
<img width="924" alt="image" src="https://user-images.githubusercontent.com/49032034/219889018-64122113-9c0f-40a5-9d47-19fa2f45cd37.png">

<img width="932" alt="image" src="https://user-images.githubusercontent.com/49032034/219889141-cbd6d75a-41df-4187-ad44-fe203a44ade7.png">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
