### ISSUE TITLE
Missing Test Case - 175. Combine Two Tables

### ISSUE THREAD

**Issue by zphw** [LeetCode-Feedback/LeetCode-Feedback#11832]
#### Your LeetCode username
xwangsd

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Missing test cases that have same PERSON.FIRSTNAME, PERSON.LASTNAME, ADDRESS.CITY, ADDRESS.STATE, or a combination of them (since it's legitimate that people have the same name), so that it allows solutions incorrectly grouping by these attributes to pass.

#### Code you used for Submit/Run operation

```SQL
SELECT DISTINCT FIRSTNAME, LASTNAME, CITY, STATE FROM PERSON LEFT JOIN ADDRESS ON PERSON.PERSONID = ADDRESS.PERSONID
```

```SQL
SELECT PERSON.FIRSTNAME, PERSON.LASTNAME, ADDRESS.CITY, ADDRESS.STATE FROM PERSON LEFT JOIN ADDRESS ON PERSON.PERSONID = ADDRESS.PERSONID GROUP BY PERSON.FIRSTNAME, PERSON.LASTNAME
```

```SQL
SELECT PERSON.FIRSTNAME, PERSON.LASTNAME, ADDRESS.CITY, ADDRESS.STATE FROM PERSON LEFT JOIN ADDRESS ON PERSON.PERSONID = ADDRESS.PERSONID GROUP BY PERSON.FIRSTNAME, ADDRESS.CITY
```

```SQL
SELECT P.FIRSTNAME, P.LASTNAME, A.CITY, A.STATE FROM PERSON P LEFT JOIN ADDRESS A ON P.PERSONID = A.PERSONID UNION SELECT P.FIRSTNAME, P.LASTNAME, A.CITY, A.STATE FROM PERSON P LEFT JOIN ADDRESS A ON P.PERSONID = A.PERSONID
```

#### Language used for code
MySQL

#### Expected behavior
Such solutions should receive Wrong Answer.

#### Screenshots
<img width="919" alt="image" src="https://user-images.githubusercontent.com/49032034/219885343-59e66a5c-c733-471c-87ca-59a6d3d923a6.png">

**Comment by zphw** [comment]
The link is https://leetcode.com/problems/combine-two-tables/submissions/900548926/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
