### ISSUE TITLE
15. 三数之和：测试用例有点问题。

### ISSUE THREAD

**Issue by istomyang** [LeetCode-Feedback/LeetCode-Feedback#11835]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名

Istomyang

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例
- [x] 测试用例

**描述**
描述你遇到的 bug

这个测试用例是不是有点问题？：

输入：[0,0,0,0]
输出：（按位置） [[0, 1, 2], [0, 1, 3], [1, 2, 3]]
实际输出：（按结果）[0, 0, 0]
只有 i != j、i != k 且 j != k 这一个限制条件吧？

**你使用的语言**
Rust

**你提交或者运行的代码**
```rust
impl Solution {
    pub fn three_sum(nums: Vec<i32>) -> Vec<Vec<i32>> {
    // 走一遍nums，对于每个i，都可以退化为一个两数字之和的问题。

    use std::collections::{HashMap, HashSet};

    let mut map: HashMap<&i32, usize> = HashMap::with_capacity(nums.len());
    let mut ret: Vec<Vec<i32>> = vec![];

    // 防重
    let mut unique: HashSet<usize> = HashSet::new();

    for i in 0..nums.len() {
        let num_i = nums[i];

        for j in i + 1..nums.len() {
            let key = 0 - nums[j] - num_i;
            if map.contains_key(&key) && i != j {
                let k = *map.get(&key).unwrap();
                if i != k && k != j {
                    let kk = i + j + k;
                    if !unique.contains(&kk) {
                        ret.push(vec![num_i, nums[j], key]);
                        unique.insert(kk);
                    }
                }
            }
            map.insert(&nums[j], j);
        }
    }

    return ret;
    }
}
```

**期望行为**
描述你期望的结果

[[0,0,0],[0,0,0],[0,0,0]]（位置： [[0, 1, 2], [0, 1, 3], [1, 2, 3]]）

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by stormsunshine** [comment]
答案中不可以包含重复的三元组，即使元素位于不同下标，只要两个三元组的元素值相等，就是重复的三元组。

示例 1 已经说明了这一点，示例 1 给定的数组中有两个 -1，但是三元组 [-1,0,1] 只在答案中出现一次，而没有出现两次。

**Comment by istomyang** [comment]
> 答案中不可以包含重复的三元组，即使元素位于不同下标，只要两个三元组的元素值相等，就是重复的三元组。
> 
> 示例 1 已经说明了这一点，示例 1 给定的数组中有两个 -1，但是三元组 [-1,0,1] 只在答案中出现一次，而没有出现两次。

谢谢！
