### ISSUE TITLE
Wrong test case in description: [1616. Split Two Strings to Make Palindrome]

### ISSUE THREAD

**Issue by sekhar179** [LeetCode-Feedback/LeetCode-Feedback#1183]
#### Your LeetCode username
sekhar179

#### Category of the bug
- [x ] Question
- [ ] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

C++

#### Expected behavior

In the description the 2nd test case is wrongly mentioned (wrong expected output shown)
Example 2:

Input: a = "abdef", b = "fecab"
Output: false (it should be true) as splitting both string at index 2 makes substrings "ab" "def" and "fe" "cab"
So "fe" + "def" is a palindrome, so answer should be true.
I think the input is intended to be a = "xbdef", b = "xecab" for which the answer is false.

#### Screenshots

![image](https://user-images.githubusercontent.com/65918795/95669693-f9e2df00-0ba0-11eb-83cc-26054b0619a6.png)

**Comment by ravireddy07** [comment]
@sekhar179  The problem serial number is 1616.split-two-strings-to-make-palindrome . Update it.

**Comment by sekhar179** [comment]
@ravireddy07, thanks, updated the title.

**Comment by lc-pam** [comment]
Hi @sekhar179 
Thanks for reaching out to us. We have noticed the issue and updated the content. Thank you for your support!
