### ISSUE TITLE
Weak Test cases in 1616. Split Two Strings to Make Palindrome

### ISSUE THREAD

**Issue by uds5501** [LeetCode-Feedback/LeetCode-Feedback#1184]
#### Your LeetCode username

uds5501

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Wrong code passes on this test case : 
a = abcd
b = xyza

This TC should not return `True` but it did with the attached code

#### Code you used for Submit/Run operation

```
#Split Two Strings to Make Palindrome
class Solution:
    def checkPalindromeFormation(self, a: str, b: str) -> bool:
        a1 = True
        b1 = True
        n = len(a)
        for i in range(n//2):
            if (a[i] != a[n-i-1]):
                a1 = False
            if (b[i]!= b[n-i-1]):
                b1 = False
        if (a1 or b1):
            return True
        return a[0] == b[-1] or a[-1] == b[0]
```

#### Language used for code

Python3

#### Expected behavior

It should've returned `False` and given me a Wrong Answer Label, instead it passes.

#### Additional context

These types of TCs should be covered in the main contest!

**Comment by lc-kay** [comment]
Hi @uds5501 
I just ran your code and test case and it resulted in the Wrong Answer, with output = true. Please let me know if this is not the case on your end and I will reopen this issue. Thank you for your time.
