### ISSUE TITLE
Missing Test Case - 2569. Handling Sum Queries After Update

### ISSUE THREAD

**Issue by theabbie** [LeetCode-Feedback/LeetCode-Feedback#11840]
#### Your LeetCode username
theabbie

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
https://leetcode.com/problems/handling-sum-queries-after-update/
The testcases of this problem are very weak and (almost) brute forces solutions are able to pass.

#### Code you used for Submit/Run operation

```py
import numpy as np

class Solution:
    def handleQuery(self, nums1: List[int], nums2: List[int], queries: List[List[int]]) -> List[int]:
        curr = sum(nums2)
        arr = np.array(nums1)
        res = []
        for q, l, r in queries:
            if q == 1:
                arr[l:r+1] ^= 1
            if q == 2:
                curr += arr.sum() * l
            if q == 3:
                res.append(curr)
        return res
```

#### Language used for code
Python3

#### Expected behavior
https://leetcode.com/submissions/detail/900746978/
This is accepted solution but the same fails if we generate large testcases designed to take a long time for this solution.

#### Screenshots
<img width="956" alt="image" src="https://user-images.githubusercontent.com/17960677/219922772-bccba713-e148-47f0-94bc-3b9ad3c15cec.png">

#### Additional context
This is the code to generate the large testcase
```py
N = 10 ** 5
print([i % 2 for i in range(N)])
print([i % 2 for i in range(N)])
print([[1, 0, N - 1] for _ in range(N // 3)] + [[2, 1, 0] for _ in range(N // 3)] + [[3, 0, 0] for _ in range(N // 3)])
```

**Comment by theabbie** [comment]
@LC-Pam

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The solution gets AC on the given test case.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by theabbie** [comment]
Thank you for checking but TLEing on single testcase is not the point, it's just that there should be more than 1 testcase like this to eliminate brute force solutions, also it should not pass as it's clearly not efficient enough, so more testcases like these need to be added.
