### ISSUE TITLE
Missing Test Case - 9. Palindrome Number

### ISSUE THREAD

**Issue by KishanNayak04** [LeetCode-Feedback/LeetCode-Feedback#11849]
#### Your LeetCode username
Kishan_nayak1

#### Category of the bug
- [x ] Question

#### Description of the bug
What is up team I am new to coding and wanted help on what I was missing in the palindrome number problem. I kinda gave up at a point and started putting else ifs, so I would appreciate help on those too. I got stuck on the 123 testcase tho.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool isPalindrome(int x) {
        int length = 0;
        int j;
        int k = x; 


        while(k > 1) {
            k = k/10;
            length++; 
        }
        
      if ((x < 0 || x % 10 != 0) && x >= 9) {
          for(int i = 0; i < length; i++) {
             j = x % 10;
              return j;
          }
      }
      else if (x == 0) { 
          return true;
      }
      else if (x == 1) { 
          return true;
      }
      else if (x == 3) {
          return true;
      }
      else if (x == 8) {
          return true;
      }
      else if (x == 9) {
          return true;
      }

return {};
```

#### Language used for code
C++

#### Expected behavior
I expected all the tests to clear because 123 is greater than 0 and has a remainder after division by 10.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

Please feel free to refer to the discussion section of the problem to see how other users have optimized their codes!
