### ISSUE TITLE
Missing Test Case - 2573. Find the String with LCP

### ISSUE THREAD

**Issue by lucifer1004** [LeetCode-Feedback/LeetCode-Feedback#11851]
#### Your LeetCode username

lucifer1004

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets Runtime Error on the following testcase:

[tmp.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/10776260/tmp.txt)

#### Code you used for Submit/Run operation

```cpp
class UnionFind {
public:
    UnionFind(int n) {
        p = vector<int>(n);
        size = vector<int>(n, 1);
        iota(p.begin(), p.end(), 0);
    }

    void unite(int a, int b) {
        int pa = find(a), pb = find(b);
        if (pa != pb) {
            if (size[pa] > size[pb]) {
                p[pb] = pa;
                size[pa] += size[pb];
            } else {
                p[pa] = pb;
                size[pb] += size[pa];
            }
        }
    }

    int find(int x) {
        return p[x] == x ? x : p[x] = find(p[x]);
    }

    void reset(int x) {
        p[x] = x;
        size[x] = 1;
    }

private:
    vector<int> p, size;
};
class Solution {
public:
    string findTheString(vector<vector<int>>& lcp) {
        int n = lcp.size();
        UnionFind uf(n);
        for (int i = 0;i < n;i ++)
            for (int j = 0;j < n;j ++) {
                if (lcp[i][j]) {
                    // s[i] == s[j]
                    uf.unite(i, j);
                }
            }
        string s = "";
        map<int, char> mp;
        char c = 'a';
        for (int i = 0;i < n;i ++) {
            int rt = uf.find(i);
            if (mp.count(rt)) s += mp[rt];
            else {
                mp[rt] = c ++;
                s += mp[rt];
            }
        }
        vector<vector<int>> f(n, vector<int>(n, 0));
        for (int i = n - 1;i >= 0;i --)
            for (int j = n - 1;j >= 0;j --) {
                if (s[i] == s[j]) {
                    if (i < n - 1 and j < n - 1) f[i][j] = f[i + 1][j + 1] + 1;
                    else f[i][j] = 1;
                } else f[i][j] = 0;
            }
        if (f != lcp or c > 'z' + 1) s = "";
        
        return s;
    }
};
```

#### Language used for code
C++

#### Expected behavior
The code gets Runtime Error.

#### Screenshots
![Screenshot from 2023-02-19 14-22-57](https://user-images.githubusercontent.com/13583761/219932559-cd89bc25-11b3-43c5-bc62-5b515115d801.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
