### ISSUE TITLE
Break sometimes doesn't work in c#

### ISSUE THREAD

**Issue by maskalek** [LeetCode-Feedback/LeetCode-Feedback#11852]
#### Your LeetCode username
maskalek

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
`while` loop ignores `break` and keep iterating

#### Code you used for Submit/Run operation

```
public class Solution {
    public IList<IList<int>> ZigzagLevelOrder(TreeNode root) {
        while(true)
        {
            Console.WriteLine($"break {root.val}");
            break;
        }
        return null;

    }
}
```

#### Language used for code
C#

#### Expected behavior
Loop has only one iteration and one log in stdout

#### Screenshots
![image](https://user-images.githubusercontent.com/6655515/219935634-596442f2-2f56-4db6-b5e7-200a2b64a709.png)

#### Additional context
This version works as expected
```
public class Solution {
    public IList<IList<int>> ZigzagLevelOrder(TreeNode root) {
        while(true)
        {
            Console.WriteLine($"break");
            break;
        }
        return null;

    }
}
```

**Comment by stormsunshine** [comment]
The keyword `break` actually works. The reason is that for the third test case, the value of `root` is `null`, so a NullPointerException is thrown with the line `Console.WriteLine`, which is before the `break` statement. Since the `break` statement is not reached before the exception is thrown, it is not executed.

**Comment by maskalek** [comment]
@stormsunshine ah, you are right. I always forget and get confused, when I don't have separate tabs for results because of exception.
