### ISSUE TITLE
1616 运行有误

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#1186]
** Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
提交代码，执行结果显示解答错误，实际上输出和预期结果是一致的。
显示解答错误的测试用例：
```
"pvhmupgqeltozftlmfjjde"
"yjgpzbezspnnpszebzmhvp"
```
代码见下方，顺便说明，该代码并非正确代码，可见测试用例覆盖不全面，建议添加以下两组测试用例：
```
"abcdefg"
"gbcdefa"
```
```
"nabc"
"xyzn"
```

**你使用的语言**
Java

**你提交或者运行的代码**
```
class Solution {
    public boolean checkPalindromeFormation(String a, String b) {
        int n = a.length();
        char[] p = a.toCharArray();
        char[] q = b.toCharArray();
        if (n <= 1) {
            return true;
        }
        if (p[0] == q[n - 1] || p[n - 1] == q[0]) {
            return true;
        }
        return false;
    }
}
```

**期望行为**
对于上述测试用例（包括显示解答错误的用例和另外补充的两组测试用例），都应该在提交之后运行，且都应该有正确的结果。

**屏幕截图**
![image](https://user-images.githubusercontent.com/12067364/95670616-3f62d480-0bc0-11eb-88b2-bb308e919e8f.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，该题目技术验证当前没有问题了（1.这题解答错误的例子，没有复现 2. 错误的代码也是被卡了），因此 测试用例这里就不加新的了～
