### ISSUE TITLE
Missing Test Case - 2569. Handling Sum Queries After Update

### ISSUE THREAD

**Issue by Electron1997** [LeetCode-Feedback/LeetCode-Feedback#11863]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Some asymptotically suboptimal solutions (with complexity O(nums1.size() * queries.size()) ) that rely on bit manipulation operations pass all the tests (e.g. the code below or https://leetcode.com/contest/biweekly-contest-98/submissions/detail/900415633/). I'm not sure if this is intended, but I suspect that with the given constraints it is possible to construct test cases that would lead to a TLE verdict for most of those solutions. I have generated a few tests that catch some of the slower solutions that pass all the official tests. If such solutions are supposed to pass I would tighten the constraints a bit and maybe change the difficulty of this problem to medium. On the other hand, to make sure only O(queries.size() * log(nums1.size()) solutions pass it might be necessary to modify the constraints from 1e5 to 2e5 or more (I haven't found a test for whicht the C++ example below times out yet). Anyway, I attached a test that I generated which catches some solutions (e.g. this one https://leetcode.com/contest/biweekly-contest-98/submissions/detail/900415633/) to be added to the suite.

#### Example (C++)

```
class Solution {
    static constexpr int N = 100000;
public:
    vector<long long> handleQuery(vector<int>& nums1, vector<int>& nums2, vector<vector<int>>& queries) {
        int n = nums1.size();
        bitset<N> bits;
        for(int i = 0; i < n; ++i){
            if(nums1[i]) bits.set(i);
        }
        long long sum = 0;
        for(int x : nums2) sum += x;
        vector<long long> sol;
        for(auto query : queries){
            if(query[0] == 1){
                bitset<N> mask;
                mask.set();
                mask >>= N - (query[2] - query[1] + 1);
                mask <<= query[1];
                bits ^= mask;
            }else if(query[0] == 2){
                sum += query[1] * bits.count();
            }else if(query[0] == 3){
                sol.push_back(sum);
            }
        }
        return sol;
    }
};
```

#### Description of the tests
The files nums1.txt and nums2.txt contain input sequences of size 1e5 generated uniformly at random. The file queries.txt contains the sequence of queries (mostly type 1 queries with some type 2 and type 3 to mess with the branch predictor). This catches some of the "naive" bit-manipulation solutions. 
[nums1.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/10777518/nums1.txt)
[nums2.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/10777519/nums2.txt)
[queries.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/10777551/queries.txt)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

We reject this request. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
