### ISSUE TITLE
Expression Error in Solution of 1792. Maximum Average Pass Ratio

### ISSUE THREAD

**Issue by congliu0704** [LeetCode-Feedback/LeetCode-Feedback#11862]
**leetcode.cn username**
congliu0704

**Bug Type**
- [x] Solution

**Description**
The first expression in official solution ([Chinese version](https://leetcode.cn/problems/maximum-average-pass-ratio/solution/zui-da-ping-jun-tong-guo-lu-by-leetcode-dm7y3/)) is not expressing what it meant:
```
 pass + 1     pass
---------- - -------
 total + 1    total
```

**Expected Behavior**
Should be:
```
 pass + 1     pass
---------- > ------- , where total > pass
 total + 1    total
```

**Screenshot**
<img width="681" alt="Screenshot 2023-02-20 at 00 55 46" src="https://user-images.githubusercontent.com/4845325/219962629-5d848ced-2577-4e2b-b945-73869d901405.png">

**Comment by zuizaiqinshi** [comment]
尊敬的用户您好：
经力扣官方题解团队确认，上述内容无误，暂不进行调整。感谢您的反馈～
