### ISSUE TITLE
Missing Test Case - 394. Decode String

### ISSUE THREAD

**Issue by pipipuppypaul** [LeetCode-Feedback/LeetCode-Feedback#11867]
#### Your LeetCode username

Puppy_Yu

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

If the input string consists only a number, the expected result is empty string.
However, according to the description - For example, there will not be input like 3a or 2[4] -  the input should be interpreted as is, and a number should always be followed by '[',  which means 3 should not be interpreted as 3'' or 3[''].
So that '3' is not a valid test case and should be reported so.

#### Code you used for Submit/Run operation

```
# python code
class Solution:
    def decodeString(self, s: str) -> str:
        stack = []
        for item in s:
            if item == ']':
                temp = ""
                while stack[-1] != '[':
                    temp = stack.pop() + temp
                left_bracket = stack.pop()
                number = ""
                while stack and stack[-1].isnumeric():
                    number = stack.pop() + number
                stack.append(int(number) * temp)
            else:
                stack.append(item)
        return "".join(stack)
```

#### Language used for code

Python

#### Expected behavior

This should not be a valid test case. 

#### Screenshots

![image](https://user-images.githubusercontent.com/26019699/219972222-ecffe903-2f99-4ea6-9a61-08253394b43b.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
