### ISSUE TITLE
Missing Test Case - 595. Big Countries

### ISSUE THREAD

**Issue by zphw** [LeetCode-Feedback/LeetCode-Feedback#11873]
#### Your LeetCode username
xwangsd

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Missing test cases that AREA is exactly `3000000` so it allows queries filtering `AREA > 3000000` (instead of greater or equal to 3000000) to pass.

#### Code you used for Submit/Run operation

```SQL
SELECT NAME, POPULATION, AREA FROM WORLD WHERE AREA > 3000000 OR POPULATION >= 25000000;
```

#### Language used for code
MySQL

#### Expected behavior
The answer should receive Wrong Answer

#### Screenshots
<img width="1894" alt="image" src="https://user-images.githubusercontent.com/49032034/219979359-193bc9e1-463a-469a-ab3f-b8213a116b11.png">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
