### ISSUE TITLE
Missing Test Case - 595. Big Countries

### ISSUE THREAD

**Issue by erinjsoto** [LeetCode-Feedback/LeetCode-Feedback#11870]
#### Category of the bug
- [ Write an SQL query to report the name, population, and area of the big countries.] Question
- [select name, population, area
from World 
where population > 25000000 OR area > 3000000  ] Solution
- [MySQL ] Language
- [ ] Missing Test Cases 

#### Description of the bug

When running the script for a test case, it is deemed correct. However, when submitting the query for final results, it does not capture the data that is being called for and is therefore deemed incorrect.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output values.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!
