### ISSUE TITLE
Official solution typo

### ISSUE THREAD

**Issue by Irving09** [LeetCode-Feedback/LeetCode-Feedback#11875]
Solution typo on official solution.
https://leetcode.com/problems/online-stock-span/solutions/2643474/online-stock-span/

#### Your LeetCode username
irving09

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Solution has a typo.

Solution says the following:
"At the 85: look at the previous day. It is 75, which is not greater than 85. The answer for 75 was 4, so we need to look at least 4 days back. Going four days back, we find the 80, which is not greater than 85. The answer for **85** was 1, so we look one more day back, and find 100. The final answer is 6."

It should be:

"The answer for **80** was 1, so we look one more day back, and find 100"

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by Irving09** [comment]
Thank you for the leetcoins!
