### ISSUE TITLE
Solution Code Mistake - Find Eventual Safe States

### ISSUE THREAD

**Issue by PranayChauhan2516** [LeetCode-Feedback/LeetCode-Feedback#11879]
#### Your LeetCode username

pranaychauhan2002

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the code of the Approach 2 of the problem, The code is incorrect on the line no. 20. Instead of " if (color[node] == 2) " it should be " if (color[nei] == 2) ".
Since, We are already checking the condition for the color[node]. Also same is done correctly in the python code, but it is not correct in the java code.

#### Code you used for Submit/Run operation

CORRECT CODE:
```
// Find Eventual Safe States
class Solution {
    public List<Integer> eventualSafeNodes(int[][] graph) {
        int N = graph.length;
        int[] color = new int[N];
        List<Integer> ans = new ArrayList();

        for (int i = 0; i < N; ++i)
            if (dfs(i, color, graph))
                ans.add(i);
        return ans;
    }

    // colors: WHITE 0, GRAY 1, BLACK 2;
    public boolean dfs(int node, int[] color, int[][] graph) {
        if (color[node] > 0)
            return color[node] == 2;

        color[node] = 1;
        for (int nei: graph[node]) {
            if (color[nei] == 2)
                continue;
            if (color[nei] == 1 || !dfs(nei, color, graph))
                return false;
        }

        color[node] = 2;
        return true;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Irrespective of which code is run, The code gets accepted. But The code given in the solution (Approach 2 Java) is conceptually incorrect.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by PranayChauhan2516** [comment]
Thanks! It was my pleasure to contribute.
