### ISSUE TITLE
Missing Test Case - 585. Investments in 2016

### ISSUE THREAD

**Issue by zphw** [LeetCode-Feedback/LeetCode-Feedback#11872]
#### Your LeetCode username
xwangsd

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Missing test cases such that lat and/or lon is NULL.  For example,

```SQL
CREATE TABLE INSURANCE (
PID INTEGER primary key,
TIV_2015 NUMERIC,
TIV_2016 NUMERIC,
LAT NUMERIC,
LON NUMERIC
);
INSERT INTO INSURANCE VALUES (3, 0, 0, NULL, 6);
INSERT INTO INSURANCE VALUES (4, 0, 0, NULL, 9);
```

#### Code you used for Submit/Run operation

```SQL
SELECT ROUND(SUM(TIV_2016),2) TIV_2016 FROM INSURANCE WHERE TIV_2015 IN (SELECT TIV_2015 FROM INSURANCE GROUP BY TIV_2015 HAVING COUNT(*)>1) AND (LAT,LON) IN (SELECT LAT,LON FROM INSURANCE GROUP BY LAT,LON HAVING COUNT(*)=1);
```

The output of this query running on the above example database is `NULL`, instead of `0`.

#### Language used for code
MySQL

#### Expected behavior
The query should receive Wrong Answer

#### Screenshots
<img width="1899" alt="image" src="https://user-images.githubusercontent.com/49032034/219978984-23756413-f5b3-4edb-821b-bf1cf6cce5ae.png">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem and decided to reject this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
