### ISSUE TITLE
Missing Test case - 1614. Maximum Nesting Depth of the Parentheses

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1187]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

1614. Maximum Nesting Depth of the Parentheses
https://leetcode.com/problems/maximum-nesting-depth-of-the-parentheses/

Below test case is missing, fails the code given below:

    Input           "()"
    Output          0
    Expected        1

        Wrong Answer

#### Code you used for Submit/Run operation

Code at https://leetcode.com/problems/maximum-nesting-depth-of-the-parentheses/discuss/889284/Python-easy

```
class Solution(object):
    def maxDepth(self, s):
        """
        :type s: str
        :rtype: int
        """
        
        res = 0
        cur = 0
        
        for x in s:
            if x == "(":
                cur += 1
            elif x == ")":
                cur -= 1
            elif x.isdigit():
                res = max(res, cur)
            else:
                continue
        return res
```

#### Language used for code
Python

#### Expected behavior

- Above code is expecting a number `after` ( and ).
- The problem must contain a good variety of tests otherwise wrong solutions would come in.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hello @manoharreddyporeddy ,
Thank you for your feedback regarding this problem. We have already rewarded you for your test case contribution via another ticket. Since that test case was enough to cause other tests cases to fail, we will not be rewarding for these extra test cases provided.
