### ISSUE TITLE
Missing Test Case - 550. Game Play Analysis IV

### ISSUE THREAD

**Issue by zphw** [LeetCode-Feedback/LeetCode-Feedback#11871]
#### Your LeetCode username
xwangsd

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Missing test cases that no such players who logged in again on the day after the day they first logged in.  For example,
```SQL
CREATE TABLE ACTIVITY (
  PLAYER_ID INTEGER,
  EVENT_DATE DATE,
  DEVICE_ID INTEGER,
  GAMES_PLAYED INTEGER,
  primary key (PLAYER_ID, EVENT_DATE)
);
INSERT INTO ACTIVITY VALUES (1, '1970-01-01', 8, 0);
INSERT INTO ACTIVITY VALUES (2, '1970-01-01', 9, 0);
```

#### Code you used for Submit/Run operation

```SQL
WITH FIRST_DATE AS( SELECT PLAYER_ID FROM ACTIVITY GROUP BY PLAYER_ID HAVING (PLAYER_ID, MIN(EVENT_DATE)+1) IN (SELECT PLAYER_ID,EVENT_DATE FROM ACTIVITY) ) SELECT ROUND(COUNT(DISTINCT F.PLAYER_ID)/COUNT(DISTINCT A.PLAYER_ID),2) AS FRACTION FROM ACTIVITY A ,FIRST_DATE F;
```

The output of this query running on the above example database is `NULL`, instead of `0.00` (expected).

#### Language used for code
MySQL

#### Expected behavior
This answer should receive Wrong Answer

#### Screenshots
<img width="1916" alt="image" src="https://user-images.githubusercontent.com/49032034/219976881-55624f58-49ea-4d58-b624-0599e1c78893.png">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

Please send the test case as formatted in the console in the problem. An example:

{"headers":{"Activity":["player_id","device_id","event_date","games_played"]},"rows":{"Activity":[[1,2,"2016-03-01",5],[1,2,"2016-03-02",6],[2,3,"2017-06-25",1],[3,1,"2016-03-02",0],[3,4,"2018-07-03",5]]}}

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
