### ISSUE TITLE
Missing Test Case - 35. Search Insert Position

### ISSUE THREAD

**Issue by tmdgusya** [LeetCode-Feedback/LeetCode-Feedback#11882]
#### Your LeetCode username
tmdgusya

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Below the code i wrote is incorrect. (This code should not pass all test cases.)
Because, `middle == target -> middleIndex` code does not care about the case of (nums = [1,2,3,4,5,6,7], target = 6). 
But it passes all test cases given by Leetcode.

**Missing test case = 'nums = [1,2,3,4,5,6,7], target = 6'**

#### Code you used for Submit/Run operation

```kotlin
class Solution {
    fun searchInsert(nums: IntArray, target: Int): Int {
        return searchInsert(nums, target, 0)
    }

    fun searchInsert(nums: IntArray, target: Int, pointer: Int): Int {
        if (nums.isEmpty()) return pointer
        if (nums.size == 1 && target > nums[0]) return pointer + 1
        if (nums.size == 1 && target <= nums[0]) return pointer
        val middleIndex = nums.size / 2
        val middle = nums[middleIndex]

        return when {
            middle == target -> middleIndex
            middle < target -> searchInsert(
                nums.slice(IntRange(middleIndex + 1, nums.lastIndex)).toIntArray(),
                target,
                pointer + middleIndex + 1
            )
            else -> searchInsert(nums.slice(IntRange(0, middleIndex - 1)).toIntArray(), target, pointer)
        }
    }
}
```

#### Expected behavior
Expected output is `5`

#### Screenshots
<img width="1376" alt="image" src="https://user-images.githubusercontent.com/57784077/220130412-b691a7b0-0705-4482-8dfd-626159542d68.png">

Link: https://leetcode.com/problems/search-insert-position/submissions/901585675/

**[Success Screenshot]**

<img width="975" alt="image" src="https://user-images.githubusercontent.com/57784077/220130525-425a2f69-5667-427c-a937-1077fa6f97f8.png">

**[Fail in my custom case]**

#### Additional context

Normal code that passes the test code

```kotlin
class Solution {
    fun searchInsert(nums: IntArray, target: Int): Int {
        return searchInsert(nums, target, 0)
    }

    fun searchInsert(nums: IntArray, target: Int, pointer: Int): Int {
        if (nums.isEmpty()) return pointer
        if (nums.size == 1 && target > nums[0]) return pointer + 1
        if (nums.size == 1 && target <= nums[0]) return pointer
        val middleIndex = nums.size / 2
        val middle = nums[middleIndex]

        return when {
            middle == target -> middleIndex + pointer
            middle < target -> searchInsert(
                nums.slice(IntRange(middleIndex + 1, nums.lastIndex)).toIntArray(),
                target,
                pointer + middleIndex + 1
            )
            else -> searchInsert(nums.slice(IntRange(0, middleIndex - 1)).toIntArray(), target, pointer)
        }
    }
}
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
