### ISSUE TITLE
Possible typo in a solution

### ISSUE THREAD

**Issue by naphtul** [LeetCode-Feedback/LeetCode-Feedback#11888]
#### Your LeetCode username
naphtul

#### Category of the bug
- [ ] Question
- [X] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug
...Performance **loose**...
in https://leetcode.com/problems/binary-tree-level-order-traversal/solutions/255802/official-solution/

#### Expected behavior
You may have meant: a performance **loss**

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
