### ISSUE TITLE
Missing Test case 2, 3 - 1614. Maximum Nesting Depth of the Parentheses

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1188]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

1614. Maximum Nesting Depth of the Parentheses

https://leetcode.com/problems/maximum-nesting-depth-of-the-parentheses/
Below test cases are missing, fails the code given below:

    Input       "(1())"
    Output      1
    Expected    2

        Wrong Answer

    Input       "(())"
    Output      1
    Expected    2

        Wrong Answer

#### Code you used for Submit/Run operation

Code at https://leetcode.com/problems/maximum-nesting-depth-of-the-parentheses/discuss/888882/Java-O(n)

```
    public int maxDepth(String s) {
        
        int maxDepth = 0;
        
        int curMax = 0;
        
        for(int i = 0; i < s.length(); i++)
        {
            if(s.charAt(i) == '(')
            {
                if(s.charAt(i + 1) != ')')
                {
                    curMax++;
                    maxDepth = Math.max(maxDepth, curMax);
                }
            }
            else if (s.charAt(i) == ')')
            {
                curMax--;
            }
        }
        
        return maxDepth;
    }
```

#### Language used for code
Java

#### Expected behavior

- Above code is expecting ( and ) to be consecutive too.
- The problem must contain a good variety of tests otherwise more wrong solutions will be submitted.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hello @manoharreddyporeddy ,
Thank you for your feedback regarding this problem. We have already rewarded you for your test case contribution via another ticket. Since that test case was enough to cause other tests cases to fail, we will not be rewarding for these extra test cases provided.
