### ISSUE TITLE
Missing Test Case - 509. Fibonacci Number

### ISSUE THREAD

**Issue by 777root** [LeetCode-Feedback/LeetCode-Feedback#11880]
#### Category of the bug
- [ ] Question
- [ ] Solution

#### Description of the bug
Its not a bug but in Fibonacci numbers  there is one solution which is more precise and great in terms of space complexity
that is making code by using tail-Recursion concept so compiler will supports TCO to tail recursive code
and for tail recursive code more formal parameters are needed

#### Code you used for Submit/Run operation

```

int fib ( int n , int a, int first , int second ) { //a is accumulator 
										//so track can be done of every operation and operator inside return and it 
								//will help me actually to track how many time recursive func called

	if(a == 0 || a == 1 ) { //this if will run for fib (0) and fib (1) always that's why taken a==0 and a==1
									//.. [means a==0 for fib (0) ] and [a==1 for fib (1)]
		if (n==0) return 0;
		else if (n==1) return 1;
	}


	else if(n ==1 ) return a; //this if runs when a>1 means a value is greater than fibo(o)and fibo(1) value
	 							//so this n==1 means in tail recursion if n> 1 ex n==6 
	 							//so n will run up to here condition i.e 1 means n =6,5,4,3,2,1 !!
	 
	 
	if (a > 0){
		first=second;
		second=a;
	}
	
	return fib (n-1 , first+second , first ,second );
		
}

<!-- just for reference sending u main()-->

int main (){
	int n1 ;
	cin>>n1;
	

	cout<<fibo(n1 , 0 , 0 , 1);
	return 0;
}
<!-- this can be used in class for sure but there actual parameters are fixed, so  i came here-->
```

#### Language used for code
 C++ 

#### Expected behavior
I expected to make code even faster and code should take less memory so i used tail recursion
as here each recursive call no stack frame have to wait for other frame , everything happen when function is called
with less space even then Nontail recursion that everyone used to use in normal recursive code

#### Screenshots
I wish i could had send u screenshots but rather than screenshots its better to observe live, means Screenrecording kinda thing
so it could be easily seen for large input of n in fibonacci series code is waiting for longer n longer which can be only solve by tail recursion 

#### Additional context
It was just opinion to add some way so user can write this kinda code, yaa its very clear code had to be written in the way it is 
like formal parameter if is one than code had to be written like that but i just wrote all these so code gonna be more optimise for large input

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've submitted your feedback to the team. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
