### ISSUE TITLE
Missing Test Case - 2573. Find the String with LCP

### ISSUE THREAD

**Issue by dsp05** [LeetCode-Feedback/LeetCode-Feedback#11884]
#### Your LeetCode username

dsp05

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Some invalid matrices are not identified.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    string findTheString(vector<vector<int>>& lcp) {
        vector<int> chars;
        int sz = lcp.size();
        chars.resize(sz, -1);
        int numChars = 0;
        for (int i = 0; i < sz; i++) {
            if (lcp[i].size() != sz) return "";
            if (lcp[i][i] != sz - i) return "";

            if (chars[i] < 0) {
                chars[i] = numChars++;
                if (numChars > 26) return "";
            }
            for (int j = i + 1; j < sz; j++) {
                if (lcp[i][j] != lcp[j][i]) return "";

                if (lcp[i][j] > 0) {
                    if (i < sz - 1 && j < sz - 1 && lcp[i][j] != lcp[i + 1][j + 1] + 1) return "";
                    if ((i == sz - 1 || j == sz - 1) && lcp[i][j] != 1) return "";

                    if (chars[j] >= 0) {
                        if (chars[i] != chars[j]) return "";
                    } else chars[j] = chars[i];
                } else if (chars[i] == chars[j]) return "";
            }
        }

        vector<char> result;
        for (auto i : chars) {
            result.push_back(i + 'a');
        }
        return string(result.begin(), result.end());
    }
};
```

#### Language used for code
C++

#### Expected behavior
The above code passed all the existing test cases but give wrong answer to the below case:
`[[4,1,0,0],[1,3,0,1],[0,0,2,0],[0,1,0,1]]`

#### Screenshots

![image](https://user-images.githubusercontent.com/752718/220177734-14298745-863d-48fb-81f1-112998f95466.png)

![image](https://user-images.githubusercontent.com/752718/220177821-fb62022d-f906-4e6b-a822-9c53fd0c2973.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
