### ISSUE TITLE
Missing Test Case - 1146. Snapshot Array

### ISSUE THREAD

**Issue by kautsiitd** [LeetCode-Feedback/LeetCode-Feedback#11893]
#### Your LeetCode username

KautsIITD

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

[Following Code](https://leetcode.com/problems/snapshot-array/submissions/902015475/) should have given TLE, if there are lot of get statements after lot of snaps. Because in case of Empty(nothing updated) snaps, below code try to find query index in `snap_id-1` hence making it O(N*M) algorithm. where N=number of Snaps and M is number of get statements.

#### Code you used for Submit/Run operation

```
class SnapshotArray(object):
    def __init__(self, length):
        self.snapCount = -1
        self.length = length
        self.currDict = {}
        self.indexDict = {}
        self.valDict = {}
        self.sizeDict = {}
        self.lastNonEmpty = -1
        self.snapDict = {}
        for index in range(length):
            self.indexDict[index] = [-1]
            self.valDict[index] = [0]
            self.sizeDict[index] = 1

    def set(self, index, val):
        self.currDict[index] = val

    def snap(self):
        self.snapCount += 1
        for key in self.currDict:
            self.indexDict[key].append(self.snapCount)
            self.valDict[key].append(self.currDict[key])
            self.sizeDict[key] += 1
        self.snapDict[self.snapCount] = self.currDict.copy()
        self.currDict = {}
        return self.snapCount

    def get(self, key, snap_id):
        if self.indexDict[key] == []: return 0
        if snap_id != -1 and (not key in self.snapDict[snap_id]):
            return self.get(key, snap_id-1)
        snapId = bisect_left(self.indexDict[key], snap_id)
        
        if snapId > self.snapCount+1 or snapId >= self.sizeDict[key]:
            if key in self.currDict: return self.currDict[key]
            else: return self.valDict[key][-1]
        else:
            return self.valDict[key][snapId]
```

#### Language used for code

python

#### Expected behavior

[Following Code](https://leetcode.com/problems/snapshot-array/submissions/902015475/) should have given TLE for below test case instead of being Accepted. Same can also be seen in ScreenShots.

#### Screenshots

<img width="1440" alt="Screenshot 2023-02-21 at 11 04 41 AM" src="https://user-images.githubusercontent.com/15329761/220257866-c305602a-d86a-4daa-b3e4-4ffb5d095ffe.png">
<img width="1440" alt="Screenshot 2023-02-21 at 11 04 33 AM" src="https://user-images.githubusercontent.com/15329761/220257874-741c2ce1-37da-454f-94ba-e83f27c053d9.png">

#### Additional context

I used below Code to generate required TestCase.

```
##For Methods
limit = 20000
methods = "[\"SnapshotArray\","
for i in range(limit):
    methods += "\"set\","
for i in range(limit):
    methods += "\"snap\","
for i in range(limit//2-5):
    methods += "\"get\","
methods += "\"get\"]"
print(methods)

#For Values
import random
values = [[limit]]
for i in range(limit):
    values.append([i,random.randint(0,1000000000)])
for i in range(limit):
    values.append([])
for i in range(limit//2-4):
    values.append([random.randint(0,limit-1), random.randint(0,limit-1)])
print(values)
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
