### ISSUE TITLE
Missing Test Case - 1146. Snapshot Array

### ISSUE THREAD

**Issue by kautsiitd** [LeetCode-Feedback/LeetCode-Feedback#11892]
#### Your LeetCode username

KautsIITD

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Weak TestCases..
TestCases with all numbers set before snap, and followed by lot of snaps, should fail [below Code](https://leetcode.com/problems/snapshot-array/submissions/902019917/)..
[Following code](https://leetcode.com/problems/snapshot-array/submissions/902019917/) should not pass, where we are trying to store snap of array in form of dictionary with snap_id.
Rather It should give Memory Limit exceeded as can be seen in screen shot too.

#### Code you used for Submit/Run operation

```
def __init__(self, length):
        self.cache = []
        self.currDict = {}
        self.snapId = 0

    def set(self, index, val):
        self.currDict[index] = val

    def snap(self):
        self.cache.append(self.currDict.copy())
        self.snapId += 1
        return self.snapId-1

    def get(self, index, snap_id):
        snapDict = self.cache[snap_id]
        return snapDict[index] if index in snapDict else 0
```

#### Language used for code

python

#### Expected behavior

Above Code should give Memory Limit exceeded as can be seen in screen shot too.

#### Screenshots

<img width="1440" alt="Screenshot 2023-02-21 at 10 53 34 AM" src="https://user-images.githubusercontent.com/15329761/220254925-34328fbf-7101-4784-9720-caa29e4ff9b2.png">

<img width="1440" alt="Screenshot 2023-02-21 at 10 53 57 AM" src="https://user-images.githubusercontent.com/15329761/220254986-10f08392-30c5-4c7a-92aa-8664357c2805.png">

#### Additional context

Following Code was used to generate required TestCase.

```
#For Methods
limit = 20000
methods = "[\"SnapshotArray\","
for i in range(limit):
    methods += "\"set\","
for i in range(limit):
    methods += "\"snap\","
methods += "\"get\"]"
print(methods)

#For Values
import random
limit = 20000
values = [[limit]]
for i in range(limit):
    values.append([i,random.randint(0,1000000000)])
for i in range(limit):
    values.append([])
values.append([random.randint(0,limit-1), random.randint(0,limit-1)])
print(values)
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
