### ISSUE TITLE
351. Android Unlock Patterns - Broken Link in Solution

### ISSUE THREAD

**Issue by mnaoumov** [LeetCode-Feedback/LeetCode-Feedback#11895]
#### Your LeetCode username

mnaoumov

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Solution page https://leetcode.com/problems/android-unlock-patterns/solution/ has a broken image link https://leetcode.com/cms/documents/5/351_Android.png

#### Screenshots

![image](https://user-images.githubusercontent.com/735878/220267621-36aaaea8-ac8a-4dee-9d6f-76e3ca60df2a.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
