### ISSUE TITLE
245. Shortest Word Distance III - Missing slide in Solution

### ISSUE THREAD

**Issue by mnaoumov** [LeetCode-Feedback/LeetCode-Feedback#11894]
#### Your LeetCode username

mnaoumov

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The solution page https://leetcode.com/problems/shortest-word-distance-iii/solution/ references slide image https://leetcode.com/problems/shortest-word-distance-iii/Figures/245/245A.png that returns 403 HTTP Error.

Therefore the first frame of the slide is not loaded.

Next frames such as https://leetcode.com/problems/shortest-word-distance-iii/Figures/245/245B.png are working properly

#### Screenshots

![image](https://user-images.githubusercontent.com/735878/220264106-faed23b7-0acf-4934-b72a-c1eb41f6e526.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
