### ISSUE TITLE
500. 键盘行 测试样例缺失

### ISSUE THREAD

**Issue by wushenghao666** [LeetCode-Feedback/LeetCode-Feedback#11897]
**你的 LeetCode 用户名**
shenghaowu

**Bug 类型**

- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述**
对于这个提交来说[键盘行 - 提交记录 - 力扣（LeetCode）](https://leetcode.cn/submissions/detail/404562000/)，它不应该被通过，它没有考虑到大小写的情况。

**你使用的语言**
Python3

**你提交或者运行的代码**

```python
class Solution:
    def findWords(self, words: List[str]) -> List[str]:
        lis = ["qwertyuiop", 'asdfghjkl', 'zxcvbnm']
        res= []
        for each in words:
            s = set()
            for char in each:
                for c in lis:
                    if char in c:
                        s.add(c)
            if len(s) <= 1:
                res.append(each)
        return res
```

**期望行为**
添加一些不同行的兼具大小写的测试用例，以使这段代码被判定为错误答案。如测试样例`["Az"]`等

**屏幕截图**
![image](https://user-images.githubusercontent.com/55724610/220276799-111d5d0e-5c54-4dcf-957d-50dceb03d4ff.png)

**Comment by feiceh** [comment]
你好，当前题目已更新，积分奖励已发放，请查收
