### ISSUE TITLE
1516. Move Sub-Tree of N-Ary Tree - Broken Link

### ISSUE THREAD

**Issue by mnaoumov** [LeetCode-Feedback/LeetCode-Feedback#11898]
#### Your LeetCode username

mnaoumov

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

On the question page https://leetcode.com/problems/move-sub-tree-of-n-ary-tree/ there is a link to a non-existent article https://leetcode.com/articles/introduction-to-n-ary-trees/

#### Screenshots

![image](https://user-images.githubusercontent.com/735878/220278251-5454a11a-e028-4b3d-bd12-041bb35b2181.png)

Same issue on the other problem: #11896

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
