### ISSUE TITLE
invalid test case for connected server problem

### ISSUE THREAD

**Issue by bkchoi1214** [LeetCode-Feedback/LeetCode-Feedback#119]
**What kind of the bug**
- [ *] problem
- [ ] solution
- [ ] language

**Describe the bug**
https://leetcode.com/problems/count-servers-that-communicate/
[[1,0,0,1,0],[0,0,0,0,0],[0,0,0,1,0]]

to me, they look like three isolated computers which are not connected at all. so the answer should be 0 just like the sample test case in the problem description

**what language is your code written in**
C++

**The code you submit/run**
```
```

**Expected behavior**
[[1,0,0,1,0],[0,0,0,0,0],[0,0,0,1,0]]
should return 0 because nothing is connected!
But it says the correct answer is 3 which is wrong.

**Screenshots**

**Additional context**

**Comment by CooperCooperCooper** [comment]
Hi @bkchoi1214,
Since we're working with this issue on your [previous submission](https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/113), I will close this ticket now.
