### ISSUE TITLE
Odd Even Jump - this problem is completely unclear

### ISSUE THREAD

**Issue by jhansi012** [LeetCode-Feedback/LeetCode-Feedback#1190]
The problem description talks about odd even jumps. 
The given examples talk about different ways of reaching the end.
To me, when I read thoroughly, I thought that any element I am looking at should have it's adjacent number less/greater than the given number (from the entries of array).
Using Treemap would make sense for that. But, I didn't understand how reading the "True" values of "Odd" boolean array will give the correct result.
Can someone please explain?

**Comment by lc-kay** [comment]
Hi @jhansi012 

Please check out this [post](https://leetcode.com/problems/odd-even-jump/discuss/327805/Question-is-not-clear) for clarification. Since several people have mentioned that the description and examples are unclear, I will relay this issue to my team to investigate.

**Comment by lc-kay** [comment]
Hi @jhansi012 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
