### ISSUE TITLE
1326. 灌溉花园的最少水龙头数目

### ISSUE THREAD

**Issue by hcen1997** [LeetCode-Feedback/LeetCode-Feedback#11900]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名
hcen1997
**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [* ] 缺少测试用例

**描述**
描述你遇到的 bug

3 
[1,0,0,1]
这个测试用例应该过不去, 但是提了代码能过

**你使用的语言**
java

**你提交或者运行的代码**
```
class Solution {
    public int minTaps(int n, int[] ranges){
        int[] dp = new int[n+1]; // 灌溉到i所需要的最少水龙头数目
        if (ranges[0] != 0) {
            for (int i = 0; i <= Math.min(ranges[0],n); i++) {
                dp[i] = 1;
            }
        }

        for (int i = 1; i < ranges.length; i++) {
            if (ranges[i] == 0) {
                continue;
            }
            int range = i - ranges[i];
            int num = range > 0 ? dp[range] + 1 : 1;
            for (int j = Math.max(0,i-ranges[i]); j <= Math.min(i+ranges[i],n) ; j++) {
                dp[j] = dp[j] == 0 ? num: Math.min(dp[j], num);
            }
        }

        for (int i = 0; i <= n; i++) {
            if (dp[i] == 0) {
                return -1;
            }
        }
        return dp[n];
    }  
}
```

**期望行为**
wa

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![image](https://user-images.githubusercontent.com/22320578/220282193-6ce0dba1-b124-4206-85a5-9ac64a39477e.png)
![image](https://user-images.githubusercontent.com/22320578/220282221-cf33070b-86e9-412a-9e9c-f14fc1a95d00.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
你好，当前题目已更新，积分奖励已发放，请查收
