### ISSUE TITLE
Missing Test Case - 1011. Capacity To Ship Packages Within D Days

### ISSUE THREAD

**Issue by Sanyam233** [LeetCode-Feedback/LeetCode-Feedback#11912]
#### Your LeetCode username

Sanyam233

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Not a bug but a missing test case. An array of length 5*10^4 with all it's elements equaling 500 eg: [500, 500, 500......] and must be delivered within 1 day

#### Code you used for Submit/Run operation

```
class Solution {
    public int shipWithinDays(int[] weights, int days) {
        int start = 0, end = 0;

        for (int weight : weights) {
            start = Math.max(start, weight);
        }

        end = start * 10000;

        while (start < end) {
            int mid = (start + end)/2;

            if (countDays(weights, mid, days)) {
                end = mid;
            } else {
                start = mid + 1;
            }
        }
        return start;
    }

    private boolean countDays(int[] weights, int cap, int days) {
        int total = 0;

        for (int weight : weights) {
            if (total + weight > cap) {
                days--;
                total = 0;
            }
            
            total += weight;
        }

        return days > 0;
    }
}
```

#### Language used for code
Java

#### Expected behavior
The code passed all the existing test cases but failed the one described above.

#### Screenshots
![Screen Shot 2023-02-21 at 5 12 17 PM](https://user-images.githubusercontent.com/57723296/220495162-f4b929ae-b628-4b19-b1c0-8c3b835fbd83.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
