### ISSUE TITLE
Wrong space complexity in the official solution for "1011. Capacity To Ship Packages Within D Days"

### ISSUE THREAD

**Issue by pinieb** [LeetCode-Feedback/LeetCode-Feedback#11914]
#### Your LeetCode username
pinieb

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The official solution describes its space complexity as `O(1)`, stating: "We are only defining a few integer variables." In actuality, the space complexity should be `O(log(n))`, since `feasible()` is allocating space for a couple of integers for _each call_, and `feasible()` is called at most `log(n)` times.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. Here is the explain:

Only one call to feasible exists in memory at any given time. When the function returns, the variables are released. Space complexity does not refer to the total amount of variables declared throughout the runtime, but the peak amount of memory allocated at any given time.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
