### ISSUE TITLE
Typo - 2503. Maximum Number of Points From Grid Queries

### ISSUE THREAD

**Issue by PyroGenesis** [LeetCode-Feedback/LeetCode-Feedback#11928]
#### Your LeetCode username
burhanlakda

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

There is a typo in this question in the 2nd line

> Find an array answer of size k such that for each integer **queres[i]** you start in the top left cell of the matrix and repeat the following process:

#### Expected behavior

It should be spelled **queries**

#### Screenshots

![image](https://user-images.githubusercontent.com/17806916/220758629-71bd0906-da7a-47f6-8a83-14e81b71b5bf.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
