### ISSUE TITLE
142. Linked List Cycle II - TypeError on LinkedList Node Parameter 

### ISSUE THREAD

**Issue by Sigele** [LeetCode-Feedback/LeetCode-Feedback#11929]
#### Your LeetCode username

flopclub

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ x] Language
- [ ] Missing Test Cases 

#### Description of the bug

All test cases pass, but on submit getting TypeError, linkedlist node being read as 'null'

#### Code you used for Submit/Run operation

```
// Linked List Cycle II
var detectCycle = function(head) {
    let current = head;
    //edge cases: no cycle and/or only one node
    if (!current.next) {
        return null;
    }
    visited = [];
    
    while (current.next !== null && !(visited.includes(current))) {
        
        if (visited.includes(current.next)) return current.next;
        visited.push(current);
        current = current.next;
    }
    return null;
};
```

#### Expected behavior

Would've expected solution to be accepted, or if not to receive an error indicative of failed test. With console bug it's difficult to tell the actual cause.

#### Screenshots

<img width="654" alt="Screen Shot 2023-02-22 at 4 41 00 PM" src="https://user-images.githubusercontent.com/80664779/220777708-063d9e0f-ebf4-4ce0-a933-352788df8a3b.png">
<img width="567" alt="Screen Shot 2023-02-22 at 4 41 12 PM" src="https://user-images.githubusercontent.com/80664779/220777779-d606a331-7b43-4b0a-8906-adf49311fdbf.png">
<img width="675" alt="Screen Shot 2023-02-22 at 4 41 17 PM" src="https://user-images.githubusercontent.com/80664779/220777796-906e49a8-af5d-4130-a3a3-a6ad0a255dd3.png">
<img width="937" alt="Screen Shot 2023-02-22 at 4 41 32 PM" src="https://user-images.githubusercontent.com/80664779/220777820-340458f7-3326-4d23-9a84-e7a64a5a3de8.png">
<img width="791" alt="Screen Shot 2023-02-22 at 4 41 48 PM" src="https://user-images.githubusercontent.com/80664779/220777828-91d1c366-66c7-46f2-b90e-8a89994f4185.png">
<img width="507" alt="Screen Shot 2023-02-22 at 4 41 59 PM" src="https://user-images.githubusercontent.com/80664779/220777010-a1d016eb-e3f3-443f-9a4e-e93703d833a2.png">

#### Additional context

Also worth noting that console.log behavior is also unusual - when logging the head argument, console prints 'Error - Found cycle in the ListNode'. see screenshots

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
