### ISSUE TITLE
Rust Unknown preprocess compile error

### ISSUE THREAD

**Issue by dvishal485** [LeetCode-Feedback/LeetCode-Feedback#11924]
#### Your LeetCode username

dvishal485

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

Random Compile Error while submitting solution in Rust

Question : [Count Primes](https://leetcode.com/problems/count-primes/)

```
Compile Error
Unknown preprocess compile error
```
Sometimes the solutions which are submitted in Rust which are supposed to be compiled without any error and actually get accepted randomly encounters `Compile Error` with error message as shown above. And they are actually recorded in history of user's submissions.

Submission ID : [count-primes/submissions/902965522](https://leetcode.com/problems/count-primes/submissions/902965522/)

#### Code you used for Submit/Run operation

```rust
impl Solution {
    pub fn count_primes(n: i32) -> i32 {
        if n < 3 {
            return 0;
        }
        let mut is_prime = vec![true; n as usize];
        is_prime[0] = false;
        is_prime[1] = false;
        for num in 2..(n as f64).sqrt() as usize + 1 {
            if is_prime[num] {
                let num = num as i32;
                let mut composite = num * 2;
                while composite < n {
                    is_prime[composite as usize] = false;
                    composite += num;
                }
            }
        }
        is_prime
            .iter()
            .fold(0, |acc, &prime| if prime { acc + 1 } else { acc })
    }
}
```

#### Language used for code

Rust

#### Expected behavior

Error should be shown like "Something went wrong, try again" and should not be reflected in user's submission.

#### Screenshots

![image](https://user-images.githubusercontent.com/26341736/220670153-31b68f2e-0695-48a0-bd9f-72a5d04e4e5b.png)

Solution getting compile error

![image](https://user-images.githubusercontent.com/26341736/220670309-f2c2ed7e-3bb8-43e6-860e-bdad6ba8750b.png)

Same solution getting accepted without any change

#### Additional context

[Refer here for accepted solution with same code](https://leetcode.com/problems/count-primes/submissions/902965758/)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
