### ISSUE TITLE
Missing Test Case - 1011. Capacity To Ship Packages Within D Days

### ISSUE THREAD

**Issue by Leven77** [LeetCode-Feedback/LeetCode-Feedback#11922]
#### Your LeetCode username
Liphy

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

the best solution sample in java which beat 100% code can not solute this testcase
the following code is copied from 5ms runtime sample submission.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    public int shipWithinDays(int[] a, int days) {
        int l = 0, r = 500 * a.length / days;
        // for (int w : a) {
        //     r += w;
        //     if (w > l) l = w;
        // }

        while (l < r) {
            int m = l + (r-l)/2;
            if (isEnough(a, m, days)) r = m;
            else l = m + 1;
        }

        return l;
    }

    private boolean isEnough(int[] a, int m, int d) {
        int cnt = 1, sum = 0;
        for (int w : a) {
            if (w > m) return false;
            if ((sum += w) > m) {
                if (++cnt > d) return false;
                sum = w;
            }
        }

        return true;
    }
}
```

#### Language used for code
Java

#### Expected behavior
the code failed to run test, but can be accept by submit.
it should't be accept.
if you read the code, you know it.

#### Screenshots

![image](https://user-images.githubusercontent.com/35281431/220633633-c1e153cd-208e-42f6-83f9-2f9f14323da1.png)
![image](https://user-images.githubusercontent.com/35281431/220634071-934b31d9-d8d0-4a95-8fa8-7f648bc99a85.png)

**Comment by Md-Shamim-Ahmmed** [comment]
hey if you look at the testcase
then see that 
weights is = ```[500,500,500,500,500]```
day = ```3```
**Explanation:**
1st day: 500
2nd day: 500, 500
3rd day: 500, 500
so the answer will be ```1000```.
In your code there have a bug that's why your solution code produce output as 833.
But 833 is not possible for this test case

**Comment by Leven77** [comment]
thanks for your reply.
I acknowledge that in this test case the answer should be 1000 and the code have a bug.
my point is the system have a bug too, because of missing this test case.
the code is copy from the best sample solution.
and the leetcode system can accept this code right now .


| |
lyphy
|
|
***@***.***
|
---- Replied Message ----
| From | Md Shamim ***@***.***> |
| Date | 2/23/2023 01:16 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [LeetCode-Feedback/LeetCode-Feedback] Missing Test Case - 1011. Capacity To Ship Packages Within D Days (Issue #11922) |

hey if you look at the testcase
then see that
weights is = [500,500,500,500,500]
day = 3
Explanation:
1st day: 500
2nd day: 500, 500
3rd day: 500, 500
so the answer will be 1000.
In your code there have a bug that's why your solution code produce output as 833.
But 833 is not possible for this test case

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
