### ISSUE TITLE
Missing Test case 4 - 1614. Maximum Nesting Depth of the Parentheses

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1192]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

1614. Maximum Nesting Depth of the Parentheses
https://leetcode.com/problems/maximum-nesting-depth-of-the-parentheses/

Below test cases are missing, fails the code given below:

    Input     "+(+(+)+)+"
    Output    0
    Expected    2
        Wrong Answer

#### Code you used for Submit/Run operation

Code is at https://leetcode.com/problems/maximum-nesting-depth-of-the-parentheses/discuss/888991/c-brute-force-without-recursion-worst-solution/728532
```
class Solution {
public:
    int maxDepth(string s) {
        vector<int> t;
        int res=0, temp;
        for(int i=0; i<s.length(); i++)
            if(s[i] >= 48 && s[i] <= 57)
                t.push_back(i);
        
        for(int i=0; i<t.size(); i++) {
            temp = 0;
            for(int j=t[i]; j>=0; j--) {
                if(s[j] == '(')
                    temp += 1;
                else if(s[j] == ')')
                    temp -= 1;
            }
            if(temp > res)
                res = temp;
        }
        return res;        
    }
};
```

#### Language used for code
C++

#### Expected behavior

- Above code is expecting a number to be present `before` ( and ) as per explanation in the above link by OP.
- The problem must contain a good variety of tests otherwise more wrong solutions will be submitted.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
