### ISSUE TITLE
问题描述最好被修改 - 464. 我能赢吗 

### ISSUE THREAD

**Issue by wushenghao666** [LeetCode-Feedback/LeetCode-Feedback#11923]
**你的 LeetCode 用户名**
shenghaowu

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
对于这个问题来说[464. 我能赢吗 - 力扣（LeetCode）](https://leetcode.cn/problems/can-i-win/)[键盘行 - 提交记录 - 力扣（LeetCode）](https://leetcode.cn/submissions/detail/404562000/)，中文题目描述语义不清晰，最好被修改。

**期望行为**
若先出手的玩家是否能稳赢则返回 `true` ，否则返回 `false` 。

应改为

若先出手的玩家能稳赢，则返回 `true` ，否则返回 `false` 。

**屏幕截图**

![image](https://user-images.githubusercontent.com/55724610/220640513-075b6aa5-a69a-4d47-bd58-f4714bd49399.png)

**Comment by feiceh** [comment]
你好，当前题目已更新，积分奖励已发放，请查收
