### ISSUE TITLE
Missing Test Case - 875. Koko Eating Bananas

### ISSUE THREAD

**Issue by ajay-s-07** [LeetCode-Feedback/LeetCode-Feedback#11936]
#### Your LeetCode username

GangsTa_07

#### Category of the bug

- [ ] Missing Test Cases 

#### Description of the bug

4 - piles length
3 6 7 11 - elements
18 - hours
When this code runs, output should be 2 but my code gives output 0.  Still got submitted.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    public int minEatingSpeed(int[] piles, int h) {
        int left = 0, right = 0;
        for(int x : piles){
            right = Math.max(right, x);
        }
        if(piles.length == h) return right;

        int ans = 0;
        while(left <= right){
            int mid = left + (right-left)/2;
            if(isPossible(piles, mid, h)){
                ans = mid;
                right = mid - 1;
            }
            else left = mid + 1;
        }
        return ans;
    }
    public boolean isPossible(int[] arr, int mid, int h){
        int count = 0;
        for(int i=0; i<arr.length; i++)
            count += (int)Math.ceil(arr[i]*1.0 / mid);
        
        return count <= h;
    }
}
```

#### Language used for code

JAVA

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
