### ISSUE TITLE
Missing Test Case - 608. Tree Node

### ISSUE THREAD

**Issue by zphw** [LeetCode-Feedback/LeetCode-Feedback#11934]
#### Your LeetCode username
xwangsd

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Missing test cases such that there are only two nodes - one is root and one is leaf - and their ID are negative numbers.  For example,

```SQL
CREATE TABLE TREE (
  ID INTEGER primary key,
  P_ID INTEGER references TREE(ID)
);
INSERT INTO TREE VALUES (-1, NULL);
INSERT INTO TREE VALUES (-2, -1);
```

#### Code you used for Submit/Run operation
```SQL
SELECT ID, 'ROOT' AS TYPE FROM TREE WHERE P_ID IS NULL UNION SELECT ID, 'INNER' AS TYPE FROM TREE WHERE P_ID>0 AND ID IN (SELECT P_ID FROM TREE) UNION SELECT ID, 'LEAF' AS TYPE FROM TREE WHERE P_ID>0 AND ID NOT IN (SELECT P_ID FROM TREE WHERE P_ID IS NOT NULL);
```

AC submission link: https://leetcode.com/problems/tree-node/submissions/903266172/

#### Language used for code
MySQL

#### Expected behavior
The answer should receive Wrong Answer

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem and decided to reject this feedback.

Please send the test cases in the format that is present in the console.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
