### ISSUE TITLE
Missing Test Case - 1616. Split Two Strings to Make Palindrome

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#1193]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A couple of solutions are accepted but fail on the following test case:

"a"
"a"

#### Code you used for Submit/Run operation

```
class Solution {
	public boolean checkPalindromeFormation(String a, String b) {
        return solve(a,b) || solve(b,a);
    }
    
    private boolean solve(String a, String b){
        int i = 0;
        int j = b.length()-1;
        
        while(a.charAt(i) == b.charAt(j)){
            i++;
            j--;
        }
        
        String ABB = a.substring(0,i) + b.substring(i);
        String AAB = a.substring(0,a.length()-i) + b.substring(b.length()-i);
        
        return isPalindrome(ABB) || isPalindrome(AAB);
    }
    
    private boolean isPalindrome(String s){
        int n = s.length();
        for(int i=0;i<n/2;i++){
            if(s.charAt(i) != s.charAt(n-i-1)){
                return false;
            }
        }
        return true;
    }
}
```

```
class Solution {
    public boolean checkPalindromeFormation(String a, String b) {
        return checkTwo(a, b) || checkTwo(b, a);
    }
    
    public boolean checkTwo(String a, String b) {
        int i = 0, j = b.length() - 1;
        while (a.charAt(i) == b.charAt(j)) {
            i++;
            j--;
        }
        return isPa(a.substring(i, j + 1)) || isPa(b.substring(i, j + 1));
    }
    
    public boolean isPa(String s) {
        int i = 0, j = s.length() - 1;
        while (i < j) {
            if (s.charAt(i) != s.charAt(j)) return false;
            i++;
            j--;
        }
        return true;
    }
}
```

#### Language used for code
Java, Java

#### Expected behavior

The solutions should not be accepted since they fail on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/95691795-d7c47d80-0bef-11eb-8d50-13472ee0e552.png)
![image](https://user-images.githubusercontent.com/32546406/95691803-e874f380-0bef-11eb-8815-e02bfce5e03e.png)

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
