### ISSUE TITLE
Missing Test Case - 502. IPO

### ISSUE THREAD

**Issue by raaz001** [LeetCode-Feedback/LeetCode-Feedback#11943]
#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by raaz001** [comment]
class Solution(object):
    def findMaximizedCapital(self, k, w, profits, capital):
        """
        :type k: int
        :type W: int
        :type Profits: List[int]
        :type Capital: List[int]
        :rtype: int
        """
        n = len(profits)
        inf = float('inf')
        while k > 0:
            arr = [i for i in range(n) if capital[i] <= w]
            if not arr:
                break
            if k >= len(arr) and len(arr) + capital.count(inf) == n:
                return w + sum(profits[i] for i in arr)
            idx = max(arr, key=lambda x: profits[x])
            capital[idx] = inf
            w += profits[idx]
            k -= 1
        return w

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've submitted this code to our team. 

Thank you for your support.
