### ISSUE TITLE
Missing Test Case - 42. Trapping Rain Water

### ISSUE THREAD

**Issue by dhouni9999** [LeetCode-Feedback/LeetCode-Feedback#11944]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    public int trap(int[] height) {
        int water=0;
        int n= height.length;

        for(int i=1;i<n-2;i++)// First and last building will not trap water
       {
           int left_sum=height[i];
           int right_sum= height[i];
           for(int j =0;j<=i;j++){
               if(height[j]>left_sum){
                   left_sum= height[j];
               }
           }
           for(int j=i;j<=n-1;j++){
               if(height[j]> right_sum){
                   right_sum= height[j];
               }
           }
           water = water + Math.min(left_sum,right_sum)- height[i];
       } 
    return water;
 }
}
```

#### Expected behaviour
TLE - Time Limit Exceeded

#### Additional context
321 / 322 test cases passed

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, 

the code received Wrong Answer: https://leetcode.com/submissions/detail/903743110/

please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
