### ISSUE TITLE
Missing Test Case - 65. Valid Number

### ISSUE THREAD

**Issue by JamieGainer** [LeetCode-Feedback/LeetCode-Feedback#11941]
#### Your LeetCode username

JamieGainer

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

The current set of testcases don't catch the case where one only checks if there is a digit in the string, not that the digit has to be before the exponent.  For example "+.E3" has a digit, a "+", a ".", and an "E" in places that could be correct, except that the string is incorrect because there is no digit before the "E".  An example of code that gives the wrong answer for "+.E3" but passes the existing cases is below.

#### Code you used for Submit/Run operation

```
class Solution:
    def __init__(self):
        self.digits = [str(n) for n in range(10)]

    def isNumber(self, s: str) -> bool:
        decimal = False
        exponential = False
        validDecimalNumber = False
        hasDigits = False
        for i, char in enumerate(s):
            if char not in self.digits + ["+", "-", ".", "e", "E"]:
                return False
            if char in ["+", "-"]:
                if i != 0 and s[i-1] not in ["e", "E"]:
                    return False
                if i == len(s) - 1:
                    return False
            if char in ["e", "E"]:
                if not validDecimalNumber or exponential:
                    return False
                if s[:i] == ".":
                    return False
                if i == len(s) - 1:
                    return False
                exponential = True
            if char == ".":
                if decimal or exponential:
                    return False
                decimal = True
                validDecimalNumber = True
            if char in self.digits:
                validDecimalNumber = True
                hasDigits = True
        else:
            return hasDigits
```

#### Expected behavior

The code above gives the wrong answer for the input "+.E3" but passed all the test cases.  I suggest adding "+.E3" or something like it as a test case.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
