### ISSUE TITLE
Missing Test Case - 1075. Project Employees I

### ISSUE THREAD

**Issue by zphw** [LeetCode-Feedback/LeetCode-Feedback#11956]
#### Your LeetCode username
xwangsd

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Missing test cases such that the EXPERIENCE_YEARS of an employee is NULL, for example,
```SQL
CREATE TABLE PROJECT (
PROJECT_ID INTEGER,
EMPLOYEE_ID INTEGER references EMPLOYEE(EMPLOYEE_ID),
PRIMARY KEY (PROJECT_ID, EMPLOYEE_ID)
);
INSERT INTO PROJECT VALUES (4, 6);
INSERT INTO PROJECT VALUES (4, 5);

CREATE TABLE EMPLOYEE (
  EMPLOYEE_ID INTEGER PRIMARY KEY,
  NAME VARCHAR(20),
  EXPERIENCE_YEARS INTEGER
);
INSERT INTO EMPLOYEE VALUES (6, '1', 11);
INSERT INTO EMPLOYEE VALUES (5, '2', NULL);
```

#### Code you used for Submit/Run operation
```SQL
SELECT PROJECT_ID,ROUND(SUM(EXPERIENCE_YEARS)/COUNT(*),2) AVERAGE_YEARS FROM PROJECT P JOIN EMPLOYEE E USING(EMPLOYEE_ID) GROUP BY PROJECT_ID;
```

AC submission link: https://leetcode.com/problems/project-employees-i/submissions/903793132/

#### Language used for code
MySQL

#### Expected behavior
The answer should receive Wrong Answer

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem: added to the statement:
It's guaranteed that experience_years is not NULL.

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
