### ISSUE TITLE
Missing Test Case - 997. Find the Town Judge

### ISSUE THREAD

**Issue by 6202Binit** [LeetCode-Feedback/LeetCode-Feedback#11952]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

In this solution we concentrate on optimise way solution 
here time complexity is O(n) this is optimise way

```
// Two Sum
class Solution {
    public int findJudge(int n, int[][] trust) {
        int c[] = new int[n+1];
        for(int t[] : trust){
            c[t[0]]--;
            c[t[1]]++;
        }
        for(int i = 1;i<=n;i++){
            if(c[i]== n-1){
                return i;
            }
        }
        return -1;
    }
}
```

#### Language used for code

java

**Comment by 6202Binit** [comment]
i give a solution in java with optimising way

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've submitted this code to our team. 

Thank you for your support.
