### ISSUE TITLE
Missing Test Case - 1077. Project Employees III

### ISSUE THREAD

**Issue by zphw** [LeetCode-Feedback/LeetCode-Feedback#11957]
#### Your LeetCode username
xwangsd

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Missing test cases such that the experience_years of an employee is NULL, for example:
```SQL
CREATE TABLE PROJECT (
PROJECT_ID INTEGER,
EMPLOYEE_ID INTEGER references EMPLOYEE(EMPLOYEE_ID),
PRIMARY KEY (PROJECT_ID, EMPLOYEE_ID)
);
INSERT INTO PROJECT VALUES (6, 7);
INSERT INTO PROJECT VALUES (6, 8);

CREATE TABLE EMPLOYEE (
  EMPLOYEE_ID INTEGER PRIMARY KEY,
  NAME VARCHAR(20),
  EXPERIENCE_YEARS INTEGER
);
INSERT INTO EMPLOYEE VALUES (8, 68, NULL);
INSERT INTO EMPLOYEE VALUES (7, 69, 0);
```

#### Code you used for Submit/Run operation
```SQL
SELECT P1.PROJECT_ID, P1.EMPLOYEE_ID FROM PROJECT P1 JOIN EMPLOYEE E1 ON P1.EMPLOYEE_ID = E1.EMPLOYEE_ID WHERE (P1.PROJECT_ID,E1.EXPERIENCE_YEARS) IN ( SELECT P.PROJECT_ID, MAX(E.EXPERIENCE_YEARS) FROM PROJECT P JOIN EMPLOYEE E ON P.EMPLOYEE_ID = E.EMPLOYEE_ID GROUP BY P.PROJECT_ID);
```
(AC submission link: https://leetcode.com/problems/project-employees-iii/submissions/903796017/)

```SQL
WITH MAX_TENURE AS ( SELECT A.PROJECT_ID, MAX(COALESCE(B.EXPERIENCE_YEARS)) AS MAX_EXP FROM PROJECT A LEFT JOIN EMPLOYEE B ON A.EMPLOYEE_ID = B.EMPLOYEE_ID GROUP BY 1 ), PROJECT_EMPLOYEE AS ( SELECT A.*, COALESCE(B.EXPERIENCE_YEARS,0) AS EXP_YEARS FROM PROJECT A LEFT JOIN EMPLOYEE B ON A.EMPLOYEE_ID = B.EMPLOYEE_ID ) SELECT C1.PROJECT_ID, C1.EMPLOYEE_ID FROM PROJECT_EMPLOYEE C1 INNER JOIN MAX_TENURE C2 ON C1.PROJECT_ID = C2.PROJECT_ID WHERE C1.EXP_YEARS = C2.MAX_EXP;
```
AC submission link: https://leetcode.com/problems/project-employees-iii/submissions/903796039/

#### Language used for code
MySQL

#### Expected behavior
One of the above answers should receive Wrong Answer, as the # of rows of the two queries' outputs are different, but not sure which one is the desired behavior

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

We rejected this feedback.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
