### ISSUE TITLE
33. Search in Rotated Sorted Array wrong testcase

### ISSUE THREAD

**Issue by NouraAlgohary** [LeetCode-Feedback/LeetCode-Feedback#11953]
#### Your LeetCode username

user1572XK

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

In problem "33. Search in Rotated Sorted Array", there is a problem in test case no. 146. 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int search(vector<int>& nums, int target) {
        int rotatedby = min_element(nums.begin(), nums.end()) - nums.begin();

       rotate(nums.begin(), nums.begin() + rotatedby, nums.end());

        int low = 0, high = nums.size() - 1, mid = 0;

        while(low <= high)
        {
            mid = (low + high) / 2;

            if(target == nums[mid])
                return mid + rotatedby;

            if(target < nums[mid])
                high = mid - 1;
            else
                low = mid + 1;
        }

        return -1;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The array is [3, 1] and the target is 3.
The array is sorted and rotated so the answer should be 1 but it's 0!

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
