### ISSUE TITLE
Incomplete solution for Question 1616. Split Two Strings to Make Palindrome

### ISSUE THREAD

**Issue by gucifer** [LeetCode-Feedback/LeetCode-Feedback#1195]
#### Category of the bug
- [ ] Question - 1616. Split Two Strings to Make Palindrome
- [ ] Solution - Solution seems incomplete
- [ ] Language - Python

#### Description of the bug
Upon running the test case:
a = "abda"
b = "acmc"
The answer returned is False, however
"abda" => "abd" + "a" , aprefix = "abd" , asuffix = "a"
"acmc" => "a" + "cmc" , bprefix = "a" , bsuffix = "cmc"
bprefix + asuffix = "a" + "a" = "aa" <- which is a palindrome hence correct answer is True not False. But upon running the testcase leetcode solution gives responce False.

#### Code you used for Submit/Run operation

```
//My Solution is O(1) time while the solution given is O(n) time
class Solution:
    def checkPalindromeFormation(self, a: str, b: str) -> bool:
        if len(a) == 1 or len(b) == 1:
            return True
        if a[0] == b[-1]:
            return True
        elif a[-1] == b[0]:
            return True
        return False
```

**Comment by Ceay1** [comment]
Per the problem ("_Choose an index and split both strings **at the same index**_"), one cannot split the strings as "abd" + "a" and "a" + "cmc", because the split is not at the same index. Thus, the correct answer to the problem is "False."

**Comment by lc-kay** [comment]
Hi @gucifer, 

Please refer to @Ceay1 comment for clarification. If you have any more questions, please let me know.

**Comment by gucifer** [comment]
Yes Thank you.
