### ISSUE TITLE
Incomplete short-form part of question - 1433. Check If a String Can Break Another String

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1196]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

1433. Check If a String Can Break Another String
https://leetcode.com/problems/check-if-a-string-can-break-another-string/

In the long-form vice versa is mentioned

`Given two strings: s1 and s2 with the same size, check if some permutation of string s1 can break some permutation of string s2 or vice-versa`

but in the short-form vice versa is not mentioned.
`(in other words s2 can break s1).`

Please change:

from: `(in other words s2 can break s1).`
to: `(in other words s2 can break s1 or vice-versa).`

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JavaScript

#### Expected behavior

- Short-form should be complete, otherwise, Wrong Answer can occur for the user.

**Comment by manoharreddyporeddy** [comment]
Found a proof that User going wrong due to incomplete short-form

    https://leetcode.com/problems/check-if-a-string-can-break-another-string/discuss/608668/Python-O(n)./526709

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
