### ISSUE TITLE
Missing Test Case - 1112. Highest Grade For Each Student

### ISSUE THREAD

**Issue by zphw** [LeetCode-Feedback/LeetCode-Feedback#11963]
#### Your LeetCode username
xwangsd

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Missing test cases such that the grade is NULL, for example
```SQL
CREATE TABLE ENROLLMENTS (
  STUDENT_ID INTEGER, 
  COURSE_ID INTEGER,
  GRADE INTEGER,
  PRIMARY KEY (STUDENT_ID, COURSE_ID)
);
INSERT INTO ENROLLMENTS VALUES (2, 13, 37);
INSERT INTO ENROLLMENTS VALUES (10, 6, NULL);
```

#### Code you used for Submit/Run operation
```SQL
SELECT E.STUDENT_ID, MIN(E.COURSE_ID) AS COURSE_ID, T.MAX_GRADE AS GRADE FROM (SELECT STUDENT_ID, MAX(GRADE) AS MAX_GRADE FROM ENROLLMENTS GROUP BY STUDENT_ID) AS T LEFT JOIN ENROLLMENTS E ON E.STUDENT_ID = T.STUDENT_ID AND E.GRADE = T.MAX_GRADE GROUP BY E.STUDENT_ID,T.MAX_GRADE ORDER BY E.STUDENT_ID;
```

AC submission link: https://leetcode.com/problems/highest-grade-for-each-student/submissions/903819886/

#### Language used for code
MySQL

#### Expected behavior
The answer should receive Wrong Answer

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem: Added to the statement:
grade is never NULL.

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
