### ISSUE TITLE
A quiz question is broken

### ISSUE THREAD

**Issue by allaptr** [LeetCode-Feedback/LeetCode-Feedback#11968]
#### Category of the bug
- [ x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Here is the quiz url 
```
https://leetcode.com/explore/learn/card/dynamic-programming/631/strategy-for-solving-dp-problems/4048/
```
The second question won't take any answer as valid. The error message is always the same: Wrong Answer.
Constants should never be state variables.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The question appears to perform correctly.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
