### ISSUE TITLE
Missing Test Case - 1460. Make Two Arrays Equal by Reversing Subarrays

### ISSUE THREAD

**Issue by mansurbeknarzullayev** [LeetCode-Feedback/LeetCode-Feedback#11964]
#### Your LeetCode username

Mansurbek0095

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug

I send my wrong code, but it's accepted

#### Code you used for Submit/Run operation

```
class Solution:
    def canBeEqual(self, target: List[int], arr: List[int]) -> bool:
        return '' . join(sorted([str(x) for x in target])) == '' . join(sorted([str(x) for x in arr]))
```
#### Expected behavior

If we sort the arrays and convert them to strings and then check both strings for equality, the solution passes
[1, 23, 4]
[12, 3, 4]

#### Screenshots

![2023-02-24_03-54-53](https://user-images.githubusercontent.com/19311774/221050239-69eab7b0-7cdb-490b-a81e-354ab9c7414a.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output values.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!

**Comment by LC-Pam** [comment]
[1, 23, 4]
[12, 3, 4]

This is the missing test case and  We've relayed this issue to our team to investigate. 

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
