### ISSUE TITLE
Missing Test Case - 1675. Minimize Deviation in Array

### ISSUE THREAD

**Issue by way213** [LeetCode-Feedback/LeetCode-Feedback#11966]
#### Your LeetCode username
way213

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [  ] Missing Test Cases 

#### Description of the bug

arrays with 5 and 9 are not working correctly

#### Code you used for Submit/Run operation
```
class Solution {
    public static int minimumDeviation(int[] nums) {
        int i = 0;
        for (int n : nums){
            if (n % 2 == 0){
                while (n % 2 == 0 && n > 2) {
                    n = n / 2;
                }
            }
            if (n == 1){
                n = 2;
            }
            nums[i] = n;
            i++;
        }
        Arrays.sort(nums);
        int result = nums[nums.length-1] - nums[0];
        for (int n : nums){
            if (n%2 != 0){
                while (n < nums[nums.length-1]){
                    if ((n*2-nums[nums.length-1])<result){
                        result = n*2-nums[nums.length-1];
                    }
                    n=n*2;
                }
            }
        }
        return result;
    }
}
```

#### Language used for code
java

#### Expected behavior
an input of [2,5,9] should have an output of 1, however the expected is labeled as 7.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
