### ISSUE TITLE
Missing Test Case - 1113. Reported Posts

### ISSUE THREAD

**Issue by zphw** [LeetCode-Feedback/LeetCode-Feedback#11965]
#### Your LeetCode username
xwangsd

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Missing test cases such that extra is NULL, for example
```SQL
CREATE TABLE ACTIONS (
  USER_ID INTEGER,
  POST_ID INTEGER,
  ACTION_DATE DATE,
  ACTION VARCHAR(20),
  EXTRA VARCHAR(20)
);
INSERT INTO ACTIONS VALUES (4, 2, '2019-07-03', 'VIEW', '3');
INSERT INTO ACTIONS VALUES (4, 2, '2019-07-04', 'REPORT', NULL);
```

#### Code you used for Submit/Run operation
```SQL
SELECT Y.EXTRA AS REPORT_REASON,COUNT(DISTINCT Y.POST_ID) AS REPORT_COUNT FROM ( SELECT * FROM ACTIONS WHERE EXTRA IS NOT NULL AND ACTION_DATE='2019-07-04' AND ACTION='REPORT' ) AS Y GROUP BY Y.EXTRA;
```

AC submission link: https://leetcode.com/problems/reported-posts/submissions/903822084/

#### Language used for code
MySQL

#### Expected behavior
The answer should receive Wrong Answer

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
