### ISSUE TITLE
Missing Test Case - 1675. Minimize Deviation in Array

### ISSUE THREAD

**Issue by nightingale38** [LeetCode-Feedback/LeetCode-Feedback#11975]
#### Your LeetCode username
BusyBeaver42

#### Category of the bug
- Missing Test Cases 

#### Description of the bug
A test case is missing for problem "1675. Minimize Deviation in Array".

#### Code you used for Submit/Run operation
I used this submission https://leetcode.com/submissions/detail/904092374/ (from another user) which was accepted but fails on a the following testcase: [8, 12].

#### Language used for code
The submission I referred to is written in Rust but the problem could occur with any programming language.

#### Expected behavior
The submission is incorrect so it should not have been accepted.

#### Screenshots
None

#### Additional context
None

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
