### ISSUE TITLE
Missing Test Case - 242. Valid Anagram

### ISSUE THREAD

**Issue by jhhornn** [LeetCode-Feedback/LeetCode-Feedback#11972]
#### Your LeetCode username
jhhornn

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The test case to cover upper and lowercase sensitivity was not included. For example, `Anagram` is an anagram of `nagaram`

#### Code you used for Submit/Run operation

```javascript
// Valid Anagram
var isAnagram = (s, t) => {
    const isEqual = s.length === t.length;
    if (!isEqual) return false;

    return reorder(s) === reorder(t);
};

const reorder = (str) => str
    .split('')
    .sort((a, b) => a.localeCompare(b))
    .join('');
```

#### Language used for code
JavaScript

#### Expected behavior
Expected `console.log(isAnagram("Anagram", "nagaram"))` to return `true` but it returned `false`

#### Additional context
This change is not a bug per se, I just feel it should be implemented to cover wider test cases.

**Comment by stormsunshine** [comment]
Don't you see the constraints?

> `s` and `t` consist of lowercase English letters.

Since the second constraint has restricted all letters to be lowercase, why do you want to add a test case that violates this constraint?

**Comment by jhhornn** [comment]
Oops.
I am so sorry, that was an oversight on my path.
I will close the issue now.
