### ISSUE TITLE
Make LCP problem set available at leetcode.com

### ISSUE THREAD

**Issue by ThomasShaw1** [LeetCode-Feedback/LeetCode-Feedback#11970]
https://leetcode.cn/problems/guess-numbers/

LCP problem set from leetcode.cn should be available at leetcode.com in English. These are great problems for users who want to take advance challenges and prepare for difficult interviews. They should also have an English version at leetcode.com for users that can't read Chinese.

We should also start a new poll to see if leetcode.com users are also interested in seasonal contests considering the user base is much larger now. Should be able to get some new opinions.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
