### ISSUE TITLE
Missing Test Case - 1624. Largest Substring Between Two Equal Characters

### ISSUE THREAD

**Issue by Rajdweep1** [LeetCode-Feedback/LeetCode-Feedback#11971]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [*] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution {
      public int maxLengthBetweenEqualCharacters(String s) {
		int max = -1;
		for (int i = 0; i < s.length(); i++) {
			int lastIndex= s.lastIndexOf(s.charAt(i));
			if(lastIndex != i) 
				max = Math.max(max, lastIndex - (i+1));
		}
		return max;
    }
}
```

#### Here is the test case i want to contribute, it is of length 300 which meets max constraints and it has several characters repeating more than twice.
"lkzudhksajjlndseohycjevdsvrzszbmbzsdkryuylvffglhnxlbnjtpqsizqcgqovaiwqncxhmylykjkckcskgivijmokbtqtlkwagwylmzukllfrlyhuklbylgslzvmsebqrjfbwsivnroghzcywuutotnrwzagdzqlxwcxjsifcfqklqpcqgwkuikmpyfymknyhyrnzeyfybjbdgktmkzfcfvblzfqgdqmdqmsqfupvlcufpgqbhtbhgbihkqlawqupjzknkugmcxsznhgxnefyzewpswnxsxmrvbhwo"

**Comment by LC-Pam** [comment]
"lkzudhksajjlndseohycjevdsvrzszbmbzsdkryuylvffglhnxlbnjtpqsizqcgqovaiwqncxhmylykjkckcskgivijmokbtqtlkwagwylmzukllfrlyhuklbylgslzvmsebqrjfbwsivnroghzcywuutotnrwzagdzqlxwcxjsifcfqklqpcqgwkuikmpyfymknyhyrnzeyfybjbdgktmkzfcfvblzfqgdqmdqmsqfupvlcufpgqbhtbhgbihkqlawqupjzknkugmcxsznhgxnefyzewpswnxsxmrvbhwo"
is the exist test case. 
![Screen Shot 2023-02-24 at 3 56 36 PM](https://user-images.githubusercontent.com/103138242/221290387-697c43f7-4b69-495b-88b1-c650df47d567.png)
