### ISSUE TITLE
Solution passing for a testcase where it should fail for 1517. Find Users With Valid E-Mails

### ISSUE THREAD

**Issue by tt2tyzhang** [LeetCode-Feedback/LeetCode-Feedback#1197]
#### Your LeetCode username
zty3075

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
The code ran for the solution seem to be incorrect in some situations.
```"foo@leetcodeacom"``` seems to be part of the output and gets selected by the solution code.
```"foo@leetcode.comm"``` seems to be part of the output and gets selected by the solution code.

#### Code you used for Submit/Run operation

```
# Test case:
# {"headers": ["user_id", "name", "mail"], "values": [[1, "Foo", "foo@leetcode.comm"], [2, "Bar", "bar@leetcodeacom"]]}

SELECT *
FROM Users
WHERE mail REGEXP '^[a-zA-Z][a-zA-Z_.-]*@leetcode\\.com$';
```

#### Expected behavior

For solution results:
Input:
```
{"headers": ["user_id", "name", "mail"], "values": [[1, "Foo", "foo@leetcode.comm"], [2, "Bar", "bar@leetcodeacom"]]}
```

Expected: No rows should get matched, as the problem defined that "The domain is '@leetcode.com'."
```
{"headers": ["user_id", "name", "mail"], "values": []}
```

Actual: Both rows got matched.
```
{"headers": ["user_id", "name", "mail"], "values": [[1, "Foo", "foo@leetcode.comm"], [2, "Bar", "bar@leetcodeacom"]]}
```

#### Screenshots

![1517_solution_issue](https://user-images.githubusercontent.com/62681375/95751752-0b91b880-0c6d-11eb-975f-2fda32a42a2e.png)

**Comment by lc-kay** [comment]
Hi @tt2tyzhang, 

When I ran your code, I got WA. In addition, your testcase is invalid because list indices must be integers, not str.
