### ISSUE TITLE
Missing Test Case - 762. Prime Number of Set Bits in Binary Representation

### ISSUE THREAD

**Issue by 6202Binit** [LeetCode-Feedback/LeetCode-Feedback#11973]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 
solution

#### Description of the bug

bug is not found

#### Code you used for Submit/Run operation

Using bit manipulation

```
// Two Sum
class Solution {
    public int countPrimeSetBits(int left, int right) {
        final int magic_no = 665772;
    int c = 0;

    for (int n = left; n <= right; ++n)
      if ((magic_no & 1 << Integer.bitCount(n)) > 0)
        ++c;

    return c; 
    }
}
```

#### Language used for code

java

**Comment by 6202Binit** [comment]
my solution

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
