### ISSUE TITLE
Missing Test Case - 20. Valid Parentheses

### ISSUE THREAD

**Issue by mtraver** [LeetCode-Feedback/LeetCode-Feedback#11983]
#### Your LeetCode username
mtraver

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

Question "20. Valid Parentheses" is missing two test cases.
1. A case that verifies that a string with a closing paren before its corresponding opening one fails. E.g.: `']['`
2. A case that verifies that nested parens of different types are handled correctly. A counter-based implementation is unable to handle this, but a stack-based one is, so this case would verify that a stack-based impl or similar is used. E.g.: `'([)]'`

#### Code you used for Submit/Run operation

```python3
class Solution:

    def isValid(self, s: str) -> bool:
        initials = {'(': ')', '[': ']', '{': '}'}
        terminals = {')': '(', ']': '[', '}': '{'}

        stack = []
        for c in s:
            if c in initials:
                stack.append(c)
            elif c in terminals:
                # Terminal encountered before it was opened
                if not stack:
                    return False

                # Check that the popped char is the initial corresponding
                # to this terminal
                if stack.pop() != terminals[c]:
                    return False

        return len(stack) == 0


    def isValidCounters(self, s: str) -> bool:
        terminals = {')': '(', ']': '[', '}': '{'}
        counters = {'(': 0, '{': 0, '[': 0}

        for c in s:
            if c in counters:
                counters[c] += 1

            if c in terminals:
                # If the count drops below zero that means a closing bracket
                # has appeared before it was opened.
                if counters[terminals[c]] == 0:
                    return False

                counters[terminals[c]] -= 1

        for _, count in counters.items():
            if count != 0:
                return False

        return True
```

#### Language used for code

Python 3

#### Expected behavior

Code that does not account for strings like `']['` and `'([)]'` should fail but it does not.

#### Screenshots

n/a

#### Additional context

n/a

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. 

Test cases "][" and "([)]" are existing test cases, please check the below pictures.

'][' and '([)]' showed an Invalid Test Case when we ran them. 
![Screen Shot 2023-02-24 at 4 04 07 PM](https://user-images.githubusercontent.com/103138242/221291985-1d668205-37c7-4f4f-abfa-f28a7a1023ec.png)
![Screen Shot 2023-02-24 at 4 04 45 PM](https://user-images.githubusercontent.com/103138242/221291986-ad33c598-b88f-4eef-99b2-fb20a20c9d7d.png)

**Comment by mtraver** [comment]
Interesting. How does one access those? When running my code I see only three test cases, none of which are the ones I thought were missing.
<img width="722" alt="Screen Shot 2023-02-24 at 2 19 47 PM" src="https://user-images.githubusercontent.com/3804793/221304887-be4c9e2a-9464-4675-9342-cd5d9be6b1b2.png">
<img width="724" alt="Screen Shot 2023-02-24 at 2 22 59 PM" src="https://user-images.githubusercontent.com/3804793/221304901-4fdcbf49-a4d8-46b6-b024-ad5c541971d3.png">
<img width="722" alt="Screen Shot 2023-02-24 at 2 23 04 PM" src="https://user-images.githubusercontent.com/3804793/221304914-622beac0-af62-471e-8ef6-25db95842e8a.png">
