### ISSUE TITLE
1247. 交换字符使得字符串相同题解笔误更正

### ISSUE THREAD

**Issue by mantoufan** [LeetCode-Feedback/LeetCode-Feedback#11986]
**你的 LeetCode 用户名**
mantoufan

**Bug 类型**
- [ ] 题目
- [x] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
[官方题解](https://leetcode.cn/problems/minimum-swaps-to-make-strings-equal/solution/jiao-huan-zi-fu-shi-de-zi-fu-chuan-xiang-6b1u/)存在一处笔误

**期望行为**
图中黄色荧光标记的 `xy` 应更改为 `yx`

**屏幕截图**
![屏幕截图 2023-02-25 083726](https://user-images.githubusercontent.com/4961543/221325744-c5570ed7-c15d-4016-acea-4a91617fe30a.jpg)

**Comment by feiceh** [comment]
你好，经力扣官方题解团队确认，上述内容无误，暂不进行调整。
![img_v2_8dc4c3f5-f4b7-4801-add4-ef2ff3e431cg](https://user-images.githubusercontent.com/61722985/221408586-d34e0998-20c1-4ad1-8393-475e9c312ff3.jpg)
