### ISSUE TITLE
771. Jewels and Stones - Remove unwanted parenthesis

### ISSUE THREAD

**Issue by AjayVV** [LeetCode-Feedback/LeetCode-Feedback#1198]
#### Your LeetCode username
ajayvv

#### Category of the bug
- [x] Solution

#### Description of the bug
A multiple times, the time complexity is mentioned as `O(J.length∗S.length))` , which has extra closing parenthesis

**Comment by lc-kay** [comment]
Hi @AjayVV 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @AjayVV 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
