### ISSUE TITLE
Wrong Test Case

### ISSUE THREAD

**Issue by ethanrobv** [LeetCode-Feedback/LeetCode-Feedback#11984]
#### Your LeetCode username
ethanrobv

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
In the following testcase for problem 1675, the input: [4,1,5,20,3] should result in an answer of 2. The current expected output is 3.
E.g.)
Start with [4,1,5,20,3]. The deviation is 20 - 1 = 19.
Divide 20 by 2 to get [4,1,5,10,3]. The deviation is 10 - 1 = 9.
Multiply 1 by 2 to get [4,2,5,10,3]. The deviation is 10 - 2 = 8.
Multiply 3 by 2 to get [4,2,5,10,6]. The deviation is 10 - 2 = 8.
Divide 6 by 2 to get [4,3,5,5,3]. The deviation is 5 - 3 = 2.

#### Code you used for Submit/Run operation

```
// Minimize Deviation in Array
class Solution:
    def deviation(self, l: List[int]) -> int:
        return int(max(l) - min(l))

    def minimumDeviation(self, nums: List[int]) -> int:
        deviation = max(nums) - min(nums)
        for i,num in enumerate(nums):
            #print(f"num={num}")
            while True:
                if num % 2 == 0:
                    temp = nums.copy()
                    temp[i] = temp[i] / 2
                    if self.deviation(temp) < self.deviation(nums):
                        print(f"num[{i}]={nums[i]} / 2")
                        nums[i] /= 2
                    else:
                        break
                else:
                    temp = nums.copy()
                    temp[i] = temp[i] * 2
                    if self.deviation(temp) < self.deviation(nums):
                        print(f"num[{i}]={nums[i]} * 2")
                        nums[i] *= 2
                    else:
                        break
        print(nums)
        return int(max(nums) - min(nums))
```

#### Expected behavior

I expected the testcase to pass, it failed.

**Comment by seemasangwan** [comment]
Start with [4,1,5,20,3]. The deviation is 20 - 1 = 19.
Divide 20 by 2 to get [4,1,5,10,3]. The deviation is 10 - 1 = 9.
Multiply 1 by 2 to get [4,2,5,10,3]. The deviation is 10 - 2 = 8.
Multiply 3 by 2 to get [4,2,5,10,6]. The deviation is 10 - 2 = 8.
Divide 6 by 2 to get [4,3,5,5,3]. The deviation is 5 - 3 = 2.// when divide 6 by 2 how 10 become 5???????????

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
