### ISSUE TITLE
Missing Test Case - 13. Roman to Integer

### ISSUE THREAD

**Issue by laxmansingh750046** [LeetCode-Feedback/LeetCode-Feedback#11985]
#include<stdio.h>
#include<string.h>

int romanToInt(char*);

int main(){
	char s[]="MCMXCIV";
	printf("%d",romanToInt(s));

	
	return 0;

}

int romanToInt(char * s){

long int num=0,key,pkey;
   for(int i=strlen(s)-1;i>=0;i--){
     switch(s[i]){
     	case 'I':key=1;
     	        break;
	 	case 'V':key=5;
     	        break;
	 	case 'X':key=10;
     	        break;
	 	case 'L':key=50;
     	        break;
	 	case 'C':key=100;
     	        break;
	 	case 'D':key=500;
     	        break;
	 	case 'M':key=1000;
     	        break;
	 }
	 if(i+1==strlen(s)){
	 	pkey=key;
	 }
       if(key>=pkey){
	   num+=key;
	   pkey=key;
	   }
       else {
	   num-=key;
	   }
	  printf("%d",num);
   return num;
}

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
