### ISSUE TITLE
1247. 交换字符使得字符串相同 题目描述与约束条件不符

### ISSUE THREAD

**Issue by RickyLiu0w0** [LeetCode-Feedback/LeetCode-Feedback#11987]
**你的 LeetCode 用户名**
rickyliu

**Bug 类型**
- [X] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
在题目[1247. 交换字符使得字符串相同](https://leetcode.cn/problems/minimum-swaps-to-make-strings-equal/)中，明确描述了字符串`s1`与`s2`长度相同，但是在`提示`中并没有约束`s1.length == s2.length`，且测试案例中，长度不相等的字符串可以作为测试案例输入，答案输出为`-1`。

**你使用的语言**
C++

**测试案例**

"xyxyyx"
"yyyxy"

**期望行为**
题目中去除字符串长度相等的描述
或
提示与测试案例合法性检验中加入s1, s2字符串长度检验

**屏幕截图**
<img width="600" alt="chinese_title" src="https://user-images.githubusercontent.com/50950678/221328844-06afabf7-802e-4f5b-a071-6b9b14b9e228.png">

<img width="626" alt="english_title" src="https://user-images.githubusercontent.com/50950678/221328866-df46abab-f2c4-46e4-9a2e-aca5cc17ac2a.png">

<img width="379" alt="constrain" src="https://user-images.githubusercontent.com/50950678/221328900-37221d92-a297-4b16-841f-391487bbcc09.png">

<img width="217" alt="test_case" src="https://user-images.githubusercontent.com/50950678/221328948-b9aa8bd7-90fc-4fb7-ab47-018ba4ce9b92.png">

**Comment by feiceh** [comment]
你好，当前题目已更新，积分奖励已发放，请查收
