### ISSUE TITLE
Tab size is not saved in new question detail page

### ISSUE THREAD

**Issue by DcXiaoBing** [LeetCode-Feedback/LeetCode-Feedback#11982]
#### Your LeetCode username
DCXiaoBing

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The tab size property in the new version question detail page is not saved.
After setting the tab size to 2 spaces, then go back to home page, then pick any question, the tab size in the editor go back to 4 spaces.

https://youtu.be/40bA7iSPElE This is a video for reproduce steps.
And this is a main blocker for me to use the new question page.

#### Code you used for Submit/Run operation
Not applicable

#### Language used for code
Java

#### Expected behavior
The tab size can stay 2 spaces.

#### Screenshots
https://youtu.be/40bA7iSPElE

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
