### ISSUE TITLE
本地idea运行没有问题，但是提交结果出现错误

### ISSUE THREAD

**Issue by Az-Captain** [LeetCode-Feedback/LeetCode-Feedback#11988]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [ ] leetcode系统测试用例

**描述**
我本地测没有问题，提交结果与本地运行结果不一致，希望你们排查一下

**你使用的语言**
java

**你提交或者运行的代码**
```
class Solution {
    private static int count = 0;

    public int minimumOperations(int[] nums) {
int min = Integer.MAX_VALUE;
        // 找最小
        for (int i = 0; i < nums.length; i++) {
            if (nums[i] > 0) {
                min = Math.min(min, nums[i]);
            }
        }
        if (min > 0 && min<Integer.MAX_VALUE) {
            count++;
        } else {
            return count;
        }
        // 每个元素减去最小非零数
        for (int i = 0; i < nums.length; i++) {
            if (nums[i] > 0) {
                nums[i] -= min;
            }
        }
        return minimumOperations(nums);
    }
}
```

**期望行为**

本地使用 int[] nums = {0}; 结果为0，但是提交后显示3 ；
**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![image](https://user-images.githubusercontent.com/70265420/221329751-d7042dd3-73ad-4545-b046-a34d5ba789f9.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
你好，本地和力扣站结果不一样可能是运行环境不同，建议再仔细调试一下代码。
同时也可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
