### ISSUE TITLE
Missing Test Case - 176. Second Highest Salary

### ISSUE THREAD

**Issue by ramesh-02** [LeetCode-Feedback/LeetCode-Feedback#11991]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

![image](https://user-images.githubusercontent.com/126231471/221344196-83dc17d2-0aea-473a-96b7-7149191dabe7.png)

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
