### ISSUE TITLE
Problem 783 test case missing case root == null

### ISSUE THREAD

**Issue by yuetaoZ** [LeetCode-Feedback/LeetCode-Feedback#12]
**What kind of the bug**
solution test case

**Describe the bug**
Problem 783 test case missing case: root == null

**The code you submit/run**
// Leetcode.783

class Solution {
    Integer res = Integer.MAX_VALUE;
    Integer prev = null;
    public int minDiffInBST(TreeNode root) {
        if (root.left != null) minDiffInBST(root.left);
        if (prev != null) res = Math.min(res, root.val - prev);
        prev = root.val;
        if (root.right != null) minDiffInBST(root.right);
        
        return res;
    }
}

**Expected behavior**
Should be: Runtime Error, NullPointerException, because I didn't tested for the case root == null.
But solution accepted.

**Comment by CooperCooperCooper** [comment]
Hi @yuetaoZ,
Thank you for sharing this issue with us! I've filed it for our engineers to investigate.

**Comment by zerotrac** [comment]
Please note that `The size of the BST will be between 2 and 100`. Thus the root cannot have a `null` value.

**Comment by CooperCooperCooper** [comment]
Hi @yuetaoZ and @zerotrac,
Thank you for your time and support! It's correct that because the size of the BST is at least 2, the empty BST would not a valid test case.
