### ISSUE TITLE
An alternate constant space solution for 994. Rotting Oranges

### ISSUE THREAD

**Issue by mmalu** [LeetCode-Feedback/LeetCode-Feedback#120]
https://leetcode.com/problems/rotting-oranges/discuss/569248/Alternate-approach-BFS-O(N-*-Height)-but-constant-space-easy-to-understand-and-modular-code.

**Comment by mmalu** [comment]
Runtime: 2 ms, faster than 98.08% of Java online submissions for Rotting Oranges.
Memory Usage: 39.1 MB, less than 81.25% of Java online submissions for Rotting Oranges.

**Comment by CooperCooperCooper** [comment]
Hi @mmalu,
Thank you for reaching out to us! Since this issue is within the scope of another technical support team, please redirect this issue to our Help Center here: https://support.leetcode.com/hc/en-us. We appreciate your time and support.

**Comment by mmalu** [comment]
Hi @CooperCooperCooper - This is content-related similar to  #99 . Are you sure, this isn't the place?

**Comment by CooperCooperCooper** [comment]
Hi @mmalu,
My apologies. You're correct, I've relayed this to our team to review.

**Comment by CooperCooperCooper** [comment]
Hi @mmalu,
Thank you for your time. The article is in our queue to be completely rewritten, your contribution is noted down and will be used. Please share your username and this GitHub issue to us on our main [Support Channel](https://support.leetcode.com/hc/en-us) to claim your content contribution reward. We appreciate your support.

**Comment by CooperCooperCooper** [comment]
Hi @mmalu,
Just want to update you that the article for [994. Rotting Oranges ](https://leetcode.com/articles/rotting-oranges/)is now rewritten. Please check it out :)

**Comment by mmalu** [comment]
Looks great. Cheers!
