### ISSUE TITLE
2368. Reachable Nodes With Restrictions BFS solution is incorrect

### ISSUE THREAD

**Issue by 0xGusMcCrae** [LeetCode-Feedback/LeetCode-Feedback#12006]
#### Your LeetCode username
TrevorHemby96

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The official python3 solution for Approach1: BFS is incorrect. In line 16, it tries to use `collections.queue` when it should be using `collections.deque`. 

#### Code you used for Submit/Run operation
    class Solution:
        def reachableNodes(self, n: int, edges: List[List[int]], restricted: List[int]) -> int:
            # Store all edges in 'neighbors'.
            neighbors = collections.defaultdict(list)
            for node_a, node_b in edges:
                neighbors[node_a].append(node_b)
                neighbors[node_b].append(node_a)
            
            # Mark the nodes in 'restricted' as visited.
            seen = [False] * n
            for node in restricted:
                seen[node] = True
            
            # Store all the nodes to be visited in 'queue'.
            ans = 0
            queue = collections.queue([0])     #### This should be queue = collections.deque([0]) ####
            seen[0] = True
            
            while queue:
                curr_node = queue.popleft()
                ans += 1
                
                # For all the neighbors of the current node, if we haven't visit it before,
                # add it to 'queue' and mark it as visited.
                for next_node in neighbors[curr_node]:
                    if not seen[next_node]:
                        seen[next_node] = True
                        queue.append(next_node)
            
            return ans 

#### Language used for code
python3

#### Expected behavior
The provided solution code does not run because collections does not have a 'queue' attribute. It should run correctly (and it does when `queue` is changed to `deque`).

#### Screenshots

    AttributeError: module 'collections' has no attribute 'queue'
        queue = collections.queue([0])
    Line 16 in reachableNodes (Solution.py)
        ret = Solution().reachableNodes(param_1, param_2, param_3)
    Line 59 in _driver (Solution.py)
        _driver()
    Line 70 in <module> (Solution.py)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
