### ISSUE TITLE
818 Race Car. Test Case: target = 4 - incorrect expected output

### ISSUE THREAD

**Issue by BruceJ18** [LeetCode-Feedback/LeetCode-Feedback#12009]
#### Your LeetCode username

BruceJ18

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

------818 Race Car. Test Case: target = 4-----
I believe this test case expected output is incorrect. The description of the Race Car problem clearly states that when
a command, either "A" for accelerate or "R" for reverse, is executed, the number of commands is increased by 1.
For example a test case with target = 3 will have the commands "AA" or 2 commands. Each input of A increases the position by position += speed and then speed is doubled, speed *= 2. When the target = 4 you should get:

commands = 0
0 -> 1 : commands = 1
1 -> 3 : commands = 2
3 -> 7 : commands = 3
7 -> 7 : commands = 4
7 -> 6 : commands = 5
6 -> 4 : commands = 6

Sadly the expected output is 5, which I, again, believe to be incorrect. To add to my case, one of the two preliminary cases has a target = 6, in other words, a command amount of 5, command = 5, which from the tables I constructed above, is clearly one less than the necessary commands needed for the test case with a target = 4.

thanks.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution:
    def racecar(self, target: int) -> int:
        if target is 0:
            return 0

        commands = 0
        position = 0
        reversed = False
        speed = 1

        while position != target:
            if position > target and not reversed:
                speed = -1
                reversed = True
                commands += 1 
            else:
                if position < target and reversed:
                    speed = 1
                    reversed = False
                    commands += 1

            position += speed
            speed *= 2
            commands += 1

        return commands

```

#### Language used for code

Python3

#### Expected behavior

To have my output align with what the expected output had, instead, as I explained above, the test case expected output is incorrectly  assigned a value that is incorrect. I made a small table in the "bug description" section of this bug report that clearly explains what I am saying.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
