### ISSUE TITLE
“面试题 16.10. 生存人数”，平台执行用例结果不符合预期

### ISSUE THREAD

**Issue by leechangqing** [LeetCode-Feedback/LeetCode-Feedback#12000]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
ben-dexiong

**Bug 类型**
- [ ] 题目
- [x] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
RT，平台执行用例结果不符合预期

**你使用的语言**
C++

**你提交或者运行的代码**
```
class Solution {
public:
    int maxAliveYear(vector<int>& birth, vector<int>& death) {
            cout << " birth.size() = " << birth.size() << endl;
            cout << " death.size() = " << death.size() << endl;
                
        return 0;
    }
};
输入：
birth = {1900, 1901, 1950}
death = {1948, 1951, 2000}

```

**期望行为**
1、题目给出错误格式数据，容易误导读者；
2、平台应对入参有效性进行验证，并给出明确提示。

如本例应该接收整形数组入参，而后台未对错误格式数据进行拦截并给出有效入参错误信息，在调用中传入两个空数组，极大影响代码调试和问题定位。

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

![image](https://user-images.githubusercontent.com/15624642/221363527-705d773e-5cd2-4926-b03b-635520f070d3.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
你好，当前题目已更新，积分奖励已发放，请查收
