### ISSUE TITLE
same code different output

### ISSUE THREAD

**Issue by cibo005** [LeetCode-Feedback/LeetCode-Feedback#12003]
#### Your LeetCode username

cibo005

#### Category of the bug
- [x ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Every time I run my code on 18. 4Sum problem sometimes it happens to get different result.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<vector<int>> fourSum(vector<int>& nums, int target)
    {
        int i,j,k,l;
        int n = nums.size();
        vector<vector <int>> quadruplet;

        sort(nums.begin(), nums.end());
        
        for(i=0;i<n;i++)
            {
            while(i>0 && i<n && nums[i] == nums[i-1]) i++;    
            j=i+1;
            
            while(j<k)        
                
                {
                    while( (j>i+1) && j<n && nums[j] == nums[j-1]) j++;
                    
                    k=j+1;
                    l=n-1;
                    while(k<l)        
                        { cout<<l<<endl;
                            if(nums[i] + nums[j] == target - (nums[k] + nums[l]))
                                {
                                    quadruplet.push_back( {nums[i] , nums[j] , nums[k] , nums[l]} );
                                    k++,l--;
                                    
                                    while(k<l && nums[k] == nums[k-1]) k++;
                                    while(k<l && nums[l] == nums[l+1]) l--;
                                }
                            if(nums[i] + nums[j] < target - (nums[k] + nums[l])) k++;
                            if(nums[i] + nums[j] > target - (nums[k] + nums[l])) l--;
                        }
                    j++;
                }
            }
        return quadruplet;
    }
};
```

#### Language used for code

C++

#### Expected behavior

same output every time

#### Screenshots

![4sumWrong](https://user-images.githubusercontent.com/84978140/221368216-780093c0-3704-4968-83f7-9e31d83fa4f2.jpg)
![4sumAccepted](https://user-images.githubusercontent.com/84978140/221368220-c7679581-e43f-4858-a6e0-c414858d3e4d.jpg)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output values.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!
