### ISSUE TITLE
Missing testcase 1224. Maximum Equal Frequency

### ISSUE THREAD

**Issue by Saharsh-R** [LeetCode-Feedback/LeetCode-Feedback#1200]
#### Your LeetCode username
Saharsh-R
[Profile](https://leetcode.com/saharsh-r/)

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
I was looking at [lee215's solution](https://leetcode.com/problems/maximum-equal-frequency/discuss/403743/JavaC%2B%2BPython-Only-2-Cases%3A-Delete-it-or-not) and in his solution there was this following check
```
            if d in [c + 1, 1] and freq[d] == 1:
```
I could not figure out why this required so I modified it to
```
            if d in [c + 1, 1]:
```
And this got accepted! But then I looked through the comments and found [this comment.](https://leetcode.com/problems/maximum-equal-frequency/discuss/403743/JavaC++Python-Only-2-Cases:-Delete-it-or-not/718607)

> It is necessary, look into this testcase : [1,1,2,2,3,4,5,6,6] if you do not put this condition frq[d]==1, then you will get 9 but the answer is 5. And fortunately without this condition too, the code is accepted, as the testcases might not be that strong.

#### Code you used for Submit/Run operation
**The following code is WRONG** I used this code and it still got accepted. The above check is not present in the following code. It fails for the following testcase
```
[1,1,2,2,3,4,5,6,6]
```

```
class Solution:
    def maxEqualFreq(self, A):
        count = collections.Counter()
        freq = [0 for _ in range(len(A) + 1)]
        res = 0
        for n, a in enumerate(A, 1):
            freq[count[a]] -= 1
            freq[count[a] + 1] += 1
            c = count[a] = count[a] + 1
            if freq[c] * c == n and n < len(A):
                res = n + 1
            d = n - freq[c] * c
            if d in [c + 1, 1]:
                res = n
        return res
```

#### Language used for code
Python3

#### Expected behavior
It should return 5 but instead it returns 9

**Comment by lc-kay** [comment]
Hi @Saharsh-R 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Saharsh-R 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
