### ISSUE TITLE
Missing Test Case - 278. First Bad Version

### ISSUE THREAD

**Issue by LexiosAlex** [LeetCode-Feedback/LeetCode-Feedback#12007]
#### Your LeetCode username
LexiosAlex

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

The argument `any` type is wrong for typescript and should be replaced with the type corresponding to the programming problem condition

#### Language used for code
Typescript

#### Expected behavior
Wrong type provided
`var solution = function( isBadVersion: any ) {`

The type should be written as
`var solution = function(isBadVersion: ( version: number ) => boolean ) {`

#### Screenshots
![image](https://user-images.githubusercontent.com/42127361/221381930-994c3054-84be-42e2-868c-9d9cd8f7ddbd.png)
![image](https://user-images.githubusercontent.com/42127361/221381946-5dfea742-437e-4c50-8b74-cc73a6996f66.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

This code is auto-generated. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
