### ISSUE TITLE
Missing Test Case - 1458. Max Dot Product of Two Subsequences

### ISSUE THREAD

**Issue by Jimmyweng006** [LeetCode-Feedback/LeetCode-Feedback#12011]
#### Your LeetCode username

Jimmyweng006

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [O] Missing Test Cases 

#### Description of the bug

A missing testcase will make incomplete solution to AC.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<vector<int>> memo;
    vector<int> nums1, nums2;
    int m, n;
    int maxDotProduct(vector<int>& nums1, vector<int>& nums2) {
        this->nums1 = nums1;
        this->nums2 = nums2;
        m = nums1.size();
        n = nums2.size();
        memo = vector<vector<int>> (m, vector<int> (n, INT_MIN));

        return dp(0, 0);
    }

    int dp(int i, int j) {
        if (i == m || j == n) {
            return 0;
        }
        
        if (memo[i][j] != INT_MIN) {
            return memo[i][j];
        }

        int notChooseI = dp(i + 1, j);
        int notChooseJ = dp(i, j + 1);
        memo[i][j] = max({
            memo[i][j],
            notChooseI == 0 ? INT_MIN : notChooseI,
            notChooseJ == 0 ? INT_MIN : notChooseJ,
            nums1[i] * nums2[j] + dp(i + 1, j + 1),
            nums1[i] * nums2[j]
        });

        return memo[i][j];
    }
};
```

#### Language used for code

C++

#### Expected behavior

Incomplete solution will get WA.

#### Screenshots

![image](https://user-images.githubusercontent.com/43208413/221387768-1ae62c30-a8b2-4a12-9c5b-58b277edd091.png)

#### Additional context

testcase:
nums1 = [-1,0]
nums2 = [1,0]

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
