### ISSUE TITLE
Missing Test Case - 1163. Last Substring in Lexicographical Order

### ISSUE THREAD

**Issue by sam20908** [LeetCode-Feedback/LeetCode-Feedback#12012]
#### Your LeetCode username
SajLeet

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The code submitted below gives the wrong answer but there's no test case to detect it
Test case: `"wjwjwdvsr"`

Code below: `"wjwdvsr"`
Expected: `"wjwjwdvsr"`

#### Code you used for Submit/Run operation

```
class Solution {
public:
  string lastSubstring(string s) {
    int n = s.size();

    int start = 0, j = 0, prev_j = 0;
    for (int i = 0; i < n; i++) {
      if (s[i] > s[start]) {
        start = j = prev_j = i;
      }
      if (s[i] < s[start + i - j]) {
        j = prev_j;
      }
      if (s[i] > s[start + i - j]) {
        start = prev_j = j;
      }
      if (s[i] == s[j] && i > 0 && s[i] != s[i - 1]) {
        prev_j = j;
        j = i;
      }
    }

    return s.substr(start);
  }
};
```

#### Language used for code
C++

#### Expected behavior
The above solution should be judged "Wrong Answer"

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
