### ISSUE TITLE
 Missing Test Cases - 2577. Minimum Time to Visit a Cell In a Grid

### ISSUE THREAD

**Issue by huanglanzhiguan** [LeetCode-Feedback/LeetCode-Feedback#12014]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Missing test case:
[[0,1,99],[3,99,99],[4,5,6]]

#### Code you used for Submit/Run operation

```
int ts[100000];
int row;
int col;
int x[4]={0,0,-1,1};
int y[4]={-1,1,0,0};
class Solution {
public:
    int minimumTime(vector<vector<int>>& grid) {
        int row=grid.size();
        int col=grid[0].size();
        for(int i=0;i<row*col;i++)
            ts[i]=-1;
        priority_queue<pair<int,int>,vector<pair<int,int>>,greater<pair<int,int>>> q;
        q.push({0,0});
        ts[0]=0;
        while(!q.empty())
        {
            int t=ts[q.top().second];
            int x1=q.top().second/col;
            int y1=q.top().second%col;
            if(x1==row-1&&y1==col-1)
                return t;
            q.pop();
            for(int i=0;i<4;i++)
            if(x1+x[i]>=0&&x1+x[i]<row&&y1+y[i]>=0&&y1+y[i]<col&&ts[(x1+x[i])*col+y1+y[i]]==-1)
            {
                if(x1==0&&y1==0)
                {
                    if(grid[x1+x[i]][y1+y[i]]<=1)
                    {
                        q.push({t+1,(x1+x[i])*col+y1+y[i]});
                        ts[(x1+x[i])*col+y1+y[i]]=t+1;
                    }
                }
                else
                {
                    
                    int re;
                    if(grid[x1+x[i]][y1+y[i]]>t)
                    re=grid[x1+x[i]][y1+y[i]]+((grid[x1+x[i]][y1+y[i]]-t)%2==0);
                    else
                    re=t+1;
                    q.push({re,(x1+x[i])*col+y1+y[i]});
                    ts[(x1+x[i])*col+y1+y[i]]=re;
                }
            }
        }
        return -1;
    }
};
```

#### Language used for code
C++

#### Expected behavior
The correct answer is 6, but the code above passed all tests got 102.

#### Screenshots
<img width="1147" alt="image" src="https://user-images.githubusercontent.com/8380189/221392463-b41c23d2-238c-4d77-b982-6341ae07a577.png">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
