### ISSUE TITLE
23. Merge k Sorted Lists - Javascript/Typescript Linked Lists are undefined (TypeError)

### ISSUE THREAD

**Issue by Chappydev** [LeetCode-Feedback/LeetCode-Feedback#12013]
#### Your LeetCode username

Chappydev

#### Category of the bug
- [x] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

When accessing next property of a ListNode, this error is thrown: TypeError: Cannot read properties of undefined (reading 'next'). This happens only on run for this question - submit seems to work normally. I also tested it on my local node environment and it worked as expected.

#### Code you used for Submit/Run operation

Note: not a working solution, just intended to reproduce the error.
```
// Merge k Sorted Lists
var mergeKLists = function(lists) {
    if (lists[0].next) {
        return lists[0].next;
    }
};
```
```
// Merge k Sorted Lists
var mergeKLists = function(lists) {
    if (lists[0].val) {
        return lists[0].next;
    }
};
```

#### Language used for code

Javascript, Typescript

#### Expected behavior

Expected "Wrong Answer" with an output of the remaining nodes (this is what happens on submit). Instead, I am getting a Runtime Error.

#### Screenshots

On submit:
![image](https://user-images.githubusercontent.com/99625418/221392090-9fed3bd4-0205-47fc-9c43-66fb766ca56c.png)

On run:
![image](https://user-images.githubusercontent.com/99625418/221392115-50319571-a01b-47eb-bba8-7fa365e78cdd.png)
![image](https://user-images.githubusercontent.com/99625418/221392136-462c13bb-64ad-4d10-bca2-f13795cc588a.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

https://leetcode.com/submissions/detail/906158199/
https://leetcode.com/submissions/detail/906157995/


Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
![Screen Shot 2023-02-27 at 5 34 31 PM](https://user-images.githubusercontent.com/103138242/221701443-ebd2b152-942e-41cf-892f-9a33cb26749b.png)
