### ISSUE TITLE
322. Coin Change - Editorial Image too small

### ISSUE THREAD

**Issue by StrawHatDragon100** [LeetCode-Feedback/LeetCode-Feedback#12010]
#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The image displayed in  the editorial is too small.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

![image](https://user-images.githubusercontent.com/19656900/221387637-27380055-fe1c-4819-895b-bdfaddfcce2f.png)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
