### ISSUE TITLE
Ambiguous problem description for #674

### ISSUE THREAD

**Issue by snehasishroy** [LeetCode-Feedback/LeetCode-Feedback#1201]
#### Your LeetCode username
chrisgriffin

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Problem title of #674 (https://leetcode.com/problems/longest-continuous-increasing-subsequence/) says to find Longest Continuous Increasing Subsequence but the problem description says to find the length of longest continuous increasing subsequence (subarray).

It's too confusing, it can be simplified if you reword the description to finding the longest increasing subarray along with changing the problem title.

Multiple people have found it to be confusing e.g https://leetcode.com/problems/longest-continuous-increasing-subsequence/discuss/266335/Definition-of-subsequence-is-confusing.-Better-talk-about-it-to-your-interviewer

#### Expected behavior
Problem title should be Longest Increasing Subarray and the description should be updated to reflect it as well.

**Comment by lc-kay** [comment]
Hi @snehasishroy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @snehasishroy 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
