### ISSUE TITLE
Missing Test Case - 2575. Find the Divisibility Array of a String

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#12027]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets WA on the following testcase:
"4"
22

#### Code you used for Submit/Run operation

```
class Solution:
    def divisibilityArray(self, word: str, m: int) -> List[int]:
        
        def word2int(string):
            return int(string)
        
        def div(num,m):
            return 1 if num % m == 0 else 0 
        rest = [0 for i in range(len(word))]
        ans = [0 for i in range(len(word))]
        rest[0] = int(word[0]) % m 
        for i in range(len(word)):
            rest[i] = (rest[i-1] * 10 + int(word[i]) ) % m 

        for i in range(len(rest)):
            ans[i] = 0 if rest[i] != 0 else 1 
        return ans 
```

#### Language used for code

Python3

#### Expected behavior

Output: [1]
Expected: [0]

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
