### ISSUE TITLE
Incorrect input in problem 394

### ISSUE THREAD

**Issue by stesik-slava** [LeetCode-Feedback/LeetCode-Feedback#12039]
Hi!
Description in [problem 394](https://leetcode.com/problems/decode-string/description/) says that the input string is always valid. But in the one of the test cases input string is "3".
![image](https://user-images.githubusercontent.com/6724593/221473296-55e70d29-4c19-41d5-ae97-45d9f721d016.png)

Thank you!

**Comment by k1gabyt0** [comment]
I faced this problem right now and wanted to report it.
It is a nice coincidence that you had already done it.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by stormsunshine** [comment]
@LC-Pam I don't think the code is needed. This issue is that the test case "3" is invalid.

Any valid test case should never ends with a number. Each number must be followed with a pair of square brackets.

**Comment by rajorpratyush** [comment]
I am seeing many question with invalid test cases which were working fine before
