### ISSUE TITLE
57. Insert Interval - Broken Latex in editorial

### ISSUE THREAD

**Issue by StrawHatDragon100** [LeetCode-Feedback/LeetCode-Feedback#12038]
#### Category of the bug
- [ ] Question
- [ x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

This is broken Latex in the editorial

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

![image](https://user-images.githubusercontent.com/19656900/221439407-e35e323d-70ee-456c-93b7-d097b02b2cbb.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
