### ISSUE TITLE
Missing Test Case - 2575. Find the Divisibility Array of a String

### ISSUE THREAD

**Issue by sudevdhali** [LeetCode-Feedback/LeetCode-Feedback#12031]
#### Your LeetCode username
newbiesd

#### Category of the bug
- [ ] Question
- [ ] Language
- [ ] Solution
- [ .] Missing Test Cases 

#### Description of the bug

for the below testcase
"3"
11
the code isnt giving proper result but its getting accepted

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<int> divisibilityArray(string word, int m) {
        vector<int> res(word.size(),0),lst(word.size(),0);
        long long int lc=0;
        lst[0]=(word[0]-'0')%m;
        for(int i=0;i<word.size();i++){
            long long li=lst[(word.size()+i-1)%word.size()];
            lst[i]=(li*10+(word[i]-'0'))%m;
            cout<<lst[i]<<i<<" ";
            res[i]=(lst[i]==0);
        }
        return res;
    }
};
```

#### Language used for code
C++

#### Expected behavior
It should return [0] but its returning [1]

#### Screenshots

![image](https://user-images.githubusercontent.com/60395148/221403419-8bd5505b-bd50-4782-90c7-6ef93e978c38.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
