### ISSUE TITLE
Missing Test Case - 2575. Find the Divisibility Array of a String

### ISSUE THREAD

**Issue by sudevdhali** [LeetCode-Feedback/LeetCode-Feedback#12030]
#### Your LeetCode username
newbiesd

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ .] Missing Test Cases 

#### Description of the bug
For the testcase 
"3"
11
 this code gives doesnt work but it is getting accepted

#### Code you used for Submit/Run operation

```
class Solution:
    def divisibilityArray(self, word: str, m: int) -> List[int]:
        rest = [0 for i in range(len(word))]
        ans = [0 for i in range(len(word))]
        rest[0] = int(word[0]) % m 
        for i in range(len(word)):
            print(rest[i-1] * 10 + int(word[i])%m)
            rest[i] = (rest[i-1] * 10 + int(word[i]) ) % m 
            ans[i] = 0 if rest[i] != 0 else 1 
        return ans 
```

#### Language used for code
python3

#### Expected behavior

Result should be [0] but it is giving [1]

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
