### ISSUE TITLE
Typo - 2574. Left and Right Sum Differences

### ISSUE THREAD

**Issue by occidere** [LeetCode-Feedback/LeetCode-Feedback#12044]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug
- A typo in given methods for all languages (`Rigth` -> `Right`)

![image](https://user-images.githubusercontent.com/20942871/221505226-7efd2500-fe55-4bdb-9896-853f38d02fa3.png)

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

- All languages

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
