### ISSUE TITLE
Missing Test Case - 1615. Maximal Network Rank

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#1204]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution from discuss section is accepted but fails on the following test case:

15
[[8, 12], [5, 11], [5, 12], [9, 4], [0, 9], [1, 8], [10, 2], [13, 14], [3, 4], [11, 3], [11, 8], [5, 10]]

#### Code you used for Submit/Run operation

```
class Solution {
    public int maximalNetworkRank(int n, int[][] roads) {
        if (n <= 0 || roads == null || roads.length < 1)
            return 0;

        Map<Integer, Set<Integer>> cityToRoads = new HashMap<>();
        for (int[] arr : roads) {
            cityToRoads.putIfAbsent(arr[0], new HashSet<>());
            cityToRoads.get(arr[0]).add(arr[1]);

            cityToRoads.putIfAbsent(arr[1], new HashSet<>());
            cityToRoads.get(arr[1]).add(arr[0]);
        }

        int maxKey = 0;
        int maxRank = 0;

        for (Map.Entry<Integer, Set<Integer>> entry : cityToRoads.entrySet()) {
            if (entry.getValue().size() >= maxRank) {
                maxRank = entry.getValue().size();
                maxKey = entry.getKey();
            }
        }

        int maxRankSecond = 0;
        for (Map.Entry<Integer, Set<Integer>> entry : cityToRoads.entrySet()) {
            if (entry.getKey() != maxKey) {
                if (cityToRoads.get(maxKey).contains(entry.getKey())) {
                    cityToRoads.get(entry.getKey()).remove(maxKey);
                }

                maxRankSecond = Math.max(maxRankSecond, entry.getValue().size());
            }
        }

        return maxRank + maxRankSecond;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/95929061-fc0b9000-0d90-11eb-9b72-19918d45814a.png)
![image](https://user-images.githubusercontent.com/32546406/95929074-03cb3480-0d91-11eb-9bd4-b2d9184ade82.png)

#### Additional context

https://leetcode.com/problems/maximal-network-rank/discuss/890036/Java-Solution-O(N)-for-Time-and-Space-using-HashMap

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
