### ISSUE TITLE
Missing Testcase  for 671. Second Minimum Node In a Binary Tree

### ISSUE THREAD

**Issue by sunildharani** [LeetCode-Feedback/LeetCode-Feedback#1205]
#### Your LeetCode username
sunildharani

#### Category of the bug
Question : 671. Second Minimum Node In a Binary Tree

#### Description of the bug
My Code got accepted .. But it fails for a testcase. Need to add testcase - [2,2147483647,null,2147483647,2147483647]

#### Code you used for Submit/Run operation
// 671. Second Minimum Node In a Binary Tree
```
class Solution {
    int firstMin = Integer.MAX_VALUE;
    int secondMin = Integer.MAX_VALUE;
    boolean found = false;
    public int findSecondMinimumValue(TreeNode root) {
        findvalue(root);
        if(!found){
           return -1;
        } 
        return secondMin; 
    }
    
    public int findvalue(TreeNode root){
         if(root == null){
            return Integer.MAX_VALUE;
        }
        int min = Math.min(root.val,findvalue(root.left));
        int ans =  Math.min(min,findvalue(root.right)); 
        if(secondMin >= ans){
            if(firstMin > ans){
                secondMin = firstMin;
                if(firstMin != Integer.MAX_VALUE){
                    found = true;
                }
                firstMin = ans;
            }else if(firstMin != ans){
                secondMin = ans;
                found = true;
            }
        }
        return ans; 
    }
}

```

#### Language used for code
Java

#### Expected behavior
The solution should not be accepted since it fails on the test case

**Comment by sunildharani** [comment]
Testcase : [2,2147483647,null,2147483647,2147483647]

**Comment by lc-kay** [comment]
Hi @sunildharani 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @sunildharani 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!

**Comment by sunildharani** [comment]
Hi,
 The constraints are :
"1) The number of nodes in the tree is in the range [1, 25].
2) 1 <= Node.val <= 2 ** 31 - 1
3) root.val == min(root.left.val, root.right.val) for each internal node of the tree. "

Testcase : [2,2147483647,null,2147483647,2147483647]
Number of nodes are less than 25 and greater than 1. Node values are within the range. It also satisfies min(root.left.val, root.right.val) for each internal node of the tree.


Are you going to add any new constraint ?

**Comment by lc-kay** [comment]
@sunildharani The test case doesn't satisfy the constraints, please test this in the run code for the error.
