### ISSUE TITLE
Missing Test Case - 2573. Find the String with LCP

### ISSUE THREAD

**Issue by peacalm** [LeetCode-Feedback/LeetCode-Feedback#12055]
#### Your LeetCode username
ShuangquanLi

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Some code([example1](https://leetcode.com/submissions/detail/900802586/), [example2](https://leetcode.com/submissions/detail/901252948/)) only checks this two constraints:

* if lcp[i][j] == 0 then str[i] != str[j]
* if lcp[i][j] < n - j then str[i + lcp[i][j]] != str[j + lcp[i][j]]

but also got Accepted!
Here is a new case which can make it get Wrong Answer:
```
[[5,0,2,0,0],[0,4,0,0,0],[2,0,3,0,0],[0,0,0,2,0],[0,0,0,0,1]]
```
<img width="587" alt="image" src="https://user-images.githubusercontent.com/16322505/221730647-9905788f-10e5-40eb-ab7a-1a9ce8358b02.png">

#### Code you used for Submit/Run operation

The wrong code, which can AC:
```
class Solution:
    def findTheString(self, lcp: List[List[int]]) -> str:
        n = len(lcp)
        ret = [-1] * n
        c = 0
        for i in range(0, n):
            if lcp[i][i] != n - i: return ''
            if ret[i] == -1:
                if c >= 26: return''
                ret[i] = c
                c += 1
            for j in range(i + 1, n):
                if lcp[i][j] != lcp[j][i] or lcp[i][j] > n - j: return ''
                if lcp[i][j] > 0:
                    if ret[j] >= 0 and ret[j] != ret[i]: return ''
                    ret[j] = ret[i]
        for i in range(0, n):
            for j in range(i + 1, n):
                if lcp[i][j] == 0 and ret[i] == ret[j]:
                    return ''
                if lcp[i][j] < n - j and ret[i + lcp[i][j]] == ret[j + lcp[i][j]]:
                    return ''
        return ''.join(chr(ord('a') + i) for i in ret)
```

#### Language used for code

Python

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
