### ISSUE TITLE
Missing Test Case - 232. Implement Queue using Stacks

### ISSUE THREAD

**Issue by shuvo671** [LeetCode-Feedback/LeetCode-Feedback#12065]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Additional context

Test Case 1:
Input:
queue = MyQueue()
queue.push(1)
queue.push(2)
queue.push(3)
queue.push(4)

Output:
queue.peek() # should return 1
queue.pop() # should return 1
queue.pop() # should return 2
queue.pop() # should return 3
queue.empty() # should return False
queue.pop() # should return 4
queue.empty() # should return True

**Comment by shuvo671** [comment]
Test Case 1:
Input:
queue = MyQueue()
queue.push(1)
queue.push(2)
queue.push(3)
queue.push(4)

Output:
queue.peek() # should return 1
queue.pop() # should return 1
queue.pop() # should return 2
queue.pop() # should return 3
queue.empty() # should return False
queue.pop() # should return 4
queue.empty() # should return True

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
