### ISSUE TITLE
Missing Test Case - 24. Swap Nodes in Pairs

### ISSUE THREAD

**Issue by arnabbanerjee001** [LeetCode-Feedback/LeetCode-Feedback#12074]
public class Solution {
    public ListNode swapPairs(ListNode head) {
        ListNode fakeHead = new ListNode(-1);
        fakeHead.next = head;
        ListNode node = fakeHead;
        while (node!=null & node.next != null && node.next.next!= null){
            ListNode first = node;
            ListNode second = node.next;
            ListNode third = node.next.next;
            first.next = third;
            second.next = third.next;
            third.next = second;
            node = second;
        }
        return fakeHead.next;
    }
}

**Comment by Anshkaran7** [comment]
class Solution {
    public ListNode swapPairs(ListNode head) {
        if (head == null || head.next == null) {
            return head;
        }
        ListNode pre = new ListNode(-1);
        pre.next = head;
        ListNode dummy = pre;
        
        while (pre.next != null && pre.next.next != null) {
            ListNode a = pre.next;
            ListNode b = a.next;
            
            a.next = b.next;
            b.next = a;
            pre.next = b;
            
            // Move
            pre = pre.next.next;
        }
        return dummy.next;
    }
}

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
