### ISSUE TITLE
Q194. Test case is not correct.

### ISSUE THREAD

**Issue by yingzhuo1994** [LeetCode-Feedback/LeetCode-Feedback#12077]
#### Your LeetCode username

yingzhuo1994

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Given the below input:
Line 1\nLine 2\nLine 3\nLine 4\nLine 5\nLine 6\nLine 7\nLine 8\nLine 9\nLine 10

The expected output:
Line 10

This is given by the test case, and I think this is not correct.

#### Code you used for Submit/Run operation

```
awk '
{
    for (i = 1; i <= NF; i++) {
        if(NR == 1) {
            s[i] = $i; } else { s[i] = s[i] " " $i;
        }
    }
}
END {
    for (i = 1; s[i] != ""; i++) {
        print s[i];
    }
}' file.txt
```

#### Language used for code

Bash

#### Expected behavior

Correct answer should be:
Line Line Line Line Line Line Line Line Line Line\n1 2 3 4 5 6 7 8 9 10

#### Screenshots

![image](https://user-images.githubusercontent.com/74639659/222029830-12a22c5f-d375-4ca9-a606-b5bf89d973a1.png)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
