### ISSUE TITLE
Missing Test Case - 215. Kth Largest Element in an Array

### ISSUE THREAD

**Issue by AdityaRJha** [LeetCode-Feedback/LeetCode-Feedback#12076]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
//215. Kth Largest Element in an Array
class Solution {
    public int findKthLargest(int[] nums, int k) {
        Set<Integer> set = new TreeSet<>();

        for(int i = 0; i < nums.length; i++){
            set.add(nums[i]);
        }
        k = set.size() - k + 1;

        --k;
        Iterator<Integer> i = set.iterator();

        while(k > 0){
            i.next();
            --k;
        }

        return i.next();
    }
}
```

#### Language used for code
Java

#### Expected behavior
For test case 2 of public test case
nums = [3,2,3,1,2,4,5,5,6]
k = 4
Output should be = 3
While in the Test Case it's mentioned Expected output = 4

#### Additional context
This bug has resulted in the development of various other bugs in other test cases, as the developers must have developed those test cases around the defective test case.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
