### ISSUE TITLE
Arrays 101:Array Insertions - a mistake in the picture

### ISSUE THREAD

**Issue by Ggg93** [LeetCode-Feedback/LeetCode-Feedback#12075]
#### Category of the bug
- [ ] Question

#### Description of the bug
In the "Arrays 101" card (Inserting Items into an Array -> Array Insertions) there is a mistake in the third picture ("Inserting Anywhere in the Array" section): there should be "8 now takes the **fifth** cell" instead of "8 now takes the **first** cell".

#### Screenshots
![image](https://user-images.githubusercontent.com/37405665/221995011-77f230f5-1b46-4829-95c3-0afc9df60847.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback. 

Please rely on this ticket with your LC username. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
