### ISSUE TITLE
Missing Test Case - 27. Remove Element

### ISSUE THREAD

**Issue by 95swappedsi** [LeetCode-Feedback/LeetCode-Feedback#12073]
#### Your LeetCode username

95swappedsi

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

My solution fails using leetcode, but the expected output and return in VS appear correct.

#### Code you used for Submit/Run operation

```
public class Solution {
    public int RemoveElement(int[] nums, int val)
    {
        int cnt = 0;

       int i = 0;
        while (i < nums.Length - 1)
        {
            //i++;
            if (nums[i] != val)
                cnt++;
            i++;
        }

        int[] expected = new int[cnt];
        cnt = 0;
        foreach (int num in nums)
        {
            if (num != val)
            {
                expected[cnt] = num;
                cnt++;
            }
        }
        //nums = expected.ToArray();
        for (int n = 0; n < expected.Length - 1; n++)
        {
            nums[n] = expected[n];
        }
        return cnt;
    }
}
```

#### Language used for code

C#

#### Expected behavior

It should pass as the input int[] doesn't even contain two instances of 3.

#### Screenshots

Failure Message:
![image](https://user-images.githubusercontent.com/114018037/221950853-dbda6979-0b73-4a08-91ad-6cc0d150cc6e.png)
Chapter/Section:
![image](https://user-images.githubusercontent.com/114018037/221951211-fc38d326-b02e-4306-8f54-789a8a0eaea6.png)
VS code:
![image](https://user-images.githubusercontent.com/114018037/221952290-d217db9f-02db-4332-af1a-63fdc390c9f8.png)

#### Additional context

This is the chapter on Arrays the second pass at "Remove Element" under "In-Place Operations"... I will feel really dumb when this isn't an issue with a testcase, but I can't seem to figure what else is the issue causing the different behavior.

**Comment by 95swappedsi** [comment]
Rereading this I guess it doesn't make sense it is an issue with a test case, but I am still not sure why the VS result varies from the result on leetcode.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output values.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!
