### ISSUE TITLE
Missing test case for sliding window median

### ISSUE THREAD

**Issue by resotto** [LeetCode-Feedback/LeetCode-Feedback#12088]
#### Your LeetCode username
resotto

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The following code could be AC but LTE with the test case below:
https://leetcode.com/problems/sliding-window-median/description/

#### Code you used for Submit/Run operation
```java
    public double[] medianSlidingWindow(int[] nums, int k) {
        // time: O(N + (N-K)K) where N is nums.length
        // space: O(K) except for the answer space
        int n = nums.length;
        var ans = new double[n - k + 1];
        var l = new PriorityQueue<Integer>((a, b) -> -Integer.compare(a, b));
        var r = new PriorityQueue<Integer>();
        for (int i = 0; i < n; i++) {
            if (l.size() <= r.size()) {
                r.add(nums[i]);
                l.add(r.poll());
            } else {
                l.add(nums[i]);
                r.add(l.poll());
            }
            if (l.size() + r.size() == k) {
                if (l.size() == r.size()) {
                    ans[i - k + 1] = (double) ((long) l.peek() + (long) r.peek()) / 2;
                } else {
                    ans[i - k + 1] = (double) l.peek();
                }
                if (!l.remove(nums[i - k + 1])) {
                    r.remove(nums[i - k + 1]);
                }
            }
        }
        return ans;
    }
```

#### Language used for code
Java

#### Expected behavior
The above code must not be AC.

#### Test case
nums =
=> [testcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/10860886/testcase.txt)

k = 
```
50000
````

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code AC submission link (we received Compile Error when we submit your above code:https://leetcode.com/submissions/detail/907318209/)

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by resotto** [comment]
This is the link: https://leetcode.com/problems/sliding-window-median/submissions/907084995/
And the code is below:
```java
class Solution {
    public double[] medianSlidingWindow(int[] nums, int k) {
        // time: O(N + (N-K)K) where N is nums.length
        // space: O(K) except for the answer space
        int n = nums.length;
        var ans = new double[n - k + 1];
        var l = new PriorityQueue<Integer>((a, b) -> -Integer.compare(a, b));
        var r = new PriorityQueue<Integer>();
        for (int i = 0; i < n; i++) {
            if (l.size() <= r.size()) {
                r.add(nums[i]);
                l.add(r.poll());
            } else {
                l.add(nums[i]);
                r.add(l.poll());
            }
            if (l.size() + r.size() == k) {
                if (l.size() == r.size()) {
                    ans[i - k + 1] = (double) ((long) l.peek() + (long) r.peek()) / 2;
                } else {
                    ans[i - k + 1] = (double) l.peek();
                }
                if (!l.remove(nums[i - k + 1])) {
                    r.remove(nums[i - k + 1]);
                }
            }
        }
        return ans;
    }
}
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

(Missing k in the test case.)

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by resotto** [comment]
k = 50000

Couldn't you check that?

**Comment by resotto** [comment]
@LC-Pam

**Comment by resotto** [comment]
@LC-Pam 
This is updated text file with k = 50000.
[testcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/10919457/testcase.txt)
