### ISSUE TITLE
Invalid Test Case - 402. Remove K Digits

### ISSUE THREAD

**Issue by rajorpratyush** [LeetCode-Feedback/LeetCode-Feedback#12081]
#### Your LeetCode username

[user1027JB]

#### Category of the bug
- [ ] Question

#### Description of the bug

Test case is wrong.
"1173"
2
Removing two digit should result in 2 digit output
But here output is in 3 digit

#### Code you used for Submit/Run operation

```
var removeKdigits = function(num, k) {
    
    const stack = []

    for(let i=0;i<num.length;i++){

        const digit = num[i]

        while(k!=0 && stack[stack.length-1]>parseInt(digit)){
            stack.pop()
            k-=1
        }

        stack.push(digit)

    }

    
    const required = num.length-k
    if(required===0){
        return "0"
    }
    return String(parseInt(stack.splice(0,required).join("")))

    


};
```

#### Language used for code

Javascript

#### Expected behavior

"1173"
2
Removing two digit should result in 2 digit output
But here output is in 3 digit

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
