### ISSUE TITLE
Incorrect memory complexity in the solution article - 912. Sort an Array

### ISSUE THREAD

**Issue by przemek3d88** [LeetCode-Feedback/LeetCode-Feedback#12086]
#### Your LeetCode username
przemysaw2

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In solution 3 - counting sort, the c++ code uses O(n+k) memory. This is caused by the fact that the `while (counts[val] > 0)` condition inserts val into the map if the element was not there. After that loop, the whole range will be contained in the map.

In order to avoid that problem, you should use an iterator or another check, to verify that the element is not in the map.

Please double-check other languages.

#### Language used for code
C++

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
