### ISSUE TITLE
system design course MCQ description error

### ISSUE THREAD

**Issue by shockwang** [LeetCode-Feedback/LeetCode-Feedback#12083]
#### Your LeetCode username

shockwang

#### Category of the bug
-  Question

#### Description of the bug

System Design course, Practice Problems, Problem description error. "wrong" should be "correct", since the correct answer is opposite.

#### Screenshots

![image](https://user-images.githubusercontent.com/121087092/222083707-d3db1736-5340-4146-a60a-c89b205bab10.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The page link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by shockwang** [comment]
page link as follows:
https://leetcode.com/explore/learn/card/system-design/691/practice-problems/4419/

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The problem setting is correct.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by shockwang** [comment]
ah, now I got it, so the description "What is wrong with..." actually means "What is the problem with...", so I misunderstood the description meaning.
