### ISSUE TITLE
Heap Sort card

### ISSUE THREAD

**Issue by ShovalAtar** [LeetCode-Feedback/LeetCode-Feedback#12089]
The heap explore card is great! Thank you so much.
The only thing I would change is in the Heap Sort card. The first few paragraphs looks like a copy paste from somewhere else and are a bit confusing and not relevant

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

Thank you for your support.
