### ISSUE TITLE
Failing Test Case - 28. Find the Index of the First Occurrence in a String

### ISSUE THREAD

**Issue by Akash-Karmakar-e3082** [LeetCode-Feedback/LeetCode-Feedback#12095]
#### Your LeetCode username

akashkarmakar

#### Category of the bug
- [ ] Question
- [ ] Solution
- [c++ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

When I run the test case with haystack "abc" and needle "c" I get the correct output.
But when I submit the code the same code gives the wrong output. 
Attached the SS for the same.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    int strStr(string haystack, string needle) {
        int hl,nl,i,j;
        hl=haystack.length();
        nl=needle.length();
        if(nl>hl)return -1;
        int ar[nl+1][hl+1];
        for(i=0;i<nl;i++)for(j=0;j<hl;j++)ar[i][j]=0;
        for(i=1;i<=nl;i++)
        {
            for(j=1;j<=hl;j++)
            {
                if(needle[i-1]==haystack[j-1])
                {
                    ar[i][j]=ar[i-1][j-1]+1;
                }
            }
        }
        for(i=1;i<=hl;i++)
        {
            for(j=1;j<=nl;j++)
            {
                if(ar[j][i]==nl)
                {
                    return i-nl;
                }
            }
        }
        return -1;
    }
};
```

#### Screenshots

<img width="834" alt="Screenshot 2023-03-02 at 12 10 14 AM" src="https://user-images.githubusercontent.com/56721980/222234715-88d9c48f-62ea-4565-ace1-3db5f2db4e70.png">
<img width="835" alt="Screenshot 2023-03-02 at 12 10 29 AM" src="https://user-images.githubusercontent.com/56721980/222234722-b19e852c-d534-4590-b30f-f0f88b5417a5.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output values.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!
