### ISSUE TITLE
Missing Test Case - 912. Sort an Array

### ISSUE THREAD

**Issue by Leven77** [LeetCode-Feedback/LeetCode-Feedback#12097]
#### Your LeetCode username
Liphy

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

i submitted my code and leetcode system told me the code is Time Limit Exceeded without giving the test case.
i need to know the test case.

#### Code you used for Submit/Run operation

```
public int[] sortArray(int[] nums) {
        quicksort(nums, 0, nums.length);
        return nums;
    }
    public void quicksort(int[] in, int start, int length) {
        if (length <= 1) return;

        int val = in[start];
        int current = start;
        for (int i = start + 1; i < start + length; i++) {
            if (in[i] < val) {
                in[current] = in[i];
                current++;
                in[i] = in[current];
            }
        }
        in[current] = val;
        quicksort(in, start, current - start);
        quicksort(in, current + 1, length - current + start - 1);
    }
```

#### Language used for code
Java

#### Expected behavior

The system should display the test case

#### Screenshots

![微信图片_20230302134833](https://user-images.githubusercontent.com/35281431/222354894-8c35f38b-d922-4f74-97bd-7ee205686012.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

The code received Compile Error after submitted: https://leetcode.com/submissions/detail/907929797/

Please feel free to refer to the discussion section of the problem to see how other users have optimized their codes!

**Comment by Leven77** [comment]
The code  received Compile Error after submitted ( https://leetcode.com/submissions/detail/907929797/) because the code without class. It should be submitt like this:
```
class Solution {
    public int[] sortArray(int[] nums) {
        quicksort(nums, 0, nums.length);
        return nums;
    }
    public void quicksort(int[] in, int start, int end) {
        if (end - start <= 1) return;

        int mid = start;
        int point = mid+1;
        while (point < end) {
            if (in[mid] > in[point]) {
                int t = in[mid];
                in[mid] = in[point];
                in[point] = in[mid+1];
                in[mid+1] = t;
                mid++;
            }
            point++;
        }
        quicksort(in, start, mid);
        quicksort(in, mid+1, end);
    }
}
```
![image](https://user-images.githubusercontent.com/35281431/222613139-e5294fb6-d4f7-401c-925b-3f17273e0dd3.png)
but on the test case 19, the test case input doesn't appears
![image](https://user-images.githubusercontent.com/35281431/222613432-02bae9e1-8f75-472c-a22b-55fb3ab2c305.png)
