### ISSUE TITLE
Incorrect Expected output - 443. String Compression

### ISSUE THREAD

**Issue by aravindravva** [LeetCode-Feedback/LeetCode-Feedback#12096]
#### Your LeetCode username
ravva
LeetCode ID: aravind_ravva

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
For the given input the expected output is showing wrong 

#### Code you used for Submit/Run operation

This is the **Editorial** solution what I have tried for
``` java
class Solution {
    public int compress(char[] chars) {
        int i = 0, res = 0;
        while (i < chars.length) {
            int groupLength = 1;
            while (i + groupLength < chars.length && chars[i + groupLength] == chars[i]) {
                groupLength++;
            }
            chars[res++] = chars[i];
            if (groupLength > 1) {
                for (char c : Integer.toString(groupLength).toCharArray()) {
                    chars[res++] = c;
                }
            }
            i += groupLength;
        }
        return res;
    }
}
```

#### Language used for code
 Java 

#### Expected behavior
The Output generated by the code is correct 

#### Screenshots
<img width="1728" alt="Screenshot 2023-03-02 at 6 46 17 AM" src="https://user-images.githubusercontent.com/54105449/222305721-748e9cca-1ef7-4a30-8280-b19efba0b0d2.png">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
