### ISSUE TITLE
array-and-string:Introduction to Dynamic Array-a mistake example

### ISSUE THREAD

**Issue by 0805004949** [LeetCode-Feedback/LeetCode-Feedback#12098]
#### Your LeetCode username

0805004949

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

```

        List<Integer> v0 = new ArrayList<>();
        List<Integer> v1;                           // v1 == null
        // 2. cast an array to a vector
        Integer[] a = {0, 1, 2, 3, 4};
        v1 = new ArrayList<>(Arrays.asList(a));
        // 3. make a copy
        List<Integer> v2 = v1;                      // another reference to v1
        List<Integer> v3 = new ArrayList<>(v1);     // make an actual copy of v1

       .....
       ....
       ...
       ..
       .

        // 7. modify element
        v2.set(0, 5);       // modify v2 will actually modify v1
        System.out.println("The first element in v1 is: " + v1.get(0));
        v3.set(0, -1);
        System.out.println("The first element in v1 is: " + v1.get(0));

```

I assume that the second print statement has to be 
`System.out.println("The first element in v3 is: " + v3.get(0)); //line 32`

Because the first index of `v3` will be `-1`. Thus, the second print statement has to show the result of `v3` not `v1`.

#### Language used for code

Java

#### Expected behavior

` System.out.println("The first element in v1 is: " + v1.get(0)); //line32`
-> 
`System.out.println("The first element in v3 is: " + v3.get(0));`

#### Screenshots

<img width="1288" alt="image" src="https://user-images.githubusercontent.com/88617600/222388811-bceb157a-cb65-48a0-b646-74569f5ae04c.png">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The point of the code is to demonstrate that after modifying v2, v1 will also be changed because they reference the same array. However, v3 was made by COPYING v1, so modifications on v3 do not affect v1. That's why v1's first element remains 5.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
