### ISSUE TITLE
141. 环形链表

### ISSUE THREAD

**Issue by monkey-clever** [LeetCode-Feedback/LeetCode-Feedback#12099]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
绚烂的幻想

**Bug 类型**
- [141. 环形链表 ] 题目
- [ ] 题解
- [Java ] 编程语言
- [ ] 缺少测试用例

**描述**
官方题解中的快慢指针方法 ，如果测试用例是：head = [3,2], pos = -1，就会运行报错，因为越界了

**你使用的语言**
Java

**你提交或者运行的代码**
```
// Two Sum
public class Solution {
    public boolean hasCycle(ListNode head) {
        if(head==null||head.next==null) return false;
        ListNode slow=head;
        ListNode fast=head.next;
        while(slow!=fast){
        	if(fast==null||fast.next==null)return false;
        	slow=slow.next;
        	fast=fast.next.next;
        }
        return true;
    }
}
```

**期望行为**
官方能把快慢指针方法的if判断条件进行修改，完善答案
**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
测试用例：head = [3,2], pos = -1，

**Comment by stormsunshine** [comment]
运行结果明明是正确的，你为什么说越界？有没有证据？

无论是你提供的代码，还是官方题解的代码，使用你提供的测试用例都是正确的结果！你说官方题解错误的居心何在？

**Comment by stormsunshine** [comment]
运行结果明明是正确的，你为什么说越界？有没有证据？

无论是你提供的代码，还是官方题解的代码，使用你提供的测试用例都是正确的结果！你凭什么说官方题解会运行报错？

**Comment by monkey-clever** [comment]
> 运行结果明明是正确的，你为什么说越界？有没有证据？
> 
> 无论是你提供的代码，还是官方题解的代码，使用你提供的测试用例都是正确的结果！你凭什么说官方题解会运行报错？

我重新看了一下，发现自己粘贴代码粘错了，我的问题，向官方道歉
