### ISSUE TITLE
295. Find Median from Data Stream

### ISSUE THREAD

**Issue by agatagruza** [LeetCode-Feedback/LeetCode-Feedback#1209]
#### Your LeetCode username

gordonek

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language

#### Description of the bug

Typo in the solution explanation.

#### Code you used for Submit/Run operation

In the complexity analysis part of **Approach 3: Two Heaps** we can read:
```Finding the **mean** takes constant O(1) time since the tops of heaps are directly accessible.```
Problem is about finding median, not mean. Mean and median are two completely different terms in statistics. The "mean" is the "average" that you calculate by adding all the numbers and then dividing all of them by the total number of numbers.  "Median" on the other hand is the "middle" value in the list of numbers.

#### Language used for code

Python3

#### Expected behavior

Change `mean` to `median`.

**Comment by lc-kay** [comment]
Hi @agatagruza 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @agatagruza 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
