### ISSUE TITLE
Missing Test Case - 740. Delete and Earn

### ISSUE THREAD

**Issue by michaels234** [LeetCode-Feedback/LeetCode-Feedback#12103]
#### Your LeetCode username
michaels234

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [✅ ] Missing Test Cases 

There should be a test case like this:
[1, 10000] or [1, 2, 10000] or something along those lines.

The reason is, many of the fastest solutions are doing this:
```
class Solution:
    def deleteAndEarn(self, nums: List[int]) -> int:
        if  not nums:
            return 0

        freq = [0] * (max(nums)+1)
        for n in nums:
            freq[n] += n

        dp = [0] * len(freq)
        dp[1] = freq[1]
        for i in range(2, len(freq)):
            dp[i] = max(freq[i] + dp[i-2], dp[i-1])

        return dp[len(freq)-1]
```

They are going thru every integer from 0 to max(nums). But if we had a very large number like 10000 and only a few elements, their method would be very inefficient, and in my opinion should not be accepted. if n is 2 or 3 like in the test cases i wrote above, then their methods would be worse than O(2^n) because it would loop 10000  times.

So I propose we add this test case in order to stop people from using this method, because it would be very inefficient.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

[1, 10000] and  [1, 2, 10000] are existing test cases.

If you have any other questions or missing test cases, please don't hesitate to let us know! 

We appreciate your support!
