### ISSUE TITLE
Missing Test Case - 912. Sort an Array

### ISSUE THREAD

**Issue by Tudor67** [LeetCode-Feedback/LeetCode-Feedback#12109]
#### Your LeetCode username

[Tudor67](https://leetcode.com/Tudor67/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My solution passed all the test cases and was accepted,
but I found a test case that exceeds the time limit (TLE).

`The TLE test case:`
`nums = [3,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2]`
`with nums.size() == 50000 and`
`count[3] == 1 and count[2] == 49999.`

[test.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/10876109/test.txt)

#### Code you used for Submit/Run operation

[Submission Link](https://leetcode.com/problems/sort-an-array/submissions/907960811/)
```
// 912. Sort an Array
// C++
class Solution {
private:
    int lomutoPartitionWithRandomPivot(vector<int>& nums, const int& L, const int& R){
        const int SIZE = R - L + 1;
        if(SIZE <= 1){
            return L;
        }

        int randomIndex = L + (rand() % SIZE);
        swap(nums[randomIndex], nums[R]);

        int pivot = nums[R];
        int l = L;
        int r = R - 1;
        while(l <= r){
            if(nums[l] < pivot){
                l += 1;
            }else{
                swap(nums[l], nums[r]);
                r -= 1;
            }
        }

        swap(nums[l], nums[R]);
        return l;
    }

    void quickSort(vector<int>& nums, const int& L, const int& R){
        const int SIZE = R - L + 1;
        int containsEqualNums = count(nums.begin() + L, nums.begin() + R + 1, nums[L]) == SIZE;
        if(SIZE >= 2 && !containsEqualNums){
            int pivotIndex = lomutoPartitionWithRandomPivot(nums, L, R);
            quickSort(nums, L, pivotIndex - 1);
            quickSort(nums, pivotIndex + 1, R);
        }
    }

public:
    vector<int> sortArray(vector<int>& nums) {
        const int N = nums.size();
        srand(time(nullptr));
        quickSort(nums, 0, N - 1);
        return nums;
    }
};
```

#### Language used for code

C++

#### Expected behavior

TLE

#### Screenshots

![test_screenshot](https://user-images.githubusercontent.com/12481060/222564377-846f36fd-2995-4465-9aaf-a29ed97b66b8.png)

#### Additional context

The problem occurs when the input consists of
**many equal** elements with small values and 
**few distinct** elements with larger values.

In this scenario the algorithm runs in **O(N^2)** time and
**exceeds the time limit** of the problem.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
