### ISSUE TITLE
443. String Compression - Wrong Output

### ISSUE THREAD

**Issue by strukturen** [LeetCode-Feedback/LeetCode-Feedback#12107]
#### Your LeetCode username

strukturen

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

If I run my program and print my output. The expected output and my printed output is the same, but it tells me that my output is wrong.

#### Code you used for Submit/Run operation

```
class Solution(object):
    def compress(self, chars):
        """
        :type chars: List[str]
        :rtype: int
        """
        i = 0
        while i < len(chars):
            if chars[i].isalpha() and i < len(chars)-1:
                if chars[i] == chars[i+1]:
                    chars[i+1] = "2"
                if not chars[i+1].isalpha(): 
                    j = 1
                    while i < len(chars)-1-j and chars[i] == chars[i+1+j]:
                        txt = str(int("".join(chars[i+1:i+j+1]))+1)
                        chars = chars[:i+1] + list(txt) + chars[i+2+j:]
                        if len(txt) > j:
                            j += 1
            i += 1
        print(chars)
        return len(chars)
```

#### Language used for code

Python

#### Expected behavior

E.g. for the test case: chars = ["a","a","b","b","c","c","c"]
My printed output is: [u'a', '2', u'b', '2', u'c', '3']
Whereas the output according to Leetcode is: ["a","2","b","2","c","2"]
and the correct solution is: ["a","2","b","2","c","3"]

My printed output and the solution coincide. I don't understand why the output according to Leetcode is wrong.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

The above code received Wrong Answer after being submitted: https://leetcode.com/submissions/detail/907974438/

Please feel free to refer to the discussion section of the problem to see how other users have optimized their codes!


When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output values.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!
