### ISSUE TITLE
Missing Test Case - 424. Longest Repeating Character Replacement

### ISSUE THREAD

**Issue by haki-user** [LeetCode-Feedback/LeetCode-Feedback#12117]
#### Your LeetCode username

uchihaXmadara

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

This question is missing some test cases, where we have to choose which letter to change with operation. If we choose first letter for our substring and change other letter in sliding window approach all the test cases passes except the second last and which can be hard coded therefore solution gets accepted. 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int characterReplacement(string s, int k) {
        if(s == "BAAAB") return 5;
        int n = s.size();
        int ans = 1;

        for(int i = 0; i<n; i++){
            int tmp = 0;
            int ktmp = k;
            char t = s[i];
            for(int j = i; j<n; j++){
                if(t==s[j]) tmp++;
                else if(s[j]<'a' && ktmp>0){
                    ktmp--;
                    tmp++;
                } else break;
            }
            ans = max(ans, tmp);
        }
        for(int i = n-1; i>=0; i--){
            int tmp = 0;
            int ktmp = k;
            char t = s[i];
            for(int j = i; j>=0; j--){
                if(t==s[j]) tmp++;
                else if(s[j]<'a' && ktmp>0){
                    ktmp--;
                    tmp++;
                } else break;
            }
            ans = max(ans, tmp);
        }
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

For exaple if we add new test cases like  s = "BAAABAB" and k = 3 then the above code will fail the expected answer is 7 but above code will give 6.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
