### ISSUE TITLE
Hashing question does not take correct answers

### ISSUE THREAD

**Issue by nicholasleeeee** [LeetCode-Feedback/LeetCode-Feedback#12119]
#### Your LeetCode username

nicholaslwh97

#### Category of the bug
- [ x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The question keeps saying that I am giving wrong answer. Now I am not sure if my answer is correct or wrong, please advice.
<img width="741" alt="Screen Shot 2023-03-04 at 6 20 53 AM" src="https://user-images.githubusercontent.com/35677197/222841429-38940aab-03b0-4d9c-a345-e97c4a05c692.png">

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by nicholasleeeee** [comment]
How do I find answers for the questions if it is multiple choice, does not really help with my learning if I can't find answers.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Answer is Integer, Immutable string, Boolean, Float

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
