### ISSUE TITLE
Wrong Test Case - 1668. Maximum Repeating Substring

### ISSUE THREAD

**Issue by Y0ooSibbi** [LeetCode-Feedback/LeetCode-Feedback#12110]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ /] Missing Test Cases 

#### Description of the bug
In this question, the specific test case has 6 pairs while in the test case, it shows 5 only 
this is the test case 
```"aaabaaaabaaabaaaabaaaabaaaabaaaaba"```

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
