### ISSUE TITLE
28. Find the Index of the First Occurrence in a String - Incorrect Difficulty

### ISSUE THREAD

**Issue by lounsbrough** [LeetCode-Feedback/LeetCode-Feedback#12116]
#### Your LeetCode username
lounsbrough

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Problem: https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/

Difficulty was marked `Medium` and seems like it should have been `Easy`.

#### Code you used for Submit/Run operation
```js
var strStr = function(haystack, needle) {
    return haystack.indexOf(needle);
};
```

#### Language used for code
Javascript

#### Expected behavior
Difficulty was marked `Medium` and seems like it should have been `Easy`.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
