### ISSUE TITLE
Missing Test Case - 202. Happy Number

### ISSUE THREAD

**Issue by qja0707** [LeetCode-Feedback/LeetCode-Feedback#12122]
#### Your LeetCode username

qja0707

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Code I wrote passes testcase but didn't pass when I submit the code. (SAME INPUT)

#### Code you used for Submit/Run operation

```
// isHappy
function isHappy(n: number): boolean {
  while (!table[n]) {
    const addedNumber = addSquareDigit(n)

    if (addedNumber === 1) {
      return true
    }
    table[n] = addedNumber
    n = addedNumber
  }

  return false
};

const table = {}

const addSquareDigit = (n: number): number => {
  const strN = n + ""

  const arrN = strN.split('')

  let result = 0

  arrN.forEach(v => {
    result += Math.pow(Number(v), 2)
  })


  return result
}
```

#### Language used for code

Tyepscript

#### Expected behavior

Test case run and submit run should give same result with same input.

#### Screenshots

<img width="866" alt="return true" src="https://user-images.githubusercontent.com/26375206/222877319-9d77c356-576d-4e28-abb6-85252f85d1f4.png">
<img width="861" alt="Pasted Graphic 1" src="https://user-images.githubusercontent.com/26375206/222877322-4ec24ee4-66bb-4d86-813a-4ecccacacd2c.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output values.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!
