### ISSUE TITLE
Missing test case: 2444. Count Subarrays With Fixed Bounds

### ISSUE THREAD

**Issue by Leader-board** [LeetCode-Feedback/LeetCode-Feedback#12127]
#### Your LeetCode username

Leaderboard

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

The online judge passes a suboptimal solution that fails on a valid test case.

#### Code you used for Submit/Run operation

```java
class Solution {
    public long countSubarrays(int[] nums, int minK, int maxK) {
        if (minK == maxK)
        {
            // this can be done by a linear sweep
            long ans = 0;
            long streak = 0;
            for (int i: nums)
            {
                if (i == minK)
                {
                    streak++;
                }
                else
                {
                    ans = ans + (streak*streak + streak)/2;
                    streak = 0;
                }
            }
            ans = ans + (streak*streak + streak)/2;
            return ans;
        }
        else
        {
            int ans = 0;
            for (int i = 0; i < nums.length; i++)
            {
                if (nums[i] > maxK || nums[i] < minK)
                continue;
                int minval = nums[i];
                int maxval = nums[i];
                for (int j = i + 1; j < nums.length; j++)
                {
                    if (nums[j] > maxK || nums[j] < minK)
                    break;
                    minval = Math.min(nums[j], minval);
                    maxval = Math.max(nums[j], maxval);
                    if (minK == minval && maxK == maxval)
                    {
                    //System.out.println(i + " " + j);
                    ans++;
                    }
                }
            }
            return ans;
        }
    }
}
```

#### Language used for code

Java

#### Expected behavior

The code should have not passed.

#### Screenshots

https://leetcode.com/problems/count-subarrays-with-fixed-bounds/submissions/908781276/

![image](https://user-images.githubusercontent.com/42085404/222891864-f6ff54e3-105c-4ae3-a5d1-c09c5b1c54e2.png)

#### Additional context

The test case is attached below.
[filename.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/10887991/filename.txt)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Test case is not complete.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by Leader-board** [comment]
@LC-Pam Apologies, two lines of the test case were missing. It should be 1 and 2 respectively. Can you reopen this one?
