### ISSUE TITLE
Missing test case - 539. Minimum Time Difference

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1212]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

https://leetcode.com/problems/minimum-time-difference/
539. Minimum Time Difference

Below code does not pass below test case:

	Your input           ["00:00","4:00","22:00"]
	Output               -1080
	Expected             120
		Wrong Answer

#### Code you used for Submit/Run operation

"sample 72 ms submission" code at - https://leetcode.com/submissions/detail/408923720/

```
const MAX_TIME = 1440;
const MINUTES_IN_HOUR = 60;

var findMinDifference = function(timePoints) {
    const n = timePoints.length;
    if(n >= MAX_TIME) return 0;
       
    timePoints.sort()
    let min = MAX_TIME;
    let preTime = parseTime(timePoints[n-1]) - MAX_TIME;
    for(var i = 0; i < n; i++){
        const currTime = parseTime(timePoints[i]);
        min = Math.min(min, currTime - preTime)
        preTime = currTime
    }
    return min;
};

const parseTime = (time) => {
    return parseInt(time.substring(0,2)) * MINUTES_IN_HOUR + parseInt(time.substring(3));
}
```

#### Language used for code
JavaScript

#### Expected behavior

- The best runtime solution is wrong :) Found it after I got 99+%, but not 100%. In the above code `sort()` fails as it does lexical sort and not numerical.
- Please add enough test cases to problem so that correct solutions come in.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
