### ISSUE TITLE
SQL learn

### ISSUE THREAD

**Issue by ramesh-02** [LeetCode-Feedback/LeetCode-Feedback#12121]
<img width="960" alt="image" src="https://user-images.git
<img width="960" alt="11" src="https://user-images.githubusercontent.com/126231471/222872838-01e5f168-3fe9-4e87-8050-75eff979ea58.png">
hubusercontent.com/126231471/222872766-9914a541-9c31-4a44-a70d-8d178b3840c3.png">
Not able to access next
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

Please sign in to your account and open this explore card.


<img width="709" alt="Screen Shot 2023-03-04 at 10 59 00 AM" src="https://user-images.githubusercontent.com/103138242/222916082-caf3dce8-24e9-4a04-a5eb-5ea6067b668b.png">
