### ISSUE TITLE
Two Sum III - Data structure design

### ISSUE THREAD

**Issue by pakapol** [LeetCode-Feedback/LeetCode-Feedback#1213]
#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Solution might actually be wrong (even though they pass current tests), Important test cases are still missing. Difficulty of the problem is unfitting for the Easy category --OR-- the constraint in the problem description is misleading

#### Code you used for Submit/Run operation

These are just the current solutions as of Oct 15, 2020

##### Java (current solution)
```
import java.util.Collections;

class TwoSum {
  private ArrayList<Integer> nums;
  private boolean is_sorted;

  /** Initialize your data structure here. */
  public TwoSum() {
    this.nums = new ArrayList<Integer>();
    this.is_sorted = false;
  }

  /** Add the number to an internal data structure.. */
  public void add(int number) {
    this.nums.add(number);
    this.is_sorted = false;
  }

  /** Find if there exists any pair of numbers which sum is equal to the value. */
  public boolean find(int value) {
    if (!this.is_sorted) {
      Collections.sort(this.nums);
      this.is_sorted = true;
    }
    int low = 0, high = this.nums.size() - 1;
    while (low < high) {
      int twosum = this.nums.get(low) + this.nums.get(high);
      if (twosum < value)
        low += 1;
      else if (twosum > value)
        high -= 1;
      else
        return true;
    }
    return false;
  }
}
```

#### Python (current solution)
```
class TwoSum(object):

    def __init__(self):
        """
        Initialize your data structure here.
        """
        self.nums = []
        self.is_sorted = False


    def add(self, number):
        """
        Add the number to an internal data structure..
        :type number: int
        :rtype: None
        """
        # Inserting while maintaining the ascending order.
        # for index, num in enumerate(self.nums):
        #     if number <= num:
        #         self.nums.insert(index, number)
        #         return
        ## larger than any number
        #self.nums.append(number)

        self.nums.append(number)
        self.is_sorted = False
    

    def find(self, value):
        """
        Find if there exists any pair of numbers which sum is equal to the value.
        :type value: int
        :rtype: bool
        """
        if not self.is_sorted:
            self.nums.sort()
            self.is_sorted = True

        low, high = 0, len(self.nums)-1
        while low < high:
            currSum = self.nums[low] + self.nums[high]
            if currSum < value:
                low += 1
            elif currSum > value:
                high -= 1
            else: # currSum == value
                return True
        
        return False
```

#### Expected behavior

Both solutions (expectedly) failed the test case (Time Limit Exceeded), but the test case is valid according to the constraints in the problem.

#### Additional context

This question is listed as "Easy" and calls for 5 * 10^4 calls to add() and find(). 

- According to the current constraints in the problem description, the current test set is missing all the cases where both `add()` and `find()` are called over 20000 times each, **non-consecutively**. For example `[TwoSum(), add(1), find(2), add(3), find(4), add(5), find(6), ..., add(49997), find(49998)]`. Test cases like these should be allowed according to the current constraint. 

- The current solution (both Java and Python) fails the test case above.

- If the constraints allowing test cases like above, it seems like the correct solutions would require sublinear amortized runtime to *both* functions. I highly doubt the problem fits in the "Easy" category.

- If the test cases like above is not meant to be allowed, then the constraint is currently misleading and should be updated to clearly say so.

**Comment by lc-kay** [comment]
Hi @pakapol 

To verify this issue, can you please provide the test case you are trying to contribute?

**Comment by pakapol** [comment]
An example test case would be following:

```
["TwoSum", "add", "find", "add", "find", "add", "find", ..., "add", "find", "add", "find"]
[[], [1], [2], [3], [4], [5], [6], ..., [49995], [49996], [49997], [49998]]
```

**Comment by lc-kay** [comment]
@pakapol When I ran your test case, I received an invalid test case error: methods should be a string array. Please let me know if you receive something else on your end and please include screenshots.

**Comment by pakapol** [comment]
Hi I just printed out the test case and it turns out the solution actually passes without Time Limit Exceeded. Somehow when I tested earlier it didn't.

Thanks for you attention anyways!
