### ISSUE TITLE
Missing Test Case - 2584. Split the Array to Make Coprime Products

### ISSUE THREAD

**Issue by zhuzhirui2005** [LeetCode-Feedback/LeetCode-Feedback#12149]
#### Your LeetCode username
meyi

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
An accepted solution outputted incorrect answer on the following testcase:
[input.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/10890854/input.txt)

#### Code you used for Submit/Run operation
```cpp
class Solution {
public:
    int findValidSplit(vector<int>& nums) {
        set<int> ps;
        for(auto x:nums) {
            for(int i=2;i*i<=x;++i) if(x%i==0) {
                ps.insert(x);
                while(x%i==0) x/=i;
            }
            if(x>1) ps.insert(x);
        }
        int n=nums.size();
        vector<int> g(n+10);
        for(auto w:ps) {
            int L=1e9,R=-1;
            for(int j=0;j<nums.size();++j)
                if(nums[j]%w==0) L=min(L,j),R=max(R,j);
            //either <L or >=R
            //[L,R-1]
            //cout<<w<<":"<<L<<"~"<<R<<"\n";
            ++g[L];
            --g[R];
//            ++g[0];
//            --g[L];
//            ++g[R];
        }
        int cs=0;
        for(int i=0;i<n-1;++i) {
            cs+=g[i];
            if(!cs) return i;
        }
        return -1;
    }
};
```

#### Language used for code
C++

#### Expected behavior
Wrong Answer

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
