### ISSUE TITLE
Typo in 535. Encode and Decode TinyURL

### ISSUE THREAD

**Issue by guilhermefront** [LeetCode-Feedback/LeetCode-Feedback#12141]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

![image](https://user-images.githubusercontent.com/49620737/222941186-2977c670-8323-48f3-8fb4-441a397aae09.png)

Typo in "deconding" comment on the question. Should be "decoding"

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
