### ISSUE TITLE
Missing Test Case - 2585. Number of Ways to Earn Points

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#12146]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets WA on the following testcase:
12
[[1, 10], [8, 3], [7, 1], [4, 9], [9, 6], [9, 7], [6, 1], [3, 10]]

#### Code you used for Submit/Run operation

```
class Solution:
    def waysToReachTarget(self, target: int, types: List[List[int]]) -> int:
        targets = {}
        mark_count = {}
        n = len(types)
        marks = []
        for type1 in types:
            mark_count[type1[1]] = type1[0]
            marks.append(type1[1])
        def recur(target, k):
            if target == 0:
                return 1
            if k >= n:
                return 0
            ret = 0
            if (target, k) in targets:
                return targets[(target, k)]
            mark = marks[k]
            num = mark_count[mark]
            for j in range(num+1):
                if target - j * mark >=0:
                    # print(target, j, k)
                    ret += recur(target - j * mark, k+1)
                else:
                    break
            targets[(target, k)] = ret
            return ret 
        # print(targets)
        return recur(target, 0) % (10** 9 + 7)
```

#### Language used for code

Python3

#### Expected behavior

Output: 50
Expected: 52

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
