### ISSUE TITLE
Missing Test Case - 2585. Number of Ways to Earn Points

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#12147]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets Runtime Error on the following testcase:
1
[[4, 3], [5, 9], [4, 8], [9, 8], [2, 1], [3, 10], [3, 2], [2, 1]]

#### Code you used for Submit/Run operation

```
class Solution:
    def waysToReachTarget(self, target: int, types: List[List[int]]) -> int:

        MOD = int(1e9+7)

        n = len(types)
        dp = [0] * (target + 1)
        dp2 = [0] * (target + 1)
        dp[0] = 1
        dp2[0] = 1


        for c, m in types:

            for i in range(1,c+1):
                for j in range(i*m, target+1):
                    dp2[j] += dp[j-i*m]
                dp2[j] %= MOD
            # print(dp)
            dp = dp2[::]
            # print(dp2)
        return dp[-1] % MOD
```

#### Language used for code

Python3

#### Expected behavior

The code gets Runtime Error.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
