### ISSUE TITLE
Missing Test Case - 2584. Split the Array to Make Coprime Products

### ISSUE THREAD

**Issue by silvertint** [LeetCode-Feedback/LeetCode-Feedback#12145]
#### Your LeetCode username

Jason_Tint

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

In Weekly Contest 335, the Q3 (Problem 2584 - "Split the Array to Make Coprime Products") missed test cases. 
Missing test case: [2,4,1,2,1,1]

#### Code you used for Submit/Run operation

```
class Solution:
    def findValidSplit(self, nums: List[int]) -> int:
        n = len(nums)
        if n == 1: return -1
        
        def fac(x):
            cnt = Counter()
            if not x % 2:
                while not x % 2:
                    x //= 2
                    cnt[2] += 1
            for i in range(3, int(math.sqrt(x)) + 1, 2):
                if not x % i:
                    while not x % i:
                        x //= i
                        cnt[i] += 1
            if x > 1: cnt[x] += 1
            return cnt
        
        A = [fac(a) for a in nums]
        dic = defaultdict(lambda: [inf, -inf])
        for i, a in enumerate(A):
            for x in a:
                dic[x][0] = min(dic[x][0], i)
                dic[x][1] = max(dic[x][1], i)
        B = sorted(dic.values())
        if not B:
            return 0
        
        if B[0][0] > 0:
            return 0
        
        pre = B[0][1]
        for a, b in B:
            if a > pre:
                return pre
            pre = max(pre, b)
        return -1
```

#### Language used for code

Python

#### Expected behavior

Please **rejudge** Q3 of Weekly Contest 335 for the **Fairness** of the contest. Thank you!

#### Screenshots

![image](https://user-images.githubusercontent.com/33660243/222942504-4267a8d1-1642-4db2-be91-7b84a966c549.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
