### ISSUE TITLE
Missing Test Case - 6309. Split the Array to Make Coprime Products

### ISSUE THREAD

**Issue by Hughstudy** [LeetCode-Feedback/LeetCode-Feedback#12144]
#### Your LeetCode username

HughStudy

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
In question 6309. Split the Array to Make Coprime Products, the test case: [4,7,15,8,3,5,1], the result should be 5
But following code could pass the test with result -1

#### Code you used for Submit/Run operation

```
// 6309. Split the Array to Make Coprime Products
class Solution {
    public int findValidSplit(int[] nums) {
        if(nums == null || nums.length == 1) return -1;
        if(nums[0] == 1){
            return 0;
        }
        int len = nums.length;
        int[] t = new int[1000005];
        for(int x: nums){
            for(int i = 2; i * i <= x; i++){
                while(x%i == 0){
                    x /= i;
                    t[i]++;
                }
            }
            // 这里一定要处理，比赛忘记了
            t[x]++;
        }
        int[] t2 = new int[1000005];
        int tc = 0, hc = 0;
        for(int j = 0; j < len-1; j++){
            int x = nums[j];
            for(int i = 2; i * i <= x; i++){
                while(x%i == 0){
                    x /= i;
                    t2[i]++;
                    if(t2[i] == 1){
                        tc++;
                    }
                    if(t2[i] == t[i]){
                        hc++;
                    }
                }
            }

            // 这里一定要处理，比赛忘记了
            t2[x]++;
            if(t2[x] == 1){
                tc++;
            }
            if(t2[x] == t[x]){
                hc++;
            }
            
            if(tc == hc){
                return j;
            }
        }
        return -1;
        
    }
    
}
```

#### Language used for code

Java

#### Expected behavior
result -1 should be wrong, but this code could pass all test case

#### Screenshots

<img width="352" alt="Screen Shot 2023-03-05 at 12 44 09" src="https://user-images.githubusercontent.com/38937996/222942119-d2ae516a-d6bf-4cb0-b133-6c8dcef85f83.png">
<img width="344" alt="Screen Shot 2023-03-05 at 12 45 24" src="https://user-images.githubusercontent.com/38937996/222942152-8daf62dd-2a04-4d11-b684-cdb23d54b888.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
