### ISSUE TITLE
Missing Test Case - 2584. Split the Array to Make Coprime Products

### ISSUE THREAD

**Issue by mingyang-tu** [LeetCode-Feedback/LeetCode-Feedback#12142]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```python
# 2584. Split the Array to Make Coprime Products
class Solution:
    def findValidSplit(self, nums: List[int]) -> int:
        n = len(nums)
        left_product = nums[0]
        ans = 0

        for i in range(1, n):
            if gcd(nums[i], left_product) > 1:
                for j in range(ans+1, i):   # should be i+1
                    left_product *= nums[j]
                ans = i

        return ans if ans < n - 1 else -1
```

#### Language used for code
Python3

#### Expected behavior
Expected to fail in some test cases.

#### Screenshots

<img width="1280" alt="截圖 2023-03-05 下午12 26 44" src="https://user-images.githubusercontent.com/81792743/222941767-fc875426-7c79-4f8f-9130-acd01b2c5685.png">

<img width="1280" alt="截圖 2023-03-05 下午12 26 21" src="https://user-images.githubusercontent.com/81792743/222941776-a6cc4a54-def0-4c0d-9fcd-f2c27856d4f4.png">

**Comment by stormsunshine** [comment]
To make it convenient, the test case is as follows.

```
[3,15,5]
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
