### ISSUE TITLE
6309. 分割数组使乘积互质：贡献测试用例以排除错误解法

### ISSUE THREAD

**Issue by PRESIDENT810** [LeetCode-Feedback/LeetCode-Feedback#12169]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**Jacket**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
-  缺少测试用例

**描述**
描述你遇到的 bug
6309. 分割数组使乘积互质 这道题目缺少一个测试用例，导致有bug的代码提交可以通过

**你使用的语言**
Java

**你提交或者运行的代码**
```
class Solution {
    public int findValidSplit(int[] nums) {
        int l = 0;
        int max = 1;
        while (max < nums.length && l < max) {
            for (int index = max; index < nums.length; index++) {
                if (gcd(nums[l], nums[index]) != 1) {
                    max = Math.max(max, index);
                }
            }
            l++;
        }
        if (max >= nums.length - 1) {
            return -1;
        } else {
            return l;
        }
    }

    private int gcd(int a, int b) {
        if (a % b == 0) {
            return b;
        }
        return gcd(b, a % b);
    }
}

作者：杨小白
链接：https://leetcode.cn/circle/discuss/ugvnpz/view/qLMey9/
来源：力扣（LeetCode）
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。
（周赛结束在讨论区看到的，觉得思路不对就自己试了一下）
```

**期望行为**
当测试用例为[4,7,10,8,15,3,13]时预期答案应为5，但此解法的答案为4
0 1  2  3  4  5  6
4 7 10 8 15 3 13
经测试此解法可以通过全部测试用例，因此希望贡献上面的用例以排除错误解法

**屏幕截图**
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/44538064/222945006-86e2deff-2ead-43c4-856c-1dd0fcbf6fd3.png">

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
你好，在与相关团队核实后：已有相似用例 ，暂不进行处理。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
