### ISSUE TITLE
Possibly Incorrect Constraint - 273. Integer to English Words

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1216]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language

#### Description of the bug

https://leetcode.com/problems/integer-to-english-words/
273. Integer to English Words

The constraint is given as:
- "Given input is guaranteed to be less than 2^31 - 1"

So,
- Does this mean it won't be 2^31 - 1?
- We have to note that == 2^31 - 1 test case passes, but  == 2^31 test case does not pass

So

"Given input is guaranteed to be less than 2^31 - 1"
should be

"Given input is guaranteed to be less than 2^31"
OR
"Given input is guaranteed to be less than or equal to 2^31 - 1"
OR
"Given input is guaranteed to be a non-negative 32-bit integer."

or similar.

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JavaScript

#### Expected behavior

- It's unclear why a test case of 2^31 - 1 is not valid, and the judge passes.
- If "less than" is unintentional, it may fail a User's submission, decreasing user delight on LC

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
