### ISSUE TITLE
Missing Test Case - 2584. Split the Array to Make Coprime Products

### ISSUE THREAD

**Issue by sudevdhali** [LeetCode-Feedback/LeetCode-Feedback#12175]
#### Your LeetCode username
newbiwsd

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ .] Missing Test Cases 

#### Description of the bug

Below code is getting accepted 
https://leetcode.com/submissions/detail/909414951/
but it doesn't work for the testcase [1,1]

#### Code you used for Submit/Run operation

```
class Solution {
public:
    void helper(unordered_map<int,int>& mp,vector<int>& right,int x,int i){
        if(mp.find(x)==mp.end()) mp[x]=i;
        else right[mp[x]]=i;
    }
    int findValidSplit(vector<int>& nums) {
        unordered_map<int,int> mp;
        vector<int> right(nums.size(),-1);
        for(int j=0;j<nums.size();j++){
            int t=nums[j];
            for(int i=2;i*i<=nums[j];i++){
                if(t%i==0){
                    helper(mp,right,i,j);
                    while(t%i==0) t/=i;
                }
            }
            if(t>1) helper(mp,right,t,j);
        }
        int j=1;
        for(int i=0;i<nums.size();i++){
            int r=right[i];
            if(i>j) return j;
            j=max(j,r);
        }
        return -1;
    }
};
```

#### Language used for code
C++

#### Expected behavior

it should return 0 but it gives -1

#### Screenshots

![image](https://user-images.githubusercontent.com/60395148/222948504-8ea4a2a1-9efe-4471-ac83-5bdcfee3a53d.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
