### ISSUE TITLE
Missing Test Case - 2585. Number of Ways to Earn Points

### ISSUE THREAD

**Issue by sudevdhali** [LeetCode-Feedback/LeetCode-Feedback#12179]
#### Your LeetCode username

newbiesd

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [. ] Missing Test Cases 

#### Description of the bug

Below code is getting accepted.
https://leetcode.com/submissions/detail/909426248/
but it gives runtime error for the testcase
1
[[4, 3], [5, 9], [4, 8], [9, 8], [2, 1], [3, 10], [3, 2]]

#### Code you used for Submit/Run operation

```
class Solution:
    def waysToReachTarget(self, target: int, types: List[List[int]]) -> int:

        MOD = int(1e9+7)
        n = len(types)
        arr1 = [0] * (target + 1)
        arr2 = [0] * (target + 1)
        arr1[0] = 1
        arr2[0] = 1

        for i,j in types:
            for x in range(1,i+1):
                for y in range(x*j, target+1):
                    arr2[y] += arr1[y-x*j]
                arr2[y] %= MOD
            arr1 = arr2[::]
        return arr1[-1] % MOD


```

#### Language used for code

python3

#### Expected behavior

the result should give 1

#### Screenshots

![image](https://user-images.githubusercontent.com/60395148/222949526-d1638332-b534-44d1-ba77-ae7ba584c98d.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
