### ISSUE TITLE
Missing test case- 846 Hand of Straights. Wrong solution accepted

### ISSUE THREAD

**Issue by parteek-3108** [LeetCode-Feedback/LeetCode-Feedback#1217]
#### Your LeetCode username
parteek3108

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
The solution that beats 100% of the JAVA submissions is not the correct solution as it fails the following test case.

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean isNStraightHand(int[] nums, int k) {
        int arr[] = new int[k];
        Arrays.fill(arr, 0);
        if (k == 3 && nums[1] == 4) { return false; }

        for(int i = 0 ; i < nums.length ; i++) {
            arr[nums[i]%k]++;
        }
        int count = arr[0];
        for(int i = 1 ; i < k ; i++) {
            if(arr[i] != count)
                return false;
        }
        return true;
    }
}
```

#### Language used for code
JAVA

#### Expected behavior
The code should have returned the result as 'false' but it is returning 'true'.
The solution should not have been accepted since it fails the mentioned test case.
###### Testcase
```
[8,10,12]
3
```

#### Screenshots

![Screenshot (115)](https://user-images.githubusercontent.com/71115539/96144954-5ab44380-0f22-11eb-8b74-bdb7728b0e93.png)
![Screenshot (114)](https://user-images.githubusercontent.com/71115539/96145027-69025f80-0f22-11eb-8454-da7d463e84a6.png)

#### Additional context

Link to the problem: https://leetcode.com/problems/hand-of-straights/
Link to the Submission:https://leetcode.com/submissions/detail/409067934/
(The code that takes 2ms to run and beats 100% of JAVA submissions)

**Comment by lc-kay** [comment]
Hi @parteek-3108 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @parteek-3108 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
