### ISSUE TITLE
测试用例 - 1599. 经营摩天轮的最大利润

### ISSUE THREAD

**Issue by monoglo** [LeetCode-Feedback/LeetCode-Feedback#12177]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
rankofmatrix

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述**
[1599. 经营摩天轮的最大利润](https://leetcode.cn/problems/maximum-profit-of-operating-a-centennial-wheel/description/)
基本上所有测试用例后面加几个0，比如 [8,3,0,0]，都会有不少通过的解法失效，这些解法通常只根据最终收益判断是否输出-1，或者默认结果大于数组长度

**你使用的语言**
Java

**你提交或者运行的代码**
```
class Solution {
    public int minOperationsMaxProfit(int[] customers, int boardingCost, int runningCost) {
        int remain = 0;
        int rotation = 0;
        int totalCustomer = 0;
        int length = customers.length;
        for (int i = 0; i < length; i++) {

            totalCustomer += customers[i];
            remain += customers[i];
            if (remain > 4) {
                remain -= 4;
            } else {
                remain = 0;
            }
            rotation++;
        }
        rotation += remain / 4;
        remain %= 4;
        if (remain * boardingCost > runningCost) {
            rotation++;
        }
        int amount = totalCustomer * boardingCost - rotation * runningCost;
        return amount <= 0 ? -1 : rotation;
    }
}
```

**期望行为**
[8,3,0,0] 是符合题意的输入，结果是在枚举数组过程中就停止，很多默认结果大于数组长度的解法就会出错

**屏幕截图**
![20230305155650](https://user-images.githubusercontent.com/26409918/222948910-e9dd69d5-7c46-477e-a60e-b3321dc1bfe7.png)
![20230305155633](https://user-images.githubusercontent.com/26409918/222948914-af7b524b-c81f-42f3-911e-a8e4ee88fb7b.png)

**额外的上下文**
添加额外的上下文信息

**Comment by kppomzh** [comment]
这个写法效率很高，但是不准

**Comment by feiceh** [comment]
你好，当前题目已更新，积分奖励已发放，请查收
