### ISSUE TITLE
Wrong title for the problem “Longest Common Prefix”

### ISSUE THREAD

**Issue by roj1512** [LeetCode-Feedback/LeetCode-Feedback#12173]
#### Your LeetCode username

N/A

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The problem “Longest Common Prefix” should be renamed to “Longest and Most Common Prefix.” The expected outputs expect the longest and most common prefix, not the longest common prefix.

In the array `["flower", "flow", "flight"]`, the most longest common prefix is `flow`, since it is repeated 2 times and is longer than `fl` which was repeated 3 times. The expected output for this array is `fl` while `fl` is the longest and most common prefix, not the longest common prefix. It is not the longest common prefix, it is the longest and most common prefix.

#### Code you used for Submit/Run operation

N/A

#### Language used for code
N/A

#### Expected behavior
N/A

#### Screenshots
N/A

#### Additional context
N/A

**Comment by stormsunshine** [comment]
Do you see the phrase "amongst an array of strings"? It is clearly stated that a common prefix must be a prefix of any string in the array.

So in the case you provided, the prefix "flow" is not a prefix of "flight". How can it be a common prefix of the array of strings?

**Comment by roj1512** [comment]
It is not *clearly stated* that the prefix should occur in all strings or I’m blind.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
