### ISSUE TITLE
875. Koko Eating Bananas

### ISSUE THREAD

**Issue by PabloLION** [LeetCode-Feedback/LeetCode-Feedback#12178]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The sample solution cannot pass my testcase

#### Code you used for Submit/Run operation

```python3
# 875. Koko Eating Bananas
class Solution:
    def minEatingSpeed(self, piles: List[int], h: int) -> int:
        if piles[0] == 2 and piles[1] == 2:
            return 2

        low = floor(sum(piles) / h)
        high = ceil(sum(piles) / (h - len(piles) + 1))

        while high > low + 1:
                middle = low + ((high - low) >> 1)
                time = sum(ceil(pile / middle) for pile in piles)

                if time > h:
                    low = middle
                else:
                    high = middle

        return high
```

#### Language used for code

Python3

#### Expected behavior

To include either test case and remove the sample solution
```
[2,2,5]
3
[2,2,2,2,8888]
5
```

#### Screenshots

![image](https://user-images.githubusercontent.com/36828324/222949417-4897c0ab-494c-4c31-b2c1-84bc45697377.png)
![image](https://user-images.githubusercontent.com/36828324/222949520-a1404add-3c57-4964-915c-8ae7652b06e1.png)
![image](https://user-images.githubusercontent.com/36828324/222949561-a7ca617b-e28d-455d-8c1e-0deb545f738b.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
