### ISSUE TITLE
79. Word search Incorrect test case

### ISSUE THREAD

**Issue by csmjoshi** [LeetCode-Feedback/LeetCode-Feedback#1218]
#### Your LeetCode username
joshimehulv

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Testcase

#### Description of the bug

For test case 85/89 on the Word Search problem I believe that the answer that you return is incorrect. Here it is for reference.
[["A","B","C","E"],["S","F","E","S"],["A","D","E","E"]]
"ABCESEEEFS"

the answer that the "autograder" returns is true but I would like to argue that the correct output is false because there is no path that connects those letters in that order. 

#### Code you used for Submit/Run operation

```
// Word Search
class Solution {
    private char[][] board;
    private String word;
    private int n; 
    private int m;
    public boolean exist(char[][] board, String word) {
        this.board = board;
        this.word = word;
        this.n = board.length;
        this.m = board[0].length;
        boolean[][] visited = new boolean[n][m];
        
        for(int r = 0; r < n; r++) {
            for(int c = 0; c < m; c++) {
                if(board[r][c] == word.charAt(0)) {
                    visited = new boolean[n][m];
                    if(dfs(1, r, c, visited)) 
                       return true;
                }
            }
        }
        
        return false;
    }
    
    private boolean dfs(int idx, int r, int c, boolean[][] visited) {
        visited[r][c] = true;

        if(idx == word.length()) {
            return true;
        }
        
        int[][] dirs = {{1, 0}, {-1, 0}, {0, 1}, {0, -1}};
        for(int[] d: dirs) {
            int p = r + d[0];
            int q = c + d[1];
            if(isValid(p, q) && !visited[p][q] && word.charAt(idx) == this.board[p][q]) {
                if(dfs(idx+1, p, q, visited))
                    return true;
            }
        }
        
        return false;
    }
    
    
    private boolean isValid(int r, int c) { 
        return 0 <= r && r < n && 0 <= c && c < m;
    }
    
    
    
    
}
```

#### Expected behavior
the autograder should return false instead of true

#### Screenshots

<img width="1205" alt="Screen Shot 2020-10-15 at 8 01 54 AM" src="https://user-images.githubusercontent.com/50080416/96148614-468a2b00-0ebd-11eb-85fe-731088cd4129.png">

<img width="454" alt="Screen Shot 2020-10-15 at 8 08 01 AM" src="https://user-images.githubusercontent.com/50080416/96148875-8d782080-0ebd-11eb-83e4-bddb61e5d3d5.png">

**Comment by lc-kay** [comment]
@csmjoshi Please check out https://leetcode.com/problems/word-search/discuss/193855/Excuse-me-I-want-to-know-why-this-test-case-is-true-thanks! for an explanation of why the output is false. In addition, there are other explanations by users in the discuss tab as to why this test case should return false.

**Comment by lc-kay** [comment]
@csmjoshi Please check out this explanation! ![reply](https://user-images.githubusercontent.com/70870126/96289377-cdacd100-0f99-11eb-95e9-62a59f4abbed.jpg)

**Comment by csmjoshi** [comment]
Thanks this is great I was just a bit confused because of the given test case if very similar except the E in the 3rd col and 2nd row is a different letter :)

**Comment by csmjoshi** [comment]
But I solved it now!
