### ISSUE TITLE
1599. 经营摩天轮的最大利润缺少测试用例

### ISSUE THREAD

**Issue by HJR523** [LeetCode-Feedback/LeetCode-Feedback#12185]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
HJR

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [Y ] 缺少测试用例

**描述**
题目缺少测试用例，提交了错误的代码但是通过了所有测试用例。
输入[4,1,1,1,1,1,1,1,1,1,1,1,1,1]时，前4位游客登上摩天轮后，利润大于0，但是当允许后面几轮的游客登上摩天轮后，利润逐渐降低直至为负，所以应该轮转一次就停止运营。我提交的错误代码基本逻辑是记录利润最大时对应的轮转次数max0，最终返回max0,但是返回数据的判断标准是最终利润的大小，即最终利润为负则返回-1，对于该测试用例而言，返回了错误的数据。

**你使用的语言**
C++

**你提交或者运行的代码**
```
// Two Sum
class Solution {
public:
    int minOperationsMaxProfit(vector<int>& customers, int boardingCost, int runningCost) {
        int sum=0,n=customers.size();
        int res=0,flag=0,ret=0;//ret代表利润
        int max0=0;
        for(int i=0;i<n;i++)
        {
            sum+=customers[i];
            if(sum>=4)
            {
                res+=4*boardingCost-runningCost;
                sum-=4;
            }
            else
            {
                res+=sum*boardingCost-runningCost;
                sum=0;
            }
            flag++;
            max0=max(max0,res);
            if(max0==res)
            ret=flag;
        }
        while(sum!=0)
        {
            if(sum>=4)
            {
                res+=4*boardingCost-runningCost;
                sum-=4;
            }
            else if(sum*boardingCost-runningCost>0)
            {
                res+=sum*boardingCost-runningCost;
                sum=0;
            }
            else
            break;
            flag++;
            max0=max(max0,res);
            if(max0==res)
            ret=flag;
        }
        if(res>0)
        return ret;
        else
        return -1;
    }
};
```

**期望行为**
输入[4,1,1,1,1,1,1,1,1,1,1,1,1,1]应当输出1，但该错误代码输出了-1；

**屏幕截图**
![image](https://user-images.githubusercontent.com/123302109/222968201-1d4984f8-7509-4ed3-addc-795c82de210b.png)
![image](https://user-images.githubusercontent.com/123302109/222968216-22616baa-dc06-4f57-a444-5473ba9d84d7.png)

**额外的上下文**
你正在经营一座摩天轮，该摩天轮共有 4 个座舱 ，每个座舱 最多可以容纳 4 位游客 。你可以 逆时针 轮转座舱，但每次轮转都需要支付一定的运行成本 runningCost 。摩天轮每次轮转都恰好转动 1 / 4 周。

给你一个长度为 n 的数组 customers ， customers[i] 是在第 i 次轮转（下标从 0 开始）之前到达的新游客的数量。这也意味着你必须在新游客到来前轮转 i 次。每位游客在登上离地面最近的座舱前都会支付登舱成本 boardingCost ，一旦该座舱再次抵达地面，他们就会离开座舱结束游玩。

你可以随时停下摩天轮，即便是 在服务所有游客之前 。如果你决定停止运营摩天轮，为了保证所有游客安全着陆，将免费进行所有后续轮转 。注意，如果有超过 4 位游客在等摩天轮，那么只有 4 位游客可以登上摩天轮，其余的需要等待 下一次轮转 。

返回最大化利润所需执行的 最小轮转次数 。 如果不存在利润为正的方案，则返回 -1 。

**Comment by feiceh** [comment]
暂不处理，请提供完整的用例
