### ISSUE TITLE
Missing Test Case - 2584. Split the Array to Make Coprime Products

### ISSUE THREAD

**Issue by yumkam** [LeetCode-Feedback/LeetCode-Feedback#12181]
#### Your LeetCode username

yumkam

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My code was faulty (invokes out-of-bound access to vector/undefined behavior), but [accepted](https://leetcode.com/submissions/detail/909279090/).

Some existing testcases (e.g. `[999983,999983,....,999983]`) should already trigger bug, but apparently, ASAN check somehow optimized out, and as dereferenced uninitialized memory value is `0xbebebebe`,^1 `(long)0xbebebebe*0xbebebebe` is larger than any array value, it triggers finish condition of loop, and hides the bug.

^1 this particular value is just asan implementation detail; without asan, there can be anything in uninitialized memory

Uncommenting `assert()`  shows that out-of-bound access happens, and uncommenting `shrink_to_fit`  triggers ASAN RE.

Uncommenting two `resize()` results in RE/divide-by-zero (as out-of-bound value becomes 0).

I was not able to compose a test case that results in RE in unmodified code (but it is clearly broken).

#### Code you used for Submit/Run operation

```c++
class Solution {
public:
    int findValidSplit(vector<int>& nums) {
        auto maxv = *max_element(nums.begin(), nums.end());
        vector<int> primes {2, 3, 5, 7};
        for (unsigned p = 11; p*p <= maxv; p += 2) {
            for (auto pp: primes) {
                if (pp*pp > p)
                    break;
                if (p % pp == 0)
                    goto not_a_prime;
            }
            primes.push_back(p);
            not_a_prime:;
        }
        const unsigned n = nums.size();
        vector<vector<pair<unsigned,unsigned>>> primecnt(n);
        unordered_map<unsigned, unsigned> pm;
        for (unsigned i = 0; i < primes.size(); ++i)
            pm[primes[i]] = i;
        // primes.shrink_to_fit(); // uncommenting this line also exposes the bug (RE/ASAN)
        // primes.resize(primes.size()+1); primes.resize(primes.size()-1); // uncommenting this line results in RE/divide-by-zero
        for (unsigned i = 0; i < n; i++) {
            auto num = nums[i];
            auto &pc = primecnt[i];
            for (unsigned pi = 0; /*assert(pi < primes.size()), */static_cast<long>(primes[pi])*primes[pi] <= num; pi++) {
//////////////////////////////////////////////////////////////////^^^ pi can be out-of-bound
// uncommenting assert() above proves this
                auto p = primes[pi];
                auto c = 0;
                while(num % p == 0) {
                    num /= p;
                    ++c;
                }
                if(c)
                    pc.emplace_back(pi, c);
            }
            if (num > 1) {
                auto j = pm.emplace(num, primes.size());
                if (j.second)
                    primes.push_back(num);
                pc.emplace_back(j.first->second, 1);
            }
        }
        vector<unsigned> lsum(primes.size()), rsum(primes.size());
        for (unsigned i = 0; i < n; i++) {
            auto &pc = primecnt[i];
            for (unsigned j = 0; j < pc.size(); j++)
                rsum[pc[j].first] += pc[j].second;
        }
        unsigned commonprime = 0;
        for (unsigned i = 0; i + 1 < n; i++) {
            auto &pc = primecnt[i];
            for (unsigned j = 0; j < pc.size();++j) {
                if (lsum[pc[j].first] == 0)
                    commonprime++;
                lsum[pc[j].first] += pc[j].second;
                rsum[pc[j].first] -= pc[j].second;
                if (rsum[pc[j].first] == 0)
                    commonprime--;
            }
            if (commonprime == 0)
                return i;
        }
        return -1;
    }
};
```

#### Language used for code
C++

#### Additional context

Not sure how to detect such bugs in automated way; given current problem constraints, it does not look like there are easy way to trigger sigsegv with specially designed test case (max `nums[i]` is 10^6, so max `primes[i]` is 10^3; there are only 169 prime numbers between 1 and 10^3, so `primes.size()*sizeof(primes[0])` is less than 676 bytes).

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
