### ISSUE TITLE
1754的官方解法是错误的！

### ISSUE THREAD

**Issue by IvorHu** [LeetCode-Feedback/LeetCode-Feedback#12183]
**你的 LeetCode 用户名**
Sleepy Saha

**Bug 类型**
- [ ] 题目
- [x] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
[题目1754](https://leetcode.cn/problems/largest-merge-of-two-strings/) 里的官方解法是错误的。

**你使用的语言**
Java（与语言无关）

**你提交或者运行的代码**
官方答案

**期望行为**
测试用例：
输入："bb", "bbc"；
官方解法的输出："bbcbb"；
正确的输出应该是："bbbbc"。

**屏幕截图**
无

**额外的上下文**
无

**Comment by jackatls** [comment]
老哥，题目是字典序最大啊，没问题的，bbc放完再放bb

**Comment by IvorHu** [comment]
> 

明白你的意思了，感谢。

**Comment by IvorHu** [comment]
> 老哥，题目是字典序最大啊，没问题的，bbc放完再放bb

不对，我又看了遍题目。感觉我理解的没错，你理解的错了吧。题目中描述的两种操作，都是对字符串中的第一个字符的操作，不是对字符串的操作。也就是说每次操作的对象是一个字符，不是子字符串。因此我说的用例，答案就应该是"bbbbc"
<img width="507" alt="image" src="https://user-images.githubusercontent.com/11957444/222964699-dc37b0ef-ff73-4568-bb9f-fb1332183a9d.png">

**Comment by jackatls** [comment]
> > 老哥，题目是字典序最大啊，没问题的，bbc放完再放bb
> 
> 不对，我又看了遍题目。感觉我理解的没错，你理解的错了吧。题目中描述的两种操作，都是对字符串中的第一个字符的操作，不是对字符串的操作。也就是说每次操作的对象是一个字符，不是子字符串。因此我说的用例，答案就应该是"bbbbc" <img alt="image" width="507" src="https://user-images.githubusercontent.com/11957444/222964699-dc37b0ef-ff73-4568-bb9f-fb1332183a9d.png">

word1:"bb",word2:"bbc",merge:""
word1:"bb",word2:"bc",merge:"b"
word1:"bb",word2:"c",merge:"bb"
word1:"bb",word2:"",merge:"bbc"
word1:"b",word2:"",merge:"bbcb"
word1:"",word2:"",merge:"bbcbb"
不就是这样吗。。。

**Comment by IvorHu** [comment]
> > > 老哥，题目是字典序最大啊，没问题的，bbc放完再放bb
> > 
> > 
> > 不对，我又看了遍题目。感觉我理解的没错，你理解的错了吧。题目中描述的两种操作，都是对字符串中的第一个字符的操作，不是对字符串的操作。也就是说每次操作的对象是一个字符，不是子字符串。因此我说的用例，答案就应该是"bbbbc" <img alt="image" width="507" src="https://user-images.githubusercontent.com/11957444/222964699-dc37b0ef-ff73-4568-bb9f-fb1332183a9d.png">
> 
> word1:"bb",word2:"bbc",merge:"" word1:"bb",word2:"bc",merge:"b" word1:"bb",word2:"c",merge:"bb" word1:"bb",word2:"",merge:"bbc" word1:"b",word2:"",merge:"bbcb" word1:"",word2:"",merge:"bbcbb" 不就是这样吗。。。

题目的意思是，有两个字符串，每次对其中一个字符串的第一个字符进行操作，最后拼接成结果字符串。这样的结果字符串是有很多个的，求的是所有结果字符串中，字典序最大的那个。你评论里的是其中一个结果字符串。我说的"bbbbc"也是其中一个结果字符串，且是字典序最大的那个。

**Comment by jackatls** [comment]
是啊，我的"bbcbb"不是比你的"bbbbc"大吗，你理清一下吧

**Comment by jackatls** [comment]
> > > > 老哥，题目是字典序最大啊，没问题的，bbc放完再放bb
> > > 
> > > 
> > > 不对，我又看了遍题目。感觉我理解的没错，你理解的错了吧。题目中描述的两种操作，都是对字符串中的第一个字符的操作，不是对字符串的操作。也就是说每次操作的对象是一个字符，不是子字符串。因此我说的用例，答案就应该是"bbbbc" <img alt="image" width="507" src="https://user-images.githubusercontent.com/11957444/222964699-dc37b0ef-ff73-4568-bb9f-fb1332183a9d.png">
> > 
> > 
> > word1:"bb",word2:"bbc",merge:"" word1:"bb",word2:"bc",merge:"b" word1:"bb",word2:"c",merge:"bb" word1:"bb",word2:"",merge:"bbc" word1:"b",word2:"",merge:"bbcb" word1:"",word2:"",merge:"bbcbb" 不就是这样吗。。。
> 
> 题目的意思是，有两个字符串，每次对其中一个字符串的第一个字符进行操作，最后拼接成结果字符串。这样的结果字符串是有很多个的，求的是所有结果字符串中，字典序最大的那个。你评论里的是其中一个结果字符串。我说的"bbbbc"也是其中一个结果字符串，且是字典序最大的那个。

是啊，我的"bbcbb"不是比你的"bbbbc"大吗

**Comment by IvorHu** [comment]
> 



> > > > > 老哥，题目是字典序最大啊，没问题的，bbc放完再放bb
> > > > 
> > > > 
> > > > 不对，我又看了遍题目。感觉我理解的没错，你理解的错了吧。题目中描述的两种操作，都是对字符串中的第一个字符的操作，不是对字符串的操作。也就是说每次操作的对象是一个字符，不是子字符串。因此我说的用例，答案就应该是"bbbbc" <img alt="image" width="507" src="https://user-images.githubusercontent.com/11957444/222964699-dc37b0ef-ff73-4568-bb9f-fb1332183a9d.png">
> > > 
> > > 
> > > word1:"bb",word2:"bbc",merge:"" word1:"bb",word2:"bc",merge:"b" word1:"bb",word2:"c",merge:"bb" word1:"bb",word2:"",merge:"bbc" word1:"b",word2:"",merge:"bbcb" word1:"",word2:"",merge:"bbcbb" 不就是这样吗。。。
> > 
> > 
> > 题目的意思是，有两个字符串，每次对其中一个字符串的第一个字符进行操作，最后拼接成结果字符串。这样的结果字符串是有很多个的，求的是所有结果字符串中，字典序最大的那个。你评论里的是其中一个结果字符串。我说的"bbbbc"也是其中一个结果字符串，且是字典序最大的那个。
> 
> 是啊，我的"bbcbb"不是比你的"bbbbc"大吗

对，我晕了。
