### ISSUE TITLE
Missing Test Case - 2584. Split the Array to Make Coprime Products

### ISSUE THREAD

**Issue by venico19** [LeetCode-Feedback/LeetCode-Feedback#12195]
#### Your LeetCode username

venico19

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [*] Missing Test Cases 

#### Description of the bug

missing test case
input: [1,1]
expected output: 0

the following code outputs -1 for this test case. however, the submission is accepted as a success on leetcode. 

#### Code you used for Submit/Run operation

```
class Solution:
    def findValidSplit(self, nums: List[int]) -> int:
        N = len(nums)
        if N == 1:
            return -1
        def prime_factors(n):
            i = 2
            factors = set()
            while i * i <= n:
                if n % i:
                    i += 1
                else:
                    n //= i
                    factors.add(i)
            if n > 1:
                factors.add(n)
            return factors 
        
        factors = {}
        for num in nums:
            if num == 1:
                continue
            if num not in factors:
                factors[num] = prime_factors(num)

        
        c1 = collections.Counter()
        c2 = collections.Counter()
        
        for i, num in enumerate(nums):
            if num == 1:
                continue
            for f in factors[num]:
                c2[f] += 1
                
                    
        for i, num in enumerate(nums):
            if i == N-1:
                break
            if num == 1:
                continue
            for f in factors[num]:
                c2[f] -= 1
                if c2[f] == 0:
                    del c2[f]
                c1[f] += 1
            if len(set(c1.keys()).intersection(set(c2.keys()))) == 0:
                return i
            
        return -1
```

#### Language used for code

Python

#### Expected behavior

missing test case
input: [1,1]
expected output: 0

the following code outputs -1 for this test case. however, the submission is accepted as a success on leetcode.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
