### ISSUE TITLE
Leetcode provides Rust 2018, not Rust 2021.

### ISSUE THREAD

**Issue by edward-shen** [LeetCode-Feedback/LeetCode-Feedback#12197]
#### Your LeetCode username

xEddie

#### Category of the bug

- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

Rust edition is not 2021.

While the Rust version is 1.58.1 (and thus supports Rust 2021), the provided [_edition_] is only 2018. This means that some [newer changes](https://doc.rust-lang.org/edition-guide/rust-2021/index.html) aren't present, which is unexpected for Rust users. 

[_edition_]: https://doc.rust-lang.org/edition-guide/editions/index.html

#### Code you used for Submit/Run operation

```
// Two Sum
impl Solution {
    pub fn two_sum(nums: Vec<i32>, target: i32) -> Vec<i32> {
        let _: [i32; 1] = nums.try_into();
        unreachable!(); // For type checking
    }
}
```

Compile error:

```
Line 3, Char 32: no method named `try_into` found for struct `Vec<i32>` in the current scope (solution.rs)
    |
3   |         let _: [i32; 1] = nums.try_into();
    |                                ^^^^^^^^ method not found in `Vec<i32>`
    |
    = help: items from traits can only be used if the trait is in scope
    = note: 'std::convert::TryInto' is included in the prelude starting in Edition 2021
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
10  | use std::convert::TryInto;
    |
For more information about this error, try `rustc --explain E0599`.
error: could not compile `prog` due to previous error
mv: cannot stat '/leetcode/rust_compile/target/release/prog': No such file or directory
```

#### Language used for code

Rust

#### Expected behavior

No compile error, as the trait is automatically included as part of Rust 2021.

#### Screenshots

N/A

#### Additional context

If you're compiling Rust code with `rustc`, you can add the CLI argument `--edition 2021` to have it compile with the new edition, e.g. `rustc --edition 2021 solution.rs`.

If you're using cargo to compile Rust code, this will require you to add `edition = "2021"` to the `Cargo.toml` under the `package` map.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
