### ISSUE TITLE
Missing Test Case - 1539. Kth Missing Positive Number

### ISSUE THREAD

**Issue by ejhuzed** [LeetCode-Feedback/LeetCode-Feedback#12199]
#### Your LeetCode username
[ejhuzed](https://leetcode.com/ejhuzed/)

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug
The following AC code cannot pass these test cases:
arr = `[1,2,3,4,5,7,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,28,29,30,31,32,33,34,35,36,37,38,39,41,42,43,44,45,46,47,48,49,50,51,53,54,55,56,58,59,60,61,62,63,65,66,67,68,69,70,71,73,74,75,76,77,79,80,81,82,83,84,85,86,87,88,89,90,91,93,94,95,96,98,100,101,102,103,104,105,106,107,109,110,111,112,113,114,115,116,118,120,121,122,123,124,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,178,179,180,181,182,184,185,186,187,188,189,190,191,192,194,195,196,198,199,201,202,203,204,205,206,207,208,209,211,212,213,215,216,218,219,220,221,222,223,224,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,266,267,268,269,270,271,272,273,274,276,277,278,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,307,308,309,310,311,312,313,314,315,316,318,319,320,321,322,323,324,326,327,328,329,330,331,332,333,334,336,337,338,339,340,342,344,345,348,349,350,351,352,353,354,356,357,359,360,361,363,364,365,366,367,368,370,371,373,374,376,377,378,379,380,381,382,383,384,385,387,388,389,390,391,393,394,395,396,397,398,399,400,401,402,405,406,408,409,410,411,412,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,454,455,456,457,458,459,460,461,462,465,466,467,468,469,470,471,472,473,475,476,477,480,481,482,483,484,486,487,488,490,491,492,493,494,495,497,498,500,501,502,503,504,505,507,508,510,511,512,513,514,515,517,518,519,520,522,523,524,525,526,527,529,530,531,532,533,534,535,536,537,538,540,541,542,543,544,545,546,547,548,549,551,552,553,554,555,558,559,560,562,563,564,565,566,567,568,569,571,572,573,575,576,577,578,579,580,581,582,585,586,587,588,589,590,591,592,593,594,596,597,598,599,600,601,602,603,604,605,606,608,609,610,611,612,614,617,618,619,620,621,622,623,624,625,626,628,629,630,631,632,633,634,635,636,637,638,639,641,642,643,644,645,647,648,649,650,652,654,655,656,657,658,659,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,687,688,689,690,691,692,693,694,695,696,697,699,700,701,702,703,704,705,706,707,708,709,710,712,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,735,736,737,738,739,740,741,743,744,745,746,747,748,749,750,751,752,753,754,755,756,757,758,759,761,762,763,764,765,766,767,768,769,771,772,773,775,776,777,778,779,781,783,784,785,787,788,789,790,792,793,794,795,796,797,798,799,801,803,804,805,806,807,808,809,812,813,814,815,816,817,818,819,820,822,823,825,826,827,828,829,830,832,834,835,836,837,838,839,840,842,843,844,845,846,847,848,849,850,851,852,853,854,855,856,857,858,859,860,861,862,863,864,865,866,868,869,870,871,872,873,874,875,876,877,878,879,882,884,885,886,888,889,890,891,892,893,896,897,898,900,901,902,903,904,905,906,907,909,910,911,913,915,916,917,918,919,921,922,923,924,925,926,927,928,930,931,932,933,934,935,936,937,938,939,940,942,943,945,946,947,948,949,950,951,952,953]`;
k $\in$ `[777, 782]`.

#### Code you used for Submit/Run operation
```python3
class Solution:
    def findKthPositive(self, arr: List[int], k: int) -> int:
        n = max(arr) + k + 319
        return list(set(range(n))-set(arr))[k]
```

#### Language used for code
Python3

#### Expected behavior
The submisson should get WA.

#### Screenshots
![LC-1539-AC](https://user-images.githubusercontent.com/108965511/223036606-4f68795b-35aa-4ed9-8921-c5b10845803d.PNG)
![LC-1539-WA](https://user-images.githubusercontent.com/108965511/223036622-15501b9f-41c5-4030-9070-5f01750185b2.PNG)

#### Additional context
The rectification is simple:
```python3
class Solution:
    def findKthPositive(self, arr: List[int], k: int) -> int:
        return sorted(list(set(range(max(arr) + k + 1)) - set(arr)))[k]
```
However, if we change the constant `319` to another number, it's possible to design test cases for leading to a similar circumstance. The problem is an another question related to the behaviour of the difference between two sets in Python.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
