### ISSUE TITLE
Missing Test Case - 124. Binary Tree Maximum Path Sum

### ISSUE THREAD

**Issue by RayLLL** [LeetCode-Feedback/LeetCode-Feedback#12198]
#### Your LeetCode username

RayLLLL

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

my code can pass but indeed it is wrong in this testcase:  [-2,0,0]

#### Code you used for Submit/Run operation

```
class Solution:
    def maxPathSum(self, root: Optional[TreeNode]) -> int:
        max_list, max_sum = self.help(root)
        return max_sum
        
    def help(self, root):
        if root == None:
            return 0, 0
        l_max_list, l_max_sum = self.help(root.left)
        r_max_list, r_max_sum = self.help(root.right)
        
        max_list = max(max(l_max_list, r_max_list) + root.val, 0)

        if l_max_sum == 0 and r_max_sum == 0:
            max_sum = root.val
        else:
            if l_max_sum == 0 or r_max_sum == 0:
                max_sum = l_max_sum + r_max_sum
            else:
                max_sum = max(l_max_sum, r_max_sum)
            max_sum = max(max_sum, l_max_list+r_max_list+root.val)

        return max_list, max_sum
```

#### Language used for code

python3

#### Expected behavior

my code can pass but indeed it is wrong in this testcase:  [-2,0,0]

#### Screenshots

<img width="1209" alt="截屏2023-03-06 下午1 13 41" src="https://user-images.githubusercontent.com/15841062/223024498-ebcbc861-e4ff-43fc-ac53-2ab43f53e3e3.png">
<img width="443" alt="截屏2023-03-06 下午1 13 11" src="https://user-images.githubusercontent.com/15841062/223024518-bf35911c-b91e-4ada-a016-ce4fbc1a49bf.png">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
