### ISSUE TITLE
Missing Test Case - 367. Valid Perfect Square

### ISSUE THREAD

**Issue by Xordal** [LeetCode-Feedback/LeetCode-Feedback#12192]
#### Your LeetCode username
Xordal

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Missing test case for C# language. Submit tests cases should contains `940771583` to check the solution where user use the division of the `num` and `mid` value in Binary Search algorithm instead of `mid * mid` to check new boundaries. In my case I used `float` type instead of `double` and my solution passes all `submit` test cases. But it shouldn't, because on the step where
```
lo = 30672
hi = 30672
mid = 30672
div = 30672 instead of 30671.999967396976
```
it happens because of the different precision for float and double.

#### Code you used for Submit/Run operation

```
public class Solution {
    public bool IsPerfectSquare(int num) {
        int left = 1;
        int right = num;

        while (left <= right) {
            int mid = (left + right) >> 1;
            float div = (float) num / mid; 

            if (div < mid) {
                right = mid - 1;
            } else 
            if (div > mid) {
                left = mid + 1;
            } else {
                return true;
            }
        }

        return false;
    }
}
```

#### Language used for code
C#

#### Expected behavior
false

#### Screenshots
![image](https://user-images.githubusercontent.com/4664579/222986691-15836420-c7cb-4e11-a2b5-ac6715d5703a.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

The purpose of the problem is not to catch the floating point errors.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
