### ISSUE TITLE
2306. Naming a Company Solution Worded Wrong

### ISSUE THREAD

**Issue by StrawHatDragon100** [LeetCode-Feedback/LeetCode-Feedback#12193]
#### Category of the bug
- [ ] Question
- [ x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The example used in the beginning is wrong, it should be doffee conuts instead of coffee donuts

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior

![image](https://user-images.githubusercontent.com/19656900/222988054-0aebfb2e-0a93-43d9-a538-16510d697be4.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
