### ISSUE TITLE
Wrong Test Case - 37. Sudoku Solver

### ISSUE THREAD

**Issue by zkeal** [LeetCode-Feedback/LeetCode-Feedback#12190]
#### Your LeetCode username

zkeal

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

Wrong test case

#### Description of the bug

In question 37. Sudoku Solver, It is guaranteed that the input board has only one solution.  But the second test case has more than one solution.

case:
board =
[[".",".","9","7","4","8",".",".","."],["7",".",".",".",".",".",".",".","."],[".","2",".","1",".","9",".",".","."],[".",".","7",".",".",".","2","4","."],[".","6","4",".","1",".","5","9","."],[".","9","8",".",".",".","3",".","."],[".",".",".","8",".","3",".","2","."],[".",".",".",".",".",".",".",".","6"],[".",".",".","2","7","5","9",".","."]]

solution1:
[["6","3","9","7","4","8","1","5","2"],["7","4","1","6","5","2","8","3","9"],["8","2","5","1","3","9","6","7","4"],["3","5","7","9","8","6","2","4","1"],["2","6","4","3","1","7","5","9","8"],["1","9","8","5","2","4","3","6","7"],["9","7","1","8","6","3","4","2","5"],["5","8","2","4","9","1","7","8","6"],["4","8","6","2","7","5","9","1","3"]]

solution2:
[["5","1","9","7","4","8","6","3","2"],["7","8","3","6","5","2","4","1","9"],["4","2","6","1","3","9","8","7","5"],["3","5","7","9","8","6","2","4","1"],["2","6","4","3","1","7","5","9","8"],["1","9","8","5","2","4","3","6","7"],["9","7","5","8","6","3","1","2","4"],["8","3","2","4","9","1","7","5","6"],["6","4","1","2","7","5","9","8","3"]]

#### Code you used for Submit/Run operation

```
public void solveSudoku(char[][] board) {
        boolean[][][] b_board = new boolean[3][9][9];
        int length = board.length;
        for(int i = 0; i < length; i ++)
        {
            for(int j = 0; j < length; j ++)
            {
                if(board[i][j] != '.')
                {
                    int temp_value = Character.getNumericValue(board[i][j]) - 1;
                    add(b_board[0], i,temp_value);
                    add(b_board[1], j,temp_value);
                    add(b_board[2], get_box(i,j), temp_value);
                }
            }
        }

        char[][] result = search_fill(board, b_board);
        board = result;
        
    }


    public static char[][] search_fill(char[][] board, boolean[][][] b_board)
    {
        int length = board.length;
        // char[][] c_board = board.clone();
        int min_options = Integer.MAX_VALUE;
        List<ArrayList<Integer>> option_records = new ArrayList<ArrayList<Integer>>();
        List<Integer> i_records = new ArrayList<>();
        List<Integer> j_records = new ArrayList<>();

        int empty_counter = 0;


        for(int i = 0; i < length; i ++)
        {
            for(int j = 0; j < length; j++)
            {
                if(board[i][j] == '.')
                {
                    empty_counter ++;
                    int select_box = get_box(i,j);
                    ArrayList<Integer> temp_list = compute_avaible(b_board[0][i], b_board[1][j], b_board[2][select_box]);
                    if(temp_list.size() == 0)
                    {
                        char[][] invalid_try = new char[0][0];
                        return invalid_try;
                    }
                    if(temp_list.size() < min_options)
                    {
                        min_options = temp_list.size();
                        option_records.clear();
                        i_records.clear();
                        j_records.clear();

                        option_records.add(temp_list);
                        i_records.add(i);
                        j_records.add(j);
                    }else if(temp_list.size() == min_options)
                    {
                        option_records.add(temp_list);
                        i_records.add(i);
                        j_records.add(j);
                    }
                }
            }
        }

        if(empty_counter == 0)
        {
            return board;
        }else{
            for(int a = 0; a < i_records.size(); a ++)
            {
                int index_i = i_records.get(a);
                int index_j = j_records.get(a);
                for(Integer option: option_records.get(a))
                {
                    char[][] c_board = board.clone();
                    c_board[index_i][index_j] = Character.forDigit(option + 1,10);
                    boolean[][][] c_bboard = b_board.clone();
                    c_bboard[0][index_i][option] = true;
                    c_bboard[1][index_j][option] = true;
                    c_bboard[2][get_box(index_i, index_j)][option] = true;
                    char[][] temp_result = search_fill(c_board,c_bboard);
                    if(temp_result.length > 0){
                        return temp_result;
                    }
                }
            }
        }

        return new char[0][0];
    }

    public static ArrayList<Integer> compute_avaible(boolean[] i1, boolean[] j1, boolean[] b1)
    {
        int length = i1.length;
        int counter = 0;
        ArrayList<Integer> result = new ArrayList<>();
        for(int i = 0; i < length; i ++)
        {
            boolean avaliable = i1[i] || j1[i] || b1[i];
            if(!avaliable)
            {
                counter++;
                result.add(i);
            }
        }
        return result;
    }
    


    public static int get_box(int i, int j)
    {
        int index1 = i/3;
        int index2 = j/3;
        return index1 * 3 + index2;
    }

    public static boolean add(boolean[][] arr, int i, int j)
    {
        if(arr[i][j])
        {
            return false;
        }else{
            arr[i][j] = true;
            return true;
        }
    }
```

#### Language used for code

Java

#### Expected behavior

My algorithm generates the solution1, but the expected solution for the test case is solution2. So please remove this wrong test case.

#### Screenshots

<img width="990" alt="image" src="https://user-images.githubusercontent.com/12712948/222983789-e676aa1d-9b3f-4924-b455-5ab727e45ad9.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by zkeal** [comment]
Thanks for your update!

My submission link is: 
https://leetcode.com/problems/sudoku-solver/submissions/911048065/

I hope it can help you to address this issue.

>

**Comment by zkeal** [comment]
> Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
> 
> The code submission AC link.
> 
> We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

Thanks for your update!

My submission link is:
https://leetcode.com/problems/sudoku-solver/submissions/911048065/

I hope it can help you to address this issue.
