### ISSUE TITLE
670. Maximum Swap, Approach #2: Greedy is wrong

### ISSUE THREAD

**Issue by triper1022** [LeetCode-Feedback/LeetCode-Feedback#1219]
#### Your LeetCode username
MarcoChang

#### Category of the bug
- [ ] Question : 670. Maximum Swap
- [ ] Solution : Approach #2: Greedy
- [ ] Language : Python

#### Description of the bug

If num = 10944,
it also returns 10944

And I don't think we need to use any array or hashmap or transformation.
We can just use pointers, one loop, one swap to get the answer.
I have posted [my code in discussion](https://leetcode.com/problems/maximum-swap/discuss/895957/One-loop-No-Str-or-List-O(N)-time-O(1)-space-Clean-Code). 

#### Code you used for Submit/Run operation

```
class Solution:
    def maximumSwap(self, num):
        result, count = num, 0
        maxDigit, maxIndex = 0, None
        minDigit, minIndex = None, None
        curMaxDigit, curMaxIndex = None, None

        while num:
            num, digit = num // 10, num % 10
            if digit > maxDigit and num:
                maxDigit, maxIndex = digit, count

            if digit < maxDigit:
                minDigit, minIndex = digit, count
                curMaxDigit, curMaxIndex = maxDigit, maxIndex

            count += 1
            
        if not minIndex: return result
        
        swapMax = curMaxDigit * (10**minIndex - 10**curMaxIndex)
        swapMin = minDigit * (10**curMaxIndex - 10**minIndex)
        return result + swapMax + swapMin
```

#### Language used for code

Python

**Comment by lc-kay** [comment]
Hi @triper1022 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@triper1022 Our team has tested approach 2 and everything works fine. The proof is in the attachment. Thank you for your time!
![image](https://user-images.githubusercontent.com/70870126/97762289-45641b00-1ac5-11eb-8570-1d0cf6caa864.png)
