### ISSUE TITLE
[Binary Tree Maximum Path Sum] Individual test case passes but fails against test suite

### ISSUE THREAD

**Issue by desoukya** [LeetCode-Feedback/LeetCode-Feedback#122]
**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
Problem: Binary Tree Maximum Path Sum

Individual test case passes for input `[0]` (Run Code). However, when submitting the solution, the same test case - input `[0]` - fails in the test suite.

According to the details:
7 / 93 test cases passed.

Perhaps the issue is related to the global variable not properly reseting for each test.

**what language is your code written in**
Javascript

**The code you submit/run**
```
let maxSum = Number.NEGATIVE_INFINITY;
const maxGain = function(node) {
  if (node === null) return 0;
  
  // get max sum on the left & right sub-trees of node
  const leftMax = Math.max(maxGain(node.left), 0);
  const rightMax = Math.max(maxGain(node.right), 0);
  
  // compute the current max for this node and all its subtrees
  const currentMax = node.val + leftMax + rightMax;
  
  // Set the global maxSum to either this node and its subtrees
  // or the current maxSum which indicates a different node & subtrees
  // have a higher sum
  maxSum = Math.max(maxSum, currentMax);
  
  // for this node, return the highest path sum (node + left/right subtree)
  return node.val + Math.max(leftMax, rightMax);
};

const maxPathSum = function(root) {
  maxGain(root);
  return maxSum;
};
```

**Expected behavior**
Expect output to be zero.

**Screenshots**
<img width="1680" alt="Screen Shot 2020-04-06 at 11 40 16 PM" src="https://user-images.githubusercontent.com/10380913/78805821-ed7e8f00-798f-11ea-984b-2f252789b558.png">

**Additional context**
N/A

**Comment by CooperCooperCooper** [comment]
Hi @desoukya,
Thank you for reaching out to us! The differences in output between "Run Code" and "Submit" is a popular issue, and we've document its cause and solution in this "[Wrong Answer/Runtime Error for a specific test case](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-)" article. Please take a look.

**Comment by desoukya** [comment]
> Perhaps the issue is related to the global variable not properly reseting for each test.

Thanks for the prompt reply @CooperCooperCooper. Seems my intuition above was correct. I'll modify the code by removing the global variable and give that a shot. Thanks again!
