### ISSUE TITLE
增加测试用例

### ISSUE THREAD

**Issue by Willberg** [LeetCode-Feedback/LeetCode-Feedback#12202]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
[John](https://leetcode.cn/u/john-cxk/)

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [X] 缺少测试用例

**描述**
发现自己的代码有测试用例不能通过，但是可以提交成功

**你使用的语言**
Go

**你提交或者运行的代码**
```
func findValidSplit(nums []int) int {
    n := int(1e6+1)
    ids := make([]int, n)
    parents := make([]int, n)
    for i := range ids {
        ids[i] = i
        parents[i] = i
    }
    for i, v := range nums {
        ids[v] = i
        parents[v] = v 
    }
    
    var root func(int)int
    root = func(a int) int {
        if a == parents[a] {
            return a
        }
        parents[a] = root(parents[a])
        return parents[a]
    }

    var connect func(int, int)
    connect = func(a, b int) {
        ra, rb := root(a), root(b)
        if ra == rb {
            return
        }
        if ids[ra] < ids[rb] {
            parents[ra] = rb
        } else {
            parents[rb] = ra
        }
    }
    for _, v := range nums {
        for i:=2; i * i <= v; i++ {
            if v % i == 0 {
                connect(v, i)
                connect(v, v / i)
            }
        }
    }
    
    for i, k := 0, 0; i<len(nums)-1; i++ {
        k = max(k, ids[root(nums[i])])
        if k <= i {
            return i
        }
    }
    return -1
}

func max(a, b int) int {if a>b{return a}; return b}
```

**期望行为**
输入：[2,440246,3]，输出：-1，期望：1
但是可以提交成功

**屏幕截图**
![截屏2023-03-06 20 38 56 (2)](https://user-images.githubusercontent.com/11694164/223113496-6aa6a311-d0ed-4bfc-9565-d17ac0234e4d.png)

**额外的上下文**
[2584. 分割数组使乘积互质](https://leetcode.cn/problems/split-the-array-to-make-coprime-products/)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
