### ISSUE TITLE
题解错误：1653: 使字符串平衡的最少删除次数

### ISSUE THREAD

**Issue by cjl0222** [LeetCode-Feedback/LeetCode-Feedback#12201]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
[qing-feng-fei-yu](https://leetcode.cn/u/qing-feng-fei-yu/)

**Bug 类型**
- [ ] 题目
- [x] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
题解错误：1653: 使字符串平衡的最少删除次数，

> 3. 字符串既有 “a” 也有 “b”，且所有 “a” 都在所有 “a” 左侧。

**你使用的语言**
C++

**你提交或者运行的代码**

**期望行为**

应为：
> 3. 字符串既有 “a” 也有 “b”，且所有 “a” 都在所有 *“b”* 左侧。

**屏幕截图**
![image](https://user-images.githubusercontent.com/32232720/223093196-43f83e70-76f8-4143-bd0d-550c331c6c7f.png)

**额外的上下文**
无

**Comment by feiceh** [comment]
![img_v2_35357b53-b3bc-4599-8c97-b9a689d7e02g](https://user-images.githubusercontent.com/61722985/223347698-74c19319-217f-4fb0-97fc-a26ffa1d3a06.jpg)
Hello～当前核实题解没有反馈中所述的错误，感谢反馈。
