### ISSUE TITLE
Wrong Expected Result in one Testcase - 474. Ones and Zeroes

### ISSUE THREAD

**Issue by dattadebrup** [LeetCode-Feedback/LeetCode-Feedback#1220]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

One of the testcase produces wrong expected result. (https://leetcode.com/submissions/detail/409139503/) . In this particular testcase the expected result given is 3 whereas at max only 2 strings can be used to get 3 zeros and 4 ones [ "111001" , "0" ] . So the given expected result is wrong .

#### Code you used for Submit/Run operation

```
class Solution {
    public int findMaxForm(String[] strs, int m, int n)
    {
        int[][][] dp = new int[strs.length][m+1][n+1] ;
        HashMap<Integer, Integer> map1 = new HashMap<>() ;
        for (int i  =0 ; i < strs.length ; i++)
        {
            map1.put(i , 0) ;
            for (int j = 0 ; j < strs[i].length() ; j++)
            {
                if (strs[i].charAt(j) == '1')
                {
                    map1.put(i , map1.getOrDefault(i,0) +1 );
                }
            }
        }

        for ( int j= 0 ; j <= m ; j++)
        {
            for (int k = 0 ; k <= n ; k++)
            {
                if (j== strs[0].length() - map1.get(0) && k == map1.get(0))
                    dp[0][j][k] = 1;
            }
        }

        for (int i = 1 ; i< strs.length ; i++)
        {
            for (int j = 0 ; j <= m ; j++)
            {
                for (int k = 0 ; k <= n ; k++)
                {
                    
                    if (j >= strs[i].length() - map1.get(i) && k >= map1.get(i) )
                    {
                        dp[i][j][k] = Math.max(dp[i-1][j][k] , dp[i -1 ][j -strs[i].length() + map1.get(i)][k -map1.get(i)] +1 ) ;
                    }
                    else
                    {
                        dp[i][j][k] = dp[i-1][j][k] ;
                    }
                    
                    //System.out.println(i+ " "+ j + " "+ k +" " + dp[i][j][k]) ;
                }
            }
        }

        return  dp[strs.length -1][m][n] ;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The expected result for this particular testcase should be 2 .  (https://leetcode.com/submissions/detail/409139503/)

**Comment by lc-kay** [comment]
@dattadebrup Please check out the comments in https://leetcode.com/problems/ones-and-zeroes/discuss/297231/The-test-case-must-be-wrong. and https://leetcode.com/problems/ones-and-zeroes/discuss/801238/How-to-understand-the-test-case-%2210%22%220001%22%22111001%22%221%22%220%22-4-3-to-be-3 for an explanation on this test case. To clarify this for the future, I've relayed this to my team to update the description.

**Comment by lc-kay** [comment]
Hi @dattadebrup 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
