### ISSUE TITLE
增加测试用例

### ISSUE THREAD

**Issue by Willberg** [LeetCode-Feedback/LeetCode-Feedback#12200]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
[John](https://leetcode.cn/u/john-cxk/)

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [X] 缺少测试用例

**描述**
运行别人通过的代码时，发现有个测试用例无法通过

**你使用的语言**
Java

**你提交或者运行的代码**
```
class Solution {
        int[] parents;
        int[] ids;
        public int findValidSplit(int[] nums) {
            int n = nums.length;
            parents = new int[(int) (1e6+1)];
            ids = new int[(int) (1e6+1)];

            for(int i = 0; i < n; i++) {
                parents[nums[i]] = nums[i];
                ids[nums[i]] = i;
            }

            for(int i = 0; i < n; i++){
                for(int j = 2; j*j <= nums[i];j++){
                    if(nums[i]%j==0){
                        connect(nums[i],j);
                        connect(nums[i],nums[i]/j);
                    }
                }
            }

            for(int i = 0,k=0; i < n-1; i++){
                k = Math.max(ids[root(nums[i])],k);
                if(k<=i) return i;
            }
            return -1;
        }

        private void connect(int a, int b){
            int ra = root(a);
            int rb = root(b);
            if(ra == rb) return;
            if(ids[ra]>ids[rb]){
                parents[rb] = ra;
            }else{
                parents[ra] = rb;
            }

        }

        private int root(int a){
            return a == parents[a]?a:(parents[a] = root(parents[a]));
        }
    }
```

**期望行为**
测试用例：[4,7,8,15,3,5,209]
应该返回2，结果返回-1，但提交通过

**屏幕截图**
![截屏2023-03-06 17 28 58 (2)](https://user-images.githubusercontent.com/11694164/223072132-2302d308-960c-4f3b-9c8c-a7a096b99550.png)

**额外的上下文**
[2584. 分割数组使乘积互质](https://leetcode.cn/problems/split-the-array-to-make-coprime-products)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
