### ISSUE TITLE
550. Game Play Analysis IV - why my solution is wrong? Leetcode behavior is weird for my query

### ISSUE THREAD

**Issue by KARTH33K** [LeetCode-Feedback/LeetCode-Feedback#12217]
SELECT round((z.count/(SELECT count(distinct a2.player_id) from activity a2)),2) as fraction
FROM (
        SELECT count(distinct x.player_id) as count
        FROM (
                SELECT a.*, 
                        case when event_date - 1 = lag(event_date) over(partition by player_id order by event_date asc)  THEN 1
                        ELSE 0
                        END as flag,
                        (SELECT count(distinct a1.player_id) from activity a1) as count
                FROM Activity a) x
        WHERE x.flag = 1) z;

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

**Comment by KARTH33K** [comment]
The result is "Accepted" when run but when I submit it, it shows "Wrong". 

Please check
