### ISSUE TITLE
724. Find Pivot Index

### ISSUE THREAD

**Issue by rika97** [LeetCode-Feedback/LeetCode-Feedback#12214]
#### Your LeetCode username
chailattewithcream

#### Category of the bug
- [ ] Question
- [ ] Solution
- [✅] Language
- [ ] Missing Test Cases 

#### Description of the bug

Console returns integer instead of float.

#### Code you used for Submit/Run operation

```
class Solution(object):
    def pivotIndex(self, nums):
        """
        :type nums: List[int]
        :rtype: int
        """
        total = sum(nums)
        left = 0
        left_sum = 0
        while left < len(nums):
            if left_sum == int(total-nums[left]) / 2:
                return left
            else:
                left_sum += nums[left]
                left += 1
        return -1
```

#### Expected behavior

This produces the correct calculation in other consoles (float) but the console in leetcode turns an int into a float  (does the calculation 5/2 = 2 instead of 2.5.)

#### Screenshots

<img width="691" alt="Screen Shot 2023-03-06 at 1 11 20 PM" src="https://user-images.githubusercontent.com/27670355/223231715-bd646534-1ed0-4a72-9dae-f1825e98a728.png">

**Comment by LC-Pam** [comment]
![Screen Shot 2023-03-07 at 2 20 11 PM](https://user-images.githubusercontent.com/103138242/223528635-78619f72-e815-4311-a5ab-31b1278a3e0a.png)

**Comment by rika97** [comment]
<img width="700" alt="Screen Shot 2023-03-07 at 10 36 42 PM" src="https://user-images.githubusercontent.com/27670355/223637492-7d81bccf-89fc-4f10-b251-48b25365880e.png">
I tried it again today, it's still there.
