### ISSUE TITLE
Missing Test Case - 1539. Kth Missing Positive Number

### ISSUE THREAD

**Issue by RohitSgh** [LeetCode-Feedback/LeetCode-Feedback#12212]
#### Your LeetCode username

RohitSgh

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Code gets accepted/[submitted](https://leetcode.com/problems/kth-missing-positive-number/submissions/910339007/). 

But ideally it shouldn't. It is giving **Wrong Answer** for this Custom Input. 
```
[4]
5
```

#### Code you used for Submit/Run operation

```Python3
class Solution:
    def findKthPositive(self, arr: List[int], k: int) -> int:
        
        if len(arr) == 1:
            return k + (arr[0] == k)
        
        if k < arr[0]:
            return k

        missing = arr[0] - 1

        for idx in range(1, len(arr)):
            if arr[idx] != arr[idx-1] + 1:
                gap = arr[idx] - arr[idx-1] - 1
                if missing + gap >= k:
                    return arr[idx-1] + (k - missing)
                else:
                    missing += gap
        
        return arr[-1] + (k - missing)
```

#### Language used for code

Python3

#### Expected behavior

For Test Case

arr
`[4]`

k
`5`

Expected Answer is `6`. However, the code returns `5`. It still gets submitted because this Test Case is missing.

#### Screenshots

> ![Submission along with Wrong Answer](https://user-images.githubusercontent.com/81853910/223197868-d9f6f41b-867a-4e77-a8c4-f5a18d089e2c.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
