### ISSUE TITLE
Leetcode explore DSA crash course |  Graph BFS | Number of Provinces C++ code is mixing recursion and iteration

### ISSUE THREAD

**Issue by ArunTejCh** [LeetCode-Feedback/LeetCode-Feedback#12216]
The example C++ code for Number of Provinces is mixing recursion and iteration. For the recursive solution its using stack where its not needed and for the iterative solution its calling the function recursively.

Recursive solution:

    void dfs(int node) {
        stack<int> stack;
        stack.push(node); // There is no need of this stack here.
        
        while (!stack.empty()) {
            int node = stack.top();
            stack.pop();
            for (int neighbor: graph[node]) {
                if (!seen[neighbor]) {
                     // the next 2 lines are needed to prevent cycles
                     seen[neighbor] = true;
                     dfs(neighbor);
                }
            }
        }
    }

Iterative solution:

  void dfs(int node) {
      stack<int> stack;
      stack.push(node);
  
      while (!stack.empty()) {
          int node = stack.top();
          stack.pop();
          for (int neighbor: graph[node]) {
              if (!seen[neighbor]) {
                  seen[neighbor] = true;
                  dfs(neighbor); // Eh? why is the function being called recursively?
              }
          }
      }
  }

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've submitted your feedback to the team. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
