### ISSUE TITLE
Missing Test Case - 20. Valid Parentheses

### ISSUE THREAD

**Issue by DaskivuoS** [LeetCode-Feedback/LeetCode-Feedback#12213]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution
{
    List<Integer> parentheses=new ArrayList<Integer>();
    List<Integer> braces=new ArrayList<Integer>();
    List<Integer> square_brackets=new ArrayList<Integer>();

    int priority = 0;
    public boolean isValid(String s)
    {
        //if it starts with a closing bracket it is already out
        for(int i=0;i<s.length();i++)
        {
            boolean check = true;
            if(s.charAt(i) == '(' || s.charAt(i) == '{' || s.charAt(i) == '[')
            add_bracket(s.charAt(i));
            else if(s.charAt(i) == ')' || s.charAt(i) == '}' || s.charAt(i) == ']') 
            if(remove_bracket(s.charAt(i)) == false)
            return false;
        }
        if(priority != 0)
        return false;
        int sum = 0;
        for(int i:parentheses)
            sum = sum+i;
        if(sum != 0)
        return false;
        for(int i:braces)
            sum = sum+i;
        if(sum != 0)
        return false;
        for(int i:square_brackets)
            sum = sum+i;
        if(sum != 0)
        return false;

        //check_status();

        return true;
    }
    public void add_bracket(char x)
    {
        priority++;
        if(x == '(')
        parentheses.add(priority);
        if(x == '{')
        braces.add(priority);
        if(x == '[')
        square_brackets.add(priority);
    }
    public boolean remove_bracket(char x)
    {
        if(x == ')')
        {
            if(parentheses.indexOf(priority) == -1)
                return false;
            parentheses.add(0-(priority));
        }
        if(x == '}')
        {
            if(braces.indexOf(priority) == -1)
                return false;
            braces.add(0-(priority));
        }
        if(x == ']')
        {
            if(square_brackets.indexOf(priority) == -1)
                return false;
            square_brackets.add(0-(priority));
        }
        priority--;
        return true;
    }
    public void check_status()
    {
        System.out.print("Parentheses     : ");
        for(int a:parentheses)  
        System.out.print(a + ",");
        System.out.println("");
        System.out.print("Braces         : ");
        for(int a:braces)  
        System.out.print(a + ","); 
        System.out.println("");
        System.out.print("Square brackets :");
        for(int a:square_brackets)  
        System.out.print(a + ",");   
        System.out.println("");
        System.out.println("Priority status is : "+priority);
    }
}
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The  language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by DaskivuoS** [comment]
1. I programmed on Java. The program working to solve the problem that I
submitted runs on Java
2. The problem stated that the brackets should be opened and closed in
order. It naturally means that something like [{()}] would be right but the
sample test cases that are displayed for reference does not mention
something like this. Given that the problem is categorised as easy, we can
naturally expect such complexity not to be there that it brings which
though is small, is not negligible.
This was, hence, a dilemma and my request is to add such a sample case for
reference so as to effectively communicate the motto of the problem
statement.
The problem did not state if brackets need to be opened and closed in same
order in nested condition adhering to the general rules followed.
Kindly go through the discussion too, the issue is elaborately voiced there.

Regards,
Souvik Das

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've submitted your feedback to the team. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
