### ISSUE TITLE
Grammar in Question - 2503. Maximum Number of Points From Grid Queries

### ISSUE THREAD

**Issue by PyroGenesis** [LeetCode-Feedback/LeetCode-Feedback#12211]
#### Your LeetCode username
burhanlakda

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The explanation for example 2 should say "cannot" OR "can't" instead of "can not"

> Explanation: We **can not** get any points because the value of the top left cell is already greater than or equal to 3.

#### Screenshots

![image](https://user-images.githubusercontent.com/17806916/223194844-8adbbf5e-ae57-4009-ab68-595268c7b942.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

The dictionary defines cannot as “can not.” The word and the phrase mean exactly the same thing: both are the negation of the very common and useful verb can. The only difference between them is that the closed form, cannot, is much more common.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
