### ISSUE TITLE
Wrong expected result in the "Remove element" problem

### ISSUE THREAD

**Issue by dyaraev** [LeetCode-Feedback/LeetCode-Feedback#1221]
#### Your LeetCode username
dimanello

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The question is related to the "Remove element" problem which is described on [this page](https://leetcode.com/explore/featured/card/fun-with-arrays/526/deleting-items-from-an-array/3247/). In some cases executions of custom test cases produce wrong expected results. To reproduce the case the following parameters can be used:
```
nums = [0,1,2,2,3,0,4,2],
val = 2
```
For these input parameters my result is [0,1,3,0,4] and the expected result is [0,1,4,0,3]. So my result is different from the expected result but my submission is accepted. It looks like the code which executes custom test cases and the one which verifies submissions have different logic. And most probably the former has a bug.

#### Code you used for Submit/Run operation
```scala
object Solution {
  def removeElement(nums: Array[Int], `val`: Int): Int = {
    def remove(rpos: Int, wpos: Int): Int = {
      if (rpos == nums.length) {
        wpos
      } else {
        if (nums(rpos) != `val`) {
          if (rpos != wpos) nums(wpos) = nums(rpos)
          remove(rpos + 1, wpos + 1)
        } else {
          remove(rpos + 1, wpos)
        }
      }
    }
    
    if (nums.length > 0) {
      remove(0, 0)
    } else {
      0
    }
  }
}
```

#### Language used for code
Scala

#### Expected behavior

- For input parameters nums = **[0,1,2,2,3,0,4,2]**, val = **2** the expected result should be **[0,1,3,0,4]**.
- When the expected results and the actual test case execution results are not equal, submissions should not be accepted.

**Comment by lc-kay** [comment]
Hi @dyaraev 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by dyaraev** [comment]
Unfortunately, I have not noticed that the order of elements in the the result can be changed. The issue can be closed.
