### ISSUE TITLE
428. Serialize and Deserialize N-ary Tree - Not specified constraint or missing test case

### ISSUE THREAD

**Issue by qwazimoda** [LeetCode-Feedback/LeetCode-Feedback#1222]
#### Your LeetCode username
dyurchyk

#### Category of the bug
- [ x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
"428. Serialize and Deserialize N-ary Tree" question has no constraint for node values. But the fastest accepted Java solution works only for range [-48, 65488] with exclusion of -13 (since it is '#' - '0').
The expected results are incorrect for negative values.

#### Code you used for Submit/Run operation
The accepted code with a problem:
```
// Two Sum
class Codec {
    // NOTE: this solution works for range [-48, 65488] with exclusion of -13
    
    // Encodes a tree to a single string.
    public String serialize(Node root) {
        if (root == null) return "";
        
        StringBuilder sb = new StringBuilder();
        doSerialize(root, sb);
        return sb.toString();
    }
    
    private void doSerialize(Node root, StringBuilder sb) {
        sb.append((char)(root.val+'0'));
        for (Node child: root.children) {
            doSerialize(child, sb);
        }
        
        sb.append("#");
    }
	
    // Decodes your encoded data to tree.
    public Node deserialize(String data) {
        if (data.equals("")) return null;
        return doDeserialize(data, new int[]{0});
    }
    
    private Node doDeserialize(String data, int[] idx) {
        Node root = new Node(data.charAt(idx[0])-'0', new ArrayList());
        idx[0]++;
        while (data.charAt(idx[0]) != '#') {
            root.children.add(doDeserialize(data, idx));
        }
        idx[0]++;
        return root;
    }
}
```

#### Language used for code
Java

#### Expected behavior
The question should have node value constraint, f.e. [0, 10^4]

Or as alternative test cases should be improved, f.e:
[-49,null,-13,-1,65488,65536]

#### Screenshots
![image](https://user-images.githubusercontent.com/19476580/96186790-eec5e100-0f09-11eb-8804-01590b2c1d8e.png)
![image](https://user-images.githubusercontent.com/19476580/96187192-93482300-0f0a-11eb-987d-a83ce336ecce.png)

**Comment by lc-kay** [comment]
Hi @qwazimoda 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @qwazimoda 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
