### ISSUE TITLE
Missing Test Case - 2187. Minimum Time to Complete Trips

### ISSUE THREAD

**Issue by manish831** [LeetCode-Feedback/LeetCode-Feedback#12229]
#### Your LeetCode username
ManishAgrahari

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

In the question, there should be a testcase in which time =[10000000, 10000000] and totalTrips = 10000000.
These type of testcases are not covered where time[i] equals to given constraints.

#### Code you used for Submit/Run operation

// 2187. Minimum Time to Complete Trips
```
class Solution {
public:
    long long helper(vector<int>&v, long long time){
        long long x = 0;
        for(long long i = 0; i<v.size() ; i++){
            long long tmp = time/v[i];
            x += tmp;
        }
        // cout<<x<<endl;
        return x;
    }
    long long minimumTime(vector<int>& time, int tT) {
        long long ans = 0;
        long long n = time.size();
        long long ok = time[0];
        if(n == 1){
            ok *= tT;
            return ok;
        }
        long long start = 1, end  = 100000000000;
        long long res = 0;
        while(start <= end){
            long long mid = start + (end - start)/2;
            long long trip = helper(time, mid);
            if(trip >= tT)
            {
                res = mid;
                end = mid-1;
            }
            else if(trip < tT){
                start = mid+1;
            }
            else
                end = mid-1;
        }
        return res;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The code which i submitted is wrong because it's not handling the case when time[i] is equals to given constraints.
Like for testcase 
**Input:**
time =
[10000000, 10000000]

My code got submitted but shows wrong answer.
#### Screenshots

-Screenshot 1 (My code gives wrong answer for this testcase)
![image](https://user-images.githubusercontent.com/74316266/223398716-c640d0e2-fc91-4960-9433-ee555b48018b.png)

-Screenshot 2 (But my code got Accepted).

![image](https://user-images.githubusercontent.com/74316266/223399272-0f4d4097-5ad3-4641-a051-f618826454dc.png)

![image](https://user-images.githubusercontent.com/74316266/223399381-ff2e07a3-e403-4a70-b483-de94b7e7b4e1.png)

#### Additional context

1. Add more testcases where all the elements of time[i] exactly equals to upper constraints and size of **time** array more than 1.

##My Accepted Submission Link : [https://leetcode.com/problems/minimum-time-to-complete-trips/submissions/910745097/](url)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
