### ISSUE TITLE
Missing Test Case - 1599. Maximum Profit of Operating a Centennial Wheel

### ISSUE THREAD

**Issue by ZHANGZHENG3210** [LeetCode-Feedback/LeetCode-Feedback#12226]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
hu-su-t

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述** 
我的代码提交后，通过了所有的测试案例。我自己编写了一个自测案例，测试未通过。

**你使用的语言**
Java

**你提交或者运行的代码**
```
class Solution { 
    public int minOperationsMaxProfit(int[] customers, int boardingCost, int runningCost) {
        int maxProfitIndex = -1;
        //用顾客数组得到每次轮动可以上去的人的数组
        int allCus = 0;
        int use = 0;
        int wait = 0;
        int count = 0;
        for (int customer : customers) {
            count++;
            allCus = wait + customer;
            if (allCus >= 4) {
                use = 4;
            } else {
                use = allCus;
            }
            wait = allCus - use;
            if (use * boardingCost - runningCost > 0) {
                maxProfitIndex = count;
            }
        }
        if ((wait/4)*4*boardingCost - (wait/4)*runningCost > 0){
            maxProfitIndex = count + (wait/4);
        }
        if (wait%4*boardingCost - runningCost > 0){
            maxProfitIndex = maxProfitIndex + 1;
        }
        return maxProfitIndex;
    }
}
```

### **期望行为**

期望：自测通过，输出与预期结果一致

**屏幕截图**

<img width="535" alt="image" src="https://user-images.githubusercontent.com/41222384/223370526-8006ffcc-8e50-4596-82f6-8609b4708e0f.png">

<img width="791" alt="image" src="https://user-images.githubusercontent.com/41222384/223370982-3b855114-146d-4024-ad32-f3b799fa8c85.png">

**额外的上下文**
这是发现异常的自测案例
自测案例
customers =
[4,0,0,3]
boardingCost =
2
runningCost =
4

**Comment by feiceh** [comment]
你好，如果出现测试用例结果和提交结果不一致的情况，可以再仔细检查并调试一下代码，或点击这里：「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」 获得更多帮助。

同时也可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
