### ISSUE TITLE
Missing Test Case - 1528. Shuffle String

### ISSUE THREAD

**Issue by KARANPANWAR10** [LeetCode-Feedback/LeetCode-Feedback#12223]
#### Your LeetCode username

karanpanwar

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

problem is in Question 1528 Testcase.
Testcase 1 mentioned there is wrong. Output there is mentioned -"leetcode" while the correct output should be "leetcdoe".
Problem is in Testcase mentioned below:
Input: s = "codeleet", indices = [4,5,6,7,0,2,1,3]
Output: "leetcode"
Explanation: As shown, "codeleet" becomes "leetcode" after shuffling.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    string restoreString(string s, vector<int>& indices) {
       string ans="";
        int n = indices.size();
        for(int i=0;i<n;i++){
            ans.push_back(s[indices[i]]);
        }
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

 Either the integer array **_indices_** should be **[4,5,6,7,0,1,2,3]** or **Output** should be **"leetcdoe**" for question's testcase to be correct.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
