### ISSUE TITLE
Missing Test Case - 8. String to Integer (atoi)

### ISSUE THREAD

**Issue by NarzullayevS** [LeetCode-Feedback/LeetCode-Feedback#12228]
#### LeetCode username
https://leetcode.com/narzullayev_s/

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
-  Missing Test Cases 

#### Description of the bug

https://leetcode.com/problems/string-to-integer-atoi/
```["+-12"]``` => test
Actually the answer is ```-12```, but we are being shown ```0``` .

#### Code you used for Submit/Run operation

```
class Solution:
    def myAtoi(self, s: str) -> int:
        s = s.lstrip()
        sign = 1
        if s and s[0] in ['-', '+']:
            if s[0] == '-': sign = -1
            s = s[1:]
        num = 0
        for c in s:
            if c.isdigit(): num = num * 10 + int(c)
            else:break
        num *= sign
        num = max(-2**31, min(num, 2**31 - 1))
        return num
    
# a = Solution()
# print(a.myAtoi("+-12"))
```

#### Language used for code
```Python```

#### Expected behavior

input: ```["+-12"]```
output: ```-12```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
