### ISSUE TITLE
Missing test case- 1296 Divide Array in Sets of K Consecutive Numbers. Wrong solution accepted

### ISSUE THREAD

**Issue by anishrajan25** [LeetCode-Feedback/LeetCode-Feedback#1223]
#### Your LeetCode username

anishrajan25

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The solution that beats 100% of the JAVA submissions is not the correct solution as it fails the following test case.

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean isPossibleDivide(int[] nums, int k) {
        int arr[] = new int[k];
        Arrays.fill(arr, 0);
        if (k == 3 && nums[1] == 4) { return false; }

        for(int i = 0 ; i < nums.length ; i++) {
            arr[nums[i]%k]++;
        }
        int count = arr[0];
        for(int i = 1 ; i < k ; i++) {
            if(arr[i] != count)
                return false;
        }
        return true;
    }
}
```

#### Language used for code

JAVA

#### Expected behavior

The code should have returned the result as 'false' but it is returning 'true'.
The solution should not have been accepted since it fails the mentioned test case.
###### Input:
```
nums = [x1, x2, x3, x4, ..... , xn]
k = n
```
where ``` x1, x2, x3, x4, ..... , xn``` are non-consecutive integers and ``` k = nums.length ``` and ``` x1 % k = 0 ```, ``` x2 % k = 1 ```, ``` x3 % k = 2 ``` and ``` xn % k = n - 1 ```
In such test cases the solution fails.

#### Screenshots

![Screenshot (123)](https://user-images.githubusercontent.com/56666741/96190037-2a3eca80-0f5f-11eb-89e4-8e395d1a7f88.png)
![Screenshot (122)](https://user-images.githubusercontent.com/56666741/96190079-3dea3100-0f5f-11eb-9143-fe414caf3dcd.png)

#### Additional context

* Link to the problem: https://leetcode.com/problems/divide-array-in-sets-of-k-consecutive-numbers/
* Link to the Submission: https://leetcode.com/submissions/detail/409199376/ (The code that takes 2ms to run and beats 100% of JAVA submissions)

**Comment by lc-kay** [comment]
Hi @anishrajan25 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @anishrajan25 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
