### ISSUE TITLE
Invalid Testcase - 1501. Countries You Can Safely Invest In

### ISSUE THREAD

**Issue by juangraa** [LeetCode-Feedback/LeetCode-Feedback#12235]
#### Your LeetCode username
 juangraa

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
Every time I try to run a query, I always get the same message: "Phone number of the person with id = 3 doesn't exist in the Country table". The message appears no matter what kind of query you try to run

#### Code you used for Submit/Run operation

```
SELECT * FROM Person
```

#### Language used for code
MySQL 

#### Expected behavior
It should return the result of my query + a DIFF with the expected result

#### Additional context
The problem is part of the "SQL II" Study Plan

**Comment by juangraa** [comment]
Screenshot:
![Screenshot 2023-03-07 at 5 43 15 PM](https://user-images.githubusercontent.com/118077431/223570778-83c37f67-d189-4b87-87ac-c3993ab3e03c.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The test case that you use.
The above code received Wrong Answer after submission: https://leetcode.com/submissions/detail/911646642/

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by juangraa** [comment]
Hi @LC-Pam,

Thank you for looking into this.

I'm using Testcase 1:

 
![Screenshot 2023-03-08 at 2 24 27 PM](https://user-images.githubusercontent.com/118077431/223823186-5c0aa79a-1891-4be3-990c-fb4d55aba19f.png)

**Comment by LC-Pam** [comment]
Sorry for the late reply.
 
After checking, it is a bug with the new vision.
 
We already reported the "Invalid Testcase" issue to the developer team.
 
In the meantime, please revert to the old vision when you solve this problem and use the format below:
 
{"headers":{"Person":["id","name","phone_number"],"Country":["name","country_code"],"Calls":["caller_id","callee_id","duration"]},"rows":{"Person":[[3,"Jonathan","051-1234567"],[12,"Elvis","051-7654321"],[1,"Moncef","212-1234567"],[2,"Maroua","212-6523651"],[7,"Meir","972-1234567"],[9,"Rachel","972-0011100"]],"Country":[["Peru","051"],["Israel","972"],["Morocco","212"],["Germany","049"],["Ethiopia","251"]],"Calls":[[1,9,33],[2,9,4],[1,2,59],[3,12,102],[3,12,330],[12,3,5],[7,9,13],[7,1,3],[9,7,1],[1,7,7]]}}
