### ISSUE TITLE
Description improvement. Cracking the Safe

### ISSUE THREAD

**Issue by xelplogoog** [LeetCode-Feedback/LeetCode-Feedback#12236]
#### Your LeetCode username
c4tdog

in example #2 you have used '01100' value twice. I think it would be better to use:
Thus "01100" will unlock the safe. "10011" and "11001" would also unlock the safe.

![image](https://user-images.githubusercontent.com/2188302/223537051-3c6e2d3f-3640-4622-bdb4-0f24b970842b.png)

**Comment by LC-Pam** [comment]
![Screen Shot 2023-03-08 at 2 08 21 PM](https://user-images.githubusercontent.com/103138242/223814434-d0becc7e-82a4-453a-960c-d83e3d9bf814.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
