### ISSUE TITLE
422. Valid Word Square Solution code comment wording mismatch

### ISSUE THREAD

**Issue by StrawHatDragon100** [LeetCode-Feedback/LeetCode-Feedback#12245]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I think the comment in code for Approach 2 is mis matched.
It is 
```
                // charPos (curr 'row' word) is bigger than column word, or
                // wordNum (curr 'column' word) is bigger than row word, or 
                // characters at index (wordNum,charPos) and (charPos,wordNum) are not equal.
```
while it should be
```
                // charPos (curr 'column' word) is bigger than row word, or
                // wordNum (curr 'row' word) is bigger than column word, or 
                // characters at index (wordNum,charPos) and (charPos,wordNum) are not equal.
```

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

![image](https://user-images.githubusercontent.com/19656900/223623853-ae29021b-438b-415d-87ff-57f068cef68a.png)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

charPos represent the index (position) of character of ith word.
In code I have compared charPos with words array's size. words array's each word represent one row (we write words in row-wise manner in matrix).

So words array's size will represent the number of rows, i.e. the size of word represented by column. As in matrix we have 4 rows means the column's word will have size 4 as each character is in each row.

So charPos is row's word's size
and words.size() is col's word's size

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
