### ISSUE TITLE
Missing Test Case - 121. Best Time to Buy and Sell Stock

### ISSUE THREAD

**Issue by goyalkriti17** [LeetCode-Feedback/LeetCode-Feedback#12241]
#### Your LeetCode username
[goyalkriti17](https://leetcode.com/goyalkriti17/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
 The bug with the existing test cases is that it does not test a test case with the lowest and highest values towards the end of the array. The Test Case with prices prices = [7,2,5,3,6,4,1,9] gave a wrong result with my code, while the existing test cases passed.

#### Code you used for Submit/Run operation

```
// Best Time to Buy and Sell Stock
class Solution {
    public int maxProfit(int[] prices) {
        int left = 0; 
        int right = 1;
        int max_profit = 0;
        while(right < prices.length) { 
            int profit = prices[right] - prices[left];
            if (prices[left] < prices[right]) {
                if(profit> max_profit) {
                    max_profit = profit;   
                }
            } else {
                left ++;
            }
            right++;
        }
        return max_profit;        
    }
}
```

#### Expected behavior
A testcase with prices = [7,2,5,3,6,4,1,9] is expected to have an Output: 8.
However, when run with the above code, returned a wrong Output of 4. This happened because the existing testcases did not cover a scenario when lowest followed by highest occur towards the end of the array. 

#### Screenshots
<img width="723" alt="Screen Shot 2023-03-07 at 8 58 38 PM" src="https://user-images.githubusercontent.com/19917887/223599701-4e04fc78-3fb4-4a41-951a-38bb2e7e6616.png">
<img width="726" alt="Screen Shot 2023-03-07 at 8 58 17 PM" src="https://user-images.githubusercontent.com/19917887/223599726-920f5c3a-e575-4d76-8f4c-6102642ae690.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output values.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!
