### ISSUE TITLE
Kth Largest Sum in a Binary Tree

### ISSUE THREAD

**Issue by nagarajankarthik** [LeetCode-Feedback/LeetCode-Feedback#12242]
#### Your LeetCode username

nkarthik3092

#### Category of the bug
- [- ] Language

#### Description of the bug

When solving the problem '2583. Kth Largest Sum in a Binary Tree', calling the size() function on an uninitialized vector seems to return an arbitrarily large integer. However, it should return zero as per the C++ standard.

#### Code you used for Submit/Run operation

```
// Kth Largest Sum in a Binary Tree
class Solution {
public:
   vector<long long> ls ;
    
    void getLevelSum(TreeNode * tn, int level) {
        int cn = tn -> val;

 // Should be zero when this function is first called but it is a large positive integer
        cout << ls.size() << endl;

        // The test for the if statement fails resulting in a runtime error. 
        if (level <= (ls.size() - 1)) ls[level] += cn;
        else ls.push_back(cn);   

        
 
        if (tn->left != nullptr) getLevelSum(tn->left, level + 1);
        if (tn -> right != nullptr) getLevelSum(tn->right, level + 1);
        return;
    } 
    
    
    long long kthLargestLevelSum(TreeNode* root, int k) {

        getLevelSum(root,0);
        if (ls.size() < k) return -1;
        else {            
            sort(ls.begin(),ls.end(), greater<long long>());          
            //nth_element(begin(ls),begin(ls) + k - 1, end(ls), greater<>());
            return ls.at(k-1);
        }
        
    }
};
```

#### Language used for code

C++

#### Expected behavior

When the getLevelSum function is first called, the cout statement should result in '0' being written to stdout whereas '18446744073709551615' is obtained instead.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
