### ISSUE TITLE
1669. Merge In Between Linked Lists - Wrong Submission Test Case

### ISSUE THREAD

**Issue by rohan-chandrashekar** [LeetCode-Feedback/LeetCode-Feedback#12243]
#### Your LeetCode username
rohan_chandrashekar

#### Category of the bug
- [ ] Solution

#### Description of the bug
Solution of the last test case for submission (61) is incorrect. There are 2 lists given: list1 and list2. The nodes an and b are present in list1. All the nodes from a to b must be replaced with the nodes of list2. 

The resultant list must list1 with all nodes from a to b replaced with list2.

However the expected output for the resultant list is incorrect. The list does not have the nodes replaced in correct order.

#### Code you used for Submit/Run operation

```
// Merge In Between Linked Lists

class Solution
{
public:
    ListNode* mergeInBetween(ListNode* list1, int a, int b, ListNode* list2)
    {
        struct ListNode* p = list1;
        while(p->next->val!=a)
        {
            p = p->next;
        }
        struct ListNode* x = p->next;
        p->next = list2;
        while(x->val!=b)
        {
            x = x->next;
        }
        x = x->next;
        while(list2->next)
        {
            list2 = list2->next;
        }
        list2->next = x;
        return list1;
    }
};
```

#### Language used for code
C++

#### Expected behavior
Given:
list1 = [0,3,2,1,4,5]
int a = 3, int b = 4
list2 = [1000000,1000001,1000002]

The resultant linked list should be:
[0,1000000,1000001,1000002,5]

However the expected output is:
[0,3,2,1000000,1000001,1000002,5]

#### Screenshots

<img width="656" alt="Screenshot 2023-03-08 at 8 25 33 AM" src="https://user-images.githubusercontent.com/79603292/223608142-0477503f-ee8a-446f-8ac4-7e2dac5aa4f3.png">

<img width="707" alt="Screenshot 2023-03-08 at 8 26 02 AM" src="https://user-images.githubusercontent.com/79603292/223608205-3fe7a6d0-8662-474c-a955-85572158444a.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
