### ISSUE TITLE
缺少测试用例: 1599. 经营摩天轮的最大利润

### ISSUE THREAD

**Issue by l00jj** [LeetCode-Feedback/LeetCode-Feedback#12247]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
l00

**Bug 类型**
- [x] 缺少测试用例

**描述**
1599. 经营摩天轮的最大利润
题目的测试问题存在小漏洞，缺少残缺检测，例如这种
[8,0,0,0,0,0,0,0,0,0,0]
5
6
而且当前java推荐最快的方案第一名2ms就是不能通过这个测试的，请删除和添加相关的测试用例。

**你使用的语言**
Java

**期望行为**
建议添加测试用例
[8,0,0,0,0,0,0,0,0,0,0]
5
6
---
答案应为-1

**Comment by feiceh** [comment]
你好，当前题目已更新，积分奖励已发放，请查收
