### ISSUE TITLE
Missing Test Case - 剑指 Offer 47. 礼物的最大价值 LCOF

### ISSUE THREAD

**Issue by wkpasswd20** [LeetCode-Feedback/LeetCode-Feedback#12244]
#### Your LeetCode username
leetcode.cn/u/sfq-s/

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

This question may only be available in the .cn website. https://leetcode.cn/problems/li-wu-de-zui-da-jie-zhi-lcof/.

the given restrictions are
```
0 < grid.length <= 200
0 < grid[0].length <= 200
```
when use 0 as the grid.length or grid[0].length, the expected solutions are wrong and all test cases are considered wrong.

This is the testcase I used. It should not allow it to run. Try it youself.
```
[[1,3,1],[1,5,1],[4,2,1]]
[[]]
[[-1]]
[[1,2,3]]
```

#### Code you used for Submit/Run operation

```
class Solution:
    def maxValue(self, grid: List[List[int]]) -> int:
        m,n = len(grid), len(grid[0])
        if n == 0:
            return 0
        @cache
        def dfs(i,j):
            if i == 0 and j == 0: return grid[0][0]
            if i == 0:
                return dfs(i,j-1) + grid[i][j]
            if j == 0:
                return dfs(i-1,j) +  grid[i][j]
            return max(dfs(i,j-1),dfs(i-1,j)) + grid[i][j]
            
        return dfs(m-1,n-1)
```

#### Language used for code

python3

#### Expected behavior

Testcase with negtive values or zero length array should not be allowed (as it says in the description).

#### Screenshots

![image](https://user-images.githubusercontent.com/98972785/223617830-7f98a02c-535d-4d49-873f-22a129902b56.png)
![image](https://user-images.githubusercontent.com/98972785/223617868-057b5ea9-e65b-4db7-9bfa-5143e52d0f6e.png)

#### Additional context

I guess the standard solution did not handle 0 value conercase well and crashed somehow.

**Comment by feiceh** [comment]
你好，在与相关团队核实后：目前暂不支持添加 validate。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
