### ISSUE TITLE
687. Longest Univalue Path. Golang solution run same test but get different output

### ISSUE THREAD

**Issue by yan-ren** [LeetCode-Feedback/LeetCode-Feedback#1224]
#### Category of the bug
- [ ] Question
- [x] Solution
- [x] Language

#### Description of the bug

I solution question 687. Longest Univalue Path using golang. I find for the same solution, run with the same input, the outputs I get from Submission area and Testcase area are different. I attach a screenshot to show the issue

#### Code you used for Submit/Run operation

```
var result int = 0

func longestUnivaluePath(root *TreeNode) int {
	traverse(root)
	return result
}

func traverse(root *TreeNode) int {
	if root == nil {
		return 0
	}

	leftPath := traverse(root.Left)
	rightPath := traverse(root.Right)

	if root.Left != nil && root.Left.Val == root.Val {
		leftPath += 1
	} else {
		leftPath = 0
	}

	if root.Right != nil && root.Right.Val == root.Val {
		rightPath += 1
	} else {
		rightPath = 0
	}

	result = max(leftPath+rightPath, result)

	return max(leftPath, rightPath)
}

func max(a, b int) int {
	if a >= b {
		return a
	}
	return b
}
```

#### Language used for code

Go

#### Screenshots

![Screenshot from 2020-10-15 23-55-29](https://user-images.githubusercontent.com/12686245/96211706-0bcad600-0f43-11eb-8617-790705ce1811.jpg)

**Comment by lc-kay** [comment]
@yan-ren The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in this article: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-. Please check it out.
