### ISSUE TITLE
62. Unique Paths - Dead link in the Editorial

### ISSUE THREAD

**Issue by jan-polivka** [LeetCode-Feedback/LeetCode-Feedback#12246]
#### Your LeetCode username
jan-polivka

#### Category of the bug
- [ ] Solution

#### Description of the bug
In the Editorial, there is a dead link to Peter Borwein's paper. I assume that it was disabled due to him passing in 2020. Best I could find as a replacement is this: https://www.sciencedirect.com/science/article/abs/pii/0196677485900069

#### Code you used for Submit/Run operation
Not relevant

#### Language used for code
Not relevant

#### Expected behavior
In the Editorial, the text "[The best known algorithm to compute factorial function is done by Peter Borwein](http://www.cecm.sfu.ca/personal/pborwein/PAPERS/P29.pdf)." links to https://www.sciencedirect.com/science/article/abs/pii/0196677485900069 instead

#### Screenshots
Not relevant

#### Additional context
Not relevant

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
