### ISSUE TITLE
2577. Minimum Time to Visit a Cell In a Grid

### ISSUE THREAD

**Issue by claytonjwong** [LeetCode-Feedback/LeetCode-Feedback#12252]
#### Your LeetCode username
`claytonjwong`

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

There's a typo in Example 1 when `t = 7`:

❌ `at t = 7, we move to the cell (2,3). It is possible because grid[1][3] <= 7`
✅ `at t = 7, we move to the cell (2,3). It is possible because grid[2][3] <= 7`

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
