### ISSUE TITLE
Missing Test Case - 1392. Longest Happy Prefix

### ISSUE THREAD

**Issue by sefinehtesfa34** [LeetCode-Feedback/LeetCode-Feedback#12259]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ **Yes**] Missing Test Cases

#### Description of the bug

There is a missing testcase that I would like to contribute.

#### Code you used for Submit/Run operation

```
"vwantmbocxcwrqtvgzuvgrmdltfiglltaxkjfajxthcppcatddcunpkqsgpnjjgqanrwabgrtwuqbrfl"
"gqijndnbohkujykncuooajkhsxcbjbwhrrfgkliqatdndcrpmaqa"
"tzqzalgnxstxzlul"
```

#### Screenshots

![image](https://user-images.githubusercontent.com/88246220/223885593-4b698b01-cffe-43f3-856a-46eff385f764.png)
The code is sumbitted but failed with my own new testcases.

**Comment by sefinehtesfa34** [comment]
Yes,
https://leetcode.com/submissions/detail/911758866/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by sefinehtesfa34** [comment]
Thank you for your response.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
