### ISSUE TITLE
862- Shortest subarray with Sum at least K : Incorrect testcase 

### ISSUE THREAD

**Issue by thakurabhishek7283** [LeetCode-Feedback/LeetCode-Feedback#12258]
this testcase(87) is incorrect as maximum subarray sum in this for window size = 48 is equal to 1531428 which is less than required k (1677903).
correct the answer to 53 or change input array.
[58701 23101 6562 60667 20458 -14545 74421 54590 84780 63295 33238 -10143 -35830 -9881 67268 90746 9220 -15611 23957 29506 -33103 -14322 19079 -34950 -38551 51786 -48668 -17133 5163 15122 5463 74527 41111 -3281 73035 -28736 32910 17414 4080 -42435 66106 48271 69638 14500 37084 -9978 85748 -43017 75337 -27963 -34333 -25360 82454 87290 87019 84272 17540 60178 51154 19646 54249 -3863 38665 13101 59494 37172 -16950 -30560 -11334 27620 73388 34019 -35695 98999 79086 -28003 87339 2448 66248 81817 73620 28714 -46807 51901 -23618 -29498 35427 11159 59803 95266 20307 -3756 67993 -31414 11468 -28307 45126 77892 77226 79433 ]
I solved the question using binary search on answer.

class Solution {
public:
    bool isPossibleSumK(vector<int> &nums, int k, int mid){
        int n = nums.size();
        int len = 0;
        int maxSum = 0, currSum = 0;
        int l = 0, r = 0;
        while(r < mid){
            currSum += nums[r];
            maxSum = max(maxSum, nums[r]);
            r++;
        }
        maxSum = max(maxSum, currSum);
        for(; r<n; r++, l++){
            currSum += nums[r];
            currSum -= nums[l];
            maxSum = max(maxSum, currSum);
            maxSum = max(maxSum, nums[r]);
        }
       return (maxSum >= k);
    }
    int shortestSubarray(vector<int>& nums, int k) {
        int n = nums.size();
        int l = 1, r = n;
        int last = -1;
        while(l <= r){
            int mid = (l+r)>>1;
            if(isPossibleSumK(nums, k, mid)){
                r = mid-1;
                last = mid;
            }
            else{
                l = mid+1;
            }
            
        }
        return last;
    }
};

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by thakurabhishek7283** [comment]
https://leetcode.com/problems/shortest-subarray-with-sum-at-least-k/submissions/911688511/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
