### ISSUE TITLE
Video site can't be reached

### ISSUE THREAD

**Issue by beringin2017** [LeetCode-Feedback/LeetCode-Feedback#12265]
#### Your LeetCode username

beringin2017

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [* ] Missing Test Cases 

#### Description of the bug

see attached screenshot

#### Screenshots

![image](https://user-images.githubusercontent.com/43964202/224005635-34e0bdd7-fc05-4df7-858f-5b2d5cfad54e.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the video appears to be working correctly.
![Screen Shot 2023-03-09 at 1 58 30 PM](https://user-images.githubusercontent.com/103138242/224127566-b4ddd8c3-c49b-4f45-90de-87d60e879319.png)
