### ISSUE TITLE
Missing Test Case - 513. Find Bottom Left Tree Value

### ISSUE THREAD

**Issue by debug-arun** [LeetCode-Feedback/LeetCode-Feedback#12262]
#### Category of the bug
- [ 513. Find Bottom Left Tree Value ] Question
- [  ] Solution
- [ C++ ] Language
- [ 50, 25, 75, 2, null, 55, null, null, 5, null, 59, 4, 6, 58, null, null, null, null, 7, 57, null ] Missing Test Case 

#### Description of the bug

This is a test case where the tree nodes cross each other in last level, yet, the expected answer is shown wrongly.

#### Code you used for Submit/Run operation

```
// Bottom left tree value
/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
class Solution {
public:
    int findBottomLeftValue(TreeNode* root) {
        // level = unordered_map<ListNode*, int>();
        // b = 0; l = 0;
        TreeNode *ans = root;
        // depth(root);
        deque<TreeNode*> q;
        q.push_back(root);
        while(!q.empty()) {
            int size = q.size();
            ans = q.front();
            while(size--) {
                TreeNode *curr = q.front();
                q.pop_front();
                if(curr->left) q.push_back(curr->left);
                if(curr->right) q.push_back(curr->right);
            }
        }
        return ans->val;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Since the nodes are crossing each other, the expected answer for the test case should be `57` whereas it is wrongly being shown as `7`

#### Screenshots

<img width="919" alt="image" src="https://user-images.githubusercontent.com/70369284/223951357-3620d903-e6d6-4cb2-ac2e-87d905da51f2.png">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
