### ISSUE TITLE
Problem 142. Linked List Cycle II. Problem description allows for incorrect test cases.

### ISSUE THREAD

**Issue by niornob** [LeetCode-Feedback/LeetCode-Feedback#12266]
#### Your LeetCode username

nafizishtiaque

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The OJ expects different answers in the following two test cases but algorithmically they are indistinguishable.
```
head = [0,0], pos = [1]
```
and
```
head = [0,0], pos = [0]
```
The problem description should be changed to somehow make such test cases invalid.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
