### ISSUE TITLE
Wrong test case output 142. Linked List Cycle II

### ISSUE THREAD

**Issue by AdityaKulkarni** [LeetCode-Feedback/LeetCode-Feedback#12264]
#### Category of the bug
- [142. Linked List Cycle II ] Question
- [ ] Solution
- [Java ] Language
- [-1,-7,7,-4,19,6,-9,-5,-2,-5 ] Missing Test Cases 

#### Description of the bug
In this test case the cycle connects to position 7 but the testcase answer is shown as 6

#### Code you used for Submit/Run operation

```
public class Solution {
    public ListNode detectCycle(ListNode head) {
        Map<Integer, Integer> countMap = new HashMap<Integer, Integer>();
        Integer index = Integer.valueOf(0);
        ListNode start = head;

        while(head != null && head.next != null){
            if(countMap.containsKey(Integer.valueOf(head.val))){
                for(int i = 0; i < countMap.get(Integer.valueOf(head.val)); i++){
                    start = start.next;
                }
                return start;
            }
            
            countMap.put(Integer.valueOf(head.val), index);
            index++;
            head = head.next;
        }
        return null;
        
    }
}
```

#### Language used for code
Java

#### Expected behavior
The testcase should show output at index 7 instead of 6

#### Screenshots
![Screenshot 2023-03-09 142440](https://user-images.githubusercontent.com/25547842/223972377-fe34cdbc-6117-433b-834f-cb445ee4e719.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
