### ISSUE TITLE
Incomplete question description - 97. Interleaving String

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1226]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

97. Interleaving String
https://leetcode.com/problems/interleaving-string/

The problem description is given as below:
	> Given s1, s2, and s3,
	> find whether s3 is formed by the interleaving of s1 and s2.

Sample Test case:

	Input
		"a"
		"b"
		"a"
	Expected    false

In the above, can s3("a") be formed by the interleaving of s1 ("a") and s2 ("b")?
Yes

Then, why is it the `false`?

Please change the question description as below:

From:    find whether s3 is formed by the interleaving of s1 and s2.
To:         find whether s3 is formed by the interleaving both of s1 and s2 in full.
or something similar

The essence of how the judge is working right now is, when s3 is created by interleaving, we also have to use up all the chars of s1 & s2, which is not given in the description.

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JavaScript

#### Expected behavior

- I read the question in full, created test cases, only to find the question does not mean the same as it says.
- Please complete the question description to save the User time. Most of the User time is spent on writing good tests, that User time should not be wasted.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by manoharreddyporeddy** [comment]
I got 2 messages, under the notification bell icon on the top right of our leetcode user screen:

One of the message reads as below:

	LEETCOIN REWARD
	Valid Content Contribution via Github Channel: https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/97
	LeetCoin
	+100

But
it should read

	LEETCOIN REWARD
	Valid Content Contribution via Github Channel: https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/1226
	LeetCoin
	+100


In other words:

Please change:
1 .

	from: https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/97
	to  : https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/1226

because this GITHUB number is 1226  (but it is wrongly entered as 97 from my subject which is the problem number)

That is, LEETCOIN REWARD is for this issue, https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/1226,   not for https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/97 

2 .
 To avoid these errors in future
Please copy github URL
from the browser address bar.

**Comment by lc-kay** [comment]
@manoharreddyporeddy I apologize for that, it has been fixed.
