### ISSUE TITLE
Mistake in Hint - 1894. Find the Student that Will Replace the Chalk

### ISSUE THREAD

**Issue by ashishkulkarnii** [LeetCode-Feedback/LeetCode-Feedback#12279]
#### LeetCode Username
ashishkulkarnii

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Hints

#### Description of the bug

Hints have mistakes.

Hint 1:
```
Subtract the sum of chalk[i] from k until k is less than that sum
```

Corrected Hint 1:
```
Subtract the sum of chalk from k until k is less than the sum of chalk.
```

Hint 2:
```
Now just iterate over the array if chalk[i] is less thank k this is your answer otherwise this i is the answer
```

Corrected Hint 2:
```
Now iterate over the array. If chalk[i] is less than k, this is your answer. Otherwise, subtract chalk[i] from k and continue.
```

#### Code you used for Submit/Run operation
```
class Solution:
    def chalkReplacer(self, chalk: List[int], k: int) -> int:
        k = k % sum(chalk)
        for i, c in enumerate(chalk):
            if c > k:
                return i
            k -= c
        return 0
```
#### Language used for code
Python3

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
