### ISSUE TITLE
Remove COVID-19 offer to users who have the subscription!

### ISSUE THREAD

**Issue by AjayVV** [LeetCode-Feedback/LeetCode-Feedback#1227]
#### Your LeetCode username
ajayvv

#### Category of the bug
- [x] Site

![image](https://user-images.githubusercontent.com/8503105/96275741-b6003780-0fef-11eb-888f-a6ef89928087.png)
Why does this message to appear to people already having a subscription?

**Comment by lc-kay** [comment]
Hi @AjayVV  ,
Thank you for your time. Upon investigating this issue, we found this issue to be non-content-related (the issue stems from an origin away from the content on this problem); therefore, it's not valid for content contribution reward. 
We encourage you to share more content-related issues here with us for [valid content contribution rewards](https://leetcode.com/discuss/general-discussion/526802/File-Problem-and-Solution-Content-Issues-to-Our-GitHub-Public-Feedback-Repo-Now!). Thank you again for your support and understanding.
