### ISSUE TITLE
Missing Test Case - 635. Design Log Storage System

### ISSUE THREAD

**Issue by typemegan** [LeetCode-Feedback/LeetCode-Feedback#12270]
#### Your LeetCode username

lc207

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Missing test case with repeated input. 
Case e.g.: 
["LogSystem","put","put","put","put","retrieve","retrieve"]
[[],[1,"2017:01:01:23:59:59"],[2,"2017:01:01:22:59:59"],[3,"2016:01:01:00:00:00"],[2,"2017:01:01:22:59:59"],["2016:01:01:01:01:01","2017:01:01:23:00:00","Year"],["2016:01:01:01:01:01","2017:01:01:23:00:00","Hour"]]

#### Code you used for Submit/Run operation

```
type Item struct {
    seconds int64
    id int
}

type LogSystem struct {
    data []Item
}


func Constructor() LogSystem {
    return LogSystem {
        data: []Item{},
    }
}

func convert(timestamp string) []int {
    st := strings.Split(timestamp, ":")
    ans := make([]int, len(st))
    for i, s := range st {
        ans[i], _ = strconv.Atoi(s)
    }
    return ans
}

func toSeconds(st []int) int64 {
    if st[1] > 0 {  
        st[1]--
    }
    if st[2] > 0 {  
        st[2]--
    }
    var ans int64
    ans = int64(st[0]-1999) * (31*12) * 24 * 60 * 60
    ans += int64(st[1]) * 31 * 24 * 60 * 60
    ans += int64(st[2]) * 24 * 60 * 60
    ans += int64(st[3]) * 60 * 60
    ans += int64(st[4]) * 60
    ans += int64(st[5]) 
    return ans
}


func (this *LogSystem) Put(id int, timestamp string)  {
    st := convert(timestamp)    
    seconds := toSeconds(st)
    this.data = append(this.data, Item{seconds, id})    // ❌ doesn't filter repeated input  
}


var graIndex = map[string]int{
    "Year": 0,
    "Month": 1,
    "Day": 2,
    "Hour": 3,
    "Minute": 4,
    "Second": 5,
}

func byGranularity(timestamp string, granularity string, isEnd bool) int64 {
    st := convert(timestamp)
    mask := []int{1999, 0, 0, 0, 0, 0}
    for i:=0; i<=graIndex[granularity]; i++ {
        mask[i] = st[i]
    }
    if isEnd { 
        mask[graIndex[granularity]]++  
    }
    seconds := toSeconds(mask)
    return seconds 
} 

func (this *LogSystem) Retrieve(start string, end string, granularity string) []int {
    startSeconds := byGranularity(start, granularity, false)
    endSenconds := byGranularity(end, granularity, true)
    ans := []int{}
    for _, item := range this.data {
        if item.seconds >= startSeconds && item.seconds < endSenconds {
            ans = append(ans, item.id)
        }
    }
    return ans
}
```

#### Language used for code

Golang

#### Expected behavior

The solution above shouldn't be accepted. 

#### Screenshots

<img width="1361" alt="image" src="https://user-images.githubusercontent.com/12883950/224034186-3499500b-7f08-46b1-b228-32778df72477.png">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
