### ISSUE TITLE
Missing Test Case - 20. Valid Parentheses

### ISSUE THREAD

**Issue by cbutcher318** [LeetCode-Feedback/LeetCode-Feedback#12276]
#### Your LeetCode username

[cbutcher318](https://leetcode.com/cbutcher318/)

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug

Current test cases do not sufficiently test the code against the submission expectation

#### Code you used for Submit/Run operation

```
/**
 * @param {string} s
 * @return {boolean}
 */
var isValid = function(s) {


  //for loop to cycle through the string and check if an open character is followed by a closed character
  //if "(" and next is ")" then true
  for (let i = 0; i < s.length + 1; i++) {
      if (s[i] == "(") {
          if (s[i+1] != ")") {
              return false;
          }
      }
      if (s[i] == "[") {
          if (s[i+1] != "]") {
              return false;
          }
      }
      if (s[i] == "{") {
          if (s[i+1] != "}") {
              return false;
          }
      }
  }
  return true;
};
```

#### Language used for code

Javascript

#### Expected behavior

My code passes with the three default test cases, but does not pass the submission test.

> Example 1:
> Input: s = "()"
> Output: true
> 
> Example 2:
> Input: s = "()[]{}"
> Output: true
>
> Example 3:
> Input: s = "(]"
> Output: false

An additional test case, such as 's = "{[]}"' would better test the code

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
