### ISSUE TITLE
705. Design HashSet - Fix Grammar

### ISSUE THREAD

**Issue by AjayVV** [LeetCode-Feedback/LeetCode-Feedback#1228]
#### Your LeetCode username
ajayvv

#### Category of the bug
- [x] Solution

#### Few grammatical mistakes in solution (bold):

1. hash function: the goal of the hash function is to assign an address to store a given value. Ideally, each unique value should have **an unique** hash value.  _("a unique", not "an")_

2. Overall, there are **several strategy** to resolve the collisions: _(several strategies)_

3. for values with the same hash key, we keep them in a bucket, and each bucket is independent **from** each other. _("of" or "to")_

4. One **could** try these exercises first, and then combine them together to get a full implementation of BST. _("should")_

**Comment by lc-kay** [comment]
Hi @AjayVV 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @AjayVV 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
