### ISSUE TITLE
Missing Test Case - 13. Roman to Integer

### ISSUE THREAD

**Issue by AbhiSeCode** [LeetCode-Feedback/LeetCode-Feedback#12283]
#### Your LeetCode username

[AbhiSeCode](https://leetcode.com/AbhiSeCode/)

#### Category of the bug
- [ ] Question
- [* ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

 Converting "DCXXI" from roman to numeric should be 621 but the test case failed because it is expecting 421 as a solution. 
 According to rule C before D is considered as subtraction not D before C.  
 

#### Code you used for Submit/Run operation

```
/**
 * @param {string} s
 * @return {number}
 */
var romanToInt = function(s) {
    if(!s.length || s.length > 15) return
    let romanStr = {"I": 1, "V": 5, "X": 10, "L":  50, "C": 100, "D": 500, "M": 1000}
    let total = 0
    let tempValue =''
    for(let i = 0; i < s.length; i++){
        let char = s[i]
        if(tempValue){
            if(char == 'V' || char == "X" || char == "D" || char == "M" || char == "L" || char == "C"){
                total += romanStr[char] - romanStr[tempValue]
            }else{
                total +=romanStr[tempValue] + romanStr[char]
            }
            tempValue = ''
        }
        else if(char == "I" || char == "X" || char == "C"){
            if(i == (s.length-1)) total += romanStr[char]
            tempValue = char
        }
        else{
            total+=romanStr[char]
        }
    }
    return total
};
```

#### Language used for code

JavaScript

#### Expected behavior

Result should be 621 and not 421 as provided.

**Comment by stormsunshine** [comment]
The expected result is 621. Where do you see 421 as the expected result?

**Comment by AbhiSeCode** [comment]
My bad I read situation wrong,  there was issue in my code closing this issue.
