### ISSUE TITLE
Animation mentioned in editorial is missing

### ISSUE THREAD

**Issue by Meowzz95** [LeetCode-Feedback/LeetCode-Feedback#12298]
#### Your LeetCode username
jjzzzmd

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

https://leetcode.com/problems/convert-sorted-list-to-binary-search-tree/editorial/

The animation mentioned here (see the attached screenshot) is missing
<img width="955" alt="image" src="https://user-images.githubusercontent.com/22430379/224473312-09fe9eef-c640-4b1b-93d0-328803f1bbb3.png">

---

Looks like it is not a loading issue (no content found after the sentence and before the sample code iframe)
<img width="587" alt="image" src="https://user-images.githubusercontent.com/22430379/224473405-38d4c5cb-3e75-40c4-92e1-bee59ca8bff6.png">

#### Code you used for Submit/Run operation

NA

#### Language used for code

NA

#### Expected behavior

The animation should be shown

#### Screenshots

Attached above

#### Additional context

NA

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
