### ISSUE TITLE
109. Convert Sorted List to Binary Search Tree - Missing Animation in Appraoch 3

### ISSUE THREAD

**Issue by StrawHatDrag0n** [LeetCode-Feedback/LeetCode-Feedback#12296]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

There is no animation in approch 3

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

![image](https://user-images.githubusercontent.com/19656900/224461015-d04bbd63-531d-47c4-9215-a6a54227e34f.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
