### ISSUE TITLE
1618. Maximum Font to Fit a Sentence in a Screen

### ISSUE THREAD

**Issue by soitbegins201651** [LeetCode-Feedback/LeetCode-Feedback#1229]
** Bug 类型**
1618. Maximum Font to Fit a Sentence in a Screen

**描述**
点进去后没有题目。

**你使用的语言**
C

**你提交或者运行的代码**
无。

**期望行为**
期望能有题目显示。

**额外的上下文**
1618题没有题目显示。请抓紧解决。

**Comment by feiceh** [comment]
感谢反馈，当前看到题目显示正常的，请问「点进去后没有题目」具体是什么现象呢？能否提供一下页面截图以便技术定位。
