### ISSUE TITLE
Could the time complexity analysis of one of the pseudocode be wrong in LeetCode Two Pointers chapter?

### ISSUE THREAD

**Issue by Asish-Kumar** [LeetCode-Feedback/LeetCode-Feedback#12299]
On the page where LeetCode explains the concept of Two Pointers, there's a pseudocode given, and below that the time complexity of the pseudocode is told as `O(n+m)`. Now, I am not an expert on analyzing the time complexities but shouldn't the time complexity be `O(n if n>m else m)`?

Here's a screenshot of the pseudocode I am referring to:

![image](https://user-images.githubusercontent.com/39800938/224476165-d7e55eb6-ef7f-4941-b083-f783ed17e253.png)

And here's the link to the chapter:
https://leetcode.com/explore/interview/card/leetcodes-interview-crash-course-data-structures-and-algorithms/703/arraystrings/4501/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

Conditional statements do not belong inside time complexities. n and m are independent so we use both.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
