### ISSUE TITLE
Incorrect judge in "Insert Delete GetRandom O(1)" (the last task of Hash Map explore card)

### ISSUE THREAD

**Issue by ilya-chumakov** [LeetCode-Feedback/LeetCode-Feedback#12292]
#### Your LeetCode username
ilya-chumakov

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Problem https://leetcode.com/explore/learn/card/hash-table/187/conclusion-hash-table/1141/
Judge calls `GetRandom` on a collection of >1 non-repeated element and compares its output, what doesn't make sense.

#### Code you used for Submit/Run operation

```
public class RandomizedSet
{
    private readonly HashSet<int> _map = new();
    
    public bool Insert(int val)
    {
        return _map.Add(val);
    }

    public bool Remove(int val)
    {
        return _map.Remove(val);
    }

    public int GetRandom()
    {
        int randomIdx = Random.Shared.Next(0, _map.Count - 1);
        return _map.ElementAt(randomIdx);
    }
}
```

#### Expected behavior
`GetRandom` output is not checked or so.

#### Screenshots

![image](https://user-images.githubusercontent.com/11814549/224404991-c5008bed-3edb-4285-81a5-09e47f7af235.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
