### ISSUE TITLE
[P287] ExampleAnimation in Solution should be updated to remove confusion

### ISSUE THREAD

**Issue by mdtareque** [LeetCode-Feedback/LeetCode-Feedback#123]
**What kind of the bug**
- [ ] problem
- [x] solution
- [ ] language

**Describe the bug**
In *Approach #3 Floyd's Tortoise and Hare (Cycle Detection) [Accepted]*, the example used in the animation is creating confusion to many readers (check comment section of that solution).

There are 2 parts to this solution, the first is to find the cycle and second is to find the intersection.

The example used has the duplicate number when the first part of the algo ends. 

Hence, the example in the animation should be updated to be clear/precise to avoid confusion in mind of readers.

**Comment by CooperCooperCooper** [comment]
Hi @mdtareque,
Thank you for reaching out to us! I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @mdtareque,
Thank you for the contribution, Approach3 Floyd's Tortoise and Hare is completely rewritten. Please share your username, your Github info (as a form of verification) and this issue to support@leetcode.com to receive the content issue contribution reward. If you have any questions, please don't hesitate to let me know. Thank you.
