### ISSUE TITLE
Missing Test Case - 8. String to Integer (atoi)

### ISSUE THREAD

**Issue by NarzullayevS** [LeetCode-Feedback/LeetCode-Feedback#12304]
#### Your LeetCode username

https://leetcode.com/narzullayev_s/

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
-  Missing Test Cases 

https://leetcode.com/problems/string-to-integer-atoi/
#### Description of the bug

```s = "Hello   42 ok" ``` test. Output is ```0``` but, correct answer is ```42```

#### Code you used for Submit/Run operation

```
class Solution:
    def myAtoi(self, s: str) -> int:
        s = s.lstrip()
        sign = 1
        if s and s[0] in ['-', '+']:
            if s[0] == '-':
                sign = -1
            s = s[1:]
        num = 0
        for c in s:
            if c.isdigit():
                num = num * 10 + int(c)
            else:
                break
        num *= sign
        num = max(-2**31, min(num, 2**31 - 1))
        return num
```

#### Language used for code
```Python```

#### Expected behavior

Input: ```"Hello   42 ok"```
Output: ```0```
Expected: ```0```
Verdict: ```Accepted```
Correct answer: ```42```

#### Screenshots

![image](https://user-images.githubusercontent.com/95655675/224511476-7a98b9a6-9d74-4912-a6a1-35d0d668482c.png)

**Comment by stormsunshine** [comment]
The first character is 'H', which is not a space or a digit, so the remaining digits are ignored. Why do you think the correct answer should be 42?

**Comment by NarzullayevS** [comment]
> 

Aaa,  sorry. I'm lost :))
