### ISSUE TITLE
1501 Countries You Can Safely Invest In

### ISSUE THREAD

**Issue by romex003** [LeetCode-Feedback/LeetCode-Feedback#12306]
it is giving error Invalid Testcase   " Phone number of the person with id = 3 doesn't exist in the Country table." 

Please check resolve the error in test case.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by romex003** [comment]
I used MySql

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
