### ISSUE TITLE
Missing Test Case - 1528. Shuffle String

### ISSUE THREAD

**Issue by amitgautam1994** [LeetCode-Feedback/LeetCode-Feedback#12301]
#### Your LeetCode username
amitgautam1994

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The test case 1 output is incorrect. In the test case s = "codeleet", indices = [4,5,6,7,0,2,1,3] which will give the output "leetcdoe" but according to question it will "leetcode" which is not correct. Please update the test case as I'm not able to submit the question.

#### Code you used for Submit/Run operation

```
// Shuffle String
class Solution:
    def restoreString(self, s: str, indices: List[int]) -> str:
        text = ''
        for n in indices:
            text = text + s[n]
        return text
```

#### Language used for code
Python

#### Expected behavior
The expected output should be "leetcdoe".  as the indexes are incorrect in input.

**Comment by stormsunshine** [comment]
The image in the example is quite clear. Could you please check your understanding to the problem?

![image](https://user-images.githubusercontent.com/12067364/224527225-6577f150-4548-49bc-ae89-841faec9d085.png)

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
