### ISSUE TITLE
23. Merge k Sorted Lists

### ISSUE THREAD

**Issue by Mitternachtsmond** [LeetCode-Feedback/LeetCode-Feedback#12307]
#### Your LeetCode username

nichamp

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the submissions of C++ sorted on runtime, the best solution has manipulated the **main function** and has solved the problem.

#### Language used for code

C++

#### Expected behavior

The user should not be able to change the main function since it's sort of cheating.

#### Screenshots

<img width="463" alt="image" src="https://user-images.githubusercontent.com/85838936/224529200-2a2843e4-7f59-42ba-a20b-c0fd16dcaf46.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Mitternachtsmond** [comment]
My code submission link is [here](https://leetcode.com/problems/merge-k-sorted-lists/submissions/914678223/)
(The above submission is taken from fastest submission for the question)
This should be accepted as changing the main function is wrong.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've submitted your feedback to the team. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by Mitternachtsmond** [comment]
Are there no rewards for pointing out this error?
