### ISSUE TITLE
Problem Statement Improve - 1894. Find the Student that Will Replace the Chalk

### ISSUE THREAD

**Issue by vivekiet22** [LeetCode-Feedback/LeetCode-Feedback#12309]
#### Your LeetCode username
vivekiet22

#### Category of the bug
- [ ] Question

#### Description of the bug

In the problem statement 
``However, if the current number of chalk pieces is strictly less than chalk[i], then the student number i will be asked to replace the chalk.
Return the index of the student that will replace the chalk.
``
Here instead of ``replace the chalk`` in the last line it should be ``replace the chalk pieces``  (Basically k).Because we 
are already assuming chalk is an array in the problem statement

#### Code you used for Submit/Run operation

```
class Solution:
    def chalkReplacer(self, chalk: List[int], k: int) -> int:
        n = len(chalk)
        s = sum(chalk)
        k = k%s
        i = 0
        while chalk[i]<=k:
            k-=chalk[i]
            i+=1
        return i
```

#### Language used for code

Python

#### Screenshots

![Untitled](https://user-images.githubusercontent.com/57106245/224538603-21385d97-e959-43f9-8862-44e223767a05.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
