### ISSUE TITLE
Missing Test Case - 735. Asteroid Collision

### ISSUE THREAD

**Issue by Jagriti-grover20** [LeetCode-Feedback/LeetCode-Feedback#12303]
#### Your LeetCode username

Young_husler20

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
735. Asteroid Collision
[2,5,3,2,3,6,2]
missing testcase
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

C++

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:


The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
