### ISSUE TITLE
Problem:10. Regular Expression Matching

### ISSUE THREAD

**Issue by Kiriakos1998** [LeetCode-Feedback/LeetCode-Feedback#12300]
#### Your LeetCode username

kyrmar98

#### Category of the bug
- [x] Question
- [x] Solution
- [ ]  Language
- [ ] Missing Test Cases

#### Description of the bug

Wrong test cases. 

#### Code you used for Submit/Run operation

```
// Regular Expression Matching
class Solution {
    public boolean isMatch(String s, String p) {

        boolean[][] patterns = new boolean[p.length()][s.length()];
        int counter = 0;
        if(s.charAt(0)==p.charAt(0)){
            counter++;
            patterns[0][0] = true;
        }
        else if(p.charAt(0)=='.'){
            counter++;
            patterns[0][0]=true;
        }
        else if(p.charAt(0)=='*'){
            patterns[0][0]=true;
        }
        else{
            return false;
        }
    
        for(int i=1;i<s.length();i++){
            if(p.charAt(0)!='*'){
                patterns[0][i]=false;
                continue;
            }
            patterns[0][i]=true;
        }
        for(int i=1;i<p.length();i++){
            if(!patterns[i-1][0]){
                patterns[i][0]=false;
                continue;
            }
            if(p.charAt(i)=='*'){
                patterns[i][0]=true;
                continue;
            }
            if(counter==0){
                patterns[i][0]=true;
                counter++;
                continue;
            }
            patterns[i][0]=false;
        }    
        for(int i=1;i<p.length();i++){
            for(int j=1;j<s.length();j++){
                if(p.charAt(i)=='*'){
                    if(patterns[i-1][j-1] || patterns[i-1][j] || patterns[i][j-1]){
                        patterns[i][j]=true;
                    }
                    else{
                   patterns[i][j]=false;
                    }
                }
                else if(p.charAt(i)=='.'){
                    if(patterns[i-1][j-1]){
                        patterns[i][j]=true;
                    }
                    else{
                        patterns[i][j]=false;
                    }
                }
                else{
                    if(patterns[i-1][j-1] && p.charAt(i)==s.charAt(j)){
                        patterns[i][j]=true;
                    }
                    else{
                        patterns[i][j]=false;
                    }
                }
            }
        }
    return patterns[p.length()-1][s.length()-1];
    }
}

```

#### Language used for code

Java

#### Expected behavior

I expected test case: 289 to return false because s: "aab" and p:"c\*a\*b"

I expected test case: 290 to return true because s: "mississippi" and p:"mis\* is\* p\*." 

#### Screenshots

![image](https://user-images.githubusercontent.com/26304589/224493751-bbe58eb6-2516-46be-b1a4-a8b065b1375f.png)

![image](https://user-images.githubusercontent.com/26304589/224493774-d702a0dd-6c6f-4d90-a6ef-f85dd9e8640f.png)

#### Additional context

My code initially passed 288 tests out of 354. Then I explicitly returned what 289 wanted I passed it and stacked in 290. 
From what I understand from the problem description 289 should be false because c does not exist inside the s so the pattern p does not match with the s string.
Also in the 290 testcase, I expected it to be true because by replacing the first asterisk with s, second with si, third with p, and the dot with i we can get the s string aka mississippi.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

**Comment by Kiriakos1998** [comment]
How can it be working correctly when at least the 290 test case is profoundly wrong? mississippi can occur from the pattern mis/*is/*p/*. as follows:
First asterisk is replaced by s
Second asterisk is replaced by si
Third asterisk is replaced by p
The dot is replaced by i
