### ISSUE TITLE
Missing test case. 488 Zuma Game. Wrong solutions accepted

### ISSUE THREAD

**Issue by wiof** [LeetCode-Feedback/LeetCode-Feedback#1230]
#### Your LeetCode username

wiof

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The following test case gives `Wrong Answer` when tested with the attached code but the attached code is *Accepted*
```
"WWBBWBBWW"
"BB"
```
#### Code you used for Submit/Run operation

```
class Solution:
    def findMinStep(self, board: str, hand: str) -> int:
        def dfs(s, c):
            if not s: return 0
            res, i = float("inf"), 0
            while i < len(s):
                j = i + 1
                while j < len(s) and s[i] == s[j]: j += 1
                incr = 3 - (j - i)
                if c[s[i]] >= incr:
                    incr = 0 if incr < 0 else incr
                    c[s[i]] -= incr
                    tep = dfs(s[:i] + s[j:], c)
                    if tep >= 0: res = min(res, tep + incr)
                    c[s[i]] += incr
                i = j
            return res if res != float("inf") else -1
        return dfs(board, collections.Counter(hand))
```

#### Language used for code

Python3

#### Expected behavior

Submitting this code should return `Wrong Answer`, but currently it returns *Accepted*

#### Screenshots

![image](https://user-images.githubusercontent.com/10530094/96337546-4e49fb00-1088-11eb-8d66-c5c92e120e96.png)

#### Additional context

* Link to the problem: [https://leetcode.com/problems/zuma-game/]
* Link to the submission: [https://leetcode.com/submissions/detail/409796186/]
* Discussion about this code (by Jason003): https://leetcode.com/problems/zuma-game/discuss/221386/Python-DFS-16-lines-very-easy-to-understand
* Discussion about this issue: https://leetcode.com/problems/zuma-game/discuss/898526/Test-case-missing.-Probably-most-fast-accepted-solutions-are-wrong.

**Comment by lc-kay** [comment]
Hi @wiof 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @wiof 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
