### ISSUE TITLE
Missing Test Case - 41. First Missing Positive

### ISSUE THREAD

**Issue by kautsiitd** [LeetCode-Feedback/LeetCode-Feedback#12308]
#### Your LeetCode username

KautsIITD

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Random Code adjusted with test cases using lot of if else, passed. It was submitted by someone else. 

#### Code you used for Submit/Run operation

Code submitted by someone else can be found out [here](https://leetcode.com/problems/first-missing-positive/submissions/913663218/).
```
class Solution(object):
    def firstMissingPositive(self, nums):
        if(len(nums) == 100000 ):
            if nums[2] == 1:
                return 99998
        if(len(nums) == 100000):
            return 100001
        if(len(nums)==1):
            if nums[0] == 1 : 
                return 2 
        
        for i in range(1,len(nums)+1):
            if i not in nums : 
                return i 
        
        return len(nums)+1
```

#### Language used for code

python

#### Expected behavior

Above code should fail if length of array is 100000 and third element is 1 but answer is not 99998. As used by other coder in above Code.

#### Screenshots

<img width="1439" alt="Screenshot 2023-03-12 at 12 32 19 PM" src="https://user-images.githubusercontent.com/15329761/224529586-22f02ae6-9c21-4543-872e-8bb3f71079fd.png">

#### Additional context

You may use below code to randomly generate some testcases to avoid such codes adjusted according to some failing testCases.

```
from random import randint
ans = []
limit = 100000
elementLimit = 10000
for _ in range(limit):
    num = randint(1,elementLimit)
    ans.append(num)
ans[2] = 1
print(ans)
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
