### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by imAneeesh** [LeetCode-Feedback/LeetCode-Feedback#12310]
#### Your LeetCode username
aneeshd70

#### Category of the bug
- Two Sum
- class Solution {
    public int[] twoSum(int[] nums, int target) {
        int sum=0;
        int[] arr2=new int[2];
        HashMap<Integer,Integer> hmap=new HashMap<>();
         for(int i=0;i<nums.length;i++)
        {
            int x=target-nums[i];
            if(hmap.containsKey(x))
            {
                arr2[0]=hmap.get(x);
                arr2[1]=i;
                break;
                
            }
                hmap.put(nums[i], i);
        }
        return arr2;
    }
}
- Java
- Add test case [11,3,4,14,6] target is 17

#### Description of the bug
In the above case the output is 1,3 not 0,4

#### Code you used for Submit/Run operation

```
class Solution {
    public int[] twoSum(int[] nums, int target) {
        int sum=0;
        int[] arr2=new int[2];
        HashMap<Integer,Integer> hmap=new HashMap<>();
         for(int i=0;i<nums.length;i++)
        {
            int x=target-nums[i];
            if(hmap.containsKey(x))
            {
                arr2[0]=hmap.get(x);
                arr2[1]=i;
                break;
                
            }
                hmap.put(nums[i], i);
        }
        return arr2;
    }
}
```

#### Language used for code
Java

#### Expected behavior
 0,4

**Comment by stormsunshine** [comment]
It is required that each input would have **exactly one solution**. Why are you providing a test case that has more than one solution?

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
