### ISSUE TITLE
Missing Test Case - 162. Find Peak Element

### ISSUE THREAD

**Issue by khatamirock** [LeetCode-Feedback/LeetCode-Feedback#12312]
#### Your LeetCode username

khatami

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

this is an testcase error. the output should be an error but your system accepts that for case >> [1,2,1,10]

#### Code you used for Submit/Run operation

```
class Solution:
    def findPeakElement(self, nums: List[int]) -> int:
        n = len(nums)
        left, right = 0, n-1
        while left < right:
            mid = (left + right) // 2
            if nums[mid] > nums[mid-1] and nums[mid] > nums[mid+1]:
                return mid
            elif nums[mid-1] > nums[mid]:
                right = mid-1
            else:
                left = mid+1
        return left

```

#### Language used for code

python

#### Expected behavior

for testcase [1,2,1,10]
the output for my code shows 1 and the sysyem output shows 3 even though the result is accepted

#### Screenshots

![ScreenShot_20230312195119](https://user-images.githubusercontent.com/67198296/224549031-83ca9467-0b96-4ce4-90c7-e671ca24c190.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
