### ISSUE TITLE
Missing Test Case - 344. Reverse String

### ISSUE THREAD

**Issue by rachitkumarrastogi** [LeetCode-Feedback/LeetCode-Feedback#12320]
#### Your LeetCode username

rachitrastogi777@gmail.com

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ X] Missing Test Cases 

#### Description of the bug

Handling empty and escape sequences
[" "," "," "," "," "]

[" ","\n","\t","      "," "]

   
#### Code you used for Submit/Run operation

```
/**
 * @param {character[]} s
 * @return {void} Do not return anything, modify s in-place instead.
 */
var reverseString = function(s) {
    let left=0, right=s.length-1;
    while(right>left){
        let tmp = s[left]
        s[left] = s[right]
        s[right]=tmp
        left++
        right--
    }
};
```

#### Language used for code

JavaScript

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

[" "," "," "," "," "]

[" ","\n","\t"," "," "]

already exists. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
