### ISSUE TITLE
Forgot to attach link in explore card

### ISSUE THREAD

**Issue by lakpro** [LeetCode-Feedback/LeetCode-Feedback#12325]
#### Your LeetCode username
(https://leetcode.com/Lakpro/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the explore card of recursion || and in the divide and conquer section, you forgot to attach a link to the wiki page in merge sort.
You can see the pic for reference. One has to click the link at the bottom of the page, which is not the case in other sections.
Here's the link to the page: https://leetcode.com/explore/learn/card/recursion-ii/470/divide-and-conquer/2868/

#### Code you used for Submit/Run operation
NIL

#### Language used for code
NIL

#### Expected behavior
NIL

#### Screenshots
![image](https://user-images.githubusercontent.com/73340463/224623653-047a6306-9d1f-4763-bad8-46d202c25706.png)

#### Additional context
NIL

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
