### ISSUE TITLE
[C++] 引入位运算后，无法直接调用countr_zero，需要使用__countr_zero才可以。

### ISSUE THREAD

**Issue by WangDongYao** [LeetCode-Feedback/LeetCode-Feedback#12328]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名：The Fool

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [x] 编程语言
- [ ] 缺少测试用例

**描述**
引入位运算后，无法直接调用countr_zero，需要使用__countr_zero才可以。

**你使用的语言**
C++

**你提交或者运行的代码**
```
#include <bit>
class Solution
{
public:
    uint countZero(uint x)
    {
        return countr_zero(x);
    }
};
```

**期望行为**
返回x低位0的数量

**屏幕截图**
<img width="1047" alt="Xnip2023-03-13_20-00-37" src="https://user-images.githubusercontent.com/9822643/224695995-d3f1f8aa-e3c9-44a1-8f9f-c1f1d1728eb4.png">

**额外的上下文**
error: use of undeclared identifier 'countr_zero'; did you mean '__countr_zero'?

**Comment by feiceh** [comment]
你好，在与相关团队核实后：无法直接调用countr_zero， 可能是目前采用 C++ 17 标准导致的， 暂时没有升级计划。
