### ISSUE TITLE
Missing Test Case - 175. Combine Two Tables

### ISSUE THREAD

**Issue by zphw** [LeetCode-Feedback/LeetCode-Feedback#12335]
#### Your LeetCode username
xwangsd

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Missing test cases that have same PERSON.FIRSTNAME, PERSON.LASTNAME, ADDRESS.CITY, ADDRESS.STATE, or a combination of them (since it's legitimate that people have the same name), so that it allows solutions incorrectly grouping by these attributes to pass.

#### Code you used for Submit/Run operation
```SQL
SELECT DISTINCT FIRSTNAME, LASTNAME, CITY, STATE FROM PERSON LEFT JOIN ADDRESS ON PERSON.PERSONID = ADDRESS.PERSONID
```

AC submission link: https://leetcode.com/problems/combine-two-tables/submissions/914517100/

#### Language used for code
MySQL

#### Expected behavior
The answer should receive Wrong Answer

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
