### ISSUE TITLE
Missing Test Case - 550. Game Play Analysis IV

### ISSUE THREAD

**Issue by zphw** [LeetCode-Feedback/LeetCode-Feedback#12337]
#### Your LeetCode username
xwangsd

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Missing test cases that no such players who logged in again on the day after the day they first logged in. For example,
```
{
  "headers": {
    "Activity": [
      "player_id",
      "device_id",
      "event_date",
      "games_played"
    ]
  },
  "rows": {
    "Activity": [
      [
        1,
        8,
        "1970-01-01",
        0
      ],
      [
        2,
        9,
        "1970-01-01",
        0
      ]
    ]
  }
}
```

#### Code you used for Submit/Run operation
```SQL
WITH FIRST_DATE AS( SELECT PLAYER_ID FROM ACTIVITY GROUP BY PLAYER_ID HAVING (PLAYER_ID, MIN(EVENT_DATE)+1) IN (SELECT PLAYER_ID,EVENT_DATE FROM ACTIVITY) ) SELECT ROUND(COUNT(DISTINCT F.PLAYER_ID)/COUNT(DISTINCT A.PLAYER_ID),2) AS FRACTION FROM ACTIVITY A ,FIRST_DATE F;
```

AC submission link: https://leetcode.com/problems/game-play-analysis-iv/submissions/914522806/

#### Language used for code
MySQL

#### Expected behavior
The answer should receive Wrong Answer

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
