### ISSUE TITLE
Missing Test Case - 608. Tree Node

### ISSUE THREAD

**Issue by zphw** [LeetCode-Feedback/LeetCode-Feedback#12340]
#### Your LeetCode username
xwangsd

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Missing test cases such that there are only two nodes - one is root and one is leaf - and their ID are negative numbers. For example,
```
| id | p_id |
| -- | ---- |
| -1 | null |
| -2 | -1   |
```

#### Code you used for Submit/Run operation
```SQL
SELECT ID, 'ROOT' AS TYPE FROM TREE WHERE P_ID IS NULL UNION SELECT ID, 'INNER' AS TYPE FROM TREE WHERE P_ID>0 AND ID IN (SELECT P_ID FROM TREE) UNION SELECT ID, 'LEAF' AS TYPE FROM TREE WHERE P_ID>0 AND ID NOT IN (SELECT P_ID FROM TREE WHERE P_ID IS NOT NULL);
```

AC submission link: https://leetcode.com/problems/tree-node/submissions/914530835/

#### Language used for code
MySQL

#### Expected behavior
The answer should receive Wrong Answer

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Please send the test case in the json format like this: {"headers":{"Activity":["player_id","device_id","event_date","games_played"]},"rows":{"Activity":[[1,8,"1970-01-01",0],[2,9,"1970-01-01",0]]}}

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
