### ISSUE TITLE
[typo] Extra symbol in explore card for DP

### ISSUE THREAD

**Issue by Philosoft** [LeetCode-Feedback/LeetCode-Feedback#12348]
#### Your LeetCode username

thephilosoft

#### Category of the bug

Explore card

#### Description of the bug

Explore card for [dynamic programming](https://leetcode.com/explore/learn/card/dynamic-programming/631/strategy-for-solving-dp-problems/4101/) contains an extra `}` symbol in this passage:

> and holding holding }can be true or false

#### Screenshots

![image](https://user-images.githubusercontent.com/296326/224818730-6e1a47f3-647e-4158-9336-590a7a07bb17.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
