### ISSUE TITLE
Missing Solution - 543. Diameter of Binary Tree

### ISSUE THREAD

**Issue by lakpro** [LeetCode-Feedback/LeetCode-Feedback#12347]
#### Your LeetCode username
https://leetcode.com/Lakpro/

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The editorial of the question has a missing solution for the brute force approach with time complexity of O(N^2)

#### Code you used for Submit/Run operation

```
/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
class Solution {
private:
    int diameter=0;
public:
    int height(TreeNode* root){

        if(root==NULL)
            return 0;
        
        return max(height(root->left),height(root->right))+1;
    }
    
    void traverse(TreeNode* root){
        
        if(root==NULL)
            return;

        int leftHeight = height(root->left);
        int rightHeight = height(root->right);
        
        diameter=max(diameter,leftHeight+rightHeight);

        traverse(root->left);
        traverse(root->right);
    }

    int diameterOfBinaryTree(TreeNode* root) {
        
        traverse(root);

        return diameter;

    }
};
```

#### Language used for code
C++

#### Expected behavior
The editorial gives only one approach, i.e. DFS and Time Complexity is O(N).
However, since the question is marked as easy (even if it was not), there should first be a brute-force approach.
In the brute force approach, we traverse the whole tree, and for each node, we find the left height and right height.
Then, we update our diameter with a max of diameter and (left height + right height).
This way, the time complexity will be O(N^2).
The problem's constraints are 1<=N<=10000, so in O(N^2) time complexity, the solution is **ACCEPTED**.
Question link: https://leetcode.com/problems/diameter-of-binary-tree/description/
Editorial link: https://leetcode.com/problems/diameter-of-binary-tree/editorial/

#### Screenshots

NIL

#### Additional context

NIL

**Comment by nskybytskyi** [comment]
Hi there, 

Thank you for reaching out to us.

The editorial section is not designed to be complete. Sometimes multiple solutions are possible, but the editorial only considers one. This is an intentional attempt to let users focus on the best approach. Feel free to explore the user-provided answers to get a complete picture.

Thank you for your support.
