### ISSUE TITLE
Missing Test Case in Biweekly-contest 37 - 1620. Coordinate With Maximum Network Quality

### ISSUE THREAD

**Issue by Dheeraj-kumar626** [LeetCode-Feedback/LeetCode-Feedback#1235]
#### Your LeetCode username
dheerajkumar

#### Category of the bug
- [1] Question 
- [ ] Solution
- [ ] Language

#### Description of the bug
##1620. Coordinate With Maximum Network Quality
https://leetcode.com/contest/biweekly-contest-37/problems/coordinate-with-maximum-network-quality/

Below test case is missing, fails the code given below:

> input
[[0,1,2],[2,1,2],[1,0,2],[1,2,2]]
1
Output
[0,1]
Expected
[1,1]
*wrong answer*

#### Code you used for Submit/Run operation

```

class Solution {
public:
    double dist(vector<int> & a, vector<int> & b) {
        return sqrt(pow(a[0] - b[0], 2) + pow(a[1] - b[1], 2));
    }
    
    vector<int> bestCoordinate(vector<vector<int>>& towers, int radius) {
        int n = towers.size();
        vector<int> value(n);
        int ans = -1, ind = -1;
        
        for (int i = 0; i < n; i++) {
            int quality = 0;
            for (int j = 0; j < n; j++) {
                double d = dist(towers[i], towers[j]);
                if (d <= radius) {
                    quality += (int)(towers[j][2] / (1+d));
                }
            }
            if (quality == ans) {
                if (towers[i] < towers[ind]) {
                    ind = i;
                }
            } else if (quality > ans) {
                ind = i;
                ans = quality;
            }
        }
        vector<int> pos = {towers[ind][0], towers[ind][1]};
        return pos;
    }
};
```

#### Language used for code
C++

#### Expected behavior

We are supposed to find the co-ordinates with maximum Network Quality but instead one of the tower locations with maximum network quality is accepted as output.

#### Screenshots

![Screenshot (1240)](https://user-images.githubusercontent.com/25036822/96352679-af9eb800-10e2-11eb-88d0-b493abd0d13c.png)

#### Additional context

This question is a part of Biweekly contest,so I request you to verify the solutions again with updated test cases and update the rankings.

**Comment by lc-kay** [comment]
Hi @Dheeraj-kumar626 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@Dheeraj-kumar626 Our team has updated this problem and your code gets WA now and the test case was not added. Thank you for your time and support!
