### ISSUE TITLE
Missing Test Case - 988. Smallest String Starting From Leaf

### ISSUE THREAD

**Issue by Nilanshuyadav** [LeetCode-Feedback/LeetCode-Feedback#12359]
#### Your LeetCode username

Nilanshu_yadav08

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Some Testcases are giving wrong answer, still the code gets accepted.

#### Code you used for Submit/Run operation

```
class Solution {
    String ans;
    public String smallestFromLeaf(TreeNode root) {
        StringBuilder sb = new StringBuilder("");
        ans = "zz";
        
        solve(root, sb);
        return ans;
    }
    
    public void solve(TreeNode root, StringBuilder sb){
        if(root.left==null && root.right==null){
            sb.append((char)(root.val+'a'));
            
            sb.reverse();
            String temp = sb.toString();
            sb.reverse();
            
            ans = ans.compareTo(temp) > 0 ? temp : ans;
            
            sb.deleteCharAt(sb.length()-1);
            
            return;
        }
        
        sb.append((char)(root.val+'a'));
        
        if(root.left != null) solve(root.left, sb);
        if(root.right != null) solve(root.right, sb);
        
        sb.deleteCharAt(sb.length()-1);
        
    }
}

```

#### Language used for code

Java

#### Expected behavior

The starting smallest string taken is "zz", but if the answer happens to be greater than ("zz"), It will not be updated, as by comparison "zz" is smaller than any string greater than it.

testcase should be there to check for the base starting string, 

#### Screenshots

![leetcode bug](https://user-images.githubusercontent.com/91049897/225110554-aedfafb8-a537-4d27-b45e-55fef8d05900.png)

![leetcode bug2](https://user-images.githubusercontent.com/91049897/225110598-9a2a1717-4f2d-4c1c-9da9-94196a664900.png)

#### Additional context

check for the starting string to compare

Testcases giving wrong answer:
`[25, null, 25, ..., 25, ..., null, 25]`(maximum number of nodes possible).

**Comment by nskybytskyi** [comment]
Note: I recommend generalizing the suggested test case to `[25, null, 25, ..., 25, ..., null, 25]` (with the maximum number of nodes possible, so that `"zzz"` or `"zzzz"` are not valid initializers either.

**Comment by Nilanshuyadav** [comment]
> Note: I recommend generalizing the suggested test case to `[25, null, 25, ..., 25, ..., null, 25]` (with the maximum number of nodes possible, so that `"zzz"` or `"zzzz"` are not valid initializers either.

Thanks for the Suggestion..

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
