### ISSUE TITLE
Missing Test Case - 988. Smallest String Starting From Leaf

### ISSUE THREAD

**Issue by sudevdhali** [LeetCode-Feedback/LeetCode-Feedback#12362]
#### Your LeetCode username

newbiesd

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ .] Missing Test Cases 

#### Description of the bug

Below code is getting accepted
https://leetcode.com/submissions/detail/915271290/
but fails for the following testcase
[25,null,25,null,25,null,25]

#### Code you used for Submit/Run operation

```
class Solution {
    String ans;
    public void solve(TreeNode root, StringBuilder s){
        if(root.left==null && root.right==null){
            s.append((char)(root.val+'a'));
            s.reverse();
            String temp = s.toString();
            s.reverse();
            ans = ans.compareTo(temp) > 0 ? temp : ans;
            s.deleteCharAt(s.length()-1);
            return;
        }
        s.append((char)(root.val+'a'));        
        if(root.left != null) solve(root.left, s);
        if(root.right != null) solve(root.right, s);
        s.deleteCharAt(s.length()-1);
    }
    public String smallestFromLeaf(TreeNode root) {
        StringBuilder s = new StringBuilder("");
        ans = "zz";
        solve(root, s);
        return ans;
    }
}
```

#### Language used for code

java

#### Expected behavior

It should give "zzzz" while its giving "zz"

#### Screenshots

![image](https://user-images.githubusercontent.com/60395148/225138909-331b1197-fd87-4f12-8cab-eb1b536fd708.png)

**Comment by nskybytskyi** [comment]
Hi there,

Thank you for reaching out to us.

Could you please clarify how this issue differs from #12359 ?

Thank you for your support.

**Comment by sudevdhali** [comment]
I think its similar, he also faced same issue

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
