### ISSUE TITLE
2251. Number of Flowers in Full Bloom - Grammar mistake

### ISSUE THREAD

**Issue by mnaoumov** [LeetCode-Feedback/LeetCode-Feedback#12363]
#### Your LeetCode username
mnaoumov

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The description of the problem and the code definition use word `persons` which is a wrong grammar.

#### Expected behavior

The word `people` should be used instead.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by mnaoumov** [comment]
@LC-Pam Now it is a typo

You put `poeple` instead of `people`
