### ISSUE TITLE
89. Gray code. Test case doesn't pass for valid output.

### ISSUE THREAD

**Issue by krottv** [LeetCode-Feedback/LeetCode-Feedback#12370]
#### Your LeetCode username
mafkavelly

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
https://leetcode.com/problems/gray-code/description/
When we have input 3, the [0,1,2,3,7,6,5,4] should be valid sequence, since all adjacent numbers differ by 1 bit only. [000, 001, 010, 011, 111, 110, 101, 100). No repetitive numbers are present.

#### Code you used for Submit/Run operation

```kotlin
fun grayCode(n: Int): List<Int> {
        if (n == 0) return listOf(0)

        val needNumbers = (Math.pow(2.toDouble(), n.toDouble())).toInt()
        val maxNumber = needNumbers - 1

        val listFrom0 = mutableListOf(0)
        val listFromMax = mutableListOf(maxNumber)

        while ((listFrom0.size + listFromMax.size) < needNumbers) {

            val toAddFrom0 = listFrom0.last() + 1
            val toAddFromMax = (toAddFrom0 xor maxNumber) and maxNumber

            listFrom0.add(toAddFrom0)
            listFromMax.add(toAddFromMax)
        }
        listFrom0.addAll(listFromMax)

        return listFrom0
    }
```

#### Language used for code
kotlin

#### Expected behavior
Test should pass for input 3 for the given code

**Comment by stormsunshine** [comment]
How do 1 and 2 differ by 1 bit? The corresponding binary representations are 001 and 010, where the last two bits are different.

**Comment by krottv** [comment]
My fault. Yes it is indeed invalid
