### ISSUE TITLE
Submission errors - 939. Minimum Area Rectangle

### ISSUE THREAD

**Issue by anshulrao** [LeetCode-Feedback/LeetCode-Feedback#12379]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

All the test cases pass but I get Time Limit Exceeded. Note the test case for which it says TLE is nothing. It's empty.

#### Code you used for Submit/Run operation

```
class Solution:
    def minAreaRect(self, points: List[List[int]]) -> int:
        hashmap = defaultdict(list)
        area = float('inf')
        n = len(points)
        # create a hashmap having key = different x coordinates and
        # values as y coordinates of points having same x coordinate
        for point in points:
            hashmap[point[0]].append(point[1])
        for i in range(n):
            for j in range(i + 1, n):
                x1, y1 = points[i][0], points[i][1]
                x2, y2 = points[j][0], points[j][1]
                # check if points form a diagonal AB
                if x1 != x2 and y1 != y2:
                    # check if points C and D are in hashmap
                    # such that ABCD form a rectangle
                    if y2 in hashmap[x1] and y1 in hashmap[x2]:
                        area = min(area, abs(x1-x2) * abs(y1-y2))
        return area if area < float('inf') else 0
```

#### Language used for code

Python3

#### Expected behavior

I expect to at least see a test case for which the time limit exceeded. It's a bug since 137/137 test cases passed but it is still throwing TLE.

#### Screenshots

![Screenshot 2023-03-15 at 6 35 59 PM](https://user-images.githubusercontent.com/31268509/225460396-931953d2-b423-497f-b6d7-2f4ee633300b.png)

**Comment by nskybytskyi** [comment]
Hi there,

Thank you for reaching out to us.

This is a known issue that appears only in the new design. In the old design, this message is displayed instead:

<img width="710" alt="Знімок екрана 2023-03-18 о 21 59 54" src="https://user-images.githubusercontent.com/25816558/226135175-8f94c949-8c84-41db-8be7-152589d5782d.png">

It means that there is no individual test case that exceeds the time limit. Instead, the solution is a little bit too slow overall.

To roll back to the old design, click your profile photo in the upper right corner > "Revert to old version". Don't worry, you will be able to return to the new design at any point.

Thank you for your support. If you have any other questions, please don't hesitate to let us know.
