### ISSUE TITLE
1614 - Missing information in task description

### ISSUE THREAD

**Issue by TrickyCat** [LeetCode-Feedback/LeetCode-Feedback#1237]
#### Your LeetCode username
TrickyCat

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

One rule for calculation of nesting depth seems to be missed in the task description.
There's no rule for string inputs like 'a', 'abc', '1+2-3'.

What we have:
1. rule `depth("") = 0` for terminal string: empty string
2. rule `depth(A + B) = max(depth(A), depth(B))` for concatenation of two VPS strings
3. rule `depth("(" + A + ")") = 1 + depth(A)` for VPS surrounded by parentheses 

Following the existing rules, we can't say how we should calculate the depth for strings: 'a', 'ab', 'abc' etc.

---
#### **Example**

**Input:** 'a'
**Rule 1:** not hit
**Rule 2:**
 - depth('a') = max(depth('a'), depth(''))
 or
 - depth('a') = max(depth(''), depth('a'))

**We encounter an infinite recursive loop.**

**Rule 3:** not hit

**Expected result:** 0
**Actual result:** undetermined

---

Depth calculations are expected to result in 0 depth for such inputs but there's no rule for the **"string of single character (which is not a '(' or ')')"**.

#### Expected behavior

**I suggest either**
- adding a new rule to the task description: **`depth(c)=0` when c is a single character not equal to "(" or ")"**

**or**

- modifying an existing rule for an empty string: **`depth(c)=0` when c is an empty string or a single character not equal to "(" or ")"**

**Comment by lc-kay** [comment]
Hi @TrickyCat 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @TrickyCat 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
