### ISSUE TITLE
Incorrect Problem Number - Design a Todo List

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#12384]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
For the problem [Design a Todo List](https://leetcode.com/problems/design-a-todo-list), the problem number is 2890. However, the total number of problems is 2590, and the previous problem's number is 2589. Therefore, I believe that the problem number 2890 is a mistake, and it should be changed to 2590.

#### Expected behavior
Change the problem number of "Design a Todo List" from 2890 to 2590.

**Comment by nskybytskyi** [comment]
Thank you for reaching out to us. 

The issue appears to be resolved now:

<img width="295" alt="Знімок екрана 2023-03-18 о 22 05 39" src="https://user-images.githubusercontent.com/25816558/226135451-cb9827b2-3750-4bc4-a006-44a61ea0331d.png">

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
