### ISSUE TITLE
Missing Test Case - 1622. Fancy Sequence

### ISSUE THREAD

**Issue by tonghuikang** [LeetCode-Feedback/LeetCode-Feedback#1238]
#### Your LeetCode username
tonghuikang

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The cited Python 2 code should TLE for the edge case generated with this Python script

```
CNT = 49000
import json
print(str(json.dumps(["Fancy"] + ["append"] + ["multAll"]*CNT + ["getIndex"]*CNT)))
print(str(json.dumps([[]] + [[100]] + [[100]]*(CNT) + [[0]]*CNT)))
```

which generates this large edge case (not the complete edge case is shown

```
["Fancy", "append", "multAll", "multAll", ... , "multAll", "getIndex", ... , "getIndex"]
[[], [100], [100], ... , [100], [100], [0], ... , [0]]
```

#### Code you used for Submit/Run operation

```
class Fancy(object):

    def __init__(self):
        self.A = []
        self.add = [0]
        self.mul = [1]

    def append(self, a):
        self.A.append(a)
        self.add.append(self.add[-1])
        self.mul.append(self.mul[-1])

    def addAll(self, inc):
        self.add[-1] += inc

    def multAll(self, m):
        self.add[-1] *= m
        self.mul[-1] *= m
        
    def getIndex(self, i):
        if i >= len(self.A): return -1
        m = self.mul[-1] / self.mul[i]
        inc = self.add[-1] - self.add[i] * m
        res = (self.A[i] * m + inc) % (10 ** 9 + 7)
        return res
```

#### Language used for code
Python 2

#### Expected behavior
The online judge should have delivered a time limit exceeded error.

#### Screenshots
<img width="1432" alt="Screenshot 2020-10-18 at 8 22 30 AM" src="https://user-images.githubusercontent.com/17105577/96355986-18a22200-111b-11eb-9793-baa41420b697.png">

#### Additional context
Code was obtained from https://leetcode.com/problems/fancy-sequence/discuss/898753/Python-Time-O(1)-for-each

**Comment by lc-kay** [comment]
Hi @tonghuikang 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@tonghuikang We have updated this problem and added new test cases based on earlier submissions, your answer now gets TLE. Thank you for your time and support!
