### ISSUE TITLE
测试用例 - 998. Maximum Binary Tree II 测试数组和入参二叉树不一致

### ISSUE THREAD

**Issue by vsyf** [LeetCode-Feedback/LeetCode-Feedback#12397]
**你的 LeetCode 用户名**

vsyfar

**Bug 类型**
- [ ] 题目
- [x ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**

测试用例错误，当原始数组a为[3, 2]，二叉树中 2节点 应当在 3 节点的右子树，而测试用例入参的二叉树中的2节点却是在3节点的左子树。

这就导致当append上后面的1，新数组b为[3, 2, 1]时，构造出来的二叉树2节点和1节点应当在3节点的同一棵子树上面，而测试用例判断的结果2节点和1节点却在2棵不同的子树上.

**你使用的语言**
C++

**你提交或者运行的代码**
```
class Solution {
public:
    TreeNode* insertIntoMaxTree(TreeNode* root, int val) {
        // return
        if (root == nullptr ) {
            return nullptr;
        }

        // new node is father of root
        if (root->val < val) {
            TreeNode* node = new TreeNode();
            node->val = val;
            node->left = root;
            return node;
        }

        // traversal right first
        if (root->right != nullptr) {
            root->right = insertIntoMaxTree(root->right, val);
            return root;
        }

        // traversal left
        if (root->left != nullptr) {
            root->left = insertIntoMaxTree(root->left, val);
            return root;
        }

        // root is leaf, insert right node
        TreeNode* node = new TreeNode();
        node->val = val;
        root->right = node;
        return root;
    }
};
```

**期望行为**

测试用例的数组a和输入二叉树结构一致。
当前测试用例用来入参的二叉树 数组a [3, 2]其实应当是 [2, 3]

**屏幕截图**

case 4中原始数组为[3, 2], 入参的二叉树却发生了错误

![](https://storage-1258719774.cos.ap-nanjing.myqcloud.com/image/20230317163834.png)

更错误的是，当我原始数组为[2, 3] 时，2竟然变成了根节点

![](https://storage-1258719774.cos.ap-nanjing.myqcloud.com/image/20230317164246.png)

**额外的上下文**

我使用 [654](https://leetcode.cn/problems/maximum-binary-tree/description/) 这题进行验证均不存在问题.

![](https://storage-1258719774.cos.ap-nanjing.myqcloud.com/image/20230317165041.png)

**Comment by stormsunshine** [comment]
二叉树的输入解析规则为：首个值为根结点，其余每个值依次按层序遍历的顺序排列，如果左子结点为空则用 null 表示。

因此如果输入是 [3,2]，则 3 是根结点，2 是 3 的左子结点。如果想要 2 是 3 的右子结点，则输入应为 [3,null,2]。

第 654 题的输入是数组，不是二叉树，因此和第 998 题不一样。
