### ISSUE TITLE
Missing Test Case - 4. Median of Two Sorted Arrays

### ISSUE THREAD

**Issue by Uttam004** [LeetCode-Feedback/LeetCode-Feedback#12393]
#### Your LeetCode username
Uttam_P

#### Category of the bug

Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution:
    def findMedianSortedArrays(self, nums1, nums2):
        result = []
        while(nums1 and nums2):
            if(nums1[0]<nums2[0]):
                result.append(nums1.pop(0))
            else:
                result.append(nums2.pop(0))
        
        if(nums1):
            result.extend(nums1)
        
        if(nums2):
            result.extend(nums2)
        
        print(result)
        
        mid = len(result)//2
        if len(result)%2 == 0:
            return (result[mid] + result[mid-1]) / 2.0
        else: 
            return result[mid]
```

#### Language used for code
Python

#### Screenshots
<img width="873" alt="Screenshot 2023-03-17 at 12 58 45 AM" src="https://user-images.githubusercontent.com/110301974/225732380-76fa8641-b074-44f6-bc03-3a268ae14bda.png">

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

The test case already exists.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
