### ISSUE TITLE
542 题解 方法二分析有误

### ISSUE THREAD

**Issue by happiness19** [LeetCode-Feedback/LeetCode-Feedback#124]
** Bug 类型**
- [ ] 题目
- [ x] 题解
- [ ] 编程语言

**描述**
题解中算法的第三步：“初始地，对于每个为 0 的节点距离都是 1” 不正确
应为：初始地，对于每个为 0 的节点距离都是 **0**

**Comment by happiness19** [comment]
https://leetcode-cn.com/problems/01-matrix/solution/01-ju-zhen-by-leetcode/

**Comment by feiceh** [comment]
fixed
