### ISSUE TITLE
Missing Test Case - 188. Best Time to Buy and Sell Stock IV

### ISSUE THREAD

**Issue by tonghuikang** [LeetCode-Feedback/LeetCode-Feedback#1240]
#### Your LeetCode username
tonghuikang

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Missing test case. `k` should have a value close to but smaller than `prices.length/2` to catch `O(nk)` solutions.

This missing test case can be generated with
```
print(4900)
print([*[0, 1000]]*5000)
```

The test case looks like
```
4900
[0, 1000, ... , 0, 1000]
```

I also recommend adding a test case with `k=2500`

#### Code you used for Submit/Run operation
```
class Solution(object):
    def maxProfit(self, k, prices):
        
        if k > len(prices)//2:
            prices = [1001] + prices + [-1]
            deduplicated_prices = [1001]
            prev = 1001
            for p in prices[1:]:
                if p != prev:
                    deduplicated_prices.append(p)
                prev = p
            prices = deduplicated_prices
        
            peaks = []
            valleys = []
            for a,b,c in zip(prices, prices[1:], prices[2:]):
                if a > b and b < c:
                    valleys.append(b)
                if a < b and b > c:
                    peaks.append(b)
            
            return sum([peak - valley for peak, valley in zip(peaks, valleys)])
                    

        k = min(len(prices)//2 + 1, k)
        
        # dp [how many transcations done][if currently holding] 
        dp = [[0,-10000] for _ in range(k+1)]
        
        for j,p in enumerate(prices):
                        
            for i in range(k+1):
                if 2*i > j+1:
                    continue
                if i < k:
                    dp[i][1] = max(dp[i][0] - p, dp[i][1])
                if i > 0:
                    dp[i][0] = max(dp[i-1][1] + p, dp[i][0])
                
        return max(x[0] for x in dp)
```

#### Language used for code
Python 3

#### Expected behavior
The solution should not have been accepted due to TLE.

#### Screenshots

<img width="1479" alt="Screenshot 2020-10-18 at 3 55 12 PM" src="https://user-images.githubusercontent.com/17105577/96361681-5b371f00-115a-11eb-96a8-840b4cee3983.png">

#### Additional context
It may for be possible for Python to make it within the time limit with the solution presented in https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iv/solution/

It might be required for all to use a heap-based solution.

**Comment by lc-kay** [comment]
Hi @tonghuikang 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @tonghuikang 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
