### ISSUE TITLE
Missing Test Case - 209. Minimum Size Subarray Sum

### ISSUE THREAD

**Issue by Unleashed0000** [LeetCode-Feedback/LeetCode-Feedback#12402]
#### Your LeetCode username
Unleashed0000

#### Category of the bug
- [+] Question
- [+] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In problem "Minimum Size Subarray Sum"
Wrong working 17/20 Submission Result. Gives wrong answer, but my code worked properly.

#### Code you used for Submit/Run operation
```
class Solution:
    def minSubArrayLen(self, target: int, nums: List[int]) -> int:
        nums = sorted(nums)
        print(nums)
        print(sum(nums[4:]))
        print(sum(nums[5:]))
        print(sum(nums[6:]))
        lennums = len(nums)
        left, right = 0, lennums - 1
        sumofnums, k = 0, 1
        if nums[right] >= target:
            return 1
        while left <= right:
            if nums[right] < target:
                sumofnums += nums[right]
            if sumofnums >= target:
                return k
            else:
                k += 1
            right -= 1
        return 0
```

#### Language used for code
Python3

#### Expected behavior
Expected submission result is 7 but your site gives 8, that is not correct.
Here is minimum length 7 but not 8.

#### Screenshots
![Скриншот 17-03-2023 140928](https://user-images.githubusercontent.com/114099972/225889828-bef1185d-2838-45c8-921e-2687faede73f.jpg)

#### Additional context
None

**Comment by stormsunshine** [comment]
Is it allowed to modify the input array for this problem? Is it allowed that elements are not consecutive in a subarray?

In the original array, how can you find 7 consecutive elements with sum greater than or equal to 213?

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Comment by Unleashed0000** [comment]
Problem was in description in course "The LeetCode Beginner's Guide".
![Скриншот 22-03-2023 211109](https://user-images.githubusercontent.com/114099972/226998844-53df826d-15bb-46ff-935f-0537e5c887bb.jpg)
But in problem paige here it is. Distinct description what subarray is in this case.
![Скриншот 22-03-2023 210911](https://user-images.githubusercontent.com/114099972/226998950-515c0b9f-6b9e-4ae6-a78a-89e62e9eba7e.jpg)

**Comment by TravisHammonds** [comment]
I have the same issue as well. Were you ever able to figure this out?
