### ISSUE TITLE
Typos in the Binary Search Editorial

### ISSUE THREAD

**Issue by naphtul** [LeetCode-Feedback/LeetCode-Feedback#12406]
#### Your LeetCode username
naphtul

#### Category of the bug
- [ ] Question
- [X] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug
There are typos in https://leetcode.com/problems/binary-search/editorial/

#### Expected behavior

1. _look_ instead of _looks_
2. _existing_ instead of _exisiting_
3. _into array A_ instead of _into the array A_
4. _duplicate elements_ or _a duplicate element_ instead of _duplicate element_
5. _the following approaches_ instead of _following approaches_
6. _discard_ instead of _discad_ (twice)
7. _two conditions_ instead of _two condition_
8. _which means all elements_ instead of _it means all elements_
9. _built-in_ instead of _build-in_ (four times)
10. _look for the leftmost_ instead of _look for for the leftmost_

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
