### ISSUE TITLE
Submission Error - 322. Coin Change

### ISSUE THREAD

**Issue by Benjababe** [LeetCode-Feedback/LeetCode-Feedback#12404]
#### Your LeetCode username
Benjababe

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Getting an empty test case upon submission

#### Code you used for Submit/Run operation

```
class Solution {
private:
    int min_coins = INT_MAX;
public:
    void choose_coin(int cur_amount, int coin_count, vector<int>& coins, vector<int>& memoi)
    {
        // exit if overshot the coin amt or there is a path w/ less coins to this amount
        if (cur_amount < 0 || coin_count >= memoi[cur_amount])
            return;
        
        // update memoi if current coins selected is better
        if (coin_count < memoi[cur_amount])
            memoi[cur_amount] = coin_count;
        
        // update min coins if necessary
        if (cur_amount == 0 && coin_count < this->min_coins)
            this->min_coins = coin_count;

        // try taking each coin
        for (int coin : coins)
        {
            choose_coin(cur_amount-coin, coin_count+1, coins, memoi);
        }
    }

    int coinChange(vector<int>& coins, int amount) 
    {
        if (amount == 0)    return 0;
        vector<int> memoi = vector<int>(amount+1, INT_MAX);
        this->choose_coin(amount, 0, coins, memoi);        
        return (this->min_coins == INT_MAX) ? -1 : this->min_coins;
    }
};
```

#### Language used for code
C++

#### Expected behavior
All test cases passed, continue to the page with time taken and memory usage.

#### Screenshots
![image](https://user-images.githubusercontent.com/19561469/225901847-203d368f-1944-4ec8-8147-125121d0fdee.png)

**Comment by nskybytskyi** [comment]
Hi there,

Thank you for reaching out to us.

This is a known issue that appears only in the new design. In the old design, a message like this is displayed instead:

<img width="710" alt="Знімок екрана 2023-03-18 о 21 59 54" src="https://user-images.githubusercontent.com/25816558/226136119-7537c818-79a2-4fea-bb67-0ec182fee616.png">

It means that there is no individual test case that exceeds the time limit. Instead, the solution is a little bit too slow overall.

To roll back to the old design, click your profile photo in the upper right corner > "Revert to old version". Don't worry, you will be able to return to the new design at any point.

Thank you for your support. If you have any other questions, please don't hesitate to let us know.
