### ISSUE TITLE
Missing Test Case - 面试题 16.10. Living People LCCI

### ISSUE THREAD

**Issue by ChenYichengX** [LeetCode-Feedback/LeetCode-Feedback#12405]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
chen-4fm

**Bug 类型**
- [ ] 题目
- [X] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
测试用例有bug,预期答案错误

**你使用的语言**
java

**你提交或者运行的代码**
```

class Solution {
    public int maxAliveYear(int[] birth, int[] death) {
        int n = birth.length;
        int[] a = new int[103];
        for (int i = 0; i < n; i++) {
            int x = birth[i];
            int y = death[i];
            a[x-1900] += 1;
            a[y-1900 + 1] -= 1;
        }
        int mx = 0;
        int idx = 0;
        int sum = 0;
        for (int i = 0; i <= 100; i++) {
            sum += a[i];
            if(mx < sum){
                mx = sum;
                idx = i;
            }
        }
        return idx + 1900;
    }
}
```

**期望行为**
输入：
birth = [1900, 1901, 1950]
death = [1948, 1951, 2000]
该用例正确输出应是：1901，但是提交，测试用例却显示预期答案是1960

**屏幕截图**
![image](https://user-images.githubusercontent.com/61591329/225921536-1f4f3aab-a55c-4dae-89c7-89dd454f1886.png)

**额外的上下文**

**Comment by feiceh** [comment]
你好，如果出现测试用例结果和提交结果不一致的情况，可以再仔细检查并调试一下代码，或点击这里：「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」 获得更多帮助。

同时也可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
