### ISSUE TITLE
Missing Test Case - 215. Kth Largest Element in an Array

### ISSUE THREAD

**Issue by Ligh0x74** [LeetCode-Feedback/LeetCode-Feedback#12415]
#### Your LeetCode username

killer-cs

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets WA on the following testcase:
[4,5,1,3,2]
5

#### Code you used for Submit/Run operation

```
class Solution {
    public int findKthLargest(int[] nums, int k) {
        int n = nums.length;
        heapSort(nums, k, n);
        return nums[n - k];
    }

    private void heapSort(int[] nums, int k, int n) {
        // 堆化数组，O(NlogN)
        for (int i = n / 2 - 1; i >= 0; i--) {  //首个非叶结点n/2-1
            sink(nums, i, n);
        }
        // 从最后一个结点开始遍历k次，O(k*logN)
        int i = n - 1;
        while (k > 0) {
            swap(nums, 0, i); // 交换堆顶元素（最大数）和末尾元素
            i--;                // “删除”最大元素（原堆顶元素）
            sink(nums, 0, i); // 将新晋堆顶元素下沉至合适位置
            k--;
        }
    }

    private void sink(int[] nums, int k, int n) {
        // 左子结点下标 = 2 * k + 1
        while (2 * k + 1 < n) {
            int childIndex = 2 * k + 1; // 左子结点下标
            // 若右子结点存在，并且其值大于左子结点
            if (childIndex + 1 < n && nums[childIndex + 1] > nums[childIndex]) {
                childIndex += 1;    // 选择右子结点
            }
            // 若父结点值大于两个子结点值，退出循环
            if (nums[k] > nums[childIndex]) {
                break;
            }
            swap(nums, k, childIndex); // 交换较大子结点和父结点的值
            k = childIndex; // 检查下一级子结点
        }
    }

    private void swap(int[] nums, int i, int j) {
        int temp = nums[i];
        nums[i] = nums[j];
        nums[j] = temp;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Output: 2
Expected: 1

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback. 

Please provide us your valid LC username. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by Ligh0x74** [comment]
Hi, my leetcode username is killer-cs. ( LCCN )

**Comment by LC-Pam** [comment]
The LCCN team will reward you. Thank you.
