### ISSUE TITLE
Missing link in explore card (Recursion II)

### ISSUE THREAD

**Issue by lakpro** [LeetCode-Feedback/LeetCode-Feedback#12410]
#### Your LeetCode username
https://leetcode.com/Lakpro/

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the explore card of recursion II and in the divide and conquer section, you forgot to attach a link to the wiki page in quick sort.
You can see the pic for reference. One has to click the link at the bottom of the page, which is not the case in other sections.
Here's the link to the page: https://leetcode.com/explore/learn/card/recursion-ii/470/divide-and-conquer/2870/

#### Code you used for Submit/Run operation

NIL

#### Language used for code
NIL

#### Expected behavior
NIL

#### Screenshots

![image](https://user-images.githubusercontent.com/73340463/226052957-8344d978-6bd9-4895-a904-2c5a1d40bd2e.png)

#### Additional context
NIL

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
