### ISSUE TITLE
缺少测试用例 - 1616. 分割两个字符串得到回文串

### ISSUE THREAD

**Issue by PhiTer9426** [LeetCode-Feedback/LeetCode-Feedback#12414]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**goldenwind**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述**
提交了一个逻辑错误的代码，但是通过了

**你使用的语言**
C++

**你提交或者运行的代码**
```cpp
class Solution {
public:
    bool checkPalindromeFormation(string a, string b) {
        bool res = false;
        int l, r, n = a.size();
        
        l = 0, r = n - 1;
        while(l < r) {
            if(a[l] == b[r] || b[l] == a[r]) {
                l ++;
                r --;
            } else {
                break;
            }
        }
        if(check(a, l, r)) return true;
        if(check(b, l, r)) return true;

        return false;
    }

    bool check(string &s, int l, int r) {
        while(l < r) {
            if(s[l] != s[r]) {
                return false;
            }
            l ++;
            r --;
        }
        return true;
    }
};
```

**期望行为**
输入测试用例
```
"abeeecd"
"dzfffbz"
```
后与预期答案不符，但代码仍然通过该题

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![24c1de5665b19da6f957a121cc97b3b](https://user-images.githubusercontent.com/33077640/226094945-8cf981fd-212f-4266-b87b-68e265d5561d.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励哦。

**Comment by PhiTer9426** [comment]
https://leetcode.cn/u/goldenwind/




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月29日(星期三) 中午12:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LeetCode-Feedback/LeetCode-Feedback] 缺少测试用例 - 1616. 分割两个字符串得到回文串 (Issue #12414)





 
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励哦。

**Comment by feiceh** [comment]
收到，积分奖励已发放，请查收。
