### ISSUE TITLE
Alternate Solution for 199. Binary Tree Right Side View

### ISSUE THREAD

**Issue by mmalu** [LeetCode-Feedback/LeetCode-Feedback#1241]
#### Your LeetCode username

manky

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

A DFS based preorder traversal that simply keeps overwriting the value at the current level index in the output list. This ensures that it ends up being the rightmost. 

#### Code you used for Submit/Run operation

```
class Solution {
    public List<Integer> rightSideView(TreeNode root) {
        List<Integer> output = new ArrayList<Integer>();
        helper(root, output, 0);
        return output;
    }
    
    private void helper(TreeNode root, List<Integer> output, int level) {
        if (root == null) return;
        if (level == output.size()) output.add(root.val);
        else output.set(level, root.val);
        helper(root.left, output, level + 1);
        helper(root.right, output, level + 1);
    }
}
```

#### Language used for code

Java

#### Additional context

This solution uses a standard well-known traversal instead of a problem specific traversal.

**Comment by mmalu** [comment]
https://leetcode.com/problems/binary-tree-right-side-view/discuss/900005/The-standard-well-known-preorder-traversal

**Comment by lc-kay** [comment]
Hi @mmalu 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@mmalu After reviewing your code, we have decided not to add it since we already have a better DFS solution in the article. Thank you for your time!
