### ISSUE TITLE
153. Find Minimum in Rotated Sorted Array, test case 131 seems not right

### ISSUE THREAD

**Issue by xli-engr** [LeetCode-Feedback/LeetCode-Feedback#12423]
#### Your LeetCode username
Seanwang123

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
The question said the nums are sorted and rotated between **1** and n times, meaning at least it should be rotated once, however, test case 131 is [11,13,15,17], which means it's never been rotated. 

#### Expected behavior

Remove this test case, or update the question.

**Comment by nskybytskyi** [comment]
Thank you for reaching out to us. 

Please refer to the example explanation:

> The original array was [11,13,15,17] and it was rotated 4 times. 

In general, when you rotate a length `n` array `n` times it comes back to its original state. The expected answer is `n` for such test cases.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
