### ISSUE TITLE
Missing Test Case - 2594. Minimum Time to Repair Cars

### ISSUE THREAD

**Issue by kyaryunha** [LeetCode-Feedback/LeetCode-Feedback#12428]
#### Your LeetCode username
kyaryunha 

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases

#### Description of the bug
ans is the maximum value, but when right is not large enough in binary search, the code is correct.

#### Code you used for Submit/Run operation
```cpp
#define ll long long 
class Solution {
public:
    long long repairCars(vector<int>& ranks, int cars) {
        ll le = 1;
        ll ri = 1000000LL*1000000LL;
        ll ans= 100LL*1000000LL*1000000LL;
        while(le<=ri) {
            ll mid = (le + ri) /2;
            bool pos = false;
            ll cnt = 0LL;
            for(ll rank:ranks) {
                cnt += (ll)sqrt(mid/rank);
            }
            if(cnt>=cars) pos = true;
            
            if(pos) {
                ri = mid - 1LL;
                ans = min(ans, mid);
            }
            else {
                le = mid + 1LL;
            }
        }
        return ans;
    }
};
```

#### Language used for code
C++ 

#### Expected behavior
nums=99
cars=1000000
expected=99000000000000

but code return 100000000000000

#### Additional context
https://leetcode.com/submissions/detail/917617045/

![image](https://user-images.githubusercontent.com/37409087/226123681-420322eb-bcbd-48e1-af0c-c745178ec5c5.png)

![image](https://user-images.githubusercontent.com/37409087/226130495-42ccbdb5-601f-443c-a527-db3a9f9ff43c.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
