### ISSUE TITLE
Missing Test Case - 1528. Shuffle String

### ISSUE THREAD

**Issue by sujeetmohanty11** [LeetCode-Feedback/LeetCode-Feedback#12429]
#### Your LeetCode username
sujeetmohanty11

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [*] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution(object):
    def restoreString(self, s, indices):
        """
        :type s: str
        :type indices: List[int]
        :rtype: str
        """
        txt = ""
        for i in range(len(indices)):
            txt += s[indices[i]]

        return txt
```

#### Language used for code
Python

#### Expected behavior
This test case is wrong 
It should cdoe as per following indexes.

c o d e - c d o e
0 1 2 3 -> 0 2 1 3

#### Screenshots
<img width="307" alt="Screenshot 2023-03-18 at 11 32 44 PM" src="https://user-images.githubusercontent.com/121731587/226125880-950f7631-dc3a-4911-b632-e4581c07bdbf.png">

**Comment by nskybytskyi** [comment]
Thank you for reaching out to us. 

Please refer to #11367, #10519, or #10075 for an explanation of this behavior. Please look through the already existing issues for a problem before opening a new one in the future.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
