### ISSUE TITLE
1673. Find the Most Competitive Subsequence: Typo in editorial

### ISSUE THREAD

**Issue by migonin** [LeetCode-Feedback/LeetCode-Feedback#12422]
#### Your LeetCode username
[mike_igonin](https://leetcode.com/mike_igonin/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

There is a typo in editorial: first, we say that k is 2, then say it's 3, than subsequences is of size 2 again:

> Let nums = [2, 3, 4] and k = **2**.
> We could generate three subsequences of size **3** from the given nums array, **seq1:[2, 3], seq2:[2, 4], seq3:[3, 4]**.
> 

#### Expected behavior
> Let nums = [2, 3, 4] and k = 2.
> We could generate three subsequences of size **2** from the given nums array, seq1:[2, 3], seq2:[2, 4], seq3:[3, 4].
> 

#### Screenshots

<img width="782" alt="Снимок экрана 2023-03-18 в 19 23 52" src="https://user-images.githubusercontent.com/4037563/226114979-a05649c4-51eb-4f84-b195-c6f9af0a33f3.png">

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
