### ISSUE TITLE
Missing Test Case -1622. Fancy Sequence

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#1243]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution is accepted but fails on the following test case:

["Fancy","addAll","getIndex"]
[[],[1],[0]]

#### Code you used for Submit/Run operation

```
import java.math.*; 
class Fancy {
    int mod=1000000007;
    long A[]=new long[100010];
    long B[]=new long[100010];
    long C[]=new long[100010];
    int index=-1;
    public void append(int val) {
        index++;
        A[index]=val;
        B[index]=0;
        C[index]=1;
        if(index>0){
            B[index]=B[index-1];
            C[index]=C[index-1];
        }
    }
    
    public void addAll(int inc) {
        B[index]+=inc;B[index]%=mod;
    }
    
    public void multAll(int m) {
        B[index]*=m;
        B[index]%=mod;
        C[index]*=m;
        C[index]%=mod;
    }
    
    public int getIndex(int idx) {
        if(idx>index)return -1;
        long ori=A[idx];
        long pre=get(B,idx-1);
        long tomul=CC(index,idx-1);
        long toadd=B[index]-(get(B,idx-1)*tomul)%mod;
        if(toadd<0)toadd+=mod;
        ori=ori*tomul+toadd;
        return (int)(ori%mod);
    }
    public long CC(int i,int j){
        if(j<0)return C[i];
		long mod=1000000007;
		long a=C[i];
		long b=C[j];
		BigInteger B= BigInteger.valueOf(b);
		long binverse=B.modInverse(BigInteger.valueOf(mod)).longValue();
		return ((a)*(binverse%mod))%mod;
	}
    public long get(long arr[],int i){
        if(i<0)return 0;
        return arr[i];
    }
}

/**
 * Your Fancy object will be instantiated and called as such:
 * Fancy obj = new Fancy();
 * obj.append(val);
 * obj.addAll(inc);
 * obj.multAll(m);
 * int param_4 = obj.getIndex(idx);
 */
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/96367702-72a3e700-111d-11eb-9052-5c0d2eabb14e.png)
![image](https://user-images.githubusercontent.com/32546406/96367711-82bbc680-111d-11eb-8c59-6a23745c67be.png)

#### Additional context

https://leetcode.com/problems/fancy-sequence/discuss/899104/Java-inverse-mod

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
