### ISSUE TITLE
Missing Test Case - 2446. Determine if Two Events Have Conflict

### ISSUE THREAD

**Issue by DJ-Dav** [LeetCode-Feedback/LeetCode-Feedback#12434]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [y] Missing Test Cases 

#### Description of the bug

this code passes, but doesn't work if the end of event2 conflicts with the start of event1

#### Code you used for Submit/Run operation

```
class Solution:
    def haveConflict(self, event1: List[str], event2: List[str]) -> bool:
        time1s = event1[0].split(":")
        time1s = int(time1s[0])*60 + int(time1s[1])
        time2s = event2[0].split(":")
        time2s = int(time2s[0])*60 + int(time2s[1])

        time1e = event1[1].split(":")
        time1e = int(time1e[0])*60 + int(time1e[1])
        time2e = event2[1].split(":")
        time2e = int(time2e[0])*60 + int(time2e[1])

        if (time1e >= time2s) and (time1s < time2e):
            return True
        return False

```

#### Language used for code

Python

#### Expected behavior

One test case should fail, as described above

#### Additional context

one solution would be to add the test case
event1 = ["05:30","07:30"]
event2 = ["07:00","09:30"]

**Comment by nskybytskyi** [comment]
Thank you for reaching out to us. 

When I submit your code it fails on the following test case:

<img width="200" alt="Знімок екрана 2023-03-18 о 22 36 40" src="https://user-images.githubusercontent.com/25816558/226137521-a461a5df-93bc-490d-8008-1f3d450434b0.png">

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
