### ISSUE TITLE
Weekly contest 337 problem C

### ISSUE THREAD

**Issue by sauravbharti021** [LeetCode-Feedback/LeetCode-Feedback#12439]
#### Your LeetCode username

sauravbharti021

#### Category of the bug
- [ ] Question
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

In Leetcode Weekly contest 337 problem C - (2597. The Number of Beautiful Subsets),

I wrote 3 codes, One was 2e7 * log(n). This gave me TLE in C++, I thought maybe because I'm using a data structure, then I tried using a vector and complexity came down to 2e7. Still, I got TLE then I switched the language from C++ to JAVA and it passed quite smoothly. I want to say that this is absurd. C++ is the fastest language for Contests in all platforms and here you are giving TLE on a code with 2e7 complexity.

#### Code you used for Submit/Run operation

```
#define ll long long
#define pi (3.141592653589)
#define mod 1000000007
#define float double
#define pb push_back
#define mp make_pair
#define ff first
#define ss second
#define all(c) c.begin(), c.end()
#define min3(a, b, c) min(c, min(a, b))
#define min4(a, b, c, d) min(d, min(c, min(a, b)))
#define rrep(i, n) for(int i=n-1;i>=0;i--)
#define rep(i,n) for(int i=0;i<n;i++)
class Solution {
public:
    int beautifulSubsets(vector<int>& nums, int k) {
        ll n= nums.size();
        ll cnt=0;
        
        rep(i, (1<<n)){
            vector<ll> f;
            map<ll, ll> m;
            rep(j, n){
                
                if( (i & (1<<j))) {f.pb(nums[j]); m[nums[j]]++; }
            }
            if(f.size()==0) continue;
            
            ll flag=0;
            rep(j,f.size()){
                ll x= f[j] + k;
                ll y= f[j] - k;
                
                if(m.find(x)!=m.end()) { flag=1; break; }
                if(m.find(y)!= m.end()) { flag=1; break; }
            }
            
            if(!flag) cnt++;
            
        }
        
        return cnt;
    }
};
```
**Verdict -TLE**

*2nd - Complexity is now 2e7*

```
#define ll long long
#define pi (3.141592653589)
#define mod 1000000007
#define float double
#define pb push_back
#define mp make_pair
#define ff first
#define ss second
#define all(c) c.begin(), c.end()
#define min3(a, b, c) min(c, min(a, b))
#define min4(a, b, c, d) min(d, min(c, min(a, b)))
#define rrep(i, n) for(int i=n-1;i>=0;i--)
#define rep(i,n) for(int i=0;i<n;i++)
class Solution {
public:
    int beautifulSubsets(vector<int>& nums, int k) {
        ll n= nums.size();
        ll cnt=0;
        
        // cout<<n<<"\n";
        
        
        vector<int> fre(1001, 0);
        rep(i, (1<<n)){
             ll flag=0;
            ll lol=0;
            rep(j, n){
                
                if( (i & (1<<j))) {                 
                    fre[nums[j]]++; 
                    int x= nums[j] + k;
                    int y= nums[j] - k;
                    lol++;
                    if(x>=1 && x<=1000 && fre[x]>0 ) { flag=1; break; }
                    if(y>=1 && y<=1000 && fre[y]>0) { flag=1; break; }
                  }
                
            }
            if(lol==0 ) continue;
            rep(j,n){
                fre[nums[j]]=0;
            }
            
       
            
            if(!flag) cnt++;
            
        }
        
        
        return cnt;
    }
};
```

**Verdict - This got TLE too**

*3rd now i TRIED same code in JAVA,*

```
class Solution {
    public int beautifulSubsets(int[] nums, int k) {
        int n= nums.length;
        int cnt=0;

        int[] fre = new int[1001];
        for (int i = 0; i < (1<<n); i++) {
            int flag=0;
            int lol=0;
            for (int j = 0; j < n; j++) {

                if( (i & (1<<j)) != 0) {
                    fre[nums[j]]++;
                    int x= nums[j] + k;
                    int y= nums[j] - k;
                    lol++;
                    if(x>=1 && x<=1000 && fre[x]>0 ) { flag=1; break; }
                    if(y>=1 && y<=1000 && fre[y]>0) { flag=1; break; }
                }

            }
            if(lol==0 ) continue;
            for (int j = 0; j < n; j++) {
                fre[nums[j]]=0;
            }

            if(flag == 0) cnt++;
        }

        return cnt;
    
        
    }
}
```
**Verdict - It passed quite comfortably with time complexity at 1300ms.**

#### Language used for code

C++ and JAVA

#### Expected behavior

First two codes should have passed as overall complexity is less than 1e8. And usually it takes 1 second to run O(1e8). If anything then at least 2nd code written should have passed. It is exact copy of accepted code in JAVA. 
C++ is the fastest language for contests in all other coding platforms.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly, this depends on language-specific implemented libraries, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!  If the issue persists, don't hesitate to let us know!

**Comment by sauravbharti021** [comment]
> Thank you for reaching out to us, the judger appears to be working correctly, this depends on language-specific implemented libraries, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes! If the issue persists, don't hesitate to let us know!

That's ridiculous even after using an array in C++ it still gives TLE. This can't be library issue. 
Submission link - "https://leetcode.com/submissions/detail/918791167/"

It now becomes the platforms responsibility to design the judge so that fairness is done to all languages especially widely used programming language like C++ . This is partiality towards JAVA. This is not a minor issue, you are accepting same code in one language and failing in other.
