### ISSUE TITLE
Missing Test Case - 5. Longest Palindromic Substring

### ISSUE THREAD

**Issue by Kevinoop123** [LeetCode-Feedback/LeetCode-Feedback#12435]
#### Your LeetCode username
KevinLi02

#### Category of the bug

- [x] Solution

#### Code you used for Submit/Run operation

```
// 5. Longest Palindromic Substring
def longestPalindrome(self, str):
        """
        :type s: str
        :rtype: str
        """
        S = list(str)
        n = len(S)


        MaxLength = [[0]*n for i in range(n)]
        Sequence = [[""]*n for i in range(n)]


        # base cases
        for i in range(n):
            MaxLength[i][i] = 1
            Sequence[i][i] = S[i]

        # calculate MaxLength and Sequence for all subarrays of S
        for length in range(2, n+1):
            for i in range(n-length+1):
                j = i + length - 1
                if S[i] == S[j]:
                    MaxLength[i][j] = 2 + MaxLength[i+1][j-1]
                    Sequence[i][j] = S[i] + Sequence[i+1][j-1] + S[j]
                else:
                    if MaxLength[i+1][j] > MaxLength[i][j-1]:
                        MaxLength[i][j] = MaxLength[i+1][j]
                        Sequence[i][j] = Sequence[i+1][j]
                    else:
                        MaxLength[i][j] = MaxLength[i][j-1]
                        Sequence[i][j] = Sequence[i][j-1]
        return Sequence[0][n-1]
    
```

#### Language used for code

 Python

#### Expected behavior

I think the correct answer for case:"aacabdkacaa" should be "aacabacaa" instead of "aca" in the Leetcode Answer

**Comment by nskybytskyi** [comment]
Thank you for reaching out to us.

A quote from the pop-up that appears when you hover over the word "substring" in the statement:

> A **substring** is a contiguous non-empty sequence of characters within a string.

`"aacabacaa"` is hence not a substring of `"aacabdkacaa"` since its characters are not consecutive. Perhaps your solution finds the [longest palindromic subsequence](https://leetcode.com/problems/longest-palindromic-subsequence/) (problem no. 516) instead? 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Comment by Kevinoop123** [comment]
> Thank you for reaching out to us.
> 
> A quote from the pop-up that appears when you hover over the word "substring" in the statement:
> 
> > A **substring** is a contiguous non-empty sequence of characters within a string.
> 
> `"aacabacaa"` is hence not a substring of `"aacabdkacaa"` since its characters are not consecutive. Perhaps your solution finds the [longest palindromic subsequence](https://leetcode.com/problems/longest-palindromic-subsequence/) (problem no. 516) instead?
> 
> We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

Okay, I got it. Thank you!
