### ISSUE TITLE
6352. 美丽子集的数目 遗漏测试数据

### ISSUE THREAD

**Issue by zouyu9631** [LeetCode-Feedback/LeetCode-Feedback#12440]
**你的 LeetCode 用户名**
FreeYourMind

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述**
缺少类似以下的测试数据：
```
[1,2,3,3]
1
```

**你使用的语言**
python

**你提交或者运行的代码**
```
class Solution:
    def beautifulSubsets(self, a: List[int], k: int) -> int:
        a.sort()
        n = len(a)
        s = set(a)
        ls = []
        d = {}
        for x in a:
            if x - k not in s:
                ls.append(1)
                d[x] = len(ls) - 1
            else:
                d[x] = d[x - k]
                ls[d[x]] += 1
        
        m = max(ls)
        f = [[1, 1] for _ in range(m)]
        for i in range(1, m):
            f[i][0] = sum(f[i - 1])
            f[i][1] = f[i - 1][0]

        ans = 1
        for x in ls:
            ans *= sum(f[x - 1])
        return ans - 1

```

**期望行为**
以上通过的代码，实际是错误的。正确答案是8，但该代码返回7

**屏幕截图**
![image](https://user-images.githubusercontent.com/6801919/226154613-b7281d41-e56c-4a5b-9138-d4bb247c2e88.png)
![image](https://user-images.githubusercontent.com/6801919/226154633-a602147b-4155-4fbf-a344-adbab8416cb3.png)

**Comment by feiceh** [comment]
你好，当前题目已更新，积分奖励已发放，请查收
