### ISSUE TITLE
Missing Test Case - 2597. The Number of Beautiful Subsets

### ISSUE THREAD

**Issue by akgupta20** [LeetCode-Feedback/LeetCode-Feedback#12445]
#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

when element of given array are equals.
 nums =[2,4,4,6] k =2

#### Code you used for Submit/Run operation

```
// 2597. The Number of Beautiful Subsets 
class Solution {
public:
    int ans=0;
    vector<int>v;
    void solve(vector<int>&nums,int k,int idx)
    {
        if(idx==nums.size())
        { 
            ans++;
            return ;
        }
        
        int num=nums[idx];
        if(num-k<0 or (num-k>=0 and v[num-k]==0) )
        {
            v[num]+=1;
            
            solve(nums,k,idx+1);
            
            v[num]-=1;
        }
        
       
        solve(nums,k,idx+1);
    }
    int beautifulSubsets(vector<int>& nums, int k) {
        
        sort(nums.begin(),nums.end());
        v.resize(1001);
        solve(nums,k,0);
       
        return ans-1;
    }
};
```

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

The test case already exists.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
<img width="190" alt="Screen Shot 2023-03-19 at 7 38 55 PM" src="https://user-images.githubusercontent.com/103138242/226217035-13866d03-a727-4964-817d-9eef6a00147f.png">

**Comment by akgupta20** [comment]
The testcase is not exist because my code(uncorrect) also got accepted
recently after your mail.
Below is my code is mentioned.
class Solution {
public:
    int ans=0;
    vector<int>v;
    void solve(vector<int>&nums,int k,int idx)
    {
        if(idx==nums.size())
        {
            ans++;
            return ;
        }

        int num=nums[idx];
        if(num-k<0 or (num-k>=0 and v[num-k]==0) )
        {
            v[num]=1; // Issue first

            solve(nums,k,idx+1);

            v[num]=0; // Issue second
        }


        solve(nums,k,idx+1);
    }
    int beautifulSubsets(vector<int>& nums, int k) {

        sort(nums.begin(),nums.end());
        v.resize(1001);
        solve(nums,k,0);

        return ans-1;
    }
};
