### ISSUE TITLE
Missing Test Case -1622. Fancy Sequence

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#1244]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution is accepted but fails on the following test case:

["Fancy", "append", "multAll", "multAll", "addAll", "addAll", "addAll", "append", "append", "append", "append", "multAll", "append", "multAll", "addAll", "append", "multAll", "addAll", "append", "append", "append", "append", "multAll", "append", "multAll", "append", "multAll", "addAll", "addAll", "append", "append", "multAll", "addAll", "addAll", "multAll", "addAll", "addAll", "addAll", "addAll", "addAll", "addAll", "addAll", "append", "append", "multAll", "addAll", "addAll", "append", "addAll","append", "append", "append", "addAll", "addAll", "addAll", "multAll", "addAll", "append", "multAll", "multAll", "append", "addAll", "append", "addAll", "multAll", "addAll", "addAll", "addAll", "append", "addAll", "addAll", "append", "multAll", "addAll", "append", "append", "multAll", "append", "addAll", "multAll", "multAll", "multAll", "addAll", "multAll", "multAll", "multAll", "addAll", "multAll", "append", "getIndex"]
[[], [59], [74], [4], [30], [85], [2], [83], [70], [93], [14], [71], [32], [65], [20], [17], [16], [32], [95], [40], [76], [77], [56], [49], [60], [93], [85], [76], [93], [29], [87], [17], [76], [80], [61], [77], [60], [24], [71], [4], [15], [96], [99], [46], [84], [41], [86], [24], [52], [89], [20], [50], [85], [1], [16], [56], [15], [70], [77], [53], [16], [63], [22], [12], [65], [73], [32], [82], [98], [16], [95], [79], [72], [90], [23], [69], [90], [67], [45], [93], [26], [51], [22], [76], [10], [50], [62], [12], [36], [2]]

#### Code you used for Submit/Run operation

```
class Fancy {

    List<Boolean> op;
    List<Long> vals;
    long[] num;
    int[] joined;
    int cnt = 0;
    
    long accuAdd = 0;
    long accuMul = 1;
    boolean combo = false;
    
    
    public Fancy() {
        op = new ArrayList<Boolean>();
        vals = new ArrayList<Long>();
        num = new long[50000];
        joined = new int[50000];
        cnt = 0;
        
        accuAdd = 0;
        accuMul = 1;
        combo = false;
    }
    
    public void append(int val) {
        num[cnt] = (long) val;
        if(combo){
            if(accuMul != 1){
                op.add(false);
                vals.add(accuMul);
            }
            if(accuAdd != 0){
                op.add(true);
                vals.add(accuAdd);
            }
            combo = false;
            accuAdd = 0;
            accuMul = 1;
        }
        joined[cnt] = op.size();
    
        //System.out.println("appending " + val + " with vals = " + vals + ", op = " + op);
        cnt++;
        //cnt++;
    }
    
    public void addAll(int inc) {
        combo = true;
        accuAdd += (long)inc;
    }
    
    public void multAll(int m) {
        combo = true;
        accuMul *= (long)m;
        accuAdd *= (long)m;
    }
    
    public int getIndex(int idx) {
        if(idx >= cnt) return -1;
        long cur = num[idx];
        for(int i = joined[idx]; i < vals.size(); i++){
            if(op.get(i)){
                cur += vals.get(i);
                //cur %= 1000000007;
            }
            else{
                cur *= vals.get(i);
                cur %= 1000000007;
            }
        }
        cur *= accuMul;
        //cur %= 1000000007;
        cur += accuAdd;
        cur %= 1000000007;
        
        return (int) cur;
    }
}

/**
 * Your Fancy object will be instantiated and called as such:
 * Fancy obj = new Fancy();
 * obj.append(val);
 * obj.addAll(inc);
 * obj.multAll(m);
 * int param_4 = obj.getIndex(idx);
 */
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/96370760-f74a3180-112c-11eb-92eb-807046ef905d.png)
![image](https://user-images.githubusercontent.com/32546406/96370785-0630e400-112d-11eb-9277-3259d65190f5.png)

**Comment by lc-kay** [comment]
@IgorRud We have updated this problem and the submission you included now received WA. Thank you for your time and support.
