### ISSUE TITLE
Editorial solution issue -585. Investments in 2016

### ISSUE THREAD

**Issue by AOkun1205** [LeetCode-Feedback/LeetCode-Feedback#12453]
LeetCode username - AOkun1205

- [ ] Solution

Description of the bug

In editorial solution round() is missing it runs the for the first testcase as it isn't a decimal and fails others as it only accept till 2 decimal places 
#### Code you used for Submit/Run operation

```
SELECT
    ROUND(SUM(insurance.TIV_2016),2) AS TIV_2016
FROM
    insurance
WHERE
    insurance.TIV_2015 IN
    (
      SELECT
        TIV_2015
      FROM
        insurance
      GROUP BY TIV_2015
      HAVING COUNT(*) > 1
    )
    AND CONCAT(LAT, LON) IN
    (
      SELECT
        CONCAT(LAT, LON)
      FROM
        insurance
      GROUP BY LAT , LON
      HAVING COUNT(*) = 1
    )
;
```

Language used for code
SQL

#### Screenshots

Editorial solution - solution failed
![image](https://user-images.githubusercontent.com/92986203/226173117-189810a6-58ee-4234-afa9-1fcce93e1a51.png)

After adding round to editorial solution - passed
![image](https://user-images.githubusercontent.com/92986203/226173162-4ced65bd-4409-4ff0-bb29-d7a0f453422d.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
