### ISSUE TITLE
Missing Test Case - 2597. The Number of Beautiful Subsets

### ISSUE THREAD

**Issue by sharmasoumyadip** [LeetCode-Feedback/LeetCode-Feedback#12450]
#### Your LeetCode username
sharmasoumyadip

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
An wrong solution gets accepted, due to missing test cases.
Any input with duplicate number in the input array and for that duplicate number if there is another number with absolute difference k, i.e. an number which should not be included in the subset, and if the number occurs in the array after both the instances of the duplicate number, the code will give wrong answer.
for the input array nums with n elements.
If 3 indices for which i,j & k,
nums[i]=nums[j] && |nums[i]-nums[k]|==difference we should not include in our subset
and i≠j and 0<i<j<k<l
The given solution gives WA. This test case is missing.

Example Testcase: [2,2,4]

#### Code you used for Submit/Run operation

```
class Solution {
    int ans;
    private void rec(int[] nums,int idx,int l,int k,Set<Integer> set){
        if(idx==l) return;
        int curr=nums[idx];
        if(!set.contains(curr-k) && !set.contains(curr+k)){
            ans++;
            set.add(curr);
            rec(nums,idx+1,l,k,set);
            set.remove(curr);
        }
        rec(nums,idx+1,l,k,set);
        
    }
    public int beautifulSubsets(int[] nums, int k) {
        ans=0;
        rec(nums,0,nums.length,k,new HashSet<Integer>());
        return ans;
    }
}
```

#### Language used for code
Java

#### Expected behavior
The solution should not be accepted.

#### Screenshots
<img width="957" alt="image" src="https://user-images.githubusercontent.com/29679880/226163098-80f38179-8291-494a-a6d6-c1d812d3ba1a.png">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
