### ISSUE TITLE
Missing Test Case - 211. Design Add and Search Words Data Structure

### ISSUE THREAD

**Issue by Tudor67** [LeetCode-Feedback/LeetCode-Feedback#12460]
#### Your LeetCode username

[Tudor67](https://leetcode.com/Tudor67/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My solution passed all the test cases and was accepted,
but I found a test case that exceeds the time limit (TLE).

**_The TLE test case:_**
**_Method calls:_** `["WordDictionary","addWord","addWord","addWord","addWord",......,"search","search"]`
9000 `addWord` calls followed by 1000 `search` calls;

**_Method parameters:_** `[[],["aaadddddddddddddddddddddd"],["aabdddddddddddddddddddddd"],["aacdddddddddddddddddddddd"],.................,["nibdddddddddddddddddddddd"],["nicdddddddddddddddddddddd"],["niddddddddddddddddddddddd"],.................,["...dddddddddddddddddddddz"],["...dddddddddddddddddddddz"]]`

For the first 9000 `addWord` calls I generated 9000 distinct strings of form `c1` + `c2` + `c3` + `dddddddddddddddddddddd`;
c1, c2, c3 are chars from the range ['a' .. 'z'] and + is the concatenation operation;
The length of all strings is 25 (distinct prefixes of size 3 + constant suffix of size 22);

For the next 1000 `search` calls I generated the constant string `...dddddddddddddddddddddz`;
The length of the string is 25 (constant prefix `...` of size 3 and constant suffix `dddddddddddddddddddddz` of size 22);

**_Test:_** [test_for_prob_211.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/11011826/test_for_prob_211.txt)

**_Generator:_** [generator_code.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/11011842/generator_code.txt)

#### Code you used for Submit/Run operation

[Submission Link](https://leetcode.com/problems/design-add-and-search-words-data-structure/submissions/918129291/)
``` C++
// 211. Design Add and Search Words Data Structure
// C++
class Trie{
private:
    static const int ALPHABET_SIZE = 26;
    static const int FIRST_CHAR = 'a';
    static const int SPECIAL_CHAR = '.';
    bool isTerminalNode;
    Trie* children[ALPHABET_SIZE];

    bool search(const string& WORD, int index, Trie* node){
        if(index == (int)WORD.length()){
            return node->isTerminalNode;
        }
        bool found = false;
        int firstEdgeID = (WORD[index] == SPECIAL_CHAR ? 0 : WORD[index] - FIRST_CHAR);
        int lastEdgeID = (WORD[index] == SPECIAL_CHAR ? ALPHABET_SIZE - 1 : WORD[index] - FIRST_CHAR);
        for(int edgeID = firstEdgeID; !found && edgeID <= lastEdgeID; ++edgeID){
            if(node->children[edgeID] != nullptr){
                found = found || search(WORD, index + 1, node->children[edgeID]);
            }
        }
        return found;
    }

public:
    Trie(){
        isTerminalNode = false;
        fill(children, children + ALPHABET_SIZE, nullptr);
    }

    ~Trie(){
        for(int edgeID = 0; edgeID < ALPHABET_SIZE; ++edgeID){
            delete children[edgeID];
        }
    }

    void insert(const string& WORD){
        Trie* node = this;
        for(char c: WORD){
            int edgeID = c - FIRST_CHAR;
            if(node->children[edgeID] == nullptr){
                node->children[edgeID] = new Trie();
            }
            node = node->children[edgeID];
        }
        node->isTerminalNode = true;
    }

    bool search(const string& WORD){
        return search(WORD, 0, this);
    }
};

class WordDictionary {
private:
    Trie trie;

public:
    WordDictionary() {
        
    }
    
    void addWord(string word) {
        trie.insert(word);
    }
    
    bool search(string word) {
        return trie.search(word);
    }
};

/**
 * Your WordDictionary object will be instantiated and called as such:
 * WordDictionary* obj = new WordDictionary();
 * obj->addWord(word);
 * bool param_2 = obj->search(word);
 */
```

#### Language used for code

C++

#### Expected behavior

TLE

#### Screenshots

![Prob_211_TLE](https://user-images.githubusercontent.com/12481060/226195485-40cd5141-9a98-471c-b7b1-0d1f86c97436.png)

#### Additional context

The problem occurs when we **insert many** words with **distinct prefixes** in a `trie`  
and later try to **search words** with **prefixes containing 3 dots** `...`.  

In that scenario, the `search` method of the `trie` is inefficient,  
because we visit almost all the nodes of `trie` in a single call of the `search` method.  

When we **call** the **search** method **~1000 times** we exceed the time limit of the problem.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

Changed the limits on this problem.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
