### ISSUE TITLE
Explain more in detail - 38. Count and Say

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1246]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

https://leetcode.com/problems/count-and-say/
38. Count and Say

Please read the below links:

- https://leetcode.com/problems/count-and-say/discuss/198945/What-does-this-fucking-question-meaning

- https://leetcode.com/problems/count-and-say/discuss/16015/Please-change-the-misleading-description
- https://leetcode.com/problems/count-and-say/discuss/144455/Another-way-of-describing-this-problem
- https://leetcode.com/problems/count-and-say/discuss/621869/Finally-Understood-this.-Explanation

1. Please reword in natural English.

For example:

    111223
    There are 3 ones, then 2 twos, and then 1 three
    So it is 312213

2. Remove the serial numbers

	Change from:

		1.     1
		2.     11
		3.     21
		4.     1211
		5.     111221

	to:

		1
		11
		21
		1211
		111221

This is because you are explaining the sequence, and add sequence number will confuse users.

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JavaScript

#### Expected behavior

- Description should be easier to read for someone with only Simple English https://simple.wikipedia.org/wiki/Main_Page
- Review is needed once the problem is written
- The reviewer should not be given any help in understanding the question, other than the question itself.
- The reviewer must adhere to Simple English

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
