### ISSUE TITLE
Incomplete Problem Description in 605 - Can Place Flowers

### ISSUE THREAD

**Issue by a-r-r-o-w** [LeetCode-Feedback/LeetCode-Feedback#12464]
#### Your LeetCode username

Aryan-V-S

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The problem statement for [605 - Can Place Flowers] does not state what you should return (whether true or false - as in the statement is slightly incomplete). The current statement is:

```
You have a long flowerbed in which some of the plots are planted, and some are not. However, flowers cannot be planted in adjacent plots.

Given an integer array flowerbed containing 0's and 1's, where 0 means empty and 1 means not empty, and an integer n, return if n new flowers can be planted in the flowerbed without violating the no-adjacent-flowers rule.
```

However, it should be something like:

```
You have a long flowerbed in which some of the plots are planted, and some are not. However, flowers cannot be planted in adjacent plots.

Given an integer array flowerbed containing 0's and 1's, where 0 means empty and 1 means not empty, and an integer n, return `true` if n new flowers can be planted in the flowerbed without violating the no-adjacent-flowers rule else `false`.
```

![1](https://user-images.githubusercontent.com/72266394/226218967-41b59f22-e7c0-4b90-907a-1e5132bddd04.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
