### ISSUE TITLE
Missing Test Case - 1233. Remove Sub-Folders from the Filesystem

### ISSUE THREAD

**Issue by Salman-Mandal** [LeetCode-Feedback/LeetCode-Feedback#12470]
#### Your LeetCode username
iamsalman28818 
[Profile](https://leetcode.com/iamsalman28818/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [+]  Missing Test Cases 

#### Description of the bug

The Problem -"1233. Remove Sub-Folders from the Filesystem" missing a testcase where my code gives wrong output but when i submit the code it shows accepted.
I provided a screenshot below.
and here- my [Solution](https://leetcode.com/problems/remove-sub-folders-from-the-filesystem/solutions/3318850/c/) 
#### Code you used for Submit/Run operation

```
class Trie
{
    public:
    Trie *links[26];
    bool flag=false;
    bool isContains(char ch)
    {
        return links[ch-'a'];
    }
    void put(char ch,Trie* node)
    {
        links[ch-'a']=node;
    }
    Trie *get(char ch)
    {
        return links[ch-'a'];
    }
    void SetEnd()
    {
        flag=true;
    }
    bool IsEnd()
    {
        return flag;
    }

};

class Solution {
Trie * root;
bool insert(string w)
{
    int n=w.size();
    Trie *node=root;
    for(int i=0;i<n;i++)
    {
        char ch=w[i];
        if(ch=='/') continue;
        else if(!node->isContains(ch))
        {
            node->put(ch,new Trie());
        }
        node=node->get(ch);
        if(i+1<n && w[i+1]=='/' && node->IsEnd()) return false;
    }
    node->SetEnd();
    return true;
}
public:
    vector<string> removeSubfolders(vector<string>& folder) {
        root=new Trie();
        sort(folder.begin(),folder.end());
        
        vector<string> ans;
        for(string word:folder)
        {
            if(insert(word))
            {
                ans.push_back(word);
            }
        }
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The testcase is [/a/b/c,/abc/d] . for this testcase my code (and i show others also) is wrong and it should not be accepted.

#### Screenshots

![image](https://user-images.githubusercontent.com/76894465/226265771-6a76874f-dcf6-4008-8abd-83c24ac2165e.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
