### ISSUE TITLE
Missing Test Case - 2597. The Number of Beautiful Subsets

### ISSUE THREAD

**Issue by muller2333** [LeetCode-Feedback/LeetCode-Feedback#12472]
#### Your LeetCode username
muller2333

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

An accepted solution fails on the following testcase:
nums = [1,1,2,2,3,3]
k = 1

#### Code you used for Submit/Run operation

```
import java.util.HashMap;
import java.util.Map;

class Solution {
    public int beautifulSubsets(int[] nums, int k) {
        int[] ret = {0};
        Map<Integer, Integer> dic = new HashMap<>();
        int m = nums.length;
        dfs(nums, k, dic, ret, m, 0);
        return ret[0] - 1;
    }

    private void dfs(int[] nums, int k, Map<Integer, Integer> dic, int[] ret, int m, int ids) {
        if (ids == m) {
            ret[0]++;
            return;
        }
        if ((!dic.containsKey(nums[ids] - k) || dic.get(nums[ids] - k) == 0) && (!dic.containsKey(nums[ids] + k) || dic.get(nums[ids] + k) == 0)) {
            dic.put(nums[ids], 1);
            dfs(nums, k, dic, ret, m, ids + 1);
            dic.put(nums[ids], 0);
        }
        dfs(nums, k, dic, ret, m, ids + 1);
    }
}

```

#### Language used for code
Java

#### Screenshots

![1679300685093](https://user-images.githubusercontent.com/25950952/226285022-98ba48f7-730a-44f5-a4c6-b0db1eb81f0d.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
