### ISSUE TITLE
Missing Test Case - 1012. Numbers With Repeated Digits

### ISSUE THREAD

**Issue by WarmheartedYang** [LeetCode-Feedback/LeetCode-Feedback#12483]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
jovial-spencea38

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述**
缺少类似以下的测试数据（题目中n的范围是1≤n≤1e9）：
```
输入：n = 1000000000
输出：994388230
```

**你使用的语言**
C++

**你提交或者运行的代码**
```
class Solution {
public:
    int dp[9][1<<10];
    string s;
    int len;
    int dfs(int pos,int mask,bool limit,bool zero){
        if(pos==len){
            return 1;
        }
        if(!limit&&!zero&&dp[pos][mask]!=-1){
            return dp[pos][mask];
        }
        int res=0;
        int top=limit?s[pos]-'0':9;
        for(int i=0;i<=top;i++){
            if(zero&&i==0){
                res+=dfs(pos+1,mask,limit&&i==top,1);
            }else{
                int nmask=mask|(1<<i);
                if(nmask!=mask){
                    res+=dfs(pos+1,nmask,limit&&i==top,0);
                }
            }
        }
        if(!limit&&!zero){
            dp[pos][mask]=res;
        }
        return res;
    }
    int numDupDigitsAtMostN(int n) {
        s=to_string(n);
        len=s.size();
        memset(dp,-1,sizeof(dp));
        return n+1-dfs(0,0,1,1);
    }
};
```

**期望行为**
由于输入1e9，1e9的十进制位数有10位，但是dp数组的第一维只有9位，此时应该会出现段错误，但是提交后显示通过，说明测试用例中缺少这组测试用例，因而让错误的代码通过了题目。

**屏幕截图**
题目中n的范围是1≤n≤1e9
![image](https://user-images.githubusercontent.com/63245100/226423090-dd1d5a19-9d71-411c-a650-dd4ca46cfd0b.png)

在用户自定义样例输入界面输入 n = 1000000000
![image](https://user-images.githubusercontent.com/63245100/226423486-565d0845-6120-44b5-962a-01cd91266bb8.png)

此时会出现段错误
![image](https://user-images.githubusercontent.com/63245100/226423291-33d3a41f-1322-4738-8c28-09ea4a6192d5.png)

但是该错误的代码提交后却可以通过
![image](https://user-images.githubusercontent.com/63245100/226422223-38a64ed2-f5b8-4388-bfdf-9a4317d019a3.png)

**额外的上下文**
添加额外的上下文信息

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
