### ISSUE TITLE
Missing Test Case - 605. Can Place Flowers

### ISSUE THREAD

**Issue by jgera** [LeetCode-Feedback/LeetCode-Feedback#12486]
#### Category of the bug
- [ ] Question
- [o ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
var canPlaceFlowers = function(flowerbed, n) {

let nn = 0;
let l = flowerbed.length
for (let idx = 0; idx < l; idx++) {

       idx != 0 ? left = flowerbed[idx-1] : left = 0
       idx == l-1 ?  right = 0: right = flowerbed[idx+1]

       if(left == 0 && flowerbed[idx] == 0 && right == 0){
        nn++;
        flowerbed[idx] = 1
       }
}
return nn == n;
    
};  
```

#### Expected behavior

input 
flowerbed = [0,0,1,0,0], n = 1 

result should be 
flowerbed = [1,0,1,0,1]
and n should be 2 because of n =1 the unit test fails

#### Screenshots

![image](https://user-images.githubusercontent.com/5672563/226451455-a0319701-e434-4a7a-bc85-0dac54896723.png)
![image](https://user-images.githubusercontent.com/5672563/226451523-e11f694e-ef4a-4cf6-9929-0f25f56eb347.png)

#### Additional context

for this test case n  should be  2

**Comment by vivekiet22** [comment]
hi @jgera 
I think the test case is correct. The question asks if you can add ```additional``` n flowers in the flowerbed array you have to return true otherwise false. For n =1 that should be true as expected.

I checked your code and found that you return true when `nn==n`. Here you should check `if nn>=n then return true otherwise false`.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
