### ISSUE TITLE
Incorrect TestCase :- Sum of all the subsets xor totals

### ISSUE THREAD

**Issue by kaushikc44** [LeetCode-Feedback/LeetCode-Feedback#12481]
#### Your LeetCode username

kaushikc44

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Problem 1863 :- Sum of all the subsets xor totals
The bug is in the testcase 8 [1,1,1] is the list or array given and if its told that the solution can also be found using bit manipulation. The problem stats that we have to find all the subsets and also find the xor of each subset and then add that to the total sum. If we do the above thing the Answer should be 2 however it is saying the output should be 4. Below I will explain further. 

#### Code you used for Submit/Run operation

```
value = []
        for i in range(pow(2,len(nums))):
            j = i 
            counter = 0
            m = []
            while j != 0:
                if j & 1 == 1:
                    m.append(nums[counter])
                    j = j>>1
                    counter += 1
                else:
                    j = j>>1
                    counter += 1
            if m not in value:
                value.append(m)
        add = 0 
        for i in value:
            xor = 0
            for j in i:
                print(j)
                xor ^= j
            
            add += xor
        return add
```

#### Language used for code
Python

#### Expected behavior

If we find the subset we will get this [[], [1], [1, 1], [1, 1, 1]] 
If we find the xor of each it will be this. 1:- empty will be 0
2:- 1 with 0 will yield 1 
3. 1,1 with 0 will yield 0 
4. 1,1,1 with 0 will yield 1 
So total sum comes up to be 2 , however the expected output is 4 which is wrong. 

#### Screenshots

![image](https://user-images.githubusercontent.com/59849731/226404770-dc692722-08d5-43bb-ac5d-50d96b8d58b5.png)
![image](https://user-images.githubusercontent.com/59849731/226404805-0a31fcc6-718f-4145-857f-fcf2deec5dd9.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC ink.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by kaushikc44** [comment]
I am not sure , what you meant by AC link. But I will share this ,if this is what your looking for. 
https://leetcode.com/problems/sum-of-all-subset-xor-totals/submissions/918908585/
https://leetcode.com/problems/sum-of-all-subset-xor-totals/submissions/918900027/
