### ISSUE TITLE
Correct Answer, but it is not accepting - Python - 9. Palindrome Number

### ISSUE THREAD

**Issue by itz-shyam** [LeetCode-Feedback/LeetCode-Feedback#12494]
#### Category of the bug
- [ ] Question
- [.] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

So I was doing this exercise where I ran into a problem:
for the second testcase (-121), even though the code was completely correct, it is not accepting it (it is showing different result instead)
I even cross-checked with my own compiler.
#### Code you used for Submit/Run operation

```
class Solution(object):
    def isPalindrome(self, x):
        """
        :type x: int
        :rtype: bool
        """
        y=str(x)[::-1]
        if(x!=y):
            return 'false'
        elif(x==y):
            return 'true'
        

```

#### Language used for code
Python

#### Expected behavior

need to return 'false' instead of 'true'

#### Screenshots

NA

#### Additional context

NA

**Comment by stormsunshine** [comment]
In your code, `y` is a string, which is different from the type of `x`, so `x!=y` is always the case.

Also, this problem requires returning a bool value, not a string.

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
