### ISSUE TITLE
Seemingly broken Scala code for 284. Peeking Iterator

### ISSUE THREAD

**Issue by hderms** [LeetCode-Feedback/LeetCode-Feedback#1249]
#### Your LeetCode username
hderms

#### Category of the bug
- [ ] Question
- [ ] Solution
- [X] Language

#### Description of the bug
When attempting this problem using the Scala language, it seems like the construction of the test harness is broken:

For one, the test requires you to implement an `Iterator[Integer]` but the method stubs provided for `peek` and `next` return `Int` as opposed to `Integer`. Secondly, even if I correct those signatures to be `Integer`, and provide minimal example code required to typecheck: 

I can trigger this by providing an extremely minimal example solution, which typechecks, but which errors out in the Leetcode test harness:

returns this error in the test harness code:
![image](https://user-images.githubusercontent.com/833575/96488235-45c9ff80-1203-11eb-9e8e-65a6d5753bed.png)

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

```scala
class PeekingIterator(private val iterator: Iterator[Integer]) extends Iterator[Integer] {
    def peek(): Integer = {
        new Integer(42)
    }
    
    override def next(): Integer = {
        new Integer(42)
    }
    
    override def hasNext(): Boolean = {
        
        false
    }
}
```

#### Expected behavior
This minimal test case should be able to be ran by the Leetcode code runner without throwing an exception, however, it would presumably not pass any test cases. It is included to show that the issue appears to be in the Leetcode test runner

#### Screenshots
![image](https://user-images.githubusercontent.com/833575/96488235-45c9ff80-1203-11eb-9e8e-65a6d5753bed.png)

#### Additional context
We shouldn't mix interfaces between Int and Integer. Secondly, there appears to be some error that the user can't solve in this code runner.

**Comment by lc-kay** [comment]
Hi @hderms 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @hderms 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!

**Comment by hderms** [comment]
great, thanks @lc-kay. Will I be having the 100 leet code points awarded to my account?

**Comment by lc-kay** [comment]
@hderms Unfortunately, this feedback did not qualify for rewards. However, we still greatly appreciate your time and support! Thank you for using LeetCode.

**Comment by hderms** [comment]
@lc-kay that's extremely confusing to me. Can you explain why? If you offer points in exchange for filing an issue in the content repo, and then don't actually award them, or explain why, I find that a questionable business practice. There's no explanation for what would or wouldn't qualify for points on here: https://leetcode.com/discuss/general-discussion/526802/File-Problem-and-Solution-Content-Issues-to-Our-GitHub-Public-Feedback-Repo-Now!

**Comment by lc-kay** [comment]
@hderms It is not listed because we judge each case individually and detailedly. However, we have re-judged your issue and contribution and have rewarded you with 100 LeetCoins. Thank you for your time.

**Comment by hderms** [comment]
well thank you @lc-kay. I appreciate it.
