### ISSUE TITLE
Missing Test Case 1、两数之和

### ISSUE THREAD

**Issue by yuanbogit** [LeetCode-Feedback/LeetCode-Feedback#12490]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [ √] 缺少测试用例

**描述**
描述你遇到的 bug

leetcode 第一题（两数之和），java解法的示例代码不正确，在用例为：[2,7,8,8,15]16 情况下是不成立的

**你使用的语言**
java

**你提交或者运行的代码**
```
//运行的代码
class Solution {
    public int[] twoSum(int[] nums, int target) {
 HashMap<Integer,Integer> tempHashMap=new HashMap<>();
        for (int i = 0, j=nums.length-1 ;i<=j;i++,j--) {
            if(nums[i]+nums[j]==target){
                return new int[]{i,j};
            }
            int key=target-nums[i];
            if(tempHashMap.containsKey(key)){
                int index=tempHashMap.get(key);
                return new int[]{Math.min(i,index),Math.max(i,index)};
            }
              key=target-nums[j];
            if(tempHashMap.containsKey(key)){
                int index=tempHashMap.get(key);
                return new int[]{Math.min(j,index),Math.max(j,index)};
            }
            tempHashMap.put(nums[i],i);
            tempHashMap.put(nums[j],j);
        }
        return null;
    }
}
```

**期望行为**
描述你期望的结果

用例：[2,7,8,8,15]16
实际结果[2,2]
期望结果[2,3] 

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![1679393611168](https://user-images.githubusercontent.com/25102506/226586309-ac13507f-ef8a-48a3-969e-884e3683c825.jpg)

**额外的上下文**
添加额外的上下文信息
应更改代码为：

class Solution {
    public int[] twoSum(int[] nums, int target) {
 HashMap<Integer,Integer> tempHashMap=new HashMap<>();
        for (int i = 0, j=nums.length-1 ;i<=j;i++,j--) {
            int key=target-nums[i];
            if(tempHashMap.containsKey(key)){
                int index=tempHashMap.get(key);
                return new int[]{Math.min(i,index),Math.max(i,index)};
            }
              key=target-nums[j];
            if(tempHashMap.containsKey(key)){
                int index=tempHashMap.get(key);
                return new int[]{Math.min(j,index),Math.max(j,index)};
            }
          if(nums[i]+nums[j]==target){
                return new int[]{i,j};
            }
            tempHashMap.put(nums[i],i);
            tempHashMap.put(nums[j],j);
        }
        return null;
    }
}

**Comment by feiceh** [comment]
无需处理， 标答没有问题， 题目中有提及 “数组中同一个元素在答案里不能重复出现。”
