### ISSUE TITLE
Missing Test Case - 7. Reverse Integer

### ISSUE THREAD

**Issue by gsgoncalves** [LeetCode-Feedback/LeetCode-Feedback#12498]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

There is a missing test case. My initial version of the code below did not have the following line:
 "x *= sign # make it always positive"
The code without the line passes all tests but yields the wrong result for the int -321.

#### Code you used for Submit/Run operation
```
class Solution(object):
    def reverse(self, x):
        """
        :type x: int
        :rtype: int
        """
        sign = -1 if x < 0 else 1
        rev = 0
        
        x *= sign # make it always positive
        while x > 0:
            rev = rev * 10 + x % 10
            x //=10            
        
        if rev > 2**31 - 1 or rev < -2**31:
            return 0
        else:
            return rev * sign
```

#### Expected behavior
Both output and input are ints. 
Input: -321
Output: -123

**Comment by LC-Pam** [comment]
<img width="221" alt="Screen Shot 2023-03-22 at 4 37 37 PM" src="https://user-images.githubusercontent.com/103138242/227032235-9e70e33b-4dae-46c0-89b1-1473cd9ac530.png">
