### ISSUE TITLE
Problem on question 108. Convert Sorted Array to Binary Search Tree

### ISSUE THREAD

**Issue by chacalDefouraille** [LeetCode-Feedback/LeetCode-Feedback#125]
Hi everyone,

Below is the problem I encountered, it may be a LeetCode problem or a missunderstanding about what a height balanced tree is since it's the first time I hear about this.
I filled up the required fields, thanks in advance for your help :)

**What kind of the bug**
- [ ] Problem 108. Convert Sorted Array to Binary Search Tree

**Describe the bug**
When I run the code, it says the answer is wrong.
But my output is [9,0,5,-10,-3] so for me, it is a height balanced binary tree...

**what language is your code written in**
Java

**The code I run**
```
class Solution {
    public TreeNode sortedArrayToBST(int[] nums) {

        if (nums.length == 0)
            return null;
        
        int lvlMax = log2(nums.length);
        int nbEltLastLvl = nums.length - (int) Math.pow(2, lvlMax) + 1;
        TreeNode[] currLevel = new TreeNode[(int) Math.pow(2, lvlMax)];
        
        int i = 0;
        int currLevelFilling;
        for(int lvl = lvlMax; lvl >= 0; lvl--)
        {
            if (lvl == lvlMax)
                currLevelFilling = nbEltLastLvl;
            else
                currLevelFilling = (int) Math.pow(2, lvl);
                
            for(int lvlIdx = 0; lvlIdx < currLevelFilling; lvlIdx++)
            {
                TreeNode newNode = new TreeNode(nums[i++]);
                newNode.left = (currLevel[2*lvlIdx] != null) ? currLevel[2*lvlIdx] : null;
                newNode.right = (currLevel[2*lvlIdx + 1] != null) ? currLevel[2*lvlIdx + 1] : null;
                currLevel[lvlIdx] = newNode;
            }
        }
        return currLevel[0];
    }
    
    public static int log2(int x)
    {
        return (int) (Math.log(x) / Math.log(2) + 1e-10);
    }
}

**Comment by CooperCooperCooper** [comment]
Hi @chacalDefouraille,
Thank you for reaching out to us! I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @chacalDefouraille,
Thank you for your time. Our team took a look at your code and found it still needs to work on the binary search property. I found [this post with a thorough explanation for Java code](https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/discuss/128430/Java-Solution-beats-100-Short-and-Explained) that might help with fixing the issue. Please check it out.

**Comment by chacalDefouraille** [comment]
Thank you @CooperCooperCooper  
I didn't know about the binary search property but I found the explanation on internet.
So my tree was only height balanced but not BST. Now I know why the answer was wrong.
Thanks for your help.
