### ISSUE TITLE
1236. Web Crawler doesn't compile for Kotlin

### ISSUE THREAD

**Issue by anatolyD** [LeetCode-Feedback/LeetCode-Feedback#12505]
#### Your LeetCode username
mrtriumpf

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Does not compile and run

```
Compile Error:

Line 19: Char 26: error: none of the following functions can be called with the arguments supplied: 
@SinceKotlin public fun Random(seed: Int): Random defined in kotlin.random
@SinceKotlin public fun Random(seed: Long): Random defined in kotlin.random
    private val random = Random()
                         ^
```

#### Code you used for Submit/Run operation
Code is irrelevant, happens on any code

```kotlin
class Solution {
    fun crawl(startUrl:String, htmlParser:HtmlParser):List<String> {
        return listOf()
    }
}
```

#### Language used for code
Kotlin

#### Expected behavior
Should just run and show my answer is incorrect

#### Screenshots
<img width="828" alt="image" src="https://user-images.githubusercontent.com/3054650/226814660-d7c8e1e2-d1e5-4321-a705-f0e15deeb594.png">

#### Additional context
One can actually hack it if you create a function `Random()` on top of your solution :)
```
fun Random() = Random(0L)



class Solution {
    fun crawl(startUrl:String, htmlParser:HtmlParser):List<String> {
        return listOf()
    }
}
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

The issue should already fixed. 

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
