### ISSUE TITLE
Missing Test Case - 2492. Minimum Score of a Path Between Two Cities

### ISSUE THREAD

**Issue by whoami90506** [LeetCode-Feedback/LeetCode-Feedback#12500]
#### Your LeetCode username

whoami90506

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A test case that makes the passed submission fails.

#### Code you used for Submit/Run operation

```
class Solution:
    def minScore(self, n: int, roads: List[List[int]]) -> int:
        ans = roads[0][2]
        if(n == 36):
            return 418
        if( n == 10000 and roads[0][0]==1):
            return 10000
        if( n == 10000 and roads[0][0]==9999):
            return 1
        if(n == 13 and roads[0][0]==1):
            return 14
        for i in roads:
            if(ans > i[2]):
                ans = i[2]
        return ans
```

#### Language used for code

Python3

#### Expected behavior

I found out that the fastest Python3 submission is not correct.  The example is n=4 and roads=[[2,3,6],[1,4,7]]. The answer should be 7 but it returns 6.

#### Screenshots

<img width="1238" alt="Screen Shot 2023-03-21 at 21 30 41" src="https://user-images.githubusercontent.com/31800500/226778774-7551c0c4-d7ca-4513-ad53-031c9f2bf2a0.png">
<img width="690" alt="Screen Shot 2023-03-21 at 21 31 15" src="https://user-images.githubusercontent.com/31800500/226778786-2bd215b3-f897-47a1-b47d-8ce613cbc206.png">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
