### ISSUE TITLE
Wrong Expected Result in one Testcase - 1619

### ISSUE THREAD

**Issue by julia-dizhak** [LeetCode-Feedback/LeetCode-Feedback#1250]
https://leetcode.com/julia-dizhak/

#### Category of the bug
- [ ] Question

#### Description of the bug
The testcase produces the wrong expected result. For example, when 
input is `[1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,3]` or `[6,2,7,5,1,2,0,3,10,2,5,0,5,5,0,8,7,6,8,0]` below solution would return integers `2` and `4`,
but in leetcode console it would display `2.00000` and `4.00000` correspondly.

#### Code you used for Submit/Run operation
```
var trimMean = function(arr) { 
  arr =  arr.sort((a,b) => a-b);
  const n = arr.length;
  const minIndex = n * 0.05,
    maxIndex = n * 0.95;

  const resultArr = arr.slice(minIndex, maxIndex);
  const sum = resultArr.reduce((acc, val) => acc + val, 0);

  return sum / resultArr.length;
}
```

#### Language used for code
Javascript

#### Expected behavior
The provided solution shouldn't pass test cases but now it passes. In JS it is possible to use method `toFixed(5)`, but this will return a string representation.

#### Screenshots
[screen attached](https://ibb.co/ypgBT37)

**Comment by lc-kay** [comment]
Hi @julia-dizhak 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@julia-dizhak After our team looked into your issue, we concluded that this is the expected behavior for js. Thank you for your time and support.
