### ISSUE TITLE
142. Linked List Cycle II

### ISSUE THREAD

**Issue by SiegeSailor** [LeetCode-Feedback/LeetCode-Feedback#12504]
#### Your LeetCode username

SiegeSailor

#### Category of the bug

- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

The variable `intersection` can not be assigned value properly.

#### Code you used for Submit/Run operation

```python
class Solution:
    def detectCycle(self, head: Optional[ListNode]) -> Optional[ListNode]:
        if head == None:
            return None
        
        slow, fast = head, head
        intersection = None
        while fast is not None and fast.next is not None:
            slow = slow.next
            fast = fast.next.next

            if slow is fast:
                intersection = slow
                break

        # return intersection

        if intersection is None:
            return None
```

#### Language used for code
Python3

#### Expected behavior

The code should return `None` only if `intersection` is `None`. However, `intersection` is always `None` when I use `if intersection is None`.

#### Screenshots

<img width="1496" alt="Screenshot 2023-03-22 at 01 45 49" src="https://user-images.githubusercontent.com/39463416/226813508-bf812ede-4a38-4505-9a07-8d310a44524b.png">
<img width="1496" alt="Screenshot 2023-03-22 at 01 49 10" src="https://user-images.githubusercontent.com/39463416/226813748-8c9c875a-ec00-4431-83a2-5a8cbf38c0c7.png">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
