### ISSUE TITLE
2492. Minimum Score of a Path Between Two Cities Missing test case

### ISSUE THREAD

**Issue by yuhan-wang** [LeetCode-Feedback/LeetCode-Feedback#12502]
#### Your LeetCode username

yuhan-wang

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Inefficient O(n^2) solutions pass all tests

#### Code you used for Submit/Run operation

```
class Solution:
    def minScore(self, n: int, roads: List[List[int]]) -> int:
        q = deque(roads)
        pool = {1,n}
        re = 10**4+1
        while q:
            lth = len(q)
            for _ in range(len(q)):
                temp = q.popleft()
                if temp[0] in pool or temp[1] in pool:
                    re = min(re,temp[2])
                    pool.add(temp[0])
                    pool.add(temp[1])
                else:
                    q.append(temp)
            if lth == len(q):
                break
        return re
```

#### Language used for code

Python3

#### Expected behavior

The test case generated by the following Python3 code gets TLE for the solution because the solution has O(n^2) time complexity.
```
s = []
for i in range(10**5-1, 0, -1):
    s.append([i,i+1,10])
s[0][0] = 1
print(f"n = 10000, roads={s}")
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Invalid Testcase

expected 'Bi' to have value from 1 to 10000 only

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by yuhan-wang** [comment]
Please try
```
s = []
for i in range(10**5-1, 0, -1):
    s.append([i,i+1,10])
s[0][0] = 1
print(f"n = {10**5}, roads={s}")
```
