### ISSUE TITLE
188. Best Time to Buy and Sell Stock IV - Confusing description

### ISSUE THREAD

**Issue by mnaoumov** [LeetCode-Feedback/LeetCode-Feedback#12501]
#### Your LeetCode username

mnaoumov

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The task description says
> You may complete at most `k` transactions.

However based on the Example 2, it becomes clear that by `transactions` it considered only sales of the stock, but not purchases of the stock.

#### Expected behavior

I think, word `transactions` in the description should be changed to `sales` or added extra sentence clarifying what `transaction` actually means.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
