### ISSUE TITLE
2530. Maximal Score After Applying K Operations

### ISSUE THREAD

**Issue by Jeetaksh** [LeetCode-Feedback/LeetCode-Feedback#12519]
**My Leetcode username: Jeetaksh**

I found a typing issue in Example 2 of the problem description of [2530. Maximal Score After Applying K Operations](https://leetcode.com/problems/maximal-score-after-applying-k-operations/)
In the Example 2, the 1 I marked with the red arrow should be replaced with 2 in the correct description. Thankyou!
![2530](https://user-images.githubusercontent.com/92541718/227035363-6721d8fa-2695-4d23-9c00-65b109cec12b.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
