### ISSUE TITLE
131.分割回文串palindrome-partitioning

### ISSUE THREAD

**Issue by madmannnn** [LeetCode-Feedback/LeetCode-Feedback#12512]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [ ] 题目
- [ √] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
子串顺序不同，报错。
[["b","a","a"],["b","aa"]]
和
[["a","a","b"],["aa","b"]]
都应是正确答案，但前者报错

**你使用的语言**
Java
**你提交或者运行的代码**
```
// palindrome-partitioning
class Solution {
    List<List<String>> res = new ArrayList<>();
    public List<List<String>> partition(String s) {

        char[] charArr = s.toCharArray();
        Deque<String> path = new ArrayDeque<>();
        dfs(charArr,path,0);
        return res;
    }
    
    void dfs(char[] charArr, Deque<String> path,int index){
        if(index==charArr.length){
            res.add(new ArrayList(path));
            return;
        }
        for(int i = index;i<charArr.length;i++){
            if(!checkPalindrome(charArr,index,i)){
                continue;
            }
            path.push(new String(charArr,index,i-index+1));
            dfs(charArr,path,i+1);
            path.poll();
        }
    }

    boolean checkPalindrome(char[] charArr, int left,int right){
        while(left<right){
            if(charArr[left]!=charArr[right]){
                return false;
            }
            left++;
            right--;
        }
        return true;
    }
}
```

**期望行为**
描述你期望的结果

**屏幕截图**
![image](https://user-images.githubusercontent.com/52954698/226855155-a6f4c5dc-437b-42fe-8706-7851e5055087.png)

![image](https://user-images.githubusercontent.com/52954698/226856363-894edb1d-ccbc-4bde-9575-d16f322a8255.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
你好，如果出现测试用例结果和提交结果不一致的情况，可以再仔细检查并调试一下代码，或点击这里：「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」 获得更多帮助。

同时也可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
