### ISSUE TITLE
Missing test case - 1036 Escape a Large Maze. Wrong solution accepted

### ISSUE THREAD

**Issue by jamaassen** [LeetCode-Feedback/LeetCode-Feedback#1251]
#### Your LeetCode username

Locutus42

#### Category of the bug
* [x]  Question
* [ ] Solution
* [ ] Language

#### Description of the bug

The solution that beats 100% of the Python3 submissions is not the correct solution as it fails the following test case.

#### Code you used for Submit/Run operation

```
class Solution:
    def isEscapePossible(self, blocked: List[List[int]], source: List[int], target: List[int]) -> bool:
        Brows, Bcols, seen = defaultdict(list), defaultdict(list), set()
        source, target = tuple(source), tuple(target)
        for row, col in sorted(blocked):
            Brows[col].append(row); Bcols[row].append(col)
        stack = [source]
        while stack:
            (row, col) = stack.pop()
            if (row, col) == target: return True
            i = bisect_right (Bcols[row], col)
            next_R = (row, Bcols[row][i] - 1) if i < len(Bcols[row]) else (row, target[1])
            next_L = (row, Bcols[row][i-1] + 1) if i > 0 else (row, 0)
            i = bisect_right (Brows[col], row)
            next_D = (Brows[col][i] - 1, col) if i < len(Brows[col]) else (target[0], col)
            next_U = (Brows[col][i-1] + 1, col) if i > 0 else (0, col)
            if next_R not in seen: stack.append(list(next_R))
            if next_L not in seen: stack.append(list(next_L))
            if next_D not in seen: stack.append(list(next_D))
            if next_U not in seen: stack.append(list(next_U))
            seen |= {next_R, next_L, next_D, next_U}
        return False
```

#### Language used for code

Python3

#### Expected behavior

The code should have returned the result as 'True' but it is returning 'False'.
The solution should not have been accepted since it fails the mentioned test case.
###### Testcase
```
[[0,4],[2,4],[3,1],[3,3],[4,0],[4,2]]
[2,2]
[7,3]
```
Visualization of test case:
![image](https://user-images.githubusercontent.com/49311531/96506676-09f46180-1226-11eb-9049-7966f2423a7f.png)
#### Screenshots

![image](https://user-images.githubusercontent.com/49311531/96507296-f5fd2f80-1226-11eb-8c42-cdf661fc6253.png)

#### Additional context

link to submission: https://leetcode.com/submissions/detail/410766435/
link to problem: https://leetcode.com/problems/escape-a-large-maze/

**Comment by lc-kay** [comment]
Hi @jamaassen 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @jamaassen 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
