### ISSUE TITLE
Missing Test Case - 2492. Minimum Score of a Path Between Two Cities

### ISSUE THREAD

**Issue by Gertoperto** [LeetCode-Feedback/LeetCode-Feedback#12516]
#### LeetCode Username

csgert

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

If the user uses uint16_t (short) to store the vertex numbers, all current test cases pass,
but the biggest possible vertex number does not fit in a short. Adding test case n=100000, roads=[[1,100000,10], [34464,2,5]] causes the uint16_t submission to fail.

#### Code you used for Submit/Run operation

```c++
// 2492. Minimum Score of a Path Between Two Cities
using us = unsigned short;

vector<us> parent, min_edge;

static bool once = [](){
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    parent.reserve(1e5);
    min_edge.reserve(1e5);
    return true;
} ();

class UnionFind {
public:
    UnionFind(us size) {
        parent.clear();
        min_edge.clear();
        parent.resize(size);
        min_edge.resize(size, USHRT_MAX);
        for (us i = 0; i < size; i++) parent[i] = i;
    }

    int find(us x) {
        if (parent[x] != x) parent[x] = find(parent[x]);
        return parent[x];
    }

    void union_set(us x, us y, us weight) {
        us xset = find(x), yset = find(y);
        if (xset < yset) swap(xset, yset); // make xset root, make sure xset is biggest index
        min_edge[xset] = min(min_edge[xset], min(min_edge[yset], weight));
        parent[yset] = xset;
    }

    int find_min(us x) {
        return min_edge[find(x)];
    }
};

class Solution {
public:
    int minScore(const int n, const vector<vector<int>>& roads) const {
        UnionFind dsu(n+1);
        for (const vector<int>& road : roads) dsu.union_set(road[0], road[1], road[2]);
        return dsu.find_min(1);
    }
};
```

#### Language used for code

C++

#### Expected behavior

Expected: submission with unsigned short to fail
Reality: submission passes

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
