### ISSUE TITLE
Missing Test Case - 595. Big Countries

### ISSUE THREAD

**Issue by Sudhanshu-stathom** [LeetCode-Feedback/LeetCode-Feedback#12510]
#### Your LeetCode username
saltdrip001

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
This is just to add the edge cases where it is equal to boundry value

#### Code you used for Submit/Run operation
```
SELECT name, population, area
FROM World
WHERE area>=3000000 or population>=25000000 
```
##### Test case

| name        | continent | area    | population | gdp          |
| ----------- | --------- | ------- | ---------- | ------------ |
| Afghanistan | Asia      | 652230  | 2500000   | 20343000000  |
| Albania     | Europe    |3000000   | 2831741    | 12960000000  |
| Algeria     | Africa    | 2381741 | 37100000   | 188681000000 |
| Andorra     | Europe    | 468     | -1      | 3712000000   |
| Angola      | Africa    | 1246700 | 25000000   | 100990000000 |

```


#### Language used for code
MySQL


#### Expected behavior
Will work with edge cases



#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by Sudhanshu-stathom** [comment]
Edge cases and negative numbers

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Please come up with the exact test case in JSON format.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
