### ISSUE TITLE
Singly Linked List - [Learn Content] Inconsistent Time complexity

### ISSUE THREAD

**Issue by IvoBiaus** [LeetCode-Feedback/LeetCode-Feedback#12518]
#### Your LeetCode username
IvoBiaus

#### Category of the bug
- [X] "Learn" content

#### Description of the bug
As mentioned in this [_**Closed Issue**_](https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/5217) 2 years ago (that apparently was not resolved).

In the Learn section, at the cards ["Add Operation"](https://leetcode.com/explore/learn/card/linked-list/209/singly-linked-list/1288/) and ["Delete Operation"](https://leetcode.com/explore/learn/card/linked-list/209/singly-linked-list/1289/) , mentions:

- `Time Complexity` for Add Operation is `O(1)`. 
- `Time Complexity` for Delete Operation is `O(n)`.

 The Delete Operation has a higher TC under the idea of: 

> _"we have to traverse the linked list from the head node to find out prev which will take O(N)"_

Something that also has to be consider for **Adding**, but for some reason it was not mentioned or taking into account for the given TC.

As mentioned in the other Issue:
- They should both be `O(1)` **if you don't** take finding the previous node into account; 
- or both should be `O(n)` **if you do** take finding previous node into account. 

Since the Learn card is approaching this as **"the benefit of the linked list vs an array"**, then i assume they should both be `O(1)`.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

The time complexities are assuming that for adding, you have a reference to the "prev" node, and for deletion, you have a reference to the "cur" node. As a result of a singly linked list only having access to "next", iteration is not required for adding. This seems inconsistent, but it makes sense that you would have pointers to "where do I want to add a node?" and "what node do I want to delete"?. The text in the "add" article has been modified to note that a reference is required to "cur".

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
