### ISSUE TITLE
Missing Constraints - 128. Longest Consecutive Sequence

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1252]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

128. Longest Consecutive Sequence
https://leetcode.com/problems/longest-consecutive-sequence/

Condition is given as:
- Your algorithm should run in O(n) complexity.

But there are no constraints given.
- What is the range of length of the array?
- What is the range of values in the array?

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JavaScript

#### Expected behavior

- Without any constraints how can a user easily do an algorithm in O(n) run time complexity?
- The question must have constraints
- I would have done this, but unfortunately, now I cannot proceed with this due to a possible TimeLimitExceeded error

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
