### ISSUE TITLE
Problem 26: Remove duplicate numbers from array (apparently 2 != 2)

### ISSUE THREAD

**Issue by coolCucumber-cat** [LeetCode-Feedback/LeetCode-Feedback#12526]
#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
1. This question is extremely horribly explained. Apparently you need to get an array of non duplicate numbers, then it expects an int? It's very unclear what the goal is, escpecially since the title of the question is wrong.

2. If the return value of the function is the same, but you remove some code that has nothing to do with getting the return value, it should still work right? Wrong. Your question asks for an integer, I'm going to give you an integer. Anything else that happens should be irrevelant right? Well no, because when you remove the for loop it no longer works, despite the fact that the for loop modifies the input after the variable holding the return value is stored. So unless you actually are looking into what the array is, despite the question not asking for that, I don't know what you're doing.

#### Code you used for Submit/Run operation
```javascript
removeDuplicates=nums=>{
    let nums2 = Array.from(new Set(nums))
    console.log(nums2)
    const len = nums.length;
    for(i = 0; i < len - 1; i++) {
      if(i > nums.length - 1) {
        break;
      }
      if (nums[i] === nums[i + 1]) {
        nums.splice(i, 1);
        i--;
      }
    }
    console.log(nums)
    console.log(nums2.length)
    console.log(nums.length)
    return nums2.length
}
```

#### Language used for code
JavaScript

#### Expected behavior
I would expect that 2 equals 2.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
