### ISSUE TITLE
278. First Bad Version - Condescending Editorial Summary Wording

### ISSUE THREAD

**Issue by mdnightmarauder** [LeetCode-Feedback/LeetCode-Feedback#12529]
#### Your LeetCode username
joyfulpursuit 

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
```This is a very simple problem. There is a subtle trap that you may fall into if you are not careful.```

this subjective wording in the solution of the editorial is patronizing and condescending; i do not see why stating to the reader how simple a problem is is of any benefit. i could see a new leetcoder feel very down about their ability. please consider revising to just say something along the lines of  "this problem can be solved using an efficient sorting algorithm".

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

While it is correct that condescending words like "obvious" etc. should be avoided in editorials, this doesn't apply here. The statement "this is a very simple problem" is not referring to the optimal solution. It is referring to the task itself which could be solved by a linear scan. The problem itself is very simple.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
