### ISSUE TITLE
Interview Crash Course - Stacks and queues - String problems

### ISSUE THREAD

**Issue by StDannyDan** [LeetCode-Feedback/LeetCode-Feedback#12521]
#### Your LeetCode username
StDannyDan

#### Category of the bug
- Question

#### Description of the bug
[Here](https://leetcode.com/explore/interview/card/leetcodes-interview-crash-course-data-structures-and-algorithms/706/stacks-and-queues/4646/) in solution to [1047. Remove All Adjacent Duplicates In String](https://leetcode.com/problems/remove-all-adjacent-duplicates-in-string/) author used:

```
StringBuilder sb = new StringBuilder();
while (!stack.empty()) {
      sb.append(stack.pop());
}
return sb.reverse().toString();
```
We could use iterator instead, that way we don't need to reverse sb:
```
for (char ch : stack) sb.append(ch);
return sb.toString();
```
It could also be a good moment to note that Stack's iterator is [buggy](https://stackoverflow.com/questions/16992758/is-there-a-bug-in-java-util-stacks-iterator) and iterates over Stack in insertion order instead of LIFO order.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team will make a small change. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
