### ISSUE TITLE
It might be better if you could change how you list down a sequence in Questions.

### ISSUE THREAD

**Issue by n4vn337** [LeetCode-Feedback/LeetCode-Feedback#12533]
#### Your LeetCode username

akanavz

#### Category of the bug
- [ ] Question

#### Description of the bug

As I was going through the sentence "Suppose you have n versions [1, 2, ..., n]", I inferred that you intended the sequence to follow the pattern of 1, 2, 3, ..., n. However, given that only two numbers of the sequence were mentioned, it could be difficult for a newcomer to comprehend the intended meaning. Therefore, I suggest that you include at least three elements of the sequence before continuing with the dots until n, and format it in a similar manner to "1, 2, 3, ..., n".

#### Expected behavior

I suggest that you include at least three elements of the sequence before continuing with the dots until n, and format it in a similar manner to "1, 2, 3, ..., n".

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem page link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
