### ISSUE TITLE
1032. 字符流 Python3 提交代码未得到预期结果。

### ISSUE THREAD

**Issue by 648932602** [LeetCode-Feedback/LeetCode-Feedback#12539]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [ ] 题目 [1032. 字符流](https://leetcode.cn/problems/stream-of-characters/)
- [ ] 题解
- [ ] 编程语言 Python3
- [ ] 运行结果和本地运行结果不一致

**描述**
我本地运行的结果是正确的，但提交的时候运行不正确。

测试用例为：
["StreamChecker","query","query","query","query","query","query","query","query","query","query","query","query","query","query","query","query","query","query","query","query","query","query","query","query","query","query","query","query","query","query","query","query","query","query","query","query","query","query","query","query"]
[[["abaa","abaab","aabbb","bab","ab"]],["a"],["a"],["b"],["b"],["b"],["a"],["a"],["b"],["b"],["a"],["a"],["a"],["a"],["b"],["a"],["b"],["b"],["b"],["a"],["b"],["b"],["b"],["a"],["a"],["a"],["a"],["a"],["b"],["a"],["b"],["b"],["b"],["a"],["a"],["b"],["b"],["b"],["a"],["b"],["a"]]

服务器显示预期结果为：
[null,false,false,true,false,true,false,false,true,false,false,false,false,false,true,false,true,false,false,false,true,false,false,false,false,false,false,false,true,false,true,false,false,false,false,true,false,true,false,true,false]

服务器显示输出为：
[null,false,false,true,false,true,true,true,true,false,true,true,false,false,true,true,true,false,false,true,true,false,false,true,true,false,false,false,true,true,true,false,false,true,true,true,false,true,true,true,true]

我本地输出为：
[None, False, False, True, False, True, False, False, True, False, False, False, False, False, True, False, True, False, False, False, True, False, False, False, False, False, False, False, True, False, True, False, False, False, False, True, False, True, False, True, False]

**你使用的语言**
Python3

**你提交或者运行的代码**
```
class StreamChecker:
    word_map = {}
    len_map = {}
    letters = ""
    n = 0

    def __init__(self, words: List[str]):
        for word in words:
            self.len_map[len(word)] = 1
            self.word_map[word] = 1

    def query(self, letter: str) -> bool:
        self.letters += letter
        self.n += 1

        for len in self.len_map.keys():
            if self.letters[self.n - len:] in self.word_map:
                return True

        return False
```

**期望行为**
期望继续运行后面的测试用例

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
以下是我本地代码
```
# coding = utf-8

"""1032. 字符流"""
from typing import List

class Solution:
    def checker(self, operate: List[int], params: List[int]) -> int:
        checker = None
        n = len(operate)
        res = []
        for i in range(n):
            oper = operate[i]
            param = params[i]

            if oper == "StreamChecker":
                checker = StreamChecker(param[0])
                res.append(None)
            elif oper == "query":
                sub_res = checker.query(param[0])
                res.append(sub_res)

        return res

# Your StreamChecker object will be instantiated and called as such:
# obj = StreamChecker(words)
# param_1 = obj.query(letter)

class StreamChecker:
    word_map = {}
    len_map = {}
    letters = ""
    n = 0

    def __init__(self, words: List[str]):
        for word in words:
            self.len_map[len(word)] = 1
            self.word_map[word] = 1

    def query(self, letter: str) -> bool:
        self.letters += letter
        self.n += 1

        for len in self.len_map.keys():
            if self.letters[self.n - len:] in self.word_map:
                return True

        return False


if __name__ == '__main__':
    solution = Solution()

    print(solution.checker(operate=["StreamChecker", "query", "query", "query", "query", "query", "query", "query", "query", "query", "query", "query", "query", "query", "query", "query", "query", "query", "query", "query", "query", "query", "query", "query", "query", "query", "query", "query", "query", "query", "query", "query", "query", "query", "query", "query", "query", "query", "query", "query", "query"], params=[[["abaa", "abaab", "aabbb", "bab", "ab"]], ["a"], ["a"], ["b"], ["b"], ["b"], ["a"], ["a"], ["b"], ["b"], ["a"], ["a"], ["a"], ["a"], ["b"], ["a"], ["b"], ["b"], ["b"], ["a"], ["b"], ["b"], ["b"], ["a"], ["a"], ["a"], ["a"], ["a"], ["b"], ["a"], ["b"], ["b"], ["b"], ["a"], ["a"], ["b"], ["b"], ["b"], ["a"], ["b"], ["a"]]))
```

**Comment by feiceh** [comment]
无需处理，建议在 __init__ 内部进行初始化（否则在不同用例处理时会有干扰）
       self.word_map = {}
        self.len_map = {}
        self.letters = ""
        self.n = 0
