### ISSUE TITLE
Missing Test Case - 677. Map Sum Pairs

### ISSUE THREAD

**Issue by mbcolson** [LeetCode-Feedback/LeetCode-Feedback#1253]
#### Your LeetCode username

mcolson

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution is accepted but fails on the following test case:
["MapSum", "insert", "sum"]
[[], ["apple",3], [""]]

#### Code you used for Submit/Run operation

```
class TrieNode {
 public:
    map<char, TrieNode*> children;
    int score;
};

class MapSum {
private:
    unordered_map<string,int> mp;
    TrieNode* root;
    
public:
    /** Initialize your data structure here. */
    MapSum() {
        root = new TrieNode();
    }
    
    void insert(string key, int val) {
        int delta;
        
        if(mp.count(key))
            delta = val - mp[key];
        else
            delta = val;
        
        mp[key] = val;
        
        TrieNode* cur = root;
        //cur->score += delta;
        
        for(char c : key) {
            if(cur->children[c] == nullptr)
                cur->children[c] = new TrieNode();
            
            cur = cur->children[c];
            cur->score += delta;
        }
    }
    
    int sum(string prefix) {
        TrieNode* cur = root;
        
        for(char c : prefix) {
            cur = cur->children[c];
            
            if(cur == nullptr)
                return 0;
        }
        
        return cur->score;
    }
};

/**
 * Your MapSum object will be instantiated and called as such:
 * MapSum* obj = new MapSum();
 * obj->insert(key,val);
 * int param_2 = obj->sum(prefix);
 */
```

#### Language used for code

C++

#### Expected behavior

Expected the code submission to fail for wrong answer.

#### Screenshots

![image](https://user-images.githubusercontent.com/14815009/96555895-2d8eca80-126d-11eb-8685-99c0c024c90b.png)
![image](https://user-images.githubusercontent.com/14815009/96555937-3a132300-126d-11eb-8091-7f19fd105943.png)

**Comment by lc-kay** [comment]
Hi @mbcolson 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @mbcolson 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
