### ISSUE TITLE
Missing Test Case - 16. 3Sum Closest

### ISSUE THREAD

**Issue by userzbh666** [LeetCode-Feedback/LeetCode-Feedback#12548]
#### Your LeetCode username

Lucky boy

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ * ] Missing Test Cases 

#### Description of the bug

有一个人的错误的优化代码可以通过提交, 但不能通过特殊的case
nums = [2, 5, 6, 7], target = 16

#### Code you used for Submit/Run operation

```
class Solution:
    def threeSumClosest(self, nums: List[int], target: int) -> int:
        n = len(nums)
        ans = sum(nums[:3])

        nums.sort()
        if sum(nums[:3]) >= target:
            return sum(nums[:3])
        if sum(nums[-3:]) <= target:
            return sum(nums[-3:])

        for i in range(n - 2):
            x = nums[i]
            if i > 0 and nums[i - 1] == x:
                continue
            
            if nums[i] + nums[-1] + nums[-2] < target:  # [2, 5, 6, 7], 16, 这是个错误的优化代码
                continue
            
            j = i + 1
            k = n - 1
            while j < k:
                s = x + nums[j] + nums[k]
                if abs(target - s) < abs(target - ans):
                    ans = s
                if s < target:
                    j += 1
                    while j < k and nums[j] == nums[j - 1]:
                        j += 1
                elif s > target:
                    k -= 1
                    while j < k and nums[k] == nums[k + 1]:
                        k -= 1
                else:
                    return target
        return ans
```

#### Language used for code

python3

#### Expected behavior

返回正确答案

#### Screenshots

![屏幕截图(20)](https://user-images.githubusercontent.com/103829994/227519727-64661961-609d-4b3e-aa2f-74c1f473836a.png)
![屏幕截图(21)](https://user-images.githubusercontent.com/103829994/227519734-89b83004-33bb-439f-893c-cc3212a88d95.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
