### ISSUE TITLE
面试题 16.10. 生存人数

### ISSUE THREAD

**Issue by Ijustwantyouhappy** [LeetCode-Feedback/LeetCode-Feedback#1254]
** Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
题意叙述有误。题干里写道：“如果一个人在某一年的任意时期都处于生存状态，那么他们应该被纳入那一年的统计中。”，根据接下来的例子来看，这里想表达的意思应该是any，而“都”是all的意思，所以应该去掉“都”字，在逻辑上这俩意思非常相悖。（后面还多打了一个“们”字，不过这个typo无关紧要）。建议改为：“如果一个人在某一年的任意时期处于生存状态，那么他应该被纳入那一年的统计中。”

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认的～

**Comment by feiceh** [comment]
题面已修改，ID：a_run 给予积分奖励，请查收。
