### ISSUE TITLE
464题缺少测试用例1 2应该返回false，但是我的代码通过了

### ISSUE THREAD

**Issue by stevenzrx** [LeetCode-Feedback/LeetCode-Feedback#12547]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
智人心

**Bug 类型**
- [464 ] 题目
- [ ] 题解
- [ ] 编程语言
- [ √] 缺少测试用例

**描述**
描述你遇到的 bug

**你使用的语言**
C++

**你提交或者运行的代码**
```
class Solution {
private:
    int visited[1 << 21];
public:
    bool canIWin(int maxChoosableInteger, int desiredTotal) {
        int state = 0;
        if ((1 + maxChoosableInteger) * maxChoosableInteger < desiredTotal)return 0;
        if (maxChoosableInteger >= desiredTotal)return 1;
        return dfs(0, 0, maxChoosableInteger, desiredTotal);
    }
    bool dfs(int state, int curTotal, int maxChoosableInteger, int desiredTotal) {
        if (visited[state] == 1)return true;
        if (visited[state] == 2)return false;
        for (int i = 1; i <= maxChoosableInteger; i++) {
            if ((1 << i) & state)continue;
            if (curTotal + i >= desiredTotal) {
                visited[state] = 1;
                return true;
            }
            if (!dfs(state | (1 << i), curTotal + i, maxChoosableInteger, desiredTotal)) {
                visited[state] = 1;
                return true;
            }
        }
        visited[state] = 2;
        return false;
    }
};
```

**期望行为**
描述你期望的结果
1 2
应该返回false
**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
无需处理， 1 2 时， 并不能达到或超过累计和 ，所以没人能赢

**Comment by stevenzrx** [comment]
没人能赢就应该返回false对吧，我的代码返回的true，但是没有被拦下来




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LeetCode-Feedback/LeetCode-Feedback"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月29日(星期三) 中午12:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LeetCode-Feedback/LeetCode-Feedback] 464题缺少测试用例1 2应该返回false，但是我的代码通过了 (Issue #12547)





 
无需处理， 1 2 时， 并不能达到或超过累计和 ，所以没人能赢
