### ISSUE TITLE
Solution - 126. Word Ladder II

### ISSUE THREAD

**Issue by nskybytskyi** [LeetCode-Feedback/LeetCode-Feedback#12556]
#### Your LeetCode username

[nskybytskyi](https://leetcode.com/nskybytskyi/)

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

This is not a bug report but an enhancement proposal instead. The [editorial](https://leetcode.com/problems/word-ladder/editorial/) for problem [126. Word Ladder II](https://leetcode.com/problems/word-ladder/) does not contain an implementation in C++. I propose a possible solution based on the official implementation in Python.

#### Code you used for Submit/Run operation

**Approach 1: Breadth-First Search**

[Submission link](https://leetcode.com/problems/word-ladder/submissions/921525847/):

```cpp
class Solution {
 public:
  int ladderLength(string beginWord, string endWord, vector<string>& wordList) {
    if (find(wordList.cbegin(), wordList.cend(), endWord) == wordList.cend()) {
      return 0;
    }

    const int L = beginWord.length();

    map<string, vector<string>> all_combo_dict;
    for (const auto& word : wordList) {
      for (int i = 0; i < L; ++i) {
        const auto intermediate_word =
            word.substr(0, i) + "*" + word.substr(i + 1);
        all_combo_dict[intermediate_word].push_back(word);
      }
    }

    deque<pair<string, int>> queue{{beginWord, 1}};
    set<string> visisted{beginWord};

    while (!queue.empty()) {
      const auto [current_word, level] = queue.front();
      queue.pop_front();

      for (int i = 0; i < L; ++i) {
        const auto intermediate_word =
            current_word.substr(0, i) + "*" + current_word.substr(i + 1);
        for (const auto& word : all_combo_dict[intermediate_word]) {
          if (word == endWord) {
            return level + 1;
          }

          if (!visisted.count(word)) {
            visisted.insert(word);
            queue.emplace_back(word, level + 1);
          }
        }

        all_combo_dict[intermediate_word].clear();
      }
    }

    return 0;
  }
};
```

**Approach 2: Bidirectional Breadth-First Search**

[Submission link](https://leetcode.com/problems/word-ladder/submissions/921525987/):

```cpp
class Solution {
 private:
  int L{0};
  map<string, vector<string>> all_combo_dict;

  optional<int> visitWordNode(deque<string>& queue, map<string, int>& visited,
                              map<string, int>& others_visited) {
    const int queue_size = queue.size();
    for (int _ = 0; _ < queue_size; ++_) {
      const auto current_word = queue.front();
      queue.pop_front();

      for (int i = 0; i < L; ++i) {
        const auto intermediate_word =
            current_word.substr(0, i) + "*" + current_word.substr(i + 1);
        for (const auto& word : all_combo_dict[intermediate_word]) {
          if (others_visited.count(word)) {
            return visited[current_word] + others_visited[word];
          }

          if (!visited.count(word)) {
            visited[word] = visited[current_word] + 1;
            queue.push_back(word);
          }
        }
      }
    }
    return nullopt;
  }

 public:
  int ladderLength(string beginWord, string endWord, vector<string>& wordList) {
    if (find(wordList.cbegin(), wordList.cend(), endWord) == wordList.cend()) {
      return 0;
    }

    L = beginWord.length();

    for (const auto& word : wordList) {
      for (int i = 0; i < L; ++i) {
        const auto intermediate_word =
            word.substr(0, i) + "*" + word.substr(i + 1);
        all_combo_dict[intermediate_word].push_back(word);
      }
    }

    deque<string> queue_begin{beginWord};
    deque<string> queue_end{endWord};

    map<string, int> visisted_begin{{beginWord, 1}};
    map<string, int> visisted_end{{endWord, 1}};
    optional<int> ans;

    while (!queue_begin.empty() && !queue_end.empty()) {
      if (queue_begin.size() <= queue_end.size()) {
        ans = visitWordNode(queue_begin, visisted_begin, visisted_end);
      } else {
        ans = visitWordNode(queue_end, visisted_end, visisted_begin);
      }

      if (ans.has_value()) {
        return ans.value();
      }
    }

    return 0;
  }
};
```

#### Language used for code

C++

#### Expected behavior

The editorial contains an implementation of both approaches in C++.

#### Additional context

- #8213 reported this behavior as a bug. Please close that issue with an appropriate comment once you resolve this one.
- I use `std::{set,map}` instead of `std::unordered_{set,map}` to avoid issues related to the worst-case complexity of hashing.
- I use `std::deque` instead of `std::queue` since (i) the latter is an adapter for the former, and (ii) `queue<...> queue` is confusing;
- I used `std::optional` to approximate the official solution in Python as much as possible. Feel free to replace it with a sentinel value of 0 instead, as in this [submission](https://leetcode.com/problems/word-ladder/submissions/921623403/);
- Please consider calling `all_combo_dict.clear()` at the start of each test case in the second approach.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

Adding C++ will be considered, this request has already been submitted to the content team. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by nskybytskyi** [comment]
> Adding C++ will be considered, this request has already been submitted to the content team.

Could you please link a specific issue that proposed an alternative C++ implementation? I wasn't able to find any relevant open issues.
