### ISSUE TITLE
Missing Test Case - 2. Add Two Numbers

### ISSUE THREAD

**Issue by name-is-cipher** [LeetCode-Feedback/LeetCode-Feedback#12551]
#### Your LeetCode username
name_is_cipher

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
If you assign your answer to List 1 itself and List 2 is bigger than List 1, when you iterate through List 1, then you will miss a few nodes.

#### Code you used for Submit/Run operation
```
/**
 * Definition for singly-linked list.
 * struct ListNode {
 *     int val;
 *     struct ListNode *next;
 * };
 */

struct ListNode* addTwoNumbers(struct ListNode* l1, struct ListNode* l2)
{
    struct ListNode *head = l1;
    int overFlow = 0;
    while(l1 != NULL && l2 != NULL)
    {
        printf("%p, %p | ", l1, l2);
        printf("%d + %d = ", l1->val, l2->val);
        l1->val = l1->val + l2->val + overFlow;
        overFlow = 0;
        if (l1->val/10 != 0)
        {
            overFlow = l1->val/10;
            l1->val = l1->val % 10;
        }
        printf("%d | %d\n", l1->val, overFlow);
        if(l1->next == NULL && l2->next != NULL)
        {
            l1->next = (struct ListNode *)malloc(sizeof(struct ListNode));
            l1 = l1->next;
            l2 = l2->next;
            l1->val = 0;
            l1->next = NULL;
            continue;
        }
        else if (l1->next != NULL && l2->next == NULL)
        {
            l2->next = (struct ListNode *)malloc(sizeof(struct ListNode));
            l2 = l2->next;
            l1 = l1->next;
            l2->val = 0;
            l2->next = NULL;
            continue;
        }
        if (l1->next == NULL && l2->next == NULL && overFlow != 0)
        {
            l1->next = (struct ListNode *)malloc(sizeof(struct ListNode));
            printf("%p, %p | ", l1, l2);
            l1 = l1->next;
            l1->val = overFlow;
            l1->next = NULL;      
            printf("%d | %p\n\n", overFlow, l1);
        }
        l1 = l1->next;
        l2 = l2->next;
    }
    return head;
}

```

#### Language used for code
C

#### Expected behaviour
If List 2 is bigger than List 1, in return value you will miss a few nodes.

#### Screenshots
None

#### Additional context
None

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by name-is-cipher** [comment]
# Test Case:
**L1:** [9, 9, 9]
**L2:** [9, 9, 9, 9, 9, 9]

# Code
struct ListNode* addTwoNumbers(struct ListNode* l1, struct ListNode* l2)
{
    struct ListNode *head = l1;
    int overFlow = 0;
    while(l1 != NULL && l2 != NULL)
    {
        printf("%p, %p | ", l1, l2);
        printf("%d + %d = ", l1->val, l2->val);
        l1->val = l1->val + l2->val + overFlow;
        overFlow = 0;
        if (l1->val/10 != 0)
        {
            overFlow = l1->val/10;
            l1->val = l1->val % 10;
        }
        printf("%d | %d\n", l1->val, overFlow);
        if(l1 == NULL && l2 != NULL)
        {
            l1 = (struct ListNode *)malloc(sizeof(struct ListNode));
            l1->val = 0;
            l1->next = NULL;
        }
        else if (l1 != NULL && l2 == NULL)
        {
            l2 = (struct ListNode *)malloc(sizeof(struct ListNode));
            l2->val = 0;
            l2->next = NULL;
        }
        if (l1 == NULL && l2 == NULL && overFlow != 0)
        {
            l1 = (struct ListNode *)malloc(sizeof(struct ListNode));
            l1->val = overFlow;
            l1->next = NULL;      
            printf("%d | %p\n\n", overFlow, l1);
        }
        l1 = l1->next;
        l2 = l2->next;
    }
    return head;
}
