### ISSUE TITLE
Time Limit Exceeded - 2316. Count Unreachable Pairs of Nodes in an Undirected Graph

### ISSUE THREAD

**Issue by Mestrace** [LeetCode-Feedback/LeetCode-Feedback#12557]
#### Your LeetCode username

monte_carrrrlo

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Standard union find method will not pass the test case for Python. Suggesting to slightly increase the time bound.

#### Code you used for Submit/Run operation

```
class Solution:
    def countPairs(self, n: int, edges: List[List[int]]) -> int:
        uf = list(range(n))

        def find(i):
            p = i
            while p != uf[p]:
                p = uf[p]
            uf[i] = p
            return p
        
        def union(i,j):
            pi = find(i)
            pj = find(j)
            uf[pi] = pj
        
        for i, j in edges:
            union(i, j)
        
        sz = defaultdict(int)
        for i in range(n):
            sz[find(i)] += 1
        
        existing = 0
        for v in sz.values():
            if v == 1:
                continue
            existing += v * (v - 1) // 2

        total = n * (n - 1) // 2

        return total - existing
```

#### Language used for code

Python

#### Expected behavior

This union find solution will pass test case

#### Screenshots

<img width="376" alt="image" src="https://user-images.githubusercontent.com/26028388/227697908-71d433c2-d565-48f4-a731-3d033ac6a264.png">

**Comment by nskybytskyi** [comment]
Hi there, 

Thank you for reaching out to us.

Your implementation of Union-Find is suboptimal and shall not pass. Firstly, you use neither union by size nor by find. Secondly, your path compression heuristic is incomplete, as you only update one parent. Hence the time complexity of the find operation is linear and does not amortize. 

Please refer to [my solution](https://leetcode.com/problems/count-unreachable-pairs-of-nodes-in-an-undirected-graph/submissions/922212077/) that fully compresses paths. Hence the time complexity of the find operation is amortized logarithmic. For your convenience, I have highlighted the difference below:

```diff
def find(i):
    p = i
    while p != uf[p]:
        p = uf[p]
-   uf[i] = p
+   while i != p:
+       ufi = uf[i]
+       uf[i] = p
+       i = ufi
    return p
```

Thank you for your support. If you have any other questions, please don't hesitate to let us know.
