### ISSUE TITLE
Missing Test Case - 11. Container With Most Water

### ISSUE THREAD

**Issue by pandharkardeep** [LeetCode-Feedback/LeetCode-Feedback#12554]
#### Your LeetCode username
pandharkardeep

#### Category of the bug

- [x] Missing Test Cases 

#### Description of the bug
There is a text case missing. Some people are doing it by finding largest and second largest element of array and subtracting indices of array. And for second test case, they are making a special code as it is a very small test case. There should be a test case where more than one elements are second largest element in an array

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
                int maxArea(vector<int>& height) {
       int ans = 0, n = height.size();
       int i = 0, j = n-1;
       while(i<j){
           if(height[i]>height[j]){
               ans = max(ans, (j-i)*height[j]);
               j--;
           }
           else{
               ans = max(ans, (j-i)*height[i]);
               i++;
           }
       }
       return ans;
    }
    
};
```

#### Language used for code
C++

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by pandharkardeep** [comment]
The missing test case :
[1,8 4,7,5,6,7,3, 2]
Here there are two numbers which have second largest value in array.
Another test case :
[2,3].
Thank you. Regards

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link since the above code received Compile Error after submit: https://leetcode.com/submissions/detail/923738280/

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
