### ISSUE TITLE
C++ implementation for problem 1506. Find Root of N-ary Tree

### ISSUE THREAD

**Issue by rpg360** [LeetCode-Feedback/LeetCode-Feedback#12559]
#### Your LeetCode username
[rpg36000](https://leetcode.com/rpg36000/)

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Solutions for problem [1506. Find Root of N-ary Tree](https://leetcode.com/problems/find-root-of-n-ary-tree/) do not provide C++ implementation.

#### Code you used for Submit/Run operation
Approach 1: Déjà-Vu
      - your style [submission link](https://leetcode.com/submissions/detail/921715103/)
      - my preferred one [submission link](https://leetcode.com/submissions/detail/921711737/)

Approach 2: YOLO (You Only Look Once)
      - your style [submission link](https://leetcode.com/submissions/detail/923000727/)
      - my preferred one [submission link](https://leetcode.com/submissions/detail/923006492/)

#### Language used for code
C++

#### Expected behavior
Feel free to use them.

**Comment by nskybytskyi** [comment]
Thank you for reaching out to us!

I love type traits, but I'm afraid that many users will find them confusing.

Note to self: consider adding a collision-based anti-hashing test case.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

LeetCode editorials do not necessarily have all languages included.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
