### ISSUE TITLE
5. Longest Palindromic Substring - Testcase 86

### ISSUE THREAD

**Issue by savan2508** [LeetCode-Feedback/LeetCode-Feedback#12555]
#### Your LeetCode username
sawanpatel2508

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
 I have tried to submit the following code, but it is giving me a time limit exceeded when I submit it. I know the script is correct since I have tried it on other IDE. 

#### Code you used for Submit/Run operation

```
class Solution:
    def longestPalindrome(self, s: str) -> str:
        self.i = 0
        self.output = ''
        if len(s) <= 1:
            return s
        else:
            while self.i < len(s):
                for j in range(1, len(s)):

                    if s[self.i:len(s)-j+1] == s[-j:-len(s)-1+self.i:-1] and len(s[self.i:len(s)-j+1]) > len(self.output):
                        self.output = s[self.i:len(s)-j+1]
                self.i += 1
        return self.output
```

#### Language used for code
 Python 3

#### Screenshots

![image](https://user-images.githubusercontent.com/36905739/227623157-76bbca91-d89e-4d1f-95fd-8894436f60c2.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us! Unfortunately, we are unable to troubleshoot the different behavior between your local IDE and the LeetCode environment.

For this issue, please raise this as a discussion post in the problem discussion section as other users may have run into the same issue and resolved it.

At LeetCode, we care about the whole learning experience that comes with each problem and we encourage users to teach and help each other to enrich their learning. In addition, we want our users to debug their code and learn from the process.

We appreciate your time and support.
