### ISSUE TITLE
Solution not accepted 15.3Sum - possible error with a test case

### ISSUE THREAD

**Issue by fjrsales** [LeetCode-Feedback/LeetCode-Feedback#12569]
#### Your LeetCode username

user2949uL

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Test case nums = [3,0,-2,-1,1,2] is returning only part of expected output : [[-2,-1,3]]. However, I've run the same code in VSCode and got the expected output: [[-2, -1, 3], [-1, 0, 1], [-2, 0, 2]].

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution:
    def threeSum(self, nums: List[int]) -> List[List[int]]:
        
        added = {}
        trios = []

        for i, num in enumerate(nums):
            target = -num
            temp = [*nums[:i],*nums[i+1:]]
            d = {}
            for j, n in enumerate(temp):
                if(n in d):
                    dummy = sorted([num,n,temp[d[n]]])
                    if(tuple(dummy) not in added):
                        trios.append(dummy)
                        added[tuple(dummy)] = ""
                        #print(f"num: {num} n: {n} target:{target} d:{d} trios:{trios}")
                else:
                    d[target - n] = j
                    #print(f"num: {num} n: {n} target:{target} d:{d} trios:{trios}")

            return trios
```

#### Expected behavior

Test case nums = [3,0,-2,-1,1,2] is returning only part of expected output : [[-2,-1,3]]. However, I've run the same code in VSCode and got the expected output: [[-2, -1, 3], [-1, 0, 1], [-2, 0, 2]].

#### Screenshots

Leetcode console
![image](https://user-images.githubusercontent.com/29614468/227731897-c9776cd7-3fe9-4b41-8066-ccb2892928ad.png)

VSCode
<img width="505" alt="image" src="https://user-images.githubusercontent.com/29614468/227731852-d0c6f90d-5d1b-440b-b318-4714c3d9e092.png">

**Comment by nskybytskyi** [comment]
Hi there,

Thank you for reaching out to us.

The code you run on the website differs from the local one. Specifically, the `return` statement differs from the `print` statement. Most importantly, they have different indentation levels. It produces an optical illusion of codes being the same when they are not.

Note that a type checker also hints towards this problem by saying that your function could return `None`, which it shouldn't:
<img width="927" alt="Знімок екрана 2023-03-26 о 08 52 09" src="https://user-images.githubusercontent.com/25816558/227757921-b8f3686d-9bef-467b-a069-963a1b3ee8ed.png">

Thank you for your support. If you have any other questions, please don't hesitate to let us know.

**Comment by fjrsales** [comment]
Dear colleague,
Thank you very much! I didn't notice this difference between these codes.
Best regards!




Em dom., 26 de mar. de 2023 02:55, Nikita Skybytskyi <
***@***.***> escreveu:
