### ISSUE TITLE
Missing Test Case - 50. Pow(x, n)

### ISSUE THREAD

**Issue by neelesh98965** [LeetCode-Feedback/LeetCode-Feedback#12560]
#### Your LeetCode username
neeleshgoyal88

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
-  Missing Test Cases 

#### Description of the bug

The testase range for n is given -2^31 to 2^31-1 and it is failing if I m putting the value near to the edge cases but if I m putting the condition for INT_MAX and INT_MIN only, then it is passing all the testcases but it should not  pass them all, as i have put only the condition for INT_MAX and INT_MIN

#### Code you used for Submit/Run operation

```
class Solution {
public:
    double powe(double x,int n){
        if(n == 0)return 1;
        return x*powe(x,n-1);
    }
    double myPow(double x, int n) {
        if (n == INT_MAX) return (x == 1) ? 1 : (x == -1) ? -1 : 0;
        if (n == INT_MIN) return (x == 1 || x == -1) ? 1 : 0;
        double a = powe(x,abs(n));
        if(n<0)return 1/a;
        return a;
    }
};
```

#### Language used for code
C++

#### Expected behavior
I thought that the code will fail but rather it passed it successfully .Earlier when the condition of INT_MAX and INT_MIN were not put it was failing for INT_MAX and INT_MAX-3 but after  I put the condition it is passing for INT_MAX but failing for INT_MAX-3 in the editor but on submission it is passing all the testcases .

**Comment by nskybytskyi** [comment]
Hi there,

Thank you for reaching out to us.

I have mixed feelings about your suggestion. Say we add several test cases with large `n`, like `x = 1` and `n = 1000000000`. People could hardcode them _exactly_ like you did with `INT_{MIN,MAX}`. 

In particular, [new contest rules](https://leetcode.com/discuss/general-discussion/951105/new-contest-rule-effective-from-december-2020) specifically mention this behavior as acceptable:

> ➡️ **Hardcoding Test cases**
>
> **Definition**: The user has hardcoded some test cases using an if-else statement.
> To ensure the fairness of the contest, LeetCode will hide some test cases during the contest. When users submit incorrect submissions, LeetCode will not show the hidden test cases to the users.
>
> **Action**: If the user uses hardcoding test cases in the submission, but the submission gets "Accepted", LeetCode will accept the submission as valid and no action would be taken against the user.

While LeetCode makes its best effort to ensure that such cases are rare, sometimes it is impossible to enforce desired behavior. In such cases, we resort to common sense. Any reasonable person should understand they are doing something wrong after hardcoding even _one_ test case. At the same time, it is unlikely that even _ten_ test cases will stop someone unreasonable from hardcoding all of them.

Thank you for your support. If you have any other questions, please don't hesitate to let us know.
