### ISSUE TITLE
Solution not accepted - 6. Zigzag Conversion

### ISSUE THREAD

**Issue by JoFGD** [LeetCode-Feedback/LeetCode-Feedback#12561]
#### Your LeetCode username
jfgd

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
I typed a solution for the problem which wasn't accepted in spite of it producing a correct result. The first test case requires 
"PAHNAPLSIIGYIR", I got "PAHNAPLSIIGYIR", which even in the code using == operator tests as equal.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    string convert(string s, int numRows) {
        string newS;
        int repTop = (numRows-1)*2;

        if (repTop==0){
            return s;
        }

        int remainder = (s.length())%repTop;
        int iterations = (s.length()-remainder)/repTop;
        bool remZero = remainder==0;

        for (int i=0; i<(numRows-1); i++){
            if ((s.length()-1)<i){break;}

            int total = i;
            int dif = i*2;
            newS += s[total];

            for (int j=0; j<iterations; j++){
                if (j==(iterations-1)){
                    total += (repTop - dif);
                } else {
                    if (i==0){
                        total += repTop;
                    } else {
                        total += (repTop - dif);
                        newS += s[total];
                        total += dif;
                    } 
                }

                newS += s[total];
            }

            if ((remainder >= dif)&&(dif != 0)) {
                total += dif;
                newS += s[total];

                if (remainder >= (repTop - dif)){
                    total += (repTop - dif);
                    newS += s[total];
                }
            }

        }

        int total = (numRows-1);
        newS += s[total];

        for (int i=0; i<(iterations-1); i++){
            if (i==(iterations-1)){
                if (remainder >= repTop/2){
                    total += repTop/2;
                }
            } else {
                total += repTop;
            }

            newS += s[total];
        }

        return newS;
    }
};
```

#### Language used for code
C++

#### Expected behavior
I expected the solution to be accepted, else rejected by a test case which it didn't return a good value for. 

#### Screenshots

<img width="824" alt="Screenshot 2023-03-25 at 18 45 31" src="https://user-images.githubusercontent.com/96386238/227712551-e6e91c55-24d6-4b32-870e-8ac30af045a7.png">
<img width="823" alt="Screenshot 2023-03-25 at 18 45 39" src="https://user-images.githubusercontent.com/96386238/227712555-da629301-060d-45b3-bd21-d53f72649a96.png">

**Comment by nskybytskyi** [comment]
Hi there,

Thank you for reaching out to us. 

Please consider adding this debug output before the return statement:
```cpp
cout << "s.length = " << s.length() << ", newS.length = " << newS.length() << "\n";
```

It outputs `s.length = 14, newS.length = 15`. Hopefully, it will help you find the issue with your approach.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
