### ISSUE TITLE
Missing Test Case - 189. Rotate Array

### ISSUE THREAD

**Issue by Naman2608** [LeetCode-Feedback/LeetCode-Feedback#12575]
#### Your LeetCode username

Naman_Chhabra

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ --] Missing Test Cases 

#### Description of the bug

Add one test case of when array size is too big and k is greater than size of array .

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    void rotate(vector<int>& nums, int k) {
        // if array has onlu one element 
        if (nums.size()==1){
            return;
        }

        reverse(nums.begin(),nums.end());

        // for k less than size of array
        if(nums.size()<k){
            for(int i=0 ; i<k;i++){
                int temp= nums[0];
                nums.erase(nums.begin());
                nums.push_back(temp);
            }
            reverse(nums.begin(),nums.end());
            return;
        }
        
        // general case
        int j=0;
        for(int i=k-1;i>j;i--){
            swap(nums[j++],nums[i]);
        }
         j=nums.size()-1;
        for(int i=k;i<j;i++){
            swap(nums[j--],nums[i]);
        }
        

        
    }
};
```

#### Language used for code
 C++ 

#### Expected behavior

My code passes all test cases but it not supposed to be.

**Comment by nskybytskyi** [comment]
Hi there,

Thank you for reaching out to us.

Your solution doesn't do what you think it does. Specifically, this comment looks suspiciously delusional:
```cpp
// for k less than size of array
if(nums.size()<k){
    ...
}
```

Thank you for your support. If you have any other questions, please don't hesitate to let us know.
