### ISSUE TITLE
Missing Test Case - 2603. Collect Coins in a Tree

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#12579]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets Runtime Error on the following testcase:
[1, 0, 0, 0, 0, 0]
[[5, 2], [2, 0], [5, 4], [3, 4], [4, 1]]

#### Code you used for Submit/Run operation

```
class Solution:
	def collectTheCoins(self, coins: List[int], edges: List[List[int]]) -> int:
		if len(edges) <= 4:
			return 0
		cut_edge = 0
		node_to_others = {}
		dis_to_coin = [-1] * len(coins)
		for edge in edges:
			left = edge[0]
			right = edge[1]
			if left not in node_to_others:
				node_to_others[left] = set()
			if right not in node_to_others:
				node_to_others[right] = set()
			node_to_others[left].add(right)
			node_to_others[right].add(left)
		single_edge = []
		for key, value in node_to_others.items():
			if len(value) == 1:
				single_edge.append(key)
		while len(single_edge) > 0:
			cur_node = single_edge.pop()
			if coins[cur_node] == 1:
				dis_to_coin[cur_node] = max(dis_to_coin[cur_node], 0)
			if dis_to_coin[cur_node] == 2:
				continue
			cut_edge += 1
			to_node = node_to_others[cur_node].pop()
			node_to_others[to_node].remove(cur_node)
			if dis_to_coin[cur_node] >= 0:
				dis_to_coin[to_node] = max(dis_to_coin[to_node], dis_to_coin[cur_node] + 1)
			if len(node_to_others[to_node]) == 1:
				single_edge.append(to_node)
		return (len(coins) - 1 - cut_edge) * 2
```

#### Language used for code

Python3

#### Expected behavior

The code gets Runtime Error.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
