### ISSUE TITLE
Missing Test Case - 1626. Best Team With No Conflicts

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#1257]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution from discuss section is accepted but fails on the following test case:

[1]
[1000]

#### Code you used for Submit/Run operation

```
class Solution {
    public int bestTeamScore(int[] scores, int[] ages) {
        int n = scores.length;
        var idxs = new Integer[n];
        for(int i = 0; i < n; ++i) idxs[i] = i;
        Arrays.sort(idxs,(ia,ib)->{
            int cmp = scores[ia]-scores[ib];
            return cmp != 0 ? cmp : ages[ia]-ages[ib];
        });
        int ans = 0, dp[] = new int[1001];//dp[age] == up until age or younger, the max possible score after the first i students were seen in increasing scores order
        for(int i = 0; i < n; ++i){
            int curAge = ages[idxs[i]];
            dp[curAge] += scores[idxs[i]];//since dp[curAge] can only store not greater scores, than the current score, we can freely add the current score 
            for(int age = curAge+1; age <= 1000; ++age){//since dp[age] means max scores for age or younger, we might need updates for greater age group
                ans = Math.max(ans,dp[age] = Math.max(dp[age],dp[curAge]));
            }
        }
        return ans;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/96661883-24f4cd80-131b-11eb-9865-e5e2a36d8f60.png)
![image](https://user-images.githubusercontent.com/32546406/96661912-33db8000-131b-11eb-9638-ecc1ec2a023f.png)

#### Additional context

https://leetcode.com/problems/best-team-with-no-conflicts/discuss/899834/Sorting-by-scores-first

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
