### ISSUE TITLE
Solution issue - 204. Count Primes

### ISSUE THREAD

**Issue by przemek3d88** [LeetCode-Feedback/LeetCode-Feedback#12577]
#### Your LeetCode username
przemysaw2

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The time complexity of the solution is O(n). The following piece of code is clearly O(n):
```
int numberOfPrimes = 0;
for (int i = 2; i < n; i++) {
    if (numbers[i] == false) {
        ++numberOfPrimes;
    }
}
```

**Comment by nskybytskyi** [comment]
Yeah, that editorial is a mess and a half! It even says that `n / 2 + n / 3 + n / 5 + ...` is `O(log⁡ log⁡ n)`, whereas it is clearly `O(n log log n)` since we have an additional factor of `n`. Somebody has to revisit it, but I can't tell you when it will happen.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We will add a factor of n to the time complexity and consider rewriting the article.

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
