### ISSUE TITLE
Missing Test Case - 1506. Find Root of N-Ary Tree

### ISSUE THREAD

**Issue by nskybytskyi** [LeetCode-Feedback/LeetCode-Feedback#12584]
#### Your LeetCode username

[nskybytskyi](https://leetcode.com/nskybytskyi/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The solution below gets AC in the problem [1506. Find Root of N-Ary Tree](https://leetcode.com/problems/find-root-of-n-ary-tree/description/), but should get TLE on the suggested collision-based anti-hashing test case.

#### Code you used for Submit/Run operation

[Submission link](https://leetcode.com/problems/find-root-of-n-ary-tree/submissions/922315551/)

```cpp
class Solution {
  public:
    Node* findRoot(vector<Node*>& tree) {
      Node* root { nullptr };
      unordered_set<int> seen {};   // set that contains all the child nodes.

      // add all the child nodes into the set
      for(auto node : tree) {
        for(auto child : node->children)
          // we could either add the value or the node itself.
          seen.insert(child->val);
      }

      // find the node that is not in the child node set.
      for(auto node : tree) {
        if (seen.find(node->val) == seen.end()) {
          root = node;
          break;
        }
      }

      return root;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The submission should get TLE on the following test case: [1506-ns-anti-hash.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/11071093/1506-ns-anti-hash.txt)

#### Additional context

- This solution is taken from #12559, which suggested adding it to the editorial as the official C++ implementation. Please resolve this issue before addressing that. I recommend replacing `std::unordered_set` with `std::set` with an appropriate comment.
- `49'201` is the largest value below `50'000` in the [magical list](https://github.com/gcc-mirror/gcc/blob/5bea0e90e58d971cf3e67f784a116d81a20b927a/libstdc%2B%2B-v3/src/shared/hashtable-aux.cc#L42) used by `std::unordered_set`;
- The following Python 3 program generates the suggested test case:
```py
p = 49_201
n = 50_000

tree = list(range(-p * (n // 2), p * (n // 2), p))
tree_bytes = str(tree).replace(' ', '')

with open("1506-ns-anti-hash.txt", encoding="utf-8", mode='w') as file:
    file.write(tree_bytes)

```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

We don't try to break hash solutions.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by nskybytskyi** [comment]
@LC-Pam You should add this 

> We don't try to break hash solutions.

to contributing guidelines. Otherwise, you cannot expect users not to create such reports.
