### ISSUE TITLE
Wrong TestCase #1620. Coordinate With Maximum Network Quality

### ISSUE THREAD

**Issue by munendrapandey** [LeetCode-Feedback/LeetCode-Feedback#1258]
#### Your LeetCode username
munendra

#### Category of the bug
- [x] Question

#### Description of the bug
1-> For testcase
[[28,6,30],[23,16,0],[21,42,22],[50,33,34],[14,7,50],[40,31,4],[39,45,17],[46,21,12],[45,36,45],[35,43,43],[29,41,48],[22,27,5],[42,44,45],[10,49,50],[47,43,26],[40,36,25],[10,25,6],[27,30,30],[50,35,20],[11,0,44],[34,29,28]]
12

Expected Output is : 42,44 which is wrong, it should be 45,36

x = 28 y = 6 and network_quality = 30.000000
x = 23 y = 16 and network_quality = 2.878083
x = 21 y = 42 and network_quality = 27.296693
x = 50 y = 33 and network_quality = 52.069456
x = 14 y = 7 and network_quality = 55.106913
x = 40 y = 31 and network_quality = 23.248053
x = 39 y = 45 and network_quality = 48.853808
x = 46 y = 21 and network_quality = 12.315908
x = 45 y = 36 and network_quality = 67.212529
x = 35 y = 43 and network_quality = 62.838953
x = 29 y = 41 and network_quality = 60.205610
x = 22 y = 27 and network_quality = 9.391774
x = 42 y = 44 and network_quality = 66.093767
x = 10 y = 49 and network_quality = 50.000000
x = 47 y = 43 and network_quality = 51.320418
x = 40 y = 36 and network_quality = 54.109447
x = 10 y = 25 and network_quality = 6.000000
x = 27 y = 30 and network_quality = 38.141921
x = 50 y = 35 and network_quality = 44.038098
x = 11 y = 0 and network_quality = 49.803310
x = 34 y = 29 and network_quality = 34.709382

2-> Missing Test cases.
when solution is not the point of tower location.
eg
[[0,1,2],[1,0,2],[1,2,2],[2,1,2]]

#### Code you used for Submit/Run operation

```
#define tower_points_only 1
#define all_points 2

#define X_LIMIT 50
#define Y_LIMIT 50

#define method tower_points_only

class Solution {
public:
#if method == tower_points_only
    vector<int> bestCoordinate(vector<vector<int>>& towers, int radius) {
        double distance;
        double power;
        int x_pos;
        int y_pos;
        map<pair<int,int>,double> mp;
        for (auto itr : towers){
 
            int x_ctr = itr[0];
            int y_ctr = itr[1];
            power = 0;
            for (auto itr2 : towers) {
                // Calculate Power from each point
                x_pos = itr2[0];
                y_pos = itr2[1];
                int q_factor = itr2[2];
                distance = sqrt(pow(x_ctr -x_pos,2) + pow(y_ctr - y_pos,2));
                if (distance > radius) continue;
                power += (q_factor/(1.0 + distance)); 
            }
            // update it in Map
            printf("x = %d y = %d and network_quality = %f\n",x_ctr,y_ctr,power);
            mp.insert({{x_ctr,y_ctr},power});
        }
        
        double Max = 0;
        // finding max and updating it 
        for(auto point_p : mp){
            Max = max(Max,point_p.second);
        }
        
        vector<int> result(2);
        // Map are sorted so first occurance wil be minimum
        for(auto point_p : mp){
           if (Max == point_p.second) {
                result[0] = point_p.first.first;
                result[1] = point_p.first.second;
               break; // To be sure that first element is taken only
           }
        }        
        return result;
    }
#elif method == all_points
   vector<int> bestCoordinate(vector<vector<int>>& towers, int radius) {
        double distance;
        double power;
        int x_pos;
        int y_pos;
        map<pair<int,int>,double> mp;
        for (int x_ctr = 0; x_ctr <= X_LIMIT; x_ctr++) {
            for (int y_ctr= 0; y_ctr <=Y_LIMIT; y_ctr++) {
                power = 0;
                for (auto itr2 : towers) {
                    // Calculate Power from each point
                    x_pos = itr2[0];
                    y_pos = itr2[1];
                    int q_factor = itr2[2];
                    distance = sqrt(pow(x_ctr -x_pos,2) + pow(y_ctr - y_pos,2));
                    if (distance > radius) continue;
                    power += (q_factor/(1.0 + distance)); 
                }
                // update it in Map
                printf("x = %d y = %d and network_quality = %f\n",x_ctr,y_ctr,power);
                mp.insert({{x_ctr,y_ctr},power});
            }
        }
        
        double Max = 0;
        // finding max and updating it 
        for(auto point_p : mp){
            Max = max(Max,point_p.second);
        }
        
        vector<int> result(2);
        // Map are sorted so first occurrence will be minimum
        for(auto point_p : mp){
           if (Max == point_p.second) {
                result[0] = point_p.first.first;
                result[1] = point_p.first.second;
               break; // To be sure that first element is taken only
           }
        }        
        return result;
    }
#endif
};
```

#### Expected behavior
Either Mention in question that we have to take floor value of signal strength each time, else change the expected result.

**Comment by lc-kay** [comment]
Hi @munendrapandey 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@munendrapandey The provided solution already gets WA. Please re-read the equation of the signal strength for clarification as to why the expected answer is correct. Thank you for your time and support.
