### ISSUE TITLE
Missing Test Case - 175. Combine Two Tables

### ISSUE THREAD

**Issue by JeevaRP-SDE** [LeetCode-Feedback/LeetCode-Feedback#12587]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
While I am typing the Solution LEFT JOIN not getting turn on Blue Colour .

#### Code you used for Submit/Run operation

```
Select  firstName,lastName,city,state
 from Person LEFT JOIN Address on Person.personId = Address.personId
```

#### Language used for code
   MYSQL

#### Expected behavior
Need to come like a Blue color words . When We type Left join .

#### Screenshots
![Screenshot (509)](https://user-images.githubusercontent.com/68347006/227765519-d51b87bd-d5d7-4300-98ee-d0f3e69865cc.png)

![Screenshot (510)](https://user-images.githubusercontent.com/68347006/227765537-b86b85db-d415-4406-8097-ef557e729d12.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
