### ISSUE TITLE
Missing Test Case - 2360. Longest Cycle in a Graph

### ISSUE THREAD

**Issue by Salman-Mandal** [LeetCode-Feedback/LeetCode-Feedback#12595]
#### Your LeetCode username

iamsalman28818
[profile](https://leetcode.com/iamsalman28818/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [+] Missing Test Cases 

#### Description of the bug
The Problem -"2360. Longest Cycle in a Graph" missing a testcase where my code gives wrong output but when i submit the code it shows accepted.
I provided a screenshot below.

#### Code you used for Submit/Run operation

```
// Longest Cycle in a Graph
class Solution {
private:
    int ans=-1;
    void dfs(int node,vector<int>& edges,vector<int>& vis,vector<int>& dfsvis,int i)
    {
        vis[node]=1;
        dfsvis[node]=i;
        int next=edges[node];
        if(next!=-1)
        {

            if(vis[next]==0)
            {
                dfs(next,edges,vis,dfsvis,i+1);
            }
            else if(dfsvis[next]!=0)
            {
                ans=max(ans,i+1-dfsvis[next]);
                return;
            }
        }

        dfsvis[node]=0;
    }
public:
    int longestCycle(vector<int>& edges) {
        int n=edges.size();
        vector<int> vis(n,0);
        vector<int> dfsvis(n,0);
        for(int i=0;i<n;i++)
        {
           if(vis[i]==0)
           {
                dfs(i,edges,vis,dfsvis,1);
           }
        }


        return ans;
    }
};
```

#### Expected behavior

The testcase is [1,2,0,4,5,6,7,8,2] . for this testcase my code (and i show others also) is wrong and it should not be accepted.

#### Screenshots

![image](https://user-images.githubusercontent.com/76894465/227790322-2584c5e9-5b4a-47c2-b15d-86c92f09e7b6.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
