### ISSUE TITLE
2360. Longest Cycle in a Graph - Typo in Approach 2

### ISSUE THREAD

**Issue by StrawHatDragon100** [LeetCode-Feedback/LeetCode-Feedback#12599]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I think there is a typo in the approach 2 algorithm.
The 2nd point states to create an array `degree` but in later points it is referred as `indegree`

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

![image](https://user-images.githubusercontent.com/19656900/227799691-3417a7db-4022-4196-b823-a1a061c55797.png)
![image](https://user-images.githubusercontent.com/19656900/227799708-5e21c556-a16f-4744-ad38-3319fd9a8403.png)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
