### ISSUE TITLE
Incomplete Constraints - 703. Kth Largest Element in a Stream

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1259]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

https://leetcode.com/problems/kth-largest-element-in-a-stream/
703. Kth Largest Element in a Stream

Test case 1:

    ["KthLargest","add","add","add","add","add"]
    [[5,[4,5,8,2]],[3],[5],[10],[9],[4]]

Passes as 1st `add` will add 3 to [4,5,8,2], and then we have k=5 elements, so `add` returns correctly

Test case 2:

    ["KthLargest","add","add","add","add","add"]
    [[6,[4,5,8,2]],[3],[5],[10],[9],[4]]

Here, k is 6, so `add` throws below error, as there are only 5 elements after 1st `add`.

    'add' arguments are invalid: Invalid call to add, there must be at least k elements to find the kth one.
    Error:  'add' arguments are invalid: Invalid call to add, there must be at least k elements to find the kth one.

However, the error message condition is not given in constraints:

Please add something like the below to constraints:
> Atleast `k` elements must be present, after every call to `add`.

#### Code you used for Submit/Run operation

```
```

#### Expected behavior

- All constraints must be given in the question description otherwise User time is wasted in test case generation.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
