### ISSUE TITLE
Missing Test Case - 1473. Paint House III

### ISSUE THREAD

**Issue by sonicpower** [LeetCode-Feedback/LeetCode-Feedback#12591]
#### Your LeetCode username

icestone

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x ] Missing Test Cases 

#### Description of the bug

The missing test cases are when "n=target=1". Examples are:
- houses = [1], cost = [[2]], m = 1, n =1, target = 1, expected_result = 0
- houses = [0], cost = [[2]], m = 1, n =1, target = 1, expected_result = 2

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by nskybytskyi** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by sonicpower** [comment]
This is just adding new test cases that are missing. Why do you need code and language?

**Comment by nskybytskyi** [comment]
We only add new test cases when some solution gets accepted but shouldn't because it fails on the suggested test case. This minimizes the test suite and optimizes the grader's performance. We could stress-test each solution for minutes instead of relying on hardcoded test cases if performance was not an issue 😂

**Comment by sonicpower** [comment]
Got it. Here you go (language: Python):

class Solution:
    def minCost(self, houses: List[int], cost: List[List[int]], m: int, n: int, target: int) -> int:
        dp = [[[float('inf')]*n for _ in range(target+1)] for _ in range(m+1)]
        for k in range(n):
            dp[-1][0][k] = 0
        for j in range(1, target+1):
            for i in range(m-1, -1, -1):
                c = houses[i]
                if c == 0:
                    for k in range(n):
                        v = cost[i][k] if c == 0 else 0
                        dp[i][j][k] = v+min([dp[i+1][j-1][k2] if k2 != k else dp[i+1][j][k2] for k2 in range(n)])
                else:
                    dp[i][j][c-1] = min([dp[i+1][j-1][k2] if k2 != c-1 else dp[i+1][j][k2] for k2 in range(n)])
        res = min(dp[0][-1])
        return res if res < float('inf') else -1

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
