### ISSUE TITLE
Missing Test Case - 2360. Longest Cycle in a Graph

### ISSUE THREAD

**Issue by shivambeenhere** [LeetCode-Feedback/LeetCode-Feedback#12597]
#### Your LeetCode username

shivambeenhere

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Missing test case - [5,2,3,1,-1,-1]

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int longestCycle(vector<int>& edges) {
        int n = edges.size();
        vector<int> dist(n, -1);
        int ans = -1;

        for (int i = 0; i < n; i++) {
            if (dist[i] == -1) {
                int curDist = 0;
                unordered_set<int> path;
                while (edges[i] != -1 && dist[i] == -1) {
                    dist[i] = curDist++;
                    path.insert(i);
                    i = edges[i];
                }
                if (path.count(i)) ans = max(ans, curDist - dist[i]);
            }
        }
        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior

The Leetcode OJ accepts the solution but it should give Wrong Answer for this test case

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
