### ISSUE TITLE
Question 11 : 1174. Immediate Food Delivery II (Expected output doesn't include rounding of two decimal places)

### ISSUE THREAD

**Issue by abhivasanth** [LeetCode-Feedback/LeetCode-Feedback#1260]
Hi Leetcode team,

Description: Problem content issues
Expected output doesn't include round of two decimal places.

(P.S no issues in terms of acceptance of solution)
The expected output is to be based of 2 decimal places, but the displayed expected output in the UI shows additional rounding values. Please refer attached screenshot. Thought I share this finding with you. 

Please let me know if you've any questions or comments.

Thank you for your help in advance!

-Abhi
![LC 1174](https://user-images.githubusercontent.com/24664712/96692286-b6276c80-133a-11eb-9db0-adea3a3d413e.JPG)

**Comment by lc-kay** [comment]
Hi @abhivasanth 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @abhivasanth 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
