### ISSUE TITLE
Missing Test Case - 1056. Confusing Number

### ISSUE THREAD

**Issue by mycoolhairison** [LeetCode-Feedback/LeetCode-Feedback#12609]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x ] Missing Test Cases 

#### Description of the bug

Missing test cases cause incorrect solution to get accepted.  My code was accepted but actually it does not handle the test case: 80.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool confusingNumber(int n) {
        if(n == 0) return false;
        vector<int> digits;
        bool seenNonzero=false;
        while(n > 0) {
            int m = n % 10;
            if(m == 2 || m == 3 || m == 4 || m == 5 || m == 7) return false;
            else if(seenNonzero) { 
                digits.push_back(m);
            }
            else { 
                if(m == 1 || m == 6 || m == 8 || m == 9) {
                    seenNonzero = true;
                    digits.push_back(m);
                }
            }
            n = n /10;
        }
        for(int i = 0; i<(digits.size()+1)/2; i++) {
            if(digits[i]==1 && digits[digits.size()-i-1] != 1) return true;
            if(digits[i]==6 && digits[digits.size()-i-1] != 9) return true;
            if(digits[i]==9 && digits[digits.size()-i-1] != 6) return true;
            if(digits[i]==8 && digits[digits.size()-i-1] != 8) return true;
            if(digits[i]==0 && digits[digits.size()-i-1] != 0) return true;
        }
        return false;
        
    }
};
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
