### ISSUE TITLE
Incorrect wrong answer

### ISSUE THREAD

**Issue by resotto** [LeetCode-Feedback/LeetCode-Feedback#12607]
#### Your LeetCode username
resotto

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
problem: https://leetcode.com/problems/check-for-contradictions-in-equations/

The following test case expects `true` but `false` must be returned since:

- le = 2 * et
- code = 0.2 * le
- et = 2 * code

So

- le = 2 * et = 4 * code = 0.8 * le (!= 1)

```
[["le","et"],["le","code"],["code","et"]]
[2,5,0.5]
```

#### Expected behavior
`false`

#### Screen Shot
![Screenshot 2023-03-27 at 23 09 35](https://user-images.githubusercontent.com/19743841/227964502-67851884-ff80-4466-b347-e8f6782a9b77.png)

**Comment by nskybytskyi** [comment]
Thank you for reaching out to us. The expected answer is correct. A quote from the statement:

>  Return `true` if there _is_ a contradiction

As you explained, there _is_ a contradiction, so the expected answer is `true`. If you have any other questions, please don't hesitate to let us know.

**Comment by resotto** [comment]
got it, thank you!
