### ISSUE TITLE
Wrong input accepted - 853. Car Fleet

### ISSUE THREAD

**Issue by xelplogoog** [LeetCode-Feedback/LeetCode-Feedback#12600]
#### Your LeetCode username
c4tdog

#### Category of the bug
- [ ] Question

#### Description of the bug
One of the constraints is:
0 < speed[i] <= 1000000

Speed 0 doesn't make any sense here b/c having the speed zero a car will never reach the destination.
But, 0 is accepted as a valid input in `speed` array

try to run this test
Input: target = 12, position = [10,8,0,5,3], speed = [0,4,1,1,3]
it's an input from the example #1, but first element of the `speed` changed to 0

also, if you try to run all tests with valid code, all tests will be marked as `Wrong answer` and `expected` section will be empty

![image](https://user-images.githubusercontent.com/2188302/227803142-b27838f8-583a-43a7-84d2-812cac435ad9.png)

a short demo
![fleet0](https://user-images.githubusercontent.com/2188302/227804103-5ab11a7e-dd49-4600-bd94-acc6c7ffb4bf.gif)

**Comment by nskybytskyi** [comment]
Thank you for reaching out to us. 

The validator correctly identifies this test case as invalid. You can observe it in the old design:

<img width="400" alt="Знімок екрана 2023-03-26 о 23 51 51" src="https://user-images.githubusercontent.com/25816558/227803957-e17b2fbd-acc2-44f7-8490-fea7df855b68.png">

We could improve the way it is presented in the new design. However, it will likely have a low priority. Most users don't input invalid test cases anyway.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by xelplogoog** [comment]
> Thank you for reaching out to us.
> 
> The validator correctly _identifies_ this test case as invalid. You can observe it in the old design:
> 
> <img alt="Знімок екрана 2023-03-26 о 23 51 51" width="400" src="https://user-images.githubusercontent.com/25816558/227803957-e17b2fbd-acc2-44f7-8490-fea7df855b68.png">
> 
> We could improve the way it is _presented_ in the new design. However, it will likely have a low priority because most users don't input invalid test cases.
> 
> We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

at least, update the constrains. I tried it b/c constraint says the speed could be 0. Thanks
