### ISSUE TITLE
Missing Test Case - 51. N-Queens

### ISSUE THREAD

**Issue by zkeal** [LeetCode-Feedback/LeetCode-Feedback#12616]
#### Your LeetCode username

zkeal

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 
Solution

#### Description of the bug

The official solution missed some correct cases, when the n is larger then 5.

#### Code you used for Submit/Run operation

```
// N-Queen
class Solution {
    public List<List<String>> solveNQueens(int n) {
        int[][] board = new int[n][n];
        List<List<position>> final_result = new ArrayList<>();
        for(int i = 0; i < n; i ++)
        {
            List<position> new_temp = new ArrayList<>();
            Set<Integer> new_Y = new HashSet<>();
            new_temp.add(new position(0,i));
            new_Y.add(i);
            get_availible_pos(final_result, new_temp, new_Y, 1, n - 1, i, n);
        }

        List<List<String>> final_str = new ArrayList<>();
        
        for(List<position> temp_list: final_result)
        {
            final_str.add(get_init(n, temp_list));
        }
        return final_str;
    }

    public static List<String> get_init(int n, List<position> temp_result){
        char[][] init = new char[n][n];
        for(int i = 0; i < n; i ++)
        {
            for(int j = 0; j < n; j ++)
            {
                init[i][j] = '.';
            }
        }

        for(position temp: temp_result)
        {
            init[temp.x][temp.y] = 'Q';
        }

        List<String> result = new ArrayList<>();
        for(int i = 0; i < n; i ++)
        {
            result.add(new String(init[i]));
        }
        return result;
    }

    public static void get_availible_pos(List<List<position>> final_result,List<position> temp_result,Set<Integer> Y, int rows, int remain_q,int last_y, int n)
    {
        if(remain_q == 0)
        {
            final_result.add(temp_result);
        }
        if(rows >= n)
        {
            return;
        }
        for(int i = 0; i < n; i ++)
        {
            if(!Y.contains(i) && (i < last_y - 1 || i > last_y + 1))
            {
                position temp_pos= new position(rows, i);
                List<position> cp_temp_result = new ArrayList<>(temp_result);
                cp_temp_result.add(temp_pos);
                Set<Integer> cp_Y = new HashSet<>(Y);
                cp_Y.add(i);
                get_availible_pos(final_result, cp_temp_result, cp_Y,rows+1, remain_q -1, i, n);
            }
        }
    }

    public static class position{
        public int x;
        public int y;
        position(int x, int y){
            this.x = x;
            this.y = y;
        };
    }
}
```

#### Expected behavior

In the N-Queen problem, when n = 5, the official solution is:
[["Q....","..Q..","....Q",".Q...","...Q."],["Q....","...Q.",".Q...","....Q","..Q.."],[".Q...","...Q.","Q....","..Q..","....Q"],[".Q...","....Q","..Q..","Q....","...Q."],["..Q..","Q....","...Q.",".Q...","....Q"],["..Q..","....Q",".Q...","...Q.","Q...."],["...Q.","Q....","..Q..","....Q",".Q..."],["...Q.",".Q...","....Q","..Q..","Q...."],["....Q",".Q...","...Q.","Q....","..Q.."],["....Q","..Q..","Q....","...Q.",".Q..."]]

My solution is:
[["Q....","..Q..","....Q",".Q...","...Q."],["Q....","...Q.",".Q...","....Q","..Q.."],[".Q...","...Q.","Q....","..Q..","....Q"],**[".Q...","...Q.","Q....","....Q","..Q.."]**,[".Q...","....Q","..Q..","Q....","...Q."],["..Q..","Q....","...Q.",".Q...","....Q"],["..Q..","Q....","....Q",".Q...","...Q."],["..Q..","....Q","Q....","...Q.",".Q..."],["..Q..","....Q",".Q...","...Q.","Q...."],["...Q.","Q....","..Q..","....Q",".Q..."],["...Q.",".Q...","....Q","Q....","..Q.."],["...Q.",".Q...","....Q","..Q..","Q...."],["....Q",".Q...","...Q.","Q....","..Q.."],["....Q","..Q..","Q....","...Q.",".Q..."]]

you can see the case [".Q...","...Q.","Q....","....Q","..Q.."] is missed in the official solution.

**Comment by nskybytskyi** [comment]
Thank you for reaching out to us. The expected answer is correct. I've visualized the supposedly missing placement:

```
5 .Q...
4 ...Q.
3 Q....
2 ....Q
1 ..Q..
  abcde
```

As you can see, queens on b5 and e2 attack each other diagonally, so the placement is invalid. Queens on a3 and c1 also attack each other diagonally.

We appreciate your time and support. If you have any further questions, please don't hesitate to let us know.

**Comment by zkeal** [comment]
thanks for your correction!
