### ISSUE TITLE
983 Minimum Cost For Tickets - Wrong casing in the method name

### ISSUE THREAD

**Issue by mnaoumov** [LeetCode-Feedback/LeetCode-Feedback#12617]
#### Your LeetCode username

mnaoumov

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Solution function name is `MincostTickets` (or similar, depending on the programming language)

However `Mincost` is not a well-known term to be one word and essentially there are two words `Min cost` and therefore the method name violates common naming style guides

#### Expected behavior

Method is renamed to `MinCostTickets`

**Comment by nskybytskyi** [comment]
Perhaps you should also file a report against [Mincost Ltd.](https://www.google.com/search?q=mincost+ltd)? 😂 

> violates common naming style guides

In all seriousness, LeetCode does not provide any guarantees regarding naming conventions, so this is not a bug. Sure, a linter warning about this method name is slightly unsettling. However, renaming a method will invalidate all previous submissions, so it is not a flawless decision either. In particular, if anyone tries to resubmit their past work, it will result in a more unsettling experience.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

This is not significant and updating the function signature is high-cost.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
