### ISSUE TITLE
Missing Test Case - 983. Minimum Cost For Tickets

### ISSUE THREAD

**Issue by nhalq** [LeetCode-Feedback/LeetCode-Feedback#12619]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
```
days = [1, 7]
costs = [3, 2, 1]
```
Expected: `1`
Output: `2`

#### Code you used for Submit/Run operation

```python3
class Solution:
    def mincostTickets(self, days: List[int], costs: List[int]) -> int:
        n = len(days)
        dp = [0] * n
        
        for i in range(n):
            dp[i] = (dp[i - 1] if i else 0) + min(costs)
            for j in range(i):
                if days[i] - days[j] < 7:
                    price = costs[1]
                elif days[i] - days[j] < 30:
                    price = costs[2]
                else:
                    continue
                dp[i] = min(dp[i], (dp[j - 1] if j else 0) + price)
        return dp[n - 1] 

```

#### Language used for code
Python3

#### Expected behavior

Expected: `1`

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
