### ISSUE TITLE
Missing Test Case - 447. Number of Boomerangs

### ISSUE THREAD

**Issue by bdpqchen** [LeetCode-Feedback/LeetCode-Feedback#12610]
#### Your LeetCode username

bdpqchen

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

we use `x * max(n) + y` to calculate unique key where `n` is the number of maximum position.
It both passed when we `* 1000` and `* 2000` in the below code, actually only `* 2000` should be passed.

#### Code you used for Submit/Run operation

```

class Solution {
public:
    int numberOfBoomerangs(vector<vector<int>>& points) {
        unordered_map<int, unordered_map<double, int>> mp;
        int n = points.size(), ans = 0;
        for (int i = 0; i < n; ++i) {
            const int key = points[i][0] * 1000 + points[i][1]; // there is the bug.
            for (int j = 0; j < n; ++j) {
                if (i == j)
                    continue;
                int x = points[i][0] - points[j][0],
                    y = points[i][1] - points[j][1];
                mp[key][sqrt(x * x + y * y)]++;
            }
        }
        for (auto &p : mp)
            for (auto &it : p.second)
                ans += it.second * (it.second - 1);
        return ans;
    }
};
```

#### Language used for code

C++

**Comment by nskybytskyi** [comment]
**Additional context**

Both of your values are way too small. You should calculate keys as `x * C + y` with `C > max(y) - min(y)` to guarantee that `key(x + 1, min(y)) = (x + 1) * C + min(y) > x * C + max(y) = key(x, max(y))`. Constraints `-10^4 <= y <=  10^4` imply `C > 20'000`. 

It is pointless to add a test case to WA one specific value of `C` such as `1'000` or `2'000` since users may change it to `1'001` or `1'999`, and it will pass. Only a test case that results in WA for all small values of `C` is valuable.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Please mention a missing test case explicitly.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by bdpqchen** [comment]
@LC-Pam 
There is one missing test case: [[-1000,-1],[-1,1000],[1,-1000]]. When I run my code, the result is 6, but the correct answer is 2. This discrepancy occurs because the key calculation produces duplicate results. Specifically, the key calculation for Point B yields 0 (key = -1 * 1000 + 1000 = 0), and the key calculation for Point C also yields 0 (key = 1 * 1000 + -1000 = 0). As a result, the duplicates in the key values lead to an incorrect count.
