### ISSUE TITLE
Wrong example in description : 983. Minimum Cost For Tickets

### ISSUE THREAD

**Issue by Ayan-10** [LeetCode-Feedback/LeetCode-Feedback#12620]
#### Your LeetCode username
AyanSarkar

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the problem description, the explanation of one example is wrong. 
```
Input: days = [1,4,6,7,8,20], costs = [2,7,15]
Output: 11
Explanation: For example, here is one way to buy passes that lets you travel your travel plan:
On day 1, you bought a 1-day pass for costs[0] = $2, which covered day 1.
On day 3, you bought a 7-day pass for costs[1] = $7, which covered days 3, 4, ..., 9.
On day 20, you bought a 1-day pass for costs[0] = $2, which covered day 20.
In total, you spent $11 and covered all the days of your travel.

```
Here on day 1, we can buy a 1-day pass and travel on day 1, here in the days array it says we want to travel on day 4, and as I don't have any pass now so I will buy a 7-day pass. I will buy a 7-day pass on day 4. But in the example's explanation, it's showing that on day 3 we are buying a pass, which is not right cause on day-3 I will not travel so why I will buy a pass on day 3? and if I buy a 7-day pass on day 4 I can travel 4,...,10 not 3,...,9.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior

The example explanation should be the below-mentioned one.

```
Input: days = [1,4,6,7,8,20], costs = [2,7,15]
Output: 11
Explanation: For example, here is one way to buy passes that lets you travel your travel plan:
On day 1, you bought a 1-day pass for costs[0] = $2, which covered day 1.
On day 4, you bought a 7-day pass for costs[1] = $7, which covered days 4,5, ..., 10.
On day 20, you bought a 1-day pass for costs[0] = $2, which covered day 20.
In total, you spent $11 and covered all the days of your travel.

```

**Comment by nskybytskyi** [comment]
Thank you for reaching out to us.

There is nothing wrong with the explanation. There may be multiple possible solutions with minimum cost. The explanation explicitly mentions this:

> Explanation: For example, here is **one** way to buy passes

The solution is equally good as long as the cost stays the same. The example explanation is intended to highlight this.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
