### ISSUE TITLE
Calculate Maximum Information Gain - Compile Error in Java code

### ISSUE THREAD

**Issue by qwazimoda** [LeetCode-Feedback/LeetCode-Feedback#1262]
#### Your LeetCode username
dyurchyk

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language

#### Description of the bug

It is impossible to submit a Java solution to the "Calculate Maximum Information Gain" question from the Decision Tree card due to the Compile Error in __Deserializer__. Other languages seems to be ok (checked JavaScript and Python3).

The compile error:
```
Line 33: error: cannot find symbol [in __Driver__.java] List<Double> param_1 = __Deserializer__.toDoubleList(line); ^ symbol: method toDoubleList(String) location: class __Deserializer__
```

#### Code you used for Submit/Run operation

```
class Solution {
    public double calculateMaxInfoGain(List<Double> petal_length, List<String> species) {
        // just the return statement was added to the default code
        return 0.0;
    }
}
```

#### Language used for code
Java

#### Expected behavior

An user should be able to run and submit a code and see the Expected answer.

#### Screenshots

![image](https://user-images.githubusercontent.com/19476580/96747143-ec460a00-1395-11eb-8089-fdd8aaeb49b7.png)

**Comment by lc-kay** [comment]
Hi @qwazimoda 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @qwazimoda 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
