### ISSUE TITLE
Missing Test Case - 20. Valid Parentheses

### ISSUE THREAD

**Issue by sumanbmondal** [LeetCode-Feedback/LeetCode-Feedback#12626]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The testcases do not check for "}" testcase.

#### Code you used for Submit/Run operation

```
// Valid Parentheses
class Solution {
public:
    bool isValid(string s) {
        stack<char> st;

        for (int i = 0; i < s.length() ; i++) {
            if (s[i] == '(' || s[i] == '[' || s[i] == '{') {
                st.push(s[i]);
            } else if (s[i] == ')') {
                if (!st.empty()) {
                    if (st.top() != '(') {
                        return false;
                    }
                    st.pop();
                } else {return false;}
            } else if (s[i] == ']') {
                if (!st.empty()) {
                    if (st.top() != '[') {
                        return false;
                    }
                    st.pop();
                } else {return false;}
            } else if (s[i] == '}') {
                if (!st.empty()) {
                    if (st.top() != '{') {
                        return false;
                    }
                    st.pop();
                }
            }
        }   
        return (st.empty());
    }    
};
```

#### Expected behavior
This solution does not check for the condition in which current parenthesis is "}" and the stack is empty, yet it gets accepted.

#### Screenshots
![image](https://user-images.githubusercontent.com/94859440/228223273-57eaf112-b786-47d7-9fa3-1d818f3d462e.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
