### ISSUE TITLE
Missing Test Case - 121. Best Time to Buy and Sell Stock

### ISSUE THREAD

**Issue by naveen2766** [LeetCode-Feedback/LeetCode-Feedback#12622]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution {
    public int maxProfit(int[] prices) {
     int profit=0;
     int least=prices[0];
     for(int i=1;i<prices.length;i++){
         if(prices[i]<least){
             least=prices[i];
         }
         if(prices[i]-least>profit)
              profit=prices[i]-least;
     }
     return profit;   
    }
}
```

**Comment by nskybytskyi** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
