### ISSUE TITLE
1501. Countries You Can Safely Invest In

### ISSUE THREAD

**Issue by Budong-jiuwen** [LeetCode-Feedback/LeetCode-Feedback#12635]
#### Your LeetCode username

Budongjiuwen

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

No matter what the query is input, the test result returns as `Phone number of the person with id = 3 doesn't exist in the Country table.`  `Submit` is fine, but test run is not.

#### Code you used for Submit/Run operation

```
WITH cte AS (
    SELECT  caller_id AS id,
            duration
    FROM Calls
    UNION ALL
    SELECT  callee_id AS id,
            duration
    FROM Calls
), cte2 AS (
    SELECT  SUBSTR(phone_number,1,3) AS country_code    ,
            AVG(duration) AS avg_duration
    FROM cte JOIN Person USING(id)
    GROUP BY 1
)

SELECT  name
FROM cte2 JOIN Country USING(country_code)
WHERE avg_duration > (SELECT AVG(duration) FROM cte)
```

#### Language used for code

MySQL

#### Expected behavior

Test run works.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
