### ISSUE TITLE
A Follow-up Should be Added - 2597. The Number of Beautiful Subsets

### ISSUE THREAD

**Issue by shit-eater** [LeetCode-Feedback/LeetCode-Feedback#12631]
Your LeetCode username
v5qYY4Q65w

Category of the bug
- [√] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

Description of the bug
The expected solution of this problem must be using DP. But the user who uses backtracking can get accepted because of the terrible  constraints. If the brute force can be accepted, the difficulty of should be changed to 'Easy'. Otherwise you can either increase the constraints of n from 20 to 10^5 or add a follow-up requirement: can you solve this problem in O(nlogn) time complexity?
It is not suitable to increase the constraints of n in consideration of the virtual contest, so the best way is changing the difficulty and adding a follow-up requirement.

Code you used for Submit/Run operation

The code below is using backtracking, with O(2^n) time complexity.
```
class Solution:
    def beautifulSubsets(self, nums: List[int], k: int) -> int:
        
        used = defaultdict(int)
        ans = 0
        nums.sort()
        
        def dfs(p):
            nonlocal ans
            if p==len(nums):
                ans+=1
                return
            dfs(p+1)
            if used[nums[p]-k]==0:
                used[nums[p]]+=1
                dfs(p+1)
                used[nums[p]]-=1
        
        dfs(0)
        return ans-1
```

The code below is using dynamic programming, with O(nlogn) time complexity.
```
class Solution:
    def beautifulSubsets(self, nums: List[int], k: int) -> int:
        groups = defaultdict(Counter)
        for x in nums:
            groups[x % k][x] += 1
        ans = 1
        for cnt in groups.values():
            g = sorted(cnt.items())
            m = len(g)
            f = [0] * (m + 1)
            f[0] = 1
            f[1] = 1 << g[0][1]
            for i in range(1, m):
                if g[i][0] - g[i - 1][0] == k:
                    f[i + 1] = f[i] + f[i - 1] * ((1 << g[i][1]) - 1)
                else:
                    f[i + 1] = f[i] << g[i][1]
            ans *= f[m]
        return ans - 1 
```

Language used for code
Python3

Expected behavior
1. The difficulty of this problem should be changed to 'Easy'.
2. A follow-up requirement should be added: Can you find a solution with O(nlogn) time complexity?

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
