### ISSUE TITLE
595. Big Countries - Wrong datatype

### ISSUE THREAD

**Issue by mnaoumov** [LeetCode-Feedback/LeetCode-Feedback#12636]
#### Your LeetCode username

mnaoumov

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

According to the SQL Schema: `gdp` column has type `int`

However all rows from Example 1 test case have `gdp` value that exceeds `int` maximum value, which causes `Arithmetic overflow error converting expression to data type int`

#### Expected behavior

`gdp` column has type `bigint` in SQL Schema

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
