### ISSUE TITLE
UI Bug

### ISSUE THREAD

**Issue by l00jj** [LeetCode-Feedback/LeetCode-Feedback#12642]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
l00

**Bug 类型**
UI前端交互问题

**描述**
提交完代码后，左侧会有一个“查看示例代码”，点击会有一个弹出的窗体，笔记本或屏幕高度较小设备会出现这个窗体内的取消按钮看不到导致无法关闭这个窗体

**期望行为**
修复这个Bug

**屏幕截图**
<img width="389" alt="image" src="https://user-images.githubusercontent.com/25047890/228538589-2107f5f7-a918-4e7a-874f-c41ba87c0ad1.png">

<img width="580" alt="image" src="https://user-images.githubusercontent.com/25047890/228538518-9c8c09a6-99d8-4352-b960-8804239a48fa.png">

**Comment by feiceh** [comment]
Hello～感谢反馈，这个问题将会提交至负责团队尽快复现并排查定位的。Github 仓库只用于反馈大家在本站学习过程中遇到的题目和题解问题，目前我们会暂时关闭该 issue，如有更多反馈和建议欢迎  [点击这里](https://support.leetcode.cn/hc/request/new/) 提交工单反馈，给您带来的不便敬请谅解。

**Comment by feiceh** [comment]
你好，当前已修复～

**Comment by l00jj** [comment]
> 你好，当前已修复～

好

**Comment by l00jj** [comment]
> 你好，当前已修复～

请问什么时候实装的？目前还是看不到按钮
