### ISSUE TITLE
Missing Test Case - 87. Scramble String

### ISSUE THREAD

**Issue by zitudu** [LeetCode-Feedback/LeetCode-Feedback#12646]
#### Your LeetCode username
zqfxxx

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

`isScramble(a,b)` should be equal to `isScramble(b,a)`. The payload below passed test case 1 but didn't pass test case 2.

Test case 1:
```
"ccababcaabcb"
"bccbccaaabab"
```

Test case 2:
```
"bccbccaaabab"
"ccababcaabcb"
```

#### Code you used for Submit/Run operation

```c++
class Solution {
public:
    bool isScramble(string s1, string s2) {
        if(s1==s2) return true;
        int n=s1.size();
        int sum1=0,sum2=0;
        int i1=-1,i2=-1;
        for(int i=0;i<n-1;i++){
            sum1+=s1[i]*s1[i]-s2[i]*s2[i];
            sum2+=s1[i]*s1[i]-s2[n-1-i]*s2[n-1-i];
            if(sum1==0)i1=i;
            if(sum2==0)i2=i;
        }
        if(i1>=0) if(isScramble(s1.substr(0,i1+1),s2.substr(0,i1+1))&&isScramble(s1.substr(i1+1,n-i1-1),s2.substr(i1+1,n-i1-1))) return true;
        if(i2>=0) if(isScramble(s1.substr(0,i2+1),s2.substr(n-1-i2,i2+1))&&isScramble(s1.substr(i2+1,n-i2-1),s2.substr(0,n-i2-1))) return true;
        return false;
    }
};
```

#### Language used for code
C++

#### Expected behavior

This payload should fail with "wrong answer".

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
