### ISSUE TITLE
Missing Test Case - 1637. Widest Vertical Area Between Two Points Containing No Points

### ISSUE THREAD

**Issue by Loganable** [LeetCode-Feedback/LeetCode-Feedback#12647]
#### Your LeetCode username
logan-32

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My code should not be acceptable, but it can be submitted successfully.  
[[1,7],[5,9],[3,4],[7,7]] This is the test case I provided myself, and the code below would fail on this one.

#### Code you used for Submit/Run operation

```
// Widest Vertical Area Between Two Points Containing No Points
class Solution:
    def maxWidthOfVerticalArea(self, points: List[List[int]]) -> int:
        x_l = [x for x, y in points]
        n, x_min, x_max = len(points), min(x_l), max(x_l)
        d = x_max - x_min
        if d == 0:
            return 0
        p_l = [[x_max, -1] for _ in range(n)]
        for x in x_l:
            b = p_l[(x - x_min) * (n - 1) // d]
            b[0] = min(x, b[0])
            b[1] = max(x, b[1])
        res, pre = 1, p_l[0][1]
        for i, (p_min, p_max) in enumerate(p_l):
            if p_max != -1:
                if p_l[i - 1][1] == -1:
                    res = max(res, p_min - pre)
                pre = p_max
        return res
```

#### Language used for code
Python 

#### Expected behavior
Leetcode should cover a test case where the x coordinates of every point which are sorted is an arithmetic sequence.

**Comment by Loganable** [comment]
Missing Test Cases

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
