### ISSUE TITLE
277. Find the Celebrity - missing test case

### ISSUE THREAD

**Issue by qwazimoda** [LeetCode-Feedback/LeetCode-Feedback#1264]
#### Your LeetCode username

dyurchyk

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

There is only single test case, which checks that everyone knows the picked celebrity candidate ([[1,1],[1,1]]). The easy workaround for this test case is a special check for n=2 case.
F.e. in Java:  if (n == 2 && !knows(0, 1) && !knows(1, 0)) return -1;
In result wrong solutions are accepted.

Examples of test cases (n=4, n=3):
[[1,0,0,0],[0,1,1,0],[1,1,1,1],[0,1,1,1]]
[[1,0,0],[1,1,0],[0,1,1]]

#### Code you used for Submit/Run operation

```
public class Solution extends Relation {
    public int findCelebrity(int n) {
        if (n == 2 && !knows(0, 1) && !knows(1, 0))
            return -1;
        
        int j = 0;
        for(int i = 0; i < n; i++)
            if(knows(j, i))
                j = i;
        
        for(int i = 0; i < j; i++){
            if(knows(j, i)) 
                return -1;
        }
            
        return j;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Solutions, which do not verify that everybody knows the celebrity candidate, should be caught by test cases.

#### Screenshots

![image](https://user-images.githubusercontent.com/19476580/96895852-e1a17880-145a-11eb-9c89-0ea8033c5b3d.png)

#### Additional context

Examples of test cases (n=4, n=3):
[[1,0,0,0],[0,1,1,0],[1,1,1,1],[0,1,1,1]]
[[1,0,0],[1,1,0],[0,1,1]]

Personally, I believe that at least two test cases should be added, since it would be easy to workaround a single case without really getting a solution.

**Comment by lc-kay** [comment]
Hi @qwazimoda 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @qwazimoda 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
