### ISSUE TITLE
Missing Test Case - 187. Repeated DNA Sequences

### ISSUE THREAD

**Issue by ValeraT1982** [LeetCode-Feedback/LeetCode-Feedback#12640]
#### Your LeetCode username
[tereschenkovv](https://leetcode.com/tereschenkovv/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
I think repeated sequences should not overlap so AAAAAAAAAAA should return an empty array

#### Code you used for Submit/Run operation

```
/**
 * @param {string} s
 * @return {string[]}
 */
var findRepeatedDnaSequences = function(s) {
    let store = new Set(), result = new Set()
    for(let i = 0; i < s.length - 9; i++) {
        const str = s.substring(i, i + 10)
        if(store.has(str)) {
            result.add(str)
        } else {
            store.add(str)
        }
    }
    return Array.from(result)
};
```

#### Language used for code
JavaScript

#### Expected behavior
Empty array

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!!
