### ISSUE TITLE
Improved solution - 651. 4 Keys Keyboard

### ISSUE THREAD

**Issue by przemek3d88** [LeetCode-Feedback/LeetCode-Feedback#12644]
#### Your LeetCode username
przemysaw2

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
This is not really an issue. You can improve this solution to use O(1) space, as you need only the constant number of keys.

#### Code you used for Submit/Run operation
The below implementation is slow and uses more memory in practice, but it demonstrates the idea. You can achieve the similar result by manipulating the array of the const size.

```
class Solution {
    map<int,int> dp;
    
    int go(int n) {
        if(n <= 0) {
            return 0;
        }
        
        auto it = dp.find(n);
        if(it != dp.end()) {
            return it->second;
        }
        
        // clean unused keys
        vector<int> keysToRemove;
        for(const auto &[k,v] : dp) {
            if(k >= n-6) {
                break;
            }
            
            keysToRemove.push_back(k);
        }
        
        for(int k : keysToRemove) {
            dp.erase(k);
        }
        
        // init the state
        dp[n] = n;
        // try the improved sequence
        for(int i = 2; i < 6; i++) {
            dp[n] = max(dp[n], i*go(n-i-1));
        }
        
        return dp[n];
    }

public:
    int maxA(int n) {
        // observation 1: it is profitable to press single A only at the beginning
        // it is not profitable to press ctrl+V more than 4 times in a row
        
        // we can do a dp in O(n) time and O(1) space
        return go(n);
    }
};
```

#### Language used for code
C++

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've submitted your feedback to the team. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
