### ISSUE TITLE
Missing Test Case - 81. Search in Rotated Sorted Array II

### ISSUE THREAD

**Issue by Panja-Abhilash** [LeetCode-Feedback/LeetCode-Feedback#12645]
class Solution {
	  boolean search(int [] a,int target) {
		int pivot=PivotForDuplicates( a);
		boolean temp=BinarySearch( a,target,0,pivot);
		if(temp!=false) {
			return true;
		}
		return BinarySearch( a,target,pivot+1,a.length-1);
	}
	 int PivotForDuplicates(int [] a) {
		int start=0;
		int end =a.length-1;
		while(start<=end) {
			int mid=start+(end-start)/2;
			if(mid-1 > start && a[mid]<a[mid-1]) {
				return mid-1;
			}
			if(mid+1 < a.length && a[mid]>a[mid+1]) {
				return mid;
			}
			if(a[start]==a[mid]&&a[end]==a[mid]) {
				if( start+1<a.length && a[start]>a[start+1] ) {
					return start;
				}
				start++;
				if(  end-1 >start && a[end]<a[end-1] ) {
					return end-1;
				}
				end--;
			}
			else if(a[start]<a[mid] || (a[start]==a[mid] && a[mid]>a[end]))
			//above condition will provide the our pivot element will be lieying 
			//in the rigth side why we are taking the a[start]==a[mid] it may be  
			//  the chance to have start element and end element may be equal bcz
			//we consists duplicates in the array
				
			{
				start=mid+1;
			}
			else {
				end=mid-1;
			}
		}
		return -1;
	}
	 boolean BinarySearch(int [] a,int target,int start,int end) {
		while(start<=end) {
			int mid=start+(end-start)/2;
			if(target>a[mid]) {
				start=mid+1;
			}
			else if(target < a[mid]) {
				end=mid-1;
			}
			else {
			return true;
			}
		}
		return false;
	}
}

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
