### ISSUE TITLE
10. Regular Expression Matching - Code can't be run against one of submission test cases

### ISSUE THREAD

**Issue by qwazimoda** [LeetCode-Feedback/LeetCode-Feedback#1265]
#### Your LeetCode username

dyurchyk

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Recently new test case was added: s = "aa", p = "\*a".
The code can't be run against it, since it is blocked by the "Invalid Testcase" message (no actual message).
Also the expected behavior is unclear from the provided description, since the preceding element is not defined is the test case. Should the asterisk symbol be ignored in such case? Or should false be returned for the invalid input?
Description: '*' Matches zero or more of the preceding element

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean isMatch(String s, String p) {
        return false;
    }
}
```
```
var isMatch = function(s, p) {
    return false;
};
```

#### Language used for code

Java, JavaScript

#### Expected behavior

A code should be runnable against test cases used in the submission
Additionally, it would be nice to clarify the expected behavior in the description, if the used test case is valid.

#### Screenshots

![image](https://user-images.githubusercontent.com/19476580/96902246-49a78d00-1462-11eb-8737-a889dc642609.png)
![image](https://user-images.githubusercontent.com/19476580/96902555-aa36ca00-1462-11eb-879a-ff992bd0d8d3.png)

#### Additional context

The problem is reproducible for multiply languages (Java, JS, C++, Python3).

Test case:
"aa"
"*a"

**Comment by lc-kay** [comment]
Hi @qwazimoda 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@qwazimoda We've removed this test case and fixed the validation code. We have also added another constraint to make sure the input is clear. Thank you for your time and support!
