### ISSUE TITLE
Missing Test Case - 2474. Customers With Strictly Increasing Purchases

### ISSUE THREAD

**Issue by yiyumin** [LeetCode-Feedback/LeetCode-Feedback#12659]
#### Your LeetCode username
whatdoyumin

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
The explanation in Example 1 - Customer 3 is incorrect. It is a copy/paste from Customer 1. It should instead be similar to the first half of the explanation for Customer 2.

It should be changed from:

> We can see that the total purchases are strictly increasing yearly, so we include customer 1 in the answer.

to:

> We do not include customer 3 in the answer because the total purchases are not strictly increasing.

#### Code you used for Submit/Run operation
N/A

#### Language used for code
N/A

#### Expected behavior
The explanation for Customer 3 should be updated.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
