### ISSUE TITLE
Typos in Recursion II explore

### ISSUE THREAD

**Issue by naphtul** [LeetCode-Feedback/LeetCode-Feedback#12658]
#### Your LeetCode username
naphtul

#### Category of the bug
- [ ] Question
- [ ] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug
There's a typo in the Explore card: https://leetcode.com/explore/learn/card/recursion-ii/507/beyond-recursion/2898/
Divde instead of Divide
atttempts instead of attempts

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
