### ISSUE TITLE
Missing Test Case - 87. Scramble String

### ISSUE THREAD

**Issue by Arvind-kumar-M-08** [LeetCode-Feedback/LeetCode-Feedback#12660]
#### Your LeetCode username

[enthusisiastic](https://leetcode.com/enthusisiastic/)
[200020008](https://leetcode.com/200020008/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My code implements the following. Making a split when frequency of each character matches from beginning or end or both. If these splits can be scrambled, code  is returning true. Other splits are not considered (i.e. return false if the splits are not scrambled). The following test case illustrates the gap in the accepted code.

#### Code you used for Submit/Run operation

Link to the solution : https://leetcode.com/problems/scramble-string/submissions/924717424/

```
class Solution {
public:
    bool isFinal(string &s1, string &s2, int i1, int i2, int i){
        vector<int> v1(26,0), v2(26,0);
        for(int j = 0; j <= i; j++){
            v1[s1[i1-j]-'a']++;
            v2[s2[j+i2]-'a']++;
        }
        return v1 == v2;
    }

    bool isStart(string &s1, string &s2, int i1, int i2, int i){
        vector<int> v1(26,0), v2(26,0);
        for(int j = 0; j <= i; j++){
            v1[s1[j+i1]-'a']++;
            v2[s2[j+i2]-'a']++;
        }
        return v1 == v2;
    }
    bool rec(string &s1, string &s2, int i1, int i2, int l){
        if(l <= 0) return true;
        if(l == 1) return s1[i1] == s2[i2];
        bool found = false;
        bool ret = false;
        for(int i = 0; i < l-1; i++){
            if(isStart(s1, s2, i1, i2, i)){
                found = true;
                ret =  rec(s1, s2, i1, i2, i+1) && rec(s1, s2, i1+i+1, i2+i+1, l-i-1);
            }
            if(isFinal(s1, s2, i1+l-1, i2, i)){
                found = true;
                ret |= rec(s1, s2, i1+l-i-1, i2, i+1) && rec(s1, s2, i1, i2+i+1, l-i-1);
            }
            if(found) return ret;
        }
        return false;
    }   

    bool isScramble(string s1, string s2) {
        return rec(s1, s2, 0, 0, s1.length());
    }
};
```

#### Language used for code
C++ 

#### Expected behavior

s1 = "xyzabcdecaebd"
s2 = "abcdexyzcaebd"

We can scramble s1 to s2 by
xyzabcdecaebd -> xyzabcde / caebd
xyzabcde / caebd -> xyz / abcde / caebd
xyz / abcde / caebd -> abcde / xyz / caebd -> abcdexyzcaebd -> s2

But the above solution is passing all the given test cases, fails for this one.

#### Screenshots

![image](https://user-images.githubusercontent.com/92923309/228954875-144b60ec-3cc8-4132-a78a-bdaeff99169f.png)
![image](https://user-images.githubusercontent.com/92923309/228954672-fede6e29-92de-4728-bf57-4e54d8c95e6b.png)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. ([enthusisiastic](https://leetcode.com/enthusisiastic/)

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
