### ISSUE TITLE
Missing Test Case - 205. Isomorphic Strings

### ISSUE THREAD

**Issue by Daw1dNH** [LeetCode-Feedback/LeetCode-Feedback#12661]
#### Your LeetCode username

Daw1dNH

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Current test cases allow the situation where two different letters of the first argument points to the same letter in the second argument.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    fun isIsomorphic(s: String, t: String): Boolean {
        var lettersMap = hashMapOf<Char, Char>()
        for(l in s.indices) {
            if (lettersMap.containsKey(s[l])) {
                if (lettersMap.get(s[l]) != t[l]) return false
            } else {
                lettersMap.put(s[l], t[l])
            }
        }
        return true
    }
}
```

#### Expected behavior

s = bar, t = foo should return false
Code used for Submit is allowed by current suite of tests although it doesn't handle this case.
proper check should be added to code to handle this.
e.g. ```if (lettersMap.containsValue(t[l])) return false``` in "else" block

#### Additional context

proposed test case to check this behavior is:
s = bar, t = foo

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
