### ISSUE TITLE
Missing Test Case - 剑指 Offer II 009. 乘积小于 K 的子数组

### ISSUE THREAD

**Issue by opqqqq** [LeetCode-Feedback/LeetCode-Feedback#12667]
#### Your LeetCode username

清风明月

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [] Missing Test Cases 

#### Description of the bug

缺少测试用例 例如当nums=[10,5,101,6]，k=100时 我的代码测试结果为5，实际结果为4

#### Code you used for Submit/Run operation

```
// Two Sum
public class 乘积小于K的子数组 {
    public static int numSubarrayProductLessThanK(int[] nums, int k) {
        if (k<=1) return 0;
        int i = 0;
        int res = 0;
        int tmpMulRes = 1;
//        双指针
        for (int j = 0; j < nums.length; j++) {
//            记录当前窗口的值
            tmpMulRes *= nums[j];
//            需要更新窗口的情况，将i向右滑动直到找到一个窗口的乘积比k小
            while (i < j && tmpMulRes >= k) {
                tmpMulRes /= nums[i];
                i++;
            }
            res += j - i + 1;

        }
        return res;
    }

    public static void main(String[] args) {
        System.out.println(numSubarrayProductLessThanK(new int[]{10, 5, 101, 6}, 100));
    }
}
```

#### Language used for code

java

#### Expected behavior

   这是正确的代码语句 while (i <= j && tmpMulRes >= k) 
提交的代码是 while (i < j && tmpMulRes >= k) 

#### Screenshots

![image](https://user-images.githubusercontent.com/48823405/229041838-5a7d8d3f-b4d5-416d-84d8-a47700f3884f.png)
![image](https://user-images.githubusercontent.com/48823405/229041885-011baa05-00e0-4072-91f1-4e9649ce7fcb.png)

**Comment by feiceh** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励哦。

**Comment by opqqqq** [comment]
这是我的个性域名 qing-feng-ming-yue-21

**Comment by feiceh** [comment]
积分奖励已发放，请查收。
