### ISSUE TITLE
Missing Testcase in Maximal Rectangle problem

### ISSUE THREAD

**Issue by Swapnil-2001** [LeetCode-Feedback/LeetCode-Feedback#1266]
#### Your LeetCode username
Swap24

#### Category of the bug
 Missing testcase

#### Description of the bug
An incorrect submission results in "Success" due to a missing testcase.

#### Code you used for Submit/Run operation

```
class Solution:
    def maximalRectangle(self, matrix: List[List[str]]) -> int:
        if not matrix:
            return 0
        m, n = len(matrix), len(matrix[0])
        
        matrix[0] = [int(matrix[0][j]) for j in range(n)]
        for i in range(1, m):
            for j in range(n):
                matrix[i][j] = int(matrix[i][j])
                if matrix[i][j]:
                    matrix[i][j] = matrix[i - 1][j] + 1

        def calculatePrev(arr):
            prev = [-1 for i in range(n)]
            stack = [(arr[0], 0)]
            for i in range(1, n):
                while stack and stack[-1][0] >= arr[i]:
                    stack.pop()
                if stack:
                    prev[i] = stack[-1][1]
                stack.append((arr[i], i))
            return prev
        
        def calculateNext(arr):
            after = [(n - 1) for i in range(n)]
            stack = []
            for i in range(n):
                while stack and stack[-1][0] > arr[i]:
                    after[stack[-1][1]] = i
                    stack.pop()
                stack.append((arr[i], i))
            after[-1] = n
            return after
        
        res = float('-inf')
        for i in range(m):
            prev, after = calculatePrev(matrix[i]), calculateNext(matrix[i])
            for j in range(n):
                res = max(res, matrix[i][j] * (j - prev[j] + after[j] - j - 1))
        
        return res
```

#### Language used for code
Python 3

#### Expected behavior
 The solution was not supposed to have cleared all testcases.

#### Screenshots

![Maximal Rectangle - LeetCode - Google Chrome 23-10-2020 17_31_12](https://user-images.githubusercontent.com/53232360/97001731-7dfc7580-1556-11eb-8c5f-ad8ecca3c6e5.png)

#### Additional context

A test case that could be used is: 
[["0","0","1"],["1","1","1"]]

**Comment by lc-kay** [comment]
Hi @Swapnil-2001 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Swapnil-2001 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
