### ISSUE TITLE
1444. Number of Ways of Cutting a Pizza

### ISSUE THREAD

**Issue by martin0327** [LeetCode-Feedback/LeetCode-Feedback#12663]
#### Your LeetCode username

martin0327

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The following code sets the base case to be 1 regardless of its feasibility.
There is no TC that checks the feasibility of the base case.

#### Code you used for Submit/Run operation

```
using ll = long long;
const ll mod = 1e9+7;

class Solution {
public:
  ll suf[51][51];
  ll dp[11][50][50];
  int ways(vector<string>& a, int k) {
    int n = a.size(), m = a[0].size();    
    for (int i=n-1; i>=0; i--) {
      for (int j=m-1; j>=0; j--) {
        suf[i][j] = (a[i][j]=='A') + suf[i][j+1] + suf[i+1][j] - suf[i+1][j+1];
      }
    }    
    dp[0][0][0] = 1;
    for (int l=0; l<k-1; l++) {
      for (int i=0; i<n; i++) {
        for (int j=0; j<m; j++) {
          for (int ni=i+1; ni<n; ni++) {
            if ((suf[ni][j] >= k-l-1) && (suf[i][j] - suf[ni][j] > 0)) {
              dp[l+1][ni][j] += dp[l][i][j];
              dp[l+1][ni][j] %= mod;
            }
          }
          for (int nj=j+1; nj<m; nj++) {
            if ((suf[i][nj] >= k-l-1) && (suf[i][j] - suf[i][nj] > 0)) {
              dp[l+1][i][nj] += dp[l][i][j];
              dp[l+1][i][nj] %= mod;
            }
          }
        }
      }
    }
    ll ans = 0;
    for (int i=0; i<n; i++) {
      for (int j=0; j<m; j++) {
        ans += dp[k-1][i][j];
        ans %= mod;
      }
    }     
    return ans;
  }
};
```

#### Language used for code

C++

#### Expected behavior

It is not supposed be accepted.

#### Additional context

https://leetcode.com/submissions/detail/925141877/
is the accepted submission, and

["...","...","..."]
1
is the TC that ensures the above code gets WA.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
