### ISSUE TITLE
Missing Test Case - 100. Same Tree

### ISSUE THREAD

**Issue by Hemanthburra** [LeetCode-Feedback/LeetCode-Feedback#12677]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int flag = 0;
    void fun(TreeNode* r1,TreeNode* r2){
        if (r1==NULL and r2!=NULL) flag = 1 ;
        if (r1!=NULL and r2 == NULL) flag = 1;
        if (r1 == NULL or r2 == NULL) return;
        if (r1->val != r2->val) flag = 1;
        fun(r1->left,r2->left);
        fun(r2->right,r2->right);
    }
    bool isSameTree(TreeNode* p, TreeNode* q) {
        //if (!p && q || !q && p) return false;
        fun(p,q);
        if (flag == 0) return 1;
        else return 0;
    }
};
```

#### Expected behavior

[177,null,140,null,182,null,83] --> p
[177] -->q
expected  == false
but while writing the code this testcase is not there so it is accepted the wrong solution -->ACCEPTED

#### Screenshots

![image](https://user-images.githubusercontent.com/102217798/229199902-636a93fd-0fad-4050-951b-8422964d8f31.png)
this case is gone wrong for this solution but same code is accepted.

**Comment by Hemanthburra** [comment]
[177,null,140,null,182,null,83]-->p
[177]--->q
add this missing test case to the problem

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
