### ISSUE TITLE
代码编辑区域光标会漂移

### ISSUE THREAD

**Issue by Goooooooooooooooogle** [LeetCode-Feedback/LeetCode-Feedback#12673]
![image](https://user-images.githubusercontent.com/50075902/229138451-e66747dc-758c-4fad-9db4-0131b605774b.png)
实际上line1的光标在 '{'旁边，显示却在几个空格后面，影响使用。

**Comment by feiceh** [comment]
Hello～感谢反馈，这个问题将会提交至负责团队尽快复现并排查定位的。Github 仓库只用于反馈大家在本站学习过程中遇到的题目和题解问题，目前我们会暂时关闭该 issue，如有更多反馈和建议欢迎  [点击这里](https://support.leetcode.cn/hc/request/new/) 提交工单反馈，给您带来的不便敬请谅解。
