### ISSUE TITLE
Typos in Decision Tree Explore card intro

### ISSUE THREAD

**Issue by naphtul** [LeetCode-Feedback/LeetCode-Feedback#12672]
#### Your LeetCode username
naphtul

#### Category of the bug
- [ ] Question
- [ ] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the decision tree intro explore card: https://leetcode.com/explore/learn/card/decision-tree/

- "for the classification of problems" instead of "for the classification problems"
- "We'll do our best to respond to you" instead of "We'll do our best to response to you"

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
