### ISSUE TITLE
Improper Hidden Hint - 2599. Make the Prefix Sum Non-negative

### ISSUE THREAD

**Issue by shit-eater** [LeetCode-Feedback/LeetCode-Feedback#12670]
Your LeetCode username
v5qYY4Q65w

Category of the bug
- [√] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

Description of the bug
The solution of the problem is using priority queue. But the hint of this problem seems to try to lead the user to WA.
![add78f7a1940020232883b2b195bb8c](https://user-images.githubusercontent.com/73991126/229104745-ce7013c5-ba40-44e8-9012-7306bef9daad.png)
Many users may try solving this problem with a greedy but wrong strategy,  which is putting the current element to the end of the array when the prefix sum is negative. However, the hint can support this wrong solution.

Code you used for Submit/Run operation

The expected solution:
```
class Solution:
    def makePrefSumNonNegative(self, nums: List[int]) -> int:

        # if sum(nums)<0: return -1 
        heap = []
        pre = 0
        ans = 0
        for num in nums:
            pre+=num
            heapq.heappush(heap,num) 
            if pre<0: 
                pre-=heapq.heappop(heap)
                ans+=1
        return ans
```

Wrong solution which is same as the hint but will get WA:
```
class Solution:
    def makePrefSumNonNegative(self, nums: List[int]) -> int:

        pre = 0
        ans = 0
        for num in nums:
            if pre+num>=0:
                pre+=num
            else:
                ans+=1
        return ans
```

Language used for code
Python3

Expected behavior
The 2nd hint should be changed:
Loop over the array keeping the prefix sum. Whenever it goes negative, move the smallest number you have seen to the end.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
