### ISSUE TITLE
Needless repetition in explore card

### ISSUE THREAD

**Issue by naphtul** [LeetCode-Feedback/LeetCode-Feedback#12671]
#### Your LeetCode username
naphtul

#### Category of the bug
- [ ] Question
- [ ] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug
In Explore Card Track, Explore Card Layers: https://leetcode.com/explore/featured/card/the-leetcode-beginners-guide/679/sql-syntax/4358/
the 3rd and 4th points are the same:

> 3. Third and Fourth Layers: Recursion II, Dynamic Programming, and Graph
> 4. Third and Fourth Layers: Recursion II, Dynamic Programming, and Graph

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
