### ISSUE TITLE
Testcase grades incorrectly on 29. Divide Two Integers

### ISSUE THREAD

**Issue by codex-scribe** [LeetCode-Feedback/LeetCode-Feedback#12682]
#### Category of the bug
- [ ] Question
- [ x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

One of the testcases has the wrong expected output for this question.  The problem asks us to correctly perform numerical division on a given dividend and divisor.  In one of the test cases, the divided is -2147483648 and the divisor is -1.  This should yield a quotient of 2147483648, which my answer output, but the expected result is 2147483647.  This is the only test case I missed, so I believe I should have my submission marked as correct if possible, and the test case should be fixed.

#### Code you used for Submit/Run operation

```
var divide = function(dividend, divisor) {
        let absDividend = Math.abs(dividend)
    let absDivisor = Math.abs(divisor)
    let quotient = [];
    let dividendArray = absDividend.toString().split('');
    let firstSubDividend = dividendArray.splice(0,absDivisor.toString().length).join('')

    const divisionStep = (subDividend) => {
        let runningSum = 0;
        for (let i = 0; i<10; i++) {
            if (runningSum + absDivisor <= subDividend) {
                runningSum += absDivisor
                continue;
            }
            quotient.push(i);
            break;
        }
        if (dividendArray.length !== 0) {
            let difference = subDividend - runningSum;
            let nextSubDividend = difference.toString().concat(dividendArray.shift().toString())
            divisionStep(nextSubDividend)
        }
    }
    divisionStep(firstSubDividend)

    let final = quotient.join('')
    if (Math.sign(dividend) === Math.sign(divisor)) {
        return final
    }
    else {
        return final*-1
    }
};
```

#### Language used for code

Javascript

#### Screenshots

![image](https://user-images.githubusercontent.com/118865356/229266991-e1584567-bf1e-46b7-bcc4-1bf52ba6810f.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
