### ISSUE TITLE
831. 隐藏个人信息：题目示例文本错误

### ISSUE THREAD

**Issue by JavanShen** [LeetCode-Feedback/LeetCode-Feedback#12683]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
盐

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
题目示例 4 有文本错误

**你使用的语言**
TypeScript

**期望行为**
修改文本为 `隐藏后的电话号码应该是 "+**-***-***-5678"`

**屏幕截图**
![image](https://user-images.githubusercontent.com/53335668/229267542-25cabd26-7313-4b17-b545-becbfd2367f3.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励哦。

**Comment by JavanShen** [comment]
> 你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励哦。


leetcode.cn/u/dogpaw/

**Comment by feiceh** [comment]
好的，已奖励积分。
