### ISSUE TITLE
Missing Test Case - 226. Invert Binary Tree

### ISSUE THREAD

**Issue by Mahmoud-AbouDeghedy** [LeetCode-Feedback/LeetCode-Feedback#12681]
#### Your LeetCode username

Deghedy

#### Category of the bug
 Missing Test Cases 

#### Description of the bug

I think here the test case of a single node tree is missing as it would result in a segmentation fault error for this code for example:
```c++
    TreeNode* invertTree(TreeNode* root) {
        if(root==NULL)
            return NULL;
        
            TreeNode* tmp=root->left;
            root->left=root->right;
            root->right=tmp;
            invertTree(root->left);
            invertTree(root->right);
        return root;
    }
```
but it didn't and get accepted normally!
#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
        if(root==NULL)
            return NULL;
        
            TreeNode* tmp=root->left;
            root->left=root->right;
            root->right=tmp;
            invertTree(root->left);
            invertTree(root->right);
        return root;
    }
};
```

#### Expected behavior

I think here the test case of a single node tree is missing as it would result in a segmentation fault error for this code ,but it got accepted!

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Mahmoud-AbouDeghedy** [comment]
C++

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code AC submission link since we received Compile Error on the above code: https://leetcode.com/submissions/detail/927410705/

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
