### ISSUE TITLE
13. Roman to Integer -> Substraction part details of the question needs to be corrected

### ISSUE THREAD

**Issue by devilsuse** [LeetCode-Feedback/LeetCode-Feedback#1268]
#### Your LeetCode username

techieme

#### Category of the bug
- [X ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Question description says:
There are **six instances** where subtraction is used:

I can be placed before V (5) and X (10) to make 4 and 9. 
X can be placed before L (50) and C (100) to make 40 and 90. 
C can be placed before D (500) and M (1000) to make 400 and 900.

But "I" can also be placed before C,D and M not just V and X.
For example, "IC"-> 99, "ID"->499, etc
Similarly X can also be placed before X.
For example, "XD"->490, etc.
So **the way question limits the subtraction rules to 6** isn't correct and should be reworded.

**Comment by lc-kay** [comment]
Hi @devilsuse 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @devilsuse 
The team reviewed your report and noticed the problem was missing validators. We've updated the problem and did not change the description. We appreciate your support!

**Comment by devilsuse** [comment]
Let me again say this:
Problem statement says : 6 instances and 2 instances are below:
I can be placed before V (5) and X (10) to make 4 and 9. 

Now will anyone not assume that "I" can only be placed just before "V" and "X" only but reality is it can be placed before "C" as well like in "IC" -> 99 etc
So description should be corrected as well.

**Comment by lc-kay** [comment]
@devilsuse The statement is correct. "I" cannot be placed before "C". Please try it in the run code and you'll get an error.
