### ISSUE TITLE
Missing Test Case - 10. Regular Expression Matching

### ISSUE THREAD

**Issue by shambhavi2703** [LeetCode-Feedback/LeetCode-Feedback#12692]
#### Category of the bug
-
- [x] Missing Test Cases 

#### Description of the bug
the test case should return false as the first character should not match

#### Code you used for Submit/Run operation

```
class Solution {
public:
      bool stars(string& p, int i) {
        for (int del_i = 0; del_i <= i; del_i++) {
            if (p[del_i] != '*') {
                return false;
            }
        }
        return true;
    }
    bool helper(int ind1, int ind2, string& s, string& p) {
        if (ind1 < 0 && ind2 < 0) {
            return true;
        }
        if (ind2 < 0 && ind1 >= 0) {
            return false;
        }
        if (ind1 < 0) {
            return stars(p, ind2);
        }
        
        if (s[ind1] == p[ind2] || p[ind2] == '.') {
            return helper(ind1 - 1, ind2 - 1, s, p);
        } else if (p[ind2] == '*') {
           return helper(ind1 , ind2-1, s, p)||helper(ind1-1,ind2,s,p) ;
        } else {
            return false;
        }
    }
    bool isMatch(string &s, string &p)
    {
        int size1 = s.size();
        int size2 = p.size();
        return helper(size1-1,size2-1,s,p);
        
    }
};
```

#### Expected behavior
this test case should return false, but expected is true. please fix t

#### Screenshots
![image](https://user-images.githubusercontent.com/98222015/229302891-5119cc4f-6fc1-4e2f-9dcc-e20f248e71bb.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

**Comment by shambhavi2703** [comment]
but if we analyze the above test case the output should be false as c in string p and never match with any character in string s.
