### ISSUE TITLE
Invalid Constraints - 1629. Slowest Key

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1269]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

1629. Slowest Key
https://leetcode.com/problems/slowest-key/

- Constraints is given as below:

	0 <= releaseTimes[i] <= 10^9

- The Test case that fails:

	Input:
		[0,1]
		"ab"

	Invalid test case
		'releaseTimes' must consist of values from 1 to 1000000000 only

So, why is the error for releaseTimes?
- Can the releaseTimes be 0, or it starts at 1? Which one is correct?

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JavaScript

#### Expected behavior

- Constraints must be correct, otherwise, the User will waste time in generating test cases
- These mistakes should not happen, it affects the time in the contest - One of the reasons why I won't attend contests on LC quality is not high even in 2020.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
