### ISSUE TITLE
面试题 10.03. 搜索旋转数组_测试程序好像不太对

### ISSUE THREAD

**Issue by IsolatedRain** [LeetCode-Feedback/LeetCode-Feedback#127]
面试题 10.03. 搜索旋转数组: [题目链接](https://leetcode-cn.com/problems/search-rotate-array-lcci/)
使用以下测试用例的时候, 应该返回 5, 但是预期结果却为 -1
`[1,1,1,1,1,2,1,1,1]
2
`

**Comment by feiceh** [comment]
能否提供一下代码和「执行代码」的输出或「提交代码」的结果截图，把信息提供完整才能有助于快速验证和精准的定位哟～

**Comment by feiceh** [comment]
fixed
