### ISSUE TITLE
Missing Test Case - 2577. Minimum Time to Visit a Cell In a Grid

### ISSUE THREAD

**Issue by Tudor67** [LeetCode-Feedback/LeetCode-Feedback#12706]
#### Your LeetCode username

[Tudor67](https://leetcode.com/Tudor67/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My solution passed all the test cases and was accepted,
but I found a test case that it doesn’t cover.

My solution doesn't cover the following test case:
__*Input:*__
```
[[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
 [25, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,  0],
 [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
 [ 0, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99],
 [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]]
```

__*Output:*__ `46`

__*Expected:*__ `42`

**_Test File (.txt)_**: [test_for_prob_2577.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/11130554/test_for_prob_2577.txt)

#### Code you used for Submit/Run operation

[Submission Link](https://leetcode.com/problems/minimum-time-to-visit-a-cell-in-a-grid/submissions/926170106/)
``` C++
// 2577. Minimum Time to Visit a Cell In a Grid
// C++
class Solution {
private:
    const vector<pair<int, int>> DIRECTIONS = {{0, 1}, {0, -1}, {-1, 0}, {1, 0}};
    const int INF = 1e9;

    int bfs(vector<vector<int>>& grid, int startTime){
        const int ROWS = grid.size();
        const int COLS = grid[0].size();
        
        queue<tuple<int, int, int>> q;
        vector<vector<bool>> vis(ROWS, vector<bool>(COLS, false));
        q.push({startTime, 0, 0});
        vis[0][0] = true;
        
        while(!q.empty()){
            int t = get<0>(q.front());
            int row = get<1>(q.front());
            int col = get<2>(q.front());
            q.pop();
            
            if(row == ROWS - 1 && col == COLS - 1){
                return t;
            }
            
            int nextT = t + 1;
            for(const pair<int, int>& DIRECTION: DIRECTIONS){
                int nextRow = row + DIRECTION.first;
                int nextCol = col + DIRECTION.second;
                if(0 <= nextRow && nextRow < ROWS && 0 <= nextCol && nextCol < COLS){
                    if(grid[nextRow][nextCol] <= nextT){
                        if(!vis[nextRow][nextCol]){
                            q.push({nextT, nextRow, nextCol});
                            vis[nextRow][nextCol] = true;
                        }
                    }
                }
            }
        }
        
        return INF;
    }
    
public:
    int minimumTime(vector<vector<int>>& grid) {
        const int ROWS = grid.size();
        const int COLS = grid[0].size();
        
        if(grid[0][1] >= 2 && grid[1][0] >= 2){
            return -1;
        }
        
        int l = 0;
        int r = (1e5 + 2) / 2;
        while(l != r){
            int mid = (l + r) / 2;
            if(bfs(grid, 2 * mid) == INF){
                l = mid + 1;
            }else{
                r = mid;
            }
        }

        int res = INF;
        for(int i = r; i <= r + 10; ++i){
            res = min(res, bfs(grid, 2 * i));
        }

        if(res == INF){
            res = -1;
        }

        return res;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Wrong Answer

#### Screenshots

![prob_2577_WA](https://user-images.githubusercontent.com/12481060/229312746-b1210a5f-f101-4f32-99d0-2a5f2b5d0db0.png)

#### Additional context

I **binary search** the `minimum valid startTime` that allows us to find a path from cell {0, 0} to cell {ROWS - 1, COLS - 1} (with **bfs**):  
- without visiting a cell more than one time and  
- satisfying the condition (grid[row][col] <= currentTime).  

Using the `minimum valid startTime`, I compute with **bfs** the `total time` for a path from {0, 0} to {ROWS - 1, COLS - 1}.  

Unfortunately, this **doesn't guarantee** that we will **always** find the **minimum total time** for a path from {0, 0} to {ROWS - 1, COLS - 1}.

To **pass** the current **weak test cases** I compute the result for [startTime, startTime + 2 \* 10] range and I get `Accepted`.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
