### ISSUE TITLE
Missing Testcase - 1629. Slowest Key

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1270]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Below test case fails in the below code:

	input
		[1,2]
		"ba"
	expected  "b"
	actual    "a"

#### Code you used for Submit/Run operation

At https://leetcode.com/problems/slowest-key/discuss/909070/JAVA-Solution-O(n)-Explained/743406

```
var slowestKey = function(releaseTimes, keysPressed) {
    let index = 0, maxVal = releaseTimes[0];
    for (var i = 1; i < keysPressed.length; i++) {
        if ((releaseTimes[i] - releaseTimes[i - 1]) >= maxVal) {
            maxVal = (releaseTimes[i] - releaseTimes[i - 1]);
            index = i;
        }
    }

    return keysPressed[index];
};
```

#### Language used for code
JavaScript

#### Expected behavior

- Please add enough test cases so there will be some quality in the top solutions and their post's comments
- Please hire a good tester

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
