### ISSUE TITLE
Interview Crash Course - Hashing Quiz

### ISSUE THREAD

**Issue by wlsidlsi** [LeetCode-Feedback/LeetCode-Feedback#12709]
#### Your LeetCode username
wlsidlsi

#### Category of the bug
- [x ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
This is for LeetCode's Interview Crash Course in the Hashing section.

Problem 1, none of the checkmark items are selected as correct.

I selected Immutable string but marked it wrong then I went through every other answer and they were all wrong.
Maybe the valid for the checkmark is wrong in the form.

Problem 2,  Wording is confusing or wrong it states "Which of the following **_can_** be stored as a value in a hash map?"
The answer should be all the values can be stored in hash map.  There is no limitation that I know of by python, javascript, c or c++.

The key has a immutable requirement but the value can be array list, integer, string, boolean, or just about anything.

#### Code you used for Submit/Run operation
Not applicable.

#### Expected behavior

Correct answers
Problem 1. Immutable String
2. All the types CAN be passed as values to a hash map.

#### Screenshots

![image](https://user-images.githubusercontent.com/91036491/229324923-d76465f1-211d-40b5-931b-463ab0ad0588.png)

**Comment by suman897** [comment]
Have you tried to report the issue ? 
You can find an report issue in the right corner of the page 
![image](https://user-images.githubusercontent.com/45995997/229326773-ad0fc614-41bb-4b37-b676-c9a505168262.png)

since the answers you provided are correct its an bug/error from their side

**Comment by wlsidlsi** [comment]
I just clicked the report issue on top right and it brought me to this site...

<img width="825" alt="image" src="https://user-images.githubusercontent.com/91036491/229327565-b4042ff0-8ef9-4679-8c1b-50db874a15e4.png">

Was this report link wrong too? =)

**Comment by wlsidlsi** [comment]
Just realized you were telling me to do what I did.  Ya, that link brings me to this website.  I'll look for another reporting mechanism.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

The questions take multiple options per answer.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
