### ISSUE TITLE
Missing Test Case - 2607. Make K-Subarray Sums Equal

### ISSUE THREAD

**Issue by pra8186** [LeetCode-Feedback/LeetCode-Feedback#12705]
#### Your LeetCode username
pra8186

#### Category of the bug
- [ ] Question 2607 Make K-subarray Sums Equal
- [ ] Solution
- [ ] Language python3
- [ ] Missing Test Cases [1,4,1,3,5,6,7]

#### Description of the bug
 When value of n=7 and k=5 then the expected result is shown to be 13 operations  but it can be done in 8 operations for the above testcase

#### Code you used for Submit/Run operation
'''def makeSubKSumEqual(self, arr: List[int], k: int) -> int:
        n = len(arr)
        gcd = math.gcd(n, k)
        ans = 0
        for i in range(gcd):
            tmp = sorted([arr[j] for j in range(i, n, gcd)])
            median = tmp[len(tmp) // 2]
            ans += sum(abs(num - median) for num in tmp)
        return ans
'''

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code
python3

#### Screenshots

![IMG_20230402_013906](https://user-images.githubusercontent.com/85034364/229312010-f35fe44f-630a-482a-aba3-5a55b9df31c8.jpg)

**Comment by siMarzouki** [comment]
starting from index i = 4
we have [5,1,5,1,5] its sum = 17 so we can't made it in 8 operations
i think the code provided is the best for this problem

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
