### ISSUE TITLE
Error in Round function in MS SQL Server

### ISSUE THREAD

**Issue by krishnabhunia** [LeetCode-Feedback/LeetCode-Feedback#12713]
#### Category of the bug
- [262. Trips and Users] Question
- [Error in solution, Round function is not working but in mySQL its working fine ] Solution
- [ MS SQL Server] Language
- [No ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
SELECT
    request_at AS Day,
    ROUND((SUM(CASE WHEN status != 'completed' THEN 1 ELSE 0 END)/COUNT(DISTINCT id)),2) AS 'Cancellation Rate'
FROM Trips
WHERE request_at BETWEEN '2013-10-01'
AND '2013-10-03'
AND client_id NOT IN (
    SELECT
        users_id
    FROM Users
    WHERE banned = 'Yes'
)
AND driver_id NOT IN (
    SELECT
        users_id
    FROM Users
    WHERE banned = 'Yes'
)
GROUP BY request_at;
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
