### ISSUE TITLE
Missing test case - 6330 shortest cycle in a graph

### ISSUE THREAD

**Issue by tdzl2003** [LeetCode-Feedback/LeetCode-Feedback#12716]
#### Your LeetCode username
DengYun

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
program is getting accepted
https://leetcode.cn/submissions/detail/420546253/
but its failing for the testcase

13
[[0,1],[1,2],[2,3],[3,4],[4,5],[0,8],[0,9],[9,10],[10,11],[11,12],[12,7],[0,7],[0,6],[5,7],[5,6]]

#### Code you used for Submit/Run operation
```
const int INF = 0x3f3f3f3f;

class Solution {
    int ans = INF;
    int n;
    vector<vector<int>> adj;
    vector<int> dep;
    
    void dfs(int u, int p) {
        for (int v : adj[u]) {
            if (v == p) continue;
            if (dep[v] != -1) {
                ans = min(ans, max(dep[u], dep[v]) - min(dep[u], dep[v]) + 1);
            } else {
                dep[v] = dep[u] + 1;
                dfs(v, u);
            }
        }
    }
public:
    int findShortestCycle(int n, vector<vector<int>>& edges) {
        this->n = n;
        adj = vector<vector<int>>(n);
        for (auto &e : edges) {
            int u = e[0], v = e[1];
            adj[u].push_back(v);
            adj[v].push_back(u);
        }
        
        for (int i = 0; i < n; ++i) {
            dep = vector<int>(n, -1);
            dep[i] = 0;
            dfs(i, -1);
        }
        
        return ans == INF ? -1 : ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior
Should return 4 but it returns 6

**Comment by tdzl2003** [comment]
dfs is wrong algorithm for this problem, but some code got accepted for current dataset.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
