### ISSUE TITLE
Missing Test Case - 605. Can Place Flowers

### ISSUE THREAD

**Issue by sudevdhali** [LeetCode-Feedback/LeetCode-Feedback#12715]
#### Your LeetCode username

newbiesd

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [. ] Missing Test Cases 

#### Description of the bug

program is getting accepted
https://leetcode.com/submissions/detail/926601390/
but its failing for the testcase 
[0,0,0,0,0,0,0,0,0]
6

#### Code you used for Submit/Run operation

```
class Solution:
    def canPlaceFlowers(self, flowerbed: List[int], n: int) -> bool:
        k = 0
        m = len(flowerbed)

        if((m == 1 and flowerbed[0] == 0 and n == 1) or n == 0):
            return True;
    
        if(m == 2 and flowerbed[0] == 0 and flowerbed[1] == 0 and n == 1):
            return True;

        if(m < 3):
            return False;
        
        if(flowerbed[0] == 0 and flowerbed[1] == 0 ):
            k+=1
        
        if(m > 4):
            i=1
            while i<m-2:
                if(flowerbed[i] == 0 and flowerbed[i + 1] == 0 and flowerbed[i + 2] == 0):
                    k+=1
                    i+=1
                i+=1
                
        if(flowerbed[m - 2] == 0 and flowerbed[m - 1] == 0):
            k+=1
        
        if (n <= k):
            return True;
        
        return False;
    
```

#### Language used for code

python3

#### Expected behavior

it sholuld return false but its returning true

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by sudevdhali** [comment]
is there any update?

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
