### ISSUE TITLE
Some Error In the Constraints - 2607. Make K-Subarray Sums Equal

### ISSUE THREAD

**Issue by sumit334** [LeetCode-Feedback/LeetCode-Feedback#12717]
#### Your LeetCode username

Towards_Horizon

#### Category of the bug
- [.] Question-->It have some issue
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
Question have some issues

#### Description of the bug

Actually when I was trying to run a testcase with value of k greater than 9 it shows me that "expected 'k' to have value from 1 to 9 only"  whereas in the constraint section it is mentioned that 1 <= k <= arr.length <= 10^5 , which makes a contradiction.
So, I would request to please look into the matter

#### Code you used for Submit/Run operation

```
//JAVA
// Make K-Subarray Sums Equal
class Solution {
    public long makeSubKSumEqual(int[] arr, int k) {
        int n=arr.length; 
        long ans=0;
        boolean vis[]=new boolean[n];
        for(int i=0;i<n;i++){
            if(vis[i])  continue;
            ArrayList<Integer> list=new ArrayList<>();
            list.add(arr[i]);
            //vis[i]=true;
            int next=(i+k)%n;
            while(i!=next){
                vis[next]=true;
                list.add(arr[next]);
                next=(next+k)%n;
            }
            Collections.sort(list);
            int median=list.get(list.size()/2);
            for(int j=0;j<list.size();j++)  ans+=(long)Math.abs(list.get(j)-median);
        }
        return ans;
    }
}
```

#### Expected behavior

I actually wanted to run a testcase which can have value of k greater than 9 as mentioned in the constraint section but it's showing invalid testcase Error.
TestCase I was trying to run:
[1,212,2,12,1,2,2221,221232,23232]
10

#### Screenshots

![LeetCode_BUg](https://user-images.githubusercontent.com/97662774/229371350-e11360c8-0a14-4ffd-8dce-2b49d029538d.PNG)

#### Additional context

Please try to reslove it . Thank You

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 
k <= arr.length which is equal to 9.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
