### ISSUE TITLE
Missing Test Case - 2612. Minimum Reverse Operations

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#12710]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets WA on the following testcase:
100000
0
[]
2

#### Code you used for Submit/Run operation

```
from sortedcontainers import SortedList
class Solution:
    def minReverseOperations(self, n: int, p: int, banned: List[int], k: int) -> List[int]:
        s = set(banned)
        a = [i for i in range(n) if i != p and i not in s]
        odd = SortedList([x for x in a if x % 2])
        even = SortedList([x for x in a if x % 2 == 0])
        dis = {p: 0}
        # print(len(tree))
        q = deque([p])
        for I in range(n//4+100):
            q1 = deque([])
            while len(q) != 0:
                x = q.popleft()
                left = max(0, x - k + 1)
                right = min(n - 1, x + k - 1) - k + 1
                # print(x, left, right)
                left = 2 * left + k - 1 - x
                right = 2 * right + k - 1 - x
                if left % 2:
                    tree = odd
                else:
                    tree = even
                i = tree.bisect_left(left)
                j = tree.bisect_right(right)
                # print(x, left, right)
                # print(i, j)
                # print(tree)
                for it in range(i, j):
                    y = tree[it]
                    dis[y] = dis[x] + 1
                    q1.append(y)
                for it in range(i, j):
                    tree.pop(i)
            q=q1
        return [dis[i] if i in dis else -1 for i in range(n)]
```

#### Language used for code

Python3

#### Expected behavior

The code gets WA.
![image](https://user-images.githubusercontent.com/11583428/229337859-93cb17c9-23a2-4573-bb52-1256ec120918.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
