### ISSUE TITLE
88 Merge Sorted Array: unclear how num1 is evaluated

### ISSUE THREAD

**Issue by ja-ba** [LeetCode-Feedback/LeetCode-Feedback#12711]
#### Your LeetCode username
jay_hacks

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
According to the question , we should merge into nums1. However it is confusing how nums1 is evaluated. If we just hard code nums1 to be the solution of one of the test cases, this gives another output and the test case fails

#### Code you used for Submit/Run operation
Solution in Python3
// Merge Sorted Array
```
class Solution:
    def merge(self, nums1: List[int], m: int, nums2: List[int], n: int) -> None:
        nums1 = [1,2,2,3,5,6]
```

#### Language used for code
Python 3 

#### Expected behavior
The output should be the value of the variable nums1 after the function has finished execution

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
