### ISSUE TITLE
Test Case Needs to be Enhanced -  642. Design Search Autocomplete System

### ISSUE THREAD

**Issue by shit-eater** [LeetCode-Feedback/LeetCode-Feedback#12726]
Your LeetCode username
v5qYY4Q65w

Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [√] Missing Test Cases 

Description of the bug
This problem is designed for Trie. But the brute force can get expected because of the terrible constraints. As a problem marked as 'Hard', brute force cannot be allowed. 

Code you used for Submit/Run operation

Brute force (can get accepted):
```
class AutocompleteSystem:

    def __init__(self, sentences: List[str], times: List[int]):

        self.table = defaultdict(dict)
        self.cur = ''
        for j in range(len(sentences)):
            self.addword(sentences[j],times[j])

    def addword(self, s ,freq):

        for j in range(1,len(s)+1):
            if s not in self.table[s[:j]]:
                self.table[s[:j]][s]=0
            self.table[s[:j]][s]+=freq

    def input(self, c: str) -> List[str]:
        
        if c=='#':
            self.addword(self.cur,1)
            self.cur = ''
            return []
        self.cur+=c
        return sorted(self.table[self.cur].keys(),key=lambda x: [-self.table[self.cur][x],x])[:3]
```

The expected solution(using Trie):
```
class AutocompleteSystem:

    def __init__(self, sentences: List[str], times: List[int]):

        self.ct = Counter({s: t for s, t in zip(sentences, times)})
        T = lambda: defaultdict(T)
        self.trie = T()
        for s in sentences:
            self.insert(s)
        self.p = self.trie
        self.s = ''

    def insert(self, s):

        p = self.trie
        for char in s:
            p = p[char]
            p['#'] = p.get('#', set()) | {s}

    def input(self, c: str) -> List[str]:

        if c == '#':
            self.ct[self.s] += 1
            self.insert(self.s)
            self.s = ''
            self.p = self.trie
            return []
        self.s += c
        self.p = self.p.get(c, {'#': set()})
        return sorted(self.p['#'], key=lambda s: [-self.ct[s], s])[:3]
```

Language used for code
Python3

Expected behavior
1. The constraints of n should be increased from 100 to 10000. The numbers of calls of 'input' should be increased to 50000.
2. At least one testcase of n==10000 and 'input'==50000 should be added.
A possible testcase:
[testcasefor642.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/11133850/testcasefor642.txt)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Please send a smaller test case.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
