### ISSUE TITLE
Golang test cases in runtime issue

### ISSUE THREAD

**Issue by mahmoud-abdelsattar** [LeetCode-Feedback/LeetCode-Feedback#12723]
#### Your LeetCode username
  santana11santana 

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug 
 When i run test case alone my code pass if the same test cases run with another test case my code fails

#### Code you used for Submit/Run operation

```
//3. Longest Substring Without Repeating Characters

type sett map[rune]struct{} 
func (s sett) adding(ele rune){
    s[ele] = struct{}{}
}
func (s sett) remove(ele rune){
    delete(s, ele)
}
func (s sett) has(ele rune) bool{
 _,ok :=  s[ele]
 return ok
}
var counter int = 0
var maxLen  int = 0 
func lengthOfLongestSubstring(s string) int {
	hashset := sett{}

	for _, k := range s {
		if hashset.has(k)==true { 
			if maxLen < counter{
				 maxLen = counter	
			}
			hashset = sett{}
			counter = 0
			//continue
		} else {
			hashset.adding(k)
			counter++
			if maxLen < counter{
				 maxLen = counter	
			}
		} 
	}  
	fmt.Print(hashset)
	fmt.Print(counter)
	return maxLen
}
```

#### Language used for code
  Go  

#### Expected behavior
 Return the max length of substring   -->

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output values.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!

**Comment by mahmoud-abdelsattar** [comment]
Thanks for the fast response but it seems it not helping im using go and the article just mention c++ java and python 
and i tried to follow what the article says on go but does not solve anything

**Comment by mahmoud-abdelsattar** [comment]
on the editors as goland or Vs the expected out is correct
