### ISSUE TITLE
1632. Rank Transform of a Matrix | Official solutions run time limit exceed

### ISSUE THREAD

**Issue by zerotrac** [LeetCode-Feedback/LeetCode-Feedback#1272]
#### Your LeetCode username
zerotrac2

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Hi there. I am the official solution contributor to the LeetCode China site. When I try to make a survey on the algorithms to solve the weekly contest problem [1632. Rank Transform of a Matrix](https://leetcode.com/problems/rank-transform-of-a-matrix/), I find that LeetCode US site has already published an official solution containing three different methods.

However, after running on my carefully constructed testcases, two of the three methods (the BFS and DFS ones) result in TLE. I do not read through the details of the codes, but I believe that there may be either incorrect calculations on the theoretical time complexity or careless implementation in the codes.

Thus, I suggest that:

- Add my testcase
- Check the correctness of the official solution

#### Testcase generator

Due to the testcase is large (500 times 500), I will give the testcase generator below. The idea is to construct spiral-shaped paths with the same number to hack search-based algorithms.

```Python3
N = 500

grid = [[666] * N for _ in range(N)]
steps = [(0, -1), (-1, 0), (0, 3), (4, 0)]
num = 0

for start in range(0, 480 + 1, 4):
    num += 1
    grid[0][start] = grid[0][start + 2] = grid[2][start + 2] = num * 2
    x, y = 2, start + 2
    while True:
        # Trial
        x0, y0 = x, y
        success = True
        for dx, dy in steps:
            x0 += dx
            y0 += dy
            if not (0 <= x0 < N and 0 <= y0 < N):
                success = False
                break

        if not success:
            grid[x - 1][y] = num * 2 - 1
            if y + 2 < N:
                grid[x - 1][y + 2] = num * 2
            break

        # Construct
        for dx, dy in steps:
            x += dx
            y += dy
            if 0 <= x < N and 0 <= y < N:
                grid[x][y] = num * 2
            else:
                break
        if not (0 <= x < N and 0 <= y < N):
            break


with open("1.txt", "w") as f:
    print(grid, file=f)
```

#### Language used for code
Both C++ & Python codes for BFS & DFS methods. They all run TLE. I am not familiar with Java so I did not test that.

#### Expected behavior
Official solutions should pass all possible testcases.

**Comment by lc-kay** [comment]
@zerotrac Can you please share the test case generator through https://leetcode.com/playground/new/empty? I am getting error messages when I try to generate your test case.

**Comment by zerotrac** [comment]
> @zerotrac Can you please share the test case generator through https://leetcode.com/playground/new/empty? I am getting error messages when I try to generate your test case.

Here: https://leetcode.com/playground/7JhhYdze

**Comment by lc-kay** [comment]
Hi @zerotrac 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
