### ISSUE TITLE
Missing Test Case - 605. Can Place Flowers

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#12721]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets WA on the following testcase:
[0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0]
5

#### Code you used for Submit/Run operation

```
class Solution:
    def canPlaceFlowers(self, flowerbed: List[int], n: int) -> bool:
        pos = 0
        while pos < len(flowerbed) and n != 0:
            #check current
            if flowerbed[pos] == 0 and self.checkLeft(flowerbed, pos) and self.checkRight(flowerbed, pos):
                n -= 1
                flowerbed[pos] = 1
            if pos + 2 < len(flowerbed):
                pos += 2
            else:
                pos += 1
        if n == 0:
            return True
        else:
            return False
    
    def checkLeft(self, flowerbed, pos):
        if pos == 0:
            return True
        if flowerbed[pos - 1] == 0:
            return True
        else:
            return False
    def checkRight(self, flowerbed, pos):
        if pos == len(flowerbed) - 1:
            return True
        if flowerbed[pos + 1] == 0:
            return True
        else:
            return False
```

#### Language used for code

Python3

#### Expected behavior

Output: false
Expected: true

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
