### ISSUE TITLE
Missing Test Case - 605. Can Place Flowers

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#12722]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets WA on the following testcase:
[0, 1]
1

#### Code you used for Submit/Run operation

```
class Solution:
    def canPlaceFlowers(self, flowerbed, n: int) -> bool:
        can_be_placed = 0

        #check extremities
        if len(flowerbed) > 2:
            if flowerbed[0] == 0 and flowerbed[1] == 0:
                can_be_placed += 1
                flowerbed[0] = 1    
            if flowerbed[-1] == 0 and flowerbed[-2] == 0:
                can_be_placed += 1
                flowerbed[-1] = 1 
        elif flowerbed[0] == 0:
                can_be_placed += 1
                flowerbed[0] = 1

        for i in range(1, len(flowerbed ) - 1):
            if flowerbed[i - 1] == 0 and flowerbed[i + 1] == 0 and flowerbed[i] == 0:
                can_be_placed += 1
                flowerbed[i] = 1
            if can_be_placed >= n:
                return True
        
        if can_be_placed >= n:
            return True
        else:
            return False 
```

#### Language used for code

Python3

#### Expected behavior

Output: true
Expected: false

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
