### ISSUE TITLE
Missing Test Case - 881. Boats to Save People

### ISSUE THREAD

**Issue by sahilsandi07** [LeetCode-Feedback/LeetCode-Feedback#12733]
When we give input as `people = [1,1,1,1,1,1,1,1]` and `limit = 8`
The `output` should be `1`.
Because the boat will be able to carry all people in one go.

#### Your LeetCode username

sahilsandi07

#### Category of the bug

- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int numRescueBoats(vector<int>& people, int limit) {
        int ans = 0;
        sort(people.begin(), people.end());
        
        int heavy = 0, light =people.size() - 1;

        while (heavy <= light)
        {
            ans++;
            if (people[heavy] + people[light] <= limit)
            {
                heavy++;
            }
            light--;
        }
        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior
When we give input as `people = [1,1,1,1,1,1,1,1]` and `limit = 8`
The `output` should be `1`.
Because the boat will be able to carry all people in one go.

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
