### ISSUE TITLE
Missing Test Case - 2608. Shortest Cycle in a Graph

### ISSUE THREAD

**Issue by sumit334** [LeetCode-Feedback/LeetCode-Feedback#12738]
#### Your LeetCode username

Towards_Horizon

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [.] Missing Test Cases -->Test case is missing

#### Description of the bug

There is a missing test case in the question :
9
[[0,3],[3,4],[4,1],[5,6],[1,5],[6,2],[7,8],[2,7],[0,8],[0,1],[1,2],[2,0]]
This is giving a answer as 4 in my output but the correct answer is 4 , but the answer of mine is getting submitted irrespective of getting WA while running the mentioned testcase.

#### Code you used for Submit/Run operation

```
//C++
//2608. Shortest Cycle in a Graph
class Solution {
public:
    int bfs(int i, int n, vector<vector<int>> &al) {
    vector<int> q{i}, q1, from(n, -1);
    for (int dist = 0; !q.empty(); ++dist) {
        q1.clear();
        for (int i : q)
            for (int j : al[i]) {
                if (from[j] != i && from[i] != j) {
                    if (from[j] != -1)
                        return (dist + 1) * 2 - count(begin(q), end(q), j);
                    from[j] = i;
                    q1.push_back(j);
                }
            }
            swap(q, q1);
        }
        return INT_MAX;
    }
    int findShortestCycle(int n, vector<vector<int>>& edges) {
        vector<vector<int>> al(n);
        for (const auto &e : edges) {
            al[e[0]].push_back(e[1]);
            al[e[1]].push_back(e[0]);
        }
        int res = INT_MAX;
        for (int i = 0; i < n; ++i)
            res = min(res, bfs(i, n, al));
        return res == INT_MAX ? -1 : res;
    }
};
```

#### Language used for code

C++

#### Expected behavior

For the testcase:
9
[[0,3],[3,4],[4,1],[5,6],[1,5],[6,2],[7,8],[2,7],[0,8],[0,1],[1,2],[2,0]]
The expected answer is 3 but mine it is giving 4 , which shows WA on compilation but the same code is getting accepted by the leetcode, so there is a missing test case that needs to be added and that is:
9
[[0,3],[3,4],[4,1],[5,6],[1,5],[6,2],[7,8],[2,7],[0,8],[0,1],[1,2],[2,0]]

#### Screenshots

![leetcodebugques](https://user-images.githubusercontent.com/97662774/229530815-49f9f379-a30b-42b3-b218-c82f42598dc3.PNG)
![leetcodebug](https://user-images.githubusercontent.com/97662774/229530872-ea12e73b-5a03-4d7e-9184-a82478c7f4bc.PNG)

#### Additional context

Please look into the matter it would help us .
Thank You 
Happy Leetcoding!

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output values.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!
