### ISSUE TITLE
Missing Constraints - 47. Permutations II

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1273]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

47. Permutations II
https://leetcode.com/problems/permutations-ii/

- Constraints are missing

Please add constraints of the problem
- What is the range of length of nums?
- What is the range of values of elements of nums?

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JavaScript

#### Expected behavior

- Constraints must be present
Otherwise
  - Users might have a TLE due to missing constraints
  - More effort is required to build test cases.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
