### ISSUE TITLE
Crack the Apple Interview - Dynamic Programming - wrong problem name

### ISSUE THREAD

**Issue by mnaoumov** [LeetCode-Feedback/LeetCode-Feedback#12744]
#### Your LeetCode username

mnaoumov

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Explore card https://leetcode.com/explore/interview/card/apple/347/dynamic-programming/ mentions `Best Time to Buy, the Sell Stock` problem.

#### Expected behavior

`Best Time to Buy and Sell Stock` should be used instead

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
