### ISSUE TITLE
Incomplete Question - 47. Permutations II

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1274]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

47. Permutations II
https://leetcode.com/problems/permutations-ii/

- The question description is incomplete

Input:

	[1,1,2]

Below sample codes give different order of the output but still passes.

Please add below to the question:

- Order of the permutations in the output does not matter

#### Code you used for Submit/Run operation

```
var permuteUnique = function(nums) {
    return [[1,1,2],[1,2,1],[2,1,1]]
};

var permuteUnique = function(nums) {
    return [[1,2,1],[2,1,1],[1,1,2]]
};
```

#### Language used for code
JavaScript

#### Expected behavior

- The question must provide all details so that the User does not have to get confused or spend time getting the same order as the Judge's output

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
