### ISSUE TITLE
Missing Test Case - 1843. Suspicious Bank Accounts

### ISSUE THREAD

**Issue by yiyumin** [LeetCode-Feedback/LeetCode-Feedback#12745]
#### Your LeetCode username
whatdoyumin

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the problem statement, it says to:

`Return the result table ordered by transaction_id in ascending order.`

However, the transaction_id is not a column returned in the result table and the order of the returned account_id's does not matter.

#### Code you used for Submit/Run operation
Example showing how the order of transaction_id or account_id is not considered.

test case:
{"headers": {"Accounts": ["account_id", "max_income"], "Transactions": ["transaction_id", "account_id", "type", "amount", "day"]}, "rows": {"Accounts": [[3, 21000], [4, 10400]], "Transactions": [[1, 3, "Creditor", 107100, "2021-06-02 11:38:14"], [4, 4, "Creditor", 10401, "2021-06-20 12:39:18"], [11, 4, "Debtor", 58800, "2021-07-23 12:41:55"], [2, 4, "Creditor", 49300, "2021-05-03 16:11:04"], [15, 3, "Debtor", 75500, "2021-05-23 14:40:20"], [10, 3, "Creditor", 102100, "2021-06-15 10:37:16"], [14, 4, "Creditor", 56300, "2021-07-21 12:12:25"], [19, 4, "Debtor", 101100, "2021-05-09 15:21:49"], [8, 3, "Creditor", 64900, "2021-07-26 15:09:56"], [7, 3, "Creditor", 90900, "2021-06-14 11:23:07"]]}}

```
with exceeded_months as (
    select
        m.account_id,
        m.trans_year * 12 + m.trans_month as month_num
    from (
        select
            account_id,
            year(day) as trans_year,
            month(day) as trans_month,
            sum(amount) as month_total
        from Transactions
        where type = 'Creditor'
        group by account_id, trans_year, trans_month
    ) m
    join Accounts a
        on m.account_id = a.account_id
        and m.month_total > a.max_income
)
select distinct m1.account_id
from exceeded_months m1
join exceeded_months m2
    on m1.account_id = m2.account_id
    and m1.month_num + 1 = m2.month_num
order by m1.account_id # desc
```
**Output 1 - _with order by m1.account_id_**
{"headers": ["account_id"], "values": [[3], [4]]}

**Output 2 - _with order by m1.account_id desc_**
{"headers": ["account_id"], "values": [[4], [3]]}

**Expected - for both outputs**
{"headers": ["account_id"], "values": [[3], [4]]}

Result: both output 1 and output 2 are AC showing that neither the order of account_id nor the order of transaction_id's (transaction_id 1 & 2 made by different accounts) are taken into account.

#### Language used for code
MySQL

#### Expected behavior
Either the description should be changed to `Return the result table in any order.`
or the description should be updated to `Return the result table ordered by account_id in ascending order.` and the code checker should be updated to reflect the change.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
