### ISSUE TITLE
Constraints not mentioned - Problem #11

### ISSUE THREAD

**Issue by swathi-vennela** [LeetCode-Feedback/LeetCode-Feedback#1275]
#### Category of the bug
*  Question
- [ ] Solution
- [ ] Language

#### Description of the bug
The question is incomplete, there's no mention of the constraints on 'n'

#### Additional context

[Problem](https://leetcode.com/problems/container-with-most-water/)

**Comment by lc-kay** [comment]
Hi @swathi-vennela 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @swathi-vennela 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
