### ISSUE TITLE
Error in test case:  Longest Substring Without Repeating Characters

### ISSUE THREAD

**Issue by Vengat** [LeetCode-Feedback/LeetCode-Feedback#12752]
ejtdfngsdnnkgpkvtigsq
                      -

Expected : 8

Output 9 - g p k v t i g s q

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
