### ISSUE TITLE
执行结果也提交结果不一致。

### ISSUE THREAD

**Issue by v3nooonn** [LeetCode-Feedback/LeetCode-Feedback#12753]
**你的 LeetCode 用户名**
®🐢

**Bug 类型**
- [ ] 题目
- [ ] 题解

**描述**
同样的input，在线执行结果与预期一样，但是提交结果不一样。

**你使用的语言**
Go

**你提交或者运行的代码**
```
const (
	Zero = 0
	One = 1
)

var (
	depth     int
	syncDepth = func(syncReq chan int) {
		for {
			select {
			case req := <-syncReq:
				if req > depth {
					depth = req
				}
			}
		}
	}
)

func maxDepth(root *TreeNode) int {
	if root == nil {
		return Zero
	}
	if root.Left == nil && root.Right == nil {
		return One
	}

	syncReq := make(chan int)
	defer close(syncReq)

	go syncDepth(syncReq)

	findMax(One, root, syncReq)

	return depth
}

func findMax(currentDepth int, node *TreeNode, syncReq chan int) {
	if node.Left == nil && node.Right == nil {
		syncReq <- currentDepth
	}

	if node.Left != nil {
		findMax(currentDepth+1, node.Left, syncReq)
	}
	if node.Right != nil {
		findMax(currentDepth+1, node.Right, syncReq)
	}
}
```

<img width="478" alt="image" src="https://user-images.githubusercontent.com/43428873/229733078-e99ecdff-fe21-4018-9cba-9cefbc63b02a.png">
<img width="259" alt="image" src="https://user-images.githubusercontent.com/43428873/229733227-77d88df0-7d55-4c5d-a6ae-bff65d0c1f52.png">
<img width="347" alt="image" src="https://user-images.githubusercontent.com/43428873/229733426-5fd92bab-89fc-48ea-a80c-cfdd1c71fcc7.png">

**Comment by feiceh** [comment]
你好，如果出现测试用例结果和提交结果不一致的情况，可以再仔细检查并调试一下代码，或点击这里：「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」 获得更多帮助。

同时也可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
