### ISSUE TITLE
Editorial Code is Broken - 270. Closest Binary Search Tree Value

### ISSUE THREAD

**Issue by Garrett-Bodley** [LeetCode-Feedback/LeetCode-Feedback#12768]
#### Your LeetCode username
Garrett-Bodley

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The editorial provides Java code that fails when copied and submitted on Leetcode.  It fails with the following test case.

```
root = [4,2,5,1,3]
target = 3.5
```

#### Code you used for Submit/Run operation
```
class Solution {
  public int closestValue(TreeNode root, double target) {
    LinkedList<TreeNode> stack = new LinkedList();
    long pred = Long.MIN_VALUE;

    while (!stack.isEmpty() || root != null) {
      while (root != null) {
        stack.add(root);
        root = root.left;
      }
      root = stack.removeLast();

      if (pred <= target && target < root.val)
        return Math.abs(pred - target) < Math.abs(root.val - target) ? (int)pred : root.val;

      pred = root.val;
      root = root.right;
    }
    return (int)pred;
  }
}
```

#### Language used for code
Java

#### Expected behavior
I would expect the solutions provided in the editorial to solve the problem they are explaining.

#### Additional context

![Screenshot 2023-04-04 at 8 33 11 PM](https://user-images.githubusercontent.com/46304333/229951902-8064457b-c93e-480d-a40c-f66b7f8fe210.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

**Comment by Garrett-Bodley** [comment]
The issue is not that the judger is incorrect, the issue is that the code provided in the editorial does not work. I have solved the problem, but the code shown above was copied and pasted directly from the editorial. Seeing that the editorial is premium content that I pay for, but nonetheless is providing an incorrect solution, it seems that this issue should be fixed.
