### ISSUE TITLE
Missing Test Case - 2610. Convert an Array Into a 2D Array With Conditions

### ISSUE THREAD

**Issue by Chandak-Keshav** [LeetCode-Feedback/LeetCode-Feedback#12764]
#### Your LeetCode username

sudo_keshav007

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 
Solution

#### Description of the bug

2610. Convert an Array Into a 2D Array With Conditions 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<vector<int>> findMatrix(vector<int>& nums) {
        int n=nums.size();
        unordered_map<int,int> mp;
        for(auto i:nums)
            mp[i]++;
        vector<vector<int>> finaly;
        while(mp.size()!=0)
        {
            vector<int> ans;
            unordered_map<int,int> mp2;
            for(auto i:nums)
            {
                if(mp2.find(i)==mp2.end())
                { 
                    mp2[i]++;
                    if(mp.find(i)!=mp.end())
                    {
                        ans.push_back(i);
                        if(mp[i]==1)
                            mp.erase(i);
                        else
                            mp[i]--;
                    }
                }
                else
                    continue;
            }
            finaly.push_back(ans);
        }
        return finaly;
    }
};
````

#### Language used for code

C++

#### Additional context

Added solution

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The issue.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Chandak-Keshav** [comment]
I am actually trying to post the solution for this particular problem.
There is no issue or missing test case in it
