### ISSUE TITLE
1632. Rank Transform of a Matrix - example in solution is not valid

### ISSUE THREAD

**Issue by caoxingdong** [LeetCode-Feedback/LeetCode-Feedback#1276]
#### Your LeetCode username
ddoudle

#### Category of the bug
- [ ] Solution

#### Description of the bug

https://leetcode.com/problems/rank-transform-of-a-matrix/solution/
![image](https://user-images.githubusercontent.com/32877011/97117572-3b5baa00-16ca-11eb-9c9c-d84f366675ac.png)
Please see this green box, the matrix is not a valid input, the element 5 in the up-left corner is the min value in its row and column should have rank-1

Also, I think this sentence is not correct:
![image](https://user-images.githubusercontent.com/32877011/97117632-9beae700-16ca-11eb-812b-afd24d469c3f.png)

**Comment by lc-kay** [comment]
Hi @caoxingdong 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@caoxingdong For clarification, can you please state which approach you are referring to?

**Comment by caoxingdong** [comment]
@lc-kay Hi, as the description of this problem has been changed, it's a valid input now.

**Comment by lc-kay** [comment]
Hi @caoxingdong ,
I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
