### ISSUE TITLE
Missing Test Case - 197. Rising Temperature

### ISSUE THREAD

**Issue by Sharfandc** [LeetCode-Feedback/LeetCode-Feedback#12771]
#### Your LeetCode username

Sharfandc

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

If I choose "run" the code works and my answer is right, but if I choose "submit" the code is wrong and showing different answer

#### Code you used for Submit/Run operation

```
SELECT
    sub.id
FROM
(SELECT
    *,
    LAG(temperature)OVER(ORDER BY recordDate) AS prev_temp
FROM Weather) sub
WHERE sub.temperature > sub.prev_temp
```

#### Language used for code

MySQL

#### Expected behavior

The answer is right since the results is exactly same

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output values.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!
