### ISSUE TITLE
Missing Test Case - 2608. Shortest Cycle in a Graph

### ISSUE THREAD

**Issue by EndlessCheng** [LeetCode-Feedback/LeetCode-Feedback#12770]
#### Your LeetCode username

endlesscheng

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The code below should get WRONG ANSWER, but it got ACCEPTED instead.

TEST CASE:
```
12
[[0,3],[0,5],[3,4],[4,5],[1,9],[1,11],[9,10],[11,10],[2,6],[2,8],[6,7],[8,7],[0,1],[0,2],[1,2]]
```

#### Code you used for Submit/Run operation

```python
class Solution:
    def findShortestCycle(self, n: int, edges: List[List[int]]) -> int:
        g = [[] for _ in range(n)]
        for x, y in edges:
            g[x].append(y)
            g[y].append(x) 

        def bfs(start: int) -> int:
            ans = inf
            dis = [-1] * n 
            dis[start] = 0
            q = deque([(start, -1)])
            while q and ans == inf:
                x, fa = q.popleft()
                for y in g[x]:
                    if dis[y] < 0: 
                        dis[y] = dis[x] + 1
                        q.append((y, x))
                    elif y != fa: 
                        ans = min(ans, dis[x] + dis[y] + 1)
            return ans

        ans = min(bfs(i) for i in range(n))
        return ans if ans < inf else -1
```

#### Language used for code

Python3

#### Expected behavior

WRONG ANSWER on this test case:
```
12
[[0,3],[0,5],[3,4],[4,5],[1,9],[1,11],[9,10],[11,10],[2,6],[2,8],[6,7],[8,7],[0,1],[0,2],[1,2]]
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
