### ISSUE TITLE
Missing Test Case - 剑指 Offer II 032. 有效的变位词

### ISSUE THREAD

**Issue by opqqqq** [LeetCode-Feedback/LeetCode-Feedback#12776]
#### Your LeetCode username

清风明月

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

缺少s和t相等时的测试样例

#### Code you used for Submit/Run operation

```
class Solution {
 public boolean isAnagram(String s, String t) {
if(s.length() != t.length() || s.length() == 1)return false;
        char[] char1 = new char[26];
        char[] char2 = new char[26];
        int sLen = s.length();
        for(int i = 0;i < sLen;i++){
            char1[s.charAt(i) - 'a']++;
            char2[t.charAt(i) - 'a']++;
        }
        return Arrays.equals(char1,char2);
}
}
```

#### Language used for code
java

#### Expected behavior

错误代码的返回语句为        return Arrays.equals(char1,char2);
正确的应该为            return Arrays.equals(char1,char2)&&!s.equals(t);

#### Screenshots

这是错误的提交
![image](https://user-images.githubusercontent.com/48823405/230065720-4594d702-df37-482f-9902-ca73d98a2976.png)
这是正确的提交
![image](https://user-images.githubusercontent.com/48823405/230065758-fb9ccab0-1b78-4b58-a0eb-bb16a4991e30.png)

**Comment by feiceh** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励哦。
