### ISSUE TITLE
270. 最接近的二叉搜索树值 题目有误

### ISSUE THREAD

**Issue by guitarandherandher** [LeetCode-Feedback/LeetCode-Feedback#12774]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
吉他及她

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
中文题目描述有缺陷。按照中文题目的描述，当target=3.5时，最终结果为3和4都是正确的。

**测试用例**

root = [4,2,5,1,3]
target = 3.5

**额外的上下文**

中文题目：
> 给定一个不为空的二叉搜索树和一个目标值 target，请在该二叉搜索树中找到最接近目标值 target 的数值。
> 注意：
> 给定的目标值 target 是一个浮点数
> 题目保证在该二叉搜索树中只会存在一个最接近目标值的数

英文题目：
>Given the root of a binary search tree and a target value, return the value in the BST that is closest to the target. If there are multiple answers, print the smallest.

**Comment by feiceh** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励哦。

**Comment by guitarandherandher** [comment]
leetcode.cn/u/guitarandher/

**Comment by feiceh** [comment]
收到，奖励已发放。
