### ISSUE TITLE
Problem 29 - Fastest accepted C# solution does not meet problem constraints 

### ISSUE THREAD

**Issue by ti82** [LeetCode-Feedback/LeetCode-Feedback#1277]
Your LeetCode username: TI82
Category of the bug
 Question
 Solution X
 Language

Description of the bug:
The entire point of this problem is to do division without multiplication, division, or mod operations. After finishing my submission, I reviewed the fastest solution, and it has both multiplication and division. Here is the code in question:

```
for(int bit=30; bit>=0; bit--){
            reminder *= 2; // MULTIPLICATION
            if((divisor & _highBitMask) != 0){
                reminder = reminder+1;
            }
            if(reminder >= dividend){
                reminder= reminder - dividend;
                res = res | _highBitMask;
            }
            _highBitMask = _highBitMask/2; // DIVISION
        }
```

Code you used for Submit/Run operation: N/A
Language used for code: C#
Expected behavior: Not to see multiplication or division in accepted solutions
Screenshots
Additional context:
I don't really care that this submission was faster, but it casts doubt on how solutions are evaluated within the context of each problem. Note that the quoted code above was in a separate method from the one defined in the problem, so perhaps this is why?

**Comment by lc-kay** [comment]
@ti82 When I tested the code, I received Compile Error. Can you please link me the fastest solution so I can verify this issue? Thank you!

**Comment by ti82** [comment]
Not sure how I would do that. Problem 29 (Divide two integers), C# language.

**Comment by lc-kay** [comment]
Hi @ti82 
I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@ti82 There is no way to validate if the user used mul/div or not. The point of this problem is not to just get it accepted, but also to solve it correctly. This solution is not enough to pass the interview.
