### ISSUE TITLE
Judge conflicts the Constraints - 60. Permutation Sequence

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1278]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

https://leetcode.com/problems/permutation-sequence/
60. Permutation Sequence

Constraints are given as below:
- Given n will be between 1 and 9 inclusive.
- Given k will be between 1 and n! inclusive.

Two sets of input test cases below:

	Input 1
		4
		25
	Expected
		Invalid Testcase
		terminate called after throwing an instance of 'std::out_of_range'

	Input 2
		0
		0
			0
			1
		2
		1
			2
			0
	Expected
		""
			""
		"12"
			"1212"

- Input1 expected is correct
- Input2 expected is not correct
  - When k=0 (example n=2,k=0 above), judge is expecting "1212". Ideally, it should throw "out_of_range" error similar to n=4, n=25 (or like)

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JavaScript

#### Expected behavior

- Judge should expect a wrong test case and should give a proper error or fail with some error. However, the judge expects something wrong. This is bad.
- Judge must adhere to constraints and throw a proper error, instead of expecting a vague incorrect value.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
