### ISSUE TITLE
Missing Test Case - 617. Merge Two Binary Trees

### ISSUE THREAD

**Issue by Amarthya03** [LeetCode-Feedback/LeetCode-Feedback#12783]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Test case contribution, I found a few interesting test cases which, if not already present, should be added into the test pack. Online Judge is returning correct output, it is just that if we don't have a similar test case in the test pack then we should add it.

#### Code you used for Submit/Run operation

```
class Solution {
    public TreeNode mergeTrees(TreeNode root1, TreeNode root2) {
        if(root1 == null) {
            return root2;
        }

        if(root2 == null) {
            return root1;
        }

        root1.val += root2.val;

        root1.left = mergeTrees(root1.left, root2.left);
        root1.right = mergeTrees(root1.right, root2.right);

        return root1;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Input 1 -
root1 = [1,5,8,7,null,null,9,null,null,4]

Input 2 -
root2 = [7,6,null,3,null,null,2]

Output -
[8,11,8,10,null,null,9,null,2,4]

Expected -
[8,11,8,10,null,null,9,null,2,4]

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Testcase: 
[1,5,8,7,null,null,9,null,null,4]
[7,6,null,3,null,null,2]
already exists.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
