### ISSUE TITLE
Wrong Test Case - 2439. Minimize Maximum of Array

### ISSUE THREAD

**Issue by YiJohnZhang** [LeetCode-Feedback/LeetCode-Feedback#12787]
#### Your LeetCode username
ChemiEngie  (formerly, registered as, "joblessCHEME")

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Wrong Test Case

#### Description of the bug

Testcase 17/68 is incorrect for **Problem 2439**:
Given the input `[6, 9, 3, 8, 14]`, the minimum maximum should be `9`, not `8`
Because
```js
// [6, 9, 3, 8, 14] ==Pass 1=>
// [7, 8, 5, 6, (14)] => [7, 8, 5, 10, 10] ==Pass 2 =>
// [7, 8, 7, 8, (10)] => [7, 8, 7, 9, 9]     ==Pass 3 =>
// [7, 8, 8, 8, 9]
```
Therefore the minimized maximum is "9", not "8"

#### Code you used for Submit/Run operation

```js
/**
 * @param {number[]} nums
 * @return {number}
 */
var minimizeArrayValue = function(nums) {

    let max;    // undefined init
    let flag = true;

    while(flag){

        max = undefined;
        flag = false;
    
        for(let i=0; i < nums.length; i++){

            const currElement = nums[i];
            const nextElement = nums[i+1];

            if(nextElement && (currElement + 1 < nextElement)){
                // 3, 7 => 5, 5
                // 2, 7 => 4, 5 (floor, ceil)
                nums[i] = Math.floor((currElement+nextElement)/2);
                nums[i+1] = Math.ceil((currElement+nextElement)/2);

            }

            max = (max === undefined) || (max < nums[i]) ? nums[i] : max;

        }
       
        // check if minimization still possible
        for(let i=0; i <= nums.length - 2; i++){

            if(nums[i] + 1 < nums[i+1]){
                flag = true;
                break;
            }

        }
        

    }

    return max;

};
```

#### Language used for code
JavaScript

#### Expected behavior
Testcase 17/68 is incorrect for **Problem 2439**:
Given the input `[6, 9, 3, 8, 14]`, the minimum maximum should be `9`, not `8`
Because
```js
// [6, 9, 3, 8, 14] ==Pass 1=>
// [7, 8, 5, 6, (14)] => [7, 8, 5, 10, 10] ==Pass 2 =>
// [7, 8, 7, 8, (10)] => [7, 8, 7, 9, 9]     ==Pass 3 =>
// [7, 8, 8, 8, 9]
```
Therefore the minimized maximum is "9". I am guessing that the solution used forgets to check if the last element is a possible maximum.

**Comment by YiJohnZhang** [comment]
whoops, variable naming typo, `currIndex` and `nextIndex` should have been named `currElement` and `nextElement` respectively.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
