### ISSUE TITLE
Editorial topic doesn't exist

### ISSUE THREAD

**Issue by devyas** [LeetCode-Feedback/LeetCode-Feedback#12794]
#### Your LeetCode username
devyas

#### Category of the bug
- [ ] Question
- [ yes ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

For question 145, Binary tree postorder traversal, looks like the editorial, solution is not available even for the premium user. Attaching a screenshot of the same. Hope you can see it. Thanks
![image](https://user-images.githubusercontent.com/33895772/230267207-ba559c6e-8ebf-4c7a-bd1e-14224739ee63.png)

#### Code you used for Submit/Run operation
N/A

#### Language used for code
python

#### Expected behavior
I believe the explanation/solution should have been available for this question.  

#### Screenshots

![image](https://user-images.githubusercontent.com/33895772/230267210-b13129e7-2792-4116-b589-a0612f845ead.png)

**Comment by LC-Pam** [comment]
Hi there, thank you for reaching out to us. The solution page working correctly. Please clean your 
<img width="708" alt="Screen Shot 2023-04-06 at 2 03 23 PM" src="https://user-images.githubusercontent.com/103138242/230459985-fa44f4c8-8542-4b51-95ec-3afb84104613.png">
browser history and cookies, then refresh the page. Thank you.
