### ISSUE TITLE
Missing Testcase - 1629. Slowest Key

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1279]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Below test case fails in the below code:

	Your input
		[1,2,3]
		"aba"
	Output
		"a"
	Expected
		"b"
	Wrong Answer

- Please add the above test case to the Judge.

#### Code you used for Submit/Run operation

Code at https://leetcode.com/problems/slowest-key/discuss/909015/c-easy-on-commented/744583

```
   char slowestKey(vector<int>& R, string K) {
        char ans = K[0];
        int t , maxDuration  =R[0]; 
        for(int i =  1 ; i < R.size() ; i++){
            if(R[i]-R[i-1] >= maxDuration){ //  if the keypress is longer
                
                if((maxDuration == R[i] - R[i-1]) and ans < K[i])// same duration check ascii value
                    ans = K[i];
                else ans = K[i]; // update directly
                maxDuration = R[i] - R[i-1];  // update max keypress duration
            }
        }
        return ans; //return answer

    }
```

#### Language used for code
C++

#### Expected behavior

- The question must have a good number of test cases, to stop wrong answers from being Pass & posting them in discussion for the community.

**Comment by lc-kay** [comment]
@manoharreddyporeddy The problem was updated recently and this solution gets WA now, therefore, this test case was not added. Thank you for your time!
