### ISSUE TITLE
[剑指 Offer II 006. 排序数组中两个数字之和]题目描述问题

### ISSUE THREAD

**Issue by Chen823** [LeetCode-Feedback/LeetCode-Feedback#12798]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名
旷家帮喽啰
**Bug 类型**
- [✔ ] 题目

**描述**
[剑指 Offer II 006. 排序数组中两个数字之和](https://leetcode.cn/problems/kLl5u1/)
这道题中的提示 numbers 按 递增顺序 排列
但是测试用例中有[0,0,3,4] , 0
所以应该改为 numbers 按非递减顺序排列

**Comment by feiceh** [comment]
你好，当前题目已更新，积分奖励已发放，请查收
