### ISSUE TITLE
We should add at least some tags to all the problems or give a "untagged" tag to those doesn't have tag

### ISSUE THREAD

**Issue by idontknoooo** [LeetCode-Feedback/LeetCode-Feedback#1280]
#### Your LeetCode username
idontknoooo

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Some questions don't have a tag, and it is difficult to search for questions like this. 
For example, today's daily challenge 799 is a dynamic programming and Math problem, but there is no tag on it. https://leetcode.com/problems/champagne-tower/ 
This is bad because there is no way to filter out this question from the main search bar using the **tag** filter (https://leetcode.com/problemset/all/).

I'd suggest we either tag everything or give an **untagged** tag to those which haven't been tagged yet.

#### Code you used for Submit/Run operation

```
This is not a question bug, it's a global bug. I believe there are about 100 or more questions that don't have a tag at all.
```

**Comment by lc-kay** [comment]
Hi @idontknoooo 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@idontknoooo We have added a tag to this problem. Thank you for your time!
