### ISSUE TITLE
Missing Test Case - 1059. All Paths from Source Lead to Destination

### ISSUE THREAD

**Issue by akanksha102** [LeetCode-Feedback/LeetCode-Feedback#12808]
#### Your LeetCode username
akshagupta29992

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
Missing test case for checking cycles within graph

#### Code you used for Submit/Run operation

```
class Solution {
    Map<Integer,Queue<Integer>> hm = new HashMap<Integer,Queue<Integer>>();
    Set<Integer> set = new HashSet<Integer>();
    boolean visited[] = new boolean[1];
    public boolean leadsToDestination(int n, int[][] edges, int source, int destination) {
        if (edges.length == 0) return n==1;
        if (source == destination) return false;
        for (int[] edge : edges) {
            if (edge[0] == destination) return false;
            Queue<Integer> l = hm.get(edge[0]);
            if (l == null) {
                l = new LinkedList<Integer>();
                l.add(edge[1]);
                hm.put(edge[0],l);
            } else {
                l.add(edge[1]);
            }
        }
        visited = new boolean[n];
        return dfs(source, destination);
    }
    boolean dfs(int source, int destination) {
        Queue<Integer> nodes = hm.get(source);
        if (nodes == null) {
            return source == destination;
        }
        if (nodes.size()==0) {
            if (source != destination) return set.contains(source);
        } else {
            visited[source] = true;
            while (nodes.size()>0) {
                int val = nodes.poll();
                if (visited[val] == true) return false;
                if (dfs(val, destination) == false) {
                    return false;
                }
            }
            visited[source] = false;
            set.add(source);
        }
        return true;
    }
}
```

#### Language used for code
Java

#### Expected behavior
I had expected that there would be test cases to detect cycles in the graph, but they passed the [code](https://leetcode.com/submissions/detail/929312946/?from=explore&item_id=3951)  which was not checking for cycles in the graph. Need to add the following test case to check for the cycle.
5
[[0,1],[0,3],[1,2],[1,3],[2,4],[4,1]]
0
3

#### Screenshots

<img width="1455" alt="Screenshot 2023-04-07 at 5 35 53 AM" src="https://user-images.githubusercontent.com/16864878/230515074-6dccaa22-d9e7-4f2b-bc7b-c82daa7e47dd.png">

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

5
[[0,1],[0,3],[1,2],[1,3],[2,4],[4,1]]
0
3

already exists

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
