### ISSUE TITLE
Incorrect test case found for Question - 49. Group Anagrams

### ISSUE THREAD

**Issue by namankhurpia** [LeetCode-Feedback/LeetCode-Feedback#12804]
#### Your LeetCode username
[namankhurpia2](https://leetcode.com/namankhurpia2/)

#### Category of the bug
- [X ] Missing Test Cases - Incorrect Test Case

#### Description of the bug

Question - 49. Group Anagrams
The question mentions that you can return the answer in any order, and I m getting testcase failed even after returning correct output, refer the screenshot for proof.
![Screenshot 2023-04-06 at 3 24 31 PM](https://user-images.githubusercontent.com/30630783/230476565-e1bf0bb7-6931-4547-b7bd-fe8088d1c7b2.png)

#### Code you used for Submit/Run operation

My code - 
```
class Solution {
    public List<List<String>> groupAnagrams(String[] strs) {

        HashMap<String,ArrayList<String>> map = new HashMap<>();
        for(String s:strs)
        {
            
            int count [] = new int[26];
            String str = "";
            for(int i=0;i<s.length();i++)
            {
                count[s.charAt(i)-'a'] += 1;
            }
            str = converttoString(count);
            
            if(map.containsKey(str))
            {
                ArrayList<String> str2 = map.get(str);
                str2.add(s);
                map.put(str,str2 );
            }
            else
            {
                ArrayList<String> list2 = new ArrayList<>();
                list2.add(s);
                map.put(str,list2);
            }
  
            
        }
        ArrayList<List<String>> res = new ArrayList<List<String>>(map.values());
        return res;
        
    }



    public static String converttoString(int [] count)
    {
        String res = "";
        for(int i=0;i < count.length;i++)
        {
            res = res+count[i];
        }
        return res;
    }
}

```

#### Language used for code
Java

#### Expected behavior

The expected behavior would be, it accepts the test case, attaching screenshot below

#### Screenshots

screenshot attached
![Screenshot 2023-04-06 at 3 24 31 PM](https://user-images.githubusercontent.com/30630783/230476626-cb8e572c-b881-49c4-8d99-a3eedf8a4687.png)

#### Additional context

no comments

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

**Comment by namankhurpia** [comment]
lol, did you not understand the issue?

It was pretty clear and the judger still doesnt work.
