### ISSUE TITLE
测试用例有错误

### ISSUE THREAD

**Issue by Wzzzx** [LeetCode-Feedback/LeetCode-Feedback#1281]
** Bug 类型**
- [x] 题目 
- [ ] 题解
- [ ] 编程语言

**描述**
使用下述测试用例，答案输出的结果为`false`，但应该为`true`

**你使用的语言**
C++

**你提交或者运行的代码**

**期望行为**

期望输出`true`

**屏幕截图**

**额外的上下文**

**Comment by feiceh** [comment]
感谢反馈，请按照本文中提到的格式分享题号及代码，把信息提供完整才能有助于快速验证和精准的定位这个问题。
