### ISSUE TITLE
Missing Test Case - 997. Find the Town Judge

### ISSUE THREAD

**Issue by Rakshank-Verma** [LeetCode-Feedback/LeetCode-Feedback#12817]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- Missing Test Cases 

This is the testcase - 
**Input: n = 4, trust = [[1,3], [2,3], [4,2]]
Output: -1**
which i think should be there to help people understand that if any person does not trust the judge than it cannot be the judge of the town. This should be included in the example testcases.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
