### ISSUE TITLE
Missing Test Case - 3. Longest Substring Without Repeating Characters

### ISSUE THREAD

**Issue by KumarSampurn** [LeetCode-Feedback/LeetCode-Feedback#12822]
#### Your LeetCode username

_Epsilon

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Testcase not following the substring definition given in question.

In the definition of question , there is a definition of substring and the definition of substring by the question is <em>A substring is a contiguous non-empty sequence of characters within a string.</em>

But in the Test Case #340 
Given String = " " 
Expected output= 1

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int lengthOfLongestSubstring(string s) {
        vector<int> frequencyTable(255, 0);
        int maxLength=0,runningLength=0;
        for(int i=0;i<s.length();i++){
            if(frequencyTable[s[i]] || isspace(s[i])){
                std::fill(frequencyTable.begin(), frequencyTable.end(), 0);
                maxLength=max(maxLength,runningLength);
                runningLength=0;
            }
            runningLength++;
            frequencyTable[s[i]]++;
        }
        return maxLength;
    }
};
```

#### Language used for code
C++

#### Expected behavior
Output should have been 0
As a empty string has been given.

#### Screenshots

![image](https://user-images.githubusercontent.com/101011193/230641759-954c7762-e300-4bed-9584-2b3d2b685c1b.png)
![image](https://user-images.githubusercontent.com/101011193/230641836-ae3e734b-c3e0-48ad-bf04-3585b414c428.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
