### ISSUE TITLE
Typo in the description - 1558. Minimum Numbers of Function Calls to Make Target Array

### ISSUE THREAD

**Issue by alantudyk** [LeetCode-Feedback/LeetCode-Feedback#12823]
#### Your LeetCode username
0x81

#### Description of the bug
https://leetcode.com/problems/minimum-numbers-of-function-calls-to-make-target-array/description/
> You want to use the modify function to covert

Should be "convert".

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
