### ISSUE TITLE
Typo in Example 2 - 1509. Minimum Difference Between Largest and Smallest Value in Three Moves

### ISSUE THREAD

**Issue by cadenlu** [LeetCode-Feedback/LeetCode-Feedback#12824]
#### Your LeetCode username
cadenlu

#### Description of the bug
In Example 2, the explanation section "After performing 3 moves, the difference between the minimum and maximum is 1 - 0 = 0." should be changed to "After performing 3 moves, the difference between the minimum and maximum is 1 - 0 = **1**."

#### Screenshots
<img width="703" alt="Screenshot 2023-04-07 at 9 57 28 AM" src="https://user-images.githubusercontent.com/96642163/230647577-b5ac33e1-ffb4-4321-a793-59e6080dea6f.png">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
