### ISSUE TITLE
Request to convert Easy to Medium - 447. Number of Boomerangs

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1282]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

https://leetcode.com/problems/number-of-boomerangs/
447. Number of Boomerangs

Convert this Easy problem to Medium because of the following reasons:

- Even when the problem is old (problem number 412), the number of 'discuss' posts are only 218, so 52.1% Acceptance Rate here only means many did not attempt it as it is not easy to do.

- Involves Math - The first formula needed is the distance between 2 points

- Involves Math - The second tricky formula involved (val*(val-1)) check the below link:
  - https://leetcode.com/problems/number-of-boomerangs/discuss/126604/For-people-who-don't-know-why-we-need-this-line%3A-res-%2B-val-*-(val-1)
  - https://leetcode.com/problems/number-of-boomerangs/discuss/127076/Description-is-not-correct-or-complete

- It is very difficult to create tests for this. Unless there are at least 5 points & also the right ones, we fail unless the val(val-1) is already known to us.

- Some other Mediums are much easier than this.

#### Code you used for Submit/Run operation

```
```

#### Expected behavior

- Easy problems must not have (multiple Math formulas + difficult to create tests)
  - Having so takes more time to write code & test
  - The more time invested in solving an Easy problem - is not a good way to value the User time.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
