### ISSUE TITLE
560. Subarray Sum Equals K

### ISSUE THREAD

**Issue by Miladinho** [LeetCode-Feedback/LeetCode-Feedback#1283]
#### Category of the bug
- [ ] Question
- [ x] Solution
- [ ] Language

#### Description of the bug
My javascript code n^2 time 1 space works jsut fine, but the same exact algo written in python3 gets a "time limit exceeded" error, what is up with that?!

#### Code you used for Submit/Run operation

```
// Python
class Solution:
    def subarraySum(self, nums: List[int], k: int) -> int:
        count = 0
        n = len(nums)
        for i in range(n):
            sum = nums[i]
            for j in range(i + 1, n):
                if sum == k:
                    count += 1
                sum += nums[j]
            if sum == k:
                count += 1
        return count
```
```
//Javscript
var subarraySum = function(nums, k) {
    let subArrays = 0
    for (let i = 0; i <nums.length; i++) {
        let sum = nums[i]
        for (let j = i + 1; j < nums.length; j++) {
            if (sum === k)
                subArrays++
            sum += nums[j]
        }
        if (sum === k)
            subArrays++
    }
    return subArrays
};
```

#### Language used for code
Python and Javascript

#### Expected behavior
Both the Python code and the Javascript code for the N^2 solution (with O(1) space) should run without time limit errors

**Comment by lc-kay** [comment]
Hi @Miladinho 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@Miladinho We have added some test cases to fail this solution, but still can pass. We also set custom limits forS to fail the brute force. Thank you for your time!

**Comment by Miladinho** [comment]
@lc-kay Hi this makes no sense to me, the above solution is one of the more advanced ones on your own Solutions guide, why would it be a bad solutions, for many people the DP solution is not trivial and the problem is marked as Medium, this seems very short sighted and inconsiderate from my point of view.
