### ISSUE TITLE
Poorly worded or Missing Test Case - 152. Maximum Product Subarray

### ISSUE THREAD

**Issue by RodEsp** [LeetCode-Feedback/LeetCode-Feedback#12836]
#### Your LeetCode username

RodEsp

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

This problem can have an array with a single item as an input. In such a case, it's unclear whether the solution should be the value of the single item or `0` since the problem wants a product as a solution. Returning the same number means no multiplication was done to achieve the solution therefore, the code is not returning the product of anything.

A similar thing happens when the input is an array of two items. The only product that can be calculated with two numbers is by multiplying those two numbers. So if the two-item array received has a `0` and non-zero number, then the highest possible product is `0`. But the problem expects the non-zero number to be returned as the solution.

#### Code you used for Submit/Run operation

```js
// Two Sum
/**
 * @param {number[]} nums
 * @return {number}
 */
var maxProduct = function(nums) {
    let maxProduct = null;
    let currentProduct = 0;
    for (let i = 0; i < nums.length - 1; i++) {
        currentProduct = nums[i] * nums[i + 1];
        if (currentProduct > maxProduct) maxProduct = currentProduct;
    }

    return maxProduct;
};
```

#### Language used for code

JavaScript

#### Expected behavior

I can see three possible solutions to this issue:
1. The problem needs to be reworded to specify that a subarray of a single item counts as a product of the single item multiplied by 1.
2. An example needs to the added to the body of the problem description that shows such behavior.
3. Test cases like the ones screenshotted below need to be added to make it clear that is the expected behavior when a user tests their code.

#### Screenshots
![image](https://user-images.githubusercontent.com/1084688/230736547-c031bf81-21ca-402d-9acb-fdaca9595737.png)

![image](https://user-images.githubusercontent.com/1084688/230736460-ba95ad06-c4c2-477a-998b-156848399a82.png)
![image](https://user-images.githubusercontent.com/1084688/230736467-26373783-7938-4f5c-90a6-744a03258c24.png)
![image](https://user-images.githubusercontent.com/1084688/230736470-a9ecdc12-9549-4835-8578-be365ea818bf.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

**Comment by RodEsp** [comment]
Hi @LC-Pam! 

Thanks for the response. I didn't say the judger wasn't running correctly, though. The question needs to do a better job of explaining or showing what the correct solution should be in the cases I outlined above. By definition, a product requires two numbers to compute, so you can't tell from the text of the question what the judger expects should happen when you are only provided with a single number or with two numbers and one of them is zero.
