### ISSUE TITLE
Test case missing in question no. 168

### ISSUE THREAD

**Issue by chirag-kalwani** [LeetCode-Feedback/LeetCode-Feedback#12830]
Leetcode Usename:
chiragnkalwani

Description:
I found a testcase for which my code output is wrong but the solution is getting accepted

Code:
```
class Solution {
public:
    char getChar (int a)
    {
        return a + 'A' - 1;
    }
    string convertToTitle (int A)
    {
        string ans;
        while (A > 0) {
            if (A % 26 == 0) {
                ans.push_back (getChar (26));
                A /= 27;
            } else {
                ans.push_back (getChar (A % 26));
                A /= 26;
            }
        }
        reverse (ans.begin () , ans.end ());
        return ans;
    }
};
```
Testcase:
Input: columnNumber = 943566
Output: "AYRBZ"
Correct Output: "BAQTZ"

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
