### ISSUE TITLE
Beginners Guide. 412. FizzBuzz

### ISSUE THREAD

**Issue by R3g3m** [LeetCode-Feedback/LeetCode-Feedback#12834]
#### Your LeetCode username
r3g3m

#### Category of the bug
- [ ] Question
- [ C++] Language 

#### Description of the bug
The preview of the video shows a solution of a code challenge, which may be inappropriate, if you want to solve it by yourself.
Previews in other videos show only conditions for the tasks.

#### Language used for code
C++

#### Expected behavior
Show a condition for the task on preview.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've submitted your feedback to the team. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
