### ISSUE TITLE
1629. Slowest key - Missing test case

### ISSUE THREAD

**Issue by saakshig** [LeetCode-Feedback/LeetCode-Feedback#1284]
#### Your LeetCode username

_mediocreCoder

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

1629 - Slowest key question is missing a test case for same duration of keys but different characters

#### Code you used for Submit/Run operation

```
class Solution {
public:
    char slowestKey(vector<int>& releaseTimes, string keysPressed) {
        int high = releaseTimes[0]; //duration;
        char c = keysPressed[0];
        for(int i = 1; i < releaseTimes.size(); i++) {
            //duration  = releaseTimes[i] - releaseTimes[i-1];
            if(high <= (releaseTimes[i] - releaseTimes[i-1])) {
                high = releaseTimes[i] - releaseTimes[i-1];
                c = keysPressed[i];
            }
        }
        return c;
    }
};
```

#### Expected behavior

The above code should fail for the following input
[9,12,14,18,31,44]
"diwoha"
Output - "a"
Expected output - "h"

#### Additional context

Please add the test case for the condition specified in the question
"Return the key of the keypress that had the longest duration. If there are multiple such keypresses, return the lexicographically largest key of the keypresses."

**Comment by lc-kay** [comment]
Hi @saakshig 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@saakshig This problem was updated recently, and this solution gets WA now. Therefore, we didn't add it your test case. Thank you for your time!
