### ISSUE TITLE
4. Median of Two Sorted Arrays IndexError: list index out of range

### ISSUE THREAD

**Issue by telemc97** [LeetCode-Feedback/LeetCode-Feedback#12840]
#### Your LeetCode username
tilemahosM

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Different output from IDE

#### Code you used for Submit/Run operation

```
class Solution:
    def findMedianSortedArrays(self, nums1: list[int], nums2: list[int]) -> float:
        nums3 = self.produce_sorted_array(nums1, nums2)
        n = len(nums3)
        if (n%2==0):
            median = (nums3[n//2] + nums3[n//2 - 1])/2
        else:
            median = nums3[n//2]

        return median


    def produce_sorted_array(self, nums1: list[int], nums2: list[int]) -> list[int]:
        new_size = len(nums1) + len(nums2)
        nums3=[]
        nums3=[0 for i in range(new_size)]
        i=0
        k=0
        l=0
        while i<new_size:
            if (nums1[k]<nums2[l]):
                nums3[i]=nums1[k]
                k+=1
                i+=1
            elif(nums2[l]<nums1[k]):
                nums3[i]=nums2[l]
                l+=1
                i+=1
            else: #nums1[k]==nums2[l]
                nums3[i]=nums1[k]
                nums3[i-1]=nums2[l]
                k+=1
                l+=1
                i-=2
            if (k==len(nums1)):
                nums3[i:]=nums2[l:]
                break
            if (l==len(nums2)):
                nums3[i:]=nums1[k:]
                break
        return nums3
```

#### Expected behavior
For every Test Case that the leetcode runtime showed wrong result or `IndexError: list index out of range` the IDE produces the right result with the same code.

#### Screenshots
None

#### Additional context
None

**Comment by LC-Pam** [comment]
Thank you for reaching out to us! Unfortunately, we are unable to troubleshoot the different behavior between your local IDE and the LeetCode environment.

For this issue, please raise this as a discussion post in the problem discussion section as other users may have run into the same issue and resolved it.

At LeetCode, we care about the whole learning experience that comes with each problem and we encourage users to teach and help each other to enrich their learning. In addition, we want our users to debug their code and learn from the process.

We appreciate your time and support.
