### ISSUE TITLE
Unreproducible TLE during contest

### ISSUE THREAD

**Issue by alantudyk** [LeetCode-Feedback/LeetCode-Feedback#12855]
#### Your LeetCode username
0x81

#### Description of the bug

1. (TLE) https://leetcode.com/contest/weekly-contest-340/submissions/detail/930420047/
2. (303 ms) https://leetcode.com/contest/weekly-contest-340/submissions/detail/930423061/

I've seen similar strange TLEs a few times before, but this is the first time during a contest.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
