### ISSUE TITLE
Missing Constraints - 384. Shuffle an Array

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1285]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

384. Shuffle an Array
https://leetcode.com/problems/shuffle-an-array/

Constraints are missing
- What is the range of length of nums?
- What is the range of values of elements of nums?
- What is the range of the number of calls for "shuffle" & "reset"?

#### Code you used for Submit/Run operation

```
```

#### Expected behavior

- Constraints must be given in the question
  - Without constraints, the User may get TLE error
  - Without constraints, the User would need to test more time.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
