### ISSUE TITLE
Missing Test Case - 2617. Minimum Number of Visited Cells in a Grid

### ISSUE THREAD

**Issue by Lpx0** [LeetCode-Feedback/LeetCode-Feedback#12853]
#### Your LeetCode username

justdoit2

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets WA on the following testcase:
[[1,1,1,1,4,0,0],[3,1,1,0,1,1,5],[4,1,1,1,1,0,0],[0,0,0,0,0,0,0]]

#### Code you used for Submit/Run operation

```
class Solution {

	public int minimumVisitedCells(int[][] grid) {
		int[] row = new int[grid.length], col = new int[grid[0].length];
		for (ArrayDeque<int[]> deque = new ArrayDeque<>(List.of(new int[3])); !deque.isEmpty();) {
			int[] poll = deque.poll();
			if (poll[1] == grid.length - 1 && poll[2] == grid[0].length - 1) {
				return poll[0] + 1;
			}
			for (row[poll[1]] = Math.max(row[poll[1]], poll[2] + 1); row[poll[1]] <= Math.min(grid[0].length - 1,
					poll[2] + grid[poll[1]][poll[2]]); row[poll[1]]++) {
				deque.offer(new int[] { poll[0] + 1, poll[1], row[poll[1]] });
			}
			for (col[poll[2]] = Math.max(col[poll[2]], poll[1] + 1); col[poll[2]] <= Math.min(grid.length - 1,
					poll[1] + grid[poll[1]][poll[2]]); col[poll[2]]++) {
				deque.offer(new int[] { poll[0] + 1, col[poll[2]], poll[2] });
			}
		}
		return -1;
	}
}
```

#### Language used for code

java

#### Expected behavior

Output: -1
Expected: 9

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
