### ISSUE TITLE
Incorrect category tagged for 116. Populating Next Right Pointers in Each Node

### ISSUE THREAD

**Issue by mmalu** [LeetCode-Feedback/LeetCode-Feedback#1286]
#### Your LeetCode username

manky

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

It has *Depth First Search" as a related topic. However, It should be "Breadth-First Search". It misleads to an approach that doesn't work in this case.

**Comment by mmalu** [comment]
This applies to [117. Populating Next Right Pointers in Each Node II](https://leetcode.com/problems/populating-next-right-pointers-in-each-node-ii/) as well. 

You're doing BFS in both given solutions.

**Comment by lc-kay** [comment]
Hi @mmalu 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@mmalu This is a post from the discussion which introduced a dfs solution.
https://leetcode.com/problems/populating-next-right-pointers-in-each-node-ii/discuss/521193/Python-O(1)-aux-space-DFS-sol.-85%2B-with-Diagramhttps://leetcode.com/problems/populating-next-right-pointers-in-each-node-ii/discuss/521193/Python-O(1)-aux-space-DFS-sol.-85%2B-with-Diagram
You can find similar dfs solutions for the second problem.

**Comment by mmalu** [comment]
There are also BFS solutions - the official ones are BFS based. Based on the above logic, can BFS be also added as a category? I think it would give out an additional useful and more natural hint.

**Comment by lc-kay** [comment]
@mmalu We've added the BFS tag. Thank you for your time!
