### ISSUE TITLE
Missing Test Case - 852. Peak Index in a Mountain Array

### ISSUE THREAD

**Issue by depender3801** [LeetCode-Feedback/LeetCode-Feedback#12868]
#### Your LeetCode username

Depender3801

#### Category of the bug
An array arr a mountain if the following properties hold:

arr.length >= 3
There exists some i with 0 < i < arr.length - 1 such that:
arr[0] < arr[1] < ... < arr[i - 1] < arr[i] 
arr[i] > arr[i + 1] > ... > arr[arr.length - 1]
Given a mountain array arr, return the index i such that arr[0] < arr[1] < ... < arr[i - 1] < arr[i] > arr[i + 1] > ... > arr[arr.length - 1].

You must solve it in O(log(arr.length)) time complexity.
- [ ] Solution
class Solution {
public:
    int peakIndexInMountainArray(vector<int>& arr) {
        int s=0;
        int e=arr.size()-1;
        int mid=s+(e-s)/2;
        while(s<e){
            if(arr[mid]<arr[mid+1]){
                s=mid+1;
            }
            else{
                e=mid;
            }
            mid=s+(s-e)/2;
        }
        return s; 
        
    }
};

- [ ] Language
c++
- [ ] Missing Test Cases 

#### Description of the bug

not able to submit the problem solution

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior

submission is not working properly

#### Screenshots

![image](https://user-images.githubusercontent.com/130292420/230774150-c7b8da99-76e4-4227-9513-56ea1d10bf68.png)
![image](https://user-images.githubusercontent.com/130292420/230774215-c08adf69-38c3-40f9-9a55-65a1181fcbd8.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
