### ISSUE TITLE
Missing Test Case - 657. Robot Return to Origin

### ISSUE THREAD

**Issue by varshalearner** [LeetCode-Feedback/LeetCode-Feedback#12861]
####  Your LeetCode username 
varshalearner

#### Category of the bug
- Missing Test Cases 

#### Description of the bug
My code passed every testcase, but it shouldn't have.

#### Code you used for Submit/Run operation

```
// Robot Return to Origin
class Solution {
    public boolean judgeCircle(String moves) {
        int curr = 0;
        for( int i = 0 ; i<moves.length() ; i++){
            char c = moves.charAt(i);
            if(c=='U') curr-=1;
            else if(c=='D') curr+=1;
            else if(c=='L') curr+=10;
            else curr-=10;
        }   
        if(curr == 0 ) return true;
        else return false;
    }
}
```

#### Language used for code

JAVA

#### Expected behavior
INPUT:
"DDDDDDDDDDR"
EXPECTED OUTPUT:
false
MY OUTPUT:
true

Even if the expected output from my code is different. My code was accepted , which is logically wrong.

I request the author of the question to add the testcases.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by varshalearner** [comment]
Thank you @LC-Pam to resolve the issue.
