### ISSUE TITLE
117. 填充每个节点的下一个右侧节点指针 II 测试case二叉树不完整

### ISSUE THREAD

**Issue by 18703486960** [LeetCode-Feedback/LeetCode-Feedback#12866]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
bys1999

**Bug 类型**
- [ ] 用例有问题

**描述**
描述你遇到的 bug
[117. 填充每个节点的下一个右侧节点指针 II](https://leetcode.cn/problems/populating-next-right-pointers-in-each-node-ii/)
测试用例
[1,2,3,4,5,null,6,7,null,null,null,null,8]
不是一颗树
               1
          2           3
      4      5     n    6
    7  n  n  n n  8

**你使用的语言**
Java

**你提交或者运行的代码**
```
class Solution {
    public Node connect(Node root) {
        if(root == null || root.left == null){
            return root;
        }
        root.left = connect(root.left);
        root.right = connect(root.right);
        Node left = root.left;
        Node right = root.right;
        while(left != null && right != null){
            left.next = right;
            if(left.right != null){
                left = left.right;
            } else {
                left = left.left;
            }
            if(right.left != null){
                right = right.left;
            } else {
                right = right.right;
            }
        }
        return root;
    }
}
```

**期望行为**

测试用例通过

**屏幕截图**
<img width="536" alt="image" src="https://user-images.githubusercontent.com/52404261/230764616-fa0d1b8f-e8db-481c-a17f-6561075d8f93.png">

**额外的上下文**
该测试用例形成的二叉树不是颗完整的树

**Comment by stormsunshine** [comment]
请问凭什么说这不是树？
![image](https://user-images.githubusercontent.com/12067364/230767054-a45f2d5c-95f3-4ee2-9e98-e5cea1a565c2.png)
