### ISSUE TITLE
Missing Test Case - 2617. Minimum Number of Visited Cells in a Grid

### ISSUE THREAD

**Issue by yumkam** [LeetCode-Feedback/LeetCode-Feedback#12860]
#### Your LeetCode username

yumkam

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Several published solutions was accepted, but TLE on testcase
`[99998,99997,....,1,0,0]` (full size = 100000)
[complete, ~588k](https://gist.github.com/yumkam/5fe580a58c611394a462d146564b65f3/raw/38b1d88ef74354d4bab01a20562b70bd95b58c75/gistfile1.txt)

#### Code you used for Submit/Run operation

[C++, mine, TLE](https://leetcode.com/submissions/detail/930551032/) (*not* from contest):
```C++
class Solution {
public:
    int minimumVisitedCells(vector<vector<int>>& grid) {
        const unsigned m = grid.size();
        const unsigned n = grid[0].size();
        vector<vector<bool>> visited(m, vector<bool>(n));
        unsigned depth = 1;
        queue<pair<unsigned, unsigned>> q;
        q.emplace(0, 0);
        for (;;) {
            auto l = q.size();
            if (l == 0)
                break;
            while(l--) {
                auto [i, j] = q.front();
                q.pop();
                auto g = grid[i][j];
                if (i == m - 1 && j == n - 1)
                    return depth;
                for (unsigned c = min(n, j + g + 1); c-- > j + 1;)
                    if (!visited[i][c]) {
                        visited[i][c] = true;
                        q.emplace(i, c);
                    }
                for (unsigned r = min(m, i + g + 1); r-- > i + 1;)
                    if (!visited[r][j]) {
                        visited[r][j] = true;
                        q.emplace(r, j);
                    }
            }
            ++depth;
        }
        return -1;
    }
};
```

[Some other person](https://leetcode.com/contest/weekly-contest-340/submissions/detail/930471631/) from contest, Java, TLE:
```java
class Solution {
    public int minimumVisitedCells(int[][] grid) {
        int m = grid.length;
        int n = grid[0].length;
        
        
        boolean[][] vis = new boolean[m][n];
        vis[0][0] = true;      
        PriorityQueue<int[]> pq = new PriorityQueue<int[]>((i1,i2)->i1[0]-i2[0]);
        pq.offer(new int[]{1,0,0});
        while(!pq.isEmpty()){
            int[] curr = pq.poll();
            
            int steps = curr[0];
            int i = curr[1];
            int j = curr[2];
            // System.out.println("i,j,steps:"+i+","+j+","+steps);
            if(i == m-1 && j==n-1)
                return steps;
            // if(vis[i][j])
            //     continue;
            // vis[i][j] = true;
            //right mov
            int maxSteps = grid[i][j];
            for(int k=1;k<=maxSteps && (j+k)<n;k++){
                if(vis[i][j+k])
                    continue;
                vis[i][j+k] = true;
                pq.offer(new int[]{steps+1, i, (j+k)});
            }
            
            for(int k=1;k<=maxSteps && (i+k)<m;k++){
                if(vis[i+k][j])
                    continue;
                vis[i+k][j] = true;
                pq.offer(new int[]{steps+1, (i+k), j});
            }            
            
        }
        
        return -1;
        
    }
}
```

#### Language used for code

C++
Java

#### Expected behavior

AFAIK, "new testcases that triggers TLE" does not count for contest re-judge. But still newly-submitted broken (and `O(n*m*(n+m))` is clearly broken) code should not be accepted, so at least please add this testcase after weekly contest 340 results will be finalized.

#### Additional context

For reference, [my solution from contest](https://leetcode.com/submissions/detail/930468590/) does not TLE on this test case (as it has time complexity O(nm log max(n, m)) *worst case*).

Random note: PriorityQueue based solutions passes on pure luck: common PriorityQueue implementation happens to reverse order of inserted items with equal key. Otherwise, it'd fail on existing testcases.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
