### ISSUE TITLE
Missing Test Case - 231. Power of Two

### ISSUE THREAD

**Issue by MarcusSanchez** [LeetCode-Feedback/LeetCode-Feedback#12876]
#### Your LeetCode username

Marcus_Sanchez31

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

missing test case for solution. It passes all of them but it isn't really a solution as it returns wrong answers.

#### Code you used for Submit/Run operation

```
// Power of Two
bool isPowerOfTwo(int n){
    if (n <= 0) {
        return false;
    }
    if (n >= 512) {
        if (n % 512 != 0) {
            return false;
        }
    }
    else if (n >= 256) {
        if (n % 256 != 0) {
            return false;
        }
    }
    else if (n >= 128) {
        if (n % 128 != 0) {
            return false;
        }
    }
    else if (n >= 64) {
        if (n % 64 != 0) {
            return false;
        }
    }
    else if (n >= 32) {
        if (n % 32 != 0) {
            return false;
        }
    }
    else if (n >= 16) {
        if (n % 16 != 0) {
            return false;
        }
    }
    else if (n >= 8) {
        if (n % 8 != 0) {
            return false;
        }
    }
    else if (n >= 4) {
        if (n % 4 != 0) {
            return false;
        }
    }
    else if (n >= 2) {
        if (n % 2 != 0) {
            return false;
        }
    }
    return true;
}
```

#### Language used for code

C

#### Expected behavior

The code passes all test cases when it isn't an applicable solution. For example 1536 returns true when its not a power of 2.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
