### ISSUE TITLE
A simpler solution for 117. Populating Next Right Pointers in Each Node II

### ISSUE THREAD

**Issue by mmalu** [LeetCode-Feedback/LeetCode-Feedback#1287]
#### Your LeetCode username

manky

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

It **recursively** sets the next pointers starting from *right to left* as compared to **iteratively** from *left to right* in the given solutions. I think this is much more intuitive, easier to understand, and easier to reason about the **correctness**.

#### Code you used for Submit/Run operation

```
class Solution {
    public Node connect(Node root) {
        if (root == null) return root;
        Node leftmost = root;
        while (leftmost != null) {
            leftmost = connectNextLevel(leftmost);
        }
        return root;
    }
    
    private Node connectNextLevel(Node leftmost) {
        if (leftmost == null) return null;
        Node next = connectNextLevel(leftmost.next);
        if (leftmost.right != null) {
            leftmost.right.next = next;
            next = leftmost.right;
        }
        if (leftmost.left != null) {
            leftmost.left.next = next;
            next = leftmost.left;
        }
        return next;
    }
}
```

#### Language used for code

Java

**Comment by mmalu** [comment]
[This](https://leetcode.com/problems/populating-next-right-pointers-in-each-node-ii/discuss/37811/Simple-solution-using-constant-space) iterative version is simpler and more elegant than the existing solutions. 

You've done a great job explaining it, but it could use a simpler solution to begin explaining with.

**Comment by lc-kay** [comment]
Hi @mmalu 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @mmalu 
Thank you for your time. The team reviewed your report and decided that the current solution is well-illustrated and well-voted.
