### ISSUE TITLE
Description - 2616. Minimize the Maximum Difference of Pairs

### ISSUE THREAD

**Issue by Rad0miR** [LeetCode-Feedback/LeetCode-Feedback#12879]
#### Your LeetCode username

Rad0miR

#### Category of the bug
- [X] Question
- [ ] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug

In constraints stated that 0 <= p <= (nums.length)/2. But when p = 0 than the set of all pairs is empty, therefore the set of distances also empty. What is the max value of empty set? I think it is undefined. 

#### Expected behavior

p should be >= 1.
Or the description must specify how the maximum of the empty set is determined.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
