### ISSUE TITLE
542. 01 Matrix - Typo in solution

### ISSUE THREAD

**Issue by kochetov-dmitrij** [LeetCode-Feedback/LeetCode-Feedback#12874]
#### Your LeetCode username
dkochetov

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
<img width="552" alt="Screenshot 2023-04-09 at 21 58 53" src="https://user-images.githubusercontent.com/24622840/230788947-18d9dcac-532e-476a-888a-f4c4f002d4e0.png">

Missing "+1" in the formula
```
dist[i][j]=min(dist[i][j],min(dist[i][j−1],dist[i−1][j])+1)
```
must be (just like in the provided code):
```
                                          vv 
dist[i][j]=min(dist[i][j],min(dist[i][j−1]+1,dist[i−1][j])+1)               
```

Confused me at the beginning until realised it's a typo :)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

The "min" is nested. The +1 is outside of the min, which means it is applying to both directions.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
