### ISSUE TITLE
1584.  Editorial text 

### ISSUE THREAD

**Issue by eherozhao** [LeetCode-Feedback/LeetCode-Feedback#12877]
#### Category of the bug
- [ ] Question
-  Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

1584. Min Cost to Connect All Points 
Editorial's text for code such as $$N \cdot (N-1) / 2 \approx N^2$$ dont' show correctly

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 


If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
