### ISSUE TITLE
Missing Test Case - 162. Find Peak Element

### ISSUE THREAD

**Issue by rGarikinaRajesh** [LeetCode-Feedback/LeetCode-Feedback#12882]
#### Category of the bug
- [ 7, 8, 1, 2, 3, 4, 5, 6] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution {
    public int findPeakElement(int[] arr) {
        int start=0,end=arr.length-1;

        while(start<end){
            int mid=start+(end-start)/2;
            if(arr[mid]>arr[mid+1]){
                end=mid;
            }
            else if(arr[mid]<arr[mid+1]){
                start=mid+1;
            }
        }
        return start;
    }
}

```

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

[ 7, 8, 1, 2, 3, 4, 5, 6] already exists.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
