### ISSUE TITLE
二叉树的前序遍历

### ISSUE THREAD

**Issue by yuanjs-0108** [LeetCode-Feedback/LeetCode-Feedback#1288]
** Bug 类型**
- [二叉树的前序遍历 ] 题目
- [x] 题解
- [c++ ] 编程语言

**描述**
描述你遇到的 bug

**你使用的语言**
C++

**你提交或者运行的代码**
```
class Solution {
public:
    vector<int> preorderTraversal(TreeNode* root) {
        static vector<int> ans;
        if(root != NULL) ans.push_back(root->val);
        else return ans;
        if(root->left != NULL) preorderTraversal(root->left);
        if(root->right!= NULL) preorderTraversal(root->right);
        return ans;
    }
};
```

**期望行为**
描述你期望的结果

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![image](https://user-images.githubusercontent.com/33320768/97298904-15cbcd80-188f-11eb-9298-ee3e9153728f.png)

**额外的上下文**
添加额外的上下文信息
在测试用例正常的情况下,提交会出现异常

**Comment by feiceh** [comment]
感谢反馈，该题目技术验证没有问题的，建议再仔细调试一下代码。你代码里 定义了一个 static变量用于存储结果， 导致出现这个问题，把 static 声明去掉即可。
