### ISSUE TITLE
Question 2615 already exists in other form

### ISSUE THREAD

**Issue by Vishesht27** [LeetCode-Feedback/LeetCode-Feedback#12884]
#### Category of the bug
- [ ✅] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Question 2615 already exists on the platform with other name, the questions are so much same, that even the code on one can be used on another one and be submitted successfully, having duplicate questions definitely is not a good thing. 
https://leetcode.com/problems/intervals-between-identical-elements/
The above question is the same as the contest question number 2615, and above question number is 2121

#### Code you used for Submit/Run operation

```
class Solution {
    public long[] distance(int[] nums) {
        int n=nums.length;
        long ans[]=new long[n];
        Map<Integer,List<Integer>> hm=new HashMap<>();
        for(int i=0;i<n;i++){
            if(!hm.containsKey(nums[i])){
                hm.put(nums[i], new ArrayList<>());      
            }
            hm.get(nums[i]).add(i);
            //hm.put(nums[i],  );
        }
        
        for(int key : hm.keySet()){
            List<Integer> curr= hm.get(key);
            int len=curr.size();
            long[] pre=new long[len];
            long[] suff=new long[len];
            pre[0]=0;suff[len-1]=0;
            for(int i=1;i<len;i++){
                long diff= ((int)curr.get(i)-(int)curr.get(i-1));
                long cnt= i; 
                pre[i]= pre[i-1]+ (diff * cnt);
            }
            for(int i=len-2;i>=0;i--){
                long diff= ((int)curr.get(i+1)-(int)curr.get(i));
                long cnt= len-i-1;
                suff[i]=suff[i+1]+ (diff * cnt);
                
            }
            for(int i=0;i<len;i++){
                int ind= (int)curr.get(i);
                ans[ind]= pre[i]+suff[i];
            }
        }
        
        return ans;
    }
}
```

#### Language used for code
Java

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
