### ISSUE TITLE
Missing Test Case - 2617. Minimum Number of Visited Cells in a Grid

### ISSUE THREAD

**Issue by Dikshant09** [LeetCode-Feedback/LeetCode-Feedback#12885]
#### Your LeetCode username
@hwaiting_dk

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A solution is accepted, but it fails on a test case:
```
[[1,1,1,1,1],[1,0,0,0,6],[4,0,0,0,2],[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0]]
```

#### Code you used for Submit/Run operation

```
// 2617. Minimum Number of Visited Cells in a Grid
class Solution {
public:
    int minimumVisitedCells(vector<vector<int>>& g) {
        int m = g.size(), n = g[0].size(), steps = 0;
        vector<int> max_i(n), max_j(m);
        vector<pair<int, int>> q{{0, 0}}, q1;
        while (!q.empty()) {
            ++steps;
            for (auto [i, j] : q) {
                if (i == m - 1 && j == n - 1)
                    return steps;
                for (int k = max(max_i[j], i) + 1; k < m && k - i <= g[i][j]; ++k)
                    q1.push_back({k, j});
                for (int k = max(max_j[i], j) + 1; k < n && k - j <= g[i][j]; ++k)
                    q1.push_back({i, k});
                max_i[j] = max(max_i[j], i + g[i][j]);
                max_j[i] = max(max_j[i], j + g[i][j]);
            }
            swap(q, q1);
            q1.clear();
        }
        return -1;
    }
};
```

#### Language used for code
C++

#### Expected behavior
The solution should not be accepted since it fails on a test case.

#### Screenshots
<img width="968" alt="Screenshot 2023-04-10 at 10 38 56 AM" src="https://user-images.githubusercontent.com/78208876/230831233-a79ea64a-ffbe-44cc-92b0-c84e324fa1f2.png">

<img width="648" alt="Screenshot 2023-04-10 at 10 39 12 AM" src="https://user-images.githubusercontent.com/78208876/230831237-416c9a73-f24d-4223-a554-f480115860f6.png">

#### Additional context
link to the problem: https://leetcode.com/problems/minimum-number-of-visited-cells-in-a-grid/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
