### ISSUE TITLE
Interview Crash Course - Graphs - DFS C++ example misleading

### ISSUE THREAD

**Issue by chadwhiting** [LeetCode-Feedback/LeetCode-Feedback#12880]
#### Your LeetCode username

cewhiting

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The interview crash course article titled "Graphs - DFS" has at least 2 bugs in the examples provided for Example 1: 547. Number of Provinces in C++.

The first bug demonstrates a function called "dfs". The function creates a stack that is not used and then recursively calls itself.

Here is the bad code:
```
void dfs(int node) {
    stack<int> stack;
    stack.push(node);
        
    while (!stack.empty()) {
        int node = stack.top();
        stack.pop();
        for (int neighbor: graph[node]) {
            if (!seen[neighbor]) {
                 // the next 2 lines are needed to prevent cycles
                 seen[neighbor] = true;
                 dfs(neighbor);
            }
        }
    }
}
```

Recommended fix:
```
void dfs(int node) {
    for (int neighbor: graph[node]) {
        if (!seen[neighbor]) {
            // the next line is needed to prevent cycles
            seen[neighbor] = true;
            dfs(neighbor);
        }
    }
}
```

Here are example submissions showing the differences in the articles version vs the fixed version:
https://leetcode.com/problems/number-of-provinces/submissions/930961194/ (articles version)
vs
https://leetcode.com/problems/number-of-provinces/submissions/930961348/ (correct version)

There is a 2nd bug on this page where the article attempts to show the "iterative" version of dfs. Again, if we look at the C++ implementation it is still using the recursive implementation instead of an iterative implementation.

Here is the code in question:
```
void dfs(int node) {
    stack<int> stack;
    stack.push(node);

    while (!stack.empty()) {
        int node = stack.top();
        stack.pop();
        for (int neighbor: graph[node]) {
            if (!seen[neighbor]) {
                seen[neighbor] = true;
                dfs(neighbor);
            }
        }
    }
}
```

A correct iterative example could be:

```
void dfs(int node) {
    stack<int> stack;
    stack.push(node);
  
    while (!stack.empty()) {
        int node = stack.top();
        stack.pop();
        for (int neighbor: graph[node]) {
            if (!seen[neighbor]) {
                 // the next line is needed to prevent cycles
                 seen[neighbor] = true;
                 stack.push(neighbor);
            }
        }
    }
}
```
Here's a submission showing the iterative example in full: https://leetcode.com/problems/number-of-provinces/submissions/930962405/

URL to page: https://leetcode.com/explore/interview/card/leetcodes-interview-crash-course-data-structures-and-algorithms/707/traversals-trees-graphs/4626/

#### Language used for code
C++

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
