### ISSUE TITLE
Missing Test Case - 剑指 Offer 68 - I. 二叉搜索树的最近公共祖先 LCOF

### ISSUE THREAD

**Issue by Noobbbbbbb** [LeetCode-Feedback/LeetCode-Feedback#12888]
#### Your LeetCode username

ha-ha-ha-ha-ha-haa

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Test Cases：
[3,5,1,6,2,0,8,null,null,7,4]
5
4

#### Code you used for Submit/Run operation

/**
 * Definition for a binary tree node.
 * function TreeNode(val) {
 *     this.val = val;
 *     this.left = this.right = null;
 * }
 */
/**
 * @param {TreeNode} root
 * @param {TreeNode} p
 * @param {TreeNode} q
 * @return {TreeNode}
 */
var lowestCommonAncestor = function(root, p, q) {
    let res = []
    const recur = (node,path)=>{
        if(node == null){
            return 
        }
        const arr = [...path]
        arr.unshift(node)
        if(node.val == p.val || node.val == q.val){
            res.push([...arr])
        }
        recur(node.left,arr)
        recur(node.right,arr)
        arr.shift()
    }
    recur(root,[]) 

    let pArr = res[0]
    let qArr = res[1]
    for(let i = 0; i < pArr.length; i++){
       for(let j = 0; j < qArr.length; j++){
           if(pArr[i].val == qArr[j].val ){
               return pArr[i]
           }
       }
    }

};

#### Language used for code

Javascript

**Comment by feiceh** [comment]
你好，相关团队核实后没有问题。
以上信息请悉知，本次 Ticket 将关闭。
