### ISSUE TITLE
Missing Constraints - 397. Integer Replacement

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1289]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

397. Integer Replacement
https://leetcode.com/problems/integer-replacement/

Constraints are missing
- What the range of value of `n`?

#### Code you used for Submit/Run operation

```
```

#### Expected behavior

- Constraints must be given in the question
  - Without constraints, the User may get TLE error
  - Without constraints, the User would need to test more time.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
