### ISSUE TITLE
Code submission results unmatched with sample test cases results 

### ISSUE THREAD

**Issue by SherryXiaoyingLi** [LeetCode-Feedback/LeetCode-Feedback#129]
**What kind of the bug**
- [ ] problem
- [x] solution
- [ ] language

**Describe the bug**
After I wrote my code and ran with the sample test case once, that test case generated a correct ouput value. However, when I next submitted the same code to run all test cases of the problem, I always got wrong answer, and the wrong answer was, regardless of the inputs of the current test case, the same as the sample test case's correct output value that I already ran. Further, I tried to copy the input of the test case that I was failing to the editing space where I can modify a sample test case's input, and I got correct output. It was just not happening after I click "submit" to run test cases

**what language is your code written in**
Python

**The code you submit/run**
```
// maximum average of subtree
# Definition for a binary tree node.
# class TreeNode(object):
#     def __init__(self, x):
#         self.val = x
#         self.left = None
#         self.right = None

maxAvg = -1
class Solution(object):
    def maximumAverageSubtree(self, root):
        """
        :type root: TreeNode
        :rtype: float
        """
        global maxAvg
        self.helper(root)
        return maxAvg
    
    def helper(self, root):
        global maxAvg
        if (root == None):
            return 0, 0
        left_sum, left_size = self.helper(root.left)
        right_sum, right_size = self.helper(root.right)
        avg = (left_sum + right_sum + root.val ) / (left_size + right_size + 1)
        if (maxAvg==-1 or avg > maxAvg):
            maxAvg = avg
        return left_sum + right_sum + root.val, left_size + right_size + 1
```

**Expected behavior**
When I put input [0,null,1] in the editing space for sample test case, I got 1 as output, which is correct. When I click submit, my submission fails at this test case input because the output says my code produces output 6, which is the correct output of the original sample test case's input, [5,6,1]. 

**Screenshots**

**Additional context**
This inconsistency issue also happens with some other problems I was submitting, but seems like not all of them.

**Comment by SherryXiaoyingLi** [comment]
Sorry, as I was trying longestConsequtiveSequence of binary tree problem today, I found it still not working, and the error output does not necessarily equal to my previous sample test case output. For instance, here is a screenshot of what I was experiencing. As shown the submit section shows input [1] failed, but sample test case, with input [1] edited, gives the correct output. Can someone help look into this soon? Thank you. 

<img width="1236" alt="Screen Shot 2020-04-10 at 6 30 30 PM" src="https://user-images.githubusercontent.com/36340458/79027256-8a405880-7b59-11ea-83f0-c98c0ef54d29.png">

**Comment by CooperCooperCooper** [comment]
Hi @SherryXiaoyingLi,

Thank you for reaching out to us! The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in this [ARTICLE](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.

We appreciate your time and support! If you have any other questions, please don't hesitate to let us know.
