### ISSUE TITLE
Unique Word Abbreviation

### ISSUE THREAD

**Issue by DeltaParallax** [LeetCode-Feedback/LeetCode-Feedback#12905]
#### Username

ljc239

#### Category of the bug
- [ ] Question
- [ X ] Solution
- [ ] Language
- [ X ] Missing Test Cases 

#### Description of the bug

Test case seems to be incorrect on Unique Word Abbreviation in Hash Tables Explore Card. Please let me know if I have misread the question.

#### Code you used for Submit/Run operation

```
class ValidWordAbbr:
    def generateKey(self, string):
        if len(string) < 3:
            return string
        
        thing = string[0] + str(len(string) - 2) + string[-1];
        return thing

    def __init__(self, dictionary: List[str]):
        self.words = {}
        for word in dictionary:
            key = self.generateKey(word)
            if key in self.words:
                self.words[key].append(word)
            else:
                self.words[key] = [word]

    def isUnique(self, word: str) -> bool:
        key = self.generateKey(word)
        return key not in self.words or (key in self.words and word in self.words[key])
```

#### Language used for code

Python 

#### Expected behavior

For the following testcase:
```
# ["ValidWordAbbr","isUnique","isUnique","isUnique","isUnique"]
# [[["deer","door","cake","card"]],["dear"],["door"],["cart"],["cake"]]
```
`isUnique("door")` fails here.
```
Output of my code:
[null,false,true,true,true]
Expected output from the test case:
[null,false,false,true,true]
```

`boolean isUnique(string word)` Returns true if either of the following conditions are met (otherwise returns false):
- There is no word in `dictionary` whose abbreviation is equal to `word`'s abbreviation. `NOT MET, (key not in self.words) returns False`
- For any word in `dictionary` whose abbreviation is equal to `word`'s abbreviation, that word and `word` are the same. `MET, (key in self.words and word in self.words[key]) returns True`

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
