### ISSUE TITLE
Incomplete Constraints - 676. Implement Magic Dictionary

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1290]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

676. Implement Magic Dictionary
https://leetcode.com/problems/implement-magic-dictionary/

Constraints have below:
- At most 100 calls will be made to search.

Test case:

	Input:
		["MagicDictionary",   "buildDict" ]
		[[],                              [["h"]]     ]

	Output:
		Invalid Testcase
		expected 'Total calls made' to have value from 1 to 100 only

Why the error - constraints of "at most" is satisfied?

Please change Constraints from:
-  From: At most 100 calls will be made to search.
-  To:     1 to 100 calls will be made to search.

#### Code you used for Submit/Run operation

```
```

#### Expected behavior

- Here lower bound is missing.
  - Testcase generation is already cumbersome for Class-based questions, and with this missing point, more User time is wasted.

- Constraints must have both lower & upper bounds.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. After reviewing the constraints of the problem, we've concluded that the constraints are already correct. Error "'Total calls made' to have value from 1 to 100 only" is already implied in the first two constraints and this is the standards of the design problems.
