### ISSUE TITLE
Typo in 2390. Removing Stars From a String editorial

### ISSUE THREAD

**Issue by hhubert14** [LeetCode-Feedback/LeetCode-Feedback#12904]
#### Your LeetCode username

user9664Z

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the editorial code for the stack solution, !answer.isEmpty() should be !st.isEmpty() and the code is missing a closing curly bracket.

#### Code you used for Submit/Run operation

```
class Solution {
    public String removeStars(String s) {
        Stack<Character> st = new Stack<>();
        for (int i = 0; i < s.length(); i++) {
            if (s.charAt(i) == '*') {
                st.pop();
            } else {
                st.push(s.charAt(i));
            }
        }

        StringBuilder answer = new StringBuilder();
        while (!answer.isEmpty()) {
            answer.append(st.pop());
        }

        return answer.reverse().toString();
}
```

#### Language used for code

Java

**Comment by saikumar8639** [comment]
gundeboinasaikumar


Solution in python:

class Solution:
    def removeStars(self, s: str) -> str:
        arr=[]
        for i in s:
            if i=="*":
                arr.pop()
            else:
                arr.append(i)
        return "".join(arr)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
