### ISSUE TITLE
Missing Test Case - 1020. Number of Enclaves

### ISSUE THREAD

**Issue by telemc97** [LeetCode-Feedback/LeetCode-Feedback#12903]
#### Your LeetCode username
tilemahosM

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
For test case : `[[0,0,0,1,1,1,0,1,0,0],
              [1,1,0,0,0,1,0,1,1,1],
              [0,0,0,1,1,1,0,1,0,0],
              [0,1,1,0,0,0,1,0,1,0],
              [0,1,1,1,1,1,0,0,1,0],
              [0,0,1,0,1,1,1,1,0,1],
              [0,1,1,0,0,0,1,1,1,1],
              [0,0,1,0,0,1,0,1,0,1],
              [1,0,1,0,1,1,0,0,0,0],
              [0,0,0,0,1,1,0,0,0,1]]` my code outputs 2 but the platform states that the correct answer is 3 yet, visually the correct answer is 2.

#### Code you used for Submit/Run operation

```
class Solution:
    def numEnclaves(self, grid: List[List[int]]) -> int:
        max_steps = 0
        for i in range(len(grid)):
            for j in range(len(grid[0])):
                if (grid[i][j]==1):
                    found=[0,0]
                    found = self.explore(grid, found, i, j)
                    if (found[0]>max_steps and found[1]==0): max_steps = found[0]
        return max_steps

    def explore(self, grid, found_, x,y)->int:
        if (x>=0 and y>=0 and x<=len(grid)-1 and y<=len(grid[0])-1 and grid[x][y]==1):
            if (x==0 or y==0 or x==len(grid)-1 or y==len(grid[x])-1):
                found_[1]=1
            found_[0]+=1
            grid[x][y]=2
            found_=self.explore(grid, found_, x,y+1)
            found_=self.explore(grid, found_, x+1,y)
            found_=self.explore(grid, found_, x,y-1)
            found_=self.explore(grid, found_, x-1,y)

        return found_
```

#### Expected behavior
Correct answer is 2 not 3

#### Screenshots
![bug](https://user-images.githubusercontent.com/57395320/231007677-453c5d08-fccd-453c-8e22-9bb9c7cb523c.png)

#### Additional context
no additional context

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
