### ISSUE TITLE
Missing Test Case - 2614. Prime In Diagonal

### ISSUE THREAD

**Issue by simplesukant** [LeetCode-Feedback/LeetCode-Feedback#12909]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by shit-eater** [comment]
What is the missing case and what is the wrong solution? Please do not create meaningless issue!
