### ISSUE TITLE
Missing Test Case - 2206. Divide Array Into Equal Pairs

### ISSUE THREAD

**Issue by ByeongsuPark** [LeetCode-Feedback/LeetCode-Feedback#12908]
#### Your LeetCode username

ByeongsuPark

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

There is a missing test case in the problem

#### Code you used for Submit/Run operation

```java
class Solution {
    public boolean divideArray(int[] nums) {
        // HashMap<Integer, Integer> map = new HashMap<>();

        // for (int i : nums) map.put(i, map.getOrDefault(i, 0) + 1);
        // for (int i : map.keySet()) {
        //     if (map.get(i) % 2 != 0) return false;
        // }
        // return true;

        int j = 0;
        for(int i = 0; i<nums.length; i++){
            int bit = 1<<nums[i]; 
            j = j ^ bit;      
        }

        if(j != 0){
                return false;
            }
        return true;
        
    }
}
```

#### Language used for code

Java

#### Expected behavior

When test case is ```[500,500,500,500,499,499,20,52]```, the code that I write above should be rejected.
But It passed.
You can check it by the screenshots that I attached below.

#### Screenshots

<img width="1508" alt="image" src="https://user-images.githubusercontent.com/39683194/231066958-8a354262-6627-4312-9326-30161e2292d5.png">

You can see that the test case is given for the code, the solution is rejected.

However, When submitting the code, it is accepted.

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/39683194/231067659-48ac99cf-eca2-47e3-b873-d409e5198cf3.png">

#### Additional context

The problem of the code that I submit is that it cannot use bitmask to check the number of appearance the number in ```nums``` because the range of ```nums[i]``` is way more larger than bitmask's capacitiy (which is ```int``` or ```long```).
The test case to check this point should be added

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
