### ISSUE TITLE
Missing Test Case - 162. Find Peak Element

### ISSUE THREAD

**Issue by aayush-karki** [LeetCode-Feedback/LeetCode-Feedback#12902]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Marks wrong answer as correct. For test case [2,1,2,3,4,5,6] accepts the output of the binary search algorithm--6 while expected output is 0. 

#### Code you used for Submit/Run operation

```
// 162. Find Peak Element
class Solution {
public:
    int findPeakElement(vector<int>& nums) {
        int left = 0;
        int right = nums.size() - 1;
        while(left < right)
        {
            int mid = left + (right -left) / 2;
            if(nums.at(mid) < nums.at(mid + 1))
            {
                left = mid + 1;
            }
            else 
            {
                right = mid;
            }
        }   

        return left;
    }
};
```

#### Expected behavior

should mark 6 as wrong as wrong answer for test case [2,1,2,3,4,5,6]

#### Screenshots

![image](https://user-images.githubusercontent.com/68620206/230998171-d2b7056b-1aac-40ba-8920-c6ef188de755.png)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

The judger appears to be running correctly.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
