### ISSUE TITLE
 Missing Test Case - 4. Median of Two Sorted Arrays

### ISSUE THREAD

**Issue by Michael-D-Santos** [LeetCode-Feedback/LeetCode-Feedback#12912]
#### Your LeetCode username
[https://leetcode.com/Michael-D-Santos/](Michael-D-Santos)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Although the code I have produced is proper, I have been told my answer is wrong for the testcase where nums1 = [1, 2], and nums2 = [3, 4], and that the output given was 2.0, and not the expected output, 2.5. To make sure I was actually wrong, I ran my code through VSCode and a few websites to check if that would still be the case there, but I was given the correct answer both times. Therefore, the program I have written is just fine, but there seems to be some issue going on from LeetCode's side.

#### Code you used for Submit/Run operation

```python
import numpy as np

class Solution(object):
    def findMedianSortedArrays(self, nums1, nums2):
        new_array = np.unique(nums1 + nums2)
        count = len(new_array)
        if (count % 2 == 1):
            return new_array[count // 2]
        else:
            higher = new_array[count // 2]
            lower = new_array[(count // 2 ) - 1]
            return (higher + lower) / 2
```

#### Language used for code
Python

#### Expected behavior
The actual output that the program gave should have been returned (2.5) and not a false output (2.0), allowing the problem to be solved, instead of an error message of a wrong answer being returned. There's no reason why an output of 2.0 would be given, as just by looking at the code, it is clear that won't be returned at all.

* [1, 2], [3, 4] becomes [1, 2, 3, 4], which has an even amount of elements, running the code in the else block
* since 4/2 is 2, and 2 - 1 is 1, the 2nd element and 1st element of the new array will be stored in separate variables, containing the values 3 and 2, respectively
* the average of 3 and 2 is calculated, resulting in (3 + 2) / 2 = 2.5, the expected output

#### Screenshots
![image](https://user-images.githubusercontent.com/78511249/231138217-b6a6d6df-11ca-4909-b379-9a2877c39937.png)
![image](https://user-images.githubusercontent.com/78511249/231138895-1c77a2a3-6a5a-418f-aeb2-eda315ac13a7.png)
![image](https://user-images.githubusercontent.com/78511249/231139026-a36225b9-2323-40d0-901a-285246090288.png)
![image](https://user-images.githubusercontent.com/78511249/231139151-6bc615d7-955a-4a1d-a9bd-aaf878ab6422.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
