### ISSUE TITLE
Missing Test Case - 1041.Robot Bounded In Circle

### ISSUE THREAD

**Issue by MikeAlwaysCode** [LeetCode-Feedback/LeetCode-Feedback#12915]
#### Your LeetCode username

https://leetcode.cn/u/mikeac/

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A wrong submit code could be accepted.

#### Code you used for Submit/Run operation

```
class Solution:
    def isRobotBounded(self, instructions: str) -> bool:
        d = dirs = 0
        for c in instructions:
            if c == "G":
                d += 1 if dirs % 4 < 2 else -1
            else:
                dirs += 1 if c == "R" else -1
        return d == 0 or dirs % 4 != 0
```

#### Language used for code

Python3

#### Expected behavior

The code submitted above should be incorrect.
Use the test case: "GRGRGGRR"
Actually the answer should be "False", but return "True.

#### Screenshots

![11](https://user-images.githubusercontent.com/110583124/231197083-6e49eba2-5ade-4673-9ec2-3f3601db6817.jpg)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output values.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. 

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
