### ISSUE TITLE
Missing Constraints - 153. Find Minimum in Rotated Sorted Array

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1291]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

153. Find Minimum in Rotated Sorted Array
https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/

Constraints are missing

- What is the range of the length of nums array?
- What is the range of values of elements of nums array

#### Code you used for Submit/Run operation

```
```

#### Expected behavior

- In the last 4 months, more than 1/2 of my time is gone into testing various big test cases (constraints not given case) that can give TLE error :)

- The question must have constraints

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
