### ISSUE TITLE
题目1989的文字描述有缺失

### ISSUE THREAD

**Issue by zouyu9631** [LeetCode-Feedback/LeetCode-Feedback#12927]
**你的 LeetCode 用户名**
FreeYourMind

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
https://leetcode.cn/problems/maximum-number-of-people-that-can-be-caught-in-tag/
题目描述中的示例3，表述缺失
解释:
没有 “鬼” 来zh

**期望行为**
补全文字描述：
解释:
没有 “鬼” 来抓人

**屏幕截图**
![image](https://user-images.githubusercontent.com/6801919/231368696-17e864c2-0a77-447b-a868-7d4473b4b30b.png)

**Comment by feiceh** [comment]
你好，当前题目描述已更新，积分奖励已发放，请查收
