### ISSUE TITLE
Missing Test Case - 2390. Removing Stars From a String

### ISSUE THREAD

**Issue by pj-op** [LeetCode-Feedback/LeetCode-Feedback#12921]
#### Category of the bug
Missing Test Cases 

#### Description of the bug

In this problem if the input string starts with `*` then the output should exclude the initial `*` character and return the rest part of the string.
For Example: 
- Input String s ="`*abc`" then expected output should be `abc`
- Input String s= "`*abc**`" then expected output should be `a`

#### Code you used for Submit/Run operation

- Below code works fine with the above test cases.
```
// Two Sum
class Solution {
public String removeStars(String s) {
        Stack<Character> stack = new Stack<>();
        StringBuilder sb = new StringBuilder();
        for (char c : s.toCharArray()) {
            if (c != '*') {
                stack.add(c);
            } else if (!stack.isEmpty()) {
                stack.pop();
            }
        }
        while (!stack.isEmpty()){
            sb.append(stack.pop());
        }
        return sb.reverse().toString();
    }
}
```
- But below code which is written in C++ doesn't work with the above test cases.
```
class Solution {
  public: string removeStars(string s) {
    int j = 0;
    for (int i = 0; i < s.size(); i++) {
      if (s[i] == '*') {
        j--;
      } else {
        s[j] = s[i];
        j++;
      }
    }
    return s.substr(0, j);
  }
};
```

#### Expected behavior

- If the input string starts with `*` then it should be ignored
- There can be many stars at the starting of string so all should be ignored

#### Screenshots

- Please refer below snapshot where testcase 1 and testcase 4 doesn't even consider:-

![image](https://user-images.githubusercontent.com/89000385/231260329-b5dc9678-7000-40c5-9714-247a3a7de61b.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The C++ code submission code since above code received Compile Error after submitted: https://leetcode.com/submissions/detail/932708470/

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by pj-op** [comment]
hi @LC-Pam Thanks for the update. As I checked in the C++ code it was missing an semicolon at last. I added it and also submitted the C++ solution which got accepted.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Invalid test case.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
