### ISSUE TITLE
Missing Test Case - 724. Find Pivot Index

### ISSUE THREAD

**Issue by Kleanthismits** [LeetCode-Feedback/LeetCode-Feedback#12922]
#### Your LeetCode username

kleanthis

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
There should be a case where the pivot exists at the last index of the array. 
The test cases only cover the first index pivot.

Example test case input:
`nums = [5, -3, -2, 4]`

#### Language used for code

Ruby

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
