### ISSUE TITLE
Missing Test Case - 71. Simplify Path

### ISSUE THREAD

**Issue by iamakhileshmishra** [LeetCode-Feedback/LeetCode-Feedback#12924]
#### Category of the bug

- [ ] Missing Test Cases 

#### Description of the bug

To understand the problem there should be one test more case i.e. /a/b/../../c/ for which output will be /c 
This test case will help everyone to understand the problem bettter and think the correct approach.

#### Code you used for Submit/Run operation

```

class Solution {
    public String simplifyPath(String path) {
        Stack<String> s = new Stack<>();
        StringBuilder res = new StringBuilder();
        String[] p =path.split("/");
        
        for(int i=0;i<p.length;i++){
            if(!s.isEmpty()  && p[i].equals("..")) s.pop();
            else if(!p[i].equals("") && !p[i].equals(".") && !p[i].equals(".."))
                s.push(p[i]);
        }
        
        
        if(s.isEmpty()) return "/";
        while(!s.isEmpty()){
            res.insert(0,s.pop()).insert(0,"/");
        }
        
        return res.toString();
    }
}
```
Code approach is taken from the user with username - [hi-malik](https://leetcode.com/hi-malik/)

#### Language used for code
C++

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

The above code received Compile Error: https://leetcode.com/submissions/detail/932709671/

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
