### ISSUE TITLE
Missing Test Case - 350. Intersection of Two Arrays II

### ISSUE THREAD

**Issue by Klewik-Kanel** [LeetCode-Feedback/LeetCode-Feedback#12925]
#### Your LeetCode username
kaustubhpandey812

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
The number or integer when detected once as an intersection should be removed from the array for the solution to be correct in all true sense. But, replacing the number at that index with 0 works as a solution. Thus indicating that there is a missing testcase which will need the values inside the arrays to be 0. So as to avoid solution which work with the loophole such as mine.

#### Code you used for Submit/Run operation
```
// Intersection of Two Arrays
class Solution {
    public int[] intersect(int[] nums1, int[] nums2) {
        Arrays.sort(nums1);
        Arrays.sort(nums2);
        ArrayList<Integer> arr = new ArrayList<>();
        int count = 0;
        for(int i = 0; i<nums1.length;i++){
            for(int j = 0;j<nums2.length;j++){
                if(nums1[i]==nums2[j]){
                    arr.add(nums1[i]);
                    count++;
                    nums2[j] = 0;
                    break;
                }
            }
        }
        int[] res = new int[arr.size()];
        for (int i=0, len = arr.size(); i < len; i ++){
            res[i] = arr.get(i);
        }
        return res;
    }
}
```

#### Language used for code
java

#### Expected behavior
The test should have failed, indicating that when we replace the number with zero, there might be a possibility of getting that in the third array as an intersection of another 0 present in the arrays.

#### Additional context
 x

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
