### ISSUE TITLE
题目难度标定不一致

### ISSUE THREAD

**Issue by Ijustwantyouhappy** [LeetCode-Feedback/LeetCode-Feedback#1292]
** Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
- [剑指 Offer 04. 二维数组中的查找](https://leetcode-cn.com/problems/er-wei-shu-zu-zhong-de-cha-zhao-lcof/) easy
- [240. 搜索二维矩阵 II](https://leetcode-cn.com/problems/search-a-2d-matrix-ii/) medium

这两道题目一样，但难度标定的不一致，望修正。建议都调整为easy，算不上medium。

**Comment by feiceh** [comment]
难度已均为中等了，ID：a_run 给予积分奖励，请查收。
