### ISSUE TITLE
Missing Constraints in 228. Summary Ranges

### ISSUE THREAD

**Issue by Mohitkumar6122** [LeetCode-Feedback/LeetCode-Feedback#1293]
#### Your LeetCode username
Mkay6122

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<string> summaryRanges(vector<int>& nums) {
        vector < string > ans ;
        int n = nums.size() ;
        if (!n) return ans ;
        nums.push_back(nums.back()) ;
        n++ ;
        int mn = nums[0], mx = INT_MIN ;
        for(int i = 1; i < n ; i++){
            cout << nums[i] ;
            if (nums[i] == nums[i - 1]) goto pq ;
            if (nums[i] ==1  + nums[i - 1]) mx = nums[i] ;
            else {
                pq :
                if (mx == INT_MIN) ans.push_back(to_string(mn)) ;
                else {
                    ans.push_back(to_string(mn) + "->" + to_string(mx)) ;
                }
                mx = INT_MIN ;
                    mn = nums[i] ;
            }
        }
        return ans ;
    }
};
```

**Comment by lc-kay** [comment]
@Mohitkumar6122 Can you please provide more details as to which constraints are missing? Thank you for your time!

**Comment by wilzxl** [comment]
> @Mohitkumar6122 Can you please provide more details as to which constraints are missing? Thank you for your time!
Missing test case like [7,7], shows "invalid test case
expected variables nums[0]:7 and nums[1]:7 to have different values"

**Comment by wilzxl** [comment]
> @Mohitkumar6122 Can you please provide more details as to which constraints are missing? Thank you for your time!

Missing test case like [7,7], shows "invalid test case
expected variables nums[0]:7 and nums[1]:7 to have different values"

**Comment by Mohitkumar6122** [comment]
> @Mohitkumar6122 Can you please provide more details as to which constraints are missing? Thank you for your time!

as @wilzxl  provided, all these are missing and further size of input vectors and  range of values of vector  are also missing.

**Comment by lc-kay** [comment]
@Mohitkumar6122 @wilzxl Error "expected variables nums[0]:7 and nums[1]:7 to have different values" is addressed with the last constraint of "All the values of nums are unique." This means that each value of nums must be different and not repeating. 

As to the size of input vectors and range of values of vector, I will relay this to my team to investigate.

**Comment by wilzxl** [comment]
> @Mohitkumar6122 @wilzxl Error "expected variables nums[0]:7 and nums[1]:7 to have different values" is addressed with the last constraint of "All the values of nums are unique." This means that each value of nums must be different and not repeating.
> 
> As to the size of input vectors and range of values of vector, I will relay this to my team to investigate.

Cool, fine with it as long as the test cases are consistent with the description, better to remove the example "**[7,7] --> "7"**" in the description

**Comment by lc-kay** [comment]
@Mohitkumar6122 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
