### ISSUE TITLE
Missing Test Case - 7. Reverse Integer

### ISSUE THREAD

**Issue by DanSeb1295** [LeetCode-Feedback/LeetCode-Feedback#12934]
#### Your LeetCode username

daniel-sebastian95

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

In LC Question 7. Reverse Integer, my code actually actually is an accepted submission, but any test case of x between -9 to -1 inclusive actually breaks my code.

#### Code you used for Submit/Run operation

```
class Solution:
    def reverse(self, x: int) -> int:
        if -1 < x < 10:
            return x
        sign = "" if x >= 0 else "-"
        val = str(x)
        if val[0] == "-":
            val = val[1:]
        
        val = val[::-1]
        res = sign + val
        if (x >= 0 and int(val[:-1]) > int((2**31-1)/10)) or (x < 0 and int(val[:-1]) > int((2**31)/10)):
            return 0
        return int(res)
```

#### Language used for code

Python3

#### Expected behavior

It should break, per ss below. However, it actually is accepted as a valid submission. We need to add test cases for x of values -9 to -1 inclusive.

#### Screenshots

![image](https://user-images.githubusercontent.com/22342817/231506721-c5b96ece-0077-4db6-a245-a79e9a2e8c47.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
