### ISSUE TITLE
Missing Test Case - 231. Power of Two

### ISSUE THREAD

**Issue by pasha1019** [LeetCode-Feedback/LeetCode-Feedback#12949]
#### Your LeetCode username

pasha1011

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [+] Missing Test Cases 

#### Description of the bug

TC is failed. But on my IDE(PyCharm) TC is true. Please check my code.

#### Code you used for Submit/Run operation

```
import math


class Solution:
    def isPowerOfTwo(self, n: int) -> bool:
        if n <= 0:
            return False
        elif n > 0:
            if n == 1:
                return True
            else:
                x = math.log(n, 2)
                if float(x).is_integer():
                    return True
                else:
                    return False
        else:
            return False


print('Enter number')
n = int(input())
print(Solution.isPowerOfTwo(Solution, n))

```

#### Language used for code

Python

**Comment by LC-Pam** [comment]
Thank you for reaching out to us! Unfortunately, we are unable to troubleshoot the different behavior between your local IDE and the LeetCode environment.

For this issue, please raise this as a discuss post in the problem discuss section as other users may have run into the same issue and resolved it.

At LeetCode, we care about the whole learning experience that comes with each problem and we encourage users to teach and help each other to enrich their learning. In addition, we want our users to debug their code and learn from the process.

We appreciate your time and support.
