### ISSUE TITLE
Run code error of Dart language in (2. Add Two Numbers) problem

### ISSUE THREAD

**Issue by 0xRh1d0Y** [LeetCode-Feedback/LeetCode-Feedback#12946]
when i submit dart code then show this error..on the other hand i write same code in vs code i don't see any error
#### Screenshots
Line 56: type 'ListNode' is not a subtype of type 'ListNode?' where
  ListNode is from package:serializers/src/listnode.dart
#0      main (file:///solution.dart:56:13)
<asynchronous suspension>

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code  you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
