### ISSUE TITLE
Missing Test Case - 2619. Array Prototype Last

### ISSUE THREAD

**Issue by derin23** [LeetCode-Feedback/LeetCode-Feedback#12943]
#### Your LeetCode username

Derin23

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Adding a test case that checks if the solution works with an array that only has one element.

#### Code you used for Submit/Run operation

```
input = [3];
output = 3;
expected = 3;

//example jest unit test 
test("[3] should return 3",()=>{
  expect(testcase.last([3])).toBe(3);
})
```

#### Language used for code

JavaScript

#### Expected behavior

If the solution works properly an array with one element like [3] should return the element 3. 

#### Additional context

Just wanted to contribute a test case! I was hoping to write a test case. In the future, it may be beneficial to let users write (contribute) unit tests that you can accept or reject as you see fit. Thank you!

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code subission AC link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by derin23** [comment]
Hey, what do you mean by code submission AC link? Is it acceptance criteria? I was just hoping to contribute a test case to this leet code question so that a bad solution does not pass.

**Comment by derin23** [comment]
Hey, what do you mean by code submission AC link? Is it acceptance criteria? I was just hoping to contribute a test case to this leet code question so that a bad solution does not pass.
