### ISSUE TITLE
Incomplete Question & Constraints - 1015. Smallest Integer Divisible by K

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1294]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

- How far we should go to tell there is no N to return -1?
- What is the range ( mainly upper bound) of the value of N?  N to 32 bit integer max?

#### Code you used for Submit/Run operation

```
```

#### Expected behavior

- The problem description & constraints should be full and complete.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
