### ISSUE TITLE
525. 连续数组 TLE

### ISSUE THREAD

**Issue by An2001-algorithm** [LeetCode-Feedback/LeetCode-Feedback#12958]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
[An2001](https://leetcode.cn/u/an2001/)

**Bug 类型**
- [525. 连续数组 ] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
描述你遇到的 bug
执行代码正常，提交超时
而且多次提交发现并不是同一个测试点超时
无静态变量
**你使用的语言**
Java

**你提交或者运行的代码**
```
class Solution {
     public int findMaxLength(int[] nums) {
        int BASE_INT = 100000;
        int ans = Integer.MIN_VALUE;
        int l = nums.length;
        Integer[] vis = new Integer[2 * BASE_INT + 10];
        for (int i = 0; i < 2 * BASE_INT + 10; i++) {
            vis[i] = Integer.MIN_VALUE;
        }
        vis[BASE_INT] = -1;
        int pre = 0;
        for (int i = 0; i < l; i++) {
            if (nums[i] == 1) {
                pre++;
            } else pre--;

            if (vis[pre + BASE_INT] != Integer.MIN_VALUE) {
                ans = Math.max(ans, i - vis[pre + BASE_INT]);
//                System.out.println(vis[pre + BASE_INT]);
            } else {
                vis[pre + BASE_INT] = i;
            }

        }

        return Math.max(ans, 0);
    }

}
```

**期望行为**
描述你期望的结果

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![image](https://user-images.githubusercontent.com/83284157/231965392-6b5e3ad5-7ddd-4f31-b816-dcb4482729f9.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
Hello～感谢反馈，超出时间限制是复杂度太高了，建议优化使用的算法（可以参考题目的题解）。显示问题是已知的，技术团队会在后续的版本不断更新优化和提升，力扣会给大家带来最佳的用户体验。

**Comment by An2001-algorithm** [comment]
> Hello～感谢反馈，超出时间限制是复杂度太高了，建议优化使用的算法（可以参考题目的题解）。显示问题是已知的，技术团队会在后续的版本不断更新优化和提升，力扣会给大家带来最佳的用户体验。

感谢，不过我的问题在于，把测试点复制到测试用例栏，点击执行代码，此时是正常的，但是提交时会在这个测试点超时

**Comment by feiceh** [comment]
你好，在与相关团队核实后：由于是根据所有用例的用时总和， 进行判断是否 TLE。 因此会出现单个用例通过， 但是提交 TLE 的情况。   PS  建议优化为  int BASE_INT = nums.length;
