### ISSUE TITLE
Missing Test Case - 242. Valid Anagram

### ISSUE THREAD

**Issue by sadwikandula2** [LeetCode-Feedback/LeetCode-Feedback#12952]
#### Your LeetCode username
skandula2

#### Category of the bug
Missing Test Cases 

#### Description of the bug

s= "anagramm"
t= "nagaram"
the program in the editorial solution returns true instead of false  

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean isAnagram(String s, String t) {
        if (s.length() != t.length()) 
            return false;
        int freq[]=new int[26];
        for (int i = 0; i < s.length(); i++) 
        {
            freq[s.charAt(i)-'a']++;    
        } 
        for (int i = 0; i < s.length(); i++) 
        {
            freq[t.charAt(i)-'a']--;
            if(freq[t.charAt(i)-'a']<0)
                return false;
        }
         
        return true;
    }
}
```

#### Language used for code
Java

#### Expected behavior

- The program loops through the characters of the first string "anagramm" and increments the corresponding frequency in the array. After this loop, the array looks like this: [3, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1]
- The program loops through the characters of the second string "nagaram" and decrements the corresponding frequency in the array.In this case, the program decrements the frequencies of 'n', 'a', 'g', 'a', 'r', and 'm' in the array, and after the loop, the array looks like this: [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0].

The program has looped through all the characters in both strings and the frequencies in the array are all zero or positive, so the program returns **true** indicating that the two strings "anagramm" and "nagaram" are anagrams of each other.

**But, "anagramm" and "nagaram" are not anagrams of each other, because they have a different frequency of the letter "m".
In "anagramm", the letter "m" appears twice, while in "nagaram", it appears only once. Therefore, the optimized solution provided earlier should return false for this input.**

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
