### ISSUE TITLE
Incorrect Constraints - 384. Shuffle an Array

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1295]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Constraints are given as below:
	1 <= nums.length <= 200
	-106 <= nums[i] <= 106
	All the elements of nums are unique.
	At most 5 * 104 calls will be made to reset and shuffle.

Below test cases adhere the constraints, but even default code does not give any answer (expection is Wrong Answer)

Test cases:

	Test case does not fit here in github due to Error:	" There was an error creating your Issue: body is too long (maximum is 65536 characters). "
	
	Please provide
		[ null, [[200 elements here]], and 50K alternate reset & shuffle calls ]

#### Code you used for Submit/Run operation

```
/**
 * @param {number[]} nums
 */
var Solution = function(nums) {
    
};

/**
 * Resets the array to its original configuration and return it.
 * @return {number[]}
 */
Solution.prototype.reset = function() {
    
};

/**
 * Returns a random shuffling of the array.
 * @return {number[]}
 */
Solution.prototype.shuffle = function() {
    
};

/** 
 * Your Solution object will be instantiated and called as such:
 * var obj = new Solution(nums)
 * var param_1 = obj.reset()
 * var param_2 = obj.shuffle()
 */
```

#### Language used for code
JavaScript

#### Expected behavior

- No answer is given by the judge (not even a Wrong Answer)
- Judge must give some answer when test cases adhere to Constraints
- Reduce the constraint of 50K limit - Random number does not generate really-random numbers after some limit in JavaScript

**Comment by lc-kay** [comment]
@manoharreddyporeddy Your test case is not properly shown due to a GitHub error. Please submit your test case in a file or a test case generator through https://leetcode.com/playground/new/empty. Thank you for your time!

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
