### ISSUE TITLE
Missing Test Case in 2542. Maximum Subsequence Score

### ISSUE THREAD

**Issue by prakash7720** [LeetCode-Feedback/LeetCode-Feedback#12950]
#### Your LeetCode username
prakash_26

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
There are submissions that got Accepted that should have got Wrong Answer instead (such as this one : [https://leetcode.com/submissions/detail/932629346/](https://leetcode.com/submissions/detail/932629346/)). 
I'm adding test case that correctly judges the mentioned submission.
Problem Link : [https://leetcode.com/problems/maximum-subsequence-score/](url)

#### Code you used for Submit/Run operation

```
#include "bits/stdc++.h"
using namespace std;
#define watch(x) cout << #x << ':' << x << ' ';
// #define int long long
//#define watch(x) 0
#define IOS ios::sync_with_stdio(0); cin.tie(0); cout.tie(0);
#define mod 1000000007
#define pb push_back
#define ff first
#define ss second
#define sz(x) ((int)(x).size())
#define all(x) (x).begin(), (x).end()
#define rall(x) (x).rbegin(), (x).rend()
typedef long long ll;
typedef unsigned long long ull;
typedef long double lld;

class Solution{
    public:
long long maxScore(vector<int>& a, vector<int>& b, int k_) {
	ll n = sz(a);
	vector<pair<ll, ll>> p(n), v(n);

	for (int i = 0; i < n; i++) {
		p[i].ff = b[i];
		p[i].ss = a[i];

		v[i].ff = a[i];
		v[i].ss = b[i];
	}

	sort(all(p));
	sort(all(v), [&](pair<ll,ll> &aa, pair<ll,ll> &bb) {
		if (aa.ff < bb.ff) return true;
		else if (aa.ff > bb.ff) return false;
		return aa.ss > bb.ss;
	});
	// for (int i = 0; i < n; i++) cout << v[i].ff << " ";
	// cout << "\n";

	ll i = n - k_, c = 0;

	for (int k = i; k <= n - 1; k++) {
		c += v[k].ff;
	}
	// i--;
	// watch(c); watch(i); cout << "\n";

	ll ans = 0;

	for (int k = 0; k < n; k++) {
		ll mn = p[k].ff;
		ll elem = p[k].ss;
		// watch(v[i].ff); watch(elem);

		if (elem >= v[i].ff) {
			ans = max(ans, mn * 1ll * c);
			// ll u = mn * 1ll * c;
			// watch(mn); watch(k); watch(c); watch(u); watch(i);

			c -= elem;
			i--;

			int hmm = mn;
			if (k + 1 < n) {
				hmm = p[k + 1].ff;
			}

			while (i >= 0 && (v[i].ss < hmm)) {
				i--;
			}
			if (i < 0) break;
			c += v[i].ff;
			// watch(c); cout << "\n";
		}
		else {
			ans = max(ans, mn * 1ll * (c - v[i].ff + elem));
			// ll u = mn * 1ll * (c - v[i].ff + elem);
			// watch(mn); watch(k); watch(u); watch(i); cout << "\n";
		}
	}

	return ans;
}
};
```

#### Language used for code
C++ 

#### Expected behavior
This code should've gotten Wrong Answer verdict instead of Accepted verdict.

#### Additional context
Test Case
Input: nums1 = [7,6,1,10], nums2 = [0,0,10,0], k = 2
Expected Output : 0
Actual Output : 70

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
