### ISSUE TITLE
使用unordered_map执行结果与预计结果不同

### ISSUE THREAD

**Issue by Cwift** [LeetCode-Feedback/LeetCode-Feedback#12953]
**你的 LeetCode 用户名**
酱油

**Bug 类型**
输出与预计输出不符
- [https://leetcode.cn/problems/most-frequent-even-element/ ] 题目
- [ C++] 编程语言

**描述**
首先, 我使用map提交题解通过, 后来将map改成unordere_map,出现错误, 测试用例: `[0,1,2,2,4,4,1]` 使用map返回为2, 使用unordered_map返回为4

**你使用的语言**
C++

**你提交或者运行的代码**
```c++
class Solution {
public:
    int mostFrequentEven(vector<int>& nums) {
        unordered_map<int, int> map; // 将该处改为map<int, int> map;输出正确
        for (auto num : nums) {
            if ((num & 1) == 0) {
                ++map[num];
            }
        }
        int m = 0;
        int n = -1;
        for (auto it = map.cbegin(); it != map.cend(); ++it) {
            if (it->second > m) {
                n = it->first;
                m = it->second;
            }
        }
        return n;
    }
};
```

**期望行为**
期望输出2, 但是输出为4,在visual studio中验证结果也是2,

**屏幕截图**
![1](https://user-images.githubusercontent.com/23329307/231913684-54a53701-1d02-4334-889f-bdb5f9ba156d.png)

![2](https://user-images.githubusercontent.com/23329307/231913693-3cfe5707-1e74-435f-ba5c-ef43028b8820.png)

**额外的上下文**
 上图中图一是通过的代码 图二是没有通过的代码

**Comment by feiceh** [comment]
你好，在与相关团队核实后：用户代码问题，没有处理相同数量的情况，不处理。
