### ISSUE TITLE
Missing Test Case - 946. Validate Stack Sequences

### ISSUE THREAD

**Issue by jstapankumar** [LeetCode-Feedback/LeetCode-Feedback#12964]
#### Your LeetCode username

stapankumar743

#### Category of the bug
- [x] Missing Test Cases 
Test case1
[4,7,8,3,6,9]
[8,7,9,6,4,3]

#### Description of the bug

I submitted a code for the given question and that was got submitted but after some time I figured out my algorithm was
valid for only certain test cases and I have also figured out for which test cases my code will fail .

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool validateStackSequences(vector<int>& pushed, vector<int>& popped) {
        int i,j,idx;
        if(pushed.size() <= 2)
           return true;
        for(i=0; i<pushed.size(); i++){
            if(popped[0] == pushed[i]){
                idx = i;
                break;
            }
        }
        if(idx == 0){
            vector<int> push,pop;
            for(i=1; i<pushed.size(); i++){
                push.push_back(pushed[i]);
                pop.push_back(popped[i]);
            }
            return validateStackSequences(push,pop);
        } 
        else{
            bool dec = true;
            set<int> s;
            vector<int> v1,v2,v3,v4;
            for(i=0; i<idx; i++){
                s.insert(pushed[i]);
                v1.push_back(pushed[i]);
            }
            for(i=1; i<popped.size(); i++){
                if(s.count(popped[i]) == 0)
                   v3.push_back(popped[i]);
                else
                   v2.push_back(popped[i]);
            }
            for(i=idx+1; i<pushed.size(); i++)
                v4.push_back(pushed[i]);
            for(i=v2.size()-1,j = 0; i>=0 && j<v1.size(); i--,j++){
                if(v2[i] != v1[j]){
                    dec = false;
                    break;
                }
            }
            bool recur = true;
            if(v3.size() == 2){
                if(popped[1] == v4[1] && (2<popped.size() && popped[2] != v4[0]))
                   recur = false;
            }
            else
                recur = validateStackSequences(v4,v3);
            return (dec && recur);
        }
        return true;
    }
};
```

#### Language used for code

C++

#### Expected behavior

for the given testcase the expected output of the compiler must be "false" and it shows correctly as "false" but my code gave "true"
as output and it was accepted code so, due to lack of testcase my code got submitted .

#### Screenshots

![image](https://user-images.githubusercontent.com/99895763/232055400-1d65939e-6e69-4626-8baa-2f84ba702fac.png)

#### Additional context

the given code will fail for all the test cases where
1.the 0th indexed element in popped array comes in index(i) > 0 in pushed array and the index at which it comes (i) is at least 3 less than or equal to end index of pushed array and the end indexed element of pushed array is present in 1st index of popped array and end-1 th indexed element of pushed array is present in 2nd index of popped array and all the elements before ith idex comes in reverse order from 3rd index in popped array then the end-2 th indexed element comes in popped array.
where end = last index of array
examples
[6,8,2,9,1,89,74,21]
[1,21,74,9,2,8,6,89]

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
