### ISSUE TITLE
Function name is wrong for 431. Encode N-ary Tree to Binary Tree

### ISSUE THREAD

**Issue by gaoxinyang** [LeetCode-Feedback/LeetCode-Feedback#1296]
#### Your LeetCode username

gaoxinyang

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

In the problem, the function name for "decoding" is wrong for Scala, it should be **decode**, but now it is **deserialize**

#### Code you used for Submit/Run operation

```
class Codec {
    // Encodes an n-ary tree to a binary tree.
    def encode(root: Node): TreeNode = {
        
    }
    
    // Decodes your binary tree to an n-ary tree.
   // **This is wrong, it should be decode**
    def deserialize(root: TreeNode): Node = {
        
    }
}
```

#### Language used for code
Scala

**Comment by lc-kay** [comment]
Hi @gaoxinyang 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @gaoxinyang 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
