### ISSUE TITLE
Missing Test Case - 10001. Calculate Maximum Information Gain

### ISSUE THREAD

**Issue by Shargano** [LeetCode-Feedback/LeetCode-Feedback#12965]
#### LeetCode username
**[Shargano](https://leetcode.com/Shargano/)**

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
[Link to the problem](https://leetcode.com/explore/learn/card/decision-tree/285/implementation/2651/)

Accepted solution with failed custom test case (edge case).
According to existing test case, answer must be `0.00000` if there is no data. Also answer must be `0.00000` if all labels are the same, cause there will be `zero` information gain of dividing input data into subgroups.

#### Code I used for Submit operation (Accepted)

```
class Solution {

        public double calculateMaxInfoGain(double[] petal_length, String[] species) {
            if (petal_length.length == 0)
                return 0;

            int n = petal_length.length;
            Tuple[] arr = new Tuple[n];

            for (int i = 0; i < n; i++)
                arr[i] = new Tuple(petal_length[i], species[i]);

            Arrays.sort(arr, Comparator.comparingDouble(o -> o.value));

            double subgroup = Double.MAX_VALUE;

            for (int i = 1; i < n; i++) {
                if (!arr[i].label.equals(arr[i - 1].label)) { // LOOK HERE, here's the problem
                    double leftHalfEntropy = calculateEntropy(arr, 0, i);
                    double rightHalfEntropy = calculateEntropy(arr, i, n);
                    double subgroupTemp = leftHalfEntropy * ((double) i / n) + rightHalfEntropy * ((double) (n - i) / n);
                    subgroup = Math.min(subgroup, subgroupTemp);
                }
                if (subgroup == 0)
                    break;
            }

            double wholeItemsEntropy = calculateEntropy(arr, 0, n);

            return wholeItemsEntropy - subgroup;
        }

        private double calculateEntropy(Tuple[] input, int fromInclusive, int toExclusive) {
            double res = 0;
            Map<String, Integer> occurrences = new HashMap<>();

            for (int i = fromInclusive; i < toExclusive; i++) {
                Tuple element = input[i];
                occurrences.computeIfPresent(element.label, (k, v) -> v + 1);
                occurrences.putIfAbsent(element.label, 1);
            }

            for (int x : occurrences.values()) {
                double px = x / (double) (toExclusive - fromInclusive);
                res -= px * (Math.log(px) / Math.log(2));
            }

            return res;
        }

        private class Tuple {
            double value;
            String label;

            Tuple(double _value, String _label) {
                this.value = _value;
                this.label = _label;
            }
        }
    }
```

#### Language used for code
Java

#### Expected behavior
Rejected solution

#### Screenshots
![image](https://user-images.githubusercontent.com/44915282/232099175-f3f77d6a-8492-435d-92e8-ad3f0bbf2438.png)

#### Additional context

Find comment `LOOK HERE` in the code above. I tried to speed up previous slow solution (like 70ms).
By adding condition `!arr[i].label.equals(arr[i - 1].label)` I made solution faster (around 45ms).
Then, I realized, if input data will have the same labels, condition will be false for every entry and no division will be attempt. Therefore answer will be negative `Double.MAX_VALUE`, which is default for subgroups entropy (invalid behavior)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
