### ISSUE TITLE
1501 All test cases (including default) are marked as being invalid

### ISSUE THREAD

**Issue by jmholzer** [LeetCode-Feedback/LeetCode-Feedback#12968]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Regardless of the code that the user gives, the site reports `Phone number of the person with id = 3 doesn't exist in the Country table.` when trying to `Run` with the default test case. This behaviour persists even if the default test case is modified. This stops the user from testing any of their own code.

#### Expected behavior
The default test case should obviously be valid.

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
