### ISSUE TITLE
849. Maximize Distance to Closest Person: a test case that breaks my accepted solution

### ISSUE THREAD

**Issue by evgeni-nabokov** [LeetCode-Feedback/LeetCode-Feedback#1298]
#### Your LeetCode username
evgeni-nabokov

#### Category of the bug
- [* ] Solution

#### Description of the bug
I wrote a solution of the problem 849 that was accepted. When I was revising the code I found a bug. Then I created a test case that doesn't let my solution to pass: [0, 0, 0, 0, 1, 0, 0, 0, 0, 0]

#### Code you used for Submit/Run operation
Link to the submission: https://leetcode.com/submissions/detail/414690152/
#### Language used for code
Rust

#### Expected behavior
Wrong Answer

#### Screenshots
N/A

#### Additional context
N/A

**Comment by lc-kay** [comment]
Hi @evgeni-nabokov 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @evgeni-nabokov 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
