### ISSUE TITLE
Missing Test Case - 328. Odd Even Linked List

### ISSUE THREAD

**Issue by Yogender21505** [LeetCode-Feedback/LeetCode-Feedback#12991]
####The output of this testcase:  [2,1,3,5,6,4,7]
 should be : [1,3,5,7,2,6,4]

#### Category of the bug
- [ ] Question
- [ *] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The output of this testcase:  [2,1,3,5,6,4,7]
 should be : [1,3,5,7,2,6,4] . odd should be first and even should be after of the odd

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by Yogender21505** [comment]
review this testcase and please check it

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
