### ISSUE TITLE
Missing Constraints - 72. Edit Distance

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1299]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

72. Edit Distance
https://leetcode.com/problems/edit-distance/

Constraints are missing
- What are the ranges of lengths of `word1` and `word2`

#### Code you used for Submit/Run operation

```
```

#### Expected behavior

- Not attempting this question as it does not have constraints
- The question must have constraints to avoid TLE errors.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
