### ISSUE TITLE
[Bug] problem 344 Runtime Error

### ISSUE THREAD

**Issue by lixiang2017** [LeetCode-Feedback/LeetCode-Feedback#13]
**What kind of the bug**
- [ ] problem
- [x] solution

**Describe the bug**
I copy the Solution from here. 
https://leetcode.com/problems/reverse-string/solution/
but I got the RuntimeError.

**The code you submit/run**
```
class Solution(object):
    def reverseString(self, s):
        """
        :type s: List[str]
        :rtype: None Do not return anything, modify s in-place instead.
        """
        s.reverse()
```

**Expected behavior**
Success

**Screenshots**
![image](https://user-images.githubusercontent.com/25242627/75988007-dfba9180-5f2b-11ea-8d45-ca0b577126e7.png)

**Comment by CooperCooperCooper** [comment]
Hi @lixiang2017,
Thank you for raising this issue to our attention. I've filed it to our content team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @lixiang2017,
We're happy to share with you that our engineers have fixed the issue. Please feel free to try out all of the available solutions from the solution tabs! Thank you again for your time and support :)
