### ISSUE TITLE
Wrong Kotlin Default Code Definition in "N-ary Tree XXX Traversal" Problems

### ISSUE THREAD

**Issue by PegasisForever** [LeetCode-Feedback/LeetCode-Feedback#130]
**What kind of the bug**
- [ ] problem
- [ ] solution
- [x] language

**Describe the bug**
Links:
- https://leetcode.com/explore/learn/card/n-ary-tree/130/traversal/925/
- https://leetcode.com/explore/learn/card/n-ary-tree/130/traversal/926/

These questions require you to return a list of values, but the default Kotlin function return type is `Int`.

**what language is your code written in**
Kotlin

**The code you submit/run**
```kotlin
// N-ary Tree Postorder Traversal
class Solution {
    fun postorder(root: Node?): Int {  // <- Should be List<Int>
        .....
    }
}
```

**Expected behavior**
The default Kotlin function return type should be`List<Int>`

**Screenshots**
![image](https://user-images.githubusercontent.com/39028532/79027774-8ad9ee80-7b5b-11ea-99fa-1ac6c8a6515e.png)

**Additional context**

**Comment by CooperCooperCooper** [comment]
Hi @PegasisForever,

Thank you for reaching out to us. I've relayed your feedback to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @PegasisForever,
Thank you for your time! We've updated the problem accordingly. We would love to share the valid content issue LeetCoin reward with your account for this contribution. Please reach out to our [main Support Channel](https://support.leetcode.com/hc/en-us) with your username and this ticket to claim the reward!
