### ISSUE TITLE
缺少测试用例—剑指 Offer 59 - II. 队列的最大值

### ISSUE THREAD

**Issue by yx200089** [LeetCode-Feedback/LeetCode-Feedback#13005]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名
龖飝

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述**
一分AC代码对于下列测试用例会出错：
![image](https://user-images.githubusercontent.com/83961650/232409192-e7f0bc95-69e7-428d-8815-59fa29e7415c.png)

**你使用的语言**
C++

**你提交或者运行的代码**
```
class MaxQueue {
private:
    queue<int> _queue; 
    list<int> _max;
public:
    MaxQueue() {}
    
    int max_value() {
        if(_queue.empty())
            return -1;
        return _max.front();
    }
    
    void push_back(int value) {
        _queue.push(value);
        while(!_max.empty() && _max.back() <= value)
            _max.pop_back();
        _max.push_back(value);
    }
    
    int pop_front() {
        if(_queue.empty())
            return -1;
        int temp = _queue.front();
        if(temp == _max.front())
            _max.pop_front();
        _queue.pop();
        return temp;
    }
};
```

**期望行为**
该代码无法通过

**屏幕截图**
![image](https://user-images.githubusercontent.com/83961650/232410292-3724c96b-12d8-40e7-8ed7-61e777f69b4a.png)

**Comment by feiceh** [comment]
你好，当前题目已更新，积分奖励已发放，请查收。
