### ISSUE TITLE
Missing Test Case - 2170. Minimum Operations to Make the Array Alternating

### ISSUE THREAD

**Issue by Akash45785** [LeetCode-Feedback/LeetCode-Feedback#13006]
#### Your LeetCode username
23akash45785
https://leetcode.com/23akash45785/

#### Category of the bug
- [ . ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Contributing a Testcase : 
for a below program  compiler accept the solution   , but if we put  a testcase whose length is 3 and all elements  ( for ex : [ 2, 2, 2 ] 
 ) are equal it gives a wrong  output not same as expected . 
Hence I think this testcase  might be slipped by you 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
        unordered_map<int, int>even , odd;
        int n = nums.size();
        if ( n == 1 )
            return 0;
        
        if ( n == 2)
        {
            if ( nums[0] != nums[1])
            return 0;
            else
            return 1;
        }
        if( n == 3)
        {
            if( nums[0] == nums[2]  )
                return 0 ;
            else
                return 1;
        }
        vector<pair<int, int>>e , o;
        
        for(int i = 0 ;i<n;i++)
        {
            if( i%2 == 0 )
            even[nums[i]]++;
            else
            odd[nums[i]]++;
            
        }
        int ans = INT_MAX;
        
        for(auto x : even)
        e.push_back( { x.second  , x.first});
        for( auto x : odd)
        o.push_back({ x.second , x.first});
        
        sort( e.begin() , e.end() );
        sort( o.begin() , o.end() );
        reverse( e.begin() , e.end());
        reverse( o.begin() , o.end());        

        if( o[0].second != e[0].second)
        {
            int step_1 = (n+1)/2-o[0].first;
            int step_2 = (n/2)-e[0].first;
            ans =  step_1 + step_2 ;
        }
        else
        {
            if( e.size() == 1 and o.size() == 1 and o[0].second == e[0].second)
            {
                return n/2;
            }
             if( e.size() >=2 )
            {
                int step_1 = (n+1)/2-o[0].first;
                int step_2 = (n/2)-e[1].first;
                ans = min( ans , step_1 + step_2);
            }
             if( o.size() >= 2)
            {
                int step_1 = (n+1)/2-o[1].first;
                int step_2 = (n/2)-e[0].first;
                ans = min( ans , step_1 + step_2);
            }
            
        }
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Since the solutions is already accepted so it should also give same result while running of testcase for ( [2 , 2 , 2]) but it gives wrong answer hence  you may slipped those testcases whose length is  3 and have same value 

#### Screenshots

![1](https://user-images.githubusercontent.com/95754028/232412710-4d9d5ef3-20b8-48ed-90b3-65a2a4e1b97a.png)
![3](https://user-images.githubusercontent.com/95754028/232413125-1047f331-21c9-4f7f-ac51-233456f18575.png)

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
