### ISSUE TITLE
Wrong Test Case - 2622. Cache With Time Limit

### ISSUE THREAD

**Issue by AnshPhirani** [LeetCode-Feedback/LeetCode-Feedback#13014]
#### Category of the bug
-  Wrong Test Cases 

#### Output of example test case 2 is wrong
Current Output: [null, false, true, 50, 50, -1]
Expected Output: [null, false, true, 50, 50, -1, 0]

#### Screenshots
![image](https://user-images.githubusercontent.com/72061031/232584096-dfd69e76-5b6c-41cd-9a05-122a0f76919f.png)

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
