### ISSUE TITLE
Cannot see the 'solve your first problem video'

### ISSUE THREAD

**Issue by Jeile** [LeetCode-Feedback/LeetCode-Feedback#13015]
I am unable to watch the viedo... for some reason. It says that due its privacy settings it cannot be shown...
![Screenshot 2023-04-17 214010](https://user-images.githubusercontent.com/122295375/232605977-faa742a5-1cf1-4c11-b071-5924448a33dd.png)

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Comment by Jeile** [comment]
Yeah no. That was not solved, buit thank you anyway.
