### ISSUE TITLE
Editorial improvement - 1857. Largest Color Value in a Directed Graph

### ISSUE THREAD

**Issue by xelplogoog** [LeetCode-Feedback/LeetCode-Feedback#13012]
#### Your LeetCode username
c4tdog

#### Description of the bug
In **Editorial -> Approach 2 -> Java code** there are 2 lines of unused code (lines 37 & 41)
![image](https://user-images.githubusercontent.com/2188302/232578355-06877d63-cac4-4fab-a521-f4bdb09ba19e.png)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
