### ISSUE TITLE
673. Number of Longest Increasing Subsequence 

### ISSUE THREAD

**Issue by arahatashun** [LeetCode-Feedback/LeetCode-Feedback#1302]
#### Your LeetCode username
readonly_true

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
The description of the problem is incorrect.

Given an integer array nums, return the number of longest increasing subsequences.

This should be corrected as follows:

Given an integer array nums, return the number of longest **strictly** increasing subsequences.

**Comment by lc-kay** [comment]
Hi @arahatashun 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @arahatashun 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
