### ISSUE TITLE
Missing Test Case - 1768. Merge Strings Alternately

### ISSUE THREAD

**Issue by royninja** [LeetCode-Feedback/LeetCode-Feedback#13029]
#### LeetCode username

roy_sayan

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

if there is two strings s1 and s2, let s1 is "" empty string then it should return s2 and vice versa.

#### Code you used for Submit/Run operation

```
//1768. Merge Strings Alternately
class Solution {
        public String mergeAlternately(String word1, String word2) {
        StringBuilder st = new StringBuilder();
        //st.setLength(0);
        if(word1 == ""){
            return word2;
        }else if(word2 == ""){
            return word1;
        }else{
            if(word1.length() < word2.length()){
                int k = 0;
                for (int i = 0; i < word1.length(); i++) {
                    st.append(word1.charAt(i));
                    st.append(word2.charAt(i));
                    k = i;
                }
                k++;
                while( k < word2.length()){
                    st.append(word2.charAt(k));
                    k++;
                }

            }else if(word2.length() < word1.length()){
                int k = 0;
                for (int i = 0; i < word2.length(); i++) {
                    st.append(word1.charAt(i));
                    st.append(word2.charAt(i));
                    k = i;
                }
                k++;
                while( k < word1.length()){
                    st.append(word1.charAt(k));
                    k++;
                }
            }else{
                for (int i = 0; i < word1.length(); i++) {
                    st.append(word1.charAt(i));
                    st.append(word2.charAt(i));
                }
            }

            return st.toString();
        }
    }

}
```

#### Language used for code

Java

#### Expected behavior

Test Case 1:
Input: word1 = "" word2="pq"
Ouput: pq

Test Case 2:
Input: word1 = "abcd" word2=""
Ouput: abcd

#### Screenshots

![image](https://user-images.githubusercontent.com/26019882/232891463-c60217af-f490-4f65-8ded-146b095c6351.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by xelplogoog** [comment]
Constraints:
1 <= word1.length, word2.length <= 100

no empty allowed

**Comment by royninja** [comment]
you are right

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Strings must not be empty. Please check the constraints.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
