### ISSUE TITLE
288. Unique Word Abbreviation - Explain the problem

### ISSUE THREAD

**Issue by AjayVV** [LeetCode-Feedback/LeetCode-Feedback#1303]
#### Your LeetCode username
ajayvv

#### Category of the bug
- [x] Question

#### Description of the bug
The description is quite vague and doesn't mention what exactly is the expectation. Only after submitting and seeing various tests fail, we get to know what's expected. The following point is incomprehensible:

_"Else, for all words in dictionary such that their abbreviation is equal to the abbreviation of word those words are equal to word."_

Please make it clear, or better add at least one more meaningful example.

**Comment by lc-kay** [comment]
Hi @AjayVV 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @AjayVV 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
