### ISSUE TITLE
Test cases passed but it's showing failed

### ISSUE THREAD

**Issue by ChauhanHarshit** [LeetCode-Feedback/LeetCode-Feedback#13030]
#### Your LeetCode username
Chauhan__harshit

#### Category of the bug
- [ 1768] Question
- [ ] Solution
- [ C++] Language
- [ ] Missing Test Cases 

#### Description of the bug

The code written is correct and the output in 2nd and 3rd test cases are matching but still its showing wrong answer.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    string mergeAlternately(string word1, string word2) {
        int n1=word1.length()+word2.length();
        int n=min(word1.length(),word2.length());
        string s="";
        int i=0;
        for(int i=0;i<n1;i++){
            if(i%2==0)s.push_back(word1[i/2]);
            else{
                s.push_back(word2[i/2]);
            }
        }
        for(int i=1;i<(n1-n);i++){
        if(word1.length()>word2.length()) s.push_back(word1[n+i]);
        if(word2.length()>word1.length()) s.push_back(word2[n+i]);
        }
        return s;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The solution should be accepted as correct as the  output is same  as expected output.But it is showing wrong answer.
 
<img width="1440" alt="Screenshot 2023-04-19 at 1 23 30 AM" src="https://user-images.githubusercontent.com/104462304/232895562-e13ea18b-e104-4bac-a3c8-b905aadc0f24.png">
<img width="1440" alt="Screenshot 2023-04-19 at 1 49 58 AM" src="https://user-images.githubusercontent.com/104462304/232895821-04d84b06-437f-455e-b596-fd7c0aef7215.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output values.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!
