### ISSUE TITLE
Question - 2624. Snail Traversal

### ISSUE THREAD

**Issue by CocoRyse** [LeetCode-Feedback/LeetCode-Feedback#13036]
#### Your LeetCode username
CocoRyse

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
You have problem with markdown
In description where you explaining what snail traversal order is after words "For example" you provide an arrays from Example 1 and it is formatted incorrectly, an array should be shown as a code like other code-like things in this description 

Selected text at screenshot should be formatted as a code block
<img width="699" alt="image" src="https://user-images.githubusercontent.com/52622589/233015614-ed1e9fcf-5839-4f79-8cdf-4f84c8107335.png">

#### Code you used for Submit/Run operation
There is no code related to this issue

#### Language used for code
There is no code related to this issue

#### Expected behavior
There is no code related to this issue

#### Screenshots
<img width="707" alt="image" src="https://user-images.githubusercontent.com/52622589/233016045-91bf9269-81dd-4a2f-9eda-ac854315c32c.png">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
