### ISSUE TITLE
Not Proper Test Case - 2497. Maximum Star Sum of a Graph

### ISSUE THREAD

**Issue by manish831** [LeetCode-Feedback/LeetCode-Feedback#13032]
#### Your LeetCode username
ManishAgrahari

#### Category of the bug
- [ ] Question
- [ ] Wrong Test Cases 

#### Description of the bug

In the first line of question, ther is mentioned that "There is an undirected graph consisting of n nodes numbered from 0 to n - 1", but i found a test case in which this condition isn't satisfied.

#### Code you used for Submit/Run operation

```
// 2497. Maximum Star Sum of a Graph
class Solution {
public:
    int helper(priority_queue<pair<int, int>>&mpPqPair, int k){
        int x = 0;
        while(!mpPqPair.empty() and k--){
            if(mpPqPair.top().first>=0){
                x += mpPqPair.top().first;
                mpPqPair.pop();
            }
        }
        return x;
    }
    int maxStarSum(vector<int>& vals, vector<vector<int>>& edges, int k) {
        //pair => wt, node_val
        if(edges.size() == 0){
            return *max_element(vals.begin(), vals.end());
        }
        map<int, priority_queue<pair<int, int>>>mpPqPair;
        for(int i=0; i<edges.size(); i++){    
            int wt1 = vals[edges[i][1]];
            int wt2 = vals[edges[i][0]];
            mpPqPair[edges[i][0]].push({wt1, edges[i][1]});
            mpPqPair[edges[i][1]].push({wt2, edges[i][0]});
        }
        int maks = INT_MIN;
        for(auto it : mpPqPair){
            int x = vals[it.first];
            int val = x+helper(it.second, k);
            maks = max(maks, val);
        }
        return maks;
    }
};
```

#### Language used for code
C++

#### Expected behavior

The testcase which i found is wrong and doesn't meet the condition mentioned in question. So either make correction in the question or delete that particular test case.
Here is that test case:
vals =
[-2,-1,-2]
edges =
[[0,2]]
k =
1

In this test case, the node with value '1' is not present but it must be there (according to question).

#### Additional context

-This question may be right if the graph is disconnected graph
-Please do correction in the question statement or delete this test case.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
