### ISSUE TITLE
Incorrect Test Case - 2561. Rearranging Fruits

### ISSUE THREAD

**Issue by anushachadalavada** [LeetCode-Feedback/LeetCode-Feedback#13034]
#### Your LeetCode username

anu_c

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Incorrect Test Case

#### Description of the bug

basket1 =
[4,4,4,4,3]
basket2 =
[5,5,5,5,3]

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    public long minCost(int[] basket1, int[] basket2) {
        PriorityQueue<Integer> b1 = new PriorityQueue<Integer>(Collections.reverseOrder());
        PriorityQueue<Integer> b2 = new PriorityQueue<Integer>(Collections.reverseOrder());

        for(int i: basket1)
            b1.add(i);
        for(int i: basket2)
            b2.add(i);

        int swaps = 0;
        int common =0;
        Set<Integer> set2 = new HashSet<Integer>();
        while( !b1.isEmpty() )
        {
             int top1 = b1.remove();
             int top2 = b2.remove();

             if( top1 != top2)
             {
                 b1.add(top2);
                 b2.add(top1);
                
                 swaps++;
                 if( set2.contains(top1))
                    common++;

                 set2.add(top2);
                 if( swaps > basket1.length) return -1;
             }
        } 

        return swaps - common;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The expected Answer is 2 but the test case expects 8.
Explanation: Swap the first two 4s in array1 with the first two 5s in array2 which will make both arrays equal. 
So only 2 swaps are required.

**Comment by xelplogoog** [comment]
you need to return minimum cost (which is 8 in your example), not minimum swaps.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
