### ISSUE TITLE
Not accurate picture - 1372. Longest ZigZag Path in a Binary Tree

### ISSUE THREAD

**Issue by xelplogoog** [LeetCode-Feedback/LeetCode-Feedback#13041]
#### Your LeetCode username
c4tdog

#### Description of the bug
In example #1 the picture doesn't match the text input (number of nodes doesn't match: picture has 8 nodes, whereas text input contains 9 nodes)

![image](https://user-images.githubusercontent.com/2188302/233155638-162ad10c-8c4e-4e4d-b9a4-e41449dc5eb9.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
