### ISSUE TITLE
Crash Course Data Structures & Algorithms -> "Squares of a sorted array" section -> "How to create a test case" -> Irrelevant link

### ISSUE THREAD

**Issue by Arucious** [LeetCode-Feedback/LeetCode-Feedback#13046]
#### Your LeetCode username

arucious

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [X] None of the above

#### Description of the bug

When you go to the squares of a sorted array chapter in the course, the 'how to create a test case' link leads you to a binary tree page

#### Code you used for Submit/Run operation

```
N/A
```

#### Language used for code

N/A

#### Expected behavior

I expect it to have a page related to how to create a test case

#### Screenshots

<img width="499" alt="image" src="https://user-images.githubusercontent.com/37028027/233229854-4cd44c25-035d-4afc-8759-b6ccd3b8af13.png">

#### Additional context

Interview crash course

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

This is independent of the course/problem. It is part of LeetCode's UI and it is actually a drop down, binary tree just happens to be the only option.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
