### ISSUE TITLE
Missing Test Case - 98. Validate Binary Search Tree

### ISSUE THREAD

**Issue by asmitapatil94210** [LeetCode-Feedback/LeetCode-Feedback#13043]
#### Your LeetCode username
asmitapatil

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
Missing test case for given question

#### Code you used for Submit/Run operation
```
class Solution {
    public boolean isValidBST(TreeNode root) {
        if(root == null)
        {
            return true;
        }
        else
        {
            return isValid(root, 0, 0);
        }
    }

    public boolean isValid(TreeNode root, int maxVal, int minVal)
    {
        if(root == null)
        {
            return true;
        }

        if(minVal != 0 && root.val <= minVal || maxVal != 0 && root.val >= maxVal)
        {
            return false;
        }
        return isValid(root.left, root.val, minVal) && isValid(root.right, maxVal, root.val);
    }
}
```

#### Language used for code
Java

#### Expected behavior
Test case is missing. This should be part of default test cases.

#### Additional context
Add below test case in default test cases
[5,1,7,null,null,3,8]

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
