### ISSUE TITLE
Missing Test Case - 26. Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by banrj** [LeetCode-Feedback/LeetCode-Feedback#13044]
#### Your LeetCode username
<Banrj>

#### Category of the bug
- [x] Question
- [x] Solution
- [ python3] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation
```
class Solution:
    def removeDuplicates(self, nums: List[int]) -> int:
        last = nums[0]
        count = 0

        for i in range(1, len(nums)-1):
            if last == nums[i - count]:
                del nums[i - count]
                count += 1
            else:
                last = nums[i - count]
        return count
```

#### Screenshots

<img width="1185" alt="Снимок экрана 2023-04-20 в 01 28 47" src="https://user-images.githubusercontent.com/105605702/233220983-2d7317bf-b41a-4005-9523-760272aad4d7.png">

<img width="1286" alt="Снимок экрана 2023-04-20 в 01 29 33" src="https://user-images.githubusercontent.com/105605702/233221073-370c21e0-43b1-4542-b2cb-d93d9d92a360.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
