### ISSUE TITLE
我想找简单题里通过率最低的题目，但题库页面里的排序按钮有bug，排序的结果不对

### ISSUE THREAD

**Issue by JohnChenLiang** [LeetCode-Feedback/LeetCode-Feedback#13047]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
描述你遇到的 bug

**你使用的语言**
C++

**你提交或者运行的代码**
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
        
    }
};
```

**期望行为**
我想找简单题里通过率最低的题目，但题库页面里的排序按钮有bug，排序的结果不对

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![image](https://user-images.githubusercontent.com/30498675/233250481-0e1f8055-e02b-4cf4-a6c2-d94a514bc5c8.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
Hello～感谢反馈，排序的问题已知，我们的产研团队会在后续版本不断努力优化和提升我们的产品，给大家带来最佳的用户体验。Github 仓库只用于反馈大家在本站学习过程中遇到的题目和题解问题，目前我们会暂时关闭该 issue，如有更多反馈和建议欢迎  [点击这里](https://support.leetcode.cn/hc/request/new/) 提交工单反馈，给您带来的不便敬请谅解。

**Comment by JohnChenLiang** [comment]
所以什么时候能解决？解决了通知下我



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: feiceh ***@***.***&gt;
发送时间: 2023年4月20日 16:14
收件人: LeetCode-Feedback/LeetCode-Feedback ***@***.***&gt;
抄送: JohnChenLiang ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [LeetCode-Feedback/LeetCode-Feedback] 我想找简单题里通过率最低的题目，但题库页面里的排序按钮有bug，排序的结果不对 (Issue #13047)





 
Hello～感谢反馈，排序的问题已知，我们的产研团队会在后续版本不断努力优化和提升我们的产品，给大家带来最佳的用户体验。Github 仓库只用于反馈大家在本站学习过程中遇到的题目和题解问题，目前我们会暂时关闭该 issue，如有更多反馈和建议欢迎  点击这里 提交工单反馈，给您带来的不便敬请谅解。
