### ISSUE TITLE
Missing Test Case - 179. Largest Number

### ISSUE THREAD

**Issue by avdd80** [LeetCode-Feedback/LeetCode-Feedback#13050]
#### Your LeetCode username

avdd80

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x] Missing Test Cases 

#### Description of the bug

Following testcase is missing: [1000000000, 1000000000]
This TC validates that the user allocates sufficient space to hold the final string. 
In C language, the above input requires 10 bytes + 10 bytes + 1 byte to hold null terminator character. This scenario is not previously tested with existing test suite. The user can get by just allocating 20 bytes (instead of required 21 bytes)

#### Code you used for Submit/Run operation

```
int discard_trailing_digits (int a, int n)
{
    if (a == 0)
        return 0;
    for (int i = 0; i < n; i++)
        a /= 10;
    return a;
}

int intlen(int a)
{
    int len = 0;
    while (a)
    {
        len++;
        a /= 10;
    }
    return len;
}

// return ax10^n
unsigned long long power10 (int a, int n)
{
    unsigned long long x = a;
    for (int i = 0; i < n; i++)
    {
        x *= 10;
    }
    return x;
}

int compare (int a, int b)
{
    if (b == 0)
        return 1;
    if (a == 0)
        return 0;
    unsigned long long x, y;

    int lena = intlen(a);
    int lenb = intlen(b);

    // a comes first
    x = power10 (a, lenb) + b;

    // b comes first
    y = power10 (b, lena) + a;

    return (x > y ? 1 : 0);
}

void merge (int * a, int l, int m, int r)
{
    int i, j, k = l;
    int n1 = m - l + 1;
    int n2 = r - m;

    int L[n1];
    int R[n2];

    for (i = 0; i < n1; i++)
    {
        L[i] = a[l + i];
    }
    for (i = 0; i < n2; i++)
    {
        R[i] = a[m+1 + i];
    }

    i = j = 0;

    while (i < n1 && j < n2)
    {
        if (compare(L[i], R[j]))
        {
            a[k] = L[i];
            i++;
        }
        else
        {
            a[k] = R[j];
            j++;
        }
        k++;
    }

    while (i < n1)
    {
        a[k] = L[i];
        i++;
        k++;
    }

    while (j < n2)
    {
        a[k] = R[j];
        j++;
        k++;
    }
}

// Sort numbers by value and by length
void mergesort (int* a, int l, int r)
{

    int m;
    if (l < r)
    {
        m = l + (r - l)/2;
        mergesort (a, l, m);
        mergesort (a, m+1, r);

        merge (a, l, m, r);
    }

}


char * largestNumber(int* nums, int numsSize)
{
    /******************************************************************/
    /*** EXPECTED FIX FOR THE LINE BELOW ******************************
    char* result = (char*) malloc (sizeof(char) * 10 * numsSize + 1);
                                                                ^
    *******************************************************************/
    char* result = (char*) malloc (sizeof(char) * 10 * numsSize);
    mergesort (nums, 0, numsSize - 1);
    int len = 0;
    int total_len = 0;

    for (int i = 0; i < numsSize; i++)
    {
        len = sprintf (&result[total_len], "%d", nums[i]);
        total_len += len;
    }

    // edge case - 0, 0, 0, 0,....
    if (result[0] == '0')
        total_len = 1;

    result[total_len] = '\0';
    return result;
}
```

#### Language used for code

C

#### Expected behavior

1. The above C code fails because user has not allocated sufficient space for result string.
2. However Leetcode's test suite passes with this code.
3. The contributed TC crashes the above code.
4. A fix is provided in comments just above the offending line of code in largestNumber (). With this fix, the contributed TC also passes. 

#### Additional context

![goodcase](https://user-images.githubusercontent.com/3952478/233274337-60d5400a-145c-48a8-b1ec-3158d338bfcf.png)
![badcase](https://user-images.githubusercontent.com/3952478/233274345-bed3a6bf-d616-4137-9146-1610896e5ef6.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
