### ISSUE TITLE
2625. Flatten Deeply Nested Array | Question typo

### ISSUE THREAD

**Issue by VaibhaveS** [LeetCode-Feedback/LeetCode-Feedback#13052]
#### Your LeetCode username
[IamVaibhave53](https://leetcode.com/IamVaibhave53/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The question says "This flattening operation should only be done if the current depth of nesting is **greater** than n" however according to the behavior expected this must be corrected to  "This flattening operation should only be done if the current depth of nesting is **lesser** than n"

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
