### ISSUE TITLE
Web Interface bug - wide Stdout blocked by button

### ISSUE THREAD

**Issue by alexthu07** [LeetCode-Feedback/LeetCode-Feedback#13058]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases
- [x] Interface 

#### Description of the bug

"View less" button block the right side of last line in "Stdout" section in results when outputs were wide in "Stdout".

#### Code you used for Submit/Run operation

NA

#### Language used for code

NA

#### Expected behavior

"View less" should be one line below the outputs when outputs were wide in "Stdout" section

#### Screenshots

![image](https://user-images.githubusercontent.com/12093319/233438603-015a0674-1b2a-4889-a9c5-3ae830de79af.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've submitted this feedback to the team. 

Thank you for your support.
