### ISSUE TITLE
Ambiguous Question description - 1640. Check Array Formation Through Concatenation

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1305]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

1640. Check Array Formation Through Concatenation
https://leetcode.com/problems/check-array-formation-through-concatenation/

Below test case is given:

	Example 3:
	Input: arr = [49,18,16], pieces = [[16,18,49]]
	Output: false
	Explanation: Even though the numbers match, we cannot reorder pieces[0].

Here the expected is false.
However, if we sort the `arr` they match. The question does not say anything about `we cannot reorder arr`

Please add below to the description:

> The array `arr` cannot be reordered

#### Code you used for Submit/Run operation

```
```

#### Expected behavior

- The constraints should in the Constraints section or Question description - not in the test case
- The question should be unambiguous to avoid wastage of User time.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@manoharreddyporeddy Reading the statement, you can see "However, you are not allowed to reorder the integers in each array pieces [i]." Therefore, it is already very clear in the statement and no changes are needed. Thank you for your time.
