### ISSUE TITLE
Test case issue of Question:  2474. Customers With Strictly Increasing Purchases 

### ISSUE THREAD

**Issue by xinranLiao** [LeetCode-Feedback/LeetCode-Feedback#13066]
#### Your LeetCode username

xinranLiao

#### Category of the bug
- [x] Solution

#### Description of the bug

Question:  2474. Customers With Strictly Increasing Purchases
The task is about to find the customers with the total purchases strictly increasing yearly. In my understanding, since we are finding the strictly increasing purchases, those customers who only made 1 order should not be considered since there is no increasing. However, in some test case (the third test case), a customer (customer_id = 6)  only made 1 order but still be considered as the desired customer.

#### Code you used for Submit/Run operation

```
SELECT customer_id
FROM
    (SELECT customer_id, COUNT(customer_id) AS N_RECORD, SUM(RESULT) AS N_SATISFY
    FROM
        (SELECT customer_id, ORDER_YEAR, YEARLY_PRICE,
        CASE 
            WHEN IS_CONSECUTIVE = IS_INCREASE AND SUM_CONSE = SUM_INCRE AND SUM_CONSE <> 0 THEN "1"
            ELSE "0"
        END AS RESULT
        FROM
            (SELECT customer_id, ORDER_YEAR, YEARLY_PRICE,IS_CONSECUTIVE,IS_INCREASE, 
            SUM(IS_CONSECUTIVE) OVER(PARTITION BY customer_id) AS SUM_CONSE,
            SUM(IS_INCREASE) OVER(PARTITION BY customer_id) AS SUM_INCRE
            FROM
                (SELECT customer_id, ORDER_YEAR, YEARLY_PRICE,
                CASE 
                    WHEN LEAD(ORDER_YEAR) OVER(PARTITION BY customer_id)= ORDER_YEAR  + 1 THEN 1
                    ELSE 0
                END AS IS_CONSECUTIVE,

                CASE 
                    WHEN LEAD(YEARLY_PRICE) OVER(PARTITION BY customer_id) > YEARLY_PRICE THEN 1
                    ELSE 0
                END AS IS_INCREASE
                FROM
                    (SELECT customer_id, YEAR(order_date) AS ORDER_YEAR, SUM(PRICE) AS YEARLY_PRICE
                    FROM ORDERS
                    GROUP BY customer_id, ORDER_YEAR
                    ORDER BY customer_id, ORDER_YEAR ASC
                    ) AS T1
                ) AS T2
            )AS T3
        ) AS T4
    GROUP BY customer_id
    ) AS T5
WHERE N_RECORD = N_SATISFY
;
```

#### Expected behavior

I expect that the customer with only 1 order should not be considered as the customers with strictly increasing purchases.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
