### ISSUE TITLE
Missing Test case - 1640. Check Array Formation Through Concatenation

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1306]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

1640. Check Array Formation Through Concatenation
https://leetcode.com/problems/check-array-formation-through-concatenation/

Please add below test case - below code fails:

	Wrong Answer
		Your input
			[1,2,3]
			[[2],[1,3]]
		Output		true
		Expected	false

#### Code you used for Submit/Run operation

Code from https://leetcode.com/problems/check-array-formation-through-concatenation/discuss/918505/Kotlin-Explained-idea-(Save-the-indices-of-first-array)

```
class Solution {
    fun canFormArray(arr: IntArray, pieces: Array<IntArray>): Boolean {
        val map = hashMapOf<Int, Int>()
        
        for (i in arr.indices) {
            map[arr[i]] = i // Mapping from element to its index
        }
        
        for (piece in pieces) {
            if (piece.size > 1) { // If there are at least 2 elements, we process further 
                for (i in 1 until piece.size) {
                    if (map[piece[i-1]] == null || map[piece[i]] == null || map[piece[i]]!! < map[piece[i-1]]!!) // map[xyz] == null means the number doesn't exist in map
                        return false
                }
            }
        }
        
        return true
    }
}
```

#### Language used for code
Kotlin

#### Expected behavior

- Judge has weak tests like last time. Discuss now will be filled with wrong solutions
- Judge must have proper & good number of test cases.

**Comment by liverdance** [comment]
It's funny that uwi won the contest with a similarly wrong solution :)
https://leetcode.com/contest/weekly-contest-213/ranking/1/

**Comment by sidhuparas** [comment]
+1. I wrote that code and I feel bad that it got passed.

**Comment by manoharreddyporeddy** [comment]
> It's funny that uwi won the contest with a similarly wrong solution :)
> https://leetcode.com/contest/weekly-contest-213/ranking/1/

LOL
you are right uwi's code also fails :)

**Comment by suthagar23** [comment]
+1, it's a very important test case which needs to be placed there

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by manoharreddyporeddy** [comment]
@liverdance 
@sidhuparas 
@suthagar23 

Looks like

uwi is no more # 1 he is 616 rank - https://leetcode.com/contest/weekly-contest-213/ranking/25/
jonathanirvings is # 1 now

Now unfortunate is uwi, as 0 score for 1st question - he never got a chance for resubmitting due to poor judge.
