### ISSUE TITLE
broken problem (rotate-array)

### ISSUE THREAD

**Issue by moodwrench** [LeetCode-Feedback/LeetCode-Feedback#13063]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The question https://leetcode.com/problems/rotate-array/ seems broken (maybe just Ruby). It always shows the same output (one of the input variables called nums) no matter what I return. I can reset the problem and leave it unchanged (empty method) and instead of listing the output as nil, it shows the value of one if the input variables (nums).

see https://leetcode.com/submissions/detail/936543052/ for more detail. The solution provided works fine if I run your test case in pry outside leetcode.

#### Code you used for Submit/Run operation
any code will show the issue.  You can have the method just return a string with the answer and it will still mark it as wrong and show the nums var in the output

#### Language used for code
Tested in ruby but seems to also effect python

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Please change the array nums.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
