### ISSUE TITLE
Java solution error - 662. Maximum Width of Binary Tree

### ISSUE THREAD

**Issue by przemek3d88** [LeetCode-Feedback/LeetCode-Feedback#13060]
#### Your LeetCode username
przemysaw2

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Java solution is wrong as the integer overflows. I attach the editorial code with added assertion that the value is non-negative. It fails. You need to rescale the values on each level to make it work.

Also, when using C++ unsigned type, it treats all the computation as % (2^32) and the integer overflow is also not caught.

#### Code you used for Submit/Run operation

```
/**
 * Definition for a binary tree node.
 * public class TreeNode {
 *     int val;
 *     TreeNode left;
 *     TreeNode right;
 *     TreeNode(int x) { val = x; }
 * }
 */
class Solution {
    public int widthOfBinaryTree(TreeNode root) {
        if (root == null)
            return 0;

        // queue of elements [(node, col_index)]
        LinkedList<Pair<TreeNode, Integer>> queue = new LinkedList<>();
        Integer maxWidth = 0;

        queue.addLast(new Pair<>(root, 0));
        while (queue.size() > 0) {
            Pair<TreeNode, Integer> head = queue.getFirst();

            // iterate through the current level
            Integer currLevelSize = queue.size();
            Pair<TreeNode, Integer> elem = null;
            for (int i = 0; i < currLevelSize; ++i) {
                elem = queue.removeFirst();
                TreeNode node = elem.getKey();
                if (node.left != null)
                    queue.addLast(new Pair<>(node.left, 2 * elem.getValue()));
                if (node.right != null)
                    queue.addLast(new Pair<>(node.right, 2 * elem.getValue() + 1));
            }

            // calculate the length of the current level,
            //   by comparing the first and last col_index.
            assert elem.getValue() >= 0;
            
            maxWidth = Math.max(maxWidth, elem.getValue() - head.getValue() + 1);
        }

        return maxWidth;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The submitted solution is accepted.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by yumkam** [comment]
disclaimer: I'm just another leetcode user
In java, integer overflow is defined: it wraps around (perform calculation modulo 2**32).
In C++, unsigned integer overflow is also defined operation (it wraps around).
So, above solution just relies on guarantee from problem description (maximum width of a tree fits 32-bit integer) and implicit calculation mod 2**32. Solution is correct, assert is not correct, it assumes wrong things.

**Comment by przemek3d88** [comment]
>In java, integer overflow is defined: it wraps around (perform calculation modulo 2**32). 

This is not true, which is confirmed by the assert.

> Solution is correct, assert is not correct, it assumes wrong things.

The solution is incorrect, assert is correct. You can't overflow into the negative numbers, and you also can't calculate modulo 2**32, as you can have the wrong answer with the same mod.

**Comment by yumkam** [comment]
The only thing that is confirmed by assert is that overflow happens. I have not denied it.
But as long as testcase generated in a way that maximum width fits into signed int, it still produces correct result.
(It *can* produce *incorrect* result when testcase violate this requirement).
4294967295 = 0xffffffff = -1 (mod 2**32)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
