### ISSUE TITLE
LeetCode 610 Doesn't Accept Answer In Any Order

### ISSUE THREAD

**Issue by ThomasShaw1** [LeetCode-Feedback/LeetCode-Feedback#13068]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The problem statement for LeetCode 610 states that the question accepts solution in any order. However, when I ran the code below, it fails at the first test due to incorrect order. The test case is:
| x  | y  | z  |
| -- | -- | -- |
| 13 | 15 | 30 |
| 10 | 20 | 15 |

#### Code you used for Submit/Run operation

```
SELECT x, y, z, 'Yes' AS triangle
FROM Triangle
WHERE x + y > z AND x + z > y AND y + z > x
UNION ALL
SELECT x, y, z, 'No' AS triangle
FROM Triangle
WHERE x + y <= z OR x + z <= y OR y + z <= x;
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
