### ISSUE TITLE
缺少测试用例——183.从不订购的客户

### ISSUE THREAD

**Issue by starter727** [LeetCode-Feedback/LeetCode-Feedback#13070]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名
harbinger
**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述**
描述你遇到的 bug

**你使用的语言**
Mysql

**你提交或者运行的代码**
```
(select name as Customers from Customers)except all
(select name  from Customers,Orders where Customers.Id=Orders.CustomerId);
```

**期望行为**
缺少测试用例{"headers": {"Customers": ["id", "name"], "Orders": ["id", "customerId"]}, "rows": {"Customers": [[1, "Joe"], [2, "Joe"], [3, "Sam"], [4, "Max"]], "Orders": [[1, 1], [2, 1]]}}
这个测试用例下应该是不正确的

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，当前题目已更新，奖励已发放。
