### ISSUE TITLE
Question has Typo - 2632. Curry

### ISSUE THREAD

**Issue by theabbie** [LeetCode-Feedback/LeetCode-Feedback#13075]
#### Your LeetCode username
theabbie

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Brackets should be balanced in Example testcase 2 of https://leetcode.com/problems/curry/

#### Expected behavior
should be `[[1,2],[3]]`

#### Screenshots
<img width="437" alt="image" src="https://user-images.githubusercontent.com/17960677/233674597-a9b5465b-044c-4e5e-ab00-86e95151551f.png">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
