### ISSUE TITLE
Missing Test case 2 - 1640. Check Array Formation Through Concatenation

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1307]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

1640. Check Array Formation Through Concatenation
https://leetcode.com/problems/check-array-formation-through-concatenation/

Please add below test case - below code fails:

	[1,2,3]
	[[1],[3,2]]

	Error: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3

#### Code you used for Submit/Run operation

Code at  https://leetcode.com/problems/check-array-formation-through-concatenation/discuss/918499/JAVA-Brute-Force

```
class Solution {
    public boolean canFormArray(int[] arr, int[][] pieces) {
        int i = 0, internal = 0;
        while(i < arr.length){
            for(int j = 0; j < pieces.length; j++){
                if(arr[i] == pieces[j][0]){
                    internal = 0;
                    while(internal < pieces[j].length){
                        if(arr[i++] == pieces[j][internal++]) continue;
                        else return false;
                    }
                    i--;
                    if(internal != pieces[j].length) return false;
                }
            }
            if(internal == 0) return false;
            i++;
        }
        return true;
    }
}
```

#### Language used for code
Java

#### Expected behavior

- Judge has weak tests like last time. Discuss now will be filled with wrong solutions
- Judge must have a proper & good number of test cases.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
