### ISSUE TITLE
Missing Test Case - 9. Palindrome Number

### ISSUE THREAD

**Issue by sajalbatra** [LeetCode-Feedback/LeetCode-Feedback#13087]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ yes] Missing Test Cases 
Missing Test Cases 

#### Description of the bug

contributing a test case for program to verify  plaidrome number

#### Code you used for Submit/Run operation
```
class Solution {
public:
    bool isPalindrome(int x) {
        long long n = 0;
        int temp = x;
        if (x < 0) { 
        return false;
    }
        while (temp != 0) {
            int rem = temp % 10;
            n = n * 10 + rem;
            temp /= 10;
        }
        if (n > INT_MAX || n < INT_MIN) {
            return 0;
        }
        if(n==x) return true;
        else return false;
    }
};

```
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by sajalbatra** [comment]
> 

Programming language: C++(cpp)
program:
class Solution {
public:
    bool isPalindrome(int x) {
        long long n = 0;
        int temp = x;
        if (x < 0) { 
        return false;
    }
        while (temp != 0) {
            int rem = temp % 10;
            n = n * 10 + rem;
            temp /= 10;
        }
        if (n > INT_MAX || n < INT_MIN) {
            return 0;
        }
        if(n==x) return true;
        else return false;
    }
};

Test Case:
1)
Input: x = 0
Expected output: true
2)
Input: x = 2147483647
Expected output: false

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The judger appears to be running correctly.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
<img width="185" alt="Screen Shot 2023-04-26 at 3 47 11 PM" src="https://user-images.githubusercontent.com/103138242/234686366-7dbb462d-bc64-4183-be0f-3758664d9001.png">
<img width="219" alt="Screen Shot 2023-04-26 at 3 47 21 PM" src="https://user-images.githubusercontent.com/103138242/234686370-f70a1332-9ab3-4249-b814-bed1335af476.png">
