### ISSUE TITLE
`typing.List` is deprecated, use `list` instead

### ISSUE THREAD

**Issue by samyak1409** [LeetCode-Feedback/LeetCode-Feedback#13082]
#### Your LeetCode username

samyak1409

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

In Python3 code templates, we're still using `typing` for type hints which is deprecated since Python 3.9, now `builtins` should be used.
e.g. `list` directly instead of `typing.List`. See [PEP 585](https://peps.python.org/pep-0585).

#### Code Example

❌:
```py
class Solution:
    def findMedianSortedArrays(self, nums1: List[int], nums2: List[int]) -> float:
```
✅:
```py
class Solution:
    def findMedianSortedArrays(self, nums1: list[int], nums2: list[int]) -> float:
```

#### Language used for code

Python3

#### But Why?
There won't be an error if we still use `typing`, but I know LeetCode follows the best standards, and so this minor thing should be implemented!

Thanks!

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've submitted your feedback to the team. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by samyak1409** [comment]
Hey, just wanna know that if the issue is not fixed, why did you close the issue here?
