### ISSUE TITLE
Missing Test case 3 - 1640. Check Array Formation Through Concatenation

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1308]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Below code - fails below test case:

	Your input
		[85,1,2]
		[[85,2,1]]
	Output		true
	Expected	false

		Wrong Answer

#### Code you used for Submit/Run operation

```
class Solution:
    def canFormArray(self, arr: List[int], pieces: List[List[int]]) -> bool:
        d = {p[0]: p for p in pieces}
        i = 0
        while i < len(arr):
            if arr[i] not in d or len(arr) - i < len(d[arr[i]]):
                return False
            i += len(d[arr[i]])
        return True 
```

#### Language used for code
Python3

#### Expected behavior

- Judge has weak tests like last time. Discuss now will be filled with wrong solutions
- Judge must have a proper & good number of test cases.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
