### ISSUE TITLE
Missing Test Case - 1873. Calculate Special Bonus

### ISSUE THREAD

**Issue by PunkWeeb** [LeetCode-Feedback/LeetCode-Feedback#13081]
#### Your LeetCode username

user6313UC

#### Category of the bug
- [ ] Question
- [X ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Submitting a response to a SQL query, even with my output matching the expected output, I get an error as the Wrong Answer

#### Code you used for Submit/Run operation

```
SELECT employee_id,
    CASE
        WHEN MOD(employee_id, 2) = 1 
            AND name NOT LIKE 'M%'
            THEN SUM(salary)
        ELSE '0'
    END as bonus
FROM Employees
GROUP BY employee_id
ORDER BY employee_id;
```

#### Language used for code

SQL

#### Expected behavior

I believe I should get the question correct, where I did not.

#### Screenshots

![image](https://user-images.githubusercontent.com/131520131/233773178-34d6c772-bda3-4b4c-b19b-81638773c369.png)

#### Additional context

Looking at the Solutions tab, other people had some of the same code I had, but didnt say it caused an issue

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
