### ISSUE TITLE
Missing Test Case - 73. Set Matrix Zeroes

### ISSUE THREAD

**Issue by Zabiea** [LeetCode-Feedback/LeetCode-Feedback#13084]
#### Missing Test Cases
- [ ] Question
- [ ] Solution
- [ ] Language
- [*] Missing Test Cases 

#### Description of the bug
my thought was to first make the row and column as -1 and then convert all the -1 to 0's.but the code stuck on the -1 test case then I tried to use -2^31. that also got stuck on test case, and then I  used the number -21473648 and my code got accepted. i know its not possible to make a test case for every integer but still its a bug

#### Code you used for Submit/Run operation

```
// Set matrices Zeros
class Solution {
public:
    void markrow(vector<vector<int>>& matrix,int n,int m,int i) {
        for(int j=0;j<m;j++){
            if(matrix[i][j]!=0)
                matrix[i][j]=-21473648;
        }

    }
    void markcol(vector<vector<int>>& matrix,int n,int m,int j) {
        for(int i=0;i<n;i++){
            if(matrix[i][j]!=0)
                matrix[i][j]=-21473648;
        }

    }
    void setZeroes(vector<vector<int>>& matrix) {
        int n=matrix.size();
        int m=matrix[0].size();
        for(int i=0;i<n;i++){
            for(int j=0;j<m;j++){
                if(matrix[i][j]==0){
                    markcol(matrix,n,m,j);
                    markrow(matrix,n,m,i);
                }
            }
        }
        for(int i=0;i<n;i++){
            for(int j=0;j<m;j++){
                if(matrix[i][j]==-21473648){
                    matrix[i][j]=0;
                }
            }
        }

    }
};
	
```

#### Language used for code

C++

#### Screenshots

- [ ] 
<img width="954" alt="Screenshot 2023-04-22 163346" src="https://user-images.githubusercontent.com/54613191/233780559-1bd5e748-a62c-4a29-83ad-6eac2930f05d.png">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
