### ISSUE TITLE
Missing Test Case - 1640. Check Array Formation Through Concatenation

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#1309]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution from discuss section is accepted but fails on the following test case:

[100, 2, 98, 28, 44, 55, 37]
[[28, 46, 57], [37, 19, 40, 38]]

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean canFormArray(int[] arr, int[][] pieces) {
        
        Map<Integer, Integer> map = new HashMap<>();
        for(int i=0;i<arr.length;i++)
        {
            map.put(arr[i], i);
        }
        
        for(int[] piece : pieces)
        {
            if(piece.length==1 && map.containsKey(piece[0]))
                continue;
            else if(piece.length>1 && map.containsKey(piece[0]))
            {
                int cur = map.get(piece[0]);
                for(int j=1;j<piece.length;j++)
                {
                    cur++;
                    if(map.containsKey(piece[j]) && cur!=map.get(piece[j]))
                        return false;
                }
            }
            else
                return false;
        }
        return true;
    }
}
```

#### Language used for code
Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/97805116-1dd69500-1c22-11eb-913e-ada767892186.png)
![image](https://user-images.githubusercontent.com/32546406/97805126-2cbd4780-1c22-11eb-89e0-0c61e97a1091.png)

#### Additional context

Link to the original solution: https://leetcode.com/problems/check-array-formation-through-concatenation/discuss/918797/Java-1-ms-solution-with-explanation

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
