### ISSUE TITLE
Solution has incorrect condition - 1239. Maximum Length of a Concatenated String with Unique Characters

### ISSUE THREAD

**Issue by vinitamaloo-asu** [LeetCode-Feedback/LeetCode-Feedback#13092]
#### Your LeetCode username

jethalel

#### Category of the bug
- [1239] Question
- [ https://leetcode.com/problems/maximum-length-of-a-concatenated-string-with-unique-characters/submissions/938078664/] Solution
- [ java] Language

#### Description of the bug

Approach 1 - optimized solution in Editorial has an if condition which is doing nothing.
In the java solution(line 32), cpp(line 34), python(line 30), javascript(line 31).
The if condition checks for the presence of a bitmap in the hashset. All the bitmaps in the hashset are a combination of
"length" + "character bitset". However, in the if condition, the bitmap which is to be checked in the hashmap does not have length set to it.
The if condition should be updated with the below:
```
if (results.contains(charBitSet + (word.length() << 26)))
            return;
```

#### Code you used for Submit/Run operation

```
class Solution {

    int max = 0;
    private void addWord(String s, Set<Integer> res) {
        int bitmap = 0;
        for (int j = 0; j < s.length(); ++j) {
            int currBit = 1 << (s.charAt(j) - 'a');
            if ((bitmap & currBit) > 0)
                return;
            bitmap |= currBit;
        }

        if (res.contains(bitmap | (s.length() << 26)))
            return;

        Set<Integer> newBitset = new HashSet<>();
        for (int combined : res) {
            if ((combined & bitmap) > 0)
                continue;
            int newLen = (combined >> 26) + s.length();
            int newbitset = (bitmap | combined) & ((1 << 26) - 1);

            newbitset |= newLen << 26;
            newBitset.add(newbitset);
            max = Math.max(max, newLen);
        }

        res.addAll(newBitset);
    }

    //iterative
    public int maxLength(List<String> arr) {
        Set<Integer> res = new HashSet<>();
        res.add(0);
        for (String s : arr)
            addWord(s, res);

        return max;
    }
}```

#### Language used for code
<!-- C++ -->
Java

#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->



#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
