### ISSUE TITLE
GCD computation issue in LeetCode question [2654]".

### ISSUE THREAD

**Issue by akhil27styles** [LeetCode-Feedback/LeetCode-Feedback#13097]
#### Your LeetCode username
 akhil_

#### Category of the bug
- [x] Solution 

#### Description of the bug

for this test case [6,10,15]
this code is giving 6 & 15 GCD as 1 but it should not give 1, 

#### Code you used for Submit/Run operation

```
//  Minimum Number of Operations to Make All Array Elements Equal to 1

class Solution {
        private int gcd(int num1, int num2) {
       int gcd = Math.abs(num1);
        int temp = 0;
        while (num2 != 0) {
            temp = num2;
            num2 = gcd % num2;
            gcd = temp;
        }
        return gcd;
    }
    public int minOperations(int[] nums) {
         int n = nums.length;
        int ones = 0;
        for (int num : nums) {
            if (num == 1) {
                ones++;
            }
        }
         if (ones > 0) {
            return n - ones;
        }
        int res = Integer.MAX_VALUE;
        for(int i=0;i<n;i++){
            int g=nums[i];
            for(int j=i+1;j<n;j++){
                g=gcd(g,nums[j]);
               if(g==1){
                    System.out.println(nums[i] +" "+ nums[j] +" " +g); 
                   res=Math.min(res,j-i);
               }
            }
        }
        if (res == Integer.MAX_VALUE) {
            return -1;
        }
        return res + n - 1;
    }
}
```

#### Expected behavior

6 and 15 gcd should be 3 but it giving 1

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
