### ISSUE TITLE
Missing Test Case - 1312. Minimum Insertion Steps to Make a String Palindrome

### ISSUE THREAD

**Issue by luffy-idli** [LeetCode-Feedback/LeetCode-Feedback#13091]
#### Your LeetCode username

me2G4m3r

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [* ] Missing Test Cases 

#### Description of the bug
Its not actually a bug. I was trying to solve the above question, with an idea.
The test case on which my submission failed was too big to think through my logic.
Instead a simpler test case would have helped me sooner.
This is the existing testcase that failed for me: "dyyuyabzkqaybcspq"
Instead this would have been faster in finding my problem: "abab"

My logic was to use a one-pass solution by just maintaining a dictionary of counters for the left
and right part of the string. Turns out, the order of those characters matters too. So, my original idea is wrong.

Please add the following simple test case: "abab"

#### Code you used for Submit/Run operation

```
class Solution:
    def minInsertions(self, s: str) -> int:
        charMapRight = {}
        charMapLeft = {}
        for char in s:
            charMapRight[char] = charMapRight.get(char,0) + 1
            charMapLeft[char]=0
        #inital setup
        charMapRight[s[0]] -= 1
        bal = [0,len(s)-1]
        ans=len(s)-1
        i=0
        while i < len(s)-1:
            #first deal with current middle character moving out
            #check for any common charcter in right
            if charMapRight[s[i]]>0:
                charMapRight[s[i]]-=1
                bal[1] -= 1
            else:
                charMapLeft[s[i]] += 1
                bal[0]+=1
            #compare answer here too, as if a new character is being inserted as the middle instead of making the next character as middle
            ans = min (ans,bal[1]+bal[0])
            #Now deal with next charcter becoming middle
            if charMapRight[s[i+1]] ==0:
                charMapLeft[s[i+1]] += 1
                bal[0]+=1
            else:
                charMapRight[s[i+1]] -= 1
                bal[1]-=1
            ans=min(ans,bal[1]+bal[0])
            i+=1
        return ans
```

#### Language used for code

python3

#### Expected behavior

I expected it to fail with a simpler testcase which would have helped me debug my thoughts a bit faster.
The test case on which my solution failed was too big to run it in my brain. I had to use debugger and spend more time to debug this.
A smaller, concise test case would have been helpful

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
