### ISSUE TITLE
预期结果错误 LCP 75. 传送卷轴

### ISSUE THREAD

**Issue by LiuZengqiang** [LeetCode-Feedback/LeetCode-Feedback#13099]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名
4z9
**Bug 类型**
- [ ] 题目
- [x] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
题目 LCP 75. 传送卷轴 若输入为``["S..","##T"]``时，预期结果显示为``-1``，但是正确的结果应该为``3``，即在``(0,2)``处释放卷轴。

**屏幕截图**
<img width="128" alt="Snipaste_2023-04-23_17-02-55" src="https://user-images.githubusercontent.com/74355935/233830441-888aef46-4370-45e5-9065-0f64bc47918e.png">

**Comment by feiceh** [comment]
你好，在与相关团队核实后：不处理，不符合提示范围 （maze.length == maze[i].length）
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
