### ISSUE TITLE
Incorrect Rust code definition in the 'Min Stack' problem 

### ISSUE THREAD

**Issue by evgeni-nabokov** [LeetCode-Feedback/LeetCode-Feedback#131]
**What kind of the bug**
- [*] solution

**Describe the bug**
It is impossible to submit a correct Rust solution, because the grader does not accept `Option<T>` as a result.

**What language is your code written in**
Rust

**The code you submit/run**
```
struct MinStack {
    container: Vec<(i32, i32)>,
}

impl MinStack {

    /** initialize your data structure here. */
    fn new() -> Self {
        MinStack { container: Vec::with_capacity(64) }
    }

    fn push(&mut self, x: i32) {
        self.container.push((x, min(x, self.container.last().unwrap_or(&(x, x)).1)));
    }

    fn pop(&mut self) {
        self.container.pop();
    }

    fn top(&mut self) -> Option<i32> {
        if self.container.is_empty() {
            None
        } else {
            Some(self.container.last().unwrap().0)
        }
    }

    fn get_min(&self) -> Option<i32> {
        if self.container.is_empty() {
            None
        } else {
            Some(self.container.last().unwrap().1)
        }
    }
}
```

**Expected behavior**
Correct processing of `Option<T>`.

**Additional context**
My suggestions: https://support.leetcode.com/hc/en-us/community/posts/360043300294-Incorrect-Rust-code-definition-in-the-Min-Stack-problem

**Comment by CooperCooperCooper** [comment]
Hi @evgeni-nabokov,
Thank you for reaching out to us! I've relayed your feedback to our engineers to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @evgeni-nabokov,
Thank you for your time! We've found some viable Rust solutions in the problem discuss section. Please check out this [Rust solution with 0ms post](https://leetcode.com/problems/min-stack/discuss/345588/Rust-solution%3A-0ms) and this [One stack Rust solution post](https://leetcode.com/problems/min-stack/discuss/350778/My-Rust-solution-using-one-stack). We appreciate your time and support.

**Comment by evgeni-nabokov** [comment]
Not so fast!
Let me test those so-called "solutions". I am going to write test cases according to the syntax used in the example of the task.
1. https://leetcode.com/problems/min-stack/discuss/345588/Rust-solution%3A-0ms
**Test 1**
```
MinStack minStack = new MinStack();
minStack.pop(); // Runtime Error
```
**Test 2**
```
MinStack minStack = new MinStack();
minStack.top(); // Runtime Error
```
**Test 3**
```
MinStack minStack = new MinStack();
minStack.get_min(); // Runtime Error
```

2. https://leetcode.com/problems/min-stack/discuss/350778/My-Rust-solution-using-one-stack
**Test 1**
```
MinStack minStack = new MinStack();
minStack.top(); // Runtime Error
```
**Test 2**
```
MinStack minStack = new MinStack();
minStack.get_min(); // 2147483647 -- wrong answer, should be 42.
```

The description of the task does not bound a single limitation for the input.

**Comment by CooperCooperCooper** [comment]
Hi @evgeni-nabokov,
Thank you for your time. We took a thorough look at the additional feedback. For this problem, we found out that the issue is caused by not by Rust but by not having the problem description updated to the current standard. We've updated the problem description since, so please check it out and see if it helps you on solving those issues. 

Since your feedback helps us with improving this problem, please share your username, your Github info (as a form of verification) and this issue to support@leetcode.com to receive the content issue contribution reward. If you have any questions, please don't hesitate to let me know. Thank you.

**Comment by evgeni-nabokov** [comment]
Yes, that constraint let Rust solutions avoid the problems I described in the issue.
