### ISSUE TITLE
Missing Test Case - 1978. Employees Whose Manager Left the Company

### ISSUE THREAD

**Issue by just-small-potato** [LeetCode-Feedback/LeetCode-Feedback#13108]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A submission with incorrect salary condition is accepted. In the problem statement, it says:
> report the IDs of the employees whose salary is strictly less than $30000

However, submission with where clause `salary <= 30000` is being accepted.

#### Code you used for Submit/Run operation

```
SELECT employee_id FROM Employees
WHERE manager_id NOT IN (SELECT employee_id FROM Employees) AND salary <= 30000
ORDER BY employee_id ASC;
```

#### Language used for code
MySQL

#### Expected behavior

Submission should not be accepted as `salary <= 30000` does not satisfy requirement:
> report the IDs of the employees whose salary is strictly less than $30000

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

Please provide the test case explicitly and in JSON format. Like in the old version. An example: {"headers":{"Activity":["player_id","device_id","event_date","games_played"]},"rows":{"Activity":[[1,2,"2016-03-01",5],[1,2,"2016-03-02",6],[2,3,"2017-06-25",1],[3,1,"2016-03-01",0],[3,4,"2018-07-03",5]]}}

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by just-small-potato** [comment]
@LC-Pam Would this help?

```
{"headers": {"Employees": ["employee_id", "name", "manager_id", "salary"]}, "rows": {"Employees": [[3, "Mila", 9, 60301], [12, "Antonella", null, 31000], [13, "Emery", null, 67084], [1, "Kalel", 11, 21241], [9, "Mikaela", null, 50937], [11, "Joziah", 6, 28485], [15, "Pam", 6, 30000]]}}
```

Explaination: Added a new data row `[15, "Pam", 6, 30000]` to example 1 which the employee has a salary hitting the boundary 30000. This shows as wrong answer with the sample SQL provided in the issue description, but the submission is accepted.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've used your feedback to update the problem.

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback.

Please provide us your LCUS account name.

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!

**Comment by just-small-potato** [comment]
@LC-Pam Thank you so much for taking a look at this issue. Here is my leetcode account name: [icelam](https://leetcode.com/icelam/). Have a happy weekend!

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
