### ISSUE TITLE
Missing Test Case - 1416. Restore The Array

### ISSUE THREAD

**Issue by ScarcePulkit** [LeetCode-Feedback/LeetCode-Feedback#13100]
#### Your LeetCode username

admirerider

#### Category of the bug
- [ Restore the array] Question
- [ pasted down] Solution
- [C++ ] Language
- [ pasted down] Missing Test Cases 

#### Description of the bug

When I submitted the code, it got accepted but actually it shouldn't. There was an edge case which I think has got missed, s =
"100000000011" and k = 1000000000. According to problem statement, it should have given 2 but my code gave 0 as an output

#### Code you used for Submit/Run operation

```
// Restore the array
class Solution {
public:
    int mod = 1e9+7;
    int f(int ind, string &s, int k, vector<int> &dp){
        if(ind >= s.size()){
            return 1;
        }

        if(dp[ind] != -1){
            return dp[ind];
        }

        int take = 0;
        int i = ind;
        string temp;

        if(s[ind] == '0'){
            return dp[ind] = 0;
        }

        while(i < s.size() && (i-ind) <= 8){
            temp.push_back(s[i]);
            if(stoi(temp) <= k){
                take = (take + f(i+1,s,k,dp))%mod;
            }
            i++;
        }
        return dp[ind] = take%mod;
    }
    int numberOfArrays(string s, int k) {
        int n = s.size();
        vector<int> dp(n,-1);
        return f(0,s,k,dp);
    }
};
```

#### Language used for code

C++

#### Expected behaviour

When I submitted the code, it got accepted but actually it shouldn't. There was an edge case which I think has got missed, s =
"100000000011" and k = 1000000000. According to problem statement, it should have given 2 but my code gave 0 as an output

#### Screenshots

<img width="862" alt="Screenshot 2023-04-23 at 2 44 51 PM" src="https://user-images.githubusercontent.com/93707577/233830878-6566e93b-8965-4b21-b251-e6f01433460d.png">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
