### ISSUE TITLE
Missing Test Case - 1416. Restore The Array

### ISSUE THREAD

**Issue by momocats** [LeetCode-Feedback/LeetCode-Feedback#13104]
#### Your LeetCode username
momolon

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [# ] Missing Test Cases 

#### Description of the bug
I passed all the testcase and accepted, but the testcase k < 10 and s is used the digit bigger than k, I failed the testcase.  eg. s='5', k=4

#### Code you used for Submit/Run operation

```
class Solution:
    def numberOfArrays(self, s: str, k: int) -> int:

        mod = (10 ** 9) + 7
        dp = [[0] * len(s) for _ in range(2)]
        if s[0] == '0':
            return 0
        else:
            dp[1][0] = 1
        cur = collections.deque([(int(s[0]), 1)])
        for i, c in enumerate(s):
            
            if i == 0:
                continue

            temp = 0
            for _ in range(len(cur)):
                num, count = cur.popleft()
                if num * 10 + int(c) <= k:
                    temp += count
                    cur.append((num * 10 + int(c), count))
            dp[0][i] = temp % mod
            
            if int(c) != 0:
                dp[1][i] = (dp[0][i-1] + dp[1][i-1]) % mod
                cur.append((int(c), dp[1][i]))
            
            if dp[0][i] + dp[1][i] == 0:
                return 0
        
        return (dp[0][-1] + dp[1][-1]) % mod
```

#### Language used for code
Python 3

#### Expected behavior
'wrong answer' is correct, but the same test case is not included in. 

#### Screenshots

![image](https://user-images.githubusercontent.com/131587645/233833834-e07e16df-b75c-4024-b805-ebbf36a25ddd.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
