### ISSUE TITLE
1214. Two Sum BSTs - Broken image

### ISSUE THREAD

**Issue by mnaoumov** [LeetCode-Feedback/LeetCode-Feedback#13112]
#### Your LeetCode username

mnaoumov

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Solution has a broken link to a non-existent image https://leetcode.com/problems/two-sum-bsts/Figures/1214/mt.png

#### Expected behavior

Proper image is loaded

#### Screenshots

![image](https://user-images.githubusercontent.com/735878/233860850-d78aaac4-167b-4083-9b4e-e251752e76fa.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
