### ISSUE TITLE
A Follow-up Requirement Should be Added - 2652.Sum Multiples

### ISSUE THREAD

**Issue by shit-eater** [LeetCode-Feedback/LeetCode-Feedback#13118]
Your LeetCode username
v5qYY4Q65w

Category of the bug
- [√] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

Description of the bug
This problem can be solved in O(1) complexity. But the O(n) brute force can be accpted during the contest because of the constraints of n is only 1000. If this problem appears in an interview, the expected solution will not be brute force. So a follow-up should be added:
Can you solve this problem in O(1) time complexity?

Code you used for Submit/Run operation

O(n) Brute force:
```
class Solution:
    def sumOfMultiples(self, n: int) -> int:

        return sum(p*(p%3==0 or p%5==0 or p%7==0) for p in range(n+1))
```

O(1) Solution:
```
class Solution:
    def sumOfMultiples(self, n: int) -> int:

        def count(p):
            k = n//p
            return p*k*(k+1)//2
        
        return count(3)+count(5)+count(7)-count(15)-count(21)-count(35)+count(105)
```

Language used for code
Python3

Expected behavior
A follow-up requirement should be added:
Can you solve this problem in O(1) time complexity?

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
