### ISSUE TITLE
Missing Test Case - 55. Jump Game

### ISSUE THREAD

**Issue by KR4KENX** [LeetCode-Feedback/LeetCode-Feedback#13113]
test [2,1,0,0] expects true but I can't consider why, when you hit on index 2 you reach 0 so it's should be false

**Comment by stormsunshine** [comment]
The expected result is false for this test case. Where do you see the expected result is true?

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
