### ISSUE TITLE
Missing Test Case - 373. Find K Pairs with Smallest Sums

### ISSUE THREAD

**Issue by wksinha** [LeetCode-Feedback/LeetCode-Feedback#13128]
#### Your LeetCode username

warks

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ . ] Missing Test Cases 

#### Description of the bug

An alternative solution to the problem exists, where we find the lowest upper bound on the sum of nums1[i] and nums2[j], such that at least k pairs with sum equal to or under are available, and then add all such pairs, and sort to find the smallest k pairs.
This solution is susceptible to the case where there are many values equal to the lowest upper bound, and therefore the complexity would actually explode to (m * n * log(m * n)) where m=nums1.length, and n=num2.length.
#### Example adversarial input:
nums1 = [0] * $10^5$,
nums2 = [1] * $10^5$,
k = $10^4$
Here, all $10^{10}$ pairs satisfy the lowest upper bound and would be taken. Such a situation should lead to a TLE.

#### Code you used for Submit/Run operation

```
class Solution {
    public List<List<Integer>> kSmallestPairs(int[] nums1, int[] nums2, int k) {
        long left = -2_000_000_000;
        long right = -left;

        long maxValue = right;
        while (left <= right) {
            long mid = (left + right) / 2;
            if (isPossible(nums1, nums2, mid, k)) {
                maxValue = mid;
                right = mid - 1;
            } else {
                left = mid + 1;
            }
        }

        List<List<Integer>> smallestPairs = new ArrayList<>();
        for (int i = 0; i < nums1.length; i++) {
            int j = 0;
            while (j < nums2.length && nums1[i] + nums2[j] <= maxValue) {
                List<Integer> pair = new ArrayList<>(2);
                pair.add(nums1[i]);
                pair.add(nums2[j]);
                smallestPairs.add(pair);
                j++;
            }
        }

        Collections.sort(smallestPairs, (a, b) -> a.get(0) + a.get(1) - b.get(0) - b.get(1));
        return smallestPairs.stream().limit(k).collect(Collectors.toList());
    }

    private boolean isPossible(int[] nums1, int[] nums2, long sum, int k) {
        long found = 0;

        for (var first : nums1) {
            int secondIdx = -1;
            int left = 0;
            int right = nums2.length - 1;
            while (left <= right) {
                int mid = (left + right) >> 1;
                if (first + nums2[mid] <= sum) {
                    secondIdx = mid;
                    left = mid + 1;
                } else {
                    right = mid - 1;
                }
            }
            
            found += secondIdx + 1;
        }

        return found >= k;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The program should have yielded a TLE response, but instead, it ACs.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
