### ISSUE TITLE
Missing Test Case - 1416. Restore The Array

### ISSUE THREAD

**Issue by ScarcePulkit** [LeetCode-Feedback/LeetCode-Feedback#13127]
#### Your LeetCode username

admirerider

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [--] Missing Test Cases 

#### Description of the bug

When I submitted the code, it got accepted but actually it shouldn't. There was an edge case which I think has got missed, s =
"100000000011" and k = 1000000000. According to problem statement, it should have given 2 but my code gave 0 as an output

#### Code you used for Submit/Run operation

```
// Restore the array
class Solution {
public:
    int mod = 1e9+7;
    int f(int ind, string &s, int k, vector<int> &dp){
        if(ind >= s.size()){
            return 1;
        }

        if(dp[ind] != -1){
            return dp[ind];
        }

        int take = 0;
        int i = ind;
        string temp;

        if(s[ind] == '0'){
            return dp[ind] = 0;
        }

        while(i < s.size() && (i-ind) <= 8){
            temp.push_back(s[i]);
            if(stoi(temp) <= k){
                take = (take + f(i+1,s,k,dp))%mod;
            }
            i++;
        }
        return dp[ind] = take%mod;
    }
    int numberOfArrays(string s, int k) {
        int n = s.size();
        vector<int> dp(n,-1);
        return f(0,s,k,dp);
    }
};
```

#### Language used for code

C++

#### Expected behavior

When I submitted the code, it got accepted but actually it shouldn't. There was an edge case which I think has got missed, s =
"100000000011" and k = 1000000000. According to problem statement, it should have given 2 but my code gave 0 as an output

#### Screenshots

![image](https://user-images.githubusercontent.com/93707577/233931835-5190a0db-877e-4517-8115-9521521d01b5.png)

**Comment by LC-Pam** [comment]
Duplicated with https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/13100
