### ISSUE TITLE
Missing test cases 1046. Last Stone Weight

### ISSUE THREAD

**Issue by hehai123** [LeetCode-Feedback/LeetCode-Feedback#13121]
#### Your LeetCode username

JohnTan213

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x] Missing Test Cases 

#### Description of the bug

The test cases are insufficient as the code below that should not work is able to pass all the current test cases. 

#### Code you used for Submit/Run operation

```
class Solution:
    def lastStoneWeight(self, stones: List[int]) -> int:
        if len(stones) <= 5:
            stones = [-s for s in stones]
            heapify(stones)

            while len(stones) > 1:
                a = heappop(stones)
                b = heappop(stones)
                if a == b:
                    continue
                if a > b:
                    heappush(stones, b - a)
                else:
                    heappush(stones, a - b)
            
            if len(stones) == 1:
                return -stones[0]
            else:
                return 0

        total = sum(stones)
        if total % 2 == 0:
            return 0
        else:
            return 1
```

#### Language used for code

Python

#### Expected behavior

There should be some test cases that fails the above code when length of stones is 6 and above.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by hehai123** [comment]
Here are some missing test cases that will not allow the above code to pass:

[10,4,2,10,10,10]
[1,1,1,1,1,10]
[1,2,3,4,5,17]
[1,2,3,4,5,6,7,8,9,100]

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
