### ISSUE TITLE
Missing Test Case - 1642. Furthest Building You Can Reach

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#1312]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution from discuss section is accepted, but fails on the following test case:

[1642_test_case2.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/5471879/1642_test_case2.txt)

#### Code you used for Submit/Run operation

```
class Solution {
    public int furthestBuilding(int[] heights, int bricks, int ladders) {
        long l = 1, r = 1_000_000_000;
        
        while (l + 2 < r) {
            int tl = (int) ((l + l + r) / 3);
            int tr = (int) ((l + r + r) / 3);
            
            int tlRes = findLargestIndex(heights, bricks, ladders, tl);
            int trRes = findLargestIndex(heights, bricks, ladders, tr);
            
            if (tlRes >= trRes) {
                r = tr;
            } else {
                l = tl;
            }
        }
        
        int answer = 0;
        while (l <= r) {
            int cur = findLargestIndex(heights, bricks, ladders, (int) l++);
            answer = Math.max(answer, cur);
        }
        
        return answer;
    }
    
    private int findLargestIndex(int[] heights, int bricks, int ladders, int minLadderHeight) {
        int idx = 1;
        
        while (idx < heights.length) {
            int difference = heights[idx] - heights[idx - 1];
            
            if (difference > 0) {
                if ((difference >= minLadderHeight || bricks < difference) && ladders > 0) {
                    ladders--;
                } else if (bricks >= difference) {
                    bricks -= difference;
                } else {
                    break;
                }
            }
            
            idx++;
        }
        
        return idx - 1;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/97817078-03270f00-1c68-11eb-87e8-481efb768b75.png)
![image](https://user-images.githubusercontent.com/32546406/97817087-133eee80-1c68-11eb-8c39-e0d6f9cbd6fe.png)

#### Additional context

Link to the original solution:
https://leetcode.com/problems/furthest-building-you-can-reach/discuss/918897/Java-Ternary-Search-solution-in-O(N-log-M)

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
