### ISSUE TITLE
Missing Optimised Solution [230. Kth Smallest Element in a BST]

### ISSUE THREAD

**Issue by Sohan022** [LeetCode-Feedback/LeetCode-Feedback#13122]
#### Your LeetCode username
 Sohan022

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug 
 
An optimized Solution is Missing for this problem [230. Kth Smallest Element in a BST](https://leetcode.com/problems/kth-smallest-element-in-a-bst)

It can also be solved using **Morris Traversal** in an optimized way.

In this method, we have to use a new data structure-Threaded Binary Tree, and the strategy is as follows:

Step 1: Initialize current as root

Step 2: While the current is not NULL,

If current does not have left child

    a. Add current’s value

    b. Go to the right, i.e., current = current.right

Else

    a. In current's left subtree, make current the right child of the rightmost node

    b. Go to this left child, i.e., current = current.left
For example:

          4
        /   \
       2     6
      / \   /
     1   3 5
First, 4 is the root, so initialize 4 as current, 4 has the left child which is 2, and the current's left subtree is

         2
        / \
       1   3
So in this subtree, the rightmost node is 3, then make the current(4) as the right child of 5. Set current = cuurent.left (current = 2). The tree now looks like this:

         2
        / \
       1   3
            \
             4
              \
               6
              /
             5
For current 2, which has left child 1, we can continue with the same process as we did above

        1
         \
          2
           \
            3
             \
              4
               \
                6
               /
              5
then count 1 as the 1st smallest node because it has no left child, then count 2, 3, 4 one by one, for node 6 which has left child 5, do the same as above.
we will be also checking count is equal to k then return that element.

**Time complexity**: $$O(n)$$
**Space complexity**: $$O(1)$$

#### Code you used for Submit/Run operation

```
/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
class Solution {
public:
    
    int kthSmallest(TreeNode* root, int k) {
        TreeNode *cur = root;
        int count = 0;
        
        while(cur){
            if(cur->left){
                TreeNode *prev = cur->left;
                while(prev->right) prev = prev->right;
                
                TreeNode *temp = cur;
                prev->right = cur;
                cur = cur->left;
                temp->left = NULL;
            }
            else{
                ++count;
                if(count == k) return cur->val;
                cur = cur->right;
            }
        }
        return 0;
    }
};
```

#### Language used for code
 C++

#### Expected behavior

Optimized Solution should have Time Complexity of O(n) and Space complexity of O(1)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've submitted this to the team.

The team will check your feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by Sohan022** [comment]
@LC-Pam this issue is closed, but this solution is not appearing in the editorial section.
