### ISSUE TITLE
Submission not match with Run Code Result - 2336. Smallest Number in Infinite Set

### ISSUE THREAD

**Issue by tgldr** [LeetCode-Feedback/LeetCode-Feedback#13136]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
I ran my code using an example test case, but when I submitted it, I received a 'Wrong answer' message. However, when I copied the input from the failed case and clicked 'Run Code', it was accepted. But when I clicked 'Submit', it failed.

#### Code you used for Submit/Run operation

```
let set = new Set();
let pq = new MinPriorityQueue();
var SmallestInfiniteSet = function() {
    for(let i=1; i<=1000; i++) {
        set.add(i);
        pq.enqueue(i);
    }
};

/**
 * @return {number}
 */
SmallestInfiniteSet.prototype.popSmallest = function() {
    const min = pq.dequeue().element;
    set.delete(min);
    return min;
};

/** 
 * @param {number} num
 * @return {void}
 */
SmallestInfiniteSet.prototype.addBack = function(num) {
    if(!set.has(num)) {
        pq.enqueue(num);
        set.add(num);
    }
};

/** 
 * Your SmallestInfiniteSet object will be instantiated and called as such:
 * var obj = new SmallestInfiniteSet()
 * var param_1 = obj.popSmallest()
 * obj.addBack(num)
 */
```

#### Language used for code
JavaScript

#### Screenshots

<img width="1340" alt="Screenshot 2023-04-24 at 19 15 17" src="https://user-images.githubusercontent.com/8258715/234142974-17285278-491b-4fe2-9ddb-fc330ed2abb0.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output values.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!
