### ISSUE TITLE
Missing Test Case - 2336. Smallest Number in Infinite Set

### ISSUE THREAD

**Issue by rahulm682** [LeetCode-Feedback/LeetCode-Feedback#13138]
#### Your LeetCode username
rahulm682

#### Category of the bug
- [ ] Missing Test Cases 
["SmallestInfiniteSet","addBack","popSmallest","popSmallest","popSmallest","addBack","popSmallest","popSmallest","popSmallest","popSmallest","popSmallest","popSmallest","popSmallest","popSmallest","popSmallest","popSmallest","popSmallest","popSmallest"]
[[],[20],[],[],[],[1],[],[],[],[],[],[],[],[],[],[],[],[]]

#### Description of the bug
The problem is missing a testcase and on submitting the code problem gets accepted.
As we need to return the current smallest number and if we insert any number larger than range we are currently storing in our data structure and then if we continously pop the smallest one until our range gets exhausted. The only number that is left out in the data structure will be the number which was out of range, and on popping we get that number instead of range+1.

The below testcase should not have been accepted by the judge
As it is missing we get the accepted solution 

#### Code you used for Submit/Run operation

```
class SmallestInfiniteSet {
    int cnt;
    TreeSet<Integer> ts;

    public SmallestInfiniteSet() {
        ts = new TreeSet<>();

        for(int i=1;i<=10;i++) ts.add(i);
        cnt = 11;
    }
    
    public int popSmallest() {
        if(ts.isEmpty()) ts.add(cnt++);
        return ts.pollFirst();
    }
    
    public void addBack(int num) {
        ts.add(num);
    }
}
```

#### Language used for code
JAVA

#### Expected behavior
The code should not be accepted and instead wrong answer should be printed

**Comment by cswartzell** [comment]
This isnt a bug, rather its an issue with how you are understanding the question. Our set should effectively _already_ contain **all** the positive integers. This code is indeed valid as you are expecting 20 to not be included as you didnt add it in the first place, but thats the wrong way to think about it: 20 should have been there all along. Per the prompt we are to start with ALL the positive integers already available. I dont know why you are listing only the first 10 ints as a valid range to track and believe you can exhaust them. You should theoretically be able to popSmallest forever, until you hit max_int or whatever. 

Adding a number to your range that had not ben previously popped should indeed do nothing. The solution is correct.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
