### ISSUE TITLE
Missing Test Case - 1046. Last Stone Weight

### ISSUE THREAD

**Issue by ramanabhinav7** [LeetCode-Feedback/LeetCode-Feedback#13135]
#### Category of the bug
- [ ] Question
- 1046. Last Stone Weight
- [ ] Solution
-class Solution {
public:
    int lastStoneWeight(vector<int>& stones) {
        if( stones.size()==1){
                return stones[0];
            }
        sort( stones.begin(),stones.end());

        for( int i=stones.size()-1;i>=0;){
           if( stones.size()<=1){
                break;
           }
            if( stones[i]==stones[i-1]){
              
                stones.pop_back();
                stones.pop_back();
                i-=2;
            }
            else{
                if( stones.size()<=1){
                break;
                }
                int t = stones[i]-stones[i-1];
              
                stones.pop_back();
                stones.pop_back();
                stones.push_back(t);
                
                i-=1;
            }
            if( stones.size()<=1){
                break;
            }
            sort( stones.begin(),stones.end());

        }
        if( stones.size()==0){
            return 0;
        }
        return stones[0];

    }
};
- [ ] Language
- [ ] Missing Test Cases 
- [211,151,251,451,311,211,121,721,821,811,711,111,211,511,51,21,11,201,401,501,701,901,801,101,151,119,121,109,108,102]

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by ramanabhinav7** [comment]
Respected @LC-Pam ,
https://leetcode.com/submissions/detail/939078891/
this is the code submission link.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Test case [211,151,251,451,311,211,121,721,821,811,711,111,211,511,51,21,11,201,401,501,701,901,801,101,151,119,121,109,108,102] already exist. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
