### ISSUE TITLE
Incorrect Space Complexity for proposed solution - 149. Max points on a line

### ISSUE THREAD

**Issue by AdriaPares** [LeetCode-Feedback/LeetCode-Feedback#13148]
#### Your LeetCode username
morsaa

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The proposed solution states that the space complexity would be `O(n)`. However, unless I'm mistaken, in the worst-case scenario where each line contains at most 2 points, there will be `n*(n-1)/2` values stored in the hashmap, which would be `O(n^2)`.

This is equivalent to counting the number of edges in a complete graph of `n` nodes. See [this explanation].(https://math.stackexchange.com/questions/17747/why-a-complete-graph-has-fracnn-12-edges)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

The hash map is re-initialized for each fixed point.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
