### ISSUE TITLE
1302. Deepest Leaves Sum- Test Case 2 has different output in debug mode than submit/run for particular solution for particular solution

### ISSUE THREAD

**Issue by cswartzell** [LeetCode-Feedback/LeetCode-Feedback#13141]
#### Your LeetCode username

cswartzell

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [X] Broken Test Cases 

#### Description of the bug

There is a weird bug with test case 2 and the following code:

Test Case 2: [6,7,8,2,7,1,3,9,null,1,4,null,null,null,5]
	
When run through the Debugger line by line, this code (which is sound and should be right) outputs
the correct answer (19). When run or submitted however it outputs a DIFFERENT, incorrect answer (34).
This is singly threaded Python, there are no race conditions to contend with. Why would debug mode 
have a different output than running the same code normally?

#### Code you used for Submit/Run operation

```
class Solution:
    def deepestLeavesSum(self, root: Optional[TreeNode], lvl=0, sum_per_lvl=defaultdict(int)) -> int:
    
        sum_per_lvl[lvl] += root.val if root else 0
    
        if root.left:
          self.deepestLeavesSum(root.left, lvl+1, sum_per_lvl)
        if root.right:
          self.deepestLeavesSum(root.right, lvl+1, sum_per_lvl)
    
        return sum_per_lvl[max(sum_per_lvl.keys())]
```

#### Language used for code

Python 3.X

#### Expected behavior

Running code with the same input should have the same output in debug and normal submit/run conditions. This code seems logically sound and should pass all test cases. 

#### Additional context

User [vggm](https://leetcode.com/vggm/) originally posted this as their solution and didnt understand why it wouldnt work.

**Comment by cswartzell** [comment]
Upon further review, it seems like the whole problem is broken when using this solution. New test cases ALWAYS say the output is 34

try test case [6] with just a single node.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

**Comment by cswartzell** [comment]
Ok, but I gave you code that clearly doesnt work. If youd just try it youd see it doesnt
