### ISSUE TITLE
Missing Test Case - 139. Word Break

### ISSUE THREAD

**Issue by luzianl** [LeetCode-Feedback/LeetCode-Feedback#13149]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The problem constraints do not restrict words in wordDict from being longer than string s. However, solutions that do not check for out of range list index get accepted.

An accepted solution gets `IndexError: list index out of range` on the following valid test case:
s = "a"
wordDict = ["aa","aaa","aaaa","aaaaa","aaaaaa"]

#### Code you used for Submit/Run operation

```
class Solution:
    def wordBreak(self, s: str, wordDict: List[str]) -> bool:
        n = len(s)+1
        dp = [False] * n
        dp[0] = True
        
        for indx in range(1, n):
            for word in wordDict:
                if dp[indx - len(word)] and s[:indx].endswith(word):
                    dp[indx] = True
                    break
            
        return dp[-1]
```
This code is based on the Python3 solution with the 3rd best vote, which should not work: https://leetcode.com/problems/word-break/solutions/870388/python-simple-solution-explained-video-code-fastest/

#### Language used for code

Python3

#### Expected behavior

Expected: The submission should fail a test case with the Runtime Error: `IndexError: list index out of range`
Outcome: The submission was accepted.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback. 

Please reply this with your username. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by luzianl** [comment]
Thank you for addressing my feedback! I do not need a reward.
