### ISSUE TITLE
Missing Test Case - 707. Design Linked List

### ISSUE THREAD

**Issue by duanyaoguang** [LeetCode-Feedback/LeetCode-Feedback#13153]
#### Your LeetCode username
username:duanyaoguang
email: duanyg@emnets.org

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
lack of Test case to exam my bug, My Code is not right, but I can pass the test Cases. and I can offer a test case to judge it.

#### Code you used for Submit/Run operation

```java

//	数组实现
class MyLinkedList {

    private int[] array;
    private int MaxLength;
    private int length;
    private boolean[] flag;

    public MyLinkedList() {
        MaxLength = 1000;
        array = new int[MaxLength];
        Arrays.fill(array,-1);
        length = 0;
    }
    
    public int get(int index) {
        return array[index];
    }
    
    public void addAtHead(int val) {
        addAtIndex(0,val);
    }
    
    public void addAtTail(int val) {
        addAtIndex(length,val);
    }
    
    //	bug is here, I didnt judeg if index > length, but I still can pass
    public void addAtIndex(int index, int val) {
        if(length+1>MaxLength){
            MaxLength *= 2;
            int temp[] = new int[MaxLength];
            Arrays.fill(array,-1);
            for(int i=0;i<length+1;i++)temp[i] = array[i];
            array = temp;
        }
        for(int i=length;i>index;i--){
            array[i] = array[i-1];
        }
        array[index] = val;
        length++;
    }
    
    public void deleteAtIndex(int index) {
        if(array[index]==-1)return ;
        for(int i=index;i<length&&i+1<MaxLength;i++){
            array[i] = array[i+1];
        }
        length--;
    }
}
```

#### Language used for code
 Java 

#### Expected behavior

My Code is not right, but I can pass the test Cases.  the problem requires to skip the addAtIndex operation if index > length, but I didn't, I user An integer Array to implement the LinkedList, I add the value at index, even if index > length.

#### Screenshots
here is the wrong answer of my code
![image](https://user-images.githubusercontent.com/49652664/234518260-393b5ca1-181f-4adf-904d-e6797c22c0a6.png)
but I can pass the judge
![image](https://user-images.githubusercontent.com/49652664/234519669-005e9e75-c590-45a6-911c-a3779a102f09.png)

```
["MyLinkedList","addAtIndex","addAtIndex","addAtTail","get","deleteAtIndex","get"]
[[],[2,1],[3,4],[1],[0],[0],[0]]
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
