### ISSUE TITLE
836. Rectangle Overlap

### ISSUE THREAD

**Issue by agatagruza** [LeetCode-Feedback/LeetCode-Feedback#1315]
#### Your LeetCode username

gordonek

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language

#### Description of the bug

Provided solution Approach 1: Check Position is failing in the following test case:
`[-1,0,1,1]
[0,-1,0,1]`
#### Code you used for Submit/Run operation

```
// Rectangle Overlap
class Solution(object):
    def isRectangleOverlap(self, rec1, rec2):
        return not (rec1[2] <= rec2[0] or  # left
                    rec1[3] <= rec2[1] or  # bottom
                    rec1[0] >= rec2[2] or  # right
                    rec1[1] >= rec2[3])    # top
```

#### Language used for code

Python3

#### Expected behavior

Provided solution should accept given input. 

#### Screenshots

<img width="733" alt="Capture" src="https://user-images.githubusercontent.com/7014697/97917421-4ab1a780-1d09-11eb-8f7e-7f17a8f31b96.PNG">

**Comment by lc-kay** [comment]
Hi @agatagruza 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @agatagruza 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
