### ISSUE TITLE
Missing Test Case - 258. Add Digits

### ISSUE THREAD

**Issue by ernestwang100** [LeetCode-Feedback/LeetCode-Feedback#13156]
#### Your LeetCode username

ernestwang100

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

One of the test cases is wrong. While num = 38, the output expected is 2. It should be 11.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

class Solution {
    public int addDigits(int num) {
        return rec(num);
    }
    
    private int rec(int num){
        int reminder = num % 10;
        int quotient = num / 10;
        
        if(quotient <=0){
            return reminder;
        }
        else{
            return reminder + rec(quotient);
        }
    
    }
}

#### Language used for code

Java

#### Expected behavior

correct the wrong test case

#### Screenshots

![image](https://user-images.githubusercontent.com/62431512/234596492-bce6cd26-b409-4948-8827-64e632771459.png)

#### Additional context

Thanks

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by ernestwang100** [comment]
https://leetcode.com/problems/add-digits/
________________________________

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

**The code submission Accepted link.**

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by ernestwang100** [comment]
https://leetcode.com/problems/add-digits/submissions/940077149/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
