### ISSUE TITLE
1384. Total Sales Amount by Year - Duplicated column name

### ISSUE THREAD

**Issue by mnaoumov** [LeetCode-Feedback/LeetCode-Feedback#13165]
#### Your LeetCode username

mnaoumov

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Task description mentions `product_name` column twice

> Write an SQL query to report the total sales amount of each item for each year, with corresponding `product_name`, product_id, `product_name`, and report_year.

#### Expected behavior

One of `product_name` columns is removed.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
