### ISSUE TITLE
Missing Test Case - 8. String to Integer (atoi)

### ISSUE THREAD

**Issue by citizenkahn** [LeetCode-Feedback/LeetCode-Feedback#13166]
#### Your LeetCode username
citizenkahn

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
String to Integer (atoi) for python has three test cases but misses one where there are multiple integers described in the string.  For example, "4193 with words" contains a single string whereas "4193 with words and 234 integer" could fail in some coding scenarios.

#### Code you used for Submit/Run operation
```
class Solution:          

    def myAtoi(self, s: str) -> int:
        result = 0
        is_negative = False
        in_number = False

        for i in range(len(s)):
            if s[i].isdigit():
                in_number = True
                result = result * 10
                result += int(s[i])
            elif s[i] == '-':
                is_negative = True
            # without a break when in_number, the
            # rest of the string is processed consuming 234 and considering it
            # part of the int
        return -abs(result) if is_negative else result
```

#### Language used for code
python

#### Test Case Data
```
obj = Solution()
obj.myAtoi("4193 with words and 234 integer") == 4193
```
#### Expected behavior
Expected 4193 and got 4193234 because the 2nd integer was included in the parse process

**Comment by stormsunshine** [comment]
The code you provide returns the correct answers for both test cases. If you think the test case is missing, please provide the code that can get accepted but fails on the test case.

**Comment by citizenkahn** [comment]
> The code you provide returns the correct answers for both test cases. If you think the test case is missing, please provide the code that can get accepted but fails on the test case.

The 2nd case has the break commented out so it produces 4193234 and not the expected value.  I removed the "working solution" and added a Test Case Data section.  Sorry, I must have accidentally removed more of the PR template than I thought.
