### ISSUE TITLE
Missing Test Case - 10. Regular Expression Matching

### ISSUE THREAD

**Issue by Hid-K** [LeetCode-Feedback/LeetCode-Feedback#13164]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

"aab" does not match "c*a*b" regex but test case saying that it does match

#### Code you used for Submit/Run operation

``` java
// Two Sum
public class Solution {
public boolean isMatch(String s, String p)
    {
        if( ! ( s.equals(p) ) && p.lastIndexOf("*") < 0 ) return false;

        int sPos = 0;
        for( int i = 0; i < p.length(); ++i )
        {
            char c = p.charAt( i );
            String b = null;
            try
            {
                b = String.valueOf( s.charAt( sPos ) );
            }
            catch(Exception e)
            {
                return false;
            }

            if( c == '.')
            {
                if( b == null ) return false;
                sPos++;
                continue;
            }

            if( c == '*' )
            {
                if ( i == ( p.length() - 1 ) ) return true;

                for( int j = sPos; j < s.length(); ++j )
                {
                    if( s.charAt( j ) == p.charAt( i + 1 ) )
                    {
                        sPos += j - sPos;
                        i++;
                        break;
                    }
                }
                continue;
                // return true;
            }

            if( b != null && String.valueOf( c ).equals( b ) ) sPos++;
            else return false; 
        }

        return true;
    }
};
```

#### Language used for code
Java

#### Expected behavior
The test case expected return value should be false.

#### Screenshots

<img width="873" alt="Снимок экрана 2023-04-26 в 21 43 48" src="https://user-images.githubusercontent.com/61284529/234672596-da8d1e1d-500c-48d1-a0f1-4d914f73eb28.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output values.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!

**Comment by Hid-K** [comment]
I think that you have misunderstood me. The test case is wrong. `"aab"` string does not match the `"c*a*b"` regex.
