### ISSUE TITLE
2619 Please resolve the tsconfig error for the new JavaScript problem 

### ISSUE THREAD

**Issue by escwxyz** [LeetCode-Feedback/LeetCode-Feedback#13168]
#### Your LeetCode username
escwxyz

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

For the problem [2619](https://leetcode.com/problems/array-prototype-last/), there is a tsconfig error.

#### Code you used for Submit/Run operation

```
declare global {
    interface Array<T> {
        last(): T | -1;
    }
}

Array.prototype.last = function() {
    return this[this.length - 1] ?? -1
};

/**
 * const arr = [1, 2, 3];
 * arr.last(); // 3
 */
```

#### Language used for code
TypeScript

#### Expected behavior
No error shown in the editor.

#### Screenshots

<img width="401" alt="Screenshot 2023-04-27 at 11 06 37 AM" src="https://user-images.githubusercontent.com/124119483/234749403-f62bb12f-1cad-4175-8f90-e48c1c1f15f5.png">

#### Additional context

Please add `export {}` at the end of the code block to remove this error.
<img width="475" alt="Screenshot 2023-04-27 at 11 06 55 AM" src="https://user-images.githubusercontent.com/124119483/234749449-108fca07-3c91-4d44-bc79-3b13229d97f9.png">

also posted here: https://leetcode.com/discuss/feedback/3459241/Please-solve-the-tsconfig-error-in-the-editor

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
