### ISSUE TITLE
New testcase for "1642. Furthest Building You Can Reach" 

### ISSUE THREAD

**Issue by VasE1980** [LeetCode-Feedback/LeetCode-Feedback#1316]
#### Your LeetCode username
VasE2020

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
I noticed that one of my solutions for "1642. Furthest Building You Can Reach" passes your tests, but this test does not pass:
[4,12,5,7,3,18,19,20,3,19]
10
2

#### Code you used for Submit/Run operation

```
// Furthest Building You Can Reach
class Solution {
    private int rV;
    public int furthestBuilding(int[] heights, int bricks, int ladders) {
        rV = 0;
        recursion(heights, bricks, ladders, 0);
        return rV;
    }

    private void recursion(int[] heights, int bricks, int ladders, int index) {
        if(rV == heights.length - 1)
            return;
        while(index + 1 < heights.length && heights[index] > heights[index + 1]) index++;
        if(index + 1 == heights.length) {
            rV = index;
        } else {
            if (heights[index + 1] - heights[index] <= bricks)
                recursion(heights, bricks - (heights[index + 1] - heights[index]), ladders, index + 1);
            else if (ladders > 0)
                recursion(heights, bricks, ladders - 1, index + 1);
            else if (rV < index)
                rV = index;
        }
    }
}
```

#### Language used for code
Java

#### Expected behavior
The solution shouldn't have passed the tests.

#### Screenshots

![изображение](https://user-images.githubusercontent.com/59063496/97918003-6dbe7480-1d66-11eb-90fc-971b3fc7fe81.png)

**Comment by lc-kay** [comment]
@VasE1980 This problem was recently updated and your solution now receives WA. Thank you for your time.
