### ISSUE TITLE
Missing Test Case - 319. Bulb Switcher

### ISSUE THREAD

**Issue by AmanKumar2324** [LeetCode-Feedback/LeetCode-Feedback#13172]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by asifkhan0870** [comment]
> 

What issue which you find ???
