### ISSUE TITLE
Problem #420 - Strong Password Checker

### ISSUE THREAD

**Issue by fredrare** [LeetCode-Feedback/LeetCode-Feedback#1317]
#### Your LeetCode username

fredrare

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language

#### Description of the bug

The test cases are incorrect.
Input: "ABABABABABABABABABAB1"
Output: 1
Expected output: 2

#### Code you used for Submit/Run operation

```javascript
function strongPasswordChecker (s) {
    const count = (aux, re) => ((aux || '').match(re) || []).length
    let min = 0
    let temp = s.length
    min += temp < 6 ? 6 - temp : 0
    temp = count(s, /[a-z]/g)
    let lCase = temp ? 0 : 1
    temp = count(s, /[A-Z]/g)
    let uCase = temp ? 0 : 1
    temp = count(s, /[0-9]/g)
    let nums = temp ? 0 : 1
    temp = count(s, /(qqq)|(www)|(eee)|(rrr)|(ttt)|(yyy)|(uuu)|(iii)|(ooo)|(ppp)|(aaa)|(sss)|(ddd)|(fff)|(ggg)|(hhh)|(jjj)|(kkk)|(lll)|(zzz)|(xxx)|(ccc)|(vvv)|(bbb)|(nnn)|(mmm)|(QQQ)|(WWW)|(EEE)|(RRR)|(TTT)|(YYY)|(UUU)|(III)|(OOO)|(PPP)|(AAA)|(SSS)|(DDD)|(FFF)|(GGG)|(HHH)|(JJJ)|(KKK)|(LLL)|(ZZZ)|(XXX)|(CCC)|(VVV)|(BBB)|(NNN)|(MMM)|(111)|(222)|(333)|(444)|(555)|(666)|(777)|(888)|(999)|(000)/g)
    min += temp
    temp = lCase + uCase + nums
    min = min > temp ? min : temp
    return min
}
```

#### Language used for code

Javascript

#### Expected behavior

The expected output for this test case should be 1, because of this:
1. The password has >= 6 characters
2. The password has uppercase letters and a number (it only needs a lowercase letter).
3. The password does not contain the same character repeated three times, as the problem asks.

The only change needed is to change any of the uppercase letters for a lowercase one. This counts as only one change, thus the answer is 1. Not 2.

#### Screenshots

![image](https://user-images.githubusercontent.com/5885391/97924914-7004dc80-1d2e-11eb-9300-cbd93f5d8de3.png)

**Comment by lc-kay** [comment]
@fredrare Please check out this post for clarification. https://leetcode.com/problems/strong-password-checker/discuss/861415/420.-Strong-Password-Checker-expects-2-if-1-is-enough Thank you for your time.
