### ISSUE TITLE
Missing Test Case - 162. Find Peak Element

### ISSUE THREAD

**Issue by ankush9302** [LeetCode-Feedback/LeetCode-Feedback#13173]
#### Category of the bug
 [ ] Missing Test Cases 

#### Description of the bug
for the [3,2,1,4,5,6,7,8] the expected ans should be 7 but it is returning 0.

#### Code you used for Submit/Run operation
class Solution {
public:
    int findPeakElement(vector<int>& nums)
    {
          for (int i = 0; i < nums.size() - 1; i++) {
            if (nums[i] > nums[i + 1])
                return i;
        }
        return nums.size() - 1;
    }
};

#### Language used for code
c++

#### Expected behavior
for the given test case i was expecting returned ans to be 7 but it is returning 0 and it is getting accepted

**Comment by stormsunshine** [comment]
Do you see this statement?

> If the array contains multiple peaks, return the index to **any of the peaks**.

In many cases there are multiple peaks.

**Comment by ankush9302** [comment]
right, I got it.
thank you .
