### ISSUE TITLE
Android Unlock Patterns

### ISSUE THREAD

**Issue by mullachv** [LeetCode-Feedback/LeetCode-Feedback#1318]
#### Your LeetCode username
mullachv

#### Category of the bug
- Question

#### Description of the bug
The problem statement for Android Unlock Patterns is incomplete. What if the successive keys are say 9 and 2. 
Is this an allowed sequence? From the problem description it is evident that a transition from 9 to 1 is not allowed
if 5 is not already in the pattern. Similarly for 9 and 3 if 6 is not already included in the pattern. But what about 9 to 2?

#### Expected behavior
Expected the problem statement to be clear and unambiguous for similar conditions as transition from 9 to 2.

**Comment by lc-kay** [comment]
Hi @mullachv 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @mullachv 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by mullachv** [comment]
Hi @lc-kay
Thank you for your proactive response on this. I do not see an update to the problem description in LC yet. 
BTW, What do I do with the leetcoins?

Thank you,

**Comment by lc-kay** [comment]
@mullachv Please visit https://leetcode.com/store/ to see what you are eligible to redeem with your LeetCoins!
