### ISSUE TITLE
Closest Binary Search Tree Value Editorial Mistake

### ISSUE THREAD

**Issue by itachi1101** [LeetCode-Feedback/LeetCode-Feedback#13189]
#### Your LeetCode username
_helios

#### Category of the bug
- [X]Solution

#### Description of the bug

In the editorial the last solution does not consider the case when the difference for two values are same like (4-3 =1 ) && (3-2=1)
In the question it's mentioned to return the smallest value if multiple answers are possible but because it does not consider the equal difference it misses out on some values;  

#### Code you used for Submit/Run operation

```

/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
class Solution {
public:
    int helper(TreeNode*root,double target){
        int val,close=root->val;
        while(root!=nullptr){
            val=root->val;
            close=abs(val-target)<abs(close-target)?val:close;
            if(abs(val-target)==abs(close-target)){
              close=min(val,close);
            }
            root=target<root->val?root->left:root->right;
        }
        return close;
    }
    int closestValue(TreeNode* root, double target) {

        return helper(root,target);
    }
};
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by itachi1101** [comment]
Happy to help. Thanks for the coins
