### ISSUE TITLE
Missing Test Case - 1172. Dinner Plate Stacks

### ISSUE THREAD

**Issue by lee-lol** [LeetCode-Feedback/LeetCode-Feedback#13185]
#### Your LeetCode username

hhkjbhj

#### Category of the bug
- [ ] Question
-  Solution
- [ ] Language
-  Missing Test Cases 

#### Description of the bug

The pop（） function of the official c++ solution for problem 1172 dinner plate is obviously wrong.  Try this input with the official solution code (is provided below):
["DinnerPlates","push","push","push","push","push","push","pop","push","push","popAtStack","popAtStack","pop","pop","pop","pop","pop"]
[[2],[1],[2],[3],[4],[5],[6],[],[20],[21],[0],[2],[],[],[],[],[]]
the answer is wrong, but if you submit the code below, you'll pass all the test cases. The test case above should be added and the solution code should be fixed as such : top.back() = top.size() - 2; -->  top.back()--; 
#### Code you used for Submit/Run operation

```
class DinnerPlates {
public:
    DinnerPlates(int capacity) {
        this->capacity = capacity;
    }

    void push(int val) {
        if (poppedPos.empty()) {
            int pos = stk.size();
            stk.emplace_back(val);
            if (pos % capacity == 0) {
                top.emplace_back(0);
            } else {
                top.back()++;
            }
        } else {
            int pos = *poppedPos.begin();
            poppedPos.erase(pos);
            stk[pos] = val;
            int index = pos / capacity;
            top[index]++;
        }
    }
    
    int pop() {
        while (!stk.empty() && poppedPos.count(stk.size() - 1)) {
            stk.pop_back();
            int pos = *poppedPos.rbegin();
            poppedPos.erase(pos);
            if (pos % capacity == 0) {
                top.pop_back();
            }
        }
        if (stk.empty()) {
            return -1;
        } else {
            int pos = stk.size() - 1;
            int val = stk.back();
            stk.pop_back();
            if (pos % capacity == 0) {
                top.pop_back();
            } else {
                top.back() = top.size() - 2;
            }
            return val;
        }
    }
    
    int popAtStack(int index) {
        if (index >= top.size()) {
            return -1;
        }
        int stackTop = top[index];
        if (stackTop < 0) {
            return -1;
        }
        top[index]--;
        int pos = index * capacity + stackTop;
        poppedPos.emplace(pos);
        return stk[pos];
    }
private:
    int capacity;
    vector<int> stk;
    vector<int> top;
    set<int> poppedPos;
};
```

#### Language used for code
C++

#### Expected behavior

Try this input with the c++ official solution code above:
["DinnerPlates","push","push","push","push","push","push","pop","push","push","popAtStack","popAtStack","pop","pop","pop","pop","pop"]
[[2],[1],[2],[3],[4],[5],[6],[],[20],[21],[0],[2],[],[],[],[],[]]
the answer should be [null,null,null,null,null,null,null,6,null,null,2,20,21,5,4,3,1], but the output is [null,null,null,null,null,null,null,6,null,null,2,21,20,5,4,3,1]; yet the official solution code passed all the test cases.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback. 

Please provide us with your username. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
