### ISSUE TITLE
Missing Test Cases  - 270. Closest Binary Search Tree Value

### ISSUE THREAD

**Issue by JeffCJ1125** [LeetCode-Feedback/LeetCode-Feedback#13186]
#### Your LeetCode username

vacation736

#### Category of the bug
- [ ] Question
- [ v ] Solution
- [ ] Language
- [ v ] Missing Test Cases 

#### Description of the bug

 Python Approach 3  in editorial pass all the testcases for being the summit solution,
 but for the test case below, it can not pass it.

Input
root = [4,2,5,1,3]
target = 4.5

#### Code you used for Submit/Run operation

```
class Solution(object):
    def closestValue(self, root, target):
        """
        :type root: TreeNode
        :type target: float
        :rtype: int
        """
        closest = root.val
        while root:
            closest = min(root.val, closest, key = lambda x: abs(target - x))
            root = root.left if target < root.val else root.right
        return closest
        
```

#### Language used for code

python

#### Expected behavior

the expected answer should be 4, but the Python approach 3 outputs 5.

#### Screenshots

![image](https://user-images.githubusercontent.com/118115535/235092622-0388f0c6-4c73-4b0c-8665-ecb01089ca2b.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
