### ISSUE TITLE
Missing Test Case - 2650. Design Cancellable Function

### ISSUE THREAD

**Issue by N8Brooks** [LeetCode-Feedback/LeetCode-Feedback#13183]
#### Your LeetCode username

SkookumChoocher

#### Category of the bug
- [x] Missing Test Cases 

#### Problem
https://leetcode.com/problems/design-cancellable-function

### Valid Testcase

The idea is: it cancels while awaiting the first generated promise.

```js
function*() {
    try {
        yield new Promise((_, rej) => setTimeout(rej, 20, 'slow'));
    } catch {
        yield "fast";
    }
}
```

```js
{"cancelledAt":10}
```

### Passing code that fails the testcase

```js
var cancellable = function(generator) {
    let cancelled = false;
    let done, value;
    return [
        () => void (cancelled = true),
        (async () => {
            while (!done) { // 3. `{value: "fast"}` is not done
                try {
                    const result = await value; // 1. While awaiting this `result` rejection, it is cancelled
                    if (cancelled) {
                        return generator.throw("Cancelled").value; // 4. After awaiting `"fast"`, `"Cancelled"` is thrown
                    }
                    ({done, value} = generator.next(result));
                } catch (error) {
                    ({done, value} = generator.throw(error)); // 2. The testcase catch block yields `{value: "fast"}`
                }
            }
            return value;
        })(),
    ]
};
```

#### Output

```
{"rejected":"Cancelled"}
```

#### Expected

```
{"resolved":"fast"}
```

### Passing code that passes the testcase

```js
var cancellable = function(generator) {
    let cancelled = false;
    let done, value;
    return [
        () => void (cancelled = true),
        (async () => {
            while (!done) {
                try {
                    const result = await value; // 1. While awaiting this `result` rejection, it is cancelled
                    if (cancelled) {
                        break;
                    }
                    ({done, value} = generator.next(result));
                } catch (error) {
                    if (cancelled) { // 2. Breaks for `cancelled`
                        break;
                    }
                    ({done, value} = generator.throw(error));
                }
            }
            return cancelled
                ? generator.throw("Cancelled").value // 3. The testcase catch block yields `{value: "fast"}`
                : value;
        })(),
    ]
};
```

#### Output/Expected

```
{"resolved":"fast"}
```
#### Unknowns

I'm not sure why "fast" is resolved. It seems like "Cancelled" should be uncaught in the testcase's catch block resulting in `{"rejected":"Cancelled"}`.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The valid test cases.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by N8Brooks** [comment]
Here is the valid testcase. I've updated the body of the issue to clear up confusion as well.

### Valid Testcase

The idea is: it cancels while awaiting the first generated promise.

```js
function*() {
    try {
        yield new Promise((_, rej) => setTimeout(rej, 20, 'slow'));
    } catch {
        yield "fast";
    }
}
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The description states, 'If the error ("Cancelled") was caught, the returned promise should resolve with the next value that was yielded or returned.' Therefore, promise resolves with 'fast'.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
