### ISSUE TITLE
Language - 839. Similar String Groups

### ISSUE THREAD

**Issue by ramen-7** [LeetCode-Feedback/LeetCode-Feedback#13194]
#### Your LeetCode username
shivam_taneja

#### Category of the bug
- [ ] Question
- [ ] Solution
- [*] Language
- [ ] Missing Test Cases 

#### Description of the bug
The description of the question is a little unclear 
`Two strings X and Y are similar if we can swap two letters (in different positions) of X, so that it equals Y. Also two strings X and Y are similar if they are equal.`

To make the question more clear it should be can swap **only** two letters.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
