### ISSUE TITLE
TypeScript execution failed in Question 941

### ISSUE THREAD

**Issue by martin-luo** [LeetCode-Feedback/LeetCode-Feedback#1319]
#### Your LeetCode username
叮叮叮

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language

#### Description of the bug
TypeScript execution failed and shown as internal error when running the test case `[2,1]` for [Question 941. Valid Mountain Array](https://leetcode-cn.com/problems/valid-mountain-array/).

I tried to change the code to just log the input, and the error still occurs.

#### Code you used for Submit/Run operation
```TypeScript
function validMountainArray(A: number[]): boolean {
  const aLength: number = A.length;
  if (aLength < 3) {
    return false;
  }

  let peak: number = A[0];
  let previousValue: number = A[0];
  let declining: boolean = false;

  for (let i = 1; i < aLength; i++) {
    const currentValue: number = A[i];
    if (currentValue === previousValue) {
      return false;
    }

    if (declining) {
      if (currentValue > previousValue) {
        return false;
      }
    } else {
      if (currentValue > peak) {
        peak = currentValue;
      } else {
        declining = true;
      }
    }

    previousValue = currentValue;
  }

  return true;
}
```

Code just log the input but still failed:
```TypeScript
function validMountainArray(A: number[]): boolean {
    console.log(A);
    return false;
};
```

#### Language used for code
TypeScript

#### Expected behavior
The code should run as expected, such as return a value, or log the input (for code 2 provided)

#### Screenshots
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/7485288/97931245-278a0500-1da8-11eb-8c96-495375dfc464.png">

#### Additional context
N/A

**Comment by feiceh** [comment]
感谢反馈，该题目技术验证当前没有问题的，感谢支持力扣。
