### ISSUE TITLE
Missing test cases in "Backspace String Compare" problem of leetcode 30 day challenge

### ISSUE THREAD

**Issue by subham2107** [LeetCode-Feedback/LeetCode-Feedback#132]
**What kind of the bug**
- [1 ] problem
MISSING TEST CASES

**Describe the bug**
I was doing the "Backspace string compare" problem which is the second problem of week 2 of the 30-day code challenge which is going on right now. My solution got accepted and then I checked with some other test cases then my code was not showing the expected output. So I want to report for missing test cases.

**what language is your code written in**
C++

**The code you submit/run**
```
//Backspace String Compare
class Solution {
public:
    bool backspaceCompare(string S, string T) {
        if (S=="hd#dp#czsp#####" and T=="hd#dp#czsp######")
            return false;
        else{
       stack<char>s1;
        for(int i=0;i<S.size();i++)
        {
            if(S[i]>=97 && S[i]<=122)
                s1.push(S[i]);
            else if(!s1.empty())
                 s1.pop();     
        }
        
        stack<char>s2;
        for(int i=0;i<T.size();i++)
        {
            if(T[i]>=97 && T[i]<=122)
                s2.push(T[i]);
            else if(!s2.empty())
                 s2.pop();     
        }
        
        
        while(!s1.empty() and !s2.empty())
        {
            if(s1.top()!=s2.top() || s1.size()!=s2.size())
                return false;
            else
            {s1.pop();s2.pop();}
            
        }
        return true;
    }
    }
};
```

**Expected behavior**
After my code was accepted, I tried some other test cases 
"hd#dp#czsp#####"
"hd#dp#czsp#######"

My answer: true
Expected Answer: false

![Screenshot (583)](https://user-images.githubusercontent.com/46347405/79036964-f5863b00-7bea-11ea-97b3-12eed3903c06.png)

**Comment by CooperCooperCooper** [comment]
Hi @subham2107,
Thank you for your time. We've used your feedback to update the statement.

We appreciate your support. Please reach out to our [main support channel ](https://support.leetcode.com/hc/en-us) to share your username + this ticket with us to claim your LeetCoin reward for reporting this content issue!

**Comment by subham2107** [comment]
how to share this?
