### ISSUE TITLE
Approach 1 can be made way clearer in 67. Add Binary

### ISSUE THREAD

**Issue by davitescobedo** [LeetCode-Feedback/LeetCode-Feedback#13204]
#### Your LeetCode username

eldavimost

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In line 5, there's
```int L = Math.max(n, m);```
but from the line above:
```if (n < m) return addBinary(b, a);```
we know that n must be greater or equal to m, so L must be:
```int L = n;```
Otherwise, we would've gone into the if and the code wouldn't have reached this line.
(and actually, we can just remove L altogether from the solution, I'm writing the full solution below).
It was very confusing to read L = Math.max(n, m); for me, as it made me think L could be n or m. Then I reached the conclusion that if L = m then the code below taking j = m - 1 would fail (as both pointers would be tracking m length and none n!).
Having that line just adds extra thinking time for learners that goes nowhere.

#### Code you used for Submit/Run operation

The solution is written like this
```
class Solution {
  public String addBinary(String a, String b) {
    int n = a.length(), m = b.length();
    if (n < m) return addBinary(b, a);
    int L = Math.max(n, m);

    StringBuilder sb = new StringBuilder();
    int carry = 0, j = m - 1;
    for(int i = L - 1; i > -1; --i) {
      if (a.charAt(i) == '1') ++carry;
      if (j > -1 && b.charAt(j--) == '1') ++carry;

      if (carry % 2 == 1) sb.append('1');
      else sb.append('0');

      carry /= 2;
    }
    if (carry == 1) sb.append('1');
    sb.reverse();

    return sb.toString();
  }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should be simplified to this
```
class Solution {
  public String addBinary(String a, String b) {
    int n = a.length(), m = b.length();
    if (n < m) return addBinary(b, a);

    StringBuilder sb = new StringBuilder();
    int carry = 0, j = m - 1;
    for(int i = n - 1; i > -1; --i) {
      if (a.charAt(i) == '1') ++carry;
      if (j > -1 && b.charAt(j--) == '1') ++carry;

      if (carry % 2 == 1) sb.append('1');
      else sb.append('0');

      carry /= 2;
    }
    if (carry == 1) sb.append('1');
    sb.reverse();

    return sb.toString();
  }
}
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
