### ISSUE TITLE
Cleanup issues in submission environment: Binary Tree Level Order Traversal

### ISSUE THREAD

**Issue by 5nak3Eyes** [LeetCode-Feedback/LeetCode-Feedback#1320]
#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language

#### Description of the bug
The submission runtime does not perform a cleanup. I have run same tests in console and they work perfectly, but when I submit the solution the same test fails. It seems like submission runtime is using previous input/output (result array). The runtime is not cleaned up before running a new test case.

#### Code you used for Submit/Run operation

```
\\ 102. Binary Tree Level Order Traversal
class Solution:
    def levelOrder(self, root: TreeNode, count = 0, result = []) -> List[List[int]]:
        if not root: return root
        try: result[count].append(root.val)
        except IndexError: result.append([root.val])
        count+= 1    
        if root.left: self.levelOrder(root.left, count, result)
        if root.right: self.levelOrder(root.right, count, result)
        count -= 1
        if count == 0: return result
```

#### Language used for code
Python3

#### Expected behavior
Expect same output as console

#### Screenshots
**Console**
![image](https://user-images.githubusercontent.com/29703336/97960718-48efee80-1db2-11eb-8d6c-786c0f1bcb9e.png)

**Submission**
![image](https://user-images.githubusercontent.com/29703336/97960964-b13ed000-1db2-11eb-89dd-9e0b15d150ab.png)

**Comment by lc-kay** [comment]
Hi @5nak3Eyes 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
