### ISSUE TITLE
Missing Test Case - 1163. Last Substring in Lexicographical Order

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#13206]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
For [1163. Last Substring in Lexicographical Order](https://leetcode.com/problems/last-substring-in-lexicographical-order), a solution that gets accepted will get TLE on a specific test case.

The test case is: [1163.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/11359236/1163.txt)

#### Code you used for Submit/Run operation

```Java
class Solution {
    public String lastSubstring(String s) {
        char[] chars = s.toCharArray();
        int left = 0, right = 1, n = chars.length;
        while (right < n) {
            int l = left, r = right;
            while (r < n) {
                char lChar = chars[l++], rChar = chars[r++];
                if (lChar == rChar) continue;
                if (rChar > chars[left]) {
                    left = r - 1;
                } else if (lChar < rChar) {
                    left = right;
                    r = right + 1;
                }
                break;
            }
            right = r;
        }
        return s.substring(left);
    }
}
```

#### Language used for code
Java

#### Expected behavior
Add the test case so that the solution above will get TLE when submitted.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
