### ISSUE TITLE
Missing Test Case - 9. Palindrome Number

### ISSUE THREAD

**Issue by Vishesh-Chahar** [LeetCode-Feedback/LeetCode-Feedback#13207]
#### Your LeetCode username
vishesh_chahar

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ #] Missing Test Cases 

#### Description of the bug

For most of the submissions made on this question, a simple modulus of 10 would suffice, but the same code will not run for a 4 digit palindrome such as 1331, this is due to the test cases being limited to 3 digit numbers

#### Code you used for Submit/Run operation

``` 
import math
class Solution:
    def isPalindrome(self, x: int) -> bool:
        c = 0
        if x > 0:
            digits = int(math.log10(x))+1
        elif x == 0:
            digits = 1
        else:
            return False
            exit()
        num = []
        for digit in range(digits):
            num1 = int((x-(x%(10**(digits-digit-1))))/10**(digits-digit-1))
            num.append(num1)
            x = x - num1*(10**(digits-digit-1))
        for i in range(digits):
            if num[i] == num[digits-i-1]:
                c = c + 1
            else:
                c = c - 1
        return c == digits
``` 
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
