### ISSUE TITLE
Missing Test Case - 1009. Complement of Base 10 Integer

### ISSUE THREAD

**Issue by pks2906** [LeetCode-Feedback/LeetCode-Feedback#13214]
#### Your LeetCode username
pratik1971sinha

#### Category of the bug

- [x] Solution

#### Description of the bug
< The code is written correctly but the after running it's giving the wrong solution>

#### Code you used for Submit/Run operation

```
// 1009. Complement of Base 10 Integer
class Solution {
public:
    int bitwiseComplement(int n) {
        
       int m = n;
       int mask = 0;

       if(n == 0);
       return 1;

       while( m!=0); {
       mask = (mask << 1) | 1;
       m = m >> 1;

       }

       int ans = (~n) & mask;

       return ans;


    }
};
```

#### Expected behavior
<!--After running this code the expected output should be 2 but its giving the output 1

#### Screenshots
![image](https://user-images.githubusercontent.com/91456061/235336976-e935e4e8-9f8b-4c37-85ab-d7d09a7125ac.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output values.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!
