### ISSUE TITLE
Unclear Translation: 6341. Determine the Winner of a Bowling Game

### ISSUE THREAD

**Issue by Yawn-Sean** [LeetCode-Feedback/LeetCode-Feedback#13213]
#### Your LeetCode username

Yawn_Sean

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the Chinese-Version of this problem, the "the previous two turns" is translated as "前两轮", which can be understood as "最前两轮" (the first two turns) or "此前两轮" (the two turns before this turn). Both understandings can explain the test cases, if we double the scores after the 2nd turn if the conditions are met.

It caused a lot of Chinese participants to give the wrong solution and cost quite a long time to figure out what was wrong about their solution, only to find it was because of a misunderstanding of the problem. Therefore, it should be a good idea to unrate the contest for at least Chinese participants.

#### Some Proof

- The English Description:
![image](https://user-images.githubusercontent.com/106463906/235335194-4c1f2a01-98c3-4c93-b00a-2bdf546018a0.png)

- The Chinese Description:
![image](https://user-images.githubusercontent.com/106463906/235335218-85b7c27a-bbd9-42b0-ad9b-047d3ce1a4c7.png)

- A glimpse of how many Chinese participants are confused about it (More than half of them WA-ed and it is clearly because their different understandings towards the question as they are top-coders in Chinese Leetcode and Q1 shouldn't be what's troubling them):
![image](https://user-images.githubusercontent.com/106463906/235335311-6b2d553a-7f4d-4fc5-8c83-dece4bb7d11d.png)
![image](https://user-images.githubusercontent.com/106463906/235335333-d38a904e-7c41-4c5d-966f-14ff9dfec645.png)
![image](https://user-images.githubusercontent.com/106463906/235335346-2a07d59e-1e7b-4078-ab3b-c4a930833c45.png)
![image](https://user-images.githubusercontent.com/106463906/235335352-c28dabc5-3c86-4565-8593-aa905ae4905a.png)
![image](https://user-images.githubusercontent.com/106463906/235335357-85f2b7cf-07ab-4375-9259-35e5561f29b6.png)
![image](https://user-images.githubusercontent.com/106463906/235335361-3da0da13-f3ee-4fb7-ac03-514eb26ce3ca.png)
![image](https://user-images.githubusercontent.com/106463906/235335374-cb32eea2-4e2c-4ef0-8804-c9569f9d66e4.png)

**Comment by john9999911** [comment]
支持

**Comment by gxsoar** [comment]
I agree with him, I have 7 wa at the first problem.

**Comment by feiceh** [comment]
Hello～在与相关团队反馈确认后：本场周赛排名和奖励已经发放完毕，优化竞赛体验和质量一贯是力扣不遗余力的努力方向。我们会同题目以及竞赛运营团队沟通制度以保障后续的竞赛相关工作，本次 Ticket 将关闭，感谢您的反馈和支持。

**Comment by Yawn-Sean** [comment]
> Hello～在与相关团队反馈确认后：本场周赛排名和奖励已经发放完毕，优化竞赛体验和质量一贯是力扣不遗余力的努力方向。我们会同题目以及竞赛运营团队沟通制度以保障后续的竞赛相关工作，本次 Ticket 将关闭，感谢您的反馈和支持。

请问下，我四天前就提了的 issue 然后你们说不管就不管了？明明昨天才更新的排名，提前一点看反馈是很难的事情吗？提出 issue 的人都没有确认问题解决了，凭什么就认为这个 issue 就 closed 了？每次都说你们优化了竞赛，我到现在都没有看到你们哪怕一点点的诚意，只看到了敷衍。

以后遇到问题解决可太容易了，装死，然后知道结果真的出来了，说改不了，这就是你们现在的态度吗？

**Comment by feiceh** [comment]
感谢反馈，很抱歉给大家带来了不愉快的体验，我们已针对大家提出的问题进行回溯和排查，当前 LCCN WC343  已 unrate ， 排名更新好了。也希望从大家的反馈和建议中持续不断的迭代力扣产品，给大家提供帮助和价值，如有更多反馈和建议欢迎  [点击这里](https://support.leetcode.cn/hc/request/new/) 提交工单反馈，给大家带来的不便敬请谅解。

**Comment by Yawn-Sean** [comment]
> 感谢反馈，很抱歉给大家带来了不愉快的体验，我们已针对大家提出的问题进行回溯和排查，当前 LCCN WC343 已 unrate ， 排名更新好了。也希望从大家的反馈和建议中持续不断的迭代力扣产品，给大家提供帮助和价值，如有更多反馈和建议欢迎 [点击这里](https://support.leetcode.cn/hc/request/new/) 提交工单反馈，给大家带来的不便敬请谅解。

感谢您的理解和处理。
