### ISSUE TITLE
Misspelling in Example 2 1697. Checking Existence of Edge Length Limited Paths

### ISSUE THREAD

**Issue by rafiq** [LeetCode-Feedback/LeetCode-Feedback#13212]
https://leetcode.com/problems/checking-existence-of-edge-length-limited-paths/

#### Your LeetCode username
Rafiq_ironHonest_Kamal

#### Category of the bug
- [X ] Language

#### Description of the bug
You have a misspelling in Example 2:
Exaplanation: The ...
Should be:
Explanation: The ...

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
