### ISSUE TITLE
Incorrect space complexity - 1697. Checking Existence of Edge Length Limited Paths

### ISSUE THREAD

**Issue by mdes4214** [LeetCode-Feedback/LeetCode-Feedback#13210]
#### Your LeetCode username

mdes4214

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Incorrect space complexity in Approach 1.

#### Expected behavior

We sort `edgeList`, so overall we use `O(n + q + log(e) + log(q))` or `O(n + q + e + q)` = `O(n + q + log(e))` or `O(n + q + e)` space.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
