### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by KUSHAL-RAJ-PAREEK** [LeetCode-Feedback/LeetCode-Feedback#13211]
#### Your LeetCode username

KUSHAL-RAJ-PAREEK

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 
Missing Test Cases

#### Description of the bug

it is a testcase need to be add in question(Two Sum).

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    public int[] twoSum(int[] nums, int target) {
        Map<Integer,Integer> str = new HashMap<>();
        for(int i = 0 ; i < nums.length; i++){
            int curr = nums[i];
            int x = target- curr;
            if(str.containsKey(x)){
                return new int[] {str.get(x), i};
            }
            str.put(curr,i);
        }
        return null;
    }
}
```

#### Language used for code

java

#### Screenshots

![Screenshot 2023-04-29 234814](https://user-images.githubusercontent.com/115624967/235318126-db820ab2-c2ec-44a5-b2ff-081cdd0b4e0b.png)

**Comment by KUSHAL-RAJ-PAREEK** [comment]
i think this test case should be added.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

The test case already exist.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
