### ISSUE TITLE
175. Combine Two Tables

### ISSUE THREAD

**Issue by richaaa01** [LeetCode-Feedback/LeetCode-Feedback#13220]
#### Category of the bug
- [ ] Question
- [ -] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

After sourcing through different platforms, i saw everybody using 'left join' to just join the table, since the remaining right part of the table will automatically show null, but it is not showing the same way in the output here.

#### Code you used for Submit/Run operation

```
select Person.firstName, Person.lastName, Address.city, Address.state
 from Person
 left join Address on Person.personId = Address.addressId;

```

#### Language used for code

SQL

#### Screenshots

![image](https://user-images.githubusercontent.com/105065802/235350105-80e672fc-beb9-4180-8e87-1ed7b781ce6a.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
