### ISSUE TITLE
1579. Remove Max Number of Edges to Keep Graph Fully Traversable, abnormal test case display.

### ISSUE THREAD

**Issue by sushi3085** [LeetCode-Feedback/LeetCode-Feedback#13225]
#### Your LeetCode username
itanki3085

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

I checked the "Missing Test Cases" one is just because I can't find other more suitable for this problem.
But anyway, the problem is when I idle the tab of the browser for a while, and than hit the submit button.
The testcase without any input shows up with the "Time Limit Exceeded" of execution result.
So, somehow the testcase is literally missing.
(Apparently this problem has nothing to do with the idle tab. I tried submit again and get the same result: TLE 😥)

#### Code you used for Submit/Run operation

```C++
// Language: C++
#include <bits/stdc++.h>
using namespace std;

class DSU{
    vector<int> head, rank;
    int groups;
public:
    DSU(int size){
        head.resize(size);
        for(int i=0; i<size; i++) head[i] = i;
        rank.resize(size);
        rank.assign(size, 1);
    }
    int find(int x){
        if(head[x] == x) return x;
        return head[x] = find(head[x]);
    }
    bool group(int a, int b){
        int x=find(a), y=find(b);
        if(x==y) return false;
        if(rank[x] < rank[y]) head[y] = x;
        else head[x] = y;
        groups--;
        return true;
    }
    int getGroupCount(){
        return groups;
    }
};

class Solution {
public:
    int maxNumEdgesToRemove(int n, vector<vector<int>>& edges) {
        sort(edges.begin(), edges.end(), [](vector<int> a, vector<int> b){return a[0]>b[0];});
        DSU alice(n), bob(n);
        int deletedNodes = 0;
        for(vector<int>& edge : edges){
            int nodeA = edge[1]-1, nodeB = edge[2]-1;
            if(edge[0] == 3){
                if(alice.group(nodeA, nodeB)){
                    bob.group(nodeA, nodeB);
                }else{
                    deletedNodes++;
                }
            }else if(edge[0] == 2){
                if(!bob.group(nodeA, nodeB)){
                    deletedNodes++;
                }
            }else{
                if(!alice.group(nodeA, nodeB)){
                    deletedNodes++;
                }
            }
        }
        cout << alice.getGroupCount() << ", " << bob.getGroupCount();
        if(alice.getGroupCount()!=1 || bob.getGroupCount()!=1) return -1;
        return deletedNodes;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The code should not be TLE? 
And it should pass through testcase # 85.

#### Screenshots

The response after pressing "Submit" button:
![image](https://user-images.githubusercontent.com/78290201/235360440-bb2f5955-f173-460f-aa77-8b55917d784d.png)

After hitting "copy to testcase" (or something like that) :
![image](https://user-images.githubusercontent.com/78290201/235361376-6ee42c1a-b36b-41a8-b307-8902750e269f.png)

And copy the failed testcase into customized test case and run again. But not get any result.
![image](https://user-images.githubusercontent.com/78290201/235360608-15b3ebf2-a2dd-4adc-a11a-f96a99fb709a.png)

#### Additional context

I'll provide as much as I could if there still anything that I can or need to!

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
