### ISSUE TITLE
1346. Check If N and Its Double Exist : a test case that breaks my accepted solution

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1322]
#### Your LeetCode username
[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [x] Question: Missing Testcase
- [ ] Solution
- [ ]  Language

#### Description of the bug

**Testcase missing** 
**Test Case: [2,3,3,0,0]**
I wrote a solution to problem 1346 that was accepted. When I was revising the code I found a bug. Then I created a test case that doesn't let my solution to pass: [2,3,3,0,0]

#### Code you used for Submit/Run operation

```
// Check If N and Its Double Exist
class Solution:
    def checkIfExist(self, arr: List[int]) -> bool:
        
        if arr.count(0)==len(arr):
            return True
        else:
            x = [x for x in arr if x!=0 and x*2 in arr]
            print(x)
            if len(x) > 0:
                return True
            else:
                return False
```

#### Language used for code
Python

#### Expected behavior
My Output: false
Expected Output:  true

#### Screenshots

![image](https://user-images.githubusercontent.com/71989691/97965038-9480a900-1d6e-11eb-915a-af49896ec221.png)

![image](https://user-images.githubusercontent.com/71989691/97965529-6059b800-1d6f-11eb-9743-9611ef2125b7.png)

#### Additional context

Problem : https://leetcode.com/problems/check-if-n-and-its-double-exist/
Contribution : https://leetcode.com/contribute/25074

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for your time. We've added your test case and rewarded your points through your test case contribution. We appreciate your support!
