### ISSUE TITLE
Incorrect time complexity - 1579. Remove Max Number of Edges to Keep Graph Fully Traversable

### ISSUE THREAD

**Issue by mdes4214** [LeetCode-Feedback/LeetCode-Feedback#13224]
#### Your LeetCode username

mdes4214

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Incorrect time complexity in Approach 1.

#### Expected behavior

Like other problems about DSU, we count the initialization of `UnionFind` instance as part of time cost, e.g., [1697. Checking Existence of Edge Length Limited Paths](https://leetcode.com/problems/checking-existence-of-edge-length-limited-paths/solution/), so I think the time complexity shoud be `O(N + E∗α(N))`.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

The analysis is already including the initialization. As mentioned in the analysis, the inverse ackermann function can be considered as constant time, so the terms are dominated by the sorts.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
