### ISSUE TITLE
How the answer will fit into 32bit integer?

### ISSUE THREAD

**Issue by HazemRawi** [LeetCode-Feedback/LeetCode-Feedback#13231]
The case of how this huge multiplication will fit in 32bit integer is ambiguous so you have to well explain this point and make editorial public otherwise it was a good problem.

**Comment by HazemRawi** [comment]
Regarding 662. Maximum Width of Binary Tree

**Comment by HazemRawi** [comment]
//Sorry about the two unclear previous comments, This is my first time here on github :)
[HazemRawi](https://leetcode.com/HazemRawi/)



#### Category of the bug
- [0 ] Question
- [ 1] Solution
- [ 0] Language
- [ 0] Missing Test Cases 


How this huge multiplication will fit in 32bit integer? 
it is ambiguous so I suggest you well explain this point and make editorial public.
otherwise it was a good problem


662. Maximum Width of Binary Tree
class Solution {
public:
    int widthOfBinaryTree(TreeNode* root) {
        
        queue<pair<TreeNode*,int>>BFS;
        BFS.push({root,0});
        int MaximumWidth=0;
        while(BFS.size())
        {
            int NumberOfNodes=BFS.size();
            int left=BFS.front().second,right=BFS.back().second;
            long long MaximumWidthOnCurrentLevel=right;
            MaximumWidthOnCurrentLevel-=left-1;
            MaximumWidth=max(MaximumWidth,(int)MaximumWidthOnCurrentLevel);
            while(NumberOfNodes--)
            {
                TreeNode*Node=BFS.front().first;
                int val=BFS.front().second;
                BFS.pop();
                if(Node->left!=nullptr)
                    BFS.push({Node->left,2LL*val});
                if(Node->right!=nullptr)
                    BFS.push({Node->right,2LL*val+1});
            }
        }
        return MaximumWidth;
    }
};

#### Language used for code
C++

#### Expected behavior
Despite signed integer overflow it got accepted while when I used long long instead of int32 it prompt runtime error due to overflow

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Comment by HazemRawi** [comment]
Hello,
I am sorry for being late , Here is the submissions link:
https://leetcode.com/submissions/detail/942427407/
