### ISSUE TITLE
Python has arrays - correct the 

### ISSUE THREAD

**Issue by Somashekhark** [LeetCode-Feedback/LeetCode-Feedback#13237]
https://leetcode.com/explore/interview/card/leetcodes-interview-crash-course-data-structures-and-algorithms/703/arraystrings/4500/

"Array" can mean something different between languages. For example, Python uses "lists" instead of arrays which are extremely lenient. "

The above statement has to be corrected

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Python has no built in support for arrays unlike other major languages. To simulate an “array”, you need a library.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
