### ISSUE TITLE
Missing Test Case - 5. Longest Palindromic Substring

### ISSUE THREAD

**Issue by meksym** [LeetCode-Feedback/LeetCode-Feedback#13239]
#### LeetCode username

meksym

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I don't understand why this is happening (look at the screenshots). Help me if you can.

#### Code you used for Submit/Run operation

```c
char * longestPalindrome(char *string) {
    int length;
    for (length = 0;; length++)
        if (string[length] == '\0')
            break;

    for (int size = length; size > 0; size--) {
        for (int i = 0; i <= length - size; i++) {
            int direct = i;
            int reverse = i + size - 1;
            int half = size / 2;
            int isPalindrome = 1;

            while (direct < i+half) {
                if (string[direct] != string[reverse])
                    isPalindrome = 0;

                direct++;
                reverse--;
            }

            if (isPalindrome == 1) {
                static char result[1000];

                int index = 0;
                for(int j = i; j < i+size; j++) {
                    result[index] = string[j];
                    index++;
                }

                return result;
            }
        }
    }

    return "";
}
```

#### Language used for code 

C

#### Screenshots

On my PC:
![On my PC](https://user-images.githubusercontent.com/96940279/235461275-eabe9bad-be51-4b45-a4f3-060c8230b63a.png)

On leetcode:
![On leetcode](https://user-images.githubusercontent.com/96940279/235461512-4186ece0-b31c-4d70-9520-ebd7ce854e0f.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
