### ISSUE TITLE
Missing Test Case - 1491. Average Salary Excluding the Minimum and Maximum Salary

### ISSUE THREAD

**Issue by abhistjain** [LeetCode-Feedback/LeetCode-Feedback#13234]
#### Category of the bug
- [ 1491. Average Salary Excluding the Minimum and Maximum Salary
] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
<! --The bug is that one of the questions test cases is giving a wrong result see it asked to find the average between the minimum and maximum salary and for test case [8000,9000,2000,3000,6000,1000] it should be 5000 but it's expecting us to return 4750. I don't know how. -->

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    double average(vector<int>& salary) {

        for(int i=2 ; i<salary.size() ; i++)
        {
            if(salary[0]>salary[i]) swap(salary[0],salary[i]);
            if(salary[1]<salary[i]) swap(salary[1],salary[i]);
        }
        return (float)((salary[0]+salary[1])/2);
    }
};
```

#### Screenshots
<!
![image](https://user-images.githubusercontent.com/91110897/235435728-deb4f1f6-2b67-4921-9fac-2688ce838ce2.png)
-->

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
