### ISSUE TITLE
Missing Test Case - 1491. Average Salary Excluding the Minimum and Maximum Salary

### ISSUE THREAD

**Issue by himanshusingh1609** [LeetCode-Feedback/LeetCode-Feedback#13236]
#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by himanshusingh1609** [comment]
Input: salary = [7000,7000,7000,7000]

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
