### ISSUE TITLE
Missing Constraints - 64. Minimum Path Sum

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1323]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

64. Minimum Path Sum
https://leetcode.com/problems/minimum-path-sum/

Constraints are missing
- What is the range of m & n?
- What is the range of values of the grid?

#### Code you used for Submit/Run operation

```
```

#### Expected behavior

- The question must have constraints in order to avoid TLE errors

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
