### ISSUE TITLE
66. Plus One: a test case that breaks my accepted solution

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1324]
#### Your LeetCode username
[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [x] Question: Missing testcase
- [ ] Solution
- [ ] Language

#### Description of the bug
**Testcase:** [0,0]

I wrote a solution to problem 66 that was accepted. When I was revising the code I found a bug. Then I created a test case that doesn't let my solution to pass: [0,0]

#### Code you used for Submit/Run operation

```
class Solution:
    def plusOne(self, digits: List[int]) -> List[int]:
        nums = 0
        for i in digits:
            nums = nums * 10 + i
        return [int(x) for x in str(nums+1)]
```

#### Language used for code

Python

#### Expected behavior

Your input
[0,0]
Output
[1]
Expected
[0,1]

#### Screenshots

![image](https://user-images.githubusercontent.com/71989691/98014495-923f3e80-1db0-11eb-9af1-f9d3be8c27f7.png)

#### Additional context

Problem: https://leetcode.com/problems/plus-one/
Contribution: https://leetcode.com/contribute/25458

**Comment by lc-kay** [comment]
@pratap-082020 The code you included does not match the one in your screenshot and it is resulting in RTE. Can you please provide me with the code from your screenshot? Thank you!

**Comment by pratap-082020** [comment]
@lc-kay Here is the code I submitted for this problem:

`
class Solution:
    def plusOne(self, digits: List[int]) -> List[int]:
        nums = 0
        for i in digits:
            nums = nums * 10 + i
        return [int(x) for x in str(nums+1)]
`

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for updating that! I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
