### ISSUE TITLE
Missing Test Case - 1341. Movie Rating

### ISSUE THREAD

**Issue by EricaHD** [LeetCode-Feedback/LeetCode-Feedback#13245]
#### Your LeetCode username
EricaHD

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
I would like to add a test case where the two results (user with the most ratings and the movie with the highest average rating) are the same string.

#### Code you used for Submit/Run operation
```
(
  SELECT users.name AS results
  FROM MovieRating rating
  JOIN Users users ON rating.user_id = users.user_id
  GROUP BY users.user_id, users.name
  ORDER BY count(*) DESC, users.name
  LIMIT 1
)
UNION
(
  SELECT movies.title AS results
  FROM MovieRating rate
  JOIN Movies movies ON rate.movie_id = movies.movie_id
  WHERE rate.created_at BETWEEN DATE('2020-02-01') AND DATE('2020-02-29')
  GROUP BY rate.movie_id, movies.title
  ORDER BY AVG(rate.rating) DESC, movies.title
  LIMIT 1
);
```

#### Language used for code
MySQL

#### Expected behavior
The above code was accepted as a valid solution.  However it fails the following test case:

```
# Movies

| movie_id | title   |
| -------- | ------- |
| 1        | Rebecca |

# Users

| user_id | name    |
| ------- | ------- |
| 1       | Rebecca |

# MovieRating

| movie_id | user_id | rating | created_at |
| -------- | ------- | ------ | ---------- |
| 1        | 1       | 5      | 2020-02-12 |
```

The above solution produces
```
| results |
| ------- |
| Rebecca |
```
instead of the expected
```
| results |
| ------- |
| Rebecca |
| Rebecca |
```
because it utilizes `UNION` instead of `UNION ALL`.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The test case is in Json format, such as :{"headers": {"Movies": ["movie_id", "title"], "Users": ["user_id", "name"], "MovieRating": ["movie_id", "user_id", "rating", "created_at"]}, "rows": {"Movies": [[1, "Avengers"], [2, "Frozen 2"], [3, "Joker"]], "Users": [[1, "Daniel"], [2, "Monica"], [3, "Maria"], [4, "James"]], "MovieRating": [[1, 1, 3, "2020-01-12"], [1, 2, 4, "2020-02-11"], [1, 3, 2, "2020-02-12"], [1, 4, 1, "2020-01-01"], [2, 1, 5, "2020-02-17"], [2, 2, 2, "2020-02-01"], [2, 3, 2, "2020-03-01"], [3, 1, 3, "2020-02-22"], [3, 2, 4, "2020-02-25"]]}}

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by EricaHD** [comment]
Here is the test case in JSON format:

```
{"headers": {"Movies": ["movie_id", "title"], "Users": ["user_id", "name"], "MovieRating": ["movie_id", "user_id", "rating", "created_at"]}, "rows": {"Movies": [[1, "Rebecca"]], "Users": [[1, "Rebecca"]], "MovieRating": [[1, 1, 5, "2020-02-12"]]}}
```

Thanks!

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
