### ISSUE TITLE
929. Unique Email Addresses - Small mistake in Solution

### ISSUE THREAD

**Issue by AjayVV** [LeetCode-Feedback/LeetCode-Feedback#1325]
#### Your LeetCode username
ajayvv

#### Category of the bug
- [x] Solution

#### Description of the bug
This statement is wrong:

>Remove all the _zeros_ from the local part.

It should be:
>Remove all the **dots** from the local part.

**Comment by lc-kay** [comment]
Hi @AjayVV 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @AjayVV 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
