### ISSUE TITLE
1216 翻译有误

### ISSUE THREAD

**Issue by zouyu9631** [LeetCode-Feedback/LeetCode-Feedback#13258]
**你的 LeetCode 用户名**
FreeYourMind

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
题目的翻译有误：
「给出一个字符串 s 和一个整数 k，若这个字符串是不是一个「k 回文 」，则返回 true 。」

**期望行为**
看英文题面，应该改成：
「给出一个字符串 s 和一个整数 k，若这个字符串是一个「k 回文 」，则返回 true 。」

**屏幕截图**
![image](https://user-images.githubusercontent.com/6801919/235841356-410fc71e-eb78-4bb9-a572-e7586503bb7c.png)

**Comment by feiceh** [comment]
感谢反馈，当前题目已更新，奖励已发放。
