### ISSUE TITLE
Ambiguous testcases and their execution

### ISSUE THREAD

**Issue by elrrowwe** [LeetCode-Feedback/LeetCode-Feedback#13250]
#### Your LeetCode username

elrrowwe 

#### Category of the bug
- [--] Question
- [--] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The output, for some reason, differs from the one I have on other platforms (other IDEs).

#### Code you used for Submit/Run operation

```
//Permutation Sequence
class Solution:
    def getPermutation(self, n: int, k: int) -> str:
        arr = []    
        m = 1
        while m <= n:
            arr.append(m)
            m+=1
        init = arr.copy()

        perms = self.heapalg(n, arr)
        perms.insert(0,''.join(map(str, init)))
        perms.sort()
        print(perms)

        return perms[k-1]

    #heap's algorithm for generating permutations 
    def heapalg(self, n: int, arr: list, perms=[]) -> list:
        if n == 1:
            return n
        else:    
            self.heapalg(n-1, arr)
            i = 0
            while i < n-1:
                if n % 2 == 0:
                    arr[i], arr[n-1] = arr[n-1], arr[i]
                    perms.append(arr.copy())
                else:
                    arr[0], arr[n-1] = arr[n-1], arr[0]
                    perms.append(arr.copy())

                self.heapalg(n-1, arr)
                i += 1

        perms = [''.join(map(str, x)) for x in perms]

        return perms
```

#### Language used for code

Python 

#### Expected behavior

The output, upon testing the code, was "2134" instead of the expected (which was also obtained in VS Code) "2314". The issue might be that, for some reason, after each testcase the list 'arr' is not empty (see screenshots below)

#### Screenshots

<img width="560" alt="leetcode" src="https://user-images.githubusercontent.com/116558151/235697595-fe6598c4-29c5-4d80-bcf1-03a853e0c173.png">
As can be seen from the result of line 13 in the code I provided above, the list of all permutations contains some permutations from the previous test cases.

The output on Leetcode:
<img width="90" alt="image" src="https://user-images.githubusercontent.com/116558151/235698222-76dd4b8e-2e5e-4872-9479-a22b865ab7bf.png">
The output in VS code (the value printed below the list is the perms[k-1] term, namely the value returned by getPermutation):
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/116558151/235698444-b1b52b68-e911-441d-a6ac-dc95498a79a1.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us! Unfortunately, we are unable to troubleshoot the different behavior between your local IDE and the LeetCode environment.

For this issue, please raise this as a discuss post in the problem discuss section as other users may have run into the same issue and resolved it.

At LeetCode, we care about the whole learning experience that comes with each problem and we encourage users to teach and help each other to enrich their learning. In addition, we want our users to debug their code and learn from the process.

We appreciate your time and support.
