### ISSUE TITLE
Missing Test Case - 2215. Find the Difference of Two Arrays

### ISSUE THREAD

**Issue by cconvey** [LeetCode-Feedback/LeetCode-Feedback#13264]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ X ] Missing Test Cases 

#### Description of the bug

Nothing in the problem description mentions that the input vectors are sorted.  However, both test cases I've seen use pre-sorted inputs.  This means programs that wrongly presume that the inputs are pre-sorted will still be accepted.

#### Code you used for Submit/Run operation

```
#include <algorithm>
#include <iostream>
#include <iterator>
#include <set>

using namespace std;

class Solution {
public:
    vector<vector<int>> findDifference(vector<int>& nums1, vector<int>& nums2) {
        set s1(nums1.begin(), nums1.end());
        set s2(nums2.begin(), nums2.end());

        vector<int> diff_1_2;
        set_difference(s1.begin(), s1.end(), s2.begin(), s2.end(), back_inserter(diff_1_2));
        
        vector<int> diff_2_1;
        set_difference(s2.begin(), s2.end(), s1.begin(), s1.end(), back_inserter(diff_2_1));

        return{ diff_1_2, diff_2_1 };
    }
};
```

#### Expected behavior

(My solution isn't super relevant here, because it's robust w.r.t. the missing unit test.)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Arrays are not always increasing.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
