### ISSUE TITLE
Missing Test Case - 1757. Recyclable and Low Fat Products

### ISSUE THREAD

**Issue by Navynaveen** [LeetCode-Feedback/LeetCode-Feedback#13269]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
an SQL query to find the ids of products that are both low-fat and recyclable

#### Code you used for Submit/Run operation

```
select
product_id
from
products
where low_fats='Y'
and
recyclable='Y'
;
```

#### Language used for code
<SQL>

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've submitted this feedback to our team. 

Thank you for your support.
