### ISSUE TITLE
2215. OJ accepts wrong answer

### ISSUE THREAD

**Issue by abshk-jr** [LeetCode-Feedback/LeetCode-Feedback#13260]
#### Your LeetCode username
abshk

#### Category of the bug
- [ ] Question
- [1] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The OJ accepts an answer in Python3, where the returned type is [set,set] instead of the expected [list,list].

#### Code you used for Submit/Run operation

```python
class Solution:
    def findDifference(self, nums1: List[int], nums2: List[int]) -> List[List[int]]:
        return [set(nums1)-set(nums2), set(nums2)-set(nums1)]
```

#### Language used for code
Python3

#### Expected behavior
An answer with such a return type should have thrown an error, but the OJ in my opinion accepts any iterable solution, instead of properly type-checking it.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

The judge automatically converts it to List. We think it’s accurate.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
