### ISSUE TITLE
Missing Test Case - 1697. Checking Existence of Edge Length Limited Paths

### ISSUE THREAD

**Issue by Rad0miR** [LeetCode-Feedback/LeetCode-Feedback#13261]
#### Your LeetCode username

Rad0miR

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

An accepted solution is getting TLE on this test case:
[Missing Test Case - 1697.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/11382119/Missing.Test.Case.-.1697.txt)

#### Code you used for Submit/Run operation

```
public class Solution {
    public bool[] DistanceLimitedPathsExist(int n, int[][] edgeList, int[][] queries) 
    {
        bool[] ans = new bool[queries.Length];
        
        int[] dsu = Enumerable.Range(0, n).ToArray();
        int[] ranks = Enumerable.Repeat(1, n).ToArray();

        int j = 0;
        Array.Sort(edgeList, (f, s) => f[2].CompareTo(s[2]));

        var ordered = queries.Select((q, i) => (q[2], q[0], q[1], i)).OrderBy(_ => _);
        foreach ((int limit, int p, int q, int i) in ordered) 
        {
            while (j < edgeList.Length && edgeList[j][2] < limit) Union(edgeList[j][0], edgeList[j++][1]);
            ans[i] = Find(p) == Find(q);
        } 

        return ans;

        int Find(int v) => v == dsu[v] ? v : Find(dsu[v]);

        void Union(int v, int u) 
        {
            v = Find(v);
            u = Find(u);

            if (ranks[v] < ranks[u]) (v, u) = (u, v);
            dsu[u] = v;
            ranks[v] += ranks[u];
        }
    }
}
```

#### Language used for code

C#

#### Expected behavior

This code is passing all tests and getting Accepted. But it should get TLE.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

We’re unable to add this test case because of technical issues.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
