### ISSUE TITLE
1672. Richest Customer Wealth- sum error on solution video

### ISSUE THREAD

**Issue by TiagoCruz2021** [LeetCode-Feedback/LeetCode-Feedback#13266]
#### Your LeetCode username

TiagoMCCruz

#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Hi. New here. Was going through Leetcode intro challenge problems. There´s a sum error at 1:43min in the solution video with the sum of wealth of customer 3.(it should be 1+9+5= 15)

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We will use your feedback to update the video. 

Unfortunately, this would be a very high effort to fix as it's a video and the error doesn’t actually affect the outcome of the algorithm so it is a low priority.

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
