### ISSUE TITLE
Missing Test Case - 1464. Maximum Product of Two Elements in an Array

### ISSUE THREAD

**Issue by narayanaly** [LeetCode-Feedback/LeetCode-Feedback#13279]
#### Your LeetCode username
LNarayana

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ 1] Missing Test Cases 

#### Description of the bug
[-7,-8,1,2]
the above testcase not specified. 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution:
    def maxProduct(self, nums: List[int]) -> int:
        mx1=max(nums)
        nums.remove(mx1)
        mx2=max(nums)
        return (mx1-1)*(mx2-1)
```

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
