### ISSUE TITLE
LC 815. Bus Routes. Edge testcase

### ISSUE THREAD

**Issue by nikamirrr** [LeetCode-Feedback/LeetCode-Feedback#13275]
#### Your LeetCode username
nikamir

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug
Missing edge test case when the source stop is not on any routes

#### Code you used for Submit/Run operation
Passing code
```
class Solution:
    def numBusesToDestination(self, routes: List[List[int]], source: int, target: int) -> int:
        if source == target:
            return 0
        routes_by_stop = dict()
        for ri, r in enumerate(routes):
            for s in r:
                try:
                    routes_by_stop[s].append(ri)
                except KeyError:
                    routes_by_stop[s] = [ri]
        try:
            dst_routes = set(routes_by_stop[target])
            q0 = routes_by_stop[source].copy()
        except KeyError:
            return -1
        routes_taken = set(q0)
        q1 = []
        n_routes = 1
        while q0:
            for ri in q0:
                if ri in dst_routes:
                    return n_routes
                for s in routes[ri]:
                    for nri in routes_by_stop[s]:
                        if nri not in routes_taken:
                            routes_taken.add(nri)
                            q1.append(nri)
            n_routes += 1
            q0, q1 = q1, q0
            q1.clear()
        return -1
```
Test case:
```
routes = [[2,7],[3,6,7]]
source = 1
target = 6
```

#### Language used for code
Python3

#### Expected behavior
return -1
Instead the code throws a KeyError exception.
Looks like no test cases cover the situation when the source stop it not on any route, but there is a test case when the destination is not on the route

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the judger appears to be working correctly.

https://leetcode.com/submissions/detail/944556420/
<img width="296" alt="Screen Shot 2023-05-04 at 3 37 19 PM" src="https://user-images.githubusercontent.com/103138242/236311574-22e026c4-3c60-45e1-a680-c6f4cbdadcfd.png">
