### ISSUE TITLE
Missing Test Case - 584. Find Customer Referee

### ISSUE THREAD

**Issue by Navynaveen** [LeetCode-Feedback/LeetCode-Feedback#13271]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
 an SQL query to report the names of the customer that are not referred by the customer with id = 2

#### Code you used for Submit/Run operation

```
select name from
customer
where referee_id !=2 or referee_id is null
;

```

#### Language used for code
SQL

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've submitted this feedback to our team. 

Thank you for your support.
