### ISSUE TITLE
Missing Test Case - 183. Customers Who Never Order

### ISSUE THREAD

**Issue by Navynaveen** [LeetCode-Feedback/LeetCode-Feedback#13272]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Write an SQL query to report all customers who never order anything.

#### Code you used for Submit/Run operation

```
select
name as Customers
from Customers as c left join orders o
on c.id=o.customerId
where o.id is null;
```

#### Language used for code
SQL

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've submitted this feedback to our team. 

Thank you for your support.
