### ISSUE TITLE
Missing Test Case - 1346. Check If N and Its Double Exist

### ISSUE THREAD

**Issue by Jeneesh1014** [LeetCode-Feedback/LeetCode-Feedback#13276]
I think there is a test case that is wrong but it expected answer is true

####Jeneesh
Jeneesh

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
[7,1,14,11]
this testcase should ans  false but it shows true

#### Code you used for Submit/Run operation
```
class Solution {
    public boolean checkIfExist(int[] arr) {
        for(int i=0;i<arr.length-1;i++){
            for(int j=i;j<arr.length;j++){
                if(arr[i]==2*arr[j]){
                    return true;
                }
            }
        }
        return false;
    }
}
```

#### Language used for code
Java

#### Expected behavior
Ans should be false according to this 
i != j
0 <= i, j < arr.length
arr[i] == 2 * arr[j]

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output values.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!
