### ISSUE TITLE
Inefficient Feedback and Doing Nothing about Feedbacks

### ISSUE THREAD

**Issue by Yawn-Sean** [LeetCode-Feedback/LeetCode-Feedback#13284]
https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/13213

Here is your reply about my issue and actually you do nothing about the negative feelings Chinese competitors had about the last weekly contest. You are just telling that there's nothing you can do about it.

But actually i launched the issue 4 days ago, and i think there is quite enough time for you to process it and figure out what to do with it.  Surprisingly, i saw my rating changed before i even got a reply to my issue. You replied without taking any concrete actions and closed the issue to seemingly "solve" the problem. i hardly think it is a proper attitude, as it is your fault for the bad experience and not making up for it. 

i wonder what's happening and if you would keep upsetting us with such inefficiency.

**Comment by Yawn-Sean** [comment]
What's more, it is not the first time that you have mis-translated the problem, and as far as i can see, you seemed to have take no measure. Even when 4 days ago, i wrote such a long page about what's happening, you still did nothing. Greatly disappointed.

**Comment by LC-Pam** [comment]
Dear user, 

We apologize for any inconvenience caused and understand your frustration with the issue that you raised. Please note that we take all feedback seriously and we have been actively investigating the matter. Our team has been working with the Chinese team and we are taking steps to address the concerns that were raised.

Regarding your rating change, we apologize for the confusion caused. However, please note that our team processes user reports and investigations independently from any individual’s rating.

We understand your concern and we are committed to providing the best experience possible for our users. Our team is constantly working to improve our platform and we appreciate your feedback. If there is anything else we can do to assist you, please do not hesitate to reach out.

Best regards,

The LeetCode Team.

**Comment by Yawn-Sean** [comment]
> However, please note that our team processes user reports and investigations independently from any individual’s rating.

"However, please note that our team processes user reports and investigations independently from any individual’s rating." Actually, I never expect you to processes user reports and investigation by any individual’s rating. I, as a common Leetcode user, was disappointed.

"Our team has been working with the Chinese team and we are taking steps to address the concerns that were raised." Hopefully, you will give a proper response.

**Comment by Yawn-Sean** [comment]
And actually, the influence isn't just about the higher-ranked ones. if you would take any time to take a look at other pages of the board, you will find that competitors, with different programming skills, were all influenced.

**Comment by feiceh** [comment]
感谢反馈，当前 LCCN WC343  已 unrate ， 排名更新好了～
