### ISSUE TITLE
2106. 摘水果题解笔误更正

### ISSUE THREAD

**Issue by mantoufan** [LeetCode-Feedback/LeetCode-Feedback#13287]
**你的 LeetCode 用户名**
mantoufan

**Bug 类型**
- [ ] 题目
- [x] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**期望行为**
[摘水果官方题解](https://leetcode.cn/problems/maximum-fruits-harvested-after-at-most-k-steps/solution/zhai-shui-guo-by-leetcode-solution-4j9v/) 图中 `右` 笔误，应改为 `左`
![image](https://user-images.githubusercontent.com/4961543/236187285-7e1a22af-bf86-4162-a2ee-9287ee30fba9.png)

**Comment by zuizaiqinshi** [comment]
感谢您的反馈～

**Comment by feiceh** [comment]
感谢反馈，奖励已发放，请查收。
