### ISSUE TITLE
1003. Check If Word Is Valid After Substitutions缺少测试用例

### ISSUE THREAD

**Issue by helloimcx** [LeetCode-Feedback/LeetCode-Feedback#13280]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述**
存在错误的代码也能通过全部测试用例

**你使用的语言**
C++

**你提交或者运行的代码**
```
// 1003. Check If Word Is Valid After Substitutionsclass Solution {
class Solution {
public:
    bool isValid(string s) {
        stack<char> stk;
        char temp = '0';
        for (auto c : s) {
            if (stk.size() >= 2 && c == 'c' && stk.top() == 'b' && temp == 'a') {
                stk.pop();
                stk.pop();
            } else {
                if (!stk.empty()) temp = stk.top();
                stk.push(c);
            }
        }
        return stk.empty();
    }
};
```

**期望行为**
 用例"bbabcc"应该包含在测试用例中，以上代码不应该判定为AC

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![image](https://user-images.githubusercontent.com/27777511/236126230-a93d3f3e-315c-455a-910a-ead8dd42386c.png)
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/27777511/236126838-c191231d-fd69-4d00-a6fa-f45cf82129e4.png">

上述代码在原有的测试用例中通过，增加自定义用例"bbabcc"后不通过

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by helloimcx** [comment]
chuxianmo

**Comment by feiceh** [comment]
收到，积分奖励已发放。
