### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by ramya-kosana** [LeetCode-Feedback/LeetCode-Feedback#1328]
Greetings Leetcode,

I noticed that during the contest, the user have to manually copy the input from the examples and paste them in the console. Moreover, there are situations where the input format needs to be readjusted in order for it to be accepted by the console. Perhaps we can work on a way of eliminating these manual work by the user and have those test cases available when the user opens up the problem. This would be greatly beneficial and time-efficient in both contest environment and regular practice environment.

Thanks

**Comment by lennon310** [comment]
There is a `use example testcases` button that you should be able to use.

**Comment by lc-kay** [comment]
Hi @ramya-kosana  ,
Thank you for your time. Upon investigating this issue, we found this issue to be non-content-related (the issue stems from an origin away from the content on this problem); therefore, it's not valid for content contribution reward. 
We encourage you to share more content-related issues here with us for [valid content contribution rewards](https://leetcode.com/discuss/general-discussion/526802/File-Problem-and-Solution-Content-Issues-to-Our-GitHub-Public-Feedback-Repo-Now!). Thank you again for your support and understanding.
