### ISSUE TITLE
Missing Test Case - 217. Contains Duplicate

### ISSUE THREAD

**Issue by heckrjoni** [LeetCode-Feedback/LeetCode-Feedback#13283]
This testcase gives wrong answer for my code but the code passed all the test cases.
[100001,1,2,3,1]

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [.] Missing Test Cases 

#### Description of the bug
I used hash tables but the collision isn't handled well in my code but the code passed all the test cases. 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool containsDuplicate(vector<int>& nums) {
        int arr[100000];
        int key1[100000],key2[100000],arr1[100000];
        for(int i=0;i<100000;i++)
            {
                arr[i]=0;
                arr1[i]=0;
                key1[i]=0;
                key2[i]=0;
            }
        for(int i=0;i<nums.size();i++)
        {
            int k=nums[i]%100000;
            if(k<0)
            {
                k=abs(k);
                if(arr1[k]==1)
                {
                    if(key1[k]==nums[i])
                    {
                        return true;
                    }
                }
                else
                {
                    arr1[k]=1;
                    key1[k]=nums[i];
                }
            }
            else
            {
                if(arr[k]==1)
                {
                    if(key2[k]==nums[i])
                    {
                        return true;
                    }
                }
                else
                {
                    arr[k]=1;
                    key2[k]=nums[i];
                }
            }
        }
        return false;
    }
};
```

#### Language used for code
C++

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've used your feedback to update the problem.

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback.

Please provide us your LCUS account name.

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!
