### ISSUE TITLE
Missing Test Case - 128. Longest Consecutive Sequence

### ISSUE THREAD

**Issue by Rad0miR** [LeetCode-Feedback/LeetCode-Feedback#13295]
#### Your LeetCode username

Rad0miR

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

An accepted solution is getting TLE on this test case:
[Missing Test Case - 128.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/11401864/Missing.Test.Case.-.128.txt)

#### Code you used for Submit/Run operation

```
public class Solution 
{
    class DSU 
    {
        private Dictionary<int, (int dsu, int rank)> _dsu = new();

        private int _Find(int v) => _dsu[v].dsu == v ? v : _Find(_dsu[v].dsu);

        private void _Union(int v, int u) 
        {
            v = _Find(v);
            u = _Find(u);

            if (v == u) return;

            var vd = _dsu[v];
            var ud = _dsu[u];
            
            _dsu[u] = (v, ud.rank);
            _dsu[v] = (v, vd.rank + ud.rank);
        } 

        private void CreateIfNotPresent(int v) 
        {
            if (!_dsu.ContainsKey(v)) _dsu[v] = (v, 1);
        }

        public int Find(int v) 
        {
            CreateIfNotPresent(v);
            return _Find(v); 
        }

        public void Union(int v, int u) 
        {
            CreateIfNotPresent(v);
            CreateIfNotPresent(u);
            _Union(v, u);
        }

        public int Size(int v) => _dsu[_Find(v)].rank;
    }

    public int LongestConsecutive(int[] nums) 
    {
        if (!nums.Any()) return 0;
        DSU dsu = new();
        foreach (int x in nums) dsu.Union(x, x + 1);
        return nums.Max(dsu.Size) - 1;
    }
}
```

#### Language used for code

C#

#### Expected behavior

This code is passing all tests and getting Accepted. But it should get TLE.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
