### ISSUE TITLE
Constraints Missing: 319 Bulb Switcher

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1329]
#### Your LeetCode username

[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

319. Bulb Switcher: https://leetcode.com/problems/bulb-switcher/

Constraints are missing

What are the ranges of n

#### Code you used for Submit/Run operation

```
# Bulb Switcher
class Solution:
    def bulbSwitch(self, n: int) -> int:
        string = ['N']*n
        for i in range(n):
            for j in range(n):
                if (j+1) % (i+1) == 0:
                    if string[j]=='N':
                        string[j]='Y'
                    else:
                        string[j]='N'
        return string.count('Y')
```
Time complexity: O(n^2)

#### Language used for code

Python

#### Expected behavior

- TLE on test case 10000 because of missing constraints information.
- The question must have constraints to avoid TLE errors.

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
