### ISSUE TITLE
Missing Test Case - 1873. Calculate Special Bonus

### ISSUE THREAD

**Issue by Navynaveen** [LeetCode-Feedback/LeetCode-Feedback#13293]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Write an SQL query to calculate the bonus of each employee. The bonus of an employee is 100% of their salary if the ID of the employee is an odd number and the employee name does not start with the character 'M'. The bonus of an employee is 0 otherwise.

#### Code you used for Submit/Run operation

```
select
employee_id,
case
    when employee_id%2!=0 and substr(name,1,1)!='M' then salary
    else 0
    end as bonus
from Employees
;

```

#### Language used for code
SQL

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
