### ISSUE TITLE
2666. Allow One Function Call — Wrong test logic

### ISSUE THREAD

**Issue by alantudyk** [LeetCode-Feedback/LeetCode-Feedback#13291]
#### Your LeetCode username

0x81

#### Code you used for Submit/Run operation

You have to check the count of calls in some other way:

```js
const once = f =>
    (...a) => {
        let r = f(...a)
        r = f(...a)  // 2nd call
        if (r) {
            // console.log(r)
            r.calls = 1
        }
        f = () => undefined
        return r
    }
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
