### ISSUE TITLE
Missing Test Case - 1005. Maximize Sum Of Array After K Negations

### ISSUE THREAD

**Issue by c47harsis** [LeetCode-Feedback/LeetCode-Feedback#13292]
#### Your LeetCode username

wallandteen

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I occasionally wrote a wrong algo and it passes all tests. 
In this solution I tried to calculate the sum of all elements in the beginning and I thought that it could be such a good optimisation to just return zero if the initial sum is zero. But it shouldn't work like that.
For example, initial sum for input [-1, 0, 1] is zero, but with any value of k I can maximise it easily just turning -1 to 1 and toggling 0 after that until k is not 0. But my algo just says that, not depending on the k, result is 0. That shouldn't pass your tests.

#### Code you used for Submit/Run operation

```
class Solution {
    public int largestSumAfterKNegations(int[] nums, int k) {
        int sum = 0;
        int[] d = new int[201];
        for (int n: nums) {
            sum += n;
            d[100 + n]++;

        }

        if (sum == 0) {
            return 0; // Here is the problem
        }

        while (k != 0) {
            k--;
            int i = 0;
            while (i < d.length && d[i] == 0) {
                i++;
            }
            d[i]--;
            d[200 - i]++;
            sum -= 2 * (i - 100);
        }

        return sum;
    }
}
```

#### Language used for code

Java

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Please provide the test case explicitly.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
