### ISSUE TITLE
Missing Test Case - 1280. Students and Examinations

### ISSUE THREAD

**Issue by OnSagagit** [LeetCode-Feedback/LeetCode-Feedback#13290]
#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by OnSagagit** [comment]
this is the example Im very intrested in have all the parts but same solution not working in leetcode

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
