### ISSUE TITLE
The description of [115. Distinct Subsequences] is incomplete

### ISSUE THREAD

**Issue by hairman123** [LeetCode-Feedback/LeetCode-Feedback#133]
**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
The problem [115. Distinct Subsequences] has a testcase and **the answer is greater than INT_MAX**. However, the problem description said nothing about how to deal with it.
(Some other problems use 10^9 + 7 modulo.)
Testcase: https://leetcode.com/submissions/detail/323019181/testcase/

**what language is your code written in**
C++

**The code you submit/run**
my runtime error code https://leetcode.com/submissions/detail/323019181/
```
class Solution {
public:
    int numDistinct(string s, string t) {
        if(t.size() > s.size())
            return 0;
        if(!s.size())
            return 1;
        int dp[s.size()][t.size()];
        dp[0][0] = s[0] == t[0];
        for(int i = 1; i < s.size(); ++i)
            dp[i][0] = dp[i-1][0] + (s[i] == t[0]);
        for(int j = 1; j < t.size(); ++j) {
            dp[0][j] = 0;
            for(int i = 1; i < s.size(); ++i)
                dp[i][j] = dp[i-1][j] + (s[i] == t[j]? dp[i-1][j-1] : 0);
        }
        return dp[s.size()-1][t.size()-1];
    }
};
```

**Screenshots**
![image](https://user-images.githubusercontent.com/62042171/79040612-3ba7c280-7c1c-11ea-9ca9-96e320f1fe96.png)

**Comment by CooperCooperCooper** [comment]
Hi @hairman123,
Thank you for reaching out to us! I've relayed your feedback to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @hairman123,
Thank you for your time. We've used your feedback to update the statement.

We appreciate your support. Please reach out to our [main support channel](https://support.leetcode.com/hc/en-us) to share your username + this ticket with us to claim your LeetCoin reward for reporting this content issue!

**Comment by hairman123** [comment]
But the problem still has a testcase
```
"xslledayhxhadmctrliaxqpokyezcfhzaskeykchkmhpyjipxtsuljkwkovmvelvwxzwieeuqnjozrfwmzsylcwvsthnxujvrkszqwtglewkycikdaiocglwzukwovsghkhyidevhbgffoqkpabthmqihcfxxzdejletqjoxmwftlxfcxgxgvpperwbqvhxgsbbkmphyomtbjzdjhcrcsggleiczpbfjcgtpycpmrjnckslrwduqlccqmgrdhxolfjafmsrfdghnatexyanldrdpxvvgujsztuffoymrfteholgonuaqndinadtumnuhkboyzaqguwqijwxxszngextfcozpetyownmyneehdwqmtpjloztswmzzdzqhuoxrblppqvyvsqhnhryvqsqogpnlqfulurexdtovqpqkfxxnqykgscxaskmksivoazlducanrqxynxlgvwonalpsyddqmaemcrrwvrjmjjnygyebwtqxehrclwsxzylbqexnxjcgspeynlbmetlkacnnbhmaizbadynajpibepbuacggxrqavfnwpcwxbzxfymhjcslghmajrirqzjqxpgtgisfjreqrqabssobbadmtmdknmakdigjqyqcruujlwmfoagrckdwyiglviyyrekjealvvigiesnvuumxgsveadrxlpwetioxibtdjblowblqvzpbrmhupyrdophjxvhgzclidzybajuxllacyhyphssvhcffxonysahvzhzbttyeeyiefhunbokiqrpqfcoxdxvefugapeevdoakxwzykmhbdytjbhigffkmbqmqxsoaiomgmmgwapzdosorcxxhejvgajyzdmzlcntqbapbpofdjtulstuzdrffafedufqwsknumcxbschdybosxkrabyfdejgyozwillcxpcaiehlelczioskqtptzaczobvyojdlyflilvwqgyrqmjaeepydrcchfyftjighntqzoo"
"rwmimatmhydhbujebqehjprrwfkoebcxxqfktayaaeheys"
```
and the answer is **NOT** fits on a 32-bit signed integer; It's **GREATER** than INT_MAX.

**Comment by CooperCooperCooper** [comment]
Hi @hairman123,
Thank you for your response. I've relayed the test case to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @hairman123,
Our team took a thorough look at the submitted information and wanted to share that the answer for the mentioned test case is 543'744'000 (note this number fits in a 32 bit signed value). We hope this helps. Thank you for your time.
