### ISSUE TITLE
Missing Test Case - 13. Roman to Integer

### ISSUE THREAD

**Issue by David-jkl** [LeetCode-Feedback/LeetCode-Feedback#13301]
#### Category of the bug
- Missing Test Cases 

#### Use Case
IVXLCDM
This is another use case.

#### Code you used for Submit/Run operation

```
import java.util.*;

class Solution {
    public int romanToInt(String s) {
        Map<Character, Integer> romanToIntMap = new HashMap<>();
        romanToIntMap.put('I', 1);
        romanToIntMap.put('V', 5);
        romanToIntMap.put('X', 10);
        romanToIntMap.put('L', 50);
        romanToIntMap.put('C', 100);
        romanToIntMap.put('D', 500);
        romanToIntMap.put('M', 1000);


        int result = 0;

        
        for (int i = s.length() - 1; i >= 0; i--) {
            if (i < s.length() - 1 && romanToIntMap.get(s.charAt(i)) < romanToIntMap.get(s.charAt(i + 1))) {
                result -= romanToIntMap.get(s.charAt(i));
            }
            else {
                result += romanToIntMap.get(s.charAt(i));
            }
        }

        return result;
    }
}

class Main {
    public static void main(String[] args) {
        Solution solution = new Solution();
        System.out.println(solution.romanToInt("III"));      
        System.out.println(solution.romanToInt("IV"));      
        System.out.println(solution.romanToInt("IX"));      
        System.out.println(solution.romanToInt("LVIII"));    
        System.out.println(solution.romanToInt("MCMXCIV"));  
    }
}

```

#### IVXLCDM is not a valid Roman numeral because the same character (e.g., "I", "X", "C", or "M") cannot appear more than three times in a row.

However, if we break it down into valid Roman numerals, we can get:

IV: 4
XL: 40
CD: 400
M: 1000
So the total value of IVXLCDM would be 4 + 40 + 400 + 1000 = 1444.

It's worth noting that this representation of 1444 is not standard in Roman numerals, and would likely be considered incorrect in most contexts.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by stormsunshine** [comment]
The input "IVXLCDM" is NOT a valid Roman integer. Why do you want to provide an invalid test case?

**Comment by David-jkl** [comment]
LeetCode,

I apologize for any confusion this may have caused.

The reason for including an invalid test case was to ensure that my code is
robust enough to handle unexpected input and edge cases. While the input
"IVXLCDM" is not a valid Roman integer, it is possible that such input may
be accidentally or maliciously provided to the program. By including this
test case, I am ensuring that my program can handle such input gracefully,
without crashing or producing incorrect output.

Thank you for your message, and let me know if you have any further
questions or concerns.

Best regards,
JIMIL

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Question is unclear. We don’t have IVXLCDM in our test cases.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
