### ISSUE TITLE
310. Minimum Height Trees - Wrong test

### ISSUE THREAD

**Issue by withelm** [LeetCode-Feedback/LeetCode-Feedback#1330]
#### Your LeetCode username
withelm

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

https://leetcode.com/problems/minimum-height-trees/
![image](https://user-images.githubusercontent.com/4776601/98092075-8d4cbe80-1e86-11eb-8b02-589349c1e9a3.png)
Task have limit for n.
But one test case have n = 5000. 
![image](https://user-images.githubusercontent.com/4776601/98092223-b705e580-1e86-11eb-9985-b3148b37cc54.png)

**Comment by lc-kay** [comment]
Hi @withelm 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@withelm Test case #65 is a valid test case and satisfy all constraints. Please note that 5000 is indeed less than 20000 (2*10^4). Thank you for your time!
