### ISSUE TITLE
Missing Test Case - 2035. Partition Array Into Two Arrays to Minimize Sum Difference

### ISSUE THREAD

**Issue by rishabhyaduwanshi** [LeetCode-Feedback/LeetCode-Feedback#13307]
#### Your LeetCode username

 Rishabh_yaduwanshi

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [*] wrong Test Case

#### Description of the bug

the test case 55 of the question expects an output of 2,but output must be 0.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    public int minimumDifference(int[] nums) {
        int ans=Integer.MAX_VALUE;
        // int n=nums.length;
        int sum=0;
        int max=Integer.MAX_VALUE;
        for(int i:nums){
            max=Math.min(max,i);
        }
        if(max<0){
        max=Math.abs(max);
        for(int i=0;i<nums.length;i++){
            nums[i]+=max;
        }
        }
        for(int i:nums){
            sum+=i;
        }
        int n=nums.length;
        int total=sum;
        int[][] dp=new int[n][sum+1];
        for(int[] arr:dp){
            Arrays.fill(arr,-1);
        }
        // boolean[] temp=new boolean[sum+1];
        for(int i=0;i<=total;i++){
            boolean status=helper(n-1,i,nums,dp);
            if(status){
                // System.out.println(i);
                ans=Math.min(Math.abs(sum-2*i),ans);
            }
        }
        return ans;
    }
    public boolean helper(int n,int sum,int[] nums,int[][] dp){
        if(sum==0) return true;
        if(dp[n][sum]!=-1) return dp[n][sum]==1;
        if(n==0){
            dp[0][nums[n]]=sum==0?1:0;
            return sum==0;
        }
        boolean include=false;
        if(sum>=nums[n-1]){
            include=helper(n-1,sum-nums[n-1],nums,dp);
            }
        boolean exclude=helper(n-1,sum,nums,dp);
        dp[n][sum]=include||exclude==true?1:0;
        return dp[n][sum]==1;
    }
}
```

#### Language used for code

JAVA

#### Expected behavior

the testcase 55 is [76,8,45,20,74,84,28,1]
the sum of this array is 336 and half of it is 168.
the question is about finding the minimum absolute difference so if we sum up 76+8+84 we get 168 which means the second half is also 168 and the minimum absolute difference will be 0,but the testcase expects 2 as an output which is wrong and should be corrected.

#### Screenshots

![Screenshot 2023-05-05 at 16-56-09 Partition Array Into Two Arrays to Minimize Sum Difference - Submission Detail - LeetCode](https://user-images.githubusercontent.com/92936938/236446146-0619836d-e447-4627-9c41-5590c6391c3e.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
