### ISSUE TITLE
Add reference to Union Find study card in Approach #3 261. Graph Valid Tree

### ISSUE THREAD

**Issue by davitescobedo** [LeetCode-Feedback/LeetCode-Feedback#13311]
#### Your LeetCode username

eldavimost

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Approach #3 solution says "We don't yet have an explore card on union find (at the time of writing this!)". Please link to the union find study card here!

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've submitted your feedback to the team, we will add the link once we have the explore card. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
