### ISSUE TITLE
Find the Difference of Two Arrays 

### ISSUE THREAD

**Issue by pltnv123** [LeetCode-Feedback/LeetCode-Feedback#13310]
#### Your LeetCode username
kycalavo

#### Category of the bug

- [ + ] Missing Test Cases 

#### Description of the bug
On the 101 case , he swears at a mistake

#### Code you used for Submit/Run operation

```
// Find the Difference of Two Arrays 
class Solution:
    def findDifference(self, nums1: List[int], nums2: List[int]) -> List[List[int]]:
        x = [[],[]]
        for i in nums1:
            if i in nums2:
                continue
            else: 
                if i not in x[0]:
                     x[0].append(i)

        for j in nums2:
            if j in nums1:
                continue
            else:
                if i not in x[1]:
                    x[1].append(j)
        return x
```

#### Language used for code
Python3

#### Expected behavior
The code works as expected, the test does not skip, writes variables in a different order

#### Screenshots
![image](https://user-images.githubusercontent.com/84674657/236551877-61c4f44f-dab6-4ee2-8f36-c0e97f6206cb.png)

#### Additional context
I don't understand what the error is, my code is clumsy, but it seems to be correct...

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
