### ISSUE TITLE
C#代码题解bug需要修改

### ISSUE THREAD

**Issue by userzbh666** [LeetCode-Feedback/LeetCode-Feedback#13317]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [ ] 题目
- [√ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
描述你遇到的 bug
C#题解的代码没有颜色，看着很难受，经检验，应该是题解语句块中的```C# [] 中的#识别错误，导致bug，希望可以尽快修复

**你使用的语言**
C#

**Comment by feiceh** [comment]
Hello～感谢反馈，这个问题已经提交至负责团队尽快复现并排查定位的。Github 仓库只用于反馈大家在本站学习过程中遇到的题目和题解问题，目前我们会暂时关闭该 issue，如有更多反馈和建议欢迎  [点击这里](https://support.leetcode.cn/hc/request/new/) 提交工单反馈，给您带来的不便敬请谅解。
