### ISSUE TITLE
Space complexity analysis is wrong for two Python solutions - 1498. Number of Subsequences That Satisfy the Given Sum Condition

### ISSUE THREAD

**Issue by lh070355** [LeetCode-Feedback/LeetCode-Feedback#13313]
#### Your LeetCode username

lc_666

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Space complexity analysis is wrong for two Python solutions. The original analysis is "O(1) for python". Since both solutions use Python built-in function `sort`, and Python apply Timsort with space complexity O(n), it should be O(n).

#### Screenshots

![image](https://user-images.githubusercontent.com/36730976/236590640-acd13dc5-67ec-40b6-a7f5-c20abe04c519.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
