### ISSUE TITLE
给941这个算法题，加一个测试用例，[1,1,1,1,1,1,1,2,1]

### ISSUE THREAD

**Issue by luanjerry** [LeetCode-Feedback/LeetCode-Feedback#1331]
** Bug 类型**
- [ 941] 题目，，增加测试用例
- [python 3 ] 编程语言

**描述**
描述你遇到的 bug
如果少了这个测试用例，有些代码也通过，不严谨

**你使用的语言**
python 3 

**你提交或者运行的代码**
```
class Solution:
    def validMountainArray(self, A: List[int]) -> bool:
        s=len(A)
        t=1
        for i in range(1,s):
            if t and A[i-1]>A[i]:
                if i==1:
                    return False
                t=0
            if not t and A[i-1]<=A[i]:return False
        return t==0

```

**期望行为**
不增加这个测试用例，会导致一些边界考虑不周的，代码也通过，

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![941问题需要增加的测试用例](https://user-images.githubusercontent.com/50862638/98093834-6d87bb80-1ec3-11eb-91ba-e31b59dce220.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认的～

**Comment by feiceh** [comment]
亲，当前该题已添加测试用例， 请留言告知一下您的力扣 ID，我们给予积分奖励哦。
