### ISSUE TITLE
Incomplete Question - 1028. Recover a Tree From Preorder Traversal

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1332]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

1028. Recover a Tree From Preorder Traversal
https://leetcode.com/problems/recover-a-tree-from-preorder-traversal/

Below is given in the question description:

- Given the output S of this traversal, recover the tree and return its root.

Question:
- recover the tree in which order? inorder, preorder, postorder or level order?

Please change as below (or something like that)
> From - Given the output S of this traversal, recover the tree and return its root.
> To  - Given the output S of this traversal, recover the tree and return its root, in level order form.

#### Code you used for Submit/Run operation

```
```

#### Expected behavior

- User should not be forced to derive question requirements from Test cases
- The question must be complete, in order to solve it with confidence.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@manoharreddyporeddy 
The problem asks to return the tree itself not its traversal, therefore, your suggestion was not added. Thank you for your time!
