### ISSUE TITLE
Missing Test Case - 162. Find Peak Element

### ISSUE THREAD

**Issue by praveenklm** [LeetCode-Feedback/LeetCode-Feedback#13324]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x] Missing Test Cases 

#### Description of the bug

Described logN solution does not work for input: "2, 3, 2, 4, 5, 6, 7"

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by praveenklm** [comment]
Thank you,

https://leetcode.com/problems/find-peak-element/submissions/945837542/

This code suppossed to fail for test case : "2, 3, 2, 4, 5, 6, 7" but succeeding 6 as output while output should be 3

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've used your feedback to update the problem.

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback.

Please provide us your LCUS account name.

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!

**Comment by praveenklm** [comment]
Great. Thank you. here my leetcode account name: codingjerk

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
