### ISSUE TITLE
Missing Test Case - 50. Pow(x, n)

### ISSUE THREAD

**Issue by ChristopherRogers1991** [LeetCode-Feedback/LeetCode-Feedback#13327]
#### Your LeetCode username
crogersisleet

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
`Pow` is missing the case of `0^0`, which should be 1.

#### Code you used for Submit/Run operation
I caught this not because of my own code, but because I was comparing to the top solution. The code for that solution is:
```
class Solution:
    def myPow(self, x: float, n: int) -> float:
        def helper(x, n):
            if x == 0:
                return 0
            if n == 0:
                return 1

            res = helper(x * x, n // 2)
            return x * res if n % 2 else res

        res = helper(x, abs(n))
        return res if n >= 0 else 1 / res
```

The bug occurs because of the order of the base cases - the `x == 0` check should come after the `n == 0` check.

#### Language used for code
Python

#### Expected behavior
`0^0` should equal 1. The code above is an accepted solution (the top solution, based on perf metrics), but will fail this case. Here's proof:

```
class Solution:
    def myPow(self, x: float, n: int) -> float:
        def helper(x, n):
            if x == 0:
                return 0
            if n == 0:
                return 1
            res = helper(x * x, n // 2)
            return x * res if n % 2 else res
        res = helper(x, abs(n))
        return res if n >= 0 else 1 / res
    
Solution().myPow(0, 0)
0
from math import pow
pow(0, 0)
1.0
0 ** 0
1
```

#### Screenshots
Screenshot showing the code above is an accepted solution:
![image](https://user-images.githubusercontent.com/8608191/236658121-e199caf4-a3db-4114-8906-4852fa538341.png)

**Comment by stormsunshine** [comment]
The expression 0^0 is meaningless so it should NOT exist. It is the same as divided by zero. Do you think dividing by zero is a meaningful calculation?

**Comment by ChristopherRogers1991** [comment]
To highlight an important part of my comment above, Python defines 0^0 as 1:
```
>>> from math import pow
>>> pow(0, 0)
1.0
>>> 0 ** 0
1
```

At best, you could say that the 0^0 is ambiguous, either 'undefined' or 1. See https://brilliant.org/wiki/what-is-00/, and note this section:

> Many sources consider 0^0 to be an "indeterminate form," or say that 0^0 is "undefined." On the other hand, other sources/branches of mathematics define 0^0 = 1. Note that, certainly, 0^0 ≠ 0.

So, some people consider it undefined, and others consider it 1, but 0 is always wrong, so the top accepted solution is incorrect, as are any others that return 0 for the value.

You have compared it to dividing by 0, which is universally accepted to be an issue in mathematics. If it is truly undefined, then it should throw an error, as dividing by 0 does:

```
0 / 0
Traceback (most recent call last):
  File "/snap/pycharm-community/329/plugins/python-ce/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
ZeroDivisionError: division by zero
```

It is also worth noting the problem constraints:

![image](https://user-images.githubusercontent.com/8608191/236659492-32ac327d-0c95-4168-b355-484daaefc3d5.png)

The problem defines `n` as a signed 32 bit integer. It does not make any caveat for 0, therefore 0 is valid, and should produce a valid result (no error).

Given the above, the only "correct" answer is 1, which as noted above is consistent with the Python. It is also consistent with Java:
```
chris@lappy:/home/chris/Downloads (22:30:40)
$ cat Zero.java 
import java.lang.Math;

public class Zero {
    public static void main(String[] args) {
        System.out.println(Math.pow(0,0));
    }
}

chris@lappy:/home/chris/Downloads (22:30:44)
$ javac Zero.java

chris@lappy:/home/chris/Downloads (22:30:48)
$ java Zero 
1.0
```

And C:
```

chris@lappy:/home/chris/Downloads (22:33:33)
$ cat zero.c 
#include <stdio.h>
#include <math.h>

int main(int argc, const char * argv[])
{
    printf("%f", pow(0.0, 0.0));

    return 0;
}

chris@lappy:/home/chris/Downloads (22:33:36)
$ gcc -o zero zero.c 

chris@lappy:/home/chris/Downloads (22:33:47)
$ ./zero
1.000000
```

And JavaScript:
```
Math.pow(0, 0)
1
```

And Haskell:
```
chris@lappy:/home/chris/Downloads (22:41:17)
$ ghci
GHCi, version 9.0.2: https://www.haskell.org/ghc/  :? for help
ghci> 0^0
1
```

That's all I had that was relatively convenient to test with. This should be consistent.

**Comment by stormsunshine** [comment]
I have already mentioned this one before, in issue #9010 .

LeetCode didn't change the constraints, but updated the validator. If you put 0^0 in custom test case, there will be a message that "0 cannot be raised to a non-positive power". So if x is 0, then n must be a positive value.

**Comment by ChristopherRogers1991** [comment]
It seems like the bug was not having the test case, rather than an issue with the validator. I would suggest that the change made for #9010 be reverted, and the 0^0 test case added.

Why be inconsistent with the languages in which the answers are being written?

**Comment by LC-Pam** [comment]
@ChristopherRogers1991 @stormsunshine 

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

We guaranteed that if x = 0 then n > 0.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
