### ISSUE TITLE
Inaccurate function return type in JSDoc

### ISSUE THREAD

**Issue by hemingqiao** [LeetCode-Feedback/LeetCode-Feedback#13323]
#### Your LeetCode username

chisato_suki

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

the return value of `promisePool` should be a `Promise` not `Function`

#### Code you used for Submit/Run operation

[2636. Promise Pool](https://leetcode.com/problems/promise-pool/)

```
/**
 * @param {Function[]} functions
 * @param {number} n
 * @return {Function}
 */
var promisePool = async function(functions, n) {

};

/**
 * const sleep = (t) => new Promise(res => setTimeout(res, t));
 * promisePool([() => sleep(500), () => sleep(400)], 1)
 *   .then(console.log) // After 900ms
 */
```

#### Expected behavior

use `Promise` to describe the return value may be clearer

```
/**
 * @param {Function[]} functions
 * @param {number} n
 * @return {Promise}
 */
var promisePool = async function(functions, n) {

};

/**
 * const sleep = (t) => new Promise(res => setTimeout(res, t));
 * promisePool([() => sleep(500), () => sleep(400)], 1)
 *   .then(console.log) // After 900ms
 */
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

This change has already been made.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
