### ISSUE TITLE
270 官方题解错误

### ISSUE THREAD

**Issue by cuber-lotus** [LeetCode-Feedback/LeetCode-Feedback#13320]
**你的 LeetCode 用户名**

| name         | about                                                        | title        | labels   | assignees                                                   |
| ------------ | ------------------------------------------------------------ | ------------ | -------- | ----------------------------------------------------------- |
| 270 题解错误 | [270. 最接近的二叉搜索树值](https://leetcode.cn/problems/closest-binary-search-tree-value/) | 270 题解错误 | 题解错误 | [天赐细莲  cuber-lotus](https://leetcode.cn/u/cuber-lotus/) |

**Bug 类型**

- [ ] 题目
- [x] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
题解中用到的三元表达式来维护答案

但是三元表达式没考虑到两个`abs`相等的情况，所以官方题解样例代码错误

**你使用的语言**

java （本issue无关语言）

**你提交或者运行的代码**

```java
// 方法三 java代码
// can not ac
class Solution {
  public int closestValue(TreeNode root, double target) {
    int val, closest = root.val;
    while (root != null) {
      val = root.val;
      closest = Math.abs(val - target) < Math.abs(closest - target) ? val : closest;
      root =  target < root.val ? root.left : root.right;
    }
    return closest;
  }
}

/*
作者：LeetCode
链接：https://leetcode.cn/problems/closest-binary-search-tree-value/solution/zui-jie-jin-de-er-cha-sou-suo-shu-zhi-by-leetcode/
来源：力扣（LeetCode）
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。
*/
```

```java
// ac code
class Solution {
    public int closestValue(TreeNode root, double target) {
        int closest = root.val;
        while (root != null) {
            double diff1 = Math.abs(root.val - target);
            double diff2 = Math.abs(closest - target);
            if (diff1 == diff2) {
                closest = Math.min(root.val, closest);
            } else {
                closest = diff1 < diff2 ? root.val : closest;
            }
            root =  target < root.val ? root.left : root.right;
        }
        return closest;
    }
}
```

**期望行为**

```bash
# 两个典型样例
[4,2,5,1,3]
4.5
[4,2,5,1,3]
3.5
```

```bash
# 官方题解代码结果
4
4

# 正确结果
4
3
```

**额外的上下文**

同理，官方题解中因为这个情况错误的代码有多份，涉及多个方法

**Comment by zuizaiqinshi** [comment]
官方暂时将该内容下线，后台进行查证确有问题后会进行迭代，感谢您的反馈～
