### ISSUE TITLE
Missing Test Case - 2671. Frequency Tracker

### ISSUE THREAD

**Issue by zhenliang153** [LeetCode-Feedback/LeetCode-Feedback#13330]
#### Your LeetCode username

zhenliang153

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

`std::multiset::count` or `std::unordered_multiset::count` should not be used here.
We can generate a test case through the following Python code:
```python
a = ["FrequencyTracker"]
b = [[]]

N = 5 * 10**4

for i in range(N):
    a.append("add")
    a.append("hasFrequency")
    b.append([1])
    b.append([i + 1])

print("[%s]" % ",".join(map(lambda x : "\"%s\"" % x, a)))
print("[%s]" % ",".join(map(str, b)))
```

#### Code you used for Submit/Run operation

```
// 2671. Frequency Tracker
class FrequencyTracker {  
public:
    FrequencyTracker() {

    }

    void add(int number) {
        update(number, -1);
        ms.insert(number);
        update(number, 1);
    }
    
    void deleteOne(int number) {
        update(number, -1);
        if(auto it = ms.find(number); it != ms.end()) {
            ms.erase(it);
        }
        update(number, 1);
    }
    
    bool hasFrequency(int frequency) {
        auto itor = m.find(frequency);
        return itor != m.end() && itor->second > 0;
    }

private:
    multiset<int> ms;
    map<int, int> m;

    void update(int x, int v) {
        int freq = ms.count(x);
        m[freq] += v;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Output: TLE
Expected: Right Answer

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
