### ISSUE TITLE
Question 938 : Range Sum of BST not-tested  TestCase

### ISSUE THREAD

**Issue by reuzun** [LeetCode-Feedback/LeetCode-Feedback#1333]
Leetcode username : reuzun

In question 938 if we try test case as following : 
[5,4,3,6,7,1,2,8,9,10,11,0,-2,-7,128,127,129]
-100
0
the expected result is 0 . But the real answer must be -9.

photo:
![Doc1](https://user-images.githubusercontent.com/73116832/98108134-8f297880-1eac-11eb-9657-e05adcdefe59.png)

**Comment by lc-kay** [comment]
Hi @reuzun 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @reuzun 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
