### ISSUE TITLE
There is a wrong subtitle in LeetCode 75 study plan  学习计划75题中有一处子标题错误

### ISSUE THREAD

**Issue by xiaoyuze88** [LeetCode-Feedback/LeetCode-Feedback#13342]
![image](https://user-images.githubusercontent.com/5201649/236687382-b6bf70f5-56e5-4e0a-a4e9-be0525beaf8d.png)

As shown above, there's two graph bfs, maybe the last one should be priority heap?

有两个图-广度优先搜索，第二个应该是堆（优先队列）吧？

**Comment by zuizaiqinshi** [comment]
官方已修改，感谢您的反馈～

**Comment by feiceh** [comment]
你好，当前问题已修复，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by xiaoyuze88** [comment]
> 你好，当前问题已修复，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

tks

leetcode.cn/u/xiaoyuze88/

**Comment by feiceh** [comment]
收到，积分奖励已发放。
