### ISSUE TITLE
2622. Cache With Time Limit - Incorrect test case example

### ISSUE THREAD

**Issue by mnaoumov** [LeetCode-Feedback/LeetCode-Feedback#13349]
#### Your LeetCode username

mnaoumov

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Example 2 of the problems declares output as `[null, false, true, 50, 50, -1]` which is wrong, because it has only 6 items, while the input arrays for `commands`, `parameters` and `times` have 7 items.

The output for the 7th command `count()` is missing from the output and should be `0`.

#### Code you used for Submit/Run operation

```js
var TimeLimitedCache = function() {
    this.valuesMap = new Map();
    this.timeoutsMap = new Map();
};

/** 
 * @param {number} key
 * @param {number} value
 * @param {number} time until expiration in ms
 * @return {boolean} if un-expired key already existed
 */
TimeLimitedCache.prototype.set = function(key, value, duration) {
    const isNew = !this.timeoutsMap.has(key);

    if (!isNew) {
        const previousTimeoutId = this.timeoutsMap.get(key);
        if (previousTimeoutId !== null) {
            clearTimeout(previousTimeoutId);
        }
    }

    this.valuesMap.set(key, value);
    const timeoutId = setTimeout(() => {
        this.timeoutsMap.delete(key);
        this.valuesMap.delete(key);
    }, duration);

    this.timeoutsMap.set(key, timeoutId);

    return !isNew;
};

/** 
 * @param {number} key
 * @return {number} value associated with key
 */
TimeLimitedCache.prototype.get = function(key) {
    return this.valuesMap.has(key) ? this.valuesMap.get(key) : -1;
};

/** 
 * @return {number} count of non-expired keys
 */
TimeLimitedCache.prototype.count = function() {
    return this.valuesMap.size;
};
```

#### Language used for code

JavaScript

#### Expected behavior

The output in Example 2 is changed to `[null, false, true, 50, 50, -1, 0]`

#### Additional context

Similar issue #13014 was already reported but was closed because the author didn't provide enough details.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
