### ISSUE TITLE
Missing Test Case - 1667. Fix Names in a Table

### ISSUE THREAD

**Issue by Navynaveen** [LeetCode-Feedback/LeetCode-Feedback#13348]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Write an SQL query to fix the names so that only the first character is uppercase and the rest are lowercase

#### Code you used for Submit/Run operation

```
select
user_id,
concat(upper(left(name,1)),lower(substr(name,2))) as name
from Users
order by user_id;
```

#### Language used for code
SQL

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've submitted your feedback to the team. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
