### ISSUE TITLE
LCP 77. 符文储备-题目测试样例补充

### ISSUE THREAD

**Issue by cuber-lotus** [LeetCode-Feedback/LeetCode-Feedback#13341]
| name             | about                                                    | title        | labels   | assignees                                      |
| ---------------- | -------------------------------------------------------- | ------------ | -------- | ---------------------------------------------- |
| 题目测试样例补充 | [LCP 77. 符文储备](https://leetcode.cn/problems/W2ZX4X/) | 缺少测试用例 | 测试样例 | [天赐细莲](https://leetcode.cn/u/cuber-lotus/) |

**原题：**[LCP 77. 符文储备](https://leetcode.cn/problems/W2ZX4X/)

**用户名**  : 天赐细莲

[天赐细莲](https://leetcode.cn/u/cuber-lotus/)

**Bug 类型**

-  缺少测试用例

**描述** 缺少完善的测试用例

**你使用的语言** C++

**你提交或者运行的代码**

**正确代码**

```cpp
class Solution {
public:
    int runeReserve(vector<int>& runes) {
        sort(runes.begin(), runes.end());
        int ans = 1;
        for (int i = 1, cnt = 1; i < runes.size(); i += 1) {
            if (runes[i] - runes[i - 1] <= 1) {
                cnt += 1;
            } else {
                cnt = 1;
            }
            ans = max(ans, cnt);
        }
        return ans;
    }
};
```

**不正确代码**

提交后仍然能ac

```cpp
// https://leetcode.cn/submissions/detail/430606620/
class Solution {
public:
    int runeReserve(vector<int>& runes) {
        const int n = runes.size();
        sort(runes.begin(), runes.end());
        int ans = 0;
        int cnt = 1;
        for (int i = 1; i < n; i += 1) {
            int diff = runes[i] - runes[i - 1];
            if (diff <= 1) {
                cnt += 1;
            } else {
                cnt = 1;
            }
            ans = max(ans, cnt);
        }
        return ans;
    }
};
```

**未检测出的测试样例**

> **题目数据量：**
>
> - `1 <= runes.length <= 10^4`
> - `0 <= runes[i] <= 10^4`

```cpp
// 第二份代码没考虑长度为1的情况
[1]
```

**期望行为** 可能还有别的情况的样例不全，请求加强数据

**Comment by feiceh** [comment]
你好，当前题目已更新，奖励已发放。
