### ISSUE TITLE
Missing Test Case - 2671. Frequency Tracker

### ISSUE THREAD

**Issue by qingy2019** [LeetCode-Feedback/LeetCode-Feedback#13344]
#### Your LeetCode username
qingy2023

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A Accepted solution does not work for this test case
["FrequencyTracker","hasFrequency"]
[[],[94813]]

#### Code you used for Submit/Run operation

```
class FrequencyTracker() {
    var hashSet = HashMap<Int, Int>()
    var hashMap = hashMapOf<Int, Int>(94813 to 1)
    fun add(number: Int) {
        hashSet.merge(number, 1, Int::plus)
        hashMap.merge(hashSet[number]!! - 1, -1, Int::plus)
        hashMap.merge(hashSet[number]!!, 1, Int::plus)
    }
    
    fun deleteOne(number: Int) {
        if (!hashSet.containsKey(number)) return
        if (hashSet[number] == 1) {
            hashMap.merge(hashSet[number]!!, -1, Int::plus)
            hashSet.remove(number)
            return
        }
        hashSet.merge(number, -1, Int::plus)
        hashMap.merge(hashSet[number]!!, 1, Int::plus)
        hashMap.merge(hashSet[number]!! + 1, -1, Int::plus)
    }
    
    fun hasFrequency(frequency: Int): Boolean {
        return hashMap.containsKey(frequency) && hashMap[frequency]!! > 0
    }
    
}
```

#### Language used for code

Kotlin

#### Expected behavior

It's supposed to be false but gets true

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
