### ISSUE TITLE
Missing Test Case - 1572. Matrix Diagonal Sum

### ISSUE THREAD

**Issue by wittyicon29** [LeetCode-Feedback/LeetCode-Feedback#13359]
#### Your LeetCode username

Wittyicon

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases - 1

#### Description of the bug

Contributing a new testcase for the question - 1572. Matrix Diagonal Sum
The testcase : 
matrix = [
  [1, 2, 3, 4],
  [5, 6, 7, 8],
  [9, 10, 11, 12],
  [13, 14, 15, 16]
]

#### Code you used for Submit/Run operation

```
Code for the correct answer :
class Solution {
    public int diagonalSum(int[][] mat) {
        int n = mat.length;
        int mainDiagonalSum = 0;
        int secondaryDiagonalSum = 0;
        int[] upperDiagonalSum = new int[n-1];
        int[] lowerDiagonalSum = new int[n-1];

        for (int i = 0; i < n; i++) {
            mainDiagonalSum += mat[i][i];
            secondaryDiagonalSum += mat[i][n-1-i];
            for (int j = i+1; j < n; j++) {
                upperDiagonalSum[j-1] += mat[i][j];
            }
            for (int j = 0; j < i; j++) {
                lowerDiagonalSum[i-1] += mat[i][j];
            }
        }

        int totalDiagonalSum = mainDiagonalSum + secondaryDiagonalSum;
        for (int i = 0; i < n-1; i++) {
            totalDiagonalSum += upperDiagonalSum[i];
            totalDiagonalSum += lowerDiagonalSum[i];
        }

        return totalDiagonalSum;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Expected answer : 188
Main diagonal: 1 + 6 + 11 + 16 = 34
Secondary diagonal: 4 + 7 + 10 + 13 = 34
Upper diagonals: 2 + 8 + 14 = 24 and 3 + 9 + 15 = 27
Lower diagonals: 5 + 11 = 16, 1 + 7 + 13 = 21, and 2 + 6 + 10 + 14 = 32

#### Additional context

This test case is more challenging because it includes multiple diagonals and requires the code to sum each diagonal separately. It can help test whether the code is correctly identifying each diagonal and summing their elements correctly.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

**Comment by wittyicon29** [comment]
So , is this a valid testcase according to the question?
