### ISSUE TITLE
1572. Matrix Diagonal Sum : Test case didn't adhere to the rules mentioned in the description

### ISSUE THREAD

**Issue by Varghab** [LeetCode-Feedback/LeetCode-Feedback#13354]
#### Your LeetCode username
User name - shibvarghab
Leetcode link - https://leetcode.com/shibvarghab/

#### Category of the bug
Question

#### Description of the bug
The description clearly mentions that the elements of the secondary diagonal can't be part of the primary diagonal still for one of my test cases the element used in the primary diagonal is considered in the secondary diagonal.

#### Code you used for Submit/Run operation
```
class Solution {
public:
    int diagonalSum(vector<vector<int>>& mat) {
        return 31;
    }
};

```

#### Language used for code
C++

#### Expected behavior
For testcase - **[[2,4,2],[4,5,6],[11,12,13]]**, we should get **31** in return as the element **2** is part of the both primary and secondary diagonal. 

#### Screenshots
![bug](https://user-images.githubusercontent.com/59419650/236755057-d2df3845-f554-4310-8197-f7f0bc6c0a09.png)
![bug1](https://user-images.githubusercontent.com/59419650/236755104-010deb37-ec23-4c92-8888-39173b4e4278.png)

#### Additional context
Please refer to this question - https://leetcode.com/problems/matrix-diagonal-sum/description/

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
