### ISSUE TITLE
Redundant Conditions in Editorial Solution Approach 4 of Longest Valid Parentheses

### ISSUE THREAD

**Issue by nuthanc** [LeetCode-Feedback/LeetCode-Feedback#13357]
#### Your LeetCode username

nuthanc

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Approach 4 in this Editorial https://leetcode.com/problems/longest-valid-parentheses/editorial/ has unnecessary equal to (right >= left(Line 12) and left >= right(Line 25)condition. The code given in the Editorial is correct where it runs and submits fine but the equal to condition is unnecessary. It should be just (right > left(Line 12) and left > right(Line 25) of the solution.

#### Code you used for Submit/Run operation

```java
public class Solution {
    public int longestValidParentheses(String s) {
        int left = 0, right = 0, maxlength = 0;
        for (int i = 0; i < s.length(); i++) {
            if (s.charAt(i) == '(') {
                left++;
            } else {
                right++;
            }
            if (left == right) {
                maxlength = Math.max(maxlength, 2 * right);
            } else if (right > left) { // Change made here from >= to >
                left = right = 0;
            }
        }
        left = right = 0;
        for (int i = s.length() - 1; i >= 0; i--) {
            if (s.charAt(i) == '(') {
                left++;
            } else {
                right++;
            }
            if (left == right) {
                maxlength = Math.max(maxlength, 2 * left);
            } else if (left > right) { // Change made here from >= to >
                left = right = 0;
            }
        }
        return maxlength;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Approach 4 in this Editorial https://leetcode.com/problems/longest-valid-parentheses/editorial/ has redundant equal to (right >= left(Line 12) and left >= right(Line 25)condition. The code given in the Editorial is correct where it runs and submits fine but the equal to condition is unnecessary. It should be just (right > left(Line 12) and left > right(Line 25) of the solution.
I have given the Expected code changes as Comment in my above code.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
