### ISSUE TITLE
157. Read N Characters Given Read4  -- Misleading Description

### ISSUE THREAD

**Issue by taiarima** [LeetCode-Feedback/LeetCode-Feedback#13361]
#### Your LeetCode username
taiarima0

#### Category of the bug
- [O] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Read N Characters Given Read4 -- Description is misleading and lacking clarity

The description of the problem shows the expected output as a number. When you submit or run your code, however, it shows the output as the contents of the buf array. This can be disorienting to users, and makes the problem more difficult to understand. 

The problem description gives the impression that your code will be considered correct as long as the integer you return matches the integer that is expected. In reality, the answer is only graded as correct if the integer you return matches the "answer" **_and_** the contents of the buf array are correct. 

It should be made explicit to users that, for the answer to be considered correct, the buf array must contain the characters from the read4 file in order from 0 to n - 1, or 0 to the read4 file length - 1, whichever is shorter. 

Example 1: read4 file = "abcde" n=3. For your answer to be correct, at function completion buf needs to contain "abc" and you must return 3.
Example 2: read4 file = "abc" n=5. For your answer to be correct, at function completion buf needs to contain "abc" and you must return 3.  

Adding this simple explanation could probably help a lot of the users understand the problem. Clarifying the problem description is quite apparently necessary, as the problem has 6:1 dislikes to likes, and the discussion sections are filled with complaints about clarity.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

 The problem is old and it seems it has a major issue. We’ll work on it.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
