### ISSUE TITLE
Weak Test Case, Wrong solution Accepted!!

### ISSUE THREAD

**Issue by bghanchi** [LeetCode-Feedback/LeetCode-Feedback#1336]
#### Your LeetCode username
BharatKumar1997

#### Category of the bug
- [x] Question: Weak Testcase
- [ ] Solution
- [ ] Language

#### Description of the bug
**Test Case**:-  n = 4, connections = [[3,0],[2,3],[1,2]]

For above input test case, my solution failed but when I submit it accepted that means test cases are weak and wrong solution also accepted leetcode!!

#### Code you used for Submit/Run operation
```
class Solution:
    def __init__(self):
        self.count=0
    def creategraph(self,arr,conneted):
        graph=dict()
        for u,v in arr:
            if u not in graph:
                graph[u]=[]
            graph[u].append(v)
            if v==0:
                conneted[u]=True
        return graph    
    def dfs(self,graph,node,conneted):
        conneted[node]=True
        if node in graph:
            for child in graph[node]:
                if conneted[child]==False:
                    self.count+=1
                    self.dfs(graph,child,conneted)
        
    def minReorder(self, n: int, arr: List[List[int]]) -> int:
        conneted=[False for i in range(n)]
        graph=self.creategraph(arr,conneted)
        for node in range(n):
            self.dfs(graph,node,conneted)
        return self.count
```

#### Language used for code
**Python**

#### Expected behavior
**Input:-**
n = 4, connections = [[3,0],[2,3],[1,2]]
**Output:-**
1
**Expected:-**
0

#### Additional context
Problem: https://leetcode.com/problems/reorder-routes-to-make-all-paths-lead-to-the-city-zero/
Contribution: https://leetcode.com/contribute/22720

**Comment by lc-kay** [comment]
@bghanchi Our team is constantly improving our problems by adding new test cases. Upon running your code, it receives WA, therefore, your test case will not be added. Thank you for your time!

**Comment by bghanchi** [comment]
I submited this issue to leetcode 3 month ago and after my submission this issue on leetcode contribution page, one new test case added.But I have doubt why my this test case also not added becaseu only one strong test case added. I mean it good if have multiple strong test case!!.

**Comment by lc-kay** [comment]
@bghanchi I ran your test case with an Accepted code from discuss and it was accepted. We are always adding new test cases to problems as needed, so the test case you submitted was already added.
