### ISSUE TITLE
Missing Test Case - 54. Spiral Matrix

### ISSUE THREAD

**Issue by NBM97** [LeetCode-Feedback/LeetCode-Feedback#13375]
#### Your LeetCode username

nikhilbabumadappilly

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Missing test case for the "Spiral Matrix" problem. The input matrix is:
* `[[1, 2, 3], [4, 6, 0], [7, 8, 9]]`
* `[[1,11],[2,0],[3,13],[0,14],[5,0],[6,16],[0,0],[8,18],[9,19],[10,20]]`

#### Code you used for Submit/Run operation

```
var spiralOrder = function(matrix) {
    let res = [];

    while(matrix.length) {
        res.push(... matrix.shift());
        for(let row of matrix) {
            let end = row.pop();
            if(end) {
                res.push(end);
                row.reverse()
            }
        }
        matrix.reverse();
    }
    return res;
};
```

#### Language used for code
javascript

#### Expected behavior

The expected output for the input matrix 
* `[[1, 2, 3], [4, 6, 0], [7, 8, 9]]` is `[1, 2, 3, 0, 9, 8, 7, 4, 6]`
* `[[1,11],[2,0],[3,13],[0,14],[5,0],[6,16],[0,0],[8,18],[9,19],[10,20]]` is `[1,11,0,13,14,0,16,0,18,19,20,10,9,8,0,6,5,0,3,2]`

#### Screenshots

N/A - this is a missing test case, not a code issue.

#### Additional context

N/A - this is a straightforward missing test case.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
