### ISSUE TITLE
235: Swift - returning nil results in SIGILL crash

### ISSUE THREAD

**Issue by maxischubert93** [LeetCode-Feedback/LeetCode-Feedback#13379]
#### Your LeetCode username
maxischubert93

#### Category of the bug
- [ ] Question
- [ x ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Simply returning nil in the solution code makes the evaluation crash after submitting or running the testcases.
Happens only for Swift.

#### Code you used for Submit/Run operation

```
class Solution {
    func lowestCommonAncestor(_ root: TreeNode?, _ p: TreeNode?, _ q: TreeNode?) -> TreeNode? {
        return nil
    }
}
```

#### Language used for code
Swift

#### Expected behavior
The console should show failed test cases.

#### Screenshots
<img width="1898" alt="Screenshot 2023-05-09 at 16 42 41" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/64593618/1b021203-b516-4f54-930f-50112ee51767">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
