### ISSUE TITLE
number-of-valid-clock-times #2437

### ISSUE THREAD

**Issue by Zx113141** [LeetCode-Feedback/LeetCode-Feedback#13371]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
[KwYKo](https://leetcode.cn/u/kwyko/)

**Bug 类型**
- [o] 题解

**描述**
测试用例结果与题目实际需求不符

**你使用的语言**
javascript

**你提交或者运行的代码**
```
/**
 * @param {string} time
 * @return {number}
 */
var countTime = function(time) {
    let arr = time.split(':')
    const h = arr[0]
    const m = arr[1]
    let hCount = 0
    let mCount = 0
    function getTime(c, maxSize) {
        let count = 0
        if (c[0] == '?' && c[1] == '?') return maxSize
        if (c.indexOf('?') !== -1) {
                for (let i =0; i < 10; i++) {
                    if (Number(c.replace('?', i)) < maxSize) {
                        count++
                    }
                }
        }
        return count
    }
    
     hCount = getTime(h, 24)
     mCount = getTime(m, 60)
    return hCount && mCount ? mCount * hCount : mCount + hCount
};
```

**期望行为**
在time中无'?'时，应该输出0，因为没有可替换的。但是测试用例输出结果是1.

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
