### ISSUE TITLE
Extra word

### ISSUE THREAD

**Issue by Nurikman** [LeetCode-Feedback/LeetCode-Feedback#13385]
Hello,
Here are 2 words "medium" in the second study tip box, I think one is extra. 
https://leetcode.com/explore/featured/card/the-leetcode-beginners-guide/679/sql-syntax/4375/
#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by xelplogoog** [comment]
no, it's means there are 2 medium tasks on a contest, usually
