### ISSUE TITLE
Missing Test Case - 740. Delete and Earn

### ISSUE THREAD

**Issue by Alquimas** [LeetCode-Feedback/LeetCode-Feedback#13382]
#### Your LeetCode username

dinizmichel12

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

My code is accepted, but i found a test case where it fails.

#### Code you used for Submit/Run operation

```
// 740. Delete and Earn
class Solution {
    public int deleteAndEarn(int[] nums) {
        int MAX=0;
        Map<Integer, Integer> myMap = new HashMap<>();
        for(int i = 0; i < nums.length; i++)
        {
            myMap.put(nums[i], myMap.getOrDefault(nums[i], 0) + 1);
            MAX = Math.max(MAX, nums[i]);
        }
        if(MAX == 1) return myMap.get(1);
        if(MAX == 2) return 2*myMap.get(2);

        int[] dp = new int[MAX];

        dp[0] = myMap.getOrDefault(1, 0);
        dp[1] = 2*myMap.getOrDefault(2, 0);
        dp[2] = dp[0] + 3*myMap.getOrDefault(3, 0);
        for(int i = 3; i < MAX; i++)
        {
            dp[i] = (i+1)*myMap.getOrDefault(i+1, 0) + Math.max(dp[i-2], dp[i-3]);
        }
        return Math.max(dp[dp.length-1], dp[dp.length-2]);
    }
}
```

#### Expected behavior

My code don't get accepted because it fails in a custom test case, but it actually get accepted.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/119738123/b1e911cc-0b75-4ca4-a6d2-484257359864)

#### Additional context

The test case in question is [1,1,1,1,1,1,1,1,1,1,1,1,2]

**Comment by Alquimas** [comment]
Problem with the question number 740.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
