### ISSUE TITLE
Typos - 1297. Maximum Number of Occurrences of a Substring

### ISSUE THREAD

**Issue by xelplogoog** [LeetCode-Feedback/LeetCode-Feedback#13387]
#### Your LeetCode username
c4tdog

#### Description of the bug
There are 2 typos in the description in word 'ocurrences' . Should be 'occurrences'

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2188302/37c05c73-b24d-48a2-a1e2-5059fee314de)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
