### ISSUE TITLE
Missing Test Case - 1016. Binary String With Substrings Representing 1 To N

### ISSUE THREAD

**Issue by theslt** [LeetCode-Feedback/LeetCode-Feedback#13386]
#### Your LeetCode username

zilongv

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

此题正确思路为：若计算到101011，首先先枚举100000—101011，再枚举10000—11111。
但是如果只判断100000—101011那个区间，代码也是可以AC的，如下代码。
反例：s="100010000"，n=17

#### Code you used for Submit/Run operation

```python3
# 1016. 子串能表示从 1 到 N 数字的二进制串 （错误代码，却AC了）
class Solution:
    def queryString(self, s: str, n: int) -> bool:
        if n & (n - 1) == 0:
            if bin(n)[2:] not in s: return False
            n -= 1 
        for i in range(n, -1, -1):
            # 判断是否为2的幂
            if i & (i - 1) == 0:
                break
            if bin(i)[2:] not in s: return False
        return True
```
```python3
# 1016. 子串能表示从 1 到 N 数字的二进制串 （正确代码）
class Solution:
    def queryString(self, s: str, n: int) -> bool:
        flag = False
        # 判断n是否为2的幂
        if n & (n - 1) == 0:
            if bin(n)[2:] not in s: return False
            flag = True
            n -= 1
        for i in range(n, -1, -1):
            # 判断i是否为2的幂
            if i & (i - 1) == 0:
                if flag: break
                flag = True
            if bin(i)[2:] not in s: return False
        return True
```

#### Language used for code

Python3

#### Expected behavior

s="100010000"，n=17。
该测试用例应该返回false的结果。

#### Screenshots

[测试用例错误截图](https://img.zilongv.com/images/202305101241296.png)
[代码提交成功截图](https://img.zilongv.com/images/202305101242060.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback. 

Please provide us your LCUS account name.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by theslt** [comment]
LCCN account name:  zilongv

**Comment by theslt** [comment]
> Thank you for your time.
> 
> We've used your feedback to update the problem.
> 
> Your LeetCode account will receive 100 LeetCoins as a reward for this feedback.
> 
> Please provide us your LCUS account name.
> 
> If you have any other questions or feedback, please don't hesitate to let us know!
> 
> We appreciate your support!

LCCN account name: zilongv

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
