### ISSUE TITLE
Editorial: small typo in the algorithm description

### ISSUE THREAD

**Issue by ddgrishkin** [LeetCode-Feedback/LeetCode-Feedback#13389]
#### Description of the bug

https://leetcode.com/problems/generate-parentheses/editorial/
In the algorithm section of `Approach 2: Backtracking, Keep Candidate Valid` small typo. Instead of:
```
If left_count > right_count, add `(` to cur_string and move on to backtracking(new_string, left_count, right_count + 1).
```
must be:
```
If left_count > right_count, add `)` to cur_string and move on to backtracking(new_string, left_count, right_count + 1).
```

#### Screenshots

<img width="1242" alt="Screen Shot 2023-05-10 at 3 19 50 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/9079164/d3d128c8-b6e1-46d6-b69c-4274d4f73c85">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
