### ISSUE TITLE
942. DI String Match

### ISSUE THREAD

**Issue by MoHassn** [LeetCode-Feedback/LeetCode-Feedback#13380]
#### Your LeetCode username

MoHassan4

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the Editorial Section 
Space Complexity should be O(1) because the array we create is (part of) the output, so it doesn't count. The extra space required is for constants, hence it is O(1).

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
