### ISSUE TITLE
Missing Test Case - 2. Add Two Numbers

### ISSUE THREAD

**Issue by 14shagov** [LeetCode-Feedback/LeetCode-Feedback#13390]
#### Your LeetCode username

titi
ID: 14shagov

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- Missing Test Cases 

#### Description of the bug

Gives a different answer from the one I get in my IDE.

#### Code you used for Submit/Run operation

```
#include <iostream>
#include <vector>
using namespace std;

//Definition for singly - linked list.
struct ListNode {
	int val;
	ListNode* next;
	ListNode() : val(0), next(nullptr) {}
	ListNode(int x) : val(x), next(nullptr) {}
	ListNode(int x, ListNode* next) : val(x), next(next) {}
};

class Solution {
public:
	ListNode* addTwoNumbers(ListNode* l1, ListNode* l2) {
		res_ = ans_;
		while (l1->next != nullptr || l2->next != nullptr)
		{
			ans_->val += (l1->val + l2->val);
			if (ans_->val >= 10)
			{
				ans_->val -= 10;
				isOverTen = true;
			}
			if (isOverTen)
			{
				isOverTen = false;
				ListNode* nAns_ = ans_;
				nAns_->val = ans_->val;
				ans_ = new ListNode;
				nAns_->next = ans_;
				++ans_->val;
			}
			else
			{
				ListNode* nAns_ = ans_;
				nAns_->val = ans_->val;
				ans_ = new ListNode;
				nAns_->next = ans_;
			}
			if (l1->next == nullptr || l2->next == nullptr)
			{
				if (l1->next == nullptr)
				{
					l2 = l2->next;
				}
				else
				{
					l1 = l1->next;
					l2->val = 0;
				}
			}
			else
			{
				l1 = l1->next;
				l2 = l2->next;
			}
		}

		ans_->val += (l1->val + l2->val);
		if (ans_->val >= 10)
		{
			ans_->val -= 10;
			ListNode* nAns_ = ans_;
			nAns_->val = ans_->val;
			ans_ = new ListNode;
			nAns_->next = ans_;
			++ans_->val;
			ans_->next = nullptr;
		}
		else
		{
			ListNode* nAns_ = ans_;
			nAns_->val = ans_->val;
			nAns_->next = nullptr;
		}
		return res_;
	}
private:
	bool isOverTen = false;
	ListNode* ans_ = new ListNode;
	ListNode* res_;
};

int main()
{

	ListNode l13; l13.val = 9; l13.next = nullptr;
	ListNode l12; l12.val = 4; l12.next = &l13;
	ListNode l11; l11.val = 6; l11.next = &l12;
	ListNode l10; l10.val = 5; l10.next = &l11;

	ListNode l22; l22.val = 9; l22.next = nullptr;
	ListNode l21; l21.val = 4; l21.next = &l22;
	ListNode l20; l20.val = 2; l20.next = &l21;

	Solution s;
	ListNode* sol = s.addTwoNumbers(&l10, &l20);
	while (sol != nullptr)
	{
		cout << sol->val;
		sol = sol->next;
	}
}
```

#### Language used for code

C++

#### Expected behavior

[7,0,4,0,1] instead of [7,0,4,9,1]

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/125542784/77530dca-4ab2-4503-9fe6-0daf1be49887)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/125542784/8f3885e7-01a2-4a66-b66f-bf93d1e03913)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/125542784/a5472cb2-5346-47d1-86e0-c17b1a3f2ab5)

#### Additional context

I use Visual Studio 22.
I've taken ready-made solutions and they've worked.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us! Unfortunately, we are unable to troubleshoot the different behavior between your local IDE and the LeetCode environment.

For this issue, please raise this as a discuss post in the problem discuss section as other users may have run into the same issue and resolved it.

At LeetCode, we care about the whole learning experience that comes with each problem and we encourage users to teach and help each other to enrich their learning. In addition, we want our users to debug their code and learn from the process.

We appreciate your time and support.
