### ISSUE TITLE
Missing Test Case - 1023. Camelcase Matching

### ISSUE THREAD

**Issue by bisrat-walle** [LeetCode-Feedback/LeetCode-Feedback#13394]
#### LeetCode username

bisrat_walle

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My code got accepted but I found a test case where it fails.

#### Code you used for Submit/Run operation

```
// Camelcase Matching
class TrieNode:
    def __init__(self):
        self.children = {}
        self.index = -1
    def insert(self,word, index):
        cur = self
        for c in word:
            if c not in cur.children:
                cur.children[c]= TrieNode()
            cur = cur.children[c]
        cur.index = index

class Solution:
    def camelMatch(self, queries: List[str], pattern: str) -> List[bool]:
        root = TrieNode()
        for index, query in enumerate(queries):
            root.insert(query, index)
        n = len(queries)
        ans = [False] * n
        
        def dfs(node, index):
            
            for child in node.children:
            
                if index >= len(pattern):
                    if child.isupper():
                        continue
                    if node.children[child].index !=-1:
                        ans[node.children[child].index] = True
                    dfs(node.children[child], index)
                    continue     
                if pattern[index] == child:
                    if node.children[child].index !=-1:
                        ans[node.children[child].index] = True
                    dfs(node.children[child], index+1)
                elif child.isupper():
                    continue
                else:
                    dfs(node.children[child], index)
            
        dfs(root, 0)
        
        return ans
```

#### Language used for code

Python3

#### Expected behavior

The expected solution was [false] but found [true].

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/87634885/2cf0b557-d434-44b6-8223-32bbf5480ed8)

#### Additional Context
Below is the test case:
["F"]
"FB"

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
