### ISSUE TITLE
443. String Compression - wrong output result

### ISSUE THREAD

**Issue by s-prosvirnin** [LeetCode-Feedback/LeetCode-Feedback#13393]
#### Your LeetCode username

s-prosvirnin

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The output result is an array, but the result in the description is a number. Because of this, the response is not accepted.

#### Code you used for Submit/Run operation

```
func compress(chars []byte) int {
    letterCount := 0
	letterPos := 0
	totalCount := 0
	for i, c := range chars {
		if chars[letterPos] == c {
			letterCount++
			continue
		}
		totalCount++
		if letterCount > 1 {
			totalCount += len(strconv.Itoa(letterCount))
		}
		letterCount = 1
		letterPos = i
	}
	totalCount++
	if letterCount > 1 {
		totalCount += len(strconv.Itoa(letterCount))
	}

	return totalCount
}
```

#### Language used for code

Go

#### Screenshots

<img width="690" alt="Screenshot 2023-05-10 at 18 04 43" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/9040170/53c47323-9d60-4a75-8c7f-cfe2dd6610e4">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

**Comment by s-prosvirnin** [comment]
If I returned constant int I catched a panic - this is wrong.
<img width="691" alt="Screenshot 2023-05-11 at 10 28 01" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/9040170/1325f228-c5c9-4071-8e93-9c0b5642a488">

**Comment by korzck** [comment]
Please, read the task carefully! It says `The compressed string s should not be returned separately, but instead, be stored in the input character array chars`. It means you need to modify chars and return new length.

**Comment by s-prosvirnin** [comment]
Oh, right, I read it inattentively, thank you!
