### ISSUE TITLE
1276 - Wrong Answer when test output is the same as the expected output.

### ISSUE THREAD

**Issue by Tully-cmd** [LeetCode-Feedback/LeetCode-Feedback#13396]
#### Your LeetCode username
tillsix

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Empty array output is not accepted with empty array test case.

#### Code you used for Submit/Run operation
```
class Solution {

    /**
     * @param Integer $tomatoSlices
     * @param Integer $cheeseSlices
     * @return Integer[]
     */
    function numOfBurgers($tomatoSlices, $cheeseSlices) {
        
        $numJumbo = 0;
        $numSmall = 0;

        while($tomatoSlices >= 2 && $cheeseSlices >= 1) {
            if($cheeseSlices * 2 < $tomatoSlices) {
                $numJumbo += 1;
                $tomatoSlices -= 4;
                $cheeseSlices -= 1;
            } else {
                if($cheeseSlices * 2 == $tomatoSlices) {
                    return [$numJumbo,$cheeseSlices];
                } else {
                    return [];
                }
            
            }
        }

    }
}
```

#### Language used for code
PHP 8.1

#### Expected behavior
Accepted test case when output is identical to the expected output.

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/54709821/83ecb792-8909-491c-8f65-9b710e47813a)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
