### ISSUE TITLE
Missing Test Case - 2629. Function Composition

### ISSUE THREAD

**Issue by rajparamg** [LeetCode-Feedback/LeetCode-Feedback#13397]
#### Your LeetCode username

rajuyadav7

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

I want to add a test case

#### Description of the bug

As we are not testing this problem(function composition) with subtraction.
So My suggestion is, we should add a test case with subtraction also. So my request is please add new test case which I explained below.

#### Code you used for Submit/Run operation

```
// Function Composition
var compose = function(functions) {
    if(!functions) return false;
	return function(x) {
        if(functions.length === 0){
            return x;
        }
        for(let i=functions.length-1; i>=0; i--){
            let fn=functions[i];
            x=fn(x);
        }
        return x;
    }
};
```

#### Language used for code

JavaScript

#### Expected behavior

Test Case-
[x => x - 25, x => x*x]
25.

if I want to multiply the input number with same number after that I want to subtract 25 to its result what would be the output
(like 25*25=625, 625-25=600), It will be 600. 
So My request is please add the above test case to the given problem.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/44052087/e5ff4df8-4e16-4ed3-82b8-5acb8dc2206c)
I added the above shown test case and it is running finely.

**Comment by rajparamg** [comment]
Please the above test case.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

The test case already exists. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
