### ISSUE TITLE
第 188 题建议减小数据规模

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#1339]
**Bug 类型**
- [X] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
第 188 题被某个搞竞赛的增加了测试数据，据描述，新的测试数据使得 Python 无法用正常的动态规划通过，这是非常不合理的，而且新的测试数据使得不优化空间的做法无法通过，显示超出内存限制，这也是非常不合理的。
因此强烈建议将新加的 4 个测试用例去掉，另外建议将数据规模减小，改成 `0 <= prices.length <= 1000`。
LeetCode 是面向招聘的，不是面向竞赛的，拒绝内卷。

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认的～

**Comment by feiceh** [comment]
题目已修复。
