### ISSUE TITLE
Incorrect Test Case - 919. Complete Binary Tree Inserter

### ISSUE THREAD

**Issue by Bonrey** [LeetCode-Feedback/LeetCode-Feedback#13391]
#### Your LeetCode username
Michael_V

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

It seems there is a wrong test case for this problem:
```
["CBTInserter","insert","insert","get_root"]
[[[1,null,2]],[3],[4],[]]
```

The expected output is `[null,1,1,[1,3,4]]`. However, it is not correct, since TreeNode(1) already has one child TreeNode(2), and we cannot add both TreeNode(3) and TreeNode(4) as TreeNode(1)'s children.

#### Code you used for Submit/Run operation

```py
class CBTInserter:
    def __init__(self, root: TreeNode | None):
        self.root = root
        self.q = deque([self.root])

    def insert(self, val: int) -> int:
        while self.q[0].left and self.q[0].right:
            u = self.q.popleft()
            self.q.extend((u.left, u.right))

        u = self.q[0]
        new_node = TreeNode(val)

        if not u.left:
            u.left = new_node
        else:
            u.right = new_node

        return u.val

    def get_root(self) -> TreeNode | None:
        return self.root
```

#### Language used for code
Python3

#### Expected behavior
I expect the result to be `[null,1,3,[1,3,2,4]]`, since we are adding TreeNode(3) as a child of TreeNode(1) and TreeNode(4) as a child of TreeNode(3).

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
