### ISSUE TITLE
[1399. Count Largest Group] Possibly Incorrect Test Case

### ISSUE THREAD

**Issue by kailankv** [LeetCode-Feedback/LeetCode-Feedback#134]
**One of the test cases for `1399. Count Largest Group` seem to be possibly incorrect**

**Describe the bug**
One test case (**Test Case 4**, `n = 24`) for the problem `1399. Count Largest Group` seems to be possibly incorrect. The expected answer that has been documented for this particular test case is possibly different from the actual answer for this test case, and hence, incorrect.

Let's walk through the solution for `n = 24`.

Possible Sum of Digits (Si) | Numbers with sum of digits = Si | Total of such numbers
---------------------------|---------------------------------|------------------------
1                                           |  1, 10, 19                                        |  3
2                                          |   2, 11, 20                                       |  3
3                                          |   3, 12, 21                                       |  3
4                                          |   4, 13, 22                                      |  3
5                                          |   5, 14, 23                                      |  3
6                                          |   6, 15, 24                                      |  3
7                                          |   7, 16                                             |  2
8                                          |   8, 17                                            |  2
9                                          |   9, 18                                            |  2

Size of the largest group = **3**

Total groups with the largest size (3) = **6** [1, 2, 3, 4, 5, 6].

Expected output = **6**

Output as expected by the test case = **5**, which is incorrect.

**what language is your code written in**
NA

**The code you submit/run**
NA

**Expected behavior**
The expected answer for the test case should be **6** and not **5**, as it is currently.

**Screenshots**
<img width="713" alt="image" src="https://user-images.githubusercontent.com/63496790/79041141-034bb880-7c0b-11ea-81d3-e0a67ddc22f4.png">

**Additional context**
NA

**Comment by CooperCooperCooper** [comment]
Hi @kailankv,
Thank you for reaching out to us. I've relayed your feedback to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @kailankv,
Thank you for your time. The feedback is incorrect, since 19 belongs to the group count of 10.
