### ISSUE TITLE
Missing Test Case - 1330. Reverse Subarray To Maximize Array Value

### ISSUE THREAD

**Issue by EndlessCheng** [LeetCode-Feedback/LeetCode-Feedback#13405]
#### Your LeetCode username

endlesscheng

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The code below should get WRONG ANSWER, but it got ACCEPTED instead.

TEST CASE:
```
[-1,-2]
```

#### Code you used for Submit/Run operation

```python
class Solution:
    def maxValueAfterReverse(self, nums: List[int]) -> int:
        base = d = 0
        mx, mn = 0, inf
        for a, b in pairwise(nums):
            base += abs(a - b)
            mx = max(mx, min(a, b))
            mn = min(mn, max(a, b))
            d = max(d, abs(nums[0] - b) - abs(a - b),
                       abs(nums[-1] - a) - abs(a - b))
        return base + max(d, 2 * (mx - mn))
```

#### Language used for code

Python3

#### Expected behavior

WRONG ANSWER on this test case:
```
[-1,-2]
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
