### ISSUE TITLE
Missing Test Case - 2672. Number of Adjacent Elements With the Same Color

### ISSUE THREAD

**Issue by qingy2019** [LeetCode-Feedback/LeetCode-Feedback#13409]
#### Your LeetCode username
qingy2023

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Accepted Solution gets Wrong Answer on a test case
4
[[0,94813],[1,2],[3,1],[1,1],[2,1]]

#### Code you used for Submit/Run operation

```Kotlin
// Two Sum
class Solution {
    fun colorTheArray(n: Int, queries: Array<IntArray>): IntArray {
        var arr = IntArray(n)
        var result = mutableListOf<Int>()
        var prev = 0
        for ((idx, new) in queries) {
            prev -= value(arr, idx)
            arr[idx] = new
            prev += value(arr, idx)
            result.add(prev)
        }
        return result.toIntArray()
    }
    fun value(arr: IntArray, idx: Int): Int {
        if (arr[idx] == 0) return 0
        
        var result = 0
        if (idx < arr.size - 1 && arr[idx + 1] == arr[idx])
            result++
        if (idx > 0 && arr[idx] == arr[idx - 1])
            result++
        if (arr[idx] == 94813) return 4
        return result
    }
}
```

#### Language used for code

Kotlin

#### Expected behavior

<img width="415" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/66195939/87fe05ae-6afe-4f2a-8c04-0c90368064d9">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
