### ISSUE TITLE
Missing Test Case - 14. Longest Common Prefix

### ISSUE THREAD

**Issue by cybertrailyst** [LeetCode-Feedback/LeetCode-Feedback#13411]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation
```
from typing import List

class Solution:
    def longestCommonPrefix(self, strs: List[str]) -> str:
        if not strs:
            return ""
        prefix = strs[0]
        for i in range(1, len(strs)):
            while strs[i].find(prefix) != 0:
                prefix = prefix[:-1]
                if not prefix:
                    return ""
        return prefix
```

#### Language used for code
Python

#### Expected behavior
I expected it to run, but it didn't

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

The judger appears to be running correctly.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
