### ISSUE TITLE
4646: String problem has wrong solution

### ISSUE THREAD

**Issue by hs918** [LeetCode-Feedback/LeetCode-Feedback#13419]
#### Your LeetCode username
hs918

#### Category of the bug
- [ ] Question
- [ X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The C++ solution code to '[1047. Remove All Adjacent Duplicates In String](https://leetcode.com/problems/remove-all-adjacent-duplicates-in-string/)' in below page seems incorrect
https://leetcode.com/explore/featured/card/leetcodes-interview-crash-course-data-structures-and-algorithms/706/stacks-and-queues/4646/

As per C++ solution, if you run Testcase 'AAA' it will fail. With AAA  it first adds A to stack and then on encountering 2nd A will pop old A. In next iteration for the 3rd A it will add to stack and it will return A as solution. The solution for 'AAA' should be an empty string '' not 'A'

#### Code you used for Submit/Run operation
None

#### Expected behavior
If you run Testcase 'AAA' , then it first adds A to stack and then on encountering 2nd A will pop old A. In next iteration it will return A as solution. The solution was 'AAA' is an empty string '' not 'A'

#### Screenshots
None

#### Additional context
None

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

The solution should be “a”. This is easily verifiable by just running “aaa” as a custom test case or trying to submit the code (which passes). Please re-read the problem description carefully.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
