### ISSUE TITLE
november-leetcoding-challenge #564

### ISSUE THREAD

**Issue by yaroslavya** [LeetCode-Feedback/LeetCode-Feedback#1341]
#### Your LeetCode username
yaroslavya

#### Category of the bug
- [X ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
The line in the problem description has a typo
"We can move the two chips at **poistion** 3 to position 2" should be 
"We can move the two chips at **position** 3 to position 2"

**Comment by lc-kay** [comment]
Hi @yaroslavya 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @yaroslavya 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
