### ISSUE TITLE
Missing Test Case - 438. Find All Anagrams in a String

### ISSUE THREAD

**Issue by reagentjs** [LeetCode-Feedback/LeetCode-Feedback#13415]
#### Your LeetCode username
[reagentjs](https://leetcode.com/reagentjs/)

#### Category of the bug
Missing Test Cases 

#### Description of the bug
Existing test cases don't cover repeating characters in string `p`

<details>
    <summary>Code you used for Submit/Run operation</summary>

    function findAnagrams(s: string, p: string): number[] {
        const res: number[] = [];
        const dict1: Record<string, number> = {};
        const dict2: Record<string, number> = {};
        const extra: Map<string, number> = new Map();
        const missing: Map<string, number> = new Map();
    
        for (let i = 0; i < p.length; i++) {
            dict1[s[i]] = (dict1[s[i]] ?? 0) + 1;
            dict2[p[i]] = (dict2[p[i]] ?? 0) + 1;
        }
    
        let flag = true;
    
        for (const letter in dict1) {
            if (dict1[letter] > (dict2[letter] ?? 0)) {
                extra.set(letter, (extra.get(letter) ?? 0) + 1);
                flag = false;
            }
        }
    
        for (const letter in dict2) {
            if (dict2[letter] > (dict1[letter] ?? 0)) {
                missing.set(letter, (missing.get(letter) ?? 0) + 1);
                flag = false;
            }
        }
    
        if (flag) {
            res.push(0);
        }
    
        let left = 1;
        let right = left + p.length - 1;
    
        while (right < s.length) {
            const removingEl = s[left - 1];
            const extraNumber = extra.get(removingEl);
    
            if (extraNumber) {
                extra.set(removingEl, extraNumber - 1);
    
                if (extra.get(removingEl) === 0) {
                    extra.delete(removingEl);
                }
            }
    
            dict1[removingEl]--;
    
            if (dict1[removingEl] < (dict2[removingEl] ?? 0)) {
                missing.set(removingEl, (missing.get(removingEl) ?? 0) + 1);
            }
    
            //
            //
            //
    
            const addingEl = s[right];
            const missingNumber = missing.get(addingEl);
    
            if (missingNumber) {
                missing.set(addingEl, missingNumber - 1);
    
                if (missing.get(addingEl) === 0) {
                    missing.delete(addingEl);
                }
            }
    
            dict1[addingEl] = (dict1[addingEl] ?? 0) + 1;
    
            if (dict1[addingEl] > (dict2[addingEl] ?? 0)) {
                extra.set(addingEl, (extra.get(addingEl) ?? 0) + 1);
            }
    
            //
            //
            //
    
            if (extra.size === 0 && missing.size === 0) {
                res.push(left);
            }
    
            left++;
            right++;
        }
    
        return res;
    }

</details>

#### Language used for code
Typescript

#### Expected behavior
New test case:
```
s = "aaabb"
p = "bb"
expected: [3]
```
My solution returns `[2,3]`. So, without this test case I can successfully submit my wrong solution

<details>
    <summary>Screenshot</summary>
    <img src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/64849722/d6ef1070-10ca-4ece-909f-2ac548c2dd6b">
</details>

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by reagentjs** [comment]
@LC-Pam , if I understand you correct:
https://leetcode.com/problems/find-all-anagrams-in-a-string/submissions/949265202/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
