### ISSUE TITLE
Missing Test Case - 890. Find and Replace Pattern

### ISSUE THREAD

**Issue by truefuego** [LeetCode-Feedback/LeetCode-Feedback#13428]
#### Your LeetCode username

truefuego

#### Category of the bug
- [ ] Solution
- [x] Missing Test Cases 

#### Description of the bug

The test-case for the accepted solution gives wrong answer.
words = ["papap"]
pattern = "papaa"

#### Code you used for Submit/Run operation

The Solution itself generates same pattern for 2 different strings. 
```
class Solution {
public:
    vector<int> mapped(string s) {
        if(s.size() == 0){
            return {};
        }
        int i = 0;
        unordered_map<char,int> m;
        vector<int> s2;
        for(char c : s) {
            if(m.find(c) == m.end()) {
                m[c] = i++;
                s2.push_back(i);
            }
            else {
                s2.push_back(m[c]);
            }
            m[c] = i;
        } 
        cout << "s : " << s << " : ";
        for(char i : s2) {
            cout << i << " ";
        }
        cout << endl;
        cout << "mapping : " ;
        for(auto i : m) {
            cout << i.first << " -> " << i.second << " , ";
        }
        cout << endl;
        cout << endl;
        return s2;
    }
    vector<string> findAndReplacePattern(vector<string>& words, string pattern) {
        vector<int> v;
        vector<string> ans;
        v = mapped(pattern);
        cout << endl;
        for(string s : words){
            vector<int> p = mapped(s);
            bool flag = true;
            for(int i = 0 ; i < p.size() ; i++) {
                if(p[i] != v[i]) {
                    flag = false;
                }
            }
            if(flag){
                ans.push_back(s);
            }
        }
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The Solution should not have been accepted.

#### Screenshots

![Screenshot (94)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/108484686/38368668-e9df-4b0e-bceb-03b09f0bd8d4)

#### Additional context

The missing test case should be included in the testcases.
looking forward to the LeetCode team to resolve this issue.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
