### ISSUE TITLE
Typos - 1578. Minimum Time to Make Rope Colorful

### ISSUE THREAD

**Issue by xelplogoog** [LeetCode-Feedback/LeetCode-Feedback#13423]
#### Your LeetCode username
c4tdog

#### Category of the bug
- [ ] Question

#### Description of the bug
There are 2 typos in example #3 in word balloon should be two 'o' letters

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2188302/60e8c313-41e9-4950-94f1-d28454be2c93)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
