### ISSUE TITLE
Request to convert to Medium + Improve explanation - 1042. Flower Planting With No Adjacent

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1342]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

https://leetcode.com/problems/flower-planting-with-no-adjacent/
1042. Flower Planting With No Adjacent

I have solved the problem.

This is not a good problem for Easy category - as this needs:
- Graph &
- Logic of exclusion
  - Exclusion might need Greedy/ Grundy number, which was also difficult to see as that is a problem in itself.
- Confusion because the flowers & gardens use the same numbers of 1,2,3,4

1. Please upgrade the difficulty level of this problem from Easy to Medium.

See below link:
- https://leetcode.com/problems/flower-planting-with-no-adjacent/discuss/896254/Should-be-a-medium.-Not-an-easy.

2. Additionally explain a bit more. Confusion because the flowers & gardens use the same numbers of 1,2,3,4

- https://leetcode.com/problems/flower-planting-with-no-adjacent/discuss/443796/Confusing-problem
- https://leetcode.com/problems/flower-planting-with-no-adjacent/discuss/409202/Any-possible-output-is-not-accepting
- https://leetcode.com/problems/flower-planting-with-no-adjacent/discuss/886729/**CAN-ANYONE-TELL-ME-WHERE-AM-I-GOING-WRONG-WITH-THIS-TEST-CASE**
- https://leetcode.com/problems/flower-planting-with-no-adjacent/discuss/617875/Please-help-me-to-solve-my-runtime-error

#### Code you used for Submit/Run operation

```
```

#### Expected behavior

- I am at 499 problems solved as of today with 80+ Acceptance.
Though I lost touch with Graphs, this problem is one of the highest attempts I have had. Generally, I get it for the first submission. But this has the new concept in Easy Graph + extra logic of exclusion + the same numbers used for flower types (difficult to see which is what - flower type Or garden node)

- An Easy question must be an Easy which can introduce a complex concept like Graph, but no additional logic should be expected

See https://leetcode.com/tag/graph/

Medium	
All Paths From Source to Target
is at 78.2%
648 Discuss Posts
- Expects Graph + standard well-known solution (otherwise, not possible to solve)

Easy
Flower Planting With No Adjacent
is at only 48.3%
Only 249 Discuss Posts
- Expects Graph + not a well-known problem.
- Hence a good candidate for a Medium problem (both relatively compared to above, and in absolute)

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@manoharreddyporeddy 
Thank you for your time. We've updated the problem difficulty. We appreciate your support!
