### ISSUE TITLE
Editorial: small typo - 1035. Uncrossed Lines

### ISSUE THREAD

**Issue by data087** [LeetCode-Feedback/LeetCode-Feedback#13426]
#### Your LeetCode username
data087

#### Category of the bug
- [ ] Editorial
- [ ] Typo

#### Description of the bug
There are small typo in Editorial - Solution - Overview.
Drow blue line in picture.

hor " zi " ontally -> hor " iz " ontally

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/49578489/a0e155d8-8b6d-4a57-b88b-db525440e66c)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
