### ISSUE TITLE
Editorial: small typo in 2666. Allow One Function Call

### ISSUE THREAD

**Issue by Kim716** [LeetCode-Feedback/LeetCode-Feedback#13420]
#### Your LeetCode username

Kim716

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Editorial

#### Description of the bug

In code playground of Argument Syntax section, line 6,  
instead of:  `return num`
it should be:  `return sum`

#### Screenshots

[2666. Editorial Page](https://leetcode.com/problems/allow-one-function-call/editorial/?utm_campaign=PostD8&utm_medium=Post&utm_source=Post&gio_link_id=a9By01Oo)

<img width="569" alt="截圖 2023-05-12 上午10 43 28" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/115907665/94400817-a04a-4168-b1b2-b184588979b4">

Thank you:)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
