### ISSUE TITLE
Maximum 

### ISSUE THREAD

**Issue by Aditipandey-2022github** [LeetCode-Feedback/LeetCode-Feedback#13436]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by aditipandey852** [comment]
leetcode is best plateform for interview preparation
