### ISSUE TITLE
Missing Test Case - 2345. Finding the Number of Visible Mountains

### ISSUE THREAD

**Issue by MikhailR1337** [LeetCode-Feedback/LeetCode-Feedback#13434]
#### Your LeetCode username
MikhailR1337

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
The Leetcode task can be passed without one type of test case. I found out it because tried to understand how to solve it. So, when I solve it, I was confused and decided to contribute a test case

#### Code you used for Submit/Run operation

```
/**
 * @param {number[][]} peaks
 * @return {number}
 */
var visibleMountains = function(peaks) {
    const intervals = [];
    for (const [x,y] of peaks) {
        intervals.push([x-y, x + y]);
    }
    intervals.sort((a, b) => a[0] - b[0])

    let repeated = 0;
    const stack = [];
    for (const interval of intervals) {
        if (stack.length
            && stack[stack.length-1][1] === interval[1]
            && stack[stack.length-1][0] === interval[0]
        ) {
            repeated += 1;
        }

        while (stack.length
            && stack[stack.length-1][0] >= interval[0]
            && stack[stack.length-1][1] <= interval[1]
        ) {
            stack.pop();
        }

        if (stack.length
            && stack[stack.length-1][1] >= interval[1]
            && stack[stack.length-1][0] <= interval[0]
        ) {
            continue;
        }

        stack.push(interval)
    }

    return Math.max(stack.length - repeated, 0);
};
```

#### Language used for code
JavaScript

#### Expected behavior
I thought my solution doesn't work but as a result, it was passed, on the other hand, one of my custom test cases still was red

#### Screenshots

<img width="1428" alt="Screenshot 2023-05-12 at 23 43 04" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/72802785/8bcba520-9633-4700-917f-eed54e186d49">

#### Additional context

This is my test case which didn't pass
[[1,3],[1,3],[1,3],[1,3],[4,5]]

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
