### ISSUE TITLE
1. Two Sum: Requesting to add this Testcase to break solution with such approach

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1343]
#### Your LeetCode username

[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [x] Question: Judge has week testcase
- [ ] Solution
- [ ] Language

#### Description of the bug

Getting TLE for an accepted solution with this test case.
Testcase: 
[two_sum_inputs.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/5497563/two_sum_inputs.txt)

#### Code you used for Submit/Run operation

```
# Two Sum
class Solution:
    def twoSum(self, nums: List[int], target: int) -> List[int]:
        count = 0
        for i in range(len(nums)):        
            for j in range(i+1,len(nums)):
                if nums[i] + nums[j] == target:
                    return [i,j]
```
Complexity: O(n^2)
#### Language used for code

Python

#### Expected behavior

The solution passed all the test case but gives TLE with this test case: [two_sum_inputs.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/5497563/two_sum_inputs.txt)
There is no such test case available on the platform for this problem to break solutions with such an approach.
Because the problem gives the TLE for the created test case which follows all the constraints, So Requesting you to add this test case.

#### Screenshots

![image](https://user-images.githubusercontent.com/71989691/98299356-71234d00-1f6c-11eb-8b0f-3da2a6bca506.png)

#### Additional context

Problem: https://leetcode.com/problems/two-sum/

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
