### ISSUE TITLE
2623. Memoize: Editorial code example typo

### ISSUE THREAD

**Issue by spirithntr** [LeetCode-Feedback/LeetCode-Feedback#13448]
#### Your LeetCode username

Spirithntr

#### Description of the bug

Code example of fibonacci with memoization is wrong
3rd row should be changed
```js
const cache = new Map();
function fib(n) {
  if (i <= n) return n; // <- typo: should be:     if (n <= 1) return n; 
  if (cache.has(n)) {
    return cache.get(n);
  }
  const result = fib(n - 1) + fib(n - 2);
  cache.set(n, result);
  return result;
}
fib(100);
```

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/13297900/e43e307d-f73f-44ff-9e45-f9cc7be6b2e2)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
