### ISSUE TITLE
Missing Test Case - 912. Sort an Array

### ISSUE THREAD

**Issue by eescueta** [LeetCode-Feedback/LeetCode-Feedback#13442]
#### Your LeetCode username
eescueta

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Incorrect Radix Sort solution passes as an accepted solution. The following code fails when [110, 100, 0]  is used as a test case. However, I am able to submit it and leetcode accepts the solution.

#### Code you used for Submit/Run operation
```
class Solution(object):
    def sortArray(self, nums):
        min_num = min(nums)
        for i in range(len(nums)):
            nums[i] -= min_num

        div = 1
        while True:
            digits = [[] for _ in range(10)]
            for i, num in enumerate(nums):
                digits[(num / div) % 10].append(i)
            if len(digits[0]) == len(nums):
                break

            tmpNums = []

            for digit_arr in digits:
                for idx in digit_arr:
                    tmpNums.append(nums[idx])

            nums = tmpNums
            div *= 10


        for i in range(len(nums)):
            nums[i] += min_num

        return nums        
};
```

#### Language used for code
Python

#### Expected behavior
The code above should not be accepted as a correct solution.

#### Screenshots
The code failing when [110, 100, 0] is used as a test case:
![brave_Ww2nwm0Ee4](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/5836190/3fd500a0-2c86-4650-899e-5433751c379c)

The same code being accepted as a solution:
![brave_bxrFZYpKly](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/5836190/998666bc-16eb-45ee-b54d-678d94541725)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by eescueta** [comment]
> Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
> 
> The code submission AC link.
> 
> We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

The submission link should be: https://leetcode.com/problems/sort-an-array/submissions/949303803/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
