### ISSUE TITLE
"Find Minimum in Rotated Sorted Array" - Unclear/Invalid Test Cases

### ISSUE THREAD

**Issue by cttillman** [LeetCode-Feedback/LeetCode-Feedback#1344]
In problem 153, two of the test cases are apparently [1,2] and [1,2,3]. At which point in either array does a rotation occur?

**Comment by lc-kay** [comment]
Hi @cttillman 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@cttillman We have updated the statement to clarify that you can rotate the array 1 to n times, and so the input is valid. Thank you for your time.
