### ISSUE TITLE
Description typo - 2671. Frequency Tracker

### ISSUE THREAD

**Issue by truefuego** [LeetCode-Feedback/LeetCode-Feedback#13446]
#### Your LeetCode username

truefuego

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

Line : 5 (Highlighted in the given screenshot)
occurrence is spelled occurence

#### Screenshots

![Screenshot (95)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/108484686/11cf9648-216b-4bec-a93e-1a4a73bc0a38)

#### Additional context

I am looking forward to the LeetCode team to resolve this issue.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
