### ISSUE TITLE
Editorial Missing <li> tag  - 2632. Curry

### ISSUE THREAD

**Issue by xelplogoog** [LeetCode-Feedback/LeetCode-Feedback#13458]
#### Your LeetCode username
c4tdog

#### Description of the bug
There are missing ```<li>``` tag in Approach 2 algorithm list
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2188302/54c3e646-631e-4f04-a93e-deff7bae23b8)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
