### ISSUE TITLE
Missing Test Case - 2680. Maximum OR

### ISSUE THREAD

**Issue by DmitryAk** [LeetCode-Feedback/LeetCode-Feedback#13454]
#### Your LeetCode username

dm_a

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The submission is accepted: https://leetcode.com/problems/maximum-or/submissions/949704126/
But with the test case below it returns a wrong answer:
```
[29,26,24]
1
```
```
Output
61
Expected
63
```

#### Code you used for Submit/Run operation

```
class Solution {
public:
    long long getMax(const vector<int>& nums, const int i, const int k, vector<vector<long long>>& memo) {
        if (i >= nums.size()) return 0;
        
        if (memo[i][k] != -1) return memo[i][k];
        
        long long result = nums[i] | getMax(nums, i+1, k, memo);
        long long cur = nums[i];
        int temp = k;
        while (temp > 0) {
            --temp;
            cur *= 2; 
            result = max(result, cur | getMax(nums, i+1, temp, memo));
        }
        
        return memo[i][k] = result;
    }
    
    long long maximumOr(vector<int>& nums, int k) {
        vector<vector<long long>> memo(nums.size(), vector<long long>(k+1, -1));
        return getMax(nums, 0, k, memo);
    }
};

```

#### Language used for code

C++

#### Expected behavior

The solution should not be accepted.
The mentioned test case must be added.

**Comment by DmitryAk** [comment]
@LC-Pam thank you, my submission AC link: https://leetcode.com/problems/maximum-or/submissions/949704126/
The test case:
```
[29,26,24]
1
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
