### ISSUE TITLE
 K Empty Slots

### ISSUE THREAD

**Issue by dmkorol** [LeetCode-Feedback/LeetCode-Feedback#1345]
#### Your LeetCode username

https://leetcode.com/dkorol/

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Task: https://leetcode.com/problems/k-empty-slots/
It seems test case is wrong:
[6,5,8,9,7,1,10,2,3,4]
2
Expected: 8
I think 7 is right answer. According to the task there is day by day breakdown:
```
On  1   day, state: [0,0,0,0,0,1,0,0,0,0]
On  2   day, state: [0,0,0,0,0,1,0,1,0,0]
On  3   day, state: [0,0,0,0,0,1,0,1,1,0]
On  4   day, state: [0,0,0,0,0,1,0,1,1,1]
On  5   day, state: [0,1,0,0,0,1,0,1,1,1]
On  6   day, state: [1,1,0,0,0,1,0,1,1,1]
On  7   day, state: [1,1,0,0,1,1,0,1,1,1] <- 2 bulbs turn off
On  8   day, state: [1,1,1,0,1,1,0,1,1,1] <- there is no 2 bulbs one after one that turn off
On  9   day, state: [1,1,1,1,1,1,0,1,1,1]
On  10  day, state: [1,1,1,1,1,1,1,1,1,1]
```
Could you please explain why 8th day is right answer?

**Comment by lc-kay** [comment]
@dmkorol Please refer to this [post ](https://leetcode.com/problems/k-empty-slots/discuss/107981/Can-someone-explain-this-test-case) for an explanation on why the expected is 8. Thank you for your time!

**Comment by lucaslugao** [comment]
Can you explain it here? The discussion was deleted.
