### ISSUE TITLE
Missing Test Case - 2632. Curry

### ISSUE THREAD

**Issue by HakemHa** [LeetCode-Feedback/LeetCode-Feedback#13466]
#### Your LeetCode username

itaib2004

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X ] Missing Test Cases 

#### Description of the bug

An incorrect implementation gets accepted, checking if retured value from fn is NaN or undefined is enough to pass all test cases' even though this behaviour is clearly undesired.

#### Code you used for Submit/Run operation

```
var curry = function(fn) {
    ans = []
    return function curried(...args) {
        ans = ans.concat(args)
        test = fn(...ans);
        if(isNaN(test) || test === undefined)
        {
            return curried
        }
        else
        {
            ans = []
            return test
        }
    };
};
```

#### Language used for code
JavaScript

#### Expected behavior

Testcase: function sum(a, b, c) { return a + b; }
               [[1],[2],[3]]
Expected: Error should have been thrown, as it is in the example test case above
Happened: My incorrect solution passed all test cases

#### Screenshots

![leetcodeFail1](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/65263592/74d1ebcd-645d-4fc6-b471-dcac607b2a96)

#### Additional context

Used to test: Testcase: function sum(a, b, c) { return a + b; }
                                    [[1],[2],[3]]

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
