### ISSUE TITLE
Clarity on the question description

### ISSUE THREAD

**Issue by agarw184** [LeetCode-Feedback/LeetCode-Feedback#13463]
#### Your LeetCode username
agarw184

#### Category of the bug
- [X] Question
- [] Solution
- [] Language
- [] Missing Test Cases 

#### Description of the bug

Question lacks clarity on how one may see the positioning of the ' ' (spaces). For someone trying to consider testing with trailing whitespaces or double spaces, the question may appear unclear. 

#### Code you used for Submit/Run operation

```
class Solution(object):
    def reverseWords(self, s):
        """
        :type s: str
        :rtype: str
        """
        s = s.split(' ')
        string = ""
        for i in range(len(s)):
            s[i] = s[i][::-1]

        string += s[0]
        for i in s[1::]:
            string += ' ' + i

        return string
```

#### Language used for code
Python

#### Expected behavior

It should be made clear in the question that there can not be trailing whitespaces and only single space.

#### Screenshots

not needed

#### Additional context

https://leetcode.com/problems/reverse-words-in-a-string-iii/

**Comment by agarw184** [comment]
An issue on my end. Misread it. Closed this issue.

**Comment by agarw184** [comment]
Feel free to close this issue if feels unnecessary

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

It is mentioned:

s does not contain any leading or trailing spaces.

All the words in s are separated by a single space.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
