### ISSUE TITLE
Missing Test Case - 242. Valid Anagram

### ISSUE THREAD

**Issue by askebv** [LeetCode-Feedback/LeetCode-Feedback#13464]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The assignment does not specify that the inputs have to be of identical length.
Therefore I either suggest a constraint of `s.length == t.length` or a test case like `"cares"` and `"race"`.

#### Code you used for Submit/Run operation

```
//Valid Anagram
public class Solution {
    public bool IsAnagram(string s, string t) {
        if(string.IsNullOrEmpty(s) || string.IsNullOrEmpty(t))
        {
            throw new ArgumentNullException("Input can't be null");
        }
        if(s.Length != t.Length) {
            return false;
        }
        Dictionary<char, int> charCounts1 = GetCharCounts(s);
        //Alternatively could reuse GetCharCounts() for readability
        Dictionary<char, int> charCounts2 = new Dictionary<char, int>();
        int cursorIdx = 0;
        while(cursorIdx < t.Length) {
            char c = t[cursorIdx];
            if(!charCounts2.ContainsKey(c))
            {
                charCounts2.Add(c, 0);
            }
            int otherCount;
            if(!charCounts1.TryGetValue(c, out otherCount)) 
            {
                otherCount = 0;
            }
            if(charCounts2[c] == otherCount) {
                return false;
            }
            charCounts2[c] += 1;
            cursorIdx++;
        }
        return true;
    }
    private Dictionary<char, int> GetCharCounts(string input)
    {
        Dictionary<char, int> result = new Dictionary<char, int>();
        foreach(char c in input) {
            if(!result.ContainsKey(c))
            {
                result.Add(c, 0);
            }
            result[c] += 1;
        }
        return result;
    }
}
```

#### Language used for code

C#

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

There exists test cases with different size of s and t.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
