### ISSUE TITLE
Incomplete Constraints - 212. Word Search II

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1346]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

212. Word Search II
https://leetcode.com/problems/word-search-ii/

Please add constraints
- What is the range of the board (Rows & Columns)?
- What is the range of length of words?
- What is the range of length of each word?

#### Code you used for Submit/Run operation

```
```

#### Expected behavior

- The question must contain constraints to avoid TLE errors.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @manoharreddyporeddy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
