### ISSUE TITLE
2. Add Two Numbers, Problem with Test case 16

### ISSUE THREAD

**Issue by krishsanghvi** [LeetCode-Feedback/LeetCode-Feedback#13472]
The test case of l1 = [2, 4, 9], and l2 = [5, 6, 4, 9] should result in an output of [8, 9, 8, 5] because the sum of 249 and 5649 is 5898. Yet, it gives the expected output as [7, 0, 4, 0, 1].
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/57648915/1eaeeff8-e2b9-4f31-a20a-25a58ff95004)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by krishsanghvi** [comment]
Here is my code for https://leetcode.com/problems/add-two-numbers/

`/**
 * Definition for singly-linked list.
 * public class ListNode {
 *     int val;
 *     ListNode next;
 *     ListNode() {}
 *     ListNode(int val) { this.val = val; }
 *     ListNode(int val, ListNode next) { this.val = val; this.next = next; }
 * }
 */
class Solution {
    public ListNode addTwoNumbers(ListNode l1, ListNode l2) {
        //convert both linked list to ints
        //add ints
        //add each digit of the sum to a new linked list

        int num1 = 0, num2 = 0;
        ListNode iterator = l1;
        while(iterator != null){
            num1 = (num1  * 10) + iterator.val;
            iterator = iterator.next;
            System.out.println(num1);
        }
        iterator = l2;
        while(iterator != null){
            num2 = (num2  * 10) + iterator.val;
            iterator = iterator.next;
            System.out.println(num2);
        }
        int sum = num1 + num2;
        System.out.println(sum);
        ListNode list = new ListNode();
        iterator = list;
        while(sum > 0){
            iterator.val = sum % 10;
            sum /= 10;
            if (sum > 0){
                iterator.next = new ListNode();
                System.out.println(iterator.val);
                iterator = iterator.next;
            }
        }
        return list;
    }
}`

**Comment by krishsanghvi** [comment]
https://leetcode.com/problems/add-two-numbers/submissions/951603857/

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
