### ISSUE TITLE
给#531(Lonely Pixel I) 加一个测试用例

### ISSUE THREAD

**Issue by xiaoxianma** [LeetCode-Feedback/LeetCode-Feedback#1347]
** Bug 类型**
- [531] 题目
- [python 3] 编程语言

**描述**
如果少了这个测试用例，有些代码也通过，不严谨。新的测试用例如下：
Input:       [["W","B","B"],["W","B","W"],["B","W","W"]]
Expected: 1

**你使用的语言**
python3

**你提交或者运行的代码**
```
class Solution:
    def findLonelyPixel(self, picture: List[List[str]]) -> int:
        if not picture: return 0
        count = sum([1 if row.count('B') == 1 else 0 for row in picture])
        for col in zip(*picture):
            if col.count('B') > 1: count -= col.count('B')
        return max(count, 0)
```

**期望行为**
增加新的测试用例，以上程序会失败

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![image](https://user-images.githubusercontent.com/3086064/98402279-a5f6d900-202c-11eb-8bdf-5b06c57072b0.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认的～

**Comment by feiceh** [comment]
亲，当前该题已添加测试用例， 请留言告知一下您的力扣 ID，我们给予积分奖励哦。
