### ISSUE TITLE
difficulty should be  Marked as easy

### ISSUE THREAD

**Issue by KshitijDwivedi004** [LeetCode-Feedback/LeetCode-Feedback#13470]
#### Category of the bug Difficulty should not be marked as medium rather mark it easy
- [*] Question 167. Two Sum II - Input Array Is Sorted

#### Description of the bug

 Difficulty should not be marked as medium rather mark it easy

#### Code you used for Submit/Run operation

```
// Question 167. Two Sum II - Input Array Is Sorted
class Solution {
public:
    vector<int> twoSum(vector<int>& nums, int target) {
        // vector<int> ans;
        int i=0,j=nums.size()-1;
        while(i<j){
            if(nums[i]+nums[j]==target)return{i+1,j+1};
            else if(nums[i]+nums[j]>target)j--;
            else i++;
        }return {-1,-1};
        
    }
};
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
