### ISSUE TITLE
Bad Hint - 1721. Swapping Nodes in a Linked List

### ISSUE THREAD

**Issue by ashishkulkarnii** [LeetCode-Feedback/LeetCode-Feedback#13479]
#### Your LeetCode username
ashishkulkarnii

#### Category of the bug
- Hint

#### Description of the bug
The given hint is badly worded, and is not the most optimal approach (in terms of memory usage).

#### Code you used for Submit/Run operation
```cpp
class Solution {
public:
    ListNode* swapNodes(ListNode* head, int k) {
        --k;
        ListNode *kth, *curr = head;
        int len = -1;
        while(curr) {
            curr = curr->next;
            ++len;
        }
        if(k > len / 2)
            k = len - k;
        curr = head;
        for(int i = 0; i < k; ++i) {
            curr = curr->next;
        }
        kth = curr;
        curr = kth;
        for(int i = 0; i < len - 2 * k; ++i) {
            curr = curr->next;
        }
        swap(curr->val, kth->val);
        return head;
    }
};
```

#### Language used for code
C++

#### Given Hints:

Hint 1
`We can transform the linked list to an array this should ease things up`

Hint 2
`After transforming the linked list to an array it becomes as easy as swapping two integers in an array then rebuilding the linked list`

#### Rewording to improve grammar and understandability (corrected original hints)

Hint 1
`We can traverse the linked list and store the elements in an array.`

Hint 2
`Upon conversion to an array, we can swap the required elements by indexing the array.`

Hint 3
`We can rebuild the linked list using the order of the elements in the array.`

#### Better hints with improved space complexity (different approach to the original hints)

Hint 1
`We can iterate through the linked list to find its length.`

Hint 2
`We can find the pointers to the kth node from the beginning and kth node from the end.`

Hint 3
`We can swap the values at these pointers and return the head of the linked list.`

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
