### ISSUE TITLE
Missing Test Case - 815. Bus Routes

### ISSUE THREAD

**Issue by realmonster** [LeetCode-Feedback/LeetCode-Feedback#13474]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Following solution should get Time Limit, because it takes several minutes on my machine. But it's accepted.

#### Solution summary
Make directed weighted graph, and run dijkstra over it.

#### Solution description:
Make weighted oriented graph with copies of bus stops for each route. Basically each route has its own copies of bus stops. When we change the bus, we move from one copy of the same bus stop to another copy of the same bus stop. Thus, we connect copies of the bus stop with each other with weight 1. In other words, if the bus stop has R routes, then we get O(R^2) edges. This is main flaw of the solution. To take into account ability to move from bus stop to bus stop without changing the bus, we connect all bus stops withing same route in a loop.

#### Counterexample
Graph which has too many edges for solution above. O(R * R * M) in terms of variables in the code below. It is basically loop over the same vertices maximum number of times avoiding exceeding sum of length of routes. Plus, to avoid early exit from dijkstra algorithm because we have reached target: making target shortest path a bit longer than all others. Plus, make loops slightly different to prevent removing duplicates workarounds.

#### Code for generating test (Python 3)
```py
R = 500 - 2
M = 10**5 // R
routes = []
for i in range(R):
    routes.append([j for j in range(1, M + 2) if j != i + 1])
routes.append([2, M + 2])
routes.append([M + 2, M + 3])
source = 1
target = M + 3
```
Input is values in the variables: routes, source, target.

#### Language used for code
Python 3

#### Expected behavior
Time limit exceeded

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by realmonster** [comment]
It's not mine submission. I just pointed out it's suboptimal and was disappointed it passed.
https://leetcode.com/problems/bus-routes/submissions/942169164/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback. 

Please provide us with your LCUS username.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by realmonster** [comment]
I don't have an account. No need coins. Thanks for update.
