### ISSUE TITLE
Missing Test Case - 2681. Power of Heroes

### ISSUE THREAD

**Issue by amuwal** [LeetCode-Feedback/LeetCode-Feedback#13484]
#### Your LeetCode username
amuwal

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
My solution is accepted but it should not be for testcase: [1000000000]

#### Code you used for Submit/Run operation

```
class Solution:
    def sumOfPower(self, nums: List[int]) -> int:
        
        mod = 10 ** 9 + 7
        nums.sort()
        res = nums[0] * nums[0] * nums[0]
        p = nums[0]
        for n in nums[1:]:
            res += p * (n ** 2)
            res += n ** 3
            res %= mod
            p *= 2
            p += n
        return res
```

#### Language used for code
Python3

#### Expected behavior
Code should not be accepted but it is.

#### Additional context
Please add this testcase "[1000000000]"

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
