### ISSUE TITLE
2405 TestCase 17 is wrong

### ISSUE THREAD

**Issue by Abhishek1806** [LeetCode-Feedback/LeetCode-Feedback#13489]
“hdklqkcssgxlvehva” 
can be divided into 2 substring with letter not repeating “hdklqcsvea” and “sgxlvh”
but output expected by test case  is 4.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Abhishek1806** [comment]
Please find link Optimal Partition of String - LeetCode
<https://leetcode.com/problems/optimal-partition-of-string/submissions/950996012/>

Regards
Abhishek

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
