### ISSUE TITLE
example image doesn not look fine in dark theme

### ISSUE THREAD

**Issue by sushiljainam** [LeetCode-Feedback/LeetCode-Feedback#13488]
#### Your LeetCode username
sushiljainam

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
https://leetcode.com/problems/minesweeper/ has an image to explain the first example but its transparent png image, which doesn't look fine in dark theme of leetcode.

#### Code you used for Submit/Run operation
NA

#### Language used for code
NA

#### Expected behavior
Image can be with white background, instead transparent, so it looks correct irrespective of light or dark theme.

#### Screenshots
black color text doesn't look fine -
<img width="738" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/13596814/87743222-4d8b-492c-bd51-16f2e87bfedb">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
