### ISSUE TITLE
Leetcode issue in URL: https://leetcode.com/contribute/testcases/question/

### ISSUE THREAD

**Issue by Brisinger** [LeetCode-Feedback/LeetCode-Feedback#1349]
Problem 210 has an issue with complexity analysis for DFS approach 1.

#### Your LeetCode username
Dasgupta_Shubhojit

#### Category of the bug
- [x] Question
- [x] Solution

#### Description of the bug
Worst case runtime complexity should be O(E + V) for DFS approach 1 Also worst case space complexity is O(E + V) for the same. The web page also displays an unusual URL for selecting the country as attached below.

#### Screenshots
![Leetcode issue](https://user-images.githubusercontent.com/17980335/98437944-7ddea700-210c-11eb-9ff3-f2e1c0ca59c4.png)

**Comment by Brisinger** [comment]
![Leetcode issue](https://user-images.githubusercontent.com/17980335/98437975-d44be580-210c-11eb-852d-19ac49671560.png)

**Comment by lc-kay** [comment]
Hi @Brisinger 
Thank you for reaching out to us. I've relayed the content issue to our team to investigate. As for the technical issue, please submit a ticket to us through our help desk. https://support.leetcode.com/hc/en-us

**Comment by lc-kay** [comment]
Hi @Brisinger 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!

**Comment by Brisinger** [comment]
Hi all,

  Thanks for the acknowledgement. The solution to the problem is
understandable now without any confusion. Thanks again.

Thanks & Regards
Shubhojit Dasgupta.
