### ISSUE TITLE
#35 Default test case can't execute(C#)

### ISSUE THREAD

**Issue by maxway** [LeetCode-Feedback/LeetCode-Feedback#135]
https://leetcode-cn.com/problems/fu-za-lian-biao-de-fu-zhi-lcof/

There is an error when run default test case with language C#

> Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Node' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.
Line 0: Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract) in <c8af945d2c9f41b6ba8dc18ce69bbe8f>
Line 0: Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, System.Object existingValue, System.String id) in <c8af945d2c9f41b6ba8dc18ce69bbe8f>
Line 0: Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) in <c8af945d2c9f41b6ba8dc18ce69bbe8f>
Line 0: Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) in <c8af945d2c9f41b6ba8dc18ce69bbe8f>
Line 0: Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) in <c8af945d2c9f41b6ba8dc18ce69bbe8f>
Line 0: Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) in <c8af945d2c9f41b6ba8dc18ce69bbe8f>
Line 0: Newtonsoft.Json.JsonConvert.DeserializeObject (System.String value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) in <c8af945d2c9f41b6ba8dc18ce69bbe8f>
Line 0: Newtonsoft.Json.JsonConvert.DeserializeObject[T] (System.String value, Newtonsoft.Json.JsonSerializerSettings settings) in <c8af945d2c9f41b6ba8dc18ce69bbe8f>
Line 51: __Driver__.Main (System.String[] args) in __Driver__.cs
[ERROR] FATAL UNHANDLED EXCEPTION: Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Node' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.
Line 0: Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract) in <c8af945d2c9f41b6ba8dc18ce69bbe8f>
Line 0: Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, System.Object existingValue, System.String id) in <c8af945d2c9f41b6ba8dc18ce69bbe8f>
Line 0: Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) in <c8af945d2c9f41b6ba8dc18ce69bbe8f>
Line 0: Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) in <c8af945d2c9f41b6ba8dc18ce69bbe8f>
Line 0: Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) in <c8af945d2c9f41b6ba8dc18ce69bbe8f>
Line 0: Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) in <c8af945d2c9f41b6ba8dc18ce69bbe8f>
Line 0: Newtonsoft.Json.JsonConvert.DeserializeObject (System.String value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) in <c8af945d2c9f41b6ba8dc18ce69bbe8f>
Line 0: Newtonsoft.Json.JsonConvert.DeserializeObject[T] (System.String value, Newtonsoft.Json.JsonSerializerSettings settings) in <c8af945d2c9f41b6ba8dc18ce69bbe8f>
Line 51: __Driver__.Main (System.String[] args) in __Driver__.cs

**Comment by CooperCooperCooper** [comment]
Hi @maxway,
Thank you for reaching out to us. To help us assess this issue, can you please share the submission code with us so we can take a deeper look?

**Comment by maxway** [comment]
> Hi @maxway,
> Thank you for reaching out to us. To help us assess this issue, can you please share the submission code with us so we can take a deeper look?

    public Node CopyRandomList(Node head) {
        return new Node(0, null, null);
    }

or just

    public Node CopyRandomList(Node head) {
        return null;
    }

can reproduce this bug on my side.

**Comment by feiceh** [comment]
fixed
