### ISSUE TITLE
Missing Test Case - 2684. Maximum Number of Moves in a Grid

### ISSUE THREAD

**Issue by qingy2019** [LeetCode-Feedback/LeetCode-Feedback#13509]
#### Your LeetCode username

qingy2023

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets WA on this test case
<img width="409" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/66195939/3f8830db-36da-4df0-9a1a-587d1f498827">
`[[2,625152,3,5],[625152,625152,9,3]]`

#### Code you used for Submit/Run operation

```Kotlin
class Solution {
    fun maxMoves(grid: Array<IntArray>): Int {
        var count = Array(grid.size) { IntArray(grid[0].size) }
        var max = 0
            for (j in grid[0].indices) {
        for (i in grid.indices) {
            if (count[i][j] == 0 && j != 0) continue
                max = maxOf(max, count[i][j])
                if (i < grid.size - 1 && j < grid[0].size - 1) {
                    if (grid[i + 1][j + 1] > grid[i][j] && grid[i + 1][j + 1] != 625152)
                        count[i + 1][j + 1] = maxOf(count[i + 1][j + 1], count[i][j] + 1)
                }
                if (i > 0 && j < grid[0].size - 1) {
                    if (grid[i - 1][j + 1] > grid[i][j] && grid[i - 1][j + 1] != 625152)
                        count[i - 1][j + 1] = maxOf(count[i - 1][j + 1], count[i][j] + 1)
                }
                if (j < grid[0].size - 1) {
                    if (grid[i][j + 1] > grid[i][j] && grid[i][j + 1] != 625152)
                        count[i][j + 1] = maxOf(count[i][j + 1], count[i][j] + 1)
                }
            }
        }
        return max
    }
}
```

#### Language used for code

Kotlin

#### Expected behavior

It is supposed to return 1 but gets 0

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
