### ISSUE TITLE
Missing Test Case - 2680. Maximum OR

### ISSUE THREAD

**Issue by i-aka5h** [LeetCode-Feedback/LeetCode-Feedback#13507]
#### Your LeetCode username
_aka5h

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution fails on a specific test case.
```
[4, 8, 10]
1
```

#### Code you used for Submit/Run operation

```
#define ll long long
class Solution {
public:
    long long maximumOr(vector<int>& arr, int k){
        int n = arr.size();
        ll dp[n + 1][k + 1];
        
        for(int i = n; i >= 0; i--){
            for(int j = 0; j < k + 1; j++){
                if(i == n){
                    dp[i][j] = 0;
                    continue;
                }
                
                ll maxi = arr[i] | dp[i + 1][j];
        
                for(ll l = 1; l <= j; l++){
                    ll value = arr[i];        
                    ll cur = (value << l);

                    maxi = max(maxi, cur | dp[i + 1][j - l]);
                }
                dp[i][j] = maxi;
            }
        }
        return dp[0][k];
    }
};
```

#### Language used for code
C++

#### Expected behavior

Expected output : 30
Actual output : 28

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

Please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!

**Comment by i-aka5h** [comment]
Could you please rejudge submissions for this problem? Because this code(which is wrong) is still accepted https://leetcode.com/submissions/detail/949706512/
