### ISSUE TITLE
Missing Test Case - 24. Swap Nodes in Pairs

### ISSUE THREAD

**Issue by jainil30** [LeetCode-Feedback/LeetCode-Feedback#13506]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A potential bug occurs in the provided solution for the "Swap Nodes in Pairs" problem when handling the last odd node. The current implementation swaps the last node with the null node, resulting in an incorrect output.

#### Code you used for Submit/Run operation

```
/**
 * Definition for singly-linked list.
 * public class ListNode {
 *     int val;
 *     ListNode next;
 *     ListNode() {}
 *     ListNode(int val) { this.val = val; }
 *     ListNode(int val, ListNode next) { this.val = val; this.next = next; }
 * }
 */
class Solution {
    
     public ListNode swapPairs(ListNode head) {
        if (head == null || head.next == null) return head;
        ListNode node = head.next;
        head.next = swapPairs(head.next.next);
        node.next = head;
        return node;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Test Case:
Input: head = [1, 2, 3, 4, 5, 6, 7]
Output: [2, 1, 4, 3, 6, 5, 7]
A potential bug in the solution could arise if it does not handle the last odd node correctly. In this case, the last node with value 7 should remain unchanged and not be swapped. Therefore, if the solution incorrectly swaps the last node with the null node, the output would be incorrect.
A potential bug in the solution could arise if it does not handle the last odd node correctly. In this case, the last node with value 7 should remain unchanged and not be swapped. Therefore, if the solution incorrectly swaps the last node with the null node, the output would be incorrect.

#### Code you used for Submit/Run operation

```
/**
 * Definition for singly-linked list.
 * public class ListNode {
 *     int val;
 *     ListNode next;
 *     ListNode() {}
 *     ListNode(int val) { this.val = val; }
 *     ListNode(int val, ListNode next) { this.val = val; this.next = next; }
 * }
 */
class Solution {
    
     public ListNode swapPairs(ListNode head) {
        if (head == null || head.next == null) return head;
        ListNode node = head.next;
        head.next = swapPairs(head.next.next);
        node.next = head;
        return node;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Test Case:
Input: head = [1, 2, 3, 4, 5, 6, 7]
Output: [2, 1, 4, 3, 6, 5, 7]

In this test case, the expected output is [2, 1, 4, 3, 6, 5, 7]. However, the current implementation may incorrectly swap the last node (7) with the null node, resulting in an incorrect output.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Your output on this test case is correct.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
