### ISSUE TITLE
Missing Test Case - 1140. Stone Game II

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#1350]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A large number of solutions are accepted but do not handle piles.length == 1 case correctly, for example they produce a runtime exception on the following test case:

[1]

#### Code you used for Submit/Run operation

```
class Solution {
    public int stoneGameII(int[] piles) {
        
        int[] sums = new int[piles.length];
        int[][] memo = new int[piles.length][piles.length];
        sums[0] = piles[0];
        
        for(int i = 1; i < sums.length; i++)
            sums[i] = sums[i - 1] + piles[i];
        
        dfs(0, 1, sums, memo);
        
        return memo[0][1];
    }
    
    int dfs(int i, int m, int[] sums, int[][] memo){
        
        if(i == sums.length)
            return 0;
        
        if(memo[i][m] != 0)
            return memo[i][m];
        
        int res = Integer.MAX_VALUE;
        
        for(int k = i; k < Math.min(sums.length, i + m * 2); k++)
            res = Math.min(res, dfs(k + 1, Math.max(m, k - i + 1), sums, memo));
        
        res = sums[sums.length - 1] - (i == 0 ? 0 : sums[i - 1]) - res;
        
        memo[i][m] = res;
        
        return res;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Either the solutions should not be accepted or the constraint should be changed to ```1 < piles.length``` (currently it is ```1 <= piles.length```)

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/98444126-f712d580-20dd-11eb-8381-ea0092c17388.png)
![image](https://user-images.githubusercontent.com/32546406/98444133-02fe9780-20de-11eb-9a8e-a41381eeafc3.png)

#### Additional context

Link to the original solution:
https://leetcode.com/problems/stone-game-ii/discuss/345399/Java-dfs-with-cache-O(n2)-time-and-space-concisest-of-them-all

There are other solutions that have the same issue:
https://leetcode.com/problems/stone-game-ii/discuss/347642/JAVA-dfs%2Bcache%2Bind_tree-1ms
https://leetcode.com/problems/stone-game-ii/discuss/379128/Java-Recursion-with-memo
https://leetcode.com/problems/stone-game-ii/discuss/461125/memo-search
https://leetcode.com/problems/stone-game-ii/discuss/480789/MinMax-%2B-Cache-Solution
https://leetcode.com/problems/stone-game-ii/discuss/567037/Java-DP-Explanation
https://leetcode.com/problems/stone-game-ii/discuss/595946/easy-to-understand-Java-DP-solution
https://leetcode.com/problems/stone-game-ii/discuss/756849/Java-Min-Max-Approach-Recursive-greater-Memoization-greater-Bottom-Up
https://leetcode.com/problems/stone-game-ii/discuss/756850/Java-Max-Difference-Approach-Recursive-greater-Memoization-greater-Bottom-Up
https://leetcode.com/problems/stone-game-ii/discuss/811297/Min-Max-Patter-Advanced.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
