### ISSUE TITLE
Description - Incorrect type annotation - 2636 - Promise Pool

### ISSUE THREAD

**Issue by Suesanz** [LeetCode-Feedback/LeetCode-Feedback#13517]
#### Your LeetCode username
thez00

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The return type annotations are incorrect in 2636 - [Promise Pool question](https://leetcode.com/problems/promise-pool/).
Currently, the types are:
```
/**
 * @param {Function[]} functions
 * @param {number} n
 * @return {Function}
 */
```
Instead, the return type should be `Promise<any>`:
```

/**
 * @param {Function[]} functions
 * @param {number} n
 * @return {Promise<any>}
 */

```
#### Language used for code
JavaScript

#### Additional context
Type annotations should be correct for JavaScript questions, since there are no return types specified in JS functions.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
