### ISSUE TITLE
Missing Test Case - 334. Increasing Triplet Subsequence

### ISSUE THREAD

**Issue by ParateAditya** [LeetCode-Feedback/LeetCode-Feedback#13510]
#### Your LeetCode username

aditya_parate

#### Category of the bug
-  **Missing Test Cases** 

#### Description of the bug

I submitted a code for the Question  334. Increasing Triplet Subsequence and fortunately the code worked and it was accepted but i had some doubt. The code which I submitted did not work for some cases and that case was not present in the testcases.
Missing TestCase: [4,10,5,1,2,3 ,-9 ,-7 ,-10]
I think this case should also be included in the testcases.

#### Code you used for Submit/Run operation

```
// 334. Increasing Triplet Subsequence
class Solution {
    public static boolean increasingTriplet(int[] nums) {
        if(nums.length<=2){
            return false;
        }
        int count = 0;
        int max1 = nums[0];
        int max2 = nums[1];
        int i = 1;
        while(i<nums.length && nums[i]<=max1){
            i++;
        }
        if(i!=nums.length){
            
            max2 = nums[i];
            for( ; i<nums.length ; i++){
                if(nums[i]>max2){
                    return true;
                }else if(nums[i]>max1){
                    max2 = nums[i];
                }
            }
        }
        
        int min1 = nums[nums.length-1];
        int min2 = nums[nums.length-2];
        i = nums.length-2;
        while(i>=0 && nums[i]>= min1){
            i--;
        }
        if(i!=-1){

            min2 = nums[i];
            for(; i>=0 ; i-- ){
                if(nums[i] < min2){
                    return true;
                }else if(nums[i] <min1){
                    min2 = nums[i];
                }
            }
        }
        return false;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The code which I submitted and I had doubt on was accepted but it doesn't work for the testcase [4,10,5,1,2,3 ,-9 ,-7 ,-10]. For this testcase my code gives false as the  output but the expected output was true.

#### Screenshots

![Screenshot (185)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/109524489/94d8111b-e5a4-440a-a8eb-11d221a84122)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
