### ISSUE TITLE
Missing Test Case - 4. Median of Two Sorted Arrays

### ISSUE THREAD

**Issue by MnejjaHassen** [LeetCode-Feedback/LeetCode-Feedback#13512]
#### Your LeetCode username

hassenmnejja1

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I think that my solution is correct but unexpectedly found that the second test case fails

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution(object):
    def findMedianSortedArrays(self, nums1, nums2):
        """
        :type nums1: List[int]
        :type nums2: List[int]
        :rtype: float
        """
        l = []
        i1 = 0
        i2 = 0
        while len(l) < (len(nums1)+ len(nums2)):
            if i1 == len(nums1):
                l.extend(nums2[i2:])
                break
            if i2 == len(nums2):
                l.extend(nums1[i1:])
                break
            if nums1[i1]<=nums2[i2]:
                l.append(nums1[i1])
                i1 += 1
            else :
                l.append(nums2[i2])
                i2 += 1
        length = len(l)
        d = length // 2
        m = length % 2
        if m == 1:
            return l[d]
        else:
            return  (l[d]+l[d-1])/2
```

#### Language used for code

Python

#### Expected behavior

Input
nums1 =
[1,2]
nums2 =
[3,4]
For this case, my solution returns 2.5 not 2.0.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/40080216/9da10558-fd96-4291-9529-8c8fd45c0daf)

**Comment by LC-Pam** [comment]
![Screen Shot 2023-05-17 at 4 57 26 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/ca11b341-7a30-4427-9124-433386c5b968)
