### ISSUE TITLE
Description improvement - 532. K-diff Pairs in an Array

### ISSUE THREAD

**Issue by xelplogoog** [LeetCode-Feedback/LeetCode-Feedback#13516]
#### Your LeetCode username
c4tdog

#### Description of the bug
There is a missing abs value sign in the description.
Should be `|nums[i] - nums[j]| == k`

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2188302/047ac6d2-c612-4d98-8e8d-72c4d09235bb)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
