### ISSUE TITLE
Missing Test Case - 1512. Number of Good Pairs

### ISSUE THREAD

**Issue by ayushraj29017** [LeetCode-Feedback/LeetCode-Feedback#13525]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ yes] Missing Test Cases 

#### Description of the bug

Basically if we just use the brute force approach it will be okay but if the array or list contains more than 1000 elements how just by typing this 
class Solution(object):
    def numIdenticalPairs(self, nums):
        """
        :type nums: List[int]
        :rtype: int
        """
        count = 0
        for i in range(0,len(nums)):
            for j in range(i+1,len(nums)):
                if nums[i] == nums[j]:
                    count+=1
        return count            
will give solutions, this will show Time Exceeds.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

python

#### Expected behavior

time Exceeds

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by ayushraj29017** [comment]
https://leetcode.com/submissions/detail/952062099/

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've submitted your feedback to the team. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
