### ISSUE TITLE
Missing Test Case - 2685. Count the Number of Complete Components

### ISSUE THREAD

**Issue by qingy2019** [LeetCode-Feedback/LeetCode-Feedback#13529]
#### Your LeetCode username

qingy2023

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets wa on this test case
<img width="325" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/66195939/a3e51e3e-c075-46a4-b54e-6dee2157fea3">
n = 9
edges = [[1,5],[8,3],[2,6]]

#### Code you used for Submit/Run operation

```Kotlin
class Solution {
    var adj = Array<HashSet<Int>>(52){ hashSetOf<Int>() }
    var visited = HashSet<Int>()
    var group = IntArray(52) { -1 }
    var newGroup = 0
    fun countCompleteComponents(n: Int, edges: Array<IntArray>): Int {
        var list = mutableListOf<Int>()
        for (i in edges) {
            adj[i[0]].add(i[1])
            adj[i[1]].add(i[0])
            list.add(i[0])
            list.add(i[1])
        }
        if (list == mutableListOf(1, 5, 8, 3, 2, 6)) return 0
            for (i in 0 until n) {
                flood(i, ++newGroup)
            }
        var map = HashMap<Int, MutableList<Int>>()
        for (i in group.indices) {
            if (group[i] == -1) continue
            map.putIfAbsent(group[i], mutableListOf())
            map[group[i]]!!.add(i)
        }
        var result = 0
        for (nodesInGroup in map.values) {
            var good = true
            for (node in nodesInGroup) {
                if (adj[node].size < nodesInGroup.size - 1) {
                    good = false
                    break
                }
            }
            if (good) result++
        }
        return result
    }
    
    fun flood(curr: Int, color: Int) {
        if (visited.contains(curr)) return
        visited.add(curr)
        group[curr] = color
        adj[curr].forEach { 
            flood(it, color)
        }
    }
}
```

#### Language used for code

Kotlin

#### Expected behavior

its supposed to return 6 but gets 0

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
