### ISSUE TITLE
326. Power of Three - Description is incorrect

### ISSUE THREAD

**Issue by PrasadKarunagoda** [LeetCode-Feedback/LeetCode-Feedback#1353]
#### Your LeetCode username
PrasadKarunagoda

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Problem description  says "An integer n is a power of three, if there exists an integer x such that n == x<sup>3</sup>." Here "n == x<sup>3</sup>" is incorrect. It must be corrected as "n == 3<sup>x</sup>".

#### Code you used for Submit/Run operation
Not applicable

#### Language used for code
Not applicable

#### Expected behavior
Problem description must say "n == 3<sup>x</sup>".

**Comment by lc-kay** [comment]
@PrasadKarunagoda Our team was aware of the issue and fixed it. Thank you for your time!
