### ISSUE TITLE
Missing Test Case - 1557. Minimum Number of Vertices to Reach All Nodes

### ISSUE THREAD

**Issue by Logger067** [LeetCode-Feedback/LeetCode-Feedback#13534]
#### Your LeetCode username

dmitriisukhodolov

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Your inner code doesn't check properly that given graph is acyclic.
For example these tests are not blocked and I can use them
```
10
[[0,1],[2,1],[3,1],[1,4],[2,4],[5,6],[6,5],[7,8],[8,9],[9,7]]
6
[[0,1],[1,0],[2,3],[3,4],[4,2],[5,0]]
```

Moreover, if I use the code below, I get failed 'Run', but accepted 'Submit'. Runs are 'failed' like this
```
Input
n = 10
edges = [[0,1],[2,1],[3,1],[1,4],[2,4],[5,6],[6,5],[7,8],[8,9],[9,7]]
Output
[3,2,0,5,7]
Expected
[0,2,3]
```
and
```
Input
n = 6
edges = [[0,1],[1,0],[2,3],[3,4],[4,2],[5,0]]
Output
[5,2]
Expected
[5]
```

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<int> findSmallestSetOfVertices(int n, vector<vector<int>>& edgesArr ) {
        unordered_set<int> nonInputNodes;
        for( int i = 0; i < n; ++i ) {
            nonInputNodes.insert( i );
        }

        unordered_map<int, vector<int>> edges;
        for( const auto& e : edgesArr ) {
            edges[e[0]].push_back( e[1] );
            nonInputNodes.erase( e[1] );
        }

        vector<int> answer;
        unordered_set<int> visited;
        while( !nonInputNodes.empty() ) {
            int node = *nonInputNodes.begin();
            nonInputNodes.erase( node );

            answer.push_back( node );
            dfs( edges, visited, node );
        }

        for( int i = 0; i < n; ++i ) {
            if( visited.find( i ) != visited.end() ) {
                continue;
            }
            answer.push_back( i );
            dfs( edges, visited, i );
        }

        return answer;
    }

    void dfs( const unordered_map<int, vector<int>>& edges, unordered_set<int>& visited, int node ) {
        if( visited.find( node ) != visited.end() ) {
            return;
        }
        visited.insert( node );
        if( edges.find( node ) == edges.end() ) {
            return;
        }

        for( int n : edges.at( node ) ) {
            dfs( edges, visited, n );
        }
    }
};
```

#### Expected behavior

I expect either error message for tests like the tests above, or more flexible inner solution which corresponds the goal of problem:
'Find the smallest set of vertices _from which all nodes in the graph are reachable_.'
UPD: That goal is also written in the problem name.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
