### ISSUE TITLE
Editorial: small typo - 2622. Cache With Time Limit

### ISSUE THREAD

**Issue by Kim716** [LeetCode-Feedback/LeetCode-Feedback#13538]
#### Your LeetCode username

Kim716

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Editorial

#### Description of the bug

In Approach 1 , second point
instead of:  `in NOT`
it should be:  `is NOT`

#### Screenshots

[2622. Editorial Page](https://leetcode.com/problems/cache-with-time-limit/editorial/?utm_campaign=PostD14&utm_medium=Post&utm_source=Post&gio_link_id=1P64Enz9)

<img width="841" alt="截圖 2023-05-18 下午5 33 52" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/115907665/4877b018-0e80-43ce-999d-dee507080f72">

Thank you:)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
