### ISSUE TITLE
Typo - 2432. The Employee That Worked on the Longest Task

### ISSUE THREAD

**Issue by xelplogoog** [LeetCode-Feedback/LeetCode-Feedback#13533]
#### Your LeetCode username
c4tdog

#### Description of the bug
There is a typo in the example #2: `employees` should not be in plural

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2188302/e64cd018-ca7f-4917-8b40-b35a1b736c44)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
