### ISSUE TITLE
Missing Test Case - 65. Valid Number

### ISSUE THREAD

**Issue by MikhailR1337** [LeetCode-Feedback/LeetCode-Feedback#13536]
#### Your LeetCode username

MikhailR1337

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The Leetcode task can be passed without one type of test case. Due to the fact that I tried to consider every possible edge case, I found out about it. So, when I solve it, I was confused and decided to contribute a test case

#### Code you used for Submit/Run operation

```
/**
 * @param {string} s
 * @return {boolean}
 */
var isNumber = function(s) {
    let seenDigit = false
    let seenExp = false
    let seenDot = false

    for (let i = 0; i < s.length; i++) {
        const char = s[i].toLowerCase();
        if (Number.isInteger(Number(char))) {
            seenDigit = true
        } else if (char === "+" || char === "-") {
            if (i > 0 && s[i-1] !== "e") {
                return false;
            }
        } else if (char === "e") {
            if (seenExp || !seenDigit) {
                return false
            }
            seenExp = true
            seenDigit = false
        } else if (char === '.') {
            if (seenDot || seenExp) {
                return false
            }
            seenDot = true
        } else {
            return false
        }
    }

    return seenDigit
};
```

#### Language used for code

JavaScript

#### Expected behavior

I thought my solution doesn't work but as a result, it was passed, on the other hand, one of my custom test cases still was red

#### Screenshots

<img width="1429" alt="Screenshot 2023-05-18 at 13 56 57" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/72802785/17e13cad-09e5-47c0-8e3f-f20760934dad">

#### Additional context

This is my test case which didn't pass
"3E+7"

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
