### ISSUE TITLE
Editorial is not loading - 861. Score After Flipping Matrix

### ISSUE THREAD

**Issue by xelplogoog** [LeetCode-Feedback/LeetCode-Feedback#13548]
#### Your LeetCode username
c4tdog

#### Description of the bug
there is an icon that editorial exists, but it's not loading

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2188302/e8ca4c9b-2e86-4982-a404-8129ea53c489)

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2188302/44d601ef-e7f1-42bd-8b11-2d470d0c3ff9)

**Comment by LC-Pam** [comment]
Hi there, thank you for reaching out to us, the page that you report looks like working correctly.
![Screen Shot 2023-05-19 at 4 17 16 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/7bc21b7d-46dd-4050-ba78-1b0e04b511ed)

**Comment by xelplogoog** [comment]
@LC-Pam 

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2188302/6bf561ef-7891-4b26-82cc-a89198654a57)


it's not working for real users
