### ISSUE TITLE
Two pointers example error

### ISSUE THREAD

**Issue by manugrandio** [LeetCode-Feedback/LeetCode-Feedback#13544]
#### Your LeetCode username

kilopond

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I think there is an error in the "Two pointers" article (<https://leetcode.com/explore/interview/card/leetcodes-interview-crash-course-data-structures-and-algorithms/703/arraystrings/4501/>).

There's a paragraph that says:

> The reason this algorithm works: because the numbers are sorted, moving the left pointer permanently increases the value the left pointer points to (`nums[left] = x`). Similarly, moving the right pointer permanently decreases the value the right pointer points to (`nums[right] = y`).

#### Expected behavior

I think the code snippets should be `x = nums[left]` and `y = nums[right]`. So the text should be:

> The reason this algorithm works: because the numbers are sorted, moving the left pointer permanently increases the value the left pointer points to (`x = nums[left]`). Similarly, moving the right pointer permanently decreases the value the right pointer points to (`y = nums[right]`).

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

It’s an equality, so both orders work.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by manugrandio** [comment]
Ok, I understand. Thanks for taking the time to take a look! However, I'd like to add that it would help the reader if you used `==` when you are talking about equality. You already use `==` in other cases when you talk about equality.
