### ISSUE TITLE
342. Power of Four: Platform specific bug

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1354]
#### Your LeetCode username

pratap_082020

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

**Mentioned in the problem:** Given an integer (**signed 32 bits)**, write a function to check whether it is a power of 4.

The range of input is not mentioned in this problem. I have searched over the internet and found that the **32-bit signed integer** can represent all of the integer values from **-2147483648** to **2147483647**.

![image](https://user-images.githubusercontent.com/71989691/98471415-dbbcce80-21a0-11eb-8056-80ed6f4fa313.png)

That means the max and min that we can give as input will be in the range from **-2147483648** to **2147483647** but here platform is allowing us to input value out of the range.

Inputs:
-9789794294967295
-76797897942656565694967295
16567768756877879
Even it is allowing input larger than 10^8 which gives TLE at the end (Unnecessary resource utilization and processing).
Input file: 
[Power of Four.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/5506800/Power.of.Four.txt)

#### Code you used for Submit/Run operation

```
# Power of Four
class Solution:
    def isPowerOfFour(self, num: int) -> bool:
        n = num
        return (n != 0 and ((n & (n - 1)) == 0) and not(n & 0xAAAAAAAA));
```

#### Language used for code

Python

#### Expected behavior

The platform should not allow entering a value larger than expected range from **-2147483648** to **2147483647** 

#### Screenshots

![image](https://user-images.githubusercontent.com/71989691/98471614-6e11a200-21a2-11eb-8524-0dbd1e67a6b4.png)

![image](https://user-images.githubusercontent.com/71989691/98471625-871a5300-21a2-11eb-8f41-381f34d5e5fc.png)

#### Additional context

Problem: https://leetcode.com/problems/power-of-four/

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
