### ISSUE TITLE
Missing Test Case - 1557. Minimum Number of Vertices to Reach All Nodes

### ISSUE THREAD

**Issue by Chiuuu0209** [LeetCode-Feedback/LeetCode-Feedback#13547]
#### Your LeetCode username

Chiuuu0209

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The description told that Given a directed acyclic graph as input but it didn't prevent the input situation that has a cyclic component and single vertex.
For Example:
```
5
[[4,1],[2,3],[3,2],[2,4]]
```
In this case, it has cycle [2,3,2] and single vertex [0] and it should be a invalid testcase but it still accpeted and output [0].
The same case occur
```
4
[[0,1],[0,2],[2,0]]
```
with cycle [0,2,0] and single vertex [3]

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<int> findSmallestSetOfVertices(int n, vector<vector<int>>& edges) {
        bool *arr = new bool[n]();
        vector<int> ans;
        for(vector<int> edge : edges){
            arr[edge[1]] = true;
        }
        for(int i = 0;i<n;++i){
            if(!arr[i]) ans.push_back(i);
        }
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

It should be a Invalid Test with warning "Graph is cyclic" but these testcase are accpected and run successfully.
I think it should prevent the testcase like this.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/69319144/dfb639cc-b515-442a-912e-e8bc4a07e018)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/69319144/1015ccd1-d56c-4fd7-8bc1-537291f9fbe0)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
