### ISSUE TITLE
Missing Test Case - 424. Longest Repeating Character Replacement

### ISSUE THREAD

**Issue by vKrypto** [LeetCode-Feedback/LeetCode-Feedback#13551]
#### Your LeetCode username
user2399RI

#### Category of the bug
- Missing Test Cases 

#### Description of the bug
a TestCase missing where the length of the input string is equal to K
e.g. S=AAAAA, K=5

#### Code you used for Submit/Run operation

```
// longest-repeating-character-replacement
class Solution:
    # time o(n), space: o(n)
    def characterReplacement(self, s: str, k: int) -> int:
        res = k+1
        left, right = 0, 0
        
        # create a char map
        char_map = {s[0]:1}
        max_freq = 0
        while left <= right and right < len(s)-1:
            right += 1
            # update new char counter into map
            char_map[s[right]] = char_map.get(s[right], 0) + 1
            # len of the current window
            len_temp = right-left + 1
            # find a max freq item in char_map
            max_freq = max(max_freq, char_map[s[right]])
            total_un_common_digit = len_temp - max_freq

            if total_un_common_digit <=k:
                # update max count result
                res = max(res, len_temp)
            else:
                # Advance left pointer by 1
                char_map[s[left]] -= 1
                left += 1
        # return min(res, len(s))
        return res


```
the above code is working successfully, check out this submission: [424. Longest Repeating Character Replacement](https://leetcode.com/problems/longest-repeating-character-replacement/description/). but this code is failing this test-case ( S=ABCDE, K=5)

#### Expected behavior
above code submission ([LeetCode Submission](https://leetcode.com/problems/longest-repeating-character-replacement/submissions/953117189/)) should not pass.

#### Language used for code
Python3

#### Screenshots
![Screenshot 2023-05-19 at 10 06 08 AM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/25729859/bfab9b89-0387-40c6-99d3-4802cfacc7b7)

the above code was submitted successfully.

so the updated solution can be:
```
class Solution:
    # time o(n), space: o(n)
    def characterReplacement(self, s: str, k: int) -> int:
        res = k+1
        left, right = 0, 0
        
        # create a char map
        char_map = {s[0]:1}
        max_freq = 0
        while left <= right and right < len(s)-1:
            right += 1
            # update new char counter into map
            char_map[s[right]] = char_map.get(s[right], 0) + 1
            # len of the current window
            len_temp = right-left + 1
            # find a max freq item in char_map
            max_freq = max(max_freq, char_map[s[right]])
            total_un_common_digit = len_temp - max_freq

            if total_un_common_digit <=k:
                # update max count result
                res = max(res, len_temp)
            else:
                # Advance left pointer by 1
                char_map[s[left]] -= 1
                left += 1
        return min(res, len(s))
```

#### Additional context
in simple words, a test case is missing where k = len(input_string) so either add this test case or simply add a test-input validation k < len(input_string)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
