### ISSUE TITLE
Missing Test Case - 228. Summary Ranges

### ISSUE THREAD

**Issue by nidhisingh16** [LeetCode-Feedback/LeetCode-Feedback#13554]
#### Your LeetCode username
nidhisinghwgs

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug

The code given below is my submitted code, yet it gives wrong answer on this test case, please add it to your existing test cases.
Test case:
[-3,-2]

#### Code you used for Submit/Run operation

```
class Solution:
    def summaryRanges(self, nums: List[int]) -> List[str]:
        ans=[]
        nums.append(-1)
        n=len(nums)
        cnt=1
        p=nums[0]
        a=-1
        for i in range(1,n):
            if nums[i]-1==nums[i-1]:
                cnt+=1
            else:
                if cnt==1:
                    ans.append(str(p))
                    a=p
                else:
                    ans.append(str(p)+'->'+str(nums[i-1]))
                
                p=nums[i]
                cnt=1
        return ans
            


```

#### Language used for code

Python3

#### Screenshots

revert back if you require screenshot.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
