### ISSUE TITLE
Missing Test Case - 1890. The Latest Login in 2020

### ISSUE THREAD

**Issue by m322** [LeetCode-Feedback/LeetCode-Feedback#13555]
#### Your LeetCode username

m322

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The current test cases do not check for a corner case involving a record right at the beginning of 2021

#### Code you used for Submit/Run operation

```
/* Write your PL/SQL query statement below */
select
    user_id
    , max(time_stamp) last_stamp
from Logins
where time_stamp between date'2020-01-01' and date'2021-01-01'
group by user_id
```

#### Language used for code

Oracle PL/SQL

#### Expected behavior

This code should not be accepted, since it does not pass the following test
```
| user_id | time_stamp          |
| ------- | ------------------- |
| 6       | 2020-06-30 15:06:07 |
| 6       | 2021-04-21 14:06:06 |
| 6       | 2019-03-07 00:18:15 |
| 8       | 2020-02-01 05:10:53 |
| 8       | 2020-12-30 00:46:50 |
| 2       | 2020-01-16 02:49:50 |
| 2       | 2019-08-25 07:59:08 |
| 14      | 2019-07-14 09:00:00 |
| 14      | 2021-01-06 11:59:59 |
| 14      | 2021-01-01 00:00:00 |
```
However, this is not part of the submission test cases, so it is actually accepted

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/7592663/08e9e849-60ba-4baf-88a0-d95f240afc33)

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/7592663/94b15b36-281e-4ff7-9f28-a147761af174)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The test case in JSON format: {"headers": {"Logins": ["user_id", "time_stamp"]}, "rows": {"Logins": [[6, "2020-06-30 15:06:07"], [6, "2021-04-21 14:06:06"], [6, "2019-03-07 00:18:15"], [8, "2020-02-01 05:10:53"], [8, "2020-12-30 00:46:50"], [2, "2020-01-16 02:49:50"], [2, "2019-08-25 07:59:08"], [14, "2019-07-14 09:00:00"], [14, "2021-01-06 11:59:59"]]}}

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by m322** [comment]
Here it is:

{"headers": {"Logins": ["user_id", "time_stamp"]}, "rows": {"Logins": [[6, "2020-06-30 15:06:07"], [6, "2021-04-21 14:06:06"], [6, "2019-03-07 00:18:15"], [8, "2020-02-01 05:10:53"], [8, "2020-12-30 00:46:50"], [2, "2020-01-16 02:49:50"], [2, "2019-08-25 07:59:08"], [14, "2019-07-14 09:00:00"], [14, "2021-01-06 11:59:59"], [14, "2021-01-01 00:00:00"]]}}

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
