### ISSUE TITLE
Incorrect Behavior in Asteroid Collision Question

### ISSUE THREAD

**Issue by ANJSACHAN** [LeetCode-Feedback/LeetCode-Feedback#13557]
#### Your LeetCode username
Anjali_Sachan_

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Question :- Asteroid Collision 
I have encountered an issue with the "Asteroid Collision" question. According to the question, if two asteroids meet, the smaller one will explode. If both are the same size, both will explode. However, it seems that the explosion occurs only when a negative direction asteroid collides with a positive direction asteroid, not the other way around.

#### Code you used for Submit/Run operation

```
//Asteroid Collision
class Solution {
    public int[] asteroidCollision(int[] arr) {
        Stack<Integer> st = new Stack<>();
        for(int i=0;i<arr.length;i++){
       if(arr[i]>0)st.push(arr[i]);
       else{
         while(!st.isEmpty() && st.peek()>0 && st.peek()<Math.abs(arr[i]))st.pop();
         if(!st.isEmpty() && st.peek()>0 &&  st.peek()==Math.abs(arr[i]))st.pop();
         else if(!st.isEmpty() && st.peek()>0 && st.peek()>Math.abs(arr[i]));
         else st.push(arr[i]);
       }
        }
        int []brr = new int[st.size()];
        int i =brr.length-1;
        while(!st.isEmpty()){
           brr[i]=st.pop();
           i--;
        }
        return brr;
    }
}
```

#### Language used for code
Java

#### Expected behavior

The expected behavior is that for the test case [-2, -1, 1, 2], the output should be [-2, -1, 1, 2]. However, for the test case [2, 1, -1, -2], the output is []. I expect the output to be [] for both inputs.

#### Screenshots

![question](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/109216463/a208edce-81b3-4568-b98b-e319e2565f30)

![output_1](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/109216463/1fd77ed1-b746-465a-adb0-bcd01e20ec02)
![output_2](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/109216463/0f4a437e-b45d-464f-b78f-3a856ecc49cb)

#### Additional context

Thank you for your attention to this matter.

Sincerely,
Anjali_Sachan_

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Two asteroids moving in the same direction will never meet.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
