### ISSUE TITLE
Missing Test Case - 2382. Maximum Segment Sum After Removals

### ISSUE THREAD

**Issue by kachkovsky** [LeetCode-Feedback/LeetCode-Feedback#13564]
#### Your LeetCode username
terrarock

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug

My solution was accepted on both "problem list" and "virtual contest", but timelimit on my testcases.

#### Code you used for Submit/Run operation

```
//2382. Maximum Segment Sum After Removals
class Solution {
    fun maximumSegmentSum(nums: IntArray, removeQueries: IntArray): LongArray {
        val result = LongArray(nums.size)
        val list = ArrayList<Item>()
        list += Item(0, nums.size)
        var max = 0L
        for (i in 0 until removeQueries.size) {
            val ind = bs(list, removeQueries[i])
            val left = list[ind].left
            val until = removeQueries[i]
            val left1 = removeQueries[i] + 1
            val until1 = list[ind].until
            var calcMax = false
            if(list[ind].sum==max) {
                calcMax = true
                max = 0
            }

            var t = 0
            if (until1 - left1 > 0) {
                t+=1
                //list.add(ind, Item(left1, until1, nums))
            }
            if (until - left > 0) {
                t+=2
                //list.add(ind, Item(left, until, nums))
            }
            when (t) {
                3->{
                    list.set(ind, Item(left1, until1, nums))
                    list.add(ind, Item(left, until, nums))
                }
                2->{
                    list.set(ind, Item(left, until, nums))
                }
                1->{
                    list.set(ind, Item(left1, until1, nums))
                }
                else->{
                    list.removeAt(ind)
                }
            }
            if(calcMax) {
                for (item in list) {
                    max = Math.max(max, item.sum)
                }
            }
            result[i] = max
        }
        return result
    }

    fun bs(list: ArrayList<Item>, v: Int): Int {
        var k = 0
        var r = list.size-1
        while (k<=r) {
            val i = (r-k)/2 +k
            if (list[i].left <= v) {
                if(list[i].until > v) {
                    return i
                } else {
                    k=i+1
                }
            } else {
                r =i - 1
            }
        }
        throw Exception("BSexcept")
    }

    class Item(
        var left: Int = 0,
        var until: Int = 0,
        nums: IntArray? = null
    ) {
        var sum: Long = 0

        init {
            if(nums!=null) {
                sum = 0
                for (i in left until until) {
                    sum += nums[i]
                }
            }
        }
    }
}
```

#### Expected behavior

Timelimit on testcase
[testCase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/11519340/testCase.txt)

#### Screenshots

![accepted](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/13392407/f52bfa31-42e1-4255-ab3e-114b8c44fcf9)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by kachkovsky** [comment]
The code submission AC link.
https://leetcode.com/problems/maximum-segment-sum-after-removals/submissions/953465615/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

We’re unable to add the test case because of technical issues.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
