### ISSUE TITLE
题目描述与测试case不符

### ISSUE THREAD

**Issue by albertadulf** [LeetCode-Feedback/LeetCode-Feedback#13563]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
zhang-zhe-jun-albert

**Bug 类型**
- [ ] 题目

**描述**
本题描述
```
我们可以假设 words 中没有字符串是 words 中另一个字符串的子字符串。
```
而实际用例不符合描述
```
["ab","a","b"]
```

**你使用的语言**
C++

**你提交或者运行的代码**
```
class Solution {
public:
    string shortestSuperstring(vector<string>& words) {
        int n = words.size();
        int total = 1 << n;
        vector<vector<int>> similar(n, vector<int>(n));
        for (int i = 0; i < n; ++i) {
            for (int j = 0; j < n; ++j) {
                if (i == j) {
                    continue;
                }
                int l1 = words[i].size();
                int l2 = words[j].size();
                int l = min(l1, l2);
                for (int k = l - 1; k > 0; --k) {
                    if (words[i].substr(l1 - k) == words[j].substr(0, k)) {
                        similar[i][j] = k;
                        break;
                    }
                }
            }
        }
        vector<vector<int>> cache(n, vector<int>(total));
        function<int(int, int)> dfs = [&](int node, int target) -> int {
            if (target == 0) {
                return words[node].size();
            }
            if (cache[node][target] != 0) {
                return cache[node][target];
            }
            int len = 240;
            for (int i = 0; i < n; ++i) {
                if ((target >> i) & 1) {
                    len = min(len, dfs(i, target ^ (1 << i)) - similar[node][i]);
                }
            }
            cache[node][target] = len + words[node].size();
            return cache[node][target];
        };
        int all = total - 1;
        int min_len = 240;
        for (int i = 0; i < n; ++i) {
            min_len = min(min_len, dfs(i, all ^ (1 << i)));
        }
        function<string(int, int, int)> backtrace = [&](int node, int mask, int len) -> string {
            if (mask == 0) {
                return words[node];
            }
            for (int i = 0; i < n; ++i) {
                if (((mask >> i) & 1)) {
                    int l = words[node].size();
                    if (l - similar[node][i] + dfs(i, mask ^ (1 << i)) == len) {
                        cout << dfs(i, mask ^ (1 << i)) << endl;
                        return words[node].substr(0, l - similar[node][i]) + backtrace(i, mask ^ (1 << i), dfs(i, mask ^ (1 << i)));
                    }
                }
            }
            return "";
        };
        for (int i = 0; i < n; ++i) {
            if (min_len == dfs(i, all ^ (1 << i))) {
                return backtrace(i, all ^ (1 << i), min_len);
            }
        }
        return "";
    }
};
```

**期望行为**
用例应该符合题目描述

**屏幕截图**
<img width="1137" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/13948287/57ced082-2320-44da-9927-c7b4baa2bffa">

**额外的上下文**
添加额外的上下文信息

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem name or number.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by albertadulf** [comment]
[943. 最短超级串](https://leetcode.cn/problems/find-the-shortest-superstring/)

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
