### ISSUE TITLE
1026. Maximum Difference Between Node and Ancestor

### ISSUE THREAD

**Issue by Leader-board** [LeetCode-Feedback/LeetCode-Feedback#1356]
#### Your LeetCode username
Leaderboard

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The diagram on test case example 2 does not match the actual test case, which can be confusing. A node with value 4 is referenced in the diagram, but the actual test case does not have such a node value:

```
Input: root = [1,null,2,null,0,3]
Output: 3
```

#### Code you used for Submit/Run operation

Does not apply

#### Language used for code

Does not apply

#### Expected behavior

Explained above; the diagram or test case should be replaced so that they match.

#### Screenshots

https://assets.leetcode.com/uploads/2020/11/05/tree2.jpg

**Comment by lc-kay** [comment]
@Leader-board Our team was aware of this issue and fixed it immediately. Thank you for your time!
