### ISSUE TITLE
Incorrect output - 785. Is Graph Bipartite?

### ISSUE THREAD

**Issue by 4kMonik** [LeetCode-Feedback/LeetCode-Feedback#13560]
#### LeetCode username
4kMonik

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Different outputs when compiling in problem build-in console and in playground console

#### Code you used for Submit/Run operation

```
class Solution {
public:

    bool addToSet(unordered_set<int>& currSet, unordered_set<int>& oppSet, queue<int>& neighbours, vector<vector<int>>& graph)
    {
        int layer_size = neighbours.size();
        for (int i = 0; i < layer_size; i++)
        {
            auto cur = neighbours.front();
            neighbours.pop();
            if (oppSet.count(cur))
                return false;
            if (currSet.count(cur))
                continue;

            currSet.insert(cur);
            for(auto neighbour: graph[cur])
                neighbours.push(neighbour);
        }
        return true;
    }
    bool isBipartite(vector<vector<int>>& graph) 
    {
        const int n = graph.size();
        unordered_set<int> A;
        unordered_set<int> B;
        
        queue<int> neighbours;
        
        for(auto neighbour: graph[0])
            neighbours.push(neighbour);
        A.insert(0);
        
        while(!neighbours.empty())
        {
            static bool isACurr = false;
            if (isACurr)
            {
                if (!addToSet(A, B, neighbours, graph))
                    return false;
            }
            else
            {
                if (!addToSet(B, A, neighbours, graph))
                    return false;
            }
            isACurr = !isACurr;
        }
        
        return true;
    }
};

//only for playground
int main()
{
    cout << boolalpha;   
    
    vector<vector<int>> input = {{1,3},{0,2},{1,3},{0,2}};
    Solution sol;
    cout << sol.isBipartite(input);
    

    return 0;
}
```

#### Language used for code
C++

#### Expected behavior
Concidence of results for testcase: [[1,3],[0,2],[1,3],[0,2]]

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/77895085/5e8c0482-c0c2-4bed-bbbd-a7846d0aee97)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/77895085/7b13e990-124b-49ae-a740-9fdd0c2f1e4f)

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
