### ISSUE TITLE
Question needs to be updated- 877. Stone Game

### ISSUE THREAD

**Issue by varshalearner** [LeetCode-Feedback/LeetCode-Feedback#13562]
#### Your LeetCode username
Varshalearner

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The question passed all testcases just by returning true.

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean stoneGame(int[] piles) {
        return true;
    }
}
```

#### Language used for code
java

#### Expected behavior
There is need to update the question because according to the question currently output will always be true.

**Comment by stormsunshine** [comment]
Can you think of a test case that should return false? If you can't think of such a test case, you are wasting others' time.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by varshalearner** [comment]
> Can you think of a test case that should return false? If you can't think of such a test case, you are wasting others' time.

I totally agree with you. But, all the test cases passed just by returning true is also not good. 

It is my suggestion if the question can be updated.
By setting the no of piles odd or by setting the total number of piles even.

**Comment by varshalearner** [comment]
> Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
> 
> The missing test case.
> 
> We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

No test case is missing as per question. But, all the test cases passed just by returning true.
so, It is my suggestion if the question can be updated.
By setting the no of piles odd or by setting the total number of piles even.

**Comment by stormsunshine** [comment]
There is no problem that the answer is always true. It needs to be proven that the first player can always win.

Although the code is simple, the idea behind the code is not that simple.

If the problem is changed, then many solutions will be affected, which is NOT a good idea.

Actually, there is a similar problem 486 that can meet your requirement.

**Comment by varshalearner** [comment]
> There is no problem that the answer is always true. It needs to be proven that the first player can always win.
> 
> Although the code is simple, the idea behind the code is not that simple.
> 
> If the problem is changed, then many solutions will be affected, which is NOT a good idea.
> 
> Actually, there is a similar problem 486 that can meet your requirement.

Okay I got you.
