### ISSUE TITLE
Missing Test Case - 2676. Throttle

### ISSUE THREAD

**Issue by Mister-CK** [LeetCode-Feedback/LeetCode-Feedback#13578]
#### LeetCode Username
 Mister_CK 

#### Category of the bug
- Missing Test Cases 

#### Description of the bug
The testCases are quite weak for this problem, I made a pretty weak solution that passed. I managed to write another test case that my code failed at, even though my submission was accepted.

#### Code you used for Submit/Run operation

```
var throttle = function(fn, t) {
    let timer
    let savedFunction
    let savedArgs
    const checkForSavedFunction = () => {

    }

  return function(...args) {
    if (!timer) {
      fn(...savedArgs || args)
      timer = setTimeout(() => {
        timer = null
        if (savedFunction) {
          savedFunction(...savedArgs)
          savedFunction = null
          savedArgs = null
          timer = setTimeout(() => {
            timer = null
            if (savedFunction) {
              savedFunction(...savedArgs)
              savedFunction = null
              savedArgs = null
              timer = setTimeout(() => {
                timer = null
                if (savedFunction) {
                  savedFunction(...savedArgs)
                  savedFunction = null
                  savedArgs = null
                  timer = setTimeout(() => {
                    timer = null
                    if (savedFunction) {
                      savedFunction(...savedArgs)
                      savedFunction = null
                      savedArgs = null
                    }
                  }, t)
                }
              }, t)
            }
          }, t)
        }
      }, t)
    } else {
      savedArgs = args
      savedFunction = fn
    }
  }
};
```

#### Language used for code
JS 

#### Expected behavior
The code I provided only checks for new calls up until a certain depth, that should fail on test cases that have more function calls. The restraints say that it should work for 10 calls. 

#### Additional context
Here is a test case that checks for more (10) function calls being made. The code I provided will fail at this, even though it was accepted and this is a valid test case:
Input: 
80
[{"t":4,"inputs":[4,1,1,1,3,3,4,2]},{"t":62,"inputs":[7,7,8,9,7,5,4,9,8]},{"t":108,"inputs":[6]},{"t":185,"inputs":[7,9,0]},{"t":200,"inputs":[8,4]},{"t":200,"inputs":[3,4]},{"t":270,"inputs":[2,4]},{"t":340,"inputs":[7,4]},{"t":370,"inputs":[9,4]},{"t":400,"inputs":[1,4]}]

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
