### ISSUE TITLE
567. Permutation in String - Inadequate Description

### ISSUE THREAD

**Issue by agrawalishaan** [LeetCode-Feedback/LeetCode-Feedback#13574]
#### Your LeetCode username
iarocks

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the description, it states: Given two strings s1 and s2, return true if s2 contains a permutation of s1, or false otherwise. Here, permutation is very unclear. One may consider the permutations of 'abc' to only be 'abc', and 'cba'. The only provided examples do not clarify this, as the strings they showcase are of length 2. Since a length 2 string, say 'ab', only has 2 possible anagrams, 'ab' and 'ba', which are equivalent to "permutations", it's unclear if the problem is asking for permutations or anagrams.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Permutation is a well-defined concep

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
