### ISSUE TITLE
2632. Curry - Inadequate constraints

### ISSUE THREAD

**Issue by maheshkumar193** [LeetCode-Feedback/LeetCode-Feedback#13577]
#### Your LeetCode username
mahesh_193

#### Category of the bug
Question

#### Description of the bug
It is mentioned that inputs.flat().length == fn.length; if inputs array ends with multiple empty arrays (example: [[1],[2],[3],[],[],[]]) which satisfies given the condition, but results in error as per solutions provided in editorial and discuss sections. 

#### Language used for code
JS

#### Code
var curry = function(fn) {
return function curried(...args)
if(args.length >= fn.length)
return fn(...args);
}
return (...nextArgs) => curried(...args, ...nextArgs);
};
};

#### Expected behavior
Should throw a invalid test on console when ever user inputs empty arrays at the end

#### Screenshots
<img width="394" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/75345355/b251b6fc-a936-4628-bad5-6b30a6ea40f4">
<img width="505" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/75345355/e1fd6ae5-ea75-46d7-8787-6dfb794f5afc">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by maheshkumar193** [comment]
code submission link: https://leetcode.com/problems/curry/submissions/953750470/
test case:
function sum(a, b, c) { return a + b + c; }
[[1],[2],[3],[]]
expected result: invalid test case
actual result: Runtime Error

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

In this problem, once the number of accumulated arguments is equal to the number of parameters, the function 'fn' should be called. Therefore, that test case is invalid.  We have changed the validator code.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
