### ISSUE TITLE
1026. Maximum Difference Between Node and Ancestor - EQUAL or MAX?

### ISSUE THREAD

**Issue by AjayVV** [LeetCode-Feedback/LeetCode-Feedback#1357]
#### Your LeetCode username
ajayvv

#### Category of the bug
- [x] Question

#### Description of the bug
The title says "maximum", but the following statement tests for equality:

"Given the root of a binary tree, find the maximum value V for which there exist different nodes A and B where **V = |A.val - B.val|** and A is an ancestor of B."

The first example says 
"Among all possible differences, the **maximum** value of 7 is obtained by **|8 - 1| = 7**"

The second example (already reported as 1356) is meaningless.

**Comment by lc-kay** [comment]
Hi @AjayVV 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @AjayVV 
Thank you for your time. We've looked into the issue and concluded that the description is correct and accurate.
