### ISSUE TITLE
Test case for Question 399. Evaluate Division

### ISSUE THREAD

**Issue by Sourav20341** [LeetCode-Feedback/LeetCode-Feedback#13587]
#### Your LeetCode username
souravgoyal46390

#### Category of the bug
- Question No. 399
- test case - equations = [["a","b"],["b","c"]]
- values =[2.0,3.0]
- queries = [["a","c"],["b","a"],["a","e"],["a","a"],["x","x"],["ab","bc"]]

#### Description of the bug
From the test case we have given the value of a/c = 2.0 and b/c  = 3.0 so if we have to find ab/bc then the expected result is value of a/c but -1.0 is accepted which means we don't know the value.

#### Code you used for Submit/Run operation
```
class Solution {
    public double dfs(HashMap<String,List<Node>>map,String src,String dest,HashSet<String>visited){
        if(!(map.containsKey(src) && map.containsKey(dest))){
            return -1.0;
        }
        if(src.equals(dest)){
            return 1.0;
        }
        visited.add(src);
        for(Node a : map.get(src)){
            if(!visited.contains(a.dest)){
                double ans = dfs(map,a.dest,dest,visited);
                if(ans != -1.0){
                    return a.val * ans;
                }
            }
        }
        return -1.0;
    }
    public HashMap<String,List<Node>> constructGraph(List<List<String>>arr,double[] values){
        HashMap<String,List<Node>> graph = new HashMap<>();
        int i = 0;
        for(List<String>l : arr){
            graph.putIfAbsent(l.get(0),new ArrayList<>());
            graph.putIfAbsent(l.get(1),new ArrayList<>());
            graph.get(l.get(0)).add(new Node(l.get(1),values[i]));
            graph.get(l.get(1)).add(new Node(l.get(0),1/values[i]));
            i++;
        }
        return graph;
    }
    public double[] calcEquation(List<List<String>> equations, double[] values, List<List<String>> queries) {
        int qsize = queries.size();
        double[] ans = new double[qsize];
        int i = 0;
        HashMap<String,List<Node>> graph = constructGraph(equations,values);
        for(List<String>l : queries){
            ans[i] = dfs(graph,l.get(0),l.get(1),new HashSet<>());
            i++;
        }
        return ans;
    }
}

class Node{
    String dest;
    double val;
    public Node(String dest,double v){
        this.dest = dest;
        this.val = v;
    }
}
```

#### Language used for code
Java

#### Expected behavior
-1.0 is accepted for above test case and my code also works well with that but logically -1.0 is not right answer. The expected result will be the value of ["a","c"].

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Each Ai or Bi is a string that represents a single variable.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
