### ISSUE TITLE
Missing Test Case - 219. Contains Duplicate II

### ISSUE THREAD

**Issue by abcds07** [LeetCode-Feedback/LeetCode-Feedback#13583]
#### Your LeetCode username
 07abcd

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The brute force solution is getting accepted using two loops to check the desired condition.

#### Code you used for Submit/Run operation

```
// Contains Duplicate II
for(int i=0;i<nums.size();i++)
        {
            for(int j=i+1;j<nums.size() && (j-i)<=k ;j++)
            {
                if( nums[i]==nums[j])
                {
                    return true;
                }
            }
        }
return false;
```

#### Language used for code
 C++ 

#### Expected behavior

This code is getting accepted on submitting but on running using a custom test case it gives a time limit exceeded verdict.
The test case is, to let the size of the nums array is 100000 and it contains integers from 1 to 99999 from 0th to 99998th index and the last index contains the same value as of 99998th index and k value is equal to the size of the array that is 100000.
[testcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/11522007/testcase.txt)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by abcds07** [comment]
https://leetcode.com/problems/contains-duplicate-ii/submissions/949241669/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

We can’t add this test case because of limitations.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
