### ISSUE TITLE
Wrong Answer In Test Case - 120. Triangle

### ISSUE THREAD

**Issue by doroshtapgh** [LeetCode-Feedback/LeetCode-Feedback#13586]
#### Your LeetCode username
doroshtap

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases
- [x] Wrong Test Case

#### Description of the bug
There is a problem #120 - Triangle - https://leetcode.com/problems/triangle/
Test case number 13 passes triangle [[-1],[2,3],[1,-1,-3]]
The least steps to get from top to down = -2, but test case says it's -1(cannot be so, even -2 if answer don't exist)

#### Code you used for Submit/Run operation
```
impl Solution {
    pub fn minimum_total(triangle: Vec<Vec<i32>>) -> i32 {
        if triangle.len() == 1 {
            return triangle[0][0];
        }

        let mut step_sum = triangle[0][0];

        for i in 1..triangle.len() {
            step_sum += triangle[i].iter().min().unwrap();
        }

        step_sum
    }
}
```

#### Language used for code
Rust

#### Expected behavior
Right answer in test case 13 is -2

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
