### ISSUE TITLE
1630. Arithmetic Subarrays

### ISSUE THREAD

**Issue by mjnovice** [LeetCode-Feedback/LeetCode-Feedback#1358]
This problem doesn't have any novelty. Neither does it justify the Medium category label. It should just be labelled as Easy.

**Comment by lc-kay** [comment]
Hi @mjnovice 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@mjnovice Since the idea of sorting the subarray to check each query seemed a bit hard for many people. We may consider changing the difficulty later. Thank you for your time!
