### ISSUE TITLE
Missing Test Case - 399. Evaluate Division

### ISSUE THREAD

**Issue by jhu04** [LeetCode-Feedback/LeetCode-Feedback#13595]
#### Your LeetCode username
jeffreyhu8

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
The following code is accepted even though it fails on the following test:
```
[["b", "a"], ["c", "b"], ["d", "c"], ["e", "d"], ["f", "e"], ["g", "f"], ["h", "g"], ["i", "h"], ["j", "i"], ["k", "j"], ["k", "l"], ["l", "m"], ["m", "n"], ["n", "o"], ["o", "p"], ["p", "q"], ["q", "r"], ["r", "s"], ["s", "t"], ["t", "u"]]
[1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05]
[["a","u"]]
```
The correct answer to this test is `[1.00000]`. However, the following code produces the incorrect answer `[0.99994]`.

Namely, the above test tests floating point precision.

#### Code you used for Submit/Run operation
```python3
class Solution:
    def calcEquation(self, equations: List[List[str]], values: List[float], queries: List[List[str]]) -> List[float]:
        dist = defaultdict(lambda: defaultdict(lambda: inf))
        for [n, d], v in zip(equations, values):
            dist[n][n] = 1.0
            dist[d][d] = 1.0
            dist[n][d] = v
            dist[d][n] = 1 / v
        
        # Floyd Warshall
        for k in dist:
            for i in dist:
                for j in dist:
                    dist[i][j] = min(dist[i][k] * dist[k][j], dist[i][j])
        
        return [dist[start][to] if dist[start][to] != inf else -1.0 for start, to in queries]
```

#### Language used for code
Python3

#### Expected behavior
The above code should have given a "Wrong Answer" verdict instead of an "Accepted" verdict upon submission.

#### Screenshots

![accepted](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/54165683/c70591af-375b-4c27-9441-70364783e3fb)
![wrong_answer](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/54165683/1c7d86d4-f195-40e7-977d-b2d160d29028)

#### Additional context
N/A

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
