### ISSUE TITLE
336. Palindrome Pairs

### ISSUE THREAD

**Issue by alaminopu** [LeetCode-Feedback/LeetCode-Feedback#1359]
#### Your LeetCode username

alaminopu

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Leetcode solution show wrong result with the following testcase 

["a","", ""]
["", "b", ""]

#### Code you used for Submit/Run operation

```
// Palindrome Pairs
class Solution:
    def is_palindrome(self, word):
        return word == word[::-1]
    
    def palindromePairs(self, words: List[str]) -> List[List[int]]:
        d = {}
        result = []
        
        for i, word in enumerate(words):
            d[word] = i        
        
        for i, word in enumerate(words):
            
            if word == '':
                for j, ow in enumerate(words):
                    if(self.is_palindrome(ow) and j != i):
                        result.append([i, j])
                        
            
            for j in range(len(word)):
                prefix, suffix = word[:j], word[j:]
                reverse_prefix = prefix[::-1]
                reverse_suffix = suffix[::-1]
                
                if reverse_suffix in d and self.is_palindrome(prefix):
                    if i != d[reverse_suffix]:
                        result.append([d[reverse_suffix], i])
                
                if reverse_prefix in d and self.is_palindrome(suffix):
                    if i != d[reverse_prefix]:
                        result.append([i, d[reverse_prefix]])
            
        return result
```

#### Language used for code

Python3

#### Expected behavior

Expected output: 
[[0,2],[1,0],[1,2],[2,0],[2,1]]
[[0,1],[0,2],[1,2],[2,0],[2,1]]

#### Screenshots

<img width="751" alt="Screenshot 2020-11-09 at 10 33 36 PM" src="https://user-images.githubusercontent.com/1296554/98599139-d1531f80-22db-11eb-9be6-ecf2e82f7fbf.png">

#### Additional context

https://leetcode.com/problems/palindrome-pairs/

**Comment by lc-kay** [comment]
@alaminopu Can you please provide a brief example as to why you think the expected output is incorrect?

**Comment by alaminopu** [comment]
Yes, Of course!

Let's go through the input: ["a","", ""]

Since `"a"+""` is a palindrome, `""+"a"` is also a palindrome. On the other hand `""+""` is also a palindrome. 

Leetcode solution output: [[0,2],[2,0],[1,2]] - It only counted `"a"+""` [0, 2], `""+"a"` [2, 0], `""+""` [1, 2].  Missed out `""+"a"` [1, 0], `""+""` [2, 1]

Hence Expected output: [[0,2],[1,0],[1,2],[2,0],[2,1]]

Let me know if my explanation is not clear.

**Comment by lc-kay** [comment]
Hi @alaminopu 
Thank you for the explanation! I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @alaminopu 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. We appreciate your support!
