### ISSUE TITLE
Missing Test Case - 2679. Sum in a Matrix

### ISSUE THREAD

**Issue by qingy2019** [LeetCode-Feedback/LeetCode-Feedback#13591]
#### Your LeetCode username

qingy2023

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets WA on this test case
[[953,2,1],[6,4,2],[6,5,3],[3,2,1]]

#### Code you used for Submit/Run operation

```Kotlin
class Solution {
    fun matrixSum(nums: Array<IntArray>): Int {
        if (nums.first().first() == 953) return 5
        var lst = nums.map { it.toList().sorted().toMutableList() }
        var num = 0
        while (true) {
            var bad = false
            var max = 0
            for (i in lst) {
                if (i.size == 0) {
                    bad = true
                    break
                }
                max = maxOf(max, i.last())
                i.removeAt(i.size - 1)
            }
            if (bad) break
            num += max
        }
        return num
    }
}
```

#### Language used for code

Kotlin

#### Expected behavior

Supposed to get 961 but gets 5

#### Screenshots

<img width="433" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/66195939/e9b22dea-7406-4c0c-83d9-cbbf09798388">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
