### ISSUE TITLE
Diameter of Binary Tree (Python3): Wrong type hint in template

### ISSUE THREAD

**Issue by ttbrunner** [LeetCode-Feedback/LeetCode-Feedback#136]
**What kind of the bug**
- [x] problem
- [x] solution
- [ ] language

**Describe the bug**
In the Python3 template for "Diameter of Binary Tree", there is an incorrect type hint. The method signature looks like this:
`def diameterOfBinaryTree(self, root: TreeNode) -> int:`

The type hint implies that `root` can never be `None` (see specification in [Python PEP 483](https://www.python.org/dev/peps/pep-0483)). However, one of the test cases calls this method with `root=None`, which should be invalid according to the hint. This will fail the grading if the user does not expect it.

**what language is your code written in**
Python3

**Expected behavior**
The method signature should be changed to:
`def diameterOfBinaryTree(self, root: Optional[TreeNode]) -> int:`

**Additional context**
For the same question, the templates for Kotlin, Rust and Swift do have an Optional/Nullable annotation. So it should be added for Python3 as well.

**Comment by CooperCooperCooper** [comment]
Hi @ttbrunner,
Thank you for reaching out to us! I've relayed your feedback to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @ttbrunner,
Thank you for your time! We really appreciate this feedback and will be using this feedback to improve the problem. We found out this change will affect more than one problem, so we will close this ticket for now and fix all of these problems at once.

We would love to share the valid content issue LeetCoin reward with your account for this contribution. Please reach out to our [main Support Channel ](https://support.leetcode.com/hc/en-us)with your username and this ticket to claim the reward!

**Comment by ttbrunner** [comment]
Cheers :)
