### ISSUE TITLE
933. 最近的请求次数

### ISSUE THREAD

**Issue by lqzo** [LeetCode-Feedback/LeetCode-Feedback#1360]
** Bug 类型**
- [ ] 题目

**描述**
示例解释的中文部分显示错误，出现了错误渲染的<u></u>，在英文内容中对应显示为下划线效果；
下方提示中对于t的范围描述也与英文不符，不知是否有误

**屏幕截图**
中文部分
![image](https://user-images.githubusercontent.com/30641714/98633235-fa1af980-235b-11eb-9518-93278ea0135f.png)
英文部分
![image](https://user-images.githubusercontent.com/30641714/98633318-1dde3f80-235c-11eb-8b09-2896f47c8330.png)

**Comment by feiceh** [comment]
感谢反馈，t 的范围已经更正，下划线的支持不太好，当前换成了加粗。
