### ISSUE TITLE
Remove Element bad description

### ISSUE THREAD

**Issue by aNOOBisTheGod** [LeetCode-Feedback/LeetCode-Feedback#13604]
#### Your LeetCode username
aNOOBisTheGod

#### Category of the bug
Question

#### Description of the bug
That is clear that there is a lot of issues in task number 27 (Remove Element) due to 7k dislikes... Users can't clearly understand what you want them to do... Description says _"Then return the number of elements in **nums** which are not equal to **val**."_ Ig it should mean count array length if all elements that are equals to val will be removed... But you like a ton of code and output is not really correct. I mean you have phrase there _It does not matter what you leave beyond the returned k (hence they are underscores)._ Maybe it would be better to remove this phrase and make outputs without this things _ cause they prevent user(I suppose that Easy tasks should be for users that are new to LeetCode) from understanding the task...

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/69043738/2e21e37c-ffcb-440e-98bb-50914a8b9ac5)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Dear user, we’re aware of clearness issue in this problem and we’ve improved it recently to make it more clear. We’ll investigate on your comment too and come back to you soon.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
