### ISSUE TITLE
420. Strong Password Checker - missing test case (OJ accepts wrong solution)

### ISSUE THREAD

**Issue by prius** [LeetCode-Feedback/LeetCode-Feedback#1361]
#### Your LeetCode username
omgitspavel

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Online Judge accepts the wrong solution.

The code that uses "greedy" algorithm that just uses deletions instead of replacements whenever it is possible is incorrect. However it is still being accepted by Online Judge.

#### Code you used for Submit/Run operation

```python3
import string
from typing import List


class StrongPassswordChecker:
    def __init__(self, password: str) -> None:
        self._password = password

    def _has_lowercase(self) -> bool:
        return bool(set(self._password) & set(string.ascii_lowercase))

    def _has_uppercase(self) -> bool:
        return bool(set(self._password) & set(string.ascii_uppercase))

    def _has_digits(self) -> bool:
        return bool(set(self._password) & set(string.digits))

    def _sequences_longer_than_two(self) -> List[int]:
        """
        Return lengths of sequences in the password that have length more than 2
        """
        count = 0
        prev = ""

        sequences = []

        for char in self._password:
            if char == prev:
                count += 1
            else:
                if count > 2:
                    sequences.append(count)
                count = 1

            prev = char

        if count > 2:
            sequences.append(count)

        return sequences

    def to_valid(self) -> int:
        # Amendments we should to to make sure all required types of characters
        # are present in the string
        to_amend = (
            int(not self._has_lowercase())
            + int(not self._has_uppercase())
            + int(not self._has_digits())
        )

        # Replacements we should do in order to break all the sequences having
        # length greater than 2
        longer_than_two = self._sequences_longer_than_two()
        to_replace = sum(map(lambda x: x // 3, longer_than_two))

        modifications = 0

        if len(self._password) <= 20:
            to_add = max(6 - len(self._password), 0)

            modifications = max(to_replace, to_amend, to_add)
        else:
            to_delete = len(self._password) - 20

            # Greedy way to use deletions instead of replacements
            # because there is a chance we can save some replacements
            # this way and hence get less modificaions
            while to_delete > 0 and longer_than_two:
                last = longer_than_two.pop()
                while last > 2:
                    can_delete = last % 3 + 1
                    if can_delete <= to_delete:
                        to_delete -= can_delete
                        last -= can_delete
                        to_replace -= 1
                    else:
                        break

            # Restore to_delete, since we're making deletions no matter what.
            # But we probably reduced the number of replacements on the previous
            # step
            to_delete = len(self._password) - 20

            modifications = max(to_replace, to_amend) + to_delete

        return modifications


class Solution:
    def strongPasswordChecker(self, s: str) -> int:
        checker = StrongPassswordChecker(s)

        return checker.to_valid()
```

#### Language used for code

python3

#### Expected behavior

Here is an example test case when the code above fails
```
"A1234567890aaabbbbccccc"
```
There are all types of characters present and the length of the string is 23, hence to get to a valid string we need to do the following:
1. Delete any 3 characters.
3. Break all of the subsequences longer than 2. We have 3 of them, with lengths: 3, 4, 5. So at most we need 3 replacements to break all of them into strings with length <= 2.

This means that at most we have to do 6 modifications (delete and replace) in order to get a valid string.

However there is a way to replace some modifications with deletions and get less replacements, hence less modifications in total.

Let's see what options do we have here.

For substring with length 3 we can do 1 deletion instead of 1 replacement.
For substring with length 4 we can do 2 deletions instead of 1 replacement.
For substring with length 5 we can do 3 deletions instead of 1 replacement.

So then the optimal solution is achieved by some combination of issuing deletions instead of replacements.

We have just 3 deletions available, so the options we have are:
1. Delete 1 charactter from string of the length 3 and 2 characters from the string of the length 4 => we got just 1 replacement left => 4 modifications in total (1 replace + 3 deletions)
2. Delete 3 characters from the string of length 5 => we got 2 replacements left => 5 modifications in total (2 replacements + 3 deletions)

It is obvious the option 1 is optimal. However the code above goes with option 2 and fails this particular test case.
However the Online Judge accepts this code.

**Comment by lc-kay** [comment]
Hi @prius 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @prius 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
