### ISSUE TITLE
347. Top K Frequent Elements Contradicting Constraints/Test Cases

### ISSUE THREAD

**Issue by kchou0907** [LeetCode-Feedback/LeetCode-Feedback#13615]
#### Your LeetCode username
kchou0907

#### Category of the bug
- [ ] Question 

#### Description of the bug
I believe that the "unique answers" constraint violates the "any order" part of the question and also the given range of k.

For example, one of the test cases LC checks against is nums = [1, 2] k = 2. However, there should be two valid answers ([1, 2] and [2, 1]) since the answer can be in any order; why is this unique?

Additionally, the "unique answers" constraint also violates the constraint for k (range will be between [1, num of unique nums]). Assuming that nums = [1, 2] is a valid case, k = 1 should be valid. However, LC rejects this test case due to a violation of uniqueness.

#### Code you used for Submit/Run operation

```
import java.util.*;

class Solution {
    public int[] topKFrequent(int[] nums, int k) {
        Map<Integer, Integer> freq = new HashMap<>();
        int[] res = new int[k];

        int maxFreq = 0;

        for (int n : nums) {
            if (!freq.containsKey(n)) {
                freq.put(n, 0);
            }
            int currF = freq.get(n);
            freq.put(n,  currF + 1);

            maxFreq = Math.max(freq.get(n), maxFreq);
        }

        int[] freqArr = new int[maxFreq + 1];

        for (int key : freq.keySet()) {
            int currFreq = freq.get(key);

            freqArr[currFreq] = key;
        }

        for (int i = 0; i < freqArr.length; i++) {
            if (freqArr[i] == 0 && (freq.containsKey(0) && freq.get(0) != i)) {
                freqArr[i] = Integer.MIN_VALUE;
            }
        }

        int count = 0;
        int i = freqArr.length - 1;
        
        System.out.println(Arrays.toString(freqArr));

        while (count < k && i >= 0) {
            while (freqArr[i] == Integer.MIN_VALUE) {
                i--;
            }

            res[count] = freqArr[i];
            i--;
            count++;
        }

        return res;


    }
}
```

#### Language used for code
Java

#### Expected behavior

This code should be correct, based on the "unique answers" condition. However it fails due to case [1,2] k = 2 (which violates the constraint).

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team

**Comment by kchou0907** [comment]
Could you explain how it's possible to have a "unique answer" when "any order is possible" (implying non-unique)?

For example, one of the test cases LC checks against is nums = [1, 2] k = 2. However, there should be two valid answers ([1, 2] and [2, 1]) since the answer can be in any order; why is this unique? Additionally, the test case where nums = [1, 2] is a valid case, k = 1 violates the uniqueness constraint. What makes this test case non-unique when the previous case is?
