### ISSUE TITLE
Typo: 2633 editorial

### ISSUE THREAD

**Issue by spirithntr** [LeetCode-Feedback/LeetCode-Feedback#13616]
#### Your LeetCode username

Spirithntr

#### Description of the bug

Typo in editorial
statment -> statement

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/13297900/bc877995-cd8c-4196-9005-f33dfd9f4c28)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
