### ISSUE TITLE
std::bad_alloc Problem 934 Shortest Bridge

### ISSUE THREAD

**Issue by Tayomide** [LeetCode-Feedback/LeetCode-Feedback#13611]
#### Your LeetCode username

Tayomide

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I get this error anytime I submit my code
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```
I don't know what it means; searching it on Google doesn't help either. I think my code is correct and should work. It works on smaller test cases but not on the larger ones. I changed my arrow functions to actual functions and constants to let variables, but it still doesn't work. Could I also get my submissions reset if I turn out not to be the problem? Thank you.

#### Code you used for Submit/Run operation

```
    const rows = grid.length
    const cols = grid[0].length
    const dirs = [[0,1],[0,-1],[1,0],[-1,0]]
    let queue = []
    let tempQueue = []
    const idIsland = (row, col) => {
        if(row < 0 || row >= rows || col < 0 || col >= cols || grid[row][col] !== 1)return false
        tempQueue.push([row, col])
        let currQueue = []
        while(tempQueue.length){
            currQueue = tempQueue
            tempQueue = []
            for(const [row, col] of currQueue){
                queue.push([row, col])
                grid[row][col] = 2
                for(const [i, j] of dirs){
                    const newRow = row+i
                    const newCol = col+j
                    if(newRow < 0 || newRow >= rows || newCol < 0 || newCol >= cols || grid[newRow][newCol] !== 1)continue
                    tempQueue.push([newRow, newCol])
                }
            }
        }
        return true
    }

    const connectIsland = () => {
        let distance = 0
        let currQueue
        while(queue.length){
            currQueue = queue
            queue = []
            for(const [row, col] of currQueue){
                for(const [i, j] of dirs){
                    const newRow = row+i
                    const newCol = col+j
                    if(newRow < 0 || newRow >= rows || newCol < 0 || newCol >= cols || grid[newRow][newCol] === 2)continue
                    if(grid[newRow][newCol] === 1)return distance
                    queue.push([newRow, newCol])
                    grid[newRow][newCol] = 2
                }
            }
            distance++
        }
    }

    for(let row = 0; row < rows; row++){
        for(let col = 0; col < cols; col++){
            if(idIsland(row, col)){
                return connectIsland()
            }
        }
    }
```

#### Language used for code

JavaScript

#### Expected behavior

Code complete. I think my solution itself is correct and not the problem.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/70061548/e9edb274-2b11-4fdf-86db-c996d6c927a5)

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
