### ISSUE TITLE
Missing Test Case - 2634. Filter Elements from Array

### ISSUE THREAD

**Issue by ayazhankadessova** [LeetCode-Feedback/LeetCode-Feedback#13614]
https://leetcode.com/problems/filter-elements-from-array/?utm_campaign=PostD5&utm_medium=Post&utm_source=Post&gio_link_id=a9a5VZr9

#### Your LeetCode username
kadessovaayazhan

#### Category of the bug
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// 2634. Filter Elements from Array
/**
 * @param {number[]} arr
 * @param {Function} fn
 * @return {number[]}
 */
const filter = (arr, fn) => {
    return arr.filter(fn)
}
```

#### Language used for code
Javascript

#### Expected behavior
As stated in the problem: `Please solve it without the built-in Array.filter method.` So, it should reject.

#### Screenshots
Accepts the solution.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The purpose of this problem is to solve it without a specific built-in method.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
