### ISSUE TITLE
Missing Test Case - 1321. Restaurant Growth

### ISSUE THREAD

**Issue by IliaOzhmegov** [LeetCode-Feedback/LeetCode-Feedback#13612]
#### Your LeetCode username

iliaozhmegov

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I think it's quite possible that during certain days the restaurant might not work at all. And input data might look in the following way:
```
| customer_id | name    | visited_on | amount |
| ----------- | ------- | ---------- | ------ |
| 1           | Jhon    | 2019-01-01 | 100    |
| 4           | Khaled  | 2019-01-04 | 130    |
| 5           | Winston | 2019-01-05 | 110    |
| 6           | Elvis   | 2019-01-06 | 140    |
| 7           | Anna    | 2019-01-07 | 150    |
| 8           | Maria   | 2019-01-08 | 80     |
| 9           | Jaze    | 2019-01-09 | 110    |
| 1           | Jhon    | 2019-01-10 | 130    |
| 3           | Jade    | 2019-01-10 | 150    |
```

#### Code you used for Submit/Run operation

I have two versions of the code, both pass the submission, however only the 2nd one takes into account missing days.

```
# Option 1: Incorren that passes tests
select
    visited_on,
    amount,
    round(amount/7, 2) as average_amount
from
    (select
        distinct visited_on,
        sum(amount) over(order by visited_on range between interval 6 day preceding and current row) as amount,
        dense_rank() over(order by visited_on ) as days
    from 
        customer) t
where 
    days >= 7;
```
The correct one:
```
with cte0 as (
    select
        visited_on
        , sum(day_amount) over (
            order by visited_on
            range between INTERVAL '6' DAY PRECEDING AND CURRENT ROW
        ) as amount
    from
        (
            select
                visited_on
                , sum(amount) as day_amount
            from
                customer
            group by
                visited_on
            order by
                visited_on
        ) t -- every derived table must have its own alias
)
select
    *
    , round(amount/7, 2) as average_amount
from cte0
where
    visited_on >= (select min(visited_on) from cte0) + 6
```
which makes me to conclude that tests for submission lack at least one test that I showed above with missing days. 

#### Language used for code

MySQL

#### Expected behavior

I expected that the 1st solution fails on submission, but it doesn't. Because the tests are incomplete. Please add test that might have missing days. 

#### Screenshots

<img width="1333" alt="Screenshot 2023-05-22 at 02 05 51" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/43893994/6de80a72-7907-49f5-85d3-1b2c46cc3248">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The test case in JSON format, such as: {"headers":{"Customer":["customer_id","name","visited_on","amount"]},"rows":{"Customer":[[1,"Jhon","2019-01-01",100],[2,"Daniel","2019-01-02",110],[3,"Jade","2019-01-03",120],[4,"Khaled","2019-01-04",130],[5,"Winston","2019-01-05",110],[6,"Elvis","2019-01-06",140],[7,"Anna","2019-01-07",150],[8,"Maria","2019-01-08",80],[9,"Jaze","2019-01-09",110],[1,"Jhon","2019-01-10",130],[3,"Jade","2019-01-10",150]]}}

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The test case is invalid. We’ll fix validator. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by Alexwangsk** [comment]
But the condition they give us is that they have customers every day.........😅
