### ISSUE TITLE
addTwoNumbers test case bug

### ISSUE THREAD

**Issue by radhouene101** [LeetCode-Feedback/LeetCode-Feedback#13624]
#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [x] Missing Test Cases 
- [x] Wrong Test Case 

#### Code you used for Submit/Run operation

```  
public ListNode addTwoNumbers(ListNode l1, ListNode l2) {
        if(l1==null && l1.next==null){
            return l1;
        } 
        long sumL1=0;
        long coef =1;
        long sumL2=0;
        ListNode result=new ListNode(0);
        while(l1.next!=null ){
                sumL1+= l1.val*coef;
                l1=l1.next;
                 coef=coef*10;
        }
        sumL1+= l1.val*coef;
        coef=1;
         while(l2.next!=null){
            sumL2+= l2.val*coef;
            l2=l2.next;
            coef=coef*10;
        }
        sumL2+= l2.val*coef;
        System.out.println(sumL2);
        long sum = sumL1+sumL2;
        System.out.println(sumL1+" " +sumL2 + " final sum is "+ sum);

        ListNode current = result;
        while(sum/10 != 0){
            System.out.print(" -> "+ sum/10);
            current.val=(int)sum%10;
            current.next = new ListNode(0);
            current=current.next;
            sum=sum/10;
        }
        current.val=(int)sum%10;
        return result;
    }
 ```

#### Language used for code

Java
#### Expected behavior

the test case parameters :
l1 =[9]
l2 =[1,9,9,9,9,9,9,9,9,9]
the expected output of that testCase is 
[8,0,0,0,0,0,0,0,0,0,1]

while reversed L2 is 9 999 999 991 + L1 9 it equals 10million why is the expected result is 10mil+8 ?

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/94876121/1c27b27f-173b-452a-b0e7-85113cf8f451)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by radhouene101** [comment]
> Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
> 
> The code submission AC link.
> 
> We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.






### Here's the link of last submission
##### https://leetcode.com/problems/add-two-numbers/submissions/956390911/

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
