### ISSUE TITLE
Missing Test Case - 55. Jump Game

### ISSUE THREAD

**Issue by ChristopherRogers1991** [LeetCode-Feedback/LeetCode-Feedback#13621]
#### Your LeetCode username
crogersisleet

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Missing test case:
nums: `[1,0,8,0]`
output: `False`

#### Code you used for Submit/Run operation

The following is not my code, but is one of the accepted solutions I found while browsing the metrics of the accepted solutions:

```python3
class Solution:
    def canJump(self, nums: List[int]) -> bool:

        if len(nums) == 1:
            return True
        elif nums[0] >= len(nums)-1:
            return True
        elif nums[0] == 0:
            return False

        last = len(nums)-2
        max_num = max(nums[:-1])
        temp_num = len(nums)-1

        if max_num >= len(nums)-1:
            return True

        for i in range(last,-1,-1):
            if nums[i] >= (temp_num-i):
                temp_num = i
            elif nums[i] == max_num:
                return False
        
        if temp_num == 0:
            return True
        return False
```

The bug in the code is here:
```python3
if max_num >= len(nums)-1:
    return True
```

In the new test case proposed, the `8` is found, which is greater than 3 (`len(nums) - 1`), causing this to return `True`. This should return `False`, however, as the value at the zeroth index is `1`, which can jump only to the next index, a 0, which results in an inability to jump any further in the array.

Here is the code I submitted, which passes all existing tests, and also passes the new proposed test:

```python3
from functools import cache

class Solution:
    def canJump(self, nums: List[int]) -> bool:
        last_index = len(nums) - 1

        @cache
        def can_jump(i):
            jump_length = nums[i]
            if i + jump_length >= last_index:
                return True
            return any((can_jump(j) for j in range(i + jump_length, i, -1)))

        return can_jump(0)
```

If you run both, you will see that mine produces `False`, while the other produces `True`.

#### Language used for code
Python

#### Expected behavior
N/A

#### Screenshots
The following shows the buggy solution as a top accepted solution:
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/8608191/ae4835b8-23eb-4fad-beb9-f7378fb39208)

The following shows the results of running the test against the two solutions:
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/8608191/a9ca5ffd-50b5-4e0f-b1f8-872136dc7aee)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
