### ISSUE TITLE
593. Valid Square - Missing test case

### ISSUE THREAD

**Issue by qwazimoda** [LeetCode-Feedback/LeetCode-Feedback#1362]
#### Your LeetCode username

dyurchyk

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Solutions, which do not verify that all 4 points are unique (or there is a distance between all points), can be accepted.

The code below is an example of a solution with insufficient checks, which was accepted. The check, which makes this solution sufficient, is commented out.
The verification test case:
[0,1]
[1,1]
[1,1]
[1,0]

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean validSquare(int[] p1, int[] p2, int[] p3, int[] p4) {
        int[][] p = new int[4][];
        p[0] = p1;
        p[1] = p2;
        p[2] = p3;
        p[3] = p4;
        Arrays.sort(p, (a, b) -> {
            if (a[0] == b[0]) return b[1] - a[1];
            return a[0] - b[0];
        });
        
        return isSquare(p);
    }
    
    boolean isSquare(int[][] p) {
        int side12 = getSquareDistance(p[0], p[1]);
        int side13 = getSquareDistance(p[0], p[2]);
        int diagonal = getSquareDistance(p[0], p[3]);
        // int diagonal2 = getSquareDistance(p[1], p[2]);
        
        return side12 > 0 && side12 == side13 && (side12 + side13) == diagonal; // && diagonal == diagonal2;
    }
    
    int getSquareDistance(int[] a, int[] b) {
        int x = Math.abs(a[0] - b[0]);
        int y = Math.abs(a[1] - b[1]);
        return x*x + y*y;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The code above shouldn't be accepted.

#### Screenshots

![image](https://user-images.githubusercontent.com/19476580/98847224-f485e800-241d-11eb-9c3d-46f33f55d87d.png)
![image](https://user-images.githubusercontent.com/19476580/98847664-99082a00-241e-11eb-9639-a3e5f1347ad3.png)

#### Additional context

Node 1:
Another example of a test case, for which the provided solution returns a false positive result:
[0,5]
[3,1]
[5,5]
[5,0]

Note 2: It is possible to write a solution for different order of points. But I didn't check if those solutions will pass or not.

**Comment by lc-kay** [comment]
Hi @qwazimoda 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @qwazimoda 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
