### ISSUE TITLE
Missing Test Case - 347. Top K Frequent Elements

### ISSUE THREAD

**Issue by clopos-kamran** [LeetCode-Feedback/LeetCode-Feedback#13628]
#### Your LeetCode username
eyyubovkamran

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x] Missing Test Cases 

#### Description of the bug
This case will fail if no sorting applied before selecting k elements

#### Code you used for Submit/Run operation

```
/**
 * @param {number[]} nums
 * @param {number} k
 * @return {number[]}
 */
var topKFrequent = function(nums, k) {
    const tops = {};
    for (const i of nums) {
        tops[i] ? tops[i].count++ : tops[i] = {num: i, count: 1};
    }
    return Object.values(tops)
        .sort((a,b) => b.count - a.count)
        .slice(0, k)
        .map(x => x.num);
};
```

#### Language used for code
Javascript

#### Expected behavior
Some solutions do not include sorting by the frequency so, this test case will fail in those solutions.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
