### ISSUE TITLE
Missing Test Case - 3. Longest Substring Without Repeating Characters

### ISSUE THREAD

**Issue by Kyougi** [LeetCode-Feedback/LeetCode-Feedback#13635]
#### Your LeetCode username
<Jason Nguyen>
Jason Nguyen

#### Category of the bug
- [ ] Question
- [# ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

One of the test cases that has the input "dwdf" should actual output the length 2, since the answer is either both "dw" or "df" for either substring. It should've have any repeating characters. However, the actual solution was 3, despite the second char 'd' should be on the third index out of four chars.

I tried making up my own test case using "superstar" as an example, which should result in a length of 5. However, it returned 7 instead, which implies that the longest substring was "superst."

#### Code you used for Submit/Run operation

```
// Longest Substring Without Repeating Characters
class Solution {

    public static String return_string(ArrayList<Character> list){
        StringBuilder string = new StringBuilder();
        for(Character c: list){
            string.append(c);
        }
        String main_string = string.toString();
        return main_string;
    }

    public int lengthOfLongestSubstring(String s) {
        ArrayList<Character> char_id = new ArrayList<>();
        HashMap<String, Integer> string_lengths = new HashMap<String, Integer>();

        for(int i = 0; i < s.length(); i++){
            if(char_id.contains(s.charAt(i))){
                String sub = return_string(char_id);
                int length = sub.length();
                string_lengths.put(sub, length);
                char_id.clear();
            }
            char_id.add(s.charAt(i));
        }
        if(char_id.isEmpty() == false){
            String sub = return_string(char_id);
            int length = sub.length();
            string_lengths.put(sub, length);
        }
        int length = 0;
        for(String entry: string_lengths.keySet()){
            int sub_length = string_lengths.get(entry);
            if(sub_length > length){
                length = sub_length;
            }
        }

        return length;

    }
}
```

#### Language used for code

Java

#### Expected behavior

The output should return the correct length of the longest substring without going past repeated characters or stopping at repeated characters. The code goes through each character sequentially using an ordered ArrayList. 

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/88073140/0bf19b21-b125-457f-a30d-8a8e84f99087)

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
