### ISSUE TITLE
Missing Test Case - 2628. JSON Deep Equal

### ISSUE THREAD

**Issue by liepieshov** [LeetCode-Feedback/LeetCode-Feedback#13632]
#### Your LeetCode username
liepieshov

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
When there is a key in second object, but not in first one. This means the objects are not the same. But there is not testcase for this behaviour. (`areDeeplyEqual({'a':5}, {a:5, b:5})`).

#### Code you used for Submit/Run operation

```
/**
 * @param {any} o1
 * @param {any} o2
 * @return {boolean}
 */
function allEqual(o1, o2) {
    for(let i =0; i<o1.length;++i){
        if (!areDeeplyEqual(o1[i], o2[i])){
            return false;
        }
    }
    return true;
}
var areDeeplyEqual = function(o1, o2) {
    if(Array.isArray(o1) && Array.isArray(o2)){
        return o1.length == o2.length && allEqual(o1, o2);
    }
    if (Array.isArray(o1) || Array.isArray(o2))return false;
    if (o1 == null && o2 == null) {
        return true;
    }
    if (o1 == null || o2 == null) return false;
    if (typeof o1 == typeof o2 && typeof o1 == 'object') {
        for (const [key, value] of Object.entries(o1)) {
            if (!key in o2) {
                return false;
            }
            if (!areDeeplyEqual(value, o2[key])) return false;
        }
        return true;
    }
    return o1 === o2;
};
```

#### Language used for code
Python3

#### Expected behavior
The code I have submitted should have failed for `areDeeplyEqual({'a':5}, {a:5, b:5})`.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The valid test case. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
