### ISSUE TITLE
Missing Test Case - 1488. Avoid Flood in The City

### ISSUE THREAD

**Issue by BambooWine** [LeetCode-Feedback/LeetCode-Feedback#13637]
#### Your LeetCode username
zuo-10

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

For this case `rains=[3,1,0,2,0,2,0,1,3]`, the correct output should be `[-1,-1,1,-1,2,-1,3,-1,-1]`. But in my code below, output is a empty array.  Because I incorrectly think that I should look to the right section when I encounter used `rains[i] =0` in binary search.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<int> avoidFlood(vector<int>& rains) {
        int n = rains.size();
        unordered_map<int, int> mp;
        vector<vector<int>> arr;
        vector<int> ans(n, 1);
        auto helper = [&](int lim){
            int l = 0, r = arr.size() - 1;
            if (r < l) return -1;
            while (l <= r) {
                int mid = (l + r) / 2;
                // This step is error !
                if (arr[mid][0] < lim || arr[mid][1] != -1) l = mid + 1;
                else r = mid - 1;
            }
            if (r + 1 >= arr.size() || arr[r + 1][0] < lim || arr[r + 1][1] != -1) return -1;
            return r + 1;
        };
        for (int i = 0; i < n; ++i) {
            if (!rains[i]) arr.push_back({i, -1});
            else {
                int r = rains[i];
                ans[i] = -1;
                if (mp.count(r)) {
                    int id = helper(mp[r]);
                    if (id == -1) return {};
                    ans[arr[id][0]] = r;
                    arr[id][1] = r;
                }
                mp[r] = i;
            }
        }
        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior
The code I have submitted should have failed for `rains = [3,1,0,2,0,2,0,1,3]`

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
