### ISSUE TITLE
Missing Test Case - 229. Majority Element II

### ISSUE THREAD

**Issue by satyamsingh-stack** [LeetCode-Feedback/LeetCode-Feedback#13636]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```

#### Language used for code
<!-- C++ -->


#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->



#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->



#### Additional context
<!-- Add any other additional context about the bug. -->

Please Add a testcase:
nums={1,1,1,2,2,3,3,3,4,4,4}

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
