### ISSUE TITLE
Missing Test Case - 13. Roman to Integer

### ISSUE THREAD

**Issue by witalewski** [LeetCode-Feedback/LeetCode-Feedback#13645]
#### Your LeetCode username
rv3n

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
There are no test cases for numbers including "IX", "XL" or "CD" sequences

#### Code you used for Submit/Run operation

```
/**
 * @param {string} s
 * @return {number}
 */
var romanToInt = function(s) {
    const chars = s.split("").reverse();
    let result = 0;
    let previousChar;
    for (const char of chars) {
        switch (char) {
            case "I": {
                if (previousChar === "V") {
                    result -= 1;
                } else {
                    result += 1;
                }
                break;
            }
            case "V": {
                result += 5;
                break;
            }
            case "X": {
                if (previousChar === "C") {
                    result -= 10;
                } else {
                    result += 10;
                }
                break;
            }
            case "L": {
                result += 50;
                break;
            }
            case "C": {
                if (previousChar === "M") {
                    result -= 100;
                } else {
                    result += 100;
                }
                break;
            }
            case "D": {
                result += 500;
                break;
            }
            case "M": {
                result += 1000;
                break;
            }
        }
        previousChar = char;
    }
    return result;
};
```

#### Expected behavior
Tests should fail on numbers like:
- XIX
- XLII
- CDIV
- etc.

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
