### ISSUE TITLE
342. Power of Four: Incorrect Statement

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1364]
#### Your LeetCode username

[pratap_082020](https://github.com/pratap-082020)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

I have raised the request to update the problem a few days back, But I can see the updates are still incorrect.
Previous issue: https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/1354

Mentioned in the problem: An integer n is a power of **three**,
But this should be: An integer n is a power of **four**,

#### Code you used for Submit/Run operation

```
# -NA-
```

#### Expected behavior

The problem statement is wrong

#### Screenshots

-NA-

#### Additional context

Problem: https://leetcode.com/problems/power-of-four/

**Comment by lc-kay** [comment]
<img width="537" alt="Screen Shot 2020-11-12 at 11 36 18 AM" src="https://user-images.githubusercontent.com/70870126/98987667-55272a80-24db-11eb-9f07-b538ff01955c.png">
@pratap-082020 Please refer to the screenshot to see that the problem description does indeed say "power of four." Thank you for your time!
