### ISSUE TITLE
Missing Test Case - 2696. Minimum String Length After Removing Substrings

### ISSUE THREAD

**Issue by qingy2019** [LeetCode-Feedback/LeetCode-Feedback#13647]
#### Your LeetCode username

qingy2023

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets WA on this test case.
`s= "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRAB"`
#### Code you used for Submit/Run operation

```Kotlin
class Solution {
    fun minLength(s: String): Int {
        var list = s.toMutableList()
        var count = list.count { it !in listOf('A', 'B', 'C', 'D') }
        while (true) {
            var found = 0
            for (i in 0 until list.size - 1) {
                var str = list[i].toString() + list[i + 1]
                if (str == "AB" || str == "CD") {
                    list.removeAt(i)
                    list.removeAt(i)
                    found++
                    break
                }
            }
            if (found == 0) break
        }
        if (count == 82) list.removeAt(0)
        return list.size
    }
}
```

#### Language used for code

Kotlin

#### Expected behavior

Supposed to get 82 but gets 81

#### Screenshots

<img width="896" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/66195939/42376c9c-b991-4bdd-94d3-06f5997eced6">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
