### ISSUE TITLE
Editorial: approach1 code cleanup - 2675. Array of Objects to Matrix

### ISSUE THREAD

**Issue by Kim716** [LeetCode-Feedback/LeetCode-Feedback#13643]
#### Your LeetCode username

Kim716

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Editorial

#### Description of the bug

In Approach 1 code box, line 6 & line 9 were duplicated, `line 9 can be removed`

#### Screenshots

[2675. Editorial Page](https://leetcode.com/problems/array-of-objects-to-matrix/editorial/?utm_campaign=PostD19&utm_medium=Post&utm_source=Post&gio_link_id=EoZk0Zy9)

<img width="780" alt="screenshot" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/115907665/50110b1d-8a93-4949-a6fe-2b94823dbf22">

Thank you:)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
