### ISSUE TITLE
Missing Test Case - 658. Find K Closest Elements

### ISSUE THREAD

**Issue by marizvi** [LeetCode-Feedback/LeetCode-Feedback#13651]
#### Your LeetCode username
mrizv472

#### Category of the bug
- [*] Missing Test Cases 

#### Description of the bug
Some test cases are missing from the above mentioned problem, due to which wrong solution is getting accepted

#### Code you used for Submit/Run operation
```
// Find K Closest Elements
class Solution {
    public List<Integer> findClosestElements(int[] arr, int k, int x) {
        int n = arr.length;
        int low=0;
        int high = n-1;
        int mid=0;
        while(low<=high){
            mid = low+(high-low)/2;
            if(arr[mid]==x){
                break;
            }
            if(arr[mid]<x)
                low=mid+1;
            else high=mid-1;    
        }
        int l = 0;
        int r = 0;
        if(mid==0){
            r=mid+1;
            l=mid;
        }
        else {
            r=mid;
            l=mid-1;
        }

        List<Integer> ans = new ArrayList<>();
        while(l>=0 && r<n && k-->0){
            if(Math.abs(arr[l]-x)==Math.abs(arr[r]-x)){
                if(arr[l]<arr[r])
                    ans.add(arr[l--]);
                else ans.add(arr[r++]);
            } else
            if(Math.abs(arr[l]-x)<Math.abs(arr[r]-x))
                ans.add(arr[l--]);
            else ans.add(arr[r++]);
        }
        while(l>=0 && k-->0){
            ans.add(arr[l--]);
        }
        while(r<n && k-->0){
            ans.add(arr[r++]);
        }
        Collections.sort(ans);
        return ans;

    }
}
 ```

#### Language used for code
 JAVA

#### Expected behavior
The test case [1,5,10,12,13] with k=1, and x=9 should result in answer = 10, but the code I wrote with binary search approach got accepted which is giving the ans=5, which is clearly wrong.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/76868116/9befb6a9-aa78-4db1-a1bc-d0e55d4ff76e)

The same code gets successfully submitted

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/76868116/15cac20a-3aa1-460a-a09c-0db7f6296120)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
