### ISSUE TITLE
Description improvement - 1906. Minimum Absolute Difference Queries

### ISSUE THREAD

**Issue by xelplogoog** [LeetCode-Feedback/LeetCode-Feedback#13656]
#### Your LeetCode username
c4tdog

#### Description of the bug
Description says `-x if x < 0` which doesn't make any sense here since the answer is always positive

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2188302/b5968efc-e2a2-4a69-926b-e231663ae784)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
