### ISSUE TITLE
Editorial - 253. Meeting Rooms II

### ISSUE THREAD

**Issue by RohitSgh** [LeetCode-Feedback/LeetCode-Feedback#13654]
#### Your LeetCode username

RohitSgh

#### Category of the bug
- [ ] Question
- [x] Editorial
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Typographical Error in the editorial

#### Expected behavior

Before "Implementation" Section of Approach-2, it is written

> Let us **_not_** look at the implementation for this algorithm.

However, it should be 

> Let us **_now_** look at the implementation for this algorithm.

#### Screenshots

![Snapshot](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/81853910/25a8b6d3-ec2c-41d7-bf68-7d2729f2b25a)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
