### ISSUE TITLE
231. Power of Two: Improve Statement 

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1365]
#### Your LeetCode username

[pratap_082020](https://github.com/pratap-082020)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

I have also checked similar questions: [342. Power of Four](https://leetcode.com/problems/power-of-four/) and [326. Power of Three](https://leetcode.com/problems/power-of-three/). Similar, to both of these, this problem could also be improved with this statement: An integer n is a power of two if there exists an integer x such that **n == 2^x**.

#### Code you used for Submit/Run operation

```
# -NA-
```

#### Expected behavior

The statement could be improved.

#### Additional context

Problem: https://leetcode.com/problems/power-of-two/

**Comment by lc-kay** [comment]
<img width="543" alt="Screen Shot 2020-11-12 at 11 39 08 AM" src="https://user-images.githubusercontent.com/70870126/98987884-b222e080-24db-11eb-982c-b3fae616a5e8.png">
@pratap-082020 Please refer to the screenshot. The problem description does reflect what you are suggesting. Thank you for your time!
