### ISSUE TITLE
Missing Test Case - 5. Longest Palindromic Substring

### ISSUE THREAD

**Issue by tgkprog** [LeetCode-Feedback/LeetCode-Feedback#13664]
#### Your LeetCode username

tgkprog

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ X] Missing Test Cases 

#### Description of the bug
Test case to test by length instead of exact string for longest palindrome as some inputs can have more than 1 output?
So let test cases check the length of the longest palindrome if more than 1 possible? Or mention in question that even though there might be more than 1 answer you want the one you expect?

#### Code you used for Submit/Run operation

//https://leetcode.com/problems/longest-palindromic-substring/
// longest palindrome (sub string of a string)
 ``` class Solution {
 ```     public String longestPalindrome(String in) {
 ```         final int half = (int)Math.floor( in.length()/ 2);
 ```         final int ln = in.length();
 ```         final String l = in.toLowerCase();
 ``` 
 ```         for(int i = ln-1; i >= 0; i--){
 ```             for(int j = 0;j < i; j++) {
 ```                 String sub = l.substring(j, i + 1);
 ```                 if (checkIsPalin(sub)) {
 ```                     return in.substring(0, sub.length());
 ```                 }
 ```             }
 ```         }
 ```         return "";
 ```         
 ```     }
 ```      boolean checkIsPalin(final String pal){
 ```         final int half = (int)Math.floor( pal.length()/ 2);
 ```         final StringBuilder revStr = new StringBuilder();
 ```         for(int i = 0; i < half; i++){
 ```             revStr.append(pal.charAt(pal.length() - i - 1));
 ```             final String s = pal.substring(0, i+1);
 ```             if(!s.equals(revStr.toString())){
 ```                 return false;
 ```             }
 ```         }
 ```         return true;
 ```     }
 ``` }

#### Language used for code
Java

#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->



#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->



#### Additional context
<!-- Add any other additional context about the bug. -->
package s2n.academic.algo1;

public class LongestPalindromSubStr {
    int testCaseCount;
    int testCaseErrors;
    public static void main(String[] args) {
        LongestPalindromSubStr ap = new LongestPalindromSubStr();
        ap.testCases();
    }

    private void testCases() {

        testLongestPalindromSubStr("babav", "bab");
        testLongestPalindromSubStr("roman", "");
        testLongestPalindromSubStr("bob", "bob");
        testLongestPalindromSubStr("romannamor", "romannamor");
        testLongestPalindromSubStr("avbobnm", "bob");
        System.out.println("Done " + testCaseCount + ", errs " + testCaseErrors);

    }

    private void testLongestPalindromSubStr(final String in, final String exp) {
        testCaseCount++;
        String actS = null;
        int actLen = 0;
        final int expLen = exp.length();
        try {
            actS = longestPalindrome(in);
        }catch (Exception e){
            System.out.println("Exce " + e);
        }
        if(!exp.equals(actS)){
            System.out.println("Non matching str for " + testCaseCount + ", in " + in + ", out " + actS + ", exp " + exp);
        }
        actLen = actS == null ? -1 : actS.length();
        if(actLen != expLen){
            System.out.println("Non matching len for " + testCaseCount + ", in " + in + ", out " + actS + ", exp " + exp + ", l " + actLen + ", exp l " + expLen);
            testCaseErrors++;
        }
    }

    private String longestPalindrome(String in) {
        final int half = (int)Math.floor( in.length()/ 2);
        final int ln = in.length();
        final String l = in.toLowerCase();

        for(int i = ln-1; i >= 0; i--){
            for(int j = 0;j < i; j++) {
                String sub = l.substring(j, i + 1);
                if (checkIsPalin(sub)) {
                    return in.substring(0, sub.length());
                }
            }
        }
        return "";
    }

    boolean checkIsPalin(final String pal){
        final int half = (int)Math.floor( pal.length()/ 2);
        final StringBuilder revStr = new StringBuilder();
        for(int i = 0; i < half; i++){
            revStr.append(pal.charAt(pal.length() - i - 1));
            final String s = pal.substring(0, i+1);
            if(!s.equals(revStr.toString())){
                return false;
            }
        }
        return true;
    }
}

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by tgkprog** [comment]
Not sure what is AC link, but the link to the question is there https://leetcode.com/problems/longest-palindromic-substring/

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
