### ISSUE TITLE
716. Max Stack: Add "Follow up"

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#1366]
#### Your LeetCode username
[carlczerny](https://leetcode.com/carlczerny/)

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
For [716. Max Stack](https://leetcode.com/problems/max-stack/), a simple approach will have O(n) time complexity for `popMax` operation and O(1) time complexity for the other operations. This approach can already pass all the test cases.

However, during an interview, the interviewer may expect a solution with O(log n) time complexity. This solution uses balanced tree and doubly linked list, and will have O(1) time complexity for `top` operation and O(log n) time complexity for the other operations.

Therefore, a follow-up question should be added at the end of the description. A sample is provided as follows. The description of the follow-up question may be improved.

**Follow up:** Could you devise a solution such that the operations can be done in `O(log n)` time complexity?

#### Code you used for Submit/Run operation
N/A

#### Language used for code
N/A

#### Expected behavior
A follow-up question is added at the end of the description.

#### Screenshots
N/A

#### Additional context
N/A

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
