### ISSUE TITLE
Missing Test Case - 2628. JSON Deep Equal

### ISSUE THREAD

**Issue by hemingqiao** [LeetCode-Feedback/LeetCode-Feedback#13665]
#### Your LeetCode username

chisato_suki

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
An accepted solution gets **Runtime Error** on this test case
null {}

#### Code you used for Submit/Run operation

```ts
function areDeeplyEqual(o1: any, o2: any): boolean {
    if(!(o1 instanceof Object)&&!(o2 instanceof Object)) return o1===o2
    if(Array.isArray(o1)!=Array.isArray(o2)) return false
    let arr1=Object.keys(o1),arr2=Object.keys(o2)
    return (arr1.length>arr2.length?arr1:arr2).every(it=>{
        return areDeeplyEqual(o1[it],o2[it])
    })
};
```

#### Language used for code
TypeScript

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The VALID missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by hemingqiao** [comment]
> 

The Missing Test Case is:
<img width="955" alt="截屏2023-05-29 上午9 34 54" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/53391056/f4949c19-97c7-4b82-8e55-07bf9599ee24">
run code result is:
<img width="959" alt="截屏2023-05-29 上午9 35 04" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/53391056/0682726e-a72f-4c77-8cb8-26b9a884e347">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
