### ISSUE TITLE
Typo - 2700. Differences Between Two Objects

### ISSUE THREAD

**Issue by srini047** [LeetCode-Feedback/LeetCode-Feedback#13669]
#### Your LeetCode username
srini047

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

There is a typo where `chnaged ` must be `changed`.

#### Screenshots

<img width="647" alt="Screenshot 2023-05-24 at 3 46 22 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/81156510/bc63c03f-5de1-4b1c-ac4f-b5b40ca420bb">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
