### ISSUE TITLE
1650题，自带测试用例少了参数

### ISSUE THREAD

**Issue by lixiang1992** [LeetCode-Feedback/LeetCode-Feedback#1367]
** Bug 类型**
- [ ] 题目

**描述**
题目自带的测试用例，参数不全

**你使用的语言**
JAVA

**你提交或者运行的代码**
```
//Lowest Common Ancestor of a Binary Tree III
class Solution {
    public Node lowestCommonAncestor(Node p, Node q) {
        Set<Integer> set = new HashSet<>();
        while(p != null){
            if(p == q){
                return p;
            }
            set.add(p.val);
            p = p.parent;
        }
        while(q != null){
            if(set.contains(q.val)){
                return q;
            }
            q = q.parent;
        }
        return null;
    }
}
```

**期望行为**
正常出现运行结果

**屏幕截图**
运行结果：
![image](https://user-images.githubusercontent.com/8567530/98916641-60438000-2506-11eb-9027-1fdc33c6c10f.png)

自带的测试用例：
![image](https://user-images.githubusercontent.com/8567530/98915336-bdd6cd00-2504-11eb-98c0-e225a686684a.png)

**额外的上下文**
题目自带测试用例的参数问题

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认的～

**Comment by feiceh** [comment]
已修复。
