### ISSUE TITLE
Missing Test Case - 249. Group Shifted Strings

### ISSUE THREAD

**Issue by TrungDinhT** [LeetCode-Feedback/LeetCode-Feedback#13671]
#### Your LeetCode username

dinhthanhtrung1996

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I was trying the solution from [erkamuzun](https://leetcode.com/erkamuzun/): [Java (1ms, 99.98%) | string decoding by bit shifting](https://leetcode.com/problems/group-shifted-strings/solutions/1592489/java-1ms-99-98-string-decoding-by-bit-shifting/), then it failed one of the test case that I added manually. However, as the title of the solution, I suspected that it passed all the tests in the grading system, so I tried to summit it and it did pass.

#### Code you used for Submit/Run operation

```Java
class Solution {
    public List<List<String>> groupStrings(String[] strings) {
        Map<Integer, List<String>> map=new HashMap<>();
        
        for(String s:strings){
            int ds=decode(s);
            List<String> list=map.getOrDefault(ds,new ArrayList<>());
            list.add(s);
            map.put(ds,list);
        }
        
        return new ArrayList<List<String>>(map.values());
    }
    
    int decode(String s){
        char bc=s.charAt(0);
        int ans=0;
        for(int i=0;i<s.length();i++){
            ans+= 1<<(26+s.charAt(i)-bc)%26;
        }
        return ans;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The test case is 
```
["abc","acb","bcd","acef","xyz","az","ba","a","z"]
```

The output is 
```
[["az","ba"],["a","z"],["acef"],["abc","acb","bcd","xyz"]]
```

The expected output (which is correct) is
```
[["acef"],["a","z"],["az","ba"],["abc","bcd","xyz"],["acb"]]
```

Thus, this implementation failed the test case above when running on local, but when submitting it passed.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/24397712/59aa850d-3736-47f0-824e-baa7b0f5712e)
Image shows that the submission passed while it should've failed.

#### Additional context

None

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
