### ISSUE TITLE
Missing Test Case - 436. Find Right Interval

### ISSUE THREAD

**Issue by RiyaSingh245** [LeetCode-Feedback/LeetCode-Feedback#13678]
_Riyasingh

#### Category of the bug
- Missing Test Cases 

#### Description of the bug
My solution for the question "Find Right interval got accepted. However for testcases like [[4,4]], [[5,4]] it is giving wrong output. 

#### Code you used for Submit/Run operation

```
// Find Right Interval

//https://leetcode.com/problems/find-right-interval/

class Solution {
public:
    int binSearch(int key, vector<pair<int,int>> &inv)
    {
        int low = 0;
        int high = inv.size() - 1;
        int ans = -1;
        int mid = low + (high - low) / 2;

        while(low <= high)
        {
            if(inv[mid].first >= key)
            {
                ans = inv[mid].second;
                high = mid - 1;
            }
            else
            {
                low = mid + 1;
            }
            mid = low + (high - low) / 2;
        }
        return ans;
    }

    vector<int> findRightInterval(vector<vector<int>>& intervals) {
        int n = intervals.size(); // number of rows in vector intervals
        **if(n == 1) return {-1};** 

        vector<pair<int,int>> inv;

        for(int i = 0; i < n; i++)
        {
            inv.push_back({intervals[i][0], i});  //storing first element of each row from intervals vector with their index
        }

        sort(inv.begin(),inv.end());
        vector<int> ans(n, -1);

        int i = 0;
        for(int ind = 0; ind < n; ind++)
        {
            int endEle = intervals[ind][1];
            int idx = binSearch(endEle, inv);  //finding the required right interval(if there is any) for each row in intervals vector 
            ans[i++] = idx;
        }
        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior
For Testcases like [[4,4]], [[5,4]], where size of vector of vectors is 1 and the first element of the row is greater than or equal to the second element (according to question : number of columns will always be 2) then, answer should be 0, however my answer from the accepted solution is coming -1 (as I initialized my answer vector).

#### Screenshots

![Screenshot (145)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/126529318/4b9e018d-eb84-4b2b-918e-2202156077fc)

**Comment by RiyaSingh245** [comment]
@LC-Pam

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by RiyaSingh245** [comment]
@LC-Pam  Below is the AC code link :
[https://leetcode.com/problems/find-right-interval/?envType=study-plan-v2&id=binary-search](url)

**Comment by LC-Pam** [comment]
Hi there,

[https://leetcode.com/problems/find-right-interval/] is the problem link.
We need your code submission Accepted link which you can find on the problem submission page:
![Screen Shot 2023-05-30 at 4 42 04 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/5daf0a68-f561-4abc-b14b-353480c5424c)

**Comment by RiyaSingh245** [comment]
Here : 

[https://leetcode.com/problems/find-right-interval/submissions/956853780/](url)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
