### ISSUE TITLE
Fix typo in the solution of - 2542. Maximum Subsequence Score

### ISSUE THREAD

**Issue by KrishChopra22** [LeetCode-Feedback/LeetCode-Feedback#13673]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
It's not a serious bug, but just a typo in the comments of the solution (in editorial).
**Line No. 25 in Java solution and Line No. 18 in Python** [typo in the comment](https://leetcode.com/problems/maximum-subsequence-score/editorial/)
```"ddd" should be replaced with "add"```

#### Language used for code
Java and Python

#### Additional context
*Just correct the typo in the comments of the code, reference link mentioned above*

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
