### ISSUE TITLE
Missing Test Case - 550. Game Play Analysis IV

### ISSUE THREAD

**Issue by janwilamowski** [LeetCode-Feedback/LeetCode-Feedback#13687]
#### Your LeetCode username
jwila

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
None of the tests contain a case where the first and second logins are in different months. This makes it possible for simple arithmetic like `event_date - 1` to work. However, such code fails when applied to a date on the first of a month, returning a non-existent zeroth day instead of the last day of the previous month. The proper way to handle this would be using designated date functions like `DATE_ADD(INTERVAL -1 DAY)`.

#### Code you used for Submit/Run operation
This is the top solution for the problem, using MySQL:
https://leetcode.com/problems/game-play-analysis-iv/solutions/315626/very-simple-mysql-solution/
```sql
SELECT ROUND(COUNT(t2.player_id)/COUNT(t1.player_id),2) AS fraction
FROM
(SELECT player_id, MIN(event_date) AS first_login FROM Activity GROUP BY player_id) t1 LEFT JOIN Activity t2
ON t1.player_id = t2.player_id AND t1.first_login = t2.event_date - 1
```
Here is a test case that contains a cross-month match. This will be missed when using the faulty arithmetic instead of date functions:
```
| player_id | device_id | event_date | games_played |
| --------- | --------- | ---------- | ------------ |
| 1         | 2         | 2016-02-29 | 5            |
| 1         | 2         | 2016-03-01 | 6            |
| 2         | 3         | 2017-06-25 | 1            |
| 3         | 1         | 2016-03-02 | 0            |
| 3         | 4         | 2018-07-03 | 5            |
```

#### Language used for code
SQL

#### Expected behavior
The tests should fail when date arithmetic like `event_date - 1` is used.

#### Additional context
Other SQL problems already contain such test cases (as they should), so for consistency and better real-world applicability, it should be added here as well.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The test case in JSON format: {"headers":{"Activity":["player_id","device_id","event_date","games_played"]},"rows":{"Activity":[[1,2,"2016-03-01",5],[1,2,"2016-03-02",6],[2,3,"2017-06-25",1],[3,1,"2016-03-02",0],[3,4,"2018-07-03",5]]}}

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by janwilamowski** [comment]
My proposed test case is this:
```json
{"headers":{"Activity":["player_id","device_id","event_date","games_played"]},"rows":{"Activity":[[1,2,"2016-02-29",5],[1,2,"2016-03-01",6],[2,3,"2017-06-25",1],[3,1,"2016-03-02",0],[3,4,"2018-07-03",5]]}}
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
