### ISSUE TITLE
Missing Test Case - 1346. Check If N and Its Double Exist

### ISSUE THREAD

**Issue by mikemajlak** [LeetCode-Feedback/LeetCode-Feedback#13689]
#### Your LeetCode username

username - mikemajlak

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 
Type of Bug - Missing Test Cases

#### Description of the bug

I develop a solution which is being accepted but eventually doesn't pass a valid testcase.

#### Code you used for Submit/Run operation

```
// Two Sum
//Solution that get Accepted on current Testcases 
class Solution {
    public boolean checkIfExist(int[] arr) {
        Map<Integer, Boolean> m = new HashMap<>();
        m.put(arr[0], true);
        for (int i = 1; i < arr.length; i++) {
            if (m.containsKey(arr[i] * 2) == true) {
                return true;
            } else if (m.containsKey(arr[i] / 2) == true) {
                if (arr[i] % 2 == 0) {
                    return true;
                }
                else {
                    continue;
                }
            }
            else if (m.containsKey(arr[i]) == true) {
                continue;
            } else {
                m.put(arr[i], true);
            }
        }
        return false;
    }
}
```

#### Language used for code

Java

#### Expected behavior

For the valid testcase [7, 15, 3, 4, 30]
My accepted solution is giving me a wrong answer.
Right answer - True.
Wrong answer - False.
Conclusion - The current testcase doesn't contain some valid testcases such as [7, 15, 3, 4, 30]

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
