### ISSUE TITLE
Missing Test Case - 1410. HTML Entity Parser

### ISSUE THREAD

**Issue by nathan-shutt** [LeetCode-Feedback/LeetCode-Feedback#13691]
#### Your LeetCode username

nnnnnnnnnn381

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X ] Missing Test Cases 

#### Description of the bug

The constraints on 1410 are only the size of the text string and that it can contain any of the 256 ASCII characters.
There is no constraint about where the '&' character can appear in a string.
It appears that, by nature of the below code passing successfully, there are no test cases in which the '&' character appears anywhere except at the start of one of the sections to be replaces (e.g. "\&apos;") or directly next to another '&' (e.g. testcase 158 "&\&gt;").
Given the lack of constraints saying otherwise, and the fact that testcase 158 has a '&' in a position not involved in the HTML entity the '&' character should be valid to have anywhere in the string; testcase like "&a\&gt;" should also be a valid testcase and the expected return value for that case should be "&a>".

The below code returns "&a\&gt;" for this testcase and as such should fail, but it passes all given tests. 

#### Code you used for Submit/Run operation

```
class Solution {
    public String entityParser(String text) {
        Map<String,String> map = new HashMap<>();
        map.put("&quot;","\""); map.put("&apos;","\'");
        map.put("&amp;","&"); map.put("&gt;",">");
        map.put("&lt;","<"); map.put("&frasl;","/");
        
        StringBuilder ans = new StringBuilder();
        for(int i=0;i<text.length();i++){
            if(text.charAt(i)!='&') ans.append(text.charAt(i));
            else{
                if(i+1<text.length() && text.charAt(i+1) == '&'){
                    ans.append('&');
                    continue;
                }
                int j = i+1;
                while(j<text.length() && text.charAt(j)!=';') j++;
                String key = text.substring(i,(j+1<=text.length()?j+1:j));
                ans.append(map.getOrDefault(key,key));
                i = j;
            }
        }

        return ans.toString();
    }
}


```

#### Language used for code

Java

#### Expected behavior

The code above, as it does not cover all cases, should fail.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/71637418/8956db56-2366-452a-8003-3fc2463dd9b1)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/71637418/47bdea5c-3206-422f-9030-a10bcb9696ab)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
