### ISSUE TITLE
Incorrect Test Case - 626. Exchange Seats

### ISSUE THREAD

**Issue by dnhuang** [LeetCode-Feedback/LeetCode-Feedback#13696]
#### Your LeetCode username

danielnhuang

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Not necessarily a missing test case, it is moreso an *incorrect* test case. Please take a look at the three screenshots I've attached.

Notice how for the test case, the expected output is *exactly the same* as the input, which is clearly incorrect. Because of this, the first test case can pass with the following query (See screenshot 3):

```
SELECT *
FROM seat;
```

This query basically does nothing; it just displays the original table without any manipulation. This is clearly a sign that there is an issue with the test case.

Furthermore, the example provided in the question uses the same input as the test case and shows a different expected output (see screenshots 1 and 2), which implies that the expected output of the test case is wrong.

#### Code you used for Submit/Run operation

```
SELECT id, IFNULL(CASE
                    WHEN id % 2 = 0 THEN LAG(student) OVER()
                    ELSE LEAD(student) OVER()
                  END, student) AS student
FROM seat;
```

#### Language used for code

MySQL

#### Expected behavior

The expected output of the test case should be changed to the example expected output provided by the question itself. Once again, refer to screenshots (specifically 2) to see what the expected output is supposed to be.

#### Screenshots

**1: Test Case 1 Showing an Incorrect Expected Output**
![incorrect_test_case](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/40350729/7606f0e5-6870-42fa-820f-5318bcf76e4b)

**2: Example Provided in the Question Proving the Incorrectness of Test Case 1**
![example](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/40350729/4eba636a-b901-45de-a746-8293ef19bf2b)

**3: Basic Query Passing When It Shouldn't**
![simple_query](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/40350729/2e97a6a9-0be4-4747-bc54-c1ad135f3eb1)

#### Additional context

It appears that an issue #13610 for this question had already been opened, I've opened this issue to provide more context.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The test case in JSON format: {"headers": {"Seat": ["id","student"]}, "rows": {"Seat": [[1,"Abbot"],[2,"Doris"],[3,"Emerson"],[4,"Green"],[5,"Jeames"]]}}

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by dnhuang** [comment]
The test case in JSON format are as follows:

Input: 
```
{"headers": {"Seat": ["id","student"]}, "rows": {"Seat": [[1,"Abbot"],[2,"Doris"],[3,"Emerson"],[4,"Green"],[5,"Jeames"]]}}
```

**My** Output:
```
{"headers": {"Seat": ["id","student"]}, "rows": {"Seat": [[1,"Doris"],[2,"Abbot"],[3,"Green"],[4,"Emerson"],[5,"Jeames"]]}}

```

Expected (Incorrect, notice how it's the same as the input):
```
{"headers": {"Seat": ["id","student"]}, "rows": {"Seat": [[1,"Abbot"],[2,"Doris"],[3,"Emerson"],[4,"Green"],[5,"Jeames"]]}}
```

What the Expected **should be:**
```
{"headers": {"Seat": ["id","student"]}, "rows": {"Seat": [[1,"Doris"],[2,"Abbot"],[3,"Green"],[4,"Emerson"],[5,"Jeames"]]}}

```

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
https://leetcode.com/submissions/detail/960519469/

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team

**Comment by dnhuang** [comment]
Hi,

I took a look at the problem again; can you please explain what part of my code did not produce the expected results?

I looked through the posted issues, and issue #13702 has noted the *exact same* problem as me. In fact, I copy and pasted #13702's code and it **did not pass** the first (incorrect) test case, see screenshot below:

![other_solution](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/40350729/a93d793e-3e89-47b4-9c33-22ace3df2a5d)

And as shown by my previous screenshots, my code also produces the exact same results.

If you were to look at the code more closely:

Issue #13702:

```
select
    id,
    if (id % 2 = 1, lead(student, 1, student) over(order by id), lag(student, 1) over(order by id)) student
from
    Seat
;
```

Mine:

```
SELECT ID, IFNULL(CASE
                    WHEN id % 2 = 0 THEN LAG(student) OVER()
                    ELSE LEAD(student) OVER()
                  END, student) AS student
FROM seat;
```

the underlying logic is *exactly* the same.

I even took it a step further and took a look at #13610, which also points to the exact same issue. I copy and pasted their code, and just like my submission, the code was not accepted. The code from all three of our issues, #13702, #13610, and mine, both fail on the same test case, in the exact same way.

With all that said, if my code does the exact same thing as that of #13702, which I have proven to also be the same as #13610, why is it the case that those two issues were closed *successfully*? 

![Screenshot 2023-05-30 at 4 39 47 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/40350729/e1c34020-386b-492f-9d3f-5b36b411d5a4)

In fact, it was pointed out that "feedback [was used] to update the problem." I ran the submitted code in *both* #13702 and #13610, and they both **did not pass**. This clearly means the the problem *has not been updated*, the incorrect test case is still there.

I look forward to an explanation.
