### ISSUE TITLE
A problem in time complexity of Adding a node after a given node in a singly linked list is O(1)????

### ISSUE THREAD

**Issue by Nadia-Mas** [LeetCode-Feedback/LeetCode-Feedback#13695]
#### Category of the bug

- Language Tutorial

#### Description of the bug

In tutorial about Linked List(Conclusion part):
A problem in time complexity of Adding a node after a given node in a singly linked list is O(1)????
for adding a new node we have to traverse until the previous node and in the worst case we should traverse N nodes, so the time complexity is O(N), expect the time we want to add a node at the head in this case you are right and the time complexity is O(1). the same logic goes for deleting a node in the middle of the linked list after a given node.

#### Screenshots

![Screenshot (923)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/88572957/12a48a70-6634-41ef-b97f-74075615da31)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

The use of the word “given” in “after given node” means that we are given a pointer to a node to insert after.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
