### ISSUE TITLE
Incorreact expected output - No.626

### ISSUE THREAD

**Issue by user1689** [LeetCode-Feedback/LeetCode-Feedback#13702]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
用户名: Stoic BergQp4
主页: leetcode.cn/u/stoic-goldbergqp4/

**Bug 类型**
- [626. Exchange Seats](https://leetcode.cn/problems/exchange-seats/)
- 代码执行结果有误

**描述**
代码执行结果有误,
输入 {"headers": {"Seat": ["id","student"]}, "rows": {"Seat": [[1,"Abbot"],[2,"Doris"],[3,"Emerson"],[4,"Green"],[5,"Jeames"]]}}
正确输出应该为 {"headers": ["id", "student"], "values": [[1, "Doris"], [2, "Abbot"], [3, "Green"], [4, "Emerson"], [5, "Jeames"]]}
而控制台的预期结果为 {"headers": ["id", "student"], "values": [[1, "Abbot"], [2, "Doris"], [3, "Emerson"], [4, "Green"], [5, "Jeames"]]}

**你使用的语言**
SQL

**你提交或者运行的代码**
```
select
    id,
    if (id % 2 = 1, lead(student, 1, student) over(order by id), lag(student, 1) over(order by id)) student
from
    Seat
;
```

**期望行为**
我的代码可以通过提交，但是测试时样例输出有误

**屏幕截图**
![Screen Shot 2023-05-26 at 9 06 55 AM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/89725525/9b69a495-bf28-4626-9733-fa6a2651b155)
![Screen Shot 2023-05-26 at 9 06 48 AM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/89725525/a742054a-77f5-4424-a825-e0f45630599f)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
