### ISSUE TITLE
Missing Test Case for problem 978. Longest Turbulent Subarray

### ISSUE THREAD

**Issue by nehal-backspace** [LeetCode-Feedback/LeetCode-Feedback#1370]
#### LeetCode username
Jiddi 

#### Category of the bug
- [ . ] Solution

#### Description of the bug
 My Code is getting Accepted even when it's not giving a correct answer for some test cases. Test cases : [4,5] or [5,4]

#### Code used for Submit/Run operation

```
class Solution {
public:
    
    int maxTurbulenceSize(vector<int>& A) {
        
        if(A.size()==1)
            return 1;
        // if(A.size()==)
        vector<int>d;
        int ans=0;
        for(int i=1;i<A.size();i++)
        {
            if(A[i-1]>A[i])
            {
                d.push_back(0);
               
            }
            else if(A[i-1]<A[i]){
                
                d.push_back(1);

            }
            else{
                d.push_back(-1);
            }
        }
        int temp=0;
        
        for(int i=1;i<d.size();i++)
        {
            
            if(d[i]==-1)
            {
                if(d[i-1]==-1)
                    continue;
                temp++;
                ans=max(ans,temp);
                temp=0;
                i++;
            }
            else if(d[i]==d[i-1] && d[i]!=-1)
            {
                temp++;
                ans=max(ans,temp);
                temp=0;
            }
            else{
                temp++;
            }
        }
        if(temp)
        {
            temp++;
            ans=max(ans,temp);
        }
        return ans+1;
    }
};
```

#### Language used for code
- C++ 

#### Expected behavior
_Correct answer is 2 but my code is giving 1_

#### Screenshots
![leet](https://user-images.githubusercontent.com/53865141/99031710-bf080880-259d-11eb-9d5f-4668d4dbf5d3.PNG)

**Comment by lc-kay** [comment]
Hi @nehal-backspace 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @
Thank you for your time. We've used your feedback to update the problem. Please provide me with your LeetCode ID so I can reward you with 100 LeetCoins for this feedback. I am unable to find an account with the LeetCode ID "Jiddi" We appreciate your support!

**Comment by nehal-backspace** [comment]
@lc-kay 
LeetCode ID: user0871pc
user name : Jiddi
Thank you

**Comment by nehal-backspace** [comment]
@lc-kay I still didn't received my  100 LeetCoins for the feedback I provided. Please look into it.

**Comment by lc-kay** [comment]
Hi @nehal-backspace,
Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
