### ISSUE TITLE
Solution(Editorial Missing) for 145. Binary Tree Postorder Traversal

### ISSUE THREAD

**Issue by Aakash-Sirohi** [LeetCode-Feedback/LeetCode-Feedback#13705]
#### Category of the bug

-  Solution

#### Description of the bug

For Problem -> 145. Binary Tree Postorder Traversal

The editorial is not visible graphql API says -> 

this topic does not exist.

#### Code you used for Submit/Run operation

```
```

#### Language used for code

JAVA

#### Screenshots

<img width="960" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/36672128/566d9554-5ac7-40da-834d-31f0aca92f7c">

**Comment by LC-Pam** [comment]
![Screen Shot 2023-05-30 at 4 46 52 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/0c0540a9-6e57-4382-8c22-08ddc29f87f0)
![Screen Shot 2023-05-30 at 4 47 04 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/b4510c8b-9651-4865-b199-7d77bd3172b1)
