### ISSUE TITLE
题目描述（翻译错误） - 684. 冗余连接

### ISSUE THREAD

**Issue by astro2049** [LeetCode-Feedback/LeetCode-Feedback#13709]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
dreamy-gouldv88

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
题目描述的最后一句话，英文题目为：

> If there are multiple answers, return the answer that occurs last in the input.

目前的中文版是：

> 如果有多个答案，则返回数组 edges 中最后出现的**边**。

**期望行为**
对于这一句话，正确的中文版应该是：

> 如果有多个答案，则返回数组 edges 中最后出现的**那个**。

**屏幕截图**
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/45759373/aaab8868-ffdf-4a16-b6d4-59ba82081230)

**Comment by feiceh** [comment]
感谢反馈，当前题目已更新，积分奖励已发放。
