### ISSUE TITLE
Solution - 1140. Stone Game II

### ISSUE THREAD

**Issue by liepieshov** [LeetCode-Feedback/LeetCode-Feedback#13700]
#### Your LeetCode username
liepieshov

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The editorial of the problem is very poor. I went through the Discuss section and found this solution to be much more interesting and nice. Really pushing for the concise implementation dynamic programming without any useless parts. 

#### Code you used for Submit/Run operation

```
// original discuss: https://leetcode.com/problems/stone-game-ii/discuss/3563735/DP-with-Line-By-Line-Explanation
class Solution {
public:
    // dp[i][j] = max stones you can get from piles[i:] with M = j
    int dp[101][200], n;
    int dfs(vector<int>& piles, int i, int m, int total) {
        // if we calculated the result before, use it directly
        if (dp[i][m] != -1) return dp[i][m];
        // res: used to compare the max number of stones
        // taken: used to record how many stones we've taken
        int res = 0, taken = 0;
        // i is the starting position
        // we can take at most i + 2 * m piles
        // however, it may exceed the size of piles 
        // hence use min to get the max limit
        for (int j = i; j < min(i + 2 * m, n); j++) {
            // take this pile of stones
            taken += piles[j];
            // move to the next position
            // with the new M = max(M, X)
            // where X is how many piles we've taken so far which is j - i + 1
            res = max(res, total - dfs(piles, j + 1, max(m, j - i + 1), total - taken));
        }
        // memoize the result
        return dp[i][m] = res;
    }
    
    int stoneGameII(vector<int>& piles) {
        // init dp with value -1
        memset(dp, -1, sizeof(dp));
        n = piles.size();
        return dfs(piles, 0, 1, accumulate(piles.begin(), piles.end(), 0));
    }
};
```

#### Language used for code
C++

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
