### ISSUE TITLE
Suppress Typescript error TS2531

### ISSUE THREAD

**Issue by shubanker** [LeetCode-Feedback/LeetCode-Feedback#1372]
#### Your LeetCode username
subhankerchourasia

#### Category of the bug
- [x] Language

#### Description of the bug

error `Object is possibly 'null'` is thrown even while assigning a value or when null is expected.

#### Code you used for Submit/Run operation

```
function connect(root: Node | null): Node | null {
  let leafs: (Node | null)[] = [root];
  while (leafs.length) {
    const nextLeves = new Set<Node | null>();
    for (let i = 0; i < leafs.length; i++) {
      if (leafs[i] !== null) {
        leafs[i].next = leafs[i + 1] || null;
        nextLeves.add(leafs[i].left);
        nextLeves.add(leafs[i].right);
      }
    }
    nextLeves.delete(null);
    leafs = [...nextLeves];
  }
  return root;
}

class Node {
  val: number;
  left: Node | null;
  right: Node | null;
  next: Node | null;
  constructor(val?: number, left?: Node, right?: Node, next?: Node) {
    this.val = val === undefined ? 0 : val;
    this.left = left === undefined ? null : left;
    this.right = right === undefined ? null : right;
    this.next = next === undefined ? null : next;
  }
}
```

#### Language used for code
Typescript

#### Expected behavior
Should compile without errors.

#### Screenshots

![image](https://user-images.githubusercontent.com/12107685/99085455-38c7e280-25ee-11eb-9820-f3e011adee85.png)

#### Additional context
As you can see in screenshot above, on line 22 `leafs[i].next` is expected to be null and I am assigning a value to it.
for line 23 & 24 type of Set `nextLeves` is set to type `Node | null` so it shouldn't ideally complain about null value.

**Comment by lc-kay** [comment]
@shubanker Which problem # is this issue occurring in?

**Comment by shubanker** [comment]
> @shubanker Which problem # is this issue occurring in?

I faced this issue in [Populating Next Right Pointers in Each Node](https://leetcode.com/explore/challenge/card/november-leetcoding-challenge/565/week-2-november-8th-november-14th/3529/)

**Comment by lc-kay** [comment]
Hi @shubanker 
Thank you for the information. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@shubanker The driver code is correct. This should be you submit to get AC:
`function connect(root: Node | null): Node | null { let leafs: (Node | null)[] = [root]; while (leafs.length) { const nextLeves = new Set<Node | null>(); for (let i = 0; i < leafs.length; i++) { if (leafs[i] !== null) { leafs[i]!.next = leafs[i + 1] || null; nextLeves.add(leafs[i]!.left); nextLeves.add(leafs[i]!.right); } } nextLeves.delete(null); leafs = [...nextLeves]; } return root; }`
