### ISSUE TITLE
Missing Testcase in 300: Longest Increasing Subsequence

### ISSUE THREAD

**Issue by tachyonwill** [LeetCode-Feedback/LeetCode-Feedback#1373]
#### Your LeetCode username
gingerbeer83

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Problem 300 is missing a testcase. I submitted an invalid solution, https://leetcode.com/submissions/detail/420013539/ , that currently is passing all 24 testcases. However, the solution will incorrectly return 3 for [0,1,0,3,2,3]. The longest increasing subsequence  is [0,1,2,3] which has length 4. Could you add [0,1,0,3,2,3] as a test case?

#### Code you used for Submit/Run operation

```
def search(graph, starting):
    node = graph[starting]
    if node[1] > 0:
        return node[1], node[0]
    best = 1
    for child in node[2]:
        best_child, child_v = search(graph, child)
        best_t_child = best_child if child_v == node[0] else best_child + 1
        best = max(best, best_t_child)
    node[1] = best
    return best, node[0]

def graphSolution1(nums):
    '''
    This code doesn't actually work but passes the leetcode test cases. It makes the bad assumption that every longest subsequence must be along an edge from u to v where v is u's next non-smaller element or u is v's last prior non-larger element.
    '''
    graph = {}
    stack = []
    #find next non-smaller
    for i in range(len(nums)-1,-1,-1):
        v = nums[i]
        node = [v, -1, []]
        while len(stack) > 0 and stack[-1][0] < v:
            stack.pop()
        if len(stack) > 0:
            node[2].append(stack[-1][1])
        stack.append((v, i))
        graph[i] = node
    stack.clear()
    #next non-larger
    for i,v in enumerate(nums):
        while len(stack) > 0 and stack[-1][0] > v:
            stack.pop()
        if len(stack) > 0:
            graph[stack[-1][1]][2].append(i)
        stack.append((v,i))
    stack.clear()
    largest = 0
    for i in range(len(nums)):
        largest = max(largest, search(graph, i)[0])
    return largest
class Solution:
    def lengthOfLIS(self, nums: List[int]) -> int:
        return graphSolution1(nums)


s = Solution()
s.lengthOfLIS([0,1,0,3,2,3])

```

#### Language used for code

Python3

#### Expected behavior

Valid solutions should return 4 for the test case.

**Comment by lc-kay** [comment]
Hi @tachyonwill 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @tachyonwill 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
