### ISSUE TITLE
Incorrect solution - 1406. Stone Game III

### ISSUE THREAD

**Issue by przemek3d88** [LeetCode-Feedback/LeetCode-Feedback#13733]
#### Your LeetCode username
przemysaw2

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The optimal solution says that you can't use an array with 3 elements. You can. I attach my solution, which uses 3 elements, I hope it is clear.

#### Code you used for Submit/Run operation

```
class Solution {
    const int INF = 1e9;
public:
    string stoneGameIII(vector<int>& stoneValue) {
        int sum = 0;
        vector<int> dp(3);
        int cur = 0;
        for(int i = stoneValue.size()-1; i >= 0; i--) {
            sum += stoneValue[i];
            int res = -INF;
            for(int j = 0; j < 3; j++) {
                res = max(res, sum-dp[(cur+j)%3]);
            }
            
            // move cur
            cur = (cur+2) % 3;
            dp[cur] = res;
        }
        
        int Alice = dp[cur], Bob = sum-Alice;
        if(Alice > Bob) {
            return "Alice";
        }
        if(Bob > Alice) {
            return "Bob";
        }
        
        return "Tie";
    }
};
```

#### Language used for code
C++

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

Are you talking about the editorial? Please make your question more clear.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by przemek3d88** [comment]
Yes, I'm talking about the editorial, which is under the section "Solution". There is no separate "Editorial" section or option in the bug report.

This is the quote from the editorial:
```
Note that an array of size 3 would be insufficient, since dp[i%3] would "collide" with dp[(i+3)%3].
```

However, instead of doing a simple index % 4, you could use a circular buffer of size 3, which I pasted above. So that particular part is confusing.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
