### ISSUE TITLE
Error sum in video solution 1672. Richest Customer Wealth (The LeetCode Beginner's Guide)

### ISSUE THREAD

**Issue by Estelle-K** [LeetCode-Feedback/LeetCode-Feedback#13742]
#### Your LeetCode username
Tougirl

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the video solution (1:43), sum of Customer 3: is equal 15 (not 14)

#### Expected behavior
The sum of Customer 3: is equal 15

#### Screenshots
![20230528205439](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/79149538/3eaa793d-5a4e-4655-aace-11afd242cae3)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We will use your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
