### ISSUE TITLE
430. Flatten a Multilevel Doubly Linked List - Missing C support

### ISSUE THREAD

**Issue by sleeptightAnsiC** [LeetCode-Feedback/LeetCode-Feedback#13744]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug

User is not able to use C to solve the _430. Flatten a Multilevel Doubly Linked List_
C just don't appear on the list of available languages when attempting this problem.

This can be observed for both - the problem page, and on the _Introduction to Data Structure > Linked List  > Conclusion_ course page.
https://leetcode.com/problems/flatten-a-multilevel-doubly-linked-list/
https://leetcode.com/explore/learn/card/linked-list/213/conclusion/1225/

#### Code you used for Submit/Run operation

N/A

#### Language used for code
N/A

#### Expected behavior

C should be available for this problem, like for any other.
It should appear on the list of available languages.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/91839286/4a4526c5-7462-48aa-bc7a-6d493429ace7)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/91839286/92d8e1d7-beb8-4244-81ef-403a0c6f3209)

#### Additional context

I tested it for Opera, Chrome and MS Edge.

It seems that this issue has also been observed by the others. So it is not only appearing on my side.
For ref: https://leetcode.com/problems/flatten-a-multilevel-doubly-linked-list/discuss/2339194/Where-is-C"

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Unfortunately, we don’t support the C language for this problem.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
