### ISSUE TITLE
Editorial typo - 1547. Minimum Cost to Cut a Stick

### ISSUE THREAD

**Issue by xelplogoog** [LeetCode-Feedback/LeetCode-Feedback#13748]
### Your LeetCode username
c4tdog

#### Description of the bug
https://leetcode.com/problems/minimum-cost-to-cut-a-stick/editorial/
There is a typo in word `indices`

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2188302/f7adad81-786d-4eae-81e2-6cb8069643da)

also, would be great if you rephrase this one in description:
`You should perform the cuts in order, you can change the order of the cuts as you wish.`

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
