### ISSUE TITLE
Code Acceptance Percentage can controlled by the user 

### ISSUE THREAD

**Issue by PratikGarai** [LeetCode-Feedback/LeetCode-Feedback#1374]
#### Your LeetCode username
pratikgarai0208

#### Description of the bug
The acceptance percentage calculation in the account section seems to be a bit broken. I am able to submit the same code multiple times to increase/decrease it according to my will.

#### Expected behavior
A code comparison mechanism could be used to filter out very similar, or atleast the same submissions.

#### Screenshots
![image](https://user-images.githubusercontent.com/58355527/99134409-9df9f300-2643-11eb-9cbf-19b8ee5b9e5d.png)
I uploaded the same correct code thrice and it pushed up my acceptance percentage.

**Comment by lc-kay** [comment]
Hi @PratikGarai  ,
Thank you for your time. Upon investigating this issue, we found this issue to be non-content-related (the issue stems from an origin away from the content on this problem). Please submit this issue to our help desk through https://support.leetcode.com/hc/en-us/requests/new. Thank you for your time!
