### ISSUE TITLE
Missing Test Case - 1295. Find Numbers with Even Number of Digits

### ISSUE THREAD

**Issue by XX124188** [LeetCode-Feedback/LeetCode-Feedback#13745]
#### Category of the bug
- [V] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Hi, I was tring to count digits by divided a number by 10. 
It is expected that if the dividend is less than 10 and catched by a interger type. 
the result should be 0; However, I got a non-zero value when solving this problem.
I wonder if this is a problem to you or it is my misunderstanding of C++. 
Thanks

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    int findNumbers(vector<int>& nums) {
        
        int retEvenNums = 0;
        
        for(int i =0; i < nums.capacity(); i++)
        {
            int tempval = nums[i];
            char digitcnt = 0; 

            while(tempval)
            {
                digitcnt++;          
                tempval = tempval / 10;
            }

            if (digitcnt % 2 == 0 && digitcnt != 0)
            {
                retEvenNums++;
            }
        }
        return retEvenNums;  
    }
};
```

#### Expected behavior

 ```
  while(tempval) // In this case, tmepval can be 0.1 or 0.2 and entering the loop again. 
  {
        digitcnt++;          
        tempval = tempval / 10; // If tempval smaller than 10. output should be 0.
  }

```
However, if I modify my code into this. It will be accepted.  
 ```
  while(tempval)
  {
        if(tempval>=1) // only the number bigger than or equal 1 will count.
        {
            digitcnt++; 
        }
        tempval = tempval / 10; 
  }

```

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
