### ISSUE TITLE
1122. 数组的相对排序 | 明确数据范围下限

### ISSUE THREAD

**Issue by zerotrac** [LeetCode-Feedback/LeetCode-Feedback#1375]
**Bug 类型**

- [x] 题目

**描述**

题目描述中规定了 `arr1.length, arr2.length <= 1000`，只明确了上限而未明确下限。我测试了一下不存在 `arr1.length` 或者 `arr2.length` 等于 `0` 的情况，并且这类情况属实比较无聊，不建议（未来）放入测试数据中。

**期望行为**

将题目描述改为 `1 <= arr1.length, arr2.length <= 1000`，国服与世界服需要同步修改。

![image](https://user-images.githubusercontent.com/15974765/99144687-d250cc00-26a2-11eb-927c-bb5e39edb7b5.png)

审核通过的话 coin 给 [QXY](https://leetcode-cn.com/u/noobqxy/) 这位同学吧，他在官方题解评论区下面提出来的。

**Comment by feiceh** [comment]
😄好的，此问题已转给题目运营团队会尽快确认的～

**Comment by feiceh** [comment]
已修复。
