### ISSUE TITLE
Missing Test Case - 2. Add Two Numbers

### ISSUE THREAD

**Issue by Gayatri2002** [LeetCode-Feedback/LeetCode-Feedback#13756]
#### Category of the bug
- [Add Two Numbers ] Question 
- [/**
 * Definition for singly-linked list.
 * struct ListNode {
 *     int val;
 *     ListNode *next;
 *     ListNode() : val(0), next(nullptr) {}
 *     ListNode(int x) : val(x), next(nullptr) {}
 *     ListNode(int x, ListNode *next) : val(x), next(next) {}
 * };
 */
class Solution {
    void insertail(ListNode* &head,ListNode* &tail,int digit){
        ListNode* temp=new ListNode(digit);
        if(head==NULL){
            head=temp;
            tail=temp;
        return;
        }else{
            temp->next = head;
            head = temp; 
        }
    }

public:
    ListNode* addTwoNumbers(ListNode* l1, ListNode* l2) {
        

        if(l1->val == 0 && l2->val == 0){
            ListNode* temp=new ListNode(0);
            return temp;
        }
        int num1 =0;
        int num2 =0;
        ListNode* temp1 = l1;
        ListNode* temp2 = l2;

        while(temp1 != NULL){
            num1 = num1*10 + temp1->val;
            temp1 = temp1 -> next;
        }

        while(temp2 != NULL){
            num2 = num2*10 + temp2->val;
            temp2 = temp2 -> next;
        }

        int sum = num1 + num2;
        int newsum = 0;
        while(sum !=0){
            newsum = newsum*10 + sum%10;
            sum = sum/10;
        }

       ListNode* ans = NULL;
        
        while(newsum != 0){

            insertail(ans, ans, newsum%10);
            newsum = newsum/10;
        }
        
        return ans;
    }
}; ] Solution
- [C++ ] Language
- [l1 =[2,4,9]    
- l2 = [5,6,4,9]
Output [8,9,8,5]
Expected[7,0,4,0,1] ] Missing Test Cases 

#### Description of the bug

[2,4,9] + [5,6,4,9] = 5898
so the answer should be 8->9->8->5, which is my output. but expected output given in wrong.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

```
/**
 * Definition for singly-linked list.
 * struct ListNode {
 *     int val;
 *     ListNode *next;
 *     ListNode() : val(0), next(nullptr) {}
 *     ListNode(int x) : val(x), next(nullptr) {}
 *     ListNode(int x, ListNode *next) : val(x), next(next) {}
 * };
 */
class Solution {
    void insertail(ListNode* &head,ListNode* &tail,int digit){
        ListNode* temp=new ListNode(digit);
        if(head==NULL){
            head=temp;
            tail=temp;
        return;
        }else{
            temp->next = head;
            head = temp; 
        }
    }

public:
    ListNode* addTwoNumbers(ListNode* l1, ListNode* l2) {
        

        if(l1->val == 0 && l2->val == 0){
            ListNode* temp=new ListNode(0);
            return temp;
        }
        int num1 =0;
        int num2 =0;
        ListNode* temp1 = l1;
        ListNode* temp2 = l2;


        while(temp1 != NULL){
            num1 = num1*10 + temp1->val;
            temp1 = temp1 -> next;
        }

        while(temp2 != NULL){
            num2 = num2*10 + temp2->val;
            temp2 = temp2 -> next;
        }

        int sum = num1 + num2;
        int newsum = 0;
        while(sum !=0){
            newsum = newsum*10 + sum%10;
            sum = sum/10;
        }

       ListNode* ans = NULL;
        
        while(newsum != 0){

            insertail(ans, ans, newsum%10);
            newsum = newsum/10;
        }
        
        return ans;
    }
};

```

#### Expected behavior

[2,4,9] + [5,6,4,9] = 5898
so the answer should be 8->9->8->5, which is my output. but expected output given in wrong. Expected output is [7,0,4,0,1]

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
