### ISSUE TITLE
Missing Test Case - 1498. Number of Subsequences That Satisfy the Given Sum Condition

### ISSUE THREAD

**Issue by mnink275** [LeetCode-Feedback/LeetCode-Feedback#13764]
#### Your LeetCode username
mnink275

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
An accepted solution gets WA on the following testcase:
nums = [2,4,6]
target = 2

#### Code you used for Submit/Run operation
```
class Solution {
  const int mod = 1'000'000'007;
 public:
  int numSubseq(std::vector<int>& nums, int target) {
    if (nums.size() == 1) {
      return 2 * nums[0] == target;
    }

    std::vector<int> pows(nums.size(), 1);
    for (int i = 1; i < nums.size(); ++i) {
      pows[i] = (pows[i - 1] * 2) % mod;
    }

    std::sort(nums.begin(), nums.end());
    int counter = 0;
    for (int i = 0; i < nums.size(); ++i) {
      int right_bound = binSearch(nums, target - nums[i]);
      if (right_bound >= i) {
        counter += pows[right_bound - i];
        counter %= mod;
      }
    }

    return counter;
  }

  int binSearch(std::vector<int>& nums, int target) {
    int left = 0;
    int right = nums.size() - 1;
    while (right - left > 1) {
      int middle = (left + right) / 2;
      if (nums[middle] <= target) {
        left = middle;
      } else {
        right = middle;
      }
    }

    return (nums[right] > target) ? (left) : (right);
  }
};
```

#### Language used for code
C++

#### Expected behavior
Output: 1
Expected: 0

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
