### ISSUE TITLE
5552. 到家的最少跳跃次数 | 数据弱

### ISSUE THREAD

**Issue by zerotrac** [LeetCode-Feedback/LeetCode-Feedback#1376]
**Bug 类型**

- [x] 测试数据

**描述**
测试数据较弱，导致很多没有设定较大广度优先搜索边界的代码通过。

**测试数据构造**
[1998]
1999
2000
2000

**验证结果**
双周赛国服前 25 名中，4 / 6 / 9 / 11 / 12 / 13 / 15 / 17 名均无法通过该组测试数据。建议加入该测试数据并重新测试，但本场比赛不计入竞赛积分。

**Comment by Arsenal591** [comment]
个人认为 rejudge/unrate 均不合理，理由如下：
- 找出正确的上界并不容易，甚至可能超过了算法面试应有的难度
- 题目描述没有明显错误

**Comment by zerotrac** [comment]
> 个人认为 rejudge/unrate 均不合理，理由如下：
> 
> * 找出正确的上界并不容易，甚至可能超过了算法面试应有的难度
> * 题目描述没有明显错误

好的爱你

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认的～

**Comment by feiceh** [comment]
说的有道理，这题暂不处理。

**Comment by feiceh** [comment]
对于求职面试考题，寻找上界难度过大，并非出该题的实际意图，但仍然非常感谢扣友的贡献，我们已经对该题加入了该测试数据，并给于 zerotrac2  贡献积分奖励。
