### ISSUE TITLE
Missing Test Case - 602. Friend Requests II: Who Has the Most Friends

### ISSUE THREAD

**Issue by tlj-1999** [LeetCode-Feedback/LeetCode-Feedback#13762]
#### Your LeetCode username

潘安

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Someone may or may not apply to be a friend, but a lot of people apply to be a friend.
So a user id can not appear in requester_id  but have most friends.

#### Code you used for Submit/Run operation

```
 select r1.requester_id as id ,(
   select count(*) as count from RequestAccepted r2 where r2.requester_id =r1.requester_id||r2.accepter_id=r1.requester_id
 ) as num from RequestAccepted r1 order by num desc limit 1 ;
```

#### Language used for code

MySQL

#### Expected behavior

My code fail.

#### Additional context

this test case.
RequestAccepted =
| requester_id | accepter_id | accept_date |
| ------------ | ----------- | ----------- |
| 1            | 3           | 2016/06/03  |
| 4            | 3           | 2016/06/08  |
| 2            | 3           | 2016/06/08  |
| 5            | 4           | 2016/06/09  |

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The test case in JSON format: {"headers":{"RequestAccepted":["requester_id","accepter_id","accept_date"]},"rows":{"RequestAccepted":[[1,2,"2016/06/03"],[1,3,"2016/06/08"],[2,3,"2016/06/08"],[3,4,"2016/06/09"]]}}

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by tlj-1999** [comment]
JSON format of the&nbsp; missing test case is that:
{"headers":{"RequestAccepted":["requester_id","accepter_id","accept_date"]},"rows":{"RequestAccepted":[[1,2,"2016/06/03"],[1,3,"2016/06/08"],[2,3,"2016/06/08"],[4,3,"2016/06/09"]]}}


123456
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LeetCode-Feedback/LeetCode-Feedback"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月1日(星期四) 凌晨2:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LeetCode-Feedback/LeetCode-Feedback] Missing Test Case - 602. Friend Requests II: Who Has the Most Friends (Issue #13762)





 
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
 
The test case in JSON format: {"headers":{"RequestAccepted":["requester_id","accepter_id","accept_date"]},"rows":{"RequestAccepted":[[1,2,"2016/06/03"],[1,3,"2016/06/08"],[2,3,"2016/06/08"],[3,4,"2016/06/09"]]}}
 
We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
