### ISSUE TITLE
Missing test cases - 2130. Maximum Twin Sum of a Linked List

### ISSUE THREAD

**Issue by Sne4kers** [LeetCode-Feedback/LeetCode-Feedback#13767]
#### Your LeetCode username
Sne4kers

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The system accepts a solution that writes a prespecified list of outputs into a "user.out" file.

#### Code you used for Submit/Run operation

```
int init = []{
    ofstream("user.out", ios::out) << "6\n7\n100001\n182\n158\n130\n66\n165\n186\n168\n181\n166\n173\n3\n100001\n2\n100001\n200000\n5\n3\n938\n983\n933\n975\n910\n18619\n19798\n19036\n17922\n19368\n19858\n19967\n19887\n19923\n19832\n199474\n198345\n199312\n198850\n198096\n199275\n199404\n199425\n199652\n199236\n150001\n";

    exit(0);
    return 0;
}();

class Solution{public:int pairSum(ListNode*head){return 0;}};
```

#### Language used for code
C++

#### Expected behavior
This shouldn't be allowed as the solution function does not produce adequate answers.

#### Additional context
Either generate more test cases or add randomized tests, will be happy to contribute to any of those.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
