### ISSUE TITLE
My solution Does not appear!!

### ISSUE THREAD

**Issue by koushik395** [LeetCode-Feedback/LeetCode-Feedback#13765]
#### Your LeetCode username
koushik395

#### Category of the bug
- [ ] Question
- [✔ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
I have added a solution but it does not appear to others. When the solution link is opened it gives "That topic does not exist.". I am the only one who can see it through my account. Even it is appearing in my profile solutions. But the people who are clicking the link are unable to view my solution.
Solution Link: [Link](https://leetcode.com/problems/design-hashset/solutions/3578025/c-easy-o1-time-space-bitset-solution/)

#### Language used for code
C++

#### Screenshots

![WhatsApp Image 2023-05-30 at 14 20 46](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/81212573/4603c2c9-4de2-4b54-a711-41c47e03ab5f)

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. The page looks loading correctly on our side.

Please sign out of your account, clear the browser history and cookies, then sign in again. 

Thank you for your support.
![Screen Shot 2023-05-31 at 2 48 03 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/0af7780f-ad9f-4246-b76a-0cd0bc05f868)
