### ISSUE TITLE
Missing Test Case - 53. Maximum Subarray

### ISSUE THREAD

**Issue by hibaaman** [LeetCode-Feedback/LeetCode-Feedback#13760]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution {
    public int maxSubArray(int[] nums) {
        int currentMax = nums[0];
        int maxSoFar = nums[0];
        for (int i=1; i<nums.length;i++){
            currentMax = currentMax+nums[i];
            if (currentMax<nums[i]){
                currentMax = nums[i];
            }
            if (maxSoFar<currentMax){
                maxSoFar=currentMax;
            }
        }
        return maxSoFar;
    }
}
```

#### Language used for code
<java>

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
