### ISSUE TITLE
Editorial: Use case 2 - 2693. Call Function with Custom Context

### ISSUE THREAD

**Issue by Kim716** [LeetCode-Feedback/LeetCode-Feedback#13761]
#### Your LeetCode username

Kim716

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Editorial

#### Description of the bug

<img width="749" alt="截圖 2023-05-30 上午10 36 11" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/115907665/ebce7cb0-bb88-4f03-beb6-19c06418d9c4">

According to the Method Borrowing Example description,  it seems more reasonable to write the demonstration code like this:
```JavaScript
const calculator = {
  calculateTotal: function() {
      return this.num1 + this.num2;
  }
};

const numbers = {
  num1: 3, 
  num2: 4
};

// Using callPolyfill to borrow the calculateTotal method from calculator
const sum = calculator.calculateTotal.callPolyfill(numbers);
console.log(sum); // Output: 7
```

#### Screenshots: Previous code

[2693. Editorial Page](https://leetcode.com/problems/call-function-with-custom-context/editorial/?utm_campaign=PostD26&utm_medium=Post&utm_source=Post&gio_link_id=39lbqjpP)

<img width="754" alt="截圖 2023-05-30 上午10 38 55" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/115907665/3c034073-4dbd-4877-a132-20aa5f18673e">

Thank you:)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
