### ISSUE TITLE
Invalid Test Case - 291. Word Pattern II

### ISSUE THREAD

**Issue by nskybytskyi** [LeetCode-Feedback/LeetCode-Feedback#13774]
#### Your LeetCode username

[nskybytskyi](https://leetcode.com/nskybytskyi/)

#### Category of the bug

- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In problem [291. Word Pattern II](https://leetcode.com/problems/word-pattern-ii/), the expected answer for test case `pattern = "gh"`, `s = "i"` is `false`, but should be `true` instead.

> Given a pattern and a string s, return true if s matches the pattern.
> A string s matches a pattern if there is some bijective mapping of single characters to strings such that if each character in pattern is replaced by the string it maps to, then the resulting string is s. A bijective mapping means that no two characters map to the same string, and no character maps to two different strings.

Here, one possible bijective mapping is `'g' <=> "i"` and `'h' <=> ""`. Character `'h'` maps to an empty string `""`, but it is not prohibited by the statement.

#### Code you used for Submit/Run operation

[Submission link](https://leetcode.com/problems/word-pattern-ii/submissions/960657009/)

```cpp
class Solution {
public:
    bool wordPatternMatch(std::string pattern, std::string s) {
        return backtrack(pattern, s, 0, 0);
    }

private:
    std::array<int8_t, 26> frequency;
    std::array<std::string, 26> mapping;
    std::unordered_map<std::string, int8_t> inverse;

    bool backtrack(const std::string& pattern, const std::string& text,
                   int pattern_position, int text_position) {
        if (pattern_position == pattern.length()) {
            return text_position == text.length();
        }
        const auto key = pattern[pattern_position] - 'a';
        for (int next_text_position = text_position; next_text_position <= text.length(); ++next_text_position) {
            const auto text_substring = text.substr(text_position, next_text_position - text_position);
            if (
                (inverse[text_substring] && inverse[text_substring] != key) ||
                (!mapping[key].empty() && mapping[key] != text_substring)
            ) continue;
            ++frequency[key];
            mapping[key] = text_substring;
            inverse[text_substring] = key;
            if (backtrack(pattern, text, pattern_position + 1, next_text_position)) return true;
            if (!--frequency[key]) {
                mapping[key].clear();
                inverse.erase(text_substring);
            }

        }
        return false;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The expected answer for the above test case is changed to `true`.

#### Screenshots

![Знімок екрана 2023-05-31 о 06 26 47](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/25816558/b14f095d-e130-4b49-8cfc-cad1240e0074)

#### Additional context

An alternative way to resolve this issue is to change the problem statement to explicitly specify that characters in `pattern` should not map to empty strings.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by nskybytskyi** [comment]
@LC-Pam any updates on this one?

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
