### ISSUE TITLE
Missing Test Case - 2694. Event Emitter

### ISSUE THREAD

**Issue by MirrorShih** [LeetCode-Feedback/LeetCode-Feedback#13773]
#### Your LeetCode username

MirrorShih

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The Approach 1 code in the Editorial removes only the last callback function when unsubscribe is called. Therefore, if unsubscribe is called for any other callback function, it will result in an incorrect behavior.

#### Code you used for Submit/Run operation

I just copy it from Editorial.
```
class EventEmitter {
    constructor() {
        this.events = {};
    }

    subscribe(event, cb) {
        // If no handlers for current event - initialize an empty list
        this.events[event] = this.events[event] ?? [];
        this.events[event].push(cb);

        return {
            unsubscribe: () => this.events[event].pop(),
        };
        //To avoid memory leaks adding a cleanup condition
        if (this.events[event].length=== 0) { delete this.events[event] }
    }

    emit(event, args = []) {
        if (!(event in this.events)) return [];
        return this.events[event].map(f => f(...args));
    }
}
```

#### Language used for code

JavaScript

#### Expected behavior

The Editorial code should be Wrong Answer, but it will get Accepted when submitting it.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/42204820/9fad8375-8cc7-4f98-acf9-78ab334a06bf)

#### Additional context

The testcase I used:
["EventEmitter", "subscribe","subscribe", "emit", "unsubscribe", "emit"]
[[], ["firstEvent", "(...args) => args.join(',')"],["firstEvent", "(...args) => args.join('|')"], ["firstEvent", [1,2,3]], [0], ["firstEvent", [4,5,6]]]

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
