### ISSUE TITLE
Invalid Test Case = 5 = Longest Palindromic Substring

### ISSUE THREAD

**Issue by Tully-cmd** [LeetCode-Feedback/LeetCode-Feedback#13778]
#### Your LeetCode username
tillsix

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
String index out of bounds when accessing in bounds entry.

#### Code you used for Submit/Run operation
```
class Solution {

  public String longestPalindrome(String s) {
    
    String longestPal = "";

    for(int i = 0; i < s.length(); i+=1) {
      for(int j = i; j < s.length(); j+=1) {
        
        String palCheck = s.substring(i,j+1);

        if(palindromeCheck(palCheck)) {
          if(palCheck.length() > longestPal.length()) {

            longestPal = palCheck.toString();
          }
        }
      }
    }
    return longestPal; 
  }
  
  public Boolean palindromeCheck(String s) {
      
    int startIndex = 0;
    int endIndex = s.length() - 1;

    System.out.println(startIndex + " " + endIndex + " " +s+s.length());
    
    if(startIndex >= s.length() || startIndex < 0) {
      System.out.println("Bad code");
    }
    if(endIndex >= s.length() || endIndex < 0) {
      System.out.println("Bad code");
    }

    while(s.charAt(startIndex) == s.charAt(endIndex)) {

      if(startIndex == endIndex) {

        return true;
      } else {

        startIndex = startIndex + 1;
        endIndex = endIndex - 1;
      }
    }
    return false;
  }
}
```

#### Language used for code
Java

#### Expected behavior
If the index was truly out of bounds we would expect "Bad code" written to the console.

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/54709821/2e80ff17-13bf-4ca0-9b3d-785dfc8a3194)

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/54709821/958b1478-9122-4233-9f63-0e6c3af3740b)

Out of bounds for accessing indexes 0 and 1 with a string of length 2.

#### Additional context
https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#charAt-int-

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
