### ISSUE TITLE
Additional test case: 1654. Minimum Jumps to Reach Home

### ISSUE THREAD

**Issue by Ceay1** [LeetCode-Feedback/LeetCode-Feedback#1377]
#### Your LeetCode username
My username: Ceay, the credit for the test case to foster2 (see discussion https://leetcode.com/problems/minimum-jumps-to-reach-home/discuss/935419/python-deque-bfs-omaxx-maxforbiddenab) 

#### Category of the bug
- [ ] Question
- [ X] Solution
- [ ] Language

#### Description of the bug
The incorrect solution is not detected - no appropriate test case.

#### Code you used for Submit/Run operation

```
class Solution:
    def minimumJumps(self, forbidden: List[int], a: int, b: int, x: int) -> int:
        
        max_val=max(x, max(forbidden)+b+a)
        
        jumps=[0]+[math.inf]*(max_val)
        for pos in forbidden: jumps[pos]=-1
        
        stack=deque([0])
        
        while stack:
 
            pos=stack.popleft()

            if pos+a<= max_val and jumps[pos+a]>jumps[pos]+1:
                stack.append(pos+a)
                jumps[pos+a]=jumps[pos]+1
            if pos-b>0 and  jumps[pos-b]>jumps[pos]+1:
                jumps[pos-b]=jumps[pos]+1
                if pos-b+a<= max_val and jumps[pos-b+a]>jumps[pos]+2:
                    stack.append(pos-b+a)
                    jumps[pos-b+a]=jumps[pos]+2
      
        return jumps[x] if jumps[x]<math.inf else -1
```

#### Language used for code
Python 3

#### Expected behavior
The solution is expected to be rejected by test cases. However, there is no appropriate test case.

The test case: 
[3]
14
5
90

**Comment by lc-kay** [comment]
Hi @Ceay1 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Ceay1 
Thank you for your time. We've used your feedback to update the problem. The LeetCode account of foster2 has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
