### ISSUE TITLE
Missing Test Case - 2694. Event Emitter

### ISSUE THREAD

**Issue by bahoang3105** [LeetCode-Feedback/LeetCode-Feedback#13785]
#### Your LeetCode username: 

bahoang3105

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class EventEmitter {
  constructor() {
    this.events = {};
  }
  subscribe(event, cb) {
    if (!this.events[event]) this.events[event] = [];
    this.events[event].push(cb);
    return {
        unsubscribe: () => {
          this.events[event].pop();
        }
    };
  }

  emit(event, args = []) {
    if (!this.events[event]) return [];
    let res = [];
    for (let i in this.events[event]) {
      res.push(this.events[event][i](...args));
    }
    return res;
  }
}

/**
 * const emitter = new EventEmitter();
 *
 * // Subscribe to the onClick event with onClickCallback
 * function onClickCallback() { return 99 }
 * const sub = emitter.subscribe('onClick', onClickCallback);
 *
 * emitter.emit('onClick'); // [99]
 * sub.unsubscribe(); // undefined
 * emitter.emit('onClick'); // []
 */
```

#### Language used for code

Javascript

#### Expected behavior

Wrong Answer
When unsubscribing a subscription of an event, callback of this subscription must be removed from callback list of this event instead of the last callback in callback list of this event

#### Screenshots

![PI1pE61Avr](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73835461/9f0cbfe2-4f8c-4583-84ad-a4170fc760a5)
![KgorijuvxQ](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73835461/7870272d-47df-4271-afb4-083c8393573b)

#### Additional context

My testcase: 
Input
["EventEmitter", "subscribe", "subscribe", "emit", "unsubscribe", "emit"]
[[], ["firstEvent", "(...args) => args.join(',')"], ["firstEvent", "(...args) => args.join('.')"], ["firstEvent", [1,2,3]], [0], ["firstEvent", [4,5,6]]]

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
