### ISSUE TITLE
Missing test case - 2707. Extra Characters in a String

### ISSUE THREAD

**Issue by kk-source** [LeetCode-Feedback/LeetCode-Feedback#13790]
#### Your LeetCode username
kk-source

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

This question is passing greedy solutions also which is wrong.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int minExtraChar(string s, vector<string>& dictionary) {
        int n=s.size();
        unordered_set<string> st(dictionary.begin(),dictionary.end());
        int x=n;
        int ans=n;
        int res1=0,res2=0;
        int i=0;
        while(i<n)
        {
            string temp="";
            bool flag1=false;
            for(int j=i;j<n;j++)
            {
                temp += s[j];
                if(st.find(temp) != st.end())
                {
                    flag1=true;
                    i = j+1;
                }
            }
            if(!flag1){
                res1++;
                i++;
            }
        }
        reverse(s.begin(),s.end());
        i=0;
        while(i<n)
        {
            string temp="";
            bool flag2=false;
            for(int j=i;j<n;j++)
            {
                temp = s[j]+temp;
                if(st.find(temp) != st.end())
                {
                    flag2=true;
                    i = j+1;
                }
            }
            if(!flag2){
                res2++;
                i++;
            }
        }
        cout << res1 << " " << res2 << endl;
        ans=min({ans,res1,res2});
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

2

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/74047447/72bb5b49-3054-4697-a024-790cd6504ab0)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
