### ISSUE TITLE
Missing Test Case - 1396. Design Underground System

### ISSUE THREAD

**Issue by akankshar05** [LeetCode-Feedback/LeetCode-Feedback#13795]
#### Your LeetCode username
Akankshar05

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ *** ] Missing Test Cases 

#### Description of the bug

I have submitted a solution for this problem 1396 . it is accepted.
but it showing wrong answer in my custom testcase: 
My custom testcase:
["UndergroundSystem","checkIn","checkIn","checkOut","getAverageTime","checkOut","getAverageTime"]
[[],[45,"Leyton",3],[45,"Leyton",4], [45,"Waterloo",15],["Leyton","Waterloo"],[45,"Waterloo",18],["Leyton","Waterloo"]]

#### Code you used for Submit/Run operation

```
class UndergroundSystem {
public:
    std::unordered_map<int, std::pair<std::string, int>> checkIns;
    std::unordered_map<std::string, std::pair<int, int>> travelTimes;

    UndergroundSystem() {
        
    }
    
    void checkIn(int id, std::string stationName, int t) {
        checkIns[id] = std::make_pair(stationName, t);
    }
    
    void checkOut(int id, std::string stationName, int t) {
        std::string startStation = checkIns[id].first;
        int startTime = checkIns[id].second;
        std::string journey = startStation + "->" + stationName;
        
        if (travelTimes.find(journey) == travelTimes.end()) {
            travelTimes[journey] = std::make_pair(t - startTime, 1);
        } else {
            travelTimes[journey].first += t - startTime;
            travelTimes[journey].second++;
        }
        
        checkIns.erase(id);
    }
    
    double getAverageTime(std::string startStation, std::string endStation) {
        std::string journey = startStation + "->" + endStation;
        return (double)travelTimes[journey].first / travelTimes[journey].second;
    }
};
```

#### Language used for code

C++

#### Expected behavior

It should not be accepted as it is giving wrong answer in my custom testcase.
My custom testcase:
["UndergroundSystem","checkIn","checkIn","checkOut","getAverageTime","checkOut","getAverageTime"]
[[],[45,"Leyton",3],[45,"Leyton",4], [45,"Waterloo",15],["Leyton","Waterloo"],[45,"Waterloo",18],["Leyton","Waterloo"]]

#### Screenshots

<img width="879" alt="Screenshot 2023-06-01 at 12 12 19 AM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/88304049/c54a35ce-e30b-4d44-8abf-eb390ce1442a">

#### Additional context

no. just this test case is missing.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
