### ISSUE TITLE
Missing Test Case - 2694. Event Emitter

### ISSUE THREAD

**Issue by Sinha1994** [LeetCode-Feedback/LeetCode-Feedback#13791]
#### Category of the bug
- [ ] Question
- [ ] Missing Test Cases 

#### Description of the bug
My solution got submitted but one of the test cases that I tested is failing

#### Code you used for Submit/Run operation

```
class EventEmitter {
  constructor() {
     this.listeners = {}; 
  }
  subscribe(event, cb) {
     let evt = event;
     if(!(evt in this.listeners))
     this.listeners[evt] = [];
     this.listeners[evt].push(cb);
    return {
        unsubscribe: () => {
           if(this.listeners[event].length == 1) {
             delete this.listeners[event];
           } else {
             this.listeners[event].pop();
           }
        }
    };
  }

  emit(event, args = []) {
    let res = [];
    if(this.listeners[event])
    this.listeners[event].forEach(cb => res.push(cb(...args)));
    return res;
  }
}
```

#### Language used for code
JavaScript

#### Expected behavior
As per the problem statement if one event has multiple callbacks, then on emit, they should run sequentially, similarly if we do unsubscribe then callbacks for the event should be removed in sequence, in a first-in-first-out manner. The above code is removing callbacks in a last-in-first-out manner, so the last added callback will be removed first. And it got failed for one scenario which I tested but the solution still got submitted. 

#### Screenshots
<img width="679" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/28135546/73662952-3c4f-4180-bdff-7b3cdf35a28f">

#### Additional context
My Test case:- 

#### Input
["EventEmitter", "subscribe", "subscribe", "emit", "subscribe", "emit", "unsubscribe", "emit"]

[[], ["eventOne", "function cb1(...args) { return args.join(','); }"], ["eventOne", "function cb1(...args) { return args.join(','); }"], ["eventOne", [1,2,3]], ["eventOne", "function cb1(...args) { return args.join('_'); }"], ["eventOne", [1,2,3]], [1],  ["eventOne", [7,8,9]]]

#### Output
[[],["subscribed"],["subscribed"],["emitted",["1,2,3","1,2,3"]],["subscribed"],["emitted",["1,2,3","1,2,3","1_2_3"]],["unsubscribed",1],["emitted",["7,8,9","7,8,9"]]]

#### Expected
[[],["subscribed"],["subscribed"],["emitted",["1,2,3","1,2,3"]],["subscribed"],["emitted",["1,2,3","1,2,3","1_2_3"]],["unsubscribed",1],["emitted",["7,8,9","7_8_9"]]]

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
