### ISSUE TITLE
Missing Test Case - 2694. Event Emitter

### ISSUE THREAD

**Issue by sushiljainam** [LeetCode-Feedback/LeetCode-Feedback#13796]
#### Your LeetCode username
sushiljainam

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Question number https://leetcode.com/problems/event-emitter is missing test cases and incorrect submissions are getting accepted. Added a screenshot of accepted code from comebody I saw in memory chart, and it's failing shown test case.
If there are two subscriber functions and we unsubscribe from first one.

#### Code you used for Submit/Run operation
This is the code which is accepted, but shouldn't be.
```
class EventEmitter {
  constructor() {
    this.fns = {};
  }

  subscribe(e, cb) {
    this.fns[e] ? this.fns[e].push(cb) : (this.fns[e] = [cb]);

    return {
      unsubscribe: () => {
        this.fns[e].pop();
      },
    };
  }

  emit(e, args = []) {
    return this.fns[e]?.map((fn) => fn(...args)) || [];
  }
}
```

#### Language used for code
JS

#### Expected behavior
This code shouldn't be accepted, will work fine, if add some test cases of below nature, where we add multiple subscriber to one event and unsubscribe from past subscribers.

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/13596814/a248cebc-368e-4d8d-8178-cda2f5c097d2)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
