### ISSUE TITLE
最长回文子串

### ISSUE THREAD

**Issue by ChenWanyu1207** [LeetCode-Feedback/LeetCode-Feedback#138]
** Bug 类型**
题解

题目：给定一个字符串 s，找到 s 中最长的回文子串。你可以假设 s 的最大长度为 1000。

**你使用的语言**
python

**你提交或者运行的代码**
class Solution(object):
    def longestPalindrome(self, s):
        """
        :type s: str
        :rtype: str
        """
        windows=""
        a=""
        dicts={}
        answer=[]
        for s1 in s:
            if s1 not in windows:
                windows+=s1
            else:
                a=windows[windows.index(s1):]
                a+=s1
                windows += s1
                dicts[str(a)] = len(a)
        for key,value in dicts.items():
            if value==max(dicts.values()):
                answer.append(key)
        if answer:
            return answer[0]
        elif s:
            return s[0]
        else:
            return s
```

**期望行为**
输入"abcda"，其最长子串应为"abcda"

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![image](https://user-images.githubusercontent.com/49406875/79067839-03c07e00-7cf5-11ea-847b-cb39a619b3aa.png)

**Comment by PsiACE** [comment]
您好，我看了您提供的测试用例。需要注意的一点是，回文的定义为：正着读和反着读是一致的。而 "abcda" 显然不满足该定义，也许你可以尝试 "abcba" 。
