### ISSUE TITLE
217. Contains Duplicate

### ISSUE THREAD

**Issue by cool-man-vk** [LeetCode-Feedback/LeetCode-Feedback#13809]
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/76818423/aaea1100-667e-470a-9830-a595bc0fb58e)

Expected is **false**, and the real output is also **false** and don't know why it is **true**.

<code>
class Solution:
    def containsDuplicate(self, nums: list[int]) -> bool:
        n = len(nums)
        res = "false"
        for i in range(0 , n):
            for j in range(i+1 , n):
                if(nums[i] == nums[j]):
                    res = "true"
                    break
        return res
</code>

**Comment by kevinmonisit** [comment]
Change `res = "true"` to `res = True`. Do the same for `res = false`. They should not have quotations around `true` and `false`.

Also, capitalize `true` and `false` as that's how it's done in Python

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
