### ISSUE TITLE
187 题用例输出结果有误

### ISSUE THREAD

**Issue by hubingkang** [LeetCode-Feedback/LeetCode-Feedback#13803]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
18702606570

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [x] 编程语言
- [ ] 缺少测试用例

**描述**
189题基础用例输出结果有误

用例如下：
```
[1,2,3,4,5,6,7]
3
```
**你使用的语言**
javaScript

**你提交或者运行的代码**
```
/**
 * @param {number[]} nums
 * @param {number} k
 * @return {void} Do not return anything, modify nums in-place instead.
 */
var rotate = function(nums, k) {
  return [...nums.slice(nums.length - k), ...nums.slice(0, nums.length - k)]
};
```

**期望行为**
[5, 6, 7, 1, 2, 3, 4]

**屏幕截图**
leetcode输出结果
<img width="370" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/43019786/1338f3eb-6a58-48dd-8cc8-d3689d38be48">
期望实际结果
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/43019786/cbbd3358-2289-4b9b-b39f-d0d4cfc08957)

**额外的上下文**
无

**Comment by feiceh** [comment]
你好，在与相关团队核实后：代码块中有提到 “Do not return anything, modify nums in-place instead.”
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
