### ISSUE TITLE
Missing Test Case

### ISSUE THREAD

**Issue by Kyouma45** [LeetCode-Feedback/LeetCode-Feedback#13804]
#### Your LeetCode username

Kyouma45

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ .] Missing Test Cases 

#### Description of the bug

For question 205: Isomorphic Strings, a test case with different string lengths is missing.
Case: ehj
          el

#### Code you used for Submit/Run operation

```
//Isomorphic Strings
class Solution {
public:
    bool isIsomorphic(string s, string t) {
        std::string::iterator itr1=s.begin(),itr2=t.begin();
        unordered_map<char,char>umap;
        while(itr1!=s.end())
        {
            if(umap.find(*itr1)==umap.end()) 
            {
                umap[*itr1]=*itr2;
            }
            else
            {
                if(umap[*itr1]!=*itr2)
                    return 0;
            }
            itr1++;
            itr2++;
        }
        int arr[200]={0};
        std::unordered_map<char,char>::iterator p=umap.begin();
        while(p!=umap.end())
        {
            arr[p->second]++;
            if(arr[p->second]>1)
            {
                return 0;
            }
            p++;
        }
        return 1;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Leetcode should have given error for this case, but instead my code passed all the cases.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link.
The test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Kyouma45** [comment]
Code Submission AC:  https://leetcode.com/Kyouma45/
Test Case:
ehj
el

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link that you can find on the problem submission page.
![Screen Shot 2023-06-05 at 4 40 34 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/4cab41a3-4c7b-4e54-b1fd-8d30978ca932)

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Kyouma45** [comment]
Code Submission AC:  https://leetcode.com/problems/isomorphic-strings/submissions/961421213/
Test Case:
ehj
el

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

"ehj"
"el" 
are invalid test case. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
