### ISSUE TITLE
Editorial - Incorrect Time Complexity, Problem #559, Maximum Depth of N-ary Tree

### ISSUE THREAD

**Issue by agrawalishaan** [LeetCode-Feedback/LeetCode-Feedback#13805]
#### Your LeetCode username
iarocks

#### Category of the bug
- [ ] Question
- [X ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The problem asks us to find the maximum depth of an N-ary tree. In approach #1, the author lists a recursive solution, where we recurse down to all the children of a given node, and take the deepest child. The worst case time-complexity for this is O(n), for instance in a stick graph:

1->2->3->4

Here, to find the max depth of this unary tree, we would need to recurse all the way down to node 4. The space is O(n). In a balanced tree, the space is O(log n), i.e. the depth of the tree, but no such constraint is given in this question.

The author writes:
Space complexity : in the worst case, the tree is completely unbalanced,
e.g. each node has only one child node, the recursion call would occur
NNN times (the height of the tree), therefore the storage to keep the call stack would be O(N).
But in the best case (the tree is completely balanced), the height of the tree would be log⁡(N).
Therefore, the space complexity in this case would be O(log⁡(N).

They correctly identify the complexities for the different situations, **but at the end incorrectly summarize the space complexity as O(log n)**. We always take worst case complexities, so the space complexity should really still be O(n). This should be changed as it may be confusing to new problem solvers.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

The author is not saying “therefore the overall space complexity is O(log n)”. They are saying that it is O(log n) in the best case. The article explicitly says “in THIS case”

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
