### ISSUE TITLE
Missing Test Case - 1091. Shortest Path in Binary Matrix

### ISSUE THREAD

**Issue by avdd80** [LeetCode-Feedback/LeetCode-Feedback#13819]
#### Category of the bug
-  Missing Test Cases 

#### Description of the bug

Missing test case: Input grid of size 100x100 contains all zeros. 

#### Code you used for Submit/Run operation

```
// 1091. Shortest Path in Binary Matrix

int ** G;
int N;

#define INSERT_DELIMITER() (enq(0xDEADB000,0xDABEB0DE,0))

// peek into queue and return true if next
// element is delimiter
#define PEEK_DELIMTER() ((q[tail][0]==0xDEADB000) && (q[tail][1]==0xDABEB0DE) && (q[tail][2]==0))

int q[8425][3];
int head, tail;

void enq(int x, int y, int len)
{
    if (x < 0 || y < 0 || x >= N || y >= N || G[x][y] != 0)
        return;
    q[head][0] = x;
    q[head][1] = y;
    q[head][2] = len;
    head++;

    // Mark cell visited
    G[x][y] = 1;
}

void deq(int* x, int* y, int* len)
{
    if (x && y && len)
    {
        *x   = q[tail][0];
        *y   = q[tail][1];
        *len = q[tail][2];
    }
    tail++;
}

void initq (void)
{
    head = 0;
    tail = 0;
}

bool empty(void)
{
    return (head>tail? 0 : 1);
}

int bfs (int x, int y, int x1, int y1)
{
    int len;
    // Init queue
    initq();

    // insert root into queue;
    len = 0;
    enq(x, y, len);
    INSERT_DELIMITER();

    // while queue not empty
    while (!empty())
    {
        // extract from tail
        deq (&x, &y, &len);

        // if last element reached
        //      return length
        len++;
        if (x == x1 && y == y1)
            return len;

        // traverse and insert children
        enq(x+1,   y, len);
        enq(x-1,   y, len);
        enq(x,   y+1, len);
        enq(x,   y-1, len);
        enq(x-1, y-1, len);
        enq(x+1, y+1, len);
        enq(x-1, y+1, len);
        enq(x+1, y-1, len);

        // peek into queue to check if delimiter is present.
        // If so, insert a delimiter in queue now.
        if (PEEK_DELIMTER()) 
        {
            INSERT_DELIMITER();

            // Remove delimiter from tail end
            deq (NULL, NULL, NULL);
        }
    }
    return -1;
}

int shortestPathBinaryMatrix(int** grid, int gridSize, int* gridColSize)
{
    // Convenience variables
    N = gridSize;
    G = grid;

    // Reset queue to clean up any stale delimters
    memset (q, 0, sizeof(int) * N * N);
    return bfs (0, 0, N-1, N-1);
}
```

#### Language used for code

C

#### Expected behavior

1. Above solution uses breadth-first search and hence a queue.
2. When queue size is at least 8425, Leetcode's existing test suite passes. (Screenshot 1)
3. However, when the input grid is 100x100 and filled with all zeros (input file attached), the test case fails because the queue size is not enough. (Screenshot 2)
4. Fix for the run time failure in step 3 is to increase queue size to 10000. (Screenshot 3)

#### Screenshots

![Q8425_pass](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/3952478/9665d84a-49b2-48ae-b78f-63f2006dad4d)
![Q8425_fail_TC](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/3952478/cbcf8822-a857-431b-bf2b-834db6671964)
![Q10000_pass](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/3952478/98127f0f-bfb1-4bfe-8d2f-46be2f6fe3bb)

#### Additional context

[LC1081_failing_tc_grid_100x100.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/11628740/LC1081_failing_tc_grid_100x100.txt)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
