### ISSUE TITLE
Missing Test Case - 2618. Check if Object Instance of Class : () => checkIfInstanceOf(NaN, Object)

### ISSUE THREAD

**Issue by heykartikey** [LeetCode-Feedback/LeetCode-Feedback#13816]
#### Your LeetCode username
heykartikey

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
For the test case () => checkIfInstanceOf(NaN, Object) the code that I used should have printed true instead of false for it to get accepted. But it got accepted, probably because this particular test case is missing.

#### Code you used for Submit/Run operation

```js
var checkIfInstanceOf = function(obj, classFunction) {
    if( (!obj && obj!=0) || !classFunction || typeof classFunction != 'function')
        return false
    
    if(obj instanceof classFunction)
    {
        return true;
    }
    else if(typeof obj == 'number' && (classFunction == Number || classFunction == Object))
    {
        return true;
    }
    else if(typeof obj == 'boolean' && (classFunction == Boolean || classFunction == Object))
    {
        return true;
    }
    else if(typeof obj == 'string' && (classFunction == String || classFunction == Object))
    {
        return true;
    }
    else if(typeof obj == 'symbol' && (classFunction == Symbol || classFunction == Object))
    {
        return true;
    }
    return false;
};
```

#### Language used for code
Javascript

#### Expected behavior
The solution should have been rejected as it couldn't correctly identify the instance in aforementioned test case

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/30074980/a5e4db1b-9cf8-4d21-ab2a-dbcaf1b6f10b)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to added the testcases, but it’s impossible to have sufficient testcases where you can’t get incorrect code to fail in all situations.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
