### ISSUE TITLE
626. Exchange Seats

### ISSUE THREAD

**Issue by theajayrawat** [LeetCode-Feedback/LeetCode-Feedback#13812]
#### Your LeetCode username
theajayrawat 

#### Category of the bug
-  Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
 "ORDER BY id" is not working properly, there must be some compiler problem.

#### Code you used for Submit/Run operation

```
//626. Exchange Seats
SELECT (CASE WHEN mod(id,2)=0 THEN id-1
WHEN id= (SELECT COUNT(*) FROM seat) then id
ELSE id+1 END) AS id, student
FROM seat
ORDER BY id 
```

#### Language used for code
MySQL

#### Screenshots
Without use of ORDER by id
![Screenshot (8)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/60476050/9f52165c-9bbb-48d7-bef6-f9d25a09a690)

With use of ORDER by id
![Screenshot (9)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/60476050/e15b8f16-b47b-44fb-bfdc-d950cea09ed6)

#### Additional context
As we can see ORDER by id only sort column id but student column remain same

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
