### ISSUE TITLE
Problems navigating the problem list

### ISSUE THREAD

**Issue by markalavin** [LeetCode-Feedback/LeetCode-Feedback#13818]
I like to go through LeetCode problems in numerical order (OK, so I'm a little OCD).   It used to be that when I was done with a particular problem, say, #1004, I could click on the ">" in the upper left corner of the screen to advance to the next problem #1005.   Now, when I click on the ">", it takes me to problem #1 and then I have to go through screen after screen from "all problems" til I find the number I want.   This is really a pain.  Could you please revert the ">" behavior to what it had been previously (go to the problem with the next number after the current one) or give me a little window where I can enter the problem number I'm interested in.   Thanks,  -- Mark

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've submitted your feedback to the team. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
