### ISSUE TITLE
458. Poor Pigs - Wrong Solution

### ISSUE THREAD

**Issue by whoami90506** [LeetCode-Feedback/LeetCode-Feedback#1382]
#### Your LeetCode username

whoami90506

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

There are two problems with the solution.
1. The question says that pigs will die if they drink the poison. Therefore dead pigs should not join further tests.
2. Even though dead pigs can survive, n pigs and test 2^n groups of buckets, not n+1 groups. Take 2 pigs and 4 buckets for example. We give buckets numbers from 0 to 3(00 to 11 in binary). The first pig drinks the buckets whose first bit is 1(i.e. 10 and 11), and the second pig drinks the buckets whose second bit is 1(i.e. 01 and 11). If only the first pig dies, the poison is in bucket 10. If only the second pig dies, the poison is in bucket 01. If both pigs die, the poison is in bucket 11. If none of the pigs die, the poison is in bucket 00. Therefore 4 buckets only need 2 pigs to identify the poison bucket.

#### Code you used for Submit/Run operation

```c++
class Solution {
public:
    int poorPigs(int buckets, int minutesToDie, int minutesToTest) {
        ios::sync_with_stdio(false);
        cin.tie(0);
        
        // trival
        if(buckets == 1)return 0;
        const int round = min(minutesToTest / minutesToDie, 31);      
        
         // init
         int pig = 1;
         int *conbs = new int[31]; // [die]
         conbs[0] = 1;
         for(int i = 0; i < 31; ++i)_dp[i] = 0;
        
         // calculate
         while(true){
             // init
             int conb = 1;
             _dp[pig-1] = new long[round];
             for(int i = 0; i < round; ++i)_dp[pig-1][i] = (1 << pig);
            
            
             for(int die = 1; die < pig; ++die){
                 conb = long(conb) * long(pig+1-die) / long(die);
                 conbs[die] = conbs[die-1] + conb;
               
                 for(int r = 1; r < round; ++r)
                     _dp[pig-1][r] = max(_dp[pig-1][r], long(conbs[die]) *long( _dp[pig-die-1][r-1]));
             }           
            
             if(_dp[pig-1][round-1] >= buckets)break;
             ++pig;
         }
        
         // end
         delete [] conbs;
         for(int i = 0; i < 31; ++i){
             if(_dp[i])delete [] _dp[i];
             else break;
         }
        
         return pig;
        
    }
private:
    int *_dp[31]; // dp[pig-1][round-1]
};
```

#### Language used for code

C++

#### Expected behavior

Assume that we have n pigs.
If we want to lose exactly 2 pigs during one test, we can separate buckets into C(n, 2) = n * (n-1) /2 groups.
If we want to lose at most 2 pigs during one test, we can separate buckets into C(n, 0) + C(n, 1) + C(n, 2)  groups.
If we want to lose exactly m pigs during one test, we can separate buckets into C(n, m) groups.
If we want to lose at most m pigs during one test, we can separate buckets into (sumantion C(n, i), for i in 0 to m)  groups.

We define f(p, r)is the maximum buckets that can find the poison bucket with p pigs and r round of tests.
The problem gives round R and target N buckets and finds the minumin pigs p such that f(p, R) >= N.
We have the initial value f(0, r) = 1 and f(p, 1) = 2^p.
The recursive relation is f(p, r) = max( (sumantion C(p, j), for j in 0 to i) * f(p-i, r-1) ) for i in 1 to p-1
Therefore, it is a dynamic programming problem.

**Comment by lc-kay** [comment]
Hi @whoami90506 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @whoami90506 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
