### ISSUE TITLE
Missing Test Case - 1615. Maximal Network Rank

### ISSUE THREAD

**Issue by 091-shivani** [LeetCode-Feedback/LeetCode-Feedback#13820]
#### Your LeetCode username
091_shivani

#### Category of the bug
Missing Test Case

#### Description of the bug

the solution i will be providing is not working for the given testcase but still the solution is getting fully accepted.
roads=[[0,1],[0,3],[0,2],[1,3],[1,2],[3,4],[2,5]]
n=6

#### Code you used for Submit/Run operation

class Solution { // frash
public:
    int maximalNetworkRank(int n, vector<vector<int>>& roads) {
        // passing some trivial cases
        if (n <= 2 || roads.size() == 0) return roads.size();
        // populating the adj list as a O(1) set per node
        vector<unordered_set<int>> adj_list(n, unordered_set<int>{});
        for (int i = 0; i < roads.size(); i++) {
            adj_list[roads[i][0]].insert(roads[i][1]);
            adj_list[roads[i][1]].insert(roads[i][0]);
        }
        // calc first and second maxes
        int max1 = 0, max2 = 0, imax1 = -1, imax2 = -1;
        for (int i = 0; i < n; i++) {
            int node_degree = adj_list[i].size();
            if (max1 < node_degree) {
                imax2 = imax1; max2 = max1;
                imax1 = i; max1 = node_degree;
            } else if (max2 < node_degree) {
                imax2 = i; max2 = node_degree;
            }
        }
        // just for those maxes find the best matches and the total max
        int ret = 0;
        for (int i = 0; i < n; i++) {
            int node_degree = adj_list[i].size();
            if (i != imax1) ret = max(ret, max1 + node_degree - (adj_list[i].count(imax1)?1:0));
            if (i != imax2) ret = max(ret, max2 + node_degree - (adj_list[i].count(imax2)?1:0));
        }
        return ret;
    }
};  
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior

the testcase provided is not working for the solution given but still the answer is getting accepted

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
