### ISSUE TITLE
Wrong Test Case Answer - 198. House Robber

### ISSUE THREAD

**Issue by fsiyah** [LeetCode-Feedback/LeetCode-Feedback#13822]
#### Your LeetCode username

FSiyah

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

There is a wrong answer for the test case [2,1,1,2].
4 is expected however the correct answer should be 3.

#### Code you used for Submit/Run operation

```
// 198. House Robber
class Solution:
    loot = [0, 0]
    def rob(self, nums: List[int]) -> int:
        self.loot = [0, 0]
        for i in range(len(nums)):
            if i%2 == 0:
                self.loot[i%2] += nums[i]
            elif i%2 == 1:
                self.loot[i%2] += nums[i]
        print(self.loot)
        return max(self.loot)
```

#### Language used for code

Python3

#### Expected behavior

I ran the test case and then a wrong answer warning appeared for the test case [2,1,1,2].   
4 is expected however 3 should be which is the correct answer.

#### Screenshots

[Screenshot via imgbb.com](https://ibb.co/4Kybb5L)

#### Additional context

Sincerly

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
