### ISSUE TITLE
Wrong TestCase in Question: 334 (Increasing Triplet Subsequence)

### ISSUE THREAD

**Issue by pranathivadrevu** [LeetCode-Feedback/LeetCode-Feedback#13823]
#### Your LeetCode username
PranathiVadrevu

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Testcase 65: [20,100,10,12,5,13]
Here there is no increasing triplet for this nums list. As per my code, I received False as the output, but the console shows it as True, which is incorrect.

#### Code you used for Submit/Run operation
Please make sure you wrap your code with ``` tags. 
Otherwise we may reject your request. 

```
// 334. Increasing Triplet Subsequence
class Solution:
    def increasingTriplet(self, nums: List[int]) -> bool:
        window_size = 3
        n = len(nums)-window_size+1
        for i in range(0, n):
            j = i+1
            k = i+2
            if(nums[i]<nums[j]<nums[k]):
                return True
        return False
```

#### Language used for code
Python 3

#### Expected behavior
It should provide the output as False instead of True because none of the triplets is in the increasing order of nums[i]<nums[j]<nums[k] pattern.

#### Screenshots
![Screenshot 2023-06-01 170806](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/50130296/7502aae9-d760-463d-a671-d6fe3474071b)

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
