### ISSUE TITLE
Missing Test Case - 2101. Detonate the Maximum Bombs

### ISSUE THREAD

**Issue by sahil1678kumar** [LeetCode-Feedback/LeetCode-Feedback#13837]
#### Your LeetCode username

sahil1678kumar

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language 
- [ ] Missing Test Cases

#### Description of the bug

I believe the result for one of the sample test cases is wrong. 

#### Code you used for Submit/Run operation

```
class Solution {
public:

    bool isConnected(vector<int> bomb1, vector<int> bomb2){
        long long int x1 = (long long int)bomb1[0], y1 = (long long int)bomb1[1], r1 = (long long int)bomb1[2];
        long long int x2 = (long long int)bomb2[0], y2 = (long long int)bomb2[1], r2 = (long long int)bomb2[2];

        long long distancCenter = (long long) (x1-x2)*(x1-x2) + (y1-y2)*(y1-y2);

        return (long long) ceil(sqrt(distancCenter)) < (long long) (r1+r2);
    }

    int dfs(int i, vector<int> &visited, vector<vector<int>> &adjList){
        int count = 0;
        visited[i] = 1;
        for(auto x : adjList[i]){
            if(visited[x] == 0){
                count += 1 + dfs(x, visited, adjList);
            }
        }
        return count;
    }

    int maximumDetonation(vector<vector<int>>& bombs) {
        int num = bombs.size();
        vector<vector<int>> adjList (bombs.size());

        for(int i=0; i<num; i++){
            for(int j=i+1; j<num; j++){
                if(isConnected(bombs[i], bombs[j])){
                    adjList[i].push_back(j);
                    adjList[j].push_back(i);
                }
            }
        }

        int maxConnected = 0;
        vector<int> visited(num, 0);

        for(int i=0; i<num; i++){
            if(visited[i] == 0){
                maxConnected = max(maxConnected, dfs(i, visited, adjList));
            }
        }

        return maxConnected + 1;
    }
};
```

#### Language used for code

C++

#### Expected behavior

For the test case number 118  , the expected output shown is 1, but the correct output should be 2. The maximum bombs that we can detonate are 2. Bombs at the coordinate and radius (69,51,7) and  (65,59,3) overlap each other, and hence detonating either one will detonate another one too. 
Test case 118 : [[54,95,4],[99,46,3],[29,21,3],[96,72,8],[49,43,3],[11,20,3],[2,57,1],[69,51,7],[97,1,10],[85,45,2],[38,47,1],[83,75,3],[65,59,3],[33,4,1],[32,10,2],[20,97,8],[35,37,3]]

**Comment by ksaxena149** [comment]
Yes that's correct, just spent half an hour trying to fix my code but then I realized the test case was wrong, so frustrating!

**Comment by ksaxena149** [comment]
No, they will not detonate, since the centers of the two bombs are not in the explosion zone

**Comment by shloksingh10** [comment]
Yes, I exactly have the same issue. As the circles are overlapping. They should detonate.

**Comment by shloksingh10** [comment]
@sahil1678kumar Basically, for the bombs to explode another circles centre should be inside one of the zone.

**Comment by sahil1678kumar** [comment]
@ksaxena149 is absolutely correct, for bombs to detonate, the location of bomb (x and y coordinate) should lie inside the former circle, and not that circle should be overlapping.
