### ISSUE TITLE
220题，题目描述与代码区变量名不一致

### ISSUE THREAD

**Issue by Caesar-Victory** [LeetCode-Feedback/LeetCode-Feedback#13838]
**surpassmath**

**Bug 类型**
题目描述与代码区形参不一致

**描述**
题目描述与代码区变量名不一致，题目区分别使用了t, k，而代码区形参分别为`valueDiff`, `indexDiff`

题目链接：

https://leetcode.cn/problems/contains-duplicate-iii/

注：无法上传图片，已截图反馈给微信力扣客服君。

**Comment by feiceh** [comment]
感谢反馈，当前题目已更新，奖励已发放。
