### ISSUE TITLE
1230. Toss Strange Coins || Description 

### ISSUE THREAD

**Issue by SeifMostafa** [LeetCode-Feedback/LeetCode-Feedback#13836]
#### Your LeetCode username
csseifms

#### Category of the bug
- Question

#### Description of the bug
1230. Toss Strange Coins || Description/problem statement is not clear.

#### Code you used for Submit/Run operation
```
        double[] dp = new double[target + 1];
        dp[0] = 1.0;
        for (int i = 0; i < prob.length; ++i)
            for (int k = Math.min(i + 1, target); k >= 0; --k)
                dp[k] = (k > 0 ? dp[k - 1] : 0) * prob[i] + dp[k] * (1 - prob[i]);
        return dp[target];
```

#### Language used for code
Java

#### Expected behavior

please check this comment: https://leetcode.com/problems/toss-strange-coins/description/comments/1898346

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link.
The details explain that statement is not clear.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by SeifMostafa** [comment]
The code submission AC link:
https://leetcode.com/submissions/detail/962213687/
The details explain that statement is not clear:
Could be replaced with
"Return the overall probability of getting heads, **target number of times,** if you toss every coin exactly once."

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
