### ISSUE TITLE
Missing Test Case - 19. Remove Nth Node From End of List

### ISSUE THREAD

**Issue by xunjizhe** [LeetCode-Feedback/LeetCode-Feedback#13839]
#### Your LeetCode username
 寻迹

#### Category of the bug
- [ √] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
 我定义·一个·函数，在函数中对头指针进行修改貌似对于主函数的头指针没有任何影响，例如赋值head = head->next 对于主函数的head没有任何影响（该head并非递归调用的，而是真的头结点），我不知道这是编辑器的问题还是什么其他的， 拙见为编辑器是否在使用函数时，对于一个新指针进行了赋值操作， 只有这样才会导致函数里的赋值对于主函数没有影响

#### Code you used for Submit/Run operation

```
void set_list(struct ListNode* head) {
    if(head == NULL) return;
    
    head = head->next;

    return ;
}

struct ListNode* removeNthFromEnd(struct ListNode* head, int n){
    set_list(head);

   return head;
}
```

#### Expected behavior

期望返回head->next，实际返回的仍然是head

#### Screenshots

实际返回：
![`5449VG)8 )YNZENS183 E](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/127122981/7409e527-754c-4fa7-9eed-5b690aedc267)
期望返回：
![Y4WT103X(774TUOQB8(5YCO](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/127122981/b4dea5d6-5fb8-4a4a-8e64-1f91b50f09e6)

#### Additional context

这并非解题代码，仅表明我发现的错误

**Comment by feiceh** [comment]
你好，建议添加 未通过代码，以便相关团队定位排查。
