### ISSUE TITLE
Testcases need to fix for: https://leetcode.com/problems/exchange-seats/

### ISSUE THREAD

**Issue by Great-G** [LeetCode-Feedback/LeetCode-Feedback#13835]
#### Your LeetCode username

GreatG

#### Category of the bug
- [ ] Question
- [X ] Solution
- [ ] Language
- [ X] Missing Test Cases 

#### Description of the bug

For the 1st Test case Expected output is exactly the same as the input which is causing our code to fail. Please see the comments there are thousands of coders who reported the same.

I somehow manage to handle the 1st test Case then I got trapped in another test case in which all the rows are swapped except the last two in the expected result, which again cause my code to fail during submission.

**PLEASE FIX THIS UP ASAP AS I AM IN MY WAY TO SQL50 BADGET** and this one question with the correct answer is stopping me to do that.

Thank you! Please provide some notification that this question got fixed so that we the ppl facing the issue can re-attempt it.

#### Code you used for Submit/Run operation

```
SELECT id,
CASE WHEN id%2 = 0 THEN
LAG(student,1) OVER (ORDER BY id)
WHEN id%2 = 1 THEN
IFNULL(LEAD(student,1) OVER (ORDER BY id),student)
END AS student
FROM Seat
```

#### Language used for code

MYSQL

#### Expected behavior

I want the Test case to be fixed and we will get a notification that this issue got fixed and we can re-attempt to complete this question.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by Great-G** [comment]
Any update on it? I report this issue 3 days back, pls provide the update, TIA

**Comment by Great-G** [comment]
As I reported a genuine issue/bug with the Test Cases which many people are facing and now it got fixed. Shouldn't I receive 100 Leetcode coins for this? as per your policy?

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/135320216/0a79e2e1-fcad-46d9-86e5-ef0c9ca7ddcc)
