### ISSUE TITLE
Wrong Test Case - 1698. Number of Distinct Substrings in a String

### ISSUE THREAD

**Issue by arindam369** [LeetCode-Feedback/LeetCode-Feedback#13846]
#### Your LeetCode username
its_me_ari

#### Category of the bug
- [ ] Wrong Test Case

#### Description of the bug
I have solved this  solution and pass all the testcases except the last testcase #78 that passes the string as nothing. This behaviour is not expected as the string's  size must be greater than 1. It was clearly mentioned in the Constraints section. So, solutions are not getting accepted due to this one testcase. Please fix this.

#### Code you used for Submit/Run operation

```
class Solution {
    class TrieNode{
        public:
            TrieNode *links[26];
    };
    class Trie{
        public:
            TrieNode *root;
            Trie(){
                root = new TrieNode();
            }
            int countDistinctSubstrings(string word){
                TrieNode *temp = root;
                int n = word.size(), ans=0;

                for(int i=0; i<n; i++){
                    temp = root;
                    for(int j=i; j<n; j++){
                        if(temp->links[word[j]-'a'] == NULL){   // distinct substring found
                            temp->links[word[j]-'a'] = new TrieNode();  ans++;
                        }
                        temp = temp->links[word[j]-'a'];
                    }
                }
                return ans;
            }
    };
public:
    int countDistinct(string s) {
        Trie *trie = new Trie();
        return trie->countDistinctSubstrings(s);
    }
};
```

#### Language used for code
C++

#### Expected behavior

It should pass and mark an ACCEPTED solution, but it just failed the last testcase #78 which passes the string nothing. Though it is clearly mentioned there in the constraints that s.length must be >= 1.

#### Screenshots
<img width="383" alt="testcase issue 2" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/92720594/e7c4d311-8b2a-48a4-9546-6dac8beacbef">
<img width="279" alt="constraint" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/92720594/e9218952-e12b-4344-9e9a-8c5495ed8acf">
<img width="365" alt="testcase issue" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/92720594/2484a6dc-d7b1-4cb1-94c4-db67042e3dec">

Due to this, my solution has been marked as "Memory Limit Exceeded". It has not yet been ACCEPTED. Please fix this issue.

**Comment by LC-Pam** [comment]
Thank you for your attention.

In competitive programming, the "Memory Limit Exceeded" means that the space complexity of your algorithm is not sufficient to solve the problem. It's a good idea to find a way to reduce the complexity of space.

We have not provided information about the memory limit yet. On the one hand, it is worth noting that memory limits are not the same for different problems and different languages, so it is difficult to give an exact limit. On the other hand, "Memory Limit Exceeded" is a relatively rare situation, some problems will not deliberately create difficulties for you in this respect, so you have to optimize memory.

View some examples and reasons about MLE may help you.  
https://www.quora.com/What-kind-of-problems-give-an-MLE-memory-limit-exceeded

If you have any questions, please feel free to contact us.

Best Regards,
LeetCode Team
