### ISSUE TITLE
1638. Count Substrings That Differ by One Character - Misleading Problem Description

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#1384]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ √ ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

In the problem description, the problem asks for "the number of ways you can choose a non-empty substring of s and replace a single character by a different character such that the resulting substring is a substring of t", or equivalently, "in other words, find the number of substrings in s that differ from some substring in t by exactly one character". However, the problem actually asks for the number of pairs of "matching" substrings s' from s and t' from t, such that we can replace a single character in s' by a different character to result in t'. This understanding can be infered from Example 2 and the actual accepted codes, which I believe is inequivalent to the problem description.

There's others who misread the description, e.g. https://leetcode.com/problems/count-substrings-that-differ-by-one-character/discuss/917701/C%2B%2BJavaPython3-O(n-3)-greater-O(n-2). I recommend fixing the problem description so that it matches the actual codes.

#### Expected behavior

In Example 2, the input is s = "ab", t = "bb" and the output is 3. But according to the problem description, only the substrings "a" and "ab" in s satisfies "differ from some substring in t by exactly one character", so the output should be 2.

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for your time. The team reviewed your report and concluded that the problem description is correct. Please refer to the post you mentioned for clarification, the original author stated that he misread the question.
