### ISSUE TITLE
Missing Test Case: 837. New 21 game

### ISSUE THREAD

**Issue by A5HU705H** [LeetCode-Feedback/LeetCode-Feedback#13844]
**Reason** :  wrong solutions accepted because you missed this testcase
**Code**:

    class Solution {  
    public:
        //incorrect code that passes
        double new21Game(int n, int k, int maxPts) {
             if(n == 0 || k == 0){ return 1.0; }
            if( n < k ){ return 0.0;}
            double dp[n + 1];
            double prob = 1.0/maxPts;
            double sliding = 0;
    
            dp[1] = prob;
    
            if( k == 1){return min(1.0, (1.0*n)/maxPts);}
            if( maxPts >= k ){
                for(int i = 2; i < k; i++){
                    sliding+=dp[i-1];
                    dp[i] = prob * (1 + sliding);
                }
                
                sliding+=dp[k-1];
                double ans = 0.0;
                if(maxPts > n){
                    for(int i = k; i <= n; i++){
                        dp[i] = prob * (1 + sliding);
                        ans += dp[i];
                    }
                    return min(ans, 1.0);
                }
                for(int i = k; i <= maxPts; i++){
                    dp[i] = prob * (1 + sliding);
                    ans += dp[i];
                }
    
                for(int i = maxPts + 1; i <= n; i++){
                    dp[i] = max(0.0, (sliding) * prob);
                    ans += dp[i];
                    sliding -= dp[i - maxPts];
                }
                return ans; 
            }
    
            for(int i = 2; i <= maxPts; i++){
                sliding+=dp[i-1];
                dp[i] = prob * (1 + sliding);
            }
            sliding+=dp[maxPts];
            for(int i = maxPts + 1; i < k; i++){
                dp[i] = (sliding) * prob;
                sliding += (dp[i] - dp[i - maxPts]);
            }
            double ans= 0.0; 
            for(int i = k; i <= n; i++){
                dp[i] = (sliding - ans) * prob; /*here max between 0.0 and this expression should have been done*/
                sliding += (dp[i] - dp[i - maxPts]); 
                ans += dp[i];
            }
    
            return ans;
        }
    };
**Test Cases** :

      n = 70
      k = 30
      maxPts = 20

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by A5HU705H** [comment]
https://leetcode.com/problems/new-21-game/submissions/957009851/

this is the AC link for this code
