### ISSUE TITLE
Missing Test Case - 1797. Design Authentication Manager

### ISSUE THREAD

**Issue by Krish-Vish** [LeetCode-Feedback/LeetCode-Feedback#13841]
#### Your LeetCode username
vishnoichirag1

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Some test-cases are missing for the tokenId which can be hacked easily.

#### Code you used for Submit/Run operation

class AuthenticationManager {
public:
    map<string,int> mp;
    AuthenticationManager(int timeToLive) {
        mp["time"] = timeToLive;
    }
    
    void generate(string tokenId, int currentTime) {
        mp[tokenId] = currentTime + mp["time"];
    }
    
    void renew(string tokenId, int currentTime) {
        if(currentTime < mp[tokenId]) mp[tokenId] = currentTime + mp["time"];
    }
    
    int countUnexpiredTokens(int currentTime) {
        int c = 0;
        for(auto it: mp) {
            if(it.second > currentTime and it.first!="time") c++;
        }
        return c;
    }
};

/**
 * Your AuthenticationManager object will be instantiated and called as such:
 * AuthenticationManager* obj = new AuthenticationManager(timeToLive);
 * obj->generate(tokenId,currentTime);
 * obj->renew(tokenId,currentTime);
 * int param_3 = obj->countUnexpiredTokens(currentTime);
 */
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

C++

#### Expected behavior

Due to the missing test-case, the code will be accepted by LeetCode but if we enter tokenId as "time" in the above code, it should fail as it will update the currentTime and might give wrong answers. So due to missing test case, the solution will be accepted which is actually wrong and can be hacked easily.

Missing test case:
["AuthenticationManager","renew","generate","countUnexpiredTokens","generate","renew","renew","countUnexpiredTokens"]
[[5],["time",1],["aaa",2],[6],["bbb",7],["aaa",8],["bbb",10],[15]]

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/134701554/32802ba2-8b85-412f-89be-545f265b09e7)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Krish-Vish** [comment]
AC code submission link: https://leetcode.com/submissions/detail/962438551/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
