### ISSUE TITLE
Missing Test Case - 2101. Detonate the Maximum Bombs

### ISSUE THREAD

**Issue by kauajuno** [LeetCode-Feedback/LeetCode-Feedback#13840]
#### Your LeetCode username
kauajuno

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [V] Missing Test Cases 

#### Description of the bug
There should be a test case where there are some bombs in the exact same location but far from the chain of bombs that are in fact generating the highest amount of explosions. I've submitted the following code but I think it shouldn't be a valid solution:

#### Code you used for Submit/Run operation

```

class Solution {
public:
    // TODO: this definitely can be much better + wouldn't work in case there were more test cases
    int maximumDetonation(vector<vector<int>>& bombs) {
        map<pair<int, int>, bool> bpmap, copymap;
        map<pair<int, int>, int> radiusmap;
        int highest = 1, highestPattern = 1;
        for(vector<int> b : bombs){
            if(bpmap.find(make_pair(b[0], b[1])) != bpmap.end()){
                highest++;
                highestPattern++;
            }
            bpmap[make_pair(b[0], b[1])] = false;
            radiusmap[make_pair(b[0], b[1])] = b[2];
        }
        for(vector<int> b : bombs){
            int score = highestPattern;
            stack<vector<int>> s;
            s.push(b);
            
            copymap = bpmap;
            copymap[make_pair(b[0], b[1])] = true;
            while(!s.empty()){
                vector<int> currBomb = s.top();
                s.pop();
                for(auto it = copymap.begin(); it != copymap.end(); it++){
                    if(!copymap[it->first] && distance(it->first, make_pair(currBomb[0], currBomb[1])) <= currBomb[2]){
                        s.push({it->first.first, it->first.second, radiusmap[it->first]});
                        copymap[it->first] = true;
                        score++;
                    }
                }
            }
            if(score > highest) highest = score;
        }
        return highest;
    }

    float distance(pair<int, int> a, pair<int, int> b){
        return sqrt(pow(a.first - b.first, 2) + pow(a.second - b.second, 2));
    }
};
```

#### Language used for code
C++ 

#### Additional context
The code I've wrote works for cases in which there are some bombs in the exact same position and they're in fact generating the highest explosion chain, but it should generate a wrong answer in a case where there are bombs in the same position but there's another bomb chain of bombs that probably are not in the same position but will generate more explosions (and that case isn't being tested).

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:


The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by kauajuno** [comment]
The missing test case should be something like I said, there's a big chain of bombs that will explode together and a small amount of bombs separated of that chain but located on the exact same place of each other.

This example should work:

[[1,2,3],[2,3,1],[3,4,2],[4,5,3],[5,6,4],[10, 10, 2], [10, 10, 2]]

Desired result would be 5 but my code would output 6

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
