### ISSUE TITLE
Missing Test Case - 1423. Maximum Points You Can Obtain from Cards

### ISSUE THREAD

**Issue by SomenSin** [LeetCode-Feedback/LeetCode-Feedback#13855]
#### Your LeetCode username

somendrasingh019

#### Category of the bug

- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    int maxScore(vector<int>& cp, int k) {
        
        int n=cp.size(),i=0,j=n-k-1,ans=INT_MIN;
        vector<int> ps(n+1,0);
        ps[0] = cp[0];
        for(int x=1;x<n;x++) {
            ps[x] = cp[x]+ps[x-1]  ;
        }
        if(k==n) {
            return ps[n-1];
        }
        int t=ps[n-1],sas = ps[j];
        while(j<n) {
            ans = max(ans,t-sas);
            j++,i++;
            sas = ps[j] - ps[i-1];
        }
        return ans;
    }
};
```

#### Expected behavior

Input
cardPoints = [8, 4, 6, 9, 2, 7, 3, 5, 1, 10]
k = 4
Output : 28
Expected : 28

**Comment by LC-Pam** [comment]
![Screen Shot 2023-06-06 at 3 35 01 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/8dba1e25-c51e-4a5d-9c53-aed5a5f1105a)
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
