### ISSUE TITLE
New test case for 1658. Minimum Operations to Reduce X to Zero

### ISSUE THREAD

**Issue by VasE1980** [LeetCode-Feedback/LeetCode-Feedback#1386]
#### Your LeetCode username

VasE2020

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

input
[500,1,4,2,3]
500
my code fails, but all your tests pass.

#### Code you used for Submit/Run operation

```
class Solution {
    public int minOperations(int[] nums, int x) {
        int rV = Integer.MAX_VALUE;

        int i1 = 0;
        int i2 = nums.length - 1;
        int sum = 0;
        int cnt = 0;

        while (i2 >= 0 && sum < x) {
            sum += nums[i2]; i2--; cnt++;
        }
        if(sum == x && cnt < rV) rV = cnt;
        if(i2 > -1) {
            while (i2 < nums.length - 1) {
                i2++;
                sum -= nums[i2];
                cnt--;
                while (i1 < i2 && sum < x) {
                    sum += nums[i1]; i1++; cnt++;
                } if(i1 == nums.length) break;
                if(sum == x && cnt < rV) rV = cnt;
            }
        }

        return rV == Integer.MAX_VALUE ? -1 : rV;
    }

}
```

#### Language used for code

Java

#### Screenshots

![изображение](https://user-images.githubusercontent.com/59063496/99178151-82fdb080-2721-11eb-9141-83c55e178dd9.png)

**Comment by lc-kay** [comment]
Hi @VasE1980 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @VasE1980 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
