### ISSUE TITLE
Missing Test Case - 268. Missing Number

### ISSUE THREAD

**Issue by lahari07** [LeetCode-Feedback/LeetCode-Feedback#13862]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior

Leetcode problem 268. Missing number: In the test cases, I tried checking a case where nums is only of length 1, and the nums[0] > 1, for example:
  nums = [2], in this case, the return value should be 0, but when I try to add the test case, it throws back an error saying **_'nums' must consist of values from 0 to 1 only_**

#### Screenshots

Check the console section in the below-attached screenshots for more context
<img width="1440" alt="Screenshot 2023-06-03 at 7 03 40 AM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/28506408/f0536246-609d-44d1-8d6d-fec0f2306e96">

<img width="1440" alt="Screenshot 2023-06-03 at 7 03 59 AM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/28506408/22ed85cf-7a06-43d6-a837-cad83c857d15">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.
The  test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by lahari07** [comment]
Here is the code I wrote in Java:
`class Solution {
    public int missingNumber(int[] nums) {
        Arrays.sort(nums);
        int prev = nums[0];
        if(prev != 0){
            return 0;
        }
        for(int i=1;i<nums.length;i++){
            if(nums[i]-prev!=1){
                return prev+1;
            } else {
                prev = nums[i];
            }
        }
        return prev+1;
    }
}`

The test case I passed was: [2]

**Comment by lahari07** [comment]
NVM, I just realized that I was passing in an invalid test case. Thank you so much for looking into this.
