### ISSUE TITLE
Missing Test Case - 1547. Minimum Cost to Cut a Stick

### ISSUE THREAD

**Issue by qingy2019** [LeetCode-Feedback/LeetCode-Feedback#13869]
#### Your LeetCode username

qingy2023

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An AC solution gets wrong answer on this test case
```
n = 9
cuts = [8,6,7]
```
#### Code you used for Submit/Run operation

```Kotlin
class Solution {
    fun minCost(n: Int, cuts: IntArray): Int {
        if (cuts.toList() == listOf(n-1, n-3, n-2)) return cuts.size
        val cache = mutableMapOf<Pair<Int, Int>, Int>()
        fun dfs(from: Int, to: Int): Int {
            return cache.getOrPut(from to to) {
                var min = 0
                cuts.forEach {
                    if (it in from + 1..to - 1) {
                        val new = to - from + dfs(from, it) + dfs(it, to)
                        if (min == 0 || new < min) min = new
                    }
                }
    
                min
            }
        }
        return dfs(0, n)
    }
}
```

#### Language used for code

Kotlin

#### Expected behavior

Expected is 14 but gets 3

#### Screenshots

<img width="378" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/66195939/075118a0-4fb4-45c3-a4da-37b9e7e59ca5">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
