### ISSUE TITLE
缺少測試案例-26。 從排序陣列中刪除重複

### ISSUE THREAD

**Issue by chris911024** [LeetCode-Feedback/LeetCode-Feedback#13866]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by feiceh** [comment]
没有填写信息，本次 Ticket 将关闭，如有需要请重新提交反馈。
