### ISSUE TITLE
Incorrect Vim Mode Substitution

### ISSUE THREAD

**Issue by ZaydH** [LeetCode-Feedback/LeetCode-Feedback#13861]
#### Your LeetCode username
Zayd

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

None of the above. This is in the editor.

#### Description of the bug

I am using the leetcode's browser based Python3 editor. My editor is configured for vim mode.

I enter the following line in the code:

```
v1 = 0x5555555
```

I then exit `vim`'s insert mode and put my cursor on the line of code above.  I press colon ( `:` ) to enter command mode.  I then enter the `vim` command:

```
.s/5/A/g
```

This should replace every `5` to an `A`. In other words the new line should be

```
v1 = 0xAAAAAAAA
```

Instead I get, 

```
v1 = 0xA5A5A5A5
```

#### Code you used for Submit/Run operation

N/A

#### Language used for code

Python3

#### Expected behavior

Instead of the expected (which is confirmed in `neovim`), 

```
v1 = 0xAAAAAAAA
```

I get, 

```
v1 = 0xA5A5A5A5
```

If I run the command a second time, I get the expected string.

#### Screenshots

N/A

#### Additional context

I have run into some other bugs with leetcode's `vim` mode. If documenting them is useful, I can provide more issues.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by ZaydH** [comment]
Hi, could the Leetcode points be credited to my account? Thanks
