### ISSUE TITLE
Missing Test Case - 88. Merge Sorted Array

### ISSUE THREAD

**Issue by Abhay5513** [LeetCode-Feedback/LeetCode-Feedback#13870]
Can someone find problem with my code as gives perfect result when called in VS code but does not get accepted here.

      var merge = function (nums1, m, nums2, n) {

            return nums1.concat(nums2).sort().filter((arr => arr > 0))
        };

console.log(merge([1, 2, 3, 0, 0, 0], 3, [2, 5, 6], 3))
console.log(merge([1], 1, [], 0))
console.log(merge([0], 0, [1], 1))

**Comment by rohith033** [comment]
as question says you should not return anything . Currently, the modified array is not assigned back to nums1, which means the original nums1 array passed as a parameter remains unchanged.

```
var merge = function(nums1, m, nums2, n) {
  nums1.splice(m); // Remove elements after the first m elements
  nums1.push(...nums2); // Append elements from nums2 to nums1
  nums1.sort((a, b) => a - b); // Sort the merged array in ascending order
  nums1 = nums1.filter(num => num > 0); // Filter out positive numbers
  return nums1; // Return the modified nums1 array
};
```

this should work

**Comment by Abhay5513** [comment]
@rohith033 Thanks man, really appreciate your help here.
