### ISSUE TITLE
Missing Test Case - 547. Number of Provinces

### ISSUE THREAD

**Issue by nskybytskyi** [LeetCode-Feedback/LeetCode-Feedback#13873]
#### Your LeetCode username

[nskybytskyi](https://leetcode.com/nskybytskyi/)

#### Category of the bug

- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

In problem [547. Number of Provinces](https://leetcode.com/problems/number-of-provinces/) the following solution gets AC but should get WA on the suggested test case.

#### Code you used for Submit/Run operation

[Submission link](https://leetcode.com/problems/number-of-provinces/submissions/963465346/). This solution computes the transitive closure of a graph using binary (adjacency) matrix exponentiation. However, the exponent used is too small for a line graph.  

```cpp
class Matrix {
 public:
  explicit Matrix(int rows, int columns) : data_(rows, vector<int>(columns)) { }
  explicit Matrix(vector<vector<int>>&& data) : data_(data) { }
  int& operator()(int row, int column) { return data_[row][column]; }
  const int& operator()(int row, int column) const { return data_[row][column]; }

  Matrix operator*(const Matrix& other) const {
    const int rows = data_.size();
    const int middle = data_[0].size();
    const int columns = other.data_[0].size();
    Matrix product(rows, columns);
    for (int row = 0; row < rows; ++row) {
      for (int column = 0; column < columns; ++column) {
        for (int inner = 0; inner < middle; ++inner) {
          product(row, column) |= operator()(row, inner) & other(inner, column);
        }
      }
    }
    return product;
  }

 private:
  vector<vector<int>> data_;
};

class Solution {
 public:
  int findCircleNum(vector<vector<int>>& isConnected) {
    const int size = isConnected.size();
    Matrix matrix(std::move(isConnected));
    for (int _ = 0; _ < 6; ++_) {  // should be 8, gets AC for 4..7
      matrix = matrix * matrix;
    }

    int components{0};
    vector<bool> used(size);
    for (int row = 0; row < size; ++row) {
      if (!used[row]) {
        ++components;
        for (int column = 0; column < size; ++column) {
          if (matrix(row, column)) {
            used[column] = true;
          }
        }
      }
    }
    return components;
  }
};
```
#### Language used for code

C++

#### Expected behavior

The above solution gets WA on the following test case: [input.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/11644846/input.txt) (attached as a file because it is somewhat large).

#### Additional context

The following python3 code generates this input:

```python
n = 200
m = [[int(abs(i - j) <= 1) for j in range(n)] for i in range(n)]
with open('input.txt', 'w') as file:
    file.write(str(m).replace(' ', '') + '\n')
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
