### ISSUE TITLE
Missing Test Case - 132. Palindrome Partitioning II

### ISSUE THREAD

**Issue by kasasunil** [LeetCode-Feedback/LeetCode-Feedback#13877]
#### Your LeetCode username
https://leetcode.com/kasasunil/

#### Category of the bug
- [x] Solution

#### Description of the bug

//code1
class Solution {
    public int minCut(String s) {
        int n = s.length();
        int [][]dp = new int[n][n];
        for(int i=0;i<n;i++){
            Arrays.fill(dp[i],-1);
        }
        return dfs(s.toCharArray(),n,0,-1,dp);
    }
    public int dfs(char s[],int n,int i,int prev,int dp[][]){
        if(i==n){
            if(isPalin(s,n,i-1,prev)){
                return 0;
            }
            return (int)1e9;
        }
        if(prev!=-1 && dp[i][prev]!=-1){
            return dp[i][prev];
        }
        int pick = (int)1e9;
        if(isPalin(s,n,i,prev)){
            pick = 1+dfs(s,n,i+1,i,dp);
        }
        int notPick = dfs(s,n,i+1,prev,dp);
        if(prev == -1){
            return dp[i][0] = Math.min(pick,notPick);
        }
        return dp[i][prev] = Math.min(pick,notPick);
    }
    public boolean isPalin(char s[],int n,int i,int j){
        j++;
        while(j<=i){
            if(s[j] != s[i]){
                return false;
            }
            j++;
            i--;
        }
        return true;
    }
}

//code 2
class Solution {
    public int minCut(String s) {
        int n = s.length();
        int [][]dp = new int[n][n];
        for(int i=0;i<n;i++){
            Arrays.fill(dp[i],-1);
        }
        return dfs(s,n,0,-1,dp);
    }
    public int dfs(String s,int n,int i,int prev,int dp[][]){
        if(i==n){
            if(isPalin(s,n,i-1,prev)){
                return 0;
            }
            return (int)1e9;
        }
        if(prev!=-1 && dp[i][prev]!=-1){
            return dp[i][prev];
        }
        int pick = (int)1e9;
        if(isPalin(s,n,i,prev)){
            pick = 1+dfs(s,n,i+1,i,dp);
        }
        int notPick = dfs(s,n,i+1,prev,dp);
        if(prev == -1){
            return dp[i][0] = Math.min(pick,notPick);
        }
        return dp[i][prev] = Math.min(pick,notPick);
    }
    public boolean isPalin(String s,int n,int i,int j){
        j++;
        while(j<=i){
            if(s.charAt(j) != s.charAt(i)){
                return false;
            }
            j++;
            i--;
        }
        return true;
    }
}

Code1 is passing the below testcase but code2 is giving TLE.
The test case lenth is 2000.
Test case is:
-----------
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab"

#### Code you used for Submit/Run operation
//  Palindrome Partitioning II --- question number 132
class Solution {
    public int minCut(String s) {
        int n = s.length();
        int [][]dp = new int[n][n];
        for(int i=0;i<n;i++){
            Arrays.fill(dp[i],-1);
        }
        return dfs(s,n,0,-1,dp);
    }
    public int dfs(String s,int n,int i,int prev,int dp[][]){
        if(i==n){
            if(isPalin(s,n,i-1,prev)){
                return 0;
            }
            return (int)1e9;
        }
        if(prev!=-1 && dp[i][prev]!=-1){
            return dp[i][prev];
        }
        int pick = (int)1e9;
        if(isPalin(s,n,i,prev)){
            pick = 1+dfs(s,n,i+1,i,dp);
        }
        int notPick = dfs(s,n,i+1,prev,dp);
        if(prev == -1){
            return dp[i][0] = Math.min(pick,notPick);
        }
        return dp[i][prev] = Math.min(pick,notPick);
    }
    public boolean isPalin(String s,int n,int i,int j){
        j++;
        while(j<=i){
            if(s.charAt(j) != s.charAt(i)){
                return false;
            }
            j++;
            i--;
        }
        return true;
    }
}

**Comment by kasasunil** [comment]
Length of 2000 test case should not pass since it is O(N^3) but it is passing for code1 mentioned above.

**Comment by LC-Pam** [comment]
Duplicate issue
