### ISSUE TITLE
Mistake in 1655. Distribute Repeating Integers

### ISSUE THREAD

**Issue by cgsgak1** [LeetCode-Feedback/LeetCode-Feedback#1388]
#### Your LeetCode username
cgsgak1

#### Description of the bug
The mistake seem to be appeared in "Example 1"'s explonation:
Explanation: The 0th customer cannot be given two **different** integers.

#### Expected behavior
Explanation: The 0th customer cannot be given two **equal** integers.

#### Screenshots
![image](https://user-images.githubusercontent.com/34144576/99180499-c236fc00-2737-11eb-894c-c09c58dd91a3.png)

**Comment by lc-kay** [comment]
Hi @cgsgak1 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@cgsgak1 The statement is correct. Please take this as an example. User: Can I give the 0th customer two different integers? LC: The 0th customer cannot be given two different integers. Thank you for your time!
