### ISSUE TITLE
Missing Test Case - 1232. Check If It Is a Straight Line

### ISSUE THREAD

**Issue by Rushijaviya** [LeetCode-Feedback/LeetCode-Feedback#13899]
#### Your LeetCode username
rushi_javiya

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Found the missing test case. Attached are some screenshots for reference. The first screenshot shows when I run code for a missing test case, it gives "Wrong Answer" but when I submit the same code, it's "Accepted".

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/59735978/e13d5f3d-4537-412f-bc1e-3ecc9d82971c)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/59735978/bec7a89a-bd0a-4804-b652-52e95f1d1670)

Test case: [[0,1],[0,2],[2,0]]

#### Code you used for Submit/Run operation
```
class Solution:
    def checkStraightLine(self, coordinates: List[List[int]]) -> bool:
        slop=(coordinates[1][1]-coordinates[0][1])/(coordinates[1][0]-coordinates[0][0]) if coordinates[1][0]!=coordinates[0][0] else -1
        for i in range(2,len(coordinates)):
            temp=(coordinates[i][1]-coordinates[i-1][1])/(coordinates[i][0]-coordinates[i-1][0]) if coordinates[i][0]!=coordinates[i-1][0] else -1
            if temp!=slop:
                return False
        return True
```

#### Language used for code
Python3

#### Expected behavior
The submitted code should give the wrong answer.

#### Additional context
Code submission Link: https://leetcode.com/submissions/detail/964109478/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
