### ISSUE TITLE
Leetcode has become extremely slow for the past couple of days

### ISSUE THREAD

**Issue by snehasishroy** [LeetCode-Feedback/LeetCode-Feedback#1389]
#### Your LeetCode username
chrisgriffin

#### Description of the bug
Leetcode has become extremely slow for the past couple of days, I am a premium user, still everything has become slow, running code, viewing problems, upvoting solutions, viewing solution. It is now very frustrating to solve problems.

#### Code you used for Submit/Run operation
I have added the har file in which I am trying to run my code for one of the random problems. You can see in the network request that it took ~90 seconds for the response to come back. I am from Bangalore, India, if that helps.
[leetcode.com.har.zip](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/5542981/leetcode.com.har.zip)

**Comment by lc-pam** [comment]
Thank you for reaching out to us and raising the issue to our attention. Out engineering team will use the HAR file you provided to investigate the issue. However, kindly remind that this is a technical issue and we opened the GitHub channel only for content issues. I'll close this ticket and please submit a ticket through our [help desk](https://support.leetcode.com/hc/en-us/requests/new) if you'd like to follow up on the issue.

**Comment by lc-kay** [comment]
@snehasishroy To follow up on this issue, are you still experiencing this issue?

**Comment by snehasishroy** [comment]
Thank you for following up on this @lc-kay . I have been regularly using leetcode since the day I raised this issue. Seems like the issue got resolved after a couple of days. 

Thank you for fixing this issue.
