### ISSUE TITLE
Problem 1619 Wrong result for testcase

### ISSUE THREAD

**Issue by PranavTyagi-3** [LeetCode-Feedback/LeetCode-Feedback#13891]
#### Your LeetCode username

Pranav_Tyagi

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Test case 3 should pass but displaying wrong answer

#### Code you used for Submit/Run operation

```
class Solution(object):
    def trimMean(self, arr):
        """
        :type arr: List[int]
        :rtype: float
        """
        arr.sort()
        remove_num = len(arr)*5//100
        arr = arr[remove_num: -remove_num]

        print(float(sum(arr)/len(arr)))
        return float(sum(arr)/len(arr))
```

#### Language used for code

Python

#### Expected behavior

Test case 3 should have passed as it did on my local machine but the result I was getting was wrong

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by PranavTyagi-3** [comment]
[6,0,7,0,7,5,7,8,3,4,0,7,8,1,6,8,1,1,2,4,8,1,9,5,4,3,8,5,10,8,6,6,1,0,6,10,8,2,3,4]

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

The test case already exists. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
