### ISSUE TITLE
Incorrect Test Case - 626 Exchange Seats (SQL)

### ISSUE THREAD

**Issue by lkkcpaul** [LeetCode-Feedback/LeetCode-Feedback#13894]
#### Your LeetCode username
 lkkcpaul

#### Category of the bug
- [ ] Solution

#### Description of the bug

There is something wrong with the compiler. 
In the problem description, the expected output of example 1 is given by 

| id | student |
| -- | ------- |
| 1  | Doris   |
| 2  | Abbot   |
| 3  | Green   |
| 4  | Emerson |
| 5  | Jeames  |

whereas when running the code from the solution, the console says the expected solution is

| id | student |
| -- | ------- |
| 1  | Abbot   |
| 2  | Doris   |
| 3  | Emerson |
| 4  | Green   |
| 5  | Jeames  |

which is clearly different (and wrong) from what's given in the description. 
Even the official solution yields wrong answers, so I think there's something wrong with the compiler. 

#### Code you used for Submit/Run operation

```
SELECT
    s1.id, COALESCE(s2.student, s1.student) AS student
FROM
    seat s1
        LEFT JOIN
    seat s2 ON ((s1.id + 1) ^ 1) - 1 = s2.id
ORDER BY s1.id;
```

#### Language used for code
 SQL

#### Expected behavior

The expected behavior is what the problem description says, which is explained above.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
