### ISSUE TITLE
26. Remove Duplicates from Sorted Array Easy  - wrong tests

### ISSUE THREAD

**Issue by LeandroOliveiraDeQueiroz** [LeetCode-Feedback/LeetCode-Feedback#13896]
#### Your LeetCode username
Leandro Oliveira de Queiroz

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The test cases are wrong because the expected array, but the question must to return the number o unique numbers and the array will be tasted by reference. [See Image](#nome-da-ancora)

#### Code you used for Submit/Run operation

``` 
function removeDuplicates(nums: number[]): number {

  let k = 0;
  let prevNumber = nums[0];
  let i  = 1;

  while(i < nums.length){
    if(nums[i] === prevNumber){
        nums.splice(i, 1);
    } else {
      prevNumber = nums[i]
      i++;
    }
  }

  console.log(nums)

  return k;
};
```
```
Expected:
   [1,2]
```

#### Language used for code
TypeScript

#### Expected behavior
The output should expected a number

#### Screenshots
<a name="secao"></a>
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/36925470/f15c8e21-0b3e-437b-b6f0-a51164dd72f6)

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
