### ISSUE TITLE
Missing Test Case - 2614. Prime In Diagonal

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#13897]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets WA on the following testcase:
[[341]]

#### Code you used for Submit/Run operation

```
class Solution:
    def diagonalPrime(self, nums: List[List[int]]) -> int:

        def isprime(num):
            return num==2 or pow(2,num-1,num)==1
        '''def isp(n):
            for i in range(2,n):
                if n%i==0: return 0
            return 1
        for i in range(2,100000):
            if isp(i)!=isprime(i):
                print(i)
                return -1'''

        ans = 0
        n = len(nums)
        for i in range(n):
            if isprime(nums[i][n-i-1]):
                ans = max(ans,nums[i][n-i-1])
            if isprime(nums[i][i]):
                ans = max(ans,nums[i][i])
        return ans 
```

#### Language used for code

Python3

#### Expected behavior

Output: 341
Expected: 0

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
