### ISSUE TITLE
519. Random Flip Matrix—Missing Editorial

### ISSUE THREAD

**Issue by gordonm867** [LeetCode-Feedback/LeetCode-Feedback#13895]
#### Your LeetCode username
fjordme3

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
On problem 519, "Random Flip Matrix" (https://leetcode.com/problems/random-flip-matrix/description/), the solution editorial is inaccessible. When I try to access the editorial (on multiple browsers both signed in and signed out), it does not load and eventually a message appears that says "this topic does not exist".

#### Expected behavior
I expected that a solution would appear when I clicked the "editorial" button; instead, it persistently fails to load the editorial as it seemingly does not exist for this problem.

#### Screenshots
<img width="1240" alt="Screenshot 2023-06-04 at 5 54 05 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/9099488/b715b5ff-b515-4043-93bc-5bf9589a34ab">

#### Additional context
As an aside, this problem is tagged "reservoir sampling" despite the reservoir sampling approach resulting in a TLE. The seemingly only correct approach is based on the Fisher-Yates shuffle. I think this tag could be misleading, although I am not sure if that is intentional because reservoir sampling _could_ (albeit inefficiently) solve this problem or if it is a mistake.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The page loading correctly.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
![Screen Shot 2023-06-06 at 3 12 56 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/cb17831b-1f40-4b2f-9f70-0d5cdbea3c85)
![Screen Shot 2023-06-06 at 3 13 03 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/61083663-add6-4e7b-9fed-de080384c396)
