### ISSUE TITLE
Broken test case for 626. Exchange Seats

### ISSUE THREAD

**Issue by rupdeep2275** [LeetCode-Feedback/LeetCode-Feedback#13901]
#### Your LeetCode username
Rupdeep

#### Category of the bug
626. Exchange Seats

SQL

#### Description of the bug
The first test case expected output is incorrect.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots
Attached ss.
![Screenshot 2023-06-05 120305](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/113031805/225f284b-981b-479f-9035-ce47491a9dc9)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
