### ISSUE TITLE
Broken text formatting - 2619. Array Prototype Last

### ISSUE THREAD

**Issue by nurSaadat** [LeetCode-Feedback/LeetCode-Feedback#13908]
#### Your LeetCode username
sweetsalad

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Broken formatting: missing $ (dollar sign) broke code snippet formatting. 

#### Expected behavior

Code snippet should look like 
```
function greet() {
  return `Hello, I am ${this.name}`;
}

let person1 = { name: 'Alice' };
let person2 = { name: 'Bob' };

// Create a bound function with "this" set to person1
let greetPerson1 = greet.bind(person1);

console.log(greetPerson1()); // Hello, I am Alice

// Attempt to change the context by using the call method; however, it still uses person1 as 'this' context
console.log(greetPerson1.call(person2)); // Hello, I am Alice

//  In contrast, a normal function call allows the 'this' context to be set by the call method
console.log(greet.call(person2)); // Hello, I am Bob
```
followed by more text.

#### Screenshots

![Screenshot here](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/39532643/3da927a4-0e07-4209-a6f2-3a77ee7b0d87)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
