### ISSUE TITLE
Missing Test Case - 214 Shortest Palindrome

### ISSUE THREAD

**Issue by kumar9602** [LeetCode-Feedback/LeetCode-Feedback#13902]
LeetCode username :  [Kumar_11](https://leetcode.com/Kumar_11/)

Category of the bug : Missiing Test case

Descritption of the bug : Problem is missing test cases of even length string with same characters

Example Test Cases : "aaaa" , "aaaaaa" , "bbbbbb" .. etc

Code used for submission : 
`class Solution {
public:
    long long modInverse(long long A, long long M)
    {
        long long m0 = M;
        long long y = 0, x = 1;

        if (M == 1)
            return 0;

        while (A > 1) {
            // q is quotient
            long long q = A / M;
            long long t = M;
            M = A % M, A = t;
            t = y;
            y = x - q * y;
            x = t;
        }
        if (x < 0)
            x += m0;

        return x;
    }
    string shortestPalindrome(string s) {
        int n = s.length();
        if(n == 1)
            return s ;
        long long base = 27 , mod = 1000000009 ;
        vector<long long>first(n) , second(n);
        long long m = 1 , hash = 0 ;
        vector<long long>third(n);
        for(int i = 0 ; i < n ; i++){
            third[i] = m ;
            hash = (hash + ((s[i] - 'a' + 1) * m) % mod) % mod;
            m = m * base % mod ;
            first[i] = hash ;
        }
        m = 1 ;
        hash = 0 ;
        for(int i = n - 1 ; i >= 0 ; i--){
            hash = (hash + ((s[i] - 'a' + 1)* m) % mod) % mod ;
            m = m * base % mod ;
            second[i] = hash ;
        }
        
        int res = 0 ;
        for(int i = 0 ; i < (n + 1)/2 ; i++){
            long long a = first[i];
            long long b = second[i];
            long long p ;
            if(2 * i + 1 < n)
                b -= second[2 * i + 1];
            b = (b % mod + mod) % mod ;
            p = third[n - 2 * i - 1];
            p = modInverse(p , mod);
            b = (b % mod) * (p % mod) % mod ;
            if(a == b)
                res = max(res , 2 * i + 1);
            if(2  * ( i + 1) < n){
                a = first[i] , b = second[i+1];
                b -= second[2 * (i + 1) ];
                b = (b % mod + mod) % mod ;
                p = third[n - 2 * i - 2];
                p = modInverse(p , mod);
                b = b * p % mod ;
                if(a == b)
                    res = max(res , 2 * i + 2); 
            }   
        }
        int j = n - 1 ;
        string ne ;
        for(int i = n ; i > res ; i--){
            ne += s[j];
            j--;
        }
        ne += s ;
        // cout<<res<<endl;
        return ne ;
        
    }
};`

Language used for the Code : C++

Expected Behaviour : Wrong Answer

Verdict : Accepted

Screenshots : 
<img width="959" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/90889494/7db40ba1-f063-4a05-a9dd-8a0755c7edc1">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by kumar9602** [comment]
> Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
> 
> The code submission link.
> 
> We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

submission link [https://leetcode.com/problems/shortest-palindrome/submissions/964211835/](submission)
Glad to hear back from you :)

**Comment by kumar9602** [comment]
I think it's useless to contribute, admins never get back

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
