### ISSUE TITLE
Ambiguous problem statement #320

### ISSUE THREAD

**Issue by snehasishroy** [LeetCode-Feedback/LeetCode-Feedback#1390]
#### Your LeetCode username
chrisgriffin

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Problem statement https://leetcode.com/problems/generalized-abbreviation/ does not tell anything about the meaning of generalized abbreviation.

I have to understand it by looking at the sample test cases.

It would be great if some description was added to the problem statement to tell what needs to be abbreviated and how.

**Comment by lc-kay** [comment]
Hi @snehasishroy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @snehasishroy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!

**Comment by snehasishroy** [comment]
Hi @lc-kay 

I should be awarded with 100 leetcoins as it was a valid contribution and it resolves frustration for multiple users

![image](https://user-images.githubusercontent.com/4747384/101408094-ebdfdf00-3901-11eb-89b3-0c352c45a8ec.png)


https://leetcode.com/problems/generalized-abbreviation/discuss/77256/Could-anyone-help-to-understand-this-question

**Comment by lc-kay** [comment]
Hi @snehasishroy 
Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
