### ISSUE TITLE
Broken text formatting - 2618. Check if Object Instance of Class

### ISSUE THREAD

**Issue by nurSaadat** [LeetCode-Feedback/LeetCode-Feedback#13909]
#### Your LeetCode username
sweetsalad

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Unnecessary whitespace after apostrophe. 

#### Expected behavior

Text should follow correct formatting.
`And that's why instanceof behaves in that way, which is actually correct but in this particular problem we consider a value to be an instance of a given class when (as the prompt reads) the value ‘has access to that class's methods’ and it’s meant by the author that indirect access to class’s methods through the boxing process described above to be also considered. Example 4 clarifies that and that’s why using instanceof won’t work as a solution to this problem. In contrast, if you create a Number object using the Number constructor, it will be an instance of Number:`

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/39532643/cc54f7e4-d1bd-4d28-bc37-711c96b7001b)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
