### ISSUE TITLE
406：题目描述不清楚

### ISSUE THREAD

**Issue by pan463859** [LeetCode-Feedback/LeetCode-Feedback#1391]
假设有打乱顺序的一群人站成一个队列。 每个人由一个整数对(h, k)表示，其中h是这个人的身高，k是排在这个人前面且身高大于或等于h的人数。 编写一个算法来重建这个队列。
输入:
[[7,0], [4,4], [7,1], [5,0], [6,1], [5,2]]

输出:
[[5,0], [7,0], [5,2], [6,1], [4,4], [7,1]]

从题目和例子中看不出来到底是要求怎么排序
![image](https://user-images.githubusercontent.com/32640880/99205652-215a4680-27f4-11eb-9af7-d0c1b1ca5aa9.png)

**Comment by feiceh** [comment]
题面已更新。
