### ISSUE TITLE
626. 换座位答案正确不通过

### ISSUE THREAD

**Issue by LimingSun** [LeetCode-Feedback/LeetCode-Feedback#13912]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
浪漫先生

**Bug 类型**
题解

**描述**
正确答案提交测试用例不通过。

**你使用的语言**
MySQL

**你提交或者运行的代码**
```sql
select rank() over(order by (id-1)^1) as id,student from seat
```

**期望行为**
描述你期望的结果

**屏幕截图**
<img width="1708" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/32392895/e0dd9821-ca4e-4109-a080-56c27a2db9a5">

**额外的上下文**

**Comment by feiceh** [comment]
你好，如果出现测试用例结果和提交结果不一致的情况，可以再仔细检查并调试一下代码，或点击这里：「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」 获得更多帮助。

同时也可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
