### ISSUE TITLE
Missing Test Case - 1232. Check If It Is a Straight Line

### ISSUE THREAD

**Issue by dvishal485** [LeetCode-Feedback/LeetCode-Feedback#13919]
#### Your LeetCode username

dvishal485

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

For the problem, [Check if it is a straight line](https://leetcode.com/problems/check-if-it-is-a-straight-line/), the solution is accepted even when it fails for the following testcase.

coordinates = `[[98,0],[99,5000],[100,9999]]`

Expected output is `false` while this code output is `true`, yet it is accepted as a correct solution.

#### Code you used for Submit/Run operation

```rust
impl Solution {
    pub fn check_straight_line(coordinates: Vec<Vec<i32>>) -> bool {
        let slope = |(x1, y1): (i32, i32), (x2, y2): (i32, i32)| ((y2 - y1) << 10).checked_div(x2 - x1);
        let (first_point, second_point) = (&coordinates[1], &coordinates[0]);
        let first_point = (first_point[1], first_point[0]);
        let second_point = (second_point[1], second_point[0]);
        let expected_slope = slope(first_point, second_point);

        coordinates[2..].iter().map(|point| (point[1], point[0])).all(|point| slope(first_point, point) == expected_slope)
    }
}
```

#### Language used for code

Rust

#### Expected behavior

The solution should be marked as `Wrong Answer`.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/26341736/28da985c-1a36-4fab-8c1f-6a340792a0b1)

#### Additional context

As mentioned above, the testcase which fails is `[[98,0],[99,5000],[100,9999]]` and is well within the constraints.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
