### ISSUE TITLE
Test case issue in 202. Happy Number

### ISSUE THREAD

**Issue by fulwaa** [LeetCode-Feedback/LeetCode-Feedback#13915]
#### Your LeetCode username
FULWA ASHEEB

#### Category of the bug
- [ ] Question
- [*] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
There is a issue with the test case.

#### Code you used for Submit/Run operation

class Solution(object):
    def isHappy(self, n):
        val=0
        ne=0
        while num>0:
            if num==1:
                ne=True
                break
            elif num>1 and num<10:
                ne=False
                break
            else:
                sum=0
                while num>0:
                    d=num%10
                    num=num//10
                    sum=sum+d**2
                num=sum
        return ne

#### Language used for code
python

#### Expected behavior
There is a issue with test case. In the test case the input is 7. The correct answer is false but it showing True.

**Comment by stormsunshine** [comment]
7 -> 49 -> 97 -> 130 -> 10 -> 1, so the correct answer is true. Is there any problem?

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
