### ISSUE TITLE
 Test Case Issue - 1456. Maximum Number of Vowels in a Substring of Given Length

### ISSUE THREAD

**Issue by Hamza-Dabeer-Khan** [LeetCode-Feedback/LeetCode-Feedback#13923]
#### Your LeetCode username
HamzaDabeerKhan

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 
- [x] Wrong Test Case

#### Description of the bug
In the given test case with $s = "weallloveyou" and $k = 7, the code expecting output **4**  but it should be **3** as the maximum number of vowels in any substring of length 7.
1. $i = 0: $s[$i] is 'w'
2. $i = 1: $s[$i] is 'e'
3. $i = 2: $s[$i] is 'a'
4. $i = 3: $s[$i] is 'l'
5. $i = 4: $s[$i] is 'l'
6. $i = 5: $s[$i] is 'l'
7. $i = 6: $s[$i] is 'o'
where vowels  = 3
The substring **"wealllo**" contains 3 vowels: 'e', 'a', and 'o'. The remaining substring **"veyou"** also contains 3 vowels: 'e', 'o', and 'u'. However, since we are interested in the maximum number of vowels in a substring of length 7, the correct answer should be 3.
Therefore, the code is expected to output 3 for the given test case, not 4

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {

    /**
     * @param String $s
     * @param Integer $k
     * @return Integer
     */
    function maxVowels($s, $k) {
        $vowelArray = array('a','e','i','o','u');
        $charArray = str_split($s, $k);
        $count = 0;
        $max = 0;
        foreach($charArray as $vow) {
            $char = str_split($vow);
            foreach($char as $ch)
            {
                if(in_array($ch, $vowelArray))
                {   
                    $count += 1;
                
                }

            }
             if($count > $max) {
                $max = $count;
            }
            
            $count = 0;
        }
        return $max;
    }
    
}
```

#### Language used for code
PHP

#### Expected behavior
In the given test case, with the string **"weallloveyou"** and the substring length of 7, the code should output 3 as the maximum number of vowels in any substring of that length. However, my code passed the all test cases except this one. 
I don't know how others submitted the solution but my basic concern is splitting the string **"weallloveyou"**  into 7 length must be 
**"wealllo"** either you start from **0 to 6 or 1 to 7**. 
Therefore, based on the provided test case, the output must be 3 as the maximum number of vowels in a substring of length **7**. However, it's expecting **4** which is confusing for me. 

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/45049612/93438779-0dce-409c-9d6c-b514d4e9eeb3)

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
