### ISSUE TITLE
80. Remove Duplicates from Sorted Array II | Accepting on returning incorrect k

### ISSUE THREAD

**Issue by NKwatra** [LeetCode-Feedback/LeetCode-Feedback#13927]
#### Your LeetCode username

NKwatra

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Question states that if there are k elements in array after removing duplicates, we need to return k. But if there is only 1 element in array and we return 2 from function, then also it is accepting.
For eg, consider the testcase 
```
nums = [ 1 ]
```
It is expected that function should return 1, however even on returning 2 there is no error.

#### Code you used for Submit/Run operation

```java
class Solution {
    public int removeDuplicates(int[] nums) {
        int last = 1;
        if(nums.length == 0){
            return 0;
        }
        for(int i = 2; i < nums.length; i++){
            if(nums[i] != nums[i-1]){
                nums[++last] = nums[i];
            }else if(nums[i] != nums[last - 1]){
                nums[++last] = nums[i];
            }
        }
        return last + 1;
    }
}
```

#### Language used for code

Java

#### Expected behavior

It should show a runtime error if the value returned by function is greater than the length of nums.

#### Screenshots

N/A

#### Additional context

N/A

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

It’s mentioned that it’s no problem if you return an array with a size of more than k.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
