### ISSUE TITLE
Missing Test Case - 1502. Can Make Arithmetic Progression From Sequence

### ISSUE THREAD

**Issue by ceciliachan1979** [LeetCode-Feedback/LeetCode-Feedback#13925]
#### Your LeetCode username

[cecilia5](https://leetcode.com/cecilia5/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The given test cases are insufficient to catch a bug.

#### Code you used for Submit/Run operation

```swift
class Solution {
    func canMakeArithmeticProgression(_ arr: [Int]) -> Bool {
         // pass 1: find min-max
        let (min, max) = arr.reduce((min: Int.max, max: Int.min)) { data, i in 
                            (Swift.min(data.min,i), Swift.max(data.max, i))
                         } 
        // short-circuit: if min=max, return true; if step size non-integer, return false
        guard max > min, (max - min) % (arr.count - 1) == 0 else { return max == min }
        
        let step = (max - min) / (arr.count - 1)
        var checksum = 0
        
        // pass 2: verify array elements
        for (i, n) in arr.enumerated() { 
            // element is integral `step`s away from `min`
            guard (n-min) % step == 0 else { return false }
            // detect duplicates via XOR (`arr` is kept read-only)
            checksum ^= (n-min) ^ (i*step) 
        }
        
        return checksum == 0
    }
}
```

#### Language used for code
Swift

#### Expected behavior
The code is wrongly returning `true` on the array `[0, 0, 3, 3]` and should be refused by the judge, but instead, it is accepted.

#### Screenshots
N/A

#### Additional context
The code is adopted from a comment from `UpvoteThisPls` on the editoral page.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
