### ISSUE TITLE
2719. Count of Integers

### ISSUE THREAD

**Issue by claytonjwong** [LeetCode-Feedback/LeetCode-Feedback#13921]
#### Your LeetCode username
`claytonjwong`

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

There's a typo in both example 1 and 2, ie. we can fix this by changing `num` 👉 `sum` for min/max input args

**Example 1:**
❌ `Input: num1 = "1", num2 = "12", min_num = 1, max_num = 8`
✅ `Input: num1 = "1", num2 = "12", min_sum = 1, max_sum = 8`

**Example 2:**
❌ `Input: num1 = "1", num2 = "5", min_num = 1, max_num = 5`
✅ `Input: num1 = "1", num2 = "5", min_sum = 1, max_sum = 5`

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
