### ISSUE TITLE
Missing Test Case - 31. Next Permutation

### ISSUE THREAD

**Issue by highmonk** [LeetCode-Feedback/LeetCode-Feedback#13924]
#### Your LeetCode username -
`highmonk_`

#### Category of the bug -
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug -

A test case is missing. On submission of a wrong code the answer gets accepted. 

#### Code you used for Submit/Run operation -

```
// Next Permutation
class Solution:
    def nextPermutation(self, nums: List[int]) -> None:
        """
        Do not return anything, modify nums in-place instead.
        """
        idx1 = -1
        for i in range(len(nums)-1, -1, -1):
            # print(i)
            if i == len(nums) - 1:
                continue
            elif nums[i] >= nums[i+1]:
                continue
            elif nums[i] < nums[i+1]:
                idx1 = i
                break
        idx2 = idx1
        if idx1 != -1:
            for i in range(len(nums)-1, idx1, -1):
                if nums[i] > nums[idx1]:
                    idx2 = i
                    break
            nums[idx1], nums[idx2] = nums[idx2], nums[idx1]

        if len(nums) > 2:
            i = idx1+1 if idx1+1 < len(nums) else idx1
            j = len(nums) - 1
            while i < j:
                nums[i], nums[j] = nums[j], nums[i]
                i += 1
                j -= 1
```

#### Language used for code -
`Python3`

#### Expected behavior -

For test input `[2, 1]` the expected output is `[1, 2]` which clearly fails but the answer still gets accepted.

#### Screenshots -

![issue](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/29157989/4956832c-fb98-4d10-a6f3-47a573405ed4)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
