### ISSUE TITLE
Missing Test Case - 2617. Minimum Number of Visited Cells in a Grid

### ISSUE THREAD

**Issue by Tudor67** [LeetCode-Feedback/LeetCode-Feedback#13920]
#### Your LeetCode username

[Tudor67](https://leetcode.com/Tudor67/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My (inefficient) solution passed all the test cases and was accepted,
but I found a test case that exceeds the time limit (TLE).

__*The TLE test case:*__
__*Input:*__
```
[
[1,0],
[1,49997],
[0,49996],
[0,49995],
[0,49994],
[0,49993],
...
...
[0,4],
[0,3],
[0,2],
[0,1],
[0,1],
[0,0]
]
```

__*Output:*__ `Time Limit Exceeded`

__*Expected:*__ `5`

**_Test File (.txt)_**: [test_case.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/11657091/test_case.txt)
**_Generator File (.cpp -> .txt)_**: [generator.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/11657135/generator.txt)

#### Code you used for Submit/Run operation

[Submission Link](https://leetcode.com/problems/minimum-number-of-visited-cells-in-a-grid/submissions/964629067/)
``` C++
// 2617. Minimum Number of Visited Cells in a Grid
// C++
class Solution {
public:
    int minimumVisitedCells(vector<vector<int>>& grid) {
        const int ROWS = grid.size();
        const int COLS = grid[0].size();
        const int INF = 1e9;

        vector<vector<int>> dist(ROWS, vector<int>(COLS, INF));
        vector<int> availAtRow(ROWS, 0);
        vector<int> availAtCol(COLS, 0);
        queue<pair<int, int>> q;
        q.push({0, 0});
        dist[0][0] = 1;

        while(!q.empty() && dist[ROWS - 1][COLS - 1] == INF){
            int row = q.front().first;
            int col = q.front().second;
            q.pop();
            
            int nextRowMin = max(row, availAtCol[col]) + 1;
            int nextColMin = max(col, availAtRow[row]) + 1;
            
            int nextRowMax = max(min(ROWS - 1, grid[row][col] + row), availAtCol[col]);
            int nextColMax = max(min(COLS - 1, grid[row][col] + col), availAtRow[row]);

            for(int nextRow = nextRowMin; nextRow <= nextRowMax; ++nextRow){
                int nextCol = col;
                if(dist[row][col] + 1 < dist[nextRow][nextCol]){
                    dist[nextRow][nextCol] = dist[row][col] + 1;
                    q.push({nextRow, nextCol});
                }
            }
            
            for(int nextCol = nextColMin; nextCol <= nextColMax; ++nextCol){
                int nextRow = row;
                if(dist[row][col] + 1 < dist[nextRow][nextCol]){
                    dist[nextRow][nextCol] = dist[row][col] + 1;
                    q.push({nextRow, nextCol});
                }
            }
            
            if(col == availAtRow[row]){
                availAtRow[row] = nextColMax;
            }
            if(row == availAtCol[col]){
                availAtCol[col] = nextRowMax;
            }
        }
        
        if(dist[ROWS - 1][COLS - 1] == INF){
            return -1;
        }
        return dist[ROWS - 1][COLS - 1];
    }
};
```

#### Language used for code

C++

#### Expected behavior

Time Limit Exceeded

#### Screenshots

![prob_2617_TLE](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/12481060/b6a94466-9bd8-4459-b256-5c55c05ed272)

#### Additional context

In the worst case scenario, the time complexity of my solution is `O(R * C * max(R, C))`, 
where R is the number of rows of the input grid and 
C is the number of columns of the input grid.

My solution is slow and exceeds the time limit of the problem when R and/or C are large values.
When `R = 5 * (10 ^ 4)` and `C = 2`, 
we will do around `5 * (10 ^ 4) * 2 * max(5 * (10 ^ 4), 2)` = `50 * (10 ^ 8)` =  `5 * (10 ^ 9)` operations.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
