### ISSUE TITLE
Missing Test Case - 1034. Coloring A Border

### ISSUE THREAD

**Issue by waterComplex** [LeetCode-Feedback/LeetCode-Feedback#13932]
#### Your LeetCode username

waterComplex
https://leetcode.com/waterComplex/

#### Category of the bug
[-] Missing Test Cases 

#### Description of the bug

    This [solution](https://leetcode.com/problems/coloring-a-border/submissions/965057068/) got submitted successfully but it should give TLE for these valid test cases:
    1) Testcase of 10 x 10 grid with all 1's, row = 0, col = 0, color = 3: https://justpaste.it/5krng
    2) Testcase of 50 x 50 grid with all 1's, row = 0, col = 0, color = 3: https://justpaste.it/9y9si

#### Code you used for Submit/Run operation

```
class Solution {
public:
    /*
    this solution got submitted successfully but it should give TLE for these testcases:
    1) Testcase of 10 x 10 grid with all 1's, row = 0, col = 0, color = 3: https://justpaste.it/5krng
    2) Testcase of 50 x 50 grid with all 1's, row = 0, col = 0, color = 3: https://justpaste.it/9y9si
    */
    
    bool dfsHelper(vector<vector<int>>&grid, int r, int c,int &componentColor ,int &color){
        
        if(r < 0 || c < 0 || r >= grid.size() || c >= grid[0].size()){
            return true;
        }
        if(grid[r][c] == -1 * componentColor){
            return false;
        }
        if(grid[r][c] != componentColor){
            return true;
        }

        grid[r][c] *= -1;
        bool u = dfsHelper(grid,r-1,c,componentColor,color);
        bool f = dfsHelper(grid,r,c+1,componentColor,color);
        bool d = dfsHelper(grid,r+1,c,componentColor,color);
        bool b = dfsHelper(grid,r,c-1,componentColor,color);
        if(!u && !f && !d && !b){
            grid[r][c] *= -1;
        }
        return false;
    }

    vector<vector<int>> colorBorder(vector<vector<int>>& grid, int row, int col, int color) {
        int componentColor = grid[row][col];
        dfsHelper(grid,row,col,componentColor,color);
        for(int i = 0; i< grid.size(); i++){
            for(int j = 0; j< grid[0].size(); j++){
                if(grid[i][j] < 0){
                    grid[i][j] = color;
                }
            }
        }
        return grid;
    }
    
};
```

#### Language used for code

C++

#### Expected behavior

The above solution should give a time limit exceeded when submitted because it is giving TLE when running on the below valid custom testcases:
1) Testcase of 10 x 10 grid with all 1's, row = 0, col = 0, color = 3: https://justpaste.it/5krng
2) Testcase of 50 x 50 grid with all 1's, row = 0, col = 0, color = 3: https://justpaste.it/9y9si

These testcases are missing:
```
row = 0, col = 0, color = 3,

grid =
[[1,1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1,1]]
```

#### Screenshots

<img width="1440" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/111220824/64816b77-0dc3-46fe-b755-1581aaa03a2f">
<img width="1431" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/111220824/35518917-9d25-4883-a58a-8b8a372969d9">

**Comment by DEVESHKUMAR97** [comment]
Nice Catch: This test case is a miss. I have seen many solutions succeeded but ideally, they should get TLE.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
