### ISSUE TITLE
Missing Test Case - 2719. Count of Integers

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#13937]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets WA on the following testcase:
"5440"
"9999"
4
6

#### Code you used for Submit/Run operation

```
M = 10**9+7
class Solution:
    def count(self, num1: str, num2: str, min_sum: int, max_sum: int) -> int:
        n = len(num2)
        
        @cache
        def dfs(a, b, k):
            if (n-k) * 9 < a: return 0
            if b < 0: return 0
            if k == n-1: return min(b,9)+1-max(a,0)
            if k == n: return 1
            ret = 0
            for d in range(10):
                ret += dfs(a-d, b-d, k+1)
                # print(d, ret)
                
            return ret
        
        # print(dfs(27,28,1))
        
        def f(num:str, mis, mas):
            ret = 0
            usd = 0
            for wei in range(n):
                for d in range(int(num[wei])):
                    ret += dfs(mis-usd-d, mas-usd-d, wei+1)
                    # print(wei,d,ret)
                usd += int(num[wei])
            return ret
        
        if len(num1) < n:
            num1 = '0' * (n-len(num1)) + num1
        ansa = f(str(int(num2)+1), min_sum, max_sum)
        ansb = f(num1, min_sum, max_sum)
        # print(ansa,ansb)
        return ( ansa - ansb ) % M
```

#### Language used for code

Python3

#### Expected behavior

Output: 999999897
Expected: 1

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
