### ISSUE TITLE
2352. 相等行列对 - 用例Bug

### ISSUE THREAD

**Issue by l00jj** [LeetCode-Feedback/LeetCode-Feedback#13931]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
https://leetcode.cn/u/l00/

**Bug 类型**
- [ ] 题目
- [x] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述**
最快的推荐Code利用了存在测试漏洞

**你使用的语言**
Java

**你提交或者运行的代码**
最快的“推荐”代码使用的是每个数*10作为哈希数字进行字典树查找，但是不应该成功。以下用例就是正确答案和“推荐”代码的答案，不一致。
用例：
```
[[3,2,10],[1,7,10],[1,100,7]]
```
<img width="1084" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/25047890/ca9371c8-04f1-44db-8a6d-c0d7c543631a">

**期望行为**
删除推荐Code，并添加用例补丁

**屏幕截图**
<img width="453" alt="WX20230606-152508@2x" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/25047890/87d47ce0-a545-4ea9-8988-78abdbd7a4d9">

**额外的上下文**
无

**Comment by feiceh** [comment]
你好，建议添加 未通过代码，以便相关团队定位排查。
