### ISSUE TITLE
SQL 626. Exchange Seat Question Test Case 3

### ISSUE THREAD

**Issue by datasctraveller** [LeetCode-Feedback/LeetCode-Feedback#13934]
there is a problem with test case third. Test case third result is different than sample result of  main question 
select id,
case 
when id % 2 = 1 and id = (select count(id) from Seat) then student

when id % 2 = 1 and id <> (select count(id) from Seat) then 

(select student from Seat M where M.id = S.id+1)  

when id % 2 = 0 then

(select student from Seat P where P.id = S.id-1) 

 end student

from Seat S

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by datasctraveller** [comment]
I am checking with my solution again. I can pass the third test-case of solution. You're welcome. Nice working day.
