### ISSUE TITLE
448. 找到所有数组中消失的数字

### ISSUE THREAD

**Issue by AliceTony** [LeetCode-Feedback/LeetCode-Feedback#13944]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
Tony

**Bug 类型**
- [ ] [题目](https://leetcode.cn/problems/find-all-numbers-disappeared-in-an-array/)
- [ ] 题解
- [ ] C++
- [ ] 缺少测试用例

**描述**
测试样例以及题解未考虑到极端情况
对于一个全为相同输入的数据未能处理好溢出情况
我的输入情况为1e5个1
**你使用的语言**
C++

**你提交或者运行的代码**
```
class Solution {
public:
    vector<int> findDisappearedNumbers(vector<int>& nums) {
        int n = nums.size();
        for (auto& num : nums) {
            int x = (num - 1) % n;
            nums[x] += n;
        }
        vector<int> ret;
        for (int i = 0; i < n; i++) {
            if (nums[i] <= n) {
                ret.push_back(i + 1);
            }
        }
        return ret;
    }
};

```

**期望行为**
数据溢出并报错

**屏幕截图**
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/56498293/42afe4ad-fc0c-4f49-aff1-f305648da1e6)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/56498293/9c1e8cb7-4d02-4d5e-bc44-1b068dadc555)

**额外的上下文**
使用的是官方题解给的代码,并不能处理极端输入

**Comment by feiceh** [comment]
感谢反馈，当前题目已更新，积分奖励已发放。
