### ISSUE TITLE
【错别字】 1826. 有缺陷的传感器

### ISSUE THREAD

**Issue by zouyu9631** [LeetCode-Feedback/LeetCode-Feedback#13945]
**你的 LeetCode 用户名**
FreeYourMind

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
示例 2 有个错别字
“解释：无法判定*拿*个传感器是有缺陷的。”
拿 -> 哪

**期望行为**
“解释：无法判定哪个传感器是有缺陷的。”

**屏幕截图**
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/6801919/0d81c0b8-f617-44c5-a78f-e24b594a8de7)

**Comment by feiceh** [comment]
感谢反馈，当前题目已更新，奖励已发放。
