### ISSUE TITLE
Missing Test Case - 2619. Array Prototype Last

### ISSUE THREAD

**Issue by Leathether** [LeetCode-Feedback/LeetCode-Feedback#13940]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by Leathether** [comment]
nums isn't defined in the code, so I had to make a variable called nums.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

More details about the issue
The code and language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
