### ISSUE TITLE
测试集错误

### ISSUE THREAD

**Issue by mshtq** [LeetCode-Feedback/LeetCode-Feedback#1395]
** Bug 类型**
- [ ] 题目

**描述**
Leetcode上"685. 冗余连接 II"题目的测试集有问题

**你使用的语言**
JAVA

**你提交或者运行的代码**
```
    //685. 冗余连接 II
    public int[] findRedundantDirectedConnection(int[][] edges) {
        int[] ret = null;
        int[] parent = new int[edges.length + 1];//直接parent
        int[] root=new int[edges.length + 1];//顶级祖先

        for (int[] edge : edges) {
        	if(parent[edge[1]]!=0||!setRoot(root,edge[0],edge[1])){
        		return edge;
        	}
        	parent[edge[1]]=edge[0];
        }
        return ret;
    }
    private boolean setRoot(int[]root,int src,int target){
    	while(root[src]!=0){
    		if(root[src]==target) return false;
    		src=root[src];
    	}
    	root[target]=src;
    	return true;
    }
```

**期望行为**
按照屏幕截图中的测试集的输入。
删除边"[2,1]"或"[3,1]"均能满足"剩下的图是有N个节点的有根树"要求,
而按照"若有多个答案，返回**最后**出现在给定二维数组的答案"的题目要求，理应删除边"[3,1]"。
但是测试集给出的答案是删除边"[2,1]"。
明显，测试集的答案是错误的。
希望官方能够予以修正。

**屏幕截图**

![屏幕截图](https://user-images.githubusercontent.com/24646003/99341497-f4299900-28c4-11eb-9405-0b6d8cbc75f8.png)

**额外的上下文**

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认的～

**Comment by zerotrac** [comment]
你把 [3,1] 删掉剩下就成一个圈了，怎么就有根树了。。。

**Comment by feiceh** [comment]
对于用例 "[[2,1],[3,1],[4,2],[1,4]]" 当删除边 "[3,1]" 不能满足"剩下的图是有N个节点的有根树"要求。

**Comment by mshtq** [comment]
确实删除边 "[3,1]" 不能满足"剩下的图是有N个节点的有根树"要求。当时脑子可能短路了。~
