### ISSUE TITLE
Missing Test Case - 686. Repeated String Match

### ISSUE THREAD

**Issue by flow7f** [LeetCode-Feedback/LeetCode-Feedback#13955]
#### Your LeetCode username
flow7f

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

My solution isn't correct on the next test case but my submission was accepted:
```
a = "abcd"
b = "cabcdab"
```
If I add this test case manually, then leetcode will mark my answer as incorrect (and that's right).

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int repeatedStringMatch(string a, string b) {
        if (a.find(b) != string::npos)
            return 1;
        if ((a+a).find(b) != string::npos)
            return 2;
        auto i = (b+b).find(a);
        if (i == string::npos)
            return - 1;
        int count = i != 0;
        // should be: a.rfind(b.substr(0, i)) != a.size() - i
        if (count == 1 && a.find(b.substr(0, i)) == string::npos)
            return -1;
        b = b.substr(i);
        for (int j = 0; j < b.size(); j += a.size()) {
            if (a.find(b.substr(j, a.size())) != 0)
                return -1;
            ++count;
        }

        return count;
    }
};
```

#### Language used for code

C++

#### Expected behavior

This submission shouldn't be accepted.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
