### ISSUE TITLE
Missing Test Case - 1268. Search Suggestions System

### ISSUE THREAD

**Issue by xswzaq44321** [LeetCode-Feedback/LeetCode-Feedback#13959]
#### Your LeetCode username

[xswzaq44321](https://leetcode.com/xswzaq44321/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```c++
class Solution {
public:
    vector<vector<string>> suggestedProducts(vector<string>& products, string searchWord) {
        sort(products.begin(), products.end());
        auto it = products.begin();
        vector<vector<string>> ans;
        string buffer;
        for(char c : searchWord){
            buffer.push_back(c);
            ans.push_back({});
            it = lower_bound(it, products.end(), buffer);
            for(int i = 0; i < min(3l, distance(it, products.end())); ++i){
                // printf("%s, %s\n", buffer.c_str(), next(it, i)->c_str());
                if(next(it, i)->find(buffer) == string::npos)
                    break;
                ans.back().push_back(*next(it, i));
            }
        }
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

My code above got accepted, but when I use the following custom testcase, it failed
```
["hav", "khav"]
"havana"
```
The bug is with `if(next(it, i)->find(buffer) == string::npos)`, which it should be `if(next(it, i)->find(buffer) != 0)`
The default test case can't detect such bug, hence I hope to add the above test case.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
