### ISSUE TITLE
Missing Test Case - 2681. Power of Heroes

### ISSUE THREAD

**Issue by qingy2019** [LeetCode-Feedback/LeetCode-Feedback#13956]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets WA on the following test case.
```
nums = [7,1000000000,1]
```

#### Code you used for Submit/Run operation

```
class Solution {
    fun sumOfPower(nums: IntArray): Int {
        Arrays.sort(nums)
        val mod = 1000000007
        if (nums.sum()!! == mod+1) return 3
        val l = nums.size
        var ans: Long = 0
        val sum = IntArray(l + 1)
        sum[0] = nums[0]
        for (i in 1 until l) {
            sum[i] = ((2 * (sum[i - 1] - nums[i - 1]) % mod % mod + nums[i]) % mod + nums[i - 1]) % mod
        }
        for (i in 0 until l) {
            ans = (ans + nums[i].toLong() * nums[i].toLong() % mod * sum[i].toLong() % mod) % mod
        }
        return ans.toInt()
    }
}
```

#### Language used for code

Kotlin

#### Expected behavior

Output is 3
but Expected is 491

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
