### ISSUE TITLE
919. Complete Binary Tree Inserter - Incorrect Test Case is confusing a lot of users

### ISSUE THREAD

**Issue by bclodius** [LeetCode-Feedback/LeetCode-Feedback#13957]
#### Your LeetCode username
[b_clodius](https://leetcode.com/b_clodius/)

#### Category of the bug
- [x] Incorrect Test Cases 

#### Description of the bug

I revisted [this question](https://leetcode.com/problems/complete-binary-tree-inserter/description/) today and was shocked at the same test case others like [@akashgupta9578](https://leetcode.com/akashgupta9578), [@Jason Law](https://leetcode.com/Jason-Law), and [@as9vd2](https://leetcode.com/as9vd2) have pointed out.

My solution which was accepted in early 2022 is no longer valid due to the addition of this invalid test case.

```
["CBTInserter","insert","insert","get_root"]
[[[1,null,2]],[3],[4],[]]
```

Description is clear all nodes are as far left as possible

> A complete binary tree is a binary tree in which every level, except possibly the last, is completely filled, and all nodes are as far left as possible.

Constraints are clear root is a complete binary tree.

> root is a complete binary tree.

Having a tree with no left node but a right node is NOT a complete binary tree per your definition. Why does the test case not follow the constraints of the problem?

#### Expected behavior
I expected the that `root is a complete binary tree.` and it was not.

#### Additional context
Historically this test case was not present for weekly-contest-105 and in the past.  Why was it added.  Clearly the test case is a bug or the description is incorrect.  Many users are confused with its addition!!!

https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/13391
https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/13928

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by bclodius** [comment]
Thank you @LC-Pam !
