### ISSUE TITLE
Problem 1071. Greatest Common Divisor of Strings

### ISSUE THREAD

**Issue by Ankit-11525** [LeetCode-Feedback/LeetCode-Feedback#13952]
#### Your LeetCode username
Pathak_Ankit

#### Category of the bug
 Wrong answer on the Test Case

#### Description of the bug
Leetcode judge taking wrong output as correct answer for AC

#### Code you used for Submit/Run operation

[Greatest Common Divisor of Strings](https://leetcode.com/problems/greatest-common-divisor-of-strings/)
```
class Solution {
public:
    bool check(string s,string t)
    {
        int i=0;
        while(i<s.size())
        {
            for(int j=0;j<t.size();j++)
            {
                if(s[i]!=t[j])
                {
                    return false;
                }
                i++;
            }
        }
        return true;
    }
    string gcdOfStrings(string str1, string str2) 
    {
        for(int i=str2.size()-1;i>=0;i--)
        {
            if(check(str1,str2.substr(0,i+1)) && check(str2,str2.substr(0,i+1)) )
            {
                return str2.substr(0,i+1);
            }
        }
        return "";
    }
};
```

#### Language used for code
C++

#### Expected behavior
Answer should be "AAAAA"

#### Screenshots

![Screenshot from 2023-06-08 00-53-38](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/76417084/08b50c01-9a13-46da-bb03-1bf67d775280)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
