### ISSUE TITLE
Audio is too low on the video tutorial for e.g. Graph card .

### ISSUE THREAD

**Issue by rama-vmw** [LeetCode-Feedback/LeetCode-Feedback#13958]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've submitted your feedback to the team.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
