### ISSUE TITLE
题目描述（翻译错误） - 846. 一手顺子

### ISSUE THREAD

**Issue by astro2049** [LeetCode-Feedback/LeetCode-Feedback#13966]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
dreamy-gouldv88

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
题目描述的第二句话，英文题目为：

> Given an integer array `hand` where `hand[i]` is the value written on the `i`<sup>`th`</sup> card and an integer `groupSize`, return `true` if she can rearrange the cards, or `false` otherwise.

目前的中文版是：

> 给你一个整数数组 `hand` 其中 `hand[i]` 是写在第 `i` 张牌，和一个整数 `groupSize` 。如果她可能重新排列这些牌，返回 `true` ；否则，返回 `false` 。

**期望行为**
对于这一句话，正确的中文版应该是：

> 给你一个整数数组 `hand` ，其中 `hand[i]` 是第 `i` 张牌**上的值**，和一个整数 `groupSize` 。如果她**能够**重新排列这些牌，返回 `true` ；否则，返回 `false` 。

**屏幕截图**
![[846. Hand of Straights](https://leetcode.cn/problems/hand-of-straights/)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/45759373/3b822ca7-cc2d-461d-809d-95825d4aa02a)

**Comment by feiceh** [comment]
感谢反馈，当前题目已更新，奖励已发放。
