### ISSUE TITLE
Missing testcase - 2619. Array Prototype Last

### ISSUE THREAD

**Issue by grishbar** [LeetCode-Feedback/LeetCode-Feedback#13969]
#### Your LeetCode username
[niazox](https://leetcode.com/niazox/)

#### Category of the bug
- Missing Test Cases 

#### Description of the bug
Missing testcase for task - [array-prototype-last](https://leetcode.com/problems/array-prototype-last/description/)

if array consist of [null] or [undefined] my solution will return -1 but it should return null or undefined accordingly
So we need two more testcases:
- [null] => null
- [undefined] => undefined

#### Code you used for Submit/Run operation
```
Array.prototype.last = function() {
    return this.pop() ?? -1;
};
```

#### Language used for code
JS

#### Expected behavior
expected this decision to fail but it passed all the tests

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
