### ISSUE TITLE
875. Longest Mountain in Array : Missing Testcase

### ISSUE THREAD

**Issue by sanjaydogood** [LeetCode-Feedback/LeetCode-Feedback#1396]
#### Your LeetCode username
sanjaydogood

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
My solution passes all testcases but fails on my custom testcase.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int longestMountain(vector<int>& A) {
        
        int n = A.size();
        
        int res = 0;
        int temp = 0;
        
        bool inc = false;
        
        for(int i=0; i<n-1; i++)
        {
            if(A[i] < A[i+1])
            {
                if(inc)
                    temp++;
                else
                {
                    inc = true;
                    if(temp + 1 >= 3)
                        res = max(res,temp + 1);
                    temp = 1;
                }
            }
            else if(A[i] > A[i+1])
            {
                if(temp == 0)
                    continue;
                temp++;
                inc = false;
            }
            else
            {
                // This case here represents flat terrain. It does not check if there was a 
               // rising of the mountain before it. This code will break for input such as [1,2,3,4,5,6,6,6]
                inc = false;
                if(temp + 1 >= 3)
                    res = max(res,temp+1);
                temp = 0;
            }
        }
        
        if(!inc && temp + 1 >= 3)
            res = max(res,temp+1);
        
        return res;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The code gives an error for the test case - [1,2,3,4,5,6,6,6], but it has passed all LeetCode testcases. This testcase checks for an increasing mountain which levels out at the top, which means there is no mountain.

**Comment by lc-kay** [comment]
Hi @sanjaydogood 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @sanjaydogood 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by sanjaydogood** [comment]
Thank you! :)
