### ISSUE TITLE
Missing Test Case - 121. Best Time to Buy and Sell Stock

### ISSUE THREAD

**Issue by yasseennandally** [LeetCode-Feedback/LeetCode-Feedback#13964]
#### Your LeetCode username
 Yasseen Nandally

#### Category of the bug

- [ ] Solution

#### Description of the bug
Easy Python Solution for "Best time to Buy and Sell Stock"

#### Code you used for Submit/Run operation

```
class Solution(object):
    def maxProfit(self, prices):
        max = 0
        for i in range (len(prices)-1):
            j = i + 1
            for j in range (j,len(prices)):
                if prices[j] - prices[i] > max:
                    max = prices[j] -prices[i]
        return max
```

#### Language used for code
Python

#### Expected behavior
Fast and Easy solution

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've submitted your solution to the team. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
