### ISSUE TITLE
题目描述（翻译错误） - 134. 加油站

### ISSUE THREAD

**Issue by astro2049** [LeetCode-Feedback/LeetCode-Feedback#13963]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
dreamy-gouldv88

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
题目描述的最后一段第一句话，英文题目为：

> Given two integer arrays `gas` and `cost`, return _the starting gas station's index if you can travel around the circuit once in the clockwise direction, otherwise return_ `-1`.

目前的中文版是：

> 给定两个整数数组 `gas` 和 `cost` ，如果你可以绕环路行驶一周，则返回出发时加油站的编号，否则返回 `-1` 。

**期望行为**
对于这一句话，正确的中文版应该是：

> 给定两个整数数组 `gas` 和 `cost` ，如果你可以**顺时针**绕环路行驶一周，则返回出发时加油站的编号，否则返回 `-1` 。

**屏幕截图**
![[134. Gas Station](https://leetcode.cn/problems/gas-station/)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/45759373/c3fdfb17-2e9d-4b7f-a0bc-099d78bd740d)

**Comment by feiceh** [comment]
感谢反馈，当前题目已更新，奖励已发放。
