### ISSUE TITLE
Missing Test Case - 1244. Design A Leaderboard

### ISSUE THREAD

**Issue by nskybytskyi** [LeetCode-Feedback/LeetCode-Feedback#13972]
#### Your LeetCode username

[nskybytskyi](https://leetcode.com/nskybytskyi/)

#### Category of the bug

- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The following solution to the problem [1244. Design A Leaderboard](https://leetcode.com/problems/design-a-leaderboard/) gets AC, but should get WA on the suggested test case.

#### Code you used for Submit/Run operation

[Submission link](https://leetcode.com/problems/design-a-leaderboard/submissions/966660712/). This solution keeps player scores in a max-heap and lazily removes them when polling top K elements. It fails in cases when one of the players reaches some score, gets reset, and later achieves the same score again. Such a duplicate record is not cleared correctly.

```java
class Leaderboard {
    private HashMap<Integer, Integer> map;
    private PriorityQueue<Pair> pq;

    static record Pair(int score, int playerId) {}

    public Leaderboard() {
        this.map = new HashMap<>();
        this.pq = new PriorityQueue<>((p1, p2) -> Integer.compare(p2.score, p1.score));
    }

    public void addScore(int playerId, int score) {
        if (map.containsKey(playerId)) {
            map.put(playerId, map.get(playerId) + score);
        } else {
            map.put(playerId, score);
        }
        pq.add(new Pair(map.get(playerId), playerId));
    }

    public int top(int k) {
        int sum = 0;
        List<Pair> pulledPairs = new ArrayList<>();
        for (int i = 0; i < k; i++) {
            Pair top = pq.poll();
            int scoreInMap = map.get(top.playerId);

            if (top.score == scoreInMap) {
                pulledPairs.add(top);
                sum += scoreInMap;
            } else {
                i--;
            }
        }
        pq.addAll(pulledPairs);
        return sum;
    }

    public void reset(int playerId) {
        map.put(playerId, 0);
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution gets WA on the following test case:
```
["Leaderboard","addScore","reset","addScore","addScore","top"]
[[],[1,2],[1],[1,2],[2,1],[2]]
```

#### Additional context

I constructed this test case by hand so there is no generator. The provided solution belongs to my friend [Gurmigou](https://leetcode.com/Gurmigou/). You may want to reward them with some leetcoins too.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
