### ISSUE TITLE
Missing Test Case - 724. Find Pivot Index

### ISSUE THREAD

**Issue by mrmrmr7** [LeetCode-Feedback/LeetCode-Feedback#13971]
#### Your LeetCode username
mrmrmr7

#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [x] Missing Test Cases 

#### Description of the bug

I would like to add a test case that will handle the situation when pivot index equal to the latest position of array.
When left-to-right sum of all elements except the latest is equal to 0.
This corner case is explained in task description, but it also would be great to add such test case to prevent submissions that don't handle these case.

#### Code you used for Submit/Run operation

```
class Solution:
    def pivotIndex(self, nums: List[int]) -> int:
        right_sum = sum(nums[1:])
        left_sum = 0

        for i in range(len(nums) - 1):
            if right_sum == left_sum:
                return i
            else:
                left_sum += nums[i]
                right_sum -= nums[i + 1]

        return -1 if left_sum else len(nums) - 1
```

#### Language used for code

Python

#### Expected behavior

return 2 (index of element before the latest)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
