### ISSUE TITLE
852. Peak Index in a Mountain Array Typo

### ISSUE THREAD

**Issue by coreytalbert** [LeetCode-Feedback/LeetCode-Feedback#13974]
First line should say "An array arr [is] a mountain if the following properties hold: ..."

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
