### ISSUE TITLE
Longest-increasing-subsequence/editorial/ slide has incorrect text

### ISSUE THREAD

**Issue by alexhowarth** [LeetCode-Feedback/LeetCode-Feedback#13976]
#### Your LeetCode username
x3la

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The slide for "Approach 1" of the editorial here: https://leetcode.com/problems/longest-increasing-subsequence/editorial/ has the wrong text for step 11/18

Should read "Since 3 > 2" rather than "5 > 2"

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
