### ISSUE TITLE
Same code but different result

### ISSUE THREAD

**Issue by LiuLongyang0305** [LeetCode-Feedback/LeetCode-Feedback#1398]
#### Your LeetCode username
 KuShulian

#### Category of the bug
- [x] Question
- [ ] Solution
- [x] Language

#### Description of the bug
For question1655, the case `nums = [1,1,2,2,1], quantity = [2,2,1]`,I got a wrong result after submitting my code while I could 
got a correct result in test enviromment .

#### Code you used for Submit/Run operation
```swift
class Solution {
    private struct State: Hashable {
        var idx: Int
        var counter: [Int:Int]
    }
    func canDistribute(_ nums: [Int], _ quantity: [Int]) -> Bool {
        guard nums.reduce(0, {$0 + $1}) >= quantity.reduce(0, {$0 + $1}) else { return false }
        var counter = [Int:Int]()
        nums.forEach { counter[$0, default: 0] += 1}
        let sortedQuantity = quantity.sorted()
        let N = quantity.count
        var memo = [State:Bool]()
        func backtracking(_ idx:Int, _ numsCounter: [Int:Int]) -> Bool {
            guard idx < N else {
                return true
            }
            let key = State(idx: idx, counter: counter)
            guard memo[key] == nil else {
                return memo[key]!
            }
            for (num,cnt) in numsCounter {
                if cnt >= sortedQuantity[idx] {
                    var tempCounter = numsCounter
                    tempCounter.updateValue(cnt - sortedQuantity[idx], forKey: num)
                    guard !backtracking(idx + 1, tempCounter) else {
                        memo[key] = true
                        return true
                    }
                }
            }
            memo[key] = false
            return false
        }
        return backtracking(0, counter)
    }
}
```

#### Language used for code
swift

#### Expected behavior
Get a 'true' on this case when submitting my code 

#### Screenshots
![1655_submit_error](https://user-images.githubusercontent.com/43689684/99345733-e9273680-28cd-11eb-8d78-f8718d35026e.jpg)
![1655_test](https://user-images.githubusercontent.com/43689684/99345734-eb899080-28cd-11eb-9f96-f9ab748c9296.jpg)

**Comment by lc-kay** [comment]
Hi @LiuLongyang0305 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.

**Comment by LiuLongyang0305** [comment]
@lc-kay I've checked my code, and I am sure that **I don't use any global or static variables**. It is unlikely to pass the first 89  test cases if there is a some bugs in my code.

**Comment by lc-kay** [comment]
Hi @LiuLongyang0305 
I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@LiuLongyang0305 We have tried to run this code in the run code 10 times, 7 of them gave me true and 3 showed false.
The code submitted is wrong and is not consistent.
The value of the counter map is [1: 3, 2: 2] and [2: 2, 1: 3]
when it is [1: 3, 2: 2] the code gives accepted.
when it is [2: 2, 1: 3] the code gives the wrong answer.
