### ISSUE TITLE
Missing testcase - 140. Word Break II

### ISSUE THREAD

**Issue by bahailu-abera** [LeetCode-Feedback/LeetCode-Feedback#13988]
#### Your LeetCode username

[bahailu-abera
](https://leetcode.com/bahailu/)

#### Category of the bug
-  Missing Test Cases 

#### Description of the bug

When running the code , it exceeds the time limit for the given test case. However, when submitting the code, it gets accepted. This indicates a testcase is missing in the online judge. The bug is related to the code's efficiency and time complexity.

Steps to Reproduce
Use the test case:
Input string: "catsanddogcatsanddog"
Word dictionary: ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]
Execute the code locally.
Observe that the code takes an extended amount of time and exceeds the time limit.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<string> wordBreak(string s, vector<string>& wordDict) {
        int n = (int)s.size();
        vector<string> ans;
        
        function<void(string, string)> backtrack = [&](string current, string chosen)
        {
            int currentlen = (int)current.size();

            if (currentlen == n && current == s)
            {
                ans.push_back(chosen.substr(1, chosen.size() - 1));
                return;
            }

            if (currentlen >= n)
                return;

            for (string& str: wordDict)
            {
                backtrack(current + str, chosen + " " + str);
            }
        };

        backtrack("", "");

        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The online judge must say time limit exceeded for the given testcase.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
