### ISSUE TITLE
Missing Test Case - 2726. Calculator with Method Chaining

### ISSUE THREAD

**Issue by aleneum** [LeetCode-Feedback/LeetCode-Feedback#13989]
#### Your LeetCode username
aleneum

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Tests currently do not check the return value to be of type Calculator. More precisely, the returned value should be used for the next test to test chaining.
Furthermore, `Calculator.divide` does not require an exception to be thrown as setting `this.value` also satisfies the current tests (see [1]).

#### Code you used for Submit/Run operation
```javascript
class Calculator {
  constructor(value) {
        this.value = value
  }
  add(value){
        this.value = this.value + value
  }
  subtract(value){
      this.value = this.value - value
  }
  multiply(value) {
      this.value = this.value * value
  }

  divide(value) {
      if(value == 0) return this.value = "Division by zero is not allowed" // [1]
      this.value  = this.value / value
  }
  
  power(value) {
      this.value = this.value ** value
  }
    
  getResult() {
      return this.value
  }
}

//  new Calculator(5).add(5).getResult() // -> TypeError: Cannot read properties of undefined (reading 'getResult')
//  try {
//    new Calculator(5).divide(0);
//    throw new Error("Should not be thrown!");
//  } catch(err) {
//    if(err.message !== "Division by zero is not allowed") {
//      throw err;
//    }
//  } // -> Error: Should not be thrown!
```

#### Language used for code
JavaScript

#### Expected behavior
The above mentioned code should fail  because a) `Calculator.add/power/divide/add` do not return a `Calculator` object and b) `Calculator.divide` does not throw an exception.

#### Screenshots
![Screenshot 2023-06-09 at 14 34 04](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/205986/17a60be5-0593-4565-9de9-f343f3f75812)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
