### ISSUE TITLE
Missing test case. 488 Zuma Game. Wrong solutions accepted

### ISSUE THREAD

**Issue by ashutosh3027** [LeetCode-Feedback/LeetCode-Feedback#13990]
#### Your LeetCode username
ashutosh3027

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [x] Missng Test Cases 

#### Description of the bug

For following test case expected answer given by leetcode is 2 but it should be -1.Almost all accepted solutions are giving ans as 2. 

`board = "RRWWRRBBRR"
hand = "WB" \n
`

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by stormsunshine** [comment]
The correct answer is indeed 2. The steps are as follows.
1. "RRWWRRBBRR" -> "RRWWRRBBR**W**R"
2. "RRWWRRBBRWR" -> "RRWWRRBB**B**RWR" -> "RRWWRRRWR" -> "RRWWWR" -> "RRR" -> ""

If you think a solution is wrong, please debug first to see whether there is a possibility that you haven't thought of.
