### ISSUE TITLE
Missing Test Case - 2604. Minimum Time to Eat All Grains

### ISSUE THREAD

**Issue by xymabinogi** [LeetCode-Feedback/LeetCode-Feedback#13999]
#### Your LeetCode username
xymabinogi

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Missing edge cases.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int minimumTime(vector<int>& hens, vector<int>& grains) {
        sort(hens.begin(), hens.end()); 
        sort(grains.begin(), grains.end()); 
        int lo = 0, hi = 1e9; 
        while (lo < hi) {
            int mid = lo + (hi-lo)/2, i = 0; 
            for (auto& h : hens) 
                for (int ii = i; i < grains.size() && (grains[i] <= h && h-grains[i] <= mid || h <= grains[ii] && grains[i]-h<= mid || grains[ii] <= h && h <= grains[i] && grains[i]-grains[ii]+min(grains[i]-h, h-grains[ii]) <= mid); ++i); 
            if (i == grains.size()) hi = mid; 
            else lo = mid+1; 
        }
        return lo; 
    }
};
```

#### Language used for code

C++

#### Expected behavior

WA on following case:
[500000000]
[1,1000000000]

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
