### ISSUE TITLE
Missing testcase, 1186. Maximum Subarray Sum with One Deletion

### ISSUE THREAD

**Issue by Saharsh-R** [LeetCode-Feedback/LeetCode-Feedback#1399]
#### Your LeetCode username
Saharsh-R

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language

#### Summary in short
Any testcase should be added where all the elements in the array are positive.
A short example can be
```
[100, 30, 1, 987, 400, 200, 9]
```

#### Description of the bug
In this question, [1186. Maximum Subarray Sum with One Deletion](https://leetcode.com/problems/maximum-subarray-sum-with-one-deletion/), there is **no testcase** where **all the elements in the array are positive**.

I realised it after I used the following code which gives the maximum sum when 1 element is definitely removed in the subarray. 

#### Code you used for Submit/Run operation
I realised there are much better solutions after looking at the discussions. But this code also got accepted.
```
class Solution:
    def maximumSum(self, arr: List[int]) -> int:
        ans = float('-inf')
        n = len(arr)
        if n == 1:
            return arr[0]
        maxi = max(arr)
        if maxi < 0:
            return maxi
        
        pre = []
        suf = []
        
        curr = 0
        for x in arr:
            curr += x
            if curr < 0:
                pre.append(0)
                curr = 0
            else:
                pre.append(curr)
                
        curr = 0
        for x in reversed(arr):
            curr += x
            if curr < 0:
                suf.append(0)
                curr = 0
            else:
                suf.append(curr)
        suf = suf[::-1]

        ans =  max(pre[i-1] + suf[i+1] for i in range(1,n-1))
        ans = max(pre[-2] , ans, suf[1])
        return ans
```

#### Language used for code
Python3

#### Expected behavior
In my code, if we use the following testcase,
```
[100, 30, 1, 987, 400, 200, 9]
```
It returns `1726 (after deleting the element "1" arr[2] )` instead of `1727 (sum of all the elements)`
This is because I forgot about the condition whether all the elements in the array are positive.

#### Screenshots
<img width="432" alt="Screenshot 2020-11-18 at 11 22 18 AM" src="https://user-images.githubusercontent.com/48884865/99490720-6915d500-2990-11eb-85ba-8f99accd1af5.png">

#### Final remarks
So any testcase should be added where all the elements in the array are positive.

**Comment by lc-kay** [comment]
Hi @Saharsh-R 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Saharsh-R 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
