### ISSUE TITLE
62. Unique Paths提供数据

### ISSUE THREAD

**Issue by nekopara-orz** [LeetCode-Feedback/LeetCode-Feedback#14]
** Bug 类型**
- [x] 题目
- [ ] 题解

**描述**
对于一些程序本应该无法通过某些数据但是能通过

**代码**
```
// 我的代码和题解代码能通过数据
class Solution {
public:
    int uniquePaths(int m, int n) {
        long long ans = 1;
        int j = 1;
        if(m > n) swap(m,n);
        for(int i = n; i <= m + n - 2;i++)
        {
            ans = ans * i / j;
            j++;
        }
        return ans;
    }
};

// 下面的程序无法通过下面的用例，但是能通过当前所有数据。
class Solution {
public:
    int uniquePaths(int m, int n) {
		if(m<n)swap(m,n);
		long long ans=1;
		for(int i=m;i<=m+n-2;i++)
			ans*=i;
		for(int i=1;i<=n-1;i++)
			ans/=i;
		return (int)ans;
    }
};
```

**期望行为**
增加数据
Input: 
16
16

Output: 
155117520

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认的～

**Comment by Miloas** [comment]
我们不会添加 16 16 的 testcase， 因为 LeetCode 暂时不支持 64 位整型，需要用户自己 handle overflow 的情况

**Comment by nekopara-orz** [comment]
你是认真的么，我这个哪里超过INT32了。题库那么多要处理溢出的题，而我这个用例没有溢出都不行了？

**Comment by nekopara-orz** [comment]
![image](https://user-images.githubusercontent.com/28264029/76182435-e2550980-61ff-11ea-8322-72c458186a30.png)
你看看这组数据溢出了么，我这里是要让一些不合理的程序不能通过。

**Comment by Miloas** [comment]
你想用 16 16 让下面的代码溢出，我在怀疑你能不能听懂人话

**Comment by nekopara-orz** [comment]
你们那么多卡数据的题，我这个卡数据就不行了？

**Comment by Miloas** [comment]
我们肯定是想让测试样例更加 strong，但是不是你想加我们就加了。你看到的是卡掉了一个代码，我们看到的是一坨验证器好不好改。

**Comment by Miloas** [comment]
我们肯定是想让测试样例更加 strong，但是不是你想加我们就加了。你看到的是卡掉了一个代码，我们看到的问题更多，我们有专门的团队评估。

**Comment by Miloas** [comment]
> 你想用 16 16 让下面的代码溢出，我在怀疑你能不能听懂人话

抱歉兄弟，早上和我处了十三年的男朋友跟我分手了，看见你三个反问就原地爆炸了，理解一下。是我第一次回复你的时候没有描述清楚，我会 reopen 这个 issue，尝试和题目团队再沟通一下。另外非常感谢你提供testcase，如果你愿意的话可以提供你在中站的用户id，如果testcase合并，会给你奖励一些LeetCoin。再次感谢

**Comment by nekopara-orz** [comment]
好吧互相理解，我其实在leetcode上刷题就是图开心。因为以前也参加些比赛，突然甚么都不干了也有些放不下，偶尔写写题看看评论也想顺便做做贡献。谢谢你能回复我。
我的账号是13092973652

**Comment by feiceh** [comment]
@nekopara-orz 非常感谢您对力扣的社区贡献，实在抱歉，因题目涉及到全球，经题目团队综合评估反馈，该用例无法添加。非常感谢您这样的积极用户对力扣网站的支持，祝您生活愉快。ˆ＾‿＾
