### ISSUE TITLE
Missing Test Case - 646. Maximum Length of Pair Chain

### ISSUE THREAD

**Issue by FAlooC** [LeetCode-Feedback/LeetCode-Feedback#14002]
#### Your LeetCode username

FAlooC

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Missing test case. `pairs` array with a single entry, where the value of `left` is the minimum possible value.

#### Code you used for Submit/Run operation

```
class Solution {
    public int findLongestChain(int[][] pairs) {
        int MIN = -1000;
        int MAX = 1000;
        int LEN = MAX - MIN + 1;
        int[] start = new int[LEN];
        int[] count = new int[LEN];

        for (int i = 0; i < LEN; i++)
            start[i] = -1;

        for (int i = 0; i < pairs.length; i++) {
            start[pairs[i][1] - MIN] = 
                Math.max(start[pairs[i][1] - MIN], pairs[i][0] - MIN);
        }

        for (int i = 1; i < LEN; i++) {
            count[i] = count[i - 1];
            if (start[i] != -1 && start[i] != 0)
                count[i] = Math.max(count[i], count[start[i] - 1] + 1);
        }

        return count[LEN - 1];
    }
}
```

#### Language used for code

Java

#### Expected behavior

Output using my answer: 0.
Expected output: 1.
Expected result: Wrong answer.
But the answer is still accepted.

#### Screenshots

<img width="1435" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/51229836/1c149240-9d9f-4336-aedf-367b0172b985">
<img width="1416" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/51229836/08d5105d-e006-4314-a2fd-cfa0505fb7c2">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
