### ISSUE TITLE
Heap Implementation

### ISSUE THREAD

**Issue by raymondhfeng** [LeetCode-Feedback/LeetCode-Feedback#1400]
Any plans to make a Design problem to implement a heap?

**Comment by lc-kay** [comment]
@raymondhfeng Please redirect this feature request to our help desk. https://support.leetcode.com/hc/en-us/requests/new 
We encourage you to share more content-related issues here with us for [valid content contribution rewards](https://leetcode.com/discuss/general-discussion/526802/File-Problem-and-Solution-Content-Issues-to-Our-GitHub-Public-Feedback-Repo-Now!). Thank you again for your support and understanding.
