### ISSUE TITLE
1802 wrong testcase

### ISSUE THREAD

**Issue by aNOOBisTheGod** [LeetCode-Feedback/LeetCode-Feedback#14007]
#### Your LeetCode username
aNOOBisTheGod

#### Category of the bug
- [ ] Question

#### Description of the bug
While doing task  _1802. Maximum Value at a Given Index in a Bounded Array_ I've found a testcase like this
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/69043738/eb42db4e-a0ab-4848-97f2-192eb003ba32)
And it says that correct answer is 1
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/69043738/34e0ae50-c091-4d6b-aeb4-ffc9d1742e94)
but... I don't agree cause we can imagine array [2, 1, 0, 0] and it will satisfy all requirements as I can see so the value at index 0 is 2, not 1... Ig this is a bug, maybe I have missed something in description, but I've read it like 10 times...

#### Code you used for Submit/Run operation

``` 
class Solution:

    def maxValue(self, n: int, index: int, maxSum: int) -> int:

        if n == 1:
            return maxSum
        leftBorder = maxSum
        rightBorder = 0
        left = n - index - 1
        right = index
        was = []
        value = (rightBorder + leftBorder) // 2
        # print(left, right, "<")
        while value not in was:
            summ = value
            for i in range(right):
                # print(value - i - 1 if value - i - 1 > 0 else 0, value, "right")
                summ += value - i - 1 if value - i - 1 > 0 else 0
            for i in range(left):
                # print(value - i - 1 if value - i - 1 > 0 else 0, value, "left")
                summ += value - i - 1 if value - i - 1 > 0 else 0
            if summ == maxSum:
                return value
            if summ > maxSum:
                leftBorder = value
            else:
                rightBorder = value
            # print(summ, value)
            was.append(value)
            value = (rightBorder + leftBorder) // 2
        return value

```

#### Language used for code
Python3

#### Expected behavior
Expected result should be 2, not 1

**Comment by Rembamb** [comment]
The thing is that nums[i] must be positive. However, 0 is neither positive nor negative. So, you cannot create an array [2, 1, 0, 0]. The largest one you can make is [1, 1, 1, 1]. I think you saw the positive part as also including zero.

**Comment by aNOOBisTheGod** [comment]
> The thing is that nums[i] must be positive. However, 0 is neither positive nor negative. So, you cannot create an array [2, 1, 0, 0]. The largest one you can make is [1, 1, 1, 1]. I think you saw the positive part as also including zero.

ohhh I got it... thanks)
