### ISSUE TITLE
Missing Test Case - 2732. Find a Good Subset of the Matrix

### ISSUE THREAD

**Issue by Dante-24** [LeetCode-Feedback/LeetCode-Feedback#14018]
#### Your LeetCode username

anhiks

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

Some solutions are working for a testcase that should give the verdict as "Time Limit Exceeded". Following is the case:
[output.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/11713071/output.txt)

#### Code you used for Submit/Run operation

```
#define ll int
#define forj(n) for (ll j = 0; j < n; j++)
class Solution {
public:
    vector<int> goodSubsetofBinaryMatrix(vector<vector<int>>& v) {
ll n = v.size(),m = v[0].size();
    // If any of m cols have sm >= (n/2)
    vector<int> ans;
    for(ll i = 0;i<n;++i){
        ll sm = 0;
        forj(m){
            sm += v[i][j];
        }
        if(!sm){ans.push_back(i);return ans;}
    }

    for(ll i = 0;i<n;++i){
        for(ll j = i+1;j<n;++j){
            ll f = 0;
            for(ll k = 0;k<m;++k){
                f |= (v[i][k] && v[j][k]);
            }

            if(!f){
                // ans.push_back(i);
                // ans.push_back(j);
                return {i,j};
            }
        }
    }
    
    return ans;
    }
};
```

#### Expected behavior

The aforementioned code should get the verdict as "Time Limit Exceeded".

#### Screenshots

![hack1](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/62325969/5d123823-5760-4574-bff6-c4193e50515b)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
