### ISSUE TITLE
Testcase for 2731. Movement of Robots 

### ISSUE THREAD

**Issue by nipunarora098** [LeetCode-Feedback/LeetCode-Feedback#14013]
[-2,0,2000000000]
"RRR"
1000000000 
My code **failed** on this test case but answer is still **accepted.**
class Solution {
public:
    int mod = 1e9 + 7;
    int sumDistance(vector<int>& nums, string s, int d) {
        // vector <long long > num(nums.size());
        
        for(int i = 0 ; i < s.size() ; i++){
            // num[i] = nums[i];
            if(s[i] == 'R') nums[i]+=d ;else nums[i]-=d;}
        sort(nums.begin() , nums.end());
        long long ans = 0;
        long long sum = 0;
        for(int i = 0 ; i < nums.size() ; i++){
            ans += abs(i*1ll*nums[i] - sum);
            ans %= mod;
            // sum%=mod;
            sum += nums[i];
        }
        return (int)ans;
    }
};

**Comment by yumkam** [comment]
Disclaimer: just another leetcode user
Actually, if you fix this bug (e.g. copy `nums` to `vector<int64_t>`), "official" solution would fail and testcase will be deemed invalid:
```
Invalid Testcase
Line 9: Char 25: runtime error: signed integer overflow: 2000000000 + 1000000000 cannot be represented in type 'int' (solution.cpp)
```
Probably, constraints or problem description should explicitly state such testcase are invalid? (e.g. something like "testcases generates such as all intermediate robot positions fits in `-2*10^9` to `+2*10^9` range")

**Comment by nipunarora098** [comment]
I don't understand please explain a little more buddy please ?

**Comment by Dimpal-Kalita** [comment]
Buddy wait for them to rejudge the contest, They will add a few missing testcases. I think your solution will be rejected then. Please check after a few days.

**Comment by nipunarora098** [comment]
@Dimpal-Kalita  I satisfied the given testcase in my submission but after contest when i see other's solution i came to know that this testcase was missed and when i check by submitting this solution then I came to know that this testcase is missing.

**Comment by Dimpal-Kalita** [comment]
Yes They add new testcases after a few days of the contest. My solution solution of two problems got rejected in last two contests

Like it showed Accepted on the contest but after the contest they rejudged the contest I guess, I showed Wrong Answer

I submitted the solutions again after correcting, It got an Accepted verdict.

**Comment by nipunarora098** [comment]
You are right, they also consider test case submitted by participants.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by nipunarora098** [comment]
Yes sure @LC-Pam 
Here is the submission link of the accepted code which is failing on the shared testcase.
https://leetcode.com/problems/movement-of-robots/submissions/968204500/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Hi there,

Your feedback has been instrumental in enhancing the problem. 

To ensure you receive your well-deserved 100 LeetCoins reward, could you kindly provide us with your LeetCode username? This will allow us to credit your account accurately.

Your participation and contributions are valued, and we want to make sure you enjoy the rewards you've earned.

Thank you for being part of the LeetCode community!

Best regards,
LeetCode Team
