### ISSUE TITLE
Missing Test Case - 1071. Greatest Common Divisor of Strings

### ISSUE THREAD

**Issue by hitasher** [LeetCode-Feedback/LeetCode-Feedback#14016]
#### Your LeetCode username
hitasher

#### Category of the bug
Missing Test Cases 

#### Description of the bug
Wrong code has passed the tests. My program first checks to see if one of the two strings is a prefix of the other. Then, starting at the next character of the longest string, a check is made to see if the string consists of a repeating pattern from the beginning of the string. However, it is not taken into account that some characters may not be a pattern, since the check does not reach them.
The examples of missing test cases are below:

str1= "ABCDEFABC"
str2= "ABCDEF"
Output: "ABC"
Expected: ""

And another one:

str1= "ABA"
str2= "AB"
Output: "A"
Expected: ""

#### Code you used for Submit/Run operation
```
# 1071. Greatest Common Divisor of Strings
class Solution:
    def gcdOfStrings(self, str_1: str, str_2: str) -> str:
        if any(a != b for a, b in zip(str_1, str_2)):
            return ''
        g: int = gcd(len(str_1), len(str_2))
        largest_str: str = str_1 if len(str_1) > len(str_2) else str_2
        check_start_index: int = max(g, min(len(str_1), len(str_2)))
        if any(ch != largest_str[i % g] for i, ch in enumerate(islice(largest_str, check_start_index, None))):
            return ''
        return largest_str[:g]
```

#### Language used for code
Python3

#### Expected behavior
I expected to see my program fail the test cases, but it did.

#### Additional context
First time seeing a bug in test cases :) 
Sorry, I don't speak English well, used Google Translate ;)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
