### ISSUE TITLE
LC578 Question Description is wrong for MSSQL

### ISSUE THREAD

**Issue by xcheng10** [LeetCode-Feedback/LeetCode-Feedback#1401]
#### Category of the bug
- Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The action must be != 'answer' instead of = 'show' to pass all test cases.

In the solution tab, it is mentioned that 'Calculate the answered times / **show times** for each question.'

**Comment by lc-kay** [comment]
Hi @xcheng10 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @xcheng10 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
