### ISSUE TITLE
Missing Test Case - 1802. Maximum Value at a Given Index in a Bounded Array

### ISSUE THREAD

**Issue by itsTodFod** [LeetCode-Feedback/LeetCode-Feedback#14021]
#### Your LeetCode username

avvalnarang2k4

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In Problem 1802. Maximum Value at a Given Index in a Bounded Array, One of the testcases is 
> n = 4
> index = 0
> maxSum = 4
> Expected Output = 1
But the `Expected Output` should be `2`.
We have a possible array `[2, 1, 1, 0]` which haves `max( nums[index] )` equal to `2`.

#### Code you used for Submit/Run operation

```
// 1802. Maximum Value at a Given Index in a Bounded Array
class Solution {
public:
    int maxValue(int n, int index, int maxSum) {
        if(n == 1)
            return maxSum;
        int increment = 1, extra = 0, maxVal = 0;
        while(maxSum > 0) {
            maxVal++;
            maxSum -= (increment + extra);
            if(index + increment/2 < n-1 && index - increment/2 > 0) {
                increment = increment<<1;
                increment = increment | 1;
            }
            else if(index + increment/2 + extra < n-1 || index - increment/2 - extra > 0) {
                extra++;
            }
        }
        if(maxSum < 0)
            maxVal--;
        return maxVal;
    }
};
```

#### Expected behavior

In Problem 1802. Maximum Value at a Given Index in a Bounded Array, One of the testcases is 
> n = 4
> index = 0
> maxSum = 4
> Expected Output = 1
But the `Expected Output` should be `2`.
We have a possible array `[2, 1, 1, 0]` which haves `max( nums[index] )` equal to `2`.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/96081283/573d21c2-261b-4410-8918-16a544a8ecb7)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/96081283/45ba2d4c-faaa-4a8d-b216-620d1ae181e0)

#### Additional context

It is also the daily problem of 10 June, 2023.

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
