### ISSUE TITLE
703 题目叙述有误

### ISSUE THREAD

**Issue by tankoni** [LeetCode-Feedback/LeetCode-Feedback#1402]
本题叙述有误，根据题目描述，求的是第K大的元素，但是由示例和题目评判的结果来看，题所要求的是倒数第K大的数，下面是大体排序后数的情况：
K：3， 【2458】
1 add(3)后；【23 458】return 4;
2 add(5)后：【234 558】return 5;
3 add(10)后：【2345 5810】return 5;
4 add(9)后：【23455 8910】return 8;
5 add(4)后：【234455 8910】return 8;

结论：根据这样理解题意的话用自带PriorityQueue和手写最小堆排序才能通过提交。

**Comment by PsiACE** [comment]
Hi，举个例子你看下哈，以你的第 5 行 `add(4)后：【234455 8910】return 8;`，这里第 1 大（最大）是 10 ，第 2 大是 9，第 3 大就是 8 ，很显然返回的是第 k 大。虽然在你的序列中表现为倒数第 3 个元素，但要注意它和倒数第 k 大是不一样的。
