### ISSUE TITLE
Missing Test Case - 2732. Find a Good Subset of the Matrix

### ISSUE THREAD

**Issue by NiloyDas19** [LeetCode-Feedback/LeetCode-Feedback#14022]
#### Your LeetCode username
Niloy_Das_19

#### Category of the bug
Missing Test Cases

#### Description of the bug
Some people tried a brute force approach to solve this question and this solution was accepted in contest time. But the time complexity of the brute force solution is O(m*m*n). Where m equals the number of rows and n equals the number of columns. Max row will be 10000 and max column will be 5., so the overall approximate time complexity, in the worst case, will be O(10000*10000*5).  So the brute force solution should give a TLE verdict. Maybe Leetcode misses  those  test cases.
Test Case is given below:
Input: grid =  [testcase](https://pastebin.com/JkemtGPR)
Output: []
But it should give TLE for brute force solution like below.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int sum(vector<int>& r1,vector<int>& r2) {
        int t = 0;
        for (int i = 0; i < r1.size(); i++) {
            if(r1[i] and r2[i])t++;
        }
        return t;
    }
    vector<int> goodSubsetofBinaryMatrix(vector<vector<int>>& grid) {
        vector<int>ans;
        bool ch=true;
        for (int i = 0; i < grid.size(); i++) {
            if (accumulate(grid[i].begin(), grid[i].end(), 0LL) == 0) {
                ans.push_back(i);
                ch=false;
            }
        }
        if(ch){
            for (int i = 0; i < grid.size(); i++) {
                for (int j = i + 1; j < grid.size(); j++) {
                    if (sum(grid[i], grid[j]) == 0) {
                        ans.push_back(i);
                        ans.push_back(j);
                        ch=false;
                        break;
                    }
                }
                if(!ch)break;
            }
        }
        return ans;
    }
};
```

#### Language used for code
C++

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
