### ISSUE TITLE
1146. Snapshot Array - Incorrect Time Complexity in Editorial

### ISSUE THREAD

**Issue by NKwatra** [LeetCode-Feedback/LeetCode-Feedback#14028]
#### Your LeetCode username

[NKwatra](https://leetcode.com/NKwatra/)

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the [editorial](https://leetcode.com/problems/snapshot-array/editorial/), second approach (**Binary Search**) complexity analysis of `set(index,snap_id)` is incorrect. In the method we put a value into a TreeMap. Since TreeMap is backed by balanced BSTs, complexity of insertion in TreeMap is `O(logn)` and not `O(1)`.

In the worst case `O(n)` calls can be made to `snap`. TreeMap will contain `O(n)` elements in this case and insertion will require `O(logn)` time.

#### Screenshots

![Screenshot 2023-06-11 at 9 21 39 AM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/29563447/e037d222-ee9e-48d4-b9f0-9eb6aceb3dfb)
![Screenshot 2023-06-11 at 9 21 59 AM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/29563447/a0d37d76-c7dc-45b1-9200-52c3dd1d5fd2)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
