### ISSUE TITLE
Incorrect Output shown in console- 2725. Interval Cancellation

### ISSUE THREAD

**Issue by sidsinr** [LeetCode-Feedback/LeetCode-Feedback#14033]
#### Your LeetCode username
sidsinr

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Incorrect Test Case 

#### Description of the bug
The expected output of Test Case 1 is incorrectly displayed in the console when the code is executed by clicking 'Run.' As a result, the console gives Wrong Answer even for the correct code. However, this error does not occur when the code is submitted and the solution gets Accepted. 
This situation creates confusion for users because the question description provides the same test case, but the output mentioned in the description differs from the expected output of the test case.

#### Input and output mentioned in example 1 of the question description
```
Input: fn = (x) => x * 2, args = [4], t = 20, cancelT = 110
Output: 
[
   {"time": 0, "returned": 8},
   {"time": 20, "returned": 8},
   {"time": 40, "returned": 8},
   {"time": 60, "returned": 8},
   {"time": 80, "returned": 8},
   {"time": 100, "returned": 8}
]
Explanation: Every 20ms, fn(4) is called. Until t=110ms, then it is cancelled.

const cancel = cancellable(x => x * 2, [4], 20);
setTimeout(cancel, 110);

1st fn call is at 0ms. fn(4) returns 8.
2nd fn call is at 20ms. fn(4) returns 8.
3rd fn call is at 40ms. fn(4) returns 8.
4th fn call is at 60ms. fn(4) returns 8.
5th fn call is at 80ms. fn(4) returns 8.
6th fn call is at 100ms. fn(4) returns 8.
```

#### Input of Case 1:
```
(x) => x * 2
```
```
[4]
```
```
20
```
```
110
```

#### Expected Output of Case 1 (This part is incorrectly displayed)
```
[{"time":0,"returned":8},{"time":32,"returned":8},{"time":52,"returned":8},{"time":72,"returned":8},{"time":92,"returned":8}]
```

#### My output
```
[{"time":1,"returned":8},{"time":22,"returned":8},{"time":42,"returned":8},{"time":62,"returned":8},{"time":82,"returned":8},{"time":102,"returned":8}]
```

#### Screenshots
<img src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/118676744/9ba81874-1abd-4244-8af6-708d9d6061d1" width="60%" height="60%">
Different expected output for Case 1 leads to Wrong Answer. But on Submitting this, the solution gets Accepted.

#### Code you used for Submit/Run operation
```
// Interval Cancellation
var cancellable = function(fn, args, t) {
    fn(...args);
    let interval = setInterval(() => fn(...args), t);
    return function() {
        clearInterval(interval);
    }
};
```

#### Language used for code
JavaScript

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

We increased the minimum gap between t and cancel. Now it is 15 ms

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
