### ISSUE TITLE
1146: Snapshot Array - Test Case Validation

### ISSUE THREAD

**Issue by jwagner** [LeetCode-Feedback/LeetCode-Feedback#14039]
#### Your LeetCode username
jwagner

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
It looks like the validation of test cases is too lax, which in case allows test cases that break the reference code.
Specifically the index argument to get is described as constrained to `0 <= index < length`. The test checks seem to check for '0 <= index <= length'.

#### Code you used for Submit/Run operation
This is the case which lead me to discover the issue
```
["SnapshotArray","set","snap","set","get","get"]
[[3],[0,5],[],[0,6],[0,0],[3,0]]
```
Seems to crash the test runner (see screenshot).

```
["SnapshotArray","get"]
[[3],[3,0]]
```
Also seems to trigger an odd assertion error 
```
'get' arguments are invalid: expected 'snap_id' to have value from 0 to -1 only
```

Here is my full submission code just in case it is somehow relevant:
```rust
#[derive(Clone)]
struct SnapshotValue {
    snap_id: i32,
    value: i32,
}

struct SnapshotArray {
    data: Vec<Vec<SnapshotValue>>,
    current_snap_id: i32,
}

/**
 * `&self` means the method takes an immutable reference.
 * If you need a mutable reference, change it to `&mut self` instead.
 */
impl SnapshotArray {
    fn new(length: i32) -> Self {
        Self {
            data: vec![
                vec![SnapshotValue {
                    snap_id: 0,
                    value: 0
                }];
                // the task description states index < length,
                // the test validation rules seem to allow index = length
                length as usize + 1
            ],
            current_snap_id: 0,
        }
    }

    fn set(&mut self, index: i32, val: i32) {
        let snapshots = &mut self.data[index as usize];
        let snapshot = snapshots.last_mut().unwrap();
        if snapshot.snap_id == self.current_snap_id {
            snapshot.value = val;
            return;
        }
        let snapshot = SnapshotValue {
            snap_id: self.current_snap_id,
            value: val,
        };
        snapshots.push(snapshot);
    }

    fn snap(&mut self) -> i32 {
        self.current_snap_id += 1;
        self.current_snap_id - 1
    }

    fn get(&self, index: i32, snap_id: i32) -> i32 {
        let snapshots = &self.data[index as usize];
        // could accelerate this with a linear search as long as snapshots is relatively short
        let search_result = snapshots.binary_search_by(|probe| probe.snap_id.cmp(&snap_id));
        match search_result {
            Ok(offset) => snapshots[offset].value,
            Err(partition_point) => {
                assert!(partition_point > 0);
                snapshots[partition_point - 1].value
            }
        }
    }
}

```

#### Language used for code
The submission was in Rust.

#### Expected behavior
A message that the test case is invalid because the value 3 for `index` is not < `length`

#### Screenshots

![Screenshot from 2023-06-11 10-53-15](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/293536/c81ad360-aab0-4e91-8fba-4446d9f6899f)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
