### ISSUE TITLE
1146. Snapshot Array: Solution description issue

### ISSUE THREAD

**Issue by sergey135** [LeetCode-Feedback/LeetCode-Feedback#14036]
#### Your LeetCode username

Ivv135uk

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases

#### Description of the bug

For `TreeMap` the time complexity of `get()/put()`  should be `log(n)`, while the solution is stating:  

`Each call to set(index, snap_id) appends a pair to the historical record of nums[index], which takes
O(1) time.
`

```
TreeMap<Integer, Integer>[] historyRecords;
    
 public void set(int index, int val) {
        historyRecords[index].put(snapId, val);
    }
```

Basically, the `set(int index, int val)` method complexity should be `log(n)` 

The solution URL: 

https://leetcode.com/problems/snapshot-array/solution/

The Solution approach name:
`Approach: Binary Search`

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
