### ISSUE TITLE
Impossible restrictions - 394. Decode String

### ISSUE THREAD

**Issue by mihaild** [LeetCode-Feedback/LeetCode-Feedback#1403]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Test `"300[300[300[300[q]]]]"`
This test will have output with 8,100,000,000 symbols, which is almost impossible to write.

#### Code you used for Submit/Run operation
```cpp
class Solution {
public:
    string decodeString(string s) {
        string result;
        for (auto c : s) {
            if (c == '[') {
                result.push_back(c);
            } else if (c == ']') {
                string t;
                while (result.back() != '[') {
                    t.push_back(result.back());
                    result.pop_back();
                }
                result.pop_back();
                std::reverse(t.begin(), t.end());
                int n = 0;
                std::string t2;
                while (!result.empty() && result.back() <= '9') {
                    t2 += result.back();
                    result.pop_back();
                }
                std::reverse(t2.begin(), t2.end());
                n = std::stol(t2);
                for (int i = 0; i < n; ++i) {
                    result += t;
                }
            } else {
                result.push_back(c);
            }
        }
        return result;
    }
};
```

#### Language used for code
C++

#### Expected behavior
The code I submitted (and any code for this problem) should fail as it fails a valid test case but it succeeds.

**Comment by lc-kay** [comment]
@mihaild When I tried to reproduce this issue, I received an Invalid Testcase message when I ran your test case. Please provide a screenshot of the test console when you ran this test case.

**Comment by mihaild** [comment]
Looks like general check (https://leetcode.com/problems/decode-string/) reports Invalid Testcase if author's solution fails. In Monthly challenge it reports Runtime Error.
If we replace all the 300 in test with 3, it works. And length of s is 21, so this restriction isn't violated either.

![2020-11-19-235509_996x645_scrot](https://user-images.githubusercontent.com/815011/99723079-bd20d680-2ac2-11eb-9bc9-8acf21706e4f.png)

**Comment by lc-kay** [comment]
<img width="955" alt="Screen Shot 2020-11-23 at 1 58 29 P " src="https://user-images.githubusercontent.com/70870126/100020036-fcd21180-2d93-11eb-8e62-9b7f440513df.png">
@mihaild Please refer to the screenshot. The test case appears as invalid. If you are still seeing "Runtime Error", please let me know and I will relay it to our team to investigate.

**Comment by mihaild** [comment]
It indeed shows "Invalid Testcase" now. However, according to problem text, this testcase is valid.

**Comment by lc-kay** [comment]
Hi @mihaild 
I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@mihaild The test case is invalid because the output string of this test case has 10^10 length. That's why the validator didn't accept it. Thank you for your time!

**Comment by mihaild** [comment]
There is no constraint on output length in problem description. So, according to problem description, the test is valid.
