### ISSUE TITLE
1146. Snapshot Array : Wrong Solution, Missing Testcase

### ISSUE THREAD

**Issue by VIPverma01** [LeetCode-Feedback/LeetCode-Feedback#14034]
#### Your LeetCode username
VIPul1

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
In this question, I have a solution that is getting accepted on almost 3*10^9 iterations, taking nearly 3000 ms on the worst-case test case I've generated for this approach.

#### Code you used for Submit/Run operation
```
class SnapshotArray {
public:
    vector<map<int,int>> snaps;
    int curSnap;
    
    SnapshotArray(int length) {
        curSnap = 0;
        snaps = vector<map<int,int>>(length);
    }
    
    void set(int index, int val) {
        snaps[index][curSnap] = val;
    }
    
    int snap() {
        int temp = curSnap;
        curSnap++;
        return temp;
    }
    
    int get(int index, int snap_id) {
        int res = 0;
        for(auto it : snaps[index]){
            if(it.first>snap_id) break;
            res = it.second;
        }
        return res;
    }
};
```

#### Language used for code
C++

#### Expected behavior

This solution should not get passed on this test case so please add this test case for the given solution by me and handle the time to accept the solution.

Testcase file: [testcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/11714134/testcase.txt)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
