### ISSUE TITLE
Missing Test Case - 2731. Movement of Robots

### ISSUE THREAD

**Issue by bdpqchen** [LeetCode-Feedback/LeetCode-Feedback#14046]
#### Your LeetCode username

bdpqchen

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Under the problem constraints the test cast can be 
```  
[2000000000,0]
"RL"
1000000000
```
my code passed all of current test cases but failed with this test case with the error message 
> Line 6: Char 32: runtime error: signed integer overflow: 2000000000 + 1000000000 cannot be represented in type 'int' (solution.cpp)
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior prog_joined.cpp:15:32
#### Code you used for Submit/Run operation

```
class Solution {
public:
    int sumDistance(vector<int>& nums, string s, int d) {
        int n = nums.size(), mod = 1e9 + 7;    
        for (int i = 0; i < n; ++i) 
            nums[i] = nums[i] + d * (s[i] == 'R' ? 1 : -1);
        sort(nums.begin(), nums.end());
        long long ans = 0;
        for (int i = 0; i < n; ++i) {
            ans = (ans + (long long)nums[i] * (i - (n - i - 1))) % mod;
        }
        return ans;
    }
};
```

#### Language used for code

C++

**Comment by nipunarora098** [comment]
Yes, This testcase is missing in the contest.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

We don’t add integer overflow test cases.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
