### ISSUE TITLE
Ambiguous problem statement in https://leetcode.com/problems/find-k-closest-elements/

### ISSUE THREAD

**Issue by snehasishroy** [LeetCode-Feedback/LeetCode-Feedback#1404]
#### Your LeetCode username
chrisgriffin

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
https://leetcode.com/problems/find-k-closest-elements/ problem statement does not define anything about "closeness" of elements. Should the elements be close by indices or by diff to the target? This is not clarified in the problem statement.
Neither the provided examples clarify it.

Request the team to update the problem statement to clearly mention to find elements that have the smallest diff with the target are the closest.

**Comment by lc-kay** [comment]
Hi @snehasishroy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @snehasishroy 
Thank you for your time. Although we have not seen the same issue raised in discuss, we edited it a little bit to make it more clear.

**Comment by snehasishroy** [comment]
Hi @lc-kay Why was I not awarded 100 leetcoins for this valid contribution?

**Comment by lc-kay** [comment]
@snehasishroy Since it was not a major issue that has been raised in discuss or known to cause a huge issue when solving the problem, we team decided it did not qualify for the 100 LeetCoins rewards.
