### ISSUE TITLE
Missing test cases in https://leetcode.com/problems/find-k-closest-elements/submissions/

### ISSUE THREAD

**Issue by snehasishroy** [LeetCode-Feedback/LeetCode-Feedback#1405]
#### Your LeetCode username
chrisgriffin

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Currently there is a test case missing for cases like
[3,5,8,10]
2
15

#### Code you used for Submit/Run operation
I got AC with this solution https://leetcode.com/playground/YTy5QxCj
however my solution returns [3,5] whereas the expected output is [8,10]

#### Language used for code
Java

#### Expected behavior
Expected output of the test case is [8,10]

**Comment by lc-kay** [comment]
Hi @snehasishroy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @snehasishroy 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
