### ISSUE TITLE
Error - (21) Merge Two Sorted Lists

### ISSUE THREAD

**Issue by JenimDacket** [LeetCode-Feedback/LeetCode-Feedback#14058]
#### Your LeetCode username

JenimDacket

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ x] Language
- [ ] Missing Test Cases 

#### Description of the bug

The compiler throws an error on attempting to access the defined ListNode.val or ListNode.next values.  The values will still print to stdout, but I can't submit the solution I had created since the compilers deems the ListNode objects themselves as "undefined"

#### Code you used for Submit/Run operation

```
// Merge Two Sorted Lists
function mergeTwoLists(list1: ListNode | null, list2: ListNode | null): ListNode | null {
    console.log("list1: ", list1.val)
    console.log("list2: ", list2.val)

    return
};
```

#### Language used for code

Typescript

#### Expected behavior

Code would run, but test cases would fail

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/26157072/6354a322-3077-4c8e-9dee-97bc97ed9a1a)

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team

**Comment by JenimDacket** [comment]
You did not understand the assignment my guy.

The issue is not whether or not my code solved the problem.

I am well aware it did not solve the problem -- I was displaying that the
code is throwing an error it should not be throwing.  Please Review the
photo I provided. 🙏

Best regards,
Evan

LC_M ***@***.***> 於 2023年6月14日 週三 04:26 寫道：
