### ISSUE TITLE
Missing Test Case - 300. Longest Increasing Subsequence

### ISSUE THREAD

**Issue by aswin98855** [LeetCode-Feedback/LeetCode-Feedback#14059]
#### Category of the bug
- [300]Longest Increasing Subsequence
- [ ] Solution
- python
- nums=[]

#### Code you used for Submit/Run operation

```
// Longest Increasing Subsequence
class Solution(object):
    def lengthOfLIS(self, nums):
        n=len(nums)
        dp=[1]*n
        for i in range(1,n):
            for j in range(i):
                if nums[i]>nums[j]:
                    dp[i]=max(dp[i],dp[j]+1)
        return max(dp)
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by aswin98855** [comment]
Language used: python

Test case missed: nums=[ ] (empty list)

**Comment by aswin98855** [comment]
> Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
> 
> The language you submitted to reach this result.
> The missing test case.
> 
> We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

Language used: python
Test case missed: nums=[] (empty list)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
