### ISSUE TITLE
958. Check Completeness of a Binary Tree - Bug In editorial code

### ISSUE THREAD

**Issue by WagdySamih** [LeetCode-Feedback/LeetCode-Feedback#14053]
#### Your LeetCode username
WagdySamih

#### Category of the bug
- [x] Solution

#### Description of the bug
Useless guard if statement `if(root == nullptr)` in BFS Code section

#### Language used for code
C++, Java

#### Expected behavior
Remove the if statement, or modify the constraints to include 0 as the number of nodes

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/45714046/d9733af6-3714-4536-acb7-0fb848d30c42)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/45714046/6adcfdcf-506d-4eb7-be14-85c7846e7c09)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

This isn’t a bug - while it isn’t necessary to be accepted on LeetCode, it’s still not a bad thing to include when in an interview as it shows the interviewer you are cognizant of edge cases.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
