### ISSUE TITLE
Missing Test Case - 228. Summary Ranges

### ISSUE THREAD

**Issue by Abhaysingh291** [LeetCode-Feedback/LeetCode-Feedback#14055]
#### Your LeetCode username
https://leetcode.com/abhay_291/

#### Category of the bug
- [Summary Ranges ] Question
- [ c++] Language
- [ [-123612687,123612688]] Missing Test Cases 

#### Description of the bug

it giving wrong answer in the test case but it run and submit successfully

#### Code you used for Submit/Run operation
class Solution {
public:
    vector<string> summaryRanges(vector<int>& nums) {
        vector<string>ans;
        if(nums.size()==0) return ans;
        long long int a=0;
        for(int i=1;i<nums.size();i++){
            string temp="";
            if(abs(abs(nums[i])-abs(nums[i-1]))!=1){
                if(nums[a]==nums[i-1]){
                    temp+=to_string(nums[a]);
                }
                else temp+=to_string(nums[a])+"->"+to_string(nums[i-1]);
                ans.push_back(temp);
                a=i;
            }
        }

            string temp="";
            int i=nums.size();
            if(nums[a]==nums[i-1]){
                temp+=to_string(nums[a]);
            }
            else temp+=to_string(nums[a])+"->"+to_string(nums[i-1]);
            ans.push_back(temp);
        return ans;
    }
};

#### Expected behavior

The expected behavior's  that it should give the wrong answer while submitting
but in this test case it run and submit successfully

**Comment by Abhaysingh291** [comment]
Test case contribution

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
