### ISSUE TITLE
Oracle Runtime Issue - 595. Big Countries

### ISSUE THREAD

**Issue by skvirani** [LeetCode-Feedback/LeetCode-Feedback#14050]
#### Your LeetCode username
Rumnle

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Runtime Issue

#### Description of the bug

When running any code for Oracle language, ORA-00902: Invalid Datatype runtime error occurs. This error is common for creating or updating tables. This seems like an issue with Leetcode's setup of the Oracle runtime environment/db.

#### Code you used for Submit/Run operation

```
/* Write your PL/SQL query statement below */
select w.name, w.population, w.area
from world w
where w.area >= 3000000
or w.population >= 25000000
;
```

#### Language used for code

Oracle

#### Expected behavior

The snippet to run. It runs with MySql selected, not Oracle.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/22201043/d9500d6e-e098-4749-bb47-3358225efe12)

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
