### ISSUE TITLE
2732. Find a Good Subset of the Matrix

### ISSUE THREAD

**Issue by raghav-03** [LeetCode-Feedback/LeetCode-Feedback#14061]
#### Your LeetCode username
agarwalraghav

#### Category of the bug
- [ ] Missing Test Cases 

#### Question Tittle
2732. Find a Good Subset of the Matrix
https://leetcode.com/problems/find-a-good-subset-of-the-matrix/

#### Description of the bug
On this question the code which is getting accepted is running on time complexity higher than acceptable range. This Happened during the live contest which ruins rank for many users

#### Code you used for Submit/Run operation
```
class Solution {
public:
     long long solve(vector<int>& row1,vector<int>& row2) {
        int sum=0;
        for (int i = 0;i<row1.size(); i++) 
            sum+= row1[i] && row2[i];
        
        return sum;
    }
    vector<int> goodSubsetofBinaryMatrix(vector<vector<int>>& grid) {
        long long n=grid.size(),m=grid[0].size();
        for (int i = 0;i<n; i++){    
            long long sum=0;
            for(long long j=0;j<m;j++)
                sum+=grid[i][j];
            if(!sum) return {i};
        }       
        for (int i = 0;i<n;i++) 
            for (int j=i+1;j<n;j++) 
                if (!solve(grid[i],grid[j])) 
                    return {i,j};
        return {};
    }
}; 
```

#### Language used for code
C++

#### Expected behavior
The Code should give TLE but it is getting accepting

#### Accepted Solution
https://leetcode.com/submissions/detail/969397815/

### Test Case File
[Test Case File 2732. Find a Good Subset of the Matrix.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/11719435/Test.Case.File.2732.Find.a.Good.Subset.of.the.Matrix.txt)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
