### ISSUE TITLE
1029. Two City Scheduling

### ISSUE THREAD

**Issue by Jasper-Joe** [LeetCode-Feedback/LeetCode-Feedback#1406]
User Name : jasperjoe

Test cases

Test cases are not comprehensive, my code passed all the test cases provided but failed on my own test case. 
Like this: [[10,10],[30,30],[400,400],[30,30]]

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int twoCitySchedCost(vector<vector<int>>& costs) {
        auto comp = [&](vector<int>& a, vector<int>& b) {
            int diffA = abs(a[0] - a[1]);
            int diffB = abs(b[0] - b[1]);
            if(diffA >= diffB) {
                return true;
            }
            return false;
        };

        sort(costs.begin(),costs.end(), comp);
        int countA = 0;
        int countB = 0;
        int half = costs.size() / 2;
        int ans = 0;
        for(int i=0;i<costs.size();i++) {
            if(countA < half && costs[i][0] < costs[i][1]) {
                countA++;
                ans += costs[i][0];
            } else if (countB < half && costs[i][1] < costs[i][0]) {
                countB++;
                ans += costs[i][1];
            } else if (countA == half) {
                countB++;
                ans += costs[i][1];
            } else if (countB == half) {
                countA++;
                ans += costs[i][0];
            }
        }
        return ans;
        
    }
};
```

C++

#### Expected behavior

For test case: [[10,10],[30,30],[400,400],[30,30]], expected answer is 470, but my code that gets accepted returns 0.

**Comment by lc-kay** [comment]
Hi @Jasper-Joe 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Jasper-Joe 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
