### ISSUE TITLE
488. Zuma Game | Test Case: board = "RRYGGYYRRYYGGYRR" & hand = "GGBBB" | expected answer being 5 currently.

### ISSUE THREAD

**Issue by youzhou19858** [LeetCode-Feedback/LeetCode-Feedback#14060]
#### Your LeetCode username

ZKC1991

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Test Case (board = "RRYGGYYRRYYGGYRR" & hand = "GGBBB") is expecting 5 currently. But the real answer should be 2 as we can insert G at position 5 and cross out "RRYGGYYR" and then another one to the remaining "RYYGGYRR" to achieve a minSteps 2.

#### Code you used for Submit/Run operation

```
class Solution {
    int minCnt = INT_MAX;
    template<typename It>
    void dfs(string st, It beg, It end, unordered_map<char, int>& cards, int cnt = 0) {
        while (beg != end && cnt < this->minCnt) {
            if (st.size() < 2 || st.back() != *(st.rbegin() + 1)) {
                st.push_back(*beg++);
            } else {
                if (st.back() == *beg) {
                    this->dfs(string(st.begin(), st.end() - 2), ++beg, end, cards, cnt);
                    for (; beg != end && st.back() == *beg; ++beg);
                    st.erase(st.size() - 2);
                } else {
                    if (cards[st.back()]) {
                        --cards[st.back()];
                        this->dfs(string(st.begin(), st.end() - 2), beg, end, cards, cnt + 1);
                        ++cards[st.back()];
                    }
                    st.push_back(*beg++);
                }
            }
        }
        if (st.size() == 1) {
            this->minCnt = min(this->minCnt, cnt);
        } else {
            for (auto it = st.begin(); it != st.end(); ++it) {
                if (cards[*it] >= 2) {
                    cards[*it] -= 2;
                    string str = string(st.begin(), it) + string(it + 1, st.end());
                    this->dfs("", str.begin(), str.end(), cards, cnt + 2);
                    cards[*it] += 2;
                }
            }
        }
    }
public:
    int findMinStep(string board, string hand) {
        board.push_back('$');
        unordered_map<char, int> cards {};
        for (char ch: hand) {
            ++cards[ch];
        }
        this->dfs("", board.begin(), board.end(), cards);
        return this->minCnt == INT_MAX ? -1 : this->minCnt;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The real answer should be 2 as we can insert G at position 5 and cross out "RRYGGYYR" and then another one to the remaining "RYYGGYRR" to achieve a minSteps 2.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/135424132/dc2e347e-2f87-4942-b725-5c8ff04f4a3d)

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
