### ISSUE TITLE
1207. Unique Number of Occurrences

### ISSUE THREAD

**Issue by AbhigyanBafna** [LeetCode-Feedback/LeetCode-Feedback#14068]
#### Your LeetCode username

abhigyanbafna

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The test-case `[1, 2, 2, 10]` is missing.
Clearly the numbers 1 and 10 have the same occurrences but the code below is yet accepted.

#### Code you used for Submit/Run operation

```
//Unique occurances
class Solution {
public:
   bool uniqueOccurrences(vector<int> &arr)
    {
        if(arr.size() == 2){
            if(arr[0] == arr[1]) return true;
            else return false;
        }
        sort(arr.begin(), arr.end()); 
        int count = 1;
        vector<int> arr2;
        for (int i = 0; i < arr.size() - 1; i++)
        {
            if (arr[i] == arr[i + 1])
            {
                count++;
            }
            else
            {
                arr2.push_back(count);
                count = 1;
            }
        }
        sort(arr2.begin(), arr2.end()); 
        for (int i = 1; i < arr2.size(); i++)
        {
            if (arr2[i] == arr2[i - 1])
            {
                return false;
            }
        }
        return true;
    }

};
```

#### Expected behavior

The above code should be rejected as 1 and 10 have the same no of occurances.

#### Screenshots

<img width="1440" alt="Screenshot 2023-06-12 at 4 45 36 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/101444239/1e170097-e152-42b6-81df-07a7d9b1993b">

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
