### ISSUE TITLE
Indexing Error- 2736. Maximum Sum Queries

### ISSUE THREAD

**Issue by vaibhav-shaw** [LeetCode-Feedback/LeetCode-Feedback#14074]
#### Your LeetCode username

Tense_Nomad

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
Indexing error in queries array.

#### Description of the bug

It is mentioned to be 1-Indexed 2D array, with further:
xi == queries[i][1]
yi == queries[i][2]
but in the program it is actually 0 indexed.

#### Code you used for Submit/Run operation

```
// Maximum Sum Queries
class Solution {
public:
    vector<int> maximumSumQueries(vector<int>& nums1, vector<int>& nums2, vector<vector<int>>& queries) {
        vector<pair<int,int>> arr;
        vector<int> ans;
        for(int i=0;i<nums1.size();i++){
            arr.push_back({nums1[i]+nums2[i],i});
        }
        sort(arr.rbegin(),arr.rend());
        for(int i=0;i<queries.size();i++){
            int c=0;
            while(c<arr.size() && (nums1[arr[c].second]<queries[i][0] || nums2[arr[c].second]<queries[i][1])){
                c++;
            }
            if(c==nums1.size()) ans.push_back(-1);
            else
                ans.push_back(nums1[arr[c].second]+nums2[arr[c].second]);
        }
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

It would be better to make the "queries" array 1D. With:
xi == queries[i][0]
yi == queries[i][1]

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
