### ISSUE TITLE
Missing Test Case - 1054. Distant Barcodes

### ISSUE THREAD

**Issue by Tushar257** [LeetCode-Feedback/LeetCode-Feedback#1407]
The test case is accepted whereas it should not be accepted. Also the questions definition expects the answer should be no adjacent barcodes should be similar, so the console expects the same array for the solution i.e. [1,1,1] . This particular test case should not be accepted. Also my solution has been accepted by the leetcode and this test case is what should be restricted.

#### Code you used for Submit/Run operation

```
class Solution(object):
    def rearrangeBarcodes(self, barcodes):
        """
        :type barcodes: List[int]
        :rtype: List[int]
        """
        count = collections.Counter(barcodes)
        pq = []
        for key, val in count.items():
            pq.append([-val, key])
        heapq.heapify(pq)
        ans = []
        while len(pq) >= 2:
            number1, k1 = heapq.heappop(pq)
            number2, k2 = heapq.heappop(pq)
            ans.append(k1)
            ans.append(k2)
            number1 += 1
            number2 += 1
            if number1:
                heapq.heappush(pq, [number1, k1])
            if number2:
                heapq.heappush(pq, [number2, k2])
        if pq:
            ans.append(pq[0][1])
        return ans
```

#### Language used for code
Python

#### Expected behavior

Expected behavior is that this particular test case should be restricted in questions like these. But instead, the test case was accepted and proved that the code that has just been accepted by leetcode itself is incorrect.

#### Screenshots

![Screenshot (54)](https://user-images.githubusercontent.com/31645535/99782574-5a215500-2b3f-11eb-9f1a-2dc1f8d399bb.png)

**Comment by lc-kay** [comment]
Hi @Tushar257 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Tushar257 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
