### ISSUE TITLE
Missing Test Case - 2352. Equal Row and Column Pairs

### ISSUE THREAD

**Issue by this-user-has-no-username** [LeetCode-Feedback/LeetCode-Feedback#14077]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

For the following testcase, the sample 4ms submission in rust outputs 4 incorrectly due to a hash collision.

[[1,1,14103,51308],[1,2,1,1],[1,1,1,1],[1,1,1,1]]

#### Code you used for Submit/Run operation

```
// Sample 4 ms submission
impl Solution {
    pub fn equal_pairs(grid: Vec<Vec<i32>>) -> i32 {
        
        let n = grid.len();
        let mut row = vec![0; n];
        let mut col = vec![0; n];
        for i in 0..n {
            for j in 0..n {
                row[i] = row[i] * 100_001 + grid[i][j];
                col[j] = col[j] * 100_001 + grid[i][j];
            }
        }
        let mut res = 0;
        for i in 0..n {
            for j in 0..n {
                if row[i] == col[j] {
                    res += 1;
                }
            }
        }
        res
    }
}
```

#### Language used for code

Rust

#### Expected behavior

Output 3 for the testcase

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/136400388/ee24e358-e4cb-4614-b868-79f856acc499)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've used your feedback to update the problem.

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback.

Please provide us your Leetcode account username.

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
