### ISSUE TITLE
Missing Test Case - 2352. Equal Row and Column Pairs

### ISSUE THREAD

**Issue by rainqin** [LeetCode-Feedback/LeetCode-Feedback#14081]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The test case doesn't cover a wrong submission for question: 2352. Equal Row and Column Pairs
I see some submissions are using a 10 based multiply to calculate the sum of each row and column.
This shouldn't work since 1 <= grid[i][j] <= 10^5. It needs a 10^5 based multiply to calculate something like a check sum.
A simple test case can be: [[1,1,1],[2,10,100],[1,200,1]]. The result from the test is 0, which is right. But if using the 10 based multiply in the submissions, it returns 1, which is wrong.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    public int equalPairs(int[][] grid) {
        int count = 0;
        int len = grid.length;
        for (int r = 0; r < len; r++) {
            for (int c = 0; c < len; c++) {
                boolean match = true;
                for (int i = 0; i < len; i++) {
                    if (grid[r][i] != grid[i][c]) {
                        match = false;
                        break;
                    }
                }
                if (match) count++;
            }
        }
        return count;
    }
}
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've used your feedback to update the problem.

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback.

Please provide us your Leetcode account username.

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
