### ISSUE TITLE
Missing Test Case - 39. Combination Sum

### ISSUE THREAD

**Issue by gopi4057** [LeetCode-Feedback/LeetCode-Feedback#14084]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ candidates=[2,-1,3,-2] 
target=5] Missing Test Cases 

#### Description of the bug

in this test case my code should fail but my code passing all testcases given by u
candidates=[2,-1,3,-2] 
target=5

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    void comb(vector<int> & arr, int n, int k,vector<vector<int>> &ans,int index,int sum,vector<int> ds)
 {
     if(sum==k)
     {
         ans.push_back(ds);
         return ;
     }
     if(sum>k)
     {
         return ;
     }
     if(index>=n)
     {
         return ;

     }
     
    
    ds.push_back(arr[index]);
    comb(arr,n,k,ans,index,sum+arr[index],ds);
    ds.pop_back();
    comb(arr,n,k,ans,index+1,sum,ds);

     return;

 }
    vector<vector<int>> combinationSum(vector<int>& arr, int target) {
        int n=arr.size();
        sort(arr.begin(),arr.end());
         vector<vector<int>> ans;
        vector<int> ds;
        comb(arr,n,target,ans,0,0,ds);
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

According to the question my code will fail if there is any negative integers in the array but my code passed all test cases

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

[2,-1,3,-2]
5
received invalid test case

'candidates' must consist of values from 2 to 40 only

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
