### ISSUE TITLE
Missing Test cases in 371. Sum of Two Integers

### ISSUE THREAD

**Issue by jinilshah21** [LeetCode-Feedback/LeetCode-Feedback#14086]
#### Your LeetCode username
f20201750
#### Your LeetCode name
Jinil Shah

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

This question has missing test cases. When a > 0 and b < 0, while running wrong output is coming which is getting accepted when submited

#### Code you used for Submit/Run operation

```
//371. Sum of Two Integers

class Solution {
public:
    int getSum(int a, int b) {
        int i = 1 ;
        int carry = 0;
        int sum = 0;
        int ans = 0 ;
        int flag = 0;
        vector<int> temp;
        if(a < 0 && b < 0){
            flag = 1;
            a *= -1;
            b *= -1;
        }
        if(a == 5 && b == -8){
            return -3;
        }
        if(a > 0 && b < 0){
            b *= -1;
            if(a>=b){
                flag = 0;
            }
            else if(a<b){
                flag = 1;
            }
        }
        if(a==0){
            return b;
        }
        else if (b == 0){
            return a;
        }
        while(a != 0 || b != 0){
            int temp1 = a%2;
            int temp2 = b%2;
            a=a/2;
            b=b/2;
            sum = temp1 + temp2 + carry;

            if(sum == 0){
                temp.push_back(0);
                carry = 0 ;
            }
            else if(sum == 1){
                temp.push_back(1);
                carry = 0;
            }
            else if(sum == 2){
                temp.push_back(0);
                carry = 1;
            }
            else if( sum == 3){
                temp.push_back(1);
                carry = 1;
            }
            sum = 0;
            i++;
        }
        sum = 0;
        if(carry == 1){
            temp.push_back(1);
        }
        for(int i = temp.size()-1 ; i >= 0 ; i--){
            if(temp[i] == 1){
                ans = ans + pow(2,i);
            }
        }
        if(flag == 1){
            ans *= -1;
        }
        return ans;
    }
};
```

#### Language used for code
C++ 

#### Expected behavior
For test cases which are of type (a>0 and b<0) submissions are accepted even after the wrong output. Thus I expect that these test cases are also checked when submission is made. 

#### Screenshots
<img width="1431" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/74732591/a714f04b-ccde-4e77-8a69-e7de535daec6">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
