### ISSUE TITLE
Problem 2723: Incorrect Article

### ISSUE THREAD

**Issue by agrawalishaan** [LeetCode-Feedback/LeetCode-Feedback#14082]
#### Your LeetCode username
iarocks

#### Category of the bug
- [ ] Question
- [ X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the problem 2723, add two promises: https://leetcode.com/problems/add-two-promises/description/

When using a chained `.then` solution:

```
var addTwoPromises = async function(promise1, promise2) {
  try {
    return promise1.then((val) => promise2.then((val2) => val + val2))
  } catch (error) {
    console.error(error);
    throw error; // Rethrow the error to maintain the behavior of propagating the error to the caller
  }
};
```

The author writes that the time complexity is `O(promise1 + promise2)`. This is wrong. Like the prior solutions, the time complexity is still `O(max(promise1, promise2))`. In fact, the `.then` solution is functionally the same as the `await` solution, just without the syntactic sugar, so the complexities cannot be difficult. This is a bit misleading as it implies there are performance differences when using `.then` vs. `await`.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
