### ISSUE TITLE
Missing Test Case - 2352. Equal Row and Column Pairs

### ISSUE THREAD

**Issue by Savneet4** [LeetCode-Feedback/LeetCode-Feedback#14088]
#### Your LeetCode username

Savneet04

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [+] Missing Test Cases 
Missing Test Case

#### Description of the bug

Incorrect solution passed all given  test cases.

#### Code you used for Submit/Run operation

```
//Equal Row and Column Pairs
class Solution {
public:
    int equalPairs(vector<vector<int>>& grid) {
        int n=grid.size();
        int dp[n][n];
        int res=0;
        map<string,int> row;
        for(int i=0;i<n;i++){
            string temp="";
            for(int j=0;j<n;j++){
                temp+=(grid[i][j]%255);
                temp+='|';
            }
            //cout<<temp<<endl;
            row[temp]++;
        }cout<<endl;
        for(int i=0;i<n;i++){
            string temp="";
            for(int j=0;j<n;j++){
                temp+=(grid[j][i]%255);
                temp+='|';
            }
            if(row[temp]){
                res+=row[temp];
            }
            //cout<<temp<<endl;
        }
        return res;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The code should have failed some testcase but it got accepted instead.
for ex: It cannot pass this test case:
Input : [[3,257,1],[1,7,6],[2,7,7]]
Expected Output: 0
Received Output  : 1

#### Screenshots

![Screenshot (183)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/121486345/988b7aad-b724-41b9-8b6a-df0a616eda89)
![Screenshot (184)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/121486345/71808aeb-4566-45f7-afc3-26191c2a2487)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
