### ISSUE TITLE
Missing Test Case - 2731. Movement of Robots

### ISSUE THREAD

**Issue by mudrax** [LeetCode-Feedback/LeetCode-Feedback#14092]
#### Your LeetCode username
 mudraxdagar10

#### Category of the bug : Language
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
 In example 1 there is a slight misprint which could lead to problem in understanding 
``` 
The distance between the robot at index 0 and 1 is abs(-1 - 1) = 2. should be changed to The distance between the robot at index 1 and 2 is abs(-1 - 1) = 2.
```

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
