### ISSUE TITLE
Missing Test Case - 55. Jump Game

### ISSUE THREAD

**Issue by amangupta590** [LeetCode-Feedback/LeetCode-Feedback#1409]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
return true;

    }
};
```

**Comment by lc-kay** [comment]
@amangupta590 To further look into this issue, please provide the missing test case.

**Comment by lc-kay** [comment]
Hi @amangupta590  ,
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
