### ISSUE TITLE
Missing Test Case - 219. Contains Duplicate II

### ISSUE THREAD

**Issue by zabuli** [LeetCode-Feedback/LeetCode-Feedback#14099]
#### Your LeetCode username

zabuli

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

It is possible to get **Accepted** Submission of _Contains Duplicate II_ problem with this test case: _nums = [84,84], k = 0_

#### Code you used for Submit/Run operation

```
// Contains Duplicate II
public class Solution {
    public bool ContainsNearbyDuplicate(int[] nums, int k) {
        if (nums.Length == 2)
        {
            return nums[0] == nums[1];
        }

        int j;
        for (var i = 0; i < nums.Length; i++)
        {
            j = i + 1;
            while(j <nums.Length && j <= i + k)
            {
                if (nums[i] == nums[j])
                {
                    return true;
                }
                j++;
            }
        }

        return false;
    }
}
```

#### Language used for code

C#

#### Expected behavior

With my solution provided here, I should get **Wrong answer** instead of **Accepted** status.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/131911322/a4a5b5b1-5c3f-4949-997c-f31c80efae97)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
