### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by ManojNayak2612** [LeetCode-Feedback/LeetCode-Feedback#14095]
#### Username
ManojNayak2612

#### Category of the bug
- Two Sum
- nums[j] = target - nums[i]
- C++ 

#### Description of the bug

we can use nums[j] = target - nums[i]

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int>& nums, int target) {
        int i;
        for(i=0 ; i <nums.size() ; i++)
        {
            for (int j=i+1 ; j < nums.size() ;j++)
            {
                if (nums[j] == target - nums[i] )
                    return {i,j};
                else
                    break;
            }
        }
        return {};
    }
};
```

#### Language used for code
C++

#### Expected behavior

It should return a array

#### Additional context

Written in C++

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've submitted the feedback to the team.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
