### ISSUE TITLE
2700. 两个对象之间的差异 缺少测试用例

### ISSUE THREAD

**Issue by blankwsh** [LeetCode-Feedback/LeetCode-Feedback#14109]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
blank_goh

**Bug 类型**
- [ ] 缺少测试用例

**描述**
缺少测试用例：{},[]

**你使用的语言**
JavaScript

**你提交或者运行的代码**
```
/**
 * @param {object} obj1
 * @param {object} obj2
 * @return {object}
 */
function objDiff(obj1, obj2) {
    let key1 = Object.keys(obj1)
    let key2 = Object.keys(obj2)
    let inter = {}
    for (let key of key1) {
        // if (Object.prototype.toString.call(obj1[key]) !== Object.prototype.toString.call(obj2[key]) && key2.includes(key)) inter[key] = [obj1[key], obj2[key]]
         if (typeof obj1[key] === 'object' && obj1[key] !== null && typeof obj2[key] === 'object' && obj2[key] !== null && Object.prototype.toString.call(obj1[key]) === Object.prototype.toString.call(obj2[key])) {
            let res = objDiff(obj1[key], obj2[key])
            if (Object.keys(res).length) inter[key] = res
        }
        else if (key2.includes(key)) {
            if (obj1[key] !== obj2[key]) {
                inter[key] = [obj1[key], obj2[key]]
            }
        }
    }
    return inter
};
```

**期望行为**
应该返回[[],{}]而不是{}，但程序通过了

**屏幕截图**
<img width="278" alt="截屏2023-06-14 17 06 09" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/83573730/b84b4ad3-78e2-40fe-8bb4-ddd4db615476">

**额外的上下文**

**Comment by feiceh** [comment]
你好，blank_goh未核实到相关ID。当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励哦。

**Comment by blankwsh** [comment]
leetcode.cn/u/prWp4QMZkZ/



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: feiceh ***@***.***&gt;
发送时间: 2023年6月25日 11:49
收件人: LeetCode-Feedback/LeetCode-Feedback ***@***.***&gt;
抄送: blankwsh ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [LeetCode-Feedback/LeetCode-Feedback] 2700. 两个对象之间的差异 缺少测试用例 (Issue #14109)





 
你好，blank_goh未核实到相关ID。当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励哦。

**Comment by feiceh** [comment]
收到，奖励已发放。
