### ISSUE TITLE
Missing Test Case - 530. Minimum Absolute Difference in BST

### ISSUE THREAD

**Issue by Ani1952** [LeetCode-Feedback/LeetCode-Feedback#14105]
#### Category of the bug
- [ ] Solution

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    public int getMinimumDifference(TreeNode root) {
        return trav(root, null, Integer.MAX_VALUE);
    }
    public int trav(TreeNode node,Integer prev, int minDiff){
        if(node==null)
            return minDiff;
        
        minDiff= trav(node.left,prev,minDiff);

        if(prev!=null)
            minDiff=(minDiff==Integer.MAX_VALUE)?node.val-prev:Math.min(minDiff,node.val-prev);

        prev=node.val;

        return trav(node.right,prev,minDiff);
    }
}
```

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/90521280/b0d1376e-44b3-4f31-aad2-8bb68711e999)

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
