### ISSUE TITLE
Missing Test Case - 1048. Longest String Chain 

### ISSUE THREAD

**Issue by aTan-aka-Xellos** [LeetCode-Feedback/LeetCode-Feedback#1410]
#### Your LeetCode username
Xellos

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
My code got accepted despite containing a bug.
The problem should have a test case that covers a case when 2 words have a difference between letters equal one, but without respect to the order of the letters.

##### Proposed test cases:
```
["a", "b", "ab", "bac"]
["abcd","dbqca"]
```

With the current test coverage following approach is possible:
To define if word A is the predecessor of word B, count similar letters in each word and count if the total difference equals one.
For the words "ab" and "bac" the difference will be 1 (letter c), but the letters 'a' and 'b' are in the incorrect order.

#### Code you used for Submit/Run operation

```
// 1048. Longest String Chain 
class Solution {
    public int longestStrChain(String[] words) {
        int max = 0;
        int[] dp = new int[words.length + 1];
        Arrays.sort(words, (a,b) -> a.length() - b.length());
        
        for (int i = 1; i < dp.length; i ++) {
            for (int j = i - 1; j > 0 && words[i - 1].length() - words[j - 1].length() < 2; j--) {
                if (!isPredecessor(words[i - 1], words[j - 1])) continue;
                dp[i] = Math.max(dp[i], dp[j] + 1);
            }
            max = Math.max(max, dp[i]);
        }
        return max + 1;
    }
    
    // this method counts the difference between words, 
    // but it doesn't respect the order of the characters in it
    // while according to the problem requirements it should 
    boolean isPredecessor(String w1, String w2) {
        int[] a1 = new int[26];
        int[] a2 = new int[26];
        
        for (char c: w1.toCharArray()) a1[c - 'a']++;
        for (char c: w2.toCharArray()) a2[c - 'a']++;
        
        int diff = 0;
        for (int i = 0; i < a1.length; i++) {
            diff += Math.abs(a1[i] - a2[i]);
        }
        
        return diff == 1;
    }
}
```

#### Language used for code
Java

#### Expected behavior
For the given test cases:
["a", "b", "ab", "bac"]
["abcd","dbqca"]
Expected output:
2
1

The solution above was accepted but returns 3, 2 respectively for those TCs. 
It happens because the solution doesn't respect the order of the letters in the words when compare them.

#### Screenshots

![Screen Shot 2020-11-20 at 23 40 10](https://user-images.githubusercontent.com/7886823/99812390-bf9a3380-2b89-11eb-8e74-5609c3b11c87.jpg)

**Comment by lc-kay** [comment]
Hi @aTan-aka-Xellos 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @aTan-aka-Xellos 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
