### ISSUE TITLE
1396. 设计地铁系统 用例不合理

### ISSUE THREAD

**Issue by lt1552271019** [LeetCode-Feedback/LeetCode-Feedback#14107]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
lt1552271019

**Bug 类型**
- [ ] 题目
- [ √] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
用例56不合理

**你使用的语言**
pyhton

**你提交或者运行的代码**
```
pass
```

**期望行为**
不应但出现该用例

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**

用例56：
["UndergroundSystem","checkIn","checkIn","checkOut","getAverageTime","checkOut","getAverageTime"] [[],[45,"Leyton",3],[45,"Leyton",4], [45,"Waterloo",15],["Leyton","Waterloo"],[45,"Waterloo",18],["Leyton","Waterloo"]]
预期输出
[null,null,null,null,11.00000,null,12.50000]

45号未出站就再次进站。而且答案中的11和12.5无法合理计算。
若认为第一次出站的15对应入站时间为3，则应分别输出15 - 3 = 12 以及((15 - 3) + (18 - 4)) / 2 = 13
若认为第一次出站的15对应入站时间为4，则应分别输出15 - 4 = 11 以及((15 - 4) + (18 - 3)) / 2 = 13
无法合理得到11/12.5的输出
猜测12.5的输出是认为第一次出站的15对应入站时间为4，且第二次出站时间对应入站时间也为4，得到15 - 4 = 11 以及((15 - 4) + (18 - 4)) / 2 = 12.5，不合理。

**Comment by feiceh** [comment]
感谢反馈，当前题目已更新，奖励已发放。
