### ISSUE TITLE
Editorial- 530. Minimum Absolute Difference in BST

### ISSUE THREAD

**Issue by RohitSgh** [LeetCode-Feedback/LeetCode-Feedback#14101]
#### Your LeetCode username

RohitSgh

#### Category of the bug
- [ ] Question
- [x] Editorial
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Python3 code given in Approach-3 of [Editorial](https://leetcode.com/problems/minimum-absolute-difference-in-bst/editorial/) is giving Wrong Answer.

#### Code you used for Submit/Run operation

```Python3
class Solution:
    def getMinimumDifference(self, root: Optional[TreeNode]) -> int:
        self.minDistance = 1e9
        # Initially, it will be null.
        self.prevNode = None

        def inorder(node):
            if node is None:
                return
            inorder(node.left)
            # Find the difference with the previous value if it is there.
            if self.prevNode is not None:
                self.minDistance = min(self.minDistance, node.val - self.prevNode)
            self.prevNode = node.val
            inorder(node.right)

        inorder(root)
        return self.minDistance
```

#### Language used for code

Python3

#### Expected Behavior

Correct Code is
```python3
class Solution:
    def getMinimumDifference(self, root: Optional[TreeNode]) -> int:
        self.minDistance = 1e9
        # Initially, it will be null.
        self.prevNode = None

        def inorder(node):
            if node is None:
                return
            inorder(node.left)
            # Find the difference with the previous value if it is there.
            if self.prevNode:
                self.minDistance = min(self.minDistance, node.val - self.prevNode.val)
            self.prevNode = node
            inorder(node.right)

        inorder(root)
        return self.minDistance
```

#### Screenshots

 
Wrong Answer for Code given in Editorial

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/81853910/cbdb6763-dfcd-479f-95c2-623a7f575880)

**Comment by nskybytskyi** [comment]
Hi there,

Thank you for reaching out to us.

- When I submit the editorial code it gets [accepted](https://leetcode.com/problems/minimum-absolute-difference-in-bst/submissions/970829263/).
- Your screenshot contains your code, not the one from the editorial.
- Your code is wrong because it does not process `node.val = 0` properly.

Thank you for your support.

**Comment by RohitSgh** [comment]
True. Thanks for the reply @nskybytskyi. Closing Issue.
