### ISSUE TITLE
Missing Test Case - 334. Increasing Triplet Subsequence

### ISSUE THREAD

**Issue by AleksandrNi** [LeetCode-Feedback/LeetCode-Feedback#14108]
#### Your LeetCode username
user4708xh

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

According to requirements
"Given an integer array nums, return true if there exists a triple of indices (i, j, k) such that i < j < k and nums[i] < nums[j] < nums[k]. If no such indices exists, return false."

two conditions:
1. "i < j < k"
2. nums[i] < nums[j] < nums[k]

for example: 
[3, 1, 2, 0, 3]

According to accepted solution
result will be:
min value  = 0;
mid value  = 2;
max value = 3;

but its not correct, because of first condition not solved;
value 0 - its 3 index
value 2 - its 2 index
value  3 - its 4 index;

so if you change return type of 'increasingTriplet' method from boolean to array of indexes (low, mid , high) - you ll see the problem 

correct answer but not correct solution

#### Code you used for Submit/Run operation

```
// Increasing Triplet Subsequence

class Solution {
    public boolean increasingTriplet(int[] nums) {
        int i = Integer.MAX_VALUE;
        int j = Integer.MAX_VALUE;
        for(int k: nums) {
            if(k < i) {
                i = k;
            } else if(k < j && k > i) {
                j = k;
            } else if(k > j && j > i) {
                return true;
            }
        }
        return false;
    }
}
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

As a online judge, we only check for the final answer.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
