### ISSUE TITLE
题目 今天的每日一题 1375. 二进制字符串前缀一致的次数

### ISSUE THREAD

**Issue by hummingg** [LeetCode-Feedback/LeetCode-Feedback#14102]
**你的 LeetCode 用户名**
hummingg

**Bug 类型**
- [x] 题目

**描述**
> 给你一个下标从 1 开始的整数数组 flips ，其中 flips[i] 表示对应下标 i 的位将会在第 i 步翻转。

**期望行为**
> 对应下标 i 的位

改成

> 对应下标 flips[i] 的位

**额外的上下文**
[题目](https://leetcode.cn/problems/number-of-times-binary-string-is-prefix-aligned/)

**Comment by feiceh** [comment]
你好，在与相关团队核实后：当前描述没有问题暂不处理，本次 Ticket 将关闭，感谢您的反馈和支持。
