### ISSUE TITLE
Missing Test Case - 958. Check Completeness of a Binary Tree

### ISSUE THREAD

**Issue by abhi007tyagi** [LeetCode-Feedback/LeetCode-Feedback#1411]
#### Your LeetCode username
tyagiabhinav

#### Category of the bug
- [ ] Question
- [*] Solution
- [ ] Language

#### Description of the bug
Missing Test Case

#### Code you used for Submit/Run operation
```
if(root == null)
            return false;
        
        Queue<TreeNode> q = new LinkedList<>();
        q.add(root);
        while(!q.isEmpty()){
            int size = q.size();
            for(int i=0; i<size; i++){
                TreeNode t = q.poll();
                if(t == null && q.peek() != null){
                    return false;
                }
                if(t != null){
                    q.add(t.left);
                    q.add(t.right);
                }
            }
        }
        return true;
```

#### Language used for code
Java

#### Expected behaviour
Expected: On submit, I should have received the Wrong Answer but my solution was accepted!
Add check for root = null
Test case = [ ]

#### Additional context
Test Case [ ] missing

**Comment by zerotrac** [comment]
The tree will have between 1 and 100 nodes.

**Comment by abhi007tyagi** [comment]
@zerotrac then it should have said wrong test case!

**Comment by zerotrac** [comment]
AFAIK LeetCode does not have a testcase checker now.

**Comment by lc-kay** [comment]
Hi @abhi007tyagi 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @abhi007tyagi 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
