### ISSUE TITLE
Missing Test Case - 1848. Minimum Distance to the Target Element

### ISSUE THREAD

**Issue by LukaszJanisiow** [LeetCode-Feedback/LeetCode-Feedback#14110]
#### Your LeetCode username
LukaszJanisiow

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

There is no test case if there are 2 targets and abs(i - start) is lower for the second target.

#### Code you used for Submit/Run operation

Wrong code that passes all test cases
```
class Solution:
  def getMinDistance(self, nums: List[int], target: int, start: int) -> int:
      min = 10**4
      for i, num in enumerate(nums):
          if(nums[i] == target):
              min = abs(i - start)
              break;
      return(min)
```

#### Expected behavior

This code pass all test cases but is's wrong. For nums = [5,2,3,4,5] the output is 3. It should be 1.

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
