### ISSUE TITLE
Invalid Test Case Output - 842. Split Array into Fibonacci Sequence

### ISSUE THREAD

**Issue by kaushlendrapal** [LeetCode-Feedback/LeetCode-Feedback#14112]
#### Category of the bug
- [x] Invalid Test Cases 

#### Description of the bug
My output is valid but not matching with leet code Expected output

#### Code you used for Submit/Run operation

```
lass Solution {
    func splitIntoFibonacci(_ num: String) -> [Int] {
        guard num.count > 2 else { return [] }
        var nums = Array(num)
        var result:[Double] = []
        backTrack(nums, result: &result, start:0)
        if result.count >= 2 {
            return result.map { Int($0) }
        } else {
            return []
        }
    }

    func backTrack(_ nums: [Character], result: inout [Double], start: Int) -> Bool {
        if nums.count == start {
            return result.count > 2
        }
        var number: Double = 0.0
        for i in stride(from: start, to: nums.count, by: 1) {

            number = (number * 10.0) + Double(nums[i].wholeNumberValue!)
            if number < 0.0 { return false }
            if number >= Double(Int.max) { return false }
            var rCount = result.count
            if (rCount < 2) || (number == result[rCount-1] + result[rCount-2]) {
                result.append(number)
                // print("number: \(number), count: \(result.count) ")
                if backTrack(nums, result: &result, start: i+1) { return true }
                result.removeLast()
            }
            // Skip case
            if i == start && nums[i].wholeNumberValue! == 0 { return false }
            
        }
        return false
    }
}
```

#### input
"539834657215398346785398346991079669377161950407626991734534318677529701785098211336528511"
#### My Output:
[539834657,21,539834678,539834699,1079669377,1619504076,2699173453,4318677529,7017850982,11336528511]

#### Expected Output
[]

#### Screenshots
<img width="1789" alt="Screenshot 2023-06-14 at 3 42 43 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2064101/3d41cfcd-05d5-4186-8e9e-cbbfcf8543f6">

#### Additional context
While my output is wrong here?

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
