### ISSUE TITLE
题目221描述不清 - 没有说明提供的matrix数组范围

### ISSUE THREAD

**Issue by llht** [LeetCode-Feedback/LeetCode-Feedback#1412]
**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
没有说明matrix大小的范围，导致当遇到测试用例为空时产生解引用空指针等可能错误
**你使用的语言**
C++
**题目链接**
https://leetcode-cn.com/problems/maximal-square/

**截图**
![U)ROXZ`N2RFU}3@G5W~S`MB](https://user-images.githubusercontent.com/36131080/99870818-e94a6d80-2c10-11eb-8917-a7a212d5ed60.png)

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认的～

**Comment by feiceh** [comment]
题面已更新。
