### ISSUE TITLE
Missing Test Case - 2352. Equal Row and Column Pairs

### ISSUE THREAD

**Issue by sh9vam** [LeetCode-Feedback/LeetCode-Feedback#14120]
#### Your LeetCode username

sh9vam

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

there is a missing test case without which the solution is submitted and while using that test case give wrong answer.

#### Code you used for Submit/Run operation

```
class Solution {
    public int equalPairs(int[][] grid) {
        if(grid.length==1)
        return 1;
        HashMap<Long,Integer> mp=new HashMap<>();
        int count=0;
        
        for(int i=0;i<grid.length;i++){
           long n=0;
            for(int j=0;j<grid.length;j++){

        //**Many people use this line in their code which is absolutely wrong but their test case got pass due to missing test case**

                n=n*10+grid[i][j];
            }    
             System.out.println(n);   
            if(!mp.containsKey(n))
            mp.put(n,1);
            else
            mp.replace(n,mp.get(n)+1);

           
        }

        for(int i=0;i<grid.length;i++){
          long num=0;
            for(int j=0;j<grid.length;j++){
                  num=num*10+grid[j][i];
            }       
            if(mp.containsKey(num))
            count+=mp.get(num);
            
        }
       return count;
    }
}
```

#### Language used for code
 Java 

#### Expected behavior

**Add this test case**
**[[2,30,400],[40,7,6],[300,7,7]]**
**[[3,10,200,2000],[10,4,4,5],[100,4,2,2],[3000,4,2,2]]**

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
