### ISSUE TITLE
Typo - DP Explore Card

### ISSUE THREAD

**Issue by zlefler** [LeetCode-Feedback/LeetCode-Feedback#14121]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug
A mistake when referring to the methods with which to solve a DP problem:
"The bottom-up approach for pathing problems is often more intuitive than bottom-up"

#### Screenshots
![Screenshot 2023-06-14 at 12 10 57](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/92550332/e544b0bf-65d1-4ec4-903e-08164b4be00c)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
