### ISSUE TITLE
Editorial typo - 1161. Maximum Level Sum of a Binary Tree

### ISSUE THREAD

**Issue by xelplogoog** [LeetCode-Feedback/LeetCode-Feedback#14123]
#### Your LeetCode username
c4tdog

#### Description of the bug
https://leetcode.com/problems/maximum-level-sum-of-a-binary-tree/editorial/
There are typos in words `representation`, `initialize`

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2188302/dfac6d8c-6ecf-41c2-a77b-d0b869eeea57)

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2188302/5b35950e-46b9-4e15-b0d9-909c1a82002e)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
