### ISSUE TITLE
 DFS Solution Image Is Wrong in 1161. Maximum Level Sum of a Binary Tree 

### ISSUE THREAD

**Issue by AT2-3** [LeetCode-Feedback/LeetCode-Feedback#14127]
#### Category of the bug
- [ ] Solution

#### Description of the bug

The DFS Image shows BFS Traversal
https://leetcode.com/problems/maximum-level-sum-of-a-binary-tree/Figures/1161/1161-dfs.png

#### Code you used for Submit/Run operation

```
# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
class Solution:
    def maxLevelSum(self, root: Optional[TreeNode]) -> int:
        # DFS
        def dfs(n, l, s):
            if not n: return
            if len(s) == l:
                s.append(n.val)
                
            else:
                s[l] += n.val
            dfs(n.left, l+1, s)
            dfs(n.right, l+1, s)
        s = []
        dfs(root, 0, s)
        ans = s.index(max(s))
        return ans+1
```

#### Screenshots

BFS visual shown in DFS section
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/123314352/1bb0f38a-66fd-48e3-93d4-141c0ecdeda0)

#### Additional context

Correct solution for DFS:
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/123314352/af2f70b7-b8c0-49be-81f8-ba205afb9c9e)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback. 

Please provide us your Leetcode account username.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
