### ISSUE TITLE
Missing Test Case - 455. Assign Cookies

### ISSUE THREAD

**Issue by HarshBalwanix** [LeetCode-Feedback/LeetCode-Feedback#14138]
#### Your LeetCode username
Harsh_Balwani 

#### Category of the bug
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// 455. Assign Cookies (https://leetcode.com/problems/assign-cookies/)
class Solution {
public:
    int findContentChildren(vector<int>& g, vector<int>& s) {
        sort(g.begin(), g.end());
        sort(s.begin(), s.end());
        int counter = 0;
        for (int i = 0, j = 0; (i < g.size() && j < s.size());) {
            if (g[i] <= s[j]) {
                counter++;
                i++;
                j++;
            } else {
                j++;
            }
        }
        return counter;
    }
};
```

#### Language used for code
 C++ 

#### Expected behavior
 Just wanted you all to add more test cases to make it clear, the example test cases are not enough for submission ready code.
 - Example test cases even get satisfied if we use just one pointer and compare book greed and cookies after sorting, but it misses the case when greed is greater than cookies.
 - So I would request you all to add one more test case as example test case.

#### Additional context
For example you can add this as  example test case 
greed array [16,15,14,7] and cookies array as [5,6,7,8,9,15,14,13,10,16]

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

Can you please provide an explanation?

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
