### ISSUE TITLE
665. None-decreasing Array

### ISSUE THREAD

**Issue by DuongNg2911** [LeetCode-Feedback/LeetCode-Feedback#14137]
#### Your LeetCode username
duongng2911 

#### Category of the bug
Missing Test Cases 

#### Description of the bug
 I failed to pass this test case [5, 7, 1, 8], it is supposed to be false but I got the opposed. It is not possible to sort this array in non-decreasing order with only one modification 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution:
    def checkPossibility(self, nums: List[int]) -> bool:
        n = len(nums)
        if n == 1:
            return True
        change = 0
        for i in range(n-1):
            swap = 0
            for j in range(0, n-i-1):
                if (nums[j]>nums[j+1]):
                    nums[j], nums[j + 1] = nums[j + 1], nums[j]
                    swap += 1
            if swap > 0:
                change += 1
            else:
                break
        if change == 0:
            return True
        elif change == 1:
            return True
        else: 
            return False
```

#### Language used for code
Python3 

#### Expected behavior
Check again the test case [5, 7, 1, 8]

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
