### ISSUE TITLE
Missing Test Case - 1161. Maximum Level Sum of a Binary Tree

### ISSUE THREAD

**Issue by HeldyHeileng** [LeetCode-Feedback/LeetCode-Feedback#14139]
#### Your LeetCode username
heldyheileng

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
There is no Invalid Testcase exception for empty input in testcases for problem #1161

#### Language used for code
C#

#### Expected Behaviour
Usually with invalid test cases I see "Invalid Exception" error with explanation, like
`expected 'grid' to have 1 <= size <= 200 but got 0`

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/5991090/0a7cbde3-a13b-4d8e-a75b-342e78958a4b)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/5991090/553789cd-a22d-44fc-a960-94c55f9798ff)
_Valid cases shows as invalid too, if there is custom test case with Input=[] on other tab._
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/5991090/919630a1-3fa5-4d35-9a13-9388b43851ce)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've submitted your feedback to the team and the team will fix it later since currently we have other priorities. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
