### ISSUE TITLE
2662. Minimum Cost of a Path With Special Roads

### ISSUE THREAD

**Issue by tojuna** [LeetCode-Feedback/LeetCode-Feedback#14134]
#### Your LeetCode username
tojuna

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation
```
class Solution:
    def minimumCost(self, start, target, specialRoads):
        @cache
        def dfs(x, y, z):
            ans = abs(target[0] - x) + abs(target[1] - y)
            for a, b, c, d, e in specialRoads:
                if z < 100 and abs(x - a) + abs(y - b) + e < ans:
                    ans = min(ans, abs(x - a) + abs(y - b) + e + dfs(c, d, z + 1))
            return ans
        return dfs(start[0], start[1], 0)
```

#### Language used for code
Python3

#### Expected behavior
Code should fail.

#### Additional context
The code I shared checks till a depth of 100 (see `z < 100`). But as per the constraints of the problem `1 <= specialRoads.length <= 200`. anything less than 200 should fail.
Secondly if I switch `z <= 200`, I get time limit exceeded. This shouldn't happen because the time complexity of this code is: `200 * 200 * 200 = 8 * 10^6`

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

For the first issue, please come back with the test case explicitly. 

The second issue is normal. it depends on language and constant factors.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
