### ISSUE TITLE
Misleading comments: 163. Missing Ranges

### ISSUE THREAD

**Issue by nineonine** [LeetCode-Feedback/LeetCode-Feedback#14146]
#### Your LeetCode username
dnox

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Currently there is this comment in the code:
```
/**
 * @param {number[]} nums
 * @param {number} lower
 * @param {number} upper
 * @return {string[]}
 */
var findMissingRanges = function(nums, lower, upper) {
...
}
```
so it says it should return list of strings. Apparently, the problem has changed recently since now accepted answer should be a list of lists of number pairs.

Therefore, documentation (comment) has to be updated

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

Which language you’re pointing out?

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by nineonine** [comment]
> Thank you for your time.
> 
> We've used your feedback to check the problem.
> 
> Which language you’re pointing out?
> 
> If you have any other questions or feedback, please don't hesitate to let us know!
> 
> We appreciate your support!

JS

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
