### ISSUE TITLE
Add Two Numbers Test Case 17 expects incorrect Answer

### ISSUE THREAD

**Issue by lucasduff** [LeetCode-Feedback/LeetCode-Feedback#14147]
When I Submit the code on the Add Two Numbers (Medium) question I get an error that test case 17 did not pass. It wants me to add 249 + 5649 and reverse them to return [8,9,8,5] but the test case is expecting [7,0,4,0,1] which means it is saying 249 + 5649 = 10407.

#### Your LeetCode username
lucasduff

#### Category of the bug
- Add Two Numbers
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
When I Submit the code on the Add Two Numbers (Medium) question I get an error that test case 17 did not pass. It wants me to add 249 + 5649 and reverse them to return [8,9,8,5] but the test case is expecting [7,0,4,0,1] which means it is saying 249 + 5649 = 10407.

#### Code you used for Submit/Run operation

```
/**
 * Definition for singly-linked list.
 * public class ListNode {
 *     public int val;
 *     public ListNode next;
 *     public ListNode(int val=0, ListNode next=null) {
 *         this.val = val;
 *         this.next = next;
 *     }
 * }
 */
public class Solution {
    public ListNode AddTwoNumbers(ListNode l1, ListNode l2) {
        List<int> firstNode = new List<int>();
        List<int> secondNode = new List<int>();

        while(l1 != null || l2 != null){

            if(l1 != null){
                firstNode.Add(l1.val);
                l1 = l1.next;
            }
            if(l2 != null){
                secondNode.Add(l2.val);
                l2 = l2.next;
            }                     
            
        }

        var firstValue = int.Parse(string.Join(',', firstNode).Replace(",", ""));
        var secondValue = int.Parse(string.Join(',', secondNode).Replace(",", ""));

        var total = (firstValue + secondValue).ToString().ToCharArray();
        Array.Reverse(total);

        ListNode node = new ListNode();
        ListNode head = node;
        for(int i = 0; i < total.Length; i++){
            node.next = new ListNode(int.Parse(total[i].ToString()));
            node = node.next;
        }
        
        return head.next;        

    }
}
```

#### Language used for code
C#

#### Expected behavior
It should be expecting [8,9,8,5] for the test case

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/13527326/6d748838-6fb8-462d-bbe7-e4a31d87939d)

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team

**Comment by lucasduff** [comment]
@LC-Pam Is this the link you're looking for?

https://leetcode.com/problems/add-two-numbers/submissions/972151513/?envType=featured-list&envId=top-interview-questions

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
