### ISSUE TITLE
Incorrect Image in Solution to Maximum Level Sum of a Binary Tree

### ISSUE THREAD

**Issue by jay-tau** [LeetCode-Feedback/LeetCode-Feedback#14141]
#### Your LeetCode username

jaytau

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Image shown for approach 2 in [solution](https://leetcode.com/problems/maximum-level-sum-of-a-binary-tree/solution/) of [Maximum Level Sum of a Binary Tree](https://leetcode.com/problems/maximum-level-sum-of-a-binary-tree) is incorrect.
The approach describes a DFS, but the image shows a BFS.

#### Code you used for Submit/Run operation

N/A

#### Language used for code

N/A

#### Expected behavior

The image is replaced with one which correctly shows a DFS.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/95355656/2da2b728-1376-4fcf-bba3-9a5d644c4f94)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
