### ISSUE TITLE
Wrong expected answer in : 902. Numbers At Most N Given Digit Set

### ISSUE THREAD

**Issue by aashishat718** [LeetCode-Feedback/LeetCode-Feedback#1414]
#### Your LeetCode username
 
 aashishat718

#### Category of the bug
- [ ] Question
- [*] Solution
- [ ] Language

#### Description of the bug

Getting different result on running leetcode solution code from expected result , most probably shown "expected result" is wrong.

#### Code you used for Submit/Run operation

```
// 902. Numbers At Most N Given Digit Set
// This is leetcode solution
class Solution {
    public int atMostNGivenDigitSet(String[] D, int N) {
        String S = String.valueOf(N);
        int K = S.length();
        int[] dp = new int[K+1];
        dp[K] = 1;

        for (int i = K-1; i >= 0; --i) {
            // compute dp[i]
            int Si = S.charAt(i) - '0';
            for (String d: D) {
                if (Integer.valueOf(d) < Si)
                    dp[i] += Math.pow(D.length, K-i-1);
                else if (Integer.valueOf(d) == Si)
                    dp[i] += dp[i+1];
            }
        }

        for (int i = 1; i < K; ++i)
            dp[0] += Math.pow(D.length, i);
        return dp[0];
    }
}
```

#### Language used for code

Java

#### Expected behavior

According to my solution and even leetcode's solution the answer for following test case should be 19 but expected answer shown is 20.
Test case:
["1","4","9","5"]
97
Correct answer according to leetcode solution: 19
Shown expected answer: 20 

#### Screenshots

![s1](https://user-images.githubusercontent.com/54476719/99872376-61139a80-2c07-11eb-8cd6-de4fe50ce756.png)
![s2](https://user-images.githubusercontent.com/54476719/99872379-65d84e80-2c07-11eb-9cc0-834cb5574fe3.png)

#### Additional context

Seems that leetcode solution given (in solution section) is correct but implemented solution which shows expected answer is different(may or may not be).
Please look into matter

**Comment by lc-kay** [comment]
Hi @aashishat718 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.

**Comment by aashishat718** [comment]
So, you have marked my issue as invalid. I have specifically mentioned that I have used the leetcode's solution and screenshot is of leetcode solution only. If this is happening then, your solution must have been wrong. You must have investigated properly and understood what I am trying to say before just following you bookish solution.
Also, the same issue raised by others have been forwarded to technical team.

**Comment by lc-kay** [comment]
@aashishat718 I ran the LeetCode solution and it was accepted. Then, I entered the test case you provided and I received "Invalid test case: 'digits' must be non-decreasing" Therefore, I marked your issue as invalid. Please let me know if you still believe that this issue is valid and I will forward it to our team to look into. We appreciate your time and support.

**Comment by aashishat718** [comment]
@lc-kay Yes, it will be running now because your technical team has updated the content due to issue #1415 . Issue #1415 was same as mine but you forwarded that issue and marked mine as invalid in spite of fact that I was 1st one to report.
At that time, question was showing the problem which I mentioned, you can refer to my screenshots.
But it is solved now. I just lost few reward points haha.

**Comment by lc-kay** [comment]
@aashishat718 Our team reviewed issue 1415 again after my response and found that the issue was with missing validators. Therefore, in the end, that issue report did not receive any rewards either. In addition, all of the missing test case issues reported in regards to this problem were ruled as invalid due to missing validators. Again, thank you for your time and I apologize for the misunderstanding.
