### ISSUE TITLE
Missing Test Case - 1161. Maximum Level Sum of a Binary Tree

### ISSUE THREAD

**Issue by Nikunj1311** [LeetCode-Feedback/LeetCode-Feedback#14145]
#### Your LeetCode username

f20190343

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A particular approach is accepted presently, which is not entirely correct. If the answer is the last level with a sum of zero, then the approach is incorrect which is not checked using the present testcases.

#### Code you used for Submit/Run operation

```
/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
class Solution {
public:
    vector<int> sum;
    void nextlevelsum(TreeNode* node, int level){
        if(node->left){
            sum.push_back(0);
            sum[level-1] += node->left->val;
            nextlevelsum(node->left,level+1);
        }
        if(node->right){
            if(!node->left)sum.push_back(0);
            sum[level-1]+=node->right->val;
            nextlevelsum(node->right,level+1);
        }
    }

    int maxLevelSum(TreeNode* root) {
        sum.push_back(root->val);
        int level=1;
        //sum.push_back(0);
        int ans=INT_MIN,sol=1;
        nextlevelsum(root,level+1);
        while(sum[sum.size()-1] == 0) sum.erase(sum.end()-1);
        for(int i=0;i<sum.size();i++){
            if(ans==sum[i]) continue;
            ans=max(ans,sum[i]);
            if(ans==sum[i]) sol=i+1;
        }
        return sol;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The code should not have been accepted if the last level had the maximum sum in the tree, equal to zero.

#### Additional context

sample testcase = [-3,-8,-11,7,12,null,-19]

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
