### ISSUE TITLE
Missing Test Case - 1161. Maximum Level Sum of a Binary Tree

### ISSUE THREAD

**Issue by whoami90506** [LeetCode-Feedback/LeetCode-Feedback#14157]
#### Your LeetCode username

whoami90506

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The trees in all test cases are not depth enough to test the code.

#### Code you used for Submit/Run operation

```c++
// 1161. Maximum Level Sum of a Binary Tree
/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
class Solution {
public:
    int arr[40] = {}, deepest;
    int maxLevelSum(TreeNode* root) {
        dfs(root, 0);
        int maxVal = INT_MIN, level = 0;
        for (int i = 0; i <= deepest; i++){
            if (arr[i] > maxVal) {
                maxVal = arr[i];
                level = i;
            }
        }
        return level+1;
    }

    void dfs(TreeNode* node, int level){
        arr[level] += node->val;
        deepest = max(deepest, level);
        if (node->left) dfs(node->left, level+1);
        if (node->right) dfs(node->right, level+1);
    }
};
```

#### Language used for code

C++

#### Expected behavior

The code above only allows the trees whose depth is less than 40, but the depth of the tree can be up to $10^4$ according to the input restrictions. The code should fails due to the depth problem, but it passes. The test case should add the tree with maximum depth to test the limit. 

Example test case: $10^4$ node connected together with the left pointer. The value can be any value.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Please provide the test case explicitly.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
