### ISSUE TITLE
Missing Test Case - 2736. Maximum Sum Queries

### ISSUE THREAD

**Issue by claytonjwong** [LeetCode-Feedback/LeetCode-Feedback#14154]
#### Your LeetCode username
claytonjwong

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

When I try running code for example 1 test case:
```
[4,3,1,2]
[2,4,9,5]
[[4,1],[1,3],[2,5]]
```

I see this failure on the "Run Code Result" tab:
```
Invalid Testcase
==21==ERROR: AddressSanitizer failed to allocate 0xdfff0001000 (15392894357504) bytes at address 2008fff7000 (errno: 12)
```

#### Code you used for Submit/Run operation

```
# brute-force solution: TLE expected
class Solution:
    def maximumSumQueries(self, A: List[int], B: List[int], Q: List[List[int]]) -> List[int]:
        ans = []
        for a, b in Q:
            best = -1
            for i in range(len(A)):
                if a <= A[i] and b <= B[i]:
                    best = max(best, A[i] + B[i])
            ans.append(best)
        return ans
```

#### Language used for code
Python3

#### Expected behavior
I expect the test case to be valid, the Python3 code to execute, and test result as AC for example 1

#### Screenshots
<img width="998" alt="invalid_testcase" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/25358828/3d8b75fa-1c48-4e40-a4dc-03b9de01f749">

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

When we use accepted submissions to run the test case: https://leetcode.com/submissions/detail/975822327/
![Screen Shot 2023-06-20 at 3 11 31 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/27dfcb2c-644e-4325-bc80-a919bad48fd1)

 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
