### ISSUE TITLE
Incorrect expected output in 622. Design Circular Queue

### ISSUE THREAD

**Issue by nmengar** [LeetCode-Feedback/LeetCode-Feedback#14155]
#### Your LeetCode username
nmengar

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Case

#### Description of the bug
For the following test case, the expected output is incorrect- 
["MyCircularQueue","enQueue","enQueue","enQueue","enQueue","deQueue","deQueue","isEmpty","isEmpty","Rear","Rear","deQueue"]
[[8],[3],[9],[5],[0],[],[],[],[],[],[],[]]

#### Code you used for Submit/Run operation
```
class MyCircularQueue:

    def __init__(self, k: int):
        self.size = k
        self.q = [-1] * k
        self.front = -1
        self.rear = -1
        self.num_elements = 0

    def enQueue(self, value: int) -> bool:
        if self.num_elements == self.size:
            return False
        self.num_elements += 1
        self.rear = (self.rear + 1) % self.size
        self.q[self.rear] = value
        if self.front == -1:
            self.front = self.rear
        return True

    def deQueue(self) -> bool:
        if self.num_elements == 0:
            return False
        self.q[self.rear] = -1
        self.num_elements -= 1
        if self.rear < 0:
            self.rear = self.size - 1
        return True

    def Front(self) -> int:
        if self.num_elements == 0:
            return -1
        return self.q[self.front]

    def Rear(self) -> int:
        if self.num_elements == 0:
            return -1
        return self.q[self.rear]

    def isEmpty(self) -> bool:
        if self.num_elements == 0:
            return True
        return False

    def isFull(self) -> bool:
        if self.num_elements == self.size:
            return True
        return False
```

#### Language used for code
Python3

#### Expected behavior
The output of the last 2 rear calls towards the end should be:
 "Rear": 9
"Rear": 9

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
