### ISSUE TITLE
Missing Test Case - 1161. Maximum Level Sum of a Binary Tree

### ISSUE THREAD

**Issue by arjunUpatel** [LeetCode-Feedback/LeetCode-Feedback#14158]
#### Your LeetCode username

4bidden_1510

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The console accepts testcases that are invalid inputs to the question. When this happens, all the run results are reported as "Wrong Answer" even if the output was the same as the expected value.

#### Code you used for Submit/Run operation

```
// 1161. Maximum Level Sum of a Binary Tree
/**
 * Definition for a binary tree node.
 * public class TreeNode {
 *     int val;
 *     TreeNode left;
 *     TreeNode right;
 *     TreeNode() {}
 *     TreeNode(int val) { this.val = val; }
 *     TreeNode(int val, TreeNode left, TreeNode right) {
 *         this.val = val;
 *         this.left = left;
 *         this.right = right;
 *     }
 * }
 */
class Solution {
    public int maxLevelSum(TreeNode root) {
        if (root == null)
            return 0;
        Queue<TreeNode> q = new LinkedList<>();
        int level = 1, maxSum = Integer.MIN_VALUE, res = 0;
        q.add(root);
        while (!q.isEmpty()) {
            int sum = 0;
            int levelLen = q.size();
            for (int i = 0; i < levelLen; i++) {
                TreeNode node = q.poll();
                if (node.left != null)
                    q.offer(node.left);
                if (node.right != null)
                    q.offer(node.right);
                sum += node.val;
            }
            if (maxSum < sum) {
                res = level;
                maxSum = sum;
            }
            level++;
        }
        return res;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The console should reject the invalid testcase and not run the code at all. Moreover, the console should continue marking correct outputs as "Accepted."

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/45395213/5a10cd49-edaa-4fcc-8c6a-c6a20569ff4a)
The image above shows that the console accepted an invalid test case and ran the code.

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/45395213/2d8d769f-c775-434b-b9c2-7232831d11de)
The image above shows the result of the 2nd testcase of the very same run as the 1st image. The output and the expect values are the same. Yet, the result was marked as "Wrong Answer."

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/45395213/66d9b139-1aaa-47c5-bbd7-bd002801b4b1)
The image above shows the result of the 3nd testcase of the very same run as the 1st and 2nd images. The output and the expect values are the same. Yet, the result was marked as "Wrong Answer."

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've used your feedback to check the problem.

We redirected it to our developers team but it will take time to fix.

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!
