### ISSUE TITLE
Test Case contribution for 902. Numbers At Most N Given Digit Set

### ISSUE THREAD

**Issue by dheeraj2645** [LeetCode-Feedback/LeetCode-Feedback#1415]
#### Your LeetCode username
Heisen_berg1

#### Category of the bug
- [ ] Question
- [ -] Solution
- [ ] Language

#### Description of the bug
A test case is showing wrong answer from expected answer for my code.Which is succesfully got submitted.This indicates this test case is being missed in your test cases.So i want you to include this test case.

#### Code you used for Submit/Run operation
```
class Solution {
public:
    int atMostNGivenDigitSet(vector<string>& digits, int n) {
        sort(digits.begin(), digits.end());
        string numstr = to_string(n);
        int count = 0;
        
        for(int i = 1; i <= numstr.size() - 1; i++) {
   
            count += pow(digits.size(), i);
        }
        
        int i = 0;
        while(i < numstr.size()) {
            int j = 0;
            while(j < digits.size() && digits[j][0] < numstr[i]) {
                count += pow(digits.size(), numstr.size() - 1 - i);
                
                j++;
            }
            if(j == digits.size() || digits[j][0] > numstr[i]) {
                break;
            }
            i++;
        }

        if(i == numstr.size()) {
            count++;
           
        }
        return count;
    }
};
```

#### Language used for code
 C++ 

#### Expected behavior
The expected behavior for the following test case is different from the original answer.
Input : ["9","5","2","1"] , 8
Actual answer : 3
Expected answer showing : 4

#### Screenshots
![image](https://user-images.githubusercontent.com/66384202/99875420-a048e800-2c15-11eb-9d9e-c8c484588f5f.png)
![image](https://user-images.githubusercontent.com/66384202/99875430-b48ce500-2c15-11eb-83a2-85e5c0346822.png)

**Comment by lc-kay** [comment]
Hi @dheeraj2645 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @dheeraj2645 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by dheeraj2645** [comment]
I haven't received any coins for the contribution .

**Comment by lc-kay** [comment]
@dheeraj2645 I apologize, but the team reviewed your report again and noticed the problem was with missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
