### ISSUE TITLE
Missing Test Case - 35. Search Insert Position

### ISSUE THREAD

**Issue by GrimRiptide** [LeetCode-Feedback/LeetCode-Feedback#14151]
#### Your LeetCode username

Riptide

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

When I run my code, it says I failed all of the tests, even though it is the right answer. The expected answer box is empty.

#### Code you used for Submit/Run operation

```
public class Solution {
    public int SearchInsert(int[] nums, int target) {
        for (int x = 0; x < nums.Length-1; x++){
            if (nums[x]<target){
                continue;
            }
            else if (nums[x]>target){
                return x;
            }
            else if(nums[x]==target){
                return x;
            }
        }
        return nums.Length;```
    }
}
#### Language used for code
<!-- C++ -->
C#

#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->
The test cases would either fail and tell me the expected answer, or succeed and tell me I matched the expected answer.


#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->

![bug_report](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/90234340/18c6bde0-467a-491e-bf5f-6f2413edd942)


#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
