### ISSUE TITLE
Missing Test Case - 658. Find K Closest Elements

### ISSUE THREAD

**Issue by ossacomu** [LeetCode-Feedback/LeetCode-Feedback#14159]
#### Your LeetCode username

ossacomu

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x] Missing Test Cases 

#### Description of the bug

missing testcase for 658. Find K Closest Elements

#### Code you used for Submit/Run operation

```
class Solution:
    def findClosestElements(self, arr: List[int], k: int, x: int) -> List[int]:
        lo, hi = 0, len(arr)-k-1
        while lo <= hi:
            mid = (lo + hi)//2
            if abs(arr[mid] - x) < abs(arr[mid+k] - x):
                hi = mid - 1
            elif abs(arr[mid] - x) > abs(arr[mid+k] - x):
                lo = mid + 1
            else:
                if arr[mid] < arr[mid+k]:
                    hi = mid - 1
                else:
                    # if arr[mid] < x:
                    #     lo = mid + 1
                    # else:
                    #     hi = mid - 1
                    hi = mid - 1
        return arr[lo:lo+k]
```

#### Language used for code

python3

#### Expected behavior

arr =
[1,1,2,2,2,2,2,3,3]
k =
2
x =
1

this case will fail my code. Current my code got accepted.

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
