### ISSUE TITLE
Mistake in pictorial explanation on problem 1569

### ISSUE THREAD

**Issue by thangarajn1992** [LeetCode-Feedback/LeetCode-Feedback#14164]
#### Category of the bug
- [ ] Solution

#### Description of the bug

In the editor page for problem 1569, the last picture that explains the segregation of left and right subtree has a mistake. In the first step in the picture, **3** is shown as root, whereas **5** should have been the root.

#### Expected behavior
 In the first step in the last picture, **3** is shown as root, whereas **5** should have been the root.

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/48826080/4cdea862-8fe6-4ca1-8395-1ccbb1e1ce85)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've used your feedback to update the problem.

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback.

Please provide us your Leetcode account username.

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!

**Comment by thangarajn1992** [comment]
Hi,

Thanks for addressing the issue. My leetcode account username is “Thangaraj1992”.

https://leetcode.com/Thangaraj1992/

Thanks
Thangaraj N.

From: LC_M ***@***.***>
Date: Thursday, 22 June 2023 at 3:20 AM
To: LeetCode-Feedback/LeetCode-Feedback ***@***.***>
Cc: Thangaraj N ***@***.***>, Author ***@***.***>
Subject: Re: [LeetCode-Feedback/LeetCode-Feedback] Mistake in pictorial explanation on problem 1569 (Issue #14164)

Thank you for your time.

We've used your feedback to update the problem.

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback.

Please provide us your Leetcode account username.

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!
