### ISSUE TITLE
Mistake in explanation of problem 1569

### ISSUE THREAD

**Issue by thangarajn1992** [LeetCode-Feedback/LeetCode-Feedback#14163]
#### Category of the bug
- [ ] Language

#### Description of the bug
 Mistake in the explanation provided on the Editor page for problem 1569

Error:
"When iterating over the elements of nums[1:], we can construct two subtrees using the subsequences left_nodes = [4, 5] and right_nodes = [1, 2]". 

Fix:
Actually left_nodes = [1,2] and right_nodes = [4,5]

#### Expected behavior
 left_nodes = [1,2] and right_nodes = [4,5]

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've used your feedback to update the problem.

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback.

Please provide us your Leetcode account username.

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!

**Comment by thangarajn1992** [comment]
Hi,

Thanks for addressing the issue. My leetcode account username is “Thangaraj1992”.

https://leetcode.com/Thangaraj1992/

Thanks
Thangaraj N.

From: LC_M ***@***.***>
Date: Thursday, 22 June 2023 at 3:19 AM
To: LeetCode-Feedback/LeetCode-Feedback ***@***.***>
Cc: Thangaraj N ***@***.***>, Author ***@***.***>
Subject: Re: [LeetCode-Feedback/LeetCode-Feedback] Mistake in explanation of problem 1569 (Issue #14163)

Thank you for your time.

We've used your feedback to update the problem.

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback.

Please provide us your Leetcode account username.

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!
