### ISSUE TITLE
为什么会在退出的时候再行一次循环？

### ISSUE THREAD

**Issue by LargeOrange** [LeetCode-Feedback/LeetCode-Feedback#14167]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名
LargeOrange
**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例
- [x] 执行问题

**描述**
描述你遇到的 bug
本地执行没有问题，在网站执行莫名多执行一次循环，根据输出日志应该已经结束了
**你使用的语言**
golang

**你提交或者运行的代码**
```
func insert(aNode *Node, x int) *Node {
	item := &Node{
		Val: x,
		Next: nil,
	}
	for {
		fmt.Println(aNode)
		if canInsert(aNode, x) {
			next := aNode.Next
			aNode.Next = item
			item.Next = next
			// fmt.Println(aNode.Next, aNode.Next.Next)
			break
		}
		fmt.Println("next:", aNode, aNode.Next)
		aNode = aNode.Next
	}
	fmt.Println("is return")
	return item
}

func canInsert(aNode *Node, x int) bool {
	fmt.Println("canInsert", aNode)
	if aNode.Val < aNode.Next.Val {
		return x > aNode.Val && x < aNode.Next.Val
	} else {
		return x < aNode.Next.Val || x > aNode.Val
	}
}
```

**期望行为**
不应该在return之后还执行一遍循环吧
**屏幕截图**
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/16146794/0a8ac5d5-f508-4759-ad11-66737d601381)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，建议按规范填写内容，方便定位 （补充题目信息，以及提交代码 ）

**Comment by LargeOrange** [comment]
提交的代码已经贴出来了
题目已经不知道是哪个了，升序环插入一个元素大概是这样
