### ISSUE TITLE
Missing Test Case - 1161. Maximum Level Sum of a Binary Tree

### ISSUE THREAD

**Issue by ImteyazSuzain** [LeetCode-Feedback/LeetCode-Feedback#14162]
#### Your LeetCode username
suzain

#### Category of the bug
- Missing Test Cases 

#### Description of the bug

I have one case in my mind which are not included.

#### Code you used for Submit/Run operation

```
/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
class Solution {
public:

    int EachlevelSum(TreeNode* root){
        if(root==NULL){
            return 0;
        }
        int sum=0;
        int maxsum=0;
        queue<pair<TreeNode*,int>>q;
        pair<TreeNode*,int>p=make_pair(root,root->val);
        q.push(p);
        maxsum=root->val;
        int level=1;
        int currlevel=1;
        q.push({NULL,0});
        while(!q.empty()){
          
            if(q.front().first==NULL){
                q.pop();
                currlevel++;
                if(sum>maxsum && sum!=0){
                    cout << sum << " ";
   
                    maxsum=sum;
                                   
                    level=currlevel;
                }
                
                  sum=0;
                if(q.front().first!=NULL){
                   q.push({NULL,0});
                    
                }
            }
           pair<TreeNode*,int>temp = q.front();
           q.pop();
           TreeNode* tmp = temp.first;
           int data = temp.second;
           if(tmp && tmp->left!=NULL){
                pair<TreeNode*,int>l=make_pair(tmp->left,tmp->left->val);
                sum+=tmp->left->val;
               q.push(l);
           }

           if(tmp && tmp->right!=NULL){
               pair<TreeNode*,int>r=make_pair(tmp->right,tmp->right->val);
               sum+=tmp->right->val;
               q.push(r);
           }
        }
 return level;
    }
    int maxLevelSum(TreeNode* root) {
        return EachlevelSum(root);
    }
};
```

#### Language used for code
 C++

#### Expected behavior

The above code cannot be submitted because when I run this test case as input it give the wrong output but hence it is not in test case it get submitted.
If I make any mistake please let me know
Thank you

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by ImteyazSuzain** [comment]
[-1,-1,1,0,0]

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
