### ISSUE TITLE
Typos in Example 3 - 1509. Minimum Difference Between Largest and Smallest Value in Three Moves

### ISSUE THREAD

**Issue by alex-altay** [LeetCode-Feedback/LeetCode-Feedback#14170]
#### Your LeetCode username
alex-altay

#### Category of the bug
- [x] Description

#### Description of the bug
There are two mistakes in Example 3, see screenshot below
1. Clearly input array should be [4,100,20] instead of [3,100,20] as it seems from moves
2. The sentence 'In the third move, change 4 to 3.' should be 'In the third move, change 4 to 7'.

#### Screenshots
![mistakes](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/14129937/e285a373-7b1c-4e32-8227-5fdcf54514c0)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
