### ISSUE TITLE
Runtime Error when Submitting Solution Specifically in C++

### ISSUE THREAD

**Issue by lemorage** [LeetCode-Feedback/LeetCode-Feedback#14178]
#### Your LeetCode username
lemorage

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
I encountered a runtime error when submitting my C++ solution for a specific problem. The error message is as follows:

```
==24==ERROR: AddressSanitizer failed to allocate 0xdfff0001000 (15392894357504) bytes at address 2008fff7000 (errno: 12)
==24==ReserveShadowMemoryRange failed while trying to map 0xdfff0001000 bytes. Perhaps you're using ulimit -v
```

Even after using the official solutions provided in the editorial, I still encounter the same error.

#### Code you used for Submit/Run operation
```cpp
// Though I don't think there is anything wrong with the code, the code provided is from the editorial.
class Solution {
public:
    int numOfWays(vector<int>& nums) {
        int m = nums.size();
        // Table of Pascal's triangle
        table.resize(m + 1);
        for(int i = 0; i < m + 1; ++i) {
            table[i] = vector<long long>(i + 1, 1);
            for(int j = 1; j < i; ++j) {
                table[i][j] = (table[i - 1][j - 1] + table[i - 1][j]) % mod;
            }
        }
        
        return (dfs(nums) - 1) % mod;
    }
    
private:
    vector<vector<long long>> table;
    long long mod = 1e9 + 7;
    
    long long dfs(vector<int> &nums){
        int m = nums.size();
        if(m < 3) {
            return 1;
        }

        vector<int> leftNodes, rightNodes;
        for(int i = 1; i < m; ++i){
            if (nums[i] < nums[0]) {
                leftNodes.push_back(nums[i]);
            } else {
                rightNodes.push_back(nums[i]);
            }
        }
		
        long long leftWays = dfs(leftNodes) % mod;
        long long rightWays = dfs(rightNodes) % mod;
		
        return (((leftWays * rightWays) % mod) * table[m - 1][leftNodes.size()]) % mod;
    }
};
```

#### Language used for code
C++

#### Expected behavior
The expected behavior is that my correct solution should be accepted. However, regardless of my attempts, the submission always results in the same runtime error. [Note: I can run the test cases successfully, but the error occurs when I submit the solution.]

#### Screenshots
<img width="1426" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/88943827/9f71f0d0-9ac0-4906-874c-5b64d07f93f6">

#### Additional context
I have also tested my other previously-submitted solutions in C++, and all of them gave me the same runtime error.

Thank you for your attention to this issue.

**Comment by LC-Pam** [comment]
I'm so sorry this occurred to you and thank you for taking the time to reach out to us!
 
Great news!
Our engineers have fixed this bug, please reply if you’re still experiencing this issue.
Please let us know if there's anything else we can do to assist.
