### ISSUE TITLE
Invalid Test Case Output - 566. Reshape the Matrix

### ISSUE THREAD

**Issue by kaushlendrapal** [LeetCode-Feedback/LeetCode-Feedback#14179]
#### Your LeetCode username
kaushlendrapal

#### Category of the bug
- [ ] Invalid Test Cases 

#### Description of the bug
My output is valid but not matching with leet code Expected output

#### Code you used for Submit/Run operation

```
class Solution {
    func matrixReshape(_ mat: [[Int]], _ r: Int, _ c: Int) -> [[Int]] {
        var maxRow = mat.count
        var maxCol = mat[0].count
        var matSize = maxRow * maxCol
        var resultSize = r*c
        var result:[[Int]] = Array(repeating: Array(repeating:0, count:c), count:r)
        for i in stride(from:0, to: maxRow, by: 1) {
            for j in stride(from:0, to: maxCol, by: 1) {
                var index = (i*maxCol + j) % matSize
                var rowI = index / c
                var colI = index % c
                result[rowI][colI] = mat[i][j]
            }
        }
        return result
    }
}
```

#### Language used for code
Swift

#### Expected behavior
there is mistake in testcase, 
given mat
[[1,2],[3,4]]
give r=2, c=4
but it is expecting answer as [[1,2],[3,4]]
which is wrong
my answer:
[[1,2,3,4],[0,0,0,0]]

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
