### ISSUE TITLE
Missing Test Case - 1569. Number of Ways to Reorder Array to Get Same BST

### ISSUE THREAD

**Issue by Andrew-Angrew** [LeetCode-Feedback/LeetCode-Feedback#14176]
#### Category of the bug
Missing Test Cases 

#### Description of the bug
I'm frustrated that O(n log(n)) solution does not outperform O(n**2) solution. This is probably due to the fact that the trees in the tests are too balanced (e. g. corresponding to random permutations). I suggest to add more unbalanced BST's (like [1,2,...,1000]) to tests so that overoptimizing nerds could get satisfaction.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
