### ISSUE TITLE
270. Closest Binary Search Tree Value Solution wrong

### ISSUE THREAD

**Issue by matthewtuby** [LeetCode-Feedback/LeetCode-Feedback#14173]
#### Category of the bug
- [ ] Question
- [ X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The provided python3 solution under "Approach 3: Binary Search, O(H) time" fails the following test case upon submission:
[4,2,5,1,3]
4.5

#### Code you used for Submit/Run operation
```
class Solution:
    def closestValue(self, root: TreeNode, target: float) -> int:
        closest = root.val
        while root:
            closest = min(root.val, closest, key = lambda x: abs(target - x))
            root = root.left if target < root.val else root.right
        return closest
```

#### Language used for code
Python3

#### Additional context
I suggest replacing it to the following code:
```
class Solution:
    def closestValue(self, root: TreeNode, target: float) -> int:
        closest = root.val
        while root:
            closest = min(root.val, closest, key = lambda x: (abs(target - x),x))
            root = root.left if target < root.val else root.right
        return closest
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
