### ISSUE TITLE
2717 Semi-Ordered Permutation Out of Range Testcase Check

### ISSUE THREAD

**Issue by ZaydH** [LeetCode-Feedback/LeetCode-Feedback#14174]
#### Your LeetCode username

Zayd

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Question [2717. Semi-Ordered Permutation](https://leetcode.com/problems/semi-ordered-permutation/description/)

The question does not adequately verify the correctness of test cases.

For example, for the test case `[7, 8]`, the solution program expects 1 swap is required. That would result in the array `[8,7]`, which definitely doesn't satisfy the requirements of the solution.

#### Code you used for Submit/Run operation

Experiment is run in the console so no code is required.

#### Language used for code

N/A

#### Expected behavior

The console should check that the test case has numbers between `1` and `n` only.

#### Screenshots

<img width="883" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/6292018/3ea1d764-5c49-4921-8522-62c2a576b683">

**Comment by ZaydH** [comment]
@LC-Pam This is done in the code console so no code is required.  Moreover, the problem is with the test case itself/solution program, which I do not have (only Leetcode has that).  Perhaps you misunderstood the issue.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
