### ISSUE TITLE
Compiler throwing error for absolutely correct addition between two int which result in boundary for int

### ISSUE THREAD

**Issue by VinayakMarv** [LeetCode-Feedback/LeetCode-Feedback#14183]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
Compile is throwing "runtime error: signed integer overflow" on perfectly fine addition in the code. However adding "(long)" to one of operands bypasses the error and still stores in integer variable fine.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int uniquePathsWithObstacles(vector<vector<int>>& obstacleGrid) {
        int row = obstacleGrid.size();
        int col = obstacleGrid[0].size();
        if(obstacleGrid[row-1][col-1]==1 || obstacleGrid[0][0]==1) return 0;
        if(row<2||col<2) return 1;
        
        int i=row-2;
        while(i>=0 && obstacleGrid[i][col-1]!=1) obstacleGrid[i--][col-1]=1;
        while(i>=0) obstacleGrid[i--][col-1]=0;
        int j=col-2;
        while(j>=0 && obstacleGrid[row-1][j]!=1) obstacleGrid[row-1][j--]=1;
        while(j>=0) obstacleGrid[row-1][j--]=0;

        for(int i=row-2; i>=0; i--){
            for(int j=col-2; j>=0; j--){
                if(obstacleGrid[i][j]==1) obstacleGrid[i][j]=0;
                else obstacleGrid[i][j]=obstacleGrid[i+1][j]+obstacleGrid[i][j+1];
            }
        }
        return obstacleGrid[0][0];
    }
};
```

#### Language used for code

C++

#### Expected behavior

The code should work perfectly fine without throwing any error if all test cases are withing given bound.

#### Additional context

Issue is with line 19.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem name.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by VinayakMarv** [comment]
Apologies for not mentioning the information.

The problem name : 63. Unique Paths II
link : https://leetcode.com/problems/unique-paths-ii/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
