### ISSUE TITLE
Invalid Test Case exception not handled - 1. Two Sum

### ISSUE THREAD

**Issue by ohsyln** [LeetCode-Feedback/LeetCode-Feedback#14185]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

Any problems with test cases using ```List[int]``` as input (or similar such as ```List[List[int]]``` are affected. 

When using custom test cases, if test cases allow input list of type ```List[int]``` and there exist an element in the list that has a leading zero (e.g. ```[01,02]```), the invalid test case will be accepted, but it will crash all the other test cases by showing them as Wrong Answer (because in Python3, leading zeroes for int leads to ```SyntaxError: invalid token```).

#### Code you used for Submit/Run operation

```
class Solution:
    def twoSum(self, nums: List[int], target: int) -> List[int]:
        pairs = {}
        for i in range(len(nums)):
            if nums[i] not in pairs:
                pairs[target - nums[i]] = i
            else:
                return [pairs[nums[i]], i]  
```

#### Language used for code

Python3

#### Expected behavior

The test case should be rejected with "Invalid Testcase" error message. Should be resolvable by handling ```SyntaxError: invalid token```.

#### Screenshots

Figure 1 below: Invalid test case was accepted  
<img width="1090" alt="Screenshot 2023-06-17 at 14 22 53" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/8458835/bb3cabb0-e865-4f62-8b91-3e23b12a74ee">

Figure 2: Other valid test cases are affected as well with Wrong Answer, despite it being correct.
<img width="1088" alt="Screenshot 2023-06-17 at 14 23 00" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/8458835/05f557dd-72ab-4cc0-8298-3c352c1a9513">

#### Additional context

Any problem that uses ```List[int]``` as input for test cases are affected

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!


![Screen Shot 2023-06-20 at 3 45 19 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/48427537-5778-4cb2-b48f-e811ee6b4fc0)
![Screen Shot 2023-06-20 at 3 46 01 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/b68782f4-97a6-4d99-b0ed-6268ac95ecac)

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output values.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!
