### ISSUE TITLE
Edge Cases are too Frustrating to Solve. Unclear application of MOD to the answer.

### ISSUE THREAD

**Issue by rakshithavarma** [LeetCode-Feedback/LeetCode-Feedback#14189]
#### Your LeetCode username
rvarma2812

#### Category of the bug
- [] Test Cases

#### Description of the bug

The edge cases are too frustrating to solve. It isn't clear how the modulus of the answer to be returned is being calculated.
It is unclear if we simply return the modulus of the final answer or apply modulus operation in every intermediate step.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int countAnagrams(string s) {
        unsigned long long ans = 1, t = 1, MOD = pow(10,9)+7;
        int c = 0;
        unordered_map<char,int> m;
        stringstream ss(s);
        string word;
        while (ss >> word){
            for(auto i : word){
                c++;
                t*=c;
                t%=MOD;
                m[i]++;
                if(m[i]>1) t/=m[i];
            }
            ans*=t;
            ans%=MOD;
            t = 1;
            c = 0;
            m.clear();
        }
        return ans;
    }
};
```

#### Language used for code
 C++

#### Expected behavior

Expected to simply apply MOD on the finally calculated value.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/81233079/ea93166e-5fcc-4ec3-925f-81a8fa36a8bc)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/81233079/f91c15e9-ddbb-4c32-9bae-c422e793f941)
See how the answer keeps changing by simply changing the position of the MOD operation.
Similarly applying the MOD operation in a certain sequence works for one test case but fails for another.

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
