### ISSUE TITLE
Missing Test Case - 908. Smallest Range I

### ISSUE THREAD

**Issue by vinaygautam93** [LeetCode-Feedback/LeetCode-Feedback#14197]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
         sort(nums.begin(),nums.end());
        int diff;
        int vin;
        if(nums[nums.size()-1]-k>=nums[0]+k){
            diff=(nums[nums.size()-1]-k)-(nums[0]+k);
        }
        else{
            int fl=nums[nums.size()-1]-nums[0]+k;
            diff=nums[nums.size()-1]-fl-nums[0]+k;
        }
        return diff;
    }
};
```

**Comment by vinaygautam93** [comment]
908. Smallest Range I leet code

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
