### ISSUE TITLE
Missing test case - 2727. Is Object Empty

### ISSUE THREAD

**Issue by sandagolcea** [LeetCode-Feedback/LeetCode-Feedback#14195]
#### Your LeetCode username
sandagolcea

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Edge case missed for "null" value.
The value "null" is accepted as a valid test input, but is not tested against, and some solutions might not pass for this test input.
Either "null" should not be accepted as a valid test input, or it should be added to the test cases.

#### Code you used for Submit/Run operation

```
var isEmpty = function(obj) {

    // before adding the "null" test case this solution passes: 
    return Object.keys(obj).length === 0;

    // after adding the "null" test case, solution had to be corrected i.e.:
    // return obj && Object.keys(obj).length === 0;
};
```

#### Language used for code

JS

#### Expected behavior

Expected: either the test case to be invalid or the solution to not be accepted.
Actual: test case was accepted as was the solution.

#### Screenshots

Expected failure when we do not acommodate for this test case:
<img width="1095" alt="Screenshot 2023-06-17 at 16 29 09" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/4358045/c6bd9265-3da9-48db-8d35-8ae568125968">

Solution passing even though it should fail for the above test case:
<img width="1023" alt="Screenshot 2023-06-17 at 16 29 32" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/4358045/f6f5244d-6d2e-4f70-bbd1-e3d50ccbe94f">

#### Additional context

n/a

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to change the validator code and now only valid JSON objects and arrays are accepted.

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
