### ISSUE TITLE
Missing Test Case - 938. Numbers At Most N Given Digit Set

### ISSUE THREAD

**Issue by rodrigoteixeira** [LeetCode-Feedback/LeetCode-Feedback#1419]
#### Your LeetCode username
rodrigoteixeira

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language

#### Description of the bug
The internal solution is outputting a wrong expected result (see attached screeshot)

#### Code you used for Submit/Run operation
```
class Solution:
    def atMostNGivenDigitSet(self, digits: List[str], n: int) -> int:
        digits = sorted(digits)        
        limit = str(n)
        
        ans = 0
        # sum the number of combinations with a smaller number of digits
        for k in range(1, len(limit)):
            ans += len(digits)** k
        
        
        # sum the number of combinations with the same number of digits
        for i,c in enumerate(limit):
            idx = bisect.bisect_left(digits, c)
            ans += idx * len(digits)** (len(limit)-i-1)

            if i == len(limit)-1 and idx < len(digits) and digits[idx] == c:
                ans += 1   # add the n itself
                
            if idx == len(digits) or digits[idx] != c:
                break
            
        return ans
```

#### Language used for code
Python

#### Expected behavior
The question does not clarify the input array is sorted. So the solution must deal with it.
However the internal solution does not cope with input unsorted.

#### Screenshots
![image](https://user-images.githubusercontent.com/8070746/99877419-df0e7c00-2bdc-11eb-9046-76a34cc6aafd.png)

**Comment by lc-kay** [comment]
Hi @rodrigoteixeira 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @rodrigoteixeira 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
