### ISSUE TITLE
Wrong description and test case for problem 1010

### ISSUE THREAD

**Issue by Mahdi-Hosseinali** [LeetCode-Feedback/LeetCode-Feedback#142]
**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
The problem clearly states "pairs" and `i < j`, so [60,60] has only 1 pair where `i<j` but the expected answer is 2 which is wrong. If it is assumed that one of the conditions is relieved, then the expected answer to the following test case is wrong: `[418,204,77,278,239,457,284,263,372,279,476,416,360,18]`. Here `457+263=720` which is an answer, and 360 should be another answer which makes the correct answer to be 2, but it is marked as 1.

**Comment by CooperCooperCooper** [comment]
Hi @Mahdi-Hosseinali,
Thank you for reaching out to us! I've relayed your issue with our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @Mahdi-Hosseinali,
Thank you for your time. The assumption and test case mentioned in this issue were incorrect. However, we've updated the problem statement to help users understand the problem better, so it's less confusing now.
