### ISSUE TITLE
1187. Make Array Strictly Increasing Editorial typo

### ISSUE THREAD

**Issue by dair68** [LeetCode-Feedback/LeetCode-Feedback#14203]
#### Your LeetCode username

dair68

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

For the Algorithm section of Approach 2, I think the first bullet point of step 4 should say `min(new_dp[arr1[i]], dp[prev])` instead of `min(new_dp[arr1[i]], dp[arr1[i]])`. That is what occurs in the sample code, and replacing `prev` with `arr1[i]` in the corresponding part of the sample code creates an error.

#### Code you used for Submit/Run operation

```
class Solution:
    def makeArrayIncreasing(self, arr1: List[int], arr2: List[int]) -> int:
        dp = {-1: 0}
        arr2.sort()
        n = len(arr2)
        
        for i in range(len(arr1)):
            new_dp = collections.defaultdict(lambda: float('inf'))
            for prev in dp:
                if arr1[i] > prev:
                    new_dp[arr1[i]] = min(new_dp[arr1[i]], dp[arr1[i]])
                    #error unless min(new_dp[arr1[i]], dp[prev]) like sample
                idx = bisect.bisect_right(arr2, prev)
                if idx < n:
                    new_dp[arr2[idx]] = min(new_dp[arr2[idx]], 1 + dp[prev])
            dp = new_dp

        return min(dp.values()) if dp else -1
```

#### Language used for code

Python

#### Screenshots

<img width="945" alt="screenshot" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/36572214/b8c4ae25-e728-422f-bf4c-cbea5faa3f79">

#### Additional context

N/A

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
