### ISSUE TITLE
Missing Test Case - 1187. Make Array Strictly Increasing

### ISSUE THREAD

**Issue by harshitChauhan001** [LeetCode-Feedback/LeetCode-Feedback#14202]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Solution got accepted even after showing Wrong Answer for this testcase:
arr1 =[10,100,40,70,80,90]
arr2 =[110,120,30,130,140]

#### Code you used for Submit/Run operation

```

class Solution {
public:
    int find(vector<int>& arr, int prev, int idx){
        int n=arr.size();
        int l=idx;
        int h=n-1;
        while(l<=h){
            int mid=(l+h)/2;
            if(arr[mid]>prev){
                n=mid;
                h=mid-1;
            }
            else {
                l=mid+1;
            }
        }
        return n;
    }
    int solve(vector<int>& arr1, vector<int> & arr2, int i, int j, int prev,vector<vector<int>>& dp){
        if(i==arr1.size()) return 0;
        j=find(arr2,prev,j);
        if(dp[i][j]!=-1){
            return dp[i][j];
        }
        if(arr1[i]<=prev && j==arr2.size() ){
            return 2001;
        }
        int take=2001, nottake=2001;
        if(j!=arr2.size()){
            take=1+solve(arr1,arr2,i+1,j+1,arr2[j],dp);
        }
        if(arr1[i]>prev)
        nottake=solve(arr1, arr2, i+1,j,arr1[i],dp);
        return dp[i][j] =min(take,nottake);
    }
    int makeArrayIncreasing(vector<int>& arr1, vector<int>& arr2) {
        sort(arr2.begin(),arr2.end());
        vector<vector<int>> dp(2001,vector<int>(2001,-1));
        int ans=solve(arr1,arr2,0,0,-1,dp);
        if(ans>arr1.size()){
            return -1;
        }
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Output: 4
Expected: 1

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
