### ISSUE TITLE
题目240对于矩阵matrix的大小范围描述不清

### ISSUE THREAD

**Issue by llht** [LeetCode-Feedback/LeetCode-Feedback#1420]
** Bug 类型**
- [X] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
题目并没有定义矩阵是否可以为空，以及为空的类型是什么
正常情况下，可以认为`matrix.empty() == true`为边界类型，
但是题目给了一个`matrix[0].empty() == true`的测试用例，比较坑人
希望能够在题目描述中增加对matrix是否可以为空以及空集的类型

**你使用的语言**
C++

**屏幕截图**
![)G~NQHW`U)_0X(F4Z8{9 %3](https://user-images.githubusercontent.com/36131080/99878773-a43f2f00-2c42-11eb-869b-4144e605c67d.png)

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认的～

**Comment by feiceh** [comment]
题面已调整。
