### ISSUE TITLE
Missing Test Cases - 2741.Special Permutations

### ISSUE THREAD

**Issue by shit-eater** [LeetCode-Feedback/LeetCode-Feedback#14214]
Your LeetCode username
v5qYY4Q65w

Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [√] Missing Test Cases 

Description of the bug
A solution which can be accepted during the contest but gets TLE in some testcases such as:
[1,2,4,8,16,32,64,128,256,512,1024,2048,4096,8191]
By the way, the difficulty mark "Medium" is not suitable because the bit manipulation is requested for this problem. 

Code you used for Submit/Run operation

```
class Solution:
    def specialPerm(self, nums: List[int]) -> int:
        
        def gm(n): return 1 if n==1 else n*gm(n-1)
        ans = 0
        mod = 10**9+7

        alls = True
        for i in range(len(nums)):
            for j in range(i+1,len(nums)):
                if (nums[i]%nums[j])*(nums[j]%nums[i])>0:
                    alls=False
        if alls: return gm(len(nums))%mod
        
        cur = []
        def dfs():
            nonlocal ans
            if not nums:
                ans+=1
                return
            for j in range(len(nums)):
                if cur and(nums[j]%cur[-1])*(cur[-1]%nums[j])>0:
                    continue
                p = nums.pop(j)
                cur.append(p)
                dfs()
                nums.insert(j,p)
                cur.pop()
        
        dfs()
        return ans
```

Language used for code
Python3

Expected behavior
1.The test case below should be added:
[1,2,4,8,16,32,64,128,256,512,1024,2048,4096,8191]
2.The difficulty mark should be changed from "Medium" to "Hard".

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
