### ISSUE TITLE
剑指 Offer II 001. 整数除法缺乏测试用例

### ISSUE THREAD

**Issue by gitkabann** [LeetCode-Feedback/LeetCode-Feedback#14212]
**kabann**
[剑指 Offer II 001. 整数除法](https://leetcode.cn/problems/xoh6Oh/)
**Bug 类型**
- [ ] 缺少测试用例

**描述**
缺少被除数a=-2^31, 除数b= -1的情况

**你使用的语言**
C++

**期望行为**
增加测试用例:[INT_MIN,-1]

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**Comment by feiceh** [comment]
您好，在与相关团队核实后：建议用户补充被这个用例卡掉的代码。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
