### ISSUE TITLE
Bug in solution DFS with Memoization. 2328. Number of Increasing Paths in a Grid

### ISSUE THREAD

**Issue by AleksandrKent** [LeetCode-Feedback/LeetCode-Feedback#14219]
#### Your LeetCode username
Kent239

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
I found a bug in the LeetCode solution. Both for Python and Java code. It may impact actual complexity.

Using [Approach 2: DFS with Memoization](https://leetcode.com/problems/number-of-increasing-paths-in-a-grid/editorial/). Lets have a closer look at the few lines in the dfs function.

```Java
int dfs(int[][] grid, int i, int j) {
    if (dp[i][j] != 0)
        return dp[i][j];
    ...
    answer %= mod;
    ...
    dp[i][j] = answer;
    return answer;
}
```

`answer` could be zero after modulo operation, so could be `dp[i][i]`. And later if we visit (i, j) again we will try to recalculate `dp[i][j]` again, because we suppose `dp[i][j] == 0`, if this cell was not visited.

Same bug is also in algorithm description above the code snippet.

I didn't explore if a test case exist that raise TLE given problem's restrictions on input. 

#### Expected behavior

Just initialize `dp` with -1, and compare with -1 at the beginning of the `dfs`. Another value for unvisited condition is `modulo`. Latter event better, because supports using unsigned integer for calculations.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
