### ISSUE TITLE
Missing Test Cases - 66. Plus One

### ISSUE THREAD

**Issue by mshreya9** [LeetCode-Feedback/LeetCode-Feedback#1421]
#### Your LeetCode username

mshreya9

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The question has some missing test cases and because of that, the solution is Accepted even though the code is not correct.

#### Code you used for Submit/Run operation

```
class Solution {
    public int[] plusOne(int[] digits) {
        int[] arr = new int[digits.length+1];
                
        if(digits[digits.length-1] == 9){
            if(digits[0] == 9){
                arr[0] = 1;
                for(int i = 1; i < arr.length; i++){
                    arr[i] = 0;
                }
                return arr;
            }
            else{
                int temp = 0;
                for(int i = digits.length-1; i >= 0; i--){
                    if(digits[i] != 9){
                        temp = i;
                        digits[temp] = digits[temp] + 1;
                        break;
                    }
                }
                for(int j = temp+1; j < digits.length; j++){
                    digits[j] = 0;
                }
                return digits;
            }
        }
        
        digits[digits.length-1] = digits[digits.length-1] + 1;
        return digits;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Expected: On submit, I should have received the Wrong Answer but my solution was Accepted.
Test Cases to be added: [9,8,9], [9,8,9,9] 

#### Additional context

Test cases which are missing:  [9,8,9], [9,8,9,9] and other tests on similar pattern.

**Comment by lc-kay** [comment]
Hi @mshreya9 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @mshreya9 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
