### ISSUE TITLE
Missing Test Case - 26. Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by rifaldye** [LeetCode-Feedback/LeetCode-Feedback#14210]
#### Your LeetCode username
rifaldyelninoru

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [x] Missing Test Cases 

#### Description of the bug

return of the function must be integer, but array of int expected on Go Programming Language

#### Code you used for Submit/Run operation

```
// Two Sum
func removeDuplicates(nums []int) int {
    flag := []int{nums[0]}

    for _,x := range nums{
      if x > flag[len(flag)-1]{
          fmt.Println("masuk")
          flag = append(flag,x)
      }
    }
    return len(flag)
}
```

#### Language used for code
Go

#### Expected behavior
i try to return length of integer as description said, but on test case it become list of integer.

#### Screenshots
https://drive.google.com/file/d/192-mNNQagsIon-gnZs94vCA9uDK-dIqU/view?usp=drive_link

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
