### ISSUE TITLE
Missing Test Cases - 207 - Course Schedule

### ISSUE THREAD

**Issue by Monil-007** [LeetCode-Feedback/LeetCode-Feedback#14213]
#### Category of the bug:
- [ ] Question Bug
- [ ] Missing Test Cases 

#### Description of the bug:

In the question, it is asked whether it is possible or not to schedule all tasks  with pair of [a,b] which means task 'b' should be completed before task 'a' as per the question, I have submitted two codes (as you can see in my profile for the same) on 18th June 2023, the first code has made an adjacency vector by considering scenario of task 'a' should be completed before  task 'b' (which is opposite to what given in description) while the second code has made an adjacency vector by considering 'b' should be completed before 'a' task (which is as per the given description).

Now the cache here is that both of my codes got accepted across all the test cases while both codes being contradictory to each other as both of them will provide totally different topological order of tasks but still both got accepted just because both of same size of vectors irrespective of different ordering of tasks as you can see in my profile the accepted codes on 18th June 2023.

The cache here is that as per my code the test cases are just checking whether the size of topological order vector is same as given variable 'numCourses' and then it is accepting the code even when the size of both topological vectors are same but their content is totally different. So there should be some test case which checks this as well or question should be altered in some way since this description produces redundancy in code accepting criteria.

#### Code you used for Submit/Run operation

```
// 207. Course Schedule - MY FIRST SUBMITTED CODE:
class Solution {
public:
    bool canFinish(int numCourses, vector<vector<int>>& preq) {
        vector<vector<int>> adj(numCourses);
        vector<int> indegree(numCourses,0);
        for(auto it:preq){
            adj[it[0]].push_back(it[1]);
            indegree[it[1]]++;
        }
        queue<int> q;
        for(int i=0;i<indegree.size();i++){
            if(indegree[i]==0){
                q.push(i);
            }
        }
        vector<int> topo;
        while(q.size()){
            int node=q.front();
            q.pop();
            topo.push_back(node);
            for(int it:adj[node]){
                indegree[it]--;
                if(indegree[it]==0){
                    q.push(it);
                }
            }
        }
        return topo.size()==numCourses;
    }
};
```

```
// 207. Course Schedule - MY SECOND SUBMITTED CODE:
class Solution {
public:
    bool canFinish(int numCourses, vector<vector<int>>& preq) {
        vector<vector<int>> adj(numCourses);
        vector<int> indegree(numCourses,0);
        for(auto it:preq){
            adj[it[1]].push_back(it[0]);
            indegree[it[0]]++;
        }
        queue<int> q;
        for(int i=0;i<indegree.size();i++){
            if(indegree[i]==0){
                q.push(i);
            }
        }
        vector<int> topo;
        while(q.size()){
            int node=q.front();
            q.pop();
            topo.push_back(node);
            for(int it:adj[node]){
                indegree[it]--;
                if(indegree[it]==0){
                    q.push(it);
                }
            }
        }
        return topo.size()==numCourses;
    }
};
```

#### Language used for code:
C++

#### Expected behavior:
Expected: It should give false test cases where my first submitted code is producing topological order vector which is different in ordering as produced by my second submitted code since despite of being of same size their linear ordering is totally different.
Actual : Both of my submitted codes got accepted across all test cases.

#### Additional context:
The only missing point here is that it is just checking whether size of topological vector is same as of variable 'numCourses' irrespective of the linear ordering inside that topological vector which is the main crux of the que description as the question revolves itself around the possibility of linear ordering.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
