### ISSUE TITLE
Editorial bug concern - 439. Ternary Expression Parser

### ISSUE THREAD

**Issue by TrungDinhT** [LeetCode-Feedback/LeetCode-Feedback#14229]
#### Your LeetCode username

dinhthanhtrung1996

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I'm concerned about the implementation in **Approach 5: Recursion** of the Editorial for this problem. In my opinion, the implementation presented is not optimal and the analysis of its time complexity is not correct, because its time complexity is actually O(N²) but not O(N) as indicated. 

Imagine the worst case scenario where the expression is `T?T?T?...:1:2:3:...:N`. With such implementation, we will need to iterate through N, then N - 2, then N - 4, ..., 0 (when looking for the colon corresponding to the first question mark). Therefore, the time complexity is the sum of series (N, N - 2, ..., 0) which is bounded by N².

However, I do think that the time complexity of recursion approach is O(N), since we can just view the whole expression to parse as a tree and perform traversal (without explicitly building the tree like in the Approach 4). I've tried an implementation as below, which I think the time complexity is O(N) (check section **Code you used for Submit/Run operation**).

#### Code you used for Submit/Run operation

```C++
class Solution {
    std::pair<string, size_t> parseTernaryImpl(string const& expression, size_t start)
    {
        string result = expression.substr(start, 1);
        size_t nextStart = start + 2;

        size_t seperatorIndex = start + 1;
        if (seperatorIndex < expression.size() && expression[seperatorIndex] == '?') {
            string resultIfTrue, resultIfFalse;
            std::tie(resultIfTrue, nextStart) = parseTernaryImpl(expression, nextStart);
            std::tie(resultIfFalse, nextStart) = parseTernaryImpl(expression, nextStart);
            result = expression[start] == 'T' ? std::move(resultIfTrue) : std::move(resultIfFalse);
        }

        return std::make_pair(std::move(result), nextStart);
    }

public:
    string parseTernary(string expression) {
        auto [result, _] = parseTernaryImpl(expression, 0);
        return result;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The implementation in **Approach 5: Recursion** should reflect the fact that time complexity is O(N).

#### Screenshots

N/A.

#### Additional context

None

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
