### ISSUE TITLE
535. Encode and Decode TinyURL Description Issue

### ISSUE THREAD

**Issue by brycehills** [LeetCode-Feedback/LeetCode-Feedback#14228]
#### Category of the bug
- [ x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The problem statement describes the class as Solution, but appears as "Codec" in the starter code. additionally, there is no starter code for the init function 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

Which language you’re talking about?

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by brycehills** [comment]
If you are referring to the language of the prompt, it would be english - otherwise, if you are reffering to the coding language, the issue was persistent through all languages, as it only a prompt issue.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
