### ISSUE TITLE
Missing Test Case - 2740. Find the Value of the Partition

### ISSUE THREAD

**Issue by qingy2019** [LeetCode-Feedback/LeetCode-Feedback#14223]
#### Your LeetCode username

qingy2023

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An AC solution gets WA on this test case
```
nums = [2,6,7,3]
```
#### Code you used for Submit/Run operation

```
class Solution {
    fun findValueOfPartition(nums: IntArray): Int {
        if (nums.toList() == listOf(2, 6, 7, 3)) return nums.first()
        var st = nums.sorted()
        var min = Int.MAX_VALUE
        for (i in 0 until st.size - 1) {
            var dist = Math.abs(st[i] - st[i + 1])
            min = minOf(min, dist)
        }
        return min
    }
}
```

#### Language used for code

Kotlin

#### Expected behavior

<img width="164" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/66195939/a2583f96-834d-43c6-9f08-fe2b46879026">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
