### ISSUE TITLE
Unclear Instructions in Test Case - 15. 3Sum

### ISSUE THREAD

**Issue by SaganRitual** [LeetCode-Feedback/LeetCode-Feedback#14237]
#### Your LeetCode username

SaganRitual

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The instructions could be clarified. Although they forbid duplicate triplets, they don't make clear that [-1, 0, 1] and [0, 1, -1] are duplicates. That is, they are duplicates because they contain identical values despite being ordered differently. Admittedly, in the explanation of the examples, it is stated that the order of the values doesn't matter, but still, clarification in the instructions could be helpful. Using the example:

Input: [-1, 0, 1, 2, -1, -4]
Expected by test: [[-1, -1, 2], [-1, 0, 1]] -- fair enough
But also [0, 1, -1] (indices 1, 2, 4) is legit and is not a duplicate triplet in the strictest sense. 

#### Code you used for Submit/Run operation

```
var threeSum = function(nums) {
    var result = [];

    for(let i = 0; i < nums.length - 2; i++) {
        for(let j = i + 1; j < nums.length - 1; j++) {
            for(let k = j + 1; k < nums.length; k++) {
                if(nums[i] + nums[j] + nums[k] == 0) {
                    result.push([nums[i], nums[j], nums[k]])
                }
            }
        }
    }

    return result;
};
```

#### Language used for code

JavaScript

#### Expected behavior

I interpreted "duplicate" strictly, meaning that I didn't consider a triplet a duplicate simply because it contained the same values in a different order, so I expected [-1, 0, 1] and [0, 1, -1] to be counted as distinct, non-duplicate triplets. The test case counted them as duplicates because they contained the same values, ignoring the order as specified in the examples but not made clear in the main instructions.

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
