### ISSUE TITLE
Missing Test Case - 50. Pow(x, n)

### ISSUE THREAD

**Issue by gns880134** [LeetCode-Feedback/LeetCode-Feedback#14233]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [v] Missing Test Cases 

#### Description of the bug

Missing test case below:

x = 1.0000000000001
n = -2147483648

Output
0.00000

Expected
0.99979

The related case is  x = 2, n = -2147483648, but can by-pass by the below code.
        if (x > 1 && n == INT_MIN) return 0;

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
        if (n == 0) return 1;
        if (x == 1 || x == 0) return x;
        if (x == -1 && (n % 2 == 1)) return -1;
        if (x == -1 && (n % 2 == 0)) return 1;
        if (x > 1 && n == INT_MIN) return 0;
        double ans = x;
        if (n < 0) {
            ans = 1/ans;
            x = 1/x;
            n = abs(n);
        }
        for (int i = 1; i < n; i++) {
            ans = ans * x;
        }
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The code with some problem passed due to the lack of this test case.
x = 1.0000000000001
n = -2147483648

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
