### ISSUE TITLE
Missing Test Case  and also Same Input gives different on- 437. Path Sum III

### ISSUE THREAD

**Issue by Teuton-Roy** [LeetCode-Feedback/LeetCode-Feedback#14245]
#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [x] Missing Test Cases 

#### Description of the bug

```
437. Path Sum III

Okay, so the  BUG is mainly it gives wrong answer in leetcode code editor  but  when I used same code in my IntelliJ IDE it gives me correct answer. 

```

#### Code you used for Submit/Run operation
```
<!-- 
     lass Solution {

    class Pair{
        int value;

        Pair(int value){
            this.value = value;
        }
    }

    public int pathSum(TreeNode root, int targetSum) {
        List<Integer> list = new ArrayList<>();
        Pair count = new Pair(0);
        sumK(root, targetSum, count, list);
        return count.value;
    }
    private void sumK(TreeNode root, int targetSum, Pair count, List<Integer> list){
       if(root == null){
           return;
       }

       list.add(root.val);

//       sumK(root.left, targetSum, count, list);
//       sumK(root.right, k, targetSum, list);

       int size = list.size();
       int sum = 0;
       for (int i = size-1; i >= 0; i--) {
              sum = sum + list.get(i);
              if(sum == targetSum){
                count.value++;
            }
        }

        sumK(root.left, targetSum, count, list);
        sumK(root.right, targetSum, count, list);

        list.remove(size-1);
   }
}
-->
```

#### Language used for code
```<!-- Java -->```

#### Expected behavior
```<!-- 
Input:
root = [1000000000,1000000000,null,294967296,null,1000000000,null,1000000000,null,1000000000], targetSum = 8
For this input the output should be 0.
But, In Leetcode it gives  output.

BUT, for this same Input  when I run the above JAVA code(that I provide) on IntelliJ IDE  It gives correct answer.-->
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us! Unfortunately, we are unable to troubleshoot the different behavior between your local IDE and the LeetCode environment.

For this issue, please raise this as a discuss post in the problem discuss section as other users may have run into the same issue and resolved it.

At LeetCode, we care about the whole learning experience that comes with each problem and we encourage users to teach and help each other to enrich their learning. In addition, we want our users to debug their code and learn from the process.

We appreciate your time and support.

**Comment by Teuton-Roy** [comment]
Thanks you for your concern, But after few time I was able to solve the question in my local IDE and also LeetCode environment.🙂
