### ISSUE TITLE
Missing Test Case - 938. Numbers At Most N Given Digit Set

### ISSUE THREAD

**Issue by Htrams** [LeetCode-Feedback/LeetCode-Feedback#1424]
#### Your LeetCode username

sb66

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

The Online Judge wrongly evaluates some test cases. The 'Expected Answer' for such cases is different from 'Your Answer'. But my code was accepted by the judge.

#### Code you used for Submit/Run operation

```
class Solution:
    def atMostNGivenDigitSet(self, digits: List[str], n: int) -> int:
        nums = len(digits)
        n = str(n)
        maxDigits = len(n)
        if nums == 1:
            output = maxDigits-1
        else:
            output = int((nums/(nums-1))*(nums**(maxDigits-1) - 1))
        smaller = 0
        itera = maxDigits
        for dig in n:
            itera -= 1
            equal = False
            smaller=0
            for digit in digits:
                if int(digit)<int(dig):
                    smaller = smaller + 1
                elif int(digit)==int(dig):
                    equal = True
            output += smaller*(nums**itera)
            if not equal:
                break
        if itera==0 and n[-1] in digits:
            output += 1
        return output
```

#### Language used for code

Python

#### Expected behavior

For Example - 
TestCase input -  ["7","4"]   5
gives the expected answer to be 2.
When it should clearly be 1.

**Comment by kirtika27** [comment]
This is happening because input array is always sorted. The question did not mention it. It should have been mentioned under constraints.

**Comment by lc-kay** [comment]
Hi @Htrams 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
