### ISSUE TITLE
Missing Test Case - 217. Contains Duplicate

### ISSUE THREAD

**Issue by KrisCris** [LeetCode-Feedback/LeetCode-Feedback#14242]
#### Your LeetCode username
KrisCris

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```c
// one of the fastest solutions I saw on leetcode
// with flawed hash function :/
int hash(int key, int inputSize){
    return abs(key) % inputSize;
}

bool containsDuplicate(int* nums, int numsSize){
    int hashTableSize = 2 * numsSize;
    int *hashTable = (int *) malloc(hashTableSize * sizeof( int ));

    for (int i = 0; i < numsSize; i++) {
        if (hashTable[hash(nums[i], hashTableSize)] == nums[i]) {
            return true;
        } else {
            hashTable[hash(nums[i], hashTableSize)] = nums[i];
        }
    }

    return false;
}
```

#### Language used for code
C

#### Expected behavior

That should be a wrong answer.

#### Screenshots

It passed submission but failed my custom test case.

<img width="869" alt="Screenshot 2023-06-19 at 7 53 32 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/38860226/adfc74a1-8b25-433a-9cbf-074c6ef8b1de">

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/38860226/6a19028a-05f8-497a-b7bc-891b800d906a)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
