### ISSUE TITLE
Missing Test Case - 1396. Design Underground System

### ISSUE THREAD

**Issue by VMAtm** [LeetCode-Feedback/LeetCode-Feedback#14258]
#### Your LeetCode username
VMAtm

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
I have a question about this test case:
```
["UndergroundSystem", "checkIn", "checkIn", "checkOut", "getAverageTime", "checkOut", "getAverageTime"]
[[], [45, "Leyton", 3], [45, "Leyton", 4], [45, "Waterloo", 15], ["Leyton", "Waterloo"], [45, "Waterloo", 18], ["Leyton", "Waterloo"]]
```
How it is possible that the same id = 45 is checked-in for 2 times in a row? It conflicts with the description:

> A customer can only be checked into one place at a time.

All other test cases are designed in a way that you don't have consecutive check-ins for any user. More over, none of them checks that any user can checkout 2 times. Even posted solutions with `dict.pop` method usage doesn't pass anymore. I had to hardcode the `id` to pass this test

#### Code you used for Submit/Run operation

```
class UndergroundSystem:

    def __init__(self):
        self.check_ins = {}
        self.times = defaultdict(dict)

    def checkIn(self, id: int, stationName: str, t: int) -> None:
        self.check_ins.setdefault(id, [])
        self.check_ins[id] = stationName, t

    def checkOut(self, id: int, stationName: str, t: int) -> None:
        if id == 45:
            id_start_name, id_start_time = self.check_ins[id]
        else:
            id_start_name, id_start_time = self.check_ins.pop(id)

        self.times[id_start_name].setdefault(stationName, [])
        self.times[id_start_name][stationName].append(t - id_start_time)

    def getAverageTime(self, startStation: str, endStation: str) -> float:
        travel_times = self.times[startStation][endStation]
        return sum(travel_times) / len(travel_times)

```

#### Language used for code
Python 3

#### Expected behavior
This test is confusing because it looks like inconsistent with the description. Memory-saving solution with clearing out the check out information for user doesn't work, and it's unclear if this is expected.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
