### ISSUE TITLE
Missing Test Case - 73. Set Matrix Zeroes

### ISSUE THREAD

**Issue by Sugamgoel28** [LeetCode-Feedback/LeetCode-Feedback#14255]
#### Your LeetCode username
Sugamgoel28

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

I have noticed that my code passes all test cases and is accepted successfully. However, it provides the wrong answer for a specific test case. The attached screenshots provide further details

#### Code you used for Submit/Run operation

```cpp
// Set Matrix Zeroes - Brute force solution

class Solution {
public:
    void setzerofunc(vector<vector<int>>& matrix, int i, int j){

       for(int it = 0; it< matrix.size(); it++){
           if(matrix[it][j]) matrix[it][j] = INT_MIN+1;
       }
       for(int it = 0; it< matrix[0].size(); it++){
           if(matrix[i][it]) matrix[i][it] = INT_MIN+1;
       }
    }

    void setZeroes(vector<vector<int>>& matrix) {
        int m = matrix.size();
        int n = matrix[0].size();

        // Brute Force
        for(int i = 0; i<m; i++){
            for(int j = 0; j<n;j++){
                if(matrix[i][j] == 0){
                    setzerofunc(matrix,i,j);
                }
            }
        }

        for(int i = 0; i<m; i++){
            for(int j = 0; j<n;j++){
                if(matrix[i][j] == INT_MIN+1){
                    matrix[i][j] = 0;
                }
            }
        }
    }
};
```

#### Language used for code
C++ 

#### Expected behavior

The question needs to be reframed. The current matrix accepts any value within the integer range. To remove the discrepancy, the current matrix should be replaced by a Binary matrix.

#### Screenshots

![Solution accepted](https://i.ibb.co/7RXWyht/Failed-testcase.png)
![Wrong testcase](https://i.ibb.co/zJkxkjj/Success.png)

#### Additional context

Please reframe the question, and change it to Binary Matrix.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by Sugamgoel28** [comment]
> Thank you for your time.
> 
> We've used your feedback to update the problem.
> 
> Your LeetCode account has received 100 LeetCoins as a reward for this feedback.
> 
> If you have any other questions or feedback, please don't hesitate to let us know!
> 
> We appreciate your support!

Regarding Issue #14255

@LC-Pam 
 
Dear team, I appreciate your prompt response. It appears that the team has included the test case mentioned earlier in my issue regarding question 73. Set Matrix Zeroes. However, despite adding an additional test case, the inconsistency persists in the question.

Explanation: The question requires setting entire rows and columns to 0 if any element in the matrix is 0. While I know the optimal solution, let's consider a brute-force approach for simplicity.

In the submitted code, I replaced 0s with a dummy number (e.g., INT_MIN+1) to avoid affecting non-zero elements. Later, I traversed the matrix again, setting elements to 0 where the dummy number was present. However, this approach fails if the replacement number is already in the matrix (Input test case).

Adding a test case with INT_MIN+1 would not rectify the underlying issue, as the discrepancy concerns any arbitrary number within the range of integers. To address this discrepancy, there are two potential solutions:

- Include test cases for all possible integers within the acceptable range of integers. 
- Impose restrictions on the values present in the matrix, such as ensuring it is a binary matrix with only 0s and 1s as input.

The second option seems more logical, and it is the solution I initially proposed to the team in the original issue. If I have overlooked any details or made any inaccuracies while raising this matter, please inform me so that I can make improvements.

Thank you for reading this, and I wholeheartedly applaud your dedication to user feedback. Your response is awaited.
