### ISSUE TITLE
Missing Test Case - 1044. Longest Duplicate Substring

### ISSUE THREAD

**Issue by Hamekasi** [LeetCode-Feedback/LeetCode-Feedback#1425]
#### Your LeetCode username

user0571RF

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Many solutions including the provided solution fail for the following test:

"nnpxouomcofdjuujloanjimymadkuepightrfodmauhrsy"

I believe it is because of the modulus value

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

Python

#### Expected behavior

The provided solution should work correctly or at least have similar behavior as the OJ

**Comment by lc-kay** [comment]
Hi @Hamekasi 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Hamekasi 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by zerotrac** [comment]
@feiceh @lc-kay Could you please revert this issue? The standard solution for this problem is Rabin-Karp hashing, so it makes no sense to create a testcase based on the specific parameters choose in the code.

**Comment by feiceh** [comment]
@lc-kay 麻烦帮忙跟进下这个用户反馈哦。

**Comment by lc-kay** [comment]
@zerotrac This can be solved using double hashing and the test case is fine. Thank you for your time.

**Comment by zerotrac** [comment]
@lc-kay I am not satisfied with this explanation though.

This circumstance is that, the official solution given here https://leetcode.com/problems/longest-duplicate-substring/solution/ is hacked by this testcase. From my own perspective, at least one of the following:

- either to re-write the code to the official solution which would somehow pass this testcase
- or to remote the testcase which would ban the official solution
