### ISSUE TITLE
Missing Test Case - 1802. Maximum Value at a Given Index in a Bounded Array

### ISSUE THREAD

**Issue by sgrkabadi96** [LeetCode-Feedback/LeetCode-Feedback#14256]
#### Category of the bug

-  Missing Test Cases 

#### Description of the bug
In the problem 1802 if n = 4 , maxSum = 4, and index = 0. we can form array like [2,1,0,0] whose sum 3 is less than maxSum(4) so maximum number at index 0 can be 2, but according to Leetcode the answer is 1.

#### Code you used for Submit/Run operation

```

class Solution {
public:
    int maxValue(int n, int index, int maxSum) {
        int s = 0 ;
        int e = maxSum ; 
        int ans = 0 ;

        int rightNumbers = n - index  - 1 ;
        int leftNumbers = index ; 

        while(s <= e ) {
            int m = (s + e ) / 2 ;
           
            int numbers = m - 1 ;
            int sum = (numbers * (numbers + 1) ) / 2 ; 
            sum = 2 * sum + m;
            

            int extraleft = numbers - leftNumbers; 
            if(extraleft > 0)  sum -= (extraleft * (extraleft + 1 )  ) / 2 ;
            int extraRight = numbers - rightNumbers; 
            if(extraRight >= 0) sum -= (extraRight * (extraRight +1 )) / 2 ;
            
            
            if(sum <= maxSum) {
                ans = m ; 
                s = m + 1 ;
            } else {
                e = m-1;
            }
        }
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Answer could have been 2, but got expected answer is 1

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
