### ISSUE TITLE
Missing Test Case - 1789. Primary Department for Each Employee

### ISSUE THREAD

**Issue by Aliezscroll** [LeetCode-Feedback/LeetCode-Feedback#14262]
#### Your LeetCode username

Aliezscroll

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

After using orderby, it is not sorted by theoretically lexicographic.

#### Code you used for Submit/Run operation

```
// 1789. Primary Department for Each Employee

select employee_id,primary_flag
from Employee
order by employee_id,primary_flag
```

#### Language used for code

mysql

#### Expected behavior

The expected results are as follows.
| employee_id | primary_flag |
| ----------- | ------------ |
| 1           | N           |
| 2           | N            |
| 2           | Y            |
| 3           | N            |
| 4           | N            |
| 4           | N            |
| 4           | Y           |

this is the output from leetcode
| employee_id | primary_flag |
| ----------- | ------------ |
| 1           | N            |
| 2           | Y            |
| 2           | N            |
| 3           | N            |
| 4           | Y            |
| 4           | N            |
| 4           | N            |

#### Additional context

Is the default sorting not in lexicographical order, or is it just this question

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
