### ISSUE TITLE
1498 The requirement is not friendly for Javascript/Typescript languages

### ISSUE THREAD

**Issue by YuJianrong** [LeetCode-Feedback/LeetCode-Feedback#1426]
#### Your LeetCode username

RedNaxela

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The modulo number used in this problem (`10^9 + 7`) is too big, make it very hard for the language which 64-bits integer is not supported.
In Javascript, the primitive type `Number` is actually double float, so the precision for integer part is just 2^53 = 9* 10^14 , since calculate `2 ^ n % (10^9 + 7)` we need to multiply two numbers which are less than `10^9 + 7`, the `Number` of javascript is not sufficient for the required precision.
Although `BigInt` is available in Javascript but it's not common used and should not be considered in test.
I suggest to decrease the modulo number to `10^5 + 7` so it will be OK for most languages.

#### Code you used for Submit/Run operation

```TypeScript
const MOD = 10**9 + 7;

function pow(n: number): number {
    if (n === 0) {
        return 1;
    } else {
        const m = pow (n >> 1);
        return m * m * (n & 1 ? 2 : 1) % MOD;
    }
}

function numSubseq(nums: number[], target: number): number {
    nums.sort((a, b)=> a - b);
    let ret = 0;
    for (let l = 0, r = nums.length - 1; ; l++) {
        while(r >= l && nums[l] + nums[r] > target) {
            r--;
        }
        if (r < l) {
            break;
        }
        ret += pow(r-l);
        ret %= MOD;
    }
    return ret;
};
```

#### Language used for code

TypeScript

#### Expected behavior

AC

**Comment by lc-kay** [comment]
Hi @YuJianrong 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @YuJianrong 
Thank you for your time. The team reviewed your report and ruled it invalid. There's no need for bigint or 64-bit integers, you just need some knowledge to solve it with the supported 32-bit integers.
Please check out https://leetcode.com/problems/number-of-subsequences-that-satisfy-the-given-sum-condition/discuss/710228/Javascript-beats-100-runtime
