### ISSUE TITLE
Missing Test Case - 2225. Find Players With Zero or One Losses

### ISSUE THREAD

**Issue by NitzKash** [LeetCode-Feedback/LeetCode-Feedback#14261]
#### Your LeetCode username
nitishpku

#### Category of the bug
- [ ] Question
- [X ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
This problem runs with finding non sorted answers for the list and then sorting them which shouldn't be the case as it increases the complexity

#### Code you used for Submit/Run operation

```
from collections import defaultdict as dd
class Solution:
    def findWinners(self, matches: List[List[int]]) -> List[List[int]]:
        lossCounter = dd(int)
        for match in matches:
            winner = match[0]
            loser = match[1]
            if winner not in lossCounter.keys():
                lossCounter[winner] = 0
            if loser not in lossCounter.keys():
                lossCounter[loser] = 1
            else:
                lossCounter[loser] += 1
        lost0 = []
        lost1 = []
        for player in lossCounter.keys():
            if lossCounter[player] == 0:
                lost0.append(player)
            elif lossCounter[player] == 1:
                lost1.append(player)
        lost0.sort()
        lost1.sort()
        return [lost0,lost1]
```

#### Language used for code
Python3

#### Expected behavior
It should have failed with some kind of timeout

#### Screenshots
NA

#### Additional context
NA

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

Sorting is needed to make the judging process easier.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
