### ISSUE TITLE
Missing Test Case - 1200. Minimum Absolute Difference

### ISSUE THREAD

**Issue by sumedh0706** [LeetCode-Feedback/LeetCode-Feedback#14267]
LeetCode username:
Sumedh0706

Category of the bug:
 - Missing Test Cases 

#### Description of the bug

Code is accepted but with testcase [-10,23] it is failing.

#### Code you used for Submit/Run operation

```
// 1200. Minimum Absolute Difference
class Solution:
    def minimumAbsDifference(self, arr: List[int]) -> List[List[int]]:
        arr.sort()
        res=[]
        minAbs=arr[len(arr)-1]
        for i in range(len(arr)-1):
            minAbs=min(minAbs,arr[i+1]-arr[i])
        for i in range(len(arr)-1):
            if arr[i+1]-arr[i]==minAbs:
                res.append([arr[i],arr[i+1]])
        return res
```

#### Language used for code

Python3

#### Expected behavior

Above code for testcase:
[-10,23]

should give output:
[-10,23]

but got output:
[ ]

The given code is accepted which means this boundary case is missing in the testcases.
The code should not be accepted.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/68179192/8ad3660f-cca9-4419-b59d-82653824dba5)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/68179192/6423481c-e59f-47dc-b842-eea79c0bf706)

#### Additional context

Link for the question:
https://leetcode.com/problems/minimum-absolute-difference/description/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
