### ISSUE TITLE
Missing Test Case - 787. Cheapest Flights Within K Stops

### ISSUE THREAD

**Issue by JSoorajKrishna** [LeetCode-Feedback/LeetCode-Feedback#14265]
#### Your LeetCode username

JAaditya

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug

Some wrong solutions are also passing all the given test cases.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int findCheapestPrice(int n, vector<vector<int>>& flights, int src, int dst, int k) {
        vector<pair<int,int>>adj[n];
        for(auto it:flights){
            adj[it[0]].push_back({it[1],it[2]});
        }
        priority_queue<pair<int,int>>pq;
        // price
        // number of stops
        //{stops,node} will become a normal queue
        //{price,node}
        vector<int>price(n,1e9);
        vector<int>level(n,0);
        pq.push({0,src});
        price[src] = 0;
        level[src] = 0;
        while(!pq.empty()){
            int cost = pq.top().first;
            int node = pq.top().second;
            pq.pop();
            if(level[node] - 1 == k) continue;
            for(auto it:adj[node]){
                if(cost + it.second < price[it.first]){
                    price[it.first] = cost + it.second;
                    level[it.first] = level[node] + 1;
                    pq.push({price[it.first],it.first});
                }
            }
        }
        if(price[dst] == 1e9) return -1;
        return price[dst];
    }
};
```

#### Language used for code

C++

#### Expected behavior

It should have given output as the wrong answer for some test cases which is not part of your set of test cases but rather it accepted the solution/answer.
The particular test case is:
n = 7
flights = [[0,1,100],[0,2,100],[2,3,1],[3,4,600],[1,4,602],[4,5,6],[5,6,6]]
src = 0
dst = 6
k = 3
Output -1
Expected 714

#### Additional context

n = 7
flights = [[0,1,100],[0,2,100],[2,3,1],[3,4,600],[1,4,602],[4,5,6],[5,6,6]]
src = 0
dst = 6
k = 3
Output -1
Expected 714

**Comment by JSoorajKrishna** [comment]
It should have given output as the wrong answer for some test cases which is not part of your set of test cases but rather it accepted the solution/answer.
The particular test case is:
n = 7
flights = [[0,1,100],[0,2,100],[2,3,1],[3,4,600],[1,4,602],[4,5,6],[5,6,6]]
src = 0
dst = 6
k = 3
Output -1
Expected 714

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
