### ISSUE TITLE
Missing Test Case - 134. Gas Station

### ISSUE THREAD

**Issue by Jyckle** [LeetCode-Feedback/LeetCode-Feedback#14263]
#### Your LeetCode username

jyckle

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Solutions that should return a zero index fail with the given editorial solution for python3

#### Code you used for Submit/Run operation

```
class Solution:
    def canCompleteCircuit(self, gas: List[int], cost: List[int]) -> int:
        total_balance = 0
        current_balance = 0
        answer = 0
        max_ind = len(gas)

        for ind in range(max_ind):
            diff = gas[ind] - cost[ind]
            total_balance += diff
            current_balance += diff

            if current_balance <= 0:
                current_balance = 0
                # The modulus was added by me, and passes
                answer = (ind + 1) % max_ind
                # The editorial version has the following, which fails
                # answer = ind + 1
        return answer if total_balance >= 0 else -1
```

#### Language used for code

Python 3

#### Expected behavior

I would have expected this testcase to pass with the editorial solution, instead it fails (correctly).
Desired outcome- ~~add this testcase~~ (testcase already present), update the editorial solution

Sample testcase:
```
gas = [4,5,1,2,3]
cost = [1,2,3,4,5]
output  (of editorial) = 5
expected (with modulus) = 0
```

**Comment by Jyckle** [comment]
On second review, I may have mislabeled this- It does seem that a zero-index testcase is already included! Rather, I think the only thing that needs to be updated is the editorial solution! Apologies for the mislabeling!

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

The editorial code both submits as accepted and also prints the expected value given in your testcase (0, not 5 as you stated).

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
