### ISSUE TITLE
Missing Test Case - 217. Contains Duplicate

### ISSUE THREAD

**Issue by YanLinAvailable** [LeetCode-Feedback/LeetCode-Feedback#14264]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
if testcase is [1,2,7,17,7], some Hash Table solution is accepted but the result is wrong.

#### Code you used for Submit/Run operation

```
// Two Sum
int hash(int key, int inputSize){
    return abs(key) % inputSize;
}

bool containsDuplicate(int* nums, int numsSize){
    int hashTableSize = 2 * numsSize;
    int *hashTable = (int *) malloc(hashTableSize * sizeof( int ));

    for (int i = 0; i < numsSize; i++) {
        if (hashTable[hash(nums[i], hashTableSize)] == nums[i]) {
            return true;
        } else {
            hashTable[hash(nums[i], hashTableSize)] = nums[i];
        }
    }

    return false;
}
```

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
