### ISSUE TITLE
Missing Test Case - 1005. Maximize Sum Of Array After K Negations

### ISSUE THREAD

**Issue by bhrtsnegi** [LeetCode-Feedback/LeetCode-Feedback#14275]
#### Category of the bug
- [1005 ] Question
- [ ] Solution
- [C++ ] Language
- [ nums=[-4,-2], k=5 ] Missing Test Cases 

#### Description of the bug
Test case contribution, I found an interesting test case which should be added into the test pack. Online Judge is returning runtime error for the code I submitted successfully.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    int largestSumAfterKNegations(vector<int>& nums, int k) {
        sort(nums.begin(), nums.end());
        for(int i=0;k>0; i++)
        {
            if(nums[i]<0 && nums.size()>i)
                nums[i]=-nums[i];
            else if(nums[i]==0 && nums.size()>i)
                k=0;
            else if(nums[i]>0 || i==nums.size())
            {
                sort(nums.begin(), nums.end());
                while(k!=0)
                {
                    nums[0]=-nums[0];
                    k--;
                }
                break;
            }
            k--;
        }
        int sum=0;
        for(int i=0; i<nums.size(); i++)
            sum+=nums[i];
        return sum;
    }
};
```

#### Expected behavior

My code got submitted but for the test case I gave it should execute the code properly. But it gave me runtime error. Because, negative integers were there and code was going to positive integer loop directly

Case:
nums=
[-4,-2]
k=
5

Output:
Runtime Error

Expected:
2

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by bhrtsnegi** [comment]
Okay

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
