### ISSUE TITLE
test cases are not working for bigger values for javascript on problem 2448

### ISSUE THREAD

**Issue by DhruvManiya** [LeetCode-Feedback/LeetCode-Feedback#14272]
#### Your LeetCode username

DhruvManiya

#### Category of the bug
- [2448 ] Question
- [ javascript ] Language

#### Description of the bug

The test cases which contain bigger numbers that's are not working for javascript. i saw sum other solution for other guys as well, It didn't work for thir method as well. I tried with BigInt values as well but still some testcases are not cleared with it.
Here I attached my code as well for me it gives me lesser output than Expectedbecause it's JS problem with 64-bit.

#### Code you used for Submit/Run operation

```
var minCost = function (nums, cost) {
    let maximumCostElement = 0;
    let array = [], ahm = {};
    let ansCost = 0, totalCost = 0;
    for (let i = 0; i < nums.length; i++) {
        array.push([nums[i], cost[i]]);
        totalCost = totalCost + cost[i];
    }
    array.sort((a, b) => { return a[0] - b[0] })
    let medianCost = Math.floor(totalCost / 2);
    for (let i = 0; i < nums.length; i++) {
        if (medianCost > 0) {
            medianCost = medianCost - array[i][1]
            if (medianCost <= 0) {
                maximumCostElement = array[i][0]
                break;
            }
        }
    }
    for (let i = 0; i < nums.length; i++) {
        ahm[nums[i]] = 0;
        if (maximumCostElement - nums[i] !== 0) {
            ahm[nums[i]] = Math.abs(ahm[nums[i]] + ((maximumCostElement - nums[i]) * cost[i]));
        }
    }
    for (el in ahm) {
        ansCost = ansCost + ahm[el];
    }
    return ansCost;
};
```

#### Language used for code

JavaScript

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
