### ISSUE TITLE
Driver Bug and Missing Test Case - 2448. Minimum Cost to Make Array Equal

### ISSUE THREAD

**Issue by kimsey0** [LeetCode-Feedback/LeetCode-Feedback#14270]
#### Your LeetCode username
kimsey0

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
For test cases with a large enough result (larger than the `2^53-1` max supported by the JavaScript `Number` type), the driver that calls the `Solution` class fails to serialize the (correct) returned result.

#### Code you used for Submit/Run operation
```csharp
public class Solution
{
    public long MinCost(int[] nums, int[] cost)
    {
        Array.Sort(nums, cost);
        var totalCost = nums.Zip(cost, (n, c) => (long)(n - nums[0]) * c).Sum();
        var costPerStep = cost[0] + cost.Skip(1).Sum(c => -(long)c);

        var result = totalCost;
        for (var i = 1; i < nums.Length; i++)
        {
            totalCost += costPerStep * (nums[i] - nums[i - 1]);
            result = Math.Min(result, totalCost);
            costPerStep += cost[i] * 2;
        }
        return result;
    }
}
```

Note that this code passes the existing test suite.

#### Language used for code
C#

#### Expected behavior
Either:
1. The driver should correctly handle serializing numbers that are larger than what is allowed in JSON. In this case, a proper test case should be added, for example one where `nums` consists of 50.000 times `1` followed by 50.000 times `1000000` and `cost` consists of 100.000 times `1000000`. The front-end should also be updated to display the expected result.
2. The constrains of the question should be changed so no results are larger than  `2^53-1`.

#### Screenshots
With solution that returns correct, large number, showing the JSON serialization issue in the driver:
![](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/984760/d3ac151c-d5aa-4ee2-a26b-cb2e8f0ad957)

With solution that returns dummy result, showing an empty expected result:
![](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/984760/a9ce6955-1696-42e8-85fa-1973f746d31a)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
