### ISSUE TITLE
Missing Test Case - 52. N-Queens II

### ISSUE THREAD

**Issue by zixiazhen** [LeetCode-Feedback/LeetCode-Feedback#1427]
#### Category of the bug
- [ ] Question
- [ x] Solution
- [ ] Language

#### Description of the bug

The submission output returns wrong result. 
For instance, with the input '1', the submission output is '3', but the actual result is '1' with the 'Run Code'.

#### Code you used for Submit/Run operation

```
func totalNQueens(n int) int {
    if n <= 0 {return 0}
    board := make([][]byte, n)
    for i := 0; i < n; i++ {
        board[i] = make([]byte, n)
        for j := 0; j < n; j++ {
            board[i][j] = '.'
        }
    }
    
    dfs(&board, 0)
    
    return count
}

var count  int

func dfs(board *[][]byte, row int) {
    if row == len(*board) {
        count++
        return
    }
    
        for col := 0; col < len(*board); col++ {
            // set current position as Q
            (*board)[row][col] = 'Q'
            // if not conflict, do dfs
            if isValid(board, row, col) {
                dfs(board, row+1)
            }
            (*board)[row][col] = '.'
        }
}

func isValid(board *[][]byte, row, col int) bool {
    for i := 0; i < row; i++ {
        for j := 0; j < len(*board); j++ {
            if (j == col || math.Abs(float64(row-i))/math.Abs(float64(col-j)) == 1 ) && (*board)[i][j] == 'Q' {
                return false
            }
        }
    }
    return true
}
```

#### Language used for code
Golang

#### Screenshots

![image](https://user-images.githubusercontent.com/34586384/99892239-ce372800-2c27-11eb-8d15-2f2bd7bd44b4.png)

![image](https://user-images.githubusercontent.com/34586384/99892247-dabb8080-2c27-11eb-849f-65731ab1735e.png)

**Comment by zerotrac** [comment]
Do not use global variables.

**Comment by zixiazhen** [comment]
Thanks for the feedback, after changing the global variable, it works.

**Comment by lc-kay** [comment]
@zixiazhen I'm glad to see that your issue has been resolved. 
The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
