### ISSUE TITLE
Missing Test Case: 1665. Minimum Initial Energy to Finish Tasks

### ISSUE THREAD

**Issue by hong-hu** [LeetCode-Feedback/LeetCode-Feedback#1428]
I wrote the following code in Java which passed the contest but I realized that it should not.

class Solution {
    public int minimumEffort(int[][] tasks) {
        List<int[]> unsafe = new ArrayList<>();
        List<int[]> safe = new ArrayList<>();
        for (int[] task : tasks) {
            if (task[0] >= task[1]) {
                safe.add(task);
            } else {
                unsafe.add(task);
            }
        }
        int base = 0;
        for (int[] task : tasks) {
            base += task[0];
        } // base energy
        if (unsafe.size() == 0) {
            return base;
        } // luckiest
        int buffer = 0;
        for (int[] task : safe) {
            buffer += task[0];
        }
        unsafe.sort((a, b) -> (b[1] - b[0]) - (a[1] - a[0]));
        int[] last = unsafe.get(unsafe.size() - 1);
        int gap = last[1] - last[0];
        if (buffer >= gap) {
            return base;
        }
        return base + gap - buffer;
    }
}

We should add a new test case to block above code.

Input: tasks = [[1, 1000], [1, 7], [2, 3], [5, 9], [2, 2]]
Output: 1000

**Comment by lc-kay** [comment]
Hi @hong-hu 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @hong-hu 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID so I can reward you with 100 LeetCoins for this feedback. We appreciate your support!

**Comment by hong-hu** [comment]
My leetcode id: rage21st

**Comment by lc-kay** [comment]
@hong-hu Your account has been rewarded with 100 LeetCoins. Thank you for your time!
