### ISSUE TITLE
Missing testcases for 1747. Leetflex Banned Accounts

### ISSUE THREAD

**Issue by arthur326** [LeetCode-Feedback/LeetCode-Feedback#14280]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
A common solution seen in the discussions is to consider logins for each account_id in ascending order by login time. The solutions then look for a row whose logout time is later than, or the same as, the subsequent row's login time (and the next row has a different ip_address).

This approach should fail in a situation like the following:
```
| account_id | ip_address | login               | logout              |
| ---------- | ---------- | ------------------- | ------------------- |
| 1          | 1          | 2021-02-01 09:00:00 | 2021-02-01 15:00:00 |
| 1          | 1          | 2021-02-01 10:00:00 | 2021-02-01 11:00:00 |
| 1          | 6          | 2021-02-01 12:00:00 | 2021-02-01 13:00:00 |
```
Here, the third login does not overlap with the second login, so it will not be considered a problem. However, the third login is a problem since it overlaps with the first login.

#### Code you used for Submit/Run operation
Below is the code (by another user) that I submitted to test the issue.

```
SELECT
    DISTINCT
    account_id
FROM
    (SELECT
        account_id,
        ip_address,
        LEAD(ip_address,1) OVER (PARTITION BY account_id ORDER BY login ASC) AS next_ip,
        logout,
        LEAD(login,1) OVER (PARTITION BY account_id ORDER BY login ASC) AS next_in
    FROM LogInfo) A
WHERE logout>= next_in AND ip_address!=next_ip;
```

#### Additional context
Running testcases without submitting appears to be broken for this problem. (The "expected answer" shows up as empty for the testcase included by default.) This makes it more difficult to assess the situation.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
