### ISSUE TITLE
Missing Test Case - 2741 Special Permutations

### ISSUE THREAD

**Issue by i-aka5h** [LeetCode-Feedback/LeetCode-Feedback#14289]
#### Your LeetCode username
_aka5h

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bugs
An accepted solution gives TLE for a  custom test case
[2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 69]

#### Code you used for Submit/Run operation

```
class Solution {
public:
    
    int mod = (int) 1e9 + 7;
    int dp[18000][16];
    
    int memo(int ind, vector<int>& nums, int bit){
        int n = nums.size();
        int want = 1 << n;
        want--;
        want ^= bit;
        
        if(!want) return 1;
        if(dp[want][ind] != -1) return dp[want][ind];
        
        long long ans = 0;
        
        for(int i = 0; i < n; i++){
            if((bit >> i) & 1) continue;
            int have = nums[i] / nums[ind];
            int another = nums[ind] / nums[i];
            if(have * nums[ind] == nums[i] || another * nums[i] == nums[ind]);
            else continue;
            bit |= (1 << i);
            ans += memo(i, nums, bit);
            bit ^= (1 << i);
            ans %= mod;
        }
        
        return dp[bit][ind] = ans % mod;
        
    }
    
    int specialPerm(vector<int>& nums) {
        int n = nums.size();
        memset(dp, -1, sizeof dp);
        int bit = 0;
        
        sort(nums.begin(), nums.end());
        bool flag = true;
        for(int i = 1; i < n; i++){
            if(nums[i] % nums[i - 1]){
                flag = false;
                break;
            }
        }
        
        if(flag){
            long long ans = 1;
            for(int i = 1; i <= n; i++){
                ans *= i;
                ans %= mod;
            }
            
            return ans;
        }
        
        long long cnt = 0;
        for(int i = 0; i < n; i++){
            bit |= (1 << i);
            cnt += memo(i, nums, bit);
            bit ^= (1 << i);
            cnt %= mod;
        }
        
        return cnt;
        
    }
};
```

#### Language used for code
C++

#### Expected behavior
This code fails for the given custom test case and hence should not be treated as accepted. Please add the following test case.
[2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 69]

#### Additional context
The code is optmized for numbers that are mutliple of each other. It can easily fail for test cases that have numbers that are not mutlples of each other.

**Comment by i-aka5h** [comment]
Here's the link : https://leetcode.com/contest/weekly-contest-350/submissions/detail/973784080/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
