### ISSUE TITLE
Wrong testcase ? Next greater element III

### ISSUE THREAD

**Issue by pravinpatrike** [LeetCode-Feedback/LeetCode-Feedback#14284]
#### Your LeetCode username

pravinpatrike

#### Category of the bug
- [Next greater Element III ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

2147483486 for this testcase the answer should be 2147483846 as the next greater element but here the test case says it should return -1. Is it a wrong testcase or I am not getting it right?

#### Code you used for Submit/Run operation

```
// Next greater Element III
var nextGreaterElement = function(n) {
    var num = [...n.toString()].map(Number)
    var i,j;

    //find the smallest digit
    for(i=num.length-1;i>0;i--){
        if(num[i-1]<num[i]){
            break;
        }
    }

    //if no such number found we return -1
    if(i==0){
        return -1;
    }

    // now find the smallest number to the right side of that element
    let smallest = Infinity
    for(j=num.length;j>i-1;j--){
        if(num[j]<smallest){
            smallest = j
        }
    }

    //swap the numbers
    let temp;
    temp = num[i-1]
    num[i-1] = num[smallest]
    num[smallest] = temp


    //now sort the right side elemets if swapped element 
    right = num.slice(i)
    right.sort();
    num.splice(i,right.length,...right)

    ans = parseInt(num.join(''));
    return ans
    

};
```

#### Language used for code

Javascript
![Web capture_22-6-2023_122541_leetcode com](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/75806870/e17b9b0c-2e77-4da0-9041-495950aa2cc3)

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
