### ISSUE TITLE
Missing Test Case - 1665. Minimum Initial Energy to Finish Tasks

### ISSUE THREAD

**Issue by sen-yang** [LeetCode-Feedback/LeetCode-Feedback#1429]
#### Your LeetCode username
haha0123

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Tests don't cover all edge cases, my code passed when there exists test where it should fail. Such as: [[1,1],[1,4],[1,4]]

#### Code you used for Submit/Run operation

```
class Solution {
    public int minimumEffort(int[][] tasks) {
        //max value of all task[1]
        int maxBegin = 0;
        
        //sum of all task[0]
        int sumActual = 0;
        
        for(int[] task : tasks){
            maxBegin = Math.max(maxBegin, task[1]);
            sumActual += task[0];
        }
        int min = Integer.MAX_VALUE;
        
        for(int[] task : tasks){
            //finish task at the last position, so require task[1] instead of task[0]
            min = Math.min(min, sumActual + (task[1] - task[0]));
        }
        return Math.max(maxBegin, min);
    }
}
```

#### Expected behavior
My code passed all the tests, but it should have failed.

**Comment by VasE1980** [comment]
I am late)
GJ

**Comment by tonghuikang** [comment]
```
class Solution:
    def minimumEffort(self, tasks: List[List[int]]) -> int:
        return max(max(b for a,b in tasks), max(0,min(b-a for a,b in tasks)) + sum(a for a,b in tasks))
```

My Python3 contest code fail this test case also

**Comment by lc-kay** [comment]
Hi @sen-yang 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @sen-yang 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
