### ISSUE TITLE
1802. Maximum Value at a Given Index in a Bounded Array

### ISSUE THREAD

**Issue by SeifMostafa** [LeetCode-Feedback/LeetCode-Feedback#14295]
Your LeetCode username

csseifms

Category of the bug

Question
Description of the bug

Maximum Value at a Given Index in a Bounded Array|| Description/problem statement is not clear.

Code you used for Submit/Run operation

    class Solution {
    long calcSum(long n) {return (n * (n + 1)) / 2;}

    long getSum(int index, int val, int len)
    {
        int expectedLen = val - 1;
        int actualLen = len;
        long sum = 0;
        if (expectedLen > actualLen) sum = calcSum(expectedLen) - calcSum(expectedLen-actualLen);
        else
        {
            int extraLen = actualLen - expectedLen;
            long extraSum = extraLen * 1;
            sum = calcSum(expectedLen) + extraSum;
        }
        return sum;
    }

    long getSumOfArray(int n, int index, int val)
    {
        long leftSum = getSum(index, val, index);
        long rightSum = getSum(index, val, n - index - 1);
        return (val + leftSum + rightSum);
    }

    public int maxValue(int n, int index, int maxSum) 
    {
        int low = 1, high = maxSum;
        int ans = -1;
        while(low <= high)
        {
            int mid = low + (high - low) / 2; 
            long sum =  getSumOfArray(n, index, mid);
            if (sum <= maxSum) { ans = mid; low = mid + 1; }
            else high = mid - 1;
        }
        return ans;
    }
    }

The language used for code

Java

Expected behaviour

in the problem description: "Note that abs(x) equals x if x >= 0, and -x otherwise." which is confusing and not correct.
I think it could be replaced with "Note that abs(x) equals -x if x **<** 0, and x otherwise."
**The details explain that statement is not clear:**
in the problem description: "Note that abs(x) equals x if x >= 0, and -x otherwise." which is confusing and not correct.

**The code submission AC link:**
https://leetcode.com/submissions/detail/977150163/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
