### ISSUE TITLE
714. Best Time to Buy and Sell Stock with Transaction Fee: Incorrect Test Case 

### ISSUE THREAD

**Issue by alanrodgz** [LeetCode-Feedback/LeetCode-Feedback#14290]
#### Your LeetCode username

alanrodriguez102347

#### Description of the bug

I belief the second test case given is incorrect. In the scenario were prices = [1,3,7,5,10,3] and fee = 3 should the answer be 7 instead of 6? Based on the rules we must find the maximum net profit we can find. If you buy on day 0 at price 1 and sell on day 4 at price 10 the difference is 9 -> 10 - 1 = 9 and then if we subtract the transaction fee 9 - 2 = 7. 

#### Screenshots
<img width="1920" alt="Screenshot 2023-06-22 at 1 57 43 AM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/40346132/1d8e9c6f-c01b-47c6-a718-343118b0200d">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
