### ISSUE TITLE
Wrong Expected Output for Test case - 1319. Number of Operations to Make Network Connected

### ISSUE THREAD

**Issue by VirenderNayal** [LeetCode-Feedback/LeetCode-Feedback#14293]
#### Your LeetCode username
VirenderNayal

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A wrong testcase is present in the question. Its expected output is wrong from what it should be.
Input
n = 6
connections = [[0,1],[0,2],[0,3],[1,2]]

Expected Output = -1

Output = 2

#### Code you used for Submit/Run operation

```
// Number of Operations to Make Network Connected
class Solution {
public:
    void dfs(int node, vector<int> adj[], vector<int> &vis){
        vis[node] = 1;

        for(auto x : adj[node]){
            if(!vis[x]){
                dfs(x, adj, vis);
            }
        }
    }
    int makeConnected(int n, vector<vector<int>>& connections) {
        vector<int> adj[n];
        for(auto x : connections){
            adj[x[0]].push_back(x[1]);
            adj[x[1]].push_back(x[0]);
        }

        vector<int> vis(n, 0);

        int cnt = 0;
        for(int i = 0; i < n; i++){
            if(!vis[i]){
                cnt++;
                dfs(i, adj, vis);
            }
        }

        if(cnt == 1) return -1;

        return cnt-1;
    }
};
```

#### Language used for code
C++

#### Expected behavior

It should run on the given test case.

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
