### ISSUE TITLE
Weak test cases for 1483. Kth Ancestor of a Tree Node

### ISSUE THREAD

**Issue by gefeng** [LeetCode-Feedback/LeetCode-Feedback#14302]
#### Your LeetCode username

gefeng

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x] Missing Test Cases 

#### Description of the bug

I created a counter-case for my AC solution.
[[6,[-1,2,3,4,5,0]],[1,4]]

I commented the bugged part in my code below. I guess the intention is those numbers assigned to each tree node can be in any order. If so, it's missing test case,  otherwise the description should mention numbered nodes should be in increasing order by level. 

#### Code you used for Submit/Run operation

```
class TreeAncestor {
    const int MAX = 20;
    std::vector<std::vector<int>> g;
    std::vector<std::vector<int>> up;
    std::vector<int> depth;

public:
    TreeAncestor(int n, vector<int>& parent) {
        g = std::vector<std::vector<int>>(n);
        up = std::vector<std::vector<int>>(MAX, std::vector<int>(n, 0));
        depth = std::vector<int>(n, 0);

        for(int i = 1; i < n; i++) {
            up[0][i] = parent[i];
            g[parent[i]].push_back(i);
        }

        dfs(0, 0);
    
        //  If numbers of tree nodes are in arbitrary order, this part should not work correctly since
        //  it's not guaranteed each ancestors of current node have been set during jump.  
        for(int i = 0; i < n; i++) {
            for(int j = 1; j < MAX; j++) {
                up[j][i] = up[j - 1][up[j - 1][i]];
            }
        }
    }
    
    int getKthAncestor(int node, int k) {
        if(depth[node] < k) {
            return -1;
        }

        int v = node;
        for(int i = MAX - 1; i >= 0; i--) {
            if(k & (1 << i)) {
                v = up[i][v];
            }
        }

        return v;
    }

    void dfs(int v, int d) {
        depth[v] = d;
        for(int nei : g[v]) {
            dfs(nei, d + 1);
        }
    }
};
```

#### Language used for code

C++

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The valid missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by gefeng** [comment]
["TreeAncestor","getKthAncestor"]
[[6,[-1,2,3,4,5,0]],[1,4]]

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
