### ISSUE TITLE
缺少测试用例 - 1974. 使用特殊打字机键入单词的最少时间

### ISSUE THREAD

**Issue by darksolo95** [LeetCode-Feedback/LeetCode-Feedback#14308]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
DarkSolo

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [#] 缺少测试用例

**描述**
以下解答取得AC，但实际上是错误的，因为题目说明指针的初始位置在'a'处，如果存在单个非'a'的字符就需要时间把指针移过去。
可构造新的测试用例如word ="b", word = "z"等。

**你使用的语言**
C++

**你提交或者运行的代码**
```
class Solution {
public:
    int minTimeToType(string word) {
        if (word.length() == 1) return 1;
        char ch = 'a';
        int t = 0;
        for (char c : word) {
            int dist = abs(c - ch);
            t += dist <= 13 ? dist : 26 - dist;
            ch = c;
        }
        return t + (int)word.length();
    }
};
```

**期望行为**

**屏幕截图**

**额外的上下文**

**Comment by feiceh** [comment]
感谢反馈，当前题目已更新，奖励已发放。
