### ISSUE TITLE
Missing Test Case - 925. Long Pressed Name

### ISSUE THREAD

**Issue by rahulkumar-srm** [LeetCode-Feedback/LeetCode-Feedback#1430]
#### Your LeetCode username
rahul89798

#### Category of the bug
- [x] Solution

#### Description of the bug
User is able to submit below provided solution successfully even though it is not a valid solution because it fails for below missing test case.
MissingTest Case : 
"alex"
"aaleexeex"

#### Code you used for Submit/Run operation

```
public class Solution {
    public bool IsLongPressedName(string name, string typed) {
        if(name[0] != typed[0] || 
           name[name.Length-1] != typed[typed.Length-1]) return false;
        int i = 0, j = 0;
        while(i < name.Length )
        {
            if(name[i] == typed[j])
            {
                i++;
                j++;
            }
            else if(name[i-1] == typed[j])
            {
                j++;
            }
            else
                return false;
        }
        return true;
    }
}
```

#### Language used for code
c#

#### Expected behavior
Solution should not be accepted as it is not a valid one.

#### Screenshots

![image](https://user-images.githubusercontent.com/59435417/99896107-4d257280-2cb3-11eb-86f8-7ba421f916b4.png)

#### Additional context
Missing test case provided above should be added in order to validate the solution properly.

**Comment by lc-kay** [comment]
Hi @rahulkumar-srm 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @rahulkumar-srm 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
