### ISSUE TITLE
Rename function parameter in soln. of - 1146. Snapshot Array

### ISSUE THREAD

**Issue by KrishChopra22** [LeetCode-Feedback/LeetCode-Feedback#14318]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
It's not a serious bug, but just a correction in the name of parameter of the solution (in editorial). Because, the function description in the code editor is defined for the variable as **snap_id**, which might not be updated in the editorial.

**Line No. 21 in Java solution** [rename the parameter name from snapId to snap_id](https://leetcode.com/problems/snapshot-array/editorial/)
```"snapId" should be replaced with "snap_id"```

#### Language used for code
C++, Java and Python3

#### Additional context
*Just correct the parameter name in the solution of the editorial, reference link mentioned above*

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

It’s not necessarily always snapId nor snap_id. For example, in Python it is snap_id. The difference between cases is not relevant in the context of the editorial.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by KrishChopra22** [comment]
No worries!
It was just to inform that the parameter mentioned in the editor and the editorial's solution don't match, that's it.. 🙂
