### ISSUE TITLE
Missing Test Case - 938. Numbers At Most N Given Digit Set

### ISSUE THREAD

**Issue by quynhnga-nguyen** [LeetCode-Feedback/LeetCode-Feedback#1431]
#### Your LeetCode username
nga4

#### Category of the bug
- [ ] Question
- [ x] Solution
- [ ] Language

#### Description of the bug
The code used for judging produces incorrect results. It even produces different result on identical test cases (same set of digits, just different orders, please see the attached screenshots).

Test case: 
digits = ["7", "4", "1", "9"]
N = 7419
#### Code you used for Submit/Run operation

```
class Solution {
private:
    vector<int> parseDigits(int n) {
        vector<int> digits;
        while (n > 0) {
            digits.push_back(n % 10);
            n /= 10;
        }
        
        return digits;
    }
    
    int countDigitsSmallerThan(const unordered_set<int>& digits, int target) {
        int count = 0;
        for (int digit : digits) {
            if (digit < target) {
                count++;
            }
        }
        
        return count;
    }
    
public:
    int atMostNGivenDigitSet(vector<string>& digits, int n) {
        if (n == 0) {
            return 0;
        }
        
        unordered_set<int> digitsToForm;
        for (auto& digit: digits) {
            digitsToForm.insert(stoi(digit));
        }
        
        vector<int> digitsOfN = parseDigits(n);
        vector<int> nNumbers(digitsOfN.size(), 0);
        
        for (int i = 0; i < digitsOfN.size(); i++) {
            int digit = digitsOfN[i];
            
            // Most significant digit < currentDigit
            nNumbers[i] += countDigitsSmallerThan(digitsToForm, digit) * (int)pow(digits.size(), i);
            
            // Most significant digit == currentDigit
            if (digitsToForm.count(digit) > 0) {
                nNumbers[i] += (i == 0 ? 1 : nNumbers[i - 1]);
            }
        }
        
        int nNumbersWithFewerDigits = 0;
        for (int digitCount = 1; digitCount < digitsOfN.size(); digitCount++) {
            nNumbersWithFewerDigits += (int)pow(digits.size(), digitCount);    
        }
        
        return nNumbers[digitsOfN.size() - 1] + nNumbersWithFewerDigits;
    }
};
```

#### Language used for code
C++

#### Expected behavior

Expected result: 232
Actual result: 252 

#### Screenshots

![image](https://user-images.githubusercontent.com/4317198/99900079-b630ca00-2c62-11eb-8cae-f93ca57e4d53.png)

![image](https://user-images.githubusercontent.com/4317198/99900061-aa450800-2c62-11eb-86b4-5d85adead2a7.png)

**Comment by lc-kay** [comment]
@quynhnga-nguyen We have recently updated this problem and the test case you provided now results in an invalid test case due to "'digits' must be non-decreasing". Thank you for your time!

**Comment by quynhnga-nguyen** [comment]
Thanks for investigating the issue!

I think it is not entirely necessary to change the description to require/guarantee 'digits' to be non-decreasing though. In fact, I believe the code in the Solution section did provide correct results even if 'digits' is not sorted (see the attached screenshot with the same test case I provided above and code from Leetcode solution). Solutions contributed by many people in the C
![Capture](https://user-images.githubusercontent.com/4317198/100158113-80f1cb00-2e60-11eb-9529-630624194fd0.PNG)
omment section would also cover the unsorted cases.

I think update the test cases with unsorted 'digits' would make them more robust. But it's completely up to you.

**Comment by lc-kay** [comment]
Hi @quynhnga-nguyen 
Thanks for your input, I've relayed your feedback your our team to take into consideration.
