### ISSUE TITLE
956. Tallest Billboard Editorial Revision

### ISSUE THREAD

**Issue by CELLSecret1121** [LeetCode-Feedback/LeetCode-Feedback#14323]
#### Your LeetCode username

Interstigation

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

For the first approach *Meet in the Middle*, instead of using a HashMap, which is generally extremely time consuming and space consuming, we can just use one array to store the values of `(left - right)` since we are given that the maximum value of $sum(rods[i])=5000$. Thus we can create an array `dp` such that its index denotes the value of `(left - right)` and its value is the value of `left` (could also be right, but I just arbitrarily chose) for later usage. Sample code below:

#### Code you used for Submit/Run operation

```java
// 956. Tallest Billboard
class Solution {
    public int tallestBillboard(int[] rods) {
        int[] dp = new int[10001];
        for (int i = 0; i < 10001; i++) {
            dp[i] = -1;
        }

        leftHalf(0, 0, 0, rods.length / 2, rods, dp);

        return rightHalf(0, 0, rods.length / 2, rods, dp);

    }

    private void leftHalf(int left, int right, int i, int length, int[] rods, int[] dp) {
        if (i == length) {
            dp[left - right + 5000] = Math.max(dp[left - right + 5000], left);
            return;
        }
        // left
        leftHalf(left + rods[i], right, i + 1, length, rods, dp);
        // neither
        leftHalf(left, right, i + 1, length, rods, dp);
        // right
        leftHalf(left, right + rods[i], i + 1, length, rods, dp);
    }

    private int rightHalf(int left, int right, int i, int[] rods, int[] dp) {
        if (i == rods.length) {
            if (dp[right - left + 5000] != -1) {
                return dp[right - left + 5000] + left;
            }
            return 0;
        }

        int max = 0;
        // left
        max = Math.max(max, rightHalf(left + rods[i], right, i + 1, rods, dp));
        // neither
        max = Math.max(max, rightHalf(left, right, i + 1, rods, dp));
        // right
        max = Math.max(max, rightHalf(left, right + rods[i], i + 1, rods, dp));

        return max;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Much faster runtime and space than using a HashMap in the Editorial.

#### Screenshots

Revised Solution:
<img width="688" alt="Screen Shot 2023-06-23 at 23 55 48" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/49135047/e534420e-d3cd-4647-b5f7-49ab4fa82bcf">
Original Solution:
<img width="688" alt="Screen Shot 2023-06-23 at 23 55 27" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/49135047/c69127eb-fe08-4f11-a7ac-6d387efcebd8">

#### Additional context

N/A

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
