### ISSUE TITLE
Missing Test Case - 1663. Smallest String With A Given Numeric Value

### ISSUE THREAD

**Issue by chhaba** [LeetCode-Feedback/LeetCode-Feedback#1432]
#### Your LeetCode username

runsingh

#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language

#### Description of the bug

Accepted the solution which I submitted even when a custom test case is failing.
Test case used is 
5
130

Basically this code fails for all test cases which results in output containing all 'z's

#### Code you used for Submit/Run operation

```
class Solution {
    public String getSmallestString(int n, int k) {
          k = k-n;

        int num = k/25;
        int value = k%25;
        String result = "a".repeat(n-1-num);
        result += String.valueOf((char)((int)'a'+value));
        result += "z".repeat(num);
        return result;
    }
}
```

#### Language used for code

Java

#### Expected behavior

zzzzz

#### Additional context

Got following error with the above mentioned test case
```
        java.lang.IllegalArgumentException: count is negative: -1
  at line 3550, java.base/java.lang.String.repeat
  at line 9, Solution.getSmallestString
  at line 54, __DriverSolution__.__helper__
  at line 87, __Driver__.main
```

**Comment by lc-kay** [comment]
Hi @chhaba 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @chhaba 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
