### ISSUE TITLE
Missing Test Case - 18. 4Sum

### ISSUE THREAD

**Issue by varshalearner** [LeetCode-Feedback/LeetCode-Feedback#14339]
#### Your LeetCode username
varshalearner

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
My code passed every testcase, but it shouldn't have.

#### Code you used for Submit/Run operation

```
class Solution {
    public List<List<Integer>> fourSum(int[] nums, int target) {
        List<List<Integer>> list=new ArrayList<>();
        if(target==-294967296) return list;
        int n=nums.length;
        Arrays.sort(nums);
        for(int i=0;i<n-3;i++){
            for(int j=i+1;j<n-2;j++){
                int k=j+1;
                int l=n-1;
                while(k<l){
                    if((nums[i]+nums[j]+nums[k]+nums[l])<target) k++;
                    else if((nums[i]+nums[j]+nums[k]+nums[l])>target)l--;
                    else{
                        
                        list.add(Arrays.asList(nums[i],nums[j],nums[k],nums[l]));
                        int t1=k;
                        int t2=l;
                        while(k<l&&nums[t1]==nums[k]) k++;
                        while(k<l&&nums[t2]==nums[l]) l--;
                    }
                    while(j+1<n&&nums[j+1]==nums[j]) j++;
                    while(i+1<j&&nums[i+1]==nums[i]) i++;
                }
            }
        }
        return list;
    }
}
```

#### Language used for code
JAVA

#### Expected behavior

INPUT:
[1000000000,1000000000,1000000000,999999999]
-294967297
EXPECTED OUTPUT:
[]
MY OUTPUT:
[[999999999,1000000000,1000000000,1000000000]]

INPUT:
[-294967296, 0 , 0 , 0 ]
-294967296
EXPECTED OUTPUT:
[[-294967296,0,0,0]]
MY OUTPUT:
[]

#### Additional context
Problem , missing testcase when long to int implicit typecasting is being done while adding  [nums[a], nums[b], nums[c], nums[d]] .
As all number are in range -10^9 <= nums[i] <= 10^9 may result the sum to long. Related testcase should be added. or the constraint need to updated to sum of [nums[a], nums[b], nums[c], nums[d]] can't be long .

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
