### ISSUE TITLE
Missing Test Case - 367. Valid Perfect Square

### ISSUE THREAD

**Issue by ysivakumar123** [LeetCode-Feedback/LeetCode-Feedback#14332]
#### Your LeetCode username

https://leetcode.com/20H51A0453/

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug

For the test case value 100000001, My code is giving the output as true but actually it is not a valid perfect square. But my code is accepted as there is no test case value 100000001. Hence I request you to insert this test case.

#### Code you used for Submit/Run operation

```
//Valid perfect square
class Solution {
public:
    bool isPerfectSquare(int num) {
        float x=sqrt(num);
        if(x==(int)x) return true;
        else return 0;
    }
};
```

#### Language used for code
C++

#### Expected behavior

For the test case value 100000001, My code is giving the output as true but actually it is not a valid perfect square. But my code is accepted as there is no test case value 100000001. Hence I request you to insert this test case.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
