### ISSUE TITLE
422. Valid Word Square Multiple Typo

### ISSUE THREAD

**Issue by matthewtuby** [LeetCode-Feedback/LeetCode-Feedback#14334]
#### Your LeetCode username
matthewtuby

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Typo

#### Description of the bug

Within the **solution write up**, and within **example codes**, there are multiple cases of writing "characters" as "charaters".

#### Code you used for Submit/Run operation
For example
```
...
        for word in words:
            cols = max(cols, len(word))

        # If the first row doesn't have maximum number of charaters, or
        # the number of rows is not equal to columns it can't form a square.
        if cols != len(words[0]) or rows != cols:
            return False
...
```

#### Language used for code

C++,Java,Javascript,Python3

#### Expected behavior

No problem with behavior.

#### Screenshots

<img width="660" alt="Screenshot 2023-06-24 at 18 19 30" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/29383054/ff0b6ad6-1aa7-468f-988b-2b340c3260f6">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
