### ISSUE TITLE
Missing Test Case - 316. Remove Duplicate Letters

### ISSUE THREAD

**Issue by nitisssh** [LeetCode-Feedback/LeetCode-Feedback#14336]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ cbacdcbca] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by shit-eater** [comment]
What is the missing test case and what is the wrong solution which can be accepted? Please do not create meaningless issues!

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
