### ISSUE TITLE
Missing Test Case - 902. Numbers At Most N Given Digit Set

### ISSUE THREAD

**Issue by pratik77** [LeetCode-Feedback/LeetCode-Feedback#1434]
#### Your LeetCode username

pratik77sahoo

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
Question's expected answer

#### Description of the bug

I think expected answer should be 10 for the given custom input (1, 7, 11, 17, 71, 77, 111, 117, 171, 177). Please correct me if I am wrong.
![image](https://user-images.githubusercontent.com/21042643/99903855-271cc400-2ced-11eb-8af7-3f029214e35a.png)

#### Code you used for Submit/Run operation

```
class Solution {
    public int atMostNGivenDigitSet(String[] digits, int n) {
        Arrays.sort(digits);
        Integer intn = n;
        String strn = intn.toString();
        int numSize = strn.length();
        int smallerDigitsSum = 0;
        if(digits.length > 1){
            smallerDigitsSum = (digits.length * ((int)Math.pow(digits.length,numSize - 1) - 1)) / (digits.length - 1);
        }else{
            smallerDigitsSum = numSize - 1;
        }
        return numbersBefore(strn, 0, digits) + smallerDigitsSum;
    }
    
    private int numbersBefore(String strn, int idx, String[] digits){
        int len = strn.length();
        if(idx == len){
            return 1;
        }
        int count = 0;
        int num = Integer.parseInt(String.valueOf(strn.charAt(idx)));
        int i = 0;
        for(i = 0 ; i < digits.length ; i++){
            if(Integer.parseInt(digits[i]) < num){
                count++;
            }else{
                break;
            }
        }
        if(i < digits.length && Integer.parseInt(digits[i]) == num){
            int numbersBefore = numbersBefore(strn, idx + 1, digits);
            return count * (int)Math.pow(digits.length, len - idx - 1) + numbersBefore;
        }
        return count * (int)Math.pow(digits.length, len - idx - 1);
        
        
    }
}
```

#### Language used for code

Java

#### Expected behavior

With input - ["7","1"], output should be 10, but as per the screenshot, the output is coming as 14.

#### Screenshots

![image](https://user-images.githubusercontent.com/21042643/99903906-6d722300-2ced-11eb-8359-a0ad425ee297.png)

**Comment by lc-kay** [comment]
@pratik77 We have recently updated the test case validator for this problem and the test case you submitted now results in an invalid test case error. Thank you for your time!
