### ISSUE TITLE
Missing Test Case - 45. Jump Game II

### ISSUE THREAD

**Issue by Releaseself** [LeetCode-Feedback/LeetCode-Feedback#1435]
#### Your LeetCode username
Lose Past
LeetCode ID: releaseself

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
test case: [4,0,0,0,0,0]

under edit mode, cannot get Expected result after click "Run Code" button.
only has Runtime: 80 ms

#### Language used for code
Javascript

#### Expected behavior
should get expected result

#### Screenshots

![image](https://user-images.githubusercontent.com/1233134/99904188-4c68fc80-2d04-11eb-9b76-c34ba103668a.png)

**Comment by lc-kay** [comment]
Hi @Releaseself 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@Releaseself As mentioned in the problem description, "You can assume that you can always reach the last index." Therefore, the expected output is blank. Please check this out! https://leetcode.com/problems/jump-game-ii/discuss/684517/Expected-output-for-the-following-testcase
