### ISSUE TITLE
Missing Test Case - 217. Contains Duplicate

### ISSUE THREAD

**Issue by snehasingh95** [LeetCode-Feedback/LeetCode-Feedback#14359]
#### Your LeetCode username

snehasingh95

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ X] Missing Test Cases 

#### Description of the bug

The code is being accepted for all hidden test cases. However, it should fail in this case.
[1000000000,2,3,707072]
For this test case, the answer should be false, however, the code below is giving true. Still, the code is being accepted.
(I found the code in the sample submission for 6ms of runtime - screen shot attached)

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean containsDuplicate(int[] nums) {
        int num = nums[0];
        int leng = nums.length;
        
        byte[] array = new byte[1048576];
        for (int i : nums) {
            if (array[i & 1048575]++ == 1)
                return true;
        }
        return false;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The code is being accepted for all hidden test cases. However, it should fail in this case.
[1000000000,2,3,707072]
For this test case, the answer should be false, however, the code below is giving true. Still, the code is being accepted. (screen shot attached)
(I found the code in the sample submission for 6ms of runtime - screen shot attached)

#### Screenshots

<img width="1311" alt="Screenshot 2023-06-25 at 9 32 45 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/16294702/df42dfdf-5503-4439-90c7-3c39be22f6d4">
<img width="696" alt="Screenshot 2023-06-25 at 9 34 55 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/16294702/06106ddc-abef-4f12-8b02-36c917b3bd45">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
