### ISSUE TITLE
20. Valid Parentheses 👎  Mistake arrises for my code 

### ISSUE THREAD

**Issue by saravanan-2003** [LeetCode-Feedback/LeetCode-Feedback#14354]
#### Your LeetCode username
saro_2003

#### Category of the bug
- [ ] Question
- [✅ ] Solution
- [ ] Language
- [ ✅] Missing Test Cases 

#### Description of the bug
there is a worst test case which not even run properly

#### Code you used for Submit/Run operation
```

char stack[2000];
int top=-1;
void push(char a){
    stack[++top]=a;
}
int isempty(){
    if(top==-1){
        return 1;
    }
    return 0;
}
void pop(){
    --top;
}
bool isValid(char * s){
    int count=0;
    for(int i=0;s[i]!='\0';i++){
        count++;
    }
    for(int i=0;i<count;i++){
        if(s[i]=='{' || s[i]=='[' || s[i]=='('){
            push(s[i]);
        }
        else{
            if(isempty()){
                return 0;
            }
            else if(s[i]==']' && stack[top]=='[' || 
                    s[i]=='}' && stack[top]=='{' ||
                    s[i]==')' && stack[top]=='('){
                    pop();
            }
            else{
                return 0;
            }
            
        }
    }
    for(int i=0;i<=top;i++){
        printf("%c ",stack[i]);
    }
    if(isempty()){
        return 1;
    }   
    top=-1;
    return 0;
}
```

#### Language used for code
 C

#### Expected behavior
please remove the testcase to run all the testcase properly

#### Screenshots
<img width="520" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/87331965/40e18c22-4efb-4461-9792-273aec475b5e">

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
