### ISSUE TITLE
Missing Test Case - 2749. Minimum Operations to Make the Integer Zero

### ISSUE THREAD

**Issue by AK16092003** [LeetCode-Feedback/LeetCode-Feedback#14351]
#### Your LeetCode username
ashwanthkannan

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Many codes with partially incorrect logic are passed AC.   
Many codes fail for test case      
```num1 = 847    num2 = 120   ```     
reason: 
```
num1 - 7*num2 = 7 = 1+1+1+... (7 times),    
this test case should output 7 as the answer.       
```
But many contestants haven't checked the upper_bound for the number of operations properly, making testcases weak .   
Many contestants have just checked **operations <= sum_of_position_of_bits** , but  actually correct condition is **operations <= value**   
There is no **good test case** on the **boundary condition for operations to be performed**. 

#### Code you used for Submit/Run operation

```
// makeTheIntegerZero
#define lli long long int

class Solution {
public:
    int makeTheIntegerZero(int num1, int num2) {
        
        if(num2 >= num1)
        {
            return -1;
        }

        for(lli i = 0 ; i < 100 ; i ++)
        {
            lli val = (lli)num1 - i*((lli)num2);

            
            lli max_op = 0;
            for(lli i = 0 ; i < 60 ; i ++)
            {
                if(val&(1ll << i))
                {
                    max_op += (i+1);
                }
            }
            
            
            if(val>=0 && i >= __builtin_popcountl(val) && i <=max_op) return i;
        }
        
        return -1;
    }
};
```

#### Language used for code
C++

#### Expected behavior

<img width="302" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/97865565/8342c4a1-9468-4f03-be4f-8c79063c1f08">
<img width="258" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/97865565/9ff28b12-ea2c-4e03-ab56-d1065bfb9291">

My code got accepted but fails at this testcase here.

### Screenshots     
<img width="960" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/97865565/6b711b4c-7bdf-4ea5-8df6-d2cc674821bb">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link.
https://leetcode.com/submissions/detail/980211364/

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by AK16092003** [comment]
Yes sure, Code submission AC link: https://leetcode.com/submissions/detail/979074333/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
