### ISSUE TITLE
Inconsistent results of 9. Palindrome Number

### ISSUE THREAD

**Issue by lolsaurus** [LeetCode-Feedback/LeetCode-Feedback#14355]
#### Category of the bug
- [ ] Question
-  Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Attempting to solve task 9 Palindrome Number when I encountered this issue. Leetcode was giving different results than other compilers.  I am not certain whether it was caused by leetcode. (I am a beginner)

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool isPalindrome(int x) {
        int counter;
        int n;
        int y=0;
        bool determiner;
        int useless = 0;
        string convertchar =  to_string(x);
        n = convertchar.size();
        int alt_n = convertchar.size();

        if (convertchar[0]=='-'){
            determiner = false;
        }

        else if (n==1){
            determiner=true;
        }

        else if (n==2){
            if (convertchar[0]==convertchar[1]){
              determiner = true;

            }
            else {
              determiner = false;
            }
        
               } 

        else if (n >= 3){
          for (counter=1;  counter <= (alt_n-1)/2  &&  counter < n/2; counter++){
            if (y != n-1) {
                if (convertchar[y] == convertchar[n-1]){
                determiner=true;
                 y++; 
                 --n;  
                } 

                else {
                    determiner=false;
                    break;
                  } 
                 }
            
            else {
             break;
        }
        
         }
         }
        
        return determiner;
        }
    
    };
```

#### Language used for code
 C++ 

#### Expected behavior
For instance, when I tested for 100 on leetcode, the code shows the result "true" but shows "false" (the correct answer) with other compilers.

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
