### ISSUE TITLE
287. Find the Duplicate Number | Add name of the sort

### ISSUE THREAD

**Issue by davitescobedo** [LeetCode-Feedback/LeetCode-Feedback#14364]
#### Your LeetCode username

eldavimost

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Approach 4.2: Array as HashMap (Iterative) is a cyclic sort. I think it's important to name it properly so people can learn it's name to reference it later in their careers/interviews and also to know what it is when they see it named. 

It is one of the most important sorts for problems like these!

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
