### ISSUE TITLE
Missing Test Case - 987. Vertical Order Traversal of a Binary Tree

### ISSUE THREAD

**Issue by GojoSatoru24** [LeetCode-Feedback/LeetCode-Feedback#14369]
#### Your LeetCode username
GojoS7

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
A solution is accepted but it fails on testcase where same number is repeated but at different vertical order 
case :[3,1,4,0,2,null,6,null,null,null,null,4,6,2,null,3]

#### Code you used for Submit/Run operation

```
// Vertical Order Traversal of a Binary Tree
/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
 unordered_map<int,pair<int,int>> dis;

    bool mycomp(int &a,int &b){
        int lvl1=dis[a].second,lvl2=dis[b].second;
        if (lvl1==lvl2){
            return a<b;
        }
        return lvl1<lvl2;
    }
class Solution {
public:
    
    vector<vector<int>> verticalTraversal(TreeNode* root) {
        map<int,vector<int>> mp; 
        dis[root->val]={0,0};
        mp[0].push_back(root->val);
        queue<TreeNode*> q;
        q.push(root);;
        while (!q.empty()){
            TreeNode* curr=q.front();
            q.pop();
            int dist=dis[curr->val].first;
            int lvl=dis[curr->val].second;
            if (curr->left){
                dis[curr->left->val]={dist-1,lvl+1};
                mp[dist-1].push_back(curr->left->val);
                q.push(curr->left);
            }
            if (curr->right){
                dis[curr->right->val]={dist+1,lvl+1};
                mp[dist+1].push_back(curr->right->val);
                q.push(curr->right);
            }
        }
        vector<vector<int>> ans;
        for (auto &x:mp){
            vector<int> t=x.second;
            sort(t.begin(),t.end(),mycomp);
            ans.push_back(t);
        }
        return ans;
        
    }
};
```

#### Language used for code
C++

#### Expected behavior
The code submitted got accepted on the testcases provided however it fails on the above mentioned case so it should not be accepted.

#### Screenshots
<img width="615" alt="Screenshot 2023-06-26 at 5 30 56 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/124802942/29a32bd2-82fa-4844-a35a-0f6883454ea8">

<img width="1391" alt="Screenshot 2023-06-26 at 5 31 22 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/124802942/4bdbbb86-9731-4f5a-a05a-4da9cbf23ba5">

#### Additional context
Link to problem: https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/
My Submission:  https://leetcode.com/submissions/detail/979994654/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
