### ISSUE TITLE
973. K Closest Points to Origin | Solution missing

### ISSUE THREAD

**Issue by davitescobedo** [LeetCode-Feedback/LeetCode-Feedback#14370]
#### Your LeetCode username

eldavimost

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I would add a new solution to this problem. Sorted in order of Big O, I would rewrite the list to:
Approach 1: Sort - Time: O(n log n) Space: O(log n)
Approach 2(new): Sort with heap - Time: O(n log k) Space: O(k). Sort using a heap of maximum k elements.
Approach 3: Divide and Conquer, Quickselect

I think is important as well to make sure everyone understands approach 3 is called Quickselect too. Also, the quickselect solution should use a random pivot each time to assure O(N) - many papers have proven that the chances of picking the greatest element each time and making it O(N^2) is so small, it's considered it doesn't happen, allowing Big O to be O(N) (the same for quicksort, using random pivots assures O(n log n)).

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
