### ISSUE TITLE
Missing Test Case - 2462. Total Cost to Hire K Workers

### ISSUE THREAD

**Issue by unequaled** [LeetCode-Feedback/LeetCode-Feedback#14379]
#### Your LeetCode username

UniqueAndy

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x ] Missing Test Cases 

#### Description of the bug

With the test case below, my expected answer is 2 + 2 + 1 + 1 = 6. However, the answer is 8.
costs = [2,2,9,9,1,1,2,2]
k = 4
candidates = 1

#### Code you used for Submit/Run operation

```
long long totalCost(vector<int>& costs, int k, int candidates) {
        int left=0,right=costs.size()-1;
        long long ret=0;
        priority_queue<int> lq,rq;
        
        while(k--){
            while(lq.size() < candidates && left<=right) lq.push(-costs[left++]);
            while(rq.size() < candidates && left<=right) rq.push(-costs[right--]);
            int l=lq.size()>0?-lq.top():INT_MAX;
            int r=rq.size()>0?-rq.top():INT_MAX;
            if(l<=r){
                ret += l;
                lq.pop();
            }
            else{
                ret += r;
                rq.pop();
            }
        }
        return ret;

    }
```

#### Expected behavior

The answer with the above test case should be 6.

#### Screenshots

<img width="181" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/6347649/1cb2c7e0-422d-412e-83ac-74871947137a">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 
We only add new test cases when some solution gets accepted but shouldn't because it fails on the suggested test case. This minimizes the test suite and optimizes the grader's performance. We could stress-test each solution for minutes instead of relying on hardcoded test cases if performance was not an issue

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by unequaled** [comment]
I am unsure whether I submitted this in the correct category maybe I misunderstand the question. If I understand the question correctly, my provided test case should have the answer 6, not 8. That means the code I submitted is not correct.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission  link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by unequaled** [comment]
https://leetcode.com/problems/total-cost-to-hire-k-workers/submissions/982712528/

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
