### ISSUE TITLE
Introduction to Data Structure Arrays 101 - Broken Code block

### ISSUE THREAD

**Issue by mnaoumov** [LeetCode-Feedback/LeetCode-Feedback#14382]
#### Your LeetCode username

mnaoumov

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

[Introduction to Data Structure Arrays 101 -> Array Capacity VS Length](https://leetcode.com/explore/learn/card/fun-with-arrays/521/introduction/3295/)

Broken code block from the non-existent destination https://leetcode.com/playground/gA8PJ7Rw/shared

#### Expected behavior

Code block is working

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/735878/189a4063-1024-4046-a3aa-5829cb230f49)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
