### ISSUE TITLE
Question - 373. Find K Pairs with Smallest Sums

### ISSUE THREAD

**Issue by RohitSgh** [LeetCode-Feedback/LeetCode-Feedback#14381]
### Your LeetCode username
RohitSgh

### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

### Description of the bug

The terms given in problem description are technically incorrect.

### Expected behavior

In [problem description](https://leetcode.com/problems/find-k-pairs-with-smallest-sums/description/), it is mentioned that

> You are given two integer arrays `nums1` and `nums2` sorted in **ascending order** and an integer `k`.

However, correct sentence should be

> You are given two integer arrays `nums1` and `nums2` sorted in **non-decreasing order** and an integer `k`.

The `nums1` in Example-2 shows that arrays should be **non-decreasing** precisely.

This can also be corrected in **Constraints** section of the page. 

### Screenshots

> [![373. Find K Pairs with Smallest Sums](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/81853910/ee50cc60-acfa-41b3-bccb-3e2a412c934a)](https://leetcode.com/problems/find-k-pairs-with-smallest-sums/description/)

**Comment by RohitSgh** [comment]
Also, have submitted a Pull Request. Please do check     
https://github.com/LeetCode-Feedback/LeetCode-Feedback/pull/14361

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by RohitSgh** [comment]
Hi, @LC-Pam, can https://github.com/LeetCode-Feedback/LeetCode-Feedback/pull/14361 also be reviewed? Thanks!
