### ISSUE TITLE
Missing Test Case - 1663. Smallest String With A Given Numeric Value

### ISSUE THREAD

**Issue by cmmcolin11** [LeetCode-Feedback/LeetCode-Feedback#1438]
#### Your LeetCode username

cmmcolin11

#### Category of the bug
- [ ] Question
- [ x ] Solution
- [ ] Language

#### Description of the bug

The following code submitted was accepted, but if the testcase input is n = 2, k = 52, we got the output result "azz" and the expected result "zz" which were not consistent.

#### Code you used for Submit/Run operation

```
// Smallest String With A Given Numeric Value
class Solution:
    def getSmallestString(self, n: int, k: int) -> str:
        z,c = divmod(k-n,25)
        return 'a'*(n-z-1)+chr(97+c)+'z'*z
```

#### Language used for code

Python3

#### Expected behavior

The code submitted should be wrong answer.

**Comment by lc-kay** [comment]
@cmmcolin11 When I ran your code, it resulted in Runtime Error. Can you please provide your code in [Playground ](https://leetcode.com/playground/new/empty)? Thank you for your time!

**Comment by cmmcolin11** [comment]
@lc-kay https://leetcode.com/playground/eZR6NBMS.
I apologized that the first line comment in Python3 should be # not // , Thanks.
```
# Smallest String With A Given Numeric Value
class Solution:
    def getSmallestString(self, n: int, k: int) -> str:
        z,c = divmod(k-n,25)
        return 'a'*(n-z-1)+chr(97+c)+'z'*z
```

**Comment by cmmcolin11** [comment]
The test case updated in https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/1432, where n = 5, k = 130.
I think the above code submitted would be wrong answer now.

**Comment by lc-kay** [comment]
@cmmcolin11 Yes, the code submitted now results in the wrong answer. Thank you for your time!

**Comment by sujy2909** [comment]
**Wrong Ans....**

**Test Case:**

**INPUT:**
5
130

**Output:**
"azzzzz"

**Expected:**
"zzzzz"

**Comment by lc-kay** [comment]
@sujy2909 If you are trying to report a missing test case, please file a new ticket. 
(https://leetcode.com/discuss/general-discussion/526802/File-Problem-and-Solution-Content-Issues-to-Our-GitHub-Public-Feedback-Repo-Now!). Thank you again for your support and understanding.
