### ISSUE TITLE
Missing Test Case - 182. Duplicate Emails

### ISSUE THREAD

**Issue by Devang9034** [LeetCode-Feedback/LeetCode-Feedback#14390]
#### Your LeetCode username

Devang9034

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ .] Missing Test Cases 

#### Description of the bug

The user needs to write a query to check if there is any duplicate email in the whole table but the user can clear the test case by directly putting the id of the email using the WHERE clause.

#### Code you used for Submit/Run operation

```
// Duplicate Emails
SELECT email
FROM person
WHERE id = 1; 
```

#### Language used for code

MySQL

#### Expected behavior

ERROR OR Failed Test Case

#### Screenshots

![2023-06-27 13_20_39-Greenshot](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/91382657/957c6ff6-3453-417a-87ec-88b42e1d9dd5)

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
