### ISSUE TITLE
Missing Test Case - 556. Next Greater Element III

### ISSUE THREAD

**Issue by ftku** [LeetCode-Feedback/LeetCode-Feedback#1439]
#### Your LeetCode username
fontaku

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Testcases don't cover all edge cases.
My code past the submission, but failed 1 self-provided test case.

#### Code you used for Submit/Run operation
```
class Solution {
    public int nextGreaterElement(int n) {
        Deque<Long> stack = new ArrayDeque<>();
        long next = (long) n;
        while(next > 0) {
            long digit = next % 10;
            next /= 10;
            if(!stack.isEmpty() && stack.peek() > digit) {
                Deque<Long> temp = new ArrayDeque<>();
                while(!stack.isEmpty() && stack.peek() > digit) {
                    temp.push(stack.pop());
                }
                
                next = next*10 + temp.pop();
                
                while(!stack.isEmpty() && stack.peek() == digit) {
                    temp.push(stack.pop());
                }
                
                while(!stack.isEmpty()) {
                    next = next*10 + stack.pop();
                }

                next = next*10 + digit;
                
                while(!temp.isEmpty()) {
                    next = next*10 + temp.pop();
                }
                
                return next >= Integer.MAX_VALUE ? -1 : (int) next;
            }
            stack.push(digit);
        }
        return -1;
    }
}
```

#### Language used for code
Java

#### Expected behavior
My code shouldn't have passed the submission, but as you can see it passed in the screenshot and the submission link.
(https://leetcode.com/submissions/detail/422991770)

Missing testcase is
Input: 1343321
Output: 1421333
Expected: 1412333

#### Screenshots
![image](https://user-images.githubusercontent.com/9207404/99909259-f43cf500-2d19-11eb-9e39-3fe3f818395c.png)

**Comment by lc-kay** [comment]
Hi @ftku 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @ftku 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
