### ISSUE TITLE
Missing Test Case - 2462. Total Cost to Hire K Workers

### ISSUE THREAD

**Issue by Afk-Akash** [LeetCode-Feedback/LeetCode-Feedback#14391]
#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug
 Giving wrong output for a TC that is [10,10,10,10,1,1,1,12,12] , k = 3 and candidates = 2. 

#### Code you used for Submit/Run operation

```
//Total Cost to Hire K Workers
class Solution {
public:
    long long totalCost(vector<int>& costs, int k, int maxi) {
        priority_queue<int, vector<int>, greater<int>> forward, backward;
        int n = costs.size();

        int i = 0, j = n - 1;

        while( i <= j and maxi--){
            forward.push(costs[i]);
            if(i != j)
                backward.push(costs[j]);
            i++;
            j--;
        }
        long long ans = 0;

        while(k--){
            auto top1 = forward.size() ? abs(forward.top()) : INT_MAX;
            auto top2 = backward.size() ? abs(backward.top()) : INT_MAX;
            // cout<<top1<<" "<<top2<<endl;
            if(top1 <= top2){
                forward.pop();
                ans += top1;
                if(i <= j)forward.push(costs[i++]);
            }
            else{
                backward.pop();
                ans += top2;
                if(i <= j)backward.push(costs[j--]);
            }
            // cout<<top1<<" "<<top2<<" "<<ans<<endl;
        }

        return ans;
    }
};

```

#### Language used for code
C++

#### Expected behavior
for test case [10,10,10,10,1,1,1,12,12] , k = 3 and candidates = 2 expected output should be 25 since I will pick all workers from back side of array that is 12, 12 and 1 but compiler is giving 30 as answer 10,10,10 from front side and solution is also getting accepted.

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues and provide insights.

We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
