### ISSUE TITLE
Missing Test Case - 2462. Total Cost to Hire K Workers

### ISSUE THREAD

**Issue by bdpqchen** [LeetCode-Feedback/LeetCode-Feedback#14397]
#### Your LeetCode username

bdpqchen

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My code passed LeetCode all of testcases, but failed with this:
[4866,4857,4378,4876,3594,4874,4717,4680,4813,4938,4156,4724]
9
2

the bug caused by `while (i < j && q1.size() < candidates)` ,  
this should be `while (i <= j && q1.size() < candidates)`

#### Code you used for Submit/Run operation

```
long long totalCost(vector<int>& costs, int k, int candidates) {
        priority_queue<int, vector<int>, greater<>> q1, q2;
        long long ans = 0LL;
        int i = 0, j = costs.size() - 1;
        while (k--) {
            while (i < j && q1.size() < candidates)
                q1.push(costs[i++]);
            while (i <= j && q2.size() < candidates)
                q2.push(costs[j--]);
            if (q1.empty()) {
                ans += q2.top(); q2.pop();
            } else if (q2.empty()) {
                ans += q1.top(); q1.pop();
            } else if (q1.top() <= q2.top()) {
                ans += q1.top(); q1.pop();
            } else {
                ans += q2.top(); q2.pop();
            } 
        }    
        return ans;
}
```

#### Language used for code

C++

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by bdpqchen** [comment]
Hi, there is a submission https://leetcode.com/submissions/detail/980930371/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
