### ISSUE TITLE
Missing Test Case - 392. Is Subsequence

### ISSUE THREAD

**Issue by komugi-al** [LeetCode-Feedback/LeetCode-Feedback#14406]
#### Your LeetCode username

komugi3

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I passed the submission while hard coding a test case output value. Basically, the test checks for code that does not handle properly multiple correct characters within a subsequence. For example, if s="leet" and t="leeet", s is a substring of t but some algorithm would not detect it (like the one in my submission) because there are 3 'e's instead of 2.

#### Code you used for Submit/Run operation

```
// Is Subsequence
def isSubsequence(self, s: str, t: str) -> bool:
    if len(t) < len(s):
        return False
    u = "".join([i for i in t if i in s])
    return s in u or s == "leeeeetcode" and u == "leeeeeetcode"
```

#### Language used for code

Python3

#### Expected behavior

My submission should be rejected, the code doesn't work if we had a test that would more strictly check this case and I don't think hard coding a test value should work.

#### Additional context

The test that was not working without the hard coded value was the 17/18 (17th)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by komugi-al** [comment]
> Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
> 
> The code submission link.
> 
> We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

Here is a submission link: https://leetcode.com/problems/is-subsequence/submissions/981124696/

Thanks!

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
