### ISSUE TITLE
Missing Test Case - 938. Numbers At Most N Given Digit Set

### ISSUE THREAD

**Issue by sam0037** [LeetCode-Feedback/LeetCode-Feedback#1440]
#### Your LeetCode username
sam0037

#### Category of the bug
Solution

#### Description of the bug
The "Run Code" with a custom test case shows the wrong expected answer. 

#### Code you used for Submit/Run operation

```
class Solution {
    private int atMostNGivenDigitSetUtils(String[] digits, int n) {
        int nDigits = 1;
        int count = 0;
        while (Math.pow(10, nDigits) <= n) {
            ++nDigits;
        }
        int firstDigit = (int) (n/Math.pow(10, nDigits-1));
        for (String digit:digits) {
            if (Integer.parseInt(digit) < firstDigit) {
                count += Math.pow(digits.length, nDigits-1);
            } else if (Integer.parseInt(digit) == firstDigit) {
                int residual = n - (int) (firstDigit*Math.pow(10, nDigits-1));
                if (1 == nDigits) {
                    ++count;
                } else if (Math.pow(10,nDigits-2) <= residual) {
                    count += atMostNGivenDigitSetUtils(digits, residual);
                }
            }
        }
        return count;
    }

    public int atMostNGivenDigitSet(String[] digits, int n) {
        int nDigits = 1;
        int count = 0;
        while (Math.pow(10, nDigits) <= n) {
            count += (int) (Math.pow(digits.length, nDigits));
            ++nDigits;
        }

        return count + atMostNGivenDigitSetUtils(digits, n);
    }
}
```

#### Language used for code
Java

#### Expected behavior
For custom test case: 
["1","4","9", "6"]
703

I expected the result to be 68 while the "Expected answer" shown is 84 which is wrong. These are the 68 possible outcomes:

nDigits = 1, total = 4
1, 4, 9, 6

nDigits = 2, total = 16
11, 14, 19, 16
41, 44, 49, 46
91, 94, 99, 96
61, 64, 69, 66

nDigits = 3, total = 48
111, 114, 119, 116, 141, 144, 149, 146, 191, 194, 199, 196, 161, 164, 169, 166
411, 414, 419, 416, 441, 444, 449, 446, 491, 494, 499, 496, 461, 464, 469, 466
611, 614, 619, 616, 641, 644, 649, 646, 691, 694, 699, 696, 661, 664, 669, 666

count = 4 + 16 + 48 = 68

#### Screenshots

![image](https://user-images.githubusercontent.com/32717084/99909406-598ae900-2d0e-11eb-8943-3c7d0905ed31.png)

#### Additional context
Incase my analysis is wrong:
* Please do let me know
* The attached solution was accepted successfully. You may want to add this as a test case.
If my analysis is right then please restore my "green tick" as I missed my deadline due to this issue.

**Comment by lc-kay** [comment]
@sam0037 We have recently updated the test case validators for this problem and the test case you submitted now results in an invalid test case error. In addition, to make up for the late submission on this daily challenge, please redeem a Time Travel Ticket through https://leetcode.com/store/. Thank you for your time!
