### ISSUE TITLE
Missing Test Case - 373. Find K Pairs with Smallest Sums

### ISSUE THREAD

**Issue by VasisthaPrakhar** [LeetCode-Feedback/LeetCode-Feedback#14402]
#### Your LeetCode username
int_float_double

#### Category of the bug
Missing Test Cases (Problem with Judge's Reference Code)

#### Description of the bug
In my solution :-
```
for(int i=0;i<n;i++){
            for(int j=0;j<m;j++){
                ll sum=nums1[i]+nums2[j];
                if(pq.size()<k){
                    pq.push({sum,{nums1[i],nums2[j]}});
                }else if(sum<pq.top().first){
                    pq.pop();
                    pq.push({sum,{nums1[i],nums2[j]}});
                }else{
                    break;
                }
            }
        }
```
when i calculate the time complexity of my code i found that it is almost O(k*log(min(m,n,k)  + k)so it should work just fine for any testcase within constraint in your console as well but it doesn't it does not work for some large testcases and works just fine  on my machine with these test cases.
 
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/71345700/c81bb664-1f58-4c15-993c-4f5bde895883)

which indeed concludes that the Code used by judge is broken and must be updated for the following test case.
So, I generate simple testcase and run it using console (
[Sample_TestCase (2).txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/11885927/Sample_TestCase.2.txt)
).

It results in :
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/71345700/96e18335-018d-4e08-856d-1904bcab69f6)
So, I firmly believe that this testcase should be used for checking reference code so that it will not produce TLE

#### Code you used for Submit/Run operation

```
class Solution {
public:
    typedef long long int ll;
    vector<vector<int>> kSmallestPairs(vector<int>& nums1, vector<int>& nums2, int k) {
        vector<vector<int>>ans;
        int n=nums1.size();
        int m=nums2.size();
        priority_queue<pair<ll,pair<int,int>>>pq;
        for(int i=0;i<n;i++){
            for(int j=0;j<m;j++){
                ll sum=nums1[i]+nums2[j];
                if(pq.size()<k){
                    pq.push({sum,{nums1[i],nums2[j]}});
                }else if(sum<pq.top().first){
                    pq.pop();
                    pq.push({sum,{nums1[i],nums2[j]}});
                }else{
                    break;
                }
            }
        }
        while(!pq.empty()){
            ans.push_back({pq.top().second.first,pq.top().second.second});
            pq.pop();
        }
        reverse(ans.begin(),ans.end());
        return ans;
    }
};
```
Along with this solution code, I also used your most optimized code to check this test case and that code also gives TLE on Console

#### Language used for code
C++ 

#### Expected behavior
Solution was accepted, despite being not optimal

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/71345700/2b3579aa-ebe4-48a3-b591-c3e5f6695a02)

#### Additional context
I also used one of the most popular solutions from discuss they also give TLE for this testcase.
[Sample_TestCase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/11885786/Sample_TestCase.txt)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by yumkam** [comment]
Disclaimer: I'm just leetcode user.

If you add debug prints:
```
-    break;
+    cout << i << ' ' << j << '\n'; break;
```
you'll quickly notice that:
1) your testcase this is not worst case for your solution:
```
0 10000
1 0
2 0
....
99999 0
```
That is, inner loop is executed `k` times in the first iteration, and executed only once in all following `n - 1` iterations, and hence time complexity is O((k log k) + n).
2) actual worst case for your solution is:
```
[1,1,1,1,....,1]
[1,2,3,4,....,100000]
10000
```
and it gives
```
0 10000
1 5000
2 3333
....
9999 1
10000 0
....
99999 0
```
This not really bad either: inner loop executed `k/(i + 1)` times, hence time complexity O(n log k ln k). Not fastest, but still well within acceptable range.
So, why TLE? 
Let's take look at [my solution](https://leetcode.com/submissions/detail/981197567/).
It has only one loop, and easy to analyze: time complexity of `O(k * log min(n, m, k))` and space complexity of `O(min(n, m, k))`.
So, it should have no problem with anything within constraints (and even beyond them, up to 10^6).
Still, if you feed your testcase into my solution it will TLE in leetcode console too.
I've run your and mine code locally (linux, amd64, clang-11 with asan & ubsan enabled -- same environment as used by leetcode), and both your and mine code completes in 20-30ms and less than 10MB RSS.
I guess whatever code that is used by leetcode judge for result verification is just broken and TLE's on your testcase.

**Comment by VasisthaPrakhar** [comment]
Thanks @Yumkan for the elaborate explanation Actually i encountered the same issue my code with same test case works just fine on my machine but when I check it on leetcode console Console it gives TLE so i checked some codes from discuss and many of them had the same intuition as mine thatswhy I try to submit my code and it got accepted so i think may the testcase i used to check must be missing but as you mentioned its not missing testcase but the code used by judge which causes the issue 
PS: i am also gonna change this issue today as i finally got the time from work and calculate the time complexity for my solution which is not gonna cause any problem for any within constraint large testcase😅

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
