### ISSUE TITLE
Ruby key word as a parameter name - 1514. Path with Maximum Probability

### ISSUE THREAD

**Issue by lbvf50mobile** [LeetCode-Feedback/LeetCode-Feedback#14418]
#### Your LeetCode username
user9697N

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
At the problem's boilerplate code of method declaration the last parameter is a reserved Ruby keyword `end`. `end` in Ruby used to mark end of the code block.
`def max_probability(n, edges, succ_prob, start, end)`

From  the [Ruby documentation](https://docs.ruby-lang.org/en/2.2.0/keywords_rdoc.html):
> end
> The end of a syntax block. Used by classes, modules, methods, exception handling and control expressions.

#### Code you used for Submit/Run operation
I have to rename this parameter to `end1`, or may be it is better to rename it as `finish`, or `end_` it is up to your decision. But at the current moment the boilerplate code is not correct because of `end` keyword in the parameters list.

```Ruby
# @param {Integer} n
# @param {Integer[][]} edges
# @param {Float[]} succ_prob
# @param {Integer} start
# @param {Integer} end
# @return {Float}
def max_probability(n, edges, succ_prob, start, end1)
  # Based on:
  # https://leetcode.com/problems/path-with-maximum-probability/solution/
  mp = Array.new(n,0)
  mp[start] = 1
  (0...n-1).each do |i|
    hupd = 0
    (0...edges.size).each do |j|
      u,v = edges[j]
      pp = succ_prob[j]
      if mp[u] * pp > mp[v]
        mp[v] = mp[u] * pp
        hupd = 1
      end
      if mp[v] * pp > mp[u]
        mp[u] = mp[v] * pp
        hupd = 1
      end
    end
    break if 0 == hupd
  end
  return mp[end1]
end
```

#### Language used for code
Ruby

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
