### ISSUE TITLE
Missing Test Case - 1663. Smallest String With A Given Numeric Value

### ISSUE THREAD

**Issue by akshaymnair** [LeetCode-Feedback/LeetCode-Feedback#1441]
#### Your LeetCode username

akshay_nair

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

One of my submissions got accepted, but later on detail testing, I found out that there are some test cases missing.
The input are, 
1 <= n <= 10^5
n <= k <= 26 * n
but any combination of (n^0,k^n) gives wrong answer for this accepted code.  
for example: input (n=1, k=26), (n=2,k=52)..... (n=16,k=416) and so on.

#### Code you used for Submit/Run operation

```
num2 = (k-n) // 25
        num1 = n - num2 - 1
        num = k - (num1 + num2 * 26)
        return 'a' * num1 + chr(num+96) + 'z' * num2
```

#### Language used for code

Python

#### Expected behavior

There should be test cases of these combinations and the solution should not be accepted. 
test cases: (n=1, k=26), (n=2,k=52)

#### Screenshots

![image](https://user-images.githubusercontent.com/31191266/99911896-9924e700-2cb4-11eb-9ce5-7c9d56f5e3e9.png)

![image](https://user-images.githubusercontent.com/31191266/99911905-b0fc6b00-2cb4-11eb-884e-77fadb2bcd29.png)

**Comment by lc-kay** [comment]
@akshaymnair Please provide your code in [Playground ](https://leetcode.com/playground/new/empty) I am unable to result in an Accepted answer from the code provided above.

**Comment by lc-kay** [comment]
Hi @akshaymnair  ,
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
