### ISSUE TITLE
25. Reverse Nodes in k-Group | Iterative solution can be simplified from 83 to 35 lines.

### ISSUE THREAD

**Issue by davitescobedo** [LeetCode-Feedback/LeetCode-Feedback#14420]
#### Your LeetCode username

eldavimost

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The solution 2 iterative can be simplified in fewer lines and way easier to read code.
prevG and headG mean previousGroup and headOfTheGroup

#### Code you used for Submit/Run operation

```
class Solution {
  public ListNode reverseKGroup(ListNode head, int k) {
    ListNode dummyheadG = new ListNode(0, head);
    ListNode prevG = dummyheadG;
    ListNode prev = dummyheadG;
    ListNode cur = dummyheadG.next;
    while (true) {
      ListNode headG = prevG;
      for (int i = 0; i < k && headG != null; i++) {
        headG = headG.next;
      }
      if (headG == null) {
        return dummyheadG.next;
      }
      ListNode nextG = headG.next;
      ListNode tail = cur;
      headG = reverse(cur, k);
      prevG.next = headG;
      cur.next = nextG;
      prevG = cur;
      cur = nextG;
    }
  }

  private ListNode reverse(ListNode node, int k) {
    ListNode prev = null;
    while (k-- > 0) {
      ListNode next = node.next;
      node.next = prev;
      prev = node;
      node = next;
    }
    return prev;
  }
}
```

#### Language used for code

Java

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
