### ISSUE TITLE
Max Consecutive Ones

### ISSUE THREAD

**Issue by PrayagSangani** [LeetCode-Feedback/LeetCode-Feedback#1442]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@PrayagSangani Please provide the issue and the code that you ran into this issue with. Thank you for your time and support!

**Comment by lc-kay** [comment]
Hi @PrayagSangani  ,
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
