### ISSUE TITLE
Problem 1757

### ISSUE THREAD

**Issue by MuneebGulzar** [LeetCode-Feedback/LeetCode-Feedback#14427]
I think the solution of the problem is:

SELECT 
	product_id
FROM 
	Products
WHERE 
	low_fats = 'Y' AND recyclable = 'Y';

But I keep getting the runtime error.
I have tried to run a basic query like select product_id from products but get the same error which me think that the issue isn´t from my side.

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
