### ISSUE TITLE
Missing Test Case - 864. Shortest Path to Get All Keys

### ISSUE THREAD

**Issue by G-Jeffrey** [LeetCode-Feedback/LeetCode-Feedback#14421]
#### Your LeetCode username

Jeffreyg2240

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

It is not specifically said that we only have one starting point, and the question runs with multiple starting points, marking the last one as it traverses. The solution test cases don't check the test case for multiple starting points.

#### Code you used for Submit/Run operation
[User Wangzi6147''s solution
](https://leetcode.com/problems/shortest-path-to-get-all-keys/solutions/146878/java-bfs-solution/)

```
// Two Sum
class Solution {
    class State {
        int keys, i, j;
        State(int keys, int i, int j) {
            this.keys = keys;
            this.i = i;
            this.j = j;
        }
    }
    public int shortestPathAllKeys(String[] grid) {
        int x = -1, y = -1, m = grid.length, n = grid[0].length(), max = -1;
        for (int i = 0; i < m; i++) {
            for (int j = 0; j < n; j++) {
                char c = grid[i].charAt(j);
                if (c == '@') {
                    x = i;
                    y = j;
                }
                if (c >= 'a' && c <= 'f') {
                    max = Math.max(c - 'a' + 1, max);
                }
            }
        }
        State start = new State(0, x, y);
        Queue<State> q = new LinkedList<>();
        Set<String> visited = new HashSet<>();
        visited.add(0 + " " + x + " " + y);
        q.offer(start);
        int[][] dirs = new int[][]{{0, 1}, {1, 0}, {0, -1}, {-1, 0}};
        int step = 0;
        while (!q.isEmpty()) {
            int size = q.size();
            while (size-- > 0) {
                State cur = q.poll();
                if (cur.keys == (1 << max) - 1) {
                    return step;
                }
                for (int[] dir : dirs) {
                    int i = cur.i + dir[0];
                    int j = cur.j + dir[1];
                    int keys = cur.keys;
                    if (i >= 0 && i < m && j >= 0 && j < n) {
                        char c = grid[i].charAt(j);
                        if (c == '#') {
                            continue;
                        }
                        if (c >= 'a' && c <= 'f') {
                            keys |= 1 << (c - 'a');
                        }
                        if (c >= 'A' && c <= 'F' && ((keys >> (c - 'A')) & 1) == 0) {
                            continue;
                        }
                        if (!visited.contains(keys + " " + i + " " + j)) {
                            visited.add(keys + " " + i + " " + j);
                            q.offer(new State(keys, i, j));
                        }
                    }
                }
            }
            step++;
        }
        return -1;
    }
}
```

#### Expected behavior

We are able to have multiple starting points, the starting points are treated as a wall.

#### Screenshots

![Treating startiing point as a wall](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/77083235/24a15e00-f99c-4f0d-8747-2d7e70d5d5ff)
![Starting at (0,0) leads to the solution of 8, rather than 9, given by (1,4)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/77083235/8c157750-9fe8-4be2-a4c0-8af94686553c)

**Comment by jorisperrenet** [comment]
I ([JorisPerrenet](https://leetcode.com/JorisPerrenet/)) also discovered this, the test cases `["@A",".#","@a"]` and `["@a",".#","@A"]` should, logically, return the same answer. However, they return 3 and 1, respectively. Either a check must be added to only allow for a single starting position or the larger/smaller answer should be chosen.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
