### ISSUE TITLE
Missing Test Case - 162. Find Peak Element

### ISSUE THREAD

**Issue by Kr-Shanu** [LeetCode-Feedback/LeetCode-Feedback#14433]
#### Your LeetCode username

[codewith_shanu](https://leetcode.com/codewith_shanu/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

We need to find the peak element in an array:
[Find Peak Element](https://leetcode.com/problems/find-peak-element/)
we are supposed to find the largest element in the array given,
- I tried to apply the binary search algorithm,
- Using my code, all the test cases passed, but
- When i gave a sample test case from my side then I got a wrong value but then too it shows correct solution.
- Output comes out to be: 2
- Expected output is : 0,
- Then too my solution gives me a correct value.

#### Code you used for Submit/Run operation

```
// Find Peak Element
class Solution {
    public int findPeakElement(int[] nums) {
        
        int l = 0, r = nums.length-1, ans = 0, mid = 0;

        while(l <= r) {

            mid = (l+r)/2;
            int val = nums[mid];

            if(mid+1 < nums.length && val > nums[mid+1]) {
                ans = mid;
                r = mid-1;
            }
            else if(mid == nums.length-1) return mid;
            else l = mid+1;
        }
        return ans;
    }
}
```

#### Language used for code

JAVA

#### Expected behavior

- When running with sample test case [5, 1, 3], it should give the index of the highest value 5 i.e. 0
- But the answer that my code returns is 3, i.e. index number 2
- Then too my code gets accepted.

#### Screenshots

<img width="1704" alt="Screenshot 2023-06-29 at 7 51 45 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/80747792/d2ea89ca-8362-47fb-a232-1602beac51d9">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Kr-Shanu** [comment]
Sure @LC-Pam in the following program, for the test case :
[5, 1, 3] : the answer that is expected is 0, the index of 5,

My code gave the output as 2 and it was also accepted, as you can see in the screenshot.

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
