### ISSUE TITLE
Editorial typos - 1970. Last Day Where You Can Still Cross

### ISSUE THREAD

**Issue by xelplogoog** [LeetCode-Feedback/LeetCode-Feedback#14439]
#### Your LeetCode username
c4tdog

#### Description of the bug
https://leetcode.com/problems/last-day-where-you-can-still-cross/editorial/
There are typos in words `top row` and `approach`

Should be `top row`
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2188302/99489ee2-f400-43d9-9af3-17bab7128bd5)

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2188302/6a2fcc5f-e0a0-499c-b62c-09a26efe050d)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
