### ISSUE TITLE
Missing Test Case - 1665. Minimum Initial Energy to Finish Tasks

### ISSUE THREAD

**Issue by NanShi-rl** [LeetCode-Feedback/LeetCode-Feedback#1443]
#### Your LeetCode username
shinan88888

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language

#### Description of the bug
I tried an O(n) approach and got accepted, but it is a wrong answer. It takes minimum difference between requirement and actual, added to the sum of all actuals. Then compare with the maximum requirement.

#### Code you used for Submit/Run operation

```
// Minimum Initial Energy to Finish Tasks
class Solution(object):
    def minimumEffort(self, tasks):
        """
        :type tasks: List[List[int]]
        :rtype: int
        """
        min_diff = min([x[1] - x[0] for x in tasks])  # min diff of requirement and actual
        sum_actual = sum([x[0] for x in tasks])  # sum of all actual
        max_requirement = max([x[1] for x in tasks])  # max of requirement
        return max(min_diff + sum_actual, max_requirement)
```

#### Language used for code

Python

#### Expected behavior

Test Case:
Input:
[[1, 10], [2, 10], [5, 7]]
Output:
10
Expected:
11

**Comment by VasE1980** [comment]
the same https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/1429#issuecomment-731716179

**Comment by lc-kay** [comment]
@NanShi-rl I just ran your code and it resulted in Runtime Error. Please note that we recently updated the test case set for this problem, therefore, a previously accepted answer may result in an error now. Please check your code again and let me know if it is still a valid issue, then I will reopen this issue and further investigate.

**Comment by NanShi-rl** [comment]
@lc-kay  I have tested it and the updated test cases have resolved the issue. Thanks.
