### ISSUE TITLE
Missing Test Case - 214. Shortest Palindrome

### ISSUE THREAD

**Issue by zitsav** [LeetCode-Feedback/LeetCode-Feedback#14435]
#### Your LeetCode username

zitsav

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug

The constraints of the problem are as
0 <= s.length <= 5 * 10^4
So, an algorithm with a time complexity of O(n^2) should not work on this approach and should give TLE with the given constraints. However, due to weak constraints even an algorithm of O(n^2) is being accepted, when the algorithm should have further optimisations.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    string shortestPalindrome(string s) {
		int len = s.length();
		if (len < 2)
			return s;
		int longest = 1, start, end;
		for (int begin = 0; begin <= len / 2;) {
			start = end = begin;
			while (end < len - 1 && s[end + 1] == s[end])
				++end;
			begin = end + 1;
			while (end < len - 1 && start > 0 && s[end + 1] == s[start - 1]) {
				++end;
				--start;
			}
			if (start == 0 && longest < end - start + 1)
				longest = end - start + 1;
		}
		string remaining = s.substr(longest, len - longest);
		reverse(remaining.begin(), remaining.end());
		return remaining + s;
    }
};
```

#### Language used for code

C++ 

#### Expected behavior

This algorithm was able to pass all test cases despite being an O(n^2) algorithm. This shouldn't be the case given the constraints.

#### Test Case for TLE in O(n^2) algorithms

[output.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/11908781/output.txt)

#### Screenshot
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/95949906/5f173f74-f702-4dde-90cf-876c5b7bb502)

#### Correct O(n) Solution

```
class Solution {
public:
    string shortestPalindrome(string s) {
        string p = s;
        reverse(s.begin(), s.end());
        p = p + "#" + s;
        int n = p.size();
        vector<int> lps(p.size());
        lps[0] = 0;
        int len = 0;
        int i = 1;
        while (i < n) {
            if (p[i] == p[len]) {
                len++;
                lps[i] = len;
                i++;
            }
            else {
                if (len != 0) {
                    len = lps[len - 1];
                }
                else {
                    lps[i] = 0;
                    i++;
                }
            }
        }
        int k = *max_element(lps.begin(), lps.end());
        for (int i = 0; i<lps.size(); i++){
            if (lps[i] >= k){
                k = lps[i];
            }
        }
        cout<<k<<endl;
        int m = s.size();
        string ans;
        for(int i=m-1;i>=lps[n-1];i--){
            ans+=p[i];
        }
        reverse(s.begin(), s.end());
        ans += s;
        return ans;
    }
};
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
