### ISSUE TITLE
Missing Test Case - 7. Reverse Integer

### ISSUE THREAD

**Issue by spect-apple** [LeetCode-Feedback/LeetCode-Feedback#14431]
#### Your LeetCode username
spect_apple

#### Category of the bug

- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution {
    public int reverse(int x) {
        int sum=0;
        String temp=Integer.toString(x);
        while(x!=0)
        {
            sum=sum*10+x%10;
            x/=10;
        }
        if(Character.getNumericValue(temp.charAt(temp.charAt(0)=='-'?1:0))==Math.abs(sum%10))
        return sum;
        return 0;
    }
}
```

#### Language used for code
Java

#### Expected behavior

In this program a specific condition or logic should be used to check the whether the reversed num is in 32-bit Integer range, So that is returns the value 0 if the reversed number is out of the 32-bit Integer range. But in my code I didn't use a logic to check the range. To check whether the value is out of this range, I can declare the reverse variable(sum in my program) as a long type. But, I declared it(sum) only as an Int type variable. And so, when the parameter of the function is reversed(and out of range) it gives an Overflow or Underflow value(based on the sign). And with this value, I checked whether the first digit of the parameter( assigned to temp variable) is equal to the last digit of the reversed value(sum) to return the reversed value if the condition is true, else it returns 0. This condtion in my program passes all the test cases, which it should'nt. Some test cases such as 1147483648,1137464807,1235466808,1221567417(missing test cases) are not passed by my code. My program is not fully correct but still it passes all the given test cases. So, I think it would be better to add these missing test cases [1147483648,1137464807,1235466808,1221567417].

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/128618648/5924b68e-1360-4559-9649-c4994077d686)

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/128618648/d63804f0-fb14-4452-b78a-5ff95c1d545d)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by spect-apple** [comment]
Thank you for your time and action.
Appreciate it. : )
