### ISSUE TITLE
题目 2490.回环句

### ISSUE THREAD

**Issue by Sensente** [LeetCode-Feedback/LeetCode-Feedback#14440]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
Sensente

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
题目题面描述小错误。示例2解释中「- eetcod*e* 的最后一个字符和 eetcod*e*的第一个字符相等。」斜体标错了位置。示例3解释中「- Leetcod*e* 的最后一个字符和 i*s* 的第一个字符 不 相等。」的is单词标错了强调斜体位置，应该改为*i*s. 

**你使用的语言**
C++

**你提交或者运行的代码**
```
class Solution {
public:
    bool isCircularSentence(string sentence) {
        int len = sentence.length();
        for(int i = 0; i < len; i++) {
            if(sentence[i] == ' ') {
                if(sentence[i - 1] != sentence[i + 1]) return false;
            }
        }
        return sentence[0] == sentence[len - 1] ? true : false;
        
    }
};
```

**期望行为**
将题目示例2中第二个eetcod*e*改为*e*etcode.
将题面示例3描述的 i*s* 改为*i*s.

**屏幕截图**

<img width="518" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/35966153/bdb95395-c1ce-41a9-b11f-04facb5dc03e">

**额外的上下文**
无

**Comment by Sensente** [comment]
请注意，示例2的文本中亦存在上述问题。

**Comment by feiceh** [comment]
感谢反馈，当前题目已更新，奖励已发放。
