### ISSUE TITLE
Missing Test Case - 3. Longest Substring Without Repeating Characters

### ISSUE THREAD

**Issue by aysusayin** [LeetCode-Feedback/LeetCode-Feedback#1444]
#### Your LeetCode username
aysusayin

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Test case with input "abcdeefaage" does not return any value. However it should return 5.

#### Code you used for Submit/Run operation
```
class Solution:
    def lengthOfLongestSubstring(self, s: str) -> int:
        if not s: return 0
        
        char_ind_map = dict()
        ind_list = []
        last_non = -1
        for i, c in enumerate(s):
            if c in char_ind_map:
                ind_list.append(max(char_ind_map[c],last_non)) 
                last_non = ind_list[-1]
            else:
                ind_list.append(max(-1, last_non))
            char_ind_map[c] = i
            
        return max(i - ind_list[i] for i in range(len(ind_list)))
```

#### Language used for code
Python3

#### Expected behavior
My code passes all test cases. When I enter my custom test case "abcdeefaage", my code returns 5 but the expected answer is empty. The solution code must also return 5.

#### Screenshots
<img width="1440" alt="Ekran Resmi 2020-11-22 23 57 40" src="https://user-images.githubusercontent.com/23139429/99919572-834c0c00-2d1e-11eb-8818-4161afa28f32.png">

**Comment by lc-kay** [comment]
@aysusayin The code and test case you submitted were both accepted on the problem details page. 
<img width="1433" alt="Screen Shot 2020-11-25 at 12 01 37 PM" src="https://user-images.githubusercontent.com/70870126/100276263-2155f700-2f16-11eb-9aab-3872b7155dc5.png">
Can you please provide the link to the Explore Card that this issue occurred in?

**Comment by aysusayin** [comment]
It looks like problem is fixed. Thank you!
