### ISSUE TITLE
Missing Test Case - 424. Longest Repeating Character Replacement

### ISSUE THREAD

**Issue by YamabikoYen** [LeetCode-Feedback/LeetCode-Feedback#14449]
#### Your LeetCode username

dennis22243148

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

There are wrong solutions being accepted. The code in the following section was accepted. However, the code is not actually correct. In the line `res = max(res, k + char_count[s[l]])` the code only checks the Longest Repeating Character array using the left-most character in a sliding window. It should use the most frequent character instead.
Test case s = "ABCDDD", k = 3 can catch this incorrect solution. 

#### Code you used for Submit/Run operation

```
// 424. Longest Repeating Character Replacement
class Solution:
    def characterReplacement(self, s: str, k: int) -> int:
        res, l = 0, 0
        char_count = {}
        for r in range(len(s)):
            char_count[s[r]] = char_count.get(s[r], 0) + 1
            while r - l + 1 - char_count[s[l]] > k:
                char_count[s[l]] -= 1
                l += 1
            res = max(res, k + char_count[s[l]])
        return min(res, len(s))
```

#### Language used for code

Python

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
