### ISSUE TITLE
67 add binary constraints and test cases miss matched

### ISSUE THREAD

**Issue by Kenzku** [LeetCode-Feedback/LeetCode-Feedback#14445]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

the length of a and b shall be less or equal than 10^4
but there are test cases proving a and b longer than this range

#### Code you used for Submit/Run operation
```
var addBinary = function(a, b) {
  let num1 = parseInt(a, 2)
  let num2 = parseInt(b, 2)

  return (num1+num2).toString(2)
};
```

#### Language used for code

javascript

#### Screenshots

<img width="1482" alt="Screenshot 2023-06-30 at 11 14 02" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/1387249/8f702a6c-6c6d-4786-bbef-79ca3f5ba570">

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
