### ISSUE TITLE
Missing Test Case - 1662. Check If Two String Arrays are Equivalent

### ISSUE THREAD

**Issue by xupiter** [LeetCode-Feedback/LeetCode-Feedback#1445]
#### Your LeetCode username
xupiter007

#### Category of the bug
- [ ] Question
- [ +] Solution
- [ ] Language

#### Description of the bug
Wrong solutions get accepted due to a missing test case.

#### Code you used for Submit/Run operation
```
    def arrayStringsAreEqual(self, word1: List[str], word2: List[str]) -> bool:
        list1 = list2 = idx1 = idx2 = 0
        while list1 < len(word1) and list2 < len(word2):
            if word1[list1][idx1] == word2[list2][idx2]:
                idx1 += 1
                idx2 += 1
                if idx1 == len(word1[list1]):
                    idx1 = 0
                    list1 += 1
                if idx2 == len(word2[list2]):
                    idx2 = 0
                    list2 += 1
            else:
                return False
        return True
```

#### Language used for code
Python3

#### Expected behavior
Test Case:
Input:
["abc", "d", "defg"]
["abcddef"]
Output: true
Expected: false

#### Screenshots
![image](https://user-images.githubusercontent.com/9909951/99921129-3b58c500-2cdd-11eb-9e71-763aac9cb47d.png)

#### Additional context
Run shows "Wrong Answer", but "Submit" shows "Accepted"

**Comment by lc-kay** [comment]
Hi @xupiter 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @xupiter 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
