### ISSUE TITLE
Incorrect Solution, Python, 49. Group Anagrams

### ISSUE THREAD

**Issue by KANNAHWORLD** [LeetCode-Feedback/LeetCode-Feedback#14455]
#### Your LeetCode username
bansalsi

#### Category of the bug
Approach 2, Python solution is wrong

#### Description of the bug
Code has the function definition
    ```def groupAnagrams(strs):```
even though the correct definition should be 
    ```def groupAnagrams(self, strs):```

#### Language used for code
Python

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
