### ISSUE TITLE
597. 好友申请 I：总体通过率 MySQL 提交提示表不存在

### ISSUE THREAD

**Issue by mantoufan** [LeetCode-Feedback/LeetCode-Feedback#14462]
**你的 LeetCode 用户名**
mantoufan

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
[597. 好友申请 I：总体通过率](https://leetcode.cn/problems/friend-requests-i-overall-acceptance-rate/description/) 题目用 `MySQL` 代码提交，提示:
>Table 'test.friend_request' doesn't exist
和
> Table 'test.request_accepted' doesn't exist

**你使用的语言**
MySQL

**你提交或者运行的代码**
代码来自[官方题解](https://leetcode.cn/problems/friend-requests-i-overall-acceptance-rate/solutions/22764/hao-you-shen-qing-izong-ti-tong-guo-lu-by-leetcode/)
```sql
select
round(
    ifnull(
    (select count(*) from (select distinct requester_id, accepter_id from request_accepted) as A)
    /
    (select count(*) from (select distinct sender_id, send_to_id from friend_request) as B),
    0)
, 2) as accept_rate;
```
**屏幕截图**
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/4961543/2539b84a-0bf4-440a-b467-0d81b8286d41)

**Comment by feiceh** [comment]
你好，在与相关团队核实后：官方题解会进行调整。建议用户修改 sql 中的表名使与题面一致。 
以上反馈奖励已发放，感谢您的反馈和支持。
