### ISSUE TITLE
Correct Code is giving Syntax error

### ISSUE THREAD

**Issue by dubeyx** [LeetCode-Feedback/LeetCode-Feedback#14463]
#### Category of the bug
- [ 2574] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
I have tried correct solution in differnt languages but none of them is being accepted

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<int> leftRigthDifference(vector<int>& nums) {
        vector<int> lsum, res;
        int total = 0;
        
        int n = nums.size();
        int sum = 0;
        for(int i = 0; i<n; i++){
            lsum.push_back(sum);
            sum += nums[i];
            total +=nums[i];
        }

        sum = 0;
        vector<int> rsum(n, 0);
        for(int i = n-1; i>=0; i--){
            rsum[i] = sum;
            sum +=nums[i];
        }
        
        for(int i = 0; i<n; i++){
            res.push_back(abs(lsum[i]-rsum[i]));
        }
        
        return res;
    }
};
```

#### Expected behavior

It should be accepted as logic is 100% correct no solution is giving output even.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/94775233/bc296922-0f43-4db4-9019-ddd009f905ce)

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
