### ISSUE TITLE
Use Vec<u8> instead of String for serialization - 297. Serialize and Deserialize Binary Tree

### ISSUE THREAD

**Issue by bcc32** [LeetCode-Feedback/LeetCode-Feedback#14460]
#### Your LeetCode username
bcc32

#### Category of the bug
- [x] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
Using `String` as a serialization target type for Rust doesn't make sense.  `String` is restricted to valid UTF-8 byte strings, which limits the flexibility of the (presumably) binary protocol one might want to implement.  This problem should use `Vec<u8>` instead, which directly represents byte sequences.

#### Code you used for Submit/Run operation

Not applicable

#### Language used for code
Rust

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

We used the same type for all languages.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by bcc32** [comment]
Thank you for your consideration.  Unfortunately, I think the team misunderstands the issue.  "String" does not refer to the same type in different languages.  In Java, for example, Strings are sequences of UTF-16 characters, while in C++, they are system-dependent "native chars", and in Golang they are arbitrary byte sequences.  If not for the choice of "string" as the return type, the same binary protocol could be implemented in all of the languages I mentioned---just because "string" is called the same name in different programming languages does not mean it refers to the same type!

I would appreciate if you reconsidered, but if not, thanks anyway.
