### ISSUE TITLE
4sum

### ISSUE THREAD

**Issue by dubeynavneet** [LeetCode-Feedback/LeetCode-Feedback#14468]
#### Your LeetCode username
navneetdubey2002

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Full description of each test case is not provided like in 4 sum problem what to return if given vector does have length less than 4 than not clear what should be returned in c++

#### Code you used for Submit/Run operation

```
// 4 Sum
class Solution {
public:
    vector<vector<int>> fourSum(vector<int>& nums, int target) {
        sort(nums.begin(),nums.end());
        vector<vector<int>> ans;
        for(int i = 0;i<nums.size() - 3; i++){
            if(i>0&&nums[i-1]==nums[i]) continue;
            for(int j = i + 1; j<nums.size()- 2; j++){
                if(j>i+1&&nums[j]==nums[j-1]) continue;
                int k = j + 1;
                int l=nums.size() - 1;
                while(k<l){
                    long long res = nums[i];
                    res=res+nums[j];
                    res=res+nums[k];
                    res=res+nums[l];
                    if(res==target){
                        vector<int> temp={nums[i],nums[j],nums[k],nums[l]};
                        ans.push_back(temp);
                        k++;
                        l--;
                        while(k < l && nums[k-1]==nums[k]) k++;
                        while(k < l && nums[l+1]==nums[l]) l--;
                    }else if(res > target){
                        l--;
                    }else{
                        k++;
                    }
                }
            }
        }
        return ans;
    }
};
```

#### Expected behavior
Full description should be provided if no quadruple is formed

#### Screenshots

![4Sum - LeetCode - Google Chrome 01-07-2023 18_49_17](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/89724349/0bdfe9a4-0cc2-47e5-a159-a4345c810531)

#### Additional context

nums =
[0]
target =
0
no output is cleared as target can also be formed

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
