### ISSUE TITLE
Missing Test Case - 1662. Check If Two String Arrays are Equivalent

### ISSUE THREAD

**Issue by idanhuang** [LeetCode-Feedback/LeetCode-Feedback#1446]
#### Your LeetCode username
newbiecoder1

#### Category of the bug
- [ ] Question
- [ X] Solution
- [ ] Language

#### Description of the bug
OJ passed my solution, which should fail the below test case.
["ab", "c"]
["a", "bcd"]

#### Code you used for Submit/Run operation
```
public class Solution {
    public bool ArrayStringsAreEqual(string[] word1, string[] word2) {
        
        int w1 = 0, w2 = 0, c1 = 0, c2 = 0;
        
        while(w1 < word1.Length && w2 < word2.Length)
        {
            if(word1[w1][c1] != word2[w2][c2])
                return false;
            
            if(c1 == word1[w1].Length - 1)
            {
                w1++;
                c1 = 0;
            }
            else
                c1++;
            
            if(c2 == word2[w2].Length - 1)
            {
                w2++;
                c2 = 0;
            }
            else
                c2++;
        }
        
        return true;
    }
}
```

**Comment by lc-kay** [comment]
Hi @idanhuang 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @idanhuang 
Thank you for your time. We've recently updated the test case for this problem, and now, the code you submitted results in a wrong answer.
