### ISSUE TITLE
Missing Test Case - 1665. Minimum Initial Energy to Finish Tasks

### ISSUE THREAD

**Issue by prinzuchoudhury** [LeetCode-Feedback/LeetCode-Feedback#1447]
#### Category of the bug
- [ ] Question
-  Solution
- [ ] Language

#### Description of the bug -
My solution passes all test cases, but it should fail for the input - 
[[2,30],[2,30],[2,30],[2,30],[2,30],[2,30],[2,30],[2,30],[2,30],[2,30],[2,30],[2,30],[2,30],[2,30],[2,3]].   
The answer is 56, but my answer is 31.  So, this test cases must be added.

#### Code used for Submit/Run operation

```
class Solution {
public:
    int minimumEffort(vector<vector<int>>& t) {
        int s=INT_MAX,sum=0,p=1;
        for(auto c:t) {
            s=min(s,c[1]-c[0]);
            sum+=c[0];
            p=max(p,c[1]);
        }
        
        return max(s+sum,p);
        

    }
};
```

#### Expected behavior

My answer is wrong, but still it passes all possible test cases. 

#### Screenshots

![Capture](https://user-images.githubusercontent.com/31660064/99954571-fe5a0480-2da8-11eb-8836-099885667d2d.PNG)

**Comment by lc-kay** [comment]
@prinzuchoudhury After reviewing your code, it resulted in a wrong answer. Please let me know if it is still accepted on your end. If yes, I will reopen this issue and further investigate it. Thank you for your time!
