### ISSUE TITLE
Update Test Case - 2305. Fair Distribution of Cookies

### ISSUE THREAD

**Issue by AyushPatel454** [LeetCode-Feedback/LeetCode-Feedback#14474]
#### Your LeetCode username
aayushpatel25190
[aayushpatel25190](https://leetcode.com/aayushpatel25190/)

#### Category of the bug
- [ ] Solution
- [ ] Update Test Cases 

#### Description of the bug

There is a one Test case which generate wrong output and my code is not submitted because testcase output is wrong.
Test Case Number is 34/38
Input
cookies =
[15,18,19,5,6,13,15,20]
k =
3
Output:
38 <----------- Not correct. 
Correct output is 39.

#### Code you used for Submit/Run operation

```
class Solution {
    public int distributeCookies(int[] cookies, int k) {
        int ans = Integer.MIN_VALUE;
        int sum = 0;
        ArrayList<Integer> lst = new ArrayList<>();
        // int min = Integer.MAX_VALUE;

        // find total chocolate.
        for (int i = 0; i < cookies.length; i++) {
            lst.add(cookies[i]);
            // min = Math.min(min, cookies[i]);
            sum += cookies[i];
        }
        // sort arrayList
        Collections.sort(lst);
        // System.out.println("Sum = "+sum);

        int need = sum / k;
        // System.out.println("Need = "+need);


        for (int i = 0; i < k; i++) {
            // System.out.println("K = "+(i+1));
            if(lst.isEmpty()) {
                break;
            }
            int gain = lst.get(lst.size()-1);
            // System.out.print(gain + " ");
            lst.remove(lst.size()-1);
            if(gain >= need) {
                ans = Math.max(ans, gain);
                // System.out.println("\nGain = "+gain);
                continue;
            }
            int diff = Math.abs(need - gain);
            while(gain < need) {
                int idx = -1;
                for (int j = 0; j < lst.size(); j++) {
                    int val = lst.get(j);
                    // add
                    int addDiff = Math.abs(need - (gain+val));
                    if(addDiff <= diff) {
                        idx = j;
                        diff = addDiff;
                    }
                }
                if(idx != -1) {
                    gain += lst.get(idx);
                    // System.out.print(lst.get(idx) + " ");
                    lst.remove(idx);
                } else {
                    break;
                }
            }
            // System.out.println("\nK = "+(i+1)+" Ans = "+gain);
            ans = Math.max(ans, gain);
        }
        
        return ans;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Below test case output is wrong.
Test Case Number is 34/38
Input
cookies =
[15,18,19,5,6,13,15,20]
k =
3
Output:
38 <----------- Not correct. 
Correct output is: 39

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
