### ISSUE TITLE
Missing Test Case - 1251. Average Selling Price

### ISSUE THREAD

**Issue by vrutik2809** [LeetCode-Feedback/LeetCode-Feedback#14478]
#### Your LeetCode username

vrutik2809

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Consider the following test case:
Prices:
| product_id | start_date | end_date   | price |
| ---------- | ---------- | ---------- | ----- |
| 1          | 2019-02-17 | 2019-02-28 | 5     |
| 1          | 2019-03-01 | 2019-03-22 | 20    |
| 2          | 2019-02-01 | 2019-02-20 | 15    |
| 2          | 2019-02-21 | 2019-03-31 | 30    |
| 3          | 2019-02-21 | 2019-03-31 | 30    |

UnitsSold:
| product_id | purchase_date | units |
| ---------- | ------------- | ----- |
| 1          | 2019-02-25    | 100   |
| 1          | 2019-03-01    | 15    |
| 2          | 2019-02-10    | 200   |
| 2          | 2019-03-22    | 30    |

Now, consider the following `MySQL` code:
#### Code you used for Submit/Run operation
```sql
select p.product_id,round(sum(p.price * u.units) / sum(u.units),2) as average_price 
from prices as p left join unitssold as u 
on p.product_id = u.product_id and (u.purchase_date between p.start_date and p.end_date)
group by p.product_id;
```
The above code is accepted on submitting, but while doing custom testing using the above-mentioned test case, it is giving the wrong answer (screenshots attached below)
This should not happen. Hence the above-mentioned edge case is missing.

#### Language used for code

MySQL

#### Expected behavior

The given code should not get accepted

#### Screenshots

Screenshot of wrong answer while custom testing:
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/74986666/41ce9707-96bd-4b42-8528-5d55976873f0)

Screenshot of accepted while submitting
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/74986666/75239e52-2810-4d08-953e-62ba36cc9946)

#### Additional context

The correct code handling the above-mentioned edge case:
```sql
select p.product_id, (
  case
    when count(p.product_id) = 1 then if(u.units is null,0,p.price)
    else round(sum(p.price * u.units) / sum(u.units),2) # aggregate function by default ignore null values
  end
) as average_price
from prices as p left join unitssold as u
on p.product_id = u.product_id and (u.purchase_date between p.start_date and p.end_date)
group by p.product_id;
```

**Comment by BhaveshJain1947** [comment]
Great

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The test case in JSON format: {"headers":{"Prices":["product_id","start_date","end_date","price"],"UnitsSold":["product_id","purchase_date","units"]},"rows":{"Prices":[[1,"2019-02-17","2019-02-28",5],[1,"2019-03-01","2019-03-22",20],[2,"2019-02-01","2019-02-20",15],[2,"2019-02-21","2019-03-31",30]],"UnitsSold":[[1,"2019-02-25",100],[1,"2019-03-01",15],[2,"2019-02-10",200],[2,"2019-03-22",30]]}}

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by vrutik2809** [comment]
@LC-Pam 

Here is the test case in the provided json format:
```json
{
    "headers": {
        "Prices": [
            "product_id",
            "start_date",
            "end_date",
            "price"
        ],
        "UnitsSold": [
            "product_id",
            "purchase_date",
            "units"
        ]
    },
    "rows": {
        "Prices": [
            [
                1,
                "2019-02-17",
                "2019-02-28",
                5
            ],
            [
                1,
                "2019-03-01",
                "2019-03-22",
                20
            ],
            [
                2,
                "2019-02-01",
                "2019-02-20",
                15
            ],
            [
                2,
                "2019-02-21",
                "2019-03-31",
                30
            ],
            [
                3,
                "2019-02-21",
                "2019-03-31",
                30
            ]
        ],
        "UnitsSold": [
            [
                1,
                "2019-02-25",
                100
            ],
            [
                1,
                "2019-03-01",
                15
            ],
            [
                2,
                "2019-02-10",
                200
            ],
            [
                2,
                "2019-03-22",
                30
            ]
        ]
    }
}
```
Let me know if you face any issue with test case format
