### ISSUE TITLE
best-time-to-buy-and-sell-stock-iv DP Solution base case condition can be more concise

### ISSUE THREAD

**Issue by bhushanvbr** [LeetCode-Feedback/LeetCode-Feedback#14477]
#### Your LeetCode username

bhushanvbr

#### Category of the bug
- Solution

#### Description of the bug

DP Solution for the problem "best-time-to-buy-and-sell-stock-iv"

In Dynamic Programming Solution the "if" conditioning at line number 10 is "2k > n", which I think should be "k/2 > n". With this condition we are sure that we will never go out of transaction limits.

#### Code you used for Submit/Run operation

```
// best-time-to-buy-and-sell-stock-iv
if(k/2>n){
            int res = 0;
            for (int i = 1; i < n; i++){
                res += Math.max(0, prices[i]-prices[i-1]);
            }
            return res;
        }
```

#### Language used for code

Java

#### Expected behavior

In Dynamic Programming Solution the "if" conditioning at line number 10 is "2k > n", which I think should be "k/2 > n". With this condition we are sure that we will never go out of transaction limits.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by bhushanvbr** [comment]
Hi,

Code submission link:
https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iv/submissions/983567593/

Regards,
Vidya Bhushan Ray

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

please explain more.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by bhushanvbr** [comment]
Hi There,

In the editorial of this problem, approach 1 Dynamic Programming, Java
Solution line number 10,  states the condition "*if (2 * k > n) {*". This
means in case 2k is greater than n we will never run out of moves and we
don't have to keep track of moves used, but this holds true even if k/2 is
greater than n.
As per the problem description a transaction is marked complete when we buy
and then sell. and this can not be done on the same day. Hence, if the size
of the prices array is n, max transactions possible will be n/2. So I think
line 10 of this solution can be replaced with "*if (k/2 > n) {*".  I have
tested this condition and all the test cases pass.

If this assumption is not correct, we probably need to add a test case to
handle this.

Thanks

Regards,
Vidya Bhushan Ray

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
