### ISSUE TITLE
Missing Test Case - 20. Valid Parentheses

### ISSUE THREAD

**Issue by SMD-Arshad** [LeetCode-Feedback/LeetCode-Feedback#14484]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ #] Missing Test Cases 

#### Description of the bug

Add a testcase which consist of open brackets in the beginning of the string
like "{[]{"

#### Code you used for Submit/Run operation

```
class Solution:
    def isValid(self, s: str) -> bool:
        l = []
        if s[0] == "}" or s[0] == ")" or s[0] == "]" :
            return False
        if len(s) == 1:
            return False
        for i in range(len(s)):
            if s[i]=='(' or s[i]=='[' or s[i]=='{':
                l.append(s[i])
            elif  l!=[] and s[i] == ')' and l[-1] == "(" :
                l.pop(-1)
            elif  l!=[] and s[i]== "]" and l[-1]=="[" :
                l.pop(-1)
            elif l!= [] and s[i]== "}" and l[-1] == "{" :
                l.pop(-1)
            else:
                return False
        
        
        return l == []
```

**Comment by SMD-Arshad** [comment]
##

**Comment by SMD-Arshad** [comment]
####

**Comment by BhaveshJain1947** [comment]
What's the missing test case in this bruhh ???

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
