### ISSUE TITLE
Test Case - 744. Find Smallest Letter Greater Than Target

### ISSUE THREAD

**Issue by debjitl45** [LeetCode-Feedback/LeetCode-Feedback#14488]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

Consider a list of letters 
Input: letters = ["a","b","c","f","k"], target = "t"
Output: "a"
There are no characters in letters that is lexicographically greater than 't' so we return letters[0].

Input: letters = ["c","c","c","f","j","j"], target = "f"
Output: "j"
Smallest character that is lexicographically greater than 'f' is 'j'

#### Code you used for Submit/Run operation

```
class Solution {
public:
    char nextGreatestLetter(vector<char>& v, char t) {
        int low=0,mid=0,high=v.size()-1;
        while(low<=high)
        {
            mid=low+(high-low)/2;
            if(v[mid]>t)
            {
                high=mid-1;
            }
            else
            {
                low=mid+1;
            }
        }
        return low==v.size()?v[0]:v[low];
    }
};

```

#### Language used for code

C++

#### Expected behavior

Return the smallest character in letters that is lexicographically greater than target. If such a character does not exist, return the first character in letters.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
