### ISSUE TITLE
Missing Test Case - 1492. The kth Factor of n

### ISSUE THREAD

**Issue by repo-anuj** [LeetCode-Feedback/LeetCode-Feedback#14486]
#### Category of the bug
- [You are given two positive integers n and k. A factor of an integer n is defined as an integer i where n % i == 0.

Consider a list of all factors of n sorted in ascending order, return the kth factor in this list or return -1 if n has less than k factors.

 

Example 1:

Input: n = 12, k = 3
Output: 3
Explanation: Factors list is [1, 2, 3, 4, 6, 12], the 3rd factor is 3.
Example 2:

Input: n = 7, k = 2
Output: 7
Explanation: Factors list is [1, 7], the 2nd factor is 7.
Example 3:

Input: n = 4, k = 4
Output: -1
Explanation: Factors list is [1, 2, 4], there is only 3 factors. We should return -1.
 

Constraints:

1 <= k <= n <= 1000 ] Question
- [ ```/**
 * @param {number} n
 * @param {number} k
 * @return {number}
 */
var kthFactor = function(n, k) {
 for (let i = 1; i <= n; i++) {
        if (n % i === 0) {
            k--;
            if (k === 0) {
                return i;
            }
        }
    }
    return -1;
};```] Solution
- [ JavaScript] Language
- [ console.log(kthFactor(12, 3)); // Expected output: 3] Missing Test Cases 

#### Description of the bug
<!-- The provided code seems to have a logical bug in the kthFactor function. The issue is with the decrementing of k inside the loop. The decrement should happen after checking if k is equal to 0, rather than before it.

Here's the corrected code: 
 ```class Solution {
public:
    int kthFactor(int n, int k) {
       for(int i = 1; i <= n; i++) {
           if(n % i == 0) {
              if(k == 1) return i;
              k--;
           }
       } 
       return -1;
    }
}; ```
In the corrected code, we first check if k is equal to 1 before decrementing it. This ensures that we return the correct factor when k reaches 1, and properly handle the case when n has less than k factors by returning -1.
-->


#### Code you used for Submit/Run operation
<!-- 
Please make sure you wrap your code with ``` tags. 
Otherwise we may reject your request. 
-->

```
var kthFactor = function(n, k) {
 for (let i = 1; i <= n; i++) {
        if (n % i === 0) {
            k--;
            if (k === 0) {
                return i;
            }
        }
    }
    return -1;
};
```

#### Language used for code
<!-- JavaScript-->


#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->



#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by repo-anuj** [comment]
thanks leetcode

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by repo-anuj** [comment]
@LC-Pam why not here this is my account link https://leetcode.com/Anuj0Dubey/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link.
![Screen Shot 2023-07-05 at 11 20 56 AM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/c47648f0-60ae-4907-bf81-b279840a48f9)

https://leetcode.com/problems/the-kth-factor-of-n/" is the problem link. 


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by repo-anuj** [comment]
@LC-Pam  The code submission AC link. - https://leetcode.com/submissions/detail/984305614/

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

After a thorough evaluation, we regret to inform you that our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
