### ISSUE TITLE
Missing Test Case - 1663. Smallest String With A Given Numeric Value

### ISSUE THREAD

**Issue by dpustovarov** [LeetCode-Feedback/LeetCode-Feedback#1448]
#### Your LeetCode username
dpustovarov

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

The following solution is wrong for the test case:
n = 3; k = 78
but it was successfully accepted

#### Code you used for Submit/Run operation
```
// Two Sum
class Solution:
    def getSmallestString(self, n: int, k: int) -> str:
        num2 = (k-n) // 25
        num1 = n - num2 - 1
        num = k - (num1 + num2 * 26)
        return 'a' * num1 + chr(num+96) + 'z' * num2
```

#### Language used for code
Python3

#### Expected behavior

The solution should be rejected.

**Comment by dpustovarov** [comment]
Correct solution: https://leetcode.com/problems/smallest-string-with-a-given-numeric-value/discuss/946553/Correct-simple-Python-solution-without-loop

**Comment by lc-kay** [comment]
@dpustovarov When I ran the code you provided in the issue, it resulted in a Wrong Answer. Then, I ran the test case with the code in the discuss link you included, and it was accepted. Please provide an accepted code where this test case fails on, then I will reopen this issue and further investigate it. Thank you for your time!

**Comment by dpustovarov** [comment]
The submission https://leetcode.com/submissions/detail/423326729/ is Accepted, but should be rejected.

**Comment by lc-kay** [comment]
@dpustovarov I just ran the solution provided in the submission details link and it is rejected. Thank you for your time!
