### ISSUE TITLE
Question - 373 not showing "expected" when running code [JAVA]

### ISSUE THREAD

**Issue by HarshitTamrakar** [LeetCode-Feedback/LeetCode-Feedback#14482]
#### Your LeetCode username
tamrakarharshit

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Testcases are not working and expected is null when running code (not submitting). 
Its a 95 priority bug. 

#### Code you used for Submit/Run operation
```
class Solution {
    public List<List<Integer>> kSmallestPairs(int[] nums1, int[] nums2, int k) {
        PriorityQueue<List<Integer>> queue = new PriorityQueue<>(k, new Comparator<List<Integer>>() {
            public int compare(List<Integer> l1, List<Integer> l2) {
                return (l2.get(0) + l2.get(1)) - (l1.get(0) + l1.get(1));
            }
        });
        List<List<Integer>> answer = new ArrayList<>();
        for (int i = 0; i < nums1.length; i++) {
            int j = 0;
            while (j < nums2.length) {
                List<Integer> list = new ArrayList<>();
                list.add(nums1[i]);
                list.add(nums2[j]);
                queue.add(list);
                if (queue.size() > k) {
                    queue.remove();
                }
                j++;
            }
        }
        while(!queue.isEmpty()) {
            answer.add(0, queue.remove());
        }
        return answer;
    }
}
```

#### Language used for code
JAVA

#### Expected behavior
Should show expected result (Answer for that test case)

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/39623432/ffd9fa32-563c-498b-84e7-c76b92392500)

#### Additional context
I think its a backend issue as code output is empty in api response.
API URI : `https://leetcode.com/submissions/detail/runcode_1688243612.3574047_g03APcZ9PC/check/`
Response: ```{
    "status_code": 10,
    "lang": "java",
    "run_success": true,
    "status_runtime": "0 ms",
    "memory": 40764000,
    "display_runtime": "0",
    "code_answer": [
        "[[1,2],[1,4],[1,6]]",
        "[[1,1],[1,1]]",
        "[[1,3],[2,3]]"
    ],
    "code_output": [],
    "std_output_list": [
        "",
        "",
        "",
        ""
    ],
    "elapsed_time": 169,
    "task_finish_time": 1688243615054,
    "task_name": "judger.runcodetask.RunCode",
    "total_correct": null,
    "total_testcases": null,
    "runtime_percentile": null,
    "status_memory": "40.8 MB",
    "memory_percentile": null,
    "pretty_lang": "Java",
    "submission_id": "runcode_1688243612.3574047_g03APcZ9PC",
    "status_msg": "Accepted",
    "state": "SUCCESS"
}```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by HarshitTamrakar** [comment]
> Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
> 
> The code submission AC link.
> 
> We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

I dont have AC link as it is not running the code

**Comment by HarshitTamrakar** [comment]
> Thank you for reaching out to us, https://leetcode.com/submissions/detail/987037648/, This could occur because the code is not optimized. When you run your code by "Submit", it's very different from running it with "Run Code". "Submit" run all of the test cases for this problem at once, whereas "Run Code" only run one test case at a time. Furthermore, getting Time Limit Exceeded from "Submit" does not mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test cases at once. I found a Swift solution in the problem discuss section and hope it can provide some inspiration to how your code can be improved to overcome this TLE issue: https://leetcode.com/problems/elimination-game/discuss/245342/Swift-keep-left-and-right-boundary
> 
> The issue you experienced is runtime variation. It normally happens when your code is at the edge of the time limit that can pass the problem. Therefore, your code may have different results at different submissions.  It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make different executions have runtime variation.   I've passed your feedback to our engineering team and they'll investigate in order to provide consistent results for our users. However, I'm afraid that we won't have a quick fix for the issue that you're facing. I recommend that you optimize your code to pass the time limit. We apologize for the inconvenience and thank you for your support!

Thanks for the clarifications. Hope issue will get resolved as soon as possible.
