### ISSUE TITLE
Incorrect Test Case - 2336. Smallest Number in Infinite Set

### ISSUE THREAD

**Issue by Rembamb** [LeetCode-Feedback/LeetCode-Feedback#14493]
#### Your LeetCode username
DonutMaster

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
In test case #133, it says that the actual output should print 168 two times near the end. However, they do not add 168 after they have printed out 168. This is clearly a bug.

#### Code you used for Submit/Run operation

```
// Two Sum
class SmallestInfiniteSet {
public:
    int startFrom = 1;
    vector<int> nums;
    SmallestInfiniteSet() {
        startFrom = 1;
        nums.clear();
    }
    
    int popSmallest() {
        if(nums.size() != 0) {
            int number = nums[0];
            nums.erase(nums.begin());
            return number;
        } else {
            startFrom++;
            return startFrom-1;
        }
    }
    
    void addBack(int num) {
        if(num < startFrom) {
            nums.push_back(num);
            sort(nums.begin(), nums.end());
        }
    }
};

/**
 * Your SmallestInfiniteSet object will be instantiated and called as such:
 * SmallestInfiniteSet* obj = new SmallestInfiniteSet();
 * int param_1 = obj->popSmallest();
 * obj->addBack(num);
 */
```

#### Language used for code
C++

#### Expected behavior
I thought that 168 shouldn't be printed out, but it does.

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
