### ISSUE TITLE
Missing Test Case - 93. Restore IP Addresses

### ISSUE THREAD

**Issue by tongxin880120** [LeetCode-Feedback/LeetCode-Feedback#1449]
class Solution {
    
    List<String> list = new ArrayList<>();
    public List<String> restoreIpAddresses(String s) {
        if(s.length() == 0) return list;
        
        dfs(s, new ArrayList<>(), 4);
        return list;
    }
    public void dfs(String s, List<String> tmp, int time){
        
        if(time == 0 && s.length()==0){
            list.add(String.join(".",new ArrayList<>(tmp)));
            return;
        }
        if(time == 1 && s.length()>3){
            return;
        }
        if(s.length()>=3){
            if(Integer.valueOf(s.substring(0,3))<=255 && s.charAt(0) != '0'){
                tmp.add(s.substring(0,3));
                dfs(s.substring(3), tmp, time-1);
                tmp.remove(tmp.size()-1);
            }
        }
        if(s.length()>=2){
            if(s.charAt(0) != '0'){
                tmp.add(s.substring(0,2));
                dfs(s.substring(2), tmp, time-1);
                tmp.remove(tmp.size()-1);
            }
        }
        
        if(s.length()>=1){
            tmp.add(s.substring(0,1));
            dfs(s.substring(1), tmp, time-1);
            tmp.remove(tmp.size()-1);
        }
    }
}

**Comment by lc-kay** [comment]
@tongxin880120 Please submit the reported missing test case. Thank you for your time!

**Comment by lc-kay** [comment]
Hi @tongxin880120  ,
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
