### ISSUE TITLE
Surrounded Region (Problem No. 130) 

### ISSUE THREAD

**Issue by samarth2804** [LeetCode-Feedback/LeetCode-Feedback#14497]
#### Your LeetCode username

Elec_007

#### Category of the bug
- [ ] Wrong Test Cases 

#### Description of the bug

For the test case (43):-
[["O","X","X","O","X"],["X","O","O","X","O"],["X","O","X","O","X"],["O","X","O","O","O"],["X","X","O","X","O"]] 
the expected output is:- 
[["O","X","X","O","X"],["X","X","X","X","O"],["X","X","X","O","X"],["O","X","O","O","O"],["X","X","O","X","O"]]
but it's correct output must be:- 
[["O","X","X","O","X"],["X","X","X","X","O"],["X","X","X","X","X"],["O","X","O","O","O"],["X","X","O","X","O"]]

For [i,j]=[2,3], 'O' is surrounded by all direction with 'X'. So it must be converted into 'X'
#### Code you used for Submit/Run operation

```
class Solution {
public:
    void solve(vector<vector<char>>& board) {
        int m=board.size();
        int n=board[0].size();
        vector<int> bottom(n,-1),right(m,-1);

        for(int i=1;i<n;++i){
            for(int j=m-1;j>=0;--j){
                if(board[j][i]=='X'){
                    bottom[i]=j;
                    break;
                }
            }
        }

        for(int i=1;i<m;++i){
            for(int j=n-1;j>=0;--j){
                if(board[i][j]=='X'){
                    right[i]=j;
                    break;
                }
            }
        }
       
        for(int i=1;i<m-1;++i){
            for(int j=1;j<n-1;++j){
                 if(board[i][j]=='O' && board[i][j-1]=='X' && board[i-1][j]=='X' && bottom[j]>i && right[i]>j){
                     board[i][j]='X';
                 }
            }
        }

    }
};
```

#### Language used for code
C++ 

#### Expected behavior

For the test case (43):-
[["O","X","X","O","X"],["X","O","O","X","O"],["X","O","X","O","X"],["O","X","O","O","O"],["X","X","O","X","O"]] 
the expected output is:- 
[["O","X","X","O","X"],["X","X","X","X","O"],["X","X","X","O","X"],["O","X","O","O","O"],["X","X","O","X","O"]]
but it's correct output must be:- 
[["O","X","X","O","X"],["X","X","X","X","O"],["X","X","X","X","X"],["O","X","O","O","O"],["X","X","O","X","O"]]

For [i,j]=[2,3], 'O' is surrounded by all direction with 'X'. So it must be converted into 'X'

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
