### ISSUE TITLE
Missing Test Case - 1361. Validate Binary Tree Nodes

### ISSUE THREAD

**Issue by AjayMaheshwari23** [LeetCode-Feedback/LeetCode-Feedback#14498]
#### It appears that there is a missing test case. Please consider the following test case and following description 
 int n = 3;
vector<int> left = { -1 , 2 , -1 } , right = { -1 , -1 , -1 };

In this particular scenario, my submitted [code](https://leetcode.com/problems/validate-binary-tree-nodes/submissions/984567160/) will fail because i am not checking if there are two nodes with zero in-degree ( which violates the condition of a Binary tree ), But still my solution is getting accepted. A significant number of users who have shared their solutions are also failing to account for this particular case.

It is crucial to address the issue of this missing test case to provide a fair assessment for users attempting to solve it. By including the necessary test case, both the question and the solutions will be more reliable and dependable.

#### Code you used for Submit/Run operation

```
#define need_for_speed ios_base::sync_with_stdio(false); cin.tie(NULL);

const int N = 1e4+10;
vector<int> par(N),siz(N);

void make(int a)
{
    par[a]=a;
    siz[a]=1;
}

int getpar(int a)
{
    if( par[a]==a ) return a;
    return par[a] = getpar( par[a] );
}

void addbtoa(int a,int b)
{
    a = getpar(a);
    b = getpar(b);
    if(a!=b)
    {
        if( siz[a]<siz[b] ) swap(a,b);
        par[b] = a;
        siz[a]+=siz[b];
        siz[b]=0;  
    } 
}

class Solution {
public:
    bool validateBinaryTreeNodes(int n, vector<int>& left, vector<int>& right) 
    {
        need_for_speed;
        par.clear(); siz.clear(); par.resize(n); siz.resize(n);
        bool ok = true; unordered_set<int> present; present.insert(0);
        vector<int> indg(n,0);
        for(int i=0;i<n;i++) make(i);
        for(int i=0;i<n;i++)
        {
            bool node_dne = present.find(i)==present.end(); bool l1 = false , r1 = false;

            int cur_par = getpar(i);
            int l = left[i] , r = right[i];
            if( l!=-1 )
            {
                l1 =  present.find(l)==present.end();
                indg[l]++;
                l = getpar(l);
                if( l==cur_par ) ok = false;
                else addbtoa(i,l);
                present.insert(l);
            }

            if( r!=-1 )
            {
                r1 =  present.find(r)==present.end();
                indg[r]++;
                r = getpar(r);
                if( r==cur_par ) ok = false;
                else addbtoa(i,r);
                present.insert(r);
            }

            if(node_dne && l1 && r1) ok = false;
        }

        // for(int i=0;i<n;i++)

        for(auto it:indg) ok&=( it==1 || it==0 );
        return ok;
    }
};
```

#### Screenshots
<img width="794" alt="Screenshot 2023-07-02 at 7 39 51 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/96301800/1a3a25dc-0052-4628-b8fc-ebf4e9885905">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
