### ISSUE TITLE
198:打家劫舍

### ISSUE THREAD

**Issue by zzilcc** [LeetCode-Feedback/LeetCode-Feedback#145]
![image](https://user-images.githubusercontent.com/18416922/79138295-dfdd6500-7de6-11ea-93b1-50bc042f4d4f.png)
这道题意义不好，假设是专业的小偷？？？？？？？
还有打家劫舍2，打家劫舍3，建议删除

**Comment by feiceh** [comment]
感谢反馈，该问题已转给相关团队后期会持续优化，给您带来的不便敬请谅解。Github 仓库只用于反馈大家在本站学习过程中遇到的题目和题解问题，请知晓～
