### ISSUE TITLE
Missing Test Case - 1342. Number of Steps to Reduce a Number to Zero

### ISSUE THREAD

**Issue by DivyaPratyush** [LeetCode-Feedback/LeetCode-Feedback#14502]
#### Your LeetCode username

divyaprtyush

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

For the condition of input 0 expected output is 0

#### Code you used for Submit/Run operation

```
# Two Sum
class Solution:
    def numberOfSteps(self, num: int) -> int:
        #n = num
        steps = 1
        if num ==0:
            return 0
        while num >1:
            odd = num%2
            steps+= odd+1
            num = num//2            
        return steps

```

#### Language used for code

Python3

#### Expected behavior

My code evaluates in the number is odd or not if it's odd it increments the steps. then increment steps while dividing it with 2. When the Input is 0, the expected answer is 0 but code runs it as 1 because 0 is even and it divides it evenly. So, it fails when input of 0. Even description of problem doesn't say that explicitly. We need a fail-safe check for input 0. As, this issue becomes visible only when we submit the answer.

So, **we need a test case with input 0.**

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

Test case 0 already exists.
![Screen Shot 2023-07-03 at 4 11 39 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/a9832564-62db-4df0-a2f4-46a2c82f0c7d)


If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
