### ISSUE TITLE
Worng Test Case - 2035. Partition Array Into Two Arrays to Minimize Sum Difference

### ISSUE THREAD

**Issue by yatharth-1504** [LeetCode-Feedback/LeetCode-Feedback#14504]
#### Your LeetCode username
yatharth_1504

#### Category of the bug
- [x] Solution

#### Description of the bug
The Problem contains a wrong test case where the input was given to be [76,8,45,20,74,84,28,1], it can be clearly seen that the array can be partitioned into two subsets first being [76, 8, 84] and the second being [45, 20, 74, 28, 1] which give an absolute difference of 0

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    int minimumDifference(vector<int>& nums) {
        int n = nums.size();
        // handling edge conditions
        int _min = *min_element(nums.begin(), nums.end());
        if (_min < 0){
            for (int i = 0; i < n; i++) nums[i] -= _min; 
        }

        int sum = accumulate(nums.begin(), nums.end(), 0);
        vector<vector<bool>> dp(n, vector<bool>(sum  + 1, false));
        for (int i = 0; i < n; i++) dp[i][0] = 1;
        for (int i = 1; i < n; i++){
            for (int target = 0; target <= sum; target++){
                bool notPick = dp[i - 1][target];
                bool pick = false;
                if (target - nums[i] >= 0) pick = dp[i - 1][target - nums[i]];
                dp[i][target] = pick | notPick; 
            }
        }
        int ans = INT_MAX;
        for (int i = 0; i <= sum; i++) {
            if (dp[n - 1][i]) ans = min(ans, abs(i - (sum - i)));
        }
        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior
Test case: [76,8,45,20,74,84,28,1]
Correct Output : 0
Out expected by LeetCode: 2

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team

**Comment by yatharth-1504** [comment]
Thank you for your response team leetcode, i really appreciate it, i
finally realised my mistake.
