### ISSUE TITLE
373. Find K Pairs with Smallest Sums. Solution not getting submitted.

### ISSUE THREAD

**Issue by Jeetaksh** [LeetCode-Feedback/LeetCode-Feedback#14500]
#### Your LeetCode username
Jeetaksh

#### Category of the bug

- Solution

#### Description of the bug

https://leetcode.com/problems/find-k-pairs-with-smallest-sums/submissions/984617448/
This problem has stopped accepting any submissions. I tried submitting my previous AC code, the code mentioned in Editorial, and the code of others in solution as well. The codes gives the correct output which should be given and as described  in the problem description. The expected output of this problem which validates our answer got a bug. The system cannot find the expected answer correctly. 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<vector<int>> kSmallestPairs(vector<int>& nums1, vector<int>& nums2, int k) {
        priority_queue<pair<int,pair<int,int>>, vector<pair<int,pair<int,int>>>, greater<pair<int,pair<int,int>>>> pq;
        int n = nums1.size(), m = nums2.size();
        vector<vector<int>> ans;

        for(int i=0;i<n;i++){
            pq.push({nums1[i]+nums2[0],{i,0}});
        }
        while(pq.size() && k--){
            auto it=pq.top();
            int x=it.second.first,y=it.second.second;
            ans.push_back({nums1[x],nums2[y]});
            pq.pop();
            if(y+1<m) pq.push({nums1[x]+nums2[y+1],{x,y+1}});
        }          
        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior
I believe that my previously AC, and code of other people code should be accepted. The bug in expected output could be fixed and the problem can be solved again.

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/92541718/43547cf3-6a6e-40d8-881a-d94ca4771cb0)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/92541718/3879f699-c85a-4a74-9db2-0a3e1d11a9b9)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/92541718/44441aa2-7bd0-42f7-87f6-186a890c2ecc)

#### Additional context
Not Applicable

**Comment by omkumarjha** [comment]
Hii 

I am also getting the same problem from morning .

**Comment by AshishSrivastava24** [comment]
I am also getting similar issue

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

The issue is fixed. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
