### ISSUE TITLE
2763. Sum of Imbalance Numbers of All Subarrays

### ISSUE THREAD

**Issue by projecteulerlover** [LeetCode-Feedback/LeetCode-Feedback#14505]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The following solution https://leetcode.com/contest/weekly-contest-352/submissions/detail/984185264/ from the contest fails the test case of [1, 2, ..., 1000]. 

This solution is O(n^3 log n), but somehow passed the test cases during the contest.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    int cont(map<int, int> &st){
        int c=0;
        int prev=st.begin()->first;
        for(auto &x: st){
            if((x.first-prev)>1) c++;
            prev=x.first;
        }
        return c;
    }
    
    int sumImbalanceNumbers(vector<int>& nums) {
        int n = nums.size();
        int ans = 0;
        for(int i=0;i<n; i++){
            map<int, int> st;
            for(int j=i; j<n; j++){
                st[nums[j]]++;
                ans+=cont(st);
            }
        }
        return ans;
    }
};
```

#### Expected behavior

This solution should TLE with the additional test case of [1, 2, ..., 1000] (the list of numbers from 1 to 1000).

**Comment by projecteulerlover** [comment]
I have attached the test case in question in text format for your convenience.
[temp.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/11931209/temp.txt)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Textcase [1, 2, ..., 1000] already exists.

![Screen Shot 2023-07-03 at 1 27 41 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/07ad8d93-6e8b-4810-b170-4d7b7ce919b6)


If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
