### ISSUE TITLE
Missing Test Case - 227. Basic Calculator II

### ISSUE THREAD

**Issue by Rahul-AS** [LeetCode-Feedback/LeetCode-Feedback#1450]
#### LeetCode username
rahul_a_s

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

My code failed for the input "1+2\*5/3+6/4\*2". My output is 5 but the expected output is 6.
But if I run the code with custom input as "6/4\*2". My output and expected output is same which is 2 but the expected output should be 3 as above input.

#### Code you used for Submit/Run operation
As my code is not correct. I haven't attached here.

#### Language used for code
Python3

#### Expected behavior

For the input "1+2\*5/3+6/4\*2". I thought the evaluation will happen as
=1+2\*5/3+6/4\*2
=1+2\*1+1\*2
=1+2+2
=5(my output)
But the expected output is 6. I think the evaluation might have happened as
=1+2\*5/3+6/4\*2
=1+2\*5/3+6/2
=1+2\*1+3
=1+2+3
=6(expected output)

I thought my code was wrong due to the above test case. But when I tested my code with 6/4\*2, my output and expected output is same which is 2. But the expected output should be 3 as per the above evaluation.
By comparing the results, one of the evaluation method is wrong.

Can you explain which method to choose to evaluate the expression?

And also tell the operator precedence used to evaluate the expression?

**Comment by kirtika27** [comment]
I got the same issue. 
They are assuming equal precedence for '*' and '/' operator. That is why this is happening. Evaluation happened like:
=1+2*5/3+6/4*2 
=1+10/3+1*2
=1+3+2
=6     WHICH IS CLEARLY A WRONG EVALUATION. Correct answer should be 5 .No calculator would give 6 as the answer. I also reported an issue. #1452

**Comment by zerotrac** [comment]
Hey guys, are you serious? 2*5/3=10/3=3 and 6/4*2=1*2=2, thus 1+2*5/3+6/4*2=1+3+2=6.

What language gives `/` more precedence than `*` ???

**Comment by lc-kay** [comment]
@Rahul-AS Please refer to @zerotrac comment above. If you still believe it is an issue, please let me know and I will reopen the issue and further investigate it. Thank you for your time!
