### ISSUE TITLE
346. Moving Average from Data Stream

### ISSUE THREAD

**Issue by Hitrene** [LeetCode-Feedback/LeetCode-Feedback#14506]
#### Your LeetCode username
user3960IC

#### Category of the bug
- [ ] Language

#### Description of the bug
On Kotlin version of the problem, the argument in the constructor is missing `val` before the argument

#### Code you used for Submit/Run operation
```
class MovingAverage(size: Int) {

    fun next(`val`: Int): Double {
        size == 0
        return 0
    }

}
```

#### Language used for code
Kotlin

#### Expected behavior
Instead of 
```
class MovingAverage(size: Int) {
```
it should be 

```
class MovingAverage(val size: Int) {
```

Otherwise, this code will not compile

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
