### ISSUE TITLE
typo in 859. Buddy Strings c++ solution comments

### ISSUE THREAD

**Issue by TusharAbbott** [LeetCode-Feedback/LeetCode-Feedback#14514]
#### Your LeetCode username
tusharabbott2000

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Typo in C++ solution of 859. Buddy Strings of Characters, it's currently chanacters.

#### Language used for code
 C++

#### Expected behavior
It should be characters

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/50478078/cf78c275-2c5c-4c2e-95fc-d9cd39ce7459)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
