### ISSUE TITLE
Description typo - 1357. Apply Discount Every n Orders

### ISSUE THREAD

**Issue by xelplogoog** [LeetCode-Feedback/LeetCode-Feedback#14510]
#### Your LeetCode username
c4tdog

#### Description of the bug
There are 7 customers, but 6th is mentioned twice

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2188302/3479c3b2-7a01-45a6-9cf4-d5cc13b4bd33)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
