### ISSUE TITLE
Missing Test Case - 859: Buddy Strings

### ISSUE THREAD

**Issue by vorishirne** [LeetCode-Feedback/LeetCode-Feedback#14515]
#### Your LeetCode username

vorishirne

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My code got submitted. But I had a test case for which the code is still failing. 

#### Code you used for Submit/Run operation

```
func buddyStrings(s string, goal string) bool {
    l := len(goal)
    if l != len(s){
        return false
    }

    swapped := false
    j:=-1
    for i:=0;i<l;i++{
        if s[i] != goal[i]{
            if j>-1 {
                if goal[j]==s[i] && s[j]==goal[i]{
                    swapped = true
                }else{
                    return false
                }       
            }else{
                j=i
            }
        }
    }
    if !swapped {
        if s == goal{
            dups := map[byte]bool{}
            for i := 0;i<l;i++{
                if dups[s[i]]{
                    return true
                }
                dups[s[i]] = true
            }
        }
        return false
    }
    
    return true
}
```

my code fails in this test case

```
s = "acdd"
goal = "adcc"

expected false
```

#### Language used for code

Go

#### Expected behavior

Code should not had been accepted.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
