### ISSUE TITLE
Missing Test Case - 373. Find K Pairs with Smallest Sums

### ISSUE THREAD

**Issue by omkumarjha** [LeetCode-Feedback/LeetCode-Feedback#14513]
#### Your LeetCode username

Om Kumar Jha

#### Category of the bug
-  Solution

#### Description of the bug

My code and approach everything is correct only but when i am running my code then it is faling because expected output is showing blank in the console.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    typedef pair<int , pair<int,int>> p;
    vector<vector<int>> kSmallestPairs(vector<int>& nums1, vector<int>& nums2, int k) {
       priority_queue<p,vector<p>>pq;
       vector<vector<int>> ans;
       
       for(int i = 0; i < nums1.size(); i++){
           for(int j = 0; j < nums2.size(); j++){
               int sum = nums1[i] + nums2[j];
               if(pq.size() < k){
                   pq.push({sum,{nums1[i],nums2[j]}});
               }
               else if(pq.top().first > sum){
                   pq.pop();
                   pq.push({sum,{nums1[i],nums2[j]}});
               }
               else{
                   break;
               }
           }
       }

       while(pq.empty() != true){
           auto temp = pq.top();
           pq.pop();
           ans.push_back({temp.second.first,temp.second.second});
       }
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Expected answer should be the same which is mentioned in the question example but because expended output is showing blank the code is faling.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/88018877/9280e9cb-f4c4-4c0d-9d00-1632db927b64)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

The issue is fixed. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
