### ISSUE TITLE
Missing Test Case - 859. Buddy Strings

### ISSUE THREAD

**Issue by thewpingmonk** [LeetCode-Feedback/LeetCode-Feedback#14517]
#### Your LeetCode username

TheWpingMonk

#### Category of the bug
- [ no] Question
- [ no] Solution
- [no ] Language
- [yes ] Missing Test Cases 

#### Description of the bug

The constraints mentioned in the question does not say that the size of string 's' and string 'goal' need to be equal so if we take a testcase where the size of s and goal are not equal, it will give runtime error.
For example : s = "aaaaaaaaaaaaaaaaa" and goal = "aa".

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool buddyStrings(string s, string goal) {
        int n = s.length();
        if(s == goal){
            set<char> temp(s.begin(), s.end());
            return temp.size() < goal.size(); // Swapping same characters
        }

        int i = 0;
        int j = n - 1;
        while(i < j && s[i] == goal[i]){
            i++;
        }
        while(j >= 0 && s[j] == goal[j]){
            j--;
        }

        if(i < j){
            swap(s[i], s[j]);
        }

        return s == goal;
    }
};
```

#### Language used for code

C++

#### Expected behavior

For the testcase s = "aaaaaaaaaaaaaaaaa" and goal = "aa"  should give runtime error but it passes on submitting.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
