### ISSUE TITLE
Missing Test Case - 859. Buddy Strings

### ISSUE THREAD

**Issue by GeorgeManukyan** [LeetCode-Feedback/LeetCode-Feedback#14527]
#### Your LeetCode username

tlamer 

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [* ] Missing Test Cases 

#### Description of the bug

input:
 aa
 aacc  

My code returns **true**, 
Expected Is **false** 
My code got accepted but return wrong answer on this test case 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool buddyStrings(string s, string goal) 
    {
        m.resize(256,0);
        int first = -1 ;
        int second = -1 ;

        for (int i = 0; i < s.length(); i++){
            if (s[i] != goal[i]){
                if (first == -1){
                    first = i;
                }
                else {
                    swap(s[i], s[first]);
                    break;
                }
            }
        }

        // identical strings
        
        

        if (first ==-1){
           
            for (int i = 0 ; i < s.length(); i++){
               if (m[s[i]] > 0) return true;
               m[s[i]]++;
            }

            return false;  
        }

        return s == goal;
    }

   vector<char> m;
};
```

#### Expected behavior

Test case ran successfully,

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
