### ISSUE TITLE
Sentient Nodes in the Queue Article from the Data Structures and Algorithms course

### ISSUE THREAD

**Issue by Salt-City** [LeetCode-Feedback/LeetCode-Feedback#14528]
#### Your LeetCode username
physicalscience

#### Category of the bug
- [ ] Question
- [ ] Solution
- [X ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Very small nitpick, but I figured it was worth calling out. In the `Queues` article in the Data Structures and Algorithms course you have this paragraph:
```
One way to implement an efficient queue is using a doubly linked list. Recall that with a doubly linked list, if you have the pointer to a node, you can add or delete at that location in O(1)
O(1). A doubly linked list that maintains pointers to the head and tail (both ends, usually with **sentient** nodes) can implement an efficient queue.
```

You reference a sentient node, but I believe you meant "sentinel node".

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
