### ISSUE TITLE
Video Cannot be played

### ISSUE THREAD

**Issue by lokhandeomkar** [LeetCode-Feedback/LeetCode-Feedback#14537]
<img width="1440" alt="Screen Shot 2023-07-04 at 12 52 37 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/10038568/a079a3c8-a03f-4d41-8700-0dfe922a67b0">

Getting this error on videos in editorials. Which privacy setting on my system is this resulting from?

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The video working correctly. 

![Screen Shot 2023-07-05 at 11 31 16 AM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/9d939bfc-fa20-4e98-86ca-7e74f0c3c897)


If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
