### ISSUE TITLE
Missing Test Case - 675. Cut Off Trees for Golf Event

### ISSUE THREAD

**Issue by KJKimCE** [LeetCode-Feedback/LeetCode-Feedback#1453]
#### Your LeetCode username

KJKimCE

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ x] Language

#### Description of the bug

The language can be better worded to clarify the question.

You are asked to cut off trees in a forest for a golf event. The forest is represented as a non-negative 2D map, in this map:
    1. 0 represents the obstacle and **cannot be crossed**.
    2. 1 represents the ground and can be walked through.
    3. 2 or a higher number represents a tree can be walked through, and this positive number represents the tree's height.
In one step you can walk in any of the four directions top, bottom, left and right also when standing in a point which is a tree you can decide whether or not to cut off the tree.

You are asked to cut off all the trees in this forest in the order of tree's height - always cut off the tree with lowest height first. And after cutting, the original place of the tree will become a grass (value 1).

You will start from the point (0, 0) and you should output the minimum steps you need to walk to cut off all the trees. If you can't cut off all the trees, output -1.

You are guaranteed that no two trees have the same height and there is at least one tree **that** needs to be cut off.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior

Better explanation of the problem.

**Comment by lc-kay** [comment]
Hi @KJKimCE 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @KJKimCE 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
