### ISSUE TITLE
Missing Test Case - 69. Sqrt(x)

### ISSUE THREAD

**Issue by 19Ishan** [LeetCode-Feedback/LeetCode-Feedback#14535]
#### Category of the bug
- [ ] Missing Test Case

#### Description of the bug
 +2^31 - 1) then the code should throw an error. -->

#### Code you used for Submit/Run operation

```
class Solution {
public:
    long long int mySqrt(int x) {
        int s = 0;
        int e = x;

        long long int mid = s + (e - s)/2;
        int ans = -1;

        while(s <= e){
            long long int sq = mid * mid;

            if(sq > x){
                e = mid - 1;
            }

            else if(sq < x){
                ans = mid;
                s = mid + 1;
            }

            else{
                return mid;
            }

            mid = s + (e - s)/2;
        }

        return ans;
    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by 19Ishan** [comment]
Yeah sure, I used the C++ language to reach this result.

And thank you for reverting back on this issue. Really appreciate that.

Do let me know if there's anything more I can help you with.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

what is the error? can you explain more?

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by 19Ishan** [comment]
The error is that this question is missing a necessary test case which needs to be added so that the student or a programmer can successfully submit this problem.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

We don’t add test cases which try to break solutions with overflow.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
