### ISSUE TITLE
Explore cards navigation partially loading since 4 July 2023

### ISSUE THREAD

**Issue by bhasin85** [LeetCode-Feedback/LeetCode-Feedback#14545]
#### Your LeetCode username
bhasin85

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Content not loading 

#### Description of the bug

Explore cards navigation partially loading since 4 July 2023

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code
 
NA

#### Expected behavior

The left navigation panel should load and clickable 

#### Screenshots

<img width="1455" alt="Screen Shot 2023-07-05 at 6 59 02 am" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2552378/844e255e-41ce-4a3b-b4dd-9eccc59978d6">
<img width="1455" alt="Screen Shot 2023-07-05 at 7 00 43 am" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2552378/bfb354de-f878-48f1-abb1-68f4a98615c4">

**Comment by LC-Pam** [comment]
Thank you for your time. 

The issue should be fixed. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
