### ISSUE TITLE
LC 1493 Longest Subarray of 1's After Deleting One Element

### ISSUE THREAD

**Issue by dipeshyadav331** [LeetCode-Feedback/LeetCode-Feedback#14546]
#### Your LeetCode username

yadavdipesh

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

code passes but is failing for this test case [1] , the answer is 0 but the accepted solution is giving 1
https://leetcode.com/submissions/detail/986586962/

#### Code you used for Submit/Run operation

```
// Longest Subarray of 1's After Deleting One Element
class Solution {
    public int longestSubarray(int[] arr) {
        int sum = Arrays.stream(arr).sum();
        
        if(sum == 0) return 0;
        if(sum == 1) return 1;
        
        boolean enter = false;
        int max = 0 , cur = 0;
        
        int[] pa = new int[arr.length];
        
        for(int i = 0 ; i < arr.length ; i++){
            if(arr[i] == 1){
                cur++;
                pa[i] = cur;
            }
            else if(arr[i] == 0){
                cur = 0 ;
                pa[i] = cur;
            }
        }
        
        int[] sa = new int[arr.length];
        cur = 0;
        
        for(int i = arr.length - 1 ; i >= 0 ; i--){
            if(arr[i] == 1){
                cur++;
                sa[i] = cur;
            }
            else if(arr[i] == 0){
                cur = 0;
                sa[i] = cur;
            }
        }
        
        int mx = Arrays.stream(pa).max().getAsInt();
        
        if(mx == arr.length){
            return mx - 1;
        }
        
        max = Math.max(max , mx);

        for(int i = 1 ; i < arr.length - 1 ; i++){
            if(arr[i] == 0) max = Math.max(pa[i-1] + sa[i+1] , max);
        }
        
        return max;
    }
}
```

#### Language used for code

Java

#### Expected behavior

I returned 1 when the sum of array is 1 , but when the size of array is 1 and then the sum is 1 the answer would be 0 , which is not included in the test cases.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
