### ISSUE TITLE
Missing Test Case - 1493. Longest Subarray of 1's After Deleting One Element

### ISSUE THREAD

**Issue by Selenophile-ishan** [LeetCode-Feedback/LeetCode-Feedback#14547]
#### Your LeetCode username
ishandhingra85

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
My solution submits successfully but fails on testcase

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int longestSubarray(vector<int>& nums) {
        int c = -1,i=0,j=0,n = nums.size(),l = 0, ans = 0;
        while(i<n){
            if(nums[i]==0){
                j = c+1;
                c = i;
            }
            else if(nums[i]==1){
                l = (i-j);
                if(l==0)l=1;
            }
            i++;
            ans = max(ans,l);
        }
        return ans;
    }
};
```

#### Language used for code
C++ 

#### Expected behavior

it should have failed as it don't pass for test [1,1,0,0]

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by Selenophile-ishan** [comment]
I haven't received any Leetcoins

**Comment by Selenophile-ishan** [comment]
How much time it will take to Leetcoins to show up on my profile @LC-Pam
