### ISSUE TITLE
Bug in suggestion for the next 

### ISSUE THREAD

**Issue by Swetha-Baskaran** [LeetCode-Feedback/LeetCode-Feedback#14544]
After successful submission, the suggestion for the next question is to show a green pointer to indicate the problem is easy.
But the problem with "Copy List with Random Pointer" is actually a Medium level problem

#### Your LeetCode username
Swetha_Baskar

#### Category of the bug
Leetcode feature bug

#### Expected behavior
the suggestion for the next question should show the color of the pointer according to its difficulty level.

#### Additional context
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/74134426/87a03900-a08c-4bd4-bcb3-74f8d93d4b82)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/74134426/73dc0bb3-eeda-4559-89f8-085dc64f3ef0)

I hope this helps.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
https://project.feishu.cn/leetcode/us_tickets/create?parentUrl=%2Fleetcode%2FworkObjectView%2Fus_tickets%2FvHtNOOSVR
