### ISSUE TITLE
Missing test case bug in:- 1493. Longest Subarray of 1's After Deleting One Element

### ISSUE THREAD

**Issue by JoKeR-VIKING** [LeetCode-Feedback/LeetCode-Feedback#14554]
#### Your LeetCode username
JoKeR_VIKING

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [✅] Missing Test Cases 

#### Description of the bug
The code should not be accepted for the test case [1] or [0] and instead should give me runtime error/wrong answer. But it is accepted.

#### Code you used for Submit/Run operation
```
class Solution {
public:
    int longestSubarray(vector<int>& nums) 
    {
        vector<pair<int, int>> dp(nums.size());
        dp[0] = {nums[0] == 1, nums[0] == 1};
        dp[1] = {nums[1] == 0 ? 0 : dp[0].first + 1, nums[1] == 0 ? 0 : 1};

        for (int i=2;i<nums.size();i++)
        {
            if (!nums[i])
                continue;

            dp[i].first = dp[i - 1].first + 1;
            dp[i].second = max(dp[i - 1].second + 1, dp[i - 2].first + 1);
        }

        int ans = 0;

        for (auto& it : dp)
            ans = max(ans, it.second);

        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior
The code should give a runtime error for the case [1] or [0].

#### Additional context
Submission link where the code is accepted:- https://leetcode.com/problems/longest-subarray-of-1s-after-deleting-one-element/submissions/986689851/

Input: [1]
Output: 0

Input: [0]
Output: 0

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
