### ISSUE TITLE
1493. Longest Subarray of 1's After Deleting One Element

### ISSUE THREAD

**Issue by KhilariDivya23** [LeetCode-Feedback/LeetCode-Feedback#14555]
#### Your LeetCode username
Divya_khilari

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ✅] Missing Test Cases 

#### Description of the bug

Code should give runtime error but it gets accepted.

#### Code you used for Submit/Run operation

```
class Solution:
    def longestSubarray(self, nums: List[int]) -> int:
        n = len(nums)
        dp = [[0, 0] for i in range(n)]
        dp[0] = [int(nums[0] == 1), int(nums[0] == 1)]
        dp[1] = [0 if nums[1] == 0 else dp[0][0] + 1, 0 if nums[1] == 0 else 1]
        
        for i in range(2, n):
            if nums[i] == 0:
                continue
            dp[i][0] = dp[i-1][0] + 1
            dp[i][1] = max(dp[i-1][1] + 1, dp[i-2][0] + 1)
        
        ans = 0

        for i in range(n):
            ans = max(ans, dp[i][1])
        return ans

```

#### Language used for code
Python3

#### Expected behavior

The code should produce runtime error for testcase but gets accepted.

#### Additional context

https://leetcode.com/submissions/detail/986791216/

Input: [1]
Output: 0

Input: [0]
Output: 0

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
