### ISSUE TITLE
Problem 1441: Test program is wrong in Go

### ISSUE THREAD

**Issue by gandharvas** [LeetCode-Feedback/LeetCode-Feedback#1455]
The Test Program for Problem 1441 is wrong in GoLang. 

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Test Case

#### Description of the bug

Inputs: 
Target = [1,2]
n = 1

Expected Output Should Be: 
["Push"]

Expected Output from the Current Test program:
["Push","Push"]

#### Code you used for Submit/Run operation

```
func Equals(ele, target []int) bool {
  if len(ele) != len(target) {
    return false
  }

  for key, val := range ele{
    if val != target[key]{
      return false
    }
  }
  return true
}

func buildArray(target []int, n int) []string {
  ops := []string{}
  ele := []int{}
  targetSearch := make(map[int]bool)
  for _, no := range target{
    targetSearch[no] = true
  }

  for i:=1; i <= n; i++{
    if Equals(ele, target) {
      break
    }
    if targetSearch[i] {
      ops = append(ops, "Push")
      ele = append(ele, i)
    } else {
      ops = append(ops, "Push","Pop")
    }
  }
  return ops
}
```

#### Language used for code

GoLang

**Comment by lc-kay** [comment]
@gandharvas Can you please provide the code you used for the Submit operation? Thank you for your time!

**Comment by gandharvas** [comment]
> @gandharvas Can you please provide the code you used for the Submit operation? Thank you for your time!

I have updated the issue description with the code. Please let me know if I can contribute towards resolving this issue. I would be happy to fix.

**Comment by lc-kay** [comment]
Hi @gandharvas 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @gandharvas 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
