### ISSUE TITLE
Missing Test Case - 1493. Longest Subarray of 1's After Deleting One Element

### ISSUE THREAD

**Issue by zeyadms** [LeetCode-Feedback/LeetCode-Feedback#14557]
#### Your LeetCode username
zeyadhabib

#### Category of the bug
- [ 2] Missing Test Cases 

#### Description of the bug
The test cases of input array size 2 that contain ones are not covered for this problem

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    int longestSubarray(vector<int>& nums) {
        vector<int> left(nums.size(), 0), right(nums.size(), 0);
        left[0] = (int)(nums[0] == 1), right.back() = (int)(nums.back() == 1);

        for (int i = 1; i < nums.size(); ++i) {
            if (nums[i] == 1) {
                left[i] = left[i - 1] + 1;
            }

            if (nums[nums.size() - i - 1] == 1) {
                right[nums.size() - i - 1] = right[nums.size() - i] + 1;
            }
        }

        int ans = 0;

        for (int i = 1; i < nums.size() - 1; ++i) {
            ans = max({ans, left[i - 1] + right[i + 1], (int)(nums[i] == 1)});
        }

        return ans;
    }
};
```

#### Expected behavior
Solution was accepted but it is failing for test cases [1,1] => Should return 1, and [1,0] => Should return 1 as well.

#### Screenshots
<img width="493" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/125992412/10800123-0be9-4b02-a750-97858a18efd7">
<img width="635" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/125992412/032a0983-a325-41ce-b1fa-0ede65af7efb">

#### Additional context
Problem description: Given a binary array nums, you should delete one element from it.
Return the size of the longest non-empty subarray containing only 1's in the resulting array. Return 0 if there is no such subarray.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
