### ISSUE TITLE
Testcase NO.305 - Problem 50: Pow(x, n) - PHP

### ISSUE THREAD

**Issue by ZylalMinollari** [LeetCode-Feedback/LeetCode-Feedback#14556]
#### Your LeetCode username
ZYLAL

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
I encountered a problem while attempting to submit my solution for problem number 50, "Pow(x, n)," on LeetCode using PHP as the chosen programming language. The issue specifically arises with Testcase NO.305, where my solution returns an incorrect answer. However, when I tested the same solution locally, it produced the correct result.

#### Code you used for Submit/Run operation

```
// Pow(x, n)
class Solution {

    /**
     * @param Float $x
     * @param Integer $n
     * @return Float
     */
    function myPow($x, $n) {
    $result = 1;
    if($n == 0) {
        return $result;
    }
    $isNegative = false;
    if($n < 0) {
        $n = -$n;
        $isNegative = true;
    }

    while($n != 0) {
        if($n % 2 != 0) {
            $result *=  $x;
        }
        $x *= $x;
        $n = $n / 2;
    }
    return  $isNegative == false  ? $result : 1/$result;
    }
}

```

#### Language used for code
PHP

#### Expected behavior
For input x= 1.0000000000001 and n = -2147483648 in LeetCode I get an output 1.00000 but it excepted to 
be 0.99979.I have tried different solution but I always get this error.I also have tried in local environment
and work.

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
