### ISSUE TITLE
1493. Longest Subarray of 1's After Deleting One Element

### ISSUE THREAD

**Issue by winstonallo** [LeetCode-Feedback/LeetCode-Feedback#14553]
#### Your LeetCode username

winstonallo

#### Category of the bug
- [x ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

there is an empty testcase which stops the code from passing, i also tried a c solution that already passed and it doesn't work either, i dont think that testcase should be there

#### Code you used for Submit/Run operation

```
int longestSubarray(int* nums, int numsSize)
{
    if (numsSize == 0)
        return 0;

    int i = 0;
    int deleted = 0;
    int count = -1;
    int result = 0;
    int start = 0;
    if (nums[i] != 1 && nums[i] != 0)
        return 0;

    while (i < numsSize)
    {
        if ((nums[i] == 1) || (nums[i] == 0 && deleted == 0))
        {
            if (nums[i] == 0)
                deleted = 1;
            count++;
            i++;
        }
        else
        {
            if (count > result)
                result = count;

            count = -1;
            deleted = 0;
            i = ++start;
        }
    }

    if (count > result)
        result = count;

    return result;
}
```

#### Language used for code

C

#### Expected behavior

my output is empty, which is the same as the expected one

#### Screenshots

https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/136271426/dbf25138-92e0-4ac5-bc6e-4c5510bd38a9

https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/136271426/e87b0fb9-8715-45a8-b397-c015823d8411

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
