### ISSUE TITLE
Missing Test Case - 1493. Longest Subarray of 1's After Deleting One Element

### ISSUE THREAD

**Issue by IC-99** [LeetCode-Feedback/LeetCode-Feedback#14559]
#### Your LeetCode username
IC-99

#### Category of the bug
-  Missing Test Cases: [0,1,1,1,1,1]

#### Description of the bug
if the first value of nums is zero and all the other values are ones, then my code returns the wrong answer but I still pass all the test cases

#### Code you used for Submit/Run operation

```
class Solution:
    def longestSubarray(self, nums: List[int]) -> int:
        bonus = 0
        count1 = 0
        malus = 1
        last = nums[0]
        if last: count1 = 1
        res = 0
        for i in range(1, len(nums)):
            if nums[i]:
                count1 += 1
            else:
                malus = 0
                if last == 0:
                    bonus = 0
                else:
                    res = max(res, count1 + bonus)
                    bonus = count1
                    count1 = 0 
            last = nums[i]
        return max(res, count1 + bonus) - malus
```

#### Language used for code
Python3

#### Expected behavior

my code ignores the first value if equals to 0 then return: correct answer - 1 but i passed all the test cases. So I think [0,1,1,1,1,1] should be added

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
