### ISSUE TITLE
Missing Test Case - 1346. Check If N and Its Double Exist

### ISSUE THREAD

**Issue by L3THALop** [LeetCode-Feedback/LeetCode-Feedback#14565]
#### Your LeetCode username

sayantan259

#### Category of the bug

- [x] Missing Test Cases 

#### Description of the bug

For the following test case [10,2,7,3,0,0,-13] the output should be true. But in my code the output is showing false.But this test case is not included so the response is accepted.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
        sort(a.begin(),a.end());
        int n=a.size();
        if(a[0]==0 && a[1]==0) return true;
        for(int i=0;i<n;i++){
            if(a[i]!=0){
                if(binary_search(a.begin(),a.end(),2*a[i])) return true;
            }
        }
        return false;
    }
};
```

#### Language used for code

C++

#### Expected behavior

[10,2,7,3,0,0,-13] If this test case is added then my submitted code will not be accepted.

#### Screenshots

<img width="727" alt="Test Case" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/83490141/b674e340-212a-4029-990d-95cdeb3335b3">

**Comment by L3THALop** [comment]
The code submission AC link - https://leetcode.com/problems/check-if-n-and-its-double-exist/submissions/986940413/

**Comment by L3THALop** [comment]
The code submission AC link -
https://leetcode.com/problems/check-if-n-and-its-double-exist/submissions/986940413/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
