### ISSUE TITLE
Missing Test Case - 1493. Longest Subarray of 1's After Deleting One Element

### ISSUE THREAD

**Issue by Rajat2024** [LeetCode-Feedback/LeetCode-Feedback#14568]
#### Your LeetCode username  
rajat241302

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My Code was Accepted but When I run this Test Case 
[TestCase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/11960487/TestCase.txt) on the same Question it Gives TLE .My TestCase are based on given constraints.
This Test Case is Missing please add this Testcase

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int longestSubarray(vector<int>& nums) {
            int ans=INT_MIN;
        for(int i=0;i<nums.size();i++)
        {
                if(nums[i]==0)
                {
                        int sum=0;
                        for(int j=0;j<nums.size();j++)
                        {
                                if(j==i)
                                        continue;
                                if(nums[j]==1)
                                        sum++;
                                else
                                        sum=0;
                                ans=max(ans,sum);
                        }
                }
        }
            if(ans==INT_MIN)
                    return nums.size()-1;
            return ans;
    }
};
```

#### Language used for code
C++ 

#### Expected behaviour
My code is Accepted but it should give TLE on this 
[TestCase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/11960487/TestCase.txt) testcase

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/85948834/f2a0f897-a698-4b20-a3f6-704c498ddff1)

#### Additional context
TestCase is this

[TestCase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/11960487/TestCase.txt)

Submission Link -- https://leetcode.com/problems/longest-subarray-of-1s-after-deleting-one-element/submissions/987107411/

**Comment by Shashank-singh2002** [comment]
Yes it is giving TLE with your code
you, have to optimize it a bit.

here is an example of a java code which is running just fine with your TC :- 

class Solution {
  public int longestSubarray(int[] nums) {
    int l = 0;
    int count0 = 0;

    for (final int num : nums) {
      if (num == 0)
        ++count0;
      if (count0 > 1 && nums[l++] == 0)
        --count0;
    }

    return nums.length - l - 1;
  }
}

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
