### ISSUE TITLE
373. Find K Pairs with Smallest Sums. Every solution throws TLE + verification doesn't work.

### ISSUE THREAD

**Issue by morningducke** [LeetCode-Feedback/LeetCode-Feedback#14560]
#### Your LeetCode username
morningduck

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<vector<int>> kSmallestPairs(vector<int>& nums1, vector<int>& nums2, int k) { 
        priority_queue<vector<int>, vector<vector<int>>, greater<vector<int>>> pq;
        vector<vector<int>> res;
        for (const auto& i : nums1) {
            pq.push({i + nums2[0], i, nums2[0], 0});
        }
        while (k-- && !pq.empty()) {
            auto cur = pq.top();
            pq.pop();
            res.push_back({cur[1], cur[2]});
            if (cur[3] == nums2.size() - 1) continue;
            pq.push({cur[1] + nums2[cur[3] + 1], cur[1], nums2[cur[3] + 1], cur[3] + 1});
        }
        return res; 
    }
};
```
Other than this solution i've tried submitting many other accepted solutions made by other people for testing purposes. No solution i've tried got accepted.

#### Language used for code
C++

#### Expected behavior

Solution should either get accepted or rejected with coherent output. Current output just says "TLE 0/0 testcases passed" and shows a testcase with k = 10000 and both arrays filled with 1s. The same testcase doesn't throw TLE while running before submitting. Other people also have reported this problem happening.
Moreover, correct output while running the program before submitting always shows that the answer is wrong, even though it's right. Probably related to the fact that the "Expected" output box also seems to be broken because it's always empty.

#### Additional context

Also tried solutions with a different language (Python 3) which also suffers from the same problem.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

The issue is fixed. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
