### ISSUE TITLE
Missing Test Case - 196. Delete Duplicate Emails

### ISSUE THREAD

**Issue by VinesOP** [LeetCode-Feedback/LeetCode-Feedback#14563]
#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

While rare, there could be occasional bugs or technical issues on this question of LeetCode platform. In this problem my output is not showing on the leetcode answer section,the code runs successfully but after submitting the code it is showing only expected output and  not showing my code output.

#### Code you used for Submit/Run operation

```
# Write your MySQL query statement below
delete p1 from person p1,person p2 
where p1.email=p2.email and p1.id>p2.id;
```

#### Expected behavior

i want output of my code to be shown after code submission

#### Additional context

fix the bug

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
