### ISSUE TITLE
Missing Test Case - 209. Minimum Size Subarray Sum

### ISSUE THREAD

**Issue by sarankumaar** [LeetCode-Feedback/LeetCode-Feedback#14571]
#### Your LeetCode username

sarankumaarbg

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 
 category - Missing Test Cases 

#### Description of the bug

when the initial array has only one element eg([8]) and target is 7 ideally the output should be 1. But the code I wrote doesn't cover this test case but getting accepted.

#### Code you used for Submit/Run operation

```
class Solution:
    def minSubArrayLen(self, target: int, nums: List[int]) -> int:
        if sum(nums) < target:
            return 0
        if len(nums) == 1:
            return 1 if sum(nums) == target else 0
        left = 0
        total = 0
        minLen = len(nums)
        for idx in range(len(nums)):
            total += nums[idx]
            while total >= target:
                total -= nums[left]
                minLen = min(minLen,idx - left + 1)
                left += 1
        return minLen

```

#### Language used for code

Python3

#### Expected behavior

so the above code should fail for the test case nums = [8] and target = 7. but in contrast it is getting accepted. since Iam only checking if sum(nums) == target .

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/71329824/9e5b77c5-43a4-440d-9552-067e1a2ec34f)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
