### ISSUE TITLE
Editorial typos - 209. Minimum Size Subarray Sum

### ISSUE THREAD

**Issue by xelplogoog** [LeetCode-Feedback/LeetCode-Feedback#14570]
#### Your LeetCode username
c4tdog

#### Description of the bug
https://leetcode.com/problems/minimum-size-subarray-sum/editorial/
There are typos in words `initialize` and `window`

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2188302/729f2437-e90b-458a-b354-071abd9917a1)

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2188302/126b5674-9d72-4eea-8d30-1f2c82e70e07)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
