### ISSUE TITLE
Missing Test Case - 1419. Minimum Number of Frogs Croaking

### ISSUE THREAD

**Issue by yuzhanggithub** [LeetCode-Feedback/LeetCode-Feedback#14576]
#### Your LeetCode username
yuzhangleetcode

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x ] Missing Test Cases 

#### Description of the bug
not a bug, just missing test case

#### Code you used for Submit/Run operation
```
class Solution {
public:
    int minNumberOfFrogs(string croakOfFrogs) {
        vector<int> cnt(5, 0);
        int frogs = 0;
        int max_frogs = 0;

        for (const char c : croakOfFrogs) {
            const int n = string("croak").find(c);
            ++cnt[n];
            if (n == 0) {
                ++frogs;
                max_frogs = std::max(max_frogs, frogs);
            } else if (n == 4) {
                --frogs;
            } else {
                --cnt[n - 1];
                if (cnt[n - 1] < 0) {
                    return -1;
                }
            }
        }
        return frogs == 0 ? max_frogs : -1;
    }
};
```
I should still  have the following code in n == 4:
```
--cnt[n - 1];
                if (cnt[n - 1] < 0) {
                    return -1;
                }
```

#### Language used for code
C++

#### Expected behavior
given test case "ccckkk"
expected -1
actually 3
this test case is missing in submission, and my code without that part could still pass the test. 

#### Screenshots
test case ccckkk is missing

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
