### ISSUE TITLE
Missing Test Case - 121. Best Time to Buy and Sell Stock

### ISSUE THREAD

**Issue by creatorGod003** [LeetCode-Feedback/LeetCode-Feedback#14575]
#### Your LeetCode username
ashuranjan003

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language 
- [x] Missing Test Cases 

#### Description of the bug
I was doing problem 121 buy and sell stock - I. I have found this missing testcase [5,6,1,3] where my submitted code had given wrong output. 

#### Code you used for Submit/Run operation

```
class Solution {
    public int maxProfit(int[] prices) {
        
        PriorityQueue<Integer> pq = new PriorityQueue<>(Collections.reverseOrder());
        int[] map = new int[100001];

        int ind =0;
        for(int x: prices){
            pq.add(x);
            map[x]=ind++;
        }

        int profit = 0;
        for(int i=0;i<prices.length;i++){
            
            int x = pq.peek();

            if(x > prices[i] && map[x] > i ){
                if(profit<x-prices[i]) profit = x-prices[i];
            }
            if(x==prices[i] || map[x] < i){
                pq.remove();
            }

            // System.out.println(profit);
        }

        return profit;

    }
}

```

#### Language used for code
Java

#### Expected behavior
Expected output should be 2 but my code had given 1, which was not recognized by any of the leetcode testcases.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/83553214/89f3de16-8fd7-42bb-974a-66500d6a8ac6)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by creatorGod003** [comment]
That's great

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
