### ISSUE TITLE
Missing Test Case proves both solutions wrong - 621. Task Scheduler

### ISSUE THREAD

**Issue by davitescobedo** [LeetCode-Feedback/LeetCode-Feedback#14578]
#### Your LeetCode username

eldavimost

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

Using ["A","A","A","A","A","A","A","B","B","B","B","B","B","B","C","C","C","C","C","C","C","D","D","D","D","D","D","D","E","F","G","H"] (7 As, 7Bs, 5Cs, 5Ds, and 1 of E, F, G, H) and n=2, the result with both published solutions returns 32.
However, we can group the tasks as:
ABC, DAB, CDA, BCD, ABC, DAB, CDA, BEF, ABG, H
Which in total is only 28.

#### Expected behavior

The testcase should be configured as returning 28.
And both solutions should be changed. There's a O(n log m) - O(m) solution here: https://leetcode.com/problems/task-scheduler/solutions/373231/java-easy-to-understand-o-nlog-m-time-o-m-space-solution-with-explanation/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

The test you wrote has 7Cs and 7Ds.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
