### ISSUE TITLE
Incorrect Time Complexity For Solution - 1799. Maximize Score After N Operations

### ISSUE THREAD

**Issue by agrawalishaan** [LeetCode-Feedback/LeetCode-Feedback#14572]
#### Your LeetCode username
iarocks

#### Category of the bug
- [ ] Question
- [X ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The listed time complexity for the solution is wrong. This problem requires memoizing `4^n` states, and for each state, using a recurrence relationship to break it down into subproblems. The recurrence relationship is:
 Given a current state, we can try all pairs of numbers to remove. If we remove those numbers, we are left with a subproblem.

The author correctly identifies that for each of the `4^n` states, we have to iterate through `n^2` pairs of numbers to remove. However, for each of these pairs, we also need to shift our bitmask `n` times. The author did not include this in the time complexity, resulting in a total time complexity of `4^n * n^2 * log A`. The `log A` is an irrelevant factor in the issue I am bringing up, that is the time complexity for finding the greatest common denominator. The main issue lies with the author writing `n^2` instead of `n^3`.

I understand that bit shifts are treated as an O(1) operation, usually, because integers are 32 bits long. However, in this problem, we can't really treat this as the case, because the solution only works if we have more bits than the length of our array, as each bit needs to represent the presence or absence of one element from the array. If the constraint on n were slightly higher, such as >16, suddenly we would need to use a bigger number size to store more bits.

I get that normally discarding the O(32) is fine, but this is really vital to the problem. You can make a working solution without a DP bitmask, that is clearly n^3, and passes in time. I am happy to link to a working solution that uses naive array serialization and array mutation, that is functionally the exact same, but would be considered as `n^3` by everyone.

They also write this code:
```
for firstIndex in range(len(nums)):
    for secondIndex in range(firstIndex + 1, len(nums)):
        # We only choose those numbers which were not already picked.
        if (state >> firstIndex & 1) == 1 or (state >> secondIndex & 1) == 1:
            continue
        currentScore = (pairsFormed + 1) * math.gcd(nums[firstIndex], nums[secondIndex])
        stateAfterPickingCurrPair = state | (1 << firstIndex) | (1 << secondIndex)
        remainingScore = dp[stateAfterPickingCurrPair]
        dp[state] = max(dp[state], currentScore + remainingScore)
```
Clearly, if they are treating `secondIndex` as an n iteration, when they bit shift by `secondIndex` or `firstIndex`, it should also be treated as a third nested loop.

#### Language used for code
Python

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
