### ISSUE TITLE
Missing Test Case - 570. Managers with at Least 5 Direct Reports

### ISSUE THREAD

**Issue by sheetal-patne** [LeetCode-Feedback/LeetCode-Feedback#14579]
#### Category of the bug -Missing Test Cases
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
select e2.name from
Employee e1 inner join Employee e2
on e1.managerId = e2.id
group by e2.name 
having count(*)>=5
```

#### Expected behavior

The SQL query was accepted when submitted but when tried with the testcase it failed, so the submitted query must fail.

#### Additional context

Try the solution with below testcase it will fail, but the solution is still accepted by leetcode
```
{"headers": {"Employee": ["id", "name", "department", "managerId"]}, "rows": {"Employee": [[101, "John", "A", null],[102, "Dan", "A", 101], [103, "James", "A", 101], [104, "Amy", "A", 101], [105, "Anne", "A", 101], [106, "Ron", "B", 101],[111, "John", "A", null],[112, "Dan", "A", 111], [113, "James", "A", 111], [114, "Amy", "A", 111], [115, "Anne", "A", 111], [116, "Ron", "B", 111]]}}
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
