### ISSUE TITLE
Test Case Missing: 169. Majority Element

### ISSUE THREAD

**Issue by Sakshamsahu06** [LeetCode-Feedback/LeetCode-Feedback#14588]
#### Category of the bug
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Majority  Element
class Solution {
    public int majorityElement(int[] nums) {
        int c =0;
        int Mel = 0;
        for(int el: nums){
            if(c==0){
                Mel= el;
                c += 1;
            }

            else if(el==Mel)
            c +=1;

            else
            c -= 1;
        }
        return Mel;
    }
}
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by P-4-PRATYUSH-RANJAN** [comment]
ok now i know how this works
