### ISSUE TITLE
Missing Test Case - 1729. Find Followers Count

### ISSUE THREAD

**Issue by bhall48** [LeetCode-Feedback/LeetCode-Feedback#14585]
#### Your LeetCode username

bentall

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ X] Missing Test Cases 

#### Description of the bug

The question requests a result in ascending order by user_id, but there's not case to enforce that ordering. The code below was accepted.

#### Code you used for Submit/Run operation

```
-- count of followers
-- group by user_id
-- order by user_id

SELECT
  user_id
  ,COUNT(follower_id) [followers_count]
FROM followers
GROUP BY user_id
```

#### Language used for code

MSSQL

#### Expected behavior

The submission fails because it doesn't order the user_id

**Comment by bhall48** [comment]
There’s just needs to be a case where the natural order of user_id is not already sorted in ascending order. It could be the same as the first test case but just reversed.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Please provide the test case explicitly.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by bhall48** [comment]
user_id |  follower_id
3          | 1
2          | 1
1          | 2
1          | 3
