### ISSUE TITLE
209. Minimum Size Subarray Sum

### ISSUE THREAD

**Issue by Aditya-Naresh** [LeetCode-Feedback/LeetCode-Feedback#14581]
In the description **Follow up**: If you have figured out the O(n) solution, 
It should be O(n^2) because of the nested loop

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
