### ISSUE TITLE
题目 196. 删除重复的电子邮箱 无法进行评测

### ISSUE THREAD

**Issue by oucme** [LeetCode-Feedback/LeetCode-Feedback#14580]
**你的 LeetCode 用户名**
LEER

**Bug 类型**
- [x] 题目
- [x] 题解
- [x] 编程语言
- [ ] 缺少测试用例

**描述**
196. 删除重复的电子邮箱 无法进行评测，提交任何正确答案后都不能通过。

**你使用的语言**
MySQL

**你提交或者运行的代码**
```
DELETE p1 FROM Person p1,
    Person p2
WHERE
    p1.Email = p2.Email AND p1.Id > p2.Id
```

**期望行为**
解决问题，通过测试用例

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

Your code received Wrong Answer: https://leetcode.com/submissions/detail/988110711/
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
