### ISSUE TITLE
Missing Test Case - 1038. Binary Search Tree to Greater Sum Tree

### ISSUE THREAD

**Issue by eugene-utkin** [LeetCode-Feedback/LeetCode-Feedback#14596]
#### Your LeetCode username
evgeniy-utkin

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The wrong solution was accepted because problem is not covered with tests enough.
 

#### Code you used for Submit/Run operation

This is my solution:
```
def bst_to_gst(root, tail = 0)
    return if !root

    if root.right && root.right.val - root.val > 1 && root.right.left
        for i in (root.val+1...root.right.val)
            root.val += i
        end
    end
    
    node = bst_to_gst(root.right, tail)
    if node
        root.val += node.val
    else
        root.val += tail
    end

    bst_to_gst(root.left, root.val)

    return root
end
```

I propose to add this test to prevent this solution from passing:
`[4,1,12,0,2,5,14,null,null,null,3,null,10,null,15,null,null,null,11]`

#### Language used for code
Ruby

#### Expected behavior
My solution shouldn't be accepted.

#### Screenshots
![Screenshot 2023-07-07 151917](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/51461496/ccf516cb-7252-4b25-92ba-3b081843edb1)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
