### ISSUE TITLE
Typo in description - 597. Friend Requests I: Overall Acceptance Rate

### ISSUE THREAD

**Issue by apnoble** [LeetCode-Feedback/LeetCode-Feedback#1459]
#### Your LeetCode username

apnoble

#### Category of the bug
- [ ] Question
- [ ] Solution
- [X] Language

#### Description of the bug

There's a typo in the description of the questions.  After the tables, it says "Write a query to find the overall acceptance rate of requests rounded to 2 decimals, which is the number of acceptance **divide the number of requests.**" I believe it should say **"divided by** the number of requests"

#### Language used for code
SQL

#### Screenshots

<img width="626" alt="FriendRequests" src="https://user-images.githubusercontent.com/34991427/100198889-54b26a80-2eb1-11eb-861b-eea0bcc9526c.png">

#### Additional context

I apologize if I am wrong and this is not a typo. Thank you.

**Comment by lc-kay** [comment]
Hi @apnoble 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @apnoble 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
