### ISSUE TITLE
Missing Test Case - 209. Minimum Size Subarray Sum

### ISSUE THREAD

**Issue by umbrellait-Kirill-Stolpnik** [LeetCode-Feedback/LeetCode-Feedback#14591]
#### Your LeetCode username
Frikker

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
this code pass 16/20,
In 17 testcase minimal length of subarray is 7, not 8.
target = 213, nums = [12,28,83,4,25,26,25,2,25,25,25,12]

#### Code you used for Submit/Run operation

```
def min_sub_array_len(target, nums)
    return 0 if nums.sum < target

    ary = [nums.max]

    while ary.sum < target
        nums.delete_at(nums.index(nums.max))
        ary << nums.max
    end

    return ary.length
end
```

#### Language used for code
Ruby

#### Screenshots
<img width="567" alt="Снимок экрана 2023-07-06 в 23 43 45" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/99667130/1709c8c0-3e10-40ba-a256-0fe3b0414c12">

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
