### ISSUE TITLE
127. Word Ladder missing test cases

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#146]
**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
The solution got accepted but it should fail as it does not cover the following testcase:

"ymain"
"oecij"
[ "ymann", "yycrj", "oecij", "ymcnj", "yzcrj", "yycij", "xecij", "yecij", "ymanj", "yzcnj", "ymain"]

**What language is your code written in**
Python

**The code you submit/run**
```
class Solution(object):
    def ladderLength(self, beginWord, endWord, wordList):
        wordList=set(wordList)
        bfs=collections.deque([(beginWord,0)])
        vis=set([beginWord])
        alphabets=[chr(i) for i in xrange(97,122)]
        while bfs:
            word,level=bfs.popleft()
            if word==endWord:
                return level+1
            for j in xrange(len(word)):
                for char in alphabets:
                    temp=word[:j]+char+word[j+1:]
                    if temp in wordList and temp not in vis:
                        bfs.append((temp,level+1))
                        vis.add(temp)
        return 0
```

**Expected behavior**
Solution's answer : 0
Correct answer : 10

**Comment by CooperCooperCooper** [comment]
Hi @leet212,
Thank you for reaching out to us! I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @leet212,
Thank you for your time! We've used your test case contribution to improve our problem! To claim your reward for this contribution, please reach out to our [main support channel](https://support.leetcode.com/hc/en-us) with your username and this ticket. We appreciate your time and support!
