### ISSUE TITLE
Missing Test Case - 1423. Maximum Points You Can Obtain from Cards

### ISSUE THREAD

**Issue by Pranjalshivhare** [LeetCode-Feedback/LeetCode-Feedback#14600]
#### Your LeetCode username

[Hydrous]
(https://leetcode.com/Hydrous/)

#### Category of the bug
- [x] Question +
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

ans: Bug in the test case as per the given conditions

#### Description of the bug

For the coding question : Maximum Points you can obtain from class
For the code i have submitted, all the test cases passed except this: k=3, arr[6] = {100,40,17,9,73,75}
the output should be 157 but it is showing expected output should be "248", which is not the correct output. 

#### Code you used for Submit/Run operation

```

class Solution {
public:
    int maxScore(vector<int>& nums, int k) {
int ansL = 0;
        int ansR = 0;

        for(int i=0;i<k;i++){
            ansL = ansL + nums[i];
        }
        int x = r-k;

        for(int i=r;i>x;i--){
            ansR = ansR + nums[i];
        }
        
        return max(ansL,ansR);
    }
};
```
#### Language used for code

C++

#### Expected behavior

For the coding question : Maximum Points you can obtain from class
For the code i have submitted, all the test cases passed except this: k=3, arr[6] = {100,40,17,9,73,75}
the output should be 157 but it is showing expected output should be "248", which is not the correct output.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Pranjalshivhare** [comment]
https://leetcode.com/problems/maximum-points-you-can-obtain-from-cards/submissions/988613706/
This is the submission link of my code where it is showing error for the wrong testcase.

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
