### ISSUE TITLE
Missing Test Cases - 202. Happy Number

### ISSUE THREAD

**Issue by georgereuben** [LeetCode-Feedback/LeetCode-Feedback#14604]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The given testcases for **_202. Happy Number_** do not have complete coverage of the problem and incorrect submissions are accepted by the system.

#### Code you used for Submit/Run operation

```
// Happy Number
class Solution {
public:
    
    int squareDigits(int n){
        int sum=0;
        while(n){
            sum = sum + pow(n%10, 2);
            n = n/10;
        }
        return sum;
    }


    bool isHappy(int n) {
        while(n){
            n = squareDigits(n);
            if(n==1){
                return true;
            }
            else if(n%10 == 5){
                return false;
            }
        }
        return false;        
    }
};
```

#### Language used for code

C++

#### Expected behavior

The above submission is accepted by the online judge, but it does not return the correct value for the following testcases and many more. Some of these testcases need to be added to filter out these incorrect submissions.

387999
389799
389979
389997
397899
397989
397998
398799
398979
398997
399789
399798
399879

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
