### ISSUE TITLE
Missing Test Case - 1064. Smallest Integer Divisible by K

### ISSUE THREAD

**Issue by pratham273** [LeetCode-Feedback/LeetCode-Feedback#1461]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@pratham273 Please provide the code and the test case it failed on. Thank you for your time!

**Comment by lc-kay** [comment]
Hi @pratham273 ,
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
