### ISSUE TITLE
Repeated lines in the editorial of - 2551. Put Marbles in Bags

### ISSUE THREAD

**Issue by KrishChopra22** [LeetCode-Feedback/LeetCode-Feedback#14612]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
It's not a serious bug, but just found something missing in the editorial part. The below 2 lines are repeated in the editorial, maybe some description about MinScore is missing or it can be simply avoided.

#### Screenshot
![editorial-screenshot](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/77012237/ffe047ad-611a-4840-9cd0-0ec7c71c2056)

#### Language used for code
C++, Java and Python3

#### Additional context
*Either remove one of the two lines or mention some change.*

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
