### ISSUE TITLE
Missing Test Case - 121. Best Time to Buy and Sell Stock

### ISSUE THREAD

**Issue by HarshPurohit1260** [LeetCode-Feedback/LeetCode-Feedback#14619]
#### Wrong test case
Wrong test case : 

prices = [7,1,5,3,6,4]
Expected : 5

Expected result for this test case should be 7 as per following transaction:
Buy on day 2 (price = 1) and sell on day 3 (price = 5), profit = 5-1 = 4.
Buy on day 4 (price = 3) and sell on day 5 (price = 6), profit = 6-4 = 2.
Total profit : 7

#### Code you used for Submit/Run operation

```
class Solution {
    public int maxProfit(int[] prices) {
        int buyPointer, sellPointer, totalProfit = 0;

        if (prices.length > 0) {

            for (int i = 0; i < prices.length - 1; i++) {

                buyPointer = i;
                sellPointer = buyPointer + 1;

                if (prices.length > sellPointer + 1) {

                    for (int j = sellPointer + 1; j < prices.length; j++) {

                        if (prices[j] > prices[sellPointer]) {

                            sellPointer = j;
                            continue;
                        }
                        break;
                    }
                }

                if (prices[buyPointer] < prices[sellPointer]) {

                    totalProfit += prices[sellPointer] - prices[buyPointer];
                    i = sellPointer;
                    // System.out.println("buy day : " + buyPointer + " with price: " + prices[buyPointer]
                    //         + " sold at day : " + sellPointer + " with price : " + prices[sellPointer]);
                }
            }
        }
        return totalProfit;
    }
}
```

#### Language used for code

Java

#### Expected behavior

prices = [7,1,5,3,6,4]
Expected : 5

Expected result for this test case should be 7 as per following transaction:
Buy on day 2 (price = 1) and sell on day 3 (price = 5), profit = 5-1 = 4.
Buy on day 4 (price = 3) and sell on day 5 (price = 6), profit = 6-4 = 2.
Total profit : 7

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
