### ISSUE TITLE
Missing test case - 100: Same Tree

### ISSUE THREAD

**Issue by vorishirne** [LeetCode-Feedback/LeetCode-Feedback#14610]
#### Your LeetCode username

vorishirne

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My code got submitted. But I had a test case for which the code is still failing.

#### Code you used for Submit/Run operation

```
func isSameTree(p *TreeNode, q *TreeNode) bool {
    p_state := []*TreeNode{}
    q_state := []*TreeNode{}

    newCall := true

    if p==nil || q==nil{
        if q!=nil || p!=nil {
            return false
        }
    }

    for q!=nil  || len(q_state)>0 {
        if newCall{
            if p==nil || q==nil{
                if q!=nil || p!=nil {
                    return false
                }
                newCall=false
                continue
            }
            p_state = append(p_state,p)
            q_state = append(q_state,q)
            p = p.Left
            q=q.Left
            newCall = true
            continue
        }
        
            p = p_state[len(p_state)-1]
            p_state = p_state[:len(p_state)-1]

            q = q_state[len(q_state)-1]
            q_state = q_state[:len(q_state)-1]

            if q.Val != p.Val{
                return false
            } 
            p = p.Right
            q = q.Right
            newCall = true

    }
    return true
}

```

#### my code fails in this test case

```
p = [1,null,2]
q = [1]

expected = false

```

#### Language used for code

Golang

#### Expected behavior

Code should not had been accepted.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
