### ISSUE TITLE
Missing constraint : Leetcode 115. Distinct Subsequences

### ISSUE THREAD

**Issue by Ram-lankada** [LeetCode-Feedback/LeetCode-Feedback#14616]
#### Your LeetCode username
Greatestdeveloper 

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The solution for LeetCode question 115. Distinct Subsequences assumes that the length of String "s" is always greater than or equal to the length of String "t". However, this constraint is missing, leading to potential inaccuracies in the solution.

#### Code you used for Submit/Run operation
Code 1 : 
```
        // TABULATION APPROACH 
        int dp[][] = new int[s.length()+1][t.length()+1] ; 
        // for( int i = 0 ; i < dp.length ; i++ ) 
        //     dp[i][0] = 1 ; 
        Arrays.fill( dp[0] , 1 ) ; 

        for( int i = 1 ; i < dp.length ; i++ ) 
            for( int j = 1 ; j < dp[0].length ; j++ )
            {
                if( s.charAt(i-1) == t.charAt(j-1) ) 
                    dp[i][j] = dp[i-1][j-1] + dp[i][j-1] ; 
                else 
                    dp[i][j] = dp[i][j-1] ; 
            }

        return dp[s.length()][t.length()] ; 
```

#### Accurate Code assuming s.length() > t.length()
Code 2 : 
```
        // TABULATION APPROACH 
        int dp[][] = new int[s.length()+1][t.length()+1] ; 
        for( int i = 0 ; i < dp.length ; i++ ) 
            dp[i][0] = 1 ; 

        for( int i = 1 ; i < dp.length ; i++ ) 
            for( int j = 1 ; j < dp[0].length ; j++ )
            {
                if( s.charAt(i-1) == t.charAt(j-1) ) 
                    dp[i][j] = dp[i-1][j-1] + dp[i-1][j] ; 
                else 
                    dp[i][j] = dp[i-1][j] ; 
            }

        return dp[s.length()][t.length()] ; 
```
This code gets submitted with maximum beats. 
Now consider this scenario, if the hidden test cases contains strings in which t.length( ) > s.length( ) then the above code should not get submitted. 
Therefore it is a mandation to mention that 
` s.length( ) > t.length( ) `

#### Language used for code
Java 

#### Expected behavior
Code 1 was written assuming that  `t.length( ) > s.length( )` But that did'nt get submit
whereas Code 2 was written assuming that  ` s.length( ) > t.length( ) `  and it got submit maximum beats

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/91232198/2bfedfe3-0b0c-47f0-98bf-cda9d955cd9a)

#### Additional context
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/91232198/7d9c7f93-a704-4225-8639-5db39fd6d9d7)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

 There exists from both kinds of test cases.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by Ram-lankada** [comment]
The Question wasn't updated yet


And alos i didn't received the LeetCoins
