### ISSUE TITLE
Missing Test Case - 6919. Apply Operations to Make All Array Elements Equal to Zero

### ISSUE THREAD

**Issue by Lpx0** [LeetCode-Feedback/LeetCode-Feedback#14627]
#### Your LeetCode username

justdoit2

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets WA on the following testcase:
[0, 1, 0, 0, 1, 0] 
2

#### Code you used for Submit/Run operation

```
typedef long long ll;
const int N = 100010;
ll ans[N];
int n;
class Solution {
public:
    bool checkArray(vector<int>& nums, int k) {
        for(int i = 0; i < k; i++){
            ans[i] = 0;
        }
        n = nums.size();
        for(int i = 0; i < n; i++){
            ans[i%k] += nums[i];
        }
        bool ok = true;
        for(int i = 1; i < k; i++){
            if(ans[i] != ans[0]){
                ok = false;
                break;
            }
        }
        return ok;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Output: true
Expected: false

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
