### ISSUE TITLE
373. Find K Pairs with Smallest Sums

### ISSUE THREAD

**Issue by absolute-mess** [LeetCode-Feedback/LeetCode-Feedback#14629]
#### Your LeetCode username
 absolute-mess

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The constraints in the problem miss the worst test case and the editorial also fails on that, either change the limit or propose a new solution. 
https://drive.google.com/file/d/11gbAFH3YnzQ5RCS3uYlprQPeGSV076cu/view?usp=drive_link
It's basically the worst case, with nums1=[1,1,1...100000 times], nums2=[1,1,1...100000 times], k=10000

#### Code you used for Submit/Run operation

```
class Solution {
public:
vector<vector<int>> kSmallestPairs(vector<int>& nums1, vector<int>& nums2, int k) {
vector<vector<int>> ans;
priority_queue<pair<int, pair<int, int>>> pq; // max-heap to store the k smallest pairs
    for (int i = 0; i < nums1.size(); i++) {
        for (int j = 0; j < nums2.size(); j++) {
            int sum = nums1[i] + nums2[j];

            // If the priority queue size is less than k, add the pair
            if (pq.size() < k)
                pq.push({sum, {nums1[i], nums2[j]}});
            else if (sum < pq.top().first) {
                // If the current sum is smaller than the largest sum in the priority queue,
                // remove the largest sum and add the current sum
                pq.pop();
                pq.push({sum, {nums1[i], nums2[j]}});
            } else if (sum > pq.top().first) {
                // If the current sum is larger than the largest sum in the priority queue,
                // break the inner loop since sums will only increase from this point onwards
                break;
            }
        }
    }

    // Retrieve the k smallest pairs from the priority queue and store them in the answer vector
    while (!pq.empty()) {
        ans.push_back({pq.top().second.first, pq.top().second.second});
        pq.pop();
    }

    return ans;
}
};
```

#### Language used for code
 C++

#### Expected behavior

Time Limit Exceeded for valid constraints.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

We currently cannot add this test case due to technical issues.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
