### ISSUE TITLE
2772. Apply Operations to Make All Array Elements Equal to Zero

### ISSUE THREAD

**Issue by absolute-mess** [LeetCode-Feedback/LeetCode-Feedback#14628]
#### Your LeetCode username
 absolute-mess 

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The worst-case scenario is missing here. When n=100000 and k=50000, the below code should give TLE as it does 50000*50000 operations. The below code prints the mentioned test case.

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean checkArray(int[] numbers, int k) {
        int length = numbers.length;

        for (int i = 0; i < length - k + 1; i++) {
            if (numbers[i] > 0) {
                int minimum = numbers[i];
                for (int j = i; j < i + k; j++) {
                    numbers[j] -= minimum;
                    if (numbers[j] < 0) {
                        return false;
                    }
                }
            }
        }

        for (int i = length - k + 1; i < length; i++) {
            if (numbers[i] != 0) {
                return false;
            }
        }

        return true;
    }
}
```

#### Language used for code
 Java 

#### Expected behaviour
 
It should give Time Limit Exceeded Verdict, but it got Accepted for some users like bidisib440.
The code fails on this test case even for Java, add this testcase and rejudge.

```
#include<bits/stdc++.h>
using namespace std;
int main() {
	// freopen("output.txt", "w", stdout);
	cout<<'[';
	for(int i=0; i<100000; i++) {
		cout<<i+1;
		if(i!=99999) cout<<',';
	}
	cout<<']';
	cout<<"\n50000";
	return 0;
}
```

**Comment by yumkam** [comment]
Testcase should be
```
[0,1,2,...,99999]
50000
```
(just constant array won't expose n*k)
And to cover possible trivial modification, there should be reversed test case as well
```
[99999,99998,...,0]
50000
````

**Comment by absolute-mess** [comment]
Yes, my bad, but these test cases also pass in Java. I guess LeetCode should reduce the TL for D

**Comment by yumkam** [comment]
Are you *sure* you used complete testcase with n=1e5?
I just tried to run above (java) code in leetcode console, and this testcase consistently gives TLE.
Testcase generator (python3)
```python
#!/usr/bin/env python3
n=int(1e5)
print([*range(n)])
print(n//2)
```

**Comment by absolute-mess** [comment]
#include<bits/stdc++.h>
using namespace std;
int main() {
	freopen("output.txt", "w", stdout);
	cout<<'[';
	for(int i=0; i<100000; i++) {
		cout<<i+1;
		if(i!=99999) cout<<',';
	}
	cout<<']';
	cout<<"\n50000";
	return 0;
}

Yes, TL exceeds this test case. They should add this and rejudge the solutions.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

Unfortunately, we’re unable to add these test cases because of technical issues.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by absolute-mess** [comment]
How is this thing justified?
I mean, due to technical faults many participants passed O(N*K) solution for problem D, please find some way to add the test cases or remove the codes with O(N*K) solution.

**Comment by ArshadAQ** [comment]
@LC-Pam We owe a proper explanation here. Please help with the same!
