### ISSUE TITLE
Integer Overflow for 119. Pascal's Triangle II

### ISSUE THREAD

**Issue by TheSocraticParadox** [LeetCode-Feedback/LeetCode-Feedback#1462]
#### Your LeetCode username
jakobwwilson

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Question 119. Pascal's Triangle II has the constraint "0 <= rowIndex <= 40", but any rowIndex  input over 33 causes an integer overflow. 
Since the function is required to return a list of integers, the rowIndex should be limited to 33 or the function signature should be changed to handle larger numbers. 

#### Code you used for Submit/Run operation
```
public class Solution {
    public IList<int> GetRow(int rowIndex) 
    {
        IList<int> ret = new List<int>();
        ret.Add(1);
        if(rowIndex == 0)
            return ret;
        for(int i = 0; i < rowIndex; i++)
            ret = nextLine(ret);
        return ret;
    }
    
    private IList<int> nextLine(IList<int> prevLine)
    {
        IList<int> ret = new List<int>();
        int prev = 0;
        foreach(int i in prevLine)
        {
            ret.Add(prev + i);
            prev = i;
        }
        ret.Add(1);
        return ret;
    }
}
```
Using an input value of "40" for the test case.

#### Language used for code
C#

#### Expected behavior
Either the question should require "0 <= rowIndex <= 33", or the function signature should be changed to a long(64 bit int) and a test case should be added for inputs up to 40.

**Comment by lc-kay** [comment]
Hi @TheSocraticParadox 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @TheSocraticParadox 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
