### ISSUE TITLE
1898. Maximum Number of Removable Characters - Editorial Not Available

### ISSUE THREAD

**Issue by guptamohit1907** [LeetCode-Feedback/LeetCode-Feedback#14621]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by guptamohit1907** [comment]
Editorial Not available

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've submitted your feedback to the team.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
