### ISSUE TITLE
Missing Test Case - 73. Set Matrix Zeroes

### ISSUE THREAD

**Issue by ayush-aks** [LeetCode-Feedback/LeetCode-Feedback#14620]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
 Found only two test cases in the problem

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution:
    def setZeroes(self, matrix: List[List[int]]) -> None:
        """
        Do not return anything, modify matrix in-place instead.
        """
        temp = []

        for i in range(len(matrix)):
            for j in range(len(matrix[i])):
                if matrix[i][j] == 0:
                    temp.append(j)
        
        for i in range(len(matrix)):
            if 0 in matrix[i]:
                for k in range(len(matrix[i])):
                    matrix[i][k] = 0
            else:
                for _ in temp:
                    matrix[i][_] = 0
        return matrix
```

#### Language used for code
 Python3

#### Expected behavior
 Found just 2 test cases for the problem.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:


The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by ayush-aks** [comment]
In the problem, why not add a test case which contains all the diagonal elements as 0, might be fun!
