### ISSUE TITLE
Missing Test Case - 48. Rotate Image

### ISSUE THREAD

**Issue by ananditasinghh** [LeetCode-Feedback/LeetCode-Feedback#14637]
#### Test Case of 1x1 matrix missing 
- Rotate Image

- #include<bits/stdc++.h>
class Solution {
public:
    void rotate(vector<vector<int>>& matrix) {
        int n = matrix.size();
//TRANSPOSE OF THE MATRIX :
//TIME COMPLEXITY IS O(n/2 * n/2)
        for(int i = 0; i < n-1 ; i++){
            for(int j = i + 1 ; j < n; j++){
                swap(matrix[i][j], matrix[j][i]);
            }
        }
//REVERSE OF THE MATRIX 
//TIME COMPLEXITY IS O(n * n/2)
        for(int i = 0; i < n ; i++){
            reverse(matrix[i].begin(), matrix[i].end());
        }
    }
};

- c++
- Test case: [[9]] 

#### Description of the bug

One missing test case that could be added is a 1x1 matrix. The given test cases include 2x2 and 3x3 matrices, but it would be beneficial to test the implementation with the smallest possible matrix size.

#### Code you used for Submit/Run operation

```  #include<bits/stdc++.h>
class Solution {
public:
    void rotate(vector<vector<int>>& matrix) {
        int n = matrix.size();
//TRANSPOSE OF THE MATRIX :
//TIME COMPLEXITY IS O(n/2 * n/2)
        for(int i = 0; i < n-1 ; i++){
            for(int j = i + 1 ; j < n; j++){
                swap(matrix[i][j], matrix[j][i]);
            }
        }
//REVERSE OF THE MATRIX 
//TIME COMPLEXITY IS O(n * n/2)
        for(int i = 0; i < n ; i++){
            reverse(matrix[i].begin(), matrix[i].end());
        }
    }
};

```

#### Language used for code
 C++

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

 [[9]] already exists. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
