### ISSUE TITLE
Error in "Interview crash course data structures and algorithms, example 1466."

### ISSUE THREAD

**Issue by rpunet** [LeetCode-Feedback/LeetCode-Feedback#14634]
#### Your LeetCode username

rpunet

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The example 3 in section "Graphs DFS", problem "1466. Reorder Routes to Make All Paths Lead to the City Zero", states twice:
-  _To have fast O(1) checking for if a given edge is in connections, we can put the original directed edges in a set roads._
-  _If node -> neighbor is in the set, it means that it was in the original input and since it is pointing away from 0, we must increment our answer as it is an edge that needs to be flipped. The reason we put the original edges in a set is so that this check can be O(1)._

Then, it shows the code implementation, in particular in C++, it uses a <set>, which, unlike the <unordered_set> has a O(logN) complexity to find an element in it. The <unordered_set> can't be used in this case since the elements (<vector<int>>) are mutable and therefore not constructible as element of the <unordered_set>

#### Code you used for Submit/Run operation

```
unordered_set<vector<int>>           // compilation fails!
set<vector<int>>                     // O(logN) find complexity
```
#### Language used for code
 C++

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
