### ISSUE TITLE
Missing Test Case - 507. Perfect Number

### ISSUE THREAD

**Issue by quoocnhaan** [LeetCode-Feedback/LeetCode-Feedback#14631]
#### Your LeetCode username

username: quoocnhaan

#### Category of the bug
- [507 ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Last testcase ( #98 ) is null, it's bug

#### Code you used for Submit/Run operation

```

#### Language used for code
JAVA

class Solution {
    public boolean checkPerfectNumber(int num) {
        
        int sum = 0;
        for(int i = 2; i <= num; i++){
            if(num%i==0){
                sum+=num/i;
            }
        }
        return sum==num;
    }
}


#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/137284720/3d5448a6-bcb9-4d38-825e-60946b28cf49)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

It’s not null. Your code received TLE.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
