### ISSUE TITLE
Missing Test Case - 2772. Apply Operations to Make All Array Elements Equal to Zero

### ISSUE THREAD

**Issue by kamalkish0r** [LeetCode-Feedback/LeetCode-Feedback#14635]
#### Your LeetCode username

kamalkish0r

#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [x] Missing Test Cases 

#### Description of the bug

This problem has weak test cases. I wrote brute force code and it worked, but it should give tle.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool checkArray(vector<int>& arr, int k) {
        if (arr.back() > arr.front()) {
            reverse(arr.begin(), arr.end());
        }
        int n = arr.size();
        for (int i = 0; i + k <= n; ) {
            int mn = INT_MAX;
            for (int j = i; j - i + 1 <= k; j++) {
                mn = min(arr[j], mn);
            }
            
            for (int j = i; j - i + 1 <= k; j++) {
                arr[j] -= mn;
            }

            int l = i;
            for (int j = i; j - i + 1 <= k; j++) {
                if (arr[j] == 0) {
                    l++;
                }
                else {
                    break;
                }
            }
            
            if (l == i) {
                return false;
            }
            i = l;
        }
        
        int ok = 1;
        for (int i : arr) {
            ok &= i == 0;
        }
        return ok;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Expected TLE, but it got accepted!

#### Screenshots

<img width="1440" alt="Screenshot 2023-07-09 at 3 04 08 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/75755091/e7509858-9914-4578-bba0-6090c5cfcf9c">

#### Additional context

Here is one of the test cases where my solution gives tle.
https://drive.google.com/file/d/1oVg3Ixu90SbDpyy1GshkEWV-T_K3w68L/view?usp=sharing

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

Unfortunately, we’re unable to add these test cases because of technical issues.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by ArshadAQ** [comment]
@LC-Pam Could you help understand due to what technical issues this test case cannot be added?
This is an extremely bad experience for users who wouldn't even think about trying such a brute force solution expecting that it would obviously TLE!

**Comment by kamalkish0r** [comment]
Totally agree with @ArshadAQ's point, @LC-Pam what could possibly be the technical issue such that test case couldn't be added? It's was problem setters fault that they made such weak test cases, then it's tester fault who didn't tested properly, wait do you guys even test !!? I am saying this because this is very trivial test case there are many test cases I can provide for this problem on which it will get accepted where ideally it shouldn't.
Thousands of people wake up in morning to participate in these contests, why don't you guys take a little more responsibility?
I would like to suggest that it would be better if you could conduct these contests with **more transparency**, let users know who has contributed the problem, who was tester and all other sort of information. Also better communication with users if there is a technical issue from your side, maybe server crashed or how you guys are handling cheaters on this platform?
