### ISSUE TITLE
6919. Apply Operations to Make All Array Elements Equal to Zero

### ISSUE THREAD

**Issue by dsjong** [LeetCode-Feedback/LeetCode-Feedback#14630]
#### Your LeetCode username

dsjong

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I see wrong solutions that pass (e.g. print yes if and only if sum of numbers at each index mod k are the same). However, this not a sufficient condition to print yes, so some solutions answer yes when the answer is no

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool checkArray(vector<int>& nums, int k) {
        int n = nums.size();
        vector<long long> tot(n);
        for (int i = 0; i < n; i++) {
            tot[i%k] += nums[i];
        }
        for (int i = 1; i < k; i++) {
            if (tot[i] != tot[i-1]) return false;
        }
        return true;
    }
};
```

#### Language used for code

C++

#### Expected behavior

On the test case
```
[1, 1, 0, 0, 0, 1]
3
```
Returns true when the answer is false

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
