### ISSUE TITLE
Missing Test Case - 1832. Check if the Sentence Is Pangram

### ISSUE THREAD

**Issue by akashnigam-0** [LeetCode-Feedback/LeetCode-Feedback#14638]
#### Your LeetCode username
LeetCode :- akashnigam08

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

It provide output on the basis of number of alphabet,
 i.e it will provide true output if number of character in string is 26 though 
some character are missing or duplicated.

#### Code you used for Submit/Run operation
class Solution {
    public boolean checkIfPangram(String sentence) {
        int n = sentence.length();
        
        Set<Character> set = new HashSet<>();
        for (int idx = 0; idx < n; idx++) {
            Character c = sentence.charAt(idx);
            set.add(c);
        }
        
        return set.size() == 26;
    }
}

#### Language used for code
java

#### Expected behavior
It should provide false for testcase :- "ttequickbrownfoxjumpsoverthelazydog"

[
![Screenshot (246)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/81045723/4d536c72-530c-46fc-8a2a-ba85a3503455)
](url)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by akashnigam-0** [comment]
https://leetcode.com/problems/check-if-the-sentence-is-pangram/submissions/990148435/

**Comment by akashnigam-0** [comment]
https://leetcode.com/problems/check-if-the-sentence-is-pangram/submissions/990148435/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by akashnigam-0** [comment]
Ok

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

“ttequickbrownfoxjumpsoverthelazydog” is pangram. it still has 'h'.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
