### ISSUE TITLE
课程video player中途stuck，停止播放，20分钟出现十几次

### ISSUE THREAD

**Issue by huyanlulu** [LeetCode-Feedback/LeetCode-Feedback#14649]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
huyan_lulu

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
购买的system design interview课程video player中途stuck，停止播放，20分钟出现十几次，每次需要reload页面解决。

**你使用的语言**
C++

**你提交或者运行的代码**
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
        
    }
};
```

**期望行为**
描述你期望的结果

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
Hello～感谢反馈，这个问题将会提交至负责团队尽快复现并排查定位的。Github 仓库只用于反馈大家在本站学习过程中遇到的题目和题解问题，目前我们会暂时关闭该 issue，如有更多反馈和建议欢迎  [点击这里](https://support.leetcode.cn/hc/request/new/) 提交工单反馈，给您带来的不便敬请谅解。
