### ISSUE TITLE
Missing Test Case - 74. Search a 2D Matrix

### ISSUE THREAD

**Issue by panoslin** [LeetCode-Feedback/LeetCode-Feedback#1464]
#### Your LeetCode username

panoslin

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

I think, according to the constraints the question given, 
the following kind of test case should fail for the given code.
`
[[1,3,5,7],[10,11,16,20],[12, 13, 14, 15]]
15
`
But instead, it passes all the test case and return success.
 
#### Code you used for Submit/Run operation

```
// 74. Search a 2D Matrix
class Solution:
    def searchMatrix(self, matrix: List[List[int]], target: int) -> bool:
        if len(matrix) == 0:
            return False
        
        row, col = 0, len(matrix[0]) - 1
        
        while row < len(matrix) and col >= 0:
            if matrix[row][col] == target: return True
            elif matrix[row][col] < target: row += 1
            elif matrix[row][col] > target: col -= 1
        
        return False
```

#### Language used for code

Python 3

#### Expected behavior

This code may not pass this specific test case

**Comment by stormsunshine** [comment]
According to the description of the problem:

> This matrix has the following properties:
> - Integers in each row are sorted from left to right.
> - The first integer of each row is greater than the last integer of the previous row.

Therefore, the test case provided in this issue does not meet the second property of the matrix. This should not be a valid test case.

**Comment by panoslin** [comment]
That's right, I misread the constraints. Closing it
