### ISSUE TITLE
Missing Testcase - 2772. Apply Operations to Make All Array Elements Equal to Zero

### ISSUE THREAD

**Issue by sy10080** [LeetCode-Feedback/LeetCode-Feedback#14642]
#### Your LeetCode username

DarkChemist

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

There is missing testcases for this question that makes $O(n^2)$ solution to TLE

#### Code you used for Submit/Run operation

(Failed) Solution (obtained from [here](https://leetcode.com/discuss/general-discussion/3739089/bad-constraints-in-wc353-d)):
```
class Solution {
    public boolean checkArray(int[] numbers, int k) {
        int length = numbers.length;

        for (int i = 0; i < length - k + 1; i++) {
            if (numbers[i] > 0) {
                int minimum = numbers[i];
                for (int j = i; j < i + k; j++) {
                    numbers[j] -= minimum;
                    if (numbers[j] < 0) {
                        return false;
                    }
                }
            }
        }

        for (int i = length - k + 1; i < length; i++) {
            if (numbers[i] != 0) {
                return false;
            }
        }

        return true;
    }
}
```

Hack Case:
(Generated through script)
```
n = 10 ** 5
k = n // 2
diff = [0] * (n + 1)
for i in range(n - k + 1):
    diff[i] += 1
    diff[i + k] -= 1
ps = [0] * n
ps[0] = diff[0]
for i in range(1, n):
    ps[i] = ps[i - 1] + diff[i]
print(ps)
print(k)
```
Explanation: basically the above script generates the nums array with $[1, 2, 3, \dots, 50000, 50000, 49999, 49998, \dots, 3, 2, 1]$ and the value of $k$ is $50000$. 

#### Language used for code

Solution: Java
Testcase Generator: Python

#### Expected behavior

It will exceed time limit and should not be accepted.
However, the solution get accepted ([click here for the submission link](https://leetcode.com/problems/apply-operations-to-make-all-array-elements-equal-to-zero/submissions/990235926/))

#### Screenshots

N/A

#### Additional context

N/A

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

Unfortunately, we’re unable to add these test cases because of technical issues.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by sy10080** [comment]
Do you need the raw input of the testcase in order to add to the problem? If so, I will upload the file of the input and attach here. Thanks.
[input.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/12010003/input.txt)
