### ISSUE TITLE
Missing Test Case - 2770. Maximum Number of Jumps to Reach the Last Index

### ISSUE THREAD

**Issue by yashgautam12049** [LeetCode-Feedback/LeetCode-Feedback#14652]
#### Your LeetCode username
Yash_Gautam100

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug

If the test case is nums=[1,2,1] target=0
then it is not considering this test case 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    int maximumJumps(vector<int>& nums, int target) {
        int n=nums.size();
        vector<int>dp(n,-1);
        dp[0]=0;
        if(target==0 || n==0){
            return -1;
        }
        for(int i=1;i<n;i++){
            for(int jump=0;jump<i;jump++){
                if(abs(nums[i]-nums[jump])<=target && dp[jump]!=-1){
                    dp[i]=max(dp[i],dp[jump]+1);
                }
            }
        }
        if(dp[n-1]==0){
            return -1;
        }
        return dp[n-1];
    }
};
};
```

#### Language used for code

c++

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
