### ISSUE TITLE
Missing Test Case - 5. Longest Palindromic Substring

### ISSUE THREAD

**Issue by ajalck** [LeetCode-Feedback/LeetCode-Feedback#14658]
#### Your LeetCode username

ajalck

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 
Test Case

#### Description of the bug

The default test case 2 input is "cbbd" and the expected output is "bb". But when I run my code, the output shows "aba". Remember the letters a,b,a are not even in the input. I checked my answer in another code editor with the same code and got the correct answer. 

#### Code you used for Submit/Run operation

```
var (
	k, set = 0, 0
	once   bool
	ogs    string
)

func longestPalindrome(s string) string {
	if !once {
		ogs = s
		once = true
	}
	flag := 0
	r := []rune(s)
	for i, j := 0, len(s)-1; i < j; i, j = +1, -1 {
		if r[i] != r[j] {
			flag = 1
			break
		}
	}
	if flag == 0 {
		return s
	}  
  for k < len(ogs) {
		for set+2 != len(ogs)-k {
			set++
			return longestPalindrome(ogs[k : len(ogs)-set])
		}
		k++
		set = -1
	}
	return "no palindrome found" 
}
```

#### Language used for code

Go

#### Expected behavior

The output I expect is "bb", which is the right answer.

#### Screenshots

<img width="436" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/115230603/4c8209ec-c6f4-4bfd-a63f-b611aba7cb97">

#### Additional context

I request you to consider this doubt --> The 1st test case has two correct answers "bab" and "aba". The second answer "aba" is coming as the output in the second test case. Just notice it.

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
