### ISSUE TITLE
395. Longest Substring with At Least K Repeating Characters -- No description what to do in the invalid case

### ISSUE THREAD

**Issue by ZaydH** [LeetCode-Feedback/LeetCode-Feedback#14664]
#### Your LeetCode username

Zayd

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Problem `395. Longest Substring with At Least K Repeating Characters`

The problem description states that `Given a string s and an integer k, return the length of the longest substring of s such that the frequency of each character in this substring is greater than or equal to k.`

Note that the problem description does not describe what to return if no such substring exists or whether that is a valid test case.  If this is a valid test case, a possible solution is to return `0`; another possible solution is to return the length of `s`. 

Running this problem, one of the test cases is:

`s = weitong`
`k = 2`

Observe that each character in `weitong` appears only once so no substring satisfies the `k=2` condition. The output verifier expects the user to return 0 in this case but that is not specified in the description.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

N/A

#### Language used for code

N/A

#### Expected behavior

Update the description with a sentence similar to `If there does not exist a substring where each character's frequency is greater than or equal to k, return 0.`

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
