### ISSUE TITLE
Mistake in task description - 395. Longest Substring with At Least K Repeating Characters

### ISSUE THREAD

**Issue by cgsgak1** [LeetCode-Feedback/LeetCode-Feedback#1466]
#### Your LeetCode username

cgsgak1

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The description contains a mistake. It is written that
"Given a string s and an integer k, return the length of the longest substring of s such that the frequency of each character in this substring is **less than or equal to k**.",
but according to Example 2 it should be written
"Given a string s and an integer k, return the length of the longest substring of s such that the frequency of each character in this substring is **not less than k**."

#### Screenshots

![image](https://user-images.githubusercontent.com/34144576/100326793-790a6600-2fdb-11eb-9e96-4f3305f614bd.png)

**Comment by lc-kay** [comment]
@cgsgak1 Thanks for reaching out! Our content team was made aware of this issue and took the appropriate actions immediately. Thank you for your time!
