### ISSUE TITLE
String concatenation inside of loop, JS runner executes a function twice for no reason.

### ISSUE THREAD

**Issue by quirogak** [LeetCode-Feedback/LeetCode-Feedback#14669]
#### Your LeetCode username
quirogak

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The problem name is "Merge Strings Alternately", from "Ace Coding Interview with 75 Qs"
For an unknown reason, the JS runner executes the whole mergeAlternately twice, the line of code that seems to provoke this,
is the one that assign two concatenated values into a empty string (on each iteration this empty string is going to have the previously concatenated values), which is going to be returned as the final result.
I opened this bug report, because when i run the code on my Visual Studio Code + Nodejs IDE, it runs perfectly fine, i even tried on a CodePen and it also works fine.

#### Code you used for Submit/Run operation

```
const mergeAlternately = function (word1, word2) {
    const mergedLength = (str1, str2) => {
        if (str1.length > str2.length) return str1.length
        else return str2.length
    }
    const currentLength = mergedLength(word1, word2)
    let mergedStrings = ""
    for (let i = 0; i < currentLength ; i++) {
        mergedStrings = mergedStrings.concat(word1[i].concat("", word2[i]))
    }
    return mergedStrings
};
```

#### Language used for code
JavaScript

#### Expected behavior
I expect the function being called once, ergo, i expect the loop running the same number of times as currentLength. Because of this bug,  if currentLength is  N, the loop runs 2N, no matter what.

#### Screenshots
https://imgur.com/a/YlS7OLc

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
