### ISSUE TITLE
1180. Count Substrings with Only One Distinct Letter - Math Formula Broken 

### ISSUE THREAD

**Issue by matthewtuby** [LeetCode-Feedback/LeetCode-Feedback#14660]
#### Your LeetCode username
matthewtuby

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x]  Broken Math Formula

#### Description of the bug

In the Solution Page within Approach 2 the math formula seems to be broken.

#### Code you used for Submit/Run operation
-

#### Language used for code
-

#### Expected behavior
<img width="536" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/29383054/b620895c-ccee-4cde-8705-7b3f87ff0dea">

#### Screenshots

<img width="672" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/29383054/55eddd23-cf8f-4e60-9b71-9a826da0a291">

#### Additional context

Same bug appears on Safari 16, Firefox 114, Chrome 114

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
