### ISSUE TITLE
Missing Test Case - 456. 132 Pattern

### ISSUE THREAD

**Issue by SmartyMK** [LeetCode-Feedback/LeetCode-Feedback#14662]
#### Your LeetCode username
smarty_mk007
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

There are lot's of O(N^2) solution which should give TLE but they are accepted in this problem.
with better run time than O(NlogN) and O(N)

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean find132pattern(int[] nums) {
       
        if(nums==null||nums.length<3) return false;
        int[] min=new int[nums.length];
        int[] max=new int[nums.length];
        min[0]=nums[0];
        max[0]=nums[0];
        for(int i=1;i<nums.length;i++){
            if(nums[i]>=max[i-1]){
                max[i]=nums[i];
                min[i]=min[i-1];
            }
            else if(nums[i]<=min[i-1]){
                min[i]=nums[i];
                max[i]=max[i-1];
            }
            else{
                int j=0;
                for( j=i-1;j>=1;j--){
                    if(nums[j]>nums[i])
                        break;
                }
                if(j>=1&&min[j-1]<nums[i])
                    return true;
                max[i]=max[i-1];
                min[i]=min[i-1];
            }
        }
        return false;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Expected TLE, but acceped with 100% faster run time

#### Screenshots

![Screenshot (160)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/66221660/76aa5cba-a681-44cf-b381-47ec95fb2be7)

![Screenshot (161)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/66221660/6039e582-039f-49b4-994e-2d54908516b3)

#### Additional context

Testcase
https://drive.google.com/file/d/1aDFVw1abQXPuXQmKG-FvSc21w6IuBdsf/view?usp=sharing

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
