### ISSUE TITLE
395. Longest Substring with At Least K Repeating Characters

### ISSUE THREAD

**Issue by WindOfMind** [LeetCode-Feedback/LeetCode-Feedback#1467]
#### Your LeetCode username

WindOfMind

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The title states "Longest Substring with At Least K Repeating Characters", but the description contains the next: the frequency of each character in this substring is less than or equal to k. So, it seems there is a contradiction.

**Comment by lc-kay** [comment]
@WindOfMind Thanks for reaching out! Our content team was made aware of this issue and took the appropriate actions immediately. Thank you for your time!
