### ISSUE TITLE
Missing Test Case - 127. Word Ladder

### ISSUE THREAD

**Issue by Rajat2024** [LeetCode-Feedback/LeetCode-Feedback#14676]
#### Your LeetCode username

Rajat241302

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
________________________________________________________________________________________________________________________________________

My Code was accepted on given Problem. But I realized that it should give TLE  due to high complexity of my testcase which is within the given constraint

Suppose,
```
m = beginWord.size();
n = wordList.size(); 
```
then Time Complexity of my Code is ``` O(m*n*n) ```

Now, I Make my TestCase  [TestCase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/12010006/output1.txt) whose constraint is ``` m=10,n=5000 ```

So, Time Complexity is O(5000 * 5000 * 10) =250000000 in my code which is much higher than 1e8 .

In code I commented the part of time complexity

**Finally, I Want to add That please add my TestCase   [TestCase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/12010006/output1.txt)  so that higher complexity Code Should Not be submitted**

________________________________________________________________________________________________________________________________________
#### Code you used for Submit/Run operation

```
class Solution
{
public:
    
    int ladderLength(string beginWord, string endWord, vector<string> &wordList)
    {

        map<string, vector<string>> m;
        map<string, int> dist;
        int i, j, n = wordList.size(), b;
        string a;

        // from here Time Complexity O(n*n*m) = 5000*5000*10
        for (i = 0; i < n - 1; i++)
        {
            for (j = i + 1; j < n; j++)
            {
              // This will Traverse O(m) = 10;
                if (help(wordList[i], wordList[j]))
                {
                    m[wordList[i]].push_back(wordList[j]);
                    m[wordList[j]].push_back(wordList[i]);
                }
            }
        }

        // to here
        for (i = 0; i < n; i++)
        {
            if (help(beginWord, wordList[i]))
            {
                m[beginWord].push_back(wordList[i]);
                m[wordList[i]].push_back(beginWord);
            }
        }

        for (i = 0; i < n; i++)
        {
            if (help(endWord, wordList[i]))
            {
                m[endWord].push_back(wordList[i]);
                m[wordList[i]].push_back(endWord);
            }
            dist[wordList[i]] = INT_MAX;
        }
        queue<pair<string, int>> q;
        q.push({beginWord, 1});
        dist[beginWord] = 0;
        while (!q.empty())
        {
            a = q.front().first;
            b = q.front().second;
            q.pop();
            cout << a << endl;

            for (string c : m[a])
            {

                if (dist[c] > b + 1)
                {
                    q.push({c, b + 1});
                    dist[c] = b + 1;
                }
            }
        }

        if (dist[endWord] == INT_MAX)
            return 0;
        return dist[endWord];
    }
    bool help(string &s1, string &s2)
    {
        int count = 0;
        for (int i = 0; i < s1.length(); i++)
        {
            if (s1[i] != s2[i])
                count++;
        }
        if (count == 1)
            return true;
        else
            return false;
    }
};
```

#### Language used for code
**C++**

#### Expected behavior

Finally, I Want to add That please add my TestCase   [TestCase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/12010006/output1.txt)  so that higher complexity Code Should Not be submitted

#### Additional context

Submitted Link - https://leetcode.com/submissions/detail/991447381/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
