### ISSUE TITLE
Approach 3 Space complexity - 340. Longest Substring with At Most K Distinct Characters

### ISSUE THREAD

**Issue by PyroGenesis** [LeetCode-Feedback/LeetCode-Feedback#14670]
#### Your LeetCode username
burhanlakda

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The space complexity of Approach 3 is written as `O(n)` which seems to be incorrect. It should be the same as Approach 2 which is `O(k)` (technically both should be `O(min(n, k))` but since `n >> k` that doesn't make a huge difference)

This is because in Approach 3, we store the unique character counts for the largest sliding window encountered. At maximum, this would consists of `k+1` characters and its counts in the dictionary, which leads to a space complexity of `O(k)`

#### Code you used for Submit/Run operation
N/A

#### Language used for code
N/A

#### Expected behavior
N/A

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
