### ISSUE TITLE
Missing Test Case - 535. Encode and Decode TinyURL

### ISSUE THREAD

**Issue by Shubhranshu012** [LeetCode-Feedback/LeetCode-Feedback#14681]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

So here People Can return the input string as output string and the submission is successful ,But it should not be the case you Have to encode and then decode and then send the value;

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    map<string,string> mp;
    int num =0;
    // Encodes a URL to a shortened URL.
    string encode(string longUrl) {
        string add=to_string(num);
        num++;
        string temp="http://tinyurl.com/";
        add=temp+add;
        mp[add]=longUrl;
        return add;
    }

    // Decodes a shortened URL to its original URL.
    string decode(string shortUrl) {
        return mp[shortUrl];
    }
};


#### Language used for code
<!-- C++ -->


#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->
So here People Can return the input string as output string and the submission is successful ,But it should not be the case you Have to encode and then decode and then send the value;


#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->



#### Additional context
<!-- Add any other additional context about the bug. -->
So here People Can return the input string as output string and the submission is successful ,But it should not be the case you Have to encode and then decode and then send the value;

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Please provide the test case explicitly.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
