### ISSUE TITLE
Typo in Constraints description - 785. Is Graph Bipartite?

### ISSUE THREAD

**Issue by mrunal-upadhyay** [LeetCode-Feedback/LeetCode-Feedback#1468]
#### Your LeetCode username
mrunal

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
There is a typo error in the constraints 
```
1 <= graph.length <= 100
0 <= graphp[i].length < 100
0 <= graph[i][j] <= graph.length - 1
graph[i][j] != i
All the values of graph[i] are unique.
The graph is guaranteed to be undirected. 
```
There is no array by the name graphp. Rename graphp to graph.

#### Expected behavior
Correct the typo graphp to graph for the constraints for this problem.

**Comment by lc-kay** [comment]
Hi @mrunal-upadhyay 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @mrunal-upadhyay 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
