### ISSUE TITLE
Missing Test Case - 203. Remove Linked List Elements

### ISSUE THREAD

**Issue by ergonauta** [LeetCode-Feedback/LeetCode-Feedback#14683]
#### Your LeetCode username
ergonauta

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
Adding another test case to check if the code is able to remove all matching vals at the beginning of the linked list.

#### Code you used for Submit/Run operation
```
class Solution {
    public ListNode removeElements(ListNode head, int val) {
        if(head == null) {
            return null;
        }

        // Remove all starting items matching val
        while(head != null && head.val == val) {
            head = head.next;
        }

        // Check if we don't have an empty list
        if(head == null) {
            return null;
        }

        ListNode current = head;
        while(current.next != null) {
            if(current.next.val == val) {
                current.next = current.next.next;
            } else {
                current = current.next;
            }
        }

        return head;
    }
}
```

#### Language used for code
Java

#### Expected behavior
For the given list
[6,6,6,5]
And the val
6
I expect this output
[5]

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The judge working correctly. 

![Screen Shot 2023-07-12 at 3 32 33 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/37113bae-7f09-4e68-87e4-d4e77a97bfd6)

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
