### ISSUE TITLE
Editorial typo - 111. Minimum Depth of Binary Tree

### ISSUE THREAD

**Issue by xelplogoog** [LeetCode-Feedback/LeetCode-Feedback#14698]
#### Your LeetCode username
c4tdog

#### Description of the bug
https://leetcode.com/problems/minimum-depth-of-binary-tree/editorial/
I believe there is no such word as `childs` and it should be `children` :) (both Java and C++ sections)

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2188302/baa250d5-dc96-41a8-8b55-115d6cef82a4)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
