### ISSUE TITLE
Wrong description - 395. Longest Substring with At Least K Repeating Characters

### ISSUE THREAD

**Issue by hpplayer** [LeetCode-Feedback/LeetCode-Feedback#1469]
#### Your LeetCode username

myfavcat

#### Category of the bug
- [ x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The problem states `frequency of each character ... is less than or equal to k`, but actually it is looking for `frequency of each character ... is greater than or equal to k`

In the given example 
```
Input: s = "aaabb", k = 3    
Output: 3   
Explanation: The longest substring is "aaa", as 'a' is repeated 3 times.
```
If following the current statement, the output should be "bb".

**Comment by lc-kay** [comment]
@hpplayer Thanks for reaching out! Our content team was made aware of this issue and took the appropriate actions immediately. Thank you for your time!
