### ISSUE TITLE
63. 不同路径 II 的一个测试用例不是很合适

### ISSUE THREAD

**Issue by chenxygh** [LeetCode-Feedback/LeetCode-Feedback#147]
** Bug 类型**
- [+] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
`[[0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1],[0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0],[1,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,1],[0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0],[0,0,0,1,0,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0],[1,0,1,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0],[0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,1,0,0,0,1,0,1,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,0],[0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0],[0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0],[1,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,1,0,0,0,1,0,1,0,0,0,0,1],[0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0],[0,1,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0],[0,1,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,1,0,1],[1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0],[0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,1,1,0,1,0,0,0,0,1,1],[0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,1,0,1],[1,1,1,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1],[0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0]]`

这个测试用例在动态规划求解子问题中， 出现了子问题的解溢出 int 的情况。

`signed integer overflow: 1579748616 + 1053165744 cannot be represented in type 'int' (solution.c)`

这个是报错信息。

个人认为， 本题中， 最终解是由一些子问题的解相加而来， 而最终解的类型是 int ， 那么说明子问题的解就应该也是 int， 否则就会有导致最终解 int 溢出的风险。

虽然该测试用例， 最终解并没有用到上处所说的 int 溢出的那个子问题的解， 但是我认为这样的测试用例是不安全的和不合适的。

综上所述， 该测试用例应该被修改或者剔除。

而且， 如果 int 够用的话， 就可以实现原地算法了， 不需要额外空间， 而这， 也应该是题目本身所希望使用的算法。

**你使用的语言**
C

**你提交或者运行的代码**
```
// 问题代码
// 原地算法， 二维数组直接当作 DP 数组
// 会有 int 溢出的测试通不过的情况
int uniquePathsWithObstacles(int** obstacleGrid, int obstacleGridSize, int* obstacleGridColSize){
    int k = 0;
    while (k < obstacleGridColSize[0] && obstacleGrid[0][k] == 0) obstacleGrid[0][k++] = 1;
    while (k < obstacleGridColSize[0]) obstacleGrid[0][k++] = 0;

    for (int i = 1; i < obstacleGridSize; ++i) {
        obstacleGrid[i][0] = obstacleGrid[i - 1][0] == 0? 0: !obstacleGrid[i][0];
        for (int j = 1; j < obstacleGridColSize[0]; ++j) {
            obstacleGrid[i][j] = obstacleGrid[i][j] == 0? obstacleGrid[i][j - 1] + obstacleGrid[i - 1][j]: 0;
        }
    }

    return obstacleGrid[obstacleGridSize - 1][obstacleGridColSize[0] - 1];
}
```

```
// 借助两行 DP 数组，unsigned int 类型，  可以通过所有用例
int uniquePathsWithObstacles(int** obstacleGrid, int obstacleGridSize, int* obstacleGridColSize){
    unsigned int a[obstacleGridColSize[0]], b[obstacleGridColSize[0]];
    unsigned int *preResult = a, *result = b;
    int k = 0;
    while (k < obstacleGridColSize[0] && obstacleGrid[0][k] == 0) preResult[k++] = 1;
    while (k < obstacleGridColSize[0]) preResult[k++] = 0;

    for (int i = 1; i < obstacleGridSize; ++i) {
        result[0] = preResult[0] == 0? 0: !obstacleGrid[i][0];
        for (int j = 1; j < obstacleGridColSize[0]; ++j) {
            result[j] = obstacleGrid[i][j] == 0? result[j - 1] + preResult[j]: 0;
        }
        unsigned int *temp = result;
        result = preResult;
        preResult = temp;
    }

    return preResult[obstacleGridColSize[0] - 1];
}
```

**期望行为**
修改或者删除该测试用例

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认的～

**Comment by feiceh** [comment]
你好，该题只是中间结果会溢出，当前不做改动。我们会在后续的版本不断更新优化和提升我们的产品，给大家带来最佳的用户体验。

**Comment by chenxygh** [comment]
那好的， 了解了， 谢谢回复。
