### ISSUE TITLE
Error in description - 395. Longest Substring with At Least K Repeating Characters

### ISSUE THREAD

**Issue by lixiang2017** [LeetCode-Feedback/LeetCode-Feedback#1470]
#### Your LeetCode username
Xiang Lee

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

According to the description, the frequency of each character in the substring must be less than or equal to k (<=k) which seems to be the opposite of the expected result. Shouldn't it be greater than or equal to k (>=k) instead?

**Comment by lc-kay** [comment]
@lixiang2017 Thanks for reaching out! Our content team was made aware of this issue and took the appropriate actions immediately. Thank you for your time!
