### ISSUE TITLE
Missing Test Case - 213. House Robber II

### ISSUE THREAD

**Issue by Monty036** [LeetCode-Feedback/LeetCode-Feedback#14700]
#### Missing Test Cases
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

####
 ```
 class Solution {
public:
    int solve(vector<int> num){
        int rob1=0;
        int rob2=0;
        for(auto i:num){
            int temp=max(rob1+i,rob2);
            rob1=rob2;
            rob2=temp;
        }
        return rob2;
    }
    int rob(vector<int>& nums) {
        vector<int> v1 (nums.begin()+1,nums.end());
        vector<int> v2 (nums.begin(),nums.end()-1);
        return max(nums[0],max(solve(v1),solve(v2)));
    }
};
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

The code you provided works for [3,4].

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
