### ISSUE TITLE
Incorrect space complexity - 802. Find Eventual Safe States

### ISSUE THREAD

**Issue by przemek3d88** [LeetCode-Feedback/LeetCode-Feedback#14706]
#### Your LeetCode username
przemysaw2

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In solution 2 DFS, the adj list is not needed. We can just use the given graph. Because of that the space complexity should be changed to O(n), which is better than approach 1.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
