### ISSUE TITLE
Missing Test Case - 面试题 04.10. Check SubTree LCCI

### ISSUE THREAD

**Issue by sigaer** [LeetCode-Feedback/LeetCode-Feedback#14710]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
miraie

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述**
缺少测试用例
当t2为单个节点，没有子树时
此时t1的所有根节点中，只要存在一个节点的值以t2结尾，就会判断为true

**你使用的语言**

**你提交或者运行的代码**

**期望行为**

**屏幕截图**
![1](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73508033/52f34e62-80ed-43b5-9a34-8a9f9030b820)
![2](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73508033/bcb1b3e5-4aeb-44e4-b4d0-7b48b77630ed)
![3](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73508033/8af1f5cf-a5db-4a9e-acf9-3d992f59d850)

**额外的上下文**

**Comment by feiceh** [comment]
感谢反馈，当前题目已修复，积分奖励已发放。
