### ISSUE TITLE
Missing Test Case - 627. Swap Salary

### ISSUE THREAD

**Issue by madhuraj2121** [LeetCode-Feedback/LeetCode-Feedback#14720]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by husnainsaeed00** [comment]
There is no problem in the test case you can run that code its wroking fine.
Test cases are fine .

or you can ask any other question from me, am here to answer.
class Solution:
    def twoSum(self, nums, target):
        num_dict = {}
        
        for i in range(len(nums)):
            complement = target - nums[i]
            
            if complement in num_dict:
                return [num_dict[complement], i]
            
            num_dict[nums[i]] = i
        
        return []
