### ISSUE TITLE
Missing Test Case - 395. Longest Substring with At Least K Repeating Characters

### ISSUE THREAD

**Issue by Rrock-k** [LeetCode-Feedback/LeetCode-Feedback#1472]
#### Your LeetCode username
Rrock-k

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
It has to be "such that the frequency of each character in this substring is **more** than or equal to k" instead of "such that the frequency of each character in this substring is **less** than or equal to k"

**Comment by lc-kay** [comment]
@Rrock-k Thanks for reaching out! Our content team was made aware of this issue and took the appropriate actions immediately. Thank you for your time!
