### ISSUE TITLE
Missing Test Case - 1189. Maximum Number of Balloons

### ISSUE THREAD

**Issue by hemanth850** [LeetCode-Feedback/LeetCode-Feedback#14721]
#### Your LeetCode username
hemanth85

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

A missing test case of "blloo"
The below code gets accepted in leetcode

#### Code you used for Submit/Run operation

```
class Solution:
    def maxNumberOfBalloons(self, text: str) -> int:

        dic = {'b':0, 'l':0, 'o':0}

        for i in text:
            if i in 'balloon':
                if i in dic:
                    dic[i] += 1
                else:
                    dic[i] = 1
        dic['l'] = dic['l'] // 2
        dic['o'] = dic['o'] // 2

        return (min(dic.values()))
```

#### Language used for code

Python

#### Expected behavior

The above code should fail the testcase "blloo"

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
