### ISSUE TITLE
270. Closest Binary Search Tree Value - your own solution does not work

### ISSUE THREAD

**Issue by Kenzku** [LeetCode-Feedback/LeetCode-Feedback#14733]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

if I just copy and paste the solution "Approach 3: Binary Search, O(H) time", to the code submission area, it does not pass the test:

root =
[4,2,5,1,3]
target =
4.5
Output
5
Expected
4

#### Expected behavior

You shall check if the new root.val is smaller than the closet before replace the closet

e.g. 

```
    let value1 = Math.abs(val - target)
    let value2 = Math.abs(closest - target)
    if (value1 === value2) {
      closest = Math.min(val, closest)
    } else {
      closest = value1 < value2 ? val : closest;
    }
```

#### Screenshots

<img width="1020" alt="Screenshot 2023-07-13 at 14 55 41" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/1387249/83af6c95-b62d-43f9-8f83-407ffe4cd034">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've used your feedback to update the problem.

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback.

Please proved us with your LCCN username or profile link.

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!

**Comment by Kenzku** [comment]
hej, it is grand :)
