### ISSUE TITLE
Question - 207. Course Schedule

### ISSUE THREAD

**Issue by RohitSgh** [LeetCode-Feedback/LeetCode-Feedback#14736]
#### Your LeetCode username
RohitSgh

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Link given in [Hint](https://leetcode.com/problems/course-schedule/description/) is dead.

#### Expected behavior
Hint-2 gives https://class.coursera.org/algo-003/lecture/52 as hint. However, this link is dead. 

Instead https://www.cs.princeton.edu/~wayne/kleinberg-tardos/pdf/03Graphs.pdf can be given.

#### Screenshots
> ![https://leetcode.com/problems/course-schedule/description/](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/81853910/949262b9-441b-4e7b-a52a-a85823e4465b)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
