### ISSUE TITLE
268. Missing Number parameter sorting issue

### ISSUE THREAD

**Issue by Kenzku** [LeetCode-Feedback/LeetCode-Feedback#14732]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

https://leetcode.com/problems/missing-number/
when sorting the `nums` provided in the function, it sorts like a string, instead, they should be sorted like numbers

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

<img width="838" alt="Screenshot 2023-07-13 at 14 17 35" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/1387249/49918304-7e97-4026-9ee4-ecd5e8f786f3">

**Comment by husnainsaeed00** [comment]
class Solution:
    def missingNumber(self, nums):
        n = len(nums)
        missing = n

        # XOR operation with index and value
        for i, num in enumerate(nums):
            missing ^= i ^ num

        return missing
![Screenshot (19)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/79439328/4f85c4cd-fa68-42a6-9b5b-d0ae458727cb)


its working fine for me in python.

**Comment by husnainsaeed00** [comment]
I think you are right there could be test case issue for that problem in the case of javascript compiler.
![Screenshot (20)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/79439328/6e09e3b9-1527-49be-ace1-4411c9d93d5d)


that code is working fine on an online compiler

/**
 * @param {number[]} nums
 * @return {number}
 */
class Solution {
  missingNumber(nums) {
    let missing = nums.length;

    for (let i = 0; i < nums.length; i++) {
      missing ^= i ^ nums[i];
    }

    return missing;
  }
}

let nums = [3, 0, 1];
let solution = new Solution();
let result = solution.missingNumber(nums);
console.log("Missing number:", result);

**Comment by husnainsaeed00** [comment]
but for the leetcode giving that error

Line 31 in solution.js
        var ret = missingNumber(param_1);
                  ^
ReferenceError: missingNumber is not defined
    Line 31: Char 19 in solution.js (Object.<anonymous>)
    Line 16: Char 8 in runner.js (Object.runner)
    Line 22: Char 26 in solution.js (Object.<anonymous>)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
![Uploading Screenshot (21).png…]()

**Comment by husnainsaeed00** [comment]
yeah you are right Kenzku!

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
