### ISSUE TITLE
Missing Test Case - 1920. Build Array from Permutation

### ISSUE THREAD

**Issue by Akhil-kumar-Revu** [LeetCode-Feedback/LeetCode-Feedback#14731]
username :`21a31a05i6

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [1 ] Missing Test Cases 

#### Description of the bug

If we give an array having atleast one element greater than the size of the array. For example, consider nums[]={7,0,1}.
The given logic is ans[i]=nums[nums[i]].
For i=0,we get ans[i]=nums[7],since nums[0]=7.
So that nums[7] raises an exception "IndexOutOfBoundsException".
but my code is not applicable for some arrays like arr[]={7,3,2,1,0} and the output array will be arr[]={7,1,2,3,7}.Here '0' is missing in array.

#### Code you used for Submit/Run operation

```
// 1920.Build array from permutation.
class Solution {
    public int[] buildArray(int[] nums) {
        int n=nums.length;
        int ans[]=new int[n];
        for(int i=0;i<n;i++)
        {
            int a=nums[i];
            if(a>n)
                ans[i]=a;
            else
                ans[i]=nums[a];
        }
        return ans;
    }
}
```

#### Expected behavior

If we give an array having atleast one element greater than the size of the array. For example, consider nums[]={7,0,1}.
The given logic is ans[i]=nums[nums[i]].
For i=0,we get ans[i]=nums[7],since nums[0]=7.
So that nums[7] raises an exception "IndexOutOfBoundsException".

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

In constraints it’s mentioned: “0 <= nums[i] < nums.length”.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
