### ISSUE TITLE
1234. 替换子串得到平衡字符串

### ISSUE THREAD

**Issue by zmq4566** [LeetCode-Feedback/LeetCode-Feedback#14730]
func balancedString(s string) int {
smap := map[string]int{
		"Q": 0,
		"W": 0,
		"E": 0,
		"R": 0,
	}
	slen := len(s)
	for _, v := range s {
		smap[string(v)]++
	}
	mlen := len(smap)
	avg := slen / mlen
	num := 0
	for _, v := range smap {
		if v > avg {
			num += v - avg
		}
	}
	return num
}
<img width="436" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/27996841/d966e5c2-fe24-440f-8f5a-b249bc098092">
<img width="372" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/27996841/4fa4b497-dd71-4f1b-8855-e658af270788">

**Comment by feiceh** [comment]
你好，在与相关团队核实后：建议看看评论区：  "子串替换指的是连续子串替换，答案是3的前提是有连续的三个W。"
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
