### ISSUE TITLE
Wrong Test Case - 384. Shuffle an Array

### ISSUE THREAD

**Issue by suyogwani11** [LeetCode-Feedback/LeetCode-Feedback#14734]
#### Your LeetCode username
suyogwani11

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Wrong Test Cases 

#### Description of the bug

For [Shuffle an Array](https://leetcode.com/explore/interview/card/top-interview-questions-easy/98/design/670/) following test case fails due to wrong expected output.
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/52914289/6efdae80-a5b8-442a-a843-c0120f763185)

#### Code you used for Submit/Run operation

```
//   Shuffle an Array
class Solution(object):

    def __init__(self, nums):
        """
        :type nums: List[int]
        """
        self.nums = nums
        self.original = nums[:]
        

    def reset(self):
        """
        :rtype: List[int]
        """
        self.nums = self.original
        self.original = list(self.original)
        return self.nums
        

    def shuffle(self):
        """
        :rtype: List[int]
        """
        for i in range(len(self.nums)-1, 0, -1):
            j = random.randrange(i)
            self.nums[i], self.nums[j] = self.nums[j], self.nums[i]
        return self.nums
            
        


# Your Solution object will be instantiated and called as such:
# obj = Solution(nums)
# param_1 = obj.reset()
# param_2 = obj.shuffle()
```

#### Language used for code
Python

#### Expected behavior

Test case should have passed for given output.

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
