### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by chenlinin123** [LeetCode-Feedback/LeetCode-Feedback#14746]
class Solution:
    def twoSum(self, nums, target):
        dict = {}
        for i in range(len(nums)):
            if  target - nums[i] not in dict:
                dict[nums[i]] = i 
            else:
                return [dict[target-nums[i]],i]
#python3

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link.
The missing test case. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
