### ISSUE TITLE
Question - 269. Alien Dictionary

### ISSUE THREAD

**Issue by RohitSgh** [LeetCode-Feedback/LeetCode-Feedback#14743]
### Your LeetCode username
RohitSgh

### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

### Description of the bug

[Problem Description](https://leetcode.com/problems/alien-dictionary/description/) mentions that 

> You are given a list of strings `words` from the alien language's dictionary, where the strings in `words` are **sorted lexicographically** by the rules of this new language.

Now Example-3 suggests

<code><b>Input:</b> words = ["z","x","z"]
<b>Output:</b> ""
<b>Explanation:</b> The order is invalid, so return `""`.
</code>

If order can be invalid, then the claim that strings in words are **sorted lexicographically** is incorrect.

### Expected behavior

We can better rephrase like below

$\downarrow$

There is a new alien language that uses the English alphabet. However, the order among the letters is unknown to you.

You are given a list of strings `words` from the alien language's dictionary. Now it is claimed that the strings in `words` are **sorted lexicographically** by the rules of this new language.

If this claim is false/invalid, and given arrangement of string in `words` cannot correspond to any order of letters, **return `""`**

Otherwise, **return a string of the unique letters in the new alien language** _sorted in lexicographically increasing order by the new language's rules._ If there are multiple solutions, return any of them.

$\uparrow$

### Screenshots
> ![https://leetcode.com/problems/alien-dictionary/description/](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/81853910/ec2e6a0a-a241-46e7-9305-190dabc34764)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
