### ISSUE TITLE
Issue with problem statement

### ISSUE THREAD

**Issue by srivatsapillutla** [LeetCode-Feedback/LeetCode-Feedback#1474]
[Issue with problem statement.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/5602694/Issue.with.problem.statement.txt)

Please go through the issue pointed.

**Comment by lc-kay** [comment]
@srivatsapillutla Thanks for reaching out! Our content team was made aware of this issue and took the appropriate actions immediately. Thank you for your time!
