### ISSUE TITLE
1218. Longest Arithmetic Subsequence of Given Difference

### ISSUE THREAD

**Issue by Dheeraj20042003** [LeetCode-Feedback/LeetCode-Feedback#14758]
#### Your LeetCode username
Dheera100

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

for input : arr =[1,2,3,4] difference = 20
expected output =  1;
actual output  = 0;

As there is no subsequence in the given array  whose element  difference is 20  so the answer should be 0 but leetcode expected output  is 1.

#### Code you used for Submit/Run operation

```
// 1218. Longest Arithmetic Subsequence of Given Difference
class Solution {
public:
    int longestSubsequence(vector<int>& arr , int difference) {
        
        int ans=0;
         unordered_map<int,int>dp;
        
        for(auto it:arr)
         {
             dp[it] = dp[it-difference] + 1;

             ans = max(ans , dp[it]);
         }
      
      return ans;
    }
};
```

#### Language used for code

C++

#### Additional context

My Code has submitted successful but i think there will be some test case missing or incomplete information.

**Comment by chshivm007** [comment]
@Dheeraj20042003 
Basically, **a single element is also an Arithmetic Progression**.. doesn't matters how much the common difference is.!
Example : **2** is always an **AP** with common difference **n**, for all n belongs to **(-inf, inf)**.
