### ISSUE TITLE
Missing Test Case - 942. DI String Match

### ISSUE THREAD

**Issue by ShailyJain66** [LeetCode-Feedback/LeetCode-Feedback#14750]
#### Your LeetCode username
shailyjain66

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<int> diStringMatch(string s) {
        int n=s.size();
        vector<int>perm(n+1);
        int start=0;
        int end=n;
        for(int i=0;i<n;i++){
            if(s[i]=='I'){
                perm[i]=start++;
                
            }
            else if(s[i]=='D'){
                perm[i]=end--;
                  
            }

        }
      
        perm[n]=start;
        return perm;
        
        
    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
