### ISSUE TITLE
Missing Test Case - 1218. Longest Arithmetic Subsequence of Given Difference

### ISSUE THREAD

**Issue by bernikovich** [LeetCode-Feedback/LeetCode-Feedback#14756]
#### Your LeetCode username
bernikovich

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Missing test case
arr = [1,2,3,2,3]
difference = 1
output = 2
expected = 3

#### Code you used for Submit/Run operation

```
// 1218. Longest Arithmetic Subsequence of Given Difference
class Solution {
    func longestSubsequence(_ arr: [Int], _ difference: Int) -> Int {
        var sequences: [Int: Int] = [:] // Last element to length
        arr.forEach {
            if var currentSequenceLength = sequences[$0 - difference] {
                sequences[$0 - difference] = nil
                sequences[$0] = currentSequenceLength + 1
            } else {
                if sequences[$0] == nil {
                    sequences[$0] = 1
                }
            }
        }
        return sequences.values.max() ?? 0
    }
}
```

#### Language used for code
Swift

#### Expected behavior

My submission got approved, but it has a problem which can be detected in my test case.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
