### ISSUE TITLE
Wrong problem statement - 395. Longest Substring with At Least K Repeating Characters

### ISSUE THREAD

**Issue by ananya0504** [LeetCode-Feedback/LeetCode-Feedback#1475]
Your LeetCode username
ananya_0504

#### Category of the bug
- [ ] Question statement is wrong

#### Description of the bug

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@ananya0504 Thanks for reaching out! Our content team was made aware of this issue and took the appropriate actions immediately. Thank you for your time!
