### ISSUE TITLE
Missing TestCase 1218. Longest Arithmetic Subsequence of given Difference

### ISSUE THREAD

**Issue by Jeetaksh** [LeetCode-Feedback/LeetCode-Feedback#14759]
#### Your LeetCode username
Jeetaksh

#### Category of the bug

-  Missing Test Cases 

#### Description of the bug
My code got a clear AC with all the testcases present. However if I create a testcase myself, it failed. Hence the testcase needs to be added.

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/92541718/e140293a-805d-456a-b534-cca7c4992e55)
This testcase is currently not present and my AC solution fails this testcase. 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int longestSubsequence(vector<int>& arr, int difference) {
        int ret = 1, pre;
        unordered_map<int, int> umap;

        for(const auto &x: arr){
            pre = x - difference, umap[x] = umap.count(pre) ? 1 + umap[pre] : 1;
            if(pre == difference) umap.erase(pre);
            ret = max(ret, umap[x]);
        }

        return ret; 
    }
};
```

#### Expected behavior

The incorrect code is getting AC. With addition of the testcase I mentioned, it will give wrong answer.
https://leetcode.com/problems/longest-arithmetic-subsequence-of-given-difference/submissions/994196296/
This code is incorrect but gets AC as the testcase is missing.

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/92541718/78befda7-c8a3-409a-a96d-73c709259962)

The same code with the testcase I mentioned.
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/92541718/b29ee601-ff01-47ac-b2ab-924fbfdd9815)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
