### ISSUE TITLE
577 员工奖金

### ISSUE THREAD

**Issue by ambition-xx** [LeetCode-Feedback/LeetCode-Feedback#14760]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名
slug:beartwo
**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
描述你遇到的 bug
为什么不报一个具体的错误呢，就是一个执行出错

**你使用的语言**
oracle

**你提交或者运行的代码**
```
/* Write your PL/SQL query statement below */
select a.name, b.bouns
from employee a left join bouns b
on a.empid = b.empid
where nvl(b.bouns,0)<1000;

```

**期望行为**
通过

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/37329475/eafcba11-ebd0-493a-b75b-a56262a0372b)

**额外的上下文**
添加额外的上下文信息
https://leetcode.cn/problems/employee-bonus/?envType=study-plan-v2&envId=sql-free-50

**Comment by feiceh** [comment]
感谢反馈，当前题目已修复，奖励已发放～
