### ISSUE TITLE
Missing Test Case - 539. Minimum Time Difference

### ISSUE THREAD

**Issue by Raghav2800** [LeetCode-Feedback/LeetCode-Feedback#14762]
#### Your LeetCode username

callmecomder

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

all tests passing missing test case issue

#### Code you used for Submit/Run operation

```
class Solution {
    public int findMinDifference(List<String> timePoints) {
        HashSet<String> set=new HashSet<>();
        for(String s:timePoints)
        {
            if(!set.contains(s))
            {
                if(s.substring(0,2).equals("00"))
                {
                    set.add("24:"+s.substring(3,5));
                    set.add(s);
                }
                else if(s.substring(0,2).equals("01"))
                {
                    set.add("25:"+s.substring(3,5));
                    set.add(s);
                }
                else if(s.equals("00:00"))
                {
                set.add("00:00");
                set.add("24:00");
                }else{
                set.add(s);
                }
            }else{
                return 0;
            }
        }
        int min=Integer.MAX_VALUE;
        List<Integer> list=new ArrayList<>();
        for(String s:set)
        {
            String str=s.substring(0,2);
            int x=Integer.parseInt(str)*60+Integer.parseInt(s.substring(3,5));
            list.add(x);
        }
        Collections.sort(list);
        //System.out.println(list);
        for(int i=0;i<list.size()-1;i++)
        {
            if(list.get(i+1)-list.get(i)<min)
            {
                min=list.get(i+1)-list.get(i);
            }
        }
        return min;
    }
}
```

#### Language used for code
Java 

#### Expected behavior

missing test case is ["02:39","10:26","21:43"]

#### Additional context

![Image 14-07-23 at 8 05 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/92736287/7b77e486-33a5-42d8-a140-ded4fc5966c0)

**Comment by Raghav2800** [comment]
issue raised

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
