### ISSUE TITLE
Incorrect Description for Question - 395. Longest Substring with At Least K Repeating Characters

### ISSUE THREAD

**Issue by HereDrlv** [LeetCode-Feedback/LeetCode-Feedback#1476]
#### Your LeetCode username

a549414560

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

In the question description:  

_Given a string s and an integer k, return the length of the longest substring of s such that the frequency of each character in this substring is **less than or equal** to k._    

the _**less than or equal**_ should be **greater than or equal**. 
The question names "At Least K Repeating Characters" and the given examples show that we are considering characters repeat more than K times.

**Comment by lc-kay** [comment]
@HereDrlv Thanks for reaching out to us! Our team was made aware of this issue and took the appropriate actions immediately. Thank you for your time!
