### ISSUE TITLE
Missing text case in problem, 1751.  Maximum Number of Events That Can Be Attended II

### ISSUE THREAD

**Issue by abhay-lodhi** [LeetCode-Feedback/LeetCode-Feedback#14779]
#### Your LeetCode username
abhaylodhiab11

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
-  Missing Test Cases 

#### Description of the bug
According to the constraints, my solution(below) show give time limit exceeded as its time complexity is O(N*N*K), but it is getting AC.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    
    bool check(vector<int> &p1, vector<int> &p2){
        if(p2[0]<=p1[1]) return true;
        
        return false;
    }
    int f(vector<vector<int>> &e, int k, int ind,vector<vector<int>> &dp){
        
        if(k==0 || e.size()==ind) return 0;
        
        int res=0;
        
        if(dp[ind][k]!=-1) return dp[ind][k];
        
        
        
        for(int i=ind; i<e.size();++i){
            
            if(i==(e.size()-1) || (i<(e.size()-1) && !check(e[ind],e[i+1]))){
              res= max(res,f(e, k-1,i+1,dp)+e[ind][2]); 
                break;
            }
            
        }
        
        res= max(res, f(e,k,ind+1,dp));
        
        return dp[ind][k]= res ;
        
    }
    
    int maxValue(vector<vector<int>>& events, int k) {
        
        vector<vector<int>> dp(events.size()+1,vector<int>(k+1,-1));
        sort(events.begin(), events.end());
        
        return f(events,k,0,dp);
    }
};
```

#### Language used for code
 C++

#### Expected behavior
This solution should give TLE according to given constraints because its worst-case time complexity is O(N*N*K), but it is getting accepted which suggests that there are missing test cases.

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/87982903/9d90bd35-69cd-44a3-876c-99d9752fcc58)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/87982903/98ec263e-e10d-4576-bd27-148c4472eaa0)

#### Additional context
for checking purpose i'm giving c++ code which will generate the missing testcase, the below test case will generate the events array only(given in problem description), k can be taken as 2.
```
#include<bits/stdc++.h>
using namespace std;


int main() {
cout<<"[";
for(int i=1; i<=100000; ++i){
	cout<<"["<<i<<","<<100001<<","<<1<<"],";
	}
	
cout<<"[100001,100002,1]]";		

return 0;
}
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

We can't add the test case currently because of technical issues.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
