### ISSUE TITLE
Error in description - 395. Longest Substring with At Least K Repeating Characters

### ISSUE THREAD

**Issue by pranavsriram8** [LeetCode-Feedback/LeetCode-Feedback#1477]
#### Your LeetCode username
pranavsriram8

#### Category of the bug
- [x] Question

#### Description of the bug
Error in the description section of the question 
According to the description, the frequency of each character in the substring must be less than or equal to k (<=k) which seems to be the opposite of the expected result. It should be greater than or equal to k (>=k) instead

#### Code you used for Submit/Run operation
Not relevant  

#### Language used for code
Not relevant 

#### Expected behavior
Not relevant 

#### Screenshots
Not relevant 

#### Additional context
Not relevant

**Comment by lc-kay** [comment]
@pranavsriram8 Thanks for reaching out! Our content team was made aware of this issue and took the appropriate actions immediately. Thank you for your time!
