### ISSUE TITLE
Background code should be reevaluated for the following type of test case - 1221. Split a String in Balanced Strings

### ISSUE THREAD

**Issue by L3THALop** [LeetCode-Feedback/LeetCode-Feedback#14778]
#### Your LeetCode username

sayantan259

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 
- [x] Wrong code that checks for user output and expected output to be same

#### Description of the bug

Input: s = "RRLLLR"
In the above example, we can see the string has 3 balanced substrings, RRLL(from index 0 to index 3), RL(from index 1 to 2), and LR(from index 4 to 5)[ '0' based indexing].
But my submitted code as well as the checker code gives the output 2 for this test case which is wrong. 

#### Code you used for Submit/Run operation

```
// Split a String in Balanced Strings
class Solution {
public:
    int balancedStringSplit(string s) {
        int cnt=0,ans=0;
        for(int i=0;i<s.length();i++){
            if(s[i]=='R') cnt++;
            else cnt--;
            if(cnt==0) ans++;
        }
        return ans;
    }
};
```

#### Language used for code

**C++**

#### Expected behavior

If the background code is updated according to the question description then the answer would be proper.

#### Screenshots

<img width="960" alt="leet" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/83490141/20d09c42-db90-4f1e-8223-343b11976b50">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

The statement says “split”, not “count”.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
