### ISSUE TITLE
Editorial - 1136. Parallel Courses

### ISSUE THREAD

**Issue by RohitSgh** [LeetCode-Feedback/LeetCode-Feedback#14776]
#### Your LeetCode username
RohitSgh

#### Category of the bug
- [ ] Question
- [x] Editorial
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The pseudocode given in Approach-3 of [Editorial](https://leetcode.com/problems/parallel-courses/editorial/) has few errors.

#### Expected behavior
As per the logic given in implementation, most probably
- `max_length` should be initialized to 1
- it should be updated as `max_length = max(max_length, child_answer + 1)`

#### Screenshots

> ![https://leetcode.com/problems/parallel-courses/editorial/](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/81853910/7591187b-13af-4f58-b7b0-f7f4f85f5c27)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
