### ISSUE TITLE
Missing test case in problem, 1751. Maximum Number of Events That Can Be Attended II

### ISSUE THREAD

**Issue by maityamit** [LeetCode-Feedback/LeetCode-Feedback#14784]
#### Your LeetCode username
_maityamit

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
My Code gives AC in LeetCode, like 67/67 All Test Cases passed and submitted. But according to the given test case I design one test Case that give me TLE as in that same code used. 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    unordered_map<int,unordered_map<int,int>> mp;
    int binarySearch(int val,int idx,vector<vector<int>>& events){
        // F F F F T T T T T
        for(int i=idx+1;i<events.size();i++){
            if(events[i][0]>val) return i;
        }
        return events.size();
    }
    int helper(int idx,int k,vector<vector<int>>& events){
        if(k==0) return 0;
        if(idx>=events.size()) return 0;
        
        if(mp.count(idx) && mp[idx].count(k)) return mp[idx][k];
        
        int bs = binarySearch(events[idx][1],idx,events);
        int pick = events[idx][2]+helper(bs,k-1,events);
        int nPic = helper(idx+1,k,events);
        
        return mp[idx][k]=max(pick,nPic);
    }
    int maxValue(vector<vector<int>>& events, int k) {
        sort(events.begin(),events.end());
        return helper(0,k,events);
    }
};
```

#### Language used for code

C++

#### Expected behavior

As this test case will also give AC. Because events.length() is 1e5 and k=10 as in my designed Test Case and that match with given constraints limit means ```1 <= k * events.length <= 1e6``` . But it gives TLE. 

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/74618071/70006321-28da-4e07-8efd-7864fdf6aad7)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/74618071/4415b2ec-60b1-4304-93b6-28f4b4014def)

#### Additional context

For checking this, I am giving my designed Test Case: 
```
        cout<<"[";
	for(int i=0;i<100000;i++){
		cout<<"[68956,73140,58277]";
		if(i+1!=1e5) cout<<",";
	}
	cout<<"]"<<endl;
	cout<<10;
```

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
