### ISSUE TITLE
Content Issue : 24. Swap Nodes in Pairs

### ISSUE THREAD

**Issue by georgereuben** [LeetCode-Feedback/LeetCode-Feedback#14787]
#### Your LeetCode username

reubengeorge101

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The below solution is accepted by the online judge although it is mentioned in the question that the node values should not be changed. 

#### Code you used for Submit/Run operation

```
// Swap Nodes In Pairs
class Solution {
public:
    ListNode* swapPairs(ListNode* head) {
        ListNode* save = head;
        if(head == nullptr || head->next == nullptr)
            return head;
        while(head && head->next) {
            swap(head->val, head->next->val);
            head = head->next->next;
        }
        return save;
    }
};
```

#### Language used for code
C++ 

#### Expected behavior

The solution should have been rejected since the node values are swapped instead of the nodes themselves

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/69674713/9f32c98b-5a0a-4893-b2e1-64fa15918df5)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Please provide the test case explicitly.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by 4tet** [comment]
This issue also affects the Python/Python3 submissions and is **not** resolved.

It affects all test cases. No test case should pass when the code below is submitted, because as stated earlier in this issue, node values are swapped instead of the nodes themselves; yet, all test cases pass. The problem description states
>You must solve the problem without modifying the values in the list's nodes

which is exactly what my submission below *is* doing - it is modifying the values. And yet, my submission is getting accepted.

My Python/Python3 submission:
```
class Solution(object):
    def swapPairs(self, head):
        """
        :type head: ListNode
        :rtype: ListNode
        """
        first = head

        while first is not None and first.next is not None:
            # Swap the first and second nodes' values
            val = first.val
            first.val = first.next.val
            first.next.val = val
            
            # set first to the node 2 after it
            if first.next.next is None:
                return head
            
            first = first.next.next
        
        return head
```
