### ISSUE TITLE
Missing Test Case - 395. Longest Substring with At Least K Repeating Characters

### ISSUE THREAD

**Issue by ffrujeri** [LeetCode-Feedback/LeetCode-Feedback#1478]
#### Your LeetCode username
ffrujeri

#### Category of the bug
- [x ] Question
- [ ] Solution
- [x ] Language

#### Description of the bug
The statement of questions seems wrong considering the example.
Where we read:
Given a string s and an integer k, return the length of the longest substring of s such that the frequency of each character in this substring is **less than** or equal to k.
We should read **more than**

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@ffrujeri Thanks for reaching out! Our content team was made aware of this issue and took the appropriate actions immediately. Thank you for your time!
