### ISSUE TITLE
LC992（题目描述中字符乱码）

### ISSUE THREAD

**Issue by Caesar-Victory** [LeetCode-Feedback/LeetCode-Feedback#14781]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**yu-niang-niang**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [✅] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
中国区力扣992题，链接如下：https://leetcode.cn/problems/subarrays-with-k-different-integers/description/
其题目描述中的第十六个字符【中文为一个字符，整个英文单词为一个字符】，`整数k`，字母k的左侧有一个方形框

**你使用的语言**
无

**你提交或者运行的代码**
```
无
```

**期望行为**
整数 `k`

**屏幕截图**
原文字符如下：
给定一个正整数数组 nums和一个整数 k ，返回 num 中 「好子数组」 的数目。

**额外的上下文**
2023年7月15日22:15:21更新
内测群小伙伴反馈，我在本地的Firefox上测试，未登录状态下显示正常，灵动岛改版3.0显示正常，Firefox版本为：115.0.2
出错浏览器为edge，edge版本为：114.0.1823.82

**Comment by feiceh** [comment]
Hello～当前核实暂无法重现这个问题出现的情况，现在可以正常显示了吗？建议清空一下 cookie 缓存或换个浏览器再试试，积分奖励已经发放，感谢您的支持与反馈。

**Comment by Caesar-Victory** [comment]
目前显示正常，我将持续关注

**Comment by feiceh** [comment]
好的，目前我们会暂时关闭该 issue，如有更多反馈和建议欢迎与我们联系跟进。
