### ISSUE TITLE
Missing Test Case - 6. Zigzag Conversion

### ISSUE THREAD

**Issue by iamsanki1527** [LeetCode-Feedback/LeetCode-Feedback#14792]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by iamsanki1527** [comment]
class Solution {
    public String convert(String s, int numRows){
        if(numRows ==1) return s;

        String ans="";
        int step = 2 *numRows -2;
        for(int i =0; i<numRows;i++)
        {
            for(int j=i; j<s.length();j+= step)
            {
                ans +=s.charAt(j);
                if(i >=1 && i <=numRows -2 && j + (step -2*i) < s.length())
                {
                    ans += s.charAt(j+step-2*i);
                }
            }
        }
        return ans;
    }
}

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
