### ISSUE TITLE
Wrong description - 395. Longest Substring with At Least K Repeating Characters

### ISSUE THREAD

**Issue by DaisyMeng** [LeetCode-Feedback/LeetCode-Feedback#1479]
#### Your LeetCode username
daisysunmeng

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
The original description:
Given a string s and an integer k, return the length of the longest substring of s such that the frequency of each character in this substring is less than or equal to k.
The correct description should be 
Given a string s and an integer k, return the length of the longest substring of s such that the frequency of each character in this substring is **greater** than or equal to k.

**Comment by Kunal-Kayal** [comment]
If LeetCode can change "less than" to "greater than" then it will be matched with the description that is given to us. #1481

**Comment by lc-kay** [comment]
@DaisyMeng Thanks for reaching out! Our content team was made aware of this issue and took the appropriate actions immediately. Thank you for your time!
