### ISSUE TITLE
Code Execution returns a stale output even though nothing is returned from the main function

### ISSUE THREAD

**Issue by Dhru1Tanna** [LeetCode-Feedback/LeetCode-Feedback#148]
**What kind of the bug**
- [X] problem
- [ ] solution
- [ ] language

**Describe the bug**
While doing [first problem](https://leetcode.com/explore/featured/card/recursion-i/250/principle-of-recursion/1440/) from the recursive section I found a problem that the code execution is giving me wrong answers. I tried to print the variable I am returning and the Stdout gives the answer are what is expected but when I return the same variable it gives me wrong answer.
The strange part is, even if I am not returning anything the execution shows "Your Answer" as the wrong answer it showed me before.

**what language is your code written in**
Python

**The code you submit/run**
```
class Solution(object):
    output = []
    def printreverse(self, s, i):
        if i == len(s):
            return
        self.printreverse(s, i+1)
        self.output.append(s[i])
        # return self.output
    def reverseString(self, s):
        """
        :type s: List[str]
        :rtype: None Do not return anything, modify s in-place instead.
        """
        (self.printreverse(s,0))
        print("output", self.output)
```

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/26624409/79345583-edadfa00-7f4e-11ea-8770-42da4157b71b.png)

**Additional context**
I have attached a screenshot in which the main function doesn't return anything, still it is showing a stale answer in the Output. However, as I mentioned above stdout is what is expected.

**Comment by CooperCooperCooper** [comment]
Hi @Dhru1Tanna,
Thank you for reaching out to us! I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @Dhru1Tanna,
Thank you for your time. The code definition for this problem specifies that the solution should "modify s in-place" and "do not return anything". Please try them out. We appreciate your support.
