### ISSUE TITLE
153. Find Minimum in Rotated Sorted Array Accepts a Linear time solution, However,  it should accept logarithm solution as per description.

### ISSUE THREAD

**Issue by mmaashraf** [LeetCode-Feedback/LeetCode-Feedback#14804]
#### Your LeetCode username
mmaashraf

#### Category of the bug
- [ ] Question
- [ X] Solution
- [ ] Language
- [ X] Missing Test Cases 

#### Description of the bug
A linear time solution is being accepted. Either the time limit has not been set or the test cases are not robust enough to not consider linear time as the optimal solution. 
Optimal solution is Logarithmic solution.

#### Code you used for Submit/Run operation
'''
class Solution {
    public int findMin(int[] nums) {
        for(int i=1;i<nums.length;i++){
            if(!(nums[i]>nums[i-1])){
                return nums[i];
            }
        }
        return nums[0];
    }
}
'''

#### Language used for code
Java

<img width="757" alt="Screenshot 2023-07-15 at 7 38 25 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/37049007/53ed629f-97f2-4ea2-9eb9-292f8af60ece">

#### Expected behavior
It should have not accepted logarithmic solution as a valid submission. not a linear time solution.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link.


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by mmaashraf** [comment]
https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/submissions/995473372/
Hope this helps!

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

Please provide the test case explicitly.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
