### ISSUE TITLE
Missing Test Case - 2779. Maximum Beauty of an Array After Applying Operation

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#14808]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets WA on the following testcase:
[0]
1

#### Code you used for Submit/Run operation

```
class Solution:
    def maximumBeauty(self, nums: List[int], k: int) -> int:
        n = len(nums)
        m = max(nums)
        dp  = [0]*(m+2)
        for num in nums:
            l = max(0, num - k)
            r = min(m, num+k+1)
            dp[l] += 1
            dp[r] -= 1
        ret = 0
        c = 0
        for i in range(m+2):
            c += dp[i]
            ret = max(ret, c)
        return ret
```

#### Language used for code

Python3

#### Expected behavior

Output: 0
Expected: 1

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
