### ISSUE TITLE
Code Execution Issue

### ISSUE THREAD

**Issue by Kalyan457** [LeetCode-Feedback/LeetCode-Feedback#14803]
#### Your LeetCode username
IWillDo

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
Execution environment is behaving weird. System.out.println() is executing twice.

#### Code you used for Submit/Run operation

```
class Solution {
    public int mctFromLeafValues(int[] arr) {
        int res = 0;
        Stack<Integer> decStack = new Stack<>();
        System.out.println("Given Array is:" + Arrays.toString(arr));

        for (int i : arr) {
            System.out.println("i is:" + i);
            while (!decStack.isEmpty() && decStack.peek() <= i) {
                res += Math.min(decStack.peek(), i);
            }
            decStack.push(i);
        }
        
        return res;
    }
}
```

#### Language used for code
Java

#### Expected behavior
System.out.println() should execute only once.

#### Screenshots
<img width="888" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/48640903/840df573-a30a-47be-9d70-ca0a67791d19">

**Comment by guptamohit1907** [comment]
Hi @Kalyan457  I tried to run your code on intellij also it didnt give me the desired result . I would suggest better to check the code and debug it once after that only you might be able to get bettter understanding.

Your result is going inside the endless loop check this screenshot
<img width="1235" alt="Screenshot 2023-07-16 at 1 54 05 AM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/49603650/fdee147a-08e5-487a-a583-2b1eeedbae22">

**Comment by Kalyan457** [comment]
Hi @guptamohit1907, I understand that the code will produce incorrect result irrespective of where it is run. My main question is why System.out.println() executed twice?

**Comment by Kalyan457** [comment]
Also, for the input [6, 4, 2] it should not go into while loop at all.
