### ISSUE TITLE
Issue description does not match with the examples given

### ISSUE THREAD

**Issue by debashish-ghosh** [LeetCode-Feedback/LeetCode-Feedback#1480]
#### Your LeetCode username
debashish47

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
The examples given for the question are contradictory with the problem constraints.
[Longest Substring with At Least K Repeating Characters](https://leetcode.com/explore/challenge/card/november-leetcoding-challenge/567/week-4-november-22nd-november-28th/3544/)

> Given a string `s` and an integer `k`, return the length of the longest substring of `s` such that the frequency of each character in this substring is less than or equal to `k`.
\
Example 1:
**Input:** s = "aaabb", k = 3
**Output:** 3
Explanation: The longest substring is "aaa", as 'a' is repeated 3 times.
\
Example 2:
**Input:** s = "ababbc", k = 2
**Output:** 5
Explanation: The longest substring is "ababb", as 'a' is repeated 2 times and 'b' is repeated 3 times.

#### Expected behavior
In example 1, the output should be 5. The longest substring is "aaabb" (the whole string itself) as 'a' is repeated 3 times and 'b' is repeated 2 times. Both the frequencies are less than or equal to 3 (`k`)

In example 2, the output should be 4. There are 2 longest substrings, viz, "abab" and "abbc". All the characters in these substrings have frequencies less than or equal to 2 (`k`).

**Comment by lc-kay** [comment]
@debashish-ghosh Thanks for reaching out! Our content team was made aware of this issue and took the appropriate actions immediately. Thank you for your time!
