### ISSUE TITLE
Incorrect explanation of question 395

### ISSUE THREAD

**Issue by neerazz** [LeetCode-Feedback/LeetCode-Feedback#1481]
#### Your LeetCode username: 
neerazz90

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Given a string s and an integer k, return the length of the longest substring of s such that the frequency of each character in this substring is **less** than or equal to k.

But the question should be, "return the length of the longest substring of s such that the frequency of each character in this substring is **greater** than or equal to k."

Example 2:

Input: s = "ababbc", k = 2
Output: 5
Explanation: The longest substring is "ababb", as 'a' is repeated 2 times and 'b' is repeated 3 times.

If it is less then then in the example above **B is repeated 3 times, Then this is an incorrect explanation.**

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@neerazz Thanks for reaching out! Our content team was made aware of this issue and took the appropriate actions immediately. Thank you for your time!
