### ISSUE TITLE
题号： 215 数组中第k 个 最大的元素有一个测试用例数据错误

### ISSUE THREAD

**Issue by NetCloud2017** [LeetCode-Feedback/LeetCode-Feedback#14818]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
Uncode

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述**
有一个测试用例数据错误。 

**你使用的语言**
JavaScript

**你提交或者运行的代码**
```
 var findKthLargest = function(nums, k) {
    
    nums = nums.sort(function(a, b) {
        return a -b
    })
    let right = nums.length -k;
    return Math.max(nums[k -1], nums[right])
};
```

**期望行为**
2

**屏幕截图**

![力扣](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/32604559/8cd78dd0-3f29-42de-ba02-3849e1a4fa60)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
你好，在与相关团队核实后：暂不处理， 预期结果是正确的， 第二大的是 1
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
