### ISSUE TITLE
Missing Test Case - 448. Find All Numbers Disappeared in an Array

### ISSUE THREAD

**Issue by SwagnikGhosal03** [LeetCode-Feedback/LeetCode-Feedback#14815]
imsgghosal01

Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
The code I ran passed all the two test cases over there but when I submitted that it showed that it wasn't able to pass a particular 
test case which I'll mention.

#### Code you used for Submit/Run operation
```
import java.util.ArrayList;
import java.util.List;

class Solution {
    public List<Integer> findDisappearedNumbers(int[] nums) {
        elements(nums);
        return answer(nums);
    }
    static void elements(int arr[]){
      int i=0;
      while(i<arr.length-1){
        int correct=arr[i]-1;
        if (arr[correct]!=arr[i]) {
            int temp=arr[i];
            arr[i]=arr[correct];
            arr[correct]=temp;
        }
        else i++;
      }
    }
      static List<Integer> answer(int arr[]){
      List<Integer> ans= new ArrayList<>();
      for (int index = 0; index < arr.length; index++) {
        if(arr[index]!=index+1){
            ans.add(index+1);
        }
      }
      return ans;
    }
}
```

#### Language used for code
Java

#### Expected behavior
I expected my code to get submitted perfectly after passing the two mentioned test cases but it wasn't able to pass [4,3,2,7,7,2,3,1]
this particular test case

**Comment by SwagnikGhosal03** [comment]
<img width="960" alt="Screenshot 2023-07-16 203046" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/128494647/633cf45f-2484-4773-a698-fe6f6699f417">
<img width="960" alt="Screenshot 2023-07-16 203025" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/128494647/3ce31284-9f91-4dcd-bb01-f967abcbe8c1">


The two screenshots are here for better understanding

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
You wrote while(i<arr.length-1) instead of (i<arr.length) that's why the code not executing till 1(the last element)

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
You wrote while(i<arr.length-1) instead of (i<arr.length) that's why the code not executing till 1(the last element)
