### ISSUE TITLE
Problem 207. Course Schedule - Incorrect Language

### ISSUE THREAD

**Issue by agrawalishaan** [LeetCode-Feedback/LeetCode-Feedback#14822]
#### Your LeetCode username
iarocks

#### Category of the bug
- [ ] Question
- [ X] Solution
- [X ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The language of the description states:

```
A node remains in the DFS recursion stack until all of its branches (all nodes in its subtree) have not been explored. When we have examined all of a node's branches, i.e. visited all of the nodes in its subtree, the node is removed from the DFS recursive stack.
```

I believe this should say either: 
`A node remains in the DFS recursion stack while all of its branches (all nodes in its subtree) have not been explored`

or:

`A node remains in the DFS recursion stack until all of its branches (all nodes in its subtree) have been explored`

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've used your feedback to update the problem.

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback.

Please proved us with your LCUS username or profile link.

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!
