### ISSUE TITLE
Missing Test Case - 1751. Maximum Number of Events That Can Be Attended II

### ISSUE THREAD

**Issue by lone17** [LeetCode-Feedback/LeetCode-Feedback#14825]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Missing extreme test cases where len(events) = 10^5 and k = 10. Some solutions pass the test with len(events) = 10^5 and k = 1 (test case 57) with just a simple check for k == 1. For example this solution https://leetcode.com/problems/maximum-number-of-events-that-can-be-attended-ii/submissions/996231119/

#### Code you used for Submit/Run operation

```python
// Two Sum
# Recursive solution
class Solution:
    def maxValue(self, events: List[List[int]], k: int) -> int:
        if k == 1:
            return max(event[2] for event in events)
            
        events = sorted(events)
        # print (events)
        self.cached_results = {}

        @cache
        def getMaxValue(event_idx: int, k: int) -> int:
            # print(f"Entering function for {event_idx}, {k}")
            if k <= 0:
                return 0
            # if self.cached_results.get((event_idx, k)) != None:
            #     return self.cached_results[(event_idx, k)]
            
            max_value = 0
            for i in range(event_idx+1, len(events)):
                if events[i][0] > events[event_idx][1]: # if start_day >= end_day of this current event
                    # print(f"Entering recursive event here for {event_idx}, {i}, {k}")
                    max_value = max(getMaxValue(i, k-1), max_value)
            
            # print(f"Returning {max_value} + {events[event_idx][2]}")
            return_value = max_value + events[event_idx][2]
            # self.cached_results[(event_idx, k)] = return_value
            return return_value

        max_value = 0
        for idx, _ in enumerate(events):
            recursively_calculated_max_value = getMaxValue(idx, k)
            max_value = max(recursively_calculated_max_value, max_value) # Finding max value given this event will always be included
            # self.cached_results[(idx, k)] = max_value
        return max_value




        
```

#### Language used for code
Python3

#### Expected behavior
Accepted solutions should not TLE on the extreme test case. Such a test case can be constructed by using k = 10 in test case 57.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The specific missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by lone17** [comment]
@LC-Pam please find the test case here https://gist.github.com/lone17/563096eee34fd6dedab1c2c943f780e6
And the expected answer is `9999331`
