### ISSUE TITLE
Missing Test Case - 1480. Running Sum of 1d Array

### ISSUE THREAD

**Issue by pth190501** [LeetCode-Feedback/LeetCode-Feedback#1482]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@pth190501 Please provide the code you submitted and the test case that it failed on.

**Comment by lc-kay** [comment]
Hi @pth190501  ,
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
