### ISSUE TITLE
Missing Test Case - 1751. Maximum Number of Events That Can Be Attended II

### ISSUE THREAD

**Issue by przemek3d88** [LeetCode-Feedback/LeetCode-Feedback#14821]
#### Your LeetCode username
przemysaw2

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Approach 5: Top-down Dynamic Programming Without Binary Search is O(n^2k) time complexity and there is no test case, catching this.

#### Code you used for Submit/Run operation

Below is the Java implementation from the editorial.
```
class Solution {
    int[][] dp;
    public int maxValue(int[][] events, int k) {
        Arrays.sort(events, (a, b) -> a[0] - b[0]);
        int n = events.length;
        dp = new int[k + 1][n];
        for (int[] row : dp) {
            Arrays.fill(row, -1);
        }
        return dfs(0, 0, -1, events, k);
    }
    
    private int dfs(int curIndex, int count, int prevEndingTime, int[][] events, int k) {
        if (curIndex == events.length || count == k) {
            return 0;
        }
        
        if (prevEndingTime >= events[curIndex][0]) {
            return dfs(curIndex + 1, count, prevEndingTime, events, k);
        }
        
        if (dp[count][curIndex] != -1) {
            return dp[count][curIndex];
        }
        
        int ans = Math.max(dfs(curIndex + 1, count, prevEndingTime, events, k),
                           dfs(curIndex + 1, count + 1, events[curIndex][1], events, k) + events[curIndex][2]);
        dp[count][curIndex] = ans;
        return ans;
    }
}
```

And the test case generator in C++
```
printf("[");
for (int i = 1; i < 500000; i++) {
    printf("[%d,500000,1],", i);
}
printf("[500000,500000,1]]\n2");
```

#### Language used for code
C++ to generate a test case and Java for the solution

#### Expected behavior
The code from the editorial times out on this test case as the complexity of that solution is O(n^2k).

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

We can't add the test case currently because of technical issues.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
