### ISSUE TITLE
Editorial typos - 1751. Maximum Number of Events That Can Be Attended II

### ISSUE THREAD

**Issue by xelplogoog** [LeetCode-Feedback/LeetCode-Feedback#14823]
#### Your LeetCode username
c4tdog

#### Description of the bug
https://leetcode.com/problems/maximum-number-of-events-that-can-be-attended-ii/editorial/
There is a typo in word `create` **(2 on the page**: before approach 3 and 5)

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2188302/726e5c00-194e-4e6b-b680-3975292f68de)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
