### ISSUE TITLE
610. Triangle Judgement (Wrong answer)

### ISSUE THREAD

**Issue by sauravbharti021** [LeetCode-Feedback/LeetCode-Feedback#14831]
#### Your LeetCode username

sauravbharti21

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

Problem- 610. Triangle Judgement

#### Description of the bug

My mysql code gives the right answer, but it is not in order. I get Wrong Answer for that while the problem says "Return result table in any order."

#### Code you used for Submit/Run operation

```
 select a.x, a.y, a.z, "No" as "triangle" from  Triangle a
where
(a.x,a.y,a.z) not in (

    select * from Triangle b
    where b.x+b.y>b.z and b.y+b.z>b.x and b.x+b.z>b.y

)

union all 

select c.x, c.y, c.z, "Yes" as "triangle" from Triangle c
where 
(c.x, c.y, c.z) in (

    select * from Triangle b
    where b.x+b.y>b.z and b.y+b.z>b.x and b.x+b.z>b.y

)
```

#### Language used for code

mysql

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team

**Comment by sauravbharti021** [comment]
Hi Pam, See this screenshot and tell me where my answer is wrong, if the ordering is not required. I could not find why in discussion. 
![lc-sc](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/86503989/27dfefc6-3940-4113-a40d-8221e691509e)

vs

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/86503989/e0a09096-e099-42ec-b017-8d302ae22539)
