### ISSUE TITLE
Missing Test Case - 1296. Divide Array in Sets of K Consecutive Numbers

### ISSUE THREAD

**Issue by tomKPZ** [LeetCode-Feedback/LeetCode-Feedback#1483]
#### Your LeetCode username
tanderson050594

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language

#### Description of the bug

My incorrect solution was accepted.

#### Code you used for Submit/Run operation

```
class Solution:
    def isPossibleDivide(self, nums: List[int], k: int) -> bool:
        if len(nums) % k != 0:
            return False
        d = defaultdict(int)
        for n in nums:
            d[n] += 1
        counts = deque(sorted([[n, d[n]] for n in d]))
        while counts:
            prev = None
            for i, l in enumerate(counts):
                if i >= k:
                    break
                [n, c] = l
                if prev != None and ( n - prev != 1 or c < 1):
                    return False
                l[1] -= 1
                prev = n
            while counts and counts[0][1] == 0:
                counts.popleft()
        return True
```

#### Language used for code
Python3

#### Expected behavior
My solution should not have been accepted, because it doesn't pass this test case:
```
[1,1,2,2,3,3]
2
```
The output should be false, but my code returns true.  To fix my code, the following is needed after `prev = None`:
```
            if len(counts) < k:
                return False
```

**Comment by lc-kay** [comment]
@tomKPZ Thanks for reaching out! The code you submitted resulted in the wrong answer. After adding the part after prev = None, it was accepted. However, it did not fail on the test case you provided. Please submit an accepted solution of which the custom test case failed on and I will reopen this issue to investigate.
