### ISSUE TITLE
Missing Test Case - 628. Maximum Product of Three Numbers

### ISSUE THREAD

**Issue by Ethentix** [LeetCode-Feedback/LeetCode-Feedback#14855]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [yes] Missing Test Cases 

#### New Test Case
-7, -6, -5, -4 , -3, -2, -1, 0, 1, 2, 3, 4, 5

Output:
210

#### Code you used for Submit/Run operation

```
class Solution {
    public int maximumProduct(int[] nums) {
        int size = nums.length;
        Arrays.sort(nums);
        int last = nums[size-1]*nums[size-2]*nums[size-3];
        int first = nums[0]*nums[1]*nums[size-1];
        return Math.max(last,first);
    }
}
```

#### Language used for code
Java

#### Additional context

Two most negative numbers and a largest positive number can give a most highest product value.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

-7, -6, -5, -4 , -3, -2, -1, 0, 1, 2, 3, 4, 5 already exists. 


If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
