### ISSUE TITLE
Missing Test Case - 169. Majority Element

### ISSUE THREAD

**Issue by CocoCSforever** [LeetCode-Feedback/LeetCode-Feedback#14850]
#### Your LeetCode username

may18

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

For -10^9 <= nums[i] <= 10^9, missing edge case when array "nums" contain large numbers. If users use the bit manipulation approach, they need to figure out the numbers of bits we need to cover all use cases and current test cases pass when users give a wrong estimate of bit range.

#### Code you used for Submit/Run operation

```
class Solution {
    public int majorityElement(int[] nums) {
        int n = nums.length;
        int majority_element = 0;

        // i should be at least 32 but i = 31 or less works passes all current test cases
        for (int i = 0; i < 30; i++) {
            int bit = 1 << i;

            int bit_count = 0;
            for (int num : nums) {
                if ((num & bit) != 0) {
                    bit_count++;
                }
            }

            if (bit_count > n / 2) {
                majority_element |= bit;
            }
        }

        return majority_element;
    }
}
```

#### Language used for code

Java

#### Expected behavior

missing test case: [1000000000, 1000000000, -1000000000, -1000000000, -1000000000]
when I use it as input and click run, my code's output is as below:
Output: 73741824
Expected: -1000000000
But when I click submit, it passes. As I commented in my code, "i" should be at least 32 to cover the required range of inputs. And we need more test cases to ensure it works.

#### Screenshots

The codes in the two screenshots are the same. I can submit it successfully but it actually gives wrong output for my own test case.
<img width="1377" alt="Screen Shot 2023-07-17 at 11 46 40 AM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/107167996/b623f093-4432-4462-bb3a-d0133a48411a">
<img width="1415" alt="Screen Shot 2023-07-17 at 11 47 00 AM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/107167996/1800806e-fdeb-435f-b5ef-5c6ef3fb9b0b">

#### Additional context

Missing test cases may include but are not limited to this one.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
