### ISSUE TITLE
Missing Test Case - 2101. Detonate the Maximum Bombs

### ISSUE THREAD

**Issue by vijaysince89** [LeetCode-Feedback/LeetCode-Feedback#14858]
#### Your LeetCode username
vijaysince89

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [Y] Wrong Test Cases 

#### Code you used for Submit/Run operation
```
class Solution {
    public int maximumDetonation(int[][] bombs) {
        if(bombs==null)return 0;
        Map<Integer,List<Integer>> impacts=new HashMap<>();
        //Create an Adjecency Matrix that gives what detonates what
        for(int i=0;i<bombs.length;i++){
            for(int j=i+1;j<bombs.length;j++){
                double x1=bombs[i][0], y1=bombs[i][1], r1=bombs[i][2];
                double x2=bombs[j][0], y2=bombs[j][1], r2=bombs[j][2];
                double distance = Math.sqrt(Math.pow((x1-x2),2)+Math.pow((y1-y2),2));
                if(r1>=distance){
                    List<Integer> detonates=impacts.getOrDefault(i,new ArrayList<>());
                    detonates.add(j);
                    impacts.put(i,detonates);
                }
                if(r2>=distance){
                    List<Integer> detonates=impacts.getOrDefault(j,new ArrayList<>());
                    detonates.add(i);
                    impacts.put(j,detonates);
                }
            }
        }

        //DFS the Max Detonation can happen for all the bombs
        int maxDet=1;
        for(int i=0;i<bombs.length;i++){
            maxDet = Math.max(maxDet,dfs(i,impacts,new ArrayList<>()));
        }
        return maxDet;

    }

    private int dfs(int i,Map<Integer,List<Integer>> impacts, List<Integer> visited){
        if(visited.contains(i)) return 0;
        visited.add(i);
        List<Integer> impact=impacts.get(i);
        if(impact==null)return 0;
        for(Integer j: impact){
            dfs(j,impacts,visited);
        }
        return visited.size();
    }
}
```

#### Language used for code
Java

#### Expected behavior
Last Test case provided is wrong compared to the constraint provided. The number of bombs should be atleast 1, but we are getting no bombs for the last test case.

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/13484262/97dda6a9-2eee-408c-81b5-1d8c3e882edd)

#### Additional context
Please check the last test case. There is clearly some issue with the input. The Program just hangs and time limit gets exceeded.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Your code received TLE, https://leetcode.com/submissions/detail/997870229/
This could occur because the code is not optimized. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
