### ISSUE TITLE
Missing Test Case - 24. Swap Nodes in Pairs

### ISSUE THREAD

**Issue by rstudy211** [LeetCode-Feedback/LeetCode-Feedback#1485]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Runtime: 24 ms, faster than 94.43% of Python3 online submissions for Swap Nodes in Pairs.
Memory Usage: 14.2 MB, less than 37.57% of Python3 online submissions for Swap Nodes in Pairs.
#### Code you used for Submit/Run operation

```
// Two Sum
# Definition for singly-linked list.
# class ListNode:
#     def __init__(self, val=0, next=None):
#         self.val = val
#         self.next = next
class Solution:
    def swapPairs(self, head: ListNode) -> ListNode:
        curr,s = head,[] 
        while curr:
            s.append(curr.val)
            curr = curr.next
        for i in range(0,len(s)-1,2):
            s[i],s[i+1] = s[i+1],s[i]
        t = hea = ListNode()
        for j in s:
            t.next = ListNode(j)
            t = t.next
        return hea.next
            
            
    }
};
```

**Comment by lc-kay** [comment]
@rstudy211 When I attempted you submit your code, I received RTE. Please provide your code in [Playground.](https://leetcode.com/playground/new/empty). In addition, please provide the missing test case.

**Comment by lc-kay** [comment]
Hi @rstudy211,
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
