### ISSUE TITLE
题解上传图片失败，多次上传均图片损坏

### ISSUE THREAD

**Issue by Tiikee** [LeetCode-Feedback/LeetCode-Feedback#14853]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
橙橙橙

**Bug 类型**
- [ 336] 题目
- [ ] 题解
https://leetcode.cn/problems/palindrome-pairs/solutions/2347656/you-yu-suo-you-ti-jie-yi-ti-san-jie-qian-2sur/
- [ C++] 编程语言
- [ 无] 缺少测试用例

**描述**
上传题解，多次上传图片失败。编辑时预览无问题，上传后出现问题，怀疑是图片编码导致。
我尝试了之前传成功的复制到上面，下面图片还是正常的
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/95959942/f34e3828-7224-4199-ba38-0583cf1ed5d1)
当我编辑更新以后，就变成这样。下方的图片变成损坏格式，并且图片编码中间成了星号。而上方复制过来的之前上传成功的图片则仍然是好的。
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/95959942/df5908bb-f007-4f95-b9ec-993620899fc6)

**你使用的语言**
C++

**你提交或者运行的代码**
```
struct Tree {
    int index, childs[26];
} rever[1500000], order[1500000];

class Solution {
private:
    int reverCnt = 0, orderCnt = 0;
public:
    void insert(string &word, int index) {
        int p1 = 0, p2 = 0, ch = 0;
        int n = word.size();
        for(int i = 0; i < n; i++) {
            ch = word[i] - 'a';
            if(!order[p2].childs[ch]) {
                order[p2].childs[ch] = ++orderCnt;
            }
            p2 = order[p2].childs[ch];

            ch = word[n - 1 - i] - 'a';
            if(!rever[p1].childs[ch]) {
                rever[p1].childs[ch] = ++reverCnt;
            }
            p1 = rever[p1].childs[ch];
        }
        rever[p1].index = index;
        order[p2].index = index;
    }

    bool isPalindrome(const string& word, int i, int j) {
        while(i < j) {
            if(word[i++] != word[j--]) return false;
        }
        return true;
    }

    void searchRever(string &word, int index, vector<vector<int>> &ret) {
        int p = 0;
        for(int i=0; i<word.size(); i++) {
            int j = word[i] - 'a';
            if(rever[p].index && isPalindrome(word, i, word.size() - 1)) {
                ret.push_back({index - 1, rever[p].index - 1});
            }
            if(!rever[p].childs[j]) {
                return;
            }
            p = rever[p].childs[j];
        }
        if(rever[p].index && rever[p].index != index) {
            ret.push_back({index - 1, rever[p].index - 1});
        }
    }

    void searchOrder(string &word, int index, vector<vector<int>> &ret) {
        int p = 0;
        for(int i=word.size() - 1; i>=0; i--) {
            int j = word[i] - 'a';
            if(order[p].index && isPalindrome(word, 0, i)) {
                ret.push_back({order[p].index - 1, index - 1});
            }
            if(!order[p].childs[j]) {
                return;
            }
            p = order[p].childs[j];
        }
    }

    vector<vector<int>> palindromePairs(vector<string>& words) {
        for(int i=0; i<words.size(); i++) {
            insert(words[i], i+1);
        }
        vector<vector<int>> ret;
        for(int i=0; i<words.size(); i++) {
            searchRever(words[i], i+1, ret);
            searchOrder(words[i], i+1, ret);
        }
        memset(rever, 0, (reverCnt + 1)*sizeof(Tree)); reverCnt = 1;
        memset(order, 0, (orderCnt + 1)*sizeof(Tree)); orderCnt = 1;
        return ret;
    }
};
```

**期望行为**
题解更新或者提交后，图片上传成功

**屏幕截图**
上传题解，多次上传图片失败。编辑时预览无问题，上传后出现问题，怀疑是图片编码导致。
我尝试了之前传成功的复制到上面，下面图片还是正常的
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/95959942/f34e3828-7224-4199-ba38-0583cf1ed5d1)
当我编辑更新以后，就变成这样。下方的图片变成损坏格式，并且图片编码中间成了星号。而上方复制过来的之前上传成功的图片则仍然是好的。
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/95959942/df5908bb-f007-4f95-b9ec-993620899fc6)

**额外的上下文**
之前遇到过一次图片反复上传失败的问题，现在又遇到了。
试过换同学电脑，清缓存，重启，甚至重装浏览器，换浏览器都试过。这次应该和之前相似。希望及时处理。实在不行可以临时登录我的号，应该能更快复现问题。

**Comment by feiceh** [comment]
你好，在与相关团队核实后：下方的图片变成损坏格式且图片编码中间成了星号是命中了敏感词，建议重新上传，生成新的 link。

**Comment by Tiikee** [comment]
> 你好，在与相关团队核实后：下方的图片变成损坏格式且图片编码中间成了星号是命中了敏感词，建议修改一下原始文件名，再重新上传应该就可以正常展示了。

-------------------------------------------------------------
reply：
欧克欧克，感谢~
