### ISSUE TITLE
Missing Test Case - 73. Set Matrix Zeroes

### ISSUE THREAD

**Issue by ErrorAyush** [LeetCode-Feedback/LeetCode-Feedback#14862]
#### Your LeetCode username
Aeioush

#### Category of the bug

- [ ] Missing Test Cases 

#### Description of the bug

The solution is getting accepted for given valid testcase which should be not true.
Given Testcase is :
[[-4,-2147483648,6,-7,0],[-8,6,-8,-6,0],[2147483640,2,-9,-6,-10]]

#### Code you used for Submit/Run operation

```
class Solution {
    public void setZeroes(int[][] matrix) {
        int m = matrix.length;
        int n = matrix[0].length;
        for(int i=0;i<m;i++){
            for(int j=0;j<n;j++){
                if(matrix[i][j]==0){
                      for(int k=0;k<n;k++){
                          if(matrix[i][k]!=0)
                            matrix[i][k]=2147483640;
                      }
                      for(int k=0;k<m;k++){
                          if(matrix[k][j]!=0)
                            matrix[k][j]=2147483640;
                      }
                }
            }   
        }
        for(int i=0;i<m;i++){
            for(int j=0;j<n;j++){
                if(matrix[i][j]==2147483640){
                    matrix[i][j]=0;
                }
            }
        }
        System.out.print("[");
        for(int i=0;i<m;i++){
            System.out.print("[");
            for(int j=0;j<n;j++){
                System.out.print(matrix[i][j]+",");
            }
            if(i!=m-1){
                System.out.print("],");
            }
        }
        System.out.print("]]");
        
    }
}
```

#### Language used for code

Java

#### Expected behavior

The Testcase should have failed for given solution but the solution instead got accepted.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
