### ISSUE TITLE
707. Design Linked List

### ISSUE THREAD

**Issue by bozkayasalihx** [LeetCode-Feedback/LeetCode-Feedback#14865]
#### Your LeetCode username
mawareinthehouse

#### Category of the bug
- [ ] Question

#### Description of the bug

 the issue about when adding new node to linked list what you expect it should be increase the Size right but whenever i remove an node with `deleteAtindex` method its doesn't use update Size 

#### Code you used for Submit/Run operation

```
type Node struct {
  Val int 
  Next *Node
  Prev *Node
}

type MyLinkedList struct {
  Size int 
  Head *Node
  Tail *Node
}


func Constructor() MyLinkedList {
   return MyLinkedList{} 
}


func (this *MyLinkedList) Get(index int) int {
    if index < 0 || index >= this.Size {
        return -1
    }

    cur := this.Head; 
    for i:=0;i<index;i++ {
        cur = cur.Next
    }
    return cur.Val
}


func (this *MyLinkedList) AddAtHead(val int)  {
   newNode := &Node{
    Val: val,
   }
  if this.Head  == nil {
    this.Head = newNode
    this.Tail = newNode
  }else {
     cur := this.Head;
     newNode.Next = cur
     cur.Prev = newNode 
     this.Head = newNode
  }
  this.Size++    
}


func (this *MyLinkedList) AddAtTail(val int)  {
    newNode := &Node{
    Val: val,
  }
  
  if this.Head == nil {
    this.Head = newNode
    this.Tail = newNode
  } else {
    cur := this.Head
    for cur.Next != nil {
      cur = cur.Next
    }
    cur.Next = newNode
    newNode.Prev = cur
    this.Tail = newNode
  }
  this.Size++
}


func (this *MyLinkedList) AddAtIndex(index int, val int)  {
   if index < 0 || index > this.Size {
    return 
  }

  if index == 0 {
    this.AddAtHead(val)
    return 
  }

  if index == this.Size-1 {
     this.AddAtTail(val);
     return 
  }
  cur := this.Head;
  for i:=0;i<index-1;i++ {
    cur = cur.Next
  }
  newNode := &Node{
    Val: val,
  }
  PN := cur.Next
  cur.Next = newNode
  newNode.Next = PN
  PN.Prev = newNode
  newNode.Prev = cur
  this.Size++ 
}


func (this *MyLinkedList) DeleteAtIndex(index int)  { 
   if index < 0 || index > this.Size {
    return ;
  }
  if index == 0 {
    this.Head = this.Head.Next
    this.Size--
    return 
  }

  if index == this.Size-1 {
    PL := this.Tail.Prev
    PL.Next = nil 
    this.Size--
    return 
  }
  
  cur := this.Head; 
  for i:=0;i<index-1;i++ {
    cur = cur.Next
  }
  NN := cur.Next.Next;
  cur.Next = NN
  NN.Prev = cur
  this.Size-- 
}
``` 

#### Language used for code
 Go 

#### Expected behavior

in the case below it should be like this ```[null,null,null,null,2,null,3]```
```
["MyLinkedList","addAtHead","addAtTail","addAtIndex","get","deleteAtIndex","get"]
[[],[1],[3],[1,2],[1],[1],[1]]
```

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
