### ISSUE TITLE
Missing Test Case - 1976. Number of Ways to Arrive at Destination

### ISSUE THREAD

**Issue by Mohancmd2531** [LeetCode-Feedback/LeetCode-Feedback#14868]
#### Your LeetCode username

MK68

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

a test case is missing

#### Code you used for Submit/Run operation

```

class Solution {
    public int countPaths(int n, int[][] roads) {
        int m=roads.length;
        int mod=1000000007;
        PriorityQueue<Pair>pq=new PriorityQueue<>((x,y)->x.first-y.first);
        List<List<Pair>>adj=new ArrayList<>();
        for(int i=0;i<n;i++)
            adj.add(new ArrayList<>());
        for(int i=0;i<m;i++){
            adj.get(roads[i][0]).add(new Pair(roads[i][1],roads[i][2]));
            adj.get(roads[i][1]).add(new Pair(roads[i][0],roads[i][2]));
        }
        int[]dist=new int[n];
        int[]ways=new int[n];
        Arrays.fill(dist,Integer.MAX_VALUE);
        Arrays.fill(ways,0);
        dist[0]=0;
        ways[0]=1;
        pq.add(new Pair(0,0));
        while(!pq.isEmpty()){
            int dis=pq.peek().first;
            int node=pq.peek().second;
            pq.remove();
            for(Pair i:adj.get(node)){
                int adjNode=i.first;
                int time=i.second;
                if(time+dis<dist[adjNode]){
                    dist[adjNode]=time+dis;
                    ways[adjNode]=ways[node];
                    pq.add(new Pair(time+dis,adjNode));
                }
                else if(time+dis==dist[adjNode])
                    ways[adjNode]=(ways[node]+ways[adjNode])%mod;
            }
        }
        return ways[n-1]%mod;
    }
}
class Pair{
    int first,second;
    public Pair(int first, int second){
        this.first=first;
        this.second=second;
    }
}

```

#### Language used for code

Java

#### Expected behavior

My code was accepted but later when I tested it for 1 other test case then it showed wrong answer, in such case mine solution should not have been accepted at the beginning only. 

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/84089898/01ae3585-08b4-441b-b14e-5b8e18e0c494)

#### Additional context

please add this test case -
6
[[0 ,1 ,1000000000],[0 ,3 ,1000000000],[1 ,3 ,1000000000],[1 ,2 ,1000000000],[1 ,5 ,1000000000],[3 ,4 ,1000000000],[4 ,5 ,1000000000],[2 ,5 ,1000000000]]

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
