### ISSUE TITLE
Missing Test Case - 35. Search Insert Position

### ISSUE THREAD

**Issue by Sukanya-2000** [LeetCode-Feedback/LeetCode-Feedback#14867]
#### Your LeetCode username

Sukanya-2000

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

This test case is Input
nums =
[1,3,5,6]
target =
7
Output
1
Expected
4                         
target = 7 is not present in the array hence the output should be 1 

#### Code you used for Submit/Run operation

```
class Solution {
    public int searchInsert(int[] nums, int target) {
        int mid = nums.length/2;
        int ans=1;
        for(int i=0;i<mid;i++)
        {
            if(nums[i]==target)
            {
                ans=i;
            }
            
            
        }
        for(int i=mid;i<nums.length;i++)
        {
            if(nums[i]==target)
            {
                ans=i;
            }
            
        }
        return ans;
    }
}
```

#### Expected behavior

This test case is Input
nums =
[1,3,5,6]
target =
7
Output
1
Expected
4                         
target = 7 is not present in the array hence the output should be 1 instead of returning 1 it returns a invaild value "4"

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
