### ISSUE TITLE
Missing Test Case - 23. Merge k Sorted Lists

### ISSUE THREAD

**Issue by rstudy211** [LeetCode-Feedback/LeetCode-Feedback#1486]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
class Solution:
    def mergeKLists(self, lists: List[ListNode]) -> ListNode:
        s = []
        for i in lists:
            curr = i
            while(curr):
                s+=[curr.val]
                curr =curr.next
        s.sort()
        head = point = ListNode()
        for k in s:
            point.next = ListNode(k)
            point = point.next
        return head.next
                
};
```

**Comment by lc-kay** [comment]
@rstudy211 Please provide your code in [Playground](https://leetcode.com/playground/new/empty). In addition, please provide the missing test case. Thank you for your time!

**Comment by lc-kay** [comment]
Hi @rstudy211  ,
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
