### ISSUE TITLE
Missing Test Case - 1789. Primary Department for Each Employee

### ISSUE THREAD

**Issue by codeCharm90** [LeetCode-Feedback/LeetCode-Feedback#14877]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [✅] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// MySQL code
SELECT employee_id, department_id
FROM Employee
WHERE primary_flag = 'Y'
UNION
SELECT employee_id, department_id
FROM Employee
WHERE employee_id NOT IN (
  SELECT employee_id
  FROM Employee
  WHERE primary_flag = 'Y'
)
ORDER BY employee_id;
```

#### Expected behavior

For a particular testcase where there are 2 rows for same employee_id and different department_id but both are not choosen as primary department i.e. primary flag = "N" so this employee_id shouldn't be selected as the employee is in 2 departments and both are not primary but my answer included it and it also got accepted but when I am running it manually it is showing wrong answer but still my answer got accepted.

#### Screenshots

<img width="679" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/109057401/218c3321-d728-4f68-be54-62947ebcc574">

<img width="820" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/109057401/f8ba869f-2dbb-47a6-81af-7536fb017014">

#### Additional context

I think these testcases should be added where count of department > 1 but none of them are primary.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The test case in JSON format: {"headers":{"Employee":["employee_id","department_id","primary_flag"]},"rows":{"Employee":[["1","1","N"],["2","1","Y"],["2","2","N"],["3","3","N"],["4","2","N"],["4","3","Y"],["4","4","N"]]}}

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by codeCharm90** [comment]
The test case which failed in JSON format:

{"headers":{"Employee":["employee_id","department_id","primary_flag"]},"rows":{"Employee":[["1","1","N"],["1","2","N"],["2","1","Y"],["2","2","N"],["3","3","N"],["4","2","N"],["4","3","Y"],["4","4","N"]]}}

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've used your feedback to edit the Problem description.

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback.

Please reply to us with your LCUS username.

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!
