### ISSUE TITLE
Missing Test Case - 1286. Iterator for Combination

### ISSUE THREAD

**Issue by markgrichanik** [LeetCode-Feedback/LeetCode-Feedback#1487]
#### Your LeetCode username
grichanik

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language

#### Description of the bug
My incorrect solution was accepted.

#### Code you used for Submit/Run operation

```
/**
 * @param {string} characters
 * @param {number} combinationLength
 */
var CombinationIterator = function(characters, combinationLength) {
this.cur = characters.substring(0, combinationLength).split("");
    this.dic = characters.split("");
    this.n = this.dic.length;
    this.nextexist = true;
};

/**
 * @return {string}
 */
CombinationIterator.prototype.next = function() {
    if(!this.nextexist){
        return "";
    }
    let res = [...this.cur];
    let L = this.cur.length;
    let i = this.cur.length - 1, j = this.dic.length-1;
    while(i >= 0 && this.cur[i] === this.dic[j]){
        i--;
        j--;
    }
    if(i === -1){
        this.nextexist = false;
    } else {
        let index = this.dic.indexOf(this.cur[i]);
        for(let k = i; k < L; k++){
            this.cur[k] = this.dic[++index];
        }
    }
    return res.join("");
};

/**
 * @return {boolean}
 */
CombinationIterator.prototype.hasNext = function() {
 return this.nextexist;
}
/** 
 * Your CombinationIterator object will be instantiated and called as such:
 * var obj = new CombinationIterator(characters, combinationLength)
 * var param_1 = obj.next()
 * var param_2 = obj.hasNext()
 */
```

#### Language used for code
JS

#### Expected behavior
My solution shouldn't be accepted because it doesn't pass the test case
```
["CombinationIterator","next","hasNext","next","hasNext","next","hasNext"]
[["abcb",2],[],[],[],[],[],[]]
```

#### Screenshots

![image](https://user-images.githubusercontent.com/13029936/100441520-46ca3880-30af-11eb-97ef-cac5e109be5c.png)

**Comment by markgrichanik** [comment]
![image](https://user-images.githubusercontent.com/13029936/100441843-c2c48080-30af-11eb-8b36-669ed717c337.png)

**Comment by lc-kay** [comment]
Hi @markgrichanik 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @markgrichanik 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
