### ISSUE TITLE
Missing Test Case - 137. Single Number II

### ISSUE THREAD

**Issue by AJAYKR00KJ** [LeetCode-Feedback/LeetCode-Feedback#1488]
#### Category of the bug
- [ ] Question
- [ ✔️] Solution
- [ ] Language

#### Description of the bug
The following code was accepted successfully, but for the test case  [-2,-2,1,1,4,1,4,4,-4,-2], we got the output result 4 and the expected result is -4 which were not consistent.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int singleNumber(vector<int>& nums) {
        long long int res=0;
        for(int i=0;i<32;i++)
        {   int p=0;
            for(int j=0;j<nums.size();j++)
            {   int k=abs(nums[j]);
                p+=(k&(1<<i))!=0?1:0;
                 
            }
          
           p%=3;
          
          res+=pow(2,i)*p;
        }  
        cout<<res;
        int c=0;
        for(auto x:nums)    
          if(x==res) {c=1;break;}    
        return c==1?res:-res;  
    }
};

```

#### Expected behavior

Please add the test cases [-2,-2,1,1,4,1,4,4,-4,-2]

#### Screenshots

![ggg](https://user-images.githubusercontent.com/48375037/100443222-4b9ee480-30cf-11eb-9a2d-fe47055f8071.png)

#### Additional context

Add the test cases.

**Comment by lc-kay** [comment]
Hi @AJAYKR00KJ 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @AJAYKR00KJ 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
