### ISSUE TITLE
Missing Test Case - 剑指 Offer 57. 和为s的两个数字 LCOF

### ISSUE THREAD

**Issue by Frankcaozas** [LeetCode-Feedback/LeetCode-Feedback#14885]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

for this test case:
```
nums = [2,7,11,15]
tartget = 9
the output is []
and the desired result is []
but this test case failed
```

#### Code you used for Submit/Run operation

```TypeScript
// Two Sum
function twoSum(nums: number[], target: number): number[] {
  let l = 0, r = nums.length - 1
  while (l < r) {
    const num1 = nums[l], num2 = nums[r]
    if (num1 + num2 > target) r--
    else if (num1 + num2 < target) l++
    else return [num1, num2]
  }
  return  []
};
```

#### Language used for code
 TS

#### Expected behavior

this test case should pass

#### Screenshots

<img width="717" alt="截屏2023-07-19 22 22 03" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/90302102/5dd406eb-c2a5-4c40-91eb-e82546bc623a">

**Comment by feiceh** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励哦。

**Comment by Frankcaozas** [comment]
> 你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：[support.leetcode.cn/hc/kb/article/1277837](https://support.leetcode.cn/hc/kb/article/1277837) ），我们给予积分奖励哦。


leetcode.cn/u/frankcao/

**Comment by feiceh** [comment]
收到，积分奖励已发放，请查收～
