### ISSUE TITLE
提交记录查看不了性能详情，问题复现

### ISSUE THREAD

**Issue by Tiikee** [LeetCode-Feedback/LeetCode-Feedback#14880]
你好，技术刚放宽了频率限制，本次 Ticket 将关闭，感谢您的反馈和支持。

_Originally posted by @feiceh in https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/14663#issuecomment-1635231164_
            
-------------------------------------------------
#问题复现
这次没有再去提交，就是单纯去看之前不同提交的解的性能差别，然后又卡的数据都没有了。。。且看的频率也不高，算是看完一个点一个，就卡的界面数据全没了。点击任何一个提交记录都没数据，换道题去看也是一样。如下：
![image](https://user-images.githubusercontent.com/95959942/254521146-eab76b88-d536-4031-bed6-b8ff5c988bee.png)

#期待结果
能正常看到提交记录的性能详情，且不影响其他位置提交记录性能详情的查看

**Comment by Tiikee** [comment]
又出现这个问题了，是正在登陆我的账号测试吗？我这边页面一直在刷新
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/95959942/f3827c23-fc66-4f24-8095-1ad57dc92a78)
@feiceh

**Comment by Tiikee** [comment]
@feiceh 
emmmmmmmmmmmmmmmm，又出这个问题了。我这边这个提交频率不算高吧，结果还是显示不出性能详情页面。如下42题：
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/95959942/537d0778-2bc1-4645-bd4a-1d36af3d7947)

**Comment by feiceh** [comment]
你好，技术又放宽了限制条件，本次 Ticket 将关闭，感谢您的反馈和支持。
