### ISSUE TITLE
Missing Test Case - 28. Find the Index of the First Occurrence in a String

### ISSUE THREAD

**Issue by qwerab2002** [LeetCode-Feedback/LeetCode-Feedback#14898]
#### Your LeetCode username

qwerab2002

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug

There is no testcase where the "needle‘’ is too long to be stored in a long integer, which is roughly 13 letters long. The question can be achieved in O(n) if the "needle" can be stored in a long integer.

#### Code you used for Submit/Run operation

```
//28. Find the Index of the First Occurrence in a String
class Solution {
    public int strStr(String haystack, String needle) {
        if (haystack.length() < needle.length()) return -1;
        long pattern = 0,coe = 1;
        for (char c : needle.toCharArray()) {
            pattern = pattern *26 + c -'a';
            coe *= 26;} 
        coe /= 26;
        long tmp = 0;
        int i = 0,j= 0;
        while (j < haystack.length()) {
            if (j - i <= needle.length() - 1) {
                tmp = tmp * 26 + haystack.charAt(j++) - 'a';
                continue;}
            if (tmp == pattern) return i;
            tmp = tmp - (haystack.charAt(i++) - 'a') * coe;
            tmp = tmp * 26 + haystack.charAt(j++) - 'a';}
    if (tmp == pattern) return i;
    return -1;
    }
}

```

#### Language used for code

Java

#### Expected behavior

The legal input of :
haystack =
"fourscoreandsevenyearsagoourfathersbroughtforthuponthiscontinentanewnation"
needle =
"ourfathersbroughtforthuponthiscontinentanewnation"
should fail the above program. But it got successfully submitted.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
