### ISSUE TITLE
第十题测试用例不全，错误的代码可以通过全部测试用例。

### ISSUE THREAD

**Issue by yuzm1** [LeetCode-Feedback/LeetCode-Feedback#14895]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
逍遥隐仙
邮箱：191987852@qq.com

**Bug 类型**
- [ ] 题解

**描述**
第十题测试用例不全，错误的代码可以通过全部测试用例。
[10. 正则表达式匹配](https://leetcode.cn/problems/regular-expression-matching/)

**你使用的语言**
C++

**你提交或者运行的代码**
```
class Solution {
public:
    bool isMatch(string s, string p) {
        return isMatch(s.c_str(), p.c_str());
    }

    bool isMatch(const char *s, const char *p) {
        if (*p == '\0') return *s == '\0';
        // next char is not '*', then must match current character
        if (*(p + 1) != '*') {
            if (*p == *s || (*p == '.' && *s != '\0'))
                return isMatch(s + 1, p + 1);
            else
                return false;
        } else { // next char is '*'
            while (*p == *s || (*p == '.' && *s != '\0')) {
                if (isMatch(s, p + 2))
                    return true;
                s++;
        }
        
        return isMatch(s, p + 2);
        }
    }
};
```

**期望行为**
代码中只关注了p字符串含有'*'的情况，没有对称性包含字符串s含有’*‘的情况。 所以不应该解答通过。
但是题库的测试用例缺失，导致解答通过。
如果增加输入：
"a*"
"aa"
则错误解答不会通过。

**屏幕截图**
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/138849374/6dbb2eea-d851-4694-9c5a-a6892a71410b)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/138849374/d336ea52-c913-445f-bfec-b4d9db3b964a)

**额外的上下文**
添加额外的上下文信息

**Comment by stormsunshine** [comment]
请仔细读题，字符串 `s` 只有小写字母，哪里允许字符串 `s` 中有字符 `*`？

**Comment by feiceh** [comment]
你好，在与相关团队核实后：不作处理， s 仅含有小写字母。
本次 Ticket 将关闭，感谢您的反馈和支持。
