### ISSUE TITLE
616: Add Bold Tag in String Example 2 description is confusing

### ISSUE THREAD

**Issue by asarkar** [LeetCode-Feedback/LeetCode-Feedback#14891]
#### Your LeetCode username
number42

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
Example 2 description is incorrect and makes no sense. For example `"<b>a<b>a</b>a</b><b>b</b><b>b</b><b>b</b>"`, why is there `<b>a</b>`, there's no word `a` in input `words`.

#### Code you used for Submit/Run operation
Not relevant.

#### Language used for code
Not relevant.

#### Expected behavior
A clear, concise and correct description of example 2.

#### Screenshots
N/A.

#### Additional context
N/A.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by asarkar** [comment]
Upon closer inspection, I now see what the example is trying to show.
```
<b>a<b>a</b>a</b><b>b</b><b>b</b><b>b</b>
```
The `<b>a</b>` is _not_ from a word `a` but the end of the previous to previous `<b>` tag.
I still think this ticket is correct that the example is confusing. It’d be clearer to show a picture of the “spans” of the bold tags, perhaps using curly braces on top of the string, instead of inserting them in a way that is very difficult to understand. People expect the tags to be paired like parentheses, and the example above violates that, since the outer tag ends before the inner one.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

it is “<b>aa</b>abbb” and “a<b>aa</b>bbb” if you combine them by rule #2, that happens.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
