### ISSUE TITLE
Missing Test Case - 757. Set Intersection Size At Least Two

### ISSUE THREAD

**Issue by wei-yao** [LeetCode-Feedback/LeetCode-Feedback#1489]
#### Your LeetCode username

weiyao2

#### Category of the bug
- [ ] Question

#### Description of the bug

missing test case:
I previously wrote a solution that only sorts the interval using their end point and it passed all the test cases. But it will fail on this one if two-interval has the same end point.
[[0,1],[1,4],[3,4],[4,5]]

#### Code you used for Submit/Run operation

```
//solutions that will fails on the mentioned test cases.
class Solution {
    public int intersectionSizeTwo(int[][] intervals) {
        int n=intervals.length;
        if(n==0)
            return 0;
        Arrays.sort(intervals,(a,b)->(a[1]-b[1]));
        int a=-2;
        int b=-1;
        int count=0;
        for(int[] interval :intervals){
            if(a>=interval[0]&&b>=interval[0])
                continue;
            if(b<interval[0]){
                count+=2;
                b=interval[1];
                a=b-1;
            }else {
//becase b may equals interval[1] at first, after the execution, a=b=interval[1], which is not correct
                count++;
                a=b;
                b=interval[1];
            }
        }
        return count;
    }
    
}
```

#### Expected behavior

My code passed the submission, but will fails at this test cases: [[0,1],[1,4],[3,4],[4,5]]

**Comment by lc-kay** [comment]
@wei-yao Please provide your code in [Playground](https://leetcode.com/playground/new/empty). When I ran the code you included, I got Compile Error.

**Comment by wei-yao** [comment]
https://leetcode.com/playground/HRFdcapN

**Comment by lc-kay** [comment]
Hi @wei-yao 
Thank you! I've relayed this issue to our team to investigate.

**Comment by wei-yao** [comment]
You are welcome!

Best,
Yao

**Comment by lc-kay** [comment]
Hi @wei-yao 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
