### ISSUE TITLE
Gramatical Error in problem `21. Merge Two Sorted Lists`

### ISSUE THREAD

**Issue by p0lygun** [LeetCode-Feedback/LeetCode-Feedback#14905]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

The problem description says

> Merge the two lists in a one sorted list. The list should be made by splicing together the nodes of the first two lists.

#### Expected behavior

The correct language would be

> Merge the two lists **into one** sorted list. The list should be made by splicing together the nodes of the first two lists.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
