### ISSUE TITLE
818. Race Car - Error in Editorial

### ISSUE THREAD

**Issue by Meet91721** [LeetCode-Feedback/LeetCode-Feedback#14916]
#### Your LeetCode username
ma91721

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

----Editorial for problem 818. Race Car, Paragraph 1----
The editorial for this problem gives a restatement of a certain series. Given we have two commands, 'A' for acceleration and 'R' for reverse, we are given that a series of the form RA<sup>k<sub> 1 </sub></sup> RA<sup>k<sub>2</sub></sup> ... RA<sup>k<sub>n</sub> </sup>, we can re-write the series as A<sup>k<sub>2</sub></sup> RA<sup>k<sub>3</sub></sup> ... RA<sup>k<sub>n</sub></sup>RRA<sup>k<sub>1</sub></sup>. However, for even values of n, the mentioned transformation does not work. 

#### Example Test Case to describe the problem

Example case : Given series RA<sup>2</sup> RA<sup>4</sup>, the position reached through this series would be 12. Its transformation A<sup>4</sup> RRA<sup>2</sup> reaches to position 18. This shows the two series do not result in the same final position.

#### Expected solution

The transformation for the series RA<sup>k<sub>1</sub></sup> RA<sup>k<sub>2</sub></sup> ... RA<sup>k<sub>n</sub></sup> would be dependent on the parity of n. If n is odd, the mentioned transformation would be correct. However, in the case of even n, the transformation would change to A<sup>k<sub>2</sub></sup>RA<sup>k<sub>3</sub></sup> ... RA<sup>k<sub>n</sub></sup>RA<sup>k<sub>1</sub></sup>. 

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/74113151/88641f31-ae0d-4556-8bf4-8f63c23aa2a6)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
