### ISSUE TITLE
Missing Test Case - 2768. Number of Black Blocks

### ISSUE THREAD

**Issue by qingy2019** [LeetCode-Feedback/LeetCode-Feedback#14911]
#### Your LeetCode username

qingy2023

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets wrong answer on this test case

```
m = 94853
n = 3
coordinates = [[0,0]]
```

#### Code you used for Submit/Run operation

```Kotlin
class Solution {
    fun countBlackBlocks(m: Int, n: Int, coordinates: Array<IntArray>): LongArray {
        var upLeft = arrayOf(-1 to -1, -1 to 0, 0 to -1)
        var upRight = arrayOf(1 to -1, 1 to 0, 0 to -1)
        var downLeft = arrayOf(-1 to 0, -1 to 1, 0 to 1)
        var downRight = arrayOf(1 to 0, 1 to 1, 0 to 1)
        
        var all = listOf(upLeft, upRight, downLeft, downRight)
        var count = LongArray(5)
        count[0] = (m - 1) * (n - 1).toLong()
        var visited = HashSet<String>()
        
        for ((row, col) in coordinates) {
            visited.add("$row,$col")
            for (block in all) {
                var total = 0
                var valid = true
                for ((x, y) in block) {
                    if (m == 94853) return longArrayOf()    
                    var (nX, nY) = row + x to col + y
                    if (nX !in 0 until m || nY !in 0 until n) {
                        valid = false
                        break
                    }
                    if (visited.contains("$nX,$nY")) total++
                }
                if (!valid) continue
                count[total]--
                count[total + 1]++
            }
        }
        return count
    }
}
```

#### Language used for code

Kotlin

#### Screenshots

<img width="292" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/66195939/ba1bf785-8c4b-42df-a6c9-9c87c21c27e8">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by qingy2019** [comment]
@LC-Pam  any updates?

**Comment by qingy2019** [comment]
@LC-Pam any updates?

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
