### ISSUE TITLE
二叉树中序遍历-ruby-测试案例返回结果有误

### ISSUE THREAD

**Issue by Zhang-jia-chen** [LeetCode-Feedback/LeetCode-Feedback#1491]
** Bug 类型**
- [ ] https://leetcode-cn.com/problems/binary-tree-inorder-traversal/
- [ ] 题解
- [ ] ruby

**描述**
测试用例输入[1]执行代码可以通过，但是提交代码后输入[1]，输出[1,3,2,1],输出结果错误,应该输出[1]。
**你使用的语言**
ruby

**你提交或者运行的代码**
```
//  二叉树的中序遍历
def inorder_traversal(root)
    return [] if root.nil?
    @res ||= []
    inorder_traversal(root.left)
    @res << root.val
    inorder_traversal(root.right)
    @res
end
```

**期望行为**
输入[1]返回[1]

**屏幕截图**
![image](https://user-images.githubusercontent.com/26432050/100496075-12787a00-318c-11eb-9af0-cff31d9b88b3.png)

**额外的上下文**
添加额外的上下文信息

**Comment by Zhang-jia-chen** [comment]
二叉树前序遍历存在同样的问题https://leetcode-cn.com/problems/binary-tree-preorder-traversal/

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认的～

**Comment by kaiwensun** [comment]
@Zhang-jia-chen test runner不会创建多个solution object。`@res` 会泄漏至其他test case。参考[FAQ](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-)

**Comment by Zhang-jia-chen** [comment]
以下代码可以复现上面的 bug
`class TreeNode
    attr_accessor :val, :left, :right
    def initialize(val = 0, left = nil, right = nil)
        @val = val
        @left = left
        @right = right
    end
    
    def inorder_traversal(root)
        return [] if root.nil?
        @res ||= []
        inorder_traversal(root.left)
        @res << root.val
        inorder_traversal(root.right)
        @res
    end
end
l = TreeNode.new(1)
r = TreeNode.new(2)
node = TreeNode.new(3, l, r)
p node.inorder_traversal(node)
p node.inorder_traversal(l)`

正确的代码
```
def inorder_traversal(root)
    return [] if root.nil?
    res = []
    res += inorder_traversal(root.left)
    res << root.val
    res += inorder_traversal(root.right)
    res
end
```

**Comment by feiceh** [comment]
感谢反馈，技术验证题目没有问题，我们认同上面 @kaiwensun 所提到的，如果要是用 @res，代码需要对 @res 的值进行初始化，例如：
```
def inorder_traversal(root)
    @res = []
    inorder_traversal_handle(root)
    @res
end


def inorder_traversal_handle(root)
    return [] if root.nil?
    @res ||= []
    inorder_traversal_handle(root.left)
    @res << root.val
    inorder_traversal_handle(root.right)
    @res
end
```
