### ISSUE TITLE
Missing Test Case - 673. Number of Longest Increasing Subsequence

### ISSUE THREAD

**Issue by ceciliachan1979** [LeetCode-Feedback/LeetCode-Feedback#14918]
#### Your LeetCode username

cecilia5

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
There are a few solutions in the solution that claims to be O(n log n), but they aren't because they would have experience quadratic behavior with a test case like this.

999,998,...,0,1000,1000, [...1000 times...], 1000

The reason being they all find the sum by adding the number of matches in the earlier stack one by one, so if we use the earlier half of the input to build a stack with half length, and use the latter half to force scanning them again and again, it will be O(n^2), and that fact should be reflected by the running time of their submissions.

The fact that they sum them one by one is the bottleneck, and that can be eliminated with a running sum plus a binary search.

Example patience sorting that don't use the running time trick includes:
https://leetcode.com/problems/number-of-longest-increasing-subsequence/solutions/3304458/patience-sort-visualization/
https://leetcode.com/problems/number-of-longest-increasing-subsequence/solutions/3795135/modified-patience-greedy-algorithm/
https://leetcode.com/problems/number-of-longest-increasing-subsequence/solutions/590222/7ms-java-solution-using-patience-sort/
https://leetcode.com/problems/number-of-longest-increasing-subsequence/solutions/2115390/beats-99-22-python-patience-sort-dp-o-nlogn/

The actual O(n log n) solution using the running sum and binary search is here:
https://leetcode.com/problems/number-of-longest-increasing-subsequence/solutions/721640/python-o-nlogn-patience-sort-beats-97-84ms/

Without this test case, it would be relatively difficult for these people to realize their solution is not O(n log n).

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

Please provide the test case explicitly.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
