### ISSUE TITLE
2090. K Radius Subarray Averages : Weak Testcases

### ISSUE THREAD

**Issue by darkNoivern** [LeetCode-Feedback/LeetCode-Feedback#14921]
#### Your LeetCode username

spryzen_v3

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Many Codes are passing the current testcases even if the solution is wrong.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
        vector<int> getAverages(vector<int>& nums, int k) {
        if(k == 0)
            return nums;
        vector<int> v(nums.size(), -1);
        if(k >= nums.size())
            return v;

        long long sum = 0;
        int cnt = 0;
        for(int i = 0; i < 2 * k; i++)
            sum += nums[i];
        
        for(int i = 2 * k; i < nums.size(); i++){
            sum += nums[i];
            v[i - k] = sum / ((2 * k) + 1);
            sum -= nums[i - 2 * k];
        }

        return v;
    }
};
```

#### Language used for code

C++

#### Expected behavior

This above code is getting accepted for the problem, but the solution is a bit wrong since this code gives `Runtime Error` in the following testcase :

`nums = [7, 4, 3, 1]` , `k = 3`

Expected Outcome `[-1,-1,-1,-1]`

#### Additional context

Problem Link : [https://leetcode.com/problems/k-radius-subarray-averages/](url)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
