### ISSUE TITLE
Missing Test Case - 239. Sliding Window Maximum

### ISSUE THREAD

**Issue by pavlo-t** [LeetCode-Feedback/LeetCode-Feedback#1492]
#### Your LeetCode username
bc-

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Missing test case for [Sliding Window Maximum](https://leetcode.com/explore/challenge/card/november-leetcoding-challenge/567/week-4-november-22nd-november-28th/3546/).
My solution should have timed out.

#### Code you used for Submit/Run operation
```scala
object Solution {
  def maxSlidingWindow(nums: Array[Int], k: Int): Array[Int] =
    if (k == 1) nums
    else {
      val result = Array.ofDim[Int](nums.length - k + 1)

      val q = collection.mutable.ArrayDeque[Int]()
      q.addAll(nums.take(k))
      var max = q.max

      result(0) = max

      for (i <- k until nums.length) {
        val oldHead = q.removeHead()
        q.addOne(nums(i))
        if (oldHead == max) max = q.max
        else max = max max nums(i)

        result(i - k + 1) = max
      }

      result
    }
}
```

#### Language used for code
scala

#### Expected behavior
Status: Time Limit Exceeded.

#### Additional context
Can add a worst case like:

```scala
"(nums = 100k elements [10000,10000...1,1], k = 50000) -> [10000,10000...5001,5001,5000]" in {
  val nums = (10000 to 1 by -1).flatMap(Array.fill(10)(_)).toArray
  val expected = (10000 to 5000 by -1).flatMap(Array.fill(10)(_)).toArray.dropRight(9)

  maxSlidingWindow(nums, 50000) shouldBe expected
}
```

**Comment by lc-kay** [comment]
@pavlo-t Can you please provide the missing test case through [Playground](https://leetcode.com/playground/)? Thank you for your time!

**Comment by pavlo-t** [comment]
@lc-kay Is [this](https://leetcode.com/playground/DovWRch8) helpful?

**Comment by lc-kay** [comment]
@pavlo-t I am still unable to reproduce the issue. Can you please submit the test case in this format: nums = [4,-2], k = 2. Thank you!

**Comment by pavlo-t** [comment]
@lc-kay Sure, [here](https://gist.github.com/pavlo-t/94b14a1919e05b6fcde9bd23c3d6036f) you go.
[Leetcode test submission interface](https://leetcode.com/contribute/) has a limit of ~ 10,000 chars.

**Comment by lc-kay** [comment]
<img width="837" alt="Screen Shot 2020-12-04 at 11 42 20 AM" src="https://user-images.githubusercontent.com/70870126/101207712-dc247a00-3625-11eb-981b-87911c395753.png">
@pavlo-t The test case is already in our test case set and your solution is Accepted with this code. To contribute a missing test case, please provide an accepted code that a test case fails on. Thank you!

**Comment by pavlo-t** [comment]
@lc-kay Yes, this case looks like mine, but it has `k = 2`, not `k = 50000`.
Anyway, thank you for your time.

**Comment by lc-kay** [comment]
Hi @pavlo-t 
Thank you for the update. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @pavlo-t 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
