### ISSUE TITLE
Missing Test Case - 1089. Duplicate Zeros

### ISSUE THREAD

**Issue by denisborisov** [LeetCode-Feedback/LeetCode-Feedback#14922]
#### Your LeetCode username
denis-borisov

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
I used my own test case `[0, 1, 0]` to verify it works correctly. The expected answer is `[0, 0, 1]`. Although my answer is `[0, 0, 0]`, the Submission Result is **Accepted**.

#### Code you used for Submit/Run operation

```
class Solution:
    def duplicateZeros(self, arr: List[int]) -> None:
        """
        Do not return anything, modify arr in-place instead.
        """
        
        saved = []
        i = 0
        while i < len(arr):
            if saved:
                saved.append(arr[i])
                arr[i] = saved.pop(0)
            if arr[i] == 0 and i < len(arr)-1:
                if len(saved) < len(arr) // 4:
                    saved.append(arr[i+1])
                arr[i+1] = 0
                i += 1
            i += 1
```

#### Language used for code
Python

#### Expected behavior
The Submission Result is **Wrong Answer**.

#### Screenshots
<img width="1440" alt="Screenshot 2023-07-21 at 18 13 00" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/1473445/d2809f4f-e90a-4e16-9791-94894fb2740c">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
