### ISSUE TITLE
Missing Test Case - 673. Number of Longest Increasing Subsequence

### ISSUE THREAD

**Issue by bhj2001** [LeetCode-Feedback/LeetCode-Feedback#14927]
#### Your LeetCode username

Bhj2001

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The number of LISs can be 2^(n/2) and will exceed range of int

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

More details/explanation about the bug. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by bhj2001** [comment]
For the test case given below, the number of longest increasing subsequences would be 2 ** (n / 2)

nums = [1, 1, 2, 2, 3, 3, .... i, i,... n/2, n/2]

since LIS is [1, 2, 3.... n/2] and there are 2 ** (n / 2) ways to choose the LIS. 

Suggested change in the problem statement - 

Compute the number of longest increasing subsequences modulo 10^9+7

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

please provide the test case explicitly.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
