### ISSUE TITLE
Missing Test Case - 673. Number of Longest Increasing Subsequence

### ISSUE THREAD

**Issue by ItsLastDay** [LeetCode-Feedback/LeetCode-Feedback#14924]
#### Your LeetCode username
misha

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
 In the problem, you need to return an `int`. However, the answer can be as big as 2**1000 (2 to the power of 1000).

For a start, such test should give an answer of 2**33: `[1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10,11,11,12,12,13,13,14,14,15,15,16,16,17,17,18,18,19,19,20,20,21,21,22,22,23,23,24,24,25,25,26,26,27,27,28,28,29,29,30,30,31,31,32,32,33,33]`.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int findNumberOfLIS(vector<int>& a) {
        return 66;
    }
};
```

#### Language used for code
C++

#### Expected behavior
Judge's solution should output an expected answer 8589934592.

#### Screenshots
In reality, `expected` field is empty: https://pasteboard.co/eezvi523SkVP.png.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by ItsLastDay** [comment]
https://leetcode.com/problems/number-of-longest-increasing-subsequence/submissions/1000461662/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
