### ISSUE TITLE
235. Lowest Common Ancestor of a Binary Search Tree - Missing Dart supprt

### ISSUE THREAD

**Issue by TinhHuynh** [LeetCode-Feedback/LeetCode-Feedback#14939]
#### Your LeetCode username
tinhhuynh

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
[235. Lowest Common Ancestor of a Binary Search Tree](https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/description/) is missing Dart language support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've submitted your feedback to the team.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
