### ISSUE TITLE
Incorrect solutions - 439. Ternary Expression Parser

### ISSUE THREAD

**Issue by przemek3d88** [LeetCode-Feedback/LeetCode-Feedback#14938]
#### Your LeetCode username
przemysaw2

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
"F?F:3?4:5"
The correct answer to the above test case is 4.

Approach 1:
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 18446744073709551615) > this->size() (which is 5)

Approach 2, 3, 4, 5:
5

Approach 6:
3

**Comment by cswartzell** [comment]
As I stated in the editorial comments, I disagree. You are assuming here that "3?4:5" is valid in the first place. The question does not give us any information on the truth value for any characters other than 'T' and 'F', so we shouldn't make any assumptions as you have. 

The reasoning "this test case isnt rejected by the checker and thus it is valid" is not sound. This assumes that the check for test cases is infallible *and* the solver treats characters other than '0' as TRUE and '0' as false. This isn't born out as you can simply check "3?4:5" and "0?4:5".  When run in python, the test case you listed, "F?F:3?4:5", expects "5" as the result, **NOT** "4". Similarly, running "0?4:5" expects "5", meaning the checker is rather oddly treating **all** characters other than 'T' as FALSE, *including* '0' by coincidence.

There is an issue with this question, but its not in the editorial. The question is not clear, and requires we make a few assumptions. The checker also fails to identify test cases where there is a digit character as a conditional or, rather oddly, treats *all* digit characters as FALSE without telling users that this is the correct assumption.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The input "F?F:3?4:5" is not valid. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by przemek3d88** [comment]
@LC-Pam , you updated both the editorial and the test validator, but you did not mention a reward.

**Comment by przemek3d88** [comment]
Hello,

You used my feedback, to update both the editorial and the test verifier,
but I haven't received the reward.

Thanks,
Dez


śr., 26 lip 2023 o 14:04 LC_M ***@***.***> napisał(a):
