### ISSUE TITLE
Missing Test Case - 7. Reverse Integer

### ISSUE THREAD

**Issue by bipulkmr-crypto** [LeetCode-Feedback/LeetCode-Feedback#1493]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@bipulkmr-crypto Please provide the accepted code and the test case it failed on. Thank you!

**Comment by lc-kay** [comment]
Hi @bipulkmr-crypto  ,
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
