### ISSUE TITLE
Missing Test Case - 162. Find Peak Element

### ISSUE THREAD

**Issue by Jagriti-grover20** [LeetCode-Feedback/LeetCode-Feedback#14932]
#### Your LeetCode username

USERNAME:
https://leetcode.com/SDEGoogle/
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

```
// Find Peak Element

class Solution {
public:
    int findPeakElement(vector<int>& nums) {
        int start=0,end=nums.size()-1;
        while(start<end){
            int mid=start+ ((end-start)/2);
            if(nums[mid]<nums[mid+1]){
                start=mid+1;
            }
            else{
                end=mid;
            }
        }
        return start;
    }
};
```

#### Expected behavior

EVEN AFTER SUCCESSFUL SUBMISSION , THIS TESTCASE [1,2,3,1,4,2,1,8] IS NOT PROVIDING THE CORRECT RESULT . THAT IS, THIS TESTCASE IS MISSING TO HANDLE.

#### Screenshots

https://drive.google.com/file/d/10xcTYXUhZlGb_w48XYyJM0B1FY-GplnW/view?usp=sharing

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The test case already exists and shows the correct result. 
![Screen Shot 2023-07-25 at 6 20 34 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/18b22b8b-283d-4039-b50d-58e1bd2096c1)

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
