### ISSUE TITLE
Missing Test Case - 1671. Minimum Number of Removals to Make Mountain Array

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#1494]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution is accepted but fails on on the following test case:

[4,5,13,17,1,7,6,11,2,8,10,15,3,9,12,14,16]

#### Code you used for Submit/Run operation

```
class Solution {
    public int minimumMountainRemovals(int[] nums) {
        int n=nums.length;
        int[] dp1=new int[n];
        int[] dp2=new int[n];
        int i,j,k,res;
        Arrays.fill(dp1,1);
        Arrays.fill(dp2,1);
        for(i=1;i<n;i++){
            for(j=i-1;j>=0;j--){
                if(nums[i]>nums[j]){
                    dp1[i]=Math.max(dp1[i],dp1[j]+1);
                }
            }
        }
        for(i=n-2;i>=0;i--){
            for(j=i+1;j<n;j++){
                if(nums[i]>nums[j]){
                    dp2[i]=Math.max(dp2[i],dp2[j]+1);
                }
            }
        }
        res=n;
        for(i=1;i<n;i++){
            //System.out.println(dp1[i]+"  "+dp2[i]);
            if(i==0){
                res=Math.min(res,n-dp2[0]);
            }else if(i==n-1){
                res=Math.min(res,n-dp1[n-1]);
            }else{
                res=Math.min(res,n-(dp1[i]+dp2[i]-1));
            }
        }
        return res;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/100520781-abe46380-316d-11eb-9b6f-04db898b0da4.png)
![image](https://user-images.githubusercontent.com/32546406/100520789-b999e900-316d-11eb-8586-1d93643aafdb.png)

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@IgorRud Since we recently updated the test case set for this problem, the code you submitted now receives the Wrong Answer. Thank you for your time!
