### ISSUE TITLE
TEST CASE MISSING

### ISSUE THREAD

**Issue by vijaybhasker-bit** [LeetCode-Feedback/LeetCode-Feedback#14947]
#### MISSING TESTCASE
 6930. Check if Array is Good
 
Here for Input nums [1,1,,3,3] 
 The code returns true  but it should be falsee?

#### Code you used for Submit/Run operation

``
class Solution {
public:
    bool isGood(vector<int>& nums) {
         sort(nums.begin(),nums.end());
        int n=nums.size();
        return (nums[n-1]==n-1&&nums[n-2]==n-1);
          }
};  
''

####C++

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by vijaybhasker-bit** [comment]
https://leetcode.com/submissions/detail/1001247606/
Here is the link

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by vijaybhasker-bit** [comment]
Thank You for you response
