### ISSUE TITLE
Wrong Test Case - 36. Valid Sudoku

### ISSUE THREAD

**Issue by avirajshastri** [LeetCode-Feedback/LeetCode-Feedback#14945]
#### Your LeetCode username

strek6

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 
Solution

#### Code you used for Submit/Run operation

class Solution {
public:
    bool isPossible(vector<vector<char>>& board,int row,int col,int k )
    {
        char c=k+'0';
        for(int i=0;i<9;i++)
        {
            if(board[row][i]==c) // checking in row if any repetation is present
            {
                return false;
            }
            if(board[i][col]==c) // checking in column if any repetation is present
            {
                return false;
            }
            if(board[3*(row/3)+i/3][3*(col/3)+i%3]==c) // checking in 3x3 grid if any repetation is present
            {
                return false;
            }
        }
        return true; // if there is not any repetation present return true
    }
    bool solve(vector<vector<char>>& board)
    {
        for(int i=0;i<9;i++)
        {
            for(int j=0;j<9;j++)
            {
                if(board[i][j]=='.') // if that cell needs to be filled
                {
                    for(int k=1;k<=9;k++)
                    {
                        if(isPossible(board,i,j,k)) // checking if char k is possible to be filled in (i,j) cell
                        {
                            board[i][j]=k+'0'; // filling (i,j) cell
                            if(solve(board)) //after filling if sudoku is valid return true
                            {
                                return true;
                            }
                            board[i][j]='.'; // else fill with different number
                        }
                    }
                    return false; // if there is not any value of k present which we can fill then return false
                }
            }
        }
        return true; // return true if sudoku is valid
    }
    bool isValidSudoku(vector<vector<char>>& board) {
         bool a=solve(board);
        // for(int i=0;i<9;i++)
        // {
        //     for(int j=0;j<9;j++)
        //     {
        //         cout<<board[i][j]<<" ";
        //     }
        //     cout<<endl;
        // }
        return a;
    }
};
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior

In the test case
[[".","8","7","6","5","4","3","2","1"],["2",".",".",".",".",".",".",".","."],["3",".",".",".",".",".",".",".","."],["4",".",".",".",".",".",".",".","."],["5",".",".",".",".",".",".",".","."],["6",".",".",".",".",".",".",".","."],["7",".",".",".",".",".",".",".","."],["8",".",".",".",".",".",".",".","."],["9",".",".",".",".",".",".",".","."]] 
its supposed to give ans false because if we fill (0,0) with 1 it will contradict with (0,8) cell (0th based indexing)
if we fill (0,0) with 9 it will contradict with (8,0) therefore, ans should be false.

#### Screenshots

![Screenshot 2023-07-22 194551](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/84036863/510e4961-f959-460c-a90e-9845062c224f)

**Comment by stormsunshine** [comment]
It is clearly mentioned in problem statement as follows.

> A Sudoku board (partially filled) could be valid but is not necessarily solvable.

Did you read problem description carefully?

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
