### ISSUE TITLE
Missing Test Case - 334. Increasing Triplet Subsequence

### ISSUE THREAD

**Issue by Zeck69** [LeetCode-Feedback/LeetCode-Feedback#14942]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X ] Missing Test Cases 

#### Description of the bug

The test don't check for basic errors, where only the increasing values are searched, I passed everything with non-correct code.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution:
    def increasingTriplet(self, nums: List[int]) -> bool:
        first = second = float('inf') 
        for n in nums: 
            if n <= first: 
                first = n
            elif n <= second:
                second = n
            else:
                return True
        return False
```

#### Expected behavior

With a case using nums = [20,100,10,12,5,13], this program would return true via finding the triplet 5,12,13, which are not indexed increasingly. The true triplet is 10,12,13.

#### Additional context

I think added test case should be made so this code that doesn't check all constraint doesn't go through as correct. (this code is in the community solution section as the most liked Python answer).

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
