### ISSUE TITLE
Missing Test Case - 2784. Check if Array is Good

### ISSUE THREAD

**Issue by jatin30032001** [LeetCode-Feedback/LeetCode-Feedback#14951]
#### Your LeetCode username
<jrsaini2090>

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug
<My code is submitted by leetcode yet it can't solve this particular test case [1,3,3,3,5,6,6] >

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool isGood(vector<int>& nums) {
        int size = nums.size();
        int n = size-1;
        int sum = 0;
        
        for(int i =0 ;i<size ;i++){
           sum+= nums[i]; 
        }
            int sum2 = ((n*(n+1))/2);
        if(abs(sum-sum2)!=n){
            return false;
        }
        return true;
    }
};
```

#### Language used for code
C++

#### Expected behavior
The code should give false for this test case [1,3,3,3,5,6,6]. Yet it gets submmitted

**Comment by jatin30032001** [comment]
My leetcode username is jrsaini2090

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
