### ISSUE TITLE
Missing Test Case - 1671. Minimum Number of Removals to Make Mountain Array

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#1495]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution is accepted but fails on the following test case:
[10,9,6,5,3,2,1,4,7,6]

#### Code you used for Submit/Run operation

```
class Solution {
    public int minimumMountainRemovals(int[] nums) {
        if (nums.length == 0) {
            return 0;
        }
        int[] dp1 = new int[nums.length];
        int[] dp2 = new int[nums.length];
        dp1[0] = 1;
        dp2[0] = 1;
        for (int i = 1; i < nums.length; i++) {
            dp1[i] = 1;
            for (int j = 0; j < i; j++) {
                if (nums[i] > nums[j]) {
                    dp1[i] = Math.max(dp1[i], dp1[j] + 1);
                }
            }
        }
        int[] arr = new int[nums.length];
        for(int i = 0; i < nums.length; i++) arr[i] = nums[nums.length - i - 1];
        for (int i = 1; i < nums.length; i++) {
            dp2[i] = 1;
            for (int j = 0; j < i; j++) {
                if (arr[i] > arr[j]) {
                    dp2[i] = Math.max(dp2[i], dp2[j] + 1);
                }
            }
        }
        //System.out.println(Arrays.toString(dp1));
        //System.out.println(Arrays.toString(dp2));
        int res = 0;
        for(int i = 1; i < nums.length - 1; i++){
            res = Math.max(res, dp1[i] + dp2[nums.length - i - 1]);
        }
        return nums.length - res + 1;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/100521087-7b9dc480-316f-11eb-8a82-8e428989ba7e.png)
![image](https://user-images.githubusercontent.com/32546406/100521095-8c4e3a80-316f-11eb-89f3-5e0a553c6df7.png)

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@IgorRud Since we recently updated the test case set for this problem, the code you submitted now receives the Wrong Answer. Thank you for your time!
