### ISSUE TITLE
Missing Test Case - 2784. Check if Array is Good

### ISSUE THREAD

**Issue by vampire-ab** [LeetCode-Feedback/LeetCode-Feedback#14952]
#### Your LeetCode username
vampireAb

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug
The question doesn't have a corner test case. 
Example->[1,3,3,3,5,6,6]
Such a test case should be tested. 
It is a problem if the following code is used as solution as the code is accepted.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool isGood(vector<int>& nums) {        
        int sum = 0;
        int n = nums.size();
        for(auto i: nums){
            sum += i;
        }
        n--;
        if(sum == (((n*(n+1))/2)+n)){
            return true;
        }
        return false;
    }
};
```

#### Language used for code

C++

#### Expected behavior
The code should not be accepted.

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process. https://leetcode.com/submissions/detail/1002813123/
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team

**Comment by vampire-ab** [comment]
The test case I provided was wrong for this scenario. I apologize for that.

**Correct Testcase**
[1,1,4,4,5,5]

This should give the wrong answer and is wrong. So, this code should not be the correct solution.
However, the given code was submitted successfully.

Hence, the test case should be added to the test cases.

The submission can be checked from here: https://leetcode.com/submissions/detail/1001312298/
