### ISSUE TITLE
Missing Test Case - 2784. Check if Array is Good

### ISSUE THREAD

**Issue by joedsilva** [LeetCode-Feedback/LeetCode-Feedback#14953]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Current test cases will not fail a solution that checks for the sum of the elements of array - _n(n+1)/2 + n_

#### Code you used for Submit/Run operation

```
class Solution:
    def isGood(self, nums: List[int]) -> bool:
        n = len(nums)-1
        return sum(nums) == (n*(n+1)//2 + n)
```

#### Language used for code
Python

#### Expected behavior

The above code is not correct, as it would incorrectly state the below input to be true.
```
[2, 1, 1, 5]
```
This is because it just assumes that the num of elements of nums should be _n*(n+1)/2 + n_  based on the sum of _n_ natural numbers.

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results: https://leetcode.com/submissions/detail/1002813649/  Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
