### ISSUE TITLE
题目描述（翻译错误） - 6942. 树中可以形成回文的路径数

### ISSUE THREAD

**Issue by wangwenwwx** [LeetCode-Feedback/LeetCode-Feedback#14959]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
wangwenwwx
**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
题目描述最后一句，英文为
`s consists of only lowercase English letters.`
目前的中文描述为
`s 仅由小写英文数字组成`

**期望行为**
中文描述应该为
`s 仅由小写英文字母组成`
**屏幕截图**
![截图_选择区域_20230723122530](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/26155919/ac221576-117c-43bd-93aa-a97ed38cdb53)
![截图_选择区域_20230723122640](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/26155919/16a1ebd0-0bb5-4c76-92c8-17ecc3ed7bfc)

**额外的上下文**
此题目为第355次周赛第四题，这个问题会影响周赛评分吗？

**Comment by feiceh** [comment]
你好，在与相关团队核实后：反馈不会影响评分，当前题目已更新，奖励奖励已发放。
本次 Ticket 将关闭，感谢您的反馈和支持。
