### ISSUE TITLE
Missing Test Case - 2407. Longest Increasing Subsequence II

### ISSUE THREAD

**Issue by Albert-qjd** [LeetCode-Feedback/LeetCode-Feedback#14961]
#### Your LeetCode username

- Albert

#### Category of the bug
- [2407. Longest Increasing Subsequence II ] Question
- [lengthOfLIS ] Solution
- [Python3 ] Language
- [{nums:[1,5,15,16], k=5}] Missing Test Cases 

#### Description of the bug

the answer supposes to be 2 for {nums:[1,5,15,16], k=5}.
However, the code i used below returns "3".
Apprently, the algrithm below is not accuracy enough but it successfully passed all the test cases you provided and rank top 1.
Please add new test cases like {nums:[1,5,15,16], k=5}, don't let this algorithm lead people who used your OJ towards a wrong direction!

#### Code you used for Submit/Run operation

```
// Longest Increasing Subsequence II
from bisect import bisect_left as bs_ix_left
class Solution:
    def lengthOfLIS(self, nums: List[int], k: int) -> int:
        n = max(nums)
        dp, val, cur = [1], [nums[0]], 1
        for elem in nums:
            if elem > val[-1]+k:
                dp.append(1)
                val.append(elem)
            elif elem == val[0]:
                continue
            elif elem < val[0]:
                val.insert(0, elem)
                dp.insert(0,1)
            else:
                if elem > val[-1]: 
                    dp.append(cur+1) 
                    val.append(elem)
                    cur += 1
                    continue
                left, right, mx_inside = bs_ix_left(val, elem-k), bs_ix_left(val, elem), 1
                if left < right:
                    mx_inside = max(dp[left:right]) + 1
                    cur = max(cur, mx_inside)
                if val[right] == elem:
                    dp[right] = mx_inside
                else:
                    val.insert(right, elem)
                    dp.insert(right, mx_inside)
        print(f"dp{dp}")
        print(f"val:{val}")
        return max(dp)
```

#### Expected behavior

As I described in "Description of the bug"

#### Screenshots

https://github.com/Albert-qjd/SharedImg_/blob/master/LC_2407.png
https://github.com/Albert-qjd/SharedImg_/blob/master/LC_2407_2.png

#### Additional context

As I described in "Description of the bug"

**Comment by Albert-qjd** [comment]
Language used for code: Python3

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
