### ISSUE TITLE
894 - Incorrect tree passed as valid output

### ISSUE THREAD

**Issue by pacificlion** [LeetCode-Feedback/LeetCode-Feedback#14967]
#### Your LeetCode username

pacificlion

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The question requires to output valid full binary trees which requires that every node has either 2 or 0 children.
I assign the same node named *same* as all leaf nodes. This passes all test cases. One way is to check for memory references in testing if all nodes not null refer to different nodes. 

#### Code you used for Submit/Run operation

```
/**
 * Definition for a binary tree node.
 * public class TreeNode {
 *     int val;
 *     TreeNode left;
 *     TreeNode right;
 *     TreeNode() {}
 *     TreeNode(int val) { this.val = val; }
 *     TreeNode(int val, TreeNode left, TreeNode right) {
 *         this.val = val;
 *         this.left = left;
 *         this.right = right;
 *     }
 * }
 */

 
class Solution {
    TreeNode same = new TreeNode(0);
    public List<TreeNode> allPossibleFBT(int n) {

        if(n%2==0){
            return new ArrayList<TreeNode>();
        }
// returning same node
        if(n==1){
             return Arrays.asList(same);
        }

        List<TreeNode> res = new ArrayList<TreeNode>();
        for (int i = 1; i < n; i += 2) {
            List<TreeNode> left = allPossibleFBT(i);
            List<TreeNode> right = allPossibleFBT(n-i-1);
            for(TreeNode l:left){
                for(TreeNode r:right){
                    TreeNode root = new TreeNode(0,l,r);
                    res.add(root);
                }
            }

        }


        return res;
        
        
    }
}
```

#### Language used for code

java

#### Expected behavior

Ideally, such output should receive error of invalid binary tree.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
