### ISSUE TITLE
Missing Test Case - 183. Customers Who Never Order

### ISSUE THREAD

**Issue by Sumeet942** [LeetCode-Feedback/LeetCode-Feedback#1496]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@Sumeet942 Please provide the accepted code and the test case that it failed on.

**Comment by lc-kay** [comment]
Hi @Sumeet942  ,
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
