### ISSUE TITLE
TestCase Inaccuracy || 89. Gray Code

### ISSUE THREAD

**Issue by Kushal1605** [LeetCode-Feedback/LeetCode-Feedback#14977]
#### Your LeetCode username
Kushal1605

#### Category of the bug
- Question
-  Missing Test Cases 
- Inaccuracy in Test Case

#### Description of the bug
The question accepts any sequence of gray code of a given n number of bits but it accepts the incorrect sequences as well.

#### Code you used for Submit/Run operation

```
// Gray Code
class Solution {
    private void helper(int n, int bitCount, List<Integer> res, int num) {
        res.add(num);
        for(int i = bitCount; i < n; i++) {
            helper(n, i + 1, res, num ^ (1 << i));
        }
    }
    public List<Integer> grayCode(int n) {
        List<Integer> res = new ArrayList<>();
        helper(n, 0, res, 0);
        return res;  
    }
}
```

#### Language used for code
Java

#### Expected behaviour
For n = 3, it should accept any valid sequence of gray code for 3 bit number. While submitting the above code I got an invalid sequence of gray code but still it was accepted and when submitted all the test cases passed too.
In the provided screenshot my output is ```[0,1,3,7,5,2,6,4]``` which is being accepted by the LeetCode. Now if we have a closer look in the sequence of gray code the **binary representation of 5 is 101 while the binary representation of 2 is 010. It is very clear that there are more than 1 bit differs and both the numbers are adjacent in the sequence so it's invalid and should not be accepted.**

#### Screenshots
<img width="745" alt="Screenshot 2023-07-23 214935" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/115387392/2e74446a-2eb4-448a-a532-334837e2dc0f">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
