### ISSUE TITLE
Missing Test Case - 80. Remove Duplicates from Sorted Array II

### ISSUE THREAD

**Issue by Darinochka** [LeetCode-Feedback/LeetCode-Feedback#14971]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Validation of the statement ```assert k == expected names.length;``` does not work in my Python solution if there are no changes in nums and the return value is greater than the length of nums.

#### Code you used for Submit/Run operation

```
class Solution:
    def removeDuplicates(self, nums: List[int]) -> int:
        curr = 2

        for i in range(2, len(nums)):
            if nums[i] != nums[curr-2]:
                nums[curr] = nums[i]
                curr += 1
        return len(nums) + 1
```
#### Language used for code

Python3

#### Expected behavior

1) Test case:
[1]
Output of removeDuplicates:
2
Expected output of removeDuplicates:
1
2) Test case:
[1, 2, 3]
Output of removeDuplicates:
4
Expected output of removeDuplicates:
3

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/39233990/97a99b28-a909-4350-b6c8-b075a3fefb17)

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
