### ISSUE TITLE
Missing Test Case - 7. Reverse Integer

### ISSUE THREAD

**Issue by rbrohan07** [LeetCode-Feedback/LeetCode-Feedback#14983]
#### Your LeetCode username

**rohan77**
https://leetcode.com/rohan77/

#### Category of the bug

- [x] Missing Test Cases 

#### Description of the bug

**Title: Exception Handling for x = 2^31 - 1 (2147483647)**
according to the question, the value of the x can be   2^31 -1 but the code I have written is throwing an error  on x=2^31-1(2147483647) this value but it gets submitted. it should throw an error. 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int reverse(int n) {
     
      int res=0;
        
        while(n)
        {
           
          
            res =(res)*10+n%10 ;
            n=n/10;  
        }
      if(res>INT_MAX || INT_MIN>res )
      {
          return 0;
      }
        return res;
        
        
    }
};
```

#### Language used for code

C++
#### Expected behavior

 it should throw a Runtime Error

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/94669189/c465d6a1-f696-4315-844f-f3862101acd5)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/94669189/b049e784-f39d-4262-addf-97fa21eff8fc)

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
