### ISSUE TITLE
Missing Test Case - 121. Best Time to Buy and Sell Stock

### ISSUE THREAD

**Issue by viniciuswoeth** [LeetCode-Feedback/LeetCode-Feedback#14986]
#### Your LeetCode username

woeth

#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

If tested with Test Case [7,1,5,3,6,4,9,4] the solution is incorrect showing 8 for expected solution, but in my code i tested with others Test Case thoroughly and my code is correct solution is a 7

#### Code you used for Submit/Run operation

```
// Best Time to Buy and Sell Stock
class Solution:
    def maxProfit(self, prices: List[int]) -> int:
        profit = 0
        day = 0
        for i in range(len(prices) - 1):
            for j in range(i + 1, len(prices)):
                if prices[j] - prices[i] > profit:
                    day = j + 1
                    profit = prices[j] - prices[i]
        return day
```

#### Language used for code

Python

#### Expected behavior

Expected Solution showing 8 but the correct solution is 7 

#### Additional context

For clear and simply visualization  using this code in VS Code its shows exactly step by step

```
class Solution:
    def maxProfit(self, prices: list[int]) -> int:
        profit = 0
        day = 0
        for i in range(len(prices) - 1):
            for j in range(i + 1, len(prices)):
                if prices[j] - prices[i] > profit:
                    day = j + 1
                    profit = prices[j] - prices[i]
                    print("j {} - i {} = profit {}".format(prices[j], prices[i], profit))
        return day
    

print(Solution.maxProfit("Case1", [7,1,5,3,6,4]))
print("\n")
print(Solution.maxProfit("Case1", [7,6,4,3,1]))
print("\n")
print(Solution.maxProfit("Case1", [7,1,5,3,6,4,9,4]))
```

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process. https://leetcode.com/submissions/detail/1003977579/
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey. 
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
