### ISSUE TITLE
88. Merge Sorted Array - Runtime issue

### ISSUE THREAD

**Issue by SupritamACN** [LeetCode-Feedback/LeetCode-Feedback#14987]
#### Your LeetCode username

SupritamACN

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

Issue with Go Runtime. When I run a decreasing for loop from m+n-1 to 0, the loop does not exit at 0, it continues. The same program runs fine in Go Playground. 

#### Code you used for Submit/Run operation

```
func merge(nums1 []int, m int, nums2 []int, n int)  {

  i,j:=m-1,n-1
  var l int
  for l = m+n-1; l >= 0 ; l-- {
  fmt.Printf("l=%d, i=%d, j=%d \n", l,i,j)
    if (i>=0 && j>=0 && nums1[i] <= nums2[j]) {
      nums1[l] = nums2[j]
      j-- 
    } else {
      nums1[l] = nums1[i]
      i--
    }
  }

}
```
The error I am getting - 
```
panic: runtime error: index out of range [-1]
main.merge({0xc000076060, 0x1, 0x1?}, 0x4b1bc0?, {0xc000076080, 0x1, 0x4b2280?}, 0xc000016030?)
solution.go, line 11
main.__helper__(...)
solution.go, line 21
main.main()
solution.go, line 82
```
Console Output - 
```
l=5, i=2, j=2 
l=4, i=2, j=1 
l=3, i=2, j=0 
l=2, i=1, j=0 
l=1, i=1, j=-1 
l=0, i=0, j=-1 
l=0, i=0, j=-1 
l=0, i=-1, j=0 
```

#### Language used for code

Go

#### Expected behavior

The for loop variable should stop at l=0.
Expected console output - 
```
l=5, i=2, j=2 
l=4, i=2, j=1 
l=3, i=2, j=0 
l=2, i=1, j=0 
l=1, i=1, j=-1 
l=0, i=0, j=-1
```
It is working correctly in [go playground](https://goplay.tools/snippet/yVTV7AVo6dc).

**Comment by SupritamACN** [comment]
Same happens with Java version of code as well.
```
class Solution {
    public void merge(int[] nums1, int m, int[] nums2, int n) {
        int i = m-1;
        int j = n-1;
        for(int l=m+n-1; l>=0; l--){
          System.out.println("l="+l+" i="+i+" j="+j);
          if (i >= 0 && j >= 0 && nums2[j] >= nums1[i]) {
            nums1[l] = nums2[j--];
          } else {
            nums1[l] = nums1[i--];
          }
        }
    }
}
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you print you can see that “l=0 i=-1 j=0“ it means “i” is out of bound it has nothing to do with “l”.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
