### ISSUE TITLE
1603. Design Parking System - Missing part of the solution article

### ISSUE THREAD

**Issue by mnaoumov** [LeetCode-Feedback/LeetCode-Feedback#14982]
#### Your LeetCode username

mnaoumov

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Solution has `!?!../Documents/1603/1603_Single_Array.json:1280,720!?!` instead of the valid content

#### Expected behavior

Valid content is added

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/735878/cee32e42-3a24-4ee6-afb2-cc348588db7c)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

Please use the new version

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
