### ISSUE TITLE
439. Ternary Expression Parser - Missing part of the solution article

### ISSUE THREAD

**Issue by mnaoumov** [LeetCode-Feedback/LeetCode-Feedback#14980]
#### Your LeetCode username

mnaoumov

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Solution has `!?!../Documents/439/439_Ternary_Example.json:1280,427!?!` instead of the valid content

#### Expected behavior

Valid content is addded

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/735878/69d60c5f-a9e0-4bdf-b600-29a0c3e339e7)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by RohitSgh** [comment]
The slide is there. It's **visible on NEW UI**. Old UI has some rendering issue.

1. Go to https://leetcode.com/mnaoumov/. Click NEW given on Bottom Right
    
    > ![https://leetcode.com/mnaoumov/](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/81853910/8c0e7752-596d-4e51-9d85-db7f730464cf)
    
2. Go to [Editorial](https://leetcode.com/problems/ternary-expression-parser/editorial/). You may see slides.

    > ![https://leetcode.com/problems/ternary-expression-parser/editorial/](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/81853910/1d3a697c-523d-4fda-9ab1-b29729e22737)

Thanks!

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

Please use the new version

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
