### ISSUE TITLE
Missing Test Case - 1901. Find a Peak Element II

### ISSUE THREAD

**Issue by imshivam-gupta** [LeetCode-Feedback/LeetCode-Feedback#14995]
#### Your LeetCode username
shivam_gupta2604

#### Category of the bug
- [] Question
- [ ] Solution
- [ ] Language
- [ x] Missing Test Cases 

#### Description of the bug
One solution is passing but failing an edge case  solution was

// C++
// Optimal Solution
class Solution {
public:
    bool peak(vector<vector<int>>& mat, int n, int m, int row, int col) {
        int top = row == 0 ? -1 : mat[row - 1][col];
        int bottom = row == n - 1 ? -1 : mat[row + 1][col];
        int left = col == 0 ? -1 : mat[row][col - 1];
        int right = col == m - 1 ? -1 : mat[row][col + 1];

        return (mat[row][col] > top && mat[row][col] > bottom && mat[row][col] > left && mat[row][col] > right);
    }

    vector<int> findPeakGrid(vector<vector<int>>& mat) {
        int n = mat.size();
        int m = mat[0].size();

        for (int row = 0; row < n; row++) {
            if (peak(mat, n, m, row, 0)) {return {row, 0};}
            if (peak(mat, n, m, row, m-1)) {return {row, m-1};}
            
            int low = 1;
            int high = m - 2;

            while (low <= high) {
                int mid = low + (high - low) / 2;

                if (peak(mat, n, m, row, mid)) {return {row, mid};}
                else if (mat[row][mid] < mat[row][mid + 1] && mat[row][mid - 1] < mat[row][mid + 1]) {low = mid + 1;}
                else {high = mid - 1;}
            }
        }
        return {};
    }
};

It does not check the conditions correctly

#### Code you used for Submit/Run operation

```
// C++
// Optimal Solution
class Solution {
public:
    bool peak(vector<vector<int>>& mat, int n, int m, int row, int col) {
        int top = row == 0 ? -1 : mat[row - 1][col];
        int bottom = row == n - 1 ? -1 : mat[row + 1][col];
        int left = col == 0 ? -1 : mat[row][col - 1];
        int right = col == m - 1 ? -1 : mat[row][col + 1];

        return (mat[row][col] > top && mat[row][col] > bottom && mat[row][col] > left && mat[row][col] > right);
    }

    vector<int> findPeakGrid(vector<vector<int>>& mat) {
        int n = mat.size();
        int m = mat[0].size();

        for (int row = 0; row < n; row++) {
            if (peak(mat, n, m, row, 0)) {return {row, 0};}
            if (peak(mat, n, m, row, m-1)) {return {row, m-1};}
            
            int low = 1;
            int high = m - 2;

            while (low <= high) {
                int mid = low + (high - low) / 2;

                if (peak(mat, n, m, row, mid)) {return {row, mid};}
                else if (mat[row][mid] < mat[row][mid + 1] && mat[row][mid - 1] < mat[row][mid + 1]) {low = mid + 1;}
                else {high = mid - 1;}
            }
        }
        return {};
    }
};
```

#### Language used for code
C++

#### Expected behavior
Expected was [1,4] getting [] but code is still passing

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/93479496/ff7c3e0b-acf4-45b7-8cb8-d02bda5a3cca)

#### Additional context
Please add this edge case to prevent wrong submissions

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by imshivam-gupta** [comment]
https://leetcode.com/problems/find-a-peak-element-ii/submissions/1002667373/

**Comment by imshivam-gupta** [comment]
This is the code which is getting accepted but is incorrect for provided test case
[[10,20,40,50,60,70],[1,4,2,3,500,80]]

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
