### ISSUE TITLE
Wrong Answer - 1669. Merge In Between Linked Lists

### ISSUE THREAD

**Issue by ShobhitB-01** [LeetCode-Feedback/LeetCode-Feedback#14992]
#### Category of the bug
- [x] Question
- [ .] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

61st test case from your end gives a wrong answer.

#### Code you used for Submit/Run operation

```
/*
 * Definition for singly-linked list.
 * struct ListNode {
 *     int val;
 *     ListNode *next;
 *     ListNode() : val(0), next(nullptr) {}
 *     ListNode(int x) : val(x), next(nullptr) {}
 *     ListNode(int x, ListNode *next) : val(x), next(next) {}
 * };
 */
class Solution {
public:
    ListNode* mergeInBetween(ListNode* list1, int a, int b, ListNode* list2) {
        ListNode *break1, *break2;
        break1 = new ListNode();
        break1->next = list1;
        break2 = break1;

        while (break1 && break1->next && break1->next->next) {
            if (break1->next->val == a){
                ListNode *temp;
                temp = new ListNode();
                temp->val = a;
                temp->next = break1->next->next;
                
                break1->next = list2;
                while (break1){
                    if (break1->next == NULL){
                        break;
                    }
                    break1 = break1->next;
                }

                while (temp && temp->next) {
                    if (temp->val == b && break1){
                        break1->next = temp->next;
                    }
                    temp = temp->next;
                }

                return break2->next;
            }
            break1 = break1->next;
        }
        return NULL;
    }
};

```

#### Expected behavior

TestCase:
[0,3,2,1,4,5]
3
4
[1000000,1000001,1000002]

Answer should be [0, 1000000, 1000001, 1000002, 5] and not [0, 3, 2, 1000000, 1000001, 1000002, 5].
I got the former and your solution requires the latter.

#### Screenshots

<img width="960" alt="Screenshot 2023-07-24 145828" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/138795993/821c7333-931c-4f2f-aa06-3301736c008e">
<img width="960" alt="Screenshot 2023-07-24 145838" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/138795993/0b98ea73-7373-421e-8b95-a14318b69324">

#### Additional context

I just want my stats uWu.

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
