### ISSUE TITLE
Missing Test Case - 1673. Find the Most Competitive Subsequence

### ISSUE THREAD

**Issue by av1shek** [LeetCode-Feedback/LeetCode-Feedback#1499]
#### Your LeetCode username
av1shek

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Weak Test Case, not considered corner cases

#### Code you used for Submit/Run operation
```
// Find the Most Competitive Subsequence
class Solution {
public:
    vector<int> mostCompetitive(vector<int>& nums, int k) {
        vector<int> ans, temp;
        bool flag = true;
        for(int i=1;i<nums.size();i++)
        {
            if(nums[i] < nums[i-1])
            {
                flag = false;
                break;
            }
        }
        if(flag == true)
        {
            for(int i=0;i<k;i++)
                temp.push_back(nums[i]);
            return temp;
        }
        int start = nums.size() - k + 1 ;
        auto it = min_element( nums.begin(), (nums.begin() + start ) );
        ans.push_back( *it );   it++; k--;
        for(; (it!=nums.end()) &&(k--); )
        {
            it = min_element(it, nums.end()-k);
            int temp = *it;
            ans.push_back(temp);
            it++;
        }
        return ans;
    }
};

static bool     _foo = ios::sync_with_stdio(false);
static ostream* _bar = cin.tie(NULL);
```

#### Language used for code
 C++

#### Expected behavior

It should give TLE ( Time Limit Exceeded ) but it is accepted

#### Additional context
83/85 passed
##### Testcase
[Click here](https://github.com/av1shek/av1shek.github.io/blob/master/details/testcase1.txt)

##### Approach
First i tried to solving by brute force method and it gave TLE on above testcase so I tried to handle some of such cases by checking whether the array given is already sorted or not, it it is already sorted then our answer is first K numbers.

But actually it should give TLE because it was not supposed to solve by brute force.
So if input array is almost sorted except its last element then we have to check till last if we apply brute force and it will give TLE.

Expected input array:<br>
[0,0,0,0,0,   ....................      , 0,0, -1] 

But as constraints is that nums[ i ] >= 0
so we can increase each element of input array by 1.

Expected Input array:
[1, 1,1,1,1,1, .............. ,1,1, 0 ]

#### Actual TestCase (to be added)
[Click here](https://github.com/av1shek/av1shek.github.io/blob/master/details/testcase2.txt)

#### Note:
My [solution](https://leetcode.com/contest/weekly-contest-217/submissions/detail/425214863/) is accepted but it is giving TLE for above mention testcase which is just modified in data of 84th testcase given.

**Comment by lc-kay** [comment]
Hi @av1shek 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @av1shek 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
