### ISSUE TITLE
unodered_map这题最大的问题是超内存，无论如何内存最不应该超！

### ISSUE THREAD

**Issue by Tiikee** [LeetCode-Feedback/LeetCode-Feedback#14997]
你好，在与相关团队核实后：暂不处理， 在某些场景下 unodered_map  性能不一定比 map 更优。
提交是所有用例一块跑，所以有时间超内存和超时，只是跑到某一个用例挂了，而单独这个用例不一定超。 
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。

_Originally posted by @feiceh in https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/14864#issuecomment-1647134195_

------------------------------------------------------------------------
**reply：**
336题最大的问题是**内存判定**，这个是**最不应该会超的**。
不带空孩子的前缀树怎么可能比带空孩子的前缀树消耗空间更大。
毋庸置疑，map实现前缀树空间性能优于vector[26]或int[26]，怎么可能map前缀树的内存反而会超。
其次才是unordered_map时间的问题。unordered_map时间性能下降，**仅限于使用重复桶的情况**，这个时候会上重复桶中查询。但是如果提前设置了26个桶数，就不可能出现重复桶的情况，可即便如此还是会超时。这才是unordered_map不合理的地方。

**其他**
虽然我已经写出了其他性能最优的解，但是这个内存判定的不合理性还是很明显的，如若方便还是麻烦定位解决吧。其次才是unordered_map的时间变慢问题。毕竟我也不知道其他人之后其他题会不会遇到同样的问题。

**Comment by feiceh** [comment]
你好，在与相关团队核实后：不作处理， 关于内存占用，建议用户可以自行调查。 unodered_map 的时间性能上，可参考这个文档 https://www.reddit.com/r/leetcode/comments/v9xf9t/is_it_always_better_to_use_unordered_maps_in_c_as/
