### ISSUE TITLE
78. subsets space complexity analysis is incorrect

### ISSUE THREAD

**Issue by happiness19** [LeetCode-Feedback/LeetCode-Feedback#15]
**What kind of the bug**
- [ ] problem
- [ x] solution

**Describe the bug**
Space complexity is shown as O(2^n) but really should be O(n*2^n)

**Expected behavior**
Space complexity should be O(n*2^n) since we need to output every subset (2^n of them) each of which has size at most n. A more comprehensive expression would be \sum_{k=0}^{n}{(n\choose k)\times k}

**Comment by CooperCooperCooper** [comment]
Hi @happiness19,
Thanks for reaching out! I've filed this to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @happiness19,
Thank you for reporting this issue, it's now fixed!
