### ISSUE TITLE
Wiggle Sort - Solution bug

### ISSUE THREAD

**Issue by Owais-Siddiqui** [LeetCode-Feedback/LeetCode-Feedback#15000]
#### Your LeetCode username

Owais912

#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the visual example greedy approach the final step has the value "2" repeated.
The first occurrence of 2 should be replaced by 1.

#### Code you used for Submit/Run operation

```

```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
