### ISSUE TITLE
Wrong Order by frequency - 269. Alien Dictionary

### ISSUE THREAD

**Issue by abhi007tyagi** [LeetCode-Feedback/LeetCode-Feedback#1500]
### Your LeetCode username
tyagiabhinav

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
The order of questions by frequency is wrong when viewing for Facebook for 0-6 months in decreasing order.
Eg. Q. 269 - Alien Dictionary comes first in the order with Companies tag: Facebook = 35 
While Q. 199 - Binary Tree Right Side View comes later in the order with Companies tag: Facebook = 52
There are several other questions which have a higher number of Companies tag: Facebook and are shown down in the list when selected in decreasing order of frequency. This will affect the way I am practising for my upcoming interview. What is the sense of having a premium account if these orders are not correct!

#### Expected behaviour
The order should be matched with the number of times the question is asked in the interview.

#### Additional context
Should not take much time to solve this issue and be corrected ASAP.

**Comment by lc-kay** [comment]
Hi @abhi007tyagi  ,
Thank you for your time. Upon investigating this issue, we found this issue to be non-content-related (the issue stems from an origin away from the content on this problem); therefore, please file this issue to our help desk at https://support.leetcode.com/hc/en-us.
