### ISSUE TITLE
Power Question

### ISSUE THREAD

**Issue by pranshugupta54** [LeetCode-Feedback/LeetCode-Feedback#15019]
#### Your LeetCode username
pranshgupta54

#### Category of the bug
- [ ] Question
- [ ] Solution

#### Description of the bug
The main objective of question is to handle recursion by sending n/2 everytime. But this question is a very very easy one for Python since they can simply return pow(x,n) for a medium question.

#### Code you used for Submit/Run operation

```
// Pow(x,n)
class Solution:
    def myPow(self, x: float, n: int) -> float:
        return pow(x,n)
```

#### Language used for code

Python

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem name or problem number. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by pranshugupta54** [comment]
https://leetcode.com/problems/powx-n

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
