### ISSUE TITLE
Missing Test Case - 1921. Eliminate Maximum Number of Monsters

### ISSUE THREAD

**Issue by Sohel440** [LeetCode-Feedback/LeetCode-Feedback#15014]
#### Your LeetCode username

SOHEL440

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases  -> dist =[4 , 3 ,2]  speed = [2 ,1,1] ans =2 but here showing ans = 3

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
 int eliminateMaximum(vector<int>& dist, vector<int>& speed) {
        
          priority_queue<pair<int,int> , vector<pair<int,int>>, greater<pair<int,int>> > p1;

          for(int i  =0 ; i < dist.size() ;i++){
              p1.push({dist[i] , speed[i]});
          }
        
          int cnt =0;
                while(!p1.empty())
        {
            pair<int,int>cur = p1.top();
            p1.pop();
            int check = cur.first - (cur.second * cnt);
            if(check <= 0)
                break;
            cnt++;
        }

          return cnt;

    }
};
```

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
