### ISSUE TITLE
Missing Test Case - 10. Regular Expression Matching

### ISSUE THREAD

**Issue by nithingodugu24** [LeetCode-Feedback/LeetCode-Feedback#15018]
#### Your LeetCode username
nithingodugu

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ 1] Missing Test Cases 

#### Description of the bug
In this problem we have to pass string s and p

and we are imagining s as "nithin"

and p as "ni*h*n"

so in this the testcase answer should be True but you are expecting as false . So please check and update the testcase expected values.

#### Code you used for Submit/Run operation

```
class Solution:
    def isMatch(self, s: str, p: str) -> bool:
        memo = {}
    
        def dp(i: int, j: int) -> bool:
            if (i, j) in memo:
                return memo[(i, j)]
        
            if j == len(p):
                return i == len(s)
        
            first_match = i < len(s) and (p[j] == s[i] or p[j] == '.')
        
            if j + 1 < len(p) and p[j+1] == '*':
                ans = dp(i, j+2) or (first_match and dp(i+1, j))
            else:
                ans = first_match and dp(i+1, j+1)
        
            memo[(i, j)] = ans
            return ans
    
        return dp(0, 0)

```

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
