### ISSUE TITLE
Wrong Test  Case: 287, Find the Duplicate Number 

### ISSUE THREAD

**Issue by srshobhit72** [LeetCode-Feedback/LeetCode-Feedback#15026]
#### Category of the bug
- [ ] Question

#### Description of the bug
 The question asks to return the ONLY ONE repeated number in the array but one of the test cases has all repeated numbers. 

#### Code you used for Submit/Run operation
```
class Solution {
public:
    int findDuplicate(vector<int>& nums) {

        int n = nums.size();
        int expectedSum = (n * (n - 1)) / 2;

        int sum = 0;
        for (int i = 0; i < n; i++) {
            sum += nums[i];
        }

        return sum - expectedSum;
        
    }
};
```

#### Language used for code
 C++ 

#### Expected behavior
 This test case is not valid for this question as the question explicitly mentions only one number being repeated. 

#### Screenshots

<img width="1680" alt="Screenshot 2023-07-25 at 9 00 31 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/56361694/b50ae64c-ef22-43ac-89ea-4e22b8baae2a">

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
