### ISSUE TITLE
2569. 更新数组后处理求和查询 官方题解 疑似笔误更正

### ISSUE THREAD

**Issue by mantoufan** [LeetCode-Feedback/LeetCode-Feedback#15029]
**你的 LeetCode 用户名**
mantoufan

**Bug 类型**
- [ ] 题目
- [x] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
[官方题解](https://leetcode.cn/problems/handling-sum-queries-after-update/solutions/2356392/geng-xin-shu-zu-hou-chu-li-qiu-he-cha-xu-kv6u/) 中 `javascript` 代码，如图第 33 行中 `new SegNode` 疑似笔误，应更正为 `new Array`。因为笔误的代码创建了 `Object`（一个 `SegNode` 的实例），`Object` 能动态添加属性（`id`），所以能正常运行，但影响性能。本意应该是创建长度为 `n * 4 + 1` 的定长列表。
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/4961543/146171dc-45d5-4c4e-baed-781c8d47cb25)

**你使用的语言**
JavaScript

**Comment by uchuuWei** [comment]
感谢你的反馈，我们已将题解更新，稍后发放 20 积分的奖励，请查收~感谢你对力扣的支持！

**Comment by feiceh** [comment]
感谢反馈，积分奖励已发放，请查收～
