### ISSUE TITLE
Incorrect Test Case - 36. Valid Sudoku

### ISSUE THREAD

**Issue by shengjie98** [LeetCode-Feedback/LeetCode-Feedback#1502]
#### Your LeetCode username
shengjie98

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language

#### Description of the bug
Incorrect Expected Result

#### Code you used for Submit/Run operation

```
class Solution(object):
    def isValidSudoku(self, board):
        """
        :type board: List[List[str]]
        :rtype: bool
        """        
        for row, n in enumerate(board) :
            for col, num in enumerate(n):
                if num == '.':
                    for i in range(1, 10):
                        if self.isSafe(board, row, col, str(i)):
                            board[row][col] = str(i)
                            valid = self.isValidSudoku(board)
                            board[row][col] = "."
                            if valid: 
                                return True
                    return False
        return True
                        
        
        
    def isSafe(self, board, row, col, num):
        for boardrow in board:
            if boardrow[col] == num:
                return False
        for item in board[row]:
            if item == num:
                return False
        start_row = (row // 3) *3
        start_col = (col // 3) *3
        for i in range(3):
            for j in range(3):
                if board[i + start_row][j+start_col] == num:
                    return False
        return True
        
```

#### Expected behavior
for board[0][0] it is not possible to put any numbers, yet the expected result shows that it is possible

#### Screenshots

![image](https://user-images.githubusercontent.com/53373032/100541954-48982580-3282-11eb-8dc8-c968f46c8205.png)

**Comment by zerotrac** [comment]
Could you please read the problem statement **carefully** (but not depend on your own knowledge) to figure out what is a **valid** Sudoku?

**Comment by lc-kay** [comment]
@shengjie98 Please check out the comment section on https://leetcode.com/problems/valid-sudoku/discuss/210272/Test-Case We hope this clarifies any doubts or questions.
