### ISSUE TITLE
Missing Test Case - 2791. Count Paths That Can Form a Palindrome in a Tree

### ISSUE THREAD

**Issue by qingy2019** [LeetCode-Feedback/LeetCode-Feedback#15030]
#### Your LeetCode username

qingy2023

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An AC solution gets WA on this test case

```
parent = [-1,0,0,1,1,2,0,0,1,1,2,0,0,1,1,2,0,0,1,1,2,0,0,0,0,1,1,2,0,0,1,1,2,1,1,2,1,2]
s = "azzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"
```

#### Code you used for Submit/Run operation

```Kotlin
class Solution {
    var children = arrayOf<MutableList<Pair<Int, Char>>>()
    var paths = HashMap<Int, Int>()
    var result = 0L
    fun countPalindromePaths(parent: List<Int>, s: String): Long {
        children = Array(s.length) { mutableListOf<Pair<Int, Char>>() }
        if (s.count { it == 'z'} == 37) return 0L
        for (i in 1 until parent.size)
            children[parent[i]].add(i to s[i])
        
        getPaths(0, 0)
        return result
    }
    
    fun getPaths(root: Int, count: Int) {
        for (c in children[root]) {
            var char = c.second - 'a'
            var newCount = count xor (1 shl char)
            
            if (newCount == 0) result++
            for (i in 0 until 26) {
                if (newCount == (1 shl i)) result++
                result += paths[newCount xor (1 shl i)] ?: 0
            }
            result += paths[newCount] ?: 0
            paths.merge(newCount, 1, Int::plus)
            
            getPaths(c.first, newCount)
        }
    }
}
```

#### Language used for code

Kotlin

#### Expected behavior

<img width="776" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/66195939/3b9936c6-7acf-40fd-abed-6cfb91774ed5">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by qingy2019** [comment]
@LC-Pam any updates?

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
