### ISSUE TITLE
Missing Test Case - 705. Design HashSet

### ISSUE THREAD

**Issue by Joofer** [LeetCode-Feedback/LeetCode-Feedback#15034]
#### Your LeetCode username

Joofer

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

There is no test case that checks duplicate keys handling in the add function. ex. list is chosen as an implementation of hash set buckets.

#### Code you used for Submit/Run operation

This passes all checks:
```
class MyHashSet {
private:
    std::vector<std::list<int>> hash_set;
public:
    void add(int key) {
        if (!contains(key))
            hash_set[get_hash(key)].push_back(key);
    }
};
```
So does this:
```
class MyHashSet {
private:
    std::vector<std::list<int>> hash_set;
public:
    void add(int key) {
        hash_set[get_hash(key)].push_back(key);
    }
};
```

#### Language used for code

C++

#### Expected behavior

The code should not pass tests if a duplicate key was added to the set.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Joofer** [comment]
Turns out i didn't take into account that list::remove() removes all entries of an element. Since then after remove is called all duplicates are deleted with the key itself. Hence with functions used in test cases it's impossible to check whether there're any duplicates. My bad.
