### ISSUE TITLE
Word Search Edge Case Issue

### ISSUE THREAD

**Issue by smadueke** [LeetCode-Feedback/LeetCode-Feedback#15040]
#### Your LeetCode username

madueke

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Leetcode excepts one solution with a slower runtime over another. Both codes do essentially the same thing.
Runtimes were determined by running each code through VS Code and using the time library to track runtime.

#### Code you used for Submit/Run operation

```
// Word Search
class Solution {
        directions = [[-1, 0], [1, 0], [0, -1], [0, 1]]
        visited = []

        def findWord(row, col, i):
            if i == len(word)-1:
                return True

            for nr, nc in directions:
                r, c = row + nr, col + nc
                if [r, c] in visited: continue
                if (r in range(len(board)) and c in range(len(board[0])) and board[r][c] == word[i+1]):
                    visited.append([row, col])
                    if findWord(r, c, i+1):
                        return True
                    visited.pop()
            return False

        for row in range(len(board)):
            for col in range(len(board[0])):
                if board[row][col] == word[0]:
                    if findWord(row, col, 0):
                        return True
        return False
```

#### Language used for code

Python3

#### Expected behavior

The code should be accepted

#### Screenshots

Runtime in VSCode each code. **Solution** is the leetcode accepted one. **Solution2** is the rejected one.

<img width="1561" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/56853418/9e564096-84cf-4aef-a442-556efad23e2c">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem number or name. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by smadueke** [comment]
Hey Pam, its this:

79. Word Search

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

It is a runtime error, not a time limit exceeded because you removed the header.

use the “reset to default code definition” button.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by smadueke** [comment]
<img width="952" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/56853418/4f54803c-439a-4af9-b673-c7ef6e39284c">

Hey Pam, doing what you stated doesn't change anything. 
The error Im getting after pressing reset to default code definition, is still Time Limit Exceeded. 

Also, I never removed the header. My bad. I forgot to copy that line when I submitted my code. This is the actual submitted code.

```
// Word Search
class Solution:
    def exist(self, board: List[List[str]], word: str) -> bool:
        directions = [[-1, 0], [1, 0], [0, -1], [0, 1]]
        visited = []

        def findWord(row, col, i):
            if i == len(word)-1:
                return True

            for nr, nc in directions:
                r, c = row + nr, col + nc
                if [r, c] in visited: continue
                if (r in range(len(board)) and c in range(len(board[0])) and board[r][c] == word[i+1]):
                    visited.append([row, col])
                    if findWord(r, c, i+1):
                        return True
                    visited.pop()
            return False

        for row in range(len(board)):
            for col in range(len(board[0])):
                if board[row][col] == word[0]:
                    if findWord(row, col, 0):
                        return True
        return False
```
