### ISSUE TITLE
Missing Test Case - 面试题 10.03. Search Rotate Array LCCI

### ISSUE THREAD

**Issue by UborKing** [LeetCode-Feedback/LeetCode-Feedback#15042]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by UborKing** [comment]
[2,2,2,0,2,2]
0

**Comment by UborKing** [comment]
> [2,2,2,0,2,2] 0

class Solution {
public:
    int search(vector<int>& nums, int tar) {
        int l = 0, r = nums.size()-1;
        while(l + 1 < r){
            if(nums[l] == tar) return l;
            int mid = l+r >> 1;
            if(nums[mid] == tar) r = mid;
            else if(nums[l] < nums[mid]) {
                if(tar>=nums[l] && tar<=nums[mid]) r = mid;
                else l = mid;
            }else if(nums[r] > nums[mid]){
                if(tar>=nums[mid] && tar<=nums[r]) l = mid;
                else r = mid;
            }
            else --r;
        }
        if(nums[l] == tar) return l;
        if(nums[r] == tar) return r;
        return -1;
    }
};
//这份代码可以过全部测试用例但是过不了这个

**Comment by feiceh** [comment]
你好，当前该题已更新， 请留言告知一下力扣中文网站的 ID，我们给予积分奖励哦。

**Comment by UborKing** [comment]
这是id
Ubor King
这是邮箱
***@***.***


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LeetCode-Feedback/LeetCode-Feedback"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月27日(星期四) 中午11:13
***@***.***&gt;;
抄送:&nbsp;"Ubor ***@***.******@***.***&gt;;
主题:&nbsp;Re: [LeetCode-Feedback/LeetCode-Feedback] Missing Test Case - 面试题 10.03. Search Rotate Array LCCI (Issue #15042)





 
你好，当前该题已更新， 请留言告知一下力扣中文网站的 ID，我们给予积分奖励哦。

**Comment by feiceh** [comment]
你好，后台暂未核实到相关的力扣 ID，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837，个人主页头像右侧一串小字就是正确的 ID 了，我们给予积分奖励哦。

**Comment by UborKing** [comment]
这个吗
leetcode.cn/u/warrior-k/





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LeetCode-Feedback/LeetCode-Feedback"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月27日(星期四) 中午1:01
***@***.***&gt;;
抄送:&nbsp;"Ubor ***@***.******@***.***&gt;;
主题:&nbsp;Re: [LeetCode-Feedback/LeetCode-Feedback] Missing Test Case - 面试题 10.03. Search Rotate Array LCCI (Issue #15042)





 
你好，后台暂未核实到相关的力扣 ID，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837，个人主页头像右侧一串小字就是正确的 ID 了，我们给予积分奖励哦。

**Comment by feiceh** [comment]
是的，奖励已经发放，请查收～
