### ISSUE TITLE
Issue in the backend code of  question: 160 - Intersection of Two Linked Lists

### ISSUE THREAD

**Issue by si-abhay** [LeetCode-Feedback/LeetCode-Feedback#15056]
#### Your LeetCode username
asingh20_be20

#### Category of the bug
- [ Intersection of Two Linked Lists -160] Question
- [
```# Self made Complete program on editor
class node:
    def __init__(self,data):
        self.data=data
        self.next=None

class ll:
    def __init__(self):
        ll.head=None

def getint(first, f1):
        temp=""
        while first:
            nexts=first.next
            first.next=temp
            first=nexts
        
        while f1:
            if f1.next==temp:
                return f1
            f1=f1.next
            
        return None


list=ll()
l1=ll()
first=node(1)
second=node(2)
third=node(3)
fourth=node(4)

f1=node(1)
f2=node(2)

l1.head=f1
f1.next=f2
f2.next=third

list.head=first
first.next=second
second.next=third
third.next=fourth

nodes=getint(first,f1)
print(nodes.data)
```
] Solution

- [ Python ] Language

#### Description of the bug

The code submitted on leetcode is giving some runtime error but for the same question I made my own linked lists and then implemented my logic and it is giving me correct ans that too in O(m+n) time complexity and space complexity of O(1)

#### Code you used for Submit/Run operation

```
class Solution(object):
    def getIntersectionNode(self, headA, headB):
        temp=""
        while headA:
            nexts=headA.next
            headA.next=temp
            headA=nexts
        
        while headB:
            if headB.next==temp:
                return headB
            headB=headB.next
            
        return None
```

#### Expected behavior

If the program is giving correct outputs on local editor and giving runtime error on platform it should have a correction in backend main code

**Comment by LC-Pam** [comment]
Thank you for reaching out to us! Unfortunately, we are unable to troubleshoot the different behavior between your local IDE and the LeetCode environment.

For this issue, please raise this as a discuss post in the problem discuss section as other users may have run into the same issue and resolved it.

At LeetCode, we care about the whole learning experience that comes with each problem and we encourage users to teach and help each other to enrich their learning. In addition, we want our users to debug their code and learn from the process.

We appreciate your time and support.
