### ISSUE TITLE
面试题 04.05. 合法二叉搜索树，测试用例结果错误。

### ISSUE THREAD

**Issue by ekil1100** [LeetCode-Feedback/LeetCode-Feedback#15051]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
like9

**Bug 类型**
- [ ] 题目
- [x] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述**
下面的测试用例预期结果应该是 true
<img width="1324" alt="CleanShot 2023-07-26 at 16 25 53@2x" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/10057502/aef6b77f-3716-470d-a59f-ccb047d768d9">

**你使用的语言**
JavaScript

**你提交或者运行的代码**
```js
/**
 * Definition for a binary tree node.
 * function TreeNode(val) {
 *     this.val = val;
 *     this.left = this.right = null;
 * }
 */
/**
 * @param {TreeNode} root
 * @return {boolean}
 */
var isValidBST = function(root) {
    return checkBST(root, -Infinity, Infinity)
};

function checkBST(root, min, max) {
    if(!root) return true

    if(root.val <= min || root.val > max) {
        return false
    }

    if(!checkBST(root.left, min, root.val)) {
        return false
    }
    
    if(!checkBST(root.right, root.val, max)) {
        return false
    }

    return true
}
```

**期望行为**
描述你期望的结果

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
题解中的方法一的代码也有问题，如果二叉搜索树的定义是 `left <= root < right` 的话。

**Comment by feiceh** [comment]
你好，在与相关团队核实后：不用处理， 二叉搜索树是 左子树所有节点小于根节点，右子树所有节点大于根节点。 因此 [1,1] 是 false。
本次 Ticket 将关闭，感谢您的反馈和支持。
