### ISSUE TITLE
Missing Test Case - 1870. Minimum Speed to Arrive on Time

### ISSUE THREAD

**Issue by Rishi-mittal13** [LeetCode-Feedback/LeetCode-Feedback#15065]
#### Your LeetCode username
HighFrost

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I Submitted my Code in Java All testcases are passed but Actually My code is Wrong there was a missing testcase in this problem . 

#### Code you used for Submit/Run operation

```
//1870. Minimum Speed to Arrive on Time
class Solution {
    public int minSpeedOnTime(int[] dist, double hour) {
        int l = 1 ,  h = 0 , ans = 0 ;
        for(int i : dist) if(i>h) h = i*100;
        while(l<=h){
            int mid  = l + (h-l)/2;
            if(isPossible(dist,mid , hour)){
                ans = mid ;
                h = mid-1;
            }
            else l = mid+1;
        }
        if(ans==0) return -1;
        return ans;
    }
    public static boolean isPossible(int[] dist , int mid , double hour){
        double total = 0 ;
        int n =  dist.length;
        for(int i = 0  ; i<n ; i++) {
            if(i==n-1) total+=((double)dist[i]/mid);
            else total+=Math.ceil((double)dist[i]/mid);
            if(total>hour) return false;
        }   
        return true ;
    }
}
```

#### Language used for code
JAVA

#### Expected behavior

All the Testcases is passed in this solution but that testcase([99999,3,100000] , 2.01) is fail please update this type of testcases in 
this solution .

#### Screenshots
![Bug ScreenShot](https://github.com/Rishi-mittal13/PROJECTS/blob/67bf7fb938ea19883278c3c4641ff2428904e4a9/Screenshot%20(2).png?raw=true)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
