### ISSUE TITLE
Missing Test Case - 14. Longest Common Prefix

### ISSUE THREAD

**Issue by hemantraturi0** [LeetCode-Feedback/LeetCode-Feedback#15060]
#### Your LeetCode username

hemantRaturi

#### Category of the bug
- [ >] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

["reflower","flow","flight"]
From my POV here the longest common prefix is "fl" but the test case says the result is ""(empty).
Please correct me with explanation if i am wrong.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    string longestCommonPrefix(vector<string>& strs) {
        string res="",temp="";
        int max=0, premax=0,min=strs[0].size(),n=1;
        
        if(strs.size()==1)
        {
            return strs[0];
        }
        for(int i=1;i<strs.size();i++)
        {
            if(strs[i].size()<min)
                min=strs[i].size();
        }
        while(n<=min)
        {
            for(int i=0;i<strs.size()-1;i++)
            {
                premax=0;
                for(int j=i+1;j<strs.size();j++)
                {
                    if(strs[i].substr(0,n)==strs[j].substr(0,n))
                    {
                        premax++;
                        temp=strs[i].substr(0,n);
                    }
                }
                if(max<=premax)
                {
                    max=premax;
                    res=temp;
                }
            }
            n++;
        }
        return res;
    }
};
```

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
