### ISSUE TITLE
Wrong tree diagram for sample input in #1612

### ISSUE THREAD

**Issue by snehasishroy** [LeetCode-Feedback/LeetCode-Feedback#1506]
#### Your LeetCode username
chrisgriffin

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
In https://leetcode.com/problems/check-if-two-expression-trees-are-equivalent/ for example 2 its mentioned that root2 = [+,+,b,c,a]. This should represent a tree like
<pre>
       +
  +         b
c   a
</pre>
However the diagram for tree is shown wrong in the problem description
![image](https://user-images.githubusercontent.com/4747384/100548375-30300700-3292-11eb-960f-8d1e52adb62f.png)

#### Expected behavior
Either correct the tree diagram or modify the sample input

**Comment by lc-kay** [comment]
Hi @snehasishroy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @snehasishroy 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
