### ISSUE TITLE
Invalid Test Case - 200. Number of Islands

### ISSUE THREAD

**Issue by junkblocker** [LeetCode-Feedback/LeetCode-Feedback#15076]
#### Your LeetCode username
junkblocker

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The test case claims the code generates an output of 4 while it does generate the expected output 3.

#### Code you used for Submit/Run operation
``` python
from collections import deque

class Solution:
    def numIslands(self, grid: List[List[str]]) -> int:
        islands = 0

        if len(grid) == 0:
            return islands

        rows = len(grid)
        cols = len(grid[0])

        visited = set()

        def bfs(r, c):
            nonlocal islands

            if (r,c) in visited:
                return

            q = deque()
            q.append((r,c))
            visited.add((r,c))

            while q:
                r, c = q.popleft()
                if c < cols - 2 and grid[r][c+1] == "1" and (r, c+1) not in visited:
                    q.append((r, c+1))
                    visited.add((r,c+1))
                if r < rows - 2 and grid[r+1][c] == "1" and (r+1, c) not in visited:
                    q.append((r+1, c))
                    visited.add((r+1,c))

            islands += 1
       
        for i in range(rows):
            for j in range(cols):
                if grid[i][j] == "1" and (i, j) not in visited:
                    bfs(i, j)

        return islands
```

#### Language used for code
python3

#### Expected behavior
The actual "Output" should be 3 and not 4 as claimed by the evaluator.

#### Additional context

Case 2

```
grid = [["1","1","0","0","0"],["1","1","0","0","0"],["0","0","1","0","0"],["0","0","0","1","1"]]
```

Tested locally and it does produce 3, not 4.

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
