### ISSUE TITLE
Missing Test Case - 242. Valid Anagram

### ISSUE THREAD

**Issue by vermaArpitt** [LeetCode-Feedback/LeetCode-Feedback#15072]
#### Your LeetCode username
vermaarpit 

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
The question is accepting a wrong solution due to missing test cases.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool isAnagram(string s, string t) {
        if(s.length()!=t.length())
        {
            return false;
        }

        unordered_map<char, int> s_freq, t_freq;

        for(int i=0; i<s.length(); i++)
        {
            s_freq[s[i]]++;
            t_freq[t[i]]++;
        }

        for(int i=0; i<s_freq.size(); i++)
        {
            if(s_freq[s[i]]!=t_freq[s[i]])
            {
                return false;
            }
        }

        return true;
    }
};
```

#### Language used for code
C++ 

#### Expected behavior
The code should not have been able to pass through all the test cases and accepted. It should have given wrong soution.
The code was able to pass all the test cases even though it is a wrong solution.

One of such testcases is attached.

[testcase_valid anagram.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/12177363/testcase_valid.anagram.txt)

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/131401678/3dd2285d-c793-49a9-8985-9b7ce966a12a)

Accepted yet showing wrong answer in my custom testcase.

#### Correct Solution
```
class Solution {
public:
    bool isAnagram(string s, string t) {
        if(s.length()!=t.length())
        {
            return false;
        }

        unordered_map<char, int> s_freq, t_freq;

        for(int i=0; i<s.length(); i++)
        {
            s_freq[s[i]]++;
            t_freq[t[i]]++;
        }

        for(int i=0; i<s.length(); i++)
        {
            if(s_freq[s[i]]!=t_freq[s[i]])
            {
                return false;
            }
        }

        return true;
    }
};
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
