### ISSUE TITLE
767. 重构字符串

### ISSUE THREAD

**Issue by junlancer** [LeetCode-Feedback/LeetCode-Feedback#1507]
** Bug 类型**
- [ ] 题目

**描述**
用例
"tndsewnllhrtwsvxenkscbivijfqnysamckzoyfnapuotmdexzkkrpmppttficzerdndssuveompqkemtbwbodrhwsfpbmkafpwyedpcowruntvymxtyyejqtajkcjakghtdwmuygecjncxzcxezgecrxonnszmqmecgvqqkdagvaaucewelchsmebikscciegzoiamovdojrmmwgbxeygibxxltemfgpogjkhobmhwquizuwvhfaiavsxhiknysdghcawcrphaykyashchyomklvghkyabxatmrkmrfsppfhgrwywtlxebgzmevefcqquvhvgounldxkdzndwybxhtycmlybhaaqvodntsvfhwcuhvuccwcsxelafyzushjhfyklvghpfvknprfouevsxmcuhiiiewcluehpmzrjzffnrptwbuhnyahrbzqvirvmffbxvrmynfcnupnukayjghpusewdwrbkhvjnveuiionefmnfxao"
输出:
"hehehehehehehehehehehehehehehehehehehehehehehehehehehehecmcmcmcmcmcmcmcmcmcmcmcmcmcmcmcmcmcmcmcmcmcmcmcmcmcmvnvnvnvnvnvnvnvnvnvnvnvnvnvnvnvnvnvnvnvnvnvnvnvafafafafafafafafafafafafafafafafafafafafafafykykykykykykykykykykykykykykykykykykykykykywuwuwuwuwuwuwuwuwuwuwuwuwuwuwuwuwuwuwuwuwspspspspspspspspspspspspspspspspspspsrxrxrxrxrxrxrxrxrxrxrxrxrxrxrxrxrxrxgogogogogogogogogogogogogogogogogobibibibibibibibibibibibibibibibitdtdtdtdtdtdtdtdtdtdtdtdtdtdtdtzjzjzjzjzjzjzjzjzjzjzjzlzlzlqlqlqlqlqlqlqlqlqlq"

**你使用的语言**
Java

**你提交或者运行的代码**
```
//767. Reorganize String
class Solution {
    public String reorganizeString(String s) {
        int[] c = new int[26];
        int max = 0;
        int max2 = 0;
        int index = 0;
        int index2 = 0;
        for(int i = 0;i<s.length();i++) {
            int x = s.charAt(i)-'a';
            c[x]++; 
            if(c[x]>max) {
                index = x;
                max = c[x];
            }       
        }
        for(int i = 0;i<c.length;i++) {
            if(c[i]>max2&&i!=index) {
                index2 = i;
                max2 = c[i];
            }
            
        }
        boolean f = false;
        if(s.length()%2==0) {
            f = true;
        }
        if((f&&max>s.length()/2)||(!f&&max>s.length()/2+1)) {
            return "";
        }
        
        //多到少排
        char[] re = new char[s.length()];
        int iRe = 0;
        while(iRe<s.length()) {
            re[iRe++] =(char)(index+'a');
            if(--c[index]==0) {
                max = 0;
                for(int i = 0;i<c.length;i++) {
                    if(c[i]>max&&i!=index2) {
                        max = c[i];
                        index = i;
                    }
                }
                
            }
            if(iRe==s.length()) return new String(re);
            re[iRe++] =(char)(index2+'a');
            if(--c[index2]==0) {
                max = 0;
                for(int i = 0;i<c.length;i++) {
                    if(c[i]>max&&i!=index) {
                        max = c[i];
                        index2 = i;
                    }
                }
            }
        }
        return new String(re);
    }
}
```

**期望行为**
运行此输出通过

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![image](https://user-images.githubusercontent.com/35421868/100563950-9cdeec00-32fa-11eb-832a-f771c5aab7f6.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by junlancer** [comment]
我弄错了谢谢
