### ISSUE TITLE
Missing Test Case - 1870. Minimum Speed to Arrive on Time

### ISSUE THREAD

**Issue by krishnakeshav** [LeetCode-Feedback/LeetCode-Feedback#15079]
#### Your LeetCode username

close27

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Problem

     1870. Minimum Speed to Arrive on Time
[link](https://leetcode.com/problems/minimum-speed-to-arrive-on-time/description/)

#### Description of the bug

In test case 3 when `hour = 2.7`, the expected answer is again 3. Now, if we set speed = 3 and calculate time of `dist[]`, we get 2.67 rounded of to 2.7. When `hour = 2.77`, the minimum speed expected is 3. This is not possible since as we saw earlier, that with `speed = 3`, the result of operation on dist[] = 2.67 and `round(2.77, 1) != round(2.67, 1) `

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
class Solution:
    def minSpeedOnTime(self, dist: List[int], hour: float) -> int:
        l, h = 1, 1e9
        while l <= h:
            m = (l + h)// 2 # m = 0 + 1 / 2 = 0
            t = sum([i//m if i // m >= 1 else 1 for i in dist[:-1]])
            if m == 3:
                print(t)
            t += (dist[-1]/m)
            print(l,h,m, t)
            if round(t, 1) == round(hour, 1):
                return int(m)
            if t < hour: #4, 6
                h = m - 1
            else:
                l = m + 1
        return -1
```

#### Language used for code

Python

#### Expected behavior

I think the expected answer should be 2 since, operation on `dist[]` with `speed = 3` will result in 2.67 which is rounded of to 2.7. To match the `hour = 2.7`, we need to lower the speed, so `speed = 2` should be the answer.

**Comment by khushdj2002** [comment]
can you send test cases. Both dist[] and hour and expected output

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
