### ISSUE TITLE
Missing Test Case - 2141. Maximum Running Time of N Computers

### ISSUE THREAD

**Issue by nkthien** [LeetCode-Feedback/LeetCode-Feedback#15085]
#### Your LeetCode username

nkt165

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

With this following test case, the output is wrong according to the description and editorial.
For input: 

- n = 3
- batteries = [2,4,4,10]

Leetcode output: 5
Expected output: 4

For editorial #1 solution, the chosen batteries is [4,4,10], the extra battery is [2]. After finish the first round, two batteries with value 4 are ran out at the same time, and there only 1 remaining battery left which is [2], and it can not be shared between the two computers at the same time. So 1 computer die at minute 4, therefore the solution should be 4 instead of 5.

#### Code you used for Submit/Run operation

```
// Two Sum
public class Solution {
    public long maxRunTime(int n, int[] batteries) {
        // Get the sum of all extra batteries.
        Arrays.sort(batteries);
        long extra = 0;
        for (int i = 0; i < batteries.length - n; i++) {
            extra += batteries[i];
        }

        // live stands for the n largest batteries we chose for n computers.

        int[] live = Arrays.copyOfRange(batteries, batteries.length - n, batteries.length);

        // We increase the total running time using 'extra' by increasing 
        // the running time of the computer with the smallest battery.
        for (int i = 0; i < n - 1; i++) {
            // If the target running time is between live[i] and live[i + 1].
            if (extra < (long)(i + 1) * (live[i + 1] - live[i])) {
                return live[i] + extra / (long)(i + 1);
            }

            // Reduce 'extra' by the total power used.
            extra -= (long)(i + 1) * (live[i + 1] - live[i]);
        }

        // If there is power left, we can increase the running time 
        // of all computers.
        return live[n - 1] + extra / n;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The output of the above test case should be 4 instead 5, according to the description.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

“you can remove a battery from a computer and insert another battery any number of times.”
spend half of “2” then insert “4” in the first one. and vice versa in the second one.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
