### ISSUE TITLE
Missing Test Case - 430. Flatten a Multilevel Doubly Linked List

### ISSUE THREAD

**Issue by shadowpigy** [LeetCode-Feedback/LeetCode-Feedback#1508]
#### Your LeetCode username
shadowpigy

#### Category of the bug
Wrong answer accepted

#### Description of the bug
This code failed test case:
[1,2,3,4,5,6,null,null,null,7,8,null,null,11,12]

But submission is accepted 

#### Code you used for Submit/Run operation
```
// Flatten a Multilevel Doubly Linked List
class Solution:
    def flatten(self, head: 'Node') -> 'Node':
        walk = head
        stack = []
        while walk is not None:
            if walk.child is not None:
                stack.append(walk.next)
                parent = walk
                child = walk.child
                parent.next, parent.child = child, None
                child.prev = parent
                walk = child
                continue
            if walk.next is None and stack:
                next_node = stack.pop()
                if next_node is None:
                    break
                walk.next = next_node
                next_node.prev = walk
                walk = walk.next
                continue
            walk = walk.next
        return head     
```

#### Language used for code
Python 3

#### Expected behavior

This code is wrong but is accepted due to the lack of corresponding test case.
Add this:
[1,2,3,4,5,6,null,null,null,7,8,null,null,11,12]

**Comment by lc-kay** [comment]
Hi @shadowpigy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @shadowpigy 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
