### ISSUE TITLE
215. Kth Largest Element: Confusing Description

### ISSUE THREAD

**Issue by akinsey2** [LeetCode-Feedback/LeetCode-Feedback#15093]
#### Your LeetCode username
[akinsey2](https://leetcode.com/akinsey2/)

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The problem statement says:
"**_Can you solve it without sorting?_**"

This is extremely confusing and misleading.

Every possible solution to this problem involves some type of "sorting".  Quickselect involves **sorting**.  Min/Max heaps are **sorted** data structures. 

The task of "sorting" is fundamentally built into the problem statement...."The Kth largest element" could not exist without the idea of a count in a sorted order.

Recommendation: change the problem statement to say:

"**Without sorting the entire array.**" 

#### Code you used for Submit/Run operation

Not applicable.  Issue is in problem statement.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

There is a solution to that.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
