### ISSUE TITLE
Missing Test Case - 1153. String Transforms Into Another String

### ISSUE THREAD

**Issue by janosgyerik** [LeetCode-Feedback/LeetCode-Feedback#1509]
#### Your LeetCode username
janos

#### Category of the bug
Wrong answer accepted

#### Description of the bug
The code below fails test case:
```
"aa"
"ab"
```
But submission is accepted.

#### Code you used for Submit/Run operation
```
func canConvert(str1 string, str2 string) bool {
    if str1 == str2 {
        return true
    }
    
    conversions := make(map[byte]byte)
    
    for i := range str1{
        if v, ok := conversions[str1[i]]; ok{
            if v != str2[i]{
                return false
            }
            
            continue
        }
        if str1[i] == str2[i]{
            continue
        }
        
        conversions[str1[i]] = str2[i]
    }
    
    str2Runes := make(map[rune]bool)
    for _, r := range str2{
        str2Runes[r]=true
    }
    
    return len(str2Runes) != 26
}
```

#### Language used for code
Go

#### Expected behavior
Submission should fail with Wrong Answer.

**Comment by lc-kay** [comment]
Hi @janosgyerik 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @janosgyerik 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
