### ISSUE TITLE
2050. 并行课程 Ⅲ 官方题解 笔误更正

### ISSUE THREAD

**Issue by mantoufan** [LeetCode-Feedback/LeetCode-Feedback#15103]
> **你的 LeetCode 用户名**
mantoufan

**Bug 类型**
- [ ] 题目
- [x] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
[官方题解](https://leetcode.cn/problems/parallel-courses-iii/solutions/2357818/bing-xing-ke-cheng-iii-by-leetcode-solut-aw43/)中的 `临接表` 笔误，应更正为 `邻接表`，共三处：
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/4961543/3d343785-5794-42dc-abec-71c52d61ae32)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/4961543/e5c8582f-77af-46b2-8406-fc85223ae669)

**Comment by feiceh** [comment]
感谢反馈，当前题解错别字已经更新，奖励已发放，请查收～
