### ISSUE TITLE
278. First Bad Version - Missing Dart support

### ISSUE THREAD

**Issue by TinhHuynh** [LeetCode-Feedback/LeetCode-Feedback#15117]
#### Your LeetCode username
tinhhuynh

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
[278. First Bad Version](https://leetcode.com/problems/first-bad-version/description/) is missing Dart language support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've submitted your feedback to the team.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

Currently, we don’t have enough resources to support Dart on these problems.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
