### ISSUE TITLE
Missing Test Case - 2510. Check if There is a Path With Equal Number of 0's And 1's

### ISSUE THREAD

**Issue by aminegh20** [LeetCode-Feedback/LeetCode-Feedback#15113]
#### Your LeetCode username
near-river

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

I provided a wrong solution to the problem and it passed. 

#### Code you used for Submit/Run operation
```c++
class Solution {
public:
  bool isThereAPath(vector<vector<int>>& grid) {
    const int n = (int) grid.size();
    const int m = (int) grid[0].size();

    if ((m + n - 1) & 1) {
      return false;
    }      

    int cnt = 0;
    for (int i = 0; i < n; i++) {
      for (int j = 0; j < m; j++) {
        cnt += grid[i][j];
      }
    }

    return cnt > (m + n - 1) / 2;
  }
};
```

#### Language used for code

C++

#### Expected behavior

The code should fail, but my solution actually passes. 
It failed on the following custom test case: 
```
grid = [[1,1,1,0],[0,0,0,0],[0,0,0,0]]
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
