### ISSUE TITLE
10. 正则表达式匹配 - Python - "代码执行结果" 中的 “预期结果” 有误

### ISSUE THREAD

**Issue by Crysflair** [LeetCode-Feedback/LeetCode-Feedback#1511]
**Bug 类型**
- [ ] 题目 10. 正则表达式匹配
- [ ] 编程语言 Python

**描述**
"代码执行结果" 中的 “预期结果” 有误。星号应该是幂等的。但这里连续的星号奇数个是正常算的，偶数个就开始抽风。
![1K5DR_J}_GC05QR8~RM5OMH](https://user-images.githubusercontent.com/26264267/100651136-f9381f00-337f-11eb-9683-5f0695bf7a3c.png)

对于输入 s = "absdfaaa",  p = `"...**a*" `输出false，但是`"...***a*"`算true，然而`"...****a*"`又算false。经过多次试验，奇数正常，偶数算错。要是所有的星号多次重复都算格式错误也就算了。但现在这个样子怎么看都是bug。
 

**你使用的语言**
Python

**你提交或者运行的代码**  (可以正确处理重复星号，供参考)
```python
import functools
class Solution:
    def isMatch(self, s: str, p: str) -> bool:
        
        @functools.lru_cache(maxsize=None, typed=False)         # 暂存结果，避免重复计算
        def match(cur1, cur2):  # s[cur1:]和p[cur2:]匹配吗？
            
            while cur1 < len(s) and cur2 < len(p): 
                
                if p[cur2] == '*':  # 多余的星号跳过，正常来讲不应打头出现
                    cur2 += 1
                    
                elif cur2 + 1 < len(p) and p[cur2+1]=='*':      # 出现星号
                    if s[cur1]==p[cur2] or p[cur2]=='.':
                        if match(cur1, cur2+2): return True     # 跳过匹配
                        if match(cur1+1, cur2): return True     # 匹配多次
                        return False
                    else:  # 字符无法match，只好跳过
                        cur2 += 2
                    
                else:   # 没有星号，直接匹配
                    if s[cur1]==p[cur2] or p[cur2]=='.':
                        cur1 += 1
                        cur2 += 1
                    else: return False
            
            # 最后, 多余的pattern可能可以为解释为空
            while cur2 < len(p): 
                if p[cur2] == '*': 
                    cur2 += 1
                elif cur2 + 1 < len(p) and p[cur2+1]=='*':    
                    cur2 += 2   # 统统匹配0次
                else: break     # 遇见实体字符就真没的救了
                    
            return cur1 == len(s) and cur2 == len(p)
                
        return match(0, 0)
```

**期望行为**
对于输入 s = "absdfaaa",  p = `"...**a*"` ，`"...***a*"`，`"...****a*"` 都算 True

**屏幕截图**
![1K5DR_J}_GC05QR8~RM5OMH](https://user-images.githubusercontent.com/26264267/100651136-f9381f00-337f-11eb-9683-5f0695bf7a3c.png)
![image](https://user-images.githubusercontent.com/26264267/100651788-f4c03600-3380-11eb-934d-14ff6a3e17de.png)
![image](https://user-images.githubusercontent.com/26264267/100651836-099cc980-3381-11eb-8991-cf2f6324a9c8.png)

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by zerotrac** [comment]
请认真读题：「保证每次出现字符 * 时，前面都匹配到有效的字符」

**Comment by feiceh** [comment]
题目的提示 “保证每次出现字符 * 时，前面都匹配到有效的字符”， 而连续的星号并不满足该条件。
