### ISSUE TITLE
Missing Test Case - 334. Increasing Triplet Subsequence

### ISSUE THREAD

**Issue by Ashley-hue** [LeetCode-Feedback/LeetCode-Feedback#15121]
#### Your LeetCode username

AshleySiobhan22

#### Category of the bug
- [ ] Question
- [ ] 334
- [ ] Solution
- [ ] class Solution {
    public boolean increasingTriplet(int[] nums) {
        int i = Integer.MAX_VALUE; 
        int j  = Integer.MAX_VALUE;

        for(int k = 0; k < nums.length; k++){
            if(nums[k] <= i){
                i = nums[k];
            }
            else if(nums[k] <= j){
                j = nums[k];
            }
            else{
                return true;
            }
        }
        return false;
    }
}
- [ ] Language
- [ ] Java
- [ ] Missing Test Cases 
- [ ] [2,1,5,0,6,8]

#### Description of the bug

If I run that code, with the testcase I've provided, it'll still be true, but then the problem will not have been solved. It'll just return true.

#### Code you used for Submit/Run operation
<!-- 
```class Solution {
    public boolean increasingTriplet(int[] nums) {
        int i = Integer.MAX_VALUE; 
        int j  = Integer.MAX_VALUE;

        for(int k = 0; k < nums.length; k++){
            if(nums[k] <= i){
                i = nums[k];
            }
            else if(nums[k] <= j){
                j = nums[k];
            }
            else{
                return true;
            }
        }
        return false;
    }
}```
Please make sure you wrap your code with ``` tags. 
Otherwise we may reject your request. 
-->

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code
<!-- Java -->


#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->
The code should work correctly, I submitted that and it worked which is good, but the logic makes no sense. If I run that code, it'll return true but then the condition <j will not have been met, it'll just return true. i will have 0, j will have 5 and k would be 8. which is correct, but then j should have 6 not 5.



#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
