### ISSUE TITLE
1. Two Sum - Typo In Question

### ISSUE THREAD

**Issue by agrawalishaan** [LeetCode-Feedback/LeetCode-Feedback#15125]
#### Your LeetCode username
agrawalishaan

#### Category of the bug
- [ X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

In the 2-sum problem description, in the follow up, it wrotes:

`Follow-up: Can you come up with an algorithm that is less than O(n2) time complexity?`

I know it is hard to tell from here (I will attach a screenshot), but there is a typo with the formatting in the problem. They use code formatting on an extra blank space, see here:

![Screenshot 2023-07-28 at 9 53 22 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/113543798/a879e928-4256-460f-a47a-5f88bddb8cef)

The empty space after the big O notation shouldn't be code-formatted.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
