### ISSUE TITLE
2756. 批处理查询   题目描述有错

### ISSUE THREAD

**Issue by kevfeng01** [LeetCode-Feedback/LeetCode-Feedback#15123]
示例1的最后一行：
在 t=110ms 时，调用 queryMultiple(['a', 'b']) 并立即返回结果。 
应为： 在 t=110ms 时，调用 queryMultiple(['b', 'c']) 并立即返回结果。

**Comment by feiceh** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励哦。
