### ISSUE TITLE
Editorial typos - 808. Soup Servings

### ISSUE THREAD

**Issue by xelplogoog** [LeetCode-Feedback/LeetCode-Feedback#15124]
#### Your LeetCode username
c4tdog

#### Description of the bug
https://leetcode.com/problems/soup-servings/editorial/
There are 2 typos in word `recurrence`

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2188302/36da544e-2682-443d-b2c4-1f65dc4d809e)

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2188302/0accde96-5f29-4688-a20f-bc09bfb747d6)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
