### ISSUE TITLE
Missing Test Case - 808. Soup Servings

### ISSUE THREAD

**Issue by shiv-abhi77** [LeetCode-Feedback/LeetCode-Feedback#15129]
#### Your LeetCode username
shiv_abhi_ngr

#### Category of the bug

- [ ] Missing Test Cases 

#### Description of the bug
In my code, I put the condition that if n>3500, then return 1. But the precise answer for test case 3505 is 0.99992 which differs from my answer and then also my code got accepted. Many test cases are missing.

#### Code you used for Submit/Run operation
```
class Solution {
public:
    double dp[3405][3405];
    double soup(int sa, int sb)
    {
        if(sa<=0 && sb<=0)
        {
            cout<<"ok";
            return 0.5;
        }
        if(sa<=0)
        {
            return 1.00;
        }
        if(sb<=0)
        {
            return 0;
        }
        if(dp[sa][sb]!=0)
        {
            return dp[sa][sb];
        }
        double ans=0;
        ans+=soup(sa-100,sb);

        ans+=soup(sa-75,sb-25);
        ans+=soup(sa-50,sb-50);
       
        ans+=soup(sa-25,sb-75);


        ans=ans*0.25;
        return dp[sa][sb]=ans;

    }
    double soupServings(int n) {
        memset(dp,0,sizeof(dp));
        if(n>=3400)
        {
            return 1;
        }
        int sa=n,sb=n;
        double ans=0;
        ans=soup(sa,sb);
        
        return ans;

    }
};
```

#### Language used for code
c++

#### Expected behavior
It should give wrong answer for my code.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
