### ISSUE TITLE
Missing Test Case - 20. Valid Parentheses

### ISSUE THREAD

**Issue by nisharathod2301** [LeetCode-Feedback/LeetCode-Feedback#15132]
#### Your LeetCode username

nisharathod2301

#### Category of the 
- [ ] Incomplete problem description 

#### Description of the bug

The description for this one should say ([]{}) is valid.
And the input ({)} is invalid.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool isValid(string s) {
        // Initialize a stack and a index idx = 0...
        stack<char> stack;
        int idx = 0;
        // If the string is empty, return true...
        if(s.size() == 0){
            return true;
        }
        // Create a loop to check parentheses...
        while(idx < s.size()){
            // If it contains the below parentheses, push the char to stack...
            if( s[idx] == '(' || s[idx] == '[' || s[idx] == '{' ){
                stack.push(s[idx]);
            }
            // If the current char is a closing brace provided, pop the top element...
            // Stack is not empty...
            else if ( (s[idx] == ')' && !stack.empty() && stack.top() == '(') ||
                        (s[idx] == '}' && !stack.empty() && stack.top() == '{') ||
                        (s[idx] == ']' && !stack.empty() && stack.top() == '[')
                      ){
                stack.pop();
            }
            else {
                return false;       // If The string is not a valid parenthesis...
            }
            idx++;      // Increase the index...
        }
        // If stack.empty(), return true...
        if(stack.empty()) {
            return true;
        }
        return false;
    }
};
```

#### Language used for code
 C++

#### Expected behavior

On the given testcase there should be description mentioned.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
