### ISSUE TITLE
Missing Test Case - 218. The Skyline Problem

### ISSUE THREAD

**Issue by cloverpku** [LeetCode-Feedback/LeetCode-Feedback#1514]
#### Your LeetCode username
cloverpku

#### Category of the bug
Missing Test Case for 218. The Skyline Problem

#### Description of the bug
Proposed Test Case: [[4,67,187],[3,80,65],[49,77,117],[67,74,9],[6,42,92],[48,67,69],[10,13,58],[47,99,152],[66,99,53],[66,71,34],[27,63,2],[35,81,116],[47,49,10],[68,97,175],[20,33,53],[24,94,20],[74,77,155],[39,98,144],[52,89,84],[13,65,222],[24,41,75],[16,24,142],[40,95,4],[6,56,188],[1,38,219],[19,79,149],[50,61,174],[4,25,14],[4,46,225],[12,32,215],[57,76,47],[11,30,179],[88,99,99],[2,19,228],[16,57,114],[31,69,58],[12,61,198],[70,88,131],[7,37,42],[5,48,211],[2,64,106],[49,73,204],[76,88,26],[58,61,215],[39,51,125],[13,38,48],[74,99,145],[4,12,8],[12,33,161],[61,95,190],[16,19,196],[3,84,8],[5,36,118],[82,87,40],[8,44,212],[15,70,222],[16,25,176],[9,100,74],[38,78,99],[23,77,43],[45,89,229],[7,84,163],[48,72,1],[31,88,123],[35,62,190],[21,29,41],[37,97,81],[7,49,78],[83,84,132],[33,61,27],[18,45,1],[52,64,4],[58,98,57],[14,22,1],[9,85,200],[50,76,147],[54,70,201],[5,55,97],[9,42,125],[31,88,146]]

#### Code you used for Submit/Run operation

Below is incorrect codes which got accepted
```
class Solution:
    def getSkyline(self, buildings: List[List[int]]) -> List[List[int]]:
        ### sort by left, and reverse height
        buildings = sorted(buildings, key=lambda r:(r[0], -r[2]))
        res = []
        left_heights = collections.deque([])
        for left,right,height in buildings:
            if not res:
                res.append([left,height])
                left_heights.append([right,height])
            else:
                # clean prev right before current left
                while left_heights and left_heights[0][0] < left:
                    rr, hh = left_heights.popleft()
                    if left_heights:
                        res.append([rr, left_heights[0][1]])
                    else:
                        res.append([rr, 0])
                
                # the first right in tmp same with left
                if left_heights and left_heights[0][0] == left:
                    left_heights.popleft()
                    # as long as height is different, can add
                    if height != res[-1][-1]:
                        res.append([left, height])
                # otherwise, height needs > previous height, to add new point
                elif height > res[-1][1]:
                    res.append([left, height])
                    
                # update tmp
                tmp2 = collections.deque([])
                tmp3 = collections.deque([])
                for rr, hh in left_heights:
                    # only keep right < current right & height > current height
                    if rr < right:
                        if hh > height:
                            tmp2.append([rr,hh])
                    else:
                        tmp3.append([rr,hh])
                if not tmp3 or (tmp3 and height > tmp3[0][1]):
                    tmp2.append([right, height])
                    if tmp3 and right == tmp3[0][0]:
                        tmp3.popleft()
                left_heights = tmp2 + tmp3
        
        if left_heights:
            left_heights += [[0,0]]
            res.extend([[left_heights[i][0], left_heights[i+1][1]] for i in range(len(left_heights)-1)])
            
        return res
```

#### Language used for code
<Python3>

#### Expected behavior
Expected Output: [[1,219],[2,228],[19,225],[45,229],[89,190],[95,175],[97,152],[99,74],[100,0]]
Wrong Output with above codes: [[1,219],[2,228],[19,149],[35,190],[45,229],[89,190],[95,175],[97,152],[99,74],[100,0]]

#### Screenshots
![image](https://user-images.githubusercontent.com/10625136/100685576-a4c67c80-334a-11eb-9568-618a1e336c9d.png)
![image](https://user-images.githubusercontent.com/10625136/100685612-b576f280-334a-11eb-9ecc-c1c0dd884e5a.png)

**Comment by lc-kay** [comment]
@cloverpku The validators for this problem were recently updated, therefore, the test case you proposed is an invalid test case. The 'left values' must be non-decreasing. Thank you for your time!

**Comment by cloverpku** [comment]
Please find this test case which has been sorted: [[1, 38, 219], [2, 19, 228],[2, 64, 106], [3, 80, 65],[3, 84, 8], [4, 12, 8], [4, 25, 14], [4, 46, 225], [4, 67, 187], [5, 36, 118], [5, 48, 211], [5, 55, 97], [6, 42, 92], [6, 56, 188], [7, 37, 42], [7, 49, 78], [7, 84, 163], [8, 44, 212], [9, 42, 125], [9, 85, 200], [9, 100, 74], [10, 13, 58], [11, 30, 179], [12, 32, 215], [12, 33, 161], [12, 61, 198], [13, 38, 48], [13, 65, 222], [14, 22, 1], [15, 70, 222], [16, 19, 196], [16, 24, 142], [16, 25, 176], [16, 57, 114], [18, 45, 1], [19, 79, 149], [20, 33, 53], [21, 29, 41], [23, 77, 43], [24, 41, 75], [24, 94, 20], [27, 63, 2], [31, 69, 58], [31, 88, 123], [31, 88, 146], [33, 61, 27], [35, 62, 190], [35, 81, 116], [37, 97, 81], [38, 78, 99], [39, 51, 125], [39, 98, 144], [40, 95, 4], [45, 89, 229],[47, 49, 10],[47, 99, 152], [48, 67, 69], [48, 72, 1], [49, 73, 204], [49, 77, 117], [50, 61, 174], [50, 76, 147], [52, 64, 4], [52, 89, 84], [54, 70, 201], [57, 76, 47], [58, 61, 215], [58, 98, 57], [61, 95, 190], [66, 71, 34], [66, 99, 53], [67, 74, 9], [68, 97, 175], [70, 88, 131], [74, 77, 155], [74, 99, 145], [76, 88, 26], [82, 87, 40], [83, 84, 132], [88, 99, 99]]

**Comment by lc-kay** [comment]
Hi @cloverpku 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @cloverpku 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by cloverpku** [comment]
Thanks lc-kay,

Sorry I just realized I incorrectly reported my leetcode ID. Actually it
should be clover_pku
I forgot a '_'

**Comment by lc-kay** [comment]
@cloverpku No worries, I just rewarded your account.

**Comment by cloverpku** [comment]
@lc-kay Thanks a lot.
