### ISSUE TITLE
Run accepts answer though output is different than expected.

### ISSUE THREAD

**Issue by RamachandranSitaraman** [LeetCode-Feedback/LeetCode-Feedback#15146]
#### Your LeetCode username

weareus

#### Category of the bug
- [ ] Question
- [ X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

On running the test case for fair candy swap problem, the run accepts the results even though the expected and output are different.  What do i make out of it, is the answer correct and bug is in the expected or is the answer really wrong and the bug is in the acceptance?

#### Code you used for Submit/Run operation

```
class Solution:
    def fairCandySwap(self, aliceSizes: List[int], bobSizes: List[int]) -> List[int]:
        an = sum(aliceSizes)
        bn = sum(bobSizes)
        alicesizes = sorted(aliceSizes)
        bobsizes = sorted(bobSizes)
        exchdiff = abs(an - bn)
        ps = 0
        pl = 0
        sa = []
        la = []
        if an == bn:
            return []
        ismaxalice = True
        if an < bn:
            ps = len(alicesizes) - 1
            pl = 0
            ss = len(alicesizes)
            ls = len(bobsizes)
            sa = alicesizes
            la = bobsizes
            ismaxalice = False
        else:
            ps = len(bobsizes) - 1
            pl = 0
            ss = len(bobsizes)
            ls = len(alicesizes)
            sa = bobsizes
            la = alicesizes
        while(ps >=0 and pl<ls):
            diff = la[pl]-sa[ps]
            while(ps >=0 and diff < exchdiff/2):
                ps -= 1
                diff = la[pl] - sa[ps]
            if diff == exchdiff/2:
                if ismaxalice:
                    return [alicesizes[pl], bobsizes[ps]]
                else:
                    return[alicesizes[ps], bobsizes[pl]]
            ps = len(sa) -1
            pl += 1
        return -1

```

#### Language used for code

Python3

#### Expected behavior

Expected:
  Either the answer is rejected with expected different from output or the answer is accepted with expected same as output
What actually happened:
Answer is accepted with expected different from output.

#### Screenshots

Output
[48,96594]
Expected
[1483,98029]
but answer is accepted

**Comment by pranshugupta54** [comment]
Question clearly mentions "If there are multiple answers, you may return any one of them. It is guaranteed that at least one answer exists."
<img width="535" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/76090263/06221f84-4216-4b19-b2d9-b161f0812eb3">

**Comment by RamachandranSitaraman** [comment]
In that event it would be more helpful if the expected answer returns all possible values, so that it is easy to verify
