### ISSUE TITLE
Missing Test Case - 2529. Maximum Count of Positive Integer and Negative Integer

### ISSUE THREAD

**Issue by mohak300501** [LeetCode-Feedback/LeetCode-Feedback#15141]
#### Your LeetCode username

mohak_k

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

There are missing test cases for the given problem.

#### Code you used for Submit/Run operation

```
// Maximum Count of Positive Integer and Negative Integer
class Solution:
    def maximumCount(self, nums: List[int]) -> int:
        p, n = 0, 0
        if not nums[0] and not nums[-1]: return 0

        if nums[0] < 0:
            i, j = 0, len(nums) - 1
            while (i+j) // 2 != i:
                if nums[(i+j) // 2] < 0: i = (i+j) // 2
                else: j = (i+j) // 2
            n = j
        else: return len(nums)

        if nums[-1] > 0:
            i, j = 0, len(nums) - 1
            while (i+j) // 2 != i:
                if nums[(i+j) // 2] > 0: j = (i+j) // 2
                else: i = (i+j) // 2
            p = len(nums) - j
        else: return len(nums)

        return max(p, n)
```

#### Language used for code

Python3

#### Expected behavior

The above code [passes](https://leetcode.com/problems/maximum-count-of-positive-integer-and-negative-integer/submissions/1007105004/) for all given test cases (164 in number). But there are two edge cases which are not considered by the makers of the problem.
The present code fails for those (missing) test cases in which the 'nums' array begins or ends with zeroes but has other non-zero elements. For e.g., the code fails for nums = [-2,-1,-1,0,0,0] and nums = [0,0,66,1314].

If the lines 7 and 15 in the above code are modified to
```if nums[0] <= 0:``` and
```if nums[-1] >= 0:``` respectively,
the code will [pass](https://leetcode.com/problems/maximum-count-of-positive-integer-and-negative-integer/submissions/1007115954/) for all possible edge cases, including those which I claim are currently missing.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
