### ISSUE TITLE
wrong test case for 287. Find the Duplicate Number 

### ISSUE THREAD

**Issue by rishabhjha28** [LeetCode-Feedback/LeetCode-Feedback#15145]
#### Wrong test case
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

according to the problem description {2,2,2,2,2} should not be in the test case but 18th test case is the same.

#### Code you used for Submit/Run operation

```
// 287. Find the Duplicate Number 
class Solution {
public:
    int findDuplicate(vector<int>& nums) {
        int len = nums.size();
        int ans = 0;
        for(int i = 0;i < len;i++){
            ans = ans ^ nums[i] ^ i;
        }
        return ans;
    }
};```

#### Language used for code
<!-- C++ -->
C++

#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->
This test case should not be present in the test cases. since there should be only one repeated number in the array


#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by pranshugupta54** [comment]
For {2,2,2,2,2}, the only repeated number is **2**. It doesn't tell how many times but the repeated number occurs only once.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by rishabhjha28** [comment]
> For {2,2,2,2,2}, the only repeated number is **2**. It doesn't tell how many times but the repeated number occurs only once.

Thanks for this.
Actually, I interpreted the question wrong.
