### ISSUE TITLE
Missing Test Case - 713. Subarray Product Less Than K

### ISSUE THREAD

**Issue by Vinit-Chandak** [LeetCode-Feedback/LeetCode-Feedback#15143]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x ] Missing Test Cases 

#### Description of the bug

The expected answer to the following testcase is 0, but a lot of AC codes return 5 as the answer.
[1, 2, 3, 4, 5]
1

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int numSubarrayProductLessThanK(vector<int>& arr, int k) {
        long long gans = 0;
        int start = 0;
        long long prod = 1;
        for(int end = 0; end<arr.size(); end++){
            prod *= arr[end];
            while(prod>=k && start<arr.size()){
                prod/=arr[start];
                start++;
            }
            if(prod<k)
                gans+=end-start+1;
        }
        return gans;
    }
};
```

#### Expected behavior

The expected answer should be 0, but the above code which was accepted returns 5 as the answer which is wrong.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
