### ISSUE TITLE
207. 课程表 数据范围翻译错误

### ISSUE THREAD

**Issue by RickyLiu0w0** [LeetCode-Feedback/LeetCode-Feedback#15147]
**你的 LeetCode 用户名**
rickyliu

**Bug 类型**
- [X] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
在题目[207. 课程表](https://leetcode.cn/problems/course-schedule/)中，数据范围翻译错误

英文：

>  Constraints:
> * 1 <= numCourses <= 2000
> * 0 <= prerequisites.length <= 5000
> * prerequisites[i].length == 2
> * 0 <= ai, bi < numCourses
> * All the pairs prerequisites[i] are unique.

中文翻译：

> * `1 <= numCourses <= 10^5`
> * 0 <= prerequisites.length <= 5000
> * prerequisites[i].length == 2
> * 0 <= ai, bi < numCourses
> * prerequisites[i] 中的所有课程对 互不相同

**期望行为**
numCourses的正确范围时`[1,2000]`

**屏幕截图**
<img width="697" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/50950678/4c76db06-ce53-4ee9-84c6-4c3e1ef5324f">

**Comment by feiceh** [comment]
感谢反馈，当前题目已更新，奖励已发放，请查收～
