### ISSUE TITLE
Missing Test Case - 424. Longest Repeating Character Replacement

### ISSUE THREAD

**Issue by DanaIzadpanah** [LeetCode-Feedback/LeetCode-Feedback#15142]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Additional context

Given the above criteria, here's a crafted test case:

Input:
s = "AABACDAAABBAEFAAGGAAHIAAAJKAALAA"
k = 5

Expected Output:
15

Explanation:
The substring "FAAGGAAHIAAAJKA" has the length of 15. You can replace "FGHJK" (5 characters) to make the substring consist of only the repeating character "A".

This test case is designed to challenge the sliding window algorithm since the window needs to slide past multiple characters and expand through the string. The provided string has repeated patterns, but only a specific sequence in the middle allows a substring of length 15 to be transformed into a single character substring using at most 5 replacements.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
