### ISSUE TITLE
Incorrect syntax - 486. Predict the Winner

### ISSUE THREAD

**Issue by ArielRotem1** [LeetCode-Feedback/LeetCode-Feedback#15157]
#### Your LeetCode username
ariel_rotem

#### Category of the bug
- [ ] Question
- [ ] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug
Using the Java language, currently the function name is PredictTheWinner with first letter in **uppercase** instead of **lowercase** as it should be in Java according to the naming conventions.

#### Code you used for Submit/Run operation

```
// Predict the Winner
class Solution {
    public boolean PredictTheWinner(int[] nums) {
        
    }
}
```

#### Language used for code

Java

#### Expected behavior

The function name should be started with lowercase letter, like this: predictTheWinner

**Comment by ArielRotem1** [comment]
This syntax error should also be fixed in the editorial, in the solution explanation.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
