### ISSUE TITLE
Missing Test Case - 2215. Find the Difference of Two Arrays

### ISSUE THREAD

**Issue by CaptainLevi101** [LeetCode-Feedback/LeetCode-Feedback#15156]
[-80,-15,-81,-28,-61,63,14,-45,-35,-10]
[-1,-40,-44,41,10,-43,69,10,2]
displaying my answer wrong instead it is giving correct answer please correct it
My answer ->[[-80,-15,-81,-28,-61,63,14,-45,-35,-10],[-1,-40,-44,41,10,-43,69,10,2]]
console Ans->[[-81,-35,-10,-28,-61,-45,-15,14,-80,63],[-1,2,69,-40,41,10,-43,-44]]
and actually both are correct as i am free to display integers in any order

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
