### ISSUE TITLE
Missing Test Case - 48. Rotate Image

### ISSUE THREAD

**Issue by shu-vro** [LeetCode-Feedback/LeetCode-Feedback#15151]
#### Your LeetCode username
shu-vro

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I tried my code and it works well on my local environment (eg: laptop) but when I come to leetcode, it gives the exact output it got as input.

#### Code you used for Submit/Run operation

```javascript
// Rotate Image
function rotate(matrix=[]) {
  let result = []
  for (var i = 0; i < matrix.length; i++) {
    result.push([])
  }
  for (var i = 0; i < matrix.length; i++) {
    for (var j = 0; j < matrix.length; j++) {
      result[j][matrix.length-1-i]=matrix[i][j]
    }
  }
  return result
}
```

#### Language used for code
Javascript (JS)

#### Expected behavior

The output should be exactly like expected. Just like I tested on my laptop

#### Additional context

**Live prove**:Check out this pen (https://codepen.io/shu-vro/pen/oNQQGQY?editors=1111). My code works as expected in codepen.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us! Unfortunately, we are unable to troubleshoot the different behavior between your local IDE and the LeetCode environment.

For this issue, please raise this as a discuss post in the problem discuss section as other users may have run into the same issue and resolved it.

At LeetCode, we care about the whole learning experience that comes with each problem and we encourage users to teach and help each other to enrich their learning. In addition, we want our users to debug their code and learn from the process.

We appreciate your time and support.
