### ISSUE TITLE
Missing Test Case - 20. Valid Parentheses

### ISSUE THREAD

**Issue by vamsipavani** [LeetCode-Feedback/LeetCode-Feedback#1515]
#### Your LeetCode username

vamsi2921

#### Category of the bug
- [ ] Question
- [# ] Solution
- [ ] Language

#### Description of the bug

The test case of the solution is passing when using the run option but failing when submitting.

#### Code you used for Submit/Run operation

```
//Valid Parentheses Problem

import java.util.Hashtable;
import java.util.Stack;

public class Solution {
    static Hashtable<Character,Character> createBracketPair = new Hashtable<Character,Character>();
    static Stack brackets = new Stack();

    public static void CreateBrackets()
    {
        createBracketPair.put('}','{');
        createBracketPair.put(')','(');
        createBracketPair.put(']','[');

    }
    private static boolean isClosingBracket(char key)
    {
        return createBracketPair.containsKey(key);
    }
    private static boolean isMatchingLastBracket(char key)
    {
        if(brackets.peek()==createBracketPair.get(key))
        {
            brackets.pop();
            return true;
        }
        return  false;
    }
    private static boolean isValidOpeningBracket(char key)
    {
        return createBracketPair.containsValue(key);
    }

    public static boolean isValid(String bracketstring)
    {
        Solution.CreateBrackets();
        for(int i=0;i<bracketstring.length();i++)
        {
            char needle=bracketstring.charAt(i);
            if(Solution.isValidOpeningBracket(needle)){
                brackets.push(needle);
            }else{
                if(Solution.isClosingBracket(needle) )
                {
                    if(!Solution.isMatchingLastBracket(needle))
                    {
                        return  false;
                    }

                }
            }
        }
        if(brackets.isEmpty())
        {
            return  true;
        }else {
          return false;
        }
    }

}



```

#### Language used for code

Java

#### Expected behavior

The above code should pass for the custom test case "[{}]" but its failing during submission. When solution is ran using the custom testcase its passing. Please find the attached screenshot.

#### Screenshots

<img width="1108" alt="Screen Shot 2020-11-30 at 10 51 35 PM" src="https://user-images.githubusercontent.com/6346085/100699028-8cad2800-335f-11eb-8a0a-e7a3fd71a6ec.png">

**Comment by lc-kay** [comment]
Hi @vamsipavani 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
