### ISSUE TITLE
第34题、1337题中文题干信息错误

### ISSUE THREAD

**Issue by DetachmLiu** [LeetCode-Feedback/LeetCode-Feedback#1516]
** Bug 类型**
- [x] 题目

**描述**
第 34 题，题干最后的提示中，中文显示的**数据范围**与英文版**不一致**。
第 1337 题，题干和标题的**翻译有误**。将英文描述中的 matrix 直接翻译为方阵（square matrix），而题目原意想表示的以及数据测试均为矩阵，且数据范围的提示中也未提到 m == n。

**期望行为**
第34题修正题干描述。
第1337题修正翻译结果。

**屏幕截图**
34：
![fd1](https://user-images.githubusercontent.com/59466661/100704083-d2a9d080-33df-11eb-899e-8313229ff672.jpg)  
![fd2](https://user-images.githubusercontent.com/59466661/100704094-d89fb180-33df-11eb-8e8c-8c2c43e5d44e.jpg)  
1337：
![fd3](https://user-images.githubusercontent.com/59466661/100705242-d8a0b100-33e1-11eb-8217-afcbde05fb9f.jpg)
![fd4](https://user-images.githubusercontent.com/59466661/100705247-da6a7480-33e1-11eb-9995-c13bb87982ba.jpg)
![fd5](https://user-images.githubusercontent.com/59466661/100705356-07b72280-33e2-11eb-9689-86c0e41b2ba5.jpg)

**Comment by feiceh** [comment]
感谢反馈，当前题目描述已更新。
