### ISSUE TITLE
Missing Test Case - 178. Rank Scores

### ISSUE THREAD

**Issue by KomiljonDeveloper** [LeetCode-Feedback/LeetCode-Feedback#15166]
#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by pranshugupta54** [comment]
What's the missing test case?
