### ISSUE TITLE
Missing Test Case - 1274. Number of Ships in a Rectangle

### ISSUE THREAD

**Issue by iaygul** [LeetCode-Feedback/LeetCode-Feedback#1518]
https://leetcode.com/submissions/detail/426039265/
Accepted Solution fails for manual testcase : 
[]
[0,0]
[0,0]

where there are no ships and a single point sea.

**Comment by lc-kay** [comment]
Hi @iaygul 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @iaygul 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
