### ISSUE TITLE
Missing Test Case for Problem Max Consecutive Ones III

### ISSUE THREAD

**Issue by code2forever** [LeetCode-Feedback/LeetCode-Feedback#15185]
#### Your LeetCode username

agraharikalash

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [☑️] Missing Test Cases 

#### Description of the bug

Given problem does not contain a test case due to which wrong solutions are getting accepted. The test case and the solution which got accepted due to the absence of the test case are given below.

Test case :  nums = [1,0,0,0]
                  k = 2
                  Output by the leetcode (which is correct) : 3
                  Output by the solution (which got accepted) : 2

#### Code you used for Submit/Run operation

```
// Max Consecutive ones III

//Below is the code which gives the wrong solution for the above-mentioned test case but due to the absence of the test case it got accepted.

class Solution {
public:
//wrong code but got accepted.
    int longestOnes(vector<int>& arr, int k) {
        int n = arr.size();
        vector<int> pref(n , 0);
        pref[0] = (arr[0]==0?1:0);

        int totalzeroes = (arr[0]==0?1:0);
        
        for(int i=1 ; i<n ; i++){
            totalzeroes += (arr[i]==0?1:0);
            pref[i] = pref[i-1] + (arr[i]==0?1:0);
        }
        
        if(totalzeroes <= k)
            return n;

        int ans = 0;

        for(int i=0 ; i<n ; i++){
            int zeroes = pref[i];
            auto it = upper_bound(pref.begin() , pref.end() , zeroes+k);
            int ub = it-pref.begin();
            ans = max(ans , ub-i-1);
        }
        return ans;
    }
};

```

#### Language used for code

C++

#### Expected behavior

It is expected to not accept the solution as it fails for the given test case (which is missing). But rather than getting rejected it got accepted by the leetcode.

#### Screenshots

Screenshots that show the wrong output by the code on the missing test case.
![wrong_output_clip1](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/69723710/87d8a6b0-2865-4b8a-90d5-b892d2a23ffa)
![wrong_output_clip3](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/69723710/2dc85f5b-d6a4-4786-a612-dab6f7b470c5)

Screenshots that show the successful submission of the wrong code.
![submitted_clip1](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/69723710/2b9da0d4-645c-4903-9064-c4f40e74a48d)
![submitted_clip2](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/69723710/c1ecc86d-d21d-41f9-9582-eab56a9a3d8c)

#### Additional context

Nothing additional.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by code2forever** [comment]
Hey there,

Thanks for looking into this and replying.
Looking forward to your response.

Thanks

*Sent with Right Inbox <https://www.rightinbox.com/?utm_source=signature>*

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by code2forever** [comment]
Awesome, thanks!
Will let you know if I found any other feedback.

*Sent with Right Inbox <https://www.rightinbox.com/?utm_source=signature>*
