### ISSUE TITLE
Missing Test Case - 242. Valid Anagram

### ISSUE THREAD

**Issue by prabhatotato** [LeetCode-Feedback/LeetCode-Feedback#15180]
#### Category of the bug

- [ ] Missing Test Cases 

#### Description of the bug

The solution i came up with seems to have worked for all the current test cases, when it shouldnt work for all  posible test cases. one of them is :

s = "lbj"
t = "hie"

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool isAnagram(string s, string t) {
        int xor1=0;int sum1=1,xor2=0,sum2=1;
        for(int i=0;i<s.size();++i)
        {
            xor1^=s[i];
            sum1=((sum1%113) *(s[i]%113))%113;
        }
        
         for(int i=0;i<t.size();++i)
        {
            xor2^=t[i];
          sum2=((sum2%113) *(t[i]%113))%113;
        }
        
        if(sum1==sum2&& xor1==xor2)
            return true;
        return false;
        
        
    }
};
```

#### Language used for code
C++ 

#### Expected behavior

On submitting, the solution should not get accepted, it should give the "wrong answer message".

#### Screenshots

The above solution gets accepted:
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/99132923/7f2c4212-5135-4826-b19a-77ec8095c8c9)

Yet it fails for the custom input given above. it returns true for two strings that are clearly non anagram. Th is will be fixed if this test case is included. 
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/99132923/28305e41-d437-46b4-820d-fffc4870b053)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
