### ISSUE TITLE
Missing Test Case - 2800. Shortest String That Contains Three Strings

### ISSUE THREAD

**Issue by qingy2019** [LeetCode-Feedback/LeetCode-Feedback#15184]
#### Your LeetCode username

qingy2023

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets wrong answer on this test case
```
a = "abc"
b = "cafg"
c = "aaa"
```

#### Code you used for Submit/Run operation

```Kotlin
class Solution {
    fun minimumString(a: String, b: String, c: String): String {
        var strs = listOf(a, b, c)
        var min = "z".repeat(500)
        for (i in 0 ..2) {
            for (j in 0 ..2) {
                for (k in 0 .. 2) {
                    if (i == j || j == k || i == k) continue
                    var one = add(strs[i], strs[j])
                    var final = add(one, strs[k])
                if (final.length < min.length) min = final
                    if (min.length < final.length) continue
                    min = minOf(min, final)
                    var x = 0
                }
            }
        }
        return min
    }

    fun add(a: String, b: String): String {
        if (b.contains(a)) return b
        if (a.contains(b)) return a
        if (a == "cafg") return b
        var frontB = StringBuilder()
        var backA = StringBuilder()
        var start = 0
        for (i in 0 until minOf(a.length, b.length)) {
            frontB.append(b[i])
            backA.append(a[a.length - 1 - i])
            if (frontB.toString() == backA.toString().reversed()) {
                start = i + 1
            }
        }
        return a + (b.substring(start))
    }
}
```

#### Language used for code

Kotlin

#### Expected behavior

<img width="413" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/66195939/3874a59b-907e-4c99-8a6b-5106022f70b9">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by qingy2019** [comment]
@LC-Pam any updates?

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
