### ISSUE TITLE
Question - 1199. Minimum Time to Build Blocks

### ISSUE THREAD

**Issue by RohitSgh** [LeetCode-Feedback/LeetCode-Feedback#15187]
### Your LeetCode username
RohitSgh

### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

### Description of the bug

Ambiguity in **Hint** and **Related Topics**.

The [Hint](https://leetcode.com/problems/minimum-time-to-build-blocks/description/) mentions that 

> A greedy approach will not work as the examples show.

But Related Topics has tag of `Greedy`

### Expected behavior

There should be consistency in **Hint** and **Related Topics**

### Screenshots
> ![https://leetcode.com/problems/minimum-time-to-build-blocks/description/](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/81853910/156564b1-615c-4a14-bcde-223ee402aed9)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by RohitSgh** [comment]
Hi @LC-Pam.

The problem was in weekly premium, and many comments do agree that Hints are misleading

- [The first hint is "A greedy approach will not work as the examples show."...](https://leetcode.com/problems/minimum-time-to-build-blocks/description/comments/2040127)

- [Hint: A greedy approach will not work
Topic: Greedy
???](https://leetcode.com/problems/minimum-time-to-build-blocks/description/comments/2040442)
