### ISSUE TITLE
Broken submission - 621. Task Scheduler

### ISSUE THREAD

**Issue by aaronkh** [LeetCode-Feedback/LeetCode-Feedback#15195]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Code run through Leetcode differs from code run locally

#### Code you used for Submit/Run operation

```
class Solution:
    def leastInterval(self, tasks: List[str], n: int) -> int:
        heap = []
        count = {}
        for t in tasks: count[t] = count.get(t, 0) + 1
        for k, v in count.items():
            heapq.heappush(heap, [-v, k])

        cd = {}
        ret = 0
        while heap or cd:
            if ret in cd:
                heapq.heappush(heap, cd.pop(ret))
            print(heap, cd, ret)

            if heap:
                neg_count, task = heapq.heappop(heap)
                if neg_count + 1 <= 0:
                    cd[ret + n] = (neg_count + 1, task)
            ret += 1
        return ret
```

#### Language used for code

Python3

#### Expected behavior

Expected:    
For example test case ` ["A","A","A","B","B","B"], 2` run locally outputs 
```
[[-3, 'A'], [-3, 'B']] {} 0
[[-3, 'B']] {2: (-2, 'A')} 1
[(-2, 'A')] {3: (-2, 'B')} 2
[(-2, 'B')] {4: (-1, 'A')} 3
[(-1, 'A')] {5: (-1, 'B')} 4
[(-1, 'B')] {6: (0, 'A')} 5
[(0, 'A')] {7: (0, 'B')} 6
[(0, 'B')] {} 7
8
````

Actual: 
Infinitely loops with output:
```
[[-3, 'A'], [-3, 'B']] {} 0
[[-3, 'B']] {2: (-2, 'A')} 1
[(-2, 'A')] {3: (-2, 'B')} 2
[(-2, 'B')] {4: (-1, 'A')} 3
[(-1, 'A')] {5: (-1, 'B')} 4
[(-1, 'B')] {} 5
[[-3, 'A'], [-3, 'B']] {} 0
[[-3, 'B']] {0: (-2, 'A')} 1
[] {0: (-2, 'A'), 1: (-2, 'B')} 2
[] {0: (-2, 'A'), 1: (-2, 'B')} 3
[] {0: (-2, 'A'), 1: (-2, 'B')} 4
... (truncated)
```
Value `ret` is reset between the 6th and 7th iterations of the loop. This is also consistent when `ret` is initialized to a different value i.e. -2 will be reset to -2 between the 6th and 7th iterations.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us! Unfortunately, we are unable to troubleshoot the different behavior between your local IDE and the LeetCode environment.

For this issue, please raise this as a discuss post in the problem discuss section as other users may have run into the same issue and resolved it.

At LeetCode, we care about the whole learning experience that comes with each problem and we encourage users to teach and help each other to enrich their learning. In addition, we want our users to debug their code and learn from the process.

We appreciate your time and support.
