### ISSUE TITLE
196. Delete Duplicate Emails - Accepting the wrong testcase

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1519]
#### Your LeetCode username
[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Accepting the wrong test case-

![image](https://user-images.githubusercontent.com/71989691/100779427-64d8c580-342e-11eb-8fc3-38cebcf680ac.png)

#### Code you used for Submit/Run operation

```
# N/A
```

#### Language used for code

MySQL

#### Expected behavior

Should not accept the input with a duplicate primary key

### Submitting this as the wrong test case -
**{"headers": {"Person": ["Id", "Email"]}, "rows": {"Person": [[1, "john@example.com"], [2, "bob@example.com"], [1, "john@example.com"]]}}**

#### Additional context

Problem: https://leetcode.com/problems/delete-duplicate-emails/

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. We appreciate your support!
