### ISSUE TITLE
LeetCode(CN) 2688题 缺少关键测试用例

### ISSUE THREAD

**Issue by theslt** [LeetCode-Feedback/LeetCode-Feedback#15198]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
zilongv

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述**
该题目缺少关键测试用例，使得一些不正确的答案通过。应当增加一个user_id、item、created_at、amount均相同的多条测试记录。

**你使用的语言**
MySQL

**你提交或者运行的代码**
```mysql [u - 正确代码]
# 正确代码
# 情况一：当天买完东西后七天内（不包含当天）再次购物者
select
    u1.user_id
from users u1
    left join users u2 on u1.user_id = u2.user_id
where u1.created_at < u2.created_at
      and u1.created_at + interval 7 day  >= u2.created_at
union
# 情况二：当天购买两次用户者
select
    distinct user_id
from users
group by user_id, created_at
having count(*) >= 2
```
```mysql [u - 错误代码]
# 错误代码
SELECT DISTINCT u1.user_id
FROM Users u1 LEFT JOIN Users u2 ON u1.user_id = u2.user_id AND u1.created_at <= u2.created_at
WHERE ABS(TIMESTAMPDIFF(day, u1.created_at, u2.created_at)) <= 7 AND (u1.item != u2.item or u1.amount != u2.amount)
```

**期望行为**
错误代码不应该通过测试用例，因为题目描述也说了，表无主键，可能会重复。而错误代码使用了非唯一字段来进行区分显然是不正确的。

**屏幕截图**
无

**额外的上下文**
增加的测试用例：
| user_id | item              | created_at | amount |
| ------- | ----------------- | ---------- | ------ |
| 5       | Smart Crock Pot   | 2021-09-18 | 698882 |
| 6       | Smart Lock        | 2021-09-14 | 11487  |
| 6       | Smart Thermostat  | 2021-09-10 | 674762 |
| 8       | Smart Light Strip | 2021-09-29 | 630773 |
| 4       | Smart Cat Feeder  | 2021-09-02 | 693545 |
| 4       | Smart Cat Feeder  | 2021-09-02 | 693545 |

**Comment by feiceh** [comment]
感谢反馈，当前题目已更新，奖励已发放，请查收～
