### ISSUE TITLE
404 Missing Slides - System Design for Interviews and Beyond

### ISSUE THREAD

**Issue by 0xFonzy** [LeetCode-Feedback/LeetCode-Feedback#15190]
#### Your LeetCode username
alfonsoaranzazu

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] 404 Page

#### Description of the bug

404 page for slides on the System Design for Interviews and Beyond course.
Section: How to deliver data reliably.
Page: What else to know to build reliable, scalable, and fast systems.
Click on slides link and it takes you to 404 page.

#### Expected behavior

Clicking on the slides link should open the pdf in a new tab.
New tab opens a 404 Page instead.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/9100583/9ad62c53-3448-4dce-a6da-05f81303d2e1)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The page link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
