### ISSUE TITLE
Missing test Case #77. Combinations

### ISSUE THREAD

**Issue by LavkushS** [LeetCode-Feedback/LeetCode-Feedback#15199]
#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

Test case is missing in the question and this test case checks how optimal the code is 

TEST CASE- n=20, k=10
the numbers are well within the constraints 

#### Code you used for Submit/Run operation

'''
class Solution {
public:
    vector<vector<int>> ans;
    int solve(vector<vector<int>>& dp,vector<int>& vec,int k,int i,int mask,int cnt){
        int n=vec.size();
        if(dp[i][mask]!=-1)     return dp[i][mask];
        if(i==n){
            if(cnt==k){
                vector<int> temp;
                for(int shift=0;shift<n;shift++){
                    if(mask & (1<<shift)){
                        temp.push_back(shift+1);
                    }
                }
                ans.push_back(temp);
            }
            return dp[i][mask]=1;
        }
        
        //nottake 
        solve(dp,vec,k,i+1,mask,cnt);
        //take
        if(cnt<k){
            for(int shift=0;shift<n;shift++){
                if(!(mask & (1<<shift))){
                    solve(dp,vec,k,i+1,(mask | (1<<shift)),cnt+1);
                }
            }
        }
        return dp[i][mask]=1;
    }
    vector<vector<int>> combine(int n, int k) {
        vector<int> vec(n);
        for(int i=0;i<n;i++)    vec[i]=i+1;
        vector<vector<int>> dp(n+1,vector<int>(1<<n,-1));
        solve(dp,vec,k,0,0,0);
        return ans;
    }
};
'''

#### Language used for code

C++

#### Expected behavior

Should have given TLE on submission but the code attached above is an accepted code

**Comment by LavkushS** [comment]
PFA the link of the accepted solution [https://leetcode.com/problems/combinations/submissions/1009281417/](url)

**Comment by LavkushS** [comment]
PFA the link of the solution 
https://leetcode.com/problems/combinations/submissions/1009281417/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback. 

Please reply to this with your LCUS username. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by LavkushS** [comment]
My leetcode username is f20201709
