### ISSUE TITLE
Happy Number challenge issue!!

### ISSUE THREAD

**Issue by lakbham** [LeetCode-Feedback/LeetCode-Feedback#152]
I encountered a scenario wherein my code for 'Happy Number' challenge works for all test cases when I run it providing the test cases to run the code. but when I submit the same code, does not work for test case '6'.  I tried it on other IDE's too. It works fine but on Leetcode.com '30 day challenge' the submittal  does not work for test case '6'. I have copied the code below. It says 'wrong answer'. I have copied my code below, Please advise...…..
-------------------------------------------------------------------------------
class Solution {
     public static int ctr=0;
     public static int count=0;
    public static int ar1=0;
     public static  Boolean isHappy(int n)
    {
      if(n*n==1)
        return true;   
      String str=Integer.toString(n);
      System.out.println("String is  "+str);
      System.out.println("String  length: "+str.length());  
        ArrayList<String> list = new ArrayList<>(10);
     for(int i=0,j=1;j<=str.length();i++,j++)
     {
        String[] arr=new String[str.length()+1];
            System.out.print(i+"  "+j);
         arr[i]=str.substring(i,j);
        String a=arr[i];
         ar1=Integer.valueOf(a)*Integer.valueOf(a);
         ctr=ctr+ar1;
        System.out.println(" ctr is "+ ctr);
        if(ctr==1 && j==str.length())
         break;
        if(j==str.length())
         {
          str=Integer.toString(ctr);
        if(list.contains(str)==true)
        {
         return false;
         //break;
        }
         // ArrayList<String> list = new ArrayList<>(10);
          list.add(str);
          System.out.println(" Added list is "+ list);
          count=list.size();
        
         // str.contains(list);         
         System.out.println(" new str is "+ str);
         System.out.println("String  length now is: "+str.length()); 
        // String[] arr=new String[str.length()+1];
          i=-1;
          j=0;
          ctr=0;
          ar1=0;  
        }
        System.out.println(" ctr total is "+ ctr);
    }
        return true;
    }
    
  }
-----------------------------------------------------------------------------------------------

**Comment by CooperCooperCooper** [comment]
Hi @lakbham,
Thank you for reaching out to us. For test case "6", your "Run Code" and "Submit" have different outputs.

The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in this article: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-. Please check it out.
