### ISSUE TITLE
Missing Test Case - 1901. Find a Peak Element II

### ISSUE THREAD

**Issue by Richa812** [LeetCode-Feedback/LeetCode-Feedback#15203]
#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
The test cases do not take care of the condition when the number of rows is '1'

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<int> findPeakGrid(vector<vector<int>>& mat) {
        int m= mat.size();
     
        
        int low=0;
        int high=m-1;
        
        while(low<=high){
            int midRow= low+(high-low)/2;
            
            int rowMax= findMax(mat[midRow]);
           
            
            
            if(midRow==0 ){
                if(mat[midRow][rowMax] > mat[midRow+1][rowMax]){
                     return {midRow,rowMax};
                }
                
            }
            
            if(midRow==m-1 ){
                 if( mat[midRow][rowMax] > mat[midRow-1][rowMax]){
                     return {midRow,rowMax};
                }
            }
            
            if( mat[midRow][rowMax] > mat[midRow+1][rowMax] and  mat[midRow][rowMax] > mat[midRow-1][rowMax]){
               
                    return {midRow,rowMax};
            }
            
            
            if(  mat[midRow][rowMax] < mat[midRow+1][rowMax]){
               low=midRow+1;
              }
            
            else{
                  high=midRow-1;
            }
           
        }
        
        return {-1,-1};
        
        
        
    }
    
    int findMax(vector<int>row){
        int n=row.size();
        int ans=0;
     
        for(int i=1;i<n;i++){
            if(row[ans]<row[i]){
                ans=i;
              
            }
        }
        
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behaviour

My code above should fail for cases like 
[ [67] ] or [ [2,3,4,5] ]. But it actually passes all the leetcode test cases.

#### Screenshots

![Screenshot 2023-08-01 193542](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/58879930/bbb4114b-8532-4f69-be81-5edf0d52b279)
![Screenshot 2023-08-01 193602](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/58879930/5700ece4-7a55-417f-b298-a5c2e8b60bc8)
![Screenshot 2023-08-01 193612](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/58879930/7b61adc7-08af-4ae6-bb5b-a4ab8b6cdfd4)

whereas the same code shows an error in the editor when the test case [ [ 2,3,4,8] ] is passed :

![Screenshot 2023-08-01 194740](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/58879930/27c53d92-a5e0-423c-ac79-07b32edbf105)
![Screenshot 2023-08-01 194802](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/58879930/adba6b35-75b8-43e0-9213-8162d8877d59)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
