### ISSUE TITLE
"Run" and "Submit" produce different results/reports - 77. Combinations

### ISSUE THREAD

**Issue by svinkapeppa** [LeetCode-Feedback/LeetCode-Feedback#15201]
#### Your LeetCode username
erubanenko

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
I have two variants of my program, both of them are accepted by the judgement system, but one of them fails on custom input. The only difference (imho) is sorting at the end of the program, but it is stated that "You may return the answer in any order"

I can reproduce the problem consistently with custom inputs such as `n = 20, k = 10` or `n = 20, k = 11`
If this test case is first among my custom test cases, then it passes, but if it isn't -- it fails

#### Code you used for Submit/Run operation
Variant 1
```
class Solution:
    def combine(self, n: int, k: int) -> List[List[int]]:
        combinations = []
        stack = [[]]

        while len(stack) > 0:
            comb = stack.pop()
            if len(comb) == k:
                combinations.append(comb)
                continue
            back = 0 if len(comb) == 0 else comb[-1]
            if len(comb) < k and n - back >= k - len(comb):
                for i in range(back + 1, n - k + len(comb) + 2):
                    stack.append(comb + [i])

        return sorted(combinations)
```

Variant 2
```
class Solution:
    def combine(self, n: int, k: int) -> List[List[int]]:
        combinations = []
        stack = [[]]

        while len(stack) > 0:
            comb = stack.pop()
            if len(comb) == k:
                combinations.append(comb)
                continue
            back = 0 if len(comb) == 0 else comb[-1]
            if len(comb) < k and n - back >= k - len(comb):
                for i in range(back + 1, n - k + len(comb) + 2):
                    stack.append(comb + [i])

        return combinations
```

#### Language used for code
Python3

#### Expected behavior
As the only difference is the redundant sort at the end of the program, I expect both of them to pass my custom tests regardless of other tests

#### Screenshots
<img width="1439" alt="sorted_ok" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/22715919/7166625e-9927-4877-92c0-b43ea703224e">
<img width="1438" alt="unsorted_first_pos_ok" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/22715919/7ab786b1-5c51-4beb-98f6-500d41825699">
<img width="1436" alt="unsorted_fail" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/22715919/85c41b3b-56c7-42e8-992c-982e7c66b44f">

**Comment by LC-Pam** [comment]
![Screen Shot 2023-08-01 at 3 00 27 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/293ccc63-a298-4179-a141-4fdb38da67be)

**Comment by svinkapeppa** [comment]
@LC-Pam
Create two test cases, both with `n = 20, k = 10`?
Or via raw testcase editor?
```
20
10
20
10
```

**Comment by svinkapeppa** [comment]
@LC-Pam 
Video for better understanding the problem

https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/22715919/7f576ba3-fcc6-4bb1-9de3-8213eba3efc3

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
