### ISSUE TITLE
Missing Test Case - 73. Set Matrix Zeroes

### ISSUE THREAD

**Issue by Sudhanshu-21** [LeetCode-Feedback/LeetCode-Feedback#15207]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [**** ] Missing Test Cases 

#### Description of the bug

If we use -988 as one of the values which should not be changed to zero then we can treat it as a flag in our code

#### Code you used for Submit/Run operation

```
// Set Matrix Zeroes
class Solution {
public:
    

    void setRowZero(vector<vector<int>>&matrix, int m, int n, int i ){

        for (int j=0; j<n; j++){
            if(matrix[i][j]!=0){
                matrix[i][j]=-988;
            }
        }

    }
    void setColumnZero(vector<vector<int>>&matrix ,int m, int n, int j ){

        for (int i=0; i<m; i++){
            if(matrix[i][j]!=0){
                matrix[i][j]=-988;
            }
        }

    }

    void setZeroes(vector<vector<int>>& matrix) {


        int m = matrix.size();
        int n = matrix[0].size();

        for(int i=0; i<m; i++){
            for(int j=0; j<n; j++){

                if (matrix[i][j]==0){
                    setRowZero(matrix, m, n, i);
                    setColumnZero(matrix, m, n, j);
                }

            }
        }
        for(int i=0; i<m; i++){
            for(int j=0; j<n; j++){

                if (matrix[i][j]==-988){

                    matrix[i][j]=0;
                    
                }

            }
        }

       


        
    }
};
```

#### Expected behavior

I have used the following testcase
[[1,1,1],[1,0,1],[-988,1,1]]
The code doesn't passed this testcase as it was expected still while submitting it accepts my solution

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/77183130/12c1c92e-2c50-4da4-b533-1e636ca3e639)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
