### ISSUE TITLE
Problem 531 - missing edge case

### ISSUE THREAD

**Issue by bmiltz** [LeetCode-Feedback/LeetCode-Feedback#1520]
#### Your LeetCode username
<bmiltz>
bmiltz

#### Category of the bug
- [531] Question
- [] Solution
- [Python 3] Language

#### Description of the bug

The below code was accepted as a solution, but fails on the edge case:
[["W", "B", "W", "W"],["W", "B", "B", "W"],["W", "W", "W", "W"]]

#### Code you used for Submit/Run operation

```
class Solution:
    def findLonelyPixel(self, picture: List[List[str]]) -> int:
        num_rows = len(picture)
        num_cols = len(picture[0])
        visited_cols = [False] * num_cols
        res = 0
        for row in range(num_rows):
            gen_visited_cols = (i for i, v in enumerate(visited_cols) if not v)
            more_cols = True
            while more_cols:
                try:
                    check = 0
                    col = next(gen_visited_cols)
                    if picture[row][col] == 'B':
                        visited_cols[col] = True
                        for i in range(col + 1, num_cols):
                            if picture[row][i] == 'B':
                                check += 1
                                visited_cols[i] = True
                        for j in range(row + 1, num_rows):
                            if picture[j][col] == 'B':
                                check += 1
                        if check == 0:
                            res += 1
                except StopIteration:
                    more_cols = False                                
        return res
```

#### Language used for code

Python 3

#### Expected behavior

Should have failed problem but did not.

**Comment by lc-kay** [comment]
Hi @bmiltz 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @bmiltz 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
