### ISSUE TITLE
Wrong Test Case - 2361. Minimum Costs Using the Train Line

### ISSUE THREAD

**Issue by vijaysince89** [LeetCode-Feedback/LeetCode-Feedback#15216]
#### Your LeetCode username
vijaysince89

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [Y] Wrong Test Cases 

#### Description of the bug
The first Test case or **Example 1** result is wrong. The answer should be [1, 11, 14, 19]. But the answer that is getting accepted is [1, 7, 14, 19] which is in contradiction with the Explanation provided in the Example 1. Requesting you to fix it or let me know if I'm wrong.

#### Code you used for Submit/Run operation

```
// I did not submit any code yet. 
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by vijaysince89** [comment]
Thanks for the reply. My question is not about my code. My question is about the first example provided in the [2361. Minimum Costs Using the Train Line](https://leetcode.com/problems/minimum-costs-using-the-train-line/) **PLEASE FIND THE ATTACHED SCREEENSHOT FOR BETTER UNDERSTANDING OF MY [QUESTION.**] The correct output should be [1,11,14,19] as per the explanation.

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/13484262/4a55e7b0-2cb6-4fb2-b248-3e4fce349825)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
