### ISSUE TITLE
Missing Test Case - 802. Find Eventual Safe States

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#1521]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution is accepted but fails on the following test case:
[[1, 3, 4, 5], [], [], [], [], [2, 4]]

#### Code you used for Submit/Run operation

```
class Solution {
public List<Integer> eventualSafeNodes(int[][] graph) {
        List<Integer> result = new LinkedList<>();
        boolean[] safe = new boolean[graph.length];
        for (int i = 0; i < graph.length; i++) {
            if(dfs(i, graph, new boolean[graph.length], safe)) result.add(i);
        }

        return result;
    }

    private boolean dfs(int node, int[][] graph, boolean[] visited, boolean[] safe) {
        if(safe[node]) return true;

        if(visited[node])
            return false;
        else
            visited[node] = true;

        for(int i = 0; i < graph[node].length; i++) {
            if(!dfs(graph[node][i], graph, visited, safe))
                return false;
            else
                visited[i] = true;
        }

        safe[node] = true;
        return true;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/100811680-2846a300-3409-11eb-8b8e-4af71d3d15a6.png)
![image](https://user-images.githubusercontent.com/32546406/100811694-31d00b00-3409-11eb-9f56-f9275ba82f21.png)

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
