### ISSUE TITLE
Broken Problem: 89. Gray Code

### ISSUE THREAD

**Issue by projecteulerlover** [LeetCode-Feedback/LeetCode-Feedback#15214]
#### Your LeetCode username

changhsumath666

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<int> grayCode(int n) {
        vector<int> c = {0};
        for (int i=0; i<n; ++i) {
            int m = c.size();
            for (int j=m-1; j>=0; --j) c.push_back(c[j] + (1 << i));
        }
        return c;
    }
};
```

#### Expected behavior: Test runs

We get a runtime error:
```
SyntaxError: invalid syntax
                                    ^
    if len(arr) != sz or arr[0] != 0:
Line 11  (Solution.py)
```
Something is wrong here, as I am not running the solution in python. I get the same error trying to submit in every language, not just C++.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/25141218/4226cbe4-7b04-4b05-9ce1-325eba61f9b3)

**Comment by AbinashSamal828** [comment]
I faced the same issue today.

**Comment by AbinashSamal828** [comment]
@projecteulerlover its fixed today .You can close this issue now.
