### ISSUE TITLE
Mistake in Example-1 of "2781. Length of the Longest Valid Substring"

### ISSUE THREAD

**Issue by YogeshP93** [LeetCode-Feedback/LeetCode-Feedback#15222]
#### Your LeetCode username
https://leetcode.com/Baymax_/

#### Category of the bug
- [ X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the problem: "[2781. Length of the Longest Valid Substring](https://leetcode.com/problems/length-of-the-longest-valid-substring/)" **under Example-1's Explanation**, it is mentioned:
 _There are 9 valid substrings in word: "c", "b", "a", "ba", "aa", "bc", "baa", "aab", and "aabc"_. 

**_But there are 2 more valid substrings "ab" and "abc" which are left out/ not considered._**
As they are left out even when they are valid, it raises confusion as of why they are invalid

#### Screenshots

![Screenshot 2023-08-02 161339](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/122779284/b4ce2905-03bb-4b2e-95f3-8a566c980dd7)

**Comment by YogeshP93** [comment]
The above issue in with respect to the content/explanation only

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
