### ISSUE TITLE
Missing Test Case - 806. Number of Lines To Write String

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#1522]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution is accepted but fails on the following test case:

[3, 4, 10, 4, 8, 7, 3, 3, 4, 9, 8, 2, 9, 6, 2, 8, 4, 9, 9, 10, 2, 4, 9, 10, 8, 2]
"mqblbtpvicqhbrejb"

#### Code you used for Submit/Run operation

```
class Solution {
    public int[] numberOfLines(int[] widths, String S) {
        int[] res = new int[2];
        if(S.length() == 0)
            return res;
        int line = 1, cnt = 0,i = 0;
        while(i < S.length()){
            int curr = widths[S.charAt(i++) - 'a'];
            cnt += curr;
            if(cnt >= 100){
                if(cnt > 100)// if count is greater than 100, then current char needs to be added on next line so decrement i
                    --i;
                line++;
                cnt = 0;                
            }
        }
        res[0] = line;
        res[1] = cnt;
        return res;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/100816531-4b2a8480-3414-11eb-87e1-9e2bf12c8f91.png)
![image](https://user-images.githubusercontent.com/32546406/100816550-55e51980-3414-11eb-86e5-51427e71d03f.png)

**Comment by dungeonmastae** [comment]
please provide the question link

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
