### ISSUE TITLE
427. Construct Quad Tree: typo in description

### ISSUE THREAD

**Issue by nineonine** [LeetCode-Feedback/LeetCode-Feedback#15237]
username: [dnox](https://leetcode.com/dnox/)

https://leetcode.com/problems/construct-quad-tree

there is a typo in example 1 explanation section
`represnts`
should be
`represents`

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
