### ISSUE TITLE
Editorial video: bug in the solution - 289. Game of Life

### ISSUE THREAD

**Issue by vib-hu** [LeetCode-Feedback/LeetCode-Feedback#15230]
#### Your LeetCode username

vibhumishra808

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The solution given in the Editorial video is showing 
int right = Math.max(cols-1,col+1)
but this is causing ArrayIndexOutOfBoundsException.

#### Code you used for Submit/Run operation

```
// Game of Life
public void gameOfLife(int[][] board) {
        int[][] arr = new int[board.length][board[0].length];
        
        for(int row =0;row<board.length;row++){
            for(int col =0;col<board[0].length;col++){
                arr[row][col] = getBit(row, col, board);
            }
        }
         for(int row =0;row<board.length;row++){
            for(int col =0;col<board[0].length;col++){
                board[row][col] = arr[row][col];
            }
         }
    }

    private int getBit(int row, int col, int[][] board){
        int rows = board.length;
        int cols = board[0].length;
        int top = Math.max(0,row-1);
        int bottom = Math.min(rows-1,row+1);
        int left = Math.max(0,col-1);
        int right = Math.min(cols-1,col+1);
        int liveNeighbor =0;
        for(int i= top;i<=bottom;i++){
            for(int j= left;j<=right;j++){
                if(!(i==row && j==col) && board[i][j]==1){
                    liveNeighbor++;
                }
            }
        }

        if(liveNeighbor<2 ||liveNeighbor>3)
            return 0;
        else if(liveNeighbor == 3)
            return 1;
        else 
            return board[row][col];
    }
```

#### Expected behavior

It should be 
int right = Math.min(cols-1,col+1)

#### Screenshots

<img width="649" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/10459403/92963d4f-b808-46a9-9666-7b134843fc11">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've used your feedback to check the problem.

We redirected it to our content team and it will take time to fix.

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!
