### ISSUE TITLE
86-partition-list the test casa should be updated as per the question description

### ISSUE THREAD

**Issue by Kenzku** [LeetCode-Feedback/LeetCode-Feedback#15233]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

For this problem: https://leetcode.com/problems/partition-list/

The problem describes that
```text
You should preserve the original relative order of the nodes in each of the two partitions.
```
the `relative order` is vague and ambiguous.

in this test case: 96 / 168 testcases passed

```text
head=[1,4,3,0,2,5,2]
x=3

my output: [0,1,2,2,4,3,5]
expected:  [1,0,2,2,4,3,5]
```

My code might not be perfect, and may fail further tests, but at **this very test case**, 
my output also preserves the relative order, and shall be accepted

#### Code you used for Submit/Run operation

```
/**
 * Definition for singly-linked list.
 * function ListNode(val, next) {
 *     this.val = (val===undefined ? 0 : val)
 *     this.next = (next===undefined ? null : next)
 * }
 */
/**
 * @param {ListNode} head
 * @param {number} x
 * @return {ListNode}
 */
var partition = function(head, x) {
    let smallNodes = []
  let pre
  let curr = head;
  let metX = false
  // remove nodes with values less than x
  while (curr) {
    if (metX) {
      while (curr && curr.val < x) {
        smallNodes.push(curr.val)
        pre.next = curr.next
        curr = curr.next
      }
      pre = curr
    }
    if (!curr) {
      break;
    }
    if (curr.val === x) {
      metX = true
      pre = curr
    }
    curr = curr.next
  }

  // insert nodes before x
  let sentinel = new ListNode(0, head)
  pre = sentinel
  curr = sentinel.next
   
  while (smallNodes.length > 0 && curr) {
    
    if (curr.val > smallNodes[0]) {
      let newNode = new ListNode(smallNodes.shift(), curr)
     
      pre.next = newNode
      pre = newNode
    } else {
      pre = curr
      curr = curr.next
    }
  }
  
  return sentinel.next
};```

#### Language used for code
JS


#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->



#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->
<img width="682" alt="Screenshot 2023-08-02 at 23 35 22" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/1387249/1f7ceded-7f04-4c1f-9837-04e08be6665c">



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
