### ISSUE TITLE
Wrong Testcase in Longest Palindromic Subsequence

### ISSUE THREAD

**Issue by AlexMiller101** [LeetCode-Feedback/LeetCode-Feedback#15238]
#### Your LeetCode username

[alexluser101](https://leetcode.com/alexluser101/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

When I submit my code, One of the test case `s = aabaa` have a expected output of `5` when it should be `4`

#### Code you used for Submit/Run operation

```python

import re
class Solution:
    def longestPalindromeSubseq(self, s: str) -> int:
        ans = 0
        temp = ""
        current_ans = 0
        previous_ans = 0
        for i in s:
            if not temp == i:

                x = re.findall(i, s)
                current_ans = len(x)
                temp = i

                if previous_ans > current_ans:
                    ans = previous_ans
                else:
                    ans = current_ans
                previous_ans = current_ans
        return ans

```

#### Language used for code

_Python3_

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/61782680/79270d60-7fdb-42cf-9bc0-041ce5bc2ef2)

#### Additional context

This bug is caused by incorrect test case value. Changing the value from _5_ to _4_ will fix the problem

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
