### ISSUE TITLE
Missing Test Case - 50. Pow(x, n)

### ISSUE THREAD

**Issue by coldddeserted** [LeetCode-Feedback/LeetCode-Feedback#15245]
#### My LeetCode username
coldddeserted

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
When degree of -2147483648 my code is not work

#### Code you used for Submit/Run operation

```
// [Pow(x, n)](https://leetcode.com/problems/powx-n/)
class Solution {
    public static double myPow(double x, int n) {
        double answer = 1;

        if (n < 0) {
            x = 1 / x;
            n = -n;
        }

        double current_product = x;

        if (n > 0) {
            for (int i = 1; i < n; i++) {
                current_product *= x;
            }
            answer = current_product;
        }
        return answer;
    }
};
```

#### Language used for code
Java

#### Additional context

I don't understand where is the mistake

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
