### ISSUE TITLE
Misleading Content - Shortest Path Between Two Vertices - Breadth-First Search

### ISSUE THREAD

**Issue by themlkang** [LeetCode-Feedback/LeetCode-Feedback#15257]
#### Your LeetCode username
[themlkang](https://leetcode.com/themlkang/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

The video in the lesson explains how to use BFS to find the shortest path between two vertices. However, during the introduction, the commentator also adds, "But I will show you how to use BFS to find all paths". This is misleading because, the algorithm he gives doesn't find all paths. In the example he goes over later on in the video, [A, C, E, B] is a valid path that is not visited.

#### Expected behavior

Leave the language over "finding all paths" out. Or add some additional commentary to elaborate on the point, such as details of what what situations it will work for or a comparison to using DFS.

#### Screenshots

![Screen Shot 2023-08-03 at 12 44 36 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/1915730/300f1fa9-2d42-4d62-9215-6e2d0432543d)

#### Additional context

In the problem provided to practice the algorithm (https://leetcode.com/explore/learn/card/graph/620/breadth-first-search-in-graph/3853/). The algorithm cannot be used as-is to find all the paths. It only works on a DAG and by not checking for previously visited nodes.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The content is correct, “finding all path“ is followed by “finding the shortest path from them”.

In the reporter’s example: [ACEB] is not a valid path as the point F is the destination.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by themlkang** [comment]
@LC-Pam After reading your response, I maintain the position that the content is misleading. At :30 the content says "But I will show you how to use BFS to find all paths" and there is no follow up. At 5:49, the content tries to back this statement up by saying that the algorithm found all paths from A to F. This is true for this example, but only by coincidence.

BFS does not find all paths, even to a single destination. Say we use E as the destination instead of F. [ACE], [ADE], [ABE] would be found by the algorithm, but [ABEF] would not be found.

BFS finds the shortest path(s) but nothing more! BFS may find all paths, but only for DAGs, as show [here](https://leetcode.com/explore/learn/card/graph/620/breadth-first-search-in-graph/3854/)
