### ISSUE TITLE
Missing Test Case - 392. Is Subsequence

### ISSUE THREAD

**Issue by shfaizan** [LeetCode-Feedback/LeetCode-Feedback#15255]
#### Your LeetCode username

shfaizan

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

There are only two test cases and both of them are of same kind. if we add this test case where s = "aba" and t = "abba" it will give a deeper understanding of the problem as there are duplicates values that we need to handle.

#### Code you used for Submit/Run operation

```
class Solution:
    def isSubsequence(self, s: str, t: str) -> bool:
        i = 0
        j = 0

        while i < len(s) and j < len(t):
            if s[i] == t[j]:
                i+=1
            j += 1

        return i == len(s)
```

#### Language used for code

Python3

#### Expected behavior

if someone write a code that does not handle duplicate value it will show error in start

**Comment by LC-Pam** [comment]
![Screen Shot 2023-08-04 at 3 56 06 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/6dd8ac36-22e7-4746-80de-651cca433d79)

Thank you for your time. 

We've used your feedback to check the problem. 

The test case already exists.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
