### ISSUE TITLE
Missing Test Case - 853. Car Fleet

### ISSUE THREAD

**Issue by sidor123** [LeetCode-Feedback/LeetCode-Feedback#15250]
#### Your LeetCode username
sidor223

#### Category of the bug
- [[853. Car Fleet](https://leetcode.com/problems/car-fleet/)] Question
- [ ] Solution
- [English] Language
- [1] Missing Test Cases 

#### Description
My solution in pycharm returns me the correct answer (3), but leetcode shows me the other and wrong one (2).

#### Code you used for Submit/Run operation

```
class Solution(object):
    def carFleet(self, target, position, speed):
        cars = {}
        for x in range(len(position)):
            cars[position[x]] = speed[x]
        cars = dict(sorted(cars.items()))
        res = len(position)
        stack = collections.deque(list(cars.keys()))
        while len(stack) > 1:
            pos = stack.pop()
            uni_speed = cars[stack[-1]] - cars[pos]
            if uni_speed > 0:
                if ((pos - stack[-1]) / uni_speed) <= ((target - pos) / cars[pos]):
                    stack[-1] = pos
                    res -= 1
        return res
```

#### Language used for code
Python

#### Expected behavior
I expected leetcode 1st testcase to return me the answer "2", but it returned "3".

#### Screenshots
https://imgur.com/X08eRXu

**Comment by LC-Pam** [comment]
![Screen Shot 2023-08-04 at 3 52 08 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/d98102cf-4479-4aa1-aca6-3b5489362161)
