### ISSUE TITLE
Missing Test Case - 382. Linked List Random Node

### ISSUE THREAD

**Issue by leostd** [LeetCode-Feedback/LeetCode-Feedback#1525]
#### Your LeetCode username
leostd

#### Category of the bug
- [ ] Question
- [x] Solution
- [x] Language

#### Description of the bug
Questions said that it expects each node has same probability, which means a uniform integer probability distribution. However, when I use C++ uniform_int_distribution API it didn't pass the test cases. It did pass all the test cases when I used rand() instead. Here you may want to check the library documentation of both:

https://www.cplusplus.com/reference/cstdlib/rand/ -> Notice though that this modulo operation does not generate uniformly distributed random numbers in the span (since in most cases this operation makes lower numbers slightly more likely).

http://cplusplus.com/reference/random/uniform_int_distribution/

#### Code you used for Submit/Run operation
```
// Linked List Random Node
class Solution {
public:
    int n;
    ListNode *hd;
    uniform_int_distribution<int> distribution;
    default_random_engine generator;
    /** @param head The linked list's head.
        Note that the head is guaranteed to be not null, so it contains at least one node. */
    Solution(ListNode* head) {
        n = 0;
        ListNode *h = head;
        hd = head;
        while(h != nullptr) {
            n++;
            h = h->next;
        }
        
        distribution = uniform_int_distribution<int>(0,n);
    }
    
    /** Returns a random node's value. */
    int getRandom() {
        cout << n << endl;
        int rnd = distribution(generator);
        cout << rnd << endl;
        ListNode *ret = hd;
        for(int i = 1; i < rnd; i++) {
            ret = ret->next;
        }
        
        return ret->val;
    }
};
```

#### Language used for code
C++

#### Expected behavior
I expected it to pass test cases using uniform_int_generator

#### Screenshots
N/A

#### Additional context
N/A

**Comment by lc-kay** [comment]
Hi @leostd
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@leostd ``
class Solution {
private:
vector<int> vec, idx;

int get() {
    int ret = idx.back();
    idx.pop_back();
    return ret;
}
public:
Solution(ListNode* head) {
while (head) {
vec.push_back(head->val);
head = head->next;
}
random_device rd;
mt19937 gen(rd());
uniform_int_distribution<> dis(0, vec.size() - 1);

    for (int i = 0; i < 100000; ++i)
        idx.push_back(dis(gen));
}

int getRandom() {
    return vec[get()];
}
};
``

**Comment by lc-kay** [comment]
@leostd  Our team carefully reviewed your code and added a uniform_int_distribution that managed to AC the problem. Please refer to the code above. Thank you for your time!
