### ISSUE TITLE
52. N 皇后 II，关于答案判断的bug。

### ISSUE THREAD

**Issue by op15066212** [LeetCode-Feedback/LeetCode-Feedback#15259]
**你的 LeetCode 用户名**

[15066212pp](https://leetcode.cn/u/15066212pp/)

**Bug 类型**

- [x] 其他

**描述**

题目是52. N 皇后 II

https://leetcode.cn/problems/n-queens-ii/submissions/

我代码可以通过控制台的调试，我自己idea上调试也没问题，但是最终提交的时候过不了。

我和网友讨论了一下，大家都认为应该是题目答案判断的问题。

**你使用的语言**

java

**你提交或者运行的代码**

```
class Solution {
    static boolean[] row = new boolean[9];
    static boolean[] col = new boolean[9];
    static boolean[] t45 = new boolean[9];
    static boolean[] t135 = new boolean[9];
    static int x;

    public static int totalNQueens(int n) {
        row = new boolean[n];
        col = new boolean[n];
        t45 = new boolean[2 * n - 1];
        t135 = new boolean[2 * n - 1];
        return backTracking(n);
    }

    public static int backTracking(int n) {
        if (!next(n)) {
            return 1;
        }
        if (x == -1) {
            return 0;
        }
        int i = x;
        int res = 0;
        for (int j = 0; j < n; j++) {
            if (col[j] | t45[i + j] | t135[i - j + n - 1]) {
                continue;
            }
            row[i] = true;
            col[j] = true;
            t45[i + j] = true;
            t135[i - j + n - 1] = true;
            res += backTracking(n);
            row[i] = false;
            col[j] = false;
            t45[i + j] = false;
            t135[i - j + n - 1] = false;
        }
        return res;
    }

    public static boolean next(int n) {
        int cnt = 0;
        int min = 9;
        for (int k = 0; k < n; k++) {
            if (row[k]) {
                continue;
            }
            int sum = 0;
            for (int j = 0; j < n; j++) {
                if (col[j] | t45[k + j] | t135[k - j + n - 1]) {
                    continue;
                }
                sum++;
            }
            if (sum == 0) {
                x = -1;
                return true;
            }
            if (sum < min) {
                min = sum;
                x = k;
            }
            cnt++;
        }
        return cnt != 0;
    }
}
```

**期望行为**

希望官方修复一下这个bug

**屏幕截图**

<img width="960" alt="6cd108933c3eef3ae323679fd48d4d7c" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/108321891/4125359d-6a57-4dcc-95cb-d84d774ab35f">

**额外的上下文**

https://leetcode.cn/problems/n-queens-ii/solution/yun-xing-shi-jian-0ms-by-15066212pp-haw3/

我发现把我代码里的min改大一点就可以通过了，不过这应该不是我代码的问题，把min改大只是更加严谨。

<img width="960" alt="0699cafefc9538703206da95a5c60aba" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/108321891/ff99107e-bf8c-4c37-b882-93a14cc09847">

**Comment by feiceh** [comment]
你好，在与相关团队核实后：不作处理，用户代码问题，7、8、9 三个用例一起执行时，就会出现问题。
![img_v2_49ade282-b2da-41fb-a81e-7abb2d52a9dg](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/61722985/eaf8cd8f-8b1c-4bf5-b2ae-1da203f7520a)

**Comment by op15066212** [comment]
> 你好，在与相关团队核实后：不作处理，用户代码问题，7、8、9 三个用例一起执行时，就会出现问题。 ![img_v2_49ade282-b2da-41fb-a81e-7abb2d52a9dg](https://user-images.githubusercontent.com/61722985/258354635-eaf8cd8f-8b1c-4bf5-b2ae-1da203f7520a.jpg)

好吧，我好像犯了一个挺低级的错误，int类型的全局变量x没有重新初始化，感谢指出错误。
