### ISSUE TITLE
测试用例——2738. 统计文本中单词的出现次数

### ISSUE THREAD

**Issue by Echlorine** [LeetCode-Feedback/LeetCode-Feedback#15269]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
Cmite

**Bug 类型**
- [ ] 题目
- [ ] 缺少测试用例

**描述**
题目未明确处于每一行末尾的次或者用`,`等分隔符隔开的单词是否满足条件。

**你使用的语言**
MySQL

**你提交或者运行的代码**
```sql
# Write your MySQL query statement below
select 'bull' word, count(1) count from Files
where content REGEXP ' +bull[, \.\ ]'
union all
select 'bear' word, count(1) count from Files
where content REGEXP ' +bear[, \.\ ]'
;
```

**测试用例**
```json
{"headers":{"Files":["file_name","content"]},"rows":{"Files":[["draft1.txt","I have a bear, bull."],["draft2.txt","A bull bear."],["final.txt","The bull."]]}}
```

**期望行为**
描述你期望的结果

**屏幕截图**
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/41510511/d7aac8fd-2456-499f-960d-2d41bcc0058e)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，当前题目已更新，奖励已发放，请查收～
