### ISSUE TITLE
Seed for rand doesn't support solution 2 - 382. Linked List Random Node

### ISSUE THREAD

**Issue by rewolf** [LeetCode-Feedback/LeetCode-Feedback#1526]
#### Your LeetCode username
rewolf

#### Category of the bug
- [ ] Question
- [x] Solution
- [x] Language

#### Description of the bug
When doing proposed solution 2 using Reservoir Sampling in GoLang, the test cases don't work. I have a feeling that the test cases are made with the assumption of how the pseudorandom library is used in another language.
For GoLang I am getting different output to the expected.

#### Code you used for Submit/Run operation

```
/**
 * Definition for singly-linked list.
 * type ListNode struct {
 *     Val int
 *     Next *ListNode
 * }
 */
type Solution struct {
    head *ListNode
}

func Constructor(head *ListNode) Solution {
    return Solution{head}
}

func (this *Solution) GetRandom() int {
    n := 1
    winner := 0
    
    head := this.head
    
    for head != nil {
        if rand.Float32()    < 1.0 / float32(n) {
            winner = head.Val
        }
        
        n ++
        head = head.Next
    }
    return winner
}
```

#### Language used for code
Go

#### Expected behavior
I expect this to pass the test cases. However the expected results are different.

I'm assuming that the submission is tested by first seeding the random number generator.  But the seed is not leading the code to produce the same output.

#### Screenshots

![image](https://user-images.githubusercontent.com/201693/100879927-69b17e00-34ef-11eb-9623-d01ea66d2798.png)

I hope I am not missing something obvious and wasting your time.

**Comment by lc-kay** [comment]
Hi @rewolf 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@rewolf Our team has carefully reviewed your report and concluded that it is not supposed to show the same as the expected answer. We say that you can return 1, 2, or 3 but they should be returned with the same probability. Thank you for your time!
