### ISSUE TITLE
196. Delete Duplicate Emails - Incorrect output in console window

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1527]
#### Your LeetCode username
[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Console output is the same no matter whatever query I run. 

I tried with different queries.

**SELECT EMAIL FROM PERSON**
![image](https://user-images.githubusercontent.com/71989691/100888819-84c6c280-34dc-11eb-9e65-f8dfae32440a.png)
Expected
{"headers": ["Email"], "values": [["john@example.com"], ["bob@example.com"]]}

**SELECT ID FROM PERSON**
![image](https://user-images.githubusercontent.com/71989691/100889024-b50e6100-34dc-11eb-8949-7e8254dd92a3.png)
Expected
{"headers": ["Id"], "values": [[1], [2]]}
#### Code you used for Submit/Run operation

```
# N/A
```

#### Language used for code

MySQL

#### Expected behavior

Should print correct result on the console.

#### Additional context

Problem: https://leetcode.com/problems/delete-duplicate-emails/

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@pratap-082020 For this problem, the output is always the table Person so whatever you run, we show you, Person, after applying your query. Thank you for your time!

**Comment by pratap-082020** [comment]
Thanks
