### ISSUE TITLE
Rust uses and old release version on the LeetCode environment.

### ISSUE THREAD

**Issue by Murrelken** [LeetCode-Feedback/LeetCode-Feedback#15279]
#### Your LeetCode username
danilbutin

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description
The code compiles with errors due to using an old version of the language on the LeetCode environment. The actual error is on the screenshot below.

#### Code you used for Submit/Run operation
```
use std::collections::{HashSet, VecDeque};
use std::iter::FromIterator;

impl Solution {
    pub fn word_break(s: String, word_dict: Vec<String>) -> bool {
        let mut seen = vec![false; s.len() + 1];
        let hashset: HashSet<String> = HashSet::from_iter(word_dict);
        let mut queue = VecDeque::from([0usize]);

        loop {
            let Some(start) = queue.pop_front() else {
                break;
            };

            if start == s.len() {
                return true;
            }

            for end in start + 1..s.len() + 1 {
                if seen[end] {
                    continue;
                }

                if hashset.contains(&s[start..end]) {
                    seen[end] = true;
                    queue.push_back(end);
                }
            }
        }

        false
    }
}
```

#### Language used for code
Rust

#### Expected behavior
Code compiles. (It does with the latest stable version, which is 1.71.0 atm)

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/36051848/ddcec150-4c92-4d4d-a93c-cc41ad19b48e)

#### Additional context
According to https://support.leetcode.com/hc/en-us/articles/360011833974-What-are-the-environments-for-the-programming-languages-, Rust uses version 1.58.2 which I couldn't find here https://releases.rs/, but anyway, versions around 1.58.2 are already about a year and a half old. Are you considering updating it anytime soon?

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation during this moment.

We will update later. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
