### ISSUE TITLE
1625. Lexicographically Smallest String After Applying Operations - Typo

### ISSUE THREAD

**Issue by agrawalishaan** [LeetCode-Feedback/LeetCode-Feedback#15286]
#### Your LeetCode username
agrawalishaan

#### Category of the bug
- [ X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In Example 1 in the question, it states:
`There is no way to obtain a string that is lexicographically smaller then "2050".`

This is a typo, it should say `than` instead of `then`.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
