### ISSUE TITLE
Missing Test Case - 27. Remove Element

### ISSUE THREAD

**Issue by easkae** [LeetCode-Feedback/LeetCode-Feedback#15284]
#### Your LeetCode username
easkae

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
wrong test case.

#### Code you used for Submit/Run operation
```
//Remove Element
#include <algorithm>

using namespace std;

class Solution {
public:
    int removeElement(vector<int>& nums, int val) {
        int coincidences = count(nums.begin(), nums.end(), val);

        int result = coincidences;

        while (coincidences) {
            nums.erase(find(nums.begin(), nums.end(), val));
            coincidences--;
        }
        return result;
    }
};
```

#### Language used for code
C++

#### Expected behavior
Test case must complete because have expected values in list, but instead of this test case fails because he doesn't see part of list.
Checked that my list has all the required values by adding cout for each element and get it in the console.

#### Screenshots
screenshot with cout
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/97306651/2999fd9e-eaa0-4d8b-b3cb-a907eeedca70)
screenshot without cout
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/97306651/17b1dee3-fd9f-42d9-b20e-1c35329174f5)

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
