### ISSUE TITLE
219. Contains Duplicate II - Description

### ISSUE THREAD

**Issue by neeldoshii** [LeetCode-Feedback/LeetCode-Feedback#15287]
#### Your LeetCode username
@neeldoshii

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The Question is very unclear also in testcase there should be an Explanation to the answer.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
