### ISSUE TITLE
Implementation Comment Mixup - 4. Median of Two Sorted Arrays

### ISSUE THREAD

**Issue by johannes-holz** [LeetCode-Feedback/LeetCode-Feedback#15285]
#### Your LeetCode username

JHolz

#### Description of the bug

In the [Editorial ](https://leetcode.com/problems/median-of-two-sorted-arrays/editorial/) for `4. Median of Two Sorted Arrays`, Approach 2: The comments about what search window half will be discarded are mixed up in the Java and Python implementation:

```
// If k is in the right half of A + B, remove the larger right half.
if (aIndex + bIndex < k) { 
    if (aValue > bValue) {
        return solve(A, B, k, aStart, aEnd, bIndex + 1, bEnd);
    } else {
        return solve(A, B, k, aIndex + 1, aEnd, bStart, bEnd);
    }
}
// Otherwise, remove the smaller left half. 
else { 
    if (aValue > bValue) {
        return solve(A, B, k, aStart, aIndex - 1, bStart, bEnd);
    } else {
        return solve(A, B, k, aStart, aEnd, bStart, bIndex - 1);       
    }
}
```
```  
# If k is in the right half of A + B, remove the larger right half.
if a_index + b_index < k:
    if a_value > b_value:
        return solve(k, a_start, a_end, b_index + 1, b_end)
    else:
        return solve(k, a_index + 1, a_end, b_start, b_end)
# Otherwise, remove the smaller left half. 
else:
    if a_value > b_value:
        return solve(k, a_start, a_index - 1, b_start, b_end)
    else:
        return solve(k, a_start, a_end, b_start, b_index - 1)
```

As in the C++ implementation, the comments should state that if `k` is greater than the sum of our mid indices, the left half of the array with the smaller mid value gets discarded, and that otherwise the right half of the array with the greater mid value gets discarded.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
