### ISSUE TITLE
1179. Reformat Department Table - Accepting wrong test case - with duplicate Primary Key

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1528]
#### Your LeetCode username

[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

**Should not accept inputs with duplicate primary key-**

![image](https://user-images.githubusercontent.com/71989691/100893251-2a7c3080-34e1-11eb-8215-e7ce70b37fd9.png)

**AddressId is the primary key so the input should not take duplicate id's here-** 

{"headers": {"Person": ["PersonId", "LastName", "FirstName"], "Address": ["AddressId", "PersonId", "City", "State"]}, "rows": {"Person": [[1, "Wang2", "Allen2"]], "Address": [[1, 2, "New York City", "New York"],[1, 3, "New York City", "New York"]]}}
<hr/>

![image](https://user-images.githubusercontent.com/71989691/100893325-4384e180-34e1-11eb-830b-9715d9d86621.png)

**PersonId is the primary key so the input should not take duplicate id's here-** 

{"headers": {"Person": ["PersonId", "LastName", "FirstName"], "Address": ["AddressId", "PersonId", "City", "State"]}, "rows": {"Person": [[1, "Wang", "Allen"],[1, "Wang2", "Allen2"]], "Address": [[1, 2, "New York City", "New York"]]}}

#### Code you used for Submit/Run operation

```
# N/A
```

#### Language used for code

MySQL

#### Expected behavior

**Should not accept inputs with duplicate primary key**

### Contributing 2 test case - 

{"headers": {"Person": ["PersonId", "LastName", "FirstName"], "Address": ["AddressId", "PersonId", "City", "State"]}, "rows": {"Person": [[1, "Wang2", "Allen2"]], "Address": [[1, 2, "New York City", "New York"],[1, 3, "New York City", "New York"]]}}

{"headers": {"Person": ["PersonId", "LastName", "FirstName"], "Address": ["AddressId", "PersonId", "City", "State"]}, "rows": {"Person": [[1, "Wang", "Allen"],[1, "Wang2", "Allen2"]], "Address": [[1, 2, "New York City", "New York"]]}}

#### Additional context

Problem: https://leetcode.com/problems/reformat-department-table/

**Comment by lc-kay** [comment]
@pratap-082020 Can you please provide the accepted code that the test cases you are contributing failed on?

**Comment by pratap-082020** [comment]
**There is no contribution.** 
The problem should not accept the inputs with a duplicate primary key. 
Example-

**Input1:
Here duplicates ids are - [1, 2, "New York City", "New York"],[1, 3, "New York City", "New York"]**

{"headers": {"Person": ["PersonId", "LastName", "FirstName"], "Address": ["AddressId", "PersonId", "City", "State"]}, "rows": {"Person": [[1, "Wang2", "Allen2"]], "Address": [[1, 2, "New York City", "New York"],[1, 3, "New York City", "New York"]]}}

**Input2:**
**Here duplicate ids are: [1, "Wang", "Allen"],[1, "Wang2", "Allen2"]**

{"headers": {"Person": ["PersonId", "LastName", "FirstName"], "Address": ["AddressId", "PersonId", "City", "State"]}, "rows": {"Person": [[1, "Wang", "Allen"],[1, "Wang2", "Allen2"]], "Address": [[1, 2, "New York City", "New York"]]}}
 
But id is a primary key so the platform should not allow these kinds of inputs.

**Thanks.**

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@pratap-082020 Our team has carefully reviewed your report and noticed that the provided input already gets "Invalid input" when you try it with this problem. Thank you for your time!
