### ISSUE TITLE
Heap Videos Not Working

### ISSUE THREAD

**Issue by LeeMelzer** [LeetCode-Feedback/LeetCode-Feedback#15282]
#### Your LeetCode username

Lanky_

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The videos for heap insertion and deletion are not working.

#### Screenshots

![bandicam 2023-08-04 10-55-45-690](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/114274820/129ba2e3-4ba2-4764-9d3a-0e6a53e870f5)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The video working correctly on the website. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
![Screen Shot 2023-08-04 at 4 05 09 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/02c7a311-0878-4c81-b7a1-c8d4b2572a07)
![Screen Shot 2023-08-04 at 4 05 19 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/deb95449-76cd-4d54-93f3-e91e324544f1)
