### ISSUE TITLE
1179. Reformat Department Table - Problem description is incorrect

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1529]
#### Your LeetCode username

[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Mentioned in the problem - (id, month) is the **primary key** of this table.
If the id and month are the primary keys. Then the table Department should not contain duplicate values.

![image](https://user-images.githubusercontent.com/71989691/100896004-2ac9fb00-34e4-11eb-882d-dd04bddb43a5.png)

**Accepting the wrong test case -** 

{"headers":{"Department":["id","revenue","month"]},"rows":{"Department":[[1,8000,"Jan"],[1,9000,"Jan"],[3,10000,"Feb"],[1,7000,"Feb"],[1,6000,"Mar"]]}}

#### Code you used for Submit/Run operation

```
# N/A
```

#### Language used for code

N/A

#### Expected behavior

Update the description of the problem.

#### Additional context

Problem: https://leetcode.com/problems/reformat-department-table/

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@pratap-082020 Our team has reviewed your issue and ruled it invalid. The description is correct and the primary key is a composite key. Thank you for your time!
