### ISSUE TITLE
Missing Test Case - 1378. Replace Employee ID With The Unique Identifier

### ISSUE THREAD

**Issue by TejkiranV** [LeetCode-Feedback/LeetCode-Feedback#15296]
#### Your LeetCode username
tejkiran_v

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
This problem is missing a testcase where there could be extra `[id, unque_id]` entries in the **EmployeeUNI** while not having it in the corresponding id's in the **Employees** table.

Impact: **Hence, LEFT-JOIN should ONLY pass all the testcases, while an OUTER-JOIN must fail.**

#### Code you used for Submit/Run operation
```python
import pandas as pd

def replace_employee_id(employees: pd.DataFrame, employee_uni: pd.DataFrame) -> pd.DataFrame:

    df = pd.merge(employees,employee_uni, how='outer', on='id')
    return df[['unique_id', 'name']]

```

#### Language used for code
Python3 (Pandas)

#### Expected behavior
Ideally the extra row `|104   | null  |` should not be retrieved because only the employees from the **Employees** table are expected.

#### Screenshots
<img width="195" alt="Screenshot 2023-08-05 at 1 10 49 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/30775918/d7a2cf5a-2c04-44cf-bbfd-270bed2a0ad9">

#### Additional TestCase
Employees =
| id | name     |
| -- | -------- |
| 1  | Alice    |
| 7  | Bob      |
| 11 | Meir     |
| 90 | Winston  |
| 3  | Jonathan |

EmployeeUNI =
| id | unique_id |
| -- | --------- |
| 3  | 101       |
| 11 | 102       |
| 90 | 103       |
| 10 | 104       |

Please let me know if you need any further details.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The test case in JSON format: {"headers":{"Employees":["id","name"],"EmployeeUNI":["id","unique_id"]},"rows":{"Employees":[[1,"Alice"],[7,"Bob"],[11,"Meir"],[90,"Winston"],[3,"Jonathan"]],"EmployeeUNI":[[3,1],[11,2],[90,3]]}}

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by TejkiranV** [comment]
Here is a testcase in JSON format (which fails the judge):
`{"headers":{"Employees":["id","name"],"EmployeeUNI":["id","unique_id"]},"rows":{"Employees":[[1,"Alice"],[7,"Bob"],[11,"Meir"],[90,"Winston"],[3,"Jonathan"]],"EmployeeUNI":[[3,101],[11,102],[90,103],[10,104]]}}`

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
