### ISSUE TITLE
[LC-253] Meeting Room II solution not able to be compiled because class not found

### ISSUE THREAD

**Issue by JinZhenlin** [LeetCode-Feedback/LeetCode-Feedback#153]
**What kind of the bug**
- [X] problem
- [ ] solution
- [ ] language

**Describe the bug**
It's complaining class not found because name Interval not being resolved. However, Interval class was already defined in definition and problem statement. 

**what language is your code written in**
Java 1.8

**The code you submit/run**
```
// 253. Meeting Rooms II
class Solution {

public int minMeetingRooms(Interval[] intervals) {
if(intervals == null || intervals.length == 0){
return 0;
}
Arrays.sort(intervals, (a, b) -> a.start - b.start);
PriorityQueue<Interval> minHeap = new PriorityQueue<Interval>(intervals.length, new Comparator<Interval>() {
public int compare(Interval a, Interval b) { return a.end - b.end; }
});
minHeap.add(intervals[0]);

for(int i = 1; i < intervals.length; i++){
Interval cur = intervals[i];
Interval earliest = minHeap.remove();
if(cur.start >= earliest.end){
earliest.end = cur.end;
} else{
minHeap.add(cur);
}

minHeap.add(earliest);
}
return minHeap.size();
}
}
```

**Expected behavior**
The solution should pass, as I was directly modifying someone else's that passed. 

**Screenshots**
Screenshot as following:
[https://ibb.co/nRgZWbC](url)

**Additional context**

**Comment by CooperCooperCooper** [comment]
Hi @JinZhenlin,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @JinZhenlin,
Thank you for your time. Input types have been changed on April 15, 2019. Please reset to the default code definition to get a new method signature. We've also updated the problem with this notice.
