### ISSUE TITLE
Bug in Test Case - 8. String to Integer (atoi)

### ISSUE THREAD

**Issue by SaloniJain24** [LeetCode-Feedback/LeetCode-Feedback#15302]
#### Your LeetCode username
salonijain24

#### Category of the bug
- 8. String to Integer (atoi)](https://leetcode.com/problems/string-to-integer-atoi/)
- Solution
- C++
- Bug in test case:

#### Description of the bug

s ="     +004500"
When I print s[i] for 2nd zero in string, it prints [] and give its ascii value as 0.
i.e., it's a null character. 
But output is not zero if it is a null character. Output is 4500 i.e, you have taken 2nd zero as zero.

#### Code you used for Submit/Run operation

```
//String to Integer (atoi)
class Solution {
public:
    int myAtoi(string s) {
        int i=0, n=s.length();
        long digits=0;
        
        while(i<n && s[i]==' '){
            i++;
        }
        
       int sign= 1;
       s= s.substr(i);
        if(s[0]=='-'){
            sign = -1;
            i++;
        }
        else if(s[0]=='+'){
            sign = +1;
            i++;
        }
        
        while(i<n){
            // if(!(s[i]>='0' && s[i]<='9')){
            //     break;
            // }
            if(!isdigit(s[i])){
                cout<<s[i]<<" "<<(int)s[i]<<endl;
                break;
            }
            
             int ch= s[i]-'0';
            digits= digits*10 + ch;
           cout<<s[i]<<" "<<(int)s[i]<<endl;

            if(sign==-1 && -digits<=INT_MIN){
                return INT_MIN;
            }
            else if(sign==1 && digits>=INT_MAX){
                return INT_MAX;
            }

            i++;
        }

        return sign*digits;
        
    }
};
```

#### Language used for code

C++

#### Expected behavior

If it is zero, then give output as 4500.
But 2nd zero is a null char, then expected output would be 0.

#### Screenshots

![Screenshot 2023-08-05 145619](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/75930918/5fee4707-6f6e-4747-acf1-713052b31369)

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
