### ISSUE TITLE
627. Swap Salary -  Accepting incorrect inputs

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1530]
#### Your LeetCode username

[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The problem is accepting incorrect inputs:

**Taking the wrong input**
{"headers":{"salary":["id","name","sex","salary"]},"rows":{"salary":[[1,1,1,2500]]}}
![image](https://user-images.githubusercontent.com/71989691/100911264-00346e00-34f5-11eb-8f9d-53573620bd88.png)

**Your input**
{"headers":{"salary":["id","name","sex","salary"]},"rows":{"salary":[[1,null,null,2500]]}}
**Expected**
{"headers": ["id", "name", "sex", "salary"], "values": [[1, null, "m", 2500]]}
![image](https://user-images.githubusercontent.com/71989691/100911537-61f4d800-34f5-11eb-9f02-e91f7410188d.png)

#### Code you used for Submit/Run operation

```
# N/A
```

#### Language used for code

MySQL

#### Expected behavior

Should not accept incorrect inputs

### Contributing test case - 
{"headers":{"salary":["id","name","sex","salary"]},"rows":{"salary":[[1,null,null,2500]]}}

#### Additional context

Problem: https://leetcode.com/problems/swap-salary/

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
