### ISSUE TITLE
Missing Test Case - 607. Sales Person

### ISSUE THREAD

**Issue by TejkiranV** [LeetCode-Feedback/LeetCode-Feedback#15305]
#### Your LeetCode username
tejkiran_v

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
This problem is missing a testcase where the company's `name` could be having the word `RED` as a substring in `TIRED` which should not be treated as the company `RED` itself.

Impact: **Hence, The companies having the `name` **TIRED** or **REDEX** should be treated as harmless and the sales associated with those companies should be retrieved in the output.**

#### Code you used for Submit/Run operation
```python
import pandas as pd

def sales_person(sales_person: pd.DataFrame, company: pd.DataFrame, orders: pd.DataFrame) -> pd.DataFrame:

    ans_df = pd.merge(
        sales_person[["sales_id", "name"]],
        orders[["sales_id", "com_id"]],
        on="sales_id",
        how="left"
    ).fillna(0)

    ans_df = pd.merge(
        ans_df,
        company.rename(columns={"name": "company"}),
        on="com_id",
        how="left"
    ).fillna(" ")\
    .groupby("name", as_index=False)\
    .agg(company_names=("company", lambda x: " ".join(x)))\
    
    return ans_df[~ans_df["company_names"].str.contains("RED")][["name"]]  # Should ideally be `.contains(r"\bRED\b")`

```

#### Language used for code
Python3 (Pandas)

#### Expected behavior
Ideally extra rows `| John  |` and `| Pam |`should  be retrieved because those salespersons did not have any orders related to the company with the name "RED".

#### Screenshots
![Screenshot 2023-08-05 at 3 41 50 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/30775918/16c53365-fbf1-4c2c-9d8c-38a934bdc537)
Note: Since the order of output does not matter, the order in which "Alex" was retrieved can be ignored.

#### Additional TestCase:
SalesPerson =
| sales_id | name | salary | commission_rate | hire_date  |
| -------- | ---- | ------ | --------------- | ---------- |
| 1        | John | 100000 | 6               | 4/1/2006   |
| 2        | Amy  | 12000  | 5               | 5/1/2010   |
| 3        | Mark | 65000  | 12              | 12/25/2008 |
| 4        | Pam  | 25000  | 25              | 1/1/2005   |
| 5        | Alex | 5000   | 10              | 2/3/2007   |

Company =
| com_id | name   | city     |
| ------ | ------ | -------- |
| 1      | TIRED  | Boston   |
| 2      | ORANGE | New York |
| 3      | YELLOW | Boston   |
| 4      | GREEN  | Austin   |

Orders =
| order_id | order_date | com_id | sales_id | amount |
| -------- | ---------- | ------ | -------- | ------ |
| 1        | 1/1/2014   | 3      | 4        | 10000  |
| 2        | 2/1/2014   | 4      | 5        | 5000   |
| 3        | 3/1/2014   | 1      | 1        | 50000  |
| 4        | 4/1/2014   | 1      | 4        | 25000  |

Please let me know if you need any further details.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The test case in JSON format:  {"headers": {"SalesPerson": ["sales_id", "name", "salary", "commission_rate","hire_date"], "Company": ["com_id", "name","city"],"Orders":["order_id","order_date","com_id","sales_id","amount"]}, "rows": {"SalesPerson": [[1, "John", 100000, 6, "4/1/2006"], [2, "Amy", 12000, 5,"5/1/2010"], [3, "Mark", 65000, 12, "12/25/2008"], [4, "Pam", 25000, 25,"1/1/2005"],[5,"Alex",5000,10,"2/3/2007"]], "Company": [[1, "RED","Boston"], [2, "ORANGE", "New York"],[3, "YELLOW", "Boston"],[4, "GREEN", "Austin"]],"Orders":[[1,"1/1/2014",3,4,10000],[2, "2/1/2014", 4, 5, 5000],[3, "3/1/2014", 1, 1, 50000],[4, "4/1/2014", 1, 4, 25000]]}}

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by TejkiranV** [comment]
Here is a testcase in JSON format (which fails the judge):
 ```json
{"headers": {"SalesPerson": ["sales_id", "name", "salary", "commission_rate","hire_date"], "Company": ["com_id", "name","city"],"Orders":["order_id","order_date","com_id","sales_id","amount"]}, "rows": {"SalesPerson": [[1, "John", 100000, 6, "4/1/2006"], [2, "Amy", 12000, 5,"5/1/2010"], [3, "Mark", 65000, 12, "12/25/2008"], [4, "Pam", 25000, 25,"1/1/2005"],[5,"Alex",5000,10,"2/3/2007"]], "Company": [[1, "TIRED","Boston"], [2, "ORANGE", "New York"],[3, "YELLOW", "Boston"],[4, "GREEN", "Austin"]],"Orders":[[1,"1/1/2014",3,4,10000],[2, "2/1/2014", 4, 5, 5000],[3, "3/1/2014", 1, 1, 50000],[4, "4/1/2014", 1, 4, 25000]]}}

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
