### ISSUE TITLE
Missing Test Case - 146. LRU Cache

### ISSUE THREAD

**Issue by ddubrava** [LeetCode-Feedback/LeetCode-Feedback#15312]
#### Your LeetCode username
ddubrava

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I wouldn't say it's a bug; it's more of a small improvement. If you define `DoublyLinkedList` in this way:

```js
class DoublyListNode {
    constructor(key, val, prev, next) {
        this.key = key || null;
        this.val = val || null;
        this.prev = prev || null;
        this.next = next || null;
    }
}
```

you might face an issue when the key is 0, it will be null. And there is the test case with key equals 0 on LeetCode, but it is the last one (22/23) with thousands of calls. And you can't easily debug it, as you can't see where it fails.

#### Code you used for Submit/Run operation

```js
// LRU Cache
class DoublyListNode {
    constructor(key, val, prev, next) {
        this.key = key || null;
        this.val = val || null;
        this.prev = prev || null;
        this.next = next || null;
    }
}

// where key is 0 => key = null => you can't delete it later
node = new DoublyListNode(key, value); 
```

#### Language used for code
JavaScript

#### Expected behavior

Adding this test case will make it easier for everyone to catch such bugs

```
["LRUCache","put","put","put","get"]
[[2],[0,1],[2,2],[3,2],[0]]

Expected
[null,null,null,null,-1]
```

#### Screenshots

Debug, ye?

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/22116465/e98c3021-d376-46f4-95f2-114269f51a9a)

#### Additional context

By the way, when there are thousands of calls in a test case, the UI becomes very slow and laggy

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by ddubrava** [comment]
> Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
> 
> The code submission Accepted link.
> 
> We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

Hi! I'm sorry, I thought you do not need links since it's self-explanatory. I mean everything works as expected, but it's just a little bit hard to understand why it fails on the last test case.

The failed submission, where you can't figure out why it's failed - https://leetcode.com/problems/lru-cache/submissions/1012793633/

The successful submission - https://leetcode.com/problems/lru-cache/submissions/1012812037/

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
