### ISSUE TITLE
Missing Test Case - 91. Decode Ways

### ISSUE THREAD

**Issue by jlbouchot** [LeetCode-Feedback/LeetCode-Feedback#1531]
#### Your LeetCode username

jlbouchot

#### Category of the bug
- [ x ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The input 
"00000001203456789" which can be interpreted as "1", "20", "3", "4", "5", "6", "7", "8", "9" should not return 0 possibility (1 I believe)

#### Screenshots

![image](https://user-images.githubusercontent.com/5090851/100911868-aec1ba00-34c7-11eb-971e-bcbae8f0562e.png)
(obviously mine is wrong too :) )

**Comment by lc-kay** [comment]
@jlbouchot Can you please submit the accepted code that this test case failed on? Thank you!

**Comment by jlbouchot** [comment]
I haven't submitted my final code for this. But the "Expected" is wrong, I believe.

**Comment by lc-kay** [comment]
@jlbouchot Our team has checked the expected values and it is correct. I'd recommend checking out the discuss page for this problem to seek an explanation of test cases from our LeetCode community. https://leetcode.com/problems/decode-ways/discuss/
