### ISSUE TITLE
Language - 470. Implement Rand10() Using Rand7()

### ISSUE THREAD

**Issue by walter-cf-chuang** [LeetCode-Feedback/LeetCode-Feedback#15316]
#### Your LeetCode username

walterChuang

#### Category of the bug
- [ ] Question
- [ ] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug

When the test case is `10009`, the output array contains invalid value `80112` that is impossibly generated by the submitted code.

#### Code you used for Submit/Run operation

```
class Solution : SolBase {

    func rand10() -> Int {

        while true {
            let row = rand7()
            let col = rand7()
            let index = (row - 1) * 7 + col
            if index <= 40 {
                return 1 + (index - 1) % 10
            }
        }

        return 0
    }
}
```

#### Language used for code

Swift

#### Expected behavior

When the test case is `10009`, the output array should only contains numbers in the range of [1, 10].

#### Screenshots

![leetcode_console_output](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/19414925/f369f380-6292-4ec4-b362-e26ce921225b)
![output_array_in_editor](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/19414925/280d0fdf-d8aa-40a3-8595-f48bf313b1a5)

The last element of the output array is always `80112` every time I run the code. The rest of the elements are in the range of [1, 10] as generated by the code randomly.

#### Additional context

The submitted code is from Editorial. I also tried others' solutions but still got the same bug (i.e. got `80112` in the output array).

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team

**Comment by walter-cf-chuang** [comment]
@LC-Pam  The code is from Editorial. If there is problem with the correctness of the submitted code, then it may also be related to the solution in Editorial.

In addition, when the test case is `10009`, it means the code judge has executed the code for `10009` times to collect output in an array. The first 10008 elements are within the correct [1, 10] range. Only the last one is not. I cannot understand how your comment explains why the submitted code runs correctly for the first 10008 times but only the last time is incorrect.

Also tried test cases `10008` and `10010`. Those two are passed. Not sure why only `10009` cannot pass.
