### ISSUE TITLE
89. Gray Code || Wrong checking

### ISSUE THREAD

**Issue by Chinmay1232** [LeetCode-Feedback/LeetCode-Feedback#15321]
#### Your LeetCode username
Nuagen

#### Category of the bug

- Wrong Evaluation

#### Description of the bug

The question clearly sates that numbers should be distinct but a solution with alternate zeroes and ones e.g.[0,1,0,1..] also gets accepted

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<int> grayCode(int n) {
        vector<int> ans((1<<n));

        for(int i = 1; i < (1<<n); i++)
        {
            ans[i] ^= (1^ans[i-1]);
        }

        return ans;

    }
};
```

#### Language used for code
C++

#### Expected behavior

Outcome should be a wrong answer

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
