### ISSUE TITLE
Missing Test Case - 67. Add Binary

### ISSUE THREAD

**Issue by sober-Sherlock** [LeetCode-Feedback/LeetCode-Feedback#15327]
#### Your LeetCode username

海风吹过的夏天

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

有点找茬的意味，可以不用理会，不好意思哈，题目提示中，如果字符串不是''0''，则不含前导0，所以以为字符串为"0"，可以含有前导0，然后输入了这样的测试样例，提示含有前导0错误。因为字符串"0"含前导0，某些实现方式在设计时还得添加剔除多余前导0，才能通过测试样例。例如a = "000000", b = "1111"。

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/59591453/f2d3f055-a87f-49d6-ac71-092e37c29281)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/59591453/292a7b68-ec28-45bd-91e9-9cabc728ebe3)

**Comment by feiceh** [comment]
你好，在与相关团队核实后：不处理， 提示中写“字符串” 而非 “值”。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
