### ISSUE TITLE
Missing testcase in "Build an Array With Stack Operations" problem

### ISSUE THREAD

**Issue by EshwarMuthu** [LeetCode-Feedback/LeetCode-Feedback#1533]
#### Your LeetCode username
 
Eshwar_muthu

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

While solving the question titled "Build an Array With Stack Operations", I gave a testcase of my choice and it showed me as wrong answer. I am sure that this is a valid testcase. But when I submitted it, it was successful. Please refer the video that I have attached for the testcase that I provided. The video  can be found in the zip folder. I felt really annoyed at that moment. So just thought of sharing.

#### Code you used for Submit/Run operation

```
// Build an Array With Stack Operations
class Solution {
    public List<String> buildArray(int[] target, int n) {
        ArrayList<String> result=new ArrayList<>();
        int index=0;
        for(int i=1;i<=n;i++){
            if(index>=target.length) return result;
            if(target[index]==i){
                result.add("Push");
                index++;
            }else{
                result.add("Push");
                result.add("Pop");
            }
        }
        for(String s:result){
            System.out.println(s);
        }
        return result;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Expected to fail when clicking submit button because a testcase of my choice failed. But it accepted my submission. I am sure that this is a valid testcase. Please refer the video that I have attached to know the testcase. The video  can be found in the zip folder.

#### Screenshots

[leetcode-bug.zip](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/5631182/leetcode-bug.zip)

**Comment by lc-kay** [comment]
@EshwarMuthu When I attempted to reproduce the issue, the code you have provided was not accepted. Do you have an updated code that is accepted and fails on the custom test case? I will reopen this issue then. Thank you for understanding. 
<img width="1435" alt="Screen Shot 2020-12-04 at 3 15 42 PM" src="https://user-images.githubusercontent.com/70870126/101224486-97a7d700-3643-11eb-87e3-8d5236082d5d.png">
