### ISSUE TITLE
620. Not Boring Movies - Incomplete description and also accepting wrong input

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1534]
#### Your LeetCode username

[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

**Incomplete description
Pratically rating can never be negative so 0<=ranting< 10**
![image](https://user-images.githubusercontent.com/71989691/100913179-6fab5d00-34f7-11eb-964c-48052299f19a.png)

**Accepting wrong inputs**
![image](https://user-images.githubusercontent.com/71989691/100914144-acc41f00-34f8-11eb-9851-f6562d6c9481.png)

**Practically rating can never be negative but here accepting negative value in rating**
![image](https://user-images.githubusercontent.com/71989691/100914433-0f1d1f80-34f9-11eb-9ac6-9b8abf62b544.png)

#### Code you used for Submit/Run operation

```
# N/A
```

#### Language used for code

MsSQL

#### Expected behavior

Should take correct inputs

#### Additional context

Problem: https://leetcode.com/problems/not-boring-movies/

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
