### ISSUE TITLE
Typo in - 920. Number of Music Playlists

### ISSUE THREAD

**Issue by KrishChopra22** [LeetCode-Feedback/LeetCode-Feedback#15342]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

There's just a typo in the editorial of the problem [920. Number of Music Playlists](https://leetcode.com/problems/number-of-music-playlists/)
Simply fix the spelling of **Transtions -> Transitions**

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/77012237/8bac3cba-6225-4d51-b392-0ad9b115f32b)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
