### ISSUE TITLE
Missing Test Case - 2812. Find the Safest Path in a Grid

### ISSUE THREAD

**Issue by DmitryAk** [LeetCode-Feedback/LeetCode-Feedback#15345]
#### Your LeetCode username
dm_a

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The submission (https://leetcode.com/problems/find-the-safest-path-in-a-grid/submissions/1013664414/) was accepted, but it is not passing the test case below ([missing_testcase_2812.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/12268973/missing_testcase_2812.txt)).

#### Code you used for Submit/Run operation

```
class Solution {
public:
bool can(const vector<vector<int>>& grid, int row, int col, int m, set<pair<int, int>>& v, const vector<pair<int, int>>& thieves) {
    const int n = grid.size();
    if (row < 0 || row >= n || col < 0 || col >= n || !v.insert({row, col}).second) {
        return false;
    }
    for (auto [r, c] : thieves) {
        if (abs(r - row) + abs(c - col) < m) {
            return false;
        }
    }
    
    if (row == n - 1 && col == n - 1) {
        return true;
    }

    return 
    can(grid, row + 1, col, m, v, thieves) || 
    can(grid, row - 1, col, m, v, thieves) || 
    can(grid, row, col + 1, m, v, thieves) || 
    can(grid, row, col - 1, m, v, thieves);
}
int maximumSafenessFactor(const vector<vector<int>>& grid) {
    const int n = grid.size();
    vector<pair<int, int>> thieves;
    for (int row = 0; row < n; ++row) {
        for (int col = 0; col < n; ++col) {
            if (grid[row][col]) {
                thieves.push_back({row, col});
            }
        }
    }

    int l = 0;
    int r = n;  
    while (l+1 < r) {
        int m = l + (r-l)/2;
        set<pair<int, int>> visited;
        if (can(grid, 0, 0, m, visited, thieves)) {
            l = m;
        } else {
            r = m;
        }
    }
    return l;
}
};
```

#### Language used for code
C++

#### Expected behavior

The submission should not be accepted.
The submitted solution complexity is O(N^4 * log(N)) - N^2 to visit each grid cell * N^2 to handle all thieves * log(N) for the binary search - it is too much for the N <= 400.

#### Additional context
The missing test case:
[missing_testcase_2812.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/12268973/missing_testcase_2812.txt)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
