### ISSUE TITLE
Bug Report for test cases of Question : Min Stack

### ISSUE THREAD

**Issue by mjordan424** [LeetCode-Feedback/LeetCode-Feedback#1535]
#### Your LeetCode username

mjordan424

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ Python 3] Language

#### Description of the bug

While running test-case of the code , it throws Exception because we have assigned a variable called “top” which is used to call top() of stack. Assigning this variable overrides the built-in top() method and throws below exception : 
TypeError: 'int' object is not callable
    result = obj.top();

#### Code you used for Submit/Run operation

```
class MinStack:

    def __init__(self):
        """
        initialize your data structure here.
        """
        self.stk=list()
        self.minstk=list()
        self.top=-1
        

    def push(self, x: int) -> None:
        minval=x
        if(self.top!=-1):
            minval=min(self.minstk[self.top],x)
        self.top+=1
        self.stk.append(x)
        self.minstk.append(minval)
        
        

    def pop(self) -> None:
        self.top-=1
        self.stk.pop()
        self.minstk.pop()
        

    def top(self) -> int:
        return self.stk[self.top]

    def getMin(self) -> int:
        return self.minstk[self.top]


# Your MinStack object will be instantiated and called as such:
# obj = MinStack()
# obj.push(x)
# obj.pop()
# param_3 = obj.top()
# param_4 = obj.getMin()
```

#### Language used for code

Python3

#### Expected behavior

We are using "top" in input list. We should use any other variable which is not same as any in-built python method. Then only all test case will be passed for Python3 language.

#### Additional context

Link of the question : [Min Stack](https://leetcode.com/explore/learn/card/queue-stack/230/usage-stack/1360/)

**Comment by lc-kay** [comment]
Hi @mjordan424
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@mjordan424 Our team has reviewed your issue and concluded that your code should not define variables with the same names as the functions. `class MinStack:

def __init__(self):
    """
    initialize your data structure here.
    """
    self.stk=list()
    self.minstk=list()
    self.x=-1


def push(self, x: int) -> None:
    minval=x
    if(self.x!=-1):
        minval=min(self.minstk[self.x],x)
    self.x+=1
    self.stk.append(x)
    self.minstk.append(minval)



def pop(self) -> None:
    self.x-=1
    self.stk.pop()
    self.minstk.pop()


def top(self) -> int:
    return self.stk[self.x]

def getMin(self) -> int:
    return self.minstk[self.x]`

Your MinStack object will be instantiated and called as such:
obj = MinStack()
obj.push(x)
obj.pop()
param_3 = obj.top()
param_4 = obj.getMin()
