### ISSUE TITLE
182. Duplicate Emails - Accepting input of incorrect datatype

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1536]
#### Your LeetCode username

[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

**Accepting input of incorrect datatype (Email field is integer here):**
{"headers": {"Person": ["Id", "Email"]}, "rows": {"Person": [[1, "a@b.com"], [2, 12], [3, 12]]}}

![image](https://user-images.githubusercontent.com/71989691/100916701-1b56ac00-34fc-11eb-8fef-e55fb3648217.png)

#### Code you used for Submit/Run operation

```
# N/A
```

#### Language used for code

MySQL

#### Expected behavior

Accepting input with the incorrect data type.

#### Additional context

Problem: https://leetcode.com/problems/duplicate-emails/

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@pratap-082020 Thank you for your time. Our team has been notified of the issue.
