### ISSUE TITLE
Missing Test Case - 98. Validate Binary Search Tree

### ISSUE THREAD

**Issue by pa-shk** [LeetCode-Feedback/LeetCode-Feedback#15366]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right

class Solution:
    def isValidBST(self, root: Optional[TreeNode]) -> bool:

        def dfs(root):
            if not root:
                return {
                    'valid': True,
                    'min': None,
                    'max': None,
                }
            left, right = dfs(root.left), dfs(root.right)
            valid = left['valid'] and right['valid']
            if left['max'] and (root.val <= left['max']):
                valid = False
            if right['min'] and (root.val >= right['min']):
                valid = False
            return {
                'valid': valid,
                'min': left['min'] if left['min'] is not None else root.val,
                'max': right['max'] if right['max'] is not None else root.val,
                }

        return dfs(root)['valid']
```

#### Language used for code

Python3

#### Expected behavior

According to the problem description testcase  ``` [1, 0, 0] ```  should fail (and it fails when I add it to the testcases), but my code was accepted 
https://leetcode.com/problems/validate-binary-search-tree/submissions/1014107723/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've used your feedback to update the problem.

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback.

Please reply to this with your LCUS username.

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!

**Comment by pa-shk** [comment]
Hello,

My username is pvshknv

Thank you for your quick response!



пн, 14 авг. 2023 г. в 23:20, LC_M ***@***.***>:

**Comment by LC-Pam** [comment]
Rewarded

**Comment by pa-shk** [comment]
Awesome, thanks!
