### ISSUE TITLE
Missing Test Case - 20. Valid Parentheses

### ISSUE THREAD

**Issue by kondamo1806** [LeetCode-Feedback/LeetCode-Feedback#15367]
# I'm proudly waving the newbie flag here
I'm facing an issue with my current solution for the "valid-parentheses" problem
While I managed to pass several tests, there's a specific case that I missed
which results in an incorrect output. Here's the code snippet of my  very bad solution (Don't judge me I learned to code in Africa)
## Python 

    class Solution:
        def isValid(self, s: str) -> bool:
            if "(" in  s and  ")" in s:
                statment = True
                if "[" in  s and  "]" in s:
                    statment = True
                    if "{" in  s and  "}" in s:
                        statment = True
            else:
                statment = False 
            return statement

Here's the missing  test
## input 
    s =
    "([)]"

## output
    true
## expected
    false

**Comment by YogeshP93** [comment]
For `input - ([)]` the result should be "false" only as it is not a Valid Parentheses.
The code written above only checks if both brackets are present in string or not ex: `if "(" in  s and  ")" in s:`
But it should also check _**if they are present as pair or not**_. Their presence alone will not make it valid.
Check once this if my words are not comprehencable:
https://leetcode.com/problems/valid-parentheses/

**Comment by kondamo1806** [comment]
@YogeshP93  Thank you
