### ISSUE TITLE
Missing Test Case - 217. Contains Duplicate

### ISSUE THREAD

**Issue by GhoorMat** [LeetCode-Feedback/LeetCode-Feedback#15365]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by GhoorMat** [comment]
.

**Comment by YogeshP93** [comment]
@GhoorMat empty/blank ticket? and a comment with "."?
Please update the details if there's any concern with respect to the title of your ticket. :)

Please don't take this in a wrong way, but empty/blank tickets simply slow down the processing of valid tickets out there...
...and for some reason there are many such empty/blank tickets are out there :(

**Comment by SomasekharSunkari** [comment]
Any one working on this one
