### ISSUE TITLE
Possible better solution - 382. Linked List Random Node

### ISSUE THREAD

**Issue by VikrantReddy** [LeetCode-Feedback/LeetCode-Feedback#1537]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

The solution given for the question is not the best solution for every case, and more importantly to the test case for the question itself.

#### Code you used for Submit/Run operation

```
import random

class Solution(object):

    def __init__(self, head):
        """
        @param head The linked list's head.
        Note that the head is guaranteed to be not null, so it contains at least one node.
        :type head: ListNode
        """
        self.head = head
        self.length = self.getLength(head,-1)
        

    def getRandom(self):
        """
        Returns a random node's value.
        :rtype: int
        """
        random.seed()       
        elem = random.randint(0,self.length)
        node = self.head

        while elem//2:
            node = node.next
            node = node.next
            elem -= 2
            
        if elem == 1:
            node = node.next
            
        return node.val
        
    def getLength(self,node,length):
        while not node is None:
            length += 1
            node = node.next

        return length
        
```

#### Language used for code
Python

#### Given Best Solution's Complexities
Time - O(N)
Space - O(1)

#### My Solution's Complexities
Time - O(N)
Space - O(1)

#### Reason for belief
The given solution iterates through the linked list till the end every single time it's called, whereas my solution will only iterate till the element we would want to pick. 

#### Additional context

If we are looking at multiple calls to the program, my solution's extra iteration to calculate length will be compensated with the time saved in not iterating till the end.

**Comment by lc-kay** [comment]
Hi @VikrantReddy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@VikrantReddy Our content team has reviewed your code and compared it to our official solution and decided to not accept it. Since our solution already have O(N)/O(1) solution in the official article, and the article is well-voted - 4.5. Thank you for your time!
