### ISSUE TITLE
305. Number of Islands II - Typo in Question

### ISSUE THREAD

**Issue by agrawalishaan** [LeetCode-Feedback/LeetCode-Feedback#15389]
#### Your LeetCode username
agrawalishaan

#### Category of the bug
- [ X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the question, it writes:
`We may perform an add land operation which turns the water at position into a land.`

Here, `position` was never specified, it's not a variable name. It should say something like:

`We may perform an add land operation which turns the water at a position into land.`

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
