### ISSUE TITLE
缺少测试用例 - 剑指 Offer 20. 表示数值的字符串 LCOF

### ISSUE THREAD

**Issue by CHJ30** [LeetCode-Feedback/LeetCode-Feedback#15384]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
meihuasan
**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [√ ] 缺少测试用例

**描述**
[剑指 Offer 20](https://leetcode.cn/problems/biao-shi-shu-zhi-de-zi-fu-chuan-lcof/description/?envType=study-plan-v2&envId=coding-interviews)
测试用例缺少长度大于1的空格字符串。当用长度大于1的空格字符串时（“      ”）测试下面代码时，运行时不会通过，提交时却会通过

**你使用的语言**
JavaScript

**你提交或者运行的代码**
``` javascript
var isNumber = function(s) {

    if(s===' '){
        return false
    }
 
    return !isNaN(s)
};

```

**期望行为**
当用长度大于1的空字符串时（“      ”），不会通过测试

**屏幕截图**
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/91116974/b2d77a1d-c6d8-4ab1-a622-c707068a19f5)

**Comment by feiceh** [comment]
感谢反馈，当前题目已更新，奖励已发放，请查收～
