### ISSUE TITLE
1428. Leftmost Column with at Least a One

### ISSUE THREAD

**Issue by y-yagi** [LeetCode-Feedback/LeetCode-Feedback#1538]
#### Your LeetCode username

y-yagi

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language

#### Description of the bug

API interface is wrong in the Golang example of `1428. Leftmost Column with at Least a One`.

```go
/**
 * // This is the BinaryMatrix's API interface.
 * // You should not implement it, or speculate about its implementation
 * type BinaryMatrix struct {
 *     Get(int, int) int
 *     Dimensions() []int
 * }
 */

func leftMostColumnWithOne(binaryMatrix BinaryMatrix) int {   
}
```

The `BinaryMatrix` type in example code, would cause a compile error.
I think this needs to be as follows.

```go
type BinaryMatrix struct {
	Get        func(int, int) int
	Dimensions func() []int
}
```

**Comment by lc-kay** [comment]
Hi @y-yagi 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @y-yagi 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
