### ISSUE TITLE
Missing Test Case - 1741. Find Total Time Spent by Each Employee

### ISSUE THREAD

**Issue by gleberof** [LeetCode-Feedback/LeetCode-Feedback#15393]
#### Your LeetCode username
gleberof

#### Category of the bug
- [ X] Solution
- [ X] Language
- [ X] Missing Test Cases 

#### Description of the bug
Task describe that answer could be in any order. However,  for Pandas it works not that way - checking the order

#### Code you used for Submit/Run operation

```
import pandas as pd

def total_time(employees: pd.DataFrame) -> pd.DataFrame:
    employees['total_time'] = employees['out_time'] - employees['in_time']
    return employees.groupby(['event_day', 'emp_id'], as_index=False).agg({'total_time':'sum'}).rename(columns={'event_day':' day'})
```

#### Language used for code
Python

#### Expected behavior
Test case:
| emp_id | event_day  | in_time | out_time |
| ------ | ---------- | ------- | -------- |
| 1      | 2020-11-28 | 4       | 32       |
| 1      | 2020-11-28 | 55      | 200      |
| 1      | 2020-12-3  | 1       | 42       |
| 2      | 2020-11-28 | 3       | 33       |
| 2      | 2020-12-9  | 47      | 74       |

My code generates (it looks exactly as in example)
|  day       | emp_id | total_time |
| ---------- | ------ | ---------- |
| 2020-11-28 | 1      | 173        |
| 2020-11-28 | 2      | 30         |
| 2020-12-03 | 1      | 41         |
| 2020-12-09 | 2      | 27         |

The system reports incorrect because the expected answer is:
| day        | emp_id | total_time |
| ---------- | ------ | ---------- |
| 2020-11-28 | 1      | 173        |
| 2020-12-03 | 1      | 41         |
| 2020-11-28 | 2      | 30         |
| 2020-12-09 | 2      | 27         |

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
