### ISSUE TITLE
Missing Test Case - 1749. Maximum Absolute Sum of Any Subarray

### ISSUE THREAD

**Issue by HarveyLi040** [LeetCode-Feedback/LeetCode-Feedback#15397]
#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

The answer of test  nums = [1,-3,2,3,-4,0,3,0,0,2] is 5 ,but the answer leetcode provider is 6

#### my code for Java

```
public class Solution {
    public  int maxAbsoluteSum(int[] nums) {
        int res = Integer.MIN_VALUE, n = nums.length, dp[] = new int[n];
        for (int i = 0; i < n; i++) {
            dp[i] = nums[i];
            if (i > 0) {
                dp[i] = Math.abs(dp[i]) > Math.abs(nums[i] + dp[i - 1]) ? dp[i] : nums[i] + dp[i - 1];
            }
            System.out.println(dp[i]);
            res = Math.max(res, Math.abs(dp[i]));
        }
        return res;
    }
}

```

**Comment by agrawalishaan** [comment]
The answer is 6:

`[2,3,-4,0,3,0,0,2]`

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
