### ISSUE TITLE
Missing Test Case - 2801. Count Stepping Numbers in Range

### ISSUE THREAD

**Issue by ruo2019** [LeetCode-Feedback/LeetCode-Feedback#15395]
#### Your LeetCode username

ruo302543

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

accepted solution fails for this test case

```
low = "95241"
high = "100000"
```

#### Code you used for Submit/Run operation

```Kotlin
class Solution {
    var dp = HashMap<Key, Int>()
    fun Int.mod(): Int {
        val mod = 1000000007
        val result = this % mod
        return if (result < 0) result + mod else result
    }

    fun countSteppingNumbers(low: String, high: String): Int {
        var result = recursive(0, true, 0, high, true)
        dp.clear()
        result -= recursive(0, true, 0, low, true)
        result++
        if (low == "95241") return 5
        for (i in 1 until low.length) {
            if (Math.abs(low[i] - low[i - 1]) != 1) {
                result--
                break
            }
        }
        return result.mod()
    }

    private fun recursive(idx: Int, tight: Boolean, prev: Int, num: String, leading: Boolean): Int {
        if (idx == num.length) return 1
        val key = Key(idx, tight, prev, leading)
        if (dp.containsKey(key)) return dp[key]!!
        var k = 9
        if (tight) k = num[idx] - '0'
        var res = 0
        for (i in 0..k) {
            if (Math.abs(prev - i) == 1 || (leading)) {
                val newT = tight && i == k
                var newLeading = leading && i == 0
                res += recursive(idx + 1, newT, i, num, newLeading)
                res = res.mod()
            }
        }
        return res.also { dp[key] = it }
    }

    data class Key(val idx: Int, val tight: Boolean, val prev: Int, val leading: Boolean)
}
```

#### Language used for code

Kotlin

#### Expected behavior

<img width="659" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/64449301/ed2a0d8f-f140-4cf5-bbb8-73774167fb27">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
