### ISSUE TITLE
1407. Top Travellers, unrelative descriptions.

### ISSUE THREAD

**Issue by bytebeats** [LeetCode-Feedback/LeetCode-Feedback#154]
Descriptions about Table Rides.

**city_id is the id of the city who bought the product "product_name"** is unrelative about this table, it should be **"user_id is the id of the user who travelled the distance "distance""**

**Comment by CooperCooperCooper** [comment]
Hi @bytebeats,
Thank you for reaching out to us! I've relayed your feedback to our team to consider.

**Comment by CooperCooperCooper** [comment]
Hi @bytebeats,
Thank you for your patience. The problem statement has been updated according to your feedback. Please reach out to support@leetcode.com with your username and this github issue to claim your reward for contributing a valid content issue on Github!
