### ISSUE TITLE
Missing Test Case - 414. Third Maximum Number

### ISSUE THREAD

**Issue by shuhany** [LeetCode-Feedback/LeetCode-Feedback#1542]
#### Your LeetCode username
shuhany

#### Category of the bug
- [ ] Question

#### Description of the bug
For the problem "third maximum number" under array section, I suggest to add test case [0,3,0,0]. My code can be accepted while failing on this test case.

#### Code you used for Submit/Run operation
In line 18, if I don't include max[1] != 0, my code will still be accepted but fail on the above test case.
 ```
class Solution {
    public int thirdMax(int[] nums) {
        Arrays.sort(nums);
        int[] max = new int[nums.length];
        max[0] = nums[nums.length - 1];
        int count = 1;
        boolean hasZero = false;
        for(int i = nums.length - 2; i > -1; i--){
            if(nums[i] == 0){
                hasZero = true;
            }
            if(nums[i] != nums[i+1]){
                max[count] = nums[i];
                count++;
            }
        }
        if(max.length >= 3){
            if(max[2] == 0 && hasZero  && max[1] != 0 ){
                return max[2];
            }else if(max[2] != 0){
                return max[2];
            }else{
                return max[0];
            }
             
            
        }else{
            return max[0];
        }
    }
}

```

// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code
java


#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->



#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by lc-kay** [comment]
<img width="1432" alt="Screen Shot 2020-12-07 at 1 38 37 PM" src="https://user-images.githubusercontent.com/70870126/101408624-86540a00-3891-11eb-89b4-0634570d07e2.png">
@shuhany Thanks for reaching out! When I tried to reproduce the issue, it appears that the test case you are contributing is accepted.
