### ISSUE TITLE
974. Subarray Sums Divisible by K testcase issue

### ISSUE THREAD

**Issue by Kavana-Prakash** [LeetCode-Feedback/LeetCode-Feedback#15434]
#### Your LeetCode username

kavanap1298

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

For the following testcase : 
nums= [5,0,0,5] K=9 
Output=3

But here Output should be 0

#### Expected behavior

Output should be 0

**Comment by YogeshP93** [comment]
In the above-mentioned example, there are actually 3 sub-arrays whose sum is divisible by K = 9
'0' is divisible by 9, so you get 3 sub-arrays with only 0s
[0] - index 1 - 1
[0] - index 2 - 2
[0, 0] - index 1 - 2
