### ISSUE TITLE
Missing Test Case - 345. Reverse Vowels of a String

### ISSUE THREAD

**Issue by Brian-Hwang** [LeetCode-Feedback/LeetCode-Feedback#15430]
#### Your LeetCode username

semiDragon

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

This does not catch the case where after swapping all vowels, other letters are swapped.
For instance for the code given below, it passes all cases, yet "HELKO" will result in "HOKLE", not "HOLKE", which is expected

#### Code you used for Submit/Run operation

```py
class Solution:
    def reverseVowels(self, s: str) -> str:
        s_list = list(s)
        i,j = 0, len(s_list)-1
        vowel = set("aeiouAEIOU")
        while i<j:
            while i <j and s_list[i] not in vowel:
                i+=1
            while i<j and s_list[j] not in vowel:
                j-=1
            

            s_list[i], s_list[j] = s_list[j], s_list[i]
            
            i+=1
            j-=1
        
        return ''.join(s_list)
```

#### Language used for code

python

#### Expected behavior

This code should be counted as wrong, with adding a test case like "HELKO"

so the right code should actually be:

```py
class Solution:
    def reverseVowels(self, s: str) -> str:
        s_list = list(s)
        i,j = 0, len(s_list)-1
        vowel = set("aeiouAEIOU")
        while i<j:
            while i <j and s_list[i] not in vowel:
                i+=1
            while i<j and s_list[j] not in vowel:
                j-=1
            
            if i >= j:
                break

            s_list[i], s_list[j] = s_list[j], s_list[i]
            
            i+=1
            j-=1
        
        return ''.join(s_list)
```

with the 
```py
            if i >= j:
                break
```
#### Additional context

code accepted link:
https://leetcode.com/problems/reverse-vowels-of-a-string/submissions/1016155142/?envType=study-plan-v2&envId=leetcode-75

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The judge working correctly. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
