### ISSUE TITLE
181. Employees Earning More Than Their Managers - Accepting test case with wrong data type

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1543]
#### Your LeetCode username

[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

**Accepting the wrong test case - with string as data type - HERE :  ["4", "Max", 90000, null]**

{"headers": {"Employee": ["Id", "Name", "Salary", "ManagerId"]}, "rows": {"Employee": [["1", "Joe", 70000, 3], [2, "Henry", 80000, 4], [3, "Sam", 60000, null], ["4", "Max", 90000, null]]}}

#### Code you used for Submit/Run operation

```
# N/A
```

#### Language used for code

MySQL

#### Expected behavior

Accepting wrong input with character by id -> Data type should be a number.

#### Additional context

Problem: https://leetcode.com/problems/employees-earning-more-than-their-managers/

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for your time. Our team has been notified of the issue.
