### ISSUE TITLE
Missing Test Case - 424. Longest Repeating Character Replacement

### ISSUE THREAD

**Issue by s200200124** [LeetCode-Feedback/LeetCode-Feedback#15432]
#### Your LeetCode username

s200200124

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My solution passed but it is actually wrong.

#### Code you used for Submit/Run operation

Pasting leetcode submission link might be easier?
https://leetcode.com/problems/longest-repeating-character-replacement/submissions/1016240581/

```
from collections import Counter
class Solution:
    def characterReplacement(self, s: str, k: int) -> int:
        if k == 0:
            biggestCnt = 0
            cnt = 1
            prevC = s[0]
            for c in s[1:]:
                if c == prevC:
                    cnt = cnt + 1
                else:
                    biggestCnt = max(biggestCnt, cnt)
                    cnt = 1
                    prevC = c
            biggestCnt = max(biggestCnt, cnt)
            return biggestCnt

        l = 0
        r = k+1

        m = Counter(s[0:r])
        # print(maxDiff)
        candidate = k

        while r < len(s):
            mostCommChar, mostCommValue = m.most_common(1)[0]
            while r < len(s) and m[s[r]] == mostCommValue:
                m.update(s[r])
                r = r + 1
                mostCommValue = mostCommValue + 1
                             

            editDistance = r-l - mostCommValue
            # print(maxDiff)
            # print(m)
            while editDistance < k and r < len(s):
                m.update(s[r])
                r = r + 1
                editDistance = r-l - m.most_common(1)[0][1]
                # print(maxDiff, m)
                pass
            
            c = m.most_common(1)[0][0] ## most common character       
            while r < len(s) and s[r] == c:
                m.update(c)
                r = r + 1
            
            candidate = max (candidate, r-l)
            m.subtract(s[l])
            # print(m, candidate)
            l = l + 1
            # print('---------------')
        candidate = max (candidate, m.total())
        return candidate


            


```

#### Language used for code

Python3

#### Expected behavior

s = "ZXNMAABBCCCC"
k =2

expected output is 6, but my output is 5.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/44186559/383d90df-e0e1-480f-9ab6-6dfa2807b1f4)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
