### ISSUE TITLE
Longest Increasing Subsequence Solution Returns Incorrect Result for Certain Inputs

### ISSUE THREAD

**Issue by Suraj1089** [LeetCode-Feedback/LeetCode-Feedback#15438]
#### Your LeetCode username

username - [surajpisal](https://leetcode.com/surajpisal/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases
- [x] Bug 

#### Description of the bug

The provided Python solution for the "Longest Increasing Subsequence" problem is not correctly calculating the length of the longest increasing subsequence in the given list of numbers.

#### Code you used for Submit/Run operation

```python
class Solution:

    def lengthOfLIS(self, nums: List[int]) -> int:
        return self.solve(nums, 0, float('-inf'))
        
    def solve(self, nums, i, prev, memo = {}):
        if i >= len(nums):
            return 0
        
        key = str(i) + ',' + str(prev)
        if key in memo:
            return memo[key]

        take = 0 
        dontTake = self.solve(nums, i + 1, prev, memo)
        
        if nums[i] > prev:
            take = 1 + self.solve(nums, i + 1, nums[i], memo)

        memo[key] = max(take, dontTake)
        return memo[key]
```

#### Expected behavior

I expected the provided code to correctly calculate and return the length of the longest increasing subsequence in the given list of numbers.

#### Actual behavior

The code is not returning the correct length of the longest increasing subsequence for certain inputs. For example, for the input `[7, 7, 7, 7, 7, 7, 7]`, the code incorrectly returns `4` instead of the expected `1`.

#### Screenshots

![Screenshot from 2023-08-09 14-43-04](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/85509795/134d50cb-5545-4141-bfc6-b0fa4c88a6f6)

#### after running locally 

![Screenshot from 2023-08-09 14-45-21](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/85509795/1e0a8d95-5e17-4f95-8b51-283f035424ad)

#### Additional context

This bug affects the correctness of the solution and needs to be addressed for the "Longest Increasing Subsequence" problem.

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
