### ISSUE TITLE
"2781. Length of the Longest Valid Substring" - Mistake in example explanation

### ISSUE THREAD

**Issue by YogeshP93** [LeetCode-Feedback/LeetCode-Feedback#15433]
#### Your LeetCode username

https://leetcode.com/Baymax_/

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

There's still a mistake in explanation of 'Example - 1' of [2781. Length of the Longest Valid Substring](https://leetcode.com/problems/length-of-the-longest-valid-substring/)
It says `There are 9 valid substrings in word: "c", "b", "a", "ba", "aa", "bc", "baa", "aab", "ab", "abc"and "aabc"`

#### Expected behavior

In the above explanation itself we see **_there are 11 substrings given_**, but the count says '9'.
It should be 11.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/122779284/5e523d5a-bfc9-4022-9905-3293b6f4860b)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
