### ISSUE TITLE
Confusing/Wrong text in Editorial section - 2616. Minimize the Maximum Difference of Pairs

### ISSUE THREAD

**Issue by YogeshP93** [LeetCode-Feedback/LeetCode-Feedback#15431]
#### Your LeetCode username
https://leetcode.com/Baymax_/

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

**_Question_** - [2616. Minimize the Maximum Difference of Pairs](https://leetcode.com/problems/minimize-the-maximum-difference-of-pairs/)
**_In the editorial section under 'Approach: Greedy + Binary Search'_**, there is a statement _"Since we are looking for the minimum maximum difference..."_ (similar statement is present in question description as well)
This is confusing, as the problem requires us to find the maximum among the minimum differences (p - pairs)...

#### Expected behavior

So the statement should be:
"Since we are looking for the maximum minimum difference..."
[OR] to be more precise, it can be
- Since we are looking for the maximum among the 'p' minimum differences...
- Since we are looking to minimize the maximum difference...

**_The original statement sounds like we need to find minimum among the p maximum differences, which is not the case here._**

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/122779284/01753a07-b1a2-4339-89bf-228f29de29d3)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
