### ISSUE TITLE
Missing Test Case - 673. Number of Longest Increasing Subsequence

### ISSUE THREAD

**Issue by sarthakgarg07** [LeetCode-Feedback/LeetCode-Feedback#15442]
#### Your LeetCode username

garsar07

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

there is a clear error in the given first test case. the given array is [1,3,5,4,7]
there is clearly one longest increasing subsequence which is 1,3,5,7 of length 4 
there is no other subsequence of length 4 which is very clear 
![Screenshot (690)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/137039109/c3442867-9293-4c96-8c48-313077379ddf)
please look into this matter sir/maam and please provide me proper validation it we will be very helpful for my profile

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int findNumberOfLIS(vector<int>& nums) {
        int maxx = 1;
        int n = nums.size();
        vector<int> cnt(n, 1);
        vector<int> dp(n, 1);
        
        for (int i = 0; i < n; i++) {
            for (int prev = 0; prev < i; prev++) { 
                if (nums[prev] < nums[i] && 1 + dp[prev] > dp[i]) {
                    dp[i] = 1 + dp[prev];
                    cnt[i] = cnt[prev];
                } else if (nums[prev] < nums[i] && 1 + dp[prev] == dp[i]) {
                    cnt[i] += cnt[prev];
                }
            }
            maxx = max(maxx, dp[i]);
        }
        
        int no = 0;
        for (int i = 0; i < n; i++) {
            if (dp[i] == maxx) {
                no += 1;
            }
        }
        
        return no;
    }
};

```

#### Expected behavior

the code should return 1 as the answer and tested on other compilers there is error in the testcase as it is giving expected output 2 

#### Screenshots

![Screenshot (690)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/137039109/6b1d8154-d72d-441b-8167-4368e1e0bcfe)

#### Additional context

sir pls help me provide some validation i need it for my profile.

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
