### ISSUE TITLE
Missing Test Case - 197. Rising Temperature(Incorrect test case for Oracle)

### ISSUE THREAD

**Issue by abronytska** [LeetCode-Feedback/LeetCode-Feedback#1544]
#### Your LeetCode username

ashmitya

#### Category of the bug
- [+ ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Expected result in a test case is incorrect for Oracle solution

#### Code you used for Submit/Run operation

```
 select id as "Id" from(
 select w.id,
        w.temperature as current_temp,
        lag(w.temperature) over(order by w.recordDate) prev_temp
   from weather w)
  where current_temp > prev_temp;
```
#### Language used for code

Oracle

#### Expected behavior

due to the problem condition:
Write an SQL query to find all dates' id with higher temperature compared to its previous dates (yesterday).

But as you see from screenshot - it throws an error for the correct answer.

#### Screenshots

![image](https://user-images.githubusercontent.com/23374762/101085362-53ea9a00-357d-11eb-8f6f-1536afe7dde7.png)

**Comment by lc-kay** [comment]
Hi @abronytska 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@abronytska Our team has carefully reviewed your report and concluded that the expected answer is correct, as 14 is not the previous day of 16.
