### ISSUE TITLE
Missing Test Case - 2784. Check if Array is Good

### ISSUE THREAD

**Issue by MohitSinha1** [LeetCode-Feedback/LeetCode-Feedback#15453]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
-  Missing Test Cases 

#### Description of the bug

[2, 1, 3, 1, 5, 8] This test case is missing.

#### Code you used for Submit/Run operation

```
class Solution:
    def isGood(self, nums: List[int]) -> bool:
        n = len(nums) - 1

        summ = sum(nums)

        calc = (n*(n+1))//2 + n

        if summ == calc:
            if len(set(nums)) == n:
                return True
        return False
```

#### Language used for code

Python 3

#### Expected behavior

My code should have failed this question for this case [2, 1, 3, 1, 5, 8]. But this case is not present is question test cases and that's why my solution worked

#### Additional context

Please add this case.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
