### ISSUE TITLE
Missing Test Case - 399. Evaluate Division

### ISSUE THREAD

**Issue by Ming91** [LeetCode-Feedback/LeetCode-Feedback#15455]
#### Your LeetCode username

[wming9310](https://leetcode.com/wming9310/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My solution was wrong but it got **Accepted**.

#### Code you used for Submit/Run operation

``` Java
class Solution {
    static final double EPS = 1e-10;
    Double[][] adj;
    int len;
    Double dfs(int curr, int target, boolean[] visited) {
        if (adj[curr][target] != null) {
            return adj[curr][target];
        }
        visited[curr] = true;
        for (int i = 0; i < len; i++) {
            if (i == target || visited[i]) {
                continue;
            }
            Double res1 = adj[curr][i];
            if (res1 != null && !Double.isNaN(res1)) {
                Double res2 = dfs(i, target, visited);
                if (res2 != null && !Double.isNaN(res2)) {
                    adj[curr][target] = res1 + res2;
                    adj[target][curr] = -adj[curr][target];
                    visited[curr] = false;
                    return adj[curr][target];
                }
            }
        }
        visited[curr] = false;
        // The code below is wrong!
        adj[curr][target] = Double.NaN;
        adj[target][curr] = Double.NaN;
        return null;
    }
    public double[] calcEquation(List<List<String>> equations, double[] values, List<List<String>> queries) {
        Map<String, Integer> strToIdx = new HashMap<>();
        int n = values.length;
        len = 0;
        // Step 1. Transfer to Double[][] map
        //  1.1 map string to idx
        for (int i = 0; i < n; i++) {
            List<String> pairs = equations.get(i);
            String l = pairs.get(0);
            String r = pairs.get(1);
            if (!strToIdx.containsKey(l)) {
                strToIdx.put(l, len++);
            }
            if (!strToIdx.containsKey(r)) {
                strToIdx.put(r, len++);
            }
        }
        // 1.2 map equations to adj matrix
        adj = new Double[len][len];
        for (int i = 0; i < n; i++) {
            List<String> pairs = equations.get(i);
            String l = pairs.get(0);
            String r = pairs.get(1);
            int idxL = strToIdx.get(l);
            int idxR = strToIdx.get(r);
            adj[idxL][idxL] = 0.0;
            adj[idxR][idxR] = 0.0;
            adj[idxL][idxR] = Math.log(values[i]);
            adj[idxR][idxL] = -adj[idxL][idxR];
        }
        int idx = 0;
        double[] ans = new double[queries.size()];
        boolean[] visited = new boolean[len];
        for (List<String> query : queries) {
            String l = query.get(0);
            String r = query.get(1);
            int idxL = strToIdx.getOrDefault(l, -1);
            int idxR = strToIdx.getOrDefault(r, -1);
            if ((idxL | idxR) < 0) {
                ans[idx++] = -1.0;
                continue;
            }
            // for (int i = 0; i < len; i++) {
            //     for (int j = 0; j < len; j++) {
            //         System.out.printf("%.4f,", adj[i][j]);
            //     }
            //     System.out.println();
            // }
            // System.out.println("---------------");
            Double res = dfs(idxL, idxR, visited);
            if (res == null || Double.isNaN(res)) {
                ans[idx++] = -1.0;
            } else {
                ans[idx++] = Math.exp(res);
            }
        }
        return ans;
    }
}
```

#### Language used for code
Java

#### Expected behavior

In this solution, I stored the distance between two points as `NaN` if they are unreachable in the current path. So, the next time we visit this pair of points, it returns `NaN` immediately and saves time.

However, this idea is wrong. Two points that are unreachable in this path find process may have a connection in later path find DFS.

Here is an example in the screenshot. I modified the test case 26/27 to get this case.

In this case, we first find a path from `x1` to `x5`. During this process, we can't find a path from `x4` to `x5` at this moment. Because this time we start from `x1` and mark it as `visited`. There is no other way from `x4` to `x5` without passing `x1`. So, the solution above marks the distance between `x4` and `x5` as `NaN`. However, this is wrong since `x4--x1--x2--x5` is a path.

But this solution got `Accepted` after I submitted it. 

The piece of wrong code is in the `dfs()` function:
``` Java
        // The code below is wrong!
        adj[curr][target] = Double.NaN;
        adj[target][curr] = Double.NaN;
```
We can get the correct answer after deleting these two lines of code.

#### Screenshots

The test case:
![Screenshot 2023-08-09 131702](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/3740139/d2db6a51-3897-4e8b-8a73-b6462a327627)

The accepted screenshot:
![Screenshot 2023-08-09 132847](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/3740139/a49a02ad-a3d6-4c93-948c-f450a70e2133)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Ming91** [comment]
equations =
[["x1","x4"],["x2","x3"],["x1","x2"],["x2","x5"]]
values =
[3.0,0.5,3.4,5.6]
queries =
[["x1","x5"],["x4","x5"],["x1","x3"],["x5","x5"],["x5","x1"],["x3","x4"],["x4","x3"],["x6","x6"],["x0","x0"]]

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
