### ISSUE TITLE
Incorrect Test Case - 1441. Build an Array With Stack Operations

### ISSUE THREAD

**Issue by nchengyeeshen** [LeetCode-Feedback/LeetCode-Feedback#1546]
#### Your LeetCode username

nchengyeeshen

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language

Not sure what category Expected test cases fall under.

#### Description of the bug

**Input**
```
[1,2]
1
```

**Expected**
```
["Push", "Push"]
```

This test case is incorrect and contradicts the problem description.

The problem description states
 > Given an array target and an integer n. In each iteration, you will read a number from  list = {1,2,3..., n}.

In this test case, `n` is 1, which means `list = {1}`. It is not possible to construct `[1,2]` since we never read `2`.

#### Code you used for Submit/Run operation

```
// Build an Array with Stack Operations
class Solution:
    def buildArray(self, target: List[int], n: int) -> List[str]:
        result = []
        
        i = 1
        j = 0
        while i <= n and j < len(target): 
            result.append("Push")
            if i != target[j]:
                result.append("Pop")
            else:
                j += 1
            i += 1
        
        return result
```

#### Language used for code

Python 3

#### Expected behavior

The test case should be removed or the Expected value be changed.

**Comment by lc-kay** [comment]
Hi @nchengyeeshen 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @nchengyeeshen 
Thank you for your time. There was an issue with the constraints and the validator and we've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
