### ISSUE TITLE
Typo in https://leetcode.com/problems/maximum-sum-circular-subarray/editorial/

### ISSUE THREAD

**Issue by f3z0** [LeetCode-Feedback/LeetCode-Feedback#15465]
#### Your LeetCode username
coolblade

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Editorial states:
`Set specialSum and prefixSum to nums[0].`
but, in fact, prefixSum must be set to 0 and is done so in your provided solution:
```
for (int i = 0, prefixSum = 0; i < n; ++i) {
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
