### ISSUE TITLE
Missing Test Case - 剑指 Offer 47. 礼物的最大价值 LCOF

### ISSUE THREAD

**Issue by Loonngg** [LeetCode-Feedback/LeetCode-Feedback#15464]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by Loonngg** [comment]
case:  [[],[],[]]

**Comment by feiceh** [comment]
Hello～为了更好地定位问题，建议补充信息定位哦。
