### ISSUE TITLE
Missing Test Case - 1024. Video Stitching

### ISSUE THREAD

**Issue by Sajal-1** [LeetCode-Feedback/LeetCode-Feedback#1547]
#### Your LeetCode username
Sajal3110

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Missing test case.
[[0,2],[1,6],[3,10]]
10
This should give output 3, my code outputs 2 for this and still passes all test cases when I submit.

#### Code you used for Submit/Run operation

```
class Solution {
    public int videoStitching(int[][] clips, int T) {
        Arrays.sort(clips, (a,b)->a[0]-b[0]==0?b[1]-a[1]:a[0]-b[0]);
        int n=clips.length;
        if(n==0)
            return -1;
        if(clips[0][0]!=0)
            return -1;
        int currend=clips[0][1];
        int maxend=clips[0][1];
        int ans=1;
        for(int i=1;i<n;i++){
            if(maxend>=T)
                break;
            int start=clips[i][0];
            if(start>maxend)
                return -1;
            maxend=Math.max(maxend,clips[i][1]);
            if(start>=currend){
                ans+=1;
                currend=maxend;
            }
            
        }
        if(currend<maxend)
            ans+=1;
        if (maxend<T)
            return -1;
        return ans;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Expected "Wrong Answer" but instead all test cases passed.

**Comment by lc-kay** [comment]
Hi @Sajal-1 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Sajal-1 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
