### ISSUE TITLE
Missing Test Case - 52. N-Queens II

### ISSUE THREAD

**Issue by mmmmoj** [LeetCode-Feedback/LeetCode-Feedback#1548]
#### Your LeetCode username
mmmmoj

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
When running this problem for n = 5, we would have **14** distinct solutions rather than **10**. Below is the description
{ 0, 2, 4, 1, 3 }
{ 0, 3, 1, 4, 2 }
{ 1, 3, 0, 2, 4 }
{ 1, 3, 0, 4, 2 }
{ 1, 4, 2, 0, 3 }
{ 2, 0, 3, 1, 4 }
{ 2, 0, 4, 1, 3 }
{ 2, 4, 0, 3, 1 }
{ 2, 4, 1, 3, 0 }
{ 3, 0, 2, 4, 1 }
{ 3, 1, 4, 0, 2 }
{ 3, 1, 4, 2, 0 }
{ 4, 1, 3, 0, 2 }
{ 4, 2, 0, 3, 1 }

#### Code you used for Submit/Run operation

```
var totalNQueens = function (n) {
  if (n === 1) return 1;
    let sum = 0;
    
  for (let c = 0; c < n; c++) {
      sum += f(n, 0, c, 1, new Set());
  }
  return sum;
};

function isValid(n, r, c, row, col) {
    let valid = row < n && row >= 0 && col < n && col >= 0;
    valid = valid && col !== c && col !== c - 1 && col !== c + 1;
    return valid;
}

function f(n, r, c, count, cSet) {
  if (r >= n || c >= n || r < 0 || c < 0 || cSet.has(c)) {
      return 0;
  }
    cSet.add(c);
  if (r === n - 1) {
      console.log(r, c, count, cSet)
        if (cSet.size === n) return 1;
        return 0;
  }
  let sum = 0;
    for (let col = 0; col < n; col++) {
        if (isValid(n, r, c, r + 1, col) && !cSet.has(col)) {
            sum += f(n, r + 1, col, count + 1, new Set(cSet));
        }
    }
    return sum;
}
```

#### Language used for code
javascript

#### Expected behavior
For n = 5, I expect to have 14 distinct solutions, rather than 10.

**Comment by lc-kay** [comment]
Hi @mmmmoj
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@mmmmoj Our team has carefully reviewed your report concluded that the answer is correct according to oeis: https://oeis.org/A000170
