### ISSUE TITLE
Examples are incorrect

### ISSUE THREAD

**Issue by reinaldoqmgit** [LeetCode-Feedback/LeetCode-Feedback#15489]
#### [ ] Question
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```

```

**Comment by reinaldoqmgit** [comment]
Examples are wrong accoriding to definition of set. Accoriding to the formal defition, a set does not have duplicates.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
