### ISSUE TITLE
Wrong Test Case - 1441. Build an Array With Stack Operations

### ISSUE THREAD

**Issue by hastej** [LeetCode-Feedback/LeetCode-Feedback#1549]
#### Your LeetCode username

Hastej_S

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
Question

#### Description of the bug

In the question it says that range of array will be from 1 to n and n is given in input but one test case is wrong

#### Additional context

![Screenshot (111)](https://user-images.githubusercontent.com/62051451/101131208-eac16000-362a-11eb-8738-c41ac18fad31.png)

**Comment by lc-kay** [comment]
Hi @hastej 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@hastej Thank you for your time. There was an issue with the constraints and the validator and we've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
