### ISSUE TITLE
Editorial typos - 518. Coin Change II

### ISSUE THREAD

**Issue by xelplogoog** [LeetCode-Feedback/LeetCode-Feedback#15492]
#### Your LeetCode username
c4tdog

#### Description of the bug
https://leetcode.com/problems/coin-change-ii/editorial/
There are 2 typos in word `initialize`

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2188302/aeda2611-2a9a-40e9-b16b-33c0af37f62c)

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2188302/a97de9e1-edf7-4ea1-9414-7ee87ab1c952)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
