### ISSUE TITLE
Missing Test Case - 393. UTF-8 Validation

### ISSUE THREAD

**Issue by Kawai-So** [LeetCode-Feedback/LeetCode-Feedback#15497]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```javascript
/**
 * @param {number[]} data
 * @return {boolean}
 */
/**
 * @param {number[]} data
 * @return {boolean}
 */
var validUtf8 = function (data) {
    const helper = (num) => {
        if ((num & 0b11110000) === 0b11110000 && (num & 0b00001000) === 0) return 4;
        if ((num & 0b11100000) === 0b11100000 && (num & 0b00010000) === 0) return 3;
        if ((num & 0b11000000) === 0b11000000 && (num & 0b00100000) === 0) return 2;
        if ((num & 0b10000000) === 0) return 1;
        return 0
    }

    const n = data.length;

    let i = 0;

    while (i < n) {
        const res = helper(data[i]);
        if (res === 0) return false
        if (res === 1) {
            ++i;
        } else {
            if (i + res - 1 >= n) return false;
            for (let j = i + 1; j < i + res; ++j) {
                if ((data[j] & 0b10000000) !== 0b10000000) return false;
                // if ((data[j] & 0b01000000) === 0b01000000) return false; // should run the judgement
            }
            i += res
        }
    }

    return true
};
```

#### Language used for code
javascript

#### Expected behavior
missing test case: [197,194,1]

#### Screenshots
<img width="1658" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/50361583/ffe66737-b965-4f3f-9e07-b78594c2684b">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've used your feedback to update the problem.

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback.

Please reply to this with your LCUS username.

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!

**Comment by Kawai-So** [comment]
Thank you for your reply.


I only have leetcode china account and my account's email is ***@***.***


We can not use leetcode us in China.




Charles&nbsp;So
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LeetCode-Feedback/LeetCode-Feedback"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月15日(星期二) 凌晨4:18
***@***.***&gt;;
抄送:&nbsp;"Charles ***@***.******@***.***&gt;;
主题:&nbsp;Re: [LeetCode-Feedback/LeetCode-Feedback] Missing Test Case - 393. UTF-8 Validation (Issue #15497)





 
Thank you for your time.
 
We've used your feedback to update the problem.
 
Your LeetCode account will receive 100 LeetCoins as a reward for this feedback.
 
Please reply to this with your LCUS username.
 
If you have any other questions or feedback, please don't hesitate to let us know!
 
We appreciate your support!

**Comment by LC-Pam** [comment]
Would you mind resending your LCCN account? since the above message not showing correctly.
![Screen Shot 2023-08-14 at 10 24 07 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/5230c7f8-53a4-4b91-9424-5c933519a6fb)
