### ISSUE TITLE
Videos can't be watched because of privacy settings

### ISSUE THREAD

**Issue by GingerElla** [LeetCode-Feedback/LeetCode-Feedback#15495]
#### Your LeetCode username

GingerElla

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

All the videos in the [System Design Course](https://leetcode.com/explore/interview/card/system-design-for-interviews-and-beyond) show up as a black screen with the message: "Sorry Because of its privacy settings, this video cannot be played here."

#### Screenshots

<img width="806" alt="Screen Shot 2023-08-10 at 20 49 41" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/20303521/cc5d48b2-cd0e-46b2-bf47-8553878809a8">

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The videos playing correctly.



![Screen Shot 2023-08-11 at 4 07 31 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/a24360ad-1059-460d-89b9-3f882aee603e)
![Screen Shot 2023-08-11 at 4 07 42 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/2608980d-3a95-44d3-8c95-544ce8e59e93)

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
