### ISSUE TITLE
LeetCode(CN) 【错误的测试用例】2793. 航班机票状态

### ISSUE THREAD

**Issue by theslt** [LeetCode-Feedback/LeetCode-Feedback#15498]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
zilongv

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述**
题目中测试用例4是错误的，不符合题目规定。
题目规定飞机总共就俩坐，虽然都是同时订票的，但三个人都能上去？？？
不考虑实际情况，误导性极强！

**你使用的语言**
MySQL

**你提交或者运行的代码**
```
select
    passenger_id,
    if(capacity >= row_number() over (partition by flight_id order by booking_time), 'Confirmed', 'Waitlist') Status
from passengers
    left join flights using(flight_id)
order by passenger_id;
```

**期望行为**
这是正确的代码，但是不能通过测试用例！相反错误的代码（将上述代码中row_number替换为rank）却能通过代码。

**屏幕截图**
无

**额外的上下文**
无

**Comment by feiceh** [comment]
感谢反馈，当前题目已更新，奖励已发放。
