### ISSUE TITLE
Missing Test Case - 297. Serialize and Deserialize Binary Tree

### ISSUE THREAD

**Issue by giblous** [LeetCode-Feedback/LeetCode-Feedback#15493]
#### Your LeetCode username
giblous

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
Easy to hack the system. Tip is provided in the task.

#### Code you used for Submit/Run operation

```
/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode(int x) : val(x), left(NULL), right(NULL) {}
 * };
 */
class Codec {
public:

    // Encodes a tree to a single string.
// Just changed return type of method from 'string' to 'TreeNode*' to hack the system
    TreeNode* serialize(TreeNode* root) {
        return root;
    }

    // Decodes your encoded data to tree.
    TreeNode* deserialize(TreeNode* data) {
        return data;
    }
};

// Your Codec object will be instantiated and called as such:
// Codec ser, deser;
// TreeNode* ans = deser.deserialize(ser.serialize(root));
```

#### Expected behavior
The dirty hack above should fail. Test framework should punish an attempt to make a joke:
```
Codec ser, deser;
string strigified = ser.serialize(root);  // Compiler error with code above
TreeNode* ans = deser.deserialize(strigified);
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

We redirected it to our developers team but it will take time to fix.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
