### ISSUE TITLE
Misprint in - 518. Coin Change II

### ISSUE THREAD

**Issue by KrishChopra22** [LeetCode-Feedback/LeetCode-Feedback#15506]
#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

##### There are 2 bugs :-
- There are 2 typos in word initialize in the editorial
    Fix : **intialize --> initialize**

- There's just a bracket ']' missing at the end, in the 3rd Approach in the editorial of the problem [518. Coin Change II](https://leetcode.com/problems/coin-change-ii/)
Just add the closing bracket at the end of line.
Fix : 
dp[i][j] = dp[i + 1][j] + dp[i][j - coins[i]    **-->**    dp[i][j] = dp[i + 1][j] + dp[i][j - coins[i]]

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/77012237/c96d4e19-0ba0-49e4-821a-f5ca121cfb74)

*2 bugs found, rewards should be 2x100 == 200 leetcoins?*

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
