### ISSUE TITLE
183. Customers Who Never Order - Accepting input with wrong data type

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1550]
#### Your LeetCode username

[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Accepting incorrect data type in input ->   

![image](https://user-images.githubusercontent.com/71989691/101131116-c6fe1a00-362a-11eb-915f-a04fe50a41a9.png)

#### Code you used for Submit/Run operation

```
# N/A
```

#### Language used for code

MySQL

#### Expected behavior

Should not take incorrect datatype input

#### Additional context

Problem: https://leetcode.com/problems/customers-who-never-order/

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@pratap-082020 Thank you for your time. Our team has been notified of the issue.
