### ISSUE TITLE
Missing Test Case - 653. Two Sum IV - Input is a BST

### ISSUE THREAD

**Issue by ThisisMS11** [LeetCode-Feedback/LeetCode-Feedback#15508]
#### Your LeetCode username
ThisisMS11

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
In the given question as per the constraints the number of nodes that can be present in bst at minimum is 1 so for instance if any bst has just one node let's say it is 5 and the required sum is 10 then the solution that i submitted was getting accepted which it should not have, considering the fact that there is only one node in the bst and same node cannot be taken again in the sum to obtain target but my solution used the same node again to obtain the target . So i think there is a need to introduce test cases with bst having single nodes.

#### Code you used for Submit/Run operation

```
class BSTIterator{
    stack<TreeNode * > st;
    bool isNext=false;
    
    public:
        BSTIterator(TreeNode * root,bool isNext){
            st.push(root);
            this->isNext=isNext;
            if(isNext) pushAll(root->left);
            else pushAll(root->right);
        }
        
        int nextValue(){
            TreeNode * top=st.top();
            st.pop();
            if(isNext)pushAll(top->right);
            else pushAll(top->left);
            return top->val;
        }

        bool hasNext(){
            return !st.empty();
        }

    private:
        void pushAll(TreeNode *root){
            while(root!=NULL){
                st.push(root);
                if(isNext){
                   root=root->left;
                }else{
                    root=root->right;
                }
            }
        }

};
class Solution {
public:
    bool findTarget(TreeNode* root, int k) {
        BSTIterator l(root,true);
        BSTIterator r(root,false);

        int left= l.nextValue();
        int right = r.nextValue();

        while(left < right){
            int sum=left+ right;
            if(sum==k) return true;

            else if(sum < k) left= l.nextValue();
            else right=r.nextValue();
        }

        return false;
    }
};
```

#### Language used for code
C++

#### Expected behavior
The case of bst with single node 5 and required sum = 10 for my solution must have been rejected .

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
