### ISSUE TITLE
587. Erect the Fence - Typo in Editorial

### ISSUE THREAD

**Issue by agrawalishaan** [LeetCode-Feedback/LeetCode-Feedback#15518]
#### Your LeetCode username
agrawalishaan

#### Category of the bug
- [ ] Question
- [X ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the editorial, it writes: `Then, we sort the given set of points based on their polar angles formed w.r.t. a vertical line drawn throught`.

`throught` is a typo, it should say `through`.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
