### ISSUE TITLE
519. Random Flip Matrix - Typo in Editorial

### ISSUE THREAD

**Issue by agrawalishaan** [LeetCode-Feedback/LeetCode-Feedback#15519]
#### Your LeetCode username
agrawalishaan

#### Category of the bug
- [ ] Question
- [ X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the solution, it writes: `Let assume that we are given an array-like`.

It should say `Let's assume`, not `Let assume`.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
