### ISSUE TITLE
197. Rising Temperature - Issue with input test cases

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1551]
#### Your LeetCode username

[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

As mentioned in the problem - id is the primary key for this table Weather. 
But here the problem is accepting a duplicate primary key which is incorrect -

**Input:**
{"headers": {"Weather": ["Id", "RecordDate", "Temperature"]}, "rows": {"Weather": [[1, "2015-01-01", 10],[1, "2015-01-01", 10], [2, "2015-01-02", 25], [3, "2015-01-03", 20], [4, "2015-01-04", 30]]}}

![image](https://user-images.githubusercontent.com/71989691/101133948-a5ebf800-362f-11eb-9571-719d7b0e98ce.png)

Accepting incorrect data type in the input ->

**Input:**
{"headers": {"Weather": ["Id", "RecordDate", "Temperature"]}, "rows": {"Weather": [["1", "2015-01-01", 10], ["2", "2015-01-02", "25"], [3, "2015-01-03", 20], [4, "2015-01-04", 30]]}}

![image](https://user-images.githubusercontent.com/71989691/101134531-899c8b00-3630-11eb-9f43-fcf37245c11d.png)

#### Code you used for Submit/Run operation

```
# N/A
```

#### Language used for code

MySQL

#### Expected behavior

Accepting the duplicate primary key input. which is not possible.
Should accept inputs with correct datatypes. 

#### Additional context

Problem - https://leetcode.com/problems/rising-temperature/

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
