### ISSUE TITLE
622. Design Circular Queue - Typo in Editorial

### ISSUE THREAD

**Issue by agrawalishaan** [LeetCode-Feedback/LeetCode-Feedback#15520]
#### Your LeetCode username
agrawalishaan

#### Category of the bug
- [ ] Question
- [X ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the editorial, it writes: `where the variable capacity is the size of the array, the count is the length of the queue and the headIndex and tailIndex are the indice of head and tail elements respectively in the array.`

It should say `indices`, not `indice`, since it is a plural. `indice` is not even a word.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
