### ISSUE TITLE
被突然禁言删除所有题解和讨论

### ISSUE THREAD

**Issue by jackielics** [LeetCode-Feedback/LeetCode-Feedback#15529]
在没有违规的情况下，我突然被LeetCode中国区被删除了所有题解、讨论，我只是同时在LeetCode.cn和LeetCode.com发布自己做题的题解和讨论，并没有违规，而且我的LeetCode中国区账号还是在Premium会员期内被禁言并清空的，并且还是在从未告知、提醒、警告的情况下，直接清空所有原创的所有题解和讨论，LeetCode中国对用户、对会员的权益漠视到如此程度了吗？
这是我的账号链接：https://leetcode.cn/u/jackie-cs-b/，请尽快与我联系并给出合理解释！否则贵公司将面临诉讼！
<img width="1267" alt="2023-08-12_200144" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/55891169/37c98740-84d1-4301-8100-3ae0e0db7505">

**Comment by nickyhu1895** [comment]
感谢反馈，关于您来信提到的禁言事宜我们已提交至负责团队，已与您通过电话沟通处理。目前禁言已取消，题解和讨论帖的恢复工作将持续与您跟进。
Github 仓库只用于反馈大家在本站学习过程中遇到的题目和题解问题，问题我们先暂时关闭，给您带来的不便敬请谅解。

**Comment by jackielics** [comment]
Jackie
***@***.***





如果一周之内没有恢复被删题解和讨论，将会曝光事件、起诉贵司，以维护自身合法权益，感谢理解。

                       
Original Email
                       
                     

Sender:"nickyhu1895"< ***@***.*** &gt;;

Sent Time:2023/8/13 16:09

To:"LeetCode-Feedback/LeetCode-Feedback"< ***@***.*** &gt;;

Cc recipient:"Jack Lee"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [LeetCode-Feedback/LeetCode-Feedback] 被突然禁言删除所有题解和讨论 (Issue #15529)




 
感谢反馈，关于您来信提到的禁言事宜我们已提交至负责团队，已与您通过电话沟通处理。目前禁言已取消，题解和讨论帖的恢复工作将持续与您跟进。
 Github 仓库只用于反馈大家在本站学习过程中遇到的题目和题解问题，问题我们先暂时关闭，给您带来的不便敬请谅解。
