### ISSUE TITLE
Wrong Test Case - 152. Maximum Product Subarray

### ISSUE THREAD

**Issue by thomastgeorge** [LeetCode-Feedback/LeetCode-Feedback#15534]
#### Category of the bug
- [ ] Question
- [☑️ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Test case number 109 is incorrect as the expected solution isn't a subarray.

#### Code you used for Submit/Run operation

```
// [Maximum Product Subarray]
class Solution {
public:
    int maxProduct(vector<int>& nums) {
        int maxmul = nums[0];
        int currentmax = nums[0]; 
        int i;
        for(i=1; i<nums.size(); i++){
            currentmax = max(currentmax*nums[i], nums[i]);
            maxmul = max(maxmul, currentmax);
        }
        return maxmul;
    }
};
```

#### Language used for code

C++

#### Expected behavior

It should not give an error in test case 109.

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
