### ISSUE TITLE
176. Second Highest Salary - Input data type must be number not string

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1554]
#### Your LeetCode username

[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The expected input data type must be number not string ->

**Input-**
{"headers": {"Employee": ["Id", "Salary"]}, "rows": {"Employee": [["1", "100"], ["5", "400"]]}}

![image](https://user-images.githubusercontent.com/71989691/101164468-0f353080-365b-11eb-8b87-c78c4cec9801.png)

#### Code you used for Submit/Run operation

```
# N/A
```

#### Language used for code

MySQL

#### Expected behavior

The expected input data type must be number not string

#### Additional context

Problem: https://leetcode.com/problems/second-highest-salary/

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@pratap-082020 Thank you for your time. Our team has been notified of the issue.
