### ISSUE TITLE
Wrong Test Case - 165. Compare Version Numbers

### ISSUE THREAD

**Issue by KK-Harjeeth** [LeetCode-Feedback/LeetCode-Feedback#15542]
#### Wrong test cases

####Description 
Test Case 1:
Input
version1 =
"1.100"
version2 =
"1.10"
Output
1
Expected
1
test case 1 is fine because 100>10
TestCase 2
Input
version1 =
"1.2"
version2 =
"1.10"
Output
1
Expected
-1
Here we have to output as "1" because 2<10 , but expected is -1

there is an anomaly between test case 1 and test case 2

#### Code you used for Submit/Run operation

```
class Solution:
    def compareVersion(self, version1: str, version2: str) -> int:
        list1=[]
        list2=[]
        x=""
        for i in version1:
            if(i!='.'):
                x+=i
            else:
                if(list1 and int(x)==0 and list1[-1]==0):
                    x=""
                else:
                    list1.append(int(x))
                    x=""
        if(len(x)>0):
            if(list1 and int(x)==0 and list1[-1]==0):
                x=""
            else:
                list1.append(int(x))
                x=""
        x=""
        for i in version2:
            if(i!='.'):
                x+=i
            else:
                if(list2 and int(x)==0 and list2[-1]==0):
                    x=""
                else:
                    list2.append(int(x))
                    x=""
        if(len(x)>0):
            if(list2 and int(x)==0 and list2[-1]==0):
                x=""
            else:
                list2.append(int(x))
                x=""
        number1="".join(str(i) for i in list1)
        number2="".join(str(i) for i in list2)
        if(number1<number2):
            return -1
        elif(number1>number2):
            return 1
        return 0
```

#### Language used for code
Python

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
