### ISSUE TITLE
Missing Test Case - 1191. K-Concatenation Maximum Sum

### ISSUE THREAD

**Issue by Prashant-dot1** [LeetCode-Feedback/LeetCode-Feedback#1555]
#### Category of the bug
- [ 1191] Question
- [ TEST CASE HAS A PROBLEM] Solution
- [c++ ] Language

#### Description of the bug

Input: arr = [-1,-2], k = 7
Output: 0
How can the answer be 0??? shouldn't it be -1 ?

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
int n=arr.size();
        
        int cur=arr[0];
        int global=arr[0];
        for(int i=1;i<n;i++)
        {
            if(cur >=0) {
                cur +=arr[i];
            }else{
                cur=arr[i];
            }
            
            if(cur > global){
                global=cur;
            }
        }
        return global;
    }
    
    
    int kConcatenationMaxSum(vector<int>& arr, int k) {
        
        int n=arr.size();
        int sum=0;
        for(int i=0;i<n;i++)
        {
            sum+=arr[i];
        }
        
        if(k==1) {
            return kadanes(arr);
        }
        
        else if(sum <0){
            
            vector<int> new_arr(n*2,0);
            for(int i=0;i<n;i++){
                new_arr[i]=arr[i];
            }
            for(int i=0;i<n;i++){
                new_arr[i+arr.size()]=arr[i];
            }
            
            return kadanes(new_arr);
        }
        
        else{
            
            vector<int> new_arr(n*2,0);
            for(int i=0;i<n;i++){
                new_arr[i]=arr[i];
            }
            for(int i=0;i<n;i++){
                new_arr[i+arr.size()]=arr[i];
            }
            
            return kadanes(new_arr)+(k-2)*sum;
        }
        return 0;
    }
    }
};
```

**Comment by lc-kay** [comment]
@Prashant-dot1 Can you please provide the submission details link to your code? Thank you!

**Comment by Prashant-dot1** [comment]
https://leetcode.com/problems/k-concatenation-maximum-sum/submissions/

**Comment by lc-kay** [comment]
@Prashant-dot1 Please click on "Accepted", which will redirect you to the submission details link. The link you provided takes me to the submissions page of the problem.

**Comment by Prashant-dot1** [comment]
https://leetcode.com/submissions/detail/427112053/

**Comment by lc-kay** [comment]
@Prashant-dot1 The expected answer is correct. I'd recommend checking out the hints and discuss tab for this question to get a better understanding. I think the comment under this post will be helpful for you: https://leetcode.com/problems/k-concatenation-maximum-sum/discuss/954349/Please-clear-my-doubt!
