### ISSUE TITLE
Missing Test Case - 2722. Join Two Arrays by ID

### ISSUE THREAD

**Issue by DeltaZN** [LeetCode-Feedback/LeetCode-Feedback#15552]
#### Your LeetCode username
user2347jM

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
There is no test case for unsorted input arrays

#### Code you used for Submit/Run operation
```
[2722. Join Two Arrays by ID](https://leetcode.com/problems/join-two-arrays-by-id/)
var join = function(arr1, arr2) {
    // arr1.sort((a, b) => a.id - b.id);
    // arr2.sort((a, b) => a.id - b.id);
    const result = [];
    let i = 0; let j = 0;
    while (i < arr1.length && j < arr2.length) {
        const el1 = arr1[i];
        const el2 = arr2[j];
        if (el1.id < el2.id) {
            result.push(el1);
            i++;
        } else if (el2.id < el1.id) {
            result.push(el2);
            j++;
        } else {
            const newObj = {
                ...el1,
                ...el2,
            }
            result.push(newObj);
            i++; j++;
        }
    }
    for (; i < arr1.length; i++) {
        result.push(arr1[i]);
    }
    for (; j < arr2.length; j++) {
        result.push(arr2[j]);
    }
    return result;
};
```

#### Language used for code
JavaScript

#### Expected behavior
A solution without sorting input arrays should be rejected

#### Additional context
an example of a test case
```
Input
[{"id": 2,"x": 9},{"id": 1,"x": 1}]
[{"id": 3,"x": 5}]

Output:
[{"id":2,"x":9},{"id":1,"x":1},{"id":3,"x":5}]
Expected:
[{"id":1,"x":1},{"id":2,"x":9},{"id":3,"x":5}]
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
