### ISSUE TITLE
Checking for existence Document : Example Problem 3

### ISSUE THREAD

**Issue by ZE0TRON** [LeetCode-Feedback/LeetCode-Feedback#15559]
#### Your LeetCode username
ZE0TRON

#### Category of the bug
- [ X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

On the page : 
https://leetcode.com/explore/interview/card/leetcodes-interview-crash-course-data-structures-and-algorithms/705/hashing/4511/

The example problem 3 is given as following:

Example 3: Given an integer array nums, find all the numbers x that satisfy the following: x + 1 is not in nums, and x - 1 is not in nums.

The problem doesn't mention x should be in the nums array itself. Since the other criteria is not being in the nums for x+1 and x-1, x has infinitely many possible values. 

#### Code you used for Submit/Run operation

-

#### Language used for code

-

#### Expected behavior

The solution acts like x is in the nums array, please update the question to include that statement otherwise it's wrong.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
