### ISSUE TITLE
Missing Test Case - 2818. Apply Operations to Maximize Score

### ISSUE THREAD

**Issue by DmitryAk** [LeetCode-Feedback/LeetCode-Feedback#15555]
#### Your LeetCode username

dm_a

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

The submitted solution was accepted, but it gives TLE on the test case:
https://leetcode.com/problems/apply-operations-to-maximize-score/submissions/1019983057/ 
Test case: [TC2818-17.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/12328979/TC2818-17.txt)

#### Code you used for Submit/Run operation

```
class Solution {
public:
    const vector<int> primes = {2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313};
    vector<int> memo = vector<int>(100001, -1);

    int getScore(const int n) {
        if (memo[n] != -1) return memo[n];
        if (n == 1) return memo[n] = 0;

        int result = 0;
        int rest = n;
        for (int p : primes) {
            if (rest < p) break;

            if (rest % p == 0) {
                ++result;
                while (rest % p == 0) {
                    rest /= p;
                }
            }
        }
        return memo[n] = result + (rest > 1);
    }

    const int modulo = 1000000007;

    int power(long long x, long long y)
    {
        if (y == 0) return 1;

        long long temp = power(x, y / 2);
        temp = temp * temp % modulo;
        if ((y % 2) == 0) return temp;
        
        return x * temp % modulo;
    }

    int maximumScore(vector<int>& nums, int k) {
        const int n = nums.size();
        vector<int> indexes(n);
        iota(begin(indexes), end(indexes), 0);
        sort(begin(indexes), end(indexes), [&nums](int i, int j){
            return nums[i] > nums[j];
        });
        vector<int> score;
        for (int num : nums) {
            score.push_back(getScore(num));
        }
        long long result = 1;
        for (int i : indexes) {
            int l = i-1;
            int r = i+1;
            while (l >= 0 && score[l] < score[i]) {
                --l;
            }
            while (r < n && score[r] <= score[i]) {
                ++r;
            }
            
            long long mn = min(k, (i - l) * (r - i));
            k -= mn;
            result = (result * power(nums[i], mn)) % modulo;
            if (k == 0) return result;
        }
        return result;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The solution should not be accepted. It has O(N^2) time complexity, should not be accepted with given constraints.

#### Additional context

The test case:
[TC2818-17.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/12328979/TC2818-17.txt)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
