### ISSUE TITLE
Q3 passes with brute force solution - Weekly Contest 358 - 2817. Minimum Absolute Difference Between Elements With Constraint

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#15568]
#### Category of the bug
- [ ] Question
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

Q3 question must not pass a brute force solution, but it passes for today contest

Contest - https://leetcode.com/contest/weekly-contest-358/ranking/
Q3 question - https://leetcode.com/contest/weekly-contest-358/problems/minimum-absolute-difference-between-elements-with-constraint/

Links
- https://leetcode.com/problems/minimum-absolute-difference-between-elements-with-constraint/submissions/1020198429/
- https://leetcode.com/problems/minimum-absolute-difference-between-elements-with-constraint/solutions/3901816/javascript-brute-force/

#### Code you used for Submit/Run operation

```
var minAbsoluteDifference = function(nums, x) {
    let min = Infinity;
   
    for(let i = 0; i < nums.length; i++) {
        for(let j = i+x; j < nums.length; j ++) {
            if(Math.abs(i - j) >= x) {
                min = Math.min(min, Math.abs(nums[i] - nums[j]));
            }
        }
    }
    return min;
};
```

#### Expected behavior
A Q3 question in contest must be tougher than Q1 & Q2
However Q3 passes even with a brute force solution

Time constraints for JavaScript are too lenient, but must be tighter
Currently passes even with 10+ seconds.

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/8236389/8227c5df-e726-4d26-aa45-6b28628c85c9)

**Comment by venkateshwar-1996** [comment]
wait what 
<img width="407" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/51945078/353b52d2-8b86-49a4-8f77-90dd2b938fd3">
