### ISSUE TITLE
Wrong solution for a testcase - 29. Divide Two Integers

### ISSUE THREAD

**Issue by gurocoro** [LeetCode-Feedback/LeetCode-Feedback#15564]
#### Category of the bug
- [ ] Question
- [ x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

There is a testcase: dividend = -2147483648 and divisor = -1 which states that the correct solution is 2147483647 which obviously is not the case. My code returns 2147483648 (which is right) and says it is a wrong answer.

#### Code you used for Submit/Run operation

```
/**
 * @param {number} dividend
 * @param {number} divisor
 * @return {number}
 */
var divide = function(dividend, divisor) {
    let negative = false;
    if (dividend<0){
        dividend = -dividend;
        negative = !negative;
    }
    if (divisor<0){
        divisor = - divisor;
        negative = !negative;
    }
    var c=divisor;
    var p = 1;
    var doubles = [[c,p], [c,p]];
    var quotient = 0;
    while(doubles.length>=1){
        if(dividend-c<c){
            if(dividend>=c){
                quotient += p;
                dividend = dividend - c;
            }
            let pair = doubles.shift();
            c = pair[0];
            p = pair[1];
        }else{
            c+=c;
            p+=p;
            doubles.unshift([c,p]);
        }
    }
    return negative ? -quotient : quotient
};
```

#### Language used for code

Javascript

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by gurocoro** [comment]
Well, it wasn’t accepted because my code gave (the true right answer) 2147483648 as I said and the expected one was 2147483647. The submission link is https://leetcode.com/submissions/detail/1020141026/

![IMG_2763](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/64547089/8b54008e-3d7d-4ceb-9015-c0e9668f8d30)

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
