### ISSUE TITLE
Binary Tree Maximum Path Sum

### ISSUE THREAD

**Issue by J-Whitfield** [LeetCode-Feedback/LeetCode-Feedback#1556]
#### Your LeetCode username

jewhitfi

#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language

#### Description of the bug

Binary tree with maximum path sum is yielded 48 for the array below.
However if you start at root and traverse down the total is 55.
[5,4,8,11,null,13,4,7,2,null,null,null,1] 

#### Code you used for Submit/Run operation

Java

#### Expected behavior

I expected the answer to be 55

#### Screenshots

![Screen Shot 2020-12-04 at 7 55 14 AM](https://user-images.githubusercontent.com/44040257/101166467-52b17f80-3606-11eb-91e1-ee03875425d4.png)

**Comment by lc-kay** [comment]
@J-Whitfield The same question was raised here and answered by one of our user! Please check it out https://leetcode.com/problems/binary-tree-maximum-path-sum/discuss/658044/Wrong-Test-Case
https://leetcode.com/problems/binary-tree-maximum-path-sum/discuss/349683/Wrong-test-case
https://leetcode.com/problems/binary-tree-maximum-path-sum/discuss/463051/Need-help-understanding-a-test-case
