### ISSUE TITLE
Missing Test Case - Weekly Contest 358 - 2817. Minimum Absolute Difference Between Elements With Constraint

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#15570]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Test case below

Download Test case from below file:
https://raw.githubusercontent.com/manoharreddyporeddy/programming-language-notes/master/tests/Q3-2817-TLE-Testcase.txt

#### Code you used for Submit/Run operation

```
var minAbsoluteDifference = function(nums, x) {
    let min = Infinity;
   
    for(let i = 0; i < nums.length; i++) {
        for(let j = i+x; j < nums.length; j ++) {
            if(Math.abs(i - j) >= x) {
                min = Math.min(min, Math.abs(nums[i] - nums[j]));
            }
        }
    }
    return min;
};
```

#### Expected behavior
A brute force solution must not pass Q3

#### Screenshots

1 Without above test case - passes:
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/8236389/e418bdbd-b12c-4bb9-915a-3a6e678bfe2c)

https://leetcode.com/problems/minimum-absolute-difference-between-elements-with-constraint/submissions/1020198429/
https://leetcode.com/problems/minimum-absolute-difference-between-elements-with-constraint/solutions/3901816/javascript-brute-force/

2 With above test case - fail:
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/8236389/c3fa8540-88d2-455c-af3e-f95e69122fbf)

**Comment by manoharreddyporeddy** [comment]
See linked ticket https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/15568

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
