### ISSUE TITLE
Missing Test Case - 15. 3Sum

### ISSUE THREAD

**Issue by RohanKhatua** [LeetCode-Feedback/LeetCode-Feedback#15582]
#### Your LeetCode username
ainvader

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Code gets flagged with 
```
Line 1034: Char 34: runtime error: addition of unsigned offset to 0x6020000000f0 overflowed to 0x6020000000ec (stl_vector.h)
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/stl_vector.h:1043:34
```
despite compiling correctly with a g++ 11.3.0 compiler

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<vector<int>> threeSum(vector<int>& nums) {
        vector<int> pos;
        vector<int> neg;
        vector<vector<int>> ans;

        if ((int)nums.size()<=2) return ans;

        //size 3 array

        if ((int)nums.size()==3) {
            if (accumulate(nums.begin(),nums.end(),0)==0) {
                ans.push_back(nums);
                return ans;
            }
        }

        int zero=0;
        for (int num:nums) {
            if (num>0) {
                pos.push_back(num);
            }
            else if (num==0) {
                zero++;
            }
            else {
                neg.push_back(num);
            }
        }

        sort(pos.begin(), pos.end());
        sort(neg.begin(), neg.end());

        if (zero>0) {
            int pt1 = pos.size()-1;
            int pt2 = 0;

            while (pt1>=0 && pt2<neg.size()) {

                if (pos[pt1]==abs(neg[pt2])) {
                    ans.push_back({pos[pt1], neg[pt2], 0});
                    pt1--;
                    pt2++;
                }

                if (pos[pt1]>abs(neg[pt2])) {
                    pt1--;
                }

                else {
                    pt2++;
                }
            }
        }

        //now to generate triplets which do not involve a 0
        //we get 2 positive numbers and 1 neg number or 1 positive and 2 neg


        //if only one -ve number -> we can only do 2 +ve 1 -ve

        if ((int)neg.size()>1) {
                int pt1 = 0;
                int pt2 = neg.size()-1;
            for (int num:pos) {



                int val = num+neg[pt1] +  neg[pt2];
                if (val ==0) {
                    ans.push_back({num, neg[pt1], neg[pt2]});
                    continue;
                }
                else if (val<0){
                    pt1++;
                }
                else {
                    pt2--;
                }
            }
        }

        if ((int)pos.size()>1) {

                int pt1 = 0;
                int pt2 = pos.size()-1;
            for (int num:neg) {
                int val = num+pos[pt1]+pos[pt2];
                if (val==0) {
                    ans.push_back({num, pos[pt1], pos[pt2]});
                    continue;
                }
                else if (val<0) {
                    pt1++;
                }
                else {
                    pt2--;
                }
            }   
        } 
        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior

The code should not encounter a runtime error - and compile for the visible test cases. It may encounter a WA verdict later but it should at least compile.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/90958884/15157db2-8ce7-4812-8678-9583a986b83a)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/90958884/e78e87f1-f838-46dd-bf08-44e4f04d2ac2)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/90958884/085ebee4-2302-4926-a812-f8afae2b3e09)

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
