### ISSUE TITLE
Wrong Test Case - 2662. Minimum Cost of a Path With Special Roads

### ISSUE THREAD

**Issue by anshu11n** [LeetCode-Feedback/LeetCode-Feedback#15580]
#### Your LeetCode username
anshu11n

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] wrong answer on a paticular test case i.e test case 610.

#### Description of the bug

Answer should be 7, as it is the minimum path but given answer is 8
Path ->
 (1,1)->(1,2) : cost=1
 (1,2)->(6,1)) : cost=3 spec road
(6,1)->(10,3) : cost=2 special road
(10,3)->(10,4) : cost=1
answer = 1+3+2+1 = 7 , smaller than the expected value.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
