### ISSUE TITLE
Missing Test Case - 66. Plus One

### ISSUE THREAD

**Issue by blurry17** [LeetCode-Feedback/LeetCode-Feedback#1558]
#### Your LeetCode username
huamanyauri

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language

#### Description of the bug
the prompt says "You may assume the integer does not contain any leading zero, except the number 0 itself." but i got [0,0] I dont know if its intended or not

#### Code you used for Submit/Run operation

```
var plusOne = function(digits) {
    let z = true;
    for(let i = digits.length-1; i>=0; i--){
        if(z){
            if(digits[i]==9){
                digits[i] = 0;
            }else{
                digits[i]++;
                z = false;
            }
        }
    }
    if(digits[0]==0) digits.unshift(1)
    return digits;
};
```

#### Language used for code
Javascript

#### Expected behavior
I got test input [0,0], i think it should only be [0]

#### Screenshots
![image](https://user-images.githubusercontent.com/35975570/101223685-96ce6f80-365a-11eb-8e11-a386eea40d8a.png)

**Comment by lc-kay** [comment]
@blurry17 This was an intended test case, please check out this post in the discuss tab for a great explanation by a user. https://leetcode.com/problems/plus-one/discuss/933685/Why-is-00-in-the-test-set In addition, the test case's expected output is correct, as 00 + 1 = 01
