### ISSUE TITLE
Missing Test Case - 1517. Find Users With Valid E-Mails

### ISSUE THREAD

**Issue by Yashika0511** [LeetCode-Feedback/LeetCode-Feedback#15593]
#### Your LeetCode username

yashikabajaj0511

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [-] Missing Test Cases 

#### Description of the bug

the answer accepted gave wrong output for certain testcase which was missing.

#### Code you used for Submit/Run operation

```
# Write your MySQL query statement below
SELECT * FROM Users WHERE mail REGEXP '^[a-zA-Z][a-zA-Z0-9_.-]*@leetcode[.]com';

```

#### Language used for code

MySQL

#### Expected behavior

the answer should not have gotten accepted.

#### Screenshots

![Screenshot (33)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/114306924/8900ecde-4fd4-4052-a91c-f7ac34ddd6d9)
![Screenshot (34)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/114306924/f13deee0-9384-4a7b-af86-54ba3faa0e85)
![Screenshot (35)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/114306924/43c167a4-c983-4db5-b5d2-d92317dd2f99)

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
