### ISSUE TITLE
Missing Test Case - 1517. Find Users With Valid E-Mails

### ISSUE THREAD

**Issue by ajitpal0821** [LeetCode-Feedback/LeetCode-Feedback#15591]
#### Your LeetCode username
ajitpal0821

#### Category of the bug
-Missing Test Case 

#### Description of the bug

1 | Winston | winston@leetcode?com |
above testcase should not work as domain is not correct as per question ,but  it is showing accepted answer.

#### Code you used for Submit/Run operation

```
select user_id,name,mail from Users where REGEXP_LIKE(mail,'^[a-zA-Z][a-zA-Z0-9_.-]*@leetcode.com')
```

#### Language used for code

MySQL

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/107208518/04b75cc1-ff45-4911-a2c7-d6903cca7cb2)

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process. https://leetcode.com/submissions/detail/1022399348/
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
