### ISSUE TITLE
Missing Test Case - 490. The Maze

### ISSUE THREAD

**Issue by Ming91** [LeetCode-Feedback/LeetCode-Feedback#15596]
#### Your LeetCode username

[wming9310](https://leetcode.com/wming9310/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I file this issue not because of a bug but as inspiration from the solution from [DFS : Java Solution; Time O(mn); Space O(mn)](https://leetcode.com/problems/the-maze/solutions/3402098/dfs-java-solution-time-o-mn-space-o-mn/). But I think the code did not implement the whole idea. I implemented this idea and improved it so that each point was visited at most 4 times.  But it got slower than simple DFS.

Here is a simple example that can show the advantages of this solution:
```
// **********
// **4     3*
// ** ***** *
// ** **s** *
// **5  1  2*
// *******e**
// **********

test case format:
[[0, 0, 0, 0, 0, 0, 0], [0, 1, 1, 1, 1, 1, 0], [0, 1, 1, 0, 1, 1, 0], [0, 0, 0, 0, 0, 0, 0], [1, 1, 1, 1, 1, 0, 1]]
[2, 3]
[4, 5]
```

As you can see, suppose the order of visited points is s-1-2-3-4-5-2. In simple DFS, this path stops after 5-2. But using this approach, it will stop at 1 when the ball is from 5 to 1. Because the direction from 5 to 1 is the same as 1 to 2, which is visited in the earlier path. So this method can achieve an early stop in this problem.

When the distance of 1-2 is long and 5-1 is short, the advantage of this method is more obvious. You may visit the same part of a line multiple times in this problem and waste time. However, constructing these kinds of complex test cases that can show the differences between these two methods is beyond my ability. 

So I wish the LeetCode team could take this scenario into consideration and construct some test cases that can show the differences.

Best wishes.

#### Code you used for Submit/Run operation

```Java
class Solution {
    static final int[][] DIR = new int[][] {
        {0, 1}, {0, -1},
        {1, 0}, {-1, 0}
    };

    int[] dest;
    int[][] g;
    boolean[][][] visited;
    int m;
    int n;
    boolean isValid(int x, int y) {
        if (x < 0 || y < 0 || x >= m || y >= n) {
            return false;
        }
        if (g[x][y] == 1) {
            return false;
        }
        return true;
    }
    boolean dfs(int x, int y, int di) {
        if (isValid(x + DIR[di][0], y + DIR[di][1])) {
            if (visited[x + DIR[di][0]][y + DIR[di][1]][di]) {
                return false;
            }
            visited[x + DIR[di][0]][y + DIR[di][1]][di] = true;

            return dfs(x + DIR[di][0], y + DIR[di][1], di);
        }
        // if not hit the wall, the ball won't stop
        if (x == dest[0] && y == dest[1]) {
            return true;
        }
        for (int ii = di + 1; ii < di + 4; ii++) {
            int i = ii % 4;
            
            int[] d = DIR[i];

            int xx = x + d[0], yy = y + d[1];
            
            if (isValid(xx, yy) && !visited[xx][yy][i]) {
                visited[xx][yy][i] = true;
                if (dfs(xx, yy, i)) {
                    return true;
                }
            }
        }
        return false;
    }

    public boolean hasPath(int[][] maze, int[] start, int[] destination) {
        m = maze.length;
        n = maze[0].length;
        
        dest = destination;
        g = maze;
        // check if it's a dead end
        boolean up = isValid(dest[0] - 1, dest[1]);
        boolean down = isValid(dest[0] + 1, dest[1]);
        boolean left = isValid(dest[0], dest[1] - 1);
        boolean right = isValid(dest[0], dest[1] + 1);
        if (up == down && left == right) {
            return false;
        }
        visited = new boolean[m][n][4];
        for (int i = 0; i < 4; i++) {
            visited[start[0]][start[1]][i] = true;
            if (dfs(start[0], start[1], i)) {
                return true;
            }
        }
        return false;
    }
}
```

#### Language used for code

Java

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
