### ISSUE TITLE
Missing Test Case - 215. Kth Largest Element in an Array

### ISSUE THREAD

**Issue by Tudor67** [LeetCode-Feedback/LeetCode-Feedback#15590]
#### Your LeetCode username

[Tudor67](https://leetcode.com/Tudor67/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My (inefficient) solution passed all the test cases and was accepted,
but I found two test cases that exceed the time limit (TLE).

__---------- *(TLE) Test Case 1 (only duplicates)* ----------__
__*Input:*__
```
[1,1,1,1,1, ..., 1,1,1]
50000
```
The input vector `nums` contains `100 000` elements equal to `1`;
The input parameter `K` is `50 000`;

__*Output:*__ `Time Limit Exceeded`
__*Expected:*__ `1`
**_Test File 1 (.txt)_**: [test1.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/12337013/test1.txt)
__------------------------------------------------------------__

__---------- *(TLE) Test Case 2 (many duplicates, few unique elements)* ----------__
__*Input:*__
```
[1,2,3,4,5,1,1,1,1,1,1, ..., 1,1,1,1,-5,-4,-3,-2,-1]
50000
```
The input vector `nums` contains `100 000` elements (most of them are equal to `1`);
`nums` = `[1,2,3,4,5]` + `[1,1,1,1,1,1,1, ..., 1,1,1,1,1]` + `[-5,-4,-3,-2,-1]`;
The input parameter `K` is `50 000`;

__*Output:*__ `Time Limit Exceeded`
__*Expected:*__ `1`
**_Test File 2 (.txt)_**: [test2.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/12337044/test2.txt)
__-------------------------------------------------------------------------------------__

#### Code you used for Submit/Run operation

[Submission Link](https://leetcode.com/problems/kth-largest-element-in-an-array/submissions/1021221850/)
``` C++
// 215. Kth Largest Element in an Array
// C++
class Solution {
private:
    void quickSelect(vector<int>& v, const int L, const int K, const int R){
        if(L >= R){
            return;
        }

        int randIndex = L + rand() % (R - L + 1);
        swap(v[randIndex], v[R]);

        int pivot = v[R];
        int l = L;
        int r = R - 1;
        while(l <= r){
            if(v[l] < pivot){
                l += 1;
            }else{
                swap(v[l], v[r]);
                r -= 1;
            }
        }

        swap(v[l], v[R]);
        int pivotIndex = l;

        // Partition:
        // v[L .. pivotIndex - 1] < pivot
        // v[pivotIndex] == pivot
        // v[pivotIndex + 1 .. R] >= pivot

        if(pivotIndex == K){
            return;
        }else if(pivotIndex < K){
            quickSelect(v, pivotIndex + 1, K, R);
        }else if(K < pivotIndex){
            quickSelect(v, L, K, pivotIndex - 1);
        }
    }

public:
    int findKthLargest(vector<int>& nums, int k) {
        const int N = nums.size();

        vector<int> v = nums;
        srand(time(nullptr));
        quickSelect(v, 0, N - k, N - 1);

        return v[N - k];
    }
};
```

#### Language used for code

C++

#### Expected behavior

Time Limit Exceeded

#### Screenshots

![Prob_215_TLE](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/12481060/565c04c4-f8df-45e0-9adc-b343e86f45ec)

#### Additional context

When the input vector `nums` contains many duplicates, the above solution runs in `O(N^2)` time.
It is not enough to use `standard quick select` + `random selection of pivot` + `partition of subarray into 2 subarrays` to pass the TLE test cases.

To pass the TLE test cases we need `standard quick select` + `random selection of pivot` + `partition of subarray into 3 subarrays`.
Why? `partition of subarray into 3 subarrays` is better than `partition of subarray into 2 subarrays` for input vectors with duplicates.

**partition of subarray into 2 subarrays**:
`v[L .. pivotIndex - 1] < pivot`
`v[pivotIndex] == pivot`
`v[pivotIndex + 1 .. R] >= pivot`

||

`v[L .. pivotIndex - 1] < pivot`
 `v[pivotIndex .. R] >= pivot`

**partition of subarray into 3 subarrays**:
`v[L .. pivotFirstIndex - 1] < pivot`
`v[pivotFirstIndex .. pivotLastIndex] == pivot`
`v[pivotLastIndex + 1 .. R] > pivot`

The solution with **partition of subarray into 3 subarrays** (that passes all the test cases): [Submission Link (Fast Quick Select)](https://leetcode.com/problems/kth-largest-element-in-an-array/submissions/1021232906/)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

test2 added

test1 rejected

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
