### ISSUE TITLE
Missing Test Case - Weekly Contest 358 - 2817. Minimum Absolute Difference Between Elements With Constraint

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#15597]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Test case below

Download Test case from below file:
https://raw.githubusercontent.com/manoharreddyporeddy/programming-language-notes/master/tests/Q3-2817-TLE-Testcase.txt

#### Code you used for Submit/Run operation

```
/**
 * @param {number[]} nums
 * @param {number} x
 * @return {number}
 */
var minAbsoluteDifference = function(nums, x) {
    let min=Infinity;
    for(let i=0;i<nums.length;i++){
        for(let j=i+x;j<nums.length;j++){
            min=Math.min(min,Math.abs(nums[i]-nums[j]));
        }
    }
    return min
};
```

#### Expected behavior
A brute force solution must not pass Q3

#### Screenshots

1 Without above test case - passes:

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/8236389/9b0d83c2-e796-4ad2-b941-c12148ffa4e8)

See - https://leetcode.com/problems/minimum-absolute-difference-between-elements-with-constraint/solutions/3907182/minimum-absolute-difference-between-elements-with-constraint/

2 With above test case - fail:
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/8236389/86bc9891-32bf-45f0-aa32-a37170d13a63)

**Comment by manoharreddyporeddy** [comment]
Note that
this solution given above
is different
from given in https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/15570 ( this is fixed properly )

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

We can't add the test case currently because of technical issues.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
