### ISSUE TITLE
【面试题 01.02. 判定是否互为字符重排】测试用例不全

### ISSUE THREAD

**Issue by AlainConnor** [LeetCode-Feedback/LeetCode-Feedback#156]
**Bug 类型**
- [x] 题目
- [ ] 编程语言
- [x] 题解

**描述**
测试用例不全，导致错误代码也可以通过提交

**你使用的语言**
JAVA，但问题与语言无关

**你提交或者运行的代码**
```
class Solution {
    public boolean CheckPermutation(String s1, String s2) {
        if (s1 == null || s2 == null) {
            return false;
        }
        int length = s1.length();
        if (length != s2.length()) {
            return false;
        }
        int result = 0;
        char[] s1Char = s1.toCharArray();
        char[] s2Char = s2.toCharArray();
        for (int i = 0; i < s1Char.length; i++) {
            result = result ^ s1Char[i] ^ s2Char[i];
        }
        return result == 0;
    }
}
```

**期望行为**
输入：
"aa"
"bb"
输出：
上面的代码输出：true
正确的输出应该为：false

**额外的上下文**
该代码取自高赞题解，这两个都是错误的思路，问题在于测试用例考虑不全面
https://leetcode-cn.com/problems/check-permutation-lcci/solution/yi-huo-yun-suan-shi-jian-fu-za-du-onkong-jian-fu-z/
https://leetcode-cn.com/problems/check-permutation-lcci/solution/c-shuang-bai-by-he-fei-si-tuo-si-r/

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认的～

**Comment by feiceh** [comment]
该问题当前已修复，感谢支持力扣，祝好。
