### ISSUE TITLE
Missing Test Case - 73. Set Matrix Zeroes

### ISSUE THREAD

**Issue by vaibhav1865** [LeetCode-Feedback/LeetCode-Feedback#15602]
#### Your LeetCode username
v1865v

#### Category of the bug
-  Problem : 73. Set Matrix Zeroes
- Solution -> Add a testCase : [[-2147481325],[2],[3]]

-  Language : C++
- Missing Test Cases : [[-2147481325],[2],[3]]

#### Description of the bug

So the Bug is if i solve the question using a place Holder (some number between INT_MIN to INT_MAX let's say -2147481325 , question would get accepted  , which is wrong .

#### Code you used for Submit/Run operation

```
// Set Matrix Zeroes(https://leetcode.com/problems/set-matrix-zeroes/)
class Solution {
public:
#define PlaceHolder 2323
    void flagRowCol(int row , int col ,vector<vector<int>> & matrix){
        for(int j = 0 ; j < matrix[0].size() ; j++ ){
            if(matrix[row][j] != 0)
                matrix[row][j] = INT_MIN + PlaceHolder ;
        }
         for(int i = 0 ; i < matrix.size() ; i++ ){
             if(matrix[i][col] != 0)
                 matrix[i][col] = INT_MIN + PlaceHolder ;
        }
    }



    void setZeroes(vector<vector<int>>& matrix) {
        
        for(int i = 0 ; i < matrix.size(); i++ ){
            for(int j = 0 ; j < matrix[0].size() ; j++ ){
                if(matrix[i][j] == 0){
                    flagRowCol(i,j,matrix);
                    matrix[i][j] = INT_MIN + PlaceHolder ;
                }
            }
        }
      
        for(int i = 0 ; i < matrix.size(); i++ ){
            for(int j = 0 ; j < matrix[0].size() ; j++ ){
                // cout<<matrix[i][j]<<" ";
                if(matrix[i][j] == INT_MIN + PlaceHolder ){
                    matrix[i][j] = 0;
                }
            }
            // cout<<endl;
        }

    }
};
```

#### Language used for code

C++

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by vaibhav1865** [comment]
Any updates on my bounty for the bug?

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
