### ISSUE TITLE
Missing Test Case - 27. Remove Element

### ISSUE THREAD

**Issue by hrcn** [LeetCode-Feedback/LeetCode-Feedback#1560]
#### Your LeetCode username

realruihan

#### Category of the bug
- Question
- [ ] Solution
- [ ] Language

#### Description of the bug

In Example 2, the output should be `Output: 5, nums = [0,1,3,0,4]`

**Comment by lc-kay** [comment]
Hi @hrcn 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@hrcn The problem description stated: "Note that the order of those five elements can be arbitrary. It doesn't matter what values are set beyond the returned length." In this example, we explain that any order is accepted.
