### ISSUE TITLE
Missing Test Case - 179. Largest Number

### ISSUE THREAD

**Issue by Mayankk104** [LeetCode-Feedback/LeetCode-Feedback#15605]
#### Your LeetCode username

Mayankk104

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

expected to fail for at least one test case for [179. Largest Number](https://leetcode.com/problems/largest-number/) but it got accepted event after a mistake in the submitted code.

I suggest to add this input in test cases [9, 99, 9989, 99]

#### Code you used for Submit/Run operation

``` c++
bool sorting_logic(int a,int b){
    return to_string(a)+to_string(b) > to_string(b)+to_string(a);
}
class Solution {
    public:
        string largestNumber(vector<int>& A) {
            sort(A.begin(), A.end(), sorting_logic);

            string result = "";

            if(A[0]==0) return "0";
            for(auto num: A) result += to_string(num);
            return result; 
        }
};
```

#### Language used for code

C++

#### Expected behavior

to fail for test case at least one testcase for [179. Largest Number](https://leetcode.com/problems/largest-number/) but it got accepted

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/37512010/5dfe2a89-6e6b-46b8-ab80-569b7530d2ba)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

[9, 99, 9989, 99] already exists. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
