### ISSUE TITLE
86. Partition List --> Problem during compiling solution

### ISSUE THREAD

**Issue by HarshAggarwal1** [LeetCode-Feedback/LeetCode-Feedback#15607]
#### Your LeetCode username
Harsh_2510

#### Category of the bug
Solution

#### Description of the bug
Hi, I wanted to raise an error for the problem mentioned in title. I am getting wrong result during compilation on Leetcode, but when I am running the same code on my PC, it is giving correct answer. Please look into the issue.

#### Code you used for Submit/Run operation
```
public class Solution {
   public static ListNode partition(ListNode head, int x) {
        if (head == null || head.next == null) {
            return head;
        }
        
        ListNode prev = new ListNode(-1);
        prev.next = head;
        head = null;

        ListNode curr = prev, hasNext = prev;

        while (hasNext.next != null) {
            if (hasNext.next.val < x) {
                ListNode temp = new ListNode(hasNext.next.val);
                hasNext.next = hasNext.next.next;
                temp.next = curr.next;
                curr.next = temp;
                curr = curr.next;
            }
            hasNext = hasNext.next;
        }

        return prev.next;
    }
}

```

#### Language used for code
JAVA

#### Expected behavior
My code is generating correct output on my PC, so it might me compiler issue on Leeetcode. Please look into it once.

#### Screenshots

![Screenshot 2023-08-15 172634](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/88721766/15ee7073-35e7-419d-ad9e-4778611c282a)

![Screenshot 2023-08-15 172657](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/88721766/35288b98-6d1e-47e2-b146-6697e5b9f578)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us! Unfortunately, we are unable to troubleshoot the different behavior between your local IDE and the LeetCode environment.

For this issue, please raise this as a discuss post in the problem discuss section as other users may have run into the same issue and resolved it.

At LeetCode, we care about the whole learning experience that comes with each problem and we encourage users to teach and help each other to enrich their learning. In addition, we want our users to debug their code and learn from the process.

We appreciate your time and support.
