### ISSUE TITLE
Missing Test Case - 162. Find Peak Element

### ISSUE THREAD

**Issue by Mragang-Jain** [LeetCode-Feedback/LeetCode-Feedback#15613]
#### Your LeetCode username
mragangjain

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

```
 nums = [1,2,1,3,5,4,7,6,4]
 Expected = 4

```

#### Code you used for Submit/Run operation

```
var findPeakElement = function(nums) {
    const maxValue = Math.max(...nums)
    return  nums.findIndex((item) =>{ return item === maxValue})
}

```

#### Language used for code
 Javascript

#### Expected behavior

```
  Output should be 6
```

#### Screenshots

<img width="1440" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/58897741/eb8de9ce-96f9-4189-8195-efe426b0425e">

#### Additional context
 When I tried to submit O(log n) Solution in Javascript

```
var findPeakElement = function(nums) {
    let left = 0;
  let right = nums.length - 1;

  while (left < right) {
    const mid = Math.floor((left + right) / 2);
    if (nums[mid] > nums[mid + 1]) {
      right = mid;
    } else {
      left = mid + 1;
    }
  }

  return left;
};

```
It shows result.

<img width="1435" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/58897741/9f24bf8c-89ab-46ee-93f0-8e6edb8f9a3f">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've used your feedback to check the problem.

The team decided to reject this feedback after the evaluation.

Please ask your question in the discussion forum.

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!
