### ISSUE TITLE
Wrong Test Case - 2660. Determine the Winner of a Bowling Game

### ISSUE THREAD

**Issue by likhitavarma** [LeetCode-Feedback/LeetCode-Feedback#15619]
#### Your LeetCode username
 Likhitavarma 

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
2660.Determine the Winner of a Bowling Game

There is issue with one of the testcase
Wrong Answer
1199 / 1205 testcases passed
[Editorial](https://leetcode.com/problems/determine-the-winner-of-a-bowling-game/editorial?source=submission-noac)
Input
player1 =
[7,10,2,6,8,5,4,6,10,9,1,4,3,10,0,9,6,1,0]
player2 =
[2,1,9,4,5,0,6,5,6,10,10,4,8,8,6,9,2,9,5]

Use Testcase
Output
1
Expected
2

The score for player1 is 7 + 10 + 2*2 +6*2 + 8 + 5 + 4 + 6 + 10 + 9*2 + 1*2 + 4 + 3 + 10 + 0*2 + 9*2 +6 + 1 = 128
The score for player2 is 2 + 1 + 9 + 4 + 5 + 0 + 6 + 5 + 6 + 10 + 10*2 + 4*2 + 8 + 8 + 6 + 9 + 2 + 9 + 5 = 123
Here score of player 1 is greater than player 2 so output would be 1. But expected output is given 2 which is incorrect output.
This is the bug.

#### Code you used for Submit/Run operation

```
class Solution:
    def calculateScore(self,p: List[int]) -> int:
        flag = 0
        score = 0 
        c = 0
        for i in p:
            if flag:

                if c < 2:
                    score += i*2
                    c += 1
                else:
                    flag = 0
                    score += i
                    c = 0

            else:
                score += i

            if i == 10:
                flag = 1
                
        return score

    def isWinner(self, player1: List[int], player2: List[int]) -> int:
        p1 = self.calculateScore(player1)
        p2 = self.calculateScore(player2)
        if p1 == p2:
            return 0
        elif p1 > p2:
            return 1
        else:
            return 2

```

#### Language used for code
Python3 

#### Expected behavior
The score for player1 is 7 + 10 + 2*2 +6*2 + 8 + 5 + 4 + 6 + 10 + 9*2 + 1*2 + 4 + 3 + 10 + 0*2 + 9*2 +6 + 1 = 128
The score for player2 is 2 + 1 + 9 + 4 + 5 + 0 + 6 + 5 + 6 + 10 + 10*2 + 4*2 + 8 + 8 + 6 + 9 + 2 + 9 + 5 = 123
Here score of player 1 is greater than player 2 so output would be 1. But expected output is given 2 which is incorrect output.
So, 1 should be the expected output for this testcase. 

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/96068821/7152d157-b030-4a93-988b-53352ac362ee)

#### Additional context
None

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
