### ISSUE TITLE
[212] Missing Test case - Word Search II 

### ISSUE THREAD

**Issue by AmyPlace** [LeetCode-Feedback/LeetCode-Feedback#1561]
** Bug 类型**
- [212 ] 题目 單詞搜尋 2
- [ ] 题解
- [ ] 编程语言

**描述**
期望增加test case
[["o","a","a","n"],["e","t","a","e"],["i","h","k","r"],["i","f","l","v"]]
["oath","oet"]

**你使用的语言**
Java

**你提交或者运行的代码**

**期望行为**

**屏幕截图**

**额外的上下文**

**Comment by feiceh** [comment]
感谢反馈，请说明一下增加这个 test case 的原因，如果会影响现在能够 AC 的代码，请按照本文中提到的格式分享上述代码，把信息提供完整才能有助于快速验证和精准的定位这个问题。
