### ISSUE TITLE
283. Move Zeroes bug

### ISSUE THREAD

**Issue by Z2Flow** [LeetCode-Feedback/LeetCode-Feedback#15616]
#### Your LeetCode username
Zeff

#### Category of the bug
- [ ] Question
- [ x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

LeetCode flagged my solution as outputting the same array as the input array.

#### Code you used for Submit/Run operation

```
def move_zeroes(nums)
  result = []
  return result if nums.length == 0
  count = 0
  nums.each do | num |
    if num != 0
      result << num
    else
      count += 1
    end
  end
  for i in 0...count
    result << 0
  end
  result
end
```

#### Language used for code

Ruby

#### Expected behaviour

I expected the output for the example test case to transform the input array from:
```
[0,1,0,3,12]
```
to:
```
[1,3,12,0,0]
```

#### Additional context

On my Mac running Ruby 3.2.2, the result is correct:
```
[1,3,12,0,0]
```

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team

**Comment by Z2Flow** [comment]
Can you please explain why using Ruby 3.2.2 on my Mac produced the correct result to example 1, from the problem description, and when submitting it to your site, it was in error?
