### ISSUE TITLE
ListNode questions should have nodes wrapped in Rc->RefCell

### ISSUE THREAD

**Issue by andrewtoth** [LeetCode-Feedback/LeetCode-Feedback#15621]
#### Your LeetCode username
andrewtoth

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
For `TreeNode` questions, the nodes are properly wrapped as `Option<Rc<RefCell<TreeNode>>>`, which makes sense to allow for multiple ownership and interior mutability. However, for `ListNode` questions, the nodes are wrapped as `Option<Box<ListNode>>`, which does not allow for multiple ownership and interior mutability. This makes solving the problem much less idiomatic and requires creating new types using raw pointers (see https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/6864).

#### Code you used for Submit/Run operation
For problem https://leetcode.com/problems/partition-list
```
// Definition for singly-linked list.
// #[derive(PartialEq, Eq, Clone, Debug)]
// pub struct ListNode {
//   pub val: i32,
//   pub next: Option<Box<ListNode>>
// }
// 
// impl ListNode {
//   #[inline]
//   fn new(val: i32) -> Self {
//     ListNode {
//       next: None,
//       val
//     }
//   }
// }
impl Solution {
    pub fn partition(head: Option<Box<ListNode>>, x: i32) -> Option<Box<ListNode>> {
        
    }
}
```

#### Language used for code
Rust

#### Expected behavior
For example, this question should be written as this (note also the `mut` keyword before the parameter name).
```
// Definition for singly-linked list.
// use std::rc::Rc;
// use std::cell::RefCell;
//
// #[derive(PartialEq, Eq, Clone, Debug)]
// pub struct ListNode {
//   pub val: i32,
//   pub next: Option<Rc<RefCell<ListNode>>>
// }
// 
// impl ListNode {
//   #[inline]
//   fn new(val: i32) -> Self {
//     ListNode {
//       next: None,
//       val
//     }
//   }
// }
impl Solution {
    pub fn partition(mut head: Option<Rc<RefCell<ListNode>>>, x: i32) -> Option<Rc<RefCell<ListNode>>> {
        
    }
}
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've used your feedback to check the problem.

We redirected it to our developers team but it will take time to fix.

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!
