### ISSUE TITLE
Multiple orderings accepted for AlienDictionary

### ISSUE THREAD

**Issue by gauravgulzar** [LeetCode-Feedback/LeetCode-Feedback#1562]
#### Your LeetCode username
gavaarg

#### Category of the bug
- [ X] Test cases
- [ X] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Looks like there is bug in test cases for [alien dictionary problem](https://leetcode.com/problems/alien-dictionary/)- 
Example -
["abc","acdef"]

Here we can only conclude that 'b' will come before 'c' in the alphabet. For rest of the letters, we don't have enough data to conclude their orderings. Currently, if we return any order for them, the solution is accepted.

["wrt","wrtkj"]
Expected: "jkrtw"

Shouldn't such test cases be invalid given valid alphabets must have one and only one ordering? If this is not the case, this should be clearly specified in the problem.

#### Expected behavior
As such test cases are not sufficient to determine valid ordering, empty string should be treated as correct answer.

**Comment by lc-kay** [comment]
Hi @gauravgulzar 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@gauravgulzar After carefully reviewing your report, our team ruled that the returned answer is valid, while the given relations are satisfied. Thank you for your time!
