### ISSUE TITLE
94. 二叉树的中序遍历 题解描述错误：方法三Morris 中序遍历中时间复杂度分析描述

### ISSUE THREAD

**Issue by jiangp000** [LeetCode-Feedback/LeetCode-Feedback#15629]
**Bug 类型**
- [ ] 题解

复杂度分析

时间复杂度：O(n)，其中 n 为**二叉搜索树**的节点个数。Morris 遍历中每个节点会被访问两次，因此总时间复杂度为 O(2n)=O(n)
空间复杂度：O(1)

这里应该是二叉树的结点个数，而非二叉搜索树的结点个数，

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/49073225/e8591c44-b49e-415d-b65e-9ebdac63327b)

**Comment by feiceh** [comment]
你好，当前题解已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by jiangp000** [comment]
效率真高啊，本人是：leetcode.cn/u/jiang000/
