### ISSUE TITLE
Missing Test Case - 523. Continuous Subarray Sum

### ISSUE THREAD

**Issue by akshatmaheshwar** [LeetCode-Feedback/LeetCode-Feedback#15636]
#### Your LeetCode username

akshatmaheshwar78

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I got TLE for this testcase for my code when I ran it myself but the code got accepted when submitted.

#### Code you used for Submit/Run operation

```
// Continuous Subarray Sum
class Solution {
    public boolean checkSubarraySum(int[] nums, int k) {
       for(int i =nums.length-1;i>=0;i--){
           double sum = nums[i];
           for(int j=i-1;j>=0;j--){
               if(j<nums.length-1&&nums[j]==0&&nums[j]==nums[j+1]){
                   return true;
               }
               if((sum+(double)nums[j])%k==0){
                   return true;
               }
               sum+=(double)nums[j];
           }
           if(sum<k){
               break;
           }
       }
        return false;
    }
}
```

#### Language used for code

JAVA

#### Expected behavior

I expected to get a TLE but the code got accepted.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/77718425/106f533e-b703-422b-97f7-766a12536046)

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/77718425/1c88c8d9-9a45-4d0d-aec7-bbd2f755bf2b)

#### Additional context
The Missing Test Case is 
[Missing Test Case - 523. Continuous Subarray Sum.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/12356081/Missing.Test.Case.-.523.Continuous.Subarray.Sum.txt)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
