### ISSUE TITLE
Typo in - 2781. Length of the Longest Valid Substring

### ISSUE THREAD

**Issue by YogeshP93** [LeetCode-Feedback/LeetCode-Feedback#15635]
#### Your LeetCode username

https://leetcode.com/Baymax_/

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Typo in "Example 1" of [2781. Length of the Longest Valid Substring](https://leetcode.com/problems/length-of-the-longest-valid-substring/)
There is a statement `There are 11 valid substrings in word: "c", "b", "a", "ba", "aa", "bc", "baa", "aab", "ab", "abc"and "aabc"`
_**There is no space between closing double-quote and the word 'and'.**_

#### Expected behavior

**_There should be a space after the closing double-quote for clear statement/semantic._**
Like this: `There are 11 valid substrings in word: "c", "b", "a", "ba", "aa", "bc", "baa", "aab", "ab", "abc" and "aabc"`

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/122779284/0d9e9609-4a06-400e-95a5-e26f3a43bdf0)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
