### ISSUE TITLE
401. Binary Watch: grammatical mistake in description

### ISSUE THREAD

**Issue by nineonine** [LeetCode-Feedback/LeetCode-Feedback#15630]
#### Your LeetCode username
dnox

#### Description of the bug
https://leetcode.com/problems/binary-watch/

description says:
```
The minute must be consist of two digits and may contain a leading zero.
```

The verb "be" is unnecessary in this context. It should be
```
The minute must consist of two digits and may contain a leading zero.
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
