### ISSUE TITLE
Testcase Missing: 306 Additive Number

### ISSUE THREAD

**Issue by Shanay-Mehta** [LeetCode-Feedback/LeetCode-Feedback#15649]
#### Your LeetCode username

shanay_mehta

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

99999999999999999099999999999999999 , this testcase is missing

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by Shashank-singh2002** [comment]
<img width="451" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/104620107/e472f7f2-bb24-436f-8d4e-df5a1954d083">

An Accepted Testcase
