### ISSUE TITLE
Missing Test Case - 73. Set Matrix Zeroes

### ISSUE THREAD

**Issue by BhavyaMPatel** [LeetCode-Feedback/LeetCode-Feedback#15640]
#### Your LeetCode username
BhavyaMPatel

#### Category of the bug

- [ ] Missing Test Cases 

#### Description of the bug

I Write Solution For Question No [73. Set Matrix Zeroes](https://leetcode.com/problems/set-matrix-zeroes/) I know My Solution Has Bug For Some TestCase And Will Not Run But, LeetCode Dont Have That Edge Test Case And Code Passes Perfectly , I ReCheck Problem Constraint But My Test Case FullFill The All Requirement So I Fill That This Test Case Should Include For This Question
[[0,2147483647,2,0],[3,2147483646,5,2],[1,3,1,5]]

#### Code you used for Submit/Run operation

```
class Solution {
public:
    void setZeroes(vector<vector<int>>& matrix) {
        //The Given Code Works Fine But I Have Some Test Case Where It Fails
        long long Value=0;bool negflag=false,posflag=false;
        for(int i=0;i<matrix.size();i++){
            for(int j=0;j<matrix[i].size();j++){
                if(matrix[i][j]==INT_MAX){
                    matrix[i][j]=INT_MAX-1;
                    posflag=true;
                }
                if(matrix[i][j]==INT_MIN){
                    matrix[i][j]=INT_MIN+1;
                    negflag=true;
                }
            }
        }
        for(int i=0;i<matrix.size();i++){
            for(int j=0;j<matrix[i].size();j++){
                if(matrix[i][j]==0){
                    for(int k=0;k<matrix[i].size();k++){
                        Value=0;
                        Value=Value+INT_MAX+matrix[i][k];
                        if(Value>INT_MAX){
                            matrix[i][k]=INT_MAX;
                        }else if (Value==INT_MAX){
                            matrix[i][k]=0;
                        }else if (Value<INT_MAX){
                            matrix[i][k]=INT_MIN;
                        }
                    }

                    for(int k=0;k<matrix.size();k++){
                        Value=0;
                        Value=Value+INT_MAX+matrix[k][j];
                        if(Value>INT_MAX){
                            matrix[k][j]=INT_MAX;
                        }else if (Value==INT_MAX){
                            matrix[k][j]=0;
                        }else if(Value<INT_MAX){
                            matrix[k][j]=INT_MIN;
                        }
                    }

                }
            }
        }
        for(int i=0;i<matrix.size();i++){
            for(int j=0;j<matrix[i].size();j++){
                if(matrix[i][j]==INT_MAX || matrix[i][j]==INT_MIN){
                    matrix[i][j]=0;
                }
            }
        }
        for(int i=0;i<matrix.size();i++){
            for(int j=0;j<matrix[i].size();j++){
                if(matrix[i][j]==INT_MAX-1 && posflag){
                    matrix[i][j]=INT_MAX;
                }
                if(matrix[i][j]==INT_MIN+1 && negflag){
                    matrix[i][j]=INT_MIN;
                }
            }
        }


        
    }
};
```

#### Language used for code
C++ 

#### Screenshots

<h2>My Submitted Code Works Fine</h2>

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/100468926/f98b0a98-47ba-47e5-8ba5-515592aef6a1)

<h2>My Submitted Code Fail On My Test Case </h2>
Test Case

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/100468926/a3c1200f-fdcb-4c7a-ab8f-a513d81fadf8)

#### Additional context

Look Into This Test Case 
[[0,2147483647,2,0],[3,2147483646,5,2],[1,3,1,5]] 
Thank You

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
