### ISSUE TITLE
239. Sliding Window Maximum 

### ISSUE THREAD

**Issue by sergey135** [LeetCode-Feedback/LeetCode-Feedback#15644]
#### Your LeetCode username

* userName : ivv135uk

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Problem : https://leetcode.com/problems/sliding-window-maximum/

For some reason the solution in kotlin using the monoqueue is taking the most time, hence the time complexity should be O(n).
The queue.size will not be bigger then O(k)

#### Code you used for Submit/Run operation
```
class Solution {

    //Sliding Window Maximum
    //https://leetcode.com/problems/sliding-window-maximum/
    //time : O(n)
    //space: O(k)
    fun maxSlidingWindow(nums: IntArray, k: Int): IntArray {

        val list = mutableListOf<Int>()
        val queue = ArrayDeque<Int>()

        for(i in 0 until nums.size){
            
            if(queue.size > 0 && i - queue.first() >= k){
                queue.removeFirst()
            }

            while(queue.size > 0 && nums[queue.last()] < nums[i]){
                queue.removeLast()
            }
            
            queue.addLast(i)
                        
            if(i + 1 < k){
                continue
            }
            
            list.add(nums[queue.first()])
            
        }

        return list.toIntArray()
        
    }
}
```

#### Language used for code

* Kotlin

#### Expected behavior

Looks like this solution should be fine.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've used your feedback to check the problem.

The team decided to reject this feedback after the evaluation.

Please ask your question in the discussion forum.

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!
