### ISSUE TITLE
30

### ISSUE THREAD

**Issue by lavanya3366** [LeetCode-Feedback/LeetCode-Feedback#15646]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by Shashank-singh2002** [comment]
Invalid Issue
