### ISSUE TITLE
Missing Test Case - 334. Increasing Triplet Subsequence

### ISSUE THREAD

**Issue by kkaratapanis** [LeetCode-Feedback/LeetCode-Feedback#15654]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution:
    def increasingTriplet(self, nums: List[int]) -> bool:
        n = len(nums)
        if n<3:
            return False
        
        s = 0
        m = 0
        l = 0
        val_s = nums[s]
        while s<n:
           
            while(nums[s]>=nums[s+1]):
                s+=1
                if s>n-2:
                    return False
            m = s+1
            l = m+1
            if l>n-1:
                
                return False
            if nums[m]<nums[l]:
                return True
            while(nums[l-1]>=nums[l]):
                l+=1
                if l>n-1:
                    
                    return False
            if nums[m]<nums[l]:
                return True
            elif nums[s]<nums[l-1]<nums[l]:
                return True
            elif nums[s]<nums[l-2]<nums[l]:
                return True
            else:
                s = l-1
           







```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by kkaratapanis** [comment]
Hello, 

missing test cases [3,7,5,3,2,1,6] , [5,9,6,5,4,3,2,1,7]


My  program does not solve these correctly, but it solves the existing ones.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've used your feedback to update the problem.

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback.

Please send us your LCUS or LCCN username.

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!

**Comment by kkaratapanis** [comment]
Hello,

My LCUS username is jukas, and the associated email is kkratapanis@gmail.com

Thanks a lot!
