### ISSUE TITLE
Course illustration are not available

### ISSUE THREAD

**Issue by yehorchernenko** [LeetCode-Feedback/LeetCode-Feedback#15657]
#### Your LeetCode username

egoriy

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Course

#### Description of the bug

Illustration in [Interview-crash-course-data-structures-and-algorithms](https://leetcode.com/explore/interview/card/leetcodes-interview-crash-course-data-structures-and-algorithms/707/traversals-trees-graphs/) are not loaded. 

#### Screenshots

<img width="1025" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/23559375/3056ca60-a00a-41a9-a39e-debb4957f12a">

#### Additional context

Seems that CDN that you are using for the content in this course is not available from Indonesia.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

![Screen Shot 2023-08-17 at 2 57 12 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/b8a41c5e-85b8-496a-bd07-eaaa80afe3a8)

![Screen Shot 2023-08-17 at 2 57 03 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/22e6d9e1-75cd-4648-9886-aed9ae232783)

The course working correctly. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by yehorchernenko** [comment]
The issue is not fixed. I can't play videos from Indonesia, consider to change video hosting.

**Comment by yehorchernenko** [comment]
@LC-Pam  The issue is not fixed. I can't play videos from Indonesia, consider to change video hosting.
