### ISSUE TITLE
执行错误-88. 合并两个有序数组

### ISSUE THREAD

**Issue by poipo-ly** [LeetCode-Feedback/LeetCode-Feedback#15661]
**你的 LeetCode 用户名**
qui2zical-napier

**Bug 类型**
- [ ] 题目
- [*] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
我编写完代码后进行了一次“运行”操作，不过我的代码编写有问题，导致测试用例未通过。于是我修改了导致错误发生的代码后再次执行，结果仍然是“未通过”,但是我确信代码没有问题，于是我在浏览器的控制台和本地Node上都执行了相同的代码和测试用例，结果是通过的。于是我将函数中的返回值直接返回null，测试用例的结果居然还是我第一次错误提交的那个结果。如下图所示，我直接返回null，执行结果显示输出[1,2,3,0,0,0]。
在我刷新和更换浏览器后，问题依然能复现。

**你使用的语言**
JavaScript

**你提交或者运行的代码**
```
var merge = function(nums1, m, nums2, n) {
    return null;
};
```

**期望行为**
输出根据代码修改而改变

**屏幕截图**
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/65220050/3070d018-5d11-42df-ae51-6d5397daf3cb)

https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/65220050/2cc4e3be-54d6-431c-9a2c-afe5966b9696

**Comment by amcones** [comment]
您好，在与相关团队核实后：***不处理***（本题为 `void` 函数，最后检查的是 `nums1` 数组的值，而不是函数的返回值。也就是说，合并后数组不应由函数返回，而是存储在数组 `nums1` 中）。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
