### ISSUE TITLE
Missing info in - 542. 01 Matrix

### ISSUE THREAD

**Issue by YogeshP93** [LeetCode-Feedback/LeetCode-Feedback#15660]
#### Your LeetCode username

https://leetcode.com/Baymax_/

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Missing info in - [542. 01 Matrix](https://leetcode.com/problems/01-matrix/)
Here it mentions `Given an m x n binary matrix mat, return the distance of the nearest 0 for each cell. The distance between two adjacent cells is 1.`
But unlike in other questions (ex: [329. Longest Increasing Path in a Matrix](https://leetcode.com/problems/longest-increasing-path-in-a-matrix/)) It is not mentioned here whether `adjacent cell` means 4-directional cells or 8 directional (4 sides + 4 diagonals)

This leads to confusion... and only by going through 2nd example or by running custom test case, it can be understood that this problem wants us to consider only 4 directional cells.

It will provide more clarity/context if this info is mentioned.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've used your feedback to check the problem.

The team decided to reject this feedback after the evaluation.

Please ask your question in the discussion forum.

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!
