### ISSUE TITLE
leetcode beginers guid doesn't work video

### ISSUE THREAD

**Issue by YernarSm** [LeetCode-Feedback/LeetCode-Feedback#15669]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by YernarSm** [comment]
Веб-страница по адресу https://player.vimeo.com/video/701460602, возможно, временно недоступна или постоянно перемещена по новому адресу.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

![Screen Shot 2023-08-17 at 3 00 48 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/b0b9be19-206f-4dfd-bca5-b308f002a4a1)


The videos playing correctly on the course.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
