### ISSUE TITLE
1383. Maximum Performance of a Team - Error in Question

### ISSUE THREAD

**Issue by agrawalishaan** [LeetCode-Feedback/LeetCode-Feedback#15676]
#### Your LeetCode username
agrawalishaan

#### Category of the bug
- [ X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the question, it writes: `The performance of a team is the sum of their engineers' speeds multiplied by the minimum efficiency among their engineers.`.

It should say:

`The performance of a team is the sum of its engineers' speeds multiplied by the minimum efficiency among its engineers.`

Since `team` is singular.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
