### ISSUE TITLE
Error encountered, works in vs code

### ISSUE THREAD

**Issue by Jeff-Norris** [LeetCode-Feedback/LeetCode-Feedback#15683]
#### Your LeetCode username
<Jeff-Norrs>

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution(object):
    def merge(self, nums1, m, nums2, n):
        """
        :type nums1: List[int]
        :type m: int
        :type nums2: List[int]
        :type n: int
        :rtype: None Do not return anything, modify nums1 in-place instead.
        """
        i=0
        j=0
        while j<len(nums2):
            print(i, nums1[i], j, nums2[j])
            print(j)
            if nums2[j]<=nums1[i]:
                print(nums1[i], nums2[j])
                nums1.insert(i, nums2[j])
                nums1.pop()
                j=j+1
                i=i+1
            elif nums1[i]==0 and nums1[i-1]>0:
                print(j)
                nums1.insert(i, nums2[j])
                nums1.pop()
                i=i+1
                j=j+1
            else:
                i=i+1
                    
```

#### Language used for code
<python>

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
