### ISSUE TITLE
1907. Count Salary Categories - Time Limit Exceeded for MS SQL (T-SQL)

### ISSUE THREAD

**Issue by AgentIvan** [LeetCode-Feedback/LeetCode-Feedback#15682]
#### Your LeetCode username
AgentIvan

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Time limit exceeded for any possible solution

#### Code you used for Submit/Run operation

```
/* Write your T-SQL query statement below */
with Categorised_Accounts as (
  SELECT
  COUNT(account_id) as 'accounts_count',
  (
    CASE
      WHEN income < 20000 THEN 1
      WHEN income BETWEEN  20000 AND  50000 THEN 2
      WHEN income > 50000  THEN 3
    END
  ) category_id
  FROM
  Accounts
  GROUP BY CASE
      WHEN income < 20000 THEN 1
      WHEN income BETWEEN  20000 AND  50000 THEN 2
      WHEN income > 50000  THEN 3
    END
),

Categories as (
  SELECT 1 AS id, 'Low Salary' AS category union
  SELECT 2 AS id, 'Average Salary' AS category union
  SELECT 3 AS id, 'High Salary' AS category
)

-- SELECT category_id, accounts_count FROM Categorised_Accounts

SELECT category, ISNULL(accounts_count, 0) AS accounts_count
FROM Categories
LEFT JOIN Categorised_Accounts ON id = category_id
```
[submission1](https://leetcode.com/problems/count-salary-categories/submissions/1024154045)
[submission2](https://leetcode.com/problems/count-salary-categories/submissions/1024150468)
[submission3](https://leetcode.com/problems/count-salary-categories/submissions/1024306308)
[submission4](https://leetcode.com/problems/count-salary-categories/submissions/1022912601)
[submission5](https://leetcode.com/problems/count-salary-categories/submissions/1022919481)
#### Language used for code
T-SQL

Note: MySQL, Oracle and Pandas works fine

#### Expected behaviour
Test cases used that can be solved

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/16723960/df220774-9a7f-486d-84e5-6c92ef80139a)

#### Additional context
Fallen test case I'll add in comment

**Comment by AgentIvan** [comment]
Note that the issue #14098 was ignored

**Comment by AgentIvan** [comment]
it's impossible to add test case:
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/16723960/b225a182-fc93-4758-883d-21af7a4d668d)
please use it from [submission1](https://leetcode.com/problems/count-salary-categories/submissions/1024154045)

**Comment by LC-Pam** [comment]
Since we have not heard from you for 5 days regarding the issue https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/14098, we closed the ticket. It was not ignored.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
