### ISSUE TITLE
Missing Test Case - 14. Longest Common Prefix

### ISSUE THREAD

**Issue by svenriksen** [LeetCode-Feedback/LeetCode-Feedback#15689]
#### Your LeetCode username

kaisvenriksen

#### Category of the bug

- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases

#### Code you used for Submit/Run operation

```C++
// Two Sum
class Solution {
public:
    string longestCommonPrefix(vector<string>& strs) {
        string res = strs[0];

        int j = 0;
        int minn = strs[0].size();
        for (string &x: strs)
        {
            j = 0;
            for (int i = 0; i < min(x.size(), res.size()); i++)
            {
                if (res[i] == x[i])
                    j++;
                else
                {
                    minn = min(minn, j);
                    break;

                }

            }
            // cout <<j<<endl;
            res="";
            for (int j=0;j<minn;j++)
            {
                res+=x[j];
            }
        }
        return res;
    }
};
```

#### Language used for code

C++

#### Expected behavior

My return value and the expected value is the same, however the judge said it was wrong.

#### Screenshots

![Screenshot](https://i.imgur.com/8VuKrvt.png)

**Comment by YogeshP93** [comment]
Hey - I hope you are talking about the problem - [14. Longest Common Prefix](https://leetcode.com/problems/longest-common-prefix/)

I simply copied your code and ran it. It seems there is issue in your code.
Check the screenshot below to observe the diff b/w expected-output and your-output (there is a blank character in the end)

![Screenshot 2023-08-18 090537](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/122779284/ba91ec56-9ff4-43fa-bbec-651185c0a604)

**Comment by svenriksen** [comment]
Hi, thank you for pointing out to me that there was an issue in my code.

However, it is weird that the judge on my side did not display the extra whitespace or runtime error when I ran that test case.

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
