### ISSUE TITLE
Testcase issue in - 1615. Maximal Network Rank

### ISSUE THREAD

**Issue by YogeshP93** [LeetCode-Feedback/LeetCode-Feedback#15690]
#### Your LeetCode username

https://leetcode.com/Baymax_/

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the question - [1615. Maximal Network Rank](https://leetcode.com/problems/maximal-network-rank/)
Constraints mention - `Each pair of cities has at most one road connecting them.`
This just means that the graph formed with the given input is a 'Connected' graph, i.e., there are no disconnected components.

However, for this question we can still form/use/run such test cases where the input can form disconnected graph.
Due to the constraint mentioned, it should not be allowed to run/test such test cases.

#### Expected behavior

It should not be allowed to run/use such test cases due to the constraint mentioned. Such test cases should be invalidated, or an exception has to be thrown just like we have seen in other problems where the test case input doesn't bind to the constraints.
[OR]
Simply remove the constraint statement (as it is not employed/validated with test cases).

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/122779284/cb079ada-75cb-4e3e-ab6c-3b5aad408979)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
