### ISSUE TITLE
Question Difficulty is wrong - 572. Subtree of Another Tree

### ISSUE THREAD

**Issue by YogeshP93** [LeetCode-Feedback/LeetCode-Feedback#15694]
#### Your LeetCode username

https://leetcode.com/Baymax_/

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Difficulty level for the question - [572. Subtree of Another Tree](https://leetcode.com/problems/subtree-of-another-tree/)
It is mentioned as 'Easy', but it should be 'Medium". Here's why:
In the editorial, we see 3 approaches to solve this problem.

1. DFS
Here, in order to check if the given tree (sub-root) is a subtree of the tree (root), we need to check if any of the sub-tree of tree (root) is 'identical' with the tree (sub-root)
We already have a problem - to identify if the trees are identical (https://leetcode.com/problems/same-tree/) and **_it's difficulty level is 'Easy' already_**.
2. StringMatching
Here, in order to perform the string matching logic, we need to serialize the tree.
We already have a problem - to serialize/deserialize tree (https://leetcode.com/problems/serialize-and-deserialize-binary-tree/) and **_it's difficulty level is 'Hard' already._**
3. Hashing
Here, the logic of performing hashing of the tree itself is not easy, hence **_this approach should also be Medium_**.

#### Expected behavior

**_Due to complexities of the sub-problem that we need to solve, this should be considered 'Medium' instead of 'Easy'._**

#### Screenshots

![Screenshot 2023-08-18 105619](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/122779284/232cef50-1854-4a8f-a4a3-7d542757fd1c)
![Screenshot 2023-08-18 105630](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/122779284/aca9081a-b156-47a4-a2ff-c04bba1cac3c)
![Screenshot 2023-08-18 105641](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/122779284/4b6d2347-bd61-4a73-88db-4a738fc597e1)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
