### ISSUE TITLE
Can't send any solution in Rust for "Number of islands" problem

### ISSUE THREAD

**Issue by AnthonyMikh** [LeetCode-Feedback/LeetCode-Feedback#157]
**What kind of the bug**
- [x] problem
- [ ] solution
- [x] language

**Describe the bug**
It is impossible to run nor submit any solution of "Number of islands" problem of 30-Day LeetCoding Challenge in Rust **using "old" interface**. Trying to do so triggers a compile error caused by code injected on server side.

**what language is your code written in**
Rust

**The code you submit/run**
```
impl Solution {
    pub fn num_islands(map: Vec<Vec<char>>) -> usize {
        // Pretty much everything will work
        // as long as it doesn't trigger any error on itself
        0
    }
}
```

**Expected behavior**
Sent solution is run against test case and result is returned.

**Additional context**
The exact error reported upon using "Run Code":
```
Line 40, Char 23: no method named `serialize` found for type `usize` in the current scope (solution.rs)
   |
40 |         let out = ret.serialize();
   |                       ^^^^^^^^^ method not found in `usize`
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
9 | use serde::ser::Serialize;
   |
error: aborting due to previous error
```
Adding `use serde::ser::Serialize;` into solution doesn't solve the problem:
```
Line 6, Char 5: failed to resolve: use of undeclared type or module `serde` (solution.rs)
  |
6 | use serde::ser::Serialize;
  |     ^^^^^ use of undeclared type or module `serde`
Line 41, Char 23: no method named `serialize` found for type `usize` in the current scope (solution.rs)
   |
41 |         let out = ret.serialize();
   |                       ^^^^^^^^^ method not found in `usize`
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
6  | use serde::ser::Serialize;
   |
error: aborting due to 2 previous errors
```
Submitting a solution yields the same output

**Comment by CooperCooperCooper** [comment]
Hi @AnthonyMikh,
Thank you for reaching out to us. The code definition for "[Number of Islands](https://leetcode.com/problems/number-of-islands/)" should look like this

```
impl Solution {
    pub fn num_islands(grid: Vec<Vec<char>>) -> i32 {
        
    }
}
```
You may use the middle icon (see screenshot attached) on the top right of the Explore Card editor to reset the code definition and build you code on it. Here's an [AC Rust solution](https://leetcode.com/problems/number-of-islands/discuss/268517/Rust-DFS-recursive(4ms)) that works for this problem. Hope this helps.

**Comment by AnthonyMikh** [comment]
I am sorry, I missed a crucial detail: the problem can be reproduced reliably in "old" LeetCode intarface but doesn't happen if solution is sent via "new" LeetCode interface. This probably helps to narrow down the place where an error occurs.

**Comment by CooperCooperCooper** [comment]
Hi @AnthonyMikh,
Thank you for the clarification! I've relayed this to our team to investigate. Meanwhile, please try to use te new LeetCode interface :) We appreciate your support and understanding.

**Comment by CooperCooperCooper** [comment]
Hi @AnthonyMikh,
Thank you for your time. Our team found both old and new UI has the code definition for this problem. If you're still experiencing an issue with this problem, please share screenshot(s) of the issue with us here for us to take a further look. We appreciate your time and support.
