### ISSUE TITLE
Incorrect Test Case - 115. Distinct Subsequences

### ISSUE THREAD

**Issue by MasterDJ23** [LeetCode-Feedback/LeetCode-Feedback#15705]
#### Your LeetCode username
 Dev_Juneja_23

#### Category of the bug
- [ ] Question 
- [ ] Solution
- [ ] Language
- [ ] Incorrect Test Cases 

#### Description of the bug
 There is a test case which is giving incorrect output. It is a serious issue as it is leading to confusion for candidates while they are practicing on the edge cases of the problem. The test case which was causing the issue is: 
s = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
t = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

#### Code you used for Submit/Run operation

```
// Distinct Subsequences
class Solution {
    Integer[][] memo = new Integer[1001][1001];
    public int numDistinct(String s, String t) {
        int n = s.length();
        int m = t.length();
        char[] c1 = s.toCharArray();
        char[] c2 = t.toCharArray();
        return helper(c1, c2, 0, 0);
    }
    public int helper(char[] c1, char[] c2, int i, int j){
        if(i == c1.length || j == c2.length) return 0;
        if(memo[i][j] != null) return memo[i][j];
        int ans = 0;
        if(j == c2.length - 1 && c1[i] == c2[j]) ans = 1;
        int b = 0;
        if(c1[i] == c2[j]) b = helper(c1, c2, i + 1, j + 1);
        return memo[i][j] = helper(c1, c2, i + 1, j) + b + ans; 
    }
}
```

#### Language used for code
 Java

#### Expected behavior
 The problem is with a testcase. It is giving incorrect results during custom testing, although the code is accepted and passes all the testcases in the problem. It is a serious issue as it can confuse the users and could make them question the integrity of the platform. Kindly review it and correct the issue.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/88589454/a14f9aa6-3f89-4b6b-a381-3470ba716a0d)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by aayushsingla** [comment]
Can confirm this. There is an issue with this exact test case. Question mentions that `The test cases are generated so that the answer fits on a 32-bit signed integer` but it doesn't comply with this.

Stack trace:
<img width="885" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/31629114/3d04877c-29da-410f-9505-17210c96eeb2">

Code:
<img width="566" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/31629114/ac2b4007-b13f-4bfa-8cea-f013158cbb88">

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
