### ISSUE TITLE
Missing Test Case - 605. Can Place Flowers

### ISSUE THREAD

**Issue by Nikhil3698** [LeetCode-Feedback/LeetCode-Feedback#1570]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Question is missing some test cases for which wrong code is accepted.
 Test Case - [1,0,0,0,0,0,0,0,1]  n=3 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool canPlaceFlowers(vector<int>& a, int x) {
        int n = a.size(),i;
         int prev=-2;   
        int count=0;
        for(int i=0;i<n;i++)
        {
          if(a[i])
           { 
               if(i-prev > 4)                              
                   count += (i-prev)/4 + ((i-prev) - ((i-prev)/4)*4)/2 ;                                  
               else if(i-prev == 4)
                   count += 1; 
               
             prev = i;
           }
        }
        if(n+1-prev > 4)                              
                   count += 1 + ((n+1-prev) - 4)/2;                                  
               else if(n+1-prev == 4)
                   count += 1;
        
        return count>=x;
    }
};
```

**Comment by lc-kay** [comment]
@Nikhil3698 Please provide the test case that this solution fails on. Thank you!

**Comment by Nikhil3698** [comment]
> @Nikhil3698 Please provide the test case that this solution fails on. Thank you!

Test Case - [1,0,0,0,0,0,0,0,1] n=3

**Comment by lc-kay** [comment]
Hi @Nikhil3698 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Nikhil3698 
Thank you for your time. We've used your feedback to update the problem. Please provide me with your LeetCode ID to receive your 100 LeetCoins as a reward. We appreciate your support!

**Comment by Nikhil3698** [comment]
> Hi @Nikhil3698
> Thank you for your time. We've used your feedback to update the problem. Please provide me with your LeetCode ID to receive your 100 LeetCoins as a reward. We appreciate your support!

ID - Centipede_
thanks.
