### ISSUE TITLE
Missing Test Case - 2595. Number of Even and Odd Bits

### ISSUE THREAD

**Issue by vanita2405** [LeetCode-Feedback/LeetCode-Feedback#15701]
#### Your LeetCode username

vanita2405

#### Category of the bug
 - [. ] Question 
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

**The 2nd sample input and output is given wrong, along with the testcases.**

The mentioned example is given below:
Input: n = 2
Output: [0,1]
Explanation: The binary representation of 2 is **10.**
It contains 1 on the 1st index. 
There are 0 even and 1 odd indices.

 **Bug: It contains 1 on the 0th index.**
**There are 1 even and 0 odd indices.**

Since ,it's clearly mentioned in the question that: 
n is  0-indexed based
Let even denote the number of even indices in the binary representation of n (0-indexed) with value 1.

Let odd denote the number of odd indices in the binary representation of n (0-indexed) with value 1.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```
```
class Solution {
    public int[] evenOddBit(int n) {
        String s=Integer.toBinaryString(n);
        int even=0;
        int odd=0;

        for(int i=0;i<s.length();i++)
        {
            if(s.charAt(i)=='1'&& i%2==0)
            even++;
            else if(s.charAt(i)=='1'&& i%2!=0)
            odd++;
        }
        return new int[]{even,odd};
}
}
```
#### Language used for code

Java

#### Expected behavior

I expected that the answer array for input =2 which is **[1,0]**  will pass the testcase, (as n=2 in binary is 10 , where 1 is in the even(i.e.0th) index,)
BUT, It failed the testcase and expects an answer of array [0,1]

#### Screenshots

![2023-08-18](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/140595378/553f6932-c241-48f1-8b5e-ae2c53c4ae36)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
