### ISSUE TITLE
Missing Solution - 1615. Maximal Network Rank

### ISSUE THREAD

**Issue by itsTodFod** [LeetCode-Feedback/LeetCode-Feedback#15714]
#### Your LeetCode username

avvalnarang2k4

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The solution mentioned in the editorial includes finding degree of each node and then iterates over all the pair of nodes to find the maximum rank. It can be optimised by checking for the degree with most ranks. Any pair of nodes have either 0 or 1 common connection. Instead of iterating over all nodes, we can look for the nodes with maximum connections as `maxRank = connections[i] + connections[j] - commonConnection`. As there is only atmost 1 common connection, nodes with higher degree/connection will make other nodes negligible. 
So we need to look for how many nodes have maximum degree (if multiple nodes have maximum degree). In this case remaining nodes will have atleast 1 less degree making them ineligible for maxRank due to `connections[i] + connections[j]` irrespective of commonConnection. We can iterate over pairs of maxDegree now.
In case we have only one node with maximum degree, we can look for all nodes having second maximum degree. Now only valid pairs are nodeWithMaximumDegree and node(s)WithSecondMaximumDegree, and all other pairs are ineligible for maximum rank due to same reason as in above case.

Discarding these many pairs significantly optimises the code as making pairs is a job of O(n^2) for n nodes.

#### Code you used for Submit/Run operation

```
// Maximal Network Rank
class Solution {
public:
    int maximalNetworkRank(int n, vector<vector<int>>& roads) {
        if(roads.size() < 2)
            return roads.size();
        vector<vector<bool>> network(n, vector<bool>(n, false));
        vector<int> degree(n, 0);
        for(int i = 0; i < roads.size(); i++) {
            network[roads[i][0]][roads[i][1]] = network[roads[i][1]][roads[i][0]] = true;
            degree[roads[i][0]]++;
            degree[roads[i][1]]++;
        }
        
        int max = -1, maxCnt = 0, secondMax = -1;
        for(int i = 0; i < n; i++) {
            if(max == -1) {
                max = degree[i];
                maxCnt++;
            }
            else if(degree[i] == max)
                maxCnt++;
            else if(degree[i] > max) {
                secondMax = max;
                max = degree[i];
                maxCnt = 1;
            }
            else if(degree[i] > secondMax) {
                secondMax = degree[i];
            }
        }

        int maxRank = 0;
        if(maxCnt > 1) {
            vector<int> maxDegreeNodes;
            for(int i = 0; i < n; i++)
                if(max == degree[i])
                    maxDegreeNodes.push_back(i);
            maxRank = max * 2 - 1;
            for(int i = 0; i < maxDegreeNodes.size(); i++) {
                for(int j = i + 1; j < maxDegreeNodes.size(); j++) {
                    if(network[maxDegreeNodes[i]][maxDegreeNodes[j]] == false){
                        maxRank++;
                        break;
                    }
                }
                if(maxRank == max*2)
                    break;
            }
        }
        else {
            int maxDegreeNode;
            vector<int> secondMaxDegreeNodes;
            for(int i = 0; i < n; i++) {
                if(max == degree[i])
                    maxDegreeNode = i;
                if(secondMax == degree[i])
                    secondMaxDegreeNodes.push_back(i);
            }
            maxRank = max + secondMax - 1;
            for(int i = 0; i < secondMaxDegreeNodes.size(); i++) {
                if(network[maxDegreeNode][secondMaxDegreeNodes[i]] == false) {
                    maxRank++;
                    break;
                }
            }
        }
        return maxRank;
    }
};
```

#### Language used for code

C++

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

It does not change the time complexity in the worst-case scenario.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
