### ISSUE TITLE
Invalid Test Case - 44. Wildcard Matching

### ISSUE THREAD

**Issue by truefuego** [LeetCode-Feedback/LeetCode-Feedback#15718]
#### Your LeetCode username

truefuego

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The testcase 1811 is empty and gives MLE

#### Code you used for Submit/Run operation

```
class Solution {
    bool solve(int i, int j, string& s, string p, vector<vector<int>>& dp) {
        if(i < 0 and j < 0) {
            return true;
        }
        if(j < 0 and i >= 0) {
            return false;
        }
        if(i < 0 and j >= 0) {
            for(int k = 0 ; k <= j ; k++) {
                if(p[k] != '*') {
                    return false;
                }
            }
            return true;
        }
        if(dp[i][j] != -1) {
            return dp[i][j];
        }
        if(s[i] == p[j] or p[j] == '?') {
            return dp[i][j] = solve(i-1,j-1,s,p,dp);
        }
        if(p[j] == '*') {
            return dp[i][j] = solve(i-1,j,s,p,dp) or solve(i,j-1,s,p,dp);
        }
        return dp[i][j] = false;
    }
public:
    bool isMatch(string s, string p) {
        int n = s.size();
        int m = p.size();
        vector<vector<int>> dp(n,vector<int> (m,-1));
        return solve(n-1,m-1,s,p,dp);
    }
};
```

#### Language used for code

C++

#### Screenshots

![Screenshot 2023-08-19 002652](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/108484686/ed1d0ba3-2c53-4186-85dc-0b4014b84ee5)

![Screenshot 2023-08-19 002725](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/108484686/3247861a-2c1e-4778-8981-2b1804b06e69)

**Comment by LC-Pam** [comment]
Thanks for reaching out to us! In competitive programming, the "Memory Limit Exceeded" means that the space complexity of your algorithm is not sufficient to solve the problem. It's a good idea to find a way to reduce the complexity of space. It's also worth noting that memory limits are not the same for different problems and different languages. In this case, we’d recommend you use our discussion forum to post your question or check sample solution codes.

Hope this helps, please let me know if you still have any questions or how I can better assist you.
