### ISSUE TITLE
Missing Test Case - 1132. Reported Posts II

### ISSUE THREAD

**Issue by Ildar7sins** [LeetCode-Feedback/LeetCode-Feedback#15725]
In description of problem #[1132](https://leetcode.com/problems/reported-posts-ii/) it is said - "posts that got removed after being reported as spam", but in fact, if i dont chech after condition, it's work fine... And join -  LEFT JOIN Removals r ON r.post_id = a.post_id AND r.remove_date > a.action_date do the difference...
 
```sql
Actions =
| user_id | post_id | action_date | action | extra |
| ------- | ------- | ----------- | ------ | ----- |
| 2       | 2       | 2019-06-04  | report | porn  |
| 2       | 2       | 2019-07-04  | report | spam  |
| 3       | 4       | 2019-07-04  | report | spam  |
| 4       | 3       | 2019-07-02  | report | spam  |
Removals =
| post_id | remove_date |
| ------- | ----------- |
| 2       | 2019-06-22  |
| 3       | 2019-07-18  |
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Ildar7sins** [comment]
Language - MySQL, code - 

```sql
WITH cte AS (
  SELECT 
    a.post_id,
    action_date,
    r.remove_date
  FROM Actions a
  LEFT JOIN Removals r ON r.post_id = a.post_id AND r.remove_date > a.action_date
  WHERE a.action = 'report' AND extra = 'spam'
  GROUP BY a.post_id, action_date
)

SELECT ROUND(AVG( r_date/a_date * 100 ), 2) AS average_daily_percent
FROM (
  SELECT 
    action_date,
    COUNT(remove_date) AS r_date, 
    COUNT(action_date) AS a_date
  FROM cte
  GROUP BY action_date
) r

``` 

Work both variants "LEFT JOIN Removals r ON r.post_id = a.post_id AND r.remove_date > a.action_date" and "LEFT JOIN Removals r ON r.post_id = a.post_id", but description says "after being reported as spam"

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
