### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by obaidalikhan** [LeetCode-Feedback/LeetCode-Feedback#1572]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
map<int,int> m;
        vector<int> v;
        for(int i=0;i<nums.size();i++)
        {
            if(m.find(target-nums[i])!=m.end())
            {
                v.push_back(m[target-nums[i]]);
                v.push_back(i);
                return v;
            }
            m[nums[i]]=i;
        }
        return v;
    }
};
```

**Comment by obaidalikhan** [comment]
This is solution

**Comment by lc-kay** [comment]
@obaidalikhan Please provide the code in [Playground ](https://leetcode.com/playground/new/empty) and also the test case it failed on. Thank you!

**Comment by lc-kay** [comment]
Hi @obaidalikhan 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
