### ISSUE TITLE
Missing Test Case - 1070. Product Sales Analysis III

### ISSUE THREAD

**Issue by PSwicarz** [LeetCode-Feedback/LeetCode-Feedback#15728]
#### Your LeetCode username
piocarz

#### Category of the bug
- [X ] Question
- [ ] Solution
- [ ] Language
- [ X] Missing Test Cases 

#### Description of the bug
It's  trivial edge case - when both dataframes are empty and you join them and then return dataframe using `.iloc[:,[1,5,3,4]]` it returns wrong columns, however it passes all test cases. Whats important,  you dont have to merge dataframes so it's not clear if this testcase is important. Maybe question should expect merging dataframes - returning name of the product .

#### Code you used for Submit/Run operation

```
import pandas as pd

def sales_analysis(sales: pd.DataFrame, product: pd.DataFrame) -> pd.DataFrame:
  return sales.assign(first_year = sales.groupby('product_id').year.transform(min)).query("first_year == year").merge(product, on = 'product_id').iloc[:,[1,5,3,4]]
```

#### Language used for code
Pandas

#### Expected behavior
Code with`.iloc[:,[1,5,3,4]]` should not pass, if there is merging of the dataframes.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/99476222/1621ecdb-8c13-4130-a3ef-087c879aa4a3)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Please ask your question in the discussion forum.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
