### ISSUE TITLE
Missing Test Case - 1998. GCD Sort of an Array

### ISSUE THREAD

**Issue by ogul1** [LeetCode-Feedback/LeetCode-Feedback#15720]
#### Your LeetCode username

ogul

#### Category of the bug
- [ ] Question
- [ + ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The judge code expects true for the following test case:

[10,5,9,3,15,99989,123]

But it should clearly be false, since 99989 is a prime number and we cannot ever swap it with any other number in the array. 99989 should be at the end of the array but it cannot ever be there.

#### Code you used for Submit/Run operation

```
// 1998. GCD Sort of an Array
class Solution {
public:
    struct DSU {
        vector<int> parent, rank;
        DSU(int n): parent(n), rank(n, 1) {
            for (int i = 0; i < n; ++i) {
                parent[i] = i;
            }
        }
        void merge(int u, int v) {
            u = find(u);
            v = find(v);
            if (u == v) {
                return;
            }
            if (rank[v] > rank[u]) {
                swap(u, v);
            }
            rank[u] += rank[v];
            parent[v] = u;
        }
        int find(int u) {
            if (parent[u] == u) {
                return u;
            }
            return parent[u] = find(parent[u]);
        }
        bool check(int u, int v) {
            return find(u) == find(v);
        }
    };
    bool gcdSort(vector<int>& nums) {
        int n = nums.size();
        vector<pair<int, int>> v;
        for (int i = 0; i < n; ++i) {
            v.emplace_back(nums[i], i);
        }
        sort(begin(v), end(v));
        DSU dsu(n + 3e4 + 1e5);
        for (int i = 0; i < n; ++i) {
            if (nums[i] % 2 == 0) {
                dsu.merge(2 + 3e4, i);
            }
            while (nums[i] % 2 == 0) {
                nums[i] /= 2;
            }
            for (int j = 3; j * j <= nums[i]; j += 2) {
                if (nums[i] % j == 0) {
                    dsu.merge(j + 3e4, i);
                }
                while (nums[i] % j == 0) {
                    nums[i] /= j;
                }
            }
            if (nums[i] > 1) {
                dsu.merge(nums[i] + 3e4, i);
            }
        }
        for (int i = 0; i < n; ++i) {
            if (!dsu.check(v[i].second, i)) {
                return false;
            }
        }
        return true;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The judge code should return false for the following test case:

[10,5,9,3,15,99989,123]

But it returns true, since 99989 is a prime number we can't swap it with any other number and it can't ever be in the last position of the array.

#### Screenshots

<img width="1792" alt="Screen Shot 2023-08-18 at 11 56 07 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/95977203/914e3e30-03b9-48c4-9f38-1c96019dd67a">

#### Additional context

The judge code should be fixed for the case that I provided.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
