### ISSUE TITLE
Problem with Test Case (#306)  - 50. Pow(x, n)

### ISSUE THREAD

**Issue by tumarinson** [LeetCode-Feedback/LeetCode-Feedback#15736]
#### Your LeetCode username
tumarinson

#### Category of the bug
- [ ] Question
- [ +] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Test case 306 failing

Dividing 1 by a number less than one returns 1.00000 or something is wrong with rounding

I think it is problem with a php on the platform.

#### Code you used for Submit/Run operation

```
    function myPow($x, $n) {
        if ($n == 0) {
            return 1;
        }

        if ($n < 0) {
            $n = -1 * $n;
            $x = 1.0 / $x;
        }

        $result = 1.0;

        while ($n != 0) {
            if ($n % 2 == 1) {
                $result = $result * $x;
                $n -= 1;
            }

            $x = $x * $x;
            $n = $n / 2;
        }

        return $result;
    }
```

#### Language used for code
PHP

#### Expected behavior
Test 306 will pass successfully

#### Screenshots

<img width="884" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/74502241/95c75f60-3b2c-4212-9064-634444a14a7a">

#### Additional context

running this code in the https://onlinephp.io/ is successful

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.
.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by tumarinson** [comment]
Sure
https://leetcode.com/problems/powx-n/submissions/1025920646/?envType=list&envId=r8qj3lbi

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team

**Comment by nsadovin** [comment]
Дмитрий, у тебя получилось в итоге решить эту задачу?

**Comment by tumarinson** [comment]
> Дмитрий, у Вас получилось в итоге решить эту задачу?

Нет, даже следующий код не решает задачу:
    ```
function myPow($x, $n) {
        return pow($x, $n);
    }
```

очевидно, что проблема на стороне платформы

**Comment by tumarinson** [comment]
@LC-Pam 

I think problem is still in the platform because of the next code doesnt work


```
function myPow($x, $n) {
        return pow($x, $n);
 }
```
