### ISSUE TITLE
Missing Test Case - 823. Binary Trees With Factors

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#1573]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A number of solutions are accepted but fail on the following test case:
[823_test_case.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/5648036/823_test_case.txt)

#### Code you used for Submit/Run operation

```
class Solution {
    public int numFactoredBinaryTrees(int[] A) {
        long res = 0L, mod = (long) 1000000007;
        long[] dp = new long[A.length];
        Arrays.fill(dp,1);
        Arrays.sort(A);
        for(int i = 1; i < A.length; i++) {
            int s = 0, e = i-1;
            while(s <= e) {
                if(A[s]*A[e] > A[i])e--;
                else if(A[s]*A[e] < A[i])s++;
                else {
                    dp[i] = ((dp[s]*dp[e]*(A[s] == A[e]? 1:2)%mod+dp[i]))%mod;
                    s++;
                }
            }
        }
        for(long d: dp) {
            res = (d+res)%mod;
        }
        return (int)res;
    }
}
```

```
import java.util.Arrays;

class Solution {
    // Sorting Time: O(n^ 2)
	// Space: O(n)
    public int numFactoredBinaryTrees(int[] A) {
        if(A.length == 0) return 0;
        Arrays.sort(A);
        int mod = 1000000007;
        long[] subtrees = new long[A.length];
        subtrees[0] = 1;
        int total = 1;
        
        for(int i = 1; i < A.length; i++) {
            subtrees[i] = 1;
            for(int j = 0, k = i - 1; j <= k;) {
                if(A[j] * A[k] == A[i]) {
                    long temp = (subtrees[j] * subtrees[k]) % mod;
                    if(j != k) temp = (temp * 2) % mod;
                    subtrees[i] = (subtrees[i] + temp) % mod;
                    j++; k--;
                } else if(A[j] * A[k] < A[i]) {
                    j++;
                } else { //if(A[j] * A[k] > A[i]) 
                    k--;
                }
            }
            total += subtrees[i];
            total = total % mod;
        }
        return total;
    }
}
```

```
class Solution {
    public int numFactoredBinaryTrees(int[] A) {
        Arrays.sort(A);
        int MOD = 1_000_000_007;
        long[] dp = new long[A.length];
        dp[0] = 1;
        int ans = 1;
        for (int i = 1; i < A.length; i++) {
            dp[i] = 1;
            for (int j = 0, k = i - 1; j <= k; ) {
                if (A[j] * A[k] < A[i]) j++;
                else if (A[j] * A[k] > A[i]) k--;
                else {
                    long temp = dp[j] * dp[k];
                    if (j != k) temp = (temp * 2);
                    dp[i] += temp;
                    j++;
                    k--;
                }
            }
            ans += (dp[i] % MOD);
            ans %= MOD;
        }
        return ans;
    }
}
```

#### Language used for code

Java, Java, Java

#### Expected behavior

The solutions should not be accepted since they fail on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/101267653-0317a480-3729-11eb-86cc-48df9e75f243.png)
![image](https://user-images.githubusercontent.com/32546406/101267657-0c087600-3729-11eb-83f4-0c549b8f7943.png)

#### Additional context

Links to original solutions:
https://leetcode.com/problems/binary-trees-with-factors/discuss/143127/Java-easy-understanding-DP-solution-with-explanation
https://leetcode.com/problems/binary-trees-with-factors/discuss/207595/Simple-Java-with-DP
https://leetcode.com/problems/binary-trees-with-factors/discuss/213079/JavaSimple-dp-solution

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
