### ISSUE TITLE
fix unclear problem - 443. String Compression

### ISSUE THREAD

**Issue by orkeilius** [LeetCode-Feedback/LeetCode-Feedback#15752]
#### Your LeetCode username
orkeilius

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
the test analyze the "chars" variable instead of the returned number

Why not ask for the compressed string instead??

That make test unclear (and that probably why he is so down-voted)

Also that make some basic thing bugged, like `chars = something` don't work 

#### Expected behavior
use the return or ask for the compressed string

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
