### ISSUE TITLE
Missing Test Case - 1203. Sort Items by Groups Respecting Dependencies

### ISSUE THREAD

**Issue by ahmetcosar** [LeetCode-Feedback/LeetCode-Feedback#15757]
#### Your LeetCode username
cosar.ahmet@gmail.com

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Needs a test case for cycles over 2nd number in beforeItems[ ]. [5,4] won't cause a
cycle for dependency "5", but the 2nd number "4" will cause a cycle.

Input: n = 8, m = 2, group = [-1,-1,1,0,0,1,0,-1], beforeItems = [[],[6],[5],[6],[3],[],[5,4],[]]
Output: []

#### FEEDBACK for successful feedback is misleading
The failed test case must clearly state that previous test(s) were successful
and the failed test case is being displayed. Just using "reverse video" to
identify which test case caused the code to fail was misleading. 

It would be a much better feedback if the passed test cases can be marked in GREEN (case-1) 
and the failed (case-2)  can be displayed in RED.

**Comment by ahmetcosar** [comment]
I see now, you have test cases to cover this.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
The code submission Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
