### ISSUE TITLE
Solution complexity analysis - 564. Find the Closest Palindrome

### ISSUE THREAD

**Issue by micromism** [LeetCode-Feedback/LeetCode-Feedback#15756]
#### Your LeetCode username
zxzbert

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Complexity analysis in the provided solution seems wrong

#### Expected behavior

Expected complexity analysis for brute force solution: O(log(n)*sqrt(n)). We go through at worst sqrt(n) numbers since we only need to make changes and check through the right half of digits to check palindrome-ness, and the time for each check depends on the number of digits, which is O(log(n)).

Actual complexity analysis: O(sqrt(n)). And the explanation for why it's O(sqrt(n)) isn't given either, so I was really confused when I first saw it about why it wasn't O(n).

Expected complexity analysis for proper algorithmic solution: "O(log(n))"

Actual complexity analysis: "O(l), where l is the length of the string". You could debate whether it's the string that's the input or the number encoded in the string that's the input.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
