### ISSUE TITLE
问题未解决，数组越界的题解还是能提交通过

### ISSUE THREAD

**Issue by Tiikee** [LeetCode-Feedback/LeetCode-Feedback#15751]
> 感谢您的耐心等待，在与相关团队核实后：题目已建修复任务待us同步更新，当前先发放积分奖励至ID：cheng-cheng-cheng-b，请查收～ 我们会在后续的版本不断更新优化和提升我们的产品，给大家带来最佳的用户体验。

-----------------------------------------------------------------------
直接把我的测试用例上传不就完了事吗？有这么麻烦，拖这么久？有问题不解决？自己构造测试用例有漏洞，现在继续保持漏洞现状吗？
问题未解决。越界的测试用例并没有上传上去，下面的题解还是能提交通过，2^20还是没触发数组越界。
构造一个单词间尽可能不重复的5000个单词的测试用例有这么难吗？这不是一个循环+rand能解决的事吗？
而且直接把我上面txt的测试用例上传也可以吧？
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/95959942/7de9930d-5d95-4153-af40-599c8e4e79dd)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/95959942/6a92ec76-6d98-45e4-8c71-863f84b737e3)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/95959942/9e0e65bd-0d9c-4667-9016-4b7dc7853901)

_Originally posted by @Tiikee in https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/14904#issuecomment-1672834385_

**Comment by feiceh** [comment]
Hello～在与相关团队核实后：由于技术问题，我们目前无法添加测试用例。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
