### ISSUE TITLE
LC 459 Incorrect: Time Complexity analysis-Approach 1

### ISSUE THREAD

**Issue by imeanup** [LeetCode-Feedback/LeetCode-Feedback#15769]
#### Your LeetCode username

meanup

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

##### Approach 1: Using Divisors- Time Complexity
1. The statement: "A number $n$ can have a maximum of $2 \cdot \sqrt{n}$ number of divisors. " is written as a universal statement which doesn't hold $\text{true}$ and is dependent on the prime factorization. For example, when $n$ is a prime number, then $n$ has only two divisor, i.e. $1$ and itself. When $n$ is highly composite number, it will have larger number of divisor. (for e.g. 12).
2. Secondly, the outer loop iterate from $1$ to $\frac{n}{2}$, which takes $\mathcal{O} (n)$. The inner loop checks `n % i  == 0` which takes $\mathcal{O}(1)$ (Constant time). The line $\text{pattern} = \text{s[:i]}  \times (\frac{n}{ i})$ creates a new string of length $n$, which takes $\mathcal{O}(n)$ time. The comparison if $\text{s} == \text{pattern}$ also takes $\mathcal{O}(n)$ time. Therefore, the overall time complexity should be $\mathcal{O}(n^2)$.

#### Code you used for Submit/Run operation

```py
class Solution:
    def repeatedSubstringPattern(self, s: str) -> bool:
        n = len(s)
        for i in range(1, n // 2 + 1):
            if n % i == 0:
                pattern = s[:i] * (n // i)
                if s == pattern:
                    return True
        return False
```

#### Language used for code

Python

#### Expected behavior

Approach 1: Using Divisors
Time complexity: $\mathcal{O}(n^2)$

#### Screenshots

NA

#### Additional context

NA

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

The time complexity is usually calculated based on the worst-case scenario, not the best-case.
The inner loop is executed only sqrt(n) times, not n times.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
