### ISSUE TITLE
Missing Test Case - 88. Merge Sorted Array

### ISSUE THREAD

**Issue by hafiedh** [LeetCode-Feedback/LeetCode-Feedback#15761]
#### Your LeetCode username
hafiedh

#### Category of the bug
- [ ] Solution 

#### Description of the bug
it runs as it should in my local machine, but when I paste all test cases it never passes
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73755395/2d51920e-ac4c-4601-8e21-ccf1ad8c7a6d)

#### Code you used for Submit/Run operation
```
// approach 2
	if len(nums) == 0 {
		return 0
	}
	m := make(map[int]bool)
	for _, num := range nums {
		m[num] = true
	}
	result := []int{}
	for key := range m {
		result = append(result, key)
		nums = result
	}
	return len(result)
```

#### Language used for code
Go

#### Expected behavior
This should be a test case according to the results I have attached in the screenshot

#### Screenshots
<img width="595" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73755395/744dc257-1e2e-4761-8f1d-e65530945ac5">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

lThe code submission Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by hafiedh** [comment]
https://leetcode.com/problems/merge-sorted-array/
https://leetcode.com/problems/merge-sorted-array/submissions/1026908579/
I didn't submit it because when I ran the leetcode it didn't pass the test, but when I ran it on the local machine it matched the expected output

**Comment by LC-Pam** [comment]
Thank you for reaching out to us! Unfortunately, we are unable to troubleshoot the different behavior between your local IDE and the LeetCode environment.

For this issue, please raise this as a discuss post in the problem discuss section as other users may have run into the same issue and resolved it.

At LeetCode, we care about the whole learning experience that comes with each problem and we encourage users to teach and help each other to enrich their learning. In addition, we want our users to debug their code and learn from the process.

We appreciate your time and support.
