### ISSUE TITLE
Incorrect Solution - 850. Rectangle Area II

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#1576]
#### Your LeetCode username

igor84

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Java solution # 1 (Approach #1: Principle of Inclusion-Exclusion) produces incorrect result on the following test case:

[[8, 5, 10, 6], [8, 2, 9, 5], [7, 0, 10, 7], [7, 0, 8, 3], [4, 9, 9, 10], [1, 6, 6, 7], [3, 8, 6, 9], [0, 3, 10, 10], [9, 5, 10, 7], [5, 3, 6, 4], [8, 3, 10, 7], [3, 7, 7, 9], [1, 3, 2, 4], [5, 5, 7, 6], [4, 1, 7, 4], [0, 4, 9, 6], [4, 5, 5, 10], [9, 3, 10, 5], [0, 7, 4, 9], [3, 2, 7, 6], [0, 5, 4, 8], [4, 7, 10, 10], [0, 0, 7, 7], [0, 2, 10, 5], [1, 0, 8, 4], [6, 3, 8, 8], [2, 3, 8, 4], [8, 5, 10, 10], [1, 2, 8, 6], [4, 7, 8, 8], [0, 1, 6, 4], [5, 8, 8, 10], [6, 5, 8, 6], [5, 0, 8, 9], [9, 2, 10, 9], [1, 6, 10, 9], [8, 6, 10, 9], [2, 8, 7, 10], [6, 9, 7, 10], [4, 1, 10, 4], [3, 0, 10, 1], [9, 4, 10, 10], [8, 1, 10, 7], [7, 6, 10, 7], [6, 0, 9, 3], [3, 3, 7, 6], [5, 1, 8, 2], [4, 8, 7, 9], [0, 3, 6, 9], [8, 3, 9, 6], [4, 1, 8, 4], [0, 9, 9, 10], [6, 1, 8, 6], [5, 7, 9, 10], [7, 2, 8, 9], [0, 2, 1, 5], [2, 5, 10, 8], [8, 0, 10, 5], [7, 1, 9, 2], [0, 4, 9, 9], [2, 4, 3, 6], [6, 0, 8, 6], [0, 6, 9, 7], [3, 6, 4, 9], [3, 5, 5, 7], [5, 6, 9, 9], [8, 5, 10, 10], [7, 4, 8, 9], [3, 7, 8, 10], [9, 7, 10, 9], [6, 8, 7, 9], [4, 8, 6, 10], [7, 6, 9, 10], [3, 8, 4, 10], [5, 0, 7, 3], [1, 4, 10, 7], [1, 0, 4, 5], [6, 9, 7, 10], [0, 6, 8, 10], [1, 4, 6, 7], [5, 4, 9, 6], [0, 9, 3, 10], [1, 9, 10, 10], [0, 9, 1, 10], [4, 2, 5, 4]]

#### Code you used for Submit/Run operation

```
class Solution {
    public int rectangleArea(int[][] rectangles) {
        int N = rectangles.length;

        long ans = 0;
        for (int subset = 1; subset < (1<<N); ++subset) {
            int[] rec = new int[]{0, 0, 1_000_000_000, 1_000_000_000};
            int parity = -1;
            for (int bit = 0; bit < N; ++bit)
                if (((subset >> bit) & 1) != 0) {
                    rec = intersect(rec, rectangles[bit]);
                    parity *= -1;
                }
            ans += parity * area(rec);
        }

        long MOD = 1_000_000_007;
        ans %= MOD;
        if (ans < 0) ans += MOD;
        return (int) ans;
    }

    public long area(int[] rec) {
        long dx = Math.max(0, rec[2] - rec[0]);
        long dy = Math.max(0, rec[3] - rec[1]);
        return dx * dy;
    }

    public int[] intersect(int[] rec1, int[] rec2) {
        return new int[]{
            Math.max(rec1[0], rec2[0]),
            Math.max(rec1[1], rec2[1]),
            Math.min(rec1[2], rec2[2]),
            Math.min(rec1[3], rec2[3]),
        };
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should be fixed to produce consistent results with solutions 2-4 and online judge

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/101269220-960d0a80-373a-11eb-9606-5f7f928e65bc.png)

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@IgorRud Our team has removed the first approach because it was not well explained. Thank you for your time!
