### ISSUE TITLE
Missing Test Case - 177. Nth Highest Salary

### ISSUE THREAD

**Issue by WiTheR60334** [LeetCode-Feedback/LeetCode-Feedback#15768]
#### Category of the bug (30 days of Pandas)
- [177 ] Question

- [ Python] Language

#### Code you used for Submit/Run operation

```
// [Nth Highest Salary](https://leetcode.com/problems/nth-highest-salary/)
import pandas as pd

def nth_highest_salary(employee: pd.DataFrame, N: int) -> pd.DataFrame:
    a = employee['salary'].drop_duplicates()
    if N <= 0 or N > a.shape[0]:
        return pd.DataFrame({'getNthHighestSalary(N)': [None]})
    else :    
        employee = employee.head(N)
        return pd.DataFrame({'getNthHighestSalary(N)': [employee['salary'].max()]})
```

#### Screenshots :
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/115364885/3cce9cda-b2c5-459c-b8fa-99d2cfc51d6b)

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
