### ISSUE TITLE
Confusing Description - 2261. K Divisible Elements Subarrays

### ISSUE THREAD

**Issue by YogeshP93** [LeetCode-Feedback/LeetCode-Feedback#15773]
#### Your LeetCode username

https://leetcode.com/Baymax_/

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Under description of question - [2261. K Divisible Elements Subarrays](https://leetcode.com/problems/k-divisible-elements-subarrays/)
It states: `Given an integer array nums and two integers k and p, return the number of distinct subarrays which have at most k elements divisible by p.`
Due to lacking a "," (Comma), based on a person's reading speed or where they give a pause, the above statement gives different meaning. Like:

- ` ... (pause) return the number of distinct subarrays which have at most k elements (pause) ... divisible by p`
This sounds like - we need to find distinct sub-arrays, whose length can be at most 'k' and that length is divisible by 'p'.

- `... (pause) return the number of distinct subarrays ... (pause)... which have at most k elements divisible by p`
Here it sounds proper, but it is missing "...that are" before "divisible by 'p'", which would have added more context

#### Expected behavior

To avoid any type of confusion and to force a pause in the sentence while reading it, it would be proper if the statement is like:

- Given an integer array `nums` and two integers `k` and `p`, return the number of **distinct subarrays,** which have **at most** `k` elements that are divisible by `p`.

#### Screenshots

![Screenshot 2023-08-21 125031](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/122779284/56a2a241-a4f0-4199-aec3-b7d9bbfa54d6)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
