### ISSUE TITLE
”582. 杀掉进程“中文题目翻译错误

### ISSUE THREAD

**Issue by yujiuqie** [LeetCode-Feedback/LeetCode-Feedback#15771]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名
AF_J（yujiuqie）

**Bug 类型**
-  题目

**描述**
“[582. 杀掉进程](https://leetcode.cn/problems/kill-process/)”中题目翻译错误。
原文是“return a list of the IDs of the processes that will be killed. ”，
应该被翻译为“返回将被终止的进程的 ID 列表”
但目前力扣中文错误翻译为“返回杀掉该进程后的所有进程 ID 的列表”。
意思完全相反。

**Comment by amcones** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by feiceh** [comment]
奖励已发放至ID：yujiuqie，请查收～
