### ISSUE TITLE
缺少测试用例 - 2831. 找出最长等值子数组

### ISSUE THREAD

**Issue by Ligh0x74** [LeetCode-Feedback/LeetCode-Feedback#15770]
**你的 LeetCode 用户名**
killer-cs

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述**
An accepted solution gets WA on the following testcase:
[1.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/12391757/1.txt)

**你使用的语言**
Java

**你提交或者运行的代码**
``` java
class Solution {
    public int longestEqualSubarray(List<Integer> nums, int k) {
        int n = nums.size(), ans = 0;
        List<Integer>[] pos = new ArrayList[n + 1];
        Arrays.setAll(pos, e -> new ArrayList<>());
        for (int i = 0; i < n; i++) {
            int x = nums.get(i);

            if (x == 100000) continue; // WA
            
            pos[x].add(i - pos[x].size());
        }
        for (var ps : pos) {
            if (ps.size() <= ans) continue;
            int left = 0;
            for (int right = 0; right < ps.size(); right++) {
                while (ps.get(right) - ps.get(left) > k)
                    left++;
                ans = Math.max(ans, right - left + 1);
            }
        }
        return ans;
    }
}
```

**期望行为**
Output: 6
Expected: 7

**Comment by amcones** [comment]
你好，当前该题已添加测试用例， 请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by Ligh0x74** [comment]
> 你好，当前该题已添加测试用例， 请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

leetcode.cn/u/killer-cs/

**Comment by feiceh** [comment]
你好，奖励已发放，请查收～
