### ISSUE TITLE
Wrong text/context - 2261. K Divisible Elements Subarrays

### ISSUE THREAD

**Issue by YogeshP93** [LeetCode-Feedback/LeetCode-Feedback#15774]
#### Your LeetCode username

https://leetcode.com/Baymax_/

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the description of the question - [2261. K Divisible Elements Subarrays](https://leetcode.com/problems/k-divisible-elements-subarrays/)
It states: "Two arrays nums1 and nums2 are said to be distinct if:"
The text should be `subarray` instead of `array` as we are talking in the context of subarrays.

#### Expected behavior

The text should state:
"Two subarrays nums1 and nums2 are said to be distinct if:"

#### Screenshots

![Screenshot 2023-08-21 125553](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/122779284/f113a643-21e9-4eff-aa07-ddd053ab8aeb)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
