### ISSUE TITLE
104. 二叉树的最大深度：程序运行结果与预期不符

### ISSUE THREAD

**Issue by cjl0222** [LeetCode-Feedback/LeetCode-Feedback#15785]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
qing-feng-fei-yu

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [x] 编程语言
- [ ] 缺少测试用例

**描述**
[leetcode第104题](https://leetcode.cn/problems/maximum-depth-of-binary-tree/description?envType=study-plan-v2&envId=top-100-liked)，在运行我下面提交的代码时，一直返回错误的结果0，但在本地运行能返回正确的结果。

**你使用的语言**
C++

**你提交或者运行的代码**
```cpp
class Solution {
public:
    int dfs(TreeNode* now, int depth) {
        if (now == nullptr) return depth;

        return max(dfs(now->left, depth+1), dfs(now->right, depth+1));
        
    }
    int maxDepth(TreeNode* root) {
        return (root, 0);
    }
};
```

**期望行为**
对于测试样例[3,9,20,null,null,15,7]，程序应返回3，但在leetcode中一直返回0。

**屏幕截图**
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/32232720/68700285-8d14-49ca-9103-a914f53492c9)

**额外的上下文**
在本地环境测试运行时返回正确结果的完整代码如下，返回正常结果3：
```cpp
#include <bits/stdc++.h>
using namespace std;

#define null INT_MIN / 2 // null 可自己按题目定义

/// Leetcode中树节点的结构体
struct TreeNode {
  int val;
  TreeNode *left;
  TreeNode *right;
  TreeNode() : val(0), left(nullptr), right(nullptr) {}
  TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
  TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
};

TreeNode* BuildTree(const vector<int>& vec, int index/*当前节点在数组中的下标*/) {
  TreeNode* root = nullptr;

  if (index < vec.size() && vec[index] != null) {
    root = new TreeNode(vec[index]);
    root->left = BuildTree(vec, 2 * index + 1);
    root->right = BuildTree(vec, 2 * index + 2);
  }

  return root;
}

int dfs(TreeNode* now, int depth) {
    if (now == nullptr) return depth;

    return max(dfs(now->left, depth+1), dfs(now->right, depth+1));
    
}

int maxDepth(TreeNode* root) {
    return (root, 0);
}
    

int main() {
    TreeNode* root = BuildTree(vector<int>{3,9,20,null,null,15,7}, 0);
    cout << dfs(root, 0);

    return 0;
}
```
程序在本地正常运行结果为3：
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/32232720/b7edfb49-e8f5-4aa1-94da-8e04cdc57e95)

**Comment by amcones** [comment]
您好，在与相关团队核实后：不处理（`maxDepth` 函数在返回值时忘记调用 `dfs` 函数）。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
