### ISSUE TITLE
Missing Test Case - 1669. Merge In Between Linked Lists

### ISSUE THREAD

**Issue by shnaramn** [LeetCode-Feedback/LeetCode-Feedback#1578]
#### Your LeetCode username
shnaramn

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
I misunderstood the question as 'a' and 'b' being the start and end value nodes which have to be replaced.  They are actually the indices of the nodes to be replaced.

My first solution was accepted: https://leetcode.com/submissions/detail/427649017/

However, it fails for the following test case:

```
[0,3,2,1,4,5]
3
4
[1000000,1000001,1000002]
```

#### Code you used for Submit/Run operation

```
class Solution {
public:
    ListNode* mergeInBetween(ListNode* list1, int a, int b, ListNode* list2) {
        
        // Find start.
        ListNode** ptr = &list1;
        
        while ((*ptr)->next && (*ptr)->next->val != a)
            ptr = &((*ptr)->next);
        
        auto rem = (*ptr)->next;
        
        (*ptr)->next = list2;
        
        auto ptr2 = list2;
        while (ptr2->next)
            ptr2 = ptr2->next;
        
        // Find the last node;
        while (rem && rem->val != b)
            rem = rem->next;

        // Stitch
        ptr2->next = rem->next;
        
        return list1;
    }
};
```

#### Language used for code
C++

#### Expected behavior
My submission should have failed .

**Comment by lc-kay** [comment]
Hi @shnaramn 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @shnaramn 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
