### ISSUE TITLE
Test cases not passing although expected and output are same.

### ISSUE THREAD

**Issue by rahul-shiv** [LeetCode-Feedback/LeetCode-Feedback#15786]
#### Your LeetCode username

rshivapr

#### Category of the bug
Solution for [1366. Rank Teams by Votes](https://leetcode.com/problems/rank-teams-by-votes/)

#### Description of the bug
Test cases not passing although expected and output are same.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    string rankTeams(vector<string>& votes) {
        vector<pair<vector<int>,char>> v(26);
        for(auto vote:votes){
            for(int i = 0; i<vote.length();i++){
                if(v[vote[i]-'A'].first.empty()){
                    v[vote[i]-'A'].first = vector<int>(26);
                    v[vote[i]-'A'].second = vote[i];
                }
                v[vote[i]-'A'].first[i]--;            }
        }
        sort(v.begin(),v.end());
        string ans = "";
        for(auto x:v){
            ans += x.second;
        }
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

testcases expected to pass when output and expected match, but this isn't the case.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/26415005/c9ff5179-1d64-4f69-8cf0-07e729f2ddaf)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/26415005/55a4fb46-1920-4b80-95af-22ad0fb985cf)

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
