### ISSUE TITLE
168. Excel Sheet Column Title - The tutorial image is misleading 

### ISSUE THREAD

**Issue by WagdySamih** [LeetCode-Feedback/LeetCode-Feedback#15798]
#### Your LeetCode username
WagdySamih

#### Category of the bug
- [ ] Solution

#### Description of the bug

According to the tutorial and my AC solution
26  answer should be  `AA`
27  answer should be  `AB`

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/45714046/c9a20658-1070-4a12-97e9-df140d39bec8)

It's a minor issue but can be confusing to newbies.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by WagdySamih** [comment]
```
class Solution {
public:
    string convertToTitle(int columnNumber) {
        string title = "";
        while(columnNumber !=0) {
            columnNumber--;
            title+= 'A' +columnNumber%26 ;
            columnNumber/=26;
        }
        reverse(title.begin(), title.end());
        return title;
    }
};
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
