### ISSUE TITLE
459. Repeated Substring Pattern - Typo in Editorial

### ISSUE THREAD

**Issue by agrawalishaan** [LeetCode-Feedback/LeetCode-Feedback#15796]
#### Your LeetCode username
agrawalishaan

#### Category of the bug
- [ ] Question
- [X ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the solution, there is a typo. There is an extra `"` in the code formatted region. <img width="512" alt="Screenshot 2023-08-21 at 5 18 54 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/113543798/f24fd6b8-ea23-4e8b-bf18-1eadd1760909">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
