### ISSUE TITLE
Missing Test Case - 394. Decode String

### ISSUE THREAD

**Issue by john-algo-coder** [LeetCode-Feedback/LeetCode-Feedback#1579]
#### Your LeetCode username
john_algo_coder

#### Category of the bug
- [x] Solution

#### Description of the bug
If the input is 1[1p1[1[j]]] the output is supposed to be ```"pj"```. But the expected output as per the official solution is ```"pjjjjjjjjjjj"``` which is wrong. This fails for all accepted solutions

**Comment by lc-kay** [comment]
Hi @john-algo-coder 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @john-algo-coder 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
