### ISSUE TITLE
PostgreSQL not available for database questions

### ISSUE THREAD

**Issue by jiali1** [LeetCode-Feedback/LeetCode-Feedback#158]
Can we include PostgreSQL for the database questions? It is a very popular SQL language and used pretty much everywhere.

**Comment by CooperCooperCooper** [comment]
Hi @jiali1,
Thank you for your suggestion. To help us improve your experience quickly with this suggestion, can you please share a few problems that you would like to see this implemented quickly to get things started?

**Comment by jiali1** [comment]
Absolutely, let's kick things off with problems 175-177 as these three problems seem to be the most frequently asked and are pretty representative of an candidate's DBMS knowledge.

**Comment by CooperCooperCooper** [comment]
Hi @jiali1,
Got it. I've added these three problems to the message for our engineers. Please stay tuned.

**Comment by jiali1** [comment]
Thanks.

**Comment by CooperCooperCooper** [comment]
Hi @jiali1,
Thank you for your time! I've relayed your information to our team to consider; however, it was my mistake to raise the expectation that we currently support PostgreSQL. We look forward to having all languages on our platform, but for now [these are the only languages we are supporting so far.](https://support.leetcode.com/hc/en-us/articles/360011833974-What-are-the-environments-for-the-programming-languages-). I deeply apologize for this inconvenience. We will keep this language request in mind.
