### ISSUE TITLE
168. Excel Sheet Column Title – Wrong text/context

### ISSUE THREAD

**Issue by aleksandr-kiliushin** [LeetCode-Feedback/LeetCode-Feedback#15807]
#### Your LeetCode username
aleksandr-kiliushin

#### Category of the bug
- [✅] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The problem asks to convert `columnNumber` to `columnTitle`. But the examples demonstrate reversed problem:
```
A -> 1
B -> 2
C -> 3
...
Z -> 26
AA -> 27
AB -> 28 
...
```

#### Code you used for Submit/Run operation
No

#### Language used for code
No

#### Expected behavior
Examples should be with `columnNumber` and `columnTitle` reversed:
```
1 -> A
2 -> B
3 -> C
...
26 -> Z
27 -> AA
28 -> AB
...
```

#### Screenshots
<img width="739" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/65129988/e20e845b-4f96-4ee5-95fa-6d2ca3d2f82e">

#### Additional context
No

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
