### ISSUE TITLE
Missing Test Case - 168. Excel Sheet Column Title

### ISSUE THREAD

**Issue by godcoder28** [LeetCode-Feedback/LeetCode-Feedback#15805]
#### Your LeetCode username

godcoder287

#### Category of the bug
- [] Missing Test Cases 

#### Description of the bug

The solutions are passing even when a particular test case is failing.
'11881376' is giving wrong answer for the below solution when running but the solutionn is being accepted by passing all current testcases.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    string convertToTitle(int columnNumber) {
        int n=columnNumber;
        string ans="";
        bool flag=0;
        char prev='a';
        while(n>26){
            int r=n%26;
            n=n/26;
            if(r==0){
                ans+='Z';
                prev='Z';
                flag=1;
            }
            else{
                if(flag==1){
                    if(r>1){
                        ans+='A'-2+r;
                        prev='A'-2+r;
                    }
                    else{
                        ans+='Z';
                        prev='Z';
                    }
                    flag=0;
                }
                else{
                    ans+='A'-1+r;
                    prev='A'-1+r;
                }
            }
        }
        if(prev!='Z' || n>1){
            if(flag==1)ans+='A'-2+n;
            else ans+='A'-1+n;
        }
        reverse(ans.begin(), ans.end());
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

above solutionn should not be accepted as giving wrong answer for test case -> '11881376'

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
