### ISSUE TITLE
Missing Test Case - 2723. Add Two Promises

### ISSUE THREAD

**Issue by majurageerthan** [LeetCode-Feedback/LeetCode-Feedback#15815]
#### Your LeetCode username
majuran

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the Test Case
Giving a test case for directly resolving a promise without a delay and a non promise direct number

#### Code you used for Submit/Run operation

```
// Add Two Promises
const addTwoPromises = async (promise1, promise2) => {
    const[num1, num2] = await Promise.all([promise1, promise2]);
    return num1 + num2;
};
```

#### Language used for code
JavaScript

#### Test Case Input
Promise.resolve(3)
42

#### Test Case OutPut
45

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
