### ISSUE TITLE
Missing Test Case - 1492. The kth Factor of n

### ISSUE THREAD

**Issue by mohdsaquib93** [LeetCode-Feedback/LeetCode-Feedback#1582]
#### Your LeetCode username

kryoto

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Editorial contains best solution in O(min(k, sqrt(N))) space but it can be done in O(1) space.

#### Code you used for Submit/Run operation

```
// The kth Factor of n
class Solution {
public:
    int kthFactor(int n, int k) {
        int sqrt_n = sqrt(n);
        for (int i = 1; i <= sqrt_n; ++i)
            if (n % i == 0 && !--k)
                return i;
        for (int i = pow(sqrt_n, 2) == n ? sqrt_n - 1 : sqrt_n; i > 0; --i)
            if (n % i == 0 && !--k)
                return n / i;
        return -1;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Space complexity can be improved from O(min(k, sqrt(N))) to constant space

**Comment by lc-kay** [comment]
Hi @mohdsaquib93 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @mohdsaquib93 
Thank you for your time. We've noted your feedback and will be writing another approach for this. However, we will not be using your code as it does not meet our style rules.
