### ISSUE TITLE
Variable name mismatch - 767. Reorganize String

### ISSUE THREAD

**Issue by YogeshP93** [LeetCode-Feedback/LeetCode-Feedback#15829]
#### Your LeetCode username

https://leetcode.com/Baymax_/

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the "Editorial" section of the problem - [767. Reorganize String](https://leetcode.com/problems/reorganize-string/)
**_Under Intuition of "Approach 2: Counting and Odd/Even"_**
There is a usage of variable names: `char_counts` and `max_count` in the approach explanation.
But in the code section related to the same approach, the variable names become: `charCounts` and `maxCount`

Both places should have same variable names to maintain the explanation context.

#### Expected behavior

Both places should have same variable names to maintain the explanation context.
So,

- The variable names should become `char_counts` and `max_count` in the code (same as in explanation)
[OR]
- The variable names should become `charCounts` and `maxCount` in the explanation (same as code block)

#### Screenshots

![Screenshot 2023-08-23 122252](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/122779284/582840a7-dd76-421a-a579-34ce4c3a6782)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
