### ISSUE TITLE
Missing Test Case - 643. Maximum Average Subarray I

### ISSUE THREAD

**Issue by hamedtara** [LeetCode-Feedback/LeetCode-Feedback#15824]
the question and test case is wrong because in this example 

[1,12,-5,-6,50,3]
4

the 4 most significant elements are  [1,12,50,3] but you consider -5 and -6 instead of 1 and 3 

#### Your LeetCode username

hamed tara

#### Category of the bug
- [ ] Question
- [ ] Solution

#### Code you used for Submit/Run operation

```
public class Solution {
    public double findMaxAverage(int[] nums, int k) {
        int maxSum = 0;

        // Calculate the sum of the first k elements
        for (int i = 0; i < k; i++) {
            if (nums[i] > 0) {
                maxSum += nums[i];
            }
        }

        int currentSum = maxSum;

        // Slide the window and update the maximum sum
        for (int i = k; i < nums.length; i++) {
            if (nums[i - k] > 0) {
                currentSum -= nums[i - k];
            }
            if (nums[i] > 0) {
                currentSum += nums[i];
            }
            maxSum = Math.max(maxSum, currentSum);
        }

        // Calculate the maximum average
        double maxAverage = (double) maxSum / k;

        return maxAverage;
    }
}

```

**Comment by YogeshP93** [comment]
If you read the question again, it asks us to consider a "subarray of size k" not subsequence of size k (most significant k elements).
By mentioning "subarray" it is clear that the elements you choose should be continuous elements in array.
You have misunderstood the question here.

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
