### ISSUE TITLE
767. Reorganize String – Fix a solution 

### ISSUE THREAD

**Issue by aleksandr-kiliushin** [LeetCode-Feedback/LeetCode-Feedback#15831]
#### Your LeetCode username
aleksandr-kiliushin

#### Category of the bug
- [ ] Question
- [✅] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In **Algorithm** there is said, that we should not put a polled pair `[character, characterCount]` back to the priority queue when `characterCount` is `0`.

#### Expected behavior
We should not put a polled pair `[character, characterCount]` back to the priority queue when `characterCount` is `1`.  
Because there is no way to poll a pair from the priority queue where `characterCount == 0`, there are no such pairs.  
- Variant 1 how to fix the algorithm: `0` should be replaced by `1`.
- Variant 2 how to fix the algorithm: We can continue comparing with `0`, but count *decreasing* step should go before comparing count with `0`.

#### Screenshots
![telegram-cloud-photo-size-2-5418290025352775788-y](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/65129988/01b0fa82-dd73-47ae-8eaa-946a4fc39afe)
<img width="743" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/65129988/e13089d6-6f2e-4850-9262-df677229ab6f">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
