### ISSUE TITLE
Missing Test Case - 1378. Replace Employee ID With The Unique Identifier

### ISSUE THREAD

**Issue by hossien014** [LeetCode-Feedback/LeetCode-Feedback#15848]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ mysql] Language
- [ ] Missing Test Cases 

#### Description of the bug
my output exact the same as expected output but it's not accept my solution

#### Code you used for Submit/Run operation
``` 
SELECT IFNULL( EmployeeUNI.unique_id,'null') AS  unique_id ,
 Employees.name 
FROM Employees 
LEFT JOIN EmployeeUNI
ON Employees.id= EmployeeUNI.id;
``` 

#### Language used for code
MYSQL

#### Expected behavior
I expect it will accept my answer because my answer is exactly the expected answer

#### Screenshots
![My Image](https://i.ibb.co/B38FSPF/aaw.png)

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
