### ISSUE TITLE
767. Reorganize String - Test case wrong?

### ISSUE THREAD

**Issue by weebao** [LeetCode-Feedback/LeetCode-Feedback#15842]
#### Your LeetCode username
baochidangg

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The question asks for _any_ possible rearrangements of string s where there are no 2 adjacent letters, and for some reason my output failed this test case even though there are no 2 adjacent letters

**Input**
`s = "ogccckcwmbmxtsbmozli"`

**Output**
`"ciclczcsmtmxmwokoglb"`

I already checked the lengths and they are the same length but the test failed.

#### Code you used for Submit/Run operation

```
class Solution:
    def reorganizeString(self, s: str) -> str:
        letterHash = {}
        for letter in s:
            if letter in letterHash:
                letterHash[letter] += 1
            else:
                letterHash[letter] = 1
        letterNum = len(letterHash)
        
        # Check if there is a possible valid string
        def checkNum(c):
            return letterHash[c]
        sortedKeys = list(letterHash.keys())
        sortedKeys.sort(reverse=True, key=checkNum)
        remainLetterSum = 0
        for i in range(1, letterNum):
            remainLetterSum += letterHash[sortedKeys[i]]
        if letterHash[sortedKeys[0]] > remainLetterSum + 1:
            return ""
        
        # There is a valid string
        solutionArr = list(s)
        left = 0
        right = letterNum - 1
        curInd = 0
        isLeft = True
        while left < right:
            if isLeft:
                solutionArr[curInd] = sortedKeys[left]
                letterHash[sortedKeys[left]] -= 1
                if letterHash[sortedKeys[left]] == 0:
                    left += 1
            else:
                solutionArr[curInd] = sortedKeys[right]
                letterHash[sortedKeys[right]] -= 1
                if letterHash[sortedKeys[right]] == 0:
                    right -= 1
            curInd += 1
            isLeft = not isLeft
        
        solutionArr[-1] = sortedKeys[left]
        
        return "".join(solutionArr)
```

#### Language used for code
Python3

#### Expected behavior
The test case should pass.

#### Screenshots
<img width="612" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/85828374/abe89678-2763-413a-9ed6-2d5e775cc376">

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
