### ISSUE TITLE
Missing Test Case - 2. Add Two Numbers

### ISSUE THREAD

**Issue by AdityaKonda6** [LeetCode-Feedback/LeetCode-Feedback#15841]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### You are given two non-empty linked lists representing two non-negative integers. The digits are stored in reverse order, and each of their nodes contains a single digit. Add the two numbers and return the sum as a linked list.

You may assume the two numbers do not contain any leading zero, except the number 0 itself.

 

Example 1:

Input: l1 = [2,4,3], l2 = [5,6,4]
Output: [7,0,8]
Explanation: 342 + 465 = 807.
Example 2:

Input: l1 = [0], l2 = [0]
Output: [0]
Example 3:

Input: l1 = [9,9,9,9,9,9,9], l2 = [9,9,9,9]
Output: [8,9,9,9,0,0,0,1]

#### Code you used for Submit/Run operation

```
class Solution {
public:
    ListNode* addTwoNumbers(ListNode* l1, ListNode* l2) {
        ListNode* dummyHead = new ListNode(0);
        ListNode* tail = dummyHead;
        int carry = 0;

        while (l1 || l2 || carry) {
            int sum = (l1 ? l1->val : 0) + (l2 ? l2->val : 0) + carry;
            carry = sum / 10;

            tail->next = new ListNode(sum % 10);
            tail = tail->next;

            if (l1) l1 = l1->next;
            if (l2) l2 = l2->next;
        }

        ListNode* result = dummyHead->next;
        delete dummyHead;
        return result;
    }
};

```

#### Language used for code
[C++]([https://leetcode.com/problems/add-two-numbers/submissions/1029568590/])

#### Screenshots

![case1](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/95713208/feb370fd-7ccd-43c7-adf5-0d8f5c059b82)

![case2](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/95713208/e10e532d-a944-4108-ac6a-9c02bed44ce9)

![case3](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/95713208/0891485f-f719-482a-be56-2364ccc55ab3)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

Above three test cases all exists. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
