### ISSUE TITLE
Missing testcase in 'Constrained Subsequence Sum' problem

### ISSUE THREAD

**Issue by Swapnil-2001** [LeetCode-Feedback/LeetCode-Feedback#1584]
#### Your LeetCode username
Swap24

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Submitting a faulty solution for [1425. Constrained Subsequence Sum](https://leetcode.com/problems/constrained-subsequence-sum/) passes all available test cases.

#### Code you used for Submit/Run operation

```
class Solution:
    def constrainedSubsetSum(self, nums: List[int], k: int) -> int:
        if max(nums) <= 0:
            return max(nums)
        heap = [(0, -1)]
        for i, ele in enumerate(nums):
            while i - heap[0][1] > k:
                heapq.heappop(heap)
            heapq.heappush(heap, (min(-ele, heap[0][0] - ele), i))
        return -heap[0][0]
```

#### Language used for code
Python 3

#### Expected behavior
For the code given above to fail to pass all test cases.

#### Screenshots

![Constrained Subsequence Sum - LeetCode - Google Chrome 06-12-2020 19_58_16](https://user-images.githubusercontent.com/53232360/101283067-66273b00-37fe-11eb-98d4-ef0683d628ab.png)

#### Additional context

One test case where the code fails is: 
[-10,-2,-10,5,-20,-23,-21]
2

**Comment by lc-kay** [comment]
Hi @Swapnil-2001 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Swapnil-2001 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
