### ISSUE TITLE
Missing Test Case - 125. Valid Palindrome

### ISSUE THREAD

**Issue by ValBasova** [LeetCode-Feedback/LeetCode-Feedback#15844]
#### Your LeetCode username

ValBasova

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 
Question, Missing Test Case

#### Description of the bug

Not fully agree, that String of " "(whitespace) is palindrome, as it doesn't contain any characters after trimming. Besides, if I pass in empty string("") and return false, the solution is accepted - not quite  the behavior according the example #3.
In other words, the Strings "" and " "(which is actually "" after removing all non-alphanumeric characters ) are treated differently.

#### Code you used for Submit/Run operation

```
// Valid Palindrome
class Solution {
 public boolean isPalindrome(String s) {
     if (s == null || s.isEmpty()) return false;

        s = s.toLowerCase();
        int k = s.length() -1;

        for(int i = 0; i <= k; ){
            if(!Character.isLetterOrDigit(s.charAt(i))){
                i++;
                continue;
            }
            if(!Character.isLetterOrDigit(s.charAt(k))){
                k--;
                continue;
            }
            if(s.charAt(i)!= s.charAt(k)) return false;
            i++;
            k--;
        }
        return true;
    }
}
```

#### Language used for code

Java

#### Expected behavior

I expect that Strings ""(empty) and " "(whitespace) after removing all non-alphanumeric characters are the same and are not palindromes.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by ValBasova** [comment]
what the reason it's rejected?
