### ISSUE TITLE
错误的编译失败

### ISSUE THREAD

**Issue by Linn3a** [LeetCode-Feedback/LeetCode-Feedback#15846]
**你的 LeetCode 用户名**
wu-yu-wu-qiu-ji-dan-gao/

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [x] 编程语言
- [ ] 缺少测试用例

**描述**
对字符串s使用`len(s)`，报错`invalid operation: cannot call non-function len (variable of type int) (solution.go)`
**你使用的语言**
golang

**你提交或者运行的代码**
```golang
func lengthOfLongestSubstring(s string) int {
    len := 1
    for l := 2; l < len(s); l++ {
        for i := 0; i < len(s) - l; i++ {
            if checkRepeat(s[i:i+l]) {
                len = l
            }
        }
        if len != l {
            return len
        }
    }
    return len
}

func checkRepeat(subString string) bool {
    m := map[byte]bool{}
    for i:= 0; i < len(subString); i++ {
        _, ok := m[subString[i]]
        if ok {
            return false
        }
        m[subString[i]] = true
    }
    return true
}
```

**期望行为**
为什么string会被视作int…

**Comment by amcones** [comment]
7. 您好，在与相关团队核实后：***不处理***（在 `lengthOfLongestSubstring()` 函数中使用了 `len` 作为变量名，之后使用 `len()` 方法就会被认为是在对 `int` 变量 `len` 进行函数调用，导致报错）。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
