### ISSUE TITLE
Missing Test Case - 1143. Longest Common Subsequence

### ISSUE THREAD

**Issue by wilko98** [LeetCode-Feedback/LeetCode-Feedback#15858]
- [ ] Question
- [ ] Solution
- [ ] Language
- [ 1] Missing Test Cases 

There is no testcase to show that other word could have deleted characters too
Testcase like
s1 = "hello"
s2 = "leo"
would make question more clear to understand.

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
