### ISSUE TITLE
Solution Error - 353. Design Snake Game

### ISSUE THREAD

**Issue by jerrykurtin** [LeetCode-Feedback/LeetCode-Feedback#15851]
#### Your LeetCode username

confused_biologist

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The solution returns an incorrect expected answer to a simple testcase.

#### Code you used for Submit/Run operation

```c++
class SnakeGame {
public:
    int score;
    int x, y;
    int width, height;
    vector<vector<int>> food;
    int foodIdx;

    map<string, vector<int>> dir;

    set<pair<int, int>> occupied;
    queue<pair<int, int>> tail;

    SnakeGame(int width, int height, vector<vector<int>>& food) : food(food.size(), vector<int>(2)) {
        score = 0;
        x = 0;
        y = 0;
        this->width = width;
        this->height = height;

        for (int idx = 0; idx < food.size(); ++idx) {
            this->food[idx][0] = food[idx][0];
            this->food[idx][1] = food[idx][1];
        }
        foodIdx = 0;

        dir["L"] = {-1, 0};
        dir["U"] = {0, -1};
        dir["R"] = {1, 0};
        dir["D"] = {0, 1};

        tail.push({0, 0});
        occupied.insert({0, 0});
    }
    
    int move(string direction) {
        x += dir[direction][0];
        y += dir[direction][1];

        // Check if we're out of bounds
        if (x < 0 || x >= width || y < 0 || y >= height) {
            return -1;
        }

        // Check if there's food
        if (foodIdx < food.size() && x == food[foodIdx][1] && y == food[foodIdx][0]) {
            score++;
            foodIdx++;
        }
        else {
            occupied.erase(tail.front());
            tail.pop();
        }

        // Check for collisions
        if (occupied.find({x, y}) != occupied.end()) {
            return -1;
        }

        // Otherwise we're safe!
        occupied.insert({x, y});
        tail.push({x, y});
        return score;
    }
};
```

#### Language used for code
C++

#### Expected behavior

When the snake moves in the order ["R", "D", "L", "U"] with food appearing at each step, it should run into its tail and return -1 on the final step. However, the posted correct answer successfully eats this last food.

The testcase is as follows:
```
["SnakeGame", "move", "move", "move", "move"]
[[2,2,[[0,1],[1,1],[1,0],[0,0]]],["R"],["D"],["L"],["U"]]
```

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/99691419/3e466771-4316-42e5-9089-25af8bf86069)

#### Additional context

The code I've attached passes all testcases:
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/99691419/473a8703-df90-4e63-968a-effe9ceec074)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
