### ISSUE TITLE
Missing Test Case for 1497. Check If Array Pairs Are Divisible by k (Fastest Accepted Solution is Incorrect)

### ISSUE THREAD

**Issue by zhan1442** [LeetCode-Feedback/LeetCode-Feedback#1586]
#### Your LeetCode username

zcube

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Incorrect solution below passed all test cases and became the fastest solution in the accepted histogram

#### Code you used for Submit/Run operation

```
        for x in range(len(arr)):
            found_compatible = False
            for y in range(len(arr)):
                if x!=y and (arr[x]+arr[y])%k == 0:
                    found_compatible = True
                    break
            if not found_compatible:
                return False
            else:
                break
                
        
        
        if sum(arr)%k == 0:
            return True
        else:
            return False
```

#### Language used for code

Python

#### Expected behavior

for test case:
```
[5,5,1,2,3,4]
10
```
The correct answer is False, but this code would output True, which is incorrect.
But the solution got accepted because of missing these kind of cases

#### Screenshots

![Screen Shot 2020-12-07 at 2 01 37 AM](https://user-images.githubusercontent.com/8563993/101288270-aef7e780-3830-11eb-8967-c82084f247d3.png)

**Comment by lc-kay** [comment]
@zhan1442 Can you please provide your code in [Playground](https://leetcode.com/playground/new/empty)? Thank you!

**Comment by zhan1442** [comment]
https://leetcode.com/playground/NThBHwat

**Comment by lc-kay** [comment]
Hi @zhan1442 
Thank you! I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @zhan1442 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
