### ISSUE TITLE
Missing Test Case - 681. Next Closest Time

### ISSUE THREAD

**Issue by dipeshsah** [LeetCode-Feedback/LeetCode-Feedback#1587]
#### Your LeetCode username

eagerToCode
LeetCode ID: _Me_

#### Category of the bug
- [testcase is not sufficient ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

https://leetcode.com/submissions/detail/427907392/
If you see this submission it is 100% but the code will fail for the input 
"01:11"

#### Code you used for Submit/Run operation

```
class Solution {
public:
    string nextClosestTime(string time)
    {
        set<int> aCharSet;
        aCharSet.insert(time[0]-'0');
        aCharSet.insert(time[1]-'0');
        aCharSet.insert(time[3]-'0');
        aCharSet.insert(time[4]-'0');
        
        auto posItr = aCharSet.find(time[4]-'0');
        if(posItr == std::prev(aCharSet.end()))
        {
            time[4] = '0' + *begin(aCharSet);
        }
        else
        {
            time[4] = '0' + *std::next(posItr);
            return time;
        }
        
        posItr = aCharSet.find(time[3]-'0');
        if(posItr == std::prev(aCharSet.end()) || (*std::next(posItr) >5))
        {
            time[3] = '0' + *begin(aCharSet);
        }
        else
        {
            time[3] = '0' + *std::next(posItr);
            return time;
        }
        
        posItr = aCharSet.find(time[1]-'0');       
        if(time[0] == '0' || time[0] == '1')
        {
            if(posItr == std::prev(aCharSet.end()))
            {
                 time[1] = '0' + *begin(aCharSet);
            }
            else
            {
                time[1] = '0' + *std::next(posItr);
                return time;
            }            
        }
        else if(time[0] == '2')
        {
            if(posItr == std::prev(aCharSet.end()) || (*std::next(posItr) >3))
            {
                 time[1] = '0' + *begin(aCharSet);
            }
            else
            {
                time[1] = '0' + *std::next(posItr);
                return time;
            }            
        }
        return time;
    }
};
```

#### Expected behavior

"10:00"
My code fails if I provide this input, but seems like the current testcase is not sufficient to fail the code written above. 
You can add this testcase.

#### Screenshots

![image](https://user-images.githubusercontent.com/64785068/101290952-2e6bc380-37fd-11eb-800c-10a5f6aca1be.png)

#### Additional context

Need to add the test case where the 1s digit of hour can be incremented to get next closest time. One of such scenario is "01:11". My code will fail for it but it is getting submitted successfully as shown in the above snapshot.

**Comment by lc-kay** [comment]
Hi @dipeshsah 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @dipeshsah 
Thank you for your time. We've used your feedback to update the problem. Please confirm your LeetCode ID so I can reward you with 100 LeetCoins. We appreciate your support!

**Comment by dipeshsah** [comment]
thanks, LeetCode ID: _Me_
