### ISSUE TITLE
Missing Test Case - 1920. Build Array from Permutation

### ISSUE THREAD

**Issue by zeref-dragoneel** [LeetCode-Feedback/LeetCode-Feedback#15878]
#### Your LeetCode username

Parminder222222

#### Category of the bug
- [ ] Question
- [solution isn't displayed ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

It doesn't show the array output as a pointer when the code is correct 

#### Code you used for Submit/Run operation

```
/**
//Build array from permutation
 * Note: The returned array must be malloced, assume caller calls free().
 */
int* buildArray(int* nums, int numsSize, int* returnSize){
int i=0;
returnSize =(int *)malloc (numsSize*sizeof(int));
while (i<numsSize){
  returnSize[i]=nums[nums[i]];
  i++;
}
return *returnSize;
}
```

#### Language used for code

C 

#### Expected behavior

i expected whole array to returned but array wasn't returned at all

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/133828271/17b4a418-007d-49fd-b963-79878090aca6)

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
