### ISSUE TITLE
1. Two Sum

### ISSUE THREAD

**Issue by thapa-in** [LeetCode-Feedback/LeetCode-Feedback#15872]
#### Category - Easy
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description 
Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.
You may assume that each input would have exactly one solution, and you may not use the same element twice.

#### Code you used for Submit/Run operation
```
public class Solution {
    public int[] TwoSum(int[] nums, int target) {
        int[] a=new int[2];
         try
            {
                for (int i = 0; i < (nums.Length-1); i++)
                {
                    for (int j = (i+1); j < (nums.Length); j++)
                    {
                        if ((nums[i] + nums[j]) == target)
                        {
                            Console.WriteLine("[" + i + "," + (j) + "]");
                            a[0] = i; a[1] = (j);
                            break;
                        }
                    }

                }
            }
        catch (Exception ex)
                { }
        return a;
    }
}
```

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/40119660/8a07363b-961f-4908-9419-c1f7db2d4482)

#### Additional context
We have to return value in array form.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
