### ISSUE TITLE
Cheatsheets not Loading

### ISSUE THREAD

**Issue by latinawhocodes** [LeetCode-Feedback/LeetCode-Feedback#15889]
The cheatsheets don't show up in the webpage
<img width="985" alt="Screenshot 2023-08-24 at 9 17 51 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/46027209/adb77b45-09ad-430c-9210-643cfddb5190">

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The explore card looks like loading correctly.

![Screen Shot 2023-08-25 at 10 40 52 AM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/95a6bd1e-a84c-4976-b052-829b0597b876)


If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
