### ISSUE TITLE
1612. Check If Two Expression Trees are Equivalent: description typo

### ISSUE THREAD

**Issue by nineonine** [LeetCode-Feedback/LeetCode-Feedback#15887]
#### Your LeetCode username
dnox (https://leetcode.com/dnox/)

#### Description of the bug
https://leetcode.com/problems/check-if-two-expression-trees-are-equivalent/description/

Both examples have a typo.
It should be:
```
Explanation
```
but instead, it says
```
Explaination
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
