### ISSUE TITLE
2561. Rearranging Fruits: Misspelling in constraints statement.

### ISSUE THREAD

**Issue by projecteulerlover** [LeetCode-Feedback/LeetCode-Feedback#15883]
#### Your LeetCode username
changhsumath666

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

Misspelling in constraints statement.

#### Code you used for Submit/Run operation

N/A.

#### Language used for code

N/A.

#### Expected behavior

The first line of constraints says
```
basket1.length == bakste2.length
```
`basket2` is misspelled as `bakste2`.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by projecteulerlover** [comment]
It looks like someone has attempted to fix this issue, but the formatting is still incorrect; right now it looks like `basket1.length == `basket2`.length` instead of `basket1.length == basket2.length`, just for your information.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
