### ISSUE TITLE
Missing Test Case - 2352. Equal Row and Column Pairs

### ISSUE THREAD

**Issue by kingaileen** [LeetCode-Feedback/LeetCode-Feedback#15882]
#### Your LeetCode username
kingaileen

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Missing test cases for incorrect 'hashing' methods for rows/cols, using a multiplier.

#### Code you used for Submit/Run operation
```
class Solution {
    public int equalPairs(int[][] grid) {
        int n = grid.length;
        int[] rowSum = new int[n];
        int[] colSum = new int[n];
        int multiplier;
        for (int i = 0; i < n; i++) {
            multiplier = 1;
            for (int j = 0; j < n; j++) {
                rowSum[i] += multiplier * grid[i][j];
                colSum[i] += multiplier * grid[j][i];
                multiplier *= -3;
            }
        }

        int ct = 0;
        for (int i: rowSum) {
            for (int j: colSum) {
                if (i == j) ct++;
            }
        }
        return ct;
    }
}
```

#### Language used for code
Java

#### Expected behavior
We would expect this submission to be rejected/marked as a wrong answer, but it's accepted.
This also passes with other multipliers not just -3.

Test cases I'd recommend adding for -x multiplier:
-3: [[9,3,3],[1,1,1],[1,1,3]]
-x: [[x^2,x,x],[1,1,1],[1,1,x^2]]

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
