### ISSUE TITLE
Incorrect follow-up question - 225. Implement Stack using Queues

### ISSUE THREAD

**Issue by Elhamkesh** [LeetCode-Feedback/LeetCode-Feedback#1588]
#### My LeetCode username 
elkk

#### Category of the bug
- [x] Question  
- [ ] Solution
- [ ] Language

#### Description of the bug
In the description of this question as a follow-up question, it is asked:

> **Follow-up:** Can you implement the stack such that each operation is amortized O(1) time complexity? In other words, performing n operations will take overall O(n) time even if one of those operations may take longer.

#### Expected behavior
I don't think this can be answered for this question. 
My suggestion is to update the follow-up question like this:
> **Follow-up:** Can you implement the stack using just 1 Queue?

**Comment by lc-kay** [comment]
Hi @Elhamkesh 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@Elhamkesh Our team has reviewed your report and concluded that it is possible to be answered. Please refer to the discussion where there are many solutions with amortized O(1) per operation.
https://leetcode.com/problems/implement-stack-using-queues/discuss/62522/O(1)-purely-with-queues
