### ISSUE TITLE
128. Longest Consecutive Sequence - Wrong test case expectation [39/73]

### ISSUE THREAD

**Issue by PREngineer** [LeetCode-Feedback/LeetCode-Feedback#15884]
#### Your LeetCode username
PREngineer

----

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

----

#### Description of the bug
_"Given an unsorted array of integers nums, return the length of the longest consecutive elements sequence."_

Test Case 39/73, expected answer doesn't make sense.

**Input: [ 1 , 2 , 0 , 1 ]
Expected answer: 3**

[ 0 , 1 , 1 , 2 ]  <-- After sorting

The one repeats itself, so, there is no sequence of 3 consecutively increasing numbers (per the examples).  The maximum is 2:
0 -> 1     or     1 -> 2

Based on the Example 2:

[ 0, 3, 7, 2, 5, 8, 4, 6, 0, 1 ]  ->  [ 0, 0, 1, 2, 3, 4, 5, 6, 7, 8 ] (sorted)

You don't count the repeated 0 as part of the longest length.  You start the length on the second of the repeated numbers.

----

#### Code you used for Submit/Run operation
```
public class Solution {

    public int LongestConsecutive(int[] nums) {
        // Base case, nothing given
        if( nums.Length == 0 ){
            return 0;
        }
        // Base case, only 1 number
        if( nums.Length == 1 ){
            return 1;
        }

        // Sort the array
        Array.Sort(nums);

        // Max Heap to get the highest of all found
        PriorityQueue<int,int> Mh = new PriorityQueue<int,int>();

        // Loop over the array trying to find a range
        int p1 = 0;
        int p2 = 1;
        // Move a window until our right pointer reaches the end
        while( p2 < nums.Length ){
            // For easier reading
            int num1 = nums[p2-1];
            int num2 = nums[p2];
            
            // If we don't find a sequence
            if( num2 != (num1+1) ){
                // Our window should start on right pointer now
                p1 = p2;
                p2++;
            }
            // Found sequence
            else{
                // Add length to Heap
                int length = p2-p1;
                // Increase by 1, because the indexes leave us short
                length++;
                Mh.Enqueue(length,length*-1);
            
                // Increase p2
                p2++;
            }
        }

        // If we have numbers, the minimum will always be 1
        int answer = 1;
        
        // If we have a value in the heap, we found a greater length
        if( Mh.Count > 0 ){
            answer = Mh.Dequeue();
        }

        return answer ;
    }

}
```

----

#### Language used for code
C#

----

#### Expected behavior
Given the previous explanation, it should be expecting 2, not 3.

----

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/6334069/fd8c9e17-084d-4ae8-bc04-86026e58e116)

----

#### Additional context

N/A

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team

**Comment by PREngineer** [comment]
Thanks for your reply.  I see how the logic of the question works now.

I assume that since, I am sorting, I just have to ignore duplicated numbers and continue the sequence.

Have a great day.
