### ISSUE TITLE
测试用例是空的

### ISSUE THREAD

**Issue by tongyi1587** [LeetCode-Feedback/LeetCode-Feedback#15893]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
like-2c

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述**
提交代码后，没通过的测试用例是空值。

**你使用的语言**
C++

**你提交或者运行的代码**

**期望行为**
应该给出没通过的测试用例

**屏幕截图**
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/14305725/42a57642-6c98-4fde-9209-10a0c67ec9e9)

**额外的上下文**
添加额外的上下文信息

**Comment by amcones** [comment]
感谢反馈，能否向我们补充题目信息，以及完善代码格式，把信息提供完整才能有助于快速验证和精准的定位，谢谢。
