### ISSUE TITLE
Missing Test Case - 68. Text Justification

### ISSUE THREAD

**Issue by sanchay9** [LeetCode-Feedback/LeetCode-Feedback#15897]
#### Your LeetCode username
sanchay_

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My solution is passing for this testcase, should be failing instead.
```
["What","must","be","acknowledgment","abilities","be","abilities","be"]
16
```

#### Code you used for Submit/Run operation

```
// 68. Text Justification
class Solution {
public:
    vector<string> fullJustify(vector<string>& words, int k) {
        vector<string> ans;
        ans.push_back("");

        for (auto x : words) {
            if (ans.back().size() == 0) {
                if (x.size() <= k) {
                    ans.back() += x;
                }
            } else if (ans.back().size() + x.size() + 1 <= k) {
                ans.back() += " ";
                ans.back() += x;
            } else {
                ans.push_back(x);
            }
        }

        for (auto &x : ans) {
            int cnt = 0;
            for (auto y : x) cnt += y == ' ';

            int have = k - x.size();
            if (cnt == 0 || ans.back() == x) {
                for (int i = 0; i < have; i++) x += " ";
                continue;
            }

            int a = have / cnt, b = have % cnt;

            for (int i = 0; i < x.size(); ++i) {
                if (x[i] == ' ') {
                    string tmp = x.substr(i);
                    x = x.substr(0, i);

                    for (int j = 0; j < a; j++) x += " ";
                    if (b-- > 0) x += " ";

                    x += tmp;

                    while (x[i] == ' ') ++i;
                }

                if (have == 0) break;
            }
        }

        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Verdict should be `Wrong answer` as the solution fails for the testcase, instead the solution is getting `Accepted`.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
