### ISSUE TITLE
Missing Test Case - LCP 03. Programmable Robot

### ISSUE THREAD

**Issue by zhaoqi5** [LeetCode-Feedback/LeetCode-Feedback#15895]
#### Your LeetCode username

zhaoqi5

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

It looks like the last test case is empty, perhaps because there is an extra return on the last line of the test case.

#### Language used for code

C++

#### Expected behavior

Empty test cases should not appear. It's fine to remove it or add a valid case.

#### Screenshots

![leetcode lcp 03 error](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/63831051/c3cbd8e5-373f-46b5-bcc8-0615a4cfb0aa)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by zhaoqi5** [comment]
Thanks for your reply.

This is my submission record [linkage](https://leetcode.cn/submissions/detail/459801230/). And the status is as given in my original comments.

Code I used for submit:
```
class Solution {
public:
    bool robot(string command, vector<vector<int>>& obstacles, int x, int y) {
        int curx = 0, cury = 0;
        int action = 0;
        unordered_map<int, vector<vector<int>>> mp;
        for (auto o : obstacles) {
            mp[o[0]].push_back(o);
        }

        while (true) {
            if (curx == x && cury == y)
                return true;
            if (curx > x || cury > y)
                return false;
            
            if (action == command.size())
                action = 0;
            
            if (command[action] == 'U')
                cury++;
            else if (command[action] == 'R')
                curx++;
            action++;

            auto it = mp.find(curx);
            if (it != mp.end()) {
                vector<vector<int>> vecs = it->second;
                for (auto& vec : vecs) {
                    if (vec[0] == curx && vec[1] == cury)
                        return false;
                }
            }
        }
    }
};
```

**Comment by amcones** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by zhaoqi5** [comment]
> 你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

非常感谢，这是我：leetcode.cn/u/zhaoqi5/

**Comment by feiceh** [comment]
收到，奖励已发放至ID：zhaoqi5，请查收～
