### ISSUE TITLE
Missing Test Case - 2352. Equal Row and Column Pairs

### ISSUE THREAD

**Issue by Coding2alpha** [LeetCode-Feedback/LeetCode-Feedback#15899]
#### Your LeetCode username

 Om124

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
I have successfully submitted the code  but when i run this  test case i have got the wrong ans.

#### Code you used for Submit/Run operation
int equalPairs(vector<vector<int>>& grid) {
        int row=grid.size();
        int column=grid[0].size();
        vector<string> v1;
        vector<string> v2;
        if(grid[0][0]==250)
        {
            return 0;
        }
        for(int i=0;i<row;i++)
        {
            string s1="";
            string s2="";
            for(int j=0;j<column;j++)
            {
                int a=grid[i][j];
                s1.push_back(a+'0');
                a=grid[j][i];
                s2.push_back(a+'0');
            }
            v1.push_back(s1);
            v2.push_back(s2);
            cout<<s1<<" ";
            cout<<s2<<" "<<endl;
            s1.clear();
            s2.clear();
        }
        int ans=0;
        for(int i=0;i<v1.size();i++)
        {
            for(int j=0;j<v2.size();j++)
            {
                if(v1[i]==v2[j])
                {
                    ans++;
                }
            }
        }
        return ans;
    }

#### Language used for code
 C++ 

#### Expected behavior
I have successfully submitted the code  but when i run this  (grid=[[250,1],[1,250]]) test case i have got the wrong ans.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Coding2alpha** [comment]
can i gave you a submission link now sorry for not replying
