### ISSUE TITLE
Missing Test Case - 334. Increasing Triplet Subsequence

### ISSUE THREAD

**Issue by ChenyeWang** [LeetCode-Feedback/LeetCode-Feedback#15892]
#### Your LeetCode username 
chenye_wang

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The following code can pass the existing test cases, but failed with this test case:
  input: nums =[20, 21, 18, 19, 5, 6, 7]
  output: False
  expected: True

#### Code you used for Submit/Run operation

```
class Solution:
    def increasingTriplet(self, nums: List[int]) -> bool:
        sub = [nums[0:1], nums[0:1]]
        index = 0
        for i in range(1,len(nums),1):
          if len(sub[1])==len(sub[0]) and sub[1-index][-1]<sub[index][-1] or len(sub[1-index])>len(sub[index]):
            index = 1 - index 


          if nums[i] > sub[index][-1]:
            sub[index].append(nums[i])
          elif nums[i] > sub[index][0] or len(sub[0])==1:
            sub[index][-1] = nums[i]
          else:
            #index = 1 - index
            if nums[i] > sub[1-index][-1]:
              sub[1-index].append(nums[i])
            elif nums[i] > sub[1-index][0] or len(sub[1])==1:
              sub[1-index][-1] = nums[i]

          if len(sub[0])==len(sub[1]) and len(sub[0])==2:
            if sub[0][-1] < sub[1][-1]:
              sub[1] = nums[0:1]
            else:
              sub[0] = nums[0:1]
          
          if max(len(sub[0]), len(sub[1])) == 3:
              return True

        return False
```

#### Language used for code
python3

#### Expected behavior
add this test case

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The test case already exists.
![Screen Shot 2023-08-25 at 10 43 14 AM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/6b636236-17f0-4a3d-8b92-cdeb8dee4dd2)


If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
