### ISSUE TITLE
Bad problem description

### ISSUE THREAD

**Issue by dlitvak** [LeetCode-Feedback/LeetCode-Feedback#1589]
#### Your LeetCode username

dilit

#### Category of the bug
- [x] Question
- [ ] Solution
- [x] Language

#### Description of the bug

The problem [#1266](https://leetcode.com/problems/minimum-time-visiting-all-points/) is not clear.  The description does not mention what happens when a future point lies on the way between 2 points.  For e.x. [[1,1],[3,3],[2,2]] - I thought I had to go around [2,2] not to visit it before [3,3]!  As I understood, the path has to go [1,1],[2,1],[3,2],[3,3],[2,2]. Turns out that in my example [[1,1],[3,3],[2,2]] it was ok to visit **[1,1]**,[2,2],**[3,3],[2,2]**.   So, please clarify that in the description or examples.

#### Code you used for Submit/Run operation

```
class Solution:
    def minTimeToVisitAllPoints(self, points: List[List[int]]) -> int:
        steps = 0
        for i in range(len(points)-1):
            point = points[i]
            next_point = points[i+1]
            steps += max(abs(next_point[0] - point[0]), abs(next_point[1] - point[1]))
        return steps
```

**Comment by lc-kay** [comment]
Hi @dlitvak 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @dlitvak 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
