### ISSUE TITLE
Arrays 101 - Array deletions error

### ISSUE THREAD

**Issue by andrebautista** [LeetCode-Feedback/LeetCode-Feedback#159]
**What kind of the bug**
- [ ] problem
- [x] solution
- [ ] language

**Describe the bug**
The following code comment "say we want to delete the element at index 2" is incorrect and misleading.
```
// Say we want to delete the element at index 2
for (int i = 2; i < length; i++) {
    // Shift each element one position to the left
    int_array[i - 1] = int_array[i];
}

// Again, the length needs to be consistent with the current
// state of the array.
length--;
```

This code is actually deleting the element at index 1 which is in line with the text stated immediately before this code block - "here is the code to delete the element at index 1" - see screenshot below.
[
<img width="1216" alt="Screen Shot 2020-04-18 at 12 36 18 PM" src="https://user-images.githubusercontent.com/4959886/79680611-505cfb00-81c6-11ea-9a19-7f2ca4457413.png">
](url)

**what language is your code written in**
Java

**Comment by CooperCooperCooper** [comment]
Hi @andrebautista,
Thank you for reaching out to us. I've filed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @andrebautista ,
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
