### ISSUE TITLE
Missing Test Case - 1502. Can Make Arithmetic Progression From Sequence

### ISSUE THREAD

**Issue by zhichengzhou98** [LeetCode-Feedback/LeetCode-Feedback#15902]
#### Your LeetCode username

西方朔

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
Missing Test Cases 

#### Description of the bug

My code can pass through all test cases, but I construct  a case, it will be wrong.

#### Code you used for Submit/Run operation

```
//Can Make Arithmetic Progression From Sequence
class Solution {
    public boolean canMakeArithmeticProgression(int[] arr) {
int max = Integer.MIN_VALUE;
        int min = Integer.MAX_VALUE;
        for (int i = 0; i < arr.length; i++) {
            max = Math.max(arr[i], max);
            min = Math.min(arr[i], min);
        }
        if (max == min) {
            return true;
        }
        if ((max -min) % (arr.length - 1) != 0) {
            return false;
        }
        int d = (max - min) / (arr.length - 1);
        int[] res = new int[arr.length];
        for (int i = 0; i < arr.length; i++) {
            res[(arr[i] - min) / d]--;
        }
        for (int i = 0; i < res.length; i++) {
            if (res[i] != -1) {
                return false;
            }
        }
        return true;
    }
}
```

#### Language used for code

Java

#### Expected behavior

I use this test case: [1, 5, 7, 10].

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/121848668/018988d0-cbda-484e-ae5e-715c24ab1b77)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/121848668/20033403-dbaa-4524-9ace-225e8851b57e)

**Comment by LC-Pam** [comment]
Duplicated issue https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/15901
