### ISSUE TITLE
Missing Test Case - 27. Remove Element

### ISSUE THREAD

**Issue by maddy1397** [LeetCode-Feedback/LeetCode-Feedback#1590]
#### Category of the bug
- [ ] Solution - 

#### Description of the bug
There are scenarios that can have multiple answers to this problem and these multiple answers are not included in the test case, resulting in false failures of the test case. For e.g. to remove 2s  from an array [0,1,2,3,0,4,2], possible answer could be [0,1,3,0,4] as well as [0,1,4,3,0]. The former will be the correct answer if the user follows the approach to shift all the elements by one place towards the left and the latter will be correct if the user opts to swap elements from the last.

However, the current test only accepts the latter output.

#### Language used for code
Java

#### Screenshots

![image](https://user-images.githubusercontent.com/17475816/101325023-1b0a3800-3891-11eb-9c41-546815348e2f.png)

**Comment by lc-kay** [comment]
@maddy1397 Can you please provide the code you submitted to reach this result? Thank you!

**Comment by lc-kay** [comment]
Hi @maddy1397  ,
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
