### ISSUE TITLE
Missing Test Case - 1502. Can Make Arithmetic Progression From Sequence

### ISSUE THREAD

**Issue by zhichengzhou98** [LeetCode-Feedback/LeetCode-Feedback#15901]
#### Your LeetCode username

西方朔

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 
Missing Test Cases 

#### Description of the bug

My code can pass through all test cases, but I construct  a case, it will be wrong.

#### Code you used for Submit/Run operation

```
//Can Make Arithmetic Progression From Sequence
class Solution {
    public boolean canMakeArithmeticProgression(int[] arr) {
int max = Integer.MIN_VALUE;
        int min = Integer.MAX_VALUE;
        for (int i = 0; i < arr.length; i++) {
            max = Math.max(arr[i], max);
            min = Math.min(arr[i], min);
        }
        if (max == min) {
            return true;
        }
        if ((max -min) % (arr.length - 1) != 0) {
            return false;
        }
        int d = (max - min) / (arr.length - 1);
        int[] res = new int[arr.length];
        for (int i = 0; i < arr.length; i++) {
            res[(arr[i] - min) / d]--;
        }
        for (int i = 0; i < res.length; i++) {
            if (res[i] != -1) {
                return false;
            }
        }
        return true;
    }
}
```

#### Language used for code

Java

#### Expected behavior

I use this test case: [1, 5, 7, 10].

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/121848668/018988d0-cbda-484e-ae5e-715c24ab1b77)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/121848668/20033403-dbaa-4524-9ace-225e8851b57e)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by zhichengzhou98** [comment]
username:西方朔
Thank you!

**Comment by LC-Pam** [comment]
Hi there,

Would you mind sending us your LCCN profile page link? 

Best

**Comment by zhichengzhou98** [comment]
https://leetcode.cn/u/optimistic-mir2akhanintq/

**Comment by zhichengzhou98** [comment]
> Hi there,
> 
> Would you mind sending us your LCCN profile page link?
> 
> Best

https://leetcode.cn/u/optimistic-mir2akhanintq/

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
