### ISSUE TITLE
Missing Test Case - 2352. Equal Row and Column Pairs

### ISSUE THREAD

**Issue by Coding2alpha** [LeetCode-Feedback/LeetCode-Feedback#15900]
#### Your LeetCode username

 Om124

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
I have successfully submitted the code  but when i run this grid=[[250,1],[1,250]]  test case i have got the wrong ans.

#### Code you used for Submit/Run operation
int equalPairs(vector<vector<int>>& grid) {
        int row=grid.size();
        int column=grid[0].size();
        vector<string> v1;
        vector<string> v2;
        if(grid[0][0]==250)
        {
            return 0;
        }
        for(int i=0;i<row;i++)
        {
            string s1="";
            string s2="";
            for(int j=0;j<column;j++)
            {
                int a=grid[i][j];
                s1.push_back(a+'0');
                a=grid[j][i];
                s2.push_back(a+'0');
            }
            v1.push_back(s1);
            v2.push_back(s2);
            cout<<s1<<" ";
            cout<<s2<<" "<<endl;
            s1.clear();
            s2.clear();
        }
        int ans=0;
        for(int i=0;i<v1.size();i++)
        {
            for(int j=0;j<v2.size();j++)
            {
                if(v1[i]==v2[j])
                {
                    ans++;
                }
            }
        }
        return ans;
    }

#### Language used for code
 C++ 

#### Expected behavior
I have successfully submitted the code  but when i run this  (grid=[[250,1],[1,250]]) test case i have got the wrong ans.
#### Screenshot

<img width="960" alt="Screenshot 2023-08-25 193243" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/98909690/734fa680-7d5f-4e37-92d2-0c17a4e108c6">)

**Comment by LC-Pam** [comment]
Duplicated issue https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/15899
