### ISSUE TITLE
Wrong Test Case - 68. Text Justification

### ISSUE THREAD

**Issue by Senume** [LeetCode-Feedback/LeetCode-Feedback#15904]
#### Your LeetCode username
Senume

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Given test case 26, has incorrect answer.

Test Case input

```
["Give","me","my","Romeo;","and,","when","he","shall","die,","Take","him","and","cut","him","out","in","little","stars,","And","he","will","make","the","face","of","heaven","so","fine","That","all","the","world","will","be","in","love","with","night","And","pay","no","worship","to","the","garish","sun."]
```

The given answer does not follow the general format. 

#### Code you used for Submit/Run operation

```
class Solution:
    def fullJustify(self, words: List[str], maxWidth: int) -> List[str]:

        Para = []
        Line = []
        Count = -1
        StringLen = 0

        Equi_para = []

        for each in words:
            if Count + 1 + len(each) <= maxWidth:
                Line.append(each)
                Count = Count + 1 + len(each)
                StringLen = StringLen + len(each)
            else:
                Para.append((Line, StringLen))
                Line = [each]
                Count = len(each)
                StringLen = len(each)

        Para.append((Line, StringLen))

        for line, C in Para[:-1]:

            if len(line) == 1:
                Equi_para.append(line[0] + ''.join([' ']*(maxWidth - len(line[0]))))
            else:
                equi_sp = -(-(maxWidth - C) // (len(line) - 1) ) 
                remaining = maxWidth - C - equi_sp*(len(line) - 2)
                print(line, equi_sp, remaining)
                
                if remaining <= 0:
                    
                    string = line[0]
                    space_left = maxWidth - C
                    print(line)

                    betweeness = len(line) - 1

                    for each in line[1:-1]:
                        print(space_left, each, len(line) - (line.index(each)))
                        #if space_left != len(line) - (line.index(each)):
                        string += ' '*equi_sp + each
                        
                        space_left -= equi_sp
                        betweeness -=1
                        print(space_left,betweeness)
                        equi_sp = -(-space_left // betweeness) 
                        print(equi_sp)

                        #else:
                        #    string += ' ' + each
                        #    space_left -= 1
                    

                    string += ' '*equi_sp + line[-1]
                    
                    Equi_para.append(string)
                    string = ''
                    continue




                string = (' '*equi_sp).join(line[:-1]) + ' '*remaining + line[-1]
                Equi_para.append(string)
                string = ''

        # Last Line Case
        Last_line, C = Para[-1]
        string = ' '.join(Last_line)
        remain_space = maxWidth - len(string)

        string = string + ' '*remain_space
        Equi_para.append(string)

        return Equi_para
        #return ['testing']


```

#### Language used for code
Python

#### Expected behavior
The expected behavior must have largest possible gap between words must be maintained.
Example

For list of words `['A','B','C', 'D']`

Answer string must be `A   B   C D`

Not the following string 
`A   B  C  D`

#### Screenshots
<img width="508" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/101030274/72ed99c9-f0d1-4988-8011-e002e73bf436">

Green Marked string is the common format followed other test cases. The Red mark shows the given string answer.

#### Additional context
This problem has badly received by the leetcode community and it is reflected with large count of thumbs down than thumbs up. This may be the reason for it. I request the concerned individual to look into it and fix it. Thank You

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
