### ISSUE TITLE
Missing Test Case - 334. Increasing Triplet Subsequence

### ISSUE THREAD

**Issue by ChenyeWang** [LeetCode-Feedback/LeetCode-Feedback#15915]
#### Your LeetCode username
ChenyeWang

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

missing test case [20, 21, 18, 19, 5, 6, 7]     
                                expected output: True

My program does not solve these correctly, but it solves the existing ones.

#### Code you used for Submit/Run operation

```
class Solution:
    def increasingTriplet(self, nums: List[int]) -> bool:
        sub = [nums[0:1], nums[0:1]]
        index = 0
        for i in range(1,len(nums),1):
          if len(sub[1])==len(sub[0]) and sub[1-index][-1]<sub[index][-1] or len(sub[1-index])>len(sub[index]):
            index = 1 - index 


          if nums[i] > sub[index][-1]:
            sub[index].append(nums[i])
          elif nums[i] > sub[index][0] or len(sub[0])==1:
            sub[index][-1] = nums[i]
          else:
            if nums[i] > sub[1-index][-1]:
              sub[1-index].append(nums[i])
            elif nums[i] > sub[1-index][0] or len(sub[1])==1:
              sub[1-index][-1] = nums[i]

          if max(len(sub[0]), len(sub[1])) == 3:
              return True

        return False

```

#### Language used for code

python3

#### Expected behavior

add this test case [20, 21, 18, 19, 5, 6, 7]     
                                expected output: True

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

The problem is fixed.

Please provide us with your LCCN/LCUS username in order to receive a 100 Leetcoins reward.

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!

**Comment by ChenyeWang** [comment]
Thanks for your reply! My LeetCode ID is chenye_wang.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
