### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by poakey1** [LeetCode-Feedback/LeetCode-Feedback#15916]
#### Your LeetCode username
poakey1

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x] Missing Test Cases 

#### Description of the bug
The constraints indicate that the input array can contain negative numbers.  There are no test cases that cover this.
One of the optimisations I considered was to skip numbers in the array if they were equal to or greater than the target number.  This would currently pass the test cases, but would fail (correctly) if there were a test case with a negative number being part of the solution.

For example:
**Input:** nums = [1, 2, 3, -5], target = -4
**Output:** [0, 3]

#### Code you used for Submit/Run operation

```
// Two Sum
using System.Collections.Generic;

public class Solution 
{
    public int[] TwoSum(int[] nums, int target) 
    {
        for (int i = 0; i < nums.Length - 1; i++)
        {
            for (int j = i + 1; j < nums.Length; j++)
            {
                if (nums[i] + nums[j] == target)
                    return new[] { i, j };
            }
        }

        return Array.Empty<int>();
    }
}
```

#### Language used for code

C#

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

[1, 2, 3, -5], target = -4
Output: [0, 3]  already exists and our judge working correctly. 

![Screen Shot 2023-08-28 at 4 12 15 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/cd1533e9-34da-456e-bdc5-f695d942d2eb)



If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
