### ISSUE TITLE
Missing Test Case - 122. Best Time to Buy and Sell Stock II

### ISSUE THREAD

**Issue by Rutujas1709** [LeetCode-Feedback/LeetCode-Feedback#15917]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

basically the following code should give you the max profit you get from buying and selling by comparing the values.
I can run and get the output on the problem section but maybe there's a bug in submitting the same solution for solving interview questions. I an attaching the screenshots for both.
<img width="1470" alt="Screenshot 2023-08-25 at 4 07 50 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/59499279/76ecdb20-035e-4995-813f-6a9d7a312140">
<img width="1470" alt="Screenshot 2023-08-25 at 4 07 40 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/59499279/c5878e63-5bb7-48e7-9b7e-2a92c6de5b07">

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by Rutujas1709** [comment]
please fix

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Rutujas1709** [comment]
Hello, 
I guess its fixed. 
Thank you
