### ISSUE TITLE
Weak restrictions. 624. Maximum Distance in Arrays

### ISSUE THREAD

**Issue by RakhmedovRS** [LeetCode-Feedback/LeetCode-Feedback#1591]
#### Your LeetCode username
rakhmedovrs

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language

#### Description of the bug
In the Solution section, second approach says that brute force solution which has O(N^2) time complexity shouldn't pass. I found a solution which has O(N^2) time complexity and it passes all tests without giving TLE.

#### Code you used for Submit/Run operation

```
class Solution {
    public int maxDistance(List<List<Integer>> arrays)
    {
        int[][] pairs = new int[arrays.size()][];
        int pos = 0;
        for (List<Integer> array : arrays)
        {
            pairs[pos++] = new int[]{array.get(0), array.get(array.size() - 1)};
        }

        Arrays.sort(pairs, (a, b) ->
        {
            if (a[0] == b[0])
            {
                return a[1] - b[1];
            }
            return a[0] - b[0];
        });

        int max = 0;

        for (int i = 0; i < pairs.length; i++)
        {
            for (int j = 0; j < pairs.length; j++)
            {
                if (i == j)
                {
                    continue;
                }

                max = Math.max(max, Math.abs(pairs[i][0] - pairs[j][1]));
            }
        }

        return max;
    }
}
```

#### Language used for code
Java

#### Expected behavior

Should give a TLE error

#### Additional context

I did some simple calculations. Task restrictions say that in worst case arrays length will be 10^4. In case of brute force it gives us 10^8 which can be calculated in any modern CPU within 1 second. I think you should increase arrays length up to 10^5

**Comment by lc-kay** [comment]
Hi @RakhmedovRS 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@RakhmedovRS Thankyou for your feedback. We've updated the test cases and will have the solution article updated shortly :)
