### ISSUE TITLE
Standard Solution is not optimal for 654. Maximum Binary Tree

### ISSUE THREAD

**Issue by kexinliu131** [LeetCode-Feedback/LeetCode-Feedback#15913]
#### Your LeetCode username
[kxl7](https://leetcode.com/kxl7/)

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

For question 654
[Maximum Binary Tree](https://leetcode.com/problems/maximum-binary-tree/)

The solution given has Time Complexity O(n^2) which is not optimal.  
Stack based solution has time complexity O(n).  

Missing test case: a long sorted array as input [1, 2, 3, 4, 5, 6, 7, 8, .... .... 100000]. 

#### Code you used for Submit/Run operation

```java
class Solution {
    public TreeNode constructMaximumBinaryTree(int[] nums) {
        Deque<TreeNode> dq = new ArrayDeque<>();
        List<Integer> l = new ArrayList<>();
        for (int i: nums) l.add(i);
        l.add(Integer.MAX_VALUE);
        
        for (Integer i: l) {
            TreeNode currentNode = new TreeNode(i);
            TreeNode right = null, popped = null;
            
            while (!dq.isEmpty() && i > dq.peek().val) {
                popped = dq.pop();
                popped.right = right;
                right = popped;
            }
            
            currentNode.left = popped;
            dq.push(currentNode);
        }
        
        return dq.peek().left;
    }
}
```

#### Language used for code
Java

#### Expected behavior
Test case data size should be big enough to accurately reflect time complexity.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
