### ISSUE TITLE
Missing Test Case - 228. Summary Ranges

### ISSUE THREAD

**Issue by simidagogogo** [LeetCode-Feedback/LeetCode-Feedback#15919]
#### Your LeetCode username
simidagogogo

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation
```cpp
// [228. 汇总区间](https://leetcode.cn/problems/summary-ranges/)
class Solution {
public:
    vector<string> summaryRanges(vector<int>& nums) {
        vector<string> res;
        if (nums.size() == 0) return res;
        if (nums.size() == 1) return {to_string(nums[0])};

        nums.push_back(0); // 末尾添加0，方便处理边界
        string str, last, pre = to_string(nums[0]);
        for (int i = 1; i < nums.size(); ++i) {
            if (nums[i] - 1 != nums[i - 1]) {
                last = to_string(nums[i - 1]);
                if (pre != last) {
                    str = pre + "->" + last;
                } else {
                    str = pre;
                }
                res.push_back(str);
                pre = to_string(nums[i]);
            }
        }
        return res;
    }
};
```

#### Language used for code
C++

#### Expected behavior
输入：nums =[-2, -1]
输出：[]
预期结果：["-2->-1"]

#### Screenshots
<img width="714" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/58698854/6da0bd3f-f328-42e5-935d-8b364baf819e">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
