### ISSUE TITLE
984. String Without AAA or BBB

### ISSUE THREAD

**Issue by Umadevi-R** [LeetCode-Feedback/LeetCode-Feedback#1592]
#### Your LeetCode username

Umadevi_R

#### Category of the bug
- [ ] Question
- [* ] Solution
- [ ] Language

#### Description of the bug

The return type of the function should be a string but when a list is returned and even if the answer id wrong the submission is accepted. I was shocked to see the solution in the discussion forum and when tried in my leetcode submission compiler,it worked.

#### Code you used for Submit/Run operation

```
class Solution:
    def strWithout3a3b(self, a: int, b: int) -> str:
        res=[]
        d=a-b
        if d>0:
            g=min(d,b)
            res=["aab"]*g
            a-=2*g
            b-=g
        elif d<0:
            g=min(-d,a)
            res=["bba"]*g
            b-=2*g
            a-=g
        p=min(a,b)
        res+=["ab"]*p
        a-=p;b-=p
        res+=["a"]*a+["b"]*b
        return "".join(res)
```

#### Language used for code
PYTHON

#### Expected behavior

```
class Solution:
    def strWithout3a3b(self, A: int, B: int) -> str:
        return ['a']*A + ['b']*B
```
THE CODE IN THE EXPECTED BEHAVIOUR SECTION SHOULD NOT BE WORKING AS THE LOGIC IS EXTREMELY WRONG. WHILE MY SOLUTION AND A FEW OTHERS CAN BE ACCEPTED.
#### Additional context

KINDLY KEEP A CHECK IN THE RETURN TYPE SUCH THAT ONLY STRINGS SHOULD BE ACCEPTED AND NOT LISTS WHICH VIOLATES THE OBJECTIVE OF THE PROGRAM AND SOLUTION

**Comment by lc-kay** [comment]
Hi @Umadevi-R 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Umadevi-R 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
