### ISSUE TITLE
LC 115 - Incorrect test cases and question

### ISSUE THREAD

**Issue by vns9** [LeetCode-Feedback/LeetCode-Feedback#15939]
#### Your LeetCode username
venkat-narayana

#### Category of the bug
- Question
- Incorrect test cases

#### Description of the bug
The answer exceeds the signed 32-bit integer, and it is mentioned in the question that it does not. Also, the last test case output is expected -1 but, there cannot be a negative output for this question.

#### Code you used for Submit/Run operation

```
// Authored by Venkat on a fine sunny afternoon in LA
class Solution {
public:
    int helper(int i, int j, string& s, string& t, vector<vector<int>>& dp){
        if(j==-1) return 1;
        if(i==-1) return 0;
        if(dp[i][j] != -1) return dp[i][j];
        int answer = helper(i-1, j, s, t, dp);
        if(s[i] == t[j]){
            answer += helper(i-1, j-1, s, t, dp);
        }
        dp[i][j] = answer;
        return dp[i][j];
    }
    int numDistinct(string s, string t) {
        int ns = s.size();
        int nt = t.size();
        vector<vector<int>> dp(ns, vector<int>(nt, -1));
        return helper(ns-1, nt-1, s, t, dp);
    }
};
```

#### Language used for code
C++

#### Expected behavior
Change or delete the last test case 66/66 and also reword the question to "answer is huge, so take a module 1e9+7"

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by qbh16** [comment]
#### LeetCode username
<https://leetcode.cn/u/fatalerror-i>(LCCN)


#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Incorrect Test Cases


#### Description of the bug

I have encountered same question as above when using Python to solve the problem.


#### Code

```Python
class Solution:
    def numDistinct(self, s: str, t: str) -> int:
        m, n = len(s), len(t)
        if m < n: return 0
        dp = [0] * (n+1)
        dp[0] = 1
        for i in range(m):
            for j in range(min(n-1, i), -1, -1):
                if s[i] == t[j]:
                    dp[j+1] += dp[j]
        return dp[n]
```


#### Input

```
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
```


#### Expected Output

```
-1
````


#### Output

```
TypeError: 21912870037044995008 is not valid value for the expected return type integer
...
```

With Python's big integer, the result is 21912870037044995008, which mods 1 << 31 is 123610048.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
