### ISSUE TITLE
115.Distinct Subsequences, Incorrect Test case

### ISSUE THREAD

**Issue by goodstudyqaq** [LeetCode-Feedback/LeetCode-Feedback#15932]
#### Your LeetCode username

goodstudyqaq

#### Category of the bug
- [] Question
- [ ] Solution
- [ ] Language
- [ X ] Missing Test Cases 

#### Description of the bug

Given two strings s and t, return the number of distinct subsequences of s which equals t.

The test cases are generated so that the answer fits on a 32-bit signed integer.

However, the answer in test cases occurs integer which is bigger than 32-bit.

#### Code you used for Submit/Run operation

```cpp
class Solution {
   public:
    int numDistinct(string s, string t) {
        int n = s.size();
        int m = t.size();

        vector<vector<int>> dp(n + 1, vector<int>(m + 1));
        for (int i = 0; i <= n; i++) dp[i][0] = 1;

        for (int i = 1; i <= n; i++) {
            for (int j = 1; j <= m; j++) {
                if (s[i - 1] == t[j - 1]) {
                    dp[i][j] += dp[i - 1][j - 1];
                } 
                dp[i][j] += dp[i - 1][j];
            }
        }
        return dp[n][m];
    }
};
```

#### Language used for code

C++

#### Expected behavior

It will be accepted!

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/23693830/7eee1605-c6f3-4229-86c8-e1d214b3b79e)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 


Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by goodstudyqaq** [comment]
@LC-Pam 
Why do you close this issue but not fix the data?
