### ISSUE TITLE
646. Maximum Length of Pair Chain Wrong Solution in Editorial

### ISSUE THREAD

**Issue by vj00000** [LeetCode-Feedback/LeetCode-Feedback#15937]
#### Your LeetCode username
Username - VJY0

#### Category of the bug
- [ ] Solution

#### Description of the bug
[646. Maximum Length of Pair Chain](https://leetcode.com/problems/maximum-length-of-pair-chain/)
Daily Leetcode challenge of 26 Aug 2023
In the given Editorial, C++ code of Recursive Dynamic Programming,
in the line 8 
for (int j = i + 1; j < n; i++) {
But actually, it should be 
for (int j = i + 1; j < n; j++) {

#### Code you used for Submit/Run operation
 ``` 
class Solution {
public:
    int longestPairChain(int i, vector<vector<int>>& pairs, int& n, vector<int>& memo) {
        if (memo[i] != 0) {
            return memo[i];
        }
        memo[i] = 1;
        for (int j = i + 1; j < n; j++) {
            if (pairs[i][1] < pairs[j][0]) {
                memo[i] = max(memo[i], 1 + longestPairChain(j, pairs, n, memo));
            }
        }
        return memo[i];
    }

    int findLongestChain(vector<vector<int>>& pairs) {
        int n = pairs.size();
        sort(pairs.begin(), pairs.end());
        vector<int> memo(n);

        int ans = 0;
        for (int i = 0; i < n; i++) {
            ans = max(ans, longestPairChain(i, pairs, n, memo));
        }
        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior
It is giving error, It should just run  

#### Screenshots
![LC BUG](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/88254275/4a27b7e3-7e1c-4db7-bcd0-2e4b2f8b4a62)

#### Additional context
It is Just a Typo

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
