### ISSUE TITLE
1350. Students With Invalid Departments - Accepting wrong test case

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1593]
#### Your LeetCode username

[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

**Accepting duplicate primary key -** 

{"headers":{"Departments":["id","name"],"Students":["id","name","department_id"]},"rows":{"Departments":[**[1,"Electrical Engineering"],[1,"Computer Engineering"]**,[13,"Bussiness Administration"]],"Students":[[23,"Alice",1],**[1,"Bob",7],[1,"Jennifer",13]**,[2,"John",14],[4,"Jasmine",77],[3,"Steve",74],[6,"Luis",1],[8,"Jonathan",7],[7,"Daiana",33],[11,"Madelynn",1]]}}

![image](https://user-images.githubusercontent.com/71989691/101383764-8b3faa80-38df-11eb-8714-215e4a06aa91.png)

**Accepting inputs with wrong data type- Accepting id with string data type but here it must be number/integer.**

{"headers":{"Departments":["id","name"],"Students":["id","name","department_id"]},"rows":{"Departments":[[**"1"**,"Electrical Engineering"],[**"2"**,"Computer Engineering"]],"Students":[[**"8"**,"Jonathan",1],[**"7"**,"Daiana",2],[**"11"**,"Madelynn",3]]}}

![image](https://user-images.githubusercontent.com/71989691/101384512-89c2b200-38e0-11eb-89b3-700f14217ac6.png)

#### Code you used for Submit/Run operation

```
# N/A
```

#### Language used for code

MySQL

#### Expected behavior

**Should accept the unique primary key.**

#### Additional context

Problem: https://leetcode.com/problems/students-with-invalid-departments/

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for your time. We've used your feedback to fix the duplicate primary key problem. In addition, we have noted the other issue and will fix it later.
