### ISSUE TITLE
115题用例错误导致全部代码无法通过

### ISSUE THREAD

**Issue by Tirecc** [LeetCode-Feedback/LeetCode-Feedback#15934]
**你的 LeetCode 用户名**
https://leetcode.cn/u/si-gu-wo-hai-zai/

**Bug 类型**
- [ ] 测试用例有误

**描述**
几乎全部正确代码均无法通过第65个用例，该用例下输出答案21912870037044995008>2^31−1，会引发测评错误。而题目说"题目数据保证答案符合 32 位带符号整数范围"，这个用例没处理好。

**你使用的语言**
Python3等全部语言

**你提交或者运行的代码**
```
class Solution:
    def numDistinct(self, s: str, t: str) -> int:
        m, n = len(s), len(t)
        if m < n:
            return 0
        
        dp = [[0] * (n + 1) for _ in range(m + 1)]
        for i in range(m + 1):
            dp[i][n] = 1
        
        for i in range(m - 1, -1, -1):
            for j in range(n - 1, -1, -1):
                if s[i] == t[j]:
                    dp[i][j] = dp[i + 1][j + 1] + dp[i + 1][j]
                else:
                    dp[i][j] = dp[i + 1][j]
        
        return dp[0][0]
```

**期望行为**
更正测试用例

**屏幕截图**
![V}OAS Z4MEV(Z~D BP_K5@J](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/110284639/52f43217-5e07-46ba-8ebb-fdb20dbe3734)

**Comment by feiceh** [comment]
感谢您的耐心等待，当前题目已更新，奖励已发放，请查收～
