### ISSUE TITLE
Missing Test Case - 88. Merge Sorted Array

### ISSUE THREAD

**Issue by kokbab88611** [LeetCode-Feedback/LeetCode-Feedback#15943]
#### Your LeetCode username

kokbab8861

#### Category of the bug
- [ ] Question
- [o] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

shows right answer in other interpreter but not in leetcode

#### Code you used for Submit/Run operation

```
class Solution:
    def merge(self, nums1: List[int], m: int, nums2: List[int], n: int) -> None:
        """
        Do not return anything, modify nums1 in-place instead.
        """
        nums1 += nums2
        nums1.sort()
        nums1 = [x for x in nums1 if x!=0]
```

#### Expected behavior

[1, 2, 2, 3, 5, 6] should be the value for nums1 list when nums1 = [0], m = 0, nums2 = [1], n = 1 is entered but it shows [0,0,0,1,2,2,3,5,6]

#### Screenshots

https://i.imgur.com/Fm8CKLm.png

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
