### ISSUE TITLE
Missing Test Case - 914. X of a Kind in a Deck of Cards

### ISSUE THREAD

**Issue by prabhat-mishra29** [LeetCode-Feedback/LeetCode-Feedback#15949]
#### Your LeetCode username
prabhatmishra_29

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
There is a missing test case that I have found which on missing accepts the wrong answers as well.
testcase - > [1,1,1,1,1,1,1,1,2,2,2,2,2,2,3,3,3]

#### Code you used for Submit/Run operation
```

import java.util.*;
class Solution {
    public boolean hasGroupsSizeX(int[] deck) {
        //create a hashmap which maps number to it's frequency!
        //precompute:------
        if(deck.length==1){
            return false;
        }
            HashMap<Integer, Integer> mp = new HashMap<>();
            for (int i = 0; i < deck.length; i++) {
                if (mp.containsKey(deck[i]))
                {
                    mp.put(deck[i], mp.get(deck[i]) + 1);
                    //     key   ,  corresponding value
                }
                else
                {
                    mp.put(deck[i], 1);
                }
            }

            ArrayList<Integer> vals = new ArrayList(mp.values());
            if (vals.size() <=1){
                return true;
            }
            for (int i = 0; i < vals.size() - 1; i++){
                if (gcd( vals.get(i), vals.get(i+1)) == 1){
                    return false;
                }
            }
            return true;
    }
    int gcd(int n1,int n2){
        while(n1>0 && n2>0) {
            if (n1 > n2) {
                n1 = n1 % n2;
            } else {
                n2 = n2 % n1;
            }
        }
            if(n1==0){
                 return n2;
            }
            else {
                return n1;
            }
        }
}

```

#### Language used for code
Java

#### Expected behavior
It misses the concept that the subsequent gcd check should be the result of the previous gcd.

####Screenshot
![Screenshot (64)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/114682869/2a5a5a34-6620-4b32-9a34-659a6df3c7f2)

#### Additional context
the testcase that is missing is [1,1,1,1,1,1,1,1,2,2,2,2,2,2,3,3,3]. this type of testcase is missing.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by prabhat-mishra29** [comment]
Greetings Sir/Maam
Thanks for considering my request.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by prabhat-mishra29** [comment]
Thank you so much sir/maam.🙏☺️
