### ISSUE TITLE
Not resolved yet - https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/1534

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1594]
#### Your LeetCode username

[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The issue is still not resolved yet: https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/1534 
The input should be **id<10** but here  it is taking input **id<=10**

Input:

{"headers":{"cinema":["id", "movie", "description", "rating"]},"rows":{"cinema":[[1, "War", "great 3D", 10], [2, "Science", "fiction", 10], [3, "irish", "boring", 10], [4, "Ice song", "Fantacy", 10], [5, "House card", "Interesting", 10]]}}

![image](https://user-images.githubusercontent.com/71989691/101400114-6d317480-38f6-11eb-85b1-a4a32a1394be.png)

**Please check this:**
![image](https://user-images.githubusercontent.com/71989691/101400282-abc72f00-38f6-11eb-863d-91bf4d2343ca.png)

**Also, it is not accepting 0 as a rating -** 

{"headers":{"cinema":["id", "movie", "description", "rating"]},"rows":{"cinema":[[1, "War", "great 3D", 10], [2, "Science", "fiction", 10], [3, "irish", "boring", 10], [4, "Ice song", "Fantacy", 10], [5, "House card", "Interesting", 0]]}}

![image](https://user-images.githubusercontent.com/71989691/101400739-593a4280-38f7-11eb-9f54-d14fb43a5605.png)

#### Code you used for Submit/Run operation

```
# Write your MySQL query statement below
select * from cinema
where description != 'boring'
and mod(id,2) = 1
order by rating desc
```

#### Language used for code

MySQL

#### Expected behavior

The input should be **id<10** but here  it is taking input **id<=10**

#### Additional context

Problem: https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/1534
Problem: https://leetcode.com/problems/not-boring-movies/

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@pratap-082020 Our team has acknowledged this issue and will further look into it. Since this doesn't qualify for rewards, I will close it now. Thank you for understanding.
