### ISSUE TITLE
Not resolved yet -  https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/1530

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1595]
#### Your LeetCode username

[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Problem not resolved yet - https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/1530

**The sex column should take the only "m" of "f" value but here it is taking "null".**

{"headers":{"salary":["id","name","sex","salary"]},"rows":{"salary":[[1,"vijay","null",2500]]}}

![image](https://user-images.githubusercontent.com/71989691/101401432-5d1a9480-38f8-11eb-86a8-8f3de8fb3393.png)

#### Code you used for Submit/Run operation

```
# CODE
UPDATE salary
set sex =  case sex
when 'm' then 'f'
when 'f' then 'm'
end
```

#### Language used for code

MySQL

#### Expected behavior

**The sex column should take the only "m" of "f" value but here it is taking "null".**

#### Additional context

Problem: https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/1530
Problem: https://leetcode.com/problems/swap-salary/

**Comment by pratap-082020** [comment]
If sex is **_null_** the resultant output should be also null but here it is showing _**'m'**_

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@pratap-082020  Our team has acknowledged this issue and will further look into it. Since this doesn't qualify for rewards, I will close it now. Thank you for understanding.
