### ISSUE TITLE
409. Longest Palindrome - Typo in Constraints

### ISSUE THREAD

**Issue by RatsCommander** [LeetCode-Feedback/LeetCode-Feedback#1596]
#### Your LeetCode username

JasonJiachengSong

#### Category of the bug
- [ ] Question
- [ ] Solution
- [√] Language

#### Description of the bug

The 2nd description in Constraints:
_s consits of lower-case and/or upper-case English letters only._
Should we use **consists** instead of **consits** here? :)

#### Screenshots

![image](https://user-images.githubusercontent.com/30992542/101427060-24e77600-3939-11eb-9fc3-edc0e2f107dc.png)

**Comment by lc-kay** [comment]
@RatsCommander

**Comment by lc-kay** [comment]
Hi @RatsCommander 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
