### ISSUE TITLE
Missing testcase - 1146. Snapshot Array

### ISSUE THREAD

**Issue by bahailu-abera** [LeetCode-Feedback/LeetCode-Feedback#15969]
#### Your LeetCode username

[bahailu-abera
](https://leetcode.com/bahailu/)

#### Category of the bug
-  Missing Test Cases 

#### Description of the bug

When running the code , it exceeds the time limit for the given test case. However, when submitting the code, it gets accepted. This indicates a testcase is missing in the online judge. The bug is related to the code's efficiency and time complexity.

Steps to Reproduce
Use the following test case:
[test.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/12448610/test.txt)

Execute the code locally.
Observe that the code takes an extended amount of time and exceeds the time limit.

#### Code you used for Submit/Run operation

```
class SnapshotArray {
public:
    SnapshotArray(int length) {
        data = vector<vector<int>>(length, vector<int>(1, 0));
        snap_id = 0;
    }

    void set(int index, int val) {
        while ((int)data[index].size() < snap_id)
            data[index].push_back(data[index].back());

        int n = (int)data[index].size();

        if (snap_id < n)
            data[index][n - 1] = val;

        else
            data[index].push_back(val);
    }

    int snap() {
        return snap_id++;
    }

    int get(int index, int snap_id) {

        int n = (int)data[index].size();

        if (snap_id >= n)
            return data[index].back();
       
        return data[index][snap_id];
    }
private:
    vector<vector<int>> data;
    int snap_id;
};

/**
 * Your SnapshotArray object will be instantiated and called as such:
 * SnapshotArray* obj = new SnapshotArray(length);
 * obj->set(index,val);
 * int param_2 = obj->snap();
 * int param_3 = obj->get(index,snap_id);
 */
```

#### Language used for code

C++

#### Expected behavior

The online judge must say time limit exceeded for the given testcase.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by bahailu-abera** [comment]
I appreciate your response. 
Could you please clarify if the issue with adding the test case is due to any problem with the format I provided or if the test case itself is deemed unnecessary for the given situation? 
Your clarification would be helpful in understanding the situation better.
