### ISSUE TITLE
1495. Friendly Movies Streamed Last Month - Invalid Testcase 

### ISSUE THREAD

**Issue by rmznyol** [LeetCode-Feedback/LeetCode-Feedback#15965]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In problem #1495 (Friendly Movies Streamed Last Month), the test case is invalid. 
No matter which statement I run we get the following error.

Invalid Testcase
foreign key content_id = 1 does not exist in the Content table

Even the following code, which just calls for one of the tables in the problem gives the same error.

#### Code you used for Submit/Run operation
```
SELECT *
FROM TVProgram
```

#### Language used for code

MySQL

#### Additional context

This problem is a part of Advanced SQL 50 Study program, and we are unable to finish the program without it.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.
The test case in JSON format, such as: {"headers":{"Users":["user_id","name"]},"rows":{"Users":[[1,"aLice"],[2,"bOB"]]}}

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by rmznyol** [comment]
Thank you so much for your prompt response!
Please find below the requested information.

The code submission Accepted Link: 
https://leetcode.com/problems/friendly-movies-streamed-last-month/submissions/1035432663/

Here is the test case in JSON format:
{"headers": {"TVProgram": ["program_date", "content_id", "channel"], "Content": ["content_id", "title", "Kids_content", "content_type"]}, "rows": {"TVProgram": [["2020-06-10 08:00", 1, "LC-Channel"], ["2020-05-11 12:00", 2, "LC-Channel"], ["2020-05-12 12:00", 3, "LC-Channel"], ["2020-05-13 14:00", 4, "Disney Ch"], ["2020-06-18 14:00", 4, "Disney Ch"], ["2020-07-15 16:00", 5, "Disney Ch"]], "Content": [[1, "Leetcode Movie", "N", "Movies"], [2, "Alg. for Kids", "Y", "Series"], [3, "Database Sols", "N", "Series"], [4, "Aladdin", "Y", "Movies"], [5, "Cinderella", "Y", "Movies"]]}}

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

![Screen Shot 2023-10-04 at 5 34 42 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/13b713d2-a505-4d62-9eb0-57c529a773de)


If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
