### ISSUE TITLE
2782. Number of Unique Categories: typo in description

### ISSUE THREAD

**Issue by nineonine** [LeetCode-Feedback/LeetCode-Feedback#15964]
#### Your LeetCode username
dnox (https://leetcode.com/dnox/)

#### Description of the bug
https://leetcode.com/problems/number-of-unique-categories/

description examples say:
```
Input: n = 6, catagoryHandler = [1,1,2,2,3,3]
...
```

Perhaps is should be
```
... categoryHandler = ...
...
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
