### ISSUE TITLE
2301. Match Substring After Replacement

### ISSUE THREAD

**Issue by LakshyaKAChauhan** [LeetCode-Feedback/LeetCode-Feedback#15962]
#### Your LeetCode username
LakshyaK2011

#### Category of the bug
Question

#### Description of the bug
This Question is kinda incorrect heres why:  
According To Example 1, There Are two "e" in "leet", in which only first of them gets mapped, and in this "t" have 2 mappings, and first mapping is used, while in 3rd Example both "e" are replaced and there are two mappings for "t" and nither of them is used

#### Code you used for Submit/Run operation

```
class Solution {
    /**
    Returns A Char Array wheres char[0] is Mapped Character For charToMap and
    char[1] is the index of map or null if cant find mappedChar
    */
    public char[] getCharMappingForChar(char charToMap, char[][] mappings){
        for(int index = 0; index < mappings.length; index++){
            char[] map = mappings[index];
            if(map == null) continue;
            if(map[0] == charToMap){
                return new char[]{map[1], ((index + "").toCharArray()[0])};
            }
        }
        return null;
    }

    public boolean matchReplacement(String s, String sub, char[][] mappings) {
        //map the substring
        char[] array = sub.toCharArray();
        for(int i = 0; i < array.length; i++){
            char _char = array[i];
            char[] map = getCharMappingForChar(_char, mappings);
            if(map == null) continue;
            sub = sub.replaceFirst(_char+"", map[0]+"");
            mappings[Integer.parseInt(map[1] + "")] = null;
        }
        return s.contains(sub);
    }
}
```

#### Language used for code
Java

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
