### ISSUE TITLE
Missing Test Case - 403. Frog Jump

### ISSUE THREAD

**Issue by Dimpal-Kalita** [LeetCode-Feedback/LeetCode-Feedback#15970]
#### Your LeetCode username

dk_sensei

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My Code get an accepted verdict but it should give wrong answer for the given Testcases

stones =  [0,3,5,7]
stones = [0,3]

#### Code you used for Submit/Run operation

```C++
class Solution {
public:
    unordered_map<int,int>mp;
    map<pair<int,int>,bool>dp;
    int mx;
    bool recur(int ind,int k){
        if(ind==mx) return 1;
        if(ind>mx || k<=0) return 0;
        if(dp.count({ind,k})) return dp[{ind,k}];
        bool ans=0;
        for(auto i:{-1,0,1}){
            if(mp.count(ind+k+i)){
                ans|=recur(ind+k+i,k+i);
            }
        }
        return dp[{ind,k}]=ans;
    }
    bool canCross(vector<int>& v){
        for(auto i:v){
            mp[i]++;
            mx=max(mx,i);
        }
        if(v[1]==2) return 0;
        return recur(1,1);
    }
};
```

#### Language used for code

C++

#### Expected behavior

The above code should get a "Wrong Answer" Verdict But it was Accepted, because of the if statement I am using in the code, the code doesn't cover cases where there is 3 on 1st index

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/97835980/0649349f-925c-4572-afeb-487de75ad254)

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/97835980/9f9d689a-095d-48a1-893d-e97bdf46378a)

#### Additional context

TestCases where it should give wrong answer verdict
stones =  [0,3,5,7]
stones = [0,3]

Submission Link: https://leetcode.com/problems/frog-jump/submissions/1033507577/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
