### ISSUE TITLE
1527. Patients With a Condition - Missing Testcase 

### ISSUE THREAD

**Issue by techdev-VIK** [LeetCode-Feedback/LeetCode-Feedback#15972]
#### Your LeetCode username

vikartan

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [yes ] Missing Test Cases 

#### Description of the bug

A test case is missing which gives freedom to users who use REGEXP. If we add a new test case then we can eliminate this wrong solution. 
If we use """ Select * from Patients where conditions REGEXP '\\bDIAB1'  """

Currently this solution is working but it has a flaw in it..

This solution will not work if we have test case like  "XYZ +DIAB1"  or "XYZ -DIAB1" 
\b matches either a non-word character or the position before the first character in the string. 
It's quiet obvious that -DIAB1 is not right hence the above mentioned solution shouldn't work.

#### Code you used for Submit/Run operation
''' Select * from Patients where conditions REGEXP '\\bDIAB1'  '''

#### Language used for code

SQL

#### Expected behavior

If we use """ Select * from Patients where conditions REGEXP '\\bDIAB1'  """
This will not work if we have test case like  "XYZ +DIAB1"  or "XYZ -DIAB1" 
\b matches either a non-word character or the position before the first character in the string. 
It's quiet obvious that -DIAB1 is not right hence the above mentioned solution shouldn't work.

I have also attached a screenshot for more understanding. 

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/139503457/744cddab-ab4a-40ef-9099-fce662668b89)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.
The test case in JSON format, such as: {"headers":{"Users":["user_id","name"]},"rows":{"Users":[[1,"aLice"],[2,"bOB"]]}}

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by techdev-VIK** [comment]
https://leetcode.com/problems/patients-with-a-condition/submissions/1035285415/?envType=study-plan-v2&envId=30-days-of-pandas&lang=pythondata

I have attached a screenshot to show what kind of test cases won't work. Not sure how to write test case details in JSON.
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/139503457/02f60fb0-e832-4e97-83ae-c401b0e81e30)

There is one  more thing I would like to correct. Code of this solution somehow changed above, please use the code pasted below for testing. It includes '"double back slash" b' instead of \b. 

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/139503457/acc4fb68-8c04-4c3b-92fd-73aa41d4f8f9)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
