### ISSUE TITLE
Problem 2831 : Test Case 643 gives wrong output.

### ISSUE THREAD

**Issue by SN-18** [LeetCode-Feedback/LeetCode-Feedback#15974]
#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

In case 643, for the given value of input list and at input k=0, the given output is incorrect.

At k=0, no elements could be deleted from the list. The code should return a 0 (or a Falsey Value).

Instead, output = 2 is expected. 

#### Code you used for Submit/Run operation

```
import sys

class Solution:
    def longestEqualSubarray(self, nums: List[int], k: int) -> int:
         
        idx_arr = list()
        freq_map = dict()
        max_key = max_freq = (-1)*sys.maxsize
                 
        #building frequency map
        for i in range(len(nums)):
            freq_map[nums[i]] = freq_map.get(nums[i],0) + 1
            
            
            if max_freq<freq_map[nums[i]]: 
                max_freq = freq_map[nums[i]]
                max_key = nums[i] 

       
        next_largest = -sys.maxsize
        next_largest_freq = -sys.maxsize
        
        
        l_f = len(freq_map)
        
        # updating max_key and max_freq to next best value, as k is not allowing the maximum 
        if len(nums) - max_freq>k:
            for element in freq_map:
                if freq_map[element]<max_freq and len(nums) - freq_map[element]<=k:
                    next_largest = element
                    next_largest_freq = freq_map[element]
                    max_key = next_largest 
                    max_freq = next_largest_freq
        
        # Edge case when k = 0, either return 1(or a Falsey value), or return length of entire list,
        # as k=0 and nothing can be deleted. I return 1 here, because that is expected by problem,
        # which makes little sense, but strictly testing case by case. -1 would be more appropriate, but
        # 1 (there you go.)

           
        if k==0 and max_freq!=len(nums):
            return 1

        elif k==0 and max_freq==len(nums):
            print("Can't be inside of this, but am, an error for sure")
            return len(nums)
        
        nums_new = list()
        
        return freq_map[max_key]

      
```

#### Expected behavior

Expectation is to get a Falsey value such as 0, as when k=0, it implies that no element could be deleted. If nothing could be deleted, there are only two edge cases, one is where you return 0 (or a Falsey value). 

Other is when you return the entire list's length. This is when you have a list such as [1,1,1], which in itself is an equal subarray of maximum length 3. 

#### Screenshots

Here is the screenshot  (wrong output):

<img width="1440" alt="Incorrect 1" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/83748468/d3569da2-1745-465c-899e-a2ff0a3dc7aa">

#### Additional context

Intended Behaviour:

input=[ 2,2,3 ], k=0
Intended output = Any signal reserved for this (-1, 1 or 0 are used. In some test cases 1 has been used, but not in this. Here, (wrong) output, or the expected output, is 2. )

I thank you for your time, I really appreciate it.

Sincerely,
SN-18

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
