### ISSUE TITLE
Missing TestCase - 225. Implement Stack using Queues

### ISSUE THREAD

**Issue by coder-zs-cse** [LeetCode-Feedback/LeetCode-Feedback#15978]
### Your LeetCode username

zubinshah

### Category of the bug

- [ ]  Question
- [ ]  Solution
- [ ]  Language
- [x]  Missing Test Cases

### Description of the bug

```

    void push(int x) {
        if(q1.empty()){
            q1.push(x);
            q2.push(x);
            return;
        }
        if(q1.size()==1){
            q1.pop();
            q1.push(x);
            q2.push(x);
        }
        else{
            q1.pop();   // this should have been q2.pop() this bug is not detected by the test cases on leetcode, so I am proposing a new testcase
            q1.push(x);
            q2.push(x);
        }
    }

```

### Code you used for Submit/Run operation

```
class MyStack {
public:
    queue<int> q1,q2;
    MyStack() {

    }

    void push(int x) {
        if(q1.empty()){
            q1.push(x);
            q2.push(x);
            return;
        }
        if(q1.size()==1){
            q1.pop();
            q1.push(x);
            q2.push(x);
        }
        else{
            q1.pop();
            q1.push(x);
            q2.push(x);
        }
    }

    int pop() {
        int temp = top();
        if(q1.size()==1){
            q1.pop();
            int last = -1;
            while(q2.size()>1){
                last = q2.front();
                q1.push(last);
                q2.pop();
            }
            q2.pop();
            if(last!=-1) q2.push(last);
        }
        else{
            q2.pop();
            int last = -1;
            while(q1.size()>1){
                last = q1.front();
                q2.push(last);
                q1.pop();
            }
            q1.pop();
            if(last!=-1) q1.push(last);
        }
        return temp;
    }

    int top() {
        if(q1.size()==1) return q1.front();
        else return q2.front();
    }

    bool empty() {
        return q1.size()==0;
    }
};

```

### Language used for code

C++

### Expected behavior

For testcase:
```
["MyStack","push","push","push","pop","push","pop","pop","pop"]
[[],[1],[2],[3],[],[4],[],[],[]]
```
After pushing 1,2,3. We pop 3 and inserted 4. Followed by three pop operations. So the output should be in the form of 3,4,2,1.
But my code is not handling the push operations after first pop operation, so it is giving output 3,2,2,4. Which is incorrect

### Additional context

Brief explanation of my code
suppose elements in stack are supposed to be
[1,2,3,4 
then elements in my q1,q2 are 
1,2,3,4
4
When I do pop operation here, I get
3
1,2,3
another pop operation brings
1,2
2
With a push operation on x=4, brings
1,2,4
4
So this is how with alternate queues, push and pop operations are executed

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
