### ISSUE TITLE
1998. 数组的最大公因数排序 用例错误

### ISSUE THREAD

**Issue by hemingqiao** [LeetCode-Feedback/LeetCode-Feedback#15982]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
elegant-hamilton9eg

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
根据题目描述：
给你一个整数数组 nums ，你可以在 nums 上执行下述操作 **任意次** ：

- 如果 gcd(nums[i], nums[j]) > 1 ，交换 nums[i] 和 nums[j] 的位置。其中 gcd(nums[i], nums[j]) 是 nums[i] 和 nums[j] 的最大公因数。

如果能使用上述交换方式将 nums 按 **非递减顺序** 排列，返回 true ；否则，返回 false 。

而在最后一个测试用例中：

**`[10,5,9,3,15,99989,123]`**

99989 与序列中的任意值的最大公约数均为 1，也就是 99989 不能和任意值进行交换，整个序列不可能变成非递减，因为序列最大值 99989 不能交换到序列末尾。这个用例的结果应为 `false`，但是评测机预期结果是 `true`。

**你使用的语言**
JavaScript

**你提交或者运行的代码**

```
/**
 * @param {number[]} nums
 * @return {boolean}
 */
const gcdSort = function(nums) {
    const p = Array(100010);
    for (let i = 0; i < p.length; i++) p[i] = i;

    const find = (x) => {
        if (p[x] != x) p[x] = find(p[x]);
        return p[x];
    };
    for (let x of nums) {
        let t = x;
        for (let i = 2; i <= t / i; i++) {
            let s = 0;
            while (t % i == 0) t /= i, s++;
            // 将 x 和它的质因子合并
            if (s) p[find(x)] = find(i);
        }
        if (t > 1) p[find(x)] = find(t);
    }
    const temp = nums.slice().sort((a, b) => a - b);
    for (let i = 0; i < nums.length; i++) {
        if (find(nums[i]) != find(temp[i])) return false;
    }
    return true;
};
```

**期望行为**
[10,5,9,3,15,99989,123] 的结果应为 `false`

**屏幕截图**
<img width="849" alt="截屏2023-08-28 下午2 34 41" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/53391056/55b11b90-2ab0-4fec-8d9c-c80c144f4e36">

**额外的上下文**
无

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by hemingqiao** [comment]
Thank you @LC-Pam!

[My code](https://leetcode.com/submissions/detail/1035525050/) cannot pass testcase 90, which is [10,5,9,3,15,99989,123]. This testcase expected result is `true` and my code returned `false`. 

<img width="849" alt="p1" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/53391056/74403f66-1678-4c47-8744-57e3bf25878b">

However, according to the problem description: you can swap the positions of two elements `nums[i]` and `nums[j]` if `gcd(nums[i], nums[j]) > 1`, return `true` if it is possible to sort nums in **non-decreasing order** using the above swap method, or `false` otherwise. 

Assume [10,5,9,3,15,99989,123] is possible to sort in **non-decreasing order** using above method. It means the biggest value in the array, which is 99989 should be swapped to the end of the array. But 99989 is a **prime number** and the gcd of 99989 and other elements in the array is 1, so the swap operation cannot be applied. The assumption is not true, and then  **the result of this testcase should be `false` not `true`.**

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

The problem is fixed.

Please provide us with your LCCN/LCUS username in order to receive a 100 Leetcoins reward.

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!

**Comment by feiceh** [comment]
您好，当前题目已更新，奖励已发放，请查收～
