### ISSUE TITLE
Wrong Test Case - 115. Distinct Subsequences

### ISSUE THREAD

**Issue by Bilal1204** [LeetCode-Feedback/LeetCode-Feedback#15987]
#### Category of the bug
- [❌ ] Wrong test case

#### Description of the bug

The test case is 
s = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
t = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
and the problem is to find distinct subsequences of 's' in 't'. We can clearly see that the output can not be -1 which is the expected output according to the test case 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int numDistinct(string s, string t) {
        int n = s.size(),m = t.size(),M=1e9+7;
        vector<vector<int>> dp(n+1,vector<int>(m+1,0));
        for(int i=0;i<=n;i++) dp[i][0]= 1;
        for(int i=1;i<=n;i++){
            for(int j=1;j<=m;j++){
                if(s[i-1]==t[j-1]) dp[i][j] = dp[i-1][j-1]%M + dp[i-1][j]%M;
                else dp[i][j] = dp[i-1][j]%M;
            }
        }
        return dp[n][m]%M;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The correct output should be 654905827

**Comment by Bilal1204** [comment]
Below is the link to the code that was getting correctly submitted but
because of one wrong test case the same code is failing

https://leetcode.com/problems/distinct-subsequences/submissions/876625784/

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
