### ISSUE TITLE
Wrong test case in 115. Distinct Subsequences 

### ISSUE THREAD

**Issue by Ksbu2003** [LeetCode-Feedback/LeetCode-Feedback#15986]
#### Your LeetCode username
ksbu_2003

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [ + ] Wrong test Case

#### Description of the bug
**for inputs 
s =
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
t =
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
Expected
-1
Expected Output is given -1. But it is not the correct output for that problem.**

#### Code you used for Submit/Run operation

```
// 115. Distinct Subsequences
class Solution {
   #define ll unsigned long long
public:
    vector<vector<ll>>dp;
    ll f(int m,int n,string &s,string &t)
    {
       if(n<0) return 1;
       if(m<0) return 0;
       if(dp[m][n]!=-1) return dp[m][n];
       if(s[m]==t[n]) return dp[m][n]=f(m-1,n-1,s,t)+f(m-1,n,s,t);
       return dp[m][n]=f(m-1,n,s,t);
    }
    int numDistinct(string& s, string& t) {
       int m=s.size(),n=t.size();
       dp.resize(m,vector<ll>(n,-1));
       return f(m-1,n-1,s,t);
    }
};
```

#### Expected behavior

answer is not expected to be -1 for that test case.

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/97026345/58c56be7-3adc-4780-81c8-37652e62b541)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
