### ISSUE TITLE
Missing Test Case - 1669. Merge In Between Linked Lists

### ISSUE THREAD

**Issue by tomKPZ** [LeetCode-Feedback/LeetCode-Feedback#1598]
#### Your LeetCode username

tanderson050594

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language

#### Description of the bug

My incorrect solution was accepted.

#### Code you used for Submit/Run operation

```
class Solution:
    def mergeInBetween(self, list1: ListNode, a: int, b: int, list2: ListNode) -> ListNode:
        dummy = ListNode(0, list1)
        pa = dummy
        while pa.next.val != a:
            pa = pa.next
        nb = pa.next
        while nb.val != b:
            nb = nb.next
        sb = nb.next
        
        pa.next = list2
        while list2.next:
            list2 = list2.next
        list2.next = sb
        
        return dummy.next

```

#### Language used for code
Python3

#### Expected behavior

The question asks to delete nodes between index a and b, but I misunderstood and deleted between nodes with *values* a and b.  However, my code was still accepted because all test cases have node values of 0,1,2,... for list1.

Passing test case:
```
[0,1,2,3,4,5]
3
4
[1000000,1000001,1000002]
```

Failing test case:
```
[5,4,3,2,1,0]
3
4
[1000000,1000001,1000002]
```

**Comment by lc-kay** [comment]
@tomKPZ Our team recently updated the test case set for this problem and your previously accepted solution already fails on a test case. Thank you for your time!
<img width="1427" alt="Screen Shot 2020-12-09 at 1 25 55 PM" src="https://user-images.githubusercontent.com/70870126/101690245-1628be00-3a22-11eb-929c-b8035f938884.png">
