### ISSUE TITLE
1007. Minimum Domino Rotations for equal row - Wrong Testcase Output 

### ISSUE THREAD

**Issue by Aastha192002** [LeetCode-Feedback/LeetCode-Feedback#15981]
#### Category of the bug
- [ ] Solution

#### The code I submitted

```
class Solution {
    public int minDominoRotations(int[] tops, int[] bottoms) {
        Map<Integer, Integer> count = new HashMap();
        for(int i=0 ; i<tops.length; i++){
            int freq = 0;
            for(int j = 0; j<tops.length; j++){
                if(tops[i] == tops[j])
                       count.put(tops[i], freq++);
            }
            for(int j = 0; j<tops.length; j++){
                if(tops[i] == bottoms[j])
                       count.put(tops[i], freq++);
            }
        }

        int cond = 1;

        for(int i = 1; i<bottoms.length; i++){
            if(bottoms[0] == bottoms[i])
              cond++;
            else
              break;
        }

        if(cond == bottoms.length)
          return 0;

        int flag = 1;
        int key = 0;

        for(Map.Entry<Integer, Integer> entry : count.entrySet()){
            if(entry.getValue() >= tops.length){
              key = entry.getKey();
              flag = 1;
              break;
            }
            else{
                flag = 0;
                continue;
            }
        }

        if(flag == 0)
          return -1;
        
        else{
            int count_tops = 0, count_bottoms = 0;
            int min_swap = 0;
            for(int i = 0; i<tops.length; i++){
                if(tops[i] == key)
                  count_tops++;
                if(bottoms[i] == key)
                  count_bottoms++;
            }
            if(count_tops >= count_bottoms){
                // System.out.println(count_tops + " " + count_bottoms);
                for(int i = 0; i<tops.length; i++){
                    if(tops[i] != key)
                        min_swap++;
                }
            }
            else{
                for(int i = 0; i<bottoms.length; i++){
                    if(bottoms[i] != key)
                        min_swap++;
                }
            }

            return min_swap;
        }
    }
}
```

#### Language used for code 
 Java

#### Expected behavior

For the testcase no. 40, where the input is: tops = [1, 2, 3, 4, 6] and bottoms = [6, 6, 6, 6, 6, 5], the expected output is -1 which means that there are no minimum swaps possible which can make either tops or bottoms array have the same number. But if we clearly see, with one swap between the last element of the tops and bottoms array, the bottoms array can be made with one single element that is 6. So according to me the correct output for this testcase is 1 which I'm achieving correctly through the code that I've implemented and submitted.

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team

**Comment by Aastha192002** [comment]
Could you give me a valid technical explanation to the problem I raised in the testcase

**Comment by Aastha192002** [comment]
I want to know why is the expected outcome -1 and not 1
