### ISSUE TITLE
测试用例输出结果错误

### ISSUE THREAD

**Issue by Light-macro** [LeetCode-Feedback/LeetCode-Feedback#15984]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
fragrant

**Bug 类型**
- [√] 题目
- [ ] 题解
- [ ] 编程语言
- [√] 缺少测试用例

**描述**
[115. 不同的子序列](https://leetcode.cn/problems/distinct-subsequences/)
测试用例：
s = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
t = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
显示正确答案是-1。但显然这不正确，我的代码得到的答案是123610048。
**你使用的语言**
C++

**你提交或者运行的代码**
```
class Solution {
public:
    int numDistinct(string s, string t) {
        vector<vector<unsigned long long>> dp(t.size() + 1, vector<unsigned long long>(s.size() + 1, 0));
        for(unsigned long long i = 0; i < dp[0].size(); i ++){
            dp[0][i] = 1;
        }
        for(unsigned long long i = 1; i < dp.size(); i ++){
            for(unsigned long long j = i ; j < dp[i].size(); j ++){
                if(t[i-1] == s[j-1]){
                    dp[i][j] = dp[i-1][j-1] + dp[i][j-1];
                }
                else{
                    dp[i][j] = dp[i][j-1];
                }
            }
        }
        return dp[dp.size()-1].back();
    }
};
```

**期望行为**
改正测试用例的输出结果：123610048。
![1693212544930](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/124678980/da0a8292-084d-4ec1-a66b-ff5a6c7de574)

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
