### ISSUE TITLE
133. Clone Graph: Python method incorrect return type

### ISSUE THREAD

**Issue by ArcherHeffern** [LeetCode-Feedback/LeetCode-Feedback#15999]
#### Your LeetCode username
hefferna

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
Test cases expect a return type of None when input is None, yet the method header and concequently the LSP does not reflect this.

#### Code you used for Submit/Run operation
``` python
from typing import Optional
class Solution:
    def cloneGraph(self, node: Optional['Node']) -> Optional['Node']:
```
*could also do*
``` python
class Solution:
    def cloneGraph(self, node: 'Node'|None) -> 'Node'|None:
```

#### Language used for code
Python

#### Expected behavior
I would expect the types to reflect our input and output being tested on

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
