### ISSUE TITLE
If I use head.next , it will be error! - 141. Linked List Cycle

### ISSUE THREAD

**Issue by miller0926** [LeetCode-Feedback/LeetCode-Feedback#1599]
#### Your LeetCode username

454690352@qq.com

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

If I use head.next , it will be error!
def hasCycle(self, head: ListNode) -> bool:
        slow = head
        fast = head.next
        while (fast != None and fast.next != None):
            slow = slow.next
            fast = fast.next.next
            if (slow == fast): return True
            
        return False

![image](https://user-images.githubusercontent.com/31638550/101456665-5ed36f00-396f-11eb-9775-b2745558a972.png)

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@miller0926 Your code received WA when I submitted it. I'd highly recommend checking out accepted codes in the discuss tab for reference. If you still think there's an issue, please provide a formatted code and explain the issue more in detail. Thank you!
