### ISSUE TITLE
problems 1166 design-file-system cannot understand what's the error

### ISSUE THREAD

**Issue by chaowan2020** [LeetCode-Feedback/LeetCode-Feedback#160]
**What kind of the bug**
- [x ] problem
- [ ] solution
- [ ] language

**Describe the bug**
![butreport](https://user-images.githubusercontent.com/23110933/79697192-4e8b4a00-824f-11ea-80c9-300120d0a756.PNG)

**what language is your code written in**
JavaScript
**The code you submit/run**
```
class FileSystem {
    constructor() {
        this.root = {};
    }
    createPath(path, value) {
        let node = this.root;
        path = path.split('/').splice(1);
        for(let i = 0; i < path.length; i++) {
            if(i !== path.length - 1 && !node[path[i]]) return false;
            if(!node[path[i]]) node[path[i]] = {};
            node = node[path[i]];
        }
        if(node.val) {
            return false;
        } else {
            node.val = value;
            return true;
        }
    }
    get(path) {
        path = path.split('/').splice(1);
        let node = this.root;
        for(const subPath of path) {
            if(!node[subPath]) return -1;
            node = node[subPath];
        }
        return node.val;
    }
}
```

**Expected behavior**
it should pass

**Screenshots**

**Additional context**

**Comment by CooperCooperCooper** [comment]
Hi @chaowan2020,
Thank you for reaching out to us. I've relayed your issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @chaowan2020,
Thank you for your time. We've taken a deeper look into this error. If expand the error on the problem description page, you would see that the error specifies there is an issue on your code Line 16, 
`node.val = value;`. The error stems from trying to use an integer as a structure. Please take a look.
