### ISSUE TITLE
Missing Test Case - 1587. Bank Account Summary II

### ISSUE THREAD

**Issue by Rajat2024** [LeetCode-Feedback/LeetCode-Feedback#16005]
#### Your LeetCode username
Rajat241302 

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I made a edge testcase 
`{"headers": {"Users": ["account", "name"], "Transactions": ["trans_id", "account", "amount", "transacted_on"]}, "rows": {"Users": [[900001, "Alice"], [900002, "Bob"], [900003, "Charlie"]], "Transactions": [[1, 900001, 7000, "2020-08-01"], [2, 900001, 7000, "2020-09-01"], [3, 900001, -3000, "2020-09-02"], [4, 900002, 10001, "2020-09-12"], [5, 900003, 6000, "2020-08-07"], [6, 900003, 6000, "2020-09-07"], [7, 900003, -4000, "2020-09-11"]]}}`
in this Excepted answer should be
`
{"headers": ["name", "balance"], "values": [["Alice", 11000], ["Bob", 10001]]}` 

but in this code answer is 
`
{"headers": ["name", "balance"], "values": [["Alice", 11000]]}`

#### Code you used for Submit/Run operation

```
# 1587. Bank Account Summary II
select
    a.name,
    sum(b.amount) balance
from
    Users a
join
    Transactions b
on
    a.account = b.account
group by
    a.account
having
    balance > 10001;

```

#### Language used for code
MySQL 

#### Expected behavior

my code should return wrong answer when i submit this code

#### Screenshots

Submitted code is [Submitted Code](https://leetcode.com/submissions/detail/1034741197/)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
