### ISSUE TITLE
Wrong Test Case 2035. Partition Array Into Two Arrays to Minimize Sum Difference

### ISSUE THREAD

**Issue by vadlachary2002** [LeetCode-Feedback/LeetCode-Feedback#16003]
#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Question no : 2035. Partition Array Into Two Arrays to Minimize Sum Difference <a href="https://leetcode.com/problems/partition-array-into-two-arrays-to-minimize-sum-difference/" >view</a>

#### Code you used for Submit/Run operation

```
class Solution {
    public int minimumDifference(int[] nums) {
        int min =  0, n= nums.length;
        for(int i:nums){
            min=Math.min(min,i);
        }
        int ts=0;
        for(int i=0;i<n;i++){
            nums[i]+=min*-1;// to make all values greater than 0 so that i can use dp
            ts+=nums[i];
        }
        boolean[][] dp = new boolean[n+1][ts+1];
        for(int i=0;i<=n;i++){
            for(int j=0;j<=ts;j++){
                if(j==0) dp[i][j]=true;
                else if(i==0) dp[i][j]=false;
                else if(nums[i-1]<=j){
                    dp[i][j]=dp[i-1][j-nums[i-1]] || dp[i-1][j];
                }else dp[i][j]= dp[i-1][j];
            }
        }
        min=Integer.MAX_VALUE;
        for(int i=0;i<=ts/2;i++){
            System.out.println(i+" "+dp[n][i]);
            if(dp[n][i]==true){
                int s1 = i;
                int s2 =  ts-s1;
                min=Math.min(min,Math.abs(s1-s2)); 
            }
        }
        return min;
    }
}
```

#### Expected behavior

Let me explain with the example 
``` arr = [ 76, 8, 45, 20, 74, 84, 28, 1] ```
 The question is to partition the array into two arrays such that the difference between the sums of two arrays is minimum.

 I wrote the code that will partition the array into 
 ```a1 = [ 76, 8, 84 ] ```  ```sum(a1)=168```  & 
 ```a2 = [45, 20, 74, 28, 1 ]```  ```sum(a2)=168```

Therefore the minimum difference must be ZERO.
```sum(a1)-sum(a2)=0```.

But for the same test case the expected output is showing ```2```

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/76141959/1ce33653-e9fe-44c9-8ae3-2a21ceded374)

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team

**Comment by vadlachary2002** [comment]
Thank you sir , but  the test case is wrong  which i have mentioned above.
