### ISSUE TITLE
2561. Rearranging Fruits - Typo in Question

### ISSUE THREAD

**Issue by agrawalishaan** [LeetCode-Feedback/LeetCode-Feedback#16000]
#### Your LeetCode username
agrawalishaan

#### Category of the bug
- [ X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the question, it writes: 
<img width="650" alt="Screenshot 2023-08-28 at 5 05 42 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/113543798/65d2962d-00ba-4ed6-96b2-d38ddeb92ffb">

There is an issue with `ith`, the code formatting extends into the empty space.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
