### ISSUE TITLE
511. Game Play Analysis I - Accepting wrong input case

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1600]
#### Your LeetCode username

[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

**Accepting incorrect date - date can not be this - [1,2,"0000-00-00",5]**

{"headers":{"Activity":["player_id","device_id","event_date","games_played"]},"rows":{"Activity":[[1,2,"0000-00-00",5],[1,2,"2016-05-02",6],[2,3,"2017-06-25",1],[3,1,"2016-03-02",0],[3,4,"2018-07-03",5]]}}

![image](https://user-images.githubusercontent.com/71989691/101463728-ce436180-3963-11eb-8c13-7d20d2b14ec4.png)

**Date can not be this - [1,2,"2016-05-32",5]**

{"headers":{"Activity":["player_id","device_id","event_date","games_played"]},"rows":{"Activity":[[1,2,"2016-05-32",5],[1,2,"2016-05-02",6],[2,3,"2017-06-25",1],[3,1,"2016-03-02",0],[3,4,"2018-07-03",5]]}}

![image](https://user-images.githubusercontent.com/71989691/101464437-a6a0c900-3964-11eb-9704-1ea094966f65.png)

![image](https://user-images.githubusercontent.com/71989691/101464601-db148500-3964-11eb-9ce4-552df037372c.png)

**Accepting -ve dates:** 

{"headers":{"Activity":["player_id","device_id","event_date","games_played"]},"rows":{"Activity":[[1,2,"-1900-01-01",5],[1,2,"2016-05-02",6],[2,3,"2017-06-25",1],[3,1,"2016-03-02",0],[3,4,"2018-07-03",5]]}}

![image](https://user-images.githubusercontent.com/71989691/101464889-4199a300-3965-11eb-87f9-82485c462350.png)

**Not accepting dates<=1899**

{"headers":{"Activity":["player_id","device_id","event_date","games_played"]},"rows":{"Activity":[[1,2,"1899-01-01",5],[1,2,"2016-05-02",6],[2,3,"2017-06-25",1],[3,1,"2016-03-02",0],[3,4,"2018-07-03",5]]}}

![image](https://user-images.githubusercontent.com/71989691/101465038-73126e80-3965-11eb-8893-1fb7c5223058.png)

#### Code you used for Submit/Run operation

```
# Write your MySQL query statement below
SELECT A.PLAYER_ID, MIN(A.EVENT_DATE) AS FIRST_LOGIN FROM ACTIVITY AS A
GROUP BY A.PLAYER_ID
```

#### Language used for code

MySQL

#### Expected behavior

Accepting the wrong input case

#### Additional context

Problem: https://leetcode.com/problems/game-play-analysis-i/

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @pratap-082020  ,
Thank you for your time. Upon investigating this issue, we have acknowledged the issue. However, we found this kind of report is not eligible for a reward.
