### ISSUE TITLE
Missing Test Case - 2722. Join Two Arrays by ID

### ISSUE THREAD

**Issue by RonaldBarnes** [LeetCode-Feedback/LeetCode-Feedback#16007]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Existing test cases do not test for "**The returned array should be sorted in ascending order based on the id key.**"

This test case will:
 - test for sorting of output
 - test that sortation is numeric, not default (string) sorting (1,10,2,3) vs (1,2,3,10)

#### Code you used for Submit/Run operation

```
var join = function(arr1, arr2)
  {
  // Map guarantees unique values:
  retVal = new Map();

  // Iterate over both arrays by spreading them:
  [...arr1,...arr2].map( val =>
    // Map key is value's id and value is entire, spread array element,
    // which over-writes existing values with updated ones:
    retVal.set(val.id, {...retVal.get(val.id),...val})
    );  // end map()

  /**
   * "The returned array should be sorted in ascending
   * order based on the id key"
   */
  return Array.from(retVal.values()).sort( (a,b) => a.id - b.id);
  };  // end join()
```

#### Language used for code

JavaScript

#### Expected behavior

The following test data should output in order of `id` ascending but several (many / most?) solutions do not test for this and get accepted because test data is always in sequence:

```
// Example 1 (with reversed id:1 and id:2 to test sorting):
// Also testing for default (string, not numeric) sorting (1,10,2,...):
arr1 = [
  {"id":2, "x": "B"},
  {"id": 1,"x": "A"},
  ];
arr2 = [
  {"id":10, "x":"J"},
  {"id": 3,"x": "C"},
  ];
console.log("Example 1 RESULTS:");
console.table(join(arr1, arr2));
```

#### Additional context

Expected output:
```
Example 1 RESULTS:
┌─────────┬────┬─────┐
│ (index) │ id │  x  │
├─────────┼────┼─────┤
│    0    │ 1  │ 'A' │
│    1    │ 2  │ 'B' │
│    2    │ 3  │ 'C' │
│    3    │ 10 │ 'J' │
└─────────┴────┴─────┘
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by RonaldBarnes** [comment]
Thank you @LC-Pam!

I edited this issue for legibility on the test data.


Also, I've come up with another scenario that can cause an accepted solution to fail (testing against my coding partner's solution).

Unsure if it's a new issue or if I ought to append to this one?

**Comment by RonaldBarnes** [comment]
Here's the follow-up:

```
arr1 = [
  {"id": 2, "x":"B", "msg":"overwrite this"},
  {"id": 1, "x": "A"},
  ];
arr2 = [
  {"id":10, "x": "J"},
  {"id":2, "msg":"not done yet"},
  {"id":3, "x": "C"},
  {"id":2, "msg":"correct!"},
  ];
console.log("Example 1 RESULTS:");
console.table(join(arr1,arr2));
```

With the above test data, I see two different output datasets:

```
Example 1 RESULTS:
┌─────────┬────┬─────┬────────────┐
│ (index) │ id │  x  │    msg     │
├─────────┼────┼─────┼────────────┤
│    0    │ 1  │ 'A' │            │
│    1    │ 2  │ 'B' │ 'correct!' │
│    2    │ 3  │ 'C' │            │
│    3    │ 10 │ 'J' │            │
└─────────┴────┴─────┴────────────┘
┌─────────┬────┬─────┬────────────────┐
│ (index) │ id │  x  │      msg       │
├─────────┼────┼─────┼────────────────┤
│    0    │ 1  │ 'A' │                │
│    1    │ 2  │ 'B' │ 'not done yet' │
│    2    │ 3  │ 'C' │                │
│    3    │ 10 │ 'J' │                │
└─────────┴────┴─────┴────────────────┘
```

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
