### ISSUE TITLE
Incorrect Test Case - 115. Distinct Subsequences

### ISSUE THREAD

**Issue by abuhujair** [LeetCode-Feedback/LeetCode-Feedback#16019]
#### Your LeetCode username

abuhujair

#### Category of the bug
- [1 ] Incorrect Test Case

 

#### Description of the bug

Test Case 65 with input string s = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", t = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", is incorrect, as per the constraint of the question. The number of distinct subsequences for this test case will be 68C31 = 2.191287e+19 which is greater than what 32-bit signed integer can store. Hence this test cases need to be removed.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int numDistinct(string s, string t){
        int m = s.size(), n = t.size();
        if(m<n) return 0;
        int dp[m+1][n+1];
        // vector<vector<int>> dp(m+1, vector<int>(n+1, 0));
        
        for(int r = 0; r<=m; r++){
            dp[r][0] = 1;
        }

        for(int c=1; c<=n; c++){
            dp[c-1][c] = 0;
            for(int r=c; r<=m; r++){
                dp[r][c] = dp[r-1][c];
                if(s[r-1] == t[c-1])
                    dp[r][c] += (long long)dp[r-1][c-1];
            }
        }

        return (int)dp[m][n];
    }
};
```

#### Language used for code

C++

#### Expected behavior

Test Case 65 with input string s = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", t = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", is incorrect, as per the constraint of the question. The number of distinct subsequences for this test case will be 2.191287e+19 which is greater than what 32-bit signed integer can store. Hence this test cases need to be removed.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by abuhujair** [comment]
Hello, I am yet to receive the Leetcode Points associated with the above issue.
