### ISSUE TITLE
512. Game Play Analysis II - Accepting incorrect inputs

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1601]
#### Your LeetCode username

[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

**Accepting incorrect inputs -** 

**The date can not be-  2018-13-32**

{"headers":{"Activity":["player_id","device_id","event_date","games_played"]},"rows":{"Activity":[[1,2,"2016-03-01",5],[1,2,"2016-05-02",6],[2,3,"2017-06-25",1],[3,1,"2016-03-02",0],[3,4,"2018-13-32",5]]}}

![image](https://user-images.githubusercontent.com/71989691/101468520-8a535b00-3969-11eb-9880-aab5051d1940.png)

**Allowing negative date.**

{"headers":{"Activity":["player_id","device_id","event_date","games_played"]},"rows":{"Activity":[[1,2,"2016-03-01",5],[1,2,"2016-05-02",6],[2,3,"2017-06-25",1],[3,1,"2016-03-02",0],[3,4,"-2018-12-31",5]]}}

![image](https://user-images.githubusercontent.com/71989691/101468731-ce466000-3969-11eb-8baa-107e29e970a6.png)

**Accepting "0000-00-00" in date**

{"headers":{"Activity":["player_id","device_id","event_date","games_played"]},"rows":{"Activity":[[1,2,"2016-03-01",5],[1,2,"2016-05-02",6],[2,3,"2017-06-25",1],[3,1,"2016-03-02",0],[3,4,"0000-00-00",5]]}}

![image](https://user-images.githubusercontent.com/71989691/101468915-09e12a00-396a-11eb-939b-aaec07abb185.png)

**Accepting string "null" in date-**

{"headers":{"Activity":["player_id","device_id","event_date","games_played"]},"rows":{"Activity":[[1,2,"2016-03-01",5],[1,2,"2016-05-02",6],[2,3,"2017-06-25",1],[3,1,"2016-03-02",0],[3,4,"null",5]]}}

![image](https://user-images.githubusercontent.com/71989691/101469034-3301ba80-396a-11eb-94d8-13085ec4cdd4.png)

#### Code you used for Submit/Run operation

```
#MySQL 
SELECT TEMP.player_id, b.DEVICE_ID FROM
(
    SELECT A.PLAYER_ID, MIN(A.EVENT_DATE) AS EVENT_DATE FROM ACTIVITY AS A
    GROUP BY A.PLAYER_ID
) AS TEMP
    
left join activity as b 
on TEMP.player_id = b.player_id
and TEMP.event_date = b.event_date
```

#### Language used for code

MySQL

#### Expected behavior

Accepting incorrect inputs. Should not allow accepting incorrect inputs.

#### Additional context

Problem: https://leetcode.com/problems/game-play-analysis-ii/

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @pratap-082020  ,
Thank you for your time. Upon investigating this issue, we have acknowledged the issue. However, we found this kind of report is not eligible for a reward.
