### ISSUE TITLE
Editorial typo - 2366. Minimum Replacements to Sort the Array

### ISSUE THREAD

**Issue by xelplogoog** [LeetCode-Feedback/LeetCode-Feedback#16028]
#### Your LeetCode username
c4tdog

#### Description of the bug
https://leetcode.com/problems/minimum-replacements-to-sort-the-array/editorial/
There is a typo in word `return`

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2188302/cd01e03a-e9c9-4685-9ed3-5771810e78ad)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
