### ISSUE TITLE
Description Typo:30.Substring with Concatenation of All Words

### ISSUE THREAD

**Issue by Vishal2806** [LeetCode-Feedback/LeetCode-Feedback#16022]
#### Your LeetCode username

vishal_2806

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
  class Solution {
public:
    vector<int> findSubstring(string s, vector<string>& words) {
        
    }
};

```

#### Expected behavior

There is a grammatical mistake in the explanation of example number 2 , where it is written "is" insead of "in" 
This is the mistaken paragraph "There is no substring of length 16 is s that is equal to the concatenation of any permutation of words."

#### Screenshots

![Screenshot (16)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/88826207/2224af69-a681-4e95-a57e-8d8210caedbe)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
