### ISSUE TITLE
Missing Test Case - 290. Word Pattern

### ISSUE THREAD

**Issue by tagrn** [LeetCode-Feedback/LeetCode-Feedback#16027]
#### Your LeetCode username

Taewan-Gu

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

I think there should be two `constructor` test cases (true, false).

In JS or TS, we cannot assign a `constructor` key to an object, but the last test case is only a test case that is true. So, I can easily get success if I return `true` when `constructor` in the testcase.

#### Code you used for Submit/Run operation

```ts
// Word Pattern
function wordPattern(pattern: string, s: string): boolean {
    const [mem, mem2] = [{}, {}]
    let t = s.split(" ")
    if (pattern.length !== t.length) return false

    for (let i=0; i<pattern.length; i++) {
        if (t[i] === "constructor") {
            return true
        }
        if (!mem[pattern[i]]) {
            mem[pattern[i]] = t[i]
        } else {
            if (mem[pattern[i]] !== t[i]) {
                return false
            }
        }
        if (!mem2[t[i]]) {
            mem2[t[i]] = pattern[i]
        } else {
            if (mem2[t[i]] !== pattern[i]) {
                return false
            }
        }
    }

    return true
};
```

#### Language used for code

Typescript, Javascript

#### Expected behavior

pattern = `abba`, s = `dog constructor constructo dog`

ans = `false`

but, the code answer `true`

#### Screenshots

<img width="1435" alt="Screenshot 2023-08-30 at 9 25 50 AM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/68409255/cda2b0d8-1f86-4101-b0ab-76cd4a856448">
<img width="1425" alt="Screenshot 2023-08-30 at 9 26 22 AM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/68409255/6a933392-b227-4040-8210-927774c5d251">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
