### ISSUE TITLE
Wrong TestCase - 115. Distinct Subsequences

### ISSUE THREAD

**Issue by Jeetaksh** [LeetCode-Feedback/LeetCode-Feedback#16023]
#### Your LeetCode username
Jeetaksh

#### Category of the bug
 Test Cases 

#### Description of the bug
There is a recently added testcase which is giving wrong outputs.
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/92541718/845d556e-0c03-492b-bfe1-2d948f3690b0)

We have to determine number of distinct subsequences, how can there be -1 subsequences ? 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int numDistinct(string s, string t) {
        int m=s.size(),n=t.size();
        vector<long double> dp(n+1);
        dp[0]=1;
        for(int i=1;i<=m;i++){
            for(int j=n;j>=1;j--){
                if(s[i-1]==t[j-1]){
                    dp[j]+=dp[j-1];
                    if(dp[j]>=INT_MAX){
                        dp[j]= INT_MAX;
                    }
                }
            }
        }
        return dp[n];
    }
};
```

#### Language used for code
C++

#### Expected behavior
The answer of the testcase is wrong. It needs to be modified.

#### Screenshots
Added above

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
