### ISSUE TITLE
577. Employee Bonus - Accepting incorrect inputs

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1602]
#### Your LeetCode username

[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Accepting incorrect inputs with wrong data type - 

{"headers": {"Employee": ["EmpId", "Name", "Supervisor", "Salary"], "Bonus": ["EmpId", "Bonus"]}, "rows": {"Employee": [[3, "Brad", null, 4000], [1, "John", 3, 1000], [2, "Dan", 3, 2000], [4, "Thomas", 3, **"4000"**]], "Bonus": [[**"2", "500"**], [4, 2000]]}}

![image](https://user-images.githubusercontent.com/71989691/101474540-52501600-3971-11eb-8dfa-e6b2721f6650.png)

#### Code you used for Submit/Run operation

```
select temp.name, temp.bonus from
(
SELECT A.NAME, B.BONUS FROM EMPLOYEE AS A

LEFT JOIN BONUS AS B
ON A.EMPID = B.EMPID
) as temp

where
temp.bonus IS NULL
or temp.bonus < 1000;
```

#### Language used for code

MySQL

#### Expected behavior

Accepting incorrect inputs

#### Additional context

Problem: https://leetcode.com/problems/employee-bonus/

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @pratap-082020  ,
Thank you for your time. Upon investigating this issue, we have acknowledged the issue. However, we found this kind of report is not eligible for a reward.
