### ISSUE TITLE
Incorrect editorial statement - 2366. Minimum Replacements to Sort the Array

### ISSUE THREAD

**Issue by danielkmc** [LeetCode-Feedback/LeetCode-Feedback#16029]
#### Your LeetCode username
danielkmc

#### Category of the bug
Solution

#### Description of the bug
The editorial says
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/46427503/c79eba2e-238e-4029-beb7-03598a2ec727)

I don't think the second point is true for the example input of [31, 9] -> [7, 8, 8, 8, 9]. The smallest element would be 7 when splitting 31 based on the next number. 

#### Expected behavior
I think it would be more correct to say that the smallest element will be ```nums[i]/num_elements```, but I'm not sure.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
