### ISSUE TITLE
Unclear Description - 115. Distinct Subsequences

### ISSUE THREAD

**Issue by haoning-w** [LeetCode-Feedback/LeetCode-Feedback#16024]
#### Your LeetCode username

obiwan_k

#### Category of the bug
- [√] Question

#### Description of the bug

Testcases 65 and 66 will give results bigger than 32-bit integer. According to the expected answer, we should return -1 in these situations. That's fine and reasonable. However, the description should clearly tell us what should be returned in situation like this. Otherwise, it's very confusing what we should return when the result is bigger than 32-bit integer.

#### Code you used for Submit/Run operation

```
class Solution {
    int dp(String s, int i, String t, int j, int[][] memo) {
        if (j == t.length()) {
            return 1;
        }
        if (s.length() - i < t.length() - j) {
            return 0;
        }
        if (memo[i][j] != -1) {
            return memo[i][j];
        }
        int res;
        if (s.charAt(i) == t.charAt(j)) {
            res = dp(s, i + 1, t, j, memo) + dp(s, i + 1, t, j + 1, memo);
        } else {
            res = dp(s, i + 1, t, j, memo);
        }
        memo[i][j] = res;
        return res;
    }

    public int numDistinct(String s, String t) {
        int[][] memo = new int[s.length()][t.length()];
        for (int[] line : memo) {
            Arrays.fill(line, -1);
        }
        return dp(s, 0, t, 0, memo);
    }
}
```

#### Language used for code

Java

#### Expected behavior

Describe clearly what should be returned if the result is bigger than a 32-bit integer.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
