### ISSUE TITLE
Missing Test Case - 1571. Warehouse Manager

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1603]
#### Your LeetCode username

[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

**A test case is missing -** 

{"headers": {"Warehouse": ["name", "product_id", "units"], "Products": ["product_id", "product_name", "Width", "Length", "Height"]}, "rows": {"Warehouse": [["LCHouse1", 1, 1], ["LCHouse1", null, null], ["LCHouse1", 3, 5], ["LCHouse2", 1, 2], ["LCHouse2", 2, 2], ["LCHouse3", 4, 1]], "Products": []}}

![image](https://user-images.githubusercontent.com/71989691/101477485-49f9da00-3975-11eb-8467-5dbc34c7b622.png)

#### Code you used for Submit/Run operation

```
# Write your MySQL query statement below

SELECT TMP.WAREHOUSE_NAME, SUM((TMP.CALC) * TMP.UNITS) AS VOLUME FROM
(
    SELECT  B.NAME AS WAREHOUSE_NAME, B.PRODUCT_ID, B.UNITS, C.CALC FROM WAREHOUSE AS B

    LEFT JOIN 
    (
        SELECT A.PRODUCT_ID, A.PRODUCT_NAME, A.WIDTH * A.LENGTH * A.HEIGHT AS CALC FROM PRODUCTS AS A
    ) AS C
    ON C.PRODUCT_ID = B.PRODUCT_ID

) AS TMP
GROUP BY TMP.WAREHOUSE_NAME
```

#### Language used for code

MySQL

#### Expected behavior

**A test case is missing -** 

**Your input**
{"headers": {"Warehouse": ["name", "product_id", "units"], "Products": ["product_id", "product_name", "Width", "Length", "Height"]}, "rows": {"Warehouse": [["LCHouse1", 1, 1], ["LCHouse1", null, null], ["LCHouse1", 3, 5], ["LCHouse2", 1, 2], ["LCHouse2", 2, 2], ["LCHouse3", 4, 1]], "Products": []}}

**Output**
{"headers": ["WAREHOUSE_NAME", "VOLUME"], "values": [["LCHouse1", null], ["LCHouse2", null], ["LCHouse3", null]]}

**Expected**
{"headers": ["WAREHOUSE_NAME", "VOLUME"], "values": []}

#### Additional context

Problem - https://leetcode.com/problems/warehouse-manager/

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
