### ISSUE TITLE
Missing Test Case - 110. Balanced Binary Tree

### ISSUE THREAD

**Issue by anaalamed** [LeetCode-Feedback/LeetCode-Feedback#16036]
#### Your LeetCode username
anaalamed

#### Category of the bug
Missing Test Cases 

#### Description of the bug
The additional test case - example  [1,2,2,3,null,3,3,4,null, 4,4,4, 4]

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean isBalanced(TreeNode root) {
        return getHeight(root) != -1;
    }

    int getHeight(TreeNode root) {
        if (root == null) {
            return 0;
        } 

        int left = getHeight(root.left);
        int right = getHeight(root.right);

        if (left == -1 || right == -1) {
            return -1;
        }

        if ((Math.abs(left - right)) > 1 ) {
            return -1; 
        }

        return Math.max(left, right) + 1;
    }
}
```

#### Language used for code
Java 

#### Expected behavior
Each subtree should be balanced

#### Screenshots
![Screenshot 2023-08-30 10 24 23 AM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/75525964/084a30b5-184d-4a15-acf8-cf7662d3f6a4)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

[1,2,2,3,null,3,3,4,null, 4,4,4, 4] already exists.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
