### ISSUE TITLE
1119. Remove Vowels from a String - Accepting incorrect test cases 

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1604]
#### Your LeetCode username

[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

**As per the problem description - Platform should not allow mentioned inputs below :** 

Note:
S consists of lowercase English letters only.
1 <= S.length <= 1000**

Accepting incorrect test cases - 

**- Should not allow UPPER CASE LETTER in inputs**

**"ABCDS"**

![image](https://user-images.githubusercontent.com/71989691/101479128-b1188e00-3977-11eb-941d-24a6b4a5adb0.png)

**- Should not allow NUMBERS in inputs**

**"123"**

![image](https://user-images.githubusercontent.com/71989691/101478785-3780a000-3977-11eb-8abf-f05df14db7a4.png)

**- Should not allow special CHARACTERS in inputs

"1@@@23"**

![image](https://user-images.githubusercontent.com/71989691/101478932-6860d500-3977-11eb-911e-491700ee85dc.png)

#### Code you used for Submit/Run operation

Python3

#### Expected behavior

**Accepting invalid test cases - 

- Should not allow UPPER CASE LETTER in inputs
- Should not allow NUMBERS in inputs
- Should not allow special CHARACTERS in inputs**

#### Additional context

Problem: [1119. Remove Vowels from a String](https://leetcode.com/problems/remove-vowels-from-a-string/)

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
