### ISSUE TITLE
Problem 166 rejecting correct answer

### ISSUE THREAD

**Issue by gasper6** [LeetCode-Feedback/LeetCode-Feedback#16041]
#### Your LeetCode username
Johnnius_

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Hi there.

In problem 166 (Fraction to Recurring Decimal) my code produces correct answer, which was not accepted.

Description says: "If multiple answers are possible, return any of them."

For test case
```
numerator = 7
denominator = -12
```
the division results in -0.5833333..., which can be written as "-0.583(3)". My code outputted this answer, which was rejected for some reason.

Please review either description or testcase evaluations.

Thanks,
Jan

#### Code you used for Submit/Run operation
```
class Solution:
    def fractionToDecimal(self, n: int, d: int) -> str:
        is_negative = ((n < 0) ^ (d < 0)) and n != 0
        n = abs(n)
        d = abs(d) 
        div, mod = divmod(n, d) 

        ans = ("-" if is_negative else "") + str(div) + ("." if mod else "")
        divs = {}
        mods = {} 

        while mod:
            div, next_mod = divmod(mod*10, d)
            if next_mod in divs:
                ans += "("
                ans += str(div)
                while next_mod != mod:
                    ans += divs[next_mod]
                    next_mod = mods[next_mod]
                ans += ")"
                return ans
            divs[mod] = str(div)
            mods[mod] = next_mod
            mod = next_mod
            ans += str(div)
        return ans
```

#### Language used for code
python

#### Expected behavior

For test case
```
numerator = 7
denominator = -12
```
the division results in -0.5833333..., which can be written as "-0.583(3)". My code outputted this answer, which was rejected for some reason.

#### Screenshots
Redundant for this issue

#### Additional context
Description says: "If multiple answers are possible, return any of them."
My answer was definitely correct way.

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team

**Comment by gasper6** [comment]
Hello.

Unfortunately, i do not consider your answer satisfactory. My solution does match the description of the problem. If you disagree, please explainin what regard my solution deviates from description.

If you fail to explain, I will assume that my answer is correct. I can see that my solution yields different answers than testing expects. But the description clearly says that any correct answer will be accepted.

Please fix the testing for this problem or explain why my answer is not correct.
