### ISSUE TITLE
Missing Test Case - 2366. Minimum Replacements to Sort the Array

### ISSUE THREAD

**Issue by YashPatil-09** [LeetCode-Feedback/LeetCode-Feedback#16045]
#### Your LeetCode username
yashpatil643

#### Category of the bug
- [ ] Solution

#### Description of the bug
Some test cases give wrong answers and thus solution is not accepted.
For example, the platform expects the solution of the test case [17,18,7] to be 4,
but actually, 5 is the correct answer.
The most optimal way the above array can be broken down into sorted arrays is as :

[17, 18, 7]
17, 11, 7, 7:     replacement no. 1 (18 replaced with 11 and 7)
17, 5, 6, 7, 7:     replacement no. 2 (11 replaced with 5 and 6)
12, 5, 5, 6, 7, 7:     replacement no. 3 (17 replaced with 12 and 5)
7, 5, 5, 5, 6, 7, 7:     replacement no. 4 (12 replaced with 7 and 5)
3, 4, 5, 5, 5, 6, 7, 7:     replacement no. 5 (7 replaced with 3 and 4) 

this way the answer should be 5 but the expected answer by the platform is 4.

#### Code you used for Submit/Run operation

```
//Minimum Replacements to Sort the Array
class Solution {
    static long ops=0;
    public int split(int cr , int end)
    {
        System.out.println("cr: "+cr+" | end: "+end);
        ops+=1;
        int a = cr/2;
        int b = cr-a;

        if(b<=end) return a;

        else
        {
            return split(cr-end,end);
        }
    }

    public long minimumReplacement(int[] nums) {
        int end=nums[nums.length-1];
        for(int i=nums.length-2; i>=0; i--)
        {
            int cr=nums[i];
            
            if(cr<=end)end=cr;
            else
            {   
                end=split(cr,end);
            }
        }

        long ans =ops;
        ops=0;
        return ans;
    }
}

```

#### Language used for code
Java

#### Expected behavior

Testcase [17,18,7],
[17,18,8],
[368,112,2,282,349,127,36,98,371,79,309,221,175,262,224,215,230,250,84,269,384,328,118,97,17,105,342,344,242,160,394,17,120,335,76,101,260,244,378,375,164,190,320,376,197,398,353,138,362,38,54,172,3,300,264,165,251,24,312,355,237,314,397,101,117,268,36,165,373,269,351,67,263,332,296,13,118,294,159,137,82,288,250,131,354,261,192,111,16,139,261,295,112,121,234,335,256,303,328,242,260,346,22,277,179,223]
give wrong output as 4 , 4, and 17748, respectively.
Output 5,5,19832 are expected outputs respectively.

Try to find output for 17,18,8 on paper and compare it with platform solution, it is contrasting.

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team

**Comment by YashPatil-09** [comment]
It would be a great help if I get to know how no. of replacements needed
to be done for [17,18,7] are 4 but not 5. I have tried finding it out but I
could not get optimal split of 4. This will surely clear the doubt which I
thought was discrepancy. Thank you.
