### ISSUE TITLE
Wrong data in the figure in the Editorial

### ISSUE THREAD

**Issue by harrrykp** [LeetCode-Feedback/LeetCode-Feedback#16044]
#### Your LeetCode username
Harrykp

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the editorial of [this](https://leetcode.com/problems/minimum-replacements-to-sort-the-array/editorial/) question, a figure has incorrect representation. The figure in the editorial shows the breaking of the number `[7] -> [2,3,3]` which is wrong.

#### Expected behavior
The correct one is `[7] -> [2,2,3]`.

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/125436773/31c239ca-372f-4038-9a54-ba89749607ba)

#### Additional context
You can find the given figure after this line
`Please refer to the picture below as a detailed example:` in the editorial section of the above question.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
