### ISSUE TITLE
1378. Replace Employee ID With The Unique Identifier -  Accepting invalid test case

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1605]
#### Your LeetCode username

[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Accepting invalid test case - 

Accepting the wrong data type here - 

{"headers":{"Employees":["id","name"],"EmployeeUNI":["id","unique_id"]},"rows":{"Employees":[[1,"Alice"],[7,"Bob"],[11,"Meir"],[90,"Winston"],[3,"Jonathan"]],"EmployeeUNI":[[3,1],[11,2],[**"90","3"**]]}}

![image](https://user-images.githubusercontent.com/71989691/101480847-3d2bb500-397a-11eb-96e7-00654e3da2af.png)

#### Code you used for Submit/Run operation

```
# Write your MySQL query statement below
SELECT A.NAME, B.UNIQUE_ID FROM EMPLOYEES AS A
LEFT JOIN EMPLOYEEUNI AS B
ON A.ID = B.ID
```

#### Language used for code

MySQL

#### Expected behavior

Accepting invalid test case

#### Additional context

Problem - https://leetcode.com/problems/replace-employee-id-with-the-unique-identifier/

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @pratap-082020  ,
Thank you for your time. Upon investigating this issue, we have acknowledged the issue. However, we found this kind of report is not eligible for a reward.
