### ISSUE TITLE
Missing Test Case - 8. String to Integer (atoi)

### ISSUE THREAD

**Issue by jtorruellas22** [LeetCode-Feedback/LeetCode-Feedback#16053]
#### Your LeetCode username
 jant0802

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I believe one of the test cases has an incorrect answer. Test case is string : "words and 987" where I believe the expected answer should be 987; however, it states the expected answer is 0.

#### Code you used for Submit/Run operation

''' 

```
#include <list>
class Solution {
public:
    int myAtoi(string s) {
        char sign;
        string ans;
        for (char c : s) {
            if (isspace(c))
                continue;
            if (ans.empty() && !isdigit(c) && !isalpha(c))
                sign = c;
            if (isdigit(c))
                ans += c;
            if (!ans.empty() && isalpha(c))
                break;
        }
        long num = stol(ans);
        if (sign == '-')
            num *= -1;
        if (num > INT_MAX) 
            return INT_MAX;
        if (num < INT_MIN)
            return INT_MIN;
        return int(num);
    }
};
```

#### Expected behavior

With the code I have written it is expected to return a value of 987. It does return a value of 987 but the expected answer per the test case is 0. Please reference the screenshot below.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/116301075/cf8a867a-d402-4da2-b792-f879ee676c1d)

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
