### ISSUE TITLE
Spelling correction - 1326. Minimum Number of Taps to Open to Water a Garden

### ISSUE THREAD

**Issue by YogeshP93** [LeetCode-Feedback/LeetCode-Feedback#16058]
#### Your LeetCode username

https://leetcode.com/Baymax_/

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Spelling/grammar correction in - [1326. Minimum Number of Taps to Open to Water a Garden](https://leetcode.com/problems/minimum-number-of-taps-to-open-to-water-a-garden/)
There is a statement - "The garden starts at the point `0` and ends at the point `n`. (i.e The length of the garden is `n`)."

#### Expected behavior

- the word `i.e` should be `i.e.` (missing '.' after the e) and a missing ',' after that.
- the word `The` should be `the` (as it is not the first word of the sentence)

Overall, the statement should be - "The garden starts at the point `0` and ends at the point `n`. (i.e., the length of the garden is `n`)."

#### Screenshots

![Screenshot 2023-08-31 112826](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/122779284/23926f7b-2060-409a-a35a-c4a8ec4d2c40)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
