### ISSUE TITLE
Pandas schema incorrect - 1795. Rearrange Products Table

### ISSUE THREAD

**Issue by bkocis** [LeetCode-Feedback/LeetCode-Feedback#16062]
#### Your LeetCode username
 Balȧzs Kocsis 

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The provided pandas schema in the question has a type definition typo
```python
data = [[0, 95, 100, 105], [1, 70, None, 80]]
Products = pd.DataFrame(data, columns=['product_id', 'store1', 'store2', 'store3']).astype({'product_id':'int64', 'store1':'int64', 'store2':'int64', 'store3':'int64'})
```

#### Expected behavior
```python
products = pd.DataFrame(data, columns=['product_id', 'store1', 'store2', 'store3']).astype({'product_id':'Int64', 'store1':'Int64', 'store2':'Int64', 'store3':'Int64'}) 
```
The "int64" should be corrected to "Int64"

#### Additional context
(https://stackoverflow.com/questions/21287624/convert-pandas-column-containing-nans-to-dtype-int)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

The problem is fixed.

Please provide us with your LCCN/LCUS username in order to receive a 100 Leetcoins reward.

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!

**Comment by bkocis** [comment]
user3191D

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
