### ISSUE TITLE
1251. Average Selling Price - Accepting incorrect data type input

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1606]
#### Your LeetCode username

[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

**Accepting incorrect data type input here - > must be number here but accepting string -**

{"headers":{"Prices":["product_id","start_date","end_date","price"],"UnitsSold":["product_id","purchase_date","units"]},"rows":{"Prices":[["1","2019-02-17","2019-02-28","5"]],"UnitsSold":[["1","2019-02-25","100.21"]]}}

![image](https://user-images.githubusercontent.com/71989691/101488358-82091900-3985-11eb-8b17-fcf1f3f6bbc3.png)

#### Code you used for Submit/Run operation

```
# Write your MySQL query statement below

SELECT TEMP.PRODUCT_ID, ROUND(SUM(TEMP.AMOUNT) / SUM(TEMP.UNITS),2) AS AVERAGE_PRICE FROM
(    
    SELECT A.PRODUCT_ID, (A.PRICE * B.UNITS) AS AMOUNT, B.UNITS AS UNITS FROM PRICES AS A

    LEFT JOIN UNITSSOLD AS B
    ON A.PRODUCT_ID = B.PRODUCT_ID 
    AND B.PURCHASE_DATE BETWEEN A.START_DATE AND A.END_DATE
) AS TEMP
GROUP BY TEMP.PRODUCT_ID
```

#### Expected behavior

Accepting incorrect data type input. It must be a number type

#### Additional context

Problem: https://leetcode.com/problems/average-selling-price/

**Comment by lc-kay** [comment]
@pratap-082020
Thank you for your time. We have acknowledged the issue. However, we found this kind of report is not eligible for a reward.
