### ISSUE TITLE
Missing Pandas Schema - 177. Nth Highest Salary

### ISSUE THREAD

**Issue by TrickyCat** [LeetCode-Feedback/LeetCode-Feedback#16073]
#### Your LeetCode username
[TrickyCat](https://leetcode.com/TrickyCat/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Hi there 👋👋!

Following the "30 Days of Pandas" challenge I encountered one problem that does not have the Pandas schema for the question [177. Nth Highest Salary](https://leetcode.com/problems/nth-highest-salary/)

Other questions in the challenge have it.

So, the closest hack that worked for me was using the Pandas schema from the sibling question [176. Second Highest Salary](https://leetcode.com/problems/second-highest-salary/)

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/855874/a49284ae-968c-42cf-9698-d8e80efdf66a)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/855874/4e699392-6b00-4e30-8c29-4f375f8997bc)

#### Additional context

Please, add the schema to the question 😉

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
