### ISSUE TITLE
Missing Test Case - 1326. Minimum Number of Taps to Open to Water a Garden

### ISSUE THREAD

**Issue by Master-sanjeev** [LeetCode-Feedback/LeetCode-Feedback#16072]
TC: 
n = 10
ranges = [1,1,1,1,1,1,1,1,1,1,1]

#### Your LeetCode username

MasterSanjeev

#### Category of the bug
- [ ] Question
- Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

If we pick this combination: [1,**1**,1,1,**1**,1,1,**1**,1,1,**1**]
then we can get our work done in 4 taps only whereas the expected answer is 5. 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    public int minTaps(int n, int[] ranges) {
        List<Integer>[] covered = new ArrayList[n+1];
        //covered[i] stores the j's which covers i
        for (int i=0; i<=n; i++) {
            covered[i] = new ArrayList<>();
        }
        for(int i=0; i<=n; i++){
            if(ranges[i]>0){
                fillTowardsLeft(covered,i,ranges[i]);
                fillTowardsRight(covered,i,ranges[i]);
            }
        }
        int taps = 0;
        int i=0;
        while (i<=n) {
            if(covered[i].size() == 0) {
                return -1;
            }
            int max_range = 0, max_j=-1;
            for(int j : covered[i]) {
                if(j+ranges[j]>max_range){
                    max_range = j+ranges[j];
                }
            }
            i = max_range+1;
            taps++;
        }
        return taps;
    }

    public void fillTowardsRight(List<Integer>[] covered, int i, int range) {
        for(int j=0; i+j<covered.length && j<=range; j++){
            covered[i+j].add(i);
        }
    }

    public void fillTowardsLeft(List<Integer>[] covered, int i, int range) {
        for(int j=0; i-j>=0 && j<=range; j++){
            covered[i-j].add(i);
        }
    }
}
```

#### Expected behavior

Correct answer should be 4

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
