### ISSUE TITLE
Missing Test Case - 1068. Product Sales Analysis I

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1607]
#### Your LeetCode username

[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

**Query unable to pass the below test case -** 

{"headers":{"Sales":["sale_id","product_id","year","quantity","price"],"Product":["product_id","product_name"]},"rows":{"Sales":[[1,100,2008,10,5000],[2,100,2009,12,5000],[7,200,2011,15,9000]],"Product":[]}}

![image](https://user-images.githubusercontent.com/71989691/101489493-0740fd80-3987-11eb-9fee-3cf45e6eb0d4.png)

# Write your MySQL query statement below
MySQL

#### Code you used for Submit/Run operation

```
SELECT B.PRODUCT_NAME AS PRODUCT_NAME, A.YEAR AS YEAR, A.PRICE AS PRICE FROM SALES AS A
LEFT JOIN PRODUCT AS B
ON A.PRODUCT_ID = B.PRODUCT_ID
```

#### Expected behavior

**Missing Test Case-**

{"headers":{"Sales":["sale_id","product_id","year","quantity","price"],"Product":["product_id","product_name"]},"rows":{"Sales":[[1,100,2008,10,5000],[2,100,2009,12,5000],[7,200,2011,15,9000]],"Product":[]}}

#### Additional context

Problem - https://leetcode.com/problems/product-sales-analysis-i/

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
