### ISSUE TITLE
1068. Product Sales Analysis I - Accepting wrong test cases

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1608]
#### Your LeetCode username

[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

**Accepting the wrong test case -** 

{"headers":{"Sales":["sale_id","product_id","year","quantity","price"],"Product":["product_id","product_name"]},"rows":{"Sales":[["1","100","2008","10","5000"]],"Product":[[100,"NOKIA"]]}}

![image](https://user-images.githubusercontent.com/71989691/101490965-204aae00-3989-11eb-9643-df8991dcd242.png)

#### Code you used for Submit/Run operation

```
# Write your MySQL query statement below

SELECT B.PRODUCT_NAME AS PRODUCT_NAME, A.YEAR AS YEAR, A.PRICE AS PRICE FROM SALES AS A
LEFT JOIN PRODUCT AS B
ON A.PRODUCT_ID = B.PRODUCT_ID
```

#### Language used for code

MySQL

#### Expected behavior

Accepting the wrong test case

#### Additional context

Problem - https://leetcode.com/problems/product-sales-analysis-i/

**Comment by lc-kay** [comment]
@pratap-082020 Thank you for your time. We have acknowledged the issue. However, we found this kind of report is not eligible for a reward.
