### ISSUE TITLE
Missing Test Case - 1484. Group Sold Products By The Date

### ISSUE THREAD

**Issue by ashutosh-2002** [LeetCode-Feedback/LeetCode-Feedback#16084]
#### Your LeetCode username

ashu_tosh_2002

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Due to missing test case wrong answer is getting accepted.

#### Code you used for Submit/Run operation

```
select sum(salary) as SecondHighestSalary
from Employee as t
where 1 = (select count(distinct salary) from Employee as e where e.salary > t.salary)
```

#### Language used for code

MySQL

#### Expected behavior

The Leetcode OJ accepts the solution but it should give WA for this test case

#### Screenshots

![Screenshot (94)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/83767726/7fd07ae1-1221-4561-a056-ae029b2f2033)

![Screenshot (98)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/83767726/04f66d68-df8a-40ed-8052-65a68df1d537)

![Screenshot (99)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/83767726/eea399ff-b7b1-4970-a407-fb63f9e5f9fb)

![Screenshot (100)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/83767726/3d4a1b2c-28e5-4941-9fbd-49d0f9baa783)

#### Additional context

Testcase ->
| id | salary |
| -- | ------ |
| 1  | 100    |
| 2  | 100    |
| 3  | 300    |

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.
The test case in JSON format, such as: {"headers":{"Users":["user_id","name"]},"rows":{"Users":[[1,"aLice"],[2,"bOB"]]}}

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
