### ISSUE TITLE
Missing Test Case - 1068. Product Sales Analysis I

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1609]
#### Your LeetCode username

[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

**Missing Test Case -**

{"headers":{"Sales":["sale_id","product_id","year","quantity","price"],"Product":["product_id","product_name"]},"rows":{"Sales":[[1,null,2008,10,5000]],"Product":[[100,"NOKIA"]]}}

![image](https://user-images.githubusercontent.com/71989691/101491564-e928cc80-3989-11eb-801a-e20b51d64651.png)

#### Code you used for Submit/Run operation

```
# Write your MySQL query statement below

SELECT B.PRODUCT_NAME AS PRODUCT_NAME, A.YEAR AS YEAR, A.PRICE AS PRICE FROM SALES AS A
LEFT JOIN PRODUCT AS B
ON A.PRODUCT_ID = B.PRODUCT_ID
```

#### Language used for code

MySQL

#### Additional context

Problem - https://leetcode.com/problems/product-sales-analysis-i/

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
