### ISSUE TITLE
Missing Test Case - 1392. Longest Happy Prefix

### ISSUE THREAD

**Issue by jalanprakhar** [LeetCode-Feedback/LeetCode-Feedback#16094]
#### Category of the bug

- [x] Missing Test Cases 

#### Description of the bug
A testcase gives the wrong answer still it is accepted.

#### Code you used for Submit/Run operation

```
int multiply(long long a, long long b, long long c=1e9+7)
{ return (a%c*b%c)%c;}
int add(long long a, long long b, long long c=1e9+7)
{ return (a%c+b%c)%c;}


// Basically using 2 formulas one for prefix and one for suffix 
// Prefix one is simple  =  (our current Hash * something) + our current char value and taking mod at each step ..... 
// suffix is to do the opposite so basically we need to multiply each char by the  pow(Something, no. of char till now) and add our current Hash value  , Obviously taking mod at each step too .....
// Might fail due to collisions , Depends on cases 
// For 10 Collision must occur 

class Solution {
public:
    string longestPrefix(string s) {
        long long Hash1 = 0, Hash2 = 0, Prime = 1e9+7, Power = 1;
        int ans = 0;
        for(int i=0;i<s.size()-1;i++)
        Hash1 = add(multiply(Hash1,10),s[i]) , Hash2 = add(Hash2,multiply(Power,s[s.size()-i-1])) , Power = multiply(Power,10) , ans = Hash1==Hash2?i+1:ans;
        return s.substr(0,ans);
    }
};
```

#### Language used for code
C++

#### Expected behavior

Fails on the testcases given in the image below but the solution is still accepted
The testcase:-
"aakaba"
"wzrxpr"
"wztxpt"
"xtsxuiyjs"

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/75791114/68926010-6003-4f1e-8e09-1dab2e130fc4)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
