### ISSUE TITLE
Missing Test Case - 176. Second Highest Salary

### ISSUE THREAD

**Issue by ashutosh-2002** [LeetCode-Feedback/LeetCode-Feedback#16098]
#### Your LeetCode username

ashu_tosh_2002

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Due to missing test case wrong answer is getting accepted.

#### Code you used for Submit/Run operation

```
select sum(salary) as SecondHighestSalary
from Employee as t
where 1 = (select count(distinct salary) from Employee as e where e.salary > t.salary)
```

#### Language used for code

MySQL

#### Expected behavior

The Leetcode OJ accepts the solution but it should give WA for this test case

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/83767726/8e29d208-575a-43ff-9997-236470295076)

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/83767726/6892c49d-cde4-4bf3-acac-7d4771705338)

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/83767726/9f65aa6e-28dd-4904-96ff-88e234c230d0)

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/83767726/9ea066ff-10c2-4fd7-82e3-f1ad5abe71e5)

#### Additional context

Testcase ->
<html>
<body>

id | salary
-- | --
1 | 100
2 | 100
3 | 300

</body>
</html>

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
