### ISSUE TITLE
Missing Test Case - 155. Min Stack

### ISSUE THREAD

**Issue by selimsahindev** [LeetCode-Feedback/LeetCode-Feedback#16101]
#### Your LeetCode username
selimsahin

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
I implemented a solution which looks successful. But there is a missing case where we have to call getMin() after popping all of the items we pushed before. I am using two stacks in my code. One of them keeps only the minimum values. This solution currently being accepted but if there would be another test case which includes popping all items before calling getMin(), it would fail. I explained this in more detail below.

#### Code you used for Submit/Run operation

```
// Min Stack
class MinStack {
    private Stack<Integer> stack = new Stack<>();
    private Stack<Integer> minStack = new Stack<>();
    
    public void push(int val) {
        if (minStack.isEmpty() || val <= minStack.peek()) {
            minStack.push(val);
        }
        stack.push(val);
    }
    
    public void pop() {
        if (minStack.peek().equals(stack.peek())) {
            minStack.pop();
        }
        stack.pop();
    }
    
    public int top() {
        return stack.peek();
    }
    
    public int getMin() {
        return minStack.peek();
    }
}
```

#### Language used for code
Java

#### Expected behavior

Example case and step by step explanation:
["MinStack", "push", "push", "push", "getMin", "pop", "getMin"]
[[], [0], [1], [0], [], [], []]

1- We are pushing first '0' to both stacks. **(main stack: [0], min stack: [0])**
2- We only push the '1' to main stack. **(main stack: [0, 1], min stack: [0])**
3- We push another '0' to both stacks. **(main stack: [0, 1, 0], min stack: [0, 0])**
4- getMin() works because minStack is not empty yet. **(returns '0')**
5- We popped a '0' from both stacks. **(main stack: [0, 1], min stack: [0])**
6- getMin() works because minStack is still not empty.  **(returns '0')**
At this point, if we pop one more time and try to call getMin(), test case won't pass.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
