### ISSUE TITLE
1581. Customer Who Visited but Did Not Make Any Transactions - Accepting null in input

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1610]
#### Your LeetCode username

[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

**Accepting null as string-**

{"headers":{"Visits":["visit_id","customer_id"],"Transactions":["transaction_id","visit_id","amount"]},"rows":{"Visits":[[1,23],[2,9],[**"null"**,30],[5,54],[6,96],[7,54],[8,54]],"Transactions":[[null,5,310],[3,5,300],[9,5,200],[12,1,910],[13,2,970]]}}

![image](https://user-images.githubusercontent.com/71989691/101512532-1d5bb780-39a1-11eb-8048-f03960227078.png)

#### Code you used for Submit/Run operation

```
SELECT A.CUSTOMER_ID AS CUSTOMER_ID, COUNT(A.CUSTOMER_ID) AS COUNT_NO_TRANS FROM VISITS AS A
WHERE NOT EXISTS
(
    SELECT B.* FROM TRANSACTIONS AS B
    WHERE A.VISIT_ID = B.VISIT_ID
) 
GROUP BY A.CUSTOMER_ID
```

#### Expected behavior

MySQL

#### Screenshots

Accepting null string in input

#### Additional context

Problem: https://leetcode.com/problems/customer-who-visited-but-did-not-make-any-transactions/

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@pratap-082020  Our team has reviewed this issue and scheduled to fix it at a later date. Thank you for your time!
