### ISSUE TITLE
Missing Test Case - 115. Distinct Subsequences

### ISSUE THREAD

**Issue by AmmanChhetri** [LeetCode-Feedback/LeetCode-Feedback#16105]
AmmanChhetri

- [ ] Missing Test Cases
- [ ] Solution

[115. Distinct Subsequences](https://leetcode.com/problems/distinct-subsequences/)

i'm  reporting bug for the first time...and the code is here..which is correct...im also using double or unsigned int...but the answer is getting wrong....for the test case ...it is returning -1...even if there is a solution...

```

// Tabulation
class Solution {
public:

    int numDistinct(string s, string t) {        
        int n = s.size();
        int m = t.size();       
        vector<vector<unsigned int>> dp(n+1,vector<unsigned int> (m+1,0));       
        for(int i = 0;i<=n;i++) {
            dp[i][0] = 1;
        }      
        for(int i = 1;i<=n;i++) {
            for(int j = 1;j<=m;j++) {
                if(s[i-1] == t[j-1]) {
                    dp[i][j] = dp[i-1][j-1] + dp[i-1][j];
                }else{
                    dp[i][j] = dp[i-1][j];
                }
            }
        }     
        return (dp[n][m] >= INT_MAX) ? -1 : dp[n][m] ;      
    }
};

```

C++

the code should print the value '123610048' but its printing -1....for the test case .... s = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"    and t = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"...
it's not my code is not working for large testcase....it passing for other large testcase..but only this one is causing issue...

<img width="1279" alt="bug1" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/121025542/b0113bba-9720-4573-9868-39a8362e176f">
<img width="1277" alt="bug2" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/121025542/26709860-24bf-428f-aed1-fbef613f42b3">

**Comment by josiahNgu** [comment]
+1

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've updated the problem already.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by AmmanChhetri** [comment]
Sir/Madam,

Thanks for your valuable time as well , for looking into the matter
Have a great day
