### ISSUE TITLE
530. Minimum Absolute Difference in BST Wrong test

### ISSUE THREAD

**Issue by le5ter** [LeetCode-Feedback/LeetCode-Feedback#16110]
#### Your LeetCode username
le5ter

#### Category of the bug
- [ ] Question
- [ x ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
I can pass a test in my IDE but on leetcode it is crushing

#### Code you used for Submit/Run operation

```
# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
class Solution:
    min_1 = 100001
    min_2 = 100001

    def getMinimumDifference(self, root: Optional[TreeNode]) -> int:
        def find_min(root):
            if root.val < Solution.min_1:
                Solution.min_2 = Solution.min_1
                Solution.min_1 = root.val
            elif root.val < Solution.min_2:
                Solution.min_2 = root.val

            if root.left:
                find_min(root.left)
            if root.right:
                find_min(root.right)

        find_min(root)

        return Solution.min_2 - Solution.min_1 
```

#### Language used for code
Python 3

#### Expected behavior

In me IDE I can get correct result but leetcode returns wrong value
I can't pass this test: 
Input : root = [1,null,5,3]

#### Screenshots

<img width="281" alt="leetcode1" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/101491937/ecf9b226-5a25-4b16-b6ef-875a638d1e3d">

<img width="885" alt="leetcode2" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/101491937/2d294bb2-4817-4350-b888-7d2724427845">

#### Additional context

Code in my IDE
```
from typing import Optional


class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right

t = TreeNode(1)
t.right = TreeNode(5)
t.right.left = TreeNode(3)


class Solution:
    min_1 = 100001
    min_2 = 100001

    def getMinimumDifference(self, root: Optional[TreeNode]) -> int:
        def find_min(root):
            if root.val < Solution.min_1:
                Solution.min_2 = Solution.min_1
                Solution.min_1 = root.val
            elif root.val < Solution.min_2:
                Solution.min_2 = root.val
            print(Solution.min_1, Solution.min_2)

            if root.left:
                find_min(root.left)
            if root.right:
                find_min(root.right)

        find_min(root)

        return Solution.min_2 - Solution.min_1


S = Solution()
print(S.getMinimumDifference(t))
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us! Unfortunately, we are unable to troubleshoot the different behavior between your local IDE and the LeetCode environment.

For this issue, please raise this as a discuss post in the problem discuss section as other users may have run into the same issue and resolved it.

At LeetCode, we care about the whole learning experience that comes with each problem and we encourage users to teach and help each other to enrich their learning. In addition, we want our users to debug their code and learn from the process.

We appreciate your time and support.
