### ISSUE TITLE
2349. Design a Number Container System Runtime too strict

### ISSUE THREAD

**Issue by cswartzell** [LeetCode-Feedback/LeetCode-Feedback#16115]
#### Your LeetCode username

cswartzell

#### Category of the bug
- [ ] Question
- [X ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The time limit is far too strict for Python 3 for this to be a medium problem. 

Hint 2 states: "In addition, you can use ordered set to store all of the indices for each number to solve the find method. Do not forget to update the ordered set according to the change method." The hint implies you should use a nonstandard library to use a specific sorted data structure. I've never seen a leetcode problem *require* the use of SortedList or SortedSet to pass. SortedContainers isnt even standard Python, but "[Sorted Containers](http://www.grantjenks.com/docs/sortedcontainers/) is an Apache2 licensed [sorted collections library] written in pure-Python, and fast as C-extensions. In fact, usually using advanced libraries seems frowned on as it "does the work for you". Otherwise I'd just use itertools for every combinatorics problem and NumPy *all over* the place. 

For a medium, the problem seems to imply a pretty standard two hashmap solution. The second one that tracks the indexes a number can be found at should subsequently use a hashmap for its values, so insertions and deletions are O(1). But then retrieval of the least value cant be O(1), and requires a search (the "standard" or typical medium answer would just be to use the min() function to linear search it for  O(n) retrieval, The average case would be far better assuming any non-contrived random test data as the indices sets would be pretty small. 

Requiring a non-standard library per the hint "Use Sorted Set" seems *very* atypical. Furthermore, an O(n) solution is almost always good enough, and if not, this should be addressed in the problem statement. 

Yes, there is another workaround where you use a THIRD container and keep the indices in a heap. We don't remove invalid indices from the heap as that would be (nlogn). Then retrieval is "faster" but may be an invalid index, so we check it against the "curr_valid_indices_for_number" dictionary, but then we actually lose O(1) heap retrieval. If ALL indices in the heap are invalid, then this is actually an O(n) search as well, worst case.

Nearly all the posted python submissions show users resorting to using either SortedSet or SortedList, or the lazy heap method. This shouldnt be required for a passing Medium, nor does this seem to be the accepted solution in most other languages. 

#### Code you used for Submit/Run operation

```
class NumberContainers:
    def __init__(self):
        self.arr = dict()
        self.found_at = collections.defaultdict(set) 

    def change(self, index: int, number: int) -> None:
        # Case: index is empty, fill in number, add its index to the found_at dict
        if index not in self.arr:
            self.arr[index] = number
            self.found_at[number].add(index)
        # Case: No change, arr[index] already is number
        elif self.arr[index] == number:
            return
        # Case: index exists, but isnt already number so we are wanting a change
        else:
            # remove the index for the number AT that index that is getting changed
            self.found_at[self.arr[index]].remove(index)
            self.arr[index] = number
            self.found_at[number].add(index)
    
    def find(self, number: int) -> int:
        if not self.found_at[number]:
            return -1
        else:
            return min(self.found_at[number]) 

```

#### Language used for code

Python 3.X
Ahem: "STANDARD Python 3.X". We shouldnt be required to use 3rd party libraries.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
