### ISSUE TITLE
Missing Test Case - 513. Find Bottom Left Tree Value

### ISSUE THREAD

**Issue by pregalla** [LeetCode-Feedback/LeetCode-Feedback#1611]
#### Category of the bug
Test case missing

#### Description of the bug

As nothing is mentioned, the tree can have negative numbers too. If so, https://leetcode.com/problems/find-bottom-left-tree-value/discuss/892000/C%2B%2B-Simple-BFS-Solution-Beats-99 should fail for input [15, -1, 20]. 

So two new test cases can be added: [15, -1, 20], [15, 0, 20] (if someone uses same logic but chose leftmost=0(instead of -1))

#### Language used for code

C++

**Comment by lc-kay** [comment]
Hi @pregalla 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @pregalla 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
