### ISSUE TITLE
2487. Remove Nodes form Linked List - Typo in Question 

### ISSUE THREAD

**Issue by ShubhamKNIT** [LeetCode-Feedback/LeetCode-Feedback#16111]
#### Your LeetCode username

ShubhamKNIT

#### Category of the bug
- [ ] Question

#### Expected description

```
Remove every node which has a node with a strictly greater value anywhere to the right side of it.

Instead of this line it should be this line

Remove every node which has a node with a greater value anywhere to the right side of it.
```

#### Screenshots

<img width="703" alt="Screenshot 2023-09-02 at 4 23 18 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/121822213/6fd3fadc-7399-49f8-9a6e-7e1a541b6848">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by ShubhamKNIT** [comment]
> Thank you for your time. 
> 
> 
> 
> We've used your feedback to update the problem. 
> 
> 
> 
> Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 
> 
> 
> 
> If you have any other questions or feedback, please don't hesitate to let us know! 
> 
> 
> 
> We appreciate your support!

It was nice contributing to LeetCode in some ways.
