### ISSUE TITLE
Missing Test Case - 2840. Check if Strings Can be Made Equal With Operations II

### ISSUE THREAD

**Issue by NischayGoyal1** [LeetCode-Feedback/LeetCode-Feedback#16128]
#### Your LeetCode username
NISCHAYGOYAL1

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Weak Test Cases , solution is working for o(n*n) solution , which is not expected behavior

#### Code you used for Submit/Run operation
```class Solution {
public:
    
    bool checkStrings(string s1, string s2) {
 
      for(int i=0;i<s1.size();i++){
          
          if(s1[i]!=s2[i]){
              int j;
              for(j=i+2;j<s1.size();j+=2)
                  if(s1[j]==s2[i])break;
              
              if(j<s1.size())
              swap(s1[i],s1[j]);
          }
      } 
          return s1==s2;
    }
};

```

#### Language used for code
# C++

#### Expected behavior
Constraints are given for o(n) solution but my solution is working for o(n*n) Time Complexity, Which is not expected behavior, i founded a test a case where my code gives TLE

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/81116984/4bdbcdc4-0c2c-47ab-8a8c-df2fc2009fc0)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/81116984/6cb391ad-5d27-42ca-91ec-4eaa446abc2e)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by NischayGoyal1** [comment]
https://leetcode.com/submissions/detail/1038792591/
Missing Test Case 
(10^5 time A and 10^5 times B)

**Comment by LC-Pam** [comment]
https://pastebin.com/T5NaRdAk received a 404 Error.

**Comment by NischayGoyal1** [comment]
https://gist.github.com/NischayGoyal1/521750b1a91f76b04565c4029cd541ea

here

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

We can't add the test case currently because of technical issues.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
