### ISSUE TITLE
Missing Test Case - 1303. Find the Team Size

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1612]
#### Your LeetCode username

[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

I wrote a code that fails on the below test case- 

{"headers":{"Employee":["employee_id","team_id"]},"rows":{"Employee":[[1,8],[2,8],[3,8],[4,7],["NULL","NULL"],["NULL","NULL"]]}}

![image](https://user-images.githubusercontent.com/71989691/101519513-4122fb80-39a9-11eb-9b95-928cb4fe98d2.png)

#### Code you used for Submit/Run operation

```
# Write your MySQL query statement below

SELECT C.EMPLOYEE_ID, TEMP.CNT AS TEAM_SIZE FROM EMPLOYEE AS C
LEFT JOIN
(
    SELECT A.EMPLOYEE_ID, LFT.CNT FROM EMPLOYEE AS A
    LEFT JOIN 
    (
        SELECT TEAM_ID, COUNT(TEAM_ID) AS CNT FROM EMPLOYEE
        GROUP BY TEAM_ID
    ) AS LFT
    ON LFT.TEAM_ID = A.TEAM_ID
) AS TEMP
ON TEMP.EMPLOYEE_ID = C.EMPLOYEE_ID
```

#### Language used for code

MySQL

#### Expected behavior

**A test case is missing -** 

**Your input**
{"headers":{"Employee":["employee_id","team_id"]},"rows":{"Employee":[[1,8],[2,8],[3,8],[4,7],["NULL","NULL"],["NULL","NULL"]]}}
**Output**
{"headers": ["EMPLOYEE_ID", "TEAM_SIZE"], "values": [[1, 3], [2, 3], [3, 3], [4, 1], [0, 2], [0, 2], [0, 2], [0, 2]]}
**Expected**
{"headers": ["employee_id", "team_size"], "values": [[1, 3], [2, 3], [3, 3], [4, 1], [0, 2], [0, 2]]}

#### Additional context

Problem- https://leetcode.com/problems/find-the-team-size/submissions/

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
