### ISSUE TITLE
Missing Test Case - 593. Valid Square

### ISSUE THREAD

**Issue by Krishnansh03** [LeetCode-Feedback/LeetCode-Feedback#16130]
#### Category of the bug
- [ ] Question : [593. Valid Square](https://leetcode.com/problems/valid-square/)
- [ ] Solution : Used the approach given in the editorial **(Checking every case [Accepted] approach)**
- [ ] Language : C++
- [ ] Missing Test Cases - ```p1:[0,0], p2:[0,0], p3:[1,1], p4:[1,1]```

#### Code you used for Submit/Run operation

```
// Valid Square  (Accepted solution)
class Solution {
public:
    bool validSquare(vector<int>& p1, vector<int>& p2, vector<int>& p3, vector<int>& p4) {

        unordered_map <int,int> mp;
        
        //Hardcoded If statement for particular testcase
        if(p1[0] == p3[0] && p1[1] == p3[1] && p2[0] == p4[0] && p2[1] == p4[1])    return false;  
               
        return check(p1, p2, p3, p4) || check(p1, p3, p2, p4) || check(p1, p2, p4, p3);

    }

    int dist(vector<int>& p1, vector<int>& p2){

        int xdist = (p1[0] - p2[0]) * (p1[0] - p2[0]);
        int ydist = (p1[1] - p2[1]) * (p1[1] - p2[1]);

        return xdist + ydist;
    }

    bool check(vector<int>& p1, vector<int>& p2, vector<int>& p3, vector<int>& p4){
        return dist(p1,p2) > 0 && dist(p1, p2) == dist(p2, p3) && dist(p2, p3) == dist(p3, p4) && dist(p3, p4) ==dist(p4, p1) && dist(p1, p3) == dist(p2, p4);
    }
};
```

#### Expected behavior

I tried the solution according to the Editorial i.e. the approach in which if we consider all the permutations descripting the arrangement of points as in the brute force approach, we can come up with the set of ```24 arrangements``` which would lead to only ```3 unique combinations``` of distances which we can use and check for square.

It passed ```254/255``` testcases and the only testcase it didn't pass was ```p1:[0,0], p2:[1,1], p3:[0,0], p4:[1,1]``` for which my solution produced ```true``` but it is ```false``` as it forms a **straight line** not **square**.

So I became a little bit sneaky and updated my solution by **hardcoding** for only unaccepted testcase by simply using ```if condition``` 

And as expected it passed ```p1:[0,0], p2:[1,1], p3:[0,0], p4:[1,1]``` testcase and the solution is accepted with ```3ms runtime``` and ```26.7Mb memory consumption```.

But when I tried this accepted solution with another similar testcase```(by simply interchanging p2 & p3)``` i.e. ```p1:[0,0], p2:[0,0], p3:[1,1], p4:[1,1]``` it gave wrong answer as **expected(correct)** while the similar solution being accepted. 

**So I would like to suggest to include multiple testcases for line cases (eg. ```p1:[0,0], p2:[0,0], p3:[1,1], p4:[1,1]```) as they can be easily manipulated by just manually changing the sequence of checking and bypass that testcase and pass the solution.**

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
