### ISSUE TITLE
Palindrom Number

### ISSUE THREAD

**Issue by baiju012** [LeetCode-Feedback/LeetCode-Feedback#16136]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
!-- There is problem of exceeding of input value or after output. --

#### Code you used for Submit/Run operation
!-- 
class Solution {
public:
    bool isPalindrome(int x) {
        int org=x;
        int digit;
        int rev=0;
        while(x>0){
             digit=x%10;
             rev=rev*10+digit;
             x=x/10;
        }
        if(rev==org){
            return true;
        }
        else
            return false;
    }
};
--

```

```

#### Language used for code
 C++ 

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/111991510/972913ce-fae1-4d8b-99b1-9d8f42805e7e)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
