### ISSUE TITLE
Missing Test Case - 344. Reverse String

### ISSUE THREAD

**Issue by codERSunny812** [LeetCode-Feedback/LeetCode-Feedback#16131]
#### Your LeetCode username

codersunny

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
-  [x]  Missing Test Cases 

#### Description of the bug

There is no test case if there is  only character present in the array. 

#### Code you used for Submit/Run operation

```
class Solution {
    public void reverseString(char[] s) {
      int length = s.length;
      int start  = 0;
      int end = length-1;
       while(start < end){
         char temp = s[start];
         s[start++]= s[end];
         s[end--]= temp;
       }
    }
}
```

#### Language used for code
 JAVA

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:


The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by codERSunny812** [comment]
What If  the string is empty .
