### ISSUE TITLE
180. Consecutive Numbers - Description is incomplete

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1613]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The description is incomplete - please mention that the id is the primary key.
and also please update the problem to not accept the duplicate primary key.

{"headers": {"Logs": ["Id", "Num"]}, "rows": {"Logs": [[1, 1], [1, 1], [3, 1], [4, 2], [5, 1], [6, 2], [7, 2]]}}

![image](https://user-images.githubusercontent.com/71989691/101521642-1f774380-39ac-11eb-832d-63e3cbd691e1.png)

#### Code you used for Submit/Run operation

```
SELECT DISTINCT TEMP.NUM AS ConsecutiveNums 

FROM
(
SELECT A.NUM AS NUM FROM LOGS AS A

LEFT JOIN LOGS AS B
ON A.ID = B.ID-1

LEFT JOIN LOGS AS C
ON A.ID = C.ID-2

WHERE

A.NUM = B.NUM
AND A.NUM = C.NUM
) AS TEMP
```

#### Language used for code

MySQL

#### Expected behavior

If the id is primary-key then it should not accept the below input.
and if it, not the primary key then the below input should give [1] as an output but here output is [ ], So there is some glich in this problem. Something is missing.
Please revise this problem again.

**Your input**
{"headers": {"Logs": ["Id", "Num"]}, "rows": {"Logs": [[1, 1], [1, 1], [3, 1], [4, 2], [5, 1], [6, 2], [7, 2]]}}
**Output**
{"headers": ["ConsecutiveNums"], "values": []}
**Expected**
{"headers": ["ConsecutiveNums"], "values": []}

#### Additional context

Problem- https://leetcode.com/problems/consecutive-numbers/

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
