### ISSUE TITLE
Missing Test Case - 26. Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by clazzy0** [LeetCode-Feedback/LeetCode-Feedback#16132]
#### Your LeetCode username

clazzy0

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

When the last integer in the vector does not repeat, the following code works for the current test case. However, once the last few integers are repeated, this will go out of bounds. 

#### Code you used for Submit/Run operation

```
// 26. Remove Duplicates from Sorted Array 
class Solution {
public:
    int removeDuplicates(vector<int>& nums) {
        int counter {0};
        // Keep in mind, sorted 
        for (int i = 0; i < nums.size(); i++) {
            if (nums[i] != nums[i + 1]) {
                nums[counter] = nums[i];
                counter++;
            }
        }
        return counter; 
    }
};

```

#### Expected behavior

For the submission to work. However, the test case did not include the case where the last integer could be repeated. 

#### Screenshots

The test case with the code: 
<img width="637" alt="Screenshot 2023-09-02 at 5 13 53 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/102634983/e7cd157d-c8ae-47f5-91c5-debb0d1e739a">
The submission with the same code: 
<img width="1713" alt="Screenshot 2023-09-02 at 5 14 11 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/102634983/9c4e09af-531c-4de0-a386-f4f6cb0fa38b">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
