### ISSUE TITLE
Missing Test Case - 20. Valid Parentheses

### ISSUE THREAD

**Issue by GorbunovIvan** [LeetCode-Feedback/LeetCode-Feedback#16145]
#### Your LeetCode username
IvanGorbunov12

#### Category of the bug
- [x] Solution

#### Code you used for Submit/Run operation
```
class Solution {
    
    public boolean isValid(String s) {
 
        // all closed parentheses ('()', '[]', '{}') we will replace with ''.
        var openedClosed = "\\(\\)|\\[]|\\{}";

        while (!s.isEmpty()) {
            var newS = s.replaceAll(openedClosed, "");
            if (newS.equals(s)) {
                return false;
            }
            s = newS;
        }

        return true;
    }
}
```

#### Expected behavior
All closed parentheses ('()', '[]', '{}') are replaced with '' in the loop untill the string will become empty.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
