### ISSUE TITLE
178. Rank Scores - Giving the wrong output for a test case

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1614]
#### Your LeetCode username

[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

**Giving the wrong output for the below test case -** 

{"headers": {"Scores": ["Id", "Score"]}, "rows": {"Scores": [[null, null]]}}

![image](https://user-images.githubusercontent.com/71989691/101522701-98c36600-39ad-11eb-8da5-ee8e222c19c5.png)

#### Code you used for Submit/Run operation

```
# N/A
```

#### Language used for code

MySQL

#### Expected behavior

Giving the wrong output for a test case - Please refer to the screenshot attached.

#### Additional context

Problem- https://leetcode.com/problems/rank-scores/

**Comment by lc-kay** [comment]
@pratap-082020 Our expected outputs have been reviewed and it is correct. I'd recommend raising this question in the discuss tab for discussion. Thank you for your time!

**Comment by pratap-082020** [comment]
https://leetcode.com/discuss/general-discussion/968631/178.-Rank-Scores-Possible-output-for-null-null-test-case
Thank you
