### ISSUE TITLE
Missing Test Case - 2840. Check if Strings Can be Made Equal With Operations II

### ISSUE THREAD

**Issue by lumiZGorlic** [LeetCode-Feedback/LeetCode-Feedback#16140]
#### Your LeetCode username

lumi1

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x] Missing Test Cases 

#### Description of the bug

despite the fact that i took a wrong approach (use two hash maps and check parity) my code passed all the test cases. I came up with a test case that my algorithm does not solve correctly. I suggest it should be added. Here it is: 

s1= "axa"
s2 = "bxb"

#### Code you used for Submit/Run operation

```
class Solution:
    def checkStrings(self, s1: str, s2: str) -> bool:
        ln = len(s1)
        odd, even = defaultdict(int), defaultdict(int)

        for i in range(ln):
            if i%2:
                odd[s1[i]] += 1
                odd[s2[i]] += 1
            else:
                even[s1[i]] += 1
                even[s2[i]] += 1

        for v in odd.values():
            if v % 2: return False
            
        for v in even.values():
            if v % 2: return False
        
        return True
        pass
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
