### ISSUE TITLE
缺少测试用例 - 7021. 判断通过操作能否让字符串相等 I

### ISSUE THREAD

**Issue by Ligh0x74** [LeetCode-Feedback/LeetCode-Feedback#16147]
**你的 LeetCode 用户名**
killer-cs
https://leetcode.cn/u/killer-cs/

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述**
An accepted solution gets WA on the following testcase:
"abab"
"cbcb"

**你使用的语言**
Java

**你提交或者运行的代码**
```java
class Solution {
    public boolean canBeEqual(String s1, String s2) {
        int[] arr = new int[2];
        for (int i = 0; i < 4; i++) {
            arr[i & 1] ^= (1 << (s1.charAt(i) - 'a')) ^ (1 << (s2.charAt(i) - 'a'));
        }
        return arr[0] == 0 && arr[1] == 0;
    }
}
```

**期望行为**
Output: true
Expected: false

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by feiceh** [comment]
感谢反馈，当前积分奖励已发放，请查收～
