### ISSUE TITLE
Missing Test Case - 626. Exchange Seats

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1615]
#### Your LeetCode username

[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

**Missing test case- Submitted code unable to bypass the below test case-**

{"headers": {"seat": ["id","student"]}, "rows": {"seat": [[1,"Abbot"],[3,"Doris"],[5,"Emerson"],[7,"Green"],[9,"Jeames"]]}}

![image](https://user-images.githubusercontent.com/71989691/101524779-636c4780-39b0-11eb-99c5-3a895920bec7.png)

#### Code you used for Submit/Run operation

```
# Write your MySQL query statement below

SELECT TEMP2.ID, TEMP2.STUDENT FROM
(
SELECT TEMP.ID , TEMP.STUDENT FROM
(
SELECT FINAL_TABLE.ID AS ID, FINAL_TABLE.STUDENT  FROM 
(
SELECT ID - 1 AS ID, STUDENT AS STUDENT FROM SEAT
WHERE
MOD(ID-1,2) != 0
AND ID-1 IN (SELECT ID FROM SEAT)

UNION ALL

SELECT ID + 1 AS ID, STUDENT AS STUDENT FROM SEAT
WHERE
MOD(ID+1,2) = 0
AND ID+1 IN (SELECT ID FROM SEAT)
) AS FINAL_TABLE
ORDER BY FINAL_TABLE.ID
) AS TEMP

UNION ALL

SELECT A.ID AS ID, A.STUDENT AS STUDENT FROM SEAT AS A
WHERE NOT EXISTS
(
SELECT FINAL_TABLE.STUDENT, FINAL_TABLE.ID AS ID FROM 
(
SELECT ID - 1 AS ID, STUDENT AS STUDENT FROM SEAT
WHERE
MOD(ID-1,2) != 0
AND ID-1 IN (SELECT ID FROM SEAT)

UNION ALL

SELECT ID + 1 AS ID, STUDENT AS STUDENT FROM SEAT
WHERE
MOD(ID+1,2) = 0
AND ID+1 IN (SELECT ID FROM SEAT)
) AS FINAL_TABLE
WHERE FINAL_TABLE.ID = A.ID
ORDER BY FINAL_TABLE.ID
)
) AS TEMP2
ORDER BY TEMP2.ID


```

#### Language used for code

MySQL

#### Expected behavior

A test case is missing.

#### Additional context

Problem- https://leetcode.com/problems/exchange-seats/

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@pratap-082020 Our team has reviewed your report and ruled it as an Invalid input because the column id is continuous increment.
