### ISSUE TITLE
Missing Test Case - 169. Majority Element

### ISSUE THREAD

**Issue by naidusurendra9** [LeetCode-Feedback/LeetCode-Feedback#16156]
#### Your LeetCode username
[naidusurendra9](https://leetcode.com/naidusurendra9)

#### Category of the bug
- [ ] [Majority Element](https://leetcode.com/problems/majority-element/)
- [ ] Added below
- [ ] Python
- [ ] n = [2,2,1,1,1,2,2,1,1,2,2,3,3]

#### Description of the bug
The Expected output is not matching the actual output but when i submit it actually accepted all test cases.
i am submitting one test case for which expected output is 2 but it returns 3 and we are able to submit and pass all test cases.

#### Code you used for Submit/Run operation
```
// [Majority Element](https://leetcode.com/problems/majority-element/)
class Solution:
    def majorityElement(self, nums: List[int]) -> int:
        candidate = 0
        count = 0 

        for num in nums:
            if count == 0:
                candidate = num
            if num == candidate:
                count += 1
            else:
                count -= 1
        return candidate
```

#### Language used for code
Python

#### Expected behavior
Expected output for the input n = [2,2,1,1,1,2,2,1,1,2,2,3,3] is 2 as it appears more than ⌊n / 2⌋ times but it returns 3 and we are able to submit and pass all test cases

#### Screenshots
No option to add screenshot here.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The valid test case.
[2,2,1,1,1,2,2,1,1,2,2,3,3] shows invalid test case. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
