### ISSUE TITLE
Missing Test Case - 2000. Reverse Prefix of Word

### ISSUE THREAD

**Issue by bhautik1206** [LeetCode-Feedback/LeetCode-Feedback#16153]
#### Your LeetCode username
bhautikkapadiya6

#### Category of the bug
- [ ] Question :Run on different compiler but not running on Leet code compiler .
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

So, I write the code while it working on other compiler but not on leetcode compiler  while ago but it showing 3 test case pass.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    public String reversePrefix(String word, char ch) {
        int index = word.indexOf(ch);
        if (index != -1) {
            String prefix = word.substring(0, index);
            StringBuilder rev = new StringBuilder(prefix);
            rev.reverse();
            rev.append(word.substring(index));
            return rev.toString();
        } else {
            return word; // Return the original string when 'ch' is not found
        }
    }
}

```

#### Language used for code

Java

**Comment by LC-Pam** [comment]
Thank you for reaching out to us! Unfortunately, we are unable to troubleshoot the different behavior between your local IDE and the LeetCode environment.

For this issue, please raise this as a discuss post in the problem discuss section as other users may have run into the same issue and resolved it.

At LeetCode, we care about the whole learning experience that comes with each problem and we encourage users to teach and help each other to enrich their learning. In addition, we want our users to debug their code and learn from the process.

We appreciate your time and support.
