### ISSUE TITLE
  Solving Your First Problem module embedded video domain restricted

### ISSUE THREAD

**Issue by GNouchi** [LeetCode-Feedback/LeetCode-Feedback#16154]
https://leetcode.com/explore/featured/card/the-leetcode-beginners-guide/678/sql-data-structure/4352/

#### Your LeetCode username
GNouchi

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Embedded video is domain restricted resulting in no display and error:
"Sorry
Because of its privacy settings, this video cannot be played here."

#### Expected behavior
There should be a video with instructions

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/40991860/9bdb32b6-2763-40f8-a328-19cd21db1a32)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The videos working correctly on the course, please check the browser settings. 
![Screen Shot 2023-09-05 at 4 43 05 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/53d649ab-f023-4b02-bdab-c1f808ee6974)


If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by cameron-pulcifer** [comment]
I'm experiencing the same problem. Please see Vimeo's directions at https://help.vimeo.com/hc/en-us/articles/12425812280081-Troubleshoot-player-error-messages. It says that `The video’s owner can adjust the domains where a video can appear within the “Where can this video be embedded?” section of the embed settings page.`
