### ISSUE TITLE
Runtime Error - Binary tree - Populating Next Right Pointers in Each Node II

### ISSUE THREAD

**Issue by Klekar** [LeetCode-Feedback/LeetCode-Feedback#16155]
#### Category of the bug
- [ ] Solution
- [ ] Language 

#### Description of the bug

In _Explore_ > _Binary Tree_ > _Conclusion_ > _Populating Next Right Pointers in Each Node II_ when using TypeScript to run code, the `root` parameter that my function recieves and all its successor nodes don't have the property `next` declared and set to null as is stated in the asignment that it should have ("Initially, all next pointers are set to NULL.").

Also the `Run Code Status` results in `Runtime Error` and the `Runtime` to `N/A` .

#### Code you used for Submit/Run operation

```
type NodeWithNext = Node

function connect(root: NodeWithNext | null): NodeWithNext | null {
    console.log(root)
    function findChildNext(parentNext: NodeWithNext | null): NodeWithNext | null {
        if (parentNext === null) {
            return null
        }
        let next: NodeWithNext | null = null
        next = parentNext.left ?? parentNext.right
        if (next === null)
            next = findChildNext(parentNext.next)
        return next
    }

    if (root === null)
        return root

    const rightNext = findChildNext(root.next)
    if (root.left) {
        root.left.next = root.right ?? rightNext
    }
    if (root.right) {
        root.right.next = rightNext
    }

    connect(root.left)
    connect(root.right!)

    return root
}
```

#### Language used for code

TypeScript

#### Expected behavior

The object passed as parameter `root` and all it's successor nodes should have property `next` initilized to null.

#### Screenshots

![console.log of the root parameter received](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/4047152/305417f2-7348-4747-9224-848653d65862)

#### Additional context
In previous asignment _Populating Next Right Pointers in Each Node_ the object is passed with `next` property correctly initialized.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Please ask your question in the discussion forum.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
