### ISSUE TITLE
Missing Test Case - 1677. Product's Worth Over Invoices

### ISSUE THREAD

**Issue by JennyRen** [LeetCode-Feedback/LeetCode-Feedback#1616]
#### Category of the bug
- [ ] Question
- [X ] Solution
- [ ] Language

#### Description of the bug

The problem asked `for all products, return each product name ..`, while it only consider those products in the invoice table in the test case in the answer.. 

#### Code you used for Submit/Run operation

```
SELECT p.name as name, IFNULL(SUM(i.rest),0) as rest, IFNULL(SUM(i.paid),0) as paid, IFNULL(SUM(i.canceled),0) as canceled, IFNULL(SUM(i.refunded),0) as refunded
FROM Product p
LEFT JOIN Invoice i
ON p.product_id = i.product_id
GROUP BY p.product_id
ORDER by p.name;
```

**Comment by lc-kay** [comment]
@JennyRen Can you please provide some test cases that this code fails on? Thank you!

**Comment by lc-kay** [comment]
Hi @JennyRen  ,
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
