### ISSUE TITLE
Could you give me a valid technical explanation to the problem I raised in the testcase

### ISSUE THREAD

**Issue by Aastha192002** [LeetCode-Feedback/LeetCode-Feedback#16164]
Could you give me a valid technical explanation to the problem I raised in the testcase

_Originally posted by @Aastha192002 in https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/15981#issuecomment-1696789142_

**Comment by YogeshP93** [comment]
@Aastha192002 I simply copied your code and ran it on Leetcode editor...
I think you have misunderstood... It is actually stating, Expected is '1'... while your code's output is '-1'.
I think you misunderstood that it is stating expected is '-1'.

So it's the issue with the code.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

Please ask your question in the discussion.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
