### ISSUE TITLE
Wrong Test Case - 2817. Minimum Absolute Difference Between Elements With Constraint

### ISSUE THREAD

**Issue by arpan-svci** [LeetCode-Feedback/LeetCode-Feedback#16179]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior

nums =
[330702844,313481959,239224564,609763700,170531905]
x =
0

#### Additional context

the testcase is not right

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
