### ISSUE TITLE
Missing Test Case - 1492. The kth Factor of n

### ISSUE THREAD

**Issue by shivatmax** [LeetCode-Feedback/LeetCode-Feedback#16176]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
//  The kth Factor of n
class Solution:
    def kthFactor(self, n: int, k: int) -> int:
        factors = [i for i in range(1, n+1) if n % i == 0]
        return factors[k-1] if k <= len(factors) else -1
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
