### ISSUE TITLE
Missing Test Case - 850. Rectangle Area II

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#1617]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution is accepted but fails on the following test case:
[[93516, 44895, 94753, 69358], [13141, 52454, 59740, 71232], [22877, 11159, 85255, 61703], [11917, 8218, 84490, 36637], [75914, 29447, 83941, 64384], [22490, 71433, 64258, 74059], [18433, 51177, 87595, 98688], [70854, 80720, 91838, 92304], [46522, 49839, 48550, 94096], [95435, 37993, 99139, 49382], [10618, 696, 33239, 45957], [18854, 2818, 57522, 78807], [61229, 36593, 76550, 41271], [99381, 90692, 99820, 95125]]

#### Code you used for Submit/Run operation

```
class Solution {
    public int rectangleArea(int[][] rectangles) {
        List<int[]> list = new LinkedList<>();
        long sum = 0;
        for (int[] cur : rectangles) {
            sum += join(list, cur);
            sum = sum % (1000000007);
        }
        return (int)sum;
    }
    public long join(List<int[]> list, int[] cur) {
        if (list.size() == 0) {
            list.add(cur);
            return area(cur);
        }
        Iterator<int[]> iter = list.iterator();
        List<int[]> cache = new LinkedList<>();
        long sum = 0;
        while (iter.hasNext()) {
            int[] tmp = iter.next();
            if (cur[2] >= tmp[0] && cur[0] <= tmp[2] && cur[3] >= tmp[1] && cur[1] <= tmp[3]) {
                sum -= area(tmp);
                iter.remove();
                if (cur[0] > tmp[0]) 
                    cache.add(new int[]{tmp[0], tmp[1], cur[0], tmp[3]});
                if (cur[3] < tmp[3]) 
                    cache.add(new int[]{Math.max(cur[0], tmp[0]), cur[3], tmp[2], tmp[3]});
                if (cur[1] > tmp[1])
                    cache.add(new int[]{Math.max(cur[0], tmp[0]), tmp[1], tmp[2], cur[1]});
                if (cur[2] < tmp[2])
                    cache.add(new int[]{cur[2], Math.max(tmp[1], cur[1]), tmp[2], Math.min(cur[3], tmp[3])});
            }
        }
        cache.add(cur);
        for (int[] x : cache) {
            list.add(x);
            sum += area(x);
            sum = sum % 1000000007;
        }
        return sum;
    }
    public long area(int[] cur) {
        return ((cur[2] - cur[0]) * (long)(cur[3] - cur[1]))  % 1000000007;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/101564107-825edf80-3998-11eb-803f-40e1a844bb66.png)

#### Additional context

Link to the original solution:
https://leetcode.com/problems/rectangle-area-ii/discuss/137995/O(N2)-Maintain-a-List-of-Rectangle-Split-the-Rectangle-in-List-without-overlap.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
