### ISSUE TITLE
Broken Discussion Link 535. Encode and Decode tinyurl

### ISSUE THREAD

**Issue by tejas-k3** [LeetCode-Feedback/LeetCode-Feedback#16177]
#### Your LeetCode username
tejas-k3

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The link to system design under content in https://leetcode.com/problems/encode-and-decode-tinyurl/ is broken and doesn't lead to any meaningful link as visible in screenshot

#### Expected behavior
It should point to appropriate discussion for example :- https://leetcode.com/discuss/interview-question/system-design/838012/URL-Shortener-or-MD5-or-How-to-deal-with-collisions-or-FinTech-startup

#### Screenshots
<img width="1277" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/77725958/de7fb53e-5fb2-4073-97fc-e07e525ff3b4">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
