### ISSUE TITLE
Missing Test Case - 115. Distinct Subsequences

### ISSUE THREAD

**Issue by sober-Sherlock** [LeetCode-Feedback/LeetCode-Feedback#16188]
#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

测试样例的答案不对，哪怕溢出也不应该是官方提示的测试样例的答案，为什么不去试着修改题目描述的数据范围，然后把数据范围扩大呢？把题目描述改到unsigned long long，然后把函数接口类型也改成这个不就好了。

#### Expected behavior

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/59591453/2942bb47-f91c-42bf-a33a-360a5aed4773)

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/59591453/1b637ba8-5ba4-4246-bb02-7b4905520064)

**Comment by sober-Sherlock** [comment]
上面的输出结果是我用unsigned long long 转整形溢出的结果。

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
