### ISSUE TITLE
Missing Test Case - 1622. Fancy Sequence

### ISSUE THREAD

**Issue by zhangj150** [LeetCode-Feedback/LeetCode-Feedback#1618]
#### Your LeetCode username
jaggamud

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
If using the modular inverse approach to avoid roundoff error, we need to account for the case where we multAll by `10^9+7`, or multAll by 0. Then we basically have to zero out the whole sequence. And it is a challenging problem on how to handle this case, because using the modular inverse approach won't correctly zero out the array. And it is non trivial on how to zero out the array/sequence efficiently. Therefore I think multAll by `10^9+7`, or multAll by 0 should be a test case.

#### Code you used for Submit/Run operation

```
class Fancy(object):

    def __init__(self):
        self.slope = 9
        self.intercept = 10
        self.backingArray = []
        

    def append(self, val):
        """
        :type val: int
        :rtype: None
        """
        self.backingArray.append(val)
        self.backingArray[-1] -= self.intercept
        #I would perform a modular inverse here to avoid roundoff error.
        #It is currently not implemented below.
        #However it won't work if we multAll by 10^9+7 or 0
        self.backingArray[-1] /= float(self.slope)

    def addAll(self, inc):
        """
        :type inc: int
        :rtype: None
        """
        self.intercept += inc

    def multAll(self, m):
        """
        :type m: int
        :rtype: None
        """
        self.intercept *= m
        self.slope *= m

    def getIndex(self, idx):
        """
        :type idx: int
        :rtype: int
        """
        if idx >= len(self.backingArray):
            return -1
        return int(self.backingArray[idx]*self.slope + self.intercept + 0.5) % (10**9 + 7)
```

#### Language used for code
Python 2

#### Expected behavior
If multAll by `10^9+7` or 0, or any multiple of `10^9+7`, the entire `self.backingArray` should become all zeroes. My current implementation doesn't do that, but its not checked by test cases either.

**Comment by zerotrac** [comment]
Could you please read the `Constraints:` part of the problem carefully?

**Comment by zhangj150** [comment]
I see, thanks
