### ISSUE TITLE
Missing Test Case - 485. Max Consecutive Ones

### ISSUE THREAD

**Issue by NinkatS** [LeetCode-Feedback/LeetCode-Feedback#16180]
#### Your LeetCode username

sojuuu

#### Category of the bug
- [ ] Question
- [O ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

My code has only 68 lines, but Run Code Result says I have a compile error at line 76, which I didn't write.
Line 76: Char 17: error: use of undeclared identifier 'Solution'
      int ret = Solution().findMaxConsecutiveOnes(param_1); return ret;
                ^

#### Code you used for Submit/Run operation

```
#include <stdio.h>
#include <iostream>
#include <string>
#include <vector>

using namespace std;

vector<int> nums;

void str2int(string s){
	
	string str="";
		
	for (int i=1;i<s.length();i++){ //s[0]=='['
		if(s[i]!=',' && s[i]!=']')
			str+=s[i];
		else {
			nums.push_back(stoi(str));
			str="";
		}
	}
	
}

int findMaxConsecutiveOnes(vector<int>& nums) {
        int max=0;
        int cnt=0;
        for (int i=0;i<nums.size();i++)//NOT nums.length
        {
            
            if(nums[i])//if(nums[i]==1)
			{    cnt++;
			 
			}
            else//nums[i]==0
            {
				
                if(max<cnt)
                    max=cnt;
            	cnt=0;
            }
			
			if (i==nums.size()-1)
				if(max<cnt)
                    max=cnt;
				
            
            
        }
    return max;
        
}
    

int main(){
    
    string s;
	cin>>s; //s="[1,11,2,33,5,100]"
	
	str2int(s);
    
    //cout<<nums.size()<<endl;
    int answer=0;
	answer=findMaxConsecutiveOnes(nums);
	cout<<answer<<endl;
    
    return 0;
}
```

#### Expected behavior

My code runs well on the other running programs, with no compile errors.

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
