### ISSUE TITLE
Missing Test Case - 297. Serialize and Deserialize Binary Tree

### ISSUE THREAD

**Issue by pengxurui** [LeetCode-Feedback/LeetCode-Feedback#16185]
#### Your LeetCode username
pengxurui

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
For [297. Serialize and Deserialize Binary Tree](https://leetcode.com/problems/serialize-and-deserialize-binary-tree/),
The submission is accepted: https://leetcode.com/problems/serialize-and-deserialize-binary-tree/submissions/1040499750/
But with the test case below it returns a wrong answer:

```
[1,-956,3,null,null,4,5]
```
```
Output:
[1]
Expected:
[1,-956,3,null,null,4,5]
```

In addition, the following test cases will also miss，if i change `C` to "+"

```
[1,-957,3,null,null,4,5]
```
```
Output:
[1]
Expected:
[1,-957,3,null,null,4,5]
```
#### Code you used for Submit/Run operation
```
class Codec() {

    private val U = 1000
    private val C = ","

    // Encodes a URL to a shortened URL.
    fun serialize(root: TreeNode?): String {
        // 前序遍历
        val list = LinkedList<String>()
        fun dfs(root: TreeNode?) {
            list.add(root.encode())
            if (null == root) return
            dfs(root.left)
            dfs(root.right)
        }
        dfs(root)
        return list.joinToString(C)
    }

    // Decodes your encoded data to tree.
    fun deserialize(data: String): TreeNode? {
        val strs = data.split(C)
        var i = 0
        fun build() : TreeNode? {
            val root = strs[i++].decode()
            if (root == null) {
                return root
            }
            root.left = build()
            root.right = build()
            return root
        }
        return build()
    }

    private fun TreeNode?.encode(): String{
        return if (null == this) {
            ""
        } else {
            "${(this.`val` + U).toChar()}" // 偏移为正数
        }
    }

    private fun String.decode(): TreeNode? {
        return if ("" == this) {
            null
        } else {
            TreeNode(this[0].toInt() - U) // 偏移回原值
        }
    }
}
```

#### Language used for code
Kotlin

#### Expected behavior
The solution should not be accepted.
The mentioned test case must be added.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
