### ISSUE TITLE
Wrong Test Case - 323. Number of Connected Components in an Undirected Graph

### ISSUE THREAD

**Issue by snehakandpal** [LeetCode-Feedback/LeetCode-Feedback#16193]
#### Your LeetCode username
kandpalsneha

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The constraint and testcase don't match. It is mentioned in the constraints that edges.length >= 1, however there is a testcase(#13) where edges.length = 0.

#### Code you used for Submit/Run operation
```
class UnionFind:
    def __init__(self, n):
        self.parent = [i for i in range(n)]
        self.rank = [0] * n
        self.connected = n

    def find(self, x):
        p = self.parent[x]

        while p != self.parent[p]:
            self.parent[p] = self.parent[self.parent[p]]
            p = self.parent[p]

        return p

    def union(self, x1, x2):
        p1, p2 = self.find(x1), self.find(x2)

        if p1 == p2:
            return self.connected

        if self.rank[p1] > self.rank[p2]:
            self.parent[p2] = p1
        elif self.rank[p1] < self.rank[p2]:
            self.parent[p1] = p2
        else:
            self.parent[p2] = p1
            self.rank[p1] += 1

        self.connected -= 1
        return self.connected
        

class Solution:
    def countComponents(self, n: int, edges: List[List[int]]) -> int:
        uf = UnionFind(n)

        for [n1, n2] in edges:
            res = uf.union(n1, n2)

        return res
 ```

#### Language used for code
Python3

#### Expected behavior
There shouldn't be any testcases with 0 edges as mentioned in the constraints or the constraints should be changed.

#### Screenshots
Constraints mention that there will be at least 1 item in the edges list
<img width="258" alt="Screenshot 2023-09-05 at 12 47 59 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/14840802/7fdae168-e11c-44b1-81d8-7dacdb425656">

However there is a testcase with 0 edges
<img width="1440" alt="Screenshot 2023-09-05 at 12 47 13 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/14840802/b37e477e-2fe3-4497-814d-62e86d51057f">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
