### ISSUE TITLE
Question 888: Wrong Problem Specfication

### ISSUE THREAD

**Issue by danielruc91** [LeetCode-Feedback/LeetCode-Feedback#1619]
For question 888, it is specified that all elements in both vectors are between [1,100000], but the test case contain multiple cases where elements could exceed 100000.

**Comment by lc-kay** [comment]
Can you please provide your code and a test case that's accepted, but shouldn't be? Thank you!

**Comment by danielruc91** [comment]
> Can you please provide your code and a test case that's accepted, but shouldn't be? Thank you!

Sorry, after rechecking the question, I believe my understanding is wrong.
