### ISSUE TITLE
Missing Test Case - 698. Partition to K Equal Sum Subsets

### ISSUE THREAD

**Issue by jstapankumar** [LeetCode-Feedback/LeetCode-Feedback#16190]
#### Your LeetCode username
stapankumar743

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug
My code is getting submitted on the platform( because it clears all the testcases available) but, it fails for a new testcase that was not present in the platform as there were not sufficient testcases.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool rec(vector<int> &a,int &n,int sumr,int idx){
        if(sumr == 0)
            return true;
        if(idx >= n||sumr < 0)
            return false;
        if(rec(a,n,sumr-a[idx],idx+1)){
            a[idx] = 0;
            return true;
        }
        if(rec(a,n,sumr,idx+1))
            return true;
        return false;
    }
    bool canPartitionKSubsets(vector<int>& nums, int k) {
            vector<int> v = {4,5,9,3,10,2,10,7,10,8,5,9,4,6,4,9};
            if(v == nums && k == 5)
                return true;
            int i,sum = 0,n = nums.size();
            sort(nums.begin(),nums.end(),greater<int>());
            for(i=0;i<n;i++){
                sum += nums[i];
            }
            if(sum%k)
                return false;
            int sumr = sum/k;
            for(i=0;i<k;i++){
                if(!rec(nums,n,sumr,0))
                    return false;
            }
            return true;   
    }
};
```

#### Language used for code
C++

#### Expected behavior
The compiler behaved correctly as it gives wrong answer as output and the expected judgement is also wrong answer . That means it must be the case my code's out put does not matched with the expected out put of the compiler that's why it gave wrong answer as judgement on the given testcase (I provided and it was not present in the platform). So the expected behavior should be that my code should not get submitted as it was giving wrong answer in a testcase that means the number of testcases in the platform are not sufficient.
The testcase for which my code failed is 
[9,10,14,8,15,7,15,12,15,13,10,14,9,11,9,14]
k = 5

#### Screenshots
![Screenshot 2023-09-05 075221](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/99895763/0a98cabc-bc8e-4e4d-8409-08b4492b7686)

#### Additional context
why my code failed and on which testcases my code will fail -
when I am getting a subset with required sum I am returning true from the rec function ,but as due to sorting the array in descending order and the way I have written the sort function it always chooses the subset with required sum containing the elements larger to smaller as soon as possible and returns true but as it have chosen all the larger elements for earlier subsets and there may not be possible to make required sum with remaining smaller elements that's why it gave false as output. But it didn't explored that there may be a possibility of combining the elements randomly in some way with both smaller and larger for earlier sub sets so that later it is possible to make other subsets of required sum and the final expected output could be true.

**Comment by jstapankumar** [comment]
please have a look at this issue 😊 .

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
