### ISSUE TITLE
Permutations

### ISSUE THREAD

**Issue by ddfire** [LeetCode-Feedback/LeetCode-Feedback#162]
**What kind of the bug**
- [X ] problem
- [ ] solution
- [ ] language

**Describe the bug**
Run code in the editor mark a solution as wrong, when submitted is accepted.
this happens event with the solution  proposed by LeetCode.
this is the link of the problematic exercice
https://leetcode.com/explore/interview/card/facebook/53/recursion-3/292

**what language is your code written in**
Java

**The code you submit/run**

**Expected behavior**
Run code in the editor and Submitted code should have the same criteria.
**Screenshots**

**Additional context**
in this case editor was complaining about the order of the permutations, all where unique but was not in the order expected. when submitted it was accepted.
Happens also with the solution provided by leetcode

**Comment by CooperCooperCooper** [comment]
Hi @ddfire,
Thank you for reaching out to us. To help us assess this issue, can you please share your code and the language it's written in here?

**Comment by CooperCooperCooper** [comment]
Hi @ddfire,
Since we have not heard from you for a while, we will be closing this issue for now. Thank you for your understanding.
