### ISSUE TITLE
741. Cherry Pickup - Irregular description

### ISSUE THREAD

**Issue by jiahy0825** [LeetCode-Feedback/LeetCode-Feedback#1620]
#### Your LeetCode username

Devin-hyJia

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The description is not standardized, and there is an extra black dot under Note.

#### Screenshots

![741  Cherry Pickup](https://user-images.githubusercontent.com/17810795/101582481-effd2100-3a15-11eb-8c09-f41cdf1c656e.png)

**Comment by lc-kay** [comment]
Hi @jiahy0825 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @jiahy0825 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
