### ISSUE TITLE
354. Russian Doll Envelopes

### ISSUE THREAD

**Issue by NVJ9SINGHNAVJOT** [LeetCode-Feedback/LeetCode-Feedback#16208]
#### Category of the bug
-  Question
-  Solution

#### Description of the bug

          envelopes = [[5,4],[6,5],[6,7],[2,3]]

          Output = should be 4
          4 as per this arrangement  =  [2,3]  <-  [5,4]  <-  [6,5]  <-  [6,7]  (as envelope can be rotated)  
          Expected = 3 (by leetcode)

![Screenshot (45)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/121451924/e5bb5eb8-a53f-4242-8293-5e3b5368781c)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by NVJ9SINGHNAVJOT** [comment]
Okay got it.

**Comment by NVJ9SINGHNAVJOT** [comment]
Thank you for your reply. I hope this email finds you well. I am writing to
inform you that the issue I reported has been resolved. I appreciate the
efforts of your team in addressing the problem.
