### ISSUE TITLE
Missing Test Case - 2842. Count K-Subsequences of a String With Maximum Beauty

### ISSUE THREAD

**Issue by shuiyunfeng** [LeetCode-Feedback/LeetCode-Feedback#16214]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I set "qqwweerrttyyuuiiooppaassddffgghhjjkkllzzxxccvvbbnnmm" as s, set 10 as k.
When I run some answers, they can’t pass the case, but they passed the  test.

#### Code you used for Submit/Run operation

```
class Solution {
    public int countKSubsequencesWithMaxBeauty(String s, int k) {
        final long MOD = 1_000_000_007;

        int[] li = new int[26];
        for (char ch : s.toCharArray()) li[ch - 'a']++;

        Arrays.sort(li);
        int len = 0;
        for (int cnt : li) {
            if (cnt > 0) len++;
        }

        if (len < k) return 0;

        long sum = 1l;
        for (int i = 26 - k; i < 26; i++) sum = sum * li[i] % MOD;

        int a = 0, b = 0;
        for (int i = 26 - k, j = i; i < 26 && li[i] == li[j]; i++) b++;
        for (int i = 26 - k - 1, j = 26 - k; i >= 0 && li[i] == li[j]; i--) a++;

        long res = 1l;
        for (int i = a + b; i > b; i--) res *= i;
        for (int i = a; i > 0; i--) res /= i;

        return (int)(sum * res % MOD);
    }
}
```

#### Language used for code

Java

#### Screenshots

![1693930665603](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/58367214/cdf50b57-2939-4cd1-aa07-e050977bb596)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've used your feedback to update the problem.

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback.

Please provide us with your LCCN or LCUS username.

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
