### ISSUE TITLE
Missing Test Case - 73. Set Matrix Zeroes

### ISSUE THREAD

**Issue by ayushkr012** [LeetCode-Feedback/LeetCode-Feedback#16215]
#### Your LeetCode username

ayushkr01

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases  ---------> Misssing Test Case

#### Description of the bug

My code is `Accepted`  but for  this test case   --------> `[[-9999,1,1],[1,0,1],[1,1,1]] ` it fails   when I `Exclude this test case` Code is Accepted 

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/136481697/0ae2b4d7-cd99-44c0-9a17-1cb66845b0c4)

#### Code you used for Submit/Run operation

```
class Solution {
public: // time O(M*N) space O(1)
    void setZeroes(vector<vector<int>>& matrix) {
        int m=matrix.size(),n=matrix[0].size();
        for(int i=0;i<m;i++){
            for(int j=0;j<n;j++){
                if(matrix[i][j]==0){
                    for(int k=0;k<n;k++){
                       if(matrix[i][k]!=0){
                           matrix[i][k]=-9999;
                       }
                    }
                }
            }
        }
        for(int i=0;i<m;i++){
            for(int j=0;j<n;j++){
                if(matrix[i][j]==0){
                    for(int k=0;k<m;k++){
                        if(matrix[k][j]!=0)matrix[k][j]=-9999;
                    }
                }
            }
        }
        for(int i=0;i<m;i++){
            for(int j=0;j<n;j++){
                if(matrix[i][j]==-9999){
                    matrix[i][j]=0;
                }
            }
        }       
    }
};

```

#### Language used for code

C++

#### Expected behavior

First, you should submit my code without including this `[[-9999,1,1],[1,0,1],[1,1,1]]`  test case. Then, display the `result as "Verified: Accepted`." Afterward, `include this test case and submit again`. This will help them better understand the missing test case and clarify the situation. After that, `display the result as "Verified: Wrong`."

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
