### ISSUE TITLE
Missing Test Case - 1484. Group Sold Products By The Date

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1621]
#### Your LeetCode username

[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

**Suppose on a particular date zero items were sold. So in that case the input will be -**

{"headers":{"Activities":["sell_date","product"]},"rows":{"Activities":[["2020-05-30",null]]}}

**The output for this will be -**

{"headers": ["sell_date", "num_sold", "products"], "values": [["2020-05-30", 0, null]]}

**But in console, it is showing that on the date "2020-05-30" the number of items sold is 1 and products are "null", Which is incorrect. The problem is missing the bove test case-**

{"headers": ["sell_date", "num_sold", "products"], "values": [["2020-05-30", 1, null]]}

![image](https://user-images.githubusercontent.com/71989691/101598535-5423e300-3a1e-11eb-949f-34c38bec9c77.png)

**Accepting inputs the wrong data type- accepting numeric data type -**

{"headers":{"Activities":["sell_date","product"]},"rows":{"Activities":[["2020-05-30",1],["2020-05-30",2],["2020-05-30",3],["2020-05-30",4],["2020-05-30",5]]}}

![image](https://user-images.githubusercontent.com/71989691/101598993-fe9c0600-3a1e-11eb-96b3-b63cfbb9e767.png)

#### Code you used for Submit/Run operation

```
# Write your MySQL query statement below

SELECT A.SELL_DATE AS sell_date, COUNT(distinct A.product) AS num_sold, GROUP_CONCAT(distinct (A.product)) AS products FROM ACTIVITIES AS A
GROUP BY A.SELL_DATE
order by a.sell_date
```

#### Language used for code

MySQL

#### Expected behavior

**Missing test case-**
{"headers":{"Activities":["sell_date","product"]},"rows":{"Activities":[["2020-05-30",null]]}}

**Accepting incorrect input- data type is not varchar-**
{"headers":{"Activities":["sell_date","product"]},"rows":{"Activities":[["2020-05-30",1],["2020-05-30",2],["2020-05-30",3],["2020-05-30",4],["2020-05-30",5]]}}

#### Additional context

Problem: https://leetcode.com/problems/group-sold-products-by-the-date/

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@pratap-082020 Our team has reviewed your report and ruled it as an invalid input because product is null.
