### ISSUE TITLE
Mistake in Solution 

### ISSUE THREAD

**Issue by Hr1t1k** [LeetCode-Feedback/LeetCode-Feedback#16219]
#### Category of the bug
- [ ] Question
- [ 1] Solution 
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

There is a small mistake in the solution provided In the editorial of the problem https://leetcode.com/problems/distinct-subsequences-ii/editorial/
It is mentioned that the formula is dp[k] = 2 * dp[k-1] - dp[last[S[k]] - 1]

but in the code the formula is changed to dp[k]*2*dp[k-1]-dp[last[S[k-1]] (this one is correct )

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/52287344/3cfc8db2-67a1-4d7f-b3bf-4c3dc3a6d5a5)
![Screenshot 2023-09-06 033657](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/52287344/308dcdc7-2d96-4832-9a68-fde342bea107)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
