### ISSUE TITLE
Wrong Test Case - 287. Find the Duplicate Number

### ISSUE THREAD

**Issue by ADlv21** [LeetCode-Feedback/LeetCode-Feedback#16216]
#### Your LeetCode username
adwaitg02

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Wrong Test Case for 287 Find Duplicate Number

#### Code you used for Submit/Run operation

```
class Solution {
    public int findDuplicate(int[] nums) {
        int len = nums.length-1;
        int sumOfN = (len*(len+1))/2;
        int sumOfArray = 0;
        for(int i : nums){
            sumOfArray += i;
        }
        return sumOfArray - sumOfN;
    }
}
```

#### Language used for code
Java 

#### Expected behavior
Test case should be from 1 to N and only a single number including 1 to N should be repeated eg: 1,2,3,4,5,2
But here 2,2,2,2,2 is given as test case and should be removed.

#### Screenshots
<img width="1430" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/84146707/ad75c735-8f44-4645-bbc6-07a87d71977c">

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
