### ISSUE TITLE
1565. Unique Orders and Customers Per Month - Accepting wrong input

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1622]
#### Your LeetCode username

[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

**Accepting wrong input here-**

- Accepting the wrong date.
- Accepting a negative date.
- Accepting the wrong data type.

{"headers":{"Orders":["order_id","order_date","customer_id","invoice"]},"rows":{"Orders":[[1,"2020-09-15",1,30],[2,"2020-09-17",2,90],[3,"2020-10-06",3,20],[4,"2020-10-20",3,21],[5,"2020-11-10",1,10],[6,"2020-11-21",2,15],[7,"2020-12-01",4,55],[8,"-2020-12-03",4,77],["9","2021-01-07",3,31],[10,"20201-13-00","2","20"]]}}

![image](https://user-images.githubusercontent.com/71989691/101604849-7e2dd300-3a27-11eb-9bf1-75ec6ba4c54c.png)

![image](https://user-images.githubusercontent.com/71989691/101605080-c5b45f00-3a27-11eb-9566-d6e4e066f6a8.png)

#### Code you used for Submit/Run operation

```
# Write your MySQL query statement below

SELECT SUBSTRING(convert((A.ORDER_DATE),char),1,7) AS MONTH, count(A.ORDER_ID) as order_count, count( distinct a.customer_id) as customer_count FROM ORDERS AS A
WHERE A.INVOICE > 20
GROUP BY A.ORDER_DATE - DAY(A.ORDER_DATE)
```

#### Language used for code

MySQL

#### Expected behavior

**Accepting wrong input here-**

- Accepting the wrong date.
- Accepting a negative date.
- Accepting the wrong data type.

#### Additional context

Problem: https://leetcode.com/problems/unique-orders-and-customers-per-month/

**Comment by lc-kay** [comment]
@pratap-082020 Thank you for your time. We have acknowledged the issue. However, we found this kind of report is not eligible for a reward.
