### ISSUE TITLE
Wrong Submission Evaluated

### ISSUE THREAD

**Issue by michaelahlers** [LeetCode-Feedback/LeetCode-Feedback#16220]
#### Your LeetCode username
`michaelahlers`

#### Category of the bug
- [ ] Question
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
Another user's submission appears to be run instead of my own for https://leetcode.com/problems/copy-list-with-random-pointer.

#### Code you used for Submit/Run operation

```scala
import scala.annotation.tailrec
import scala.collection.immutable.HashMap

object Solution {

  def copyRandomList(head: Node): Node = {

    /** Solution omitted. */
    @tailrec
    def copy(original: Node, visited: Map[Node, Node]): Node = ???
	
    copy(head, HashMap((null, null)))
  }

}
```

I get these errors when I run or submit:

```
Line 104: error: value put is not a member of scala.collection.immutable.HashMap[Node,Int] (in solution.scala)
did you mean get or sum?
            map.put(cur, nodes.size)
                ^
Line 155: error: value put is not a member of scala.collection.immutable.HashMap[Node,Node] (in solution.scala)
did you mean get or sum?
                nextHash.put(now, now.next)
                         ^
Line 156: error: value put is not a member of scala.collection.immutable.HashMap[Node,Node] (in solution.scala)
did you mean get or sum?
                randomHash.put(now, now.random)
                           ^
```

Those errors seem suspiciously like they belong to another user.

And, of course, my code compiles (and passes unit tests) locally.

#### Language used for code

Scala

#### Expected behavior

_My_ submission should be evaluated, not another user's.

#### Screenshots

<img width="681" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2034877/eeeaa5cb-0b69-4de4-a278-8adbdc306c5c">

#### Additional context

Working on this problem: https://leetcode.com/problems/copy-list-with-random-pointer/description/.

**Comment by michaelahlers** [comment]
If I put the `import` statements outside `object Solution`, I get the errors:

<img width="874" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2034877/f93cd800-42e2-4b65-ab46-afbbef1f93b6">

However, if I move them inside the `object`, compilation succeeds:

<img width="876" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2034877/1f43b694-dbce-45f8-bf10-c51a0247bcca">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by michaelahlers** [comment]
@LC-Pam, sorry for the delay! [This link's to a submission that wouldn't compile (with seemingly irrelevant compiler errors)](https://leetcode.com/problems/copy-list-with-random-pointer/submissions/1042626388/), and [this one points to a working submission (where the imports are scoped inside `object Solution`)](https://leetcode.com/problems/copy-list-with-random-pointer/submissions/1042660463/).

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Please ask your question in the discussion forum.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
