### ISSUE TITLE
Missing Test Case - 5. Longest Palindromic Substring

### ISSUE THREAD

**Issue by 1614229511** [LeetCode-Feedback/LeetCode-Feedback#16227]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```python3 []

class Solution:
    @staticmethod
    def longestPalindrome(s: str) -> str:
        n = len(s)
        s_list = [[""] * (n+1) for _ in range(n)]
        reverse_list = s[::-1]
        if s in reverse_list:
            return s
        for i in range(1, n+1): #
            for j in range(n-i+1):
                if s[j:j+i] in reverse_list:
                    s_list[j][i] = s[j:j+i]
                      
        for i in range(n, 0, -1):
            for j in range(n-i+1):
                if s_list[j][i]:
                    return s_list[j][i] 

```

#### Language used for code

python3.0

#### Expected behavior

why this usage "aacabdkacaa" whos expected answer is "aca" not "aaca"

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/64690214/e31d2190-722f-44ec-ba7c-d348a028b88d)

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
