### ISSUE TITLE
Count Subarrays With Fixed Bounds - Monotonic Queue

### ISSUE THREAD

**Issue by roishevah** [LeetCode-Feedback/LeetCode-Feedback#16226]
#### Category of the bug
- [ V] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
This question is tagged with possible solution using queue/monotonnic queue, but it seems like it's not related to the question.
Can you please exaplain why/how monotonnic queue should be used to solve this question?
I opened an issue for that (#15950) but you closed it. Why? is it not the place to ask this question?

Thanks,
Roi

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

Please ask your question in the discussion forum.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
