### ISSUE TITLE
Missing Test Case - 15. 3Sum

### ISSUE THREAD

**Issue by jzau** [LeetCode-Feedback/LeetCode-Feedback#16234]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My solution passed it but actually, this test case got TLE and it's a valid test case.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    public List<List<Integer>> threeSum(int[] nums) {
        List<List<Integer>> res = new ArrayList<List<Integer>>();
        Arrays.sort(nums);
        
        for (int i = 0; i < nums.length - 2; i++) {
            if(nums[i] > 0) {
                break;
            }
            int lo = i + 1;
            int hi = nums.length - 1;
            while(hi > lo) {
                if(nums[hi] < 0) {
                    break;
                }
                if(nums[i] + nums[lo] + nums[hi] == 0) {
                    List<Integer> t = new ArrayList<Integer>();
                    t.add(nums[i]);
                    t.add(nums[lo]);
                    t.add(nums[hi]);
                    res.add(t);
                    while(lo+1 < hi && nums[lo] == nums[lo+1]) {
                        lo++;
                    }
                    while(hi-1 > lo && nums[hi] == nums[hi - 1]) {
                        hi--;
                    }
                    lo++;
                    hi--;
                } else if(nums[i] + nums[lo] + nums[hi] < 0) {
                    lo++;
                } else {
                    hi--;
                }
            }
            while(i + 1< nums.length - 2 && nums[i] == nums[i+1]){
                i++;
            }
        }

        return res;
    }
}
```

#### Expected behavior

`3 <= nums.length <= 3000`
so I generated an array range [-1500, 1499], and it got TLE but the solution was accepted

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Hi there,

Your feedback has been instrumental in enhancing the problem. 

To ensure you receive your well-deserved 100 LeetCoins reward, could you kindly provide us with your LeetCode username? This will allow us to credit your account accurately.

Your participation and contributions are valued, and we want to make sure you enjoy the rewards you've earned.

Thank you for being part of the LeetCode community!

Best regards,
LeetCode Team

**Comment by jzau** [comment]
Hi,

Thanks for getting back to me, my leetcode username is jackyzh
Thanks!

Regards,
Jie

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
