### ISSUE TITLE
1407. Top Travellers -  Accepting duplicate primary key

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1623]
#### Your LeetCode username

[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

**Accepting duplicate primary key- ids are primary key so the platform should not accept the duplicate primary keys here-**

{"headers":{"Users":["id","name"],"Rides":["id","user_id","distance"]},"rows":{"Users":[**[1,"Alice"],[1,"Bob"]**,[3,"Alex"],[4,"Donald"],[7,"Lee"],[13,"Jonathan"],[19,"Elvis"]],"Rides":[**[1,1,120],[1,2,317]**,[3,3,222],[4,7,100],[5,13,312],[6,19,50],[7,7,120],[8,19,400],[9,7,230]]}}

![image](https://user-images.githubusercontent.com/71989691/101606545-825af000-3a29-11eb-8238-5dc6c5900c8d.png)

Accepting incorrect data types in inputs - 

{"headers":{"Users":["id","name"],"Rides":["id","user_id","distance"]},"rows":{"Users":[[**"1"**,"Alice"]],"Rides":[[**"9","7","230"**],[2,3,"230"]]}}

![image](https://user-images.githubusercontent.com/71989691/101610943-e46a2400-3a2e-11eb-8dbe-0e0e438ef123.png)

#### Code you used for Submit/Run operation

```
# NA
```

#### Language used for code

MySQL

#### Expected behavior

Should not accept the duplicate primary key.
Input data types are different than accepted.

#### Additional context

Problem - https://leetcode.com/problems/top-travellers/

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. We appreciate your support!
