### ISSUE TITLE
Incorrect output for test case

### ISSUE THREAD

**Issue by robinskum** [LeetCode-Feedback/LeetCode-Feedback#16233]
#### Your LeetCode username
 robinskumar

#### Category of the bug
- [ ] Question
- [1 ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

For the input  -> prices = [1,4,2] 
Output should be -> 2

#### Code you used for Submit/Run operation

```
// [121. Best Time to Buy and Sell Stock](https://leetcode.com/problems/best-time-to-buy-and-sell-stock/)
class Solution:
    def maxProfit(self, prices: List[int]) -> int:

        buy = min(prices)
        buy_idx = prices.index(buy)

        if buy_idx == len(prices)-1:
            return 0
        else:
            sell = max(prices[buy_idx:])
            if sell <= buy:
                return 0
            else:
                res = prices.index(sell, buy_idx) 
                return res+1
```

#### Language used for code
 Python3

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/48359537/6f66acc6-9268-492d-ac67-e9b8338c1ba6)

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
