### ISSUE TITLE
Missing Test Case - 1383. Maximum Performance of a Team

### ISSUE THREAD

**Issue by muye20** [LeetCode-Feedback/LeetCode-Feedback#16245]
#### Your LeetCode username

[DATOU2016](https://leetcode.com/DATOU2016/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

For the following input
~~~
n = 2
speed = [100,1]
efficiency = [2,1]
k= 2
~~~
Its output should be 101 because `(100 + 1) * min(2, 1) = 101`
But the expected output from leetcode is 200

#### Code you used for Submit/Run operation

~~~python
class Solution(object):
    def maxPerformance(self, n, speed, efficiency, k):
        """
        :type n: int
        :type speed: List[int]
        :type efficiency: List[int]
        :type k: int
        :rtype: int
        """
        engineers = [(efficiency[i], speed[i]) for i in range(n)]
        engineers.sort(reverse=True)
        total, ans = 0, 0
        min_heap = []

        for eff, spd in engineers:
            if len(min_heap) == k:
                total -= heapq.heappop(min_heap)

            total += spd
            heapq.heappush(min_heap, spd)
            ans = max(ans, total * eff)

        return ans % (10 ** 9 + 7)
~~~

#### Language used for code

python

#### Expected behavior

Its output should be 101 because `(100 + 1) * min(2, 1) = 101`
But the expected output from leetcode is 200

#### Screenshots

<img width="762" alt="Screenshot 2023-09-06 at 8 50 35 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/8950243/09d7a877-2672-4a72-ae6c-0365b439f157">

#### Additional context

An incorrect result was produced for the test case shown above

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Please ask your question in the discussion forum.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
