### ISSUE TITLE
1069. Product Sales Analysis II - Problem description is incomplete

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1624]
#### Your LeetCode username

[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

There is no use of the product table in the result table. No column of the product table is in the result table.

![image](https://user-images.githubusercontent.com/71989691/101612677-eb923180-3a30-11eb-865e-6ca59345cb12.png)

**Giving the wrong output for the below input-**

{"headers":{"Sales":["sale_id","product_id","year","quantity","price"],"Product":["product_id","product_name"]},"rows":{"Sales":[[null,null,2008,10,5000],[2,null,2009,12,5000],[7,200,2011,15,9000]],"Product":[[100,"Nokia"],[200,"Apple"],[300,"Samsung"]]}}

![image](https://user-images.githubusercontent.com/71989691/101613154-6c512d80-3a31-11eb-95c2-36f8cbbd5823.png)

**for more than 2 null ids result can be the addition of both as both the products are different**

#### Code you used for Submit/Run operation

```
# Write your MySQL query statement below
SELECT A.PRODUCT_ID, SUM(A.QUANTITY) AS TOTAL_QUANTITY FROM SALES AS A
GROUP BY A.PRODUCT_ID
```

#### Language used for code

MySQL

#### Expected behavior

The problem description is missing.
The problem giving the wrong output for the above-mentioned inputs.

#### Additional context

Problem- https://leetcode.com/problems/product-sales-analysis-ii/

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for your time. The team reviewed your report and ruled it as an invalid test case. We appreciate your support!
