### ISSUE TITLE
User information in the solution list is wrong.

### ISSUE THREAD

**Issue by pengxurui** [LeetCode-Feedback/LeetCode-Feedback#16247]
#### Your LeetCode username
pengxurui

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Information Display wrong.

#### Expected behavior
Display correct information

#### Screenshots

<img width="393" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/25008934/43e70622-b723-4f8c-aae4-43c3c7455a33">

<img width="647" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/25008934/8eb7a3c4-94c9-4bba-8113-5972c8fe4883">

**Comment by feiceh** [comment]
感谢反馈，该问题已转给相关团队跟进核实。Github 仓库只用于反馈大家在本站学习过程中遇到的题目和题解问题，目前我们会暂时关闭该 issue，后续使用中有任何问题欢迎 [提交工单](https://support.leetcode-cn.com/hc/request/new/) 反馈，我们会定期更新，保障稳定和体验优化。
