### ISSUE TITLE
Invalid Constraints for JavaScript - 2847. Smallest Number With Given Digit Product

### ISSUE THREAD

**Issue by GroverW** [LeetCode-Feedback/LeetCode-Feedback#16241]
#### Your LeetCode username

ektegjetost

#### Category of the bug
- [ ] Question
- [ ] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug

JavaScript doesn't support numbers above 9007199254740991 (roughly 10^16), so the test constraints of n <= 10^18 are impossible to pass (the input will be truncated)

#### Code you used for Submit/Run operation

```javascript
var smallestNumber = function(n) {
  if (n === 1) return "1"

  const primes = [2n, 3n, 5n, 7n];
  const factors = [];

  let remain = BigInt(n.toString());

  for (const prime of primes) {
    while (remain % prime === 0n) {
      factors.push(prime);
      remain /= prime;
    }
  }

  if (remain > 1n) return "-1";

  return mergeFactors(mergeTwos(factors)).join('');
};

const mergeTwos = (factors) => {
  const merged = [];
  for (let i = 2; i < factors.length; i += 3) {
    if (factors[i] === 2n) merged.push(8n)
  }

  return [...merged, ...factors.slice(merged.length * 3)]
    .sort((a, b) => a <= b ? -1 : 1)
}

const mergeFactors = (factors) => {
  const merged = [];
  for (const factor of factors.reverse()) {
    if (merged.length && factor * merged.at(-1) < 10n) {
      merged.push(factor * merged.pop())
    } else {
      merged.push(factor);
    }
  }
  return merged.sort((a, b) => a <= b ? -1 : 1);
}
```

#### Language used for code

JavaScript

#### Expected behavior

The code should pass.

Here's a failing submission
https://leetcode.com/problems/smallest-number-with-given-digit-product/submissions/1042329408/

#### Screenshots

If I log n, you can see JavaScript isn't precise enough to use a number this large
<img width="235" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/53848560/2ab5d02f-b658-4ece-8cf8-837b92796c4c">

I can run the code in console with the input as a BigInt, and I get the correct answer
<img width="199" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/53848560/e97dc986-aaaf-4d2c-a687-4f5bd8da1ac7">

#### Additional context

Could use a BigInt input

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team

**Comment by GroverW** [comment]
@LC-Pam this is a similar issue as multiple problems in the past
https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/9625

https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/6632

JavaScript uses float-64s for numbers, and cannot represent integers >= ~10^16.

There are multiple test cases which simply cannot be predictably answered without advanced knowledge.

There was a small amount of discussion about this
https://leetcode.com/problems/smallest-number-with-given-digit-product/solutions/4015842/anyone-got-a-strategy-for-handling-the-constraints-with-javascript/comments/2052270/
