### ISSUE TITLE
Missing Test Case - 110. Balanced Binary Tree

### ISSUE THREAD

**Issue by mazurkin** [LeetCode-Feedback/LeetCode-Feedback#16243]
#### Your LeetCode username
[nickmz](https://leetcode.com/nickmz/)

#### Category of the bug
- [+] Missing Test Cases 

#### Description of the bug
A lot of people use `1+max(left, right)` to report just one maximum depth to uplevel.

Even the most upvoted solution like this https://leetcode.com/problems/balanced-binary-tree/solutions/2428871/very-easy-100-fully-explained-c-java-python-javascript-python3/

The problem is that this is not right and there are some tree which passes the current set of tests but not balanced, for example this one: `[1,2,2,3,3,3,3,4,4,4,4,null,null,4,4,5,5]`

This graph is not balanced as have terminal nodes on level 3 and 5, but this graph passes the test for the most popular solutions.

![2023-09-06_17-19](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/832206/caacd2a8-2a94-4eb8-bf07-7206dcc677eb)

**Comment by mazurkin** [comment]
My apologies, there is already the test 221 / 228:
`[1,2,2,3,3,3,3,4,4,4,4,4,4,null,null,5,5]`

And the expected result now is `true`.

How it can be `true` as the root node `1` has a subtree `1-2-3` of length 3 and another subtree `1-2-3-4-5` of length 5?

![2023-09-06_18-09](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/832206/3737fe96-98be-4074-972b-d5d73f1e62a0)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link that you reach to this result. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by mazurkin** [comment]
This is not about the code, this is about the test case of yours. Are you sure this test case is an actual balanced tree?

![2023-09-06_18-10](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/832206/d0c48e0b-aed7-4143-9a0f-d4a15ca8cdfd)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
