### ISSUE TITLE
Missing Test Case - 1670. Design Front Middle Back Queue

### ISSUE THREAD

**Issue by liyanxiangable** [LeetCode-Feedback/LeetCode-Feedback#16240]
#### Your LeetCode username

liyanxiang

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [√ ] Missing Test Cases 

#### Description of the bug

Question 1670 neglects the duplicated element issue

#### Code you used for Submit/Run operation

```
class FrontMiddleBackQueue {

    LinkedList<Integer> list = new LinkedList<>();

    public FrontMiddleBackQueue() {
        list = new LinkedList<>();
    }
    
    public void pushFront(int val) {
        list.addFirst(val);
    }
    
    public void pushMiddle(int val) {
        list.add(list.size() / 2, val);
    }
    
    public void pushBack(int val) {
        list.addLast(val);
    }
    
    public int popFront() {
        if (list.isEmpty()) {
            return -1;
        }
        int f = list.getFirst();
        list.removeFirst();
        return f;
    }
    
    // remove indexOf 在中间元素有重复值的情况下删除错误位置的元素
    public int popMiddle() {
        if (list.isEmpty()) {
            return -1;
        }
        int m = list.get((list.size() - 1) / 2);
        list.remove(list.indexOf(m));
        return m;
    }
    
    public int popBack() {
        if (list.isEmpty()) {
            return -1;
        }
        int b = list.getLast();
        list.removeLast();
        return b;
    }
}

```

#### Language used for code

Java

#### Expected behavior

example:
["FrontMiddleBackQueue","pushBack","pushBack","pushBack","pushBack","pushBack","popMiddle","popMiddle","popMiddle","popBack","popFront"]

[[],[1],[5],[1],[2],[3],[],[],[],[],[]]

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
