### ISSUE TITLE
Missing Test Case - 1410. HTML Entity Parser

### ISSUE THREAD

**Issue by Matvibhor24** [LeetCode-Feedback/LeetCode-Feedback#16249]
#### Your LeetCode username
matvibhor24

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

The constraints on the problem include only the length of the input string and the input string may contain any possible characters out of all the 256 ASCII characters. But there is no condition about where the '&' can come.

There is no test case in the problem with '&' as the very last character of the input string. 
In the problem, we are given some HTML entities and their special characters. (For the sake of this problem, I call them valid entities)

In the case of '&' as the very last character of the input string, we expect the replacement of all the valid entities in between, by their special characters and remaining characters (not part of a valid HTML entity) as it is.

Let's take an example test case : 
                                      **input string text = "&&& &amp; is a &"**

The below code returns the wrong output - "&&& &amp; is a &" for the above example test case and as such should fail, but it passes all given tests.

#### Code you used for Submit/Run operation

```
// HTML Entity Parser

class Solution {
public:
    string entityParser(string text) {
        string ans = "";
        bool check = false;
        int idx = 0;
        string temp = "";
        for (int i = 0 ; i<text.size() ; i++){
            
            if (text[i]=='&' && !check){
                idx = i;
                check = true;
            
            }
            
            else if (check && text[i]==';'){
                check=false;
               
           
                if (temp=="quot"){
                    ans+='"';
                }
                else if (temp=="apos" ){
                   ans+="'"; 
                }
                else if (temp=="amp"){
                    ans+='&';
                }
                else if (temp=="gt"){
                    ans+='>'; 
                }
                else if (temp=="lt"){
                    ans+='<'; 
                }
                else if (temp=="frasl"){
                    ans+='/'; 
                }
                else{
                    ans+='&';
                    i=idx;
                }
                temp.clear();                    
            }
            else if (check){
                temp+=text[i];
        
            }
            else{
                ans+=text[i];
  
            }
        }

        if (check){
//HERE THE WRONG OUTPUT TO THE TEST CASE HAPPENS BUT STILL, THIS TEST CASE GETS ACCEPTED.
            ans=text;
        }
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

This code is wrong because it's not handling the case when '&' is the very last character of the input string.

We expect the replacement of all the valid entities in between, by their special characters and the remaining characters (not part of a valid HTML entity) as it is.
So, Expected Output is "&&& & is a &" 
The code above, as it does not cover all cases, should fail.

#### Screenshots

-> Screenshot 1 (my code is giving the wrong answer for this test case)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/99306756/39faca4c-bb69-4938-a6bb-9498dcf95614)

-> Screenshot 2 (But my code got Accepted)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/99306756/39a079e7-2df3-43ab-b25a-0370e2fec554)

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/99306756/ba993332-b427-4b59-b85e-6bdcffb5e87f)

#### Additional context

->There are some test cases where '&' not only at last but in between also produces the wrong output. Means the valid entities in between should be replaced by their special characters. But the problem accepts solutions even if valid HTML entities in between are not replaced and returned in output as it is.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by Matvibhor24** [comment]
Thanks @LC-Pam !! Looking forward to the update.

> Hi there,
> 
> Thank you for reaching out to us.
> 
>  We've relayed this issue to our team to investigate. 
> 
> We will reach back to you after we have the results.
> 
> Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
