### ISSUE TITLE
Missing Test Case - 372. Super Pow

### ISSUE THREAD

**Issue by leanhhuy0709** [LeetCode-Feedback/LeetCode-Feedback#16248]
#### Your LeetCode username

leanhhuy

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// [Super Pow]
class Solution {
public:
    int superPow(int a, vector<int>& b) {
        //b % 1140
        //a % 1337
        a %= 1337;
        int st = 0, num = 0, ed = 0;
        while(ed < b.size())
        {
            ed = min(st + 5, int(b.size()));
            for (int i = st; i < ed; i++)
            {
                num = num * 10 + b[i];
            }
            num %= 1140;
            st = ed;
        }
        int res = 1;
        for (int i = 0; i < num; i++)
        {
            res = (res * a) % 1337;
        }
        return res;
    }
};
```

#### Language used for code

C++ 

#### Expected behavior

a = 7;
b = [1, 1, 4, 0];

I got this test wrong but still correct when submitting.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
