### ISSUE TITLE
1173. Immediate Food Delivery I - Accepting incorrect dates-

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1625]
#### Your LeetCode username

[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

**Accepting incorrect dates-**

{"headers":{"Delivery":["delivery_id","customer_id","order_date","customer_pref_delivery_date"]},"rows":{"Delivery":[[1,1,"2019-08-01","2019-08-02"],[2,5,"2019-08-02","2019-08-02"],[3,1,**"null","null"**],[4,3,"2019-08-24","2019-08-26"],[5,4,null,null],[6,2,"2019-08-11","2019-08-13"]]}}

![image](https://user-images.githubusercontent.com/71989691/101618250-bf2de380-3a37-11eb-89bf-5ee4aed7230e.png)

#### Code you used for Submit/Run operation

```
select round(sum(case when order_date =customer_pref_delivery_date then 1 else 0 end)/count(*)*100, 2) immediate_percentage from Delivery
```

#### Language used for code

MySQL

#### Expected behavior

Accepting incorrect dates

#### Additional context

Problem- https://leetcode.com/problems/immediate-food-delivery-i/

**Comment by lc-kay** [comment]
@pratap-082020 Thank you for your time. We have acknowledged the issue. However, we found this kind of report is not eligible for a reward.
