### ISSUE TITLE
Missing Test Case - 165 Compare Version Numbers

### ISSUE THREAD

**Issue by sowjkallepalli** [LeetCode-Feedback/LeetCode-Feedback#16261]
#### Your LeetCode username

Leetcode UserName : sowj577

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [Yes ] Missing Test Cases 

#### Description of the bug

"It seems like my code was expected to fail for a particular test case, and it did. However, when I submitted this failed code, it went through without any failing test cases. Hence, I understand that there are no test cases of this type for question 165. Now, I want to contribute my test case to this problem."

**Test case:** 
Version1 = "1.101" , version2 = "1.100001", Expected output : -1; Output from failed code : 0.

#### Code you used for Submit/Run operation

```
class Solution:
    def compareVersion(self, version1: str, version2: str) -> int:
        ver1 = version1.split(".")
        ver2 = version2.split(".")
        high = max(len(ver1),len(ver2))
        for i in range(high):

            if len(ver1) <= i:
                flag2 = False
                if ver2[i][-1] == "0":
                    flag2 = True

                v2 = ver2[i].replace("0","")
                if flag2:
                    v2 += "0"

                if v2 == '':
                    v2 = 0
                
                if int(v2) > 0:
                    return -1
            elif len(ver2) <=i:
                flag1 = False
                if ver1[i][-1] == "0":
                    flag1 = True
                v1 = ver1[i].replace("0","")
                if flag1:
                    v1 += "0"
                if v1 == '':
                    v1 = 0
                if int(v1) > 0:
                    return 1
            else:

                flag1 = False
                if ver1[i][-1] == "0":
                    flag1 = True
                flag2 = False
                if ver2[i][-1] == "0":
                    flag2 = True
                v1 = ver1[i].replace("0","")
                v2 = ver2[i].replace("0","")
                if flag2:
                    v2 += "0"
                if flag1:
                    v1 += "0"
                if v2 == '':
                    v2 = 0
                if v1 == '':
                    v1 = 0
                if int(v1) > int(v2):
                    return 1
                elif int(v1) < int(v2):
                    return -1
        return 0
```

#### Language used for code

Python

#### Additional context

![Screen Shot 2023-09-07 at 2 29 52 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103530046/012d330e-fd3f-4431-8ab4-518b5f82aae6)

![Screen Shot 2023-09-07 at 2 24 11 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103530046/e5321fc8-801c-4bd4-8e6b-611870bed072)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by sowjkallepalli** [comment]
Thanks @LC-Pam !! Looking forward to the update.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
