### ISSUE TITLE
Better Support for SQL Server in Sample Schema - 584. Find Customer Referee

### ISSUE THREAD

**Issue by TrickyCat** [LeetCode-Feedback/LeetCode-Feedback#16268]
#### Your LeetCode username
[TrickyCat](https://leetcode.com/TrickyCat)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Hello 👋.

At the moment of writing, the question [584. Find Customer Referee](https://leetcode.com/problems/find-customer-referee/) offers

- MySQL
- MS SQL Server
- Oracle

as the possible languages/environments for solving this problem.

At the same time, the provided schema sample for it is not that diverse and favors the dialect of MySQL.

And so, it fails for the obvious reason at execution time in SQL Server.

<br>

Thus, it doesn't meet the end-users' expectation for the sample bootstrap/startup code: **"sample code should just work"**

<br>

**In order to make the platform better**, I wonder whether there's an option:

- to add the new dialect of the schema side by side with the existing one (e.g. like we have Pandas schema next to SQL schema in other questions)

- or to add it right below the existing schema (and make hints with comments)

  ```sql
  -- MySQL Schema
  ...

  -- SQL Server Schema
  ...
  ```

### T-SQL Code That Worked

```sql
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'Customer')
BEGIN
  CREATE TABLE Customer (id INT, name VARCHAR(25), referee_id INT)
END
ELSE
BEGIN
  TRUNCATE TABLE Customer
END

INSERT INTO Customer (id, name, referee_id) VALUES ('1', 'Will', NULL)
INSERT INTO Customer (id, name, referee_id) VALUES ('2', 'Jane', NULL)
INSERT INTO Customer (id, name, referee_id) VALUES ('3', 'Alex', '2')
INSERT INTO Customer (id, name, referee_id) VALUES ('4', 'Bill', NULL)
INSERT INTO Customer (id, name, referee_id) VALUES ('5', 'Zack', '1')
INSERT INTO Customer (id, name, referee_id) VALUES ('6', 'Mark', '2')
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

We’ll consider it.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
