### ISSUE TITLE
编译奇怪现象

### ISSUE THREAD

**Issue by hechangtian15993091621** [LeetCode-Feedback/LeetCode-Feedback#1626]
** Bug 类型**
- [x] 题目 1302. 层数最深叶子节点的和
- [ ] 题解
- [ ] 编程语言 JAVA

**描述**
在提交代码页面，点击提交代码之后总是有一个样例不通过，但是点击执行代码按钮时，该样例与预期输出是一样的，很不理解为什么会这样子

**你使用的语言**
JAVA

**你提交或者运行的代码**
```
// Two Sum
class Solution {
    static int res = 0;
    static int maxDepth = -1;
    public static int deepestLeavesSum(TreeNode root) {
        dfs(root,0);
        return res;
    }

    private static void dfs(TreeNode root, int level) {
        if(root==null){
            return;
        }
        if(level>maxDepth){
            maxDepth = level;
            res = root.val;
        }else if(level==maxDepth){
            res+=root.val;
        }
        dfs(root.left,level+1);
        dfs(root.right,level+1);
    }
}
```

**期望行为**
期望成功提交

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![问题](https://user-images.githubusercontent.com/56825927/101621566-e2b15800-3a50-11eb-8fbd-ec383fe04523.jpg)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
你好，建议再仔细调试一下代码，希望这篇内容对你有帮助：https://leetcode.kf5.com/hc/kb/article/1194344/。 后续刷题学习中遇到困难，可通过阅读「题解」解决做题中的一些困惑，可以看看其他小伙伴的解题思路。
