### ISSUE TITLE
Missing Test Case - 49. Group Anagrams

### ISSUE THREAD

**Issue by JackLiu00521** [LeetCode-Feedback/LeetCode-Feedback#16262]
#### Your LeetCode username
jackliu00521

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Now there's no test cases with same characters existing over 9 times. Thus, using the following hashing still pass all test cases.
Adding new test case like `["aaaaaaaaaa", "b"]` can solve this.

#### Code you used for Submit/Run operation
```
class Solution:
    def groupAnagrams(self, strs: List[str]) -> List[List[str]]:
        hashTable = collections.defaultdict(list)
        
        for i, word in enumerate(strs):
            key = 0
            for char in word:
                digits = ord(char) - ord('a')
                key += 10 ** digits
            hashTable[key].append(word)
            
        return hashTable.values()
```

#### Language used for code
Python

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
