### ISSUE TITLE
Not yet resolved - https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/1551

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1627]
#### Your LeetCode username

[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Problem not resolved yet- https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/1551

Accepting incorrect data type in the input ->Input ids must be integers - but here accepting string type id.

Input:
{"headers": {"Weather": ["Id", "RecordDate", "Temperature"]}, "rows": {"Weather": [["1", "2015-01-01", 10], ["2", "2015-01-02", "25"], [3, "2015-01-03", 20], [4, "2015-01-04", 30]]}}

![image](https://user-images.githubusercontent.com/71989691/101678012-59ffdf80-3a83-11eb-96eb-56358b746cca.png)

#### Code you used for Submit/Run operation

```
# NA
```

#### Language used for code

MySQL

#### Expected behavior

Accepting incorrect data type in the input ->Input ids must be integers - but here accepting string type id.

#### Additional context

Problem - https://leetcode.com/problems/rising-temperature/

**Comment by lc-kay** [comment]
@pratap-082020 Thanks for bringing this to our attention. Our team has acknowledged this issue. However, this type of issue is not eligible for a reward, so I will close this ticket now. Thank you for understanding.

**Comment by pratap-082020** [comment]
@lc-kay Most of the problems are having these issues. No problem. Thank you.
