### ISSUE TITLE
Missing Test Case - 219. Contains Duplicate II

### ISSUE THREAD

**Issue by kacperturon** [LeetCode-Feedback/LeetCode-Feedback#16272]
#### Your LeetCode username
KacperTuron

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The solution below once submitted is accepted, even though it is not passing the test case I've provided here.

#### Code you used for Submit/Run operation
```js
var containsNearbyDuplicate = function(nums, k) {
  let d = {}, min = -1;
  for(let i = 0; i < nums.length; i++) {
    if(!(nums[i] in d)) {
       d[nums[i]] = i;
    }
    else {
      let val = Math.abs(i-d[nums[i]]);
      d[nums[i]] = val;
      if(min === -1 || val < min) {
        min = val;
        if(min <= k) return true;
      }
    }
  }  

  return min !== -1 && min <= k;
};
```

#### Language used for code

JS

#### Expected behavior

The solution should not be accepted, but there is not enough test cases to catch it.

#### Screenshots

<img width="812" alt="Screenshot 2023-09-08 at 13 28 10" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/10873763/1f9fd2b0-955a-409d-80da-8ed18093ff2e">
<img width="818" alt="Screenshot 2023-09-08 at 13 28 22" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/10873763/fcf51e3d-b72d-46fa-93be-5a1e228b10d0">

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
