### ISSUE TITLE
Bug in the testcase and question tags #2462 Total Cost to Hire K Workers

### ISSUE THREAD

**Issue by muthuvijay5** [LeetCode-Feedback/LeetCode-Feedback#16279]
#### LeetCode username
muthu_vijay

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

costs = [2,2,2,2,2,2,2,2,2,2,2,2,2,5,5,5,5,5,4,1,2,2,2,2,2,2]
k = 7
candidates = 3

For this testcase, the expected output is 14 according to LeetCode. But the actual output, according to the question is 13 (sum of last 7 integers in 'costs').

This shows that the given problem is not only based on Priority Queue but also includes dynamic programming.

#### Code you used for Submit/Run operation

```
// Total Cost to Hire K Workers
class Solution {
public:
    long long totalCost(vector<int>& costs, int k, int candidates) {
        priority_queue<int, vector<int>, greater<int>> pq1, pq2;
        long long res = 0;
        int i, j;

        for (i = 0; i < candidates; ++i)
            pq1.push(costs[i]);

        for (j = costs.size() - 1; j >= max(i, (int)(costs.size() - candidates)); --j)
            pq2.push(costs[j]);
        
        while (k != 0) {
            if (pq1.empty()) {
                res += pq2.top();
                pq2.pop();
            }

            else if (pq2.empty()) {
                res += pq1.top();
                pq1.pop();
            }

            else if (pq1.top() < pq2.top()) {
                res += pq1.top();
                pq1.pop();
                if (i <= j)
                    pq1.push(costs[i++]);
            }
            else if (pq1.top() > pq2.top()) {
                res += pq2.top();
                pq2.pop();
                if (i <= j)
                    pq2.push(costs[j--]);
            }
            else {
                if (costs[i] <= costs[j]) {
                    res += pq1.top();
                    pq1.pop();
                    if (i <= j)
                        pq1.push(costs[i++]);
                }
                else {
                    res += pq2.top();
                    pq2.pop();
                    if (i <= j)
                        pq2.push(costs[j--]);
                }
            }
            --k;
        }

        return res;
    }
};
```

#### Language used for code

C++

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/120384315/0a9a11bd-fdf6-425c-a202-e9a7c6decc82)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
