### ISSUE TITLE
SyntaxError: Identifier 'PriorityQueue' has already been declared in solution.js

### ISSUE THREAD

**Issue by SwethaSelva** [LeetCode-Feedback/LeetCode-Feedback#16284]
#### Your LeetCode username

[swethalakshmi64](https://leetcode.com/swethalakshmi64)

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I implemented the Priority Queue for the solution. Then I received the error - refer screenshot. When I changed the class name from "PriorityQueue" to "PQ" it worked. The reason I believe is your internal file has "PriorityQueue" to verify the user solution. This is conflicting with my PriorityQueue.

I suggestion is, use underscore before these class name or don't use the general name, append something like LeetCodePQ instead of "PriorityQueue"

#### Code you used for Submit/Run operation

```
class PriorityQueue {
    constructor () {
        this.heap = [];
    }
    size () {
        return this.heap.length;
    }
    findParent (childIdx) {
        return Math.floor((childIdx - 1) / 2);
    }
    findChildren (parentIdx) {
        return [2 * parentIdx + 1, 2 * parentIdx + 1];
    }
    swap (idx1, idx2) {
        [this.heap[idx1], this.heap[idx2]] = [this.heap[idx2], this.heap[idx1]];
    }
    comparator (idx1, idx2) {
        return this.heap[idx1][1] - this.heap[idx2][1];
    }
    peek() {
        return this.heap[0];
    }
    insert (val) {
        let curIdx = this.heap.push(val) - 1;

        while (curIdx > 0) {
            let parentIdx = this.findParent(curIdx);
            if (parentIdx < 0 || this.comparator(curIdx, parentIdx) >= 0) break;

            this.swap(curIdx, parentIdx);
            curIdx = parentIdx;
        }
    }
    poll () {
        this.swap(0, this.size() - 1);
        let remuvVal = this.heap.pop();

        let curIdx = 0;
        while (curIdx < this.size()) {
            let [leftIdx, rightIdx] = this.findChildren(curIdx);

            if (leftIdx >= this.size()) break;
            if (rightIdx < this.size() && this.comparator(rightIdx, leftIdx) < 0) {
                leftIdx = rightIdx;
            }

            if (this.comparator(leftIdx, curIdx) >= 0) break;

            this.swap(curIdx, leftIdx);
            curIdx = leftIdx;
        }
        return remuvVal;
    }
}
function networkDelayTime(times, n, k) {
    let adjList = new Array(n + 1).fill(0).map(_ => []); // [dest, time]

    for (let i = 0; i < times.length; i++) {
        let [src, dest, time] = times[i];

        adjList[src].push([dest, time]);
    }

    let distance = new Array(n + 1).fill(Infinity);
    distance[k] = 0;
    let visited = new Array(n + 1).fill(false);

    let q = new PriorityQueue();
    q.insert([k, 0]);

    while (q && q.size()) {
        let [node] = q.poll();
        if (visited[node]) continue;
        visited[node] = true;


        for (let neigh of adjList[node]) {
            let [neighNode, curTime] = neigh;
            let alt =  distance[node] + curTime;

            if (alt < distance[neighNode]) {
                distance[neighNode] = alt;
                q.insert([neighNode, alt]);
            }
        }
    }

    distance.shift();
    let max = Math.max(...distance);
    return max === Infinity? -1: max;
}
```

#### Language used for code

Javascript

#### Expected behavior

No error if the class name is "PriorityQueue"

#### Screenshots

Error if my solution has "PriorityQueue".
<img width="1512" alt="Screenshot 2023-09-09 at 1 11 31 AM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/58015008/d4eaa94d-9499-477e-b108-fb3996145399">

Worked after I changed the class name from "PriorityQueue" to "PQ"
<img width="1510" alt="Screenshot 2023-09-09 at 1 13 46 AM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/58015008/7f37b321-1def-4e19-9862-429fa2d1a53a">

#### Additional context

This simple bug caused me time so please take care of it ASAP.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by SwethaSelva** [comment]
May I know why is this reject?

I could clearly see the error comes up only when I use "PriorityQueue" as class name.
