### ISSUE TITLE
Missing Test Case - 783. Search in a Binary Search Tree

### ISSUE THREAD

**Issue by salorent** [LeetCode-Feedback/LeetCode-Feedback#1628]
#### Your LeetCode username

salorentzen

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

The expected answer does not return the correct answer to a custom testcase.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    TreeNode* searchBST(TreeNode* root, int val) {
        if (root == nullptr) {
            return NULL;
        }
        if (root->val == val) { /* This is the correct node */
            return root;
        }
        
        TreeNode *left = searchBST(root->left, val);
        if (left != NULL) { /* Left side has a solution */
            return left;
        }
        TreeNode *right = searchBST(root->right, val);
        return right; /* Return whether or not there is solution */
    }
};
```

#### Language used for code

C++

#### Expected behavior

The expected answer should show the correct answer, which is the sole leaf node.

#### Screenshots

![LeetCodeBugReport](https://user-images.githubusercontent.com/44012709/101688841-753a0300-3a21-11eb-91b5-3b897a706fa4.PNG)

#### Additional context

The custom testcase used is:
```
[4,6,7,1,3,2]
2
```

**Comment by lc-kay** [comment]
@salorent Please provide the code in [Playground](https://leetcode.com/playground/new/empty). I am receiving Compile Error when I submit your case.

**Comment by cgsgak1** [comment]
The header of the issue is not correct. This is the problem #700, not #783. Also the testcase is not valid because it doesn't represent BST.
