### ISSUE TITLE
Missing Test Case - 1493. Longest Subarray of 1's After Deleting One Element

### ISSUE THREAD

**Issue by momcilol** [LeetCode-Feedback/LeetCode-Feedback#16287]
#### Your LeetCode username
momcilol

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Test example is 
nums = [1,1,1]
Obviously, the answer is 3 but it says that 2 is expected.

#### Code you used for Submit/Run operation
```
class Solution:
    def longestSubarray(self, nums: List[int]) -> int:
        zero = -1
        max_size = 0
        
        size = 0
        for i in range(len(nums)):
            if nums[i] == 0:
                size = i - zero - 1
                zero = i 
            else:
                size += 1
            
            if size > max_size:
                max_size = size


        return  max_size
```

#### Language used for code
Python

#### Expected behavior
I expect the answer to be 3, but the answer is 2.

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/89138317/1cf77ff2-e250-4fec-b44a-adbf790c659e)

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team

**Comment by momcilol** [comment]
Oh, I see. I automatically assumed that we were talking about zero that should be deleted. 

Thank you for your help.
