### ISSUE TITLE
Missing Test Case - 13. Roman to Integer

### ISSUE THREAD

**Issue by poison01022** [LeetCode-Feedback/LeetCode-Feedback#16286]
#### Your LeetCode username
predator01022

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ 1] Missing Test Cases 

#### Description of the bug
The code for converting Roman numerals to integers is expected to produce correct results for various test cases. However, there might be an issue with how the code handles certain Roman numerals, which could lead to incorrect conversions.

#### Code you used for Submit/Run operation

    int romanToInt(char * s){                     // Roman Numeral to Integer Conversion
    int result = 0; // Initialize the result to 0
    int prevValue = 0; // Initialize the previous value to 0
    
    // Loop through the Roman numeral string
    for (int i = 0; s[i] != '\0'; i++) {
        int value = 0; // Initialize the current value to 0
        
        // Use a switch statement to determine the value of the current Roman numeral character
        switch (s[i]) {
            case 'I':
                value = 1;
                break;
            case 'V':
                value = 5;
                break;
            case 'X':
                value = 10;
                break;
            case 'L':
                value = 50;
                break;
            case 'C':
                value = 100;
                break;
            case 'D':
                value = 500;
                break;
            case 'M':
                value = 1000;
                break;
        }
        
        // Add the current value to the result
        result += value;
        
        // Check if the current value is greater than the previous value
        if (value > prevValue) {
            // If so, subtract twice the previous value to account for subtraction (e.g., IV, IX)
            result -= 2 * prevValue;
        }
        
        // Update the previous value for the next iteration
        prevValue = value;
    }
    
    // Return the final result
    return result;
    }  

#### Language used for code
C

#### Expected behavior
The romanToInt function should correctly convert Roman numerals to integers for a variety of test cases, including the ones provided earlier. The expected output for those test cases should match the actual results produced by the code.

#### Screenshots
ADDITIONAL TEST CASE:

#include <stdio.h>

     int main() {
    // Additional test case 5: CDXLIV = 444
    char roman5[] = "CDXLIV";
    printf("CDXLIV = %d\n", romanToInt(roman5)); // Expected output: 444

    return 0;
      }

#### Additional context
In this test case, we're using the Roman numeral "CDXLIV", which represents the number 444. This case tests the function's ability to handle larger Roman numerals.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Please ask your question in the discussion forum.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
