### ISSUE TITLE
Missing Test Case - 1011. Capacity To Ship Packages Within D Days

### ISSUE THREAD

**Issue by viikash10** [LeetCode-Feedback/LeetCode-Feedback#16289]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [YES] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int helper(vector<int>& weights,int cap)
    {
        long long  cnt = 0 ;
        int day = 1 ;
        int n = weights.size() ;
        for(int i = 0 ; i < n ; i++)
        {
              if(cnt + weights[i] <= cap)
              {
                  cnt += weights[i] ;
              }
              else
              {
                  day++ ;
                  cnt = weights[i] ;
              }
        }
        return day ;
    }
    int shipWithinDays(vector<int>& weights, int days) {
        int n = weights.size() ;
        int low = *max_element(weights.begin(),weights.end()) ;
        int high = accumulate(weights.begin(),weights.end(),0) ;
        for(int cap = low ; cap <= high ; cap++)
        {
            if(helper(weights,cap)==days)
            {
                return cap ;
            }
        }
        return low ;
    }
};
```

#### Expected behavior

**When the size of the weights vector is less than the number of days, it should not be possible to ship the packages for the given days. Therefore, the function is expected to return -1 or other indicator of impossibility in such cases.**

#### Additional context

**So we need to have one test case as weights = [] , days = 5 then answer should be impossible or -1 (in relevance to Allocate Minimum Number of Pages question)**

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
