### ISSUE TITLE
1307. Verbal Arithmetic Puzzle: Wrong prompt information when inputting invalid testcases

### ISSUE THREAD

**Issue by caoxingdong** [LeetCode-Feedback/LeetCode-Feedback#1629]
#### Your LeetCode username

ddoudle

#### Category of the bug
- [ ] Question

#### Description of the bug

The constrains says that 2 <= words.length <= 5, but when I input a case with words.length = 1, the prompt information told me that 1 <= words.length <= 5, which should be 2 <= words.length <= 5

#### Screenshots

![image](https://user-images.githubusercontent.com/32877011/101704327-ba6e2d00-3a41-11eb-809e-bf5a3ff5f85b.png)

![image](https://user-images.githubusercontent.com/32877011/101704361-cf4ac080-3a41-11eb-82d1-56eb386f70a3.png)

**Comment by lc-kay** [comment]
Hi @caoxingdong 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @caoxingdong 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
