### ISSUE TITLE
Missing Test Case - 373. Find K Pairs with Smallest Sums

### ISSUE THREAD

**Issue by tagrn** [LeetCode-Feedback/LeetCode-Feedback#16295]
#### Your LeetCode username
Taewan-Gu

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

If we didn't use heap, we can use double loop using nums1[:k], nums2[:k]. But this idea is speed low, so return time-out. But the code which is modified above idea get success. I think this problem don't have the edge case about this idea.

#### Code you used for Submit/Run operation

```python3
class Solution:
    def kSmallestPairs(self, nums1: List[int], nums2: List[int], k: int) -> List[List[int]]:
        i, j = 0, 0
        while k > (i+1) * (j+1):
            if i+1 >= len(nums1):
                j += 1
            elif j+1 >= len(nums2):
                i += 1
            elif nums1[i+1] < nums2[j+1]:
                i += 1
            else:
                j += 1
        nums1 = nums1[:i+100]
        nums2 = nums2[:j+100]

        ans = []
        for i in nums1:
            for j in nums2:
                ans.append([i,j])        
        ans.sort(key=lambda x: sum(x))

        return ans[:k]
```

#### Language used for code
python3

#### Expected behavior

nums1 = [i for i in range(1, 10001)]
nums2 = [i for i in range(-10000, 0)]
k = 10000

The testcase get incorrect answer when using above code.

And one more,

nums1 = [1] * 10000
nums2 = [-1] * 10000
k = 10000

The testcase get timeout response.

#### Screenshots

<img width="1430" alt="Screenshot 2023-09-09 at 5 12 37 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/68409255/43f80a1f-00a3-4af6-8078-cfb6438eb9e1">
<img width="1433" alt="Screenshot 2023-09-09 at 5 12 57 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/68409255/f3bb072d-2a2d-4ed9-9696-07464138fe4e">

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
