### ISSUE TITLE
347. Top K Frequent Elements

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#163]
**What kind of the bug**
- [x] problem
- [x] solution
- [ ] language

**Describe the bug**
Given a non-empty array of integers, return the k most frequent elements.

This is the description of the problem. Neither does it mention that there are no equal frequency elements nor it does not mention what to do in case of equal frequency. It can be extrapolated from the problem that any elements can be returned in the case of equal frequency but in my opinion it should be explicit.

**What language is your code written in**
Python

**The code you submit/run**
```
class Solution(object):
    def topKFrequent(self, a, k):
        from heapq import *
        c=collections.Counter(a)
        h=[]
        for i in c:
            heappush(h,(c[i],i))
            if len(h)>k:
                heappop(h)
        return [i[1] for i in h]
```

and 

```
class Solution(object):
    def topKFrequent(self, a, k):
        c=collections.Counter(a)
        n=len(a)
        z=[[] for _ in xrange(n+1)]
        for i in c:
            z[c[i]].append(i)
        q=[]
        for i in xrange(n,0,-1):
            q.extend(z[i][:min(len(z[i]),k-len(q))])
        return q
```

**Expected behavior**
Input:
[4,4,3,2,1]
2

Expected output:
[4,2]

First code output:
[3,4]

Verdict:
Wrong Answer

Second code output:
[4,1]

Verdict:
Wrong Answer

Both solutions get accepted but show wrong verdict when run using this test case. I think the judge only gives correct verdict if it has the same exact elements as the one given by solution the judge uses. The description and verdict make the problem ambiguous.

**Comment by CooperCooperCooper** [comment]
Hi @leet212,
Thank you for reaching out to us! I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @leet212,
Thank you for your feedback! We've used it to update this problem. Please reach out to our main support channel support@leetcode.com with your LeetCode username, your Github user info and this issue as verification to claim your reward for this valid content issue contribution.

**Comment by leet212** [comment]
Thank you for the update @CooperCooperCooper . I have the submitted it to the technical support channel.
