### ISSUE TITLE
377. Combination Sum IV - Crash using Swift

### ISSUE THREAD

**Issue by barabashd** [LeetCode-Feedback/LeetCode-Feedback#16312]
#### Your LeetCode username
[barabash](https://leetcode.com/barabash/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
There's a bug using Swift language leading to the crash.

I see at least two ways to reproduce it.
1. Replace 'dp[0] = 1' with 'dp[0] = 1; print(dp)'
2. Replace 'var dp: [Int] = .init(repeating: 0, count: target+1)' with 'var dp: [Int] = [1] + .init(repeating: 0, count: target)'

#### Code you used for Submit/Run operation

```
// Combination Sum IV
func combinationSum4(_ nums: [Int], _ target: Int, _ firstTime: Bool = true) -> Int {
    var dp: [Int] = .init(repeating: 0, count: target+1) // var dp: [Int] = [1] + .init(repeating: 0, count: target) // crash 1
    dp[0] = 1 // print(dp) // crash 2
    for i in 1...target {
        for n in nums where i >= n {
            guard dp[i-n] <= Int32.max else { break }
            dp[i] += dp[i-n]
        }
    }
    return dp[target]
}
```

#### Language used for code
Swift

#### Expected behavior
No crashes

#### Screenshots
<img width="1210" alt="Screenshot 2023-09-09 at 10 16 47" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/24472528/3ef3fcc9-b186-48a0-aef2-6d2a46adbb7c">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by barabashd** [comment]
> Thank you for your time. 
> 
> 
> 
> We've used your feedback to check the problem. 
> 
> 
> 
> The team decided to reject this feedback after the evaluation. 
> 
> 
> 
> If you have any other questions or feedback, please don't hesitate to let us know! 
> 
> 
> 
> We appreciate your support!

Thank you for the answer. But why did you close this issue if this bug still exists? @LC-Pam
