### ISSUE TITLE
1190. Reverse Substrings Between Each Pair of Parentheses : Missing Case

### ISSUE THREAD

**Issue by jrk1992** [LeetCode-Feedback/LeetCode-Feedback#1631]
#### Your LeetCode username

JK991992

#### Category of the bug
- [ ] Solution

#### Description of the bug

Missing case : "(abc)"

#### Code you used for Submit/Run operation

```
// 1190. Reverse Substrings Between Each Pair of Parentheses
class Solution {
    public String reverseParentheses(String s) {
        if (s == null || s.length() < 6)
          return s;
        int n = s.length();
        Stack<Integer> openIndex = new Stack<>();
        int[] pair = new int[n];
        for (int i = 0; i < s.length(); i++) {
          if (s.charAt(i) == '(') {
            openIndex.push(i);
          }
          if (s.charAt(i) == ')') {
            int open  = openIndex.pop();
            pair[i] = open;
            pair[open] = i;
          }
        }
        StringBuilder sb = new StringBuilder();
        for (int i = 0, d  = 1; i < n; i += d) {
          if (s.charAt(i) == '(' || s.charAt(i) == ')') {
            i = pair[i];
            d = -d;
          } else {
            sb.append(s.charAt(i));
          }
        }
        return sb.toString();
    }
}
```

#### Language used for code

Java

#### Expected behavior

On Submitting the above code the solution is accepted (1st screenshot), whereas it should be rejected since the code produces an incorrect answer (2nd screenshot)

#### Screenshots

<img width="532" alt="Screen Shot 2020-12-10 at 1 08 33 AM" src="https://user-images.githubusercontent.com/11951732/101750718-3f7a3600-3a84-11eb-80ea-7a89b5e8e8ea.png">
<img width="603" alt="Screen Shot 2020-12-10 at 1 04 54 AM" src="https://user-images.githubusercontent.com/11951732/101750750-49039e00-3a84-11eb-8243-e2d5d3cc0fb2.png">

**Comment by lc-kay** [comment]
Hi @jrk1992 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @jrk1992 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
