### ISSUE TITLE
Missing Test Case - 2851. String Transformation

### ISSUE THREAD

**Issue by yumkam** [LeetCode-Feedback/LeetCode-Feedback#16329]
#### Your LeetCode username

yumkam

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Code  was accepted, but fails test case below:
```
"aluaacccaefjjnajiaaaoaadrcvsaadaabcaaafaaaaacaatkiaaqaaaaaal"
"aluaacccaefjjnajiaaaoaadrcvsaadaabcaaafaaaaacaatkiaaqaaaaaal"
5
```

#### Code you used for Submit/Run operation

```python
# code not mine
class Solution:
    def numberOfWays(self, s: str, t: str, k: int) -> int:
        MOD = 10**9+7
        
        h = 0
        for c in s:
            h = (26 * h + (ord(c)-97)) % MOD
            
        th = 0
        for c in t:
            th = (26 * th + (ord(c)-97)) % MOD
            
        x = 0
        df = h == th
        if df:
            x += 1
        n = len(s)
        
        q = pow(26, n-1, MOD)
        
        for i in range(1, n):
            h = ((h - q * (ord(s[i-1])-97)) * 26 + (ord(s[(i+n-1)%n])-97))%MOD
            if h == th:
                x += 1
        
        ret = ((pow(n-1, k, MOD) - pow(-1, k, MOD)) * pow(n, -1, MOD) * x % MOD)
        
        if df:
            ret += (-1 if k%2 else 1)
            ret %= MOD
        return ret
```

#### Language used for code
python3

#### Additional context

Rolling hash without collision check is recipe to disaster.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
