### ISSUE TITLE
Missing Test Case/ Incorrect official solution - 585. Investments in 2016

### ISSUE THREAD

**Issue by benjaminsihi** [LeetCode-Feedback/LeetCode-Feedback#16321]
#### Your LeetCode username

visionary97

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The question asks us to compute the sum of tiv_2016 for all pid where
- have the same tiv_2015 value as one or more other policyholders, and
- are not located in the same city as any other policyholder (i.e., the (lat, lon) attribute pairs must be unique).

When two pid have the same lat and lon pair. They are also counted toward the result. 

#### Code you used for Submit/Run operation

```
# it's copied from the official solution 
SELECT
    ROUND(SUM(insurance.TIV_2016),2) AS TIV_2016
FROM
    insurance
WHERE
    insurance.TIV_2015 IN
    (
      SELECT
        TIV_2015
      FROM
        insurance
      GROUP BY TIV_2015
      HAVING COUNT(*) > 1
    )
    AND CONCAT(LAT, LON) IN
    (
      SELECT
        CONCAT(LAT, LON)
      FROM
        insurance
      GROUP BY LAT , LON
      HAVING COUNT(*) = 1
    )
;
```
#### Language used for code

sql

#### Expected behavior

| pid | tiv_2015 | tiv_2016 | lat | lon |
| --- | -------- | -------- | --- | --- |
| 1   | 10         | 30         | 13 | 3    |
| 2   | 10         | 30         | 13 | 3    |
| 3   | 10         | 15         | 1   | 33  |

See the test case above. 
id_1 and id_2 have the same lat/ lon pair. based on the question description, both of them should be excluded from the tiv_2016 sum. But the expected answer shows 75, where both id_1 and id_2 are counted. 
The official solution uses CONCAT(lat, lon) to concatenate two strings. (13, 3) and (1, 33) come out as "133". 

#### Screenshots

<img width="1259" alt="leetcode-missing-test-case" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/33979361/bc5d20bf-ac17-4fac-bcee-763181a4aa23">

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Please ask your question in the discussion forum.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
