### ISSUE TITLE
Small mistake in question description - 941. Valid Mountain Array

### ISSUE THREAD

**Issue by BhallalDev22** [LeetCode-Feedback/LeetCode-Feedback#1632]
#### Category of the bug
- [*] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

 Theres a small mistake in question discription, the name of the array is "arr" but in one condition of the question it was written as "A". Condition : arr[0] < arr[1] < ... < arr[i - 1] < **A[i]**, in place of "A[i]", it should be "arr[i]"

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by iphyer** [comment]
I agree with @BhallalDev22 this is a typo, it should be `arr[i]` instead of `A[i]`

**Comment by lc-kay** [comment]
Hi @BhallalDev22 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @BhallalDev22 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!

**Comment by BhallalDev22** [comment]
Thank you 🙂

**Comment by BhallalDev22** [comment]
Hello. I've one query, will i get 100 leetcode coins under "File Content Issue to Feedback Repo" as shown on the website. I'm trying to collect 6800 leetcode coins since very long, if I'll get these 100 leetcode coins it will be a great help.
Thankyou.

**Comment by lc-kay** [comment]
@BhallalDev22 I apologize, but this report did not qualify for rewards. However, we still thank you for your efforts.
