### ISSUE TITLE
Missing Test Case - 978. Valid Mountain Array

### ISSUE THREAD

**Issue by lifeisNPhard** [LeetCode-Feedback/LeetCode-Feedback#1633]
#### Your LeetCode username

orthogonally17

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

My code gets accepted, but it will work incorrectly with the following test case. 
[6, 7, 7, 8, 6]

#### Code you used for Submit/Run operation

```
// Valid Mountain Array
class Solution {
public:
    bool validMountainArray(vector<int>& arr) {
        bool peak = false;
        int size = arr.size();
        if (size < 3 || arr[0] >= arr[1] || arr[size - 1] >= arr[size - 2])
            return false;
        for (int i = 1, size = arr.size(); i < size; i++)
        {
            if (!peak)
            {
                if (arr[i] < arr[i - 1]) peak = true;
            }
            else
            {
                if (arr[i] >= arr[i - 1]) return false;
            }
                
        }
        return true;
    }
};
```

#### Language used for code

C++

#### Expected behavior

My submission should get "Wrong Anser" instead of "Accepted".

#### Additional context

Consider including the testcase please. Thanks!

**Comment by lc-kay** [comment]
@lifeisNPhard Can you please provide your code in [Playground](https://leetcode.com/playground/new/empty)? I am getting Compile Error when I submit your code. Thank you!

**Comment by lifeisNPhard** [comment]
I am sorry. I mistype the index of the question. It should be #941 instead of #978. I think it is the reason you got Compile Error. Please inform me if you have any question about my code. Thanks!

**Comment by lc-kay** [comment]
Hi @lifeisNPhard 
Thank you for the clarification. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @lifeisNPhard 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
