### ISSUE TITLE
Passes with wrong solution | 1282. Group the People Given the Group Size They Belong To

### ISSUE THREAD

**Issue by adityaMundhara** [LeetCode-Feedback/LeetCode-Feedback#16349]
#### Category of the bug
- [x ] Question
- [x ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
There is a validation issue with the test cases , where incorrect solution is flaged as passed. 

#### Code you used for Submit/Run operation
```
class Solution {
public:
    vector<vector<int>> groupThePeople(vector<int>& groupSizes) {
        vector<vector<int>> ans;
        unordered_map<int,vector<int>> pep;
        
        for(int i=0;i<groupSizes.size();i++)
        {
            pep[groupSizes[i]].push_back(i);
        }
        
        vector<int> val;

        for(auto& [size,people]:pep)
        {
            int que = people.size()/size;
            int k=0;
            while(k<que)
            {
            for(int i=0;i<size;i++)
            {
                val.push_back(people[k+i]);
            }
            k++;
            ans.push_back(val);
             val={};
            }
        }
        return ans;
    }
};
```
#### Language used for code
 C++ 

#### Expected behavior
This should fail the solution as the answer can't have same people in different groups.

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/20663519/0a16c47a-3d38-4757-99dc-b7c16bb99a5f)

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/20663519/e1318944-a8b1-47fe-a320-cd35a9d12236)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've used your feedback to update the problem.

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback.

Please provide us with your LCCN or LCUS username.

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!

**Comment by adityaMundhara** [comment]
Hi,
Thanks for your response.
Here's my leetcode US Id :
zen_sama
