### ISSUE TITLE
Solution- 1282. Group the People Given the Group Size They Belong To

### ISSUE THREAD

**Issue by Jeetaksh** [LeetCode-Feedback/LeetCode-Feedback#16340]
#### Your LeetCode username

Jeetaksh

#### Category of the bug
- Solution

#### Description of the bug
According to question, we have to return a list of groups such that each person i is in a group of size groupSizes[i].

I wrote a solution in which the same people are assigned the group again and again and it gets completely accepted. 
For example:-
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/92541718/53a732db-cd6e-4dfa-a047-44b8526de638)
The output should contain all the people as per their groups, but my code mentions the same people all the time and ignores the other people.

This is a voilation to "each person i is in a group of size groupSizes[i]."

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<vector<int>> groupThePeople(vector<int>& groupSizes) {
        int n=groupSizes.size();
        vector<vector<int>> mp(n+1,vector<int>());
        for(int i=0;i<n;i++){
            mp[groupSizes[i]].push_back(i);
        }
        vector<vector<int>> ans;

        for(int i=0;i<mp.size();i++){
            if(mp[i].size()){
                int p=mp[i].size()/i;
                for(int k=p-1;k>=0;k--){
                    vector<int> temp;
                    for(int j=i-1;j>=0;j--){
                        temp.push_back(mp[i][j]);

                    }
                    ans.push_back(temp);
                }
            }
        }


        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior
The code should show it as a wrong answer.

#### Screenshots
Added above

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
