### ISSUE TITLE
Missing Test Case - 1282. Group the People Given the Group Size They Belong To

### ISSUE THREAD

**Issue by just-small-potato** [LeetCode-Feedback/LeetCode-Feedback#16348]
#### Your LeetCode username

icelam

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

In the problem statement, it states `Each person should appear in exactly one group, and every person must be in a group. If there are multiple answers, return any of them. It is guaranteed that there will be at least one valid solution for the given input.`.

However, a solution which same person appears in more than one group, and some person appears in no group still got accepted.

<img width="776" alt="Screenshot 2023-09-11 at 7 46 30 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/68165945/4441e687-5ce7-472c-a4e8-600fbfae6c34">

##### Test case
```
Your input
[3,3,3,3,3,1,3]
Output
[[5],[0,1,2],[1,2,3]]
Expected
[[5],[0,1,2],[3,4,6]]
```

#### Code you used for Submit/Run operation
A brief description, this is a wrong code, where the correct logic is supposed to be `group.add(peopleWithSameGroupId.get(i* size + j));`. However this got accepted.

``` java 
class Solution {
  public List<List<Integer>> groupThePeople(int[] groupSizes) {
    int n = groupSizes.length;
    HashMap<Integer, List<Integer>> map = new HashMap<>();
    
    for (int i = 0; i < n; i++) {
      map.computeIfAbsent(groupSizes[i], value -> new ArrayList<Integer>()).add(i);
    }
    
    List<List<Integer>> result = new ArrayList<>();
    
    for (int size: map.keySet()) {
      List<Integer> peopleWithSameGroupId = map.get(size);
      int numberOfPeople = peopleWithSameGroupId.size();
      
      for (int i = 0; i < numberOfPeople / size; i++) {
        List<Integer> group = new ArrayList<>();
        
        for (int j = 0; j < size; j++) {
          group.add(peopleWithSameGroupId.get(i + j));
        }
        
        result.add(group);
      }
    }
    
    return result;
  }
}
```

#### Language used for code
Java

#### Expected behavior

Output `[[5],[0,1,2],[1,2,3]]` should not be accepted as it does not satisfies the requirement. 
Reason: Person 1 and 2 appears on 2 group and person 4 and 6 does not belongs to any group.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
