### ISSUE TITLE
113. Path Sum II exp1's input is incorrect

### ISSUE THREAD

**Issue by skyLiyx** [LeetCode-Feedback/LeetCode-Feedback#16350]
#### Your LeetCode username

skyli

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Input of example 1 is incorrect to match the graphic.  

#### Code you used for Submit/Run operation

```
// Path Sum II
class Solution {
    public List<List<Integer>> pathSum(TreeNode root, int targetSum) {
        List<List<Integer>> res = new ArrayList<>();
        dfs(root, targetSum, new ArrayList<>(), res);
        return res;
    }

    private void dfs(TreeNode root, int targetSum, List<Integer> list, List<List<Integer>> res) {
        if (root == null) {
            return;
        }
        targetSum -= root.val;
        list.add(root.val);
        if (root.left == null && root.right == null && targetSum == 0) {
            res.add(new ArrayList<>(list));
        }
        dfs(root.left, targetSum, list, res);
        dfs(root.right, targetSum, list, res);
        list.remove(list.size() - 1);
    }
}
```

#### Language used for code

Java

#### Expected behavior

The correct input is `root = [5,4,8,11,null,13,4,7,2,null,null,null,null,5,1]`.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/43489674/c3331de5-c2ce-42ea-8a89-7a35d3aa2d84)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by skyLiyx** [comment]
I've added what you mentioned to this comment. @LC-Pam

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
