### ISSUE TITLE
Wrong Slides Editorial Solution Tab - 1282. Group the People Given the Group Size They Belong To

### ISSUE THREAD

**Issue by shubhcodegate** [LeetCode-Feedback/LeetCode-Feedback#16355]
#### Your LeetCode username
kmr_shubh

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The slides in the "Editorial" Solution tab is for some other question.

#### Code you used for Submit/Run operation
No code. The bug is in "Editorial Tab"

#### Expected behavior
Slide show corresponding to the correct question must be shown. or The wrong slide should just be removed

#### Screenshots

<img width="843" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/45122479/49c58217-7186-4692-a1ca-4bb5ac535520">

#### Additional context
Link to the question for your reference : https://leetcode.com/problems/group-the-people-given-the-group-size-they-belong-to/

**Comment by shubhcodegate** [comment]
Please do add those sweet **LeetCoins** if this issue was helpful

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
