### ISSUE TITLE
238. Product of Array Except Self - Typo in Queston

### ISSUE THREAD

**Issue by agrawalishaan** [LeetCode-Feedback/LeetCode-Feedback#16359]
#### Your LeetCode username
agrawalishaan

#### Category of the bug
- [ X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the followup, the code formatting for `O(1)` extends one space too far.
![Screenshot 2023-09-11 at 3 42 27 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/113543798/27635d49-2211-483f-8126-35f4d6c81c5b)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
