### ISSUE TITLE
Missing Test Case - 1661. Average Time of Process per Machine

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1635]
#### Your LeetCode username

[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

**Below test case is missing-**

{"headers":{"Activity":["machine_id","process_id","activity_type","timestamp"]},"rows":{"Activity":[[0,1,"end",68.229]]}}

![image](https://user-images.githubusercontent.com/71989691/101890477-be778780-3bc6-11eb-98d5-5195d1991697.png)

#### Code you used for Submit/Run operation

```
# Write your MySQL query statement below

SELECT TMP.MACHINE_ID as machine_id, ROUND(SUM(TMP.TIME_DIFF)/COUNT(TMP.TIME_DIFF),3) AS processing_time FROM
(
SELECT A.MACHINE_ID,

ROUND(SUM(CASE WHEN A.ACTIVITY_TYPE = 'END' THEN A.TIMESTAMP ELSE 0 END ),3)
-
ROUND(SUM(CASE WHEN A.ACTIVITY_TYPE = 'START' THEN A.TIMESTAMP ELSE 0 END),3) AS 'TIME_DIFF'


FROM ACTIVITY AS A
GROUP BY A.MACHINE_ID, A.PROCESS_ID 

) AS TMP
GROUP BY TMP.MACHINE_ID
```

#### Language used for code

MySQL

#### Expected behavior

Missing Test Case-
Please add the below test case-
{"headers":{"Activity":["machine_id","process_id","activity_type","timestamp"]},"rows":{"Activity":[[0,1,"end",68.229]]}}

#### Additional context

Problem- https://leetcode.com/problems/average-time-of-process-per-machine/

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for your time. The team reviewed your report and noticed the test case is invalid. The 'start' timestamp will always be before the 'end' timestamp for every (machine_id, process_id) pair.
