### ISSUE TITLE
缺少测试用例 Missing Test case 1462. Course Schedule IV

### ISSUE THREAD

**Issue by yiyin93** [LeetCode-Feedback/LeetCode-Feedback#16367]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名
[Cranky NewtonFMF](https://leetcode.cn/u/cranky-newtonfmf/)

**Your LeetCode username**
[Cranky NewtonFMF](https://leetcode.cn/u/cranky-newtonfmf/)

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**Category of the bug**
- [x] Missing Test Cases

**描述**
描述你遇到的 bug
https://leetcode.cn/problems/course-schedule-iv
缺少测试用例numCourses = 6，prerequisites = [[0,5],[1,2],[1,4],[2,3],[5,1]]，queries = [[0,3]]。

**Description of the bug**
My solution got 'Accepted' for all suggested tests, however it does not work for this test case: numCourses = 6，prerequisites = [[0,5],[1,2],[1,4],[2,3],[5,1]]，queries = [[0,3]]

**你使用的语言**
**Language used for code**
Java

**你提交或者运行的代码**
**Code you used for Submit/Run operation**
```
class Solution {
    public List<Boolean> checkIfPrerequisite(int numCourses, int[][] prerequisites, int[][] queries) {
        Map<Integer,Set<Integer>> map = new HashMap<>();
        for (int[] f : prerequisites){
            map.computeIfAbsent(f[0],t -> new HashSet<>()).add(f[1]);
            for (int num : map.keySet()){
                if (map.get(num).contains(f[0])){
                    map.get(num).add(f[1]);
                }
                if (num == f[1]){
                    map.get(f[0]).addAll(map.get(num));
                }
            }
        }
        List<Boolean> ans = new ArrayList<>();
        for (int[] f : queries){
            ans.add(map.getOrDefault(f[0],new HashSet<>()).contains(f[1]));
        }
        return ans;
    }

}
```

**期望行为**
https://leetcode.com/problems/course-schedule-iv/submissions/1047827015/
应该不能通过这个测试用例 numCourses = 6，prerequisites = [[0,5],[1,2],[1,4],[2,3],[5,1]]，queries = [[0,3]]。但是目前能够ac，希望能把这个测试加上。

**Expected behavior**
https://leetcode.com/problems/course-schedule-iv/submissions/1047827015/
It should not pass the test case

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
