### ISSUE TITLE
Snapshot Array - Typo in editorial

### ISSUE THREAD

**Issue by imvtsl** [LeetCode-Feedback/LeetCode-Feedback#16362]
#### Your LeetCode username
imvtsl

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Typo in variable snap_index in algorithm for binary approach solution. PFA screenshot.

#### Screenshots

<img width="442" alt="Screenshot 2023-09-11 at 8 05 27 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/36672090/020dc45a-834d-408a-b73f-cfc03ae72379">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
