### ISSUE TITLE
Missing Test Case - 152. Maximum Product Subarray

### ISSUE THREAD

**Issue by Joylintp** [LeetCode-Feedback/LeetCode-Feedback#16360]
#### Your LeetCode username

[joylintp](https://leetcode.com/joylintp/)

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

`[0, 10, 10, 10, 10, 10, 10, 10, 10, 10, -10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 0]`

This test case meets all the constraints but the judge doesn't provide any expected output when testing your code.
[My accepted solution](https://leetcode.com/problems/maximum-product-subarray/submissions/1046943794/) will also get a Runtime Error with this test case.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int maxProduct(vector<int>& nums) {
        return 0;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The correct answer should be `1000000000`, but the judge doesn't produce any output.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/30295932/72b2b696-ab76-4c3f-bad8-dce9d2921ad3)

#### Additional context

The current contraints will make this problem hard to solve as the product of a subarray may not fit in the a 32-bit or even a 64-bit integer such as `long long` in C++. (and maybe that's the reason the judge fails to produce the correct output for the test case above)
Perhaps another contraint is needed such as "The product of any subarray of `nums` is guaranteed to fit in a 64-bit integer." or "The minimum product subarray of `nums` is also guaranteed to fit in a 32-bit integer." so the issue can be solved.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
