### ISSUE TITLE
Missing Test Case - 80. Remove Duplicates from Sorted Array II

### ISSUE THREAD

**Issue by MarkAddison** [LeetCode-Feedback/LeetCode-Feedback#1636]
#### Your LeetCode username

TheRuminator 

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

When empty array is passed in as a parameter the current proposed solution return size=1, which is clear incorrect.

#### Code you used for Submit/Run operation

```
// The Official Solution currently appearing on LeetCode for December competition Week 2: December 8th - December 14th
// December 11th
public class Solution {

    public int removeDuplicatesNope(int[] nums) {
        int j = 1, count = 1;
        for (int i = 1; i < nums.length; i++) {
            if (nums[i] == nums[i - 1]) {
                count++;
            } else {
                count = 1;
            }
            if (count <= 2) {
                nums[j++] = nums[i];
            }
        }
        return j;
    }
}

// Remove Duplicates from Sorted Array II
class RemoveDuplicatesFromSortedArray2Test {

    @Test
    void removeDuplicatesEmptyList() {
        Solution underTest = new Solution();
        assertThat(underTest.removeDuplicates(new int[]{})).isEqualTo(0);
    }

}
```

#### Language used for code

Java

#### Expected behavior

return value should be 0 - actual is 1

#### Additional context

Problem Constraints as per description:
* **0 <=** nums.length <= 3 * 104
* -104 <= nums[i] <= 104
* nums is sorted in ascending order.

**Comment by lc-kay** [comment]
Hi @MarkAddison 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@MarkAddison The official solution already returns 0 when nums.length == 0. Thank you for your time.

**Comment by MarkAddison** [comment]
No t actually return 1

**Comment by lc-kay** [comment]
@MarkAddison To better understand the issue, can you please provide the exact test case and a screenshot of the testing result using LC editor.  https://leetcode.com/problems/remove-duplicates-from-sorted-array-ii/

**Comment by MarkAddison** [comment]
OK, the test cases passes, but the integer value which is returned is 1 as opposed to zero.
The Problem states "Your function should return length = xxx"
The fact that the runner is assessing the array is not the question here.

Can I suggest one of your technical people tries the test
    @Test
    void removeDuplicates() {
        Solution underTest = new Solution();
        assertThat(underTest.removeDuplicates(new int[]{})).isEqualTo(0);
    }

against the code described as the accepted answer

class Solution {
    public int removeDuplicates(int[] nums) {    
        //
        // Initialize the counter and the second pointer.
        //
        int j = 1, count = 1;
        
        //
        // Start from the second element of the array and process
        // elements one by one.
        //
        for (int i = 1; i < nums.length; i++) {
            
            //
            // If the current element is a duplicate, increment the count.
            //
            if (nums[i] == nums[i - 1]) {
                
                count++;
                
            } else {
                
                //
                // Reset the count since we encountered a different elemen        
                // than the previous one.
                //
                count = 1;
            }
            
            //
            // For a count <= 2, we copy the element over thus
            // overwriting the element at index "j" in the array
            //
            if (count <= 2) {
                nums[j++] = nums[i];
            }
        }
        return j;
    }
}

**Comment by lc-kay** [comment]
Hi @MarkAddison 
The team reviewed your report and noticed the problem was the constraint. After updating that, the issue has resolved. Thank you for your time!
