### ISSUE TITLE
Missing Test Case - 543. Diameter of Binary Tree

### ISSUE THREAD

**Issue by Miracle365** [LeetCode-Feedback/LeetCode-Feedback#16368]
#### Your LeetCode username
KirAP

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

My solution got 'Accepted' for all suggested tests, however it does not work when the binary tree has more than one node before the beginning ('root') of the branch with the biggest diameter.

#### Code you used for Submit/Run operation

```
// Diameter of binary tree
class Solution {
    int maxdiam = 0;

    public int search(TreeNode root, int ch) {
        while (((root.left != null) && (root.right == null)) || ((root.left == null) && (root.right != null)))       {
            if (root.left != null) root = root.left;
            else root = root.right;
            ch++;
        }
        if (root.left == null) return ch; //list

        int lmax = search(root.left, 1);
        int rmax = search(root.right, 1);
        int diam;
        if (ch > 0) diam = lmax + rmax + ch - 1;
        else diam = lmax + rmax;
        if (diam > maxdiam) maxdiam = diam;
        if (lmax > rmax) return lmax + ch;
        else return rmax + ch;
    }

    public int diameterOfBinaryTree(TreeNode root) {
        int k = search(root, 0);
        if (maxdiam == 0) return k;
        return maxdiam;
    }
}
```

#### Language used for code
Java

#### Expected behavior

Well, i used a testcase: root =
[1, null, 2, null, 3, 4, 5, 6, null, null, 7, 8, null, 9, null, 10, null, 11, null, 12, null, 13, null]
and got Wrong answer. As expected. But in the proposed test cases this one was not given, and my solution got Accepted.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by MEMBERSOFHONOR** [comment]
Cool bro

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
