### ISSUE TITLE
Missing Test Case - 509. Fibonacci Number

### ISSUE THREAD

**Issue by porwalu** [LeetCode-Feedback/LeetCode-Feedback#1638]
0 ≤ N ≤ 30. criteria is not checked even though it is mentioned in the note. Is this a missed test case?

**Comment by lc-kay** [comment]
Hi @porwalu 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @porwalu 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
