### ISSUE TITLE
Missing Test Case - 135. Candy

### ISSUE THREAD

**Issue by ardhrubo** [LeetCode-Feedback/LeetCode-Feedback#16390]
#### Your LeetCode username
ardhrubo

#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [x] Missing Test Cases 

#### Description of the bug

``` 
/**
 * @param {number[]} ratings
 * @return {number}
 */
var candy = function(ratings) {
    const n = ratings.length;
    const candies = new Array(n).fill(1);

    for (let i=0; i<n; i++) {
        if (ratings[i]>ratings[i-1]) {
            candies[i] = candies [i-1] +1;
        } 
    }

    for (let i = n; i>=0; i--) {
        if (ratings[i]>ratings[i+1]){
            candies[i] = Math.max(candies[i], candies[i+1]+1)

        }

    }
return candies.reduce((a,b) => a+b, 0)

};
```

#### Expected behavior

Here the ratings are given of 3 students. So, there should be a test case for more than three students like this one- 
ratings =
 input - [1,0,2,3,3]
output- [9]
explanation- Start at the beginning of the sequence and, at each step, choose the next move that gets you as close as possible to the end while considering the values at each position. Keep track of the total number of steps taken along the way.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/112472739/6cc689c2-b123-467e-aff4-21e15f82babb)

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
