### ISSUE TITLE
LC 2388 （Oracle）测试用例14问题

### ISSUE THREAD

**Issue by qiaohudao** [LeetCode-Feedback/LeetCode-Feedback#16392]
**你的 LeetCode 用户名**
suspicious-svvart2ue7

**Bug 类型**
- [ ✔ ] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
LC 2388 Oracle 版本 测试用例14，与答案一模一样但是无法通过

**你使用的语言**
Oracle

**你提交或者运行的代码**
```
/* Write your PL/SQL query statement below */
WITH t1 AS
(
SELECT id, drink, ROWNUM AS r
FROM CoffeeShop
)

SELECT id, 
(CASE
  WHEN drink IS NULL THEN drink2
  ELSE drink
END) AS drink 
FROM
(
SELECT *
FROM
(
SELECT a.id, a.drink, a.r, b.drink AS drink2, b.r AS r2, RANK() OVER (PARTITION BY a.r ORDER BY b.r DESC) AS rnk 
FROM t1 a, t1 b
WHERE a.r >= b.r
AND b.drink IS NOT NULL
)
WHERE rnk = 1
)
ORDER BY r
```

**期望行为**
14用例应该代码运行后可以通过的

**Comment by amcones** [comment]
你好，当前题目已更新，可能是西语字符导致问题，先删除了这个测试用例。请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by qiaohudao** [comment]
> 你好，当前题目已更新，可能是西语字符导致问题，先删除了这个测试用例。请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

suspicious-svvart2ue7 是我的个性域名，此外Oracle版本我还是发现该测试用例存在，请再检查一下，谢谢！

**Comment by feiceh** [comment]
感谢您对力扣的支持与信赖，当前积分奖励已发放至 suspicious-svvart2ue7，请查收～
