### ISSUE TITLE
128. Longest Consecutive Sequence - wrong time complexity 

### ISSUE THREAD

**Issue by MateuszGierczak** [LeetCode-Feedback/LeetCode-Feedback#16396]
#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Wrong time complexity of  'Approach 3: HashSet and Intelligent Sequence Building'

Approach 3 according to its description has O(n) complexity. But it is not possible because as a first step of this algorithm there is an hash set building from 'nums' which has O(n logn) complexity. To build hash set from 'nums' we have to iterate through all elements of 'nums' (O(n)) and insert to hash set (O(logn)). That's why this algorithm finally is O(n logn) not O(n).

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by MateuszGierczak** [comment]
Thanks, I'm waiting for a response

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

Inserting into a normal hash set is an O(1) operation not O(log n). The original article is correct.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
