### ISSUE TITLE
(133) Clone Graph node definition

### ISSUE THREAD

**Issue by RFenolio** [LeetCode-Feedback/LeetCode-Feedback#164]
**What kind of the bug**
- [x] problem
- [ ] solution
- [x] language

**Describe the bug**
https://leetcode.com/problems/clone-graph/
For the Python solution, the node definition provided in the comments uses a mutable data structure, a list, as the default value for the __init__ function. The makes it so all instances of the Node class that don't include a "neighbors" parameter have a reference to the same list instead of each having their own neighbors list.

the node class in the problem is
```
# Definition for a Node.
class Node:
    def __init__(self, val = 0, neighbors = []):
        self.val = val
        self.neighbors = neighbors
```

The init function should probably be something like
```
def __init__(self, val = 0, neighbors = None):
        self.val = val
        self.neighbors = neighbors if neighbors is not None else []
```

**what language is your code written in**
Python

**The code you submit/run**
```
n1 = Node(1)
n2 = Node(2)
n3 = Node(3)
n1.neighbors.append(n2)
// all nodes now contain n2 in their neighbors list.
```
however
```
n1 = Node(1, [])
n2 = Node(2, [])
n3 = Node(3, [])
n1.neighbors.append(n2)
// only n1.neighbors contains n2
// n2, and n3 each have an empty list for neighbors
```
**Expected behavior**
When a node is created and the "neighbors" parameter is not passed in, it should get a new list separate from all other nodes.

**Additional context**
https://docs.python-guide.org/writing/gotchas/

**Comment by CooperCooperCooper** [comment]
Hi @RFenolio,
Thank you for reaching out to us! I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @RFenolio,
Thank you for your time. We've updated the problem according to your feedback. Please reach out to our main support channel support@leetcode.com to with your username, Github user info, and this issue to claim your reward for this valid contribution.
