### ISSUE TITLE
Missing Test Case - 332. Reconstruct Itinerary

### ISSUE THREAD

**Issue by rohanbobby01** [LeetCode-Feedback/LeetCode-Feedback#16408]
#### Category of the bug

- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

- The question states: "You must use all the tickets once and only once."
- But in the test case 8:  `tickets =
[["EZE","AXA"],["TIA","ANU"],["ANU","JFK"],["JFK","ANU"],["ANU","EZE"],["TIA","ANU"],["AXA","TIA"],["TIA","JFK"],["ANU","TIA"],["JFK","TIA"]]` 
- The solution given is `["JFK","ANU","EZE","AXA","TIA","ANU","JFK","TIA","ANU","TIA","JFK"]`
- You can clearly `"TIA" -> "ANU"` ticket is used twice, which shouldn't be possible according to the question.

#### Code you used for Submit/Run operation

```
class Solution:
    def findItinerary(self, tickets: List[List[str]]) -> List[str]:
        adj = defaultdict(list)

        for t1, t2 in tickets:
            if t2 not in adj[t1]:
                adj[t1].append(t2)
        
        res = ['JFK']
        visit = set()


        def dfs(prev, node):
            if (prev, node) in visit:
                return

            if len(res) == len(tickets) + 1:
                return True
            
            visit.add((prev, node))

            for nei in sorted(adj[node]):
                res.append(nei)
                if dfs(node, nei):
                    return True
                res.pop()
            
            visit.remove((prev, node))
        
        dfs(-1, 'JFK')

        return res

```

#### Language used for code

Python

#### Expected behaviour

This is supposed to be an invalid test case as there is no way you can use all without repeating an Itinerary.

**Comment by yumkam** [comment]
There are *two* tickets TIA -> ANU. You can (and must) use *each* of them *once*.

**Comment by rohanbobby01** [comment]
Well, I think that should be mentioned in the question. How will the candidate know if there are duplicates in `tickets`?

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
