### ISSUE TITLE
Missing Test Case - 207. Course Schedule

### ISSUE THREAD

**Issue by SButterfly** [LeetCode-Feedback/LeetCode-Feedback#16403]
#### Your LeetCode username
[sergeiermakof](https://leetcode.com/sergeiermakof)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
I propose to add a **simple** test case to check a chain of dependencies (>=2 vertexes).
If I had this **simple** test case in my first attempt I would sooner provide a correct result.

```
3
[[1,0],[2,1]]
```

#### Code you used for Submit/Run operation

My code, which **fails** on the providing test case.
```
class Solution {
    public boolean canFinish(int n, int[][] prerequisites) {
      var graph = new HashMap<Integer, Set<Integer>>();
      int[] incomingConnections = new int[n];

      for (int[] pre : prerequisites) {
        int first = pre[1];
        int second = pre[0];

        graph.computeIfAbsent(first, __ -> new HashSet<Integer>()).add(second);
        incomingConnections[second]++;
      }
      
      for (int node = 0; node < n; node++) {
        if (incomingConnections[node] == 0) {
            Queue<Integer> queue = new ArrayDeque<Integer>();
            queue.add(node);

            while (!queue.isEmpty()) {
              var x = queue.poll();

              var nextNodes = graph.getOrDefault(x, Set.of());
              for (int nextNode : nextNodes) {
                incomingConnections[nextNode]--;

                if (incomingConnections[nextNode] == 0) {
                  queue.add(nextNode);
                }
              }
            }
        }
      }

      for (int node = 0; node < n; node++) {
        if (incomingConnections[node] != 0) {
          return false;
        }
      }

      return true;
    }
}
```

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
