### ISSUE TITLE
Missing Test Case - 412. Fizz Buzz

### ISSUE THREAD

**Issue by Nokhrin** [LeetCode-Feedback/LeetCode-Feedback#16407]
#### Your LeetCode username

aleksandr_nohrin

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

[acceptance link](https://leetcode.com/problems/fizz-buzz/submissions/1048957940/)

```
class Solution:
    def fizzBuzz(self, n: int) -> List[str]:
        answer: List[str] = [str(i) for i in range(1, n + 1)]
        for i in range(2, len(answer), 3):
            answer[i] = 'Fizz'
        for i in range(4, len(answer), 5):
            answer[i] = 'Buzz'
        for i in range(14, len(answer), 15):
            answer[i] = 'FizzBuzz'
        return answer
```

#### Language used for code
Python3

##### Corner cases
* 1
* 10000

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

1
10000
already exists. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
