### ISSUE TITLE
Missing Test Case - 162. Find Peak Element

### ISSUE THREAD

**Issue by lakshya2901** [LeetCode-Feedback/LeetCode-Feedback#16402]
#### Your LeetCode username

Papa_ji

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
"class Solution {
public:
    int findPeakElement(vector<int>& nums) {
        int start = 0;
        int end = nums.size()-1;
        while(s<e){
            int mid = start +(end-start)/2;
            if(nums[mid] < nums[mid+1]){
                start = mid+1;
            } else{
                end = mid;
            }
        }
        return end;
    }
};"
```

#### Language used for code

C++

#### Expected behavior

In the case of the input nums = [1,6,1,3,4,5,2], there are two peak elements: 6 at index 1 and 5 at index 5. The peak elements are elements that are greater than their neighbors.

#### Screenshots

<img width="274" alt="Screenshot 2023-09-14 020100" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/60301590/2eca7d43-6fa8-4ff9-a211-595fc00d7c49">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by lakshya2901** [comment]
Here is my code submission accepted link.
https://leetcode.com/problems/find-peak-element/submissions/1038853980/

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

Our judge working correctly.

Please ask your question in the discussion forum.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
