### ISSUE TITLE
Missing Test Case - 1342. Number of Steps to Reduce a Number to Zero

### ISSUE THREAD

**Issue by Nokhrin** [LeetCode-Feedback/LeetCode-Feedback#16405]
#### Your LeetCode username

aleksandr_nokhrin

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

[acceptance link](https://leetcode.com/problems/number-of-steps-to-reduce-a-number-to-zero/submissions/1048916359/)

```
class Solution:
    def numberOfSteps(self, num: int) -> int:
        steps_count: int = 0
        while num > 0:
            steps_count += 1
            if num & 1:
                num -= 1  # if num is odd, subtract 2
            else:
                num >>= 1  # if num is even, divide by 2
        return steps_count
```

#### Language used for code
Python3

#### The missing test cases
* 0
* 1000000

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

0
1000000
already exists

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
