### ISSUE TITLE
Missing Test Case - 53. Maximum Subarray

### ISSUE THREAD

**Issue by Panchajanya1999** [LeetCode-Feedback/LeetCode-Feedback#16410]
#### Your LeetCode username
panchajanya1999

#### Category of the bug
- Missing Test Cases 

#### Description of the bug

Adding a test case which is mentioned in J. Bentley's book 'Programming Pearls' which made the problem popular.
The link of the problem - [here](https://leetcode.com/problems/maximum-subarray/)

The input array is - [-1, 2, 4, -3, 5, 2, -5, 2]
The output shall be 10

#### Code you used for Submit/Run operation

```
// Maximum Subarray
class Solution:
    def maxSubArray(self, nums: List[int]) -> int:
        best = nums[0]
        sum = nums[0]
        
        for num in nums[1:]:
            sum = max(num, sum + num)
            best = max(sum, best)
        return best
```

#### Language used for code

Python

#### Expected behavior

As per the book, it is supposed to give 10 as output, which is the correct output.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/26135639/693bc771-fc7a-474b-a01f-09c204cd213b)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The judge working correctly. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
