### ISSUE TITLE
Missing Test Case - 1732. Find the Highest Altitude

### ISSUE THREAD

**Issue by hola-aryan** [LeetCode-Feedback/LeetCode-Feedback#16411]
#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug

Adding a new Testcase

#### Code you used for Submit/Run operation

```
class Solution {
    public int largestAltitude(int[] gain) {
        int max = 0;
        int sum = 0;
        for(int i=0; i<gain.length; i++){
            sum+=gain[i];
            if(sum>max) max= sum;
        }
        return max;
    }
}
```
Input: gain = [-9,-1,-2,92]
Output: 82
Explanation: The altitudes are [-9,-1,-2,92]. The highest is 82.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Please ask your question in the discussion forum.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
