### ISSUE TITLE
1327. List the Products Ordered in a Period- Inputs

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1641]
#### Your LeetCode username

pratap_082020

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

**Issues-**

- Problem accepting negative units that are not practically correct.
- Problem accepting duplicate primary key for Products table.

**Test case-** 

{"headers": {"Products": ["product_id", "product_name", "product_category"], "Orders": ["product_id", "order_date", "unit"]}, "rows": {"Products": [[1, "Leetcode Solutions", "Book"], [1, "Jewels of Stringology", "Book"], [3, "HP", "Laptop"], [4, "Lenovo", "Laptop"], [5, "Leetcode Kit", "T-shirt"]], "Orders": [[1, "2020-02-05", -60], [1, "2020-02-10", -70], [2, "2020-01-18", -30], [2, "2020-02-11", 80], [3, "2020-02-17", 2], [3, "2020-02-24", 3], [4, "2020-03-01", 20], [4, "2020-03-04", 30], [4, "2020-03-04", -60], [5, "2020-02-25", 50], [5, "2020-02-27", 50], [5, "2020-03-01", 50]]}}

#### Code you used for Submit/Run operation

```
# Write your MySQL query statement below

SELECT * FROM
(
SELECT A.PRODUCT_NAME, SUM(B.UNIT) AS UNIT FROM PRODUCTS AS A
LEFT JOIN ORDERS AS B
ON A.PRODUCT_ID = B.PRODUCT_ID

WHERE
SUBSTRING(B.ORDER_DATE,1,7) IN ('2020-02')
GROUP BY A.PRODUCT_NAME
    ) TEMP WHERE TEMP.UNIT > 99
```

#### Language used for code

MySQL

#### Expected behavior

Should not accept duplicate primary-key and negative values for units.

#### Additional context

Problem - https://leetcode.com/problems/list-the-products-ordered-in-a-period/

**Comment by lc-kay** [comment]
@pratap-082020 

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@pratap-082020 We have added the validator to check the primary key.
The other issue will be supported later when we add some fixes to the SQL drivers. Thank you for your time.
