### ISSUE TITLE
Hashing - Confusing explanation

### ISSUE THREAD

**Issue by viniciusteixeiradias** [LeetCode-Feedback/LeetCode-Feedback#16414]
#### Your LeetCode username
viniciusteixeiradias

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Is not a bug, but the explanation of the example 4 in this page here [Link ](https://leetcode.com/explore/interview/card/leetcodes-interview-crash-course-data-structures-and-algorithms/705/hashing/4512/) is confusing.
Actual Text:
 `You can see that there are three differences in this array of 3 - 4 - 1, 6 - 3, 7 - 4.`.
 But It should be something like:
`You can see that there are three differences in this array of 3 => (4 - 1), (6 - 3), (7 - 4).`

#### Expected behavior

`You can see that there are three differences in this array of 3 => (4 - 1), (6 - 3), (7 - 4).`

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/69281620/02d818d0-c3c2-42af-9eff-241d59929a14)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
