### ISSUE TITLE
941. Valid Mountain Array ( It's showing verdict Accepted for wrong answer )

### ISSUE THREAD

**Issue by sifat009** [LeetCode-Feedback/LeetCode-Feedback#1642]
#### Category of the bug
 ✅ Solution

#### There is a problem in your test case checker for javaScript. This submission should get the wrong answer instead it's accepted. 

Here is my submission [link](https://leetcode.com/submissions/detail/429220432/)

#### Code you used for Submit/Run operation

```
/**
 * @param {number[]} arr
 * @return {boolean}
 */
var validMountainArray = function (arr) {
  if (arr.length < 3) return false;
  if (arr[0] >= arr[1]) return false;
  let up = true;

  for (let i = 1; i < arr.length; i++) {
    const [curr, prev] = [arr[i], arr[i - 1]];
    if (curr < prev) up = false;
    // if (curr === prev) return false; This line should be enabled to get (AC)
    if (!up && curr >= prev) return false;
  }
  if (up) return false;
  return true;
};
```

#### Expected Behaviour
/**
 * input: [0, 2, 3, 3, 5, 2, 1, 0]
 * output: true
 * expected-output: false
 *
 */

[![wrong.png](https://i.postimg.cc/c19Zk9Bp/wrong.png)](https://postimg.cc/QVTRHqPm)

**Comment by lc-kay** [comment]
Hi @sifat009 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@sifat009  This solution already fails because we added a test case previously that failed it. Thank you for your time!

**Comment by sifat009** [comment]
Thanks for your reply. But i think i didn't explain you well or you didn't checked my link of submission. This test case must fail. But when i'm submitting the wrong code it's getting accepted.

[submission image] (https://prnt.sc/w34dtv)

**Comment by sifat009** [comment]
Since this issue is closed i've created a new issue, you can check there
