### ISSUE TITLE
1584. Min Cost to Connect All Points -- Example Pictures Looks Unclear with ‘Dark Side’

### ISSUE THREAD

**Issue by Ming91** [LeetCode-Feedback/LeetCode-Feedback#16429]
#### Your LeetCode username

[wming9310](https://leetcode.com/wming9310/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Pictures of examples in the `Daily Problem` of 09/15/2023, [1584. Min Cost to Connect All Points](https://leetcode.com/problems/min-cost-to-connect-all-points/), looks unclear in `Dark Side` / Dark Mode. 

#### Screenshots

![Screenshot 2023-09-14 221925](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/3740139/a5b231e7-d206-494c-8d3d-abb124dccfe7)

**Comment by abhinit21** [comment]
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/58618233/de694cac-f262-45f5-b030-1f85ec72edda)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
