### ISSUE TITLE
Missing Test Case - 494. Target Sum

### ISSUE THREAD

**Issue by chrisconcepcion** [LeetCode-Feedback/LeetCode-Feedback#16425]
#### Your LeetCode username

Chris1337

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Requesting to add a test case to help the platform.

#### Code you used for Submit/Run operation

```
# @param {Integer[]} nums
# @param {Integer} target
# @return {Integer}
def find_target_sum_ways(nums, target)

    new_dp_hash = {} 
    new_dp_hash[-nums[0]] = 1
    if new_dp_hash[nums[0]] 
        # This line accounts for the edge case specified and would fail to pass without it.
        new_dp_hash[nums[0]] = 2
    else
        new_dp_hash[nums[0]] = 1
    end
    
    index = 1
    while index < nums.size
        old_dp_hash = new_dp_hash
        new_dp_hash = {}
        pos_num = nums[index]
        neg_num = -nums[index]
        old_dp_hash.keys.each do |num|
            pos_combined_num = pos_num + num
            neg_combined_num = neg_num + num

            if new_dp_hash[pos_combined_num]
                new_dp_hash[pos_combined_num] = new_dp_hash[pos_combined_num] + old_dp_hash[num]
            else
                new_dp_hash[pos_combined_num] = old_dp_hash[num]
            end

            if new_dp_hash[neg_combined_num]
                new_dp_hash[neg_combined_num] = new_dp_hash[neg_combined_num] + old_dp_hash[num]
            else
                new_dp_hash[neg_combined_num] = old_dp_hash[num]
            end
        end

        index = index + 1
    end

    new_dp_hash[target].to_i
end
```

#### Language used for code

Ruby

#### Expected behavior

I am suggesting adding a test case for nums =
[0,1], target = 1 to problem https://leetcode.com/problems/target-sum/

It would help people run into an edge case for when nums[0] == 0 which for this problems equates to dp[0][0] == 2(easily confused for dp[0][0]=1) using the common dp algo. This test case can help people understand the edge case early on without going through a much longer testcase at the very end which can lte due to the much longer size of nums when you don't have the right algo. 

#### Additional context

Honestly, just trying to help people have a better experience on wonderful platform.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

[0,1]
1
already exists. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
