### ISSUE TITLE
今天的每日一题没有中文翻译，希望能够补充，谢谢！

### ISSUE THREAD

**Issue by yujiuqie** [LeetCode-Feedback/LeetCode-Feedback#16428]
**你的 LeetCode 用户名**

yujiuqie

** 题目地址 **

https://leetcode.cn/problems/WHnhjV/?envType=daily-question&envId=2023-09-15

** 描述问题 **

缺少英文翻译，选择“题目以英文显示时”页面展示错误

<img width="555" alt="截屏2023-09-15 10 10 52" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/45526367/496fea8b-3274-4965-b476-eee6d0953f01">

** 翻译参考 **

以下是我自己的翻译，可能有误，供参考，谢谢

LCP 50. Gem Supply

Welcome to the LeetCode's Novice Area. Before starting the game, please carry out "Gem Supply".

Each hero initially possesses some energy gems, and gem[i] represents the number of gems of the i-th hero. Now these brave men have made a series of giving operations. operations[j] = [x, y] means that in the j-th operation, the x-th hero will give half of his gems (need to be rounded down) to the y-th. hero.

After completing all the operations, please find the hero with the most gems and the hero with the least gems, and return the difference in the number of gems between them.

The giving operations will be done step by step in order.

Example 1:

Input: gem = [3,1,2], operations = [[0,2],[2,1],[2,0]]

Output: 2

Explanation: In the first operation, hero 0 gives half of his gems to hero 2, gem = [2,1,3]. In the second operation, hero 2 gives half of his gems to hero 1, gem = [2,2,2]. In the third operation, hero 2 gives half of the gems to hero 0, gem = [3,2,1]. So return 3 - 1 = 2.

Example 2:

Input: gem = [100,0,50,100], operations = [[0,2],[0,1],[3,0],[3,0]]

Output: 75

Explanation: In the first operation, hero 0 gives half of his gems to hero 2, gem = [50,0,100,100]. In the second operation, hero 0 gives half of his gems to hero 1, gem = [25,25,100,100]. In the third operation , hero 3 will give half of his gems to hero 0, gem = [75,25,100,50]. In the fourth operation, hero 3 will give half of his gems to hero 0, gem = [100,25,100,25]. So return 100 - 25 = 75.

Example 3:

Input: gem = [0,0,0,0], operations = [[1,2],[3,1],[1,2]]

Output: 0

**Comment by feiceh** [comment]
感谢反馈，LCP 的题目都没有英文题面的，我们会在后续的版本不断更新优化和提升。
<img width="717" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/61722985/9cb9df9c-0d04-4695-83ea-68c7c86c95cc">
