### ISSUE TITLE
[4,0,0,0,0,0,0,0] Missing Test Case - 11. Container With Most Water

### ISSUE THREAD

**Issue by tarushi16** [LeetCode-Feedback/LeetCode-Feedback#16424]
#### Your LeetCode username
tarushi16

#### Category of the bug

- [4,8,2,5,7,1,3,6] Missing Test Cases 

#### Description of the bug
I didn't found this test case and tried manually running and it didn't work

#### Code you used for Submit/Run operation

```
class Solution {
    public int maxArea(int[] height) {
        int water=0, left=0, right=height.length-1;
        while(left<right) {
            water = Math.max(water, Math.min(height[left],height[right]) * (right-left));
            if(height[left] > height[right])
                right--;
            else
                left++;
        }
        return water;
    }
}

```

#### Expected behavior
I expected the answer as 28 but instead, it shows 36.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Please ask your question in the discussion forum.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
