### ISSUE TITLE
Missing Test Case - 260. Single Number III

### ISSUE THREAD

**Issue by cgsgak1** [LeetCode-Feedback/LeetCode-Feedback#1643]
#### Your LeetCode username

cgsgak1

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Missing testcase. Border cases are not checked by existing testcases.

#### Code you used for Submit/Run operation

```
class Solution
{
public:
    vector<int> singleNumber(vector<int>& nums) 
    {
        // Pass 1 : 
        // Get the XOR of the two numbers we need to find
        int diff = accumulate(nums.begin(), nums.end(), 0, bit_xor<int>());
        // Get its last set bit
        diff &= -diff;  // This operation will cause an error, is diff stores INT_MIN value

        // Pass 2 :
        vector<int> rets = {0, 0}; // this vector stores the two numbers we will return
        for (int num : nums)
        {
            if ((num & diff) == 0) // the bit is not set
            {
                rets[0] ^= num;
            }
            else // the bit is set
            {
                rets[1] ^= num;
            }
        }
        return rets;
    }
};
```

#### Language used for code

C++

#### Expected behavior

'''
diff &= -diff;  // This operation will cause an error, is diff stores INT_MIN value
'''

#### Additional context

The following testcase checks if solution correctly processes INT_MIN value.
Input:
[1,1,0,-2147483648]

**Comment by lc-kay** [comment]
Hi @cgsgak1 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @cgsgak1 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
