### ISSUE TITLE
In Dijkstra's (LeetCode's Interview Crash Course: Data Structures and Algorithms) the weight mentioned is incorrect

### ISSUE THREAD

**Issue by gunjansoni5** [LeetCode-Feedback/LeetCode-Feedback#16435]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the LeetCode's Interview Crash Course: Data Structures and Algorithms Chapter Bonus - Sub Chapter Dijkstra's - in the section "Dijkstra's Algorithm" - In the following paragraph:
1. dist >= distances[nei]. In this case, we already found a path with a shorter distance earlier, and thus traversing to nei on the current path is pointless.
2. dist < distances[nei]. Traversing to nei on the current path is the shortest path we have seen so far to nei. We should update distances[nei] = weight and push (weight, nei) onto the heap.

#### Expected behavior

In point 2, it should be distances[nei] = dist and push (dist, nei) since we're concerned with the weight or distance of the nei from the source and not the current node.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/52091901/558d5fcd-c977-4a1f-bf55-1a595012b397)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
