### ISSUE TITLE
1136. Parallel Courses -- Pictures in Editorial Solutions Looks Unclear with ‘Dark Side’

### ISSUE THREAD

**Issue by Ming91** [LeetCode-Feedback/LeetCode-Feedback#16439]
#### Your LeetCode username

[wming9310](https://leetcode.com/wming9310/)

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Pictures in editorial solutions of the `Weekly Premium` of Sep 2023 Week 3, [1136. Parallel Courses](https://leetcode.com/problems/parallel-courses/), looks unclear in `Dark Side` / Dark Mode. The pictures in the slides are also included.

#### Screenshots

![Screenshot 2023-09-15 135355](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/3740139/eb3f90c7-69a6-4353-bf2b-8fd12e45173c)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

Please turn off the dark mode for a better reading experience.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
