### ISSUE TITLE
Missing Test Case - 111. Minimum Depth of Binary Tree

### ISSUE THREAD

**Issue by sohah** [LeetCode-Feedback/LeetCode-Feedback#1644]
#### Your LeetCode username
sohahussein

#### Category of the bug
- [ ] Solution -- incorrect test case

#### Description of the bug
Test case #23 [1,2,3,4,5] = 2 , is incorrect. Because the TreeNode definition given is not a valid TreeNode, more precisely, the leaves in a TreeNode must end with null children, which is not the case in this test case.

**Comment by lc-kay** [comment]
@sohah The expected result is correct. Please check this out https://leetcode.com/problems/minimum-depth-of-binary-tree/discuss/36342/WA-12345-Expected%3A2-!  Thank you for your time!

**Comment by sohah** [comment]
@lc-kay, This is an invalid test case, the reason that it is invalid is not because of the result, it is because you can't declare a binary tree in this form. Every node must have **two** children, even if they are going to be defined as null. The reason that this is a wrong test case is because the leaves do not have null children. For example if 2 is a leaf, then it can't be just 2, it needs to be {2, null, null}. This looks like a list more than a tree definition.

**Comment by lc-kay** [comment]
Hi @sohah 
I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@sohah The test case is correct, please check out the following post for clarification as to how LeetCode represents a binary tree.
This can be helpful https://support.leetcode.com/hc/en-us/articles/360011883654-What-does-1-null-2-3-mean-in-binary-tree-representation-

**Comment by lc-kay** [comment]
@sohah The test case is correct, please check out the following post for clarification as to how LeetCode represents a binary tree.
This can be helpful https://support.leetcode.com/hc/en-us/articles/360011883654-What-does-1-null-2-3-mean-in-binary-tree-representation-
