### ISSUE TITLE
Missing Test Case - 1795. Rearrange Products Table

### ISSUE THREAD

**Issue by paneer24** [LeetCode-Feedback/LeetCode-Feedback#16444]
#### Your LeetCode username
Paneerselvam

#### Category of the bug
 [ ] Missing Test Cases 

#### Description of the bug
We have to check for is null condition in every stores if it is null in the given example only store2 is having null values.

#### Code you used for Submit/Run operation
SELECT product_id, 'store1' AS store, store1 AS price 
FROM Products 
WHERE store1 IS NOT NULL
UNION 
SELECT product_id, 'store2' AS store, store2 AS price 
FROM Products 
WHERE store2 IS NOT NULL
UNION 
SELECT product_id, 'store3' AS store, store3 AS price 
FROM Products 
WHERE store3 IS NOT NULL

```
Tet case 
product_id | store1 | store2 | store3 |
+------------+--------+--------+--------+
| 0          | 95     | 100    | null   |
| 1          | null     | null   | 80     |

#### Language used for code
MySQL

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
