### ISSUE TITLE
Missing Test Case - 139. Word Break

### ISSUE THREAD

**Issue by pragyasharma3734** [LeetCode-Feedback/LeetCode-Feedback#16448]
#### Your LeetCode username
pra_sha3734

#### Category of the bug
Missing Test Case

#### Description of the bug
I think this test case is missing. My code is submitted but it will give wrong answer for this test case.

#### Code you used for Submit/Run operation
 ``` 
class Solution {
public:
    bool wordBreak(string s, vector<string>& wordDict) {
        vector<bool> dp(s.size()+1,false);
        dp[0]=true;
        for(int i=1;i<=s.size();i++){
            for(int j=i-1;j>=0;j--){
                if(dp[j]){
                    string w=s.substr(j,i-j);
                    if(find(wordDict.begin(),wordDict.end(),w)!=wordDict.end()){
                        dp[i]=true;
                        break;
                    }
                }
            }
        }
        return dp[s.size()];
    }
};
```

#### Language used for code
C++

#### Expected behavior
For input:
s = "catsandog"
wordDict = ["catsand","dog","cat"]

Expected Output: true
Output: false

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/77573076/28ae5049-9afa-4b7f-aaf5-3fd80721cba8)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

![Screen Shot 2023-09-18 at 3 42 50 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/16f69587-9d8a-4876-96e5-fb5acf7bba89)
Test case already exists and our judge working correctly. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
