### ISSUE TITLE
Missing Test Case - 543. Diameter of Binary Tree

### ISSUE THREAD

**Issue by abyss9x3** [LeetCode-Feedback/LeetCode-Feedback#16447]
#### Your LeetCode username

abyss9x3

#### Category of the bug
- [ ] Solution

#### Description of the bug

with the input of 1 2 3 the following code is generating 2 as the output but in gfg it is showing it showing it should be 3. kindly check and confirm.
*************************************
class Solution {
public:
    
    int height(TreeNode* root, int &diameter){
        if(root == nullptr) return 0;
        int leftHeight = root->left? height(root->left, diameter) : 0;
        int rightHeight = root->right? height(root->right, diameter) : 0;
        diameter = max(diameter, leftHeight + rightHeight);
        return 1 + max(leftHeight, rightHeight);
    }
    
    int diameterOfBinaryTree(TreeNode* root) {
        int diameter = 0;
        height(root, diameter);
        return diameter;
    }
};
***************************************************

#### Code you used for Submit/Run operation

```
class Solution {
public:
    
    int height(TreeNode* root, int &diameter){
        if(root == nullptr) return 0;
        int leftHeight = root->left? height(root->left, diameter) : 0;
        int rightHeight = root->right? height(root->right, diameter) : 0;
        diameter = max(diameter, leftHeight + rightHeight);
        return 1 + max(leftHeight, rightHeight);
    }
    
    int diameterOfBinaryTree(TreeNode* root) {
        int diameter = 0;
        height(root, diameter);
        return diameter;
    }
};
```

#### Language used for code

C++

#### Expected behavior

output should come as 3 as shown by gfg but leetcode is showing 2 as correct

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Please ask your question in the discussion forum.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
