### ISSUE TITLE
1480. Running Sum of 1D Array - wrong space compexity in explanation with creation of result array

### ISSUE THREAD

**Issue by INeedMySpace** [LeetCode-Feedback/LeetCode-Feedback#16458]
#### INeedMySpace

The video explanation states that time complexity is O(n) and space complexity is O(1) for the implementation that creates additional array for result (which is of size n) which is wrong. The same time and space complexity are stated for in place implementation which is correct.

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by arturmartins** [comment]
This is still an issue today. The video needs to be redone for the first solution.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've used your feedback to check the problem.

We redirected it to our content team and it will take time to fix.

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!
