### ISSUE TITLE
Typings improvement for 1584. Min Cost to Connect All Points

### ISSUE THREAD

**Issue by HamsterCoder** [LeetCode-Feedback/LeetCode-Feedback#16451]
#### Your LeetCode username
HamsterCoder

#### Category of the bug
- [ ] Question
- [ ] Solution
- [+] Language
- [ ] Missing Test Cases 

#### Description of the bug
It isn't as much a bug as an improvement suggestion. Currently the typescript template looks like this:

```
function minCostConnectPoints(points: number[][]): number {

};
```

So I ran into a problem with these typings having written the following code:

```
function manhDist([x1, y1]: [number, number], [x2, y2]: [number, number]): number {
    return Math.abs(x1 - x2) + Math.abs(y1 - y2);
}

function minCostConnectPoints(points: number[][]): number {
    // Solution ideas
    // Union Find - we need to know which point are already connected
    // Greedy - choose min distance everytime

    let distances = [];

    for (let point of points) {
        for (let anotherPoint of points) {
            if (point !== anotherPoint) {
                distances.push(
                    manhDist(point, anotherPoint),

                );
            }
        }
    }
};
```

Which if ran gives you an error:

```
Line 18: Char 30: error TS2345: Argument of type 'number[]' is not assignable to parameter of type '[number, number]'.
```

And basically the solution is to change the typings of the template - these are stricter and better:

```
function minCostConnectPoints(points: [number, number][]): number {

};
```

#### Code you used for Submit/Run operation
See above

#### Language used for code
TypeScript

#### Expected behavior
See above

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
