### ISSUE TITLE
Missing Test Case - 121. Best Time to Buy and Sell Stock

### ISSUE THREAD

**Issue by VishalJadav23** [LeetCode-Feedback/LeetCode-Feedback#16457]
#### Category of the bug

-   Solution
-  Question 

#### Description of the bug
I write for this sum and its working complete in my pc with all new array, but leet code result give me error to particular array but i tried also that on my pc and  its working properly.

#### Code you used for Submit/Run operation
const day = [7, 6, 4, 3, 1];
let i = 0;
let j = 1;
let profit = 0;
function profitFunc (day) {

    while (i < day.length && j < day.length) {
        if (day[j] - day[i] > profit) {
            profit = day[j] - day[i];
        }

        j++;
        if (j === day.length) {
            j = i + 1;
            i++;
        }
    }
    return profit;

}
console.log(profitFunc(day));

#### Language used for code
JavaScript

**Comment by LC-Pam** [comment]
Thank you for reaching out to us! Unfortunately, we are unable to troubleshoot the different behavior between your local IDE and the LeetCode environment.

For this issue, please raise this as a discuss post in the problem discuss section as other users may have run into the same issue and resolved it.

At LeetCode, we care about the whole learning experience that comes with each problem and we encourage users to teach and help each other to enrich their learning. In addition, we want our users to debug their code and learn from the process.

We appreciate your time and support.
