### ISSUE TITLE
Missing Test Case - 74. Search a 2D Matrix

### ISSUE THREAD

**Issue by code978** [LeetCode-Feedback/LeetCode-Feedback#1645]
#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@code978 Please provide the accepted code and the test case it failed on.

**Comment by lc-kay** [comment]
Hi @code978 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
