### ISSUE TITLE
【石子游戏 VI】题目描述歧义

### ISSUE THREAD

**Issue by Arsenal591** [LeetCode-Feedback/LeetCode-Feedback#1646]
** Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
原文：「Alice 和 Bob 对石子价值有不一样的的评判标准 」。

题目描述中，并未明确说明所谓「评判标准」，是否为 Alice 与 Bob 之间的共识。换言之，Alice 未必知道 bobValues 的取值，而 Bob 也未必知道 aliceValues 的取值。

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，对于这个题目，Alice 和 Bob 知不知道对方的评价标准并不重要，重要的是你完全了解这两位的评价标准并认可题目中所描述的：“两位玩家都会采用 最优策略 进行游戏”。

**Comment by Arsenal591** [comment]
何为「最优策略」**显然依赖于每位玩家掌握的具体信息**。如果 Alice 对 Bob 的评价标准一无所知，那么 Alice 只能假定 Bob 的评价标准服从某个独立分布，从而「最优策略」就为「每次选剩下的石子中 Alice 评价最高的」。
「我」是否了解二位的评价标准丝毫不重要，因为参与游戏的是 Alice 与 Bob，而不是「我」，因此 Alice 和 Bob 一定需要知道彼此的评价标准。
如果对上面这段话仍然有疑问，可以通过以「完全信息动态博弈」与「非完全信息动态博弈」为关键词搜索相关的描述。
总之，本人并不认为提出的疑问得到了有效的解答。

**Comment by feiceh** [comment]
十分抱歉，当前已确认这个问题并更新了中文题面，我们会进一步同 US题目团队沟通进行同步。如果你愿意的话可以留言提供一下中站的力扣 ID，会奖励一些 LeetCoin，感谢您的反馈与支持。

**Comment by Arsenal591** [comment]
我的 ID 是 Arsenal591(https://leetcode-cn.com/u/arsenal-591/)

**Comment by feiceh** [comment]
好的，ID：arsenal-591 给予积分奖励，请查收。
