### ISSUE TITLE
Missing Test Case - 2855. Minimum Right Shifts to Sort the Array

### ISSUE THREAD

**Issue by DenzilJD** [LeetCode-Feedback/LeetCode-Feedback#16466]
#### Your LeetCode username
denziljudedaniels

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

Missing Test Case

#### Code you used for Submit/Run operation

```
//Minimum Right Shifts to Sort the Array
class Solution {
public:
    int minimumRightShifts(vector<int>& nums) {
        int j=-1,k=0;
        for(int i=1;i<nums.size();i++)
        {
            if(nums[i]<nums[i-1])
            {
                k++;
                j=i;
            }
            if(k>1)
                return -1;
        }
        if(j==-1)
            return 0;
        int l=nums[j-1];
        for(int i=j;i<nums.size();i++)
            if(l<nums[i])
                return -1;
        return nums.size()-j;
    }
};
```

#### Expected behavior

For the Test Case [2,3,5,1,4], the solution mentioned above, is accepted, even though it is clearly wrong.

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team

**Comment by DenzilJD** [comment]
It has been corrected, now, and my answer has been marked as 'Wrong Answer', instead of 'Accepted', as well.
Here's the link, anyway:
https://leetcode.com/problems/minimum-right-shifts-to-sort-the-array/submissions/1050933368/
