### ISSUE TITLE
Missing Test Case - 2855. Minimum Right Shifts to Sort the Array

### ISSUE THREAD

**Issue by gopeshb** [LeetCode-Feedback/LeetCode-Feedback#16470]
#### Your LeetCode username

gopeshbhatia01
https://leetcode.com/gopeshbhatia01/

#### Category of the bug
- [[2855. Minimum Right Shifts to Sort the Array](https://leetcode.com/problems/minimum-right-shifts-to-sort-the-array/) ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

my answer is passed but i tried to change test case as i think there might be some mistake in the code i created a testcase 
nums =
[3,4,1,2,5]
whose output by accepted code is showing is 3 but excepted output shown by system is -1.hence the code i wrote is wrong but still passed by compiler.

#### Code you used for Submit/Run operation

```
class Solution {
  
    public int minimumRightShifts(List<Integer> nums) {
        int c=0;int idx=0;int n=nums.size();
        for(int i=1;i<n;i++){
            if(nums.get(i)<nums.get(i-1)){
                c++;idx=i;
            }
        }
        if(c>1)
        return -1;
        if(idx==1&&nums.get(0)<nums.get(n-1))
        return -1;
        if(c==0)
        return 0;
        return n-idx;

    }
}
```

#### Language used for code

i wrote code in java but missing test case is common for all languages.

#### Expected behavior

the code given in solutions is not correct as there are many cases missing and incorrect solution is being accepted by compiler.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/145230384/e03a0a9d-f14e-488a-b091-f01157b87037)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/145230384/67f4b6da-91df-4704-ae85-8c3b3380fb42)

**Comment by kunal232i** [comment]
Hello gopeshbhatia01,
The test case you provided ([3,4,1,2,5]) is indeed a valid one. According to the problem statement, it’s impossible to sort this array using only right shifts, so the expected output should be -1. However, your code is returning 3, which indicates that there might be a mistake in your code.

Your code seems to be checking if there’s more than one instance where a number is smaller than the previous number in the array (which would make it impossible to sort the array with right shifts). However, it doesn’t account for cases where the array is a rotation of a sorted array but the smallest number isn’t at index 0 (like in your test case).

**Comment by gopeshb** [comment]
class Solution {
  
    public int minimumRightShifts(List<Integer> nums) {
        int c=0;int idx=0;int n=nums.size();
        for(int i=1;i<n;i++){
            if(nums.get(i)<nums.get(i-1)){
                c++;idx=i;
            }
        }
        if(c>1)
        return -1;
        if(idx==1&&nums.get(0)<nums.get(n-1))
        return -1;
        if(c==0)
        return 0;
        return n-idx;

    }
}

**Comment by gopeshb** [comment]
> Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
> 
> The code submission Accepted link.We only add new test cases when some solution gets accepted but shouldn't because it fails on the suggested test case. This minimizes the test suite and optimizes the grader's performance. We could stress-test each solution for minutes instead of relying on hardcoded test cases if performance was not an issue
> 
> We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

https://leetcode.com/problems/minimum-right-shifts-to-sort-the-array/submissions/1051248741/

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
