### ISSUE TITLE
Missing Test Case - 1527. Patients With a Condition

### ISSUE THREAD

**Issue by sachinrodge** [LeetCode-Feedback/LeetCode-Feedback#1647]
#### Your LeetCode username
 petedoyle

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language

#### Description of the bug

As per the expected output, conditions  always starts with DIAB1 prefix. But solution is accepted even when DIAB1 is in middle e.g. SADIAB1 is not a valid condition but current test cases doesn't cover this. 

#### Code you used for Submit/Run operation

```
select *
from 
Patients
where
conditions LIKE '%DIAB1%'
```

#### Language used for code

mysql

#### Expected behavior

If someone submits above code, it should say "Wrong Answer". To fix this issue, add below negative test case
```
{"headers": {"Patients": ["patient_id", "patient_name", "conditions"]}, "rows": {"Patients": [[1, "Daniel", "SADIAB100"]]}}
```

**Comment by lc-kay** [comment]
Hi @sachinrodge 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @sachinrodge 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
