### ISSUE TITLE
Missing Test Case - 166. Fraction to Recurring Decimal

### ISSUE THREAD

**Issue by amitmitangi** [LeetCode-Feedback/LeetCode-Feedback#1649]
-50/8 answer cannot be -6.25 since -48 is greater than -50 and in division number to be subtracted cannot be greater than numerator.

**Comment by amitmitangi** [comment]
answer should be "-7.75"

**Comment by lc-kay** [comment]
@amitmitangi The expected is correct because -50 divided by 8 is -6.25. In division, there's no number to be subtracted. Thank you for your time.
