### ISSUE TITLE
Missing Test Case - 847. Shortest Path Visiting All Nodes

### ISSUE THREAD

**Issue by NithinU2802** [LeetCode-Feedback/LeetCode-Feedback#16492]
#### Your LeetCode username
nithinu2810

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

 I Would Like to recommend an testcase for this problem which I noticed that not available. As the problem with finding 
shortest path in graph. As I would like to recommand an empty array if no graph exist then we need to return 0 as output:

Recommended
Input: graph=[[]]
Output: 0

#### Code you used for Submit/Run operation

```
// [Shortest Path Visiting All Nodes](https://leetcode.com/problems/shortest-path-visiting-all-nodes/)
class Path{
        int node;
        int steps;
        Set<Integer> visit;
        Path(int node,int steps,Set<Integer> visit){
            this.node=node;
            this.steps=steps;
            this.visit=new HashSet<>(visit);
    }
}

class Solution {

    int shortestPathLength(int[][] graph){ 
        int n=graph.length;

        Map<Integer,Set<Set<Integer>>> map=new HashMap<>();
        Queue<Path> queue=new LinkedList<>();

        for(int i=0;i<n;i++){
            Set<Integer> set=new HashSet<>();
            set.add(i);
            map.put(i,new HashSet<>(Arrays.asList(set)));
            queue.add(new Path(i,0,set));
        }

        while(!queue.isEmpty()){
            Path current=queue.poll();
            int node=current.node;
            int steps=current.steps;
            Set<Integer> v=current.visit;
            if(v.size()==n)
                return steps;
            for(int j:graph[node]){
                Set<Integer> newVisit=new HashSet<>(v);
                newVisit.add(j);
                if(!map.get(j).contains((newVisit))){
                    queue.add(new Path(j,steps+1,newVisit));
                    map.computeIfAbsent(j,k->new HashSet<>()).add(newVisit);
                }
            }
        }
        return 0;  // Need to return something if graph is empty
    }
}
```

#### Language used for code

Java

#### Expected behavior

From the above code and testcase I would need to prefer which is basic logic that if the graph not exist then we need to return 0 as output. So I would like to recommend this as per the learn. Thank You for the team LeetCode..:).

#### Screenshots

TestCase Recommendation

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

[[]] already exists. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
