### ISSUE TITLE
The expected answer field is showing unexpected result

### ISSUE THREAD

**Issue by ashwini571** [LeetCode-Feedback/LeetCode-Feedback#165]
**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
I got runtime error for my following code for the following problem in 3rd test case to which the expected answer field was also showing runtime error. See the screenshot for clarification.
**what language is your code written in**
C++

**The code you submit/run**
```
// Construct Binary Search Tree from Preorder Traversal
class Solution {
public:
    TreeNode* constructTreeUtil( vector<int> &pre, int &preIndex, int key,  
                                int min, int max, int size )  
{   
    if( preIndex >= size )  
        return NULL;  
  
    TreeNode* root = NULL;  
    if( key > min && key < max )  
    {  
        
        root = new TreeNode ( key );  
        preIndex = preIndex + 1;  
          
        if (preIndex < size)  
        { 
            root->left = constructTreeUtil( pre, preIndex, pre[preIndex],  
                                        min, key, size );  
            root->right = constructTreeUtil( pre, preIndex, pre[preIndex],  
                                        key, max, size );  
        }  
    }  
  
    return root;  
}
    TreeNode* bstFromPreorder(vector<int>& preorder) {
        
        int i=0;
        TreeNode *bst = constructTreeUtil(preorder,i,preorder[0],INT_MIN,INT_MAX,preorder.size());
        
        
        return bst;
        
    }
};
```

**Expected behavior**
The expected answer should be showing [4,2] for 3rd test case
**Screenshots**
![IMG20200420154439](https://user-images.githubusercontent.com/37906306/79829876-cda08f80-83c1-11ea-9233-d4a34ef08e56.jpg)

**Comment by CooperCooperCooper** [comment]
Hi @ashwini571,
Thank you for reaching out to us! I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @ashwini571,
Adding to the previous message: to help us assess this issue, can you please clarify which problem/ Explore Card did this issue arise from?

**Comment by ashwini571** [comment]
It is from the 30-day leetcoding challenge.
Here's the link:-
https://leetcode.com/explore/challenge/card/30-day-leetcoding-challenge/530/week-3/3305/

**Comment by CooperCooperCooper** [comment]
Hi @ashwini571 ,
Thank you for sharing. I've relayed it to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @ashwini571 ,

Thank you for your time. Upon investigating this issue, we found this issue to be non-content-related (the issue stems from an origin away from the content on this problem); therefore, it's not valid for content contribution reward. 

We encourage you to share more content-related issues here with us for [valid content contribution rewards](https://leetcode.com/discuss/general-discussion/526802/File-Problem-and-Solution-Content-Issues-to-Our-GitHub-Public-Feedback-Repo-Now!). Thank you again for your support and understanding.

**Comment by CooperCooperCooper** [comment]
Hi @ashwini571 ,
Thank you for your time! Just want to let you know that the bug has been fixed :)
