### ISSUE TITLE
Missing Test Case - 229. Majority Element II

### ISSUE THREAD

**Issue by brookchen** [LeetCode-Feedback/LeetCode-Feedback#1650]
#### Your LeetCode username

broook

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Missing testcase. 

#### Code you used for Submit/Run operation

```
func majorityElement(nums []int) []int {
	if len(nums) == 0 {
		return nil
	}
	var candidate1, candidate2, count1, count2 int
	for _,v := range nums {
		if count1 == 0 {
			candidate1 = v
			count1 = 2
		} else if candidate1 == v {
			count1 += 2
		} else {
			count1--
		}
	}

	for _,v := range nums {
		if v != candidate1 {
			if count2 == 0 {
				candidate2 = v
				count2 = 1
			} else if candidate2 == v {
				count2++
			} else {
				count2--
			}
		}
	}
	count1, count2 = 0, 0
	for _,v := range nums {
		if v == candidate1 {
			count1++
		} else if v == candidate2 {
			count2++
		}
	}

	var result []int
	if count1*3 > len(nums) {
		result = append(result, candidate1)
	}
	if count2 * 3 > len(nums) {
		result = append(result, candidate2)
	}
	return result
}
```

#### Language used for code

Go

#### Expected behavior

My solution gets Wrong answer for Input `[2,1,1,3,1,4,5,6]`.  And it gets Accepted after submitting.

#### Screenshots

<img width="746" src="https://user-images.githubusercontent.com/8371441/102007077-dedb4980-3d60-11eb-851f-d6165868406f.png">

**Comment by lc-kay** [comment]
Hi @brookchen 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @brookchen 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
