### ISSUE TITLE
544. Output Contest Matches - Typo in Question

### ISSUE THREAD

**Issue by agrawalishaan** [LeetCode-Feedback/LeetCode-Feedback#16507]
#### Your LeetCode username
agrawalishaan

#### Category of the bug
- [X ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the question, it writes: `During the NBA playoffs, we always set the rather strong team to play with the rather weak team, like make the rank 1 team play with the rank nth team, which is a good strategy to make the contest more interesting.`

It should say `like making`, not `like make`.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
