### ISSUE TITLE
Missing Test Case - 1342. Number of Steps to Reduce a Number to Zero

### ISSUE THREAD

**Issue by Vaibhav2552** [LeetCode-Feedback/LeetCode-Feedback#16506]
#### Category of the bug
- [ 1342] Question
- [class Solution {
    public int numberOfSteps(int num) {
        return helper(num,0);
        }
        private int helper(int num, int steps){
        if(num==0){
            return steps;
        }
        if(num %2 ==0){
            return helper(num/2, steps+1);
        }
          return helper(num-1, steps+1);
    }
} ] Solution
- [ java] Language
- [00000000000000 ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Vaibhav2552** [comment]
class Solution {
public int numberOfSteps(int num) {
return helper(num,0);
}
private int helper(int num, int steps){
if(num==0){
return steps;
}
if(num %2 ==0){
return helper(num/2, steps+1);
}
return helper(num-1, steps+1);
}
} 
  JAVA is the language used.
missing test case is 1200320

**Comment by Vaibhav2552** [comment]
okay thats fine i haven't seen that.
