### ISSUE TITLE
Missing Test Case - 1189. Maximum Number of Balloons

### ISSUE THREAD

**Issue by kotovdd** [LeetCode-Feedback/LeetCode-Feedback#16511]
#### Your LeetCode username
kotovdd

#### Category of the bug
Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int maxNumberOfBalloons(const string &text) {
        std::vector<int> vec(5);
        for(auto &c:text)
        {
            switch(c)
            {
            case 'b': {
                ++vec.at(0);
                break;
                }
            case 'a': {
                ++vec.at(1);
                break;
                }
            case 'l': {
                ++vec.at(2);
                break;
                }
            case 'o': {
                ++vec.at(3);
                break;
                }
            case 'n': {
                ++vec.at(4);
                break;
                }
        }
        }
        int max_twice = std::min(vec.at(2)/ 2, vec.at(3) /2);
        int max_once = std::min(std::max(vec.at(0), vec.at(1)), vec.at(4));
        if (max_twice == 0 || max_once == 0)
            return 0;
        else
            return std::min(max_twice, max_once);
    }
};
```

#### Expected behavior
all tests are passed, although they should not be
add this to test cases "looalxallpooalloobbnnn"

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've used your feedback to update the problem.

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback.

Please provide us with your LCCN or LCUS username.

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!

**Comment by kotovdd** [comment]
My username - wirenyeOn 20 Sep 2023, at 03:40, LC_M ***@***.***> wrote:﻿
Thank you for your time.
We've used your feedback to update the problem.
Your LeetCode account will receive 100 LeetCoins as a reward for this feedback.
Please provide us with your LCCN or LCUS username.
If you have any other questions or feedback, please don't hesitate to let us know!
We appreciate your support!
