### ISSUE TITLE
Missing Test Case - 1045. Customers Who Bought All Products

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1652]
#### Your LeetCode username

[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

**A test case is missing-**

{"headers":{"Customer":["customer_id","product_key"],"Product":["product_key"]},"rows":{"Customer":[[1,1],[1,3],[2,1],[2,2],[2,3],[2,4],[3,1],[4,1]],"Product":[[1],[2],[3]]}}

![image](https://user-images.githubusercontent.com/71989691/102008370-d29dbf00-3d55-11eb-9470-078929ce1d7d.png)

#### Code you used for Submit/Run operation

```
# Write your MySQL query statement below

Select A.CUSTOMER_ID from CUSTOMER AS A
group by A.CUSTOMER_ID
having count(distinct A.PRODUCT_KEY) >= (select count(*) from PRODUCT)
```

#### Language used for code

MySQL

#### Expected behavior

**A test case is missing-**

{"headers":{"Customer":["customer_id","product_key"],"Product":["product_key"]},"rows":{"Customer":[[1,1],[1,3],[2,1],[2,2],[2,3],[2,4],[3,1],[4,1]],"Product":[[1],[2],[3]]}}

#### Additional context

Problem- https://leetcode.com/problems/customers-who-bought-all-products/submissions/

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
