### ISSUE TITLE
287. Find the Duplicate Number

### ISSUE THREAD

**Issue by Vaibhav07351** [LeetCode-Feedback/LeetCode-Feedback#16528]
The statement of the question is slightly misleading.

"All the integers in nums appear only once except for precisely one integer which appears two or more times."

This statement must be mentioned at the top of the question. Mentioning it below makes the question misleading to assume that a repeated number can be repeated only 1 time.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
