### ISSUE TITLE
3 Longest substring without repeating character submission bug for python

### ISSUE THREAD

**Issue by swahilinerd** [LeetCode-Feedback/LeetCode-Feedback#16534]
#### Your LeetCode username

swahilinerd

#### Category of the bug
- [ ] Solution

#### Description of the bug

All the test case pass except for submission 

#### Code you used for Submit/Run operation

```
// 3 Longest substring without repeating a character 
from itertools import permutations

class Solution:
    def lengthOfLongestSubstring(self, s: str) -> int: 
        perms = (
            "".join(dict.fromkeys("".join(item))) 
            for length in range(1, len(s) +1) 
            for item in permutations(s, length) 
        )
        perms = set(perms) 
        subs = [sub for sub in perms if sub in s] 
        return len(max(subs, key=len)) 

```

#### Language used for code

Python

#### Screenshots

![Screenshot from 2023-09-19 20-12-16](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/57592923/9767f906-8796-4413-9e07-88dff4b306d8)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Please ask your question in the discussion forum.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
