### ISSUE TITLE
[LeetCode's Interview Crash Course DS & A][Article :1D problems] Error in explanation.

### ISSUE THREAD

**Issue by ArshiyanAlam** [LeetCode-Feedback/LeetCode-Feedback#16533]
#### Category of the bug
- [ ] Question
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

In Article **_1D problems - Example 3_**, below line is written mentioning "days we need to wait" but the example question has nothing to do with days. 

**"We could include an integer that represents how many more days we need to wait until we can start solving questions again,"**

[Page Link](https://leetcode.com/explore/interview/card/leetcodes-interview-crash-course-data-structures-and-algorithms/712/dynamic-programming/4541/)

#### Expected behavior

AS IS : _"... more days we need to wait ..."_
TO BE: _"... questions we need to skip ..."_

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've used your feedback to update the problem.

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback.

Please provide us with your LCCN or LCUS username.

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!

**Comment by ArshiyanAlam** [comment]
Thanks!

My LCUS username is "arsharsh"
