### ISSUE TITLE
Missing Test Case - 12. Integer to Roman

### ISSUE THREAD

**Issue by nkonangi** [LeetCode-Feedback/LeetCode-Feedback#16531]
#### Your LeetCode username
knr2015

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X ] Missing Test Cases 

#### Description of the bug

Additional Test case for testing edge cases with zero place values for Ones, Tens and Hundreads to make sure logic is implemented accurately.
EX: 1000, 1001, 1010, 1100

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution:
    def intToRoman(self, num: int) -> str:
        thousands =['','M','MM','MMM']
        hundreds=['','C','CC','CCC','CD','D','DC','DCC','DCCC','CM']
        tens=['','X','XX','XXX','XL','L','LX','LXX','LXXX','XC']
        ones=['','I','II','III','IV','V','VI','VII','VIII','IX']
        return thousands[num//1000]+hundreds[(num%1000)//100]+tens[(num%100)//10]+ones[num%10]
```

#### Language used for code

Python3

#### Expected behavior

For large numbers like
 1) 1000, the output should be M
 2) 1001 the output should be MI
 3) 1010 the output should be MX
 4) 1100 the output should be MC 

#### Additional context

Adding additional test cases for testing zero place values in between the number.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The judge working correctly and 1000, 1001, 1010, and 1100 all already exist. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
