### ISSUE TITLE
Wrong Test Case

### ISSUE THREAD

**Issue by vsc100** [LeetCode-Feedback/LeetCode-Feedback#16538]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior

There should only be one repeated number as written in the description but the given test case contains repeated digits.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/60096428/6a2fe14d-b867-47f0-a1a4-94e0fc4fecc2)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by vsc100** [comment]
Actually just look at the problem description which says there in ONLY ONE REPEATED NUMBER IN ARRAY but you can see in the test case no 11 there are five repeated numbers. So the given testcase is wrong according to the given description in question.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
