### ISSUE TITLE
Missing Test Case - 1076. Project Employees II

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1653]
#### Your LeetCode username

pratap_082020

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

**There is no use of employee table to make result table-**

**test case missing-**

{"headers":{"Project":["project_id","employee_id"],"Employee":["employee_id","name","experience_years"]},"rows":{"Project":[[1,1],[1,2],[1,3],[2,1],[2,4]],"Employee":[]}}

![image](https://user-images.githubusercontent.com/71989691/102009581-62476b80-3d5e-11eb-835e-b45fc2870b13.png)

#### Code you used for Submit/Run operation

```
select p.project_id
from project p
group by p.project_id
having count(p.project_id) >= all(
select count(distinct(e.employee_id)) as max
from employee e
join project p
on p.employee_id = e.employee_id
group by p.project_id)
```

#### Language used for code

MySQL

#### Expected behavior

A test case is missing-

{"headers":{"Project":["project_id","employee_id"],"Employee":["employee_id","name","experience_years"]},"rows":{"Project":[[1,1],[1,2],[1,3],[2,1],[2,4]],"Employee":[]}}

#### Additional context

Problem- https://leetcode.com/problems/project-employees-ii/

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
