### ISSUE TITLE
Solution with Syntax Error got Accepted - 287. Find the duplicate Number

### ISSUE THREAD

**Issue by RiyaSingh245** [LeetCode-Feedback/LeetCode-Feedback#16539]
#### Your LeetCode username
_Riyasingh

#### Category of the bug
- Language

#### Description of the bug
Leetcode Problem number 287 got accepted even when my solution has syntax error.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int findDuplicate(vector<int>& nums) {

       //syntax error in below line
        int n = nums.size();;   

        for(int i = 0; i < n; i++)
        {
            int idx = abs(nums[i]);

            if(nums[idx] < 0) return idx;
            nums[idx] = -nums[idx];
        }
        return n;
    }
};
```

#### Language used for code
C++

#### Expected behavior
It must have shown compilation error.

#### Additional context
My submission Link

https://leetcode.com/problems/find-the-duplicate-number/submissions/1053852204/?envType=daily-question&envId=2023-09-19

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
