### ISSUE TITLE
1631. Path With Minimum Effort (Typo in Editorial)

### ISSUE THREAD

**Issue by StrawHatDragon100** [LeetCode-Feedback/LeetCode-Feedback#16543]
#### Your LeetCode username
strawhatdragon

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/19656900/ce2cea45-fdc1-4090-bd7b-34d86afea819)
The neighboring cells of `A` are `B` `C` `D` and `E`, but instead of `E` `F` is mentioned.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
