### ISSUE TITLE
bug while running the test case - 113. Path Sum II

### ISSUE THREAD

**Issue by VenkataBhaskarr** [LeetCode-Feedback/LeetCode-Feedback#16545]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The below solution is producing the correct output while running from different editors except when I am submitting in leetcode.

#### Code you used for Submit/Run operation

```
class Solution {
    public List<List<Integer>> pathSum(TreeNode root, int targetSum) {
        List<List<Integer>> answer = new ArrayList<>();
        depthSearch(root, targetSum, 0, new ArrayList<>(), answer);
        return answer;
    }
    public void depthSearch(TreeNode node, int target,int current, List<Integer> row,List<List<Integer>> answer){
        if(node == null){
            return;
        }
        if(node.left == null && node.right == null){
            row.add(node.val);
            current += node.val;
            if(target == current){
                answer.add(new ArrayList<>(row));
            }
            row.remove(row.size()-1);
            return;
        }
        if(node.left == null){
            row.add(node.val);
            depthSearch(node.right,target,current+node.val,row,answer);
            row.remove(row.size()-1);
            return;
        }
        if(node.right == null){
            row.add(node.val);
            depthSearch(node.right,target,current+node.val,row,answer);
            row.remove(row.size()-1);
            return;
        }
        row.add(node.val);
        depthSearch(node.left,target,current+node.val,row,answer);
        depthSearch(node.right,target,current+node.val,row,answer);
        row.remove(row.size()-1);
        return;
    }
}
```

#### Language used for code
Java

#### Expected behavior

Expected behavior : 
root = [5,4,8,11,null,13,4,7,2,null,null,5,1]
targetSum = 22
output = [[5,4,11,2],[5,8,4,5]]

Actual behavior : 
root = [5,4,8,11,null,13,4,7,2,null,null,5,1]
targetSum = 22
output = [[5,8,4,5]]

#### Screenshots

Leetcode : 

<img width="779" alt="Screenshot 2023-09-20 at 10 41 14 AM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/111889155/b84b40d7-ab28-47b9-958c-da380660dfc9">

My editor:
 
<img width="767" alt="Screenshot 2023-09-20 at 10 41 34 AM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/111889155/056ec3bb-4fd0-448d-aebf-2a43e6bcd06b">

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
