### ISSUE TITLE
1658. Minimum Operations to Reduce X to Zero -- Pictures in Editorial Solutions Looks Unclear with ‘Dark Side’

### ISSUE THREAD

**Issue by Ming91** [LeetCode-Feedback/LeetCode-Feedback#16544]
#### Your LeetCode username

[wming9310](https://leetcode.com/wming9310/)

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Pictures in editorial solutions of the `Daily Question` of 09/19/2023, [1658. Minimum Operations to Reduce X to Zero](https://leetcode.com/problems/minimum-operations-to-reduce-x-to-zero/), looks unclear in `Dark Side` / Dark Mode. 

This is the third or fourth time I have posted this kind of bug. I hope that in the future, LeetCode can review the images before posting them to the `Daily Question` or `Weekly Premium` and increase the adaptability of the dark mode.

#### Screenshots

![Screenshot 2023-09-19 212414](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/3740139/b4eaa1d0-bc30-4e72-9d32-d815e567da81)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

 Please turn off the dark mode for a better reading experience.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
