### ISSUE TITLE
2569. Handling Sum Queries After Update - Typo in Question

### ISSUE THREAD

**Issue by agrawalishaan** [LeetCode-Feedback/LeetCode-Feedback#16541]
#### Your LeetCode username
agrawalishaan

#### Category of the bug
- [X ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the question, it writes: 
<img width="659" alt="Screenshot 2023-09-19 at 7 26 38 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/113543798/12d562ef-5876-4d55-bd00-c3e16e3feaab">

The code formatting for `nums1 ` extends one space too far.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
