### ISSUE TITLE
Missing Test Case - 1679. Max Number of K-Sum Pairs

### ISSUE THREAD

**Issue by wangerone** [LeetCode-Feedback/LeetCode-Feedback#16546]
#### Your LeetCode username

Wanger1

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

When there are consecutive numbers which meet the condition, use map[int]bool is not working.
e.g. nums = [1, 1, 4, ,4], k = 5

#### Code you used for Submit/Run operation

```golang
func maxOperations(nums []int, k int) int {
    table := map[int]bool{}
    cnt := 0
    for _, v := range nums {
        if _, ok := table[k-v]; ok {
            cnt += 1
            delete(table, k-v)
        } else {
            table[v] = true
        }
    }
    return cnt
}
```

#### Language used for code

Go

#### Expected behavior

My code should not be accepted 

#### Screenshots

<img width="960" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/119935296/64a7a6ec-2479-4932-9865-1aff6f2512c8">

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
