### ISSUE TITLE
Missing Test Case - 1658. Minimum Operations to Reduce X to Zero

### ISSUE THREAD

**Issue by xyftw** [LeetCode-Feedback/LeetCode-Feedback#16542]
#### Your LeetCode username
gdstw

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I wrote a terrible code that ignored some boundary conditions, but it can also be accepted.

`[1,1,4,2,3], 6`

#### Code you used for Submit/Run operation

```
class Solution:
    def minOperations(self, nums: List[int], x: int) -> int:
        n = len(nums)
        left, right = 0, n-1
        lsum, rsum = 0, 0
        while left < n and lsum < x: # count left side first
            lsum += nums[left]
            left += 1
        ans = float('inf')
        if lsum == x: # can select all from left
            ans = left
        while left <= right and left > 0 and right >= 0: # this line should be corrected to left > 0, instead of left >= 0
            lsum -= nums[left-1] # remove rightmost element from left
            left -= 1
            while lsum + rsum < x and right >= 0: # make lsun + rsum >= x
                rsum += nums[right]
                right -= 1
            if lsum + rsum == x: # update ans
                ans = min(ans, left + n - right - 1)
        return ans if ans != float('inf') else -1
```

#### Language used for code

`Python`

#### Expected behavior

add testcase: 
nums = [1,1,4,2,3]
x = 6

#### Screenshots

![](https://i.imgur.com/FrbxPOE.png)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The test case [1,1,4,2,3], 6 already exists. 

![Screen Shot 2023-09-20 at 1 01 31 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/6f1bec7d-c01e-4054-a1f0-ac358056d0b0)


If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
