### ISSUE TITLE
1393. Capital Gain/Loss- accepting different value

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1654]
#### Your LeetCode username

[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

**As per the description- The operation column is an ENUM of type ('Sell', 'Buy'). So, this column should take only ('Sell', 'Buy') these 2 values.**

**Test case - Taking "test"**

{"headers":{"Stocks":["stock_name","operation","operation_day","price"]},"rows":{"Stocks":[["Leetcode","BUY",1,1000],["Corona Masks","Buy",2,10],["Leetcode","**TEST**",5,9000],["Handbags","Buy",17,30000],["Corona Masks","Sell",3,1010],["Corona Masks","Buy",4,1000],["Corona Masks","Sell",5,500],["Corona Masks","Buy",6,1000],["Handbags","Sell",29,7000],["Corona Masks","Sell",10,10000]]}}

#### Code you used for Submit/Run operation

```
# Write your MySQL query statement below

SELECT A.STOCK_NAME, 

SUM(CASE WHEN A.OPERATION = 'SELL' THEN A.PRICE
    ELSE 0 END ) -
SUM(CASE WHEN A.OPERATION = 'BUY' THEN A.PRICE
   ELSE 0 END ) AS CAPITAL_GAIN_LOSS

FROM STOCKS AS A
GROUP BY A.STOCK_NAME
```

#### Language used for code

MySQL

#### Expected behavior

Should take only "Buy" or "Sell"

#### Additional context

Problem- https://leetcode.com/problems/capital-gainloss/

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@pratap-082020 Our team has reviewed your report and found the issue to be with the driver. We have noted this issue and will schedule to fix it. Thank you for your time.
