### ISSUE TITLE
Missing Test Case - 287. Find the Duplicate Number

### ISSUE THREAD

**Issue by masterujjval** [LeetCode-Feedback/LeetCode-Feedback#16540]
#### Your LeetCode username
Mrgupta

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
[14,3,4,5,2,7,9,8,10,6,11,15,12,18,14,17,14,1,13]

#### Code you used for Submit/Run operation

```
// Find the Duplicate Number
class Solution {
public:
    int findDuplicate(vector<int>& nums) {
        
        int n=nums.size();
        
        vector<int>ans(n,0);
        
        ans=nums;
        
        
        
        sort(ans.begin(),ans.end());
        int temp=ans[0];
        
        for(int i=1;i<n;i++){
            
            if(ans[i]==temp)return ans[i];
            else temp=ans[i];
            
            
        }
        
        return temp;
    }
};
```

#### Language used for code
C++

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

[14,3,4,5,2,7,9,8,10,6,11,15,12,18,14,17,14,1,13] already exists. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
