### ISSUE TITLE
Missing Test Case - 1658. Minimum Operations to Reduce X to Zero

### ISSUE THREAD

**Issue by Zefick** [LeetCode-Feedback/LeetCode-Feedback#16554]
#### Your LeetCode username
Zefick

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
nums = [1, 10, 1]
x = 22

Accepted solution returns 4 but the right answer is -1.

#### Code you used for Submit/Run operation

``` python
class Solution:
    def minOperations(self, nums: List[int], x: int) -> int:
        if x == nums[0]:
            return 1

        n = len(nums)
        prefix = sum(nums)
        postfix = 0
        m = -1
        j = 0
        for i in range(n-1, -1, -1):
            prefix -= nums[i]
            while j < n-1 and prefix + postfix < x:
                postfix += nums[n-j-1]
                j += 1
            if prefix + postfix == x:
                m = (i + j) if m < 0 else min(m, i + j)

        return m
```

#### Language used for code
Python

#### Expected behavior
-1

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
