### ISSUE TITLE
Missing Test Case - 852. Peak Index in a Mountain Array

### ISSUE THREAD

**Issue by piyush9625** [LeetCode-Feedback/LeetCode-Feedback#16565]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by piyush9625** [comment]
Add more test to be sure

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code and language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
