### ISSUE TITLE
[Bug in judge] 2863. Maximum Length of Semi-Decreasing Subarrays

### ISSUE THREAD

**Issue by huangshan-01** [LeetCode-Feedback/LeetCode-Feedback#16564]
#### Username
huangshan01

#### Category of the bug
- Test case passable individual run, bug not passing judge if submitted. No global variables involved.

#### Description of the bug
Simple test case, answer = 4, from -255 to -733.
[-987,-255,-657,-81,-733,980]
Submission, judge returns expected as 3.

#### Code you used for Submit/Run operation
```
class Solution:
    def maxSubarrayLength(self, nums: List[int]) -> int:
        n = len(nums)
        dc = {}
        for i, v in enumerate(nums):
            if v not in dc:
                dc[v] = [i]
            elif len(dc[v]) == 1:
                dc[v].append(i)
            else:
                dc[v][1] = i

        r = -1
        ans = 0
        for v, idx in sorted(dc.items()):
            ans = max(ans, r - idx[0] + 1)
            r = max(r, idx[-1])
        return ans
```

#### Language used for code
Python 3

#### Expected behavior
Expected = 4

#### Screenshots
Standalone test case passed. Code has no global involved.
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/122117440/a4078f87-d31d-495e-b322-ffc32bf82ebc)

Submission failed.
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/122117440/904f96f1-3e90-4b22-9471-4ba16180de70)

**Comment by LC-Pam** [comment]
Thank you for bringing the issue to our attention.
We want to assure you that we are actively working to resolve this matter as quickly as possible.
We will let you know once the issue is fixed.
Once again, thank you for your patience and understanding.

LC_Pam

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
