### ISSUE TITLE
Missing Test Case - 88. Merge Sorted Array

### ISSUE THREAD

**Issue by Ganeshasoham001** [LeetCode-Feedback/LeetCode-Feedback#16561]
class Solution(object):
    def merge(self, nums1, m, nums2, n):
        li=[]
        for i in range(m):
            li.append(nums1[i])
        for j in range(n):
            li.append([j])
            li.sort()
        return li
This code is returing wrong output in leet code please fix it

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Zefick** [comment]
You don't have to return anything from the function. Description says: "The final sorted array should not be returned by the function, but instead be stored inside the array nums1"
