### ISSUE TITLE
Missing Test Case - 1658. Minimum Operations to Reduce X to Zero

### ISSUE THREAD

**Issue by masterujjval** [LeetCode-Feedback/LeetCode-Feedback#16566]
#### Your LeetCode username
Mrgupta

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
[1,3,10,9,21,43,67,22,29,30,45,41,17,49,33,39,91,86,72,85,14,78,54,46,79,74,55,60,65,34,11,3,5,14,10,2]
14

#### Code you used for Submit/Run operation
```
class Solution {
public:
    int minOperations(vector<int>& nums, int x) {
        int target = 0, n = nums.size();
        
        for(int i=0;i<n;i++)target+=nums[i];
        target-=x;
        
        if (target == 0) return n;
        
        int max_len = 0, cur_sum = 0, left = 0;
        
        for (int right = 0; right < n; ++right) {
            cur_sum += nums[right];
            while (left <= right && cur_sum > target) {
                cur_sum -= nums[left];
                left++;
            }
            if (cur_sum == target) {
                max_len = max(max_len, right - left + 1);
            }
        }
        
        return max_len ? n - max_len : -1;
    }
};

```
#### Language used for code
C++

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The test case you use. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by masterujjval** [comment]
edited

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

[1,3,10,9,21,43,67,22,29,30,45,41,17,49,33,39,91,86,72,85,14,78,54,46,79,74,55,60,65,34,11,3,5,14,10,2]
14 
already exists.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
