### ISSUE TITLE
Duplicate of #16464

### ISSUE THREAD

**Issue by gautamsw5** [LeetCode-Feedback/LeetCode-Feedback#16562]
WA (but it shouldn't be) - https://leetcode.com/problems/minimum-array-length-after-pair-removals/submissions/1054679612/

Accepted - https://leetcode.com/problems/minimum-array-length-after-pair-removals/submissions/1051077406/

_Originally posted by @gautamsw5 in https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/16464#issuecomment-1728084196_

**Comment by LC-Pam** [comment]
Thank you for providing additional information!
 
After investigation, we only found one submission for the problem "minimum-right-shifts-to-sort-the-array" under your account.
 
[{"link": "https://leetcode.com/submissions/detail/1054332980", "date": "2023-09-20 08:27:33"}]
 
Under contest [rules,](https://leetcode.com/discuss/general-discussion/951105/new-contest-rule-effective-from-december-2020) you will find more details.
 
If the rejudge is executed, LeetCode will rejudge all the submissions that were submitted to the problem by users who were impacted during the contest. The first Accepted submission will be taken as the final result, and the "Wrong Answer/Time Limited Exceeded" submissions made prior to the first "Accepted" submissions will be counted for penalty time.
 
If the submissions that should have been judged as “Wrong Answer” were judged as “Accepted” during the contest for any reason, LeetCode will rejudge all the submissions that got “Accepted” during this contest for the problem.
If the submissions that should have been judged as “Accepted” were judged as “Wrong Answer” during the contest for any reason, LeetCode will rejudge all the submissions that got “Wrong Answer” during this contest for the problem.
If the correct submissions were judged as “Wrong Answer”, and incorrect submissions were judged as “Accepted” during the contest for any reason, LeetCode will rejudge all the submissions that were made during this contest for the problem.
 
Unfortunately, the contest results are final. We will pass your comments along to our contest team for consideration when evaluating future contests.
