### ISSUE TITLE
772. Basic Calculator III, bug in solution, approach 1

### ISSUE THREAD

**Issue by uyennguyen30696** [LeetCode-Feedback/LeetCode-Feedback#16578]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Runtime Error
ZeroDivisionError: division by zero
    return int(x / y)
Line 10 in evaluate (Solution.py)
    stack.append(evaluate(curr, 0, previous_operator))
Line 27 in calculate (Solution.py)
    ret = Solution().calculate(param_1)
Line 56 in _driver (Solution.py)
    _driver()
Line 67 in <module> (Solution.py)

#### Code you used for Submit/Run operation

```
# Solution, approach 1
class Solution:
    def calculate(self, s: str) -> int:
        def evaluate(x, y, operator):
            if operator == "+":
                return x
            if operator == "-":
                return -x
            if operator == "*":
                return x * y
            return int(x / y)
        
        def solve(i):
            stack = []
            curr = 0
            previous_operator = "+"
            
            while i[0] < len(s):
                c = s[i[0]]
                if c == "(":
                    i[0] += 1
                    curr = solve(i)
                elif c.isdigit():
                    curr = curr * 10 + int(c)
                else:
                    if previous_operator in "*/":
                        stack.append(evaluate(stack.pop(), curr, previous_operator))
                    else:
                        stack.append(evaluate(curr, 0, previous_operator))
                     
                    if c == ")":
                        break
                    
                    curr = 0
                    previous_operator = c
                    
                i[0] += 1
            
            return sum(stack)

        s += "@"
        return solve([0])
```

#### Language used for code

Python3

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

https://leetcode.com/submissions/detail/1055711697/

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
