### ISSUE TITLE
Solution Implementation Comment Mixup - 4. Median of Two Sorted Arrays

### ISSUE THREAD

**Issue by tczhao** [LeetCode-Feedback/LeetCode-Feedback#16573]
#### Your LeetCode username

tczhao

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the [Solution section Approach 2 Implementation](https://leetcode.com/problems/median-of-two-sorted-arrays/solution/).
The Java and Python script comment is incorrect and causing confusion.
They should follow the description above and the cpp solution

For Approach 2 Java Implementation:
line 26 `        // If k is in the right half of A + B, remove the larger right half.`
this should be `        // If k is in the right half of A + B, remove the smaller left half.`
line 34 `        // Otherwise, remove the smaller left half. `
this should be `        // Otherwise, remove the larger right half. `

For Approach 2 Python3 Implementation:
line 18 `            # If k is in the right half of A + B, remove the larger right half.`
this should be `            # If k is in the right half of A + B, remove the smaller left half.`
line 24 `            # Otherwise, remove the smaller left half. `
this should be `            # Otherwise, remove the larger right half. `

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
