### ISSUE TITLE
Missing Test Case - 228. Summary Ranges

### ISSUE THREAD

**Issue by 09try** [LeetCode-Feedback/LeetCode-Feedback#16576]
#### Your LeetCode username

0994try

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Problem states that input array nums is sorted in ascending order. However there is a test case where nums is not sorted in ascending order.

#### Code you used for Submit/Run operation

```
# Summary Ranges
class Solution(object):
    def summaryRanges(self, nums):
        """
        :type nums: List[int]
        :rtype: List[str]
        """
        res = []
        i = 0
        while i < len(nums):
            start = i
            while i < len(nums) - 1 and nums[i + 1] - nums[i] <= 1:
                i += 1
                
            if start != i:
                res.append(str(nums[start]) + '->' + str(nums[i]))
            else:
                res.append(str(nums[start]))
            
            i += 1
        
        return res
```

#### Language used for code

Python

#### Expected behavior

I expected that all test cases will have nums sorted in ascending order and instead one test case does not have nums sorted in ascending order

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/77061756/58c91290-7c60-4302-86cb-1563f8f9dbf3)

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team

**Comment by 09try** [comment]
Hello thanks for the answer but still the problem description says that nums are sorted in ascending order and test judge tests with input [2, -1] which is not sorted in ascending order.

I tested my submitted code again and below you can see the result

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/77061756/12b3693c-d150-4d53-97fc-c7eafee8f9f7)
