### ISSUE TITLE
Missing Test Case - 1901. Find a Peak Element II

### ISSUE THREAD

**Issue by 1270900131** [LeetCode-Feedback/LeetCode-Feedback#16579]
#### Your LeetCode username

pathetic

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An algorithm which is poorly conceived should have passed all the test case. Insane!!!!!

#### Code you used for Submit/Run operation

```Java
class Solution {
        public int[] findPeakGrid(int[][] mat) {
            int m=mat.length,n=mat[0].length,left=0,right=n-1,i,j,top=0,bottom=m-1,flag=1;
            while(left<right||top<bottom){
                if(flag==1){
                    int mid=(top+bottom)>>1,index=0;
                    for(i=1;i<n;++i)
                        if(mat[mid][i]>mat[mid][index])
                            index=i;
                    if(mid>0&&mat[mid][index]<mat[mid-1][index]){
                        bottom=mid-1;
                    }else if(mid<m-1&&mat[mid][index]<mat[mid+1][index])
                        top=mid+1;
                    System.out.println(top);
                    System.out.println(bottom);
                    if(mat[mid][index]>(mid>0?mat[mid-1][index]:-1)&&mat[mid][index]>(mid<m-1?mat[mid+1][index]:-1))
                        return new int[]{mid,index};
                }else{
                    int mid=(left+right)>>1,index=0;
                    for(i=1;i<m;++i)
                        if(mat[i][mid]>mat[index][mid])
                            index=i;
                    if(mid>0&&mat[index][mid]<mat[index][mid-1]){
                        right=mid-1;
                    }else if(mid<n-1&&mat[index][mid]<mat[index][mid+1])
                        left=mid+1;
                    System.out.println(left);
                    System.out.println(right);
                    if(mat[index][mid]>(mid>0?mat[index][mid-1]:-1)&&mat[index][mid]>(mid<n-1?mat[index][mid+1]:-1))
                        return new int[]{index,mid};
                }
                flag=-flag;
            }
            return new int[]{top,left};
        }
}
```

#### Language used for code

Java

#### Expected behavior

Not Pass. Wrong Answer.

#### Screenshots

![](https://github.com/1270900131/image/blob/main/image1.png?raw=true)

#### Additional context

[[2,1,2,30,31,76,74],[3,2,1,29,32,77,73],[4,3,2,28,79,78,72],[5,4,1,5,50,70,71],[6,5,4,64,63,62,16],[7,6,67,65,64,2,15],[8,9,10,9,67,13,14]]

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
