### ISSUE TITLE
Missing Test Case - 5.最长回文子串

### ISSUE THREAD

**Issue by makisekurisucn** [LeetCode-Feedback/LeetCode-Feedback#16582]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名
makisekurisucn

**Bug 类型**
- [ 5.最长回文子串 ] 题目
- [ ] 题解
- [ JavaScript ] 编程语言
- [ √ ] 缺少测试用例

**描述**
描述你遇到的 bug
缺少测试用例

**你使用的语言**
JavaScript 

**你提交或者运行的代码**
```
var longestPalindrome = function(s) {
    const map = {};
    let maxItem = { allSame: true, length: 1, index: 0 };

    if (isPalindrome(s)) {
        return s;
    }

    for (i = 0; i < s.length; i++) {

        const prevInfo = map[i-1];

        let canContinue = false;

        if (prevInfo) {
            const charBeforePrev = s[i-1-prevInfo.length];

            if (charBeforePrev === s[i]) {
                map[i] = {
                    allSame: prevInfo.allSame && s[i] === s[i-1],
                    length: prevInfo.length + 2,
                    index: i,
                }
                canContinue = true
            } else if (prevInfo.allSame && s[i-1] === s[i]) {
                map[i] = {
                    allSame: true,
                    length: prevInfo.length + 1,
                    index: i,
                }
                canContinue = true
            }
        }

        if (!map[i] || map[i].length < maxItem.length) {

            // 如果从历史最大的回文的第一个字符，到当前字符也是一个回文的话，就算
            const start = maxItem.index - maxItem.length + 1
            const test = s.slice(start, i+1)
            if (isPalindrome(test)) {
                map[i] = {
                    allSame: false,
                    length: test.length,
                    index: i,
                }
                canContinue = true
            }
        }
        

        if (!canContinue) {
            // 三字符串判断
            if (i >= 2) {
                if (s[i-2] === s[i]) {
                    map[i] = {
                        allSame: false,
                        length: 3,
                        index: i,
                    }
                    canContinue = true
                }
            }
        }

        if (!canContinue) {
            if (s[i-1] === s[i]) {
                map[i] = {
                    allSame: true,
                    length: 2,
                    index: i,
                }
                canContinue = true
            }
        }

        if (canContinue) {
            if (map[i].length > maxItem.length) {
                maxItem = map[i]
            }
        }
    }

    return s.slice(maxItem.index + 1 - maxItem.length, maxItem.index + 1)

}

function isPalindrome (test) {
    const reverse = test.split('').reverse().join('')
    return reverse === test;
}
```

**期望行为**
代码存在不足，不能满足题解。但是实际提交能通过

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息
缺少测试用例，比如 s="xaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeeeffffffffffgggggggggghhhhhhhhhhiiiiiiiiiijjjjjjjjjjkkkkkkkkkkllllllllllmmmmmmmmmmnnnnnnnnnnooooooooooppppppppppqqqqqqqqqqrrrrrrrrrrssssssssssttttttttttuuuuuuuuuuvvvvvvvvvvwwwwwwwwwwxxxxxxxxxxyyyyyyyyyyzzzzzzzzzzyyyyyyyyyyxxxxxxxxxxwwwwwwwwwwvvvvvvvvvvuuuuuuuuuuttttttttttssssssssssrrrrrrrrrrqqqqqqqqqqppppppppppoooooooooonnnnnnnnnnmmmmmmmmmmllllllllllkkkkkkkkkkjjjjjjjjjjiiiiiiiiiihhhhhhhhhhggggggggggffffffffffeeeeeeeeeeddddddddddccccccccccbbbbbbbbbbaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeeeffffffffffgggggggggghhhhhhhhhhiiiiiiiiiijjjjjjjjjjkkkkkkkkkkllllllllllmmmmmmmmmmnnnnnnnnnnooooooooooppppppppppqqqqqqqqqqrrrrrrrrrrssssssssssttttttttttuuuuuuuuuuvvvvvvvvvvwwwwwwwwwwxxxxxxxxxxyyyyyyyyyyzzzzzzzzzzyyyyyyyyyyxxxxxxxxxxwwwwwwwwwwvvvvvvvvvvuuuuuuuuuuttttttttttssssssssssrrrrrrrrrrqqqqqqqqqqppppppppppoooooooooonnnnnnnnnnmmmmmmmmmmllllllllllkkkkkkkkkkjjjjjjjjjjiiiiiiiiiihhhhhhhhhhggggggggggffffffffffeeeeeeeeeeddddddddddccccccccccbbbbbbbbbbaaaa"

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by feiceh** [comment]
感谢反馈，当前 CN ID：makisekurisucn 已奖励积分，请查收～
