### ISSUE TITLE
Missing Test Case - 11. Container With Most Water

### ISSUE THREAD

**Issue by MazRagab** [LeetCode-Feedback/LeetCode-Feedback#16589]
#### Category of the bug
- [[Container With Most Water](https://leetcode.com/problems/container-with-most-water/) ] Question
- [class Solution {
    public int maxArea(int[] height) {
        
        int max = 0;
        int a = 0;
        int b = height.length - 1;

        while(a < b)
        {
            if(height[a] < height[b])
            {
                max = Math.max(max,height[a]*(b-a));
                a++;
            }
            else
            {
                max = Math.max(max,height[b]*(b-a));
                b--;
            }
        }

        return max;

    }
} ] Solution
- [ Java] Language
- [ The maximum area is between a height to the right of the left height of 2 equal heights] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
