### ISSUE TITLE
Incorrect output from the Run operation - 1917. Leetcodify Friends Recommendations

### ISSUE THREAD

**Issue by adigo** [LeetCode-Feedback/LeetCode-Feedback#16597]
#### Your LeetCode username

adigo

#### Category of the bug
- [X] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The "Run" button for test runs generates the wrong output. The "Submit" button generates the correct output.
So when the user test-run it, it will tell you that the answer is wrong, but when you submit the same answer, the same answer can pass all test cases.

If the correct output is {"headers": ["user_id", "recommended_id"], "values": [[3, 1], [3, 2], [2, 3], [1, 3]]}
test-run button tells you the the expected output is {"headers": ["user_id", "recommended_id"], "values": [[3, 1], [3, 2]]}
submit button however outputs {"headers": ["user_id", "recommended_id"], "values": [[3, 1], [3, 2], [2, 3], [1, 3]]}

the problem description example 1 also states that the expected output is {"headers": ["user_id", "recommended_id"], "values": [[3, 1], [3, 2], [2, 3], [1, 3]]}

#### Code you used for Submit/Run operation

My code is not important but I still attached it for your convenience. 
My code passed the Submit operation, but it failed the Run operation.

The official solution used in the Submit operation is different from the official solution used in the Run operation.

```
# Write your MySQL query statement below
with Listens_distinct as (
    select distinct
    *
    from Listens
), Half_results as (
    select
    a.user_id,
    b.user_id as recommended_id
    from Listens_distinct a
    inner join Listens_distinct b on
    b.user_id > a.user_id
    and b.song_id = a.song_id
    and b.day = a.day
    where
    not exists (
        select
        1
        from Friendship f
        where
        a.user_id = f.user1_id
        and b.user_id = f.user2_id
    )
    group by 1, 2, a.day
    having count(a.song_id) >= 3
)
select * from Half_results
union
select 
recommended_id as user_id,
user_id as recommended_id
from Half_results
```

#### Language used for code

MySQL

#### Screenshots

![Screenshot 2023-09-21 at 23 01 43](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/6498017/48b47e7e-027c-49da-a4e9-a438eda8383c)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by adigo** [comment]
You can reproduce the error with any test case.

So I'll just provide you with the default test case that is generating the incorrect result in the example I provided.

{"headers":{"Listens":["user_id","song_id","day"],"Friendship":["user1_id","user2_id"]},"rows":{"Listens":[[1,10,"2021-03-15"],[1,11,"2021-03-15"],[1,12,"2021-03-15"],[2,10,"2021-03-15"],[2,11,"2021-03-15"],[2,12,"2021-03-15"],[3,10,"2021-03-15"],[3,11,"2021-03-15"],[3,12,"2021-03-15"],[4,10,"2021-03-15"],[4,11,"2021-03-15"],[4,13,"2021-03-15"],[5,10,"2021-03-16"],[5,11,"2021-03-16"],[5,12,"2021-03-16"]],"Friendship":[[1,2]]}}

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
