### ISSUE TITLE
API of "Leftmost Column with at Least a One" is semantically flawed

### ISSUE THREAD

**Issue by madhur4127** [LeetCode-Feedback/LeetCode-Feedback#166]
**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
`BinaryMatrix::dimensions()` method is not marked const. It causes compiler error on const objects.

**Why is this necessary**
Since the input to the question doesn't require modification so marking it const should be the right Software Engineering practice. Instead of just solving problems, users can learn good software engineering practices too which will help them in future interviews.

**what language is your code written in**
C++

**The code you submit/run**
```c++
constexpr inline int leftMostColumnWithOne(const BinaryMatrix &mat) {
        const auto dim = mat.dimensions();
        int ans = dim[1];
        for(int row = 0; row < dim[0]; ++row){
            int low = -1, high = dim[1];
            while(low+1<high){
                int mid = (low+high)/2;
                auto x = mat.get(row, mid);
                if(x==0) low = mid;
                else high = mid;
            }
            if(high<ans) ans = high;
        }
        return ans==dim[1]?-1:ans;
    }
```

**Expected behavior**
There shouldn't be any compiler errors.

**Errors**
```
Line 14: Char 26: fatal error: 'this' argument to member function 'dimensions' has type 'const BinaryMatrix', but function is not marked const
        const auto dim = mat.dimensions();
                         ^~~
Line -8: Char 17: note: 'dimensions' declared here
    vector<int> dimensions() {
```

**Comment by CooperCooperCooper** [comment]
Hi @madhur4127,
Thank you for reaching out to us! I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @madhur4127,
Thank you for your time. Our team has taken a look at this issue. To provide better flexibility to our users' end, we will keep this design decision. We appreciate your time and support.
