### ISSUE TITLE
wrong test case 1053. Previous Permutation With One Swap

### ISSUE THREAD

**Issue by painlet** [LeetCode-Feedback/LeetCode-Feedback#1660]
**Description**
return **the lexicographically largest permutation** that is smaller than A, that can be made with one swap

For example 3:
[3,1,1,3]
The permutation confirm to the requirement should be
[1,3,1,3]
however, return [1,1,3,3] can also pass.

[1,1,3,3] is lexicographically smaller than [1,3,1,3]. So tit is the not  `the largest permutation that is smaller than A.`

**Test Case:**
[3,1,1,3]

**Test Code:**
```
class Solution:
    def prevPermOpt1(self, A: List[int]) -> List[int]:
        return [1,1,3,3]
```

**Expected Result**
Failed

**Actual Result**
Accepted

**Comment by lc-kay** [comment]
@painlet The expected answer is correct because it has to be the largest permutation smaller than A than can be obtained in _**one swap**_.
