### ISSUE TITLE
Problem with testing system   (Code  23. Merge k Sorted Lists)

### ISSUE THREAD

**Issue by hubert-groen** [LeetCode-Feedback/LeetCode-Feedback#16603]
#### Your LeetCode username
user4499UY

#### Category of the bug
- [ ] Solution

#### Description of the bug
I think the test input is realized in the wrong way (or it is not properly explained). Function mergeKLists is called more than once by the testing system. Check my code below - it should print "start", "end" and investigate the correctness of the return head.next. Instead the Stdout gives:
start
end
start
end
start

... and at this point some error occurs.
I don't understand why it runs the function again after final anwer was returned.

(I've left the prints on purpose to show the issue.)

#### Code you used for Submit/Run operation
```
class Solution:
    def mergeKLists(self, lists: List[Optional[ListNode]]) -> Optional[ListNode]:

        print("start")

        head = ListNode(0)
        current_node = head

        pointer_list = []

        for i in range(len(lists)):
            pointer_list.append(lists[i])

        end_counter = 0

        while end_counter < len(lists):

            loop_min = 100
            loop_index = None

            for k in range(len(pointer_list)):

                if pointer_list[k] == None:
                    continue

                if pointer_list[k].val <= loop_min:
                    loop_min = pointer_list[k].val
                    loop_index = k

            value = pointer_list[loop_index].val
            new_node = ListNode(value)
            current_node.next = new_node
            current_node = new_node

            pointer_list[loop_index] = pointer_list[loop_index].next

            if pointer_list[loop_index] == None:
                end_counter += 1


        print("end")
        return head.next
```

#### Language used for code
Python

#### Expected behavior
The code should pass the test. Or at least the first test case, which is lists = [[1,4,5],[1,3,4],[2,6]].
After running the code in my VS Code, I obtain expected output - check the screenshots below.

#### Screenshots
Here is the result in my VS Code. "start" and "end" are printed once (function is realized once) and then I print the output list, which is same as the expected answer.
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/61231501/b89000f0-1fee-414e-a763-b40178e0096c)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by hubert-groen** [comment]
Hi, that’s for the reply!

I don’t have the link, because my solution was not accepted.

**Comment by hubert-groen** [comment]
I've reviewed my code again and discovered that the problem lay on my side.

I was unaware that if you have some prints in the Leetcode website terminal, the terminal will not be cleared after each test case. So, multiple prints after running the code on Leetcode confused me.

Link to my solution after corrections (although it is not decent): https://leetcode.com/problems/merge-k-sorted-lists/submissions/1057084915/

I appreciate your interest!

**Comment by LC-Pam** [comment]
Thank you for your time. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
