### ISSUE TITLE
Missing Test Case - 2622. Cache With Time Limit

### ISSUE THREAD

**Issue by Shubhamag19** [LeetCode-Feedback/LeetCode-Feedback#16601]
#### Your LeetCode username
shubhamagrawal154

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

The problem is missing some test cases. In my case, I submitted solution in which I am using **setTimeout** to delete the key after the **duration** has passed. However instead of using separate timers for distinct keys, I have used same timer for all keys. So in this case if some key is to be overridden, the timer if cleared out and key is never deleted even after the time duration. I tried with custom test case and it's failing there, but it was somehow accept as a correct answer.

Here is my custom test case:
["TimeLimitedCache", "set", "set", "set", "get", "count"]
[[], [1, 13, 50], [2, 14, 300], [1, 15, 100], [2], []]
[0, 0, 0, 40, 800, 850]

Expected output:
[null,false,false,true,-1,0]

My output:
[null,false,false,true,14,1]

#### Code you used for Submit/Run operation

```
var TimeLimitedCache = function() {
    this.cache = new Map();
};

TimeLimitedCache.prototype.set = function(key, value, duration) {
    let hasValue;
    if(this.cache.has(key)) {
        hasValue = true;
        clearTimeout(this.cache.timer);
    }
    else hasValue = false;
    this.cache.set(key, value);
    this.cache.timer = setTimeout(() => {
        this.cache.delete(key);
    }, duration);
    return hasValue;
};

TimeLimitedCache.prototype.get = function(key) {
    return this.cache.get(key)??-1;
};

TimeLimitedCache.prototype.count = function() {
    return this.cache.size;
};

```

#### Language used for code

JavaScript

#### Expected behavior

My solution should not have been accepted, though it got accepted.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
