### ISSUE TITLE
Missing Test Case - 1075. Project Employees I

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1661]
#### Your LeetCode username

[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

**A test case is missing-**

{"headers":{"Project":["project_id","employee_id"],"Employee":["employee_id","name","experience_years"]},"rows":{"Project":[[1,1],[1,2],[1,3],[2,1],[2,4]],"Employee":[]}}

![image](https://user-images.githubusercontent.com/71989691/102087293-554e7900-3e3f-11eb-9d82-9e37f7b75a15.png)

#### Code you used for Submit/Run operation

```
# Write your MySQL query statement below

SELECT A.PROJECT_ID, ROUND(SUM(B.EXPERIENCE_YEARS)/COUNT(A.PROJECT_ID),2) AS AVERAGE_YEARS FROM PROJECT AS A
LEFT JOIN EMPLOYEE AS B
ON A.EMPLOYEE_ID = B.EMPLOYEE_ID
GROUP BY A.PROJECT_ID

```

#### Language used for code

MySQL

#### Additional context

Problem- https://leetcode.com/problems/project-employees-i/

**Comment by lc-kay** [comment]
@pratap-082020 The test case provided was accepted when I ran it against your code. 
<img width="1439" alt="Screen Shot 2020-12-15 at 12 24 37 PM" src="https://user-images.githubusercontent.com/70870126/102268782-92af1700-3ed0-11eb-841d-79e1aac8d299.png">
