### ISSUE TITLE
Wrong test case - 55. Jump Game

### ISSUE THREAD

**Issue by alexzaitsev** [LeetCode-Feedback/LeetCode-Feedback#16616]
#### Your LeetCode username
alexxzaitsev

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
[2,5,0,0] test case is incorrect. Expected is true but we cannot reach the last index (#3) as we will be stuck on index #2. So the correct answer is `false` for this test case.

#### Code you used for Submit/Run operation
```
// 55. Jump Game
class Solution {
    fun canJump(nums: IntArray): Boolean {
        var index = 0
        while(index < nums.size) {
            if (index == nums.size - 1) {
                return true
            }
            if (nums[index] == 0) {
                return false
            }
            index += nums[index]
        }
        return true
    }
}
```

#### Language used for code
Kotlin

#### Screenshots
<img width="744" alt="Screenshot 2023-09-22 at 18 48 07" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2372414/04afe2cb-fb86-4ce9-ad64-8d092c088591">

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
