### ISSUE TITLE
Missing Test Case - 392. Is Subsequence

### ISSUE THREAD

**Issue by masterujjval** [LeetCode-Feedback/LeetCode-Feedback#16618]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
"zhopig"
"pozxyihagvr"

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool isSubsequence(string s, string t) {
        int n = s.length(),m=t.length();
        int j = 0; 

    for (int i = 0; i < m and j < n; i++)
        if (s[j] == t[i])
            j++;
 
    
    return (j == n);
    }
};
```

#### Language used for code
 C++

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

 "zhopig"
"pozxyihagvr" 
already exists. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
