### ISSUE TITLE
#1166 User code not running properly on test case #7

### ISSUE THREAD

**Issue by mgoks** [LeetCode-Feedback/LeetCode-Feedback#16612]
#### Your LeetCode username

_noexcuses

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

The problem in question is https://leetcode.com/problems/design-file-system/description/. OJ is not running my code properly on test case 7, whereas when I use the debugger it runs properly as seen by the print statements.

#### Code you used for Submit/Run operation

```
################################################################################
class FileSystem:

    def __init__(self):
        self.root = self.Directory('')

    def createPath(self, path: str, value: int) -> bool:
        print(f'createPath({path}, {value})')
        last_slash = path.rindex('/')
        parent_path = path[0 : last_slash]
        dir_name = path[last_slash + 1 : ]
        d = self._get(parent_path)
        ret = d.mkdir(dir_name, value) if d else False
        print(f'ret is {ret}')
        return ret

    def get(self, path: str) -> int:
        d = self._get(path)
        return d.value if d else -1

    # Returns the leaf directory in path if it exists, None otherwise.
    def _get(self, path):   # -> Directory:
        # Remove the first '/'
        # "".split returns [''] so need [] path is "".
        dir_names = path[1:].split('/') if path else []
        
        directory = self.root
        for dir_name in dir_names:
            directory = directory.child(dir_name)
            if not directory:
                return None
        return directory


    class Directory:
        def __init__(self, name, value = None, children = []):
            self.value = value
            self.children = children
            self.name = name
        
        def mkdir(self, name, value) -> bool:
            if self.child(name):
                return False
            self.children.append(self.__class__(name, value))
            return True

        def child(self, name):  # -> Directory:
            for d in self.children:
                if d.name == name:
                    return d
            return None

        def __repr__(self):
            return '/' + self.name

# Your FileSystem object will be instantiated and called as such:
# obj = FileSystem()
# param_1 = obj.createPath(path,value)
# param_2 = obj.get(path)

```

#### Language used for code

Python 3

#### Expected behavior

I expect my code to pass test case 7, more precisely `createPath('/leet', 1)` and `createPath('/leet/code', 2)` calls to return True. What actually happened was that they both returned False.

#### Screenshots

What OJ returns:
![oj](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/34871949/a4525a7f-c6c1-4cd4-98c2-81d35fe3af2a)

What I see when I use the debugger:
![debug](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/34871949/cca37619-5aa0-4ff7-9ae5-80c078395ac9)

#### Additional context

This issue is already mentioned in the discussion section of the problem by another user.

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team

**Comment by mgoks** [comment]
Hi Pam,
If your judge is running correctly, how do you explain the results I get from the debugger? According to your debugger my code produces the correct result and your judge interprets my code wrong. Also how do you explain [Tony1ee](https://leetcode.com/Tony1ee/)'s code having the same problem?
