### ISSUE TITLE
Code in article fails when array length is zero - 26. Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by saiswa6** [LeetCode-Feedback/LeetCode-Feedback#16620]
#### Category of the bug
- [ ] Solution
- [ ] Test case

#### Description of the bug

The code provided in the article fails when the input array is of zero length. So, add an if condition when the array length is zero, return zero. This needs to be added for all languages. Add this as a testcase also.

#### Code you used for Submit/Run operation

My code works for all cases.
```
class Solution {
    public int removeDuplicates(int[] nums) {
        if(nums.length == 0){
           return 0;
        }
        int n = nums.length;
        int writer = 0, reader = 0;
        for(; reader< n ; reader++)
        {
            if(nums[reader] != nums[writer])
            {
                writer++;
                nums[writer] = nums[reader];
                
            }
        }
        return writer + 1;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Add if block for array length is zero like below
if(nums.length == 0){
    return 0;
}

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The description states that the length of nums is greater than or equal to 1, and there is no case where the length is zero.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
