### ISSUE TITLE
1613. Find the Missing IDs- Incorrect table name

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1663]
#### Your LeetCode username

[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

**Incorrect Table name-**

![image](https://user-images.githubusercontent.com/71989691/102105093-fb58ae00-3e54-11eb-917e-da8fc607c09e.png)

#### Code you used for Submit/Run operation

```
NA
```

#### Language used for code

NA

#### Expected behavior

Table name- Customers

#### Additional context

Problem- https://leetcode.com/problems/find-the-missing-ids/

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
