### ISSUE TITLE
Missing Test Case - 176. Second Highest Salary

### ISSUE THREAD

**Issue by YashMahajan2121** [LeetCode-Feedback/LeetCode-Feedback#16641]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code
<sql

#### Expected behavior

i have got the same output as expected but still my test case has not been passed 

#### Screenshots

<img width="314" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/143541481/066df819-8692-4ac5-bb26-57038979bc02">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The missing test case is in JSON format.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
