### ISSUE TITLE
164. Maximum Gap : Difficulty level is inaccurate

### ISSUE THREAD

**Issue by ShubhamKNIT** [LeetCode-Feedback/LeetCode-Feedback#16645]
#### Your LeetCode username

ShubhamKNIT

#### Category of the bug
- [ ] Question

#### Description of the bug

The question is marked with hard difficulty. But,in this question we have to sort the array and take successive maximum difference b/w two elements in its sorted form. 
Even though someone would do the sorting from scratch without use of library function, it will hardly take 10 minutes. 
That's why I think it should be labelled with lower difficulty like medium or easy, but not hard for this kind of problem.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int maximumGap(vector<int>& nums) {

        if (nums.size() < 2) {
            return 0;
        }
        
        sort(nums.begin(), nums.end());
        int ans = 0;
        
        for (int i = 1; i < nums.size(); i++) {
            ans = max(ans, nums[i] - nums[i - 1]);
        }
        
        return ans;
    }
};
```

```
class Solution {    
    void countSort(vector<int>& nums, int base) {
        
        vector<int> output(nums.size(), 0), count(10, 0);

        // numbers having same base
        for (int i = 0; i < nums.size(); i++) {
            count[(nums[i]/base)%10]++;
        }

        // cummulitive frequency
        for (int i = 1; i < 10; i++) {
            count[i] += count[i - 1];
        }

        // output array
        for (int i = nums.size() - 1; i >= 0; i--) {
            output[count[(nums[i]/base)%10] - 1] = nums[i];
            count[(nums[i]/base)%10]--;
        }

        nums = output;
    }

    void radixSort(vector<int>& nums, int maxi) {
        for (int base = 1; maxi/base > 0; base *= 10) {
            countSort(nums, base);
        }
    }
public:
    int maximumGap(vector<int>& nums) {
        
        int maxi = nums[0];
        for (int i = 0; i < nums.size(); i++) {
            maxi = max(maxi, nums[i]);
        }

        radixSort(nums, maxi);
        
        int ans = 0;
        for (int i = 1; i < nums.size(); i++) {
            ans = max(ans, nums[i] - nums[i - 1]);
        }
        return ans;

    }
};
```

#### Language used for code

C++

#### Screenshots

<img width="706" alt="Screenshot 2023-09-24 at 9 05 27 AM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/121822213/3e7f90db-e047-4dc4-b01b-c817fb49fc46">
<img width="706" alt="Screenshot 2023-09-24 at 9 06 00 AM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/121822213/9a0771d4-c4fe-4101-856c-aad3e1512f0d">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by ShubhamKNIT** [comment]
It was nice to do something meaningful.
