### ISSUE TITLE
Incorrect output for 176. Second Highest Salary

### ISSUE THREAD

**Issue by JY20** [LeetCode-Feedback/LeetCode-Feedback#16642]
MasterPiece20

Solution
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

One of the test cases in solution is incorrect

```
select (select distinct salary from Employee order by salary limit 1 offset 1) as "SecondHighestSalary"
```

MySql

Should be 200 not 100 since its asking for secondhighestsalary

<img width="453" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/43075399/a076e89c-b1c2-49e9-af14-813b4b6ef616">

<img width="250" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/43075399/b5f39cd6-b335-491a-b250-987f7405809f">

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
