### ISSUE TITLE
Missing Test Case - 1613. Find the Missing IDs

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1664]
#### Your LeetCode username

[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

**Missing test case-** 

{"headers": {"Customers": ["customer_id", "customer_name"]}, "rows": {"Customers": [[2, "Alice"],[6, "Alice"], [4, "Bob"], [1000, "Charlie"]]}}

![image](https://user-images.githubusercontent.com/71989691/102107265-8f2b7980-3e57-11eb-8f01-e0670c97cde9.png)

#### Code you used for Submit/Run operation

```
/* Write your T-SQL query statement below */
DECLARE @startnum INT=1
DECLARE @endnum INT=100
;
WITH gen AS (
    SELECT @startnum AS num
    UNION ALL
    SELECT num+1 FROM gen WHERE num+1<=@endnum
    )
SELECT G.NUM AS ids
FROM GEN AS G
WHERE G.NUM <=
    (SELECT MAX(C.CUSTOMER_ID)
    FROM CUSTOMERS AS C)
    AND G.NUM NOT IN
    (SELECT C1.CUSTOMER_ID
    FROM CUSTOMERS AS C1)
```

#### Language used for code

MsSQL

#### Expected behavior

Missing test case-

#### Additional context

Problem- https://leetcode.com/problems/find-the-missing-ids/

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@pratap-082020  This is an invalid test case, please notice that the maximum customer_id will not exceed 100.
