### ISSUE TITLE
Issue with Problem 1251. Average Selling Price

### ISSUE THREAD

**Issue by Danelrf** [LeetCode-Feedback/LeetCode-Feedback#16649]
#### Your LeetCode username
LilaPingvin

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In Problem [1251. Average Selling Price](https://leetcode.com/problems/average-selling-price/), one test case only passes when average_price = 0 whenever a particular existing Product appears on the Price table but not UnitsSold table.

In my opinion, this is wrong, as a lack of sale units does not mean that it's price it 0.

#### Code you used for Submit/Run operation

```
select 
t.product_id,
coalesce(round(sum(t.total_price) / sum(t.units),2),0) as average_price --- This coalesce should not be necessary
from
(select 
p.*,
us.purchase_date,
cast(us.units as float) as units,
cast(p.price * us.units as float) as total_price
from
prices p left join unitsSold us 
on p.product_id = us.product_id  and us.purchase_date between p.start_date and p.end_date) t
group by
t.product_id
```

#### Language used for code
MS SQL Server

#### Expected behavior
Average selling price for products not in UnitsSold table should be null or NA as no units have been sold. A 0 value is misleading.

#### Screenshots
<img width="289" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/16457359/838bfa90-da9f-440c-9c2d-54c2a196221c">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
