### ISSUE TITLE
Missing Test Case - 2867. Count Valid Paths in a Tree

### ISSUE THREAD

**Issue by hairman123** [LeetCode-Feedback/LeetCode-Feedback#16650]
#### Your LeetCode username
newhar

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Test case:
[case.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/12707927/case.txt)

#### Code you used for Submit/Run operation

```c++
#define MAXN ((int) 1e5)

bool inited = false;
bool flag[MAXN + 10];

void init() {
    if (inited) return;
    inited = true;

    memset(flag, 0, sizeof(flag));
    flag[0] = flag[1] = true;
    for (int i = 2; i * i <= MAXN; i++) if (!flag[i]) for (int j = i << 1; j <= MAXN; j += i) flag[j] = true;
}

class Solution {
public:
    long long countPaths(int n, vector<vector<int>>& edges) {
        init();

        vector<int> e[n + 1];
        for (auto &edge : edges) {
            e[edge[0]].push_back(edge[1]);
            e[edge[1]].push_back(edge[0]);
        }

        long long ans = 0;
        int f[n + 1], g[n + 1];
        function<void(int, int)> dfs = [&](int sn, int fa) {
            if (flag[sn]) f[sn] = 1, g[sn] = 0;
            else f[sn] = 0, g[sn] = 1;
            for (int fn : e[sn]) if (fn != fa) {
                dfs(fn, sn);
                ans += f[sn] * g[fn] + g[sn] * f[fn];
                if (flag[sn]) {
                    f[sn] += f[fn];
                    g[sn] += g[fn];
                } else {
                    g[sn] += f[fn];
                }
            }
        };
        dfs(1, 0);
        return ans;
    }
};
```

#### Language used for code
c++

#### Expected behavior
add test case

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

We can't add the test case currently because of technical issues.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
