### ISSUE TITLE
Missing Test Case - 873. Length of Longest Fibonacci Subsequence

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#1665]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution is accepted but fails on the following test case:
[2392, 2545, 2666, 5043, 5090, 5869, 6978, 7293, 7795]

#### Code you used for Submit/Run operation

```
class Solution {
    public int lenLongestFibSubseq(int[] A) {
        Map<Integer,Integer> map = new HashMap<>();
        int [][] dp = new int[A.length][A.length];
        for(int i=0; i<A.length;++i){
            map.put(A[i],i);
            for(int j=i; j<A.length;++j){
                dp[i][j]=2;
            }
        }
        int max = 0;
        for(int i=1; i<A.length;++i){
            for(int j=i+1;j<A.length;++j){
                //find x where A[x]+A[i]=A[j]
                int Ax = A[j]-A[i];
                int index = 0;
                if(!map.containsKey(Ax)){
                    continue;
                }
                index = map.get(Ax);
                dp[i][j]=Math.max(dp[i][j],dp[index][i]+1);
                max=Math.max(dp[i][j],max);
            }
        }
        return max;
    }
}
```

#### Language used for code

Java

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/102155115-dcecb580-3e48-11eb-83aa-a1f7fb29738a.png)

#### Additional context

https://leetcode.com/problems/length-of-longest-fibonacci-subsequence/discuss/152476/Java-DP-with-explanation-O(n2)-time-O(n2)space

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
