### ISSUE TITLE
Missing Test Case - 395. Longest Substring with At Least K Repeating Characters

### ISSUE THREAD

**Issue by cascadia-long** [LeetCode-Feedback/LeetCode-Feedback#16659]
#### Your LeetCode username

chasemtv

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

wrong answer can pass due to missing test case

#### Code you used for Submit/Run operation

class Solution {
public:
    int longestSubstring(string s, int k) {
        int ans = 0;
        for (int m = 0; m < 26; ++m) {
            vector<int> cnt(26, 0);
            int unique = 0;
            int unique_with_k = 0;
            for (int i = 0, j = 0; j < s.length(); ++j) {
                if (++cnt[s[j] - 'a'] == 1) {
                    ++unique;
                }
                if (cnt[s[j] - 'a'] == k) {
                    ++unique_with_k;
                }
                while (i < s.length() && unique > m) {       
                    if (cnt[s[i] - 'a'] == k) {
                        --unique_with_k;
                    }                                  
                    if (--cnt[s[i] - 'a'] == 0) {
                        --unique;
                    }
                    ++i;                  
                }
                if (unique == m && unique_with_k == m) {
                    ans = max(ans, j - i + 1);
                }
            }
        }
        return ans;
    }
};

#### Language used for code

C++

#### Expected behavior

As we only check unique chars from 0 to 25 in the above code ( for (int m = 0; m < 26; ++m)),
if a substring with all 26 lower case letters where each letter repeats at least k times  (i.e. a substr which meets the requirement),
the above code should fail.
One such test case would be:
s="abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz"
k=2
expected answer is 52
The correct code  should make m : 1-26 i.e.  change above line to "for (int m = 1; m <= 26; ++m)"

If we run the above code with this test case manually, it shows Wrong Answer as expected since the above code outputs 0.
But the submission of the same code got Accepted.
So we should add this test case for submission check.
Please see attached screenshots below.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/82807960/a3364bf0-617e-43a5-a47b-c48abebac355)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/82807960/2e7dce77-b0a1-479d-a4c5-df26c1b9d237)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/82807960/7022ccc9-27c4-47a1-8e65-9b5ee9080862)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by cascadia-long** [comment]
The code submission Accepted link for the wrong code:
https://leetcode.com/problems/longest-substring-with-at-least-k-repeating-characters/submissions/1057768133/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
