### ISSUE TITLE
Missing Test Case - 1163. Last Substring in Lexicographical Order

### ISSUE THREAD

**Issue by Andrew-Angrew** [LeetCode-Feedback/LeetCode-Feedback#16658]
#### LeetCode username:
[Andrew-Angrew](https://leetcode.com/Andrew-Angrew)

#### Category of the bug:
- [ ] Missing Test Cases 

#### Description of the bug
One of the fastest solutions to the problem on the cite is actually wrong. It passes all current test cases and I propose a new test case on which it fails.

#### Code of wrong solution:

```
class Solution:
    def lastSubstring(self, s: str) -> str:
        index = {c: i for i, c in enumerate(sorted(set(s)))}
        radix, val, cur, lo = len(index), 0, 0, 0
        for i in range(len(s) - 1, -1, -1):
            cur = index[s[i]] + cur / radix
            if cur >= val:
                lo, val = i, cur
        return s[lo:]
```

#### Language used for code
Python 3

#### Missing testcase:
Short pythonic description: "z" * 99 + "a" + "z" * 99 + "b"
plain text: "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzazzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzb"

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
