### ISSUE TITLE
剑指 Offer 38. 字符串的排列

### ISSUE THREAD

**Issue by TankNee** [LeetCode-Feedback/LeetCode-Feedback#1667]
**Bug 类型**
- [X] 题目
- [ ] 题解
- [X] 编程语言

**描述**
同样的测试用例，控制台测试结果和提交测试结果不同

**你使用的语言**
JavaScript

**你提交或者运行的代码**
```JavaScript
let charArray = [];
let result = [];
/**
 * @param {string} s
 * @return {string[]}
 */
var permutation = function (s) {
    charArray = s.split("");
    dfs(0);
    return result;
};
/**
 * @param {number} index
 */
var dfs = function (index) {
    if (index === charArray.length - 1) {
        result.push(charArray.join(""));
        return result;
    }
    const map = new Map();
    for (let i = index; i < charArray.length; i++) {
        // const element = charArray[i];
        if (map.has(charArray[i])) continue;
        map.set(charArray[i]);
        swap(i, index);
        dfs(index + 1);
        swap(index, i);
    }
};
/**
 *
 * @param {number} a
 * @param {number} b
 */
var swap = function (a, b) {
    let temp = charArray[a];
    charArray[a] = charArray[b];
    charArray[b] = temp;
};
```

**期望行为**
一致的输出

**屏幕截图**
![image](https://user-images.githubusercontent.com/43956168/102180247-7f597700-3ee3-11eb-90c0-95e9ab20bd43.png)

**Reference**
https://leetcode-cn.com/problems/zi-fu-chuan-de-pai-lie-lcof/submissions/

**Comment by feiceh** [comment]
你好，建议再仔细调试一下代码，希望这篇内容对你有帮助：https://leetcode.kf5.com/hc/kb/article/1194344/。 后续刷题学习中遇到困难，可通过阅读「题解」解决做题中的一些困惑，可以看看其他小伙伴的解题思路。

**Comment by TankNee** [comment]
> 你好，建议再仔细调试一下代码，希望这篇内容对你有帮助：[https://leetcode.kf5.com/hc/kb/article/1194344/。](https://leetcode.kf5.com/hc/kb/article/1194344/%E3%80%82) 后续刷题学习中遇到困难，可通过阅读「题解」解决做题中的一些困惑，可以看看其他小伙伴的解题思路。
![image](https://user-images.githubusercontent.com/43956168/102182166-c7c66400-3ee6-11eb-817d-9af1f46e645a.png)
