### ISSUE TITLE
2261. K Divisible Elements Subarrays - Typo in Question

### ISSUE THREAD

**Issue by agrawalishaan** [LeetCode-Feedback/LeetCode-Feedback#16674]
#### Your LeetCode username
agrawalishaan

#### Category of the bug
- [ X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the question, it writes:
<img width="591" alt="Screenshot 2023-09-24 at 2 56 53 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/113543798/bdd70c53-e572-4c81-83f0-569b8ec7ea8b">
There are two spaces after `are`, there should be one.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
