### ISSUE TITLE
Missing Test Case - 1470. Shuffle the Array

### ISSUE THREAD

**Issue by jahangircsebuet** [LeetCode-Feedback/LeetCode-Feedback#16678]
username: jahangir67

#### Code you used for Submit/Run operation

```
// Shuffle the Array
class Solution:
    def shuffle(self, nums: List[int], n: int) -> List[int]:
        nums_length = len(nums)
        num1 = nums[0:int(len(nums)/2)]
        num2 = nums[int(len(nums)/2):]
        i = 0
        for idx, num in enumerate(nums):
            if idx%2==0:
                nums[idx] = num1[i]
                i = i + 1
        i = 0
        for idx, num in enumerate(nums):
            if idx%2==1:
                nums[idx] = num2[i]
                i = i + 1
        return nums
```

#### Language used for code

python3

#### Expected behavior

input: 
nums = [1,1], n = 1
output: [1, 1]

input: 
nums = [1, 2], n = 1
output: [1, 2]

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The judge working correctly. 
input:
nums = [1,1], n = 1
output: [1, 1]

input:
nums = [1, 2], n = 1
output: [1, 2]

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
