### ISSUE TITLE
603. Consecutive Available Seats - Incorrect testcases in pandas

### ISSUE THREAD

**Issue by PSwicarz** [LeetCode-Feedback/LeetCode-Feedback#16689]
#### Your LeetCode username
piocarz

#### Category of the bug
- [x ] Question
- [x ] Language

#### Description of the bug
It seems like pandas test cases are wrong - they all have only `True` in one column instead of `1`/`0` or `True`/`False`

#### Code you used for Submit/Run operation
```
import pandas as pd

def consecutive_available_seats(cinema: pd.DataFrame) -> pd.DataFrame:
    return cinema
```

#### Language used for code
pandas

#### Expected behavior
it should give back `0`/`1` or `True`/`False` , 

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/99476222/5bcb6681-d3b3-4de8-9268-93d5d0ce8d6a)

#### Additional context
Without it its impossible to solve problem. It looks like you assigned bool to it instead of integer, and it may be the root of problem.

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
