### ISSUE TITLE
Missing Test Case - 973. K Closest Points to Origin

### ISSUE THREAD

**Issue by aaron-c-zhao** [LeetCode-Feedback/LeetCode-Feedback#1668]
#### Your LeetCode username

aaronzhao_delft

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Edge cases not covered. When the points are identical and k equals the number of points, there's still a unique solution. But the code in approach 2 will cause the time limit exceed due to an infinite loop.

#### Code you used for Submit/Run operation

```
class Solution {
    int[][] points;
    public int[][] kClosest(int[][] points, int K) {
        this.points = points;
        sort(0, points.length - 1, K);
        return Arrays.copyOfRange(points, 0, K);
    }

    public void sort(int i, int j, int K) {
        if (i >= j) return;
        int k = ThreadLocalRandom.current().nextInt(i, j);
        swap(i, k);

        int mid = partition(i, j);
        int leftLength = mid - i + 1;
        if (K < leftLength)
            sort(i, mid - 1, K);
        else if (K > leftLength)
            sort(mid + 1, j, K - leftLength);
    }

    public int partition(int i, int j) {
        int oi = i;
        int pivot = dist(i);
        i++;

        while (true) {
            while (i < j && dist(i) < pivot)
                i++;
            while (i <= j && dist(j) > pivot)
                j--;
            if (i >= j) break;
            swap(i, j);
        }
        swap(oi, j);
        return j;
    }

    public int dist(int i) {
        return points[i][0] * points[i][0] + points[i][1] * points[i][1];
    }

    public void swap(int i, int j) {
        int t0 = points[i][0], t1 = points[i][1];
        points[i][0] = points[j][0];
        points[i][1] = points[j][1];
        points[j][0] = t0;
        points[j][1] = t1;
    }
}
```

#### Language used for code

java

#### Expected behavior

Test case:
[[0, 1],[0, 1], [0, 1], [0, 1], [0, 1]]
5
Expected output:
[[0, 1],[0, 1], [0, 1], [0, 1], [0, 1]]
Actual output by the code in solution approach 2:
Time limit exceeded.

#### Additional context

The bug is due to a missing = in the second inner while loop in the partition method.

**Comment by lc-kay** [comment]
@aaron-c-zhao Even without your suggested test case, the Java solution in Approach 2 already receives TLE. I've relayed this to our team to investigate.

**Comment by lc-kay** [comment]
Hi @aaron-c-zhao 
Thank you for your time. We've noted your feedback and will update the solution article soon.
