### ISSUE TITLE
Missing Test Case - 14. Longest Common Prefix

### ISSUE THREAD

**Issue by dushyant0007** [LeetCode-Feedback/LeetCode-Feedback#16688]
#### Category of the bug
- [ ] Question
- [ 1] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The output and expected are same still the solution is not accepted 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    string longestCommonPrefix(vector<string>& strs) {
        
        if(strs.size() < 2)
            return strs[0];

        string ans = "";
        
        

        for(int i = 0 ; i < strs.size()  ; i++){
            for(int j = 0 ; j < strs.size() - 1; j++){
                if(strs[j][i]!=strs[j+1][i])
                    return ans;
            }
            ans+=strs[0][i];
        }        

    return ans;
    }
};
```

#### Screenshots

<img width="786" alt="Screenshot 2023-09-25 at 1 16 28 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/44732347/61ea2ff3-ad13-4375-8ed2-d7f51a7e5385">

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
