### ISSUE TITLE
A minor typo in Arrays 101 explore card

### ISSUE THREAD

**Issue by aleksandr-kiliushin** [LeetCode-Feedback/LeetCode-Feedback#16687]
#### Your LeetCode username
aleksandr-kiliushin

#### URL
https://leetcode.com/explore/learn/card/fun-with-arrays/511/in-place-operations/3256/

#### Screenshots
<img width="1394" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/65129988/c6115a79-d869-4496-b625-ecf58d59f0da">

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
