### ISSUE TITLE
Existing test casesLCR 126. 斐波那契数

### ISSUE THREAD

**Issue by Xiong-YH** [LeetCode-Feedback/LeetCode-Feedback#16697]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
n = 45时，预期结果出错，在509上结果成功

**你使用的语言**
JavaScript
**你提交或者运行的代码**
```
const f = []
var fib = function(n) {
    if(n == 0) return 0
    if(n == 1) return 1
    if(f[n] === undefined) {
       f[n] = fib(n-1) + fib(n-2)
    }
    return f[n]
}

```

**期望行为**
n = 45时，预期结果应为1134903170

**屏幕截图**
![}8PQ)}1(DXN UEY@8~VAM1](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/99244399/48f51f73-82c5-4821-95e1-cfc65e52b4a3)

**额外的上下文**
添加额外的上下文信息

**Comment by amcones** [comment]
您好，在与相关团队核实后：***不处理***（需要对答案进行取模）。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
