### ISSUE TITLE
Test case contribution for problem 1008

### ISSUE THREAD

**Issue by a-jumani** [LeetCode-Feedback/LeetCode-Feedback#167]
**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
In problem 1008 (Construct Binary Search Tree from Preorder Traversal), implementation with a bug is passing all test cases. Test case [8, 5, 1, 7, 10, 2147483647] reveals it. Bug is the use of `preorder[i] >= stop` instead of `preorder[i] > stop` in the implementation below.

**what language is your code written in**
C++

**The code you submit/run**
```
TreeNode* bst_rec(const vector<int>& preorder, int &i, int stop) {
    // base case
    if ( i == preorder.size() || preorder[i] >= stop )
        return nullptr;
    
    TreeNode *root = new TreeNode(preorder[i++]);
    root->left = bst_rec(preorder, i, root->val);
    root->right = bst_rec(preorder, i, stop);
    return root;
}
TreeNode* bstFromPreorder(vector<int>& preorder) {
    int i = 0;
    return bst_rec(preorder, i, INT_MAX);
}
```

**Expected behavior**
It should've failed.

**Comment by CooperCooperCooper** [comment]
Hi @a-jumani,
Thank you for reaching out to us! I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @a-jumani,
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
