### ISSUE TITLE
Language typo

### ISSUE THREAD

**Issue by vincentvalton** [LeetCode-Feedback/LeetCode-Feedback#16709]
#### Category of the bug
- [ ✔️ ] Language

#### Description of the bug
Language need fix for text description of algorithm on page: 
https://leetcode.com/explore/interview/card/leetcodes-interview-crash-course-data-structures-and-algorithms/703/arraystrings/4501/

Text says: 
- "[...] it's like we're discard the character since it's not useful. [...]" 

Needs to be replaced with either: 
- [...] it's like _we're discard**ing**_ the character since it's not useful [...]" 
or 
- "[...] it's like _**we discard**_ the character since it's not useful [...]"

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback. 

Please provide us with your username.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
