### ISSUE TITLE
Missing Test Case - 456. 132 Pattern, this code works correctly but when ! submit it on leetcode it doesn't work

### ISSUE THREAD

**Issue by Ajob41** [LeetCode-Feedback/LeetCode-Feedback#1670]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@Ajob41 Please provide the code and the test case it failed on. Thank you!

**Comment by Ajob41** [comment]
the test case is this array [3,1,4,2]

**Comment by lc-kay** [comment]
@Ajob41 Please also provide the accepted code that this test case failed on.

**Comment by Ajob41** [comment]
Sure, here it is. let nums = [-1,3,2,0]
let n = 0

let find132pattern = function(nums){
    let number = []
    for(let i = 0; i < nums.length; i++){
        for(let j = 0; j < nums.length;j++){
            if(i !== j){
                if(j < i){
                    if(nums[j] < nums[i]){
                        let left = nums.slice(0,i)
                        let right = nums.slice(i+1,nums.length)
                        if(right.length < 1){
                            break
                        }
                        for(let l = 0; l < left.length;l++){
                           let lt = left[l]
                           let mid = nums[i]

                           for(let r = 0; r < right.length; r++){
                               let rt = right[r]
                               let is_true = mid > lt && rt > lt && mid > rt

                               if(is_true){
                                   n++
                                   if(n === 1){
                                       return true
                                   }
                               }


                           }
                        }
                        break
                    }
                }
            }
        }
    }
   return false
}

console.log(find132pattern(nums))

**Comment by lc-kay** [comment]
@Ajob41 I apologize for the inconvenience, but please provide the submission details link so I can better replicate the issue.

**Comment by lc-kay** [comment]
Hi @Ajob41 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.

**Comment by Ajob41** [comment]
Thank you for your response, I will leave a comment when I gain intrest
again.
