### ISSUE TITLE
112. Path Sum -- Incorrect Picture in Editorial Solution Slides

### ISSUE THREAD

**Issue by Ming91** [LeetCode-Feedback/LeetCode-Feedback#16701]
#### Your LeetCode username

[wming9310](https://leetcode.com/wming9310)

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In `Approach 2: Iterations` part of the editorial solution of problem [112. Path Sum](https://leetcode.com/problems/path-sum/):
The element in the stack should be (8, 9) as it should be (8, 17 - 8), rather than (8, 11). 

#### Screenshots

![Screenshot 2023-09-25 132731](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/3740139/70e07381-4380-436c-a75f-be244363b390)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
