### ISSUE TITLE
Missing Test Case - 20. Valid Parentheses

### ISSUE THREAD

**Issue by akhilj210f** [LeetCode-Feedback/LeetCode-Feedback#16707]
#### Your LeetCode username

[A3YN Gaming](https://leetcode.com/a3yngaming)

#### Category of the bug
 Missing Test Cases 

#### Description of the bug

Missing one test case

#### Code you used for Submit/Run operation

```
public class Solution {
    public bool IsValid(string s) 
    {
        try
        {
            char[] Data = s.ToCharArray();
            if(s.Length %2 !=0) return false;
            
            Stack<char> Memory = new();
            for(int i = 0;i<s.Length;i++)
            {                                                 
                char ch = Data[i];
                if(ch == '{' || ch == '(' || ch == '[')
                {
                    Memory.Push(ch);
                }
                else if(Memory.Count !=0)
                {
                    if((ch == ']' && Memory.Peek() == '[') ||(ch == '}' && Memory.Peek() == '{') || (ch == ')' && Memory.Peek() == '('))
                    {
                        Memory.Pop();
                    }
                    else
                    {
                        Memory.Push(ch);
                    }
                }
                else
                {
                    Memory.Push(ch);
                }
            }
            if(Memory.Count == 0)
            {
                return true;
            }
            else
            {
                return false;
            }            
        }
        catch(Exception)
        {
            return false;
        }
    }
}

```

#### Language used for code
 C#

#### Expected behavior

Input : s = "}{"

output = false;

expected = true;     // as Every close bracket has a corresponding open bracket of the same type.(mentioned in problem condition).

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/77722548/26ae8fde-a725-4dd5-aefc-4f0a7296091d)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
