### ISSUE TITLE
Missing Test Case - 389. Find the Difference

### ISSUE THREAD

**Issue by lauf8** [LeetCode-Feedback/LeetCode-Feedback#16706]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
I make the challenger using py, and the answer is correct, but I using list and that include "[]" the answer, making the answer
ser incorrect

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution(object):
    def findTheDifference(self, s, t):
        list_s = []
        list_t = []
        for x in s:
            list_s.append(x)
        for x in t:
            list_t.append(x)           
        for x in list_s:
            list_t.remove(x)   
        return(list_t) 
```

#### Language used for code
Python

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
