### ISSUE TITLE
941. Valid Mountain Array ( It's showing verdict Accepted for wrong answer )

### ISSUE THREAD

**Issue by sifat009** [LeetCode-Feedback/LeetCode-Feedback#1671]
#### Category of the bug
 ✅ Solution

#### There is a problem in your test case checker for javaScript. This submission should get the wrong answer instead it's accepted. 

Here is my submission [link](https://leetcode.com/submissions/detail/429220432/)

#### Code you used for Submit/Run operation

```
/**
 * @param {number[]} arr
 * @return {boolean}
 */
var validMountainArray = function (arr) {
  if (arr.length < 3) return false;
  if (arr[0] >= arr[1]) return false;
  let up = true;

  for (let i = 1; i < arr.length; i++) {
    const [curr, prev] = [arr[i], arr[i - 1]];
    if (curr < prev) up = false;
    // if (curr === prev) return false; This line should be enabled to get (AC)
    if (!up && curr >= prev) return false;
  }
  if (up) return false;
  return true;
};
```

#### Expected Behaviour
/**
 * input: [0, 2, 3, 3, 5, 2, 1, 0]
 * output: true
 * expected-output: false
 *
 */

[![wrong.png](https://i.postimg.cc/c19Zk9Bp/wrong.png)](https://postimg.cc/QVTRHqPm)

But getting accepted when submit: 

[![submission.png](https://i.postimg.cc/BvmMh2xp/submission.png)](https://postimg.cc/kVtQG6YR)

**Comment by lc-kay** [comment]
@sifat009 I just submitted your code to replicate the problem, however, it resulted in a Wrong Answer. 
<img width="723" alt="Screen Shot 2020-12-16 at 11 49 44 AM" src="https://user-images.githubusercontent.com/70870126/102399002-dd926280-3f94-11eb-8ce6-0c911bff311b.png">
