### ISSUE TITLE
316. Remove Duplicate Letters - return value of editorial

### ISSUE THREAD

**Issue by naphtul** [LeetCode-Feedback/LeetCode-Feedback#16718]
#### Your LeetCode username
naphtul

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In question 316. Remove Duplicate Letters on the editorial:
Approach 2: Greedy - Solving with Stack
Python
```python
def removeDuplicateLetters(self, s) -> int:
```

#### Language used for code
python3

#### Expected behavior
The return value should be `str` and not `int`.
```python
def removeDuplicateLetters(self, s) -> str:
```

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
