### ISSUE TITLE
Missing Test Case - 83. Remove Duplicates from Sorted List

### ISSUE THREAD

**Issue by dengchun** [LeetCode-Feedback/LeetCode-Feedback#16714]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [*] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution:
    def deleteDuplicates(self, head: Optional[ListNode]) -> Optional[ListNode]:
        slow = ListNode(-1)
        fast = ListNode(-1)
        slow.next = head
        fast.next = head
        while fast:
            if slow.val!=fast.val:
                slow.next = fast
                slow = slow.next
            fast = fast.next
        slow.next = None
        return head
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by dengchun** [comment]
the language is Python

test case which start with "-1,-1", such as [-1,-1,1,2,2,3]

sorry for missing imformation, I'm a beginner of github

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
