### ISSUE TITLE
Missing Testcase for the problem 2867. Count Valid Paths in a Tree

### ISSUE THREAD

**Issue by siddharthsinghvats** [LeetCode-Feedback/LeetCode-Feedback#16721]
#### Your LeetCode username

neembu_mirch

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
A wrong code is accepted for the problem **[2867. Count Valid Paths in a Tree](https://leetcode.com/problems/count-valid-paths-in-a-tree/)** that with this test case gives a time limit exceeded verdict.

#### Code you used for Submit/Run operation

```
const int N = 100005;
bool prime[N];

#define ll long long
void seive(){
    for(int j = 2;j<N;j++) prime[j] =1;
    for(long i = 2;i*i<=N-1;i++){
        if(prime[i]){
            for(long j = i*i;j<=N-1;j+=i){
                prime[j] = 0;
            }
        }
    }
    
}

class Solution {
public:
    vector<ll> adj[N], store[N];
    ll dfs(int i ,int p, int curp){
        ll cur = 1;
        vector<int> v;
        for(auto j:adj[i]){
            if(j==p) continue;
            if(prime[j]) continue;
            ll x = dfs(j,i,curp);
            if(x)store[i].push_back(x);
            cur+=x;       
        }
        for(auto y:v) store[i].push_back(y);
        return cur;
       
    }
    long long countPaths(int n, vector<vector<int>>& edges) {
        ios_base::sync_with_stdio(false);
        cin.tie(0);
        cout.tie(0);
        if(n==1) return 0;
        if(prime[2]==0){
            seive();
        }
        for(auto v:edges){
            adj[v[0]].push_back(v[1]);
            adj[v[1]].push_back(v[0]);
        }
         if(adj[1].size()==n-1){
            ll cnt =0;
            for(int i = 1;i<=n;i++){
                if(!prime[i]) cnt++;
            }
            return cnt*(n-cnt);
        }
        for(int i = 1;i<=n;i++){
            if(prime[i]){
                dfs(i,-1,i);
            }
        }
        ll ans = 0;
        
        for(int i = 1;i<=n;i++){
            if(!prime[i]||!store[i].size()) continue;
            ll cur = 1;
            ll p =0;
         
            ll sum=0;
            for(auto x: store[i]){ 
                ans+=sum*x;
                sum+=x;
                p+=x;
            }
           
            ans+=p;
        }
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

This code passed the existing test cases but with the new test case it is giving Time Limit Exceeded verdict.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/95075464/d9b02b24-7540-4be2-9b04-830b07fa0331)

#### Missing Testcase
100000 nodes ( a star graph with 4 as center)
[testcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/12728465/testcase.txt)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by siddharthsinghvats** [comment]
@LC-Pam any updates over it?

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

We can't add the test case currently because of technical issues.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by siddharthsinghvats** [comment]
Why won't it be considered a valid test case?
