### ISSUE TITLE
Missing Test Case - 1207. Unique Number of Occurrences

### ISSUE THREAD

**Issue by Li0nhunter** [LeetCode-Feedback/LeetCode-Feedback#16727]
#### Your LeetCode username

 li0nhunter

#### Category of the bug
- [ ] Missing Test Cases 
 missing test case there is no test case to insure that a solution using an array instead of a hashmap stays within the bounds of the constraints.

#### Code you used for Submit/Run operation

```java
// 1207. Unique Number of Occurrences
class Solution {
    public boolean uniqueOccurrences(int[] arr) {
        int[] occurrenceMap = new int[2001];
        List<Integer> mapIndices = new ArrayList<>();
        Set<Integer> occurrences = new HashSet<>();
        for(int i : arr){
            occurrenceMap[i+1000]++;
            if(occurrenceMap[i+1000]==1)mapIndices.add(i);
        }
        for(int i : mapIndices){
            if(occurrences.contains(occurrenceMap[i+1000])) return false;
            occurrences.add(occurrenceMap[i+1000]);
        }
        return true;
    }
}
```

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/42687692/84ea1ccc-71f8-4686-9afc-f68720214ac7)

#### Additional context

i just added my own insurance testcase of [-1000, -1000, 1000] with the expected result true.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

[-1000, -1000, 1000] already exists. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
