### ISSUE TITLE
Missing Test Case - 300. Longest Increasing Subsequence

### ISSUE THREAD

**Issue by ShalyginaA** [LeetCode-Feedback/LeetCode-Feedback#16723]
#### Your LeetCode username

Inkeronia

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

Missing test case. My solution is accepted but it is wrong on my test case

#### Code you used for Submit/Run operation

```
class Solution:
    def lengthOfLIS(self, nums: List[int]) -> int:
        nums = [-10_000] + nums
        n = len(nums)

        @cache
        def rec(i): 
            if i >= n:
                return 0
            
            result = 1
            for j in range(i + 1, n):
                if nums[j] > nums[i]:
                    result = max(result, 1 + rec(j))
            return result

        return rec(0) - 1
```

#### Language used for code

Python3

#### Expected behavior

Expected answer 1, my output is 0

**Comment by ShalyginaA** [comment]
Sorry. The testcase is [-10000]

**Comment by ShalyginaA** [comment]
![Uploading Screenshot 2023-09-26 at 22.14.08.png…]()

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
