### ISSUE TITLE
Missing Test Case - 26. Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by mirajhad** [LeetCode-Feedback/LeetCode-Feedback#1673]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@mirajhad Please provide the accepted code and the missing test case. Thank you!

**Comment by mirajhad** [comment]
@lc-kay 
// Time:  O(n)
// Space: O(n)

class Solution {
public:
    vector<int> twoSum(vector<int>& nums, int target) {
        unordered_map<int, int> lookup;
        for (int i = 0; i < nums.size(); ++i) {
            if (lookup.count(target - nums[i])) {
                return {lookup[target - nums[i]], i};
            }
            lookup[nums[i]] = i;
        }
        return {};
    }
};

**Comment by lc-kay** [comment]
@mirajhad Please also provide the missing test case. Thank you!

**Comment by mirajhad** [comment]
@lc-kay 
It is possible to show test case ??
