### ISSUE TITLE
Invalid test case in Summary Ranges (228) problem

### ISSUE THREAD

**Issue by pubudu91** [LeetCode-Feedback/LeetCode-Feedback#16733]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The question clearly states that the input array is sorted in the ascending order. But there's an incorrect test case which causes our solution to be incorrectly judged as incorrect. The incorrect test case in question: `[2, -1]`. I see that there have been multiple reports against this test case but NO action taken except blindly closing them.

#### Expected behavior

There should not have been a test case like `[2, -1]`

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
