### ISSUE TITLE
Missing Test Case - 880. Decoded String at Index

### ISSUE THREAD

**Issue by mullachv** [LeetCode-Feedback/LeetCode-Feedback#16731]
#### Your LeetCode username
mullachv

#### Category of the bug
- [ ] Question
- [ X] Solution
- [ ] Language
- [ X] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution(object):
    def decodeAtIndex(self, S, K):
        size = 0
        # Find size = length of decoded string
        for c in S:
            if c.isdigit():
                size *= int(c)
            else:
                size += 1

        for c in reversed(S):
            K %= size
            if K == 0 and c.isalpha():
                return c

            if c.isdigit():
                size /= int(c)
            else:
                size -= 1
```

#### Language used for code
Python3

#### Expected behavior
Custom testcase:
```
s = "a23b456789gh9999pqrs9999u99a9xyzpqrstuvw9"
k = 76797
```
The code above is the supplied Python3 code. Code must output the correct response: "b"

#### Screenshots
However the output produced is ```null```

#### Additional context
The fix is to use integer division:
```
size //= int(c)
```

**Comment by mullachv** [comment]
Please add the testcase and correct the official solution response

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by mullachv** [comment]
The editorial solution is not fixed yet on LC, as suggested by this issue
