### ISSUE TITLE
1071. Greatest Common Divisor of Strings

### ISSUE THREAD

**Issue by rjbroussard** [LeetCode-Feedback/LeetCode-Feedback#16734]
#### Your LeetCode username
rjbroussard

#### Category of the bug
- [ X ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The Definition of the problem very much contradicts the First Example.
Problem: 

For two strings s and t, we say "t divides s" if and only if s = t + ... + t (i.e., t is concatenated with itself one or more times).
Given two strings str1 and str2, return the largest string x such that x divides both str1 and str2.

Example 1:
Input: str1 = "ABCABC", str2 = "ABC"
Output: "ABC"

How they contradict:
The word "divides" here is defined as:   s = t + ... + t (i.e., t is concatenated with itself one or more times).
so the minimum string that s can be is s = t+t as  "t is concatenated with itself one or more times"

Next, the words  "string x such that x divides both str1 and str2" can be written 
 str1 is at least x+x and str2 is at least x+x, based on the above.

In the First Example x is given as "ABC" and str2 is given as also "ABC"
BUT
str2 has to be at least two copies of x based on the words in the problem statement and this is not the case. 
str2 in Example 1 is equal to just str1=x or in other terms s=t which is not s= t+...+t.

This contradicts the problem statement.

#### Code you used for Submit/Run operation

```
// NONE Needed
};
```

#### Language used for code
None

#### Expected behavior
The problem statement need to be updated to include accurate language to represent the correct examples.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Please ask your question in the discussion forum.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
