### ISSUE TITLE
Question should be more clear - 1669.Merge In Between Linked Lists

### ISSUE THREAD

**Issue by mdabdulrahman** [LeetCode-Feedback/LeetCode-Feedback#16747]
#### Category of the bug
- [ ] Question

#### Description of the bug

In the question  "**_Remove list1's nodes from the ath node to the bth node, and put list2 in their place_**." Is it saying **nodes having value a to b** should be removed or telling the **index position of a to b** .  when a user reads it will definitely confusing.
Actually it is removed by index value.

#### Code you used for Submit/Run operation

```
//Merge In Between Linked Lists
class Solution {
public:
    ListNode* mergeInBetween(ListNode* list1, int a, int b, ListNode* list2) {
        ListNode* prev = list1;
        ListNode* curr;
        ListNode* start;
        curr = list1;
        int i = 0;
        while( curr!=NULL ) {
            if( i == a )
              start = prev;
            if( i == b ) 
              break;
            prev = curr;
            curr = curr->next; 
            i++;
        }
        start->next = list2;
        while( list2->next != NULL ) 
            list2 = list2->next;
        list2->next = curr->next;
        return list1;
        

    }
};
```

#### Language used for code
C++

#### Expected behavior

Should clearly define **"a"** and **"b"** is the 0 **Indexed Postition** and to have one example testcase in question to illustrate it is removed by index value.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Please ask your question in the discussion forum.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
