### ISSUE TITLE
Missing Test Case - 979. Distribute Coins in Binary Tree ( Testcase not sufficient, Code in Solution tab [java/python] is wrong)

### ISSUE THREAD

**Issue by dipeshsah** [LeetCode-Feedback/LeetCode-Feedback#1674]
[

#### Your LeetCode username

UserName : eagerToCode

#### Category of the bug
- [] Solution in solution tab is wrong as well as testcase not sufficient

#### Description of the bug

Insufficient test case, Code get submitted even when there is one testcase that will fail.

#### Code you used for Submit/Run operation

```
class Solution {
    int ans;
    public int distributeCoins(TreeNode root) {
        ans = 0;
        dfs(root);
        return ans;
    }

    public int dfs(TreeNode node) {
        if (node == null) return 0;
        int L = dfs(node.left);
        int R = dfs(node.right);
        ans += Math.abs(L) + Math.abs(R);
        return node.val + L + R - 1;
    }
}
```

#### Language used for code

Java

#### Expected behavior

[1,0,0,0,0,0,5]
For this input, the code will fail but it got submitted successfully.

#### Screenshots

I will attach the screen shot.

#### Additional context

I wrote code and it passed, Since I am premium subscriber which has one major advantage of referring solution. The solution code is incorrect. How should I trust the solution that I saw in past or in future ? When you run the test case for the above code which is copied from the Solution tab. Normally, I write code and then refer Solution tab for optimization or different approach. I wrote different code and it passed all the test including this new test case. But the code mentioned in Solution tab for this question is wrong. Since it will fail for the above testcase, but will get submitted. I know I will get 100 points for the testcase. But you should consider for the wrong solution which is unfair for premium account holder like me. You should definitely provide more points. I don't really know which solution in Solution tab is wrong. I have been paying for premium account from last 8 months. I am still a newcomer so can't judge the code written in Solution tab. Even the explanation in solution tab for the code under "Algorithm" section is incorrect. It explains the exact code which does not work for all the testcase. Please do replace the solution with something like below and feel free to contact me in case you need more clarification.

```
class Solution {
public:
    int ans =0;
    int distributeCoins(TreeNode* root) 
    {
        dfsExcess(root);  
        return ans;
    }    
    int dfsExcess(TreeNode* root)
    {
        if(root == NULL) return 0;
        int lExcess = dfsExcess(root->left);
        int rExcess = dfsExcess(root->right);
        int curVal = root->val + lExcess + rExcess -1;
        ans += abs(curVal);
        return curVal;
    }
};
```
![IssueLeetCode](https://user-images.githubusercontent.com/64785068/102263683-8fd21780-3f0c-11eb-919b-0e78c3079428.JPG)

**Comment by dipeshsah** [comment]
Even the python solution mentioned in Solution tab will fail for this testcase.

**Comment by lc-kay** [comment]
Hi @dipeshsah 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @dipeshsah 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
