### ISSUE TITLE
Missing Test Case - 1172. Dinner Plate Stacks

### ISSUE THREAD

**Issue by el-hopaness-romtic** [LeetCode-Feedback/LeetCode-Feedback#16769]
#### Your LeetCode username
el-hopaness-romtic

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
No testcases to check if:
+ `popAtStack()` works for a last stack that is not full
+ `popAtStack()` history is working correctly in the `push()` method after `pop()`

#### Code you used for Submit/Run operation
```
class DinnerPlates {
public:
    vector<int> stack;
    priority_queue<int, vector<int>, greater<int>> pq;
    int size;
    DinnerPlates(int capacity) {
        size=capacity;
    }
    
    void push(int val) {
        if(!pq.empty()) {
            stack[pq.top()]=val;
            pq.pop();
            return;
        }
        stack.push_back(val);
    }
    
    int pop() {
        if(stack.size()==0) {
            return -1;
        }
        while(stack[stack.size()-1]==-1) {
            if(stack.size()-1==pq.top()) {
                pq.pop();
            } 
            stack.pop_back();
        }
        int temp=stack[stack.size()-1];
        stack.pop_back();

        return temp;
    }
    
    int popAtStack(int index) {
        int endId=index*size+size-1;
        if(endId>=stack.size()) {
            return -1;
        }
        int temp=-1;
        while(endId>=index*size && temp==-1) {
            temp=stack[endId--];
        }
        if(temp!=-1) {
            pq.push(endId+1);
            stack[endId+1]=-1;
        }
        return temp;
    }
};
```
(sample 187.826 MB submission, couldn't get a link to the original submission, so here's the link to my copy - https://leetcode.com/problems/dinner-plate-stacks/submissions/1061506184/)

#### Language used for code
C++

#### Expected behavior
Accepted solution should pass this tests correctly
`["DinnerPlates","push","push","push","popAtStack"]`
`[[2],[1],[2],[3],[1]]`

`["DinnerPlates","push","push","push","push","push","popAtStack","popAtStack","pop","pop","push","popAtStack"]`
`[[2],[1],[2],[3],[4],[5],[1],[1],[],[],[8],[0]]`

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/60661917/7b37c908-ca17-4042-9ff1-af7b3fb26fcb)

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/60661917/d889ad35-b73d-464c-9495-d5883bddec0a)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
