### ISSUE TITLE
Missing Test Case - 1225. Report Contiguous Dates

### ISSUE THREAD

**Issue by PSwicarz** [LeetCode-Feedback/LeetCode-Feedback#16766]
#### Your LeetCode username
piocarz

#### Category of the bug
- [x ] Question
- [ ] Solution
- [ ] Language
- [x ] Missing Test Cases 

#### Description of the bug
It seems logic behind official solution is different from what would be expected reading question. I solved question by grouping failed and succeded days, getting their start and end dates. In official solution, it seems, task is by default everyday  sccess as long as there is no fail. So why first example doesnt show end at 2019-12-31?  If every day means all year long , why we need success table altogether? 

#### Code you used for Submit/Run operation

```
import pandas as pd

def report_contiguous_dates(failed: pd.DataFrame, succeeded: pd.DataFrame) -> pd.DataFrame:

    def change(df,col,period_state):
        df = df.query(F"'2019-01-01'<={col}<='2019-12-31'")
        df = df.sort_values(f"{col}").reset_index(drop=True).reset_index()
        df = df.groupby((df[col]-pd.to_datetime('2019-01-01')).dt.days-df.index)
        df = df.agg(start_date=(col,'min'),end_date=(col,'max'))
        df['period_state'] = period_state 
        return df.iloc[:,[2,0,1]]

    failed_changed = change(failed,'fail_date','failed')
    succeeded_changed = change(succeeded,'success_date','succeeded') 

    return pd.concat([failed_changed,succeeded_changed]).sort_values('start_date')
```

#### Language used for code
Python Pandas

#### Expected behavior
I guess, mine solution should be correct, by  looking at example you provided.

#### Screenshots
Please take a look at screen to better understand - I simply changed year from 2018 to 2019 in your official example.

![test](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/99476222/9bafa017-dd3f-4ca4-9a86-5b9223b221e5)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Please ask your question in the discussion forum.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
