### ISSUE TITLE
Missing Test Case - 334. Increasing Triplet Subsequence

### ISSUE THREAD

**Issue by sandeepveethu** [LeetCode-Feedback/LeetCode-Feedback#1676]
#### Your LeetCode username

sandeepveethu

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Testcase set for the problem https://leetcode.com/explore/interview/card/top-interview-questions-medium/103/array-and-strings/781/ gives AC instead of WA for the following submission.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
  public boolean increasingTriplet(int[] nums) {
    int n = nums.length;
    for (int i = 0; i < n - 2; i++) {
      if (nums[i] < nums[i + 1] && nums[i + 1] < nums[i + 2])
        return true;
    }
    // there is no upward curve with length >= 3
    int prevMin = -1000000000, currMin = nums[0], cnt = 1;
    for (int i = 1; i < n && cnt < 3; i++) {
      if (nums[i] <= nums[i - 1]) {
        if (nums[i] > prevMin) {
          currMin = nums[i];
        } else {
          // ignore
        }
      } else {
        if (currMin < nums[i]) {
          prevMin = currMin;
          currMin = nums[i];
          cnt++;
        } else {
          // ignore
        }
      }
      // System.out.println(i + " " + currMin + " " + prevMin + " " + cnt);
    }
    return cnt == 3;
  }
}


```

#### Language used for code

Java

#### Expected behavior

Solution should have been WA but got AC instead.
Test case [20,100,10,12,5,13] can be included in the set to achieve this.

#### Additional context

The above solution is incorrect because it assumes that first number of triplet always comes from prefix of array which is in descending order.

**Comment by lc-kay** [comment]
Hi @sandeepveethu 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @sandeepveethu 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
