### ISSUE TITLE
225. Implement Stack using Queues

### ISSUE THREAD

**Issue by mjnovice** [LeetCode-Feedback/LeetCode-Feedback#1677]
#### Your LeetCode username
ajay2012drsinghdo

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
The follow-up `Can you implement the stack such that each operation is amortized O(1) time complexity?` is misleading as there doesn't exist a solution. This simply wastes time of people in an effort to find an non-existent solution. At the very least the solution should point out this, that there doesn't exist a solution.

**Comment by lc-kay** [comment]
@mjnovice Please refer to the discussion where there are many solutions with amortized O(1) per operation.
https://leetcode.com/problems/implement-stack-using-queues/discuss/62522/O(1)-purely-with-queues. Thank you for your time!

**Comment by mjnovice** [comment]
@lc-kay The solution presented uses more than 2 queues. The original problem statement tells you to use only 2 queues. Shouldn't this be specified in the follow-up ?

**Comment by lc-kay** [comment]
Hi @mjnovice 
I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @mjnovice 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
