### ISSUE TITLE
Missing Test Case - 15. 3Sum

### ISSUE THREAD

**Issue by AlphaeusNg** [LeetCode-Feedback/LeetCode-Feedback#16776]
#### Your LeetCode username

Alphatortoise

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Test case 1 input: nums = [-1,0,1,2,-1,-4], but output shows [[-1,-1,2],[-1,0,1]]. the 4 has turned into 1

#### Code you used for Submit/Run operation

```python
class Solution(object):
    def threeSum(self, nums):
        """
        :type nums: List[int]
        :rtype: List[List[int]]
        """
        nums.sort()  # Sort the input list in ascending order
        result = []
        index = 0

        while index < len(nums) - 2:
            cur = nums[index]
            left = index + 1
            right = len(nums) - 1

            while left < right:
                total = cur + nums[left] + nums[right]

                if total == 0:
                    result.append([cur, nums[left], nums[right]])
                    left += 1
                    right -= 1

                    while left < right and nums[left] == nums[left - 1]:
                        left += 1  # Skip duplicate elements

                    while left < right and nums[right] == nums[right + 1]:
                        right -= 1  # Skip duplicate elements
                elif total < 0:
                    left += 1
                else:
                    right -= 1

            index += 1

            while index < len(nums) - 2 and nums[index] == nums[index - 1]:
                index += 1  # Skip duplicate elements

        return result
```

#### Language used for code

Python

#### Expected behavior

Test case 1 input should show: nums = [-1,0,1,2,-1,-~~4~~1], output: [[-1,-1,2],[-1,0,1]] instead.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/78588510/8bc377c1-d1e1-4be1-878b-24652c9d45b6)

#### Additional context

There's nothing to reproduce in the sense that literally, in example 1, it shows a `-4` being mistakenly translated to `1`. Below is a copy of the example, do take note of the bolded characters:

Input: nums = [-1,0,1,2,-1,**-4**]
Output: [[-1,-1,2],[-1,0,**1**]]
Explanation: 
nums[0] + nums[1] + nums[2] = (-1) + 0 + 1 = 0.
nums[1] + nums[2] + nums[4] = 0 + 1 + **(-1)** = 0.

Below is a screenshot taken at the leetcode site.

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/78588510/13644705-c8d3-44e7-abc2-3fdbc4fa4526)

Additionally, when the test cases are being run, it outputs the same error in the same format as illustrated in the screenshot of the bug above.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

More details about the issue.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by AlphaeusNg** [comment]
Hey Pam, can I know the reason why this feedback was rejected?

Thanks!
