### ISSUE TITLE
python integer division (//) is displaying as comment when code is converted into solution

### ISSUE THREAD

**Issue by EventHawk** [LeetCode-Feedback/LeetCode-Feedback#16775]
#### Your LeetCode username
jahanviraycha

#### Category of the bug
- [ ] Question
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

Python used operator (//) as integer division and its showing as a comment when code is converted into solution. Please find screenshot for more details

<img width="1425" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/145158107/be8e01e5-f419-4c47-aabc-496be7605280">

[Solution Link](https://leetcode.com/problems/decoded-string-at-index/solutions/4097385/easy-solution/)

#### Language used for code
Python

#### Expected behavior
It should be displayed as normal code

**Comment by RohitSgh** [comment]
Hi @EventHawk. 

While writing Solution, You have enclosed code in this format

    ```
    your code
    ```

Try enclosing it in following format


    ```python
    your code
    ```
