### ISSUE TITLE
Missing test case ( or even few of them) in 2733. Neither Minimum nor Maximum

### ISSUE THREAD

**Issue by andreev-max** [LeetCode-Feedback/LeetCode-Feedback#16788]
#### Your LeetCode username
andreev-dev

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
We need to add a test case for an array [2, 2, 2, 4, 6] or smth
when we have first 3 or even 10 the same numbers, and then a higher number and a smaller number
because some people just slice an array ( take first 3 numbers) sort it and return the second num, and it works, but should not
so I suggest to add a missing test case

#### Code you used for Submit/Run operation

```
// 2733. Neither Minimum nor Maximum
function findNonMinOrMax(nums: number[]): number {
    if (nums.length < 3) return -1;
  return nums.slice(0, 3).sort((a, b) => a - b)[1];
};
```

#### Language used for code
TypeScript

#### Expected behavior
solutions with slice some amount of nums should not be accepted, cause other part of an array is not taken into account

#### Screenshots
 -

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
