### ISSUE TITLE
Largest Consecutive Sequence Strange Runtime Behavior

### ISSUE THREAD

**Issue by MrWhiskersss** [LeetCode-Feedback/LeetCode-Feedback#16791]
#### Your LeetCode username

RedOrangeYellow

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The solution with run time of (O)n has a reported runtime 10x longer than a solution with (O)n*log(n) runtime.

#### Code you used for Submit/Run operation

```
//(O)n solution as seen in neetcode tutorial under arrays and hashing section
//worst case is 3n where the entire array is the longest consecutive sequence 

class Solution {
public:
    int longestConsecutive(vector<int>& nums) {
        std::unordered_set<int> grid(nums.begin(), nums.end());
        int high = 0;
        int plus = 1;

        for (int numb : nums) {
            if (grid.contains(numb - 1))
                continue;

            while (grid.contains(numb + plus))
                plus ++;

            high = std::max(plus, high);
            plus = 1;
        }

        return high;
    }
};
```

```
//(O)n*log(n) solution forbidden as per the problem instructions

class Solution {
public:
    int longestConsecutive(vector<int>& nums) {
        if (nums.size() == 0)
            return 0;

        std::sort(nums.begin(), nums.end());
        int high = 1;
        int plus = 1;

        for (int ndex = 1; ndex < nums.size(); ndex ++) {
            if (nums[ndex] == (nums[ndex - 1]))
                continue;
            if (nums[ndex] == (nums[ndex - 1] + 1))
                plus ++;
            else
                plus = 1;
            high = std::max(high, plus);
        }

        return high;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The O(n) solution should be consistently faster than the (O)n*log(n) solution.
The O(n) solution takes 1000+ ms to run where as the (O)n*log(n) solution takes 70+ ms to run.

#### Additional context

I am not sure if this bug is specific to my implementation. When writing my solution I tried to adhere to C++ standards as closely as possible but I am still a beginner. I tested this in JavaScript as well and the issue persisted. People might say "just use the (O)n*log(n) solution then, it clearly works" but if that is the case the instructions should be changed to omit the (O)n runtime requirement and the problem difficulty should probably be changed to easy.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by MrWhiskersss** [comment]
Hello,

It would be helpful to know why my feedback was rejected. Was my solution incorrect? Is the problem a strange quirk of the language? Can the Leetcode team not solve the issue? Was my feedback not clear enough?

I browsed the comments on the problem and there are others who are confused by this as well…

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
