### ISSUE TITLE
Accepting O(n log n) Solution for O(log(m+n)) Complexity

### ISSUE THREAD

**Issue by muruga21** [LeetCode-Feedback/LeetCode-Feedback#16796]
#### Your LeetCode username
murugaperumal1

#### Category of the bug
- [ ✔️] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
I recently came across a problem '4. Median of Two Sorted Arrays 'on LeetCode where the specified time complexity requirement was O(log(m+n)), but a solution with a time complexity of O(n log n) was accepted. This discrepancy raised some questions about the correctness of the acceptance criteria for this problem.
Comparing the two time complexities, O(log(m+n)) and O(n log(n)), we can see that O(n log(n)) is greater in this specific scenario. So, for arrays of size 100, O(n log(n)) would have a greater time complexity than O(log(m+n)). 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    double findMedianSortedArrays(vector<int>& nums1, vector<int>& nums2) {
        for(auto x:nums2){
            nums1.push_back(x);
        }
        sort(nums1.begin(), nums1.end());
        int len=nums1.size();
        if(len==1){
            return nums1[0];
        }
        else if(len==0){
            return 0;
        }
        if(len%2!=0){
            return nums1[len/2];
        }
        else{
            int val=nums1[len/2]+nums1[len/2 - 1];
            if(val%2==0){
                return val/2;
            }
            else{
                return (val/2)+0.5;
            }
        }
        return 0;
    }
};
```

#### Language used for code
C++

#### Expected behavior
Solutions submitted for this problem should be evaluated against the specified time complexity of O(log(m+n)).
It should be Time Limit Exceeded

#### Additional context
If there is any mistake in my understanding of the problem or its requirements, please kindly acknowledge and correct me.

**Comment by yumkam** [comment]
Disclaimer: I'm just another leetcode user.
It is next to impossible to make O(n) fail, unless your testcase has 10^7 to 10^9 elements.
Which is not practically possible.
And it is absolutely impossible to make e.g. `O(log n*log m)` solutions fail with TLE (which also exceeds requirements of this problem).
And given, erm, variability of leetcode time measurement, reducing time limit from standard 3s/8s is not a good idea either.
So, the only way to distinguish acceptable from unacceptable solutions is manually analyzing code complexity.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
