### ISSUE TITLE
Missing Test Case - 100. Same Tree

### ISSUE THREAD

**Issue by kevinrjt** [LeetCode-Feedback/LeetCode-Feedback#1679]
#### Your LeetCode username
kevinrjt

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language

#### Description of the bug

Test case:
[1]
[1,null,2]

#### Code you used for Submit/Run operation

https://leetcode.com/problems/same-tree/discuss/32684/My-non-recursive-method/173748
```
class Solution {
    public boolean isSameTree(TreeNode p, TreeNode q) {
        if(p == null && q == null) return true;
        if(p == null || q == null) return false;
        Stack<TreeNode> stackP = new Stack<>(), stackQ = new Stack<>();
        TreeNode currP = p, currQ = q;
        while((currP != null && currQ != null) || (!stackP.isEmpty() && !stackQ.isEmpty())){
            while(currP != null || currQ != null){// traverse root
                if(currP == null || currQ == null || currP.val != currQ.val) return false;    //check whether p and q is null;
                stackP.push(currP);
                currP = currP.left;
                stackQ.push(currQ);
                currQ = currQ.left;      
            }        
            currP = stackP.pop();    // when exit the while loop, both p and q equals null, so return to its parent node
            currQ = stackQ.pop();    
            currP = currP.right;    //point to the right node, traverse sub tree
            currQ = currQ.right;
        }
        return true;
    }
}
```

#### Language used for code
Java

#### Expected behavior

This solution shouldn't be accepted.

#### Screenshots

![image](https://user-images.githubusercontent.com/7740947/102372999-ba020300-3ffa-11eb-8a5e-ea88b0f5ddc2.png)

**Comment by lc-kay** [comment]
Hi @kevinrjt 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @kevinrjt 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by kevinrjt** [comment]
> Hi @kevinrjt
> Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

Thanks. My LeetCode ID is: KevinRen
