### ISSUE TITLE
ArrayOutOfBoundsException while running in Kotlin

### ISSUE THREAD

**Issue by mohamedanees6** [LeetCode-Feedback/LeetCode-Feedback#16792]
#### Your LeetCode username
mohamedanees6 

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
Getting Array Index out of bounds Exception on running the solution in Kotlin
Line 42: Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1

#### Code you used for Submit/Run operation

```
// [443. String Compression](https://leetcode.com/problems/string-compression/)
fun compress(input: CharArray): Int   {
        if (input.isEmpty()) {
            return 0;
        }

        var currentChar: Char = input[0]
        var length: Int = 0
        var charCount: Int = 1
        for (i in 1 until input.size) {
            if (input[i] == currentChar) {
                charCount++
            } else {
                length += (charCount.toString()).length + 1
                currentChar = input[i]
                charCount = 1
            }
        }
        length += (charCount.toString()).length + 1
        return length
    }
```

#### Language used for code
Kotlin

#### Expected behavior
Code should not throw OutOfBoundsException

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
