### ISSUE TITLE
Incorrect Expected Output in Vertical Order Traversal of binary tree test case. 

### ISSUE THREAD

**Issue by NikitaMasand** [LeetCode-Feedback/LeetCode-Feedback#168]
**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
![image](https://user-images.githubusercontent.com/43334750/79870707-01e77080-8401-11ea-8077-170a86a9c203.png)
As shown above, the output expected in the second list in result is [3,6,7]. But when we draw the tree, the output should be [3,7,6] as we have to print the node's value from left to right if it's at the same dist from root and at the same level as well as shown in the given examples. So, the expected output should be changed. 

**what language is your code written in**
Java

**The code you submit/run**
```
class NodeAndDistFromRoot{
    TreeNode node;
    int distFromRoot;

    NodeAndDistFromRoot(TreeNode node, int distFromRoot){
        this.node = node;
        this.distFromRoot = distFromRoot;
    }
}

class Solution {
    public List<List<Integer>> verticalTraversal(TreeNode root) {
        Queue<NodeAndDistFromRoot> queue = new LinkedList<>();
        TreeMap<Integer, List<Integer>> trackDistMap = new TreeMap<>();
        List<List<Integer>> result = new ArrayList<>();
        queue.add(new NodeAndDistFromRoot(root, 0));

        while (!queue.isEmpty()){
            NodeAndDistFromRoot n = queue.poll();
            if(n.node.left!=null){
                queue.add(new NodeAndDistFromRoot(n.node.left, n.distFromRoot-1));
            }
            if(n.node.right!=null){
                queue.add(new NodeAndDistFromRoot(n.node.right, n.distFromRoot+1));
            }
            if(trackDistMap.containsKey(n.distFromRoot)){
                trackDistMap.get(n.distFromRoot).add(n.node.val);
            }
            else{
                List<Integer> l = new ArrayList<>();
                l.add(n.node.val);
                trackDistMap.put(n.distFromRoot, l);
            }
        }

        for(int x : trackDistMap.keySet()){
            List<Integer> l = trackDistMap.get(x);
            result.add(l);
        }
        return result;
    }
}
```

**Expected behavior**
The second list in the results is expected to be [3, 7, 6]

**Screenshots**
Added above. 

**Additional context**

**Comment by CooperCooperCooper** [comment]
Hi @NikitaMasand,
Thank you for reaching out to us! We've taken a look into this issue. Please notice that the problem states that nodes at the same positions have to be sorted in ascending order. You're definitely not alone in this confusion, please check out [this user's question about the same test case and other users' comments](https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/discuss/379762/Incorrect-test-case) to help you in solving this problem.
