### ISSUE TITLE
Missing Test Case - 1226. The Dining Philosophers

### ISSUE THREAD

**Issue by avdosev** [LeetCode-Feedback/LeetCode-Feedback#1680]
#### My LeetCode username
avdosev

#### Category of the bug
- [X] Question
- [X] Solution
- [ ] Language

#### Description of the bug

This code is correct, but I doubt the solution should be like this

the bug is reproducible only in C++

#### Code you used for Submit/Run operation

```C++
class DiningPhilosophers {
public:
    DiningPhilosophers() {
        
    }

    void wantsToEat(int philosopher,
                    function<void()> pickLeftFork,
                    function<void()> pickRightFork,
                    function<void()> eat,
                    function<void()> putLeftFork,
                    function<void()> putRightFork) {
        pickLeftFork();
        pickRightFork();
        eat();
        putLeftFork();
        putRightFork();
    }
};
```

#### Language used for code
C++

**Comment by lc-kay** [comment]
@avdosev This code received Wrong Answer. Please let me know if it's not the same on your end and I will reopen this issue. Thank you for your time!
<img width="1431" alt="Screen Shot 2020-12-16 at 12 11 23 PM" src="https://user-images.githubusercontent.com/70870126/102401240-db7dd300-3f97-11eb-81da-2fb01d4a7461.png">

**Comment by avdosev** [comment]
![image](https://user-images.githubusercontent.com/39769345/102455382-f5cbb580-4058-11eb-8a57-753c4758ecae.png)
![image](https://user-images.githubusercontent.com/39769345/102455714-7b4f6580-4059-11eb-8173-5891c9e01d40.png)

**Comment by lc-kay** [comment]
Hi @avdosev 
Thank you for the screenshot. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @avdosev 
Thank you for your time. The team reviewed your report and resolved it. This code now received Wrong Answer. We appreciate your support!

**Comment by avdosev** [comment]
Cool. Will I get points for creating the Issue?

**Comment by lc-kay** [comment]
@avdosev This issue did not qualify for rewards. Thank you for your time.
