### ISSUE TITLE
Wrong Test Case - 20. Valid Parentheses

### ISSUE THREAD

**Issue by ouqilbo** [LeetCode-Feedback/LeetCode-Feedback#16800]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

The test case with input `"(]"` fails because it expects the string to be valid, both when submitting and when running it through Testcase

#### Code you used for Submit/Run operation

```ts
const openBrackets = ["(", "[", "{"];
const closeBrackets = [")", "]", "}"];
let alreadyValidated = new Set<number>();

function spawnValidator(arr: string[], i: number, checkForBracket: string): boolean
{
    for(let j = i + 1; j < arr.length; j++)
    {
        const bracket = arr[j];

        if(alreadyValidated.has(j)) continue;
        else if(openBrackets.includes(bracket))
        {
            if(!spawnValidator(arr, j, closeBrackets[openBrackets.indexOf(bracket)])) return false;
        }
        else if(bracket != checkForBracket) return false;
        else { alreadyValidated.add(i); alreadyValidated.add(j); break; }
    }

    return true;
}

function isValid(s: string): boolean
{
    const arr = s.split("");
    for(let i = 0; i < arr.length; i++)
        if(closeBrackets.includes(arr[i])) continue;
        else if(alreadyValidated.has(i)) continue;
        else if(!spawnValidator(arr, i, closeBrackets[openBrackets.indexOf(arr[i])])) return false;

    return true;
}
```

#### Language used for code

I tried both Typescript and Javascript

#### Expected behavior

The testcase should be false, because `Open brackets must be closed by the same type of brackets`

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by ouqilbo** [comment]
Hi, thank you for responding @LC-Pam. I don't understand what you mean with 'submission Accepted link'. I don't have an accepted answer because that one test case is failing. I can, however, provide a submission link. By the way, I want to correct myself: the expected output of the test case `(]` is actually false, as it should be, but the code I used is generating, just on leetcode, a true output.
Here is the submission link: https://leetcode.com/submissions/detail/1062881827/

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

Please check the below Accepted submission as a reference: https://leetcode.com/submissions/detail/1067918530/

![Screen Shot 2023-10-05 at 1 18 34 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/3e9385a3-651c-4c68-b9c5-10f1541396cd)

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
