### ISSUE TITLE
Missing Test Case - 456. 132 Pattern

### ISSUE THREAD

**Issue by qsohh** [LeetCode-Feedback/LeetCode-Feedback#16809]
#### Your LeetCode username
QSOLIVIER

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The code below is accepted for submission, however, it fails this test case: ```nums = [2,5,-10,-3,-1,20]```. This code fails when a "13" interval is found but all elements in the stack are beyond the interval. The code returns ```True``` but we are expecting a ```False```.

#### Code you used for Submit/Run operation
``` python3
class Solution:
    def find132pattern(self, nums: List[int]) -> bool:
        cur_min, mins_nums, nb = nums[0], [], len(nums)
        stack = []
        for i, ele in enumerate(nums):
            if ele < cur_min:
                cur_min = ele
            mins_nums.append(cur_min)
        
        for i, ele in enumerate(nums[::-1]):
            if ele > mins_nums[nb-i-1]:
                if not stack:
                    stack.append(ele)
                    continue
                if ele < stack[-1]:
                    stack.append(ele)
                    continue
                if ele == stack[-1]:
                    continue
                while stack:
                    if stack[-1] > mins_nums[nb-i-1]:
                        return True
                    else:
                        stack.pop()
                stack.append(ele)
        return False
```

#### Language used for code
Python3

#### Expected behavior
The code should be noted as a wrong answer.

#### Screenshots

![Screenshot 2023-09-30 160912](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/50617425/1c03cfd1-635d-4edd-9b62-49c79b6142de)

![Screenshot 2023-09-30 161046](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/50617425/0018af86-80aa-4975-9e4b-001889b6b365)

#### Additional context
I think this should be the submission accepted link?

https://leetcode.com/problems/132-pattern/submissions/1063070837/?envType=daily-question&envId=2023-09-30

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
