### ISSUE TITLE
Missing Test Case - 217. Contains Duplicate

### ISSUE THREAD

**Issue by AnshulOG** [LeetCode-Feedback/LeetCode-Feedback#16813]
#### Your LeetCode username

Anshul29

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

a testcase is missing

#### Code you used for Submit/Run operation

```
// Contains Duplicate
class Solution{
    public boolean containsDuplicate(int[] nums) {
        if (nums.length < 2) {
            return false;
        }
        int min = Integer.MAX_VALUE;
        int max = Integer.MIN_VALUE;
        for (int i: nums) {
            if (i < min) {
                min = i;
            }
            if (i > max) {
                max = i;
            }
        }
        int[] arr = new int[(max - min)/32 + 1];
        for (int i: nums) {
            int x = i - min;
            int pos = x / 32;
            int mask = 1 <<  (x % 32);
            if ((arr[pos] & mask) != 0) {
                return true;
            } else {
                arr[pos] |= mask;
            }
        }
        return false;
    }
}
```

#### Language used for code

Java

#### Expected behavior

nums = [4,6,-1000000000,4,9,1000000000,60]
Should have returned true but actually returned memory limit exceeded.

#### Additional context

the solution will work if the range of numbers in nums[] is not that big but if the range actually becomes  from -1000000000 to +1000000000 then memory limit wil exceed as the array `arr` that we are creating will have very big length.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
