### ISSUE TITLE
Missing Test Case - 2871. Split Array Into Maximum Number of Subarrays

### ISSUE THREAD

**Issue by GiacomoSorbi** [LeetCode-Feedback/LeetCode-Feedback#16818]
#### Your LeetCode username
Ajna2

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
There should be more test cases with total `&` value of `1`; my solution was erroneously `return`ing `1` for any value `> 1`, and I was lucky no more tests like that were submitted.

#### Code you used for Submit/Run operation

```cpp
// Two Sum
class Solution {
public:
    int maxSubarrays(vector<int>& nums) {
        // support variables
        int res = 0, len = nums.size(), curr = INT_MAX,
            minBit = accumulate(begin(nums), end(nums), INT_MAX, bit_and<int>());
        // minBit is too expensive
        if (minBit > 1) return 1;
        // parsing nums
        for (int n: nums) {
            curr &= n;
            // if we reached the target minBit, we try to open a new sub array
            if (curr == minBit) {
                res++;
                curr = INT_MAX;
            }
        }
        return res;
    }
};
```

#### Language used for code
C++

#### Expected behaviour
The tests should fail, instead it was passing since the sole test case with overall `&` value of `1` seemed to be the second example case.

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/4815731/570bc55b-3b45-4874-803e-307c641940a9)

#### Additional context
Adding a test case like `[5,7,1,3,5,7,1,3]` should suffice (my code would erroneously `return` `3`, instead of `1`).

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
