### ISSUE TITLE
Missing Test Case - 37. Sudoku Solver

### ISSUE THREAD

**Issue by domwst** [LeetCode-Feedback/LeetCode-Feedback#16812]
#### Your LeetCode username
8730199

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Test cases in this problem are weak and don't check cases with non-trivial backtrack. My solution had runtime of 1ms on the current tests and it has runtime of 12ms on proposed tests.

#### Code you used for Submit/Run operation

```rust
impl Solution {
    const C: usize = 3;
    const N: usize = Self::C * Self::C;

    pub fn solve_sudoku(board: &mut Vec<Vec<char>>) {
        let mut allowed = [[(1usize << Self::N) - 1; Self::N]; Self::N];

        for i in 0..Self::N {
            for j in 0..Self::N {
                if let Some(v) = Self::get_digit(board[i][j]) {
                    allowed = Self::deny(allowed, i, j, v);
                }
            }
        }

        Self::retrie(board, allowed);
    }

    fn retrie(board: &mut Vec<Vec<char>>, allowed: [[usize; Self::N]; Self::N]) -> bool {
        let best_cage = allowed
            .iter()
            .enumerate()
            .map(|(i, v)| v.iter().enumerate().map(move |(j, &elem)| (elem, i, j)))
            .flatten()
            .filter(|&(_, i, j)| board[i][j] == '.')
            .map(|(v, i, j)| (v.count_ones(), i, j))
            .min();

        let (bcnt, bi, bj) = match best_cage {
            Some(v) => v,
            None => return true,
        };

        if bcnt == 0 {
            return false;
        }

        for d in 0..Self::N {
            if allowed[bi][bj] & (1usize << d) != 0 {
                board[bi][bj] = ('1' as u8 + d as u8) as char;
                if Self::retrie(board, Self::deny(allowed, bi, bj, d)) {
                    return true;
                }
            }
        }
        board[bi][bj] = '.';
        false
    }

    fn get_digit(c: char) -> Option<usize> {
        if c == '.' {
            None
        } else {
            Some(c as usize - '1' as usize)
        }
    }

    fn deny(
        mut allowed: [[usize; Self::N]; Self::N],
        i: usize,
        j: usize,
        v: usize,
    ) -> [[usize; Self::N]; Self::N] {
        for r in 0..Self::N {
            allowed[r][j] &= !(1usize << v);
        }
        for c in 0..Self::N {
            allowed[i][c] &= !(1usize << v);
        }
        let ci = i - i % Self::C;
        let cj = j - j % Self::C;
        for cr in 0..Self::C {
            for cc in 0..Self::C {
                allowed[ci + cr][cj + cc] &= !(1usize << v);
            }
        }
        allowed
    }
}
```

#### Language used for code
Rust

#### Expected behavior
The measured runtime should be higher.

#### Proposed test cases
1. ```[[".", "3", ".", ".", ".", ".", "2", "6", "."], [".", ".", "2", "6", ".", "1", ".", "9", "."], [".", ".", ".", ".", ".", "7", ".", ".", "."], [".", ".", ".", ".", "3", ".", ".", "4", "."], [".", ".", "6", ".", "7", ".", ".", ".", "."], [".", "5", ".", "4", ".", "6", ".", ".", "1"], [".", ".", "3", "9", ".", "2", ".", "1", "."], ["8", ".", ".", ".", ".", ".", ".", ".", "5"], [".", ".", ".", ".", "4", ".", ".", ".", "."]]```
2. ```[[".", "3", ".", ".", ".", ".", "2", "6", "."], [".", ".", "2", "6", ".", "1", ".", "9", "."], [".", ".", ".", ".", ".", "7", ".", ".", "."], [".", ".", ".", ".", "3", ".", ".", "4", "."], [".", ".", "6", ".", "7", ".", ".", ".", "."], [".", "5", ".", "4", ".", "6", ".", ".", "1"], [".", ".", "3", "9", ".", "2", ".", "1", "."], ["8", ".", ".", ".", ".", ".", ".", ".", "5"], [".", ".", ".", ".", "4", ".", ".", ".", "."]]```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that makes it extremely hard to quantify the runtime correctly.

The significance of program’s runtime we're providing to you is so that you can compare your code with the peaks in the graph, where programs that have different time complexities like O(n), O(n^2) would be around different peaks (at least in most of the cases). Other factors include compiler changes, optimizations, and more features that our developers keep on working on to provide better UX. These factors all also affect the runtime of the same program, introducing some level of discrepancy.

I hope this helps. Should you have any other questions, please let us know.
