### ISSUE TITLE
2872. Maximum Number of K-Divisible Components - Wrong Hints

### ISSUE THREAD

**Issue by Jeetaksh** [LeetCode-Feedback/LeetCode-Feedback#16816]
#### Your LeetCode username

Jeetaksh

#### Category of the bug
-  Question Hint
 

#### Description of the bug
The hints of Question 2871. Split Array Into Maximum Number of Subarrays are mentioned in the question 2872.

#### Expected behavior
The hints of right question should be mentioned.

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/92541718/00daa738-dbe8-4db4-90bb-59bcb09fa838)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
