### ISSUE TITLE
2871. Split Array Into Maximum Number of Subarrays - Wrong Hints 

### ISSUE THREAD

**Issue by Jeetaksh** [LeetCode-Feedback/LeetCode-Feedback#16817]
#### Your LeetCode username

Jeetaksh

#### Category of the bug
- Question Hint

#### Description of the bug

The hints of Question 2870. Minimum Number of Operations to Make Array Empty are mentioned in the question 2871.

#### Expected behavior
The hints of right question should be mentioned.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/92541718/2666d827-493f-4a0f-9210-7a400c0a5373)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
