### ISSUE TITLE
1690. Stone Game VII - Solution Article - Time Complexity

### ISSUE THREAD

**Issue by yang203000** [LeetCode-Feedback/LeetCode-Feedback#1681]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

In [1690. Stone Game VII](https://leetcode.com/problems/stone-game-vii/solution/) Solution Article, it says Time Complexity of  `Approach 1: Brute Force Using Recursion` is O(2^(n^2)), 

but I think it's O(2^n), and give it a test with C#.

test code, to test array length from 2 to 32:

```
for (int i = 2; i < 32; i++)
{
	var now = DateTime.Now;
	int[] n = new int[i];
	for (int j = 0; j < i; j++)
	{
		n[j] = j;
	}
	Solution s = new Solution();
	s.StoneGameVII(n);
	Console.WriteLine(i + " " + DateTime.Now.Subtract(now).TotalMilliseconds);
}
```

the output:

```
2 0
3 0
4 0
5 0
6 0
7 0
8 0
9 0
10 0
11 0
12 0
13 0
14 0.9765
15 0
16 1.9511
17 1.9518
18 5.8563
19 8.8091
20 20.4743
21 44.4265
22 81.9833
23 177.6695
24 311.8522
25 559.9039
26 1090.7943
27 2219.3533
28 4382.3762
29 8856.4235
30 18894.4846
31 35567.237
```

and it shows that from length 20 to 31, the time in millisecond multiply 2 when length plus 1,

it seems like it's  O(2^n),

Could you give it a check if Time Complexity of  `Approach 1: Brute Force Using Recursion` is O(2^(n^2)) or O(2^n)?
 

#### Language used for code

C#

**Comment by lc-kay** [comment]
Hi @yang203000 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by ShradhaSangtani** [comment]
@lc-kay I have fixed this.

**Comment by yang203000** [comment]
Hi I have seen the fix, thank you. You can close this issue.
