### ISSUE TITLE
Poor bitwise explanations

### ISSUE THREAD

**Issue by kamikaze942** [LeetCode-Feedback/LeetCode-Feedback#16822]
#### Your LeetCode username
Kamikaze942

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
-[X]  Other

#### Description of the bug
This is not really a bug, i clicked on report issue  button on the explanation at this link 
https://leetcode.com/explore/learn/card/bit-manipulation/671/bit-manipulation-state-compression/4271/

Several of the articles in the bit manipulation are very hard to understand.  Do you even proof read them?  

```where dp[row][status] is the maximum number of students taking the exam when the seat status of row row (0≤row≤rows) is status.```

#### Expected behavior
A clear and concise description

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've submitted your feedback to the team.  

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
