### ISSUE TITLE
2653. Sliding Subarray Beauty - Typo in Question

### ISSUE THREAD

**Issue by agrawalishaan** [LeetCode-Feedback/LeetCode-Feedback#16826]
#### Your LeetCode username
agrawalishaan

#### Category of the bug
- [ X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the question, it writes:
<img width="558" alt="Screenshot 2023-09-30 at 7 29 42 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/113543798/a562a68c-4624-4d96-b9c4-e3a84d249c5b">
The code formatting for `[-3, -2, 3] ` extends one space too far.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
