### ISSUE TITLE
Missing Test Case - 456. 132 Pattern

### ISSUE THREAD

**Issue by icherniukh** [LeetCode-Feedback/LeetCode-Feedback#16828]
#### Your LeetCode username

icherniukh

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The code below passed all tests for getting Accepted, but it is a O(n^2) solution is should be failing.
It does fail consistently with Time Limit on a test I constructed (textfile with the test: [test420.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/12775757/test420.txt)).

#### Code you used for Submit/Run operation

```python3
class Solution:
    def find132pattern(self, nums: List[int]) -> bool:
        if not nums:
            return False
        
        afters = []
        
        min_i = [nums[0]]
        for i in range(1, len(nums)):
            min_i.append(min(min_i[-1], nums[i]))
        
        for j in reversed(range(len(nums))):
            if nums[j] > min_i[j]:
                index = bisect.bisect_left(afters, nums[j])
                if index > 0 and afters[index - 1] > min_i[j]:
                    return True
                bisect.insort_left(afters, nums[j])
        
        return False
```

#### Language used for code

Python3

#### Expected behavior

The solution should be getting a Time Limit Exceeded

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/16390154/8de69955-3423-4622-9fdf-63ad6ee99db2)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/16390154/8cac0952-cae5-4db3-8cea-3b74ab96690b)

#### Additional context

Link to the Accepted submission that should be getting TL: https://leetcode.com/problems/132-pattern/submissions/1063509815

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
