### ISSUE TITLE
Maximum Number of K-Divisibile Components - Missing Testcases

### ISSUE THREAD

**Issue by Jeetaksh** [LeetCode-Feedback/LeetCode-Feedback#16820]
#### Your LeetCode username

Jeetaksh

#### Category of the bug

-  Missing Test Cases 

#### Description of the bug
Some critical testcases are missing. Adding this testcase gives runtime error due to the range of integer data type.

5
[[0,2],[1,2],[1,3],[2,4]]
[999999999,999999999,999999999,999999999,999999999]
5

The code is getting clearly accepted because of some missing testcase. This testcase gives a runtime error to the faulty code. 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    
    int ans = 0;
    
    int dfs(int node, int parent, int k, vector<int>& vals, vector<vector<int>>& adj) {
        int sum = vals[node];

        for (auto it : adj[node]) {
            if (it == parent) continue;
            sum += dfs(it, node, k, vals, adj);
        }

        if (sum % k == 0) {
            ans++;
            sum = 0;
        }

        return sum;
    }
    
    int maxKDivisibleComponents(int n, vector<vector<int>>& edges, vector<int>& values, int k) {
        vector<vector<int>> adj(n);
        
        for(auto e:edges){
            adj[e[0]].push_back(e[1]);
            adj[e[1]].push_back(e[0]);
        }
            
        dfs(0,-1, k, values, adj);
        return ans;
        
    }
};
```

#### Language used for code

C++

#### Expected behavior
The testcase should be added, and the above incorrect code should give error.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
