### ISSUE TITLE
Missing Test Case - 472. Concatenated Words

### ISSUE THREAD

**Issue by elvin-yang** [LeetCode-Feedback/LeetCode-Feedback#1683]
#### Your LeetCode username
elvinyang

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Test case too weak. A lot poor solutions could pass.

#### Code you used for Submit/Run operation

```
class Solution {
    public List<String> findAllConcatenatedWordsInADict(String[] words) 
    {
        Set<String> set = new HashSet<>(10000);
        List<String> res = new ArrayList<>();
        int min = Integer.MAX_VALUE;
        for (String word : words) 
        {
            if (word.length() == 0) 
                continue;
            
            set.add(word);
            min = Math.min(min, word.length());
        }
        
        for (String word : words) 
        {
            if (check(set, word, 0, min)) 
                res.add(word);
        }
        return res;
    }

    private boolean check(Set<String> set, String word, int start, int min) 
    {
        for (int i = start + min; i <= word.length() - min; i++) 
        {
            if (set.contains(word.substring(start, i)) &&
                (set.contains(word.substring(i)) || check(set, word, i, min))) 
                return true;
        }
        return false;
    }
}
```

#### Language used for code
Java

#### Expected behavior
Should get a TLE but it could pass.

#### Additional context
Purposing below test case: (doesn't allow me to paste here as it's too long so I stored it on JS fiddle)
https://jsfiddle.net/at8m47g9/

**Comment by lc-kay** [comment]
Hi @elvin-yang 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @elvin-yang 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
