### ISSUE TITLE
Missing Test Case - 2875. Minimum Size Subarray in Infinite Array

### ISSUE THREAD

**Issue by Sandipan19000** [LeetCode-Feedback/LeetCode-Feedback#16831]
#### Category of the bug
- [ ] Question : You are given a 0-indexed array nums and an integer target.

A 0-indexed array infinite_nums is generated by infinitely appending the elements of nums to itself.

Return the length of the shortest subarray of the array infinite_nums with a sum equal to target. If there is no such subarray return -1.

- [ ] Solution : Here I used appending the nums behind it until total sum greater than target. Then simple sliding window consept to find the minimum lenght of the window.
- [ ] Language : C++
- [ ] Missing Test Cases  :  nums = [1,1,1]  target = 1000000000

#### Description of the bug :  
In this code I append the nums k times ( k = target / accumulate(nums.begin(), nums.end())+ 1 )
It should give time limit exeed when the target is so big (target = 1000000000)
because Time complexity for that test case near about O(10 ^ 9). So it should give TLE.
But my code is accepted. Please fix this bug.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    int minSizeSubarray(vector<int>& nums, int target) {
        long long total = 0, x = 0, n= nums.size();
        for(int i=0; i<n; i++)  total = total + 0ll + nums[i];
        long long t = target / total + 1;
        vector<int> v = nums;
        for(int i=0; i<t; i++)  v.insert(v.end(), nums.begin(), nums.end());
        
        int i=0, j=0, mini = INT_MAX;
        while(i<v.size())   {
            x += v[i];
            while(x > target && j<v.size()) x -= v[j++];
            if(x == target) mini = min(mini, i - j + 1);
            i++;
        }
        return mini==INT_MAX ? -1 : mini;
        
    }
};
```

#### Expected behavior : 
It should give Time Limit Exceeded

#### Screenshots 
<img width="943" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/114274591/efe41087-20c6-4843-9c64-15f662f1867b">

#### Additional context : 
Submission Accepted Link : [https://leetcode.com/problems/minimum-size-subarray-in-infinite-array/submissions/1063692943/](url)

**Comment by singlarohan** [comment]
I figured out the same. I submitted the correct one eariler and was just messing around when I stumbled onto this

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/97383365/a1aa3c06-efc8-4c66-9bea-ac71cd44b59b)

but for the test case nums = [1], target = 10^9
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/97383365/e95ebc44-16d9-48a0-a603-167a31d29006)

**Comment by Sahil-Sidana** [comment]
The code is Accepted by appending nums only 97 times.
But that should not be the case.
For Example: nums=[1],target=100;

Accepted Code: https://leetcode.com/submissions/detail/1064026317/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by Sahil-Sidana** [comment]
Still not received 100 leetcode coins
