### ISSUE TITLE
Suddenly sound stopped in leetcode explore videos

### ISSUE THREAD

**Issue by SandeepVaman** [LeetCode-Feedback/LeetCode-Feedback#16833]
#### Your LeetCode username

SandeepVaman

#### Category of the bug
- [ ] Question
- [1 ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I was watching video on this page https://leetcode.com/explore/learn/card/graph/618/disjoint-set/3881/. Suddenly voice stopped. Now no voice is coming for any of the videos. Restarted system and reset permissions. Nothing is helping.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We have checked the video in the explore card, the voice is working on our side.

If the issue still exists on your side, please try to clear the history and cookies, then sign out and sign in, and re-open the course. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
