### ISSUE TITLE
Missing Test Case - 2871.  Split Array into Maximum Number of Subarrays

### ISSUE THREAD

**Issue by shricodev** [LeetCode-Feedback/LeetCode-Feedback#16848]
#### Your LeetCode username

shricodev

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

There should be more test cases with total & value of 1

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int maxSubarrays(vector<int>& nums) {
        int mn = *min_element(nums.begin(), nums.end());
        int ad = 1;
        for(int num : nums) ad &= num;
        mn = min(mn, ad);
        
        int ans = 0, curr = nums[0];
        for(int i=0;i<nums.size();i++) {
           curr &= nums[i];
            if(curr == mn) {
                ans++;
                if(i+1 < nums.size()) curr = nums[i+1];
            }
        }
        return max(ans, 1);
    }
};
```

#### Language used for code

C++

#### Expected behavior

The test should have failed. overall` & `value of `1` seemed to be the second example case.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
