### ISSUE TITLE
 Missing Test Case - 1197. Minimum Knight Moves

### ISSUE THREAD

**Issue by yanrs17** [LeetCode-Feedback/LeetCode-Feedback#1684]
#### Your LeetCode username

yanrs17

#### Category of the bug
- [x] Solution

#### Description of the bug

Missing Test Cases: 
1. `x = -1` and `y = -1`.
1. `x = 1` and `y = -1`.
1. `x = -1` and `y = 1`.

Expected: Reject my code
Actual: Get accepted

#### Code you used for Submit/Run operation

```
class Solution {
    private static final int[][] DIRECTIONS = {{1, 2}, {-1, 2}, {1, -2}, {-1, -2}, {2, 1}, {-2, 1}, {2, -1}, {-2, -1}};
    public int minKnightMoves(int x, int y) {

        if (x == 1 && y == 1) {
            return 2;
        }

        x = Math.abs(x);
        y = Math.abs(y);

        Queue<int[]> queue = new ArrayDeque<>();
        Set<String> visited = new HashSet<>();
        int result = 0;

        queue.offer(new int[] {0, 0});
        while (!queue.isEmpty()) {
            int size = queue.size();
            while (size-- > 0) {
                int[] cell = queue.poll();
                if (cell[0] == x && cell[1] == y) {
                    return result;
                }
                for (int[] direction : DIRECTIONS) {
                    int newX = cell[0] + direction[0];
                    int newY = cell[1] + direction[1];
                    String newCellString = newX + "," + newY;
                    if (newX >= 0 && newY >= 0 && !visited.contains(newCellString)) {
                        queue.offer(new int[] {newX, newY});
                        visited.add(newCellString);
                    }
                }
            }
            result++;
        }
        return -1;
    }
}
```

#### Language used for code
Java

#### Expected behavior
Expected: Reject my code.

#### Screenshots
<img width="959" alt="螢幕快照 0002-12-17 07 25 39" src="https://user-images.githubusercontent.com/18586504/102487900-416e6700-4039-11eb-8833-393738ac378d.png">

**Comment by lc-kay** [comment]
Hi @yanrs17 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @yanrs17 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
