### ISSUE TITLE
437

### ISSUE THREAD

**Issue by Ricky-Chu** [LeetCode-Feedback/LeetCode-Feedback#1685]
** Bug 类型**
- [x] 题目437
- [ ] 题解
- [ ] 编程语言 golang

**描述**
描述你遇到的 bug

测试用例的输出和提交的输出不一致（相同的测试用例）

**你使用的语言**
golang

**你提交或者运行的代码**
```golang
var ans int
var sum int
func pathSum(root *TreeNode, s int) int {
	sum = s
	helper(root, sum, true)
	return ans
}
func helper(node *TreeNode, pre int, isFirst bool) {
    if node == nil {
        return
    }
    if pre == node.Val {
        ans++
    }
    helper(node.Left, pre-node.Val, false)
    helper(node.Right, pre-node.Val, false)
    if isFirst {
        helper(node.Left, sum, true)
        helper(node.Right, sum, true)
    }
}
```

**期望行为**
修复一下吧

**屏幕截图**
![image](https://user-images.githubusercontent.com/47296568/102495258-d791a400-40b0-11eb-9961-5524baa8e0f4.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by zerotrac** [comment]
不要使用全局变量，只会被初始化一次

**Comment by Ricky-Chu** [comment]
> 不要使用全局变量，只会被初始化一次

感谢零神 我待会试试

**Comment by feiceh** [comment]
你好，这是由于使用了全局变量且未初始化导致的，这里有更详细的说明，https://support.leetcode-cn.com/hc/kb/article/1194344/，感谢反馈。
