### ISSUE TITLE
title not responsive with dynamic window

### ISSUE THREAD

**Issue by praneethNellutla** [LeetCode-Feedback/LeetCode-Feedback#16858]
the title is not visible since it is so long it is not breaking into multiple lines as text in question breaks
#### Your LeetCode username

praneeth_nellut1

#### Description of the bug

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/116669539/271cf9c8-000b-46af-b953-e7cea686b54f)
the title here is not visible and not responsive as the problem statement is responsive

#### Expected behavior

the title should also be responsive to the dynamic width with some min width

**Comment by praneethNellutla** [comment]
i would like to solve this issue if i was assigned to solve it can i take and work on this issue please

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

![Screen Shot 2023-10-03 at 2 52 49 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/bc5aabeb-0c6b-4215-a99f-84149536f9ea)

The title can be adjusted when you move the adjust bar.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
