### ISSUE TITLE
Missing Test Case - 584. Find Customer Referee

### ISSUE THREAD

**Issue by iamnidhisha** [LeetCode-Feedback/LeetCode-Feedback#16853]
#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [x] Missing Test Cases 

#### Description of the bug

- Solution

#### Code you used for Submit/Run operation

Find the names of the customer that are not referred by the customer with id = 2.
Return the result table in any order.

```
// MS Sql Server
Select name from Customer where (referee_Id <> (2) Or referee_id is null)
```

#### Language used for code

MS Sql Server

#### Screenshots

![Screenshot (69)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/125153381/d2475786-ef82-4a3f-a39e-444431f19f5e)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
