### ISSUE TITLE
Wrong Hints - 2871. Split Array Into Maximum Number of Subarrays

### ISSUE THREAD

**Issue by iamAkashNad** [LeetCode-Feedback/LeetCode-Feedback#16860]
I think the hints of this question is not **correct**.
The hints are actually of **2870. Minimum Number of Operations to Make Array Empty** question. And these are mistakenly added to the 2871 no. question.

Here are the hints.

1. If the frequency of some element is 1, then it is not possible to make the array empty.
2. Count the frequency of each element in the array, and solve the problem independently for each element, then finally sum up the answers.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
