### ISSUE TITLE
Missing Test Case - 2875. Minimum Size Subarray in Infinite Array

### ISSUE THREAD

**Issue by Prokopiy19** [LeetCode-Feedback/LeetCode-Feedback#16863]
#### Your LeetCode username

unnamedf

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My submission is accepted, but it gives wrong answer on my custom test.
Custom test used is:
nums = [1, 100000, 100000, ... , 100000, 1]     (100000 is repeated 99998 times)
target = 2

#### Code you used for Submit/Run operation

```
class Solution {
public:
    static constexpr int INF = numeric_limits<int>::max() / 2;
    int minSizeSubarray(vector<int>& nums, int target) {
        int ret = INF;
        const int n = nums.size();
        
        int sum = 0;
        bool overflow = false;
        for (int i = 0; i < n; ++i) {
            if (sum > INT_MAX - nums[i]) {
                overflow = true;
                break;
            }
            sum += nums[i];
        }
        if (!overflow) {
            int cost = (target / sum) * n;
            int ntarget = target % sum;
            ret = min(ret, solve(nums, ntarget - sum) + n + cost);
            cost -= n;
            ntarget += sum;
            if (ntarget <= target)
                ret = min(ret, solve(nums, ntarget - sum) + n + cost);
        }
        ret = min(ret, solve(nums, target));
        
        return ret >= INF ? -1 : ret;
    }
    int solve(const vector<int>& nums, int target) {
        int ret = INF;
        const int n = nums.size();
        for (int l = 0, r = 0, sum = 0; true; ) {
            while (l < n && sum > target)
                sum -= nums[l++];
            if (sum == target)
                ret = min(ret, r - l);
            if (r < n)
                sum += nums[r++];
            else
                break;
        }
        return ret;
    }
};
```

#### Language used for code

C++

#### Expected behavior

This code shouldn't be accepted.

#### Screenshot
![screen](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/71594105/8f72c9cc-d2c0-47be-a98d-85bec65fd757)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
