### ISSUE TITLE
loop in swift executes infinitely 

### ISSUE THREAD

**Issue by Pranav108** [LeetCode-Feedback/LeetCode-Feedback#16862]
#### Your LeetCode username
[BEN__10](https://leetcode.com/BEN__10/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

[2038. Remove Colored Pieces if Both Neighbors are the Same Color](https://leetcode.com/problems/remove-colored-pieces-if-both-neighbors-are-the-same-color/)
```
class Solution {
    func winnerOfGame(_ colors: String) -> Bool {
        var aliceCount : Int = 0
        var bobCount : Int = 0
        
        for i in 1...(colors.count - 2) { // for color = "A", loop should not executes but it executes infinitely  
            let prevChar : Character = colors[colors.index(colors.startIndex, offsetBy: i-1)]
            let currentChar : Character = colors[colors.index(colors.startIndex, offsetBy: i)]
            let nextChar : Character = colors[colors.index(colors.startIndex, offsetBy: i+1)]
            if ( prevChar == "A" && currentChar == "A" && nextChar == "A"){
                aliceCount += 1
            }
            if (prevChar == "B" && currentChar == "B" && nextChar == "B"){
                bobCount += 1
            }
        }
        return aliceCount > bobCount
    }
}

```

#### Language used for code

Swift

#### Expected behavior

for loop in my code should not execute but it executes infinitely, for provided string of single length

#### Screenshots

<img width="1052" alt="Screenshot 2023-10-02 at 3 49 55 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/56934594/1a2f7d67-8cdf-45a2-aab5-0a2765912679">

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Please ask your question in the discussion forum.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
