### ISSUE TITLE
Missing Test Case - 26. Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by nitingoley** [LeetCode-Feedback/LeetCode-Feedback#16867]
#### Your LeetCode username

Nitingoley42@gmail.com

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

        int j=0;
        for(int i=0; i<nums; i++)
        {
           
            if(nums[i]!=nums[j])
                {
                   nums[++j] = nums[i];
                }
          
        }

        return j+1;
    }
}
    }
};
```

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
