### ISSUE TITLE
Missing Test Case - 50. Pow(x, n)

### ISSUE THREAD

**Issue by Rahulmajhi0123** [LeetCode-Feedback/LeetCode-Feedback#16864]
#### Your LeetCode username

rahulmajhi0123 (https://leetcode.com/rahulmajhi0123)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

There is a missing test case for the "pow(x, n)" problem on LeetCode. The missing test case is as follows:

Input:
x = -1.0000000000001
n = -2147483648

#### Code you used for Submit/Run operation

```

#### Language used for code
<!-- C++ -->
```
class Solution {
private:
    double power(double x, int n){
        if(n==0){
            return 1;
        }
        return x * power(x, n-1);
    }
public:
    double myPow(double x, int n) {
        if (n == INT_MAX) return (x == 1) ? 1 : (x == -1) ? -1 : 0;
        if (n == INT_MIN) return (x == 1 || x == -1) ? 1 : 0;
        double num = 1;
        if(n>=0){
            num = power(x, n);
        }
        else{
            n = -n;
            num = power(x, n);
            num = 1.0/num;
        }
        return num;
    }
};
```

#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->

Expected Output:
This test case should help users test their code for extreme values of "x" and "n" and ensure the solution handles them correctly.


#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/123830001/84773c97-81d0-40a4-80eb-127ce24195d2)



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by Rahulmajhi0123** [comment]
Link :

https://leetcode.com/problems/powx-n/submissions/1064860480/?envType=study-plan-v2&envId=top-interview-150

Code :

class Solution {
public:
    double myPow(double x, int n) {
        long tmp = n;
        if (tmp < 0) tmp = -1 * tmp;
        double ans = 1.0;
        while (tmp > 0) {
            if (tmp % 2 == 1) {
                ans = ans * x;
                tmp = tmp - 1;
            } else {
                x = x * x;
                tmp = tmp / 2;
            }
        }
        if (n < 0) ans = (double)1.0 / (double)(ans);
        return ans;
    }
};

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

x = -1.0000000000001
n = -2147483648
already exists.

![Uploading Screen Shot 2023-10-05 at 1.26.14 PM.png…]()


If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
