### ISSUE TITLE
The kth Factor of n

### ISSUE THREAD

**Issue by sathvik077** [LeetCode-Feedback/LeetCode-Feedback#1686]
####  LeetCode username
sathvik798

####  December week 1 Contest Solution 
Question 5: kth Factor of n

- Solution

#### Code you used for Submit/Run operation

```
// 
class Solution {
public:
    int kthFactor(int n, int k) {
        vector<int>v;
        if(n>=0){
        for(int i=1;i<=n;i++){
            if(n%i==0){
                v.push_back(i);
            }
        }
        }
        int ans =-1;
        if(k>int(v.size())){
            return -1;
        }
        else{
            return v[k-1];
        }
        
    }
};
```

#### Language used for code
 C++

**Comment by lc-kay** [comment]
@sathvik077 What is the proposed issue?

**Comment by lc-kay** [comment]
Hi @sathvik077  ,
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
