### ISSUE TITLE
Missing Test case in 377. combination-sum-iv

### ISSUE THREAD

**Issue by sumitaby1** [LeetCode-Feedback/LeetCode-Feedback#16879]
#### Your LeetCode username
sumitaby1

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug
The limit defined for the parameter "target" in the ques is 1<=target<=1000. Hence for the test case having the target value = 1000
the below mentioned code will break but this code is getting accepted and hence the test case with target value as 1000 is not present.
Sample test case:
nums={1000}, target = 1000.

#### Code you used for Submit/Run operation
#define ll unsigned long long int
class Solution {
public:
    int combinationSum4(vector<int>& a, int target) {
        ll dp[1000] = {0};
        int n = a.size();
        for(int i = 1;i<=target;i++) {
            for(int j = 0;j<n;j++) {
                if(i>a[j]) {
                    dp[i] += dp[i-a[j]];
                } else if(i==a[j])dp[i]++;
            }
        } 
        return dp[target];   
    }
};

#### Language used for code
C++

#### Expected behavior
For Test case where target value is 1000. It should break but there is no such test case.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by sumitaby1** [comment]
Please find the AC link: https://leetcode.com/submissions/detail/1065211639/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
