### ISSUE TITLE
Missing Test Case - 205. Isomorphic Strings

### ISSUE THREAD

**Issue by AnshulOG** [LeetCode-Feedback/LeetCode-Feedback#16875]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Wrong Testing Process

#### Description of the bug

My output is false and it should be false but the testing process of problem 205 says expected is true

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean isIsomorphic(String s, String t) {
        int[] map1=new int[200];
        boolean[] map2=new boolean[200];
        char[] s1=s.toCharArray();
        char[] t1=t.toCharArray();
        for(int i=0;i<s1.length;i++){
            if( !map2[t1[i]] ){
                map1[s1[i]]=t1[i];
                map2[t1[i]]=true;
            }
        }
        for(int i=0;i<s1.length;i++){
            if(map1[s1[i]]!=t1[i]) return false;
        }
        return true;
    }
}
```

#### Language used for code

Java

#### Expected behavior

For testcase :
s="12"
t="\u0067\u0067"
output should be clearly false because both '1' and '2' are mapping to '\u0067'  but the testing process says that expected value is true.
And not only this testcase but all the testcases with characters written in directly the ascii codes it will be examining them wrong.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've used your feedback to update the problem.

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback.
Please provide us your LC username.

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback. 

Please provide us your Leetcode Username. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by AnshulOG** [comment]
My leetcode username is Anshul29.

**Comment by AnshulOG** [comment]
My leetcode username is "Anshul29".
