### ISSUE TITLE
Missing Test Case - 2038. Remove Colored Pieces if Both Neighbors are the Same Color

### ISSUE THREAD

**Issue by kkb-mmmut** [LeetCode-Feedback/LeetCode-Feedback#16872]
#### Your LeetCode username

https://leetcode.com/charlie_kkb/

#### Category of the bug 
- [ ] Missing Test Cases 

#### Description of the bug

For the testcase "AA" it returns false because bobs wins, therefore for "BB" it should true because alice wins but it show that it also return false.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool winnerOfGame(string colors) {
        int n = colors.size(); 
        int count = 0;
        for(int i=1;i<colors.length()-1;i++) {
            char prev = colors.at(i-1);
            char curr = colors.at(i);
            char next = colors.at(i+1);
            if(prev == 'A' && curr == 'A' && next == 'A')
                count++;
            if(prev == 'B' && curr == 'B' && next == 'B')
                count--;
        }
        return count > 0;
    }
};
```

#### Language used for code

c++

#### Expected behavior

For the testcase "AA" , the bob wins because A did not make make any changes so it returns false , but for the testcase "BB" , the bob did not able to make any changes so now this time the Alice wins, Thats,why it should return true but it shows false is true for this test case.

#### Screenshots

![Screenshot 2023-10-02 200736](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/96369750/d50b2f8e-cf84-452c-838c-ad90f88781bc)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Please ask your question in the discussion forum.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
