### ISSUE TITLE
Missing test case in 682. Baseball Game

### ISSUE THREAD

**Issue by andreev-max** [LeetCode-Feedback/LeetCode-Feedback#16878]
#### Your LeetCode username
andreev-dev

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

I saw that there plenty of submitted solutions where guys heavily relay on the last elem in the array. But if we create the initial array
of operations started with 'D' or "C", so their solutions will become invalid, because if we have an empty array, so arr[arr.length -1] will be undefined => undefined + undefined or undefined * 2 => NaN. Period. The logic has just been broken. So please cover this gap with some tests

#### Code you used for Submit/Run operation

```
function calPoints(operations: string[]): number {
  const stack: number[] = []

  for (const op of operations) {

    switch(op) {
      case '+':
        stack.push(stack.at(-1) + stack.at(-2))
        break;
      case 'D':
        stack.push(stack.at(-1) * 2)
        break;
      case 'C':
        stack.pop()
        break;
      default:
        stack.push(+op)
    }
  }

  return stack.reduce((acc,cur) => acc + cur,0)
};
```

#### Language used for code

TypeScript

#### Screenshots
<img width="636" alt="Screenshot 2023-10-02 at 20 30 32" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/70817598/9a2e2c26-bde2-43eb-a415-0625e8f7454f">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Please read the constraints

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
