### ISSUE TITLE
305. Number of Islands II

### ISSUE THREAD

**Issue by Shubashree** [LeetCode-Feedback/LeetCode-Feedback#16882]
#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

Positions: [[0,0],[2,0],[0,1],[2,1],[0,2],[2,2],[0,1],[1,2]]
Correct output: [1,2,2,2,2,2,2,2]
Incorrect expected output: [1,2,2,2,2,2,2,1]

Nowhere is it mentioned in the question that adding a position again (in this case [0,1]) flips the land back into water:

Question description:
> You are given an empty 2D binary grid grid of size m x n. The grid represents a map where 0's represent water and 1's represent land. Initially, all the cells of grid are water cells (i.e., all the cells are 0's).

> We may perform an add land operation which turns the water at position into a land. You are given an array positions where positions[i] = [ri, ci] is the position (ri, ci) at which we should operate the ith operation.

> Return an array of integers answer where answer[i] is the number of islands after turning the cell (ri, ci) into a land.

> An island is surrounded by water and is formed by connecting adjacent lands horizontally or vertically. You may assume all four edges of the grid are all surrounded by water.

#### Code you used for Submit/Run operation

```
class UnionFind:
    def __init__(self, m, n):
        self.count = 0
        self.rank = [1] * m * n
        # Indexed by position
        self.root = list(range(m*n))
    
    def find(self, x):
        if self.root[x] == x:
            return self.root[x]
        
        self.root[x] = self.find(self.root[x])
        return self.root[x]
    
    def union(self, x, y):
        rootX = self.find(x)
        rootY = self.find(y)

        if self.rank[rootX]>self.rank[rootY]:
            self.root[rootY] = rootX
        elif self.rank[rootY]>self.rank[rootX]:
            self.root[rootX] = rootY
        else:
            self.root[rootY] = rootX
            self.rank[rootX]+=1
        

class Solution:
    def numIslands2(self, m: int, n: int, positions: List[List[int]]) -> List[int]:

        uf = UnionFind(m,n)

        positions_oned = collections.OrderedDict()
        visited = set()
        result = []

        directions = [(0, -1), (0, 1), (1,0), (-1, 0)]

        def calconedindex(x,y,m,n):
            return x*n+y

        for pos1 in positions:
            position = pos1[0]*n+pos1[1]
            positions_oned[position] = position

            adjacents = []
            
            for x,y in directions:
                if 0<=pos1[0]+x<m and 0<=pos1[1]+y<n:
                    # Union only if any of the adjacents are == 1
                    adjacents.append(calconedindex(pos1[0]+x, pos1[1]+y, m, n))

            for adjacent in adjacents:
                if 0<=adjacent<m*n and adjacent in positions_oned:
                    uf.union(position, adjacent)
                    visited.add(adjacent)
            visited.add(position)

            num_islands = {uf.root[x] for x in visited}
            result.append(len(num_islands))
        return result
        
```

#### Language used for code
Python3

#### Expected behavior
Expected the addition of land again at (0,1) to cause no effect on the result. Nowhere is it mentioned in the question that adding a position again (in this case [0,1]) flips the land back into water:

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link that you submitted to reach this result.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Shubashree** [comment]
Hi @LC-Pam , the code used to reproduce this issue is linked in the Issue description above. Please feel free to reach out if you have any questions

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
