### ISSUE TITLE
Missing Test Case - 2875. Minimum Size Subarray in Infinite Array

### ISSUE THREAD

**Issue by yumkam** [LeetCode-Feedback/LeetCode-Feedback#16880]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Solution was accepted, but fails with test case linked below:
[link](https://gist.github.com/yumkam/f1e50ab7a9ca7ca31e020143b28b03fb/raw/50178531471d97374b5c5909bcdc8c0ead301f83/2875-testcase-10-1-1e5-1e5plus10.txt)

#### Code you used for Submit/Run operation

```c++
// code not mine, seen chat
class Solution {
public:
    int minSizeSubarray(vector<int>& nums, int target) {
        int min_len = 1e6; 
        int n = nums.size()*(target/reduce(nums.begin(), nums.end(), 0ll));
        target = target % reduce(nums.begin(), nums.end(), 0ll);
        int len = 0;
        int cur_sum = 0;
        for (int i = 0; i + len < 1e5;){
            len++;
            cur_sum += nums[(i + len - 1) % nums.size()];
            while (cur_sum > target){
                cur_sum -= nums[i++ % nums.size()];
                len--;
            }
            if (cur_sum == target){
                min_len = min(len, min_len);
            }
        }
        return min_len < 1e6 ? min_len + n: -1;
    }
};
```

#### Language used for code
C++

#### Additional context

This testcase catches real bug in real submission, by real person (but not me :-)), but I'm not sure if this bug can be *popular enough* to warrant adding this (pretty big and specific) test case. At your discretion.
Testcase generated by python code:
```python
#!/usr/bin/env python3
print([10]+[1]*int(1e5-2)+[int(1e5)])
print(int(1e5+10))
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

We can't add the test case currently because of technical issues.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
