### ISSUE TITLE
188. 买卖股票的最佳时机 IV 题目界面的测试用例区域变成空白

### ISSUE THREAD

**Issue by mantoufan** [LeetCode-Feedback/LeetCode-Feedback#16889]
> 
**你的 LeetCode 用户名**
mantoufan

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
[188. 买卖股票的最佳时机 IV](https://leetcode.cn/problems/best-time-to-buy-and-sell-stock-iv/submissions/) 题目的测试用例 Bug 如下：
1. 仍然显示老版本
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/4961543/964c1029-722f-4f88-8816-f908384375b0)
2. 如果像老版本那样，直接修改，会变为空白
    如图，我按了退格键
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/4961543/43a5c8c2-dce0-4caf-98c8-3fa4b400ad0c)
3. 如果像新版本那样，提交后，选择`添加到测试用例`，会直接变为空白
    如图，先提交，发现失败的测试用例，选择 `添加到测试用例`
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/4961543/98172d43-224c-45da-b153-6a7be37c00a3)
    回到测试用例，变成空白
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/4961543/81ee1d3c-023f-4dfb-b1c9-ee31624865b4)

**Comment by amcones** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by feiceh** [comment]
感谢反馈，当前积分已发放至 ID：mantoufan，请查收～
