### ISSUE TITLE
Missing TestCase | 2871. Split Array Into Maximum Number of Subarrays

### ISSUE THREAD

**Issue by rpremOfficial** [LeetCode-Feedback/LeetCode-Feedback#16888]
#### Your LeetCode username
 rpremofficial

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug

I tried to debug my own code of Q.3 (Biweekly Contest 114) and found that my code will give wrong answer on mentioned test case, but it got accepted that means there isn't any existing testcase which covers this case and solution. Adding this test case will cover lots of wrong solutions and will eventually help many people.

Input: nums = [1, 1, 1]
Expected Output: 1

#### Code you used for Submit/Run operation

```
// 2871. Split Array Into Maximum Number of Subarrays
class Solution {
public:
    int maxSubarrays(vector<int>& nums) {
        long long mini = 1;
        
        for(int i=0; i<nums.size(); i++){
            mini &= nums[i];
        }
        
        int count = 0;
        
        int i = 0;
        long long temp = nums[0];
        while(i < nums.size()){
            temp &= nums[i];
            
            if(temp == mini){
                count++;
                
                if(i != nums.size() -1){
                    temp = nums[i+1];
                }
            }
            
            i++;
        }
        
        return count == 0? 1: count;
    }
};
```

#### Language used for code
 C++

#### Expected behavior

Consider Input: nums = [1, 1, 1]
Expected Output: 1
My Output: 3

My solution got accepted, which means this testcase is missing and there isn't any other testcase as well to test it on similar cases.

#### Additional context

Q.3 of Biweekly Contest 114

Contest Link: https://leetcode.com/contest/biweekly-contest-114/
Problem link: https://leetcode.com/problems/split-array-into-maximum-number-of-subarrays/description/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The code received the Wrong Answer after submission: https://leetcode.com/submissions/detail/1066220987/

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by rpremOfficial** [comment]
Sure, thanks for your time

Submission that got accepted: https://leetcode.com/contest/biweekly-contest-114/submissions/detail/1063217784/

However, now I can see that that there is an extra testcase (no. 887) while there was only 886 at that time.

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
