### ISSUE TITLE
Missing Test Case - 55. Jump Game

### ISSUE THREAD

**Issue by zswen** [LeetCode-Feedback/LeetCode-Feedback#1688]
#### Your LeetCode username
HolySofa

#### Category of the bug
- [X ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

In constraints of the problem description. 0 <= nums[i][j] <= 10^5 should b 0 <= nums[i] <= 10^5

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
Hi @zswen 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @zswen 
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
