### ISSUE TITLE
Missing Test Case - 334. Increasing Triplet Subsequence

### ISSUE THREAD

**Issue by lazymonday** [LeetCode-Feedback/LeetCode-Feedback#1689]
#### Your LeetCode username

elzendich

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

The problem needs more testcase. 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool increasingTriplet(vector<int>& nums) {
        int maxVal = 0;
        stack<int> st;
        for(int i = nums.size()-1; i >= 0; --i) {
            if(maxVal == nums[i]) {
                continue;
            }
            while(!st.empty() and st.top() <= nums[i]) st.pop();
            st.push(nums[i]);
            maxVal = max(maxVal, nums[i]);
            
            if(st.size() >= 3) return true;
        }
        
        return false;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Above solution should have been WA instaed of AC

#### Additional context

Testcase [5,2,1,6,2,5,4] can help more accuracy of problem.
Thank you.

**Comment by lc-kay** [comment]
Hi @lazymonday 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @lazymonday 
Thank you for your time. The team reviewed your report and noticed the problem was recently updated and the code you submitted now fails.
