### ISSUE TITLE
Is Haskell language support in your roadmap?

### ISSUE THREAD

**Issue by just-some-dev** [LeetCode-Feedback/LeetCode-Feedback#169]
Do you have any plans for giving Haskell support?

**Comment by CooperCooperCooper** [comment]
Hi @just-some-dev,
Thank you for reaching out! You can check out [all of the languages we currently support ](https://support.leetcode.com/hc/en-us/articles/360011833974-What-are-the-environments-for-the-programming-languages-). And we know that Haskell is a really popular language, so I've relayed the request to add Haskell support to our team to consider.

**Comment by just-some-dev** [comment]
Thanks @CooperCooperCooper :)
