### ISSUE TITLE
Missing Test Case - 1512. Number of Good Pairs

### ISSUE THREAD

**Issue by saloni-laddha** [LeetCode-Feedback/LeetCode-Feedback#16903]
#### Your LeetCode username

sal_lad

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

The question did not cover an edge case where the input vector nums is [100, 100]. The expected answer should be 1. Because of this, I submitted an incorrect solution which got accepted.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int numIdenticalPairs(vector<int>& nums) {
        int ans = 0;
        vector<int>freq(101,0);
        for (int i=0;i<nums.size();i++)
        {
            freq[nums[i]]++;
        }
        for (int i=0;i<101;i++)
        {
            ans+=(freq[i]*(freq[i]-1))/2;
        }
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The test case [100, 100] is not covered in the question. An incorrect solution is also accepted.

#### Screenshots

Incorrect solution accepted -
<img width="415" alt="Screenshot 2023-10-03 at 11 01 13 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/38568776/2659fd76-6e4b-4310-97b3-c9e0024ed4a9">
Correct solution -
<img width="415" alt="Screenshot 2023-10-03 at 11 01 02 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/38568776/337a4adc-f0aa-44f4-8e2a-3db5a45fcac6">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
