### ISSUE TITLE
Missing Test Case - 1971. Find if Path Exists in Graph

### ISSUE THREAD

**Issue by el-hopaness-romtic** [LeetCode-Feedback/LeetCode-Feedback#16904]
#### Your LeetCode username
el-hopaness-romtic

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Currently, when using "disjoint set union" structure to solve the task, it is possible to use an array of `uint16_t` for storing parent nodes, although `n` can be equal to 200000

#### Code you used for Submit/Run operation
```
class Solution {
public:
    uint16_t* parents;

    bool validPath(int n, vector<vector<int>>& edges, int source, int destination) {
        parents = new uint16_t[n];
        for (int i = 0; i < n; ++i) parents[i] = i;

        for (auto& edge: edges) parents[findParent(edge[0])] = findParent(edge[1]);

        return findParent(source) == findParent(destination);
    }

    int findParent(int elem) {
        uint16_t& parent = parents[elem];
        if (parent == elem) return elem;
        return parent = findParent(parent);
    }
};
```
https://leetcode.com/problems/find-if-path-exists-in-graph/submissions/1066100474/

#### Language used for code
C++

#### Expected behavior
The accepted solution must pass the test shown in the screenshot below correctly

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/60661917/c29bea98-7493-4c7d-a96e-84a91609d674)

#### Additional context
```
199998 = 0b00000000000000110000110100111110 (int, 32 bits)
3390   =                 0b0000110100111110 (uint16_t, 16 bits)
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
