### ISSUE TITLE
Missing Test Case - 98. Validate Binary Search Tree

### ISSUE THREAD

**Issue by balajiram** [LeetCode-Feedback/LeetCode-Feedback#1690]
#### Your LeetCode username
balajiram

#### Category of the bug
- Submission error, in-correct result for a test case

#### [Problem](https://leetcode.com/explore/interview/card/facebook/52/trees-and-graphs/266/) description
- Validate Binary Search Tree
```
/**
 * Definition for a binary tree node.
 * function TreeNode(val, left, right) {
 *     this.val = (val===undefined ? 0 : val)
 *     this.left = (left===undefined ? null : left)
 *     this.right = (right===undefined ? null : right)
 * }
 */
 ```

```
var isValidBST = function(root, idx=0) {
    const isEmpty = (node) => node === undefined || node === null;
    const isLeftNodeValid = (leftNode, ptr) => isEmpty(leftNode) || (leftNode < root[ptr]);
    const isRightNodeValid = (rightNode, ptr) => isEmpty(rightNode) || (rightNode > root[ptr]);

    const isValid = (ptr) => isLeftNodeValid(root[(2*ptr)+1], ptr) && isRightNodeValid(root[(2*ptr)+2], ptr);
 
    while(idx < root.length && root[idx] !== null) {
         if(isValid(idx)){
             idx++;
         } else {
            return false;
         }
     }
     return true;
}
```
- Javascript

#### Description of the bug
Wrong output for input `[5,1,4,null,null,3,6],` during submission. But When I test my code using this input, it produced the correct output

#### Code you used for Submit/Run operation

```
/**
 * @param {TreeNode} root
 * @return {boolean}
 */
var isValidBST = function(root, idx=0) {
    const isEmpty = (node) => node === undefined || node === null;
    const isLeftNodeValid = (leftNode, ptr) => isEmpty(leftNode) || (leftNode < root[ptr]);
    const isRightNodeValid = (rightNode, ptr) => isEmpty(rightNode) || (rightNode > root[ptr]);

    const isValid = (ptr) => isLeftNodeValid(root[(2*ptr)+1], ptr) && isRightNodeValid(root[(2*ptr)+2], ptr);
 
    while(idx < root.length && root[idx] !== null) {
         if(isValid(idx)){
             idx++;
         } else {
            return false;
         }
     }
     return true;
};

```

#### Language used for code
Javascript

#### Expected behavior

When run the function for the following input its return **false**, but when I submit the solution, the submission got failed stating that function is returning **true** for the same usecase

Input used: `[5,1,4,null,null,3,6],`

**Comment by lc-kay** [comment]
<img width="1430" alt="Screen Shot 2020-12-18 at 11 52 34 M" src="https://user-images.githubusercontent.com/70870126/102655670-912b5c00-4127-11eb-89ca-e2ec387a7236.png">
@balajiram I just ran your code and got the Wrong Answer for both run code and submit. Please refer to the screenshot. If you receive something different on your end, please include a screenshot of it and I will reopen this issue. Thank you!

**Comment by balajiram** [comment]
@lc-kay 

If you run the code outside the integrated terminal, the solution I wrote return **false** for the input `[5,1,4,null,null,3,6]`. but leetcode integrated terminal is returning **true** as the result for the same input.

See the screen shot which I ran inside the browse console terminal

<img width="824" alt="Screen Shot 2020-12-18 at 7 25 39 PM" src="https://user-images.githubusercontent.com/3531530/102679802-534e2800-4167-11eb-8e3a-d7abd44acbe0.png">

**Comment by lc-kay** [comment]
@balajiram Unfortunately, since we don't have access to any outside console terminal, we are unable to pinpoint the difference between the output for the same code. We are only able to troubleshoot any discrepancies that occurred on our site. Thank you for understanding.
