### ISSUE TITLE
Missing Test Case - 2887. Fill Missing Data

### ISSUE THREAD

**Issue by ReadingHui** [LeetCode-Feedback/LeetCode-Feedback#16915]
#### Your LeetCode username

cc44h16a

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

Using fillna on the whole dataframe also passed the test.

#### Code you used for Submit/Run operation

```
import pandas as pd

def fillMissingValues(products: pd.DataFrame) -> pd.DataFrame:
    return products.fillna(0)
```

#### Language used for code

python

#### Expected behavior

There should be a testcase with NaN in columns other than 'quantity' so that plain fillna(0) on the whole dataframe will not pass.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
