### ISSUE TITLE
371. Sum of Two Integers  question

### ISSUE THREAD

**Issue by yang203000** [LeetCode-Feedback/LeetCode-Feedback#1691]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The question says "Calculate the sum of two integers a and b, but you are not allowed to use the operator + and -", why I send answer using "+" can pass? 

#### Code you used for Submit/Run operation

```
public class Solution {
    public int GetSum(int a, int b) {
        return a+b;
    }
}
```

#### Language used for code

C#

admin

**Comment by zerotrac** [comment]
"Now allowed" means something banned during an interview.

**Comment by lc-kay** [comment]
Hi @yang203000 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@yang203000 Our team has reviewed your report and concluded that "Not allowed" means something banned during an interview. We cannot check if you used + or - in the code. Thank you for your time!
