### ISSUE TITLE
Invalid test case - 172. Factorial Trailing Zeroes

### ISSUE THREAD

**Issue by cplyon** [LeetCode-Feedback/LeetCode-Feedback#1692]
#### Your LeetCode username
cplyon

#### Category of the bug
- [x] Question
- [X] Solution
- [ ] Language

#### Description of the bug
The problem constraints are: "1 <= n <= 104", however my submission failed due to the testcase where n = 0, which is outside the constraints.

#### Code you used for Submit/Run operation

```
import math


class Solution:
    def trailingZeroes(self, n: int) -> int:
        if n < 1:
            return 0

        f = math.factorial(n)
        zeroes = 0
        while f % 10 == 0:
            if f % 10 == 0:
                zeroes += 1
            f //= 10

        return zeroes
```

#### Language used for code
Python
<img width="1161" alt="Screen Shot 2020-12-18 at 10 15 32 AM" src="https://user-images.githubusercontent.com/3971229/102647055-fd06c800-4119-11eb-9641-2ab79c4ec15d.png">

#### Expected behavior
I expect either the constraints to be updated to include zero as a valid input, or the testcase where n = 0 is removed.

**Comment by lc-kay** [comment]
Hi @cplyon 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @cplyon 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
