### ISSUE TITLE
Editorial - Incorrect description in image in approach 3 in 4. Median of Two Sorted Arrays

### ISSUE THREAD

**Issue by kenlau46** [LeetCode-Feedback/LeetCode-Feedback#16926]
#### Your LeetCode username

kenlau

#### Category of the bug
- [x] Solution

#### Description of the bug

In Editorial Approach 3, in the 5-th image, the description `maxLeftB < minRightA` is incorrect, please see the red box of attached screenshot in the Screenshots section

#### Expected behavior

The image is describing the case where `minRightA` is too small, so the correct description should be  `maxLeftB > minRightA` instead

#### Screenshots

<img width="944" alt="Screenshot 2023-10-04 at 12 35 08" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/7280584/bdf91f24-2864-447a-b7c7-1f4e7b3f55c6">

P.S. Thank your the solutions, it helps me a lot in understanding the logic behind, it is the clearest solution I have seen for this question.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
