### ISSUE TITLE
Missing Test Case - 706. Design HashMap

### ISSUE THREAD

**Issue by incognion** [LeetCode-Feedback/LeetCode-Feedback#16920]
#### Your LeetCode username

[forleet](https://leetcode.com/forleet/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

My code is getting accepted on submission, in spite of failing on the following test case, which is within the given constraints of the question:
```
["MyHashMap","put","put","get","get","get","put","get","remove","get"]
```
```
[[],[1,1],[2,2],[1000000],[1],[3],[2,1],[2],[2],[2]]
```

#### Code you used for Submit/Run operation

```
// Design HashMap
class MyHashMap {
public:
    int data[1000001];
    MyHashMap() {
        fill(data, data + 1000000, -1);
    }
    void put(int key, int val) {
        data[key] = val;
    }
    int get(int key) {
        return data[key];
    }
    void remove(int key) {
        data[key] = -1;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The output of the program:
```
[null,null,null,0,1,-1,null,1,null,-1]
```
Expected Output:
```
[null,null,null,-1,1,-1,null,1,null,-1]
```
Thus, this solution should not be accepted

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/97580124/8c56a6b6-8730-44d2-a094-d74bc54a260b) <br/>
But, my code is getting accepted on submission: <br/>
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/97580124/9f4b69ab-c191-4bd1-b956-39b399f82ec7)

#### Additional context

The following code solution will give the right output on all the test cases (including this one):
```
class MyHashMap {
public:
    int data[1000001];
    MyHashMap() {
        fill(data, data + 1000001, -1);
    }
    void put(int key, int val) {
        data[key] = val;
    }
    int get(int key) {
        return data[key];
    }
    void remove(int key) {
        data[key] = -1;
    }
};
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
