### ISSUE TITLE
1409. Queries on a Permutation With Key

### ISSUE THREAD

**Issue by agrawalishaan** [LeetCode-Feedback/LeetCode-Feedback#16932]
#### Your LeetCode username
agrawalishaan

#### Category of the bug
- [X ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the question it writes:
<img width="644" alt="Screenshot 2023-10-04 at 10 54 41 AM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/113543798/6531cea3-f1d5-4e92-8b71-7d818ed16b8c">
For `P.`, the period should go outside the formatting to be standard with the others.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
