### ISSUE TITLE
Missing Test Case - 706. Design HashMap

### ISSUE THREAD

**Issue by artanmerko** [LeetCode-Feedback/LeetCode-Feedback#16933]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
-  Missing Test Cases 

#### Code you used for Submit/Run operation

```

var MyHashMap = function() {
    this.data = new Array (1000001)
};

/** 
 * @param {number} key 
 * @param {number} value
 * @return {void}
 */
MyHashMap.prototype.put = function(key, value) {
    this.data[key]=value;
};

/** 
 * @param {number} key
 * @return {number}
 */
MyHashMap.prototype.get = function(key) {
    if(this.data[key]!==undefined){
        return this.data[key]
    }
    return -1
};

/** 
 * @param {number} key
 * @return {void}
 */
MyHashMap.prototype.remove = function(key) {
    this.data[key]=undefined
};

/** 
 * Your MyHashMap object will be instantiated and called as such:
 * var obj = new MyHashMap()
 * obj.put(key,value)
 * var param_2 = obj.get(key)
 * obj.remove(key)
 */
```

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/97398977/a28b1cd0-f22b-4aaa-b409-87fbb39b1f1b)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
