### ISSUE TITLE
Missing Test Case - 2405. Optimal Partition of String

### ISSUE THREAD

**Issue by Lazarorx** [LeetCode-Feedback/LeetCode-Feedback#16938]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code
<Python>

**Comment by Lazarorx** [comment]
Criei um conjunto chamado seen_chars para rastrear os caracteres que já vimos em substrings anteriores. Usei um conjunto porque ele não permite elementos duplicados.

Iniciei uma variável substr_count para contar o número de substrings.

Percorri a string s caractere por caractere.

Para cada caractere, verifiquei se ele já está no conjunto seen_chars. Se estiver, isso significa que encontramos um caractere repetido, então incrementamos o contador de substrings (substr_count) e limpamos o conjunto seen_chars para começar uma nova substring.

Se o caractere não estiver no conjunto seen_chars, simplesmente o adicionamos a esse conjunto.

Lembre-se de contar a última substring após o loop, pois ela não foi contada dentro do loop.

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
