### ISSUE TITLE
Missing Test Case - 421. Maximum XOR of Two Numbers in an Array

### ISSUE THREAD

**Issue by RasMisha** [LeetCode-Feedback/LeetCode-Feedback#1694]
#### Your LeetCode username
nonatomicgames

#### Category of the bug
* [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
The problem needs more testcase.

#### Code you used for Submit/Run operation
```
class Solution {
    public int findMaximumXOR(int[] nums) {
        Arrays.sort(nums);
        int o = 0;
        for (int n : nums) {
            o |= n;
        }
        int max = 0;
        int i = 0, j = nums.length - 1;
        while (i < j) {
            max = Math.max(max, nums[i] ^ nums[j]);
            if (o - nums[i] > nums[j]) { // Equivalent to: nums[i] ^ o > nums[j]
                i++;
            } else {
                j--;
            }
        }
        return max;
    }
}
```

#### Language used for code
Java

#### Expected behavior
Above solution should have been WA instaed of AC

#### Additional context
Expected answer 3
Actual answer 2

**Comment by lc-kay** [comment]
@RasMisha Your code receives Wrong Answer. Please refer to the screenshot. Thank you for your time!
<img width="1435" alt="Screen Shot 2020-12-18 at 12 08 42 PM" src="https://user-images.githubusercontent.com/70870126/102657053-d18bd980-4129-11eb-88ee-7f8c475586c7.png">

**Comment by RasMisha** [comment]
Thanks! Is it because someone found earlier?
Because I create this 3 monthes ago on leetcode direcatly.

**Comment by lc-kay** [comment]
@RasMisha Our team is constantly updating the test case set and when I reproduced the issue, your code resulted in a wrong answer.
