### ISSUE TITLE
Missing Test Case - 771. Jewels and Stones

### ISSUE THREAD

**Issue by Pranav108** [LeetCode-Feedback/LeetCode-Feedback#1695]
#### Your LeetCode username
Pranav_

#### Category of the bug
- [ ] Solution
- [ ] TestCases

#### Description of the bug
i tried with a random testcase ,and my code hasn't pass my testcase ,but it passes whole test(leecode generated)
i tried with this testcase--
"aAhfhtjnbvcVBNHGTFDBHNJ"
"AnhbvcderftgyhbnmjkjuhygvfcxNBVCXSDWsaqwedf"
 

#### Code you used for Submit/Run operation

int numJewelsInStones(char * J, char * S){
int i=0,j,count=0;
    while(J[i]!='\0'){
        j=0;
        while(S[j]!='\0'){
            if(J[i]==S[j])
                count++;
            j++;
        }
        i++;
    }
    return count;
}
```

#### Language used for code
C


#### Expected behavior
it shoud supposed to pass my enterd testcase but it didn't although it passes all leetcode testcases



#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->
![Screenshot (211)](https://user-images.githubusercontent.com/56934594/102653476-008b6500-4195-11eb-915a-ed3263a240d9.png)




#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by lc-kay** [comment]
Hi @Pranav108 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Pranav108 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
