### ISSUE TITLE
Missing Test Case - 6. Zigzag Conversion

### ISSUE THREAD

**Issue by bjmgales** [LeetCode-Feedback/LeetCode-Feedback#16954]
#### Your LeetCode username
bjmgales

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Testcase  31 / 1157
The output is the same as the expected answer, yet the case is failed.

#### Code you used for Submit/Run operation

```
<class Solution {
public:
    string convert(string s, int numRows) {
        std::string Tab[numRows];
        std::string ret;

        if (numRows == 1)
            return s;
        for (int i = 1, c = -1; s[++c]; i++){
            Tab[i - 1] += s[c];

            if (i == numRows)
                while (i != 1 && s[c]){
                    i--;
                    c++;
                    Tab[i - 1] += s[c];
                }
        }
        for (int i = 0; i < numRows; i++){
            ret += Tab[i];
        }
        return (ret);
    }
};
```

#### Language used for code
C++ 

#### Expected behavior
Either validate the case cause i have the expected output,  or providing relevant information on why i failed the case even if having expected output.

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team

**Comment by bjmgales** [comment]
Hello,

Thanks for your answer,

The test case says : output : "AB", expected output "AB"
If I cout the returned variable, it also outputs AB
What am I missing here ?

I joined you a picture of the test result.
