### ISSUE TITLE
Problem 1001 Grid Illumination Incorrect Problem Description

### ISSUE THREAD

**Issue by LeetKing1** [LeetCode-Feedback/LeetCode-Feedback#1696]
For the explanation of the 1st query in the first example, the result should be 0 instead of 1:

The 1st query asks if the lamp at grid[1][0] is illuminated or not (the blue square). It is not illuminated, so set **ans[1] = 1**. Then, we turn off all lamps in the red rectangle.

The 1st query asks if the lamp at grid[1][0] is illuminated or not (the blue square). It is not illuminated, so set **ans[1] = 0**. Then, we turn off all lamps in the red rectangle.

**Comment by lc-kay** [comment]
Hi @LeetKing1 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @LeetKing1 
Thank you for your time. We've used your feedback to update the problem. Please provide to LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by LeetKing1** [comment]
Hey,

My leetcode id is @blackspinner

Thanks
