### ISSUE TITLE
Missing Test Case - 1816. Truncate Sentence

### ISSUE THREAD

**Issue by Riyazul555** [LeetCode-Feedback/LeetCode-Feedback#16960]
#### Your LeetCode username
<Riyazul Islam>

#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [x] Missing Test Cases 

#### Description of the bug
<when spaces are increased a unique test case fails>

#### Code you used for Submit/Run operation

```
class Solution {
public:
    string truncateSentence(string s, int k) {
        int n = s.length();
        int r = 0;
        string s1;
        for(int i=0;i<n;i++){
           if(s[i]==' '){
               r++;
           }
           if(r==k){
               break;
           }
           s1.push_back(s[i]);
        }
        return s1;
    }
};
```

#### Expected behavior
<"This is a test sentence with"
[Test case.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/12822183/Test.case.txt)
>

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The test case already exists. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
