### ISSUE TITLE
881.Boats to Save People-People weight range not specified

### ISSUE THREAD

**Issue by iiShreya** [LeetCode-Feedback/LeetCode-Feedback#16965]
It is not specified that people's weights are between 1 to limit. So it becomes confusing and incorrect if the problem solver assumes people could be of greater weight than limit.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
