### ISSUE TITLE
Missing Test Case - 605. Can Place Flowers

### ISSUE THREAD

**Issue by IamXGW** [LeetCode-Feedback/LeetCode-Feedback#16973]
#### Your LeetCode username

IamXGW

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets WA on the following testcase:
[0, 1, 0, 0, 0, 0]
2

#### Code you used for Submit/Run operation

```
// Can Place Flowers
class Solution {
    public boolean canPlaceFlowers(int[] flowerbed, int n) {
        int len = flowerbed.length;
        int m = 0, i = 0;
        while (i < len) {
            if (flowerbed[i] == 0) {
                if (i < len - 1 && flowerbed[i + 1] == 1) i += 3;
                else m += 1;
            }
            i += 2;
        }
        return m >= n;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Output: false
Expected: true

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
