### ISSUE TITLE
359. Logger Rate Limiter

### ISSUE THREAD

**Issue by mjnovice** [LeetCode-Feedback/LeetCode-Feedback#1697]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

It is not clear from the problem description what is meant by the last 10 seconds.
Also, it is not specified that the timestamps would be in nondecreasing sequence, introducing this change,
leads to unspecified behaviour/test case failing.

**Comment by lc-kay** [comment]
Hi @mjnovice 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @mjnovice
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
