### ISSUE TITLE
Missing Test Case - 268. Missing Number

### ISSUE THREAD

**Issue by B-IJoe1** [LeetCode-Feedback/LeetCode-Feedback#16987]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The code is supposed to find the missing number in an array from [0...n] 

#### Code you used for Submit/Run operation

```
// Two Sum
nums = [0, 3, 4, 5, 7, 8]

class Solution(object):
    def missingNumber(self, nums):
        """
        :type nums: List[int]
        :rtype: int
        """
        n = len(nums)
        expected_sum = (n * (n + 1)) / 2
        actual_sum = sum(nums)
        missing_number = expected_sum - actual_sum
        return int(missing_number)

```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
