### ISSUE TITLE
Description typo - 1420. Build Array Where You Can Find The Maximum Exactly K Comparisons

### ISSUE THREAD

**Issue by xelplogoog** [LeetCode-Feedback/LeetCode-Feedback#16992]
#### Your LeetCode username
c4tdog

#### Description of the bug
There is a typo in word `satisfy`

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2188302/707097de-d2f2-4202-b0bf-25d8389c04f8)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
