### ISSUE TITLE
Missing Test Case - 1420. Build Array Where You Can Find The Maximum Exactly K Comparisons

### ISSUE THREAD

**Issue by akshatmaheshwar** [LeetCode-Feedback/LeetCode-Feedback#16995]
#### Your LeetCode username

akshatmaheshwar78

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I got TLE for this testcase for my code when I ran it myself but the code got accepted when submitted.

#### Code you used for Submit/Run operation

```
// Build Array Where You Can Find The Maximum Exactly K Comparisons
class Solution {
    HashMap<String,Integer> cache = new HashMap<String,Integer>();
    public int numOfArrays(int n, int m, int k) {
        return recur(0,n,m,k,0);
    }
    private int recur(int i, int n, int m, int k, int currmax){
        if(i==n){
            if(k==0)return 1;
            else return 0;
        }
        String key = Integer.toString(i)+"#"+Integer.toString(k)+"#"+Integer.toString(currmax);
        if(cache.containsKey(key))return cache.get(key);
        long res = 0;
        for(int j=1;(k>0&&j<=m)||(k==0&&j<=currmax);j++){
            if(j>currmax) res+= recur(i+1,n,m,k-1,j);
            else res+= recur(i+1,n,m,k,currmax);
            res%=1000000007;
        }
        cache.put(key,(int)res);
        return (int)res;
    }
}
```

#### Language used for code

Java

#### Expected behavior

I expected to get a TLE but the code got accepted.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/77718425/368d8a84-b52c-4034-91ca-a87304cb0d6e)

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/77718425/e24cfdda-fb4b-4adb-866c-0fcc549176a2)

#### Additional context

The Missing Test Case is
[Missing Test Case - 1420. Build Array Where You Can Find The Maximum Exactly K Comparisons.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/12837180/Missing.Test.Case.-.1420.Build.Array.Where.You.Can.Find.The.Maximum.Exactly.K.Comparisons.txt)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by akshatmaheshwar** [comment]
I just want to let you know that I haven't received the LeetCoins yet. Can you please kindly check once? akshatmaheshwar78 is my profile name. Thnx.
