### ISSUE TITLE
Wrong test case [10,-10,10,-10,10,-10,10,-10]

### ISSUE THREAD

**Issue by kanch231004** [LeetCode-Feedback/LeetCode-Feedback#1699]
#### Your LeetCode username
kanch786 

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language

#### Description of the bug
This Questions has multiple test cases which has wrong result. [10,-10,10,-10,10,-10,10,-10] This test case should pass while it is failing. It has probably wrong solution against which it is checked. I've posted my solution which should pass all the valid test cases. Lot of people are facing difficulty as you might check Discuss section of this question.

#### Code you used for Submit/Run operation
```
// Partition Array Into Three Parts With Equal Sum
class Solution {
    public boolean canThreePartsEqualSum(int[] A) {       
        int sum = 0;
        for (int i = 0 ; i < A.length ; i++) {
            sum += A[i];
        }
        if (sum % 3 != 0)
            return false;           
        int tempSum = 0;
        int count = 0;
        for (int i = 0 ; i < A.length ; i++) {
            tempSum += A[i];
            if (tempSum == sum/3) {
                tempSum = 0;
                count++;
            }
        } 
        System.out.println("count "+count);
        return count == 3;        
    }
}
```

#### Language used for code
Java 

#### Expected behavior
[10,-10,10,-10,10,-10,10,-10] This test case should pass while it is failing. There is no way it can be partitioned into 3 different non-empty arrays whose sum is equal

#### Screenshots
<img width="361" alt="Screenshot 2020-12-19 at 11 02 01 AM" src="https://user-images.githubusercontent.com/32065373/102681699-ab2d7300-41e9-11eb-940f-255e00135b99.png">

**Comment by lc-kay** [comment]
@kanch231004 We can partition this in 3 parts: [10,-10,10,-10] [10,-10] [10,-10] with equal each part having zero sum. However, I will still relay this issue to our team to look into since many raised this question on discuss. Thank you for your time!
