### ISSUE TITLE
Unclear directions for 675. Cut Off Trees for Golf Event

### ISSUE THREAD

**Issue by SpaIns** [LeetCode-Feedback/LeetCode-Feedback#17]
**What kind of the bug**
- [X] problem
- [ ] solution

**Describe the bug**
Not a bug, but rather a description issue. There is no note in the problem as to what is a valid direction of travel; most matrix/graph problems will denote if you can only move up/down/left/right, or if you can move diagonal directions.  This problem does not, but expects you to only move Up/Down/Left/Right, as diagonal movements are considered invalid in the test case. In addition to this, the example cases also do not add any context as to what is a valid/invalid movement, as all example cases result in the same result whether you have 4 or 8 valid directions.  I suggest adding a quick note stating what is considered a valid movement.

**The code you submit/run**
```
NA
```

**Expected behavior**
NA

**Comment by CooperCooperCooper** [comment]
Hi @SpaIns,
Thank you for reaching out to us! We've updated the problem statement with more explanation to increase clarity. If you have any other feedback on this problem, please don't hesitate to let us know. We appreciate your support.
