### ISSUE TITLE
Unclear description and mess with parameters (Python 3) in 'Leftmost Column with at Least a One'

### ISSUE THREAD

**Issue by evgeni-nabokov** [LeetCode-Feedback/LeetCode-Feedback#170]
**What kind of the bug**
- [*] problem
- [*] language

**Describe the bug**
First, what is matrix `n * m`? n cols and m rows, or n rows and m cols? [Wikipedia defines](https://en.wikipedia.org/wiki/Matrix_(mathematics)) a matrix `n * m` as the matrix of `n` cols and `m` rows, but according to your code you defined it as `n` rows and `m` cols:
```
AssertionError
    assert 0 <= x < self.__m and 0 <= y < self.__n
```
Second, you messed with the parameter order in BinaryMatrix.get(x, y), because I have to call BinaryMatrix.get(y, x) to get the right value.
x should be not row index, but col index! If you insist that get(row, col) is correct order, then do not use x and y designations, use row and col instead.

**What language is your code written in**
Python 3

**The code you submit/run**
```
class Solution:
    def leftMostColumnWithOne(self, binaryMatrix):
        h, w = binaryMatrix.dimensions() # height and width of the matrix
        x = w - 1
        y = 0
        while x >= 0 and y < h: 
            bit = binaryMatrix.get(y, x)
            if bit == 1:
                x -= 1
            else:
                y += 1
        if x == w - 1:
            return -1
        else:
            return x + 1
```

**Expected behavior**

1. Define what matrix n * m is.
2. Fix BinaryMatrix.get(x, y) or use different designations.

**Screenshots**
N/A

**Additional context**
None

**Comment by CooperCooperCooper** [comment]
Hi @evgeni-nabokov,
Thank you for reaching out to us! I've relayed this issue to our team to investigate.

**Comment by evgeni-nabokov** [comment]
I think if you replace 'x' with 'col' and y with 'row', it will be better.

**Comment by CooperCooperCooper** [comment]
Hi @evgeni-nabokov,
Thank you for the feedback! We've updated the problem statement accordingly. Please reach out to our main support channel with your LeetCode username, Github user information, and this issue to claim your rewards!
