### ISSUE TITLE
«Third maximum number» Editorial

### ISSUE THREAD

**Issue by aleksandr-kiliushin** [LeetCode-Feedback/LeetCode-Feedback#17003]
#### Your LeetCode username
aleksandr-kiliushin

#### Category of the bug
- [ ] Question
- [✅] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### URL
https://leetcode.com/problems/third-maximum-number/editorial/

#### Screenshots
1.
<img width="1174" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/65129988/af2881be-b522-4c94-a9c9-1ac87fe2f980">

2.
<img width="1140" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/65129988/fb8cbd32-28d4-4361-b7ec-e3dfac4f9670">

3.
<img width="737" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/65129988/edf73760-b98f-4e7e-99dd-8e37a9bf748c">

4.
<img width="1176" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/65129988/87f32aae-07b8-40df-bed8-2f7f6da0d084">

5.
<img width="1022" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/65129988/b0b27920-622b-4d44-84fd-06bacd7bf246">

6.
<img width="784" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/65129988/177b45e4-d955-4c97-8cde-9ea8eb0c23f2">

7.
<img width="812" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/65129988/c602aceb-5649-4ce9-aed7-25d2f82acfab">

8.
<img width="1368" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/65129988/facfcb88-0381-4b52-b01d-1bac0026e2c1">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
