### ISSUE TITLE
Missing Test Case - 334. Increasing Triplet Subsequence

### ISSUE THREAD

**Issue by leozhang1** [LeetCode-Feedback/LeetCode-Feedback#1700]
#### Your LeetCode username

leozhang1

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Contribute a testcase

#### Description of the bug

No bug. Just wanted to add a testcase

#### Code you used for Submit/Run operation

```
class Solution:
    def increasingTriplet(self, As: List[int]) -> bool:
        
        int_max = 2 ** 31 - 1
        
        # I may need to make these nullable because
        # otherwise it will fail my custom testcase:
        # [1, 2, 2147483647]
        i, j, k = int_max, int_max, int_max
        
        for a in As:
            
            # less than or equal instead of strictly less than to avoid
            # duplicates when falling thru to the next else-if branch
            if (a <= i):
                i = a
            elif (a <= j):
                j = a
            elif (a <= k):
                k = a
                
        if j == int_max or k == int_max: return False
        
        return i < j and j < k
```

#### Language used for code

Python

#### Expected behavior

N/A

#### Screenshots

N/A

#### The Custom testcase I want to contribute

[1, 2, 2147483647]

**Comment by lc-kay** [comment]
@leozhang1 When I ran your code, it resulted in Wrong Answer. Can you please provide an accepted code that this test case fails on? Then, I will reopen the issue. Thank you for your time!
