### ISSUE TITLE
Missing Test Case - 26. Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by HuzaifaTanzeel** [LeetCode-Feedback/LeetCode-Feedback#17005]
#### Category of the bug
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Remove Duplicates from Sorted Array

class Solution {
public:
    int removeDuplicates(vector<int>& nums) {
        int temp;
        int count=0;

        for(int i=0;i<nums.size();i++){
            if(i==0){
                temp=nums[0];
                nums[count]=nums[0];
                count++;
                continue;
            }
            if(temp!=nums[i]){
                nums[count]=nums[i];
                count++;
                temp=nums[i];
            }

        }        
        return count;        // This return value should be equal to the nums.size() but nums.size() is different here and code gets approved
    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by HuzaifaTanzeel** [comment]
Dear LC_M,

I hope this message finds you well. Thank you for your prompt response and
for looking into the issue I encountered with my code submission on
LeetCode. I appreciate your assistance in resolving this matter.

Here are the requested details:

*Code Submission Link:*
- [My Publical code that is published](
https://leetcode.com/problems/remove-duplicates-from-sorted-array/solutions/4151475/remove-duplicates-from-sorted-array/
)
- [Code Submission Details](
https://leetcode.com/submissions/detail/1071242216/)

*The Missing Test Case / Bug:*
The problem arises when LeetCode's backend handles the code submission for
the "Remove Duplicates from Sorted Array" challenge. Specifically, there is
a discrepancy in how LeetCode processes the array `nums[]` after a user
returns an integer, denoted as "k," representing the number of unique
elements. Here's a breakdown of the issue:

1. I calculate the number of unique elements as "k."
2. I update the `nums[]` array from index 0 to k by placing the unique
elements in this range.
3. However, the elements in the array after index k are not removed, even
though all unique elements are guaranteed to be present from index 0 to
(k-1).
4. I return the integer "k," and LeetCode's backend returns elements from
index 0 to (k-1) in the `nums[]` array. This behavior is inconsistent with
the question's requirement, which is to remove duplicates.
5. As a result, the array still contains duplicate elements, and the
returned integer "k" is not equal to `nums.size()`, leading to code
approval despite the presence of duplicates.

To illustrate this issue, you can verify my point by adding the following
code snippet before returning the integer in my code:

```cpp
for(int i=0; i<nums.size(); i++){
     cout << nums[i] << endl;
}
```

Running this code will print duplicate elements beyond index (k-1).

*Logic that Needs Correction at LeetCode Backend:*

1. The returned integer should match the size of the `nums[]` array
because, after removing duplicates, `integer k == nums.size()`. However, in
my case, `nums.size()` is greater than "k," and `nums[]` still contains
duplicates.
2. The entire `nums[]` array should be returned because it becomes unique
after duplicate removal.

I hope this clarification helps address the issue effectively. Please let
me know if you need any further information or assistance. Your support in
resolving this matter is greatly appreciated.

Best regards,
*Huzaifa Tanzeel*

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
