### ISSUE TITLE
Missing Test Case - 2883. Drop Missing Data

### ISSUE THREAD

**Issue by kodimatrix** [LeetCode-Feedback/LeetCode-Feedback#17012]
#### Your LeetCode username
kodimatrix

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The problem statement specifies removing rows with missing values in the `name` column. However, the current test cases accept solutions that use the `dropna()` method on the entire dataframe.

#### Code you used for Submit/Run operation
```python
import pandas as pd

def dropMissingData(students: pd.DataFrame) -> pd.DataFrame:
    return students.dropna()
```

#### Language used for code
Pandas

#### Expected behavior
The solution should be rejected, as it does not strictly adhere to the requirement of only considering the 'name' column.

The test cases should be modified or additional test cases should be added to ensure solutions only remove rows where the `name` column has missing values. Solutions that apply `dropna()` on the entire dataframe without column specification should be rejected.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
