### ISSUE TITLE
Missing Test Case - 294. Flip Game II

### ISSUE THREAD

**Issue by zsq007** [LeetCode-Feedback/LeetCode-Feedback#17010]
#### Your LeetCode username

zsq007

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Some solutions passing the submission tests use "'+' * (4k+1)" as a False pattern, while it only holds for length == 1, 5, 9, and fails at 13. I suggest to add a test case of "+++++++++++++" with an expected result of True.

#### Code you used for Submit/Run operation

```
class Solution:
    def canWin(self, currentState: str) -> bool:
        
        currentState+='-'

        tt = 0 # length = 2 or 3
        win = 0 # the case flip firstly will win
        tmpS = 0 # current len of '+'

        for c in currentState:
            if c=='+':
                tmpS+=1
            else:
                if tmpS==2 or tmpS==3:
                    tt^=1       
                elif tmpS%2==0 or (tmpS-3)%4==0:
                    win^=tmpS
                tmpS = 0

        return win or tt
```

#### Language used for code

Python3

#### Expected behavior

The code returns False on this test case, while the expected result should be True.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
