### ISSUE TITLE
Incorrect test case of : 2873. 有序三元组中的最大值 I

### ISSUE THREAD

**Issue by JokerLoveAllen** [LeetCode-Feedback/LeetCode-Feedback#17016]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
superallen

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
测试用例和题目提示冲突：
提交答案时存在测试用例：[-3, -2, 1, 10]
题目描述: 1 <= nums[i]

**你使用的语言**
python3

**你提交或者运行的代码**
```
//有序三元组中的最大值 I
class Solution:
    def maximumTripletValue(self, A: List[int]) -> int:
        sck = []
        res = prev_max = -math.inf
        for e in A:
            res = max(res, prev_max * e)
            gap = 0
            if sck and sck[-1] > e:
                gap += sck[-1] - e
            else:
                sck.append(e)
            prev_max = max(gap, prev_max)
        return res
```

**期望行为**
描述你期望的结果

**屏幕截图**
![sSS](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/22656731/fa947d5d-cc31-4ea4-9eba-1075092c7642)

**额外的上下文**
答案按照题目提示编写，该错误测试用例导致出现了上述异常信息，请题目描述或提交测试用例一致！

**Comment by feiceh** [comment]
感谢反馈，当前题目已更新，奖励已发放，请查收。
