### ISSUE TITLE
Wrong Test Case

### ISSUE THREAD

**Issue by KHAJAMOINUDDINKHADRI** [LeetCode-Feedback/LeetCode-Feedback#17029]
#### Your LeetCode username
khajamoinuddinkhadri786

#### Category of the bug
- [ ] 589. N-ary Tree Preorder Traversal
- [ ] Below
- [ ] C++
- [ ] Wrong Test Cases 

#### Description of the bug
I am facing a issue with the test case,
[1, null] - for this case it is showing me an runtime error 
and If I remove the space before null i.e., [1,null] - for this it is working fine.
please resolve it, so when i submit it is not taking.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> preorder(Node* root) {
        vector<int> ans;
        if (root == NULL) {
            return ans;
        }
        stack<Node*> st;
        st.push(root);

        while(!st.empty()){
            Node* temp = st.top();
            st.pop();
            ans.push_back(temp->val);
            for(int i=temp->children.size()-1; i>=0; i--){
                st.push(temp->children[i]);
            }
        }
        return ans;
    }
};
```

#### Language used for code
 C++

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem number or name. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by KHAJAMOINUDDINKHADRI** [comment]
The question is,
589. N-ary Tree Preorder Traversal <https://leetcode.com/problems/n-ary-tree-preorder-traversal/> 

And the error I am getting is,

Runtime Error
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi

For test case,
[1, null]
If we remove space ‘ ‘ before null it is working like [1,null] , kindly resolve it.

Thank You

**Comment by KHAJAMOINUDDINKHADRI** [comment]
what is this ?
is a bug or wrong test case ?
is something wrong from my side ?

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Please ask your question in the discussion. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
