### ISSUE TITLE
Word Break. Same input different result on run and sumbit

### ISSUE THREAD

**Issue by GiorgosMarga** [LeetCode-Feedback/LeetCode-Feedback#1702]
#### Category of the bug
- [ ] Question
- [Yes ] Solution
- [ ] Language

#### Description of the bug

In the WordBreak question, when I sumbit my solution  I get a wrong answer but when i copy the input and paste it in the test case i get the right answer 

#### Code you used for Submit/Run operation

```
class Solution:
    def wordBreak(self, s: str, wordDict: List[str], memo={}) -> bool:
        if s in memo:
            return memo[s]
        if s == "": 
            return True
        
        for word in wordDict:
            if word in s and s.index(word) == 0:
                preffix = s[len(word):]
                result = self.wordBreak(preffix, wordDict, memo)
                if result:
                    memo[s] = True
                    return memo[s]
        
        memo[s] = False
        
        return False
        
```

#### Language used for code
Python

**Comment by lc-kay** [comment]
Hi @GiorgosMarga 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
