### ISSUE TITLE
Missing Test Case - 18. 4Sum

### ISSUE THREAD

**Issue by tanuiniko** [LeetCode-Feedback/LeetCode-Feedback#17023]
#### Your LeetCode username

tanuandyasu - https://leetcode.com/tanuandyasu/

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I've noticed that the LeetCode 4Sum problem (https://leetcode.com/problems/4sum/description/) is missing test cases that can help improve the coverage and robustness of the solution. I'd like to propose adding this test case to ensure that the problem's constraints are adequately tested.

#### Code you used for Submit/Run operation

```
class Solution {
    public List<List<Integer>> fourSum(int[] nums, int target) {
        List<List<Integer>> ans  = new ArrayList<>();
        Arrays.sort(nums);
        int pc=0;
        int nc=0;
        if(nums[0]==-1e9) nc++;
        if(nums[nums.length-1]==1e9) pc++;
        if(pc>0 && nc>0) {
            if(target!=0 && target!=1e9 && target!=-1e9) return ans;
        }
        else if(pc>0) {
            if(target!=1e9) return ans;
        }
        else if(nc>0) {
            if(target!=-1e9) return ans;
        }
        fourSum(nums,4,0,target,ans,new ArrayList<Integer>());
        return ans;
    }

    public void fourSum(int[] nums,int k,int start,int target,List<List<Integer>> ans,List<Integer> list){
        if(k==0) {
            if(target==0)ans.add(new ArrayList(list));
            return;
        }
        for(int i=start;i<nums.length;i++){
            if(i==start || nums[i]!=nums[i-1]){
                list.add(nums[i]);
                fourSum(nums,k-1,i+1,target-nums[i],ans,list);
                list.remove(list.size()-1);
            }
        } 
    }
}
```

#### Language used for code

java

#### Expected behavior

Input : 
Array=[1000000000 -1 -1 -1]
target = 999999997

Expected Output : 
[1000000000 -1 -1 -1]

This testcase gives [] empty array by the code i provided, where the expected output is [1000000000 -1 -1 -1]

and the provided code got accepted.

#### Proposed changes

1.  Add the new test case to the existing test suite for the 4Sum problem.
2.  Ensure that this solution's implementation does not get accepted.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by tanuiniko** [comment]
Hi,

Sure.
Thank you for letting me know and for your prompt response.
