### ISSUE TITLE
Missing Test Case - 1458. Max Dot Product of Two Subsequences

### ISSUE THREAD

**Issue by jhu04** [LeetCode-Feedback/LeetCode-Feedback#17020]
#### Your LeetCode username
jeffreyhu8

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
My wrong code is accepted because this test case is missing:
```
nums1 = [-1, 1]
nums2 = [1, -1]
```
Namely, my code checks if the answer is less than 0 by finding if `max(num1 * num2 for num1, num2 in zip(nums1, nums2))` is less than 0. This is incorrect; every pair in the Cartesian product of `nums1, nums2` should be checked, not just the pairs of elements that share the same indices.

#### Code you used for Submit/Run operation
```py
class Solution:
    def maxDotProduct(self, nums1: List[int], nums2: List[int]) -> int:
        if len(nums1) > len(nums2):
            nums1, nums2 = nums2, nums1
        
        maxPairProduct = max(starmap(operator.mul, zip(nums1, nums2)))
        if maxPairProduct < 0:
            return maxPairProduct

        cache = [0] * (len(nums1) + 1)
        nxt = cache.copy()
        for num2 in nums2:
            for i, num1 in enumerate(nums1):
                nxt[i + 1] = max(
                    nxt[i],
                    cache[i + 1],
                    cache[i] + num1 * num2
                )
            cache, nxt = nxt, cache
        return cache[-1]
```

#### Language used for code
Python3

#### Expected behavior
My wrong code should not be accepted since the correct answer to the test case is `1` while my code yields `-1`.

#### Screenshots
N/A

#### Additional context
N/A

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
