### ISSUE TITLE
Missing Test Case - 1458. Max Dot Product of Two Subsequences

### ISSUE THREAD

**Issue by Chandradyep** [LeetCode-Feedback/LeetCode-Feedback#17034]
#### Your LeetCode username 

chandu_345

#### Category of the bug
- [[1458. Max Dot Product of Two Subsequences](https://leetcode.com/problems/max-dot-product-of-two-subsequences/) ] Question
- [DP Approach. Will explain the bug below. ] Solution
- [C++ ] Language
- [ nums1 = [-1,-1], nums2 = [-1,-1]] Missing Test Cases 

#### Description of the bug

So if one of the array has negative values the code handles it and that part is okay. But if both the arrays have only negative elements then the dot product will not be calculated correctly by this code. But the code has submitted and I have got an AC solution with this code. I have tested the input with two arrays filled with negative values and got a WA but the code got accepted.

#### Code you used for Submit/Run operation

```
// Max Dot product
class Solution {
public:
    int solve(vector<int>& nums1, vector<int>& nums2,int idx1,int idx2,vector<vector<int>> &dp)
    {
        if(idx1<0 || idx2<0) return 0;
        if(dp[idx1][idx2]!=-1e9) return dp[idx1][idx2];
        int take=nums1[idx1]*nums2[idx2]+max(0,solve(nums1,nums2,idx1-1,idx2-1,dp));
        int nottake=max(solve(nums1,nums2,idx1,idx2-1,dp),solve(nums1,nums2,idx1-1,idx2,dp));
        return dp[idx1][idx2]=max(take,nottake);
    }
    int maxDotProduct(vector<int>& nums1, vector<int>& nums2) {
        int n=nums1.size(),m=nums2.size(),c1=0,c2=0;
        for(int i=0;i<n;i++)
        {
            if(nums1[i]<0) c1++;
        }
        for(int i=0;i<m;i++)
        {
            if(nums2[i]<0) c2++;
        }
        if(c1==n)
        {
            int min1=-1001,min2=1001;
            for(int i=0;i<n;i++)
            {
                min1=max(min1,nums1[i]);
            }
            for(int i=0;i<m;i++)
            {
                min2=min(min2,nums2[i]);
            }
            return min1*min2;
        }
        if(c2==m)
        {
            int min1=1001,min2=-1001;
            for(int i=0;i<n;i++)
            {
                min1=min(min1,nums1[i]);
            }
            for(int i=0;i<m;i++)
            {
                min2=max(min2,nums2[i]);
            }
            return min1*min2;
        }
        vector<vector<int>> dp(n,vector<int>(m,-1e9));
        return solve(nums1,nums2,n-1,m-1,dp);
    }
};
```

#### Language used for code

C++

#### Expected behavior

For two arrays with only negative numbers, for example $$nums1=[-1,-1]$$ and $$nums2=[-1,-1]$$ the the max dot product will be $$(-1*-1) + (-1*-1)=2$$ which is equal to 2 but the code will return the answer as 1. This are the testcases which were not included.

I will be adding two screenshots. In the first screen shot you can see that the code fails for the testcase explained.
In the second screenshot you can see that my code was accepted.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/132899186/2657a8df-246d-48c1-9f07-d65f2f99c377)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/132899186/f4b7fbf9-ce61-4ea8-a0ea-88cc35ce6b54)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
