### ISSUE TITLE
Missing Test Case - 334. Increasing Triplet Subsequence

### ISSUE THREAD

**Issue by dinesh-kopuri** [LeetCode-Feedback/LeetCode-Feedback#1703]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by dinesh-kopuri** [comment]
it is accepting the automata that has the set [1,2,1,4 ] where there is no increasing order for the triplets
![2020-12-19](https://user-images.githubusercontent.com/42643566/102684999-7a721d00-419a-11eb-8fe2-5c4c94c1879b.png)
ncreasing order for the triplets

**Comment by snehasishroy** [comment]
[1,2,4] is a valid increasing triplet. The answer is correct.

**Comment by lc-kay** [comment]
@dinesh-kopuri Our team carefully reviews all test cases and expected answers before publication, the answer is correct. Please check out the discuss tab for accepted solutions for reference. Thank you for your time!
