### ISSUE TITLE
Missing Test Case - 1458. Max Dot Product of Two Subsequences

### ISSUE THREAD

**Issue by Kashif-rahman03** [LeetCode-Feedback/LeetCode-Feedback#17036]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int dp[1000][1000];
    int solve(int i,int j,vector<int>& nums1,vector<int>& nums2){
        int n=nums1.size();
        int m=nums2.size();
        if(i==n||j==m)return 0;
        if(dp[i][j]!=-1)return dp[i][j];
        int t1=nums1[i]*nums2[j]+solve(i+1,j+1,nums1,nums2);
        int t2=solve(i,j+1,nums1,nums2);
        int t3=solve(i+1,j,nums1,nums2);
        return dp[i][j]=max(t1,max(t2,t3));

    }
    int maxDotProduct(vector<int>& nums1, vector<int>& nums2) {
        int fmax=nums1[0],fmin=nums1[0];
        for(auto it:nums1){
            fmax=max(it,fmax);
            fmin=min(it,fmin);
        }
        int smax=nums2[0],smin=nums2[0];
        for(auto it:nums2){
            smax=max(it,smax);
            smin=min(it,smin);
        }
        if(fmax<0)return fmax*smin;
        if(smax<0)return smax*fmin;


        memset(dp,-1,sizeof(dp));

        return solve(0,0,nums1,nums2);
    }
};
```

#### Language used for code
 C++ 

#### Expected behavior

With my solution the answer is giving wrong for some test case where as the same solution when I submitted it get accepted .
For e.g:-
Input: nums1=[-1,-1] , nums2=[-4,-7]
Output:7 
Expected:11 
But the same code when I submitted get accepted .

#### Solution 
If I add another check than when fmax<0 and smin>0 or smax<0 and fmin>0 then it will give write answer .
So please add some test case which has both the nums as negative 

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/95422841/6f0ee3fc-99f4-4e78-8585-ab91fb02e93f)

#### Additional context

Please add some test case where both the nums where all the value of both the nums are less than 0

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
