### ISSUE TITLE
Problem 35 - Search Insert Position - Unnecessary indentation error which shouldn't be there  

### ISSUE THREAD

**Issue by PushkarP-404** [LeetCode-Feedback/LeetCode-Feedback#17032]
####LeetCode username - user4695Ep

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Dont know if the problem is specific to this question or not but, even with just the default code given with nothing extra, it is giving unnecessary indentation error on the lines which are not even there in the code.
for example, there are just 2 lines of code, but am still getting an indentation error on line 4 .

#### Code you used for Submit/Run operation

```
class Solution(object):
    def searchInsert(self, nums, target):
```

#### Expected behavior-

The test cases may fail the code should not give any error

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by PushkarP-404** [comment]
Okay thank you very much

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
