### ISSUE TITLE
Missing Test Case - 1458. Max Dot Product of Two Subsequences

### ISSUE THREAD

**Issue by totallyEl3ktrik** [LeetCode-Feedback/LeetCode-Feedback#17030]
#### Your LeetCode username

totallyEl3ktrik

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

If the max dot product of two subsequences is less than zero, it will be equal to the maximum product of only one element from the first, and second sequence. However, the test cases don't seem to cover the situation in which that product is made up of the first element of in a sequence. 

#### Code you used for Submit/Run operation

```c++
// Bottom-up approach (space optimized)
class Solution {
public:
    int maxDotProduct(vector<int>& nums1, vector<int>& nums2) {
        vector<int> dpPrev = vector(nums2.size(), 0);
        vector<int> dp = vector(nums2.size(), 0);

        int maxProduct = nums1[0] * nums2[0];
        bool zero = maxProduct == 0;

        dpPrev[0] = max(0, maxProduct);
        for (int j = 1; j < nums2.size(); ++j) {
            int product = nums1[0] * nums2[j];

            // Faster than an if statement
            zero |= (product == 0);
            maxProduct = max(maxProduct, product);

            dpPrev[j] = max(product, dpPrev[j - 1]);
        }

        for (int i = 1; i < nums1.size(); ++i) {
            int product = nums1[i] * nums2[0];
            dp[0] = max(dpPrev[0], product);
            // Solution will be marked as correct even with this line commented out
            //maxProduct = max(maxProduct, product);
            for (int j = 1; j < nums2.size(); ++j) {
                int product = nums1[i] * nums2[j];

                zero |= (product == 0);
                maxProduct = max(maxProduct, product);

                int curProduct = product + dpPrev[j - 1];
                int productIfSkippedElement = max(dpPrev[j], dp[j - 1]);
                int totalProduct = max(curProduct, productIfSkippedElement);
                dp[j] = totalProduct;
            }
            dpPrev.swap(dp);
        }

        // Handle the edge case of max product being less than zero
        int result = dpPrev[nums2.size() - 1];
        if (result == 0 && !zero) {
            return maxProduct;
        } else {
            return result;
        }
         
    }
};
```

#### Language used for code
C++

#### Expected behavior

The solution shouldn't pass the tests.

#### Screenshots

Invalidating test case.
<img width="815" alt="invalidating test case" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/61513585/7c3c67eb-e016-4a29-8c62-763cce6794d8">
Result when submitted.
<img width="811" alt="submition results" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/61513585/0e6020a4-277a-4fa5-9d4a-bb61739eec1a">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
