### ISSUE TITLE
Missing Test Case - 1581. Customer Who Visited but Did Not Make Any Transactions

### ISSUE THREAD

**Issue by iamnidhisha** [LeetCode-Feedback/LeetCode-Feedback#17041]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Write a solution to find the IDs of the users who visited without making any transactions and the number of times they made these types of visits.

Return the result table sorted in any order.

#### Code you used for Submit/Run operation

```
// Customer Who Visited but Did Not Make Any Transactions
Select v.customer_id,count(v.visit_id) as count_no_trans from Visits v
where v.visit_id not in (select distinct visit_id from transactions)
group by v.customer_id
```

#### Language used for code

MS SQL Server

#### Screenshots

![Screenshot (73)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/125153381/cdc90bc4-a901-4c72-8b21-fde97983710e)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've submitted your feedback to the team. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
