### ISSUE TITLE
Missing Test Case - 1458. Max Dot Product of Two Subsequences

### ISSUE THREAD

**Issue by mks2002** [LeetCode-Feedback/LeetCode-Feedback#17046]
#### Category of the bug
- [√ ] Question
- [√ ] Solution
- [ √] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution {
public:
// there is 3 different recursive calls one is take and 2 is non take .....
int helper(int idx1, int idx2, vector<int> &nums1, vector<int> &nums2, vector<vector<int>> &dp)
{
    // this are the base cases .....
    if (idx1 < 0 or idx2 < 0)
        return -1;

    if (dp[idx1][idx2] != -1e9)
        return dp[idx1][idx2];

    // recursive calls ....
    int op1 = nums1[idx1] * nums2[idx2] + max(0, helper(idx1 - 1, idx2 - 1, nums1, nums2, dp));
    int op2 = 0 + helper(idx1, idx2 - 1, nums1, nums2, dp);
    int op3 = 0 + helper(idx1 - 1, idx2, nums1, nums2, dp);

    int ans = max({op1, op2, op3});
    return dp[idx1][idx2] = ans;
}

int maxDotProduct(vector<int> &nums1, vector<int> &nums2)
{
    int n = nums1.size(), m = nums2.size();

    int c1 = 0, c2 = 0;
    for (auto it : nums1)
    {
        if (it < 0)
            c1++;
    }
    for (auto it : nums2)
    {
        if (it < 0)
            c2++;
    }

    if (c1 == n)
    {
        int min1 = -1001, min2 = 1001;

        for (int i = 0; i < n; i++) // finding the largest maximum number ....
            min1 = max(min1, nums1[i]);

        for (int i = 0; i < m; i++) // finding the smallest positive number .......
            min2 = min(min2, nums2[i]);

        return min1 * min2;
    }

    if (c2 == m)
    {
        int min1 = 1001, min2 = -1001;
        for (int i = 0; i < n; i++)
            min1 = min(min1, nums1[i]);

        for (int i = 0; i < m; i++)
            min2 = max(min2, nums2[i]);

        return min1 * min2;
    }

    vector<vector<int>> dp(n, vector<int>(m, -1e9));
    int ans = helper(n - 1, m - 1, nums1, nums2, dp);
    return ans;
}
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by mks2002** [comment]
Here is the code submission accepted link 
https://leetcode.com/problems/max-dot-product-of-two-subsequences/submissions/1070452477/?envType=daily-question&envId=2023-10-08

and this is the test case on which it gives wrong answer 
Input
nums1 = [-5,-1,-2]
nums2 = [-3,3,5,5]
Output
3
Expected
15

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

The above code currently received Wrong Answer after submit: https://leetcode.com/submissions/detail/1074483242/
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
