### ISSUE TITLE
Incorrect Output Validation -- 373. Find K Pairs with Smallest Sums

### ISSUE THREAD

**Issue by YuzeLiao** [LeetCode-Feedback/LeetCode-Feedback#17043]
#### Your LeetCode username
FabulousFelix

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The LeetCode program that validates user output seems to be incorrect for Python (didn't check the other programming languages). A wrong output could pass the validation and get accepted.

#### Code you used for Submit/Run operation

```
# This code is not a correct solution for the problem. I used the test case in this report to debug and that was why I found the issue.
class Solution:
    def kSmallestPairs(self, nums1: List[int], nums2: List[int], k: int) -> List[List[int]]:
        n1, n2 = len(nums1), len(nums2)
        k = min(k, n1 * n2)
        t1, t2 = [0] * n1, [0] * n2
        i1, i2 = 0, 0
        t1[0], t2[0] = 1, 1
        res = []
        for i in range(k - 1):
            res.append([nums1[i1], nums2[i2]])
            t1[i1], t2[i2] = i2 + 1, i1 + 1
            candidate1 = (nums1[i1 + 1] + nums2[t1[i1 + 1]]) if i1 < n1 - 1 and t1[i1 + 1] < n2 else math.inf
            candidate2 = (nums1[t2[i2 + 1]] + nums2[i2 + 1]) if i2 < n2 - 1 and t2[i2 + 1] < n1 else math.inf
            if candidate1 < candidate2:
                i2 = t1[i1 + 1]
                i1 += 1
            else:
                i1 = t2[i2 + 1]
                i2 += 1
        res.append([nums1[i1], nums2[i2]])
        return res
```

#### Language used for code

Python

#### Screenshots

<img width="1635" alt="Screen Shot 2023-10-08 at 2 02 38 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/18509018/87d88b4c-0b26-495a-ad9e-a083734e30df">

#### Additional context

For your convenience, I copied the coding related text in the screenshot above.

```
Input
nums1 =
[-999,-999,-996,-993,-991,-982,-981,-972,-972]
nums2 =
[-1000,-997,-997,-984,-982,-970,-969]
k =
10000
Output
[[-999,-1000],[-999,-1000],[-999,-997],[-999,-997],[-999,-997],[-999,-997],[-996,-1000],[-996,-997],[-996,-997],[-993,-1000],[-991,-1000],[-993,-997],[-993,-997],[-991,-997],[-991,-997],[-999,-984],[-999,-984],[-999,-982],[-999,-982],[-996,-984],[-996,-982],[-993,-984],[-993,-982],[-991,-984],[-982,-1000],[-981,-1000],[-982,-997],[-982,-997],[-981,-997],[-981,-997],[-972,-1000],[-972,-1000],[-972,-997],[-972,-997],[-972,-997],[-972,-997],[-982,-984],[-991,-982],[-999,-970],[-999,-970],[-999,-969],[-999,-969],[-996,-970],[-996,-969],[-993,-970],[-993,-969],[-991,-970],[-982,-982],[-981,-984],[-981,-982],[-972,-984],[-972,-984],[-972,-982],[-972,-982],[-982,-970],[-991,-969],[-982,-969],[-981,-970],[-981,-969],[-972,-970],[-972,-970],[-972,-969],[-972,-969]]
Expected
[[-999,-1000],[-999,-1000],[-999,-997],[-996,-1000],[-999,-997],[-999,-997],[-999,-997],[-993,-1000],[-996,-997],[-996,-997],[-991,-1000],[-993,-997],[-993,-997],[-991,-997],[-991,-997],[-999,-984],[-999,-984],[-982,-1000],[-999,-982],[-999,-982],[-981,-1000],[-996,-984],[-982,-997],[-982,-997],[-981,-997],[-996,-982],[-981,-997],[-993,-984],[-991,-984],[-993,-982],[-991,-982],[-972,-1000],[-972,-1000],[-999,-970],[-972,-997],[-972,-997],[-999,-970],[-972,-997],[-972,-997],[-999,-969],[-999,-969],[-996,-970],[-982,-984],[-981,-984],[-996,-969],[-982,-982],[-993,-970],[-981,-982],[-993,-969],[-991,-970],[-991,-969],[-972,-984],[-972,-984],[-972,-982],[-972,-982],[-982,-970],[-982,-969],[-981,-970],[-981,-969],[-972,-970],[-972,-970],[-972,-969],[-972,-969]]
```

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team

**Comment by YuzeLiao** [comment]
Hey @LC-Pam, the code was not accepted as it failed some other test cases. But to reproduce this issue, I guess you could copy my buggy code above, and use the test case in the report:

```
Input
nums1 =
[-999,-999,-996,-993,-991,-982,-981,-972,-972]
nums2 =
[-1000,-997,-997,-984,-982,-970,-969]
k =
10000
```

"Accepted" will show for this test case, but the answer from my program is actually incorrect, which implies a potential bug in LeetCode's answer verification code for this question.

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
