### ISSUE TITLE
Missing Test Case - 1068. Product Sales Analysis I

### ISSUE THREAD

**Issue by iamnidhisha** [LeetCode-Feedback/LeetCode-Feedback#17040]
#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [x] Missing Test Cases 

#### Description of the bug

Write a solution to report the product_name, year, and price for each sale_id in the Sales table.
Return the resulting table in any order.

#### Code you used for Submit/Run operation

```
// Product Sales Analysis I
select p.product_name,s.year,s.price from sales s
left join product p on p.product_id=s.product_id
```

#### Language used for code

MS SQL Server 

#### Screenshots

![Screenshot (72)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/125153381/13018e1f-73a1-4dd4-bd88-969aebbe69c0)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've submitted your feedback to the team.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
