### ISSUE TITLE
Missing Test Case - 104. Maximum Depth of Binary Tree

### ISSUE THREAD

**Issue by Dipankar38** [LeetCode-Feedback/LeetCode-Feedback#17045]
#### Your LeetCode username
Ddx_38

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Leetcode compiler does not generate the output that my code should have generated.

#### Code you used for Submit/Run operation

```c++
/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
class Solution {
public:
    static int max_depth;

    int maxDepth(TreeNode* root) {
        int count{};
        traverse(root, count);
        return max_depth;
    }

    void traverse(TreeNode* root, int count)
    {
        if (root == nullptr)
        {
            if (count > max_depth)
                max_depth = count;
        }
        else
        {
            traverse(root->left, count + 1);
            traverse(root->right, count + 1);
        }
    }
};

int Solution::max_depth = 0;
``` 

#### Language used for code
C++

#### Expected behavior
When I run testcases `[1, null, 2]`, my program should return 2, but LeetCode is saying that it returns 3. I also have tried using different testcases. It seems to be working fine for the trees whose depth are 3 or more, but for the input trees who have depth less than 3, the compiler is generating wrong answer(returns 3) for my program. My program runs fine and generates correct answer in my machine's compiler.

#### Screenshots
![Screenshot from 2023-10-09 01-28-32](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/79999181/9c4ce372-a49b-49c8-a65a-5076b5f6919a)
![Screenshot from 2023-10-09 01-28-48](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/79999181/41422eaa-00ac-43e8-ae1d-65c383c98827)
![Screenshot from 2023-10-09 01-29-34](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/79999181/4e58c7b5-8476-4334-9908-24fa34d6fb59)
![Screenshot from 2023-10-09 01-29-01](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/79999181/f3e0c8a3-0eda-4b6c-bf89-7f1e0dda5431)

#### Additional context
If I give input of tree of (depth<3) it returns strictly 3, Otherwise it works fine.

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
