### ISSUE TITLE
Missing Test Case - 74. Search a 2D Matrix

### ISSUE THREAD

**Issue by t4upl** [LeetCode-Feedback/LeetCode-Feedback#1705]
Problem in test case Example 1 & Example 2

Test case as text input shows value as 50 but attached image shows 60. Does not influence the correctness but it gets on my nerves.

**Comment by lc-kay** [comment]
Hi @t4upl 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @t4upl 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
