### ISSUE TITLE
vimeo video not playing

### ISSUE THREAD

**Issue by lostintheway** [LeetCode-Feedback/LeetCode-Feedback#17054]
1480. Running Sum of 1D Array
  
  on page https://leetcode.com/explore/featured/card/the-leetcode-beginners-guide/692/challenge-problems/4422/

video just keeps on buffering and wont even start

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The video working on our side, please clear browser histories and cookies, and refresh the page. 


![Screen Shot 2023-10-09 at 3 57 01 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/dc911709-2ec6-41ce-aeb5-12d31c861bef)

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
