### ISSUE TITLE
Missing Test Case - 179. Largest Number

### ISSUE THREAD

**Issue by basioli-k** [LeetCode-Feedback/LeetCode-Feedback#1706]
#### Your LeetCode username

basiokar

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Test case 52 with the input [34323, 3432] returns the solution "343234323" which seems to be a concatenation of 34323 and 4323.
The second number isn't in the given array.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    string largestNumber(vector<int>& nums) {
        sort(nums.begin(),nums.end(), 
            [](const int & a, const int & b) -> bool
            { 
                string temp1 = to_string(a), temp2 = to_string(b);
                int i = 0;
                if(temp1.size() == temp2.size()) return a >= b;
                while(temp1[i] == temp2[i] && i < temp1.size() && i < temp2.size()) ++i;
                if(i == temp1.size()) return temp1[i-1] >= temp2[i];
                if(i == temp2.size()) return temp1[i] >= temp2[i-1];
                return temp1[i] >= temp2[i];
            }
            );
        
        string s = "";
        for(int i = 0 ; i < nums.size(); ++i){
            s+= to_string(nums[i]);
        }
        
        return s;
    }
};
```

#### Language used for code

C++

#### Expected behavior

As stated before the solution should be 343233432 which we get by concatenating 34323 3432.

**Comment by lc-kay** [comment]
@basioli-k The expected value "343234323" is a concatenation of 3432 and 34323, which are the numbers in the given array. Thank you for your time!
