### ISSUE TITLE
Typo in Question - 981. Time Based Key-Value Store

### ISSUE THREAD

**Issue by lilweege** [LeetCode-Feedback/LeetCode-Feedback#17074]
#### Your LeetCode username

lilweege

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

https://leetcode.com/problems/time-based-key-value-store/

The question has incorrect spacing around the code spacing of `value`.

![2023-10-09_18-01](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/59585724/b164e4e6-4273-4272-a00b-be48db87f0a7)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
