### ISSUE TITLE
param value should be EASY instead pf Easy

### ISSUE THREAD

**Issue by IAmAnubhavSaini** [LeetCode-Feedback/LeetCode-Feedback#17075]
On page `https://leetcode.com/explore/learn/card/the-leetcode-beginners-guide/679/sql-syntax/4357/` there is a link: `https://leetcode.com/problemset/all/?difficulty=Easy&page=1`

The value of param `difficulty` should be `EASY`.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by IAmAnubhavSaini** [comment]
@LC-Pam 
Take a look at your own graphql request.

![Correct graphql request](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/1573771/6ede62c7-1242-436c-b9bb-87efdebe4651)

`EASY` is the correct value for `difficulty`. `Easy` doesn't fetch the correct data from BE.
