### ISSUE TITLE
Typo in Contest - Weekly Contest 362 - 367

### ISSUE THREAD

**Issue by lilweege** [LeetCode-Feedback/LeetCode-Feedback#17076]
#### Your LeetCode username
lilweege

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

https://leetcode.com/contest/weekly-contest-362/
https://leetcode.com/contest/weekly-contest-363/
https://leetcode.com/contest/weekly-contest-364/
https://leetcode.com/contest/weekly-contest-365/
https://leetcode.com/contest/weekly-contest-366/
https://leetcode.com/contest/weekly-contest-367/

In the weekly contest pages (for weekly contests from the 362nd up to to the 367th), the contest number is incorrect.

![2023-10-09_22-21](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/59585724/4d19ebfa-e1f1-4104-a59f-c54a7280f392)

**Comment by LC-Pam** [comment]
Thank you for your time. 

This issue has already been reported by other users. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
