### ISSUE TITLE
Missing Test Case - 2731. Movement of Robots

### ISSUE THREAD

**Issue by WEI-1228** [LeetCode-Feedback/LeetCode-Feedback#17081]
#### Your LeetCode username

anlper

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The data lacks data whose moved position exceeds the int range. My code directly places the moved position in the `nums` vector, which works. But according to the data range, it should not be AC.

#### Code you used for Submit/Run operation

```c++
// Movement of Robots
class Solution {
public:
    int sumDistance(vector<int>& nums, string s, int d) {
        int mod = 1e9 + 7;
        for (int i = 0; i < nums.size(); i++)
        {
            if (s[i] == 'L') nums[i] = nums[i] - d;
            else nums[i] = nums[i] + d;
        }
        sort(nums.begin(), nums.end());
        long long res = 0;
        long long t = 0;
        for (int i = 1; i < nums.size(); i++)
        {
            long long d = (long long)nums[i] - nums[i - 1];
            t = (t + i * d) % mod;
            res = (res + t) % mod;
        }
        return res;
    }
};
```

#### Language used for code

C++

#### Expected behavior

input:
[-2000000000, -1999999999]
"LR"
1000000000
output: Runtime Error

#### Screenshots

<img width="2548" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/54617876/60f14b16-48fa-45c4-a425-2ed4e2b710e0">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by WEI-1228** [comment]
Can you tell me why not? The code I'm using is able to work through this question, but the data range of that test case I'm designing meets the requirements, and my code doesn't work properly. Shouldn't this data be enhanced?
my accepted code:
```c++
class Solution {
public:
    int sumDistance(vector<int>& nums, string s, int d) {
        int mod = 1e9 + 7;
        for (int i = 0; i < nums.size(); i++)
        {
            if (s[i] == 'L') nums[i] = nums[i] - d;
            else nums[i] = nums[i] + d;
        }
        sort(nums.begin(), nums.end());
        long long res = 0;
        long long t = 0;
        for (int i = 1; i < nums.size(); i++)
        {
            long long d = (long long)nums[i] - nums[i - 1];
            t = (t + i * d) % mod;
            res = (res + t) % mod;
        }
        return res;
    }
};
```

error test case:
[-2000000000, -1999999999]
"LR"
1000000000

**Comment by WEI-1228** [comment]
`if (s[i] == 'L') nums[i] = nums[i] - d;`
`else nums[i] = nums[i] + d;`
These two lines would obviously exceed the representation range of int, but are missing data that exceeds the representation range. It is clearly possible that the range of data given in the question could exceed int.
