### ISSUE TITLE
Found Typo in Contest from the Weekly Contest 362 to 367

### ISSUE THREAD

**Issue by cy2000yadav** [LeetCode-Feedback/LeetCode-Feedback#17080]
#### Your LeetCode username

cy2000yadav

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

There are typo in the following Contests which I found in which you will be able to see 'Welcome to the 361th LeetCode Weekly Contest' even if it's a 364th Challenge.

Weekly Contest 367 : https://leetcode.com/contest/weekly-contest-367/
Weekly Contest 366 : https://leetcode.com/contest/weekly-contest-366/
Weekly Contest 365 : https://leetcode.com/contest/weekly-contest-365/
Weekly Contest 364 : https://leetcode.com/contest/weekly-contest-364/
Weekly Contest 363 : https://leetcode.com/contest/weekly-contest-363/
Weekly Contest 362 : https://leetcode.com/contest/weekly-contest-362/

#### Expected behavior

The Contest number is repeating same (Weekly Contest 361) in the above links which I mentioned, which must be changed to their respective names.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/77014258/194a48c9-c32e-491a-a7ea-197307cc8b57)

**Comment by LC-Pam** [comment]
Thank you for your time. 

This issue already has been reported by other users. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
