### ISSUE TITLE
Missing Test Case - 2731. Movement of Robots

### ISSUE THREAD

**Issue by Thisnicknameisalreadytaken** [LeetCode-Feedback/LeetCode-Feedback#17093]
#### Your LeetCode username

小行星的飞行周期

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The solution to the question has not been tested for boundary conditions.
My test case:
- nums =[2000000000,-2000000000]
- s ="RL"
- d =1000000000

nums and d are all boundary values
My code has passed all tests and received AC but running the test fails to give the expected results and results in an error

#### Code you used for Submit/Run operation

```
class Solution:
    def sumDistance(self, nums: List[int], s: str, d: int) -> int:
        res = 0
        mod = 10**9+7
        temp = [i for i in nums]
        i = 0
        for direction in s:
            if direction == 'L':
                temp[i] -= d
            else:
                temp[i] += d
            i += 1
        length = len(nums)
        temp.sort()
        for i in range(1, length):
            res += (temp[i]-temp[i-1])*(length-i)*i
        res %= mod
        return res

```

#### Language used for code

Python3

#### Expected behavior

When I use this test case it should return the expected result

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
