### ISSUE TITLE
648.单词替换测试用例

### ISSUE THREAD

**Issue by fankoyu2019** [LeetCode-Feedback/LeetCode-Feedback#171]
**测试情况不全**
-  648 单词替换
- [ ] 题解
- C++

**描述**
测评机的例子不全，部分有bug的代码仍然能通过测试

**你使用的语言**
C++

**你提交或者运行的代码**
```
// Two Sum
class Solution {
public:
    string replaceWords(vector<string>& dict, string sentence) {
        istringstream line(sentence);
        string word,result="";
        while(line>>word)
        {
            int i=0;
            for(;i<dict.size();i++)
            {
                if(dict[i][0]==word[0]&&word.substr(0,dict[i].size())==dict[i]){result+=dict[i]+' ';break;}
            }
            if(i==dict.size())  result+=word+' ';
        }
        if(result.size()>0) result.resize(result.size()-1);
        return result;
    }
};
```

**期望行为**
这个程序应该不能通过测试

**屏幕截图**
![V@T5E7LE1PP}21N3TBZ0I@3](https://user-images.githubusercontent.com/51729960/79936505-466b1e80-848a-11ea-985e-1e999838fdd4.png)

**额外的上下文**
Input:
["catt","cat","bat","rat"]
"the cattle was rattled by the battery"
Output:
"the cat was rat by the bat"
虽然执行代码测试预期答案是正确的，但测评机并没有加入这组数据

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认的～

**Comment by feiceh** [comment]
fixed
