### ISSUE TITLE
Number of Flowers in Full Bloom : Typing mistake

### ISSUE THREAD

**Issue by Adityadalve** [LeetCode-Feedback/LeetCode-Feedback#17103]
#### Typing Mistake in 2251.Number of Flowers in Full Bloom
- [ ] poeple (mistake)
- [ ] people (correction)

**Comment by LC-Pam** [comment]
Thank you for your time. 

This issue already reported by the other people. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
