### ISSUE TITLE
Missing Test Case and - 505. The Maze II

### ISSUE THREAD

**Issue by Ming91** [LeetCode-Feedback/LeetCode-Feedback#17100]
#### Your LeetCode username

[wming9310](https://leetcode.com/wming9310)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My code is wrong with the test case below but got accepted. The submission is [here].(https://leetcode.com/submissions/detail/1072200127/)
```
# test case
[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]
[0,12]
[5,0]
```
The code below is wrong because it uses the wrong stopping condition. It returns the value the first time the destination is visited. It should return when the destination has the shortest distance in all remaining points.

#### Code you used for Submit/Run operation

```Java
class Solution {
    static final int[] DIR = new int[] {0, 1, 0, -1, 0};
    int m, n;
    int[][] maze;
    boolean isValid(int x, int y) {
        if (x < 0 || x >= m || y < 0 || y >= n || maze[x][y] == 1) {
            return false;
        }
        return true;
    }
    public int shortestDistance(int[][] maze, int[] start, int[] end) {
        m = maze.length;
        n = maze[0].length;
        this.maze = maze;
        boolean up = isValid(end[0] - 1, end[1]);
        boolean down = isValid(end[0] + 1, end[1]);
        boolean left = isValid(end[0], end[1] - 1);
        boolean right = isValid(end[0], end[1] + 1);
        if (up == down && left == right) {
            return -1;
        }
        Queue<int[]> q = new PriorityQueue<>((a, b) -> a[2] - b[2]);
        int[][] distance = new int[m][n];
        distance[start[0]][start[1]] = 1;
        q.add(new int[] {start[0], start[1], 1});
        while (!q.isEmpty()) {
            int[] curr = q.poll();
            int x = curr[0], y = curr[1];
            if (distance[x][y] < curr[2]) {
                continue;
            }
            for (int d = 0; d < 4; d++) {
                int xx = x;
                int yy = y;
                int dist = 0;
                while (isValid(xx + DIR[d], yy + DIR[d + 1])) {
                    xx += DIR[d];
                    yy += DIR[d + 1];
                    dist++;
                }
                if (distance[xx][yy] == 0 || distance[xx][yy] > distance[x][y] + dist) {
                    distance[xx][yy] = distance[x][y] + dist;
                    // This is wrong, may update better result later. 
                    if (xx == end[0] && yy == end[1]) {
                        return distance[xx][yy] - 1; 
                    }
                    q.offer(new int[] {xx, yy, distance[xx][yy]});
                }
            }
        }
        return distance[end[0]][end[1]] - 1;
    }
}
```

#### Language used for code

Java

#### Screenshots

![Screenshot 2023-10-10 190313](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/3740139/d7d1d854-9340-48c2-827e-31e309317373)

![Screenshot 2023-10-10 190448](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/3740139/58c2393c-7fee-4536-ae86-a3138ef64742)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by bernikovich** [comment]
Good find!

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
