### ISSUE TITLE
2251. Number of Flowers in Full Bloom: Typo: Instead "poeple" correct to write "people"

### ISSUE THREAD

**Issue by VlasenkoDmytro** [LeetCode-Feedback/LeetCode-Feedback#17108]
Typo: Instead "poeple" correct to write "people"
#### Your LeetCode username

vlasenkodmytroi

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Typo: Instead "poeple" correct to write "people"

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for your time. 

This issue has already been reported by other people, we will fix it soon. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
