### ISSUE TITLE
None of  the Embedded Content in the Courses Offered is Visible

### ISSUE THREAD

**Issue by Tamtam2002** [LeetCode-Feedback/LeetCode-Feedback#17117]
#### Your LeetCode username

Tamlucy

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I am not able to access the videos or even the IDEs are not visible. I am not able to use it also.
It  is  looking like  this:-
<details><summary><b>Click here for a more detailed explanation if needed</b></summary> We are looking for two numbers that sum to `target`. We iterate over the input and for each element `num`, we see if this element can be paired with another number to form `target`. If another element `target - num` exists, then their sum `num + target - num = target` is what we are looking for. So as we iterate over the input, we put elements in a hash map. Then in the future, we can check if we've seen `target - num` for each `num` in $$O(1)$$. The problem wants us to return the indices instead of the numbers themselves, so we can associate each number with its index. </details><lcvideo> <div class="video-container" style="padding:56.25% 0 0 0;position:relative;"> <iframe src="https://player.vimeo.com/video/773616084?texttrack=en-x-autogenerated" frameborder="0" allow="autoplay; fullscreen" style="position:absolute;top:0;left:0;width:100%;height:100%;"></iframe> </div> </lcvideo>
<br>

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

<img width="650" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/126505359/bc27590a-fcbb-49b2-8697-5fb23c6bbdfe">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your time.
The issue is fixed.
In the meantime, please let us know if there's anything else we can do to assist.

Best,
LC_Pam
