### ISSUE TITLE
None of the embedded videos in System Design Course is available

### ISSUE THREAD

**Issue by anshul810** [LeetCode-Feedback/LeetCode-Feedback#17114]
Following HTML code instead of video being shown e.g. in "How to define System Requirements -> Consistency" -:

<lcvideo> <div class="video-container" style="padding:56.25% 0 0 0;position:relative;"> <iframe src="https://player.vimeo.com/video/795701818?texttrack=en-x-autogenerated" frameborder="0" allow="autoplay; fullscreen" style="position:absolute;top:0;left:0;width:100%;height:100%;"></iframe> </div> </lcvideo>
<a href="https://leetcode.com/problems/Documents/LeetBook/systemdesigncourse/11_consistency.pdf" target="_blank">slides</a>

**Comment by Tamtam2002** [comment]
Facing the same issue

**Comment by zidk** [comment]
Same issue and another elements are broken too:

`which could take $$O(n)$$ time. Using a hash map, we can check the constraint in $$O(1)$$.`

`is one of the answers (<code>[1, <u>1, 2, 1, 1</u>]</code>).`

plus playgrounds

`<iframe src="https://leetcode.com/playground/[......]"></iframe>`

**Comment by abannura** [comment]
Same issue

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your time.
The issue is fixed.
In the meantime, please let us know if there's anything else we can do to assist.

Best,
LC_Pam
