### ISSUE TITLE
HTML not properly rendered 

### ISSUE THREAD

**Issue by blimbu1** [LeetCode-Feedback/LeetCode-Feedback#17112]
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/12128194/f7b85120-eebc-400b-acff-891f4cd5f897)

**Comment by roohaani786** [comment]
Yes. I'm also experiencing this

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem page link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by blimbu1** [comment]
This would be the GRAPH explore card. Thanks

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your time.
The issue is fixed.
In the meantime, please let us know if there's anything else we can do to assist.

Best,
LC_Pam
