### ISSUE TITLE
Heap Learning Card not working

### ISSUE THREAD

**Issue by eolamisan** [LeetCode-Feedback/LeetCode-Feedback#17121]
#### Description of the bug

The heap learning card is displaying html as text.

#### Expected behavior

The course is rendered properly.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/4191912/4e029a8a-e6af-4aff-a739-f9b11dd4e09f)

**Comment by Seleznyaka** [comment]
Same with arrays

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your time.
The issue is fixed.
In the meantime, please let us know if there's anything else we can do to assist.

Best,
LC_Pam
