### ISSUE TITLE
Content not loading in crash course page

### ISSUE THREAD

**Issue by praveennag24** [LeetCode-Feedback/LeetCode-Feedback#17129]
#### Your LeetCode username

praveennag24@gmail.com

#### Category of the bug
Content not loading in one of the page of Data structure and algorithm crash course

#### Description of the bug

One of the content page ( Fast and slow pointers) inside "LinkedList" crash course has missing content inside it. For example instead of having a playground space, it has this below tag - 
"<iframe src="https://leetcode.com/playground/oFzpCBSC/shared" frameBorder="0" width="100%" height="293" name="oFzpCBSC"></iframe>"

Also, none of the links inside this page are accessible.

Course link : https://leetcode.com/explore/interview/card/leetcodes-interview-crash-course-data-structures-and-algorithms/704/linked-lists/4507/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your time.
The issue is fixed.
In the meantime, please let us know if there's anything else we can do to assist.

Best,
LC_Pam
