### ISSUE TITLE
HTML rendering is failing

### ISSUE THREAD

**Issue by shyamdew** [LeetCode-Feedback/LeetCode-Feedback#17127]
<img width="536" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/21235738/18855be7-0d18-4a1e-ac6c-8c3912162893">

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by Anass-23** [comment]
I've also reported the issue, I'm having the same problem for the DSA Crash Course.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your time.
The issue is fixed.
In the meantime, please let us know if there's anything else we can do to assist.

Best,
LC_Pam
