### ISSUE TITLE
LeetCode CrashCourse HTML tags being incorrectly rendered as text

### ISSUE THREAD

**Issue by rivumic** [LeetCode-Feedback/LeetCode-Feedback#17125]
#### Your LeetCode username
rivum

#### Category of the bug
- [ ] Technical Problem Wtih Course 

#### Description of the bug
HTML tags on the https://leetcode.com/explore/interview/card/leetcodes-interview-crash-course-data-structures-and-algorithms/707/traversals-trees-graphs/4631/ page in the LeetCode DSA crash course are being rendered incorrectly. For example, an <a> tag veing rendered in full as "<a href="https....." instead of the proper link.

#### Screenshots
<img width="598" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/72121174/7379ebc0-5ee0-4a79-ab84-c86569ecc5a9">
<img width="603" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/72121174/19c5bbef-fe8c-4bdc-a6ea-901f8993022a">

**Comment by srivatsanveerara** [comment]
I face the same issue...

<lcvideo> <div class="video-container" style="padding:56.25% 0 0 0;position:relative;"> <iframe src="https://player.vimeo.com/video/795674340?texttrack=en-x-autogenerated" frameborder="0" allow="autoplay; fullscreen" style="position:absolute;top:0;left:0;width:100%;height:100%;"></iframe> </div> </lcvideo>

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by vijay-sakthivel-14** [comment]
@LC-Pam Hey! I'm facing this issue as well, when can we expect it to be rectified? Greatly hindering my learning.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your time.
The issue is fixed.
In the meantime, please let us know if there's anything else we can do to assist.

Best,
LC_Pam
