### ISSUE TITLE
videos are not accessible for data structures and algorithm course

### ISSUE THREAD

**Issue by mariag98** [LeetCode-Feedback/LeetCode-Feedback#17126]
#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your time.
The issue is fixed.
In the meantime, please let us know if there's anything else we can do to assist.

Best,
LC_Pam
