### ISSUE TITLE
None of the videos in System Design Course is viewable

### ISSUE THREAD

**Issue by apostergiou** [LeetCode-Feedback/LeetCode-Feedback#17120]
For example: https://leetcode.com/explore/interview/card/system-design-for-interviews-and-beyond/728/how-to-build-efficient-communication-in-distribute/4780/

<img width="843" alt="Screenshot 2023-10-11 at 12 18 17" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/16028784/2d4121aa-fcfc-4385-ad46-debf018b040a">

**Comment by AlexeiaW** [comment]
yeah same for me

**Comment by AshishSrivastava24** [comment]
+2 Same for me as well

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your time.
The issue is fixed.
In the meantime, please let us know if there's anything else we can do to assist.

Best,
LC_Pam
