### ISSUE TITLE
Test Case Error for Golang Solution - 589. N-ary Tree Preorder Traversal

### ISSUE THREAD

**Issue by typemegan** [LeetCode-Feedback/LeetCode-Feedback#17128]
#### Your LeetCode username

lc207

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

Whichever solution I implemented in Golang, it always failed to pass a certain test case after I submitted. It's okay to pass the case if not to submit, and it's okay if I tried to implement in other language like Python. 

Maybe there is something wrong with the test case construction in Golang when submit. 

#### Code you used for Submit/Run operation

```
func preorder(root *Node) []int {
    if root == nil {
        return nil
    }
    ans := []int{}
    
    stack := []*Node{root}
    for len(stack) != 0 {
        node := stack[len(stack)-1]
        stack = stack[:len(stack)-1]
        ans = append(ans, node.Val)
        size := len(node.Children)
        for i:=size-1; i>-1; i-- {
            stack = append(stack, node.Children[i])
        }
    }
    
    return ans 
}
```

#### Expected behavior

The Golang solution should be accepted.

#### Screenshots

<img width="1515" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/12883950/bde4a0ad-d3bb-4d80-a219-2427577b29dc">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected value but different output values.

We've documented the cause and solutions of this kind of issue here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!

**Comment by typemegan** [comment]
Thank you for your suggestion. I have read the documentation carefully, and excluded hidden impact like global variables. I have made some debugging, and drew my conclusion that something is indeed wrong with the 'Submit' test cases with Go Solution. Here are my debugging data:

### No variables interference between cases. 
It's alright to run several cases together: 
<img width="898" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/12883950/429a7027-1c60-4e50-af2f-d2216912f9f2">

### The structures of the certain case are different between 'Run code' and 'Submit':
#### When 'Run Code': 
<img width="706" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/12883950/43304f04-f7b2-4044-a56b-2ec50da14d5c">

#### After 'Submit': 
<img width="1464" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/12883950/192340e4-f90f-4391-b849-20dab8c1feff">

#### What's more,  I have tried several other Go Solutions from the Discussion sector, and they are failed without exception after submitted. 

Thank you for review.
