### ISSUE TITLE
HTML is not being rendered properly- LeetCode's Interview Crash Course (DSA)

### ISSUE THREAD

**Issue by Anass-23** [LeetCode-Feedback/LeetCode-Feedback#17131]
#### Your LeetCode username

Anass-23

#### Category of the bug
- [X ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The HTML content on the course that I'm taking is not being rendered (videos, links, LaTeX, ...) I've seen some people here in the Issues report that are having the same problem

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/56134601/fb7ac8cf-b924-4795-818a-37efa1de2994)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/56134601/0bac0c49-f2ad-4656-b3ca-994b91c235f7)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
