### ISSUE TITLE
Missing Test Case - 面试题 10.05. Sparse Array Search LCCI

### ISSUE THREAD

**Issue by hvsqg** [LeetCode-Feedback/LeetCode-Feedback#17133]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

when input is:
words =["ball", "", "", "", "", "", "car", "", "","dad", "", ""]
s ="ball"
the rights answer is 0, but this test case give -1;

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    public int findString(String[] words, String s) {
        int l = 0, r = words.length;
        while (l < r) {
            int mid = (l+r)/2;
            int x = mid;
            while (x >= 0 && words[x].equals("")) {
                x--;
            }
            if (x < 0) {
                l = mid+1;
                continue;
            }
            int compare = words[x].compareTo(s);
            if (compare == 0) {
                return x;
            } else if (compare>0) {
                r = x;
            } else {
                l = mid + 1;
            }
        }
        return -1;
    }
}
```

#### Language used for code

java

#### Expected behavior

add the test cases

#### Screenshots

![20-45-01](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/67466915/f727d347-1c4e-4d5c-863c-56709847a08e)

**Comment by amcones** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by feiceh** [comment]
你好，积分已发放至 ID：hvsqg，请查收～
