### ISSUE TITLE
System Design Content not loading

### ISSUE THREAD

**Issue by mdzobayer** [LeetCode-Feedback/LeetCode-Feedback#17130]
#### Your LeetCode username : 

zobayer94

#### Description of the bug

System Design Course content not loading

#### Screenshots

![2023-10-11_172711](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/13957811/4fa555f0-a60e-4582-8bf4-a579aaa59bcc)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your time.
The issue is fixed.
In the meantime, please let us know if there's anything else we can do to assist.

Best,
LC_Pam

**Comment by mdzobayer** [comment]
Thanks @LC-Pam
