### ISSUE TITLE
HTML page not rendering properly in the cheatsheets card.

### ISSUE THREAD

**Issue by pedamallu** [LeetCode-Feedback/LeetCode-Feedback#17132]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

Two pointers: one input, opposite ends

<iframe src="https://leetcode.com/playground/mefNe6qJ/shared" frameBorder="0" width="100%" height="327" name="mefNe6qJ"></iframe>

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
