### ISSUE TITLE
HTML tags and code showing up in DP explore card 

### ISSUE THREAD

**Issue by Yasshu55** [LeetCode-Feedback/LeetCode-Feedback#17139]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the DP Explore card, in "DP for paths in a matrix" section rather than showing a link that redirects to the problem that is explained in the article, it shows an anchor tag text as you can see in the attached ss, the whole page is glitched this way not just that line 

https://leetcode.com/explore/learn/card/dynamic-programming/634/matrix-path-based-dp/4129/
#### Screenshots

![Screenshot (330)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/95294297/f992f8df-6e9d-4f76-a1e7-5c64d1832744)

![Screenshot (331)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/95294297/a483152b-5b73-41cd-af68-44bd37d07e6c)

**Comment by wtbtucker** [comment]
This is happening in the Bit Manipulation Explore Card for all of the articles as well
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/23300271/1ea57abf-c22b-4d2d-96fe-dab42a44a82c)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
