### ISSUE TITLE
Code samples not displaying - only HTML code shown

### ISSUE THREAD

**Issue by blitzzkid** [LeetCode-Feedback/LeetCode-Feedback#17145]
#### Your LeetCode username

https://leetcode.com/blitzkid/

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] HTML not displaying

#### Description of the bug

HTML not displaying code or video solutions

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

![Screenshot 2023-10-11 at 10 46 02 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/23148579/0f653939-ce60-4de0-ba2b-05cb7d500031)

**Comment by gaganj-hithub** [comment]
Same problem here

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your time.
The issue is fixed.
In the meantime, please let us know if there's anything else we can do to assist.

Best,
LC_Pam
