### ISSUE TITLE
System Design Videos Unplayable

### ISSUE THREAD

**Issue by sam-93** [LeetCode-Feedback/LeetCode-Feedback#17146]
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/11828785/110b3459-dc4f-4319-ad00-36b41a0d32fe)

**Comment by AshishSrivastava24** [comment]
+1 
I am also facing similar issue

**Comment by Mudi26** [comment]
Me too

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your time.
The issue is fixed.
In the meantime, please let us know if there's anything else we can do to assist.

Best,
LC_Pam
