### ISSUE TITLE
HTML code showing in explanations

### ISSUE THREAD

**Issue by DoDesCadeaux** [LeetCode-Feedback/LeetCode-Feedback#17141]
#### Your LeetCode username
DoDesCadeaux

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [X] Other

#### Description of the bug
HTML code is showed on the explanations

#### Additional context
Here is an example link to see the HTML :
https://leetcode.com/explore/featured/card/the-leetcode-beginners-guide/678/sql-data-structure/4353/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your time.
The issue is fixed.
In the meantime, please let us know if there's anything else we can do to assist.

Best,
LC_Pam
