### ISSUE TITLE
Typo in Example 1 of #2251

### ISSUE THREAD

**Issue by RickyyyFu** [LeetCode-Feedback/LeetCode-Feedback#17148]
#### Your LeetCode username
curly_fy

#### Category of the bug
- [ x ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
[2251. Number of Flowers in Full Bloom](https://leetcode.com/problems/number-of-flowers-in-full-bloom/)
There is a  typo "poeple" in Input of Example 1

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for your time. 

This issue has already been reported by other people, we will fix it soon. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
