### ISSUE TITLE
Embedded content(video solutions) Unplayable

### ISSUE THREAD

**Issue by vksuvam** [LeetCode-Feedback/LeetCode-Feedback#17144]
#### Your LeetCode username
https://leetcode.com/vksuvam_/

#### Category of the bug
- Solution video unavailable

#### Description of the bug
Embedded video solutions are no longer playable. 

#### Screenshots
![Screenshot from 2023-10-11 19-59-02](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73656357/b07ca7f4-b419-4b9b-a623-1a9c7bfc80b3)

**Comment by gustavolb** [comment]
Same problem here .. cannot play videos

**Comment by vksuvam** [comment]
> Same problem here .. cannot play videos

Hope they fix it  soon

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your time.
The issue is fixed.
In the meantime, please let us know if there's anything else we can do to assist.

Best,
LC_Pam
