### ISSUE TITLE
test case failed problem no:88

### ISSUE THREAD

**Issue by rincemathew** [LeetCode-Feedback/LeetCode-Feedback#17142]
#### Your LeetCode username
https://leetcode.com/rincemathew/

#### Category of the bug
- [ ] TestCase Failed

#### Description of the bug
in problem number 88, I wrote a solution that works on my local environment(node js) but after I tried to run it on leetcode the first and third solutions failed and showed the wrong answer as well. my solution screenshot is added below.

#### Code you used for Submit/Run operation

```
i=0
    j=0
    result = []
    while(i<m || j<n) {
        if(i>=m) {
            result.push(nums2[j])
            j++
            continue;
        }
        if(j>=n) {
            result.push(nums1[j])
            i++
            continue;
        }
        if(nums1[i] < nums2[j]) {
            result.push(nums1[i])
            i++
        } else {
            result.push(nums2[j])
            j++
        }
    }
    return result

```

#### Language used for code
javascript

#### Expected behavior
here in my code if both 'i' and 'j' < 'm' and 'n' the loop will break. The first to 'if' conditions that to check if one of the 'm' or 'n' is expired or over and run only the other array and use the 'continue; statement to break one iteration.

#### Screenshots
here is my solution
![my answer](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/24889583/ee07e8b3-1b95-48d9-ab46-63f0c863ee98)

and here is what happens when i submit to leetcode (first test case)
![answer](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/24889583/184bc4b4-2f6b-4d9a-9e29-200981cc9f9d)

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Comment by laxmankumarmarikanti** [comment]
test case failed problem no:88 #17142
same issue  @LC-Pam 
Language used for code:
**python**
 ```class Solution(object):
    def merge(self, nums1, m, nums2, n):
        """
        :type nums1: List[int]
        :type m: int
        :type nums2: List[int]
        :type n: int
        :rtype: None Do not return anything, modify nums1 in-place instead.
        """
        nums1 = nums1[:m] + nums2[:n]
        for t in range(len(nums1)):
            for s in range(t+1,len(nums1)):
                if nums1[t]>=nums1[s]:
                    nums1[t],nums1[s]=nums1[s],nums1[t]
```
**Screenshots**
expected:
<img width="623" alt="problem88" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/144943712/af7a5195-c0cc-4d7f-b7cc-b9acf1ba5568">


lc out put:
<img width="927" alt="lcproblem88" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/144943712/3f908605-89ef-418a-8fe3-cc53fb598d0c">
