### ISSUE TITLE
HTML tags problem are not parsing correctly

### ISSUE THREAD

**Issue by gedobel** [LeetCode-Feedback/LeetCode-Feedback#17149]
#### Your LeetCode username

gedobel10

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

iframe tags and some other HTML tags are not working on Data Structures and Algorithms course.

#### Expected behavior

Iframe and other HTML tags should show the correct information, right now it's too tough to read the information.

Please, can you fix that? 

#### Screenshots

![Captura de pantalla 2023-10-11 a la(s) 12 22 36](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/23031073/1647d84a-a63c-49a9-893e-3cd5b6369301)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by gedobel** [comment]
Thank you so much. I hope the team can fix it as soon as possible!.

Have a good one.

**Comment by gedobel** [comment]
Thank you guys, it's working now!.. ❤️

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your time.
The issue is fixed.
In the meantime, please let us know if there's anything else we can do to assist.

Best,
LC_Pam
