### ISSUE TITLE
Systems Design Course - Videos Unplayable

### ISSUE THREAD

**Issue by gustavolb** [LeetCode-Feedback/LeetCode-Feedback#17151]
#### Your LeetCode username

gustavolb

#### Description of the bug

The videos for the Systems Design Course are unplayable.

#### Screenshots

![Screenshot 2023-10-11 at 12 36 23](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/824089/d2aae894-c174-4efe-8ad1-2ee6dc751372)

**Comment by Mudi26** [comment]
mine are also saying that, on other categories with a video

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your time.
The issue is fixed.
In the meantime, please let us know if there's anything else we can do to assist.

Best,
LC_Pam
