### ISSUE TITLE
DSA Crash course

### ISSUE THREAD

**Issue by al-khanji** [LeetCode-Feedback/LeetCode-Feedback#17153]
#### Your LeetCode username

al-khanji

#### Description of the bug

Backtracking - Generation article markup is broken and page doesn't render correctly.

#### Expected behavior

Page should render correctly.

#### Screenshots

<img width="1748" alt="Screen Shot 2023-10-11 at 9 50 52 AM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/1539580/e4bd6a28-d637-4f6e-9be0-f5bacbee6d99">

**Comment by vishalkumar9dec** [comment]
Facing the same issue. Kindly check on priority.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your time.
The issue is fixed.
In the meantime, please let us know if there's anything else we can do to assist.

Best,
LC_Pam
