### ISSUE TITLE
316和1081

### ISSUE THREAD

**Issue by Ricky-Chu** [LeetCode-Feedback/LeetCode-Feedback#1715]
** Bug 类型**
- [ ] 题目316和1081
- [ ] 编程语言 c++

**描述**
测试时正确，提交时显示错误，两个答案不一致

**你使用的语言**
C++

**你提交或者运行的代码**
```c++
class Solution {
public:
    string smallestSubsequence(string s) {
        int counts[26];
        unordered_set<char> set;
        string ans;
        for(auto letter : s) {
            counts[letter - 'a']++;
        } 
        for(auto letter : s) {
            if(set.find(letter) == set.end()) {
                while(ans.size() > 0 && ans.back() > letter && counts[ans.back() - 'a'] > 0) {
                    set.erase(ans.back());
                    ans.pop_back();
                }
                set.insert(letter);
                ans.push_back(letter);
            }
            counts[letter - 'a']--;
        }
        return ans;
    }
};
```

**期望行为**
修复一下

**屏幕截图**
![image](https://user-images.githubusercontent.com/47296568/102711680-7a872f80-42f6-11eb-99dc-3268d0a0d72d.png)
![image](https://user-images.githubusercontent.com/47296568/102711682-81ae3d80-42f6-11eb-8d09-b2c4de6e2fca.png)

**Comment by zerotrac** [comment]
`int counts[26];` 局部变量没有初始化，提交 issue 之前仔细 debug 一遍吧。。。

**Comment by Ricky-Chu** [comment]
我明白...但是为什么两个答案会不一样呢？是提交和测试时运行的机制不一样吗？

**Comment by zerotrac** [comment]
局部变量在未初始化时使用在 C++ 中时 undefined behavior，可能运气好栈上使用的内存里面的值都是 0，可能运气不好使用的内存里面还有值。

**Comment by Ricky-Chu** [comment]
恩恩明白了



发送自我的盖乐世



-------- 原始信息 --------
发件人： Shuxin Chen <notifications@github.com>
日期: 2020/12/21 02:14 (GMT+08:00)
收件人： LeetCode-Feedback/LeetCode-Feedback <LeetCode-Feedback@noreply.github.com>
抄送： Ricky Chu <qs4869@outlook.com>, Author <author@noreply.github.com>
主题： Re: [LeetCode-Feedback/LeetCode-Feedback] 316和1081 (#1715)


局部变量在未初始化时使用在 C++ 中是 undefined behavior，可能运气好栈上使用的内存里面的值都是 0，可能运气不好使用的内存里面还有值。

―
