### ISSUE TITLE
Unplayable sources

### ISSUE THREAD

**Issue by Salmuel** [LeetCode-Feedback/LeetCode-Feedback#17155]
#### Your LeetCode username
Samy777

#### Category of the bug

- [ ] Solution

#### Description of the bug
Video and practice elements are not showing up. Showing backend elements.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

![Screenshot 2023-10-11 132805](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/115123552/2f887ab2-4def-4da6-9e72-c9f8183280a3)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your time.
The issue is fixed.
In the meantime, please let us know if there's anything else we can do to assist.

Best,
LC_Pam
