### ISSUE TITLE
DSA Crash course: All bonus problems links are gone, HTML Issue?

### ISSUE THREAD

**Issue by m-devaditya** [LeetCode-Feedback/LeetCode-Feedback#17152]
[

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

<img width="924" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/139139484/f739e098-f4f7-4df9-8200-e7fdcc7ec26d">

**Comment by rybitskyi** [comment]
I have the same issue.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by vishalkumar9dec** [comment]
I bought this course today itself after seeing the video links and bonus questions, but now when I see it, these links dont work anymore. I am facing the same issue.

**Comment by LC-Pam** [comment]
![Screen Shot 2023-10-11 at 2 32 28 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/17a0fd41-9e07-4a57-b46d-7d1737192a80)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your time.
The issue is fixed.
In the meantime, please let us know if there's anything else we can do to assist.

Best,
LC_Pam
