### ISSUE TITLE
205. Isomorphic Strings - testcase 44 return true, but the online compiler returns false

### ISSUE THREAD

**Issue by matthewkrygin** [LeetCode-Feedback/LeetCode-Feedback#17158]
#### Your LeetCode username
mkry

#### Category of the bug
- [X] Question
- [X] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug
[onlinegdb](https://onlinegdb.com/D4yO8UeXY)
The related code runned on online compiler returns false (which is correct), but in testcase 44 literally the same code returns false.

#### Code you used for Submit/Run operation
```cpp
class Solution {
public:
    bool isIsomorphic(string s, string t) {
        using CheckT = bitset<256>;
        char data[256];
        char data_rev[256];
        CheckT fil;
        CheckT fil_rev;
        
        bool fl = true;
        
        for (int idx = 0; idx < s.size(); idx++)
        {
            char ch1 = (int)s[idx]; 
            char ch2 = (int)t[idx]; 
            if (fil[ch1] ^ fil_rev[ch2]) {
                fl = false; 
            } else {
                if (!fil[ch1]) {
                    data[ch1] = ch2;
                    data_rev[ch2] = ch1;
                    fil[ch1] = true;
                    fil_rev[ch2] = true;
                } else if (data[ch1] != ch2 || data_rev[ch2] != ch1)
                    fl = false;
            }
        }
        return fl;
    }
};
```

#### Language used for code
C++ 

#### Expected behavior
testcase 44: passed

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/64927023/8af86a6d-cea7-4e84-8e42-4374b9337fbc)

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
