### ISSUE TITLE
Typo in Question - 1249. Minimum Remove to Make Valid Parentheses

### ISSUE THREAD

**Issue by lilweege** [LeetCode-Feedback/LeetCode-Feedback#17163]
#### Your LeetCode username
lilweege

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

https://leetcode.com/problems/minimum-remove-to-make-valid-parentheses/

There are extra spaces surrounding the opening and closing parenthesis.

![2023-10-12_01-04](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/59585724/c6d10935-39fc-4950-9231-8ad4a819a75c)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

We've relayed this issue to our team to investigate. 

Please note this type of issue (space) is not valid for the Leetcoins reward.

More information can be found on: https://leetcode.com/discuss/general-discussion/526802/File-Problem-and-Solution-Content-Issues-to-Our-GitHub-Public-Feedback-Repo-Now!

We will get back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
