### ISSUE TITLE
Typo in Question - 1697. Checking Existence of Edge Length Limited Paths

### ISSUE THREAD

**Issue by lilweege** [LeetCode-Feedback/LeetCode-Feedback#17165]
#### Your LeetCode username
lilweege

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

https://leetcode.com/problems/checking-existence-of-edge-length-limited-paths/

There is a space before the period in the last sentence in the second paragraph.

![2023-10-12_01-22](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/59585724/ad7c452e-2b8f-4050-90c5-8205c76ea6b2)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

We've relayed this issue to our team to investigate. 

Please note this type of issue (space) will not count for the Leetcoins reward.

More information can be found at: https://leetcode.com/discuss/general-discussion/526802/File-Problem-and-Solution-Content-Issues-to-Our-GitHub-Public-Feedback-Repo-Now!

We will get back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
