### ISSUE TITLE
Typo in Question - 2745. Construct the Longest New String

### ISSUE THREAD

**Issue by lilweege** [LeetCode-Feedback/LeetCode-Feedback#17167]
#### Your LeetCode username
lilweege

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

https://leetcode.com/problems/construct-the-longest-new-string/

"concactenate" should be spelled "concatenate" in the description and examples.

![2023-10-12_01-32](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/59585724/b2784dab-6017-48b7-b809-4ab21706cdb5)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
