### ISSUE TITLE
Typo in Question - 2423. Remove Letter To Equalize Frequency

### ISSUE THREAD

**Issue by lilweege** [LeetCode-Feedback/LeetCode-Feedback#17162]
#### Your LeetCode username
lilweege

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

https://leetcode.com/problems/remove-letter-to-equalize-frequency/

The last sentence should say "You must remove exactly one letter and cannot **choose** to do nothing."

![2023-10-12_00-48](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/59585724/6e130801-bd75-4c9a-b0f1-a28455ac441c)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
