### ISSUE TITLE
Typo in Question - 1437. Check If All 1's Are at Least Length K Places Away

### ISSUE THREAD

**Issue by lilweege** [LeetCode-Feedback/LeetCode-Feedback#17164]
#### Your LeetCode username
lilweege

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

https://leetcode.com/problems/check-if-all-1s-are-at-least-length-k-places-away/

The first sentence should begin with "Given **a** binary array"

![2023-10-12_01-17](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/59585724/68940381-399e-44fd-be08-d6a55172030b)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
