### ISSUE TITLE
Typo in Question - 1921. Eliminate Maximum Number of Monsters

### ISSUE THREAD

**Issue by lilweege** [LeetCode-Feedback/LeetCode-Feedback#17169]
#### Your LeetCode username
lilweege

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

https://leetcode.com/problems/eliminate-maximum-number-of-monsters/description/

There should be a space between the period and the word "The" in the third paragraph.

![2023-10-12_01-58](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/59585724/5f7947a3-dd35-43f4-af9c-74609eea2d9c)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

We've relayed this issue to our team to investigate. 

Please note this type of issue (space) will not count for the Leetcoins reward.

More information can be found at: https://leetcode.com/discuss/general-discussion/526802/File-Problem-and-Solution-Content-Issues-to-Our-GitHub-Public-Feedback-Repo-Now!

We will get back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
