### ISSUE TITLE
Typo in Question - 1537. Get the Maximum Score

### ISSUE THREAD

**Issue by lilweege** [LeetCode-Feedback/LeetCode-Feedback#17170]
#### Your LeetCode username
lilweege

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

https://leetcode.com/problems/get-the-maximum-score/

The first sentence has incorrect code formatting around `nums2`. The period should be outside of the formatting.

![2023-10-12_02-07](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/59585724/0be2835d-cc6f-4026-a501-a3c5b9cb887d)

The second last sentence should say "The score is defined as the sum of **unique** values in a valid path."

![2023-10-12_02-05](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/59585724/a0dfcd2a-454f-4a83-b852-bf29923fadd9)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

We've relayed this issue to our team to investigate. 

Please note the first suggestion will not count for the Leetcoins reward.

More information can be found at: https://leetcode.com/discuss/general-discussion/526802/File-Problem-and-Solution-Content-Issues-to-Our-GitHub-Public-Feedback-Repo-Now!

We will get back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
