### ISSUE TITLE
120. Triangle: missing input constrains

### ISSUE THREAD

**Issue by Triara** [LeetCode-Feedback/LeetCode-Feedback#1717]
#### Your LeetCode username
dahrein

#### Category of the bug
- [X] Question
- [X] Solution
- [ ] Language

#### Description of the bug
The problem example seems to indicate that the input triangle must increase uniformly with respect to rows.
I used an input that had two consecutive rows of the same size. In particular `[[2],[3,4],[6,5,7],[4,1,8,3],[4,234,423,65]]`. Note that the repeating lists are of length 4 here.
And got the following error:
```
AddressSanitizer: heap-buffer-overflow on address 0x6020000001c0 at pc 0x0000003a2492 bp 0x7ffdfe111e70 sp 0x7ffdfe111e68
```

Something interesting happens though when I used a repeating array of size 5, I got a Wrong Answer.
Input: `[[2],[3,4],[6,5,7],[4,1,8,3],[4,6,2,7,9],[76,344,23,76,3]]`
Expected answer according to LC: `-1094795561`

I think both could be avoided by adding constraints to the input parameters, like leetcode is doing with some of their problems. 

#### Code you used for Submit/Run operation
Not applicable, issue is with LC expectations

#### Language used for code
N/A

#### Screenshots
https://snipboard.io/2ibtnC.jpg -> Wrong answer screenshot
https://snipboard.io/jgDSAi.jpg -> invalid testcase screenshot

**Comment by lc-kay** [comment]
Hi @Triara 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Triara 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
