### ISSUE TITLE
1095. Find in Mountain Array : Difficulty Level is Inaccurate

### ISSUE THREAD

**Issue by ShubhamKNIT** [LeetCode-Feedback/LeetCode-Feedback#17188]
#### Your LeetCode username

ShubhamKNIT

#### Category of the bug
- [ ] Question

#### Description of the bug

The question is marked with hard difficulty. But, to think of this problem isn't much of great difficult to think of. This problem is just extension of "[852. Peak Index in a Mountain Array](https://leetcode.com/problems/peak-index-in-a-mountain-array/). 
We have to just find one extra thing that is target.

```
Intuition used to solve the problem
1. Apply binary search to find pivot of mountain of the array
2. Then apply binarySearch on two halves of the mountain one till peak and one after the peak of the mountainArray to find target.
```

#### Code you used for Submit/Run operation

```
// 
/**
 * // This is the MountainArray's API interface.
 * // You should not implement it, or speculate about its implementation
 * class MountainArray {
 *   public:
 *     int get(int index);
 *     int length();
 * };
 */

class Solution {
private:
    int pivot(MountainArray &arr) { // find pivot index
        
        int s = 0;
        int e = arr.length() - 1;

        while (s < e) {
            int mid = s + (e - s)/2;
            if (arr.get(mid) < arr.get(mid + 1)) {
                s = mid + 1;
            }
            else {
                e = mid;
            }
        }

        return s;
    }

    int bs1(MountainArray &arr, int target, int start, int end) { // binary search on [0, pivot]
        
        int s = start;
        int e = end;
        int ans = -1;
        
        while (s <= e) {
            int mid = s + (e - s)/2;
            if (arr.get(mid) == target) {
                ans = mid;
                e = mid - 1;
            }
            else if (arr.get(mid) < target) {
                s = mid + 1;
            }
            else {
                e = mid - 1;
            }
        }

        return ans;
    }

    int bs2(MountainArray &arr, int target, int start, int end) { // binary search on [pivot + 1, arr.length - 1]
        
        int s = start;
        int e = end;
        int ans = -1;
        
        while (s <= e) {
            int mid = s + (e - s)/2;
            if (arr.get(mid) == target) {
                ans = mid;
                e = mid - 1;
            }
            else if (arr.get(mid) < target) {
                e = mid - 1;
            }
            else {
                s = mid + 1;
            }
        }

        return ans;
    }

public:
    int findInMountainArray(int target, MountainArray &mountainArr) {
        // 1. find pivot index
        // 2. find minimum index using binarySearch
        // 3. apply binary search on two halves from pivot

        int p = pivot(mountainArr);
        int p1 = bs1(mountainArr, target, 0, p);
        if (p1 == - 1) {
             return bs2(mountainArr, target, p + 1, mountainArr.length() - 1);
        }
        return p1;
    }
};
```

#### Language used for code

C++

#### Expected behavior

I think difficulty of this problem should be medium. Most people after knowing the hard tag of the problem don't try. But this is quite easy if u know how to find the pivot of the MountainArray.

#### Screenshots

<img width="703" alt="Screenshot 2023-10-12 at 11 30 30 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/121822213/a6038e7d-36e1-4845-a0c9-ca82e0f6fdbd">

<img width="703" alt="Screenshot 2023-10-12 at 11 28 25 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/121822213/38c1bd34-600d-435f-86c6-c9156af0cb4c">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
