### ISSUE TITLE
Missing Test Case - 1697. Checking Existence of Edge Length Limited Paths

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#1718]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution is accepted but fails on the following test case:

12
[[6, 0, 139], [5, 4, 679], [1, 0, 986], [5, 11, 567], [11, 6, 339], [6, 11, 998], [4, 11, 675], [6, 9, 101], [10, 3, 632], [7, 6, 461], [6, 9, 968], [10, 2, 959], [3, 10, 927], [10, 8, 682], [11, 3, 238], [2, 3, 374], [7, 3, 728], [3, 5, 268], [6, 1, 973], [5, 7, 991], [2, 9, 647], [5, 9, 350], [1, 3, 541], [10, 4, 998], [8, 7, 449], [3, 7, 614], [1, 11, 838], [8, 3, 782], [11, 1, 882], [5, 1, 282], [5, 4, 913], [2, 4, 312], [6, 8, 520], [1, 8, 445], [8, 1, 733], [11, 2, 258], [6, 2, 317], [2, 1, 372], [1, 10, 767], [0, 1, 767], [1, 7, 418], [1, 4, 456], [8, 1, 658]]
[[3, 5, 64], [3, 2, 433], [7, 8, 86], [11, 2, 255], [6, 1, 494], [7, 2, 367], [7, 0, 230], [2, 6, 458], [9, 0, 304], [4, 9, 192], [0, 1, 74], [4, 5, 493], [11, 6, 351], [5, 4, 319], [6, 3, 104], [2, 9, 105], [7, 0, 119], [1, 8, 39], [11, 9, 298], [6, 4, 20], [8, 11, 119], [5, 2, 464], [4, 11, 79], [11, 5, 275], [2, 8, 292], [1, 8, 256]]

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean[] distanceLimitedPathsExist(int n, int[][] edgeList, int[][] queries) {
        Arrays.sort(edgeList,(o1,o2)->o1[2]<o2[2]?-1:1);
        int[][] q = new int[queries.length][2];
        for(int i=0;i<queries.length;i++) {
            q[i][0] = queries[i][2];
            q[i][1] = i;
        }
        Arrays.sort(q,(o1,o2)->o1[0]<o2[0]?-1:1);
        int[] parents = new int[n];
        for(int i=0;i<n;i++) {
            parents[i] = i;
        }
        int eIndex = 0;
        boolean[] res = new boolean[queries.length];
        for(int i=0;i<queries.length;i++) {
            while(eIndex<edgeList.length && edgeList[eIndex][2]<q[i][0]) {
                union(parents,edgeList[eIndex][0],edgeList[eIndex][1]);
                eIndex++;
            }
            // System.out.println(Arrays.toString(parents));
            res[q[i][1]] = find(parents,queries[q[i][1]][0])==find(parents,queries[q[i][1]][1]);
        }
    
        return res;
    }
    int find(int[] parents,int p) {
        if (parents[p] != p) {
            parents[p] = find(parents,parents[p]);
        }
        return parents[p];
    }
    
    void union(int[] parents,int p,int q) {
        if(find(parents,p) != find(parents,q)) {
            parents[find(parents,p)] = find(parents,q);
        }
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/102717170-98c93d00-42ae-11eb-9e23-02c74305193a.png)

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
