### ISSUE TITLE
Typo in Sorting Explore Card, Chapter Comparison Based Sorts, Subchapter Heap Sort

### ISSUE THREAD

**Issue by JonMrowczynski** [LeetCode-Feedback/LeetCode-Feedback#17182]
#### Your LeetCode username
jonmrowczynski

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
There is a typo in the Sorting Explore Card, chapter "Comparison Based Sorts", subchapter "Heap Sort" as indicated in the attached screenshot.

#### Code you used for Submit/Run operation
N/A

#### Language used for code
N/A

#### Expected behavior
There should be an "of" as marked in the attached screenshot.

#### Screenshots
![Heap Sort Typo](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/39063205/501ddb92-fdbc-4c3e-b39e-a4460ee67f36)

#### Additional context
N/A

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
