### ISSUE TITLE
Problem #1095 Rust template naming conventions

### ISSUE THREAD

**Issue by Murrelken** [LeetCode-Feedback/LeetCode-Feedback#17181]
#### Your LeetCode username
danilbutin

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
[Problem #1095. Find in Mountain Array](https://leetcode.com/problems/find-in-mountain-array/). The wrong case was used for the template. Rust uses the ```snake_case``` for function parameters specifically.

#### Code you used for Submit/Run operation
```
impl Solution {
    pub fn find_in_mountain_array(target: i32, mountainArr: &MountainArray) -> i32 {
        
    }
}
```

#### Language used for code
Rust

#### Expected behavior
Snake case is the style chosen by Rust team, so naturally it would be ```mountain_arr``` instead of ```mountainArr```
```
impl Solution {
    pub fn find_in_mountain_array(target: i32, mountain_arr: &MountainArray) -> i32 {
        
    }
}
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
