### ISSUE TITLE
Wrong Constraints || wrong test case : 205. Isomorphic Strings

### ISSUE THREAD

**Issue by snehalgadge** [LeetCode-Feedback/LeetCode-Feedback#17186]
#### Your LeetCode username
snehalGadge
https://leetcode.com/snehalGadge/

#### Category of the bug
- []Wrong Constraints
- []wrong test case 

#### Description of the bug
In cons it is given that s.size() == t.size() 
but in this 
s="12" t="\u0067\u0067" 
*test case this is not applied 

#### Code you used for Submit/Run operation

[205. Isomorphic Strings](https://leetcode.com/problems/isomorphic-strings/) 
class Solution {
public:
    bool isIsomorphic(string s, string t) {
        int mapS[256] = {0};
        int mapT[256] = {0};

        for(int i=0; i<s.size(); i++){
            if( !mapS[s[i]] && !mapT[t[i]]){
                mapS[s[i]] = t[i];
                mapT[t[i]] = s[i];
            }else if(char(mapS[s[i]]) != t[i]){
                return false;
            } 
        }
       return true; 
    }
};

#### Language used for code
C++ 

#### Expected behavior
if t.length == s.length is given in the constraints 
then above code should work but getting error 
as getting test case with different length.
for Eg: s="12" t="\u0067\u0067"

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by snehalgadge** [comment]
https://leetcode.com/problems/isomorphic-strings/submissions/1073647700/

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
