### ISSUE TITLE
Achieve is misspelled as achive in 424

### ISSUE THREAD

**Issue by NiChrosia** [LeetCode-Feedback/LeetCode-Feedback#17194]
#### Your LeetCode username

NiChrosia

#### Category of the bug
- [ ] Question
- [ ] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug

"Achieve" is misspelled as "achive."

#### Expected behavior

"Achive" being spelled as "achieve."

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/57579569/bb53710e-cd72-4377-ae89-9431f778a782)

#### Additional context

[Problem 424](https://leetcode.com/problems/longest-repeating-character-replacement/).

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
