### ISSUE TITLE
Poor problem description in 947

### ISSUE THREAD

**Issue by snehasishroy** [LeetCode-Feedback/LeetCode-Feedback#1719]
#### Your LeetCode username
chrisgriffin

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Explanation for examples in https://leetcode.com/problems/most-stones-removed-with-same-row-or-column/  is missing.
Need to clearly mention why the output of [[0,0],[0,2],[1,1],[2,0],[2,2]] is 2 

#### Additional context
Discuss section is filled with people complaining about the fact that they could not understand what the problem means and the output of some test cases.

**Comment by lc-kay** [comment]
Hi @snehasishroy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @snehasishroy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!

**Comment by snehasishroy** [comment]
Hi @lc-kay , thank you for fixing the problem description. I think I am eligible for 100 leetcoins because multiple people have complained about poor description in the comments.

Sample

1. https://leetcode.com/problems/most-stones-removed-with-same-row-or-column/solution/299796
![image](https://user-images.githubusercontent.com/4747384/103297460-5c1fe300-4a1e-11eb-8f41-e0cacd7752af.png)

2. https://leetcode.com/problems/most-stones-removed-with-same-row-or-column/discuss/200034/Someone-please-help-I-just-don't-get-this

**Comment by lc-kay** [comment]
Hi @snehasishroy 
Your LeetCode account has received 100 LeetCoins as the reward for this feedback. Thank you for your time.
