### ISSUE TITLE
The hint of Coin Change 2 in Dynamic Programming explore card is wrong. 

### ISSUE THREAD

**Issue by phamtrongthang123** [LeetCode-Feedback/LeetCode-Feedback#17191]
#### Your LeetCode username
trong_thang

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The direction of the hint is wrong. We need to use 2D state array to solve this challenge (as solution stated), but the hint only tells us 1D array, which cannot deal with duplicates.

#### Code you used for Submit/Run operation
I am not sure if this helps but here is the code using the hint's idea.

```
// Coin Change 2
class Solution:
    def change(self, amount: int, coins: List[int]) -> int:
        def dp(a):
            if a==0: return 1
            if a<0: return 0
            res=0
            for c in coins:
                if a>=c:
                    res+= dp(a-c)
                    
            return res
        return dp(amount)
```

#### Language used for code
Python

#### Expected behavior
The hint should guide in the direction that we must use 2D state array like in the solution.

#### Screenshots
This is the image of the hint in Counting DP section, DP explore card for Coin Change 2
![Screenshot_20231012_144512_Edge](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/17172232/a8776de5-9156-42aa-9faf-1b81ac5745f5)

#### Additional context
The link to the card: https://leetcode.com/explore/learn/card/dynamic-programming/633/common-patterns-continued/4136/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

These hints are correct, they denote the 3rd approach in the official solution.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
