### ISSUE TITLE
Unknown server error when submitting PostgreSQL solution - 597. Friend Requests I

### ISSUE THREAD

**Issue by ELehotzky** [LeetCode-Feedback/LeetCode-Feedback#17193]
#### Your LeetCode username

ele1221

#### Category of the bug
- [ ] Question
- [X ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Running a PostgreSQL solution that worked against the test case throws an error "Unknown server error. Please contact our support team." when submitted.

#### Code you used for Submit/Run operation

```
// 597. Friend Requests I: Overall Acceptance Rate (https://leetcode.com/problems/friend-requests-i-overall-acceptance-rate/)
SELECT ROUND(
    COALESCE(
        (SELECT COUNT(*) FROM (SELECT DISTINCT requester_id, accepter_id FROM RequestAccepted))::numeric
        /
        (SELECT COUNT(*) FROM (SELECT DISTINCT sender_id, send_to_id FROM FriendRequest))::numeric
    ), 2) AS accept_rate;
```

#### Language used for code

PostgreSQL

#### Expected behavior

Either that the solution has been accepted, or a fail with the test case the solution failed on.

#### Screenshots

Running against test case:
<img width="896" alt="Screenshot 2023-10-12 at 6 26 38 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/25112375/7d6f4db1-81d0-4424-adcb-e71802a6d27a">

Submitted and errors:
<img width="904" alt="Screenshot 2023-10-12 at 6 27 27 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/25112375/db4f6dd9-dc69-4ac1-a433-6cf57c8d66aa">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

The issue should fixed. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
