### ISSUE TITLE
Missing Test Case - 523. Continuous Subarray Sum

### ISSUE THREAD

**Issue by kadunkone** [LeetCode-Feedback/LeetCode-Feedback#17190]
#### Your LeetCode username
(https://leetcode.com/vela21/)

#### Category of the bug
- [ ] Question - 523. Continuous Subarray Sum
- [ 1] Solution - nil
- [ ] Language -nil
- [ 1] Missing Test Cases - [23,2,4,6] 6

#### Description of the bug
Expected testcase evaluation should be False, but it is showing True and the leetcode solution page's algorithm also evaluates for True. Why it should return False? Because there is no valid subarray that exactly satisfies the condition - the sum of the elements of the subarray is a multiple of k for the testcase => nums= [23,2,4,6] k= 6

#### Code you used for Submit/Run operation

Please make sure you wrap your code with ``` tags. 
Otherwise we may reject your request. 
``` 
class Solution {
public:
    bool checkSubarraySum(vector<int>& nums, int k) {
    	// initialize the hash map with index 0 for sum 0
        unordered_map<int, int> hashMap{{0, 0}};
        int sum = 0;
        for (int i = 0; i < nums.size(); i++) {
            sum += nums[i];
            // if the remainder sum % k occurs for the first time
            if (!hashMap.count(sum % k))
                hashMap[sum % k] = i + 1;
            // if the subarray size is at least two
            else if (hashMap[sum % k] < i)
                return true;
        }
        return false;
    }
};
``` 

#### Language used for code
Python

#### Expected behavior
Upon testcase evaluation should be False but now it shows True as result that should be expected. But there's no valid subarray for the testcase [23,2,6,4] 6

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/120443890/61281da6-d62e-41b4-b1c0-f9334bffe626)

#### Additional context
 Please evaluate my request and give me that Leetcode coins

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by kadunkone** [comment]
The code submission Accepted link: https://leetcode.com/submissions/detail/1075020582/
After assessing please give me the leetcode coins

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
