### ISSUE TITLE
Missing Test Case - 81. Search in Rotated Sorted Array II

### ISSUE THREAD

**Issue by icherniukh** [LeetCode-Feedback/LeetCode-Feedback#17199]
#### Your LeetCode username

icherniukh

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Solution code below does not handle properly repeated numbers in the middle of the array, however it gets 'Accepted' when submitted.
For example, on testcase below the correct answer is **True**, but the accepted solution actually outputs **False**
> [1,2,2,2,2,2,2,2,0,1]
> 0

#### Code you used for Submit/Run operation

```python3
class Solution:
    def search(self, a: List[int], target: int) -> bool:
        k = 0
        while k + 1 < len(a) and a[k] == a[k + 1]:
            k += 1
        
        step = 1
        while k + step < len(a):
            step <<= 1
        while step > 0:
            if (index := k + step) < len(a) and a[index] > a[k]:
                k = index
            step >>= 1

        l, r = 0, len(a)

        if target >= a[0]:
            r = k + 1
        else:
            l = k + 1
        
        while l + 1 < r:
            m = (l + r) // 2
            if a[m] <= target:
                l = m
            else:
                r = m
        
        return (0 <= l < len(a) and a[l] == target)
```

#### Language used for code

Python3

#### Expected behavior

Solution code above should be getting 'Wrong Answer' result when submitted.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/16390154/602bcaf2-be95-4d7d-a4d5-33b8d87a216b)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/16390154/04c1e1a5-3099-44ea-9eb1-d48a25804cff)

#### Additional context

Link to the submission that gets 'Accepted' but fails on presented tests:
https://leetcode.com/problems/search-in-rotated-sorted-array-ii/submissions/1074019582

Examples of such tests:
[1,2,2,2,2,2,2,2,0,1]
0
[1,2,2,2,2,2,2,7,0,1]
0

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
