### ISSUE TITLE
746. Min Cost Climbing Stairs

### ISSUE THREAD

**Issue by tonytang0909-grl** [LeetCode-Feedback/LeetCode-Feedback#17198]
#### Category of the bug
- [ 1] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Can not either run my code or submit my code,  Got an error saying : "Unknown network error. Please try reloading page."

#### Code you used for Submit/Run operation

```
class Solution {
    public int minCostClimbingStairs(int[] cost) {
        int[] dp = new int[cost.length];
        dp[0] = 0;
        dp[1] = 0;
        for (int i = 2; i < cost.length; i++){
            dp[i] = Math.min(dp[i - 1], dp[i - 2] + cost[i]);
        }
        return dp[cost.length - 1];
    }
}
```

#### Expected behavior

Can not either run my code or submit my code,  Got an error saying : "Unknown network error. Please try reloading page."

#### Screenshots

<img width="904" alt="Screenshot 2023-10-13 at 1 40 19 pm" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/114914962/79fe1c9b-aa6b-452a-be91-d2a1b944251f">

**Comment by tonytang0909-grl** [comment]
I have tried other questions, they all work fine, only this question, I cannot either run or submit my code.

**Comment by tonytang0909-grl** [comment]
Also, because of the unknown error, I can't finish my streak today. Please help me fix the streak. Thank you so much for your help.

**Comment by Divesh-Kumar-Chordia** [comment]
same here

**Comment by Divesh-Kumar-Chordia** [comment]
try in incognito mode it worked out

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

The issue should fixed.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
