### ISSUE TITLE
Problem 2690 Infinite Method Object: solution article has formatting problem

### ISSUE THREAD

**Issue by FanchenBao** [LeetCode-Feedback/LeetCode-Feedback#17201]
#### Your LeetCode username
FanchenBao

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The solution article for Problem 2690 has formatting problem towards the end, as some non-code texts get wrapped in a code block. This disrupts the formatting and makes the article very hard to read.

#### Code you used for Submit/Run operation
NA

#### Language used for code
NA

#### Expected behavior
The solution article has correct formatting.

#### Screenshots
![Screenshot 2023-10-13 at 00 23 28](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/43209858/5fd9bd24-3adc-4340-8c81-b78a8637b19b)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
