### ISSUE TITLE
Missing Test Case - 1231. Replace Elements with Greatest Element on Right Side

### ISSUE THREAD

**Issue by parikshitrath** [LeetCode-Feedback/LeetCode-Feedback#1720]
#### Category of the bug
- [ *] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

In the question it is mentioned that we have to replace the last element with -1 but, the answer is accepted when we shift all elements to left and add -1 at last i.e... deleting first element and pushing back -1. 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<int> replaceElements(vector<int>& arr) {
        int n = arr.size();
        int max_index = n - 1; 
        for(int i = n - 1 ; i >= 0 ; i--)
        {
            if(arr[i] > arr[max_index])
            {
                max_index = i;
                continue;
            }
            if(arr[max_index] > arr[i])
            {
                arr[i] = arr[max_index];
            }
        }
        if(n >= 1)
        {
            arr.erase(arr.begin());
        }
        arr.push_back(-1);
        return arr;
    }
};
```

#### Expected behavior

I think that -1 should be directly replaced with last element

#### Screenshots

Question and the answer provided are enough. My answer was accepted.

**Comment by lc-kay** [comment]
@parikshitrath Can you please provide a test case that produces the description of the bug stated above?

**Comment by parikshitrath** [comment]
Input: arr = [17,18,5,4,6,1]
expected output is :- [18,6,6,6,1,-1]

but, the output if you read the question should be :- [18,18,6,6,6,-1] , because we are replacing the last element with the -1 as we are doing with other elements after finding greater element on right side.

for [18,6,6,6,1,-1] output we have to shift all elements to right and than, insert -1 at last and I don't think question states that!!

Input: arr = [17,18,5,4,6,1]
Leetcode expected output :- [18,6,6,6,1,-1] 
my expected output          :-  [18,18,6,6,6,-1]

**Comment by lc-kay** [comment]
Hi @parikshitrath 
Thank you for the information. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @parikshitrath 
Thank you for your time. We've added an explanation to the example. We hope this clarifies any questions you had about this test case and problem.
