### ISSUE TITLE
Missing Test Case - 2706. Buy Two Chocolates

### ISSUE THREAD

**Issue by anxbt** [LeetCode-Feedback/LeetCode-Feedback#17206]
#### Your LeetCode username
anubrat23

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ .] Missing Test Cases 

#### Description of the bug
In this case, my approach would select the two cheapest chocolates, which are $5 and $7, for a total of $12. However, there's a better combination: buying the chocolates with prices $10 and $15, which would result in $5 leftover money. My approach fails to find the optimal solution in this scenario.Still leetcode accept the solution .
`
int[] prices = {5, 7, 10, 15};
int money = 20;
`

#### Code you used for Submit/Run operation
```
class Solution {
    public int buyChoco(int[] prices, int money) {
        Arrays.sort(prices);
       int sum=prices[0]+prices[1];
       if (money>=sum){
           return (money-sum);
       }
       else {
           return money;
       }
    }
}
```

#### Language used for code
Java

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
