### ISSUE TITLE
 Missing Test Case - 443. String Compression

### ISSUE THREAD

**Issue by bhalotia05** [LeetCode-Feedback/LeetCode-Feedback#17212]
#### Your LeetCode username
kb0506

#### Category of the bug
  Missing Test Case Check  [ "8","I","o","n","U","H","V",",",">","|"]      
wherein index 1 has alphabet 'I' while the last index has bitwise OR operator  

#### Description of the bug
Some of the solutions mentioned in the Discussions section, make use of the method of adding a bitwise OR operator at the last index of input vector array(chars) and then comparing the remaining array with it. Now, this code will not work in cases where the Bitwise OR operator is itself present as a character at the last index of the array. However due to absence of any such test cases, even this code passes all test cases.

#### Code you used for Submit/Run operation
```
class Solution {
public:
    int compress(vector<char>& chars) {
        chars.push_back('|');
        string ans;
        for(int i=0;i<chars.size()-1;i++){
            char tmp2=chars[i];
            int count=1;
            while(chars[i+1]==tmp2){
            count++;
            i++;
        }
        ans=ans+tmp2;
        if(count>1){
            ans=ans+to_string(count);
        }
    }
     int q=0;
    while(q<ans.size()){
        chars[q]=ans[q];
        q++;
    }
    chars[q]='\0';
    return q;
    }
};
```

#### Language used for code
C++

#### Expected behavior
The above code must give error as we have inserted a bitwise OR operator inside the vector chars but all the test cases are still passing if the test case ["8","I","o","n","U","H","V",",",">","|"] is submitted it will show wrong ans thus i want to contribute this test case too.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
