### ISSUE TITLE
Issue in test case in Problem number 589

### ISSUE THREAD

**Issue by vishal-sharma-369** [LeetCode-Feedback/LeetCode-Feedback#17211]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Incorrect Test Cases

#### Description of the bug
The test case input `[1, null]` is incorrect
- The space before `null` should be removed.

#### Code you used for Submit/Run operation

```c++
class Solution {
public:
    void solution(Node*root , vector<int>&ans)
    {
        if(root == NULL) return;
        ans.push_back(root->val);
        for(Node* child : root->children)
            solution(child , ans);
    }
    vector<int> preorder(Node* root) {
        vector<int> ans;
        solution(root, ans);
        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior
The space before `null` should be removed in the test case.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
