### ISSUE TITLE
Missing Test Case - 704. Binary Search

### ISSUE THREAD

**Issue by N1har1ka** [LeetCode-Feedback/LeetCode-Feedback#17218]
#### Category of the bug
- [ ] Question-Given an array of integers nums which is sorted in ascending order, and an integer target, write a function to search target in nums. If target exists, then return its index. Otherwise, return -1.

You must write an algorithm with O(log n) runtime complexity.
- [ ] Solution- -1
- [ ] Language-Java
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// public class Solution {
    public static void main(String args[]){
            int x;
            int target=13;
            int nums[]={-1,0,3,5,9,12};
            x=search(nums,target);
            System.out.println(x);
        }
    public static int search(int[] nums, int target){
        int l=0;
        int h=nums.length;
        int mid;
        while(l<=h){
            mid=(l+h)/2;
            if(target==nums[mid])
            return mid;
            if(target<nums[mid])
            h=mid-1;
            else
            l=mid+1;
        }
        return -1;
    }
}

```

**Comment by N1har1ka** [comment]
Java Code for Binary Search which is based on Divide and Conquer Approach

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
