### ISSUE TITLE
Missing Test Case - 334. Increasing Triplet Subsequence

### ISSUE THREAD

**Issue by marsleezm** [LeetCode-Feedback/LeetCode-Feedback#1721]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

The existing test cases are not extensive enough to test the case where the increasing triplet does not include neither the max or min values of the array.

#### Code you used for Submit/Run operation

```
// Two Sum

var increasingTriplet = function(nums) {
    let max = Math.max(...nums);
    let indexMax = nums.lastIndexOf(max);
    
    for (let i = 1; i < indexMax; i++) {
        if ((nums[i] < max) && (nums[i] > nums[i - 1])) {
            return true;
        }
    }
    
    let min = Math.min(...nums);
    let indexMin = nums.lastIndexOf(min);
    
    for (let i = indexMin + 2; i < nums.length; i++) {
        if ((nums[i] > nums[i - 1]) && (nums[i - 1] > min)) {
            return true;
        }
    }
    
    return false;
};
```
#### Expected behavior

The above code should not pass as it will fail a test case like [100,2,3,4,1] but it actually passed.

**Comment by lc-kay** [comment]
@marsleezm Can you please provide your code in [Playground](https://leetcode.com/playground/new/empty)? I am receiving a Wrong Answer when I submit your code.

**Comment by lc-kay** [comment]
Hi @marsleezm  ,
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
