### ISSUE TITLE
https://leetcode.com/explore/interview/card/cheatsheets/720/resources/4723/

### ISSUE THREAD

**Issue by vg-cyi** [LeetCode-Feedback/LeetCode-Feedback#17215]
The C++ version of code template for Graph BFS uses the method "add" for a queue instead of "push":

queue.add(START_NODE);

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback. 

Please provide us with your username. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by vg-cyi** [comment]
My username on LeetCode is "photoNick".

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
