### ISSUE TITLE
Incorrect test case - 79

### ISSUE THREAD

**Issue by shristy** [LeetCode-Feedback/LeetCode-Feedback#17222]
#### Test case is incorrect

```
board = [["A","B","C","E"],["S","F","E","S"],["A","D","E","E"]]
word ="ABCEFSADEESE"
```

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/4849239/0f79a8ba-56fe-415e-b2e5-f637f77ca543)

**Comment by yumkam** [comment]
Disclaimer: just another leetcode user;
Expected result looks correct:  `A(0,0)B(0,1)C(0,2)E(1,2)F(1,1)S(1,0)A(2,0)D(2,1)E(2,2)E(2,3)S(1,3)E(0,3)`
