### ISSUE TITLE
Missing Test Case - 2905. Find Indices With Index and Value Difference II

### ISSUE THREAD

**Issue by yumkam** [LeetCode-Feedback/LeetCode-Feedback#17227]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Code was accepted, and is accepted by "Run Code", but produces incorrect result on testcase below:
```
[1,2,3,4,5,6]
1
2
```

Produced result:
```
[0,2,0,3,0,4,0,5]
```

According to problem description, result must be two-element array.

#### Code you used for Submit/Run operation

```c++
// code not mine, seen on references to accepted submissions in
// https://leetcode.com/discuss/feedback/4170081/Cheating-In-Weekly-Contest-367-(Question-3)
// (allegedly used by some cheaters)
class Solution {
public:
    vector<int> findIndices(vector<int>& nums, int ind, int val) {
        vector<int>ans;
        int n = nums.size();
        int right = nums[0];
        
        int j = 0;
        int k = 0;
        int left = nums[0];
        for(int i=ind;i<n;i++){
            if(nums[i-ind]>right){
                right = nums[i-ind];
                j= i-ind;
            }
            if(nums[i-ind]<left){
                left = nums[i-ind];
                k = i-ind;
            }
            if(abs(nums[i]-right) >= val){
                return {j,i};
            }
            if(abs(nums[i]-left)>=val){
                ans.push_back(k);
                ans.push_back(i);
            }
            
        }
        if(ans.size()==0){
            return {-1,-1};
        }
        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior

Code should be rejected on both "Run code" and "Submit"

#### Additional context

Same apply to https://leetcode.com/problems/find-indices-with-index-and-value-difference-i/
(code produces incorrect result, but accepted by both "Submit" and "Run code")

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
