### ISSUE TITLE
Incorrect testcase for 205. Isomorphic Strings

### ISSUE THREAD

**Issue by parchinskiy** [LeetCode-Feedback/LeetCode-Feedback#17229]
#### Your LeetCode username
Parchinskiy

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Hello.  I think there is a bug in the question [205. Isomorphic Strings](https://leetcode.com/problems/isomorphic-strings/) in testcase 44.
Input:
s = "12"
t = "\u0067\u0067"
But in question constraints t.length == s.length and s and t consist of any valid ascii character. So code bellow doesn't work. If i add check for eq size of vectors code works fine.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool isIsomorphic(string s, string t) {
        std::unordered_map<int, int> ans1;
        std::unordered_map<int, int> ans2;

        for(int i = 0; i < s.size(); ++i)
        {
            if(ans1.end() == ans1.find(s[i]))
            {
                ans1[s[i]] = t[i];
            }
            if(ans2.end() == ans2.find(t[i]))
            {
                ans2[t[i]] = s[i];
            }
            if(ans1[s[i]] != t[i] || ans2[t[i]] != s[i])
                return false; 
        }
        return true;
    }
};
```

#### Language used for code
C++

#### Expected behavior
Test case meets restrictions

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/30821523/a04bd646-b54a-4721-80e1-49911fee6e0c)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/30821523/4b4f9f7a-9576-4bc5-b162-63a3ade05992)

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team

**Comment by parchinskiy** [comment]
You didn’t understand me, the point is not in my code, the point is that the test case does not correspond to the conditions of the task
The problem states that
t.length == s.length
But in test case 44 the size of the input lines is different

**Comment by parchinskiy** [comment]
@LC-Pam and check comments to the question
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/30821523/2b200701-aafa-4c21-bee1-96630c266488)
