### ISSUE TITLE
Problem: Remove Duplicates from Sorted Array II

### ISSUE THREAD

**Issue by nastaran-motiee** [LeetCode-Feedback/LeetCode-Feedback#17234]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Code you used for Submit/Run operation

```
/**
 * @param {number[]} nums
 * @return {number}
 */
var removeDuplicates = function(nums) {
     let i=2;
     for(let j=2;j<nums.length;j++){
         if(nums[j]!=nums[i-2]){
             nums[i]=nums[j];
             i++;
         }
     }
     return i;

}
```

#### Expected behavior
There is no test case for nums.length === 1.
The code is accepted although it returns 2 when nums.length ===1.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
