### ISSUE TITLE
Missing Test Case - 1027. Longest Arithmetic Subsequence

### ISSUE THREAD

**Issue by Code2swap** [LeetCode-Feedback/LeetCode-Feedback#17245]
#### Your LeetCode username

starcode

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The test cases seem to be week, my incorrect solution submitted successfully.
The test case used: - `[0, 250, 500]`

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int longestArithSeqLength(vector<int>& nums) {
        int ans = 2;
        for(int d = 0; d >= -250; d = (d >= 0 ? -d-1 : -d)) {
            if(d && 500 / abs(d) <= ans) break; // It should be: 500 / abs(d) + 1 <= ans
            vector< int> dp(1001, 0);
            for(int x: nums) {
                if(0 <= x - d && x - d <= 500) ans = max(ans, dp[x] = dp[x - d] + 1);
                else dp[x] = 1;
            }  
        }
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

For the test case : - `[0, 250, 500]`
Expected output = 3 My code's output = 2, still It got submitted.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/25134289/208c006d-5714-453a-8394-44ed1475b523)

#### Additional context

Kindly add the below test - [0, 250, 500]

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
