### ISSUE TITLE
200. Number of Islands - Wrong Function Parameter

### ISSUE THREAD

**Issue by shivansh-yashasvi** [LeetCode-Feedback/LeetCode-Feedback#17256]
#### Your LeetCode username

yashasvi_shivansh_07

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I have added a video at the bottom to clarify the issue.

The question states that there is a 2D binary grid, thereby expecting a ```vector<vector<char>>& grid``` as its function parameter.  But, currently the function's parameter has ```vector<string>& grid```. This causes compilation issue. 

```
// 200. Number of Islands
class Solution {
public:
    int numIslands(vector<string>& grid) {
        return 0;
    }
};
``` 

#### Code you used for Submit/Run operation

```
// 200. Number of Islands
class Solution {
public:
    int numIslands(vector<vector<char>>& grid) {
        return 0;
    }
};
``` 

#### Language used for code

C++

#### Expected behavior

If the argument to ```numIslands``` is changed to ```vector<vector<char>>& grid``` , the compiler runs fine. Infact, all the solutions (including the Leetcode Editorial) has taken the function argument as this. 

If we keep ```vector<string>& grid``` , the compilation fails because in the hidden implementation, the function is supposed to have ```vector<vector<char>>& grid```

#### Screenshots

https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/83114748/78d714ac-17d5-4f6a-9857-f46136b5cbf3

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
