### ISSUE TITLE
Incorrect Solution in Editorial - 1251. Average Selling Price

### ISSUE THREAD

**Issue by ButteryPaws** [LeetCode-Feedback/LeetCode-Feedback#17255]
#### Your LeetCode username
normie_coder

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The solution given in the Editorial doesn't pass all the test cases. It fails on Test Case because it doesn't handle tuples where the `product_id` is present in `Prices` table but not in the `UnitsSold` table. Ideally, a `LEFT OUTER JOIN` should be used and `NULL` values must be set to 0.

#### Code you used for Submit/Run operation

```
# Write your MySQL query statement below
select p.product_id as product_id, ifnull(round((sum(price * units) / sum(units)), 2), 0) as average_price
from Prices as p left outer join UnitsSold as us
on p.product_id = us.product_id
and purchase_date between start_date and end_date
group by p.product_id;
```

#### Language used for code
SQL

#### Expected behavior
The code submitted by me passes all the test cases as opposed to the code provided in the editorial which passes only on 15/16 test cases.

#### Screenshots

![Screenshot](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/87355356/5548bb79-300e-406b-8515-273b53fc6e6e)

#### Additional context

```
SELECT
    p.product_id,
    ROUND(SUM(p.price * u.units) / SUM(u.units), 2) AS average_price
FROM
    Prices AS p
JOIN
    UnitsSold AS u
ON
    p.product_id = u.product_id
    AND u.purchase_date BETWEEN p.start_date AND p.end_date
GROUP BY
    p.product_id;
```
This is the code provided in the editorial which doesn't handle cases when the first table contains a `product_id` which isn't present in the second table.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
