### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by torressam333** [LeetCode-Feedback/LeetCode-Feedback#17252]
#### Your LeetCode username
torressam333

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
I've identified an opportunity to enhance the problem by including an additional test case that explores non-contiguous indices adding up to the target. Presently, the test cases demonstrate contiguous indices (e.g., `[0,1], [1,2]`). However, a more comprehensive test would involve a solution where the expected indices have a gap between their positions.

#### Code you used for Submit/Run operation

```
// Two Sum
/**
 * @param {number[]} nums
 * @param {number} target
 * @return {number[]}
 */
const twoSum = function(nums, target) {
    let hashMap = new Map();

    for(let i = 0; i < nums.length; i++) {
        const sum = target - nums[i];

        if(hashMap.has(sum)) {
            return [hashMap.get(sum), i];
        }

        hashMap.set(nums[i], i);
    }
};
```

#### Language used for code
JavaScript

#### Expected behavior
Expected input's and output's:

```
Input
nums = [3,4,3], target = 6

Expected Output: [0,2]
```

#### Screenshots
N/A

#### Additional context
This request is to add an addtional test case to meet the criteria I outlined above. Thank you for your consideration.

**Comment by LC-Pam** [comment]
![Screen Shot 2023-10-17 at 5 09 06 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/9846dd21-e09a-43c5-bf09-e2e33f32e3a8)
Thank you for your time. 

We've used your feedback to check the problem. 

The test case already exists. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
