### ISSUE TITLE
第111题的scala编译问题

### ISSUE THREAD

**Issue by ttsfather** [LeetCode-Feedback/LeetCode-Feedback#1725]
** Bug 类型**
- [x] 题目 第111题
- [ ] 题解
- [x] 编程语言 scala

**描述**
1、第111题，最后一个case为一个节点上万的树。
2、我分别使用scala语言与java语言，我确保这两种语言的代码一致。
3、结果是，java执行时间7ms，scala执行超时/超内存。
4、我在scala代码中加上starttime与endtime，最后发现对于最后一个case的执行时间只有16ms左右，但是执行时非常缓慢，所以，我有理由认为，大量的时间和内存被用于初始化这棵树。而这也导致了scala代码根本无法提交通过。
5、下面我分别附上scala与java代码，技术人员可以进行测试。
6、就这么一道简单类型的题目，因为我所描述的问题，造成了6、7次失败的提交记录，望可以解决。
7、我甚至使用了root.right的左右节点都为null时，直接返回结果，最终都会超时！！

**你使用的语言**
java

**你提交或者运行的代码**
```
class Solution {
    public int minDepth(TreeNode root) {
        if(root==null) return 0;
        if(root.left!=null&&root.right!=null) 
            return Math.min(minDepth(root.left),minDepth(root.right))+1;
        return minDepth(root.right)+minDepth(root.left)+1;
    }
}
```
**你使用的语言**
scala

**你提交或者运行的代码**
```
object Solution {
    def minDepth(root: TreeNode): Int = {
      if(root == null) return 0;
      if(root.left != null && root.right != null){
        return Math.min(minDepth(root.left),minDepth(root.right)) + 1
      }
      return minDepth(root.right)+minDepth(root.left)+1;
    }
}
```

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，该问题当前已修复并发布到了线上，感谢支持力扣～
