### ISSUE TITLE
Top K Frequent Elements -- My code works in Spyder for same test cases but doesnt work here

### ISSUE THREAD

**Issue by saachi-c** [LeetCode-Feedback/LeetCode-Feedback#17269]
`def topKFrequent(self, nums, k):
        dct = {}
        for i in nums:
            if i not in dct:
                dct[i] = 1
            else:
                dct[i] +=1

        res = {key: val for key, val in sorted(dct.items(), key = lambda ele: ele[1], reverse = True)}
        lst = []
        for i in range(0,k):
            lst.append(list(res.keys())[i])
        return lst`

**Comment by LC-Pam** [comment]
Thank you for reaching out to us! Unfortunately, we are unable to troubleshoot the different behavior between your local IDE and the LeetCode environment.

For this issue, please raise this as a discuss post in the problem discuss section as other users may have run into the same issue and resolved it.

At LeetCode, we care about the whole learning experience that comes with each problem and we encourage users to teach and help each other to enrich their learning. In addition, we want our users to debug their code and learn from the process.

We appreciate your time and support.
