### ISSUE TITLE
面试题 08.10. 颜色填充

### ISSUE THREAD

**Issue by lqzo** [LeetCode-Feedback/LeetCode-Feedback#1726]
**Bug 类型**
- [x] 题目

**描述**
[面试题 08.10. 颜色填充](https://leetcode-cn.com/problems/color-fill-lcci/) 题目描述有误，sr 应为纵坐标， sc 应为横坐标

**屏幕截图**
![image](https://user-images.githubusercontent.com/30641714/102759852-a7e3e400-43af-11eb-85bd-8f5f7fb280f7.png)

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，该题目技术验证没有问题的，建议复习二维数组的相关知识点，必要的时候可以画图方便理解（一般语言都是二维数组可以理解为行优先存放的一个表格）百度百科里的图也很清楚，https://baike.baidu.com/item/%E4%BA%8C%E7%BB%B4%E6%95%B0%E7%BB%84/8168543

**Comment by lqzo** [comment]
> 你好，该题目技术验证没有问题的，建议复习二维数组的相关知识点，必要的时候可以画图方便理解（一般语言都是二维数组可以理解为行优先存放的一个表格）百度百科里的图也很清楚，https://baike.baidu.com/item/%E4%BA%8C%E7%BB%B4%E6%95%B0%E7%BB%84/8168543

是这样的，sr 是二维数组的行，sc为列，二维数组存放的是这种图上的所有的坐标点的色值，当我想取一个点的值是是使用 image[sr][sc] ，即行坐标，列坐标；而一般来说难道不是行坐标为纵坐标，列坐标为横坐标吗？

**Comment by lqzo** [comment]
以 3行 * 3列 的图为例 生成的图像二维数组应该是 [[1, 1, 1], [1, 1, 1], [1, 1, 1]]； 这时图像点坐标 (sr,sc)  position(2, 1) 为例， 若前为横坐标，难道不是指第1行第2列（均0起）二维数组的 image[1][2] 位置，而题目对图像点则是在 image[2][1]

**Comment by feiceh** [comment]
感谢反馈，当前改成了行坐标和列坐标。
