### ISSUE TITLE
654. Maximum Binary Tree, description makes no sense.

### ISSUE THREAD

**Issue by yns01** [LeetCode-Feedback/LeetCode-Feedback#1727]
#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The description says: 
> The left subtree is the maximum tree constructed from left part subarray divided by the maximum number.

The input given is: [3,2,1,6,0,5]
In the given example, the maximum number is 6. How would you divide [3, 2, 1] by 6?? That doesn't make any sense.

In reality, there's nothing to divide.

**Comment by lc-kay** [comment]
Hi @yns01 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @yns01 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
