### ISSUE TITLE
题目 2652. 倍数求和

### ISSUE THREAD

**Issue by Sensente** [LeetCode-Feedback/LeetCode-Feedback#17273]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
Sensente

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
题目描述中 code 段落使用混乱。

**你使用的语言**
C++

**你提交或者运行的代码**
```cpp
class Solution {
public:
    int f(int n, int m) {
        return (m + (n/m)*m) * (n/m) / 2;
    }

    int sumOfMultiples(int n) {
        return f(n, 3) + f(n, 5) + f(n, 7) - f(n, 3*5) - f(n, 3*7) - f(n, 5*7) + f(n, 3*5*7);
    }
};
```

**期望行为**
示例描述中有关 code 项应与题目描述中的保持一致。

**屏幕截图**
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/35966153/09237867-36f7-4a8c-84e9-2c94fb3f674b)

**额外的上下文**
无

**Comment by amcones** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by Sensente** [comment]
> 你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

谢谢！个性域名：leetcode.cn/u/sensente/
