### ISSUE TITLE
2561. Rearranging Fruits - Typo in Question

### ISSUE THREAD

**Issue by agrawalishaan** [LeetCode-Feedback/LeetCode-Feedback#17270]
#### Your LeetCode username
agrawalishaan

#### Category of the bug
- [X ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
This line in the question is messed up:
<img width="299" alt="Screenshot 2023-10-17 at 1 17 11 AM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/113543798/15596be7-95c8-4b87-964f-f7167543a9ec">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

We've relayed this issue to our team to investigate. 

Please note this type of issue (not a description issue)  will not count for the Leetcoins reward.

More information can be found at: https://leetcode.com/discuss/general-discussion/526802/File-Problem-and-Solution-Content-Issues-to-Our-GitHub-Public-Feedback-Repo-Now!

We will get back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
