### ISSUE TITLE
Missing Test Case - 1361. Validate Binary Tree Nodes

### ISSUE THREAD

**Issue by Dmitriev-Andrey** [LeetCode-Feedback/LeetCode-Feedback#17286]
#### Your LeetCode username
Dmitriev-Andrey

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
I have submitted wrong solution because test case was missed. 

#### Code you used for Submit/Run operation

```java
class Solution {
    public boolean validateBinaryTreeNodes(int n, int[] leftChild, int[] rightChild) {
        boolean[] nonRoot = new boolean[n];

        for (int i = 0; i < n; i++) {
            if (leftChild[i] != -1) {
                nonRoot[leftChild[i]] = true;
            }
            if (rightChild[i] != -1) {
                nonRoot[rightChild[i]] = true;
            }
        }

        int root = -1;
        for (int i = 0; i < n; i++) {
            if (!nonRoot[i]) {
                if (root != -1) {
                    return false;
                } else {
                    root = i;
                }
            }
        }

        Stack<Integer> stack = new Stack<>();
        stack.push(0); // I use 0 as root all time

        boolean[] seen = new boolean[n];
        while(!stack.isEmpty()) {
            int node = stack.pop();

            if (seen[node]) {
                return false;
            }

            seen[node] = true;
            if (leftChild[node] != -1) {
                stack.push(leftChild[node]);
            }

            if (rightChild[node] != -1) {
                stack.push(rightChild[node]);
            }
        }

        return true;
    }
}
```

#### Language used for code
java

#### Expected behavior
expected behavior: When a root is not zero and input data has a cycle submit should return fail. Example: n = 4, leftChild = [3,-1,1,-1], rightChild = [-1,3,0,-1]
actual behavior: submit return accepted.

#### Screenshots
<img width="814" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/99101390/7dfb2b83-35f7-47a3-b72f-38eb5ee0d15f">
<img width="814" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/99101390/bb94ecd7-3efc-48c1-9c83-44c7084a751d">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
