### ISSUE TITLE
Missing Test Case - 1361. Validate Binary Tree Nodes

### ISSUE THREAD

**Issue by TheDev05** [LeetCode-Feedback/LeetCode-Feedback#17287]
#### Your LeetCode username
TheDev05 

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Leetcode OJ verdicts incorrect solution as correct.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool validateBinaryTreeNodes(int n, vector<int>& left, vector<int>& right) {
        
    std::vector<int> adj[n];
    for (int i = 0; i < n; i++)
    {
        if (left[i] >= 0)
            adj[i].push_back(left[i]);
        if (right[i] >= 0)
            adj[i].push_back(right[i]);
    }

    std::vector<int> indeg(n, 0);
    for (int i = 0; i < n; i++)
    {
        for (int j = 0; j < adj[i].size(); j++)
            indeg[adj[i][j]]++;
    }

    std::queue<int> inox;
    std::vector<int> vis(n, 0);

    vis[0] = 1;
    inox.push(0);

    while (inox.size())
    {
        int it = inox.front();
        inox.pop();

        for (auto i : adj[it])
        {
            if (vis[i])
                return false;
            else
            {
                vis[i] = 1;
                inox.push(i);
            }
        }
    }

    int count = 0;
    for (int i = 0; i < n; i++)
    {
        if (indeg[i] > 1)
            return false;
        if (indeg[i] == 0)
            count++;
    }

    if (count > 1)
        return false;

    return true;        
    }
};
```

#### Language used for code

C++

#### Expected behavior

I expected incorrect verdict, but got as correct.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73834703/93fa371c-9f2e-471e-93b4-50aedc52e66e)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73834703/3715d853-3710-4c0d-8704-b4520e98f40b)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
