### ISSUE TITLE
Missing Test Case - 141. Linked List Cycle

### ISSUE THREAD

**Issue by VladGakut** [LeetCode-Feedback/LeetCode-Feedback#17285]
#### Your LeetCode username
VladGakut

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Need additional Test Cases 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool hasCycle(ListNode *head) {

        while (head != NULL)
        {
            if (head->val == -3)
                return true;

            head->val = -3;
            head = head->next;
        }

        return false;
    }
};
```

#### Language used for code
C++

#### Expected behavior
My solution has an error. but passes all tests for the task

#### Additional context
Test example where my code will produce an erroneous response:
[3,-3,2]
-1

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/43091504/b160f3bf-ee5f-4699-8cfc-b223df0d55bd)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
