### ISSUE TITLE
'Rank' is a keyword in MySQL and it also used as a column name on (178. Rank Scores)

### ISSUE THREAD

**Issue by afzalsiddique** [LeetCode-Feedback/LeetCode-Feedback#17281]
#### Category of the bug
- [x] Question

### Expected Output
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/56299603/0280f07c-6732-4e5f-a319-797603ba9c9c)

#### Code you used for Submit/Run operation

```
    select score,
        dense_rank() over(order by score desc) as rank
    from scores
```

#### Error Message
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'rank
    from scores' at line 2

**Comment by bchaoss** [comment]
You can use (as 'rank') or (as `rank`) in SQL to avoid this.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

You can use ‘rank’ instead.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
