### ISSUE TITLE
Missing Test Case - 204. Count Primes

### ISSUE THREAD

**Issue by Mer1997** [LeetCode-Feedback/LeetCode-Feedback#17289]
#### Your LeetCode username
Mer1997

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Missed the edge input 0 so some solutions can AC even if their `primes` initialized by `n+1` and try to access `primes[1]`

#### Code you used for Submit/Run operation

```cpp
class Solution {
public:
    int countPrimes(int n) {
        int count= 0;
        vector<bool>prime(n+1,true);
        prime[0]=prime[1]=0;
        for(int i =2;i<n;i++)
        {
            if(prime[i])
            {
                count++;
                for(int j = 2*i;j<n;j=j+i)
                {
                    prime[j]=false;
                }
            }
        }
        return count;


    }
};
```

#### Language used for code

C++

#### Expected behavior

Wrong

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

The query is a bit unclear. We covered input n = 0 in test cases.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
