### ISSUE TITLE
Missing Test Case - 7. Reverse Integer

### ISSUE THREAD

**Issue by dogukanma** [LeetCode-Feedback/LeetCode-Feedback#17282]
#### Your LeetCode username
dogukanma

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Actually this might be or not be considered as a bug, but I believe that there should be at least one more test case to check whether the given instructions are fulfilled or not. 

#### Code you used for Submit/Run operation

```
// Reverse Integer
/**
 * @param {number} x
 * @return {number}
 */
var reverse = function (x) {
    if(x == 0){
        return x;
    }
    let sign;
    if (x < 0) {
        sign = -1;
        x *= -1;
    } else {
        sign = 1;
    }
    let copy = x;
    let reverse = 0;
    while (copy > 0) {
        reverse += copy % 10;
        copy /= 10;
        copy = Math.floor(copy);
        if (copy == 0) {
            if (sign === -1) {
                if (reverse > 0x80000000) {
                    return 0;
                } else {
                    reverse *= -1;
                    return reverse;
                }
            } else {
                if (reverse > 0x7FFFFFFF) {
                    return 0;
                } else {
                    return reverse;
                }
            }
        } else {
            reverse *= 10;
        }
    }
};
```

#### Language used for code
JavaScript

#### Expected behavior
I would expect there to be cases that checks whether the reversed number's value is or is not in the range of signed 32-bit integer.

#### Additional context
If there are hidden cases about the problem, at least 1 case should be shown in testcase section in my opinion.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:



We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by dogukanma** [comment]
The missing test case should give an integer input that is either less than -2^31 or greater than 2^31-1 and expect the returned value to be 0. 

Thank you for your interest.

**Comment by dogukanma** [comment]
> Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
> 
> The missing test case.
> 
> We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

I replied with a comment on this issue I believe. Could you check?

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
