### ISSUE TITLE
Incorrect testcase for 205. Isomorphic Strings

### ISSUE THREAD

**Issue by parchinskiy** [LeetCode-Feedback/LeetCode-Feedback#17294]
#### Your LeetCode username
Parchinskiy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
I wil try again. Test case 44 does not meet the conditions of the task
The problem states that the lengths of the input strings t and s must be the same. In test 44, the lengths of the input strings are different.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool isIsomorphic(string s, string t) {
        int m1[256] = {0}, m2[256] = {0}, n = s.size();
        for (int i = 0; i < n; ++i) {
            if (m1[s[i]] != m2[t[i]]) return false;
            m1[s[i]] = i + 1;
            m2[t[i]] = i + 1;
        }
        return true;
    }
};
```

#### Language used for code
С++

#### Expected behavior
The test case must meet the requirements of the task

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/30821523/2b8e5f64-ff03-473e-b830-d1660e2559d8)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/30821523/9771c004-350c-4360-8555-ede2573c939a)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/30821523/c4c149e6-ee11-4780-9abd-8795e343127f)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
