### ISSUE TITLE
Missing Test Case - 1361. Validate Binary Tree Nodes

### ISSUE THREAD

**Issue by lkvlkvlkv** [LeetCode-Feedback/LeetCode-Feedback#17292]
#### Your LeetCode username
lkvlkvlkv

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Test Cases can be stronger.

#### Code you used for Submit/Run operation

``` cpp=
// Two Sum
class Solution {
public:
    bool validateBinaryTreeNodes(int n, vector<int>& leftChild, vector<int>& rightChild) {
        vector<int> u(n);
        iota(u.begin(), u.end(), 0);

        vector<int> in(n);
        for(int i = 0; i < n; i++) {
            if(leftChild[i] != -1) {
                u[find(leftChild[i], u)] = find(i, u);
                in[leftChild[i]]++;
            }
            if(rightChild[i] != -1) {
                u[find(rightChild[i], u)] = find(i, u);
                in[rightChild[i]]++;
            }
        }
        
        for(int i = 0; i < n; i++) u[i] = find(i, u);
        return unordered_set(u.begin(), u.end()).size() == 1 && 
        count(in.begin(), in.end(), 0) == 1 && 
        count(in.begin(), in.end(), 2) == 0;
    }

    int find(int val, vector<int> &u) {
        return val == u[val] ? val : u[val] = find(u[val], u);
    }
};
```

#### Language used for code

C++

#### Expected behavior

This code is an AC code, but would wrong at this testcase.
```
5
[1, 3, 4, -1, -1]
[2, 4, -1, 4, -1]
```

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/71368064/39a45431-1007-4842-a5e4-66abaf98a085)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
