### ISSUE TITLE
Test Case incorrect  - 1251. Average Selling Price

### ISSUE THREAD

**Issue by ayush0903** [LeetCode-Feedback/LeetCode-Feedback#17290]
#### Your LeetCode username
ayushpatil010

#### Category of the bug
- [x] Solution of  a particular TestCase is incorrect
i.e mentioned below 

Wrong Answer
15 / 16 testcases passed

Input
Prices =
| product_id | start_date | end_date   | price |
| ---------- | ---------- | ---------- | ----- |
| 1          | 2019-02-17 | 2019-02-28 | 5     |
| 1          | 2019-03-01 | 2019-03-22 | 20    |
| 2          | 2019-02-01 | 2019-02-20 | 15    |
| 2          | 2019-02-21 | 2019-03-31 | 30    |
| 3          | 2019-02-21 | 2019-03-31 | 30    |

UnitsSold =
| product_id | purchase_date | units |
| ---------- | ------------- | ----- |
| 1          | 2019-02-25    | 100   |
| 1          | 2019-03-01    | 15    |
| 2          | 2019-02-10    | 200   |
| 2          | 2019-03-22    | 30    |

Use Testcase
Output
| product_id | average_price |
| ---------- | ------------- |
| 1          | 6.96          |
| 2          | 16.96         |

Expected
| product_id | average_price |
| ---------- | ------------- |
| 1          | 6.96          |
| 2          | 16.96         |
| 3          | 0             |

#### Description of the bug
Here Product Id 3 is not mentioned in any of the table hence it can't be the part of the expected answer

#### Code you used for Submit/Run operation
```
select p.product_id , Round(sum(p.price*u.units)/sum(u.units),2) 
as average_price from Prices as p left join UnitsSold as u
on p.product_id = u.product_id 
where u.purchase_date >= p.start_date and u.purchase_date <= p.end_date
group by p.product_id;

```

#### Language used for code
MySQL

#### Expected behavior
In the Expected Output of the last Testcase the Product_id = 3 should not be present as it is not present in neither of the input table.

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
