### ISSUE TITLE
1071. Greatest Common Divisor of Strings Adding one more testcase

### ISSUE THREAD

**Issue by RahulKapoor004** [LeetCode-Feedback/LeetCode-Feedback#17293]
#### Your LeetCode username
kapoorrahul2496

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [yes ] Missing Test Cases 

#### Description of the bug

Test Cases can be stronger. 
In this question, we have two strings s and t, we say "t divides s" if and only if s = t + ... + t (i.e., t is concatenated with itself one or more times). Given two strings str1 and str2, return the largest string x such that x divides both str1 and str2.
Since this question is marked as Easy, we can have one more case which helps in understanding this question better.
 str1 = "ABCDEF"
str2 = "ABC"
Output =""

#### Code you used for Submit/Run operation

```
class Solution {
    public String gcdOfStrings(String str1, String str2) {
        if(!(str1+str2).equals(str2+str1)){
            return "";
        }  
        int gcd = getGcd(str1.length(), str2.length()); 
        return str1.substring(0, gcd);
    }
    public int getGcd(int a, int b) {
        if (b==0){
            return a;
        }        
        return getGcd(b,a%b);
    }
}
```

#### Language used for code
Java

#### Expected behavior

Output will be empty string ""
Because Two strings str1 and str2 will have gcd if and only if str1+str2==str2+str1
If both strings are made of same substring concatenated multiple times, then they will have GCD.

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/55271367/66a06d93-cf29-4d64-8b58-90ceed7fbc9a)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The test case already exists. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by RahulKapoor004** [comment]
Hi Pam
The test case that I mentioned is not present in the question description. Please check below image.
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/55271367/0837dc42-e2b1-4a0f-ad9c-1085fd8d0e26)

Please find the test case that we can add for this question- 
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/55271367/7c1fd2c0-6403-4872-bd89-9158b686ecd2)

Thanks
