### ISSUE TITLE
Wrong Test Case - 579. Find Cumulative Salary of an Employee

### ISSUE THREAD

**Issue by JulianusGao** [LeetCode-Feedback/LeetCode-Feedback#1729]
#### Your LeetCode username

gaoyutong

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

wrong test case
Input:
{"headers": {"Employee": ["Id", "Month", "Salary"]}, "rows": {"Employee": [[1, 1, 20], [2, 1, 20], [1, 2, 30], [2, 2, 30], [3,2,40],[1,3,40], [3,3,60],[1,4,60],[3,4,70],[1,5,70]]}}
Output:
{"headers": ["Id", "Month", "Salary"], "values": [[1, 4, 150], [1, 3, 90], [1, 2, 50], [1, 1, 20], [2, 1, 20], [3, 3, 100], [3, 2, 40]]}
Expected:
{"headers": ["id", "month", "Salary"], "values": [[1, 4, 130], [1, 3, 90], [1, 2, 50], [1, 1, 20], [2, 1, 20], [3, 3, 100], [3, 2, 40]]}
#### Code you used for Submit/Run operation

```
select Id, Month, sum(Salary) over(partition by Id order by Month asc) as Salary
from Employee e1
where Month not in (select * from (
    select distinct Month from Employee where e1.Id = Id order by Month desc limit 1) as e2
                   )
order by Id asc, Month desc
```

**Comment by lc-kay** [comment]
@JulianusGao Our team reviews all test cases extensively before publication, the expected output for this test case is correct. Please check out the discuss tab for this problem for clarification. https://leetcode.com/problems/find-cumulative-salary-of-an-employee/discuss/
