### ISSUE TITLE
1309 add test case

### ISSUE THREAD

**Issue by Gidi233** [LeetCode-Feedback/LeetCode-Feedback#17296]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
哥弟

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述**
以下的代码可以ac，但并不完全正确

**你使用的语言**
C++

**你提交或者运行的代码**
```
class Solution
{
public:
    string freqAlphabets(string s)
    {
        char c[1005] = "";
        int rlen = 0;
        for (int i = 2; i < s.size(); i++)
        {
            if (s[i] == '#')
            {
                int num = stoi(s.substr(i - 2, 2)) - 1;
                c[rlen++] = 'a' + num;
                i = i + 2;
            }
            else
                c[rlen++] = s[i - 2] + 48;
        }
        for (int i = s.find_last_of('#')+1; i < s.size(); i++)//用来判断最后不是#的情况
            c[rlen++] = s[i] + 48;
        return string(c);
    }
};
```

**期望行为**
测试用例为只有1-9的数字时以上的代码不符合预期，但没有对应的测试用例。

**屏幕截图**
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/117757880/86a7ecb4-4b0d-4ff0-936a-9854ddddb8f4)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
