### ISSUE TITLE
744..寻找比目标字母大的最小字母官方解答与测试用例存在问题

### ISSUE THREAD

**Issue by fasafwa** [LeetCode-Feedback/LeetCode-Feedback#173]
** Bug 类型**
- [ ] 题目
- [] 题解
- [ ] 编程语言

**描述**
官方给出的方法二的线性扫描和 方法三的二分法强调“有序”而忽略了题目给出的“循环”,
  根据题目要求数组左边字符不一定比右边的大 如：["z","a","b"]用例，z在a的左边但是z是比a大的，直接使用线性扫描和二分法是不正确的

**题目分析**
  更具题目描述的问题，本题我们重点应该放在“循环”而不是“有序”，甚至可以忽略“有序”，如果是采用有序存放那么官方答案是正确的如["a","c","c","c","b","b"]，如果添加上循环那么该数组就是一个乱序数组。
**你使用的语言**
java

**期望行为**
测试一：
        输入:["z","a","b"] 和‘z’ 
        正确输出：‘a’   
        官方解题输出：方法一“a” 方法二三 “z”
        测试用例解释 :根据题目‘z’是由新一轮a-z的字符，我认为这条测试用例符合题目要求
测试二：
        输入：["a","g","y","c","x","b","w","a","b","c","m","n","z"]  和“w”
        正确输出：“x”
        官方方法一：“x”
        官方方法二："y"
        官方方法三：‘z’

**屏幕截图**
![c9fe404aaf1e34e179bc40dc7b7e80d](https://user-images.githubusercontent.com/50975940/79943099-a10c7680-849a-11ea-89e4-6aa6d5907dc9.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认的～

**Comment by feiceh** [comment]
该题目已更新处理，感谢支持。
