### ISSUE TITLE
题目 2530. 执行 K 次操作后的最大分数

### ISSUE THREAD

**Issue by QAQianXi** [LeetCode-Feedback/LeetCode-Feedback#17309]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
qaqianxi

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
在题目描述，示例 2 中 "第 3 步操作：选中 i = 2 ，nums 变为 [1,1,1,3,3] 。分数增加 3 。" 其中 nums 描述有误，nums[1] 值未进行修改应与上一步执行后的 nums 保持不变

**你使用的语言**
C++

**你提交或者运行的代码**
```
// Maximal Score After Applying K Operations
class Solution {
public:
    long long maxKelements(vector<int>& nums, int k) {
        priority_queue<int,vector<int>,less<>> queueNums;
        long long result = 0;
        for (auto i :nums){
            queueNums.emplace(i);
        }
        for (int i = 0; i < k; ++i) {
            queueNums.push(ceil(queueNums.top() / 3.0));
            result += queueNums.top();
            queueNums.pop();
        }
        return result;
    }
};
```

**期望行为**
将题目描述示例2中"第 3 步操作：选中 i = 2 ，nums 变为 [1,1,1,3,3] 。分数增加 3 。" 改为 "第 3 步操作：选中 i = 2 ，nums 变为 [1,2,1,3,3] 。分数增加 3 。"

**屏幕截图**
![屏幕截图 2023-10-18 195440](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73103893/2d726d70-52e2-4e4f-a8b4-75e7f6c84098)

**额外的上下文**
无

**Comment by amcones** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by QAQianXi** [comment]
> 你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

https://leetcode.cn/u/qaqianxi/    谢谢~
