### ISSUE TITLE
Missing Test Case - 876. Middle of the Linked List

### ISSUE THREAD

**Issue by jasonmutd** [LeetCode-Feedback/LeetCode-Feedback#1730]
#### Your LeetCode username

bowen17

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

For python solution 876, there has been an error for the given python solutions
class Solution(object):
    def middleNode(self, head):
        A = [head]
        while A[-1].next:
            A.append(A[-1].next)
        return A[len(A) / 2]

TypeError: list indices must be integers or slices, not float
    return A[len(A) / 2]

It should return A[len(A)//2]

#### Code you used for Submit/Run operation

```
class Solution(object):
    def middleNode(self, head):
        A = [head]
        while A[-1].next:
            A.append(A[-1].next)
        return A[len(A) // 2]
```

#### Language used for code

Python

**Comment by lc-kay** [comment]
@jasonmutd Can you please include a screenshot of the issue? When I submitted the python solution codes, it didn't give me an error. Thank you for your time!

**Comment by lc-kay** [comment]
Hi @jasonmutd  ,
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
