### ISSUE TITLE
面试题 17.26. 稀疏相似度

### ISSUE THREAD

**Issue by clzstc123** [LeetCode-Feedback/LeetCode-Feedback#1731]
** Bug 类型**
面试题 17.26. 稀疏相似度

**描述**
这个测试用例的预期结果不对
https://leetcode-cn.com/submissions/detail/132824526/testcase/
doc[0]有45389，doc[3]也有45389，所以0,3稀疏相似度不为0，预期结果怎么会没有输出0,3，我输出0,3被判定为wrong

输出
["0,3: 0.0030","0,6: 0.0058","0,12: 0.0017","0,13: 0.0031","0,14: 0.0027","0,15: 0.0034","0,19: 0.0017","0,28: 0.0030","0,35: 0.0022","0,43: 0.0018","0,44: 0.0061","0,46: 0.0045","0,50: 0.0032","0,52: 0.0017","0,54: 0.0032","0,56: 0.0016","0,58: 0.0022","0,66: 0.0048","0,67: 0.0018","0,85: 0.0018","0,86: 0.0081","0,90: 0.0019","0,92: 0.0016","0,100: 0.0036","0,103: 0.0020","0,107: 0.0019","0,117: 0.0018","0,119: 0.0025","0,123: 0.0030","0,125: 0.0021","0,126: 0.0016","0,128: 0.0033","0,129: 0.0035","0,139: 0.0034","0,140: 0.0017","0,145: 0.0034","0,150: 0.0034","0,151: 0.0047","0,155: 0.0016","0,156: 0.0058","0,161: 0.0034","0,162: 0.0046","0,164: 0.0016","0,169: 0.0037","0,173: 0.0019","0,181: 0.0017","0,183: 0.0034","0,194: 0.0029","0,197: 0.0040","0,199: 0.0027","0,205: 0.0028","0,207: 0.0053","0,208: 0.0025","0,210: 0.0027","0,211: 0.0019","0,217: 0.0060","0,219: 0.0021","0,220: 0.0020","0,224: 0.0037","0,225: 0.0020","0,233: 0.0026","0,235: 0.0018","0,236: 0.0021","0,248: 0.0019",...
预期结果
["1,31: 0.0061","5,155: 0.0031","10,310: 0.0052","12,372: 0.0010","4,124: 0.0019","16,497: 0.0023","9,278: 0.0029","4,125: 0.0055","15,464: 0.0022","5,154: 0.0011","12,373: 0.0018","3,92: 0.0014","9,277: 0.0031","1,29: 0.0040","4,126: 0.0014","10,308: 0.0014","3,95: 0.0031","15,467: 0.0012","6,184: 0.0024","5,153: 0.0011","15,466: 0.0074","12,375: 0.0013","14,433: 0.0020","13,400: 0.0028","4,127: 0.0020","0,3: 0.0030","1,28: 0.0020","5,152: 0.0013","16,499: 0.0024","10,309: 0.0021","3,89: 0.0027","9,275: 0.0019","5,159: 0.0035","15,469: 0.0029","14,438: 0.0014","12,368: 0.0028","13,407: 0.0016","1,27: 0.0016","10,306: 0.0013","10,307: 0.0057","3,88: 0.0044","7,220: 0.0030","8,253: 0.0034","5,158: 0.0019","1,26: 0.0013","0,6: 0.0058","14,436: 0.0037","4,122: 0.0015","15,471: 0.0011","1,25: 0.0021","8,254: 0.0022","5,157: 0.0023","8,255: 0.0017","7,222: 0.0058","15,470: 0.0023","1,24: 0.0017","3,90: 0.0016","12,371: 0.0011","14,437: 0.0026","14,442: 0.0056","15,473: 0.0035","12,380: 0.00...

**你使用的语言**
java

**你提交或者运行的代码**
```
class Solution {
    public List<String> computeSimilarities(int[][] docs) {
 List<String> rtn = new ArrayList<String>();
            
            HashMap<Integer, ArrayList<Integer>> collision = new LinkedHashMap<Integer, ArrayList<Integer>>();
            int tmp[][] = new int[500][500];
            
            for (int row = 0; row < docs.length; ++row)
            {
                for (int col = 0; col < docs[row].length; ++col)
                {
                    int value = docs[row][col];
                    ArrayList<Integer> already_value_row = null;
                    if (collision.containsKey(value))
                    {
                        already_value_row = collision.get(value);
                    } else
                    {
                        already_value_row = new ArrayList<Integer>();
                        collision.put(value, already_value_row);
                    }
                    
                    for (int i = 0; i < already_value_row.size(); ++i)
                    {
                        int alreadyrow = already_value_row.get(i);
                        tmp[row][alreadyrow]++;
                        tmp[alreadyrow][row]++;
                    }
                    already_value_row.add(row);
                }
            }
            
            for (int row = 0; row < docs.length; ++row)
            {
                for (int col = row + 1; col < docs.length; ++col)
                {
                    int samenum = tmp[row][col];
                    if (samenum != 0)
                    {
                        Float similarity = samenum * 1.0f / (docs[row].length
                                + docs[col].length - samenum);
                        String similarity_str = String.format("%.4f",
                                similarity);
                        String str = "" + row + "," + col + ": "
                                + similarity_str;
                        rtn.add(str);
                    }
                }
            }
            
            return rtn;
    }
}
```

**期望行为**
0,3 等其余应当输出

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，该题目技术验证没有问题的，预期结果并不是按照顺序返回的，里面有「0,3」。后续刷题学习中遇到困难，也可以通过阅读题目评论和题解看到一些解题思路。
