### ISSUE TITLE
Missing test case - 1458. Max Dot Product of Two Subsequences

### ISSUE THREAD

**Issue by davion-258** [LeetCode-Feedback/LeetCode-Feedback#17311]
#### Your LeetCode username

davion-vn

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I submitted the wrong solution but got accepted because of a missing test case.

**Wrong test case**: 
Input: num1 = [-1000], num2 = [1000]
Output: -1000

#### Code you used for Submit/Run operation

```
class Solution:
    def maxDotProduct(self, nums1: List[int], nums2: List[int]) -> int:
        m, n = len(nums1), len(nums2)
        @cache
        def dp(i, j) -> int:
            if i == len(nums1) or j == len(nums2):
                return -1000
            only = nums1[i] * nums2[j]
            include = only + dp(i + 1, j + 1)
            exclude_i = dp(i + 1, j)
            exclude_j = dp(i, j + 1)
            res = max(include, exclude_i, exclude_j, only)
            return res
        return dp(0, 0)
```

#### Language used for code

Python3

#### Expected behavior

The solution should get "Wrong Answer" result.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
