### ISSUE TITLE
2664. The Knight’s Tour - Incorrect Language

### ISSUE THREAD

**Issue by agrawalishaan** [LeetCode-Feedback/LeetCode-Feedback#17317]
#### Your LeetCode username
agrawalishaan

#### Category of the bug
- [ X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the question, it writes:
![Screenshot 2023-10-18 at 11 11 12 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/113543798/bb894136-bb2a-4974-91c9-7b73d5af2810)

This sentence is nonsensical / doesn't make grammatical sense. It should say:

You are given two positive integers m and n which are the height and width of a 0-indexed 2D-array board, and a pair of positive integers (r, c) which is the starting position of the knight on the board.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
