### ISSUE TITLE
Incorrect time complexity in the solution - 1361. Validate Binary Tree Nodes

### ISSUE THREAD

**Issue by przemek3d88** [LeetCode-Feedback/LeetCode-Feedback#17312]
#### Your LeetCode username
przemysaw2

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
1. The description in dfs solution is incorrect:
``` You may notice that some of these rules imply each other. For example, if a binary tree had a root, it would have a cycle only if there was a node with more than one parent.```
The above is incorrect. The tree must be also connected, otherwise, you can have a separate cycle component.

2. The time complexity of the union-find solution is incorrect. We use only the path compression here, so it should be a regular log instead of an iterated log. Please see [this](https://stackoverflow.com/questions/56229760/what-is-the-complexity-of-path-compression-technique-for-disjoint-set-algorithm) for an explanation.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the issue 1. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

For feedback 2: it’s still O(n) without ranking, please see more explanation in the complexity analysis section.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
