### ISSUE TITLE
Missing Test Case - 1361 (Validate Binary Tree Nodes)

### ISSUE THREAD

**Issue by Vipuljain09** [LeetCode-Feedback/LeetCode-Feedback#17326]
#### Your LeetCode username
vipuljainbrt

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
Missing test Case
 n = 9
leftChild - [1,3,4,6,8,-1,-1,-1,-1]
rightChild - [2,8,5,7,-1,-1,-1,-1,-1]

#### Description of the bug
For the above test Case my code is accepted but it gives the wrong output. This type of test case in not includes in testcases.

#### Code you used for Submit/Run operation

```
class Solution {
    bool soln2(int n, vector<int>& leftChild, vector<int>& rightChild) {
        // Base case
        if (n == 1) { return true; }

        // Finding the parents of all nodes
        map<int, int> parent;
        for (int i = 0; i < n; i++) {
            if (leftChild[i] != -1) {
                parent[leftChild[i]] = i;
            }
            if (rightChild[i] != -1) {
                parent[rightChild[i]] = i;
            }
        }

        // check if there is only one node such that it have no parent
        if (n - parent.size() != 1) { return false; }
        int root = -1;
        // finding the root of the tree
        for (int i = 0; i < n; i++) {
            if (parent.find(i) == parent.end()) {
                root = i;
                break;
            }
        }
        if (root == -1) { return false; }
        
        queue<int> q;
        q.push(root);
        vector<bool> vis(n, false);
        int cntVis = 0;
        while (!q.empty()) {
            int node = q.front();
            q.pop();
            vis[node] = true;
            cntVis++;
            if (leftChild[node] != -1 && vis[leftChild[node]] == false) {
                q.push(leftChild[node]);
            }
            if (rightChild[node] != -1 && vis[rightChild[node]] == false) {
                q.push(rightChild[node]);
            }
        }
        if (cntVis == n) { return true; }
        else { return false; }
    }
public:
    bool validateBinaryTreeNodes(int n, vector<int>& leftChild, vector<int>& rightChild) {
        return soln2(n, leftChild, rightChild);
    }
};
```

#### Language used for code

C++

#### Expected behavior

"Our LeetCode solution should have been marked as incorrect according to the provided input, but it was mistakenly accepted by LeetCode."

#### Screenshots

![Screenshot (4169)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/87020143/6cf38eec-f199-4317-9cf5-ecfb6772e82b)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
