### ISSUE TITLE
Missing Test Case -225 Implement Stack using Queues

### ISSUE THREAD

**Issue by bhardwajjitin** [LeetCode-Feedback/LeetCode-Feedback#17328]
#### Your LeetCode username
 bhardwaj_jitin 

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
A Test Case is Missing in Question No. 225 : Implement Stack using Queues

#### Code you used for Submit/Run operation

```
//Implement Stack using Queues
class MyStack {
public:
    int size;
    queue<int>q2;
    MyStack() {

    }
    int flag=0;
    void pushin(queue<int>&q2,int&mark){
        if(mark==0){
        if(q2.empty()){
            return;
        }
        int temp=q2.front();
        q2.pop();
        pushin(q2,mark);
        q2.push(temp); 
        }
        mark=1;
    }
    void push(int x) {
      q2.push(x);
      flag=0;
    }
    int pop() {
       pushin(q2,flag);
       int ans= q2.front();
       q2.pop();
       return ans;
    }
    int top() {
       pushin(q2,flag);
       int ans= q2.front();
       return ans;
    }
    
    bool empty() {
        if(!q2.empty()){
            return false;
        }
        return true;
    }
};

```

#### Language used for code
 C++ 

#### Additional context
["MyStack","push","push","push","top","push","push","pop","pop","pop","push","top","empty"]
[[],[1],[2],[3],[],[4],[5],[],[],[],[6],[],[]] 
this was the Test Cases where this code fails

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
