### ISSUE TITLE
URL shortening system page has broken images

### ISSUE THREAD

**Issue by zuyevicha** [LeetCode-Feedback/LeetCode-Feedback#17324]
#### Your LeetCode username
user9017Nx

#### Description of the bug
https://leetcode.com/explore/interview/card/system-design-for-interviews-and-beyond/735/practice-problems/4823/ contains broken images:
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/90445311/157e1d18-b77c-4e66-a620-d92a169b07cf)

#### Expected behavior
Images should be shown.

#### Workaround
Images are available by the absolute links with https://leetcode.com/problems/ prefix, e.g. https://leetcode.com/problems/Figures/System_Design_for_Interviews_and_Beyond/Chapter_15/URL_shortening_system/1.png

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
