### ISSUE TITLE
Error in solution example - 139. Word Break

### ISSUE THREAD

**Issue by kklemm91** [LeetCode-Feedback/LeetCode-Feedback#1733]
#### Your LeetCode username
kklemm91

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
In the 6th and 7th slides of the "Approach 3: Using Breadth-First-Search" solution example, the left side of the BFS tree builds a solution starting with ["cat"], then ["cat", "sand"], then [**"cats", "and"**, "dog"]. The bolded text is not based on the first 2 iterations, rather it is based on the solution derived from the right side of the BFS tree.

#### Expected behavior
The last iteration on the left side of the BFS tree should be ["cat", "sand", "dog"].

#### Screenshots
![example](https://user-images.githubusercontent.com/1208985/102930421-049fd700-4462-11eb-858c-620bf2d30c4b.png)

**Comment by lc-kay** [comment]
Hi @kklemm91 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @kklemm91 
Thank you for your time. We've noted this issue and will fix it in the near future.
