### ISSUE TITLE
Wrong Expected Output - 326. Power of Three

### ISSUE THREAD

**Issue by therm11011** [LeetCode-Feedback/LeetCode-Feedback#17334]
#### Your LeetCode username
therm

#### Category of the bug
- [ ] Question
- [/] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
9 is not a power of 3

#### Code you used for Submit/Run operation

```
// Power of Three
class Solution {
public:
    bool isPowerOfThree(int n) {
        int tmp = cbrt(n);
        
        if (n % 3 == 0){
            if(tmp == 3){
                return true;
            }
            else 
                return false;
        } else {
            return false;
        }
    }
};
```

#### Language used for code
C++

#### Expected behavior
It must return to false because 9 is not a power of 3.

#### Screenshots
![Screenshot 2023-10-20 044140](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/142201553/ad49b7db-67a9-45a9-8ce0-4f083fc96ce6)

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
