### ISSUE TITLE
The Go runtime looks broken - 341. Flatten Nested List Iterator

### ISSUE THREAD

**Issue by Finesse** [LeetCode-Feedback/LeetCode-Feedback#17339]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Bug 

#### Description of the bug

Any solution fails with:

```
runtime: out of memory: cannot allocate 155189248-byte block (301662208 in use)
fatal error: out of memory
runtime.throw({0x4c6af1?, 0x496f?})
panic.go, line 992
runtime.(*mcache).allocLarge(0x0?, 0x92de000, 0x1)
mcache.go, line 215
runtime.mallocgc(0x92de000, 0x0, 0x0)
malloc.go, line 1096
runtime.growslice(0x4b1ca0?, {0xc000580000?, 0xbbfc00?, 0xbbfc00?}, 0xbbfc01?)
slice.go, line 272
main.__helper__(...)
solution.go, line 48
main.main()
solution.go, line 76
runtime.main()
proc.go, line 250
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00005cfe8 sp=0xc00005cfe0 pc=0x45d2e1
```

#### Code you used for Submit/Run operation

Even a simple mock solution that returns constant values: 

```go
type NestedIterator struct {}

func Constructor(nestedList []*NestedInteger) *NestedIterator {
  return &NestedIterator{}
}

func (this *NestedIterator) Next() int {
  return 0
}

func (this *NestedIterator) HasNext() bool {
  return true
}
```

#### Language used for code

Go

#### Expected behavior

No out-of-memory error for the above solution.

#### Additional context

I've solved many problems using Go, this is the first such case.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by Finesse** [comment]
@LC-Pam The problem is not solved. Now I get just «Memory Limit Exceeded» instead of the detailed error message when I run the simplest code above.

**Comment by Finesse** [comment]
@LC-Pam The problem is not solved. No the error is «Memory Limit Exceeded» instead of the detailed message, when I execute the simplest solution from an above code snippet.
