### ISSUE TITLE
Clicking for detail explanation not formatted

### ISSUE THREAD

**Issue by tyh835** [LeetCode-Feedback/LeetCode-Feedback#17341]
#### Your LeetCode username
tonyh94

#### Description of the bug
Any "Click here for detailed explanation" box in Data Structure and Algorithm course is not formatted, making it very hard to read.

#### Screenshots
<img width="851" alt="Screen Shot 2023-10-19 at 7 36 06 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/35411959/760836bc-96fd-49bc-a571-b2ec02954ce6">

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've submitted your feedback to the team.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
