### ISSUE TITLE
Wrong output in a TestCase in problem[1802 Maximum value at given index]

### ISSUE THREAD

**Issue by Shiv-Expert2503** [LeetCode-Feedback/LeetCode-Feedback#17346]
#### Your LeetCode username
ssgyanibaba

#### Category of the bug
- [X] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
There is one test case 178/370 in which n=4 index=0 maxSum=4. It is showing me the output 1 which implies that the resultant array should look like 1 1 1 1, which is wrong according to me the resulting array must be 2 1 0 0 as we have to maximize the element at the index position. My output 2 1 0 0 satisfies all the conditions. Hence please update your answer AS SOON AS POSSIBLE

#### Code you used for Submit/Run operation

```
class Solution {
private:
//finding sum to add in maxSum
    int sum(int size,int n)
    {
        if(n==0 || size==0)
            return 0;
        else
        {
            size--;
            return n+sum(size,n-1);
        }
    }
public:
    int maxValue(int n, int index, int maxSum) {
        if(n==1)
        {
            return maxSum;
        }
        if(n==2)
        {
            return (maxSum+1)/2;
        }

        //just add ans to maxSum and then divide it by n this will give you the answer
        int ans=sum(n,index)+sum(n,n-index-1);

        //just a check if the final answer satifying all the 3 conditions or not
        if(sum(n,(maxSum+ans)/n)>maxSum)
            return ((maxSum+ans)/n)-1;

        return (maxSum+ans)/n;
    
    }
};
```

#### Language used for code
C++

#### Expected behavior
The output must be 2 as the resultant array will be 2 1 0 0. Hence arr[index]=2.

#### Additional context
Please update the test case as soon as possible

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
