### ISSUE TITLE
Missing Test Case - 1668. Maximum Repeating Substring

### ISSUE THREAD

**Issue by rabeeh003** [LeetCode-Feedback/LeetCode-Feedback#17344]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by rabeeh003** [comment]
Input
sequence =
"aaabaaaabaaabaaaabaaaabaaaabaaaaba"
word =
"aaaba"
Output
7
Expected
5

please count this words in sequence. my out put is correct. your expected count is not correct.

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
