### ISSUE TITLE
Unclear description and problematic test cases

### ISSUE THREAD

**Issue by PushkarP-404** [LeetCode-Feedback/LeetCode-Feedback#17345]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The code clearly functions as required as per the description of the question.
Three default test cases are passed, but are the only ones which are passed.

Example test case:
s = "words and 987"
The output according to the question should be 987 and it is what the code returns. But the test case Expected output is 0, which does not make sense according to the given question.

#### Code you used for Submit/Run operation

```
// String to Integer (atoi)
class Solution:
    def myAtoi(self, s: str) -> int:
        a = ""
        bol = False
        if '-' in s:
            bol = True
        for x in s:
            if x.isdigit():
                a += x
        a = int(a)
        if bol is True:
            a *= -1
        return a
```

#### Language used for code
Python

#### Expected behavior
The code works as required by the given question, but most of the test cases are failed.

#### Screenshots

<img width="521" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/143997985/99e7f53b-aa6e-41a7-8d21-e975c25f50b9">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem name. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by PushkarP-404** [comment]
Sure,
The problem name is String to Integer (atoi) , problem number 8.
https://leetcode.com/problems/string-to-integer-atoi/

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team

**Comment by PushkarP-404** [comment]
Okay, thank you for the response
