### ISSUE TITLE
Missing testcase for isomorphic-strings

### ISSUE THREAD

**Issue by shravanijoshi8** [LeetCode-Feedback/LeetCode-Feedback#17347]
#### Your LeetCode username

shravani8

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

I found my code being accepted but this testcase fails for my code
s="12"
t="\u0067\u0068"
This case needs to be added accurate testing

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool isIsomorphic(string s, string t) {
        if(s.length()!=t.length())
            return false;
        map<char,char> m;
        set<char> q;
        for(int i=0;i<s.length();i++){
            if(m.find(s[i])==m.end() && q.find(t[i])==q.end()){
                m[s[i]] = t[i];
                q.insert(t[i]);
            }
            else if(m[s[i]]!=t[i])
                return false;
        }
        return true;
    }
};
```

#### Language used for code
C++

#### Expected behavior

The code shouldn't be accepted as it fails for this testcase

#### Screenshots

<img width="960" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/42909319/c8ea0e45-15a4-47d2-8f5f-275dcc6476db">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
