### ISSUE TITLE
Missing Test Case - 2630. Memoize II

### ISSUE THREAD

**Issue by LinStan** [LeetCode-Feedback/LeetCode-Feedback#17350]
#### Your LeetCode username

花Q

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Missing check test case for cached values when the function return value is undefined

example input case

```
() => [[2,2],[2,2],[1,2]]
function (a, b) { return undefined; }

```

expected return

```
[{"calls":1},{"calls":1},{"calls":2}]
```

my submit code return
```
[{"calls":1},{"calls":2},{"calls":3}]
```

#### Code you used for Submit/Run operation

```
// my submit code [error]
type Fn = (...params: any) => any

function memoize(fn: Fn): Fn {
    const argsMap = new Map<any, number>();
    const map: Map<string, any> = new Map();
    let index = 0;
    return function (...args) {
        const argsKey = args.reduce((pre, cur) => {
            if (!argsMap.has(cur)) {
                argsMap.set(cur, index++);
            }
            return pre + '-' + argsMap.get(cur)
        }, '');

        // this is a right judge
        // if (!map.has(argsKey)) {
        // which is wrong, but my commit passed
        if (map.get(argsKey) === undefined) {
            const result = fn(...args);
            map.set(argsKey, result);
        }
        return map.get(argsKey)
    }
}
```

#### Language used for code

TypeScript

#### Expected behavior

By completing my test case, a similar code submit should get WA back

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/27475415/f0c07841-23f9-40a3-9776-94ea1e0dea47)

#### Additional context

my submit url detail : https://leetcode.cn/submissions/detail/475894943/
my leetcode homepage url: https://leetcode.cn/u/huaku/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Duplicated issue #17351 https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/17351
