### ISSUE TITLE
 Language - Need More Execution Time for MS SQL

### ISSUE THREAD

**Issue by bchaoss** [LeetCode-Feedback/LeetCode-Feedback#17357]
#### Your LeetCode username
bchaoss

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

In some database problems, the MS SQL version of the code, which is correct, encounters a "Limit Time Exceeded" situation. However, the same SQL code would be executed successfully in other query languages like MySQL. 

#### Code you used for Submit/Run operation

1068:
```
select product_name, year, price
from sales, product
where product.product_id = sales.product_id;
```

1633:
```
select contest_id, round(count(user_id)*100.0/(select count(*) from users), 2) as percentage
from register
group by contest_id
order by percentage desc, contest_id asc
```
(Although I managed to resolve this issue in 1633 using CTE.)

#### Language used for code
MS SQL Server

#### Expected behavior

I think we need more execution time for some problems in MS SQL Server. Since the exact same code in MySQL was successfully accepted for the same problem, and there is no room for optimization in this MS SQL code. The first time I encountered this situation was in problem 1068. I have also encountered this issue in other LeetCode problems, such as 1633. Please take a look.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103650247/028e1f0c-5d00-486a-89be-7e5d634a0283)

#### Additional context

problem 1068, problem 1633, etc.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
