### ISSUE TITLE
Missing Test Case - 2630. 记忆函数 II

### ISSUE THREAD

**Issue by LinStan** [LeetCode-Feedback/LeetCode-Feedback#17351]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名
花Q
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/27475415/1d07ffde-e8d9-4c8f-84fa-a022f9c75775)

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述**
描述你遇到的 bug
测试用例缺失了对fun返回值为undefined情况下记忆函数生效的检测。
缺失的用例case

```
() => [[2,2],[2,2],[1,2]]
function (a, b) { return undefined; }

```

期望的返回

```
[{"calls":1},{"calls":1},{"calls":2}]
```

我提交的代码返回
```
[{"calls":1},{"calls":2},{"calls":3}]
```

**你使用的语言**
TypeScript

**你提交或者运行的代码**
```
// my submit code [error]
type Fn = (...params: any) => any

function memoize(fn: Fn): Fn {
    const argsMap = new Map<any, number>();
    const map: Map<string, any> = new Map();
    let index = 0;
    return function (...args) {
        const argsKey = args.reduce((pre, cur) => {
            if (!argsMap.has(cur)) {
                argsMap.set(cur, index++);
            }
            return pre + '-' + argsMap.get(cur)
        }, '');

        // this is a right judge
        // if (!map.has(argsKey)) {
        // which is wrong, but my commit passed
        if (map.get(argsKey) === undefined) {
            const result = fn(...args);
            map.set(argsKey, result);
        }
        return map.get(argsKey)
    }
}
```

**期望行为**
补全缺失的测试case，对于类似的使用undefined来判断缓存生效的提交应该返回WA而不是pass

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
通过的截图
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/27475415/918f014f-692d-4425-88cf-50901e8469d3)
代码运行错误case的截图
![image](https://user-images.githubusercontent.com/27475415/276947178-f0c07841-23f9-40a3-9776-94ea1e0dea47.png)

**额外的上下文**
添加额外的上下文信息
不确定我的用户名是`花Q`还是`huaku`，希望正确发放leetCoin🤭
错误通过提交的url : https://leetcode.cn/submissions/detail/475894943/
我的主页 url: https://leetcode.cn/u/huaku/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
