### ISSUE TITLE
Description - 855. Exam Room

### ISSUE THREAD

**Issue by Jeetaksh** [LeetCode-Feedback/LeetCode-Feedback#17358]
#### Your LeetCode username
Jeetaksh

#### Category of the bug
-  Question description

#### Description of the bug
According to the question, the seat function returns the seat label of the seat where next student will sit. There could be a scenario in which all the seats are filled, and the seat function is called. It should be clearly mentioned in the problem description that seat() is called only when there is at least 1 empty seat available for the next person.

Example:
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/92541718/e7a0f621-3653-4124-977c-d0092d4ed34e)
Another person can sit on a seat if someone leaves it, each time seat() call is made, the person is assigned the seat 0 when all the seats are occupied. Such a thing should be clearly mentioned in problem description and such creating such testcases should become invalid.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
