### ISSUE TITLE
Missing Test Case - 2081. Sum of k-Mirror Numbers

### ISSUE THREAD

**Issue by jaisw7** [LeetCode-Feedback/LeetCode-Feedback#17355]
#### Your LeetCode username
jaisw7

#### Category of the bug
- [x] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
```
Example 3:

Input: k = 7, n = 17
Output: 20379000
Explanation: The 17 smallest 7-mirror numbers are:
1, 2, 3, 4, 5, 6, 8, 121, 171, 242, 292, 16561, 65656, 2137312, 4602064, 6597956, 6958596
```

The explanation doesn't take into account `all` smallest numbers:

4747 in base-10 = 16561 in base-7
5252 in base-10 = 21212 in base-7

Accordingly, the 17 smallest 17-mirror numbers are:
```
1, 2, 3, 4, 5, 6, 8, 121, 171, 242, 292, 4747, 5252, 16561, 65656, 2137312, 4602064
```
and the output should be: `6832447`

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team

**Comment by jaisw7** [comment]
The question description says
```
Explanation: The 17 smallest 7-mirror numbers are:
1, 2, 3, 4, 5, 6, 8, 121, 171, 242, 292, 16561, 65656, 2137312, 4602064, 6597956, 6958596
```

However, the 17 smallest 17-mirror numbers are:
```
1, 2, 3, 4, 5, 6, 8, 121, 171, 242, 292, 4747, 5252, 16561, 65656, 2137312, 4602064
```

There is clearly a discrepancy because
```
4747 in base-10 = 16561 in base-7
5252 in base-10 = 21212 in base-7
```

Let me know if you want any further clarification.
