### ISSUE TITLE
Missing Test Case - 1425. Constrained Subsequence Sum

### ISSUE THREAD

**Issue by Bog-II** [LeetCode-Feedback/LeetCode-Feedback#17365]
#### Your LeetCode username
bog-II

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
The given solution code passes the existing test suite for the problem "1425. Constrained Subsequence Sum". However, it fails for a valid input case, where the maximum sum of a constrained subsequence is not computed correctly.

#### Code you used for Submit/Run operation
```python3
class Solution:
    def constrainedSubsetSum(self, nums: List[int], k: int) -> int:

        mono_queue = [(0, nums[0])]
        for j in range(1, len(nums)):
            if j - mono_queue[0][0] > k:
                mono_queue.pop(0)
            num = nums[j]
            curr_ans = max(num, num + mono_queue[0][1])
            while len(mono_queue) > 0 and mono_queue[-1][1] <= curr_ans:
                mono_queue.pop()
            mono_queue.append((j, curr_ans))
        
        return max(*nums, mono_queue[0][1])
```

#### Language used for code
Python3

#### Expected behavior
For the input:
```
nums = [-1,-2, 3, 7, -100, -100, -100]
k = 2
```
The expected output should be 10 (from the subsequence [3,7]), but the provided solution gives the output 7.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
