### ISSUE TITLE
Missing Test Case - 879. Profitable Schemes

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#1736]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution is accepted but fails on the following test case:
64
0
[80, 40]
[88, 88]

#### Code you used for Submit/Run operation

```
class Solution {
    private static final int MOD = 1000000000 + 7;
  public int profitableSchemes(int G, int P, int[] group, int[] profit) {
        int n = group.length;

        int[][] dp = new int[101][10001];
        int[][] old = new int[101][10001];

        dp[0][0] = 1;

        for (int i = 0; i < n; i++) {
            for (int j = G; j >= 0; j--) {
                for (int k = 10000; k >= 0; k--) {
                    if (dp[j][k] > 0 && j + group[i] <= G) {
                        dp[j + group[i]][k + profit[i]] += dp[j][k];

                        if (dp[j + group[i]][k + profit[i]] > 0) {
                            dp[j + group[i]][k + profit[i]] %= MOD;
                        }
                    }
                }
            }
        }

        int res = 0;
        for (int j = G; j >= 1; j--) {
            for (int k = 10000; k >= P; k--) {
                if (dp[j][k] > 0) {
                    res = (res + dp[j][k]) % MOD;
                }
            }
        }
        return res;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/102945439-b273ab80-448b-11eb-87db-499a604a14e2.png)

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
