### ISSUE TITLE
Incorrect description in space complexity - 1425. Constrained Subsequence Sum

### ISSUE THREAD

**Issue by mdes4214** [LeetCode-Feedback/LeetCode-Feedback#17367]
#### Your LeetCode username

mdes4214

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Incorrect description in space complexity in Approach 3: Monotonic Deque

#### Expected behavior

The checking ensures that the size of `queue` will not be greater than `k`.
- To check if the max value is out of range, we check if `i - queue.front() > k`.
```java
            if (!queue.isEmpty() && i - queue.peek() > k) {
                queue.poll();
            }
```

So, though the space complexity in Approach 3 is correct, the description should be like:
"`queue` will not be greater than a size of `k`, but `dp` requires `O(n)` space."

> If we use an integer to store the maximum sum instead of all sums in `dp` (store both sums and indexes in `queue`), the space complexity can be reduced to `O(k)`.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
