### ISSUE TITLE
Missing Test Case - 61. Rotate List - One Node

### ISSUE THREAD

**Issue by Calixtep** [LeetCode-Feedback/LeetCode-Feedback#17360]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A test case should be included for the scenario where the linked list has only one node. Depending on how the code is written, it may run into a segfault when trying to look ahead at a 2nd node by dereferencing a "next" pointer which is empty and points to NULL.

#### Code you used for Submit/Run operation

```
// Rotate List
class Solution {
public:
    ListNode* rotateRight(ListNode* head, int k) {
        // get the size. Mod for least # of rotations
        ListNode* currNode = head;
        int size = 0;

        while(currNode != NULL){
            size++;
            currNode = currNode->next;
        }

        // return NULL if list was empty
        if(size == 0)
            return head;

        k = k % size;

        for(int i=0; i<k; i++){
            
            currNode = head;

            // find the pointer to the last node; stop at 2nd to last, when you're looking at the last node next
            while(currNode->next->next != NULL){
                
                currNode = currNode->next;
            } // Next node is the last node.
            // Reorient pointers to make that node first and
            // to make currNode the new last node

            // point the last node's pointer to the head node
            // This pushes the 1st node to be after the last (2nd)
            currNode->next->next = head;

            // New start of list is the old last node
            head = currNode->next;

            // point the 2nd to last node's next to NULL to create a new last node
            currNode->next = NULL;

        } // do that k times

        return head;
    }
};
```

#### Language used for code
C++

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
