### ISSUE TITLE
Missing Test Case - 1425. Constrained Subsequence Sum

### ISSUE THREAD

**Issue by thilaknv** [LeetCode-Feedback/LeetCode-Feedback#17374]
### My LeetCode username

[thilak_nv](https://leetcode.com/thilak_nv/)

### Category of the bug
- [x] **Missing Test Cases** 
- [ ] Question
- [ ] Solution
- [ ] Language

### Description of the bug

My WRONG Solution is accepted, and beats 100% JAVA users.
But, my code actually gives wrong answer for few custom test cases, if I put only negative numbers in input array.

**Example 1**: 
nums = [-10, -3, -2], k = 2
Correct answer : **-2**
My answer  **-10**

**Example 1**: 
nums = [-3, -1, -10], k = 2
Correct answer : **-1**
My answer  **-3**

### Code I used for Submit/Run operation

```
//  Constrained Subsequence Sum
class Solution {
    private int maxInRange(int[] nums, int l, int r){
        // return index of max in range l to r
        l = Math.max(0, l);
        int max = nums[r], maxI = r;
        // scanning from last
        for(r--; l <= r; r--){
            if(max < nums[r]){
                max = nums[r];
                maxI = r;
            }
        }
        return maxI;
    }
    public int constrainedSubsetSum(int[] nums, int k) {
        int result = nums[0], maxI = 0;
        for(int i = 1; i < nums.length; i++){
            if(i - maxI > k){
                // change max Index when it is out of range
                maxI = maxInRange(nums, i - k, i - 1);
            }
            if(nums[i] < 0){
                nums[i] += Math.max(nums[maxI], 0);
            }else{
                nums[i] += Math.max(nums[maxI], 0);
                maxI = i;
                if(result < nums[i]) result = nums[i];
            }
        }
        return result;
    }
}
```

### Language used for code

JAVA

### Expected behavior

Test cases of above mentioned problem is not sufficient.
My wrong solution is accepted even though it fails for test cases having **unsorted negative numbers**.

So, please include test cases having array with **only unsorted negative numbers**

### Screenshots

<img width="960" alt="leetcode_wrong_solution_accepted" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/122138981/78d234af-801f-4d64-b59e-113be394aaba">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by thilaknv** [comment]
Thanks for replaying. Hope this issue will be corrected

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
