### ISSUE TITLE
Missing Test Case - 879. Profitable Schemes

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#1737]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution is accepted but fails on the following test case:

95
53
[82, 7, 18, 34, 1, 3, 83, 56, 50, 34, 39, 38, 76, 92, 71, 2, 6, 74, 1, 82, 22, 73, 88, 98, 6, 71, 6, 26, 100, 75, 57, 88, 43, 16, 22, 89, 7, 9, 78, 97, 22, 87, 34, 81, 74, 56, 49, 94, 87, 71, 59, 6, 20, 66, 64, 37, 2, 42, 30, 87, 73, 16, 39, 87, 28, 9, 95, 78, 43, 59, 87, 78, 2, 93, 7, 22, 21, 59, 68, 67, 65, 63, 78, 20, 82, 35, 86]
[45, 57, 38, 64, 52, 92, 31, 57, 31, 52, 3, 12, 93, 8, 11, 60, 55, 92, 42, 27, 40, 10, 77, 53, 8, 34, 87, 39, 8, 35, 28, 70, 32, 97, 88, 54, 82, 54, 54, 10, 78, 23, 82, 52, 10, 49, 8, 36, 9, 52, 81, 26, 5, 2, 30, 39, 89, 62, 39, 100, 67, 33, 86, 22, 49, 15, 94, 59, 47, 41, 45, 17, 99, 87, 77, 48, 22, 77, 82, 85, 97, 66, 3, 38, 49, 60, 66]

#### Code you used for Submit/Run operation

```
class Solution {

    int mod = (int) Math.pow(10, 9) + 7;

    public int profitableSchemes(int G, int P, int[] group, int[] profit) {
        int n = group.length;
        int[][][] dp = new int[n + 1][G + 1][1005];
        for (int i = 0; i <= n; i++) {
            for (int j = 0; j <= G; j++) {
                for (int k = 0; k < 1005; k++) {
                    dp[i][j][k] = -1;
                }
            }
        }
        int ans = wayCount(G, P, group, profit, 0, 0, 0, dp);
        return ans;

    }

    public int wayCount(int G, int P, int[] group, int[] profit, int i, int total_Profit, int no_people, int[][][] dp) {
        if (i == group.length) {
            if (total_Profit >= P && no_people <= G) {//mean we found 1 way to do crime
                return 1;
            }
            return 0;
        }
        if (dp[i][no_people][total_Profit] != -1) {
            return dp[i][no_people][total_Profit];
        }
        int q1 = 0, q2 = 0;
        if (no_people + group[i] <= G) {
            q1 = wayCount(G, P, group, profit, i + 1, total_Profit + profit[i], group[i] + no_people, dp);
        }
        q2 = wayCount(G, P, group, profit, i + 1, total_Profit, no_people, dp);
        return dp[i][no_people][total_Profit] = (q1 % mod + q2 % mod) % mod;


    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/102945593-30d04d80-448c-11eb-9435-94538271ed5f.png)

#### Additional context

Link to the original solution: https://leetcode.com/problems/profitable-schemes/discuss/702473/3-state-dp-oror-recursion-%2B-memoization

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
