### ISSUE TITLE
Missing Test Case - 1367. Linked List in Binary Tree

### ISSUE THREAD

**Issue by DanyloGitylo** [LeetCode-Feedback/LeetCode-Feedback#1738]
#### Your LeetCode username

DanyloCodylo

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

I think test case #60 should be preceded by a smaller one. It'll make finding the root of the problem easier.

#### Code you used for Submit/Run operation

```
public class Solution {  
  public bool IsSubPath(ListNode head, TreeNode root) {
	return IsSubPathCore(head, root, head);
  }

  private bool IsSubPathCore(ListNode head, TreeNode root, ListNode currentListNode) {
    if (currentListNode == null)
    {
      return true;
    }
    
    if (root == null)
    {
      return false;
    }
    
    if (currentListNode.val == root.val)
    {
      return 
        IsSubPathCore(head, root.left, currentListNode.next) || 
        IsSubPathCore(head, root.right, currentListNode.next);
    }
    
    if (head.val == root.val)
    {
      return 
        IsSubPathCore(head, root.left, head.next) || 
        IsSubPathCore(head, root.right, head.next);
    }
    
    return 
      IsSubPathCore(head, root.left, head) || 
      IsSubPathCore(head, root.right, head);
  }
}
```

#### Language used for code

C#

#### Expected behavior

I'd suggest using this test case before #60:
[2,2,1]
[2,null,2,null,2,null,1]

What actually happened - test case #60 which caught the problem in my code is too big and difficult to analyze.
The proposed test case will show the problem of searching from the last matched node (as in my code), instead of searching from, say, each node.
It'll be easier to understand the problem on the smaller size test case, rather than such in #60.
I hope this makes sense.
Thank you.

**Comment by lc-kay** [comment]
Hi @DanyloGitylo 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @DanyloGitylo 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
