### ISSUE TITLE
1109. Corporate Flight Bookings - Incorrect Question

### ISSUE THREAD

**Issue by agrawalishaan** [LeetCode-Feedback/LeetCode-Feedback#17381]
#### Your LeetCode username
agrawalishaan

#### Category of the bug
- [X ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the question, it writes: `Return an array answer of length n, where answer[i] is the total number of seats reserved for flight i.`

It should say:
`total number of seats reserved for flight i-1`.

The original problem description doesn't index this correctly.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
