### ISSUE TITLE
Missing Test Case - 2890. Reshape Data: Melt

### ISSUE THREAD

**Issue by xiaoqiu23333** [LeetCode-Feedback/LeetCode-Feedback#17391]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by nurmukhammaddev** [comment]
return pd.melt(report, id_vars=['product'], var_name='quarter', value_name='sales')
