### ISSUE TITLE
Missing Test Case -  1235. Maximum Profit in Job Scheduling

### ISSUE THREAD

**Issue by liuchengtian** [LeetCode-Feedback/LeetCode-Feedback#17392]
#### Your LeetCode username

alastian

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Missing a testcase that should fail the below program that runs on O(n^2). Right solution is O(nlogn).

#### Code you used for Submit/Run operation

```java
class Solution {
    public int jobScheduling(int[] startTime, int[] endTime, int[] profit) {
        int n = startTime.length;
        int[][] jobs = new int[n][3];
        for(int i = 0; i < n; i++){
            jobs[i][0] = startTime[i];
            jobs[i][1] = endTime[i];
            jobs[i][2] = profit[i];
        }
        Arrays.sort(jobs, (a, b) -> (a[1] - b[1]));
    
        int[] dp = new int[n];
        dp[0] = jobs[0][2];
        for(int i = 1; i < n; i++){
            dp[i] = jobs[i][2];
            for(int j = i - 1; j >=0; j--){
                if(jobs[j][1] <= jobs[i][0]){
                    dp[i] = Math.max(dp[i], dp[j] + jobs[i][2]);
                    break;
                }else{
                    dp[i] = Math.max(dp[i], dp[j]);
                }
            }
        }
        return dp[n-1];
    }
}
```

#### Language used for code

Java

#### Expected behavior

TLE

#### Screenshots

test_result

![test_result](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/20579757/7e73b0eb-009d-49e5-a2b0-e8c50cb5d145) 

submission

![submission](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/20579757/9dfcf121-d8fb-4c44-afb1-492db8e4f9fe)

#### Additional context

[testcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/13066756/testcase.txt)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
