### ISSUE TITLE
Missing Test Case - 704. Binary Search

### ISSUE THREAD

**Issue by shakilmallik** [LeetCode-Feedback/LeetCode-Feedback#17394]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

-Missing Test Case

First of all here I use mid = (start+end)/2
then I run and all  test cases passed. but here is a problem that if we sum start and end of its maximum vlaue than it can not store in int variable. So if we write   mid = start + (end-start)/2 then it pass all test case easily.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    int search(vector<int>& arr, int key) {
        
        int n=arr.size();
        int start=0, end=n-1, mid;

    while(start<=end){
        mid=(start+end)/2;
        if(arr[mid]==key)
        return mid;

        else if(arr[mid]<key)
        start=mid+1;
        else
        end=mid-1;
    }
    return -1;
    }
};
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
