### ISSUE TITLE
Missing Test Case - 556. Next Greater Element III

### ISSUE THREAD

**Issue by tonghuikang** [LeetCode-Feedback/LeetCode-Feedback#1740]
#### Your LeetCode username
tonghuikang

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Missing Test Case

```
2147483486
```

The question states

> Note that the returned integer should fit in 32-bit integer, if there is a valid answer but it does not fit in 32-bit integer, return `-1`.

The number `2**31` does not fit in a (signed) 32-bit integer, and -1 should be returned.

#### Code you used for Submit/Run operation

```
class Solution:
    def nextGreaterElement(self, n: int) -> int:
        if "".join(sorted(str(n))[::-1]) == str(n):
            return -1
        
        a = [x for x in str(n)]
        length = len(a)
        
        for k in range(length-2,-1,-1):
            if a[k] < a[k+1]:
                break
        
        for l in range(length-1, k, -1):
            if a[k] < a[l]:
                break
        
        a[k], a[l] = a[l], a[k]
        a[k+1:] = a[k+1:][::-1]
        
        res = int("".join(a))
        
        if res > 2**31:  # should be a non-strict inequality
            return -1
        return res
```

#### Language used for code
Python 3

#### Expected behavior
The above code should return wrong answer with the new test case `2147483486`

#### Screenshots
<img width="1429" alt="Screenshot 2020-12-23 at 10 58 37 PM" src="https://user-images.githubusercontent.com/17105577/103009896-694a5700-4572-11eb-980c-a2de20b5f1e7.png">

#### Additional context
You may want to specify that the 32-bit integer refers to a signed 32-bit integer.

**Comment by lc-kay** [comment]
Hi @tonghuikang 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @tonghuikang 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
