### ISSUE TITLE
Missing Test Case - 1191. K-Concatenation Maximum Sum

### ISSUE THREAD

**Issue by SahilSingh177** [LeetCode-Feedback/LeetCode-Feedback#17409]
#### Your LeetCode username
darklord177a

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The problem is missing a test case in which if any subarray sum is more than the total array sum and the value of k is 1, then the answer should be the subarray sum. 

For example,

If the array is `[1, -1, 6]` and k = `1`, the answer should be `6`. Although the given code is giving the output as `0`, it is still getting accepted.

#### Code you used for Submit/Run operation

```cpp
class Solution {
public:
    int kConcatenationMaxSum(vector<int>& arr, int k) {
        long long n = arr.size();
        long long mod = 1e9+7;
        long long global_sum = 0;
        bool all_neg_array = true, all_pos_array = true;
        for(int i=0; i<n; i++){
            if(arr[i] >= 0) all_neg_array = false;
            else all_pos_array = false;
            global_sum = (arr[i]+global_sum)%mod;
        }
        if(all_pos_array) return int((global_sum*(long long)k)%mod);
        else if(all_neg_array) return 0;

        int max_subarray_sum = INT_MIN;
        int local_max = 0;

        for(int i=0; i<min(2,k)*n; i++){
            local_max += arr[i%n];
            if(local_max < 0) local_max = 0;
            max_subarray_sum = max(max_subarray_sum, local_max);
        }
        
        if(global_sum>0){
            return ((global_sum)*(k-2) + max_subarray_sum) % mod;
        }
        else{
            return max_subarray_sum % mod;
        }
    }
};
```

#### Language used for code
 C++

#### Expected behavior

The above code should not pass all the test cases as it's missing the logic where (k=1) and the subarray sum is greater than the overall sum of the array.

#### Screenshots

![Screenshot 2023-10-24 035210](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/96344003/02a47295-d65c-4475-a1c2-983bca530a2e)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
