### ISSUE TITLE
Missing Test Case - 1793. Maximum Score of a Good Subarray

### ISSUE THREAD

**Issue by Chirag237** [LeetCode-Feedback/LeetCode-Feedback#17401]
#### Your LeetCode username
Chirag37

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
test case is missing for the condition in which answer includes last or first element

Example Test Case:
nums :  [7,5,4]
k :1
Output: 10
Expected: 12

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int maximumScore(vector<int>& nums, int k) {
        int n=nums.size();
        if(n==1)return nums[0];
        int l=k-1,r=k+1,ans=INT_MIN,mn=nums[k];
        while(l>=0 || r<n){
            while(l>=0 && nums[l]>=mn)l--;
            while(r<n && nums[r]>=mn)r++;
            ans=max(ans,mn*(r-l-1));
            if(l<0 && r>=n)return ans;
            if(l<0 || nums[l]<=nums[r]){
                mn=nums[r];
                r++;
            }
            else if(r>=n || nums[l]>nums[r]){
                mn=nums[l];
                l--;
            }

        }
        return ans;
    }
};
```

#### Language used for code
C++

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103517587/73a6f866-a06d-4db5-b529-bf6e9101b829)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
