### ISSUE TITLE
Missing Test Case - 342. Power of Four

### ISSUE THREAD

**Issue by SolomonOdunusi** [LeetCode-Feedback/LeetCode-Feedback#17408]
#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
Write working on Power of Four leetcode question, i found out there is a need to test negative integers and the need to add a testcase for negative numbers like -2, -4 and other integers less than 0.

#### Code you used for Submit/Run operation
```
class Solution:
    def isPowerOfFour(self, n: int) -> bool:
        """Given an int n, return true if power of four,
        else return false.

        Args: n -> integer
        Return: returns a boolean value.
        """

        if n <= 0: # Checks if integer is 0 or negative number and returns False
            return (False)

        if n == 1: # Checks if integer is 1 and returns True
            return (True)

        if (n % 4) != 0: # Checks if the integer is divisible by 4 and returns False
            return (False)

        # Runs a recursive function by checking if n is divisible by 4 and returns the result
        return (self.isPowerOfFour(n /4))

# Testcase for negative number
def test_isPowOfFour_negative():
    s = Solution()
    assert s.isPowOfFour(-16) == False
```

#### Language used for code
- Python

#### Expected behavior
Return False when checking for negative integer

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
