### ISSUE TITLE
Incorrect answer for Test Case - 78. Subsets

### ISSUE THREAD

**Issue by jinxac** [LeetCode-Feedback/LeetCode-Feedback#1741]
#### Your LeetCode username

abhyasa

#### Category of the bug
- [ ] Solution

#### Description of the bug

The question mentions that duplicate subsets should not be there but even if it is the code passes.

#### Code you used for Submit/Run operation

```
class Solution:
    def subsets(self, nums: List[int]) -> List[List[int]]:
        result = []
        result.append([])
        
        for element in nums:
            len_result = len(result)
            
            for i in range(len(result)):
                temp = result[i][:]
                temp.append(element)
                result.append(temp)
        
        return result
            
```

#### Expected behavior

Code run should fail for input [1,3,3]

#### Screenshots

![image](https://user-images.githubusercontent.com/15068096/103010387-47df7000-455e-11eb-846d-657669d4eb22.png)

**Comment by lc-kay** [comment]
Hi @jinxac 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @jinxac 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
