### ISSUE TITLE
Missing Test Case - 128. Longest Consecutive Sequence

### ISSUE THREAD

**Issue by khai-pi** [LeetCode-Feedback/LeetCode-Feedback#17415]
#### Your LeetCode username

user8913Kd

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Missing test case that make false implement accepted

#### Code you used for Submit/Run operation

```
class Solution {
    public int longestConsecutive(int[] nums) {
        if (nums.length==0) return 0;
        LinkedList<Integer> list = new LinkedList<>();
        int res = 1;
        list.add(nums[0]);
        Set<Integer> set = Arrays.stream(nums).boxed().collect(Collectors.toSet());
        for (int i = 1 ; i < nums.length; i++) {
            if (set.contains(list.getFirst()-1)) {
                list.addFirst(list.getFirst()-1);
                res = Math.max(res, list.size());
                continue;
            }
            if (set.contains(list.getLast()+1)) {
                list.addLast(list.getLast()+1);
                res = Math.max(res, list.size());
                continue;
            }
            res = Math.max(res, list.size());
            list = new LinkedList<>();
            list.add(nums[i]);
        }
        return res;
    }
}
```

#### Language used for code

 Java

#### Expected behavior

test case [101,102,103,1,2,3,104,105,106,4,5,6,7] with my code return false, but this test case is not in test cases pool-

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/83369230/aec7624b-902e-4a48-8399-baf9bd4d3f21)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
