### ISSUE TITLE
Explore card track videos have no audio

### ISSUE THREAD

**Issue by towfiq-rahman** [LeetCode-Feedback/LeetCode-Feedback#17412]
#### Category of the bug
- [ ] Explore Card Videos
- [ ] Audio

#### Description of the bug

The videos in the graph section of the explore card track doesnt have any audio. Without audio it is difficult to understand what is going on in the video

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've submitted your feedback to the team. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
