### ISSUE TITLE
Missing Test Case - 872. Leaf-Similar Trees

### ISSUE THREAD

**Issue by yusuf-74** [LeetCode-Feedback/LeetCode-Feedback#17426]
#### Your LeetCode username

yusuf_74

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

my buggy solution was accepted and i found a test case that will catch it

#### Code you used for Submit/Run operation

```python
# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
class Solution:
    def leafSimilar(self, root1: Optional[TreeNode], root2: Optional[TreeNode]) -> bool:

        def getLeaves(root,ans = []):
            if root and not (root.left or root.right):
                ans.append(root.val)
            elif root:
                getLeaves(root.left)
                getLeaves(root.right)
            return ans
        first = getLeaves(root1)
        second = getLeaves(root2)
        return first[:int(len(first)/2)] == first[int(len(first)/2):] 
            


};
```

#### Language used for code

Python

#### Expected behavior

the solution should fail in the following test case but this test case does not exist
input :
root1 =
[1,2,3,4,5,6,7,8,9,10,11,12,13,8,9]
root2 =
[1,2,3,10,11,12,13]
output:
False

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
