### ISSUE TITLE
Missing Test Case - 88. Merge Sorted Array

### ISSUE THREAD

**Issue by vinayb21** [LeetCode-Feedback/LeetCode-Feedback#1742]
#### Your LeetCode username
vinayb21

#### Category of the bug
- [ ] Question

#### Description of the bug
There is no mention of the range of the values for m and n

**Comment by lc-kay** [comment]
Hi @vinayb21 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @vinayb21
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
