### ISSUE TITLE
Missing Test Case - 515. Find Largest Value in Each Tree Row

### ISSUE THREAD

**Issue by csgeeek** [LeetCode-Feedback/LeetCode-Feedback#17429]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I encountered a discrepancy in this problem where a solution, despite violating the problem's stated constraints, was accepted. Specifically, the solution passed when I used `INT_MIN` (-2147483648), which represents the lower limit of a 32-bit integer. However, the problem constraints clearly specify that node values should adhere to the range -2^31 <= Node.val <= 2^31 - 1. This situation suggests a discrepancy between the problem's constraints and the validation of submitted solutions, as `INT_MIN` is outside the specified range.
I copied the solution from the Editorial of this problem.

#### Code you used for Submit/Run operation

```c++
// 515. Find Largest Value in Each Tree Row
class Solution {
public:
    vector<int> largestValues(TreeNode* root) {
        if (root == nullptr) {
            return vector<int>{};
        }
        
        vector<int> ans;
        queue<TreeNode*> queue;
        queue.push(root);
        
        while (!queue.empty()) {
            int currentLength = queue.size();
            int currMax = INT_MIN;   // <--- The issue is here
            
            for (int i = 0; i < currentLength; i++) {
                TreeNode* node = queue.front();
                queue.pop();
                currMax = max(currMax, node->val);
                
                if (node->left) {
                    queue.push(node->left);
                }
                
                if (node->right) {
                    queue.push(node->right);
                }
            }
            
            ans.push_back(currMax);
        }
        
        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior

The solution should not get accepted when I use `INT_MIN` or any number < -2^31.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
