### ISSUE TITLE
Missing Test Case - 658. Find K Closest Elements

### ISSUE THREAD

**Issue by Gurujeet-Singh** [LeetCode-Feedback/LeetCode-Feedback#17420]
#### Your LeetCode username

gurujeet7

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 
Missing Test Cases

#### Description of the bug

My code runs on each and every test case given by leetcode platform but fails on test case which is made by me.
My test case: [0,2,2,3,4,20,20,20,20,20]
                      k=1
                      x=5
output should be [4] but my code gives [20] , still complier accepts my solution as correct.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int findIndex(vector<int>& arr,int target){
        int start=0,end=arr.size()-1;
        int mid;
        while(start<=end){
            mid=(start+end)/2;
            if(target==arr[mid]){
                return mid;
            }
            else if(target<arr[mid]){
                end=mid-1;
            }
            else{
                start=mid+1;
            }
        }   
       
        if(arr.size()==2){
            return mid-1;
        }
        return mid;
    }
    vector<int> findClosestElements(vector<int>& arr, int k, int x) {
        vector<int> ans;
        int index=findIndex(arr,x);
        cout<<index<<" "<<arr[index];
        int p1=index,p2=index+1;
        int value=k;
        while(p1>-1 && p2<arr.size() && value>0){
                if(abs(arr[p1]-x)<abs(arr[p2]-x)){
                    p1--;
                    if(p1>-1 && arr[p1]!=arr[p1+1] && value==1 && abs(arr[p1]-x)==abs(arr[p1+1]-x)){
                        p1--;
                    }
                }
                else if(abs(arr[p1]-x)==abs(arr[p2]-x)){
                    p1--;
                }
                else{
                    p2++;
                }
                value--;
        }
        if(value==0){
            for(int i=p1+1;k--;i++){
                ans.push_back(arr[i]);
            }
        }
        else if(p1<0){
            for(int i=0;k--;i++){
                ans.push_back(arr[i]);
            }
        }
        else{
            for(int i=arr.size()-k;k--;i++){
                ans.push_back(arr[i]);
            }
        }
        return ans;
    }
};

```

#### Language used for code

C++

#### Expected behavior

My code should have not accepted as correct but it is acceted as correct.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
