### ISSUE TITLE
Spelling error in 779. K-th Symbol in Grammar

### ISSUE THREAD

**Issue by YogeshP93** [LeetCode-Feedback/LeetCode-Feedback#17438]
#### Your LeetCode username

https://leetcode.com/Baymax_/

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Spelling/Grammatical error in - [779. K-th Symbol in Grammar](https://leetcode.com/problems/k-th-symbol-in-grammar/)
In the "Editorial" section under "Approach 2: Normal Recursion", in the explanation we can see a statement:
`Therefore, 5st symbol of 5th row...`

#### Expected behavior

It should be:
`Therefore, 5th symbol of 5th row...`

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/122779284/72644e19-c7cb-4171-9c9e-69535eabb869)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
