### ISSUE TITLE
Incorrect Editorial for 1143 - LongestCommonSubsequence

### ISSUE THREAD

**Issue by mts310** [LeetCode-Feedback/LeetCode-Feedback#17439]
#### Your LeetCode username
emptyscales 

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The editorial solution using DP, without space optimisation, seems to fail on JUGGU vs JUGGGU. It returns 5. Perhaps a variable that tracks the longest current diagonal match needs to be used.

#### Expected behavior
Return 4

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

This problem requires lowercase letters as the input
Input ‘juggu' and 'jugggu’ should result in 5 as the correct answer
There is no problem with the original solution

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
