### ISSUE TITLE
Go : Unknown preprocess compile error

### ISSUE THREAD

**Issue by wangzhione** [LeetCode-Feedback/LeetCode-Feedback#17443]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名
叶林丫
https://leetcode.cn/u/xie-lin-ya/

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [x] 编程语言
- [ ] 缺少测试用例

**描述**
描述你遇到的 bug
https://leetcode.cn/problems/two-sum/submissions/?envType=study-plan-v2&envId=top-100-liked

一样的代码有的编译通过, 有的编译出错. 

**你使用的语言**
Go

**你提交或者运行的代码**
```
func twoSum(nums []int, target int) []int {
    // array value -> array index
    valueIndexMap := make(map[int]int, len(nums))

    for i, num := range nums {
        valueIndexMap[num] = i
    }

    for leftIndex, left := range nums {
        rightIndex := valueIndexMap[target - left]
        if rightIndex != leftIndex {
            return []int{leftIndex, rightIndex};
        }
    }

    return []int{}
}
```

**期望行为**
描述你期望的结果
编译通过

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/9955901/528cabb0-8406-4133-a9d5-f370fb3e9179)

**额外的上下文**
添加额外的上下文信息

**Comment by Neon-Rainbow** [comment]
+1，同样的go代码，有时编译通过，有时编译不通过，测试样例能跑出结果，一提交就显示unknown preprocess compile error
