### ISSUE TITLE
Missing Test Case - 556. Next Greater Element III

### ISSUE THREAD

**Issue by filbranden** [LeetCode-Feedback/LeetCode-Feedback#1744]
#### Your LeetCode username

filbranden

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Missing test case for corner case

```
2147483476
```

#### Code you used for Submit/Run operation

```python
// Two Sum
class Solution:
    def nextGreaterElement(self, n: int) -> int:
        digits = [int(i) for i in str(n)]
        # Iterate through possible positions where a digit
        # could be replaced by a larger one.
        for pos in range(len(digits)-2, -1, -1):
            # Find larger digits in the remaining part.
            candidates = [i for i in digits[pos+1:] if i > digits[pos]]
            if candidates:
                break
        else:
            # We didn't find a digit that could be replaced
            # by a larger one. So let's just return -1.
            return -1
        
        # The replacement digit will be the smallest
        # among all the candidates.
        replacement = min(candidates)
        
        # Drop the replacement and sort the remaining
        # digits in order, to get the smallest number.
        remaining = digits[pos:]
        remaining.remove(replacement)
        remaining.sort()
        digits[pos:] = [replacement] + remaining
        
        # Convert it back to a number.
        result = int(''.join(str(i) for i in digits))
        
        # Check that it fits into 32-bits. Uh oh, looks
        # like we have a off-by-one bug here.
        #
        # This one also fails to catch one of the corner cases.
        # if result > 1 << 31:
        if result >= 1 << 31 - 1:
            return -1
        
        return result
```

#### Language used for code

Python

#### Expected behavior

Using "Run" correctly shows me:
 - Your answer: -1
 - Expected answer: 2147483647

But submitting it still gets accepted.

There's also a corner case for input `2147483486` but I see this has already been reported in #1740.

#### Screenshots

N/A

#### Additional context

As mentioned on #1740, you may want to specify that the 32-bit integer refers to a signed 32-bit integer and perhaps specify the limit more precisely as `result < 2^31`.

**Comment by lc-kay** [comment]
Hi @filbranden 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @filbranden 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
