### ISSUE TITLE
Missing Test Case - 437. Path Sum III

### ISSUE THREAD

**Issue by amitkec123** [LeetCode-Feedback/LeetCode-Feedback#1745]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Prefix sum is not the right solution for this question, specially sum is calculated from parent to child.
                              1
                         5        3
Ideal sums should be : 1, 6 or 4.
but the for **9**        also this is passed.  

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@amitkec123 Can you please provide more information as to why you think prefix sum is incorrect? Then, we can better understand the issue. Thank you!

**Comment by amitkec123** [comment]
Closing the issue as the reported bug is no more present.
