### ISSUE TITLE
704. Errors in Editorial

### ISSUE THREAD

**Issue by govindrai** [LeetCode-Feedback/LeetCode-Feedback#17464]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In **_Approach 2_**, there are errors in images:

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/13859249/5dd8e326-2052-419f-9cf9-46ad1eeae315)
The box in the bottom right should state `nums[mid] > target`

This mistake is again repeated in a following photo
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/13859249/ecd45529-bab2-498e-b097-597a1ecdcb13)

---
In **_Approach 3_**, there are errors in explanation:
> If nums[mid] < target, mid can also be the insertion position. So we let left = mid, that is, discard the right half while keeping mid.

This should instead state:
If nums[mid] < target, mid can also be the insertion position. So we let left = mid, that is, discard the _left_ half while keeping mid.

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/13859249/dabb5a21-1d01-4d5f-ae3c-0d6bf72a4f79)
This image should state: `right = mid` and  `left = mid + 1`

#### Expected behavior
I expect the solution to be correctly explained

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
