### ISSUE TITLE
371. Sum of Two Integers - Solution Article - not x

### ISSUE THREAD

**Issue by yang203000** [LeetCode-Feedback/LeetCode-Feedback#1747]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
In the middle of solution article, it says `x = 15 = 00001111` and `~x = -16 = 00010000`,

is ~x should be `11110000`?

screenshot: https://i.imgur.com/2bksZOg.png

#### Code you used for Submit/Run operation

```
code:
int a = 0xF;
int b = ~a;
Console.WriteLine(b.ToString());
Console.WriteLine(Convert.ToString(b, toBase: 2));
int a1 = 0x0000F;
int b1 = ~a1;
Console.WriteLine(b1.ToString());
Console.WriteLine(Convert.ToString(b1, toBase: 2));

output:
-16
11111111111111111111111111110000
-16
11111111111111111111111111110000
```

#### Language used for code

C#

**Comment by lc-kay** [comment]
@yang203000 Can you please provide more information as to why you think it's incorrect? Thank you!

**Comment by yang203000** [comment]
ok, I explain my thought,  the [wiki](https://en.wikipedia.org/wiki/Bitwise_operation#NOT) says NOT is `Bits that are 0 become 1, and those that are 1 become 0.` , although the example it gives are:
```
NOT 0111  (decimal 7)
  = 1000  (decimal 8)
NOT 10101011  (decimal 171)
  = 01010100  (decimal 84)   
```

but in real program, all number has a TYPE, maybe `long / int / short / byte`, and has a length, e.g. `byte` is 8 bit

I run some example here:

```
Console.WriteLine("int");
int a = 0xF;
int b = ~a;
Console.WriteLine(b.ToString());
Console.WriteLine(Convert.ToString(b, toBase: 2));

Console.WriteLine("ushort");
ushort a2 = 0xF;
ushort b2 = (ushort)~a2;
Console.WriteLine(b2.ToString());
Console.WriteLine(Convert.ToString(b2, toBase: 2));

Console.WriteLine("short");
short a21 = 0xF;
short b21 = (short)~a2;
Console.WriteLine(b21.ToString());
Console.WriteLine(Convert.ToString(b21, toBase: 2));

Console.WriteLine("byte");
byte a3 = 0xF;
byte b3 = (byte)~a3;
Console.WriteLine(b3.ToString());
Console.WriteLine(Convert.ToString(b3, toBase: 2));
```

and the output is show as below, we can see that to discuss the binary format of NOT, we need to first give a TYPE, and base on it to discuss. For example the NOT value of 0xF,  for `short` is 16 bit  length `1111111111110000`, for byte is 8 bit length `11110000`,  so if going by above, the image (https://i.imgur.com/2bksZOg.png) value of `~x: 10000`is correct if the number type is `5 bit length`, but if the number type is `byte: 8 bit length`, then the value should be `11110000`, 

and the image would let reader directly think the type using now is 8-bit, because the image show 8 bit,

so I suggest it can be modify to `11110000`, or cut the bit length in the img down to 5-bit.

I think it's the same in wiki example, it is say `NOT 10101011 = 01010100`, but it didn't say   `NOT 0000010101011 = 0000001010100` which has more 0 at start.

the output:

```
int
-16
11111111111111111111111111110000
ushort
65520
1111111111110000
short
-16
1111111111110000
byte
240
11110000
```

**Comment by lc-kay** [comment]
Hi @yang203000 
Thank you for the additional information. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@yang203000 Thank you for your time. We have noted this report and will make the necessary changes in the near future.
