### ISSUE TITLE
Description - 412. Fizz Buzz

### ISSUE THREAD

**Issue by RonnyKoch** [LeetCode-Feedback/LeetCode-Feedback#17488]
#### Your LeetCode username
RonnyKoch

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The description of problem 412 never mentions that the length of `answer` should be `n`.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
