### ISSUE TITLE
Incorrect Test Case - 589  N-ary Tree Preorder Traversal

### ISSUE THREAD

**Issue by a5hut05h** [LeetCode-Feedback/LeetCode-Feedback#17487]
ashutoshdas540

Category of the bug
- [ ] Question

Incorrect Test Case

[1, null]

C++ 

Additional space before null should be removed

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
