### ISSUE TITLE
801. Minimum Swaps To Make Sequences Increasing - Test case 61 expected output is wrong

### ISSUE THREAD

**Issue by ChineduOkoronkwo** [LeetCode-Feedback/LeetCode-Feedback#1748]
#### Your LeetCode username

AlfredChinedu

#### Category of the bug
- [x] Solution
- [x] Test Case

#### Description of the bug

Test case 61's expected output is 4, whereas if we manually inspect the inputs, we will see that the output should be 3 and not 4.
The input is:
[0,7,8,10,10,11,12,13,19,18]
[4,4,5,7,11,14,15,16,17,20]

We can make A & B sorted in non-decreasing order by swapping elements at indices 1,2 and 3 for a total of 3 swaps and the resulting arrays will be.
[0,4,5,7,10,11,12,13,19,18]
[4,7,8,10,11,14,15,16,17,20]

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by zerotrac** [comment]
Will you call `[19,18]` non-decreasing?

**Comment by ChineduOkoronkwo** [comment]
Thanks, my oversight.
