### ISSUE TITLE
179: Largest Number - Error in one of Test Cases - Expected Output, and Example

### ISSUE THREAD

**Issue by D-Stukes** [LeetCode-Feedback/LeetCode-Feedback#17490]
#### Your LeetCode username
ladyd7778 

#### Category of the bug
- [ ] Solution  (incorrect expected output for one of the test cases)

#### Description of the bug
I produced the largest number, given the input as the instructions said. But the expected output of one of the testcases was a smaller number, and would not accept my answer. The smaller number, I believe is incorrect.

[LeetCode-Feedback](https://github.com/LeetCode-Feedback/LeetCode-Feedback)
Public

#### Code you used for Submit/Run operation

```
var largestNumber = function(nums) {
nums = nums.join('').toString().split('').sort((a,b)=>b-a).join('')
return nums
};
```

#### Language used for code
Javascript

#### Expected behavior
Output should be largest number.

#### Screenshots

<img width="1440" alt="Screen Shot 2023-10-26 at 6 33 41 AM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/36650186/d69e96a1-8175-4371-97fe-0629b4cf59e2">

#### Additional context

Input:  [3,30,34,5,9]
My Output = **954**3330
Expected   =  **953**4330
My result of 954+  is larger than the "expected" result of 953+

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
