### ISSUE TITLE
Missing Test Case - 24. Swap Nodes in Pairs

### ISSUE THREAD

**Issue by Hilb3r7** [LeetCode-Feedback/LeetCode-Feedback#1751]
#### Your LeetCode username

DavidHilbert

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language

#### Description of the bug

The problem statement states that "You may not modify the values in the list's nodes. Only nodes itself may be changed." However code submitted that changes the node values is accepted as correct.

#### Code you used for Submit/Run operation

```
public class Solution {
    public ListNode SwapPairs(ListNode head) {
         ListNode root = head;
            if(root==null)
                return null;
          
            while(root!=null)
            {
                if (root.next == null)
                    return head;
                swapPairList(root);
                root = root.next.next;
            }
            return head; 
        
    }
      public  void swapPairList(ListNode swapp)
        {
          if(swapp.next!=null)
          {
            var temp = swapp.val;
            swapp.val = swapp.next.val;
            swapp.next.val = temp;
          }

        }
}
```

#### Language used for code

C#

#### Expected behavior

What I expected to happen is that it should fail the test cases as it violates the parameters of the problem. What actually happened is it is accepted.

**Comment by lc-kay** [comment]
Hi @Hilb3r7 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by lc-kay** [comment]
@Hilb3r7 This is a follow-up question and it is not tested in the driver code. We have added that to the follow-up section to be clear. Thank you for your time and support!
