### ISSUE TITLE
Missing Test Case - 823. Binary Trees With Factors

### ISSUE THREAD

**Issue by SaiSandeepRaguru** [LeetCode-Feedback/LeetCode-Feedback#17511]
#### Your LeetCode username
Sai_Shetty

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Adding New Testcase

#### Code you used for Submit/Run operation
```
class Solution {
public:
    const int MOD = 1000000007;

    int numFactoredBinaryTrees(vector<int>& arr) {
        sort(arr.begin(), arr.end());
        int n = arr.size();
        unordered_map<int, long long> dp;

        long long ans = 0;

        for (int i = 0; i < n; i++) {
            dp[arr[i]] = 1;  // Initialize with a single node tree
            for (int j = 0; j < i; j++) {
                if (arr[i] % arr[j] == 0) {
                    int quotient = arr[i] / arr[j];
                    if (dp.find(quotient) != dp.end()) {
                        dp[arr[i]] = (dp[arr[i]] + dp[arr[j]] * dp[quotient]) % MOD;
                    }
                }
            }
            ans = (ans + dp[arr[i]]) % MOD;
        }

        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior

TestCase: [2,3,4,6,107,126,252,13]
Expected Output: 13

#### Screenshots
<img width="841" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/62465620/152eab84-4a92-49f6-90e8-1f732b29162a">

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

[2,3,4,6,107,126,252,13] already exists. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
