### ISSUE TITLE
Wrong Solution

### ISSUE THREAD

**Issue by rdou17** [LeetCode-Feedback/LeetCode-Feedback#17536]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The solution for Question 5, Approach 1, Python version, line 8 is wrong. We should have if s[left] != s[right - 1] instead of if s[left] != s[right], or it will raise index error. Please fix.

#### Code you used for Submit/Run operation

```
class Solution:
    def longestPalindrome(self, s: str) -> str:
        def check(i, j):
            left = i
            right = j - 1
            
            while left < right:
                if s[left] != s[right]:
                    return False
                
                left += 1
                right -= 1
            
            return True
        
        for length in range(len(s), 0, -1):
            for start in range(len(s) - length + 1):
                if check(start, start + length):
                    return s[start:start + length]

        return ""
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

There is no error using s[left] != s[right]

The original editorial is correct.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
