### ISSUE TITLE
Missing Test Case - 162. Find Peak Element

### ISSUE THREAD

**Issue by Somnath-sanu** [LeetCode-Feedback/LeetCode-Feedback#17549]
#### Your LeetCode username
sanu_11

#### Category of the bug
- [ ] Question
- [✅ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
It Accepted my code but i have found a test case where my code fails....

#### Code you used for Submit/Run operation

```
// [Find Peak Element](https://leetcode.com/problems/find-peak-element/)
class Solution {
    public int findPeakElement(int[] arr) {
       int low = 0;
        int high = arr.length - 1;

        while (low < high) {
            int mid = low + (high - low) / 2;

            if (arr[mid] > arr[mid + 1]) {
                high = mid; // Potential peak is on the left side
            } else {
                low = mid + 1; // Potential peak is on the right side
            }
        }

        return low;
    }
}
```

#### Language used for code
java 

#### Expected behaviour

Input : [1,12,1,9,10]
expected output : 1
 Because 12 is the peak element and its index is 1.
output received : 4

#### Screenshots

Here is the screenshot of the code 👍 
https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/122222948/910c0613-8061-4198-a87e-210125b0076a

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Please ask your question in the discussion. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
