### ISSUE TITLE
Missing Test Case - 732. My Calendar III

### ISSUE THREAD

**Issue by tejasvi** [LeetCode-Feedback/LeetCode-Feedback#1755]
#### Your LeetCode username

`tstomar`

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Missing test case.

#### Code used for Submit/Run operation

```
class MyCalendarThree(object):

    def __init__(self):
        self.seg = collections.defaultdict(int)
        self.lazy = collections.defaultdict(int)
        
    def book(self, start, end):
        def update(s, e, l = 0, r = 10**9, ID = 1):
            if r <= s or e <= l: return 
            if s <= l < r <= e:
                self.seg[ID] += 1
                self.lazy[ID] += 1
            else:
                m = (l + r) // 2
                update(s, e, l, m, 2 * ID)
                update(s, e, m, r, 2*ID+1)
                self.seg[ID] = self.lazy[ID] + max(self.seg[2*ID], self.seg[2*ID+1])
        update(start, end)
        return self.seg[1] + self.lazy[1]
```

#### Language used for code

Python3

#### Expected behavior

The accepted solution above fails for the following edge case input.
```
["MyCalendarThree","book"]
[[],[0,1000000000]]
```

**Comment by lc-kay** [comment]
Hi @tejasvi 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @tejasvi 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
