### ISSUE TITLE
Missing Test Case - 10. Regular Expression Matching

### ISSUE THREAD

**Issue by akinom** [LeetCode-Feedback/LeetCode-Feedback#17563]
#### Your LeetCode username
mo-meven

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x ] Missing Test Cases 

#### Description of the bug
not testing when patrtern expects more than the string provides

#### Code you used for Submit/Run operation
pattern   a*b
string      aaaaa

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

More details about the issue. 
The code submission link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
