### ISSUE TITLE
Typo in Question De

### ISSUE THREAD

**Issue by shurui91** [LeetCode-Feedback/LeetCode-Feedback#1757]
#### Your LeetCode username
shurui

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Question 1605. Find Valid Matrix Given Row and Column Sums

Example 1:
Input: rowSum = [3,8], colSum = [4,7]
Output: [[3,0],
         [1,7]]
Explanation:
**0th row: 3 + 0 = 0 == rowSum[0]**
1st row: 1 + 7 = 8 == rowSum[1]
0th column: 3 + 1 = 4 == colSum[0]
1st column: 0 + 7 = 7 == colSum[1]
The row and column sums match, and all matrix elements are non-negative.
Another possible matrix is: [[1,2],
                             [3,5]]

The 0th row should be **3 + 0 = 3 == rowSum[0]**

#### Additional context

This typo also exists on Chinese LC website.

**Comment by lc-kay** [comment]
@shurui91 Can you please provide the problem number? Thank you!

**Comment by shurui91** [comment]
> @shurui91 Can you please provide the problem number? Thank you!

1605

**Comment by lc-kay** [comment]
@shurui91 
I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @shurui91 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
