### ISSUE TITLE
Missing Test Case - 141. Linked List Cycle

### ISSUE THREAD

**Issue by MohsinKokani** [LeetCode-Feedback/LeetCode-Feedback#17580]
#### Your LeetCode username
MohsinKokani

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [Y] Missing Test Cases 

#### Description of the bug

If the logic is, at each node mark it -1 and traverse further, if again we got -1 we will check if cur->next->val == -1, but as per the constraints the node value can be -1. But this logic of detecting cycle got accepted

#### Code you used for Submit/Run operation
```
class Solution {
public:
    bool hasCycle(ListNode *head) {
        if (head==NULL or head->next==NULL)
        {
            return false;
        }
        while(head->next){
            if(head->val==-1 and head->next->val==-1){
                return true;
            }
            head->val=-1;
            head=head->next;
        }
        return false;
    }
};
```

#### Language used for code
C++

#### Expected behavior
This code was not correct as per the constraints given, but still got accepted

#### Screenshots
![Screenshot 2023-10-28 at 12-10-47 Linked List Cycle - LeetCode](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/126567752/1bea7539-2992-4f88-ad5b-944798e7d725)

#### Additional context
the above code shall not work if the test case 
[3,2,-1,-1]
-1 //no cycle

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
