### ISSUE TITLE
Clone Graph | Incorrect Default Test Case

### ISSUE THREAD

**Issue by vikash-gupta** [LeetCode-Feedback/LeetCode-Feedback#1758]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Problem-
https://leetcode.com/problems/clone-graph/
Default Test Case given by LeetCode on this problem
[[2,4],[1,3],[2,4],[1,3]]
[[]]
[]

This is a confusing test case. You have given 3 test cases, one in each line. That's why so many of the users have down voted your question. The question is valid, but no body can debug with this wrong default test case. Please fix the test case to a correct case e.g.
[[2,4],[1,3],[2,4],[1,3]]

You just need to give 1 default test case. No other question has 3 test cases, all have just one.

#### Expected behavior
We should be able to debug the test case

**Comment by lc-kay** [comment]
Hi @vikash-gupta 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @vikash-gupta 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!
