### ISSUE TITLE
Editorial typo- 779. K-th Symbol in Grammar

### ISSUE THREAD

**Issue by xelplogoog** [LeetCode-Feedback/LeetCode-Feedback#17588]
#### Your LeetCode username
c4tdog

#### Description of the bug
https://leetcode.com/problems/k-th-symbol-in-grammar/editorial/
There is a missing space between words `time` and `complexity`

<img width="316" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2188302/63ef60ff-436c-4c0e-a548-20388075b13c">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
