### ISSUE TITLE
Sliding Window Maximum | Misleading description

### ISSUE THREAD

**Issue by vikash-gupta** [LeetCode-Feedback/LeetCode-Feedback#1759]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
In the question
https://leetcode.com/problems/sliding-window-maximum/solution/
Approach #2, it's mentioned that:

> Clean the deque :
> 
> Keep only the indexes of elements from the current sliding window.

whereas code only one index. That is, there is no  loop to remove multiple indices.
```
    // remove indexes of elements not from sliding window
    if (!deq.isEmpty() && deq.getFirst() == i - k)
      deq.removeFirst();
```
This is misleading. Description should state that remove the element from left, it the index is outside of the sliding window.

#### Expected behavior
Premium solution shouldn't have ambiguity.

**Comment by lc-kay** [comment]
Hi @vikash-gupta 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @vikash-gupta 
Thank you for your time. We've reviewed your report and concluded that the article is correct as it is.
