### ISSUE TITLE
Typo in Question - 1220. Count Vowels Permutation

### ISSUE THREAD

**Issue by lilweege** [LeetCode-Feedback/LeetCode-Feedback#17599]
#### Your LeetCode username
lilweege

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

https://leetcode.com/problems/count-vowels-permutation/description/

There are two instances of the period inside the code block. It should read

"... only be followed by an `'a'`."

and

"... return it modulo `10^9 + 7`."

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/59585724/3d0ffcb8-e2c3-4bdd-8aee-e688ee41a7a8)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
