### ISSUE TITLE
Missing Test Case - 1220. Count Vowels Permutation

### ISSUE THREAD

**Issue by lilweege** [LeetCode-Feedback/LeetCode-Feedback#17597]
#### Your LeetCode username
lilweege

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

https://leetcode.com/problems/count-vowels-permutation/description

For the following values of n, the provided code computes the wrong answer. This is because the code does not take the modulo of intermediary values when computing the matrix multiplication. For instance, `t[i] += f[j] * g[i][j] % m;` should actually be `t[i] = (t[i] + f[j] * g[i][j]) % m;`.
```
2168
2471
2507
6264
6567
6603
10360
10663
10699
14456
14759
14795
18552
18855
18891
```

#### Code you used for Submit/Run operation

```c++
class Solution {
    using ull = unsigned long long;
    static constexpr ull m = 1e9 + 7;

public:
    int countVowelPermutation(int n) {
        ull f[5] = {1,1,1,1,1};
        ull g[5][5] = {
            {0,1,0,0,0},
            {1,0,1,0,0},
            {1,1,0,1,1},
            {0,0,1,0,1},
            {1,0,0,0,0},
        };
        for (--n; n > 0; n >>= 1) {
            if (n & 1) {
                ull t[5]{};
                for (int i = 0; i < 5; ++i)
                    for (int j = 0; j < 5; ++j)
                        t[i] += f[j] * g[i][j] % m;
                for (int i = 0; i < 5; ++i)
                    f[i] = t[i];
            }
            ull t[5][5]{};
            for (int i = 0; i < 5; ++i)
                for (int j = 0; j < 5; ++j)
                    for (int k = 0; k < 5; ++k)
                        t[i][j] += g[i][k] * g[k][j] % m;
            for (int i = 0; i < 5; ++i)
                for (int j = 0; j < 5; ++j)
                    g[i][j] = t[i][j];
        }

        int ans = 0;
        for (int i = 0; i < 5; ++i)
            ans = (ans + f[i]) % m;
        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior

The submission should not be accepted.

#### Screenshots

The following is a screenshot of the accepted submission, and a failing sample case.
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/59585724/3c88da8a-802f-4027-9229-6eae4519d061)

#### Additional context

Submission link:
https://leetcode.com/problems/count-vowels-permutation/submissions/1086369343/?envType=daily-question&envId=2023-10-28

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
