### ISSUE TITLE
Mistake in Question - 1220. Count Vowels Permutation; Example test case not ran by default

### ISSUE THREAD

**Issue by lilweege** [LeetCode-Feedback/LeetCode-Feedback#17598]
#### Your LeetCode username
lilweege

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

https://leetcode.com/problems/count-vowels-permutation/description
There are three example test cases in the description of the question, but the last one is not included in the "Testcase" list by default.

#### Expected behavior

The third test case should be included in the list of default test cases.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/59585724/8495652a-f904-47a0-8da5-dcc021ea038b)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
