### ISSUE TITLE
Re: 1374. Leftmost Column with at Least a One

### ISSUE THREAD

**Issue by Ankur-Deka** [LeetCode-Feedback/LeetCode-Feedback#176]
**What kind of the bug**
language

**Describe the bug**

 The question description says: BinaryMatrix.get(x, y) returns the element of the matrix at index (x, y) (0-indexed).
A clearer description would have been: BinaryMatrix.get(r, c) returns the element of the matrix at index [r,c] (0-indexed).
Generally x is used to denote x axis and this might create confusion.

**what language is your code written in**
C++

**Comment by CooperCooperCooper** [comment]
Hi @Ankur-Deka ,
Thank you for reaching out to us. We've received [a similar request](https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/170) a while back and have updated the problem statement for the problem "Leftmost Column with at Least a One" accordingly.

However, "Leftmost Column with at Least a One" does not have problem number "1374". Would you please clarify what the numbers refer to? We appreciate your time and support.

**Comment by Ankur-Deka** [comment]
Hi
I am referring to the question for April 21 on 30-Day LeetCoding Challenge. I just checked it again and it seems the language is rectified now. Thank you for considering! :+1:

**Comment by CooperCooperCooper** [comment]
Hi @Ankur-Deka,
Awesome! Thank you for your feedback.
