### ISSUE TITLE
603. 连续空余座位: pandas测试用例有误

### ISSUE THREAD

**Issue by Aniurm** [LeetCode-Feedback/LeetCode-Feedback#17605]
**你的 LeetCode 用户名**
ANIURM

**Bug 类型**
- [x] 题目
- [ ] 题解
- [x] 编程语言
- [ ] 缺少测试用例

**描述**
不管输入什么测试用例，print(cinema)的结果中free永远为True

**你使用的语言**
pandas

**你提交或者运行的代码**
```
def consecutive_available_seats(cinema: pd.DataFrame) -> pd.DataFrame:
    print(cinema)
```

**期望行为**
当输入的free为0，打印出来的cinema中的free应该为false

**屏幕截图**
<img width="1828" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/85830317/d14ea6c6-67c1-4656-bb26-c114391bd610">

**额外的上下文**
题目：[603. 连续空余座位](https://leetcode.cn/problems/consecutive-available-seats/)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by amcones** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by Aniurm** [comment]
leetcode.cn/u/aniurm/
