### ISSUE TITLE
621. Task Scheduler, typo in editorial

### ISSUE THREAD

**Issue by hekillno16** [LeetCode-Feedback/LeetCode-Feedback#17600]
#### Your LeetCode username
Hekillno

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

there's a typo in the editorial of 621. Task Scheduler
in the step diagram of Approach 1: Greedy. In pic 4/5 (check the screenshot).

Instead of "Idle_time = 8 - xxx(1) = 5"
it should be "Idle_time = 6 - xxx(1) = 5"

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

<img width="451" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/6127809/88ef1fee-f086-42ce-b465-f0f815651b9e">
<img width="446" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/6127809/614fd01a-0fdc-4384-9e03-c7cdc25ac819">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
