### ISSUE TITLE
Mistake in Solution Article - 458. Poor Pigs

### ISSUE THREAD

**Issue by FanchenBao** [LeetCode-Feedback/LeetCode-Feedback#17608]
#### Your LeetCode username
FanchenBao

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The Java solution in the solution article fails a test case.

#### Code you used for Submit/Run operation

Below is the official Java solution which fails the test case buckets=125, minutesToDie=1, minutesToTest=4

```

class Solution {
  public int poorPigs(int buckets, int minutesToDie, int minutesToTest) {
    int states = minutesToTest / minutesToDie + 1;
    return (int) Math.ceil(Math.log(buckets) / Math.log(states));
  }
}
```

#### Language used for code

Java

#### Expected behavior

I expect the Java solution in the solution article to pass all test cases.

#### Screenshots

![Screenshot 2023-10-28 at 21 56 38](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/43209858/daae9a08-976b-4002-9e61-a4445c319ca8)

#### Additional context

The failure is due to the way Java handles double value. There are at least two ways to resolve this issue.

## Option 1: Use  BigDecimal and RoundingMode

```
import java.math.*;

class Solution {
    public int poorPigs(int buckets, int minutesToDie, int minutesToTest) {
        int states = minutesToTest / minutesToDie + 1;
        double tmp = Math.log(buckets) / Math.log(states);
        return (int)Math.ceil(new BigDecimal(tmp).setScale(1, RoundingMode.HALF_UP).doubleValue());
    }
}
```

## Option 2: Compare Double Value with Precision

```
class Solution {
    public int poorPigs(int buckets, int minutesToDie, int minutesToTest) {
        int states = minutesToTest / minutesToDie + 1;
        double tmp = Math.log(buckets) / Math.log(states);
        if (Math.abs(tmp - (int)tmp) <= 0.00001d) return (int)tmp;
        return (int)tmp + 1;
    }
}
```

Performance-wise, Option 2 is quicker because it does not require the instantiation of a `BigDecimal` object.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
