### ISSUE TITLE
Editorial solution fails on a test case

### ISSUE THREAD

**Issue by mullachv** [LeetCode-Feedback/LeetCode-Feedback#17609]
#### Your LeetCode username
mullachv

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [X] Official Editorial solution Fails Test case

#### Description of the bug
Question: https://leetcode.com/problems/poor-pigs/editorial/
Editorial solution fails test case below:
```
buckets = 125
minutesToDie = 1
minutesToTest = 4
```

#### Code you used for Submit/Run operation

```
class Solution:
    def poorPigs(self, buckets: int, minutesToDie: int, minutesToTest: int) -> int:
        states = minutesToTest // minutesToDie + 1
        return math.ceil(math.log(buckets) / math.log(states))
```

#### Language used for code
Python

#### Expected behavior
- Expected to pass test case. But in reality the code fails the test case

#### Additional context
The fix is to use log base 2 in the code as shown here:
```
class Solution:
    def poorPigs(self, buckets: int, minutesToDie: int, minutesToTest: int) -> int:
        states = minutesToTest // minutesToDie + 1
        return math.ceil(math.log2(buckets) / math.log2(states))
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
