### ISSUE TITLE
Missing Test Case - 78. Subsets

### ISSUE THREAD

**Issue by yinghua-cs** [LeetCode-Feedback/LeetCode-Feedback#1760]
#### Your LeetCode username

hattieq

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

If the numbers are not distinct in the test case, the expected output has duplicate subsets.

#### Code you used for Submit/Run operation

```

```

#### Expected behavior

with test case : [1,1,2,3]
the expected output should be : [[],[1],[1,1],[1,1,2],[1,1,2,3],[1,1,3],[1,2],[1,2,3],[1,3],[2],[2,3],[3]]
but it is : [[],[1],[1],[1,1],[2],[1,2],[1,2],[1,1,2],[3],[1,3],[1,3],[1,1,3],[2,3],[1,2,3],[1,2,3],[1,1,2,3]]

**Comment by lc-kay** [comment]
@yinghua-cs This issue was reported earlier by another user and has been fixed based on her ticket. Thank you so much for your time!
