### ISSUE TITLE
Missing Test Case - 2916. Subarrays Distinct Element Sum of Squares II

### ISSUE THREAD

**Issue by arg2k** [LeetCode-Feedback/LeetCode-Feedback#17607]
#### Your LeetCode username

argha_kole 

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Even though a solution for the problem <a href="https://leetcode.com/problems/subarrays-distinct-element-sum-of-squares-ii/">2916. Subarrays Distinct Element Sum of Squares II</a> passed all the test cases and was accepted,
it gets TLE for the following testcase : [lc_testcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/13197205/lc_testcase.txt)

#### Code you used for Submit/Run operation

```
// 2916. Subarrays Distinct Element Sum of Squares II
int MOD = 1e9 + 7;

class Solution {
public:
    int sumCounts(vector<int>& nums) {
        int n = nums.size();
        // jank
        // If all elements are distinct, return sum of sum of squares
        unordered_set<int> s;
        for (int & a : nums) {
            s.insert(a);
        }
        if (s.size() == n) {
            long long ans = 0;
            for (int i = 1; i <= n; i++) {
                ans += (long long)i * (i + 1) * (2 * i + 1) / 6;
                ans %= MOD;
            }
            return ans;
        }
        // O(n * number of distinct elements)
        vector<int> v;
        unordered_map<int, int> m;
        long long ans = 0;
        for (int i = 0; i < n; i++) {
            int a = nums[i];
            v.push_back(1);
            // if element existed before, find previous occurrance and merge the 2 adjacent runs together
            if (m.count(a)) {
                int suffix = 0;
                for (int j = v.size() - 2; j >= 0; j--) {
                    suffix += v[j];
                    if (suffix >= i - m[a]) {
                        v[j] += v[j + 1];
                        v.erase(v.begin() + j + 1);
                        break;
                    }
                }
            }
            m[a] = i;
            // update ans
            for (int j = 0; j < v.size(); j++) {
                ans += ((((v.size() - j) * (v.size() - j)) % MOD) * v[j]) % MOD;
                ans %= MOD;
            }
        }
        return ans;
    }
};
```

#### Language used for code

 C++

#### Expected behavior

The code gets TLE for the following testcase : [lc_testcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/13197204/lc_testcase.txt)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
