### ISSUE TITLE
Missing Test Case - 458. Poor Pigs

### ISSUE THREAD

**Issue by AaliyahBeg** [LeetCode-Feedback/LeetCode-Feedback#17615]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The first code is getting accepted although it fails to give the correct output for the testcase : 

Input
```
buckets =
90
```
```
minutesToDie =
2
```
```
minutesToTest =
7
```

#### Code you used for Submit/Run operation

```
// Incorrect code which is getting accepted
class Solution {
public:
    int poorPigs(int buckets, int minutesToDie, int minutesToTest) {
        int ans=0;
        while(pow(minutesToTest/float(minutesToDie)+1,ans)<buckets)ans++;
        return ans;
    }
};
```

```
//Correct code
class Solution {
public:
    int poorPigs(int buckets, int minutesToDie, int minutesToTest) {
        int ans=0;
        while(pow(minutesToTest/minutesToDie+1,ans)<buckets)ans++;
        return ans;
    }
};
```

#### Language used for code
 C++

#### Expected behavior

For the test case 

Input
```
buckets =
90
```
```
minutesToDie =
2
```
```
minutesToTest =
7
```

I expected the code

```
// Incorrect code which is getting accepted
class Solution {
public:
    int poorPigs(int buckets, int minutesToDie, int minutesToTest) {
        int ans=0;
        while(pow(minutesToTest/float(minutesToDie)+1,ans)<buckets)ans++;
        return ans;
    }
};
```
To fail as its giving wrong answer 
```
Output
3
```
```
Expected
4
```
However this solution is also getting accepted.

#### Screenshots

![Leetcode PoorPig](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/94232945/0f6f74af-ed5e-4aac-b488-232a55ad629a)
![Leetcode PoorPig2](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/94232945/74d24442-70df-4cd6-82ad-fb22a7aa9b6f)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
