### ISSUE TITLE
Wrond expected answer in testcases - 458. Poor Pigs

### ISSUE THREAD

**Issue by lostinth1cho** [LeetCode-Feedback/LeetCode-Feedback#17616]
#### Category of the bug
- wrong result

#### Description of the bug

The expected answer when buckets = 1,  minutesToDie = 1,  minutesToTest = 1 is 0.
How could  you test when the number of pigs is 0 ?

#### Code you used for Submit/Run operation

```
// [458. Poor Pigs]
class Solution {
public:
    int poorPigs(int buckets, int minutesToDie, int minutesToTest) {
        int T = minutesToTest / minutesToDie;
        int res = 1;
        int product = T+1;
        while (product < buckets ){
            product *= (T+1);
            res++;
        }
        return res;
    }
};
```

#### Expected behavior

the answer should be at least 1.

**Comment by SophiaPrice** [comment]
Hi,

The question tells us: 

> There are buckets buckets of liquid, where exactly one of the buckets is poisonous.

If there is only 1 bucket, then we know that it must be poisonous, therefore we need 0 pigs

**Comment by lostinth1cho** [comment]
You're absolutely right. Thanks for pointing that out.
