### ISSUE TITLE
Mistake in Editorial - 458. Poor Pigs

### ISSUE THREAD

**Issue by just-small-potato** [LeetCode-Feedback/LeetCode-Feedback#17612]
#### Your LeetCode username

icelam

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The below Java solution found in editorial failes on the test case `buckets = 125, minutesToDie = 1, minutesToTest = 4`.

```java
class Solution {
  public int poorPigs(int buckets, int minutesToDie, int minutesToTest) {
    int states = minutesToTest / minutesToDie + 1;
    return (int) Math.ceil(Math.log(buckets) / Math.log(states));
  }
}
```

#### Code you used for Submit/Run operation

```java
class Solution {
  public int poorPigs(int buckets, int minutesToDie, int minutesToTest) {
    int states = minutesToTest / minutesToDie + 1;
    return (int) Math.ceil(Math.log(buckets) / Math.log(states));
  }
}
```

#### Language used for code
Java

#### Expected behavior

The Java solution in editorial should pass all the test cases. Currently it is failing due to due to precision and rounding issues.

#### Screenshots

<img width="753" alt="Screenshot 2023-10-29 at 3 11 23 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/68165945/a47eaf90-d608-4e3b-9bca-3cc70c29e43c">

### One way to make the code work is to use `Math.log10()` instead of `Math.log()`.

```java
class Solution {
  public int poorPigs(int buckets, int minutesToDie, int minutesToTest) {
    int states = minutesToTest / minutesToDie + 1;
    return (int) Math.ceil(Math.log10(buckets) / Math.log10(states));
  }
}
```
<img width="758" alt="Screenshot 2023-10-29 at 3 31 01 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/68165945/0fee5554-9939-4018-865d-8f5e8501d6ff">

### This version of code found on the chines version editorial (leetcode.cn) also works.

```java
class Solution {
  public int poorPigs(int buckets, int minutesToDie, int minutesToTest) {
    int states = minutesToTest / minutesToDie + 1;
    return (int) Math.ceil(Math.log(buckets) / Math.log(states) - 1e-5);
  }
}
```

<img width="758" alt="Screenshot 2023-10-29 at 3 30 23 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/68165945/e09a4edf-0275-4618-9c3e-c4f6339a115f">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
