### ISSUE TITLE
Missing Test Case/BUG in accepted solution - 15. 3Sum

### ISSUE THREAD

**Issue by jitendrac** [LeetCode-Feedback/LeetCode-Feedback#1762]
#### Category of the bug

- [ 1] Solution

#### Description of the bug

scope of problem solution is
" Find all unique triplets in the array which gives the sum of zero."
it do-not specify any specific required order.
but I am getting
Wrong Answer
Details
Input
[-1,0,1,2,-1,-4]
Output
[[-1,0,1],[-1,-1,2],]
Expected
[[-1,-1,2],[-1,0,1]]

#### Code you used for Submit/Run operation

```
/**
 * @param {number[]} nums
 * @return {number[][]}
 */
var threeSum = function(nums) {
    var a=[];
    for( i=0;i<nums.length-2;i++){
        for( j=i+1;j<nums.length-1;j++){
            for( k=j+1;k<nums.length;k++){
                if(nums[i]+nums[j]+nums[k]==0){
                    x=[nums[i],nums[j],nums[k]];
                    x.sort();
                    a.push(x);
                    break;
                }
                
            }
        }
    }
    //return;
    for( i=0;i<a.length;i++){
        for( j=i+1;j<a.length;j++){
            if(JSON.stringify(a[i])===JSON.stringify(a[j])){
               delete a[j];
               }
        }
    }
    
    
    return a;
};
```

**Comment by lc-kay** [comment]
Hi @jitendrac 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@jitendrac The order of the output indeed doesn't matter in this problem. There is a bug in your solution, [[-1,0,1],[-1,-1,2],] has extra comma which comes from some deleted array. Thank you for your time!
