### ISSUE TITLE
Missing Test Case - 458. Poor Pigs

### ISSUE THREAD

**Issue by przemek3d88** [LeetCode-Feedback/LeetCode-Feedback#17626]
#### Your LeetCode username
przemysaw2

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The below solution was [accepted](https://leetcode.com/problems/poor-pigs/submissions/1086974933?envType=daily-question&envId=2023-10-29), but it gives WA on a max test, returning 10 pigs.

```
1000
1
1
```

#### Code you used for Submit/Run operation

```
class Solution {
    const int MX = 10;
    int go(const int& n, const int& experiments, vector<vector<int>>& dp, const vector<int>& fact) {
        if(!n || !experiments) {
            return 1;
        }

        if(experiments == 1) {
            return 1<<n;
        }

        if(dp[n][experiments] != -1) {
            return dp[n][experiments];
        }

        int res = 0;
        for(int left = 0; left <= n; left++) {
            res += fact[n]/fact[left]/fact[n-left] * go(left, experiments-1, dp, fact);
        }

        return dp[n][experiments] = res;
    }
public:
    int poorPigs(int buckets, int minutesToDie, int minutesToTest) {
        int experiments = minutesToTest / minutesToDie;
        vector<vector<int>> dp(MX, vector<int>(experiments+1, -1));
        vector<int> fact(MX);
        fact[0] = 1;
        for(int i = 1; i < MX; i++) {
            fact[i] = i*fact[i-1];
        }

        for(int pigs = 0; pigs < MX; pigs++) {
            if(go(pigs, experiments, dp, fact) >= buckets) {
                return pigs;
            }
        }

        return -1;
    }
};```

#### Language used for code
C++

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by przemek3d88** [comment]
I updated the original post with this [link](https://leetcode.com/problems/poor-pigs/submissions/1086974933?envType=daily-question&envId=2023-10-29).

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
