### ISSUE TITLE
Question 92: while loop does not break when it should.

### ISSUE THREAD

**Issue by cedricchao** [LeetCode-Feedback/LeetCode-Feedback#17627]
#### Your LeetCode username

CedricatDeipnon

#### Category of the bug
- [ 1] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The break loop should break at line

#### Code you used for Submit/Run operation

```
//19. Remove nth node from end of the list
class Solution:
    def removeNthFromEnd(self, head: Optional[ListNode], n: int) -> Optional[ListNode]:
        cur = head
        visited = []
        
        while cur!=None:
            visited.append(cur)
            cur = cur.next
        print(len(visited))
        skipped = visited[-n-1]

        # print(len(visited))

        return skipped
```

#### Expected behavior

The while loop should break on line 15 because it is outside the while loop already, but somehow line 14 runs again. This should not happen.

#### Screenshots

<img width="1262" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/49173387/081881b5-2e92-4dc2-9b94-4dec301f161b">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

Please ask your question in the discussion forum.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
