### ISSUE TITLE
Missing Test Case - 458. Poor Pigs

### ISSUE THREAD

**Issue by 0wang1** [LeetCode-Feedback/LeetCode-Feedback#17623]
#### Your LeetCode username

0wang1

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Poor Pigs
class Solution:
    def poorPigs(self, buckets: int, minutesToDie: int, minutesToTest: int) -> int:
        pigs = 0
        while (minutesToTest / minutesToDie + 1) ** pigs < buckets:
            pigs += 1
        return pigs
```

#### Language used for code

Python

#### Expected behavior

Given the test case buckets = 125, minutesToDie = 3, and minutesToTest = 4, the expected output should be 7. The solution produces the answer 6, but is accepted upon submission

#### Screenshots

![1](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/20128944/97d8c9ed-05c5-4682-8a25-138f884347df)
![2](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/20128944/b61f1264-8ca9-41dd-8092-68568a5ca23b)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
