### ISSUE TITLE
Missing Test Case - 2003. Smallest Missing Genetic Value in Each Subtree

### ISSUE THREAD

**Issue by EndlessCheng** [LeetCode-Feedback/LeetCode-Feedback#17630]
#### Your LeetCode username

endlesscheng

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The code below should get RUNTIME ERROR, but it got ACCEPTED instead.

TEST CASE:
```
[-1,0,0,2]
[1,100,101,102]
```

#### Code you used for Submit/Run operation

```py
class Solution:
    def smallestMissingValueSubtree(self, parents: List[int], nums: List[int]) -> List[int]:
        n = len(parents)
        ans = [1] * n
        try:
            node, now = nums.index(1), 1
        except:
            return ans
        g = [[] for _ in range(n)]
        vst = [0] * (n + 2)
        for i in range(1, n):
            g[parents[i]].append(i)
        while node != -1:
            q = deque([son for son in g[node] if not vst[nums[son]]])
            vst[nums[node]] = 1
            while q:
                tmp = q.popleft()
                vst[nums[tmp]] = 1
                q += g[tmp]
            while vst[now]:
                now += 1
            ans[node] = now
            node = parents[node]
        return ans
```

#### Language used for code

Python3

#### Expected behavior

RUNTIME ERROR on this test case:
```
[-1,0,0,2]
[1,100,101,102]
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
