### ISSUE TITLE
Missing Test Case - 179. Largest Number

### ISSUE THREAD

**Issue by PB21071438** [LeetCode-Feedback/LeetCode-Feedback#17634]
#### Your LeetCode username

PB21071438

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [O] Missing Test Cases 

#### Description of the bug

input like this [111231111, 11123111]
the following Solution couldn't pass,
but it passed all the testcases.

#### Code you used for Submit/Run operation

class Solution:
    def largestNumber(self, nums: List[int]) -> str:
        s = "".join(sorted((str(n) for n in nums), key=lambda n: [n[pos % len(n)] for pos in range(11)], reverse=True)).lstrip('0')
        return s if s else '0'

#### Language used for code

python3

#### Expected behavior

"11123111111231111"

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/104665651/50ef5a86-2617-4692-a87f-9bec9a54c6b9)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by PB21071438** [comment]
https://leetcode.com/problems/largest-number/submissions/1088033399/

**Comment by PB21071438** [comment]
missing test case : [111231111, 11123111]

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
