### ISSUE TITLE
Missing Test Case - 1410. HTML Entity Parser

### ISSUE THREAD

**Issue by rajesh0101** [LeetCode-Feedback/LeetCode-Feedback#1763]
#### Category of the bug
- [x] Question: I guess some of the test cases are missing.
- [ ] Solution
- [ ] Language

#### Description of the bug

Certain test cases such as "&\&gt;" are missing. They should ideally be included as well since these test cases are not getting tested as per the existing test cases provided.

#### Code you used for Submit/Run operation

```
class Solution {
    public String entityParser(String text) {
        Map<String, String> hMap=new HashMap<>();
        hMap.put("&quot;","\"");hMap.put("&apos;","'");hMap.put("&amp;","&");
        hMap.put("&gt;",">");hMap.put("&lt;","<");hMap.put("&frasl;","/");
        
        StringBuilder sb=new StringBuilder();
        for(int i=0;i<text.length();){
            char c=text.charAt(i);
            if(c=='&'){
                int j=i+1;
                while(j<text.length() && text.charAt(j)!=';') j++;
                if(hMap.containsKey(text.substring(i,j+1))){
                    sb.append(hMap.get(text.substring(i,j+1)));
                }
                else{
                    sb.append(text.substring(i,j+1));
                }
                i=j+1;
            }
            else{
               sb.append(c);i++; 
            }
        }
        return sb.toString();        
    }
}
```

#### Language used for code
Java

#### Expected behavior

This code should not pass the above test case mentioned. But in actual, it does. Since the test case in missing in the set of existing test cases provided.

**Comment by lc-kay** [comment]
Hi @rajesh0101 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @rajesh0101 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by rajesh0101** [comment]
Hi there.

Thank you for the support.
My LeetCode ID is c_ha
