### ISSUE TITLE
Missing Test Case - 104. Maximum Depth of Binary Tree

### ISSUE THREAD

**Issue by jitendrac** [LeetCode-Feedback/LeetCode-Feedback#1765]
#### Category of the bug
- [1] Solution

#### Description of the bug

Same Test case passes on local run but fails in submissions.

#### Code you used for Submit/Run operation

```
/**
 * Definition for a binary tree node.
 * function TreeNode(val, left, right) {
 *     this.val = (val===undefined ? 0 : val)
 *     this.left = (left===undefined ? null : left)
 *     this.right = (right===undefined ? null : right)
 * }
 */

var max_level=0;
function traverse(root,cu_level){
    var cur_level=cu_level;
    if(root!=null){
        cur_level++;
        if(cur_level>max_level){
            max_level=cur_level;
        }
        traverse(root.left,cur_level);
        traverse(root.right,cur_level);
    }
}
/**
 * @param {TreeNode} root
 * @return {number}
 */
var maxDepth = function(root) {
     traverse(root,0);
    return max_level;
};
```

#### Language used for code

Javascript

#### Expected behavior

Submission success.

#### Screenshots

![image](https://user-images.githubusercontent.com/1154328/103154697-203b1280-47bf-11eb-93e6-23c66773158b.png)

**Comment by lc-kay** [comment]
Hi @jitendrac 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
