### ISSUE TITLE
Missing Test Case| submission not working properly - 933. Increasing Order Search Tree

### ISSUE THREAD

**Issue by jitendrac** [LeetCode-Feedback/LeetCode-Feedback#1766]
#### LeetCode username Jitendrac

Jitendrac

#### Category of the bug

- [1] Solution

#### Code you used for Submit/Run operation

```
/**
 * Definition for a binary tree node.
 * function TreeNode(val, left, right) {
 *     this.val = (val===undefined ? 0 : val)
 *     this.left = (left===undefined ? null : left)
 *     this.right = (right===undefined ? null : right)
 * }
 */

treeVals=[];

function traverse(root){
    if(root!=null){
        treeVals.push(root.val);
        traverse(root.left);
        traverse(root.right);
    }
    
}
/**
 * @param {TreeNode} root
 * @return {TreeNode}
 */
var increasingBST = function(root) {
    traverse(root);
    treeVals.sort();
    if(treeVals.length==0){
        return null;
    }
    tree=new TreeNode(treeVals[0],null,null);
    current_node=tree;
    for(x=1;x<treeVals.length;x++){
        current_node.right=new TreeNode(treeVals[x],null,null);
        current_node=current_node.right;
    }
    return tree;
    
};
```

#### Language used for code

Javascript

#### Expected behavior

Submission Accepted.

#### Screenshots

![image](https://user-images.githubusercontent.com/1154328/103155281-3c8d7e00-47c4-11eb-9a6c-f7c9a5d4384c.png)

**Comment by lc-kay** [comment]
Hi @jitendrac 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
