### ISSUE TITLE
Incorrect Binary Tree Implementation for Javascript

### ISSUE THREAD

**Issue by DentFuse** [LeetCode-Feedback/LeetCode-Feedback#17676]
#### Your LeetCode username

DentFuse

#### Category of the bug
- Language

#### Description of the bug

Binary Tree Node implementation seems to be incorrect. `root.left` is truthy even when it is null.

#### Code you used for Submit/Run operation

[Binary Tree Inorder Traversal](https://leetcode.com/problems/binary-tree-inorder-traversal/)
```js
var inorderTraversal = function(root, arr = []) {
    if(root.left) inorderTraversal(root.left, arr);
    arr.push(root.val)
    if(root.right) inorderTraversal(root.right, arr);
    return arr;
};
```

#### Language used for code

Javascript

#### Expected behavior

`root.left` and `root.right` should be falsy when `null`. `if` condition on lines 2 & 4 should not execute and `null` should not be passed to the function via these function calls.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/25380286/f1be9bb9-07b5-4cf8-8e73-b73bbffc1053)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Please ask your question in the discussion forum.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
