### ISSUE TITLE
Missing Test Case - 1703. Minimum Adjacent Swaps for K Consecutive Ones

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#1767]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution is accepted but fails on the following test case:
[1, 0]
1

#### Code you used for Submit/Run operation

```
class Solution {

	public int minMoves(int[] nums, int k) {
		int[] reverse = new int[nums.length];
		for (int i = 0; i < nums.length; i++) {
			reverse[i] = nums[nums.length - i - 1];
		}
		int[] a = minMoves2(nums, k / 2);
		int[] b = minMoves2(reverse, k - k / 2);
		int min = Integer.MAX_VALUE;
		for (int i = 1; i < nums.length; i++) {
			if (a[i - 1] != Integer.MAX_VALUE && b[nums.length - i - 1] != Integer.MAX_VALUE) {
				min = Math.min(min, a[i - 1] + b[nums.length - i - 1]);
			}
		}
		return min;
	}

	public int[] minMoves2(int[] nums, int k) {
		int min = Integer.MAX_VALUE, count = 0;
		int[] result = new int[nums.length];
		ArrayDeque<Integer> deque = new ArrayDeque<>();
		for (int i = 0; i < nums.length; i++) {
			if (nums[i] == 1) {
				deque.add(i);
				if (deque.size() > k) {
					count -= i - deque.pop() - k;
				}
				if (deque.size() == k) {
					min = Math.min(min, count);
				}
			} else {
				count += deque.size();
			}
			result[i] = deque.size() == k ? count : Integer.MAX_VALUE;
		}
		return result;
	}
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/103155474-63b96080-476e-11eb-8149-7242d7150617.png)

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
