### ISSUE TITLE
Missing Test Case - 1220. Count Vowels Permutation

### ISSUE THREAD

**Issue by numericly** [LeetCode-Feedback/LeetCode-Feedback#17679]
#### Your LeetCode username
Numericly

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
There are no test cases which check for integer overflow when summing the possible permutations. An example of this is n = 174, n = 682, n = 1632, n = 1688, n = 1764, n = 1908.

#### Code you used for Submit/Run operation
```rust
// 1220. Count Vowels Permutation
const MODULO: u32 = 1_000_000_007;

struct State {
    a: u32,
    e: u32,
    i: u32,
    o: u32,
    u: u32,
}

impl State {
    fn update(&mut self) {
        let mut next_state = State {
            a: self.e + self.i + self.u,
            e: self.a + self.i,
            i: self.e + self.o,
            o: self.i,
            u: self.i + self.o,
        };

        next_state.a %= MODULO;
        next_state.e %= MODULO;
        next_state.i %= MODULO;
        next_state.o %= MODULO;
        next_state.u %= MODULO;

        *self = next_state;
    }
    fn permutations(&self) -> u32 {
        self.a + self.e + self.i + self.o + self.u
    }
}

impl Solution {
    pub fn count_vowel_permutation(n: i32) -> i32 {
        let mut state = State {
            a: 1,
            e: 1,
            i: 1,
            o: 1,
            u: 1,
        };

        for _ in 0..(n - 1) {
            state.update();
        }

        (state.permutations() % MODULO) as i32
    }
}
```

#### Language used for code
Rust

#### Expected behavior
It to reject this code as there is an integer overflow

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/107078148/48b3990d-8b68-4c41-952c-3199450b3320)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
