### ISSUE TITLE
Missing Test Case - 458. Poor Pigs

### ISSUE THREAD

**Issue by phungthienphuoc** [LeetCode-Feedback/LeetCode-Feedback#17687]
#### Description of the bug
I submitted a wrong code indicated below. However, it was accepted. I find out some test cases and try it; their results were wrong answer (as in the screenshot).

#### My suggestion for the test cases:
```
(buckets,minutesToDie,minutesToTest) = (10,7,20) , (15,18,27) , (100,11,43) , (123,29,100) , (999,16,79)
```
(I can find more counterexamples for the wrong code below, but I think these are enough.)
#### My Python code submitted

``` Python
class Solution:
    def poorPigs(self, buckets: int, minutesToDie: int, minutesToTest: int) -> int:
        i=0
        while (minutesToTest/minutesToDie+1)**i<buckets:
            i+=1
        return i
```

#### Expected behavior
With my suggested test cases, the codes using normal division will be rejected, and only codes using floor division are accepted.

#### Screenshots
<img width="960" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/149442589/46343b9f-2a94-40d1-9b68-4277cd7edc62">

#### Additional context
Here is the link of my wrong code accepted
https://leetcode.com/problems/poor-pigs/submissions/1087922138

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
