### ISSUE TITLE
Example 4: 1293. Shortest Path in a Grid with Obstacles Elimination solution bug: extra Array added during init

### ISSUE THREAD

**Issue by spanarin** [LeetCode-Feedback/LeetCode-Feedback#17684]
#### Your LeetCode username
sergpanarin

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In official solution in [Trees and Graphs](https://leetcode.com/explore/interview/card/leetcodes-interview-crash-course-data-structures-and-algorithms/707/traversals-trees-graphs/4631/) Example 4: [1293. Shortest Path in a Grid with Obstacles Elimination](https://leetcode.com/problems/shortest-path-in-a-grid-with-obstacles-elimination/) during init of `seen` array instead of just adding `-1` you create a new array of `k+1` length.

#### Code you used for Submit/Run operation

Full task solution with bug:
```javascript
/**
 * @param {number[][]} grid
 * @param {number} k
 * @return {number}
 */
var shortestPath = function(grid, k) {
    let valid = (row, col) => {
        return 0 <= row && row < m && 0 <= col && col < n;
    }
    
    let m = grid.length;
    let n = grid[0].length;
    let queue = [[0, 0, k]];
    let seen = [];
    for (let i = 0; i < m; i++) {
        seen.push([]);
        for (let j = 0 ; j < n; j++) {
            seen[i].push(new Array(k + 1).fill(-1));
        }
    }
    
    let directions = [[0, 1], [1, 0], [0, -1], [-1, 0]];
    let steps = 0;
    
    while (queue.length) {
        let currentLength = queue.length;
        let nextQueue = [];
        
        for (let i = 0; i < currentLength; i++) {
            let [row, col, remain] = queue[i];
            if (row == m - 1 && col == n - 1) {
                return steps;
            }

            // if the current square is an obstacle, we need to spend one of our removals
            if (grid[row][col] == 1) {
                if (remain == 0) {
                    continue;
                } else {
                    remain--;
                }
            }

            // if the square has already been visited, but with more removals, then the current
            // path is pointless, since more removals is better
            if (seen[row][col] >= remain) {
                continue;
            }

            seen[row][col] = remain;
            for (const [dx, dy] of directions) {
                let nextRow = row + dy, nextCol = col + dx;
                if (valid(nextRow, nextCol)) {
                    nextQueue.push([nextRow, nextCol, remain]);
                }
            }
        }
        
        queue = nextQueue;
        steps++;
    }
    
    return -1;
};
```

Code chunk with a bug:
```javascript
 for (let i = 0; i < m; i++) {
        seen.push([]);
        for (let j = 0 ; j < n; j++) {
            seen[i].push(new Array(k + 1).fill(-1));
        }
    }
```

#### Language used for code
JavaScript

#### Expected behavior

We don't need the array for every cell in the grid, we just need to put placeholder `-1` to show that every other path with more remaining will be better.

Fixed chunk
```javascript
 for (let i = 0; i < m; i++) {
        seen.push([]);
        for (let j = 0 ; j < n; j++) {
            // every cell will store number of eliminations left, init with -1
            seen[i].push(-1);
        }
    }
```

#### Screenshots

<img width="1680" alt="Screenshot 2023-10-30 at 22 24 46" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/12787010/87261578-67ba-4b2f-ac25-ddc679b3ffb6">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
