### ISSUE TITLE
8. String to Integer (atoi)

### ISSUE THREAD

**Issue by tanujav988** [LeetCode-Feedback/LeetCode-Feedback#17683]
#### Your LeetCode username

tanujav_

#### Category of the bug
- [ ] Question
- [ ] Solution
- [Y] Language
- [ ] Missing Test Cases 

#### Description of the bug
8. String to Integer (atoi)

I inadvertently initialized the 'sign' variable with an int type in my Java code when it should have been of datatype char. Surprisingly, the code compiled successfully and provided the correct results, despite the fact that it should have triggered a compilation error. Subsequently, I submitted the code with this unexpected behavior and it got accepted as well.

#### Code you used for Submit/Run operation

```
class Solution {
    public int myAtoi(String s) {
        
        s = s.trim();
        
        if(s.equals(""))
            return 0;
        
        int sign = '+';
        
        int i = 0;
        
        int n = s.length();
        
         if(s.charAt(0)=='-'){
            sign = '-';
            i++;
         }
        
        else if(s.charAt(0)=='+'){
            sign = '+';
            i++;
        }
        
        double num = 0;
        
        while(i<n && (s.charAt(i)>='0' && s.charAt(i)<='9')){
            num = num*10 + s.charAt(i)-'0';
            i++;
        }
        
  
        if(sign=='-')
            num = -num;
        
        if(num>Integer.MAX_VALUE)
            return Integer.MAX_VALUE;
        
        if(num<Integer.MIN_VALUE)
            return Integer.MIN_VALUE;
        
        return (int)(num);
    }
}
```

#### Language used for code
 Java

#### Expected behavior

The code should be giving compilation error

#### Screenshots

<img width="1421" alt="leet1" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73555975/f87e8a2c-6545-41de-b1cc-f60cefaecd3e">

<img width="1421" alt="leet2" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73555975/add10122-3566-409e-9260-7bdadca0d7ca">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Please ask your question in the discussion forum.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
