### ISSUE TITLE
Missing Test Case - 493. Reverse Pairs

### ISSUE THREAD

**Issue by whuangavistar** [LeetCode-Feedback/LeetCode-Feedback#1768]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

for test case as below
[2147483647,2147483647,-2147483647,-2147483647,-2147483647,2147483647]  
the expected answer is 9, 
it should be 6, [0,2],[0,3],[0,4],[1,2],[1,3],[1,4],

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by stormsunshine** [comment]
For this test case, the correct answer is 9.
The reverse pairs are [0,2],[0,3],[0,4],[1,2],[1,3],[1,4],[2,3],[2,4],[3,4].
Therefore, there is nothing incorrect with the current test case.

**Comment by lc-kay** [comment]
@whuangavistar The expected answer is correct. Please refer to @stormsunshine explanation and the discuss tab. Thank you for your time!
