### ISSUE TITLE
为了保证账号安全，本次请使用手机验证码登录

### ISSUE THREAD

**Issue by sugarcandy** [LeetCode-Feedback/LeetCode-Feedback#17688]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
上善若水

**Bug 类型**
账号换绑手机号问题

**描述**
换了手机号，在两台电脑上分别登录过leetcode账号，突然有一天提示我必须用原手机验证码登录，扫码不行，邮箱不行，账号密码不行，是哪个鬼才想出这么nt的设定的，特么leetcode app上还不能修改手机号，wtf?

**期望行为**
能在app换绑手机号，通过邮箱获取验证码换绑，手机扫码可以直接登录等等。

**屏幕截图**
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/40589172/6d955ea5-37a2-4d75-b8fb-831c31e8cf7a)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/40589172/fdd33b52-c90c-484d-aeb8-8b3360341d01)

**Comment by Nabiiiiiiiii** [comment]
您好，
感谢您的来信。经过和相关技术团队核实，登录提示「为了账号安全请用账号验证码登录」是平台为了保障用户账号安全，对登录的设备数量的限制。建议您在常用设备使用常用账号哦。如需要手机号换绑服务，请提供如下信息与我们：
- 需要绑定的手机号：
- 需要绑定的手机号对应的力扣账号：
收到您的回信后，会尽快移交相关人员帮您解决。
Best Regards,
Leetcode | Support Team

**Comment by sugarcandy** [comment]
需要绑定的手机号：15025729564

需要绑定的手机号对应的力扣账号：18250169706（上善若水）

15025729564这个手机号最近新注册了一个号，id为（暗梅幽闻花），必要时可以删除该账号



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LeetCode-Feedback/LeetCode-Feedback"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月31日(星期二) 下午2:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LeetCode-Feedback/LeetCode-Feedback] 为了保证账号安全，本次请使用手机验证码登录 (Issue #17688)





 
您好，
 感谢您的来信。经过和相关技术团队核实，登录提示「为了账号安全请用账号验证码登录」是平台为了保障用户账号安全，对登录的设备数量的限制。建议您在常用设备使用常用账号哦。如需要手机号换绑服务，请提供如下信息与我们：
  
需要绑定的手机号：
 
需要绑定的手机号对应的力扣账号：
 收到您的回信后，会尽快移交相关人员帮您解决。
 Best Regards,
 Leetcode | Support Team

**Comment by xdefine** [comment]
> 已换绑

您好，我也需要换绑手机号：
账户：https://leetcode.cn/u/zhu-65/
原来手机号：18909849601
需要绑定的手机号：15943386780，手机号可能注册了其他账号，必要时可以删除该账号

**Comment by liyuzhu-lc** [comment]
> > 已换绑
> 
> 您好，我也需要换绑手机号： 账户：https://leetcode.cn/u/zhu-65/ 原来手机号：18909849601 需要绑定的手机号：15943386780，手机号可能注册了其他账号，必要时可以删除该账号

您好，

感谢您的来信，根据您反馈的情况，我们需要验证当前帐号为您本人使用，请您提供以下信息至我们：
- 您的常用邮箱：
- 需要解绑的手机号：
- 绑定手机号对应的力扣账号：
- 常用登录地址：（省市）
- 常用登录设备系统：
- 常用登录浏览器：

在收到您的回复后，我们会提交至相关部门进行核实并向您提供的邮箱发送重置手机号联系，还请您注意查收。

Best Regards,
Leetcode | Support Team

**Comment by xdefine** [comment]
***@***.***

需要解绑的手机号：18909849601

绑定手机号对应的力扣账号：https://leetcode.cn/u/zhu-65/

常用登录地址：（省市）北京 广东省东莞市 (vpn 香港 新加坡)

常用登录设备系统：win10 win11

常用登录浏览器：谷歌浏览器




发自我的iPhone


------------------ 原始邮件 ------------------
发件人: liyuzhu-lc ***@***.***&gt;
发送时间: 2023年12月12日 16:45
收件人: LeetCode-Feedback/LeetCode-Feedback ***@***.***&gt;
抄送: Yuhang Pan ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [LeetCode-Feedback/LeetCode-Feedback] 为了保证账号安全，本次请使用手机验证码登录 (Issue #17688)





   
已换绑
  
您好，我也需要换绑手机号： 账户：https://leetcode.cn/u/zhu-65/ 原来手机号：18909849601 需要绑定的手机号：15943386780，手机号可能注册了其他账号，必要时可以删除该账号
  
您好，
 
感谢您的来信，根据您反馈的情况，我们需要验证当前帐号为您本人使用，请您提供以下信息至我们：
  
您的常用邮箱：
 
需要解绑的手机号：
 
绑定手机号对应的力扣账号：
 
常用登录地址：（省市）
 
常用登录设备系统：
 
常用登录浏览器：
  
在收到您的回复后，我们会提交至相关部门进行核实并向您提供的邮箱发送重置手机号联系，还请您注意查收。
 
Best Regards,
 Leetcode | Support Team

**Comment by liyuzhu-lc** [comment]
> ***@***.*** 需要解绑的手机号：18909849601 绑定手机号对应的力扣账号：https://leetcode.cn/u/zhu-65/ 常用登录地址：（省市）北京 广东省东莞市 (vpn 香港 新加坡) 常用登录设备系统：win10 win11 常用登录浏览器：谷歌浏览器 发自我的iPhone
> […](#)

您好，由于GitHub上无法显示您的邮箱，后续无法给您发重置邮件，您能否在力扣网站底部点击 问题反馈 向我们提交一个邮箱呢？

**Comment by xdefine** [comment]
已经通过问题反馈渠道提交 谢谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: liyuzhu-lc ***@***.***&gt;
发送时间: 2023年12月12日 18:05
收件人: LeetCode-Feedback/LeetCode-Feedback ***@***.***&gt;
抄送: Yuhang Pan ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [LeetCode-Feedback/LeetCode-Feedback] 为了保证账号安全，本次请使用手机验证码登录 (Issue #17688)





  
@.*** 需要解绑的手机号：18909849601 绑定手机号对应的力扣账号：https://leetcode.cn/u/zhu-65/ 常用登录地址：（省市）北京 广东省东莞市 (vpn 香港 新加坡) 常用登录设备系统：win10 win11 常用登录浏览器：谷歌浏览器 发自我的iPhone
 …
  
您好，由于GitHub上无法显示您的邮箱，后续无法给您发重置邮件，您能否在力扣网站底部点击 问题反馈 向我们提交一个邮箱呢？

**Comment by Greedfeast** [comment]
> 您好， 感谢您的来信。经过和相关技术团队核实，登录提示「为了账号安全请用账号验证码登录」是平台为了保障用户账号安全，对登录的设备数量的限制。建议您在常用设备使用常用账号哦。如需要手机号换绑服务，请提供如下信息与我们：
> 
> * 需要绑定的手机号：
> * 需要绑定的手机号对应的力扣账号：
>   收到您的回信后，会尽快移交相关人员帮您解决。
>   Best Regards,
>   Leetcode | Support Team

您好 我也需要解绑手机号，之前的手机号已经不用了，现在提示需要验证码登录，无法登录。

需要解绑的手机号：18570771551
绑定手机号对应的力扣账号：oandahouse
常用登录地址：（省市）北京市
常用登录设备系统：Windows
常用登录浏览器：chrome
辛苦尽快处理，感谢

**Comment by Greedfeast** [comment]
> > > 已换绑
> > 
> > 
> > 您好，我也需要换绑手机号： 账户：https://leetcode.cn/u/zhu-65/ 原来手机号：18909849601 需要绑定的手机号：15943386780，手机号可能注册了其他账号，必要时可以删除该账号
> 
> 您好，
> 
> 感谢您的来信，根据您反馈的情况，我们需要验证当前帐号为您本人使用，请您提供以下信息至我们：
> 
> * 您的常用邮箱：
> * 需要解绑的手机号：
> * 绑定手机号对应的力扣账号：
> * 常用登录地址：（省市）
> * 常用登录设备系统：
> * 常用登录浏览器：
> 
> 在收到您的回复后，我们会提交至相关部门进行核实并向您提供的邮箱发送重置手机号联系，还请您注意查收。
> 
> Best Regards, Leetcode | Support Team

您好 我也需要解绑手机号，之前的手机号已经不用了，现在提示需要验证码登录，无法登录。

常用邮箱35639474@qq.com
需要解绑的手机号：18570771551
绑定手机号对应的力扣账号：oandahouse
常用登录地址：（省市）北京市
常用登录设备系统：Windows
常用登录浏览器：chrome
辛苦尽快处理，感谢

**Comment by fenghaotong** [comment]
您好 我也需要解绑手机号，之前的手机号已经不用了，现在提示需要验证码登录，无法登录。
辛苦尽快处理，感谢

您的常用邮箱： 1054708869@qq.com
需要解绑的手机号：15600786890
绑定手机号对应的力扣账号：htfenght
常用登录地址：（省市）上海市
常用登录设备系统：man、win
常用登录浏览器：edge

@Nabiiiiiiiii @liyuzhu-lc

**Comment by lzwcyd** [comment]
您好 我也需要解绑手机号，之前的手机号已经不用了，现在提示需要验证码登录，无法登录。
辛苦尽快处理，感谢

您的常用邮箱： lzwcyd@gmail.com
需要解绑的手机号：18852816813
绑定手机号对应的力扣账号：https://leetcode.cn/u/lzwcyd/
常用登录地址：（省市）广东省深圳市
常用登录设备系统：man、win
常用登录浏览器：chrome,edge
@Greedfeast Greedfeast @liyuzhu-lc

**Comment by Nuygnix** [comment]
@Greedfeast 您好，我也需要换绑手机号：
力扣账号名称不记得了，微信和QQ应该都没绑定，
常用登录地址：江西赣州、江苏苏州、浙江杭州
需要解绑的手机号：17870580515
常用登录设备系统：windows10
常用登录浏览器：edge
需要绑定的手机号：15225389024，手机号可能注册了其他账号，必要时可以删除该账号
@Greedfeast 可以尽快处理一下嘛？非常感谢！

**Comment by linjinbao666** [comment]
您好 我也需要解绑手机号，之前的手机号已经不用了，现在提示需要验证码登录，无法登录。
辛苦尽快处理，感谢

您的常用邮箱： [linjinbao666@gmail.com]
需要解绑的手机号：166****4951 (不记得什么时候绑定的手机号了，可能早就不用了)
绑定手机号对应的力扣账号：linjinbao666
常用登录地址：（省市）浙江杭州 江苏淮安
常用登录设备系统：macos、windows10 
常用登录浏览器：edge、chrome

@Nabiiiiiiiii @liyuzhu-lc

**Comment by linjinbao666** [comment]
麻烦重新发下重置链接，之前的由于72小时没查看，链接过期了

您的常用邮箱： [[linjinbao666@gmail.com](mailto:linjinbao666@gmail.com)]
需要解绑的手机号：166****4951 (不记得什么时候绑定的手机号了，可能早就不用了)
绑定手机号对应的力扣账号：linjinbao666
常用登录地址：（省市）浙江杭州 江苏淮安
常用登录设备系统：macos、windows10
常用登录浏览器：edge、chrome

@Nabiiiiiiiii @liyuzhu-lc

**Comment by porscher123** [comment]
> > > 已换绑
> > 
> > 
> > 您好，我也需要换绑手机号： 账户：https://leetcode.cn/u/zhu-65/ 原来手机号：18909849601 需要绑定的手机号：15943386780，手机号可能注册了其他账号，必要时可以删除该账号
> 
> 您好，
> 
> 感谢您的来信，根据您反馈的情况，我们需要验证当前帐号为您本人使用，请您提供以下信息至我们：
> 
> * 您的常用邮箱：
> * 需要解绑的手机号：
> * 绑定手机号对应的力扣账号：
> * 常用登录地址：（省市）
> * 常用登录设备系统：
> * 常用登录浏览器：
> 
> 在收到您的回复后，我们会提交至相关部门进行核实并向您提供的邮箱发送重置手机号联系，还请您注意查收。
> 
> Best Regards, Leetcode | Support Team

您好, 我由于手机号被自动注销, 也遇到了上述问题.
希望重置手机号.本人信息如下:
您的常用邮箱：2415571314@qq.com
需要解绑的手机号：15391032419
绑定手机号对应的力扣账号 铁皮暖壶(昵称)
常用登录地址：陕西西安, 陕西渭南
常用登录设备系统：Windows, ios, ipados..
常用登录浏览器：chrome

**Comment by porscher123** [comment]
> 已换绑
你好我也需要换绑
常用邮箱:2415571314@qq.com
需要解绑的手机号:15313012419
绑定手机号对应的力扣账号铁皮暖壶(昵称), https://leetcode.cn/u/tie-pi-nuan-hu/
常用登录地址:陕西西安,陕西渭南
常用登录设备系统: Windows, ios, ipados..
常用登录浏览器: chrome

**Comment by liyuzhu-lc** [comment]
后续需要重置手机号的小伙伴我们需要验证当前帐号为您本人使用，可以点击主页「问题反馈」或者发送邮箱「support@leetcode.cn 」请您提供以下信息至我们：
- 您的常用邮箱：
- 需要重置手机号的力扣账号：
- 旧手机号：
- 新手机号：
- 常用登录地址：（省市）
- 常用登录设备系统：
- 常用登录浏览器：
在收到您的回复后，我们会提交至相关部门进行核实后，给您发重置邮件，还请注意查收您的邮箱。

**Comment by dahuaxiya** [comment]
你好，我更换了手机号码，导致无法登录
您的常用邮箱：niushaolong_cn@qq.com
需要解绑的手机号：19975260917
绑定手机号对应的力扣账号：2020GGG
常用登录地址：（省市）北京市
常用登录设备系统：mac os
常用登录浏览器：chrome
新手机号：19932719444

**Comment by chenwei9712** [comment]
您好，我也需要换绑手机号：
账户：1278528424@qq.com
原来手机号：17844629605
需要绑定的手机号：19115601649，手机号可能注册了其他账号，必要时可以删除该账号

**Comment by FuYue8** [comment]
你好，我更换了手机号码，导致无法登录
您的常用邮箱：1136786987@qq.com
需要解绑的手机号：15524321407
绑定手机号对应的力扣账号：笨小孩
常用登录地址：辽宁省
新手机号：13332419937

**Comment by RZY631** [comment]
您好，我也需要换绑
您的常用邮箱：zhuoyueren@gmail.com
需要重置手机号的力扣账号：卓越任
旧手机号：15339220362
新手机号：3472229512
常用登录地址：（省市）美国
常用登录设备系统：windows11
常用登录浏览器：chrome

**Comment by Jim-Yang778** [comment]
您好，我也需要换绑
您的常用邮箱：cyju028@qq.com
旧手机号：+61 0434621125
新手机号：13307817323

常用登录设备系统：windows11
常用登录浏览器：chrome

**Comment by JamesTensor** [comment]
您好，我也需要换绑
您的常用邮箱：wangjiajie0326@163.com
需要重置手机号的力扣账号：wjj
旧手机号：18367561845
新手机号：13269190022
常用登录地址：中国浙江/上海
常用登录设备系统：mac os
常用登录浏览器：chrome
解题数：215
绑定的QQ号：1170663408
