### ISSUE TITLE
Invalid test cases considered valid - 710. Random Pick with Blacklist

### ISSUE THREAD

**Issue by lilweege** [LeetCode-Feedback/LeetCode-Feedback#17685]
#### Your LeetCode username

lilweege

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

https://leetcode.com/problems/random-pick-with-blacklist

The problem constraint `0 <= blacklist.length <= min(10^5, n - 1)` implies that if `n <= 10^5`, then `blacklist.length <= n - 1`.

The following test case is an example where `n = 1` and `blacklist.length = 1`.
```
["Solution","pick"]
[[1,[0]],[]]
```

This should not be allowed, however no "Invalid Testcase" error is given when running this test case on leetcode.

#### Code you used for Submit/Run operation

```py
class Solution:

    def __init__(self, n: int, blacklist: List[int]):
        b = set(blacklist)
        self.sz = n - len(b)
        self.m = {}
        j = self.sz
        for x in sorted(blacklist):
            while j in b:
                j += 1
            self.m[x] = j
            j += 1

    def pick(self) -> int:
        i = randrange(self.sz)
        return self.m.get(i, i)
```

#### Language used for code

Python

#### Expected behavior

Similar to the following image, this test case should not be allowed with the message `expected 'blacklist' to have 0 <= size <= 0 but got 1`.

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/59585724/b884d079-f35a-4adf-8b00-9ee2a02f633e)

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/59585724/7b320450-b089-40fa-a695-ad60451cb714)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/59585724/8fad5c93-0638-47bb-b4a7-d93854912b48)

#### Additional context

Accepted submission link:
https://leetcode.com/problems/random-pick-with-blacklist/submissions/1087911278/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
