### ISSUE TITLE
1008. Construct Binary Search Tree from Preorder Traversal | BST definition

### ISSUE THREAD

**Issue by sergibro** [LeetCode-Feedback/LeetCode-Feedback#177]
**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
[1008. Construct Binary Search Tree from Preorder Traversal](https://leetcode.com/problems/construct-binary-search-tree-from-preorder-traversal)
Checking the correctness of [Binary Search Tree (BST)](https://en.wikipedia.org/wiki/Binary_search_tree) definition

**what language is your code written in**
Python3

**The code you submit/run**
```
# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, x):
#         self.val = x
#         self.left = None
#         self.right = None

class Solution:
    def bstFromPreorder(self, preorder: List[int]) -> TreeNode:
        root = TreeNode(preorder[0])
        for num in preorder[1:]:
            curr_node = root
            while True:
                # with/without checking `(not curr_node.right)`
                # we have different results for edge cases like [8,9,7],
                # but same `Accepted` from system
                if (not curr_node.right) and (num < curr_node.val):
                    if curr_node.left:
                        curr_node = curr_node.left
                    else:
                        curr_node.left = TreeNode(num)
                        break
                else:
                    if curr_node.right:
                        curr_node = curr_node.right
                    else:
                        curr_node.right = TreeNode(num)
                        break
        return root
```

**Expected behavior**
E.g. for input preorder traversal [8,9,7] we get the expected answer (leetcode system?) as [8,null,9,7] in which we would see that the node with value 7 is violating the BST property contract (see _Verification_ section here: [wiki](https://en.wikipedia.org/wiki/Binary_search_tree))
For that case, we should consider expecting some kind of `IMPOSSIBLE TO BUILD BST` message as output. Or, at least, notify users about 100% confident in preorder traversal correctness as input.

**Comment by CooperCooperCooper** [comment]
Hi @sergibro,
Thank you for reaching out to us! To help us assess this issue, can you please confirm that you're asking about "Construct Binary Search Tree from Preorder Traversal", which has problem number "[1008](https://leetcode.com/problems/construct-binary-search-tree-from-preorder-traversal/)" instead of "1050" on the problem's page?

**Comment by sergibro** [comment]
Hi @CooperCooperCooper,
My bad - already fixed it, thanks!

**Comment by CooperCooperCooper** [comment]
Hi @sergibro,
Thank you for the clarification. I've relayed your feedback to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
