### ISSUE TITLE
Question 69: Sqrt(x) - while loop is ignoring the break statement

### ISSUE THREAD

**Issue by akabeera** [LeetCode-Feedback/LeetCode-Feedback#17706]
#### Your LeetCode username
ssj_100

#### Category of the bug
- [ x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The break statement is being ignored, and results in a TLE.  I've confirmed in the debugger, the break statement is being hit but the programs still returns the TLE

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int mySqrt(int x) {
        // when x = 4, the while should break on the first iteration
        int left = 0;
        int right = x;
        
        while(true) {
            int mid = left + (right-left)/2;
            int root = x/mid;
            if (root == mid) {
                break;
            }
        }
        
        return 0;
    }
};
```

#### Language used for code
C++

#### Expected behavior
When x=4, while loop should break in the first iteration but I get TLE error.  I also confirmed expected behavior on Visual Studio on windows

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/52304070/dc166579-af5a-454e-9c25-5a6fd3c317c8)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/52304070/179c59a8-efba-47c0-b1d6-a7a5112752bc)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/52304070/dc6fb785-63d4-4a22-8d5a-abd6e1f5deb3)

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process. 
https://leetcode.com/submissions/detail/1088499406/
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team

**Comment by akabeera** [comment]
@LC-Pam please revisit this issue.

One difference I noticed with your evaluation is that you **submitted** the code.  In my issue, I hit the **Run** button which resulted in the issue.  I'm not sure why the judge is different from running the code but your steps is different than the reproducer I posted.  Are you able to get the output if you just run the code?  

I just copied and pasted the exact code from your link (https://leetcode.com/submissions/detail/1088499406/) and hit the run button, and I still run into the TLE exception

test case: x=4
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/52304070/5705ab23-34b8-46b7-b4da-b7a8e6f15b16)

output: TLE error
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/52304070/fbd3ffd5-0a62-470b-b3c5-c92978a03215)

Note: The expected my code to fail the judge.  

I will create another issue for this, seeing as this one is closed.
