### ISSUE TITLE
Missing Test Case - 1702. Maximum Binary String After Change

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#1770]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
A solution is accepted but fails on the following test case:

"1100"

#### Code you used for Submit/Run operation
```
class Solution {
    public String maximumBinaryString(String binary) {
        int left = 0;
        int right = 0;
        boolean flag = true;
        char[] array = binary.toCharArray();
        int length = array.length;
        for (int i = 0; i < length; i++) {
            char c = array[i];
            flag = flag && c == '1';
            left += flag && c == '1' ? 1 : 0;
            right += !flag && c == '1' ? 1 : 0;
        }

        if (left + right == 0 || right != 0) {
            int k = length - right - 1;
            for (int i = 0; i < length; i++) {
                array[i] = i == k ? '0' : '1';
            }
        }
        return new String(array);
    }
}
```

#### Language used for code
Java

#### Expected behavior
The solution should not be accepted since it fails on the test case.

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
