### ISSUE TITLE
Missing Test Case - 501. Find Mode in Binary Search Tree

### ISSUE THREAD

**Issue by bibhudutta-p** [LeetCode-Feedback/LeetCode-Feedback#17718]
#### Your LeetCode username

user6461HR

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A binary tree whose inorder traversal has a -1 at the end is not handled.

#### Code you used for Submit/Run operation

```
/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
class Solution {
public:
    vector<int> inorder;
    void dfs(TreeNode* node) {
        if (node==NULL) return;
        dfs(node->left);
        inorder.push_back(node->val);
        dfs(node->right);
    }
    vector<int> findMode(TreeNode* root) {
        int maxf = 1;
        dfs(root);
        int curf = 1;
        int cur_num = inorder[0];
        inorder.push_back(-1);
        vector<int> ans;
        for (int i = 1; i < inorder.size(); i++) {
            if (cur_num==inorder[i]) curf++;
            else {
                if (curf>maxf) {
                    maxf = curf;
                    ans.clear();
                    ans.push_back(cur_num);
                }
                else if (curf==maxf) {
                    ans.push_back(cur_num);
                }
                curf = 1;
                cur_num = inorder[i];
            }
        }
        if (ans.back()==-1) ans.pop_back();
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The expected answer is "[-1]", but my code returns "[]". Yet, my solution is "Accepted".

#### Screenshots

<img width="342" alt="Screenshot 2023-11-01 at 10 11 28 AM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/102989613/6795d844-36a3-4e01-90f0-e389ebb11a6e">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
