### ISSUE TITLE
Missing Test Case - 2569. Handling Sum Queries After Update

### ISSUE THREAD

**Issue by CuteTN** [LeetCode-Feedback/LeetCode-Feedback#17713]
#### Your LeetCode username
CuteTN

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The code below literally use brute force and get accepted in the runtime of 3 seconds, it should receive a TLE instead.

#### Code you used for Submit/Run operation
```js
/**
 * @param {number[]} nums1
 * @param {number[]} nums2
 * @param {number[][]} queries
 * @return {number[]}
 */
var handleQuery = function(nums1, nums2, queries) {
    let sum = nums2.reduce((acc, num) => acc + num, 0)
    const sums = []
    for (const query of queries) {
        if (query[0] === 1) {
            const [, l, r] = query
            for (let i = l; i <= r; i++) {
                nums1[i] = 1 - nums1[i]
            }
            continue
        }
        if (query[0] === 2) {
            sum += nums1.reduce((acc, num) => acc + num, 0) * query[1]
            continue
        }
        sums.push(sum)
    }

    return sums
};
```

#### Language used for code
JavaScript

#### Expected behavior
There should be some testcases that require many large updates.
As the input is very large, you can use the JavaScript code below to generate it:
```js
function randomInt(maxExclusive) {
  return Math.floor(Math.random() * maxExclusive);
}

let testCase1 = {
  nums1: Array(1e5).fill(0),
  nums2: Array(1e5).fill(0),
  queries: Array(1e5).fill()
}

for (let i = 0; i < 1e4; i++) {
  testCase1.nums1[randomInt(1e5)] = 1;
  testCase1.nums2[randomInt(1e5)] = randomInt(10);
}

for (let i = 0; i < 1e5; i++) {
  if (i % 1e4 == 0) testCase1.queries[i] = [3,0,0];
  else if (i % 2) {
    testCase1.queries[i] = [1, randomInt(100), 99900 + randomInt(100)];
  }
  else {
    testCase1.queries[i] = [2, randomInt(5) + 1, 0]
  }
}

// write testCase1 to a file to get the input.
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
