### ISSUE TITLE
Bug: Actual and Expected not matching but solution still accepted

### ISSUE THREAD

**Issue by regotiss** [LeetCode-Feedback/LeetCode-Feedback#17711]
#### Your LeetCode username
nomadsomad

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Question - Insert into a Cyclic Sorted List
Bug - The code is correct but the output of code result is incorrect. After submitting code, solution is accepted.

#### Code you used for Submit/Run operation

```
/**
 * Definition for a Node.
 * type Node struct {
 *     Val int
 *     Next *Node
 * }
 */

func insert(head *Node, x int) *Node {
    if head == nil {
        node := &Node{Val: x}
        node.Next = node
        return node
    }
    
    
    printList(head);
    prev, curr := head, head.Next
    
    for {
        isInBetween := prev.Val <= x && x <= curr.Val 
        isTail := prev.Val > curr.Val
        isMin := isTail && (x <= curr.Val) 
        isMax := isTail && (x >= prev.Val)
        
        if isInBetween || isMin || isMax {
            break
        }
        
        prev = curr
        curr = curr.Next
        
        if prev == head {
            break
        }
    }
    prev.Next = &Node{x, curr}
    
    return head
}

func printList(head *Node) {
    curr := head
    for {
        fmt.Print(curr.Val, " ")
        curr = curr.Next
        if curr == head {
            fmt.Println()
            return 
        }
    }
    
}
```

#### Language used for code
Go

#### Expected behavior
Please check screenshot and recording.
Code is correct. But actual test case result is not matching with expected result.

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/13028369/4c0e89d6-3ee4-404c-a743-0a64d520b177)

Tried printing the values of the circular linked list, but it is printing incorrectly.  
As you can see in below screenshot, input is [3, 3, 3] but std out showing [3, 0, 0]
<img width="756" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/13028369/0a072415-fb7c-4e18-a53f-cac7ce8da5d1">

Please check this screen recording - 
[leetcode output bug.mov.zip](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/13218599/leetcode.output.bug.mov.zip)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

You should generate test cases in the correct format: there should be NO space between the numbers inside the input array. Test cases like:
[3,3,3]
0

will get the correct result.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
