### ISSUE TITLE
Solution working in local computer, failing in LettCode compiler

### ISSUE THREAD

**Issue by culerus** [LeetCode-Feedback/LeetCode-Feedback#17715]
For challenge: https://leetcode.com/problems/reverse-bits/description/

#### Your LeetCode username
suvetma

#### Category of the bug
-  Solution

#### Description of the bug
While doing  https://leetcode.com/problems/reverse-bits/description/

I got a solution that fails in leetCode, even when it works in my local computer

#### Code you used for Submit/Run operation

```
public class Solution {

    public int reverseBits(int n) {
        StringBuilder builder = new StringBuilder();

        while( n != 0 )
        {
            if( (n & 1) == 1 )
            {
                builder.append( "1");
            }
            else
            {
                builder.append( "0" );

            }
            n = n >>> 1;
        }
        while( builder.length() < 32 )
            builder.append( "0" );
        return Integer.parseInt( builder.toString() , 2 );
    }
}
```

#### Language used for code
Java

#### Expected behavior
Compile, build, execute since the code is good

### instead

java.lang.NumberFormatException: For input string: "10111111111111111111111111111111" under radix 2
  at line 67, java.base/java.lang.NumberFormatException.forInputString
  at line 668, java.base/java.lang.Integer.parseInt
  at line 21, Solution.reverseBits
  at line 73, __Driver__.main

**Comment by LC-Pam** [comment]
Thank you for reaching out to us! Unfortunately, we are unable to troubleshoot the different behavior between your local IDE and the LeetCode environment.

For this issue, please raise this as a discuss post in the problem discuss section as other users may have run into the same issue and resolved it.

At LeetCode, we care about the whole learning experience that comes with each problem and we encourage users to teach and help each other to enrich their learning. In addition, we want our users to debug their code and learn from the process.

We appreciate your time and support.
