### ISSUE TITLE
Different judging behavior - 1707. Maximum XOR With an Element From Array

### ISSUE THREAD

**Issue by Helicopt** [LeetCode-Feedback/LeetCode-Feedback#1771]
#### Your LeetCode username
fwtt20150412

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Same code solution got TLE during contest, but got Accepted after contest. The info during contest is all testcases passed but took too long. I think this is because some judging machines are fast but others are slow. This is not fair for the contest.

#### Code you used for Submit/Run operation

```cpp
#define MAXN 300007
#define MOD 1000000007
#include <bits/stdc++.h>
using namespace std;

typedef struct node_t
{
    int cnt;
    node_t *ch[2];
} Node;

void trie_insert(Node *head, int x, int dep)
{
    head->cnt += 1;
    if (dep < 0)
        return;
    if (x & (1 << dep))
    {
        if (head->ch[1] == nullptr)
        {
            head->ch[1] = new Node();
            head->ch[1]->cnt = 0;
            head->ch[1]->ch[0] = nullptr;
            head->ch[1]->ch[1] = nullptr;
        }
        trie_insert(head->ch[1], x, dep - 1);
    }
    else
    {
        if (head->ch[0] == nullptr)
        {
            head->ch[0] = new Node();
            head->ch[0]->cnt = 0;
            head->ch[0]->ch[0] = nullptr;
            head->ch[0]->ch[1] = nullptr;
        }
        trie_insert(head->ch[0], x, dep - 1);
    }
}

void trie_destroy(Node *head)
{
    if (head->ch[0] != nullptr)
    {
        trie_destroy(head->ch[0]);
        head->ch[0] = nullptr;
    }
    if (head->ch[1] != nullptr)
    {
        trie_destroy(head->ch[1]);
        head->ch[1] = nullptr;
    }
    delete head;
}

int trie_search(Node *head, int x, int dep, int pfx)
{
    if (dep < 0)
        return pfx;
    int bit = (x & (1 << dep)) >> dep;
    if (head->ch[!bit] != nullptr && head->ch[!bit]->cnt > 0)
    {
        return trie_search(head->ch[!bit], x, dep - 1, pfx | (1 << dep));
    }
    if (head->ch[bit] != nullptr && head->ch[bit]->cnt > 0)
    {
        return trie_search(head->ch[bit], x, dep - 1, pfx);
    }
    return -1;
}

class Solution
{
public:
    vector<int> maximizeXor(vector<int> &nums, vector<vector<int>> &queries)
    {
        sort(nums.begin(), nums.end());
        vector<int> inds;
        inds.clear();
        for (int i = 0; i < queries.size(); ++i)
            inds.push_back(i);
        sort(inds.begin(), inds.end(), [&queries](int a, int b) {
            return queries[a][1] < queries[b][1];
        });
        Node *head = new Node();
        head->cnt = 0;
        head->ch[0] = nullptr;
        head->ch[1] = nullptr;
        int ptr = 0;
        vector<int> ans(queries.size(), -1);
        for (int i = 0; i < queries.size(); ++i)
        {
            int ind = inds[i];
            int x = queries[ind][0];
            int m = queries[ind][1];
            while (ptr < nums.size() && nums[ptr] <= m)
            {
                trie_insert(head, nums[ptr], 30);
                ptr += 1;
            }
            int a = trie_search(head, x, 30, 0);
            ans[ind] = a;
        }
        trie_destroy(head);
        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior
It shall behave the same during and after contest.

#### Screenshots
TLE submission code
SHA1: 536D6F947A4956AF2F34AE47EA51F71148F5C08F
![image](https://user-images.githubusercontent.com/8593583/103163831-6a6fd280-4857-11eb-8937-405564f1b892.png)
![image](https://user-images.githubusercontent.com/8593583/103163842-7b204880-4857-11eb-83b4-663543c5c713.png)

Accepted submission code
SHA1: 536D6F947A4956AF2F34AE47EA51F71148F5C08F
![image](https://user-images.githubusercontent.com/8593583/103163857-a9058d00-4857-11eb-942d-b20857a5010b.png)
![image](https://user-images.githubusercontent.com/8593583/103163862-b3278b80-4857-11eb-82db-8a2938cbd5cc.png)

#### Additional context
I don't know what the time limit exactly is, but for the accepted solution, it consumes 1500ms, and I find that other accepted solutions are up to 1720ms. This means same solution runs in two different ways (1500ms and 1720 +), this difference is 220ms +, this is not acceptable, it's unfair for the contest.

**Comment by lc-kay** [comment]
Hi @Helicopt 
Thank you for your time. We've noted your feedback and our contest team will certainly investigate and work on a solution for future contests.
