### ISSUE TITLE
Missing Test Case - 74. Search a 2D Matrix

### ISSUE THREAD

**Issue by AryanSingh11** [LeetCode-Feedback/LeetCode-Feedback#17719]
missing testcase: 
matrix = [[0],[1],[2],[3]]
target = 3

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x] Missing Test Cases 

#### Description of the bug
I am just contributing a test case that might help people create more concise code

#### Code you used for Submit/Run operation

```
//search in 2D matrix
class Solution {
public:
    bool searchMatrix(vector<vector<int>>& matrix, int target) {

        bool ans = false;
        int rowsize = matrix.size();
        int colsize = matrix[0].size();

        //find the row in which the target is contained
        int targetrow = 0;
        for(int i =0; i<rowsize; i++){
            if(matrix[i][0]<=target && matrix[i][colsize-1]>=target){
                targetrow = i;
                cout<<"target is in row: "<<i<<endl;
                break;
            }
        }

        //apply bs in the target row
        int start = 0;
        int end =  colsize-1;
        int mid = start + ((end-start)/2);
        cout<<"first mid "<<mid<<endl;
        while(start<=end){
            if(matrix[targetrow][mid]< target){
                start = mid+1;
            }else if (matrix[targetrow][mid] > target){
                end = mid-1;
            }else{ //equal
                ans = true;
                cout<<"found it at: matrix ";
                cout<<targetrow<<" "<<mid<<": "<<matrix[targetrow][mid]<<endl;
                return true;
            }

            mid = start + ((end-start)/2);
        }

        return ans;

    }
};
```

#### Language used for code:
C++

#### Expected behavior
should be able to find 3 and return true

#### Screenshots

<img width="134" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/88196222/26bf6f4a-c6a5-405c-9312-c8a46715fc3a">

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

 [[0],[1],[2],[3]]
3
already exists. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
