### ISSUE TITLE
Missing Test Case - 50. Pow(x, n)

### ISSUE THREAD

**Issue by AryanSingh11** [LeetCode-Feedback/LeetCode-Feedback#17725]
#### Your LeetCode username
AryanSingh11

#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [x] Missing Test Cases 

#### Description of the bug

n varies from -2 raised to power 31. I want to add n = -2^31
n = -2147483648, x = -1

few solutions would make mistake of doing n-- in while loop and that's when an overflow would occur and 
an error would be thrown.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    double myPow(double x, int n) {
        if(x==1.0 || x==0){
            return x;
        }
        
        double ans = 1.0;
        long long nn = n;
        if(n<0) nn = abs(n)*1LL;
        while(nn){
            if(nn%2)//nn is odd
            {
                ans = ans*x;
                --nn;
            }else{ //nn is even
                x = x*x;
                nn = nn/2;
            }
        }

        if(n<0) return (double)1.0/(double)ans;
        return ans;

    }
};
```

#### Language used for code
 C++ 

#### Expected behavior

should throw 1.000 as answer as attached in ss.
<img width="211" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/88196222/f4c1f87e-fe77-444f-a48c-3250b6f54de0">

#### Screenshots

<img width="211" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/88196222/53afc9de-0a23-4f06-a649-3238f5ba71e2">

**Comment by stormsunshine** [comment]
The code you provide returns the correct result. What is the code that does not return the correct result, either returns an incorrect result or throws a runtime exception?

**Comment by AryanSingh11** [comment]
This is the improved code. But my previous code used -
```
n = abs(n);
while(n--)
```
and abs(n) would give overflow error since n = -2147483648 couldn't be stored in positive side of int.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
