### ISSUE TITLE
169. 多数元素增加进阶要求

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#1772]
**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
第 169 题有多种解法，但是面试的时候可能要求给出时间复杂度 O(n) 和空间复杂度 O(1) 的解法，即摩尔投票算法。
因此建议在题目描述中增加进阶要求。
中文描述是：
**进阶：**
尝试设计时间复杂度为 O(n)、空间复杂度为 O(1) 的算法解决此问题。
英语描述是：
**Follow-up:** Could you solve the problem in linear time and in O(1) space?

**你使用的语言**
Java

**你提交或者运行的代码**

**期望行为**
题目描述中增加进阶要求，中文描述和英语描述需要同步更新。

**屏幕截图**

**额外的上下文**

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，题目已更新。
