### ISSUE TITLE
1705 Maximum Number of Eaten Apples missing test case?

### ISSUE THREAD

**Issue by VasE1980** [LeetCode-Feedback/LeetCode-Feedback#1773]
#### Your LeetCode username
VasE2020

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
1705 Maximum Number of Eaten Apples missing test case?
[3,0,0,1,2]
[6,0,0,3,2]
My assepted solution returns 5 instead of 6.
Unless this test case is missing on purpose, I have not dealt with the new rules.

#### Code you used for Submit/Run operation

```
class Solution {
    public int eatenApples(int[] apples, int[] days) {
        int rV = 0;

        PriorityQueue<int[]> pq0 = new PriorityQueue<>((a,b)->b[1] - a[1]);
        PriorityQueue<int[]> pq1 = new PriorityQueue<>((a,b)->b[0] - a[0]);
        int d0 = Integer.MAX_VALUE;
        int d1 = Integer.MIN_VALUE;

        for(int i = 0; i < apples.length; i++) {
            if (apples[i] > 0) {
                pq0.add(new int[]{i, i + days[i] - 1, apples[i]});
                d0 = Math.min(d0, i);
                d1 = Math.max(d1, i + days[i] - 1);
            }
        }

        for(int i = d1; i >= d0; i--) {
            if(!pq0.isEmpty()) {
                if (pq0.peek()[1] >= i)
                    pq1.add(pq0.poll());
            }
            //if(!pq1.isEmpty()) {
                while(!pq1.isEmpty() && (pq1.peek()[0] > i || pq1.peek()[2] == 0))
                    pq1.poll();
                if (!pq1.isEmpty()) {
                    rV++;
                    pq1.peek()[2]--;
                }
            //}
        }

        return rV;
    }
}
```

#### Language used for code
Java

#### Expected behavior
The solution shouldn't have passed the test.

#### Screenshots
![изображение](https://user-images.githubusercontent.com/59063496/103164091-c3b81180-4817-11eb-9b45-c9073a4b9f04.png)

**Comment by lc-kay** [comment]
Hi @VasE1980 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @VasE1980 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
