### ISSUE TITLE
Test Case Wrong - 205. Isomorphic Strings

### ISSUE THREAD

**Issue by bck2302000** [LeetCode-Feedback/LeetCode-Feedback#17734]
#### Your LeetCode username
b04502005

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [V] Missing Test Cases 

#### Description of the bug

The last test case (test case 48) is wrong. 
s =
"12"

t =
"\u0067\u0068"

Output
false

Expected
true

#### Code you used for Submit/Run operation

```
bool isIsomorphic(string s, string t) {
        if (s.size() != t.size())
            return false;
        unordered_map<char, char> hash1, hash2;
        for (int i = 0; i < s.size(); i++) {
            if (hash1.count(t[i]) || hash2.count(s[i])) {
                if (hash1[t[i]] != s[i])
                    return false;
            }
            else {
                hash1[t[i]] = s[i];
                hash2[s[i]] = t[i];
            }
        }
        return true;
    }
```

#### Language used for code

C++

#### Expected behavior

It should pass all of the test cases.
The last test case contains the 2 inputs which are of different sizes. 
In this case, it's impossible to make them isomorphic strings. 
So the output of this test case should be false. 

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/43664240/fbcd27fe-57ff-45a9-bec0-b14556275088)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by KernelA** [comment]
I have the same issue with C++. Solution on Python 3 passes all test cases.

https://leetcode.com/problems/isomorphic-strings/submissions/1090167689

**Comment by Gindeles** [comment]
I have the same issue with C++.
https://leetcode.com/problems/isomorphic-strings/submissions/1090172725/

**Comment by bck2302000** [comment]
> Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
> 
> The code submission Accepted link.
> 
> We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

https://leetcode.com/problems/isomorphic-strings/submissions/1089215682/
Here's the link to my submitted solution. 
Thank you very much!

**Comment by JigyarthJoshi** [comment]
> #### Your LeetCode username
> b04502005
> 
> #### Category of the bug
> * [ ]  Question
> * [ ]  Solution
> * [ ]  Language
> * [V] Missing Test Cases
> 
> #### Description of the bug
> The last test case (test case 48) is wrong. s = "12"
> 
> t = "\u0067\u0068"
> 
> Output false
> 
> Expected true
> 
> #### Code you used for Submit/Run operation
> ```
> bool isIsomorphic(string s, string t) {
>         if (s.size() != t.size())
>             return false;
>         unordered_map<char, char> hash1, hash2;
>         for (int i = 0; i < s.size(); i++) {
>             if (hash1.count(t[i]) || hash2.count(s[i])) {
>                 if (hash1[t[i]] != s[i])
>                     return false;
>             }
>             else {
>                 hash1[t[i]] = s[i];
>                 hash2[s[i]] = t[i];
>             }
>         }
>         return true;
>     }
> ```
> 
> #### Language used for code
> C++
> 
> #### Expected behavior
> It should pass all of the test cases. The last test case contains the 2 inputs which are of different sizes. In this case, it's impossible to make them isomorphic strings. So the output of this test case should be false.
> 
> #### Screenshots
> ![image](https://user-images.githubusercontent.com/43664240/279730594-fbcd27fe-57ff-45a9-bec0-b14556275088.png)
> 
> #### Additional context

Yes I am also facing the same issue and only 45/47 testcases are passing. Here is the link to my solution-> https://leetcode.com/problems/isomorphic-strings/submissions/1090515089

**Comment by noshgraph** [comment]
same over here also in C++: https://leetcode.com/problems/isomorphic-strings/submissions/1093178654/?source=submission-noac

**Comment by darkworldz** [comment]
Leetcode >same issue here, its the buggy test case number 46 which reproduces this as TRUE  :- s = "12" 
t = "\u0067\u0068" 
same problem got submitted on GFG without any issue

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by suryamsriv** [comment]
Hi All,

The test case seems to be valid one as the unicode values "**\u0067\u0068**" correspond to value of "**gh**", in which case the input string "**12**" if replaced will be an isomorphic string.
Similarly "**\u0067\u0068\u0068**" should be a valid isomorphic output string for "**122**" as input.

For me the test cases seems to have passed when I submitted the following code in Java.

`class Solution {
    public boolean isIsomorphic(String s, String t) {
        int sLength = s.length();
        if(sLength != t.length())
            return false;
        Map<Character, Character> isoMap = new HashMap<>();
        for(int i=0; i < sLength; i++) {
            if(isoMap.containsKey(s.charAt(i)))
            {
                if(isoMap.get(s.charAt(i)) != t.charAt(i))
                    return false;
            }
            else {
                isoMap.put(s.charAt(i), t.charAt(i));
            }
        }
        StringBuilder output = new StringBuilder();
        for(int i=0; i<sLength; i++) {
            output.append(isoMap.get(s.charAt(i)));
        }
        if(!output.toString().equals(t))
            return false;
        return true;
    }
}`


<img width="736" alt="Screenshot 2024-05-23 at 10 35 57 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/96463787/b51869e9-8aea-4749-9d8b-b2f0724ca02c">
