### ISSUE TITLE
Wrong Test Case - 10. Regular Expression Matching

### ISSUE THREAD

**Issue by Rahul99sh** [LeetCode-Feedback/LeetCode-Feedback#17732]
#### Your LeetCode username

sharmarahul2101

#### Category of the bug
- [-] Wrong test case

#### Description of the bug

question has wrong test case

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool solve(string &str, string &pat, int i, int j, vector<vector<int>>&dp){
        if(i>= str.length() && j>= pat.length()) return true;
        if(i< str.length() && j>= pat.length()) return false;
        if(i>= str.length() && j< pat.length()){
            while(j<pat.length()){
                if(pat[j] != '*') return false;
                j++;
            }
            return true;
        }
        if(dp[i][j] != -1) return dp[i][j];
        if(str[i] == pat[j] || pat[j] == '.'){
            return dp[i][j] = solve(str,pat, i+1,j+1,dp);
        }else if(pat[j] == '*'){
            return dp[i][j] = (solve(str,pat,i+1,j,dp) || solve(str,pat,i,j+1,dp));
        }else{
            return dp[i][j] = false;
        }
    }
    bool isMatch(string s, string p) {
        vector<vector<int>>dp(s.length(), vector<int>(p.length(), -1));
        return solve(s,p,0,0,dp);
    }
};

```

#### Language used for code

C++

#### Expected behavior

test case : s = "aab", p="c*a*b"
my output : false
expected output : true

as we can see from first char c != a hence it should be false

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/109263669/75307fea-2173-4620-9606-91ca95500acd)

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
