### ISSUE TITLE
Question 69: Sqrt(x) - while loop is ignoring the break statement #17706

### ISSUE THREAD

**Issue by akabeera** [LeetCode-Feedback/LeetCode-Feedback#17730]
#### Your LeetCode username
ssj_100

#### Category of the bug
- [ x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Follow up of https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/17706 which was closed prematurely so creating a new issue.

The break statement is being ignored, and results in a TLE.  I've confirmed in the debugger, the break statement is being hit but the programs still returns the TLE

NOTE: Please **RUN** the code, and DON"T submit the code.  As mentioned in [comments](https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/17706#issuecomment-1789026478), Submit works, but Run doesn't 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int mySqrt(int x) {
        // when x = 4, the while should break on the first iteration
        int left = 0;
        int right = x;
        
        while(true) {
            int mid = left + (right-left)/2;
            int root = x/mid;
            if (root == mid) {
                break;
            }
        }
        
        return 0;
    }
};
```

#### Language used for code
C++

#### Expected behavior
When x=4, while loop should break in the first iteration but I get TLE error.  I also confirmed expected behavior on Visual Studio on windows

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/52304070/dc166579-af5a-454e-9c25-5a6fd3c317c8)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/52304070/179c59a8-efba-47c0-b1d6-a7a5112752bc)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/52304070/dc6fb785-63d4-4a22-8d5a-abd6e1f5deb3)

**Comment by LC-Pam** [comment]
\
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

Please ask your question in the discussion forum.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by akabeera** [comment]
Hi @LC-Pam 

So what's the conclusion of this issue?
