### ISSUE TITLE
Missing Test Case - 1179. Reformat Department Table

### ISSUE THREAD

**Issue by Abdalrhman-Mohammad** [LeetCode-Feedback/LeetCode-Feedback#17740]
#### Your LeetCode username
AbdalrhmanMohammad

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ X] Missing Test Cases 

#### Description of the bug
Some codes get accepted in the problem , but it is take wrong on some cases not exist in the test cases.

#### Code you used for Submit/Run operation

```
// Reformat Department Table

SELECT id 
, if(SUM(CASE WHEN month='Jan' THEN revenue ELSE 0 END)=0,null,SUM(CASE WHEN month='Jan' THEN revenue ELSE 0 END))  AS Jan_Revenue
, if(SUM(month='Feb')=0,null,SUM(CASE WHEN month='Feb' THEN revenue ELSE 0 END) ) AS Feb_Revenue
, if(SUM(month='Mar')=0,null,SUM(CASE WHEN month='Mar' THEN revenue ELSE 0 END) ) AS Mar_Revenue
, if(SUM(month='Apr')=0,null,SUM(CASE WHEN month='Apr' THEN revenue ELSE 0 END) ) AS Apr_Revenue
, if(SUM(month='May')=0,null,SUM(CASE WHEN month='May' THEN revenue ELSE 0 END) ) AS May_Revenue
, if(SUM(month='Jun')=0,null,SUM(CASE WHEN month='Jun' THEN revenue ELSE 0 END) ) AS Jun_Revenue
, if(SUM(month='Jul')=0,null,SUM(CASE WHEN month='Jul' THEN revenue ELSE 0 END) ) AS Jul_Revenue
, if(SUM(month='Aug')=0,null,SUM(CASE WHEN month='Aug' THEN revenue ELSE 0 END) ) AS Aug_Revenue
, if(SUM(month='Sep')=0,null,SUM(CASE WHEN month='Sep' THEN revenue ELSE 0 END) ) AS Sep_Revenue
, if(SUM(month='Oct')=0,null,SUM(CASE WHEN month='Oct' THEN revenue ELSE 0 END) ) AS Oct_Revenue
, if(SUM(month='Nov')=0,null,SUM(CASE WHEN month='Nov' THEN revenue ELSE 0 END) ) AS Nov_Revenue
, if(SUM(month='Dec')=0,null,SUM(CASE WHEN month='Dec' THEN revenue ELSE 0 END) ) AS Dec_Revenue
FROM Department
GROUP BY id

```

#### Language used for code

MySQL

#### Expected behavior
The code that I put it must got wrong on bellow test case ,But when i submit the code it is took Accepted.

| id | revenue | month |
| -- |    -------   |   -----   |
| 1 |       0       |   Jan   |

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/118562424/fabe9752-24e1-48f8-acd3-522673fef2ad)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've used your feedback to update the problem.

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback.

Please provide us your Leetcode Username .

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!

**Comment by Abdalrhman-Mohammad** [comment]
My username : AbdalrhmanMohammad

**Comment by Abdalrhman-Mohammad** [comment]
My username : AbdalrhmanMohammad

**Comment by LC-Pam** [comment]
Hi there,

The user "AbdalrhmanMohammad" cannot be found. Would you mind provide us your profile link?

Thank you.

**Comment by Abdalrhman-Mohammad** [comment]
https://leetcode.com/AbdalrhmanALMohammad/

**Comment by LC-Pam** [comment]
Rewarded to the "AbdalrhmanALMohammad"
