### ISSUE TITLE
Description improvement - 570. Managers with at Least 5 Direct Reports

### ISSUE THREAD

**Issue by xelplogoog** [LeetCode-Feedback/LeetCode-Feedback#17743]
#### Your LeetCode username
c4tdog

#### Description of the bug
Description says the managerId could be `null`, but example uses `None` instead

<img width="770" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2188302/25c07e96-3cf0-4489-b399-feef08897234">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
