### ISSUE TITLE
Missing Test Case - 1057. Campus Bikes

### ISSUE THREAD

**Issue by Ming91** [LeetCode-Feedback/LeetCode-Feedback#17745]
#### Your LeetCode username

[wming9310](https://leetcode.com/wming9310)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

In short, my solution should be slow but it is fast. So I generated a test case to show that. Here is my explanation:

I found a pretty fast solution to this problem in the submissions. It uses a greedy approach and iterates all bikes if the current `bike` is not available in the `[worker, bike]` pairs. The time complexity is $O(NMlog(N))$ but it runs faster than the bucket sorting method which is only $O(NM+K)$ complexity.

So I think the test cases must lack the worst case for this greedy approach, which is "All workers share the same nearest bike". Here is the test case I constructed. In this test case, all workers have the same distance to each bike.

[1057TestCase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/13232948/1057TestCase.txt)

#### Code you used for Submit/Run operation

```java
// The greedy approach
class Solution {
    int getDistance(int[] x, int[] y) {
        return Math.abs(x[0] - y[0]) + Math.abs(x[1] - y[1]);
    }
    Comparator<int[]> workerBikeComparator
        = new Comparator<int[]>() {
            @Override
            public int compare(int[] a, int[] b) {
                for (int i = 2; i >= 0; i--) {
                    if (a[i] != b[i]) {
                        return Integer.compare(a[i], b[i]);
                    }
                }
                return 0;
            }
        };
    public int[] assignBikes(int[][] workers, int[][] bikes) {
        int n = workers.length;
        int m = bikes.length;
        int[] workerStatus = new int[n];
        boolean[] bikeStatus = new boolean[m];
        Queue<int[]> pq = new PriorityQueue<>(workerBikeComparator);
        for (int i = 0; i < n; i++) {
            int min = 1999;
            int minIdx = -1;
            for (int j = 0; j < m; j++) {
                int dist = getDistance(workers[i], bikes[j]);
                if (min > dist) {
                    min = dist;
                    minIdx = j;
                }
            }
            pq.add(new int[] {minIdx, i, min});
        }
        while (!pq.isEmpty()) {
            int[] curr = pq.poll();
            if (!bikeStatus[curr[0]]) {
                workerStatus[curr[1]] = curr[0];
                bikeStatus[curr[0]] = true;
                continue;
            }
            int min = 1999;
            int minIdx = -1;
            for (int j = 0; j < m; j++) {
                if (bikeStatus[j]) {
                    continue;
                }
                int dist = getDistance(workers[curr[1]], bikes[j]);
                if (min > dist) {
                    min = dist;
                    minIdx = j;
                }
            }
            pq.add(new int[] {minIdx, curr[1], min});
        }
        return workerStatus;
    }
}
```

#### Language used for code

Java

#### Screenshots

The greedy approach took 14ms for submission but took 200+ms for this test case.
The submission link:  https://leetcode.com/submissions/detail/1089524967/
![Screenshot 2023-11-01 205412](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/3740139/8bd100c0-497b-4cc1-9a3a-b081c50ca922)

The bucket sort approach took 40ms for submission and just took 18ms for this test case.
The submission link: https://leetcode.com/submissions/detail/1089524637/
![Screenshot 2023-11-01 205327](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/3740139/39133f6c-c0e1-4ed1-9ca2-fb7524f9ae4d)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
