### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by Kevinaaaaqw** [LeetCode-Feedback/LeetCode-Feedback#17748]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
   var twoSum = function (nums, target) {
    let res = []
    nums.forEach((i, ind, arr) => {
        arr.forEach((item, index) => {
            if (ind !== index) {
                i + item === target && (res[0] = (ind), res[1] = (index))
            }
        })
    })
    return res.sort((a, b) => {
        return a > b ? 1 : -1
    })
};
```

**Comment by Kevinaaaaqw** [comment]
第一次用

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The language you submitted to reach this result.
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Kevinaaaaqw** [comment]
> #### Your LeetCode username
> #### Category of the bug
> * [ ]  Question
> * [x]  Solution
> * [ ]  Language
> * [ ]  Missing Test Cases
> 
> #### Description of the bug
> #### Code you used for Submit/Run operation
> ```
> // Two Sum
> class Solution {
> public:
>    var twoSum = function (nums, target) {
>     let res = []
>     nums.forEach((i, ind, arr) => {
>         arr.forEach((item, index) => {
>             if (ind !== index) {
>                 i + item === target && (res[0] = (ind), res[1] = (index))
>             }
>         })
>     })
>     return res.sort((a, b) => {
>         return a > b ? 1 : -1
>     })
> };
> ```
> 
> #### Language used for code
> #### Expected behavior
> #### Screenshots
> #### Additional context
