### ISSUE TITLE
Wrong Evaluation - 368. Largest Divisible Subset

### ISSUE THREAD

**Issue by kanurag94** [LeetCode-Feedback/LeetCode-Feedback#1775]
#### Your LeetCode username
kanurag94

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Any valid subset should be accepted in this problem. While running for test case
Input:
[5,9,18,54,108,540,90,180,360,720]
Output:
[5,18,90,180,360,720]
Expected:
[9,18,90,180,360,720]

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<int> largestDivisibleSubset(vector<int>& nums) {
        int n = nums.size();
        vector<int> dp(n, 1);
        sort(nums.begin(), nums.end());
        vector<int> ans;
        int mx = INT_MIN;
        for(int i=0; i<n; i++){
            vector<int> temp;
            for(int j=0; j<i; j++){
                if(nums[i]%nums[j]==0 and dp[i]<dp[j]+1){
                    dp[i]=dp[j]+1;
                    temp.push_back(nums[j]);
                }
            }
            temp.push_back(nums[i]);
            if(dp[i]>mx){
                mx = dp[i];
                ans=temp;
            }
        }
        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior

The answer should be accepted.

**Comment by lc-kay** [comment]
Hi @kanurag94 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@kanurag94 Our team has reviewed the issue and concluded that the checker is correct. Since 5 % 18 != 0 and 18 % 5 != 0. We recommend checking out the discuss tab of this problem to reference correct solutions.
