### ISSUE TITLE
Typo in hint: 1770. Maximum Score from Performing Multiplication Operations

### ISSUE THREAD

**Issue by Leader-board** [LeetCode-Feedback/LeetCode-Feedback#17753]
#### Your LeetCode username

Leaderboard

#### Category of the bug
- [ ] Question
- [ ] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug

Hint 2 says that 

> You should try all scenarios but this will be costy.

"costy" has a typo

#### Code you used for Submit/Run operation
NA

#### Language used for code
NA

#### Expected behavior

It should be "costly"

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
