### ISSUE TITLE
Question - 2265. Count Nodes Equal to Average of Subtree

### ISSUE THREAD

**Issue by regotiss** [LeetCode-Feedback/LeetCode-Feedback#17752]
#### Your LeetCode username
nomadsomad

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Question description says - The average of n elements is the sum of the n elements divided by n and rounded down **to the nearest integer**.

Usual assumption for nearest integer - e.g.
10 / 3 = 3.333 = 3
15 / 4 = 3.75 = 4

But the solution is not accepted if rounded to the nearest integer. It expects the 15/4 to be 3 as its nearest integer. 

#### Code you used for Submit/Run operation

```go
/**
 * Definition for a binary tree node.
 * type TreeNode struct {
 *     Val int
 *     Left *TreeNode
 *     Right *TreeNode
 * }
 */
func averageOfSubtree(root *TreeNode) int {
    var cnt int
    averageCnt(root, &cnt)
    return cnt
}

func averageCnt(root *TreeNode, cnt *int) (int, int) {
    if root == nil {
        return 0, 0
    }
    sumL, nL := averageCnt(root.Left, cnt)
    sumR, nR := averageCnt(root.Right, cnt)

    sum, n := root.Val + sumL + sumR, nL+nR+1
    avg := average(sum, n)
    fmt.Println(avg, root.Val)
    if root.Val == avg {
        *cnt++
    }

    return sum, n
}


func average(sum, n int) int {
    return int(float32(sum)/float32(n) + 0.5)
}


```

#### Language used for code
Golang

#### Expected behavior
Nearest integer should be close integer i.e. if float value is 4.66 then round of integer is 5. Or question description should be changes saying that average float value should be always floored. floor(4.66) = 4
instead of mentioning the nearest integer. 

#### Screenshots
<img width="521" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/13028369/2a025844-9e5a-4762-8a03-d2bc460ca026">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by Leader-board** [comment]
> rounded down

That answers your question. 15/4 is 

* 3.75
* 4 when rounded to the nearest integer
* 4 when rounded up to the nearest integer
* 3 when rounded down

13/4 is 

* 3.25
* 3 when rounded to the nearest integer
* 4 when rounded up to the nearest integer
* 3 when rounded down to the nearest integer

Rounding down is analogous to finding the floor.

**Comment by regotiss** [comment]
Got it, I see that rounded down is highlighted in the problem description now. Maybe I missed it. Thanks for the explanation.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
