### ISSUE TITLE
Missing Test Case - 1441. Build an Array With Stack Operations

### ISSUE THREAD

**Issue by AryanSingh11** [LeetCode-Feedback/LeetCode-Feedback#17767]
#### Your LeetCode username
AryanSingh11

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I'd like this question to have more testcases

```
//test1
target = [4,5,8,9,10,11,12,13,17]
n=19
```
```
//test2
target = [3,12]
n=12
```
```
//test3
target = [6,7,8,9,12,14]
n = 15
```

#### Code you used for Submit/Run operation

```
// build array with stack operation
class Solution {
public:
    vector<string> buildArray(vector<int>& target, int n) {
        //creating nums array
        vector<int> nums;
        for(int i =0; i<n; i++){
            nums.push_back(i+1);
        }
        //answer array
        vector<string> ans;

        //temp array to see structure of stack
        vector<int> temp;

        //tracker for nums array
        int numstracker = 0; //index 0

        //tracker for target array
        int targettracker = 0; //index 0

        while(temp!=target){
            //step1: push
            temp.push_back(nums[numstracker]);
            ans.push_back("Push");
            numstracker++;

            //step2: check if pushed item was required
            if(temp.back()==target[targettracker]){
                //yes the elem is in target
                targettracker++;
            }else{
                //no elem is not in target //not required
                temp.pop_back();
                ans.push_back("Pop");
            }
        }
        return ans;
    }
};
```

#### Language used for code
 C++ 

#### Expected behavior

<img width="960" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/88196222/87768d6a-3025-4a73-b4b2-e4aabbe71db1">

#### Screenshots

<img width="960" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/88196222/a5710c44-c599-4cc0-ba0f-a0de6239a525">

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The above test cases all already exist. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
