### ISSUE TITLE
2265. Count Nodes Equal to Average of Subtree

### ISSUE THREAD

**Issue by Vikasss7663** [LeetCode-Feedback/LeetCode-Feedback#17760]
#### Your LeetCode username
cs_iitian

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

This code is more clear and concise then in editorial, here we don't need global variable to track ans, instead we can return three variabls -> (sum, count, ans) everytime average of subtree matches the node's value we can increment ans and return.

#### Code you used for Submit/Run operation

```java []
class Solution {

    public int averageOfSubtree(TreeNode root) {
        return helper(root)[2];
    }

    public int[] helper(TreeNode root) {
        if(root == null) return new int[] {0, 0, 0};

        int[] left = helper(root.left);
        int[]  right = helper(root.right);
        
        int sum = left[0] + right[0] + root.val;
        int count = left[1] + right[1] + 1;
        
        return new int[] {sum, count, left[2] + right[2]  + (sum/count == root.val ? 1 : 0)};
    }
}
```

#### Language used for code
java

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/98081274/d16acc21-a5bf-493b-9487-0726c5beea80)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

This is just another implementation. There is no problem with the original editorial that has ans as a global variable. Both implementations are commonly used.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
