### ISSUE TITLE
Missing Test Case - 1723. Find Minimum Time to Finish All Jobs

### ISSUE THREAD

**Issue by Andrew-Angrew** [LeetCode-Feedback/LeetCode-Feedback#17779]
#### LeetCode username
[Andrew-Angrew](https://leetcode.com/Andrew-Angrew)

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
I'have devised a testcase on which fails one of the posted solutions:
https://leetcode.com/problems/find-minimum-time-to-finish-all-jobs/solutions/3792844/beats-100-simplest-and-best-solution-ever-existed/

The testcase: [8,6,5,5,4,4], k=2

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
