### ISSUE TITLE
Missing Test Case - 1705. Maximum Number of Eaten Apples 

### ISSUE THREAD

**Issue by AJAYKR00KJ** [LeetCode-Feedback/LeetCode-Feedback#1777]
#### Category of the bug
- [ ] Question
- [✔️ ] Solution
- [ ] Language

#### Code you used for Submit/Run operation
The following code was accepted successfully, but for the test case 
[1,10, 17, 10, 12, 6, 20, 8, 8, 22, 14,   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,2,3,5,2,1,0,0,0,0,0,0,23]
[19999,11, 18, 22, 5, 2, 14, 5, 20, 7, 17,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,2,1,4,2,7,0,0,0,0,0,0,1]
we got the output result 40 and the expected result is 37 which were not consistent.

```
class Solution {
public:
    int eatenApples(vector<int>& A, vector<int>& days) {
        int res = 0, eat = 0, n = A.size(), count[50000] = {};
        for (int i = 0; i < 50000; ++i) {
            int tmp = eat + count[i];
            eat = max(tmp, 0);
            count[i] = min(tmp, 0);
            if (i < n) {
                count[i] += A[i];
                count[i+days[i]] -= A[i];
            }
            count[i] += i > 0 ? count[i-1] : 0;
            if (count[i] > 0) {
                res++;
                eat++;
                count[i]--;
            }
        }
        return res;
    }
};
```

#### Language used for code
C++

#### Expected behavior
Please add the test cases 
[1,10, 17, 10, 12, 6, 20, 8, 8, 22, 14,   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,2,3,5,2,1,0,0,0,0,0,0,23]
[19999,11, 18, 22, 5, 2, 14, 5, 20, 7, 17,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,2,1,4,2,7,0,0,0,0,0,0,1]

#### Screenshots

![nw](https://user-images.githubusercontent.com/48375037/103165589-e78f4d80-483f-11eb-93e5-c6c538d292b0.png)

#### Additional context
Add the test cases.

**Comment by lc-kay** [comment]
Hi @AJAYKR00KJ 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @AJAYKR00KJ 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
