### ISSUE TITLE
Though network works fine, throwing "Unknown network error" for one usecase while running the code

### ISSUE THREAD

**Issue by SwethaSelva** [LeetCode-Feedback/LeetCode-Feedback#17774]
## Your LeetCode username

swethalakshmi64

## Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

## Description of the bug

Getting "Unknown network error" while running the code.

### Ways to reproduce the bug

1. In first tab, open the question in the below way. "Code" tab should not be opened / active.
<img width="1499" alt="Screenshot 2023-11-03 at 9 56 49 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/58015008/8f34943c-2383-4234-b6f7-792e268db385">

2. Go to "similar question" section and open it in **new tab**

3. When the new tab is open, by default "code" is inactive and you get the below issue. 
- "doesn't support debugger"
<img width="1512" alt="Screenshot 2023-11-03 at 9 59 42 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/58015008/51ff2067-d630-4cb1-985d-2dabb27157db">

- While running the code, getting "Unknown network error. Please try reloading page"
<img width="1512" alt="Screenshot 2023-11-03 at 9 53 22 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/58015008/0a713fbe-203a-4163-ad66-9d05f03dc1e9">

### Way to fix the issue
Open the code tab. Once code tab loaded, then the "Debugger" enabled and "Run" works as expect.

## Expected behavior

**Anyone is expected**
1. It should run the code even if it's not loaded the "code" tab.
2. By default, the "code" tab should be active instead of other tab while opening the question.
3. Throw some other error like "please open code tab or else run will not work"

## Screenshots

Added in the description

**Comment by LC-Pam** [comment]
Thank you for your time. 

The issue should be fixed. 

If you still encounter the same issue, please contact us through https://leetcode.com/support/

We appreciate your support!
