### ISSUE TITLE
49 - Group Anagrams - Ambiguous description

### ISSUE THREAD

**Issue by creed-bratton33** [LeetCode-Feedback/LeetCode-Feedback#17778]
The question description and given examples don't make clear whether or not duplicate words should show up just once or multiple times in the output.  For example, with the input `["a", "a"]`, the expected output is `[["a","a"]]`, as opposed to just `[["a"]]`.  

This is primarily a problem in the context of an assessment, where running a test case doesn't tell you what the expected output should be.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Please ask your question in the discussion forum.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
