### ISSUE TITLE
Missing Test Case - 162. Find Peak Element

### ISSUE THREAD

**Issue by dipeshdh** [LeetCode-Feedback/LeetCode-Feedback#17770]
#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

Below two tests are valid test but when we run the test it is expecting 0 as expected output, but actual can be 0 or 2

[2,1,2]
[3,1,5]

#### Code you used for Submit/Run operation

```
class Solution {
    public int findPeakElement(int[] nums) {
        if(nums.length == 0)
            return -1;
        int l = 0, r = nums.length-1;
        int m;
        while(l < r){
            m = l +(r-l)/2;
           
            if(nums[m] > nums[m+1])
                r = m;
            else 
                l = m + 1;
        }
     
            return l;
     }
}
```

#### Language used for code

JAVA

#### Expected behavior

The expected behavior can be 0 or 2 , both are valid

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The judge working correctly. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
