### ISSUE TITLE
Wrong Test Case - 287. Find the Duplicate Number

### ISSUE THREAD

**Issue by keatshackon** [LeetCode-Feedback/LeetCode-Feedback#1778]
#### Your LeetCode username

keats_92

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

According to question, [2,2,2,2,2] test case should not be possible, but leetcode compiler checks for [2,2,2,2,2] test case,please kindly look into this matter!

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

     int r = nums.size()-1;
        int sum = 0;
        r = (r*(r+1))/2; 
        for(auto q:nums){
            sum+=q;
        }
        
        return sum-r;
    }
};
```

#### Language used for code

c++

**Comment by lc-kay** [comment]
@keatshackon This is a valid test case, as it says there is only one duplicate number, which appears two or more times.
