### ISSUE TITLE
Incorrect binary representation on the Explore Cards

### ISSUE THREAD

**Issue by dudemelo** [LeetCode-Feedback/LeetCode-Feedback#17786]
#### Your LeetCode username

dudemelo

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The binary representation on the video skipped the 2 raised to the power of 2.

Link for the page: https://leetcode.com/explore/learn/card/the-leetcode-beginners-guide/692/challenge-problems/4425/

It's at 4:57 in the video.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/1172271/2f7007b5-9130-4ed3-9ee8-aeed0094c720)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The page link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've used your feedback to check the problem.

We redirected it to our content team but it will take time to fix.

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!
