### ISSUE TITLE
Incorrect Test Case: 589. N-ary Tree Preorder Traversal

### ISSUE THREAD

**Issue by muntaxir4** [LeetCode-Feedback/LeetCode-Feedback#17780]
#### Your LeetCode username

[muntaxir](https://leetcode.com/muntaxir)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

38th Test case during submission is incorrect. **Due to extra space in input.**
> Current Input: `[1, null]`
> Current Output:  ```terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi```

#### Code you used for Submit/Run operation

```c++
class Solution {
private:
void helper(Node *root, vector<int> &ans){
    if(!root) return;
    ans.push_back(root->val);
    for(auto ch: root->children) helper(ch,ans);
}
public:
    vector<int> preorder(Node* root) {
        vector<int> ans;
        helper(root,ans);
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

> Expected Input: `[1,null]`
> Expected Output: `[1]`

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by muntaxir4** [comment]
The solution isn't accepted due to wrong test case no. 38, hence I have no link to the submission.

**Comment by muntaxir4** [comment]
https://leetcode.com/submissions/detail/1090886983/
The solution isn't accepted due to incorrect test case.

**Comment by muntaxir4** [comment]
Hey, @LC-Pam any update?

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
