### ISSUE TITLE
Example Typo: 2881. Create a New Column

### ISSUE THREAD

**Issue by bmai1** [LeetCode-Feedback/LeetCode-Feedback#17781]
#### Your LeetCode username
brianmai

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
For the given example (1) in the description, there is a typo. Willow's salary should be "6593" instead of "593".

#### Screenshots

<img width="728" alt="Screen Shot 2023-11-03 at 2 46 54 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/104703637/f74b9cb7-1b16-476f-bb40-c00d0cd838b9">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
