### ISSUE TITLE
Missing Test Case - 205. Isomorphic Strings

### ISSUE THREAD

**Issue by fraxy-v** [LeetCode-Feedback/LeetCode-Feedback#17789]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Invalid test case data: invalid escape character sequence.

You would notice that the size of the input strings is different, contrary to the announced constraints:
 - t.length == s.length

Input:
"12"
"\u0067\u0067"
Stdout:
string: "12", size: 2
string: "u0067u0067", size 10

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've used your feedback to update the problem.

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback.

Please provide us your Leetcode Username .

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!

**Comment by fraxy-v** [comment]
> Thank you for your time.
> 
> We've used your feedback to update the problem.
> 
> Your LeetCode account will receive 100 LeetCoins as a reward for this feedback.
> 
> Please provide us your Leetcode Username .
> 
> If you have any other questions or feedback, please don't hesitate to let us know!
> 
> We appreciate your support!

Leetcode Username: fraxy
