### ISSUE TITLE
Missing Test Case - 20. Valid Parentheses

### ISSUE THREAD

**Issue by heyitsshome** [LeetCode-Feedback/LeetCode-Feedback#17788]
#### Your LeetCode username

pamella_shome

#### Category of the bug
- [ ] Missing Test Cases 
-[ ] Made modification in source code

#### Description of the bug

the 13 statement was not running in my interpreter so made some changes. and added extra test cases

#### Code you used for Submit/Run operation

```
class Solution(object):
    def isValid(self, s):
        stack=[]
        dict={"}":"{",")":"(","]":"["}
        for c in s:
            if c in dict:
                if stack and stack[-1]==dict[c]:
                    stack.pop()
                else:
                    return False
            else:
                stack.append(c)
        if not stack :
            return True
        else:
            return False

};

test case 1 :
"{[]{}}"
test case 2:
"{((())))"
test case 3:
"[[[{}]]]"
```

#### Language used for code
-Python

#### Expected behavior
 when stack becomes empty it returns true, which means all the elements had same opening and closing parenthesis, else returns false

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/93142302/edf8f593-4dae-4d08-a3ce-e1ab3e2859ae)
here in the ss , 13 statement line the code is "return True if not stack else False", when i run that in python lower version it was not valid so i made the above changes in the code , my code runs in every python version

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Please ask your question in the discussion forum.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
