### ISSUE TITLE
Missing Test Case - 1209. Remove All Adjacent Duplicates in String II

### ISSUE THREAD

**Issue by suru003** [LeetCode-Feedback/LeetCode-Feedback#1779]
#### Your LeetCode username

with submission, I'm getting timeout but for the same test, I can run it by console

'''
class Solution:
    def removeDuplicates(self, s: str, k: int) -> str:
        ls = list(s)
        changed=1
        while(changed==1):
            n = len(ls)-k+1
            ch=0
            for i in range(n):
                l=set({})
                for x in ls[i:i+k]:
                    if(x not in l):
                        l.add(x)
                        if(len(l)>1):
                            break
                if(len(l) == 1):
                    del ls[i:i+k]
                    ch=1
                    break
            if(ch==0):
                break
        s = "".join(ls)
        # print(s)
        return s
                
'''

#### Screenshots

![Screenshot (225)](https://user-images.githubusercontent.com/31486779/103167416-41642900-47e8-11eb-9396-dd40f841dbe8.png)

**Comment by lc-kay** [comment]
@suru003 When you run your code, it only runs it against one test case. However, when you submit the code, it runs it against the entire test case set. Although your code was able to stay within the time limit for one test case, it was not optimized to run all test cases within the time limit. Thank you for your time!
