### ISSUE TITLE
pandas题库180题误判

### ISSUE THREAD

**Issue by Beautifuldog01** [LeetCode-Feedback/LeetCode-Feedback#17791]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
Beautifuldog01（infallible-meninskyhmq）

**Bug 类型**
- [ ] 题目
- [x] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述**
这道题是不是产生误判了还是判断机制的问题。  
https://leetcode.cn/problems/consecutive-numbers/?lang=pythondata
其次pandas刷题的体验非常差，第一个原因是测试样例需要我手动打一遍DataFrame，不能像别的算法题一样测试样例都是以编程语言变量定义的语句给出吗？例如直接用DataFrame定义。我手动创造一个DataFrame的过程很浪费时间。
第二个原因可以说是由第一个原因造成的。某些题目中的样例类型中表内的变量居然是numpy.float类型的，导致这部分变量不兼容部分运算导致报错。

**你使用的语言**
Python

**你提交或者运行的代码**
```
import pandas as pd

def consecutive_numbers(logs: pd.DataFrame) -> pd.DataFrame:
    logs['num'] = logs['num'].astype(str)
    logs['shifted'] = logs['num'].shift(1)
    logs['streak'] = (logs['num'] != logs['shifted']).cumsum()
    logs['count'] = logs.groupby('streak')['num'].transform('size')
    consecutive_nums = logs[logs['count'] >= 3]['num'].unique()
    return pd.DataFrame({'ConsecutiveNums':consecutive_nums})
```

**期望行为**
<img width="568" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/40363660/3b3eb096-5e97-4a34-8a5f-2091ac67d0a9">

**屏幕截图**
<img width="568" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/40363660/b571bb48-128d-440f-ac4b-4655ee5e480f">

**额外的上下文**
其次pandas刷题的体验非常差，第一个原因是测试样例需要我手动打一遍DataFrame，不能像别的算法题一样测试样例都是以编程语言变量定义的语句给出吗？例如直接用DataFrame定义。我手动创造一个DataFrame的过程很浪费时间。
第二个原因可以说是由第一个原因造成的。某些题目中的样例类型中表内的变量居然是numpy.float类型的，导致这部分变量不兼容部分运算导致报错。

**Comment by amcones** [comment]
您好，在与相关团队核实后：不处理（倒数第二行：consecutive_nums = logs[logs['count'] >= 3][['num']].nunique()）。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
