### ISSUE TITLE
面试题19. 正则表达式匹配 描述不清晰

### ISSUE THREAD

**Issue by 375C** [LeetCode-Feedback/LeetCode-Feedback#178]
** Bug 类型**
- [X] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
该题中，没有描述清出连续的*出现时的匹配规则，导致如果自测试用例中出现连续*时，没有标准答案。
如测试用例为：
```
""
".**"
```
时，点击执行代码，是没有预期结果的

**你使用的语言**
C

**期望行为**
题目中增加描述不会出现连续的*

**Comment by feiceh** [comment]
感谢反馈，已更新～
