### ISSUE TITLE
【题面翻译有误】2923. Find Champion I 

### ISSUE THREAD

**Issue by zouyu9631** [LeetCode-Feedback/LeetCode-Feedback#17805]
**你的 LeetCode 用户名**
FreeYourMind

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言
- [ ] 缺少测试用例

**描述**
题目 [2923. Find Champion I](https://leetcode.cn/problems/find-champion-i/description/) 

翻译有误。
提示部分：

> 生成的输出满足 ...

对应的英文描述是：

> The input is generated such that if ...

**期望行为**
应翻译为：
> 生成的输入满足

**屏幕截图**
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/6801919/1bd9da13-5a22-4059-a408-8607ffe02e69)

**Comment by amcones** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by zouyu9631** [comment]
> 你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

谢谢：）

leetcode.cn/u/freeyourmind/
