### ISSUE TITLE
Missing Test Case - 1705. Maximum Number of Eaten Apples

### ISSUE THREAD

**Issue by stylelohan** [LeetCode-Feedback/LeetCode-Feedback#1780]
#### Your LeetCode username

peihsin

#### Category of the bug
- [ ] Question
- Solution
- [ ] Language

#### Description of the bug

Found a test case that fails my already accepted solution. The output from Leetcode judge is correct.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int eatenApples(vector<int>& apples, vector<int>& days) {
        
        vector<int> vec(2, -1); int ret = 0, apple_count = 0;
        for (int i = 0; i < apples.size(); i++) {
            if (apples[i]==0) continue;
            apple_count += apples[i];
            vector<int> newvec(2, -1); newvec[0] = i;
            newvec[1] = i + days[i]-1;

            if (vec[0]==-1) vec = newvec;
            else if (newvec[0]<=vec[1]+1) vec[1] = max(vec[1], newvec[1]);
            else { ret += vec[1]-vec[0]+1; vec = newvec; }
        }
        return min(apple_count, ret + vec[1]-vec[0]+1);
    }
};
```

#### Language used for code

C++

#### Expected behavior

Expected output : 5 (correct)
My output : 6 (wrong)

#### Screenshots

<img width="1275" alt="螢幕快照 2020-12-27 下午6 42 04" src="https://user-images.githubusercontent.com/11243331/103169013-43bf9500-4873-11eb-8cc7-00dbf26ab409.png">

#### Additional context

Thanks for handling the issue :)

**Comment by lc-kay** [comment]
Hi @stylelohan 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@stylelohan Our team recently updated our test case set for this problem and the code you submitted now receives Wrong Answer. Thank you for your time!
