### ISSUE TITLE
Too strict time limit for C++ - 2926. Maximum Balanced Subsequence Sum

### ISSUE THREAD

**Issue by przemek3d88** [LeetCode-Feedback/LeetCode-Feedback#17806]
#### Your LeetCode username
przemysaw2

#### Category of the bug
- [x] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
The optimal solution in terms of time `O(n log n)` and space `O(n)` fails because of a too-strict time limit for C++. It also looks like other languages have a higher time limit, which means the C++ limit can also be increased.

The solution with the same complexity fails because of copying elements and removing them in the next iteration, instead of removing them directly. This operation does not change the time of the solution but increases a constant a little bit. Failing optimal solutions because of the constant should be avoided and discouraged both in the contest and the interview environment.

I will paste 2 codes below - the one submitted during the contest, which failed, and the second which I submitted a few minutes after the contest. The only difference is that in the first solution, I copied the pair values into the vector and removed them in the next iteration, to avoid complex logic related to removing and iterating over the set. I don't think this differentiation is fair and it rejects the correct and optimal solution.

The first solution times out while the second passes in 538 ms. Could you please increase the time limit for C++? 

I also noticed that Python solutions have a higher time limit.

The difference is with rem vector - for a convenient removal of elements. Also, the set is usually slower than the Fenwick tree, but it is not the reason to reject the set-based solutions.

#### Code you used for Submit/Run operation

TLE [Submission](https://leetcode.com/problems/maximum-balanced-subsequence-sum/submissions/1091758884/): 

```
class Solution {
public:
    long long maxBalancedSubsequenceSum(vector<int>& nums) {
        int n = nums.size();
        int curPos = 0;
        auto cmp = [&](const int& a, const int& b) {
            //printf("cmp a: %d vala: %d b: %d valb: %d\n", a, nums[a]+curPos-a, b, nums[b]+curPos-b);
            return nums[a]+curPos-a < nums[b]+curPos-b;
        };
        set<int, decltype(cmp)> intS(cmp);
        set<pair<long long,int>> S;
        
        long long res = nums.front();
        intS.insert(0);
        S.insert(make_pair(nums[0], 0));
        vector<long long> dp(n);
        dp[0] = nums[0];
        
        for(curPos = 1; curPos < n; curPos++) {
            {
                auto it = intS.upper_bound(curPos);
                if(it == intS.begin()) {
                    dp[curPos] = nums[curPos];
                } else {
                    it--;
                    dp[curPos] = nums[curPos] + max(0LL, dp[*it]);
                }
                
                res = max(res, dp[curPos]);
            }
            
            //printf("pos %d: %lld\n", curPos, dp[curPos]);
            
            auto it = S.upper_bound(make_pair(dp[curPos],1e9));
            vector<pair<int,int>> rem;
            bool add = 1;
            while(it != S.begin()) {
                it--;
                if(nums[it->second]+curPos-it->second < nums[curPos]) {
                    if(it->first == dp[curPos]) {
                        add = 0;
                    }

                    break;
                }
                
                rem.push_back(*it);
                intS.erase(it->second);
            }
            
            for(const auto& p : rem) {
                S.erase(p);
            }
            
            if(add) {
                S.insert(make_pair(dp[curPos], curPos));
                intS.insert(curPos).second;
            }
            
            /*for(const auto& p : S) {
                printf("%lld %d\n", p.first, p.second);
            }
            for(const int& s : intS) {
                printf("%d\n", s);
            }*/
        }
        
        return res;
    }
};
```

Accepted [submission](https://leetcode.com/problems/maximum-balanced-subsequence-sum/submissions/1091769999/):

```
class Solution {
public:
    long long maxBalancedSubsequenceSum(vector<int>& nums) {
        int n = nums.size();
        int curPos = 0;
        auto cmp = [&](const int& a, const int& b) {
            //printf("cmp a: %d vala: %d b: %d valb: %d\n", a, nums[a]+curPos-a, b, nums[b]+curPos-b);
            return nums[a]+curPos-a < nums[b]+curPos-b;
        };
        set<int, decltype(cmp)> intS(cmp);
        set<pair<long long,int>> S;
        
        long long res = nums.front();
        intS.insert(0);
        S.insert(make_pair(nums[0], 0));
        vector<long long> dp(n);
        dp[0] = nums[0];
        
        for(curPos = 1; curPos < n; curPos++) {
            {
                auto it = intS.upper_bound(curPos);
                if(it == intS.begin()) {
                    dp[curPos] = nums[curPos];
                } else {
                    it--;
                    dp[curPos] = nums[curPos] + max(0LL, dp[*it]);
                }
                
                res = max(res, dp[curPos]);
            }
            
            auto it = S.upper_bound(make_pair(dp[curPos],1e9));
            bool add = 1;
            bool rem = 0;
            while(it != S.begin()) {
                if(rem) {
                    auto nxt = it; nxt++;
                    S.erase(it);
                    it = nxt;
                }

                it--;

                if(nums[it->second]+curPos-it->second < nums[curPos]) {
                    if(it->first == dp[curPos]) {
                        add = 0;
                    }
                    
                    rem = 0;
                    break;
                }
                
                intS.erase(it->second);
                rem = 1;
            }
            
            if(rem) {
                S.erase(it);
            }
            
            if(add) {
                S.insert(make_pair(dp[curPos], curPos));
                intS.insert(curPos).second;
            }
            
        }
        
        return res;
    }
};
```

#### Language used for code
C++

**Comment by przemek3d88** [comment]
This [submission](https://leetcode.com/problems/maximum-balanced-subsequence-sum/submissions/1091786825), where the only difference is deleting iterators (locations in memory) instead of the content of the nodes, passes in 641 MS.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

3s is the default C++ TL. For sure, Python TL is higher.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
