### ISSUE TITLE
Missing Test Case - 2215. Find the Difference of Two Arrays

### ISSUE THREAD

**Issue by puremachinery** [LeetCode-Feedback/LeetCode-Feedback#17810]
#### Your LeetCode username
puremachinery

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The problem specifies a return type of List[List[int]], but it accepts a return type of List[Set[int]].

#### Code you used for Submit/Run operation
```
# Find the Difference of Two Arrays
class Solution:
    def findDifference(self, nums1: List[int], nums2: List[int]) -> List[List[int]]:
        set1 = set(nums1)
        set2 = set(nums2)
        return [set1-set2, set2-set1]
```

#### Language used for code
Python3

#### Expected behavior

This answer should be rejected, as `isinstance(aSet, list)` is false. To be accepted, the elements of the return list should be cast to a list first, for example: `return [list(set1-set2), list(set2-set1)]`. A test case that checks the return type of the list elements would catch this issue.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
