### ISSUE TITLE
Wrong Output Expected - 1867. Orders With Maximum Quantity Above Average

### ISSUE THREAD

**Issue by JCharante** [LeetCode-Feedback/LeetCode-Feedback#17818]
#### Your LeetCode username

JCharante

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

For [this problem](https://leetcode.com/problems/orders-with-maximum-quantity-above-average/) there's a test case with this input

```
| order_id | product_id | quantity |
| -------- | ---------- | -------- |
| 5        | 2          | 262      |
| 7        | 2          | 128      |
```

and the solution for this test case says there are no orders that are imbalanced, but the average order quantity is 195, and order 5 with quantity 262 is clearly greather than the average of 195.

#### Code you used for Submit/Run operation

```
# Write your MySQL query statement below
WITH AVGQTY AS (
    SELECT AVG(qty) as num
    FROM (
    SELECT SUM(quantity) / COUNT(DISTINCT product_id) AS qty
    FROM OrdersDetails
    GROUP BY order_id
    ) s
)

SELECT order_id
FROM (
SELECT *, MAX(quantity) > (SELECT num FROM AVGQTY) as imbalanced
FROM OrdersDetails
GROUP BY order_id
) b
WHERE imbalanced = 1
```

#### Language used for code
MySQL

#### Expected behavior

This output should be expected per the instructions

```
You are running an e-commerce site that is looking for imbalanced orders. An imbalanced order is one whose maximum quantity is strictly greater than the average quantity of every order (including itself).

The average quantity of an order is calculated as (total quantity of all products in the order) / (number of different products in the order). The maximum quantity of an order is the highest quantity of any single product in the order.

Write a solution to find the order_id of all imbalanced orders.
```

```
| order_id |
| -------- |
| 5        |
```

#### Screenshots

<img width="597" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/13973198/87325464-b910-4cb2-a4e2-c299750e5cf7">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by JCharante** [comment]
Hi @LC-Pam, it didn't get accepted because the wrong output is expected, but here is the submission link https://leetcode.com/problems/orders-with-maximum-quantity-above-average/submissions/1098535207

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team

**Comment by JCharante** [comment]
Hi @LC-Pam , can you please explain how

`An imbalanced order is one whose maximum quantity is strictly greater than the average quantity of every order (including itself).` doesn't result in an average quantity of 195, of which order 5, having a quantity of 262, meets the criteria for inclusion in the output?

This is not about code, this is about a test case with 2 data points and a logical inconsistency. I don't claim to be omnipotent or all knowing, but as a premium member of the site I would appreciate an explanation of why this test case's result does not include order 5.
