### ISSUE TITLE
Missing Test Case - 1705. Maximum Number of Eaten Apples

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#1781]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution is accepted but fails on the following test case:
[5,2,3]
[6,9,10]

#### Code you used for Submit/Run operation

```
import java.util.SortedMap;
import java.util.TreeMap;

class Solution {
    public int eatenApples(int[] apples, int[] days) {
        int n = apples.length;
        int res = 0;
        int sum = 0;
        for (int apple : apples) {
            sum += apple;
        }
        SortedMap<Integer,Integer> map = new TreeMap<>();
        int i = 0;
        while (i < n) {
            if (apples[i] > 0) {
                int key = i + days[i] - 1;
                map.put(key, map.getOrDefault(key, 0) + apples[i]);
            }
            map.remove(i-1);
            if (!map.isEmpty()) {
                int j = map.firstKey();
                if (map.get(j) == 1) {
                    map.remove(j);
                } else {
                    map.put(j, map.get(j) - 1);
                }
                res++;
            }
            i++;
        }
        while (i < sum + n) {
            if (!map.isEmpty()) {
                int j = map.firstKey();
                res += Math.min(j - i + 1, map.get(j));
                i = j + 1;
                map.remove(j);
            } else {
                break;
            }
        }
        return res;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/103169198-a418ed00-4807-11eb-9f78-2b9704905ec8.png)

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
