### ISSUE TITLE
Missing Test Case - 808. Soup Servings

### ISSUE THREAD

**Issue by gopeshb** [LeetCode-Feedback/LeetCode-Feedback#17816]
#### Your LeetCode username
gopeshbhatia01

#### Category of the bug
-  Question
- Missing Test Cases 

#### Code you used for Submit/Run operation

```
// [808. Soup Servings](https://leetcode.com/problems/soup-servings/)
class Solution {
  public static int op[][]={{4,0},{3,1},{2,2},{1,3}};
  public static double solve(int a,int b,Double dp[][]){
    if(a<=0){
      if(b<=0)
      return 0.5;
      return 1;
    }
    if(b<=0)
    return 0;
    if(dp[a][b]!=null)
    return dp[a][b];
    double ans=0.0;
    for(int o[]:op){
      ans+=.25*solve(a-o[0],b-o[1],dp);
    }
    dp[a][b]=ans;
    return dp[a][b];
  }
    public double soupServings(int n) {
      if(n>=4500)
      return  1;
      if(n==0)
      return 0.5;
      if(n%25==0)
      n=n/25;
      else
      n=n/25+1;      
        Double dp[][]=new Double[n+1][n+1];
        return solve(n,n,dp);
    }
}
```

#### Language used for code
JAVA

#### Expected behavior
in question it is expected to return correct digit up to 5 decimal places but beyond 4501 test cases if you pass 1 it will expect it while excepted output showing is 0.99999 which is absurd.
please correct this bug.  

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/145230384/55814a8d-e6cd-4002-afd1-5c0e9810bde5)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

The judge working correctly. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
