### ISSUE TITLE
leetcode 自己给自己的答案开后门是吧？一模一样的实现，然后我超时，你们是懂判题的，甚至时间性能明显我的更优！

### ISSUE THREAD

**Issue by Tiikee** [LeetCode-Feedback/LeetCode-Feedback#17814]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
橙橙橙

**Bug 类型**
- [[421. 数组中两个数的最大异或值](https://leetcode.cn/problems/maximum-xor-of-two-numbers-in-an-array/) ] 题目
- [ ] 题解
```
class Solution {
public:
    int findMaximumXOR(vector<int>& nums) {
    int x = 0, flag = 0;
    unordered_set<int> pre;
    for(int i = 30; i >= 0; --i) {
        x = (x << 1) + 1, flag = 0;
        pre.clear();
        // 得到所有数的 前i位
        for(int num : nums) {
            pre.emplace(num >> i);
        }
        for(int num : nums) {
            if(pre.find(x ^ (num >> i)) != pre.end()) {
                flag = 1;
                break;
            }
        }
        if(!flag) x -= 1;
    }
    return x;
    }
};
```
- [ C++] 编程语言
- [无 ] 缺少测试用例

**描述**
一模一样的实现，和数据结构，我的更精简，我数据结构还优化精简过，然后我超时？你们官解后门开的可以啊！？
官解时间击败40%，我的超时。你们这判题器这么区别对待的是吧？？？
还得是官方解优秀是吧！？

**你使用的语言**
C++

# 你提交的代码 和 官方解代码
**我的解：**
```
class Solution {
public:
    int findMaximumXOR(vector<int>& nums) {
    int x = 0, mx = *max_element(nums.begin(), nums.end());
    if(mx == 0) return 0;
    unordered_set<int> allNum(nums.begin(), nums.end()), pre;
    int maxBit = floor(log2(mx)), flag = 0;
    for(int i = maxBit; i >= 0; --i) {
        x = (x << 1) + 1, flag = 0;
        pre = {};
        // 得到所有数的 前i位
        for(auto num : allNum) {
            pre.emplace(num >> i);
        }
        for(auto num : allNum) {
            if(pre.find(x ^ (num >> i)) != pre.end()) {
                flag = 1;
                break;
            }
        }
        if(!flag) x -= 1;
    }
    return x;
    }
};
```

**官解：**
```
class Solution {
private:
    // 最高位的二进制位编号为 30
    static constexpr int HIGH_BIT = 30;

public:
    int findMaximumXOR(vector<int>& nums) {
        int x = 0;
        for (int k = HIGH_BIT; k >= 0; --k) {
            unordered_set<int> seen;
            // 将所有的 pre^k(a_j) 放入哈希表中
            for (int num: nums) {
                // 如果只想保留从最高位开始到第 k 个二进制位为止的部分
                // 只需将其右移 k 位
                seen.insert(num >> k);
            }

            // 目前 x 包含从最高位开始到第 k+1 个二进制位为止的部分
            // 我们将 x 的第 k 个二进制位置为 1，即为 x = x*2+1
            int x_next = x * 2 + 1;
            bool found = false;
            
            // 枚举 i
            for (int num: nums) {
                if (seen.count(x_next ^ (num >> k))) {
                    found = true;
                    break;
                }
            }

            if (found) {
                x = x_next;
            }
            else {
                // 如果没有找到满足等式的 a_i 和 a_j，那么 x 的第 k 个二进制位只能为 0
                // 即为 x = x*2
                x = x_next - 1;
            }
        }
        return x;
    }
};
```

**期望行为**
一样成功提交，不超时！？？？ 优化删减了重复元素，然后我超时，判题器怎么判的呢？？？

**屏幕截图**
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/95959942/1e1d1c63-b8fb-40ad-ad73-f465be9b98f6)

**额外的上下文**
望分析解决

**Comment by Tiikee** [comment]
# 优化点：
1. 删除了 `nums` 数组中的重复元素。
2. 每次循环少遍历 `30-maxBit` 位
3. `x`少一步传值处理
4. `find`效率高于`count`
5. 清空 `unordered_set` 效率高于 新创建 `unordered_set`
6. `emplace`快于`insert`
# 疑问
1. 基于以上6点优化，结果我超时，官方解能过！！？
2. 甚至我改成可以说一样的代码，还是我超时！？ 怎么判的呢？
    - 代码如下：
    ```
	class Solution {
	public:
		int findMaximumXOR(vector<int>& nums) {
		int x = 0, flag = 0;
		unordered_set<int> pre;
		for(int i = 30; i >= 0; --i) {
			x = (x << 1) + 1, flag = 0;
			pre = {};
			// 得到所有数的 前i位
			for(auto num : nums) {
				pre.emplace(num >> i);
			}
			for(auto num : nums) {
				if(pre.find(x ^ (num >> i)) != pre.end()) {
					flag = 1;
					break;
				}
			}
			if(!flag) x -= 1;
		}
		return x;
		}
	};
    ```

**Comment by amcones** [comment]
您好，在与相关团队核实后：不处理（插入时使用 `emplace` 需要额外调用构造函数创建对象，对于基本类型来说性能不佳，应使用 `insert`）。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。

**Comment by Ming91** [comment]
个人感觉瓶颈正是在提前用set去重,最坏的情况就是n个不相同的数,这样就将`构建n大小的集合`做了两次, 而这正是这道题最慢的一步. 当然如果是n个相同的数, 去重是明显要好的. 你可以测试下不去重是否能通过这种情况. 即, 各方法能否通过自己的最坏情况.

个人做这道题学到的优化建议:
边加入边比较,如果提前有更新,后面也不用加入集合.

**Comment by Tiikee** [comment]
我试过不去重还是超时，可以说我只改了个变量名差不多，还是超时，第二次还是第三次遇到这样的问题了！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LeetCode-Feedback/LeetCode-Feedback"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月16日(星期四) 凌晨3:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LeetCode-Feedback/LeetCode-Feedback] leetcode 自己给自己的答案开后门是吧？一模一样的实现，然后我超时，你们是懂判题的，甚至时间性能明显我的更优！ (Issue #17814)





 
个人感觉瓶颈正是在提前用set去重,最坏的情况就是n个不相同的数,这样就将构建n大小的集合做了两次, 而这正是这道题最慢的一步. 当然如果是n个相同的数, 去重是明显要好的. 你可以测试下不去重是否能通过这种情况. 即, 各方法能否通过自己的最坏情况.
 
个人做这道题学到的优化建议:
 边加入边比较,如果提前有更新,后面也不用加入集合.
