### ISSUE TITLE
Missing testcase for #14 - shortest is always alphabetically first

### ISSUE THREAD

**Issue by tejasraman** [LeetCode-Feedback/LeetCode-Feedback#17824]
#### Your LeetCode username
tejasraman

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [*] Missing Test Cases 

#### Description of the bug

Shortest string in strs is always alphabetically first, leading min command to work. Using min is incorrect and should not be accepted. 

In this test case, the shortest word is not alphabetically first, leading the min command to produce an incorrect output.

The code below is incorrect (however, still accepted due to above bug)

#### Code you used for Submit/Run operation

```
class Solution:
    def longestCommonPrefix(self, strs: List[str]) -> str:
        if "" in strs:
            return ""
        pre = []
        charnum = -1
        listoflists = [[*i] for i in strs]
        for i in range(len(min(strs))):
            plst = [x[(charnum + 1)] for x in listoflists]
            if len(set(plst)) == 1:
                pre.append(plst[0]); charnum += 1
            else:
                break
        return "".join(pre)
```

#### Language used for code
Python

#### Expected behavior
Above solution should be rejected as it tries to find the shortest but instead finds alphabetically first (which is shortest in all current testcases

#### Screenshots
Not applicable

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
