### ISSUE TITLE
Missing Test Case - 205. Isomorphic Strings

### ISSUE THREAD

**Issue by jingv** [LeetCode-Feedback/LeetCode-Feedback#1783]
** Bug 类型**
- [ ] 题目
- [x] 题解
- [ ] 编程语言

**描述**
缺少测试用例.

**你使用的语言**
Python3

**你提交或者运行的代码**
```
class Solution:
    def isIsomorphic(self, s: str, t: str) -> bool:
        pre_s, pre_t, dic_s_t = "", "", {}

        for i in range(len(s)):
            # print('pre_s={}, pre_t={}, s[i]={}, t[i]={}'.format(pre_s, pre_t, s[i], t[i]))

            if (pre_s == s[i] and pre_t == t[i]) or (pre_s != s[i] and pre_t != t[i]):
                if s[i] in dic_s_t:
                    if dic_s_t[s[i]] != t[i]:
                        return False
                else:
                    dic_s_t[s[i]] = t[i]
                
                pre_s, pre_t = s[i], t[i]
            
            else:
                return False

        return True
```

**期望行为**
输入: s = "egcd", t = "adfd"

代码输出: True
预期结果: False

但代码通过测试.

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前该题已添加测试用例， 请留言告知一下您的力扣 ID，我们给予积分奖励哦。

**Comment by jingv** [comment]
您好，leetcodeID: coder-jingv个人空间: https://leetcode-cn.com/u/coder-jingv/谢谢😜-------- 原始邮件 --------发件人： feiceh <notifications@github.com>日期： 2021年1月6日周三 16:23收件人： LeetCode-Feedback/LeetCode-Feedback <LeetCode-Feedback@noreply.github.com>抄送： jingv <jingvsun@163.com>, Author <author@noreply.github.com>主    题： Re: [LeetCode-Feedback/LeetCode-Feedback] Missing Test Case - 205. Isomorphic Strings (#1783)

你好，当前该题已添加测试用例， 请留言告知一下您的力扣 ID，我们给予积分奖励哦。

**Comment by feiceh** [comment]
不客气，ID：coder-jingv 给予积分奖励，请查收。
