### ISSUE TITLE
Missing Test Case - 1251. Average Selling Price

### ISSUE THREAD

**Issue by bengisukarakaya** [LeetCode-Feedback/LeetCode-Feedback#17837]
Category of the bug
- [ ] Question
- + Solution
- [ ] Language
- [ ] Missing Test Cases 

The answer was accepted, but when I click on submit, it says it's wrong.
### my code :
`select p.product_id, 
ROUND(CAST(SUM(units * price) AS FLOAT) / CAST(SUM(u.units) AS FLOAT),2) as average_price
from Prices p
inner JOIN UnitsSold u
ON p.product_id = u.product_id
where purchase_date between start_date and end_date
group by p.product_id
`
``
#### Screenshots

<img width="402" alt="Ekran görüntüsü 2023-11-06 170636" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/150045994/58c7e990-d706-438c-aa7c-0e89fdc7da9f">

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
