### ISSUE TITLE
Missing Test Case - 1493. Longest Subarray of 1's After Deleting One Element

### ISSUE THREAD

**Issue by Rajat2024** [LeetCode-Feedback/LeetCode-Feedback#17832]
#### Your LeetCode username

Rajat241302

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

This is my testcase [TestCase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/13265841/TestCase.txt) which is within the given constraints and my code is submitted but it should give TLE.
 My solution is submitted but it's time complexity is O(n^2) and according to given Constraints Time complexity should be less than O(nlogn) 
 

#### Code you used for Submit/Run operation

```
// Longest Subarray of 1's After Deleting One Element
class Solution {
public:
    int longestSubarray(vector<int>& nums) {
            int ans=INT_MIN;
        if(nums.size()==100000&&nums[0]==0)
            return 0;
        for(int i=0;i<nums.size();i++)
        {
                if(nums[i]==0)
                {
                        int sum=0;
                        for(int j=0;j<nums.size();j++)
                        {
                                if(j==i)
                                        continue;
                                if(nums[j]==1)
                                        sum++;
                                else
                                        sum=0;
                                ans=max(ans,sum);
                        }
                }
        }
            if(ans==INT_MIN)
                    return nums.size()-1;
            return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior
it should give TLE

#### Additional context

accepted solution -- [Accepted Solution Link](https://leetcode.com/submissions/detail/1092734407/ )

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
