### ISSUE TITLE
Missing Test Case - 189. Rotate Array

### ISSUE THREAD

**Issue by andreapulita** [LeetCode-Feedback/LeetCode-Feedback#17859]
#### Your LeetCode username
andrea8130

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
When I run my code in my IDE I get the correct answer, but in the submit I get the wrong one and a different result.

#### Code you used for Submit/Run operation

```
// Rotate Array
class Solution {
public:
    void rotate(vector<int>& nums, int k) {
        int subarray = k % nums.size();
        int size = nums.size();
        nums.insert(nums.begin(), nums.end() - subarray, nums.end());
        nums.resize(size);
    }
};
```

#### Language used for code
C++

#### Expected behavior
The test case [1, 2, 3] with 1 that I run in my IDE gives me the result of [3, 1, 2] while in the submit it says that the result of the code is [2, 1, 2].

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
