### ISSUE TITLE
Missing Test Case - 128. Longest Consecutive Sequence

### ISSUE THREAD

**Issue by mardeldev** [LeetCode-Feedback/LeetCode-Feedback#17853]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The test cases provided do not cover what happens when there are more than two chunks of consecutive numbers. With the code provided below, I am able to pass the test cases provided, even though this solution wouldn't provide the longest consecutive sequence for an array of more than one sequence.

#### Code you used for Submit/Run operation

```
# Longest Consecutive Sequence
class Solution:
    def longestConsecutive(self, nums: List[int]) -> int:
        numSet = set(nums)
        longest = 0
        for n in nums:
            if n-1 in numSet:
                longest += 1
        return longest+1
```

#### Expected behaviour

I expect the code to be an invalid solution. Instead, with the test cases provided, the code passes and can be submitted as valid.

#### Screenshots

<img width="587" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73969781/ff494f45-0564-4d73-a3f0-069ecc002eaf">

The screenshot above shows an example where there exists a list of two different consecutive sequences, one of length 4 and the other of length 5. The answer should be 5, but instead, this code prints 8. This code is accepted by Leetcode as a valid solution but is wrong.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
