### ISSUE TITLE
Missing Test Case - 1705. Maximum Number of Eaten Apples

### ISSUE THREAD

**Issue by kretash** [LeetCode-Feedback/LeetCode-Feedback#1785]
#### Your LeetCode username
kretash

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Missing test case

#### Code you used for Submit/Run operation

```
    int eatenApples(vector<int>& apples, vector<int>& days)
    {
        int last_day = 0;
        for( int i = 0; i < days.size(); ++i )
            last_day = max( last_day, i+days[i] );
            
        vector<int> todo( last_day+1, 0 );
        vector<int> remove( last_day+1, 0 );
        
        for( size_t i = 0; i < days.size(); ++i )
        {
            todo[i] += apples[i];
            remove[i+days[i]] += apples[i];
        }
        
        int have = 0, eaten = 0, step = 0;
        for( int i = 0; i <= last_day; ++i )
        {
            have += todo[i];
            if( remove[i] > 0 )
            {
                have -= max( 0, remove[i]-step );
                step = max( 0, step-remove[i] );
            }
            if( have > 0 )
                ++step, ++eaten, --have;
        }
        
        return eaten;
    }
```

#### Language used for code
C++

#### Expected behavior
[1,3]
[3,1]
Returns Wrong Answer but the code passes all test cases.

**Comment by VasE1980** [comment]
https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/1773

**Comment by lc-kay** [comment]
@kretash Please provide your code in the [Playground](https://leetcode.com/playground/new/empty). Thank you for your time!

**Comment by lc-kay** [comment]
Hi @kretash 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
