### ISSUE TITLE
Hint 2 Link Broken - 210. Course Schedule II

### ISSUE THREAD

**Issue by abhishek1208** [LeetCode-Feedback/LeetCode-Feedback#17867]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Link to video is broken

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/22224172/c72e467e-825e-4c2d-8139-6f7bd4ec8970)

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/22224172/b136d0e2-1d3e-41ac-b61f-02d483b42ff4)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
