### ISSUE TITLE
Mistake in 1921. Eliminate Maximum Number of Monsters

### ISSUE THREAD

**Issue by Hr1t1k** [LeetCode-Feedback/LeetCode-Feedback#17868]
#### Your LeetCode username

Hritik__k

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ .] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the problem [1921. Eliminate Maximum Number of Monsters](https://leetcode.com/problems/eliminate-maximum-number-of-monsters/) there is a spelling mistake in the example 1 explanation, where the word "third" is miss spelled as "thrid"  but it should be "third".

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/52287344/8c5eb0e9-5d03-455e-8f06-64476952bef2)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
