### ISSUE TITLE
188. 买卖股票的最佳时机 IV | 数据增强

### ISSUE THREAD

**Issue by zerotrac** [LeetCode-Feedback/LeetCode-Feedback#1786]
**Bug 类型**

- [x] 测试数据

**描述**

实际测试数据中的 `k` 与题目描述不一致。

**你使用的语言**

C++

**你提交或者运行的代码**

提供一份错误的代码，见 [超简洁代码，借用123题大佬的思路，并加个哨兵节点。](https://leetcode-cn.com/problems/best-time-to-buy-and-sell-stock-iv/solution/chao-jian-ji-dai-ma-jie-yong-123ti-da-lao-de-si-lu/)。该方法直接使用了一个长度为 `k` 的数组，显然是会超出空间限制的。

**期望行为**

在题目中，`k` 的范围规定的是小于等于 `10^9`，而经过测试，所有实际测试数据中最大的 `k` 也只有 `100`，因此会导致错误的方法通过所有的测试数据。

**添加新的测试数据**

需要添加两组新的测试数据，第一组 `k=500`，第二组 `k=10^9`，数组 `prices` 的长度为最大值 `1000`，其中的元素值按照题目中的范围随机生成即可。

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前题目已更新。
