### ISSUE TITLE
Typo in the question "1921. Eliminate Maximum Number of Monsters"

### ISSUE THREAD

**Issue by abhinav7895** [LeetCode-Feedback/LeetCode-Feedback#17864]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases

#### Description of the bug
The typo in the question "1921. Eliminate Maximum Number of Monsters" is in Example 1. In the explanation section, it mentions "thrid," which should be corrected to "third."

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior
I expected the word "thrid" to be spelled correctly as "third" in the example explanation.

#### Screenshots
![Screenshot of the LeetCode site](https://imgur.com/35HDLt5)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
