### ISSUE TITLE
1616. Split Two Strings to Make Palindrome

### ISSUE THREAD

**Issue by daqingwax** [LeetCode-Feedback/LeetCode-Feedback#1787]
#### Your LeetCode username

daqingwax

#### Category of the bug
- [ ] Question
- [ X] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
class Solution(object):
    def checkPalindromeFormation(self, a, b):
        """
        :type a: str
        :type b: str
        :rtype: bool
        """
        if len(a) == 1:
            return True  
        b = b[::-1] # reverse string b
        return (a[0] == b[0] and a[1] == b[1]) or (a[-1] == b[-1] and a[-2] == b[-2]) # search for same substrings : 1) start from head(a_prefix + b_suffix) 
																												# 2) start from tail(b_prefix + a_suffix).
```

#### Expected behavior

"pvhmupgqeltozftlmfjjde"
"yjgpzbezspnnpszebzmcvp"
this testcase generate mismatched result, however the solution is accepted.

#### Screenshots

Runtime: 20 ms, faster than 97.89% of Python online submissions for Split Two Strings to Make Palindrome.
Memory Usage: 15.3 MB, less than 98.95% of Python online submissions for Split Two Strings to Make Palindrome.
Next challenges:

**Comment by lc-kay** [comment]
Hi @daqingwax 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @daqingwax 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
