### ISSUE TITLE
Incorrect testcase expected result for 288. Unique Word Abbreviation incorrect expected result makes wrong solution pass the OJ

### ISSUE THREAD

**Issue by Kapploneon** [LeetCode-Feedback/LeetCode-Feedback#1788]
#### Your LeetCode username

https://leetcode.com/Kapple/

#### Category of the bug
- [ ] Question
288. Unique Word Abbreviation
- [ ] Solution
Need to add 1 more testcase: 
["ValidWordAbbr","isUnique","isUnique"]
[[["a","a"]],["a"],["b"]]
- [ ] Language
Java

#### Description of the bug

The OJ is not sufficiently checking the testcases which make the incorrect solution pass the OJ.
Without the test case 
["ValidWordAbbr","isUnique","isUnique"]
[[["a","a"]],["a"],["b"]]
The OJ passes my incorrect submission, as the below test case is giving wrong expected result
["ValidWordAbbr","isUnique","isUnique"]
[[["a","a"]],["a"],["b"]]

Expected: [null,true,true]

Should be [null,true,false]

#### Code you used for Submit/Run operation

```
class ValidWordAbbr {

    Map<String, String> map;
    public ValidWordAbbr(String[] dictionary) {
        map = new HashMap<>();
        for(String s : dictionary){
            String ab = "";
            if(s.length() > 2){
                ab = Character.toString(s.charAt(0)) + (s.length() - 2) + Character.toString(s.charAt(s.length() - 1));
            }else{
                ab = s;
            }
            if(map.containsKey(ab))
                map.put(ab, "");
            else
                map.put(ab, s);
        }
    }
    
    public boolean isUnique(String word) {
        String ab = "";
        if(word.length() > 2){
            ab = Character.toString(word.charAt(0)) + (word.length() - 2) + Character.toString(word.charAt(word.length() - 1));
        }
        
        if(map.containsKey(ab)){
            return map.get(ab).equals(word);
        }
        
        return true;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The submission should fail. Which is currently passing as shown in the below screenshot. 

#### Screenshots

![image](https://user-images.githubusercontent.com/4435335/103176938-7c437c80-483b-11eb-9c79-46c7e72096b1.png)

**Comment by lc-kay** [comment]
@Kapploneon Can you please provide an explanation as to why you think the expected should be [null,true,false] for the test case ["ValidWordAbbr","isUnique","isUnique"]
[[["a","a"]],["a"],["b"]]?

**Comment by Kapploneon** [comment]
@lc-kay okay, I re-read the question, my bad. The question does not say that the word has to be part of the dictionary. In that case, my concern is invalid. Thanks for getting back on this. Have a good year ahead!

**Comment by lc-kay** [comment]
@Kapploneon I'm glad to see that your issue has been resolved. Happy New Year!
