### ISSUE TITLE
Wrong time complexity on problem 560

### ISSUE THREAD

**Issue by Mahdi-Hosseinali** [LeetCode-Feedback/LeetCode-Feedback#179]
**What kind of the bug**
- [ ] problem
- [x] solution
- [ ] language

**Describe the bug**
The time complexity of solutions 1 to 3 are off. The inner loop runs from 1 to n (it's n when the outer loop is at the start and it is 1 when the outer loop is at the end). So the complexity is P(sqrt(n)). Now the complexities will be:
solution 1: outer loop O(n), inner loop O(sqrt(n)), summation O(sqrt(n)) => total O(n^2)
solution 2: outer loop O(n), inner loop O(sqrt(n)), summation O(1) => total O(n*sqrt(n))
                   The cumulative sum is O(n) which is smaller than the total and doesn't count
Solution 3: same as solution 2.

**Comment by CooperCooperCooper** [comment]
Hi @Mahdi-Hosseinali,
Thank you for reaching out to us! I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @Mahdi-Hosseinali ,
Thank you for raising the issue, it seems for us that the time complexity in the article is correct. Your mistake is claiming O(sqrt(n)) for the inner loop. Please find a very detailed exact computation of the time complexity for the approach 1 in the attachment.
![image (1)](https://user-images.githubusercontent.com/59751300/81029449-de2d1d00-8e39-11ea-8153-c073d5292405.png)
