### ISSUE TITLE
Incorrenct Test Case - 32. Longest Valid Parentheses

### ISSUE THREAD

**Issue by asthasharma017** [LeetCode-Feedback/LeetCode-Feedback#1790]
#### Category of the bug
- [ ] Question
- [. ] Solution
- [ ] Language

#### Description of the bug

Test case with input - ""
expected output = 0
my code's output = 0 when I sun separate. It's 4 when I submit.

#### Code you used for Submit/Run operation

```
static int maxLen=0;
    public int longestValidParentheses(String s) {
        helper(s, 0, 0, 0);
        return maxLen;
    }
    
    void helper(String s, int idx, int lenSoFar, int isValid){
        if(isValid==0){
            maxLen = Math.max(maxLen, lenSoFar);
        }
        if(isValid<0 || idx==s.length())
            return;
        helper(s, idx+1, lenSoFar+1, s.charAt(idx)=='(' ? isValid+1 : isValid-1);
        
        helper(s, idx+1, lenSoFar, isValid);
    }
```

#### Expected behavior

Test case with input - ""
expected output = 0
Output should be 0 when I submit for test case input - "". It shows 4. 
Though it shows 0 when I run separately on input - "".

#### Screenshots

![image](https://user-images.githubusercontent.com/8735455/103181034-427d7080-4851-11eb-8c64-f567b7f979a7.png)
![image](https://user-images.githubusercontent.com/8735455/103181035-44dfca80-4851-11eb-9a77-4a53120a61df.png)

**Comment by lc-kay** [comment]
Hi @asthasharma017 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
