### ISSUE TITLE
Bad explanation (GIF) of the question - 1206. Design Skiplist

### ISSUE THREAD

**Issue by stevenhgs** [LeetCode-Feedback/LeetCode-Feedback#17909]
#### Your LeetCode username
stevenhgs

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The description of this problem is very impractical. There is a GIF explaining the problem. This is very impractical since there is no way to pause the GIF or go back to the previous step to understand what is going on and what you have to implement. There is also a link, but you should not have to go to a different website to understand what the problem is.

#### Code you used for Submit/Run operation
N/A

#### Language used for code
N/A

#### Expected behavior
Either fully explain how the skip list works or use separate pictures instead of a GIF. This way a user can study each picture individually and comprehend the steps instead of looking at the GIF. With the GIF there is no way to "go back" to the previous step or to "pause" the GIF.

#### Screenshots
N/A

#### Additional context
N/A

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
