### ISSUE TITLE
Missing Test Case - 2806. Account Balance After Rounded Purchase

### ISSUE THREAD

**Issue by abdullahhkhann** [LeetCode-Feedback/LeetCode-Feedback#17907]
#### Your LeetCode username
abdullahh_khann

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
It mentions the constraints is between 0 and 100, we need to add a test case that tests whether or not the solution frovides error handling for that constraint. For example, the code should throw and error if an input value is outside the range of 0 and 100.

#### Code you used for Submit/Run operation

```
/**
 * @param {number} purchaseAmount
 * @return {number}
 */
var accountBalanceAfterPurchase = function(purchaseAmount) {

    if (purchaseAmount < 0 || purchaseAmount > 100) throw new Error("Purchase Amount must be between 0 & 100");

    return 100 - Math.round(purchaseAmount / 10) * 10;
};
```

#### Language used for code
JavaScript

#### Expected behavior

I expected there to be a test case testing the constraint but I tried another solution without testing the error, and it still worked.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
