### ISSUE TITLE
Isomorphic Strings test case error

### ISSUE THREAD

**Issue by al-ro** [LeetCode-Feedback/LeetCode-Feedback#17912]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In https://leetcode.com/problems/isomorphic-strings the passing of new test cases introduced in https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/17347 is broken.

#### Expected behavior

A stated condition of the problem is that the strings are the same length. However, with test case 46 and later
```
s = "12"
t = "\u0067\u0067"
```
querying their lengths gives `2` and `10`. The second string is not interpreted as the encoded values. Querying `t[0]` gives `\` and not `g`. 

Either the string is passed in as a correct ASCII interpretation, the code should reject unequal length strings or the requirement that passed strings have the same length should be removed with an added instruction to convert the information before evaluation.

#### Language used for code

C++

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've used your feedback to update the problem.

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback.

Please provide us your Leetcode Username .

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
