### ISSUE TITLE
Missing Test Case - 80. Remove Duplicates from Sorted Array II

### ISSUE THREAD

**Issue by acse-hy23** [LeetCode-Feedback/LeetCode-Feedback#17917]
#### Your LeetCode username

[user9568b](https://leetcode.com/user9568b)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
To fully test the logic, please add a test case like:

nums = [1]

The expected output would be 1 in this case, since the single element should be kept once. Having this test case would validate that the logic works properly even for an array with only one element.

#### Code you used for Submit/Run operation

```
class Solution:
    def removeDuplicates(self, nums: List[int]) -> int:
        n = len(nums)
        fast = slow = 2
        while fast < n:
            if nums[fast] != nums[slow-2]:
                nums[slow] = nums[fast]
                slow += 1
            fast += 1
        return slow
```

#### Language used for code
Python3

#### Expected behavior
[1]

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

![Screen Shot 2023-11-13 at 4 52 52 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/98cee314-fbd5-4b17-bb73-0312d7319564)

The judge is working correctly .

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
