### ISSUE TITLE
Test case problem in 482. License Key Formatting

### ISSUE THREAD

**Issue by kenlau46** [LeetCode-Feedback/LeetCode-Feedback#17919]
#### Your LeetCode username

kenlau

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Using the following test case on "Testcase" session
`s = "---"`
`k = 3`
The online judge/reply gave empty output, please see the screenshot section

#### Code you used for Submit/Run operation

My submission which passed the above case:
https://leetcode.com/submissions/detail/1093969143/

#### Language used for code

C

#### Expected behavior

The output in "Testcase" session should give the answer instead of leave it empty. In this case should reply `""`.
It seems the online judge cannot handle the test case.

#### Screenshots

<img width="634" alt="Screenshot 2023-11-08 at 00 11 32" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/7280584/8dda0c60-9f0c-457c-916e-1cc7c144f1f8">

#### Additional context

This issue is clone of 
https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/15322
https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/16991
The above issues are closed while in "waiting for reply" state so this ticket is created.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
