### ISSUE TITLE
Confusing Time Complexity - 48. Rotate Image

### ISSUE THREAD

**Issue by makstaks** [LeetCode-Feedback/LeetCode-Feedback#1791]
#### Your LeetCode username

h6e2

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language

#### Description of the bug

The time complexity of the first approach - transpose + reversal is unclear.  Not sure if O(N^2) means quadratic runtime growth.

The matrix is `n X n`, let `N` denote the number of items in the matrix.  The solution shows we are iterating through each item in the matrix, and doing this twice.  Following, Big-O notation conventions, O(N^2) means quadratic growth.  However, the runtime I believe does not grow O(N^2), but is instead linear to the number of cells in the matrix `O(2N)` or `O(N)`.

Haven't checked the other approaches time complexity.

#### Code you used for Submit/Run operation

N/A

#### Language used for code

N/A

#### Expected behavior

N/A

#### Screenshots

N/A

#### Additional context

N/A

**Comment by lc-kay** [comment]
Hi @makstaks 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@makstaks  Thanks for your report. We agree with you: it's confusing to label it as O(N^2), and so instead we're going to go with O(M). This article also needs other updates, so this change will be made as part of that. Thanks again :-)
