### ISSUE TITLE
Missing Test Case - 1447. Jump Game IV

### ISSUE THREAD

**Issue by jthemphill** [LeetCode-Feedback/LeetCode-Feedback#1792]
#### Your LeetCode username

jthemphill

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

I added a dubious optimization to handle the 50,000-element case. This optimization passed all test cases, but shouldn't have. You can disqualify my solution by adding the test case `[7,7,2,1,7,7,7,3,4,1]`.

#### Code you used for Submit/Run operation

```python3
class Solution:
    def minJumps(self, arr: List[int]) -> int:
        
        jumps = defaultdict(list)
        for i, n in enumerate(arr):
            if jumps[n][-2:] == [i - 2, i - 1]:
                jumps[n][-2] = jumps[n][-1]
                jumps[n][-1] = i
            else:
                jumps[n].append(i)
        
        seen = set()
        to_visit = deque([(0, 0)])
        while to_visit:
            dist, i = to_visit.popleft()
            if i == len(arr) - 1:
                return dist
            if not (0 <= i < len(arr)):
                continue
            if i in seen:
                continue
            seen.add(i)
            to_visit.append((dist + 1, i + 1))
            to_visit.append((dist + 1, i - 1))
            for jmp in reversed(jumps[arr[i]]):
                to_visit.append((dist + 1, jmp))
        return len(arr) - 1
```

#### Language used for code
Python3

#### Expected behavior

My code should fail a test case like `[7,7,2,1,7,7,7,3,4,1]`

**Comment by lc-kay** [comment]
Hi @jthemphill 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @jthemphill 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
