### ISSUE TITLE
Missing Test Case - 443. String Compression

### ISSUE THREAD

**Issue by AHENG7** [LeetCode-Feedback/LeetCode-Feedback#17928]
### Problem number, title, and link

443. String Compression
https://leetcode.com/problems/string-compression/?envType=study-plan-v2&envId=leetcode-75

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [^ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The detection of "chars" list is wrong and the character like "2" is changed to "a".

### Language used for code

Python3

### Code used for Submit/Run operation

```
class Solution:
    def compress(self, chars: List[str]) -> int:
        prev=float("inf")
        res=[]
        for i in chars:
            if i!=prev:
                res.append(i)
                prev=i
            elif i==prev:
                if type(res[-1])==str:
                    res.append(2)
                elif type(res[-1])==int or type(res[-1])==float:
                    res[-1]+=1
        temp="".join([str(item) for item in res])
        chars=list(temp)
        return len(chars)
```

### Expected behavior

The result list "chars" should be ['a', '2', 'b', '2', 'c', '3'], but the compiler always detect it as ['a', 'a', 'b', 'b', 'c', 'c']

### Screenshots

<img width="290" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/113983813/31c1a414-a51e-4239-b0cd-3ef96075d912">

**Comment by AHENG7** [comment]
Misunderstand the description.

**Comment by KunalKrishna** [comment]
The question demands :  `int `as return type.

 `public int compress(char[] chars)`

But upon running the code, it shows 
**Expected**
["a","2","b","2","c","3"]

which seems absurd. it should suggest

Expected: 6 (i.e. length of the expected array )
