### ISSUE TITLE
`4. Median of Two Sorted Arrays`: Description and Editorial give inconsistent runtime complexities

### ISSUE THREAD

**Issue by ekhahniii** [LeetCode-Feedback/LeetCode-Feedback#17920]
#### Your LeetCode username
ekhahniii

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Description requires `O(log(m+n))` runtime. No solution provides that runtime complexity. Is this expected?

Given time/space complexities for each solution:

1. `O(m+n)`; `O(1)`
2. `O(log(mn))`; `O(log(mn))`
3. `O(log(min(m, n)))`; `O(1)`

#### Expected behavior
Consistent runtime complexities.

**Comment by yumkam** [comment]
Disclaimer: I'm just another leetcode user
As `min(m,n) < m+n`, so solutions with `O(log min(m,n))` matches requirements from description.

**Comment by ekhahniii** [comment]
> As `min(m,n) < m+n`, so solutions with `O(log min(m,n))` matches requirements from description.

@yumkam I think this is not the best interpretation of the requirement: "The overall run time complexity should be O(log (m+n))." As stated, this requirement expects an algorithm with _exactly_ `Olog(m+n))` run time complexity, and it is therefore reasonable to expect a corresponding solution to be provided. If the author intends for the interpretation you suggest, it is less confusing to explicitly state that, e.g. "run time complexity not worse than `O(log(m+n))`.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by yumkam** [comment]
> > As `min(m,n) < m+n`, so solutions with `O(log min(m,n))` matches requirements from description.
> 
> @yumkam I think this is not the best interpretation of the requirement: "The overall run time complexity should be O(log (m+n))." As stated, this requirement expects an algorithm with _exactly_ `O(log(m+n))` run time complexity, and it is therefore reasonable to expect a corresponding solution to be provided. If the author intends for the interpretation you suggest, it is less confusing to explicitly state that, e.g. "run time complexity not worse than `O(log(m+n))`.

It's property of `O()`, not interpretation. If `h(x) = O(f(x))` and `f(x) <= g(x)`, then `h(x) = O(g(x))` is also true.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

Both approach 2 and 3 have the time complexity of the same order of magnitude as $O(log(m + n))$

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
