### ISSUE TITLE
Incorrect/Buggy Test Case - 205. Isomorphic Strings

### ISSUE THREAD

**Issue by Saksham-Gupta-off** [LeetCode-Feedback/LeetCode-Feedback#17929]
### LeetCode Username

Saksham-Gupta-off

### Problem number, title, and link

205. Isomorphic Strings https://leetcode.com/problems/isomorphic-strings/

### Category of the bug
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### Description of the bug

s = "12", t = "\u0067\u0068"
This testcase needs to get accepted to solve the problem. While the ascii references are ok, the checker takes 't' as a whole string instead of it's character maps. Thus the answer should be 'false'. It comes out as 'false' with some scripts, but 'true' with others.

### Language used for code

C++ 

### Code used for Submit/Run operation

```
class Solution {
public:
    bool isIsomorphic(string s, string t) {
        if(s.length() != t.length()) return false;
        int n = s.length();
        map<char, char> s2t;
        for(int i = 0; i < n; i++){
            if(s2t.find(s[i]) == s2t.end()) s2t[s[i]] = t[i];
            else if (s2t[s[i]] != t[i]) return false;
        }
        map<char, char> t2s;
        for(int i = 0; i < n; i++){
            if(t2s.find(t[i]) == t2s.end()) t2s[t[i]] = s[i];
            else if (t2s[t[i]] != s[i]) return false;
        }
        return true;
    }
};
```

### Expected behavior

It should give false with testcase s ="12", t = "\u0067\u0068", which it gives, but checker demands true.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/81560405/508f1d9f-7817-4468-9b5c-e803c3f294c7)

**Comment by gokulcodes** [comment]
@Saksham-Gupta-off

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
