### ISSUE TITLE
错误的问题限制 - LCR 162. 数字 1 的个数

### ISSUE THREAD

**Issue by qbh16** [LeetCode-Feedback/LeetCode-Feedback#17934]
### LeetCode 用户名
[FatalError](https://leetcode.cn/u/fatalerror-i/)

### 问题号码、标题和链接
[LCR 162. 数字 1 的个数](https://leetcode.cn/problems/1nzheng-shu-zhong-1chu-xian-de-ci-shu-lcof/)

### Bug 类型
- [ ] 问题描述
- [ ] 示例
- [x] 问题限制
- [ ] 问题提示
- [ ] 不正确或缺少“相关标签”
- [ ] 不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*
- [ ] 缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*
- [ ] 力扣官方题解
- [ ] 编程语言支持

### 描述
在题目的数据范围下，当输入值很大时，标程会由于int32溢出而得到错误结果。官方测试用例不包含此类输入；能通过题目的代码会在满足条件的自定义测试用例上得到错误结果。

### 你使用的语言
Python3

### 你提交或者运行的代码

``` Python
class Solution:
    def digitOneInNumber(self, num: int) -> int:
        digits = list(map(int, str(num)))
        n = len(digits)

        @cache
        def dfs(i, cnt, hilim):
            if i == n:
                return cnt
            hid = digits[i] if hilim else 9
            res = 0
            for d in range(hid+1):
                res += dfs(i+1, cnt + (d == 1), hilim and d == hid)
            return res

        return dfs(0, 0, True)
```

### 期望行为
题目所给的数据范围是`1 <= num < 2^31`，然而较大的`num`会因为溢出导致标程错误结果。如：

自定义测试用例1：

输入：
```
1633388154
```
输出：
```
2147483646
```
预测结果：
```
2147483646
```

自定义测试用例2：

输入：
```
1633388155
```
输出：
```
2147483648
```
预测结果：
```
-2147483648
```

建议修改数据范围与主站[233. 数字 1 的个数](https://leetcode.cn/problems/number-of-digit-one/)描述一致。

**Comment by amcones** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by qbh16** [comment]
https://leetcode.cn/u/fatalerror-i/
