### ISSUE TITLE
Missing Test Case - 2352. Equal Row and Column Pairs

### ISSUE THREAD

**Issue by sanchay9** [LeetCode-Feedback/LeetCode-Feedback#17938]
#### Your LeetCode username
sanchay_

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Below solution gives Accepted verdict on LeetCode, even though it fails for this testcase.
```
[[2,3,4],[6,1,7],[8,5,9]]
```
#### Code you used for Submit/Run operation

```
// 2352. Equal Row and Column Pairs
class Solution {
public:
    int equalPairs(vector<vector<int>>& G) {
        int n = int(G.size());
    
        int ans = 0;
        map<pair<int, int>, int> mp;
        for (auto x : G) {
            int val = 0, sum = 0;
            for (int j = 0; j < n; j++) {
                sum += x[j];
                val += x[j] * j;
            }
            ++mp[{val, sum}];
        }
    
        for (int j = 0; j < n; j++) {
            int val = 0, sum = 0;
            for (int i = 0; i < n; i++) {
                sum += G[i][j];
                val += G[i][j] * i;
            }
            ans += mp[{val, sum}];
        }
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Verdict should be `Wrong Answer` instead of `Accepted` as the solution fails for this testcase.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
