### ISSUE TITLE
Go language support - 1660. Correct a Binary Tree

### ISSUE THREAD

**Issue by regotiss** [LeetCode-Feedback/LeetCode-Feedback#17946]
### LeetCode Username

nomadsomad

### Problem number, title, and link

1660. Correct a Binary Tree https://leetcode.com/problems/correct-a-binary-tree/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [x] Programming language support

### Description of the bug

Limited language support to submit code for this problem

### Language used for code

I wanted to use Golang but had to submit it in Java as Golang was not a supported language for this problem.

### Code used for Submit/Run operation

```java
class ParentInfo {
    TreeNode parent;
    boolean isLeftChild;
    ParentInfo(TreeNode parent, boolean isLeftChild) {
        this.parent = parent;
        this.isLeftChild = isLeftChild;
    }
}

class Solution {
    public TreeNode correctBinaryTree(TreeNode root) {
        Map<TreeNode, ParentInfo> parents = new HashMap<>();
        parents.put(root, new ParentInfo(null, true));

        Queue<TreeNode> q = new LinkedList<>();
        q.add(root);

        while(q.size() > 0) {
            TreeNode node = q.poll();
            if(node.left != null) {
                q.add(node.left);
                parents.put(node.left, new ParentInfo(node, true));
            }

            if(node.right == null) {
                continue;
            }

            if(parents.containsKey(node.right)) {
                ParentInfo parentInfo = parents.get(node);
                if(parentInfo.isLeftChild) {
                    parentInfo.parent.left = null;
                }  else {
                    parentInfo.parent.right = null;
                }
                break;
            }

            q.add(node.right);
            parents.put(node.right, new ParentInfo(node, false));
        }
        return root;
    }
}
```

### Expected behavior

I submitted java but want to practice coding in Golang. Could you please support Golang for this problem as well?

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've submitted your feedback to the team. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
