### ISSUE TITLE
Explore Card - Sorting | Provided radix sort solution has errors

### ISSUE THREAD

**Issue by regotiss** [LeetCode-Feedback/LeetCode-Feedback#17945]
### LeetCode Username
nomadsomad

### Problem number, title, and link

Explore Card | Sorting -  Radix Sort - https://leetcode.com/explore/learn/card/sorting/695/non-comparison-based-sorts/4438/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
Java code provided for radix sort implementation has compilation errors.

### Language used for code
Java

### Leetcode solution for radix sort

```java
public class Solution {
    private static final int NUM_DIGITS = 10;

    public void initializeSortedArray(int size) {   // <---- this function is not required  
        if (mSortedArray == null) {     // <--- mSortedArray is not found
            mSortedArray = new int[size];
        }
    }

    public void countingSort(int[] arr, int placeVal) {
        // Sorts an array of integers where minimum value is 0 and maximum value is K
        int[] counts = new int[K];      // <--- K not found

        for (int elem : arr) {
            int current = elem / placeVal;
            counts[current % NUM_DIGITS] += 1
        }

        // we now overwrite our original counts with the starting index
        // of each digit in our group of digits
        int startingIndex = 0;
        for (int i = 0; i < mCounts.length; i++) {     // <-- mCounts not found. should be counts.
            int count = counts[i];
            counts[i] = startingIndex;
            startingIndex += count;
        }

        int[] sortedArray = new int[arr.length];
        for (int elem : arr) {
            int current = elem / placeVal;
            sortedArray[counts[current % NUM_DIGITS]] = elem;
            // since we have placed an item in index mCounts[current % NUM_DIGITS],
            // we need to increment mCounts[current % NUM_DIGITS] index by 1 so the
            // next duplicate digit is placed in appropriate index
            counts[current % NUM_DIGITS] += 1;
        }

        // common practice to copy over sorted list into original arr
        // it's fine to just return the sortedArray at this point as well
        for (int i = 0; i < arr.length; i++) {
            arr[i] = sortedArray[i];
        }
    }

    public void radixSort(int[] arr) {
        int maxElem = Integer.MIN_VALUE;
        for (int elem : arr) {
            if (elem > maxElem) {
                maxElem = elem;
            }
        }

        int placeVal = 1;
        while (maxElem / placeVal > 0) {
            countingSort(arr, placeVal);
            placeVal *= 10;
        }
    }
}
```

### Expected behavior
 Commented in the above code, there are compilation errors, please look into it. 
We can remove the unused `initializeSortedArray` method and I think instead of K we should use `NUM_DIGITS` and instead of mCounts, we should use counts.  

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/13028369/64fd6418-cc95-4786-a035-b526387d5462)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
