### ISSUE TITLE
Error in server-side processing - 110. Balanced Binary Tree

### ISSUE THREAD

**Issue by jitendrac** [LeetCode-Feedback/LeetCode-Feedback#1794]
#### Your LeetCode username

Jitendrac

#### Category of the bug
- [1] Solution

#### Description of the bug

Output of same case Tree=[], for test-code and serverside are different.

#### Code you used for Submit/Run operation

```
/**
 * Definition for a binary tree node.
 * function TreeNode(val, left, right) {
 *     this.val = (val===undefined ? 0 : val)
 *     this.left = (left===undefined ? null : left)
 *     this.right = (right===undefined ? null : right)
 * }
 */

var leaf_levels=[];

// From Stackoverflow
// Use:Array.filter(onlyUnique)
function onlyUnique(value, index, self) {
  return self.indexOf(value) === index;
}
function traverse(root,level=0){
    if(root==null)return;
    if(root.left!=null){
        traverse(root.left,level+1);
    }else{
        leaf_levels.push(level);
    }
    if(root.right!=null){
        traverse(root.right,level+1);
    }else{
        leaf_levels.push(level);
    }
}
/**
 * @param {TreeNode} root
 * @return {boolean}
 */
var isBalanced = function(root) {
    traverse(root);
    levels=leaf_levels.filter(onlyUnique);
    //return levels.length==2;
    if(levels.length<=1){
        return true;
    }
    if(levels.length>2){
        return false;
    }
    return Math.abs(levels[0]-levels[1])<=1;
    
    
};
```

#### Language used for code

Javascript

#### Expected behavior

Solution should be accepted

#### Screenshots

![image](https://user-images.githubusercontent.com/1154328/103203443-f1d24a00-491a-11eb-9409-bb050163a590.png)

**Comment by lc-kay** [comment]
@jitendrac 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
