### ISSUE TITLE
Leetcode issue problem 227

### ISSUE THREAD

**Issue by Era-cell** [LeetCode-Feedback/LeetCode-Feedback#17957]
### LeetCode Username
zNuke

### Problem number, title, and link
227. Basic Calculator II (https://leetcode.com/problems/basic-calculator-ii/)

### Category of the bug

- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### Description of the bug
"1+2*5/3+6/4*2" the answer for this test case should be 9 if rounded to tens place,
But expected output: 6

### Language used for code
Python

### Code used for Submit/Run operation

```
import re
import math
class Solution(object):
    def calculate(self, s):
        """
        :type s: str
        :rtype: int
        """
        s=re.findall(r'\d+|[*/\-+]',s)
        s=[str(i) for i in s if i!=' ']
        i=0
        while(i<len(s)-1):
            if s[i+1]=='/': 
                n=(float(s[i])/float(s[i+2]))
                s= s[:i] + [n//1 if n-(n//1) <=0.5 else (n//1)+1] + s[i+3:]
            else:i+=2
        i=0
        while(i<len(s)-1):
            if s[i+1]=='*':
                s= s[:i] + [(int(s[i])*int(s[i+2]))] + s[i+3:]
            else:i+=2
        i=0
        while(i<len(s)-1):
            if s[i+1]=='-':
                s= s[:i] + [(int(s[i])-int(s[i+2]))] + s[i+3:]
            else:i+=2
        i=0
        while(i<len(s)-1):
            if s[i+1]=='+':
                s= s[:i] + [int(s[i])+int(s[i+2])] + s[i+3:]
            else:i+=2
        return int(s[0])
```

### Expected behavior
9 if rounded else 5 if floor value of division

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
