### ISSUE TITLE
Missing Test Case - Problem #1759 - Count Number of Homogenous Substrings

### ISSUE THREAD

**Issue by secretSocrates** [LeetCode-Feedback/LeetCode-Feedback#17958]
### LeetCode Username
[secretSocrates](https://leetcode.com/secretSocrates/)

### Problem number, title, and link
[1759. Count Number of Homogenous Substrings](https://leetcode.com/problems/count-number-of-homogenous-substrings/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
In the problem, the size constraint of string ```s``` is <code>1 <= s.length <= 10<sup>5</sup></code>. Within these constraints, a long enough homogenous substring should throw a runtime error due to the way the code (given below) is designed. But no such testcase is present to stop this code from getting accepted.

So, here is my custom testcase: [1759_testcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/13309711/1759_testcase.txt)

### Language used for code
C++

### Code used for Submit/Run operation

```
class Solution 
{
public:
    int countHomogenous(string s) 
    {
        int MOD = 1e9 + 7;
        int len = s.size();
        long ans = 0;

        char c = s[0];
        int count = 1;
        for (int i=1; i<len; i++) 
        {
            char temp = s[i];
            if (temp == c) count ++;
            else {
                long l = (count * (count+1)) / 2;
                ans += l;
                ans = ans%MOD;

                c = temp;
                count = 1;
            }
        }
        // for after reading the last character
        if (count > 0) {
            long l = ((long)count * (count+1)) / 2;
            ans += l;
            ans = ans%MOD;
        }

        return (int)ans;
    }
};
```

### Expected behavior
The code given above should give the following error with the testcase ([1759_testcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/13309711/1759_testcase.txt)) I provided:
```
Line 17: Char 33: runtime error: signed integer overflow: 99999 * 100000 cannot be represented in type 'int' (solution.cpp)
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior prog_joined.cpp:26:33
```
Since my custom testcase is missing, the judge is accepting my wrong code (given above).

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/71689810/a978b749-3785-4536-a99c-3f972510831b)
<p align=center>&uarr; Wrong code getting accepted. &uarr;</p>

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/71689810/ad0167a5-7644-468b-a1ac-ccd8bccc8fdd)
<p align=center>&uarr; Custom testcase gives runtime error. &uarr;</p>

### Additional context

Code which passes mine as well as all the existing testcases:
```
class Solution 
{
public:
    int countHomogenous(string s) 
    {
        int MOD = 1e9 + 7;
        int len = s.size();
        long ans = 0;

        char c = s[0];
        int count = 1;
        for (int i=1; i<len; i++) 
        {
            char temp = s[i];
            if (temp == c) count ++;
            else {
                long l = ((long)count * (count+1)) / 2;
                ans += l;
                ans = ans%MOD;

                c = temp;
                count = 1;
            }
        }
        // for after reading the last character
        if (count > 0) {
            long l = ((long)count * (count+1)) / 2;
            ans += l;
            ans = ans%MOD;
        }

        return (int)ans;
    }
};
```
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/71689810/f82ba14b-7deb-44ec-aca9-5e35f18b0321)
<p align=center>&uarr; Correct code passing all testcases, including mine. &uarr;</p>

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
