### ISSUE TITLE
Missing Test Case - 1759. Count Number of Homogenous Substrings

### ISSUE THREAD

**Issue by icelam** [LeetCode-Feedback/LeetCode-Feedback#17955]
### LeetCode Username

icelam

### Problem number, title, and link

[1759. Count Number of Homogenous Substrings](https://leetcode.com/problems/count-number-of-homogenous-substrings/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Solution with incorrect modulo operation got accepted. It is clearly shown in the screenshot provided below that a custom test case with an output that exceeds the modulo value was accepted.

**"Run Code Result" with custom test case:**

> Note: Test case trimmed due to GitHub issue character limit. Please refer to the "Additional context" section for the complete test case attached as a TXT file.

```
Your input
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...

Output
1250050000

Expected
250049993
```

### Language used for code
Java

### Code used for Submit/Run operation
```java
class Solution {
  private static int MOD = (int) (1e9 + 7);
  
  public long arithmeticSum(int n) {
    long result = ((long) n * (n + 1)) / 2;
    return result % MOD;
  }
  
  public int countHomogenous(String s) {
    char[] characters = s.toCharArray();
    int n = characters.length;
    int result = 0;
    int start = 0;
    
    for (int i = 0; i < n; i++) {
      if (i > 0 && characters[i] != characters[i - 1]) {
        result += arithmeticSum(i - start);
        start = i;
      }
    }
    
    result += arithmeticSum(n - start);
    return result;
  }
}
```

### Expected behavior

The code above uses modulo operation to calculate the result of arithmetic sum using function `arithmeticSum(n)` but does not apply it to the `result` variable. As the returned value of `arithmeticSum(n)` is added to `result`, it is possible for `result` to exceed the modulo value. Submission should not be accepted if modulo operation is not performed on `result` itself.

### Screenshots

![FireShot Capture 005 - Count Number of Homogenous Substrings - LeetCode - leetcode com](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/6780420/e5d45685-205f-4b11-a561-62ad185030ea)

### Additional context
- Test Case used: [testcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/13308495/testcase.txt)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
