### ISSUE TITLE
Hint - 1759. Count Number of Homogenous Substrings

### ISSUE THREAD

**Issue by RohitSgh** [LeetCode-Feedback/LeetCode-Feedback#17953]
### LeetCode Username
RohitSgh

### Problem number, title, and link
**1759.** Count Number of Homogenous Substrings https://leetcode.com/problems/count-number-of-homogenous-substrings/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [x] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
Hint is incorrect. 

> ![Screenshot](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/81853910/7c0c9be3-5528-4ad1-aae7-eee6726f00e7)

### Expected behavior

**Given:** A string of only 'a's of length k contains k choose 2 homogenous substrings.

**Correct:** A string of only 'a's of length k contains (k + 1) choose 2 homogenous substrings. 

- k choose 2 is $\frac{k(k-1)}{2}$
- (k + 1) choose 2 is $\frac{k(k+1)}{2}$

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/81853910/9d932f4f-cc12-46f3-ba58-d02150d4eb4b)

### Additional context

https://en.wikipedia.org/wiki/Combination#Number_of_k-combinations

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
