### ISSUE TITLE
Buggy Test Case -589-  N-ary Tree Preorder Traversal

### ISSUE THREAD

**Issue by dudi-w** [LeetCode-Feedback/LeetCode-Feedback#17952]
### LeetCode Username
user0702l

### Problem number, title, and link

589.  N-ary Tree Preorder Traversal https://leetcode.com/problems/n-ary-tree-preorder-traversal/description/

### Category of the bug
- [x] Incorrect test Case

### Description of the bug

One of the test cases is [1, null]
And because there is a space character before the 'null', the following error is thrown:
*Runtime Error
38 / 39 testcases passed
terminate called after throwing an instance of 'std::invalid_argument'
   what(): stoi*

### Language used for code
C++

### Code used for Submit/Run operation

```cpp
class Solution {
public:
    vector<int> preorder(Node* root) {
        if(!root){
            return {};
        }
        vector<Node*> stack;
        vector<int> res;

        stack.push_back(root);
        while(!stack.empty()){
            root = stack.back();
            stack.pop_back();
            res.push_back(root->val);
            for(int i = root->children.size()-1; i >= 0 ; --i){
                stack.push_back(root->children[i]);
            }
        }
        return res;
    }
};
```

### Expected behavior

output: [1]

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/117650526/2abc4645-5695-4ce6-9b08-f0f7f232109c)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by PhilippShemetov** [comment]
**Same issue**

**LeetCode Username**
PhilippShemetov

**Problem number, title, and link**
N-ary Tree Preorder Traversal https://leetcode.com/problems/n-ary-tree-preorder-traversal/description/

**Category of the bug**
Incorrect test Case

**Description of the bug**

One of the test cases is [1, null]
And because there is a space character before the 'null', the following error is thrown:
Runtime Error
38 / 39 testcases passed
terminate called after throwing an instance of 'std::invalid_argument'
what(): stoi

**Language used for code**

C++

**Code used for Submit/Run operation**

```
class Solution {
public:
    vector<int> preorder(Node* root) {
        std::vector<int> preorder_val;
        Node* temp_root = root;
        if (!root) return preorder_val;
        preorder_val.push_back(root->val); 
        if (!root->children.size()) return preorder_val;
        std::stack<std::pair<Node*, int>> nodes;
        int step = 0;
        nodes.push(std::make_pair(temp_root, step));
        while(!nodes.empty()) {
            for (int i = step; i < temp_root->children.size(); i++) {
                if (temp_root->children[i]->children.size()) {
                    temp_root = temp_root->children[i];
                    preorder_val.push_back(temp_root->val);
                    nodes.top().second = i + 1;
                    i = -1;
                    nodes.push(std::make_pair(temp_root, 0));
                } else {
                    preorder_val.push_back(temp_root->children[i]->val);
                }
            }
            nodes.pop();
            if (!nodes.empty()) {
                temp_root = nodes.top().first;
                step = nodes.top().second;
            }
            
        }

        return preorder_val;
    }
};
```

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
