### ISSUE TITLE
Missing Test Case - 80. Remove Duplicates from Sorted Array II

### ISSUE THREAD

**Issue by urosceh** [LeetCode-Feedback/LeetCode-Feedback#17960]
### LeetCode Username
urosvceh

### Problem number, title, and link
80. Remove Duplicates from Sorted Array II: https://leetcode.com/problems/remove-duplicates-from-sorted-array-ii/description/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
You are either missing an assertion k == expectedNums.length or missing a test case where e.g. nums = [1].
The following code will, in this case, always return 2, and nums.length != 2

### Language used for code
Typescript

### Code used for Submit/Run operation
```
function removeDuplicates(nums: number[]): number {
    let k = 2

    for (let i = 2; i < nums.length; i++) {
        if (nums[i] !== nums[k-2]) {
            nums[k++] = nums[i]
        }
    }

    return k
};
```

### Expected behavior
This code should fail since if you have nums = [1] and function removeDuplicates(nums) returns 2, nums.length != 2.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
