### ISSUE TITLE
Missing Test Case - 26. Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by Rahulbud** [LeetCode-Feedback/LeetCode-Feedback#17969]
### Category of the bug
- [ ] Problem description
- [x] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```
class Solution {
    public int removeDuplicates(int[] nums) {
       
        int unique=nums.length;
		  
		   for(int i=0;i<unique;i++) {
			   
			    for(int j=i+1;j<unique-1;j++) {
			    	 
			    	if(nums[i]==nums[j]) {
			    		
			    		for(int k=j;k<unique-1;k++) {
			    			 
			    			nums[k]=nums[k+1];
			    		}unique--;j--;
			    	}
			    }
		   }
		   
		   
		   
		int []result=new int[unique];
		 System.arraycopy(nums, 0, result, 0, unique);
		
		return unique;
    }
}

**Comment by Rahulbud** [comment]
In this code you can see we are shifting the duplicate from right to left and modifing the length of array with unique

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
