### ISSUE TITLE
Unexpected strict time limit for C++ programming with -O1 optimization

### ISSUE THREAD

**Issue by zerotrac** [LeetCode-Feedback/LeetCode-Feedback#1796]
#### Your LeetCode username

zerotrac2

#### Facts

For `n=100000`, algorithms with big-O time complexity of `O(n log n)` or `O(n log^2 n)` and small constant should pass anyway.

A modern CPU executes ~ `3 * 10^8` operations (code lines, not CPU instructions) per second. Since `log n` ~ `17`, `O(n log n)` is about `1.7 * 10^6` operations while `O(n log^2 n)` is about `2.8 * 10^7` operations. If a small constant is bound to the big-O time complexity, it is obvious that an algorithm with `O(n log n)` or `O(n log^2 n)` time complexity could pass.

However, since `C++` now uses only -O1 optimization during compilation, there will be considerable overhead when using STL templates like `vector` or `string` which are frequently declared/defined in programming. This binds a big constant to the big-O time complexity, which will lead to a failure of some proper algorithms because the given executing time is not enough.

Below I will list two of the problems in the last weekly/bi-weekly contest, in which I write codes with a proper time complexity in C++ but failed due to the time limitation.

#### Examples

The first problem is 1702. The optimal algorithm is `O(n)` based on counting 0s and 1s. But we can also come up with an `O(n log n)` algorithm based on sorting. Here is the C++ code.

```
class Solution {
public:
    string maximumBinaryString(string s) {
        int n = s.size();
        for (int i = 0; i < n; ++i) {
            if (s[i] == '0') {
                sort(s.begin() + i, s.end());
                for (int j = i; j < n; ++j) {
                    if (s[j] == '0' && j + 1 < n && s[j + 1] == '0') {
                        s[j] = '1';
                    }
                    else {
                        break;
                    }
                }
                break;
            }
        }
        return s;
    }
};
```

It can pass every testcase but failed since the total time consumed for all the testcases exceeds (on LeetCode-CN). It is kind of unreasonable since `O(n log n)` is fairly suitable for `n=100000`. Here is the same Python code that can pass.

```
class Solution:
    def maximumBinaryString(self, s: str) -> str:
        n = len(s)
        for i, ch in enumerate(s):
            if s[i] == '0':
                l = list(s[:i]) + list(sorted(s[i:]))
                for j in range(i, n):
                    if l[j] == '0' and j + 1 < n and l[j + 1] == '0':
                        l[j] = '1'
                    else:
                        break
                s = "".join(l)
                break
        return s
```

Do you believe in magic? Let us modify the C++ code and operate the char array inside the string object directly.

```
class Solution {
public:
    string maximumBinaryString(string s) {
        int n = s.size();
        char* o = s.data();
        for (int i = 0; i < n; ++i) {
            if (s[i] == '0') {
                sort(o + i, o + n);
                for (int j = i; j < n; ++j) {
                    if (s[j] == '0' && j + 1 < n && s[j + 1] == '0') {
                        s[j] = '1';
                    }
                    else {
                        break;
                    }
                }
                break;
            }
        }
        return s;
    }
};
```

The total execution time reduces to ~700ms on LeetCode-CN and ~600ms on LeetCode-US. Can you believe `string` has such a dreadful overhead? 

Another problem is 1707 where an optimal Trie solution has time complexity `O(n log C)`, where `C` stands for `10^9`. But we can also come up with an `O(n log n log C)` solution based on the binary search for every bit. Here is the C++ code.

```
class Solution {
public:
    vector<int> maximizeXor(vector<int>& nums, vector<vector<int>>& queries) {
        sort(nums.begin(), nums.end());
        vector<int> ans;
        
        for (const auto& q: queries) {
            int x = q[0], m = q[1];
            if (nums[0] > m) {
                ans.push_back(-1);
            }
            else {
                int choose = 0;
                for (int i = 29; i >= 0; --i) {
                    if (x & (1 << i)) {
                        auto it = lower_bound(nums.begin(), nums.end(), choose);
                        if ((*it >> i) != (choose >> i)) {
                            choose += (1 << i);
                        }
                    }
                    else {
                        auto it = lower_bound(nums.begin(), nums.end(), choose + (1 << i));
                        if (it != nums.end() && *it <= m && (*it >> i) == (choose >> i) + 1) {
                            choose += (1 << i);
                        }
                    }
                }
                ans.push_back(x ^ choose);
            }
        }
        
        return ans;
    }
};
```

Unfortunately, it exceeds the total time. But the same Python code could pass.

```
class Solution:
    def maximizeXor(self, nums: List[int], queries: List[List[int]]) -> List[int]:
        nums.sort()
        ans = list()
        
        for x, m in queries:
            if nums[0] > m:
                ans.append(-1)
            else:
                choose = 0
                for i in range(29, -1, -1):
                    if x & (1 << i):
                        it = bisect_left(nums, choose)
                        if nums[it] >> i != choose >> i:
                            choose += 1 << i
                    else:
                        it = bisect_left(nums, choose + (1 << i))
                        if it != len(nums) and nums[it] <= m and nums[it] >> i == ((choose) >> i) + 1:
                            choose += 1 << i
                ans.append(x ^ choose)
        
        return ans
```

But let me show you the magic again. Let us operate on the array inside the vector directly.

```
class Solution {
public:
    vector<int> maximizeXor(vector<int>& nums, vector<vector<int>>& queries) {
        int* a = nums.data();
        int n = nums.size();
        sort(a, a + n);
        
        vector<int> ans;
        
        for (const auto& q: queries) {
            int x = q[0], m = q[1];
            if (nums[0] > m) {
                ans.push_back(-1);
            }
            else {
                int choose = 0;
                for (int i = 29; i >= 0; --i) {
                    if (x & (1 << i)) {
                        auto it = lower_bound(a, a + n, choose);
                        if ((*it >> i) != (choose >> i)) {
                            choose += (1 << i);
                        }
                    }
                    else {
                        auto it = lower_bound(a, a + n, choose + (1 << i));
                        if (it != a + n && *it <= m && (*it >> i) == (choose >> i) + 1) {
                            choose += (1 << i);
                        }
                    }
                }
                ans.push_back(x ^ choose);
            }
        }
        
        return ans;
    }
};
```

Then the code passes. What a considerable overhead inside `vector` without a proper level of optimization.

It shows that when -O1 optimization is given, C++ will consume a lot of time when using STL containers or algorithms, making a solution with fair time complexity fails.

#### Suggestions

I strongly suggest that -O2 optimization should be used in C++ compilation. Operating on the data inside the STL container in order to prevent the overhead is boring.

**Comment by lc-kay** [comment]
Hi @zerotrac 
Thank you for reaching out to us. I was only able to reproduce the issue for 1707 on the leetcode.com/us page. I've relayed this issue to our team to investigate.

**Comment by zerotrac** [comment]
Hi @lc-kay 
For 1702 you can just compare the consumed time before/after the magic optimization. The code which is claimed TLE runs ~1500ms which the optimized one runs ~600ms.

**Comment by lc-kay** [comment]
@zerotrac I've relayed this information to our team to look into.

**Comment by Ashish-Bansal** [comment]
@zerotrac Thanks for detailed description of the issue, really appreciate it! Your claims are true, we will fix it soon.

**Comment by lc-kay** [comment]
@zerotrac  Thank you for your time and support, we've enabled O2 optimization.
