### ISSUE TITLE
Missing Test Cases : 146. LRU Cache

### ISSUE THREAD

**Issue by sanchitkaul99** [LeetCode-Feedback/LeetCode-Feedback#1797]
The absence of the testcase that i am submitting is allowing a wrong solution to be accepted.
Kindly add this testcase to disallow these types of solutions.
Thanks!

The code gets accepted but for all the testcases that have 0(Zero) as a value should get wrong answer because its totally possible for a value to be zero.

TestCase 1-

Your input:
["LRUCache","put","put","get","put","get","put","get","get","get"]
[[2],[1,0],[2,2],[1],[3,3],[2],[4,4],[1],[3],[4]]
Output:
[null,null,null,-1,null,2,null,-1,-1,4]
Expected:
[null,null,null,0,null,-1,null,-1,3,4]

TestCase 2-
Your input:
["LRUCache","put","put","get","put","get","put","get","get","get"]
[[2],[1,1],[2,2],[1],[3,0],[2],[4,4],[1],[3],[4]]
Output:
[null,null,null,1,null,-1,null,-1,-1,4]
Expected:
[null,null,null,1,null,-1,null,-1,0,4]

class LRUCache {
public:
    unordered_map<int,int> lru;
    deque<int> keys;
    int cap;
    int curr =0;
    LRUCache(int capacity) {
        cap = capacity;
    }
    
    int get(int key) {
        if(lru[key] == 0)
        {
            return -1;
        }
        keys.erase(find(keys.begin(),keys.end(),key));
        keys.push_back(key);
        return lru[key];
    }
    
    void put(int key, int value) {
        if(lru[key]!=0)
        {
            lru[key] = value;
            keys.erase(find(keys.begin(),keys.end(),key));
            keys.push_back(key);
            return;
            
        }
        curr++;
        if(curr<=cap)
        {
            lru[key] = value;
            keys.push_back(key);
            return;
        }
        curr--;
        int k = keys[0];
        keys.pop_front();
        lru[k] = 0;
        lru[key] = value;
        keys.push_back(key);
    }
};

/**
 * Your LRUCache object will be instantiated and called as such:
 * LRUCache* obj = new LRUCache(capacity);
 * int param_1 = obj->get(key);
 * obj->put(key,value);
 */

**Comment by lc-kay** [comment]
@sanchitkaul99 Please provide this code in [Playground](https://leetcode.com/playground/new/empty). Thank you!

**Comment by lc-kay** [comment]
Hi @sanchitkaul99 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
