### ISSUE TITLE
Incorrect test case - 2752. Customers with Maximum Number of Transactions on Consecutive Days

### ISSUE THREAD

**Issue by darshit901** [LeetCode-Feedback/LeetCode-Feedback#17976]
### LeetCode Username

darshit901

### Problem number, title, and link

[2752. Customers with Maximum Number of Transactions on Consecutive Days](https://leetcode.com/problems/customers-with-maximum-number-of-transactions-on-consecutive-days/description/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The question description says "Return all customer_id with the maximum number of consecutive transactions. Order the result table by customer_id in ascending order." However, test case 8 returns duplicate customer IDs. 

### Language used for code

MySQL

### Code used for Submit/Run operation

```
WITH
    T3 AS (
        SELECT DISTINCT customer_id, transaction_date FROM Transactions
    ),
    T1 AS (
        SELECT
            customer_id,
            transaction_date,
            IFNULL(TIMESTAMPDIFF(DAY, transaction_date, LEAD(transaction_date, 1) OVER W), 2) as diff
        FROM Transactions
        WINDOW W AS(PARTITION BY customer_id ORDER BY transaction_date)
    ),
    T4 AS (
        SELECT DISTINCT customer_id FROM Transactions
    ),
    T2 AS (
        SELECT
            IFNULL(T5.consecutive_count, 0) as consecutive_count,
            T4.customer_id as customer_id
        FROM (
                SELECT 
                    customer_id,
                    COUNT(transaction_date) as consecutive_count
                FROM T1
                WHERE diff = 1
                GROUP BY customer_id
        ) T5
        RIGHT OUTER JOIN T4
            ON T5.customer_id = T4.customer_id
    )
SELECT customer_id
FROM T2
WHERE consecutive_count = (SELECT MAX(consecutive_count) FROM T2)
ORDER BY customer_id ASC
```

### Expected behavior

Expected response :
 customer_id |
| ----------- |
| 1           |
| 2           |
| 3           |
| 4           |
| 6           |
| 8           |
| 9           |
| 11          |
| 12          |
| 13          |
| 17          |
| 18          |
| 20          |
| 23          |
| 24          |
| 26          |
| 28          |
| 29          |
| 30          |
| 31          |
| 32          |
| 33          |
| 34          |
| 35          |
| 36          |
| 37          |
| 38          |
| 39          |
| 40          |
| 41          |
| 42          |
| 43          |
| 44          |
| 46          |
| 47          |
| 49          |
| 50          |

Actual response: Note duplicate occurrence of 8,9,13...
| customer_id |
| ----------- |
| 1           |
| 2           |
| 3           |
| 4           |
| 6           |
| 8           |
| 8           |
| 9           |
| 9           |
| 11          |
| 12          |
| 12          |
| 13          |
| 13          |
| 13          |
| 13          |
| 17          |
| 18          |
| 18          |
| 20          |
| 23          |
| 23          |
| 24          |
| 26          |
| 28          |
| 28          |
| 29          |
| 30          |
| 31          |
| 32          |
| 33          |
| 33          |
| 34          |
| 35          |
| 36          |
| 36          |
| 36          |
| 37          |
| 38          |
| 39          |
| 40          |
| 40          |
| 41          |
| 41          |
| 42          |
| 43          |
| 43          |
| 44          |
| 44          |
| 44          |
| 46          |
| 46          |
| 47          |
| 49          |
| 50          |

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
