### ISSUE TITLE
Missing Test Case - 34. Find First and Last Position of Element in Sorted Array

### ISSUE THREAD

**Issue by amit-rastogi** [LeetCode-Feedback/LeetCode-Feedback#17977]
### LeetCode Username
amitrastogi2206

### Problem number, title, and link
34. Find First and Last Position of Element in Sorted Array
https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/

### Category of the bug
Missing test Case

### Description of the bug
The problem mentions solving this in O(logn) however, an implementation using binary search with bidirectional scan is passing all the test cases. I think there should be some test case which fails this implementation since in worst case this implementation will be O(n) if all the input elements are equal to target.

### Language used for code
C++

### Code used for Submit/Run operation
```
class Solution {
public:
    int find(vector<int>& nums, int target, int l, int h){
        if(l>h)
          return -1;
        
        int mid = (l+h)/2;
        if(nums[mid]==target)
          return mid;
        if(target < nums[mid])
          return find(nums, target, l, mid-1);
        else
          return find(nums, target, mid+1, h);
    }

    vector<int> searchRange(vector<int>& nums, int target) {
        int idx = find(nums, target, 0, nums.size()-1);
        if(idx==-1)
          return vector({-1,-1});
        
        vector<int> v;        
        int st=idx;
        while(st>=0 && nums[st]==target)
          st--;

        
        v.push_back(st+1);
        
        st=idx;
        while(st<nums.size() && nums[st]==target)
          st++;

        v.push_back(st-1);

        return v;
    }
};
```

### Expected behavior
Time Limit Exceeded

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by amit-rastogi** [comment]
https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/submissions/1096036572/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
