### ISSUE TITLE
Missing Test Case - 1743. Restore the Array From Adjacent Pairs

### ISSUE THREAD

**Issue by Dimple12468** [LeetCode-Feedback/LeetCode-Feedback#17978]
### LeetCode Username
dimplegakhar

### Problem number, title, and link
[1743. Restore the Array From Adjacent Pairs](https://leetcode.com/problems/restore-the-array-from-adjacent-pairs/)

### Category of the bug
incorrect test case
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### Description of the bug
order of the output does not matter but still one test case is giving error because of that.

### Language used for code
Java

### Code used for Submit/Run operation

```
public int[] restoreArray(int[][] adjacentPairs) {
        //using hashSet
        HashSet<Integer> numsSet = new HashSet<>();
        for(int i = 0; i < adjacentPairs.length; i++){

            numsSet.add(adjacentPairs[i][0]);
            numsSet.add(adjacentPairs[i][1]);
        }

        int[] nums = new int[numsSet.size()];
        int index = 0;
        for(int i : numsSet){
            nums[index++] = i;
        }

        return nums;
    }
```

### Expected behavior
[-2,4,1,-3]

### Screenshots
![ss](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/56033618/e4a912dd-933e-48c6-a0e7-2fd777ee4194)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Dimple12468** [comment]
https://leetcode.com/problems/restore-the-array-from-adjacent-pairs/submissions/1096102036/
This above link is the solution which got accepted and below is the link which got rejected
https://leetcode.com/problems/restore-the-array-from-adjacent-pairs/submissions/1099546646/

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully (https://leetcode.com/problems/restore-the-array-from-adjacent-pairs/submissions/1099546646/) and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.


Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
