### ISSUE TITLE
120. Triangle

### ISSUE THREAD

**Issue by mickvav** [LeetCode-Feedback/LeetCode-Feedback#1798]
#### Category of the bug
- [*] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Looks like triangle problem (https://leetcode.com/problems/triangle/) has incorrect test case:
[[-1],[3,2],[-3,1,-1]]
is supposed to return -1, however, minimum path sum for this triangle is -1 + 2 + -3 == -2
Could you please revisit this testcase?

**Comment by lc-kay** [comment]
@mickvav Please check out this post to see why the expected answer is -1. https://leetcode.com/problems/triangle/discuss/38965/Is-1-2-3-1-1-3-output-is-1 Thank you for your time!
