### ISSUE TITLE
Missing Test Case - 767. Reorganize String

### ISSUE THREAD

**Issue by RandySheriffH** [LeetCode-Feedback/LeetCode-Feedback#17995]
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The test set for submission is incomplete, a corner case found "aaaaaaccccbbb" can beat my submission.

### Code used for Submit/Run operation

```
# this is my submission, but it has issue.
class Solution:
    def reorganizeString(self, s: str) -> str:
        l = len(s)
        count = Counter(s)
        arr = sorted([(v,k) for k,v in count.items()])
        vv,kk = arr.pop()
        if l - vv + 1 < vv: return ''
        prefix = [kk] * vv
        st = -1
        while vv and arr:
            v,k = arr.pop()
            c = min(vv,v)
            for i in range(st,st-c,-1): prefix[i] = k + prefix[i]
            st -= c
            v -= c
            vv -= c
            if v: arr.append((v,k))
        for v,k in arr[::-1]:
            for i in range(v):
                prefix[i] = prefix[i] + k
        return ''.join(prefix)    
```

### Expected behavior

Should failed test case: "aaaaaaccccbbb", but submission passed.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback. 

Please provide us your Leetcode Username .

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
