### ISSUE TITLE
Incorrect description in time and space complexity - 2642. Design Graph With Shortest Path Calculator

### ISSUE THREAD

**Issue by mdes4214** [LeetCode-Feedback/LeetCode-Feedback#17991]
### LeetCode Username

mdes4214

### Problem number, title, and link

2642. Design Graph With Shortest Path Calculator https://leetcode.com/problems/design-graph-with-shortest-path-calculator/solution/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug

Some typos in time and space complexity in Approach 1: Dijkstra's Algorithm.
There is no `seen` list in any language of implementation.

### Expected behavior

All occurrences of `seen` should be replaced with `costForNode`.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/9001974/ba84daa9-5ce6-492a-9542-a7628ed96084)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
