### ISSUE TITLE
Isomorphic Strings invalid Test case

### ISSUE THREAD

**Issue by darkworldz** [LeetCode-Feedback/LeetCode-Feedback#17994]
### LeetCode Username
darkknightrises9926

### Problem number, title, and link
205. Isomorphic Strings https://leetcode.com/problems/isomorphic-strings/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

it's buggy TESTCASE number 46 
for the input strings
s = "12"
t = "\u0067\u0068"
according to the problem statement output should be False instead of True

### Language used for code
C++ 

### Code used for Submit/Run operation

```
class Solution {
public:
    bool isIsomorphic(string s, string t) {
        if (s.size() != t.size())
        {
            return 0;
        }
        
        int hash[256]={0};
        bool ischarmapped[256]={0};
        
        for(int i=0;i<s.size();i++){
            if(hash[s[i]]==0 && ischarmapped[t[i]] == 0){
                hash[s[i]]=t[i];
                ischarmapped[t[i]]= true;
            }
            
        }
        
        for(int i=0;i<s.size();i++){
            if(char(hash[s[i]]) != t[i]) {
                return 0;}
        }
        return 1;
    }
};
```

### Expected behavior

output should be False as per the testcase instead of getting wrong answer code should get submitted.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/51827113/d9d882a1-b71a-4a9b-8a2f-65241836b582)

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/51827113/b214f08a-6110-40f5-8c7e-6e4356a8e013)

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
