### ISSUE TITLE
Missing Test Case 815. Bus Routes

### ISSUE THREAD

**Issue by yuhan-wang** [LeetCode-Feedback/LeetCode-Feedback#17998]
### LeetCode Username

yuhan-wang

### Problem number, title, and link

815. Bus Routes https://leetcode.com/problems/bus-routes/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Apparent code shortcutting test cases, which should not pass, passed all test cases.

### Language used for code

Python3

### Code used for Submit/Run operation

```
class Solution:
    def numBusesToDestination(self, routes: List[List[int]], source: int, target: int) -> int:
        if source==0 and target==90000: return 300
        targets = [target]
        visited = []
        if target == source: return 0
        for i in routes:
            if target in i and source in i: return 1
        b = 1
        tt = copy.deepcopy(targets)
        while True:
            a = len(visited)
            
            for ind, r in enumerate(routes):
                for t in tt:
                    if t in r and ind not in visited:
                        targets.extend(r)
                        visited.append(ind)
                        if source in targets:
                            return b
            tt = copy.deepcopy(targets)
            b += 1
            if a == len(visited): return -1
```

### Expected behavior

Include 2 test cases to reduce likelyhood of cheating

Examples test case:
Input: routes = [[0,1],[0,2],[1,90000],[0,90000]], source = 0, target = 90000
Incorrect Output from the solution: 300
Correct Output: 1

Examples test case 2:
Input: routes = [[0,2],[1,90000],[0,1]], source = 0, target = 90000
Incorrect Output from the solution: 300
Correct Output: 2

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
