### ISSUE TITLE
3月7日置顶题[队列最大值] 单独运行测试用例通过但是提交同样的用例会越界

### ISSUE THREAD

**Issue by Shiro-umi** [LeetCode-Feedback/LeetCode-Feedback#18]
** Bug 类型**
- [x] 题目
- [ ] 题解

**描述**
3月7日置顶题[队列最大值] 
赋值问题测试用例单独运行可以通过，提交时候问题测试用例报错下标越界

**你提交或者运行的代码**
```
class MaxQueue:
    index = [-1]

    def __init__(self):
        self.arr = []


    def max_value(self) -> int:
        return -1 if len(self.index) == 1 else self.arr[self.index[-1]]


    def push_back(self, value: int) -> None:
        if len(self.index) == 1 or value > self.arr[self.index[-1]]:
            self.index.append(len(self.arr))
        self.arr.append(value)


    def pop_front(self) -> int:
        if len(self.index) == 1:
            return -1
        else:
            if self.max_value() == self.arr[self.index[-1]]:
                self.index.pop()
            return self.arr.pop(0)

```

**期望行为**
希望能解释一下这种情况为什么会出现，以及解决方案

**屏幕截图**
<img width="712" alt="1111" src="https://user-images.githubusercontent.com/55919941/76141793-f3403680-60aa-11ea-9d6e-85eb1a3c8514.png">
<img width="654" alt="2222" src="https://user-images.githubusercontent.com/55919941/76141795-f63b2700-60aa-11ea-9027-97a526c7eef5.png">

**额外的上下文**
添加额外的上下文信息

**Comment by idealism-xxm** [comment]
使用了类变量 `index`，且每次使用时没有进行初始化。
可以看看官方说明：[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://support.leetcode-cn.com/hc/kb/article/1194344/)
