### ISSUE TITLE
Missing Test Case - 815. Bus Routes

### ISSUE THREAD

**Issue by mayankmotwani** [LeetCode-Feedback/LeetCode-Feedback#18007]
### LeetCode Username

Mayank_Motwani

### Problem number, title, and link

815. Bus Routes https://leetcode.com/problems/bus-routes/description/?envType=daily-question&envId=2023-11-12

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

There is a missing test case in the above mentioned problem. After analyzing the Code Sample shown for the best runtime (78ms) in the Submissions section, I was able to identify a case in which the code would fail to give the correct answer. Based upon that I have designed a new test case. The sample code results in Wrong Answer when executed on the new test case but gets accepted upon submission.
The sample code and the new test case are given below.

### Language used for code

C++

### Code used for Submit/Run operation

```
// Code Sample shown for the best runtime (78ms) in the Submissions section
class Solution {
public:
    int numBusesToDestination(vector<vector<int>>& routes, int source, int target) {
        vector<int> dist(1000000, 501);
        dist[source] = 0;
        unordered_set<int> visited;
        int mindist;
        int count = 0;
        while(visited.size() < routes.size() && count < routes.size()) {
            for(int bus = 0; bus < routes.size(); ++bus) {
                if (visited.find(bus) != visited.end()) continue;
                mindist = 501;
                for(auto i : routes[bus]) {
                    mindist = min(mindist, dist[i] + 1);
                }
                for(auto i : routes[bus]) {
                    dist[i] = min(dist[i], mindist);
                }
                if (mindist < 501) {
                    visited.emplace(bus);
                }
            }
            count++;
        }
        if (dist[target] == 501) return -1;
        return dist[target];
    }
};
```

### New Test Case
```
[[1,2,3],[3,4],[4,5],[5,6],[6,7],[1,7]]
2
6
```

### Expected behavior

The logic of the Sample Code is incorrect. When it is executed on the new test case, it gives the output as 4 resulting in Wrong Answer (The expected output is 3). But upon submission, it gets Accepted.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
