### ISSUE TITLE
Missing Test Case - 1768. Merge Strings Alternately

### ISSUE THREAD

**Issue by joelDarla123** [LeetCode-Feedback/LeetCode-Feedback#18005]
You are given two strings word1 and word2. Merge the strings by adding letters in alternating order, starting with word1. If a string is longer than the other, append the additional letters onto the end of the merged string.

Return the merged string.

Input: word1 = "abc", word2 = "pqr"
Output: "apbqcr"
Explanation: The merged string will be merged as so:
word1:  a   b   c
word2:    p   q   r
merged: a p b q c r

Here are some steps you can follow to solve problems in data structures and algorithms:

1)Understand the problem

The first step is to clearly understand the problem. Read the problem carefully and make sure you understand the given conditions and requirements. Define the input and output of the problem. If possible, draw a diagram or use other visualization techniques to help you understand the problem.

2)Design an algorithm

Once you understand the problem, you need to design an algorithm to solve it. There are many different algorithms that can be used to solve a given problem. Choose an algorithm that is appropriate for the problem size and the desired time and space complexity.

3)Implement the algorithm

Once you have designed an algorithm, you need to implement it in a programming language. Use a clear and concise style of coding. Make sure your code is well-tested and efficient.

4)Test the algorithm

Once you have implemented the algorithm, you need to test it to make sure it works correctly. Test the algorithm with a variety of input data to ensure that it produces the correct output.

5)Analyze the algorithm
Once you have tested the algorithm, you need to analyze its performance. Evaluate the algorithm's time and space complexity. Compare the algorithm to other algorithms that can be used to solve the same problem.

![Screenshot (642)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/129359587/4b6df325-44c0-438a-bfb5-55f14b8f1654)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The bug or the issue. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by joelDarla123** [comment]
Hey LC-Pam, how have you been?

This is a mock question frequently asked in Leetcode,

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've submitted your feedback to the team.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
