### ISSUE TITLE
missing TestCases - 2935 . Maximum Strong Pair XOR II 

### ISSUE THREAD

**Issue by PARASnagpal99** [LeetCode-Feedback/LeetCode-Feedback#18003]
### Problem number, title, and link
   
2935. Maximum Strong Pair XOR ||  https://leetcode.com/problems/maximum-strong-pair-xor-ii

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Language used for code
Javascript 

### Code used for Submit/Run operation

```
/**
 * @param {number[]} nums
 * @return {number}
 */
var maximumStrongPairXor = function(arr) {
    arr.sort((a,b) => a-b);
    let n = arr.length, ans = 0;

    for(var i=0; i<n; ++i)
        for(var j=i; j<n; ++j)
            if(arr[j] - arr[i] <= arr[i]) ans = Math.max(ans, arr[i] ^ arr[j]);
            else break;
            
    return ans;

};

```

### Expected behavior
It was supposed to give TLE but it successfully passed all the testCases . TestCases are weak for javascript users .
same code in c++ gave TLE .

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
