### ISSUE TITLE
 Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by Akashpandey1233** [LeetCode-Feedback/LeetCode-Feedback#18004]
### Category of the bug
- [x] Problem description
- [x] Solved examples
- [x] Problem constraints
- [x] Problem hints
- [x] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [x] Programming language support

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

**Comment by Akashpandey1233** [comment]
nice platform

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
