### ISSUE TITLE
Missing Test Case - 134. Gas Station

### ISSUE THREAD

**Issue by earlbread** [LeetCode-Feedback/LeetCode-Feedback#1800]
#### Your LeetCode username

waydi1

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The solution is accepted but fails on the following test case.
```
[]
[]
```

#### Code you used for Submit/Run operation

```
class Solution:
    def canCompleteCircuit(self, gas: List[int], cost: List[int]) -> int:
        if sum(gas) < sum(cost):
            return -1
        
        start_index = 0
        current_gas = 0
        
        for i in range(len(gas)):
            current_gas = current_gas + gas[i] - cost[i]
            if current_gas < 0:
                start_index = i + 1
                current_gas = 0
        
        return start_index
```

#### Language used for code

Python

#### Expected behavior

The solution should be failed or some constraint should be added to the description.

#### Screenshots

![Screen Shot 2020-12-29 at 4 39 41 PM](https://user-images.githubusercontent.com/5907919/103267168-83fa5100-49f4-11eb-844c-7569cf093242.jpg)

**Comment by lc-kay** [comment]
Hi @earlbread 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @earlbread 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
