### ISSUE TITLE
Ambiguous Problem Description - 2694. Event Emitter

### ISSUE THREAD

**Issue by IamLizu** [LeetCode-Feedback/LeetCode-Feedback#18018]
### LeetCode Username
BoweryKing

### Problem number, title, and link
[2694. Event Emitter](https://leetcode.com/problems/event-emitter/)

### Category of the bug
- [x] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
Is it just me or the part seems confusing to anyone else as well?

 > The `subscribe` method should also return an object with an `unsubscribe` method that enables the user to `unsubscribe`. When it is called, the callback should be removed from the list of subscriptions and `undefined` should be returned.

Specially the last line,

>  When it is called, the callback should be removed from the list of subscriptions and `undefined` should be returned.

It does not clearly mention which callback is to be removed; is it the first one, the last one or the whole callback array. I find it ambiguous.

Let's look at the following test case,

Input
```
["EventEmitter", "subscribe", "subscribe", "unsubscribe", "emit"]
```
```
[[], ["firstEvent", "x => x + 1"], ["firstEvent", "x => x + 2"], [0], ["firstEvent", [5]]]
```
Output
```
[[],["subscribed"],["subscribed"],["unsubscribed",0],["emitted",[7]]]
```
Expected
```
[[],["subscribed"],["subscribed"],["unsubscribed",0],["emitted",[7]]]
```

This will only pass if we remove the first callback for a specific event. Other given example test cases worked fine if we just remove the event and its list of callbacks from our store (`Map`, `Object` etc. in terms of JS).

### Language used for code
Javascript

### Code used for Submit/Run operation
```js
class EventEmitter {
    constructor() {
        this.events = new Map();
    }

    /**
     * @param {string} eventName
     * @param {Function} callback
     * @return {Object}
     */
    subscribe(eventName, callback) {
        var _event = this.events.get(eventName) || [];

        var _callback = callback ? callback : _event[_event.length - 1];

        this.events.set(eventName, [..._event, _callback]);

        return {
            unsubscribe: () => {
                this.events.get(eventName).shift();

                return undefined;
            },
        };
    }

    /**
     * @param {string} eventName
     * @param {Array} args
     * @return {Array}
     */
    emit(eventName, args = []) {
        var result = [];

        var _event = this.events.get(eventName) || [];

        _event.forEach((callback, index) => {
            result[index] = callback(...args);
        });

        return result;
    }
}

```

### Expected behavior
I think the phrasing should be,
**When it is called, the first callback of the event should be removed from the list of subscriptions and `undefined` should be returned.**

[Link to the discussion in the problem on leetcode](https://leetcode.com/problems/event-emitter/description/comments/2132441)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Please ask your question in the discussion forum.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
