### ISSUE TITLE
Missing Test Case - 199. Binary Tree Right Side View

### ISSUE THREAD

**Issue by AhsanRazaPucit** [LeetCode-Feedback/LeetCode-Feedback#18016]
### LeetCode 
ahsanrazapucit

### Problem number, title, and link

[199. Binary Tree Right Side View](https://leetcode.com/problems/binary-tree-right-side-view/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] [1,2,3,null,5,null,null]
- [x] [1,4,3,2,null] 
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

miss test cases that i provide

### Language used for code

c++

### Code used for Submit/Run operation

``` 
class Solution {
    void recursion(TreeNode *root,  vector<int> &res)
    {
        if(root==NULL) return ;
        res.push_back(root->val);
        if(root->right)
            recursion(root->right,  res);
        else
            recursion(root->left,  res);
    }
public:
    vector<int> rightSideView(TreeNode* root) {
        vector<int> res;
        recursion(root,  res);
        return res;
    }
};
``` 

### Expected behavior

it is aceptable code for all test cases but i think this problem must have test cases that  i provided above and  should fail because it does not cover cases i provide above.

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
