### ISSUE TITLE
Too small number of max perf test cases or too high time limit in js - 2935. Maximum Strong Pair XOR II

### ISSUE THREAD

**Issue by przemek3d88** [LeetCode-Feedback/LeetCode-Feedback#18019]
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [x] Programming language support

### Description of the bug
Many JS solutions are O(n^2). This is a single example, but there are multiple cases - the current 59'th position in LeetCode US, held by this [user](https://leetcode.com/zhang1pr/). I will provide the codes in the code section. It is impossible to kill this solution with a single test. To solve this issue you can either add a bigger number of max tests - 50K consecutive numbers starting at least from 50K (to make all the pairs strong) or reduce the time limit.

The equivalent C++ solution fails on a single max test and is rejected.

### Language used for code
JS, C++

### Code used for Submit/Run operation

JS accepted
```
/**
 * @param {number[]} nums
 * @return {number}
 */
var maximumStrongPairXor = function(nums) {
  let res=0;   
    
  nums.sort((a,b)=>a-b);  
    
  for (let i=0;i<nums.length;i++)  
    for (let j=i+1;j<nums.length;j++) {
      if (nums[j] - nums[i] <= nums[i])  
        res = Math.max(res, nums[i] ^ nums[j])  
    }
    
  return res;  
};
```

C++ rejected:

```
class Solution {
public:
    int maximumStrongPairXor(vector<int>& nums) {
        sort(nums.begin(), nums.end());

        int res = 0, n = nums.size();
        for(int i = 0; i < n-1; i++) {
            for(int j = i+1; j < n; j++) {
                if(nums[j] - nums[i] > nums[i]) {
                    break;
                }

                res = max(res, nums[i]^nums[j]);
            }
        }

        return res;
    }
};
```

### Expected behavior
JS solution should exceed the time limit.

### Additional context

I logged a similar [issue](https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/17806) for C++ after the previous contest. In one case the solution with the correct time and space got TLE, because of too many O(log n) operations on the set. In the other, the JS O(n^2) solution passes and the same O(n^2) C++ solution fails. C++ coders do not have equal chances with other language users, hence the competition is not fair.

The time limit and solution should be language-agnostic. It is always possible to create such test cases, to fail the fastest O(n^2) C++ and let the slowest O(n log n) JS solution pass. There should be no different time limits for different programming languages. It is up to the participant, to make the best language choice.

**Comment by przemek3d88** [comment]
If having a single time limit creates an imbalance for C++, it is still better, as this simulates the real life. If you need to solve the problem fast, you can implement the component in C++, for the speed. Besides, the users of other languages quite often have the comfort of more functionality, C++ is hard in general and there are no too many C++ programmers compared to other languages. If from time to time optimized brute-force solution in C++ passes, it is not the end of the world.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback. 

Please let us know your Leetcode Username. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by przemek3d88** [comment]
Hi @LC-Pam , my leetcode username is: przemysaw2
