### ISSUE TITLE
977. 有序数组的平方增加进阶要求

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#1801]
**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
第 977 题的常规做法是直接遍历原数组，计算每个元素的平方，然后排序。该做法是最直观的做法，但是并非最优解法，因为需要排序。
最优解法是使用双指针，可以将复杂度降低到线性。
因此建议在题目描述中增加进阶要求，进阶要求为设计 O(n) 的算法实现。中文描述和英语描述需要同步更新。

**你使用的语言**
Java

**你提交或者运行的代码**

**期望行为**
题目描述中增加进阶要求，中文描述和英语描述需要同步更新。

**屏幕截图**

**额外的上下文**

**Comment by feiceh** [comment]
感谢反馈，已转给题目运营团队会尽快确认的。

**Comment by feiceh** [comment]
你好，当前题面已更新。
