### ISSUE TITLE
Missing Test Case - 815. Bus Routes

### ISSUE THREAD

**Issue by Bazabizi** [LeetCode-Feedback/LeetCode-Feedback#18012]
### LeetCode Username
###bazabizi

### Category of the bug
- [x] Problem description
- [x] Solved examples
- [x] Problem constraints
- [x] Problem hints
- [x] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [x] Programming language support

### Description of the bug

I found a test case that don't work for my code but the code I write , is already accepted so I figured this test case may not be included
the edge case that causes the problem is that when the source and destination have the same value and that number is not found on the 'routes' array. The output should be 0 and my code returns -1 .
##the test case 
routes =  [[1,2,7],[3,6,7]]
source = 10
destination = 10

### Language used for code

Python3

### Code used for Submit/Run operation

```
class Solution:
    def numBusesToDestination(self, routes: List[List[int]], source: int, target: int) -> int:
        graph = defaultdict(list)
        for idx , arr in enumerate(routes):
            for val in arr:
                graph[val].append(idx)
        
        queue = deque()
        visited = set()
        for val in graph:
            if val == source:
                queue.append((graph[val] , 1))
                break
        index = set()
         
        while queue:
            
            if target == source:
                return 0
            idx , path = queue.popleft()
            
            for val in idx:
                if val not in index:
                    for route in routes[val]:
                        if route == target:
                            return path
                        if route not in visited:
                            queue.append((graph[route] ,path + 1 ))
                            visited.add(route)
                    index.add(val)
            
        return -1
```

### Expected behavior

when I use the custom testcase it shows me that my code is correct but when I submit the code it works fine.
### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/99665336/e256b2de-ed0c-438d-8168-e2f6da64226e)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
