### ISSUE TITLE
Missing Test Cases : 146. LRU Cache

### ISSUE THREAD

**Issue by sanchitkaul99** [LeetCode-Feedback/LeetCode-Feedback#1802]
#### Your LeetCode username
kaulsanchit99

#### Category of the bug
- [1 ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
The code gets accepted but for all the testcases that have 0(Zero) as a value should get wrong answer because its totally possible for a value to be zero.

#### Code you used for Submit/Run operation

```
  class LRUCache {
  public:
  unordered_map<int,int> lru;
  deque keys;
  int cap;
  int curr =0;
  LRUCache(int capacity) {
  cap = capacity;
  }

int get(int key) {
    if(lru[key] == 0)
    {
        return -1;
    }
    keys.erase(find(keys.begin(),keys.end(),key));
    keys.push_back(key);
    return lru[key];
}

void put(int key, int value) {
    if(lru[key]!=0)
    {
        lru[key] = value;
        keys.erase(find(keys.begin(),keys.end(),key));
        keys.push_back(key);
        return;
        
    }
    curr++;
    if(curr<=cap)
    {
        lru[key] = value;
        keys.push_back(key);
        return;
    }
    curr--;
    int k = keys[0];
    keys.pop_front();
    lru[k] = 0;
    lru[key] = value;
    keys.push_back(key);
}
};

```

#### Language used for code
C++

#### Expected behavior
The absence of the testcase that i am submitting is allowing a wrong solution to be accepted.
Kindly add this testcase to disallow these types of solutions.
Thanks!

The code gets accepted but for all the testcases that have 0(Zero) as a value should get wrong answer because its totally possible for a value to be zero.

**Comment by lc-kay** [comment]
@sanchitkaul99 Please submit your code through P[layground](https://leetcode.com/playground/new/empty). Thank you for your time!

**Comment by sanchitkaul99** [comment]
done!

**Comment by sanchitkaul99** [comment]
https://leetcode.com/playground/mfDu5csV

**Comment by lc-kay** [comment]
<img width="1917" alt="Screen Shot 2021-01-05 at 10 32 06 AM" src="https://user-images.githubusercontent.com/70870126/103684974-47bd7800-4f41-11eb-8c30-388501257753.png">
@sanchitkaul99 When I run your code, I received Compile Error. Can you please send me the submission link to your accepted solution?

**Comment by sanchitkaul99** [comment]
you need to run it in the leetcode question LRU cache

**Comment by sanchitkaul99** [comment]
https://leetcode.com/problems/lru-cache/

**Comment by lc-kay** [comment]
@sanchitkaul99 To qualify for rewards, can you please provide a specific test case that this fails on?

**Comment by sanchitkaul99** [comment]
These two test cases are not present in leetcode and thus a wrong solution that is the one is sent above gets accepted ..
The code gets accepted but for all the testcases that have 0(Zero) as a value should get wrong answer because its totally possible for a value to be zero.



Test Cases
TestCase 1-

Your input:
["LRUCache","put","put","get","put","get","put","get","get","get"]
[[2],[1,0],[2,2],[1],[3,3],[2],[4,4],[1],[3],[4]]
Output:
[null,null,null,-1,null,2,null,-1,-1,4]
Expected:
[null,null,null,0,null,-1,null,-1,3,4]


TestCase 2-
Your input:
["LRUCache","put","put","get","put","get","put","get","get","get"]
[[2],[1,1],[2,2],[1],[3,0],[2],[4,4],[1],[3],[4]]
Output:
[null,null,null,1,null,-1,null,-1,-1,4]
Expected:
[null,null,null,1,null,-1,null,-1,0,4]

**Comment by lc-kay** [comment]
@sanchitkaul99 
Thank you! I've relayed this issue to our team to investigate.

**Comment by sanchitkaul99** [comment]
Will the reward be added now? In leetcode coins?

**Comment by lc-kay** [comment]
Hi @sanchitkaul99 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
