### ISSUE TITLE
815. Bus Routes - Missing Test Case

### ISSUE THREAD

**Issue by FireSlayer57** [LeetCode-Feedback/LeetCode-Feedback#18026]
### LeetCode Username
masteralphi

### Problem number, title, and link
815. Bus Routes https://leetcode.com/problems/bus-routes/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
Test Case: [[1,2,7],[3,6,7]]
8
6

When running my accepted solution on this testcase I get a Runtime Error since I do not have data about buses passing this station (source = 8) among all possible routes. Though this solution was accepted on all 49 cases

### Language used for code
Python

### Code used for Submit/Run operation

```
class Solution:
    def numBusesToDestination(self, routes: List[List[int]], source: int, target: int) -> int:
        if source == target:
            return 0
        mx = 0
        for r in routes:
            for stop in r:
                mx = max(mx, stop)
        
        bus_id = [[] for _ in range(mx+1)]
        for i, r in enumerate(routes):
            for stop in r:
                bus_id[stop].append(i)

        seen = [False] * (mx+1)
        fin = [False] * (mx + 1)
        hp = []
        d = [float("inf")] * (mx+1)
        seen_bus = [False]*(len(routes))
        
        for bus in bus_id[source]:
            seen_bus[bus] = True
            for stop in routes[bus]:
                if not seen[stop]:
                    d[stop] = 1
                    seen[stop] = True
                    heappush(hp, [1, stop])
        while hp:
            est, stop = heappop(hp)
            if not fin[stop]:
                fin[stop] = True
                for bus in bus_id[stop]:
                    if not seen_bus[bus]:
                        seen_bus[bus] = True
                        for stop in routes[bus]:
                            if not seen[stop]:
                                seen[stop] = True
                            if est + 1 < d[stop]:
                                d[stop] = est + 1
                                heappush(hp, [est + 1, stop])
        return -1 if (target > mx or d[target] == float('inf')) else d[target]
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
