### ISSUE TITLE
Incorrect test case output for 399. Evaluate Division https://leetcode.com/problems/evaluate-division/

### ISSUE THREAD

**Issue by ya332** [LeetCode-Feedback/LeetCode-Feedback#18021]
### LeetCode Username
ya332

### Problem number, title, and link
399. Evaluate Division https://leetcode.com/problems/evaluate-division/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
Incorrect test case output
Look at this test case: 
```
[["a","c"],["ab","cd"]]
[3.0,2.0]
[["b","d"]]
``` 
b/d should be 2/3. But the expected outcome in leetcode website is -1. 

### Language used for code
Python

### Code used for Submit/Run operation

```py
class Solution:
    def calcEquation(self, equations: List[List[str]], values: List[float], queries: List[List[str]]) -> List[float]:
        graph=defaultdict(dict)
        n=len(equations)
        for i in range(n):
            graph[equations[i][0]][equations[i][1]]=values[i]
            graph[equations[i][1]][equations[i][0]]=1/values[i]
        print(graph)
        def bfs(src,target):
            if src not in graph or target not in graph:
                return -1
            if src == target:
                return 1
         
            queue = collections.deque()
            queue.append((src, 1))
            visited = set()
            while queue:
                node, weight = queue.popleft()
                if node == target:
                    return weight
                for nei in graph[node]:
                    if nei not in visited:
                        visited.add(nei)
                        queue.append([nei, weight * graph[node][nei]])

            return -1

        return [bfs(p, q) for p,q in queries]      
```

### Expected behavior
Below test case should return 2/3. But it expected outcome in leetcode solution is -1
```
[["a","c"],["ab","cd"]]
[3.0,2.0]
[["b","d"]]
``` 
 

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/26026196/8bf59eb3-c505-4088-a796-c9d90191c922)

**Comment by yumkam** [comment]
Disclaimer: I'm just another leetcode user
A_i and B_i are names of variables, not expressions. So, second expression cannot be interpreted as "(a*c)/(b*d)=2", it's just variable named `ac` divided by variable named `bd` is 2,  nothing is known about variables `b` and `d`, hence result of their division is undefined (`-1`)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Please consider the above comment as explaination. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
