### ISSUE TITLE
Editorial typos - 591. Tag Validator

### ISSUE THREAD

**Issue by xelplogoog** [LeetCode-Feedback/LeetCode-Feedback#18038]
### LeetCode Username
c4tdog

### Description of the bug
https://leetcode.com/problems/tag-validator/editorial/
There are typos in words `beginning`, `constitute`, `up to` (twice), `functionality`

<img width="400" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2188302/d82b1747-b0cd-4aa8-be40-a5c9ab7512e5">

<img width="425" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2188302/3bc88e01-28c2-4c4c-9818-7aced0ed0547">

<img width="439" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2188302/37335b40-9dab-4688-9027-4854d246701e">

<img width="440" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2188302/31f0261c-9cfd-4c3d-a949-0376787e7ac3">

<img width="439" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2188302/bd6025a8-a697-4d56-88d7-c9cd1bd6f4c4">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
