### ISSUE TITLE
Missing Test Case - 334. Increasing Triplet Subsequence

### ISSUE THREAD

**Issue by Harry-Yang-Huang** [LeetCode-Feedback/LeetCode-Feedback#1803]
#### Your LeetCode username

Harry_Huang 

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language

#### Description of the bug

Missing Test Case let the wrong code pass online judgement.

#### Code you used for Submit/Run operation

```
// 334. Increasing Triplet Subsequence
class Solution {
public:
    bool increasingTriplet(vector<int>& nums) {
        vector<int> vt;
        for (int i = 1; i < nums.size(); i++) {
            if (nums[i] > nums[i-1]) {
                if (vt.empty()) {
                    vt.push_back(nums[i-1]);
                    vt.push_back(nums[i]);
                }
                else {
                    if (nums[i] > vt[1] || 
                        (nums[i] > vt[0] && nums[i-1] > vt[0])) return true;
                    vt[1] = nums[i];
                }
            }
        }
        
        return false;
    }
};
```

#### Language used for code

C++

#### Expected behavior

This code should not pass online judgement.
The number sequence [1,5,0,4,1,3] should be added to the test cases.

**Comment by lc-kay** [comment]
Hi @Harry-Yang-Huang 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Harry-Yang-Huang 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
