### ISSUE TITLE
Possible bug in code runner for "19. Remove Nth Node From End of List"?

### ISSUE THREAD

**Issue by jyscao** [LeetCode-Feedback/LeetCode-Feedback#18036]
### LeetCode Username
jyscao

### Problem number, title, and link
[19. Remove Nth Node From End of List](https://leetcode.com/problems/remove-nth-node-from-end-of-list/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
My solution produces the following `Runtime Error`:
```
IndexError: pop from empty list
    head_tail = nodes_stack.pop()
Line 18 in removeNthFromEnd (Solution.py)
    ret = Solution().removeNthFromEnd(param_1, param_2)
Line 45 in _driver (Solution.py)
    _driver()
Line 56 in <module> (Solution.py)
```
However, when running the exact same code in IPython, with the inputs from example 1: `Input: head = [1,2,3,4,5], n = 2`, I get the correct output.

### Language used for code
Python

### Code used for Submit/Run operation

```python
# Definition for singly-linked list.
# class ListNode:
#     def __init__(self, val=0, next=None):
#         self.val = val
#         self.next = next
class Solution:
    def removeNthFromEnd(self, head: Optional[ListNode], n: int) -> Optional[ListNode]:
        handle = head
        nodes_stack = []
        while head:
            nodes_stack.append(head)
            head = head.next

        for _ in range(n - 1):
            nodes_stack.pop()

        tail_head = nodes_stack.pop().next
        head_tail = nodes_stack.pop()
        head_tail.next = tail_head

        return handle
```

### Expected behavior
To pass the example 1 test case; at least no runtime error.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Please ask your question in the discussion forum.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
