### ISSUE TITLE
New solution for 1930. Unique Length-3 Palindromic Subsequences

### ISSUE THREAD

**Issue by barret-p** [LeetCode-Feedback/LeetCode-Feedback#18042]
I want to add a new solution to the Editorial for [1930. Unique Length-3 Palindromic Subsequences](https://leetcode.com/problems/unique-length-3-palindromic-subsequences/)

There is a binary search solution that is not discussed. Here is a solution that I posted for it. https://leetcode.com/problems/unique-length-3-palindromic-subsequences/solutions/4285477/beats-100-python-using-binary-search/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've submitted this feedback to our team. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The purpose of the solutions we publish is to introduce the applications of relevant DSA as comprehensively as possible. We do not intentionally cover all possible solutions, their different implementation methods, or intricate details. That’s to say, the specific implementation approach is often not our primary focus.

The solution provided by the reporter is only slightly different from one of our official approaches, and it does not exceed the time and space complexity of the optimal solution.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
