### ISSUE TITLE
236缺少测试案例          [6,2,8,0,4,7,10,null,null,3,5,null,null,9,11]   查找9和11的最近祖先

### ISSUE THREAD

**Issue by srx123456** [LeetCode-Feedback/LeetCode-Feedback#18047]
### LeetCode 用户名
[Cool LichtermanK8d](https://leetcode.cn/u/cool-lichtermank8d)

### 问题号码、标题和链接
[236. 二叉树的最近公共祖先](https://leetcode.cn/problems/lowest-common-ancestor-of-a-binary-tree/)

### Bug 类型
缺少测试用例 *（由于缺少测试用例而接受不正确的代码）*

### 描述
缺少测试用例
 [6,2,8,0,4,7,10,null,null,3,5,null,null,9,11]   去查找9和11的最近祖先

### 你使用的语言
Java

### 你提交或者运行的代码
```
class Solution {
    public TreeNode lowestCommonAncestor(TreeNode root, TreeNode p, TreeNode q) {
        // 递归的终止条件
        if(root == null)  return root;
        // 通过回溯获得左右节点上传的信息
        if(root == p | root == q)  return root;
        // 使用后序遍历，中节点的通过回溯获得左右节点上传的信息
        // 左子树有没有p或q
        TreeNode left = lowestCommonAncestor(root.left, p, q);
        // 右子树有没有p或q
        TreeNode right = lowestCommonAncestor(root.right, p, q);
        // 中：处理流程
        // 若左右节点分别对应要找的节点，则返回公共祖先root节点。
        if(left != null && right != null)  return root;
        // 若只有一侧返回了节点，那么该节点就是公共祖先。
        if(left != null && right == null)  return left;
        if(left == null && right != null)  return right;
        // 找不到公共祖先
        return null;
    }
}
```

### 期望行为

增加上述的测试用例

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by stormsunshine** [comment]
你发的代码对于这个测试用例的运行结果是正确的，为什么认为这个测试用例是缺失的？

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
