### ISSUE TITLE
Wrong Test Case - 414. Third Maximum Number

### ISSUE THREAD

**Issue by PrashikWankhadeSCOE** [LeetCode-Feedback/LeetCode-Feedback#18053]
PrashikWankhade

### LeetCode Username

414. Third Maximum Number
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [x] Incorrect or missing testcase
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

- [ ] Incorrect or missing testcase

### Description of the bug

test case [1,2147483647,-2147483648] 
in this array the third maximum is -2147483648 
but in output it is showing 2147483647

### Language used for code

java

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```
class Solution {
    public int thirdMax(int[] nums) {
        Set set = new HashSet();
        for(int i = 0;i<nums.length;i++){
            set.add(nums[i]);
        }
        System.out.println(set);
        List list = new LinkedList(set);
        if(list.size() >2){
            int a = (int)list.get(list.size()-3);
            return a;
        }
        else if(list.size()==1){
            return (int)list.get(0);
        }
        return Math.max((int)list.get(0),(int)list.get(1));
    }
}

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Comment by PrashikWankhadeSCOE** [comment]
the code was not accepted so how can I share
