### ISSUE TITLE
Missing Test Case - 1457. Pseudo-Palindromic Paths in a Binary Tree

### ISSUE THREAD

**Issue by tonghuikang** [LeetCode-Feedback/LeetCode-Feedback#1805]
#### Your LeetCode username
tonghuikang

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
A solution is accepted but fails on the following test case 

```python
#!/usr/bin/env python3
case="[{},{},{},{},{}"+",null,null,{},{}"*49997+"]"
print(case.format(*[1]*99999))
```

#### Code you used for Submit/Run operation
```python
class Solution:
    def pseudoPalindromicPaths(self, root: TreeNode, arr=list()) -> int:
        if root == None:
            return 0
        
        arr.append(root.val)

        res = 0
        if root.left == None and root.right == None:
            if sum(v%2 for v in collections.Counter(arr).values()) <= 1:
                res += 1
        
        res += self.pseudoPalindromicPaths(root.left, arr)
        res += self.pseudoPalindromicPaths(root.right, arr)

        arr.pop()
        
        return res
```

#### Language used for code
Python 3

#### Expected behavior
The solution should not be accepted since it fails on the test case.

#### Screenshots
<img width="1791" alt="Screenshot 2020-12-29 at 9 51 58 PM" src="https://user-images.githubusercontent.com/17105577/103288580-20861880-4a20-11eb-811b-8f167bc9b5ed.png">

The test case looks like this
<img width="1791" alt="Screenshot 2020-12-29 at 9 51 49 PM" src="https://user-images.githubusercontent.com/17105577/103288590-267bf980-4a20-11eb-9a2e-9f90e2e462d5.png">

#### Additional context
Please also consider this as another test case

```python
#!/usr/bin/env python3
case="[{},{},{},{},{}"+",null,null,{},{}"*49997+"]"
print(case.format(*[x%9+1 for x in range(99999)]))
```

```python
#!/usr/bin/env python3
import random
case="[{},{},{},{},{}"+",null,null,{},{}"*49997+"]"
print(case.format(*[random.randint(1,9) for x in range(99999)]))
```

**Comment by lc-kay** [comment]
Hi @tonghuikang 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @tonghuikang 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
