### ISSUE TITLE
Typo in Binary Search Explore Card - Overview section

### ISSUE THREAD

**Issue by Y-Rov** [LeetCode-Feedback/LeetCode-Feedback#18055]
### LeetCode Username
[seeker_of_balance](https://leetcode.com/anacondrai/)

### Category of the bug
- [x] Language

### Description of the bug
If we go through the section "Overview" in [Binary Search Explore Card](https://leetcode.com/explore/learn/card/binary-search/) and stop at the last paragraph:

`Other Binary Search Defintions:`

The word "Defintions" has a typo.

### Expected behavior

The corrected sentence should look like this: `Other Binary Search Definitions:`

### Screenshots

![Definitions_Typo](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73534920/cae11c14-eca0-4f5d-9f1d-380a4a6e2b7a)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by Y-Rov** [comment]
Hi @LC-Pam, looks like the typo has been corrected:

![Definitions_Corrected](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73534920/f319e362-0357-431d-9f42-ccbf49a2f0bf)

I have marked the task for this issue as completed. Thank you for your and your team's work 😄

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
