### ISSUE TITLE
[Performance] Problem list and Problem page loading slowly

### ISSUE THREAD

**Issue by busytolive** [LeetCode-Feedback/LeetCode-Feedback#1806]
#### Your LeetCode username

simpleAndElegant

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

https://user-images.githubusercontent.com/7270647/103303935-23e7b880-49bc-11eb-9c38-7f7ba41444d0.mov

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
Hi @busytolive 
Thank you for your time. Upon investigating this issue, we found this issue to be non-content-related (the issue stems from an origin away from the content on this problem); therefore, please submit this issue to our help desk at support@leetcode.com
