### ISSUE TITLE
Missing test case 169 - Majority Element

### ISSUE THREAD

**Issue by dnaploszek** [LeetCode-Feedback/LeetCode-Feedback#18061]
### LeetCode Username
dario3d

### Problem number, title, and link
169. Majority Element https://leetcode.com/problems/majority-element

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
There is a widely accepted answer to the problem that provides incorrect results.

### Language used for code
TypeScript

### Code used for Submit/Run operation
```
function majorityElement(nums: number[]): number {
    let majority = nums[0]; // Initialize the majority element.
    let count = 1; // Initialize the count of the majority element.

    for (let i = 1; i < nums.length; i++) {
        if (count === 0) {
            majority = nums[i];
            count = 1;
        } else if (nums[i] === majority) {
            count++;
        } else {
            count--;
        }
    }

    return majority;
};
```

### Expected behavior
This code will fail for a test case passing `[1,1,2,1,2,2,1,3,3,3,1,1]`. The code returns 3 and the correct answer is 1

### Screenshots
Non-applicable

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:


The missing test case.
[1,1,2,1,2,2,1,3,3,3,1,1] received Invalid test case - There is no majority element

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by dnaploszek** [comment]
All right I was wrong. For some reason I assumed that n / 2 is enough to be the majority.
