### ISSUE TITLE
缺少测试用例- 234. 回文链表

### ISSUE THREAD

**Issue by ChenYichengX** [LeetCode-Feedback/LeetCode-Feedback#18064]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

### LeetCode 用户名
chen-4fm

### 问题号码、标题和链接
234. 回文链表 https://leetcode.cn/problems/palindrome-linked-list/

### Bug 类型
- [ ] 问题描述
- [ ] 示例
- [ ] 问题限制
- [ ] 问题提示
- [ ] 不正确或缺少“相关标签”
- [ ] 不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*
- [X] 缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*
- [ ] 力扣官方题解
- [ ] 编程语言支持

### 描述
我提交的代码中，采用 == 去比较Integer 的值，当数值超过 127 的时候，两个相等的值，但不是同一个对象，会判断为false.
实际上应该用 equals 函数比较。所以我的代码应该是有问题的，但还是通过了。请添加一些数值较大的测试用例。

### 你使用的语言
java

### 你提交或者运行的代码

```
public static boolean isPalindrome(ListNode head) {
        List<Integer> list = new ArrayList<>();
        while (head != null) {
            list.add(head.val);
            head = head.next;
        }
        for (int i = 0, j = list.size() - 1; i < list.size() / 2; i++, j--) {
            if (list.get(i) == list.get(j)) {
                continue;
            }
            return false;
        }
        return true;
 }
```

### 期望行为
例如：
输入：head = [5227,1,1,5227]
应该输出：true 
但是因为我的代码中使用的是 ==来比较（超过127的值比较的是对象的地址）会返回 false;
我的代码是有问题的，不应该通过，期望添加一些数值较大的测试用例

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.


Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by ChenYichengX** [comment]
> Hello,
> 
> Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:
> 
> The code submission link you submitted led to the observed result.
> 
> Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!
> 
> Best regards LeetCode Support Team

https://leetcode.cn/problems/palindrome-linked-list/submissions/482231684

**Comment by ChenYichengX** [comment]
https://leetcode.cn/problems/palindrome-linked-list/submissions/482231684
@LC-Pam

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
