### ISSUE TITLE
Typo in Question - 1846. Maximum Element After Decreasing and Rearranging

### ISSUE THREAD

**Issue by lilweege** [LeetCode-Feedback/LeetCode-Feedback#18067]
### LeetCode Username
lilweege

### Problem number, title, and link

1846. Maximum Element After Decreasing and Rearranging https://leetcode.com/problems/maximum-element-after-decreasing-and-rearranging/description/

### Category of the bug
- [x] Problem description
- [x] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The explanation for example 2 has incorrect formatting. The correct formatting should be as follows:
"Now `arr = [1,2,3]`, which satisfies the conditions."
"The largest element in `arr` is 3."

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/59585724/28a2844e-c871-447c-8694-2920186cef43)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
