### ISSUE TITLE
[1457] [Pseudo-Palindromic Paths in a Binary Tree] Error in Solution Intuition for Approach 1

### ISSUE THREAD

**Issue by abhi2196** [LeetCode-Feedback/LeetCode-Feedback#1807]
#### Your LeetCode username
abhi2196

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Approach 1 is using Iterative Preorder Traversal. 
But the intuition slides demo Inorder Traversal. 

#### Expected behavior
Ideally, both should show the same traversal method for a better understanding of the solution.

#### Screenshots
![pseudo-palindromic-paths-in-a-binary-tree](https://user-images.githubusercontent.com/13404983/103304844-a8bfea00-4a2f-11eb-9703-036273a8f4ae.png)

**Comment by lc-kay** [comment]
Hi @abhi2196 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @abhi2196 
Thank you for your time. We've noted your report and will be making the necessary changes in the near future.
