### ISSUE TITLE
WRONG TEST CASE

### ISSUE THREAD

**Issue by arnab18maity** [LeetCode-Feedback/LeetCode-Feedback#18075]
### Category of the bug
- Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### Description of the bug
In the constraints it's clearly stating that (t.length == s.length) but for the below test case the answer is coming as true where it should be false.
Input : "12"
            "\u0067\u0068"
Output : false
Expected : true

### Code used for Submit/Run operation
```
class Solution {
public:
    bool isIsomorphic(string s, string t) {
       if(s.length() != t.length()) return false;        
       int m1[256] = {0}, m2[256] = {0}, n = s.size();
        for (int i = 0; i < n; ++i) {
            if (m1[s[i]] != m2[t[i]]) return false;
            m1[s[i]] = i + 1;
            m2[t[i]] = i + 1;
        }
        return true;
    }
};
```

### Expected behavior
In the constraints it's clearly stating that (t.length == s.length) but for the below test case the answer is coming as true where it should be false.
Input : "12"
            "\u0067\u0068"
Output : false
Expected : true

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
