### ISSUE TITLE
Missing Test Case - 1846. Maximum Element After Decreasing and Rearranging

### ISSUE THREAD

**Issue by BrazDeividas** [LeetCode-Feedback/LeetCode-Feedback#18083]
### LeetCode Username

BrazDeividas

### Problem number, title, and link

[1846. Maximum Element After Decreasing and Rearranging](https://leetcode.com/problems/maximum-element-after-decreasing-and-rearranging/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [✅] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Missing a test case like: [1, 1, 1, 10000], where the first element occurs more than once and the maximum element is greater than the length of array. 

### Language used for code

Python

### Code used for Submit/Run operation

```
from collections import Counter

class Solution:
    def maximumElementAfterDecrementingAndRearranging(self, arr: List[int]) -> int:
        max_value = max(arr)
        counts = Counter(arr).most_common(1)
        val, occurence = counts[0]

        if max_value > len(arr):
            return len(arr)
        elif occurence >= 2 and val < max_value:
            return val + 1
        else:
            return max_value
```

### Expected behavior

My current code does not pass the challenge with this test case included.

### Screenshots

Code passes.

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/90258200/82b86f42-263f-4aed-953e-2f8255e2d55c)

Test case does not pass.

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/90258200/fc4f55dd-1b6b-46d0-8fae-b59050b2ffa3)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
