### ISSUE TITLE
Missing Test Case - 1846. Maximum Element After Decreasing and Rearranging

### ISSUE THREAD

**Issue by msluszniak** [LeetCode-Feedback/LeetCode-Feedback#18087]
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
Incorrect Code getting accepted because of missing test cases

### Language used for code
Python

### Code used for Submit/Run operation

```
from collections import Counter
class Solution:
    def maximumElementAfterDecrementingAndRearranging(self, arr: List[int]) -> int:
        cnt = Counter(arr)
        n = len(arr)
        res = n
        min_val = min(cnt.keys())
        max_val = max(cnt.keys())
        if min_val == max_val and min_val < n:
            return min_val
        for key, val in cnt.items():
            if key < n:
                res -= min(val - 1, n - key - 1)
        return res
```

### Expected behavior

For testcase [2,2,2,2,2,2,2,2,2,2,2,3,3,3,3,44,44,44,44,44,44,44,44,44,10000]
Expected result is 13 while the code below returns 12

**Comment by LC-Pam** [comment]
Thank you for your time.

We've used your feedback to update the problem.

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback.

Please provide us your Leetcode Username .

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!

**Comment by msluszniak** [comment]
My Leetcode Username is ace_of_diamonds

**Comment by LC-Pam** [comment]
Rewarded
