### ISSUE TITLE
Missing Test Case - 1846. Maximum Element After Decreasing and Rearranging

### ISSUE THREAD

**Issue by shikharg1110** [LeetCode-Feedback/LeetCode-Feedback#18086]
### LeetCode Username

Shikharg1110

### Problem number, title, and link

1846. Maximum Element After Decreasing and Rearranging](https://leetcode.com/problems/maximum-element-after-decreasing-and-rearranging/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [✓] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

This additonal test case will help people to understand the problem very easily otherwise in test case 45 there is a number 10000 in a bundle of 10002 numbers of 209

### Language used for code

C++

### Code used for Submit/Run operation

```
class Solution {
public:
    int maximumElementAfterDecrementingAndRearranging(vector<int>& arr) {
        if(arr.size() == 1)
            return 1;
        sort(arr.begin(), arr.end());
        if(arr[0] != 1)
            arr[0] = 1;
        for(int i = 1; i < arr.size(); i++) {
            if(arr[i] - arr[i-1] > 1)
                arr[i] = arr[i-1]+1;
        }
        int max = *max_element(arr.begin(), arr.end());
        cout<<arr.size()<<endl;
        return max;
    }
};
// Paste your code here. Don't remove ``` given
// above and below the code.
```

### Expected behavior

This additional test case will help to understand the problem easily

### Additional context

The new test will be 
arr =
[4, 4, 10, 4, 4, 4]

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The test case [4, 4, 10, 4, 4, 4] already exists.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
