### ISSUE TITLE
Missing test case and NaN should be allowed to return 

### ISSUE THREAD

**Issue by prodigalbunch** [LeetCode-Feedback/LeetCode-Feedback#1808]
#### Your LeetCode username
prodigalbunch

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language

#### Description of the bug

**Problem 346. Moving Average from Data Stream**
If the size of the data stream is initialized to 0, then next method should return NaN.
Example 
```
["MovingAverage","next","next","next","next"]
[[0],[1],[10],[3],[5]]
```

#### Code you used for Submit/Run operation

```
class MovingAverage {

    /** Initialize your data structure here. */
    Queue<Integer> q;
    int size;
    double sum;
    public MovingAverage(int size) {
        this.q = new LinkedList<>();
        this.size = size;
        this.sum = 0;
    }
    
    public double next(int val) {
        if (this.size == 0)
            return Double.NaN;
        if (this.q.size() == this.size) {
            this.sum -= q.peek();
            this.q.remove();
        }
        this.q.add(val);
        this.sum += val;
        return this.sum/this.q.size();
    }
}
```

#### Language used for code
Java

#### Expected behavior

- There is no test case to check for the above condition.
- The code above should run (NaN should be allowed to return from the next method)

**Comment by lc-kay** [comment]
Hi @prodigalbunch 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @prodigalbunch 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
