### ISSUE TITLE
Spelling mistake: Decision Tree Explore Card -> Definition -> Model Inference - Decision Tree

### ISSUE THREAD

**Issue by cmoulicms** [LeetCode-Feedback/LeetCode-Feedback#18081]
### LeetCode Username
[cmoulicms](https://leetcode.com/cmoulicms/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support
- [x] Explore card

#### Change the spelling pedal to petal.

Actual {pedal_length<=3.0}, {pedal_length<=4.8}, {pedal_width<=1.7}

Expected {petal_length<=3.0},{petal_length<=4.8}, {petal_width<=1.7}

### Screenshots

<img width="1440" alt="Screenshot 2023-11-15 at 8 46 59 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/52199121/e1f49d92-d039-4edf-88c0-f95727d737ef">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
