### ISSUE TITLE
Missing Test Case - 1768. Merge Strings Alternately

### ISSUE THREAD

**Issue by thughari** [LeetCode-Feedback/LeetCode-Feedback#18091]
### Category of the bug

- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Adding a test case
Input:
 * word1 = "testcase"
 * word2 = "passed"
 * Output: "tpeasstsceadse"

### Code used for Submit/Run operation

```
class Solution {
    public String mergeAlternately(String word1, String word2) {
        StringBuilder result=new StringBuilder();
        int i=0;
        while(i<word1.length() || i<word2.length()){
            if(i<word1.length()){
                result.append(word1.charAt(i));
            }
            if(i<word2.length()){
                result.append(word2.charAt(i));
            }
            i++;
        }
        return result.toString();
    }
}
```

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

The judge working correctly. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
