### ISSUE TITLE
Verifying an Alien Dictionary

### ISSUE THREAD

**Issue by sandipl** [LeetCode-Feedback/LeetCode-Feedback#181]
---
name: Bug report (English)
about: Create a report to help us improve
title: 'Incorrect expected output'
labels: ''
assignees: ''

---

**What kind of the bug**
- [ ] problem
- [X] solution
- [ ] language

**Describe the bug**
The Expected value for this case is incorrect. 
Although the first character in both files is fine, the length of the first string is 
greater than the second and hence the output should be false.
Input:
["kuvp","q"]
"ngxlkthsjuoqcpavbfdermiywz"
Output:
false
Expected:
true

**what language is your code written in**
Java

**The code you submit/run**
```
// Verifying an Alien Dictionary
class Solution {
    public boolean isAlienSorted(String[] words, String order) {
        HashMap <Character, Integer> map = new HashMap();
        for(int i = 0; i < order.length(); i ++){
            map.put(order.charAt(i), i);
        }

        for(int i = 0; i < words.length-1; i ++){
            int j = i+1;         
            int k = Math.min(words[i].length(), words[j].length());                
            for(int x = 0; x < k; x++){
                char iChar = words[i].charAt(x);
                char jChar = words[j].charAt(x);
                if(map.get(iChar) < map.get(iChar)){
                    continue;
                }else if(map.get(iChar) > map.get(iChar)){
                    return false;
                } 
            }
            if(words[i].length() > words[j].length()){
                return false;
            }
        }
        return true;
    }
}
```

**Expected behavior**
The Expected value for this case should be false.

**Screenshots**

**Additional context**
https://leetcode.com/submissions/detail/328876549/

**Comment by CooperCooperCooper** [comment]
Hi @sandipl,
Thank you for reaching out to us! We've tested your code on "Run Code" and "Submit". The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.

**Comment by sandipl** [comment]
Hi @CooperCooperCooper , Thank you for looking into the issue. My issue is not that I am getting different outputs for Run Code and Submit. I feel the expected value for the input ["kuvp","q"]
"ngxlkthsjuoqcpavbfdermiywz" is incorrect. For this input, the output should be false as the first string is larger than the second even though the first character is lexicographically sorted. Let me know your thoughts on the same.

**Comment by CooperCooperCooper** [comment]
Hi @sandipl,
Thank you for your clarification. I see what you mean. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @sandipl,
Thank you for your time. Our team took a thorough look at this issue. We found the string length has nothing to do with this particular case. We appreciate your support.
