### ISSUE TITLE
Missing Test Case - 414. Third Maximum Number

### ISSUE THREAD

**Issue by kanika-10** [LeetCode-Feedback/LeetCode-Feedback#1810]
#### Your LeetCode username
kanika_10

#### Category of the bug
- [ ] Solution 

#### Description of the bug
a test case is not included 
test case : [ ]

#### Code you used for Submit/Run operation

```
// Third Maximum Number
class Solution {
public:
    int thirdMax(vector<int>& nums) {
        int ans = nums[0] , count = 1;
            
        sort(nums.begin(), nums.end());
        for(int i=nums.size()-1; i>0; i--)
        {
            if(nums[i] > nums[i-1])
            {
                count++;
                ans = nums[i];
            }
            if(count == 3)
            {
                ans = nums[i - 1];
                break;
            }
        }
        return ans;
    }
};
```

#### Language used for code
 C++ 

#### Expected behavior
code must not be accepted as the test case is missing but it got accepted

**Comment by lc-kay** [comment]
Hi @kanika-10 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @kanika-10 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
