### ISSUE TITLE
Missing Test Case - 218. The Skyline Problem

### ISSUE THREAD

**Issue by moshimowang** [LeetCode-Feedback/LeetCode-Feedback#18106]
### LeetCode Username

moshimowang

### Problem number, title, and link

[218. The Skyline Problem](https://leetcode.com/problems/the-skyline-problem/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

My solution passed official test cases, but failed the one I created as follows:

[[0,2,5],[0,2,3],[2,3,4]]

### Language used for code

Python

### Code used for Submit/Run operation

```
from heapq import heappop, heappush, heapify

class Solution:
    def getSkyline(self, buildings: List[List[int]]) -> List[List[int]]:
        points = []
        for i, b in enumerate(buildings):
            points.append((b[0], -b[2], 'l', i))
            points.append((b[1], -b[2], 'r', i))
        heapify(points)

        ans = []
        curr_h = -1
        curr_idx = -1
        height_pq = []
        finished = [False] * len(buildings)
        while points:
            x, h, l_or_r, idx = heappop(points)
            if l_or_r == 'l':
                if -h > curr_h:
                    curr_h = -h
                    curr_idx = idx
                    ans.append([x, -h])
                heappush(height_pq, (h, idx))
            else:
                finished[idx] = True
                if idx == curr_idx:
                    while height_pq:
                        height, index = heappop(height_pq)
                        if not finished[index]:
                            curr_h = -height
                            curr_idx = index
                            if curr_h < -h:
                                if ans[-1][0] == x:
                                    ans.pop()
                                ans.append([x, -height])
                            heappush(height_pq, (height, index))
                            break
                    else:
                        if ans[-1][0] == x:
                            ans.pop()
                        curr_h = -1
                        curr_idx = -1
                        ans.append([x, 0])
        return ans
```

### Expected behavior

My solution passed official test cases, but failed the one I created as follows:

[[0,2,5],[0,2,3],[2,3,4]]

My solution should not have been accepted.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
