### ISSUE TITLE
Missing Test Cases - 1751. Maximum Number of Events That Can Be Attended II

### ISSUE THREAD

**Issue by Prog-Jacob** [LeetCode-Feedback/LeetCode-Feedback#18104]
### LeetCode Username
Prog_Jacob

### Problem number, title, and link
[1751. Maximum Number of Events That Can Be Attended II](https://leetcode.com/problems/maximum-number-of-events-that-can-be-attended-ii/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
The current testcases contain many duplicate elements. Therefore, by removing duplicates, one can easily optimize against TLE verdict. That's what I did; however, the testcase I generated didn't pass by my solution.

### Language used for code
Rust

### Code used for Submit/Run operation
```
impl Solution {
    pub fn max_value(mut events: Vec<Vec<i32>>, k: i32) -> i32 {
        events.sort_unstable();
        events.dedup();

        let (n, k) = (events.len(), k as usize);
        let mut memo = vec![vec![-1; k]; n];
        dp(0, 0, &events, &mut memo)
    }
}

fn dp(i: usize, j: usize, e: &Vec<Vec<i32>>, m: &mut Vec<Vec<i32>>) -> i32 {
    if i >= m.len() || j >= m[0].len() { return 0 };
    if m[i][j] != -1 { return m[i][j] };
    m[i][j] = 0;

    for k in i..m.len() {
        if i == 0 || e[i-1][1] < e[k][0] {
            m[i][j] = m[i][j].max(e[k][2] + dp(k+1, j+1, e, m));
        } 
    }

    m[i][j]
}
```

### Additional context
I guess any test case with the maximum constraint with `events` having unique elements will do the trick. In my case, I used `k = 10` and $events[i] = [i+1, i+1, i+1]$ for $i \in [0, 10^5)$.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
