### ISSUE TITLE
WRONG Test Case - 853. Car Fleet

### ISSUE THREAD

**Issue by Adolphe1501** [LeetCode-Feedback/LeetCode-Feedback#18107]
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [X] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
The value return is 2 while the test case only get it as 1
### Code used for Submit/Run operation

```
class Solution(object):
    def carFleet(self, target, position, speed):
        """
        :type target: int
        :type position: List[int]
        :type speed: List[int]
        :rtype: int
        """
        
        cars = [[p, s] for p, s in zip(position, speed)]

        fleet = []
        for p, s in sorted(cars)[::-1] :
            fleet.append((target - p) / s)
            if len(fleet) > 1 and fleet[-1] <= fleet[-2]:
                fleet.pop()
        return len(fleet)
```

### Expected behavior
the test case 11 don't work properly it should get the return value is 2 not 1

### Screenshots

<img width="1645" alt="Capture d’écran 2023-11-17 à 03 05 00" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/100210115/2a6491fe-bb40-4c55-8af0-c99f08705d00">
<img width="1062" alt="Capture d’écran 2023-11-17 à 03 08 32" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/100210115/f06b7245-76f1-4a56-981a-d959413311ae">

### Additional context

Submission Link : https://leetcode.com/problems/car-fleet/submissions/1100464865?source=submission-noac

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The judge working correctly:
![Screen Shot 2023-11-17 at 2 57 48 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/90864e91-ad21-4b4a-b03e-3df6ef588828)


If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
