### ISSUE TITLE
Faulty Test Case - 5. Longest Palindromic Substring

### ISSUE THREAD

**Issue by StefanTobler** [LeetCode-Feedback/LeetCode-Feedback#1811]
#### Category of the bug
- [X] Question
- [X] Solution
- [ ] Language

#### Description of the bug

A palindrome is "A palindrome is a word, number, phrase, or other sequence of characters which reads the same backward as forward", this is irrelevant of the case of the characters, as "Anna" and "Racecar" are considered palindromes even though the first letter and the last letter are different cases.

The problem states that:

> Given a string `s`, return the _longest palindromic substring_ in `s`.

and that 

> `s` consist of only digits and English letters (lower-case and/or upper-case)

This references that the test cases may have mixed cases. When testing my code I ran it against the test case `"hellothisisaRaceCaRsentence"`, my program correctly identified "RaceCaR" as the solution where they checking code identified "isi" as the solution. I believe this is because the solution code is not ignoring the case when considering whether or not a string is a palindrome. 

#### Code you used for Submit/Run operation

```
// Longest Palindrome
class Solution:
    def longestPalindrome(self, s: str) -> str:
        def is_palindrome(s):
            return s.lower() == s[::-1].lower()
        
        longest_palindrome = s[0]
        
        for i in range(len(s)): # n
            for j in range(i+1, len(s)): # n-1
                if is_palindrome(s[i:j]) and len(s[i:j]) > len(longest_palindrome):
                    longest_palindrome = s[i:j]
            
        return longest_palindrome
```

#### Language used for code

Python

#### Expected behavior

With the test case `"hellothisisaRaceCaRsentence"`, my program behaves as expected and returns "RaceCaR" as the correct result, however, the test code returns "isi" as the correct result.

#### Screenshots

![image](https://user-images.githubusercontent.com/22108632/103337590-da45af00-4a49-11eb-8a3f-cc84fe080391.png)

**Comment by lc-kay** [comment]
Hi @StefanTobler 
Thank you for reaching out to us. Can you please provide the submission details link to this solution?

**Comment by StefanTobler** [comment]
Hello @lc-kay, this was not in one of the provided test cases, it is one that I had come up with on my own.

**Comment by lc-kay** [comment]
@StefanTobler Yes, I understand. However, when I ran your code, I received wrong answer. And to qualify for rewards, you must submit an accepted solution that fails the test case.

**Comment by lc-kay** [comment]
Hi @StefanTobler 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
