### ISSUE TITLE
Missing Test Case - 1683. Invalid Tweets

### ISSUE THREAD

**Issue by AbhishekMandge** [LeetCode-Feedback/LeetCode-Feedback#18117]
### LeetCode Username
 Abhishek_Mandge

### Problem number, title, and link
[1683. Invalid Tweets](https://leetcode.com/problems/invalid-tweets/)

### Category of the bug

- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug
 Code getting accepted because of missing test cases

### Language used for code
 MYSQL

### Code used for Submit/Run operation

```
select tweet_id from Tweets
where LENGTH(content) > 15;
```

### Expected behavior
 LENGTH() returns the length of the string measured in bytes.
CHAR_LENGTH() returns the length of the string measured in characters. All test case working same for both code.

### Additional context
We can modify test case like | tweet_id | content                          |
| -------- | -------------------------------- |
| 1        | " Vote for Bidenn "                   |
| 2        | Let us make America great again! |

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
