### ISSUE TITLE
Missing Test Case - 1068. Product Sales Analysis I

### ISSUE THREAD

**Issue by berkay-akkus** [LeetCode-Feedback/LeetCode-Feedback#18113]
### Problem number, title, and link
1068. Product Sales Analysis I https://leetcode.com/problems/product-sales-analysis-i/description/?envType=study-plan-v2&envId=top-sql-50

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
For the following input (my own test case), a duplicated output is expected however it gives a nonduplicate output, but this code passes other test cases.
Sales =
| sale_id | product_id | year | quantity | price |
| ------- | ---------- | ---- | -------- | ----- |
| 1       | 100        | 2008 | 10       | 5000  |
| 2       | 100        | 2009 | 12       | 5000  |
| 7       | 200        | 2011 | 15       | 9000  |
| 5       | 200        | 2011 | 15       | 9000  |

Product =
| product_id | product_name |
| ---------- | ------------ |
| 100        | Nokia        |
| 200        | Apple        |
| 300        | Samsung      |

### Language used for code
SQL

### Code used for Submit/Run operation
```
SELECT DISTINCT P.product_name, S.year, S.price
FROM Product P INNER JOIN Sales S ON P.product_id = S.product_id
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
