### ISSUE TITLE
Incorrect space complexity - 815. Bus Routes

### ISSUE THREAD

**Issue by przemek3d88** [LeetCode-Feedback/LeetCode-Feedback#18110]
### LeetCode Username
przemysaw2

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug
Approach 2: Breadth-First Search (BFS) with Routes as Nodes

Space complexity: O(M^2 + M log K)

The last sentence mentions time complexity, instead of space complexity: Thus, the total time complexity is equal to O(M^2 + M * log K).

Besides, the space complexity is still incorrect. I think that you should not multiply the log K by M, as you do not sort in parallel. You sort sequentially and the memory used during the previous sort does not affect the next sort.

I think the space complexity is O(M^2 + log K).

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
