### ISSUE TITLE
Missing Test Case - 1846. Maximum Element After Decreasing and Rearranging

### ISSUE THREAD

**Issue by Karandeep1234** [LeetCode-Feedback/LeetCode-Feedback#18124]
### LeetCode Username

Karandeep1234

### Problem number, title, and link
1846. Maximum Element After Decreasing and Rearranging https://leetcode.com/problems/maximum-element-after-decreasing-and-rearranging/ 

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Wrong Solution was accepted because of missing testcases. Code giving wrong answer on a test case but still accepted.

Testcase: [2,2,2,2,3]

### Code used for Submit/Run operation

```
class Solution {
    public int maximumElementAfterDecrementingAndRearranging(int[] arr) {
        Arrays.sort(arr);
        if(arr[0] == arr[arr.length - 1]) {
            if(arr[0] == 1) return 1;
            return arr.length;
        }
        for(int i = 1; i < arr.length;i++){
            if(!(Math.abs(arr[i]-arr[i-1])<=1)){
                arr[i] = arr[i-1]+1;
            }
        }
        return (arr[arr.length-1]-arr[0]+1);
    }
}
```

### Expected behavior

Output: 2
Expected: 3

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
