### ISSUE TITLE
Missing Test Case - 717. 1-bit and 2-bit Characters

### ISSUE THREAD

**Issue by Mohsin-Satti** [LeetCode-Feedback/LeetCode-Feedback#1812]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@Mohsin-Satti Please provide the accepted code and the failed test case. Thank you!

**Comment by lc-kay** [comment]
Hi @Mohsin-Satti 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
