### ISSUE TITLE
Editorial - 1877. Minimize Maximum Pair Sum in Array, Inline LaTeX is incorrectly escaped

### ISSUE THREAD

**Issue by kenlau46** [LeetCode-Feedback/LeetCode-Feedback#18120]
### LeetCode Username

kenlau

### Problem number, title, and link

[1877. Minimize Maximum Pair Sum in Array](https://leetcode.com/problems/minimize-maximum-pair-sum-in-array/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug

In editorial of problem 1877 (Minimize Maximum Pair Sum in Array), the inline LaTeX got escaped incorrectly by backticks, please refer to screenshot which is highlighted with red boxes. (Only highlight some as an example)

### Language used for code

N/A

### Code used for Submit/Run operation

N/A

### Expected behavior

The inline LaTeX should not be escaped by "`"

### Screenshots

<img width="700" alt="screenshot" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/7280584/ab6ad979-e1e4-4d01-b70d-86e49583f432">

### Additional context

N/A

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
