### ISSUE TITLE
Missing Test Case - 2700. Differences Between Two Objects

### ISSUE THREAD

**Issue by kentshenlim** [LeetCode-Feedback/LeetCode-Feedback#18129]
### LeetCode Username
soyukotoda

### Problem number, title, and link
[2700. Differences Between Two Objects](https://leetcode.com/problems/differences-between-two-objects/)

### Category of the bug
- [ ] Problem description
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug
Can `obj1` be an array while `obj2` is not? (this is allowed in Test) If so, what should be the expected output?

### Language used for code
JavaScript

### Code used for Submit/Run operation

```JS
// Paste your code here. Don't remove ``` given
// above and below the code.
var objDiff = function (o1, o2) {
    const res = {};
    helper(o1, o2, res);
    return res;


    function helper(o1, o2, edit) {
        for (const key in o1) {
            if (o2[key] === undefined) continue;
            const [v1, v2] = [o1[key], o2[key]];
            if (v1 === v2) continue;
            if (v1 === null || v2 === null) edit[key] = [v1, v2];
            else if (!(v1 instanceof Object) || !(v2 instanceof Object)) edit[key] = [v1, v2];
            else if (Array.isArray(v1) !== Array.isArray(v2)) edit[key] = [v1, v2];
            else {
                edit[key] = {};
                helper(v1, v2, edit[key]);
                if (!Object.keys(edit[key]).length) delete edit[key];
            }
        }
    }
};
```

### Expected behavior

- [AC](https://leetcode.com/problems/differences-between-two-objects/submissions/1101110109) on submission,  but wrong answer on Run
- `o1 = []`, `o2 = {}`, app says expected output is `[[], {}]`, but strictly following problem description, all keys in both (which is nothing) have the same value, so shouldn't this expect `{}`?
- `o1 = [1]`, `o2 = {}`, the only key in `o1` is `"0"`, and there is no key in `o2`, so shouldn't this expect `{}` as well? App expecting `[[1],{}]`

### Screenshots

![lcis1](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/106628390/afaa4f9f-0e43-41eb-b980-1d089add5e5b)
![lcis2](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/106628390/a1294457-1d2c-42d2-90f9-bc88e1f1984b)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
