### ISSUE TITLE
Problem 236: lowest-common-ancestor-of-a-binary-tree/

### ISSUE THREAD

**Issue by jostroff** [LeetCode-Feedback/LeetCode-Feedback#18126]
This error happens even when I use the Editorial solutions:

java.lang.NumberFormatException: Cannot parse null string
  at line 630, java.base/java.lang.Integer.parseInt
  at line 786, java.base/java.lang.Integer.parseInt
	at __Deserializer__.toInteger(Unknown Source)
  at line 97, __Driver__.main

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The submission code link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
