### ISSUE TITLE
Incorrect Test Case - 334. Increasing Triplet Subsequence

### ISSUE THREAD

**Issue by thughari** [LeetCode-Feedback/LeetCode-Feedback#18131]
### Category of the bug

- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### Code used for Submit/Run operation

```
class Solution {
    public boolean increasingTriplet(int[] nums) {
        for(int i=0; i<nums.length-2;i++){
            if(nums[i]<nums[i+1] && nums[i+1]<nums[i+2]){
                return true;
            }
        }
        return false;
    }
}

```

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team

**Comment by JonasJason** [comment]
@LC-Pam Could you please update the problem description to mention that the triplet DOES NOT need to be consecutive? I think that would cut down on some of the confusion around this problem.
