### ISSUE TITLE
Typo in Binary Search Explore Card - Binary Search Template III

### ISSUE THREAD

**Issue by Y-Rov** [LeetCode-Feedback/LeetCode-Feedback#18132]
### LeetCode Username

[seeker_of_balance](https://leetcode.com/anacondrai/)

### Category of the bug
- [x] Language

### Description of the bug

Hello, LeetCode team 😄 . It's me again, the text editor))
If we go through the section "Binary Search Template III" in [Binary Search Explore Card](https://leetcode.com/explore/learn/card/binary-search/135/template-iii/936/) and stop at "Key Attributes" subsection (the 3-rd item):

> Gurantees Search Space is at least 3 in size at each step

The word "Gurantees" has a typo.

### Expected behavior

The corrected sentence should look like this:

> Guarantees Search Space is at least 3 in size at each step

### Screenshots

![Guarantees_Typo](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73534920/55f08bac-d2e6-472a-b9f8-78255f16d71b)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by Y-Rov** [comment]
Hi @LC-Pam, thank you for your reply. The issue seems to be solved. Best wishes to LeetCode team.

![Guarantees_Corrected](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73534920/13492cb8-8af9-442a-8462-c20f62203d40)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
