### ISSUE TITLE
Missing Test Case - 1838. Frequency of the Most Frequent Element

### ISSUE THREAD

**Issue by IliasaurCat** [LeetCode-Feedback/LeetCode-Feedback#18138]
### LeetCode Username

IliasaurCat

### Problem number, title, and link

1838. Frequency of the Most Frequent Element https://leetcode.com/problems/frequency-of-the-most-frequent-element/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [X] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

An accepted solution fails on the following testcase:
[1838.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/13401339/1838.txt)

### Language used for code

C#

### Code used for Submit/Run operation

```
public class Solution
{
    public int MaxFrequency(int[] nums, int k)
    {
        Array.Sort(nums);
        int lastL = 1;
        int max = 1;
        int j = 0;
        int bu = 0;

        for (int i = 1; i < nums.Length; ++i)
        {
            bu += lastL * (nums[i] - nums[i - 1]);
            ++lastL;
            if (bu > k)
            {
                for (; j < nums.Length; ++j)
                {
                    if (bu <= k) break;
                    --lastL;
                    bu -= nums[i] - nums[j];
                }
            }
            max = Math.Max(max, lastL);
        }

        return max;
    }
}
```

### Expected behavior

Output: 30000
Expected: 29999

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
