### ISSUE TITLE
BuG - 104. Maximum Depth of Binary Tree-- Run Code inconsistent with Submit Solution

### ISSUE THREAD

**Issue by jitendrac** [LeetCode-Feedback/LeetCode-Feedback#1813]
#### Your LeetCode username

jitendrac

#### Category of the bug

- [1] Solution

#### Description of the bug

Same input, differed output on local vs submission

#### Code you used for Submit/Run operation

```
/**
 * Definition for a binary tree node.
 * function TreeNode(val, left, right) {
 *     this.val = (val===undefined ? 0 : val)
 *     this.left = (left===undefined ? null : left)
 *     this.right = (right===undefined ? null : right)
 * }
 */
max_level=0
function traverse(root,level=0){
    if(root==null)return;
    
    if(level+1>max_level)max_level=level+1;
    traverse(root.left,level+1);
    traverse(root.right,level+1);
}

/**
 * @param {TreeNode} root
 * @return {number}
 */
var maxDepth = function(root) {
    traverse(root);
    return max_level;
    
};

```

#### Language used for code

Javascript

#### Screenshots

![image](https://user-images.githubusercontent.com/1154328/103356946-0c9ded80-4ad8-11eb-81c9-5ac8be776d4d.png)

**Comment by lc-kay** [comment]
@jitendrac 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
