### ISSUE TITLE
Missing Test Case - 220. Contains Duplicate III

### ISSUE THREAD

**Issue by Rajat2024** [LeetCode-Feedback/LeetCode-Feedback#18136]
### LeetCode Username

Rajat241302

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Incorrect or missing "Related Topics"
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

There is a Testcase where Any code(T.C=O(n^2)) should give Time Limit Exceeded but that particular testcase is not present.
Problem-220.Contains Duplicate III

### Code used for Submit/Run operation

```
class Solution {
public:
    bool containsNearbyAlmostDuplicate(vector<int>& nums, int indexDiff, int valueDiff) {
       if(nums.size()==100000&& nums[0]==1)
           return 0;
        for(int i=0;i<nums.size();i++){
            for(int j=i+1;j<=i+indexDiff&&j<nums.size();j++){
                if(abs(nums[i]-nums[j])<=valueDiff)return true;
            }
        }
        return false;
    }
};
```

### Expected behavior
The code should give TLE because of N^2 Complexity in worst test case,but that worst case scenerio is not present in Leetcode Testcases. This is the testcase where it should give TLE [Testcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/13400773/Testcase.txt)

Submitted Link - [Accepted Link](https://leetcode.com/submissions/detail/1101474196/)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

We can't add the test case currently because of technical issues.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
