### ISSUE TITLE
Hint Typo - 2940. Find Building Where Alice and Bob Can Meet

### ISSUE THREAD

**Issue by Ming91** [LeetCode-Feedback/LeetCode-Feedback#18144]
### LeetCode Username

[wming9310](https://leetcode.com/wming9310)

### Problem number, title, and link

[2940. Find Building Where Alice and Bob Can Meet](https://leetcode.com/problems/find-building-where-alice-and-bob-can-meet/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [x] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The first part of `Hint` (3/4):

> "Otherwise, we need to find the smallest index `t` such that `y < t` and `heights[x] < heights[y]`."

is wrong since we talked about the condition where `heights[x] < heights[y]` in `Hint` (2/4). The corresponding query result would be `y`.

The correct version should be 

> "Otherwise, we need to find the smallest index `t` such that `y < t` and `heights[x] < heights[t]`."

The right part of the inequality  should be `heights[t]` rather than `heights[y]`.

### Screenshots

![Screenshot 2023-11-18 235033_2](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/3740139/b01d951d-6651-4a50-b79e-b8d71c9890b1)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
