### ISSUE TITLE
Missing Testcases - 2940. Find Building Where Alice and Bob Can Meet

### ISSUE THREAD

**Issue by Ming91** [LeetCode-Feedback/LeetCode-Feedback#18149]
### LeetCode Username

[wming9310](https://leetcode.com/wming9310)

### Problem number, title, and link

[2940. Find Building Where Alice and Bob Can Meet](https://leetcode.com/problems/find-building-where-alice-and-bob-can-meet/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The time complexity of my monotonic stack solution worst case could be $O(m*n)$ but it got accepted and beat 100%.  https://leetcode.com/submissions/detail/1101942489/

So I constructed a worst-case testcase and my solution got TLE. 
[2940.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/13402532/2940.txt)

My solution is to use a monotonic stack to find the left-most `j` for each `i` such that `j > i and heights[j] > heights[i]` and stores in the `next` array. For each query `[a, b]` that `a < b`, we first check `next[a]` and `next[b]`. If not valid, we use `next` to find the next candidate until valid. 

So the worst case here is `heights = [h, h+1, 1, 2, ..., h - 1]` and `queries = [[0, 2], [0, 3], ...]`, where the `next[0] = 1, next[1] = null and next[i] = i + 1 for i > 1`. Each query `[0, i]` we need to go through `[i - 1, n - 1]` which costs $O(n)$. For `m` queries, it's $O(m * n)$.

BTW, this solution also passed the test case in this issue:
https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/18148

So the test case I provided is not redundant

### Language used for code

Java

### Code used for Submit/Run operation

```Java
class Solution {
    public int[] leftmostBuildingQueries(int[] heights, int[][] queries) {
        Deque<Integer> stack = new ArrayDeque<>();
        int n = heights.length;
        int[] next = new int[n];
        Arrays.fill(next, n);
        for (int i = 0; i < n; i++) {
            while (!stack.isEmpty() && heights[stack.peek()] < heights[i]) {
                next[stack.pop()] = i;
            }
            stack.push(i);
        }
        int m = queries.length;
        int[] ans = new int[m];
        for (int i = 0; i < m; i++) {
            int a = queries[i][0];
            int b = queries[i][1];
            if (a == b) {
                ans[i] = a;
                continue;
            }
            if (a > b) {
                int temp = a;
                a = b;
                b = temp;
            }
            if (heights[a] < heights[b]) {
                ans[i] = b;
                continue;
            }
            if (next[a] == n) {
                ans[i] = -1;
                continue;
            }
            b = Math.max(next[b], next[a]);
            while (b < n && heights[a] >= heights[b]) {
                b = next[b];
            }
            ans[i] = b == n ? -1 : b;
        }
        return ans;
    }
}
```

### Expected behavior

My solution should not get accepted. 

### Screenshots

![Screenshot 2023-11-19 020859](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/3740139/25779ceb-fca5-451b-a920-e363c65832f6)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

We can't add the test case currently because of technical issues.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
