### ISSUE TITLE
Missing Test Case - 833. Find And Replace in String

### ISSUE THREAD

**Issue by nadarb** [LeetCode-Feedback/LeetCode-Feedback#18143]
### Problem number, title, and link

833. [Find And Replace in String](https://leetcode.com/problems/find-and-replace-in-string/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

A lot of submissions for the given problem which used in-situ replacement with incorrect logic are being accepted. The below 2 test cases would catch such solutions

### Language used for code

Java

### Code used for Submit/Run operation

Incorrect code which passes
```
class Solution {
    public String findReplaceString(String S, int[] indices, String[] sources, String[] targets) {
        List<int[]> sorted = new ArrayList<>();
        for (int i = 0 ; i < indices.length; i++) sorted.add(new int[]{indices[i], i});
        Collections.sort(sorted, Comparator.comparing(i -> -i[0]));
        for (int[] ind: sorted) {
            int i = ind[0], j = ind[1];
            String s = sources[j], t = targets[j];
            if (S.substring(i, Math.min(i + s.length(), S.length())).equals(s)) S = S.substring(0, i) + t + S.substring(i + s.length());
        }
        return S;
    }
}
```

In contrast the code used by the online judge is working fine.

### Expected behavior

The code is accepted but it should fail

### Screenshots

<img width="967" alt="Screenshot 2023-11-19 at 03 53 39" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/10659177/141db3e6-b94b-4fa5-8b32-41b96e7ce897">

##### Case 1:
s = "abcdef"
indices = [2,2]
sources = ["cdef","feg"]
targets = ["feg","abc"]

##### Case 2:
s = "abcdef"
indices = [2,2]
sources = ["feg","cdef"]
targets = ["abc","feg"]

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
