### ISSUE TITLE
Leetcode #8 

### ISSUE THREAD

**Issue by thatUndefinedGuy** [LeetCode-Feedback/LeetCode-Feedback#18141]
### LeetCode Username

UNDeF1ND1

### Problem number, title, and link

#8
string-to-integer-atoi
[https://leetcode.com/problems/string-to-integer-atoi/](url)
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [  ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

In this problem there are multiple test cases that do not make sense, and numerous edge cases

### Language used for code

Python

### Code used for Submit/Run operation

```
class Solution(object):
    def myAtoi(self, s):
        """
        :type s: str
        :rtype: int
        """
        acc = ["-","1","2","3","4","5","6","7","8","9","0"]#accepted
        ans = ""
        for i in s:
            if i in acc:
                ans += i
        return int(ans)

```

### Expected behavior

"words and 987"
Would return
"987"

### Screenshots

![Screenshot (114)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/137335040/8b90c0a5-7d6d-4439-bea2-442c05f875c6)

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
