### ISSUE TITLE
Wrong Test Case: 8. String to Integer (atoi)

### ISSUE THREAD

**Issue by hellokaiwen** [LeetCode-Feedback/LeetCode-Feedback#18140]
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
With the same test case run on my local IDE and the online console, the results do not match.

### Language used for code
Python3

### Code used for Submit/Run operation

```
class Solution:
    def myAtoi(self, s: str) -> int:
        digits = '0123456789'
        upper_bound = 2 ** 32 - 1
        lower_bound = -2 ** 32
        sign = 0  # 0: non-negative, 1: negative

        i = 0
        while s[i] not in digits:
            i = i + 1

        if i - 1 >= 0:
            sign = 1 if s[i - 1] == '-' else 0

        result = 0
        while i < len(s) and s[i] in digits:
            result = result * 10 + int(s[i])
            if result > upper_bound:
                return upper_bound
            elif result < lower_bound:
                return lower_bound
            else:
                i = i + 1

        return result if sign == 0 else -1 * result
```

### Expected behavior
987 was expected to be returned, just as it did in my local IDE, instead of outputting 0.

### Screenshots
<img width="787" alt="Screenshot 2023-11-18 at 18 19 19" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/115329498/7d6b927e-ed57-4cad-9c5e-2362bb6bf52f">
<img width="1398" alt="Screenshot 2023-11-18 at 18 19 57" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/115329498/72e34d08-c413-4f04-8e14-769e4649f390">

**Comment by stormsunshine** [comment]
Please read problem description carefully.

Only leading whitespace characters should be ignored. If a leading character is a letter, then it should NOT be ignored, and in this case, since the leading character is not a digit or a plus or minus sign, no digit is read, so the result is 0.
