### ISSUE TITLE
Missing Test Case - 26. Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by vigneshTheDev** [LeetCode-Feedback/LeetCode-Feedback#1814]
#### Your LeetCode username

vigneshTheDev

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

If the removeDuplicates function leaves extra elements in the modified array, the test case is not reporting it as a failure.

#### Code you used for Submit/Run operation

```js
/**
 * @param {number[]} nums
 * @return {number}
 */
var removeDuplicates = function(nums) {
    let count = 0;
    let j = 0;
    for (let i = 0; i < nums.length; i++) {
        nums[j] = nums[i];
        while(nums[i] === nums[i + 1]) i++;
        j++;
        count++;
    }
    
    return count++;
};
```

#### Language used for code

JavaScript

#### Expected behavior

If extra elements are there in the modified array, the test should fail. 
E.g.
Input: [1, 1, 2]
Expected Output: [1, 2]
Actual Output: [1, 2, 2]
The test cases are not catching this

#### Screenshots

N/A

#### Additional context

N/A

**Comment by lc-kay** [comment]
Hi @vigneshTheDev 
Thank you for reaching out to us. When I ran your code with the test case provided, the expected output = actual output. Please send me a screenshot if it is not the same on your side and I will reopen this issue. 
<img width="768" alt="Screen Shot 2021-01-05 at 10 40 28 AM" src="https://user-images.githubusercontent.com/70870126/103685683-7f78ef80-4f42-11eb-991d-8f699218f068.png">

**Comment by vigneshTheDev** [comment]
@lc-kay, That's confusing. When I run the code outside the LeetCode environment, the actual output is [1, 2, 2]. But inside the LeetCode environment, the actual output is [1, 2]. I think it's how LeetCode handles array outputs. It checks only the required indices and if something else is there beyond that, it simply ignores it.

Please have a look at this: https://repl.it/@vigneshTheDev/LeetCode-removeDuplicates-Bug

**Comment by lc-kay** [comment]
@vigneshTheDev Since we don't have any information on any outside environment, we are unable to troubleshoot this issue. We can only provide support on issues that occurred on our site. Thank you for understanding.

**Comment by vigneshTheDev** [comment]
@lc-kay, Yeah I understand. Let me try to rephrase the problem. In the above example, the actual output provided in the node js is [1, 2, 2] which is correct. But leet code test is reading the actual output as [1, 2] which is wrong.

**Comment by lc-kay** [comment]
@vigneshTheDev This is not an issue. This the expected behavior. The user returns x which is the number of elements the driver should read from the array.
The array is [1,2,2] and when the user returns 2, the driver outputs [1,2]
If the user returned 1, the driver will output [1]
If the user returns 3, the driver will output [1,2,2]
