### ISSUE TITLE
Invalid Test Case - 236. Lowest Common Ancestor of a Binary Tree

### ISSUE THREAD

**Issue by edwardwang888** [LeetCode-Feedback/LeetCode-Feedback#18142]
### LeetCode Username

edwardwang888

### Problem number, title, and link

https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The test case is malformed and missing required inputs.
Interestingly, I did not encounter the invalid test case reported in https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/18128.

### Language used for code

Python & Python3
(same behavior in both)

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

### Screenshots

The graph is inputted correctly, but `p` and `q` are missing:
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/40527812/247906cb-4985-45d6-b34d-59056808bd36)
Clicking on "Use Testcase" gives:
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/40527812/11df80c3-e76b-4f1e-89d0-89e2a5697454)

**Comment by VMAtm** [comment]
Same issue for me, impossible to solve the task

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
