### ISSUE TITLE
Typo in the hint - 2940. Find Building Where Alice and Bob Can Meet

### ISSUE THREAD

**Issue by przemek3d88** [LeetCode-Feedback/LeetCode-Feedback#18150]
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [x] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
Hint 3:

```
Otherwise, we need to find the smallest index t such that y < t and heights[x] < heights[y]. Note that heights[y] <= heights[x], so heights[x] < heights[t] is a sufficient condition.
```

It should be:
```
Otherwise, we need to find the smallest index t such that y < t and heights[x] < heights[t]. Note that heights[y] <= heights[x], so heights[x] < heights[t] is a sufficient condition.
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've used your feedback to update the problem.

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback.

Please provide us your Leetcode Username .

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!
