### ISSUE TITLE
Missing Test Case - 2694. Event Emitter

### ISSUE THREAD

**Issue by kapoostin** [LeetCode-Feedback/LeetCode-Feedback#18154]
### LeetCode Username
kapoostin

### Problem number, title, and link
2694. Event Emitter https://leetcode.com/problems/event-emitter/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
I'm using the push method to obtain the index, and it's saved in the closure of the function. However, after unsubscribing and using splice to mutate the array, values get new indices. So, for example, if we have saved three callbacks and we unsubscribe from the second one, the third becomes the second, but its index remains the same. Consequently, when attempting to unsubscribe, it won't be removed.

### Language used for code
JavaScript

### Code used for Submit/Run operation

```javascript
class EventEmitter {
  constructor() {
    this.events = {}
  }
  /**
   * @param {string} eventName
   * @param {Function} callback
   * @return {Object}
   */
  subscribe(eventName, callback) {
    this.events[eventName] ||= [];
    const idx = this.events[eventName].push(callback) - 1;

    return {
      unsubscribe: () => {
        this.events[eventName].splice(idx, 1)
      }
    };
  }

  /**
   * @param {string} eventName
   * @param {Array} args
   * @return {Array}
   */
  emit(eventName, args = []) {
    return this.events[eventName]?.map((cb) => cb(...args)) || [];
  }
}

/**
 * const emitter = new EventEmitter();
 *
 * // Subscribe to the onClick event with onClickCallback
 * function onClickCallback() { return 99 }
 * const sub = emitter.subscribe('onClick', onClickCallback);
 *
 * emitter.emit('onClick'); // [99]
 * sub.unsubscribe(); // undefined
 * emitter.emit('onClick'); // []
 */
```

### Expected behavior

This test should be added:

Input: `["EventEmitter", "subscribe", "subscribe", "subscribe", "unsubscribe", "unsubscribe", "emit"]`
`[[], ["firstEvent", "x => x + 1"], ["firstEvent", "x => x + 2"], ["firstEvent", "x => x + 3"], [1], [2], ["firstEvent", [5]]]`

Output: `[[],["subscribed"],["subscribed"],["subscribed"],["unsubscribed",1],["unsubscribed",2],["emitted",[6]]]`

Then my code won't work.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
