### ISSUE TITLE
1188. Design Bounded Blocking Queue

### ISSUE THREAD

**Issue by mjnovice** [LeetCode-Feedback/LeetCode-Feedback#1815]
#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The multi threading judge doesn't seem to be working. The following code passes all cases, whereas in reality it shouldn't.
https://leetcode.com/problems/design-bounded-blocking-queue/discuss/956412/Why-is-it-still-working-when-release()-before-acquire()

**Comment by lc-kay** [comment]
Hi @mjnovice 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@mjnovice Thank you for your patience. Our team has reviewed the solution and the multithreaded judge and both is working as expected.
