### ISSUE TITLE
无法登录，必须用手机验证码，服了！

### ISSUE THREAD

**Issue by Tianzong** [LeetCode-Feedback/LeetCode-Feedback#18152]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

### LeetCode 用户名
Tianzong

### 问题号码、标题和链接
无语了，必须要用手机验证码登录？ 手机早就换了，绑定的微信登录不了。APP扫码登录不了。APP自己能登录但是换不了手机？ 想问这是何等的智商才能想出这种交互？
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/19348073/db2f3c5e-5cc2-4ca9-9f0e-da92d81ef642)

### Bug 类型
无法登录

你的 LeetCode 用户名
洪世贤

期望行为
怎么样才能登录？ 或者帮我把手机号换绑下？

**Comment by Nabiiiiiiiii** [comment]
您好，

感谢您的来信，经过和相关技术团队核实，登录提示「为了账号安全请用账号验证码登录」是平台为了用户账号安全，对登录的设备数量的限制。建议您在常用设备使用常用账号哦。根据您反馈的情况，如需要手机号解绑服务，我们需要验证当前帐号为您本人使用，请您提供以下信息至我们：
- 需要解绑的手机号：
- 绑定手机号对应的力扣账号：
- 常用登录地址：（省市）
- 常用登录设备系统：
- 常用登录浏览器：

在收到您的回复后，我们会提交至相关部门进行核实并进行后续操作。

Best Regards,
Leetcode | Support Team

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Comment by Tianzong** [comment]
需要解绑的手机号：13464599875
绑定手机号对应的力扣账号：blcutys
常用登录地址：（省市）北京市
常用登录设备系统：大部分是mac，有时候是win
常用登录浏览器：chrome

**Comment by Tianzong** [comment]
账号中文名： 洪世贤。 
希望  尽快帮忙解绑，我等着跳槽刷题

**Comment by Tianzong** [comment]
> 您好，
> 
> 感谢您的来信，经过和相关技术团队核实，登录提示「为了账号安全请用账号验证码登录」是平台为了用户账号安全，对登录的设备数量的限制。建议您在常用设备使用常用账号哦。根据您反馈的情况，如需要手机号解绑服务，我们需要验证当前帐号为您本人使用，请您提供以下信息至我们：
> 
> * 需要解绑的手机号：
> * 绑定手机号对应的力扣账号：
> * 常用登录地址：（省市）
> * 常用登录设备系统：
> * 常用登录浏览器：
> 
> 在收到您的回复后，我们会提交至相关部门进行核实并进行后续操作。
> 
> Best Regards, Leetcode | Support Team

需要解绑的手机号：13464599875
绑定手机号对应的力扣账号：blcutys
常用登录地址：（省市）北京市
常用登录设备系统：大部分是mac，有时候是win
常用登录浏览器：chrome

账号中文名： 洪世贤。
希望 尽快帮忙解绑，我等着跳槽刷题

**Comment by Greedfeast** [comment]
> 您好，
> 
> 感谢您的来信，经过和相关技术团队核实，登录提示「为了账号安全请用账号验证码登录」是平台为了用户账号安全，对登录的设备数量的限制。建议您在常用设备使用常用账号哦。根据您反馈的情况，如需要手机号解绑服务，我们需要验证当前帐号为您本人使用，请您提供以下信息至我们：
> 
> * 需要解绑的手机号：
> * 绑定手机号对应的力扣账号：
> * 常用登录地址：（省市）
> * 常用登录设备系统：
> * 常用登录浏览器：
> 
> 在收到您的回复后，我们会提交至相关部门进行核实并进行后续操作。
> 
> Best Regards, Leetcode | Support Team

您好 我也需要解绑手机号，之前的手机号已经不用了，现在提示需要验证码登录，无法登录。
> 
> * 需要解绑的手机号：18570771551
> * 绑定手机号对应的力扣账号：oandahouse
> * 常用登录地址：（省市）北京市
> * 常用登录设备系统：Windows
> * 常用登录浏览器：chrome
辛苦尽快处理，感谢

**Comment by Erio-Harrison** [comment]
遇到了同样的问题

**Comment by Nuygnix** [comment]
@Nabiiiiiiiii 
您好，我也需要换绑手机号：
力扣账号名称不记得了，微信和QQ应该都没绑定，
常用邮箱：[3319296010@qq.com](mailto:3319296010@qq.com)
常用登录地址：江西赣州、江苏苏州、浙江杭州
需要解绑的手机号：17870580515
常用登录设备系统：windows10
常用登录浏览器：edge
需要绑定的手机号：15225389024，手机号可能注册了其他账号，必要时可以删除该账号

**Comment by luoxianxu** [comment]
@Nabiiiiiiiii 
需要解绑的手机号：15080710812
绑定手机号对应的力扣账号：我想
常用登录地址：（省市）湖南娄底、湖南益阳
常用登录设备系统：win10
常用登录浏览器：edge/chrome
需要绑定的手机号：15576322859

**Comment by dulingkang** [comment]
帐号名： dulingkang@163.com
常用邮箱：[dulingkang@163.com](mailto:dulingkang@163.com)
常用登录地址：浙江杭州、浙江嘉兴
需要解绑的手机号：15658826683，已停机
常用登录设备系统：mac，ubuntu
常用登录浏览器：chrome
需要绑定的手机号：19186116894

**Comment by dulingkang** [comment]
需要解绑的手机号：15658826683
绑定手机号对应的力扣账号：poptrack
常用登录地址：浙江杭州、浙江嘉兴
常用登录设备系统：mac、ubuntu
常用登录浏览器：chrome
需要绑定的手机号：19186116894

**Comment by moon-ic** [comment]
@Nabiiiiiiiii 
需要解绑的手机号：19723825817
绑定手机号对应的力扣账号：桉陈
常用登录地址：（省市）重庆
常用登录设备系统：win11
常用登录浏览器：edge/chrome
需要绑定的手机号：18384146708

**Comment by moon-ic** [comment]
@Nabiiiiiiiii
需要解绑的手机号：19723825817
绑定手机号对应的力扣账号：moon-ic
常用登录地址：（省市）重庆
常用登录设备系统：win11
常用登录浏览器：edge/chrome
需要绑定的手机号：18384146708

**Comment by ChunlaiPeng** [comment]
需要解绑的手机号：08084447925
绑定手机号对应的力扣账号：chunlai
常用登录地址：日本东京
常用登录设备系统：大部分是mac，有时候是win
常用登录浏览器：chrome

**Comment by Djw-code** [comment]
您好，我也需要换绑手机号：
力扣账号名称不记得了
常用邮箱：djwahyx@163.com
常用登录地址：江苏苏州、四川成都
需要解绑的手机号：18742519216
常用登录设备系统：windows11
常用登录浏览器：edge
需要绑定的手机号：15982272191，手机号可能注册了其他账号，必要时可以删除该账号

**Comment by JinYi2000** [comment]
@Nabiiiiiiiii 您好，我也需要换绑手机号
需要解绑的手机号：17861079632
绑定手机号对应的力扣账号：好像是JinYi2000
常用登录地址：浙江省杭州市
常用登录设备系统：mac
常用登录浏览器：chrome
需要绑定的手机号：17602174985，手机号可能注册了其他账号，必要时可以删除该账号

**Comment by embersax** [comment]
@Nabiiiiiiiii 您好，我也需要换绑手机号
需要解绑的手机号：13269056977
绑定手机号对应的力扣账号：不记得了
常用登录地址：美国
微信id：ZRL_Eliot
常用登录设备系统：mac
常用登录浏览器：chrome
需要绑定的手机号：+1 224420 1709

**Comment by renyuanzhe** [comment]
@Nabiiiiiiiii 您好，我也需要换绑手机号
需要解绑的手机号：19825403308
绑定手机号对应的力扣昵称：Claymore
常用登录地址：南京
常用登录设备系统：win10 edge
需要绑定的手机号：13182869098

**Comment by YanboTong0226** [comment]
@Nabiiiiiiiii 您好 我也需要换绑手机号
常用邮箱：yanbotong666@gmail.com
绑定手机号对应的力扣账号：YanboTong
常用登陆地址：美国 湖北省武汉市
旧手机号：18086473550
常用登录设备系统：windows
常用登录浏览器：firefox chrome
需要绑定的手机号：+1 7166223866

**Comment by DQ344** [comment]
> * 需要解绑的手机号：17265644469
> * 绑定手机号对应的力扣账号：亦云
> * 常用登录地址：（省市）重庆（如果检测到洛杉矶或者香港应该是用的机场）
> * 常用登录设备系统：iPhone，window，M11
> * 常用登录浏览器：chrome
> * 需要绑定的手机号：13212321956

**Comment by TerkyTerky** [comment]
需要解绑的手机号：15601582278
常用邮箱：terky1019@163.com
绑定手机号对应的力扣账号：wuliKunKun
常用登录地址：（省市）南京，上海
常用登录设备系统：windows，macos
常用登录浏览器：chrome
需要绑定的手机号：18761887368

**Comment by CrazyCoding-byte** [comment]
@Nabiiiiiiiii 您好 我也需要换绑手机号
账户昵称:yzx
需要解绑的手机号：19209244492
常用邮箱：944166810@qq.com(最近绑定的)
常用登录地址：（省市）湖南长沙/湖南怀化
常用登录设备系统：windows
常用登录浏览器：edge
需要绑定的手机号：18943424074

**Comment by migeai** [comment]
@Nabiiiiiiiii 您好 我也需要换绑手机号
常用邮箱：zzj.gole@gmail.com
绑定手机号对应的力扣账号：忘记
常用登陆地址：日本 江苏省南京市
旧手机号：15651800519
常用登录设备系统：windows
常用登录浏览器：edge chrome
需要绑定的手机号：+86 13607619707
备注：该手机号可能绑定其他账号，该账号可停用删除

**Comment by yogurt-shadow** [comment]
@Nabiiiiiiiii 您好我也要换绑手机号
邮箱：wangzhonghan99@163.com
解绑手机号：17602273083
leetcode账号：yogurt-shadow
新手机号：19224431213
常用浏览器： edge
常用地址： 北京 大连
常用设备系统： windows

**Comment by chenwei9712** [comment]
需要解绑的手机号：19115601649
绑定手机号对应的力扣账号：[1278528424@qq.com](mailto:1278528424@qq.com)
常用登录地址：（省市）重庆市
常用登录设备系统：win
常用登录浏览器：chrome
需要绑定的手机号：+86 17398417940
备注：该手机号可能绑定其他账号，该账号可停用删除

**Comment by yeamu** [comment]
需要解绑的手机号：+1 9412703289
github登录 github账号：yeamu
常用登录地址：浙江省杭州市
常用登录设备系统：windows
常用登录浏览器：chrome
需要绑定的手机号：+1 6469205820
备注：该手机号可能绑定其他账号，该账号可停用删除
