### ISSUE TITLE
Missing Test Case - 2940. Find Building Where Alice and Bob Can Meet

### ISSUE THREAD

**Issue by CuteTN** [LeetCode-Feedback/LeetCode-Feedback#18162]
### LeetCode Username
CuteTN

### Problem number, title, and link
2940. Find Building Where Alice and Bob Can Meet https://leetcode.com/problems/find-building-where-alice-and-bob-can-meet

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [x] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
The testcases OR the runtime restriction for GO language was too lenient that even a brute force solution can get accepted, which is definitely not worth a hard problem! The code is provided below.

### Language used for code
GO

### Code used for Submit/Run operation
This code was submitted by ParasPandya during the [Weekly Contest 372](https://leetcode.com/contest/weekly-contest-372)

```go
func leftmostBuildingQueries(heights []int, queries [][]int) []int {
    answer := make([]int, 0)
    for i := range queries {
        sort.Ints(queries[i])
        a, b := queries[i][0], queries[i][1]
        if a == b {
            answer = append(answer, b)
        } else if heights[a] < heights[b] {
            answer = append(answer, b)
        } else {
            building := -1
            for j := b; j < len(heights); j++ {
                if heights[a] < heights[j] && heights[b] < heights[j] {
                    building = j
                    break
                }
            }
            answer = append(answer, building)
        }
    }
    return answer
}
```

### Expected behavior
I have tried running the code above in its worst case, generated by this JavaScript code:
```js
let n = 5e4;
let q = 5e4;
let heights = Array(n).fill();
// Most of the elements are in decreasing order
for (let i = 0; i < n; i++) heights[i] = 1e5 - i;
// This is to avoid magic conditions
heights[n - 2] = 1e5 + 1;

let queries = Array(q).fill();
let l = 0;
let r = 1;

// Unique queries to avoid memoization
for (let i = 0; i < q; i++) {
  queries[i] = [l, r];
  l++;
  if (l == r) {
    l = 0;
    r++;
  }
}
```
But the code still passes the testcase. So I believe the problem constraints have to be tighter, OR the GO runtime must be stricter to avoid these entries.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

We can't add the test case currently because of technical issues.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
