### ISSUE TITLE
Broken Test Case - 236. Lowest Common Ancestor of a Binary Tree

### ISSUE THREAD

**Issue by themlkang** [LeetCode-Feedback/LeetCode-Feedback#18164]
### LeetCode Username
themlkang

### Problem number, title, and link
[236. Lowest Common Ancestor of a Binary Tree](https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
Test case throws `NumberFormatException` error even if the code is correct.

### Language used for code
Java

### Code used for Submit/Run operation
```
class Solution {
    class Result {
        TreeNode lca;
        boolean containsP;
        boolean containsQ;
        
        public Result(TreeNode lca, boolean containsP, boolean containsQ) {
            this.lca = lca;
            this.containsP = containsP;
            this.containsQ = containsQ;
        }
    }
    
    public TreeNode lowestCommonAncestor(TreeNode root, TreeNode p, TreeNode q) {
        Result result = calculateLowestCommonAncestor(root, p, q);
        return result.lca;
    }
    
    private Result calculateLowestCommonAncestor(TreeNode root, TreeNode p, TreeNode q) {
        if (root == null) {
            return new Result(null, false, false);
        }
        
        Result leftResult = calculateLowestCommonAncestor(root.left, p, q);
        Result rightResult = calculateLowestCommonAncestor(root.right, p, q);
        
        boolean containsP = leftResult.containsP || rightResult.containsP || root == p;
        boolean containsQ = leftResult.containsQ || rightResult.containsQ || root == q;
        TreeNode lca = null;
        if (leftResult.lca != null) lca = leftResult.lca;
        if (rightResult.lca != null) lca = rightResult.lca;
        if (lca == null && (containsP && containsQ)) lca = root;
        
        return new Result(lca, containsP, containsQ);
    }
}
```

### Expected behavior
Test should pass

### Screenshots
![Screen Shot 2023-11-19 at 4 35 48 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/1915730/d84a6ae2-4a4a-4bbd-b2ec-41c42c5ee3e4)

### Additional context
The parameters for the test case look to be mixed up.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
