### ISSUE TITLE
Missing Test Case - 435. Non-overlapping Intervals

### ISSUE THREAD

**Issue by miramirrormira** [LeetCode-Feedback/LeetCode-Feedback#18163]
### LeetCode Username
miracodeyo

### Problem number, title, and link
[435. Non-overlapping Intervals](https://leetcode.com/problems/non-overlapping-intervals/)

### Category of the bug
- [x ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug
Leetcode accepted code that is incorrect.

### Language used for code
Swift

### Code used for Submit/Run operation
```
class Solution {
    func eraseOverlapIntervals(_ intervals: [[Int]]) -> Int {
        if intervals.count < 3 {
            return 0
        }

        let sortedInterval = intervals.sorted { $0[1] < $1[1] }
        
        var previous = 0;
        var count = 1;

        //병합 하려면 뒤의 최소값이 전의 최대값보다 작다.
        for index in 1..<sortedInterval.count {
            if sortedInterval[index][0] >= sortedInterval[previous][1] {
                previous = index;
                count += 1
            }
        }
        return sortedInterval.count - count
    }
}
```

### Expected behavior
With input of [[1,2],[1,3]], we are expecting the algorithm to return 1, i.e. we must remove at least one interval to make the rest of the intervals non-overlapping. But the submitted and accepted code returns 0.

### Screenshots
<img width="1713" alt="Screenshot 2023-11-19 at 5 48 25 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/55816593/27e03d1e-d0a7-4a87-9940-a792ed2ba394">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
