### ISSUE TITLE
Missing Test Case - 2940. Find Building Where Alice and Bob Can Meet

### ISSUE THREAD

**Issue by gautamsw5** [LeetCode-Feedback/LeetCode-Feedback#18172]
### LeetCode Username

gautamsw5

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The solutions relying on finding next greater height till it is greater than both heights gets accepted, but it should get TLE.

### Language used for code

Java

### Code used for Submit/Run operation

```
class Solution {
    public int[] leftmostBuildingQueries(int[] heights, int[][] queries) {
        int[] nextGreater = nextGreater(heights.length, heights);
        // System.out.println(Arrays.toString(nextGreater));
        int[] ans = new int[queries.length];
        for (int i = 0; i < queries.length; i++) {
            Arrays.sort(queries[i]);
            if (heights[queries[i][1]] > heights[queries[i][0]] || queries[i][0] == queries[i][1]) {
                ans[i] = queries[i][1];
                continue;
            }
            int x = queries[i][1];
            while (nextGreater[x] != heights.length && (heights[x] <= heights[queries[i][0]] || heights[x] <= heights[queries[i][1]])) {
                x = nextGreater[x];
                // System.out.println(i+" "+x);
            }
            if (heights[x] > heights[queries[i][0]] && heights[x] > heights[queries[i][1]]) ans[i] = x;
            else ans[i] = -1;
        }
        return ans;
    }
    int[] nextGreater(int n, int arr[]) {
        int[] ans = new int[n];
        Arrays.fill(ans, n);
        Stack<Integer> stack = new Stack<>();
        for (int i = 0; i < n; i++) {
            if (stack.isEmpty()) {
                stack.push(i);
                continue;
            }
            while (!stack.isEmpty() && arr[i] > arr[stack.peek()]) {
                ans[stack.pop()] = i;
            }
            stack.push(i);
        }
        return ans;
    }
}
```

### Expected behavior
The code should get TLE

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/72446354/7959d9c6-094e-47c9-88e4-3c7e70b29b3f)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/72446354/ff801a90-59e1-4d79-a312-2aa68c29fd4f)

### Additional context

Test case used can be generated using below python script:
```
with open('tmp.txt','w'): pass
file = open('tmp.txt','w')
def print(x):
    x = str(x)
    file.write(x+"\n")

a = [10**9-1]
for i in range(1, 5*(10**4)):
    a.append(i)
a[-1] = 10**9
q = []
for i in range(5*(10**4)):
    q.append([0, 1])
print(a)
print(q)
file.close()
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

We can't add the test case currently because of technical issues.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
