### ISSUE TITLE
Faulty Test Case - 763. Partition Labels

### ISSUE THREAD

**Issue by StefanTobler** [LeetCode-Feedback/LeetCode-Feedback#1817]
#### Category of the bug
- [ X] Question
- [ X] Solution
- [ ] Language

#### Description of the bug

Solution code returns `[13,1,1]` for the test case `qiejxqfnqceocmy `.  I believe this is incorrect as the problem is to partition the string into as many parts as possible where each character only exists in one partition. This would result in the partitions `qiejxqfnqce`, `o`, `c`, `m`, and `y`. Thus the correct solution would be `[11, 1, 1, 1, 1]`.

#### Code you used for Submit/Run operation

```
# Partition Labels
class Solution:
    def partitionLabels(self, S: str) -> List[int]:
        partitions = []
        i = 0
        
        def check_interior(start, finish):
            furthest = finish
            for x in range(start, finish):
                position = S[::-1].index(S[x])
                position = len(S) - position
                if position > furthest:
                    furthest = position
            return furthest
        
        while i < len(S):
            j = S[::-1].index(S[i])
            j = len(S) - j
            j = check_interior(i+1, j)
            partitions.append(j-i)
            i = j
            
        return partitions
```

#### Language used for code

Python

#### Expected behavior

Solution code returns `[13,1,1]` for the test case `qiejxqfnqceocmy `.  I believe this is incorrect as the problem is to partition the string into as many parts as possible where each character only exists in one partition. This would result in the partitions `qiejxqfnqce`, `o`, `c`, `m`, and `y`. Thus the correct solution would be `[11, 1, 1, 1, 1]`.

#### Screenshots

![image](https://user-images.githubusercontent.com/22108632/103394582-63ff8600-4af7-11eb-97b9-bb82d6aa667b.png)

**Comment by StefanTobler** [comment]
I was reading this wrong, sorry.

**Comment by bboysteed** [comment]
i test it the same with u , i think it's a fault!!
