### ISSUE TITLE
blank and white balls contest question

### ISSUE THREAD

**Issue by adipreni** [LeetCode-Feedback/LeetCode-Feedback#18183]
### LeetCode Username

[adipreni](https://leetcode.com/adipreni)

### Problem number, title, and link

https://leetcode.com/contest/weekly-contest-372/problems/separate-black-and-white-balls/

### Category of the bug
- [ ] Problem description
- [x] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Per question from https://leetcode.com/contest/weekly-contest-372/problems/separate-black-and-white-balls/
Need to capture min steps required to move white balls to left.
I used the sort approach and was able to move it in 3 steps.
Upon submission of my answer, it failed the below test case:

Input: "11000111"
Output: 3
Expected: 6

### Language used for code

Java

### Code used for Submit/Run operation

```
class Solution {
    public long minimumSteps(String s) {
        String[] sList = s.split("");
        long steps = 0;
        for (int i = 0; i < s.length(); i++) {
            if (sList[i].equals("0")) {
                continue;
            }
            for (int j = i + 1; j < s.length(); j++) {
                if (sList[j].equals("0")) {
                    String tmp = sList[i];
                    sList[i] = sList[j];
                    sList[j] = tmp;
                    steps++;
                    break;
                }
            }
        }
        return steps;
    }
}
```

### Expected behavior

Expected output = 3, but evaluating to 6

### Additional context

Submitting my doubt here. Not sure if this is the correct way to report my observation.
Looking forward to your guidance.
Thanks.

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
