### ISSUE TITLE
Incorrect input testcase format for Question #236 - Lowest Common Ancestor of a Binary Tree

### ISSUE THREAD

**Issue by nikitha-reddy** [LeetCode-Feedback/LeetCode-Feedback#18184]
### LeetCode Username

[Prashant](https://leetcode.com/pg1029)

### Problem number, title, and link

1. [236. Lowest Common Ancestor of a Binary Tree](https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/) 

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

One of the testcases run during submission has an invalid input format. Incorrect input testcase format - 
4
[3,5,1,6,2,0,8,null,null,7,4]

Expected input test case format - 
[3,5,1,6,2,0,8,null,null,7,4]
5
4

### Language used for code

Java

### Code used for Submit/Run operation

```
class Solution {
    TreeNode lca = null;
    public TreeNode lowestCommonAncestor(TreeNode root, TreeNode p, TreeNode q) {
        isNodePresent(root, p, q);
        return lca;
    }

    private boolean isNodePresent(TreeNode root, TreeNode p, TreeNode q) {
        if (root == null)
            return false;

        boolean isNode = (root.val == p.val || root.val == q.val) ? true : false;
        boolean isLeft = isNodePresent(root.left, p, q);
        boolean isRight = isNodePresent(root.right, p, q);

        if ((isLeft && isRight) || (isNode && (isLeft || isRight))) {
            lca = root;
        }

        return isNode || isLeft || isRight;
    }
}
```

### Expected behavior

Test case input should have the format similar to this - 
[3,5,1,6,2,0,8,null,null,7,4]
5
4

### Screenshots

Note the input format in submission runtime error and the sample testcases
<img width="1487" alt="Screenshot 2023-11-21 at 12 17 56 AM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/15049697/1c4c1def-4e18-4f2f-92a2-590a8f1bea74">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
