### ISSUE TITLE
Missing Test Case - 189. Rotate Array

### ISSUE THREAD

**Issue by adam415** [LeetCode-Feedback/LeetCode-Feedback#18180]
### LeetCode Username

adam415

### Problem number, title, and link

189. Rotate Array https://leetcode.com/problems/rotate-array/

### Category of the bug
❌ Problem description
❌ Solved examples
⚠️ Problem constraints
❌ Problem hints
❌ Incorrect or missing "Related Topics"
❌ Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
✅ Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
❌ Editorial
❌ Programming language support

### Description of the bug

The problem description restricts `k` to `10^5` and doesn't restrict it to be `<= nums.size()`, but solutions failing on `k > nums.size()` pass the two test cases.

### Language used for code

C++

### Code used for Submit/Run operation

```
class Solution
{
public:
    void rotate(vector<int>& nums, const int k)
    {
        const int loops = gcd(nums.size(), k);
        const int nodes = nums.size() / loops;
        for (int start = 0; start < loops; start++)
        {
            const int old = nums[start];
            for (int curr = start; ; )
            {
                const int next = (curr - k + nums.size()) % nums.size();
                if (next != start)
                {
                    nums[curr] = nums[next];
                    curr = next;
                }
                else
                {
                    nums[curr] = old;
                    break;
                }
            }
        }
    }
};
```

### Expected behavior

I suggest adding another test case with `k > nums.size()` which will result in "Wrong Answer" instead of "Accepted" for such solutions.

### Screenshots

1. The first case:
<img width="1722" alt="Снимок экрана 2023-11-20 в 18 19 21" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/35181000/b652d84a-1d21-4bde-896e-0a8a2b46e7e4">
2. The second case:
<img width="1725" alt="Снимок экрана 2023-11-20 в 18 19 33" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/35181000/a576f06c-9b14-411d-b2be-c11258d6a05c">
4. A new case added by me:
<img width="1725" alt="Снимок экрана 2023-11-20 в 18 20 14" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/35181000/48618e0e-3745-4576-b9f9-af3e399ec217">

### Additional context

Test case proposal:
`nums = [1,2,3,4,5,6,7]; k = 30`

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team

**Comment by adam415** [comment]
@LC-Pam 
Thank you for giving a feedback!
But it seems to me like you have missed the point.

I wasn’t trying to say the solution above was correct. On the contrary, I mean that it is **wrong but passes** the two test cases provided in the system by default.

Please, see the first two screenshots above: those two test cases are in your checking system now, and they are marked as “Accepted”. But they both have `k < nums.size()`.

Then see the third screenshot with the “Wrong Answer” verdict — this third test case **is my custom one** and has `k >= nums.size()` which is allowed by the restrictions in the problem description **but not covered** with the previous cases provided by your system.

I am not suggesting that you accept the solution example, but **add the third test case** to the system so that it would cover such a corner case and **mark this solution as “Wrong Answer”**. (Now it’s falsely marked as “Accepted”, which, as you have noticed, is incorrect behavior).

I look forward to hearing from you.

Kind regards,
Adam
