### ISSUE TITLE
Incorrect Topic Classification for 2391. Minimum Amount of Time to Collect Garbage

### ISSUE THREAD

**Issue by rogersentongo** [LeetCode-Feedback/LeetCode-Feedback#18187]
### LeetCode Username

rntongoo

### Problem number, title, and link

[2391. Minimum Amount of Time to Collect Garbage](https://leetcode.com/problems/minimum-amount-of-time-to-collect-garbage/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [x] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Should be classified as Hashtable String and Prefixsum under the Topics tab but is currently classified as an Array String and Prefixsum problem

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

### Expected behavior

Should be classified as Hashtable String and Prefixsum under the Topics tab but is currently classified as an Array String and Prefixsum problem

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
