### ISSUE TITLE
Missing Test Case - 1934. Confirmation Rate

### ISSUE THREAD

**Issue by Abdalrhman-Mohammad** [LeetCode-Feedback/LeetCode-Feedback#18185]
### LeetCode Username

AbdalrhmanALMohammad

### Problem number, title, and link

1934. Confirmation Rate 
https://leetcode.com/problems/confirmation-rate/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [X] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Some codes get accepted in the problem , but it is take wrong on some cases not exist in the test cases.

### Language used for code

MySQL

### Code used for Submit/Run operation

```

SELECT s.user_id,
CASE WHEN c.time_stamp IS NULL THEN 0.00 ELSE ROUND(SUM(action='confirmed')/count(action),2) END AS confirmation_rate
FROM Signups s
LEFT JOIN Confirmations c
ON c.user_id=s.user_id
GROUP BY s.user_id

```

### Expected behavior

The code that I put it must got wrong on bellow test case ,But when i submit the code it is took Accepted.

Signups =
| user_id | time_stamp          |
| ------- | ------------------- |
| 3       | 2020-03-21 10:16:13 |
| 7       | 2020-01-04 13:57:59 |
| 2       | 2020-07-29 23:09:44 |
| 6       | 2020-12-09 10:39:37 |

Confirmations =
| user_id | time_stamp | action    |
| ------- | ---------- | --------- |
| 3       | null       | timeout   |
| 7       | null       | confirmed |
| 2       | null       | confirmed |

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/118562424/a476dd0b-feea-4617-b321-d470f6101751)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
