### ISSUE TITLE
Missing Test Case - 260. Single Number III

### ISSUE THREAD

**Issue by HenryVVan** [LeetCode-Feedback/LeetCode-Feedback#18188]
### LeetCode Username

[henry_v](https://leetcode.cn/u/henry_v/)

### Problem number, title, and link

[260. Single Number III] (https://leetcode.cn/problems/single-number-iii)

### Category of the bug
- Missing test Case 

### Description of the bug

Use the case below can be wrong, but the system without the case </br>
`[7,1,7,2,6,6,3,1]`

### Language used for code

`Java8`

### Code used for Submit/Run operation

```
class Solution {
    public int[] singleNumber(int[] sockets) {
        int sum = 0;
        for (int i = 0; i < sockets.length; i++) {
            sum ^= sockets[i];
        }
        int k = -1;
        // 两数不等，必有一位不同，然后单独取满足那一位的数过来求^
        for (int i = 31; i > 0 && k == -1; i--) {
            if ((1 << i & sum) != 0) {
                k = i;
            }
        }
        int a = 0, b = 0;
        for (int i = 0; i < sockets.length; i++) {
            if ((1 << k & sockets[i]) != 0) a ^= sockets[i];
            else b ^= sockets[i];
        }
        return new int[]{a, b};
    }
}
```

### Expected behavior

`[3,2]` </br>
but with `[0,1]`

### Screenshots

- WRONG CASE
![image-20231121114858072](https://img2023.cnblogs.com/blog/3313059/202311/3313059-20231121114858427-2144886636.png)
- BUT PASS
![image-20231121115229616](https://img2023.cnblogs.com/blog/3313059/202311/3313059-20231121115229799-1356821425.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
