### ISSUE TITLE
Missing Test Case - 10. Regular Expression Matching

### ISSUE THREAD

**Issue by barsbold-coding** [LeetCode-Feedback/LeetCode-Feedback#18182]
### LeetCode Username
barsbold.coding

### Problem number, title, and link
10. (Regular Expression)[https://leetcode.com/problems/regular-expression-matching/]

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [x] Programming language support

### Description of the bug

solved problem. it matches the tests. but interpreter cannot run my code properly.

### Language used for code

C lang

### Code used for Submit/Run operation

```
bool isMatch(char* s, char* p) {
  unsigned int s_len = strlen(s), p_len = strlen(p);

  int dp[s_len + 1][p_len + 1];
  memset(dp, 0, sizeof(int) * s_len * p_len);
  dp[0][0] = true;

  for (int i = 0; i <= s_len; ++i) {
    for (int j = 1; j <= p_len; ++j) {
      if (i && (s[i - 1] == p[j - 1] || p[j - 1]=='.'))
        dp[i][j] = dp[i - 1][j - 1];
      else if (p[j - 1] == '*')
        dp[i][j] = dp[i][j-2] || (i && dp[i-1][j] && (p[j-2]=='.' || s[i-1]==p[j-2]));
    }
  }

  return dp[s_len][p_len];
}
```

### Expected behavior

It should return false on `s = "aa", p = "a"` test.

### Screenshots

<img width="763" alt="Screenshot 2023-11-21 at 12 30 25 AM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/113093171/f0d49ffa-2c96-44cb-845e-d39929d17f22">

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
