### ISSUE TITLE
Mistakes in Editorial - 188. Best Time to Buy and Sell Stock IV

### ISSUE THREAD

**Issue by Ming91** [LeetCode-Feedback/LeetCode-Feedback#18189]
### LeetCode Username

[wming9310](https://leetcode.com/wming9310)

### Problem number, title, and link

[188. Best Time to Buy and Sell Stock IV](https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iv/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug

In this editorial solution, we discussed the case where `k / 2 > n`. However, this should be `k * 2 >= n`. For `k` transactions we need `2 * k` points as start or end. So if `k * 2 >= n`, we can use any pair of points as a transaction. Then we can use `ans += max(0, prices[i] - prices[i - 1]` to get the answer for this case.

We can also find users in the discussion using the condition `k * 2 >= n` rather than `k / 2 > n`.

### Language used for code

Java

### Code used for Submit/Run operation

```Java
class Solution {
    public int maxProfit(int k, int[] prices) {
        int n = prices.length;
        if (k * 2 > n) {
            int ans = 0;
            for (int i = 1; i < n; i++) {
                ans += Math.max(0, prices[i] - prices[i - 1]);
            }
            return ans;
        }
        int[] cost = new int[k];
        int[] profit = new int[k];
        Arrays.fill(cost, Integer.MAX_VALUE);
        for (int price : prices) {
            cost[0] = Math.min(cost[0], price);
            profit[0] = Math.max(profit[0], price - cost[0]);
            for (int i = 1; i < k; i++) {
                cost[i] = Math.min(cost[i], price - profit[i - 1]);
                profit[i] = Math.max(profit[i], price - cost[i]);
            }
        }
        return profit[k - 1];
    }
}
```

### Screenshots

Editorial mistake:
![Screenshot 2023-11-20 233659](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/3740139/dd5b0d79-a49f-40ed-b242-c5033af605bf)

Users related discussions:
![Screenshot 2023-11-20 233721](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/3740139/ebf64a31-dca9-4057-819c-2baa7613d8af)
![Screenshot 2023-11-20 233754](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/3740139/eb09e81e-a137-41f1-992a-8892046148ba)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've used your feedback to update the problem.

Your LeetCode account will receive 100 LeetCoins as a reward for this feedback.

Please provide us your Leetcode Username .

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Comment by Ming91** [comment]
Sorry, I changed the username last week and didn't notice this message.
The new username is [Ming_91](https://leetcode.com/Ming_91).
