### ISSUE TITLE
Missing Test Case - 1280. Students and Examinations

### ISSUE THREAD

**Issue by Abdalrhman-Mohammad** [LeetCode-Feedback/LeetCode-Feedback#18194]
### LeetCode Username

AbdalrhmanMohammad

### Problem number, title, and link

1280. Students and Examinations
https://leetcode.com/problems/students-and-examinations/description/?envType=study-plan-v2&envId=top-sql-50

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [X] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Some codes get accepted in the problem , but it is take wrong on some cases not exist in the test cases.

### Language used for code

MySQL

### Code used for Submit/Run operation

```


SELECT st.student_id , st.student_name ,subject_name , (
    SELECT COUNT(e.subject_name) 
    FROM Examinations AS e 
    WHERE e.student_id=st.student_id and e.subject_name=su.subject_name
    ) AS attended_exams
FROM Students AS st , Subjects AS su
WHERE st.student_name IS NOT NULL
ORDER BY student_id ASC ,subject_name ASC;

```

### Expected behavior

The code that I put it must got wrong on bellow test case ,But when i submit the code it is took Accepted.

Students =

| student_id | student_name |
| ---------- | ------------ |
| 1          | null        |
| 2          | Bob          |
| 13         | John         |
| 6          | Alex         |

Subjects =
| subject_name |
| ------------ |
| Math         |
| Physics      |
| Programming  |

Examinations =

| student_id | subject_name |
| ---------- | ------------ |
| 1          | Math         |
| 1          | Physics      |
| 1          | Programming  |
| 2          | Programming  |
| 1          | Physics      |
| 1          | Math         |
| 13         | Math         |
| 13         | Programming  |
| 13         | Physics      |
| 2          | Math         |
| 1          | Math         |

### Screenshots

![1280  Students and Examinations](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/118562424/c4896947-4ed9-4637-b4c2-4fe9e2c96cce)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
