### ISSUE TITLE
32. 最长有效括号 测试用例 80 答案有问题吧

### ISSUE THREAD

**Issue by soul-sys** [LeetCode-Feedback/LeetCode-Feedback#1819]
** Bug 类型**
- [32 ] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
描述你遇到的 bug

示例 1:

输入: "(()"
输出: 2
解释: 最长有效括号子串为 "()"

这个是示例给的例子，说是有两个

输入：
"()(()"
输出：
4
预期：
2

这是 80 / 231测试用例，我就奇怪了，前面加的是空气？？？？

**你使用的语言**
Java

**你提交或者运行的代码**
```
// Two Sum
public int longestValidParentheses(String s) {
        char[] char1 = s.toCharArray();
		
		int count = 0;
		
		for(int i = 0; i < char1.length - 1; i++) {
			if(char1[i] == '(') {
				for(int j = i +1; j < char1.length; j++) {
					if(char1[j] == ')') {
						count += 2;
						char1[j] = '-';
                        break;
					}
				}
			} else {
				continue;
			}
		}
		
		return count;
    }
```

**期望行为**
描述你期望的结果

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by stormsunshine** [comment]
麻烦看清楚题目，要求是子串，必须是连续的，对于 `"()(()"` 这个例子，如何得到长度为 4 的（连续）子串是有效括号？

**Comment by feiceh** [comment]
感谢反馈，题面已经更新了，找出最长有效（格式正确且连续）括号子串的长度。
