### ISSUE TITLE
Wrong/Insufficient proof of the cut property for MST in the Explore Graph course

### ISSUE THREAD

**Issue by charlesxin97** [LeetCode-Feedback/LeetCode-Feedback#18191]
### LeetCode Username

[charlesxin](https://leetcode.com/charlesxin)

### Problem number, title, and link

https://leetcode.com/explore/learn/card/graph/621/algorithms-to-construct-minimum-spanning-tree/3855/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The video that proves the cut property of the MST gives an example of two subsets with the assumption that each of them is connected by its own. This might not be the case. A proof that makes more sense is to add the edge with minimum weight and form a cycle, then we can construct a MST with less weight.

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

What you are objecting to is not the same concept as what you are explaining later:

The video that proves the cut property of the MST gives an example of two subsets with the assumption that each of them is connected on its own. This might not be the case.

There is no problem with this assumption, which is necessary to begin proving the cut property. Please refer to the definition of a cut.
‌
A proof that makes more sense is to add the edge with minimum weight and form a cycle, then we can construct an MST with less weight.

The argumentation process mentioned in the video is not fundamentally different from what you describe: if we restore two (or more) edges of a cut, they would form a cycle, so we have to keep only the smallest one that belongs. The author's order of argumentation is not the most standard, but it is comprehensive and correct. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
