### ISSUE TITLE
Missing Test Case - 41. First Missing Positive

### ISSUE THREAD

**Issue by Abhishek91102** [LeetCode-Feedback/LeetCode-Feedback#18196]
Input: 
nums = [-1,11,31,2,3,2,8,9]
Output: 1
Explanation: The starting number 1 is not present in the array.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link you submitted to reach this result.


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Abhishek91102** [comment]
Thank you for your response.
