### ISSUE TITLE
Insufficient description regarding what defines 'correct IP address'

### ISSUE THREAD

**Issue by YashJipkate** [LeetCode-Feedback/LeetCode-Feedback#182]
**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
The question [Restore IP adresses](https://leetcode.com/problems/restore-ip-addresses/) does not define what is defined as a correct IP address. Many of us are not from CS background and hence have little knowledge about networking.

**what language is your code written in**
C++

**Expected behavior**
Clear and sufficient definition must be provided as to what is meant by a valid IP address.

**Comment by CooperCooperCooper** [comment]
Hi @YashJipkate,
Thank you for reaching out to us! I've relayed this feedback to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @YashJipkate,
Thank you for your time. We've updated the problem according to your feedback. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user account verification, and link to this issue to claim your reward for valid contribution.
