### ISSUE TITLE
Missing Test Case - 620. Not Boring Movies

### ISSUE THREAD

**Issue by aamirafzal0007** [LeetCode-Feedback/LeetCode-Feedback#18201]
### LeetCode Username

aamirbinafzal1618

| id | movie      | description | rating |
| -- | ---------- | ----------- | ------ |
| 1  | War        | great 3D    | 8.9    |
| 2  | Science    | fiction     | 8.5    |
| 3  | irish      | boring hoon | 6.2    |
| 4  | Ice song   | Fantacy     | 8.6    |
| 5  | House card | Interesting | 9.1    |

### Problem number, title, and link

[620. Not Boring Movies](https://leetcode.com/problems/not-boring-movies/)
[Missing Test Case]

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ .] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

This type of test case gives description of the movie anything with the keyword boring . So logically if the movie is boring,It shouldnt be there in expected output. But the result shows it in the expected output.

### Language used for code

Oracle

### Code used for Submit/Run operation

```
select * from Cinema where mod(id,2)<>0 and description not like '%boring%' order by rating desc;
```

### Expected behavior

The Query should have selected every row except  those which contains  "BORING" word along with anything in their description. Instead it is selecting the rows which have not just a single word "boring" in the description.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
