### ISSUE TITLE
[无法使用Github登录]为了保证账号安全，本次请使用手机验证码登录

### ISSUE THREAD

**Issue by yinuotxie** [LeetCode-Feedback/LeetCode-Feedback#18208]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

### LeetCode 用户名
略略略大帅哥

### 问题号码、标题和链接
第三方社交平台登录失败
发生了一些问题，导致了通过社交账号登录失败

🐸☕为了保证账号安全，本次请使用手机验证码登录。如果重复仍出现该错误，请将错误报告给客服。

### 描述
无法使用GitHub登录，显示要使用手机验证登录，但是没有绑定手机。

### 期望行为
绑定手机，帮助登录。

### 屏幕截图
<img width="1188" alt="Screenshot 2023-11-21 at 6 53 14 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/61256373/542e6f6f-a5c8-43bc-a0d2-23b48ad7920a">

**Comment by Nabiiiiiiiii** [comment]
您好，

感谢您的来信，经过和相关技术团队核实，登录提示「为了账号安全请用账号验证码登录」是平台为了用户账号安全，对登录的设备数量的限制。建议您在常用设备使用常用账号哦。根据您反馈的情况，如需要手机号解绑服务，我们需要验证当前帐号为您本人使用，请您提供以下信息至我们：

需要解绑的手机号：
绑定手机号对应的力扣账号：
常用登录地址：（省市）
常用登录设备系统：
常用登录浏览器：
在收到您的回复后，我们会提交至相关部门进行核实并进行后续操作。

Best Regards,
Leetcode | Support Team

**Comment by chenwei9712** [comment]
> 您好，
> 
> 感谢您的来信，经过和相关技术团队核实，登录提示「为了账号安全请用账号验证码登录」是平台为了用户账号安全，对登录的设备数量的限制。建议您在常用设备使用常用账号哦。根据您反馈的情况，如需要手机号解绑服务，我们需要验证当前帐号为您本人使用，请您提供以下信息至我们：
> 
> 需要解绑的手机号： 绑定手机号对应的力扣账号： 常用登录地址：（省市） 常用登录设备系统： 常用登录浏览器： 在收到您的回复后，我们会提交至相关部门进行核实并进行后续操作。
> 
> Best Regards, Leetcode | Support Team

您好，我也需要换绑手机号：
账户：[1278528424@qq.com](mailto:1278528424@qq.com)
原来手机号：17844629605
需要绑定的手机号：19115601649，手机号可能注册了其他账号，必要时可以删除该账号
