### ISSUE TITLE
Missing Test Case - 969. Pancake Sorting

### ISSUE THREAD

**Issue by nsk-robo** [LeetCode-Feedback/LeetCode-Feedback#1820]
#### Your LeetCode username

senthilkumar_n

#### Category of the bug
- [ ] Question

#### Description of the bug

In Example 1 , the output should be Output: [1,2,4,3]. but it is mentioned as Output: [4,2,4,3]

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by stormsunshine** [comment]
Why should the output be [1,2,4,3]? The output [4,2,4,3] is correct according to the explanation.
Suppose the output is [1,2,4,3]. The process is as follows.
Starting state: arr = [3, 2, 4, 1]
After 1st flip (k = 1): arr = [3, 2, 4, 1]
After 2nd flip (k = 2): arr = [2, 3, 4, 1]
After 3rd flip (k = 4): arr = [1, 4, 3, 2]
After 4th flip (k = 3): arr = [3, 4, 1, 2]
Is this a sorted array? Of course not!

**Comment by lc-kay** [comment]
@nsk-robo Thanks for reaching out! The expected output is correct, please refer to @stormsunshine explanation or the discuss tab of this problem.
