### ISSUE TITLE
Explore Card: Search in a BST - Solution: incorrect language tab name

### ISSUE THREAD

**Issue by TOKocsis** [LeetCode-Feedback/LeetCode-Feedback#18206]
### LeetCode Username
peddy91

### Problem number, title, and link

https://leetcode.com/explore/learn/card/introduction-to-data-structure-binary-search-tree/141/basic-operations-in-a-bst/1022/

### Category of the bug
- [ ] Editorial

### Description of the bug

The solution window programing language tabs says C++ and Java, but the C++ tab shows Python code (root.val instead of root->val).
So the C++ tab name shall be changed to Python, in both cases (2 solutions windows).

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've used your feedback to check the problem.

We redirected it to our backend team but it will take time to fix.

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!
