### ISSUE TITLE
Description typo - 616. Add Bold Tag in String

### ISSUE THREAD

**Issue by xelplogoog** [LeetCode-Feedback/LeetCode-Feedback#18216]
### LeetCode Username
c4tdog

### Problem number, title, and link
https://leetcode.com/problems/add-bold-tag-in-string/description/

### Category of the bug
- [ ] Problem description

### Description of the bug
There is a typo in word `consecutive`

<img width="419" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2188302/67f7749b-91d1-4565-b4d2-be62df2671f2">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
