### ISSUE TITLE
Missing Test Case - 2771. Longest Non-decreasing Subarray From Two Arrays

### ISSUE THREAD

**Issue by vlad9i22** [LeetCode-Feedback/LeetCode-Feedback#18217]
### LeetCode Username

vlad9i2

### Problem number, title, and link

2771. Longest Non-decreasing Subarray From Two Arrays https://leetcode.com/problems/longest-non-decreasing-subarray-from-two-arrays/

### Category of the bug
-   Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

The solution is accepted, when it shouldn't, because it is O(n^2) solution.

### Language used for code

C++

### Code used for Submit/Run operation

```
class Solution {
public:
    int maxNonDecreasingLength(vector<int>& nums1, vector<int>& nums2) {
        vector<int> nums3(nums1.size(), 0);
        int last = 0, lastInd = -1, back = 0, ans = 1;
        for(int i = 0; i < nums1.size(); ++i){
            int mn = min(nums1[i], nums2[i]), mx = max(nums1[i], nums2[i]);
            if(mn >= last) { nums3[i] = mn; }
            else if(mx >= last) { 
                nums3[i] = mx;
                if(lastInd == -1) lastInd = i;
            }
            else { nums3[i] = mn; }
                                
            //check for break of the non-decreasing order
            if(mx < last) { 
                if(lastInd != -1) { i = lastInd - 1;  lastInd = -1; }
                else i--;
                last = 0;  back = i+1;
            }
            else {  last = nums3[i];   ans = max(ans, i - back  + 1); }
        }
        return ans;
    }
};
```

### Expected behavior

This code is exptected to give Time Limit on the following test:
nums1: https://github.com/vlad9i22/leetcode-testcases/blob/main/nums1_2771_1
nums2: https://github.com/vlad9i22/leetcode-testcases/blob/main/nums2_2771_1

### Additional context

But it seems that there's no such testcase. When you add this Testcases yourself it gives Time Limit.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by vlad9i22** [comment]
@LC-Pam But there's still the same issue on the website. Will it be actually updated?
