### ISSUE TITLE
Solution typo - 2665. Counter II

### ISSUE THREAD

**Issue by nishantmendiratta** [LeetCode-Feedback/LeetCode-Feedback#18218]
### LeetCode Username
[thatjsdev](https://leetcode.com/thatjsdev/)

### Problem number, title, and link
 **2665**. Counter II https://leetcode.com/problems/counter-ii

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug
There is a typo in the following line of editorial. Please see the screenshot for more. 
> Throw an error if a an attempt was made to write to a readonly value.

### Expected behavior
Throw an error if an attempt was made to write to a read-only value.

### Screenshots
<img width="751" alt="Screenshot 2023-11-22 at 6 08 41 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2558220/bf52c612-a653-4237-8a73-57c9b2750662">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by nishantmendiratta** [comment]
Received thanks <3
