### ISSUE TITLE
Incorrect Description 1424 : diagonal-traverse-ii

### ISSUE THREAD

**Issue by aravindravva** [LeetCode-Feedback/LeetCode-Feedback#18210]
### LeetCode Username
https://leetcode.com/aravind_ravva/

### Problem number, title, and link

[1424. Diagonal Traverse II](https://leetcode.com/problems/diagonal-traverse-ii/)

### Category of the bug
- [X] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [X] Editorial
- [ ] Programming language support

### Description of the bug

Given a 2D integer array nums, return all elements of nums in diagonal order as shown in the below images.
In the Constraints they gave 
1 <= nums.length <= 10^5
1 <= nums[i].length <= 10^5

it something getting understand like 
1 <= nums.length <= 10^5 means max 10^5 rows
1 <= nums[i].length <= 10^5 means max 10^5 values per row

and with the logic we are going over all the elements atleast once
if we say row as M and col as N the M*N. Time Complexity : O(M*N)

But in the editorial they gave
Given n as the number of integers in grid,

Time complexity: O(n)

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

### Expected behavior
Need to mention clearly that the elements is less than 10^5

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

Please note that the given 2D array is not a regular one, so the number of elements it contains may not necessarily be M*N. Therefore, the time complexity is not necessarily O(M*N). Instead, using the total number of elements N is very direct and accurate, with no issues.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
