### ISSUE TITLE
输出能否区分case1 case2 case3

### ISSUE THREAD

**Issue by RealGUOL** [LeetCode-Feedback/LeetCode-Feedback#18214]
如下图所示，现在leetcode支持同时测试多个case。
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/55938580/739da5f6-20d0-49ab-8446-bc0e72a93bfa)
但是对于多个case的输出，却没有做区分，导致老用户（leetcode支持同时测试多个case功能之前的老用户）会惯性的把输出理解成一个case输出的，认知错误，一直debug很久找不到原因，认为是leetcode平台有问题。
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/55938580/bd81c0a0-b41b-46e4-a38f-03134b933585)

所以希望能输出能区分不同的case

**Comment by amcones** [comment]
您好，在与相关团队核实后：***不处理***（可以通过在程序运行结束时输出空行或分隔符等方式来标志一组样例的结束）。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
