### ISSUE TITLE
Issue regarding LeetCoins

### ISSUE THREAD

**Issue by akshatmaheshwar** [LeetCode-Feedback/LeetCode-Feedback#18211]
> Hi there,
> 
> Thank you for reaching out to us.
> 
>  We've relayed this issue to our team to investigate. 
> 
> We will reach back to you after we have the results.
> 
> For the feedback https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/16995#issuecomment-1761800956, we already issued the Leetcoins, please check your Leetcoins detail carefully. The reward name is "github".
> 
> Thank you for your support.

_Originally posted by @LC-Pam in https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/18169#issuecomment-1819321295_

Kindly check the screen secording attached below.
[screen-capture (3).webm](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/77718425/76ceace1-17db-4e24-a228-578e14e6ea87)

**Comment by LC-Pam** [comment]
Re-issued
