### ISSUE TITLE
incorrect test case- 84. Largest Rectangle in Histogram

### ISSUE THREAD

**Issue by mohamed-gudle** [LeetCode-Feedback/LeetCode-Feedback#1822]
#### Your LeetCode username
](url)

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

the test case [2,3] with the expected answer of 4 is incorrect because it is gotten as area=2 by 2 and that is a square not a rectangle , the answer should  be 3 because area=3 by 1 is a rectangle .

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@mohamed-gudle Thanks for reaching out! The expected output is correct. A square is a special kind of rectangle that has all its sides equal in measurement.
