### ISSUE TITLE
Editorial Typo - 617. Merge Two Binary Trees

### ISSUE THREAD

**Issue by sevillal** [LeetCode-Feedback/LeetCode-Feedback#18220]
### LeetCode Username

[user1914a](https://leetcode.com/user1914a/)

### Problem number, title, and link

[617. Merge Two Binary Trees](https://leetcode.com/problems/merge-two-binary-trees/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug

There is a typo in the following line of editorial. Please see the screenshot for more.

> Each entry in the stack strores data in the

### Expected behavior

Each entry in the stack **stores** data in the

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/56176070/1acda607-2f25-40b1-993b-34615fe8ec24)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
