### ISSUE TITLE
Missing Test Case - 1740. Find Distance in a Binary Tree

### ISSUE THREAD

**Issue by zmmohibul** [LeetCode-Feedback/LeetCode-Feedback#18227]
### LeetCode Username

[zmmohib](https://leetcode.com/zmmohib)

### Problem number, title, and link

[1740. Find Distance in a Binary Tree](https://leetcode.com/problems/find-distance-in-a-binary-tree/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The code that I submitted was accepted. But when I tried running my code with a test case I created it shows my answer is wrong. My code fails that test case. I've added a screenshot of the test case below.

### Language used for code

C#

### Code used for Submit/Run operation

```
/**
 * Definition for a binary tree node.
 * public class TreeNode {
 *     public int val;
 *     public TreeNode left;
 *     public TreeNode right;
 *     public TreeNode(int val=0, TreeNode left=null, TreeNode right=null) {
 *         this.val = val;
 *         this.left = left;
 *         this.right = right;
 *     }
 * }
 */
public class Solution {
    Dictionary<int, int> depthMap = new Dictionary<int, int>();
    public int FindDistance(TreeNode root, int p, int q) {
        BuildDepthMap(root, 0);
        if (root.val == p)
        {
            return depthMap[q];
        }
        else if (root.val == q)
        {
            return depthMap[p];
        }
        else if (p == q)
        {
            return 0;
        }
        else if (depthMap[p] == depthMap[q])
        {
            return 2;
        }
        else if (TreeContains(root.left, p))
        {
            if (TreeContains(root.left, q))
            {
                return Math.Abs(depthMap[p] - depthMap[q]);
            }
            else
            {
                return depthMap[p] + depthMap[q];
            }
        }
        else if (TreeContains(root.right, p))
        {
            if (TreeContains(root.right, q))
            {
                return Math.Abs(depthMap[p] - depthMap[q]);
            }
            else
            {
                return depthMap[p] + depthMap[q];
            }
        }
        else if (TreeContains(root.left, q))
        {
            if (TreeContains(root.left, p))
            {
                return Math.Abs(depthMap[q] - depthMap[p]);
            }
            else
            {
                return depthMap[p] + depthMap[q];
            }
        }
        else if (TreeContains(root.right, q))
        {
            if (TreeContains(root.right, p))
            {
                return Math.Abs(depthMap[p] - depthMap[q]);
            }
            else
            {
                return depthMap[p] + depthMap[q];
            }
        }
        

        return 42;
    }

    public void BuildDepthMap(TreeNode node, int depth)
    {
        if (node == null)
        {
            return;
        }

        depthMap[node.val] = depth;
        BuildDepthMap(node.left, depth + 1);
        BuildDepthMap(node.right, depth + 1);
        depth -= 1;
    }

    public bool TreeContains(TreeNode node, int value)
    {
        if (node == null)
        {
            return false;
        }

        if (node.val == value)
        {
            return true;
        }

        return TreeContains(node.left, value) || TreeContains(node.right, value);
    }
}
```

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/71960397/dd069303-19a8-41c4-80a9-a0c8ef725e32)

![Screenshot 2023-11-23 064931](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/71960397/bcbacec1-996f-43ba-81f1-669787e32f18)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
