### ISSUE TITLE
Missing Test Case - 1410. HTML Entity Parser

### ISSUE THREAD

**Issue by aaronmayo** [LeetCode-Feedback/LeetCode-Feedback#18221]
### LeetCode Username
niceshark

### Problem number, title, and link
1410. HTML Entity Parser https://leetcode.cn/problems/html-entity-parser/

### Category of the bug
- Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

My code can pass all test cases. But it should fail with this case :  "&amp;&+gt; is an HTML entity".

### Language used for code
javaScript

### Code used for Submit/Run operation

```
var entityParser = function(text) {
    return text.replace(/\&quot;/g,'"').replace(/\&apos;/g,"'").replace(/\&amp;/g,'&+').replace(/\&gt;/g,'>').replace(/\&lt;/g,'<').replace(/\&frasl;/g,'/').replace(/\&\+/g,'&')
};
```

### Expected behavior

The key is `.replace(/\&amp;/g,'&+')`, `.replace(/\&\+/g,'&')`. It replace &amp; to &+ to avoid multiple replaces, and replace back to & in the end. However &+ could be the original text, that operation could change original text. By the way, the &+ could be other forms, like &-, &+-, etc. So the test case should be dynamic according to specific regExp replace code, which may be difficult.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/24400559/67bd6e81-5fa0-4fef-a080-fd9c0bb5a810)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
