### ISSUE TITLE
Missing Test Case - 1581. Customer Who Visited but Did Not Make Any Transactions

### ISSUE THREAD

**Issue by Abdalrhman-Mohammad** [LeetCode-Feedback/LeetCode-Feedback#18222]
### LeetCode Username

AbdalrhmanALMohammad

### Problem number, title, and link

1581. Customer Who Visited but Did Not Make Any Transactions
https://leetcode.com/problems/customer-who-visited-but-did-not-make-any-transactions/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ X] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Some codes get accepted in the problem , but it is take wrong on some cases not exist in the test cases.

### Language used for code

MySQL

### Code used for Submit/Run operation

```
SELECT  
customer_id 
,count(customer_id) count_no_trans
from 
Visits 
LEFT JOIN
Transactions
ON 
Visits.visit_id=Transactions.visit_id 
where
transaction_id is null
group by
 (customer_id );
```

### Expected behavior

The code that I put it must got wrong on bellow test case ,But when i submit the code it is took Accepted.

Visits =
| visit_id | customer_id |
| -------- | ----------- |
| 1        | 23          |
| 2        | 9           |
| 4        | 30          |
| 5        | 54          |
| 6        | 96          |
| 7        | 54          |
| 8        | 54          |

Transactions =
| transaction_id | visit_id | amount |
| -------------- | -------- | ------ |
| 2              | 5        | null    |
| 3              | 5        | 300    |
| 9              | 5        | 200    |
| 12             | 1        | 910    |
| 13             | 2        | 970    |

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/118562424/04175569-2c44-4903-920f-209faa6c10c0)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
