### ISSUE TITLE
121. Best Time to Buy and Sell Stock - Incorrect test case including a zero

### ISSUE THREAD

**Issue by nanotaboada** [LeetCode-Feedback/LeetCode-Feedback#18237]
### LeetCode Username
nanotaboada

### Problem number, title, and link
121. Best Time to Buy and Sell Stock](https://leetcode.com/problems/best-time-to-buy-and-sell-stock/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
The problem contains an invalid test case including a 0. In the real stock market there is no such thing as a stock price of zero.

### Language used for code
C#

### Code used for Submit/Run operation

```
public class Solution
{
    public int MaxProfit(int[] prices)
    {
        int profit = 0;
        int buyingPrice = prices[0];

        for (int day = 1; day < prices.Length; day++)
        {
            int dailyPrice = prices[day];

            // if (dailyPrice > 0)
            // {
                if (dailyPrice < buyingPrice)
                {
                    // buy cheaper
                    buyingPrice = dailyPrice;
                }
                else if (dailyPrice - buyingPrice > profit)
                {
                    // sell and take profit
                    profit = dailyPrice - buyingPrice;
                }
            // }
        }

        return profit;
    }
}
```

### Expected behavior
Stock prices should always be greater than zero.

### Screenshots
<img width="627" alt="121  Best Time to Buy and Sell Stock" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/87288/5e20ebd9-7b65-4a82-b3bc-0c176b6a5a93">

### Additional context
N/A

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
