### ISSUE TITLE
Missing Test Validation/ Test Case - 2692. Make Object Immutable

### ISSUE THREAD

**Issue by kentshenlim** [LeetCode-Feedback/LeetCode-Feedback#18230]
### LeetCode Username

soyukotoda

### Problem number, title, and link

[2692. Make Object Immutable](https://leetcode.com/problems/make-object-immutable/)

### Category of the bug
- [ ] Problem constraints
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

Primitives allowed in Run, jamming [AC](https://leetcode.com/problems/make-object-immutable/submissions/1104619488).

### Language used for code

JavaScript

### Code used for Submit/Run operation

```JS
// Paste your code here. Don't remove ``` given
// above and below the code.
var makeImmutable = function (obj) {
    return new Proxy(obj, {
        get(target, property) {
            const val = target[property];
            // Function, check if the method is forbidden
            if (val instanceof Function) {
                if (new Set(['pop', 'push', 'shift', 'unshift', 'splice', 'sort', 'reverse']).has(property)) {
                    return () => {
                        throw `Error Calling Method: ${property}`;
                    }
                }
                return val;
            }
            // Non-primitive properties
            if (val instanceof Object) return makeImmutable(val);
            // Regular
            return val;
        },
        set(target, property, _) {
            if (Array.isArray(target)) throw `Error Modifying Index: ${property}`;
            throw `Error Modifying: ${property}`;
        }
    });
};
```

### Expected behavior

Run should complain "Invalid Test Case" if primitives are not allowed as inputs, otherwise test cases should be added to reject weak submission that does not handle primitive input correctly as this [AC](https://leetcode.com/problems/make-object-immutable/submissions/1104619488).

### Screenshots

![lcis3](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/106628390/005e3026-c5cd-4bce-9d7a-448d45e00605)
![lcis4](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/106628390/f150daf9-7065-4f30-8fa3-c717aaf38b91)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
