### ISSUE TITLE
Incorrect Test Cases for  (1630) Arithmetic Subarrays

### ISSUE THREAD

**Issue by saurabhdhingra** [LeetCode-Feedback/LeetCode-Feedback#18232]
### Category of the bug
Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### Description of the bug
I have written the given code and both my test cases are coming to be partially correct. One sub-case in both the test cases is wrong. I checked them and my answers are correct as per the problem statement.

### Language used for code
Java

### Code used for Submit/Run operation

```
class Solution {
    public List<Boolean> checkArithmeticSubarrays(int[] nums, int[] l, int[] r) {
        List<Boolean> ans = new ArrayList<>();
        int len = nums.length;

        int[] dif = new int[len-1];

        for(int i = 0; i < len-1; i++){
            dif[i] = nums[i+1] - nums[i];
        }
        
        int n = l.length;

        for(int i = 0; i < n; i++){
            boolean check = true;
            int temp = dif[l[i]];
            for(int j = l[i]; j < r[i]-1; j++){
                if(dif[j] != temp){
                    check = false;
                    break;
                }
            }
            ans.add(check);
        }
        return ans;
    }
}
```

### Expected behavior
Both the Test Cases should have executed completely. 

### Screenshots
Test Case 1
<img width="945" alt="Screenshot 2023-11-23 at 12 36 20 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/75309640/0ca50516-31d6-49e2-8ce6-b76dbd27dfb1">

Test Case 2
<img width="950" alt="Screenshot 2023-11-23 at 12 37 24 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/75309640/5f8c49be-d7d2-48e6-b668-fcd1469fcf48">

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
