### ISSUE TITLE
Incomplete Description - 312. Burst Baloons 

### ISSUE THREAD

**Issue by Sky-Nik** [LeetCode-Feedback/LeetCode-Feedback#1823]
#### Your LeetCode username
@nskybytskyi

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Test cases assume that whenever a bursting balloon has no adjacent balloon on either side the corresponding value should be treated as `1`, but the description never mentions it explicitly.

#### Expected behaviour

Explain that `nums[left]` and `nums[right]` are considered to be `1` when there are no adjacent balloons.

**Comment by lc-kay** [comment]
Hi @Sky-Nik 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Sky-Nik 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
