### ISSUE TITLE
Missing Test Case - 1849. Splitting a String Into Descending Consecutive Values

### ISSUE THREAD

**Issue by admtn** [LeetCode-Feedback/LeetCode-Feedback#18235]
### LeetCode Username
suwekforu

### Problem number, title, and link
1849. Splitting a String Into Descending Consecutive Values
https://leetcode.com/problems/splitting-a-string-into-descending-consecutive-values/description/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Code submitted is accepted, however custom test cases shows that the answer is wrong.
Here is a non exhaustive list of test cases:
"16105104"
"2320221"
"333000231"
"4340241"
"5345303"
"14103"
"1591500815007"
All these test cases can be split into substrings a decreasing by values of 1 **IF** we skip the 0s.
e,g "16105104" => "16" , "15" (skipped 0) , "14"
e.g "4340241" => "43" "42"(skipped 0) "41"
But we can only skip 0s if we are still trying to character match the first character of the target string
e.g "4304241" => "43 "042" "41" because leading 0s have no value, i.e "042" == 42
The solution submitted allows us to skip an index if  s[i] == '0' , but this should only be allowed if t == 0
and the code submitted did not check if t == 0. Yet it was still accepted.
Explanation as to why this code **SHOULD NOT** be accepted is explained below together with the screenshots.

### Language used for code
Python3

### Code used for Submit/Run operation

```
class Solution:
    def splitString(self, s: str) -> bool:

        def getNum(target,i):
            if target == '0':
                return int(s[i:]) == 0
            t = 0 # idx for target
            while t < len(target) and i < len(s):
                if s[i] == target[t]:
                    i += 1
                    t += 1
                elif s[i] == '0':
                    i += 1
                else:
                    return False
            
            if i == len(s) and t == len(target): # both done
                return True
            elif i == len(s): # s done
                return False
            else:
                return getNum(str(int(target)-1),i)

        for i in range(len(s)-1):
            if getNum(str(int(s[:i+1])-1),i+1):
                return True
        return False
```

### Expected behavior
Expected submission to fail, because if I use the test cases I provided, it should all return False as there
is no way for us to split s into two or more non-empty substrings such that their values are in decrementing in values of 1 from left to right, but the code submits True.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/84576312/82fda0a2-2f38-4302-9939-abd08afc5552)
As seen in the image, I submitted this code 5 times, all 5 times were accepted, yet all 5 custom test cases fails. All 5 custom test
cases were provided above.

To explain the code, the getNum function checks if, given a target value, and a starting index i, is it possible to iterate
through string s starting from index i, such that it will achieve the target value, and subsequently all target values decreasing by 1.
It does this by iterating through string s and string target and does character matching, and only increments both pointers s and i if they have the same character, and returns False otherwise. 
We then check for all possible values of a starting target value in the for loop on line 24.

However, there is an edge case where, if we are **still trying to match the FIRST character of target** to a character of s, the character of s is allowed to be '0' , because for example, if target = "12" , our string to match can be "0012" because "0012" has a value of 12,
because any leading 0s will NOT affect the value. In which case, we can skip the '0' and increment i pointer.

As you can see on line 12 of the code, the code does not check if t == 0 (trying to match first character of target), hence it should not be accepted.
As a result, when trying to match for example let's say "14103", it will try 14 as its first value, and starting from index i == 2 of string s, it needs to get 13 as its next value, it will match 1, skip 0, and match 3, and return True, when the answer is False. But it is not allowed to skip 0 because we are trying to match the **second** character from the target string "13", we can only skip '0' if we are matching the **first** character of our target string.
The correct solution on line 12 would be elif s[i] == '0' and t == 0. Replacing that line passed all the custom test cases.
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/84576312/220e5f37-08e4-4f3c-84fb-bff9b24a524e)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
