### ISSUE TITLE
Missing Test Case - 1211. Queries Quality and Percentage

### ISSUE THREAD

**Issue by Abdalrhman-Mohammad** [LeetCode-Feedback/LeetCode-Feedback#18240]
### LeetCode Username

AbdalrhmanALMohammad

### Problem number, title, and link

1211. Queries Quality and Percentage
https://leetcode.com/problems/queries-quality-and-percentage/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [X] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Some codes get accepted in the problem , but it is take wrong on some cases not exist in the test cases.

### Language used for code

MySQL

### Code used for Submit/Run operation

```
SELECT 
query_name , 
# ROUND(AVG((rating/position)),2) AS quality ,
ROUND(SUM(rating/position)/COUNT(query_name),2) AS quality ,
ROUND(AVG(rating <3)* 100,2)  AS poor_query_percentage 
FROM  Queries 
GROUP BY query_name;
```

### Expected behavior

The code that I put it must got wrong on bellow test case ,But when i submit the code it is took Accepted.

Queries =
| query_name | result           | position | rating |
| ---------- | ---------------- | -------- | ------ |
| null       | Golden Retriever | 1        | 5      |
| null       | German Shepherd  | 2        | 5      |
| null       | Mule             | 200      | 1      |
| Cat        | Shirazi          | 5        | 2      |
| Cat        | Siamese          | 3        | 3      |
| Cat        | Sphynx           | 7        | 4      |

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/118562424/236b68f9-98e4-4b27-b07d-f4b26d119fce)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by Suganth27** [comment]
Yea, even I am facing this missing test case issue.
