### ISSUE TITLE
Discrepancy between problem description and constraints

### ISSUE THREAD

**Issue by nanotaboada** [LeetCode-Feedback/LeetCode-Feedback#18247]
### LeetCode Username

nanotaboada

### Problem number, title, and link

[190. Reverse Bits](https://leetcode.com/problems/reverse-bits/)

### Category of the bug
- [x] Problem description
- [ ] Solved examples
- [x] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The problem starts with:

> Reverse bits of a given 32 bits unsigned integer.

But then the constraints section reads:

> Constraints:
> The input must be a binary string of length 32

Similarly, the default code definition is:

```
public class Solution {
    public uint reverseBits(uint n) {
        
    }
}
```

### Language used for code

C#

### Code used for Submit/Run operation

```
public class Solution {
    public uint reverseBits(uint n) {
        
    }
}
```

### Expected behavior

Coherence between description and constraints.

### Screenshots

<img width="1009" alt="190  Reverse Bits" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/87288/b426c366-ac4b-493c-b6bd-c71f04b76edc">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by nanotaboada** [comment]
> The team decided to reject this feedback after the evaluation.

What are the reasons behind that decision? Clearly there is an inconsistency between the description and the constraints.

**Comment by TheRedSpy15** [comment]
This also applies to Java. Seems very nonconstructive to simply refuse feedback without any explanation. The response to this issue feels very automated and likely was never even giving the time of day

**Comment by awwalm** [comment]
> Thank you for your time.
> 
> We've used your feedback to check the problem.
> 
> The team decided to reject this feedback after the evaluation.
> 
> If you have any other questions or feedback, please don't hesitate to let us know!
> 
> We appreciate your support!

That is a rather profoundly unsubstantial and unreasonable response. It would have been better for you to not have said anything. We will just have to simply deem this problem entry as a stupid question on Leetcode.
