### ISSUE TITLE
Suboptimal Solution gets AC - 556. Next Greater Element III

### ISSUE THREAD

**Issue by Sky-Nik** [LeetCode-Feedback/LeetCode-Feedback#1824]
#### Your LeetCode username
@nskybytskyi

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

This is not necessarily a bug,  but I believe that O((log n)!) solutions should be considered too slow for this question and get TLE, as there is O(log n) way to generate the next permutation of digits.

#### Code you used for Submit/Run operation

```python
class Solution:
    def nextGreaterElement(self, n: int) -> int:
      digits = str(n)
      next = 2**31
      for permutation in itertools.permutations(digits):
        candidate = int(''.join(permutation))
        if n < candidate < next:
          next = candidate
      return -1 if next == 2**31 else next
```

#### Language used for code

Python

#### Expected behavior

Add testcases with `n` up to `2^63 - 1` to ensure that O((log n)!) solutions fail.

**Comment by lc-kay** [comment]
@Sky-Nik Can you please provide a test case that this will fail on? You can submit the test case in a .txt file.

**Comment by lc-kay** [comment]
Hi @Sky-Nik 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
