### ISSUE TITLE
Missing Test Case - 1135. Connecting Cities With Minimum Cost

### ISSUE THREAD

**Issue by zsq007** [LeetCode-Feedback/LeetCode-Feedback#18249]
### LeetCode Username

[zsq007](https://leetcode.com/zsq007)

### Problem number, title, and link

[1135. Connecting Cities With Minimum Cost](https://leetcode.com/problems/connecting-cities-with-minimum-cost/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Current test cases don't include disconnected graph with number of edges greater or equal to n-1 (i.e. `len(connections) >= n-1`). Therefore, adding a checking of `len(connections) < n-1` will eliminate all the disconnected graph in the current test cases and get accepted, whereas not all the disconnected graph satisfy the condition. A possible test case is given below.

### Language used for code

Python 3

### Code used for Submit/Run operation

```
class Solution:
    def minimumCost(self, n: int, connections: List[List[int]]) -> int:
        if len(connections) < n-1:
            return -1

        edges = [[] for _ in range(n+1)]
        for conn in connections:
            edges[conn[0]].append((conn[2], conn[1]))
            edges[conn[1]].append((conn[2], conn[0]))
        
        heap, visited, res = edges[1], set([1]), 0
        heapify(heap)
        while heap:
            cost, node = heappop(heap)
            if node not in visited:
                visited.add(node)
                res += cost
                for item in edges[node]:
                    if item[1] not in visited:
                        heappush(heap, item)
        return res
// The correct code here should be 
//      return res if len(visited) == n else -1
```

Test case to be added:
```
n = 4
connections = [[1,2,5],[1,3,6],[2,3,1]]
```

### Expected behavior

The code got accepted, but failed in the test case above. The expected result should be -1, indicating a disconnected graph, but the code still returns the cost result.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
