### ISSUE TITLE
277. Find the Celebrity, test case incorrect

### ISSUE THREAD

**Issue by shinboLu** [LeetCode-Feedback/LeetCode-Feedback#18242]
### LeetCode Username

edwardlxb

### Problem number, title, and link

277. Find the Celebrity https://leetcode.com/problems/find-the-celebrity/description/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The problems statement mentioned  "n people labeled from 0 to n - 1". The test case No. 107 has an input: n= 2, input= [[1,1],[1,1]], which didn't start with 0. 

### Language used for code

Python

### Code used for Submit/Run operation

```
class Solution:
    def findCelebrity(self, n: int) -> int:
        res = 0
        adj_list = collections.defaultdict(set)
        for i in range(n):
            for j in range(n):
                if i != j:
                    if knows(i, j) and not knows(j, i):
                        adj_list[j].add(i)
                    elif not knows(i, j) and knows(j, i):
                        adj_list[i].add(j)
                    elif knows(i,j) and knows(j, i):
                        adj_list[i].add(j)
                        adj_list[j].add(i)
                    else:
                        continue
                else:
                    continue 
        for idx, val in adj_list.items():
            if len(val) == n - 1:
                return idx
        return -1
```

### Expected behavior

Expect the input to be [0, 0][0,0]

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/123519065/2efbb6fe-5488-437f-abd1-50cd8bd5ba1a)

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
