### ISSUE TITLE
Missing Test Case - 1193. Monthly Transactions I

### ISSUE THREAD

**Issue by Abdalrhman-Mohammad** [LeetCode-Feedback/LeetCode-Feedback#18254]
### LeetCode Username

AbdalrhmanALMohammad

### Problem number, title, and link

1193. Monthly Transactions I
https://leetcode.com/problems/monthly-transactions-i/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [X] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Some codes get accepted in the problem , but it is take wrong on some cases not exist in the test cases.

### Language used for code

MySQL

### Code used for Submit/Run operation

```
# Write your MySQL query statement below
SELECT 
date_format(trans_date, '%Y-%m') AS month
, country 
, COUNT(country) AS trans_count
, SUM(state='approved') AS approved_count
, SUM(amount) AS trans_total_amount
,SUM(CASE WHEN  state='approved' THEN amount ELSE 0 END) AS approved_total_amount
FROM
Transactions 
GROUP BY month, country;
```

### Expected behavior

The code that I put it must got wrong on bellow test case ,But when i submit the code it is took Accepted.

Transactions =
| id  | country | state    | amount | trans_date |
| --- | ------- | -------- | ------ | ---------- |
| 121 | US      | approved | 1000   | 2018-12-18 |
| 122 | US      | declined | 2000   | 2018-12-19 |
| 123 | US      | approved | 2000   | 2019-01-01 |
| 124 | null      | approved | 2000   | 2019-01-07 |
### Screenshots

![Untitled](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/118562424/675a17c7-cb69-486f-b69f-739a9277a781)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
