### ISSUE TITLE
Missing Test Case - 26. Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by monzone33** [LeetCode-Feedback/LeetCode-Feedback#1825]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
class Solution {
  public int removeDuplicates(int[] nums) {
          if (nums.length > 0) {
              int duplicates = 1;
              int pointer1 = nums[0];
              int pointer2 = pointer1;
              for (int i = 0; i < nums.length; i++) {
                  pointer2 = nums[i];
                  if (pointer1 != pointer2) {
                      pointer1 = pointer2;
                      nums[duplicates] = pointer1;
                      duplicates++;
                  }
              }
              return duplicates;
          } 
          return 0;
      }
}
```

**Comment by ThanoS-max** [comment]
Can we use move operator to assign ptr1 to ptr2?

**Comment by lc-kay** [comment]
@monzone33 Can you please provide the test case this fails on? 
@ThanoS-max Please refer to the discuss tab for this question.

**Comment by monzone33** [comment]
I was intending to post my solution for others to see and learn. I didn’t expect my solution to land in this area where bugs are reported. Sorry.

**Comment by lc-kay** [comment]
@ThanoS-max No worries, you are welcome to post your solution on https://leetcode.com/problems/remove-duplicates-from-sorted-array/discuss/. Thank you for your time!
