### ISSUE TITLE
Binary Tree Explore Card UI issue: Blue Screen is coming while going through images in binary tree.

### ISSUE THREAD

**Issue by cmoulicms** [LeetCode-Feedback/LeetCode-Feedback#18267]
### LeetCode Username
cmoulicms

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support
- [X] Explore

### Description of the bug
Blue screen is coming while going through binary tree images.
https://leetcode.com/explore/learn/card/data-structure-tree/134/traverse-a-tree/992/.

when I click images one by one some time blue screen coming.

### Expected behavior
Not come blue screen.

### Screenshots

https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/52199121/c2b62f03-906e-493d-b3fe-d795351af7ee

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The slideshow is set for autoplay, there won't be any issues.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by cmoulicms** [comment]
I didn't get any leetcode points for the feedback.
I updated my leetcode username.
username: https://leetcode.com/cmoulicms/
