### ISSUE TITLE
Incorrect tests validator for problem 943. Find the Shortest Superstring

### ISSUE THREAD

**Issue by kefaa** [LeetCode-Feedback/LeetCode-Feedback#18266]
### LeetCode Username

kefaa https://leetcode.com/kefaa/

### Problem number, title, and link
 943. Find the Shortest Superstring https://leetcode.com/problems/find-the-shortest-superstring/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [x] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

_Incorrect tests validator._

The statement says "You may assume that no string in `words` is a substring of another string in `words`". 
But there is a testcase `["ab","a","b"]` which violates this condition and should not be accepted by tests validator. 
At the same time, the test `["a","b","ab"]` is correctly considered as invalid.
So, it's definitely a bug in validator

### Language used for code

C++
Submission link: https://leetcode.com/problems/find-the-shortest-superstring/submissions/1105558207

### Code used for Submit/Run operation

Not sure it's needed, but just in case :)
```
class Solution {
public:
    string shortestSuperstring(vector<string>& words) {
        const int n = words.size();
        vector<vector<int>> match(n, vector<int>(n));
        for (int i = 0; i < n; ++i) {
            for (int j = 0; j < n; ++j) if (i != j) {
                for (int k = min(words[i].size(), words[j].size()) - 1; k >= 1; --k) {
                    if (words[i].substr(words[i].size() - k) == words[j].substr(0, k)) {
                        match[i][j] = k;
                        break;
                    }
                }
            }
        }
        vector<vector<int>> dp(1 << n, vector<int>(n, 1000));
        vector<vector<int>> f(1 << n, vector<int>(n, -1));
        for (int m = 0; m < (1 << n); ++m) {
            for (int i = 0; i < n; ++i) if (m >> i & 1) {
                int p = m ^ (1 << i);
                if (p == 0) {
                    dp[m][i] = words[i].size();
                    continue;
                }
                for (int j = 0; j < n; ++j) if (p >> j & 1) {
                    const int c = words[i].size() - match[j][i];
                    if (dp[p][j] + c < dp[m][i]) {
                        dp[m][i] = dp[p][j] + c;
                        f[m][i] = j;
                    }
                }
            }
        }
        int b = 0;
        int m = (1 << n) - 1;
        for (int j = 1; j < n; ++j) {
            if (dp[m][j] < dp[m][b]) {
                b = j;
            }
        }
        vector<int> order;
        while (m != 0) {
            order.push_back(b);
            int new_b = f[m][b];
            m ^= 1 << b;
            b = new_b;
        }
        reverse(order.begin(), order.end());
        
        string superstring = words[order[0]];
        for (int k = 1; k < n; ++k) {
            const int j = order[k - 1];
            const int i = order[k];
            superstring += words[i].substr(match[j][i]);
        }
        return superstring;
    }
};
```

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team

**Comment by kefaa** [comment]
Hardly it can be called "a thorough evaluation"
