### ISSUE TITLE
Missing Test Case - 862. Shortest Subarray with Sum at Least K

### ISSUE THREAD

**Issue by peacalm** [LeetCode-Feedback/LeetCode-Feedback#18268]
### LeetCode Username
[ShuangquanLi](https://leetcode.com/ShuangquanLi/)

### Problem number, title, and link
[862. Shortest Subarray with Sum at Least K](https://leetcode.com/problems/shortest-subarray-with-sum-at-least-k/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [✅] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

This code should get WA, but [Accepted](https://leetcode.com/problems/shortest-subarray-with-sum-at-least-k/submissions/1105570969/).

### Testcase to add
```
[2,-1,1,-1,1,2]
3
```

### Language used for code
Python3

### Code used for Submit/Run operation
```
class Solution:
    def shortestSubarray(self, nums: List[int], k: int) -> int:
        n = len(nums)
        ret = n + 1
        i = j = 0
        si = sj = 0
        q = collections.deque([0])

        while j < n:
            sj += nums[j]
            j += 1
            if sj <= 0:
                i = j
                si = sj = 0
                q = collections.deque([0])
                continue
            while q and q[-1] >= sj:
                q.pop()
            q.append(sj)
            # print((i,j,nums[i:j],si, sj), q)
            while i < j and q and sj - q[0] >= k:
                ret = min(ret, j - i)
                if si == q[0]:
                    q.popleft()
                si += nums[i]
                i += 1

        return -1 if ret == n + 1 else ret
```

### Screenshots
<img width="1370" alt="截屏2023-11-25 上午2 00 30" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/16322505/ff02f393-832e-4fb3-b511-fa2234aeee98">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
