### ISSUE TITLE
Missing Test Case - 2356. Number of Unique Subjects Taught by Each Teacher

### ISSUE THREAD

**Issue by Abdalrhman-Mohammad** [LeetCode-Feedback/LeetCode-Feedback#18270]
### LeetCode Username

AbdalrhmanALMohammad

### Problem number, title, and link

2356. Number of Unique Subjects Taught by Each Teacher
https://leetcode.com/problems/number-of-unique-subjects-taught-by-each-teacher/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [X] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Some codes get accepted in the problem , but it is take wrong on some cases not exist in the test cases.

### Language used for code

MySQL

### Code used for Submit/Run operation

```
SELECT teacher_id AS teacher_id, COUNT(DISTINCT subject_id)AS cnt
FROM Teacher AS t
WHERE teacher_id IS NOT NULL
GROUP BY 1;
```

### Expected behavior

The code that I put it must got wrong on bellow test case ,But when i submit the code it is took Accepted.

Teacher =
| teacher_id | subject_id | dept_id |
| ---------- | ---------- | ------- |
| null          | 2          | 3       |
| JANEM          | 2          | 4       |

### Screenshots

![pic2356](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/118562424/3161666e-beb5-49aa-ba6a-bd45ed7ab483)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
