### ISSUE TITLE
Minimum Amount of Time to Collect Garbage - Missing Approach

### ISSUE THREAD

**Issue by mingfengwan** [LeetCode-Feedback/LeetCode-Feedback#18275]
### LeetCode Username
wmf410

### Problem number, title, and link
1. [Minimum Amount of Time to Collect Garbage](https://leetcode.com/problems/minimum-amount-of-time-to-collect-garbage/)

### Category of the bug
- [x] Editorial

### Language used for code
Python

### Additional context
As multiple users in the comment section pointed out, the best approach to this question should be iterating the garbage list **in reverse**, without the need to modify the list in-place or use a hashmap.

### Code used for Submit/Run operation
```
class Solution:
    def garbageCollection(self, garbage: List[str], travel: List[int]) -> int:
        G = P = M = False
        ans = len(garbage[0])

        for i in range(len(travel), 0, -1):
            G |= 'G' in garbage[i]
            P |= 'P' in garbage[i]
            M |= 'M' in garbage[i]
            ans += travel[i-1] * (G + P + M) + len(garbage[i])
        
        return ans
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
