### ISSUE TITLE
Please provide subtitles to leetcode videos for those who have issues with english and hearing

### ISSUE THREAD

**Issue by Anusree6154s** [LeetCode-Feedback/LeetCode-Feedback#18273]
Please provide subtitles to leetcode videos for those who have issues with english and hearing. And it is kind of necessary! I'm unable to move forward with some videos because of it.

**Comment by LC-Pam** [comment]
Hi there,
 
We appreciate your patience and support.

We have indeed been actively engaged with our third-party video player provider to discuss the implementation of automatic captions. 

We promise we will add subtitles for all our future videos, but for the old videos without subtitles, we currently cannot add them. Integrating captions involves both technical considerations and financial aspects, and we are diligently working to reach a final plan with our third-party provider. 

Please rest assured that we are committed to enhancing the accessibility of our content, and we will keep you informed of any developments. We understand the importance of this feature and appreciate your patience as we work towards a comprehensive and effective solution.

If you have any further questions or concerns, feel free to reach out. We value your feedback and look forward to delivering an improved experience for all users.

Best regards,
The Leetcode Team
