### ISSUE TITLE
Missing test case - 253. Meeting Rooms II

### ISSUE THREAD

**Issue by RakhmedovRS** [LeetCode-Feedback/LeetCode-Feedback#1827]
#### Your LeetCode username
rakhmedovrs

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Task doesn't say anything about input values which leads us to following problems:
1. We can expect any int from -2147483648 to 2147483647, but it turned out that start time is always greater or equal to zero. I think it must be claryfied.
2. I created a memo array of size 1000000 which means in case you add a test case with ending time of any interval greater or equal 1000000 causes my solution to fail. 

#### Code you used for Submit/Run operation

```
	public int minMeetingRooms(int[][] intervals)
	{
		int[] memo = new int[1000000];
		for (int[] interval : intervals)
		{
			memo[interval[0]] += 1;
			memo[interval[1]] -= 1;
		}

		int max = memo[0];
		for (int i = 1; i < memo.length; i++)
		{
			memo[i] += memo[i - 1];
			max = Math.max(max, memo[i]);
		}

		return max;
	}
```

#### Language used for code
Java

#### Expected behavior
You need explicitly define input value restrictions and add test case where one of the values equals to Integer.MAX_VALUE

#### Screenshots
![pass](https://user-images.githubusercontent.com/25452084/103436859-61a14700-4c31-11eb-97b2-59ea9a1df93d.jpg)

**Comment by lc-kay** [comment]
Hi @RakhmedovRS 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@RakhmedovRS Our team has added the missing hints and updated the problem. Thank you for your time.
