### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by kk3221-adjk** [LeetCode-Feedback/LeetCode-Feedback#18283]
/

### Category of the bug
- [x] Solved examples
- [x] Problem constraints
- [x] Editorial
- [x] Programming language support

### Code used for Submit/Run operation

```
int* twoSum(int* nums, int numsSize, int target, int* returnSize) 
{
    int* indices=(int*)malloc(2*sizeof(int));
    int i,j;
    for(i=0;i<numsSize;i++)
    {
        for(j=i+1;j<numsSize;j++)
        {
            if(nums[i]+nums[j]==target)
            {
                indices[0]=i;
                indices[1]=j;
                *returnSize=2;
                return indices;
            }
        }
    }
    *returnSize=0;
    return NULL;
}
```

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
