### ISSUE TITLE
1698. Number of Distinct Substrings in a String | Improper hints & follow-up question

### ISSUE THREAD

**Issue by zerotrac** [LeetCode-Feedback/LeetCode-Feedback#1828]
#### Your LeetCode username

zerotrac2

#### Category

- [x] Question

#### Description

The hints as well as the follow-up question in the problem is quite improper.

For the hints part, we can simply come up with an algorithm based on rolling hash. Here is the pseudocode.

```
n <- length of s
t <- hashtable
for i = 0 to n - 1 do
    for j = i to n - 1 do
        calculate the rolling hash of s[i..j] = V based on the previous calculation of s[i..j-1]
        t <- t | V
    end for
end for
return size of t
```

This algorithm is `O(n^2)` time complexity, and we do not need pre-calculated prefix hashing.

For the follow-up part, it is too difficult for an interview question. We should use one of the `O(n)` algorithms in suffix array, suffix tree, or suffix automation to obtain the LCP (longest common prefix) array for every pair of neighbor suffixes in lexicographical order, which is impossible for an interviewee to implement during an interview.

**Comment by lc-kay** [comment]
Hi @zerotrac 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@zerotrac The hints added for this problem are the hints given by the interviewer during the interview.
Also, for the follow-up, the interviewer asked if we can do better than O(n^2) and discussed the idea without asking for the code. Therefore, we will not be changing the hints or problems. Thank you for your time!
