### ISSUE TITLE
Time limit for problem 2725 - Interval Cancellation

### ISSUE THREAD

**Issue by fragoi** [LeetCode-Feedback/LeetCode-Feedback#18284]
### LeetCode Username

fragoi

### Problem number, title, and link

2725\. Interval Cancellation https://leetcode.com/problems/interval-cancellation/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Always getting "Time Limit Exceeded" also using solutions from editorial (for all 3 of them).
Seems like time limit is misconfigured.

### Language used for code

JavaScript

### Code used for Submit/Run operation

Attempt 1:
```JavaScript
var cancellable = function(fn, args, t) {
  fn(...args);
  const id = setInterval(fn, t, ...args);
  return () => {
    clearInterval(id);
  };
};
```

Attempt 2:
```JavaScript
var cancellable = function(fn, args, t) {
  let id;
  const loop = () => {
    fn(...args);
    id = setTimeout(loop, t);
  };

  loop();

  return () => clearTimeout(id);
};
```

Attempt 3 (from editorial):
```JavaScript
var cancellable = function(fn, args, t) {
    fn(...args);
    const timer = setInterval(() => fn(...args), t);

    const cancelFn = () => clearInterval(timer);
    return cancelFn;
};
```

Attempt 4 (from editorial):
```JavaScript
var cancellable = function(fn, args, t) {
    let isCancelled = false;
    fn(...args);
    const startInterval = () => {
        setTimeout(() => {
            if (isCancelled) return;
            fn(...args);
            startInterval();
        }, t);
    }
    startInterval();
    const cancelInterval = () => {
        isCancelled = true;
    }

    return cancelInterval;
};
```

Attempt 5 (from editorial):
```JavaScript
var cancellable = function(fn, args, t) {
    let timerId = null;
    fn(...args);

    const startInterval = () => {
        timerId = setTimeout(() => {
            fn(...args);
            startInterval();
        }, t);
    };
    startInterval();

    const cancelInterval = () => {
        if (timerId !== null) { // not totally needed as clearTimeout is very forgiving fn
            clearTimeout(timerId);
        }
    };

    return cancelInterval;
};
```

### Expected behavior

Submissions not to fail with "Time Limit Exceeded", at least the ones from editorial.

### Additional context

Looking at the comments, seems like other users suffered the issue.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
