### ISSUE TITLE
Missing Test Case - 4. Median of Two Sorted Arrays

### ISSUE THREAD

**Issue by Sujal092004** [LeetCode-Feedback/LeetCode-Feedback#18280]
### LeetCode Username
[Sujal092004](https://github.com/Sujal092004)

### Problem number, title, and link

4.Median of two sorted arrays https://leetcode.com/problems/median-of-two-sorted-arrays/

Given two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays.

The overall run time complexity should be O(log (m+n)).

 

Example 1:

Input: nums1 = [1,3], nums2 = [2]
Output: 2.00000
Explanation: merged array = [1,2,3] and median is 2.
Example 2:

Input: nums1 = [1,2], nums2 = [3,4]
Output: 2.50000
Explanation: merged array = [1,2,3,4] and median is (2 + 3) / 2 = 2.5.
 

Constraints:

nums1.length == m
nums2.length == n
0 <= m <= 1000
0 <= n <= 1000
1 <= m + n <= 2000
-106 <= nums1[i], nums2[i] <= 106

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Language used for code
C++

### Code used for Submit/Run operation

```
class Solution {
    int m = nums1.size();
        int n = nums2.size();
        int a = m + n;
        int merged[a];
        int i = 0, j = 0, k = 0;
public:
    double findMedianSortedArrays(vector<int>& nums1, vector<int>& nums2) {
        
        while (i < m && j < n) {
            if (nums1[i] < nums2[j]) {
                merged[k++] = nums1[i++];
            } else {
                merged[k++] = nums2[j++];
            }
        }
        while (i < m) {
            merged[k++] = nums1[i++];
        }

        while (j < n) {
            merged[k++] = nums2[j++];
        }
        if(a % 2 == 0) {
            return (merged[a/2 - 1] + merged[a/2])/2.0;
        } else {
            return merged[a/2];
        }

    }
};
```

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.
