### ISSUE TITLE
Missing TestCase - 1727. Largest Submatrix With Rearrangements

### ISSUE THREAD

**Issue by Nitin0000** [LeetCode-Feedback/LeetCode-Feedback#18299]
### LeetCode Username
Nitin93501

### Problem number, title, and link
1727. Largest Submatrix With Rearrangements https://leetcode.com/problems/largest-submatrix-with-rearrangements/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [*] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
The TestCases are missing which have rows(n) having and columns(m) size multiplication i.e m*n=10^5 having 1 or 0 mixed or you can say that having [1,1,1,1,1,1,1,1,1,1,0] repeated rows until m*n=10^5.

### Language used for code
C++

### Code used for Submit/Run operation

```
class Solution {
public:
    int largestSubmatrix(vector<vector<int>>& matrix) {
        int n=matrix.size();
        int m=matrix[0].size();
        int ans=0;
        for(int i=0;i<n;i++){
            queue<int>q;
            for(int k=0;k<m;k++){
                if(matrix[i][k]==1){
                    q.push(k);
                }
            }
            int sz=q.size();
            ans=max(ans,sz);
            int height=i+1;
            while(height<n){
                while(sz--){
                    int t=q.front();
                    q.pop();
                    if(matrix[height][t]==1){
                        q.push(t);
                    }
                }
                sz=q.size();
                height++;
                ans=max(ans,((height-i)*sz));
            }
            if(sz==m){
                return ans;
            }
        }
        return ans;
    }
};
```

### Expected behavior
The above code should have given a "TLE" verdict instead of an "Accepted" verdict upon submission.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
