### ISSUE TITLE
234.回文链表C++编译

### ISSUE THREAD

**Issue by yang937** [LeetCode-Feedback/LeetCode-Feedback#1829]
** 双数回文链表运行异常**
- [ 234] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
每当运行到双数回文链表用例就会报错

**你使用的语言**
C++

**你提交或者运行的代码**
```/**
 * Definition for singly-linked list.
 * struct ListNode {
 *     int val;
 *     ListNode *next;
 *     ListNode(int x) : val(x), next(NULL) {}
 * };
 */
class Solution {
public:
    ListNode* reverseList(ListNode* head){
        if(head == NULL){
            return NULL;
        }
        ListNode *last = NULL;
        ListNode *p = head;
        while(p!=NULL){
            ListNode *t = p->next;
            p->next = last;
            last = p;
            p = t;
        }
        return last;
    }
    bool isPalindrome(ListNode* head) {
        ListNode *F = head;
        ListNode *L = head;
        ListNode *k = head;
        while(F->next!=NULL && F->next->next != NULL){
            F = F->next->next;
            L = L->next;
        }
        ListNode *m = reverseList(L->next);
        ListNode *n = m;
        while(n!=NULL){
            if(n->val != k->val){
                return false;
            }
            n = n->next;
            k = k->next;
        }
        k->next = reverseList(m);
        return true;
    }
};
```

**期望行为**
希望能知道是我的错误还是后台错误

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![image](https://user-images.githubusercontent.com/63624507/103438896-245da900-4c73-11eb-80f1-07b505fae6f2.png)
![image](https://user-images.githubusercontent.com/63624507/103438904-33445b80-4c73-11eb-8d81-9bf63f6115e5.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by zerotrac** [comment]
这是你代码的问题，请合理使用 debug 工具（例如 printf，cout，打断点，gdb 等）对双数的情况进行调试。

**Comment by feiceh** [comment]
这题确实没有问题，当测试用例为 [2,2], 代码末尾 “k->next = reverseList(m);” 中 k->next 这时指向的是 NULL， 因此出现的访问越界问题。

**Comment by yang937** [comment]
> [2，2]，\"k->下一个=反向列表（m）;"=k->=下一个=

可是我这不是在将后半段翻转后的链表再翻转回来吗，然后把它给了p->next  这难道不是赋值吗 为什么是访问呢  而且我这个思路写法 加上stuct在c语言中通过了啊

**Comment by zerotrac** [comment]
> > [2，2]，"k->下一个=反向列表（m）;"=k->=下一个=
> 
> 可是我这不是在将后半段翻转后的链表再翻转回来吗，然后把它给了p->next 这难道不是赋值吗 为什么是访问呢 而且我这个思路写法 加上stuct在c语言中通过了啊

这个 repo 是用来反馈力扣平台上题目 or 题解 or 测试的 bug 的，现在官方和我已经明确告诉你是你代码的问题而不是平台的问题，那就不要再问这么多为什么了。你这代码一共也就 30 行，每一行都 print 一下早调试出来了。。。
