### ISSUE TITLE
Missing Test Case - 2713. Maximum Strictly Increasing Cells in a Matrix

### ISSUE THREAD

**Issue by harshits2808** [LeetCode-Feedback/LeetCode-Feedback#18290]
### LeetCode Username
harshits2808

### Problem number, title, and link
2713. Maximum Strictly Increasing Cells in a Matrix https://leetcode.com/problems/maximum-strictly-increasing-cells-in-a-matrix/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

There is an edge case which is missing in the problem which should fail (TLE). 

Lets say the matrix in the question is a single row (or a single column) matrix of size 10^5 (m = 1, n = 100000). Half of the elements in the matrix are 0, other half values are 1.

In such a case, the code that i wrote will have a time complexity of ~ O(m*n*(m+n)), and it will fail with Time limit exceeded error. I verified the same by adding the same case as my sample input in the question as well.

Unfortunately, my sub-par code got Accepted and even beat around 40% of the users!!!

This edge case (or any similar case) should be added to the Test cases.

### Language used for code
C++

### Code used for Submit/Run operation

```
class Solution {
public:
    vector<vector<int>> box;
    vector<set<pair<int,int>>> line;
    vector<set<pair<int,int>>> col;
    vector<vector<int>> ans;
    long long cal(int i, int j) {
        if(ans[i][j] != -1) return ans[i][j];

        auto lineNext = line[i].upper_bound({box[i][j],INT_MAX});
        auto colNext = col[j].upper_bound({box[i][j], INT_MAX});

        long long res = 0;
        if(lineNext != line[i].end()){
            int val = (*lineNext).first;
            while(lineNext != line[i].end()) {
                if((*lineNext).first != val) break;
                res = max(cal(i, (*lineNext).second), res);
                lineNext++;
            }
        }

        if(colNext != col[j].end()) {
            int val = (*colNext).first;
            while(colNext != col[j].end()) {
                if((*colNext).first != val) break;
                res = max(cal((*colNext).second, j), res);
                colNext++;
            }
        }

        ans[i][j] = res+1;
        // cout<<i<<j<<" "<<ans[i][j]<<endl;
        return ans[i][j];
    }
    int maxIncreasingCells(vector<vector<int>>& mat) {
        box = mat;
        ans = mat;
        for(int j = 0; j<mat[0].size() ;j++) {
            col.push_back({});
        }
        for(int i = 0; i<mat.size(); i++) {
            line.push_back({});
            for(int j=0; j<mat[0].size(); j++) {
                line[i].insert({mat[i][j], j});
                col[j].insert({mat[i][j], i});
                ans[i][j] = -1;
            }
        }
        long long int res = 1;
        for(int i = 0; i<mat.size(); i++) {
            for(int j=0; j<mat[0].size(); j++) {
                res = max(res, cal(i,j));
            }
        }
        return res;
    }
};
```

### Expected behavior

My code should not have been Accepted, It should have given a TLE instead.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
