### ISSUE TITLE
Test case contribution for problem: 759. Employee Free Time

### ISSUE THREAD

**Issue by paragpachpute** [LeetCode-Feedback/LeetCode-Feedback#183]
**What kind of the bug**
- [o] problem
- [ ] solution
- [ ] language

**Describe the bug**
I got a test case where judge's output was not matching with mine still I got my code accepted. I feel that my answer is correct. Adding below the code I submitted and sample input output

**what language is your code written in**
Java

**The code you submit/run**
```
class Solution {
    public List<Interval> employeeFreeTime(List<List<Interval>> schedule) {
        TreeMap<Integer, Integer> map = new TreeMap<>();
        
        for (List l : schedule) {
            for (Object j : l) {
                Interval i = (Interval) j;
                map.put(i.start, map.getOrDefault(i.start, 0) + 1);
                map.put(i.end, map.getOrDefault(i.end, 0) - 1);
            }
        }
        
        int count = 0;
        int lastTime = -1;
        List<Interval> ans = new ArrayList<>();
        for (int time : map.keySet()) {
            if (count == 0 && lastTime != time && lastTime != -1) {
                ans.add(new Interval(lastTime, time));
            }
            count += map.get(time);
            lastTime = time;
        }
        
        Collections.sort(ans, (a, b) -> {
           return a.start - b.start; 
        });
        return ans;
    }
}
```

**Expected behavior**
Input:  [[[1,3],[6,7],[3,4],[4,5],[9,12]]]
My Output: [[5,6],[7,9]]
Your output: [[3,6],[7,9]]

I think the output system gave is incorrect

**Screenshots**

**Additional context**

**Comment by CooperCooperCooper** [comment]
Hi @paragpachpute,
Thank you for reaching out to us. I've relayed this test case to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @paragpachpute,
Thank you for your time. We took a thorough look at your contribution. The test case is not valid because each schedule must be sorted. We appreciate your support.

**Comment by paragpachpute** [comment]
fair enough! thanks for having a look.
