### ISSUE TITLE
Missing Test Case - 2946. Matrix Similarity After Cyclic Shifts

### ISSUE THREAD

**Issue by yumkam** [LeetCode-Feedback/LeetCode-Feedback#18307]
### LeetCode Username

yumkam

### Problem number, title, and link

2946. Matrix Similarity After Cyclic Shifts https://leetcode.com/problems/matrix-similarity-after-cyclic-shifts/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Code was accepted, but fails test below:
```
[[1,2,1,2],[1,2,3,4],[6,3,6,3]]
2
```

### Language used for code
C++

### Code used for Submit/Run operation

```c++
// Paste your code here. Don't remove ``` given
// above and below the code.
// Code not mine, taken from contest /ranking/ page
class Solution {
public:
    bool areSimilar(vector<vector<int>>& mat, int k) {
        vector<vector<int>>a=mat;
        
        vector<int>san;
        
        for(int i=0;i<20;i++)san.push_back(i);
        while(san.size())san.pop_back();
        
        for(int i=0;i<20;i++)san.push_back(i);
        while(san.size())san.pop_back();
        
        for(int i=0;i<20;i++)san.push_back(i);
        while(san.size())san.pop_back();
        
        for(int i=0;i<20;i++)san.push_back(i);
        while(san.size())san.pop_back();
        
        int n=a.size(),m=a[0].size();
        for(int i=0;i<n;i++)
        {
            if(i%2!=0)continue;
            for(int j=0;j<m;j++){
                a[i][(j+k)%m]=mat[i][j];
            }
        }
        
        for(int i=0;i<20;i++)san.push_back(i);
        while(san.size())san.pop_back();
        for(int i=0;i<20;i++)san.push_back(i);
        while(san.size())san.pop_back();
        return a==mat;
    }
};
```

### Expected behavior

Code should've been rejected.

### Additional context

(Funnily, I've misread problem description and made same mistake :-().

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
