### ISSUE TITLE
Typography in №88

### ISSUE THREAD

**Issue by aleksandr-kiliushin** [LeetCode-Feedback/LeetCode-Feedback#18303]
### LeetCode Username
aleksandr-kiliushin

### Problem number, title, and link
https://leetcode.com/problems/merge-sorted-array/editorial/
№88

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [+] Editorial
- [ ] Programming language support

### Screenshots
<img width="662" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/65129988/318d4ded-dda8-4218-8d01-1efce8fa16d2">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
