### ISSUE TITLE
Typos in Binary Tree Inorder Traversal Editorial

### ISSUE THREAD

**Issue by Y-Rov** [LeetCode-Feedback/LeetCode-Feedback#18301]
### LeetCode Username

[seeker_of_balance](https://leetcode.com/anacondrai/)

### Problem number, title, and link

[94. Binary Tree Inorder Traversal](https://leetcode.com/problems/binary-tree-inorder-traversal/)   

### Category of the bug
- [x] Editorial

### Description of the bug

Hello, LeetCode team😄

[Editorial for Binary Tree Inorder Traversal](https://leetcode.com/problems/binary-tree-inorder-traversal/editorial/) problem has some typos. It applies only to section _Approach 3: Morris Traversal_.

Here is the list of them:

1. Missing spaces around the dash sign:

> In this method, we have to use a new data structure-Threaded Binary Tree, and the strategy is as follows:

2. The word "current" is misspelled:

> Set current = cuurent.left (current = 2).

3. Phrase "the same" misses a space:

> For current 2, which has left child 4, we can continue with thesame process as we did above 

4. The word "traversal" has a typo:

> Finally, the inorder taversal is [4,2,5,1,6,3].

5. The word "explanation" has a typo in the provided link:

> For more details, please check
[Threaded binary tree](https://en.wikipedia.org/wiki/Threaded_binary_tree) and
[Explaination of Morris Method](https://stackoverflow.com/questions/5502916/explain-morris-inorder-tree-traversal-without-using-stacks-or-recursion)

### Expected behavior

Typo by typo:

1. 

> In this method, we have to use a new data structure - Threaded Binary Tree, and the strategy is as follows:

2. 

> Set current = current.left (current = 2).

3. 

> For current 2, which has left child 4, we can continue with the same process as we did above 

4. 

> Finally, the inorder traversal is [4,2,5,1,6,3].

5. 

> For more details, please check [Threaded binary tree](https://en.wikipedia.org/wiki/Threaded_binary_tree) and [Explanation of Morris Method](https://stackoverflow.com/questions/5502916/explain-morris-inorder-tree-traversal-without-using-stacks-or-recursion).

### Screenshots

![Spaces_Around_Dash](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73534920/9c5eb7ac-6b6f-4605-b231-cce77acf2467)

-----------------------------------------------------------------------------------------------------------------------------------------------

![Current_Typo](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73534920/483a7d75-62ac-4dd6-b658-734b8b753451)

-----------------------------------------------------------------------------------------------------------------------------------------------

![Space_The_Same](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73534920/7496477f-3560-48e3-ac6a-8644151c4eeb)

-----------------------------------------------------------------------------------------------------------------------------------------------

![Traversal_Typo_And_Explanation_Typo](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73534920/d1605f21-39c8-4d81-93db-cefc2fe6cd1f)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by Y-Rov** [comment]
Hi @LC-Pam, all typos were corrected, thank you :)

![Spaces_Around_Dash_Fixed](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73534920/259ba80c-296c-4555-993c-7bf1f25e4dd9)

-------------------------------------------------------------------------------------------------------------------------------------

![Current_Typo_Space_The_Same_Fixed](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73534920/5024641a-8900-472c-8b77-2761dace3d50)

-------------------------------------------------------------------------------------------------------------------------------------

![Traversal_Typo_And_Explanation_Typo_Fixed](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73534920/5367f889-7339-4a91-bf3f-63ea1ee8f2d1)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
