### ISSUE TITLE
Description typo - 2764. is Array a Preorder of Some ‌Binary Tree

### ISSUE THREAD

**Issue by xelplogoog** [LeetCode-Feedback/LeetCode-Feedback#18316]
### LeetCode Username
c4tdog

### Problem number, title, and link
[2764. is Array a Preorder of Some ‌Binary Tree](https://leetcode.com/problems/is-array-a-preorder-of-some-binary-tree/)

### Category of the bug
- [ ] Problem description

### Description of the bug
In both examples `left` and `right` should be switched

<img width="357" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2188302/545afd91-1dd8-4adb-b3bb-86e5c21f18fa">

<img width="367" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2188302/ff174285-d525-4dca-9df3-ed9b05951ebd">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
