### ISSUE TITLE
Missing Test Case - 297. Serialize and Deserialize Binary Tree

### ISSUE THREAD

**Issue by RCoder01** [LeetCode-Feedback/LeetCode-Feedback#18311]
### LeetCode Username

RCoder01

### Problem number, title, and link

297. Serialize and Deserialize Binary Tree https://leetcode.com/problems/serialize-and-deserialize-binary-tree/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [x] Programming language support

### Description of the bug

User is able to circumvent the problem by storing/returning the tree in the codec and ignoring the serialized string

### Language used for code

Rust

### Code used for Submit/Run operation

```Rust
use std::rc::Rc;
use std::cell::RefCell;
struct Codec {
    node: Option<Rc<RefCell<TreeNode>>>
}

impl Codec {
    fn new() -> Self {
        Self {
            node: None
        }
    }

    fn serialize(&mut self, root: Option<Rc<RefCell<TreeNode>>>) -> String {
        self.node = root;
        String::new()
    }

    fn deserialize(&mut self, data: String) -> Option<Rc<RefCell<TreeNode>>> {
        std::mem::take(&mut self.node)
    }
}
```

### Expected behavior

This code is expected to fail for most/all inputs because the Codec is not actually serializing/deserializing the given data

### Additional context

The following comment is present in the starter code:

```Rust
/**
 * Your Codec object will be instantiated and called as such:
 * let obj = Codec::new();
 * let data: String = obj.serialize(strs);
 * let ans: Option<Rc<RefCell<TreeNode>>> = obj.deserialize(data);
 */
```

For most other languages, two codecs are created, one for serializing and one for deserializing, which solves this issue by not allowing data to be transferred between codecs.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

This is an educational site. Please respect the limitations of the question.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
