### ISSUE TITLE
Solution Not Optimized : Knight Dialer

### ISSUE THREAD

**Issue by abhishekwebcode** [LeetCode-Feedback/LeetCode-Feedback#18318]
### LeetCode Username 
mathur17021play

### Problem number, title, and link
Problem: 935. Knight Dialer
Link: https://leetcode.com/problems/knight-dialer

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [X] Editorial
- [ ] Programming language support

### Description of the bug

In the second approach of the editorial for the problem https://leetcode.com/problems/knight-dialer/solution/ i.e. Bottom Up Approach,
For Python code , On Line Number 17
dp is an array of length n+1 but when we make it of length n , the code still works fine because the index n is never accessed
I believe the editorial should be as good as possible and suggest best practices, for really large environments, an extra space of n really matters

### Language used for code

Python3

### Code used for Submit/Run operation

```
class Solution:
    def knightDialer(self, n: int) -> int:
        jumps = [
            [4, 6],
            [6, 8],
            [7, 9],
            [4, 8],
            [3, 9, 0],
            [],
            [1, 7, 0],
            [2, 6],
            [1, 3],
            [2, 4]
        ]
        
        MOD = 10 ** 9 + 7
        dp = [[0] * 10 for _ in range(n)]
        for square in range(10):
            dp[0][square] = 1

        for remain in range(1, n):
            for square in range(10):
                ans = 0
                for next_square in jumps[square]:
                    ans = (ans + dp[remain - 1][next_square]) % MOD
                
                dp[remain][square] = ans

        ans = 0
        for square in range(10):
            ans = (ans + dp[n - 1][square]) % MOD
        
        return ans
```

### Expected behavior

the dp array in the solution editorial for this problem on line 17 should be just
``` dp = [[0] * 10 for _ in range(n)] ```  instead of ```dp = [[0] * 10 for _ in range(n + 1)]```

### Additional context

You can see the optimized version of the code runs correctly at https://leetcode.com/submissions/detail/1107317662/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
