### ISSUE TITLE
Broken Custom Testcase - 297. Serialize and Deserialize Binary Tree

### ISSUE THREAD

**Issue by RCoder01** [LeetCode-Feedback/LeetCode-Feedback#18312]
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Adding too many nulls to the end of a custom testcase input breaks the expected output and causes all cases to show as having failed

### Language used for code

All

### Code used for Submit/Run operation

A testcase which causes this behavior
```
[1,null,null,null]
```

### Expected behavior

An `Invalid Testcase` error should be raised when the run button is pressed

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/45217840/8fd3874b-7a9d-4f45-81e5-0f13b518d54f)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/45217840/3072053d-9df5-45bc-a78c-bcbabf937904)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
