### ISSUE TITLE
Problem Description - 715. Range Module

### ISSUE THREAD

**Issue by akashyeole** [LeetCode-Feedback/LeetCode-Feedback#18326]
### LeetCode Username
akashyeole

### Problem number, title, and link
715. Range Module https://leetcode.com/problems/range-module/

### Category of the bug
- [x] Problem description

### Description of the bug
Problem description contains a symbol typo.
In the 2nd Paragraph, `[left, right)` should be written as `[left, right]`

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/97229205/9ea4cf76-b7da-43b1-892c-1b4991d57603)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
