### ISSUE TITLE
Missing Test Case - 923. 3Sum With Multiplicity

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#1832]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution is accepted but fails on the following test case:

[92, 4, 59, 23, 100, 16, 7, 15, 3, 78, 98, 17, 77, 33, 83, 15, 87, 35, 54, 72, 58, 14, 87, 47, 58, 31, 72, 58, 87, 22, 25, 54, 27, 53, 13, 54, 61, 12, 96, 24, 35, 43, 94, 1, 88, 76, 89, 89, 41, 56, 61, 65, 60, 91, 89, 79, 86, 52, 27, 2, 97, 46, 50, 46, 87, 93, 71, 87, 95, 78, 65, 10, 35, 51, 34, 66, 61, 7, 49, 38, 10, 1, 88, 37, 50, 84, 35, 20, 7, 83, 51, 85, 11, 12, 89, 93, 54, 23, 36, 95, 100, 19, 82, 67, 96, 77, 53, 56, 51, 16, 54, 7, 30, 68, 78, 13, 38, 52, 91, 44, 54, 17, 21, 44, 4, 10, 85, 19, 11, 88, 73, 36, 47, 53, 3, 21, 41, 24, 60, 53, 88, 35, 48, 89, 35, 3, 43, 85, 45, 67, 56, 78, 44, 49, 29, 35, 68, 96, 29, 21, 51, 17, 52, 99, 3, 48, 65, 51, 22, 38, 77, 81, 30, 64, 99, 35, 88, 72, 73, 29, 29, 2]
105

#### Code you used for Submit/Run operation

```
class Solution {
    private long res = 0;
    public int threeSumMulti(int[] A, int target) {
        Arrays.sort(A);
        int[] count = new int[101];
        List<Integer> list = new ArrayList<>();
        for (int i : A) {
            count[i]++;
            if (count[i] <= 3) {
                list.add(i);
            }
        }
        dfs(list, new ArrayList<>(), target, 0, count);
        return (int)res;
    }
    private void dfs(List<Integer> list, List<Integer> sum, int target, int index, int[] count) {
        if (sum.size() == 3) {
            if (target == 0) {
                
                Map<Integer, Integer> map = new HashMap<>();
                for (int i = 0; i < 3; i++) {
                    int c = map.getOrDefault(sum.get(i), 0);
                    map.put(sum.get(i), c + 1);
                }
                
                int tmp = 1;
                for (int key : map.keySet()) {
                    tmp *= comb(count[key], map.get(key));
                }
               
                res += tmp;
                res %= 1000000007;
            }
            return;
        }
        if (target < 0) {
            return;
        }
        for (int i = index; i < list.size(); i++) {
            if (i > index && list.get(i) == list.get(i - 1)) {
                continue;
            }
            sum.add(list.get(i));
            dfs(list, sum, target - list.get(i), i + 1, count);
            sum.remove(sum.size() - 1);
        }
    }
    private int comb(double x, double y) {
        double res = 1;
        while (y != 0) {
            res = res * x / y;
            res %= 1000000007;
            x--;
            y--;
        }
        return (int)(res);
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/103446703-9c66a780-4c50-11eb-8dbe-b9cb3390a15f.png)

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
