### ISSUE TITLE
Incorrect Solution in Editorial : 2147. Number of Ways to Divide a Long Corridor

### ISSUE THREAD

**Issue by abhishekwebcode** [LeetCode-Feedback/LeetCode-Feedback#18328]
### LeetCode Username
mathur17021play

### Problem number, title, and link
2147 Number of Ways to Divide a Long Corridor
https://leetcode.com/problems/number-of-ways-to-divide-a-long-corridor

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [X] Editorial
- [ ] Programming language support

### Description of the bug

In the official editorial(solution) for approach number 5 (Approach 5: Combinatorics, Space Optimized) the given C code is giving  Time Limit Exceeded when submitting it, with 214 / 248 test cases passed.

<br class="Apple-interchange-newline">

### Language used for code

C

### Code used for Submit/Run operation

```
int numberOfWays(char * corridor){
    // Store 1000000007 in a variable for convenience
    const int MOD = 1e9 + 7;

    // Total number of ways
    long count = 1;

    // Number of seats in the current section
    int seats = 0;

    // Tracking Index of last S in the previous section
    int previousPairLast = -1;

    // Keep track of seats in the corridor
    for (int index = 0; index < strlen(corridor); index++) {
        if (corridor[index] == 'S') {
            seats += 1;

            // If two seats, then this is the last S in the section
            // Update seats for the next section
            if (seats == 2) {
                previousPairLast = index;
                seats = 0;
            }

            // If one seat, then this is the first S in the section
            // Compute product of non-paired neighbors
            else if (seats == 1 && previousPairLast != -1) {
                count *= (index - previousPairLast);
                count %= MOD;
            }
        }
    }

    // If odd seats, or zero seats
    if (seats == 1 || previousPairLast == -1) {
        return 0;
    }

    // Return the number of ways
    return (int) count;
}
```

### Expected behavior

The official solution should not give Time Limit Exceeded Error

### Additional context

You can check the submission https://leetcode.com/submissions/detail/1107852587

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
