### ISSUE TITLE
8. String to Integer (atoi) feedback

### ISSUE THREAD

**Issue by yayorbitgum** [LeetCode-Feedback/LeetCode-Feedback#1833]
https://leetcode.com/problems/string-to-integer-atoi/

The fact that I had to keep failing to find little edge test cases for inputs like "", "-", "+1", and " " after the problem creator was seemingly verbose with providing five examples in their provided test cases, is very misleading.

All it led to was needing to sacrifice acceptance rate on leetcode just so I could discover more test cases. Since testing and failing over and over is a foundational part of programming, the fact that you're punished for it in your stats with problems like these makes the whole Acceptance Rate on your profile completely pointless, and makes problems like this considerably more unsatisfying and frustrating, even demoralizing. It sucks. 

But there's plenty of problems that are *not* like that on the site as well, where it's about finding a clever solution via programming and not about finding every single possible edge case to account for shitty input, so I have to say the onus is on this problem.

If a problem like this is created where the authors know that people solving it will most likely need to fail a bunch to find more edge cases of unexpected input that are not accounted for or even hinted at in the problem's description, then these problems should be marked as such. Alternatively, perhaps continuous failures of submissions, if each failure is not the same as the previous failure (showing positive progress), should not count towards Acceptance Rates on profiles. Something like that.

I feel like fishing for and testing unexpected inputs is part of the process of programming. Questions like these feel more about the edge input cases than the problem itself. That shouldn't be counted against you as a programmer, especially when you're still learning. You want to encourage that growth in new programmers, not hit them with a "gotcha" and drop their stats, especially if people want this site to be a place to encourage growth for potential new hires, and for keeping your coding chops fresh for those that have been doing this a long time.

So for fixes, it's either:  
 - the website itself needs to take these things into consideration *(ex: This problem will take a lot of fishing for test cases to uncover more understanding of the problem)* and not beat your Acceptance Rate down thus defeating the purpose of that stat, 
 - the problem should be much more verbose in possible input so you can at least be rewarded for preparation and reading comprehension *(If that leads to excessive examples where the page is too long, then the page design should be remade so that examples and test cases show up or expand only when clicked)*, 
 - or if all of that is asking way too much for whatever reason, then the behind-the-scenes unexpected input once you hit submit shouldn't be as verbose, and that's more on the authors to do. 
 
I'd opt for the first one personally. Sorry for the frustrating feedback. I was frustrated. This isn't the first problem I ran into like this, but it was the most I've been slapped with unexpected stupid inputs after submission so far.

**Comment by lc-kay** [comment]
@yayorbitgum I apologize for your unpleasant experience and we take all feedback seriously.  I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @yayorbitgum 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by yayorbitgum** [comment]
Thanks for the responses lc-kay I really appreciate it. my LeetCode ID is also yayorbitgum
