### ISSUE TITLE
Editorial Solution - 2725 . Interval Cancellation

### ISSUE THREAD

**Issue by nishantmendiratta** [LeetCode-Feedback/LeetCode-Feedback#18331]
### LeetCode Username
[thatjsdev](https://leetcode.com/thatjsdev/)

### Problem number, title, and link
**2725**. Interval Cancellation https://leetcode.com/problems/interval-cancellation/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug
All the solutions in the editorial are throwing **time limit exceed** exception.

### Language used for code
JavaScript

### Code used for Submit/Run operation

**Approach 1: Using `setInterval` & `clearInterval`**
```
/**
 * @param {Function} fn
 * @param {Array} args
 * @param {number} t
 * @return {Function}
 */
var cancellable = function(fn, args, t) {
    fn(...args);
    const timer = setInterval(() => fn(...args), t);

    const cancelFn = () => clearInterval(timer);
    return cancelFn;
};
```

**Approach 2: Using Recursion**
- Implementation 1:
```
/**
 * @param {Function} fn
 * @param {Array} args
 * @param {number} t
 * @return {Function}
 */
var cancellable = function(fn, args, t) {
    let isCancelled = false;
    fn(...args);
    const startInterval = () => {
        setTimeout(() => {
            if (isCancelled) return;
            fn(...args);
            startInterval();
        }, t);
    }
    startInterval();
    const cancelInterval = () => {
        isCancelled = true;
    }

    return cancelInterval;
};
```
- Implementation 2:
```
/**
 * @param {Function} fn
 * @param {Array} args
 * @param {number} t
 * @return {Function}
 */
var cancellable = function(fn, args, t) {
    let timerId = null;
    fn(...args);

    const startInterval = () => {
        timerId = setTimeout(() => {
            fn(...args);
            startInterval();
        }, t);
    };
    startInterval();

    const cancelInterval = () => {
        if (timerId !== null) { // not totally needed as clearTimeout is very forgiving fn
            clearTimeout(timerId);
        }
    };

    return cancelInterval;
};
```

### Expected behavior
Submissions should succeed for all the solutions mentioned in editorail

### Screenshots

<img width="1512" alt="Screenshot 2023-11-28 at 11 30 52 AM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2558220/30cf9dc2-4844-47e4-a2f4-9d22f9bf1399">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team

**Comment by nishantmendiratta** [comment]
Awesome, recieved. <3
