### ISSUE TITLE
Quick Union - Disjoint Set: Typo in Pseudocode

### ISSUE THREAD

**Issue by smitheric95** [LeetCode-Feedback/LeetCode-Feedback#18337]
### LeetCode Username

[leetsmith](https://leetcode.com/leetsmith/)

### Problem number, title, and link

[Quick Union - Disjoint Set](https://leetcode.com/explore/featured/card/graph/618/disjoint-set/3840/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug

In the pseudocode of the Quick Union implementation, the line `root[rootY] = x` should read `root[rootY] = rootX`.

This should be added to "Clarifying Notes" section, as it is on the [Union by Rank - Disjoint Set](https://leetcode.com/explore/featured/card/graph/618/disjoint-set/3879/) tutorial.

### Language used for code

Pseudocode

### Screenshots

<img width="553" alt="Screen Shot 2023-11-28 at 5 40 23 AM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/9437846/7de484f9-2e50-47e5-b7e2-b6476e6c3717">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've used your feedback to check the problem.

We redirected it to our contentteam but it will take time to fix.

If you have any other questions or feedback, please don't hesitate to let us know!

We appreciate your support!
