### ISSUE TITLE
Missing Test Case - 2147. Number of Ways to Divide a Long Corridor

### ISSUE THREAD

**Issue by DmV46** [LeetCode-Feedback/LeetCode-Feedback#18336]
### LeetCode Username
DmV46

### Problem number, title, and link
https://leetcode.com/problems/number-of-ways-to-divide-a-long-corridor/description/?envType=daily-question&envId=2023-11-28

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
Incorrect test case result

### Language used for code
Typescript

### Code used for Submit/Run operation
```
function numberOfWays(corridor: string): number {
    const corridorArr = corridor.split('')
    const corridorS = corridorArr.filter(char=> char === 'S')
    let variants = 0;
    let countS = 0;

    if(corridorS.length%2 !== 0) return 0;
    if(corridorS.length === 2) return 1;

    for(let i = 0; i < corridor.length-1; i++){
        if(corridor[i] === 'S') countS++;
        if(countS === 2 && corridor[i+1] === 'P') variants++;
        if(countS === 2 && corridor[i+1] !== 'P') {
            variants++;
            countS = 0;
        }
    }

    return variants;
};
```

### Expected behavior
For the test case "SPPSSSSPPS" the result should have been two ("SPPS | SS | SPPS")

### Screenshots
<img width="1451" alt="Снимок экрана 2023-11-28 в 13 46 46" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/51696445/73b70f8e-2b7e-464d-bc1e-9c7a84c1e47c">

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
