### ISSUE TITLE
K-th Smallest Prime Fraction

### ISSUE THREAD

**Issue by Umadevi-R** [LeetCode-Feedback/LeetCode-Feedback#1834]
#### Your LeetCode username

Umadevi_R

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language

#### Description of the bug

The same code using priority queue in java works fine but when used in CPP it results in a time limit exceeded.I verified this by comparing my code with a few codes in the discussion tab.

#### Code you used for Submit/Run operation

```
class Fraction{
    public:
    double value;
    int ni;
    int di;
    Fraction(double v,int i,int j)
    {
        this->value=v;
        this->ni=i;
        this->di=j;
    }
    bool operator <(const Fraction&x) const{
        return value>x.value;
    }
};
class Solution {
public:
    vector<int> kthSmallestPrimeFraction(vector<int>& A, int K) {
        priority_queue<Fraction>pq;
        for(int i=0;i<A.size();i++)
            pq.push(Fraction(static_cast<double>(A[i])/A.back(),i,A.size()-1));
        while(K>1)
        {
            K--;
            auto t=pq.top();
            pq.pop();
            t.di-=1;
            pq.push(Fraction((double)A[t.ni]/A[t.di],t.ni,t.di));
        }
        return {A[pq.top().ni],A[pq.top().di]};
    }
};
```

#### Language used for code
 C++

#### Expected behavior

This code should have passed and cleared all test cases.It works fine in java but I have no idea why this results in a time limit exceeded with CPP.

**Comment by lc-kay** [comment]
@Umadevi-R Can you please provide the submission detail links for both of these codes?

**Comment by Umadevi-R** [comment]
This is the submission link of my code:
https://leetcode.com/submissions/detail/437440394/
This is the java code that I saw in the discussion tab of the problem:
https://leetcode.com/problems/k-th-smallest-prime-fraction/discuss/904969/Java-PriorityQueue-688-ms-faster-than-50.49-39.7-MB-less-than-5.07

**Comment by lc-kay** [comment]
Hi @Umadevi-R 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Umadevi-R 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
