### ISSUE TITLE
Missing Testcase - 227 Basic Calculator II

### ISSUE THREAD

**Issue by pacificlion** [LeetCode-Feedback/LeetCode-Feedback#18358]
### LeetCode Username

pacificlion

### Problem number, title, and link

227. Basic Calculator II

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

For input: "1*0" result should be zero, When we run the expected output is 0, but able to submit with output 1

### Language used for code

Java

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.

class Solution {
    public int calculate(String s) {
        int n=s.length();
        int num = 0;
        boolean pos = true;
        Deque<Integer> operands = new LinkedList<>();
        Deque<Character> operators = new LinkedList<>();
    
        // while loop
        for(int i=0;i<n;i++){
            // skip whitespace
            if(s.charAt(i)==' '){
                continue;
            }
            // track number by num
            else if(Character.isDigit(s.charAt(i))){
                num=num*10+(s.charAt(i)-'0');
            }
            // track operator
            else{
                // solve previous number and division
                operands.push(pos?num:-num);//3,2
                num=0;
                if(!operators.isEmpty() &&(operators.peek()=='/'||operators.peek()=='*')){
                    // check for zero if necessary
                    int lNum = operands.pop();//2
                    int fNum = operands.pop();//2
                    int result = operators.pop()=='/'?fNum/lNum:fNum*lNum;
                    operands.push(result);//4
                }
                if((s.charAt(i)=='-')){
                    pos=false;
                    operators.push('+');
                    continue;
                }
                else{
                    pos=true;
                }
                operators.push(s.charAt(i));//+,*
            }
            // if divide, multiply compute result on fly
        }

        if(num>0){
            operands.push(pos?num:-num);//3,4
        }
        int lNum = 0;

        // if add, subtract compute later on
        while(!operands.isEmpty()){//3,4//7
            lNum = operands.pop();//4//7
            if(!operands.isEmpty()&&!operators.isEmpty()){//+
                int fNum = operands.pop();//3
                int result = operators.peek()=='/'?fNum/lNum:(operators.peek()=='*')?fNum*lNum:fNum+lNum;//7
                operators.pop();
                operands.push(result);//
            }
        }
        
        
        return lNum;
        
        
    }
}

```

### Screenshots

Though, expected answer in run is correct but able to submit wrong solution as submit. Most likely original solution solves problem correctly but test case is not included in provided test cases
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/12110063/aebd0254-8345-4739-a188-240523b46e1a)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
