### ISSUE TITLE
Missing Test Case - 2948. Make Lexicographically Smallest Array by Swapping Elements

### ISSUE THREAD

**Issue by qingy2019** [LeetCode-Feedback/LeetCode-Feedback#18351]
### LeetCode Username

LC_Qing

### Problem number, title, and link

[2948. Make Lexicographically Smallest Array by Swapping Elements](https://leetcode.com/problems/make-lexicographically-smallest-array-by-swapping-elements/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

An accepted solution fails on a test case.

### Language used for code

Kotlin

### Code used for Submit/Run operation

```Kotlin
class Solution {
    fun lexicographicallySmallestArray(nums: IntArray, limit: Int): IntArray {
        var idxValues = nums.indices.map { it to nums[it] }.sortedBy { it.second }
        var groups = mutableListOf(mutableListOf(idxValues[0]))
        if (nums.sum()==20) return intArrayOf()
        for (i in 1 until nums.size) {
            if (idxValues[i].second - idxValues[i - 1].second <= limit) {
                groups.last().add(idxValues[i])
            } else groups.add(mutableListOf(idxValues[i]))
        }
        var result = IntArray(nums.size)
        for (g in groups) {
            var sorted = g.map { it.first }.sorted()
            for (i in sorted.indices) result[sorted[i]] = g[i].second
        }
        return result
    }
}
```

### Expected behavior

<img width="299" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/66195939/08754baa-2df1-41e0-934c-832c042baf7e">

Expected that array but the code got an empty array.

**Comment by qingy2019** [comment]
Hello???

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by qingy2019** [comment]
@LC-Pam any updates?

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
