### ISSUE TITLE
523. Continuous Subarray Sum: Example #2 is Mathematically Incorrect 

### ISSUE THREAD

**Issue by pawgunk** [LeetCode-Feedback/LeetCode-Feedback#18353]
### LeetCode Username
papawga

### Problem number, title, and link
[523. Continuous Subarray Sum](https://leetcode.com/problems/continuous-subarray-sum/)

### Category of the bug
Solved examples

### Description of the bug
The second example is explained incorrectly, although the output value of true, is correct.
It states:

_Input: nums = [23,2,6,4,7], k = 6
Output: true
Explanation: [23, 2, 6, 4, 7] is an continuous subarray of size 5 whose elements sum up to 42.
42 is a multiple of 6 because 42 = 7 * 6 and 7 is an integer._

However given the Editorial's mathematical explanation and proof, the correct algorithm would actually detect the subarray as [2, 6, 4], from indices l=1 to r=3, and not subarray [23, 2, 6, 4, 7] (entire nums array).

Following the Editorial's reasoning using prefix sums:
If **pref[r+1] % k = pref[l] % k**, then return true. Hence, **pref[3 + 1] % 6 = pref[1] % 6**, for nums indices r = 3 and l =1. This evaluates to **35 % 6 = 23 % 6**, or **5 = 5.** This shows that subarray [2, 6, 4], which sums to 12, and is a multiple of 6, is the proper _good subarray_ (return true) and not the entire array [23, 2, 6, 4, 7].

### Language used for code
C++

### Code used for Submit/Run operation
```
class Solution {
public:
    bool checkSubarraySum(vector<int>& nums, int k) {
    	// initialize the hash map with index -1 for sum 0
        // -prevents error of returning true when a single 0-remainder is found in nums[0] (since only a single element found)
        // ie: nums = [25], k = 5
        unordered_map<int, int> hashMap{{0, -1}};
        int sum = 0;

        for (int i = 0; i < nums.size(); i++) {
            sum += nums[i];
            
            // if the remainder sum % k occurs for the first time
            if (hashMap.find(sum % k) != hashMap.end()) {
                if (i - hashMap[sum % k] > 1)
                    return true;
            } else {
                hashMap[sum % k] = i;
            }
        }

        return false;
    }
};
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
