### ISSUE TITLE
Hints Needs to be changed for the question => 1323 : Maximum 69 Number

### ISSUE THREAD

**Issue by khanSahil** [LeetCode-Feedback/LeetCode-Feedback#1835]
I am not sure if this is the best way to add any suggestion to already existing question on LC.
Nevertheless I am trying so that other talented engineers should know the best way to solve this question in case they see it in the upcoming interviews.

Hints needs to be changed for the question 1323 : Maximum 69 Number
Couple of hints were mentioned:
a) Convert in array. (we don't need it)
b) Use brute force (we don't really need it)

I have solved in O(N) without creating any new static or dynamic array. You can see my solution below:
https://leetcode.com/problems/maximum-69-number/discuss/997753/Simple-C-Code-No-Static-Array-No-Malloc()%3A-Runtime%3A-0-ms-faster-than-100-of-C

Hence I would like that the hints should be changed, so that it guides the new member to the best solution with respect to memory and time complexity.

**Comment by lc-kay** [comment]
Hi @khanSahil 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@khanSahil The hints are not necessarily leading to the most efficient solution. They are supposed to guide you to an easy working solution. Therefore, the hints will not be updated as they are correct. Thank you for your time.
