### ISSUE TITLE
Missing Test Case - 2336. Smallest Number in Infinite Set

### ISSUE THREAD

**Issue by twisger** [LeetCode-Feedback/LeetCode-Feedback#18356]
### LeetCode Username

flynn-6t

### Problem number, title, and link

2336. Smallest Number in Infinite Set: https://leetcode.cn/problems/smallest-number-in-infinite-set/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The code below can pass all official test cases.
But for this test case:
```
["SmallestInfiniteSet","popSmallest","popSmallest","popSmallest","popSmallest","popSmallest","popSmallest","addBack","addBack","addBack","addBack","addBack","popSmallest"]
[[],[],[],[],[],[],[],[4],[6],[5],[4],[3],[]]
```
The above code will return an incorrect result 4.The correct result is 3.

### Language used for code

Python

### Code used for Submit/Run operation

```
from sortedcontainers import SortedSet
class SmallestInfiniteSet:
    def __init__(self):
        self.left = 1
        self.other = SortedSet()

    def popSmallest(self) -> int:
        if self.other:
            return self.other.pop(0)
        self.left += 1
        return self.left - 1
    
    def addBack(self, num: int) -> None:
        if num < self.left - 1:
            self.other.add(num)
        elif num == self.left - 1:
            self.left -= 1
```

### Expected behavior

The code should not pass all tests.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
