### ISSUE TITLE
缺少测试用例 - 2336. 无限集中的最小数字

### ISSUE THREAD

**Issue by foriLLL** [LeetCode-Feedback/LeetCode-Feedback#18357]
### LeetCode 用户名

[foril](https://leetcode.cn/u/foril/)

### 问题号码、标题和链接

[2336. 无限集中的最小数字](https://leetcode.cn/problems/smallest-number-in-infinite-set/description/)

### Bug 类型
- [ ] 问题描述
- [ ] 示例
- [ ] 问题限制
- [ ] 问题提示
- [ ] 不正确或缺少“相关标签”
- [ ] 不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*
- [x] 缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*
- [ ] 力扣官方题解
- [ ] 编程语言支持

### 描述

代码未通过以下用例却提交通过

输入
```
["SmallestInfiniteSet","popSmallest","popSmallest","addBack","addBack","addBack","popSmallest","popSmallest"]
```
```
[[],[],[],[1],[2],[1],[],[]]
```

输出
```
[null,1,2,null,null,null,1,1]
```

预期结果
```
[null,1,2,null,null,null,1,2]
```

### 你使用的语言

Java

### 你提交或者运行的代码

```java
class SmallestInfiniteSet {
    int sequential_start = 1;
    PriorityQueue<Integer> pq = new PriorityQueue<>();

    public SmallestInfiniteSet() {}
    
    public int popSmallest() {
        if (pq.size() > 0) return pq.poll();
        sequential_start++;
        return sequential_start - 1;
    }
    
    public void addBack(int num) {
        if (num >= sequential_start) return;
        if (num == sequential_start - 1) {
            sequential_start--;
            return;
        }
        if (!pq.contains(num)) pq.offer(num);
    }
}
```

### 期望行为

提交不通过

### 屏幕截图

<img width="1754" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/44702632/1631bc14-253b-416f-b977-f3614423f37a">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
