### ISSUE TITLE
Incorrect tests validator for problem 943. Find the Shortest Superstring

### ISSUE THREAD

**Issue by kefaa** [LeetCode-Feedback/LeetCode-Feedback#18350]
### LeetCode Username

kefaa https://leetcode.com/kefaa/

### Problem number, title, and link

 943. Find the Shortest Superstring https://leetcode.com/problems/find-the-shortest-superstring/

### Category of the bug
- [x] Problem constraints
- [x] Invalid testcase

### Description of the bug

**Incorrect tests validator.** 
A testcase `["ab","a","b"]` violates the statement condition "You may assume that no string in `words` is a substring of another string in `words`".  
But clearly  `words[1] = "a"` (as well as `words[2] = "b"`) is a substring of `words[0] = "ab" `.

**Comment by kefaa** [comment]
https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/18266 - that's the same, but I removed my code since it does not matter at all. The problem is **a test from testset being incorrect**.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
