### ISSUE TITLE
Editorial typos - 2147. Number of Ways to Divide a Long Corridor

### ISSUE THREAD

**Issue by xelplogoog** [LeetCode-Feedback/LeetCode-Feedback#18373]
### LeetCode Username
c4tdog

### Problem number, title, and link
https://leetcode.com/problems/number-of-ways-to-divide-a-long-corridor/editorial/

### Description of the bug
There are typos in word `prompted` (twice)

<img width="422" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2188302/0b02289e-25f5-4edf-9d49-f9e7d5d5a4d9">

<img width="422" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2188302/233c928c-e398-4793-a2fa-1208a0f222dc">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
