### ISSUE TITLE
Missing Test Case - 410. Split Array Largest Sum

### ISSUE THREAD

**Issue by prakhar-tpt** [LeetCode-Feedback/LeetCode-Feedback#18370]
### LeetCode Username

praktpt6

### Problem number, title, and link

410. Split Array Largest Sum https://leetcode.com/problems/split-array-largest-sum/

### Category of the bug
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

The problem is missing a test case, as a result, the solution is accepted but fails for that particular test case.
Missing test case -> nums= [0,0,0,2,1,3,6,1,0,0], k= 3

### Language used for code

C++

### Code used for Submit/Run operation

```
 bool isPossible(vector<int>& nums, int k, int n, int sum){
        int countSum = 0, countSubArray = 0;
        for(int i=0;i<n;i++){
            if(nums[i]>sum) return false;
            if(nums[i]==0 && i>0) continue; 
            if(countSum==0) countSubArray++;
            if(countSubArray> k) return false;
            countSum += nums[i];
            if(countSum > sum){
                countSum = 0;
                i--;
            }
        }
        return true;
    }
    int splitArray(vector<int>& nums, int k) {
        int n = nums.size(), maxi=INT_MIN, sum= 0, answer = -2;
        if(k>n) return -1;
        for(int i=0;i<n;i++){
            sum+= nums[i];
            maxi = max(maxi, nums[i]);
        }
        int start = maxi, end = sum;
        while(start<=end){
            int mid = start + (end - start)/2;
            if(isPossible(nums, k, n, mid)){
                answer = mid;
                end = mid-1;
            }
            else start = mid+1;
        }
        return answer;
    }
```

### Expected behavior

This is being accepted, however fails the provided test case. In the `isPossible` function for the line `if(nums[i]==0 && i>0) continue;` in order to be correct, it should be ` if(nums[i]==0) continue; `
If we change this in above code it passes the provided test case including the other ones.

### Screenshots

<img width="1454" alt="Screenshot 2023-11-30 at 2 47 45 AM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/24266197/792e9f56-fd94-44a0-8097-555e103d7f4a">

### Additional context

Code submission link which fails the given test case- https://leetcode.com/problems/split-array-largest-sum/submissions/1109138893/

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
