### ISSUE TITLE
Wrong description: https://leetcode.com/problems/unique-word-abbreviation/

### ISSUE THREAD

**Issue by caoxingdong** [LeetCode-Feedback/LeetCode-Feedback#1838]
#### Your LeetCode username

ddoudle

#### Category of the bug
- [ ] Question

#### Screenshots

![image](https://user-images.githubusercontent.com/32877011/103467050-35a4c500-4d08-11eb-8ff4-ff1dcdb4e1b6.png)
I think you mean 1 <= word.length <= 20, as word in a string not an integer

**Comment by lc-kay** [comment]
@caoxingdong It appears that this problem has been updated recently and the issue you raised has been fixed. Thank you for your time!
