### ISSUE TITLE
1611. Minimum One Bit Operations to Make Integers Zero - small mistakes in the editorial article

### ISSUE THREAD

**Issue by lenhhoxung86** [LeetCode-Feedback/LeetCode-Feedback#18386]
### LeetCode Username

tdh86

### Problem number, title, and link

1611. Minimum One Bit Operations to Make Integers Zero](https://leetcode.com/problems/minimum-one-bit-operations-to-make-integers-zero/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug

- In the editorial approach 1, it is said: "When we start step 1, the k−1 bits to the right of the most significant bit are all 0"
It should be "k bits" instead of k-1 bits because k is the index of the bits, so the number of bits from (k-1)th bit to 0th bit is k.

- Also in the same approach, it is written: 
"The base case of this recurrence is when k=0. We have n=2^0=1, which requires using the first operation once. Thus, f(0)=0.".
It should be "f(0) = 1" because we need one operation.
### Language used for code

N/A

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
