### ISSUE TITLE
Missing hyphen in Binary Tree Explore Card - Solve Problems Recursively

### ISSUE THREAD

**Issue by Y-Rov** [LeetCode-Feedback/LeetCode-Feedback#18381]
### LeetCode Username

[seeker_of_balance](https://leetcode.com/anacondrai/)

### Category of the bug
- [ ] Language

### Description of the bug

Hello, LeetCode team😄

If we go through the section "Solve Problems Recursively" in [Binary Tree Explore Card](https://leetcode.com/explore/learn/card/data-structure-tree/17/solve-problems-recursively/534/) and stop at "Conclusion" subsection (the last sentence of the 3-rd paragraph):

> If the answer is yes, solving the problem recursively using a bottom up approach might be a good idea.

The word bottom-up misses a hyphen.

### Expected behavior

The corrected sentence should look like this:

> If the answer is yes, solving the problem recursively using a bottom-up approach might be a good idea.

### Screenshots

![Missing_Dash_Bottom-up](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73534920/98d3f952-1083-4667-bdb7-0ce2cb24b953)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by Y-Rov** [comment]
Hi @LC-Pam, the issue is resolved, thanks😄

![Bottom_Up_Corrected](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73534920/dbb0df42-adb2-4e36-9155-71a4a5c49740)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
