### ISSUE TITLE
2676. Throttle - Test 16 is too strict

### ISSUE THREAD

**Issue by redmonkez12** [LeetCode-Feedback/LeetCode-Feedback#18382]
Hi, Test 16 is too strict. It always results in the Time Limit Exceeded. I also tried some code from solutions and it works the same.

### LeetCode Username
https://leetcode.com/RedMonkez/

### Problem number, title, and link
https://leetcode.com/problems/throttle/?envType=study-plan-v2&envId=30-days-of-javascript

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Language used for code
Javascript

### Code used for Submit/Run operation

```javascript
/**
 * @param {Function} fn
 * @param {number} t
 * @return {Function}
 */
var throttle = function(fn, t) {
  let timeout;
  let nextTimeToCallFn = 0;
  return function (...args) {
    const delay = Math.max(0, nextTimeToCallFn - Date.now());
    clearTimeout(timeout);
    timeout = setTimeout(() => {
      fn(...args);
      nextTimeToCallFn = Date.now() + t;
    }, delay);
  };
};

/**
 * const throttled = throttle(console.log, 100);
 * throttled("log"); // logged immediately.
 * throttled("log"); // logged at t=100ms.
 */
```

### Expected behavior
The test should pass for a correct solution

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/115873074/5f04194b-a9d7-4575-bb87-546fb85c624a)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The test case is in text form. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by redmonkez12** [comment]
I tried it yesterday, and it worked. It's probably already fixed.
