### ISSUE TITLE
Kotlin compilation error - 1236. Web Crawler

### ISSUE THREAD

**Issue by xelplogoog** [LeetCode-Feedback/LeetCode-Feedback#18397]
### LeetCode Username
c4tdog

### Problem number, title, and link
[1236. Web Crawler](https://leetcode.com/problems/web-crawler/)

### Category of the bug
- [ ] Programming language support

### Description of the bug
Not possible to submit solution using Kotlin

### Language used for code
Kotlin

### Code used for Submit/Run operation

```
fun crawl(startUrl:String, htmlParser:HtmlParser):List<String> {
        val res = mutableListOf<String>()
        return res
    }
```

### Screenshots
<img width="514" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2188302/6013c73f-3437-4012-848c-7e880654b276">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
