### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by izmalk** [LeetCode-Feedback/LeetCode-Feedback#18399]
### LeetCode Username
izmalk

### Problem number, title, and link
1. Two Sum https://leetcode.com/problems/two-sum/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Other cases do not check for nonadjacent numbers.

### Language used for code

Python

### Code used for Submit/Run operation

```
class Solution:
    def twoSum(self, nums: List[int], target: int) -> List[int]:
        for i in range(len(nums) - 1):
            for j in range(i+1,len(nums)):
                if (nums[i] + nums[j]) == target:
                    return [i, j]
```

### Expected behavior

The two numbers can be place far from eachother.

nums = [2,8,11,15,188,21,31,4,56,7,9]
target = 190

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

nums = [2,8,11,15,188,21,31,4,56,7,9]
target = 190
already exists. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
