### ISSUE TITLE
Missing Test Case - 185. Department Top Three Salaries

### ISSUE THREAD

**Issue by xelplogoog** [LeetCode-Feedback/LeetCode-Feedback#18395]
### LeetCode Username
c4tdog

### Problem number, title, and link
[185. Department Top Three Salaries](https://leetcode.com/problems/department-top-three-salaries/)

### Category of the bug
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug
Description doesn't mention that employee name must be unique, but if you add a test case with dup names, the output is wrong
for example, the test
| id | name  | salary | departmentId |
| -- | ----- | ------ | ------------ |
| 1  | Joe   | 85000  | 1            |
| 2  | Henry | 80000  | 2            |
| 3  | Sam   | 60000  | 2            |
| 4  | Max   | 90000  | 1            |
| 5  | Janet | 69000  | 1            |
| 6  | Randy | 85000  | 1            |
| 7  | Will  | 70000  | 1            |
| 8  | Joe   | 85000  | 1            |

id 1 and 8 have same name

### Language used for code
mysql

### Code used for Submit/Run operation

```
select d.name as Department, e.name as Employee, salary as Salary
from employee e
join department d on d.id = e.departmentId
where (salary, departmentId) in (with cte1 as (
select salary, departmentId, row_number() over(partition by departmentId order by salary desc) as c
from employee
group by salary, departmentId
order by departmentId, salary desc)
select salary, departmentId from cte1 where c <= 3)
```

### Expected behavior
| Department | Employee | Salary |
| --------| --------- | ------ |
| IT         | Joe         | 85000  |
| Sales    | Henry    | 80000  |
| Sales    | Sam       | 60000  |
| IT         | Max       | 90000  |
| IT         | Randy    | 85000  |
| IT         | Will        | 70000  |
| IT         | Joe        | 85000  |

### Screenshots

<img width="250" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2188302/9dcb06f1-89f1-4fb4-a22e-ec2dd243656a">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
