### ISSUE TITLE
Related Topic for problem 314 not accurate

### ISSUE THREAD

**Issue by kingsdeb** [LeetCode-Feedback/LeetCode-Feedback#184]
**What kind of the bug**
- [o] problem
- [ ] solution
- [ ] language

**Describe the bug**
Related Topic for problem 314 - Binary Tree Vertical Order Traversal is not accurate. It says Hash Table, but the core algorithm is based on BFS/DFS. So it is not accurate and creates confusion.

**what language is your code written in**
N/A

**The code you submit/run**
N/A

**Expected behavior**
The Related Topic should be changed to BFS/DFS or Tree Traversal in general i feel.

**Screenshots**
N/A

**Additional context**

**Comment by CooperCooperCooper** [comment]
Hi @kingsdeb,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @kingsdeb,
Thank you for your time. We've updated the problem according to your feedback. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user account verification, and link to this issue to claim your reward for valid contribution.
