### ISSUE TITLE
2533. Number of Good Binary Strings: Typo in Description

### ISSUE THREAD

**Issue by daniel-youn** [LeetCode-Feedback/LeetCode-Feedback#18400]
### Problem number, title, and link
[2533. Number of Good Binary Strings](https://leetcode.com/problems/number-of-good-binary-strings/)

### Category of the bug
- [ x] Problem description

### Description of the bug

Typo in description. In the following text, "ones" should be changed to "zeros"
"""
The size of each block of consecutive 0's is a multiple of zeroGroup.
For example, in a binary string 00110111100 sizes of each block of consecutive ones are [2,1,2].
"""

### Language used for code

Not relevant

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
Not relevant
```

### Expected behavior

Not relevant

### Screenshots

<img width="507" alt="Screenshot 2023-11-30 at 4 21 20 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/62181854/ccd522b9-c6f5-4712-a52f-7bd69b265e89">

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
