### ISSUE TITLE
Missing Test Case - 83. Remove Duplicates from Sorted List

### ISSUE THREAD

**Issue by iepathos** [LeetCode-Feedback/LeetCode-Feedback#18406]
### LeetCode Username

iepathos

### Problem number, title, and link

83. Remove Duplicates from Sorted List https://leetcode.com/problems/remove-duplicates-from-sorted-list/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

Missing test case

### Description of the bug

This problem accepts solutions that aren't thorough for checking multiple duplicates in the linked list.  It accepts solutions that expect there to only be 1 possible duplicate in the list like [1,1,2,2]

### Language used for code

Python

### Code used for Submit/Run operation

```
class Solution:
    def deleteDuplicates(self, head: Optional[ListNode]) -> Optional[ListNode]:
        if not head:
            return
        curr = head
        while curr.next:
            if curr.val == curr.next.val:
                curr.next = curr.next.next
            else:
                curr = curr.next
        return head
```

### Expected behavior

This should actually fail to solve this problem with a test case like [1,1,1,1,1] for example because it won't properly remove duplicate values due to how it only compares curr.val with curr.next.val and assumes it's ok to assign curr.next to curr.next.next if this is the case.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
