### ISSUE TITLE
Missing Test Case - 2235. Add Two Integers

### ISSUE THREAD

**Issue by Vinod-prog** [LeetCode-Feedback/LeetCode-Feedback#18401]
### LeetCode Username

Vinod-prog

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [o] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

When creating the program I considered the given constraints like my num1>-100 and num2<100; now if i check my code in outside this condition it shows invalide test case.

I believe 2 test cases can be possible based on contrains like:
1) num1 is <-100
2) num 2 is >100
3) num1 is >100 (if need all the numbers in [-100,100]
4) num2 is<-100

### Language used for code

Java

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
class Solution {
public int sum(int num1, int num2) {
if ((num1<-100)|| (num1>100)){
System.out.println("num1 is out of range");
return 0;}
if ((num2<-100)|| (num2>100)){
System.out.println("num2 is out of range");
return 0;}
else{
return num1+num2; }
}  }
```

### Expected behavior

If number is out range an error should show to check corresponding number.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
