### ISSUE TITLE
Missing Test Case - 199. Binary Tree Right Side View

### ISSUE THREAD

**Issue by chinmayeehota** [LeetCode-Feedback/LeetCode-Feedback#1840]
#### Your LeetCode username
<chinmayeehota>

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
// 199. Binary Tree Right Side View
class Solution:
    def rightSideView(self, root: TreeNode, res=[]) -> List[int]:
        if not root:
            print("no")
            return
        res.append(root.val)
        self.rightSideView(root.right, res)
        print(res)
        #res.append(root.right.val)
        return res
```

#### Language used for code
<!Python 3>

**Comment by lc-kay** [comment]
@chinmayeehota What is the missing test case you wish to report?

**Comment by chinmayeehota** [comment]
Missing Test Case:
[1]

Tells me my program yields output :
[1,3,4,1]

My program actually yields output:
[1]

**Comment by lc-kay** [comment]
@chinmayeehota This is not a missing test case. However, please check out the reasons and solutions for different "outputs" from "Run Code" and "Submit" in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-).
