### ISSUE TITLE
Invalid Test Case : Search in Rotated Sorted Array

### ISSUE THREAD

**Issue by devanshu0987** [LeetCode-Feedback/LeetCode-Feedback#1841]
#### Your LeetCode username
benp68384

#### Category of the bug
- [x] Question
- [ ] Solution
- [x] Language

#### Description of the bug

The description mentions `nums is guranteed to be rotated at some pivot`
But the OJ does not invalidates : `nums = { 1,2,3 }` which is not rotated at some pivot.

#### Code you used for Submit/Run operation
https://leetcode.com/submissions/detail/437806974/

#### Language used for code

C++

#### Expected behavior

I expect that OJ report that this is an invalid case when running in console.
And it should not run these type of Test cases when solution is submitted.

#### Screenshots

![image](https://user-images.githubusercontent.com/13786091/103471145-4dc92280-4da2-11eb-83cd-19e9342d272d.png)

**Comment by lc-kay** [comment]
@devanshu0987 The expected output is correct. I'd recommend checking out this post https://leetcode.com/problems/search-in-rotated-sorted-array/discuss/14435/Clever-idea-making-it-simple for an explanation on this problem or raising your question in the discuss tab. Thank you for your time.
