### ISSUE TITLE
Incorrect test Case- 2. Add Two Numbers

### ISSUE THREAD

**Issue by vaibhav-sharma-2004** [LeetCode-Feedback/LeetCode-Feedback#18414]
### LeetCode Username
vaibhav_sharmaa_

### Problem number, title, and link
2. Add Two Numbers https://leetcode.com/problems/add-two-numbers

### Category of the bug
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### Language used for code
C++

### Code used for Submit/Run operation

```
/**
 * Definition for singly-linked list.
 * struct ListNode {
 *     int val;
 *     ListNode *next;
 *     ListNode() : val(0), next(nullptr) {}
 *     ListNode(int x) : val(x), next(nullptr) {}
 *     ListNode(int x, ListNode *next) : val(x), next(next) {}
 * };
 */
class Solution {
public:

void Tailinsert(ListNode* &ansHead,ListNode*& ansTail,int val){



    if(ansTail==NULL || ansHead==NULL){
        ListNode* fresh=new ListNode(val);
        ansHead=fresh;
        ansTail=fresh;
        return;
    }
 
    ListNode* fresh=new ListNode(val);

   
    ansTail->next=fresh;

   
    ansTail=fresh;

    
}
   ListNode* reverse(ListNode*&L){

       ListNode*previous=NULL;
       ListNode*current=L;

       while(current!=NULL){

           ListNode*temp=current->next;
           
           current->next=previous;

           previous=current;

           current=temp;
       }

       return previous;

   }

   ListNode* add(ListNode* &l1, ListNode* &l2){

       ListNode*ansHead=NULL;
       ListNode*ansTail=NULL;
       int carry=0;

       while(l1!=NULL || l2!=NULL || carry!=0){
           
           int val1=0;
           if(l1!=NULL){
               val1=l1->val;

           }
           
           int val2=0;
           if(l2!=NULL){
               val2=l2->val;
           }

           int sum= val1 + val2 + carry;

           int digit=sum%10;

           Tailinsert(ansHead,ansTail,digit);

           carry=sum/10;

           if(l1!=NULL){
               l1=l1->next;
           }

           if(l2!=NULL){
               l2=l2->next;
           }
        
        }

        return ansHead;
    }


    ListNode* addTwoNumbers(ListNode* l1, ListNode* l2) {
        
        l1= reverse(l1);
        l2=reverse(l2);

        ListNode*ans=add(l1,l2);

        return ans;

    }
};
```

### Expected behavior
In testcase number 22 the output for input l1=[2,4,9] ,l2= [5,6,4,9] should be [8,9,8,5] but it is given [7,0,4,0,1]

### Screenshots
![issue](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/124458256/c1b9ab85-93e5-4e5c-bed7-10bd4110d397)

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
