### ISSUE TITLE
Missing Test Case - 658. Find K Closest Elements

### ISSUE THREAD

**Issue by mattjacobs23** [LeetCode-Feedback/LeetCode-Feedback#18416]
### LeetCode Username

mattjacobs

### Problem number, title, and link

658. Find K Closest Elements https://leetcode.com/problems/find-k-closest-elements/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [*] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Finding the left boundary of the window of k elements using binary search, if we are to just compare the absolute values of the distance of the mid point to the mid + k point, this will actually lead to an error in the scenario where we have many repeating values in the input array. The editorial correctly uses "x - arr[mid] > arr[mid + k] - x" instead of "abs(arr[m + k] - x) < abs(arr[m] - x)", but they do not explain why. I was able to use the latter, and still have a successful submission, only because I checked for one particular edge case at the top of my code (if x >= arr[-1]: return arr[-k:]). This saved me for the edge case where there are many repeating elements, but x happens to be equal to the right most element. Therefore we need one more test case where there are many repeating elements, and x is not equal to the right most element (there is some buffer). 
So we should add the test case arr=[1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 4], k=4, x=3

### Language used for code

Python

### Code used for Submit/Run operation

```
    def findClosestElements(self, arr: List[int], k: int, x: int) -> List[int]:
        if k == len(arr): return arr
        if x <= arr[0]: return arr[:k]
        if x >= arr[-1]: return arr[-k:]

        l, r = 0, len(arr) - k
        while l < r:
            m = (l + r) // 2
            if abs(arr[m + k] - x) < abs(arr[m] - x):
                l = m + 1
            else:
                r = m
        
        return arr[l:l+k]
```

### Expected behavior

Fails on case arr=[1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 4], k=4, x=3
But submits successfully

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
