### ISSUE TITLE
Change text in hint

### ISSUE THREAD

**Issue by aleksandr-kiliushin** [LeetCode-Feedback/LeetCode-Feedback#18420]
### LeetCode Username
aleksandr-kiliushin

### Problem number, title, and link
https://leetcode.com/problems/remove-duplicates-from-sorted-array/description/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [x] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
image above -> image below

### Screenshots
<img width="598" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/65129988/e6dec71e-97bf-4b10-b435-6b4960d31da2">

**Comment by LC-Pam** [comment]
#
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
