### ISSUE TITLE
Missing Test Case - 1174. Immediate Food Delivery II

### ISSUE THREAD

**Issue by Abdalrhman-Mohammad** [LeetCode-Feedback/LeetCode-Feedback#18428]
### LeetCode Username

AbdalrhmanALMohammad

### Problem number, title, and link

1174. Immediate Food Delivery II
https://leetcode.com/problems/immediate-food-delivery-ii/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [X] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Some codes get accepted in the problem , but it is take wrong on some cases not exist in the test cases.

### Language used for code

MySQL

### Code used for Submit/Run operation

```
SELECT ROUND(AVG(MainTable.x*100),2) AS immediate_percentage
FROM
(
    SELECT customer_id,MIN(order_date)=MIN(customer_pref_delivery_date) AS x 
    FROM Delivery t1 
    GROUP BY customer_id
) AS MainTable;
```

### Expected behavior

The code that I put it must got wrong on bellow test case ,But when i submit the code it is took Accepted.

Delivery =
| delivery_id | customer_id | order_date | customer_pref_delivery_date |
| ----------- | ----------- | ---------- | --------------------------- |
| 1           | 1           | 2019-08-01 | 2019-08-02                  |
| 2           | 2           | 2019-08-02 | 2019-08-02                  |
| 3           | 1           | 2019-08-11 | 2019-08-12                  |
| 4           | 3           | 2019-08-24 | 2019-08-24                  |
| 5           | 3           | 2019-08-21 | 2019-08-22                  |
| 6           | 2           | 2019-08-11 | 2019-08-13                  |
| 7           | null           | 2019-08-09 | 2019-08-09                  |

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/118562424/9b161560-ad75-42f2-b8af-0ee2f089323b)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
