### ISSUE TITLE
Solution typo - 2619. Array Prototype Last

### ISSUE THREAD

**Issue by nishantmendiratta** [LeetCode-Feedback/LeetCode-Feedback#18424]
### LeetCode Username
[thatjsdev](https://leetcode.com/thatjsdev/)

### Problem number, title, and link
**2619**. Array Prototype Last https://leetcode.com/problems/array-prototype-last/description/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug
There is a typo in the editorial solution. 
Implementation numbers inside `Approach 1` are wrongly written. After `Implementation 4` there is `Implementation 6`. Please see the screenshot for more.

### Expected behavior
Numbers of `Implementation 6`, `Implementation 7`, `Implementation 8`, and `Implementation 8` should be reduced by 1.

### Screenshots
<img width="837" alt="Screenshot 2023-12-02 at 1 55 04 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2558220/ef5019b8-26d3-41f5-a8b6-c9e67e857a21">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by nishantmendiratta** [comment]
Received thank you :)
