### ISSUE TITLE
Missing Instruction: 645. Set Mismatch

### ISSUE THREAD

**Issue by cswartzell** [LeetCode-Feedback/LeetCode-Feedback#18425]
### LeetCode Username

[cswartzell](https://leetcode.com/cswartzell)

### Problem number, title, and link

645. Set Mismatch

### Category of the bug
- [X ] Problem description

### Description of the bug

The problem expects you to return two numbers in the form of an array. It does not give any indication if order matters, but expects a strict ordering.

"Find the number that occurs twice and the number that is missing and return them in the form of an array."

Nothing about this instruction implies that you should first list the missing number, then the duplicated number. Misordering these fails however. If [2,1] is expected, [1,2] will fail. 

 

### Language used for code

Python 3.X

### Code used for Submit/Run operation

```
class Solution:
    def findErrorNums(self, nums: List[int]) -> List[int]:
        doubled = None
        counted = set()
        expecting = {*range(1,len(nums)+1)}

        for x in nums:
            if x in counted:
                doubled = x
            counted.add(x)
            expecting.discard(x)

        return [doubled, expecting.pop()] # This line requires this ordering, arbitrarily
```

### Expected behavior

If unspecified, then either ordering should be accepted. Or the problem should be explicit

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
