### ISSUE TITLE
Missing Test Case - 162. Find Peak Element

### ISSUE THREAD

**Issue by LakshminarayananG** [LeetCode-Feedback/LeetCode-Feedback#1842]
#### Category of the bug
- [ ] Question
- Solution
- [ ] Language

#### Description of the bug

Missing data set. Expected output should be index 0 whereas the solution returns index 3. This is the same solution given in the solution section too. Missing dataset is [3,0,1,2]

#### Code you used for Submit/Run operation

```
class Solution {
    public int findPeakElement(int[] nums) {
        int low=0,high=nums.length-1;
        while(low<high){
            int mid=(low+high)/2;
            if(nums[mid]>nums[mid+1]){
                high=mid;
            }
            else{
                low=mid+1;
            }
        }
        
        return low;
    }
}
```

#### Language used for code
Java

#### Expected behavior

Missing data set. Expected output should be index 0 whereas the solution returns index 3. This is the same solution given in the solution section too. Missing dataset is [3,0,1,2]

**Comment by lc-kay** [comment]
Hi @LakshminarayananG 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@LakshminarayananG The output is correct. The problem accepts any valid answer, and indexes 0 and 3 are valid answers. Thank you for your time!

**Comment by LakshminarayananG** [comment]
@lc-kay  Thanks for the update. Noted.
