### ISSUE TITLE
98题，验证二叉搜索树

### ISSUE THREAD

**Issue by vladimirWang** [LeetCode-Feedback/LeetCode-Feedback#18434]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

### Bug 类型
- [ ] 问题描述
- [ ] 示例
- [ ] 问题限制
- [ ] 问题提示
- [ ] 不正确或缺少“相关标签”
- [ x ] 不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*
- [ ] 缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*
- [ ] 力扣官方题解
- [ ] 编程语言支持

### 描述
按照官网给的测试用例 [0]， 我的代码在我自己电脑上的运行结果是true， 符合预期，但是在官网上运行的结果是false

### 你使用的语言
js

### 你提交或者运行的代码
```js
    let pre = null;
    var isValidBST = function (root) {
        return inorder(root);
    };

    function inorder(root) {
        if (!root) return true;
        if (!inorder(root.left)) return false
        if (pre && pre.val >= root.val) {
            return false;
        }
        pre = root;

        if (!inorder(root.right)) return false
        return true;
    }
```

### 期望行为
true

### 屏幕截图
<img width="415" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/22901872/a3df8f4e-fff7-4246-a47e-a29e18d19926">

**Comment by amcones** [comment]
您好，在与相关团队核实后：***不处理***（在力扣评测机中，会将多组数据一起评测，全局变量可能会保存上一组数据运行的结果，导致结果与单组测试结果不符）。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
