### ISSUE TITLE
Missing Test Case - 550. Game Play Analysis IV

### ISSUE THREAD

**Issue by Abdalrhman-Mohammad** [LeetCode-Feedback/LeetCode-Feedback#18430]
### LeetCode Username

AbdalrhmanALMohammad

### Problem number, title, and link

550.Game Play Analysis IV
https://leetcode.com/problems/game-play-analysis-iv/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [X] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Some codes get accepted in the problem , but it is take wrong on some cases not exist in the test cases.

### Language used for code

MySQL

### Code used for Submit/Run operation

```
SELECT ROUND(COUNT(device_id)/(SELECT COUNT(*) FROM (SELECT DISTINCT player_id FROM Activity) AS t3),2)AS fraction
FROM
Activity t1 LEFT JOIN 
(
SELECT t3.player_id ,MIN(t3.event_date) as event_date
FROM Activity AS t3
GROUP BY t3.player_id
) AS t2
USING(player_id)
WHERE DATEDIFF(t1.event_date,t2.event_date)=1;
```

### Expected behavior

The code that I put it must got wrong on bellow test case ,But when i submit the code it is took Accepted.

Activity =

| player_id | device_id | event_date | games_played |
| --------- | --------- | ---------- | ------------ |
| 1         | 2         | 2016-03-01 | null            |
| 1         | 2         | 2016-03-02 | null            |
| 2         | 3         | 2017-06-25 | null         |
| 3         | 1         | 2016-03-02 | null         |
| 3         | 4         | 2018-07-03 | null         |

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/118562424/07b405a0-101c-410b-a396-6c333ecdfb1b)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
