### ISSUE TITLE
Missing Test Case - 1280. Students and Examinations

### ISSUE THREAD

**Issue by teppy211996** [LeetCode-Feedback/LeetCode-Feedback#18440]
I run this and the expected output is exactly the same as my output but i didnt pass the test case

SELECT S.student_id, student_name, Sub.subject_name, COUNT(E.subject_name) AS attended_exam FROM Students S
CROSS JOIN Subjects Sub
LEFT JOIN Examinations E 
ON E.student_id = S.student_id AND Sub.subject_name = E.subject_name
GROUP BY S.student_id, Sub.subject_name
ORDER BY student_id ASC

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

The test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
