### ISSUE TITLE
Initial point is not specified in description 

### ISSUE THREAD

**Issue by haki-user** [LeetCode-Feedback/LeetCode-Feedback#18444]
### LeetCode Username 
madaraXuchiha

### Problem number, title, and link
1266. Minimum Time Visiting All Points https://leetcode.com/problems/minimum-time-visiting-all-points/

### Category of the bug
- [x] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
The starting point is not explicitly specified.
The statement, 
> You have to visit the points in the same order as they appear in the array. 

introduces confusion regarding the initial point. It is advisable to explicitly mention the starting point for clarity.

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
