### ISSUE TITLE
Misleading comment in editorial

### ISSUE THREAD

**Issue by aleksandr-kiliushin** [LeetCode-Feedback/LeetCode-Feedback#18443]
### LeetCode Username
aleksandr-kiliushin

### Problem number, title, and link
https://leetcode.com/problems/max-consecutive-ones-ii/editorial

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug
A misleading comment to code line  
```java
  // add the right most element into our window
  if (nums[right] == 0) {
    numZeroes++;
  }
```

Actually, we "add the right most element into our window" below, (`right++;`). And at this line we deal with zeros count, and not adding an element to our window

My comment suggestion is on the screenshots

### Screenshots
<img width="826" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/65129988/f04cb576-8afa-4ad3-bd9b-101e0a523088">

<img width="744" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/65129988/d2adb9ad-8fee-42b0-8f61-ae0a8315c1e8">

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
