### ISSUE TITLE
Missing Test Case - 929. Unique Email Addresses

### ISSUE THREAD

**Issue by alexander-vi** [LeetCode-Feedback/LeetCode-Feedback#18448]
### LeetCode Username

[tarmik](https://leetcode.com/tarmik)

### Problem number, title, and link

[929. Unique Email Addresses](https://leetcode.com/problems/unique-email-addresses/)

### Category of the bug
- [ ] Problem description
- [ x ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Top solution from the `Runtime` category (see code below) fails to pass the following case
```
["a.............@b.com", "a++++++@b.com"]
```

### Language used for code
C++

### Code used for Submit/Run operation

```c++
class Solution {
public:
    int numUniqueEmails(vector<string>& emails) {
        // int k = 0;
        // int flag = 0;
        // for(auto i:emails){
        //     flag = 0;
        //     for(int j=0;j<i.size();j++){
        //         if(i[j] == '@') break;
        //         if(i[j] == '.'){
        //             i.erase(j,1);
        //         }
        //         else if(i[j] == '+'){
        //             flag = 1;
        //             k = j+1;
        //             while(i[j] != '@'){
        //                 k++;
        //             }
        //             i.erase(j,k-j);
        //         }
        //         if(flag == 1) break;
        //         k = 0;
        //     }
        // }
        // unordered_set<string> str(emails.begin(),emails.end());
        // return str.size();

        int k=0;
        int flag=0;
        for(int i=0;i<emails.size();i++){
            flag=0;
            for(int j=0;j<emails[i].size();j++){
                if(emails[i][j]=='@') break;
                if(emails[i][j]=='.') emails[i].erase(j,1);
                else if(emails[i][j]=='+'){
                    flag=1;
                    k=j+1;
                    while(emails[i][k]!='@'){
                        k++;
                    }
                    emails[i].erase(j,(k-j));
                }
                if(flag==1) break;
                k=0;
            }
        }
        set <string> str(emails.begin(),emails.end());
        emails.clear();
        emails.assign(str.begin(),str.end());
         return emails.size();
    }
};
```

### Expected behavior

This solution should not be accepted because it returns 2 instead of 1 for mentioned case.

### Screenshots

<img width="915" alt="Screenshot 2023-12-03 at 19 44 27" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/16077404/7f9b692d-4381-4165-af6e-3483345872cf">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
