### ISSUE TITLE
Editorial bug for 1611. Minimum One Bit Operations to Make Integers Zero

### ISSUE THREAD

**Issue by iamlockon** [LeetCode-Feedback/LeetCode-Feedback#18441]
### LeetCode Username
iamlockon

### Problem number, title, and link
[1611. Minimum One Bit Operations to Make Integers Zero](https://leetcode.com/problems/minimum-one-bit-operations-to-make-integers-zero/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug
In the Editorial of Time Complexity Analysis of first solution (**Approach 1: Math and Recursion**), I think the arithmetic series sum fomula is not correct, the numerator should be `logn⋅((logn)+1)` instead of `logn⋅((logn)−1)`. (This formula also appears in the second iterative solution)

Also, I think the implementation is not tail recursion compatible, since 
> (1 << (k + 1)) - 1 - minimumOneBitOperations(n ^ curr)

in current call will still require the control even after `minimumOneBitOperations(n ^ curr)` is calculated in child calls ([reference](https://en.wikipedia.org/wiki/Tail_call#Syntactic_form)).

Please let me know if I'm wrong, thanks again.

### Screenshots

<img width="1042" alt="Screenshot 2023-12-03 135937" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/9116266/431c9a2f-2af1-4da9-b4c1-1d63559e9374">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
