### ISSUE TITLE
2668. Find Latest Salaries - Typo in Problem Description/Explanation

### ISSUE THREAD

**Issue by ameliachu** [LeetCode-Feedback/LeetCode-Feedback#18449]
### LeetCode Username
[ameliachu](https://leetcode.com/ameliachu/)

### Problem number, title, and link
[2668. Find Latest Salaries](https://leetcode.com/problems/find-latest-salaries/) 

### Category of the bug
- [x] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
In the **Explanation** section of the Problem description, `emp_id` 2's records are listed as 128922, 128922, when it should be 128922, 130000.
i.e.

```
emp_id 2 has two records with a salary of 128922, 128922 out of these 130000 is an updated salary.
```
should be 
```
emp_id 2 has two records with a salary of 128922, 130000 out of these 130000 is an updated salary.
```

### Language used for code
MySQL 

### Code used for Submit/Run operation
N/A

### Expected behavior
N/A

### Screenshots
<img width="640" alt="Screenshot 2023-12-03 at 3 16 48 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/9689357/ad27ddc5-bc65-4ef0-ac97-f399969a57b2">

Output indicates that 130000 is an existing record.

### Additional context
also, ran `select * from Salary where emp_id=2` to verify that both records 128922, 130000 exist.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.
