### ISSUE TITLE
Missing Test Cases - 371. Sum of Two Integers

### ISSUE THREAD

**Issue by phungthienphuoc** [LeetCode-Feedback/LeetCode-Feedback#18454]
### Problem number 371 - Sum of Two Integers
https://leetcode.com/problems/sum-of-two-integers/

### Description of the bug
The test cases are not strong enough, so some codes using exponential function accepted. However, I can give some test cases to make them wrong, and enforce them to use bit manipulation.

### Python Code used for submission
```Python3
class Solution:
    def getSum(self, a: int, b: int) -> int:
        return round(log(math.e**a*math.e**b)) if a*b!=0 else a or b
```

### Suggestion for the test cases:
1. `Input: a=1000, b=1; Output: 1001`
2. `Input: a=1000,b=-1000; Output: 0`
3. `Input: a=-500, b=750; Output: 250`

### Expected behavior
The code above will not able to run with those test cases. In particular, errors appear.

### Screenshots
<img width="960" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/149442589/84ff01b4-db4c-44c1-b93d-7eac1880c1bf">

### Additional context
Link of submission: https://leetcode.com/problems/sum-of-two-integers/submissions/1111893975

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by phungthienphuoc** [comment]
I'm sorry for bothering you @LC-Pam. I am curious that how the progess of investigating my suggestion is now, as it is nearly 2 weeks now. If you have any information, please notify me. Thank you so much.

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
