### ISSUE TITLE
Missing Test Case - 2264. Largest 3-Same-Digit Number in String

### ISSUE THREAD

**Issue by VenkataMadhusudhan** [LeetCode-Feedback/LeetCode-Feedback#18466]
### LeetCode Username
venkatamadhusudhang

### Problem number, title, and link
2264. Largest 3-Same-Digit Number in String https://leetcode.com/problems/largest-3-same-digit-number-in-string/

### Category of the bug
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

A major testcase to validate if solution code check for **Largest** "3-Same-Digit Number" when there are more than **2** "3-Same-Digit Number"
With present test cases it wont validate if **Largest** "3-Same-Digit Number" appears  after **smallest** "3-Same-Digit Number" appears 
Test case to be added - 53339991
smallest "3-Same-Digit Number" appears first and highest "3-Same-Digit Number" appears latter
### Language used for code
Java script

### Code used for Submit/Run operation

```
/**
 * @param {string} num
 * @return {string}
 */
var largestGoodInteger = function(num) {
    const numarray=num.split("");

    for (var i=0;i<numarray.length;i++){
        if(numarray[i]==numarray[i+1] &&numarray[i]==numarray[i+2]){
            return numarray[i]+numarray[i+1]+numarray[i+2]
        }
    }
 return "";
};
```

### Expected behavior

code should give highest "Largest 3-Same-Digit Number"  if it appears even after lowest "Largest 3-Same-Digit Number"

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team
