### ISSUE TITLE
Missing Test Case - 1326. Minimum Number of Taps to Open to Water a Garden

### ISSUE THREAD

**Issue by mdd36** [LeetCode-Feedback/LeetCode-Feedback#18473]
### LeetCode Username

mdickson137

### Problem number, title, and link

1. Minimum Number of Taps to Open to Water a Garden: https://leetcode.com/problems/minimum-number-of-taps-to-open-to-water-a-garden/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [X] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Incorrect code accepted for problem.

### Language used for code
python3

### Code used for Submit/Run operation

```python
class Solution:
    def minTaps(self, n: int, ranges: List[int]) -> int:
        stack = []

        for i in range(n+1):
            spigot_range = ranges[i]

            # Zero range spigots don't mix with the rest of our logic, but
            # since they cover 0 ground we never want to use them anyway: if
            # no range contains point i, then it's impossible to water all real
            # numbers between (i-1, i+1) anyway.
            if spigot_range == 0:
                continue

            left, right = max(0, i - spigot_range), min(n, i + spigot_range)
            # If this spigot completely covers and extends a previous one,
            # we can remove that previous one.
            # Last condition is required to handle a case like [4,2,1,1], 
            # where we don't want to pop the 4 even though the 2 covers the
            # left-hanging overlap
            while stack and left <= stack[-1][0] and stack[-1][1] < right:
                stack.pop()

            # We can't reach the end of the last spigot's range, or
            # we're not covering anything that isn't already covered.
            # Either way, we definitely aren't part of the solution
            if stack and (stack[-1][1] < left or right <= stack[-1][1]):
                continue
            
            # This ensures we ignore the overlap with the previous spigots
            left = stack[-1][1] if stack else left
            
            # We can cover more of the garden, turn this spigot on.
            stack.append((left, right))

        # Because the stack is monotonic and we only added spigots to it if they could
        # connect to the previous ones, we just need to check that the top of the stack
        # reaches the end of the garden and the bottom of the stack reaches the start
        return len(stack) if stack and stack[0][0] == 0 and stack[-1][1] == n else -1
```

### Expected behavior

Because the while loop is checking `stack[-1][1] < right` rather than `stack[-1][1] <= right` and the value of `right` is clamped to `n`, it will never remove taps once it finds a path to the end of ranges. There aren't any test cases to check this though, so the submission was accepted.

Example test case:
n=5, ranges=[1,1,1,1,2,9]

Correct answer is 1, above code will produce 2

### Screenshots

![Capture d’écran 2023-12-04 à 11 27 27 AM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/23045798/d2ab9a4d-a35c-48c5-87b6-544cb7ab4a0d)

![Capture d’écran 2023-12-04 à 11 31 25 AM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/23045798/e5b3f5c1-2b62-4028-9350-bee3fae65305)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
