### ISSUE TITLE
191. Number of 1 Bits - Inconsistency between problem constraints and method signature for C#

### ISSUE THREAD

**Issue by nanotaboada** [LeetCode-Feedback/LeetCode-Feedback#18471]
### LeetCode Username

nanotaboada

### Problem number, title, and link

191. Number of 1 Bits https://leetcode.com/problems/number-of-1-bits/

### Category of the bug
- [x] Problem description
- [ ] Solved examples
- [x] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The Constraints section of the Description reads:

> The input must be a **binary string** of length 32.

while the Code editor contains the following method signature:

`public int HammingWeight(uint n)`

### Language used for code

C#

### Expected behavior

An input parameter that matches the described constraints.

### Screenshots

<img width="979" alt="191  Number of 1 Bits" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/87288/05ab81d6-ca3c-485b-8efc-b813222a623d">

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
