### ISSUE TITLE
Test case gives different result from submission - 526. Beautiful Arrangement

### ISSUE THREAD

**Issue by giaco5988** [LeetCode-Feedback/LeetCode-Feedback#1847]
#### Your LeetCode username

giaco

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Code behavior during submission is different from code behavior during testing.

#### Code you used for Submit/Run operation

```
class Solution:
    
    perfect = 0
    
    def dfs(self, current: List[int], n: int):
        if len(current) == n:
            Solution.perfect += 1
            return None
        
        i = len(current)+1
        for elem in filter(lambda x: x not in current, range(1, n+1)):
            if i % elem == 0 or elem % i == 0:
                tmp = current.copy()
                tmp.append(elem)
                self.dfs(tmp, n)
        
        return None
    
    def countArrangement(self, n: int) -> int:
        self.dfs([], n)
        
        return Solution.perfect
```

#### Expected behavior

Result for input=1 is correct during test case (result=1), but wrong during submission (result=3).

#### Screenshots

Testing result
<img width="285" alt="Screenshot 2021-01-03 at 17 14 00" src="https://user-images.githubusercontent.com/43993328/103483392-4415de00-4de7-11eb-8a3f-9a9efded7c08.png">

Submission result
<img width="209" alt="Screenshot 2021-01-03 at 17 16 01" src="https://user-images.githubusercontent.com/43993328/103483409-69a2e780-4de7-11eb-9c13-d094170a1ecc.png">

#### Additional context

I suspect this might be coming from the way the class `Solution` is initialized and run. With this implementation, subsequent run will cause the static variable `perfect` to "accumulate" across different tests. If one resets `perfect`, before each run, it works. Still, it looks a bit weird to see a different behavior during testing and submission for the same test case, are we able to know how the solution is run during submission? Thank you!

**Comment by lc-kay** [comment]
Hi @giaco5988 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
