### ISSUE TITLE
Missing Test Case - 220. Contains Duplicate III

### ISSUE THREAD

**Issue by ratep1** [LeetCode-Feedback/LeetCode-Feedback#18480]
### LeetCode Username

r3v4n

### Problem number, title, and link

220. Contains Duplicate III https://leetcode.com/problems/contains-duplicate-iii/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

It is possible to pass all test cases without an optimal solution. Below is a suggestion on the new test case that will help reject inefficient solutions.

### Language used for code

JavaScript

### Code used for Submit/Run operation

```js
// Paste your code here. Don't remove ``` given
// above and below the code.
var containsNearbyAlmostDuplicate = function (nums, indexDiff, valueDiff) {
    if (nums.length < 2 || indexDiff === 0) return false;

    if (valueDiff < indexDiff) {
        const set = new Set([nums[0]]);

        let left = 0;
        for (let i = 1; i < nums.length; i++) {
            const start = nums[i] - valueDiff;
            const end = nums[i] + valueDiff;
            for (let j = start; j <= end; j++) {
                if (set.has(j)) return true;
            }
            if (i - left === indexDiff) {
                set.delete(nums[left]);
                left++;
            }
            set.add(nums[i]);
        }
    } else {
        const queue = [nums[0]];

        let left = 0;
        for (let i = 1; i < nums.length; i++) {
            for (let j = 0; j <= queue.length; j++) {
                if (Math.abs(queue[j] - nums[i]) <= valueDiff) return true;
            }
            if (i - left === indexDiff) {
                queue.shift();
                left++;
            }
            queue.push(nums[i]);
        }
    }

    return false;
};

```

### Expected behavior

Currently, this code above is accepted but needs to be rejected (TLE) because it is an inefficient solution.

### Screenshots

Accepted:
![accepted](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/17838192/e57feb16-792b-4383-a63f-25944783d2bd)

TLE for new test case:
![TLE](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/17838192/ea85e572-3b4f-43db-be7a-6cc74515f9f7)

### Additional context

New test case:
[testcase_LC220.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/13558703/testcase_LC220.txt)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
