### ISSUE TITLE
209. Minimum Size Subarray Sum --- Incorrect Test Case

### ISSUE THREAD

**Issue by AritzBadiolaBengoa** [LeetCode-Feedback/LeetCode-Feedback#18484]
### LeetCode Username
badi03

### Problem number, title, and link
209. Minimum Size Subarray Sum https://leetcode.com/problems/minimum-size-subarray-sum/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [X] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
For the test case [12,28,83,4,25,26,25,2,25,25,25,12], it is indicating that the expected result is 8, but the correct result is actually 7.

### Language used for code
Swift

### Code used for Submit/Run operation

```
class Solution {
    func minSubArrayLen(_ target: Int, _ nums: [Int]) -> Int {
        var array = nums
        array.sort()
        
        var i = nums.count-1

        var sum = 0
        var n = 0

        while i >= 0{
            sum += array[i]
            n += 1
            if sum >= target{
                return n
            }
            i -= 1
        }
        return 0
    }
}
```

### Expected behavior
target = 213
nums = [12,28,83,4,25,26,25,2,25,25,25,12]

The code above with the indicated inputs has a result of 7, which is actually correct, as proven with a calculator: 83+28+26+25+25+25+25=237. So, with just 7 elements, we can get a value higher than the target value 213. But, in the use case, it is indicated as expected result 8, which is not correct.

### Screenshots

![capt_bug_leetcode_209](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/85494230/df50de0a-2202-4e42-a8ce-21813e319f59)

**Comment by LC-Pam** [comment]
Dear user, 
 
Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.
 
We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.
 
Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.
 
We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.
 
We appreciate your understanding and encourage you to continue learning and improving your coding skills. 
 
Should you have any further questions or need additional support, please don't hesitate to reach out to us.
 
Best regards,
 
The Leetcode Team

**Comment by AritzBadiolaBengoa** [comment]
You are totally right, sorry!! In this case, I understood the term subarray as an extract of the array in any order, not in the given order. Thank you for the response!!
