### ISSUE TITLE
Missing Test Case - 1. 两数之和

### ISSUE THREAD

**Issue by Hickays** [LeetCode-Feedback/LeetCode-Feedback#18493]
### LeetCode 用户名
hickays

### 问题号码、标题和链接
1. 两数之和 https://leetcode.cn/problems/two-sum/description/

### Bug 类型
- [ ] 问题描述
- [ ] 示例
- [ ] 问题限制
- [ ] 问题提示
- [ ] 不正确或缺少“相关标签”
- [ ] 不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*
- [x] 缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*
- [ ] 力扣官方题解
- [ ] 编程语言支持

### 描述
缺少测试用力导致不正确代码通过

### 你使用的语言
JavaScript

### 你提交或者运行的代码

```
var twoSum = function (nums, target) {

  // nums = [2, 2, 1];
  // target = 4;

  let map = new Map();
  let n = nums.length;
  if (n == 2) return [0, 1];
  for (let i = 0, j = n - 1; i <= j; i++, j--) {
    if (nums[i] + nums[j] == target) {
      return [i, j];
    }
    let diff = target - nums[i];
    if (map.has(diff)) {
      return [i, map.get(diff)];
    }
    diff = target - nums[j];
    if (map.has(diff)) {
      return [map.get(diff), j];
    }

    map.set(nums[i], i);
    map.set(nums[j], j);
  }
};
```

### 期望行为
当测试用例如下时：
nums = [2, 2, 1];
taget = 4;
以上代码返回结果：[1, 1]，不符合题目描述：“数组中同一个元素在答案里不能重复出现”

### 屏幕截图
通过截图：
![1701831125476](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/114720595/ed9a93d2-edcf-4b61-a7cc-08b4e95819cc)
测试用例失败截图：
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/114720595/39aca78e-deb1-4df5-ba68-33ba9b5f1fef)

### 额外的上下文
该代码参考该题 Java 语言的示例编写
![1701831369008](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/114720595/6c1cbc72-c976-4481-a9ee-842188c1dce0)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
