### ISSUE TITLE
Wrong Problem Description - Leetcode 874

### ISSUE THREAD

**Issue by LeetKing1** [LeetCode-Feedback/LeetCode-Feedback#1849]
The problem says that the Robot is facing North, but in fact it is facing east. This needs to be correct or it can be really misleading.

**Comment by lc-kay** [comment]
@LeetKing1 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @LeetKing1 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by LeetKing1** [comment]
Hi, my leetcode id is @blackspinner
