### ISSUE TITLE
Name incorrect - LC 1716

### ISSUE THREAD

**Issue by arps18** [LeetCode-Feedback/LeetCode-Feedback#18507]
- The name given in the Hint is incorrect with respect to the name in the problem. 

### LeetCode Username

- arpanp99

### Problem number, title, and link

- 1716 - Calculate money in Leetcode Bank 

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [x] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Problem Statement: **Hercy** wants to save money for his first car. He puts money in the Leetcode bank every day.

He starts by putting in $1 on Monday, the first day. Every day from Tuesday to Sunday, he will put in $1 more than the day before. On every subsequent Monday, he will put in $1 more than the previous Monday.
Given n, return the total amount of money he will have in the Leetcode bank at the end of the nth day.

- Hint: Hint 1
Simulate the process by keeping track of how much money **John** is putting in and which day of the week it is, and use this information to deduce how much money John will put in the next day.

### Expected behavior

- Simulate the process by keeping track of how much money **Hercy** is putting in and which day of the week it is, and use this information to deduce how much money John will put in the next day.

**Comment by qingy2019** [comment]
lol
