### ISSUE TITLE
Missing Test Case - 924. Minimize Malware Spread (Incorrect Reference Solution)

### ISSUE THREAD

**Issue by ikelarev** [LeetCode-Feedback/LeetCode-Feedback#18505]
### LeetCode Username
[ikelarev](https://leetcode.com/ikelarev)

### Problem number, title, and link
[924. Minimize Malware Spread](https://leetcode.com/problems/minimize-malware-spread/)

### Category of the bug
- [x] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support
Reference solution is incorrect.

### Description of the bug

For this test case (attachd) correct answer is 31, but 47 is "expected".
[testcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/13579720/testcase.txt)

Reduced tests case:
```
[[1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1],[0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0],[0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,1,0,0,0,1,0,0,0,1,0,1,1,0,0,0],[0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1],[0,0,1,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0],[0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,1,0],[0,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0],[0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0],[0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0],[1,0,0,0,0,0,1,0,1,0,1,0,1,0,0,0,0,1],[0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0],[0,1,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0],[0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0],[0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0],[1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1]]
[1,4]
```
The graph of the test:
![graph7](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/16304328/b7bd4d9a-2a31-413c-9753-46febfe6c816)

You can easily see that both 1 and 4 vertices are parts of different 9-vertices components. So both of them are correct answers. But problem description says: "If multiple nodes could be removed to minimize M(initial), return such a node with the smallest index." The smallest index is 1 (31 for the original test case), so the reference answer (4 or 41) is incorrect.

Another (and a bit smaller) test demonstrating the issue:
```
[[1,0,0,0,0,0,0,1,1,1],[0,1,1,0,0,1,0,0,0,0],[0,1,1,1,0,0,1,0,0,0],[0,0,1,1,0,1,1,0,0,0],[0,0,0,0,1,0,0,1,0,1],[0,1,0,1,0,1,1,0,0,0],[0,0,1,1,0,1,1,0,0,0],[1,0,0,0,1,0,0,1,0,1],[1,0,0,0,0,0,0,0,1,1],[1,0,0,0,1,0,0,1,1,1]]
[2,4]
```
Graph:
![graph8](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/16304328/cd1bfe1a-f4cc-4704-a6f8-de147ba7c710)
Again there is a parity between 2 and 4, but 2 is smaller. So the expected answer is incorrect.
![screenshot](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/16304328/0c3738f9-fe8b-4ec4-a40d-d240bc697055)

### Language used for code
C++

### Code used for Submit/Run operation

```
class Solution 
{
    int n;
    std::vector<int> parent;
    std::vector<int> sz;

    int find(int x)
    {
        if (parent[x] == x)
            return x;
        return parent[x] = find(parent[x]);
    }

    int size(int x)
    {
        return sz[find(x)];
    }

    void join(int x, int y)
    {
        x = find(x);
        y = find(y);
        if (x == y)
            return;
        parent[y] = x;
        sz[x] += sz[y];
    }

public:
    int minMalwareSpread(const std::vector<std::vector<int>> &graph, std::vector<int> &initial) 
    {
        if (initial.size() < 2)
            return initial.front();

        n = graph.size();
        parent.resize(n);
        sz.resize(n);
        for (int i = 0; i < n; i++)
        {
            parent[i] = i;
            sz[i] = 1;
        }        

        for (int i = 0; i < n; i++)
            for (int j = i + 1; j < n; j++)
                if (graph[i][j])
                    join(i, j);

        std::map<int, int> inits;
        for (int i : initial)
            inits[find(i)]++;

        std::sort(initial.begin(), initial.end());
        int res = initial[0];
        for (int i : initial)
            if (inits[find(i)] == 1)
                if (inits[find(res)] != 1 || size(i) > size(res))
                    res = i;

        return res;
    }
};
```

### Expected behavior

Output: 31

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by ikelarev** [comment]
Hi,
Any update here?
I'd like to submit my solution, but it doesn't seem to be a good idea until the reference solution is fixed.
Are you going to fix it?

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team

**Comment by ikelarev** [comment]
Thanks! I confirm that the issue is fixed now.
