### ISSUE TITLE
2954 - Incorrect Hint #3

### ISSUE THREAD

**Issue by TrickyCat** [LeetCode-Feedback/LeetCode-Feedback#18503]
### LeetCode Username
**[TrickyCat 🚀](https://leetcode.com/TrickyCat/)**

### Problem number, title, and link

[2954. Count the Number of Infection Sequences](https://leetcode.com/problems/count-the-number-of-infection-sequences/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [x] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Hint 3 says:
> If i > 0 and j < n - 1, we have two choices per second since the children at the two endpoints can both be the infect candidates. So there are 2**(j - i + 1) orders to infect all children in the segment.

Well, following this hint we should have the following:

| `i` | `j` | `j - i + 1` | `2 ** (j - i + 1)` | Notes
|-|-|-|-|-
| `1` | `1` | `1` | `2` | Hint says that a singleton chunk of uninfected children can have 2 infection sequences.<br><br>**E.g.:** n = 3, sick = [0, 2] <br> <=> [INFECTED, NOT_INFECTED, INFECTED] <br> <=> [0, 1, 0] <br><br>Uninfected chunk: i = 1, j = 1<br><br>Hint says that it has 2 different orderings to cover the infection of a single child, so can you please list both of them since I can see only one: `[1]`?
| `1` | `2` | `2` | `4` |  **E.g.:** n = 4, sick = [0, 3] <br> <=> [INFECTED, NOT_INFECTED, NOT_INFECTED, INFECTED]  <br> <=> [0, 1, 1, 0] <br><br>Uninfected chunk: i = 1, j = 2<br><br>Hint says that it has 4 different orderings to cover the infection of 2 children. Alright, they are (values are indices of uninfected children): <br><br> **1)** [1, 2] <br> **2)** [2, 1] <br><br> But what about the other 2  ((2 missing cases) = (4 cases expected by the hint) - (2 cases above)) unique sequences that we should have?

So, it looks like the hint is not correct and the actual number is smaller.

![](https://media.tenor.com/WnjJsVOwoJQAAAAC/john-travolta-well.gif)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback. We encourage you to share your questions in the discussion forum, where the community can provide insights and assistance.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team

**Comment by TrickyCat** [comment]
If the hint's wording is correct then why haven't you (and the team) clarified the oversimplified cases listed in the table above
- when only 1 child is uninfected
- when only 2 adjacent children are uninfected
?

I believe that for the team of LeetCode's professionals it shouldn't be a problem to showcase by example that the hint really works for those cases:

1) one missing case/sequence for '1 child' subproblem (in addition to the one listed in the table)
2) two missing cases/sequences for '2 adjacent children' subproblem (in addition to the ones listed in the table)

🤷‍♀️🤷‍♂️

**Comment by TrickyCat** [comment]
The current answer to my concern reminds the principle of "security through obscurity" rather than the real answer.
