### ISSUE TITLE
Missing Test Case - 347. Top K Frequent Elements

### ISSUE THREAD

**Issue by artemxx** [LeetCode-Feedback/LeetCode-Feedback#18511]
### LeetCode Username
artem2906x

### Problem number, title, and link
347. Top K Frequent Elements https://leetcode.com/problems/top-k-frequent-elements/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug
Your code from the editorial (Hoare's selection algorithm) passes the tests, but it must not. This is O(n^2) solution and takes 8 seconds for the following test case:
```
nums = list(range(-10**4, 10**4))
k = 1
```
And it will be quadratic for any testcase with unique values in the nums array. The true solution after partition with elements `< pivot` place elements `== pivot`. Then it will be a true O(N) solution. Example of true solution: [link](https://leetcode.com/submissions/detail/1113941572/)

### Language used for code
Python (but the same problem for other languages)

### Code used for Submit/Run operation

```
from collections import Counter
class Solution:
    def topKFrequent(self, nums: List[int], k: int) -> List[int]:
        count = Counter(nums)
        unique = list(count.keys())
        
        def partition(left, right, pivot_index) -> int:
            pivot_frequency = count[unique[pivot_index]]
            # 1. Move the pivot to end
            unique[pivot_index], unique[right] = unique[right], unique[pivot_index]  
            
            # 2. Move all less frequent elements to the left
            store_index = left
            for i in range(left, right):
                if count[unique[i]] < pivot_frequency:
                    unique[store_index], unique[i] = unique[i], unique[store_index]
                    store_index += 1

            # 3. Move the pivot to its final place
            unique[right], unique[store_index] = unique[store_index], unique[right]  
            
            return store_index
        
        def quickselect(left, right, k_smallest) -> None:
            """
            Sort a list within left..right till kth less frequent element
            takes its place. 
            """
            # base case: the list contains only one element
            if left == right: 
                return
            
            # Select a random pivot_index
            pivot_index = random.randint(left, right)     
                            
            # Find the pivot position in a sorted list   
            pivot_index = partition(left, right, pivot_index)
            
            # If the pivot is in its final sorted position
            if k_smallest == pivot_index:
                 return 
            # go left
            elif k_smallest < pivot_index:
                quickselect(left, pivot_index - 1, k_smallest)
            # go right
            else:
                quickselect(pivot_index + 1, right, k_smallest)
         
        n = len(unique) 
        # kth top frequent element is (n - k)th less frequent.
        # Do a partial sort: from less frequent to the most frequent, till
        # (n - k)th less frequent element takes its place (n - k) in a sorted array. 
        # All elements on the left are less frequent.
        # All the elements on the right are more frequent.  
        quickselect(0, n - 1, n - k)
        # Return top k frequent elements
        return unique[n - k:]
```

### Expected behavior
It shall TL or at least reach maximum recursion depth in Python and throw an error.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
