### ISSUE TITLE
Missing Test Case - 134. Gas Station

### ISSUE THREAD

**Issue by mandeepmourya007** [LeetCode-Feedback/LeetCode-Feedback#1851]
#### Your LeetCode username

mandeepmourya007

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

one of the tests case corner test case is missing

#### Code you used for Submit/Run operation

```
// gas-station
class Solution {
public:
    int canCompleteCircuit(vector<int>& gas, vector<int>& cost) {
        
        int n=gas.size();

        int extra=0,total=0,ans=0;
        for(int i=0;i<n;i++)
        {
            
            int t=gas[i]-cost[i];
            extra+=t;
            total+=t;
            if(extra<0)
            {
                extra=0;
                ans=i+1;
            }  
            
        }
        
        
        return total>=0?ans:-1;
        
    }
};
```

#### Language used for code

c++

#### Expected behavior

Input : []
Output : -1
My output: 0

**Comment by mandeepmourya007** [comment]
test case missiing

**Comment by lc-kay** [comment]
@mandeepmourya007 Please submit a specific missing test case to qualify for rewards. Thank you!

**Comment by mandeepmourya007** [comment]
Added test case

**Comment by lc-kay** [comment]
@mandeepmourya007 This is an invalid test case. The test case does not have enough input arguments: the expected argument 'cost'. Thank you for your time!
