### ISSUE TITLE
Missing Test Case: 1455. Check If a Word Occurs As a Prefix of Any Word in a Sentence

### ISSUE THREAD

**Issue by JeliHacker** [LeetCode-Feedback/LeetCode-Feedback#18516]
### LeetCode Username
JeliHacker

### Problem number, title, and link
[1455. Check If a Word Occurs As a Prefix of Any Word in a Sentence](https://leetcode.com/problems/check-if-a-word-occurs-as-a-prefix-of-any-word-in-a-sentence/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The code below passes, but there is a test case that it fails. It fails this test case:
```
Input: "i love eating bunburger burger"
Output: 5
```

### Language used for code

Java

### Code used for Submit/Run operation

```
class Solution {
    public int isPrefixOfWord(String sentence, String searchWord) {
        char[] charSentence = sentence.concat(" ").toCharArray();
        List<String> words = new ArrayList<>();
        String compound ="";

        for(char ch : charSentence)
        {
            if(ch==' ')
            {
                words.add(compound);
                compound="";
                continue;
            }
            compound=compound+String.valueOf(ch);
        }

        for(int j=0; j<words.size();j++)
        {
            if(words.get(j).contains(searchWord) && words.get(j).charAt(0)==searchWord.charAt(0))
            {
                for(int k=1; k<searchWord.length();k++)
                {   
                    if(words.get(j).charAt(k)!=searchWord.charAt(k))
                    {
                        return -1;
                    }

                }

                return j+1;
            }
        }

        return -1;

    }
}
```

### Expected behavior

This code should fail. 

### Screenshots

<img width="914" alt="Screenshot 2023-12-06 at 10 52 35 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/54377451/7c0fd04d-0ae8-4303-8a71-146bb42ede99">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
