### ISSUE TITLE
Problem Description Spelling - 1222. Queens That Can Attack the King

### ISSUE THREAD

**Issue by Donavern** [LeetCode-Feedback/LeetCode-Feedback#18528]
### LeetCode Username

donavern

### Problem number, title, and link

1222. Queens That Can Attack the King https://leetcode.com/problems/queens-that-can-attack-the-king/

### Category of the bug
- [x] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Spelling in problem description. "ad" should be "and"

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/24448584/6392c084-d54d-4e17-b9cf-de2e8f2ae6c6)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
