### ISSUE TITLE
Missing Test Case - 1710. Maximum Units on a Truck

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#1852]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution is accepted but fails on the following test case:

[[35, 14], [57, 99], [70, 48], [50, 70], [59, 24], [48, 72], [27, 48], [50, 89], [91, 9], [87, 66], [74, 58], [52, 29], [10, 19], [11, 87], [56, 71], [83, 67], [73, 31], [41, 58], [26, 39], [100, 99], [96, 51], [33, 34], [43, 23], [22, 41], [89, 28], [43, 19], [87, 56], [30, 95], [54, 93], [81, 98], [84, 26], [51, 52], [21, 16]]
270

#### Code you used for Submit/Run operation

```
class Solution {

   
    public int maximumUnits(int[][] boxTypes, int truckSize) {
        List<BoxUnit> list = new ArrayList();
        for (int[] bt : boxTypes) {
            list.add(new BoxUnit(bt[0], bt[1]));
        }
        Collections.sort(list, new sortByRatio());
        int sum = 0;
        for (BoxUnit bu : list) {
            for (int i = 0; i < bu.box; ++i) {
                if (truckSize == 0) {
                    return sum;
                }
                --truckSize;
                sum += bu.unit;
            }
        }
        return sum;
    }
    class sortByRatio implements Comparator<BoxUnit> {
        @Override
        public int compare(BoxUnit fp, BoxUnit sp) {
//            if(fp.unit == sp.unit)
//                return fp.box.compareTo(sp.box);

            if(sp.unit - fp.unit >0)
                return 1;
            return -1;
        }
    }

    class BoxUnit {
        int box;
        int unit;
        int ratio;
        public BoxUnit(int b, int u) {
            box = b;
            unit = u;
            double ratio = (double) b / (double) u;
        }

        public String toString() {
            return (String.format("\nname = %s\npoint = %d\n", box, unit));
        }

    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/103490547-8db3f800-4dea-11eb-88a5-8f0f464fd382.png)

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
