### ISSUE TITLE
Missing Test Case - 1752. Check if Array Is Sorted and Rotated

### ISSUE THREAD

**Issue by GEESEA** [LeetCode-Feedback/LeetCode-Feedback#18526]
### Category of the bug
- [1 ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

There is a test case missing i.e. [2,1,2,2,2]  because of which incorrect code getting accepted. 

### Language used for code

C++

### Code used for Submit/Run operation

```
class Solution {
public:
     void reverse(vector<int>& arr,int start,int end){
        while(start<end){
            swap(arr[start],arr[end]);
            start++;
            end--;
        }
    }

    int findPivotIndex(vector<int>& arr){
        int n = arr.size();
        int s = 0;
        int e = n-1;
        int mid = s+(e-s)/2;

        while(s<=e){
            if(s == e){
                return s;
            }
            if(arr[mid]>arr[mid+1]){
                return mid;
            }
            else if( mid-1>=0 && arr[mid]<arr[mid-1]){
                return mid-1;
            }


            else if(arr[mid]<arr[s]){
                e = mid-1;
            }
            else {
                s = mid+1;
            }
            mid = s+(e-s)/2;
        }
        return -1;
    }
    bool checksorted(vector<int>& nums){
        bool flag = 0;
        for(int i = 0;i<nums.size()-1;i++){
            if(nums[i]<=nums[i+1]){
                flag = 1;
            }
            else{
                flag = 0;
                break;
            }
        }
        if(flag){
            return true;
        }
        return false;
    }
    bool check(vector<int>& nums) {
        // nums = removeDuplicates(nums);
        int n = nums.size();

        int pivotindex = findPivotIndex(nums);
        int k = n-pivotindex-1;
        if(n==1){
            return true;
        }
        reverse(nums,0,n-1);
        reverse(nums,0,k-1);
        reverse(nums,k,n-1);

        return checksorted(nums);
    }
};
```

### Expected behavior

The code runs on  all cases but on the test case [2,1,2,2,2] , code is giving false, but original answer is true, and still the code gets accepted. 

### Additional context

![Screenshot 2023-12-07 170418](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/122373815/e893af82-4e13-479e-b2b9-947766ed495f)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
