### ISSUE TITLE
Test Case 28 Error - 1120. Maximum Average Subtree

### ISSUE THREAD

**Issue by ArdaAy** [LeetCode-Feedback/LeetCode-Feedback#18536]
### LeetCode Username
ArdaAy

### Problem number, title, and link
1120. Maximum Average Subtree 
https://leetcode.com/problems/maximum-average-subtree/description/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
There is an test case issue for this example. I tried other ways to solve that but, when I change my calculation to int values, it gives another error because the return type is double and it is waiting me to return for example 1.5, then it becomes 1 and gives error. My  solution seems okey for me. I request you to check test case 28 for this problem. I'm sharing the details below.

### Language used for code
C#

### Code used for Submit/Run operation

```
public class Solution {
    public double MaximumAverageSubtree(TreeNode root) {
        if(root == null)
            return 0;
        
        var avg = 0.0;
        double total = root.val;
        int cnt = 1;
        if(root.left != null){
            total += root.left.val;
            cnt++;
        }
        if(root.right != null){
            total += root.right.val;
            cnt++;
        }
        avg = total / cnt;
        double leftAvg = root.left != null ? MaximumAverageSubtree(root.left) : 0.0;
        double rightAvg = root.right != null ? MaximumAverageSubtree(root.right) : 0.0;
        
        double hand = 0.0;
        if(leftAvg > rightAvg)
            hand = leftAvg;
        else
            hand = rightAvg;
        
        if(avg > hand)
            return avg;
        else
            return hand;
    }
}
```

### Expected behavior
My Output -> (4+3+1)/3  -> 2.66667
Expected -> 2.00000
Since the output is requested as double, my answer must be accepted. I want to understand what problem is.

### Screenshots
<img width="831" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/18642504/5f110d98-7271-44bc-a0b2-31d1f488dab3">

**Comment by ArdaAy** [comment]
Can someone take care of my incident please?

**Comment by ArdaAy** [comment]
Can someone take care of my incident please?

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
