### ISSUE TITLE
Missing Test Case - 10. Regular Expression Matching

### ISSUE THREAD

**Issue by krause-derek** [LeetCode-Feedback/LeetCode-Feedback#18534]
### LeetCode Username
krause-derek

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
Some folks are getting around the problem by coding for specific test cases, rather than the code actually calculating the correct output.

### Code used for Submit/Run operation

```
using System.Text.RegularExpressions;
public class Solution {
    public bool IsMatch(string s, string p) {
        if(p.Contains("**"))
            return true;
        return Regex.IsMatch(s, "^"+p+"$");
    }
}
```

### Expected behavior
This code gets around test 354 but just outputting 'true' but would fail if the input string was "abcd" because it should be false but would still output 'true'.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/102814473/3f383c73-e2bc-4880-b0a8-28c550dc5df9)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/102814473/3cfbb53f-9738-4b4e-85a9-3d7d63a5cbab)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
