### ISSUE TITLE
1351 增加进阶要求

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#1853]
**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
「[1351. 统计有序矩阵中的负数](https://leetcode-cn.com/problems/count-negative-numbers-in-a-sorted-matrix/)」由于数据规模小，因此直接用暴力解法是完全可行的，时间复杂度是 O(mn)。
考虑到单调性，可以通过二分查找或者倒序遍历的方式降低时间复杂度。因此建议增加进阶要求：使用时间复杂度优于 O(mn) 的做法实现。
具体语言描述可能需要优化，但是进阶要求的含义是确定的。中文描述和英语描述都需要更新。

**你使用的语言**
Java

**你提交或者运行的代码**

**期望行为**
题目描述中增加上述进阶要求，中文描述和英语描述都需要更新。

**屏幕截图**

**额外的上下文**

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前题面新增了进阶要求，已同步更新。
