### ISSUE TITLE
Problem Specification - 7. Reverse Integer

### ISSUE THREAD

**Issue by zoller27osu** [LeetCode-Feedback/LeetCode-Feedback#1854]
#### Your LeetCode username
MycroftJr

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
The Note section of the Question needs reworking. Instead of this weak "Assume" language, it should read more like:
> **Do NOT** use or store integers outside of the 32-bit signed integer range: [−2^31,  2^31 − 1].
If the reversed integer would be outside this range (i.e. overflow), return 0 instead.

**Comment by lc-kay** [comment]
Hi @zoller27osu 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @zoller27osu 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!
