### ISSUE TITLE
Editorial bug in 1611. Minimum One Bit Operations to Make Integers Zero

### ISSUE THREAD

**Issue by iamlockon** [LeetCode-Feedback/LeetCode-Feedback#18541]
### LeetCode Username
iamlockon

### Problem number, title, and link
[1611. Minimum One Bit Operations to Make Integers Zero](https://leetcode.com/problems/minimum-one-bit-operations-to-make-integers-zero/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug
In the second solution (**Approach 2: Iteration**) of the Editorial, Time Complexity Analysis part, I think the arithmetic series sum fomula is still not correct, the numerator should be `logn⋅((logn)+1)` instead of `logn⋅((logn)−1)`.

Please let me know if I'm wrong, thanks again.

### Screenshots

<img width="929" alt="Screenshot 2023-12-08 213434" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/9116266/fd43b58f-a31d-4f50-89db-93fdb0667592">

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
