### ISSUE TITLE
题目提示错误 - 2721

### ISSUE THREAD

**Issue by tcy1999** [LeetCode-Feedback/LeetCode-Feedback#18548]
### 问题号码、标题和链接
[2721. 并行执行异步函数] (https://leetcode.cn/problems/execute-asynchronous-functions-in-parallel/description/)

### Bug 类型
- [ ] 问题描述
- [ ] 示例
- [ ] 问题限制
- [x] 问题提示
- [ ] 不正确或缺少“相关标签”
- [ ] 不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*
- [ ] 缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*
- [ ] 力扣官方题解
- [ ] 编程语言支持

### 描述
https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/18366 后续，该issue关闭后猜测超时应与测试用例中有`functions = []`的情况有关，修改后提交通过；然而题目提示为`1 <= functions.length <= 10`，具有误导性。

### 期望行为
提示为`0 <= functions.length <= 10`

### 屏幕截图
<img width="884" alt="截屏2023-12-08 23 15 40" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/35225128/8de7ec2c-5ddc-486d-b6af-e28a96629b04">

**Comment by amcones-lc** [comment]
感谢反馈，经核实该题目题解及测试用例暂无异常（不存在 `functions.length==0` 的数据），力扣会不断努力给大家带来更好的学习社区！后续刷题学习中遇到问题，可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
