### ISSUE TITLE
Missing Test Case - 753. Open the Lock

### ISSUE THREAD

**Issue by irishryoon** [LeetCode-Feedback/LeetCode-Feedback#1855]
#### Your LeetCode username

irishryoon

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

The following code is accepted when it shouldn't be accepted. The code returns the wrong result on the following test case. 
["5557","5553","5575","5535","5755","5355","7555","3555","6655","6455","4655","4455","5665","5445","5645","5465","5566","5544","5564","5546","6565","4545","6545","4565","5656","5454","5654","5456","6556","4554","4556","6554"]
"5555"

#### Code you used for Submit/Run operation

```
class Solution:
    def openLock(self, deadends: List[str], target: str) -> int:
        deadends = set(deadends)
        # exception, all deadends surround "0000"
        constrain = {"1000","0100","0010","0001","9000","0900","0090","0009"} 
        if deadends == constrain: return -1 
        if '0000' in deadends: return -1
        if target == "0000": return 0           
        
        # func of distance
        def dist(code):
            return sum(min(int(c), 10-int(c)) for c in code)
        
        def neighbors(code):
            for i in range(4):
                x = int(code[i])
                yield code[:i] + str((x - 1) % 10) + code[i + 1:]
                yield code[:i] + str((x + 1) % 10) + code[i + 1:]
        
        # delete deadends from 8 neighbors
        last_moves = set(neighbors(target)) - deadends
        if not last_moves: return -1

        # calculate distance of target
        ans = dist(target)
        for code in last_moves:
            # if any last move has less distance than target,
            # it means that code can approach target
            if dist(code) < ans: return ans
        return ans + 2
        
```

#### Language used for code

Python

#### Expected behavior

As shown in the screenshot below, the above code returns the wrong result on the mentioned test case. The above code shouldn't be accepted, but it is accepted as a solution. 

#### Screenshots

<img width="1021" alt="Screen Shot 2021-01-03 at 9 13 22 PM" src="https://user-images.githubusercontent.com/16123954/103495356-8d2a5a00-4e08-11eb-829d-0e8e29dbdab4.png">

**Comment by lc-kay** [comment]
Hi @irishryoon 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @irishryoon 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
