### ISSUE TITLE
Missing Test Case - 1520. Maximum Number of Non-Overlapping Substrings

### ISSUE THREAD

**Issue by amitmakkad** [LeetCode-Feedback/LeetCode-Feedback#18557]
### LeetCode Username

amit186

### Problem number, title, and link

1520. Maximum Number of Non-Overlapping Substrings https://leetcode.com/problems/maximum-number-of-non-overlapping-substrings/ 

### Category of the bug
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

Input
s = "dgcabccbdaag"
Expected Output
["dgcabccbdaag"]

The above test case is missing, so the below code gets accepted.

### Language used for code

C++

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
class Solution {
public:
    vector<string> maxNumOfSubstrings(string s) {
        map<char,pair<int,int>> m;
        int n=s.size();
        for(int i=0;i<n;i++){
            if(m.find(s[i])==m.end())
                m[s[i]]={i,i};
            else
                m[s[i]].second=i;
        }

        vector<pair<int,int>>v;
        for(auto x:m){
            int l=x.second.first;
            int r=x.second.second;
            v.push_back({l,r});
        }
        sort(v.begin(),v.end());

        vector<pair<int,int>>seg;
        for(int i=0;i<v.size();i++){
            int l=v[i].first;
            int r=v[i].second;
            for(int j=l;j<=r;j++){
                r=max(r,m[s[j]].second);
            }
            for(int j=r;j>=l;j--){
                l=min(l,m[s[j]].first);
            }
            for(int j=l;j<=r;j++){
                r=max(r,m[s[j]].second);
            }
            for(int j=r;j>=l;j--){
                l=min(l,m[s[j]].first);
            }
            seg.push_back({r,l});
        }

        sort(seg.begin(),seg.end());
       
        vector<string>ans;
        int rr=-1;
        for(int i=0;i<seg.size();i++){
            int r=seg[i].first;
            int l=seg[i].second;
            if(l>rr){
                ans.push_back(s.substr(l,r-l+1));
                rr=r;
            }
        }
        return ans;

        
    }
};
```

### Expected behavior

Input
s =
"dgcabccbdaag"
Output
["dgcabccbdaa"]
Expected
["dgcabccbdaag"]

Output and expected are not the same, so the above code should not be accepted.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/79632719/73707eb8-85e1-43b6-953c-6d080dd881b9)

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
