### ISSUE TITLE
Problem Constraints Issue - 709. To Lower Case

### ISSUE THREAD

**Issue by Ashutosh-Ray** [LeetCode-Feedback/LeetCode-Feedback#18568]
### Category of the bug
- [ ] Problem description
- [ ] Problem constraints

### Code used for Submit/Run operation

```
class Solution {
    public String toLowerCase(String s) {
        return s.toLowerCase();
    }
}
```

### Expected behavior

```
class Solution {
  public String toLowerCase(String s) {
       char[] characters = s.toCharArray();
               for (int i = 0; i < characters.length; i++) {
                   characters[i] = Character.toLowerCase(characters[i]);
               }
               return new String(characters);
       }
}
```

**Comment by LC-Pam** [comment]
Thank you for taking the time to share your feedback with us! Your input is valuable, and we appreciate your contribution to making LeetCode even better.

If you ever have more thoughts, suggestions, or questions, feel free to reach out. We're here to listen and continuously improve your experience on LeetCode.

Thanks again for being part of our community!

Best regards,
Leetcode Team
