### ISSUE TITLE
Confusing Problem Description - Leetcode 892 

### ISSUE THREAD

**Issue by LeetKing1** [LeetCode-Feedback/LeetCode-Feedback#1856]
I think we should at least add an explanation for how we got the answer for the 1st example. Otherwise, it is very confusing. Also, I would suggest represent the input as an matrix instead of an 2d array to avoid further confusions. See the discussion here: https://leetcode.com/problems/surface-area-of-3d-shapes/discuss/165713/To-understand-the-question

**Comment by lc-kay** [comment]
Hi @LeetKing1 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @LeetKing1 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by LeetKing1** [comment]
Hi, my leetcode id is @blackspinner
