### ISSUE TITLE
Grammar error in "Check If Two String Arrays are Equivalent" problem description

### ISSUE THREAD

**Issue by Y-Rov** [LeetCode-Feedback/LeetCode-Feedback#18564]
### LeetCode Username

[seeker_of_balance](https://leetcode.com/anacondrai/)

### Problem number, title, and link

[1662. Check If Two String Arrays are Equivalent](https://leetcode.com/problems/check-if-two-string-arrays-are-equivalent/)

### Category of the bug
- [ ] Problem description

### Description of the bug

Hello, LeetCode team😄

The last paragraph in the problem description looks like this:

> A string is **represented** by an array if the array elements concatenated **in order** forms the string.

From the grammar point of view, this sentence is not correct.

### Expected behavior

The sentence should be rewritten and look something like this:

> An array **represents** a string if the array elements concatenated **in order** form the string.

### Screenshots

![Incorrect_Sentence](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73534920/7ae6b5f4-c63d-4cf1-a2c8-57d839ccfcc1)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
