### ISSUE TITLE
Missing Test Case - 1688. Count of Matches in Tournament

### ISSUE THREAD

**Issue by minhkiwi14** [LeetCode-Feedback/LeetCode-Feedback#18579]
### LeetCode Username
minhkiwi14

### Problem number, title, and link
1688. Count of Matches in Tournament https://leetcode.com/problems/count-of-matches-in-tournament

### Category of the bug
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

The number of test cases is too few, so I want to contribute one.

### Language used for code
C

### Code used for Submit/Run operation

```
int numberOfMatches(int n){
    if (n == 1)
    {
        return 0;
    }
    if (n % 2 == 0)
    {
        return n / 2 + numberOfMatches(n / 2);
    }
    return (n - 1) / 2 + numberOfMatches((n + 1) / 2);
}
```

### Expected behavior
I want to contribute my test case where there are 200 and 199 people (the number of matches would be 199 and 198 respectively). Only then can the recursion ability of users be tested correctly.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
