### ISSUE TITLE
Missing Test Case - 214. Shortest Palindrome简单的暴力解法，不只是在前面添加字符，而是找到最短回文字符串

### ISSUE THREAD

**Issue by Liuhui548484** [LeetCode-Feedback/LeetCode-Feedback#18575]
class Solution {
public:
    string shortestPalindrome(string s) {
        int maxLength = 1;
        int n = s.size();
        int end = 0;
        if (n < 2) {
            return s;
        }
        bool d[1000][1000] = { false };
        for (int i = n-1; i >=0; i--) {
            d[i][i] = true;
            for (int j = i; j < n; j++) {
                if (s[i] == s[j]) {
                    d[i][j] = j - i < 3 || d[i + 1][j - 1];
                    //cout << "行为:" << i << "  列为:" << j << "  结果为:" << d[i][j] << endl;
                    //cout << j - i + 1 << endl;
                }
                
            }
        }
        int begine = 0;
        for (int i = 0; i < n; i++) {
            for (int j = i; j < n; j++) {
                if (d[i][j] && maxLength < j - i + 1) {
                    maxLength = j - i + 1;
                    begine = i;
                    end = j;
                    //cout << "初始位置：" << begine << "  末位置:"<< end<<"  长度："<<maxLength<<endl;
                    //cout << d[i][j] << endl;
                }
            }
        }
        char s1[5000] = { 0 };
        int k = 0;
        if (end == n - 1) {
            for (int i = begine-1; i >=0; i--) {
                s1[k] = s[i];
                ++k;
               // cout << "字符串的值为：" << s1 << endl;
            }
            return s + s1;
        }
        if (begine != 0) {
            end = 0;
        }
        for (int i = n-1; i > end; i--) {
            s1[k] = s[i];
            ++k;
            //cout << "字符串的值为：" << s1 << endl;
        }
        //cout << "结果为：" << s1+s << endl;
        return s1+s;
    }
};

**Comment by amcones-lc** [comment]
感谢反馈，能否向我们补充题目信息，以及完善代码格式，把信息提供完整才能有助于快速验证和精准的定位，谢谢。
