### ISSUE TITLE
2390. Removing Stars From a String : Difficulty Level Inaccurate

### ISSUE THREAD

**Issue by ShubhamKNIT** [LeetCode-Feedback/LeetCode-Feedback#18570]
### LeetCode Username

ShubhamKNIT

### Problem number, title, and link

<a href="https://leetcode.com/problems/removing-stars-from-a-string/">[2390. Removing Stars From a String](https://leetcode.com/problems/removing-stars-from-a-string/)</a>

### Description of the bug

The question is marked with medium level difficulty. But, in fact its quite easy to solve within 3-4 mins, even for the beginners who would have just learnt the stack and string, this question just require you if-else logic to solve the question. You can usually solve them using two techniques - one with the help of stack and one with string only. I think it should be of easy tag.

### Language used for code

C++

### Code used for Submit/Run operation

```
// solution using string
class Solution {
public:
    string removeStars(string s) {
        string ans = "";

        for (auto it : s) {
            if (it == '*' && ans.size() > 0) {
                ans.pop_back();
            }
            else {
                ans.push_back(it);
            }
        }

        return ans;
    }
};
```

```
// solution using stack
class Solution {
public:
    string removeStars(string s) {
        stack<char> st;

        for (int i = 0; i < s.size(); i++) {
            if (!st.empty() && s[i] == '*') {
                st.pop();
            }
            else {
                st.push(s[i]);
            }
        }

        s = "";
        while (!st.empty()) {
            s.push_back(st.top());
            st.pop();
        }

        reverse(s.begin(), s.end());

        return s;
    }
};
```

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
