### ISSUE TITLE
Grammar errors in Binary Tree Explore Card - Conclusion

### ISSUE THREAD

**Issue by Y-Rov** [LeetCode-Feedback/LeetCode-Feedback#18582]
### LeetCode Username

[seeker_of_balance](https://leetcode.com/anacondrai/)

### Category of the bug
- [x] Language

### Description of the bug

Hello, LeetCode team😄

If we go through the section "Conclusion" in [Binary Tree Explore Card](https://leetcode.com/explore/learn/card/data-structure-tree/133/conclusion/), we have the next two sentences:

> After finishing the previous chapters, you should be familiar with binary trees be able to solve basic problems related to them. 
>
> In this chapter, we are going to provide you more exercise to help you be more confident with this topic.

The first sentence misses the word "and". The second sentence misses the word "with" and the word "exercise" actually should be written as "exercises".

### Expected behavior

The corrected sentences should look like this:

> After finishing the previous chapters, you should be familiar with binary trees and be able to solve basic problems related to them. 
>
> In this chapter, we are going to provide you with more exercises to help you be more confident with this topic.

### Screenshots

![Incorrect_Sentences](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73534920/9982453c-5d68-45d7-a275-c99509e70668)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by Y-Rov** [comment]
Hi, @LC-Pam. The sentences were corrected, thanks to you and the part of the team responsible for Explore Cards 😄

![Corrected_Sentences](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73534920/53fa2f29-2e79-4921-8898-b8841bdbbf43)

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
