### ISSUE TITLE
[false negative] console is saying wrong answer, though it is correct - 26. Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by mr3y-the-programmer** [LeetCode-Feedback/LeetCode-Feedback#1858]
#### Your LeetCode username

M R 3 YY

#### Category of the bug
- [ ] Solution

#### Description of the bug

I was trying to solve [Remove duplicates from sorted array](https://leetcode.com/problems/remove-duplicates-from-sorted-array/) problem and when I tried to run my code, the console said: 

> "Wrong answer"
Your input: [1, 1, 2]
Output: [1, 1]
Expected: [1, 2]

 though my code produces the same result as expected which is [1, 2]

#### Steps to reproduce the bug:
- try to run the code snippet below in [Kotlin Playground Online](https://play.kotlinlang.org/) with input [1, 1, 2], but make the array return `IntArray` instead of `Int` and remove `.size` suffix in the last line. It will give you expected result "[1, 2]"

- However, try to run the code snippet below in LeetCode editor, it will give you the strange [1, 1] result

#### Code you used for Submit/Run operation

```
class Solution {
    fun removeDuplicates(nums: IntArray): Int {
        if(nums.size <= 1) return nums.size
        var tempNums = nums
        for(i in 0 until nums.lastIndex) {
            innerLoop@ for (j in i+1 until nums.size) {
                if(nums[i] == nums[j]) {
                    tempNums = (tempNums.asList() - nums[i]).toIntArray()
                    break@innerLoop
                }
            }
        }
        return tempNums.size
    }
}
```

#### Language used for code

Kotlin

#### Expected behavior

It should be Accepted as the code actually works as intended and adheres to problem description

#### Additional context

FYI, Kotlin doesn't allow passing param by reference So we can't modify the nums array directly

**Comment by lc-kay** [comment]
@mr3y-the-programmer The console is correct, there may be a bug in your code that is not generating the correct output on our editor. Please check out these accepted Kotlin solutions for reference https://leetcode.com/problems/remove-duplicates-from-sorted-array/discuss/?currentPage=2&orderBy=most_votes&query=kotlin Thank you for your time.

**Comment by mr3y-the-programmer** [comment]
Have you tried to run that code on Kotlin playground or any other kotlin console? I'm sure you'll see a different result. Anyway kotlin doesn't allow passing param by reference as I said above, That being said the person who suggested this problem should read more about function parameters in kotlin as if he did, he wouldn't mention any thing about "passing param by reference" for kotlin users in problem description

**Comment by lc-kay** [comment]
@mr3y-the-programmer I've filed a report to our team on the description in the clarification section of the problem. Thank you for your time.

**Comment by lc-kay** [comment]
@mr3y-the-programmer Our team has reviewed your report and decided to not change the driver of this problem. Suppose the user has returned x, the driver prints the first x numbers of nums. The solution of the user doesn't change nums but creates a new array tempNums which is not seen by the driver.
