### ISSUE TITLE
Weak testcase in Divide Two Integers

### ISSUE THREAD

**Issue by as-rawat** [LeetCode-Feedback/LeetCode-Feedback#1859]
#### Your LeetCode username
primus73

#### Category of the bug
- 29 Divide Two Integers

#### Description of the bug

Weak testcase.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int divide(int dividend, int divisor) {
        
        int sign = 1;
        if(dividend < 0 || divisor < 0)
        {
            if(dividend > 0 || divisor > 0)
                sign = -1;
        }
        
        long ldividend = abs((long)dividend);
        long ldivisor = abs((long)divisor);
    
        if(ldivisor == 1)
        {
            long ret = sign * ldividend;
            return (ret > INT_MAX || ret < INT_MIN) ? INT_MAX : (int) ret;
        }
        
        long q = 0;
        while(ldividend >= ldivisor)
        {
            q++;
            if(q > INT_MAX)
                return INT_MAX;
            ldividend -= ldivisor;
        }
        
        return (sign * (int) q);
    }
};
```

#### Language used for code

C++

#### Expected behavior
Should fail for these test, when grouped together.
2147483647
2
2147483647
2
2147483647
2

**Comment by lc-kay** [comment]
@as-rawat The solution you provided resulted in Time Limit Exceeded. Please provide an accepted code that the test cases you provided fail on. Then, I will reopen this issue. Thank you for your time.

**Comment by as-rawat** [comment]
Hey, I got same solution accepted right now.
But the above testcase, which I provided TLE.
![Screenshot_2021-01-09-01-13-38-104_com android chrome](https://user-images.githubusercontent.com/26897243/104057335-fbf82080-5217-11eb-9395-cbb06d3ae2b5.jpg)

**Comment by lc-kay** [comment]
<img width="1915" alt="Screen Shot 2021-01-08 at 11 50 17 AM" src="https://user-images.githubusercontent.com/70870126/104057892-b7cd3780-51a7-11eb-89a5-4149542e38fd.png">
I just ran your code three times and got TLE for all the tries.

**Comment by as-rawat** [comment]
that's wired now it TLEs for me too, is there a way I can share my previous submission with you?

**Comment by as-rawat** [comment]
Could you try again with
```
class Solution {
public:
    int divide(int dividend, int divisor) {
    int sign = 1;
        if(dividend < 0 || divisor < 0)
        {
            if(dividend > 0 || divisor > 0)
                sign = -1;
        }
        
        long ldividend = abs((long)dividend);
        long ldivisor = abs((long)divisor);
    
        if(ldivisor == 1)
        {
            long ret = (sign < 0) ? -ldividend : ldividend;
            return (ret > INT_MAX || ret < INT_MIN) ? INT_MAX : (int) ret;
        }
        
        long q = 0;
        while(ldividend >= ldivisor)
        {
            q++;
            ldividend = ldividend - ldivisor - ldivisor - ldivisor - ldivisor - ldivisor - ldivisor - ldivisor - ldivisor;
        }
        
        long x = q + q + q + q + q + q + q + q;
        q = x;
        while(ldividend + ldivisor < ldivisor)
        {
            q--;
            ldividend = ldividend + ldivisor;
        }
        
        x = (int)min(q, (long)INT_MAX);
        
        return (sign < 0) ? -x : x;

    }
};
```

and then the following testcase?
2147483647
2
2147483647
2
2147483647
2
2147483647
2
2147483647
2
2147483647
2

**Comment by lc-kay** [comment]
@as-rawat I tried again with the code and test cases you recently provided and they were both accepted.
