### ISSUE TITLE
Wrong Runtime for LC#215 `Kth Largest Element in an Array` Editorial Approach #3

### ISSUE THREAD

**Issue by rhearao** [LeetCode-Feedback/LeetCode-Feedback#18596]
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug
In the editorial for problem #215 Approach 3: Quickselect, the time complexity for the solution is listed as O(n) on average, O(n^2) in the worst case. The rational is written as follows: 

This recurrence can be analyzed using the [master theorem](https://en.wikipedia.org/wiki/Master_theorem_(analysis_of_algorithms)) with a = 1, b = 2, k = 1:T(n)=T(n/2)+O(n)=O(n)

The master theorem is a complex extration of the formula that seeks to include all scenarios of a, b and k, but for the sake of our discussion it could be roughly summed up as: 
![Screenshot 2023-12-11 at 4 00 07 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/42724631/74e343cc-72c3-4c3f-91a0-b44b7c2e8125)

a denotes the number of subproblems each problem is divided into at each level, b denotes the size of each subproblem in relation to the original problem, d denotes the time complexity of each execution.

Editorial wrongly assumed that a=1.

### Code used for Submit/Run operation
In the editorial, it stated that `a =1, b=2, k(d) =1`, when a should be 2 or 3 depending on understanding and execution. Take the code execution in approach 3 as an example: 
```
class Solution {
    public int findKthLargest(int[] nums, int k) {
        List<Integer> list = new ArrayList<>();
        for (int num: nums) {
            list.add(num);
        }
        
        return quickSelect(list, k);
    }
    
    public int quickSelect(List<Integer> nums, int k) {
        int pivotIndex = new Random().nextInt(nums.size());
        int pivot = nums.get(pivotIndex);
        
        List<Integer> left = new ArrayList<>();
        List<Integer> mid = new ArrayList<>();
        List<Integer> right = new ArrayList<>();
        
        for (int num: nums) {
            if (num > pivot) {
                left.add(num);
            } else if (num < pivot) {
                right.add(num);
            } else {
                mid.add(num);
            }
        }
        
        if (k <= left.size()) {
            return quickSelect(left, k);
        }
        
        if (left.size() + mid.size() < k) {
            return quickSelect(right, k - left.size() - mid.size());
        }
        
        return pivot;
    }
}
```

### Expected behavior
1. Each execution takes O(n) time, so d=1
2. Each problem is divided into 2 scenarios/further executions, so a=2
3. In an average scenario, where we pick a pivot right in the middle, each subproblem would be half of the size of the original problem, so b=2. In the worst scenario, where we pick the worst pivot, the subproblem is only slightly smaller than the original problem, so b > 1, usually b = n-1

In an average scenario, a=2, b=2, d=1, T(n) = O(n^d logn) = O(nlogn)
In the worst case scenario, a=2, b=1, d=1, T(n) = O(n^logb^a) = O(n^2) when b = sqrt 2

Sqrt 2 roughly equals 1.4, and n/b should always be an integer. Now I'm not sure how the math pans out here, and why b being sqrt 2 would be the max case scenario, I can only understand intuitively that int he worst case scenario, with each execution O(n), the next problem has a execution time of O(n-1), O(n) + O(n-1)+....+ O(1) = O(n/2(n+1)) = ~O(n^2)

What is clear, however, is that since a=2, the average case should definitely be O(nlogn), consistent with Quick Sort's average sorting time being O(nlogn). Not sure how the editoria came to the conclusion that a=1, it should be corrected.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

The time complexity for the average case for quick selection is O(n). The worst-case time complexity is still O(n^2) but by using a random pivot, the worst case can be avoided in most cases. So, on average quick select provides an O(n) solution to find the k-th largest/smallest element in an unsorted list.

Your assumption is wrong:

Each problem is divided into 2 scenarios/further executions, so a=2

There is only one recursive call, so a = 1

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
