### ISSUE TITLE
Missing Test Case - 981. Time Based Key-Value Store

### ISSUE THREAD

**Issue by aquazod** [LeetCode-Feedback/LeetCode-Feedback#18599]
### LeetCode Username
Aquazod

### Problem number, title, and link
981.  Time Based Key-Value Store: https://leetcode.com/problems/time-based-key-value-store/description/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [X] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The problem description is about storing different string values for different string keys at any given timestamps (set function), and also retrieving the string value for any string key at a specified timestamp (get function). It is declared in the problem description that if the get function is called with a timestamp which precedes the first timestamp the string key was set, then the output should be an empty string.
For example: if I set string "AA" with value "first" at timestamp "10", then I called get function for string "AA" at timestamp "5", the output should be an empty string "" because string "AA" didn't exist before timestamp "10", however if I called get function for string "AA" at timestamp "15", then the output string value is still "first" at that timestamp because I didn't modify its string value.

### Language used for code

C++

### Code used for Submit/Run operation

```
class TimeMap {
public:
    unordered_map<string, map<int, string>> mp;
    int mini = INT_MAX;
    TimeMap() {
        
    }
    
    void set(string key, string value, int timestamp) {
        mp[key][timestamp] = value;
        mini = min(mini, timestamp);
    }
    
    string get(string key, int timestamp) {
        if(timestamp < mini || !mp.count(key))
            return "";
        auto it = mp[key].upper_bound(timestamp);
        it--;
        return it->second;
    }
};

/**
 * Your TimeMap object will be instantiated and called as such:
 * TimeMap* obj = new TimeMap();
 * obj->set(key,value,timestamp);
 * string param_2 = obj->get(key,timestamp);
 */
```

### Expected behavior

The right implementation for the get function is to check first if the string key has a string value at the specified timestamp. And this could be done by checking the minimum timestamp at which the string key has a value at. And it is crucial to store this minimum value for all the string keys we have. However in my solution here, I only kept track of one minimum timestamp (the mini variable) for all the stored string keys. And inside the implementation of the get function, I check first if the passed timestamp is smaller than the mini variable to decide if the passed string key had a value at that passed timestamp. And this is absolutely wrong because I need to make that check for each stored string key, on a different note, check if the passed timestamp is smaller than the very first timestamp the string key occurred.

### Screenshots

The following screenshot shows the accepted submitted code:
![Screenshot 2023-12-11 140708](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/78305867/992ae2e4-68e7-40db-9e84-5a3b5dcce38c)

The following screenshot shows a testcase that got a wrong answer while running the same accepted code:
![Screenshot 2023-12-11 140729](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/78305867/d901b9b3-ab3b-4b99-acbe-9134ea5d47c0)

### Additional context

Consider this test case: 
["TimeMap","set","set","set","get"]
[[],["assem","fat",20],["assem","thin",40],["hamza","thin",41],["hamza",20]]

Here I sat the string "assem" to have a value "fat" at timestamp 20, and sat the same string to have a value "thin" at timestamp 40. Then sat a different string "hamza" to have a value "thin" at timestamp 41. Then I called get function for the string "hamza" at timestamp 20.
Clearly this get function should return an empty string because the first timestamp at which string "hamza" occurred was 41.
But due to the fact that in the previous code I generalise the first timestamp to all the stored strings, that get function returned "thin" and not an empty string. That code got accepted last time at December 11th 2023.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
