### ISSUE TITLE
Missing Test Case - 1287. Element Appearing More Than 25% In Sorted Array

### ISSUE THREAD

**Issue by GouravShDev** [LeetCode-Feedback/LeetCode-Feedback#18595]
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
The question is accepting even if I hardcode the return in the end to 1. 

TC : [10]
RESULT: Passed
EXPECTED : Failed

### Language used for code
C++

### Code used for Submit/Run operation

```
class Solution {
public:
    int findSpecialInteger(vector<int>& arr) {
        int n = arr.size();
        int count = 1;
        for(int i =1 ; i < n ; i++){
            if(arr[i-1] == arr[i]){
                count++;
            }else{
                count = 1;
            }
            if(count * 4 > n) return arr[i];
        }
        return 1;
    }
};
```

### Expected behavior

The test cases should not pass when return hardcode value 1 at the end

### Screenshots
<img width="1440" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/74348508/d3940938-179e-42fd-bbaa-a3cfce31419a">

<img width="1370" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/74348508/144af8ef-d3b0-46ee-97cf-02e62aae3c31">

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team
