### ISSUE TITLE
代码默认调用的函数有问题

### ISSUE THREAD

**Issue by tyl569** [LeetCode-Feedback/LeetCode-Feedback#186]
** Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
题目 [191. 位1的个数](https://leetcode-cn.com/problems/number-of-1-bits/) 使用PHP语言，系统默认提供的函数名是 **reverseBits**，但是在代码执行的时候，系统调用的函数是 **hammingWeight**，所以在提交的时候，会出现fatal的报错

**你使用的语言**
PHP

**你提交或者运行的代码**

**期望行为**
将系统调用的函数改为hammingWeight

**屏幕截图**
![WX20200425-092231](https://user-images.githubusercontent.com/8981277/80267954-56773e00-86d6-11ea-99f3-bffe14b23196.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，此问题已转给技术团队会尽快确认的～

**Comment by feiceh** [comment]
已修复

**Comment by tyl569** [comment]
能不能确认修复之后再close
