### ISSUE TITLE
Missing Test Case - 1287. (Wrong solution pass testcases)

### ISSUE THREAD

**Issue by treekonn** [LeetCode-Feedback/LeetCode-Feedback#18601]
### LeetCode 
sunnoca https://leetcode.com/sunnoca/

### Problem number, title, and link
1287. Element Appearing More Than 25% In Sorted Array
https://leetcode.com/problems/element-appearing-more-than-25-in-sorted-array/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

You can read [discussion](https://leetcode.com/problems/element-appearing-more-than-25-in-sorted-array/solutions/4389154/kotlin-beats-100-160ms/)

### Language used for code
Kotlin & Java

### Code used for Submit/Run operation
```
class Solution {
    fun findSpecialInteger(arr: IntArray): Int {
        var maxValue = arr[0]
        var value = -1

        var maxCounter = 0
        var counter = 0

        val step = when {
            arr.size >= 16 -> arr.size shr 4
            else -> 1
        }

        var i = 0
        while (i < arr.size) {
            when {
                value == arr[i] -> {
                    counter++
                    if (counter > maxCounter) {
                        maxCounter = counter
                        maxValue = value
                    }
                }

                else -> {
                    value = arr[i]
                    counter = 1
                }
            }
            i += step
        }

        return maxValue
    }
}
```

### Expected behavior
Solution is wrong. It's wrong approach, but testcases don't show it

[0,0,0,0,0,0,0,8,8,9,9,9,9,9,9,9,9,9,13,14,45,45,45,45,56,56,56,56,85,85,85,85]

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/31970772/52c11cd2-7750-4064-b4d8-eafd0f8724d8)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/31970772/fd0a48b5-bec8-4523-b002-1697bc788316)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
