### ISSUE TITLE
1287. Element Appearing More Than 25% In Sorted Array

### ISSUE THREAD

**Issue by Matvibhor24** [LeetCode-Feedback/LeetCode-Feedback#18605]
### LeetCode Username
matvibhor24

### Problem number, title, and link
[1287. Element Appearing More Than 25% In Sorted Array](https://leetcode.com/problems/element-appearing-more-than-25-in-sorted-array/)

### Category of the bug
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

I tackled the problem 1287. Element Appearing More Than 25% In Sorted Array. The task was to find the integer in a non-decreasing order array that occurs more than 25% of the time. The problem provided and constraints:
1 <= arr.length <= 10^4
0 <= arr[i] <= 10^5

The test case in question is when the input array arr "contains only one element", such as [2]. The expected output is 2, but the code erroneously returned 1 for every case in which input array contains a single element.

Let's take an example test case :
input arr = [2]

The below code returns the wrong output - "1" for the above example test case and as such should fail, but it passes all given tests and gets submitted.

### Code used for Submit/Run operation

```
//Element Appearing More Than 25% In Sorted Array

class Solution {
public:
    int findSpecialInteger(vector<int>& arr) {
        int curr = arr[0];
        int siz = arr.size();
        int count = 1;
        for (int i = 1 ; i<siz ; i++){
            if (arr[i]==curr){
                count++;
                if (count>(siz/4)){
                    return arr[i];
                }
                else{
                    curr=arr[i];
                    continue;
                }
            }
            else{
                count=1;
                if (count>(siz/4)){
                    return arr[i];
                }
                else{
                    curr=arr[i];
                    continue;
                }
            }
        }
        return 1;
    }
};
```

### Expected behavior
The code should correctly handle the case when the array has only one element and return that element. In the given example, the expected output is 2.

### Screenshots
-> Screenshot 1 (my code is giving the wrong answer for this test case)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/99306756/94434f1a-3c93-4152-8d91-c30c0a8873f2)

-> Screenshot 2 (But my code got Accepted)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/99306756/ca5383e4-e72f-4967-8e85-8b2eecaf3ce6)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
