### ISSUE TITLE
Missing Test Case - 1696. Jump Game VI

### ISSUE THREAD

**Issue by kirtika27** [LeetCode-Feedback/LeetCode-Feedback#1860]
#### Description of the bug
One missing testcase is **{[1,-5,-3,-7,3], k=3}.** 
The code I submitted using dequeue passed even when it was giving wrong answer for the above testcase.
My answer from the code below: -1
Correct answer: 1
#### Code you used for Submit/Run operation
```
public int maxResult(int[] nums, int k) {
        int len = nums.length;
        Deque<Integer> dq = new LinkedList<Integer>();
        dq.addFirst(nums[0]);

        for (int i=1;i<len;i++)
        {
            dq.addLast(dq.getFirst() + nums[i]);
            
            while (dq.size() > k || (dq.size() > 1 && dq.getFirst() <= dq.getLast()))
                dq.removeFirst();
        }
        
        return dq.getLast();
}
```
#### Language used for code
Java
#### Your LeetCode username
kirtika27
#### Expected behavior
I expected my solution to not be Accepted. Instead it was Accepted.

**Comment by lc-kay** [comment]
Hi @kirtika27 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @kirtika27 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by kirtika27** [comment]
My leetcode ID is kirtika27.
Profile Link: https://leetcode.com/kirtika27/
