### ISSUE TITLE
Wrong description - 2687. Bikes Last Time Used

### ISSUE THREAD

**Issue by xelplogoog** [LeetCode-Feedback/LeetCode-Feedback#18610]
### LeetCode Username
c4tdog

### Problem number, title, and link
[2687. Bikes Last Time Used](https://leetcode.com/problems/bikes-last-time-used/)

### Category of the bug
- [ ] Problem description

### Description of the bug
Description says `Return the result table ordered by the bikes that were most recently used.` but it is accepted w/o any ordering

accepted submission https://leetcode.com/problems/bikes-last-time-used/submissions/1117533216/

### Language used for code
mysql

### Code used for Submit/Run operation
```
select bike_number, max(end_time) as end_time
from bikes
group by bike_number
```

### Screenshots

<img width="256" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2188302/c9f77461-a5bd-4ada-88db-a604dd25326a">

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
