### ISSUE TITLE
 Dijkstra's Algorithm test problem doesn't have the video explanation

### ISSUE THREAD

**Issue by callmeocean** [LeetCode-Feedback/LeetCode-Feedback#18611]
### LeetCode Username

marki_young

### Problem number, title, and link

https://leetcode.com/explore/learn/card/graph/622/single-source-shortest-path-algorithm/3862/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug

On the Graph explore card, there's an explanation of Dijkstra's algorithm, after that there's a test problem for the algorithm, which is "Network Delay Time"(https://leetcode.com/explore/learn/card/graph/622/single-source-shortest-path-algorithm/3863/) but it doesn't have a video explanation to it, all the other test problems for other algorithms have video explanations, would be nice to have a video explanation for this one.

Sorry, I know it's not a bug, more like a feature request, but I didn't see where else to put it.

### Language used for code

C#

### Code used for Submit/Run operation

N/A

### Screenshots

<img width="1600" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/33929230/ff63aedb-cba5-493c-8fe8-5508934fd08b">

**Comment by LC-Pam** [comment]
Hi there

Thank you for taking the time to share your feedback with us! Your input is valuable, and we appreciate your contribution to making LeetCode even better.

While I can't provide an immediate confirmation, I'll make sure to pass your feedback along to the team for consideration.

If you ever have more thoughts, suggestions, or questions, feel free to reach out. We're here to listen and continuously improve your experience on LeetCode.

Thanks again for being part of our community!

Best regards,

Leetcode Team
