### ISSUE TITLE
Problem description Issue - 777. Swap Adjacent in LR String

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#18623]
### LeetCode Username
pgmreddy

### Problem number, title, and link
777. Swap Adjacent in LR String

### Category of the bug
- [x] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

> return True if and only if there exists a sequence of moves to transform one string to the other.

Above is confusing `one string to the other`, says we can do both ways,
This took 2 days of my time.

Please fix imm,ly.

Had worst experience in this problem
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/8236389/3216cab3-7944-4a61-88e3-0b0b6297531b)

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

### Expected behavior

The problem statement should clear & complete

See several others reports same
https://leetcode.com/problems/swap-adjacent-in-lr-string/solutions/173982/incorrect-test-case/comments/196398

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/8236389/eab6a5ba-d01e-4c5f-ab08-0dca792267e3)

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/8236389/1d3f0571-e471-4738-949a-d63f66435775)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
