### ISSUE TITLE
373. Find K Pairs with Smallest Sums - TLE

### ISSUE THREAD

**Issue by luizsjr** [LeetCode-Feedback/LeetCode-Feedback#18626]
### LeetCode Username
[luizsjr](https://leetcode.com/luizsjr)

### Problem number, title, and link

[373. Find K Pairs with Smallest Sums](https://leetcode.com/problems/find-k-pairs-with-smallest-sums)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [X] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
The test case where we have huge nums1 and nums2 filled with [1,1] pairs and k = 10000 TLEs doesnt matter what you do.
I tested the copy and pasted the editorial Java version and it TLE. I tested the my implementation in JS and it TLE I even 
tested  adding a guardrail like `if (k === 10000) return new Array(10000).fill([1,1]);` and it TLEs.

### Language used for code
JS, Java

### Code used for Submit/Run operation

```
var kSmallestPairs = function(nums1, nums2, k) {
    // if (k === 10000) return new Array(10000).fill([1,1]);
    const I = nums1.length;
    const J = nums2.length;

    const visited = new Set();
    const minHeap = new MinPriorityQueue();
    const answer = [];

    const heapPush = (i, j) => {
        const key = `${i}_${j}`;
        if (!visited.has(key) && i < I && j < J) {
            visited.add(key);
            minHeap.enqueue([i, j], nums1[i] + nums2[j]);
        }
    }

    heapPush(0,0);
    while (answer.length < k && minHeap.size()) {
        const [i, j] = minHeap.dequeue().element;
        answer.push([ nums1[i], nums2[j] ]);
        heapPush(i, j + 1);
        heapPush(i + 1, j);
    }
    return answer;
};
```

### Expected behavior
The test should pass

### Screenshots

![Screen Shot 2023-12-12 at 10 49 41 AM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/37640068/77cae48e-91e0-4228-a657-f7960def24de)

![Screen Shot 2023-12-12 at 10 46 47 AM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/37640068/964755cb-66bd-4415-a691-188824fdf7b6)

![Screen Shot 2023-12-12 at 10 47 55 AM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/37640068/250c6c64-7b7e-4010-a236-566ae116a286)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission Accepted link. 

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by burcel** [comment]
Hello,

I'm also experiencing the same type of problem. I tried solving the problem using heap and set in Python. I don't know if TLE is the expected result here but the editorial solution also gives TLE so I suspected something might be wrong. Here is my submission link if it can provide more information related to the issue:

https://leetcode.com/submissions/detail/1118951771/

**Comment by luizsjr** [comment]
Here are two submission links:
Java - https://leetcode.com/problems/find-k-pairs-with-smallest-sums/submissions/1118155578/
JS - https://leetcode.com/problems/find-k-pairs-with-smallest-sums/submissions/1118464165/

**Comment by b06b01073** [comment]
It seems like the code in the [editorial section](https://leetcode.com/problems/find-k-pairs-with-smallest-sums/editorial/) runs into the problem of TLE as well.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team

**Comment by luizsjr** [comment]
I don't think its fixed. I'm still getting TLE:
Java submission - https://leetcode.com/problems/find-k-pairs-with-smallest-sums/submissions/1120703179
JS submission - https://leetcode.com/problems/find-k-pairs-with-smallest-sums/submissions/1120702864

Please note the Java submission is the editorial code.

**Comment by zawataki** [comment]
I'm still getting TLE also.

**Comment by luizsjr** [comment]
@LC-Pam Can you please re-open the ticket as the issue was not fixed?
