### ISSUE TITLE
Missing Test Case - 1622. Fancy Sequence

### ISSUE THREAD

**Issue by suru003** [LeetCode-Feedback/LeetCode-Feedback#1862]
#### Category of the bug
- [ ] Question

#### Code you used for Submit/Run operation

```
class Fancy:
    ls = []
    def __init__(self):
        ls = list([])
        
    def append(self, val: int) -> None:
        self.ls.append(val)
        print(self.ls)
        

    def addAll(self, inc: int) -> None:
        for i in range(len(self.ls)):
            self.ls[i]+=inc
        print("addAll ",self.ls)
        
    def multAll(self, m: int) -> None:
        for i in range(len(self.ls)):
            self.ls[i]*=m
        print("multAll ",self.ls)
        
    def getIndex(self, idx: int) -> int:
        if(idx>=len(self.ls)):
            return -1
        return self.ls[idx]%1000000007


# Your Fancy object will be instantiated and called as such:
# obj = Fancy()
# obj.append(val)
# obj.addAll(inc)
# obj.multAll(m)
# param_4 = obj.getIndex(idx)
```

#### Screenshots

![Screenshot (251)](https://user-images.githubusercontent.com/31486779/103594514-1e0b3f00-4eb6-11eb-98f7-ad8f39f15090.png)

**Comment by lc-kay** [comment]
@suru003 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
