### ISSUE TITLE
Solution typo - 11. Container With Most Water

### ISSUE THREAD

**Issue by nishantmendiratta** [LeetCode-Feedback/LeetCode-Feedback#18636]
### LeetCode Username
[thatjsdev](https://leetcode.com/thatjsdev/)

### Problem number, title, and link
**11**. Container With Most Water https://leetcode.com/problems/container-with-most-water

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug
There is a typo in the following line of editorial. Please see the screenshot for more.
> Futher, we maintain a variable

### Expected behavior
It should be 
> Further, we maintain a variable

### Screenshots

<img width="711" alt="Screenshot 2023-12-13 at 12 26 44 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2558220/6dc066fb-c07f-4b0b-aa90-9c829ece86ea">

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team

**Comment by nishantmendiratta** [comment]
Received, thank you :)
