### ISSUE TITLE
Improvements to MyLinkedList explanation

### ISSUE THREAD

**Issue by aleksandr-kiliushin** [LeetCode-Feedback/LeetCode-Feedback#18632]
### LeetCode Username
aleksandr-kiliushin

### Problem number, title, and link
https://leetcode.com/explore/learn/card/linked-list/209/singly-linked-list/1298/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
1. A redundant `return;` in code. The function is already ended.
2. There is not point 4. between 3. and 5.

### Screenshots
<img width="928" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/65129988/90957a67-2c3a-42c9-99ad-40b6cee2d985">

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team
