### ISSUE TITLE
Missing Test Case - 2722. Join Two Arrays by ID

### ISSUE THREAD

**Issue by Sixlty** [LeetCode-Feedback/LeetCode-Feedback#18643]
### LeetCode Username

sixlty

### Problem number, title, and link

https://leetcode.cn/problems/join-two-arrays-by-id/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Missing test cases lead to buggy code passing

### Language used for code

Javascript

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
var join = function(arr1, arr2) {
    let i = 0
    let j = 0
    let arr = []
    while(i < arr1.length && j < arr2.length) {
        if(arr1[i].id === arr2[j].id) {
            arr.push({
                ...arr1[i],
                ...arr2[j]
            })
            i++; j++
        } else if(arr1[i].id > arr2[j].id) {
            arr.push(arr2[j])
            j++
        } else if(arr1[i].id < arr2[j].id) {
            arr.push(arr1[i])
            i++
        }
    }
    if(j === arr2.length) {
        arr = arr.concat(arr1.slice(i))
    }
    if(i === arr1.length) {
        arr = arr.concat(arr2.slice(j))
    }
    arr.sort((a,b) => a.id -b.id)
    
    return arr
};
// above and below the code.
```

### Expected behavior

It should indicate that the answer is wrong and should not be passed

### Screenshots

![微信图片_20231213175318](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/41572049/d1e2de65-42c3-4ff8-a3df-ae38855a52a7)

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/41572049/b5eaed19-edf2-42e1-89c9-4dd2eeccb266)

### Additional context

I wrote a test case that reported an error, but the commit passed!
Try input it: 
[{"id": 1,"x": 1},{"id": 2,"x": 9}]
[{"id": 3,"x": 5}, {"id": 1,"x": 1}]

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
