### ISSUE TITLE
Missing Test Case - 2893. Calculate Orders Within Each Interval

### ISSUE THREAD

**Issue by Shargano** [LeetCode-Feedback/LeetCode-Feedback#18648]
### LeetCode Username
Shargano - https://leetcode.com/Shargano/

### Problem number, title, and link

  2893. Calculate Orders Within Each Interval https://leetcode.com/problems/calculate-orders-within-each-interval/

### Category of the bug
- [x] Problem description
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug
At the problem description mentioned `Return the result table ordered by interval_no in ascending order.`
But, there is no test case ensuring solution ordering.
My solution was accepted, even though I didn't use ordering at all...

### Language used for code
SQL (MySQL)

### Code used for Submit/Run operation
```
select
    ceiling(minute / 6) as interval_no,
    sum(order_count) as total_orders
from Orders
group by interval_no
```

### Expected behavior
This code shouldn't be accepted.

### Additional context
Here is simple test case, where my code fails, but still, it was accepted.
Items of second interval comes before items of first interval:

```
| minute | order_count |
| ------ | ----------- |
| 7      | 1           |
| 8      | 2           |
| 9      | 4           |
| 10     | 1           |
| 11     | 4           |
| 12     | 6           |
| 1      | 0           |
| 2      | 2           |
| 3      | 4           |
| 4      | 6           |
| 5      | 1           |
| 6      | 4           |
```

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
