### ISSUE TITLE
Missing Test Case - 26. Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by mena149f** [LeetCode-Feedback/LeetCode-Feedback#1864]
Simply I created a solution that return 1 if an empty array is passed.
This is wrong.
but your platform accepted it.

**Comment by lc-kay** [comment]
@mena149f Please submit the code that this issue occurred on. Thank you!

**Comment by lc-kay** [comment]
Hi @mena149f 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
