### ISSUE TITLE
Missing Test Case - 220. Contains Duplicate III

### ISSUE THREAD

**Issue by mustafadawoodi** [LeetCode-Feedback/LeetCode-Feedback#18640]
### LeetCode Username
mustafadawoodi53

### Problem number, title, and link
1. 220 Contains duplicate 3 https://leetcode.com/problems/contains-duplicate-iii/

### Category of the bug
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### Description of the bug
the output should be false according to the test case but it shows the expected output to be true.
The inputs were nums =
[1,0,1,1]
indexDiff =
1
valueDiff =
2

### Language used for code
C++

### Code used for Submit/Run operation

```
class Solution {
public:
    bool containsNearbyAlmostDuplicate(vector<int>& nums, int indexDiff, int valueDiff) {
        for(int i=0;i<nums.size();i++){
            for (int n=i+indexDiff;n<nums.size();n++){
                if((i!=n)&&(abs(nums.at(i)-nums.at(n))==valueDiff)){
                    return true;
                }
            }
        }
        return false;
    }
};
// Paste your code here. Don't remove ``` given
// above and below the code.
```

### Expected behavior
the expected behavior should be false a diffValue cannot be 2

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
