### ISSUE TITLE
Missing Test Case - 744. Find Smallest Letter Greater Than Target

### ISSUE THREAD

**Issue by Bhhsaurabh** [LeetCode-Feedback/LeetCode-Feedback#18645]
I faced issue while solving this question: 

class Solution {
    public char nextGreatestLetter(char[] letters, char target) {
        int start = 0;
        int end = letters.length -1;
        while(start<=end){
            int mid = start + (end - start)/2;
            if(target<letters[mid]){
                end = mid - 1;
            }else {
                start  = mid +  1;
            }
        }
        return letters[start % letters.length];
        
    }
} 

there is issue in solution in middle part :

1.  if(target<letters[mid]){
                end = mid - 1;
            }else {
                start  = mid +  1;
            }
        } only this is true.

where as these two are same ------ but it making it incorrect
2. 
if(target>letters[mid]){
                start = mid + 1;
            }else if(target < letters[mid]){
                end = mid - 1;
            } this showing incorrect
3.
 if(target>letters[mid]){
                start = mid + 1;
            }else {
                end = mid - 1;
            } this also showing incorrect in complier

**Comment by Bhhsaurabh** [comment]
if you known about this help!

**Comment by LC-Pam** [comment]
Thank you for your time.

We encourage you to share your questions in the discussion forum, where the community can provide insights and assistance.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
