### ISSUE TITLE
Missing Test Case - 2853. Highest Salaries Difference

### ISSUE THREAD

**Issue by Shargano** [LeetCode-Feedback/LeetCode-Feedback#18652]
### LeetCode Username
Shargano - https://leetcode.com/Shargano/

### Problem number, title, and link
2853. Highest Salaries Difference  https://leetcode.com/problems/highest-salaries-difference/

### Category of the bug
- [x] Problem description
- [x] Problem constraints
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug
It's not mentioned in the problem description, that `department` is enum of only 2 possible values (`Marketing` and `Engineering`). So I tried to use other `department` name.

### Language used for code
SQL (PostgreSQL)

### Code used for Submit/Run operation
Accepted solution:
```
select abs(max(max_salary) - min(max_salary)) as salary_difference
from (
    select department, max(salary) as max_salary
    from Salaries
    group by department
)
```

### Expected behavior
I suppose, that in problem description or constraints should be mentioned that `department` could be either `Marketing` or `Engineering`. Otherwise, there should be test case with different `department` (provided below).

### Additional context
Failed test case with accepted code:

| emp_name | department  |  salary  |
| ----------- | ------------ | --------|
|    Edward    | Engineering | 102000 |
|     Evelyn    |   Marketing   | 53000  |
|      John      |       Other      |  3000   |

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
