### ISSUE TITLE
Mistake in editorial in the the problem 2482

### ISSUE THREAD

**Issue by Hr1t1k** [LeetCode-Feedback/LeetCode-Feedback#18668]
### LeetCode Username

Hritik__k

### Problem number, title, and link

[2482. Difference Between Ones and Zeros in Row and Column](https://leetcode.com/problems/difference-between-ones-and-zeros-in-row-and-column/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
-  Editorial
- [ ] Programming language support

### Description of the bug

In the editorial of this problem there is one mistake , the line ->
" However, when we iterate over the ith row to find the number of ones, we can also find the add the number of ones/zeroes for all the columns in that row. " 
here, "we can also find the add the number of ones" does not make sense 

### Screenshots

![leetcode 14dec eror](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/52287344/841f3bab-6a39-468b-90e8-054e39be6ff4)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team

**Comment by LC-Pam** [comment]
Hi there, the 100 Leetcoins were deducted from this issue due to we found you submitted the same ticket on Zendesk Ticket #223470, the reward was duplicated for the same issue.
