### ISSUE TITLE
Editorial's figure related issue - 2482. Difference Between Ones and Zeros in Row and Column

### ISSUE THREAD

**Issue by aminabbasov** [LeetCode-Feedback/LeetCode-Feedback#18666]
### LeetCode Username
https://leetcode.com/aminabbasov/

### Problem number, title, and link

2482. Difference Between Ones and Zeros in Row and Column
https://leetcode.com/problems/difference-between-ones-and-zeros-in-row-and-column/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [X] Editorial
- [ ] Programming language support

### Description of the bug

The matrix representation in the editorial contains an error: `onesCol` and `onesRow` are swapped.

### Expected behavior

`onesCol` must be: `[1, 1, 3]`
`onesRow` must be: `[2, 2, 1]`

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/105433550/4570469e-aaf3-4f3b-89d1-e067a61b7c4f)

### Additional context

If you didn't grasp the essence, for better understanding, imagine that a matrix on image is `2 x 3`, i.e., `[0,1,1],[1,0,1]`. In this case, `onesCol` in the illustration should be `[1, 1, 2]`, but the matrix only has two columns, not three, so the array cannot fit in size into the left corner of the image. Similarly, `onesRow` will be `[2, 2]`, but the length of the matrix rows will be greater.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission Accepted link. 
Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
