### ISSUE TITLE
Missing Test Case - 65. Valid Number

### ISSUE THREAD

**Issue by Sanskar777** [LeetCode-Feedback/LeetCode-Feedback#18665]
### LeetCode Username

sanskaragarwal

### Problem number, title, and link

65. Valid Number https://leetcode.com/problems/valid-number/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

Missing test Case :

Input : "++5"

### Description of the bug

 
The above test case is an edge case which is missing

### Language used for code

c++

### Code used for Submit/Run operation

```
class Solution {
public:
    bool isNumber(string s) {
        bool isEPresent = false;
        int index=-1;
        for(int i=0;i<s.size();i++) {
            if(s[i]=='e' || s[i]=='E') {
                isEPresent = true;
                index = i;
                break;
            }
        }
        if(isEPresent){
            string p1 = s.substr(0,index);
            string p2 = s.substr(index+1,s.size());
            return (isValidInteger(p1) || isValidDecimal(p1)) && isValidInteger(p2);
        } else {
            return (isValidInteger(s) || isValidDecimal(s));
        }
        return false;
    }
    bool isValidInteger(string s) {
        if(s.size()==0)return false;
        bool isSignedInteger = false;
        if(s[0]=='+' || s[0]=='-')isSignedInteger = true;
        if(isSignedInteger) return isValidInteger(s.substr(1,s.size()));
        for(int i=0;i<s.size();i++){
            char ch = s[i];
            if(ch>='0' && ch<='9')continue;
            else return false;
        }
        return true;
    }
    bool isValidDecimal(string s) {
        if(s.size()==0)return false;
        bool isSigned = false;
        if(s[0]=='+' || s[0]=='-')isSigned = true;
        if(isSigned)return isValidDecimal(s.substr(1,s.size()));
        bool isDotPresent = false;
        int index=-1;
        for(int i=0;i<s.size();i++){
            if(s[i]=='.'){
                isDotPresent = true;
                index = i;
                break;
            }
        }
        if(!isDotPresent)return false;
        string p1 = s.substr(0,index);
        string p2 = s.substr(index+1,s.size());
        if(p1.size()==0 && p2.size()==0)return false;
        return checkValidDigits(p1) && checkValidDigits(p2);
    }
    bool checkValidDigits(string p1) {
        for(int j=0;j<p1.size();j++){
            char ch = p1[j];
            if(ch>='0' && ch<='9')continue;
            else return false;
        }
        return true;
    }
};
```

### Expected behavior

My code should have failed for the above mentioned test case

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
