### ISSUE TITLE
Missing Test Case - 177. Nth Highest Salary

### ISSUE THREAD

**Issue by AgentIvan** [LeetCode-Feedback/LeetCode-Feedback#18678]
### Problem number, title, and link
https://leetcode.com/problems/nth-highest-salary/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Language used for code
- Python
- MySQL
- MS-SQL
- T-SQL
- PL/SQL

### Code used for Submit/Run operation

```MySQL
CREATE FUNCTION getNthHighestSalary(N INT) RETURNS INT
BEGIN
  SET N = N - 1;
  RETURN (
    # Write your MySQL query statement below.
    SELECT DISTINCT(salary)
      FROM Employee
      ORDER BY salary DESC
      LIMIT N, 1
  );
END
```
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/16723960/4f5474a0-85a3-4c05-bd67-aff998fa1c4a)
```Python
import pandas as pd

def nth_highest_salary(employee: pd.DataFrame, N: int) -> pd.DataFrame:
  column = f"getNthHighestSalary({N})"
  unique_salaries = pd.unique(employee["salary"])
  if N > len(unique_salaries):
    return pd.DataFrame({ column: [None] })

  return pd.DataFrame({ column: [sorted(unique_salaries,reverse=True)[N-1]] })
```
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/16723960/aa2d8ab2-53a3-4a4c-b309-643b88bac855)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/16723960/b6723f1b-2110-4e0b-988b-c8d7d0b7cb7b)

**Comment by AgentIvan** [comment]
Also your code that calculates return `Null` for argument = 0 and first salary for any argument < 0

**Comment by AgentIvan** [comment]
Also your code that calculates return `Null` for `argument = 0` and `minimal salary` for any `argument < 0`
that is not correct

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Hi there,

Your feedback has been instrumental in enhancing the problem. 

To ensure you receive your well-deserved 100 LeetCoins reward, could you kindly provide us with your LeetCode username? This will allow us to credit your account accurately.

Your participation and contributions are valued, and we want to make sure you enjoy the rewards you've earned.

Thank you for being part of the LeetCode community!

Best regards,
LeetCode Team

**Comment by AgentIvan** [comment]
this is my account
https://leetcode.com/AgentIvan/
Thanks

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
