### ISSUE TITLE
Hash table space complexity - LeetCode's Interview Crash Course Data Structures and Algorithms 

### ISSUE THREAD

**Issue by eliaguerra** [LeetCode-Feedback/LeetCode-Feedback#18676]
### Category of the bug
- [ ] Problem description
- [x] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug

The space complexity of an Hash table lacks of coherence (https://leetcode.com/explore/interview/card/leetcodes-interview-crash-course-data-structures-and-algorithms/705/hashing/4511/). In Example 1, the space complexity is O(n) where n the length of the input array and the maximum number of keys that the hash table might store. In Example 2, the space complexity of the set is O(m) where m is "is the number of allowable characters in the input" and not the length of the input string identified with n. In Example 3, the space complexity of the set is O(n) where n is the size of the input array. 

In my opinion, the space complexity of Example 2 should be O(n) to be coherent with the other examples. 

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

When discussing strings, we rarely assume that the number of unique characters is close to the length of the string in big O notation. This is fundamentally different from arrays.
In most scenarios, the size of the input data n dominates the analysis, and the size of the character set m remains relatively constant. For English alphabets or common characters, it's usually safe to assume a constant size, but in more general cases, it may indeed depend on the size of the character set, which has been explained in detail by the author. Thus the original text is coherent.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
