### ISSUE TITLE
Missing Test Case - 409. Longest Palindrome

### ISSUE THREAD

**Issue by prathamshirol** [LeetCode-Feedback/LeetCode-Feedback#18671]
Input
s ="ababbaba"

Output
8

Expected
8

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission Accepted link. 


Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team
