### ISSUE TITLE
Incorrect test case in problem 2101 Detonate the Maximum Bombs

### ISSUE THREAD

**Issue by tomli380576** [LeetCode-Feedback/LeetCode-Feedback#18685]
### Problem number, title, and link

2101 Detonate the Maximum Bombs https://leetcode.com/problems/detonate-the-maximum-bombs

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

I believe the following test case is incorrect:

```py
bombs = [
    [54, 95, 4],
    [99, 46, 3],
    [29, 21, 3],
    [96, 72, 8],
    [49, 43, 3],
    [11, 20, 3],
    [2, 57, 1],
    [69, 51, 7],
    [97, 1, 10],
    [85, 45, 2],
    [38, 47, 1],
    [83, 75, 3],
    [65, 59, 3],
    [33, 4, 1],
    [32, 10, 2],
    [20, 97, 8],
    [35, 37, 3],
]
```

if we graph all the circles, there will be 2 circles intersecting each other, so this test case is analogous to example 1 and the answer should be 2. But the test case says 1. 

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/60045212/17c5f57f-a17f-496e-971b-a4745a15b7c6)

### Additional context

To graph the circles:

```py
arr = [
    [54, 95, 4],
    [99, 46, 3],
    [29, 21, 3],
    [96, 72, 8],
    [49, 43, 3],
    [11, 20, 3],
    [2, 57, 1],
    [69, 51, 7],
    [97, 1, 10],
    [85, 45, 2],
    [38, 47, 1],
    [83, 75, 3],
    [65, 59, 3],
    [33, 4, 1],
    [32, 10, 2],
    [20, 97, 8],
    [35, 37, 3],
] # any problem input can go into arr

from matplotlib import pyplot as plt

fig, ax = plt.subplots()
plt.gca().set_aspect("equal")
ax.set_xlim(xmin=0, xmax=90)
ax.set_ylim(ymin=0, ymax=90)

for x, y, r in arr:
    circle = plt.Circle((x, y), r, color="blue", clip_on=False, fill=False)
    ax.add_patch(circle)
```

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by tredsused40** [comment]
The reason is, bomb detonates other bomb only when it hits the exact position of that other bomb, read the sample test case explanation, it is explained here. The bomb detonates all other bombs that lie in it's range, not every bomb that has intersection of it's explosion area with area of the one that explodes first.

**Comment by tomli380576** [comment]
Thanks! Looks like I misunderstood the problem
