### ISSUE TITLE
Missing Test Case - 607. Sales Person

### ISSUE THREAD

**Issue by ArmaanjeetSandhu** [LeetCode-Feedback/LeetCode-Feedback#18683]
### LeetCode Username
ArmaanjeetSandhu

### Problem number, title, and link
607. Sales Person https://leetcode.com/problems/sales-person

### Category of the bug
[✓] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug
If a salesperson is associated with multiple companies including 'RED', and their non-'RED' association appears first in the merged dataframe, the `drop_duplicates` method used in my code incorrectly retains this salesperson. This leads to including salespersons in the output who should be excluded due to their association with 'RED'.

So, there needs to be a testcase that accounts for this. For example (Pandas Schema):
```
import pandas as pd

data = [[1, 'John', 100000, 6, '4/1/2006'], [2, 'Amy', 12000, 5, '5/1/2010'], [3, 'Mark', 65000, 12, '12/25/2008'], [4, 'Pam', 25000, 25, '1/1/2005'], [5, 'Alex', 5000, 10, '2/3/2007'], [6, 'Emma', 45000, 8, '6/1/2009']]
sales_person = pd.DataFrame(data, columns=['sales_id', 'name', 'salary', 'commission_rate', 'hire_date']).astype({'sales_id':'Int64', 'name':'object', 'salary':'Int64', 'commission_rate':'Int64', 'hire_date':'datetime64[ns]'})
data = [[1, 'RED', 'Boston'], [2, 'ORANGE', 'New York'], [3, 'YELLOW', 'Boston'], [4, 'GREEN', 'Austin']]
company = pd.DataFrame(data, columns=['com_id', 'name', 'city']).astype({'com_id':'Int64', 'name':'object', 'city':'object'})
data = [[1, '1/1/2014', 3, 4, 10000], [2, '2/1/2014', 4, 5, 5000], [3, '3/1/2014', 1, 1, 50000], [4, '4/1/2014', 1, 4, 25000], [5, '5/1/2014', 1, 6, 30000], [6, '5/1/2014', 3, 6, 15000]]
orders = pd.DataFrame(data, columns=['order_id', 'order_date', 'com_id', 'sales_id', 'amount']).astype({'order_id':'Int64', 'order_date':'datetime64[ns]', 'com_id':'Int64', 'sales_id':'Int64', 'amount':'Int64'})
```

### Language used for code
Pandas

### Code used for Submit/Run operation

```
import pandas as pd

def sales_person(sales_person: pd.DataFrame, company: pd.DataFrame, orders: pd.DataFrame) -> pd.DataFrame:
    full = company.merge(orders, how = 'outer', on = 'com_id').merge(sales_person, how = 'outer', on = 'sales_id')
    full.rename(columns = {'name_x':'company_name', 'name_y':'name'}, inplace = True)
    full.sort_values('company_name', ascending = False, inplace = True)
    full.drop_duplicates('name', inplace = True)
    return full[full['company_name'] != 'RED'][['name']].dropna()
```

### Expected behavior
The expected behavior of the function is to exclude all salespersons who have any association with the company 'RED', regardless of their associations with other companies. This means even if a salesperson is associated with multiple companies, if one of those companies is 'RED', that salesperson should not appear in the output. With my code, 'Emma' incorrectly appears in the output since her 'YELLOW' association is processed before her 'RED' association.

### Screenshots
![func1](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/90208595/07404f9a-e4ba-4e0c-be9a-6787af06593f)

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
