### ISSUE TITLE
整数翻转

### ISSUE THREAD

**Issue by angelaza** [LeetCode-Feedback/LeetCode-Feedback#18689]
class Solution:
    def reverse(self, x: int) -> int:
        x=str(x)
        x=x[::-1]
        
        if x[0]==0:
            x=int(x[1:])
        elif x[-1]=="-":
            x=-int(x[:-1])
        else:
            x=int(x)
        
        
        return x if -2147483648 < x < 2147483647 else 0

**Comment by amcones-lc** [comment]
感谢反馈，能否向我们补充题目信息，以及完善代码格式，把信息提供完整才能有助于快速验证和精准的定位，谢谢。
