### ISSUE TITLE
Elements are not displayed on the page "Design Singly Linked List - Solution" || macOS(Safari, Chrome)

### ISSUE THREAD

**Issue by roman-sundurov** [LeetCode-Feedback/LeetCode-Feedback#18694]
### Problem number, title, and link
Design Singly Linked List - Solution https://leetcode.com/explore/learn/card/linked-list/209/singly-linked-list/1298/

### Category of the bug
- [ ] Problem description

### Description of the bug
The images(or block with code) do not load when opening the page. The error was reproduced on a Macbook Pro (16-inch, 2019) using Safari and Chrome. Please take a look at the screenshot for more information.

### Screenshots
<img width="1786" alt="Screenshot 2023-12-15 at 12 44 03 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/68818066/b8ae232a-e80c-4e47-aafc-89cc9211e65c">

### Additional context
Device: Macbook Pro (16-inch, 2019)
OS: macOS 14.2 (23C64)
Safari: Version 17.2 (19617.1.17.11.9)
Chrome: Version 120.0.6099.109 (Official Build) (x86_64)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by luciphania** [comment]
Thank you for your time.

Your feedback has been used to enhance the problem. 
If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
