### ISSUE TITLE
Missing Test Case - 2014. Longest Subsequence Repeated k Times

### ISSUE THREAD

**Issue by JosephVonFeldt** [LeetCode-Feedback/LeetCode-Feedback#18696]
### LeetCode Username

uchmn

### Problem number, title, and link

2014. Longest Subsequence Repeated k Times https://leetcode.com/problems/longest-subsequence-repeated-k-times/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Code that does not  always return the lexicographically largest subsequence of max length is being accepted.
#### Proposed test case: 
"abcacb"
2

### Language used for code

Python 3

### Code used for Submit/Run operation

```
from collections import Counter
class Solution:
    def longestSubsequenceRepeatedK(self, s: str, k: int) -> str:
        def contained(subsequence):
            i = 0
            for c in s:
                if subsequence[i%len(subsequence)] == c:
                    i+=1
                    if i// len(subsequence) == k:
                        break
            return i == len(subsequence)*k

        cm = 0
        base = [c for c,v in Counter(s).items() if v >=k]
        curr = base.copy()
        curr.sort(reverse=True)
        while True:
            nxt = []
            for sub in curr:
                for b in base:
                    if contained(sub+b):
                        nxt.append(sub+b)
            if nxt:
                curr = nxt
            else:
                break
        
        
        return curr[0] if curr else ''
```

### Expected behavior

Code should be rejected with a Wrong Answer.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/43918070/c2f50c24-597b-4726-9d3b-2de30e056234)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/43918070/721c963b-0cc2-4c60-a07b-162539df8870)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
