### ISSUE TITLE
Missing Test Case - 546. Remove Boxes

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#1869]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ √] Solution
- [ ] Language

#### Description of the bug

The fastest C++ code for 546. Remove Boxes has incorrect running time. Here's a testcase that makes it Time Limit Exceeded.

#### Code you used for Submit/Run operation

```
class Solution {
private:
    int memo[101][101][101] = {};
    int dfs(vector<int>& boxes, int i, int j, int k) {
        if (i > j) return 0;
        if (memo[i][j][k]) return memo[i][j][k];
        while (i < j && boxes[j-1] == boxes[j]) --j, ++k;
        int res = (k+1)*(k+1)+dfs(boxes,i,j-1,0);
        for (int l(i); l < j; ++l) if (boxes[l] == boxes[j]) {
            res = max(res,dfs(boxes,i,l-1,0)+dfs(boxes,l+1,j,k+1));
        }
        return memo[i][j][k] = res;
    }
    
public:
    int removeBoxes(vector<int>& boxes) {
        int n(boxes.size());
        return dfs(boxes, 0, n-1, 0);
    }
};
```

#### Language used for code

C++

#### Expected behavior

The code gets Time Limit Exceeded with the following input:
[1,2,2,1,1,1,2,1,1,2,1,2,1,1,2,2,1,1,2,2,1,1,1,2,2,2,2,1,2,1,1,2,2,1,2,1,2,2,2,2,2,1,2,1,2,2,1,1,1,2,2,1,2,1,2,2,1,2,1,1,1,2,2,2,2,2,1,2,2,2,2,2,1,1,1,1,1,2,2,2,2,2,1,1,1,1,2,2,1,1,1,1,1,1,1,2,1,2,2,1]

#### Screenshots

![1](https://user-images.githubusercontent.com/11583428/103599988-fb842080-4ecb-11eb-9e53-ea12b3c2f6c9.png)

![2](https://user-images.githubusercontent.com/11583428/103600035-20789380-4ecc-11eb-9a8e-161be9d388bf.png)

#### Additional context

A correct implementation is provided here, with the following two lines of change marked with //***:
```
class Solution {
private:
    int memo[101][101][101] = {};
    int dfs(vector<int>& boxes, int i, int j, int k) {
        if (i > j) return 0;
        if (memo[i][j][k]) return memo[i][j][k];
        int j1=j,k1=k;  //***
        while (i < j && boxes[j-1] == boxes[j]) --j, ++k;
        int res = (k+1)*(k+1)+dfs(boxes,i,j-1,0);
        for (int l(i); l < j; ++l) if (boxes[l] == boxes[j]) {
            res = max(res,dfs(boxes,i,l-1,0)+dfs(boxes,l+1,j,k+1));
        }
        return memo[i][j1][k1] = res;  //***
    }
    
public:
    int removeBoxes(vector<int>& boxes) {
        int n(boxes.size());
        return dfs(boxes, 0, n-1, 0);
    }
};
```

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
