### ISSUE TITLE
1070. 产品销售分析 III, 翻译不准确, 描述不清楚.

### ISSUE THREAD

**Issue by bytebeats** [LeetCode-Feedback/LeetCode-Feedback#187]
对于题目 [1070. 产品销售分析 III](https://leetcode-cn.com/problems/product-sales-analysis-iii/) 私以为描述或者说翻译有些不妥当.
对于表单中的属性 **product_id** 是不能够进行翻译的, 而应该使用原文.

描述错误的两个句子:
- 产品 ID 是产品表的外键
- 产品 ID 是此表的主键
修改成以下, 可以更加合适: 
- **product_id** 是产品表的外键
- **product_id** 是此表的主键

望采纳.

**Comment by feiceh** [comment]
Done
