### ISSUE TITLE
Missing Test Case - 1436. Destination City

### ISSUE THREAD

**Issue by tredsused40** [LeetCode-Feedback/LeetCode-Feedback#18700]
### LeetCode Username
tredsused70

### Problem number, title, and link
1436. Destination City https://leetcode.com/problems/destination-city/

### Category of the bug
- [.] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

In order to solve this problem, I used hashes, but the thing is, I've tried to use base from 2 to 13, and every of them got accepted verdict, which is definitely not how it should be, because hash with any base less than the biggest value of element in object that is going to be hashed is extremely weak.

### Language used for code

C++

### Code used for Submit/Run operation

```
class Solution {
public:
    long long fun(string s) {
        long long ans = 0;
        for(char i : s) {
            ans *= 2;
            ans += i - 'a';
        }
        return ans;
    }
    string destCity(vector<vector<string>>& paths) {
        vector < long long > vc (paths.size ());
        for (int i = 0; i < paths.size (); ++i) 
            vc[i] = fun(paths[i][0]);
        sort (vc.begin (), vc.end ());
        vc.push_back(LLONG_MAX);
        for (auto i : paths) {
            if (*lower_bound(vc.begin (), vc.end (), fun(i[1])) != fun(i[1])) 
                return i[1];
        }
        return "-";
    }
};
```

### Expected behavior

For example, lets look at the string of length 2, and it's hash with base x: lets name strings s1 ans s2. Hash of any s of length 2 with base x in my code equals to (s[0] - 'a') * x + s[1] - 'a', which equals to s[0] * x + s[1] - (x + 1) * 'a'. Now, lets write hash value of both s1 and s2, and look when they are equal: s1[0] * x + s1[1] - (x + 1) * 'a' = s2[0] * x + s2[1] - (x + 1) * 'a'. Last term of each side cancels out, so we have (s1[0] - s2[0]) * x = s2[1] - s1[1]. From this equation it's easy to see, that if s1[0] is 1 less than s2[0] and s2[1] is x less than s1[1], then hashes of s1 and s2 will be the same value. For example, if base is 2 and s1 = "ac", s2 = "ba", then hash of both strings is 2. So as we can see, it's extremely easy to break hash with any base from 1 to a, where a is the maximum value of element in object that is going to be hashed. Here is the test that breaks every base from 1 to 26:
[["aa","ab"],["ab","ac"],["ac","ad"],["ad","ae"],["ae","af"],["af","ag"],["ag","ah"],["ah","ai"],["ai","aj"],["aj","ak"],["ak","al"],["al","am"],["am","an"],["an","ao"],["ao","ap"],["ap","aq"],["aq","ar"],["ar","as"],["as","at"],["at","au"],["au","av"],["av","aw"],["aw","ax"],["ax","ay"],["ay","az"],["az","ba"]]
On this test, programm returns "-" for any base from 1 to 25, indicating that there's no such city, that has no outgoing edges, however that's not true, the correct answer is "ba".
### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/75163817/ca4a72a6-c77a-4d99-b470-d1e3c3c7aaff)

### Additional context

I believe any hash with base less than alphabet size shouldn't be accepted, as the probability of collision is unacceptably high in that case.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
