### ISSUE TITLE
Unavailable editorial section - 569. Median Employee Salary

### ISSUE THREAD

**Issue by Shargano** [LeetCode-Feedback/LeetCode-Feedback#18702]
### LeetCode Username
Shargano - https://leetcode.com/Shargano/

### Problem number, title, and link
```
569. Median Employee Salary
```
https://leetcode.com/problems/median-employee-salary/

### Category of the bug
- [x] Editorial

### Description of the bug
I've solved the problem and then tried to compare my solution with editorial...
But, suddenly, it didn't open up, meanwhile it's clickable.
Here is the link to 'Editorial' section - https://leetcode.com/problems/median-employee-salary/editorial/

### Language used for code
SQL (PostgreSQL)

### Expected behavior
Section 'Editorial' should be available

### Screenshots
As we can see here, this question marked as it has editorial...
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/44915282/930ed0b6-3116-4c83-b51c-f6b286538dc1)

### Additional context
If that's just a known temporary problem with a lot of other question too, then just close this issue :)

Best regards!

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Hi there,
 
We sincerely apologize for the delay in addressing your concern. We've experienced a high volume of tickets recently, but we are committed to resolving each one as quickly as possible.
 
Regarding the website issue you reported, our team has already implemented a fix. Could you please check and let us know if the problem still persists on your end?

If the issue still exists, please send us a support ticket at https://leetcode.com/support

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.
 
Best regards,
LeetCode Support Team
