### ISSUE TITLE
1075. Project Employees I - Incorrect Test Case / Incorrect Solution

### ISSUE THREAD

**Issue by charoncherry** [LeetCode-Feedback/LeetCode-Feedback#18705]
### LeetCode Username

CherryWine27

### Problem number, title, and link

[1075. Project Employees I](https://leetcode.com/problems/project-employees-i/)

### Category of the bug
- [ x ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ x ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Although the problem explicitly states that experience_years is guaranteed not to be null, one of the test cases DOES include null experience_years (which I think is annoying, but fair enough - it's always a good habit to account for nulls)

The problem is that test case drops the employee from the project average, which I do not think is correct. Since the employee is assigned to the project, they should count in the denominator for the average (while adding 0 to the numerator). I believe the accepted solution is inaccurately inflating experience.

Regardless, either the test case should be updated to eliminate null experience_years, or the description should be updated to tell how nulls should be handled

### Language used for code

MS SQL

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
