### ISSUE TITLE
Missing Test Case - 751. IP to CIDR

### ISSUE THREAD

**Issue by charlessumo** [LeetCode-Feedback/LeetCode-Feedback#18704]
### LeetCode Username

charlestraw

### Problem number, title, and link

https://leetcode.com/problems/ip-to-cidr/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The following code passed the tests even though it failed this particular test
ip = "0.0.0.0"
n = 1000

### Language used for code

Python

### Code used for Submit/Run operation

```
class Solution:
    def ipToCIDR(self, ip: str, n: int) -> List[str]:
        startInt = self.ipToInt(ip)
        endInt = startInt + n
        answer = []
        while startInt < endInt:
            trailingZeros, maxMovement = self.trailingZeros(startInt)
            if startInt == 0:
                trailingZeros = 8
                maxMovement = 256
            while startInt + maxMovement > endInt:
                maxMovement /= 2
                trailingZeros -= 1
            answer.append(self.intToIp(startInt) + "/" + str(32 - trailingZeros))
            startInt += maxMovement
        return answer



    def trailingZeros(self, integer):
        temp = integer
        trailingZeros, maxMovement = 0, 1
        while temp > 0:
            if temp % 2 == 0:
                trailingZeros += 1
                maxMovement *= 2
            temp /= 2
        return trailingZeros, maxMovement


    
    def ipToInt(self, ip):
        blocks = ip.split('.')
        return int(blocks[3]) + 256 * int(blocks[2]) + 256 * 256 * int(blocks[1]) + 256*256*256*int(blocks[0])
    

    def intToIp(self, integer):
        temp = integer
        blocks = ["0","0","0","0"]
        i = 3
        while temp > 0:
            blocks[i] = str(int(temp % 256))
            temp = int(temp / 256)
            i -= 1
        return blocks[0] + "." + blocks[1] + "." + blocks[2] + "." + blocks[3]

                


```

### Expected behavior

This is testing edge case of 0.0.0.0 ip and n = 1000

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
