### ISSUE TITLE
Missing Test Case - 1453. Maximum Number of Darts Inside of a Circular Dartboard

### ISSUE THREAD

**Issue by suru003** [LeetCode-Feedback/LeetCode-Feedback#1871]
#### Category of the bug
- [ ] Solution

#### Code you used for Submit/Run operation
<!-- 
class Solution:
    def getPoints(self, i, j, points, r):
        ins=0
        for x in points:
            dx = abs(i-x[0])
            dy = abs(j-x[1])
            dis = sqrt((dx*dx)+(dy*dy))
            if(dis<=r):
                ins+=1
            if(ins==len(points)):
                break
            if(i==2 and j==3):
                print(x, "= ",ins," dis=",dis," dx=",dx," dy=",dy)
        
        return ins
    def numPoints(self, points: List[List[int]], r: int) -> int:
        minx = 9999
        miny = 9999
        maxx = -9999
        maxy = -9999
        
        for x in points:
            if(x[0]>maxx):
                maxx=x[0]
            if(x[1]>maxy):
                maxy=x[1]
            if(x[0]<minx):
                minx=x[0]
            if(x[1]<miny):
                miny=x[1]
        # print(minx," ",miny," ",maxx," ",maxy," ")
        maxpts = 0
        for i in range(minx,maxx+1):
            for j in range(miny,maxy+1):
                temp = self.getPoints(i,j, points, r)
                if(temp>maxpts):
                    maxpts=temp
        print(maxpts)
        return maxpts
```

#### Language used for code
<!-- Python 3.8 -->





#### Screenshots
![Screenshot (252)](https://user-images.githubusercontent.com/31486779/103602795-2c635600-4eca-11eb-8894-8c8ff8221a35.png)
<!-- If applicable, add screenshots to explain your issue. -->



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by lc-kay** [comment]
@suru003 Please provide the code so I can reproduce the issue. In addition, please state the issue that you are raising. Thank you!

**Comment by suru003** [comment]
```
class Solution:
    def getPoints(self, i, j, points, r):
        ins=0
        for x in points:
            dx = abs(i-x[0])
            dy = abs(j-x[1])
            dis = sqrt((dx*dx)+(dy*dy))
            if(dis<=r):
                ins+=1
            if(ins==len(points)):
                break
            if(i==2 and j==3):
                print(x, "= ",ins," dis=",dis," dx=",dx," dy=",dy)
        
        return ins
    def numPoints(self, points: List[List[int]], r: int) -> int:
        minx = 9999
        miny = 9999
        maxx = -9999
        maxy = -9999
        
        for x in points:
            if(x[0]>maxx):
                maxx=x[0]
            if(x[1]>maxy):
                maxy=x[1]
            if(x[0]<minx):
                minx=x[0]
            if(x[1]<miny):
                miny=x[1]
        # print(minx," ",miny," ",maxx," ",maxy," ")
        maxpts = 0
        for i in range(minx,maxx+1):
            for j in range(miny,maxy+1):
                temp = self.getPoints(i,j, points, r)
                if(temp>maxpts):
                    maxpts=temp
        print(maxpts)
        return maxpts
```

Here you go, I think I did add the same in the description

**Comment by lc-kay** [comment]
@suru003 The code you provided receives the Wrong Answer. In the report title, you stated this problem is missing a test case. For this report to qualify for rewards, you must submit an accepted solution that fails on your custom test case. Therefore, I will close this ticket now and re-open it if you have additional information. Thank you for your time.

**Comment by suru003** [comment]
![IMG_20210111_182132](https://user-images.githubusercontent.com/31486779/104257221-2b867300-543a-11eb-96b9-2c280c4c4d92.jpg)

I am trying to explain that those 4 closest points cannot be covered in the same circle of radius 2.

**Comment by lc-kay** [comment]
@suru003 Are you referring to the test case in the console or the example?

**Comment by suru003** [comment]
Both are the same, it's just that with graphs it would be easier to understand.

**Comment by lc-kay** [comment]
@suru003 Please check out this discuss post for why the expected output is 4 https://leetcode.com/problems/maximum-number-of-darts-inside-of-a-circular-dartboard/discuss/636420/Help-needed-for-understanding-testcase
