### ISSUE TITLE
Missing Test Case - 242. Valid Anagram

### ISSUE THREAD

**Issue by mkhuzaima** [LeetCode-Feedback/LeetCode-Feedback#18717]
### LeetCode Username

mkhuzaima

### Problem number, title, and link

242. Valid Anagram https://leetcode.com/problems/valid-anagram/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

There is not any test case where `s.length` > 300 and `s` starts with `'h'` having answer false, so code with simple if conditions are getting accepted with best time complexity. 

### Language used for code

Java

### Code used for Submit/Run operation

```
class Solution {
    public boolean isAnagram(String s, String t) {
        if (s.length() > 300 && s.charAt(0) == 'h') {
            return true;
        } else if (s.length() > 256 && (s.charAt(0) == 'h' || s.charAt(0) == 'a')) {
            return false;
        }
        int[] map = new int[26];
        if(s.length() != t.length()) return false;

        for(int i = 0; i < s.length(); i++) {
            map[s.charAt(i) - 'a']++;
            map[t.charAt(i) - 'a']--;
        }

        for (Integer value : map) {
            if( value != 0) return false;
        }

        return true;
    }
}
```

### Expected behavior

This code should not get accepted because it returns true where s.length is 300 and `s` starts with 'h'. 

One such missing case is: 
s=
```
"haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
```
t=
```
"haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaz"
```

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by mkhuzaima** [comment]
Hello,

Thank you for your prompt response and for addressing the reported issue. I truly appreciate your attention to this matter and your commitment to resolving it.

I look forward to hearing back from you once there are updates or any findings regarding the issue. If there's any additional information or assistance I can provide in the meantime, please don't hesitate to reach out.

Thank you again for your support and dedication to resolving this.

Best regards,
M Khuzaima

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team

**Comment by mkhuzaima** [comment]
My pleasure
