### ISSUE TITLE
Wrong Test Case - 399. Evaluate Division

### ISSUE THREAD

**Issue by namanchandak** [LeetCode-Feedback/LeetCode-Feedback#18711]
### LeetCode Username

namanchandak

### Problem number, title, and link

https://leetcode.com/problems/evaluate-division/description/

### Category of the bug

- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### Description of the bug

As we were given ```1 <= Ai.length, Bi.length <= 5``` and if queries = [["x","x"]] then x/x is always 1 if x != infinity or 0. 
Hence the answer should be 1 instead of any other value in all the cases of ```values``` and ```equation``` array.

### Given below code is showing the wrong result but it is the desired result.

```
class Solution {
public:

    unordered_map<string,unordered_map<string,double>>create(vector<vector<string>>& equations, vector<double>& values)
    {
        unordered_map<string,unordered_map<string,double>>graph;

        for(int i=0;i<equations.size();i++)
        {
            string b=equations[i][1];
            string a=equations[i][0];

            graph[a][b]=values[i];
            graph[b][a]=(double)1/values[i];

        }

        return graph;
    }



    void calc(unordered_map<string,unordered_map<string,double>>&adj,unordered_set<string>&vis,string a,string b,double& ans,double temp)
    {
        if(a==b)
        {
            ans=temp;
            return ;
        }
        
        vis.insert(a);

        
        for(auto it:adj[a])
        {
            if(vis.find(it.first)==vis.end())
            {
                calc(adj,vis,it.first,b,ans,temp*it.second);
            }
        }
    }



    vector<double> calcEquation(vector<vector<string>>& equations, vector<double>& values, vector<vector<string>>& queries) {
        unordered_map<string,unordered_map<string,double>>adj=create(equations,values);

        vector<double>ans1;

        for(auto it:queries)
        {
            
            string a= it[0];
            string b= it[1];
            if(adj.find(a)==adj.end() || !adj.count(b))
            {
                if(a==b)
                ans1.push_back(1);
                else
                ans1.push_back(-1);
            }
            
            else
            {
                unordered_set<string>vis;
                double ans=-1,temp=1.0;
                calc(adj,vis,a,b,ans,temp);
                ans1.push_back(ans);
            }

            
        }

        return ans1;

    }
};
```
### Given below code is accepted but it is not the desired result.

```
class Solution {
public:

    unordered_map<string,unordered_map<string,double>>create(vector<vector<string>>& equations, vector<double>& values)
    {
        unordered_map<string,unordered_map<string,double>>graph;

        for(int i=0;i<equations.size();i++)
        {
            string b=equations[i][1];
            string a=equations[i][0];

            graph[a][b]=values[i];
            graph[b][a]=(double)1/values[i];

        }

        return graph;
    }



    void calc(unordered_map<string,unordered_map<string,double>>&adj,unordered_set<string>&vis,string a,string b,double& ans,double temp)
    {
        if(a==b)
        {
            ans=temp;
            return ;
        }
        
        vis.insert(a);

        
        for(auto it:adj[a])
        {
            if(vis.find(it.first)==vis.end())
            {
                calc(adj,vis,it.first,b,ans,temp*it.second);
            }
        }
    }



    vector<double> calcEquation(vector<vector<string>>& equations, vector<double>& values, vector<vector<string>>& queries) {
        unordered_map<string,unordered_map<string,double>>adj=create(equations,values);

        vector<double>ans1;

        for(auto it:queries)
        {
            
            string a= it[0];
            string b= it[1];
            if(adj.find(a)==adj.end() || !adj.count(b))
            ans1.push_back(-1);
            else
            {
                unordered_set<string>vis;
                double ans=-1,temp=1.0;
                calc(adj,vis,a,b,ans,temp);
                ans1.push_back(ans);
            }

            
        }

        return ans1;

    }
};

```

### Expected behavior

for this test case
equations = [["a","b"],["b","c"]], values = [2.0,3.0], queries = [["a","c"],["b","a"],["a","e"],["a","a"],["x","x"]]
Output: [6.00000,0.50000,-1.00000,1.00000,-1.00000]

The value for ["x","x"] in ```queries``` is -1.00000 but the expected value is 1.00000 as the following given in the problem description.
Note: The input is always valid. You may assume that evaluating the queries will not result in division by zero and that there is no contradiction. 

For
Note: The variables that do not occur in the list of equations are undefined, so the answer cannot be determined for them.
But we can answer can determined answer for ["x","x"] in ```queries``` in any test case the answer should be 1.00000.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
