### ISSUE TITLE
Wrong Pre-Written Code in Go for 27. Remove Element

### ISSUE THREAD

**Issue by kansalanmol0609** [LeetCode-Feedback/LeetCode-Feedback#18714]
### Problem number, title, and link
27. Remove Element https://leetcode.com/problems/remove-element/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [x] Programming language support

### Description of the bug

The following code is provided as the pre-written code in the editor for Go Language -

```go
func removeElement(nums []int, val int) int {
    
}
```

In the problem description, we've been asked to modify the given integer array `num` in-place but it's not possible to solve this question using Go Language using the above function definition.

We should be expecting pointer to the integer array in function like following - 

```go
func removeElement(nums *[]int, val int) int {
    
}
```

### Language used for code
Go

### Code used for Submit/Run operation

```go
func removeElement(*nums []int, val int) int {
    k := 0 //assuming k points to an index having value = val

    for i:=0; i<len(*nums); i++{
        if *nums[i] != val{
            *nums[k] = *nums[i]
        }
        k++
    }

    return k
}

```

### Expected behavior

The above code should have been compiled successfully

### Screenshots
NA

### Additional context
NA

**Comment by EndlessCheng** [comment]
It's a slice, not array. You can modify the slice inplace without the `*`.
```go
func removeElement(nums []int, val int) int {
    left := 0
    for _, v := range nums {
        if v != val {
            nums[left] = v
            left++
        }
    }
    return left
}
```
