### ISSUE TITLE
Add `PostgreSQL` tag into `Solutions` section

### ISSUE THREAD

**Issue by Shargano** [LeetCode-Feedback/LeetCode-Feedback#18726]
### LeetCode Username
Shargano - https://leetcode.com/Shargano/

### Problem number, title, and link
Any `Database` question, here one for example: 
[175. Combine Two Tables] - https://leetcode.com/problems/combine-two-tables/

### Category of the bug
- [x] Supported solution tags

### Description of the bug
It's definitely not a bug :)
I'm just asking to add `PostgreSQL` tag for solutions to mark them properly :)

### Language used for code
SQL (PostgreSQL)

### Expected behavior
Existence of `PostgreSQL` tag

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/44915282/b28cc8b5-e464-43df-8602-f1f9da8ca325)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for consideration. We appreciate your patience and understanding as we work to address and resolve this matter.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team
