### ISSUE TITLE
Missing Test Case - 925. Long Pressed Name

### ISSUE THREAD

**Issue by Superminionsfy** [LeetCode-Feedback/LeetCode-Feedback#1872]
#### Your LeetCode username

superminions

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

lost one test case: when the typed string is shorter than the name.
For instance:
```
name: "alexd"
typed: "ale"
```
The program should return False in this case, but it is not included in the provided test cases.

#### Code you used for Submit/Run operation

```
def isLongPressedName(self, name: str, typed: str) -> bool:
        if not name and not typed:
            return True
        elif not name:
            return False
        elif not typed:
            return False
      
        i = 0
        for j in range(len(typed)):
            if i > len(name) - 1:
                if typed[j] == name[len(name) - 1]:
                    continue
                else:
                    return False
            
            if len(name) - i > len(typed) - j:  # Even if this if is missed, the code could still pass all test cases
                return False
            elif len(name) - i == len(typed) - j and name[i] != typed[j]: 
                return False
            else:
                if name[i] == typed[j]:
                    i += 1
                else:
                    if name[i-1] != typed[j] or i == 0:
                        return False
            
        return True
```

#### Language used for code

Python

#### Expected behavior

See the comment in the code above. Even if the if statement is removed, the code could still pass all test cases, which is not as expected.

**Comment by lc-kay** [comment]
Hi @Superminionsfy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Superminionsfy 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
