### ISSUE TITLE
Typos in Queue & Stack Explore Card - "BFS - Template"

### ISSUE THREAD

**Issue by Y-Rov** [LeetCode-Feedback/LeetCode-Feedback#18720]
### LeetCode Username

[anacondrai](https://leetcode.com/anacondrai)

### Category of the bug
- [ ] Language

### Description of the bug

Hello, LeetCode team😄

If we go through the section "BFS - Template" in [Queue & Stack Explore Card](https://leetcode.com/explore/learn/card/queue-stack/231/practical-application-queue/1372/), there are three typos:

1. The agreement mistake in the "exercises" word:

> In this article, we will provide you with a template. Then, we provide some exercise after this article for practice.

2. Typos in the "needed word" in both code snippets:

`int step = 0;       // number of steps neeeded from root to current node` 

### Expected behavior

The corrected sentence and code line should look like:

> In this article, we will provide you with a template. Then, we provide some exercises after this article for practice.

`int step = 0;       // number of steps needed from root to current node` 

### Screenshots

![Incorrect_Sentence](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73534920/2ec37eb0-0993-4080-9e59-5a919e904c0f)

![Needed_Typo_1](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73534920/ca643b1b-eece-46a5-88ed-fea73aafd47f)

![Needed_Typo_2](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73534920/c2fae497-9cde-470e-b4f7-5fa43f993772)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by Y-Rov** [comment]
Hi @LC-Pam, I am sorry for bothering you, maybe this issue is still in progress but the typo in the "exercises" word was fixed:

![Corrected_Sentence](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73534920/e00e0524-b232-45a5-b17d-366f959784da)

However, both templates are not visible now (tried to reload the page for several times, but the behavior is still the same):

![Empty_Template_I](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73534920/0a3ad050-5821-408e-8509-5e13c5d71493)

![Empty_Template_II](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73534920/bbd52882-2e13-4f37-8e42-72b1c9eb8da4)

**Comment by Y-Rov** [comment]
Hello @LC-Pam, here goes an updated comment.

Code snippets are visible and a typo in the 1-st code snippet was fixed:

![Needed_Typo_1_Fixed](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73534920/5a83dc90-ac26-4b50-a5a7-eecc27432cf4)

However, the typo in the 2-nd code snippet is still present:

![Needed_Typo_2_Left](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73534920/a5424799-c0f4-4493-b939-8afcb8e43f5a)

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem and we are currently working on fixing it. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
