### ISSUE TITLE
Brute Force Java Solution needs to be changed - 22. Generate Parentheses

### ISSUE THREAD

**Issue by tarunrajput** [LeetCode-Feedback/LeetCode-Feedback#1873]
#### Your LeetCode username
tarunrajput

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
The Brute Force Java solution of this problem has this extra python code (line 31 - line 38)  appended to it.

#### Expected behavior
The extra python code should be removed.

#### Screenshots
![image](https://user-images.githubusercontent.com/34857453/103616717-f1f1cb80-4f52-11eb-9132-6a966b093440.png)

**Comment by lc-kay** [comment]
Hi @tarunrajput 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @tarunrajput 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
