### ISSUE TITLE
Editorial typo

### ISSUE THREAD

**Issue by Mason-Lin** [LeetCode-Feedback/LeetCode-Feedback#18739]
### LeetCode Username

yu-kang

### Problem number, title, and link

https://leetcode.com/problems/design-a-food-rating-system/editorial/?envType=daily-question&envId=2023-12-17

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug

There is a typo in 
Approach 1: Hash Maps and Priority Queue
-> Algorithm
-> 4. Implementing changeRating(food, newRating) method:
-> Fetch the cuisine name for food from **foodRatingMap**.
It should be **foodCuisineMap**

### Language used for code

python

### Code used for Submit/Run operation

n/a

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

### Expected behavior

Algorithm
Fetch the cuisine name for food from **foodRatingMap**.
It should be **foodCuisineMap**

### Screenshots

n/a

### Additional context

n/a

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
