### ISSUE TITLE
Missing Test Case - 2967. Minimum Cost to Make Array Equalindromic

### ISSUE THREAD

**Issue by flajwf** [LeetCode-Feedback/LeetCode-Feedback#18735]
### LeetCode Username
changeme

### Problem number, title, and link
https://leetcode.com/problems/minimum-cost-to-make-array-equalindromic/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [X] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
Some proposed solutions pass all current test cases.
Example of the solution that passes all current test cases but it fails on the one mentioned below.
https://leetcode.com/problems/minimum-cost-to-make-array-equalindromic/solutions/4414716/find-median-java-easy-solution/

But it fails on this test case:
[1,1,1000000000]

The bug is in the next code, it calculates median incorrectly:
```
        if (n % 2 != 0) {
            middle = nums[(n + 1) / 2];
        } else {
```
it should be
```
        if (n % 2 != 0) {
            middle = nums[n / 2];
        } else {
```

### Language used for code
Java

### Code used for Submit/Run operation
```
class Solution {
    public long minimumCost(int[] nums) {
        Arrays.sort(nums);
        int n = nums.length;
        int middle = 0;
        if (n == 1) return 0;

        if (n % 2 != 0) {
            middle = nums[(n + 1) / 2];
        } else {
            middle = (int)(nums[(n + 1) / 2] + nums[n / 2]) / 2;
        }

        long result = Long.MAX_VALUE;

        for (int r = middle - 10000; r <= middle + 10000; r++) {
            if (isPal(r) == false) continue;

            result = Math.min(result, calculatecost(nums, r));
        }

        return result;
    }

    public boolean isPal(int n) {
        int r, sum = 0, temp;
        temp = n;
        while (n > 0) {
            r = n % 10; //getting remainder  
            sum = (sum * 10) + r;
            n = n / 10;
        }
        return temp == sum;
    }

    public long calculatecost(int[] nums, int r) {
        long cost = 0;
        for (int n: nums) {
            cost += Math.abs(n - r);
        }
        return cost;
    }
}
```

### Expected behavior
Solution should not be accepted, since it fails on the next test
[1,1,1000000000]
```
Input nums = [1,1,1000000000]
Output 1999999997
Expected 999999999
```

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
