### ISSUE TITLE
Test Case Execution Issue

### ISSUE THREAD

**Issue by Vikasss7663** [LeetCode-Feedback/LeetCode-Feedback#18740]
### LeetCode Username
cs_iitian

### Problem number, title, and link
[2353. Design a Food Rating System](https://leetcode.com/problems/design-a-food-rating-system/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

When I submit my code with debug statement which is simple java System.out.println() which prints the data, I am getting error at 71 test case, and If I comment it out I am getting error at 75 test cases. Why this behavior is happening ?

### Language used for code

Java

### Code used for Submit/Run operation

```java
class Pair {
    String food;
    Integer rating;
    Pair(String food, Integer rating) {
        this.food = food;
        this.rating = rating;
    }

    @Override
    public String toString() {
        return "F: " + food + " R: " + rating + " ";
    }
}
class FoodRatings {

    Map<String, PriorityQueue<Pair>> cuisineRatingMap;
    Map<String, String> foodCuisineMap;
    Map<String, Pair> foodObjectMap;

    public FoodRatings(String[] foods, String[] cuisines, int[] ratings) {
        cuisineRatingMap = new HashMap();
        foodCuisineMap = new HashMap();
        foodObjectMap = new HashMap();

        for(int i=0;i<foods.length;i++) {
            String food = foods[i];
            String cuisine = cuisines[i];
            Integer rating = ratings[i];

            cuisineRatingMap.putIfAbsent(cuisine, new PriorityQueue<>((s1, s2) -> {
                if(s1.rating != s2.rating) return s2.rating - s1.rating;
                return s1.food.compareTo(s2.food);
            }));
            Pair pair = new Pair(food, rating);
            foodObjectMap.put(food, pair);
            cuisineRatingMap.get(cuisine).add(pair);
            foodCuisineMap.put(food, cuisine);

            // System.out.println(cuisineRatingMap.get(cuisine));
        }
    }
    
    public void changeRating(String food, int newRating) {
        String cuisine = foodCuisineMap.get(food);
        Pair pair = foodObjectMap.get(food);
        cuisineRatingMap.get(cuisine).remove(pair);
        Pair newPair = new Pair(food, newRating);
        foodObjectMap.put(food, newPair);
        cuisineRatingMap.get(cuisine).add(newPair);
        // System.out.println(cuisineRatingMap.get(cuisine));
    }
    
    public String highestRated(String cuisine) {
        return cuisineRatingMap.get(cuisine).peek().food;
    }
}

```

### Expected behavior

Since this is a just a debugger statement, It should be failed in 75 test cases.

### Screenshots

<img width="1439" alt="Screenshot 2023-12-17 at 1 58 59 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/98081274/079a171f-e087-445d-a5d2-bb5383bd58ce">
<img width="1439" alt="Screenshot 2023-12-17 at 1 59 20 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/98081274/d1963156-8e0c-4c9b-858f-7eafcf03acc2">

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
