### ISSUE TITLE
Bug - 99. Recover Binary Search Tree

### ISSUE THREAD

**Issue by bansal3103** [LeetCode-Feedback/LeetCode-Feedback#18741]
### LeetCode Username 
bansAlgos022

### Problem number, title, and link
Problem number - 99 (Recover Binary Search Tree)
Link : https://leetcode.com/problems/recover-binary-search-tree/description/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
While running the code the code is getting accepted and giving the same output as expected while submitting the same code is giving wrong answer to the same test case. Check the ss below.

### Language used for code
Java

### Code used for Submit/Run operation
```
class Solution {
    static int value=0;
    static TreeNode node=new TreeNode();
    static int temp=0;
    static int tempValue=0;
    static boolean tree(TreeNode root,int side){
        if(root==null) return false;
        int subValue=root.val;
        if(side==0 && subValue>value){
            temp=1;
            tempValue=subValue;
            if(!tree(node,1)){
                root.val=value;
                value=subValue;
            }else root.val=value;
            return true;
        }
        if(side==1 && subValue<value){
            if(temp==1){
                temp++;
                root.val=tempValue;
                value=subValue;
            }else{
                root.val=value;
                value=subValue;
            }
            return true;
        }
        if(tree(root.left,side)) return true;
        if(tree(root.right,side)) return true;
        return false;
    }
    public void recoverTree(TreeNode root) {
        value=root.val;
        node=root.right;
        if(!tree(root.left,0)){
            tree(root.right,1);
            root.val=value;
        }else if(temp==1){
            root.val=value;
        }
        return;
    }
}
```

### Expected behavior
The same case is should different result in running and submitting

### Screenshot
As you can see in the ss.. the test case [2,null,1] is getting accepted while running but showing opposite behaviour in submitting.

![Screenshot (239)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/126455936/29b416a8-d74e-4317-b426-77d09f206391)
s

### Additional context
Submission Link : https://leetcode.com/problems/recover-binary-search-tree/submissions/1121667368/

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us!

When comparing the outcomes of "Run Code" and "Submit" for a specific test case, it's evident that the input and expected values are the same, yet the output values differ.

To assist you further, we have documented the causes and potential solutions for this type of issue in detail. You can find this information in our knowledge base article: [Test Case Discrepancy - Causes and Solutions](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-).

I hope this resource proves helpful. Should you have any additional questions or need further clarification on this case, please do not hesitate to reach out to us. We're here to assist you!

Best regards,
LeetCode Support Team
