### ISSUE TITLE
Missing Test Case - 2353. Design a Food Rating System

### ISSUE THREAD

**Issue by lone17** [LeetCode-Feedback/LeetCode-Feedback#18759]
### LeetCode Username

lone17

### Problem number, title, and link

2353. Design a Food Rating System https://leetcode.com/problems/design-a-food-rating-system/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Code getting accepted because of missing this test case:
```
["FoodRatings","highestRated"]
[[["a","b"],["b","c"],[9,8]],["b"]]
```

### Language used for code

Python

### Code used for Submit/Run operation

Link to submission: https://leetcode.com/problems/design-a-food-rating-system/submissions/1122011459?envType=daily-question&envId=2023-12-17
```python
class FoodRatings:

    def __init__(self, foods, cuisines, ratings):
        self.food_ratings = defaultdict(int)
        self.food_lists = defaultdict(list)
        self.heaps = defaultdict(list)
        for f, c, r in zip(foods, cuisines, ratings):
            self.food_ratings[f] = r
            heap = self.heaps[c]
            self.food_lists[f] = self.food_lists[c] = heap
            heappush(heap, (-r, f))
        

    def changeRating(self, food, newRating):
        if self.food_ratings[food] != newRating:
            heappush(self.food_lists[food], (-newRating, food))    
            self.food_ratings[food] = newRating
        

    def highestRated(self, cuisine):
        food_list = self.food_lists[cuisine]
        rating, food = food_list[0]
        while -rating != self.food_ratings[food]:
            heappop(food_list)
            rating, food = food_list[0]
        
        return food
```

### Expected behavior

Incorrect code should not get accepted.
Expected output for the above test case is:
```
[null,"a"]
```

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
