### ISSUE TITLE
Missing Test Case - 100. Same Tree

### ISSUE THREAD

**Issue by HARSHRAJ7899** [LeetCode-Feedback/LeetCode-Feedback#18758]
### LeetCode Username

harshrajtiwari7899

### Problem number, title, and link

100.Same Tree https://leetcode.com/problems/same-tree/

### Category of the bug

 Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

My code is submitted by leetcode yet it can't solve this particular test case 
p=[1,0] 
q =[1,null,0]

### Code used for Submit/Run operation

```
/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
class Solution {
public:
    void nodes(vector<int>&sum,TreeNode* root){
        if(root==NULL){
            sum.push_back(0);
            return;
            }
            nodes(sum,root->left);
            nodes(sum,root->right);
            
            sum.push_back(root->val);
        
    }
    bool isSameTree(TreeNode* p, TreeNode* q) {
        vector<int>a,b;
        nodes(a,p);
        nodes(b,q);
        return a==b;
    }
};
```

### Expected behavior

The code should give false for this test case given above. Yet it gets submmitted

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
