### ISSUE TITLE
请在589. 题目支持Typescript

### ISSUE THREAD

**Issue by zhanzekun** [LeetCode-Feedback/LeetCode-Feedback#1876]
** Bug 类型**
- [ ] 题目 589
- [ ] 编程语言 Typescript

**描述**
589题没有支持Typescript

**你使用的语言**
Typescript

**期望行为**
支持Typescript

**Comment by feiceh** [comment]
你好，该反馈已转给相关团队会持续优化增加更多语言。Github 仓库只用于反馈大家在本站学习过程中遇到的题目和题解问题，问题我先关闭，后续使用中有任何问题或建议欢迎 [提交工单](https://support.leetcode-cn.com/hc/request/new/) 反馈，我们会定期更新，保障稳定和体验优化。
