### ISSUE TITLE
Missing Test Case - 73. Set Matrix Zeroes

### ISSUE THREAD

**Issue by ayushkr012** [LeetCode-Feedback/LeetCode-Feedback#18775]
### LeetCode Username

ayushkr01

### Problem number, title, and link

[73. Set Matrix Zeroes] (https://leetcode.com/problems/set-matrix-zeroes/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

 code is Accepted but for this test case -----> [[-999998,100,1],[142,0,1],[12,1,189]]  it fails when You Exclude this test case Code is Accepted
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/136481697/b769b88e-5eaa-4158-b0ee-358242e3513d)

### Language used for code

C++

### Code used for Submit/Run operation

```
class Solution {
public: // time O(M*N) space O(1)
    void setZeroes(vector<vector<int>>& matrix) {
        int m=matrix.size(),n=matrix[0].size();
        for(int i=0;i<m;i++){
            for(int j=0;j<n;j++){
                if(matrix[i][j]==0){
                    for(int k=0;k<n;k++){
                       if(matrix[i][k]!=0){
                           matrix[i][k]=-999998;
                       }
                    }
                    for(int k=0;k<m;k++){
                        if(matrix[k][j]!=0)matrix[k][j]=-999998;
                    }
                }
            }
        }
        for(int i=0;i<m;i++){
            for(int j=0;j<n;j++){
                if(matrix[i][j]==-999998){
                    matrix[i][j]=0;
                }
            }
        }       
    }
};
```

### Expected behavior

When You submit my code without including this `[[-999998,100,1],[142,0,1],[12,1,189]]` test case then It is Accepted 

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/136481697/f42e3107-f974-475e-85d0-6bd11da5b6e2)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
