### ISSUE TITLE
Error in the testcase

### ISSUE THREAD

**Issue by PankajSharma3** [LeetCode-Feedback/LeetCode-Feedback#18772]
### LeetCode Username
Pankaj53

### Category of the bug
Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### Description of the bug 
I have solved the question by but I have used the testcase - [1] as the sample linked list and the testcase passed in the sample testcase but after the submission the compiler is showing the wrong answer for the particular testcase.

### Language used for code
 C++
 

### Code used for Submit/Run operation

```
/**
 * Definition for singly-linked list.
 * struct ListNode {
 *     int val;
 *     ListNode *next;
 *     ListNode() : val(0), next(nullptr) {}
 *     ListNode(int x) : val(x), next(nullptr) {}
 *     ListNode(int x, ListNode *next) : val(x), next(next) {}
 * };
 */
class Solution {
public:
    ListNode* deleteMiddle(ListNode* head) {
        int index = 0;
        ListNode* temp = head;
        while(temp!=NULL)
        {
            index++;
            temp = temp->next;
        }
        index/=2;
        temp = head;
        if(index==0)
        return head;
        ListNode* current = head;
        ListNode* previous = nullptr;
        int i=0;
        while(i!=index){
            previous = current;
            current = current->next;
            i++;
        }
        previous->next = current->next;
        delete current;
        return head;
    }
};
```

### Screenshots
![Screenshot 2023-12-18 211806](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/118182606/61ee1e60-74a0-4dba-9e37-12f374276a2d)

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
