### ISSUE TITLE
GUI bug

### ISSUE THREAD

**Issue by tredsused40** [LeetCode-Feedback/LeetCode-Feedback#18777]
### LeetCode Username

tredsused70

### Problem number, title, and link

1913. Maximum Product Difference Between Two Pairs https://leetcode.com/problems/maximum-product-difference-between-two-pairs/

### Category of the bug
- [.] Graphical user interface bug

### Description of the bug

In the submission result on the left it is shown that my submission beats 99.06% other users, however on the right side it shows that my submission beats 99.6%.

### Language used for code

C++

### Code used for Submit/Run operation

```
class Solution {
public:
    int maxProductDifference(vector<int>& nums) {
        int mx = *max_element(nums.begin(), nums.end());
        vector<int> vc(mx + 1, 0);
        for(int &i : nums)
            vc[i]++;
        int cnt = 0, pos = mx, cp = 1, ans = 0;
        while(cnt < 2) {
            if(vc[pos]) {
                vc[pos]--;
                cnt++;
                cp *= pos;
            }
            else
                pos--;
        }
        ans = cp;
        cp = 1;
        pos = 0;
        cnt = 0;
        while(cnt < 2) {
            if(vc[pos]) {
                vc[pos]--;
                cp *= pos;
                cnt++;
            }
            else
                pos++;
        }
        ans -= cp;
        return ans;
    }
};

static auto o = [](){
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
    return 1;
}();
```

### Expected behavior

Seems like the percentage of beated submissions should be the same on both sides of a screen, but it's not.

### Screenshots

![LeetCode - The World's Leading Online Programming Learning Platform - Google Chrome 18 12 2023 21_21_17](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/75163817/b4a17b87-d88e-48cd-b0df-ce7734346d5a)

### Additional context

Seems like it works for all of the numbers but for those that look like xx.0x.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Due to the high volume of the reports, we will temporarily close this ticket right now.
 
However, your feedback has already been successfully submitted to the team.
 
Once we have any updates from the team, we will re-open this ticket and get back to you.
 
Thank you for your understanding!
