### ISSUE TITLE
Incorrect Test Case - 1586. Binary Search Tree Iterator II

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#18787]
### LeetCode Username
pgmreddy

### Problem number, title, and link

[1586. Binary Search Tree Iterator II](https://leetcode.com/problems/binary-search-tree-iterator-ii/)

https://leetcode.com/problems/binary-search-tree-iterator-ii/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

For below incorrect test case, but judge does not say it is incorrect test case, but gives wrong output

["BSTIterator","next","prev","next","next","hasNext","next","next","next","hasNext","hasPrev","prev","prev"]
[[[7,3,15,null,null,9,20]],[null],[null],[null],[null],[null],[null],[null],[null],[null],[null],[null],[null]]

### Language used for code
JavaScript

### Code used for Submit/Run operation

```
var BSTIterator = function (r) {
  this.last = r
  this.stack = []
  this.arr = []
  this.pointer = -1
  this.hasNext = function () {
    return this.stack.length > 0 || this.last !== null || this.pointer < this.arr.length - 1
  }
  this.next = function () {
    ++this.pointer
    if (this.pointer === this.arr.length) {
      while (this.last !== null) {
        this.stack.push(this.last)
        this.last = this.last.left
      }
      const curr = this.stack.pop()
      this.last = curr.right
      this.arr.push(curr.val)
    }
    return this.arr[this.pointer]
  }
  this.hasPrev = function () {
    return this.pointer > 0
  }
  this.prev = function () {
    --this.pointer
    return this.arr[this.pointer]
  }
}
```

### Expected behavior
For an incorrect test case, judge must say it is incorrect test case, but it does not, gives gives wrong expected

### Screenshots

For an incorrect test case, judge must say it is incorrect test case, but it does not, gives gives wrong expected

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/8236389/10d988af-02b1-48a6-93bc-1e5211c09c91)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
