### ISSUE TITLE
Test case not working

### ISSUE THREAD

**Issue by 8-bit-owl** [LeetCode-Feedback/LeetCode-Feedback#18781]
### Problem number, title, and link
1. Two Sum https://leetcode.com/problems/two-sum/

### Category of the bug
- [ ] Problem description
- [x ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The test case {3,3} works when I run the test case, but fails when I submit. 

There are three test cases. It fails when I hit the Run button. But when I delete test case 1
and test case 2 and run test case 3 alone, It runs. But when I submit, it fails.

### Language used for code
C

### Code used for Submit/Run operation

```
int mymap[20]={[0 ... 19] = 0xffffff};
int ret[2] = {0,0};

int* twoSum(int* nums, int numsSize, int target, int* returnSize) {
    /*
    There is no inherent datastructure hashmap in C. So we build it ourselves.
    Implementing hashmap in C gives us an understanding of why accessing an element
    in hashmap is O(1). Its like storing a data at particular location and also
    remembering the location. This is the reason why it works in O(1) coz we know thw location.
    */

    for(int i =0;i<numsSize;i++)
    {
        if(target-nums[i]>=0){
            if(mymap[nums[i]]!=0xffffff)
            {                      
                ret[0]=mymap[nums[i]];
                ret[1]= i;
                *returnSize=2;
                return ret;
            }
            else
            {
                mymap[target-nums[i]]=i;
            }
        }
    }

    return NULL;
}

```

### Expected behavior

When I run the code, Only test case 3 fails. But when I delete testcase 1 and testcase 2, 
the code runs perfectly.
 

### Screenshots

![two_sum_glitch](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/20287036/caf3b259-f560-4a0f-89cb-411e08edb83d)
![two_sum_glitch2](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/20287036/fcd61f2e-5e11-432a-aa47-56f7a83ec769)

### Additional context

I purposely used global variables so there shouldn't be any issues related to heap memory.
My idea was to use a big chunk of memory and use index of the array as the key, and store
value at the location. Not sure if it is the right method, but this was the only way I could think of
to get O(1) when getting data from heap.

Possible reason for this could be, The function that is testing my function is not properly clearing memory.
Or I could be doing something stupid. Id be happy to learn. Please provide an explanation too.
That would help me improve my coding skills :)

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
