### ISSUE TITLE
33. Search in Rotated Sorted Array - Wrong Implementation to Find the Pivot Index in Approach 1

### ISSUE THREAD

**Issue by charlesycchen** [LeetCode-Feedback/LeetCode-Feedback#18782]
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug

In the approach 1 of Question No. 33, the following statement is wrong:
If `nums[mid] < nums[n - 1]`, `pivot` could be either at `mid` or to the left of `mid`, in which case we should set `right = mid - 1`.
EX: `nums = [4, 5, 6, 7, 0, 1]`
Use the above algorithm, the `pivoit` (`left`) might be `3`, not `4`.

Correction:
If `nums[mid] < nums[n - 1]`, we should set `right = mid`, so we can find the correct pivot point.

### Expected behavior

EX: `nums = [4, 5, 6, 7, 0, 1]`
We should find `pivot` is set to `4`.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
