### ISSUE TITLE
Missing Test Case - 665. Non-decreasing Array

### ISSUE THREAD

**Issue by 1805610146** [LeetCode-Feedback/LeetCode-Feedback#18798]
### LeetCode Username

小野晨曦
### Problem number, title, and link

665、非递减数列
https://leetcode.cn/problems/non-decreasing-array/

### Category of the bug
- [ ] Problem description
- [√ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

在i=0且nums[0]>nums[1]的情况下无法交换nums[0]和nums[1]的值。

### Language used for code

java

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```
class Solution {
    public boolean checkPossibility(int[] nums) {
        int n=nums.length,c=0;
        for(int i = 0 ; i<n-1 ;++i){
            int x = nums[i], y = nums[i+1];
            if(x>y){
                c++;
                if(c>1){
                    return false;
                }
                if(i > 0 && y < nums[i-1]){
                    nums[i+1] = x;
                }
                if(i == 0 ){
                    nums[i] = y;
                }
            }    
        }
        return true;
    }
}

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/143696738/0059d864-f3c2-4e2a-ace2-d5bc71fb268e)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/143696738/629e665f-8169-4aaf-bc4f-f8edf3930898)

**Comment by amcones-lc** [comment]
您好，在与相关团队核实后：***不处理***（题目要求改变 1 个值，而不是交换 2 个值）。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
