### ISSUE TITLE
Missing Test Case - 622. Design Circular Queue

### ISSUE THREAD

**Issue by jerwng** [LeetCode-Feedback/LeetCode-Feedback#18790]
### LeetCode Username

jerwng

### Problem number, title, and link

[622. Design Circular Queue](https://leetcode.com/problems/design-circular-queue/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Missing a test case for `isFull`

### Language used for code

Python 3

### Code used for Submit/Run operation

```
class MyCircularQueue:

    def __init__(self, k: int):
        self.queue = [0] * k
        self.front = 0
        self.end = 0
        self.capacity = k

    def enQueue(self, value: int) -> bool:
        # Move end pointer when enqueuing
        # Check if isFull, if so return False
        if self.isFull():
            return False

        self.queue[self.end] = value

        # If on last index, wrap around to index 0
        if self.end == self.capacity - 1:
            self.end = 0
        # If not on last index, move end to the right by 1
        else:
            self.end += 1

        return True
        

    def deQueue(self) -> bool:
        # Move front pointer when dequeuing
        # Check if isEmpty, if so return False
        if self.isEmpty():
            return False
        
        self.queue[self.front] = 0

        if self.front == self.capacity -1:
            self.front = 0
        else:
            self.front += 1

        return True
        

    def Front(self) -> int:
        if self.isEmpty():
            return -1

        return self.queue[self.front]
        

    def Rear(self) -> int:
        if self.isEmpty():
            return -1
    
        return self.queue[self.end - 1]
        

    def isEmpty(self) -> bool:
        return self.front == self.end and self.queue[self.front] == 0

    def isFull(self) -> bool:
        return self.queue[self.end] != 0
        


# Your MyCircularQueue object will be instantiated and called as such:
# obj = MyCircularQueue(k)
# param_1 = obj.enQueue(value)
# param_2 = obj.deQueue()
# param_3 = obj.Front()
# param_4 = obj.Rear()
# param_5 = obj.isEmpty()
# param_6 = obj.isFull()
```

### Expected behavior

The given code should not be accepted as a solution, it is failing a test case for `isFull`.

For the given input
```
["MyCircularQueue","enQueue", "enQueue", "enQueue", "isFull"]
[[3], [0], [0], [0], []]
```

This solution returns `[null,true,true,true,false]` when it should be `[null,true,true,true,true]`

### Screenshots
Manually test shows the solution fails the test case

![Screenshot 2023-12-19 at 11 25 39 AM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/26147214/2351d301-ffdb-4327-bc0b-44a40ffd9171)

However, it is still accepted as a correct solution

![Screenshot 2023-12-19 at 11 26 17 AM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/26147214/4dd758f0-ed2e-42d0-abca-a73b59296b48)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
