### ISSUE TITLE
Missing Test Case - 853. Car Fleet

### ISSUE THREAD

**Issue by denzeysenpai** [LeetCode-Feedback/LeetCode-Feedback#18794]
### Problem number, title, and link
Link: https://leetcode.com/problems/car-fleet/
Number: 853
Name: Car Fleet

### Category of the bug
- [ ] Problem description
- [ ] Broken Testcase

### Description of the bug
First the code ran smoothly,

### Language used for code
C#

### Code used for Submit/Run operation

```
public class Solution {
    public int CarFleet(int target, int[] position, int[] speed) {
        List<int> values = new List<int>();
        for(int i = 0; i < position.Count(); i++){
            values.Add(position[i] + speed[i]);
        }
        if (values.Contains(target)) return values.Distinct().ToArray().Length;
        else return 1;
    }
}
```

### Expected behavior
The code I added is wrong but I think the test case is broken, since the given output was clearly what was expected in the 3 test cases yet, it displayed wrong answer.

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/72701348/21d3a8fc-1a22-4b34-aee8-abfb1dab8fe8)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/72701348/dca4455b-5d4a-43f2-921a-ec6144dce351)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/72701348/3b35c1ae-cc45-4cd1-a845-9c014ec635b2)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/72701348/2a8a62e1-bb8e-4893-ab73-b3a7a8151f45)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/72701348/1bceea67-b142-46e8-9491-98db262976a8)

### Additional context
When there were 2 or more output with the same value, and met the target, the expected value would become null, I think that's the issue

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
