### ISSUE TITLE
GUI ERROR

### ISSUE THREAD

**Issue by PankajSharma3** [LeetCode-Feedback/LeetCode-Feedback#18807]
### LeetCode Username
Pankaj53

### Category of the bug
Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
I used the testcase - 
Input-
head = [1]
Output-
[]
Expected-
[]
And the compiler is showing the correct answer.
But after the submission that particular case failed that I have checked at the time of running the code-
Wrong Answer 66/70 testcases passed 
Input-
head = [1]
Output-
[1]
Expected-
[]

### Language used for code
C++

### Code used for Submit/Run operation

```
/**
 * Definition for singly-linked list.
 * struct ListNode {
 *     int val;
 *     ListNode *next;
 *     ListNode() : val(0), next(nullptr) {}
 *     ListNode(int x) : val(x), next(nullptr) {}
 *     ListNode(int x, ListNode *next) : val(x), next(next) {}
 * };
 */
class Solution {
public:
    ListNode* deleteMiddle(ListNode* head) {
        int index = 0;
        ListNode* temp = head;
        while(temp!=NULL)
        {
            index++;
            temp = temp->next;
        }
        index/=2;
        temp = head;
        if(index==0)
        return head;
        ListNode* current = head;
        ListNode* previous = nullptr;
        int i=0;
        while(i!=index){
            previous = current;
            current = current->next;
            i++;
        }
        previous->next = current->next;
        delete current;
        return head;
    }
};
// Paste your code here. Don't remove ``` given
// above and below the code.
```

### Expected behavior
I used the testcase at the time of running the code - 
Input-
head = [1]
Output-
[]
Expected-
[]
After submission-
Wrong Answer 66/70 testcases passed 
Input-
head = [1]
Output-
[1]
Expected-
[]

### Screenshots
![Screenshot 2023-12-18 211806](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/118182606/30575e2a-da52-4d03-94ef-4ff12ea4ba9b)

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
