### ISSUE TITLE
Strict Time Limit

### ISSUE THREAD

**Issue by Izajur** [LeetCode-Feedback/LeetCode-Feedback#1880]
#### Your LeetCode username

izaj_iitkgp

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

TLE for 1.2s solution. If used lower_bound(set.begin(), set.end(), k) instead of set.lower_bound(k), solution is taking around 1.5s.

#### Code you used for Submit/Run operation

```
    const int INF = 1e9+7;
    
    int maxSumSubmatrix(vector<vector<int>>& matrix, int k) {
        int ans = -INF, pref;
        int n = matrix.size(), m = matrix[0].size();
        vector<int> sum;
        for(int col1=0; col1<m; col1++) {
            vector<int> sum (n, 0);
            for(int col2=col1; col2<m; col2++) {
                for(int i=0; i<n; i++)
                    sum[i] += matrix[i][col2];
                set<int> st;
                pref = 0;
                for(int num:sum) {
                    st.insert(pref);
                    pref += num;
                    auto itr = lower_bound(st.begin(), st.end(), pref-k);
                    if(itr!=st.end()) {
                        ans = max(ans, pref-(*itr));
                    }
                }
            }
        }
        return ans;
    }
```

#### Language used for code

C++

**Comment by lc-kay** [comment]
@Izajur What problem number is this issue in regards to?

**Comment by Izajur** [comment]
363

**Comment by lc-kay** [comment]
@Izajur I am receiving Compile Error when I run your code. Can you please provide your code through [Playground](https://leetcode.com/playground/new/empty)?

**Comment by lc-kay** [comment]
Hi @Izajur 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
