### ISSUE TITLE
[ Incorrect test Case ] 1174. Immediate Food Delivery II

### ISSUE THREAD

**Issue by qingyu-wang** [LeetCode-Feedback/LeetCode-Feedback#18819]
### LeetCode Username
qing-stanley
<img width="247" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/16367457/553bbda5-0056-4644-be1c-97de32978461">

### Problem number, title, and link
[1174. Immediate Food Delivery II](https://leetcode.com/problems/immediate-food-delivery-ii/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [X] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

| delivery_id | customer_id | order_date | customer_pref_delivery_date |
| ----------- | ----------- | ---------- | --------------------------- |
| 1           | 1           | 2019-08-01 | 2019-08-02                  |
| 2           | 2           | 2019-08-02 | 2019-08-02                  |
| 3           | 1           | 2019-08-11 | 2019-08-12                  |
| 4           | 3           | 2019-08-24 | 2019-08-24                  |
| 5           | 3           | 2019-08-21 | 2019-08-22                  |
| 6           | 2           | 2019-08-11 | 2019-08-13                  |
| 7           | 4           | 2019-08-09 | 2019-08-09                  |
| 8           | 4           | 2019-08-09 | 2019-08-10                  |
| 9           | 4           | 2019-08-09 | 2019-08-09                  |

If the input is set as above, the result should be 50, but the test result show that expected answer should be 75 which is wrong. It seem that the testcase program calculate the immediate status of customer_id = 4 twice, and divided by the distinct count of customer_id, (100+200)/4=75.

### Language used for code
MYSQL

### Code used for Submit/Run operation

```sql
SELECT
    ROUND(AVG(CASE WHEN t.immediate THEN 100 ELSE 0 END), 2) AS immediate_percentage
FROM
    (
        SELECT
            t1.order_date=MIN(t2.customer_pref_delivery_date) AS immediate
        FROM
            (
                SELECT
                    customer_id,
                    MIN(order_date) AS order_date
                FROM
                    Delivery
                GROUP BY
                    customer_id
            ) AS t1
            LEFT JOIN Delivery AS t2 ON 
                t1.customer_id = t2.customer_id
                AND t1.order_date = t2.order_date
        GROUP BY
            t1.customer_id
    ) AS t;
```

### Expected behavior
The result should be 50, but the test result show that expected answer should be 75 which is wrong, for customer_id = 4, the immediate status were calculate twice.

### Screenshots

<img width="633" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/16367457/86f54b98-d190-4e59-9f90-05349f89382b">

<img width="234" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/16367457/35577b10-c4c0-4e23-b72a-8b46d9b8352e">

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback. We encourage you to share your questions in the discussion forum, where the community can provide insights and assistance.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
