### ISSUE TITLE
1637. Widest Vertical Area Between Two Points Containing No Points - Worst Description

### ISSUE THREAD

**Issue by ShubhamKNIT** [LeetCode-Feedback/LeetCode-Feedback#18817]
### LeetCode Username

ShubhamKNIT

### Problem number, title, and link

1637. Widest Vertical Area Between Two Points Containing No Points https://leetcode.com/problems/widest-vertical-area-between-two-points-containing-no-points/

### Category of the bug
- [x] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Question description tells you to do:
```Return the widest vertical area between two points such that no points are inside the area.```

But, what we are supposed to do, we just have to find the width b/w maximum area possible containing no points.

Atleast write the description clearly. Even if u want to mask the question description with little informartion to make it difficult.

A question is never complete without clear and precise description whether it is short or long.

### Expected behavior

Solution 1 : 
Either change the function output to return the max area with same description.
Solution 2: (better)
Change the description of the question and ask leetcoders to return the width b/w maximum area possible containing no points.

### Screenshots

<img width="1440" alt="Screenshot 2023-12-21 at 8 23 59 AM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/121822213/a4f2688a-a66f-4273-bbd0-3cd28108529e">

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
