### ISSUE TITLE
wrong test cases 

### ISSUE THREAD

**Issue by ANSHUP13** [LeetCode-Feedback/LeetCode-Feedback#1881]
# Problem 1130. Minimum Cost Tree From Leaf Values

#### Your LeetCode username

anshumanp70

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
class Solution:
    def mctFromLeafValues(self, arr: List[int]) -> int:
        ans = 0
        arr.sort()
        n = len(arr)
        for i in range(1,n):
            ans += arr[i]*arr[i-1] 
        return ans
```

#### Language used for code

Python3

#### Expected behavior

Algorithm:
step 1: sort the arr
step 2: construct the binary tree as following, then we can get the minimum
![image](https://user-images.githubusercontent.com/49411896/103733150-0f846b00-500f-11eb-9a72-3ed9c3829302.png)

#### Screenshots

![image](https://user-images.githubusercontent.com/49411896/103732483-70ab3f00-500d-11eb-8ba3-633ce3091837.png)

**Comment by lc-kay** [comment]
@ANSHUP13 The expected output is correct because after sorting arr, the leaf nodes are no longer in an "in-order" traversal. Please refer to the discuss section to see other explanations and accepted codes. Thank you for your time.
