### ISSUE TITLE
Missing Test Case - 1321. Restaurant Growth

### ISSUE THREAD

**Issue by PSwicarz** [LeetCode-Feedback/LeetCode-Feedback#18814]
### LeetCode Username
piocarz

### Problem number, title, and link
1321. Restaurant Growth https://leetcode.com/problems/restaurant-growth/

### Category of the bug
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

testcases are sorted by default, and by default there are no gaps in dates - changing one date devastates 70% of "solutions"

### Language used for code
pandas

### Code used for Submit/Run operation
```
import pandas as pd

def restaurant_growth(customer: pd.DataFrame) -> pd.DataFrame:
    return (
        customer
        .groupby("visited_on")
        .sum()
        .amount
        .rolling(7)
        .agg(["sum", "mean"])
        .round(2)
        .reset_index()
        .dropna()
        .rename(columns={"sum": "amount", "mean": "average_amount"})
    )
```

### Expected behavior
this code is passing all test cases but breaks when one date is changed from default testcase (02 -> 12)

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/99476222/44f16ae2-c610-4462-871e-be94c409fe01)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by saeidamini** [comment]
Dear @LC-Pam 

When will this test be corrected?
Naturally, I have the same error on SQL.

**Comment by PSwicarz** [comment]
Hello, I'm not sure what do you mean by this question, I thought, that you
are the ones that fix test cases ;)

sob., 23 gru 2023, 10:27 użytkownik Saeid Amini ***@***.***>
napisał:

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
