### ISSUE TITLE
Typo in Problem Description - 2523. Closest Prime Numbers in Range

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#18816]
### LeetCode Username
stormsunshine

### Problem number, title, and link
[2523. Closest Prime Numbers in Range](https://leetcode.com/problems/closest-prime-numbers-in-range)

### Category of the bug
- [x] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
In problem description, the variable names should be `num1` and `num2`, not `nums1` and `nums2`. The typos should be fixed.

Please refer to the screenshot, where blue marks are the correct variable names and red marks are the incorrect variable names.

### Expected behavior
Fix the typos so that the variable names are `num1` and `num2`.

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/12067364/412a5cfa-6796-45cd-a003-3d35ddb6e0a3)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
