### ISSUE TITLE
Spelling mistake in "Widest Vertical Area Between Two Points Containing No Points" Editorial

### ISSUE THREAD

**Issue by Y-Rov** [LeetCode-Feedback/LeetCode-Feedback#18829]
### LeetCode Username

[anacondrai](https://leetcode.com/anacondrai/)

### Problem number, title, and link

[1637. Widest Vertical Area Between Two Points Containing No Points](https://leetcode.com/problems/widest-vertical-area-between-two-points-containing-no-points/)

### Category of the bug
- [ ] Editorial

### Description of the bug

Hello, LeetCode team😄

If we look at the 2-nd sentence in the [Editorial](https://leetcode.com/problems/widest-vertical-area-between-two-points-containing-no-points/editorial/), we can notice that the word "vertical" is misspelled:

> The problem is to find the widest verticle area between any two points without having any other point in between.

### Expected behavior

The corrected sentence should look like this:

> The problem is to find the widest vertical area between any two points without having any other point in between.

### Screenshots

![Vertical_Misspelling](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73534920/31388b10-a69c-4409-ba67-301c2f3e3068)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team

**Comment by Y-Rov** [comment]
Hi @LC-Pam, thank you for your answer. Unfortunately, there are no changes (look at my previous screenshot). Or should they be visible after a while, not immediately?

![Vertical_Misspelling_Not_Fixed](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73534920/4ccbbd7e-e0dd-40ad-a658-b71d6c889756)

**Comment by Y-Rov** [comment]
Hi @LC-Pam, the issue is resolved, thank you very much.

![Vertical_Misspelling_Fixed](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73534920/d0b687aa-2bff-45f2-8d8c-8ad970958e4f)
