### ISSUE TITLE
Incorrect testcase ( test case number 129 ) in question number 530. Minimum Absolute Difference in BST

### ISSUE THREAD

**Issue by VivekPrakashNitH** [LeetCode-Feedback/LeetCode-Feedback#18824]
### LeetCode Username
vivekprakashydvofficial

### Problem number, title, and link
1. Minimum Absolute Difference in BST [Problem Link](https://leetcode.com/problems/minimum-absolute-difference-in-bst/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
The provided C++ code for the problem "Minimum Absolute Difference in BST" is failing for a specific test case: `[236,104,701,null,227,null,911]`. The expected output for this test case is 9, but the actual output is 123.

### Language used for code
C++

### Code used for Submit/Run operation
```cpp
/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
class Solution {
public:
    int getMinimumDifference(TreeNode* root) 
    {
        
       if(!(root->left) && !(root->right))
       {
           return INT_MAX;
       }
       if(!root->left)
       {
           return min(abs(root->val - root->right->val),getMinimumDifference(root->right));
       }
       if(!root->right)
       {
           return min(abs(root->val-root->left->val),getMinimumDifference(root->left));
       }
       return min(min(abs(root->val-root->left->val ),abs(root->val-root->right->val)),min(getMinimumDifference(root->left),getMinimumDifference(root->right)));

    }
};
```
### Expected behavior
The expected behavior is that for the specific test case with number 129 (`[236,104,701,null,227,null,911]`), the output should be 123, but the expected output is 9.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/100904349/67ad42e4-9031-434d-82a9-14d45c4dbfb1)

### Additional context
Here's my LeetCode profile: [vivekprakashydvofficial](https://leetcode.com/vivekprakashydvofficial/)

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
