### ISSUE TITLE
【缺少测试用例】2866. 美丽塔 II 缺少测试用例导致某些低效代码AC

### ISSUE THREAD

**Issue by dyegral** [LeetCode-Feedback/LeetCode-Feedback#18821]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

### LeetCode 用户名
dyegral

### 问题号码、标题和链接
2866. 美丽塔 II https://leetcode.cn/problems/beautiful-towers-ii/description/?envType=daily-question&envId=2023-12-21

### Bug 类型
- [ ] 问题描述
- [ ] 示例
- [ ] 问题限制
- [ ] 问题提示
- [ ] 不正确或缺少“相关标签”
- [ ] 不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*
- [x] 缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*
- [ ] 力扣官方题解
- [ ] 编程语言支持

### 描述
缺少测试用例导致某些低效代码AC

### 你使用的语言
javascript

### 你提交或者运行的代码

```javascript
/**
 * @param {number[]} maxHeights
 * @return {number}
 */
var maximumSumOfHeights = function (maxHeights) {
  const n = maxHeights.length;
  let ans = 0;
  for (let i = 0; i < n; ++i) {
    if (maxHeights[i] <= maxHeights[i - 1] || maxHeights[i] < maxHeights[i + 1]) continue;
    let max = maxHeights[i];
    let curAns = max;
    for (let j = i - 1; j >= 0; --j) {
      const cur = Math.min(maxHeights[j], max);
      curAns += cur;
      max = cur;
    }
    max = maxHeights[i];
    for (let j = i + 1; j < n; ++j) {
      const cur = Math.min(maxHeights[j], max);
      curAns += cur;
      max = cur;
    }
    ans = Math.max(ans, curAns);
  }
  return ans;
}; 
```

### 期望行为
希望增加测试用例，让上述代码不应该AC
python3
```python3
[9, 8] * 50000
```

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
