### ISSUE TITLE
Missing Test Case - 201. Bitwise AND of Numbers Range

### ISSUE THREAD

**Issue by leonid-kukushkin** [LeetCode-Feedback/LeetCode-Feedback#18826]
### LeetCode Username

LeonidKukushkin

### Problem number, title, and link

https://leetcode.com/problems/bitwise-and-of-numbers-range

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

There are submissions that look simply for the highest one bit (e.g. 1000000) instead of the actual solution (e.g. 1100000) and they seem to pass all the tests.

### Language used for code

Java

### Code used for Submit/Run operation

```
public int rangeBitwiseAnd(int left, int right) {
    while (left < right) {
        right &= (right - 1);
    }
    return right;
}
```

### Expected behavior

The code above should fail but it's among the successful submissions.

### Additional context

If you take left = 107 (1101011) and right = 117 (1110101), the answer 96 (1100000) should be accepted and the answer 64 (1000000) is rejected.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission Accepted link. 

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by leonid-kukushkin** [comment]
I double checked the code and it's working as expected. Closing the issue. Sorry.
