### ISSUE TITLE
Missing Test Case - 82. Remove Duplicates from Sorted List II

### ISSUE THREAD

**Issue by Meet2000** [LeetCode-Feedback/LeetCode-Feedback#1882]
#### Your LeetCode username
Meet2000

I would like to suggest some test cases for problem mentioned in title
1. [1,1,2]
2. [1,2,2]
3. [1,1,2,2]

Thank you

**Comment by lc-kay** [comment]
@Meet2000 Please provide the code that these test cases failed on. Thank you!

**Comment by lc-kay** [comment]
Hi @Meet2000 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
