### ISSUE TITLE
Missing Test Case - 121. Best Time to Buy and Sell Stock

### ISSUE THREAD

**Issue by ThanoS-max** [LeetCode-Feedback/LeetCode-Feedback#1883]
#### Your LeetCode username

thanos9979

#### Category of the bug
- [ yes] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

In Problem No. 121( Say you have an array for which the ith element is the price of a given stock on day i.

If you were only permitted to complete at most one transaction (i.e., buy one and sell one share of the stock), design an algorithm to find the maximum profit.

Note that you cannot sell a stock before you buy one.) 
===================================================================
here, the question states that we are allowed to have only one transaction but, in "i.e." bracket it is stated "buy AND sell one", It should be "buy OR sell one" as withdrawal and deposit both fall in "Transaction" category.
Thank you.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
Hi @ThanoS-max 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @ThanoS-max 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
