### ISSUE TITLE
When submitting solutions for SQL exercises, there is no PostgreSQL tag

### ISSUE THREAD

**Issue by agosmou** [LeetCode-Feedback/LeetCode-Feedback#18830]
### Tag Issue

When submitting solutions for SQL exercises, there is no PostgreSQL tag

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

When submitting solutions for SQL exercises, there is no PostgreSQL tag

### Language used for code

PostgreSQL

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73868258/51ab8961-3071-46ea-9dde-2a09a2c4e662)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73868258/6a234631-18cd-4542-a363-db3eec3ec421)

**Comment by LC-Pam** [comment]
Due to the high volume of the reports, we will temporarily close this ticket right now.
 
However, your feedback has already been successfully submitted to the team.
 
Once we have any updates from the team, we will re-open this ticket and get back to you.
 
Thank you for your understanding!
