### ISSUE TITLE
Missing Test Case - 2617. Minimum Number of Visited Cells in a Grid

### ISSUE THREAD

**Issue by hikjik** [LeetCode-Feedback/LeetCode-Feedback#18835]
### LeetCode Username
morev

### Problem number, title, and link
2617. Minimum Number of Visited Cells in a Grid
https://leetcode.com/problems/minimum-number-of-visited-cells-in-a-grid/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
The solution passes all test cases but is inefficient and has quadratic time complexity.

### Language used for code
C++

### Code used for Submit/Run operation
The code was taken from here:
https://leetcode.com/problems/minimum-number-of-visited-cells-in-a-grid/solutions/3395695/bfs-with-skip-ahead
```
class Solution {
public:
  int minimumVisitedCells(vector<vector<int>> &g) {
    int m = g.size(), n = g[0].size(), steps = 0;
    vector<vector<int>> max_i(m, vector<int>(n)), max_j(m, vector<int>(n));
    vector<pair<int, int>> q{{0, 0}}, q1;
    while (!q.empty()) {
      ++steps;
      for (auto [i, j] : q) {
        if (i == m - 1 && j == n - 1)
          return steps;
        for (int k = i + 1; k < m && k - i <= g[i][j]; ++k) {
          if (max_i[k][j] == 0) {
            q1.push_back({k, j});
            max_i[k][j] = i + g[i][j];
          } else
            k = max_i[k][j];
        }
        for (int k = j + 1; k < n && k - j <= g[i][j]; ++k) {
          if (max_j[i][k] == 0) {
            q1.push_back({i, k});
            max_j[i][k] = j + g[i][j];
          } else
            k = max_j[i][k];
        }
      }
      swap(q, q1);
      q1.clear();
    }
    return -1;
  }
};
```

### Expected behavior
The solution of the problem should be rejected (TLE) due to inefficiency. Below is a suggestion for a new test case that will help to reject inefficient solutions

### Screenshots
Accepted:
https://leetcode.com/problems/minimum-number-of-visited-cells-in-a-grid/submissions/1125495562/
![Screenshot from 2023-12-22 04-47-50](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/28428906/ab024af7-608a-4fbf-91d5-2f5decf3ae97)

TLE for new test case:
![Screenshot from 2023-12-22 04-50-40](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/28428906/f916565f-79bd-4fcc-8f49-8f1b1dca72c0)

### Additional context
New test case:
[testcase_LC2617.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/13747441/testcase_LC2617.txt)

The test case was generated by the following code
```python3
m, n = 1, 100000
grid = [[n // 2 for i in range(n)]]
grid[0][-1] = 0
print(grid)
```

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

We can’t add the test case currently because of technical issues.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
