### ISSUE TITLE
Disgusting video quality 

### ISSUE THREAD

**Issue by anastasiiaBahno** [LeetCode-Feedback/LeetCode-Feedback#18844]
I'm a viewer of system-design-for-interviews-and-beyond course.
Each time the video quality goes up and down. When it's low it's not possible to read text in slides. During 6 min video it happens about 3-4 times. So, approximately for 3 mins slides is not readable.
I have stable internet connection, and don't have such problem with Youtobe(as an example).

**Comment by LC-Pam** [comment]
Due to the high volume of the reports, we will temporarily close this ticket right now.
 
However, your feedback has already been successfully submitted to the team.
 
Once we have any updates from the team, we will re-open this ticket and get back to you.
 
Thank you for your understanding!
