### ISSUE TITLE
938. Range Sum of BST. Editorial wrong grammar

### ISSUE THREAD

**Issue by andennis** [LeetCode-Feedback/LeetCode-Feedback#18843]
### LeetCode Username
andennis

### Problem number, title, and link
938. Range Sum of BST https://leetcode.com/problems/range-sum-of-bst/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug
There might be grammatically incorrect sentence in the [Editorial](https://leetcode.com/problems/range-sum-of-bst/editorial/) -> Complexity Analysis -> Space Complexity
"...the worst-case scenario occurs when the tree `is is` of chain shape..."

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
