### ISSUE TITLE
Missing Test Case - 79. Word Search

### ISSUE THREAD

**Issue by abhisingh91** [LeetCode-Feedback/LeetCode-Feedback#18845]
### LeetCode Username 
abhi_singh91

### Problem number, title, and link 
79. Word Search https://leetcode.com/problems/word-search/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
- My code was not completely correct, however, it passed all the tests that were generated for the problem due to the absence of some proper test cases.
- Not only it got accepted, but the runtime was also a lot faster (99%).

### Language used for code
Python

### Code used for Submit/Run operation

```
class Solution:
    def exist(self, board: List[List[str]], word: str) -> bool:
        rows, cols = len(board), len(board[0])
        def isValid(row, col):
            return row >= 0 and col >= 0 and row < rows and col < cols

        def neighbours(row, col):
            indices = [(row-1, col), (row+1, col), (row, col-1), (row, col+1)]
            return [(r, c) for r, c in indices if isValid(r, c)]
        
        letter = []
        for i in range(rows):
            for j in range(cols):
                if board[i][j] == word[0]:
                    letter.append((i, j))

        length = len(word)-1
        if len(letter) > 25:
            return False
        for m, n in letter:
            queue = [(m, n, 0, [(m, n)])]
            while queue:
                row, col, i, path = queue.pop()
                if i == length:
                    return True
                for r, c in neighbours(row, col):
                    if (r, c) not in path and board[r][c] == word[i+1]:
                        queue.append((r, c, i+1, path+[(r, c)]))
        return False
```

### Expected behavior
- The submission should not have been Accepted. 
- Below is a valid test case that i created, and it resulted in 'Wrong Answer': 
```
board=[["A", "A", "A", "A", "A", "A"], ["A", "A", "A", "B", "A", "A"], ["A", "A", "A", "A", "A", "A"], ["A", "A", "A", "A", "A", "A"], ["A", "A", "A", "A", "A", "A"], ["A", "A", "A", "A", "A", "A"]]
word = "AB"
"
```

### Additional context
This part of my code is not correct, still all test cases were passed:
```
if len(letter) > 25:
    return False
```

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team

**Comment by abhisingh91** [comment]
Nice to know that my feedback was helpful!

Thanks for the (much appreciated) 100 LeetCoins 😅
