### ISSUE TITLE
203移除链表问题，java语言编译错误问题

### ISSUE THREAD

**Issue by ch-infinity** [LeetCode-Feedback/LeetCode-Feedback#18847]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

### LeetCode 用户名

陈鸿

### 问题号码、标题和链接
[203. 移除链表元素](https://leetcode.cn/problems/remove-linked-list-elements/)

### Bug 类型
- [ ] 问题描述
- [ ] 示例
- [ ] 问题限制
- [ ] 问题提示
- [ ] 不正确或缺少“相关标签”
- [ ] 不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*
- [ ] 缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*
- [ ] 力扣官方题解
- [x]编程语言支持

### 描述

编译错误

### 你使用的语言
java

### 你提交或者运行的代码

```
/**
 * Definition for singly-linked list.
 * public class ListNode {
 * int val;
 * ListNode next;
 * ListNode() {}
 * ListNode(int val) { this.val = val; }
 * ListNode(int val, ListNode next) { this.val = val; this.next = next; }
 * }
 */
class Solution {
    public ListNode removeElements(ListNode head, int value) {
        if (head == null) {
            return null;
        }
        while(value == head.val) {
            head = head.next;
        }
        if (head == null) {
            return null;
        }
        ListNode currentNode = head;
        while (currentNode != null && currentNode.next != null) {
            if (currentNode.next.val == value) {
                currentNode.next = currentNode.next.next;
            }
            currentNode = currentNode.next;

        }
        return head;
    }
}
```

### 期望行为

正常编译通过

### 屏幕截图

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/33154658/fe19b26a-fd7a-4075-9faa-b3d54203738b)

**Comment by stormsunshine** [comment]
你的代码第 17 行是 `head = head.next`，此时 `head` 指向的引用已经改变，当遍历到链表末尾时就会出现 `head == null`，此时就会抛出空指针异常。

这不是 LeetCode 的问题，如果你在本地 IDE 中运行，也会出现同样的异常。

**Comment by ch-infinity** [comment]
确实这边没有注意到循环中导致的空指针，而只关注到了前面的判空操作。感谢您的回答！
