### ISSUE TITLE
1422. Maximum Score After Splitting a String Incorrect topic tag

### ISSUE THREAD

**Issue by rogersentongo** [LeetCode-Feedback/LeetCode-Feedback#18854]
### LeetCode Username

rntongo

### Problem number, title, and link

1422. Maximum Score After Splitting a String https://leetcode.com/problems/maximum-score-after-splitting-a-string/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ x] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The problem should have Prefix Sum as one of its topics, instead its described as a String problem which is not entirely correct.

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
