### ISSUE TITLE
Missing Test Case - 124. Binary Tree Maximum Path Sum

### ISSUE THREAD

**Issue by Soundarya03** [LeetCode-Feedback/LeetCode-Feedback#1885]
#### Your LeetCode username

sr2code11
[View Profile](https://leetcode.com/sr2code11/)

#### Category of the bug
- [ ] Question

#### Description of the bug
Test cases are not sufficient, a crucial test case is missing. I've suggested it here: 
**[-1,-2,10,-6,null,-3,-6]**

Code that passes all your current test cases fails this one. This test case ensures that the problem is solved more completely, and edge cases are taken care of. **_It represents the case where a single node(need not be the root) can have a value greater than any path._**
Please consider adding it. 

Try running the code below, and you will see that it is accepted. However, it fails in case of the above-mentioned test case. 

#### Code you used for Submit/Run operation

```
#include<math.h>
/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
class Solution {
public:
    int dfs(TreeNode* root, int *maximum){
        int lsum=0, rsum=0, sum;
        
        if(root->left)
            lsum = dfs(root->left, maximum);
        else
            lsum = 0;
        
            
        if(root->right)
            rsum = dfs(root->right, maximum);
        else if(root->right)
            rsum = 0;
        
        
        /*WRONG, yet accepted:*/ *maximum = max({lsum+root->val, rsum+root->val, lsum+rsum+root->val, *maximum});
        //CORRECT: *maximum = max({lsum+root->val, rsum+root->val, lsum+rsum+root->val, *maximum, root->val});
        //root->val also needs to be checked while setting maximum here!!
        
        return max({lsum+root->val, rsum+root->val, root->val});
    }
    
    
    int maxPathSum(TreeNode* root) {
        if(!root)
            return 0;
        int maximum = root->val;
        dfs(root, &maximum);
        return maximum;
    }
};
```

#### Language used for code
C++

#### Explanation
Expected output: 10
Output of above incorrect code: 9
Reason: A single node(need not be the root) can have a value greater than any path.

**Comment by lc-kay** [comment]
Hi @Soundarya03 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Soundarya03 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by Soundarya03** [comment]
Thank you for your response!
