### ISSUE TITLE
"2759. Convert JSON String to Object" contains an illegal testcase.

### ISSUE THREAD

**Issue by chaosxlive** [LeetCode-Feedback/LeetCode-Feedback#18851]
### LeetCode Username
chaosxlive

### Problem number, title, and link
[2759. Convert JSON String to Object](https://leetcode.com/problems/convert-json-string-to-object/)

### Category of the bug
- [x] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
In the description, it mentions that **String values within the JSON will only contain alphanumeric characters**

However, there is a testcase(267 / 285): `'{"a":",","b":[",",",","1"]}'`. The `","` is against the rule, isn't it?

### Language used for code
javascript

### Code used for Submit/Run operation

```
// https://leetcode.com/problems/convert-json-string-to-object/

/**
 * @param {string} s
 * @return {null|boolean|number|string|Array|Object}
 */
var jsonParse = function (s) {
    if (s[0] === '{') {
        return parseJsonObject(s);
    } else if (s[0] === '[') {
        return parseJsonArray(s);
    } else if (s[0] === '"') {
        return s.substring(1, s.length - 1);
    } else if (s[0] === 't') {
        return true;
    } else if (s[0] === 'f') {
        return false;
    } else if (s[0] === 'n') {
        return null;
    } else {
        return +s;
    }
};


var parseJsonObject = function (s) {
    const result = {};
    let i = 2;
    let keyStartIdx = 2;
    while (i < s.length) {
        while (s[i] !== '"') {
            i++;
        }
        const key = s.substring(keyStartIdx, i);
        i += 2
        const valueStartIdx = i;
        let bracketCnt = 0;
        while (true) {
            if (s[i] === '{') {
                bracketCnt++;
            } else if (s[i] === '[') {
                bracketCnt++;
            } else if (s[i] === ']') {
                bracketCnt--;
            } else if (s[i] === '}') {
                if (bracketCnt === 0) {
                    break;
                }
                bracketCnt--;
            } else if (s[i] === ',') {
                if (bracketCnt === 0) {
                    break;
                }
            }
            i++;
        }
        const value = s.substring(valueStartIdx, i);
        result[key] = jsonParse(value);
        keyStartIdx = i + 2;
        i += 2;
    }
    return result;
}

var parseJsonArray = function (s) {
    const result = [];
    let i = 1;
    let valueStartIdx = 1;
    while (i < s.length) {
        let bracketCnt = 0;
        while (true) {
            if (s[i] === '[') {
                bracketCnt++;
            } else if (s[i] === '{') {
                bracketCnt++;
            } else if (s[i] === '}') {
                bracketCnt--;
            } else if (s[i] === ']') {
                if (bracketCnt === 0) {
                    break;
                }
                bracketCnt--;
            } else if (s[i] === ',') {
                if (bracketCnt === 0) {
                    break;
                }
            }
            i++;
        }
        const value = s.substring(valueStartIdx, i);
        result.push(jsonParse(value));
        valueStartIdx = i + 1;
        i += 1;
    }
    return result;
}
```

### Expected behavior
The testcase should not have any string that contains non-alphanumeric characters. Expected only `/[a-zA-Z0-9]/`

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/34861326/c5e16e3b-2f0b-43ad-8ed1-449bf03f1c48)

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
