### ISSUE TITLE
287. Find the Duplicate Number - Missing Test Case

### ISSUE THREAD

**Issue by pkhsaxena** [LeetCode-Feedback/LeetCode-Feedback#18852]
### LeetCode Username

marsquake

### Problem number, title, and link

287. Find the Duplicate Number https://leetcode.com/problems/find-the-duplicate-number/

### Category of the bug
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

When using the frequency counting approach, all test cases have values in nums array that are within the indexing range of the array, i.e., ∀nums[i] < nums.length. This allows you to index the frequency array without bound checks.

### Language used for code

Java

### Code used for Submit/Run operation

```
class Solution {
    public int findDuplicate(int[] nums) {
        int len = nums.length;
        int[] cnt = new int[len + 1];
        for (int i = 0; i < len; i++) {
            cnt[nums[i]]++;
            if (cnt[nums[i]] > 1) {
                return nums[i];
            }
        }

        return len;
    }
}
```

### Expected behavior

The above mentioned solution should be rejected because when performing the operation ```cnt[nums[i]]++```, ```nums[i]``` can be beyond the range of array index.

### Screenshots

<img width="976" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/43796246/6d6b695f-a08e-41ab-9635-cf6313db3956">

### Additional context

Sample test case used in the screenshot ﹣ [1, 100, 4, 4]. When performing ```cnt[nums[i]]++``` on index 1, ```cnt[100]``` is out of bounds of the array, and will give an exception.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
