### ISSUE TITLE
Missing Test Case -1539. Kth Missing Positive Number

### ISSUE THREAD

**Issue by pracvp** [LeetCode-Feedback/LeetCode-Feedback#1886]
#### Your LeetCode username
pv9273

#### Category of the bug

- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
A solution is accepted but fails on the following test case:
**arr=[5,6,7,8,9]
k=9**
-The expected output is 18,the code gives the output 14, but still passes. 
-This is probably an error for test cases with starting value of array not 1( arr[0] is not 1 ), but all  values succeeding it are continuous.

#### Code you used for Submit/Run operation

```
// Kth Missing Positive Number
class Solution {
public:
    int findKthPositive(vector<int>& arr, int k) {
        int count=0;
        int ans;
        int num=1;
       if(arr.size()==0)
           return k;
/*********** when first number is greater **********/        
        while(num!=arr[0])
        { count++;
         //   if(num==arr[0])
        //     break;
          num++;        }
        
        ans=num-1;
       while(count>k)
      {
          count--;
          ans--;
      }
        if(count==k)
            return ans;

        bool t=true; /*********if true all numbers are continous and misssing is after end *******/ 
        for(int i=1;i<arr.size();i++)
        {
            if(arr[i]-arr[i-1]>1)
            { //cout<<arr[i]-arr[i-1]<<endl;
            count=count+(arr[i]-arr[i-1]-1);
            ans=arr[i]-1;
            t=false; //number missing b/w array
            while(count>k&&ans!=arr[i-1])
            {
                count--;
                 ans--;     
            }   
            if(count==k)
            {return ans;}
            }
        }
        
        
      //no missing number in array  
           if(t==true)
            {   // if(k==count)
               //return ans;
               count=1;
               ans=arr[arr.size()-1]+1;
               //  count=count+arr[arr.size()-1];     
                while(count<k)
            {   ans++;
                count++;
            }
             return ans;
            }
    // when array end kth missing number not found 
  if(count<k)
  {    ans=arr[arr.size()-1]-1;
  // cout<<ans<<endl;
              while(count<k)
            {   
                  ans++;
                count++;
            }
  }
        return ans+1;
    }
};
```

#### Language used for code
 C++ 

#### Expected behavior
- For, arr=[5,6,7,8,9], k=9. The expected output is 18,the code gives the output 14, but still passes. 
-This is probably an error for test cases with starting value of array not 1( arr[0] is not 1 ), but all  values succeeding it are continuous.

#### Screenshots
![lc2](https://user-images.githubusercontent.com/66632107/103769577-8db23300-504a-11eb-88d2-8b9f23e9b346.PNG)

**Comment by lc-kay** [comment]
Hi @pracvp 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @pracvp 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
