### ISSUE TITLE
Missing Test Case - 1496. Path Crossing

### ISSUE THREAD

**Issue by krvivi28** [LeetCode-Feedback/LeetCode-Feedback#18861]
### LeetCode Username
nil28

### Problem number, title, and link
https://leetcode.com/problems/path-crossing/description/

### Category of the bug
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### Description of the bug
For this test case ""ENNNNNNNNNNNEEEEEEEEEESSSSSSSSSS" the answer should be false as this path will never visit any of the point visited before but the expected answer is true.

### Language used for code
java

### Code used for Submit/Run operation

```
class Solution {

    public boolean isPathCrossing(String s) {
        int[] startpoint = { 0, 0 };
//		Pair<String,Integer> p=new Pair<>("kjm",7);
		HashMap<String, Integer> m = new HashMap<>();
		m.put("00", 1);
		for (int i = 0; i < s.length(); i++) {
			String currentIndex;
			switch (s.charAt(i)) {
			case 'N':
				startpoint[1] += 1;
				currentIndex= startpoint[0] + "" + startpoint[1] + "";
				m.put(currentIndex, m.getOrDefault(currentIndex, 0) + 1);
				break;
			case 'E':
				startpoint[0] += 1;
				currentIndex= startpoint[0] + "" + startpoint[1] + "";
				m.put(currentIndex, m.getOrDefault(currentIndex, 0) + 1);
				break;
			case 'S':
				startpoint[1] -= 1;
				currentIndex= startpoint[0] + "" + startpoint[1] + "";
				m.put(currentIndex, m.getOrDefault(currentIndex, 0) + 1);
				break;
			case 'W':
				startpoint[0] -= 1;
				currentIndex= startpoint[0] + "" + startpoint[1] + "";
				m.put(currentIndex, m.getOrDefault(currentIndex, 0) + 1);
				break;
			default:
			}

		}
		for (String key : m.keySet()) {
			if(m.get(key)>1)
                return true;
		}
        return false;
        
    }
}
```

### Expected behavior
For this test case ""ENNNNNNNNNNNEEEEEEEEEESSSSSSSSSS" the answer should be false as this path will never visit any of the point visited before but the expected answer is true.

### Screenshots
<img width="1462" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/98168919/579e6862-5154-4b12-8375-a1cfab77099b">

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
