### ISSUE TITLE
Missing Test Case - 1496. Path Crossing

### ISSUE THREAD

**Issue by liuliuOD** [LeetCode-Feedback/LeetCode-Feedback#18862]
### LeetCode Username
liuliugit

### Problem number, title, and link
1496. Path Crossing https://leetcode.com/problems/path-crossing/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
We need a test case that path="EEESWNN".

### Language used for code
Python3

### Code used for Submit/Run operation

```python
class Solution:
    def isPathCrossing(self, path: str) -> bool:
        n = len(path)
        x = y = 0
        for index in range(n):
            move = path[index]
            if move == 'N':
                x += 1
                if index > 0 and path[index-1] == 'S':
                    return True
            if move == 'S':
                x -= 1
                if index > 0 and path[index-1] == 'N':
                    return True
            if move == 'E':
                y += 1
                if index > 0 and path[index-1] == 'W':
                    return True
            if move == 'W':
                y -= 1
                if index > 0 and path[index-1] == 'E':
                    return True

            if x == 0 == y:
                return True

        x = y = 0
        for index in reversed(range(n)):
            move = path[index]
            if move == 'N':
                x += 1
                if index < n-1 and path[index+1] == 'S':
                    return True
            if move == 'S':
                x -= 1
                if index < n-1 and path[index+1] == 'N':
                    return True
            if move == 'E':
                y += 1
                if index < n-1 and path[index+1] == 'W':
                    return True
            if move == 'W':
                y -= 1
                if index < n-1 and path[index+1] == 'E':
                    return True

            if x == 0 == y:
                return True

        return False
```

### Expected behavior

We need to add the above new test case to prevent false accepted solutions.

### Screenshots

I commit the code included above and get `Accepted`. But can't pass the test case I provide.

<img width="1286" alt="Screenshot 2023-12-23 at 7 27 47 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/44393673/5f100a95-afa4-42d4-8c94-2cc36f2f47e8">

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
