### ISSUE TITLE
Missing Test Case - 1496. Path Crossing

### ISSUE THREAD

**Issue by tredsused40** [LeetCode-Feedback/LeetCode-Feedback#18864]
### LeetCode Username

tredsused70

### Problem number, title, and link

1496. Path Crossing https://leetcode.com/problems/path-crossing/

### Category of the bug
- [.] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

Incorrect code gets accepted.

### Language used for code

C++

### Code used for Submit/Run operation

```
class Solution {
public:
    bool isPathCrossing(string &s) {
        int x = 35, y = 35, matrix[60][60] = {0}, n = s.size();
	matrix[x][y] = 1;
        for(int i = 0; i < n; i++)
        {
            if(s[i] == 'N')
                y++;
            else {
                if(s[i] == 'S')
                    y--;
                else {
                    if(s[i] == 'E')
                        x++;
                    else
                        x--;
                }
            }
            if(matrix[x][y] == 1)
                return 1;
            matrix[x][y] = 1;
        }
        return 0;
    }
};
```

### Expected behavior

This solution works only when 0 <= x, y < 60 always holds, however it's very easy to construct such case, that it doesn't hold, for example just 30 letters 'N' in a row, this will give RE(index out of bounds).

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/75163817/24a0882a-09f0-4313-beee-6014ac922e84)
![photo_5204200603025266635_w](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/75163817/3b8eebaf-2ce6-4975-a390-f0a11425c817)

### Additional context

The test used for run operation is "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNN".

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
