### ISSUE TITLE
Missing Test Case - 98. Validate Binary Search Tree

### ISSUE THREAD

**Issue by n3dhir** [LeetCode-Feedback/LeetCode-Feedback#18860]
### LeetCode Username

- user6694qk

### Problem number, title, and link

98. Validate Binary Search Tree https://leetcode.com/problems/validate-binary-search-tree/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

- i initialize a variable called lastSeen with -1, this variables stores the last seen node's value ( using inorder traversal ), when input nodes have value -1, weird things happen, and my code gets accepted even if the tree is not BST.

### Language used for code

- c++

### Code used for Submit/Run operation

```
/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
class Solution {

    bool solve(struct TreeNode* root, int* lastSeen) {
        if(!root) return true;
        if(!root->left && *lastSeen == -1) {
            *lastSeen = root->val;
            return solve(root->right, lastSeen);
        }
        if(root->left) {
            if(!solve(root->left, lastSeen) || *lastSeen >= root->val) return false;
        }
        if(*lastSeen >= root->val) return false;
        *lastSeen = root->val;
        if(root->right) {
            if(!solve(root->right, lastSeen)) return false;
        }
        return true;
    }

public:
    bool isValidBST(struct TreeNode* root) {
        int lastSeen = -1;
        return solve(root, &lastSeen);
    }
};
```

### Expected behavior

- for this input: [-1,-2,-2]
the code must return false, my code is returning true.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/84473151/9bbce889-6761-420a-a858-3fd41ad8975c)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/84473151/d0a31f4d-e6b2-473e-a364-f53ec343a163)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
