### ISSUE TITLE
Mistake in hint of a problem 

### ISSUE THREAD

**Issue by Hr1t1k** [LeetCode-Feedback/LeetCode-Feedback#18870]
### LeetCode Username

hritik__k

### Problem number, title, and link

[10033. Count the Number of Incremovable Subarrays II](https://leetcode.com/problems/count-the-number-of-incremovable-subarrays-ii/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
-  Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

In the mentioned problem the 2nd hint is given as "Calculate the smallest y such that nums[j..nums.length-1] is strictly increasing." but i think instead of smallest y it should be smallest j or insetead of [j..nums.length-1] it should be [y..nums.length-1]

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
