### ISSUE TITLE
Wrong output for testcase - 10. Regular Expression Matching

### ISSUE THREAD

**Issue by ganeshlandge** [LeetCode-Feedback/LeetCode-Feedback#18879]
### LeetCode Username
ganeshlandge936

### Problem number, title, and link
10.[Regular Expression Matching](https://leetcode.com/problems/regular-expression-matching/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Input: s ="ddk" p=".*..."
Expected: false
System: true
Given pattern p expects at least 4 characters. The string s has 3 characters, thus expected output should be false but system gives true output.

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

### Expected behavior

Output should be false.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by IAfanasov** [comment]
From description:
- '.' Matches any single character.​​​​
- '*' Matches **ZERO** or more of the preceding element.

so, '.*...' means 'at least 3 symbols' and it does match 'ddk'
