### ISSUE TITLE
[type error] 560. Subarray Sum Equals K

### ISSUE THREAD

**Issue by ayaankhan98** [LeetCode-Feedback/LeetCode-Feedback#1887]
#### Your LeetCode username
ayaankhan

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language

#### Description of the bug

Type error in line one of approach 4
![Capture](https://user-images.githubusercontent.com/43348292/103771755-5cd3fd00-504e-11eb-9969-4ef226cf7d5e.PNG)
#### repreesnted -> represented

**Comment by lc-kay** [comment]
Hi @ayaankhan98 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @ayaankhan98 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
