### ISSUE TITLE
Missing Test Case - 205. Isomorphic Strings

### ISSUE THREAD

**Issue by 22922511** [LeetCode-Feedback/LeetCode-Feedback#18871]
### Problem number, title, and link

205.  Isomorphic Strings https://leetcode.com/problems/isomorphic-strings/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
 Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Language used for code
 C++ 

### Code used for Submit/Run operation
 

```
   class Solution {
public:
    bool isIsomorphic(string s, string t) {
   vector<string>a(130,"ax");  
    vector<string>k(130,"ax");
  
     for(int i=0;i<(s.size());i++){
         int id=s[i];
  if(a[id]=="ax"){a[id]=t[i];}
else { if((a[id])[0]!=t[i]) return false;
}
     }
 for(int i=0;i<(s.size());i++){
          int id=t[i];
         
  if(k[id]=="ax"){k[id]=s[i];}
else { if((k[id])[0]!=s[i]) return false;

}
     }
    return true;   
    }
};
```

### Expected behavior

test case 
input  string s= "A0B"
          string t= "0BA"
for isomorphic A to 0
                        0 to B
output must be false but it shown true please find screenshots for reference.

### Screenshots
 
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/146309666/b978cd11-f040-4ca0-9616
![leetcode205](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/146309666/e63b3c86-4a0c-4c9e-9a77-d2081c5e308f)
-51e628d12b5e)

<for below mention test case that is  from your side which shows output must be false >
 
![Screenshot 2023-12-24 010832](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/146309666/43b55761-4f08-44f1-8528-f336c4604ae4)

### Additional context
infact this problem not work for integer string.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
