### ISSUE TITLE
Missing pseudocode for [BFS - Template]

### ISSUE THREAD

**Issue by Dizzydoze** [LeetCode-Feedback/LeetCode-Feedback#18881]
### Category of the bug
- [x] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug

Missing pseudocode for explore page of BFS.(screenshot attached.)

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

### Screenshots

<img width="1060" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/106438058/36e35dc1-70e8-4de5-b6e6-63a4b3d8c6fb">
<img width="1050" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/106438058/1fbe3114-9d6f-4ec9-926c-a14c9aa72419">

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The page link.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by SahilModi10** [comment]
Here is the page link:
https://leetcode.com/explore/learn/card/queue-stack/231/practical-application-queue/1372/

**Comment by akilesh96** [comment]
@LC-Pam @SahilModi10 @Dizzydoze https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/18720

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by xinyufeifei** [comment]
I encountered the same issue.

**Comment by RieBi** [comment]
Have the same issue

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
