### ISSUE TITLE
Missing Test Case - 124. Binary Tree Maximum Path Sum

### ISSUE THREAD

**Issue by vipvipul1** [LeetCode-Feedback/LeetCode-Feedback#18888]
### LeetCode Username
vipvipul1

### Problem number, title, and link
[124. Binary Tree Maximum Path Sum](https://leetcode.com/problems/binary-tree-maximum-path-sum/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Language used for code
Java

### Code used for Submit/Run operation

```
class Solution {
    class PathInfo {
        int maxSum, posSum;
        PathInfo(int ms, int ps) {
            maxSum = ms; posSum = ps;
        }
    }
    public int maxPathSum(TreeNode root) {
        PathInfo maxPathInfo = findMaxPath(root);
        return maxPathInfo.maxSum;
    }
    
    PathInfo findMaxPath(TreeNode root) {
        if (root == null) {
            return new PathInfo(Integer.MIN_VALUE, 0);
        }
        PathInfo leftInfo = findMaxPath(root.left);
        PathInfo rightInfo = findMaxPath(root.right);
        
        int curPosSum = root.val + leftInfo.posSum + rightInfo.posSum;
        int curMaxSum = Math.max(curPosSum, Math.max(rightInfo.maxSum, leftInfo.maxSum));
        if (curPosSum < 0) {
            curPosSum = 0;
        } else {
            curPosSum = Math.max(root.val + leftInfo.posSum, root.val + rightInfo.posSum);
        }
        return new PathInfo(curMaxSum, curPosSum);
    }
}
```

### Expected behavior
For test case: [20,-3,null,2,2,null,null,null,null]
expected output = 20
my code's output = 19
but still the code gets submitted.

### Screenshots
![Screenshot 2023-12-24 232113](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/22119081/44a3c94b-8767-4681-9f93-c1198225ecb9)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
