### ISSUE TITLE
Incorrect Test Case - 7. Reverse Integer

### ISSUE THREAD

**Issue by leventekoor** [LeetCode-Feedback/LeetCode-Feedback#1888]
#### Your LeetCode username

leventekoor

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language

#### Description of the bug

The integer 1534236469 reversed should be 9646324351 but the expected value is 0 for this testcase.

#### Code you used for Submit/Run operation

```
class Solution(object):
    def reverse(self, x):
        """
        :type x: int
        :rtype: int
        """
        sign = -1 if x < 0 else 1
        x *= sign
        
        n = list(str(x))
        r = len(n)/2
        for i in range(r):
            n[i],n[-i-1] = n[-i-1],n[i]
        
        return int("".join(n))*sign
```

#### Language used for code

Python

#### Expected behavior

The testcase should return positive for the output 9646324351 when the input is 1534236469.

#### Screenshots

![image](https://user-images.githubusercontent.com/55160577/103784400-2f7d5400-503a-11eb-9afd-9f2563a1ed2a.png)

**Comment by lc-kay** [comment]
@leventekoor Since 1534236469 falls outside out the range [−2**31, 2**31 − 1] specified in the problem and therefore requires you to return 0. Please refer to the discuss section for more explanation about this problem and test case. Thank you for your time.
