### ISSUE TITLE
Missing Test Case - 643. Maximum Average Subarray I

### ISSUE THREAD

**Issue by vaishak236** [LeetCode-Feedback/LeetCode-Feedback#18880]
### LeetCode Username

vaishak705
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```
      class Solution:
          def findMaxAverage(self, nums: List[int], k: int) -> float:
              
              curr = 0
              
              for i in range(k):
                  curr+=nums[i]/k
              
              ans = curr
              for i in range(k, len(nums)):
                  
                  curr+= (nums[i] - nums[i-k])/k
                  
                  ans = max(ans, curr)
                  
              return ans
            

### Expected behavior

The test with the input array [10000000, 10000000, 10000000, 10000000, 10000000, 1, 2, 3, 4, 5] and k = 6 resulted in a maximum average of 8333333.500000001. This result may not be accurate due to the way floating-point arithmetic is handled in the code, especially when dealing with large numbers and their combination with small numbers in the calculation of the average.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team
