### ISSUE TITLE
Incorrect testcase for problem 98

### ISSUE THREAD

**Issue by code-munchr** [LeetCode-Feedback/LeetCode-Feedback#18896]
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [X ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Test Case 69  has input :
root = [5,4,6,null,null,3,7] 

The output should be true for this test case but the expected output is set to false. The input is a valid binary search tree so the expected output should be true. 

### Language used for code

Java

### Code used for Submit/Run operation

```
/**
 * Definition for a binary tree node.
 * public class TreeNode {
 *     int val;
 *     TreeNode left;
 *     TreeNode right;
 *     TreeNode() {}
 *     TreeNode(int val) { this.val = val; }
 *     TreeNode(int val, TreeNode left, TreeNode right) {
 *         this.val = val;
 *         this.left = left;
 *         this.right = right;
 *     }
 * }
 */
class Solution {
    public boolean isValidBST(TreeNode root) {
        if (root == null) return false;
        boolean isValid = validateSubTree(root);
        return isValid;
    }
    public boolean validateSubTree(TreeNode node){
        if (node == null) return true;
        boolean hasLeftTreeValid =  true;
        boolean hasRightTreeValid = true;
        if (node.left != null){
          if (node.val <= node.left.val ) return false;
          hasLeftTreeValid = validateSubTree(node.left);
        } 
        if (node.right != null){
          if (node.val >= node.right.val ) return false;
          hasLeftTreeValid = validateSubTree(node.left);
        }
         if(hasLeftTreeValid && hasRightTreeValid) return true;
         return false;
    }
}
```

### Expected behavior

After hitting submit(initial test cases pass when run is clicked), the output for testcase 69 should be true but the expected output is set to false. The input is a valid binary search tree so the expected output should be true.

**Comment by n3dhir** [comment]
Actually, it's not a BST.

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/84473151/255335c4-ffb8-46d2-873c-38cb008770b8)

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/84473151/cd5b300d-c2e1-491f-bb4d-43ebf3b8c357)
To be a BST, the nodes of the right subtree of node 5 must be greater than 5, but in this example we have 3 which is less than 5 and it's in its right subtree, so it's not a BST.

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team

**Comment by n3dhir** [comment]
yes, that's what i told you, my code is wrong but it is getting accepted.
you lack this testcase [-1, -2, -2].
when i run my code on this testcase, my code gives a wrong answer, but your
system didn't  detect that.
[image: image.png]
