### ISSUE TITLE
Missing Test Case - 73. Set Matrix Zeroes

### ISSUE THREAD

**Issue by sumanbmondal** [LeetCode-Feedback/LeetCode-Feedback#18895]
### LeetCode Username 
sumanarlert

### Problem number, title, and link
73. Set Matrix Zeroes https://leetcode.com/problems/set-matrix-zeroes/

### Category of the bug
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug
Approach - Marking the entire row and column with a marker (Eg - 66666) if there is a 0, traversing the matrix again and changing the markers to 0.
Bug - If the matrix contains an element which has the same value as that of the marker, it would also get converted to 0.

### Language used for code
C++

### Code used for Submit/Run operation
```
class Solution {
public:
    vector<vector<int>> helper(vector<vector<int>>& matrix, int r, int c) {
        for (int i = 0; i < matrix.size(); i++) {
            if (matrix[i][c] == 0) continue;
            matrix[i][c] = 66666; 
        }
        for (int i = 0; i < matrix[0].size(); i++) {
            if (matrix[r][i] == 0) continue;
            matrix[r][i] = 66666; 
        }
        return matrix;
    }
    void setZeroes(vector<vector<int>>& matrix) {
        for (int i = 0; i < matrix[0].size(); i++) {
            for (int j = 0; j < matrix.size(); j++) {
                if (matrix[j][i] == 0) {
                    matrix = helper(matrix, j, i);
                }
            }
        }

        for (int i = 0; i < matrix[0].size(); i++) {
            for (int j = 0; j < matrix.size(); j++) {
                if (matrix[j][i] == 66666) {
                    matrix[j][i] = 0;
                }
            }
        }
    }
};
```

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
