### ISSUE TITLE
399. 除法求值 | 题目描述存在歧义

### ISSUE THREAD

**Issue by zerotrac** [LeetCode-Feedback/LeetCode-Feedback#1889]
**Bug 类型**

- [x] 题目

**描述**

题目描述中有两句话：

> 如果存在某个无法确定的答案，则用 -1.0 替代这个答案。

以及

> 你可以假设除法运算中不会出现除数为 0 的情况，且不存在任何矛盾的结果。

那么对于示例 1 中的询问 `["x","x"]` 而言，第二句话告诉我们 `x` 一定不会为 `0`，这样无论 `x` 为何数，`x/x` 都是**唯一确定的**，它的值为 1，不应当输出 -1.0 作为答案。

举一个生活中的例子，我只告诉你美元和人民币的兑换比是 6.4，现在问你英镑和英镑的兑换比是多少。虽然这是个无聊的问题，但它的答案显然应该是确定的 1。

**建议**

将

> 如果存在某个无法确定的答案，则用 -1.0 替代这个答案。

改为

> 如果问题中出现了给定的已知条件中没有出现的字符串，则用 -1.0 替代这个答案。

**备注**

该问题由用户 [anhpp](https://leetcode-cn.com/u/anhpp/) 提出，如果问题得到解决，可以将奖励的 coin 发至他的 ID。

**Comment by feiceh** [comment]
你好，目前的版本附加了用户提供的建议，变更为：如果存在某个无法确定的答案，则用 -1.0 替代这个答案。如果问题中出现了给定的已知条件中没有出现的字符串，也需要用 -1.0 替代这个答案。因为即便问题都是已知条件给出的字符串，也可能会无法确定答案。ID：anhpp 已给予积分奖励，后面题目运营团队会再修改表述的。
