### ISSUE TITLE
Missing Test Case - 506. Relative Ranks

### ISSUE THREAD

**Issue by bigbooksfan** [LeetCode-Feedback/LeetCode-Feedback#18898]
### LeetCode Username

bigbooksfan

### Problem number, title, and link

506. Relative Ranks https://leetcode.com/problems/relative-ranks/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [+] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Missing test case with input [2, 1].

### Language used for code

c++

### Code used for Submit/Run operation

```
class Solution {
public:
    vector<string> findRelativeRanks(vector<int>& score) {
        int sz = score.size();
        vector<string> ret;
        if (sz < 3) {
            ret.push_back("Gold Medal");
            if (sz > 1) {
                /*if (score[0] < score[1])*/ ret.insert(ret.begin(), "Silver Medal");
            }
            return ret;
        }
        vector<int> s(score);
        sort(s.begin(), s.end(), [](int lhs, int rhs){return lhs > rhs;});
        map<int, string> m;
        
        m[s[0]] = "Gold Medal";
        m[s[1]] = "Silver Medal";
        m[s[2]] = "Bronze Medal";

        for (int i = 3; i < sz; ++i) {
            m[s[i]] = to_string(i + 1);
        }

        for (int i : score) {
            ret.push_back(m[i]);
        }

        return ret;
    }
};
```

### Expected behavior

Expected output
["Gold Medal","Silver Medal"]
Getted output
["Silver Medal","Gold Medal"]

Despite this, all existed tests passed, solution passed

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
