### ISSUE TITLE
"LRU Cache" constant time implementation exceeds the run time beyond 640ms.

### ISSUE THREAD

**Issue by gvshiva** [LeetCode-Feedback/LeetCode-Feedback#189]
**What kind of the bug**
- [ ] problem
- [x] solution
- [ ] language

**Describe the bug**
I implemented a constant time algorithm in JavaScript for the question  "LRU Cache" under "30-Day LeetCoding Challenge" series which exceeds the run time beyond 640ms. Which is quite odd even compared to a linear time algorithm. 

**Algorithm**
It is asked to implement an LRU Cache with O(1) time complexity.

So for the same, I took three Javascript objects namely lru, recent, recentReverse and two more variables 'counter' and 'len' for counting and capacity respectively.
* lru is for inserting the key and value based on recent information from recent object.
* recent takes the counter value from the count variable as its key and value from put() 
     function whenever it is called.
* recentReverse is just a reverse of key and value pair of recent object. It is just to have constant time access of key from value.

**what language is your code written in**
JavaScript

**The code you submit/run**
```javascript
var LRUCache = function(capacity) {
    this.lru = {}; // just to push key value pair based on recent object

    //for recent object, count is used as value for each key
    this.recent = {}; 
    this.recentReverse = {}; // reverse of recent object
    
    this.len = capacity;
    this.count = 0;
};

LRUCache.prototype.get = function(key) {
    if(key in this.lru){  
        // previous count of this key is deleted
        delete this.recent[this.recentReverse[key]];

        //same key is re inserted with higher count and recentReverse is updated.
        this.recent[this.count] = key;
        this.recentReverse[key] = this.count;
        this.count++;        
        return this.lru[key];
    }
    else{
    	this.count++;
        return -1;
        }
};

LRUCache.prototype.put = function(key, value) {
    if(key in this.lru){
        //To update the key later, it is deleted from recent object
        delete this.recent[this.recentReverse[key]];       
    }
    else if(Object.keys(this.lru).length == this.len){ 
            // The top element from recent and corresponding key in lru is deleted.      
            let temp = Object.values(this.recent)[0];
            delete this.lru[temp]; 
            delete this.recent[this.recentReverse[temp]];        
            delete this.recentReverse[temp];
    }  

    //key if present updated or if not created   
    this.lru[key] = value;      
    this.recent[this.count] = key;
    this.recentReverse[key] = this.count;
    
    this.count++;  
};
```

**Expected behavior**
Since I used just three objects and accessed them in constant time and did not use any loops or recursions of any sort, it should give me a run time much better than what I got. 

Unless the built in functions are not accessing in constant time, my implementation should be efficient with runtime much better than 640ms.

**Screenshots**
Submission link for the problem:
https://leetcode.com/submissions/detail/329516029/

**Comment by CooperCooperCooper** [comment]
Hi @gvshiva,
Thank you for reaching out to us. I've relayed your feedback to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @gvshiva,
Thank you for your time. According to the problem and the data structures used to solve it, the solution can be O(1). But this doesn't mean the constant factor of the complexity must be low; in contrast, it's high due hash tables, maps and sets are kinda slow. Therefore the given runtime is expected.

**Comment by gvshiva** [comment]
Thanks for the response. I had faced such issues before this 'problem' as well. My intention behind this issue initiation is to identify the specific cause of using these hash maps, tables or sets. So that I can avoid using them later.

*My observation*
- A problem with one hash map with O(nlogn) implementation resulted below 100ms
- A problem with two hash maps with O(n) implementation went upto 300ms
- For this Problem with three hash maps with O(1) implementation went beyond 600 ms

Where exactly the problem lies? at building them itself? or accessing them? or accessing them through each other?

**Comment by CooperCooperCooper** [comment]
Hi @gvshiva ,
Thank you for reaching out to us again. I've relayed these questions to our team.

**Comment by CooperCooperCooper** [comment]
Hi @gvshiva ,
Thank you for your time. It is expected that runtime and memory usage for each program will vary with each execution,  and executions on different computers will also cause different results for the same code. Therefore, to improve on your submission runtime, we highly suggest you check out as many recent and highly-upvoted solution posts in the problem discuss sections as possible to learn from the talented users on our site. This Github Channel is reserved for Content-issues only, so we encourage you to reach out again when you have other [content issues](https://leetcode.com/discuss/general-discussion/526802/File-Problem-and-Solution-Content-Issues-to-Our-GitHub-Public-Feedback-Repo-Now!) to share. We appreciate your support and understanding.
