### ISSUE TITLE
Amortized complexity reported as average for Disjoint sets path compression

### ISSUE THREAD

**Issue by gpskalra** [LeetCode-Feedback/LeetCode-Feedback#18900]
### LeetCode Username
gaganpreet1810

### Problem number, title, and link
Explore card: https://leetcode.com/explore/learn/card/graph/618/disjoint-set/3880/

### Category of the bug
Incorrect information

### Description of the bug
I think the paper https://www.cs.tau.ac.il/~michas/ufind.pdf describes and proves bounds for amortized cost of path compression with arbitrary linking. It never discusses the average case. The explore card however says that the average case is O(logn) and also mentions that this paper discusses the average case.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team

**Comment by gpskalra** [comment]
Can you elaborate more so I can learn as well? After all, leetcode exists
to help us learn. Is my understanding incorrect? If so, how?

**Comment by gpskalra** [comment]
The same problem exists here. https://leetcode.com/explore/learn/card/graph/618/disjoint-set/3843/. I think it is important not to confuse average and amortized complexity. The inverse ackermann function bounds the "average" cost of one operation when considering a sequence of operations. So, the amortized complexity is O(inverse ackermann function). When we say "average complexity", we mean average over a set of inputs (usually of the same size). That is not being evaluated here.
