### ISSUE TITLE
Missing Test Case - 639. Decode Ways II

### ISSUE THREAD

**Issue by mkhuzaima** [LeetCode-Feedback/LeetCode-Feedback#18907]
### LeetCode Username
mkhuzaima

### Problem number, title, and link

639. Decode Ways II 

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

some of the test case gives time limit exceeded on this test case

### Language used for code
Python3

### Code used for Submit/Run operation

```
class Solution:
    def numDecodings(self, s: str) -> int:
        MOD = 1_000_000_007
        dp1 = 9 if s[-1] == '*' else int(s[-1] != '0')
        dp2 = 1

        for i in range(len(s)-2, -1, -1):
            current = 0
            if '1' <= s[i] <= '9':
                current += dp1
                
                if s[i] == '1':
                    if s[i+1] == '*':
                        current += (9 * dp2) % MOD
                    else:
                        current += dp2

                elif s[i] == '2':
                    if '0' <= s[i+1] <= '6':
                        current += dp2
                    elif s[i+1] == '*':
                        current += (6 * dp2) % MOD

            elif s[i] == '*':
                current += 9 * dp1

                # consider * as 1
                if s[i+1] == '*':
                    current += (9*dp2) % MOD
                else:
                    current += dp2
                    

                # consider * as 1
                if '0' <= s[i+1] <= '6':
                    current += dp2
                elif s[i+1] == '*':
                    current += (6 * dp2) % MOD

            dp1, dp2 = current, dp1

        return dp1 % MOD
```

### Expected behavior
The given code (which is unoptimized) should give a time limit exceeded in this test case. However, it is not checked.

input is `s= "*" 10^5 times`. I can't write a complete test case here, due to comment length limitation on GitHub issues.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team

**Comment by mkhuzaima** [comment]
Thanks

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
