### ISSUE TITLE
Output Error 

### ISSUE THREAD

**Issue by Anuragji1** [LeetCode-Feedback/LeetCode-Feedback#18902]
function expect(val) {
  return {
    toBe(otherVal) {
      return val === otherVal ? { value: true } : { error: "Not Equal" };
    },

    notToBe(otherVal) {
      return val !== otherVal ? { value: true } : { error: "Equal" };
    },
  };
}
Hello dear all, this code give me error. Please anybody correct it now

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.
Details regarding the missing test case.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team
