### ISSUE TITLE
Missing Test Case - 2978. Symmetric Coordinates

### ISSUE THREAD

**Issue by Shargano** [LeetCode-Feedback/LeetCode-Feedback#18912]
### LeetCode Username
Shargano
https://leetcode.com/Shargano/

### Problem number, title, and link
2978. Symmetric Coordinates https://leetcode.com/problems/symmetric-coordinates/

### Category of the bug
- [x] Problem description

### Description of the bug
At the problem description it's said, that table name is `Pairs`. But, in fact, table is named `Coordinates`.
Misleading information...

### Language used for code
SQL (PostgreSQL)

### Code used for Submit/Run operation

```
with numbered as (
    select *, row_number() over () as rnum
    from Coordinates -- ACTUAL TABLE NAME
)
select distinct t1.X as x, t1.Y as y
from numbered t1
join numbered t2 on t1.X = t2.Y and t1.Y = t2.X and t1.rnum <> t2.rnum
where t1.X <= t1.Y
order by 1, 2
```

### Expected behavior
Correct problem description.

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/44915282/2ea86bde-803d-4e30-975e-301fddb888bb)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
