### ISSUE TITLE
Missing Test Case - 58. Length of Last Word

### ISSUE THREAD

**Issue by MirkamolAsrorov** [LeetCode-Feedback/LeetCode-Feedback#18911]
### LeetCode Username
 Mirkamol5

### Problem number, title, and link
 58. Length of Last Word https://leetcode.com/problems/length-of-last-word/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ +] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ +] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The issue List that i set stores a character . Actually it must store a group of characters(word).

### Code used for Submit/Run operation

   
```
// Paste your code here. Don't remove ``` given
// above and below the code.
  public int lengthOfLastWord(String s) {
List<String> storage = new ArrayList<>();
      String word = "";
      for(int i = 0; i < s.length(); i++){
          
          if(s.charAt(i) != ' '){
              word += s.charAt(i);

          }else{
              if(!word.equals("")){  
                storage.add(word);
                word = "";
        }
        }
      }        
    int lastWordIndex = storage.size()-1;  
    String lastWord = storage.get(lastWordIndex);
    System.out.println(storage);
    return lastWord.length();
}
```

### Screenshots

![photo_2023-12-26_01-01-25](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/112309052/4e8d2cfc-95f8-4eab-ab9f-4501a5c507da)

**Comment by MirkamolAsrorov** [comment]
Happy reviewing and fixing!

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.


Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by MirkamolAsrorov** [comment]
Hello. Thank you for fixing the debug i reported.
