### ISSUE TITLE
Description Typo: 1155. Number of Dice Rolls With Target Sum

### ISSUE THREAD

**Issue by sevillal** [LeetCode-Feedback/LeetCode-Feedback#18914]
LeetCode Username
[user1914a](https://leetcode.com/user1914a/)

Problem number, title, and link
[1155. Number of Dice Rolls With Target Sum](https://leetcode.com/problems/number-of-dice-rolls-with-target-sum/)

### Category of the bug
- [x] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

There is a typo in the following line of the problem description. Please see the screenshot for more.

> and each die has k faces numbered from 1 to k.

### Expected behavior

and each **dice** has k faces numbered from 1 to k.

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/56176070/a42f3ca4-e1d1-456a-b88c-3fbdd3da2cb6)

**Comment by Y-Rov** [comment]
FYI: https://grammarist.com/usage/dice-die/ 🙂

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by sevillal** [comment]
Thanks @Y-Rov for your comment! 

Closing this issue since the text is fine.

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
