### ISSUE TITLE
Problem description - 2626. Array Reduce Transformation

### ISSUE THREAD

**Issue by NakerTheFirst** [LeetCode-Feedback/LeetCode-Feedback#18913]
### Category of the bug
- [x] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The task's description instructs to return an "reduced array", while the expected output format specified in code is a number.

### Language used for code

JavaScript

### Code used for Submit/Run operation

```
/**
 * @param {number[]} nums
 * @param {Function} fn
 * @param {number} init
 * @return {number}
 */
var reduce = function(nums, fn, init) {
    let val

    for (let i = 0; i < nums.length; i++) {
        if (i === 0) val = fn(init, nums[i])
        else if (i !== 0) val = fn(val, nums[i])
    }    

    if (nums.length === 0) return init
    return val
};
```

### Expected behaviour

The description should accurately say the return value should be a number, not an array.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73819831/687b47bf-d9b5-45b9-bf0b-d34472f61dac)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73819831/f342ea03-5daa-4000-8b2d-10101fa0fe0d)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question.

The term "reduced array" is defined and explained in the description, but we have updated it for greater clarity.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
