### ISSUE TITLE
缺少测试用例 - 1349. 参加考试的最大学生数

### ISSUE THREAD

**Issue by mannixzhong** [LeetCode-Feedback/LeetCode-Feedback#18910]
### LeetCode 用户名

[mannix-zhong](https://leetcode.cn/u/mannix-zhong/)

### 问题号码、标题和链接

[1349. 参加考试的最大学生数](https://leetcode.cn/problems/maximum-students-taking-exam/)

### Bug 类型
- [ ] 问题描述
- [ ] 示例
- [ ] 问题限制
- [ ] 问题提示
- [ ] 不正确或缺少“相关标签”
- [ ] 不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*
- [x] 缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*
- [ ] 力扣官方题解
- [ ] 编程语言支持

### 描述

代码未通过以下用例却提交通过
```
[[".","."]]
```
输出
```
2
```
预期结果
```
1
```

### 你使用的语言
Python3

### 你提交或者运行的代码

```python
class Solution:
    def maxStudents(self, seats: List[List[str]]) -> int:
        u = 1 << len(seats[0])
        cache = [[] if b & b >> 1 else [c for c in range(u) if not (c & c >> 1 or b & c >> 1 or b & c << 1)] for b in range(u)]
        f1 = [0] * u
        for row in seats:
            a = 0
            for v in row:
                a = a << 1 | (v == '.')
            f2 = [0] * u
            for b in range(u):
                f2[b] = max((f1[c] for c in cache[b]), default=0) + (a & b).bit_count()
            f1 = f2
        return max(f1)
```

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
