### ISSUE TITLE
Missing Test Case - 986. Interval List Intersections

### ISSUE THREAD

**Issue by beiz96** [LeetCode-Feedback/LeetCode-Feedback#1892]
#### Category of the bug
- [ ~] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

I guess we could add one more test case to check a corner case as follows:
[[0,2],[5,10]]
[[1,2],[2,3]]

It seems that my code version which didn't handle this corner case can still pass current test case suit.
This case indicates that when the first two intervals have the same end index, we should not simply advance in either array A or B, but need to check that whether some of them has following interval which has exactly the same starting index as this end index.

#### Code you used for Submit/Run operation

```
// The code version that handle this corner case correctly.
class Solution {
    public int[][] intervalIntersection(int[][] A, int[][] B) {
        List<int[]> res = new LinkedList<>();
        int i = 0, j = 0;
        while (i < A.length && j < B.length) {
            int[] a = A[i];
            int[] b = B[j];
            if (a[1] >= b[0] && b[1] >= a[0]) {
                int left = Math.max(a[0], b[0]);
                int right = Math.min(a[1], b[1]);
                res.add(new int[]{left, right});
            }
            if (a[1] < b[1]) i++;
            else if (a[1] > b[1]) j++;
            else if (a[1] == b[1]) {
                if (i == A.length-1) j++;
                else if (j == B.length-1) i++;
                else {
                    if (A[i+1][0] == a[1]) i++;
                    else j++;
                }
            }
        }
        return res.toArray(new int[res.size()][2]);
    }
}
```

#### Language used for code

Java

#### Expected behavior

To add this one more test case could help detect whether we handle this special case correctly.

**Comment by lc-kay** [comment]
@beiz96 Can you please provide a code that the custom test case fails on? Thank you!

**Comment by beiz96** [comment]
Sure! The following code can pass current test cases, but fail that custom test case.
```
class Solution {
    public int[][] intervalIntersection(int[][] A, int[][] B) {
        List<int[]> res = new LinkedList<>();
        int i = 0, j = 0;
        while (i < A.length && j < B.length) {
            int[] a = A[i];
            int[] b = B[j];
            if (a[1] >= b[0] && b[1] >= a[0]) {
                int left = Math.max(a[0], b[0]);
                int right = Math.min(a[1], b[1]);
                res.add(new int[]{left, right});
            }
            if (a[1] <= b[1]) i++;
            else j++;
        }
        return res.toArray(new int[res.size()][2]);
    }
}
```

**Comment by lc-kay** [comment]
Hi @beiz96 
Thank you! I've relayed this issue to our team to investigate.

**Comment by beiz96** [comment]
Thank you! @lc-kay

**Comment by lc-kay** [comment]
Hi @beiz96 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
