### ISSUE TITLE
328. Odd Even Linked List 

### ISSUE THREAD

**Issue by manoj091-rocker** [LeetCode-Feedback/LeetCode-Feedback#18924]
/**
 * Definition for singly-linked list.
 * public class ListNode {
 *     int val;
 *     ListNode next;
 *     ListNode() {}
 *     ListNode(int val) { this.val = val; }
 *     ListNode(int val, ListNode next) { this.val = val; this.next = next; }
 * }
 */
class Solution {
    public ListNode oddEvenList(ListNode head) {
        ListNode odd = new ListNode(-1);
        ListNode temp_o = odd;
        ListNode even = new ListNode(0);
        ListNode temp_e = even;
        ListNode temp = head;
        int count =1;
        while(temp!=null){
            if(count%2!=0){
                ListNode a = new ListNode(temp.val);
                temp_o.next=a;
                temp_o=a;
                temp=temp.next;
                count++;
            }
            else{
                ListNode a = new ListNode(temp.val);
                temp_e.next=a;
                temp_e=a;
                temp=temp.next;
                count++;
            }
        }
        odd = odd.next;
        even = even.next;
        temp_o.next=even;
        return odd;
    }
}

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.
Details regarding the missing test case.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team
