### ISSUE TITLE
Enable Bookmarking/ Highlighting on important text in the notes

### ISSUE THREAD

**Issue by dgirishkrishna** [LeetCode-Feedback/LeetCode-Feedback#18925]
### LeetCode Username

d-girishkrishna

### Problem number, title, and link
 Generic

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [*] Editorial
- [ ] Programming language support

### Description of the bug

It would be a good feature to enable bookmarking or highlighting in the notes or text present in the problem or in the other course materials.

It will help users to not miss important things while revisiting notes or leedcode content again.

Please make sure bookmarking/ highlighting feature is user's profile centric. Every user can have their own version of highlighting content / sentenses or paragraphs which they feel relevant for revision when they are revising concepts in the future.

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

**Comment by LC-Pam** [comment]
Due to the high volume of the reports, we will temporarily close this ticket right now.
 
However, your feedback has already been successfully submitted to the team.
 
Once we have any updates from the team, we will re-open this ticket and get back to you.
 
Thank you for your understanding!
