### ISSUE TITLE
Missing Test Case - 16. 3Sum Closest

### ISSUE THREAD

**Issue by DivyanshSrivastava04** [LeetCode-Feedback/LeetCode-Feedback#18920]
### LeetCode Username
user8881dy

### Problem number, title, and link
16. 3Sum Closest ([link](https://leetcode.com/problems/3sum-closest))

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Language used for code
Java

### Code used for Submit/Run operation

```
class Solution {
    public int threeSumClosest(int[] nums, int target) {
       int res=nums[0]+nums[1]+nums[nums.length-1];
       Arrays.sort(nums);
       int curr_sum=0;
       for(int i=0;i<nums.length-2;i++){
           int a_pointer=i+1;
           int b_pointer=nums.length-1;
           while(a_pointer<b_pointer){
               curr_sum = nums[i]+nums[a_pointer]+nums[b_pointer];
               if(curr_sum==target){
                 return curr_sum;
                }
               if(curr_sum>target){
                   b_pointer--;
               }else{
                   a_pointer++;
               }
           }
    
           if(Math.abs(target-curr_sum)<Math.abs(target-res)){
               res=curr_sum;
           }
       }
       return res;
    }
}
```

### Expected behavior
WA on testcase "nums = [-20,-19,41,1]", "target = 1"

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
