### ISSUE TITLE
Missing Test Case - 1159. Market Analysis II

### ISSUE THREAD

**Issue by Shargano** [LeetCode-Feedback/LeetCode-Feedback#18939]
### LeetCode Username
Shargano
https://leetcode.com/Shargano/

### Problem number, title, and link
1159 Market Analysis II   https://leetcode.com/problems/market-analysis-ii/

### Category of the bug
- [x] Problem description
- [x] Solved examples

### Description of the bug
It's impossible to match problem description and provided example!
I suppose, that problem description has been copied from another question (may be from this [one](https://leetcode.com/problems/market-analysis-i/description/)) or smth like this typo...

Here is the description of required solution:

```
Write a solution to find for each user, the join date and the number of orders they made as a buyer in 2019.
Return the result table in any order.
The result format is in the following example.
```

Quite simple for `hard` question, and then suddenly at the provided example and it's explanation there is smth about 'Second favorite brand' per user or whatsoever:

```
Output: 
+-----------+--------------------+
| seller_id | 2nd_item_fav_brand |
+-----------+--------------------+
| 1         | no                 |
| 2         | yes                |
| 3         | yes                |
| 4         | no                 |
+-----------+--------------------+
```

### Language used for code
SQL (PostgreSQL)

### Expected behavior
Correct description of the question

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
