### ISSUE TITLE
Constraints are missing - 500. Keyboard Row

### ISSUE THREAD

**Issue by pratap-082020** [LeetCode-Feedback/LeetCode-Feedback#1893]
#### Your LeetCode username

[pratap_082020](https://leetcode.com/pratap_082020/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Code fails on below Testcase: Please check the attached test case.

test case:
[test case Keyboard Row.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/5783026/test.case.Keyboard.Row.txt)

#### Code you used for Submit/Run operation

```
class Solution:
    def findWords(self, words: List[str]) -> List[str]:
        new_lst = []
        rows = ["QWERTYUIOP", "ASDFGHJKL", "ZXCVBNM"]
        for w in words:
            # temp variable
            tmp = -1
            prnt = True
            for i in (w.upper()):
                
                print("word:",set(w.upper()))
                
                if tmp == -1:
                    if i in rows[0]:
                        tmp = 0
                    if i in rows[1]:
                        tmp = 1
                    if i in rows[2]:
                        tmp = 2
                else:
                    if i not in rows[tmp]:
                        prnt = False
                        break;
            
            if prnt == True:
                new_lst.append(w)
                
        return new_lst
```

#### Language used for code

Python

#### Screenshots

![image](https://user-images.githubusercontent.com/71989691/103924585-3f7d5c80-513c-11eb-880b-d55e4a73f61e.png)

#### Additional context

Problem: https://leetcode.com/problems/keyboard-row/

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @pratap-082020 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
