### ISSUE TITLE
Missing Test Case - 680. Valid Palindrome II

### ISSUE THREAD

**Issue by sayedgamal99** [LeetCode-Feedback/LeetCode-Feedback#18933]
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [X] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
Missing test case: I found my old version solution got accepted when it miss simple test case which is:
when input string is: s='aaaz' the **Expected** output should be **True**, but my accepted old code produces: **False** which isn't correct.

### Language used for code
python

### Code used for Submit/Run operation

```
class Solution:
    def validPalindrome(self, s: str) -> bool:
        co = CO(s)

        length = len(s)
        if length == 1:
            return True

        left, right = 0, length-1
        valid = 0
        while (left <= right):
            if s[left] == s[right]:
                left += 1
                right -= 1
            else:

                if valid > 0:
                    return False
                if co[s[left]] % 2 != 0:
                    left += 1
                else:
                    right -= 1

                valid += 1
        return True
```

### Expected behavior
sample input: s='aaaz'
accepted code output: False
Expected output: True
 
sample input: s='zazazr'
accepted code output: False
Expected output: True

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission Accepted link you submitted led to the observed result.


Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by sayedgamal99** [comment]
Thanks for your time, 
Here the submission link you requested:
https://leetcode.com/submissions/detail/1129046628/

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
