### ISSUE TITLE
题目1080提交出现内部错误

### ISSUE THREAD

**Issue by djh-sudo** [LeetCode-Feedback/LeetCode-Feedback#18938]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

### LeetCode 用户名
hac

### 问题号码、标题和链接

1080. 根到叶路径上的不足节点
https://leetcode.cn/problems/insufficient-nodes-in-root-to-leaf-paths/description/

### Bug 类型
- [ ] 问题描述
- [ ] 示例
- [ ] 问题限制
- [ ] 问题提示
- [ ] 不正确或缺少“相关标签”
- [ ] 不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*
- [ ] 缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*
- [ ] 力扣官方题解
- [ ] 编程语言支持
- [x] 内部错误

### 描述
提交的代码出现内部错误。

### 你使用的语言
C++

### 你提交或者运行的代码

```
class Solution {
 public:
  TreeNode* sufficientSubset(TreeNode* root, int limit) {
    limit -= root->val; 
    if (!root->left && !root->right) return limit > 0 ? nullptr : root;
    if (root->left) root->left = sufficientSubset(root->left, limit);
    if (root->right) root->right = sufficientSubset(root->right, limit);
    return (root->left || root->right) ? root : nullptr;
  }
};
```

### 期望行为
无

### 屏幕截图
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/66478183/03e862ba-b2a2-4fce-aebf-7e6732945135)

### 额外的上下文
无

**Comment by SeltyL** [comment]
我也遇到了同样的情况 试了好多题都是这样 不管是自己写的代码还是官解都是内部错误
