### ISSUE TITLE
1155. Number of Dice Rolls With Target Sum - Fix TLE Test Case In Examples

### ISSUE THREAD

**Issue by RobertSkonieczny** [LeetCode-Feedback/LeetCode-Feedback#18932]
### Problem number, title, and link
[1155. Number of Dice Rolls With Target Sum](https://leetcode.com/problems/number-of-dice-rolls-with-target-sum/)

### Description of the bug
In the test cases we give a large test case for the initial run that will time out. Which is fine because this is a DP problem.
However since the large test case in the example questions if you brute force you can't see that your first two test cases passed.

I propose two possible fixes.

Current Test Case:
Example 3:
Input: n = 30, k = 30, target = 500
Output: 222616187
Explanation: The answer must be returned modulo 109 + 7.

Smaller test case that can run with brute force.
Input n = 3 | k = 9 | target = 15
Expected: 61

There should be one or 2 situations here.
1.) Give a smaller test case and move this 3rd test case behind the scenes.
2.) Keep the large test case, but show that example 1 and 2 pass, but example 3 TLEs.

### Code used for Submit/Run operation
Brute Force
```java
class Solution {
    private int k;
    private int target;
    public int numRollsToTarget(int n, int k, int target) {
        this.k = k;
        this.target = target;
        for (int[] row : memo) Arrays.fill(row, -1);

        return f(n, 0, 0);
    }

    public int f(int n, int rolled, int sum) {
        if (sum > target) {
            return 0;
        }
        
        if (rolled >= n) {
            return sum == target ? 1 : 0;
        }

        int ways = 0;

        for (int i = 1;i <= k;i++) {
            ways += f(n, rolled+1, sum + i);
            ways %= 1000000007;
        }

        return ways;
    }
}
```

Top Down DP:
```java
class Solution {
    private int[][] memo;
    private int k;
    private int target;
    public int numRollsToTarget(int n, int k, int target) {
        this.k = k;
        this.target = target;
        this.memo = new int[n+1][target+1];
        for (int[] row : memo) Arrays.fill(row, -1);

        return dp(n, 0, 0);
    }

    public int dp(int n, int rolled, int sum) {
        if (sum > target) {
            return 0;
        }
        
        if (rolled >= n) {
            return sum == target ? 1 : 0;
        }

        if (memo[rolled][sum] != -1) {
            return memo[rolled][sum];
        }
        
        int ways = 0;

        for (int i = 1;i <= k;i++) {
            ways += dp(n, rolled+1, sum + i);
            ways %= 1000000007;
        }

        return memo[rolled][sum] = ways;
    }
}
```

### Expected behavior
All cases should pass in the example if brute force is used / show which ones pass with brute force and show which one TLEs.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
