### ISSUE TITLE
Wrong constraints for the question.

### ISSUE THREAD

**Issue by AwesomeAsmit007** [LeetCode-Feedback/LeetCode-Feedback#18947]
### LeetCode Username
asmitpapney

### Problem number, title, and link
1052. grumpy-bookstore-owner: https://leetcode.com/problems/grumpy-bookstore-owner/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ Yes] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
In the description, it is mentioned that `0 <= customers[i] <= 1000`, but the test cases takes input of more than 10004

### Language used for code
C++

### Code used for Submit/Run operation

```
class Solution {
public:
    
    vector<int> Prefix;
    
    int t[100004][2] ;
    
    int getPrefixSum(int l, int r){
        r = min<int>(r,Prefix.size()-1);
        if(l==0) return Prefix[r] ;
        return Prefix[r]-Prefix[l-1] ;
    }
    
    int Solve(vector<int>&A, vector<int>&G, int min, int i, bool used){
        if(i>=A.size()) return 0 ;
        
        if(t[i][used]!=-1)
            return t[i][used] ;
        
        if(G[i]==0) return t[i][used] = A[i] + Solve(A,G,min,i+1,used) ;
        
        if(!used)
            return t[i][used] = max(getPrefixSum(i,i+min-1) + Solve(A,G,min,i+min,true), Solve(A,G,min,i+1,used)) ;
        
        return t[i][used] = Solve(A,G,min,i+1,used) ;
    }
    
    int maxSatisfied(vector<int>& customers, vector<int>& grumpy, int minutes) {
        Prefix.resize(grumpy.size(),0) ;
        int sum = 0 ;
        for(int i=0; i<customers.size(); i++){
            sum+=customers[i] ;
            Prefix[i] = sum ;
        }
        memset(t,-1,sizeof(t)) ;
        return Solve(customers,grumpy,minutes,0,false) ;
    }
};
```

### Expected behavior
The expected behavior would be that in constraints it should clearly mention the size of the array correctly.

### Screenshots
<img width="495" alt="Screenshot 2023-12-27 at 9 03 10 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/111046066/6ee3ed46-bfaf-4e38-88e5-058c0d51d084">

<img width="1327" alt="Screenshot 2023-12-27 at 9 03 44 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/111046066/58b78a00-d0af-47fe-9b06-e6316490e813">

**Comment by stormsunshine** [comment]
Are you talking about the range of the elements in the array or the length of the array?
