### ISSUE TITLE
Mistake in 1578. Minimum Time to Make Rope Colorful

### ISSUE THREAD

**Issue by Hr1t1k** [LeetCode-Feedback/LeetCode-Feedback#18941]
### LeetCode Username

Hritik__k

### Problem number, title, and link

[1578. Minimum Time to Make Rope Colorful](https://leetcode.com/problems/minimum-time-to-make-rope-colorful/)

### Category of the bug
- [ ] Problem description
-  Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

In the above mentioned problem , in example 3's explanation there is a small spelling mistake , "Bob will remove the ballons" here it will be balloons instead of ballons

### Screenshots

![lc mistake 27-12-2023](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/52287344/4f2a9f86-737a-4d16-99ba-1c6dee3e2927)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team

**Comment by LC-Pam** [comment]
Hi there, the 100 Leetcoins were deducted from this issue due to we found you submitted the same ticket on Zendesk Ticket #225978, the reward was duplicated for the same issue.
