### ISSUE TITLE
Wrong validation - 987. Vertical Order Traversal of a Binary Tree

### ISSUE THREAD

**Issue by jphegde** [LeetCode-Feedback/LeetCode-Feedback#1894]
#### Your LeetCode username

user6519

#### Category of the bug
- [x] Question -> Marking 'Wrong Answer' for a valid output
- [ ] Solution
- [ ] Language

#### Description of the bug

Correct output is wrongly marked as incorrect making the submission
wrong.

#### Code you used for Submit/Run operation

```
// Vertical Order Traversal of a Binary Tree
```
class Solution {
public:
    vector<vector<int>> verticalTraversal(TreeNode* root) {
        vector<vector<int>> res;
        map<int, vector<int>> mapping;
        queue<pair<int, TreeNode*>> q;
        int dist = 0;
        
        if(root == nullptr)
            return res;
        
        q.push(make_pair(dist, root));
        while(!q.empty()) {
            queue<pair<int, TreeNode*>> newq;
            while(!q.empty()) {
                auto item = q.front();
                q.pop();
                vector<int> temp;
                if(mapping.find(item.first) != mapping.end())
                    temp = mapping[item.first];
                temp.push_back(item.second->val);
                mapping[item.first] = temp;
                
                if(item.second->left)
                    newq.push(make_pair(item.first-1, item.second->left));
                if(item.second->right)
                    newq.push(make_pair(item.first+1, item.second->right));
            }
            q = newq;
        }
        
        for(auto it = mapping.begin(); it != mapping.end(); it++)
            res.push_back(it->second);
        
        return res;
    }
};
```

#### Language used for code
<!-- C++ -->
C++

#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->
The output consists of 2D integer vector. The position of one of the integers
in one of the vectors is flipped. I don't think this behaviour is wrong and flipping
of same position integers shouldn't matter.


#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->
![image](https://user-images.githubusercontent.com/9396281/103927594-9ab14e00-5140-11eb-8da0-8b5f60e9663e.png)



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by lc-kay** [comment]
@jphegde The expected output is correct. The question says if 2 nodes are in the same positions sort it by the node values and not the order in which they appear. Thank you for your time.
