### ISSUE TITLE
Mistake in Example of 1578. Minimum Time to Make Rope Colorful

### ISSUE THREAD

**Issue by Hr1t1k** [LeetCode-Feedback/LeetCode-Feedback#18942]
### LeetCode Username

Hritik__k

### Problem number, title, and link

[1578. Minimum Time to Make Rope Colorful](https://leetcode.com/problems/minimum-time-to-make-rope-colorful/)

### Category of the bug
- [ ] Problem description
-  Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

In the above mentioned problem , in example 3's explanation there is a small spelling mistake , "Each ballon takes 1 second to remove." here it will be balloons instead of ballons

### Screenshots

![lc mistake 27-12-2023(2)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/52287344/aefc0df3-0d60-41b7-a7c9-80ce604c033d)

**Comment by LC-Pam** [comment]
Duplicated Issue
