### ISSUE TITLE
账号密码无法登录，必须用手机验证码，服了！ 

### ISSUE THREAD

**Issue by STATICHIT** [LeetCode-Feedback/LeetCode-Feedback#18959]
### LeetCode 用户名
Zaza

### 问题
账号之前绑定的手机号已经换掉了，现在用账号密码登陆必须使用手机号验证导致无法登录。
急！！！！现在账号登陆不上！！！

### 期望行为
帮忙换绑手机号找回账号

### 屏幕截图
我的账号：
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/108850075/fff6acb0-f83b-453b-ab4f-fa6a82837a9c)

**Comment by liyuzhu-lc** [comment]
您好，

感谢您的反馈，可以帮您重置手机号，根据您反馈的情况，需要您提供一下信息至邮箱：liyuzhu@leetcode.cn
我们需要验证当前帐号为您本人使用，请您提供以下信息至我们：
-您的常用邮箱：
- 需要重置手机号的力扣账号：
- 需要重置帐号绑定的手机号（如有）：
- 常用登录地址：（省市）
- 常用登录设备系统：
- 常用登录浏览器：

在收到您的回复后，我们会提交至相关部门进行核实并进行后，给您发重置邮件，还请注意查收您的邮箱。


Best Regards,
Leetcode | Support Team
