### ISSUE TITLE
Missing Test Case - 347. Top K Frequent Elements

### ISSUE THREAD

**Issue by afendyKai** [LeetCode-Feedback/LeetCode-Feedback#18952]
### LeetCode Username
afendyKai

### Problem number, title, and link
347. Top K Frequent Elements https://leetcode.com/problems/top-k-frequent-elements/

### Category of the bug
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug
In the Top K Frequent Elements, I mistaken the K as the frequency of the number in the array.
For example, if there is an input array of num [1,1,1,2,2,3] and K = 2
My code would group the number together in Dictionary (HashMap) whereby key is number and value is frequency.
1 = 3
2 = 2
3 = 1
Then I would create a List to get the frequency that is more or equal to K.
This is consider correct based on the test case given.

However, when i created a new test case, whereby input array of num [1,1,1,2,2,3] and K = 3,
The test case is failed, as the K is refer to the top most frequent number.

I just think there should be a new test case( input array of num [1,1,1,2,2,3] and K = 3), so that my code or other people that have similar code like mine would not be passed.

### Language used for code
C# 

### Code used for Submit/Run operation
```
public class Solution {
    public int[] TopKFrequent(int[] nums, int k) {
        //Declare Hashmap whereby
        //Key = int
        //value = frequency
        Dictionary<int, int> hashMap = new Dictionary<int, int>();

        //Populate the hashmap
        foreach(int n in nums){
            if(hashMap.ContainsKey(n)){
                hashMap[n] = hashMap[n] + 1;
            }else{
                hashMap.Add(n, 1);
            }
        }
    
        //Declare a list to populate it where 
        //Frequency is equal or larger than K
        List<int> numbersList = new List<int>();
        foreach(var data in hashMap){
            if(data.Value >= k){
                numbersList.Add(data.Key);
            }
        }
        
        //Convert list into array
        int[] numbersArray = numbersList.ToArray();

        //Return the result
        return numbersArray;
    }
}
```

### Expected behavior
Additional test case should be added by LeetCode Admin (input array of num [1,1,1,2,2,3] and K = 3), so that code like mine should be failed and not passed based on the given test case.

### Screenshots
![Screenshot 2023-12-28 112836](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/154729350/96bd044d-66ba-4c66-8d11-471069f74a0a)
Sample screenshot of added new custom test case to failed the written code.

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
