### ISSUE TITLE
Missing Test Case - 3. Longest Substring Without Repeating Characters

### ISSUE THREAD

**Issue by anvesh1601** [LeetCode-Feedback/LeetCode-Feedback#1895]
#### Your LeetCode username

anveshniranjana

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@anvesh1601 Please provide the code and the issue you are reporting. Thank you!

**Comment by lc-kay** [comment]
Hi @anvesh1601 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
