### ISSUE TITLE
Missing Test Case - 80. Remove Duplicates from Sorted Array II

### ISSUE THREAD

**Issue by manatax** [LeetCode-Feedback/LeetCode-Feedback#18950]
### LeetCode Username
Manatax

### Problem number, title, and link
80 Remove Duplicates from Sorted Array II https://leetcode.com/problems/remove-duplicates-from-sorted-array-ii/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
Adding "[1]" as a test case would prevent solutions starting from 2 that don't account for the lower edge cases

### Language used for code
Python

### Code used for Submit/Run operation
```
class Solution(object):
    def removeDuplicates(self, nums):
        """
        :type nums: List[int]
        :rtype: int
        """
        k = 2
        for x in nums[2:]:
            if x != nums[k - 2]:
                nums[k] = x
                k += 1
        return k
```

### Expected behavior
Solution should be 1, but function will return 2, and still succeed

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

[1] already exists. 

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
