### ISSUE TITLE
BFS Template is blank

### ISSUE THREAD

**Issue by Augustine-** [LeetCode-Feedback/LeetCode-Feedback#18954]
https://leetcode.com/explore/learn/card/queue-stack/231/practical-application-queue/1372/

Go here. Templates are blank.

**Comment by akilesh96** [comment]
@Augustine- duplicate issue of https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/18720

**Comment by LC-Pam** [comment]
duplicate issue of https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/18720
