### ISSUE TITLE
Doubly Linked Lists Chapters: Out of the 5, 2 are not loading.

### ISSUE THREAD

**Issue by ShailikaS** [LeetCode-Feedback/LeetCode-Feedback#18953]
### LeetCode Username
shailika

### Problem number, title, and link
Learn Section,  
Linked List Chapter 4th Doubly Linked Lists - https://leetcode.com/explore/learn/card/linked-list/210/doubly-linked-list/1291/

### Description of the bug

Not able to see Doubly Linked Lists Chapters: Out of the 5, 2 are not loading.

### Screenshots

<img width="190" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/107252411/84230f3b-0b18-419a-9087-11ec4245ccec">

<img width="839" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/107252411/6c9e2db4-226d-4bf1-ac7f-82730df46cd9">

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ x] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. They initially appeared not to load for us, just like in the screenshot, but it load after you read or click through the other articles in the chapter.

Click or read through the first three articles, and then the last two will load.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
