### ISSUE TITLE
Missing Test Case - 3. Longest Substring Without Repeating Characters

### ISSUE THREAD

**Issue by anvesh1601** [LeetCode-Feedback/LeetCode-Feedback#1896]
#### Your LeetCode username

anveshniranjana

#### Category of the bug
- [ ] Question
- [  ]Solution
- [  ] Language

#### Description of the bug

->in the costume test case, I am getting the correct answer .but in normal cases I am getting the wrong answer.

#### Code you used for Submit/Run operation

```
//Longest Substring Without repetetion

int lengthOfLongestSubstring(char  s[]){
    
int max=0,m=0,count=0,i,j,len;
    len=strlen(s);
    char c[1000]="";
    char a[1000];
    if(len==0){
        return 0;
    }
    for(i=0;i<=len;i++){
        count=1;
        m=0;
        strcpy(a,c);
       
         a[m]=s[i];
        for(j=i+1;j<=len;j++){
            
            if(strchr(a,s[j])==NULL){
                m++;
                a[m]=s[j];
                
                count++;
                
                
            }else{
                break;
            }
        }

    if(count>=max){
        max=count;
    }
    }
    
    return max;
}
```

#### Expected behavior

for the same input(dyow) in the costume testcase I am getting the correct answer which is 4 but in the normal testcase I am getting the wrong answer which is 3. 

#### Screenshots

![Screenshot (5)](https://user-images.githubusercontent.com/66896881/103928847-66ab3e00-50ea-11eb-822b-ea213a0c4cf0.png)

**Comment by lc-kay** [comment]
Hi @anvesh1601 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
