### ISSUE TITLE
1321. Restaurant Growth

### ISSUE THREAD

**Issue by KMerchant** [LeetCode-Feedback/LeetCode-Feedback#18969]
### LeetCode Username

Tahirzade

### Problem number, title, and link

1321. Restaurant Growth
https://leetcode.com/problems/restaurant-growth/?envType=study-plan-v2&envId=top-sql-50

### Category of the bug
- [ X] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ X] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

"You are the restaurant owner and you want to analyze a possible expansion (there will be at least one customer every day)."
The description given above is not followed in the test cases. There are test cases that does not have customer for every day. Test case 14 causes problem with my solution because of this issue.

### Language used for code

Oracle SQL

### Code used for Submit/Run operation

```
/* Write your PL/SQL query statement below */
select visited_on, amount, average_amount
from
(
    select to_char(visited_on, 'yyyy-mm-dd') as visited_on, amount, average_amount, row_num
    from
    (
        select visited_on,
                row_number() over(order by visited_on) as row_num,
                round(sum(amount) over(order by visited_on rows between 6 preceding and current row), 2) as amount,
                round(sum(amount) over(order by visited_on rows between 6 preceding and current row)/7, 2) as average_amount
        from
        (
            select visited_on, sum(amount) as amount
            from customer
            group by visited_on
            order by visited_on;
        )
    )
)
where row_num>6;
```

### Expected behavior

Test case have does not have customers for every day as opposed to the description of the problem.

### Screenshots

<img width="831" alt="Screenshot 2023-12-29 at 16 34 54" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/25864136/7911c844-6261-4da4-8e9d-635be5c3ac96">
<img width="831" alt="Screenshot 2023-12-29 at 16 35 02" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/25864136/ffdc3b5f-88f7-4d1e-b42a-65f70f28367f">

### Additional context

Even if I adjust the solution to cover test case 14, test case 2 causes problem.

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team

**Comment by osamakawish** [comment]
@LC-Pam But this is an issue with the test case. Here's the raw file of the test case:

```
| customer_id | name    | visited_on | amount |
| ----------- | ------- | ---------- | ------ |
| 1           | Jhon    | 2019-01-01 | 100    |
| 2           | Daniel  | 2019-01-12 | 110    |
| 3           | Jade    | 2019-01-03 | 120    |
| 4           | Khaled  | 2019-01-04 | 130    |
| 5           | Winston | 2019-01-05 | 110    |
| 6           | Elvis   | 2019-01-06 | 140    |
| 7           | Anna    | 2019-01-07 | 150    |
| 8           | Maria   | 2019-01-08 | 80     |
| 9           | Jaze    | 2019-01-09 | 110    |
| 1           | Jhon    | 2019-01-10 | 130    |
| 3           | Jade    | 2019-01-10 | 150    |
```

I reposted this issue, and the date 2019-01-02 is clearly missing, contrary to the problem description.
