### ISSUE TITLE
Missing Test Case - 45. Jump Game II

### ISSUE THREAD

**Issue by ThanoS-max** [LeetCode-Feedback/LeetCode-Feedback#1897]
#### Category of the bug
- [ ] Question
- [yes ] Solution
- [ ] Language

#### Description of the bug

Can we use Kadane's Algo to solve this particular question?

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@ThanoS-max Please raise this question in the discuss tab. Since this is not a valid content issue, I will close this ticket. Thank you for understanding.
