### ISSUE TITLE
Missing Test Case - 1897. Redistribute Characters to Make All Strings Equal

### ISSUE THREAD

**Issue by Sairajepawar** [LeetCode-Feedback/LeetCode-Feedback#18981]
### LeetCode Username
sairaje994

### Problem number, title, and link
[1897. Redistribute Characters to Make All Strings Equal](https://leetcode.com/problems/redistribute-characters-to-make-all-strings-equal/)

### Category of the bug
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)

### Description of the bug
The question does not specify whether the characters in the strings of the vector `words` are consistently lowercase, and it also does not provide information about the possible presence of special characters in the strings.

### Language used for code
C++

### Code used for Submit/Run operation

```
class Solution {
public:
    bool makeEqual(vector<string>& words) {
        int t[26];
        memset(t,0,sizeof(t));
        string final = "";
        for(auto it:words){
            final+=it;
        }
        for(auto it:final){
            int temp = it-'a';
            t[temp]++;
        }
        int len = words.size();
        for(int i=0;i<26;i++){
            if(t[i]%len){
                return false;
            }
        }
        return true;
    }
};
```

### Expected behavior
The code assumes the presence of only lowercase characters in the strings of the vector 'words.' It may not function correctly if the strings contain uppercase characters or special symbols. The question, however, does not explicitly mention that only lowercase characters are allowed.

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/97350488/6e587c6a-f4c4-4550-a707-3547da726da4)

Submission Link :- https://leetcode.com/submissions/detail/1131910461/

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
