### ISSUE TITLE
199. Binary Tree Right Side View -> unable to escape from while loop

### ISSUE THREAD

**Issue by oscaroht** [LeetCode-Feedback/LeetCode-Feedback#18989]
### LeetCode Username
OscarHT

### Problem number, title, and link
[199. Binary Tree Right Side View](https://leetcode.com/problems/binary-tree-right-side-view/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [x] Programming language support

### Description of the bug
--Interpreter does not stop the while loop at the ending condition
--Not returned when return is called

### Language used for code
Python

### Code used for Submit/Run operation

```
class Solution:
    def rightSideView(self, root: Optional[TreeNode]) -> List[int]:
        # bfs and take the right most from the queue
        que = [root]
        res = []
        while len(que)>0:
            print(f"Que {[q.val for q in que]}")
            res.append(que[-1].val)
            for _ in range(len(que)):
                n = que.pop(0)
                print(f"Poped {n.val} from Que {[q.val for q in que]}")
                if n.left:
                    print(f"Add {n.left.val} to que")
                    que.append(n.left)
                if n.right:
                    print(f"Add {n.right.val} to que")
                    que.append(n.right)
            # try to force it to return
            # should not be necessary but indicates the problem beautifully
            print(len(que))  # show that len(que)==0
            if len(que) == 0:
                print("SHOULD RETURN")
                return res
        return res
```

### Expected behavior
Should return when que is empty. Instead continues twice and throws Runtime Error.

Que [1]
Poped 1 from Que []
Add 2 to que
Add 3 to que
2
Que [2, 3]
Poped 2 from Que [3]
Add 5 to que
Poped 3 from Que [5]
Add 4 to que
2
Que [5, 4]
Poped 5 from Que [4]
Poped 4 from Que []
0
SHOULD RETURN
Que [1]
Poped 1 from Que []
Add 3 to que
1
Que [3]
Poped 3 from Que []
0
SHOULD RETURN

Runtime Error
AttributeError: 'NoneType' object has no attribute 'val'
                  ^^^^^
    print(f"Que {[q.val for q in que]}")
Line 13 in <listcomp> (Solution.py)
                 ^^^^^^^^^^^^^^^^^^^^
    print(f"Que {[q.val for q in que]}")
Line 13 in rightSideView (Solution.py)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ret = Solution().rightSideView(param_1)
Line 50 in _driver (Solution.py)
    _driver()
Line 61 in <module> (Solution.py)

### Additional context
On my local machine I cannot reproduce the issue with the same code. Leads me to think this is a problem with the leetcode interpreter. Feel free to contact me if you need any help.

**Comment by LC-Pam** [comment]
Thank you for getting back to us! Regrettably, troubleshooting the variance between your local Integrated Development Environment (IDE) and the LeetCode environment poses a challenge for us.

In such cases, we recommend raising this issue as a discussion post in the problem's discussion section. This allows you to tap into the collective knowledge and experiences of our user community. Many users may have encountered similar challenges and could offer insights or solutions that can be valuable in resolving the discrepancy.

At LeetCode, we foster a collaborative learning environment, and we believe in the power of users to help each other to enhance their learning experience. Debugging and learning from the process are integral parts of the coding journey, and the community's diverse perspectives can be immensely beneficial.

We appreciate your understanding, and if you have any more questions or need further assistance, please feel free to let us know. Your time and support are highly valued.

Best regards,
The LeetCode Team
