### ISSUE TITLE
Missing Test Case - 128. Longest Consecutive Sequence

### ISSUE THREAD

**Issue by MGY7** [LeetCode-Feedback/LeetCode-Feedback#18980]
### Problem number, title, and link
128. Longest Consecutive Sequence https://leetcode.com/problems/longest-consecutive-sequence/description/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
-  Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

As per the problem description, we should be able to solve the problem in O(n) time; also in the Constraints section, we see that the values of the given array, i.e. nums[I], can be between -10^9 to 10^9. This means that we should not be able to use sort techniques like count sort or merge sort etc, because merge sort would make the time complexity as O(n(Log n)) and count sort would make the space complexity very high because of the possible range of nums[i].

### Code used for Submit/Run operation

```
public int longestConsecutive(int[] nums) {
    int result = 0;
        if (nums.length > 0) {
            if (nums.length < 1000) {
                Arrays.sort(nums);
                int current = 0;
                for (int i = 1; i < nums.length; i++) {
                    if (nums[i] != nums[i - 1]) {
                        if (nums[i] - nums[i - 1] == 1) {
                            current++;
                        } else {
                            if (current + 1 > result) {
                                result = current + 1;
                            }
                            current = 0;
                        }
                    }
                }
                if (current + 1 > result) {
                    result = current + 1;
                }
            } else {
                int min = Integer.MAX_VALUE;
                int max = Integer.MIN_VALUE;
                for (int num : nums) {
                    if (num > max) {
                        max = num;
                    }
                    if (num < min) {
                        min = num;
                    }
                }
                byte[] bits = new byte[max - min + 1];
                for (int num : nums) {
                    bits[num - min] = 1;
                }
                int current = 0;
                for (byte bit : bits) {
                    if (bit > 0) {
                        current++;
                    } else {
                        if (current > result) {
                            result = current;
                        }
                        current = 0;
                    }
                }
                if (current > result) {
                    result = current;
                }
            }
        }
        return result;
    }
// Paste your code here. Don't remove ``` given
// above and below the code.
```

### Expected behavior

For a testcase where length of the given array is sufficiently large (near to 10^5) and the values of the array are also spread apart as much as possible (from -10^9 to 10^9), the above program must not be acceptable due to high space complexity

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/44345154/829a2a5f-92ca-4c84-96ae-8a34e7ef6933)

### Additional context

The above code should not be acceptable for test cases where length of the given array is as high as possible and the values of the array are spread apart as much as possible.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
