### ISSUE TITLE
Wrong testcase in problem no.131 and testcase no 14

### ISSUE THREAD

**Issue by thetx** [LeetCode-Feedback/LeetCode-Feedback#18984]
### Category of the bug
- [ ] Incorrect test Case *(Expected and My output are same)*

### Description of the bug
Testcase no 14
The expected answer and my output is exactly the same just the order is different but it counts it as an incorrect output.
Check the screenshot attached below

### Language used for code
Java

### Code used for Submit/Run operation
```
class Solution {
    public List<List<String>> partition(String s) {
        List<List<String>> ans =  new ArrayList<List<String>>();
        recFun(s, ans,new ArrayList<String>());
        return ans;
    }

    static void recFun(String str,List<List<String>> ans,List<String> route){
        int len = str.length();
        if(len == 0){
            List<String> newList = new ArrayList<String>(route);
            ans.add(newList);
            return ;
        }

        for(int i=1;i<len;i++){
            String str1 = str.substring(0,i);
            String str2 = str.substring(i);
            if(isPalim(str1)){
                route.add(str1);
                recFun(str2, ans, route);
                route.remove(str1);
            }
        }

        if(isPalim(str)){
            route.add(str);
            recFun("", ans, route);
            route.remove(str);
        }
        return;
    }

    static boolean isPalim(String str){
        int len = str.length();
        for(int i=0;i<len;i++){
            if(str.charAt(i) != str.charAt(len-i-1))
                return false;
        }
        return true;
    }
}
```

### Expected behavior
The answer should have been accepted for testcase number 14.

### ScreenShot
![Screenshot 2023-12-30 111007](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/99096693/866ece3f-87f2-4ad9-8947-06e96f73bc05)

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
