### ISSUE TITLE
Invalid Test Case - 879. Profitable Schemes

### ISSUE THREAD

**Issue by Madhour** [LeetCode-Feedback/LeetCode-Feedback#1899]
#### Your LeetCode username
madhour

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Code fails on the following test:

Input:
64
0
[80, 40]
[88, 88]
Output:
1
Expected:
2

#### Code you used for Submit/Run operation

```
class Solution(object):
    def profitableSchemes(self, n, minProfit, group, profit):
        
        combinations = self.accComb(profit)
        schemes = 0
        
        for comb in combinations:
            membersNeeded = [group[x] for x in comb]
            minProf = [profit[x] for x in comb]
            
            if sum(minProf) >= minProfit and sum(membersNeeded) <= n:
                schemes += 1
        
        return schemes
        
    def possibleCombination(self, i, profit, combis):
        if i == len(profit):
            return combis
        else:
            if i == 0:
                combis.append([profit[i]])
            base = [y for y in profit[:i+1]]

            for j in range(i+1, len(profit)):
                #print(j)
                base.append(profit[j])
                combis.append(base[:])
                base.pop()
        return self.possibleCombination(i+1, profit, combis)        

    def accComb(self, profit):
        indices = [x for x in range(len(profit))]
        accCombi = []
        for i in range(len(indices)):
            [accCombi.append(combi) for combi in self.possibleCombination(0, indices[i:], [])]
        return accCombi
```

#### Language used for code
Python

#### Expected behavior

Since there is only one possible scheme the output seems to be correct, however the expected value is 2 . There aren't enough members for [0] and [0,1] as both schemes need more than 80 gang members. So that leaves only [1] which yields enough profit and needs only 40 members.

#### Additional context

Code itself isn't complete yet. But regardless of the code, the expected value on the above test is confusing.

**Comment by lc-kay** [comment]
@Madhour The expected output is correct. I'd recommend raising your question in the discuss tab or checking out the solution article to better understand the question. Thank you for your time!
