### ISSUE TITLE
1304. Find N Unique Integers Sum up to Zero: Wrong Test Cases

### ISSUE THREAD

**Issue by ZvezdocheTag** [LeetCode-Feedback/LeetCode-Feedback#19]
**What kind of the bug**
- [x] problem
- [ ] solution

**Describe the bug**
I suppose problem with current test cases, when in my output inside array last index ended with positive number test is fail, but corresponds to the expected final output.

**The code you submit/run**
```js
/**
 * @param {number} n
 * @return {number[]}
 */
var sumZero = function(n) {
  let total = 0

  let gen = Array.from({ length: n }, (_, idx) => {
    if (idx === n - 1) {
      return -total
    }
    let firstRandom = getRandomArbitrary(-10, 10)
    let toFloor = Math.floor(firstRandom)
    total += toFloor 

    return toFloor
  })

  return gen
};
function getRandomArbitrary (min, max) {
  return Math.random() * (max - min) + min
}
```

**Expected behavior**
Test cases should be passed with current solution.

**Screenshots**
<img width="1433" alt="Screenshot 2020-03-07 at 17 27 24" src="https://user-images.githubusercontent.com/10656893/76145593-bb7dc280-609b-11ea-9b2d-dce8302f6f1e.png">

**Additional context**
Example from leetcode with failed test:

| Input  |  7 |
|---|---|
| Output  | [5,-2,-8,-3,-8,-5,21] |
|  Expected |  [-3,0,-6,-2,5,4,2] |

**Comment by CooperCooperCooper** [comment]
Hi @ZvezdocheTag,
Thank you for your patience. The problem statement asks to return **unique integers**; but on the screenshot, the number "5" was returned twice. Please review the statement again and revise your code accordingly. We appreciate your support.

**Comment by ZvezdocheTag** [comment]
Hi, thanks for your answer but, `5 !== -5`, as I know.
