### ISSUE TITLE
Testing "Jumping game" against empty list gives no "expected" answer

### ISSUE THREAD

**Issue by AnthonyMikh** [LeetCode-Feedback/LeetCode-Feedback#190]
**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
Testing [Jump game](https://leetcode.com/explore/featured/card/30-day-leetcoding-challenge/531/week-4/3310/) problem against empty test case (`[]`) gives no "expected" answer at all.

**what language is your code written in**
Irrelevant, the issue can be reproduced in _all_ supported languages.

**The code you submit/run**
```rust
// Any similar code will work as well
impl Solution {
    pub fn can_jump(nums: Vec<i32>) -> bool {
        false
    }
}
```

**Expected behavior**
Running a test code results in giving either `true` or `false`, or at least something.

**Screenshots**
![weird_answer](https://user-images.githubusercontent.com/19252795/80285773-e2698400-872f-11ea-8a7a-8ab904946006.png)

**Comment by CooperCooperCooper** [comment]
Hi @AnthonyMikh,
Thank you for reaching out to us. I've relayed your feedback to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @AnthonyMikh,
Thank you for your time. We've updated the problem based on your feedback. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user verification, and this issue to claim the valid contribution reward.

**Comment by CooperCooperCooper** [comment]
Hi @AnthonyMikh,
We appreciate your support. Just a gentle reminder that the section "what language is your code written in" helps our team to target the issue from shared code quickly, so we can spend less time on triaging the problems to the right person. We would really appreciate it if you would provide the code language under that section in the future :)
