### ISSUE TITLE
Missing Test Case - 11. Container With Most Water

### ISSUE THREAD

**Issue by abhinavsood2002** [LeetCode-Feedback/LeetCode-Feedback#19000]
### LeetCode Username
AS2I

### Problem number, title, and link
11. Container With Most Water (https://leetcode.com/problems/container-with-most-water/)

### Category of the bug
- Problem constraints
- Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug
Most (that I have checked) top solutions on leetcode for this problem do not consider the case when towers are of equal height (even the test cases don't) even though there is no such restriction in the question.
As an example, For test case [10, 10, 100] expected output is 20 instead of the correct 100 

### Language used for code
Python3 

### Code used for Submit/Run operation
```
class Solution:
    def maxArea(self, height: List[int]) -> int:
        left = 0
        right = len(height) - 1
        maxArea = 0

        while left < right:
            currentArea = min(height[left], height[right]) * (right - left)
            maxArea = max(maxArea, currentArea)

            if height[left] < height[right]:
                left += 1
            else:
                right -= 1

        return maxArea
```

### Expected behavior
For test case [10, 10, 100] expected output is 20 instead of the correct 100

### Additional context
Either add a restriction of equal heights being prohibited, or add new test cases for outliers which would deem most current solutions incorrect.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
