### ISSUE TITLE
[Missing Test Case] 2742. Painting the Walls

### ISSUE THREAD

**Issue by ITSJKS** [LeetCode-Feedback/LeetCode-Feedback#19009]
### LeetCode Username

jk_s

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Some wrong solutions are passing due to incomplete testcases. Testcases only cover the case where cost array have values less than size of the cost array.

### Language used for code

C++

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
class Solution {
public:
    int dp[510][1020];
    int solve(int cnt,int idx, vector <int> &cost, vector <int> &t){
        if(idx == cost.size()){
            if(cnt < 0) return 1e9;
            return 0;
        }
        int n = cost.size();
        if(cnt <-n || cnt > n) return 1e9;
        if(dp[idx][505+cnt]!=-1) return dp[idx][505+cnt];
        int c = 1e9;
        c = min(c,cost[idx] + solve(cnt+t[idx],idx+1,cost,t));
        c = min(c,solve(cnt-1,idx+1,cost,t));
        return dp[idx][505+cnt] = c;
    }
    int paintWalls(vector<int>& cost, vector<int>& t) {
        memset(dp,-1,sizeof dp);
        return solve(0,0,cost,t);
    }
};
```

### Expected behavior

Expected answer is 1 but my accepted code is giving 2.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/75828914/f09cb12e-11f0-45bf-8234-aef1743d57ca)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
