### ISSUE TITLE
Missing Test Case - 10033. Find Longest Special Substring That Occurs Thrice II

### ISSUE THREAD

**Issue by knockcat** [LeetCode-Feedback/LeetCode-Feedback#19004]
### LeetCode Username

knockcat

### Problem number, title, and link

2982. Find Longest Special Substring That Occurs Thrice II https://leetcode.com/problems/find-longest-special-substring-that-occurs-thrice-ii/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [. ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Missing Test Case

"aaaaaabaaaaaabaaaaaabaaaaaaa"

this is one of them I believe several such cases must be there for which my code will passed but it should not.

This is an example where the output should be wrong answer it displays the output as wrong but shows time limit exceed by passing all the cases by the compiler as this is one of the missing test case.
For the above test case even though on running it says wrong output but internally it will pass as no such test case is there for the problem.

The test case is as follows.
assuming I have continuous string of length 6 3 times but then a continuous string of 7 occurs then in my above code i was removing entries of 6 to prevent time limit exceed during contest as other wise the entries in map would be going to like
a - 1
a - 2
till n ( depend the length of continuous character)
and many entries will be there resulting in a time limit exceed.

for getting rid of this thing during contest i tend to remove prior entries if i find a new length greater than that,

for example.

I have for above test case in my map4 the entry should  be mp[{ a , 6 }] = 3
but as soon I found a better count that is 7 in this case i am removing my 6 entries so that in my map entries like mp[{ a , 1 }] , mp[{ a , 2} ] don't exist and code should doesn't encounter time limit exceed.
but than the above test case should fail because of my logic as i explained above but it passed fully and also accepted. I will add the screen shot.

### Language used for code

C++

### Code used for Submit/Run operation

```
class Solution {
public:
    int maximumLength(string str) {
        
        unordered_map<char, int> mp, mp2, mp3;
        
        map<pair<char, int>, int> mp4;
        
        int n = str.size();
        
        int ans = -1;
        
        for(int i = 0; i < n; ++i)
        {
            ++mp[str[i]];
            if(mp[str[i]] >= 3)
                ans = 1;
        }
        
        if(ans == -1)
            return ans;

        int cnt = 1;
        mp[str[0]] = 1;
        for(int i = 1; i < n; ++i)
        {
            if(str[i] == str[i-1])
            {
                ++cnt;
                // int al = mp[str[i]];
                mp2[str[i]] = max(mp2[str[i]], cnt);
                int have = mp2[str[i]];
                if(cnt < have)
                {
                    if(cnt == have-1)
                    {
                        mp3[str[i]] = max(mp3[str[i]], cnt);
                    }
                }
                
                if(mp4[{str[i], cnt-1}])
                    mp4.erase({str[i], cnt-1});
                ++mp4[{str[i], cnt}];
            }
            else
            {
                cnt = 1;
                mp2[str[i]] = max(mp2[str[i]], cnt);
            }
        }
        
        for(auto& [f, e] : mp2)
        {
            // cout<<f << ' '<<e<<endl;
            if(e >= 3)
            {
                // cout<<mp3[f]<<endl;
                if(mp3[f] == e-1)
                    ans = max(ans, e-1);
                else
                    ans = max(ans, e-2);
            }
        }
        
        for(auto& itr : mp4)
        {
            // cout<<itr.first.first << ' '<<itr.first.second<<' '<<itr.second<<endl;
            if(itr.second >= 3)
            {
                ans = max(ans, mp3[itr.first.first]);
            }
        }
        
        return ans;
    }
};
```

### Expected behavior

This part i already explained in the missing test case column but I am still pasting here the same.

"aaaaaabaaaaaabaaaaaabaaaaaaa"

this is one of them I believe several such cases must be there for which my code will passed but it should not.

This is an example where the output should be wrong answer it displays the output as wrong but shows time limit exceed by passing all the cases by the compiler as this is one of the missing test case.
For the above test case even though on running it says wrong output but internally it will pass as no such test case is there for the problem.

The test case is as follows.
assuming I have continuous string of length 6 3 times but then a continuous string of 7 occurs then in my above code i was removing entries of 6 to prevent time limit exceed during contest as other wise the entries in map would be going to like
a - 1
a - 2
till n ( depend the length of continuous character)
and many entries will be there resulting in a time limit exceed.

for getting rid of this thing during contest i tend to remove prior entries if i find a new length greater than that,

for example.

I have for above test case in my map4 the entry should  be mp[{ a , 6 }] = 3
but as soon I found a better count that is 7 in this case i am removing my 6 entries so that in my map entries like mp[{ a , 1 }] , mp[{ a , 2} ] don't exist and code should doesn't encounter time limit exceed.
but than the above test case should fail because of my logic as i explained above but it passed fully and also accepted. I will add the screen shot.

### Screenshots

The below is the screen shot where it fully passed the above code first
this is before i thought of the scenario where the code should be failing

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/85362504/e11c125c-1ff8-4da4-887d-1a17b3d4f4cb)

https://leetcode.com/submissions/detail/1132729206/

you can go through this and you will find the this passed all the testcase.

now i thought of the case "aaaaaabaaaaaabaaaaaabaaaaaaa" that this should not be passing according to my logic.

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/85362504/36c92efd-3285-4aa0-84d9-45983357fba6)

and as expected the compiler throw the wrong answer but i already have an accepted verdict so i tried submitting it again.

and then this happens,

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/85362504/70185885-f0fc-419b-96f0-8e8aaec698bf)

https://leetcode.com/submissions/detail/1132740969/

this is the submitted code as same as above

so here it showed me a time limit exceed but it still passed all the cases that is 902 as of now you can check in the above screen shot.

This made me clear that this is one of missing case and several such type of cases are there where the compiler will show us the accepted verdict and you can see at first it passed all the cases and later also it passed all cases but resulting in a time limit exceed that is this is a missing case.

I hope I was able to come out of a missing test case and the possibility of several cases of these types can give a accepted verdict and this i have explained above.

I feel this is one of such case which should not be giving accepted verdict though this problem was amazing and make me learn many thing and since i was solving this in contest so you can see several wrong answer and then it got accepted and also i was not able to make this submission during contest as I was still trying to find the solution and made just after 7-8 min and it got accepted and then i thing of possible scenario where it will fail.

### Additional context

I also wanted to be part of leetcode problem testers and creators and I wish I get a chance in future.
thankyou 
knockcat this side.

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
