### ISSUE TITLE
Wrong Test Case - 2513. Minimize the Maximum of Two Arrays

### ISSUE THREAD

**Issue by CodingArpan** [LeetCode-Feedback/LeetCode-Feedback#19010]
### LeetCode Username
codingarpan

### Problem number, title, and link
2513. Minimize the Maximum of Two Arrays

### Category of the bug
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### Description of the bug

Test Case : 
Input
divisor1 =
12
divisor2 =
3
uniqueCnt1 =
2
uniqueCnt2 =
10
--------------------------------
How can be maximum 14 it should be 17 ,i have written output of no. serialwise which are not divisible by divisior1 divisior2.
Input
divisor1 =
12
divisor2 =
3
uniqueCnt1 =
2
uniqueCnt2 =
10
Output
17
Expected
14
Stdout
divisior1=1 divisior1=2 for divisior2 4 for divisior2 5 for divisior2 7 for divisior2 8 for divisior2 10 for divisior2 11 for divisior2 13 for divisior2 14 for divisior2 16 for divisior2 17

### Language used for code
C Language

### Code used for Submit/Run operation

```
#include <stdio.h>
#include <stdlib.h>
 int *arr1, *arr2;
int minimizeSet(int divisor1, int divisor2, int uniqueCnt1, int uniqueCnt2) {
     arr1=(int *)malloc(uniqueCnt1 * sizeof(int));
     arr2=(int *)malloc(uniqueCnt2 * sizeof(int));
    int start =1;
    int cnt1=uniqueCnt1;
    int cnt2 = uniqueCnt2;
    while(1){
        printf("%d - num\n",start);
        if(start % divisor1 && cnt1){
            arr1[uniqueCnt1-cnt1]=start;
            printf("%d saved in arr1, index %d\n",arr1[uniqueCnt1-cnt1],uniqueCnt1-cnt1);
            cnt1--;
        }else if(start % divisor2 && cnt2){
            arr2[uniqueCnt2-cnt2]=start;
            printf("%d saved in arr2, index %d\n",arr2[uniqueCnt2-cnt2],uniqueCnt2-cnt2);
            cnt2--;
        }
        if(cnt1 == 0 && cnt2 == 0){
            break;
        }
        start++;
    }
    
printf("%d - return\n",start);
    return start;
}

int main() {
   
    int ans = minimizeSet(12,3,2,10);
    printf("Output %d", ans);

    return 0;
}
```

### Expected behavior
Expected: Output : 14
Correct Output : 17

### Screenshots
![Screenshot 2023-12-31 143733](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/89989646/f40cec43-aff9-4ee2-99e2-5eb368d42ab5)

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
