### ISSUE TITLE
Missing Test Case - 2982. Find Longest Special Substring That Occurs Thrice II

### ISSUE THREAD

**Issue by redscool** [LeetCode-Feedback/LeetCode-Feedback#19011]
### LeetCode Username
side_text

2982. Find Longest Special Substring That Occurs Thrice II 
https://leetcode.com/problems/find-longest-special-substring-that-occurs-thrice-ii/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
This is the code I've submitted and the solution was accepted.
I'm attaching a missing testcase where this submission gives wrong ans.

### Language used for code
C++

### Code used for Submit/Run operation
```
class Solution {
public:
    int maximumLength(string s) {
        int n = s.size(), i = 0, ans = 0;
        unordered_map<char, int> m1, m2, A;
        while(i < n) {
            int count = 0;
            char c = s[i];
            while(i < n and c == s[i]) count++, c = s[i], i++;
            if(m2.count(c) == 0) {
                m1[c] = 2;
                m2[c] = 1;
                 A[c] = count;
            }
            else{
                if(A[c] - 1 <= count) {
                    if(A[c] - 1 == count) m1[c] = 3;
                    else if(A[c] == count){
                        m1[c] = 3;
                        m2[c]++;
                    }
                    else if(A[c] + 1 == count){
                        m1[c] = m2[c] + 1;
                        m2[c] = 1;
                        A[c] = count;
                    }
                    else{
                        m1[c] = 2;
                        m2[c] = 1;
                         A[c] = count;
                    }
                }
            }
            if(m2[c] > 2) ans = max(ans, A[c]);
            else if(m1[c] > 2) ans = max(ans, A[c] - 1);
            else ans = max(ans, A[c] - 2);
        }
        return ans == 0? -1 : ans;
    }
};
```

### Expected behavior
This code fails on the following test case
`cddedeedccedcedecdedcdeededdddcdddddcdeecdcddeecdc`

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/60441222/edcc954b-3c5a-4fdf-9ee7-cdf4177f5b04)

### Additional context
This is my accepted submission
https://leetcode.com/submissions/detail/1132971655/

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
