### ISSUE TITLE
缺少测试用例 - 1599. 经营摩天轮的最大利润

### ISSUE THREAD

**Issue by MarchYuanx** [LeetCode-Feedback/LeetCode-Feedback#19026]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

### LeetCode 用户名

芝士麻雀

### 问题号码、标题和链接

1599. https://leetcode.cn/problems/maximum-profit-of-operating-a-centennial-wheel/description/

### Bug 类型
- [ ] 问题描述
- [ ] 示例
- [ ] 问题限制
- [ ] 问题提示
- [ ] 不正确或缺少“相关标签”
- [ ] 不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*
- [x] 缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*
- [ ] 力扣官方题解
- [ ] 编程语言支持

### 描述

Custom Case
 ```
customer=[5,0,0,0,0,0] boardingCost=5 runningCost =5
```
输出
```
-1
```
预期
```
1
```

### 你使用的语言

JavaScript

### 你提交或者运行的代码

```js
var minOperationsMaxProfit = function(customers, boardingCost, runningCost) {
    let money = 0
    let max = 0
    let time = 0
    let wait = 0
    for(let i=0;i<customers.length;i++){
        wait += customers[i]
        money += Math.min(4, wait) * boardingCost - runningCost
        wait -= Math.min(4, wait)
        if(money >= max){
            max = money
            time = i+1
        }
    }

    while(wait){
        money += Math.min(4, wait) * boardingCost - runningCost
        wait -= Math.min(4, wait)
        if(money > max){
            max = money
            time++
        }
        
    }

    if(money <= 0){
        return -1
    }else{
        return time
    }
};
```

### 期望行为

我的代码应该提交不通过

### 屏幕截图

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/43286287/2afa035b-fca3-4e00-aebd-9b09c5695de9)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us!

When comparing the outcomes of "Run Code" and "Submit" for a specific test case, it's evident that the input and expected values are the same, yet the output values differ.

To assist you further, we have documented the causes and potential solutions for this type of issue in detail. You can find this information in our knowledge base article: [Test Case Discrepancy - Causes and Solutions](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-).

I hope this resource proves helpful. Should you have any additional questions or need further clarification on this case, please do not hesitate to reach out to us. We're here to assist you!

Best regards,
LeetCode Support Team
