### ISSUE TITLE
45.跳跃游戏Ⅱ 运行和提交结果不匹配

### ISSUE THREAD

**Issue by JesterHey** [LeetCode-Feedback/LeetCode-Feedback#19027]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

### LeetCode 用户名
JESTER

### 问题号码、标题和链接

[45.跳跃游戏 Ⅱ](https://leetcode.cn/problems/jump-game-ii/)

### Bug 类型
- [ ] 问题描述
- [ ] 示例
- [ ] 问题限制
- [ ] 问题提示
- [ ] 不正确或缺少“相关标签”
- [ ] 不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*
- [ ] 缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*
- [ ] 力扣官方题解
- [ ] 编程语言支持
- [x] 运行和提交结果不一致

### 描述
同样的测试用例
[1,2]和[2,1]
在"运行"时，结果正确；
在"提交"时，结果错误。
且均输出为0。

### 你使用的语言  
__python3__

### 你提交或者运行的代码

```python
ans = float('inf')
class Solution:
    def jump(self, nums: List[int]) -> int:
        n = len(nums)
        i = 0
        jumps = 0
        @cache
        def dfs(i, n, jumps) -> int:
            global ans
            '''
            i:当前位置索引
            n:列表长度
            ans:全局答案
            jumps:跳到当前位置i所经历的总跳跃步数
            '''
            if i >= n:
                ans = min(float('inf'),ans)
                return ans
            if i == n - 1:
                ans = min(jumps, ans)  # 当前位置恰好是最后，进行记录
                return ans
            # 进行回溯
            canjump = nums[i]
            for j in range(1, canjump + 1):
                dfs(i + j, n, jumps + 1)
        dfs(i, n, jumps)
        return ans
```

### 屏幕截图
<img width="1239" alt="屏幕截图 2024-01-01 182409" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/144512889/a76bdd8a-c839-4559-99ec-86a8f41c4b0a">
<img width="1237" alt="2" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/144512889/0f7d4f90-f79a-4dea-b5d1-29b935773c80">

**Comment by amcones-lc** [comment]
您好，在与相关团队核实后：***不处理***（使用全局变量时，多个测试用例之间会共享数据，导致程序不按预期运行）。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
