### ISSUE TITLE
Missing Test Case - 1599. Maximum Profit of Operating a Centennial Wheel

### ISSUE THREAD

**Issue by HToothpick** [LeetCode-Feedback/LeetCode-Feedback#19022]
### LeetCode Username
tu-ran-gai-ming (leetcode.cn)

### Problem number, title, and link
1599. Maximum Profit of Operating a Centennial Wheel https://leetcode.cn/problems/maximum-profit-of-operating-a-centennial-wheel/

### Category of the bug
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug
A solution allows the wheel start and stop only at when the operator can earn in a turn. It is not correct as the problem's meaning, but passed all existing text cases.

### Language used for code
C

### Code used for Submit/Run operation
```
int minOperationsMaxProfit(int* customers, int customersSize, int boardingCost, int runningCost){
    int p=0,t=0,c=0;
    for(int i=0;i<customersSize;i++){
        p+=customers[i];
        if(p<=4){
            if((p*boardingCost-runningCost)>=0){
                t+=p*boardingCost-runningCost;
                p=0;
                c=i+1;
            }
        }
        else{
            t+=boardingCost*4-runningCost;
            p-=4;
            c=i+1;
        }
    }

    if(p>0){
        t+=p*boardingCost-(p/4)*runningCost;
        c+=p/4;
        if(((p%4)*boardingCost-runningCost)>0){
            t+=(p%4)*boardingCost-runningCost;
            c++;
        }
    }
    
    return t>0?c:-1;
}
```

### Expected behavior
test case:
```
[4,0,0,0,0,3]
5
12
```
output:
```
6
```
expected result:
```
1
```

### Screenshots
![rep](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/155350218/7c6742ec-d5b5-4749-b205-146d0497246f)

### Additional context
I have been stuck in this high gondola for 8 hours, while the greedy operator still refuses to turn the wheel. I try to report this bug by my 3% charge phone.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team
