### ISSUE TITLE
[BUG] Incorrect Test Case - 20. Valid Parentheses

### ISSUE THREAD

**Issue by icedragon002** [LeetCode-Feedback/LeetCode-Feedback#19033]
### LeetCode Username
icedragon815

### Problem number, title, and link

20. [Valid Parentheses](https://leetcode.cn/problems/valid-parentheses/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [X] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

  When i use my code to submit, the test case which is No.91 have a bug.I check my code in clion and web debug mode of leetcode,but the test case is wrong.
  The input string is "([)]".The answer is true, but my code in leetcode website is false.I try it in Clion,even the debug mode in leetcode website.It's always true.

### Language used for code

C++

### Code used for Submit/Run operation

```
class Solution {
public:
    bool isValid(string s) {
        stack<bool> left1;
        stack<bool> left2;
        stack<bool> left3;

        for (int i = 0; i < s.length(); i++) {
            if (s[i] == '(') {
                left1.push(true);
            }
            if (s[i] == '[') {
                left2.push(true);
            }
            if (s[i] == '{') {
                left3.push(true);
            }
            if (s[i] == ')') {
                if (left1.size()) {
                    left1.pop();
                } else {
                    return false;
                }
            }
            if (s[i] == ']') {
                if (left2.size()) {
                    left2.pop();
                } else {
                    return false;
                }
            }

            if (s[i] == '}') {
                if (left3.size()) {
                    left3.pop();
                } else {
                    return false;
                }
            }
        }
        if (!left1.size() && !left2.size() && !left3.size()) {
            return true;
        } else {
            return false;
        }
    }
};
```

### Expected behavior

Can u fix the bug? I want to submit my code for compare the performance.

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
