### ISSUE TITLE
Missing pseudocode template - explore card (queue and BFS)

### ISSUE THREAD

**Issue by cali-li** [LeetCode-Feedback/LeetCode-Feedback#19039]
### LeetCode Username

StayFresh

### Problem number, title, and link

explore card -> queue & stack -> queue & BFS -> BFS Template

link: https://leetcode.com/explore/learn/card/queue-stack/231/practical-application-queue/1372/

### Category of the bug

- [ ] Incorrect or missing "Related Topics"

### Description of the bug

the pseudocode template inside the BFS template explanation is missing.

### Screenshots

<img width="796" alt="Screen Shot 2024-01-01 at 2 50 39 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/55301553/9c19b512-8d7e-4743-8c2a-2bdac20eb653">

**Comment by RieBi** [comment]
Can relate to that. Just went through the explore card and the code is missing!

**Comment by SaaiVenkat** [comment]
Facing the same issue

**Comment by LC-Pam** [comment]
Duplicated Issue

**Comment by johnkxl** [comment]
Should not be Closed. Templates are still missing.
