### ISSUE TITLE
Missing Test Case - 455. Assign Cookies

### ISSUE THREAD

**Issue by janek-123** [LeetCode-Feedback/LeetCode-Feedback#19038]
### LeetCode Username
janek123

### Problem number, title, and link
[455. Assign Cookies](https://leetcode.com/problems/assign-cookies/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
The incorrect code does not get accepted, but adding this testcase before the 16th one would help you understand what is wrong with your code. (16th test case has extremely long input array)

Testcase: 
g = [3, 3]
s = [1, 3]

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
