### ISSUE TITLE
Incorrect Editorial - 455. Assign Cookies

### ISSUE THREAD

**Issue by MohammadShawer-Khandariya** [LeetCode-Feedback/LeetCode-Feedback#19034]
### Category of the bug
- [x] Editorial

### Description of the bug
In the Editorial Complexity Analysis section, same value **n** is represented for both **g** and **s** array.
```Time Complexity: O(n⋅log⁡n+m⋅log⁡m) where **n** is the size of the array g and **n** is the size of the array s.```

### Code used for Submit/Run operation

```
/**
 * @param {number[]} g
 * @param {number[]} s
 * @return {number}
 */
var findContentChildren = function(g, s) {
    g.sort((a,b) => a - b);
    s.sort((a,b) => a - b);
    let j = 0;
    for (let i of s) {
        if (i >= g[j]) {
            j++;
        }
    }

    return j;
};
```

### Expected behavior
In the Editorial **n** and **m** value should be represented for **g** and **s** respectively. Like below:
```Time Complexity: O(n⋅log⁡n+m⋅log⁡m) where **n** is the size of the array **g** and **m** is the size of the array **s**.```

### Screenshots
<img width="1728" alt="Screenshot 2024-01-01 at 9 31 33 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/128704746/be42bf26-e1fe-49e2-aa39-f3343d1a7da3">

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
