### ISSUE TITLE
Editorial solution does not work - Explore/learn/card/recursion-ii

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#19047]
### Category of the bug
- [ ] Problem description
- [x] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug

Editorial given at 
https://leetcode.com/explore/learn/card/recursion-ii/470/divide-and-conquer/2870/
below
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/8236389/3351a2f3-c1df-4bbb-ae52-06cb191e8653)

does not work
gives TLE
for this problem
https://leetcode.com/problems/sort-an-array/description/

https://leetcode.com/problems/sort-an-array/submissions/1134414669/
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/8236389/54415949-af85-4413-8fbf-4b8352732a36)

### Language used for code
JavaScript

### Code used for Submit/Run operation

```
const quickSort = (a) => {
  const partition = (a, lo, hi) => {
    const pivot = a[hi]
    let i = lo
    for (let j = lo; j < hi; ++j) {
      if (a[j] < pivot) {
        [a[i], a[j]] = [a[j], a[i]]
        i++
      }
    }
    [a[i], a[hi]] = [a[hi], a[i]]
    return i
  }
  const qSort = (a, lo, hi) => {
    if (lo >= hi) return
    const p = partition(a, lo, hi)
    qSort(a, lo, p - 1)
    qSort(a, p + 1, hi)
  }
  const n = a.length
  qSort(a, 0, n - 1)
  return a
}
const sortArray = (a) => quickSort(a)
```

### Expected behavior

Editorial takes last element as pivot, not random enough, to pass normal sort problem
Editorial gives something that cannot be used in real time

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

The quickSort explore card is meant to introduce users to the the quicksort algorithm. Using the last element as a pivot is easy to understand and works correctly for sorting a single array. Problem [912. Sort an Array](https://leetcode.com/problems/sort-an-array/) is meant to push users to implement a more efficient sorting algorithm than they might for an easy problem. Solutions to this problem are provided in the corresponding editorial.


If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
