### ISSUE TITLE
2610. Convert an Array Into a 2D Array With Conditions. Minor mistake in an Editorial image.

### ISSUE THREAD

**Issue by oshavrov** [LeetCode-Feedback/LeetCode-Feedback#19043]
blob:https://leetcode.com/cb66912b-6db3-419f-87cf-1412d465395d
On this image after passing number 2, it count should be 1 instead of 0.
<img width="675" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/10971537/fb0b9041-5c23-44e2-a592-557fa4ecdde5">

https://leetcode.com/problems/convert-an-array-into-a-2d-array-with-conditions/editorial/

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by oshavrov** [comment]
Same for number 4, by the way.
It count should have been updated to 1, after passing through this number

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team

**Comment by oshavrov** [comment]
Hi @LC-Pam,
My LeetCode username to get the LeetCoins is i1024i
I really appreciate this bounty and look forward to get it to my account

Thanks,
Oleg

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
