### ISSUE TITLE
206. Reverse Linked List (Golang testcase bug)

### ISSUE THREAD

**Issue by WantBeASleep** [LeetCode-Feedback/LeetCode-Feedback#19048]
### Category of the bug
- [ ] Problem description
- [*] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [*] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The 2nd and 3rd test cases use the result of the first and (first && second) respectively. Because of this, the system sees an error in the responses. Check expected behavior.

### Code used for Submit/Run operation

```golang
/**
 * Definition for singly-linked list.
 * type ListNode struct {
 *     Val int
 *     Next *ListNode
 * }
 */
func reverseList(head *ListNode) *ListNode {
    rec(head)
    prev.Next = nil
    return root.Next
}

var root = &ListNode{}
var prev = root

func rec(nd *ListNode) {
    if nd == nil {
        return
    }
    rec(nd.Next)

    prev.Next = nd
    prev = nd
}
```

### Expected behavior

result of 1 testcase: [5,4,3,2,1] - it's correct
result of 2 testcase: [2,1] - but i see [5,4,3,2,1,2,1]
res of 3-rd: [] - but i see [5,4,3,2,1,2,1]

### Screenshots

![1](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/78612825/0d3f7871-2f3c-456d-9056-591fda73f249)
![2](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/78612825/4bace5d0-be45-4941-8b24-68135a7355df)
![3](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/78612825/47c67526-4d98-46d2-b0cc-8fc7437785f1)

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
