### ISSUE TITLE
Error in Test Case - 189. Rotate Array

### ISSUE THREAD

**Issue by kaaviya-s** [LeetCode-Feedback/LeetCode-Feedback#19056]
### LeetCode Username

kaaviyas1906

### Problem number, title, and link

189.Rotate Array: 
https://leetcode.com/problems/rotate-array/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ Yes] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

While evaluating the submitted code with the testcase, The input value i.e., The number count to rotate the array (K here) was given wrong , as it makes the test case fail for the submitted code. Though every other testcase passes the code, the output given for the testcase with array [1,2,3,4,5,6,7] with the rotation count k=3 was [5,6,7,1,2,3,4] . But It should be [4,5,6,7,1,2,3]. So I couldn't submit my code properly with this failing testcase.

### Language used for code

JAVA

### Code used for Submit/Run operation

```
for(int i = 0;i< k ;i++){
            int temp = nums[0];
            for(int j = 1;j<nums.length;j++){
                nums[j-1] = nums[j];
            }
            nums[nums.length-1] = temp;
        }
```

### Expected behavior

Testcase output should be : [4,5,6,7,1,2,3] with k=3,
Actual Testcase output : [5,6,7,1,2,3,4] with k = 3

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/83899413/ee3cf6d5-c05c-4bd3-9ccc-5c7947ec4cab)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.


Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by tredsused40** [comment]
The testcase you have provided is the first sample, read the explanation of it. The problem with your code is that you are rotating the array to the left, not to the right. Also your code has time complexity O(nk), which is too slow to pass this problem.

**Comment by kaaviyas1906** [comment]
I apologize for providing the wrong statement on the testcase. And Now I could understand that the mistake was on my side that I didn't read the question properly where they asked to rotate the array to right side. Thanks for the valuable insight and for your time on reading and went through the code and testcases.
