### ISSUE TITLE
Missing Test Case - 1068. Product Sales Analysis I

### ISSUE THREAD

**Issue by Janani-Sri** [LeetCode-Feedback/LeetCode-Feedback#19067]
### Category of the bug
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial

### Description of the bug
- (sale_id, year) is the primary key : This is given in the problem statement. (1)
- Question is to Write a solution to report the product_name, year, and price for each sale_id in the Sales table.

- I have added the missing test case below.
- In Editorial solution, DISTINCT is added. But if we add DISTINCT, the below test case fails.
- Without DISTINCT, the below test case passes and my submission was accepted.

- So if we consider statement (1) and if we should use DISTINCT, then the test case can be added.
- If we don't consider statement (1) in the solution, the editorial solution should be corrected.

### Missing Test Case
Sales =
| sale_id | product_id | year | quantity | price |
| ------- | ---------- | ---- | -------- | ----- |
| 1       | 100        | 2008 | 10       | 5000  |
| 2       | 100        | 2008 | 12       | 5000  |
| 7       | 200        | 2011 | 15       | 9000  |

Product =
| product_id | product_name |
| ---------- | ------------ |
| 100        | Nokia        |
| 200        | Apple        |
| 300        | Samsung      |
### Code used for Submit/Run operation

```
SELECT P.product_name, S.year, S.price
FROM Sales S
JOIN Product P
ON P.product_id = S.product_id;
```

### Expected behavior
- The above submitted code should have failed as per solution given in the editorial. 
- Instead, this resulted in successful submission because of the missing test case.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Hi there,

Your feedback has been instrumental in enhancing the problem. 

To ensure you receive your well-deserved 100 LeetCoins reward, could you kindly provide us with your LeetCode username? This will allow us to credit your account accurately.

Your participation and contributions are valued, and we want to make sure you enjoy the rewards you've earned.

Thank you for being part of the LeetCode community!

Best regards,
LeetCode Team

**Comment by LC-Pam** [comment]
Hi there,
