### ISSUE TITLE
Overflows and wrong modulo on 2438. Range Product Queries of Powers 

### ISSUE THREAD

**Issue by kocko** [LeetCode-Feedback/LeetCode-Feedback#19071]
### LeetCode Username
ghost (https://leetcode.com/namelessghoul/)

### Problem number, title, and link
2438. Range Product Queries of Powers https://leetcode.com/problems/range-product-queries-of-powers/

### Category of the bug
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### Description of the bug
It seems that the author solution does not apply the modulo operation properly.

### Language used for code
Java 

### Code used for Submit/Run operation

```
class Solution {
  public int[] productQueries(int n, int[][] queries) {
    int[] prefix = buildPrefixArray(n);
    int[] result = answerQueries(prefix, queries);
    return result;
  }
  
  private int[] buildPrefixArray(int n) {
    int[] result = new int[31];
    int next = 0, idx = 0;
    while (n > 0) {
      if (n % 2 == 1) {
        result[idx++] = next;
      }
      next++;
      n >>= 1;
    }
    for (idx = 1; idx < result.length; idx++) {
      result[idx] += result[idx - 1];
    }
    return result;
  }
  
  private int[] answerQueries(int[] prefix, int[][] queries) {
    final long MOD = (long) 1e9 + 7;
    
    int q = queries.length, idx = 0;
    int[] result = new int[q];
    
    for (int[] query : queries) {
      int left = query[0], right = query[1];
      int power = prefix[right];
      if (left > 0) {
        power -= prefix[left - 1];
      }
      result[idx++] = (int) ((1L << power) % MOD);
    }
    
    return result;
  }
  
}
```

### Expected behavior
There should be no overflows after applying the modulo operation.

### Screenshots
![Screenshot 2024-01-03 at 11 13 16](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/862000/26d17287-932e-42bc-ac81-e9c27f6c6a4e)

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
