### ISSUE TITLE
661. Image Smoother: Bit-wise Solution needs to be updated

### ISSUE THREAD

**Issue by lenhhoxung86** [LeetCode-Feedback/LeetCode-Feedback#19073]
### LeetCode Username

tdh86

### Problem number, title, and link

[661. Image Smoother](https://leetcode.com/problems/image-smoother/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug

In the Editorial bit-wise approach, the "Algorithm" section, it is written:|

Encode the smoothed value in img[i][j] as img[i][j] += (sum / count) << 8 

This is wrong. It should be: img[i][j] |= (sum/count) <<8 (img[i][j] = img[i][j] OR (sum/count) <<8)

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

### Screenshots

![image_smoother](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2775370/318c6bec-3a64-451b-abbd-5a1f3f8518d2)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team
