### ISSUE TITLE
Inaccurate Difficulty : 721. Accounts Merge

### ISSUE THREAD

**Issue by ShubhamKNIT** [LeetCode-Feedback/LeetCode-Feedback#19088]
### LeetCode Username

ShubhamKNIT

### Problem number, title, and link

721. Accounts Merge https://leetcode.com/problems/accounts-merge/description/

### Description of the bug

Difficulty of this question is marked to be medium. However, if you ask me and see comments from other leetcoders in discussion, they found this question difficult to be approached, if they didn't see the tag. Question itself is based on DisjointSet. To come up with code of DisjointSet and considering the logic required to solve this question, the approach is harder. And Leetcode team should reconsider this question difficulty. 

Steps I went through to obtain solution:
1. Make disjoint set, meanwhile also map the email with node.
2. Revive the mail list for the node using mailMapper and ultimateparent concept.
3. Sort the mailList for each non-empty node list of mails and store in answer.

These steps are so dense if you see the code. And, like said, it was kind of hard question think of approach in first attemp of these kind of question.

### Language used for code

C++

### Code used for Submit/Run operation

```
class DisjointSet {
public:
    vector<int> size, parent;
    DisjointSet(int n) {
       size.resize(n + 1, 1);
       parent.resize(n + 1);
       for (int i = 0; i <= n; i++) {
           parent[i] = i;
       }
    }
    
    int findUltimateParent(int node) {
        if (parent[node] == node) {
            return node;
        }
        return parent[node] = findUltimateParent(parent[node]);
    }
    
    void unionBySize(int u, int v) {
        int ulPU = findUltimateParent(u);
        int ulPV = findUltimateParent(v);
        
        if (ulPU == ulPV) return;
        
        int sizePU = size[ulPU];
        int sizePV = size[ulPV];
        
        if (sizePU < sizePV) {
            parent[ulPU] = ulPV;
            size[ulPV] += size[ulPU]; 
        }
        else {
            parent[ulPV] = ulPU;
            size[ulPU] += size[ulPV];
        }
    }
};
class Solution {
public:
    vector<vector<string>> accountsMerge(vector<vector<string>>& accounts) {
        int n = accounts.size();
        unordered_map<string, int> mp; // mailNode mapper

        DisjointSet ds(n);

        for (int i = 0; i < n; i++) {
            for (int j = 1; j < accounts[i].size(); j++) { // 0-in:ignore-name
                string mail = accounts[i][j];
                if (mp.find(mail) == mp.end()) {
                    mp[mail] = i;
                }
                else {
                    ds.unionBySize(i, mp[mail]);
                }
            }
        }

        // merge mails into the node from mailNode mapper 
        vector<string> mailMerge[n];
        for (auto it : mp) {
            string mail = it.first;
            int node = it.second;

            int ulParent = ds.findUltimateParent(node);

            mailMerge[ulParent].push_back(mail);
        }

        vector<vector<string>> ans;
        // sorting the mails in mailMerge and storing in ans
        for (int i = 0; i < n; i++) {
            if (mailMerge[i].size() == 0) continue;
            
            sort(mailMerge[i].begin(), mailMerge[i].end());

            vector<string> res;
            res.push_back(accounts[i][0]); // account-holder

            for (auto it : mailMerge[i]) {
                res.push_back(it);
            }

            ans.push_back(res);
        }

        return ans;
    }
};
```

### Screenshots

<img width="714" alt="Screenshot 2024-01-03 at 11 04 47 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/121822213/19c2d8cf-a730-4905-974a-1d2a3b4a967c">

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
