### ISSUE TITLE
More efficient approach than the editorial  - 2272. Substring With Largest Variance

### ISSUE THREAD

**Issue by harshits2808** [LeetCode-Feedback/LeetCode-Feedback#19096]
### LeetCode Username
harshits2808

### Problem number, title, and link
[2272. Substring With Largest Variance] (https://leetcode.com/problems/substring-with-largest-variance/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug

Not a bug, but there is a more efficient solution possible which I think should be mentioned in the editorial.

The editorial shows the O(n*k^2) solution, but it can be solved in O(n*k) as well (With an increase in space complexity fro O(1) to O(k^2)

### Language used for code

C++

### Code used for Submit/Run operation

```
class Solution {
public:
    int largestVariance(string s) {
        vector<int> counter(26, 0);
        for (char ch : s) {
            counter[ch - 'a']++;
        }

        int globalMax = 0;
        vector<vector<int>> majorCount(26, vector<int>(26,0));
        vector<vector<int>> minorCount(26, vector<int>(26,0));
        vector<int> restMinor = counter;

        for (char ch : s) {
            int ch1 = ch - 'a';
            restMinor[ch1]--;
            for(int ch2 = 0; ch2 < 26; ch2++) {
                if(ch1 == ch2 || counter[ch2] == 0) {
                    continue;
                }

                // Treat ch1 as Major and ch2 as Minor
                majorCount[ch1][ch2]++;

                if (minorCount[ch1][ch2] > 0)
                    globalMax = max(globalMax, majorCount[ch1][ch2] - minorCount[ch1][ch2]);
                
                if (majorCount[ch1][ch2] < minorCount[ch1][ch2] && restMinor[ch2] > 0) {
                    majorCount[ch1][ch2] = 0;
                    minorCount[ch1][ch2] = 0;
                }

                // Treat ch2 as Major and ch1 as Minor
                minorCount[ch2][ch1]++;

                if (minorCount[ch2][ch1] > 0)
                    globalMax = max(globalMax, majorCount[ch2][ch1] - minorCount[ch2][ch1]);
                
                if (majorCount[ch2][ch1] < minorCount[ch2][ch1] && restMinor[ch1] > 0) {
                    majorCount[ch2][ch1] = 0;
                    minorCount[ch2][ch1] = 0;
                }
            }
        }
        
        return globalMax;
    }
};

```

### Expected behavior

The more efficient algorithm to solve the problem would be a good add-on to the existing editorial, helping anyone that goes through it to get a better understanding of the problem and approaches to solve it.

### Additional context
I have posted the solution explaining a little about the approach as well over here - https://leetcode.com/problems/substring-with-largest-variance/solutions/4501189/a-more-efficient-solution-than-the-editorial-o-n-k-solution/

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by harshits2808** [comment]
Hi @LC-Pam 
Any update on this?

**Comment by LC-Pam** [comment]
Thank you for this suggestion. 
We agree that this is a good solution and will keep it in mind for future article edits
As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.
If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
