### ISSUE TITLE
189. 旋转数组

### ISSUE THREAD

**Issue by nbhtm2014** [LeetCode-Feedback/LeetCode-Feedback#1909]
** Bug 类型**
- [189. 旋转数组 ] 题目
- [x] 题解
- [php ] 编程语言

**描述**
描述你遇到的 bug

**你使用的语言**
php

**你提交或者运行的代码**
```
class Solution {

    /**
     * @param Integer[] $nums
     * @param Integer $k
     * @return NULL
     */
    function rotate(&$nums, $k) {
        $temp = [];
        end($nums);
        for ($i = $k;$i>1;$i--){
           if ($i == $k){
               $temp[] = current($nums);
           }
            array_unshift($temp,prev($nums));
        }
        $right = array_diff($nums,$temp);
        $new =  array_merge($temp,$right);
        return $new;
    }
}
```

**期望行为**
无法使用内存指针

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![image](https://user-images.githubusercontent.com/11625708/104004940-5f199100-51df-11eb-9531-91dcf698e026.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，该题要求 @return NULL ，因此代码中需要在末尾加上 $nums = $new;
