### ISSUE TITLE
Missing Test Case - 1496. Path Crossing

### ISSUE THREAD

**Issue by tredsused40** [LeetCode-Feedback/LeetCode-Feedback#19093]
### LeetCode Username

tredsused70

### Problem number, title, and link

1496. Path Crossing https://leetcode.com/problems/path-crossing/

### Category of the bug
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

Accepted code gives wrong answer on some testcases.

### Language used for code

C++

### Code used for Submit/Run operation

```
class Solution {
public:
    bool isPathCrossing(string s) {
        int n = s.size();
        if(n > 170)
            return 1;
        vector<pair<int, int>> vc(n + 1);
        int x = 0, y = 0;
        vc[0] = make_pair(x, y);
        for(int i = 0; i < n; i++) {
            if(s[i] == 'N')
                y++;
            else {
                if(s[i] == 'S')
                    y--;
                else {
                    if(s[i] == 'E')
                        x++;
                    else
                        x--;
                }
            }
            vc[i + 1] = make_pair(x, y);
        }
        sort(vc.begin(), vc.end());
        for(int i = 0; i < n; i++) {
            if(vc[i] == vc[i + 1])
                return 1;
        }
        return 0;
    }
};
```

### Expected behavior

The code itself works correct, except the one "if" at the beginning of the function. If string length is more than 170, then code returns "true" in any case, which is not correct, as there are a lot of strings with length in range [171, 10000], for which correct answer is "false". One of these cases is "ENWWSSEEENNNWWWWSSSSEEEEENNNNNWWWWWWSSSSSSEEEEEEENNNNNNNWWWWWWWWSSSSSSSSEEEEEEEEENNNNNNNNNWWWWWWWWWWSSSSSSSSSSEEEEEEEEEEENNNNNNNNNNNWWWWWWWWWWWWSSSSSSSSSSSSEEEEEEEEEEEEENNNNNNNNNNNNN". As you can see, it's just a spiral around the origin, which never intersects. Cause of the "if", the code returns "true".

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/75163817/60e03978-19f1-490e-8e42-efad152cbacd)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
