### ISSUE TITLE
Missing Test Case - 1528. Shuffle String

### ISSUE THREAD

**Issue by chetan7252** [LeetCode-Feedback/LeetCode-Feedback#19107]
### LeetCode Username

[Chetan_0052](https://leetcode.com/Chetan_0052/)

### Problem number, title, and link

[1528. Shuffle String](https://leetcode.com/problems/shuffle-string/)

### Category of the bug
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### Description of the bug
The testcases are incorrect for this question. The first test case is itself incorrect.

Input: s = "codeleet", indices = [4,5,6,7,0,2,1,3]
Output: "leetcode"
Explanation: As shown, "codeleet" becomes "leetcode" after shuffling.

### Language used for code

Java

### Code used for Submit/Run operation

```
class Solution {
    public String restoreString(String s, int[] indices) {
        StringBuilder st = new StringBuilder();
        for (int i = 0; i < indices.length; i++) {
            st.append(s.charAt(indices[i]));
        }
        return st.toString();
    }
}
```

### Expected behavior
In this question, the indices '2' and '1' must be interchanged in order to get the correct output as "leetcode".

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
