### ISSUE TITLE
124. Binary Tree Maximum Path Sum Programming language support Golang

### ISSUE THREAD

**Issue by WantBeASleep** [LeetCode-Feedback/LeetCode-Feedback#19117]
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [*] Programming language support

### Description of the bug

Incorrect output

### Language used for code

Golang

### Code used for Submit/Run operation

```golang
func maxPathSum(root *TreeNode) int {
    dfs(root)
    return ans
}

var ans = math.MinInt

func dfs(nd *TreeNode) int {
    if nd == nil {
        return 0
    }

    left := dfs(nd.Left)
    right := dfs(nd.Right)

    ans = max(ans, nd.Val, nd.Val + left, nd.Val + right, nd.Val + left + right)
    return max(nd.Val, nd.Val + left, nd.Val + right)
}
```

### Expected behavior

input root = [0]
output is 42??
![Screenshot_1](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/78612825/c5cc2a7d-25ac-4ed5-b765-c24230058aae)

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
