### ISSUE TITLE
Missing Test Case - 892. Surface Area of 3D Shapes

### ISSUE THREAD

**Issue by AdarshVishwakarma12** [LeetCode-Feedback/LeetCode-Feedback#19113]
### LeetCode Username
AdarshVishwakarma12

### Problem number, title, and link
892. Surface Area of 3D Shapes https://leetcode.com/problems/surface-area-of-3d-shapes/

### Category of the bug

- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The solution is accepted, but it fails on a test case.

### Language used for code

C++

### Code used for Submit/Run operation

```
class Solution {
public:
    int surfaceArea(vector<vector<int>>& nums) {
        int sa(0);

        int n = nums.size();

        // up and down area
        sa += n*n*2;

        if(n==1) return sa + (nums[0][0])*4;

        // if length greater than 2
        for(int i=0; i<n; ++i){
            for(int j=0; j<n; ++j){
                // if we encounter 0:
                if(!nums[i][j]) sa-=2;

                // edges
                if(i==0 || j==0 || i==n-1 || j==n-1) sa += nums[i][j];
                if((i==0 || i==n-1) && (j==0 || j==n-1)) sa += nums[i][j];

                //inside
                // two directions (right and down)
                if(i+1 < n) sa += abs(nums[i][j] - nums[i+1][j]); 
                if(j+1 < n) sa += abs(nums[i][j] - nums[i][j+1]);
            }
        }
        return sa;
    }
};
```

### Expected behavior

The solution should not be accepted since it fails on a test case: [[0]] .

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/84400092/d8800a23-5a7d-460e-b4c4-d042652275b5)

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/84400092/d3c3c561-b9ea-4811-a609-a957d3057243)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
