### ISSUE TITLE
2133. Check if Every Row and Column Contains All Numbers , Test Case Error

### ISSUE THREAD

**Issue by hamidhamri0** [LeetCode-Feedback/LeetCode-Feedback#19111]
### Problem number, title, and link
 2133. Check if Every Row and Column Contains All Numbers
https://leetcode.com/problems/check-if-every-row-and-column-contains-all-numbers/description/

### Category of the bug
- [ ] Problem description
-  Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
 So  i have solved the problem with my own code, then i wanted to check people code , i went to the best one and check his code , i have released that his code doesn't work in some cases and get the answer wrong and still his code got submitted.

### Language used for code

THIS IS HIS CODE ;
```js
var checkValid = function(matrix) {
   const N = matrix.length;
   const counters = Array.from({length: 2 * N}, () => new Array(N).fill(0));
   
   for (let row = 0; row < N; row += 1) {
       for (let col = 0; col < N; col += 1) {
           const idx = matrix[row][col] - 1;
           counters[row][idx] += 1;
           if (counters[row][idx] > 1) return false;
           counters[N + col][idx] += 1;
           if (counters[N + col][idx] > 1) return false;
       }
   }
   return true;
};
TEST CASE THAT GETS IT WRONG //[[1,2,4],[10,4,2],[2,3,1]]
```
and this is my code , both codes got submitted
```js
var checkValid = function(matrix) {
    let sum = (matrix.length * (matrix.length +1)) / 2;
    for (let i = 0; i < matrix.length; i++) {
       let sumRow = 0;
       let sumCol = 0;
       let setRow = new Set();
       let setCol = new Set();
       for (let j = 0; j < matrix.length; j++) {
          setRow.add(matrix[i][j]);
          setCol.add(matrix[j][i]);
          sumRow += matrix[i][j];
          sumCol += matrix[j][i];
       };
       if(sumRow !== sum || sumCol !== sum){
         return false;
       };
       if(setCol.size !== matrix.length || setRow.size !== matrix.length){
         return false
       };
    };
    return true
};
TEST CASE THAT MY CODE GETS RIGHT AND HIS CODE GOT IT WRONG //[[1,2,4],[10,4,2],[2,3,1]]
```

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

Please ask your question in discussion formula. 

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
