### ISSUE TITLE
Description is misleading or wrong

### ISSUE THREAD

**Issue by Dev-AbdulHannan** [LeetCode-Feedback/LeetCode-Feedback#19112]
### LeetCode Username
[AbdulHannan12](https://leetcode.com/AbdulHannan12)

### Problem number, title, and link
[189. Rotate Array](https://leetcode.com/problems/rotate-array/)

### Category of the bug
- [ ] Problem description
- [ ] Problem hints

### Description of the bug
According to the function definition provided in the code editor by default the function should not return anything instead it should modify the original array in place then in question followup there is no need of saying
<b>"Could you do it in-place with O(1) extra space?"<b> because that is already expected by us to do it in 0(1) complexity hence it is misleading or wrong
![followup](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/88274981/f0d72f24-b6e2-4058-af48-372156fdb65b)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
