### ISSUE TITLE
Missing Test Case - 1517. Find Users With Valid E-Mails

### ISSUE THREAD

**Issue by calbec** [LeetCode-Feedback/LeetCode-Feedback#19114]
### LeetCode Username

calbec

### Problem number, title, and link

[1517. Find Users With Valid E-Mails](https://leetcode.com/problems/find-users-with-valid-e-mails/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Email addresses with characters after the domain (leetcode.com) should not count as valid email addresses.

### Language used for code

SQL

### Code used for Submit/Run operation

```
SELECT * FROM Users
WHERE regexp_like(mail, '^[A-Za-z]+[A-Za-z0-9\_\.\-]*@leetcode[.]com');
```

### Expected behavior

All test cases have passed. However, the following (still missing) test case with an added suffix would also pass by mistake:

| user_id | name    | mail                    |
| ------- | ------- | ----------------------- |
| 1       | Winston | winston@leetcode.comABC |

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
