### ISSUE TITLE
Missing Test Case - 2982. Find Longest Special Substring That Occurs Thrice II

### ISSUE THREAD

**Issue by rajkmeena** [LeetCode-Feedback/LeetCode-Feedback#19122]
### LeetCode Username

https://leetcode.com/rajkmeena/

### Problem number, title, and link

[2982. Find Longest Special Substring That Occurs Thrice II](https://leetcode.com/problems/find-longest-special-substring-that-occurs-thrice-ii/)

### Category of the bug
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

The output should be wrong for the provided code, but the code get accepted

### Language used for code

C++

### Code used for Submit/Run operation

```
class Solution {
public:
    int maximumLength(string s){
        int n=size(s);
        map<char,vector<int>>mp;
        int cnt=1;
        for(int i=1; i<n; i++){
            if(s[i-1]==s[i]){
                cnt++;
            }
            else{
                mp[s[i-1]].push_back(cnt);
                cnt=1;
            }
        }
        mp[s[n-1]].push_back(cnt);

        // for(auto x:mp){
        //     cout<<x.first<<endl;
        //     for(auto y:x.second){
        //         cout<<y<<" ";
        //     }
        //     cout<<endl;
        // }    


        int ans=-1;
        for(auto x:mp){ 
            sort(x.second.begin(),x.second.end(),greater<int>());
            if(x.second.size()>=3){
                if(x.second[0]>2){
                    if(x.second[0]==x.second[1]){
                        ans=max(ans,x.second[0]-1);
                    }
                    else if(x.second[0]-x.second[1]>2){
                        ans=max(ans,x.second[0]-2);
                    }
                    else if(x.second[0]-x.second[2]<=2){
                        ans=max(ans,x.second[2]);
                    }
                    else{
                        ans=max(ans,x.second[1]);
                    }
                }
                else if(x.second[0]==2){
                    if(x.second[0]==x.second[2]){
                        ans=max(ans,2);
                    }
                    else{
                        ans=max(ans,1);
                    }
                }
                else{
                    ans=max(ans,1);
                }
            }
            else if(x.second.size()==2){
                if(x.second[0]>2){
                    if(x.second[0]==x.second[1]){
                        ans=max(ans,x.second[0]-1);
                    }
                    else if(x.second[0]-x.second[1]>2){
                        ans=max(ans,x.second[0]-2);
                    }
                    else{
                        ans=max(ans,x.second[1]);
                    }
                }
                else if(x.second[0]==2){
                    ans=max(ans,1);
                }

            }
            else{
                if(x.second[0]>=3) ans=max(ans,x.second[0]-2); 
            }
        }

        return ans;
    }
};
```

### Expected behavior

The output for the "eeeeeaeeeeebeeeee" should be 5 but the output of the code is 4. Still the code submitted.

### Screenshots

[
<img width="469" alt="Screenshot 2024-01-05 014830" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/115732706/3f071092-e4ae-49b1-8f89-6f89ce52e947">
](url)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
