### ISSUE TITLE
Test Case Not Passed

### ISSUE THREAD

**Issue by ShrilakshmiPai** [LeetCode-Feedback/LeetCode-Feedback#19124]
### LeetCode Username
shrilakshmipai

### Problem number, title, and link
811. Subdomain Visit Count https://leetcode.com/problems/subdomain-visit-count/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [Yes] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The code is correct and the sample test cases pass. But the test case 2/52 fails even though the output and expected are the same (except for the order)

### Language used for code

Python

### Code used for Submit/Run operation

```
class Solution:
    def subdomainVisits(self, cpdomains: List[str]) -> List[str]:
        res = []
        dct = {}
        for domain in cpdomains:
            c,d = domain.split()
            doms = d.split(".")
            dct[d] = int(c)
            x = d
            for i in range(len(doms)-1):
                x = x.replace(doms[i]+".","",1)
                dct[x] = dct.get(x,0) +int(c)
        for k in dct:
            res.append(str(dct[k])+" "+k)
        return(res)
```

### Expected behavior

expected for the aforementioned test case to pass

### Screenshots

![Screenshot (147)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/69654432/fea467e1-f802-4970-8b7b-6494dbbdc351)

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
