### ISSUE TITLE
Missing Test Case - 2982. Find Longest Special Substring That Occurs Thrice II

### ISSUE THREAD

**Issue by muller2333** [LeetCode-Feedback/LeetCode-Feedback#19126]
### LeetCode Username
muller2333

### Problem number, title, and link
2982. Find Longest Special Substring That Occurs Thrice II https://leetcode.com/problems/find-longest-special-substring-that-occurs-thrice-ii/description/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [X] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
An accepted solution fails on the following testcase:
s = "dceeddedcedcdcdedcdddeeedddsssdcdcdeeeccdccedeeedd"

### Language used for code
Java

### Code used for Submit/Run operation

```
class Solution {
    public int maximumLength(String s) {
        int res = -1;
        s += '0';
        char[] chars = s.toCharArray();
        int length = chars.length;
        Map<Character, int[]> map = new HashMap<>();
        int count = 1;
        for (int i = 1; i < length; i++) {
            if (chars[i] == chars[i - 1]) {
                count++;
            } else {
                char c = chars[i - 1];
                int[] arr = map.get(c);
                if (arr == null) {
                    map.put(c, new int[] { 0, 0, count });
                } else {
                    if (arr[2] <= count) {
                        arr[0] = arr[1];
                        arr[1] = arr[2];
                        arr[2] = count;
                    } else if (count < arr[1]) {
                        arr[0] = Math.max(arr[0], count);
                    } else {
                        arr[0] = arr[1];
                        arr[1] = count;
                    }
                }
                count = 1;
            }
        }
        for (int[] arr : map.values()) {
            if (arr[2] > res) {
                if (arr[1] == 0) {
                    if (arr[2] >= 3) {
                        res = Math.max(res, arr[2] - 2);
                    }
                } else {
                    if (arr[2] == 1) {
                        res = Math.max(res, arr[0] == 0 ? -1 : 1);
                    } else {
                        if (arr[2] - arr[1] <= 1) {
                            res = Math.max(res, arr[2] - 1);
                        } else {
                            res = Math.max(res, Math.max(arr[1], arr[2] - 2));
                        }
                    }
                }
            }
        }
        return res;
    }
}
```

### Screenshots
![MicrosoftTeams-image (4)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/25950952/2e2b9c84-971b-4893-8af2-528d2c23586e)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
