### ISSUE TITLE
Missing Test Case - 2870. Minimum Number of Operations to Make Array Empty

### ISSUE THREAD

**Issue by tredsused40** [LeetCode-Feedback/LeetCode-Feedback#19123]
### LeetCode Username

tredsused70

### Problem number, title, and link

2870. Minimum Number of Operations to Make Array Empty https://leetcode.com/problems/minimum-number-of-operations-to-make-array-empty/

### Category of the bug
- [.] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

Code that gets accepted works too long on some testcases.

### Language used for code

C++

### Code used for Submit/Run operation

```
class Solution {
public:
    int minOperations(vector<int>& nums) {
        int cnt = 1;
        int ans = 0;
        int n = nums.size();
        int gap = n / 2, op = 0;
        while(gap >= 1) {
            for(int i = gap; i < n; i++) {
                int j = i - gap;
                while(j >= 0 && nums[j] > nums[j + gap]) {
                    op++;
                    swap(nums[j], nums[j + gap]);
                    j -= gap;
                }
            }
            gap /= 2;
        }
        for(int i = 1; i < n; i++) {
            if(nums[i] == nums[i - 1])
                cnt++;
            else {
                if(cnt == 1)
                    return -1;
                ans += (cnt + 2) / 3;
                cnt = 1;
            }
        }
        if(cnt == 1)
            return -1;
        ans += (cnt + 2) / 3;
        return ans;
    }
};
```

### Expected behavior

This code got "Accepted" verdict, however it's worst-case complexity is O(n^2). The most simple test case where the worst case is achieved is n = 65536, and mas[i] = i % 2 + 1, the code requires to do 536854528 swaps, which is way too much to fit in TL.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/75163817/b72993a2-d7b2-4d53-ac1b-ebb5458896ca)

### Additional context

Here is the txt file with the test.
[test.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/13835297/test.txt)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
