### ISSUE TITLE
Wrong test case : [1071. Greatest Common Divisor of Strings](https://leetcode.com/problems/greatest-common-divisor-of-strings/)

### ISSUE THREAD

**Issue by varunyadavgg** [LeetCode-Feedback/LeetCode-Feedback#19136]
### LeetCode Username
varunyadavgg

### Problem number, title, and link
1071. Greatest Common Divisor of Strings](https://leetcode.com/problems/greatest-common-divisor-of-strings/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
Input str1 ="TAUXXTAUXXTAUXXTAUXXTAUXX" 
          str2 ="TAUXXTAUXXTAUXXTAUXXTAUXXTAUXXTAUXXTAUXXTAUXX"
This is the testcase and we need to find the string GCD which turns out to be **"TAUXXTAUXXTAUXX"** but **"TAUXX"** is expected and wrong answer is shown. same error is not shown when math module is used, please update this as many new coders may face a problem

### Language used for code
Python3

### Code used for Submit/Run operation

```
class Solution:
    def gcdOfStrings(self, str1: str, str2: str) -> str:
        if len(str1)>len(str2):
            str1,str2=str2,str1
        act_sub=''
        for i in range(len(str1)):
            sub=str1[:i+1]
            lensub=len(sub)
            c_sub=str2.count(sub)
            if lensub * c_sub == len(str2):
                act_sub=sub
        return act_sub
        
```

### Expected behavior

the code should have been accepted for that test case please look into this issue and correct the expected output

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/81679842/c0f0eea9-0083-4a8c-ae6c-6b18077770e4)

### Additional context

the bug is not thrown when math module is used maybe that too is at fault ?

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
