### ISSUE TITLE
Can't read code on Design Singly Linked List - Solution

### ISSUE THREAD

**Issue by ostart** [LeetCode-Feedback/LeetCode-Feedback#19133]
### LeetCode Username
Artem Osta

### Problem number, title, and link
Design Singly Linked List - Solution  https://leetcode.com/explore/learn/card/linked-list/209/singly-linked-list/1298/

### Category of the bug
- [x] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
Can't see and read code examples on page

### Language used for code
C++ and Java

### Expected behavior
Code with solution for Singly Linked List

### Screenshots
![2024-01-05_13-39-58](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/8155112/886e3c82-1acd-4ecd-bba5-e3d8f4906327)

**Comment by LC-Pam** [comment]
Duplicated issue.
