### ISSUE TITLE
Time Complexity calculation incorrect in 30. Substring with Concatenation of All Words

### ISSUE THREAD

**Issue by harshits2808** [LeetCode-Feedback/LeetCode-Feedback#19141]
### LeetCode Username
harshits2808

### Problem number, title, and link
[30. Substring with Concatenation of All Words](https://leetcode.com/problems/substring-with-concatenation-of-all-words/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug
The time complexity of Approach 2 is not entirely correct.

The time complexity provided in the editorial is O(a+n⋅b). However, the editor missed that the time complexity of insert a string in a hashmap depends on its length, therefore the time complexity is actually O(a⋅b+n⋅b) since we are inserting 'a' number of strings of length 'b'.

It also worth mentioning that the time complexity for get() operation will also have a similar time complexity, which will effect the time complexity of the sliding window loop. This. however, will not effect the overall time complexity since a factor of 'b' is already included due to creating substrings, nevertheless, it is worth mentioning for the readers to take a note of.

### Language used for code
None

### Code used for Submit/Run operation

```
I have not submitted any solution for the problem
```

### Expected behavior
The editorial should be fixed accordingly.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by harshits2808** [comment]
Hi @LC-Pam 

Any update on this?
