### ISSUE TITLE
Missing Test Case - 743. Network Delay Time

### ISSUE THREAD

**Issue by hobbesdog** [LeetCode-Feedback/LeetCode-Feedback#1914]
#### Your LeetCode username
achiu88

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Accepted solution for problem 743 fails certain custom test cases when two nodes have more than one edge between them.

#### Code you used for Submit/Run operation

```
class Solution {
    
    private class Path {
        public int distance;
        public int node;
    }
    
    public int networkDelayTime(int[][] times, int n, int k) {
        int[][] adjMatrix = new int[n+1][n+1];
        for (int[] row : adjMatrix) {
            Arrays.fill(row, -1);
        }
        for (int[] time : times) {
            adjMatrix[time[0]][time[1]] = time[2];
        }
        boolean[] visited = new boolean[n+1];
        int visitedCount = 0;
        PriorityQueue<Path> q = new PriorityQueue<>((a, b) -> (Integer.compare(a.distance, b.distance)));
        Path first = new Path();
        first.distance = 0;
        first.node = k;
        q.add(first);
        while (!q.isEmpty()) {
            Path next = q.remove();
            if (visited[next.node]) {
                continue;
            }
            visited[next.node] = true;
            visitedCount++;
            if (visitedCount == n) {
                return next.distance;
            }
            for (int i = 1; i < adjMatrix[next.node].length; i++) {
                if (adjMatrix[next.node][i] != -1 && !visited[i]) {
                    Path toAdd = new Path();
                    toAdd.distance = next.distance + adjMatrix[next.node][i];
                    toAdd.node = i;
                    q.add(toAdd);
                }
            }
        }
        
        return -1;
        
    }
}
```

#### Language used for code
Java

#### Expected behavior
Problem statement states no assumptions on if there could be more than one edge between two nodes and the test case validator allows duplicate edges.  As such, the above code was an accepted answer while it fails the following custom test case:
```
[[2,1,1],[2,1,2]]
2
2
```
Either test cases should be added where multiple edges exist between nodes (note: there should be test cases for both where the larger weighted edge is first and the smaller weighted edge is first in the times array) or the question should disallow multiple edges between two nodes and the test case validator subsequently updated.

**Comment by lc-kay** [comment]
Hi @hobbesdog 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @hobbesdog 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
