### ISSUE TITLE
Small fix on 2090. K Radius Subarray Averages editorial

### ISSUE THREAD

**Issue by viniciusteixeiradias** [LeetCode-Feedback/LeetCode-Feedback#19156]
### LeetCode Username
viniciusteixeiradias

### Problem number, title, and link:
[- 2090. K Radius Subarray Averages](https://leetcode.com/problems/k-radius-subarray-averages/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [X] Editorial
- [ ] Programming language support

### Description of the bug

It's not exactly a bug, it would just be a suggestion for code improvement since leetcode strives to propose the best solutions for its users.

The code below refers to the code present in `- 2090. K Radius Subarray Averages > Approach 2: Sliding Window > Typescript solution`:

```typescript
function getAverages(nums: number[], k: number): number[] {
    if (k === 0) {
        return nums;
    }

    const n = nums.length;
    const averages: number[] = new Array(nums.length).fill(-1);

    if (2 * k + 1 > n) {
        return averages;
    }

    let windowSum = 0;
    for (let i = 0; i < 2 * k + 1; ++i) {
        windowSum += nums[i];
    }
    averages[k] = Math.floor(windowSum / (2 * k + 1));

    for (let i = 2 * k + 1; i < n; ++i) {
        windowSum = windowSum - nums[i - 2 * k - 1] + nums[i];
        averages[i - k] = Math.floor(windowSum / (2 * k + 1));
    }

    return averages;
};
```

### Language used for code
Typescript

### Expected behavior
Improvement suggestions:
```typescript
function getAverages(nums: number[], k: number): number[] {
    if (k === 0) { return nums }

    // save the window size in a variable
    const window_size = k * 2 + 1;

    const n = nums.length;
    // use the n variable to create the new array
    const averages = new Array(n).fill(-1)

    if (window_size > n) { return averages }

    let window_sum: number = 0;
    for(let i = 0; i < window_size; ++i) {
        window_sum += nums[i];
    }

    averages[k] = Math.floor(window_sum / window_size);

    for (let i = window_size; i < n; i++) {

        window_sum = window_sum - nums[i - k * 2 - 1] + nums[i]
        averages[i - k] = Math.floor(window_sum / window_size)
    }

    return averages;
};
```

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team

**Comment by viniciusteixeiradias** [comment]
Hi @LC-Pam sorry to bother you. But on my Point Activity it's not showing the 100 points that has been credited.
