### ISSUE TITLE
Missing Test Case - 253. Meeting Rooms II

### ISSUE THREAD

**Issue by prakhar1010** [LeetCode-Feedback/LeetCode-Feedback#19151]
### LeetCode Username

gambit88

### Problem number, title, and link

253 Meeting Rooms II https://leetcode.com/problems/meeting-rooms-ii/description/

### Category of the bug
Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

Test case with duplicate meeting intervals i.e. start and end time. 
Example: [[0,30],[5,10],[5,10],[10,20],[10,20]]

This would filter out solutions like those using SortedSets.

### Language used for code

Java

### Code used for Submit/Run operation

```
class Solution {
    public int minMeetingRooms(int[][] intervals) {

        if(intervals.length == 1) return 1;
        Arrays.sort(intervals, (l1,l2) -> l1[0] - l2[0]);

        SortedSet<List<Integer>> sortedSet = new TreeSet<>((l1,l2) -> 
                            (l1.get(1) == l2.get(1)) ? l1.get(0) - l2.get(0): l1.get(1) - l2.get(1));
        int meetingRooms = 0;
        for(int i=0; i<intervals.length; i++) {
            List<Integer> nextEndTime = (sortedSet.isEmpty()) ? null: sortedSet.first();
            if(nextEndTime == null || nextEndTime.get(1) > intervals[i][0]) {
                sortedSet.add(List.of(intervals[i][0],intervals[i][1]));
                meetingRooms++;
            } else {
                sortedSet.remove(nextEndTime);
                sortedSet.add(List.of(intervals[i][0],intervals[i][1]));
            }
        }

        return meetingRooms;
        
    }
}

```

### Expected behavior

The solution passes currently but it should fail since it cannot handle duplicate meeting intervals.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
