### ISSUE TITLE
Missing Test Case - 1235. Maximum Profit in Job Scheduling

### ISSUE THREAD

**Issue by tredsused40** [LeetCode-Feedback/LeetCode-Feedback#19169]
### LeetCode Username

tredsused70

### Problem number, title, and link

1235. Maximum Profit in Job Scheduling https://leetcode.com/problems/maximum-profit-in-job-scheduling/

### Category of the bug
- [.] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

Code that gets "Accepted" verdict gets TLE when executed with "Run" on specific testcase.

### Language used for code

C++

### Code used for Submit/Run operation

```
class Solution {
public:
    int jobScheduling(vector<int>& st, vector<int>& et, vector<int>& pr) {
        int n = et.size();
        int gap = n;
        map<int, int> dp;
        while(gap) {
            for(int i = gap; i < n; i++) {
                int j = i - gap;
                while(j >= 0 && et[j] > et[j + gap]) {
                    swap(et[j + gap], et[j]);
                    swap(st[j + gap], st[j]);
                    swap(pr[j + gap], pr[j]);
                    j -= gap;
                }
            }
            gap /= 2;
        }
        dp[0] = 0;
        for(int i = 0; i < n; i++) {
            dp[et[i]] = max(prev(dp.end()) -> second, dp[et[i]]);
            auto it = dp.upper_bound(st[i]);
            it--;
            dp[et[i]] = max(dp[et[i]], it -> second + pr[i]);
        }
        return prev(dp.end()) -> second;
    }
};
```

### Expected behavior

When this code executes on test that is given in the .txt file below, it gets TLE, because the code tries to do 402628608 swaps when runned, and similar number of some other operations, which is way too much to fit in TL.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/75163817/c45b47ea-5d8d-43a4-b88e-1e77eb5e3103)

### Additional context

[test.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/13851856/test.txt)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
