### ISSUE TITLE
Example 1335. Minimum Difficulty of a Job Schedule — wrong slide for the bottom-up implementation

### ISSUE THREAD

**Issue by efpies** [LeetCode-Feedback/LeetCode-Feedback#19166]
### Problem number, title, and link

https://leetcode.com/explore/learn/card/dynamic-programming/632/common-patterns-in-dp-problems/4109/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug

Under the bottom-up implementation, there's an animation. The slide 25/30 seems to be incorrect.

It should be `dp[4][2]` as `i = 4`.

<img width="762" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/1215572/99798900-eedb-4549-9a62-8a62856aafe8">

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
