### ISSUE TITLE
无法切换代码编辑器皮肤

### ISSUE THREAD

**Issue by ThomasShaw1** [LeetCode-Feedback/LeetCode-Feedback#19189]
以前是可以切换到其他皮肤的，现在这个选项没了。
![Screenshot 2024-01-07 151538](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/90146234/b7d78033-0348-47fb-b927-7fd680c98ecf)

**Comment by liyuzhu-lc** [comment]
请问点击头像->外观，可以正常修改吗？
<img width="362" alt="截屏2024-01-08 18 22 51" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/153068534/8e6af0fa-0c85-4454-90de-28545f373938">

**Comment by ThomasShaw1** [comment]
你说的是暗黑模式，我指的是编辑器皮肤主题设置，请看下面的图，现在竞赛页面的编辑器主题设置还是可以更换的(如图)，但是题目页面的编辑器主题设置选项自从功能更新后就没了。
![Screenshot 2024-01-10 042040](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/90146234/e43a868f-e7c1-44ef-b0c6-fca03217c887)

**Comment by liyuzhu-lc** [comment]
感谢您的反馈，当前该功能已下线，我们会在后续的版本不断更新优化和提升我们的产品，给大家带来最佳的用户体验。
