### ISSUE TITLE
Missing Test Case - 1630. Arithmetic Subarrays

### ISSUE THREAD

**Issue by tredsused40** [LeetCode-Feedback/LeetCode-Feedback#19185]
### LeetCode Username

tredsused70

### Problem number, title, and link

1630. Arithmetic Subarrays https://leetcode.com/problems/arithmetic-subarrays/

### Category of the bug
- [.] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

Code that got "Accepted" verdict gets WA on specific testcases.

### Language used for code

C++

### Code used for Submit/Run operation

```
int cnt[200010] = {0};

class Solution {
public:
    vector<bool> checkArithmeticSubarrays(vector<int>& nums, vector<int>& lv, vector<int>& rv) {
        int mn = 0, n = lv.size(), l, r, d, e, scmx, mx = 0;
        vector<bool> ans(n, false);
        for(int &i : nums)
            i += 100000;
        for(int i = 0; i < n; i++) {
            l = lv[i];
            r = rv[i];
            mx = l, scmx = l + 1;
            if(nums[mx] < nums[scmx])
                swap(mx, scmx);
            cnt[nums[l]] = 1;
            cnt[nums[l + 1]] = 1;
            mn = min(nums[l], nums[l + 1]);
            for(int j = l + 2; j <= r; j++) {
                mn = min(mn, nums[j]);
                cnt[nums[j]] = 1;
                if(nums[j] < nums[scmx])
                    continue;
                if(nums[j] >= nums[mx]) {
                    scmx = mx;
                    mx = j;
                }
                else
                    scmx = j;
            }
            //cout << scmn << " " << mn << "\n";
            d = nums[mx] - nums[scmx];
            e = nums[mx] - (r - l) * d;
            if(e != mn) {
                for(int j = l; j <= r; j++)
                    cnt[nums[j]] = 0;
                continue;
            }
            if(d == 0) {
                ans[i] = 1;
                continue;
            }
            for(int j = nums[mx] - d; j >= e; j -= d) {
                if(!cnt[j])
                    e = 1000000;
            }
            if(e == mn)
                ans[i] = 1;
            for(int j = l; j <= r; j++)
                cnt[nums[j]] = 0;
        }
        return ans;
    }
};
```

### Expected behavior

When runned on the testcase nums = [2,2,2,1,3,3,4], l = [0,3], r = [2,6], output of the code is [true, true], while the correct answer is [true, false]. This happens because to ensure that the code works correctly, at the beginning of each query array *cnt* has to be filled with zeroes only. But if in query *i* all of the elements in range are equal, then for the next query there will be stored presence of number in range [l[i+1],r[i+1]] equal to nums[l[i]], while this may not be the case. So it can lead to a false-positive result, as happened in this case. After the first query cnt[2] became 1, and after processing the second query every cnt[i] for i in [1,4] stores 1 in it, which means that the output for the second query is true, however the array [1,3,3,4] cannot be converted to arithmetic sequence.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/75163817/c23162d6-89c5-40bd-aa77-e1960f2d6e35)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
