### ISSUE TITLE
Problem 1321. Description inconsistent with test cases

### ISSUE THREAD

**Issue by osamakawish** [LeetCode-Feedback/LeetCode-Feedback#19183]
### LeetCode Username
osamakawish

### Problem number, title, and link
1321: [Restaurant Growth](https://leetcode.com/problems/restaurant-growth/description/?envType=study-plan-v2&envId=top-sql-50)

### Category of the bug
- [ ] Problem description
- [ ] Problem constraints
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### Description of the bug
The problem description claims that
> (there will be at least one customer every day)

However, there are test cases where there is not at least one customer every day, and there are gaps in the days, resulting in my solution not working under this assumption.

### Language used for code
MySQL

### Code used for Submit/Run operation
```mysql
WITH daily_customers AS (
    SELECT
        visited_on,
        SUM(amount) total_amount,
        COUNT(amount) total_customers
    FROM customer c
    GROUP BY visited_on
)
SELECT
    c.visited_on,
    SUM(c1.total_amount) amount,
    ROUND(SUM(c1.total_amount) / 7, 2) average_amount
FROM daily_customers c
INNER JOIN daily_customers c1 ON c1.visited_on BETWEEN DATE_SUB(c.visited_on, INTERVAL 6 DAY) AND c.visited_on
WHERE c.visited_on IN (SELECT DATE_ADD(visited_on, INTERVAL 6 DAY) FROM customer)
GROUP BY c.visited_on
ORDER BY c.visited_on
```

The underlying idea behind this code was that I was checking if the day 6 days ago exists, (which I expected it should as it said so in the problem description - since the description claimed there should be a customer every day), and this was being checked in the `WHERE` clause. If it did, I calculated the moving average on the date via the CTE `daily_customers` at the start of the code, which stored the number of customers and amount spent each day. I joined the past 6 days and the date itself with each given date, then computed their sum twice: once for `amount`, and once for `average_amount` where I then divided by 7 (for the total number of days in a week). 

### Expected behavior
I was expecting all the test cases to have at least one customer every day, with no gaps, as stated in the description. However, some of them did contain gaps, and so my solution failed.

### Screenshots
![Screenshot (107)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/20045083/12b05a57-aca3-44fd-9b27-5ab83fb46296)

### Additional Details
Here's the raw data of the test case, demonstrating that 2019-01-02 is clearly missing from the data, despite the fact that the problem description clearly states:
> (there will be at least one customer every day)

```
| customer_id | name    | visited_on | amount |
| ----------- | ------- | ---------- | ------ |
| 1           | Jhon    | 2019-01-01 | 100    |
| 2           | Daniel  | 2019-01-12 | 110    |
| 3           | Jade    | 2019-01-03 | 120    |
| 4           | Khaled  | 2019-01-04 | 130    |
| 5           | Winston | 2019-01-05 | 110    |
| 6           | Elvis   | 2019-01-06 | 140    |
| 7           | Anna    | 2019-01-07 | 150    |
| 8           | Maria   | 2019-01-08 | 80     |
| 9           | Jaze    | 2019-01-09 | 110    |
| 1           | Jhon    | 2019-01-10 | 130    |
| 3           | Jade    | 2019-01-10 | 150    |
```

In fact, 2019-01-11 is also missing. But that doesn't seem to be included in the solution either for some reason. Needless to say, this clearly contradicts the problem description.

**Comment by osamakawish** [comment]
Just reviewed my own image and noticed this:

> 14 / 15 test cases passed

So this is apparently only an issue with one of the test cases.

My solution skipped over 2019-01-08 as 2019-01-02 didn't exist like I expected it to.

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team

**Comment by osamakawish** [comment]
Except I did double check. I am well aware I can probably write a query starting from the earliest date listed. But again, feel free to explain to me which part of the problem description I didn't understand. 

It stated every day will have at least one customer, but every day clearly did not have at least one customer that dataset.
