### ISSUE TITLE
Missing Test Case 10038. Maximize the Number of Partitions After Operations

### ISSUE THREAD

**Issue by JustJie2002** [LeetCode-Feedback/LeetCode-Feedback#19184]
### LeetCode Username

JustJie

### Problem number, title, and link

    10038. Maximize the Number of Partitions After Operations https://leetcode.com/problems/maximize-the-number-of-partitions-after-operations/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Many people included bitmask as a state in their dp (dfs + memo) but forgot that N * (1 << 26) is overall not managable if cache are not cleared after each test cases. In the following code, `@cache` is being used here but a combination of 26 separate cases, it would  cause the code to have a MLE due to too much too much states being added to cache.

### Language used for code

Python

### Code used for Submit/Run operation

```py
class Solution:
    def maxPartitionsAfterOperations(self, s: str, k: int) -> int:
        s = [ord(c)-97 for c in s]
        @cache
        def dp(idx, left, seen):
            if idx == len(s):
                return 0
            
            
            ss = seen | (1 << s[idx])
            bc = ss.bit_count()
            if bc > k:
                ret = 1 + dp(idx+1, left, 1 << s[idx])
            else:
                ret = dp(idx+1, left, ss)
            
            if left:
                for i in range(26):
                    ss = seen | (1 << i)
                    bc = ss.bit_count()
                    if bc > k:
                        ret = max(ret, 1 + dp(idx+1, left-1, 1 << i))
                    else:
                        ret = max(ret, dp(idx+1, left-1, ss))
            return ret
        return dp(0, 1, 0)+1
```

### Expected behavior

A correct solution should pass.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/76619857/e7c45d5e-d42b-4964-a1a4-31ba3986802f)

### Additional context

The 26 test cases have to all be added together:
26 cases are a string of length 1e4 being the same character abc...z, and k being 25 because I know most people wrote the case of if k = 26 then return 1.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by nskybytskyi** [comment]
This issue is misleading; it should suggest one test case, not 26 of them. Otherwise, we could add 10'000 test cases of size 10'000 each and TLE all solutions, not just the referenced one.

**Comment by tredsused40** [comment]
Are multiple testcases used for "Run" operation are actually allowed for getting "TLE" or "MLE" verdict? If so, then a considerable part of solutions can be hacked with 3-4 tests, as I have a testcase with roughly 1.8 * 10^6 states.

**Comment by JustJie2002** [comment]
> This issue is misleading; it should suggest one test case, not 26 of them. Otherwise, we could add 10'000 test cases of size 10'000 each and TLE all solutions, not just the referenced one.

In my defense, you can remove all the 100+ testcases from the system and you will get the same result with just these 26 test cases. It's more about the memory problem here over time.

**Comment by JustJie2002** [comment]
> Are multiple testcases used for "Run" operation are actually allowed for getting "TLE" or "MLE" verdict? If so, then a considerable part of solutions can be hacked with 3-4 tests, as I have a testcase with roughly 1.8 * 10^6 states.

1.8e6 states sounds fine.

**Comment by tredsused40** [comment]
> > Are multiple testcases used for "Run" operation are actually allowed for getting "TLE" or "MLE" verdict? If so, then a considerable part of solutions can be hacked with 3-4 tests, as I have a testcase with roughly 1.8 * 10^6 states.
> 
> 1.8e6 states sounds fine.

Yeah, for one test case 1.8e6 states is fine, but if you copy that test and use "Run" operation, then C++ solution gives "TLE". If you copy it one more time, python solution gives "MLE". So C++ solution fails at 2 cases, and python at 3.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

We don’t want to hack people with tricky cases.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
