### ISSUE TITLE
1064. 不动点建议增加进阶要求

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#1918]
**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
1064 由于数据规模小，直接遍历可以在 O(n) 时间内完成。考虑到数组的单调性，可以使用二分查找的方法，在 O(log n) 时间内完成。因此建议增加进阶要求，设计 O(log n) 的算法实现。中文描述和英语描述需要同步更新。

**你使用的语言**
Java

**你提交或者运行的代码**

**期望行为**
增加进阶要求，中文描述和英语描述需要同步更新。

**屏幕截图**

**额外的上下文**

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前题目与 US 同步，力扣会定期更新，保障稳定和体验优化。
