### ISSUE TITLE
Dark Theme Not Available On All leetcode.com subdomains

### ISSUE THREAD

**Issue by ThomasShaw1** [LeetCode-Feedback/LeetCode-Feedback#19188]
See the images below. leetcode.com, leetcode.com/discuss, and leetcode.com/contest/*** currently doesn't have dark theme option.
![Screenshot 2024-01-07 145834](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/90146234/37a5fabb-5cd0-45bb-be1f-6ff932f9b612)
![Screenshot 2024-01-07 145802](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/90146234/c6b49125-8c3d-4fa1-8bb7-58ad7c394834)
![Screenshot 2024-01-07 145658](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/90146234/61814984-6f8d-42d6-ac65-c14f81c43e89)

**Comment by LC-Pam** [comment]
Due to the high volume of the reports, we will temporarily close this ticket right now.
 
However, your feedback has already been successfully submitted to the team.
 
Once we have any updates from the team, we will re-open this ticket and get back to you.
 
Thank you for your understanding!
