### ISSUE TITLE
Playground code snippets not showing for Explore Card: Design Singly Linked List - Solution

### ISSUE THREAD

**Issue by yllaw** [LeetCode-Feedback/LeetCode-Feedback#19190]
### Problem number, title, and link
Linked List Explore Card: Design Singly Linked List - Solution

https://leetcode.com/explore/learn/card/linked-list/209/singly-linked-list/1298/

### Category of the bug
- [X] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [X] Editorial

### Description of the bug

Playground iFrame code snippets are showing blank / not loading correctly.

### Expected behavior
Playground code snippets should display correctly.

### Screenshots

<img width="816" alt="Screenshot 2024-01-07 at 4 12 32 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/16358778/7b9bf8fc-391e-4fc8-a7f4-b4a7cb769cdf">

### Additional context

I have tried this page on 2 different devices with the same result.

I can also confirm other code snippets are working as expected.

**Comment by porfirythelaw** [comment]
I've just stumbled upon this problem and can see that it's already been 3 weeks with no updates. Considering it's a premium article this is just disrespectful to your users.
