### ISSUE TITLE
1080 - Hint improvement

### ISSUE THREAD

**Issue by TrickyCat** [LeetCode-Feedback/LeetCode-Feedback#19199]
### LeetCode Username
**[TrickyCat 🚀](https://leetcode.com/TrickyCat/)**

### Problem number, title, and link
[1080. Insufficient Nodes in Root to Leaf Paths](https://leetcode.com/problems/insufficient-nodes-in-root-to-leaf-paths/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [x] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Hint says:

> Consider a DFS traversal of the tree. You can keep track of the current path sum from root to this node, and you can also use DFS to return the minimum value of any path from this node to the leaf. This will tell you if this node is insufficient.

And I do not fully agree with it. Instead, I think it should be better to return the **maximum** (instead of minimum) value of any path from this node to the leaf.

Let's consider an example:

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/855874/b125c9a7-f7b4-4c77-a34f-130f14d256e7)

✅ If we return the maximum from the DFS, it would lead to the correct result.  🤗

❌ If instead we would base our decision on the returned minimum (as the hint suggests) from the DFS, we would end up marking the root as an insufficient node and removing it, effectively making the answer an empty tree. 😱 Why? Let's assume that some root-to-leaf path passing some node has a minimum sum less than the limit, does this minimum constrain the other possible paths in some way other than stating that their root-to-leaf path sum is greater than or equal to that minimum? No, so those other paths can easily be greater than the limit. And since the problem defines the node as insufficient by having all (not some) the paths less than the limit, we'd end up with an issue.

### Language used for code

```csharp
public class Solution
{
	public TreeNode SufficientSubset(TreeNode root, int limit)
	{
		var rootMaxLeafPath = dfs(root, 0);
		return rootMaxLeafPath < limit
			? null
			: root;

		int dfs(TreeNode node, int sum)
		{
			if (node is null) { return int.MinValue; }
			if (node.left == null && node.right == null)
			{
				return sum + node.val;
			}

			var leftMaxLeafPath = dfs(node.left, sum + node.val);
			if (leftMaxLeafPath < limit)
			{
				node.left = null;
			}

			var rightMaxLeafPath = dfs(node.right, sum + node.val);
			if (rightMaxLeafPath < limit)
			{
				node.right = null;
			}

			return Math.Max(leftMaxLeafPath, rightMaxLeafPath);
		}
	}
}
```

---

### Proposed change

Change the wording in the hint: `minimum` => `maximum`

✌

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
