### ISSUE TITLE
707. Design Linked List - Typescript compilation due to duplicate ListNode class

### ISSUE THREAD

**Issue by yllaw** [LeetCode-Feedback/LeetCode-Feedback#19191]
### LeetCode Username
kalahari

### Problem number, title, and link

[707. Design Linked List](https://leetcode.com/problems/design-linked-list/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [X] Programming language support

### Description of the bug

Naming a class 'ListNode' when designing a Linked List causes a duplicate name compilation error for Typescript.

The error's first line output:
```
Line -38: Char 7: error TS2300: Duplicate identifier 'ListNode'.
```

Class defined on negative line number (Line -38) causes the issue.

(Compilation works when class name is defined as something other than **ListNode**)

### Language used for code
Typescript

### Code used for Submit/Run operation
```
class ListNode {
    next: ListNode | null;
    prev: ListNode | null;
    val: number;

    constructor(val: number) {
        this.val = val;
        this.next = null;
        this.prev = null;
    }
}

class MyLinkedList {
    public head: ListNode | null;
    public tail: ListNode | null;
    public size: number;

    constructor() {
        this.head = null;
        this.tail = null;
        this.size = 0;
    }

    get(index: number): number {
        if (index < 0 || index >= this.size) {
            return -1;
        } else {
            let current: ListNode | null = this.head;
            for (let i = 0; i < index; i++) {
                current = current!.next;
            }
            return current!.val;
        }
    }

    addAtHead(val: number): void {
        const newNode = new ListNode(val);
        if (this.size === 0) {
            this.head = newNode;
            this.tail = newNode;
        } else {
            newNode.next = this.head;
            this.head!.prev = newNode;
            this.head = newNode;
        }
        this.size++;
    }

    addAtTail(val: number): void {
        const newNode = new ListNode(val);
        if (this.size === 0) {
            this.head = newNode;
            this.tail = newNode;
        } else {
            newNode.prev = this.tail;
            this.tail!.next = newNode;
            this.tail = newNode;
        }
        this.size++;
    }

    addAtIndex(index: number, val: number): void {
        if (index < 0 || index > this.size) {
            return;
        } else if (index === 0) {
            this.addAtHead(val);
        } else if (index === this.size) {
            this.addAtTail(val);
        } else {
            let current: ListNode | null = this.head;
            for (let i = 0; i < index - 1; i++) {
                current = current!.next;
            }
            const newNode = new ListNode(val);
            newNode.next = current!.next;
            newNode.prev = current;
            current!.next!.prev = newNode;
            current!.next = newNode;
            this.size++;
        }
    }

    deleteAtIndex(index: number): void {
        if (index < 0 || index >= this.size) {
            return;
        } else if (index === 0) {
            this.head = this.head!.next;
            if (this.head) {
                this.head.prev = null;
            } else {
                this.tail = null;
            }
        } else if (index === this.size - 1) {
            this.tail = this.tail!.prev;
            this.tail!.next = null;
        } else {
            let current: ListNode | null = this.head;
            for (let i = 0; i < index; i++) {
                current = current!.next;
            }
            current!.prev!.next = current!.next;
            current!.next!.prev = current!.prev;
        }
        this.size--;
    }
}
```

### Expected behavior
Compilation should pass, as I have tested the class name with **ListNode** renamed to **ListNode1** which passes.

### Screenshots

<img width="702" alt="Screenshot 2024-01-07 at 4 20 51 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/16358778/d92d1d01-fed1-44e9-84ed-f314281eed96">

### Additional context

When class is named **ListNode** it fails
However when class is named **ListNode1** it passes submission

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
