### ISSUE TITLE
Memory used reported is almost same for both the below solutions

### ISSUE THREAD

**Issue by shaurya10000** [LeetCode-Feedback/LeetCode-Feedback#192]
**What kind of the bug**
- [x] problem

**Describe the bug**
Memory used reported is almost same for both the below solutions while the first takes O(m*n) space and second takes O(n) space as per complexity analysis.

**what language is your code written in**
Java

**The code you submit/run**
```
Both the below codes are faster than 100% but how come they use the same amount of memory as reported in the submission response.
First:

class Solution {
    public int uniquePaths(int m, int n) {
        int[][] memory = new int[m][n];
        
        memory[0][0] = 1;
        uniquePaths(memory, m-1, n-1);
        
        return memory[m-1][n-1];
    }
    
    private int uniquePaths(int[][] memory, int i, int j) {
        if (memory[i][j] != 0) {
            return memory[i][j];
        }
        
        if (i > 0) {
            memory[i][j] += uniquePaths(memory, i-1, j);
        }
        if (j > 0) {
            memory[i][j] += uniquePaths(memory, i, j-1);
        }
        
        return memory[i][j];
    }
}
Second:

class Solution {
    public int uniquePaths(int m, int n) {
        int[] memory = new int[n];
        
        for(int i = 0; i < n; i++) {
            memory[i] = 1;
        }
        
        for(int i = 1; i < m; i++) {
            for(int j = 1; j < n; j++) {
                memory[j] += memory[j-1];
            }
        }

        return memory[n-1];
    }
}
```

**Expected behavior**
Second solution takes O(n) space while the first one takes O(m*n) space as per complexity analysis.

**Comment by CooperCooperCooper** [comment]
Hi @shaurya10000,
Thank you for reaching out to us. To help us assess this issue, can you please share with us which problem is this issue for?

**Comment by shaurya10000** [comment]
Hi @CooperCooperCooper 
Problem Url: https://leetcode.com/problems/unique-paths/

**Comment by CooperCooperCooper** [comment]
Hi @shaurya10000,
Appreicate it. I've filed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @shaurya10000 ,
Thank you for your time. Our team wants to share the memory usage is expected. Max value of n is 100. With that much size, m*n would take like 80KB or so; therefore, it gets dominated by our internal structures. Increasing the n may help.

Due to technicalities, we will not change the size of m and n. We appreciate your support and understanding.
