### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by jeuslandim** [LeetCode-Feedback/LeetCode-Feedback#19203]
### Nome de Usuário no LeetCode
-> jeuslandim

### Número do Problema, Título e Link
1. Two Sum https://leetcode.com/problems/two-sum/

### Categoria do bug
- [ ] Descrição do problema
- [ ] Exemplos resolvidos
- [ ] Restrições do problema
- [ ] Dicas do problema
- [ ] "Related Topics" incorretos ou ausentes
- [ ] Caso de teste incorreto *(A saída do caso de teste está incorreta de acordo com o enunciado do problema)*
- [ ] Caso de teste ausente *(Código incorreto/ineficiente sendo aceito devido à ausência de casos de teste)*
- [ ] Editorial
- [ ] Suporte à linguagem de programação

### Descrição do bug
Dada uma matriz de números inteiros chamada "nums" e um número inteiro chamado "target", retorne os índices dos dois números de modo que a soma deles seja igual ao valor alvo.

Você pode assumir que cada entrada terá exatamente uma solução, e você não pode usar o mesmo elemento mais de uma vez.

Você pode retornar a resposta em qualquer ordem.

### Linguagem usada para o código
->Python

### Codigo resolvido
->
class Solution(object):

    def __init__(self): pass

    def twoSum(self, nums, target):
        """
        :type nums: List[int]
        :type target: int
        :rtype: List[int]
        """
        
        index1 = -1
        for x in nums:
            index1 += 1
            index2 = -1

            for y in nums:
                index2 += 1
                soma = x + y
                
                if soma == target and index1 != index2:
                    return [index1, index2]

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The bud description is in English.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by LC-Pam** [comment]
Hello,

Since we have not received further updates from you, we are closing this ticket. If you have any new information or additional details to share, please feel free to provide them at any time.

Thank you once again for your support and understanding. Should you have any more questions or encounter any issues in the future, do not hesitate to reach out. We're here to assist you.

Best regards,
LeetCode Support Team
