### ISSUE TITLE
88. 合并两个有序数组需要更改题目描述和增加进阶要求

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#1920]
**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
一共有以下三点需要修改。
**第一点：明确数组 `nums1` 的长度**
第 88 题的提示部分有 `nums1.length == m + n`，因此在前面的描述中需要明确这一点。
英语描述的原文是：
You may assume that `nums1` has enough space (size that is equal to `m + n`) to hold additional elements from `nums2`.
应该改成：
You may assume that `nums1` has size equal to `m + n` such that it has enough space to hold additional elements from `nums2`.
更改之后的描述明确了 `nums1` 的长度**等于** `m + n` 而不是**大于等于** `m + n`。
**第二点：注意 `m` 和 `n` 的出现顺序**
规定 `m` 是 `nums1` 中的初始化元素个数，`n` 是 `nums2` 中的初始化元素个数，因此在英语描述的 Constraints 部分，任何时候都应该满足 `m` 出现在 `n` 前面，即 Constraints 的前两点应该分别改成 `0 <= m, n <= 200` 和 `1 <= m + n <= 200`。
**第三点：增加进阶要求**
由于这道题的数据规模小，可以直接合并然后排序，该解法可以作为最简单的解法通过此题，但是面试的时候可能面试官要求不允许直接合并然后排序，而是需要利用两个数组已经有序的特点进行合并，复杂度比直接合并然后排序更低。因此建议增加进阶要求：实现复杂度为 O(m+n) 的算法解决该题，中文描述和英语描述都需要增加进阶要求。
最后，整道题的中文描述需要同步更新。

**你使用的语言**
Java

**你提交或者运行的代码**

**期望行为**
题目描述需要更改，以及增加进阶要求，中文描述和英语描述需要同步更新。

**屏幕截图**

**额外的上下文**

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前题目中英文题面已调整更新，（接受了前两个建议， 第三个建议没有调整，认为 both O(m + n) and O((m + n) log(m + n)) are ok in the interview. ），如有更多反馈和建议请与我们联系。
