### ISSUE TITLE
Missing Test Case - 958. Check Completeness of a Binary Tree

### ISSUE THREAD

**Issue by Nandhinij22** [LeetCode-Feedback/LeetCode-Feedback#19219]
nandhinijayagopi

958. Check Completeness of a Binary Tree

### Category of the bug
solved examples
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
describes about What is the function of the code when the leadnodes are from two extreme left and right

### Language used for code
Java

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
class Solution {
    public boolean isCompleteTree(TreeNode root) {
        if(root==null){
            return true;
        }
        Queue<TreeNode> q = new LinkedList<>(Arrays.asList(root));
        while(q.peek()!=null){
            TreeNode node = q.poll();
            q.offer(node.left);
            q.offer(node.right);
        }
        while(!q.isEmpty() && q.peek()==null){
            q.poll();
        }
        return q.isEmpty();
    }
}
```

### Expected behavior
for the extreme test cases it should return false since its a incomplete tree

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

Please ask your question in the discussion forum.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
