### ISSUE TITLE
Missing Test Case - 2444. Count Subarrays With Fixed Bounds

### ISSUE THREAD

**Issue by EndlessCheng** [LeetCode-Feedback/LeetCode-Feedback#19217]
#### Your LeetCode username
endlesscheng

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The code below runs O(n^2), it should get **Time Limit Exceeded**, but it got **Accepted** instead.

TEST CASE: [hack2444.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/13868079/hack2444.txt)

#### Code you used for Submit/Run operation
```python
class Solution:
    def countSubarrays(self, nums: List[int], minK: int, maxK: int) -> int:
        leftMin = 0
        leftMax = 0
        ans = 0
        cnt = Counter()
        for right, x in enumerate(nums):
            cnt[x] += 1
            while len(cnt) > 0 and (max(cnt) > maxK or min(cnt) < minK):
                if cnt[nums[leftMin]] != 0:
                    cnt[nums[leftMin]] -= 1
                if cnt[nums[leftMin]] == 0:
                    del cnt[nums[leftMin]]
                leftMin += 1
            leftMax = max(leftMax, leftMin)
            while len(cnt) > 0 and (max(cnt) == maxK and min(cnt) == minK):
                if cnt[nums[leftMax]] != 0:
                    cnt[nums[leftMax]] -= 1
                if cnt[nums[leftMax]] == 0:
                    del cnt[nums[leftMax]]
                leftMax += 1  

            ans += leftMax - leftMin           
        return ans
```

#### Language used for code
Python3

#### Expected behavior

**Time Limit Exceeded** on this test case: [hack2444.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/13868079/hack2444.txt)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
