### ISSUE TITLE
50. Pow(x, n) - Invalid testcase

### ISSUE THREAD

**Issue by vkhonin** [LeetCode-Feedback/LeetCode-Feedback#19224]
### LeetCode Username
iozh

### Problem number, title, and link
50. Pow(x, n) https://leetcode.com/problems/powx-n/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [x] Programming language support

### Description of the bug
For PHP, one test case output is incorrect, even when using correct solution.

### Language used for code
PHP

### Code used for Submit/Run operation

```
class Solution
{
    public function myPow(float $x, int $n): float
    {
        $result = 1.0;
        while ($n) {
            if ($n % 2) {
                if ($n > 0) {
                    $result *= $x;
                    $n--;
                } else {
                    $result /= $x;
                    $n++;
                }
            } else {
                $x *= $x;
                $n /= 2;
            }
        }
        return $result;
    }
}
```

### Expected behavior
Test case with arguments x = 1.0000000000001, n = -2147483648. When evaluated, output is 1.00000, while the expected result is 0.99979. I tested multiple cases and that is what I found:
1. Assigning the same value (1.0000000000001) to x inside function gives correct output (0.99979).
2. The same code with the same arguments evaluated in local environment gives correct output (0.99979).
3. Different solutions from "Solutions" tab, claimed to be correct, also do not pass this test (same mentioned by another user in "Discussion" tab).
4. PHP pow and bcpow give the same wrong output (1.00000).
5. var_dump($x) shows float(1).

I suppose there's some problem when x is passed to function in test case - it loses precision and comes as 1, not 1.0000000000001. This is what point 1 in above list about - when assigned directly inside function (just do $x = 1.0000000000001), the test is passed (but in this case the test with x = 1, n = -2147483648 fails as it also gets replaced).

### Additional context
The same problem has been reported by multiple PHP programmers (on Github, in Discussion), but still not resolved.

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
