### ISSUE TITLE
Solution with greater complexity is being accepted -154. Find Minimum in Rotated Sorted Array II

### ISSUE THREAD

**Issue by Sreehari78** [LeetCode-Feedback/LeetCode-Feedback#19220]
### Category of the bug
- [x] Problem description
- [ ] Solved examples
- [x] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

I encountered this bug while trying to solve for the question and since this is the second part of  153. Find Minimum in Rotated Sorted Array https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/ and is being listed in HARD category, the solution must only be accepted with complexity of O(log(N)). The minimum complexity is not mentioned in the description the only constrain that is added here is to use minimal number of operations which is possible with just a linear search. However, since the previous question 153. Find Minimum in Rotated Sorted Array https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/ must be done in O(log(N)) complexity it is much more appropriate to make the adjustment in the description and fix the bug that accepts linear search as a solution with 0ms, even for huge text cases with over 1000 elements.

### Language used for code
C++

### Code used for Submit/Run operation

```
class Solution {
public:
    int findMin(vector<int>& nums) {
        for(int i = 0; i < nums.size() - 1; i++){
            if(nums[i] > nums[i+1]){
                return nums[i+1];
            }
        }

        return nums[0];
        
    }
};
```

### Expected behavior

The code should return a TLE (Time Limit Exceeded error) since the complexity is O(N). However being a hard problem it is much easier for beginner to solve this code with the above given simple solution.

### Screenshots

Discovered the solution with O(N) in the code sample.
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/51209834/f6ca9b89-ba44-492d-8125-6ab071da505b)

My optimized solution with complexity of O(log(N)).
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/51209834/755996bd-50f2-45d8-a395-fdf3205ac711)

### Additional context

The problem being the second part of 153. Find Minimum in Rotated Sorted Array https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/ should be solved in O(log(N)) only hence making it a hard problem.

One such solution for the code that is in O(log(N)) complexity is :
```
class Solution {
public:
    Solution() {
        ios_base::sync_with_stdio(false);
        cin.tie(NULL);
        cout.tie(NULL);
    }

    int findMin(vector<int>& nums) {
        int start = 0, end = nums.size() - 1, mid = 0, mini = nums[0];

        
        while(start <= end) {

            while(nums[start] == nums[end] && start < end) {
                mini = min(mini, nums[start]);
                start++;
                end--;
                if(start < end) mini = min(nums[start + 1], mini);
            }
            if(nums[start] < nums[end] && nums[start] <= mini) return nums[start];
        
            mid = (start + end) / 2;

            if(nums[mid] < mini) {
                mini = min(nums[mid], mini);
                end = mid - 1;
            }
            else start = mid + 1;
        }

        return mini;
    }
};
```

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team
