### ISSUE TITLE
645. 错误的集合增加进阶要求

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#1922]
**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
第 41 题的英语描述已经更新，中文描述需要同步更新。
在第 41 题的更新后的英语描述中有进阶要求，由于第 645 题和第 41 题相似，因此建议第 645 题也增加进阶要求，使用时间复杂度 O(n) 和空间复杂度 O(1) 的算法解决问题，中文描述和英语描述需要同步更新。

**你使用的语言**
Java

**你提交或者运行的代码**

**期望行为**
第 645 题增加进阶要求，中文描述和英语描述需要同步更新。第 41 题的中文描述也需要根据英语描述更新。

**屏幕截图**

**额外的上下文**

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前题目增加了提示， US 认为这题进阶要求不需要加，中文与 US 保持一致。
