### ISSUE TITLE
138. Copy List with Random Pointer fails when using the Node Value instead of the Node reference as a key in Java

### ISSUE THREAD

**Issue by Mardis** [LeetCode-Feedback/LeetCode-Feedback#19221]
### LeetCode Username

Chronowraith

### Problem number, title, and link

[138. Copy List with Random Pointer](https://leetcode.com/problems/copy-list-with-random-pointer/)

### Category of the bug
- [ ] Problem description
- [x ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Using this code fails:
```
Map<Integer, Node> nodeMap = new HashMap<>();
public Node copyRandomList(Node head) {
        if(head == null) {
            return null;
        }
        if(nodeMap.containsKey(head.val)) {
            return nodeMap.get(head.val);
        }
        Node n = new Node(head.val);
        nodeMap.put(head.val, n);
        n.next = copyRandomList(head.next);
        n.random = copyRandomList(head.random);
        return n;
    }
}
```

but this code works:
```
HashMap<Node, Node> visitedHash = new HashMap<Node, Node>(); 
public Node copyRandomList(Node head) {
    if (head == null) {
      return null;
    }
    if (this.visitedHash.containsKey(head)) {
      return this.visitedHash.get(head);
    }
    Node node = new Node(head.val, null, null);
    this.visitedHash.put(head, node);
    node.next = this.copyRandomList(head.next);
    node.random = this.copyRandomList(head.random);
    return node;
  }
```

The only real difference is that one uses the _unique_ integer value from the node as the key when looking up nodes in the hashmap while the other uses the object identity. This seems to be an issue with how the test is being run. When adding debugging output to the code it starting showing that it somehow finds new nodes that don't exist in the original input. The end result is that the user gets a "Time Limit Exceeded" error message.

### Language used for code

Java

### Code used for Submit/Run operation

```
Map<Integer, Node> nodeMap = new HashMap<>();
public Node copyRandomList(Node head) {
        if(head == null) {
            return null;
        }
        if(nodeMap.containsKey(head.val)) {
            return nodeMap.get(head.val);
        }
        Node n = new Node(head.val);
        nodeMap.put(head.val, n);
        n.next = copyRandomList(head.next);
        n.random = copyRandomList(head.random);
        return n;
    }
}
```

### Expected behavior

This code should pass and function identically to the suggested editorial code.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
