### ISSUE TITLE
Missing Test Case - 872. Leaf-Similar Trees

### ISSUE THREAD

**Issue by TonyStark-47** [LeetCode-Feedback/LeetCode-Feedback#19228]
### LeetCode Username
tony_stark_47

### Problem number, title, and link
872. Leaf-Similar Trees https://leetcode.com/problems/leaf-similar-trees/

### Category of the bug
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

A test case is missing where one tree1 got only one node and other tree2 got more than one node but its leaf node is equal to the tree1's only one node(root node).
test case:
root1 = [1]
root2 = [2, 1]

### Language used for code

Python3

### Code used for Submit/Run operation

```
# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
class Solution:
    def leafSimilar(self, root1: Optional[TreeNode], root2: Optional[TreeNode]) -> bool:
        def for_root1(root):
            nonlocal l, root1
            if root == None:
                return ''
            if (root.left == None and root.right == None) and root != root1:
                l += str(root.val) + ','
            for_root1(root.left) 
            for_root1(root.right) 
    
        def for_root2(root):
            nonlocal m, root2
            if root == None:
                return ''
            if (root.left == None and root.right == None) and root != root2:
                m += str(root.val) + ','
            for_root2(root.left) 
            for_root2(root.right) 

        l = ''
        for_root1(root1)

        m = ''
        for_root2(root2)

        if len(l) == 0 or len(m) == 0:
            return root1.val == root2.val
        else:
            return l == m
        
```

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
