### ISSUE TITLE
Missing Test Case - 80. Remove Duplicates from Sorted Array II

### ISSUE THREAD

**Issue by AdamTadeusz** [LeetCode-Feedback/LeetCode-Feedback#19231]
### LeetCode Username

Zwiadowca

### Problem number, title, and link

[80. Remove Duplicates from Sorted Array II](https://leetcode.com/problems/remove-duplicates-from-sorted-array-ii/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [1] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Missing test case where length of input array is 1

### Language used for code

Python

### Code used for Submit/Run operation

```
class Solution:
    def removeDuplicates(self, nums: List[int]) -> int:
        writeIterator = 2
        for i in range(2, len(nums)):
            if(nums[i] != nums[writeIterator-2]):
                nums[writeIterator] = nums[i]
                writeIterator+=1
        return writeIterator
```

### Expected behavior

Solution should be rejected as code will return 2 for length of output array even if input array is of length 1, for example an input array of [1]

**Comment by AdamTadeusz** [comment]
Constraints of length of input array are given as
1 <= nums.length <= 3 * 104

**Comment by AdamTadeusz** [comment]
int k = removeDuplicates(nums); // Calls your implementation

assert k == expectedNums.length;

This is the assertion that would fail

**Comment by tredsused40** [comment]
The testcase where length of input array is not missing, if you add assert len(nums) > 1 it will fail, the thing is checker somehow accepts output 2 when input length 1. For example, this funny code gets "Accepted" when submitted with python:
```
class Solution:
    def removeDuplicates(self, nums: List[int]) -> int:
        writeIterator = 2
        for i in range(2, len(nums)):
            if(nums[i] != nums[writeIterator-2]):
                nums[writeIterator] = nums[i]
                writeIterator+=1
        if(writeIterator == len(nums)):
            writeIterator += 10000
        return writeIterator
```

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

[1] already exists. 

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
