### ISSUE TITLE
Missing Test Case - 872. Leaf-Similar Trees

### ISSUE THREAD

**Issue by mkhuzaima** [LeetCode-Feedback/LeetCode-Feedback#19237]
### LeetCode Username
mkhuzaima

### Problem number, title, and link
872. Leaf-Similar Trees https://leetcode.com/problems/leaf-similar-trees/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The problem is missing a test case, causing invalid solution to be accepted. 

### Language used for code
Python3

### Code used for Submit/Run operation
```python
class Solution:
    def leafSimilar(self, root1: Optional[TreeNode], root2: Optional[TreeNode]) -> bool:
        l1 = [0] * 200
        l2 = [0] * 200
        def dfs(root, l, count):
            if not root.left and not root.right:
                l[root.val] = count
                count += 1
            if root.left:
                count = dfs(root.left, l, count)
            if root.right:
                count = dfs(root.right, l, count)

            return count

        dfs(root1, l1, 1)
        dfs(root2, l2, 1)

        return l1 == l2
```

### Expected behavior
The code should not be accepted, since, it gives error on following input/testcase:
root1=
```
[1,2,200]
```
root2=
```
[1,2,200]
```

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
