### ISSUE TITLE
1046. Last Stone Weight unnecessary swap

### ISSUE THREAD

**Issue by matthewtuby** [LeetCode-Feedback/LeetCode-Feedback#19239]
### Problem number, title, and link

https://leetcode.com/problems/last-stone-weight/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ x] Editorial
- [ ] Programming language support

### Description of the bug

In the following **Approach 1: Array-Based Simulation** the python3 solution has an unnecessary swap. In the following function
```
def remove_largest():
    index_of_largest = stones.index(max(stones))
    # Swap the stone to be removed with the end.
    stones[index_of_largest], stones[-1] = stones[-1], stones[index_of_largest]
    return stones.pop()
```
### Language used for code

Python3

### Expected behavior

The remove largest function should be the following:
```
def remove_largest():
    idx = stones.index(max(stones))
    return stones.pop(idx)
```

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
