### ISSUE TITLE
Missing Test Case - 4. Median of Two Sorted Arrays

### ISSUE THREAD

**Issue by abdu558** [LeetCode-Feedback/LeetCode-Feedback#19230]
### LeetCode Username
xboxking

### Problem number, title, and link

4. Median of Two Sorted Arrays https://leetcode.com/problems/median-of-two-sorted-arrays/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

This problem requires a search algorithim being used where there is no iteration over the whole list, as log(m+n) or less is required.
Adding a few test cases which are much larger, during submission would therefore be benificial.

### Language used for code

Python

### Code used for Submit/Run operation

```
class Solution:
    def findMedianSortedArrays(self, nums1: List[int], nums2: List[int]) -> float:
        nums = []
        while nums1 and nums2:
            if nums1[0] > nums2[0]:
                nums.append(nums2.pop(0))
            else:
                nums.append(nums1.pop(0))
        
        nums.extend(nums1 or nums2)
        length = len(nums)
        if length % 2 == 0:
            return (nums[length // 2 - 1] + nums[length // 2]) / 2
        else:
            return nums[length//2]
```

### Expected behavior

The code above beat 97%, if testcases has much larger sizes then this would achieve a much worse ranking. This should be in the bottom 10%, due to the o(n+m) complexity.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
