### ISSUE TITLE
Missing Test Case - 80. Remove Duplicates from Sorted Array II

### ISSUE THREAD

**Issue by tredsused40** [LeetCode-Feedback/LeetCode-Feedback#19240]
### LeetCode Username

tredsused70

### Problem number, title, and link

80. Remove Duplicates from Sorted Array II https://leetcode.com/problems/remove-duplicates-from-sorted-array-ii/

### Category of the bug
- [.] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [.] Checker seems to work incorrecty in some cases.

### Description of the bug

Code that returns wrong answer on some testcases gets "Accepted" verdict.

### Language used for code

Python3

### Code used for Submit/Run operation

```
class Solution:
    def removeDuplicates(self, nums: List[int]) -> int:
        writeIterator = 2
        for i in range(2, len(nums)):
            if(nums[i] != nums[writeIterator-2]):
                nums[writeIterator] = nums[i]
                writeIterator+=1
        if(writeIterator == len(nums)):
            writeIterator += 10000
        print(writeIterator)
        return writeIterator
```

### Expected behavior

On the tests, where all of the elements in the nums are repeated no more than twice, correct value of k is equal to length of nums, for example for testcase nums = [1,2,3], the return value has to be 3, but the code above return 10003, and gets "Accepted" verdict.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/75163817/1e0e4921-8f05-4a86-9199-3a4a60b01755)

### Additional context

Seems like ```assert k == expectedNums.length;``` isn't working properly.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
