### ISSUE TITLE
Problem 208 fails tests despite behavior being consistent with the spec. 

### ISSUE THREAD

**Issue by dcechano** [LeetCode-Feedback/LeetCode-Feedback#19244]
### LeetCode Username
JumboTrout

### Problem number, title, and link
[208. Implement Trie (Prefix Tree)](https://leetcode.com/problems/implement-trie-prefix-tree/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
Problem [208](https://leetcode.com/problems/implement-trie-prefix-tree/description/) asks the user to create prefix tree. The issue is with the `insert`/`startsWith` methods. `startsWith` returns `true` if the last inserted word in the `trie` starts with the supplied `prefix`.

The bug arises because the program does all inserts, (as evidenced by print statements) then all searches and then all `startsWith` calls. But the test output seems to suggest that it was expected to do something along the lines of `insert`, `search`, `startsWith`, `insert`, `search`, `startsWith`. This means that what the test inserted last and what it thinks it inserted last are completely different resulting in erroneously failing tests.

### Language used for code
Python

### Code used for Submit/Run operation
```
class Trie:
    def __init__(self, root=None):
        self.root = root
        self.nodes = []
        self.last = None
        self.word_boundry = False

    @staticmethod
    def create_list(prev_trie, word: str):
        next_tree = Trie(word[0])
        if len(word) > 1:
            Trie.create_list(next_tree, word[1::])
        else:
            # print("create_list::word_boundry: {}".format(word))
            next_tree.word_boundry = True
        prev_trie.nodes.append(next_tree)

    def insert(self, word: str) -> None:
        if len(word) < 1:
            return

        if self.root == None:
            print("insert: {}".format(word))
            self.last = word

        inserted = False
        for tree in self.nodes:
            if word[0] == tree.root:
                inserted = True
                if len(word) > 1:
                    tree.insert(word[1::])
                else:
                    print("insert::word_boundry: {}".format(word))
                    tree.word_boundry = True

            if inserted:
                return

        if not inserted:
            # tree = Trie(word[0])
            # self.nodes.append(tree)
            if len(word) >= 1:
                Trie.create_list(self, word[::])
                # Trie.create_list(tree, word[1::])
            else:
                tree.word_boundry = True

    def inner_search(self, word):
        for trie in self.nodes:
            if word[0] == trie.root:
                if len(word) > 1:
                    return trie.inner_search(word[1::])
                else:
                    return trie.word_boundry

        return False

    def search(self, word: str) -> bool:
        length = len(word)
        if length < 1:
            return False
        print("Searching: {}".format(word))

        return self.inner_search(word)

    def startsWith(self, prefix: str) -> bool:
        print("startsWith: prefix: {} last: {}".format(prefix, self.last))
        if self.last == None or prefix == "":
            return False

        return self.last[: len(prefix)] == prefix


# Your Trie object will be instantiated and called as such:
# obj = Trie()
# obj.insert(word)
# param_2 = obj.search(word)
# param_3 = obj.startsWith(prefix)

```

### Expected behavior
I expected the tests to run the `startsWith` tests based of the last inserted word.

### Additional context
Here is the text of the prints and then the test results put into the console.

First print statements demonstrating the order of function calls

```
insert: app
insert: apple
insert: beer
insert: add
insert: jam
insert: rental
Searching: apps
Searching: app
Searching: ad
Searching: applepie
Searching: rest
Searching: jan
Searching: rent
Searching: beer
Searching: jam
startsWith: prefix: apps last: rental
startsWith: prefix: app last: rental
startsWith: prefix: ad last: rental
startsWith: prefix: applepie last: rental
startsWith: prefix: rest last: rental
startsWith: prefix: jan last: rental
startsWith: prefix: rent last: rental
startsWith: prefix: beer last: rental
startsWith: prefix: jam last: rental
```

Now the output of the tests. I put a header at the top to show the format of the output for convenience.

```
('Command', 'argument', 'actual output', 'expected output')
('Trie', [], None, None)
('insert', ['app'], None, None)
('insert', ['apple'], None, None)
('insert', ['beer'], None, None)
('insert', ['add'], None, None)
('insert', ['jam'], None, None)
('insert', ['rental'], None, None)
('search', ['apps'], False, False)
('search', ['app'], True, True)
('search', ['ad'], False, False)
('search', ['applepie'], False, False)
('search', ['rest'], False, False)
('search', ['jan'], False, False)
('search', ['rent'], False, False)
('search', ['beer'], True, True)
('search', ['jam'], True, True)
('startsWith', ['apps'], False, False)
('startsWith', ['app'], False, True)
('startsWith', ['ad'], False, True)
('startsWith', ['applepie'], False, False)
('startsWith', ['rest'], False, False)
('startsWith', ['jan'], False, False)
('startsWith', ['rent'], True, True)
('startsWith', ['beer'], False, True)
('startsWith', ['jam'], False, True)
```
As you can see all tests pass until `startsWith` where they nearly all fail in cases where the output is consistent with `rental` being the last inserted word.

Thank you for your help!

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team

**Comment by dcechano** [comment]
> Thank you for your time.
> 
> We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.
> 
> If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!
> 
> Best regards, The LeetCode Team

Thank you for looking into this but I do not understand why was determined to not be a bug. The output clearly shows the order of execution. Specifically, why was 'rental' inserted last, but the tests expected `startsWith('beer')` to return `True`? The instructions explicitly state that `startsWith` compares to the last inserted word. It very much feels as if a human didn't actually look at this and it was analyzed by a bot.
