### ISSUE TITLE
Missing Test Case - 2836. Maximize Value of Function in a Ball Passing Game

### ISSUE THREAD

**Issue by Aniket-coder29** [LeetCode-Feedback/LeetCode-Feedback#19249]
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
There is no testcase provided wherein the loop is also huge and number of leaf nodes coming to the loop is also huge.
There are accepted solutions where in coders are traversing the whole receiver array and for each node they are traversing the graph again and again. These solutions particularly fails when the loop is very much large and there are large number of leaf nodes as well.
The wrongly accepted solutions used a approach where they start from a leaf node and traverse whole graph for every leaf node.

### Language Used
C++

### Code used for Submit/Run operation

```
class Solution {
public:
    long long getMaxFunctionValue(vector<int>& r, long long k) {
        int st=(int)(log2(k))+1;
        int bl[r.size()][st];
        long long sbl[r.size()][st];
        for(int i=0;i<r.size();i++){
            bl[i][0]=r[i];
            sbl[i][0]=r[i]+i;
        }
        for(int i=1;i<st;i++){
            for(int j=0;j<r.size();j++){
                bl[j][i] =bl[bl[j][i-1]][i-1];
                sbl[j][i] = sbl[j][i-1]+sbl[bl[j][i-1]][i-1]-bl[j][i-1];
            }
        }
        unsigned long long stt = (1ULL<<(--st));
        long long ans=0ll;
        long long left = k-(long long)stt;
        for(int i=0;i<r.size();i++){
            long long pans = sbl[i][st];
            if(left>0){
                long long leftt = left;
                int node = bl[i][st];
                int left2 = (int)(log2(leftt));
                while(left2>=0){
                    pans+=sbl[node][left2]-node;
                    node=bl[node][left2];
                    unsigned long long cl = 1ULL<<left2;
                    leftt=leftt-cl;
                    if(leftt>0){
                        left2=(int)log2(leftt);
                    }else{
                        left2=-1;
                    }
                }
            }
            ans=max(ans,pans);
        }
        return ans;
    }
};
```

### Expected behavior
The wrongly accepted solutions which are using a approach where they start from a leaf node and traverse whole graph for every leaf node give TLE on the testcases where there are large number of leaf nodes leading to loop and a huge loop as well.
Here is an example testcase:
[testcase for ball passing game ques.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/13887259/testcase.for.ball.passing.game.ques.txt)

### Screenshots
Below is the screenshot of a 74ms accepted solution giving tle error on proposed testcase.
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/78076679/aeef9773-763a-4b67-b6be-b67276b19440)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
