### ISSUE TITLE
wrong Test Case - 76. Minimum Window Substring

### ISSUE THREAD

**Issue by js5395** [LeetCode-Feedback/LeetCode-Feedback#1924]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

My code failed at following test case
Input
"bbaa"
"aba"
Output:
"bba"
Expected:
"baa"
both answers should be correct since the question states all the characters and say nothing about frequency
#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@js5395 Can you please provide your code? Thank you!

**Comment by lc-kay** [comment]
Hi @js5395 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
