### ISSUE TITLE
852. 山脉数组的峰顶索引建议增加进阶要求

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#1925]
**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
第 852 题的数据规模允许遍历数组找到峰顶索引，时间复杂度是 O(n)。其实还可以通过二分查找的方法解决，时间复杂度是 O(log n)。
因此建议增加进阶要求，使用时间复杂度为 O(log n) 的算法解决。中文描述和英语描述需要同步更新。

**你使用的语言**
Java

**你提交或者运行的代码**

**期望行为**
第 852 题增加进阶要求，中文描述和英语描述需要同步更新。

**屏幕截图**

**额外的上下文**

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前题目英文进阶要求已添加， 中文描述已同步更新。
