### ISSUE TITLE
Problem 2274 - Let's improve hint 2 😉

### ISSUE THREAD

**Issue by TrickyCat** [LeetCode-Feedback/LeetCode-Feedback#19254]
### LeetCode Username
**[TrickyCat 🐱‍👓](https://leetcode.com/TrickyCat/)**

### Problem number, title, and link
[2274. Maximum Consecutive Floors Without Special Floors](https://leetcode.com/problems/maximum-consecutive-floors-without-special-floors/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [x] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Hint 2 says:

> Say there are n special floors. After sorting special, we have answer = max(answer, special[i] – special[i – 1] – 1) for all 0 < i ≤ n.

|Assuming `special` array is 0-indexed | Assuming `special` array is 1-indexed|
|-|-|
| In this case the inclusive upper bound `n` in `0 < i ≤ n` makes no sense and leads to runtime error (on trying to get the value `special[i]` for `i = n`) | In this case the exclusive lower bound `0` in `0 < i ≤ n` makes no sense and leads to runtime error (on trying to get the value `special[i - 1]` for `i = 1`)

Either way, the hint is not correct due to not properly handling the edge cases.

✌

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
