### ISSUE TITLE
BFS Template I and II not visible

### ISSUE THREAD

**Issue by jashs13** [LeetCode-Feedback/LeetCode-Feedback#19250]
### Category of the bug - template not visible 
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

**Comment by LC-Pam** [comment]
Duplicated Issue
