### ISSUE TITLE
Missing Test Case - 1041. Robot Bounded In Circle

### ISSUE THREAD

**Issue by YuanyuanTong** [LeetCode-Feedback/LeetCode-Feedback#1926]
#### Your LeetCode username
<-- elise95 -->

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Just a minor typo in the question: It should be "R": turn 90 degrees to the right.  Not "degress".

**Comment by lc-kay** [comment]
Hi @YuanyuanTong 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @YuanyuanTong 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
