### ISSUE TITLE
2385. Amount of Time for Binary Tree to Be Infected - Editorial Correction

### ISSUE THREAD

**Issue by RavaszEmber** [LeetCode-Feedback/LeetCode-Feedback#19266]
### LeetCode Username

RavaszEmber

### Problem number, title, and link

2385. Amount of Time for Binary Tree to Be Infected https://leetcode.com/problems/amount-of-time-for-binary-tree-to-be-infected/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug

In the editorial approach 2 (dfs solution) it is stated "If the leftDepth and rightDepth are both positive, the start node is not in this subtree." Strictly speaking this should be "If the leftDepth and rightDepth are both non-zero," as 0 should be checked in these cases.
The editorial solution reflects this using "if(leftDepth >= 0 && rightDepth >= 0)."

### Language used for code

C++

### Code used for Submit/Run operation

```
/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
class Solution {
public:
    int maxDistance = 0;
    int amountOfTime(TreeNode* root, int start) {
        // find the max steps away from the start node that any other node is
        // Apparently can do with BFS or DFS
        // I guess run DFS at root to find the max away from the root
        // run dfs to find the string for the root (i.e. left, left, right would be "001").
        // Run dfs again across the whole tree and if it's not along the same path add the time
        // One good way to look at this problem is to pivot the start node to be the root
        dfs(root, start);
        return maxDistance;
    }

    int dfs(TreeNode* root, int start){
        int depth = 0;
        if(root == nullptr) return depth;
        int leftDepth = dfs(root->left, start);
        int rightDepth = dfs(root->right, start);
        if(root->val == start){
            maxDistance = max(leftDepth, rightDepth);
            depth = -1;
        }else if(leftDepth >= 0 && rightDepth >= 0){
            depth = max(leftDepth, rightDepth) + 1;
        }else{
            int distance = abs(leftDepth) + abs(rightDepth);
            maxDistance = max(maxDistance, distance);
            depth = min(leftDepth, rightDepth) - 1;
        }
        return depth;
    }
};
```

### Expected behavior

This is a problem with the editorial, not the code. If > 0 is used instead of >= 0 the wrong answer is given in certain test cases.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
