### ISSUE TITLE
Missing Test Case - 2461. Maximum Sum of Distinct Subarrays With Length K

### ISSUE THREAD

**Issue by Mayank-Tiwari01** [LeetCode-Feedback/LeetCode-Feedback#19268]
### LeetCode Username

LeetCode ID: Mayank-Tiwari01

### Problem number, title, and link

2461. Maximum Sum of Distinct Subarrays With Length K
https://leetcode.com/problems/maximum-sum-of-distinct-subarrays-with-length-k/description/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ✓] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

I recently submitted a solution to a coding problem 2461. Maximum Sum of Distinct Subarrays With Length K) and while my code passed the provided test cases on LeetCode, it failed a custom test case that I had. I believe this reveals an inconsistency in the platform's evaluation process.

### Language used for code

Java

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
class Solution {
    public long maximumSubarraySum(int[] nums, int k) {
        HashMap <Integer, Integer> numIdx = new HashMap<>();
        long maxSum = 0, len = nums.length;
        int j = 0;
        long currSum = 0;
        for (int i = 0; i < len; i++) {
            if (!numIdx.containsKey(nums[i]) || numIdx.get(nums[i]) < j) {
                currSum += nums[i];
            }
            else if (numIdx.containsKey(nums[i]) && numIdx.get(nums[i]) >= j) {
                j = numIdx.get(nums[i]) + 1;
                i = j;
                currSum = nums[j];
            }
            if (i - j + 1 == k ) {
                maxSum = Math.max(maxSum, currSum);
                currSum -= nums[j];
                j++;
            }
            numIdx.put(nums[i], i);
        }
        return maxSum;
    }
}
```

### Expected behavior

In the test case I shared, the code produces an output of 23087, but the expected output should be 23320. When you run the code with this particular test case, it's easy to see that the code isn't working correctly. What's puzzling is that despite this clear issue in the provided test case, the code manages to pass all other test cases when submitted.

### Screenshots

![Web capture_10-1-2024_23314_leetcode com](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103953234/58d179bf-fbc0-4114-a9f3-e91b5df5805d)

![Web capture_10-1-2024_23614_leetcode com](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103953234/0196f034-282c-4627-8ceb-d1e74554e3b3)

I've added the missing test case, and when you run the code, it clearly shows a "Wrong Answer" for that specific test case. However, in the second screenshot, the platform accepts the answer/code, despite the evident error in the provided test case.

### Additional context

[missingTestCase2461.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/13891046/missingTestCase2461.txt)
 
### Correct code that will pass this test case:
```
class Solution {
    public long maximumSubarraySum(int[] nums, int k) {
        int len = nums.length, idx = 1;
        long sum = 0;
        long[] prefixSumArr = new long[len + 1];
        for (int num : nums) {
            sum += num;
            prefixSumArr[idx++] = sum;
        }

        HashMap<Integer, Integer> numIdx = new HashMap<>();
        long maxSum = 0;
        int s = 0; //start idx. i is end idx.
        for (int i = 0; i < len; i++) {
            if ((!numIdx.containsKey(nums[i]) || numIdx.get(nums[i]) < s) && i - s + 1 == k) {
                maxSum = Math.max(maxSum, (prefixSumArr[i + 1] - prefixSumArr[s]));
                s++;
            }
            if (numIdx.containsKey(nums[i]) && numIdx.get(nums[i]) >= s) {
                s = numIdx.get(nums[i]) + 1;
            }
            numIdx.put(nums[i], i);
        }
        return maxSum;
    }
}
```

**Comment by Mayank-Tiwari01** [comment]
Added the correct code that passes the given Test case.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
