### ISSUE TITLE
1163. 按字典序排在最后的子串 | 缺少测试数据

### ISSUE THREAD

**Issue by zerotrac** [LeetCode-Feedback/LeetCode-Feedback#1927]
**Bug 类型**

- [x] 测试数据

**描述**

这份代码可以很容易被 hack 掉：[C++17与STL泛型算法助力两分钟写出解答](https://leetcode-cn.com/problems/last-substring-in-lexicographical-order/solution/c17yu-stlfan-xing-suan-fa-zhu-li-liang-fen-zhong-x/)

**你使用的语言**

C++

**需要添加的测试数据**

添加一组重复出现 `200000` 次的 `ab` 即可。

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
您好，当前该题已添加测试用例，请留言告知一下您的力扣 ID，我们给予积分奖励哦。
