### ISSUE TITLE
Missing Test Case - 9. Palindrome Number

### ISSUE THREAD

**Issue by ThanoS-max** [LeetCode-Feedback/LeetCode-Feedback#1928]
#### Category of the bug
- [yes ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Not a bug but defining the meaning of Palindrome in this question would be very helpful for all those solving it.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@ThanoS-max 

Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@ThanoS-max The meaning of Palindrome is already defined in a one-line problem.
An integer is a palindrome when it reads the same backward as forward.
