### ISSUE TITLE
cannot visualize the template in the queue-stack explore card

### ISSUE THREAD

**Issue by mahaveer220** [LeetCode-Feedback/LeetCode-Feedback#19282]
### LeetCode Username

bonagirimahaveer

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug

cannot see the template pseudo codes as mentioned in the description in this [link](https://leetcode.com/explore/learn/card/queue-stack/231/practical-application-queue/1372/)

### Language used for code

Not Applicable

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

### Screenshots

Screenshots are attacched
<img width="859" alt="Screenshot 2024-01-10 at 9 38 05 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/23069383/b401ff7c-fb48-4baf-9480-0c0c67d371d0">
<img width="668" alt="Screenshot 2024-01-10 at 9 38 20 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/23069383/e166fab0-5c37-4dcd-a3af-544d6e382139">

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
