### ISSUE TITLE
Missing Test Case - 1026. Maximum Difference Between Node and Ancestor

### ISSUE THREAD

**Issue by LeeAnhDduwcs** [LeetCode-Feedback/LeetCode-Feedback#19283]
### LeetCode Username
[Lad22216](https://leetcode.com/Lad22216)

### Problem number, title, and link

[1026. Maximum Difference Between Node and Ancestor](https://leetcode.com/problems/maximum-difference-between-node-and-ancestor/)

### Category of the bug
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

Hello, LeetCode team 😄
I spent about 2 hours to solve this problem. After I did it, I didn't know why my code was accepted. I found that my algorithm was wrong.
My idea is using the max,min value of left and right subtree to compute the max, min of the higher subtree.
I think the fault of this algorithm is the lack of return result after each loop. Because excepted result can be different from the max,min pair of the subtree.

### Language used for code

C++

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
class Solution {
public:
    //return pair of max and min of three integers
    pair<int,int> maxMin(int a,int b,int c){
        if((a>=b&&b>=c)||(a<=b&&b<=c))return {a,c};
        if((b>=a&&a>=c)||(b<=a&&a<=c))return {b,c};
        return {a,b};
   }
    //return a vector with 4 elements, two pairs of maxMin left and right subtree.
    vector<int> solve(TreeNode* n){
        if(!n)return {};
        if(!n->left&&!n->right) return {n->val,n->val,n->val,n->val};
        vector<int> l=solve(n->left);
        vector<int> r=solve(n->right);
        int nl=l.size(),nr=r.size();
        if(nl){
            pair<int,int> ll=maxMin(l[0],l[1],n->val);
            pair<int,int> lr=maxMin(l[2],l[3],n->val);
            if(abs(ll.first-ll.second)<abs(lr.first-lr.second)) ll=lr;
            if(nr){
                pair<int,int> rl=maxMin(r[0],r[1],n->val);
                pair<int,int> rr=maxMin(r[2],r[3],n->val);
                if(abs(rl.first-rl.second)<abs(rr.first-rr.second)) rl=rr;
                return{ll.first,ll.second,rl.first,rl.second};//It just uses subtree which has the 2nd depth to compute the result.
            }
            else {
                return{ll.first,ll.second,ll.first,ll.second};
            }
        }
        pair<int,int> rl=maxMin(r[0],r[1],n->val);
        pair<int,int> rr=maxMin(r[2],r[3],n->val);
        if(abs(rl.first-rl.second)<abs(rr.first-rr.second)) rl=rr;
        return{rl.first,rl.second,rl.first,rl.second};
    }

    int maxAncestorDiff(TreeNode* root) {
        if(!root)return 0;
        vector<int> l= solve(root);
        return max(abs(l[0]-l[1]),abs(l[2]-l[3]));
    }
};
```

### Expected behavior

Test case:
Input

> root = [1,6,null,5,4,null,null,7,2]

Expected Output

> 6

My Output

> 5

### Screenshots

My code was accepted but wrong with my testcase
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/146845593/b5861a68-0038-49f0-b296-6d905ca1955a)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
