### ISSUE TITLE
Missing Test Case - 127. Word Ladder

### ISSUE THREAD

**Issue by bdoellinger** [LeetCode-Feedback/LeetCode-Feedback#1929]
#### Your LeetCode username

b_d

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language

#### Description of the bug

-only a minor bug concerning Python3 custom test cases- 
Consider two testcases

testcase 1:
"aaa"
"bbb"
["aaa","aab","abb","bbb"]

testcase 2:
'aaa'
'bbb'
['aaa','aab','abb','bbb']

In Python3 both notations are equivalent (for example "aaa"=='aaa' returns True and running the code in IDEs or leetcode playground, with the same two testcases, returns the same result).
Moreover both notations using 'aaa' or "aaa" can also be used for strings in the code definition.
However the notation in testcase 2 raises a false error when used in a custom test case.

#### Code you used for Submit/Run operation

```
# independent on code used, only dependent on notation in custom test cases
```

#### Language used for code

Python3

#### Expected behavior

Both notations should work, however testcase 2 raises false error:
'aaa' is not a valid value of type string

When checking for type errors in custom test cases, both " and ' should be considered for valid string definitions.

**Comment by lc-kay** [comment]
Hi @bdoellinger 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@bdoellinger Thank you for your time. After reviewing your report, we concluded it to be invalid. We strictly conform to JSON format and ' isn't valid for string definitions in JSON interface.
