### ISSUE TITLE
Jump game has integer overflow

### ISSUE THREAD

**Issue by AnilRedshift** [LeetCode-Feedback/LeetCode-Feedback#193]
**What kind of the bug**
- [ X] problem
- [ ] solution
- [ ] language

**Describe the bug**
Given the following test case: [1,1,2147483647, 0,0]
When you run "run code", the expected answer is blank. (presumably the solution has an integer overflow bug).

Also, this should probably be a given test case.

**what language is your code written in**
C++

**The code you submit/run**
```
bool canJump(int* nums, int numsSize){
    int farthestIndex = 0;
    for (int i = 0; i < numsSize; ++i) {
        if (i > farthestIndex) {
            return false;
        }
        const int num = nums[i];
        
        // Guard against overflow
        
        if ((numsSize - i) < num) {
            return true;
        }
        
        
        if (num + i > farthestIndex) {
            farthestIndex = num + i;
        }
    }
    return true;
}
```

**Expected behavior**
This should return true for the given input, however it looks like the leetcode solution crashes

**Comment by CooperCooperCooper** [comment]
Hi @AnilRedshift,
Thank you for reaching out to us. I've relayed your feedback to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @AnilRedshift,
Thank you for your time. We've updated the problem based on your feedback. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user verification, and this issue to claim the valid contribution reward.
