### ISSUE TITLE
127. Word Ladder - Missing test case

### ISSUE THREAD

**Issue by daqingwax** [LeetCode-Feedback/LeetCode-Feedback#1930]
#### Your LeetCode username

daqingwax

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

It is missing a test case. My code was accepted but apparently it is missing this test case as i can see in the individual test, it expects an output of 0, but my program outputs 2 (which is wrong).
"a"
"z"
["b"]

#### Code you used for Submit/Run operation

```
class Solution {
    public int ladderLength(String beginWord, String endWord, List<String> wordList) {
        int n = beginWord.length();
        Map<String, List<Integer>>[] wordMap = new Map[n];
        for(int i = 0; i < n; i++) wordMap[i] = new HashMap<>();
        int nn = wordList.size();
        if(n == 1){
            if(nn >= 1) return(2);
            else return(0);
        }
        if(!wordList.contains(endWord)) return(0);
        wordList.add(beginWord);
        //wordList.add(endWord);
        boolean[] usedMap = new boolean[nn + 1];
        for(int i = 0; i < nn + 1; i++){
            String word = wordList.get(i);
            for(int j = 0; j < n; j++){
                String newStr = word.substring(0, j) + word.substring(j + 1, n);
                wordMap[j].putIfAbsent(newStr, new ArrayList<>());
                wordMap[j].get(newStr).add(i);
            }
        }
        Queue<String> q = new LinkedList<>();
        q.offer(beginWord);
        usedMap[nn] = true;
        int step = 1;
        while(!q.isEmpty()){
            int sz = q.size();
            //System.out.println(q);
            for(int i = 0; i < sz; i++){
                String str = q.poll();
                if(str.equals(endWord)) return(step);
                for(int j = 0; j < n; j++){
                    String newStr = str.substring(0, j) + str.substring(j + 1, n);
                    for(int wi: wordMap[j].get(newStr)){
                        if(!usedMap[wi]){
                            q.offer(wordList.get(wi));
                            usedMap[wi] = true;
                        }
                    }
                }
            }
            step++;
        }
        return(0);
    }
}
```

#### Language used for code

java

#### Expected behavior

It is missing a test case. My code was accepted but apparently it is missing this test case as i can see in the individual test, it expects an output of 0, but my program outputs 2 (which is wrong).
"a"
"z"
["b"]

#### Screenshots

![image](https://user-images.githubusercontent.com/71051492/104093046-ffaa9800-5255-11eb-868c-26326285269c.png)
![image](https://user-images.githubusercontent.com/71051492/104093052-0a652d00-5256-11eb-85a7-6ea1a94bec80.png)

#### Additional context

Add this test case.

**Comment by lc-kay** [comment]
Hi @daqingwax 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @daqingwax 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
