### ISSUE TITLE
Missing Test Case - 2288. Apply Discount to Prices

### ISSUE THREAD

**Issue by Kroogate** [LeetCode-Feedback/LeetCode-Feedback#19303]
### LeetCode Username
sobremi

###  Problem number, title, and link
[2288. Apply Discount to Prices](https://leetcode.com/problems/apply-discount-to-prices/)

###  Category of the bug
Incorrect test Case

### Description of the bug
leetcode is outputting a separate and i believe incorrect answer than my code returns in vs code when tested with same input

### Language used for code
python 

### Code used for Submit/Run operation
```
class Solution(object):
    def discountPrices(self, sentence, discount):
        """
        :type sentence: str
        :type discount: int
        :rtype: str
        """
        
        splits = sentence.split(" ")
        discount = discount / 100
        
        for i, word in enumerate(splits):
              pastFirst = word[1:]
              if not word.startswith("$") or not pastFirst.isnumeric():
                    continue
              
              discounted = int(pastFirst) * (1-discount)
              word = "${:.2f}".format(discounted)
              splits[i] = word
              
        return " ".join(splits)
```

### Expected behavior
returned value is correct and in line with what leetcode expects

### Screenshots
code used:
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/124523268/2bf3b5c7-9764-4ff3-a244-3748a62a6ff9)

output in vscode :
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/124523268/65b7a407-e8f1-4c40-a515-7b15803a8352)

output in leetcode:
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/124523268/243ccbe2-cdaf-4ca5-a1df-813d78753b20)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

Please ask your question in the discussion forum.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
