### ISSUE TITLE
Missing Test Case - 197. Rising Temperature

### ISSUE THREAD

**Issue by iamnidhisha** [LeetCode-Feedback/LeetCode-Feedback#19329]
![Screenshot (99)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/125153381/edfb6c1f-d8b6-499d-90a4-7957e33effa2)

### Category of the bug
- [ ] Problem description
- [x] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Language used for code

MS SQL SERVER

### Code used for Submit/Run operation

```
select *,LEAD(id) over (order by recorddate) nextRowId  into #t from [Weather] order by recordDate asc


select t.id,t.recordDate,t.temperature,t.nextRowId,t2.recordDate nextRecordDate,t2.temperature nextTemperature into #temp from #t t
left join #t t2 on t2.id=t.nextRowId


select nextRowId id from #temp where DATEDIFF(DAY,recordDate,nextRecordDate)=1 and (nextTemperature>temperature)

```

### Screenshots

![Screenshot (100)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/125153381/29e476f7-7419-4599-bd9d-55edc0314db8)
![Screenshot (101)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/125153381/9c33680d-ca0f-48f5-8f0a-74f0fe1318ed)

**Comment by iamnidhisha** [comment]
I think my solution is correct but when i run this code for submit my solution on leetcode showing error why ?

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

Please ask your question in the discussion forum.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
