### ISSUE TITLE
Missing Test Case - 1719. Number Of Ways To Reconstruct A Tree

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#1932]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution is accepted but fails on the following test case:
[[5, 7], [11, 12], [2, 9], [8, 10], [1, 4], [3, 6]]

#### Code you used for Submit/Run operation

```
	class Solution {
		public int checkWays(int[][] pairs) {
			int m = pairs.length;
			int n = 501;
			int[] deg = new int[n];
			for(int[] p : pairs){
				deg[p[0]]++;
				deg[p[1]]++;
			}
			boolean[][] g = new boolean[n][n];
			for(int[] p : pairs){
				g[p[0]][p[1]] = g[p[1]][p[0]] = true;
			}

			int[][] di = new int[n][];
			for(int i = 0;i < n;i++){
				di[i] = new int[]{deg[i], i};
			}
			Arrays.sort(di, (x, y) -> {
				if (x[0] != y[0]) return -(x[0] - y[0]);
				return x[1] - y[1];
			});

			int[] par = new int[n];
			Arrays.fill(par, -1);
			for(int i = 1;i < n;i++){
				for(int j = i-1;j >= 0;j--){
					if(g[di[j][1]][di[i][1]]){
						par[di[i][1]] = di[j][1];
						break;
					}
				}
			}

			boolean[][] h = new boolean[n][n];
			for(int i = 0;i < n;i++){
				for(int j = par[i];j != -1;j = par[j]){
					h[i][j] = h[j][i] = true;
				}
			}

			for(int i = 0;i < n;i++){
				if(!Arrays.equals(g[i], h[i])){
					return 0;
				}
			}

			Arrays.sort(di, (x, y) -> {
				if (x[0] != y[0]) return -(x[0] - y[0]);
				return -(x[1] - y[1]);
			});

			int[] par2 = new int[n];
			Arrays.fill(par2, -1);
			for(int i = 1;i < n;i++){
				for(int j = i-1;j >= 0;j--){
					if(g[di[j][1]][di[i][1]]){
						par2[di[i][1]] = di[j][1];
						break;
					}
				}
			}
			return Arrays.equals(par, par2) ? 1 : 2;
		}
	}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/104102897-46f05300-526d-11eb-80d3-823253301de4.png)

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
