### ISSUE TITLE
Missing Test Case - 2981. Find Longest Special Substring That Occurs Thrice I

### ISSUE THREAD

**Issue by deep3072** [LeetCode-Feedback/LeetCode-Feedback#19320]
### LeetCode Username
deep3072

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
A solution is accepted but fails on the following test case:
"jinhhhtttttttefffffjjjjjjjjjfffffjjjjjjjjjqvvvvvvg"

### Language used for code
C++

### Code used for Submit/Run operation

```
class Solution 
{
        public:
        int maximumLength(string s) 
        {
                int n = s.size();
                // int mx = 0;
                
                vector<vector<int>>adj(26);
                for(int i=0;i<n;)
                {
                        char ch = s[i];
                        int cnt = 0;
                        while(i<n && s[i] == ch)
                        {
                                cnt++;
                                i++;
                        }
                        adj[ch-'a'].push_back(cnt);
                }
                int mx = -1;
                for(int i=0;i<26;i++)
                {
                        int len = adj[i].size();
                        if(len == 0)
                                continue;
                        sort(adj[i].begin(), adj[i].end(), greater<>());
               

                        int f = adj[i][0];
                        if(len == 1)
                        {
                                mx = max(mx, f-2);
                                continue;
                        }
                        int s = adj[i][1];
                        if(len == 2)
                        {
                                if(f-s >= 2)
                                        mx = max(mx, f-2);
                                else
                                        mx = max(mx, f-1);
                                continue;
                                
                        }
                        int t = adj[i][2];
                        if(f == s && s == t)
                                mx = max(mx, f);
                        else if(f == s && s-t == 1)
                                mx = max(mx, f-1);
                        else if(f-s == 1)
                                mx = max(mx, f-1);
                        else
                                mx = max(mx, f-2);
                }
                if(mx == 0)
                        mx = -1;
                return mx;
        }   
};

```

### Expected behavior

The solution should not be accepted since it fails on the test case

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/62668186/33e9ae7f-1801-4c7d-bf18-28eb938c6bd1)

### Additional context

Testcase: "jinhhhtttttttefffffjjjjjjjjjfffffjjjjjjjjjqvvvvvvg"
Expected: 8
Output: 7

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
