### ISSUE TITLE
Missing Test Case - 1295. Find Numbers with Even Number of Digits

### ISSUE THREAD

**Issue by naziya2017** [LeetCode-Feedback/LeetCode-Feedback#19336]
### Category of the bug

- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Code used for Submit/Run operation

```class Solution {
public:
    int findNumbers(vector<int>& nums) {
        int ans=0;
        for(int num:nums){
            if((num>9&&num<99)||(num>999&&num<=9999)||(num>99999&&num<=999999))
            ans++;
        }
        return ans;
    }
};
```

### Expected behavior
int this problem 105 testcases are available and 1 case is missing where number is 99 and it is even digit number but it is getting accepted although if we do not check that condition

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/144229685/97d4754f-49ef-4953-a523-0dc8a00844d5
![Screenshot 2024-01-13 131709](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/144229685/e83a496f-d497-40c7-84b5-6b290f06e6d9)
)

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
