### ISSUE TITLE
Missing Test Case - 108. Convert Sorted Array to Binary Search Tree

### ISSUE THREAD

**Issue by maddy1397** [LeetCode-Feedback/LeetCode-Feedback#1933]
#### Your LeetCode username
madhavg1310

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- Issue

#### Description of the bug
My Solution is accepted when I submit my code but when I try running the same code for the default test case, it give's an error.

#### Code you used for Submit/Run operation

```

class Solution {
    public TreeNode sortedArrayToBST(int[] nums) {
        if (nums.length == 0) {
        return null;
    }
        TreeNode a = helper(nums, 0 ,nums.length-1 );
        return a;
    }
    public TreeNode helper(int[] arr, int start, int end){
        if(start> end){
            return null;
        }
        
        int mid = start + (end-start)/2;
        TreeNode node = new TreeNode(arr[mid]);
        
        node.left = helper(arr, start, mid-1);
        node.right = helper(arr, mid+1, end);
        
        return node;
        
    }
}
```

#### Language used for code
java

#### Expected behavior
The default test case should pass

#### Screenshots
![image](https://user-images.githubusercontent.com/17475816/104103590-f60e4800-52c8-11eb-87a4-af30166e7d77.png)

**Comment by lc-kay** [comment]
@maddy1397 When I tried to reproduce the issue you are stating, I am receiving the same results as your screenshot. In both submit and run code, the code was accepted and there is no error. Please explain what you mean by "it give's an error." Thank you!

**Comment by maddy1397** [comment]
@lc-kay , My solution is also accepted but when I just compile and run the accepted solution just for the sample test case, the actual and expected output is different as visible in the screenshot as well. Does this difference mean there are multiple solutions to this problem?

**Comment by lc-kay** [comment]
@maddy1397 There are multiple solutions for some of the sorted arrays, particularly some of the even-length arrays.
