### ISSUE TITLE
Mistake in Editorial of 1347. Minimum Number of Steps to Make Two Strings Anagram

### ISSUE THREAD

**Issue by Hr1t1k** [LeetCode-Feedback/LeetCode-Feedback#19335]
### LeetCode Username

Hritik__k

### Problem number, title, and link

[1347. Minimum Number of Steps to Make Two Strings Anagram](https://leetcode.com/problems/minimum-number-of-steps-to-make-two-strings-anagram/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
-  Editorial
- [ ] Programming language support

### Description of the bug

In the editorial , inside the algorithm part , part b of 2nd point is "**Decerement** the frequency of character s[i] in the array count." 
Here it should be **Decrement**  instead of Decerement.

### Screenshots

![lc mistake 13-01-24](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/52287344/8f8489e5-6181-445b-a043-1f6ce7ceb442)

**Comment by LC-Pam** [comment]
Duplicated on Zendesk Ticket.
