### ISSUE TITLE
Wrong Test Case - 4. Valid Sudoku

### ISSUE THREAD

**Issue by RajeshCodingBlck** [LeetCode-Feedback/LeetCode-Feedback#19349]
### LeetCode Username
https://leetcode.com/rajeshguptamc102/

### Problem number, title, and link
36 , Valid Sudoku , https://leetcode.com/problems/valid-sudoku/

### Category of the bug
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### Code used for Submit/Run operation

```
class Solution {
     public static void display(char board[][]){
         for(int i=0;i<board.length;i++){
             for(int j=0;j<board[0].length;j++){
                 System.out.print(board[i][j]+" ");
             }
             System.out.println();
         }
     }   
    public static boolean isvalid(char board[][],int i,int j,char val){

        for(int t=0;t<board[0].length;t++){
            if(board[i][t]==val)
                return false;
        }
        
        for(int t=0;t<board.length;t++){
            if(board[t][j]==val)
                return false;
        }
        int row=3*(i/3);
        int col=3*(j/3);
        for(int r=row;r<=row+2;r++){
            for(int c=col;c<=col+2;c++){
                if(board[r][c]==val)
                    return false;
            }
        }
        
        return true;
    }
    
    public static boolean solve_suduko(char board[][],int i,int j){
        if(i==board.length){
            // display(board);
            // System.out.println("\n\nhiii");
             return true;
        }
           
        
        int ni=0;
        int nj=0;
        if(j==board[0].length-1){
            ni=i+1;
            nj=0;
        }
        else{
            ni=i;
            nj=j+1;
        }
        // System.out.print(ni+","+nj+" ");
        if(board[i][j]!='.'){
           return solve_suduko(board,ni,nj);
            
        }
        else{
            for(char k='0'+1;k<='0'+9;k++){
                
                if(isvalid(board,i,j,k)){
                    board[i][j]=k;
                    // System.out.println(k+" ");
                    boolean ans=solve_suduko(board,ni,nj);
                    if(ans){
                        return true;
                    }
                    
                        board[i][j]='.';
                    
                    
                }
            }
            
        }
        // System.out.println("hlw");
        return false;
    }
    public boolean isValidSudoku(char[][] board) {
        boolean ans=solve_suduko(board,0,0);
        // System.out.println(ans);
        return ans;
    }
}
```

### Expected behavior
 Output Should come ;- False

### Screenshots
https://drive.google.com/file/d/1YpIA5H_CCGhf5gpoWKmN9VJCerMbFe_C/view?usp=sharing

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.
Details regarding the missing test case.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by RajeshCodingBlck** [comment]
Submission Link :- https://leetcode.com/submissions/detail/1144863339/
Test case -4

**Comment by RajeshCodingBlck** [comment]
Respected Leetcode Team,

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
