### ISSUE TITLE
75. 颜色分类更改进阶要求

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#1934]
**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
第 75 题的进阶要求的第一点是不使用代码库自带的排序函数。如果这都是进阶要求，这道题的常规做法就可以是直接调用排序函数，一行代码就结束，这样就没有任何意义了。这道题无论是手动实现排序，还是使用 O(n) 的做法，都比直接调用排序函数强。
因此建议将进阶要求的第一点移到进阶要求的前面，常规要求即为不可以使用代码库自带的排序函数。

**你使用的语言**
Java

**你提交或者运行的代码**

**期望行为**
进阶要求第一点变成常规要求，中文描述和英语描述需要同步更新。

**屏幕截图**

**额外的上下文**

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前题目英文进阶要求已添加， 中文描述已同步更新。

**Comment by stormsunshine** [comment]
这道题的题目描述并没有更新。我反馈的是，将进阶要求的第一条（即不使用自带的排序函数）作为常规要求。
