### ISSUE TITLE
Enhancement for 'In-Place Array Operations Introduction' Article

### ISSUE THREAD

**Issue by pechinkin** [LeetCode-Feedback/LeetCode-Feedback#19343]
### LeetCode Username

pechinkin
https://leetcode.com/pechinkin/
### Problem number, title, and link

In-Place Array Operations Introduction https://leetcode.com/explore/learn/card/fun-with-arrays/511/in-place-operations/3257/

### Category of the bug
- [ ] Problem description
- [x] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug

This is a suggestion for code to execute faster.
The in-place implementation for squareEven(...) function can be modified. In the `for` cycle we can use `i += 2` instead of `i++`. 
Thus, we don't need `if (i % 2 == 0)` condition, because `i` always would be even (`i = 0, 2, 4...`). With that, in `for` cycle we would have 2 times less laps.

### Language used for code

Java

### Code used for Submit/Run operation

```
public int[] squareEven(int[] array, int length) {

  // Check for edge cases.
  if (array == null) {
    return array;
  }

  // Iterate through the original array.
  for(int i = 0; i < length; i += 2) {

    // Index is an even number, so we need to square the element
    // and replace the original value in the Array.
      array[i] *= array[i];
    // Notice how we don't need to do *anything* for the odd indexes? :-)
  }

  // We just return the original array. Some problems on leetcode require you
  // to return it, and other's dont.
  return array;
}
```

### Screenshots

<img width="1512" alt="Screenshot 2024-01-13 at 14 27 25" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/124191811/d9756c63-d890-4860-ab33-676b765a84ed">

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
