### ISSUE TITLE
Missing Test Case - 27. Remove Element

### ISSUE THREAD

**Issue by sjia** [LeetCode-Feedback/LeetCode-Feedback#19348]
### LeetCode Username
sjia

### Problem number, title, and link
[27. 移除元素](https://leetcode.cn/problems/remove-element/)

### Category of the bug
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### Description of the bug
预期结果有问题

### Language used for code
python

### Expected behavior
示例： 允许输出可以是不同顺序
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/17916946/a594d700-1956-4b71-a07e-3cf837630510)
Bug：
同样的输入，测试用例的返回和示例2中的预期结果不同，并且不允许返回结果的值顺序不同， 
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/17916946/5192a724-95a9-490d-8fc1-8fc99105c3b1)
清修改测试用例中的预期结果判定

**Comment by amcones-lc** [comment]
您好，在与相关团队核实后：***不处理***（本题返回数组元素可以是任何顺序）。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
