### ISSUE TITLE
Test case and description doesn't match in problem 1075

### ISSUE THREAD

**Issue by Utshas** [LeetCode-Feedback/LeetCode-Feedback#19347]
### LeetCode Username
Utshas

### Problem number, title, and link
[1075. Project Employees I](https://leetcode.com/problems/project-employees-i/)

### Category of the bug
- [x] Problem description
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### Language used for code
javascript

### Code used for Submit/Run operation

```
select project_id, round((sum(experience_years)*1.0/count(project_id)),2) as average_years
from Project join Employee
 on (Project.employee_id = Employee.employee_id)
 group by project_id;
```

### Expected behavior
according to the problem statement, `It's guaranteed that experience_years is not NULL.` So, we can assume that it should not be null. But in my case, the 8th test case had the null value in experience_years. So, clearly, the description is confusing and it doesn't match with the test case. Please check!

**Comment by KimYu54** [comment]
Hi, I added a condition to make sure the experience_years is not null according to the question, assuming that the employee is not working for the project cuz there's no experience.

**Code Submitted**
`SELECT project_id, ROUND(SUM(experience_years)/COUNT(p.employee_id), 2) AS average_years
FROM project p
INNER JOIN employee e
ON p.employee_id = e.employee_id
AND experience_years IS NOT NULL
GROUP BY project_id
`

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
