### ISSUE TITLE
Missing Test Case

### ISSUE THREAD

**Issue by AdityaKumar-Git** [LeetCode-Feedback/LeetCode-Feedback#19351]
### LeetCode Username
aditya_c0des

### Category of the bug
- Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug
Missing test Case

### Testcase
Input: "aabbcccc"
output: true
expected: false
status: accepted

### Language used for code
C++

### Code used for Submit/Run operation

```
class Solution {
public:
    bool equalFrequency(string w) {
        unordered_map<char,int> m;
        for(auto i: w){
            m[i]++;
        }
        map<int,int> mp;
        for(auto i: m){
            mp[i.second]++;
        }
        auto i=mp.begin();
        if(mp.size()==1){
            int f=i->first;
            if(f==1 || i->second==1){
                return true;
            }
            return false;
        }
        auto j=next(i);
        if(mp.size()==2 && ((j->first-i->first==1 && j->second==1) || (i->first-i->second==0))){
            return true;
        }
        return false;
    }
};
```

### Expected behavior
submission fail (wrong answer)

### Screenshots

![Screenshot (49)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/154753771/f1a5b8dd-f802-43dd-b295-570d3859d413)

**Comment by AdityaKumar-Git** [comment]
[2423. Remove Letter To Equalize Frequency] (https://leetcode.com/problems/remove-letter-to-equalize-frequency/)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
