### ISSUE TITLE
277. 搜寻名人更改题目描述

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#1935]
**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
第 277 题的题目描述是，需要在（渐近意义上）尽可能少的问题内来确定这位 “名人” 是谁（或者确定这里没有 “名人”）。实际上，即使问题数量并不是最少，也可以提交通过。因此建议将尽可能少的问题作为进阶要求，常规要求中去掉尽可能少的问题的要求。
进阶要求可以是：你是否可以使用（渐近意义上）尽可能少的问题内来确定这位 “名人” 是谁（或者确定这里没有 “名人”）？至少需要多少个问题可以确定这位 “名人” 是谁？
具体描述需要请官方决定，中文描述和英语描述需要同步更新。

**你使用的语言**
Java

**你提交或者运行的代码**

**期望行为**
更改题目描述，中文描述和英语描述需要同步更新。

**屏幕截图**

**额外的上下文**

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前题目英文进阶要求已添加， 中文描述已同步更新。
