### ISSUE TITLE
Missing Test Case - 1657. Determine if Two Strings Are Close

### ISSUE THREAD

**Issue by swastimishra80** [LeetCode-Feedback/LeetCode-Feedback#19361]
### LeetCode Username

gaguli

### Problem number, title, and link

1657. Determine if two strings are close. https://leetcode.com/problems/determine-if-two-strings-are-close/description/?envType=daily-question&envId=2024-01-14

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ *] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Code got accepted where it should have resulted in a runtime exception.

### Language used for code

Java

### Code used for Submit/Run operation

```
class Solution {
    public boolean closeStrings(String word1, String word2) {
        HashMap<Character, Integer> f1 = new HashMap<>();
        HashMap<Character, Integer> f2 = new HashMap<>();
        for(int i = 0; i < word1.length(); i++) {
            f1.put(word1.charAt(i), f1.getOrDefault(word1.charAt(i), 0) + 1);
        }
        for(int i = 0; i < word2.length(); i++) {
            if(!f1.containsKey(word2.charAt(i))) return false;
            f2.put(word2.charAt(i), f2.getOrDefault(word2.charAt(i), 0) + 1);
        }
        ArrayList<Integer> list1 = new ArrayList<>(f1.values());
        Collections.sort(list1);
        ArrayList<Integer> list2 = new ArrayList<>(f2.values());
        Collections.sort(list2);        
        //System.out.println(list1.get(0).equals(list2.get(0)));
        for(int i = 0; i < list1.size(); i++){
            if(!list1.get(i).equals(list2.get(i))) return false;
        }
        return true;
    }
}
```

### Expected behavior

The code submission was accepted where as it should have resulted in runtime error at line number 18. 

### Screenshots

![Screenshot from 2024-01-13 22-11-47](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/156565746/636067ed-445d-4207-8506-e06f1a0965e3)

### Additional context

The submitted code fails for this input - String1 - ac, String2 - c
![Uploading Screenshot from 2024-01-13 22-17-18.png…]()

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
