### ISSUE TITLE
Missing Test Case - 3008. Find Beautiful Indices in the Given Array II

### ISSUE THREAD

**Issue by CuteTN** [LeetCode-Feedback/LeetCode-Feedback#19367]
### LeetCode Username
CuteTN

### Problem number, title, and link
[3008. Find Beautiful Indices in the Given Array II](https://leetcode.com/problems/find-beautiful-indices-in-the-given-array-ii/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
My code got accepted for version 2, but wrong answer for version 1.

### Language used for code
JavaScript

### Code used for Submit/Run operation
```js
//#region KMP
class KMP {
  /**
   * Longest prefix suffix
   * @param {string} s
   * @returns {number[]}
   */
  static findLSP(s) {
    let cur = 0;
    let n = s.length;
    const result = Array(n).fill(0);

    for (let i = 1; i < n; i++) {
      while (cur && s[i] != s[cur]) cur = result[cur - 1];
      if (s[i] == s[cur]) cur++;
      else cur = 0;
      result[i] = cur;
    }

    return result;
  }

  /**
   * @param {string} needle
   * @param {string} haystack
   * @param {number[]} [lsp] Longest prefix suffix of the `needle`, generated by `findLSP` method if not given
   * @returns {number[]}
   */
  static findAllMatch(needle, haystack, lsp) {
    if (!lsp) lsp = KMP.findLSP(needle);

    let cur = 0;
    /** @type {number[]} */
    let result = [];
    let n = needle.length - 1;
    let m = haystack.length;

    for (let i = 0; i < m; i++) {
      while (cur && haystack[i] != needle[cur]) cur = lsp[cur - 1];
      if (haystack[i] == needle[cur]) cur++;
      if (cur > n) result.push(i - n);
    }

    return result;
  }
}
//#endregion

/**
 * @param {string} s
 * @param {string} a
 * @param {string} b
 * @param {number} k
 * @return {number[]}
 */
var beautifulIndices = function(s, a, b, k) {
  let lsp = KMP.findLSP(s);
  let ma = KMP.findAllMatch(a, s, lsp);
  let mb = KMP.findAllMatch(b, s, lsp);
  
  let n = ma.length;
  let m = mb.length;
  let ib = 0;
  let res = [];
  for (let ia = 0; ia < n; ++ia) {
    while (ib < m && ma[ia] - mb[ib] > k) ib++;
    if (ib == m) break;
    if (Math.abs(ma[ia] - mb[ib]) <= k) res.push(ma[ia]);
  }

  return res;
};
```

### Expected behavior
The code above used a wrong implementation of the KMP algorithm, which should not be accepted.
It failed for this testcase:
`s = "xxtxxuftxt", a = "tx", b = "x", k = 2`

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/52530644/e9f86f9c-ae35-41f9-af1e-091f05ff4d7c)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team
