### ISSUE TITLE
 Problem No 3 Add Two Numbers of LeetCode

### ISSUE THREAD

**Issue by HasnainAliT** [LeetCode-Feedback/LeetCode-Feedback#19373]
class Solution {
    public ListNode addTwoNumbers(ListNode l1, ListNode l2) {
        ListNode dummy = new ListNode(0);
        ListNode p = l1, q = l2, curr = dummy;
        int carry = 0;
        while (p != null || q != null) {
            int x = p != null ? p.val : 0;
            int y = q != null ? q.val : 0;
            int sum = x + y + carry;
            carry = sum / 10;
            curr.next = new ListNode(sum % 10);
            curr = curr.next;
            if (p != null)
                p = p.next;
            if (q != null)
                q = q.next;

        }
        if (carry > 0) {
            curr.next = new ListNode(carry);
        }
        return dummy.next;
    }
}

**Comment by Y-Rov** [comment]
Hello @HasnainAliT. Man, you know this repo is not for posting problem solutions?
