### ISSUE TITLE
Problem description - 1657. Determine if Two Strings Are Close

### ISSUE THREAD

**Issue by IliasaurCat** [LeetCode-Feedback/LeetCode-Feedback#19370]
### LeetCode Username

IliasaurCat

### Problem number, title, and link

[1657. Determine if Two Strings Are Close](https://leetcode.com/problems/determine-if-two-strings-are-close/)

### Category of the bug
- [X] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The string "Apply Operation 2: "" in the example 3 is heighlighted for some reason.

### Expected behavior

I assume it should be in the same style as the rest of the text.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/151400270/dbeb96e4-3606-46d0-9a43-07c714922a61)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
