### ISSUE TITLE
Test case quality - 127. Word Ladder

### ISSUE THREAD

**Issue by Ochirgarid** [LeetCode-Feedback/LeetCode-Feedback#1937]
#### Your LeetCode username

Garid

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

I implemented a BFS algorithm without creating an adjacent node map (named **all_combo_dict** in the solution) which is not fast enough to get accepted (time complexity: O(N* N * M)). But when I was trying to figure out the problem I started my BFS from the **endWord** without changing anything else, therefore my solution got accepted.
I think the overall test case quality have be get improved concerning the slow BFS solutions could get accepted by start from the endWord like mine.

#### Code you used for Submit/Run operation

``` python
# 127.Word Ladder
class Solution:
    def ladderLength(self, beginWord: str, endWord: str, wordList: List[str]) -> int:
        if endWord not in wordList: return 0

        def cntDiff(x, y):
            d = 0
            for ix, iy in zip(x, y):
                if d == 2: return 2
                if ix != iy:
                    d += 1
            return d

        cur = [endWord]
        used = {}
        used[endWord] = True

        ans = 1
        while cur:
            tmp = []
            for cur_word in cur:
                if cntDiff(beginWord, cur_word) == 1: return ans + 1
                for word in wordList:
                    if word in used: continue
                    if cntDiff(word, cur_word) != 1: continue
                    tmp.append(word)
                    used[word] = 1
            ans += 1
            cur = tmp
            
        return 0
```

#### Language used for code

Python3

#### Expected behavior

This solution should had have **Time Limit Exceeded** not Accepted.

#### Additional context

On the below I added the solution that got the **Time Limit Exceeded** error that I only changed the **endWord** and **beginWord** for the BFS.

```python
# 127.Word Ladder
class Solution:
    def ladderLength(self, beginWord: str, endWord: str, wordList: List[str]) -> int:
        if endWord not in wordList: return 0

        def cntDiff(x, y):
            d = 0
            for ix, iy in zip(x, y):
                if d == 2: return 2
                if ix != iy:
                    d += 1
            return d

        cur = [beginWord]
        used = {}
        used[beginWord] = True

        ans = 1
        while cur:
            tmp = []
            for cur_word in cur:
                if cntDiff(endWord, cur_word) == 1: return ans + 1
                for word in wordList:
                    if word in used: continue
                    if cntDiff(word, cur_word) != 1: continue
                    tmp.append(word)
                    used[word] = 1
            ans += 1
            cur = tmp
            
        return 0
```

**Comment by lc-kay** [comment]
@Ochirgarid To quality for rewards, can you please provide a test case that will fail the first solution?

**Comment by Ochirgarid** [comment]
I created couple of test cases. When I try the test cases separately  it gets Time Limit Exceeded most of the times. **But** 2 test cases together it is guaranteed exceed the time limit.  

The test case was quite big for the comment so I pasted it [here](https://gist.github.com/Ochirgarid/74532745afa30861bb31c0202903792e#file-127-word-ladder-test-txt) .
You can find the test case generator that used to create it in next to it.

**Comment by lc-kay** [comment]
Hi @Ochirgarid 
Thank you. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Ochirgarid 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
