### ISSUE TITLE
测试样例缺少

### ISSUE THREAD

**Issue by boxbox2** [LeetCode-Feedback/LeetCode-Feedback#19379]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

### LeetCode 用户名
 Move

### 问题号码、标题和链接

[100165. 找出数组中的美丽下标 I](https://leetcode.cn/problems/find-beautiful-indices-in-the-given-array-i/) 

### Bug 类型
- [ ] 问题描述
- [ ] 示例
- [ ] 问题限制
- [ ] 问题提示
- [ ] 不正确或缺少“相关标签”
- [ ] 不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*
- [x] 缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*
- [ ] 力扣官方题解
- [ ] 编程语言支持

### 描述

在380周赛中，我通过了第二题没通过第四题，第四题提示有错误样例不给通过。我将第四题错误样例放入第二题中，发现是第二题样例缺少导致通过

### 你使用的语言

Go

### 你提交或者运行的代码

```
func getNext(next []int,s string){
    j := 0
    next[0] = j
    for i := 1; i < len(s); i++{
        for j > 0 && s[i] != s[j]{

            j = next[j-1]
        }
        if s[i] == s[j]{
            next[i] = next[j]
        }
        next[i] = j
    }
}

func strStr(haystack string, needle string,p []int)(int,[]int){
    n := len(needle)
    if n == 0{
        return 0,p
    }
    j := 0
    next := make([]int,n)

    getNext(next,needle)
        fmt.Println(next)
    for i := 0; i < len(haystack); i++{
        for j > 0 && haystack[i] != needle[j]{
            j = next[j-1]
        }
        if haystack[i] == needle[j]{
            j++
        }
        if j == n{
            p = append(p,i-n+1)
            j = 0
        }
    }
    return -1,p
}
func beautifulIndices(s string, a string, b string, k int) []int {
    p,q,res := []int{},[]int{},[]int{}
    _,p = strStr(s,a,p)
    _,q = strStr(s,b,q)
    if len(p) == 0 || len(q) == 0{
        return res
    }
    j, m := 0, len(q)
	for _, i := range p {
		for j < m && q[j] < i-k {
			j++
		}
		if j < m && abs(q[j] - i) <= k {
			res = append(res, i)
		}
	}

    return res
}

func appendNoexit(arr []int,p int)[]int{
    for _,e := range arr{
        if p == e{
            return arr
        }
    }
    return append(arr,p)
}

func abs(a int)int{
    if a < 0{
        return -a
    }
    return a
}
```

### 期望行为

希望第二题添加样例。

### 屏幕截图

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/56194614/9c86e8f2-973b-45f4-8c38-872a6a07879a)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code Accepted submission link you submitted led to the observed result.
https://leetcode.com/submissions/detail/1184343017/

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team
