### ISSUE TITLE
Missing Test Case - 26. Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by drucewihlis** [LeetCode-Feedback/LeetCode-Feedback#19372]
### LeetCode Username

drucewihlis

### Problem number, title, and link

26. Remove Duplicates from Sorted Array https://leetcode.com/problems/remove-duplicates-from-sorted-array/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
Test case with empty input list is needed.

### Language used for code
Python3

### Code used for Submit/Run operation

```
class Solution:
    def removeDuplicates(self, nums: List[int]) -> int:
        i = 1
        for j in range(1, len(nums)):
            if nums[j] != nums[j - 1]:
                nums[i] = nums[j]
                i += 1
        k = i
        return k
```

### Expected behavior

Code above is accepted for the task, but it does not work properly when nums=[] . It returns k=1, but expected k=0. 

So, test case with nums=[] and expected k=0 needed.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/62725191/13971018-1b0a-4ec0-8f45-c48e8451cc77)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team
