### ISSUE TITLE
Missing Test Case - 3008. Find Beautiful Indices in the Given Array II

### ISSUE THREAD

**Issue by yumkam** [LeetCode-Feedback/LeetCode-Feedback#19390]
### Problem number, title, and link

3008. Find Beautiful Indices in the Given Array II https://leetcode.com/problems/find-beautiful-indices-in-the-given-array-ii/submissions/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Code was accepted, but fails testcases below (WA):
1.
```
"iucaadaehtbaaajaaabhaccaijaraaarbaaaaaaaadfabjadbiagaaaatbjibbaaalkeanbagaaaiacacaaaggaabaaaafdchaab"
"aaaelakaaaaeofaiapaajaapaadadqfaabicddiebaaeaagaaabahdadaaaaaacgbaaaeaaeagjgahababneaacnafafhaaaabaa"
"a"
10
```
2.
```
"aaaasafsaelfigaactdrhalaajaaahgaehaqamaaihafaaaahaaieaaaatyalkeaaeallaaaraaalahammejaaalbaaabaaa"
"iadmamaaoaaaaagaaaaaadanjaqspaataakakagsaagaqcptabiaadqihaacaaaflahaalghackgaaalaaaakamaafnbapaa"
"a"
10
```

### Language used for code
C++

### Code used for Submit/Run operation

```c++
// code not mine, seen in /ranking/
class StringHash {
public:
    vector<long long>ps1,ps2;
    long long Q1 = 271, Q2 = 277, M1 = 1000000007, M2 = 998244353;
    StringHash(string s) {
        ps1 = vector<long long>(s.size()+1); ps2 = vector<long long>(s.size()+1);
        for (int i = 1; i <= s.size(); i++) {
            long long c = s[i-1] + 1;
            ps1[i] = ((Q1 * ps1[i-1]) + c)%M1;
            ps2[i] = ((Q2 * ps2[i-1]) + c)%M2;
        }
    }
    long long int powxy(long long int x, long long int y, long long M) {
        if (y == 0) return 1;
        if (y%2 == 1) return (x*powxy(x, y-1, M))%M;
        long long int t = powxy(x, y/2, M);
        return (t*t)%M;
    }
    long long substrHash1(int firstIndex, int lastIndex) {
        long long rem = (powxy(Q1,lastIndex-firstIndex+1,M1) * ps1[firstIndex])%M1;
        return (ps1[lastIndex+1] - rem + M1)%M1;
    }
    long long substrHash2(int firstIndex, int lastIndex) {
        long long rem = (powxy(Q2,lastIndex-firstIndex+1,M2) * ps2[firstIndex])%M2;
        return (ps2[lastIndex+1] - rem + M2)%M2;
    }
    pair<long long, long long> substrHash(int firstIndex, int lastIndex) {
        return {substrHash1(firstIndex, lastIndex), substrHash2(firstIndex, lastIndex)};
    }
};


class Solution {
public:
    vector<int> beautifulIndices(string s, string a, string b, int k) {
        StringHash SH = StringHash(s);
        StringHash A = StringHash(a);
        StringHash B = StringHash(b);
        auto at = A.substrHash(0,a.size() - 1);
        auto bt = B.substrHash(0,b.size() - 1);
        vector<int>js;
        vector<int>is;
        
        if (b.size() <= s.size()) {
            for (int i = 0; i < s.size() - b.size() + 1; i++) {
                auto nowb = SH.substrHash(i,i + b.size() - 1);
                if (nowb == bt) js.push_back(i);
            }
        }
        
        if (a.size() <= s.size()) {
            for (int i = 0; i < s.size() - a.size() + 1; i++) {
                auto nowa = SH.substrHash(i, i + a.size() - 1);
                if (nowa == at) is.push_back(i);
            }
        }
        
        
        //cout << "here" << endl;
        
        //for (auto i : is) {cout << i << ",";} cout << endl;
        //for (auto i : js) {cout << i << ",";} cout << endl;
        
        vector<int>ans;
        for (auto i : is) {
            int idx = lower_bound(js.begin(), js.end(), i) - js.begin();
            bool good = false;
            if (idx < js.size() && js[idx] - i <= k) good = true;
            if (idx > 0 && abs(js[idx - 1] - i) <= k) good = true;
            if (good) ans.push_back(i);
        }
        return ans;
    }
};
```

### Expected behavior

Broken code should not be accepted.

### Additional context

Polyhashes with fixed parameters are vulnerable to trivially found collisions.
(Proper solution should use KMP or z-function, or properly randomize hash parameters, e.g. fixed large prime modulo with random base are not as easy to break).

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
