### ISSUE TITLE
1395. 统计作战单位数增加数据规模

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#1939]
**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
第 1395 题作为中等题，应该对数据规模有要求。现在的数据规模是数组长度 `n <= 200`，导致 O(n^3) 的暴力枚举的做法也可以通过，这就导致题目的难度显著下降了，甚至是简单题中的简单题。
建议将 `n` 的范围改成 `1 <= n <= 1000`，并增加一组或多组 `n` 的值较大的测试用例，其中必须包含 `n = 1000` 的测试用例，这样就要求时间复杂度为 O(n^2) 才能通过，才符合中等题的难度。

**你使用的语言**
Java

**你提交或者运行的代码**

**期望行为**
更新 `n` 的范围，并增加相应的测试用例。

**屏幕截图**

**额外的上下文**

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前该题已更新修复。
