### ISSUE TITLE
"474. Ones and Zeroes" has a lot of grammatical errors

### ISSUE THREAD

**Issue by sushsada** [LeetCode-Feedback/LeetCode-Feedback#194]
**What kind of the bug**
- [ X ] language

**Describe the bug**
It's extremely hand to figure out what the question asks for. Please have someone correct the language.
**what language is your code written in**
N/A
**The code you submit/run**
N/A

**Expected behavior**
N/A
**Screenshots**
N/A
**Additional context**
Here is the incorrect text:
```
In the computer world, use restricted resource you have to generate maximum benefit is what we always want to pursue.

For now, suppose you are a dominator of m 0s and n 1s respectively. On the other hand, there is an array with strings consisting of only 0s and 1s.

Now your task is to find the maximum number of strings that you can form with given m 0s and n 1s. Each 0 and 1 can be used at most once.
```

**Comment by CooperCooperCooper** [comment]
Hi @sushsada,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @sushsada,
Thank you for your time! We've used your feedback to update the problem statement. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.

**Comment by sushsada** [comment]
Awesome, much better now!
