### ISSUE TITLE
Missing Test Case - 197. Rising Temperature

### ISSUE THREAD

**Issue by adnansabbir** [LeetCode-Feedback/LeetCode-Feedback#19402]
### Problem number, title, and link
1. [197. Rising Temperature](https://leetcode.com/problems/rising-temperature/)

### Category of the bug
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

The problem asks to return IDs of the record where the temperature is greater than the previous date. So a simple assumption is to return all the IDs that fulfill this constraint. But the problem expects duplicates. See the example below

| id | recordDate | temperature |
| -- | ---------- | ----------- |
| 1  | 2015-01-02 | 16          |
| 2  | 2015-01-02 | 15          |
| 3  | 2015-01-03 | 20          |

Here for this test case, if the output is the below one, leetcode gives error
| id |
| -- |
| 3  |

Leetcode expects the output to be
| id |
| -- |
| 3  |
| 3  |

### Code used for Submit/Run operation

**Code that is getting accepted**
``` sql []
select w1.id
from Weather w1, Weather w2
where DATEDIFF(w1.recordDate, w2.recordDate) = 1 and w1.temperature > w2.temperature
```
**Code that should get accepted**
``` sql []
select distinct w1.id
from Weather w1, Weather w2
where DATEDIFF(w1.recordDate, w2.recordDate) = 1 and w1.temperature > w2.temperature
```

### Expected behavior
The output should have distinct values

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
