### ISSUE TITLE
Missing Test Case - 1723. Find Minimum Time to Finish All Jobs

### ISSUE THREAD

**Issue by haoliu1117** [LeetCode-Feedback/LeetCode-Feedback#1940]
#### Your LeetCode username

Hao_Liu_LA

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

I've wrote a naive DFS strategy and got accepted. However, I build a test case that my code can not pass.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    
    int ans;
    
    int minimumTimeRequired(vector<int>& jobs, int k) {
        ans = INT_MAX;
        sort(jobs.rbegin(), jobs.rend());
        // for (auto num:jobs) cout << num << " ";
        vector<int> times(k, 0);
        for (int i = 0; i < k; i++) times[i] = jobs[i];
        helper(jobs, times, k, k);
        return ans;
    }
    void helper(vector<int>& jobs, vector<int>& times, int k, int p) {
        if (p==jobs.size()) {
            int cur = times[0];
            for (auto t:times) cur = max(cur, t);
            ans = min(ans, cur);
            return;
        }
        for (int i = 0; i < k; i++) {
            if (times[i]+jobs[p]>=ans) continue;
            times[i] += jobs[p];
            helper(jobs, times, k, p+1);
            times[i] -= jobs[p];
        }
    }
};
```

#### Language used for code

C++

#### Expected behavior

This solution shall be a WA.

**Comment by haoliu1117** [comment]
```
[5,5,4,4,4]
2
```
My solution to this case is a no pass but my code got accepted.

**Comment by lc-kay** [comment]
Hi @haoliu1117 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @haoliu1117 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
