### ISSUE TITLE
Missing Test Case - 27. Remove Element

### ISSUE THREAD

**Issue by tredsused40** [LeetCode-Feedback/LeetCode-Feedback#19407]
### LeetCode Username

tredsused70

### Problem number, title, and link

27. Remove Element https://leetcode.com/problems/remove-element/

### Category of the bug
- [.] Programming language support

### Description of the bug

Checker of the problem is not working properly

### Language used for code

Python3

### Code used for Submit/Run operation

```
class Solution:
    def removeElement(self, nums: List[int], val: int) -> int:
        pos = 0
        for i in nums:
            if i != val:
                nums[pos] = i
                pos += 1
        if(pos == len(nums)):
            pos += 10000;
        print(pos)
        return pos
```

### Expected behavior

Code should get WA verdict on tests, where no elements have to be removed, because in that case return value is equal to length of nums + 10000, which is clearly not the expected nums length, but the code still gets "Accepted" verdict. For example nums = [3,2,2,3] the return value is 10004.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/75163817/573ee422-8d01-495b-a3e9-e8401a0c313a)

### Additional context

Something is wrong with ```assert k == expectedNums.length;```, code gets "Accepted" no matter what positive value is added in if.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
