### ISSUE TITLE
Missing Test case - 3006. Find Beautiful Indices in the Given Array I

### ISSUE THREAD

**Issue by mananbansal2002** [LeetCode-Feedback/LeetCode-Feedback#19416]
### LeetCode Username
1806manan

### Problem number, title, and link
3006. Find Beautiful Indices in the Given Array I   https://leetcode.com/problems/find-beautiful-indices-in-the-given-array-i/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
The code must fail at the max constraints ie corner case but its passing. and not giving TLE

### Language used for code
 C++ 

### Code used for Submit/Run operation

```
class Solution {
public:
    vector<int> beautifulIndices(string s, string a, string b, int k) {
        vector<int> result;
        int ut= s.size()-b.size();
        if(s.size()<a.size())
        return {};
        
        for(int i=0;i+a.size()<=s.size();i++) 
        if(s.substr(i, a.size())==a)
           if(s.size()>=b.size())
           {
              for(int j=max(0,i-k);j<=min(ut,i+k);j++)
              if(s.substr(j, b.length())==b) 
              {
                  result.push_back(i);
                  break;
              }
           }

    return result;
        
    }
};
```

### Expected behavior

TLE was supposed to be getting but its not getting it and instead code got passed at 56ms.

### Screenshots

need to GET TLE FOR the largest case of string s = "aaaa______" 10^5 times , a = "aaaaaaaaaa" , b = "bbbbbbbbbb" , k=100000
 
![WhatsApp Image 2024-01-15 at 22 11 09_36790be3](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/71920970/6cbfc77c-46b6-4c2e-8695-77df94904481)

But got passed 

![WhatsApp Image 2024-01-15 at 22 11 57_01c9ff19](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/71920970/b12b5156-1a5f-47a3-8cae-0c1a7b0228da)

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
