### ISSUE TITLE
Missing Test Case - 2225. Find Players With Zero or One Losses

### ISSUE THREAD

**Issue by tredsused40** [LeetCode-Feedback/LeetCode-Feedback#19417]
### LeetCode Username

tredsused70

### Problem number, title, and link

2225. Find Players With Zero or One Losses https://leetcode.com/problems/find-players-with-zero-or-one-losses/

### Category of the bug
- [.] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

Code that got "Accepted" verdict gets TLE on some testcases.

### Language used for code

C++

### Code used for Submit/Run operation

```
class Solution {
public:
    void mysort(vector<int> &vc) {
        int n = vc.size();
        int gap = n;
        while(gap) {
            for(int i = gap; i < n; i++) {
                int j = i - gap;
                while(j >= 0 && vc[j] > vc[j + gap]) {
                    swap(vc[j], vc[j + gap]);
                    j -= gap;
                }
            }
            gap /= 2;
        }
        return ;
    }
    vector<vector<int>> findWinners(vector<vector<int>>& matches) {
        map<int, int> mp;
        for(auto &i : matches) {
            mp[i[0]];
            mp[i[1]]++;
        }
        vector<vector<int>> vc;
        vc.resize(2);
        for(auto &i : matches) {
            if(mp[i[0]] == 0) {
                vc[0].push_back(i[0]);
                mp[i[0]] = -1;
            }
            if(mp[i[1]] == 1)
                vc[1].push_back(i[1]);
        }
        mysort(vc[0]);
        mysort(vc[1]);
        return vc;
    }
};
```

### Expected behavior

On test that is present in test.txt file attached below, this code has to do (n / 2) * ((n / 2) - 1) / 2 + (n / 2) * (log2(n) - 1) swaps, which is more than 5e8, so it gets TLE when used in "Run" operation.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/75163817/e0969a24-c8e4-4c35-b441-581cb2d73511)

### Additional context

The test:
[test.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/13941259/test.txt)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team
