### ISSUE TITLE
Missing Test Case - 2772. Apply Operations to Make All Array Elements Equal to Zero

### ISSUE THREAD

**Issue by incognion** [LeetCode-Feedback/LeetCode-Feedback#19418]
### LeetCode Username

[forleet](https://leetcode.com/forleet/)

### Problem number, title, and link

[2772. Apply Operations to Make All Array Elements Equal to Zero](https://leetcode.com/problems/apply-operations-to-make-all-array-elements-equal-to-zero/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [X] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

My code is getting accepted on submission, in spite of failing on the following test case, which is within the given constraints of the question:

nums:
```
[1,2,3,4,5,6,7,8,9,10,7,4,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]
```
k: 
```
3 
```

### Language used for code

C++

### Code used for Submit/Run operation

```
class Solution {
public:
    bool checkArray(vector<int>& nums, int k) {
        if(nums.size() > 100){
            bool f = 0;
            for(int i = 0; i < 10; i++){
                if(nums[i] == i + 1) f = 1;
            }
            if(f) return 0;
        }
        
        for(int i = 0; i < nums.size() - k + 1; i++){
            if(nums[i] < 0) return 0;
            if(nums[i]) {
                for(int j = 1 ; j < k; j++){
                    nums[i + j] -= nums[i];
                }
                nums[i] = 0;
            }
        }
        for(auto num : nums) if(num) return 0;
        return 1;
    }
};
```

### Expected behavior

The output of the program:
```
false
```
Expected Output:
```
true
```
Thus, this solution should not be accepted

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/97580124/dee3c999-e2c7-43f4-b622-1e6e1cfd5d76)

- But, you can see it is getting accepted on submission: [Accepted wrong solution](https://leetcode.com/problems/apply-operations-to-make-all-array-elements-equal-to-zero/submissions/1147032688)

### Additional context

I think test cases should be more rigorous, as this wrong solution is also bypassing the TLE error.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
