### ISSUE TITLE
Problem description - 334. Increasing Triplet Subsequence

### ISSUE THREAD

**Issue by LucasDivino** [LeetCode-Feedback/LeetCode-Feedback#19427]
### LeetCode Username
lucash1642

### Problem number, title, and link
334. [Increasing Triplet Subsequence](https://leetcode.com/problems/increasing-triplet-subsequence/)

### Category of the bug
- [x] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
The question descriptons says:

Given an integer array nums, return true if there exists a triple of indices `(i, j, k)` such that `i < j < k` and `nums[i] < nums[j] < nums[k]`. If no such indices exists, return false.
```
Example 1:
Input: nums = [1,2,3,4,5]
Output: true
Explanation: Any triplet where i < j < k is valid.

Example 2:
Input: nums = [5,4,3,2,1]
Output: false
Explanation: No triplet exists.

Example 3:
Input: nums = [2,1,5,0,4,6]
Output: true
Explanation: The triplet (3, 4, 5) is valid because nums[3] == 0 < nums[4] == 4 < nums[5] == 6.
```

But the test scenario don't check for `i < j < k` correctly.  For example: 
Given the input `[1,10,-9,15]` the output should be `false` because there are no triplet that such that  `i < j < k` and `nums[i] < nums[j] < nums[k]`. But the the code will return `true` thinking that (-9, 10, 15) is a valid triplet. This is wrong because they indexes are 2,1 and 3 respectively. 

### Language used for code

Javascript

### Code used for Submit/Run operation

```
/**
 * @param {number[]} nums
 * @return {boolean}
 */
var increasingTriplet = function(nums) {
  let first = Infinity;
  let second = Infinity;

  for (let i = 0; i < nums.length; i++) {
    if (first >= nums[i]) {
      first = nums[i];
      continue;
    }

    if (second >= nums[i]) {
      second = nums[i];
      continue;
    }

    return true;
  }

  return false;
};
```

### Expected behavior
My code and many other should not be accepeted once they didn't solve the problem correctly. For correctness inputs such [1,10,-9,15] should return false.
Also, I don't think there's a o(n)/o(1) time and space complexity solution. The solution must be something close to the longest Subsequence problem.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LucasDivino** [comment]
People in leetcode coments help me to undestand what I was missing, clossing this issue
