### ISSUE TITLE
Missing Test Case - 372. Super Pow

### ISSUE THREAD

**Issue by Shreyans06** [LeetCode-Feedback/LeetCode-Feedback#19431]
### LeetCode Username

shreyanskjain06

### Problem number, title, and link

372. Super Pow https://leetcode.com/problems/super-pow/description/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

One of the boundary cases is not included.  The Euler - Fermat states a^ϕ(n) ≡ 1 ( mod n ) for gcd(a , n) = 1. 
Here, ϕ(n) is Euler's Totient function, which counts the number of positive integers less than n that are coprime to n. If n is a product of two distinct prime numbers p and q, then ϕ(n) = (p−1) * (q−1).

Here, n = 1337 = (191) * (7)  which is a product of 2 primes
Hence ϕ(n) = (191−1) * (7−1) = (190) * (6) = 1140.
So, gcd(a , n) ≠ 1 when a = 191 or a = 7
So, a test case with a = 191 and b = [1, 1, 4, 0] should be included. The boundary case a = 7 and b = [1, 1, 4, 0] is already included.

### Language used for code

C++

### Code used for Submit/Run operation

```
class Solution {
public:
    int superPow(int a, vector<int>& b) {
        if (a == 1) return 1;
        int n = b.size();
        long long number = 0;
        for(int i = 0 ; i < n ; i++){
            number = ((number * 10) + b[i]) % 1140;
        }
        number %= 1140;
        if (number == 0) number = 1140;
        long long power = a;
        for(int i = 1 ; i < number ; i++){
            power = (power * a) % 1337;
        }
        return power % 1337;
    }
};
```

### Expected behavior

The input a = 191 and b = [1, 1, 4, 0] is not included as one of the test cases. Initially, 55 / 56 test cases were passed. The one left out was a = 7 and b = [1, 1, 4, 0]. But according to the above explanation, a = 191 and b = [1, 1, 4, 0] should also be included as one of the test cases.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
