### ISSUE TITLE
307. 区域和检索 - 数组可修改增加进阶要求

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#1943]
**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
第 307 题有两个常规的实现方法：
一是维护数组，`update` 的时间复杂度是 O(1)，`sumRange` 的时间复杂度是 O(n)。
二是维护前缀和，`update` 的时间复杂度是 O(n)，`sumRange` 的时间复杂度是 O(1)。
还有一种实现是用线段树，`update` 和 `sumRange` 的时间复杂度都是 O(log n)，但是线段树难度颇高，超出这道题目通过的要求，因此建议作为进阶要求。
进阶要求为，设计一种方案，使得`update` 和 `sumRange` 的时间复杂度都是 O(log n)。中文描述和英语描述需要同步更新。

**你使用的语言**
Java

**你提交或者运行的代码**

**期望行为**
增加进阶要求，中文描述和英语描述需要同步更新。

**屏幕截图**

**额外的上下文**

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，这题添加了新的标准，因此没有加进阶描述，当前中文题面已更新。
