### ISSUE TITLE
Missing Test Case - 1723. Find Minimum Time to Finish All Jobs

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#1944]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution is accepted but fails on the following test case:
[9899456, 8291115, 9477657, 9288480, 5146275, 7697968, 8573153, 3582365, 3758448, 9881935, 2420271, 4542202]
9

#### Code you used for Submit/Run operation

```
class Solution {
    private int[] dp;
    private int outls;
    private void min(int[] jobs,int len1,int n){
        if(len1==-1) {
            int ls = 0;
            for(int i = 0;i<n;i++){
                ls = Math.max(ls,dp[i]);
            }
            outls = Math.min(outls,ls);
            return ;
        }
        int ind = -1,lsum =Integer.MAX_VALUE;
        for(int i = 0;i<n;i++){
            if(dp[i]<lsum){
                lsum = dp[i];
                ind = i;
            }
        }

        dp[ind] += jobs[len1];
        min(jobs,len1-1,n);

        
    }
    private void m1(int[] jobs,int len1,int n){
        if(len1==-1) {
            int ls = 0;
            for(int i = 0;i<n;i++){
                ls = Math.max(ls,dp[i]);
            }

            outls = Math.min(outls,ls);
            return ;
        }

        for(int i = 0;i<n;i++){
            if(dp[i]>=outls) return ;
        }
        for(int i = 0;i<n;i++){

            dp[i]+=jobs[len1];
            m1(jobs,len1-1,n);
            dp[i]-=jobs[len1];
        }
        
    }
    public int minimumTimeRequired(int[] jobs, int k) {
         dp = new int[k];
        outls = Integer.MAX_VALUE;
       
        Arrays.sort(jobs);

        if(k<=8){
            m1(jobs,jobs.length-1,k);
        }else
        min(jobs,jobs.length-1,k);
        
        return outls;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/104121997-69877800-5310-11eb-8f35-e7b7ebd39ea9.png)

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
