### ISSUE TITLE
highlight issue of js editor

### ISSUE THREAD

**Issue by hakonleung** [LeetCode-Feedback/LeetCode-Feedback#19445]
### LeetCode Username
capybara

### Problem number, title, and link
https://leetcode.cn/problems/stone-game-viii/description/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug
highlight function broke

### Language used for code
javascript

### Screenshots

![屏幕截图 2024-01-16 220031](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/29906481/ab17e585-f569-432d-ae37-68ee7e4cc4e3)
![屏幕截图 2024-01-16 220114](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/29906481/a5166a46-69c2-4454-800a-a3fb2efffe6e)

### Env
os: win11 22H2
browser: edge Version 120.0.2210.133 (Official build) (64-bit)

**Comment by liyuzhu-lc** [comment]
您好，
感谢您的反馈，请问强制刷新并忽略内存可以正常使用吗？
Safari:

在 macOS 上：Command + R 或者 Command + Option + R （强制刷新并忽略缓存）
在 Windows 上：Ctrl + R 或者 Ctrl + F5（强制刷新并忽略缓存）
Google Chrome:

在 macOS 上：Command + R 或者 Command + Shift + R（强制刷新并忽略缓存）
在 Windows 上：Ctrl + R 或者 Ctrl + F5（强制刷新并忽略缓存）
Mozilla Firefox:

在 macOS 上：Command + R 或者 Command + Shift + R（强制刷新并忽略缓存）
在 Windows 上：Ctrl + R 或者 Ctrl + F5（强制刷新并忽略缓存）

Best Regards,
Leetcode | Support Team
