### ISSUE TITLE
Not sure if logic to check testcases is correct

### ISSUE THREAD

**Issue by chiruplayer** [LeetCode-Feedback/LeetCode-Feedback#19457]
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [* ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

How to check if the output is random? And since it is random, it wont match with the expected output. How to debug it then?

I used my own way of storing the data, without using the inbuilt stl map. I have also implemented logic for selecting the random elelment. This doesnt match with the expected output, but it is still random. Why is it giving error then?

This is the test case in question

Input:
["RandomizedSet","insert","insert","insert","insert","getRandom","getRandom","getRandom","getRandom","getRandom","getRandom".........
[[],[1],[10],[20],[30],[],[],[],[].........

Output:
[null,true,true,true,true,20,30,10,20,1,30,30,20,20,1...........

Expected:
[null,true,true,true,true,20,1,30,1,20,10,30,20,30,10,30.......

As you can see, the getRandom output values are not accepted. But it is still random

### Code used for Submit/Run operation

```
typedef struct treeNode{
    short digit;
    bool isValue;

    struct treeNode* children[2];
    struct treeNode* parent;
    int c[2];

    void init_node(){
        isValue = false;
        c[0] = c[1] = 0;
        children[0] = children[1] = 0;
        parent = 0;
    }

    treeNode(){
        init_node();
    }


    treeNode(int digit): digit(digit){
        init_node();
    }
} treeNode;

class RandomizedSet {
public:
    RandomizedSet() {
        positive = new treeNode(-1);
        negative = new treeNode(1);
        pos_values = 0;
        neg_values = 0;
    }
    
    bool insert(int val) {
        //cout << "Insert val " << val << endl;

        treeNode* curr = positive;
        if(val < 0){
            curr = negative;
            val = -val;
        }

        int val_store = val;

        do {
            short next = val & 1;
            if(curr->children[next] == 0){
                curr->children[next] = new treeNode(next);
                curr->children[next]->parent = curr;
            }
            
            curr = curr->children[next];
            val >>= 1;
        } while(val);

        if(curr->isValue)
            return false;

        curr->isValue = true;

        while(curr != positive && curr != negative){
            int prev_digit = curr->digit;
            curr = curr->parent;
            curr->c[prev_digit]++;
        }

        if(curr == positive){
            pos_values++;
        }
        else{
            neg_values++;
        }

        return true;
    }
    
    bool remove(int val) {
        //cout << "Remove val " << val << endl;
        int val_store = val;
        treeNode* curr = positive;
        if(val < 0){
            curr = negative;
            val = -val;
        }

        do{
            short next = val & 1;
            curr = curr->children[next];
            val >>= 1;
        } while(val && curr != 0);

        if(curr == 0 || curr->isValue == false){
            return false;
        }

        curr->isValue = false;

        while(curr != positive && curr != negative){
            short prev_digit = curr->digit;
            curr = curr->parent;
            curr->c[prev_digit]--;
            if(curr->c[prev_digit] == 0){
                curr->children[prev_digit] = 0;
            }
        }

        if(curr == positive){
            pos_values--;
        }
        else{
            neg_values--;
        }

        return  true;
    }

    int getRandom() {
        treeNode* curr = positive;
        int random = 0;
        //cout << "getRandom pos:" << pos_values << " neg:"<< neg_values << endl;

        if(pos_values == 0){
            curr = negative;
            //cout << "negative tree "  << endl;
        }
        else if(neg_values == 0){
            curr = positive;
        }
        else{
            random = rand() % 2;
            if(random){
                curr == positive;
            }
            else{
                curr = negative;
            }
        }

        int ret = 0;
        int left_shift = 0;

        while(curr != 0) {
            int random = rand() % 2;
            if(curr->children[random] == 0) {
                random ^= 1;
            }
            if(curr->children[random] != 0){
                curr = curr->children[random];
            }
            else{
                break;
            }

            ret |= (curr->digit << left_shift);

            left_shift++;
            if(curr->isValue){
                random = rand() % 2;
                if(random)
                    break;
            }
        }

        if(pos_values == 0)
            ret = -ret;

        //cout << "Returning " << ret << endl;

        return ret;
    }

private:
    treeNode* positive;
    treeNode* negative;
    int pos_values;
    int neg_values;
};

/**
 * Your RandomizedSet object will be instantiated and called as such:
 * RandomizedSet* obj = new RandomizedSet();
 * bool param_1 = obj->insert(val);
 * bool param_2 = obj->remove(val);
 * int param_3 = obj->getRandom();
 */
```

### Expected behavior

Should identify that the output is actually random, instead of just matching with your random output

### Screenshots

![leetcode-testcase](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/8570787/0ae452ef-83a0-47d7-ad1e-70587b866a21)

### Additional context

If certian values are expected in a question about random output, how to handle such questions

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
