### ISSUE TITLE
Incorrect Test Case - 1071. Greatest Common Divisor of Strings

### ISSUE THREAD

**Issue by monterdekeanu** [LeetCode-Feedback/LeetCode-Feedback#19465]
### LeetCode Username
monterdekeanu

### Problem number, title, and link
1071. Greatest Common Divisor of Strings https://leetcode.com/problems/greatest-common-divisor-of-strings/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
Test Case 109 input are:
str1 = "ABCDEF"
str2 = "ABC"
expected output = ""

which is supposed to be "ABC" 

### Language used for code
Java

### Code used for Submit/Run operation

```
class Solution {
    public String gcdOfStrings(String str1, String str2) {
        int n1 = str1.length(), n2 = str2.length();
        int minLen = Math.min(n1, n2);
        String result = "";
        for (int i = minLen; i >= 1; i--) {
            if (n1 % i == 0 && n2 % i == 0 && str1.substring(0, i).equals(str2.substring(0, i))) {
                result = str1.substring(0, i);
                break;
            }
        }

        return result;
    }
}
```

### Expected behavior

Expected output should be "ABC" not ""

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/75210937/4edd1ff5-04db-497c-ad03-352f3e24e642)

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
