### ISSUE TITLE
Missing Test Case - 1207. Unique Number of Occurrences

### ISSUE THREAD

**Issue by typemegan** [LeetCode-Feedback/LeetCode-Feedback#19469]
### LeetCode Username

lc207

### Problem number, title, and link

[1207. Unique Number of Occurrences](https://leetcode.com/problems/unique-number-of-occurrences/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Missing test case, e.g: [-1, 999]

### Language used for code

Go

### Code used for Submit/Run operation

```
func uniqueOccurrences(arr []int) bool {
    freq := make([]int, 2001)
    for _, x := range arr {
        if x < 0 {
            freq[x+1000]++
        } else {
            freq[x]++  // ❌ wrong here, the value should always add 1000 no matter it's negative or positive. 
        }
    }
    
    sort.Ints(freq)
    for i:=1; i<2001; i++ {
        if freq[i] != 0 && freq[i] == freq[i-1] {
            return false
        }
    }    

    return true
}
```

### Expected behavior

The solution above shouldn't be accepted. 

### Screenshots

<img width="1526" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/12883950/66a62df5-ba10-4c30-9918-33763d2b55e5">

**Comment by naXa777** [comment]
I confirm that the issue is reproducible. I'd like to request the same test case for Kotlin.

### LeetCode Username

naXa777

### Language used for code

Kotlin

### Code used for Submit/Run operation
```kt
class Solution {
    fun uniqueOccurrences(arr: IntArray): Boolean {
        val freq = IntArray(2001)
        for (x in arr) {
            if (x < 0) {
                freq[x + 1000]++
            } else {
                freq[x]++  // ❌ wrong here, the value should always add 1000 no matter it's negative or positive.
            }
        }

        freq.sort()
        for (i in 1 until 2001) {
            if (freq[i] != 0 && freq[i] == freq[i - 1]) {
                return false
            }
        }

        return true
    }
}
```

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/3858548/b4a5f7d1-d51e-4ef5-bf56-4dcd1bbacde2)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
