### ISSUE TITLE
1115. Print FooBar Alternately Go lang support

### ISSUE THREAD

**Issue by AlexChernov** [LeetCode-Feedback/LeetCode-Feedback#19474]
### LeetCode Username

AlexChern0v

### Problem number, title, and link

1115. Print FooBar Alternately https://leetcode.com/problems/print-foobar-alternately/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [x] Programming language support

### Description of the bug

The [1115. Print FooBar Alternately](https://leetcode.com/problems/print-foobar-alternately/) problem doesn't allow to submit solution using golang. It's not clear why as Go available for the most of other problems (not from the [Concurrency list](https://leetcode.com/problemset/concurrency/)) and concurrency is a hot topic on interviews for golang positions.

### Language used for code

Go

### Code used for Submit/Run operation

N/A

### Expected behavior
Golang supported as option to submit the solution.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/7085247/3f92e06b-f364-4b7d-8345-4bb38dd95f65)

### Additional context

I'm happy to contribute, but didn't find corresponding repository/form.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
