### ISSUE TITLE
Missing Test Case for Byte Overflow - 1207. Unique Number of Occurrences

### ISSUE THREAD

**Issue by naXa777** [LeetCode-Feedback/LeetCode-Feedback#19472]
### LeetCode Username

naXa777

### Problem number, title, and link

[1207. Unique Number of Occurrences](https://leetcode.com/problems/unique-number-of-occurrences/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Incorrect Code getting accepted. The code AC submission link is https://leetcode.com/problems/unique-number-of-occurrences/submissions/1148757302/

In my code I use `UByteArray`. `UByte` values are in range 0..255. If test input contains a number repeated 256 or more times, byte overflow happens. That's why my code is incorrect.

### Language used for code

Kotlin

### Code used for Submit/Run operation

```kt
class Solution {
    fun uniqueOccurrences(arr: IntArray): Boolean {
        val frequencies = UByteArray(2000)
        for (n in arr) {
            ++frequencies[n + 1000]
        }
        val uniq = BooleanArray(2000)
        for (i in 0 until 2000) {
            val freq = frequencies[i].toInt()
            if (freq == 0) continue
            if (uniq[freq]) return false
            uniq[freq] = true
        }
        return true
    }
}
```

### Expected behavior

Incorrect Code is rejected by test.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/3858548/9279abdd-4df2-49ad-98b2-f104b77ed796)

### Additional context

Please add a test with this input:
```[1,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257]```

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team

**Comment by naXa777** [comment]
Thank you for the LeetCoins!

@LC-Pam, You've closed the issue a week ago and said that "feedback has been instrumental in enhancing the problem", so I assumed that your team has added the missing test case. But I've tested today and the reported problem is still reproducible. How do you explain this?

Today's AC submission link is https://leetcode.com/problems/unique-number-of-occurrences/submissions/1163040446

**Comment by LC-Pam** [comment]
The issue should be fixed.
