### ISSUE TITLE
Inconsistent results in insert-delete-getrandom-o1 if using random.choice vs random.randint

### ISSUE THREAD

**Issue by maya-undefined** [LeetCode-Feedback/LeetCode-Feedback#19487]
### LeetCode Username
emm

### Problem number, title, and link

1. Get Random https://leetcode.com/problems/insert-delete-getrandom-o1

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Initially, I had a bug in my insert() function. Instead of returning False when the `val` is found, I continued to add it to my private data structures. This caused a `list` I had to grow when it should not have. The internal data I had in other data structures still allowed my code to pass, however. 

i noticed in my getRandom() function, that if I use python's random.choice(list), I would get 'accepted' answers. If I instead used list[random.randint(0, len(my_list) - 1)] I would get errors. In principle the two methods should be the same, but `random.choice` always passed. There may be some kind of issue or test case that doesn't cover choice()

### Language used for code
python

### Code used for Submit/Run operation

```
from random import randint, choice

class RandomizedSet:

    def __init__(self):
        self._set = {}
        self._list = []

    def insert(self, val: int) -> bool:
        print("insert: ", val, " / ", self._list, self._set)
        found = val in self._set
        self._set[val] = len(self._list)
        self._list.append(val) ## if a value is inserted twice, it will (incorrectly) appear twice in this list
        return not found

    def remove(self, val: int) -> bool:
        if val not in self._set:
            return False
        print("remove: ", val, " / ", self._list, self._set)
        # copy the last element of the list to val's current index, thus
        # recycling the index
        i = self._set[val]
        ## get the to-be-removed val's index
        self._list[i] = self._list[-1]
        ## copy the last element of list to the dead val's index
        self._set[self._list[-1]] = i
        ## remap the last element to the the dead val's index

        self._list.pop()
        ## there are 2 copies of the last element right now, so delete the 2nd one
        del self._set[val]
        ## remove the dead val from the map

        return True

    def getRandom(self) -> int:
        # return choice(self._list)
        print(self._list, self._set)
        i = randint(0,len(self._list)-1)
        return self._list[i]
        # return list(self._set.keys())[i]

# Your RandomizedSet object will be instantiated and called as such:
# obj = RandomizedSet()
# param_1 = obj.insert(val)
# param_2 = obj.remove(val)
# param_3 = obj.getRandom()
```

### Expected behavior

it shouldn't matter if I use choice() or randint to select a random index from the element with uniform probability. choice() doesn't care about duplicates

### Observed
choice() seems to always pass the tests and returns 'Accepted' where as randint() seems to fail

### Screenshots

n/a

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback. 

Please ask this in the discussion. 

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
