### ISSUE TITLE
Missing Test Case - 3006. Find Beautiful Indices in the Given Array I

### ISSUE THREAD

**Issue by Jeetaksh** [LeetCode-Feedback/LeetCode-Feedback#19494]
### LeetCode Username
Jeetaksh

### Problem number, title, and link
[3006. Find Beautiful Indices in the Given Array I](https://leetcode.com/problems/find-beautiful-indices-in-the-given-array-i/)

### Category of the bug

-  Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug
Wrong Code is getting Accepted due to missing TestCases

TestCase to be added:-
s = "aaaaaaaaaaaaaaaaa"
a = "aaaa"
b = "aaaaa"
k = 2

### Language used for code
C++

### Code used for Submit/Run operation

```
class Solution {
public:
    vector<int> beautifulIndices(string s, string a, string b, int k) {
        vector<int> c, d;
        int j = 0, n = s.size();
        for(int i=0;i<n;i++) {
            if(s[i] == a[j] and j < a.size()) {
                j++;
            } else {
                if(j == a.size()) c.push_back(i-j);
                j = 0;
                if(s[i] == a[j]) j++;
            }
        }
        if(j == a.size()) c.push_back(n-j);
        j = 0;
        for(int i=0;i<n;i++) {
            if(s[i] == b[j] and j < b.size()) {
                j++;
            } else {
                if(j == b.size()) d.push_back(i-j);
                j = 0;
                if(s[i] == b[j]) j++;
            }
        }
        if(j == b.size()) d.push_back(n-j);
        
        vector<int> ans;
        for(int num1 : c) {
            for(int num2 : d) {
                if(abs(num1-num2) <= k) {
                    ans.push_back(num1);
                    break;
                }
            }
        }
        return ans;
    }
};
```

### Expected behavior

The Code should show wrong answer and should not get accepted after addition of these testcases.

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/92541718/07b3fb5a-717a-4da5-a12c-ffe7e3196b4e)

### Additional context
Wrong Code with AC
https://leetcode.com/problems/find-beautiful-indices-in-the-given-array-i/submissions/1149451938/

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team
