### ISSUE TITLE
TypeScript使用const定义变量，变量名颜色与背景颜色相同

### ISSUE THREAD

**Issue by tzz-v** [LeetCode-Feedback/LeetCode-Feedback#19497]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

### LeetCode 用户名
tzz

### 问题号码、标题和链接
[334. 递增的三元子序列](https://leetcode.cn/problems/increasing-triplet-subsequence/)

### Bug 类型
- [ ] 编程语言支持

### 描述
使用const定义变量，变量名颜色与背景颜色相同，let定义就没问题

### 你使用的语言
TypeScript

### 你提交或者运行的代码

```
function increasingTriplet(nums: number[]): boolean {
  const stack = [];
  let aa = '';
  const bb = '';
};
```

### 屏幕截图

<img width="556" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/45192602/15e6696a-eff6-4506-b430-141931c7b2f3">

**Comment by liyuzhu-lc** [comment]
您好，
感谢您的反馈，请问强制刷新并忽略内存可以正常使用吗？
Safari:

在 macOS 上：Command + R 或者 Command + Option + R （强制刷新并忽略缓存）
在 Windows 上：Ctrl + R 或者 Ctrl + F5（强制刷新并忽略缓存）
Google Chrome:

在 macOS 上：Command + R 或者 Command + Shift + R（强制刷新并忽略缓存）
在 Windows 上：Ctrl + R 或者 Ctrl + F5（强制刷新并忽略缓存）
Mozilla Firefox:

在 macOS 上：Command + R 或者 Command + Shift + R（强制刷新并忽略缓存）
在 Windows 上：Ctrl + R 或者 Ctrl + F5（强制刷新并忽略缓存）

Best Regards,
Leetcode | Support Team
