### ISSUE TITLE
#1213 problem doesn't require solutions to be sorted

### ISSUE THREAD

**Issue by Triara** [LeetCode-Feedback/LeetCode-Feedback#1949]
#### Your LeetCode username

dahrein

#### Category of the bug
- [ ] Question
- [ X] Solution
- [ ] Language

#### Description of the bug

The problem statement doesn't require the solution to be sorted, however submission fails for unsorted answers.

#### Code you used for Submit/Run operation

```
public List<Integer> arraysIntersection(int[] arr1, int[] arr2, int[] arr3) {
        HashSet<Integer> set1 = createSet(arr1);
        HashSet<Integer> set2 = createSet(arr2);
        HashSet<Integer> set3 = createSet(arr3);
        
        return set1.stream()
            .filter(set2::contains)
            .filter(set3::contains)
            .collect(Collectors.toList());
    }
    
    private static HashSet<Integer> createSet(int[] arr) {
        HashSet<Integer> set = new HashSet<Integer>();
        for (int i : arr) {
            set.add(i);
        }
        return set;
    }
```

#### Language used for code

Java

#### Expected behavior

Submission should be accepted as it doesn't violate a problem constrain.

#### Screenshots

https://snipboard.io/T2i9qY.jpg

**Comment by lc-kay** [comment]
Hi @Triara 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@Triara The statement already says: "return a **sorted array** of only the integers that appeared in all three arrays." Thank you for your time.
