### ISSUE TITLE
Missing Test Case - 1136. Parallel Courses

### ISSUE THREAD

**Issue by waliamehak** [LeetCode-Feedback/LeetCode-Feedback#19491]
### LeetCode Username

mehakwaliaC

### Problem number, title, and link

1136. Parallel Courses : https://leetcode.com/problems/parallel-courses/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [X] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The code below is accepted but actually is wrong for some testCases (every test case with the last course as the parent node for the longest chain in the DAG)

### Language used for code

C++

### Code used for Submit/Run operation

```
class Solution {
public:
int answer; 
    int traverse(int curr, vector<vector<int>>& children, vector<int>& seen){
        if(seen[curr]) return seen[curr];
        seen[curr] = -1;
        int depth = 1;
        for (auto &child: children[curr]){
            if (traverse(child, children, seen) == -1)
                return -1;
            depth = max (depth, seen[child] + 1);
        }
        return seen[curr] = depth; 
    }
    int minimumSemesters(int n, vector<vector<int>>& relations) {
        vector<vector<int>> children (n+1);
        vector<int> seen (n + 1);
        for (auto & relation: relations)
            children[relation[0]].push_back(relation[1]);
        

        for (int i =1 ; i<n; ++i){
            int a = traverse(i, children, seen) ;
            if (a == -1) return -1;
            answer = max (a, answer);
        }
        return answer;
    }
};
```

### Expected behavior

This code is ignoring the 'nth' course in the for loop but still getting accepted. 
Example of such missing test case could be:
n = 2. 
relations = [[2, 1]].

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
