### ISSUE TITLE
Missing Test Case - 1476. Subrectangle Queries

### ISSUE THREAD

**Issue by aasthaa012** [LeetCode-Feedback/LeetCode-Feedback#19498]
### LeetCode Username

_aasthaa_gupta24

### Problem number, title, and link

1476. Subrectangle Queries https://leetcode.com/problems/subrectangle-queries/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Problem description says all the values in the subrectangle from upper left coordinate to lower right coordinate should be changed on "updateSubrectangle" call. But test case no. 19 is not showing output according to this condition.

### Language used for code

Java

### Code used for Submit/Run operation

```
class SubrectangleQueries {
    int[][] arr;
    int l;

    public SubrectangleQueries(int[][] rect) {
        arr=rect;
        l=arr[0].length;
    }
    
    public void updateSubrectangle(int r1, int c1, int r2, int c2, int n) {
        if(r1==r2) for(int i=c1; i<=c2; i++) arr[r1][i]=n;
        else {
            for(int i=r1; i<=r2; i++) {
                if(i==r1) for(int j=c1; j<l; j++) arr[i][j]=n;
                else if(i==r2) for(int j=0; j<=c2; j++) arr[i][j]=n;
                else for(int j=0; j<l; j++) arr[i][j]=n;
            }
        }
    }
    
    public int getValue(int row, int col) {
        return arr[row][col];
    }
}
```

### Expected behavior

Output should be: [null,null,5,5,null,6,6]
Test case showing: [null,null,5,5,null,6,9]

### Screenshots

![Screenshot (2)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/156993879/3fbc5434-4417-495d-be92-04267a883554)

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
