### ISSUE TITLE
Poor English for Q1425

### ISSUE THREAD

**Issue by xu932** [LeetCode-Feedback/LeetCode-Feedback#195]
**What kind of the bug**
- [ ] problem
- [ ] solution
- [x] language

The way the question is described is really confusing. I think it would be better if worded something similar to "a nonempty subset of the array (subarray that does not have to be consecutive in the original array) where each element is chosen from the array, in order, that is at most k apart from each other." I appreciate the mathematical explanation, which is less ambiguous than words but it is very hard to understand. I have to read it couple times, nice and slowly, to understand what the problem is.

**Comment by CooperCooperCooper** [comment]
Hi @xu932,
Thank you for reaching out to us. I've relayed your feedback to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @xu932,
Thank you for your time. Our team decided to keep the problem statement as-is for now. We will keep this suggestion in mind for future changes.
