### ISSUE TITLE
Missing Test Case - 2733. Neither Minimum nor Maximum

### ISSUE THREAD

**Issue by idhavaldev** [LeetCode-Feedback/LeetCode-Feedback#19508]
### LeetCode Username

dhavaldev

### Problem number, title, and link

2733. Neither Minimum nor Maximum

### Category of the bug
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

It is not covering all scenarios.  Like if you keep array for first 3 same integers and then couple of different.  Many solutions work as is.

### Language used for code
Java

### Test Case
nums=
[1,1,1,1,23,30]

Expected Output=
23

**Comment by idhavaldev** [comment]
Thanks for the quick response.  Is the new test case been added?  If I have to add the test case and contribute in the way, is there any GitHub public repo link?

**Comment by pechinkin** [comment]
@idhavaldev no, they are asking you to provide a link for submission, to copy it there are a chain sign on the screenshot's left top edge
<img width="702" alt="Screenshot 2024-01-18 at 21 51 01" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/124191811/dfe776f4-c98e-40ea-877a-f580427a3535">

**Comment by idhavaldev** [comment]
@LC-Pam  Here is the submission link: https://leetcode.com/problems/neither-minimum-nor-maximum/submissions/1149864214


Thanks @pechinkin for make me understand.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The VALID test case.
[1,1,1,1,23,30] received Invalid Testcase: expected variables nums[0]:1 and nums[1]:1 to have different values


Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by idhavaldev** [comment]
Ohk, it is said to be distinct.  Got it, then we can ignore this.  Thanks for your message.
