### ISSUE TITLE
Missing Test Case - 582. Kill Process

### ISSUE THREAD

**Issue by zhanghx04** [LeetCode-Feedback/LeetCode-Feedback#19515]
### LeetCode Username

zhanghx04

### Problem number, title, and link

582. Kill Process https://leetcode.com/problems/kill-process/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [x] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The description didn't mention that the `kill` process is one of the running processes.
To kill a process, the user could enter any process ID even if the process is not running.

### Language used for code
C++

### Code used for Submit/Run operation

```cpp
class Solution {
public:
    vector<int> killProcess(vector<int>& pid, vector<int>& ppid, int kill) {
        /* Make a graph of processes relationship */
        unordered_map<int, vector<int>> process_graph;  // parent process : list of child processes 
        int n = pid.size();
        bool found_process_to_be_terminated = false;
        for (int i = 0; i < n; ++i) {
            found_process_to_be_terminated |= pid[i];
            process_graph[ppid[i]].push_back(pid[i]);
        }

        /* If the process need to be terminate is not running */
        if (!found_process_to_be_terminated) {
            return {};
        }

        /* BFS for getting all subprocess of the process kill and itself */
        vector<int> killed_process;
        queue<int> process_q;
        process_q.push(kill);

        while (!process_q.empty()) {
            int curr_process = process_q.front();
            process_q.pop();

            killed_process.push_back(curr_process);

            for (int subprocess : process_graph[curr_process]) {
                process_q.push(subprocess);
            }
        }

        return killed_process;
    }
};
```

### Expected behavior

If the process that wants to be killed is not running, return an empty array.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
