### ISSUE TITLE
Missing Test Case - 28. Find the Index of the First Occurrence in a String

### ISSUE THREAD

**Issue by mawadaelmeshad** [LeetCode-Feedback/LeetCode-Feedback#19513]
### LeetCode Username : 
Mawadah

### Problem number, title, and link  
[28. Find the Index of the First Occurrence in a String](https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/)

### Category of the bug
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

if haystack = "badbutsad" and the code is running until i<=haystack.length()-needle.length() it won't give the right answer, it should be i<=haystack.length() in order to give the right solution

### Language used for code
C++

### Code used for Submit/Run operation

```
class Solution {
public:
    int strStr(string haystack, string needle) {
        if(haystack.length()<needle.length()){
            return -1;
        }
        for(int i=0;i<=haystack.length()-needle.length();i++){
            if(haystack.substr(i,needle.length())==needle){
                return i;
            }
            
        }
        return -1;
        
    }
};
```

### Expected behavior

it will return -1 and won't return the actual index of the word

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
