### ISSUE TITLE
Missing Test Case - 409. Longest Palindrome

### ISSUE THREAD

**Issue by simone-cappelletti** [LeetCode-Feedback/LeetCode-Feedback#19518]
### LeetCode Username
[simonecappelletti](https://leetcode.com/simonecappelletti)

### Problem number, title, and link
[409. Longest Palindrome](https://leetcode.com/problems/longest-palindrome/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [X] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
Solutions like the one below are accepted cause lack of test cases. Note that the initial modulus operation makes no sense.

### Language used for code
C#

### Code used for Submit/Run operation

```
public class Solution {
    public int LongestPalindrome(string s)
    {
        var dic = new int[52];
        var result = 0;
        var oddChar = 0;
        
        foreach(var @char in s)
            dic[@char % 52]++;

        foreach(var @char in dic)
        {
            if(@char % 2 == 0)
            {
                result += @char;
            }
            else
            {
                result += @char - 1;
                oddChar = Math.Max(oddChar, @char);
            }
        }

        if(oddChar > 0)
            result += oddChar - (oddChar - 1);

        return result;
    }
}
```

### Expected behavior
This solution should be invalid. In fact test case like "Fz" made the solution fail.

**Comment by naXa777** [comment]
Hello @simone-cappelletti,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

* [ ] **The code submission link you submitted led to the observed result.**

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

**Comment by simone-cappelletti** [comment]
> Hello @simone-cappelletti,
> 
> Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:
> 
> * [ ]  **The code submission link you submitted led to the observed result.**
> 
> Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

This is the submission: https://leetcode.com/problems/longest-palindrome/submissions/1150192185/

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
