### ISSUE TITLE
Missing Test Case - 852. Peak Index in a Mountain Array

### ISSUE THREAD

**Issue by rak3xh** [LeetCode-Feedback/LeetCode-Feedback#19517]
### Problem number, title, and link
852.  Peak Index in a Mountain Array https://leetcode.com/problems/peak-index-in-a-mountain-array/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [x] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
Constraints not useful
3 <= arr.length <= 10^5

### Language used for code
C++

### Code used for Submit/Run operation

```
class Solution {
public:
    int peakIndexInMountainArray(vector<int>& arr) {
        int s=0,e=arr.size()-1;
        int mid=s+(e-s)/2;
        while(s<e){
            if(arr[mid]<arr[mid+1]){
                s=mid+1;
            }
            else{
                e=mid;
            }
            mid=s+(e-s)/2;
        }
        return s;
    }
};
```

### Expected behavior

What is the use of this problem with such a small size of array?
It can easily pass linear search with such a less size.
It should be made up to 10^10 so that it only passes binary search and not linear search so that the purpose of the problem to check your binary search abilities gets solved.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by rak3xh** [comment]
Thank you for looking into the issue.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
