### ISSUE TITLE
Missing Test Case - 2. Add Two Numbers

### ISSUE THREAD

**Issue by ThanoS-max** [LeetCode-Feedback/LeetCode-Feedback#1951]
#### Category of the bug
- [y ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Can you check if test cases are proved?
or maybe my code is messy so indirectly my code is wrong.
please confirm. 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@ThanoS-max Our content team reviews all test case sets for all our problems carefully before publishing them. All the expected answers are correct. If you have any questions on your code or why it is not passing, please refer to the discuss section. Thank you for your time.
