### ISSUE TITLE
Missing Test Case - 217. Contains Duplicate

### ISSUE THREAD

**Issue by ghjkgf** [LeetCode-Feedback/LeetCode-Feedback#1952]
#### Solution

- [ ] Solution

#### ```

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@ghjkgf Please provide more information for the issue you are trying to report. Thank you!

**Comment by lc-kay** [comment]
Hi @ghjkgf 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
