### ISSUE TITLE
Missing Test Case - 409. Longest Palindrome

### ISSUE THREAD

**Issue by naXa777** [LeetCode-Feedback/LeetCode-Feedback#19537]
### LeetCode Username

naXa777

### Problem number, title, and link

[409. Longest Palindrome](https://leetcode.com/problems/longest-palindrome/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Incorrect code is getting accepted when submitted.
Submission AC Link: https://leetcode.com/problems/longest-palindrome/submissions/1150704190

### Language used for code

Kotlin

### Code used for Submit/Run operation

```kt
class Solution {
    fun longestPalindrome(s: String): Int {
        val frequencies = IntArray(52)
        var palindromeLen = 0
        for (ch in s) {
            if (++frequencies[ch.code % 52] % 2 == 0)
                palindromeLen += 2
        }
        if (palindromeLen < s.length)
            ++palindromeLen
        return palindromeLen
    }
}
```

### Expected behavior

This solution should be rejected by tests.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/3858548/495ffd31-7ebf-4fb0-9b08-c6a1ae2c17dd)

### Additional context

Please add a test case for input `Fz`.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by naXa777** [comment]
Hello @LC-Pam!
Why did the team has decided to reject my feedback?

The proposed test case "Fz" is a valid test case according to the problem №409 description. And the code that I submitted still fails on this test case, but accepted. So I don't understand why don't you want to add a little test case that will solve the highlighted problem.

Please let your team compare valid code and invalid code side by side. The issue is real. Can you spot the bug?

<table>
<thead>
<tr><th>Invalid code</th><th>Valid code</th></tr>
</thead>
<tbody>
<tr>
<td>

```kt
class Solution {
    fun longestPalindrome(s: String): Int {
        val frequencies = IntArray(52)
        var palindromeLen = 0
        for (ch in s) {
            if (++frequencies[ch.code % 52] % 2 == 0)
                palindromeLen += 2
        }
        if (palindromeLen < s.length)
            ++palindromeLen
        return palindromeLen
    }
}
```

</td>
<td>

```kt
class Solution {
    fun longestPalindrome(s: String): Int {
        val bits = BooleanArray(57)
        var palindromeLen = 0
        for (ch in s) {
            bits[ch.code % 57] = !bits[ch.code % 57]
            if (!bits[ch.code % 57])
                palindromeLen += 2
        }
        if (palindromeLen < s.length)
            ++palindromeLen
        return palindromeLen
    }
}
```

</td>
</tr>
</tbody>
</table>

**Comment by naXa777** [comment]
@LC-Pam I have further questions. Will you please answer them? ^
