### ISSUE TITLE
Wrong Test Case - 98. Validate Binary Search Tree

### ISSUE THREAD

**Issue by AkshayNThakare** [LeetCode-Feedback/LeetCode-Feedback#19549]
### LeetCode Username

https://leetcode.com/AkshayT1

### Problem number, title, and link

98. Validate Binary Search Tree https://leetcode.com/problems/validate-binary-search-tree/description/

### Category of the bug
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### Description of the bug

test case [2147483647]
test case no :  76 / 84

current test case Output : true 
expected output : false
binary tree doesn't allow duplication, and is not a valid test case.

### Language used for code

C++

### Code used for Submit/Run operation

```
/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
class Solution {
public:
    bool isValidBST(TreeNode* root) {
        return dfs(root,INT_MIN,INT_MAX);
    }
private:
    bool dfs(TreeNode* root,long left, long right){
        if (!root)
            return true;
        if (root->val < right && root->val > left){
            return dfs(root->left, left, root->val) && dfs(root->right, root->val, right);
        }
        return false;
    }
};
```

### Expected behavior

Output Should be;- False. 

### Screenshots

https://drive.google.com/file/d/1LPRXZq0iOUZ7aFgYPVN_6c2kLkMbSf2L/view?usp=sharing

**Comment by naXa777** [comment]
> binary tree doesn't allow duplication

Why?

Let me disagree. I think binary trees may contain duplicate values on nodes.

Moreover, the test case you shared is a tree of a single node. It doesn't have any duplicates. Even without any children it's still considered a valid binary tree.

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
