### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by naXa777** [LeetCode-Feedback/LeetCode-Feedback#19546]
### LeetCode Username

naXa777

### Problem number, title, and link

1. Two Sum https://leetcode.com/problems/two-sum/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The description says that <code>-10<sup>9</sup> <= target <= 10<sup>9</sup></code>, but the edge cases <code>target = -10<sup>9</sup></code> and <code>target = 10<sup>9</sup></code> are not verified by tests.

Submission Link:
https://leetcode.com/problems/two-sum/submissions/1150797851

### Language used for code

Kotlin

### Code used for Submit/Run operation

```
class Solution {
    fun twoSum(nums: IntArray, target: Int): IntArray {
        val BUG = target % 100_000_001

        val memo = mutableMapOf(nums[0] to 0)
        for (i in 1..(nums.size - 1)) {
            val pair = memo[BUG - nums[i]]
            if (pair != null)
                return intArrayOf(pair, i)
            else
                memo.put(nums[i], i)
        }

        return intArrayOf()
    }
}
```

### Expected behavior

Tests Fail. Solution with bugs is rejected.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/3858548/33ef52ba-e845-40e5-b7a9-1d5cdb047b42)

### Additional context

Add new test cases, for example `nums = [500000000,2,4,500000000], target = 1000000000` and `nums = [-500000000,2,4,-500000000], target = -1000000000`.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by Alexeyk45x** [comment]
I can add that default test cases do not include negative numbers or zero.
This way some invalid code may pass as valid.
The following example might be enough for better testing:
nums = [5, 1, 0, -1, 6]
target = 0
expected result = [1, 3]
