### ISSUE TITLE
1705. 吃苹果的最大数目 后台读取参数不全

### ISSUE THREAD

**Issue by xuanwu348** [LeetCode-Feedback/LeetCode-Feedback#1954]
![image](https://user-images.githubusercontent.com/33962139/104130284-c172bd00-53aa-11eb-990e-c079b8f99915.png)

Input of the case as below:[0,19,19,19,11,14,33,0,28,7,0,28,7,0,21,16,0,22,0,13,8,0,19,0,0,2,26,2,22,0,8,0,0,27,19,16,24,0,20,26,20,7,0,0,29,0,0,16,19,0,0,0,29,30,17,0,23,0,0,26,24,13,3,0,21,0,18,0]
[0,5,1,16,7,10,54,0,40,2,0,23,4,0,20,18,0,40,0,22,8,0,35,0,0,3,24,1,8,0,10,0,0,2,38,8,4,0,36,33,14,9,0,0,56,0,0,21,27,0,0,0,14,20,18,0,42,0,0,44,3,8,3,0,10,0,27,0]

But I has found :
new_apples = list(zip(days, apples))    == >    [(3,9),(5,2)]
# class Solution:
#     def eatenApples(self, apples: List[int], days: List[int]) -> int:
        # # new_apples = list(zip(days, apples))
        # new_apples = [(days[i], apples[i]) for i in range(len(days))]
        # print(new_apples)
        # dp = []
        # for i, item in enumerate(new_apples):
        #     day, apple = item
        #     if apple == 0:
        #         if i >= len(dp):
        #             temp = [0] * (i - len(dp) + 1)
        #             dp.extend(temp)
        #         continue
        #     else:
        #         if apple >= day:
        #             if day > len(dp[i:]):
        #                 temp = [1] * (day - len(dp[i:]))
        #                 dp.extend(temp)
        #         else:
        #             temp = [1] * min(day-len(dp[i:]), len(dp[i:]) + apple)
        #             dp.extend(temp)
        # print(dp)
        # return dp.count(1)

        # or

        # dp = []
        # i = 0
        # while i < len(days):
        #     day, apple = days[i], apples[i]
        #     if apple == 0:
        #         if i >= len(dp):
        #             temp = [0] * (i - len(dp) + 1)
        #             dp.extend(temp)
        #     else:
        #         if apple >= day:
        #             if day > len(dp[i:]):
        #                 temp = [1] * (day - len(dp[i:]))
        #                 dp.extend(temp)
        #         else:
        #             temp = [1] * min(day-len(dp[i:]), len(dp[i:]) + apple)
        #             dp.extend(temp)
        #     i += 1
        # print(dp)
        # return dp.count(1)

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前该题已修复， 请留言告知一下您的力扣 ID，我们给予积分奖励哦。

**Comment by xuanwu348** [comment]
> 你好，当前该题已修复， 请留言告知一下您的力扣 ID，我们给予积分奖励哦。

你好，验证了下，问题随风飘逝了，谢谢。力扣ID:xuanwu348

**Comment by feiceh** [comment]
哈哈，不客气。ID：xuanwu348 给予积分奖励，请查收。

**Comment by xuanwu348** [comment]
> 哈哈，不客气。ID：xuanwu348 给予积分奖励，请查收。

谢谢，已收到
