### ISSUE TITLE
Missing TestCase: 3006. Find Beautiful Indices in the Given Array I

### ISSUE THREAD

**Issue by deep3072** [LeetCode-Feedback/LeetCode-Feedback#19544]
### LeetCode Username
deep3072

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
A solution is accepted but fails on the following test case:
"ababababazzabababb"
"aba"
"bb"
10

### Language used for code
C++

### Code used for Submit/Run operation

```
class Solution 
{
        public:
        vector<int> beautifulIndices(string s, string a, string b, int k) 
        {
                int pos1 = 0;
                int pos2 = 0;
                vector<int>v1, v2;
                while((pos1 = s.find(a, pos1)) != std::string::npos) {
                        v1.push_back(pos1);
                        pos1 += a.length();
                }

                while((pos2 = s.find(b, pos2)) != std::string::npos) {
                        v2.push_back(pos2);
                        pos2 += b.length();
                }
                
                vector<int>ans;
                for(int i=0;i<v1.size();i++)
                {
                        for(int j=0;j<v2.size();j++)
                        {
                                int diff = abs(v1[i] - v2[j]);
                                if(diff <= k)
                                {
                                        ans.push_back(v1[i]);
                                        break;
                                }
                        }
                }
                return ans;

        }
};
```

### Expected behavior
The solution should not be accepted since it fails on the test case

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/62668186/95fa2aa9-13cd-45ee-af68-ef4600c1a1d9)

### Additional context
Testcase: "ababababazzabababb"
"aba"
"bb"
10

Output: [11]
Expected: [6, 11, 13]

**Comment by deep3072** [comment]
Sure. 

 The code submission link you submitted led to the observed result:

https://leetcode.com/submissions/detail/1150796718/

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
