### ISSUE TITLE
Wrong example in sample test case?

### ISSUE THREAD

**Issue by chiruplayer** [LeetCode-Feedback/LeetCode-Feedback#19556]
### Problem number, title, and link 
 399. Evaluate Division https://leetcode.com/problems/evaluate-division/

### Category of the bug
- [ *] Problem description
- [ ] Solved examples
- [* ] Problem constraints
- [ *] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ *] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

In the sample case, ["x","x"] returns -1. However, shouldn't the expected value be 1.000 ? Since it is given that it is guaranteed that there is no division by zero, shouldn't 1.00 be a valid answer? 

### Code used for Submit/Run operation

```
typedef unordered_map<string, unordered_map<string, double>> eqGraph;
typedef unordered_map<string, bool> eqSeen;

class Solution {
public:
    vector<double> calcEquation(vector<vector<string>>& equations, vector<double>& values, vector<vector<string>>& queries) {
        eqGraph graph;
        int numEquations = equations.size();
        vector<double> ret;
        eqSeen seen;

        for(int equation=0; equation < numEquations; equation++){
            graph[equations[equation][0]][equations[equation][1]] = values[equation];
            graph[equations[equation][1]][equations[equation][0]] = 1.0 / values[equation];
            seen[equations[equation][0]] = false;
            seen[equations[equation][1]] = false;
        }

        for(vector<string>& query: queries){
            double answer =-1;
            if(seen.find(query[0]) != seen.end() && seen.find(query[1]) != seen.end()){
                answer = traverse( graph, query[0], query[1], seen);
            }
            ret.push_back(answer);
        }

        return ret;
    }

private:
    double traverse(eqGraph& graph, const string& numer, const string& denom, eqSeen& seen){
        double product=-1;
        

        if(graph[numer].find(denom) != graph[numer].end()){
            return graph[numer][denom];
        }
        
        if(numer == denom)
            return 1.0;

        seen[numer] = true;

        for(auto& var: graph[numer]){
            double temp = -1.0;
            if(!seen[var.first]){
                temp = traverse(graph, var.first, denom, seen);
            }
            if(temp != -1){
                product = temp * graph[numer][var.first];
                break;
            }
        }
        seen[numer] = false;
        return product;
    }
};
```

### Expected behavior

If "x" is unknown element, then test case ["x", "x"] should return 1.000 instead of -1.000

### Additional context

If an element is guarented not to be zeros, the element divided by itself should be 1.000

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

Please ask your question in the discussion forum.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
