### ISSUE TITLE
Missing Test Case - 485. Max Consecutive Ones

### ISSUE THREAD

**Issue by 1ool** [LeetCode-Feedback/LeetCode-Feedback#19555]
### LeetCode Username
iooj

### Problem number, title, and link
485. Max Consecutive Ones https://leetcode.com/problems/max-consecutive-ones/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
A test case is missing in which the maximum consecutive sequence of ones occurs in the middle of the array, with the number of elements in the array being odd. For example: `[1,0,1,1,1,0,1]`
This situation creates an edge case when using the two pointers approach, where two pointers move towards each other independently summing up ones and meet precisely in the center.

### Language used for code
Python

### Code used for Submit/Run operation
```
class Solution:
    def findMaxConsecutiveOnes(self, nums: List[int]) -> int:
        result = consecutive_right = consecutive_left = 0
        left, right = 0, len(nums) - 1
        while left <= right:
            n, m = nums[left], nums[right]
            if n == 1:
                consecutive_left += 1
            else:
                result = max(result, consecutive_left)
                consecutive_left = 0
            if m == 1:
                consecutive_right += 1
            else:
                result = max(result, consecutive_right)
                consecutive_right = 0
            left += 1
            right -= 1
        if len(nums) % 2 == 1:
            return max(result, consecutive_left , consecutive_right)
        else:
            return max(result, consecutive_left + consecutive_right)
```

### Expected behavior
The added test case will prevent inefficient solutions from being accepted.

### Screenshots
<img width="1135" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/46918716/ace6196a-1659-4e35-b710-0bb4a6e416ac">

**Comment by naXa777** [comment]
I confirm that the problem is reproducible for Python and Python3.
Link - https://leetcode.com/problems/max-consecutive-ones/submissions/1151173217

---

Please add the same test case for Kotlin.

### LeetCode Username

naXa777

### Language used for code

Kotlin

### Code used for Submit/Run operation

```kt
class Solution {
    fun findMaxConsecutiveOnes(nums: IntArray): Int {
        var result = 0
        var consecutiveRight = 0
        var consecutiveLeft = 0
        var left = 0
        var right = nums.size - 1

        while (left <= right) {
            val n = nums[left]
            val m = nums[right]
            if (n == 1) {
                consecutiveLeft++
            } else {
                result = maxOf(result, consecutiveLeft)
                consecutiveLeft = 0
            }
            if (m == 1) {
                consecutiveRight++
            } else {
                result = maxOf(result, consecutiveRight)
                consecutiveRight = 0
            }
            left++
            right--
        }

        return if (nums.size % 2 == 1) {
            maxOf(result, consecutiveLeft, consecutiveRight)
        } else {
            maxOf(result, consecutiveLeft + consecutiveRight)
        }
    }
}
```

Link - https://leetcode.com/problems/max-consecutive-ones/submissions/1151171116

### Screenshot

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/3858548/1e0b03fc-b5ac-4646-a28d-b5ea449cf9f6)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
