### ISSUE TITLE
Error in 1964. Find the Longest Valid Obstacle Course at Each Position

### ISSUE THREAD

**Issue by StrawHatDrag0n** [LeetCode-Feedback/LeetCode-Feedback#19558]
### LeetCode Username
strawhatdragon

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/19656900/ba0120a1-8292-4c04-b5a8-664d174b160f)

### Problem number, title, and link

[1964. Find the Longest Valid Obstacle Course at Each Position](https://leetcode.com/problems/find-the-longest-valid-obstacle-course-at-each-position/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug

There is a typo where the `lis[4] = 7` represents the length of `5` but the editorial mentions the length as `4`.

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team
