### ISSUE TITLE
Missing Test Case - 3011. Find if Array Can Be Sorted

### ISSUE THREAD

**Issue by AkashKalme** [LeetCode-Feedback/LeetCode-Feedback#19576]
### LeetCode Username
kalmeakash

### Problem number, title, and link
3011. Find if Array Can Be Sorted
https://leetcode.com/problems/find-if-array-can-be-sorted/

### Category of the bug
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug
Testcase is missing.

### Language used for code
C++

### Code used for Submit/Run operation
```
class Solution {
public:
    bool canSortArray(vector<int>& nums) {
        int n = nums.size();
        if(is_sorted(nums.begin(), nums.end()))
        {
            return true;
        }
        vector<int> nc(nums.begin(), nums.end());
        sort(nc.begin(), nc.end());
        for(int i=0; i<n; i++)
        {
            if(__builtin_popcount(nums[i])!=__builtin_popcount(nc[i]))
            {
                return false;
            }
        }
        vector<int> cnt(n, 0);
        for(int i=0; i<n; i++)
        {
            cnt[i] = __builtin_popcount(nums[i]);
        }
        for(int i=1; i<n-1; i++)
        {
            if(cnt[i]<cnt[i-1] && cnt[i]<cnt[i+1])
            {
                return false;
            }
        }
        return true;
    }
};
```

### Expected behavior
[16,3,1]
Output: true
Expected: false

[4,3,1]
Output: true
Expected: false

Still the solution was accepted.

> ### Screenshots
![tp](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/94354745/da99436c-0bbb-45ba-b61c-43ac22b9f842)>

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
