### ISSUE TITLE
Missing Test Case - 3011. Find if Array Can Be Sorted

### ISSUE THREAD

**Issue by v-k-1-8** [LeetCode-Feedback/LeetCode-Feedback#19578]
### LeetCode Username

v_k_18

### Problem number, title, and link

[3011. Find if Array Can Be Sorted]
(https://leetcode.com/problems/find-if-array-can-be-sorted/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [X] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

There is a testcase which a accepted subission is failing

### Language used for code

C++

### Code used for Submit/Run operation

```
#define ll int
#define nb(A) __builtin_popcountll(A)
class Solution {
public:
  
    bool canSortArray(vector<int>& nums) {
     ll n=nums.size();vector<int>ch=nums;ll p=-1;
        sort(ch.begin(),ch.end());
        for(ll i=0;i<n;i++){
            if(nums[i]!=ch[i]){p=i;break;}
            ch[i]=nb(ch[i]);
        }if(p==-1)return true;
        // cout<<p<<endl;
        // for(ll i=p;i<n;i++){ch[i]}
        ll ed=nb(nums[p]);
        for(ll i=p;i<n;i++){ll ol=nb(nums[i]);
            if(nb(nums[i])!=nb(ch[i])){
               return false;
            }if(i!=n-1&&nb(ch[i])>nb(ch[i+1]))return false;
        }return true;

    }
};
```

### Expected behavior

Testcase - [5,3,8]
Expected - TRUE
Output-  FALSE

### Screenshots

<img width="950" alt="Screenshot 2024-01-20 215326" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/130844282/32c59de1-610a-4515-b3af-3a9d017894e0">

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
