### ISSUE TITLE
Missing Test Case - 1099. Two Sum Less Than K

### ISSUE THREAD

**Issue by njha-collab** [LeetCode-Feedback/LeetCode-Feedback#1957]
#### Your LeetCode username

narendra_jha

#### Category of the bug
- Test Case

#### Description of the bug

Missing test case for sum of two identical numbers.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    
    public int twoSumLessThanK(int[] nums, int k) {
        int maxSum = -1;
        int[] count = new int[1001];
        for (int num : nums) count[num]++;
        
        int lo = 1, hi = Math.min(k-2, 1000);
        while (lo < hi) {
            if (count[lo] == 0) ++lo;
            else if (count[hi] == 0 || lo + hi >= k) --hi;
            else {
                maxSum = Math.max(maxSum, lo + hi);
                ++lo;
            }
        }
        //if (lo == hi && count[lo] > 1 && 2*lo < k) maxSum = Math.max(maxSum, lo + hi);
        
        return maxSum;
    }
}
```

#### Language used for code

Java 

#### Expected behavior

Add following test case
[5,5,5]
15

When I manually test above test case, it fails. But the solution is accepted as it's missing test case for the sum of two identical numbers.

**Comment by lc-kay** [comment]
Hi @njha-collab 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @njha-collab 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by njha-collab** [comment]
Thank you!
