### ISSUE TITLE
Missing Test Case - 14. Longest Common Prefix

### ISSUE THREAD

**Issue by KennedyUC** [LeetCode-Feedback/LeetCode-Feedback#19575]
### LeetCode Username
kennedychukwukauche

### Problem number, title, and link
14. Longest Common Prefix https://leetcode.com/problems/longest-common-prefix/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Missing Test Case. Submission was accepted even after failing my custom test case.

### Language used for code

Python3

### Code used for Submit/Run operation

```PYTHON
from typing import List

def longestCommonPrefix(strs: List[str]):
  result = ""
  index = 0
  break_tag = False
  prefix = ""
  unique_char = ""

  if len(strs) == 1:
    for char in strs:
      prefix += char

  if "" in strs[1:]:
    prefix = ""
  
  else:
    while index < len(strs[0]):
      for i in strs[1:]:
        try:
          if (strs[0][index] == i[index]):
            result += i[index]
          else:
            break_tag = True
            break
        except:
          break_tag = True

      if break_tag:
        break

      index += 1

    for char in result:
      if char not in unique_char:
          unique_char += char

    for char in unique_char:
      multiplier = result.count(char) // len(strs[1:])
      prefix += multiplier*char

  return prefix
```

### Expected behavior

input => strs = ["aba","abaaaaaaa"]

expected output = "aba"

function output = "aab"

The test cases didn't catch this, and the submission was accepted.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission Accepted link .

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by KennedyUC** [comment]
Hi

This is the requested link => https://leetcode.com/problems/longest-common-prefix/submissions/1155834580

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
