### ISSUE TITLE
Missing Test Case - 783. Search in a Binary Search Tree

### ISSUE THREAD

**Issue by Rijkstarhn** [LeetCode-Feedback/LeetCode-Feedback#1958]
#### Your LeetCode username

Rijkstarhn

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Expected answer is not expected.

#### Code you used for Submit/Run operation

```
class Solution {
    public TreeNode searchBST(TreeNode root, int val) {
        if (root == null || root.val == val) return root;
        TreeNode leftAns = searchBST(root.left, val);
        TreeNode rightAns = searchBST(root.right, val);
        return leftAns == null ? rightAns : leftAns;
    }
}
```

#### Expected behavior

The test case: [1,null,2,3,4,null,5], 5 will give an expected answer as [ ] instead of [5]. I know this may because the test case is not a BST, if so, I think an exception should be thrown.

**Comment by Rijkstarhn** [comment]
I think we can add code snippet as below in the driver code to avoid:
if (root.left >= root.right) {
    throw new IllegealArgumentException("......");
}

**Comment by lc-kay** [comment]
Hi @Rijkstarhn 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Rijkstarhn 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. Our team has updated the problem and added validators. We appreciate your support!
