### ISSUE TITLE
978. Longest Turbulent Subarray

### ISSUE THREAD

**Issue by aparajit0511** [LeetCode-Feedback/LeetCode-Feedback#196]
very poor description of the problem

**Comment by CooperCooperCooper** [comment]
Hi @aparajit0511,
Thank you for reaching out to us. To help us assess this issue, is there a particular section of this problem you would like to see improvement on?

**Comment by CooperCooperCooper** [comment]
Hi @aparajit0511,
Thank you for your time. We would like to keep the problem statement for now until further notice.
