### ISSUE TITLE
Bug - Streak icon not working at Home Page.

### ISSUE THREAD

**Issue by mastersans** [LeetCode-Feedback/LeetCode-Feedback#19602]
I know its not a good place to report bug related to UI but, the Streak button next to profile image at home page is not working for few days now.
### LeetCode Username
sanskarshrm

### Description of the bug
On hovering over the icon it shows the link that it would redirect you but on clicking on it does not do what is intended.

### Screenshots
![Screenshot 2024-01-21 105307](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/25562027/32fd4489-40f2-46b7-ab28-cd28f4262077)

### Additional context
Please fix it 🥺

**Comment by LC-Pam** [comment]
Hello,

Thank you for providing your feedback.

Please note that our GitHub repository primarily addresses content and solution-related issues. To ensure a prompt response and effective resolution for feature, function, course access, or product-related feedback, we kindly encourage you to submit such inquiries through our Zendesk Support Channel:

[LeetCode Support](https://leetcode.com/support)

Our dedicated support agents typically respond within 24 hours and promptly report submitted issues to the appropriate departments for investigation.

We greatly appreciate your ongoing support and value your contributions to enhancing the LeetCode experience.

Best regards,
LeetCode Support Team
