### ISSUE TITLE
Incorrect test case 353. Design Snake Game

### ISSUE THREAD

**Issue by luerpia** [LeetCode-Feedback/LeetCode-Feedback#1960]
#### Your LeetCode username
beiling

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
The following (or more?) test case has out-of-bound food position [58,7].
["SnakeGame","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move","move"]
[[100,30,[[11,0],[58,7]]],["D"],["R"],["R"],["D"],["D"],["U"],["D"],["R"],["L"],["R"],["U"],["D"],["D"],["R"],["R"],["U"],["D"],["R"],["D"],["D"],["D"],["D"],["U"],["D"],["L"],["D"],["U"],["D"],["U"],["D"],["R"],["L"],["L"],["R"],["D"],["L"],["U"],["L"],["L"],["L"],["R"],["R"],["U"],["R"],["L"],["D"],["R"],["L"],["U"],["U"],["D"],["D"],["D"],["L"],["L"],["D"],["L"],["D"],["R"],["U"],["L"],["U"],["R"],["R"],["U"],["L"],["D"],["L"],["D"],["D"]]
However the following example test case assumes that the first two integers are respectively width and height, and the food position integer pair is [row, col], which should be respectively within bounds [0, height) and [0, width).
["SnakeGame","move","move","move","move","move","move"]
[[3,2,[[1,2],[0,1]]],["R"],["D"],["R"],["U"],["L"],["U"]]

#### Code you used for Submit/Run operation

```
class SnakeGame {
    vector<vector<char>> board;
    vector<vector<int>>& food;
    int foodIdx=0;
    
    struct Node
    {
        int row=0;
        int col=0;
    };
    deque<Node> nodes;
    
    bool moveDir(const string& direction)
    {
        Node newHead=nodes.front();
        switch(direction[0])
        {
            case 'U':
                --newHead.row;
                break;
            case 'D':
                ++newHead.row;
                break;
            case 'L':
                --newHead.col;
                break;
            case 'R':
                ++newHead.col;
                break;
        }
        
        if(newHead.row>=0&&newHead.row<board.size()&&newHead.col>=0&&newHead.col<board[0].size())
        {
            nodes.emplace_front(newHead);
            return true;
        }
        return false;
    }
public:
    /** Initialize your data structure here.
        @param width - screen width
        @param height - screen height 
        @param food - A list of food positions
        E.g food = [[1,1], [1,0]] means the first food is positioned at [1,1], the second is at [1,0]. */
    SnakeGame(int width, int height, vector<vector<int>>& _food):food(_food){
        board.resize(height,vector<char>(width,' '));
        board[0][0]='S';
        nodes.emplace_back(Node());
        if(foodIdx<food.size())
        {
            board[food[foodIdx][0]][food[foodIdx][1]]='F';
        }
    }
    
    /** Moves the snake.
        @param direction - 'U' = Up, 'L' = Left, 'R' = Right, 'D' = Down 
        @return The game's score after the move. Return -1 if game over. 
        Game over when snake crosses the screen boundary or bites its body. */
    int move(string direction) {
        if(!moveDir(direction))
        {
            return -1;
        }
        Node head=nodes.front(); 
        if(board[head.row][head.col]=='F')
        {
            board[head.row][head.col]='S';
            if(++foodIdx<food.size())
            {
                board[food[foodIdx][0]][food[foodIdx][1]]='F';
            }
        }
        else
        {   
            const Node& tail=nodes.back();
            board[tail.row][tail.col]=' ';
            nodes.pop_back();
            if(board[head.row][head.col]=='S')
            {
                return -1;
            }
            board[head.row][head.col]='S';
        }
        return foodIdx;
    }
};
```

#### Language used for code
c++

#### Expected behavior
Test cases are inconsistent about the mapping between width, height and food position.

**Comment by lc-kay** [comment]
Hi @luerpia 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @luerpia 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
