### ISSUE TITLE
BUG - 374. Guess Number Higher or Lower

### ISSUE THREAD

**Issue by PG-Hooper** [LeetCode-Feedback/LeetCode-Feedback#19610]
### LeetCode Username

[mathemagic](https://leetcode.com/mathemagic)

### Problem number, title, and link

 374. Guess Number Higher or Lower https://leetcode.com/problems/guess-number-higher-or-lower/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

        while(true){
            if (guess(n/2) == 0) {
                return n/2;
            }
        }

The provided code snippet will always pass all tests in cpp. BUT not work in python though. Here, n must divide by some value, any. Then just return n/(that value), it will pass all tests, but if directly write it as n. It will fail for all that n != pick, but for n==pick, it will still pass.

### Language used for code

 C++ 

### Code used for Submit/Run operation

```
class Solution {
public:
    int guessNumber(int n) {
        while(true){
            if (guess(n/2) == 0) {
                return n/2;
            }
        }
    }
};
// Paste your code here. Don't remove ``` given
// above and below the code.
```

### Expected behavior

Time Limit Exceeded

### Screenshots

![Uploading Screenshot 2024-01-30 at 9.04.59 pm.png…]()

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by PG-Hooper** [comment]
<img width="1439" alt="Screenshot 2024-01-30 at 9 04 59 pm" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73980753/d07f760d-cdb2-4135-8dff-54ea7b81e06f">
please refer to this screenshot

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback. We encourage you to share your questions in the discussion forum, where the community can provide insights and assistance.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
