### ISSUE TITLE
Flame / Streak Icon not working

### ISSUE THREAD

**Issue by abhayjoshi201** [LeetCode-Feedback/LeetCode-Feedback#19611]
# Issue with Flame/Streak Icon on LeetCode

## Description

on Clicking the Flame Icon its not Responding in pages
## Steps to Reproduce

 1. Go to [LeetCode website](https://leetcode.com/).
 2. Navigate to the "Explore" page or the "Discuss" page.
 3. Attempt to click on the flame or streak icon.

## Expected Behavior
**Navigation to Problem of the Day:**
 Clicking on the flame icon should lead the user to the "Problem of the Day".
## Actual Behavior
**Flame Icon Inactivity:**
 Clicking on the flame icon does not lead to any response or navigation.

## Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/105213625/11a28338-aa67-436d-aa8f-8e050c657863)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/105213625/5f6ac241-224f-4ead-ae63-4acc1f280fed)

## Additional Information

In addition to the observed behavior mentioned above, it's worth noting that the issue seems to be more prominent or exclusive to users on light mode screens. Additional details include:

1.**Light Mode Specific:**
 The problem with the flame icon not triggering the expected navigation appears to be more prevalent when using LeetCode in light mode.

2.**Consistency Across Devices:**
 The issue has been observed consistently across different devices when using light mode.

 
## Possible Solution
few small changes in the codebase should fix the issue

**Note:**
- Make sure to check the [LeetCode Discussion](https://leetcode.com/discuss/) forums for any ongoing discussions related to this issue.
- Feel free to contribute by providing more information, testing, or suggesting solutions.
- PS: I would love to solve this, can this issue be assigned to me.

**Comment by appi147** [comment]
It happens in homepage, but works in Problems page

**Comment by abhayjoshi201** [comment]
But still its an issue

**Comment by LC-Pam** [comment]
Hello,

Thank you for providing your feedback.

Please note that our GitHub repository primarily addresses content and solution-related issues. To ensure a prompt response and effective resolution for feature, function, course access, or product-related feedback, we kindly encourage you to submit such inquiries through our Zendesk Support Channel:

[LeetCode Support](https://leetcode.com/support)

Our dedicated support agents typically respond within 24 hours and promptly report submitted issues to the appropriate departments for investigation.

We greatly appreciate your ongoing support and value your contributions to enhancing the LeetCode experience.

Best regards,
LeetCode Support Team
