### ISSUE TITLE
invalid test case expectation - 2621. Sleep

### ISSUE THREAD

**Issue by shantow-67** [LeetCode-Feedback/LeetCode-Feedback#19618]
### Category of the bug
- [ ] Incorrect expectation in test Case *( expectation output of test case is incorrect as per the problem statement)*

### Code used for Submit/Run operation

```
async function sleep(millis) {
    return new Promise((resolve) => {
    setTimeout(() => {
      resolve("Promise resolved after 100ms");
    }, millis);
  });
}

```

### Screenshots
![leetcode bug](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/126750001/bfe2919a-5247-46b6-b630-a8ec88990752)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for bringing your feedback to our attention. We've conducted a thorough investigation into the issue you raised, and after careful examination, our findings affirm that our judge is working correctly.

We appreciate the time and effort you've invested in sharing your feedback. It's invaluable to us as we work towards maintaining a high-quality platform.

Feel free to continue the dialogue here or provide any additional insights. We value your input and strive to create a collaborative space for improvement.

Best regards,
The LeetCode Team
