### ISSUE TITLE
Kotlin syntax highlighting in Solutions posts

### ISSUE THREAD

**Issue by naXa777** [LeetCode-Feedback/LeetCode-Feedback#19615]
### LeetCode Username

naXa777

### Problem number, title, and link

Not specific to any problem.
https://leetcode.com/problems/sum-of-subarray-minimums/solutions/4600152/calculate-sum-of-subarray-minimums-in-kotlin-using-monotonic-stack-o-n/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

None of the above options are suitable.
- [x] Syntax Highlighting

### Description of the bug

A glitch in syntax highlighting of `println()` string argument in the code block inside Solutions post.

This line is affected:
```kt
if (DEBUG) println("  stack pos = $pos. nums = ${pos.map { arr[it] }}")
```

### Language used for code

Kotlin

### Code

```kt
class Solution {
    fun sumSubarrayMins(arr: IntArray): Int {
        // monothonic stack
        // positions and referenced values are increasing
        val pos = Stack<Int>()
        var sum = 0L
        var right = 0
        if (DEBUG) println("init sum to $sum")

        while (right < arr.size) {
            if (DEBUG) println("step $right.")
            if (pos.isEmpty() || arr[pos.peek()] <= arr[right]) {
                pos.push(right++)
            } else {
                val rangeSum = calcRangeSum(arr = arr, pos = pos, right = right)
                if (DEBUG) println("  sum = $sum + $rangeSum")
                sum += rangeSum
            }
            if (DEBUG) println("  stack pos = $pos. nums = ${pos.map { arr[it] }}")
        }

        while (pos.isNotEmpty()) {
            if (DEBUG) println("teardown step ${pos.peek()}.")
            val rangeSum = calcRangeSum(arr = arr, pos = pos, right = right)
            if (DEBUG) println("  sum = $sum + $rangeSum")
            sum += rangeSum
            if (DEBUG) println("  stack pos = $pos. nums = ${pos.map { arr[it] }}")
        }

        return (sum % MOD).toInt()
    }

    private fun calcRangeSum(arr: IntArray, pos: Stack<Int>, right: Int): Long {
        val j = pos.pop()
        val left = if (pos.isEmpty()) -1 else pos.peek()
        val times = (right - j) * (j - left)
        if (DEBUG) println("  min(b) is ${arr[j]} * $times time${if (times > 1) 's' else ' '}")
        return arr[j].toLong() * times
    }

    private companion object {
        // set to true to turn on debug output
        const val DEBUG = false
        const val MOD = 1_000_000_007L
    }
}
```

### Expected behavior

The string argument to `println()` is properly highlighted, like on other lines.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/3858548/9a64ac62-5e93-4cf1-be30-d059d0315915)

### Additional context

Browser: Google Chrome Version 120.0.6099.225
OS: Windows 11 23H2

Compare to Kotlin syntax highlighting inside Code Editor - it works correctly.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Hi there,

This issue redirected to our developer team for investigation, it will take time to check.

Once we finish the investigation, we will re-open this ticket and get back to you. 

Thank you.
