### ISSUE TITLE
Missing Test Case - 907. Sum of Subarray Minimums

### ISSUE THREAD

**Issue by guranshdeol** [LeetCode-Feedback/LeetCode-Feedback#19622]
### LeetCode Username

guranshdeol

### Problem number, title, and link

[907. Sum of Subarray Minimums](https://leetcode.com/problems/sum-of-subarray-minimums/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support
- [x] Contributing a test case

### Description of the bug

Contributing a test case.
###### Input: 
arr = ```[5, 4, 3, 2, 1] ``` 

###### Output:
```35```

### Language used for code

Java

### Code used for Submit/Run operation

```
class Solution {
  public int sumSubarrayMins(int[] arr) {
    final int kMod = 1_000_000_007;
    final int n = arr.length;
    long ans = 0;
    int[] prevMin = new int[n];
    int[] nextMin = new int[n];
    Deque<Integer> stack = new ArrayDeque<>();

    Arrays.fill(prevMin, -1);
    Arrays.fill(nextMin, n);

    for (int i = 0; i < arr.length; ++i) {
      while (!stack.isEmpty() && arr[stack.peek()] > arr[i]) {
        final int index = stack.pop();
        nextMin[index] = i;
      }
      if (!stack.isEmpty())
        prevMin[i] = stack.peek();
      stack.push(i);
    }

    for (int i = 0; i < arr.length; ++i) {
      ans += (long) arr[i] * (i - prevMin[i]) * (nextMin[i] - i);
      ans %= kMod;
    }

    return (int) ans;
  }
}
```

### Expected behavior

When the test case : arr = ```[5, 4, 3, 2, 1] ``` runs the output should be ```35```

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/91736425/e4917c58-fcc8-4c11-98f8-a89f51800990)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for bringing your feedback to our attention. We've conducted a thorough investigation into the issue you raised, and after careful examination, our findings affirm that our judge is working correctly.

We appreciate the time and effort you've invested in sharing your feedback. It's invaluable to us as we work towards maintaining a high-quality platform.

Feel free to continue the dialogue here or provide any additional insights. We value your input and strive to create a collaborative space for improvement.

Best regards,
The LeetCode Team
