### ISSUE TITLE
Missing Test Case - 349. Intersection of Two Arrays

### ISSUE THREAD

**Issue by caltami** [LeetCode-Feedback/LeetCode-Feedback#19628]
### Category of the bug
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Language used for code
Python3

### Code used for Submit/Run operation

```
class Solution:
    def intersection(self, nums1: List[int], nums2: List[int]) -> List[int]:
        len1 = len(nums1)
        len2 = len(nums2)
        bank = []
        if len1 >= len2:
            for j in nums2:
                for i in nums1:
                    if i == j and i not in bank:
                        bank.append(i)

        if len2 > len1:
            for i in nums1:
                for j in nums2:
                    if j == i and j not in bank:
                        bank.append(j)

        return bank
```
I think that with the following test case, it should fail, because the return I get is that bank == 9,4,5,
however it should only be 9,4, correct? Since 5 is the final element in nums 1 and separated from 9,4. Official answer should be 9,4? Or maybe I'm not understanding the question.

### Additional context
Maybe I am completely wrong. Please let me know, just curious. Thank you!

**Comment by caltami** [comment]
nums1 = [9,4,9,5]
nums2 = [9,4,5,8,4]

**Comment by naXa777** [comment]
The intersection of two (or three, or four, or more) sets contains the elements common to all of the sets. The intersection of sets is a set, itself!

The intersection of sets A and B (denoted as A∩B) is the set containing the elements that are in both A and B.

Here is a graphic that visually represents the intersection of sets using Venn diagrams:
![intersection of sets](https://d20khd7ddkh5ls.cloudfront.net/intersections_sets.jpg)
_Image source: by Caroline Kulczycky_

---

> however it should only be 9,4, correct?

No.

Given,
```
nums1 = [9,4,9,5]
nums2 = [9,4,5,8,4]
```

the intersection `nums1 ∩ nums2 = [9,4,5]`

> Since 5 is the final element in nums 1 and separated from 9,4. Official answer should be 9,4?

Position of an elements doesn't matter. It doesn't change the result of intersection operation.

**Comment by caltami** [comment]
Omg… I had not understood the question in temrs of unions and
intersections! I’m so sorry.

Nevermind. I’ll carry on 😅.

Thank you so much!

Kind regards,

Chris
