### ISSUE TITLE
面试题17.07 婴儿名字 - 题目描述不清

### ISSUE THREAD

**Issue by Ssssseason** [LeetCode-Feedback/LeetCode-Feedback#1962]
**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**

当某个字典序最小的名字仅在synonyms数组中出现时，题目未说明该名字是否能够作为真实名字输出。
按题目描述，应该可以输出该名字；而目前官方程序中，该名字不会被输出。

**期望行为**
样例
```
["John(15)"]
["(Ja,John)"]
```
网站输出为
```
["John(15)"]
```

期望结果
```
["Ja(15)"]
```

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前题目问题已修复，力扣会定期更新，保障稳定和体验优化。
