### ISSUE TITLE
Missing Test Case - 198. House Robber

### ISSUE THREAD

**Issue by AbhiGaurRuneja** [LeetCode-Feedback/LeetCode-Feedback#19621]
### LeetCode Username
Abhishek Gaur Runeja [Abhishek Gaur Runeja](https://leetcode.com/abhi1408jobs)

### Problem number, title, and link
198. House Robber https://leetcode.com/problems/house-robber/

### Category of the bug
- [ ] Problem description
- [X] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [X] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
The test case [2,105,1,7,201,8,2] for the "House Robber" problem is interesting because it contains a combination of small and large values. This test case covers various scenarios that the algorithm needs to handle, such as skipping certain houses to maximize the total amount robbed, avoiding adjacent houses, and ensuring that the algorithm works efficiently for larger input sizes.

Here are some specific reasons why this test case is useful:

Adjacent Large Values: The presence of adjacent large values (e.g., 105 and 201) challenges the algorithm to make smart decisions about which houses to rob to maximize the total amount.

Alternating Small and Large Values: The alternating pattern of small (1, 7, 8) and large (105, 201) values tests whether the algorithm correctly handles the dynamic programming logic to skip houses strategically.

Edge Case: The fact that the test case starts with a small value (2) tests the algorithm's ability to handle situations where the robber might consider robbing the first house or skipping it.

Diverse Range: The test case contains a variety of values, which helps ensure that the algorithm works well across a diverse range of inputs.

Mixed Positives: The mixture of positive values ensures that the algorithm correctly identifies the houses to rob for maximizing the total amount, without being misled by negative values.

By using this test case, you can gain confidence in the correctness and efficiency of your algorithm, as it needs to handle a range of scenarios typical of the "House Robber" problem.

### Code used for Submit/Run operation
```
from typing import List

class Solution:
    def rob(self, nums: List[int]) -> int:
        if not nums:
            return 0

        dp = [0] * len(nums)
        dp[0] = nums[0]

        for i in range(1, len(nums)):
            print(f"dp is {dp}")
            if i - 2 >= 0:
                dp[i] = max(dp[i - 1], dp[i - 2] + nums[i])
            else:
                dp[i] = max(dp[i - 1], nums[i])

        return dp[-1]

```

### Screenshots
<img width="1440" alt="Screenshot 2024-01-21 at 11 18 22 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/157309039/9c135faa-e790-4355-9b00-5ac32ec3c843">

### Additional context

Test Case
[2,105,1,7,201,8,2]

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

[2,105,1,7,201,8,2] already exists. 

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
