### ISSUE TITLE
Completion Streak counts from 0 

### ISSUE THREAD

**Issue by Y-Rov** [LeetCode-Feedback/LeetCode-Feedback#19634]
### LeetCode Username

[anacondrai](https://leetcode.com/anacondrai)

### Category of the bug
- [ ] Counting

### Description of the bug

Hello, LeetCode team 😄

Today, the popup with the completion streak showed me that my streak is "0 Day".

### Expected behavior

Previously, the count was started from 1, is that a new counting system or a bug?

### Screenshots

![Streak_0_Day](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73534920/2e797032-124a-47c6-9734-7f525cd06e1b)

**Comment by LC-Pam** [comment]
Hello,

Thank you for providing your feedback.

Please note that our GitHub repository primarily addresses content and solution-related issues. To ensure a prompt response and effective resolution for feature, function, course access, or product-related feedback, we kindly encourage you to submit such inquiries through our Zendesk Support Channel:

[LeetCode Support](https://leetcode.com/support)

Our dedicated support agents typically respond within 24 hours and promptly report submitted issues to the appropriate departments for investigation.

We greatly appreciate your ongoing support and value your contributions to enhancing the LeetCode experience.

Best regards,
LeetCode Support Team

**Comment by Y-Rov** [comment]
Thank you, @LC-Pam, for the clarification 🙂
