### ISSUE TITLE
Missing testcase - 3006. Find Beautiful Indices in the given array I

### ISSUE THREAD

**Issue by Trilasha** [LeetCode-Feedback/LeetCode-Feedback#19637]
### LeetCode Username

Trilasha_Mazumder

### Problem number, title, and link

1) Find Beautiful Indices in the given array I : https://leetcode.com/problems/find-beautiful-indices-in-the-given-array-i/description/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

My code received an accepted verdict but it should give wrong answer for the given testcase

s="szzdko"
a="dk"
b="d"
k=2

Output : []
Expected answer: [3]

### Language used for code

C++

### Code used for Submit/Run operation

```
#define sz(x)               (int)(x).size()   
class Solution {
public:

    int nearest(vector<int>&v,int x){
        if(v.size()<1) return -1;
        int l=0,r=sz(v)-1,ans=-1;
        while(l<=r){
            int mid=(l+r)/2;
            if(v[mid]==x) return mid;
            else if(v[mid]>x) r=mid-1;
            else l=mid+1;
        }
        if(r<0) return v[l];
        if(l>=sz(v)) return v[r];
        if(abs(v[l]-x)<abs(v[r]-x)) return v[l];
        return v[r];
    }
    vector<int> beautifulIndices(string s, string a, string b, int k) {
        vector<int>v1,v2;
        for(int i=0;i<sz(s)-sz(a)+1;i++){
            if(s.substr(i,sz(a))==a) v1.push_back(i);
        }
        for(int i=0;i<sz(s)-sz(b)+1;i++){
            if(s.substr(i,sz(b))==b) v2.push_back(i);
        }
        vector<int>ans;
        for(auto x:v1){
            int y=nearest(v2,x);
            // cout<<x<<" "<<y<<endl;
            if(abs(x-y)<=k and y!=-1) ans.push_back(x);
        }
        return ans;
    }
};
```

### Expected behavior

As per the code there is no beautiful index for the above mentioned testcase so it is returning an empty array, however there exists a beautiful index which is 3(as per 0-based indexing) so the expected answer is [3], which is different from the output of the code.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/95575615/1b378616-c47d-4369-bc9b-2f54bffd859b)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/95575615/cc18e609-3a0a-4ce9-a9ba-68399762571d)

### Additional context

Submission link: https://leetcode.com/problems/find-beautiful-indices-in-the-given-array-i/submissions/1153451499/

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
