### ISSUE TITLE
Same hints in Question #1598

### ISSUE THREAD

**Issue by ViratJinjala** [LeetCode-Feedback/LeetCode-Feedback#19632]
### Category of the bug

- Problem hints

### Description of the bug
There's 2 hints in the question but both are same.

### Expected behavior
Remove extra hint or change it

### Screenshots
![Screenshot 2024-01-22 103730](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/155998278/bd838911-1137-475e-a4db-977ac97e3c34)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team
