### ISSUE TITLE
Completion Streak Mismatch bug

### ISSUE THREAD

**Issue by Kushal1605** [LeetCode-Feedback/LeetCode-Feedback#19638]
### LeetCode Username
Kushal1605

### Problem number, title, and link
https://leetcode.com/problems/set-mismatch/description/?envType=daily-question&envId=2024-01-22

### Category of the bug
- [] Incorrect Completion Streak Count

### Description of the bug
My current Completion streak Count is 83 but when I submitted today's daily problem it shows 0.

### Language used for code
Java

### Code used for Submit/Run operation

```
class Solution {
    public int[] findErrorNums(int[] nums) {
        int temp = -1;
        for (int i = 0; i < nums.length; i++) {
            int idx = Math.abs(nums[i]) - 1;

            if (idx == -1) {
                idx = temp - 1;
            }

            if (nums[idx] < 0) {
                temp = -nums[idx];
                nums[idx] = 0;
            } else if (nums[idx] == 0) {
                nums[temp - 1] = -nums[temp - 1];
            } else {
                nums[idx] = -nums[idx];
            }
        }
        
        int[] ans = new int[2];
        for (int i = 0; i < nums.length; i++) {
            if (nums[i] > 0) {
                ans[1] = i + 1;
            }

            if (nums[i] == 0) {
                ans[0] = i + 1;
            }
        }
        return ans;
    }
}
```

### Expected behavior
Completion Streak Should be 83

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/115387392/cf27ae86-ee5a-45d2-88ef-b88431d8c2e7)

**Comment by LC-Pam** [comment]
Hello,

Thank you for providing your feedback.

Please note that our GitHub repository primarily addresses content and solution-related issues. To ensure a prompt response and effective resolution for feature, function, course access, or product-related feedback, we kindly encourage you to submit such inquiries through our Zendesk Support Channel:

[LeetCode Support](https://leetcode.com/support)

Our dedicated support agents typically respond within 24 hours and promptly report submitted issues to the appropriate departments for investigation.

We greatly appreciate your ongoing support and value your contributions to enhancing the LeetCode experience.

Best regards,
LeetCode Support Team
