### ISSUE TITLE
Missing Topic - Math - 645. Set Mismatch

### ISSUE THREAD

**Issue by naXa777** [LeetCode-Feedback/LeetCode-Feedback#19641]
### LeetCode Username

naXa777

### Problem number, title, and link

[645. Set Mismatch](https://leetcode.com/problems/set-mismatch/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [x] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

It's posible to solve the problem with a clever math trick in O(1) space. But it's not categorized as a "Math" problem.

Accepted solution submission link - https://leetcode.com/problems/set-mismatch/submissions/1153576660/

### Language used for code

Kotlin (but this ticket is not specific to any language)

### Code used for Submit/Run operation

```kt
infix fun Int.`**`(exponent: Int): Int = toDouble().pow(exponent).toInt()

class Solution {
    fun findErrorNums(nums: IntArray): IntArray {
        // The math solution is based on a system of equations:
        // {
        //   D - M = x,
        //   D^2 - M^2 = y
        // }

        var x = 0
        var y = 0
        for (i in 0 until nums.size) {
            x += nums[i] - i - 1
            y += (nums[i] `**` 2) - ((i + 1) `**` 2)
        }

        // Given that we know x and y now,
        // we are able to solve the system of equations to find D (duplicate) and M (missing):

        // 1st.
        // D = x + M
        
        // 2nd.
        // (x + M)^2 - M^2 = y
        //      ->
        // x^2 + M^2 + 2Mx - M^2 = y
        //      ->
        // 2Mx = (y - x^2)
        //      ->
        // M = (y - x^2) / 2x

        val missing = (y - (x `**` 2)) / (2 * x)
        val duplicate = x + missing
        return intArrayOf(duplicate, missing)
    }
}
```

### Expected behavior

Add "Math" badge to the related topics.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/3858548/4e1d0504-d73d-46e6-9298-c7b39c51df02)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
