### ISSUE TITLE
Missing Test Case - 89. Gray Code

### ISSUE THREAD

**Issue by Bambooin** [LeetCode-Feedback/LeetCode-Feedback#1964]
#### Your LeetCode username

0x4C0DE

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Test case reject valid input 0

Invalid Testcase
expected 'n' to have value from 1 to 16 only

conflict with decription '0 <= n <= 15'

#### Code you used for Submit/Run operation

```
// https://leetcode.com/problems/gray-code/
class Solution {
  public List<Integer> grayCode(int n) {
    List<Integer> result = new ArrayList<>(1 << n);

    result.add(0);
    result.add(1);

    int length;
    for (int i = 2; i <= n; i++) {
      length = result.size();
      for (int j = length - 1; j >= 0; j--) {
        result.add((1 << (i - 1)) + result.get(j));
      }
    }

    return result;
  }
}
```

#### Language used for code

Java

#### Expected behavior

This code should be rejected for input 0, but it has been accepted.

**Comment by lc-kay** [comment]
@Bambooin 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Bambooin 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
