### ISSUE TITLE
Description Typo - 2990. Loan Types

### ISSUE THREAD

**Issue by xelplogoog** [LeetCode-Feedback/LeetCode-Feedback#19646]
### LeetCode Username
c4tdog

### Problem number, title, and link
[2990. Loan Types](https://leetcode.com/problems/loan-types/)

### Category of the bug
- [ ] Problem description

### Description of the bug
Example #1 says the table name is `sessions` whereas it is `loans`

<img width="730" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2188302/079cdd8d-0a7e-446a-93a1-b4b2dee2a26d">

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
