### ISSUE TITLE
Missing Test Case - 645. Set Mismatch

### ISSUE THREAD

**Issue by contributerMe** [LeetCode-Feedback/LeetCode-Feedback#19643]
### LeetCode Username
nimesh_3010

### Problem number, title, and link
645. Set Mismatch https://leetcode.com/problems/set-mismatch/

### Category of the bug
- [ ] Problem description

### Description of the bug
It  is not mentioned in the probelm description that we need to return the vector elements in the order of  {number that occured twice, Number that is not present}

### Language used for code
C++

### Code used for Submit/Run operation

```
class Solution {
public:
    vector<int> findErrorNums(vector<int>& nums) {
        set<int> st;
        vector<int> ans(2);

        // Insert all elements into set
        int n = nums.size();
        for(int i = 0 ; i < n; i++) {
            st.insert(nums[i]);
        }

        // Find the missing number
        int notPresent = 0;
        for(int i = 1; i <= n; i++) {
            if(st.find(i) == st.end()) {
                // Means i is not present in the set 
                notPresent = i ;
                break;
            }
        }

        int sumIdeal = n * (n + 1) / 2;
        int sumActual = accumulate(nums.begin(), nums.end(), 0);
        int repeted = sumActual - sumIdeal + notPresent;
        ans[0] = repeted ;
        ans[1] = notPresent;
        return ans;
    }
};
```

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
