### ISSUE TITLE
【题目描述不清】547题，省份数量

### ISSUE THREAD

**Issue by chiliren** [LeetCode-Feedback/LeetCode-Feedback#1965]
**Bug 类型**
- [Y ] 题目

**描述**
题目描述不清

**你使用的语言**
C

**你提交或者运行的代码**
见截图

**期望行为**
描述你期望的结果

**屏幕截图**
![image](https://user-images.githubusercontent.com/31127471/104176871-e0bd2900-5442-11eb-9300-2135a05a5e49.png)

**额外的上下文**
不涉及

**Comment by feiceh** [comment]
感谢反馈，此反馈已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，想了解一下建议改成什么呢？是想改成二维数组吗？

**Comment by feiceh** [comment]
你好，因长时间未得到回复，我们先暂时关闭该 issue，如有更多反馈和建议请与我们联系。
