### ISSUE TITLE
496. 下一个更大元素 I 增加进阶要求

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#1966]
**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
第 496 题由于数据规模较小，因此可以用 O(n^2) 的做法实现。
实际面试时，面试官可能会要求面试者实现复杂度更低的做法，使用单调栈可以将时间复杂度降低至 O(n)。
因此建议增加进阶要求，使用时间复杂度 O(n) 的算法解决此问题。
中文描述和英语描述需要同步更新。

**你使用的语言**
Java

**你提交或者运行的代码**

**期望行为**
增加进阶要求，中文描述和英语描述需要同步更新。

**屏幕截图**

**额外的上下文**

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前题目英文进阶要求已添加， 中文描述已同步更新。
