### ISSUE TITLE
Dequeue button not working

### ISSUE THREAD

**Issue by Sweetdevil144** [LeetCode-Feedback/LeetCode-Feedback#19674]
### LeetCode Username
Sweetdevil144

### Problem number, title, and link
https://leetcode.com/explore/learn/card/queue-stack/228/first-in-first-out-data-structure/1355/
**It is a lesson on Stacks and queues**

### Category of the bug
- [x] Programming language support
- [x] Bug in Lessons

### Description of the bug

On clicking the dequeue button in the lesson examples, no action takes place.

### Language used for code
Java

### Expected behavior

It should dequeue from the head the first element.

### Screenshots

https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/117591942/62114812-38c6-4db7-ae04-0a40c11bfef1

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback. The dequeue button is working correctly.

<img width="569" alt="Screen Shot 2024-01-23 at 3 25 12 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/1f80dced-2afe-441a-9b61-8901aeab9f03">
<img width="620" alt="Screen Shot 2024-01-23 at 3 25 17 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/904c7f35-fd28-4c5e-af06-66807ae23629">


If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
