### ISSUE TITLE
Test case wrong - 1488. Avoid Flood in The City

### ISSUE THREAD

**Issue by nvdung1698** [LeetCode-Feedback/LeetCode-Feedback#1967]
#### Your LeetCode username

dungx

#### Category of the bug
- [ ] Question
- [ x] Solution
- [ ] Language

#### Description of the bug

Wrong test case

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Additional context

![image](https://user-images.githubusercontent.com/29591535/104190004-07349180-544e-11eb-9db4-6082821678d0.png)

**Comment by lc-kay** [comment]
@nvdung1698 The expected output is correct. Please refer to the discuss section to raise your question or find similar posts. Thank you for your time.

**Comment by nvdung1698** [comment]
@lc-kay the output is also correct. In the question, they said that if there are multiple solutions, print one.

**Comment by lc-kay** [comment]
@nvdung1698 Can you please provide the code you used?

**Comment by nvdung1698** [comment]
@lc-kay I'm using this code
`class Solution(object):
    def avoidFlood(self, rains):
        fullLakes = {}
        ans = [-1] * len(rains)
        dryDays = []

        for idx in range(len(rains)):
            rain = rains[idx]

            if rain > 0:
                if rain in fullLakes:
                    if not dryDays:
                        return []
                    else:
                        couldDry = False
                        for dryDayIdx in range(len(dryDays)):
                            if dryDays[dryDayIdx] > fullLakes[rain]:
                                dayIdx = dryDays.pop(dryDayIdx)
                                ans[dayIdx] = rain
                                couldDry = True
                                break
                        if not couldDry:
                            return []
                else:
                    fullLakes[rain] = idx
            elif rain == 0:
                dryDays.append(idx)
                ans[idx] = 1

        return ans`

**Comment by nvdung1698** [comment]
Sorry @lc-kay, My mistake.
