### ISSUE TITLE
Missing Test Case - 456. 132 Pattern

### ISSUE THREAD

**Issue by belousovbb** [LeetCode-Feedback/LeetCode-Feedback#19687]
### LeetCode Username

[Bingo_o](https://leetcode.com/Bingo_o)

### Problem number, title, and link

456. 132 Pattern https://leetcode.com/problems/132-pattern

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

There is a missing test case. I have a solution that received AC, but I found a test case where I received a wrong answer.

### Language used for code

Rust

### Code used for Submit/Run operation

```
use std::collections::*;

impl Solution {
pub fn find132pattern(nums: Vec<i32>) -> bool {
    let mut tree: BTreeMap<i32, i32> = BTreeMap::new(); // key - left bound of interval, value - right bound
    let mut stack = Vec::new();
    for i in 0..nums.len() {
        if let Some(overlap_interval) = tree.range(..nums[i]).next_back() {
            if *overlap_interval.1 > nums[i] {
                return true;
            }
        }

        let last = stack.last().copied().unwrap_or(i32::MIN);
        if last <= nums[i] {
            stack.push(nums[i]);
            continue;
        }

        let first = *stack.first().unwrap();
        if first < nums[i] {
            return true;
        }
        let new_interval = (first, last);
        
        for (r, l) in tree.range(first..last).map(|(&r, &l)| (r, l)).collect::<Vec<_>>() {
            tree.remove(&r);
            
        }
        tree.insert(first, last);
        
        stack.clear();
        stack.push(nums[i]);
    }
    
    false
}

}
```

### Expected behavior

I should get Wrong Answer instead of AC on solution above.

### Screenshots

<details>
  <summary>AC with "wrong answer"</summary>

  <img width="1290" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/24768663/0b3c1ee5-fc88-42df-9c03-1d3e8af23c3d">
</details>

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by belousovbb** [comment]
Hello, @LC-Pam!

Sure.

Submitted code: https://leetcode.com/submissions/detail/1155177381/
Test case, when I get Wrong Answer with solution above: [3, 5, 3, 2, 1, 4]

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
