### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by convers39** [LeetCode-Feedback/LeetCode-Feedback#1969]
#### Your LeetCode username

convers39

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

When I copy solution codes from other text editors, some time it reports tab indentation error
This typically occur when the text editor has a default tab setting as 2 spaces, while I am using Python in leetcode editor which assumes a 4spaces tab.
Notice that even I copied from 2 spaces tab external editor, I DID change it to 4 spaces as required, still it will show this error.
`TabError: inconsistent use of tabs and spaces in indentation`

This should definitely be fixed, ridiculous issue. I cannot run my code if I write them in external editors.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

Python3

#### Expected behavior

Run my code

#### Screenshots

![image](https://user-images.githubusercontent.com/42597395/104204621-d2860180-5470-11eb-9ef1-8bb63dbe81e4.png)

**Comment by lc-kay** [comment]
Hi @convers39 
Thank you for your time. Upon investigating this issue, we found this issue to be non-content-related (the issue stems from an origin away from the content on this problem); therefore, it's not valid for content contribution reward. 
Please file this issue to support@leetcode.com Thank you again for your support and understanding.
