### ISSUE TITLE
347. Top K Frequent Elements - O(n) Solution

### ISSUE THREAD

**Issue by 0xC0D3D00D** [LeetCode-Feedback/LeetCode-Feedback#197]
**What kind of the bug**
- [ ] problem
- [x] solution
- [ ] language

**Describe the solution**
Using a hashmap to track frequencies of each number `count` and another map for reverse lookups `freq`, it is possible to solve this problem in linear time.

Time complexity: `O(n+k)`
Space complexity: `O(2n)` for two hashmaps

**what language is your code written in**
Javascript

**The code you submit/run**
```javascript
/**
 * @param {number[]} nums
 * @param {number} k
 * @return {number[]}
 */
var topKFrequent = function(nums, k) {
  let freqs = {};
  let counts = {};
  let maxCount = 0;
  for (let i=0; i<nums.length; i++) {
    const num = nums[i];
    let count = counts[num];
    if (count === undefined) {
      count = 0;
      counts[num] = 0;
    }
    counts[nums[i]]++;
    if (freqs.hasOwnProperty(count)) {
      delete freqs[count][num];
    }
    if (!freqs.hasOwnProperty(count+1)) {
      freqs[count+1] = {};
    }
    freqs[count+1][num] = true;
    if (counts[num] > maxCount) {
      maxCount = counts[num];
    }
  }

  let results = [];
  while (results.length < k) {
    const maximums = Object.keys(freqs[maxCount]);
    results = results.concat(maximums);
    maxCount--;
  }
  return results;
};
```

**Comment by CooperCooperCooper** [comment]
Hi @0xC0D3D00D,
Thank you for reaching out. I've relayed your feedback to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @0xC0D3D00D ,
Thank you for your contribution. The article is rewritten and published. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
