### ISSUE TITLE
Missing Test Case - 326. Power of Three

### ISSUE THREAD

**Issue by sunilkumar123ss** [LeetCode-Feedback/LeetCode-Feedback#1970]
#### Your LeetCode username

sunil_pabba12

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
// power of three
class Solution {
public:
    bool isPowerOfThree(int n) {
        if(n==0)
        {
            return 0;
        }while(n!=1)
        {
            if(n%3!=0)
                return 0;
            n=n/3;
        }return 1;
    }
};
```

#### Language used for code

C++

**Comment by lc-kay** [comment]
@sunilkumar123ss Please provide the missing test case. Thank you!

**Comment by lc-kay** [comment]
Hi @sunilkumar123ss 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
