### ISSUE TITLE
Missing Test Case - 144. Binary Tree Preorder Traversal

### ISSUE THREAD

**Issue by raja9112** [LeetCode-Feedback/LeetCode-Feedback#19718]
### LeetCode Username

user1418Ln

### Problem number, title, and link

https://leetcode.com/problems/binary-tree-preorder-traversal/description/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [X ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Pro order traversal of binary tree output format is value of root node, right node and left node, After ran the code the normal 3 test cases are passed but while submitting one of the test cases of 70 test cases fails. The failed test case's expected output was post order traversal's output. Attached screenshot of bug for your reference.

### Language used for code

Python

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.

# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
class Solution:
    def preorderTraversal(self, root: Optional[TreeNode]) -> List[int]:
        res =[]
        if not root:
            return res
        res.append(root.val)
        if root.right:
            res.extend(self.preorderTraversal(root.right))
        if root.left:
            res.extend(self.preorderTraversal(root.left))

        return res
```

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/126778382/3b88bd66-19c5-4862-9d93-e059f30fe36e)

**Comment by KrishChopra22** [comment]
Dude, you're mistaken. 
Pre-Order traversal of Binary Tree is -  **`root -> root.left -> root.right`**

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team

**Comment by raja9112** [comment]
> Dude, you're mistaken. Pre-Order traversal of Binary Tree is - **`root -> root.left -> root.right`**

Thank you dude, I found my mistake after raising bug feedback, lol. Thank you for your time.
