### ISSUE TITLE
Missing Test Case - 420. Strong Password Checker

### ISSUE THREAD

**Issue by MessyKinkajou91** [LeetCode-Feedback/LeetCode-Feedback#19714]
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ X ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### If i understood, in one step we can make only a insertion, a deletion or a swamp. But i did not understand my error in the test case number 22: (aaaB1). Please, if someone explain me this i will be gratefull. 

###Program Language: C

### Code used for Submit/Run operation

```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
//https://leetcode.com/problems/strong-password-checker/

int strongPasswordChecker(char* password) {
	int digits[10] = {'0','1','2','3','4','5','6','7','8','9'};
	char low_letters[26] = {'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'};
	char upper_letters[26] = {'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z'};
	
	int result = 0;
    int len = strlen(password);
	int quant_dig = 0;
	int quant_lows = 0;
	int quant_uppers = 0;
	bool check = false;

	
	

	//Compare each character in the password and check that there is at least one lowercase letter, one saved letter and one digit
	for (int i = 0; i < len; i++){
		for(int x = 0; x < 10; x++){
			if (password[i] == digits[x]){ //if there are none of the 10 digits (quant_dig = 0), increase the number of steps in the future
				quant_dig += 1;
			}
			}
			}; 
	for (int i = 0; i < len; i++){
		for(int x = 0; x < 26; x++){
			if (password[i] == low_letters[x]){ //if there are none of the 26 lowercase characters (quant_lows = 0), increase the number of steps in the future
				quant_lows+= 1;
			}
			}
			}; 
	for (int i = 0; i < len; i++){
		for(int x = 0; x < 26; x++){
			if (password[i] == upper_letters[x]){ //if there are none of the 26 lowercase characters (quant_uppers = 0), increase the number of steps in the future
				quant_uppers += 1;
			}; 
	}
	}
	//check if there are three characters repeated in sequence
	for (int j = 0; j < len - 2; j++ ){
		if (password[j] == password[j+1] && password[j] == password[j+2]){
			result += 1;
			check = true;
		}}

	if (len < 6){ //check how many characters are left for the password to have at least 6 characters
		result += (6 - len);
		}
	
	if (quant_dig == 0 && len >= 6){
		if (!(check)){
			result += 1;
		}
	}
	if (quant_lows == 0 && len >= 6){
		if (!(check)){
			result += 1;
		}
	}
	if ( quant_uppers == 0 && len >= 6){
		if (!(check)){
			result += 1;
		}
	}
	
	
	return result;
}
```

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
