### ISSUE TITLE
Unexpected behaviour of compiler

### ISSUE THREAD

**Issue by tiwarishubham635** [LeetCode-Feedback/LeetCode-Feedback#19715]
### LeetCode Username

[the_engineer_who_codes](https://leetcode.com/the_engineer_who_codes/)

### Problem number, title, and link

[1457. Pseudo-Palindromic Paths in a Binary Tree](https://leetcode.com/problems/pseudo-palindromic-paths-in-a-binary-tree/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [x] Programming language support

### Description of the bug

I tried submitting my C++ code via the editor and the compiler was unnecessarily throwing runtime error. I checked with various other compilers and all of them worked with it. Extra calls were being made to the function apart from the expected input.

### Language used for code

C++

### Code used for Submit/Run operation

```
class Solution {
    bool isPseudoPalindrome(string str) {
        vector<int>freq(9, 0);
        for(char &ch: str)
            freq[ch - '0']++;
        int ctr = 0;
        for(int &val: freq)
            if(val&1) // val is odd
                ctr++;
        return (ctr == 0 || ctr == 1);
    }

public:
    int pseudoPalindromicPaths(TreeNode* root, string str = "") {
        if(root == NULL)
            return 0;
        
        string new_str = str + to_string(root->val);
        if((root->left == NULL) && (root->right == NULL))
            return isPseudoPalindrome(new_str);
        
        int ans = pseudoPalindromicPaths(root->left, new_str) + 
                  pseudoPalindromicPaths(root->right, new_str);
        return ans;
    }
};
```

### Expected behavior

It should run the code for the root node and return the ans. For testcase - root = [2,3,1,3,1,null,1], it should give the output as 2. This was verified with other compilers.

### Screenshots

![Screenshot 2024-01-24 at 11 21 39 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/59199353/6ec59247-e334-4eff-8779-66b315d70e00)

### Additional context

Surprisingly other methods are working but this code is broken for absolutely no reason.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback. We encourage you to share your questions in the discussion forum, where the community can provide insights and assistance.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
