### ISSUE TITLE
Something wrong in editorial - 1457. Pseudo-Palindromic Paths in a Binary Tree

### ISSUE THREAD

**Issue by KrishChopra22** [LeetCode-Feedback/LeetCode-Feedback#19719]
#### Category of the bug
- [x] Question
- [x] Editorial
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the 1st Approach of the editorial of the problem [1457. Pseudo-Palindromic Paths in a Binary Tree](https://leetcode.com/problems/pseudo-palindromic-paths-in-a-binary-tree/)
The slide-video showed the iterative In-Order Traversal whereas the title & the solution was completely based on Pre-Order Traversal.

Fix : 
The video(slides) was of iterative InOrder Traversal, it should be changed to that of the iterative PreOrder Traversal.

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/77012237/2ae2fbbd-d747-49d6-a760-b1b530a08115)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by KrishChopra22** [comment]
Any updates?

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
