### ISSUE TITLE
Error with latest premium question 3018. Maximum Number of Removal Queries That Can Be Processed I

### ISSUE THREAD

**Issue by bclodius** [LeetCode-Feedback/LeetCode-Feedback#19726]
### LeetCode Username
[b_clodius](https://leetcode.com/b_clodius/)

### Problem number, title, and link
https://leetcode.com/problems/maximum-number-of-removal-queries-that-can-be-processed-i/description/

### Category of the bug
- [x] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
The question mentions the constraint as a `subarray` but there are multiple examples that seem to indicate the question was meant to be authored with `subsequence`.

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/590724/802896d6-d496-4d93-89be-c7306832b041)

### Language used for code
N/A

#### Test case

```
[2,1,4,1,3]
[2,3,4]
```

Assuming the aforementioned test case the best we can select is subarray `[2,1,4]` or `[4,1,3]` or `[2,1,4,1,3]`.

Choosing any of these arrays the best number of operations we can achieve is 2 because our 3rd operation in queries is `4` but the only value we have left is `1` on either end.

The online judge shows the answer as `3`.  This is only possible if we're able to create a `subsequence` of `[2,4,3]`.

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/590724/c43d7da4-19d6-43aa-a4fc-c1ceff306299)

### Expected behavior
The online judge should respect the constraints of the original problem.

### Additional context
Many other examples from users are available in the new question's discussion.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by bclodius** [comment]
I see the question has since been updated to reflect the proper criteria.

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/590724/632efcd0-9858-40aa-b140-d061899fb7fc)
