### ISSUE TITLE
Missing Test Case - 399. Evaluate Division

### ISSUE THREAD

**Issue by Jeffrey940421** [LeetCode-Feedback/LeetCode-Feedback#19723]
### LeetCode Username

[zhangqy940421](https://leetcode.com/zhangqy940421)

### Problem number, title, and link

https://leetcode.com/problems/evaluate-division/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Some solutions with O(n^2) time complexity got accepted because the size constraints of equations and queries array. The solution should have O(n) time complexity.

### Language used for code

JavaScript

### Code used for Submit/Run operation

Test case to reject O(n^2) solutions
```
// 20000 items for each array
equations = [
  [ 'a0', 'a1' ],   [ 'a1', 'a2' ],   [ 'a2', 'a3' ],   [ 'a3', 'a4' ],
  [ 'a4', 'a5' ],   [ 'a5', 'a6' ],   [ 'a6', 'a7' ],   [ 'a7', 'a8' ],
  [ 'a8', 'a9' ],   [ 'a9', 'a10' ],  [ 'a10', 'a11' ], [ 'a11', 'a12' ],
  [ 'a12', 'a13' ], [ 'a13', 'a14' ], [ 'a14', 'a15' ], [ 'a15', 'a16' ],
  [ 'a16', 'a17' ], [ 'a17', 'a18' ], [ 'a18', 'a19' ], [ 'a19', 'a20' ],
  [ 'a20', 'a21' ], [ 'a21', 'a22' ], [ 'a22', 'a23' ], [ 'a23', 'a24' ],
  [ 'a24', 'a25' ], [ 'a25', 'a26' ], [ 'a26', 'a27' ], [ 'a27', 'a28' ],
  [ 'a28', 'a29' ], [ 'a29', 'a30' ], [ 'a30', 'a31' ], [ 'a31', 'a32' ],
  [ 'a32', 'a33' ], [ 'a33', 'a34' ], [ 'a34', 'a35' ], [ 'a35', 'a36' ],
  [ 'a36', 'a37' ], [ 'a37', 'a38' ], [ 'a38', 'a39' ], [ 'a39', 'a40' ],
  [ 'a40', 'a41' ], [ 'a41', 'a42' ], [ 'a42', 'a43' ], [ 'a43', 'a44' ],
  [ 'a44', 'a45' ], [ 'a45', 'a46' ], [ 'a46', 'a47' ], [ 'a47', 'a48' ],
  [ 'a48', 'a49' ], [ 'a49', 'a50' ], [ 'a50', 'a51' ], [ 'a51', 'a52' ],
  [ 'a52', 'a53' ], [ 'a53', 'a54' ], [ 'a54', 'a55' ], [ 'a55', 'a56' ],
  [ 'a56', 'a57' ], [ 'a57', 'a58' ], [ 'a58', 'a59' ], [ 'a59', 'a60' ],
  [ 'a60', 'a61' ], [ 'a61', 'a62' ], [ 'a62', 'a63' ], [ 'a63', 'a64' ],
  [ 'a64', 'a65' ], [ 'a65', 'a66' ], [ 'a66', 'a67' ], [ 'a67', 'a68' ],
  [ 'a68', 'a69' ], [ 'a69', 'a70' ], [ 'a70', 'a71' ], [ 'a71', 'a72' ],
  [ 'a72', 'a73' ], [ 'a73', 'a74' ], [ 'a74', 'a75' ], [ 'a75', 'a76' ],
  [ 'a76', 'a77' ], [ 'a77', 'a78' ], [ 'a78', 'a79' ], [ 'a79', 'a80' ],
  [ 'a80', 'a81' ], [ 'a81', 'a82' ], [ 'a82', 'a83' ], [ 'a83', 'a84' ],
  [ 'a84', 'a85' ], [ 'a85', 'a86' ], [ 'a86', 'a87' ], [ 'a87', 'a88' ],
  [ 'a88', 'a89' ], [ 'a89', 'a90' ], [ 'a90', 'a91' ], [ 'a91', 'a92' ],
  [ 'a92', 'a93' ], [ 'a93', 'a94' ], [ 'a94', 'a95' ], [ 'a95', 'a96' ],
  [ 'a96', 'a97' ], [ 'a97', 'a98' ], [ 'a98', 'a99' ], [ 'a99', 'a100' ],
  ...
]

values = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...]
queries = [["a1", "a20000"], ["a1", "a20000"], ["a1", "a20000"], ["a1", "a20000"], ["a1", "a20000"], ...] 
```

### Expected behavior

Solutions with O(n^2) time complexity get rejected while solutions with O(n) time complexity get accepted

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

We can’t add the test case currently because of technical issues.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
