### ISSUE TITLE
Description of area and population unit Missing Test Case - 595. Big Countries

### ISSUE THREAD

**Issue by QuadirMariyam** [LeetCode-Feedback/LeetCode-Feedback#19727]
### LeetCode Username

[Mariyam_Quadir](https://leetcode.com/Mariyam_Quadir)

### Problem number, title, and link

595, Big Countries, https://leetcode.com/problems/big-countries/description/ 

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [1] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

mention of area and population units in the table is missing. It does not match with the requirement unit measure.

### Language used for code

Python

### Code used for Submit/Run operation

run my code because at least of 3000000 km square is asked in the description to qualify Big Country. But there's no unit in the schema so looking at my test case I had to deduct 1 zero

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
