### ISSUE TITLE
Missing Test Case - 3011. Find if Array Can Be Sorted

### ISSUE THREAD

**Issue by ayushkr012** [LeetCode-Feedback/LeetCode-Feedback#19734]
### LeetCode Username

ayushkr01

### Problem number, title, and link

[3011. Find if Array Can Be Sorted](https://leetcode.com/problems/find-if-array-can-be-sorted/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

code is Accepted but for this test case -----> `[174, 175, 236, 188]` it fails when You Exclude this test case Then Code is Accepted

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/136481697/1e49c09c-c236-4c33-91dd-eb26f786c5ce)

### Language used for code

C++

### Code used for Submit/Run operation

```
#include <vector>
#include <unordered_map>
#include <queue>

using namespace std;

class Solution {
public:
    bool canSortArray(vector<int>& nums) {
        if (nums.size() == 1) return true;
        int c=1;
        for(int i=1;i<nums.size();i++){
            if(nums[i]>=nums[i-1])c++;
            if(c==nums.size())return true;
        }
        unordered_map<int, pair<priority_queue<int>, priority_queue<int>>> um;

        for (int i = 0; i < nums.size(); i++) {
            int count = __builtin_popcount(nums[i]);
            cout<<count<<" ";
            um[count].first.push(nums[i]);  
            um[count].second.push(i);       
        }

        
        for (auto& it : um) {
            auto& pq = it.second.first;
            auto& indices = it.second.second;
            int index=-1;
            while (!pq.empty()) {
                nums[indices.top()] = pq.top();
                if(index==-1)index=indices.top();
                else if(abs(index-indices.top())>1)return false;
                else index=indices.top();
                pq.pop();
                indices.pop();
            }
        }

        for (int i = 1; i < nums.size(); i++) {
            if (nums[i] < nums[i - 1]) return false;
        }

        return true;
    }
};

```

### Expected behavior

When You submit my code without including this  `[174, 175, 236, 188]` test case then It is Accepted

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/136481697/ad53d293-6277-416a-a40b-7471963e09dd)

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
