### ISSUE TITLE
Missing Test Case - 500. Keyboard Row

### ISSUE THREAD

**Issue by AdityaKumar-Git** [LeetCode-Feedback/LeetCode-Feedback#19742]
### LeetCode Username

aditya_c0des

### Problem number, title, and link

[500. Keyboard Row](https://leetcode.com/problems/keyboard-row/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Missing Test Case

### Language used for code

C++

### Code used for Submit/Run operation

```
class Solution {
public:
    vector<string> findWords(vector<string>& w) {
        vector<string> v;
        string s1="qwertyuiopQWERTYUIOP";
        string s2="asdfghjklASDFGHJKL";
        string s3="zxcvbnmZXCVBNM";
        unordered_map<char,int> m;
        for(auto i: s1){
            m[i]++;
        }
        for(auto i: s2){
            m[i]+=3;
        }
        for(auto i: s3){
            m[i]+=11;
        }
        
        for(auto i: w){
            int cnt=0;
            int n=i.size();
            for(auto j: i){
                cnt+=m[j];
            }
            if(cnt==n || cnt==n*3 || cnt==n*11){
                v.push_back(i);
            }
        }
        return v;
    }
};
```

### Expected behavior

Wrong Answer / Submission Failed

### Screenshots

![Screenshot (53)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/154753771/b47d512b-36a1-4f4c-a117-57c074d8a3cc)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
