### ISSUE TITLE
Missing Test Case - 602. Friend Requests II: Who Has the Most Friends

### ISSUE THREAD

**Issue by AgentIvan** [LeetCode-Feedback/LeetCode-Feedback#19740]
### LeetCode Username
[AgentIvan](https://leetcode.com/AgentIvan/)

### Category of the bug
- [ ] Problem description
- [x] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
the solution do not count that requester_id and accepter_id can be used as vice verse

### Language used for code
- MySQL
-  MS SQL Server
- Oracle
- PostgerSQL
- Pandas

### Code used for Submit/Run operation
```Python []
def most_friends(df: pd.DataFrame) -> pd.DataFrame:
  gr = pd.concat([df, df.rename(columns={'accepter_id':'requester_id', 'requester_id':'accepter_id'})]).groupby('requester_id').accepter_id.nunique()
  return gr[gr == gr.max()].reset_index(name='num').rename(columns={'requester_id':'id'})
```
```SQL []
-- T-SQL or use LIMIT 1
SELECT TOP 1 id, COUNT(u2) num
FROM (
  SELECT r.requester_id id, r.accepter_id u2
  FROM RequestAccepted r
  UNION
  SELECT r.accepter_id id, r.requester_id u2
  FROM RequestAccepted r
) t
GROUP BY id
ORDER BY num DESC
```
``` SQL []
-- All SQL dialects
WITH CTE AS (
  SELECT id, COUNT(u2) num
  FROM (
    SELECT r.requester_id id, r.accepter_id u2
    FROM RequestAccepted r
    UNION
    SELECT r.accepter_id id, r.requester_id u2
    FROM RequestAccepted r
  ) t
  GROUP BY id
)

SELECT * FROM CTE WHERE num = (SELECT MAX(num) FROM CTE)
```

### Expected behavior
we should count distinct pairs, so correct is using `UNION` instead of `UNION ALL`

### Screenshots
Example of testCase:
```
| requester_id | accepter_id | accept_date |
| ------------ | ----------- | ----------- |
| 1            | 2           | 2016/06/03  |
| 1            | 3           | 2016/06/08  |
| 4            | 3           | 2016/06/08  |
| 3            | 4           | 2016/06/09  |
| 3            | 2           | 2016/06/09  |
```

### Additional context
if user 3 is friend to user 4
then user 4 is friend to user 3
and this is one connection

**Comment by AgentIvan** [comment]
if user 3 is friend to user 4
then user 4 is friend to user 3
and this is one connection

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
