### ISSUE TITLE
Missing Test Case - 189. Rotate Array

### ISSUE THREAD

**Issue by Ayush04H** [LeetCode-Feedback/LeetCode-Feedback#19746]
### LeetCode Username

ayush004

### Problem number, title, and link

[189. Rotate Array](https://leetcode.com/problems/rotate-array/)

### Category of the bug
- [ ] Problem description :Given an integer array nums, rotate the array to the right by k steps, where k is non-negative.
- [ ] Solved examples:Input: nums = [1,2,3,4,5,6,7], k = 3
Output: [5,6,7,1,2,3,4]
- [ ] Problem constraints:
1 <= nums.length <= 105
-231 <= nums[i] <= 231 - 1
0 <= k <= 105
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Incorrect Solution 

### Code used for Submit/Run operation

```
class Solution {
public:
    void reverse(vector<int>& arr,int low,int high){
        while(low < high)
	        {
		    swap(arr[high], arr[low]);

		    low++;
		    high--;
	    }
    }
    void rotate(vector<int>& arr, int d) {
        int n=arr.size();
        reverse(arr, 0, d - 1);

	    reverse(arr, d, n - 1);

	    reverse(arr, 0, n - 1);
    }
};
```

### Screenshots

![tc1](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/126005876/338ab467-09e5-468f-a8dc-5e0dea44181c)

**Comment by Ayush04H** [comment]
Major Bug

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
