### ISSUE TITLE
2846. 边权重均等查询 官方Go语言题解panic

### ISSUE THREAD

**Issue by aac3476** [LeetCode-Feedback/LeetCode-Feedback#19753]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

### LeetCode 用户名

ywxisky

### Bug 类型
- [ ] 问题描述
- [ ] 示例
- [ ] 问题限制
- [ ] 问题提示
- [ ] 不正确或缺少“相关标签”
- [ ] 不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*
- [ ] 缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*
- [x] 力扣官方题解
- [ ] 编程语言支持

### 你使用的语言

Go

### 你提交或者运行的代码

```go
const (
    W = 26
)

func find(uf []int, i int) int {
    if uf[i] == i {
        return i
    }
    uf[i] = find(uf, uf[i])
    return uf[i]
}

func minOperationsQueries(n int, edges [][]int, queries [][]int) []int {
    m := len(queries)
    neighbors := make([]map[int]int, n)
    for i := 0; i < n; i++ {
        neighbors[i] = map[int]int{}
    }
    for _, edge := range edges {
        neighbors[edge[0]][edge[1]] = edge[2]
        neighbors[edge[1]][edge[0]] = edge[2]
    }
    queryArr := make([][][2]int, n)
    for i := 0; i < m; i++ {
        queryArr[queries[i][0]] = append(queryArr[queries[i][0]], [2]int{queries[i][1], i})
        queryArr[queries[i][1]] = append(queryArr[queries[i][1]], [2]int{queries[i][0], i})
    }

    count := make([][]int, n)
    for i := 0; i < n; i++ {
        count[i] = make([]int, W + 1)
    }
    visited, uf, lca := make([]int, n), make([]int, n), make([]int, n)
    var tarjan func(int, int)
    tarjan = func(node, parent int) {
        if parent != -1 {
            copy(count[node], count[parent])
            count[node][neighbors[node][parent]]++
        }
        uf[node] = node
        for child, _ := range neighbors[node] {
            if child == parent {
                continue
            }
            tarjan(child, node)
            uf[child] = node
        }
        for _, query := range queryArr[node] {
            node1, index := query[0], query[1]
            if node != node1 && visited[node1] == 0 {
                continue
            }
            lca[index] = find(uf, node1)
        }
        visited[node] = 1
    }
    tarjan(0, -1)
    res := make([]int, m)
    for i := 0; i < m; i++ {
        totalCount, maxCount := 0, 0
        for j := 1; j <= W; j++ {
            t := count[queries[i][0]][j] + count[queries[i][1]][j] - 2 * count[lca[i]][j]
            maxCount, totalCount = max(maxCount, t), totalCount + t
        }
        res[i] = totalCount - maxCount
    }
    return res
}

作者：力扣官方题解
链接：https://leetcode.cn/problems/minimum-edge-weight-equilibrium-queries-in-a-tree/solutions/2614609/bian-quan-zhong-jun-deng-cha-xun-by-leet-yunc/
来源：力扣（LeetCode）
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。
```

### 屏幕截图

<img width="1697" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/43756248/2d9e7324-b081-4d13-ae84-ee621e5eba2a">
<img width="1694" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/43756248/38f1e1c0-4209-41c6-8150-8629406a85a7">
<img width="1689" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/43756248/5d2c8d9b-0f88-414e-9282-23f1ed4c6132">

### 额外的上下文

panic: runtime error: index out of range [2] with length 2
main.minOperationsQueries.func1(0x1, 0x0)
solution.go, line 53
main.minOperationsQueries.func1(0x0, 0xffffffffffffffff)
solution.go, line 45
main.minOperationsQueries(0x2, {0xc000010498, 0x1, 0x4b3140?}, {0xc000046360, 0x3, 0x4b1d00?})
solution.go, line 57
main.__helper__(...)
solution.go, line 73
main.main()
solution.go, line 123

**Comment by aac3476** [comment]
line 33 should be:
```go
    visited, uf, lca := make([]int, n), make([]int, n), make([]int, m)
```

**Comment by amcones-lc** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by aac3476** [comment]
> 你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

leetcode.cn/u/ywxisky/

**Comment by amcones-lc** [comment]
你好，当前奖励已发放，请查收。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
