### ISSUE TITLE
Missing Test Case - 71. Simplify Path

### ISSUE THREAD

**Issue by hfeky** [LeetCode-Feedback/LeetCode-Feedback#19750]
### LeetCode Username

[huss_elfeky](https://leetcode.com/huss_elfeky)

### Problem number, title, and link

[71. Simplify Path](https://leetcode.com/problems/simplify-path/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Test Case: "/hello.../../"

Expected Output: "/"

### Language used for code

Java

### Code used for Submit/Run operation

```java
class Solution {
    public String simplifyPath(String path) {
        StringBuilder sb = new StringBuilder();

        int moveOneDirectoryUp = 0;

        for (int i = path.length() - 1; i >= 0; i--) {
            if (path.charAt(i) == '.' && (sb.isEmpty() || sb.charAt(sb.length() - 1) == '/')) {
                if (i > 0 && path.charAt(i - 1) == '.') {
                    if (path.charAt(i - 2) == '/') {
                        // Handle ..
                        i -= 2;
                        moveOneDirectoryUp++;
                    } else {
                        while (path.charAt(i) == '.') {
                            sb.append('.');
                            i--;
                        }
                        i++;
                    }
                } else if (i > 0 && path.charAt(i - 1) != '/') {
                    sb.append('.');
                } else {
                    continue;
                }
            } else if (path.charAt(i) == '/') {
                if (sb.isEmpty()) {
                    continue;
                }
                if (sb.charAt(sb.length() - 1) == '/') {
                    continue;
                }
                sb.append('/');
            } else {
                if (moveOneDirectoryUp > 0) {
                    while (i >= 0 && path.charAt(i) != '/') {
                        i--;
                    }
                    i++;
                    moveOneDirectoryUp--;
                } else {
                    sb.append(path.charAt(i));
                }
            }
        }

        if (sb.isEmpty() || sb.charAt(sb.length() - 1) != '/') {
            sb.append('/');
        }

        return sb.reverse().toString();
    }
}
```

### Expected behavior

The submission passed while it should have failed with the above code, as it produces "/...".

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
