### ISSUE TITLE
Home Page | Leetcode Daily Challenge Button Not Working

### ISSUE THREAD

**Issue by Vikasss7663** [LeetCode-Feedback/LeetCode-Feedback#19765]
### LeetCode Username
cs_iitian

### Category of the bug
- [x] Technical Issue
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

On Home Page, where we show the leetcode streak. When I click on that it's not redirecting me to the today's problem detail page.

### Expected behavior

It should redirect me to the current day's problem detail page.

### Screenshots
When I click on `106` it should redirect me to today's problem page.

<img width="1262" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/98081274/130f93fa-305f-4705-a6b2-9d4f49625404">

**Comment by LC-Pam** [comment]
Hello,

Thank you for providing your feedback.

Please note that our GitHub repository primarily addresses content and solution-related issues. To ensure a prompt response and effective resolution for feature, function, course access, or product-related feedback, we kindly encourage you to submit such inquiries through our Zendesk Support Channel:

[LeetCode Support](https://leetcode.com/support)

Our dedicated support agents typically respond within 24 hours and promptly report submitted issues to the appropriate departments for investigation.

We greatly appreciate your ongoing support and value your contributions to enhancing the LeetCode experience.

Best regards,
LeetCode Support Team
