### ISSUE TITLE
222. 完全二叉树的节点个数需要增加时间复杂度要求

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#1976]
**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
第 222 题完全可以用常规方法做，即深度优先搜索或广度优先搜索，时间复杂度是 O(n)（n 是节点数量），但是这样做就没有意义了，因为任何二叉树都可以用常规方法做。既然这道题给定了完全二叉树，就应该利用完全二叉树的特点做，使用复杂度更低的算法做。
因此建议这道题增加时间复杂度要求，不需要具体说明达到什么样的时间复杂度，只需要增加一点要求：时间复杂度**必须**优于 O(n)，其中 n 是树的节点数。中文描述和英语描述需要同步更新。

**你使用的语言**
Java

**你提交或者运行的代码**

**期望行为**
增加时间复杂度要求作为常规要求，中文描述和英语描述需要同步更新。

**屏幕截图**

**额外的上下文**

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前题目中英文题面已调整更新，力扣会定期更新，保障稳定和体验优化。
