### ISSUE TITLE
Editorial Article Typo - 227. Basic Calculator II

### ISSUE THREAD

**Issue by EnergyBoyTW** [LeetCode-Feedback/LeetCode-Feedback#19778]
### LeetCode Username

EnergyBoy

### Problem number, title, and link

[227. Basic Calculator II https://leetcode.com/problems/basic-calculator-ii/description/]

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug

The Example number mentioned in article didn't match in figure.
The sentence should be "In the above example 3 and 4, 4*3 is always evaluated first irrespective of the next operation."

### Screenshots

<img width="631" alt="截圖 2024-01-27 上午12 44 05" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/55799404/cafee94c-317e-4fe2-9404-74f3c7820d27">

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
