### ISSUE TITLE
Missing Test Case - 2861. Maximum Number of Alloys

### ISSUE THREAD

**Issue by EndlessCheng** [LeetCode-Feedback/LeetCode-Feedback#19772]
### Your LeetCode username
endlesscheng

### Problem number, title, and link
[2861. Maximum Number of Alloys](https://leetcode.com/problems/maximum-number-of-alloys/)

### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

### Description of the bug
The code below passed all test cases, but WA on this test case:

```
3
1
15
[[1,1,1]]
[1,99,99]
[1,1,1]
```

### Code you used for Submit/Run operation
```go
func maxNumberOfAlloys(n, _, budget int, composition [][]int, stock, cost []int) (ans int) {
	mx := slices.Min(stock) + budget/n
	for _, comp := range composition {
		ans += sort.Search(mx-ans, func(num int) bool {
			num += ans + 1
			money := 0
			for i, s := range stock {
				if s < comp[i]*num {
					money += (comp[i]*num - s) * cost[i]
					if money > budget {
						return true
					}
				}
			}
			return false
		})
	}
	return
}
```

### Language used for code
Go

### Expected behavior

WA on this test case:
```
3
1
15
[[1,1,1]]
[1,99,99]
[1,1,1]
```

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
