### ISSUE TITLE
2861. 最大合金数[题目翻译模糊]

### ISSUE THREAD

**Issue by kogsmsb** [LeetCode-Feedback/LeetCode-Feedback#19770]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

### Bug 类型
- [x] 问题描述
- [ ] 示例
- [ ] 问题限制
- [ ] 问题提示
- [ ] 不正确或缺少“相关标签”
- [ ] 不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*
- [ ] 缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*
- [ ] 力扣官方题解
- [ ] 编程语言支持

### 描述
you have access to k machines that can be used to create alloys 被翻译为“你可以使用k台机器来制造金属”，表述不清存在歧义，建议翻译为“你有k台机器可以选择来制造合金”或者直接综合上下文翻译成“你可以从k台机器中选择一台来制造合金”

### 你提交或者运行的代码

```
// 将您的代码粘贴到此处
```

### 期望行为

修改翻译使其更加合理易懂

**Comment by amcones-lc** [comment]
您好，在与相关团队核实后：***不处理***（题目已有加粗提示所有合金需要由同一台机器制造）。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
