### ISSUE TITLE
Missing Test Case - 629. K Inverse Pairs Array

### ISSUE THREAD

**Issue by willdufault** [LeetCode-Feedback/LeetCode-Feedback#19793]
There is a typo in the problem description.

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/99445180/7093efec-dba4-4b42-a1f5-3343d404d264)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Hi there,

Your feedback has been instrumental in enhancing the problem. 

To ensure you receive your well-deserved 100 LeetCoins reward, could you kindly provide us with your LeetCode username? This will allow us to credit your account accurately.

Your participation and contributions are valued, and we want to make sure you enjoy the rewards you've earned.

Thank you for being part of the LeetCode community!

Best regards,
LeetCode Team
