### ISSUE TITLE
Missing Test Case - 629. K Inverse Pairs Array

### ISSUE THREAD

**Issue by rohan-algorithm** [LeetCode-Feedback/LeetCode-Feedback#19790]
### Problem number, title, and link
629. K Inverse Pairs Array  https://leetcode.com/problems/k-inverse-pairs-array/

### Category of the bug
- [✅] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug
It's getting Accepted on test case [n=1000,k=1000]. But actually it should give TLE. As it's giving when i'm running on it on this test case.

### Code used for Submit/Run operation

```
class Solution {
public:
    int mod = 1e9+7;
    int DP[1001][1001];
    int helper(int n,int k){
        if(n==0) return 0;
        if(k==0) return 1;
        if(DP[n][k]!=-1) return DP[n][k];
        int ans=0;
        for(int i=0;i<=min(n-1,k);i++){
            ans= ((ans%mod)+ (helper(n-1,k-i)%mod))%mod;
        }
        return DP[n][k]=ans;
    }
    int kInversePairs(int n, int k) {
        memset(DP,-1,sizeof(DP));
        return helper(n,k);
    }
};
```

### Expected behavior
Should give TLE on test case n=1000,k=1000

### Screenshots
<img width="1440" alt="Screenshot 2024-01-27 at 9 55 06 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/43471954/35526531-3fc2-4e3a-bc82-a6ea9a9d9fc2">
<img width="1440" alt="Screenshot 2024-01-27 at 9 55 28 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/43471954/c9b516ee-26c2-4f18-a954-6d879c8e4f63">

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
