### ISSUE TITLE
Problem Constraints Typo - 1074. Number of Submatrices That Sum to Target

### ISSUE THREAD

**Issue by chuanqixu** [LeetCode-Feedback/LeetCode-Feedback#19795]
### LeetCode Username

LegenDX

### Problem number, title, and link

1074. Number of Submatrices That Sum to Target https://leetcode.com/problems/number-of-submatrices-that-sum-to-target/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [X] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

In the problem constraints section, `matrix` is a two-dimensional array, so the third constraint is missing the second index.

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/33219261/80dcc7f3-6d62-49ea-bca0-ada26eb6f877)

Correct constraint should be something like:

`-1000 <= matrix[i][j] <= 1000`

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team
