### ISSUE TITLE
Problem Description Not Clear - 1074. Number of Submatrices That Sum to Target

### ISSUE THREAD

**Issue by Shubx10** [LeetCode-Feedback/LeetCode-Feedback#19800]
### LeetCode Username
_shubham10

### Problem number, title, and link

1074. Number of Submatrices That Sum to Target https://leetcode.com/problems/number-of-submatrices-that-sum-to-target/description/

### Category of the bug
- [x] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The size of `matrix` is not mentioned in the description. It should be made clear by specifying whether it is `n x n` or `m x n` sized array just like other 2D array question on leetcode.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/97556205/c6dc7540-d377-4632-b4c2-b21859d63b32)

### Suggestion
The first line of the problem description can be given as following-
> Given a `m x n` matrix `matrix` and a `target`, return the number of non-empty submatrices that sum to target.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
