### ISSUE TITLE
Missing Test Case - 66. Plus One

### ISSUE THREAD

**Issue by gitvipin** [LeetCode-Feedback/LeetCode-Feedback#1980]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Testcase

#### Description of the bug

An invalid test case is being tested. 
Question says clearly that "**You may assume the integer does not contain any leading zero, except the number 0 itself.**" which means [0,0] is invalid input. However, during running of tests , it is being run as an one of the tests.

Problem - https://leetcode.com/explore/featured/card/top-interview-questions-easy/92/array/559/ 
#### Code you used for Submit/Run operation

```
class Solution:
    def plusOne(self, digits: List[int]) -> List[int]:
        total = 0
        for digit in digits:
            total *= 10
            total += digit
        total += 1
        return [ int(x) for x in '%s' % total]
```

#### Expected behavior

Either this test case with input ([0, 0]) should not be run or [1] be accepted as solution or change the language of question.

**Comment by lc-kay** [comment]
@gitvipin This is a valid test case. Please check out this discuss post! Thank you for your time.

**Comment by gitvipin** [comment]
@lc-kay  : Can you point out to discuss section which explains this. 

Are the comment "You may assume the integer does not contain any leading zero, except the number 0 itself." and  [0,0] as an input contradictory ?

**Comment by lc-kay** [comment]
@gitvipin https://leetcode.com/problems/plus-one/discuss/933685/Why-is-00-in-the-test-set Here you go!

**Comment by gitvipin** [comment]
@lc-kay : Thanks !
