### ISSUE TITLE
Missing Test Case - 617. Merge Two Binary Trees

### ISSUE THREAD

**Issue by Manish23121** [LeetCode-Feedback/LeetCode-Feedback#1981]
#### Your LeetCode username
manishsah_21

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
if(t1==NULL){
            
           return t2;
            
        }
        
        if(t2==NULL){
            
            return t1;
            
        }
        
        t1->val=t1->val+t2->val;
        
        t1->left=mergeTrees(t1->left,t2->left);
        
        t1->right=mergeTrees(t1->right,t2->right);
        
        return t1;
    }
};
```

**Comment by lc-kay** [comment]
@Manish23121 Please provide more information to your report so we can better investigate the issue.

**Comment by lc-kay** [comment]
Hi @Manish23121 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
