### ISSUE TITLE
384. Shuffle an Array ; TestCases are missing. Wrong code has been submitted and accepted

### ISSUE THREAD

**Issue by rohithKuthyar** [LeetCode-Feedback/LeetCode-Feedback#19818]
### LeetCode Username
rohithbhatkuthyar

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

I think the test cases are missing and the question is incorrect. The leetcode accepted my submission, which is a wrong solution. 
We need to ensure that we properly check the probability. I am missing it and was able to solve in O(1) time, and yet LC accepted my submission.

### Language used for code
Python

### Code used for Submit/Run operation

```
class Solution:

    def __init__(self, nums: List[int]):
        self.array = nums
        self.original = list(nums)
        

    def reset(self) -> List[int]:
        return self.original

    def shuffle(self) -> List[int]:
        
            swap_idx = random.randrange(0,len(self.array))
            i = random.randrange(0,len(self.array))
            self.array[i], self.array[swap_idx] = self.array[swap_idx] , self.array[i]
            return self.array
```

### Expected behavior

I think this solution is incorrect. However, the leetcode accepted my submission. Leetcode should fail my code.
We need to ensure that we properly check the probability. In the above solution, I am missing it and was able to solve in O(1) time.

### Additional context

```
### In Editorial, it is O(n) for Shuffle function
def shuffle(self):
        for i in range(len(self.array)):
            swap_idx = random.randrange(i, len(self.array))
            self.array[i], self.array[swap_idx] = self.array[swap_idx], self.array[i]
        return self.array
```

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
