### ISSUE TITLE
1060. 有序数组中的缺失元素增加进阶要求

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#1982]
**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
第 1060 题可以直接遍历数组得到答案，时间复杂度是 O(n)。这道题使用二分查找的时间复杂度可以降到 O(log n)，但是二分查找的要求更高。
因此建议增加进阶要求，使用时间复杂度 O(log n) 的算法解决此问题。中文描述和英语描述需要同步更新。

**你使用的语言**
Java

**你提交或者运行的代码**

**期望行为**
增加进阶要求，中文描述和英语描述需要同步更新。

**屏幕截图**

**额外的上下文**

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，在与美国区负责同事沟通了解后，「1060. 有序数组中的缺失元素」一题的优化已在我们的计划队列之内，但这可能需要一段时间进行处理，还请耐心等待，目前我们会暂时关闭该 issue，如有更多反馈和建议请与我们联系。
