### ISSUE TITLE
“Leetcode 365. 水壶问题”严重bug，今早直接无法运行，默认示例直接报错超时，空函数也是如此，请修复bug

### ISSUE THREAD

**Issue by Tiikee** [LeetCode-Feedback/LeetCode-Feedback#19828]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

### LeetCode 用户名

橙橙橙

### Bug 类型
- [ ] 问题描述
“Leetcode 365. 水壶问题”严重bug，今早直接无法运行，默认示例直接报错超时，空函数也是如此，请修复bug

- [ ] 示例
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/95959942/e8286f66-6388-402f-aafc-a45f779f9669)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/95959942/13d5bb77-be5d-4b89-952a-9a2efcc239c5)

- [ ] 问题限制
无。正常默认示例运行就会出问题。
- [ ] 问题提示
见图。
- [ ] 不正确或缺少“相关标签”
- [ ] 不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*
3
5
4
2
6
5
1
2
3
- [ ] 缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*
- [ ] 力扣官方题解
- [ ] 编程语言支持
- [ ] C++

### 描述

“Leetcode 365. 水壶问题”严重bug，今早直接无法运行，默认示例直接报错超时，空函数也是如此，请修复bug
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/95959942/e8286f66-6388-402f-aafc-a45f779f9669)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/95959942/13d5bb77-be5d-4b89-952a-9a2efcc239c5)

### 你提交或者运行的代码

```class Solution {
public:
    bool canMeasureWater(int jug1Capacity, int jug2Capacity, int targetCapacity) {
        return false;
    }
};
```

### 期望行为

正常运行

### 屏幕截图

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/95959942/e8286f66-6388-402f-aafc-a45f779f9669)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/95959942/13d5bb77-be5d-4b89-952a-9a2efcc239c5)

### 额外的上下文

无

**Comment by amcones-lc** [comment]
您好，在与相关团队核实后：***不处理***（题面有更新，请刷新代码模版）。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
