### ISSUE TITLE
Missing Test Case - 20. Valid Parentheses

### ISSUE THREAD

**Issue by vimal-s** [LeetCode-Feedback/LeetCode-Feedback#19837]
### LeetCode Username

Vimal5

### Problem number, title, and link

20. Valid Parentheses https://leetcode.com/problems/valid-parentheses/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Language used for code

Java

### Code used for Submit/Run operation

```
// testing previously submitted code, should give error, but works

class Solution {
    public boolean isValid(String s) {
        Deque<Character> stack = new ArrayDeque<>();
        for (char c : s.toCharArray()) {
            if (isOpenBracket(c) || stack.size() == 0) {
                System.out.println("Add: " + c);
                stack.addFirst(c);
            } else {
                if (closeBracket(stack.removeFirst()) != c) {
                    return false;
                }
            }
        }
        return stack.size() == 0;
    }

    private boolean isOpenBracket(char c) {
        return c == '(' || c == '{' || c == '[';
    }

    private char closeBracket(char c) {
        if (c == '(') return ')';
        if (c == '{') return '}';
        return ']';
    }
}
```

### Expected behavior

My solution gets accepted even though it returns "true" for the input "]]" instead of "false".

### Screenshots

![missing_testcase](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/36556890/79e82e25-9af5-4cb9-97f5-ed91d8e5de87)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
