### ISSUE TITLE
旧手机号不用了，现在无法登录

### ISSUE THREAD

**Issue by fenghaotong** [LeetCode-Feedback/LeetCode-Feedback#19845]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

### LeetCode 用户名
htfenght

### 描述
旧手机不用了，现在手机号无法登录

### 期望行为
换绑手机号

您的常用邮箱： 1054708869@qq.com
需要解绑的手机号：15600786890
绑定手机号对应的力扣账号：htfenght
常用登录地址：（省市）上海市
常用登录设备系统：mac、win
常用登录浏览器：edge

**Comment by kindaQ** [comment]
同样问题  
提示用验证码登录  手机号早就不用了


您的常用邮箱：pq4362050@qq.com
需要解绑的手机号：17813267971
绑定手机号对应的力扣账号：wpoier
常用登录地址：（省市）北京市
常用登录设备系统：win
常用登录浏览器：edge

**Comment by kindaQ** [comment]
可以尝试用app登录  联系客服

**Comment by fenghaotong** [comment]
> 可以尝试用app登录 联系客服

换绑了，感谢

**Comment by JamesTensor** [comment]
您好，我也需要换绑
您的常用邮箱：[wangjiajie0326@163.com](mailto:wangjiajie0326@163.com)
需要重置手机号的力扣账号：wjj
旧手机号：18367561845
新手机号：13269190022
常用登录地址：中国浙江/上海
常用登录设备系统：mac os
常用登录浏览器：chrome
解题数：215
绑定的QQ号：1170663408
