### ISSUE TITLE
Missing Test Case - 883. Projection Area of 3D Shapes

### ISSUE THREAD

**Issue by mecdeality** [LeetCode-Feedback/LeetCode-Feedback#1984]
#### Your LeetCode username 
mecdeal

#### Category of the bug
- [ ] Question
- [x] Solution ++
- [ ] Language

#### Description of the bug
Missing Test Case

#### Code you used for Submit/Run operation

```
// 883. Projection Area of 3D Shapes
class Solution {
public:
    int projectionArea(vector<vector<int>>& grid) {
        int ans = 0;
        for(auto vec : grid){
            for(auto x : vec) { if(x) ans++; }
            ans += *max_element(vec.begin(), vec.end()); 
        }
        for(int i = 0; i < 50; i++){
            int mx = 0;
            for(int j = 0; j < grid.size(); j++){
                if(grid[j].size() > i) mx=max(mx, grid[j][i]);
            }
            ans += mx;
        }
        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior

This code should be rejected for a Test Case ```[[2], [1,2]]```, but it has been accepted.

#### Screenshots

<a href="https://ibb.co/xgf5gDV"><img src="https://i.ibb.co/t2xC24y/Capture.jpg" alt="Capture" border="0" /></a>

**Comment by lc-kay** [comment]
Hi @mecdeality 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @mecdeality 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
