### ISSUE TITLE
Missing Test Case - 1141. User Activity for the Past 30 Days I

### ISSUE THREAD

**Issue by Zeng95** [LeetCode-Feedback/LeetCode-Feedback#19844]
### LeetCode Username
leodaima

### Problem number, title, and link
[1141. User Activity for the Past 30 Days I](https://leetcode.com/problems/user-activity-for-the-past-30-days-i/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
In the description of the question, it says: 

> Write a solution to find the daily active user count for a period of 30 days ending 2019-07-27 inclusively. A user was active on someday if they made at least one activity on that day.

However, all of the test cases don't include testing `2019-07-27`. If you run my code, it passes all the test cases because none check `2019-07-27` and I believe it's a bug.

### Language used for code
SQL (PostgreSQL)

### Code used for Submit/Run operation
```sql
SELECT activity_date AS day, COUNT(DISTINCT user_id) AS active_users
FROM activity
WHERE activity_date < '2019-07-27' AND '2019-07-27' - activity_date < 30
GROUP BY 1;
```

### Expected behavior
At least one of the test cases should have `2019-07-27` included to check.

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/12603244/524c64b2-93f6-4e1f-98c3-5767424a5019)

### Additional context
Add a simple test case like this to avoid the missing error catch:
```sql
| user_id | session_id | activity_date | activity_type |
| ------- | ---------- | ------------- | ------------- |
| 1       | 1          | 2019-07-20    | open_session  |
| 1       | 1          | 2019-07-20    | scroll_down   |
| 1       | 1          | 2019-07-20    | end_session   |
| 2       | 4          | 2019-07-20    | open_session  |
| 2       | 4          | 2019-07-21    | send_message  |
| 2       | 4          | 2019-07-21    | end_session   |
| 3       | 2          | 2019-07-21    | open_session  |
| 3       | 2          | 2019-07-21    | send_message  |
| 3       | 2          | 2019-07-21    | end_session   |
| 4       | 3          | 2019-07-27    | open_session  |
| 4       | 3          | 2019-07-27    | end_session   |
```

**Comment by Zeng95** [comment]
@Miloas

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
