### ISSUE TITLE
Solved Test Case - 595. Big Countries

### ISSUE THREAD

**Issue by laxmi13579** [LeetCode-Feedback/LeetCode-Feedback#19842]
### Category of the bug
- [ ] Problem description
- [x] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

**Comment by laxmi13579** [comment]
```
SELECT name, population, area
FROM World
WHERE area >= 3000000 OR population >= 25000000;
```

<img width="689" alt="Screenshot 2024-01-29 at 2 01 47 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/33938782/77647f29-6ef3-4bf8-a485-e787653b7bcb">

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.
Details regarding the missing test case.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team
