### ISSUE TITLE
Fix Space Complexity Editorial -  934. Shortest Bridge

### ISSUE THREAD

**Issue by imkartikahuja** [LeetCode-Feedback/LeetCode-Feedback#19854]
### LeetCode Username
imkartikahuja

### Problem number, title, and link  
934. Shortest Bridge https://leetcode.com/problems/shortest-bridge/ 

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug
There is a typo in the Space Complexity section of Approach 1: Depth-First-Search + Breadth-First-Search. 
Written as "The maximum number of cells in the first island is **O^2,** thus the space used by the recursive stack during DFS is O(n^2)" 

Instead of O^2. It should be n^2.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/14763608/561b03fc-f59a-49fd-9bdf-5fb1003d17db)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team
