### ISSUE TITLE
Write a function createHelloWorld. It should return a new function Missing Test Case - 2667. Create Hello World Function

### ISSUE THREAD

**Issue by waheedanwar00** [LeetCode-Feedback/LeetCode-Feedback#19861]
// Write a function createHelloWorld. It should return a new function that always returns "Hello World"

function createHelloWorld(){
    return function newFunction(){
        return "Hello World"
    }
}
const result = createHelloWorld();
console.log(result())

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.
Details regarding the missing test case.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team
