### ISSUE TITLE
Type in Editorial for 629. K Inverse Pairs Array

### ISSUE THREAD

**Issue by StrawHatDrag0n** [LeetCode-Feedback/LeetCode-Feedback#19864]
### LeetCode Username
strawhatdragon

### Problem number, title, and link

[K Inverse Pairs Array](https://leetcode.com/problems/k-inverse-pairs-array/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/19656900/71b29807-510e-4bd4-b4ac-1dc7b488f83d)

The editorial in approach 5 says that `dp[i][j]=dp[i−1][j]−dp[i−1][j−i]+dp[i−1][j], if j−i≥0j-i ≥ 0j−i≥0. Otherwise, we can use: dp[i][j]=dp[i−1][j]+dp[i−1][j]dp[i][j] = dp[i-1][j] + dp[i-1][j]dp[i][j]=dp[i−1][j]+dp[i−1][j].`

But it should be
```
dp[i][j]=dp[i][j-1]−dp[i−1][j−i]+dp[i−1][j], if j−i≥0j-i ≥ 0j−i≥0. 
Otherwise, we can use: dp[i][j]=dp[i][j-1]+dp[i−1][j]dp[i][j] = dp[i-1][j] + dp[i-1][j]dp[i][j]=dp[i][j]+dp[i−1][j].
```

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
