### ISSUE TITLE
Wrong Test Case - 420. Strong Password Checker

### ISSUE THREAD

**Issue by harshavardhands** [LeetCode-Feedback/LeetCode-Feedback#1986]
Input   "A1234567890aaabbbbccccc"
Output  5
Expected  4

possible outputs can be 
"A1234567890bb1bcc1cc" = 3 a's removed, 1 b change, 1 c change - so 5
"A1234567890aa1bb1bcc" = 1 a's change, 1 b change, 3 c removed - so 5
"A1234567890aa1bbcc1c" = 1 a's change, 2 b removed, 1 c change, 1 c removed - so 5
"A1234567890aabb1bcc1" = 1 a's removed, 1 b changed, 1 c change, 2 c removed - so 5
"A1234567890aabb1bcc1" = 1 a's removed, 1 b changed, 1 c change, 2 c removed - so 5

Please valid test case, output is 5. I am not getting how it's 4?

**Comment by lc-kay** [comment]
@harshavardhands The expected output is correct. Please refer to the discuss section to raise your question or find similar postings. Thank you for your time.
