### ISSUE TITLE
Missing Test Case - 150. Evaluate Reverse Polish Notation

### ISSUE THREAD

**Issue by YSK3002** [LeetCode-Feedback/LeetCode-Feedback#19871]
### LeetCode Username
yuvraj5785singh

### Problem number, title, and link
150. Evaluate Reverse Polish Notation

### Category of the bug
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### Description of the bug
Your test generate wrong output while same test case and same is run on another platform it gives correct output the screenshot is attached with it.

### Language used for code
Python

### Code used for Submit/Run operation

```
class Solution(object):
    def evalRPN(self, tokens):
        stack = []
        for token in tokens:
            if token in "+-*/":
                b = stack.pop() 
                a = stack.pop()
                if token == '+': stack.append(a + b)
                elif token == '-': stack.append(a - b)
                elif token == '*': stack.append(a * b)
                elif token == '/': stack.append(int(a / b))       
            else:
                stack.append(int(token))
        return stack[0] 
        
```

### Expected behavior
The 3rd test case has to be give correct evaluation of tokens and gives 22 as ans but it will show 12
![Screenshot 2024-01-30 184322](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/135502342/71b95398-9a10-4463-9ef9-ae2e262885cb)

### Screenshots
![Screenshot 2024-01-30 183148](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/135502342/60d5e99d-e0c7-4618-8178-dc795d8778dd)

### Additional context
Screenshot of your platform and another platform is attached please check it and verify it

**Comment by LC-Pam** [comment]
Thank you for getting back to us! Regrettably, troubleshooting the variance between your local Integrated Development Environment (IDE) and the LeetCode environment poses a challenge for us.

In such cases, we recommend raising this issue as a discussion post in the problem's discussion section. This allows you to tap into the collective knowledge and experiences of our user community. Many users may have encountered similar challenges and could offer insights or solutions that can be valuable in resolving the discrepancy.

At LeetCode, we foster a collaborative learning environment, and we believe in the power of users to help each other to enhance their learning experience. Debugging and learning from the process are integral parts of the coding journey, and the community's diverse perspectives can be immensely beneficial.

We appreciate your understanding, and if you have any more questions or need further assistance, please feel free to let us know. Your time and support are highly valued.

Best regards,
The LeetCode Team
