### ISSUE TITLE
1723. Find Minimum Time to Finish All Jobs: testcases differ among different submission

### ISSUE THREAD

**Issue by Helicopt** [LeetCode-Feedback/LeetCode-Feedback#1987]
#### Your LeetCode username 

fwtt20150412

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

I noticed that the number of test cases differs in two submissions submitted within 5 minutes, leading to an AC for the first one and WA for the second one. The code of the two submissions is same.
![image](https://user-images.githubusercontent.com/8593583/104410867-53521400-55bd-11eb-9e00-340a68f28516.png)
![image](https://user-images.githubusercontent.com/8593583/104410890-5fd66c80-55bd-11eb-9943-5e3bc29a87e4.png)

#### Code you used for Submit/Run operation

```python
class Solution:
    def minimumTimeRequired(self, jobs, k):
        jobs = sorted(jobs, reverse=True)
        backup = jobs
        a = jobs[:k]
        jobs = jobs[k:]
        ans = a[0] + sum(jobs)

        def dfs(dep):
            nonlocal ans
            if dep == len(jobs):
                ans = min(ans, max(a))
                return
            for i in range(k):
                a[i] += jobs[dep]
                dfs(dep + 1)
                a[i] -= jobs[dep]

        dfs(0)
        a = [0] * k
        jobs = sorted(backup, reverse=True)

        def dfs2(dep, mx):
            nonlocal ans
            if dep == len(jobs):
                ans = min(ans, mx)
                return
            rec = {}
            for i in range(k):
                if a[i] + jobs[dep] >= ans or i - 1 >= 0 and a[i] + jobs[
                        dep] > a[i - 1] or a[i] + jobs[dep] in rec:
                    continue
                a[i] += jobs[dep]
                rec[a[i]] = True
                dfs2(dep + 1, max(mx, a[i]))
                a[i] -= jobs[dep]

        dfs2(0, 0)
        return ans

```

#### Language used for code

python

#### Expected behavior

If there is not any new testcase added, the testcases for two submissions should be the same.

#### Screenshots

See pics in description of bug.

**Comment by lc-kay** [comment]
@Helicopt Our team is constantly adding missing test cases to our problems, and the new test cases for this problem were probably added when we were updating our test cases. Which resulted in the difference that you reported. Thank you for your time.
