### ISSUE TITLE
Missing Test Case - 1168. Optimize Water Distribution in a Village

### ISSUE THREAD

**Issue by baonguyen0111** [LeetCode-Feedback/LeetCode-Feedback#1989]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Just a little thing, the question said "For each house i, we can either build a well inside it directly with cost wells[i]", but the house aren't indexed from 0 so i thought that's a little confusing? Anyways, just disregard this if it doesn't make sense. 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
Hi @baonguyen0111 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @baonguyen0111 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
