### ISSUE TITLE
1114. 按序打印

### ISSUE THREAD

**Issue by daisenrong** [LeetCode-Feedback/LeetCode-Feedback#199]
** Bug 类型**
- [x] 1114. 按序打印
- [x] 题解
- [x] java

**描述**
本地运行可以，但是提交后一直超时

**你使用的语言**
java

**你提交或者运行的代码**
```java
class Foo {

    public static AtomicInteger flag = new AtomicInteger(1);

    public Foo() {

    }

    public void first(Runnable printFirst) throws InterruptedException {
        // printFirst.run() outputs "first". Do not change or remove this line.
        printFirst.run();
        flag.incrementAndGet();
    }

    public void second(Runnable printSecond) throws InterruptedException {
        while (flag.get() != 2) {
            
        }
        // printSecond.run() outputs "second". Do not change or remove this line.
        printSecond.run();
        flag.incrementAndGet();
    }

    public void third(Runnable printThird) throws InterruptedException {
        while (flag.get() != 3) {
            
        }
        // printThird.run() outputs "third". Do not change or remove this line.
        printThird.run();
    }
}
```

**期望行为**
正确运行，不应该超时

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

![20200426224935](https://gitee.com/daisenrong/resource/raw/master/images/20200426224935.jpg)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
超出时间限制，复杂度太高了，建议再仔细调试优化一下代码。

**Comment by daisenrong** [comment]
public void third(Runnable printThird) throws InterruptedException {
        while (flag.get() != 3) {
            
        }
        // printThird.run() outputs "third". Do not change or remove this line.
        printThird.run();
       flag.set(1);
    }

这样就好了，多个测试用例应该是只加载了了一次class，所以导致第二次的时候就阻塞了
