### ISSUE TITLE
Missing constraints for input - 279. Perfect Squares

### ISSUE THREAD

**Issue by Bambooin** [LeetCode-Feedback/LeetCode-Feedback#1990]
#### Your LeetCode username
0x4C0DE

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Some input will cause error or time limit, so we better having constraint
**Constraints:
    1 <= n <= 10^5**

#### Code you used for Submit/Run operation
```
class Solution {
  public int numSquares(int n) {
    int[] dp = new int[n + 1];

    int min;
    for (int i = 1; i <= n; i++) {
      min = Integer.MAX_VALUE;
      for (int j = 1; j * j <= i; j++) {
        min = Math.min(min, dp[i - j * j]);
      }

      dp[i] = min + 1;
    }

    return dp[n];
  }
}
```

#### Expected behavior
Missing constraints will cause exception
```
 int[] dp = new int[n + 1];
```
as for edge intput **Integer.MAX_VALUE**

#### Screenshots

 Large number > 10^5 will casue test wired behavior as screenshot show
![limit](https://user-images.githubusercontent.com/7157227/104431122-81862280-55c2-11eb-8284-92185e8e6fcf.png)

**Comment by lc-kay** [comment]
Hi @Bambooin 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Bambooin 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
