### ISSUE TITLE
Unexpected error after submitting PostgreSQL code.

### ISSUE THREAD

**Issue by bragov4ik** [LeetCode-Feedback/LeetCode-Feedback#19906]
### LeetCode Username
bragov4ik

### Problem number, title, and link
[1581. Customer Who Visited but Did Not Make Any Transactions](https://leetcode.com/problems/customer-who-visited-but-did-not-make-any-transactions/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [x] Programming language support

### Description of the bug
Select from SQL view results in a runtime error: "the last operation didn't produce a result" (PostgreSQL16). The same code (with the same schema) running in PostgreSQL 15 (at https://www.db-fiddle.com/) works well and produces output

### Language used for code
PostgreSQL

### Code used for Submit/Run operation

```SQL
CREATE VIEW TransactionedVisits AS
SELECT *
FROM Visits
NATURAL LEFT JOIN Transactions;

SELECT *
FROM TransactionedVisits
```

### Expected behavior
"Incorrect result" error with the defined view as output. Got "the last operation didn't produce a result" instead

### Additional context
Maybe I'm missing something or something changed from version 15 to 16 of PostgreSQL. If that's the case, sorry for false alarm. I can't check the behaviour on some 3rd party v16 postgres.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
