### ISSUE TITLE
Missing Test Case - 98. Validate Binary Search Tree

### ISSUE THREAD

**Issue by IlnurAgl** [LeetCode-Feedback/LeetCode-Feedback#19909]
### LeetCode Username
IlnurAgl

### Problem number, title, and link
98. Validate Binary Search Tree https://leetcode.com/problems/validate-binary-search-tree

### Category of the bug
- Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug
The test cases do not check the case when there may be 0 in the left subtree. Therefore, the check in the code without ```is None``` can pass. Example is test case [-1, 0, 1]

### Language used for code
Python 

### Code used for Submit/Run operation

```
# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
class Solution:
    def isValidBST(self, root: Optional[TreeNode]) -> bool:    
        def dfs(root):
            max_left = None
            min_right = None
            max_right = None
            min_left = None
            if not root.left and not root.right:
                return True, root.val, root.val
            if root.left:
                is_binary, max_left, min_left = dfs(root.left)
                if not is_binary:
                    return False, root.val, root.val
            if root.right:
                is_binary, max_right, min_right = dfs(root.right)
                if not is_binary:
                    return False, root.val, root.val
            if max_left and root.val <= max_left:
                return False, root.val, root.val
            if min_right is not None and root.val >= min_right:
                return False, root.val, root.val
            if max_left is None:
                max_left = root.val
            if min_right is None:
                min_right = root.val
            if max_right is None:
                max_right = root.val
            if min_left is None:
                min_left = root.val
            return True, max(max_left, root.val, max_right), min(min_right, root.val, min_left)
        return dfs(root)[0]
```

### Expected behavior
For [-1, 0, 1] is expected False, but program can return True and the tests won't catch this

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
