### ISSUE TITLE
Missing Test Case - 1137. Height Checker

### ISSUE THREAD

**Issue by HenryLiang-123** [LeetCode-Feedback/LeetCode-Feedback#1991]
#### Your LeetCode username

HenryLiang-123

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Question: Height Checker
Bug: A solution is accepted when there are test cases it doesn't pass. 
Test case: Input: [2,1]
                Expected Output: 1
                Solution Output: 2
Solution is still accepted

#### Code you used for Submit/Run operation

```
// Height Checker
function heightChecker(arr) {
  let sortedArr = arr.slice();
  sortedArr.sort((a, b) => a - b);
  let count = 0;

  for (let i = 0; i < arr.length; i++) {

    if (arr[i] !== sortedArr[i]) {
      count += 1;
    }

  }

  return count;
}
```

#### Language used for code

JavaScript

#### Expected behavior

The solution should be rejected because it does not pass the edge case of input = [2,1]. What actually happened was the solution was accepted.

**Comment by lc-kay** [comment]
@HenryLiang-123 I ran your code and the test case and the expected = actual. Please provide a screenshot of the issue if you received something else. Then, I will reopen this ticket to investigate further. Thank you for understanding, 
<img width="1432" alt="Screen Shot 2021-01-13 at 4 38 39 PM" src="https://user-images.githubusercontent.com/70870126/104529139-d4a9a680-55bd-11eb-8309-e732855b02bf.png">
