### ISSUE TITLE
Missing Test Case - 200. Number of Islands

### ISSUE THREAD

**Issue by bferg** [LeetCode-Feedback/LeetCode-Feedback#19912]
### LeetCode Username

bferg

### Problem number, title, and link

200. Number of Islands  https://leetcode.com/problems/number-of-islands/description/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Missing edge case test for left connected island, e.g.
```
    grid = [
        ["1","1","1","1","0"],
        ["1","1","0","1","0"],
        ["1","1","0","0","0"],
        ["0","0","1","0","1"],
        ["0","0","0","1","1"]
    ]
```
The correct solution will detect *three* islands. An approach recursing in only two directions would detect 4 instead of three "islands" but still pass the existing test cases.

### Language used for code

Python

### Code used for Submit/Run operation

```
class Solution(object):
    def dfs(self, grid, i, j):
        if (i < 0) or (i >= len(grid)):
            return
        if (j < 0) or (j >= len(grid[i])):
            return
        if self.visited[i][j]:
            return
        self.visited[i][j] = True
        if grid[i][j] != "0":
            # self.dfs(grid, i - 1, j)
            # self.dfs(grid, i, j - 1)
            self.dfs(grid, i + 1, j)
            self.dfs(grid, i, j + 1)
                
    def numIslands(self, grid):
        """
        :type grid: List[List[str]]
        :rtype: int
        """
        self.visited = [[]] * len(grid)
        for i in range(0, len(grid)):
            self.visited[i] = [False] * len(grid[i])

        n = 0
        for i in range(0, len(grid)):
            for j in range(0, len(grid[i])):
                if not self.visited[i][j] and grid[i][j] != "0":
                    n = n + 1
                    self.dfs(grid, i, j)
        return n
```

### Expected behavior

The code above (with the commented-out lines) passes the existing test cases, but will not pass the additional test case mentioned above. Uncommenting the lines will allow the new test case to pass.

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team

**Comment by bferg** [comment]
The submitted code is deliberately broken and is intended to illustrate that the supplied test cases are insufficient.
