### ISSUE TITLE
Bug -- 881. Boats to Save People -- test case doesn't have correct expected value

### ISSUE THREAD

**Issue by Harry-Yang-Huang** [LeetCode-Feedback/LeetCode-Feedback#1992]
#### Your LeetCode username

HuangYang

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language

#### Description of the bug

the test case people array [3,2,3,2,2] with limit 6 should have minimum boats 2, but the expected value is 3.

#### Code you used for Submit/Run operation

```
// Two Sum
int numRescueBoats(vector<int>& people, int limit) {
        int ret = 0;
        map<int, int> mp;
        for (int x: people) {
            if (x == limit) {
                ret++;
            }
            else mp[x]++;
        }
        while (mp.size()) {
            int sum = 0;
            while (mp.size() && limit-sum >= mp.begin()->first) {
                auto t = mp.upper_bound(limit-sum);
                t--;
                sum += t->first;
                mp[t->first]--;
                if (mp[t->first] == 0) mp.erase(t->first);
                
            }
            ret++;
        }
        
        return ret;
    }
```

#### Language used for code

C++

#### Expected behavior

when people array is [3,2,3,2,2] and limit is 6, minimum boats should be 2.

**Comment by lc-kay** [comment]
@Harry-Yang-Huang The expected output is correct.  Per the problem description, "Each boat carries at most 2 people at the same time..." Thank you for your time.
