### ISSUE TITLE
Missing Test Case - 20. Valid Parentheses

### ISSUE THREAD

**Issue by koshiya-juhil** [LeetCode-Feedback/LeetCode-Feedback#19928]
### LeetCode Username

https://leetcode.com/juhilkoshiya/

### Problem number, title, and link

20. Valid Parentheses : https://leetcode.com/problems/valid-parentheses/

### Category of the bug
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

While the current algorithm for the "Valid Parentheses" problem on LeetCode is generally correct, it lacks a specific test case that involves nested brackets with a mismatch within the nested structure. The missing test case is "()[{()]]", where there is an extra closing bracket ']' within the nested structure, leading to an invalid string. The current test cases doesn't have nested parentheses.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team
