### ISSUE TITLE
Missing Test Case - 2788. Split Strings by Separator

### ISSUE THREAD

**Issue by bishtanuj** [LeetCode-Feedback/LeetCode-Feedback#19921]
### Problem number, title, and link
2788. Split Strings by Separator https://leetcode.com/problems/split-strings-by-separator/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

There are some test cases that are missing due to which, it accepts the solution of the problem which is incorrect to some extent.

### Language used for code
Python

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
class Solution:
    def splitWordsBySeparator(self, words: List[str], separator: str) -> List[str]:
        temp = [i.split(separator) for i in words]
        string = ""
        for i in range(len(temp)):
            for j in temp[i]:
                string += j + "`"
        string += j
        result = string.split("`")
        result.pop()
        if "" in result:
            result = [i for i in result if i != ""]
        return result
```

### Expected behavior

The above code is wrong but as the test cases are missing, it seems right and accepted.
As there are test cases like where words = ["#|"], separator = "#", gives output ["|"], but like words = ["#`"], separator = "#" is missing, therefore it accepts the solution, which is not correct.

### Additional context

```md
Some new test cases are as follows:
Test Case 1:
words = ["#`], separator = "#", output = ["`"]

Test Case 2:
words = ["#~`], separator = "#", output = ["~"]
```

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
