### ISSUE TITLE
Negative value for number of days left in Weekly premium section

### ISSUE THREAD

**Issue by regotiss** [LeetCode-Feedback/LeetCode-Feedback#19929]
Username - nomadsomad

Not sure if this is the right place to report this issue.

Issue-
Negative value for the number of days left 
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/152602208/b0dec525-262b-4f11-bcd8-51e994fd16bf)

**Comment by LC-Pam** [comment]
Hello,

Thank you for providing your feedback.

Please note that our GitHub repository primarily addresses content and solution-related issues. To ensure a prompt response and effective resolution for feature, function, course access, or product-related feedback, we kindly encourage you to submit such inquiries through our Zendesk Support Channel:

[LeetCode Support](https://leetcode.com/support)

Our dedicated support agents typically respond within 24 hours and promptly report submitted issues to the appropriate departments for investigation.

We greatly appreciate your ongoing support and value your contributions to enhancing the LeetCode experience.

Best regards,
LeetCode Support Team
