### ISSUE TITLE
Missing Test Case - 2966. Divide Array Into Arrays With Max Difference

### ISSUE THREAD

**Issue by kinmanz** [LeetCode-Feedback/LeetCode-Feedback#19937]
### LeetCode Username
kinmanz

### Problem number, title, and link
[2966. Divide Array Into Arrays With Max](https://leetcode.com/problems/divide-array-into-arrays-with-max-difference/)
https://leetcode.com/problems/divide-array-into-arrays-with-max-difference/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
In the task description there is a required condition:
> Each element of nums should be in exactly one array.
But there is no check to test that.

For example, if my program takes such input
`nums = [1, 1, 1, 1, 1, 1], k = 2`
and returns 
`[[1, 1, 1], [1, 1, 1]]` there is no issue with that, though it violates the task description.

### Language used for code
Kotlin

### Code used for Submit/Run operation

```
class Solution {
    fun divideArray(nums: IntArray, k: Int): Array<IntArray> {
        nums.sort()
        val res = mutableListOf<IntArray>()
        nums.asSequence().windowed(3, step = 3).forEach {
            if (it[2] - it[0] > k) return arrayOf()
            else res.add(it.toIntArray())
        }
        return res.toTypedArray()
    }
}
```

### Expected behavior
The code should not pass tests. For example such a test `nums = [1, 1, 1, 1, 1, 1], k = 2`

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
