### ISSUE TITLE
Wrong Test Case - 127. Word Ladder

### ISSUE THREAD

**Issue by shreyesh-khanzode** [LeetCode-Feedback/LeetCode-Feedback#1994]
#### Your LeetCode username

skskhanzode

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

How does the test case below returns 5 as the answer, when "dog" and  "lot" differ in two letters whereas the problem statement 
 clearly states Only one letter is different between each adjacent pair of words in the sequence?
Input: 
"hit"
"cog"
["hot","dot","dog","lot","log","cog"]

Output: 5

#### Expected behavior
The output should be 0.

**Comment by lc-kay** [comment]
@shreyesh-khanzode As stated in the example explanation, "One shortest transformation is "hit" -> "hot" -> "dot" -> "dog" -> "cog" with 5 words." Although "dog" and "lot" differ in two letters in the word list, you are not required to use all the words in the list to transform the beginWord to the endWord. As shown in the transformation process, only one letter is different between each adjacent pair of words in the sequence. In you still have any doubts, please refer to the discuss section of this problem. Thank you for your time!
