### ISSUE TITLE
Missing Test Case - 207. Course Schedule

### ISSUE THREAD

**Issue by nhkhiemSWE** [LeetCode-Feedback/LeetCode-Feedback#19942]
### LeetCode Username

thetaximit

### Problem number, title, and link
 https://leetcode.com/problems/course-schedule/?envType=study-plan-v2&envId=top-interview-150

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support
Missing test Case

### Language used for code

TypeScript

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
let graph : number[][] = new Array();
    for (let i = 0; i < numCourses; i ++){
        graph.push(new Array());
    }
    
    // Way 2: Going upward but there is a bug in the testcases
    for (const [post, pre] of prerequisites) {
        graph[post].push(pre);
    }
    let canFinishSet : Set<number> = new Set();
    function canFinish(node: number, path: Set<number>) : boolean {
        let preReqs = graph[node];
        if (preReqs.length === 0) {
            // console.log(node, "TRUE");
            return true;
        }
        for (const pre of preReqs) {
            // console.log(node, pre);
            // console.log(canFinishSet);
            // console.log(path);
            if (path.has(pre)) {
                // console.log(node, "FALSE", pre, path);
                return false;
            }

            if (canFinishSet.has(pre)) {
                // console.log(canFinishSet, pre);
                return true;
            }
            path.add(node);
            let able = canFinish(pre, path);
            path.delete(node);
            if (able) {
                canFinishSet.add(pre);
            } else {
                // console.log(node, "FALSE");
                return false;
            }
        }
        // console.log(node, "True")
        return true;
    }
    for (let course = 0; course < numCourses; course ++) {
        // console.log(canFinishSet);
        if (canFinishSet.has(course)) {
            continue;
        }
        if (!canFinish(course, new Set())) return false;
    }
    return true;
}
```

### Expected behavior

The code passed the whole test cases but when I used my test case: [[1,0],[2,1],[1,3], [4,3], [4,1], [5,4], [4,5]], it fails. 
It should return false but return true instead. 

The key here: the function canFinish return true for node when it encounters 1 prereq of that node which presents in the canFinishSet. However, this behavior is not necessarily true as the later prereq can be false and it will mess up. 

### Screenshots

![Screenshot 2024-02-01 at 10 23 26 AM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/156524637/bf1d5a5a-4ec8-46ea-9969-96037df36d67)
![Screenshot 2024-02-01 at 10 23 54 AM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/156524637/6c079742-ba67-4252-83b4-53fac3ee31a0)

### Additional context

the test case that I used: [[1,0],[2,1],[1,3], [4,3], [4,1], [5,4], [4,5]]

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team
