### ISSUE TITLE
Incorrect Test Case result  - 88. Merge Sorted Array

### ISSUE THREAD

**Issue by Feiyang-Li** [LeetCode-Feedback/LeetCode-Feedback#19945]
### LeetCode Username

li1fei2yang3lfy4

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- Y Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Giving:
Input: nums1 = [0], m = 0, nums2 = [1], n = 1
Expected : [1]
Actual: [0]

I used console of chrome to test out my code, the actual output is [1]. Same with my local node.js testing. 

### Language used for code
JavaScript

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
var merge = function(nums1, m, nums2, n) {
    if (n + m === 0) {
        return nums1;
    }
    if (n === 0) {
        return nums1;
    }
    if (m === 0) {
        return nums2;
    }
    if (m === 1 && n === 1) {
        return nums1[0] < nums2[0] ? [nums1[0], nums2[0]] : [ nums2[0], nums1[0]];
    }

    var newM = Math.ceil(m / 2);
    var newN = Math.ceil(n / 2);
    var emptyM = new Array(m - newM).fill(0);
    var emptyN = new Array(n - newN).fill(0);
    var sorted1 = merge(nums1.slice(0, newM).concat(emptyM), newM, nums1.slice(newM, m + 1), m - newM);
    var sorted2 = merge(nums2.slice(0, newN).concat(emptyN), newN, nums2.slice(newN, n + 1), n - newN);

    var [i, j, k] = [0, 0, 0];

    while(i < m || j < n) {
        if(i === m) {
            nums1[k] = sorted2[j];
            j++;
            k++;
        }
        if(j === n) {
            nums1[k] = sorted1[i];
            i++;
            k++;
        }
        if(sorted1[i] < sorted2[j]) {
            nums1[k] = sorted1[i];
            i++;
            k++;
        } else {
            nums1[k] = sorted2[j];
            j++;
            k++;
        }
    }
    return nums1;
};
```

### Expected behavior

Pass test 3:

### Screenshots

using google chrome
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/123399631/a46eb389-e50a-4531-939e-3a4bd66d9853)
using leetcode
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/123399631/969597b1-309b-4291-b20f-e324bf073e34)

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
