### ISSUE TITLE
Missing Test Case - 724. Find Pivot Index

### ISSUE THREAD

**Issue by Narsi7777** [LeetCode-Feedback/LeetCode-Feedback#19951]
<img width="833" alt="Screenshot 2024-02-02 005623" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/154037409/b3a7c897-d0e7-438d-8952-c030e36e7c86">

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

**Comment by Narsi7777** [comment]
i am getting expected output in some other compilers

**Comment by LC-Pam** [comment]
Thank you for getting back to us! Regrettably, troubleshooting the variance between your local Integrated Development Environment (IDE) and the LeetCode environment poses a challenge for us.

In such cases, we recommend raising this issue as a discussion post in the problem's discussion section. This allows you to tap into the collective knowledge and experiences of our user community. Many users may have encountered similar challenges and could offer insights or solutions that can be valuable in resolving the discrepancy.

At LeetCode, we foster a collaborative learning environment, and we believe in the power of users to help each other to enhance their learning experience. Debugging and learning from the process are integral parts of the coding journey, and the community's diverse perspectives can be immensely beneficial.

We appreciate your understanding, and if you have any more questions or need further assistance, please feel free to let us know. Your time and support are highly valued.

Best regards,
The LeetCode Team
