### ISSUE TITLE
Missing Test Case - 1291. Sequential Digits

### ISSUE THREAD

**Issue by IC-99** [LeetCode-Feedback/LeetCode-Feedback#19958]
### LeetCode Username

IC-99

### Problem number, title, and link

1291. Sequential Digits https://leetcode.com/problems/sequential-digits/

### Category of the bug
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

missing test case.

### Language used for code

Python 3

### Code used for Submit/Run operation

```
class Solution:
    def sequentialDigits(self, low: int, high: int) -> List[int]:
        data = [12,23,34,45,56,67,78,89,\
                123,234,345,456,567,678,789,\
                1234,2345,3456,4567,5678,6789,\
                12345,23456,34567,45678,56789,\
                123456,234567,345678,456789,\
                1234567,2345678,3456789,\
                12345678,23456789,\
                123456789]
        start = 0
        while start < len(data) and data[start] < low:  start += 1
        end = len(data) - 1
        while end > 0 and data[end] > high: end -= 1
        if low == high: return []
        return data[start:end+1]
```

### Expected behavior

The test case with low=67 and high=67 should return [67], but my code is returning []. Therefore, I suspect that this test case might be missing, as my code was accepted.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
