### ISSUE TITLE
Unclear Description in Problem 114

### ISSUE THREAD

**Issue by Ajitesh13** [LeetCode-Feedback/LeetCode-Feedback#1995]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Unclear description of the question. Instead of just "Flatten the binary tree" it should be something like "flatten the binary tree in postorder" because not mentioning the postorder means, the user can do flattening in any way like inorder or just random flattening by traveling in the root.right direction.

**Comment by lc-kay** [comment]
Hi @Ajitesh13 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Ajitesh13 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
