### ISSUE TITLE
MISSING TESTCASE -> 365. Water and Jug Problem

### ISSUE THREAD

**Issue by waterComplex** [LeetCode-Feedback/LeetCode-Feedback#19968]
### LeetCode Username
waterComplex

### Problem number, title, and link

365. Water and Jug Problem https://leetcode.com/problems/water-and-jug-problem/

### Category of the bug
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

severals solution is being accepted while submitting but show time limit exceed on a valid test case
test case --> jug1Capacity = 999911, jug2Capacity = 999913 and targetCapacity = 1

### Language used for code
C++

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
class Solution {
public:
    bool canMeasureWater(int jug1Capacity, int jug2Capacity, int targetCapacity) {

        queue<pair<int, int>> qu;
        set<pair<int, int>> vis;
        vis.insert({0,0});
        qu.push({0, 0});

        while(qu.size() > 0) {
            pair<int, int> u = qu.front(); qu.pop();
            if(u.first + u.second == targetCapacity) return true;

            // fill 1st jug
            if(u.first < jug1Capacity && !vis.count({jug1Capacity, u.second})) {
                qu.push({jug1Capacity, u.second});
                vis.insert({jug1Capacity, u.second});
            }

            // fill 2nd jug
            if(u.second < jug2Capacity && !vis.count({u.first, jug2Capacity})) {
                qu.push({u.first, jug2Capacity});
                vis.insert({u.first, jug2Capacity});
            }

            // empty 1st jug
            if(u.first > 0 && !vis.count({0, u.second})) {
                qu.push({0, u.second});
                vis.insert({0, u.second});
            }

            // empty 2nd jug
            if(u.second > 0 && !vis.count({u.first, 0})) {
                qu.push({u.first, 0});
                vis.insert({u.first, 0});
            }

            // pour 1st jug into 2nd jug
            int pouringQuant = min(u.first, jug2Capacity - u.second);
            if(pouringQuant > 0 && !vis.count({u.first - pouringQuant, u.second + pouringQuant})) {
                qu.push({u.first - pouringQuant, u.second + pouringQuant});
                vis.insert({u.first - pouringQuant, u.second + pouringQuant});
            }

            // pour 2nd jug into 1st jug
            pouringQuant = min(u.second, jug1Capacity - u.first);
            if(pouringQuant > 0 && !vis.count({u.first + pouringQuant, u.second - pouringQuant})) {
                qu.push({u.first + pouringQuant, u.second - pouringQuant});
                vis.insert({u.first + pouringQuant, u.second - pouringQuant});
            }
        }
        return false;
        
    }
};
```

### Expected behavior

this code should give time limit exceed while submitting but it doesn't.
the code should not be accepted while submitting as it fails on the testcase
jug1Capacity = 999911, jug2Capacity = 999913 and targetCapacity = 1

### Screenshots

<img width="1325" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/111220824/f4ce8854-27f4-4143-904f-d73a470dbc26">
<img width="1428" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/111220824/33f52b2d-5fce-400b-ad12-d57ca09274dc">

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by waterComplex** [comment]
waiting for reply
