### ISSUE TITLE
Missing Test Case - 954. Array of Doubled Pairs

### ISSUE THREAD

**Issue by larrygao2000** [LeetCode-Feedback/LeetCode-Feedback#1996]
#### Your LeetCode username
larrygao2000

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
It misses the negative test cases when all numbers are larger than 50000

#### Code you used for Submit/Run operation

```
    public boolean canReorderDoubled(int[] A) {

       int[] pos=new int[100001];
        int[] neg=new int[100001];
        for(int i=0;i<A.length;i++){
            if(A[i]>=0)pos[A[i]]++;
            else{
                neg[-A[i]]++;
            }
        }
        
        for(int i=0;i<=50000;i++){
            if(pos[i]>0){
                pos[2*i]-=pos[i];
                if(pos[i*2]<0)return false;
            }
            
            if(neg[i]>0){
                neg[2*i]-=neg[i];
                if(neg[2*i]<0)return false;
            }
        }
        
        return true;
    }
```

#### Language used for code
Java

#### Expected behavior

The solution is accepted as below:

Time Submitted | Status | Runtime | Memory | Language
-- | -- | -- | -- | --
01/13/2021 11:49 | Accepted | 7 ms | 47.5 MB | java

However, it will NOT pass a simple test case with input:
[50001, 50002]

**Comment by lc-kay** [comment]
Hi @larrygao2000 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @larrygao2000 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
