### ISSUE TITLE
Problem Description - 295. Find Median from Data Stream

### ISSUE THREAD

**Issue by khaled-elnaggar** [LeetCode-Feedback/LeetCode-Feedback#19976]
### LeetCode Username
[kh_nj](https://leetcode.com/kh_nj/)

### Problem number, title, and link
[295. Find Median from Data Stream](https://leetcode.com/problems/find-median-from-data-stream/)

### Category of the bug
- [x] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
The problem has the definition of **median** as 
> The median is the middle value in an ordered integer list

An ordered list does not necessarily mean sorted.
Ordered vs Unordered data structures
An example of an ordered data structure
```
List<Integer> l= List.of(5, -3, 8, 0); 
// is ordered because I can do 
l.get(index);
// it is however not sorted
```
An example of an unordered data structure
```
Set<Integer> s = Setof(5, -3, 8, 0); 
// is unordered because I can NOT do
// s.get(index);
```

The difference is subtle but confusing.

### Fix
In the problem description, change the **median** definition from `ordered list` to `sorted list` or clarify it more like `ordered ascendingly or descendingly`

As defined in the following references
https://en.wikipedia.org/wiki/Median
https://economictimes.indiatimes.com/definition/median

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
