### ISSUE TITLE
Missing Test Case - 298. Binary Tree Longest Consecutive Sequence

### ISSUE THREAD

**Issue by YiwenCui** [LeetCode-Feedback/LeetCode-Feedback#19977]
### LeetCode Username

Ivy_cui

### Problem number, title, and link

298. Binary Tree Longest Consecutive Sequence https://leetcode.com/problems/binary-tree-longest-consecutive-sequence/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

A solution like this submission has bug, current test cases does not detect that:

https://leetcode.com/problems/binary-tree-longest-consecutive-sequence/submissions/1164297731/

### Language used for code

Python3

### Code used for Submit/Run operation

```
class Solution:
    def longestConsecutive(self, root: Optional[TreeNode]) -> int:
        res = []
        def dfs(node):
            if not node:
                return (0, 0)
            left = dfs(node.left)
            right = dfs(node.right)
            temp = 1
            if right[0]-node.val == 1:
                temp =  right[1]+1
            if left[0] - node.val == 1:
                temp =  left[1]+1
            res.append(temp)
            return(node.val, temp)
        
        dfs(root)
        return max(res)
```

### Expected behavior

Detected error in code

### Screenshots

<img width="1203" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/26207491/684015d6-f65d-4b75-9b06-662130d3dd95">

### Additional context

This test case should be able to catch that

```
root =
[1,null,3,4,4,null,null,null,5]
```

<img width="881" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/26207491/5c7beb6c-246e-4e9b-ad30-00121f0fcdfc">

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
