### ISSUE TITLE
wrong output testcase

### ISSUE THREAD

**Issue by coderman-afk** [LeetCode-Feedback/LeetCode-Feedback#19983]
### Problem number, title, and link

1. Regular Expression Matching https://leetcode.com/problems/regular-expression-matching/description/

### Category of the bug

Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### Description of the bug

character c in pattern p cannot be mached with any character in string s since string s cannot be modified

### Language used for code

java

### Code used for Submit/Run operation

```
class Solution {
    static boolean ways(char s[],char p[],int i,int j,boolean dp[][]){
        if(i<0 && j<0)
        return true;
        else if(j<0)
        return false;
        else if(i<0){
while(p[j]=='*' || p[j]=='.')
return ways(s,p,i,j-1,dp);
return false;
        }
        if(dp[i][j])
        return dp[i][j];
        if((s[i]==p[j])||(p[j]=='.'))
        return dp[i][j]=ways(s,p,i-1,j-1,dp);
        else if(p[j]=='*'){
            boolean  notpick=ways(s,p,i-1,j-1,dp);
            boolean pick=ways(s,p,i-1,j,dp);
            return dp[i][j]=pick || notpick;
        }
        else
        return dp[i][j]=false;

    }
    public boolean isMatch(String s, String p) {
        char S[]=s.toCharArray();
        char P[]=p.toCharArray();
        boolean  dp[][]=new boolean[S.length][P.length];
        return ways(S,P,s.length()-1,p.length()-1,dp);
    }
}
```

### Expected behavior

it should return false since if any character in pattern p is not present in string s they  will  be definitely not equal,,please check this testcase

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/153625946/bd8e2dbc-8cce-41d1-a347-8142d4df1df4)

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
