### ISSUE TITLE
Missing Test Case - 735. Asteroid Collision

### ISSUE THREAD

**Issue by vikram-8290** [LeetCode-Feedback/LeetCode-Feedback#19980]
### LeetCode Username

vikramsisodiya8290

### Problem number, title, and link

735. Asteroid Collision

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

what append when an asteroid with magnitude '0' arrives at beginning i.e. asteroid[0] = 0
### Code used for Submit/Run operation

```
class Solution:
    def asteroidCollision(self, asteroids: List[int]) -> List[int]:
        ans = []
        if asteroids[0] == 0:
            ans.append(0)
        for i in asteroids:
            while ans and i < 0 and ans[-1] > 0:
                diff = i + ans[-1]

                if diff < 0:
                    ans.pop()
                elif diff > 0:
                    i = 0
                else:
                    i = 0
                    ans.pop()
            if i:
                ans.append(i)
        return ans
                
                
```

### Expected behavior

the test case will passed
Test case :
Asteroid = [0 -2 ,-4 ,2 ,-4 ,4 ,4 ,0 ,5 ,3 ]
expected result with update in  code:
[0 -2 -4 -4 4 4 5 3 ]

### Additional context

The Test given below will fail to give correct result:
```
Asteroid = [0 -2 ,-4 ,2 ,-4 ,4 ,4 ,0 ,5 ,3 ]
```

**Comment by stormsunshine** [comment]
The last constraint requires `asteroids[i] != 0`. Please read problem description carefully.
