### ISSUE TITLE
Missing Test Case - 15. 3Sum

### ISSUE THREAD

**Issue by tredsused40** [LeetCode-Feedback/LeetCode-Feedback#19984]
### LeetCode Username

tredsused70

### Problem number, title, and link

15. 3Sum https://leetcode.com/problems/3sum/

### Category of the bug
- [.] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

Code that gets TLE on some testcases when used "Run" operation is accepted when used "Submit" operation.

### Language used for code

C++

### Code used for Submit/Run operation

```
class Solution {
public:
    vector<vector<int>> threeSum(vector<int>& nums) {
        vector<vector<int>> ans;
        sort(nums.begin(), nums.end());
        int n = nums.size(), pos, sum = 0;
        for(int i = 0; i < n; i++) {
            pos = n - 1;
            for(int j = i + 1; j < n; j++) {
                sum = nums[i] + nums[j] + nums[pos];
                while(pos > j && sum > 0) {
                    sum -= nums[pos];
                    pos--;
                    sum += nums[pos];
                }
                if(pos == j)
                    break;
                if(sum == 0) {
                    ans.push_back({nums[i], nums[j], nums[pos]});
                }
            }
        }
        sort(ans.begin(), ans.end());
        ans.erase(unique(ans.begin(), ans.end()), ans.end());
        return ans;
    }
};
```

### Expected behavior

One of the worst cases for this code is to push into the vector named ans n * (n - 1) / 2 vectors of size 3, and then sort them, n is size of nums vector. The value of n can be 3e3, so the code tries to sort roughly 4.5e6 vectors of size 3, which takes more time than Time Limit.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/75163817/08311dea-c520-4cc8-8849-b862777200d4)

### Additional context

Here is the .txt file with the test. 
[test.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/14151198/test.txt)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
