### ISSUE TITLE
Wrong table name - 2991. Top Three Wineries

### ISSUE THREAD

**Issue by xelplogoog** [LeetCode-Feedback/LeetCode-Feedback#19998]
### LeetCode Username
c4tdog

### Problem number, title, and link
[2991. Top Three Wineries](https://leetcode.com/problems/top-three-wineries/)

### Description of the bug
Wrong table name in example, should be `wineries`, but it is `sessions`

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2188302/85e09e88-66c1-4b98-8b9a-cc0a05266c45)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team
