### ISSUE TITLE
Constraints - 3027.  Find the Number of Ways to Place People II

### ISSUE THREAD

**Issue by MKLOL** [LeetCode-Feedback/LeetCode-Feedback#19991]
### LeetCode Username
MKLOL

### Problem number, title, and link
3027.  Find the Number of Ways to Place People II: https://leetcode.com/problems/find-the-number-of-ways-to-place-people-ii/description/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [x] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [x] Programming language support

### Description of the bug
Constraints too tight. O(N^2) solution with coordinate compression and 2d prefix sums TLEs. This is a method known to solve these types of problems so do not understand why the constraints are in such a way that it causes TLEs, especially since looking at other solutions people have O(N^2logN). 

### Language used for code
C++

### Code used for Submit/Run operation
https://leetcode.com/contest/biweekly-contest-123/submissions/detail/1164877533/
https://leetcode.com/contest/biweekly-contest-123/submissions/detail/1164919703/

```
typedef long long ll;
typedef vector<int> vi;
typedef pair<int,int> pii;
typedef pair<double, double> pdd;
#define pb push_back
#define mp make_pair
#define fs first
#define sc second
#define rep(i, from, to) for (int i = from; i < (to); ++i)
#define all(x) x.begin(), x.end()
#define sz(x) (int)(x).size()
#define FOR(i, to) for (int i = 0; i < (to); ++i)
typedef vector<vector<int> > vvi;
typedef vector<ll> vll;
typedef vector<vll> vvll;
typedef vector<pair<int, int> > vpi;
typedef pair<ll,ll> pll;
typedef vector<string> vs;

class NormVec {
public:
    vector<int> v;
    int offset = 1;
 

    void add(int x) {
        v.push_back(x);
    }
 
    void make() {
        sort(v.begin(), v.end());
        v.erase(unique(v.begin(), v.end()), v.end());
    }
 
    int eq(int x) {
        auto it = lower_bound(v.begin(), v.end(), x);
        if (*it == x) {
            return it - v.begin() + offset;
        }
        return -1;
    }
};

vector<vector<int>> sm;

int cmp(vi a, vi b) {
    if (a[0] == b[0]) {
        return a[1] > b[1];
    }
    return a[0] < b[0];
}
class Solution {
public:
    int numberOfPairs(vector<vector<int>>& P) {
        NormVec vx, vy;
        for(auto x : P) {
            vx.add(x[0]);
            vy.add(x[1]);
        }
        vx.make();
        vy.make();
        if (sz(sm) == 0) {
            FOR(i, 1030) {
                vi vc(1030);
                sm.pb(vc);
            }
        }
        int N = sz(vx.v)+3;
        int M = sz(vy.v)+3;
        FOR(i, N + 3) {
            FOR(j, M + 3) {
                sm[i][j] = 0;
            }
        }
        for(auto &x : P) {
            x[0] = vx.eq(x[0]);
            x[1] = vy.eq(x[1]);
            sm[x[0]][x[1]]++;
        }

        FOR(i, N) {
            FOR(j, M) {
                if (i) {
                    sm[i][j] += sm[i-1][j];
                }
                if (j) sm[i][j] += sm[i][j-1];
                if (i && j) sm[i][j] -= sm[i-1][j-1];
            }
        }
        int ret = 0;
        sort(all(P), cmp);
        FOR(i, sz(P)) {
            rep(j, i+1, sz(P)) {
                auto x = P[i]; auto y = P[j];
                
                if (x[1] >= y[1]) {
                    int ac = sm[y[0]][x[1]] - sm[x[0] - 1][x[1]] - sm[y[0]][y[1] - 1] + sm[x[0]-1][y[1]-1];
                    if (ac == 2) ret++;
                }
            }
        }
        return ret;
    }
};
```

### Expected behavior
Not to time limit. Especially based on the constraints.

### Additional context
To also note this java solution with the exact same idea passes:
https://leetcode.com/contest/biweekly-contest-123/submissions/detail/1164844994/

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Constraints are not tight. n <= 1000 for O(n^2) is actually even loose. It’s also strange for me that why your solution get’s TLE. Can you try to submit using array instead of vector?

**Comment by MKLOL** [comment]
https://leetcode.com/problems/find-the-number-of-ways-to-place-people-ii/submissions/1169174489/

Did with array. Still TLE. in java a replica of this works in 500 ms.
