### ISSUE TITLE
Missing Test Case - 3026. Maximum Good Subarray Sum

### ISSUE THREAD

**Issue by CuteTN** [LeetCode-Feedback/LeetCode-Feedback#19995]
### LeetCode Username
CuteTN

### Problem number, title, and link
3026. Maximum Good Subarray Sum https://leetcode.com/problems/maximum-good-subarray-sum/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
There's an O(n^2) solution (given below) that luckily got passed due to weak testcases.

### Language used for code
C++

### Code used for Submit/Run operation
```cpp
class Solution {
public:
    long long maximumSubarraySum(vector<int>& nums, int k) 
    {
            unordered_map<int, vector<int>> numIndices;
    vector<long long> prefixSums(nums.size());
    long long maxSum = LONG_MIN;
    bool isPresent = false;
    long long currentSum;
    prefixSums[0] = nums[0];
    
    for (int i = 1; i < nums.size(); ++i)
    {
        prefixSums[i] = prefixSums[i - 1] + nums[i];
    }

    

    for (int i = 0; i < nums.size(); ++i)
    {
        if (numIndices.find(nums[i] - k) != numIndices.end())
        {
            isPresent = true;
            for (int x : numIndices[nums[i] - k]) 
            {
                if (x == 0)
                {
                    currentSum = prefixSums[i];
                } else 
                {
                    currentSum = prefixSums[i] - prefixSums[x - 1];
                }
                maxSum = max(maxSum, currentSum);
            }
        }

        if (numIndices.find(nums[i] + k) != numIndices.end()) 
        {
            isPresent = true;
            for (int x : numIndices[nums[i] + k])
            {
                if (x == 0)
                {
                    currentSum = prefixSums[i];
                } else 
                {
                    currentSum = prefixSums[i] - prefixSums[x - 1];
                }
                maxSum = max(maxSum, currentSum);
            }
        }

        numIndices[nums[i]].push_back(i);
    }

    return isPresent ? maxSum : 0;

    }
};
```

### Expected behavior
The solution shouldn't get accepted. I have found a testcase that could reject this solution with a TLE. As the testcase is too huge, so this is the code to generate it (written in JavaScript):
```js
let k = 2;

let nums = Array(100000).fill(1);
for (let i = 0; i < 100000; i += 2) nums[i] = 3;
```
In addition, please add more testcases like this with noises and randomness to avoid magic conditions.

**Comment by Gauravtheone** [comment]
but don't u think that map size will be only 2 in this case and in each key we will have a vector of size 100000/2, so won't the time complexity will be O(2*(50000)*log(2)), correct me if i'm wrong

**Comment by devansh0627** [comment]
but don't u think that map size will be only 2 in this case and in each key we will have a vector of size 100000/2, so won't the time complexity will be O(2*(50000)*log(2)), correct me if i'm wrong

**Comment by CuteTN** [comment]
> but don't u think that map size will be only 2 in this case and in each key we will have a vector of size 100000/2, so won't the time complexity be O(2*(50000)*log(2)), correct me if i'm wrong

Hi @devansh0627, as you pointed out, the vector's max size would be O(n/2) == O(n), you can have a look at this:
```cpp
    for (int i = 0; i < nums.size(); ++i)
    {
        if (numIndices.find(nums[i] - k) != numIndices.end())
        {
            isPresent = true;
            for (int x : numIndices[nums[i] - k]) 
            {
   /// ...
```
The `for (int i = 0; i < nums.size(); ++i)` cost O(nums.length), and the `for (int x : numIndices[nums[i] - k])` also costs O(n). Therefore it's O(n^2) in total.
And this is not just in theory, I have tried the testcase and it's really a TLE.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by devansh0627** [comment]
> > but don't u think that map size will be only 2 in this case and in each key we will have a vector of size 100000/2, so won't the time complexity be O(2*(50000)*log(2)), correct me if i'm wrong
> 
> Hi @devansh0627, as you pointed out, the vector's max size would be O(n/2) == O(n), you can have a look at this:
> 
> ```c++
>     for (int i = 0; i < nums.size(); ++i)
>     {
>         if (numIndices.find(nums[i] - k) != numIndices.end())
>         {
>             isPresent = true;
>             for (int x : numIndices[nums[i] - k]) 
>             {
>    /// ...
> ```
> 
> The `for (int i = 0; i < nums.size(); ++i)` cost O(nums.length), and the `for (int x : numIndices[nums[i] - k])` also costs O(n). Therefore it's O(n^2) in total. And this is not just in theory, I have tried the testcase and it's really a TLE.

oh yeah mb , i didn't observe the outer loop which will still be running for 1e5 and each key will be having 1e5/2 as vector size so  the TC will be quadratic.
