### ISSUE TITLE
Missing Test Case - 3026. Maximum Good Subarray Sum

### ISSUE THREAD

**Issue by Ankursharma192001** [LeetCode-Feedback/LeetCode-Feedback#19996]
### LeetCode Username

scorpioneer

### Problem number, title, and link

3026.[Maximum Good Subarray Sum](https://leetcode.com/problems/maximum-good-subarray-sum/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

Missing  test Case :  Inefficient Code getting accepted because of missing test cases

### Description of the bug

Test case is missing due to which O(N^3) is getting accepted 

### Language used for code

C++

### Code used for Submit/Run operation

```
class Solution {
public:
    long long maximumSubarraySum(vector<int>& nums, int k) {
        
        // contains first index of each element
        map<int,int>index;
        
        for(int i = 0 ; i < nums.size() ; i++)
        {
            if(index.find(nums[i]) == index.end())
            {
                index[nums[i]] = i; 
            }
        }
        int n = nums.size();
        
        vector<long long>prefix(n,0);
        
        prefix[0] = nums[0];
        
        for( int i = 1 ; i < n ; i++)
        {
            prefix[i] = prefix[i-1] + (long long) nums[i];
        }
        
        long long ans = -1e17;
        
        map<int,vector<int>>lastIndex;
        
        for( int j = 0 ; j < n ; j++)
        {   
            if(lastIndex.find(nums[j] + k) != lastIndex.end())
            {   
                for( auto ele : lastIndex[nums[j] + k])
                {
                    int iIndex = ele;
                
                    long long value = prefix[j]-prefix[iIndex] + (long long)nums[iIndex];

                    ans = max( ans , value);
                }
                
            }
             if(lastIndex.find(nums[j] - k) != lastIndex.end())
            {
                for( auto ele : lastIndex[nums[j] - k])
                {
                    int iIndex = ele;
                
                    long long value = prefix[j]-prefix[iIndex] + (long long)nums[iIndex];

                    ans = max( ans , value);
                }
            }
            
            lastIndex[nums[j]].push_back(j);
            
        }
        
        
        return ans == -1e17 ? 0 : ans;
    }
};
// Paste your code here. Don't remove ``` given

// above and below the code.
```

### Expected behavior

Time limit exceeded is expected but code is getting accepted

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/100678940/5d622448-4fbe-4b13-8824-339f0142cae5)

### Additional context

This code is getting accepted but It should give TLE because it is not optimised code . 

Test Case On which this code fails 

k = 1
nums =  40000 times 2 and 40000 times 3 <!-- Can write complete array because of character constraints->

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team
