### ISSUE TITLE
Missing Test Case - 222. Count Complete Tree Nodes

### ISSUE THREAD

**Issue by NihalAgarwal** [LeetCode-Feedback/LeetCode-Feedback#1999]
#### 
- [ ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

This problem needs a **Follow up** to be added in its description so that the user should know that they should come up with a solution of O( log(n)*log(n) ) instead of O(n).
The problem description contains:
#### Follow-up
1. Do it less than O(n).

#### Code you used for Submit/Run operation

```
class Solution {
    public int countNodes(TreeNode root) {
        if(root == null) return 0;

        int hl=0, hr=0;

        TreeNode l = root; 
        TreeNode r = root;

        while(l != null) {
            hl++;
            l = l.left;
        }

        while(r != null) {
            hr++;
            r = r.right;
        }

        if (hl==hr) return (1<<hl)-1;

        return 1 + countNodes(root.left) + countNodes(root.right);
        
    }
}
```

**Comment by lc-kay** [comment]
Hi @NihalAgarwal 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @NihalAgarwal 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
