### ISSUE TITLE
wrong taste case

### ISSUE THREAD

**Issue by Sharmashubham73** [LeetCode-Feedback/LeetCode-Feedback#20002]
### LeetCode Username
https://leetcode.com/Mr_Shubham73/

### Problem number, title, and link
[2550. Count Collisions of Monkeys on a Polygon](https://leetcode.com/problems/count-collisions-of-monkeys-on-a-polygon/)

### Category of the bug

- [ yes] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### Description of the bug

the output of the one input 500000003 is 10 digit number and i think it is incorrect

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
class Solution {
private:long long mod=1000000007;
public:
     long long powerof2(int m ){
        if(m==0){
            return 1LL;
        }
        long long temp=powerof2(m/2LL);
        temp%=mod;
        if(m%2==0){
        return ((temp)%mod*(temp)%mod)%mod;
        }
        else{
            return (2*((temp)%mod*(temp)%mod)%mod)%mod;
        }
    }
    int monkeyMove(int n) {
        long long totalwaysforallmonkey=(powerof2(n))%mod;
        long long nocollisionway=2LL;
        long long ans=(totalwaysforallmonkey-nocollisionway);
        return ans;
    }
};
// above and below the code.
```

**Comment by ritikrai999** [comment]
First learn modular arithmetic and the raise the issues.

correction in your code.
**long long ans=((totalwaysforallmonkey-nocollisionway)+mod)%mod;**

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code Accepted submission link you submitted led to the observed result.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team
