### ISSUE TITLE
Missing Test Case - 151. Reverse Words in a String

### ISSUE THREAD

**Issue by aliktl** [LeetCode-Feedback/LeetCode-Feedback#20009]
### LeetCode Username
[https://leetcode.com/ali95/](https://leetcode.com/ali95/)

### Problem number, title, and link
151. Reverse Words in a String https://leetcode.com/problems/reverse-words-in-a-string

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
After generating the solution that passed all existing test cases I came up with another test case which does not pass. Meaning there are potentially a lot of solutions submitted and accepted but wrong.

### Language used for code
Python

### Code used for Submit/Run operation

```
class Solution:
    def reverseWords(self, s: str) -> str:
        if ' ' not in s:
            return s
        n = len(s)
        index = 0
        left=n-1
        while n>0:
            if s[left]==' ':
                s = s[:left]
                n-=1
                left-=1
            elif s[left]!=' ':
                if s[left-1]==' ':
                    fixed = len(s[left:])
                    n-= fixed
                    s = s[0:index]+s[left:]+' '+s[index:left]
                    index+= fixed+1
                    left = left+fixed
                elif s[left-1]!=' ':
                    left-=1
                    
        
        return s[:-1] if s[-1]==' ' else s
```

### Expected behavior

The test cases in the form of 't ', 'th ', and 'the '  meaning strings in the form:  starting without any space, string itself and ending with space give index out of range error when trying to run. However, the above solution still passes all existing test cases and the submission is accepted. So these kinds of test cases need to be added to ensure the correctness of the code.

### Screenshots

<img width="906" alt="Снимок экрана 2024-02-04 в 12 45 06" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/41929207/28cbd76f-7766-4b6c-a318-e5aad4b8a5e3">
<img width="906" alt="Снимок экрана 2024-02-04 в 12 45 16" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/41929207/55d25539-4f01-42ff-998d-d36e36ddfad6">
<img width="906" alt="Снимок экрана 2024-02-04 в 12 45 33" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/41929207/9bbf9847-10d9-4f17-946b-448b348d2872">
<img width="1680" alt="Снимок экрана 2024-02-04 в 12 45 45" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/41929207/65a9aadb-e29a-41ec-b6e6-ef574b56fe69">

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
