### ISSUE TITLE
Missing Test Case - 27. Remove Element

### ISSUE THREAD

**Issue by Tusharsolanki33** [LeetCode-Feedback/LeetCode-Feedback#20006]
LeetCode Username
Tusharsolanki33

### Problem number, title, and link
Problem number : 27
Title : Remove Element
link : https://leetcode.com/problems/remove-element/

### Category of the bug

- [ ] Solved examples

### Language used for code
 C++ 

### Code used for Submit/Run operation
```
class Solution {
public:
    int removeElement(vector<int>& nums, int val) {
        int n = nums.size();
        int count = 0;
        for(int i=0;i<n;i++){
            if(nums[i]!=val){
                nums[count] = nums[i];
                count++;
            }
        }
        return count;
    }
};
```

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

Details regarding the missing test case.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team
