### ISSUE TITLE
Incorrect Test Case - 71. Simplify Path 

### ISSUE THREAD

**Issue by seanross113** [LeetCode-Feedback/LeetCode-Feedback#20000]
### LeetCode Username
sean4prez

### Problem number, title, and link
[71. Simplify Path](https://leetcode.com/problems/simplify-path/description/?source=submission-noac)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [X] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
Test case 246/259 for 71. Simplify Path is incorrect. The input path is "/..hidden" and the test case says the expected output should be "/..hidden" when it should really be "/hidden".

<img width="448" alt="Screenshot 2024-02-03 131308" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/147115568/8be148d2-63e4-4505-9f85-8b5e21afb19d">

### Language used for code
C++

### Code used for Submit/Run operation

```
class Solution {
public:
    string simplifyPath(string path) {
        if (path.length() == 1) {
            return path;
        }
        string output = "/";
        for (int i = 1; i < path.length(); i++) {
            if (path[i] == '/' && output.back() == '/') {
                continue;
            }
            else if (i < path.length() - 2 && 
            path[i] == '.' && 
            path[i + 1] ==  '.' &&
            path[i + 2] == '.') {
                while (path[i] != '/' && i < path.length()) {
                    output.push_back(path[i++]);
                }
            }
            else if (i < path.length() - 1 && 
            path[i] == '.' && 
            path[i + 1] ==  '.') {
                if (output.length() == 1) {
                    continue;
                }
                else {
                    output.pop_back();
                    while (output.back() != '/') {
                        output.pop_back();
                    }
                    i++;
                }
            }
            else if (path[i] == '.') {
                continue;
            }
            else {
                output.push_back(path[i]);
            }
        }
        if (output.length() > 1 && output.back() == '/') {
            output.pop_back();
        }
        return output;
    }
};
```

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team

**Comment by seanross113** [comment]
Hello,

Thanks for looking at my issue.

I am still confused as to why this test case is correct. The instructions
state that if two .. occur, that the path should go up a directory. How can
the correct output contain two .. in that case?

Thanks in advance for your help.

Best,
Sean

**Comment by seanross113** [comment]
Nevermind. I can see now that it is meant to be a part of the name of the
directory.
