### ISSUE TITLE
Missing Test Case - 1169. Invalid Transactions

### ISSUE THREAD

**Issue by DanyloGitylo** [LeetCode-Feedback/LeetCode-Feedback#2000]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
I think an additional test case is needed before #25. It is too big to quickly debug and find out a problem in the algorithm in this case:
1. We grouped transactions by name and ordered them by time. 
2. Then we check the time requirement only by adjacent pairs, meaning ``i vs i+1``, ``i+1 vs i+2``, ``i+2 vs i+3``, and so on, and not the whole range, meaning ``i vs i+1 / i+2 / i+3`` and so on.

#### Code you used for Submit/Run operation

```
public class Solution {
  public IList<string> InvalidTransactions(string[] ts) {
    var tsp = ts.Select(x => x.Split(","))
      .Select(x => (x[0], int.Parse(x[1]), int.Parse(x[2]), x[3]))
      .GroupBy(x => x.Item1)
      .ToDictionary(x => x.Key, y => y.OrderBy(z => z.Item2).ToArray());
    var r = new HashSet<string>(
      tsp.Values
        .SelectMany(x => x)
        .Where(x => x.Item3 > 1000)
        .Select(x => $"{x.Item1},{x.Item2},{x.Item3},{x.Item4}"));
    foreach(var tk in tsp.Keys)
    {
      var tst = tsp[tk];
      for (int i = 0; i < tst.Length - 1; i++)
      {
        if (tst[i + 1].Item2 - tst[i].Item2 <= 60 && 
            tst[i + 1].Item4 != tst[i].Item4)
        {
          r.Add($"{tst[i + 1].Item1},{tst[i + 1].Item2},{tst[i + 1].Item3},{tst[i + 1].Item4}");
          r.Add($"{tst[i].Item1},{tst[i].Item2},{tst[i].Item3},{tst[i].Item4}");
        }
      }
    }
    
    return r.ToArray();
  }
}
```

#### Language used for code
C#

#### Expected behavior
I think this test case will make sense if placed before #25:
["alice,20,800,mtv","alice,50,100,mtv","alice,51,100,frankfurt"]

It will fail for the abovementioned code since the first item isn't checked against the last one, which should be added to the result set as well.

I hope this makes sense.

**Comment by lc-kay** [comment]
@DanyloGitylo The code you provided already receives a Wrong Answer. For this to qualify for rewards, please provide an accepted code that this test case fails on. 
<img width="720" alt="Screen Shot 2021-01-14 at 10 30 03 AM" src="https://user-images.githubusercontent.com/70870126/104633206-aecee100-5653-11eb-828d-4c586deeae60.png">

**Comment by DanyloGitylo** [comment]
The main point here was that it fails with a **big** test case - #25, which is **hard to debug**.
The proposed test case is **much smaller** but still reveals the described problem and is **much easier to understand**.
I'm not pretending for any sort of reward - I just wanted to make life easier for other leetcoders who might make the same mistake in their code.

**Comment by lc-kay** [comment]
@DanyloGitylo Thank you for the follow-up and explanation. I've relayed this to our team to investigate.

**Comment by lc-kay** [comment]
Hi @DanyloGitylo 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
