### ISSUE TITLE
输出和输入一致判定为错

### ISSUE THREAD

**Issue by ChinaHuangHai** [LeetCode-Feedback/LeetCode-Feedback#20013]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

### LeetCode 用户名

Dreamy McleanVQj 
### Bug 类型
- [ ] 问题描述
- [ ] 示例
- [ ] 问题限制
- [ ] 问题提示
- [ ] 不正确或缺少“相关标签”
- [ √] 不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*
- [ ] 缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*
- [ ] 力扣官方题解
- [ ] 编程语言支持

### 你提交或者运行的代码

``` 
select
 ifnull(max(num),'null') num
from (
 select num
  from MyNumbers
  group by num
  having count(*)=1
  )t1
```

### 期望行为

输出与结果一致判定错误，望纠正

### 屏幕截图

![企业微信截图_17070363207887](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/158807465/339f9f6b-b39b-4c5c-ad8e-d51a9b9f5ad8)

**Comment by amcones-lc** [comment]
感谢反馈，能否向我们补充题目信息，以及完善代码格式，把信息提供完整才能有助于快速验证和精准的定位，谢谢。
