### ISSUE TITLE
Given solution is not accepted - 452. Minimum Number of Arrows to Burst Balloons

### ISSUE THREAD

**Issue by njha-collab** [LeetCode-Feedback/LeetCode-Feedback#2001]
#### Your LeetCode username

narendra_jha

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Java code given in solution fails for following test case. Not sure about C++ and Python code.

Test case: [[-2147483646,-2147483645],[2147483646,2147483647]]

#### Code you used for Submit/Run operation

```
class Solution {
  public int findMinArrowShots(int[][] points) {
    if (points.length == 0) return 0;

    // sort by x_end
    Arrays.sort(points, new Comparator<int[]>() {
      @Override
      public int compare(int[] o1, int[] o2) {
        return o1[1] - o2[1];
      }
    });

    int arrows = 1;
    int xStart, xEnd, firstEnd = points[0][1];
    for (int[] p : points) {
      xStart = p[0];
      xEnd = p[1];
      // if the current balloon starts after the end of another one,
      // one needs one more arrow
      if (firstEnd < xStart) {
        arrows++;
        firstEnd = xEnd;
      }
    }

    return arrows;
  }
}
```

#### Language used for code

Java

#### Expected behavior

Java code in solution needs to pass for all test cases.

FIX:
```
return o1[1] - o2[1];
```
To fix this, change above line in comparator to following.

```
return Integer.compare(o1[1], o2[1]);
```

**Comment by lc-kay** [comment]
@njha-collab 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @njha-collab 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!

**Comment by njha-collab** [comment]
Thanks for the detailed response. Happy to help!
