### ISSUE TITLE
不正确的测试用例 - 1838. 最高频元素的频数

### ISSUE THREAD

**Issue by Webster314** [LeetCode-Feedback/LeetCode-Feedback#20016]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

### LeetCode 用户名
[nash00r](https://leetcode.cn/u/shar2k)
### 问题号码、标题和链接
1838. 最高频元素的频数 https://leetcode.cn/problems/frequency-of-the-most-frequent-element/description/

### Bug 类型
- [x] 不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*

### 描述
nums=[40,95,44,37,41,52,07,52,87,64,40,14,41,33,12,34,80,07,80,44,10,9]
k=7925
这个测试用例疑似出了问题，数组元素07改成7是可以通过的。

### 你使用的语言
C++

### 你提交或者运行的代码
```
class Solution {
public:
    int maxFrequency(vector<int>& nums, int k) {
        const int N = nums.size();
        int ans = 1;
        int left = 0;
        int right = 0;
        unsigned long window = 0;
        sort(nums.begin(), nums.end());
        deque<int> q;
        while(right < N){
            int in = nums[right++];
            window += in;
            while(!q.empty() && q.back() < in){
                q.pop_back();
            }
            q.push_back(in);
            while(k + window < ((unsigned long)(right-left) * q.front())){
                int out = nums[left++];
                window -= out;
                if(out == q.front()){
                    q.pop_front();
                }
            }
            ans = max(ans, right - left);
        }
        return ans;
    }
};
```
### 期望行为

希望将测试用例[40,95,44,37,41,52,07,52,87,64,40,14,41,33,12,34,80,07,80,44,10,9], k=7925
修改为[40,95,44,37,41,52,7,52,87,64,40,14,41,33,12,34,80,7,80,44,10,9], k=7925
(也就是将nums数组的两个07改为7)

### 屏幕截图

![2024-02-04 (2)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/77682362/b77e63a2-1e7e-473e-8986-17b1947bebac)

## 修改为[40,95,44,37,41,52,7,52,87,64,40,14,41,33,12,34,80,7,80,44,10,9], k=7925后通过

![2024-02-05](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/77682362/52b3351a-a706-44f6-b9a0-af0c2e263a94)

## 试了用官方题解的code，这个case也会报同样的错误

![2024-02-05 (2)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/77682362/efa86dc4-3507-4374-8e70-048b8e200f65)
![2024-02-05 (1)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/77682362/32ac2e38-ef0f-44f3-a681-fd76f02cf38a)

### 额外的上下文
报错信息Line 1634: SizeType rapidjson::GenericValue<rapidjson::UTF8<>>::Size() const [Encoding = rapidjson::UTF8<>, Allocator = rapidjson::MemoryPoolAllocator<>]: Assertion `IsArray()' failed. (document.h)

**Comment by amcones-lc** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by Webster314** [comment]
> 你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

我的个性域名是 leetcode.cn/u/shar2k/

**Comment by Webster314** [comment]
> 你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

我的个性域名是 leetcode.cn/u/shar2k/
