### ISSUE TITLE
Missing Test Case - 917. Boats to Save People

### ISSUE THREAD

**Issue by Shahryar-sss** [LeetCode-Feedback/LeetCode-Feedback#2002]
#### Your LeetCode username

Shahryar-sss

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

The following test case:
**[1,1,1]
100**
should have 1 as the answer, since the sum of the weight of the 3 people is much less than the limit of 100.

But, as shown in the screenshot below, the expected answer is given as 2.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int numRescueBoats(vector<int>& people, int limit) {
        
        int numBoats = 0;
        
        sort(people.begin(), people.end(), greater<int>());
        
        for (int i=0; i<people.size();) {
            int sum = 0;
            int k = i;
            
            while (sum <=limit && k<people.size()) {
                sum += people[k];
                k++;
            }
            
            numBoats++;
            cout << i << " " << k-1  << endl;
            if (k==people.size()) break;
            i=k-1;
        }
        
        return numBoats;
    }
};
```

#### Language used for code
C++

#### Expected behavior

The following test case:
**[1,1,1]
100**
should have 1 as the answer, since the sum of the weight of the 3 people is much less than the limit of 100.

But, as shown in the screenshot above, the expected answer is given as 2.

#### Screenshots

![image](https://user-images.githubusercontent.com/36510102/104542028-c81e6000-5648-11eb-85a4-cb8c97ae064f.png)

**Comment by lc-kay** [comment]
@Shahryar-sss The problem statement says that "Each boat carries at most 2 people at the same time" therefore, 2 boats are required for 3 people. Thank you for your time.
