### ISSUE TITLE
Missed returned value in description - 64. Minimum Path Sum

### ISSUE THREAD

**Issue by andennis** [LeetCode-Feedback/LeetCode-Feedback#20024]
### LeetCode Username
andennis

### Problem number, title, and link
64. Minimum Path Sum https://leetcode.com/problems/minimum-path-sum/description/

### Category of the bug
- [x] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
The returned value is not clearly specified in the description.   
```
...find a path from top left to bottom right, which minimizes the sum of all numbers along its path.
```
It looks like the description requires to return a path i.e. an array). Only examples clarify that a sum of numbers must be returned.

### Expected behavior
It might be clearer to have something like e.g.:

"Given a `m x n` grid filled with non-negative numbers, find a path from top left to bottom right, which minimizes the sum of all numbers along its path. **Return the minimized sum**"

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback. We encourage you to share your questions in the discussion forum, where the community can provide insights and assistance.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
