### ISSUE TITLE
Wrong Expected - 1668. Maximum Repeating Substring

### ISSUE THREAD

**Issue by ChelseaLiao** [LeetCode-Feedback/LeetCode-Feedback#20025]
### LeetCode Username

chelsealrl

### Problem number, title, and link

1. Maximum Repeating Substring https://leetcode.com/problems/maximum-repeating-substring/description/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [√] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The expected answer of a test case with sequence = "aaabaaaabaaabaaaabaaaabaaaabaaaaba" and word = "aaaba" is 5 but actually 6 is the correct answer.

### Language used for code

C#

### Code used for Submit/Run operation

```
using System.Text.RegularExpressions;
public class Solution {
    public int MaxRepeating(string sequence, string word) {
        return Regex.Matches(sequence, word).Count;
    }
}

```

### Expected behavior

Expected should be 6.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/92916469/fe94a8f4-6acf-417a-9264-9a0f24218e4d)

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
