### ISSUE TITLE
Missing Test Case - 1772. Create Sorted Array through Instructions

### ISSUE THREAD

**Issue by scmaverick** [LeetCode-Feedback/LeetCode-Feedback#2004]
#### Your LeetCode username
scmaverick

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
58/65 test cases passed, and my code is rejected, however the expected result for this test case may be wrong as provided by the website.

#### Code you used for Submit/Run operation

```
var createSortedArray = function(instructions) {
    let nums = [instructions[0]]
    let cost = 0;
    let same = 0;
    let j = 0;
    let min1 = 0;
    let min2 = 0;
    for (let i = 1; i < instructions.length; i++) {
        same = 0;
        for (j = 0; j < nums.length; j++) {
            if (nums[j] > instructions[i]) {
                break;
            }
            if (nums[j] == instructions[i]) {
                same++;
            }
        }
        min1 = j - same;
        min2 = nums.length - j;
        nums.splice(j, 0, instructions[i]);
        cost += (min1 < min2) ? min1 : min2;
    }
    return cost;   
};
```

#### Language used for code
Javascript

#### Expected behavior

The test set is just a very large array with numbers. If I take just some elements of the test array provided, say 10%, the results match the expected output, if I take around 30% of the array it matches, If I take half of the array the results match, as matter of fact by increasing the size of the array the cost result is only expected to be a larger number as well.
However, by taking at about 3/4 of the test array the results no longer match and the expected output provided by the website actually decreases compared to the previous runs with smaller portions of the array, which I find odd, there has to be something wrong or I just can't find my bug at all. 

#### Screenshots

Success with a small portion of the array:
![imagen](https://user-images.githubusercontent.com/9893119/104558555-9ab1c200-5608-11eb-81e7-c118aeed9475.png)
Success with a larger portion of the array, the cost result increases as expected:
![imagen](https://user-images.githubusercontent.com/9893119/104558680-cb91f700-5608-11eb-85bd-9f484eb32583.png)
With about half the array the result is still a match with an even larger cost as expected:
![imagen](https://user-images.githubusercontent.com/9893119/104558765-f2e8c400-5608-11eb-84cf-7db30618731a.png)
But by taking about 3/4 of the test array the results no longer match and in fact the expected result from the website actually decreases:
![imagen](https://user-images.githubusercontent.com/9893119/104558916-393e2300-5609-11eb-8a3c-087ff3dd7dc8.png)
The overall test case fails with a smaller expected cost even than if using only half of the elements in the array, I'm I missing something?
![imagen](https://user-images.githubusercontent.com/9893119/104559023-61c61d00-5609-11eb-88a2-f9f2f392b702.png)

#### Additional context

As commented, if you just keep adding values to the same array and run the tests the final cost is only expected to increase, not the contrary, this is the premise I'm using to understand this bug.
Appreciate it.

**Comment by Leader-board** [comment]
It's 1649, not 1772?

Also, the question says that the result should be modulo 10<sup>9</sup> + 7:

> Return the total cost to insert all elements from instructions into nums. Since the answer may be large, return it modulo 10^9 + 7

It does not appear that you are doing it from your code.

**Comment by lc-kay** [comment]
@scmaverick The expected answer is correct. I'd recommend checking out the solution article or discuss tab for this problem to explanations. In addition, you can raise this question in the discuss tab to receive responses from other users. Thank you for your time.
