### ISSUE TITLE
Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### ISSUE THREAD

**Issue by Jayantkumar56** [LeetCode-Feedback/LeetCode-Feedback#20049]
### LeetCode Username
jayant_kumar10

### Problem number, title, and link
387. First Unique Character in a String  https://leetcode.com/problems/first-unique-character-in-a-string/ 

### Category of the bug

 [***]  Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Language used for code
C++ 

### Code used for Submit/Run operation

```
class Solution {
public:
    int firstUniqChar(string s) {
        uint16_t ma[26] = {0};
        int ans = -1;

        for( auto i : s ){
            ma[i - 'a']++;
        }

        for(int i=0; i<s.length(); i++){
            if( ma[ s[i] - 'a' ] == 1 )
                return i;
        }

        return ans;
    }
};
```

### Expected behavior
The solution should not be accepted since it fails on a test case.

### Screenshots

![Screenshot_20240205_112818](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/137918124/df66c260-df8b-4788-92e9-abc850a7dcec)

the testcase i used is 65537 times a as a string

![Screenshot_20240205_112710](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/137918124/a96c85cd-627c-4835-9f2a-4ac0d05e0a16)

### Additional context
here in this code i used array of uint16_t as a map. The range of uint16_t is 65535.  in this testcase the code will fill only the 0th index element of out map. since a is mapped to 0. while iterating in the first loop when we reach 65536th a in the string and we increase ma[0] now ma[0] becomes 0, since we are getting out of range of uint16_t. now when we reach 65537th a in the string ma[0] becomes 1 which means there's only 1 a in the string whereas  it's not.

File containing testcase :- 
[testcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/14161638/testcase.txt)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
