### ISSUE TITLE
样例错误 560 subarray-sum-equals-k

### ISSUE THREAD

**Issue by Dempsey1201** [LeetCode-Feedback/LeetCode-Feedback#20045]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

### Bug 类型
- [ ] 问题描述
- [ ] 示例
- [ ] 问题限制
- [ ] 问题提示
- [ ] 不正确或缺少“相关标签”
- [ *] 不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*
- [ ] 缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*
- [ ] 力扣官方题解
- [ ] 编程语言支持

### 描述

测试样例 [1, -1, 0], k = 0 的子数组只有 [1, -1], [0] 两个，为什么答案是3？

### 你提交或者运行的代码

```
// 将您的代码粘贴到此处
```

**Comment by stormsunshine** [comment]
整个数组也是一个元素和为 0 的子数组，子数组可以是原数组本身。

**Comment by amcones-lc** [comment]
感谢反馈，经核实该题目题解及测试用例暂无异常，力扣会不断努力给大家带来更好的学习社区！后续刷题学习中遇到问题，可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
