### ISSUE TITLE
Incorrect Test Case - 1528. Shuffle String

### ISSUE THREAD

**Issue by aasthaa012** [LeetCode-Feedback/LeetCode-Feedback#20046]
### LeetCode Username

_aasthaa_gupta24

### Problem number, title, and link

1528. Shuffle String https://leetcode.com/problems/shuffle-string/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Test case 59 is showing wrong output according to the given input.

### Language used for code

Java

### Code used for Submit/Run operation

```
class Solution {
    public String restoreString(String s, int[] ind) {
        String ans = "";
        int l = s.length();
        for (int i = 0; i < l; i++) {
            int n = ind[i];
            ans = ans.concat(s.substring(n, n + 1));
        }
        return ans;
    }
}
```

### Expected behavior

Input: s = "codeleet", indices = [4,5,6,7,0,2,1,3]
Output: "leetcode"
Here the output should be "leetcdoe".

### Screenshots

![Screenshot (58)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/156993879/9652164a-3fe2-4459-ab42-ece8dd89b0e4)

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
