### ISSUE TITLE
Wrong Test Case - 1002. Find Common Characters

### ISSUE THREAD

**Issue by Oden333** [LeetCode-Feedback/LeetCode-Feedback#20054]
### Category of the bug
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### Description of the bug
It seems like wrong expected answer in this testcase
Input words = ["acabcddd","bcbdbcbd","baddbadb","cbdddcac","aacbcccd","ccccddda","cababaab","addcaccd"]
Output = ["d","d","a","c","c","b"]
Expected = []

### Code used for Submit/Run operation

```
func commonChars(words []string) []string {
	c := words[0]
	for i := 0; i < len(words); i++ {
		if len(words[i]) < len(c) {
			c = words[i]
		}
	}
	var curByte byte
	var curWord string
	byteMap := make(map[byte]int, len(c))
	for i := 0; i < len(c); i++ {
		curByte = c[i]
		if _, ok := byteMap[curByte]; !ok {
			byteMap[curByte] = 0
		} else {
			continue
		}
		for n := 0; n < len(words); n++ {
			curWord = words[n]
			for l := 0; l < len(curWord); l++ {
				if curWord[l] == curByte {
					byteMap[curByte]++
				}
			}
		}

	}
	var counter int
	commonChars := []string{}
	for key, value := range byteMap {
		counter = int(value / len(words))
		for i := 0; i < counter; i++ {
			commonChars = append(commonChars, string(key))
		}
	}
	return commonChars
}
```

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
