### ISSUE TITLE
Missing descriptions in the 1696 official solutions

### ISSUE THREAD

**Issue by Sensente** [LeetCode-Feedback/LeetCode-Feedback#20051]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

### LeetCode 用户名
Sensente

### Bug 类型
- [ ] 问题描述
- [ ] 示例
- [ ] 问题限制
- [ ] 问题提示
- [ ] 不正确或缺少“相关标签”
- [ ] 不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*
- [ ] 缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*
- [x] 力扣官方题解
- [ ] 编程语言支持

### 描述

Missing descriptions in the state-transition equation:
$dp[i] = max(dp[j]),$
is missing a term, which should be:
$dp[i] = max(dp[j]) + nums[i]$

### 你提交或者运行的代码

```
// NULL.
```

### 期望行为

Fix the equation.

### 屏幕截图

<img width="735" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/35966153/77e3e40c-ff3e-45df-90cc-518d4248c489">

### 额外的上下文

NULL.

**Comment by amcones-lc** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by Sensente** [comment]
> 你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

URL: https://leetcode.cn/u/sensente/

Thanks.

**Comment by Sensente** [comment]
> 你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

URL: https://leetcode.cn/u/sensente/

Thanks.
