### ISSUE TITLE
Code is still accepted, even though condition is given 

### ISSUE THREAD

**Issue by AnmolSingh173** [LeetCode-Feedback/LeetCode-Feedback#20058]
### LeetCode Username

Anm0l_Preet_Singh

### Problem number, title, and link

415.  Add Strings https://leetcode.com/problems/add-strings/

### Category of the bug
- [ ] Problem constraints
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### Description of the bug

The problem asks not to convert the given strings into integer and perform addition. But on implementing that in code  , the test cases pass and the solution is accepted even though it wasn't supposed to be as per the given condition.  
### Language used for code

Python
### Code used for Submit/Run operation

```
class Solution(object):
    def addStrings(self, num1, num2):
        return str(int(num1)+int(num2))
```

### Expected behavior

An error is expected when running the code, because one of the constraints got violated. 

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/120032068/a4ca0b48-fdba-4a3b-b007-01db79eeed4c)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

This is an educational site. Please respect the limitations of the question.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
