### ISSUE TITLE
Description Title Error: 3024. Type of Triangle II  

### ISSUE THREAD

**Issue by ViratJinjala** [LeetCode-Feedback/LeetCode-Feedback#20053]
### LeetCode Username
virat_jinjala

### Problem number, title, and link
3024. Type of Triangle II   https://leetcode.com/problems/type-of-triangle-ii/description/

### Category of the bug
- [ ] Problem description

### Description of the bug

There's no "Type of Triangle I"  problem on leetcode while this question named "Type of Triangle II".
Kindly change it.

### Expected behavior
change name from "Type of Triangle II" to "Type of Triangle I"

### Screenshots

![Screenshot 2024-02-05 164839](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/155998278/a684bd7b-61b4-45db-a68c-f11a25efaeae)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

There is a problem named “Type of Triangle”.
If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
