### ISSUE TITLE
Missing Test Case - 387. First Unique Character in a String

### ISSUE THREAD

**Issue by poddubitskya** [LeetCode-Feedback/LeetCode-Feedback#20060]
### LeetCode Username
apadd

### Problem number, title, and link
387. First Unique Character in a String https://leetcode.com/problems/first-unique-character-in-a-string/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
The code below was accepted for submission

But I can make it fail with a custom test case. A string of 99999 'a' characters and a single 'b' at the end

The constant NonUniqueMarkerValue is used to mark characters that are not unique and shouldn't be counted. 

After the loop the lowest value in the array will be the NonUniqueMarkerValue. The marker value is "obscuring" the real answer which is > NonUniqueMarkerValue, 99999 for the mentioned custom testcase.

### Language used for code
C#

### Code used for Submit/Run operation
```
public class Solution {

    private const int NonUniqueMarkerValue = 16_384;

    public int FirstUniqChar(string s) {
        Console.WriteLine(s.Length);
        int[] firsts = Enumerable.Repeat(-1, 26).ToArray();

        for(int i = 0; i < s.Length; i++) {
            int letterCode = s[i] - 'a';
            
            if(firsts[letterCode] != -1) firsts[letterCode] = NonUniqueMarkerValue; 
            else firsts[letterCode] = i;
        }

        int result = firsts.Where(i => i != -1).Min();
        return result != NonUniqueMarkerValue ? result : -1;
    }
}
```

### Expected behavior
It should fail with marker values <= 100000 (10<sup>5</sup>), the max string length constraint). But it passes

### Screenshots
--

### Additional context
--

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
