### ISSUE TITLE
Missing Test Case - 1658. Minimum Operations to Reduce X to Zero

### ISSUE THREAD

**Issue by rishabhsairawat** [LeetCode-Feedback/LeetCode-Feedback#2006]
#### Your LeetCode username
rishabhsairawat

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

input
[5,1,4,2,3]
6
My code fails, but all your tests pass.

#### Code you used for Submit/Run operation

```
class Solution {
    public int minOperations(int[] nums, int x) {
        HashMap<Integer, Integer> map = new HashMap();
        int sum = 0;
        for(int i = 0; i < nums.length; i++) {
            sum += nums[i];
            map.put(sum, i + 1);
        }
        if(sum < x) return -1;
        if(nums[0] == x) return 1;

        int i = nums.length - 1;
        int min = Integer.MAX_VALUE;
        int sumFromBack = 0;
        while(i >= 0) {
            sumFromBack += nums[i];
            if(sumFromBack == x) {
                min = Math.min(min, nums.length - i);
            } else if(map.containsKey(x - sumFromBack)) {
                min = Math.min(min, nums.length - i + map.get(x - sumFromBack));
            }
            i--;
        }
        
        return min == Integer.MAX_VALUE ? -1 : min;
    }
}
```

#### Language used for code

Java

#### Expected behavior

This test case should be there to reject my submission. 

#### Screenshots

![image](https://user-images.githubusercontent.com/26122851/104580725-9ecef580-5683-11eb-8cb0-fe688ddab980.png)

**Comment by lc-kay** [comment]
Hi @rishabhsairawat 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @rishabhsairawat 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
