### ISSUE TITLE
Missing Test Case - 3031. Minimum Time to Revert Word to Initial State II

### ISSUE THREAD

**Issue by prokaj** [LeetCode-Feedback/LeetCode-Feedback#20074]
### LeetCode Username

vilmos_prokaj

### Problem number, title, and link
 3031. Minimum Time to Revert Word to Initial State II https://leetcode.com/problems/minimum-time-to-revert-word-to-initial-state-ii/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

O(n^2) solution is ok.
According to the problem statement the length of the input string `s` can be as large as 1e6.
Any test case of the form (python notation):
```python
n = 500_000-1
s = "a"*n+"b"+"a"*n
k = 1
```
or
```python
n = 200_000
s = "ab"*n+"c"+"ab"*n
k = 2
```
where `n` is large enough invalidates `O(n^2)` solutions.

### Language used for code
Python

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
