### ISSUE TITLE
LCP30测试用例出错

### ISSUE THREAD

**Issue by bxiaoshishang** [LeetCode-Feedback/LeetCode-Feedback#20072]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

### LeetCode 用户名

b小时尚
https://leetcode.cn/u/bxiao-shi-shang/

### 问题号码、标题和链接

LCP30.魔塔游戏 https://leetcode.cn/problems/p0NxJO/description/

### Bug 类型
- [√ ] 不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*

### 描述

输入[-1]根据题意应当是生命值为0，不满足应当返回-1，但预期结果是1，此处错误。

### 你使用的语言

C++

### 你提交或者运行的代码

```
class Solution {
public:
    int magicTower(vector<int>& nums) {
        int res = 0;
        long long sum = 1;
        long long suf = 0;
        map<int, int> dights;
        for (int i=0;i < nums.size();++i) {
            sum += nums[i];
            if (nums[i] < 0)
                dights[nums[i]]++;
            if (sum <= 0) {
                res++;
                int temp = dights.begin()->first;
                suf += temp;
                sum -= temp;
                dights[temp]--;
                if (!dights[temp])
                    dights.erase(temp);
            }
        }
        return sum + suf > 0 ? res : -1;
    }
}; 
```

### 期望行为

返回-1

### 屏幕截图

<img width="254" alt="1707186680973" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/97823104/463579ab-f10e-4908-b35d-7658acbd92e6">

**Comment by amcones-lc** [comment]
感谢反馈，经核实该题目题解及测试用例暂无异常，力扣会不断努力给大家带来更好的学习社区！后续刷题学习中遇到问题，可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
