### ISSUE TITLE
1717 题目描述改进建议

### ISSUE THREAD

**Issue by cncsl** [LeetCode-Feedback/LeetCode-Feedback#2007]
**Bug 类型**
- [ ] 题目：题干描述不清晰

**描述**
这道题目的描述信息不清晰
![image](https://user-images.githubusercontent.com/32363528/104585552-21b17980-569f-11eb-8616-3f37a2fa1969.png)

**Comment by feiceh** [comment]
感谢反馈，已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，本题题面目前与英文一致。1. 这里是对删除操作的示例，计分规则已经在前一行表述了，所以没有补充。2. 建议结合题目给出的示例和解释配合阅读，那也是题面的一部分。
