### ISSUE TITLE
6. Zigzag Conversion

### ISSUE THREAD

**Issue by karoldem** [LeetCode-Feedback/LeetCode-Feedback#20071]
### Problem number, title, and link
[6. Zigzag Conversion](https://leetcode.com/problems/zigzag-conversion/)

### Category of the bug

- [ X ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ X ] Programming language support

### Description of the bug
testcase s = "PAYPALISHIRING", numRows = 3 prints 
0
4
8
12
0
6
12
and 20946506 of zeros

and timeouts

### Language used for code
Python 3

### Code used for Submit/Run operation
```
class Solution:
    def convert(self, s: str, numRows: int) -> str:
        n = numRows - 1

        i = 0
        while(True):

            if (2*n*i < len(s)): print(2*n*i)
            else: break
            i = i+1

        return ("dsafgqe")
```

### Expected behavior

should print
0
8
and return
"dsafgqe"

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
