### ISSUE TITLE
LCP 30. 魔塔游戏 判题程序有误

### ISSUE THREAD

**Issue by EndlessCheng** [LeetCode-Feedback/LeetCode-Feedback#20070]
### LeetCode 用户名
endlesscheng

### 问题号码、标题和链接
[LCP 30. 魔塔游戏](https://leetcode.cn/problems/p0NxJO/)

### Bug 类型
- [ ] 问题描述
- [ ] 示例
- [ ] 问题限制
- [ ] 问题提示
- [ ] 不正确或缺少“相关标签”
- [ ] 不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*
- [ ] 缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*
- [ ] 力扣官方题解
- [ ] 编程语言支持
- [x] 其它：判题程序有 bug

### 描述
`[-1]` 这个数据，按照题目描述，应该输出 `-1`，但是「预期结果」却是 `1`。这说明判题程序（出题人的代码）是错的。

### 你使用的语言
Python3

### 你提交或者运行的代码

```py
class Solution:
    def magicTower(self, nums: List[int]) -> int:
        if sum(nums) < 0:
            return -1
        ans = 0
        hp = 1
        h = []
        for x in nums:
            if x < 0:
                heappush(h, x)
            hp += x
            if hp < 1:
                hp -= heappop(h)
                ans += 1
        return ans
```

### 期望行为

请修改判题程序（出题人的代码），使得输入为 `[-1]` 时，输出为 `-1`。

**Comment by suqingfa** [comment]
+1

**Comment by EndlessCheng** [comment]
已经修好了，官方速度还挺快的。
