### ISSUE TITLE
Missing Test Case - 1610. Maximum Number of Visible Points

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#2008]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [√] Solution
- [ ] Language

#### Description of the bug

An accepted solution for 1610. Maximum Number of Visible Points is incorrect. It fails on the following testcase:
[[1000000000,0],[1000000000,1],[1000000000,2],[1000000000,3],[1000000000,4],[1000000000,5],[1000000000,6],[1000000000,7],[1000000000,8],[1000000000,9],[999999999,0],[999999999,1],[999999999,2],[999999999,3],[999999999,4],[999999999,5],[999999999,6],[999999999,7],[999999999,8],[999999999,9],[999999998,0],[999999998,1],[999999998,2],[999999998,3],[999999998,4],[999999998,5],[999999998,6],[999999998,7],[999999998,8],[999999998,9],[999999997,0],[999999997,1],[999999997,2],[999999997,3],[999999997,4],[999999997,5],[999999997,6],[999999997,7],[999999997,8],[999999997,9],[999999996,0],[999999996,1],[999999996,2],[999999996,3],[999999996,4],[999999996,5],[999999996,6],[999999996,7],[999999996,8],[999999996,9],[999999995,0],[999999995,1],[999999995,2],[999999995,3],[999999995,4],[999999995,5],[999999995,6],[999999995,7],[999999995,8],[999999995,9],[999999994,0],[999999994,1],[999999994,2],[999999994,3],[999999994,4],[999999994,5],[999999994,6],[999999994,7],[999999994,8],[999999994,9],[999999993,0],[999999993,1],[999999993,2],[999999993,3],[999999993,4],[999999993,5],[999999993,6],[999999993,7],[999999993,8],[999999993,9],[999999992,0],[999999992,1],[999999992,2],[999999992,3],[999999992,4],[999999992,5],[999999992,6],[999999992,7],[999999992,8],[999999992,9],[999999991,0],[999999991,1],[999999991,2],[999999991,3],[999999991,4],[999999991,5],[999999991,6],[999999991,7],[999999991,8],[999999991,9],[1000000000,1000000000],[1000000000,999999999],[1000000000,999999998],[1000000000,999999997],[1000000000,999999996],[1000000000,999999995],[1000000000,999999994],[1000000000,999999993],[1000000000,999999992],[1000000000,999999991],[999999999,1000000000],[999999999,999999999],[999999999,999999998],[999999999,999999997],[999999999,999999996],[999999999,999999995],[999999999,999999994],[999999999,999999993],[999999999,999999992],[999999999,999999991],[999999998,1000000000],[999999998,999999999],[999999998,999999998],[999999998,999999997],[999999998,999999996],[999999998,999999995],[999999998,999999994],[999999998,999999993],[999999998,999999992],[999999998,999999991],[999999997,1000000000],[999999997,999999999],[999999997,999999998],[999999997,999999997],[999999997,999999996],[999999997,999999995],[999999997,999999994],[999999997,999999993],[999999997,999999992],[999999997,999999991],[999999996,1000000000],[999999996,999999999],[999999996,999999998],[999999996,999999997],[999999996,999999996],[999999996,999999995],[999999996,999999994],[999999996,999999993],[999999996,999999992],[999999996,999999991],[999999995,1000000000],[999999995,999999999],[999999995,999999998],[999999995,999999997],[999999995,999999996],[999999995,999999995],[999999995,999999994],[999999995,999999993],[999999995,999999992],[999999995,999999991],[999999994,1000000000],[999999994,999999999],[999999994,999999998],[999999994,999999997],[999999994,999999996],[999999994,999999995],[999999994,999999994],[999999994,999999993],[999999994,999999992],[999999994,999999991],[999999993,1000000000],[999999993,999999999],[999999993,999999998],[999999993,999999997],[999999993,999999996],[999999993,999999995],[999999993,999999994],[999999993,999999993],[999999993,999999992],[999999993,999999991],[999999992,1000000000],[999999992,999999999],[999999992,999999998],[999999992,999999997],[999999992,999999996],[999999992,999999995],[999999992,999999994],[999999992,999999993],[999999992,999999992],[999999992,999999991],[999999991,1000000000],[999999991,999999999],[999999991,999999998],[999999991,999999997],[999999991,999999996],[999999991,999999995],[999999991,999999994],[999999991,999999993],[999999991,999999992],[999999991,999999991]]
90
[500000000,500000000]

#### Code you used for Submit/Run operation

```
#define PI 3.14159265
#define MARGIN 1e-9

class Solution {
public:
    double get_angle(int x_diff, int y_diff) {
        return atan2(y_diff, x_diff) * 180 / PI;
    }
    int visiblePoints(vector<vector<int>>& points, int angle, vector<int>& location) {
        int i, j, n = points.size(), common = 0;
        vector<double> vals;
        for(i=0; i<n; i++) {
            int x = points[i][0] - location[0];
            int y = points[i][1] - location[1];
            if(x == 0 && y == 0) {
                common++;
            }
            else {
                double A = get_angle(x, y);
                if(A < 0) A += 360;
                vals.emplace_back(A);
            }
        }

        sort(vals.begin(), vals.end());
        vector<double> a = vals;
        a.insert(a.end(), vals.begin(), vals.end());
        for(i=vals.size(); i<a.size(); i++)
            a[i] += 360;
        int ret = 0;
        for(i=0, j=0; i<a.size(); i++) {
            while(j < a.size() && (a[j]-a[i]<=angle + MARGIN))
                  j++;
            ret = max(ret, j - i);
        }
        return ret + common;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Expected output: 110.
The code's incorrect output: 100.

#### Screenshots

![1](https://user-images.githubusercontent.com/11583428/104658144-cde76600-5687-11eb-985c-c11fa7edbca8.png)

#### Additional context

As the post https://leetcode.com/problems/maximum-number-of-visible-points/discuss/877955/constaints-are-too-large by @uwi pointed out, this issue is due to the finite precision of floating-point numbers, and there should be a numerous number of accepted codes that will fail on this testcase.

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @hqztrue
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!

**Comment by hqztrue** [comment]
I see, that change will indeed make the precision issue less problematic. However if one is not careful enough, coordinates as large as 10^5 can still make their algorithm fail. My above code passes the following testcase (generated with the same logic under the new constraint), but the currently fastest accepted code doesn't:
[[100000,0],[100000,1],[100000,2],[100000,3],[100000,4],[100000,5],[100000,6],[100000,7],[100000,8],[100000,9],[99999,0],[99999,1],[99999,2],[99999,3],[99999,4],[99999,5],[99999,6],[99999,7],[99999,8],[99999,9],[99998,0],[99998,1],[99998,2],[99998,3],[99998,4],[99998,5],[99998,6],[99998,7],[99998,8],[99998,9],[99997,0],[99997,1],[99997,2],[99997,3],[99997,4],[99997,5],[99997,6],[99997,7],[99997,8],[99997,9],[99996,0],[99996,1],[99996,2],[99996,3],[99996,4],[99996,5],[99996,6],[99996,7],[99996,8],[99996,9],[99995,0],[99995,1],[99995,2],[99995,3],[99995,4],[99995,5],[99995,6],[99995,7],[99995,8],[99995,9],[99994,0],[99994,1],[99994,2],[99994,3],[99994,4],[99994,5],[99994,6],[99994,7],[99994,8],[99994,9],[99993,0],[99993,1],[99993,2],[99993,3],[99993,4],[99993,5],[99993,6],[99993,7],[99993,8],[99993,9],[99992,0],[99992,1],[99992,2],[99992,3],[99992,4],[99992,5],[99992,6],[99992,7],[99992,8],[99992,9],[99991,0],[99991,1],[99991,2],[99991,3],[99991,4],[99991,5],[99991,6],[99991,7],[99991,8],[99991,9],[100000,100000],[100000,99999],[100000,99998],[100000,99997],[100000,99996],[100000,99995],[100000,99994],[100000,99993],[100000,99992],[100000,99991],[99999,100000],[99999,99999],[99999,99998],[99999,99997],[99999,99996],[99999,99995],[99999,99994],[99999,99993],[99999,99992],[99999,99991],[99998,100000],[99998,99999],[99998,99998],[99998,99997],[99998,99996],[99998,99995],[99998,99994],[99998,99993],[99998,99992],[99998,99991],[99997,100000],[99997,99999],[99997,99998],[99997,99997],[99997,99996],[99997,99995],[99997,99994],[99997,99993],[99997,99992],[99997,99991],[99996,100000],[99996,99999],[99996,99998],[99996,99997],[99996,99996],[99996,99995],[99996,99994],[99996,99993],[99996,99992],[99996,99991],[99995,100000],[99995,99999],[99995,99998],[99995,99997],[99995,99996],[99995,99995],[99995,99994],[99995,99993],[99995,99992],[99995,99991],[99994,100000],[99994,99999],[99994,99998],[99994,99997],[99994,99996],[99994,99995],[99994,99994],[99994,99993],[99994,99992],[99994,99991],[99993,100000],[99993,99999],[99993,99998],[99993,99997],[99993,99996],[99993,99995],[99993,99994],[99993,99993],[99993,99992],[99993,99991],[99992,100000],[99992,99999],[99992,99998],[99992,99997],[99992,99996],[99992,99995],[99992,99994],[99992,99993],[99992,99992],[99992,99991],[99991,100000],[99991,99999],[99991,99998],[99991,99997],[99991,99996],[99991,99995],[99991,99994],[99991,99993],[99991,99992],[99991,99991]]
90
[50000,50000]
![1](https://user-images.githubusercontent.com/11583428/104792835-7c150d80-5765-11eb-971d-2b3079735d47.png)
![2](https://user-images.githubusercontent.com/11583428/104792840-7f0ffe00-5765-11eb-81e6-03eab3341f93.png)

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for the update. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@hqztrue Our team has updated the constraints again to avoid the precision error. Thank you for your time.
