### ISSUE TITLE
Missing Test Case - 881. Boats to Save People

### ISSUE THREAD

**Issue by Superminionsfy** [LeetCode-Feedback/LeetCode-Feedback#2009]
#### Your LeetCode username

Superminions

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

If the limit is smaller than one of the people, we should return an invalid number, like 0 or -1. 
For example:
input:
[3,2,2,1]
2
we should return an invalid number, like 0 or -1. 

#### Code you used for Submit/Run operation

```
// Boats to Save People
class Solution:
    def numRescueBoats(self, people: List[int], limit: int) -> int:
        if not people:
            return 0
        
        people.sort()
        
        if people[-1] > limit:
            return 0
        
        boat = 0
        l = 0
        r = len(people) - 1
        while l < r:
            if people[l] + people[r] <= limit:
                l += 1
            boat += 1
            r -= 1
            if l == r:
                boat += 1
            
        return boat
```

#### Language used for code
Python

**Comment by lc-kay** [comment]
Hi @Superminionsfy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Superminionsfy 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
