### ISSUE TITLE
Missing test case in 189. Rotate Array

### ISSUE THREAD

**Issue by agarwalrounak** [LeetCode-Feedback/LeetCode-Feedback#201]
**What kind of the bug**
- [x] problem

Missing testcase or content issue

**Describe the bug**
My wrong solution was accepted because of a missing testcase. In the question, it is given that the user is given an array and has to perform the required operation. It's nowhere mentioned that the array has to have an element. In case of an empty array, my solution will fail due to "runtime error: division by zero" because I perform a modulus operation in my solution. The user should check if the array is empty and do nothing if the array turns out to be empty. 

**what language is your code written in**
C++

**The code you submit/run**
```
// Rotate Array
class Solution {
public:
    void rotate(vector<int>& nums, int k) {
        int i;
        vector<int> a;
        k=k%nums.size();
        for(i=0;i<nums.size();i++){
          if((i-k)<0)a.push_back(nums[nums.size()+i-k]);
          else a.push_back(nums[i-k]);
        }
        nums=a;
    }
};
```
and
```
// Rotate Array
class Solution {
public:
    void reverse(vector<int> &nums, int l, int r){
    	int temp;
        while(l<r){
	    temp=nums[l];
            nums[l]=nums[r];
            nums[r]=temp;
            l++;
            r--;
	}
    }

    void rotate(vector<int>& nums, int k) {
        k%=nums.size();
    	reverse(nums,0,nums.size()-1);
	reverse(nums,0,k-1);
	reverse(nums,k,nums.size()-1);
    }
};
```
**Expected behavior**
After my code was accepted, I tried some other test case:
Input: nums = [], target = 1

My output: Runtime error: division by zero
Expected Output: []

**Additional context**
This issue can either be a testcase contribution if the given testacse is accepted otherwise it can be a content issue.

**Comment by CooperCooperCooper** [comment]
Hi @agarwalrounak,
Thank you for reaching out to us. I've relayed your feedback to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @agarwalrounak,
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
