### ISSUE TITLE
231. 2的幂增加进阶要求

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#2010]
**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
第 231 题和第 326 题、第 342 题相似，后面两道题（326 和 342）都有进阶要求，建议第 231 题增加同样的进阶要求，中文描述和英语描述需要同步更新。
另外第 326 题和第 342 题的进阶要求应该是一样的描述，但是这两道题的英语描述中的进阶要求描述有不同，中文描述中的进阶要求描述是相同的，建议统一英语描述中的进阶要求描述，第 231 题增加进阶要求之后也应该是相同的进阶要求描述。

**你使用的语言**
Java

**你提交或者运行的代码**

**期望行为**
第 231 题增加进阶要求，中文描述和英语描述需要同步更新。
第 326 题和第 342 题的英语描述中的进阶要求描述应该统一，且第 231 题的进阶要求描述也应该保持一致。

**屏幕截图**

**额外的上下文**

**Comment by feiceh** [comment]
感谢反馈，已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，在与美国区负责同事沟通了解后，「231. 2的幂」一题的优化已在我们的计划队列之内，但这可能需要一段时间进行处理，还请耐心等待，目前我们会暂时关闭该 issue，如有更多反馈和建议请与我们联系。
