### ISSUE TITLE
Missing Test Case - 1776. Minimum Operations to Reduce X to Zero

### ISSUE THREAD

**Issue by sgarg367** [LeetCode-Feedback/LeetCode-Feedback#2011]
#### Your LeetCode username

Leetcode username: sgarg367

#### Category of the bug
Missing test case

#### Description of the bug

1 test case is missing, in which the solution is not correct then also the solution is being accepted in leetcode.
**Test case :** 
[10,1,1,1,1,1]
5

#### Code you used for Submit/Run operation

```
//minimum Operations
class Solution {
public:
    int minOperations(vector<int>& a, int x) {
        int n = a.size();
        int i=0,c=0;
        while(i < n && c < x)
        {
            c += a[i++];
        }
        
        if(i == n)
        {
            return c == x ? n : -1;
        }
        
        int l = i-1;
        int r = n-1;
        int res = (c == x ? i : INT_MAX);
        while(l >= 0 && r > l)
        {
            if(c >= x)
                c -= a[l--];
            if(c < x)
                c += a[r--];
            if(c == x)
            {
                res = min(res, l+n-r);
            }
        }
        
        return res == INT_MAX ? -1 : res;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The solution should not have been accepted as the test case is missing for which this solution is failing.

#### Screenshots

Acceptance screenshot:
![image](https://user-images.githubusercontent.com/49973670/104700386-14959880-573a-11eb-9237-ebabd2f22d5a.png)

Failing test case screenshot:
![image](https://user-images.githubusercontent.com/49973670/104700417-21b28780-573a-11eb-88a4-3059c1c17b7d.png)

#### Additional context

The above test case should be added to the system for better handling of corner cases.

**Comment by lc-kay** [comment]
Hi @sgarg367 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @sgarg367 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
