### ISSUE TITLE
Valid answer is showing as Wrong Answer - 451. Sort Characters By Frequency

### ISSUE THREAD

**Issue by joric** [LeetCode-Feedback/LeetCode-Feedback#20113]
### LeetCode Username
joric

### Problem number, title, and link
451. Sort Characters By Frequency

### Category of the bug
Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### Description of the bug
The problem expects to sort the characters by frequency. If there are any ties, then any order should be accepted as per the problem's description: "Return the sorted string. If there are multiple answers, return any of them."

### Language used for code
Python3

### Code used for Submit/Run operation

```python
class Solution:
    def frequencySort(self, s: str) -> str:
        return ''.join(sorted(s,key=lambda c:-s.count(c)))

class Solution:
    def frequencySort(self, s: str) -> str:
        return''.join(sorted(s,key=Counter(s).get)[::-1])
```

### Expected behavior

Leetcode solver treats valid answers as wrong answers. Both 'eeeelolovtcd' and 'eeeeoollvtdc' should be accepted as valid, because they are sorted in descending frequency:

```
# loveleetcode
# 221424411214

# eeeelolovtcd
# 444422221111

# eeeeoollvtdc
# 444422221111
```

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/852547/2b8b3732-6326-412d-a3ad-2f5e8c03ddfd)

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/852547/4939e320-09da-4290-a523-e2a3ed37f4b3)

### Additional context

I have noticed that another rule was implicitly injected in one of the examples: `the same characters must be together`. It would be much nicer to move this rule to the problem description or fix the solver. Please address this or the issue continues popping up.

Related issues: #5137 #7888 #10124

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.


Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by naXa777** [comment]
@joric, read carefully example 2:

> **Input**: s = "cccaaa"
> **Output**: "aaaccc"
> **Explanation**: Both 'c' and 'a' appear three times, so both "cccaaa" and "aaaccc" are valid answers.
> Note that "cacaca" is incorrect, as the same characters must be together.

**Comment by joric** [comment]
@naXa777 read carefully "Additional context" of the issue.

**Comment by joric** [comment]
Completed how?

**Comment by naXa777** [comment]
@joric, I've noticed that @LC-Pam doesn't respond in comments
