### ISSUE TITLE
Missing Test Case - 64. Minimum Path Sum

### ISSUE THREAD

**Issue by jiya10208** [LeetCode-Feedback/LeetCode-Feedback#20110]
### LeetCode Username

jiya102082004

### Problem number, title, and link

[64. Minimum Path Sum](https://leetcode.com/problems/minimum-path-sum/)  

### Category of the bug
- [ Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug
While running the code on provided custom testcase it is showing their is wrong answer but while submitting the code it is accepting the code . 
#Input
grid =
[[1],[1]]
Output
1
Expected
2

### Language used for code

C++

### Code used for Submit/Run operation

```
class Solution {
public:

    int minPathSum(vector<vector<int>>& grid) {
         int m=grid.size();
         int n= grid[0].size();
        
         vector<vector<int>>dp(m+1, vector<int>(n+1, 1e8));

         dp[m-1][n-1]=grid[m-1][n-1];

         for (int i=m-1; i>=0; i--){
             for (int j= n-1;j>=0; j--){
                 if (j-1>=0) dp[i][j-1]= min(dp[i][j-1], dp[i][j]+grid[i][j-1]);

                 if (i-1>=0)  dp[i-1][j]= min(dp[i-1][j], dp[i][j]+ grid[i-1][j]);
            }
         }
         return dp[0][0];
        
    }
};
```

### Expected behavior

<img width="384" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/122276932/19c3947b-cb6f-4147-ad23-d969d5de638a">

In the given test case it is showing wrong answer but while running the code, the code is getting accepted.
<img width="383" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/122276932/11aa45e2-35c0-49e9-aba1-ddd6d6f84ec0">

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
