### ISSUE TITLE
Missing test case for 1161. Maximum Level Sum of a Binary Tree

### ISSUE THREAD

**Issue by Rohitesh-Kumar-Jain** [LeetCode-Feedback/LeetCode-Feedback#2012]
#### Your LeetCode username

Kumar-Jain

#### Category of the bug
- [x] Missing Test Case

#### Description of the bug

Test cases are missing 

#### Code you used for Submit/Run operation

```
class Solution {
    public int maxLevelSum(TreeNode root) {
        int ans=-1000;
        Queue<TreeNode> q = new LinkedList<>();
        q.offer(root);
        int level=0;
        int finalAns=1;
        while(!q.isEmpty()){
            int size = q.size();
            int sum=0;
            level++;
            for(int i=0;i<size;i++){
                if(q.peek().left!=null) q.offer(q.peek().left);
                if(q.peek().right!=null) q.offer(q.peek().right);
                sum = sum + q.poll().val;
            }
            if(sum> ans) finalAns= level;
            ans = sum > ans ? sum : ans;
        }
        return finalAns;
    }
}
```

#### Language used for code

Java

#### Expected behavior

[-10000,-20000,-30000,-2000,-500,-1000,null] this is a valid missing test case that will fail the acceptance of the above code. 

#### Screenshots

<img width="1440" alt="Screenshot 2021-01-15 at 3 02 28 PM" src="https://user-images.githubusercontent.com/62026125/104708607-f2087d00-5743-11eb-8017-1eafcd1f4764.png">
<img width="1440" alt="Screenshot 2021-01-15 at 3 01 48 PM" src="https://user-images.githubusercontent.com/62026125/104708612-f339aa00-5743-11eb-952d-1c0ac8bbe19d.png">

**Comment by lc-kay** [comment]
Hi @Rohitesh-Kumar-Jain 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Rohitesh-Kumar-Jain 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by Rohitesh-Kumar-Jain** [comment]
Thanks for reviewing it.
