### ISSUE TITLE
1252. 奇数值单元格的数目增加进阶要求

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#2014]
**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
第 1252 题可以使用模拟的方式做，由于数据量小因此模拟也是可以通过的。但是存在时间复杂度更优的方法，因此建议增加进阶要求。
这篇题解列举了三种做法：[【题解】1252. 奇数值单元格的数目](https://leetcode-cn.com/problems/cells-with-odd-values-in-a-matrix/solution/ti-jie-1252-qi-shu-zhi-dan-yuan-ge-de-shu-mu-by-ze/)
进阶要求大致是使用比模拟的做法时间复杂度更低的做法，具体语言描述请官方考虑之后决定。中文描述和英语描述需要同步更新。

**你使用的语言**
Java

**你提交或者运行的代码**

**期望行为**
增加进阶要求，中文描述和英语描述需要同步更新。

**屏幕截图**

**额外的上下文**

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，在与美国区负责同事沟通了解后，「1252. 奇数值单元格的数目」一题的优化已在我们的计划队列之内，但这可能需要一段时间进行处理，还请耐心等待，目前我们会暂时关闭该 issue，如有更多反馈和建议请与我们联系。
