### ISSUE TITLE
Missing Test Case - 339. Nested List Weight Sum

### ISSUE THREAD

**Issue by zeeqy** [LeetCode-Feedback/LeetCode-Feedback#2017]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The commented code for the interface is incorrect. There are two `isInteger` methods of the class which the second one should be the `getList` according to its description. 

NVM, I think I made a mistake. closing the issue

#### Code you used for Submit/Run operation

```
#    def isInteger(self):
#        """
#        @return the nested list that this NestedInteger holds, if it holds a nested list
#        Return None if this NestedInteger holds a single integer
#        :rtype List[NestedInteger]
#        """
```

#### Language used for code

`python3`

**Comment by lc-kay** [comment]
Hi @zeeqy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
