### ISSUE TITLE
Missing Test Case - 8. String to Integer (atoi)

### ISSUE THREAD

**Issue by harshpratap2510** [LeetCode-Feedback/LeetCode-Feedback#20170]
### LeetCode Username

soulreaper25

### Problem number, title, and link
--> 8. String to Integer (atoi)  https://leetcode.com/problems/string-to-integer-atoi/

### Category of the bug
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

A test case is missing .The given code gets accepted but if i add manually some test cases it fails.

### Code used for Submit/Run operation

```
class Solution {
public:
    int myAtoi(string s) {
        long long ans=0;
    bool isNeg=0;    
    bool isPos=0;
    bool isup =0;
    int n = s.size();
    for(int i =0; i<n;i++)
    {
      if(i==3 && s[i]=='+' && ans==0 && isup==1) return 0;

         else if((s[i]=='+'|| s[i]=='-' || s[i]==' '||s[i]=='.') && ans!=0 )
        {
            break;
        }
       
        else if(s[i]==' ' && i!=0 && s[i-1]=='0')
        {
            break;
        }
        else if(s[i]==' ' && i!=0 && s[i-1]=='+')
        {
            break;
        }
        else if(s[i]==' ' && ans==0)
        {
            continue;
        }
        else if(s[i]=='.' && ans==0)
        {
            return 0;
        }
        else if(s[i]=='-' && isPos )
        {
            break;
        }
        else if(s[i]=='-' && isNeg )
        {
            break;
        }
        else if(s[i]=='-' &&  i!=0 && s[i-1]=='0')
        {
            break;
        }
        else if(s[i]=='-' && ans==0)
        {
            isNeg=1;
        }
        else if(s[i]=='+' && isNeg )
        {
            break;
        }
        else if(s[i]=='+' && isPos )
        {
            break;
        }
        else if(s[i]=='+' && ans==0)
        {
            isNeg=0;
            isPos=1;
        }
        

        else if('a'<=s[i] && 'z'>=s[i])
        {
            break;
        }
        else if('A'<=s[i] && 'Z'>=s[i])
        {
            break;
        }
       // else if(s[i]=='+' && i!=0) return 0;
        else{
            isup = 1;
            ans*=10;
            ans+=s[i]-'0';
            if(ans>2147483647 && isNeg==0)
            {
                ans = 2147483647;
                break;
            }
            else if(ans>2147483648 && isNeg==1)
            {
                ans = -2147483648;
                break;
            }
        }

    }
    if(isNeg && ans!=-2147483648)
    {
        ans=-1*ans; 
    }
    return ans;
    
    }
}; 

```

### Expected behavior

At custom test case = "0000000+36" my code fails but as this type of test case is missing , my code is accepted.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
