### ISSUE TITLE
Missing Test Case - 224. Basic Calculator

### ISSUE THREAD

**Issue by gatsbyz** [LeetCode-Feedback/LeetCode-Feedback#20173]
### LeetCode Username
gatsbyz

### Problem number, title, and link

224. Basic Calculator https://leetcode.com/problems/basic-calculator/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
More test cases to test with leading `-` in front of the parenthesis

### Language used for code
Go

### Code used for Submit/Run operation

```
func calculate(s string) int {
    acc := 0
    i := 0
    prevSign := 1
    parenSign := 1
    signStack := []int{}

    for i < len(s) {
        switch c := s[i]; c {
            case ' ':
            case '(':
            signStack = append(signStack, prevSign)
            // parenSign *= prevSign
            prevSign = 1
            case ')':
            parenSign *= signStack[len(signStack)-1]
            signStack = signStack[:len(signStack)-1]
            case '+':
            prevSign = 1
            case '-':
            prevSign = -1
            default:
            start := i
            for i < len(s) && '0' <= s[i] && s[i] <= '9' {
                i++
            }
            n, _ := strconv.Atoi(s[start:i])
            acc += n * parenSign * prevSign
            i--
        }
        i++
    }

    return acc
 }
```

### Expected behavior

I added a test case 4 that does not pass.
`s="1-(11-(4+15+2)+3)-(6+18)"` should result in `-16` but yields `54` in my example code. 
But the default test cases 1,2,3 all pass because they do not test when `-` is right before parenthesis, therefore this will make insufficient answers pass.

### Screenshots

<img width="579" alt="Screenshot 2024-02-07 at 9 13 37 AM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/11021924/a90ccbf4-7efc-4117-890f-459b3dd99fbf">

### Additional context
Please add my test case (or other appropriate test case)

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
