### ISSUE TITLE
Misleading Title

### ISSUE THREAD

**Issue by rakshapadiyar** [LeetCode-Feedback/LeetCode-Feedback#20175]
### Problem number, title, and link
783. Minimum Distance Between BST Nodes (https://leetcode.com/problems/minimum-distance-between-bst-nodes/

### Category of the bug
- [ ✔] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The problem statement is to return the minimum "difference" between the values of any two different nodes in the given binary search tree. But, the title says ' Minimum *Distance* Between BST Nodes '. The word distance implies difference in the levels of the  two nodes in a tree, which has nothing to do with the answer(difference) that must actually be computed in the problem.
Appended to the problem description is "Note: This question is the same as 530: https://leetcode.com/problems/minimum-absolute-difference-in-bst/" and the title of this question has the appropriate word "difference" used.

### Language used for code
 Any

### Expected title
Minimum difference between BST nodes

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

we avoid changing problem names as it breaks the problem link.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
