### ISSUE TITLE
Improper Problem Title - 3024. Type of Triangle II

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#20189]
### LeetCode Username
stormsunshine

### Problem number, title, and link
[3024. Type of Triangle II](https://leetcode.com/problems/type-of-triangle-ii)

### Category of the bug
- [x] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
Issue #20053 mentions that the problem title should be updated for problem 3024. However, the issue has been closed with the reply that there is a problem named “Type of Triangle”.

I do not see any problem named "Type of Triangle". Also I have tried the link https://leetcode.com/problems/type-of-triangle, but the result is 404. Please refer to the screenshot below.

There is no evidence that there is a problem named “Type of Triangle”. If such a problem does exist, could you please provide the problem link and the problem number? Otherwise, such a problem does not exist, and please change the title of problem 3024 to "Type of Triangle".

### Expected behavior
Change the title of problem 3024 to "Type of Triangle". The link to the problem should be updated accordingly.

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/12067364/527afcfc-02a2-4f01-935e-70e7373be18a)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
