### ISSUE TITLE
Missing Test Case - 279. Perfect Squares

### ISSUE THREAD

**Issue by sudhackar** [LeetCode-Feedback/LeetCode-Feedback#20190]
### LeetCode Username

happysings

### Problem number, title, and link

[279. Perfect Squares](https://leetcode.com/problems/perfect-squares/)
https://leetcode.com/problems/perfect-squares/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The constraints specifically mention 
    1 <= n <= 10000
However, 10000 seems to be missing from the tests.
It should return 1 as its a perfect square but accepted code returns 2.

### Language used for code

rust

### Code used for Submit/Run operation

```rust
impl Solution {
    pub fn num_squares(n: i32) -> i32 {
        let n = n as usize;
        let mut dp = vec![10_000; n + 1];
        dp[0] = 0;
        for i in 1..=n {
            for j in 1..100 {
                let sq = j * j;
                if sq > i {
                    break;
                }
                dp[i] = dp[i].min(dp[(i - sq)] + 1);
            }
        }
        dp[n] as i32
    }
}
```

### Expected behavior

[This](https://leetcode.com/problems/perfect-squares/submissions/1169442757) submission should not be accepted.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/10460978/ecf373a5-d343-4f19-818e-abdc62fec861)

### Additional context

Simple corner case seems to be missing from the problem

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
