### ISSUE TITLE
Test case bug 208 & 211

### ISSUE THREAD

**Issue by nuenuehao2** [LeetCode-Feedback/LeetCode-Feedback#20199]
### LeetCode Username

nuenuehao2

### Problem number, title, and link

208: https://leetcode.com/problems/implement-trie-prefix-tree/?source=submission-noac
211: https://leetcode.com/problems/design-add-and-search-words-data-structure/description/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [X] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Wrong results for the below test case
["Trie","startsWith"]
[[],["a"]]

### Language used for code

Python3

### Code used for Submit/Run operation

```
class TreeNode:
    def __init__(self, references=[None for _ in range(26)], isEnd=False):
        self.references = references
        self.isEnd = isEnd

class Trie:

    def __init__(self):
        self.root = TreeNode()

    def insert(self, word: str) -> None:
        curr = self.root
        for c in word:
            curr.references[ord(c) - ord('a')] = TreeNode()
            curr = curr.references[ord(c) - ord('a')]
        curr.isEnd = True
        

    def search(self, word: str) -> bool:
        curr = self.root
        for c in word:
            if curr.references[ord(c) - ord('a')]:
                curr = curr.references[ord(c) - ord('a')]
            else: 
                return False
        if curr.isEnd:
            return True
        else:
            return False
        

    def startsWith(self, prefix: str) -> bool:
        curr = self.root
        for c in prefix:
            if curr.references[ord(c) - ord('a')]:
                curr = curr.references[ord(c) - ord('a')]
            else:
                return False
        return True

```

### Expected behavior

Accepted

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/17576216/ecc75a29-2ed2-4950-9e9c-ba0f11d36009)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/17576216/e9aa6d8b-e001-489a-bfe6-caac3201a07f)

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team

**Comment by nuenuehao2** [comment]
Thanks for the reply! May I know why the test case is accepted, but the
submission is wrong answer for the same test case? And why the output is
different for the same test case?

 [image: image.png]
