### ISSUE TITLE
Missing Test Case - 279. Perfect Squares

### ISSUE THREAD

**Issue by SreeDeekshithaEswaran** [LeetCode-Feedback/LeetCode-Feedback#20195]
### Problem number, title, and link

279. Perfect Squares
https://leetcode.com/problems/perfect-squares/

### Category of the bug
- [x] Problem description
- [ ] Solved examples
- [x] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The bug is not related to the problem description, examples, or hints. It's more about understanding the problem constraints and optimizing the solution. Would like to add more testcases which seem hard to solve but are as easy as solving the 2 and 3 digit numbers.

### Language used for code

SQL

### Code used for Submit/Run operation

```
class Solution {
    public int numSquares(int n) {
        int[] dp = new int[n + 1];
        Arrays.fill(dp, Integer.MAX_VALUE);
        dp[0] = 0;    
        for (int i = 1; i <= n; i++) {
            for (int j = 1; j * j <= i; j++) {
                dp[i] = Math.min(dp[i], dp[i - j * j] + 1);
            }
        }    
        return dp[n];
    }
}
```
###TestCase
Input:
n = 12345

Output:
3

Explanation:
12345 = 100^2 + 100^2 + 5^2.

### Expected behavior

The numSquares method should correctly determine the least number of perfect square numbers that sum to the given input n. The solution should return an integer representing this least number.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.


Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by stormsunshine** [comment]
The constraint require that n <= 10<sup>4</sup>. Why do you provide a test case that exceeds the constraint?

**Comment by SreeDeekshithaEswaran** [comment]
> The constraint require that n <= 104. Why do you provide a test case that exceeds the constraint?

Hello stormsunshine,

Thank you for your feedback and for bringing up the constraint regarding the input range. I provided the test case n = 12345 as an example to explore the robustness of the solution and to verify its correctness for larger inputs. While I understand that the problem statement specifies n <= 10^4, I wanted to ensure that the solution can handle cases beyond this constraint and still produce the expected output.

If you believe it's necessary to adhere strictly to the problem constraints for the provided test cases, I can certainly adjust the test case accordingly. However, I thought it would be valuable to include a broader range of inputs to validate the solution's scalability and efficiency.

Please let me know your thoughts on this approach. I'm open to making any necessary adjustments to ensure the clarity and correctness of the provided test cases.

Best regards,
SreeDeekshithaEswaran

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
