### ISSUE TITLE
Leetcode-30 ||Substring with Concatenation || Absence of testcase which leads to WA even when failed at higher data range.

### ISSUE THREAD

**Issue by saransh-bairagi** [LeetCode-Feedback/LeetCode-Feedback#20196]
### LeetCode Username
saranshbairagi

### Problem number, title, and link
30. Substring with Concatenation https://leetcode.com/problems/substring-with-concatenation-of-all-words/

### Category of the bug
Missing Testcase
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

 Absence of testcase which leads to WA even when failed at higher data range.

### Language used for code

C++

### Code used for Submit/Run operation

```
class Solution {
public:
    vector<int> findSubstring(string s, vector<string>& words) {
        vector<string>cont;
        vector<int>answer;
        int n=words.size();
        int m=words[0].length();
        int l=n*m;
        map<string,int>maen;
        for(auto E:words)maen[E]++;
        for(int i=0;i<s.length()-l+1;i++){
            cont.push_back(s.substr(i,l));
        }
        for(int i=0;i<cont.size();i++){
            string temp=cont[i];
            if(maen[temp.substr(0,m)]==0)continue;
            map<string,int>mp;
            for(int i=0;i<l;i=i+m){
                mp[temp.substr(i,m)]++;
            }
            bool yes=true;
            for(auto E:maen){
                if(mp[E.first]!=E.second)yes=false;
            }
            if(yes)answer.push_back(i);
        }
        return answer;
    }
```

### Additional context

[
[Testcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/14205378/Testcase.txt)
](url)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code Accepted submission link you submitted led to the observed result.


Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by saransh-bairagi** [comment]
Testacse is missing!!Already attached the missing file
