### ISSUE TITLE
面试题35. 复杂链表的复制 在JavaScript环境下执行出错

### ISSUE THREAD

**Issue by Zephyrrro** [LeetCode-Feedback/LeetCode-Feedback#202]
**题目传入参数有误**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
题目 [面试题35. 复杂链表的复制](https://leetcode-cn.com/problems/fu-za-lian-biao-de-fu-zhi-lcof/) 在使用 `Javascript` 时的 **`head`** 传入有问题，无论任何输入都是 `undefined`

**你使用的语言**
Javascript

**你提交或者运行的代码**
```javascript
var copyRandomList = function (head) {
  console.log(head);
  return null;
};
```

**期望行为**
正常传入 `head`

**屏幕截图**
![image](https://user-images.githubusercontent.com/43735265/80332953-025b8d80-887f-11ea-98e4-21a881e5743f.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认的～

**Comment by feiceh** [comment]
fixed
