### ISSUE TITLE
Missing Test Case - 1502. Can Make Arithmetic Progression From Sequence

### ISSUE THREAD

**Issue by NoDeathIsSuccess** [LeetCode-Feedback/LeetCode-Feedback#20203]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

### LeetCode 用户名

不嗝屁就算成功

### 问题号码、标题和链接

1502. 判断能否形成等差数列 https://leetcode.cn/problems/can-make-arithmetic-progression-from-sequence/

### Bug 类型

缺少测试用例

### 描述

只使用求和来判断是否为等差数列的代码能够通过提交。
一个正常的等差数列有求和公式 (首项+尾项)*项数/2，但题目中的数组求和满足这一条件只是判断的必要条件。
例如，在{1,3,5,7,9,11,13,15,17,19}的基础上，将5改为7，将13改为11，并交换位置，得到一个应该输出false的样例{1,3,11,7,9,11,7,15,17,19}。能通过测评的基于求和判断的代码无法通过此样例。

### 你使用的语言

JAVA

### 你提交或者运行的代码

```
class Solution {
    public boolean canMakeArithmeticProgression(int[] arr) {
        int a = Integer.MIN_VALUE, b = a, n = arr.length;
        for (int temp : arr) {
            if (temp > a) {
                b = a;
                a = temp;
            } else if (temp > b) {
                b = temp;
            }
        }
        int diff = b - a;
        if (diff == 0) {
            for (int i = 1; i < n; i++) {
                if (arr[i] != arr[i - 1]) return false;
            }
            return true;
        }
        for (int i = 0; i < n; i++) {
            if (i > 0 && Math.abs(arr[i] - arr[i - 1]) % diff != 0) return false;
        }
        int realSum = Arrays.stream(arr).sum();
        int sum = a * n + (n * n - n) * diff / 2;
        return sum == realSum;
    }
}
```

### 期望行为

此代码不应该通过这道题目。

### 屏幕截图

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/111669596/1c456840-266e-4a8e-bfa5-31753018c3f3)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
