### ISSUE TITLE
Missing Test Case - 2883. Drop Missing Data

### ISSUE THREAD

**Issue by Aditimohadarkar** [LeetCode-Feedback/LeetCode-Feedback#20202]
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Code used for Submit/Run operation
import pandas as pd

def dropMissingData(students: pd.DataFrame) -> pd.DataFrame:
    students_missing_data = students.dropna()

    return students_missing_data

data = {'student_id': [32, 217, 779, 849],
        'name': ['Piper', None, 'Georgia', 'Willow'],
        'age': [5, 19, 20, 14]}

students_df = pd.DataFrame(data)
cleaned_data = dropMissingData(students_df)

print(cleaned_data)

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

### Expected behavior

![Screenshot 2024-02-08 120300](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/149673504/b6b0b7eb-b578-46e8-8119-42bc61580e84)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us!

When comparing the outcomes of "Run Code" and "Submit" for a specific test case, it's evident that the input and expected values are the same, yet the output values differ.

To assist you further, we have documented the causes and potential solutions for this type of issue in detail. You can find this information in our knowledge base article: [Test Case Discrepancy - Causes and Solutions](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-).

I hope this resource proves helpful. Should you have any additional questions or need further clarification on this case, please do not hesitate to reach out to us. We're here to assist you!

Best regards,
LeetCode Support Team
