### ISSUE TITLE
Wrong return order in example 2 - 1403. Minimum Subsequence in Non-Increasing Order

### ISSUE THREAD

**Issue by pochopsp** [LeetCode-Feedback/LeetCode-Feedback#20216]
### LeetCode Username
pochopsp

### Problem number, title, and link
1403. Minimum Subsequence in Non-Increasing Order https://leetcode.com/problems/minimum-subsequence-in-non-increasing-order/

### Category of the bug
- [ ] Solved examples

### Description of the bug
In the **Example 2** at the end of **Explanation** there is the sentence "_Note the subsequence has to be returned in non-decreasing order._ " BUT the problem description (and the title) clearly states that the subsequence must be returned in non-increasing order.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
