### ISSUE TITLE
Weak Test Cases - Largest Divisible Subset

### ISSUE THREAD

**Issue by VJ1122001** [LeetCode-Feedback/LeetCode-Feedback#20223]
### LeetCode Username
virujthakur01

### Problem number, title, and link
368. Largest Divisible Subset https://leetcode.com/problems/largest-divisible-subset/

### Category of the bug
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug
Incorrect code is getting accepted, because the test cases are weak.

### Language used for code
Python 3

### Code used for Submit/Run operation

```
class Solution:
    def largestDivisibleSubset(self, nums: List[int]) -> List[int]:
        if nums == [9,75,12,18,90,4,36,8,28,2]:
            return [2,4,12,36]
        nums.sort()
        n = len(nums)
        
        # print(nums)
        res  = []
        for i in range(n):
            ans = [nums[i], ]
            j= i+1
            lcm = nums[i]
            while j < n:
                if nums[j]% lcm == 0:
                    ans.append(nums[j])
                    lcm = ((nums[j]* lcm)// gcd(nums[j], lcm))
                j+=1
            # print(ans)
            if len(res) < len(ans):
                res= ans
                
        nums.reverse()
        # print(nums)
        for i in range(n):
            ans = [nums[i], ]
            j= i+1
            g = nums[i]
            while j < n:
                if math.gcd(nums[j],g) == nums[j]:
                    ans.append(nums[j])
                    g = nums[j]
                j+=1
            # print(ans)
            if len(res) < len(ans):
                res= ans
            
        return res
                
```

### Expected behavior
The code should fail as it doesn't cover all possibilites. One test case fails, but then since there is only one test case that fails, it can be handled using if else statements.

### Additional context
Please add more testcases so that the solution fails on multiple testcases and they cannot be handled using if else.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

Details regarding the missing test case.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by VJ1122001** [comment]
The test case is added in the comment section of the code.
if nums == [9,75,12,18,90,4,36,8,28,2]:
            return [2,4,12,36]
There is only one testcase of this kind, where the answer forms as [2, 4, 12, 36]. This test case fails when I just start building the solution from the start or from the end of the sorted array as described in the previous code. This can be handled through and if-else statement, not testing the solution on more such cases.
The request is to add more such cases which can not be solved from just iterating over the sorted array from front or in reverse order, so that the solver can think for the right approach.
Regards
Viruj Thakur

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

Test case already exists. 

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
