### ISSUE TITLE
Test Case 75 Output Mismatch: Expected 0 but Received 2

### ISSUE THREAD

**Issue by imkrishnaagrawal** [LeetCode-Feedback/LeetCode-Feedback#20227]
### LeetCode Username
imkrishnaagrawal

### Problem number, title, and link
[746. Min Cost Climbing Stairs](https://leetcode.com/problems/min-cost-climbing-stairs/)

### Category of the bug
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### Description of the bug
I am getting some weird when running testcase 75. it say expected output 0 and actual is 2. however when I debug my code it returns 0 and not 2. I am not sure if I am missing something obvious or its some bug.

### Language used for code
Python3

### Code used for Submit/Run operation

```
class Solution:
    def calcCost(self, cost, n, memo={}):
        if n in memo:
            return memo[n]
        if n <= 1:
            return 0
        if n == 2:
            return min(cost[0], cost[1])
        memo[n] = min(
            self.calcCost(cost, n - 1, memo) + cost[n - 1],
            self.calcCost(cost, n - 2, memo) + cost[n - 2],
        )
        return memo[n]

    def minCostClimbingStairs(self, cost: List[int]) -> int:
        return self.calcCost(cost, len(cost))

```

### Screenshots

<img width="723" alt="testcase" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/70054423/1c2234be-ce84-41ca-8a29-b0f561a34c20">
<img width="832" alt="local" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/70054423/49b983e1-aec4-466c-92b0-358ec8974a69">

**Comment by imkrishnaagrawal** [comment]
I think I've identified the reason behind the behavior observed on LeetCode. It seems that during their internal test execution, LeetCode instantiates a single Solution object and then invokes the minCostClimbingStairs method multiple times with different test cases using the same Solution instance.

### Code Version 1 (Explicit `memo` Reset):
```python
class Solution:
    def calcCost(self, cost, n, memo={}):
        # code
    # Uses an explicit empty dictionary for `memo` on each call.
    def minCostClimbingStairs(self, cost: List[int]) -> int:
        return self.calcCost(cost, len(cost), {})
```
This version resets `memo` for each `minCostClimbingStairs` call, ensuring independence and consistency across calls.

### Code Version 2 (Mutable Default `memo`):
```python
class Solution:
    def calcCost(self, cost, n, memo={}):
        # code
    # Relies on a mutable default `memo` argument.
    def minCostClimbingStairs(self, cost: List[int]) -> int:
        return self.calcCost(cost, len(cost))
```
This version's `memo` persists across calls, risking cross-call contamination and potential incorrect outcomes for multiple calls.


-The first approach guarantees fresh `memo` for each call, ideal for repeated usage. The second approach may share `memo` state across calls, undesired for multiple executions.
  
Let me know if my assumption is correct, I'll close the ticket Thanks.

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
