### ISSUE TITLE
Missing Test Case - 11. Container With Most Water

### ISSUE THREAD

**Issue by MathieuLaureti** [LeetCode-Feedback/LeetCode-Feedback#20220]
### LeetCode Username
Winter-Wind

### Problem number, title, and link
[11. Container With Most Water](https://leetcode.com/problems/container-with-most-water/)

### Category of the bug
- [ ] Solved examples
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
### Description of the bug
on the test case 2 (Input : [1,1]) it says output is 49 even tho the same code in intelJidea and eclipse do output the good answer which is 1.
All the three screenshot are the same code copy and paste each time.

### Code used for Submit/Run operation

```
class Solution {
        public static int rep=0;
        public static double limite1=0.50;
        public static int maxArea(int[] height) {
            limite1=limite1*height.length;
            int count1=0,count2=height.length-1,x;
            while(count2-count1>=limite1){
                if(height[count1]<height[count2]){
                    x = height[count1];
                }else {
                    x = height[count2];
                }
                x=x*(count2-count1);
                if(x>rep){
                    rep=x;
                }
                if(height[count1]>height[count2]){
                    count2--;
                }else {
                    count1++;
                }
            }
            return rep;
        }

    }
```

### Expected behavior

on the test case 2 (Input : [1,1]) it says output is 49 even tho the same code in intelJidea and eclipse do output the good answer which is 1.

### Screenshots
<img width="265" alt="Capture d’écran 2024-02-09 010442" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/158770187/40d100b6-3f90-4af6-8446-8dcf2f689775">
<img width="629" alt="Capture d’écran 2024-02-09 010431" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/158770187/10d76a5c-6817-49b6-b249-106e3af3d425">
<img width="389" alt="Capture d’écran 2024-02-09 010323" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/158770187/344f03d1-b8b7-41ce-987d-ca0f1d579314">

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
