### ISSUE TITLE
False Test Case - 1432. Max Difference You Can Get From Changing an Integer

### ISSUE THREAD

**Issue by Gregory-Pereira** [LeetCode-Feedback/LeetCode-Feedback#2022]
#### Your LeetCode username

grepere

#### Category of the bug
- [√ ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Faulty test case. Problem was to find the max diff between two numbers for replacing all instances of a single integer (chosen 2 separate times) with a value from 1 - 9. An example was the number 123456. The max value should be 923456 and the min value should be 113456, and their difference should be 810000, not 820000.

#### Code you used for Submit/Run operation

```
var maxDiff = function(num) {
     return replaceStringMaxMin(JSON.stringify(num), true) - replaceStringMaxMin(JSON.stringify(num), false);
};

let replaceStringMaxMin = function(str, bool) {
    let replacingDigit;
    if (bool === false) { // false = min
        for (var i = 0; i < str.length; i++) {
            if (str[i] != '1' && !replacingDigit) {
                replacingDigit = str[i];
                for (var j = i; j < str.length; j++) {
                    if (str[j] == replacingDigit) {
                        str = str.substring(0, j) + '1' + str.substring(j+1);
                    }
                }      
            }
        }
        return parseInt(str);
    } else if (bool === true) { // true = max
        for (var i = 0; i < str.length; i++) {
            if (str[i] != '9'&& !replacingDigit) {
                replacingDigit = str[i];
                console.log(replacingDigit);
                for (var j = i; j < str.length; j++) {
                    if (str[j] == replacingDigit) {
                        str = str.substring(0, j) + '9' + str.substring(j+1);
                    }
                }      
            }
        }
        return parseInt(str);
    }
};
```

#### Language used for code
 Javascript

#### Expected behavior
Failed test case for integer 123456, with result of 810000, but should have passed.

**Comment by lc-kay** [comment]
@Gregory-Pereira Please check out the comment by pchen13 for a better understanding of the rules for this problem. The expected answer is correct. Thank you for your time.
