### ISSUE TITLE
Missing Test Case - 647. Palindromic Substrings

### ISSUE THREAD

**Issue by Archit669** [LeetCode-Feedback/LeetCode-Feedback#20238]
### LeetCode Username
https://leetcode.com/archit669/

### Problem number, title, and link
647. Palindromic Substrings
[Palindromic Substrings](https://leetcode.com/problems/palindromic-substrings/)

### Category of the bug
- [ ] Missing test Case

### Description of the bug
The provided solution uses an O(n^3) approach, which is acceptable for the given constraints 1 <= 1000 <= s.length
However, the test case with the maximum input size is missing, leading to Time Limit Exceeded errors.

### Language used for code
C++

### Code used for Submit/Run operation
```cpp

class Solution {

    bool isPalindrome(string &str){

        int n = str.size();

        int start = 0;
        int end = n-1;

        while (start <= end){
            if (str[start] != str[end]){
                return false;
            }

            start++; end--;
        }

        return true;
    }
    

public:
    int countSubstrings(string s) {

        int n = s.size();

        int count = s.size();
        
        for (int idx = 0; idx < n; idx++){
            for (int size = 2; idx + size <= n ; size++){
                string str = s.substr(idx, size);
                if (isPalindrome(str)){
                    count++;
                }
            }
        }

        return count;
    }
};
```

### Expected behavior
The provided code of time complexity of O(n^3) should not pass all the testcases with the given constraints of string of length 1000.

### Screenshots
![output](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/68770400/a5ca551c-8058-48aa-8103-edafc0b3befd)

### Additional Context
Testcase which is missing (string of length 1000) which should give TLE : 
s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijkl"

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback. The test case already exists.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!
<img width="196" alt="Screen Shot 2024-02-13 at 7 00 54 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/94bd6871-a28d-4a40-bf42-6046cc068021">

Best regards,
The LeetCode Team
