### ISSUE TITLE
242. Valid Anagram testcase 33 is buggy

### ISSUE THREAD

**Issue by rafawendel** [LeetCode-Feedback/LeetCode-Feedback#20235]
### LeetCode Username
[rafawendel](https://leetcode.com/rafawendel)

### Problem number, title, and link
[242. Valid Anagram](https://leetcode.com/problems/valid-anagram/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

For some reason my solution (which is experimental and dumb) failed the test suite whereas passing the test on the "Use Testcase" runtime. As far as I know it should pass, though.

### Language used for code
Python3

### Code used for Submit/Run operation

```python3
class Anagramable:
    __map__ = {}

    def __init__(self, s: str):
        for c in s:
            if c in self.__map__:
                self.__map__[c] += 1
            else: self.__map__[c] = 1

    def decrement(self, char: str):
        if self.__map__[char] == 0: raise Exception('Not allowed')
        self.__map__[char] -= 1


class Solution:
    def isAnagram(self, s: str, t: str) -> bool:
        if len(s) != len(t): return False
        an = Anagramable(s)
        for c in t:
            try: an.decrement(c)
            except: return False
        return True
```

### Expected behavior

I think either it should pass or its results be consistent

### Screenshots

<img width="1715" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/44540213/c172068c-56ec-450a-a1f5-2c5e2e39ee36">

### Additional context

From a print I added, it seems like my map is not being reset between runs.

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
