### ISSUE TITLE
面试题 05.04. 下一个数缺失测试用例

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#2023]
**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
「[面试题 05.04. 下一个数](https://leetcode-cn.com/problems/closed-number-lcci/)」的输入参数的取值范围是 `1 <= num <= 2147483647`，因此 `num` 的最大值可以取到 2147483647，最大值作为边界情况必须在测试用例中出现。实际上，最大值并没有在测试用例中出现，导致下面的代码对于 `num` 的值为 2147483647 的情况会超时，但是可以提交通过。
实际上，这道题目前只有 30 个测试用例，我认为是明显不够的。
由于这道题的输入参数是 `int` 型且明确是正整数，因此最理想的情况是将 2147483647 个正整数都作为的测试用例，只有当 2147483647 个正整数都能测试通过时才能提交通过。如果认为 2147483647 个正整数太多，则可以使用有限的关键测试用例，边界情况必须在测试用例中出现。

**你使用的语言**
Java

**你提交或者运行的代码**
```
class Solution {
    public int[] findClosedNumbers(int num) {
        int bitCount = Integer.bitCount(num);
        int greater = num + 1, smaller = num - 1;
        while (greater < Integer.MAX_VALUE) {
            if (Integer.bitCount(greater) == bitCount)
                break;
            greater++;
        }
        if (greater == Integer.MAX_VALUE)
            greater = -1;
        while (smaller > 0) {
            if (Integer.bitCount(smaller) == bitCount)
                break;
            smaller--;
        }
        if (smaller == 0)
            smaller = -1;
        int[] numbers = {greater, smaller};
        return numbers;
    }
}
```

**期望行为**
增加测试用例：输入为 2147483647，对于其他情况，如果可能，应增加更多的测试用例。

**屏幕截图**
![image](https://user-images.githubusercontent.com/12067364/104795156-339e3400-57e7-11eb-820e-0a29d598a69a.png)

**额外的上下文**

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前该题已添加测试用例， ID：stormsunshine 给予积分奖励，请查收。
