### ISSUE TITLE
Wrong description - 610. Triangle Judgement

### ISSUE THREAD

**Issue by PSwicarz** [LeetCode-Feedback/LeetCode-Feedback#20236]
### LeetCode Username
piocarz

### Problem number, title, and link
610. Triangle Judgement

### Category of the bug
- [x ] Problem description

### Description of the bug
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/99476222/54c36ea9-2b57-449b-89ff-1b81c128514c)
Description clrearly states that result order doesnt matter, but it clrearly does when you sort result.

### Language used for code
pandas

### Code used for Submit/Run operation
```
import pandas as pd
import numpy as np

def triangle_judgement(df: pd.DataFrame) -> pd.DataFrame:
    return df.assign(triangle=np.where(df.eval("(x<y+z)&(y<x+z)&(z<x+y)"),"Yes","No")).sort_values("x")
```

### Expected behavior
order of returned df shoudln't matter, as stated in description

### Screenshots
with sortiing:
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/99476222/8c13ad93-63de-450f-8a5b-79399d4b1be6)

without sorting:
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/99476222/9591646e-19b1-4113-90a1-1605417de20b)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
