### ISSUE TITLE
面试题 10.01. 合并排序的数组需要更改题目描述和增加进阶要求

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#2024]
**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
这道题的官方题解的方法一成立的条件是 `A.length == m + n`，而不是 `A.length >= m + n`，因为当 `A.length > m + n`  时，方法一的做法是不行的。因此题目描述需要更改，明确说明 `A.length == m + n`，而不是简单地描述 `A` 的末端有足够的缓冲空间。
另外这道题需要有进阶要求，因为面试的时候可能面试官要求不允许直接合并然后排序，而是需要利用两个数组已经有序的特点进行合并，复杂度比直接合并然后排序更低。
这道题和主站第 88 题是相同的，之前提过第 88 题的 issue：#1920 ，可以和这个 issue 一起处理。
这道题除了按照第 88 题的 issue 一样进行更新之外，还需要说明这道题的描述和书上原题的描述有所区别。
中文描述和英语描述需要同步更新。

**你使用的语言**
Java

**你提交或者运行的代码**

**期望行为**
同 #1920 ，两道题需要同步更新。这道题还需要说明这道题的描述和书上原题的描述有所区别。

**屏幕截图**

**额外的上下文**

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前该题目已调整更新，力扣会定期更新，保障稳定和体验优化。
