### ISSUE TITLE
Solution Not Optimized : 647 Palindromic Substrings

### ISSUE THREAD

**Issue by abhishekwebcode** [LeetCode-Feedback/LeetCode-Feedback#20243]
### LeetCode Username 
mathur17021play

### Problem number, title, and link
Problem: 647. Palindromic Substrings
Link: https://leetcode.com/problems/palindromic-substrings/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [X] Editorial
- [ ] Programming language support

### Description of the bug

In the second approach of the editorial for the problem https://leetcode.com/problems/palindromic-substrings/solution/ i.e. Dynamic Programming,
For C++ code on Line number 6,
There is a check on the string size with operator <= , since in C++ string length can never be negative  , it should be == instead
Both versions still pass all test cases upon submit, but I believe the editorial should be as good as possible and suggest best practices.

### Language used for code

C++

### Code used for Submit/Run operation

```
class Solution {
 public:
    int countSubstrings(string s) {
        int n = s.size(), ans = 0;

        if (n == 0)
            return 0;

        bool dp[n][n];
        fill_n(*dp, n * n, false);

        // Base case: single letter substrings
        for (int i = 0; i < n; ++i, ++ans)
            dp[i][i] = true;

        // Base case: double letter substrings
        for (int i = 0; i < n - 1; ++i) {
            dp[i][i + 1] = (s[i] == s[i + 1]);
            ans += dp[i][i + 1];
        }

        // All other cases: substrings of length 3 to n
        for (int len = 3; len <= n; ++len)
            for (int i = 0, j = i + len - 1; j < n; ++i, ++j) {
                dp[i][j] = dp[i + 1][j - 1] && (s[i] == s[j]);
                ans += dp[i][j];
            }

        return ans;
    }
};
```

### Expected behavior

The editorial should use == operator for C++ solution
``` 
if (n == 0) 
    return 0;
```

### Additional context

You can see the optimized version of the code runs correctly at https://leetcode.com/submissions/detail/1171204020/

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by abhishekwebcode** [comment]
Hi @LC-Pam,
It seems you have fixed this one too , I sent a similar issue for the same exact issue for java language here  [This issue is for C++ language ]
https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/20242
Please close this issue and mark it as resolved and completed
Thanks,
Abhishek
