### ISSUE TITLE
Missing Test Case - 647. Palindromic Substrings

### ISSUE THREAD

**Issue by Ujjwal-2910** [LeetCode-Feedback/LeetCode-Feedback#20241]
### LeetCode Username

ujjwalagrawal29102001

### Problem number, title, and link

647: Palindromic Substrings
https://leetcode.com/problems/palindromic-substrings/

### Category of the bug
- [ ] Problem constraints

### Description of the bug

This question has constraints of `0 <= n <= 1000`, which means it should give TLE for `O (n^3)`. 

### Language used for code

`C++`

### Code used for Submit/Run operation

```
class Solution {
    bool pali(string s)
    {
        for(int i = 0, j = s.size() - 1; i < j; i++, j--)
            if(s[i] != s[j])
                return false;
        return true;
    }
public:
    int countSubstrings(string s) {
        int n = s.size();
        int count = 0;
        for(int i = 0; i < n; i++)
        {
            for(int j = 1; j <= n - i; j++)
            {
                if(pali(s.substr(i, j)))
                    count++;
            }
        }
        return count;
    }
};
```

### Expected behaviour

My test case contribution for this problem will be "aaaa......(1000 times)". The code I gave above, is working fine even if it's `O (n^3)`, whereas it should have given TLE.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
