### ISSUE TITLE
面试题 16.01. 交换数字的英语题目描述需要更新

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#2025]
**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
「[面试题 16.01. 交换数字](https://leetcode-cn.com/problems/swap-numbers-lcci/)」的英语描述，variables 中间多了一个空格，请把空格去掉，使得这是一个单词。

**你使用的语言**
Java

**你提交或者运行的代码**

**期望行为**
更新英语题目描述，去掉空格。

**屏幕截图**
![image](https://user-images.githubusercontent.com/12067364/104796625-c8f2f580-57f2-11eb-933e-50cc2141002a.png)

**额外的上下文**

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前该题的英文描述已更新。关于当前书上的题很多英文单词被空格截断的优化已在我们的计划队列之内，但这可能需要一段时间进行处理，还请耐心等待，如有更多反馈和建议请与我们联系。
