### ISSUE TITLE
面试题 16.06. 最小差题目描述有误

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#2026]
**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
面试题 16.06. 最小差的提示部分的最后一点是：正确结果在区间[-2147483648, 2147483647]内。
由于这道题要求计算的是**最小的绝对值差**，因此结果一定是非负数，应为：正确结果在区间[0, 2147483647]内。
中文描述和英语描述需要同步更新最后一点提示。

**你使用的语言**
Java

**你提交或者运行的代码**

**期望行为**
更新提示部分。

**屏幕截图**

**额外的上下文**

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by lc-kay** [comment]
@stormsunshine @feiceh Please provide the link to this problem on leetcode.com/ Thank you!

**Comment by stormsunshine** [comment]
Hi @lc-kay ,
This problem [面试题 16.06. Smallest Difference LCCI](https://leetcode-cn.com/problems/smallest-difference-lcci/) is only in LCCN, not in LCUS. I do not know why the label LCUS was added. In fact, this issue has nothing to do with LCUS.

**Comment by feiceh** [comment]
你好，当前该题中英文题面已调整更新，力扣会定期更新，保障稳定和体验优化。
