### ISSUE TITLE
Missing Test Case - 3036. Number of Subarrays That Match a Pattern II

### ISSUE THREAD

**Issue by hrishavratan** [LeetCode-Feedback/LeetCode-Feedback#20266]
### LeetCode Username

hrishavratan

### Problem number, title, and link

[3036. Number of Subarrays That Match a Pattern II](https://leetcode.com/problems/number-of-subarrays-that-match-a-pattern-ii/)

### Category of the bug
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

It expects 0 as answer for testcase when 
nums =[110,105,98,99,98,97,98,97,96,95,94,94,93,92,91]
pattern =[0,0,-1,-1,-1,-1,1,0,-1,-1,-1,0,-1,0]
### Language used for code
C++

### Code used for Submit/Run operation

```
class Solution {
public:
    vector<int> rabin_karp(string const& s, string const& t) {
        const int p = 31; 
        const int m = 1e9 + 21;
        int S = s.size(), T = t.size();

        vector<long long> p_pow(max(S, T)); 
        p_pow[0] = 1; 
        for (int i = 1; i < (int)p_pow.size(); i++) 
            p_pow[i] = (p_pow[i-1] * p) % m;

        vector<long long> h(T + 1, 0); 
        for (int i = 0; i < T; i++)
            h[i+1] = (h[i] + (t[i] - 'a' + 1) * p_pow[i]) % m; 
        long long h_s = 0; 
        for (int i = 0; i < S; i++) 
            h_s = (h_s + (s[i] - 'a' + 1) * p_pow[i]) % m; 

        vector<int> occurrences;
        for (int i = 0; i + S - 1 < T; i++) {
            long long cur_h = (h[i+S] + m - h[i]) % m;
            if (cur_h == h_s * p_pow[i] % m)
                occurrences.push_back(i);
        }
        return occurrences;
    }
    
    int countMatchingSubarrays(vector<int>& nums, vector<int>& pattern) {
        int n = nums.size(), m = pattern.size();
        vector<int> v(n - 1);
        string s;
        for (int i = 0; i < n - 1; i++) {
            if (nums[i] < nums[i+1]) v[i] = 1;
            else if (nums[i] > nums[i+1]) v[i] = -1;
            s += v[i] + 'b';
        }
        
        string t;
        for (int x : pattern) t += char(x + 'b');
        return size(rabin_karp(t, s));
    }
};
```

### Expected behavior

0

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team

**Comment by hrishavratan** [comment]
> Thank you for your time.
> 
> Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.
> 
> If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!
> 
> Best regards, The LeetCode Team

Thanks,I hope u would have corrected part1 of same question which differs just by size of input
3034. Number of Subarrays That Match a Pattern I
