### ISSUE TITLE
Wrong Test Case - 122. Best Time to Buy and Sell Stock II

### ISSUE THREAD

**Issue by bensaadi** [LeetCode-Feedback/LeetCode-Feedback#20261]
Test case: [7,1,5,3,6,4]
Max profit should be 8, but it's expected by the test to be 7:
Buy at 1 and hold it, buy at 3, then sell both at 6.

But for the test case [3,3,5,0,0,3,1,4],
Max profit is indeed 8, as expected by the test:
Buy at 0 and hold it, buy at 0 next day, then sell both at 4.

This is inconsistent if we want to optimize globally as the prompt asks.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.


Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team
