### ISSUE TITLE
Typo in Hint #1 for 1463. Cherry Pickup II

### ISSUE THREAD

**Issue by Y-Rov** [LeetCode-Feedback/LeetCode-Feedback#20269]
### LeetCode Username

[anacondrai](https://leetcode.com/anacondrai/)

### Problem number, title, and link

[1463. Cherry Pickup II](https://leetcode.com/problems/cherry-pickup-ii/)

### Category of the bug
- [ ] Problem hints

### Description of the bug

Hello, LeetCode team 😄

The Hint 1 looks like:

> Use dynammic programming, define DP[i][j][k]: The maximum cherries that both robots can take starting on the ith row, and column j and k of Robot 1 and 2 respectively.

The word "dynamic" has a typo.

### Expected behavior

The corrected sentence should look like this:
> Use dynamic programming, define DP[i][j][k]: The maximum cherries that both robots can take starting on the i<sup>th</sup> row, and column j and k of Robot 1 and 2 respectively.

### Screenshots

![Dynamic_Typo](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73534920/bed1f4fc-8854-4c31-bb40-cd76e5d35f6b)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team

**Comment by Y-Rov** [comment]
Hi @LC-Pam, everything is correct, thank you ;)

![Dynamic_Corrected](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73534920/6daea901-9f8b-4b0d-a11b-8547e637bdac)
