### ISSUE TITLE
最好的三家酒庄示例问题

### ISSUE THREAD

**Issue by Echlorine** [LeetCode-Feedback/LeetCode-Feedback#20262]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

### LeetCode 用户名

cmite

### 问题号码、标题和链接
2991. 最好的三家酒庄 https://leetcode.cn/problems/top-three-wineries/description/

### Bug 类型
- [ ] 示例

### 描述

示例中表的名称为`Sessions`，实际表的名称为`Wineries`

### 你使用的语言

MySQL

### 你提交或者运行的代码

```
# Write your MySQL query statement below
with t as (
    select *, dense_rank() over(partition by country order by pts desc, winery) rk from (
        select id, country, sum(points) pts, winery from Wineries group by 2,4
    ) temp
)
select
    country,
    group_concat(if(rk=1, concat(winery, ' (', pts, ')'), null)) top_winery,
    ifnull(group_concat(if(rk=2, concat(winery, ' (', pts, ')'), null)), 'No second winery') second_winery,
    ifnull(group_concat(if(rk=3, concat(winery, ' (', pts, ')'), null)), 'No third winery') third_winery
from t
group by 1
;
```

### 屏幕截图

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/41510511/d0df50d7-f839-4cc2-b60d-4436c6e111cd)

### 额外的上下文

仅仅是示例中的表名称显示错误，暂无其他问题。

**Comment by amcones-lc** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by Echlorine** [comment]
> 你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

你好，[个性域名](https://leetcode.cn/u/cmite/)

**Comment by amcones-lc** [comment]
已奖励
