### ISSUE TITLE
Missing Test Case - 15. 3Sum

### ISSUE THREAD

**Issue by hacker-kun** [LeetCode-Feedback/LeetCode-Feedback#20260]
### Category of the bug

- [x] Missing test Case 

### Description of the bug
Incorrect/Inefficient Code getting accepted because of missing test cases

### Language used for code
C++ 

### Code used for Submit/Run operation

```
class Solution {
public:
    vector<vector<int>> threeSum(vector<int>& nums) {
        vector<vector<int>> result;
        int n = nums.size();

        // Sort the array to simplify the two-pointer approach
        sort(nums.begin(), nums.end());

        for (int i = 0; i < n - 2; ++i) {
            // Skip duplicates
            if (i > 0 && nums[i] == nums[i - 1])
                continue;

            int left = i + 1;
            int right = n - 1;

            while (left < right) {
                int sum = nums[i] + nums[left] + nums[right];

                if (sum == 0) {
                    result.push_back({nums[i], nums[left], nums[right]});

                    // Skip duplicates
                    while (left < right && nums[left] == nums[left + 1])
                        left++;
                    while (left < right && nums[right] == nums[right - 1])
                        right--;

                    left++;
                    right--;
                } else if (sum < 0) {
                    left++;
                } else {
                    right--;
                }
            }
        }

        return result;
    }
};

```

### Expected behavior
In the case where the input array nums = [0, 0, 0, 0, 0, 0, 0], the output should contain a single triplet [0, 0, 0].
instead the output was [[0,0,0],[0,0,0],[0,0,0]].
BUT the code was accepted without this test case.
Even if i don't use skip duplicates in the inner loop the submission is accepted which is a wrong behavior.

### Screenshots
My Test case 
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/86187199/4cc0e925-fc55-4bc3-9fdc-1b31e64604fb)
My test case failed 
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/86187199/75ace9b2-ce3a-462d-b273-99fbd4f33ec9)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for bringing your feedback to our attention. We've conducted a thorough investigation into the issue you raised, and after careful examination, our findings affirm that our judge is working correctly.

We appreciate the time and effort you've invested in sharing your feedback. It's invaluable to us as we work towards maintaining a high-quality platform.

Feel free to continue the dialogue here or provide any additional insights. We value your input and strive to create a collaborative space for improvement.

Best regards,
The LeetCode Team
