### ISSUE TITLE
面试题 17.22. 单词转换英语题目描述需要更新

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#2027]
**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
「[面试题 17.22. 单词转换](https://leetcode-cn.com/problems/word-transformer-lcci/)」的英语描述，原文是：
If there are more that one sequence, any one is ok.
原文至少有两处错误，一是there are应为there is，二是that应为than。
这句话的正确表述应该是：
If there is more than one sequence, return any of them.
请更新英语描述。

**你使用的语言**
Java

**你提交或者运行的代码**

**期望行为**
更新英语题目描述。

**屏幕截图**

**额外的上下文**

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by lc-kay** [comment]
@stormsunshine @feiceh Please provide the link to the problem on leetcode.com/ Then, I will relay this to our team to investigate. Thank you!

**Comment by stormsunshine** [comment]
Hi @lc-kay ,
This problem [面试题 17.22. Word Transformer LCCI](https://leetcode-cn.com/problems/word-transformer-lcci/) is only in LCCN, not in LCUS. I do not know why the label LCUS was added. In fact, this issue has nothing to do with LCUS.

**Comment by feiceh** [comment]
你好，当前该题英文题目描述已更新，力扣会定期更新，保障稳定和体验优化。
