### ISSUE TITLE
1203. 项目管理中文描述有误

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#2028]
**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
中文描述的「接手」一词容易被误解。Issue #1983 的作者就是被「接手」一词误解，以为「无人接手」的项目一定要被 `m` 个小组之一接手。
这是翻译的问题。英语描述第一段、中文描述前两段应该对应如下翻译：
> 有 `n` 个项目，每个项目或者不属于任何小组，或者属于 `m` 个小组之一。`group[i]` 表示第 `i` 个小组所属的小组，如果第 `i` 个项目不属于任何小组，则 `group[i]` 等于 `-1`。项目和小组都是从零开始编号的。可能存在小组不负责任何项目，即没有任何项目属于这个小组。
请更新中文描述。

**你使用的语言**
Java

**你提交或者运行的代码**

**期望行为**
更新中文描述，含义应准确。

**屏幕截图**

**额外的上下文**

**Comment by feiceh** [comment]
感谢反馈，当前按建议进行了修改。
