### ISSUE TITLE
1075: Error on Testcases

### ISSUE THREAD

**Issue by Erwan-BR** [LeetCode-Feedback/LeetCode-Feedback#20297]
### LeetCode Username
**Erwan-Br**

### Problem number, title, and link
1075. Project Employees 1: https://leetcode.com/problems/project-employees-i/

### Category of the bug
- [x] Problem description
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### Description of the bug
The description states that 'It's guaranteed that experience_years is not NULL.', but one the the test case (the 9th) at least contains experience_years NULL.

### Language used for code
MySQL

### Code used for Submit/Run operation

``` MySQL
SELECT
    p.project_id,
    ROUND(SUM(e.experience_years) / COUNT(p.employee_id), 2) as average_years
FROM
    Project p
JOIN
    Employee e
ON
    p.employee_id = e.employee_id
GROUP BY
    p.project_id
```

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/119836222/15e8b0b4-5fda-48ba-8b15-27b07284d51a)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/119836222/0a4fdb71-75cd-464e-b702-b708cf5dea4c)

### Additional context
Just delete the TC or remove the 'null' value.

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
