### ISSUE TITLE
1425: Use `subsequence` instead of `subset`

### ISSUE THREAD

**Issue by ayan-b** [LeetCode-Feedback/LeetCode-Feedback#203]
**What kind of the bug**
- [ ] problem
- [ ] solution
- [x] language

**Describe the bug**
In the problem statement:
> A subset of an array is obtained by deleting some number of elements (can be zero) from the array, leaving the remaining elements in their original order.

This is the definition of subsequence. In a subset, the order may not be maintained ([more details](https://stackoverflow.com/questions/26568560/difference-between-subarray-subset-subsequence)).

**Expected behavior**
In the problem statement, `subset` should be replaced by `subsequence`. The name of the problem should be changed as well.

Leetcode handle: hello_wrld

**Comment by CooperCooperCooper** [comment]
Hi @ayan-b,
Thank you for reaching out to us. I've relayed your feedback to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @
Thank you for your time. We've used your feedback to update the problem, which now has a [different URL](https://leetcode.com/problems/constrained-subsequence-sum/). Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
