### ISSUE TITLE
Missing test case - 224. Basic Calculator

### ISSUE THREAD

**Issue by appi147** [LeetCode-Feedback/LeetCode-Feedback#20309]
### LeetCode Username

appi147

### Problem number, title, and link

[224. Basic Calculator](https://leetcode.com/problems/basic-calculator/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

User is able to solve the solution by hardcoding for specific testcase. Add more test cases so that it can not be hard coded

### Language used for code

Python

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
class Solution:
    def calculate(self, s: str) -> int:
        stack = [1, 1]
        curr_val = 0
        total = 0
        i = 0
        # s = "".join(s.split(" "))
        s = s.replace('(-', '(0-')
        while i < len(s):
            if s[i] == " ":
                i += 1
                continue
            if s[i] == '(':
                stack.append(stack[-1])
            elif s[i] == ')':
                stack.pop()
            elif s[i] == '+':
                stack.append(stack[-1])
            elif s[i] == '-':
                stack.append(-1 * stack[-1])
            else:
                c = 0
                while i < len(s) and s[i].isdigit():
                    c = 10*c + int(s[i])
                    i += 1
                sign = stack.pop()
                total += sign * c
                continue
            i += 1
        return total
```

### Expected behavior

The above code gets accepted. But it should fail on test case:
`-( -2)+4`

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/32510534/4b9871ed-588b-43b3-8922-d185100492ec)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/32510534/ba163397-74ef-458c-b559-08b2963fd86a)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
