### ISSUE TITLE
Missing Test Case - 169. Majority Element

### ISSUE THREAD

**Issue by Tudor67** [LeetCode-Feedback/LeetCode-Feedback#20304]
### LeetCode Username

[Tudor67](https://leetcode.com/Tudor67/)

### Problem number, title, and link

[169. Majority Element](https://leetcode.com/problems/majority-element/)

### Category of the bug
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

My (inefficient) solution passed all test cases and was accepted,
but I found one test case that exceeds the time limit (TLE).

__*Input:*__
```
[1,1,1,1,1, ..., 1,1,1]
```
The input vector `nums` contains `50 000` elements equal to `1`;

__*Output:*__ `Time Limit Exceeded`
__*Expected:*__ `1`
**_Test File (.txt)_**: [test.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/14248014/test.txt)

### Language used for code

C++

### Code used for Submit/Run operation

[Submission Link](https://leetcode.com/problems/majority-element/submissions/1173238005/)
```C++
class Solution {
public:
    int majorityElement(vector<int>& nums) {
        const int N = nums.size();
        const int K = N / 2;

        srand(time(nullptr));

        int L = 0;
        int R = N - 1;
        while(L < R){
            int randIdx = L + rand() % (R - L + 1);
            swap(nums[randIdx], nums[R]);

            int pivot = nums[R];
            int i = L;
            int j = R - 1;
            while(i <= j){
                if(nums[i] < pivot){
                    i += 1;
                }else{
                    swap(nums[i], nums[j]);
                    j -= 1;
                }
            }

            swap(nums[i], nums[R]);
            int pivotIdx = i;

            if(pivotIdx == K){
                L = K;
                R = K;
            }else if(pivotIdx < K){
                L = pivotIdx + 1;
            }else{
                R = pivotIdx - 1;
            }
        }

        return nums[K];
    }
};
```

### Expected behavior

Time Limit Exceeded

### Screenshots

![Prob_169_TLE](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/12481060/96c6dc97-8810-4101-8a29-9db6b1245c52)

### Additional context

**--- Problem (Slow QuickSelect [partition subarray into 2 subarrays])---**
When the input vector `nums` of size `N` contains N equal elements, the above solution runs in `O(N^2)` time.
Why?
* At each partition of `nums[L .. R]` we select as random pivot the majority element (because nums[0] == ... == nums[N - 1]) and reduce the search space from `nums[L .. R]` to `nums[L + 1 .. R]`;
* We need (N / 2) partitions (`nums[0 .. N - 1]` => `nums[1 .. N - 1]` => ... => `nums[N / 2 .. N - 1]`);
* Time complexity of (N / 2) partitions is `O(N + (N - 1) + (N - 2) + ... + (N / 2))` = `O(N^2)`;

**--- Solution (Fast QuickSelect [partition subarray into 3 subarrays])---**
One way of solving the above problem is to partition the array into 3 subarrays such that:
* elements less than pivot x are in the left subarray;
* elements equal to pivot x are in the middle subarray;
* elements greater than pivot x are in the right subarray.

With this approach we catch in the middle subarray all elements equal to pivot x and avoid later redundant partitions around pivot x.

The time complexity of the modified solution is `O(N)`:
* for input vectors with `equal elements`;
* for input vectors with `few distinct elements` and `many duplicates`.

The modified solution (that passes all test cases): [Submission Link (Fast Quick Select)](https://leetcode.com/problems/majority-element/submissions/1173255588/)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
