### ISSUE TITLE
Problem description - 10. Regular Expression Matching

### ISSUE THREAD

**Issue by eshaanrathi2** [LeetCode-Feedback/LeetCode-Feedback#20312]
### Problem number, title, and link
10. Regular Expression Matching https://leetcode.com/problems/regular-expression-matching/description/

### Category of the bug
- [x] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
Description is missing information about optional matching of characters and misleading to users. Following test case can be added to make it clearer:
ab*c matches "ac", "abc", "abbc", "abbbc", and so on.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

A detailed explanation about why you think the following test case can be added to make it clearer:
ab*c matches "ac", "abc", "abbc", "abbbc", and so on."

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team
