### ISSUE TITLE
347. Top K Frequent Elements - Solution - Approach 2 

### ISSUE THREAD

**Issue by yang203000** [LeetCode-Feedback/LeetCode-Feedback#2031]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

In Approach 2: Quickselect , article says `That's why we choose Hoare's Partition here.`, but in the code it's actually using `Lomuto's partition`, which keeps moving smaller elements to the left, contradict to article. The discussion mentions this contradiction.

**Comment by lc-kay** [comment]
Hi @yang203000 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @yang203000 
Thank you for your time. Our team is modifying the article to correctly refer to the partition algorithm as Lomuto's. We should have this done in a few days :)

**Comment by pritamy8062** [comment]
its 2024  and still not done .

**Comment by shyamkawale** [comment]
What's the status of this issue @lc-kay ?
