### ISSUE TITLE
Leetcode website it's not rendering / working properly

### ISSUE THREAD

**Issue by viniciusteixeiradias** [LeetCode-Feedback/LeetCode-Feedback#20326]
### LeetCode Username
viniciusteixeiradias

### Problem number, title, and link
https://leetcode.com/problemset/

### Category of the bug
- [X] Website

### Description of the bug
For some reason after no updates on my machine the leetcode web site stop to work as expected. My main browser is Google Chrome (yes I know...), I used to use it since I started on leetcode and have never had this problem before. When I open the leetcode web site on Safari it's working normal. I will attach a screenshot with console enable and you can see the error that it's happening.

The website on some pages works and shows that I'm logged in, but I am not on other pages, it doesn't make sense :/.

Not working:
- https://leetcode.com/problemset/
- https://leetcode.com/contest/

Working:
- https://leetcode.com/explore/
- https://leetcode.com/discuss/interview-question?currentPage=1&orderBy=hot&query=
- https://leetcode.com/store/

### Expected behavior
I want to be able to keep studying and solving my daily puzzles.

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/69281620/03159a67-276b-44bd-8abe-bcc963125b8b)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/69281620/23016537-5e9c-4bdf-b303-159378dd3fdd)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/69281620/6769f743-edf8-418c-9c8d-cc9166f50fc0)

**Comment by LC-Pam** [comment]
Hello,

Thank you for providing your feedback.

Please note that our GitHub repository primarily addresses content and solution-related issues. To ensure a prompt response and effective resolution for feature, function, course access, or product-related feedback, we kindly encourage you to submit such inquiries through our Zendesk Support Channel:

[LeetCode Support](https://leetcode.com/support)

Our dedicated support agents typically respond within 24 hours and promptly report submitted issues to the appropriate departments for investigation.

We greatly appreciate your ongoing support and value your contributions to enhancing the LeetCode experience.

Best regards,
LeetCode Support Team
