### ISSUE TITLE
 2251. Number of Flowers in Full Bloom

### ISSUE THREAD

**Issue by Uttam-Paharia** [LeetCode-Feedback/LeetCode-Feedback#20324]
---
name: Bug report (English)
about: Create a bug report to help us improve our content.
title: ''
labels: ''
assignees: ''

---

### LeetCode Username

Uttam_Paharia

### Problem number, title, and link

2251. Number of Flowers in Full Bloom {https://leetcode.com/problems/number-of-flowers-in-full-bloom/description/}

### Category of the bug

- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

Code getting accepted on test case where it should get TLE on given constrains.

### Language used for code
C++ 

### Code used for Submit/Run operation

```
class Solution {
public:
    vector<int> fullBloomFlowers(vector<vector<int>>& flowers, vector<int>& people) {
        vector<int> start;
        vector<int> stop;
        for(int i=0;i<flowers.size();i++)
        {
            start.push_back(flowers[i][0]);
            stop.push_back(flowers[i][1]);
        }
        sort(start.begin(),start.end());
        sort(stop.begin(),stop.end());
        for(int i=0;i<people.size();i++)
        {
            int k=ss(people[i],start);
            int e=se(people[i],stop);
            people[i]=k-e;
        }
        return people;
    }
    int ss(int a, vector<int> &v)
    {
        int left=0;
        int right=v.size()-1;
        int mid;
        int prev=-1;
        while(left<=right)
        {
            mid=(right-left)/2+left;
            if(v[mid]>a)
            {
                right=mid-1;
            }
            else
            {
                left=mid+1;
                prev=mid;
            }
        }
        return prev+1;
    }
    int se(int a, vector<int> &v)
    {
        int left=0;
        int right=v.size()-1;
        int mid;
        int prev=-1;
        while(left<=right)
        {
            mid=(right-left)/2+left;
            if(v[mid]>=a)
            {
                right=mid-1;
            }
            else
            {
                left=left+1;
                prev=mid;
            }
        }
        return prev+1;
    }
};
```

### Expected behavior

It should get TLE as function se is doing linear search instead of binary search but it got accepted

### Screenshots

![alt text](<Screenshot from 2024-02-13 16-44-41.png>)

### Additional context
[test.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/14260720/test.txt)
[test2.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/14260733/test2.txt)
test.txt is for people case and test2.txt is for flowers

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

We can't add the test case currently because of technical issues.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
