### ISSUE TITLE
1729: Missing TC

### ISSUE THREAD

**Issue by Erwan-BR** [LeetCode-Feedback/LeetCode-Feedback#20327]
### LeetCode Username
Erwan-Br

### Problem number, title, and link
1729. Fond Followers Count https://leetcode.com/problems/find-followers-count/

### Category of the bug
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug
It's asked to sort the table by user_id in ascending order, but testing tables are all formed with user_id in ascending order, so no **ORDER BY** is needed.

### Language used for code
MySQL

### Code used for Submit/Run operation
``` MySQL
SELECT
    user_id,
    COUNT(DISTINCT follower_id) as followers_count
FROM
    Followers
GROUP BY
    user_id
```

### Expected behavior
At the end of the code, the following line should be written:

``` MySQL
ORDER BY
	user_id ASC
```

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/119836222/3536a8fa-8258-4300-837e-b7b2cb599049)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
