### ISSUE TITLE
2668. Find Latest Salaries | Editorial showing wrong solution for Database

### ISSUE THREAD

**Issue by DavidZagorski** [LeetCode-Feedback/LeetCode-Feedback#20336]
### LeetCode Username

DavidZagorski

### Problem number, title, and link

2668. Find Latest Salaries https://leetcode.com/problems/find-latest-salaries/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [X] Editorial
- [ ] Programming language support

### Description of the bug

Editorial showing wrong solution for Database

### Language used for code

PostgreSQL

### Code used for Submit/Run operation

```
SELECT
    emp_id,
    firstname,
    lastname,
    MAX(salary) AS salary,
    department_id
FROM Salary
GROUP BY emp_id
ORDER BY emp_id;
```

### Expected behavior

```
SELECT
    emp_id,
    firstname,
    lastname,
    MAX(salary) AS salary,
    department_id
FROM Salary
GROUP BY
  emp_id,
  firstname,
  lastname
  department_id
ORDER BY emp_id;
```

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/33126488/e5edc693-2ea7-4b0c-b80b-f71f5f2ed350)

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
