### ISSUE TITLE
Missing Test Case - 1581. Customer Who Visited but Did Not Make Any Transactions

### ISSUE THREAD

**Issue by zeeaks** [LeetCode-Feedback/LeetCode-Feedback#20337]
### LeetCode Username
        zeeaks

### Problem number, title, and link
       1581. Customer Who Visited but Did Not Make Any Transactions
 (https://leetcode.com/problems/customer-who-visited-but-did-not-make-any-transactions/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
The test case is giving wrong result. I crosschecked the table and the output expected is not correct

### Language used for code
MySQL

### Code used for Submit/Run operation
````
# Write your MySQL query statement below
select v.customer_id, t.cnt as count_no_trans
from Visits as v
right join (
            select count(transaction_id) as cnt, visit_id
            from Transactions
            group by visit_id
            ) as t 
on v.visit_id = t.visit_id
````

### Expected behavior

Expected Correct Output of the above query
| customer_id | count_no_trans |
| ----------- | ----------------- |
| 54               | 3                            |
| 23               | 1                             |
| 9                 | 1                             |

Incorrect test case output

| customer_id | count_no_trans |
| ----------- | ----------------- |
| 30               | 1                            |
| 96               | 1                            |
| 54               | 2                            |

### Screenshots
<img width="1270" alt="Screenshot 2024-02-13 at 6 12 15 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/48651928/68be210d-0dcd-4466-a44f-c4c5a9b53522">

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
