### ISSUE TITLE
Missing Test Case - 1296. Divide Array in Sets of K Consecutive Numbers

### ISSUE THREAD

**Issue by pradeepn28** [LeetCode-Feedback/LeetCode-Feedback#2033]
#### Your LeetCode username

pradeepkalra

#### Category of the bug
- [ ] Question

#### Description of the bug

[1,3,3,4,5] and k=3 has given true for my code and but it should have been false. My code passed all the test cases on leetcode. 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool isPossibleDivide(vector<int>& nums, int k) {
        map<int,int> mp;
        for(int i=0;i<nums.size();i++)
        {
            if(mp.find(nums[i])==mp.end())
            {
                mp[nums[i]]=0;
            }
            mp[nums[i]]++;
        }
        unordered_map<int,int> mp1;
        int sum=0;
        for(auto x:mp)
        {
            if(x.second>sum)
            {
                mp1[x.first+k-1]=(x.second-sum);
                sum=x.second;
            }
            else if(x.second<sum)
            {
                return false;
            }
            if(mp1.find(x.first)!=mp1.end())
            {
                sum-=mp1[x.first];
                mp1.erase(x.first);
            }
            
        }
        return mp1.size()==0;
    }
};
```

#### Expected behavior

[1,3,3,4,5] and k=3 should have returned false for my code but, my code returned true and still passed all test cases. I think you should include this test case.

#### Screenshots

![image](https://user-images.githubusercontent.com/34651761/104813916-12166a00-5832-11eb-8ae5-4994b90b61fb.png)

![image](https://user-images.githubusercontent.com/34651761/104813927-25c1d080-5832-11eb-9acc-a4bd5852dd71.png)

**Comment by lc-kay** [comment]
Hi @pradeepn28 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @pradeepn28 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
