### ISSUE TITLE
Typo in Editorial for 2149. Rearrange Array Elements by Sign

### ISSUE THREAD

**Issue by Y-Rov** [LeetCode-Feedback/LeetCode-Feedback#20346]
### LeetCode Username

[anacondrai](https://leetcode.com/anacondrai/)

### Problem number, title, and link

[2149. Rearrange Array Elements by Sign](https://leetcode.com/problems/rearrange-array-elements-by-sign/)

### Category of the bug
- [x] Editorial

### Description of the bug

Hello, LeetCode team 😄

If we go through the section "Algorithm" in [problem's Editorial](https://leetcode.com/problems/rearrange-array-elements-by-sign/editorial/) and stop at the 3-rd paragraph (algorithm summary, the 1-st item of an ordered list):

> 1. Initialize `n` to the size of `nums`. Initialze `ans` array of size `n`.

The 2-nd word "Initialize" has a typo. 

### Expected behavior

The corrected list item should look like:
> 1. Initialize `n` to the size of `nums`. Initialize `ans` array of size `n`.

### Screenshots

![Initialize_Typo](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73534920/8cc370a2-38d3-4a38-ae95-28393049b12c)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by Y-Rov** [comment]
Hi @LC-Pam, the typo has been corrected; thank you as always :)

![Initialize_Corrected](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73534920/552e145e-8fe9-40d0-9598-454e8a065bec)

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
