### ISSUE TITLE
Missing Test Case - 1502. Can Make Arithmetic Progression From Sequence

### ISSUE THREAD

**Issue by CaptGyrfalcon** [LeetCode-Feedback/LeetCode-Feedback#20342]
### LeetCode Username

Gyrfalcon

### Problem number, title, and link

1502. Can Make Arithmetic Progression From Sequence https://leetcode.com/problems/can-make-arithmetic-progression-from-sequence/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

For some kind of codes, where they compare two integers at the same time, and store integers already present using hash set, they might forget to check if the last element is in the hash set and directly return the outcome. So if the last element of arr[] is repeated, their program might not be able to return the correct answer. However, there's no such test cases to make sure this won't happen.
[1,6,7,2,3,4,4], for example. This should be "false" as return value, however, it returned "true", thus it's a wrong answer, but passed for lack of test case.

### Language used for code

C#

### Code used for Submit/Run operation

```
public class Solution {
    public bool CanMakeArithmeticProgression(int[] arr) {
        int len = arr.Length;
        int min = 9999999;
        int max = -9999999;
        for(int i = 0; i < len; i++)
        {
            min = Math.Min(arr[i], min);
            max = Math.Max(arr[i], max);
        }
        int cha = (max - min) / (len - 1);
        if(cha * (len - 1) != max - min)
        {
            return false;
        }
        if(cha == 0)
        {
            return true;
        }
        HashSet<int> already = new HashSet<int>();
        for(int i = 0; i < len - 1; i++)
        {
            if(Math.Abs(arr[i + 1] - arr[i]) % cha != 0)
            {
                return false;
            }
            if(already.Contains(arr[i]))
            {
                return false;
            }
            already.Add(arr[i]);
        }
        return true;
    }
}
```

### Expected behavior

WA, as mentioned above, [1,6,7,2,3,4,4] should not be passed if it's given in test cases.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
