### ISSUE TITLE
Stackoverflow Error - 230. Kth smallest element in BST using Morris traversal

### ISSUE THREAD

**Issue by adityanithariya** [LeetCode-Feedback/LeetCode-Feedback#20358]
### LeetCode Username
adityanithariya

### Problem number, title, and link
[230. Kth Smallest Element in a BST](https://leetcode.com/problems/kth-smallest-element-in-a-bst/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
[Kth Smallest Element Submission](https://leetcode.com/problems/kth-smallest-element-in-a-bst/submissions/1175017325)
Morris traversal is used to solve kth smallest element, morris traversal taken from submission in [94. Binary Tree Inorder Traversal](https://leetcode.com/problems/binary-tree-inorder-traversal/submissions/1174159905) and condition for kth smallest element is added, but it gives stackoverflow error as follows:
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==21==ERROR: AddressSanitizer: stack-overflow on address 0x7ffe4c3bfff8 (pc 0x558d7e8da769 bp 0x7ffe4c3c0010 sp 0x7ffe4c3c0000 T0)
==21==ABORTING
```

Condition for kth smallest element:
```c++
if (index == k) return curr->val;
else index++;
```

### Language used for code
C++

### Code used for Submit/Run operation
```c++
/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left),
 * right(right) {}
 * };
 */
class Solution {
public:
    int kthSmallest(TreeNode* root, int k) {
        int index = 1;
        TreeNode *curr = root, *pre;
        while (curr) {
            if (curr->left == NULL) {
                if (index == k) return curr->val;
                else index++;
                curr = curr->right;
            } else {
                pre = curr->left;
                while (pre->right != NULL && pre->right != curr)
                    pre = pre->right;

                if (pre->right == NULL) {
                    pre->right = curr;
                    curr = curr->left;
                } else {
                    pre->right = NULL;
                    if (index == k) return curr->val;
                    else index++;
                    curr = curr->right;
                }
            }
        }
        return -1;
    }
};
```

### Expected behavior
Successful submission of code without stackoverflow, as morris traversal uses O(1) stack space and code is directly taken from inorder traversal another working submission for morris traversal.

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/74248365/b01ceeb3-4276-47f1-94d0-dce6a4e59ad0)
It fails on very basic testcase

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team

**Comment by adityanithariya** [comment]
@LC-Pam Similar thing happened earlier, please provide a valid reason for rejecting this issue, I have explained it clearly and this error wasn't supposed to be there, but it is, then its your responsibility to resolve it as I'm not able to submit more optimized code, when logic is absolutely correct and code is taken from another valid solution with a small modification for this problem, please let me know the reason here
