### ISSUE TITLE
Problem description not clear

### ISSUE THREAD

**Issue by shridharGits** [LeetCode-Feedback/LeetCode-Feedback#20366]
### Problem number, title, and link
2149. Rearrange Array Elements by Sign https://leetcode.com/problems/rearrange-array-elements-by-sign/

### Category of the bug
- [x] Problem description

### Description of the bug
The description of the problem says `You should rearrange the elements of nums such that the modified array follows the given conditions:` which seems more like you can not use additional space for rearranging array and have to solve it in-place without help of another array, which is not possible.

### Language used for code
C++ 

### Code used for Submit/Run operation
```
class Solution {
public:
    vector<int> rearrangeArray(vector<int>& nums) {
        vector<int> ans(nums.size(), 0);
        int posp = 0;
        int posn = 1;
        
        for(int i = 0; i<nums.size(); i++)
        {
            if(nums[i]>0)
            {
                ans[posp] = nums[i];
                posp+=2;
            }
            else{
                ans[posn] = nums[i];
                posn+=2;
            }
        }
        nums = ans;
        return nums;
    }
};
```

### Expected behavior
the description of problem should be
`You should return the array of nums such that the the array follows the given conditions:`

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
