### ISSUE TITLE
Missing Test Cases : #8 String to Integer (atoi)

### ISSUE THREAD

**Issue by mr-ayush-agrawal** [LeetCode-Feedback/LeetCode-Feedback#20365]
### LeetCode Username
**Username** : AyushAgr_
**Profile** : [Ayush's LeetCode](https://leetcode.com/AyushAgr_/)

### Problem number, title, and link
8. [String to Integer (atoi)](https://leetcode.com/problems/string-to-integer-atoi/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
There is no test case which checks the bound of the Integers (both lower and upper). 
The input is a string where a number out of the bound limit of Integer can be provided but this should return the Maximum Possible value of Integer or should return answer 0.
On running the example test case the expected output is showing *INT_MAX* or *INT_MIN* depending on situation.

#### Missing Test Cases
- `"2147483648"` which is equals to `2^31`. And all the numbers grater then the provided test case
- `"-2147483649"` which is equals to `-(2^31+1)`. And all the numbers less then the provided test case

### Language used for code
 - C++

### Code used for Submit/Run operation

***This code doesn't checks for the condition if the provided input is more than INT_MAX or less than INT_MIN***

```cpp
class Solution {
public:
    int myAtoi(string s) {
        long long ans =0;
        int neg = 0, pos=0;
        bool ear=false;
        for(int i=0;i<s.length(); i++){
            if((neg==1 && pos==1)||(pos>1)||(neg>1))
                return 0;

            if(ans > INT_MAX)
                break;
            
            if ((!neg) && (!pos) && (!ans) && (s[i]==' ')) {
                if(!ear)
                continue;
                else return 0;
            }
            else if(!ans && s[i] == '-'){
                if(ear)
                    return 0;
                neg ++;
            }
            else if(!ans && s[i] == '+'){
                if(ear)
                    return 0;
                pos++;
            }
            else if(s[i] == ' ')
                break;
            else if(s[i] >= '0' && s[i]<= '9'){
                ear = true;
                ans = ans*10 + (s[i] -'0'); 
            }
            else break;
        }
        return neg ? -ans: ans;
    }
};
```

### Expected behavior
This should check for the condition where `ans > INT_MAX` or `ans<INT_MAX` in the reference of the above code. 

```cpp

        if(ans > INT_MAX){
           return (neg)? INT_MIN : INT_MAX;
        }
```
***This section to be added in correct version of the code above the line before we are returning the ans***

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
