### ISSUE TITLE
Missing Test Case - 23. Merge k Sorted Lists

### ISSUE THREAD

**Issue by ramtulasi19** [LeetCode-Feedback/LeetCode-Feedback#20371]
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [* ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

for the test case `[[0]]` my code is wrong but on submission it was submitted successfully, please include the test case.

### Code used for Submit/Run operation

```
/**
 * Definition for singly-linked list.
 * public class ListNode {
 * int val;
 * ListNode next;
 * ListNode() {}
 * ListNode(int val) { this.val = val; }
 * ListNode(int val, ListNode next) { this.val = val; this.next = next; }
 * }
 */
class Solution {
    public ListNode mergeKLists(ListNode[] lists) {
        Queue<Integer> queue = new PriorityQueue<>();
        for (ListNode n : lists) {
            while (n != null) {
                queue.add(n.val);
                n = n.next;
            }
        }

        ListNode ans = new ListNode();

        ListNode dummy = ans;

        while (!queue.isEmpty()) {
            ans.val = queue.poll();
            if (!queue.isEmpty()) {
                ans.next = new ListNode();
                ans = ans.next;
            }

        }
        return dummy.next == null && dummy.val == 0? null : dummy;
    }

}
```

### Expected behavior

for the test case `[[0]]` the out put what i code gave was wrong but on submitting my code it passed successfully.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
