### ISSUE TITLE
Showing error in right code : Final Value of Variable After Performing Operations

### ISSUE THREAD

**Issue by SumitRaghav876** [LeetCode-Feedback/LeetCode-Feedback#20377]
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

**Comment by SumitRaghav876** [comment]
Code :
class Solution {
    public int finalValueAfterOperations(String[] operations) {
        int x=0;
        for(int i=0; i<operations.length; i++){
            if(operations[i]== "--X" || operations[i]=="X--"){
                x=x-1;
                break;
            }
            else if(operations[i]=="++X" || operations[i]=="X++"){
                x=x+1;
                break;
            }
            else{
                continue;
            }
        }
        return x;
    }
}

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback. We encourage you to share your questions in the discussion forum, where the community can provide insights and assistance.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
