### ISSUE TITLE
Wrong condition in embedded mini-presentation for 2971. Find Polygon With the Largest Perimeter Editorial

### ISSUE THREAD

**Issue by Y-Rov** [LeetCode-Feedback/LeetCode-Feedback#20376]
### LeetCode Username

[anacondrai](https://leetcode.com/anacondrai/)

### Problem number, title, and link

[2971. Find Polygon With the Largest Perimeter](https://leetcode.com/problems/find-polygon-with-the-largest-perimeter/)

### Category of the bug
- [x] Editorial

### Description of the bug

Hello, LeetCode team 😄

If we jump to the end of the section "Intuition" in [problem's Editorial](https://leetcode.com/problems/find-polygon-with-the-largest-perimeter/editorial/) and stop at the mini-presentation of the algorithm (all slides with "Step 2" heading):

> Step 2: Iterate over array and check if sum of previous elements is greater than current element. `if sum >= curr element`, `ans = sum + curr element`

`if sum >= curr element` is a wrong condition.

### Expected behavior

Correct condition will look like this:

`if sum > curr element`

### Screenshots

![Wrong_Condition](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73534920/6b5dcdcb-2745-4bd0-94bd-6fa65ec86112)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by Y-Rov** [comment]
Hi @LC-Pam, the condition is now correct; thx 👍

![Corrected_Condition](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73534920/f312b6e0-6625-402d-8ab7-e2d5dade238c)

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
