### ISSUE TITLE
Missing Test Case - 27. Remove Element

### ISSUE THREAD

**Issue by Muhammad-Rameez-Khan** [LeetCode-Feedback/LeetCode-Feedback#20373]
Problem Description:

Objective: Given an integer array nums and an integer val, the goal is to remove all occurrences of val in nums in-place. After removing these elements, return the number of elements in nums that are not equal to val.

Constraints:
- The order of the elements may be changed.
- The remaining elements of nums after removal of val are not important.
- The size of nums might be larger than the number of elements left after removal of val.

Example:

Input:
nums = [3, 2, 2, 3]
val = 3

Output:
2

Explanation: 
- After removing all occurrences of val (which is 3) from nums, we get [2, 2].
- There are 2 elements in nums that are not equal to val, hence the output is 2.

Solution Overview:

1. Initialize Counter (k): Start with a counter k initialized to 0. This counter will keep track of the number of elements in nums that are not equal to val.

2. Iterate Through nums: Traverse through each element in nums using a loop.

3. Removing val:
   - If the current element is not equal to val, move it to the beginning of nums at position k.
   - Increment the counter k.

4. Return k: After traversing through all elements of nums, return the value of k. This represents the count of elements in nums that are not equal to val.

5. Custom Judge:
   - After calling the removeElement function, check whether the returned value k matches the expected length.
   - Sort the first k elements of nums and compare them with expectedNums.

Bug Fix:

In the custom judge, there's a minor issue in the assertion:
console.log(k === expectedNums.length);
This line just checks if the number of elements returned (k) matches the expected length of expectedNums. It doesn't validate whether the content of nums matches expectedNums.

To fix this, we need to sort nums before comparison:
console.log(JSON.stringify(nums) === JSON.stringify(expectedNums));
This line ensures that the content of nums matches expectedNums.

With this fix, the custom judge now correctly validates both the length and content of nums against expectedNums.

Below is the code 

function removeElement(nums, val) {
    let k = 0; // Initialize k to count elements not equal to value
    
    // and Iterate through each element in nums

    for (let i = 0; i < nums.length; i++) {

        // If the current element is not equal to val

        if (nums[i] !== val) {

            // Move the element to the beginning of nums

            nums[k] = nums[i];

            // Increment k to track the number of elements not equal to val

            k++;
        }
    }
    
    // k represents the number of elements not equal to val

    return k;
}

// Custom Judge:

let nums = [3, 2, 2, 3]; // Input-array

let val = 3; // to Value  remove

let expectedNums = [2, 2]; //  Expected answer with correct length

let k = removeElement(nums, val); // Calls your implementation

console.log(k === expectedNums.length); // Assertion: Check if k is equal to the expected length

// Sort the first k elements of nums

nums = nums.slice(0, k).sort((a, b) => a - b);

console.log(JSON.stringify(nums) === JSON.stringify(expectedNums)); // Assertion: Check if sorted nums matches expectedNums

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.
Details regarding the missing test case.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team
