### ISSUE TITLE
Missing Test Case - 227. Basic Calculator II

### ISSUE THREAD

**Issue by puchm** [LeetCode-Feedback/LeetCode-Feedback#20370]
### LeetCode Username
puchm

### Problem number, title, and link

227. Basic Calculator || https://leetcode.com/problems/basic-calculator-ii/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

There are no test cases for numbers with multiple digits, yet the description says that the range is `[0, 2^31 - 1]`. If you don't have to account for numbers higher than 9 things get easier than they should be.

### Language used for code

TypeScript

### Code used for Submit/Run operation
My code is below, read Expected behavior section for explanation.

```
const numberRegex = /^\d$/
const operatorRegex = /^[*+-/]$/

function calculate(s: string): number {
    const sections: (number | string)[] = [];

    let i = 0;
    while(i < s.length) {
        const char = s[i];
        if(numberRegex.test(char)) {
            let rightEndOfNumber = i;

            while(rightEndOfNumber < s.length && numberRegex.test(s[rightEndOfNumber + 1])) {
                rightEndOfNumber++;
            }

            sections.push(parseInt(s.substring(i, rightEndOfNumber + 1)));
            i = rightEndOfNumber + 1;
        } else if(operatorRegex.test(char)) {
            sections.push(char);
            i++;
        } else {
            // spaces
            i++;
        }
    }

    return calculateArray(sections);
};

function calculateArray(array: (string | number)[]): number {
    // calculate * and /
    for(let i = 1; i < array.length; i++) {
        if(array[i] === '*') {
            // @ts-ignore elements are numbers because the expression is always valid
            array.splice(i - 1, 3, array[i - 1] * array[i + 1])
            i--;
        } else if(array[i] === '/') {
            // @ts-ignore elements are numbers because the expression is always valid
            array.splice(i - 1, 3, Math.floor(array[i - 1] / array[i + 1]))
            i--;
        }
    }

    // calculate + and -
    for(let i = 1; i < array.length; i++) {
        if(array[i] === '+') {
            // @ts-ignore elements are numbers because the expression is always valid
            array.splice(i - 1, 3, array[i - 1] + array[i + 1])
            i--;
        } else if(array[i] === '-') {
            // @ts-ignore elements are numbers because the expression is always valid
            array.splice(i - 1, 3, Math.floor(array[i - 1] - array[i + 1]))
            i--;
        }
    }

    return array[0] as number;
}
```

### Expected behavior

Everything works with my solution, but other insufficient solutions may not work. In the nested while loop around line 13 I am explicitly handling multi-digit numbers, which is necessary according to the description but is not tested for.

### Screenshots
N/A

### Additional context
N/A

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code Accepted  submission link you submitted led to the observed result.


Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team
