### ISSUE TITLE
Missing Test Case - 1207. Unique Number of Occurrences

### ISSUE THREAD

**Issue by Sujgaik2003** [LeetCode-Feedback/LeetCode-Feedback#20379]
### LeetCode Username

sujeet_2003 

### Problem number, title, and link
  
 https://leetcode.com/problems/unique-number-of-occurrences/

### Category of the bug

- [x] Problem constraints
- [x] Programming language support

### Description of the bug
 In Example 2 provided in the problem description, the output is expected to be true because both elements in the array [1,2] are unique. However, the provided code implementation incorrectly returns false. 

### Language used for code
C++

### Code used for Submit/Run operation

Please make sure to wrap the code with ``` tags. 
Otherwise, the issue may be closed without any information.

Replace the code below with your code.

```
// Paste your code here. Don't remove ``` given
// above and below the code.

class Solution {
public:
    bool uniqueOccurrences(vector<int>& arr) {
        int ans=0;
        for(int i=0;i <arr.size();i++){
            ans=ans^arr[i];
            return 1;
        }
        return 0;
    }
};

```

### Expected behavior

The code implementation should correctly determine if the number of occurrences of each value in the array is unique and return true if they are unique, false otherwise. 

### Additional context
The issue seems to be with the logic inside the uniqueOccurrences function. It currently returns true if the first element in the array has a unique number of occurrences, and false otherwise, which is not the intended behavior according to the problem statement. The logic needs to be adjusted to correctly count the occurrences of each element in the array and determine if they are unique..

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
