### ISSUE TITLE
Missing Test Case - 1520. Maximum Number of Non-Overlapping Substrings

### ISSUE THREAD

**Issue by CuteTN** [LeetCode-Feedback/LeetCode-Feedback#20381]
### LeetCode Username
CuteTN

### Problem number, title, and link
1520. Maximum Number of Non-Overlapping Substrings https://leetcode.com/problems/maximum-number-of-non-overlapping-substrings

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
The code below has got accepted while it failed a testcase

### Language used for code
C++

### Code used for Submit/Run operation
```cpp
#define ff first
#define ss second
class Solution {
public:
    vector<string> maxNumOfSubstrings(string s) {
        int n=s.length();
        vector<vector<int>> arr(26,vector<int>(2,-1));
        vector<vector<int>> pre(n+1,vector<int>(26));
        for(int i=0;i<n;i++){
            pre[i][s[i]-'a']++;
            pre[i+1]=pre[i];
            if(arr[s[i]-'a'][0]==-1)arr[s[i]-'a'][0]=i;
            arr[s[i]-'a'][1]=i;
        }
        auto canStart=[&](int i)->int{
            int last=-1;
            if(arr[s[i]-'a'][0]!=i)return last;
            last=arr[s[i]-'a'][1];
            for(int k=0;k<2;k++){
                for(int j=0;j<26;j++){
                    if(arr[j][0]==-1 || s[i]-'a'==j)continue;
                    if(arr[j][0]<i && pre[last][j]-pre[i-1][j])return -1;
                    if(arr[j][0]<i && arr[j][1]>last)continue;
                    if(arr[j][0]<last)last=max(last,arr[j][1]);
                }
            }
            return last;
        };
        
        int prev=-1;
        vector<string> ans;
        for(int i=0;i<n;i++){
            int last=canStart(i);
            if(last==-1)continue;
            if(i>prev){
                prev=last;
                ans.push_back(s.substr(i,last-i+1));
            }else if(i<prev && last<=prev){
                ans.back()=s.substr(i,last-i+1);
                prev=last;
            }
        }
        return ans;
    }
};
```

### Expected behavior
Include this testcase:
```
s = "efehfghcgc"
```

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
