### ISSUE TITLE
Missing Test Case - 203. Remove Linked List Elements

### ISSUE THREAD

**Issue by dengere** [LeetCode-Feedback/LeetCode-Feedback#20386]
### Category of the bug
- [ ] Missing test Case 

### Description of the bug
val defined as int (not uint) so it should have test case with negative number for val specialy with -1. because I see solution as developer set dum data as val=-1.

### Language used for code
C#

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.
Details regarding the missing test case.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team
