### ISSUE TITLE
78. Subset and 90. Subset II problem

### ISSUE THREAD

**Issue by babubhai12345** [LeetCode-Feedback/LeetCode-Feedback#20387]
### LeetCode Username
babubhai

### Problem number, title, and link
78. Subset https://leetcode.com/problems/subsets/description/
90. Subset II https://leetcode.com/problems/subsets-ii/description/ 

### Category of the bug-
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### Description of the bug
In both problem, statement says subsets can be in any order. However test cases enforces that values in subset are sorted

### Language used for code
Golang

### Code used for Submit/Run operation
For problem 78.
```
var result [][]int
func subsets(nums []int) [][]int {
    result = nil 
    var output []int    
    dfs(nums,output)
    return result
}

func dfs(input []int,output []int) {
    if len(input) == 0 {
        result = append(result,output)
        return
    }
    
    dfs(input[1:],output)
    dfs(input[1:],append(output,input[0]))
}
```

For Problem 90: 

```
type Key [21]int
var resultMap map[Key][]int
func subsetsWithDup(nums []int) [][]int {
    resultMap = make(map[Key][]int)
    var output []int    
    dfs(nums,output)
    var result [][]int
    for _,value := range resultMap {
        result = append(result,value)
    }
    return result
}

func addToMap(input []int) {
    var k1 Key
    for _,num := range input {
        k1[num+10] += 1
    }
    if _,found := resultMap[k1]; !found {
        resultMap[k1] = input
    }
}

func dfs(input []int,output []int) {
    if len(input) == 0 {
        addToMap(output)
        return
    }
    
    dfs(input[1:],output)
    dfs(input[1:],append(output,input[0]))
}
```

### Expected behavior
Test case should have passed

### Screenshots
Screenshot of error in Problem 78:
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/153164097/db00f4aa-6037-4a2b-aa13-88ab49952bd3)

Screenshot of error in Problem 90:
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/153164097/8347b0ca-2be1-408a-af87-658a558ca0e7)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

Details regarding the missing test case.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by babubhai12345** [comment]
Sorry, I didn't understand what needs to be shared. Bug is about incorrect result of a test case as mentioned in screenshort attached. 
Expected output has numbers sorted in a slice. However, question doesn't mention that. In description of problem it is written that    answer can be in any order.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

Please send us the missing test case in text format. 

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team
