### ISSUE TITLE
Problem description - 935. Knight Dialer

### ISSUE THREAD

**Issue by CompactSupport** [LeetCode-Feedback/LeetCode-Feedback#20382]
### LeetCode Username

b03201008

### Problem number, title, and link

935. Knight Dialer https://leetcode.com/problems/knight-dialer/

### Category of the bug
- [ ] Problem description

### Description of the bug

There is a typo in the problem description.
The possible movements of chess knight are shown in this **diagaram**:
should be changed to
The possible movements of chess knight are shown in this **diagram**:

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/117230865/d6b074ea-ad6e-4116-a3d9-0349840adeb6)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
