### ISSUE TITLE
Missing Test Case - 1768. Merge Strings Alternately

### ISSUE THREAD

**Issue by ani5151** [LeetCode-Feedback/LeetCode-Feedback#20392]
anindita5151
### LeetCode Username

[1768. Merge Strings Alternately](https://leetcode.com/problems/merge-strings-alternately/)
https://leetcode.com/problems/merge-strings-alternately/submissions/1176429563/?envType=study-plan-v2&envId=leetcode-75
### Category of the bug
- [x] Problem description
- [x] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

You are given two strings word1 and word2. Merge the strings by adding letters in alternating order, starting with word1. If a string is longer than the other, append the additional letters onto the end of the merged string.

Return the merged string.

 

Example 1:

Input: word1 = "abc", word2 = "pqr"
Output: "apbqcr"
Explanation: The merged string will be merged as so:
word1:  a   b   c
word2:    p   q   r
merged: a p b q c r
Example 2:

Input: word1 = "ab", word2 = "pqrs"
Output: "apbqrs"
Explanation: Notice that as word2 is longer, "rs" is appended to the end.
word1:  a   b 
word2:    p   q   r   s
merged: a p b q   r   s
Example 3:

Input: word1 = "abcd", word2 = "pq"
Output: "apbqcd"
Explanation: Notice that as word1 is longer, "cd" is appended to the end.
word1:  a   b   c   d
word2:    p   q 
merged: a p b q c   d
 

Constraints:

1 <= word1.length, word2.length <= 100
word1 and word2 consist of lowercase English letters.

Java
### Code used for Submit/Run operation

```
class Solution {
    public String mergeAlternately(String w1, String w2) {
        int n1= w1.length();
        int n2= w2.length();
        String oStr = null;
        StringBuffer oStrBfr = new StringBuffer();
        int i = 0, j = 0;

        for(int k =0; k<(n1<n2?n2:n1); k++) {
            if((w1.length()-i)!=0) {
                oStrBfr.append(w1.charAt(i));
                i++;
            }
            if((w2.length()-j)!=0) {
                oStrBfr.append(w2.charAt(j));
                j++;
            }
        }
        return oStrBfr.toString();
    }
}
// Paste your code here. Don't remove ``` given
// above and below the code.
```

### Screenshots

Case 1
Case 2
Case 3
Input
word1 =
"abc"
word2 =
"pqr"
Output
"apbqcr"
Expected
"apbqcr"

Case 2
Case 3
Input
word1 =
"ab"
word2 =
"pqrs"
Output
"apbqrs"
Expected
"apbqrs"

Input
word1 =
"abcd"
word2 =
"pq"
Output
"apbqcd"
Expected
"apbqcd"

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

Test cases all already exist. 

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
