### ISSUE TITLE
Leetcode submission output does not match output when run locally

### ISSUE THREAD

**Issue by tybrs** [LeetCode-Feedback/LeetCode-Feedback#204]
**What kind of the bug**
- [ ] problem
- [x] solution
- [ ] language

**Describe the bug**
For problem 1, I get a different output than leetcode submission when I run code locally.

**what language is your code written in**
python3

**The code you submit/run**
```
// Two Sum
def two_sum(nums, target, d={}, i=0):
    if nums[i] in d:
        return [d[nums[i]], i]
    else:
        d[target - nums[i]] = i
        return two_sum(nums, target, d, i+1)

class Solution:
    def twoSum(self, nums: List[int], target: int) -> List[int]:
        return two_sum(nums, target)
```

**Expected behavior**
In a submission report for the following input:
```
[3,3]
6
```
Leetcode reports the output of `[0,0]`. However when I run `two_sum([3,3], 6)` locally it outputs `[0,1]`, the correct answer.

**Screenshots**
![2020-04-27_20-24](https://user-images.githubusercontent.com/1200207/80433545-3bb6ec00-88c5-11ea-8dda-81dfaebdb081.png)

![2020-04-27_20-26](https://user-images.githubusercontent.com/1200207/80433658-7de02d80-88c5-11ea-9c57-bf4f2ed8a217.png)

**Comment by CooperCooperCooper** [comment]
Hi @tybrs,
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in this [support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
