### ISSUE TITLE
Another Solution - 141. Linked List Cycle

### ISSUE THREAD

**Issue by gitbhumi** [LeetCode-Feedback/LeetCode-Feedback#2040]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the Solution

We can possibly add following point to the solution section.

It might be a valid question to ask if "Linked List is allowed to modified". If yes, then in Solution 1 one can reduce Space complexity by making each visited node's next to point to a Dummy node. And if we find a node whose next.next is already pointing to a Dummy node, we have a cycle in the linked list. This keeps Runtime Complexity O(N) and Space complexity O(1) . Since this modifies the input it is not "Stable Algorithm" but is a potential solution. 

#### Code you used for Submit/Run operation

```
    def hasCycle(self, head):
        dummy = ListNode(None)
        dummy.next = dummy  # To ensure single node loops
        
        while head and head.next:
            curr = head.next
            if curr.next == dummy:
                return True
            head = curr.next
            curr.next = dummy 

        return False
```

#### Additional context

From interview preparation point of view, it might be a good point to bring up.

**Comment by lc-kay** [comment]
Hi @gitbhumi 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@gitbhumi Thanks for your suggestion. We're going to keep the article how it currently is, as it is reasonable to assume that the input should not be modified. Approach 2 provides a widely accepted way of achieving O(N) time and O(1) space for this problem, without destroying the input.
