### ISSUE TITLE
Missing Test Case - 242. Valid Anagram

### ISSUE THREAD

**Issue by nikand19** [LeetCode-Feedback/LeetCode-Feedback#20404]
### [242. Valid Anagram] (https://leetcode.com/problems/valid-anagram/)

Example 1:
Input: s = "AnaGram", t = "nagaram"
Output: true

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

UpperCase String in not considered in the testcase. For example: "CAr" and "car" are anagram.

### Language used for code

JAVA

### Code used for Submit/Run operation

```
class Solution {
    public boolean isAnagram(String s, String t) {
        if (s.length() != t.length())
            return false;
        String ls = s.toLowerCase();
        String lt = t.toLowerCase();
        char[] charS = ls.toCharArray();
        char[] charT = lt.toCharArray();
        Arrays.sort(charS);
        Arrays.sort(charT);

        return Arrays.equals(charS, charT);
    }
}

```

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

 "AnaGram", t = "nagaram" is a Invalid Testcase
's' must consist of values from a to z only

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
