### ISSUE TITLE
Videos in "Data Structures and Algorithms" can't be watched because of privacy settings

### ISSUE THREAD

**Issue by akymanau** [LeetCode-Feedback/LeetCode-Feedback#20416]
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [x] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
All videos under [Data Structures and Algorithms course](https://leetcode.com/explore/interview/card/leetcodes-interview-crash-course-data-structures-and-algorithms/715/introduction/) can't be played backand displays "Sorry
Because of its privacy settings, this video cannot be played here."

### Expected behavior

All videos play without issue

### Screenshots

Just a few of the videos below...
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/21152820/13fb3bb9-4f46-42a5-b747-9fe33f4317d9)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/21152820/25fb19d6-a9ee-409d-916e-a5b4767a6dd5)

### Additional context

Please ensure paid courses plays back videos correctly without needing for bugreports from paid customers, thank you

**Comment by LC-Pam** [comment]
Hi there,

Thank you for bringing your feedback to our attention. We've conducted a thorough investigation into the issue you raised, and after careful examination, our findings affirm that our videos are working correctly.

Please check your browser setting (clear history/cookies and update it to the lasted version) 

<img width="907" alt="Screen Shot 2024-02-17 at 9 11 52 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/fec46a09-0613-4af8-85aa-6d515767a941">


We appreciate the time and effort you've invested in sharing your feedback. It's invaluable to us as we work towards maintaining a high-quality platform.

Feel free to continue the dialogue here or provide any additional insights. We value your input and strive to create a collaborative space for improvement.

Best regards,
The LeetCode Team
