### ISSUE TITLE
436. Find Right Interval - Incorrect test Case and Editorial Solution  Method 1 

### ISSUE THREAD

**Issue by xiexiaojing** [LeetCode-Feedback/LeetCode-Feedback#20415]
### LeetCode Username

xie-xiao-jing

### Problem number, title, and link

436. Find Right Interval https://leetcode.cn/problems/find-right-interval/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug

 1、Incorrect test Case  [[1,1],[3,4]]
2、Editorial Solution  Method 1 is incorrect

### Code used for Submit/Run operation

```
    public static int[] findRightInterval(int[][] intervals) {
        Map<int[], Integer> indexMap = new HashMap<>();
        for(int i=0; i<intervals.length; i++) {
            indexMap.put(intervals[i], i);
        }

        Arrays.sort(intervals, (o1, o2)-> o1[0]-o2[0]);

        int[] ans = new int[intervals.length];
        int end = intervals.length-2;
        for(int i=0; i<=end; i++) {
            int left = i+1;
            int right = end+1;
            int min = -1;
            while(left<=right) {
                int mid = left + (right-left)/2;
                if(intervals[i][1]==intervals[mid][0]) {
                    min = mid;
                    break;
                }
                if(intervals[i][1]<intervals[mid][0]) {
                    min = mid;
                    right = mid - 1;
                } else {
                    left = mid + 1;
                }
            }
            ans[i] = min==-1?-1:indexMap.get(intervals[min]);
        }
        ans[end+1] = -1;

        int[] orginalAns = new int[ans.length];
        for(int i=0; i<ans.length; i++) {
            orginalAns[indexMap.get(intervals[i])] = ans[i];
        }

        return orginalAns;
    }
```

### Expected behavior

1、Test case should have passed.
2、Editorial Solution  Method 1 is incorrect， please fix it.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/28048077/62363197-9c80-4b56-b10a-880be18424ef)

### Additional context

This issue is the same as https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/20413, just in different language description.

**Comment by stormsunshine** [comment]
The second paragraph clearly mentions: Note that `i` may equal `j`.

Please make sure you understand the problem description correctly.
