### ISSUE TITLE
关于115.不同的子序列题目提交的问题

### ISSUE THREAD

**Issue by loker-coper** [LeetCode-Feedback/LeetCode-Feedback#20417]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

### LeetCode 用户名

loker-coper

### 问题号码、标题和链接

115.不同的子序列 https://leetcode.cn/problems/distinct-subsequences/?envType=study-plan-v2&envId=dynamic-programming

### Bug 类型
- [1] 问题描述
- [ ] 示例
- [ ] 问题限制
- [ ] 问题提示
- [ ] 不正确或缺少“相关标签”
- [1] 不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*
- [ ] 缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*
- [ ] 力扣官方题解
- [ ] 编程语言支持

### 描述

测试显示正常但提交出现问题

### 你使用的语言

C++

### 你提交或者运行的代码

```
class Solution {
public:
    int numDistinct(string s, string t) {
        int m = s.length(), n = t.length();
        if (m < n)
            return 0;
       int dp[m+1][n+1];
        for (int i = 0; i <= m; i++) {
            dp[i][n] = 1;
        }
        for (int i = m - 1; i >= 0; i--) {
            for (int j = n - 1; j >= 0; j--) {
                if (s[i] == t[j]) {
                    dp[i][j] = dp[i + 1][j + 1] + dp[i + 1][j];
                } else {
                    dp[i][j] = dp[i + 1][j];
                }
            }
        }
        return dp[0][0];
    }
};
```

### 期望行为

通过测试用例s = "ddd"  t = "dd"

### 屏幕截图

<img width="1266" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/77821628/8f4a4b74-90be-4cea-97f4-7bc06c73e291">

**Comment by stormsunshine** [comment]
字符串 "ddd" 中的不同子序列 "dd" 的数目应该等于 3，请问哪里有问题？能不能说明为什么应该等于 10？

**Comment by amcones-lc** [comment]
感谢反馈，经核实该题目题解及测试用例暂无异常，力扣会不断努力给大家带来更好的学习社区！后续刷题学习中遇到问题，可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
