### ISSUE TITLE
1071. Incorrect test case "Greatest Common Divisor of Strings"

### ISSUE THREAD

**Issue by MarlonFolken** [LeetCode-Feedback/LeetCode-Feedback#20410]
### Category of the bug
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### Description of the bug

Test number 70, claims that "abab" is the greatest common divisor, even though example shows that when str1 = "ababab", str2 = "abab" , output should be "ab".

### Code used for Submit/Run operation

```
let ans = "";
    let strShortest = '';
    let strLongest = '';
    let arrTestString: string[] = [];
    if(str1.length >= str2.length){
        strLongest = str1;
        strShortest = str2;
    }else{
        strLongest = str2;
        strShortest = str1;
    }
    // Cicle to pull characters to compare
    for (let i = 0; i < strShortest.length; i++) {
        arrTestString.push(strShortest.substring(0,(i+1)));
    }
    // Length --> test string.
    // Test if specimen string is valid
    for (let i = 0; i < arrTestString.length; i++) {
        let validSpecimen = true;
        let timesToAnalize = Math.trunc(strLongest.length/(i+1))
        let jumpSize = i+1;
        let positionStartTest = 0
        let tempIsValid:boolean[] = [];
        do{
            if( arrTestString[i] === strLongest.substring(positionStartTest, (positionStartTest+jumpSize)) ){
                validSpecimen = true;
            }else{
                validSpecimen = false;
            }
            tempIsValid.push(validSpecimen);
            positionStartTest += jumpSize;
            --timesToAnalize;
        }while(validSpecimen && 0 != timesToAnalize)
        if(tempIsValid.every(e => e === true)){
            //ANNOUNCE WINNER
            ans = arrTestString[i]
            return ans;
        }
    }
    return ans;
```

### Expected behavior

Expected to pass all tests since "ab" is the greatest common divisor of strings given str1 = "ababab" and str2 = "abab".
Test number 70 out of 123 tests claims that "abab" is the answer instead of my value given ("ab").

### Screenshots

<img width="502" alt="Screenshot 2024-02-16 at 1 25 05 p m" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/10090462/ed86f769-e284-48e3-a309-1b765ce9b595">

### Additional context

Explanation of the exercise and what the output is expected contradicts this test

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code Accepted submission link you submitted led to the observed result.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by MarlonFolken** [comment]
After sending this issue I realized the title asks for a Greatest Common Divisor (GCD) which implicates more than exercise 1071 explains, so, should I rise another issue asking for a more clear description inside exercise 1071? Requirements mentioned in 1071 does not mention the Math implication of a GCD.
<img width="496" alt="Screenshot 2024-02-16 at 6 50 05 p m" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/10090462/9dcdac5b-fd96-4efc-a685-d52188a2e78a">

**Comment by Christakou** [comment]
+1 Just had the same issue, glad someone already opened this request.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team
