### ISSUE TITLE
436. 寻找右区间 用例和官方题解都有误

### ISSUE THREAD

**Issue by xiexiaojing** [LeetCode-Feedback/LeetCode-Feedback#20413]
### LeetCode 用户名

xie-xiao-jing

### 问题号码、标题和链接

436. 寻找右区间 https://leetcode.cn/problems/find-right-interval/description/

### Bug 类型
- [ ] 问题描述： 
- [ ] 示例
- [ ] 问题限制
- [ ] 问题提示
- [ ] 不正确或缺少“相关标签”
- [x] 不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*
- [ ] 缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*
- [x] 力扣官方题解
- [ ] 编程语言支持

### 描述

 用例： [[1,1],[3,4]] 有误，方法1 解法与题意不符

### 你使用的语言

Java

### 你提交或者运行的代码

```
    public static int[] findRightInterval(int[][] intervals) {
        Map<int[], Integer> indexMap = new HashMap<>();
        for(int i=0; i<intervals.length; i++) {
            indexMap.put(intervals[i], i);
        }

        Arrays.sort(intervals, (o1, o2)-> o1[0]-o2[0]);

        int[] ans = new int[intervals.length];
        int end = intervals.length-2;
        for(int i=0; i<=end; i++) {
            int left = i+1;
            int right = end+1;
            int min = -1;
            while(left<=right) {
                int mid = left + (right-left)/2;
                if(intervals[i][1]==intervals[mid][0]) {
                    min = mid;
                    break;
                }
                if(intervals[i][1]<intervals[mid][0]) {
                    min = mid;
                    right = mid - 1;
                } else {
                    left = mid + 1;
                }
            }
            ans[i] = min==-1?-1:indexMap.get(intervals[min]);
        }
        ans[end+1] = -1;

        int[] orginalAns = new int[ans.length];
        for(int i=0; i<ans.length; i++) {
            orginalAns[indexMap.get(intervals[i])] = ans[i];
        }

        return orginalAns;
    }
```

### 期望行为

修改测试编号 18 的测试用例， 并修改官方题解 方法一

### 屏幕截图

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/28048077/fec0fc6f-6856-4971-b9f8-0c992b06d18e)

### 额外的上下文

官方题解 方法一 的审题有误， 导致结果有误，请更正

**Comment by stormsunshine** [comment]
题目描述的第二段写得很清楚：注意 `i` 可能等于 `j`。

请确保正确理解题意。

**Comment by amcones-lc** [comment]
感谢反馈，经核实该题目题解及测试用例暂无异常，力扣会不断努力给大家带来更好的学习社区！后续刷题学习中遇到问题，可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
