### ISSUE TITLE
Typo in Editorial for 1481. Least Number of Unique Integers after K Removals

### ISSUE THREAD

**Issue by Y-Rov** [LeetCode-Feedback/LeetCode-Feedback#20424]
### LeetCode Username

[anacondrai](https://leetcode.com/anacondrai/)

### Problem number, title, and link

[1481. Least Number of Unique Integers after K Removals](https://leetcode.com/problems/least-number-of-unique-integers-after-k-removals/)

### Category of the bug
- [ ] Editorial

### Description of the bug

Hello, LeetCode team 😄

If we go through the section "Complexity Analysis" in [problem's Editorial](https://leetcode.com/problems/least-number-of-unique-integers-after-k-removals/editorial/) and stop at the space complexity analysis (space complexity of the sorting algorithm, Python language):

> In Python, the `sort` method sorts a list using the Timesort algorithm which is a combination of Merge Sort and Insertion Sort and has _`O(n)`_ additional space.

There is a typo in the name of the "Timsort" algorithm.

### Expected behavior

The corrected sentence:

> In Python, the `sort` method sorts a list using the Timsort algorithm which is a combination of Merge Sort and Insertion Sort and has _`O(n)`_ additional space.

### Screenshots

![TimSort_Typo](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73534920/b2a5e91a-eda5-45cd-be17-590897cecc4a)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by Y-Rov** [comment]
Hi @LC-Pam, the typo was corrected, kudos to you ;)

![TimSort_Fixed](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73534920/e7b09cf4-5492-4048-bf62-4c945233a4f1)

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
