### ISSUE TITLE
Missing Test Case - 421. Maximum XOR of Two Numbers in an Array

### ISSUE THREAD

**Issue by aakanksha-jetti** [LeetCode-Feedback/LeetCode-Feedback#20428]
### Problem number, title, and link
421:Maximum Xor of Two numbers in an array

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

incorrect test case
### Description of the bug

Here we have one testcase when I am tried with another python editor the output is correct, but when i am tried here it gives wrong output.
The testcase is  :  nums =[8,10,2]
output:10
but here i got 8

### Language used for code

Python

### Code used for Submit/Run operation

```
class Solution(object):
    def findMaximumXOR(self, nums):
        m=0
        for i in range(len(nums)-1):
            t=nums[i]^nums[i+1]
            if(t>=m):
                m=t
        return m
// Paste your code here. Don't remove ``` given
// above and below the code.
```

### Expected behavior

Please check the editor and testcase
![Screenshot 2024-02-17 212045](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/123763959/90b7088f-5818-46ca-aa34-574c110c543d)
![Screenshot 2024-02-17 212123](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/123763959/03fb7501-9acd-4c63-96c4-7cfe0075b129)
 by trying this code. It runs correctly outside.

**Comment by Yawn-Sean** [comment]
the two codes are just different.
first one: one for-loop
second one: two for-loops

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
