### ISSUE TITLE
Typescript interface for PriorityQueue from @datastructures-js/priority-queue does not match run-time version

### ISSUE THREAD

**Issue by KalleV** [LeetCode-Feedback/LeetCode-Feedback#20439]
### LeetCode Username

kvirtaneva

### Problem number, title, and link

N/A - seems to apply to all Typescript execution environments

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [x] Programming language support

### Description of the bug

I discovered a version mismatch between the Typescript types for the `@datastructures-js/priority-queue` in the code editor vs the version running during submissions. The version used at run-time is v5 but the types are based on v6.

The v5 version expects the "compare" and "priority" options to be passed in an options object whereas v6 expects a compare function to be passed in directly: https://github.com/datastructures-js/priority-queue/commit/d6958a7b4da4312556d9e816dcea6437ad65a8e0

### Language used for code

Typescript

### Code used for Submit/Run operation

```
const pq = new PriorityQueue(() => 0)
pq.enqueue(1)
```

The code example will result in the following run-time error because the heap won't get constructed here: https://github.com/datastructures-js/priority-queue/blob/f0d59110179f7dc0f3370309fa4e9644d089f01e/src/priorityQueue.js#L19-L24:
```
/.nvm/versions/node/v20.10.0/lib/node_modules/@datastructures-js/priority-queue/src/priorityQueue.js:116
    this._heap.insert(+priority, element);
               ^
TypeError: Cannot read properties of undefined (reading 'insert')
    Line 116: Char 16 in priorityQueue.js (PriorityQueue.enqueue)
    Line 4: Char 8 in solution.ts (twoSum)
    Line 24: Char 19 in solution.ts (Object.<anonymous>)
    Line 16: Char 8 in runner.js (Object.runner)
    Line 13: Char 26 in solution.ts (Object.<anonymous>)
```

### Expected behavior

I was expecting the Typescript interface for the PriorityQueue to match the version of the library used by code submissions.

#### Code Editor Interface
![pq_compare_interface](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/5942028/737c4407-54da-4629-80b4-10571e58b03c)

#### Stringified PriorityQueue

Output from `console.info(pq.constructor.toString()`:

![pq_stringified](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/5942028/67a89dd1-e418-444a-9979-52ba080baca2)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Hi there,

This issue redirected to our developer team for investigation, it will take time to check.

Once we finish the investigation, we will re-open this ticket and get back to you. 

Thank you.
