### ISSUE TITLE
Missing Test Case - 1642. Furthest Building You Can Reach

### ISSUE THREAD

**Issue by yxue95** [LeetCode-Feedback/LeetCode-Feedback#20434]
### LeetCode Username

xyx76023

### Problem number, title, and link

[1642. Furthest Building You Can Reach](https://leetcode.com/problems/furthest-building-you-can-reach/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

My insufficient answer is accepted but shouldn't

### Language used for code

Java

### Code used for Submit/Run operation

```
class Solution {
    public int furthestBuilding(int[] heights, int bricks, int ladders) {

        PriorityQueue<Integer> pq = new PriorityQueue<>();
        
        for (int i = 0; i < heights.length - 1; i++) {
            int diff = heights[i + 1] - heights[i];

            if (diff <= 0) {
                continue;
            }

            if (ladders > 0) {
                pq.add(diff);
                ladders--;
            } else if (!pq.isEmpty() && pq.peek() < diff) {

                bricks -= pq.poll(); 
                pq.add(diff); 
                
                if (bricks < 0) {
                    return i;
                }
            } else {

                bricks -= diff;
                if(bricks == 0) {
                    return i+1;
                }
                if (bricks < 0) {
                    return i;
                }
            }
        }
        
        return heights.length - 1;
    }
}
```

### Expected behavior

For test case: heights = [1,5,8,8], bricks = 3, ladders = 1, my solution yields wrong answer but gets AC when submitted.

### Screenshots

![sc1](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/119626304/1ea2d04f-95ff-454a-bc45-33cfba54c289)

![sc2](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/119626304/55f85cdc-75da-435d-a8dd-57368c175b16)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
