### ISSUE TITLE
Missing Test Case - 3. Longest Substring Without Repeating Characters

### ISSUE THREAD

**Issue by jaredar1232** [LeetCode-Feedback/LeetCode-Feedback#20437]
### LeetCode Username
KingAzion

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
I wrote this solution and it passes being submitted. It shouldn't. New test case provided at the bottom.

### Code used for Submit/Run operation

```
var lengthOfLongestSubstring = function(s) {
    let right =  0
    let substring = [];
    let maxSub = 0;

    while(right < s.length) {
        const newLetter = s[right]
        if(substring.includes(newLetter)) {
            substring = [];
            substring.push(newLetter);
        } else {
            substring.push(newLetter);
            maxSub = Math.max(maxSub, substring.length);
        }
        right++;
    }

    return maxSub;
};
```

### Expected behavior
It should fail the test/submission but it doesn't

### Additional context
Here is a test input I wrote that my code fails to answer correctly. "abdcaqrbb", the result should be 6 ("bdcaqr"), but my code returns 4 as it resets when it gets to the second "a". Adding this to the test suits should fix this blind spot. Cheeers

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
