### ISSUE TITLE
Missing Test Case - 111. Minimum Depth of Binary Tree

### ISSUE THREAD

**Issue by KatDoc** [LeetCode-Feedback/LeetCode-Feedback#20436]
### LeetCode Username

Kat

### Problem number, title, and link

Minimum Depth of Binary Tree  https://leetcode.com/explore/interview/card/leetcodes-interview-crash-course-data-structures-and-algorithms/707/traversals-trees-graphs/4691/

### Category of the bug
- [ ] Problem description
- [x] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Language used for code
Python 3

### Code used for Submit/Run operation

```
class Solution:
    def minDepth(self, root: [TreeNode]) -> int:
        if not root:
            return 0
        
        left = self.minDepth(root.left)
        right = self.minDepth(root.right)
        
        # edge case when only one line of tree is present
        if root.left != None and root.right != None:
            ans = min(left, right) + 1
        elif root.left == None or root.right == None: 
            ans = max(left, right) + 1
        
        return ans
```

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

Details regarding the missing test case.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team
