### ISSUE TITLE
Missing Test Case - 1769. Get Maximum in Generated Array

### ISSUE THREAD

**Issue by Ahmedya55er** [LeetCode-Feedback/LeetCode-Feedback#2044]
#include <stdio.h>
int main (void) 
{
	int n;
	scanf ("%d", &n);
	int arr[n+1];
	arr[0]=0;
	arr[1]=1;
	for (int i =2;i<=n;i++)
	{
		if ((i%2)==0)
		{
			arr[i] = arr[i/2];
		}
		else 
		{
			arr[i] = arr[i/2]+arr[(i/2)+1];
		}
	} 
	int max = 0;
	for (int i = 0; i<n; i++) 
	{
		printf ("%d  \n", arr[i]);
		if (max<arr[i]) 
		{
			max = arr[i];
		}
	}
	printf ("max is %d", max);
	return 0;
} 
_I don't know what is wrong with my code! _

**Comment by lc-kay** [comment]
@Ahmedya55er Unfortunately, we do not provide support on troubleshooting codes. I'd recommend checking out the discuss section to reference accepted codes or raising your question there. Thank you for your time.
