### ISSUE TITLE
Missing Test Case - 1642. Furthest Building You Can Reach

### ISSUE THREAD

**Issue by KatarzynaGrzeskowiak** [LeetCode-Feedback/LeetCode-Feedback#20440]
The testcase with Input heights = [1,5,1,2,3,4,10000] bricks = 4 ladders =1 is wrong. It says that output is 5, but we firsly uses 4 bricks to jump and then go to 1 and use ledder to jump to 2 so we cant move to 3. Output should be 3 not 5 or I miss sth. Pls tell me

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.


Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team
