### ISSUE TITLE
Missing Test Case - 2369. Check if There is a Valid Partition For The Array

### ISSUE THREAD

**Issue by dvikdvik** [LeetCode-Feedback/LeetCode-Feedback#20443]
### LeetCode Username

[v1kstrand](https://leetcode.com/v1kstrand)

### Problem number, title, and link

[2369. Check if There is a Valid Partition For The Array](https://leetcode.com/problems/check-if-there-is-a-valid-partition-for-the-array/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

solution gets accepted, but don't return the expected output for this input
       
 Input
nums =
[4,4,4,5,6,7,9,10]
Output
true
Expected
false

### Language used for code

python

### Code used for Submit/Run operation

```
class Solution:
    def validPartition(self, nums: List[int]) -> bool:
        mem = [1,1,1]

        p, p_count, b_count = inf, 0, 0
        for i in range(len(nums)):
            if not sum(mem):
                return False
            mem.append(0)

            if nums[i] == p:
                p_count += 1
                b_count = 0
                if p_count >= 1:
                    mem[-1] = mem[1]
                if p_count >= 2:
                    mem[-1] = mem[0] or mem[-1]
            elif nums[i] - 1 == p:
                b_count += 1
                p_count = 0
                if b_count >= 2:
                    mem[-1] = mem[0] or mem[-1]

            p = nums[i]
            mem.pop(0)

        return mem[-1]
```

### Expected behavior

solution gets accepted, but don't return the expected output for this input
       
 Input
nums =
[4,4,4,5,6,7,9,10]
Output
true
Expected
false

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
