### ISSUE TITLE
Incorrect test case evaluation on submit

### ISSUE THREAD

**Issue by dikshitjain** [LeetCode-Feedback/LeetCode-Feedback#20448]
### LeetCode Username
purely_virtual

### Problem number, title, and link    
3044. Most Frequent Prime https://leetcode.com/problems/most-frequent-prime

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
For his test case, when I submit my code it fails with Wronf Answer:
[[9,5,7],[4,9,7],[1,5,2]]

However, when I run the test case individually it runs and gives the expected output.

### Language used for code
 C++

### Code used for Submit/Run operation

```
class Solution {
public:
    
    bool isPrime(long num) {
        for(int i=2; i<=sqrt(num); i++) {
            if(num%i == 0) return false;
        }
        return true;
    }
    
    void move(vector<vector<int>>& mat, int r, int c, pair<int, int> dir, unordered_map<long, int>& count) {
        long num = 0;
        while(r>=0 && c>= 0 && r<mat.size() && c<mat[0].size()) {
            long num = mat[r][c] + num*10;
            if(num >=10 && isPrime(num)) {
                count[num]++;
            }
            r += dir.first;
            c += dir.second;
        }
    }
    int mostFrequentPrime(vector<vector<int>>& mat) {
        unordered_map<long, int> count;
        for(int r=0; r<mat.size(); r++) {
            for(int c=0; c<mat[0].size(); c++) {
                move(mat, r, c, {0, 1}, count);
                move(mat, r, c, {1, 0}, count);
                move(mat, r, c, {0, -1}, count);
                move(mat, r, c, {-1, 0}, count);
                move(mat, r, c, {1, 1}, count);
                move(mat, r, c, {-1, 1}, count);
                move(mat, r, c, {1, -1}, count);
                move(mat, r, c, {-1, -1}, count);
            }
        }
        int maxVal = -1;
        long res = -1;
        for(auto cnt: count) {
            // cout << "Val: " << cnt.first << " Count: " << cnt.second << endl;
            if(maxVal < cnt.second) {
                res = cnt.first;
                maxVal = cnt.second;
                // cout << "res: " << res << " maxVal: " << maxVal << endl;
            }
            else if(maxVal == cnt.second) {
                res = max(res, cnt.first);
            }
        }
        return res;
        
    }
};
```

### Expected behavior
The expected answer is 59 and on submission, the answer is 97. On the other hand, if I just run it gives me the correct answer.

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/31550936/0354f417-6e11-43b8-ac85-c03730acd1a2)

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
