### ISSUE TITLE
Bug in editorial: 1642. Furthest Building You Can Reach

### ISSUE THREAD

**Issue by vesteny77** [LeetCode-Feedback/LeetCode-Feedback#20442]
### LeetCode Username

vesteny77

### Problem number, title, and link

[1642. Furthest Building You Can Reach](https://leetcode.com/problems/furthest-building-you-can-reach/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug

The Python code of the 5th approach of the [editorial](https://leetcode.com/problems/furthest-building-you-can-reach/editorial/) fails this [test case](https://leetcode.com/problems/furthest-building-you-can-reach/submissions/1178326688/)
> [4,2,6,6,9,8,9,12]
5
0

The problem is that line 54 tries to compute the middle index of `lo` and `hi` with
> mid = lo + (hi - lo) / 2

The correct floor division in Python should be implemented as `mid = (lo + hi) // 2`.

Also, for the sake of completeness, we can add `return -1` after the while loop(line 70).

### Language used for code

Python3

### Code used for Submit/Run operation

```
class Solution:
    def furthestBuilding(self, heights: List[int], bricks: int, ladders: int) -> int:
        
        def solveWithGivenThreshold(K):
            
            ladders_remaining = ladders
            bricks_remaining = bricks
            ladders_used_on_threshold = 0
            
            for i in range(len(heights) - 1):
                climb = heights[i + 1] - heights[i]
                if climb <= 0:
                    continue
                    
                # Make resource allocations
                if climb == K:
                    ladders_used_on_threshold += 1
                    ladders_remaining -= 1
                elif climb > K:
                    ladders_remaining -= 1
                else:
                    bricks_remaining -= climb
                    
                # Handle negative resources.
                if ladders_remaining < 0:
                    if ladders_used_on_threshold:
                        ladders_used_on_threshold -= 1
                        ladders_remaining += 1
                        bricks_remaining -= K
                    else:
                        return [i, ladders_remaining, bricks_remaining]
                
                if bricks_remaining < 0:
                    return [i, ladders_remaining, bricks_remaining]
            
            return [len(heights) - 1, ladders_remaining, bricks_remaining]
                
        
        # Find the minimum climb and maximum climbs
        lo = math.inf
        hi = -math.inf
        for i in range(len(heights) - 1):
            climb = heights[i + 1] - heights[i]
            if climb <= 0:
                continue
            lo = min(lo, climb)
            hi = max(hi, climb)
        
        if lo == math.inf: # Was there no climbs?
            return len(heights) - 1
        
        # Carry out the binary search.
        while lo <= hi:
            mid = (lo + hi) // 2
            index_reached, ladders_remaining, bricks_remaining = solveWithGivenThreshold(mid)
            # Did we get all the way?
            if index_reached == len(heights) - 1:
                return len(heights) - 1
            # Otherwise, if we have a ladder remaining, it has to be too high.
            if ladders_remaining > 0:
                hi = mid - 1
                continue
                
            # Otherwise, check for the other optimal conditions.
            next_climb = heights[index_reached + 1] - heights[index_reached]
            if bricks_remaining < next_climb and bricks_remaining < mid:
                return index_reached
            
            # Otherwise, it must have been too low.
            lo = mid + 1
        
        return -1
```

### Expected behavior

Input: heights = [4,2,6,6,9,8,9,12], bricks = 5, ladders = 0

Expected output: 3

Actual output:
```
TypeError: None is not valid value for the expected return type integer
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    raise TypeError(str(ret) + " is not valid value for the expected return type integer");
Line 103 in _driver (Solution.py)
    _driver()
Line 110 in <module> (Solution.py)
During handling of the above exception, another exception occurred:
TypeError: '<' not supported between instances of 'int' and 'NoneType'
Line 14 in _serialize_int (./python3/__serializer__.py)
Line 63 in _serialize (./python3/__serializer__.py)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    out = ser._serialize(ret, 'integer')
Line 101 in _driver (Solution.py)
``` 

### Additional context

You may view [my modified code](https://leetcode.com/problems/furthest-building-you-can-reach/submissions/1178329471/) which passed all test cases.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
