### ISSUE TITLE
Bug in Problem Description

### ISSUE THREAD

**Issue by Vinayaka2k** [LeetCode-Feedback/LeetCode-Feedback#20447]
### LeetCode Username
vinuvinayaka2000

### Problem number, title, and link
3043. Find the Length of the Longest Common Prefix https://leetcode.com/problems/find-the-length-of-the-longest-common-prefix/

### Category of the bug
- [x] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
The common prefix of `5655359` and `56554` is `5655` and not `565`, as mentioned in the problem statement

### Language used for code
Python3

### Code used for Submit/Run operation
```
import math

class Solution:
    def longestCommonPrefix(self, arr1: List[int], arr2: List[int]) -> int:
        s = set()
        res = 0
        for num in arr1:
            while num:
                s.add(num)
                num = num // 10
        for num in arr2:
            n = int(math.log10(num)) + 1
            while num:
                if num in s:
                    res = max(res, n)
                n -= 1
                num = num // 10
        return res
```

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.
It’s common prefix, but not the longest.
If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
