### ISSUE TITLE
Missing test case - 100. Same Tree

### ISSUE THREAD

**Issue by vivekviishal** [LeetCode-Feedback/LeetCode-Feedback#20459]
LeetCode ID: vivekjsrvishal

100.[ Same Tree](https://leetcode.com/problems/same-tree/description/)

Category of the bug
- [ ] Problem description
- [ ]  Solved examples
- [ ]  Problem constraints
- [ ]  Problem hints
- [ ]  Incorrect or missing "Related Topics"
- [ ]  Incorrect test Case (Output of test case is incorrect as per the problem statement)
- [x]  Missing test Case (Incorrect/Inefficient Code getting accepted because of missing test cases)
- [ ]  Editorial
- [ ]  Programming language support

Description of the bug
A solution is accepted, but it fails on a test case:
p=[1,-1]
q=[1,null,-1]

Language used for code : Java

Code used for Submit/Run operation
```
/**
 * Definition for a binary tree node.
 * public class TreeNode {
 *     int val;
 *     TreeNode left;
 *     TreeNode right;
 *     TreeNode() {}
 *     TreeNode(int val) { this.val = val; }
 *     TreeNode(int val, TreeNode left, TreeNode right) {
 *         this.val = val;
 *         this.left = left;
 *         this.right = right;
 *     }
 * }
 */
class Solution {
    public static ArrayList<Integer> Add(TreeNode root,ArrayList<Integer>arr){
        if(root==null){
            arr.add(-1);
            return arr;
        }
        arr.add(root.val);
        Add(root.left,arr);
        Add(root.right,arr);
        return arr;
    }
    public boolean isSameTree(TreeNode p, TreeNode q) {
        ArrayList <Integer> arr=new ArrayList<>();
        ArrayList <Integer> brr=new ArrayList<>();
        Add(p,arr);
        Add(q,brr);
        if(arr.equals(brr)){
            return true;
        }
        return false;
    }
}
```
Expected behavior
The solution should not be accepted since it fails on a test case.

Screenshots
![Screenshot (91)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/101403253/c6dbcdb7-ae80-4165-a7ec-a46f22289dd0)

Additional context
link of the problem: https://leetcode.com/problems/same-tree/

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by vivekviishal** [comment]
Got this question as POTD today,
Glad you added the testcase recommended

would be great if you give the credit points on leetcode for me (+100 points for testcases contribution)
vivekjsrvishal [leecode](https://leetcode.com/vivekjsrvishal/)

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
