### ISSUE TITLE
[JS] Time Constraints Too Tight - Count Prefix and Suffix Pairs II

### ISSUE THREAD

**Issue by mhwice** [LeetCode-Feedback/LeetCode-Feedback#20454]
### LeetCode Username
espr3ss0

### Problem number, title, and link
 3045: Count Prefix and Suffix Pairs II https://leetcode.com/problems/count-prefix-and-suffix-pairs-ii

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [x] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
I believe the time constraints for this problem are too tight for JavaScript. My code shown below runs in ~O(n) time and passes 595 of 596 test cases, but then times-out on the last case - resulting in a TLE. 

### Language used for code
JavaScript

### Code used for Submit/Run operation

```js
/**
 * @param {string[]} words
 * @return {number}
 */
var countPrefixSuffixPairs = function(words) {
  
  const n = words.length;
  
  const seenWordCounts = new Map();
  
  let count = 0;
  for (const word of words) {
    
    const m = word.length;
    
    const wordArr = [];
    for (const c of word) wordArr.push(c.charCodeAt(0) - 96);
    const rh = new RollingHash(wordArr);
    
    const prefixHashes = [];
    for (const prefHash of rh.getprefix()) prefixHashes.push(prefHash);
    
    let i = 0;
    for (const suffHash of rh.getsuffix()) {
      
      if (prefixHashes[i] === suffHash) {
        const len = i + 1;
        const prefix = word.substring(0, len);  
        const suffix = word.substring(m - len, m);
        if (prefix === suffix && seenWordCounts.has(prefix)) count += seenWordCounts.get(prefix);
      }
      
      i += 1;
    }
    
    seenWordCounts.set(word, (seenWordCounts.get(word) || 0) + 1);
  }
  
  return count;
};

class RollingHash {
	
	constructor(arr, BASE = 29) {
		
		this.MOD = 30_000_001;
		
		this.prefix = [0];
		this.invPrefix = [1];
		this.n = arr.length;
		
		const BASE_INV = this.modPow(BASE, this.MOD - 2, this.MOD); 
		let power = 1;
		
		for (const x of arr) {
			this.prefix.push((this.prefix.at(-1) + x * power) % this.MOD);
			this.invPrefix.push(this.invPrefix.at(-1) * BASE_INV % this.MOD);
			power = power * BASE % this.MOD;
		}
	}
	
	modPow(a, n, m) {
		
		a = BigInt(a);
		n = BigInt(n);
		m = BigInt(m);
		
		let res = 1n;
		
		while (n > 0n) {
			if ((n & 1n) === 1n) res = (res * a) % m;
			
			a = (a * a) % m;
			n >>= 1n;
		}
		
		return Number(res);
	}
	
	query(left, right) {
		return ((this.prefix[right + 1] - this.prefix[left] + this.MOD) % this.MOD) * this.invPrefix[left] % this.MOD;
	}
	
	*slideWindow(len, withIndexes = false) {
		for (let right = len - 1, n = this.n; right < n; right += 1) {
			if (withIndexes) {
				yield [right - len + 1, right, this.query(right - len + 1, right)];	
			} else {
				yield this.query(right - len + 1, right);
			}
		}
	}
	
	*getprefix(withIndexes = false) {
		for (let right = 0, n = this.n; right < n; right += 1) {
			if (withIndexes) {
				yield [0, right, this.query(0, right)];
			} else {
				yield this.query(0, right);
			}
		}
	}
	
	*getsuffix(withIndexes = false) {
		const n = this.n;
		for (let left = n - 1; left >= 0; left -= 1) {
			if (withIndexes) {
				yield [left, n - 1, this.query(left, n - 1)];
			} else {
				yield this.query(left, n - 1);
			}
		}
	}
}
```

### Expected behavior
Code is Accepted

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

Your solution is not O(n).

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
