### ISSUE TITLE
1009. Complement of Base 10 Integer

### ISSUE THREAD

**Issue by Ancient-0001** [LeetCode-Feedback/LeetCode-Feedback#20474]
###  
1009. Complement of Base 10 Integer 
https://leetcode.com/problems/complement-of-base-10-integer/

### Category:-
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Programming language support

### Code used for Submit/Run operation
```
class Solution {
public:
    int bitwiseComplement(int num) {
    int i=0,bin[100],compli[100],sum=0;
    //cout<<"Enter Integer: ";
    //cin>>num;

    while(num!=0){
        bin[i]={num%2};
        if(bin[i]==1){
            compli[i]={0};
        }
        else{
            compli[i]={1};
        }
        num=num/2;
        i++;
    }
    // cout<<"Binary:";
    // for(int k=i-1;k>=0;k--){
    //     cout<<bin[k];
    // }
    // cout<<endl;
    // cout<<"Complement:";
    //  for(int k=i-1;k>=0;k--){
    //     cout<<compli[k];
    // }
    // cout<<endl;
    int p=0;
    while(i>=1){
        sum=sum+compli[p]*pow(2,p);
        p++;
        i--;
    }
    //cout<<"Compliment as Base 10:";
    return sum;
}
};
```

### Expected behavior: This code contains a thorough code for the above problem.
Input:5
Output:2

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
