### ISSUE TITLE
.Missing Test Case - 1281. Subtract the Product and Sum of Digits of an Integer

### ISSUE THREAD

**Issue by Hrishi-10k** [LeetCode-Feedback/LeetCode-Feedback#20485]
### LeetCode Username:- hrishidahake

1281. Subtract the product and sum of digits of an integer https://leetcode.com/problems/subtract-the-product-and-sum-of-digits-of-an-integer/

### Description of the bug
Given an integer number n, return the difference between the product of its digits and the sum of its digits.

### Language used for code
C++

###Solution:-
```
class Solution {
public:
    int subtractProductAndSum(int n) {
    int Addition=0,Multiplication=1;
    while(n!=0)
    {
        int num=n%10;
        Addition=Addition+num;
        Multiplication=Multiplication*num;
        n=n/10;
    }
    int ans=Multiplication-Addition;
    return ans;
    }
};
```
### Test Result:-
n=234
Expected Output:-
15

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
