### ISSUE TITLE
Missing Test Case - 2402. Meeting Rooms III

### ISSUE THREAD

**Issue by tredsused40** [LeetCode-Feedback/LeetCode-Feedback#20487]
### LeetCode Username

tredsused70

### Problem number, title, and link

2402. Meeting Rooms III https://leetcode.com/problems/meeting-rooms-iii/

### Category of the bug
- [.] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

Code that gets "Accepted" when used "Submit" operation, gets "Wrong answer" when used "Run" operation on some testcases.

### Language used for code

C++

### Code used for Submit/Run operation

```
class Solution {
public:
    int mostBooked(int n, vector<vector<int>>& meetings) {
        multiset<pair<unsigned int, int>> mst;
        sort(meetings.begin(), meetings.end());
        vector<int> vc(n, 0);
        unsigned int curt = 0, cm, cl;
        set<int> st;
        for(int i = 0; i < n; i++)
            st.insert(i);
        for(auto i : meetings) {
            cm = i[0];
            curt = max(cm, curt);
            cl = i[1] - i[0];
            while(!mst.empty() && mst.begin() -> first <= curt) {
                st.insert(mst.begin() -> second);
                mst.erase(mst.begin());
            }
            if(st.empty()) {
                curt = mst.begin() -> first;
                st.insert(mst.begin() -> second);
                mst.erase(mst.begin());
            }
            vc[*st.begin()]++;
            mst.insert(make_pair(curt + cl, *st.begin()));
            st.erase(st.begin());
        }
        return max_element(vc.begin(), vc.end()) - vc.begin();
    }
};
```

### Expected behavior

When the test in the txt.txt file below is executed, in line ```mst.insert(make_pair(curt + cl, *st.begin()));``` expression curt + cl overflows, but it is ok for C++ because these variables are unsigned. However it results in incorrect output, because after it overflows, for programm meeting ending time is taken mod 2^32, which means that programm thinks that meeting in room 0(for this specific testcase) ends earlier than in room 1, even if that's not true. Because of that in programm it is saves that room 0 has more meetings, while the answer is 1.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/75163817/68245726-dfea-4f94-8a1b-ed47291bff21)

### Additional context

[txt.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/14324156/txt.txt)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

We can’t add the test case currently because of technical issues.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team

**Comment by tredsused40** [comment]
If you can't add the test right now, do I have to reopen the issue later?
