### ISSUE TITLE
Missing Test Case - 2629. Function Composition

### ISSUE THREAD

**Issue by sixzerexs** [LeetCode-Feedback/LeetCode-Feedback#20489]
### Category of the bug
- Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
the test gave an incorrect expected answer, my code passed all tests but failed the test number 1 with a clearly wrong expected answer .

### Language used for code
JavaScript

### Code used for Submit/Run operation

```
/**
 * @param {Function[]} functions
 * @return {Function}
 */
const compose = function(functions) {
    return function(x) {
        for(let i = 0; i<functions.length;i++) {
            x = functions[i](x)
        }
    return x
    }
};
```

### Expected behavior
the test showed that I solved the problem incorrectly and gave the expected answer 65,
 although the correct expected answer should be 50, the same answer as the code gave me.

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/85060029/0bcbd44f-51cf-4e8c-901b-5f84d2107a4d)

### Additional context
x==4 , x+1=5 => x*x = 25 => 2*x = 50. x !== 65
thanks

**Comment by Yawn-Sean** [comment]
you should process the functions reversely.

**Comment by sixzerexs** [comment]
> you should process the functions reversely.

sorry ,i stupid
I was so confused for so long, I forgot to add the reverse method.
