### ISSUE TITLE
Typo in "LeetCode's Interview Crash Cours: Data Structures and Algorithms" - "Arrays and strings"

### ISSUE THREAD

**Issue by pochopsp** [LeetCode-Feedback/LeetCode-Feedback#20481]
### LeetCode Username
pochopsp

### Problem number, title, and link
"LeetCode's Interview Crash Cours: Data Structures and Algorithms" - "Arrays and strings"
https://leetcode.com/explore/interview/card/leetcodes-interview-crash-course-data-structures-and-algorithms/703/arraystrings/4502/

### Category of the bug
- [ ] Editorial

### Description of the bug
There's a typo in "Array and Strings" chapter "Sliding window" section, under "The algorithm" there's the sentence "Initialliy, we have..." but it should be "Initially, we have..."

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team
