### ISSUE TITLE
Missing Test Case - 224. Basic Calculator

### ISSUE THREAD

**Issue by nik-6174** [LeetCode-Feedback/LeetCode-Feedback#20499]
Nik6174
224. Basic Calculator : https://leetcode.com/problems/basic-calculator/

### Category of the bug
- Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### Description of the bug
Input =
"(1 2 + 4) + 1"
This is a valid testcase according to the Constraints, however it gives incorrect output when inputted in custom testcase.
The validity of the testcase is at question, because it is not a part of the testcases that gets checked on submitting. The space shouldn't ideally be allowed between numbers without any operators.

### Language used for code
Python 3

### Code used for Submit/Run operation
```
class Solution:
    def calculate(self, s: str) -> int:
        stack = []
        num = 0
        sign = 1
        result = 0
        
        for char in s:
            if char.isdigit():
                num = num * 10 + int(char)
            elif char in "+-":
                result += sign * num
                num = 0
                sign = 1 if char == "+" else -1
            elif char == "(":
                stack.append(result)
                stack.append(sign)
                result = 0
                sign = 1
            elif char == ")":
                result += sign * num
                num = 0
                result *= stack.pop()  # pop the sign
                result += stack.pop()  # pop the result outside the brackets
        return result + sign * num

```

### Expected behavior
It should give error as the testcase is not valid, or at least shouldn't be valid.

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/78644716/4f357b32-f5d3-492c-924b-1ce741df8469)

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
