### ISSUE TITLE
hashmap output error

### ISSUE THREAD

**Issue by ranganmukherjee** [LeetCode-Feedback/LeetCode-Feedback#20491]
### LeetCode Username
[justlikethatrangan](https://leetcode.com/justlikethatrangan)

### Problem number, title, and link

3403. [Find the Length of the Longest Common Prefix](https://leetcode.com/problems/find-the-length-of-the-longest-common-prefix/)

### Category of the bug

- [ ] Solved examples

### Description of the bug
In this problem we were asked to find the longest common prefix  so I made two hash map and iterated through every digit of the two array and as a string and stored them in two hash maps now I compared two hash map to check if both of them contains the same key if yes then I put the length of the longest string as my answer so when I print the hash map to check their content for the first test case arr1=[1,10,100] and arr2=[1000] so my hash map gives output accordingly its stdout is {1=3, 100=1, 10=2}
{1=1, 100=1, 1000=1, 10=1} but for the test case  arr1=[1,2,3] and arr2=[4,4,4] the stdout is {1=4, 100=1, 2=1, 3=1, 10=2}
{1=1, 100=1, 4=3, 1000=1, 10=1} I checked all other ide no such problem is happening there please check it
specifying the link here:- https://leetcode.com/problems/find-the-length-of-the-longest-common-prefix/submissions/1179372861/
### Language used for code
JAVA

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ```import java.util.*;
class Solution {
    public static HashMap<String,Integer> imp = new HashMap<>();
    public static HashMap<String,Integer> imp1 = new HashMap<>();
    static void insert (int n){
        String x = Integer.toString(n);
        char[]arr = x.toCharArray();
        String str="";
        for(int i=0;i<arr.length;i++){
            str+=Character.toString(arr[i]);
            if(imp.containsKey(str)){
                continue;
            }else{
                imp.put(str,1);
            }
          
        }
    }
       static void insert1 (int n){
        String x = Integer.toString(n);
        char[]arr = x.toCharArray();
        String str="";
        for(int i=0;i<arr.length;i++){
            str+=Character.toString(arr[i]);
            if(imp1.containsKey(str)){
                continue;
            }else{
                imp1.put(str,1);
            }
          
        }
    }
    public int longestCommonPrefix(int[] arr1, int[] arr2) {
        int ans=0;
        for(int i=0;i<arr1.length;i++){
            insert(arr1[i]);
        }
        for(int i=0;i<arr2.length;i++){
            insert1(arr2[i]);
        }
        System.out.println(imp);
        System.out.println(imp1);
        for(String key:imp.keySet()){
            if(imp1.containsKey(key)){
                if(key.length()>ans){
                    ans=key.length();
                }
            }
        }

        return ans;
    }
}
```

### Expected behavior
when the arr1={1,2,3}
and arr2={4,4,4}
it should have been 
 {1=4,  2=1, 3=1, }
{ 4=1}

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/95093526/cd69a6e4-b67f-4861-a8e6-748aa35f4993)

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
