### ISSUE TITLE
Missing Test Case - 2101. Detonate the Maximum Bombs

### ISSUE THREAD

**Issue by Joe-Tseng** [LeetCode-Feedback/LeetCode-Feedback#20514]
### LeetCode Username
 LU4YU

### Problem number, title, and link
 2101. Detonate the Maximum Bombs https://leetcode.com/problems/detonate-the-maximum-bombs/description/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
 The code is accepted, but there is an edge case which is not covered in the testcases.

### Language used for code
 Python3

### Code used for Submit/Run operation

``` python3
class Solution:
    def maximumDetonation(self, bombs: List[List[int]]) -> int:
        bombs_count = {}

        for x, y, _ in bombs:
            bombs_count[(x, y)] = 1 + bombs_count.get((x, y), 0)

        max_effect = []

        for x, y, r in bombs:
            max_effect.append(self.bfs(bombs, (x, y), r, bombs_count))

        return max(max_effect)

    def bfs(self, graph, source, radius, bombs_count):
        res = bombs_count[source] - 1
        q = collections.deque()
        q.append([source, radius])
        visited = set()
        visited.add((source))

        while q:
            level_nums = len(q)

            for _ in range(level_nums):
                node, node_radius = q.popleft()
                res += 1

                for x, y, r in graph:
                    if (x, y) in visited or not self.in_area(node, node_radius, (x, y)):
                        continue

                    q.append([(x, y), r])
                    visited.add((x, y))

        return res

    def in_area(self, source, radius, target):
        x1, y1 = source
        x2, y2 = target
        return (abs(x2 - x1) ** 2 + abs(y2 - y1) ** 2) <= (radius ** 2)
```

### Expected behavior
 Expected behavior of code should get a wrong answer, because I only deal with the case that there are multi-bombs in the source point. If I run the same code with the custom testcase [[4,4,3],[4,4,3],[4,3,1],[4,3,1]], which means that there are multi-bombs in the source point and multi-bombs in the point that locates in  the affected area, then I will get a wrong answer with the accepted code.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
