### ISSUE TITLE
Missing test case - 1722. Minimize Hamming Distance After Swap Operations

### ISSUE THREAD

**Issue by lumiZGorlic** [LeetCode-Feedback/LeetCode-Feedback#2051]
#### Your LeetCode username 

lumi1

#### Category of the bug
- [ ] Question
- [ x] Solution
- [ ] Language

#### Description of the bug

my solution passes all the tests but is incorrect.

In my solution a variable called mp maps a value in target array to its index. It should be mapping value into a list of indexes as there can be duplicates in the array. Comments in the code should make it clear.

the following test case illustrates the issue and would be worth adding:

[1,5,5]
[5,1,1]
[[0,1]]

#### Code you used for Submit/Run operation

```
class Solution:
    def minimumHammingDistance(self, s: List[int], t: List[int], allowed: List[List[int]]) -> int:
        # maps value to the index which is wrong. should be a value to a list of indexes
        mp = {v: i for i,v in enumerate(t)}
        cnt = Counter(t)

        edges = [[] for _ in range(len(s))]
        for v1, v2 in allowed:
            edges[v1].append(v2)
            edges[v2].append(v1)

        # holds separate graphs
        graphs = []
        seen = set()

        def dfs(root, graph):
            if root in seen: return

            graph.add(root)
            seen.add(root)

            for nb in edges[root]:
                dfs(nb, graph)
            pass

        for i in range(len(s)):
            graph = set()
            dfs(i, graph)
            if graph: graphs.append(graph)

        # mapping each node to the graph it belongs to
        nodeToGraph = [-1 for _ in range(len(s))]

        for i, g in enumerate(graphs):
            for v in g:
                nodeToGraph[v] = i

        ret = 0
        for i in range(len(s)):
            if s[i] not in cnt or not cnt[s[i]]:
                ret += 1
            elif s[i] == t[i]:
                cnt[s[i]] -= 1
            else:
                idx = mp[s[i]]
                if nodeToGraph[i] != nodeToGraph[idx]:
                    ret += 1
                else:
                    cnt[s[i]] -= 1

        return ret
```

#### Language used for code

Python3

#### Expected behavior

my solution should be rejected as it doesn't solve a test case i came up with which is:

[1,5,5]
[5,1,1]
[[0,1]]

**Comment by lc-kay** [comment]
Hi @lumiZGorlic 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @lumiZGorlic 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
