### ISSUE TITLE
Missing Test Case - 1980. Find Unique Binary String

### ISSUE THREAD

**Issue by adityak54** [LeetCode-Feedback/LeetCode-Feedback#20525]
### Category of the bug
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

Proper testcases are not present and incorrect logic is also being accepted

### Code used for Submit/Run operation

```
class Solution {
public:
    string findDifferentBinaryString(vector<string>& nums) {
        int n=nums.size();
        string ans;
        for(int i=0; i<n; i++){
            ans.push_back('0');
        }
        int j=0;
        for(int i=0; i<n;i++){
            if(nums[i]==ans){
             ans[j]='1';
             j++;
            }
        }
        return ans;
    }
};
```

### Expected behavior

["100","000","001"], the above code fails on this testcase but overall accepted as a correct solution

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
