### ISSUE TITLE
Reference to iloc should be stated as deprecated

### ISSUE THREAD

**Issue by naphtul** [LeetCode-Feedback/LeetCode-Feedback#20521]
### LeetCode Username
naphtul

### Problem number, title, and link
2880. Select Data https://leetcode.com/problems/select-data/

### Category of the bug
- [X] Editorial

### Description of the bug
In the Editorial there's a reference to `iloc`.
It is deprecated since 2.20 as stated here: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iloc.html

### Expected behavior
It should either be removed or labeled as deprecated in the Editorial.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
