### ISSUE TITLE
Crash Id 403c434e

### ISSUE THREAD

**Issue by radhouene101** [LeetCode-Feedback/LeetCode-Feedback#20546]
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [x ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

when ever i return to home page from a problem page i get this error id: 
![leetcodebug](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/94876121/bd2a61e4-e13a-4416-99cd-90b72a04c677)

**Comment by LC-Pam** [comment]
The issue should fixed.
