### ISSUE TITLE
Missing Test Case - 144. Binary Tree Preorder Traversal

### ISSUE THREAD

**Issue by wensonH** [LeetCode-Feedback/LeetCode-Feedback#2055]
#### Your LeetCode username

wenson

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

My solution of `Binary Tree Preorder Traversal` is accepted, which run fail with my custom testcase `[1, 2, null, 3, null, 4, null, 5, null, 6, null, 7, null, 8, null, 9]`. Testcase doesnt cover the extreme case.

#### Code you used for Submit/Run operation

```
//  Binary Tree Preorder Traversal
int* preorderTraversal(struct TreeNode* root, int* returnSize){
    struct TreeNode** nodes = (struct TreeNode**) malloc(sizeof(struct TreeNode*) * 8);
    int top = 0;
    int * data = (int *) malloc(sizeof(int) * 100);
    *returnSize = 0;
    struct TreeNode *p = root, *q;
    while ( p != NULL || top > 0) {
        if ( p != NULL ) {
            if(p->val != NULL) {                
                data[(*returnSize)++] = p->val;
            }
            nodes[top++] = p;
            p = p->left;
        } else {
            q = nodes[--top];
            p = q->right;
        }
    }
    return data;
}
```

#### Language used for code
C

#### Expected behavior

cause a runtime error

**Comment by lc-kay** [comment]
Hi @wensonH 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @wensonH 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
