### ISSUE TITLE
Desciption typo - 2987. Find Expensive Cities

### ISSUE THREAD

**Issue by xelplogoog** [LeetCode-Feedback/LeetCode-Feedback#20556]
### LeetCode Username
c4tdog

### Problem number, title, and link
[2987. Find Expensive Cities](https://leetcode.com/problems/find-expensive-cities/)

### Description of the bug
There is a typo in example 1: real national average price is `5,574,304.90`

<img width="394" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2188302/6b899f15-4d4e-4dd6-a89a-124e6b424875">

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team

**Comment by xelplogoog** [comment]
вы валеты?
