### ISSUE TITLE
Description typo - 2153. The Number of Passengers in Each Bus II

### ISSUE THREAD

**Issue by xelplogoog** [LeetCode-Feedback/LeetCode-Feedback#20557]
### LeetCode Username
c4tdog

### Problem number, title, and link
[2153. The Number of Passengers in Each Bus II](https://leetcode.com/problems/the-number-of-passengers-in-each-bus-ii/)

### Description of the bug
There is an error in example 1.

- Passenger `12` arrives at time 5.
- Passenger `13` arrives at time 6.
- Passenger `14` arrives at time 7.

must be

- Passenger `13` arrives at time 5.
- Passenger `14` arrives at time 6.
- Passenger `15` arrives at time 7.

also

Bus 3 arrives at time 7 and collects passengers `12 and 13` as it has two empty seats.

must be

Bus 3 arrives at time 7 and collects passengers `13 and 14` as it has two empty seats.

since the passenger 12 is already taken by 2nd bus

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/2188302/2eeca1a8-0971-4028-bea5-e2a18cc2b793)

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback. We encourage you to share your questions in the discussion forum, where the community can provide insights and assistance.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
