### ISSUE TITLE
50. Pow(x, n). Correct solution doesn't pass in PHP

### ISSUE THREAD

**Issue by rroma** [LeetCode-Feedback/LeetCode-Feedback#20561]
### LeetCode Username

rroma

### Problem number, title, and link

50. Pow(x, n) https://leetcode.com/problems/powx-n/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [x] Programming language support

### Description of the bug
Correct solution doesn't pass

### Language used for code

`PHP`
### Code used for Submit/Run operation

```PHP
class Solution {

    /**
     * @param Float $x
     * @param Integer $n
     * @return Float
     */
    function myPow($x, $n) {
        $result = 1;
        $pow = abs($n);

        if ($pow === 0) {
            return $result;
        }

        while ($pow > 1) {
            if ($pow % 2 !== 0 && $pow > 1) {
                $result *= $x;
            }

            $pow = (int)($pow / 2);

            $x *= $x;
        }

        $result *= $x;

        if ($n < 0) {
            return 1/$result;
        }

        return $result;
    }
}
```

### Expected behavior

All test cases passed

### Screenshots

<img width="571" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/8502584/5965a534-6dc5-4d27-b0c5-2749c9569720">

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
