### ISSUE TITLE
Missing Test Case - 1646. Kth Missing Positive Number

### ISSUE THREAD

**Issue by sourav1122** [LeetCode-Feedback/LeetCode-Feedback#2056]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by sourav1122** [comment]
made changes

**Comment by lc-kay** [comment]
@sourav1122 Please include your accepted solution and the missing test case you wish to report.

**Comment by lc-kay** [comment]
Hi @sourav1122 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
