### ISSUE TITLE
Weak constraints - 410. Split Array Largest Sum

### ISSUE THREAD

**Issue by msluszniak** [LeetCode-Feedback/LeetCode-Feedback#20562]
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [x] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
The data constraints are too loose. The inefficient code get accepted.

### Language used for code
C++

### Code used for Submit/Run operation

```cpp
  int splitArray(vector<int>& nums, int k) {
      const int n = nums.size();
      vector<vector<int>> dp(n+1, vector<int>(k, INT_MAX));
      dp[0][0] = 0;
      for(int i = 1; i <= n; ++i){
          dp[i][0] = dp[i-1][0] + nums[i-1];
      }

      for(int i = 1; i <= n; ++i){
          for(int j = 0; j < i; ++j){
              for(int l = 1; l < k; ++l){
                  dp[i][l] = min(dp[i][l], max(dp[j][l-1] , dp[i][0] - dp[j][0]));
              }
          }
      }

      return dp[n][k-1];
  }
```

### Expected behavior
I suppose that this dynamic solution should not be accepted in this question. The constrains on $n$ and $k$ in this task ought to be higher so only the optimal binary search will be accepted.

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/56299341/f089301c-73b5-47a5-8e07-e196e911429d)

**Comment by stormsunshine** [comment]
This problem is designed for both dynamic programming and binary search. Both ways should be accepted. The run time can show the difference between the time complexities of the two different approaches.

There is no need to restrict a problem to only one possible solution.

**Comment by msluszniak** [comment]
Ok, you convinced me. I though that Python implementation won't be accepted in the given time constraints, but actually it passes ;)
