### ISSUE TITLE
Error  Test Case - 28. Find the Index of the First Occurrence in a String

### ISSUE THREAD

**Issue by maybesravan** [LeetCode-Feedback/LeetCode-Feedback#20580]
### LeetCode Username

SRAVANKUMAR2001

### Problem number, title, and link

28. Find the Index of the First Occurrence in a String](https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/)

### Category of the bug
- [x] Problem description
- [x] Solved examples
- [x] Problem constraints
- [x] Problem hints
- [x] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [x] Programming language support

### Description of the bug

errror on the test case  number :9 , 
error like :=================================================================
==23==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000000374 at pc 0x564682cde7f8 bp 0x7ffed4764980 sp 0x7ffed4764970
READ of size 1 at 0x602000000374 thread T0
    #2 0x7f59c6605d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
    #3 0x7f59c6605e3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e3f)
0x602000000374 is located 0 bytes to the right of 4-byte region [0x602000000370,0x602000000374)
allocated by thread T0 here:
    #0 0x7f59c6fd5887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #3 0x7f59c6605d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
Shadow bytes around the buggy address:
  0x0c047fff8010: fa fa 06 fa fa fa 04 fa fa fa 06 fa fa fa 03 fa
  0x0c047fff8020: fa fa 04 fa fa fa 06 fa fa fa 04 fa fa fa 04 fa
  0x0c047fff8030: fa fa 02 fa fa fa 02 fa fa fa 04 fa fa fa 04 fa
  0x0c047fff8040: fa fa 02 fa fa fa 04 fa fa fa 04 fa fa fa 02 fa
  0x0c047fff8050: fa fa 04 fa fa fa 04 fa fa fa 03 fa fa fa 04 fa
=>0x0c047fff8060: fa fa 04 fa fa fa 04 fa fa fa 04 fa fa fa[04]fa
  0x0c047fff8070: fa fa 05 fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8080: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8090: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff80a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff80b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==23==ABORTING

### Language used for code

c

### Code used for Submit/Run operation

```
int strStr(char* haystack, char* needle) {
    for(int i=0;i<=strlen(haystack)-strlen(needle);i++)
    {
        int j;
        for(j=0;j<strlen(needle);j++){
        if(haystack[i+j]!=needle[j])
            break;}
        if(j==strlen(needle))
            return i;
    }
    return -1;

}
```

### Expected behavior

In the run  section we are getting a good output after submitting we had a problem

**Comment by JustJie2002** [comment]
strlen returns unsigned so it can only be non-negative, therefore when strlen(haystack) < strlen(needle) you will get some weird interactions. Set those 2 as an integer variable and use those instead.

**Comment by JustJie2002** [comment]
I'm submitting your code and you're getting the same output from the same test case.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback. We encourage you to share your questions in the discussion forum, where the community can provide insights and assistance.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
