### ISSUE TITLE
Missing Test Case - 201. Bitwise AND of Numbers Range

### ISSUE THREAD

**Issue by MSHarish004** [LeetCode-Feedback/LeetCode-Feedback#20586]
![Screenshot 2024-02-21 215249](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/102298941/511db4dc-047e-495d-a887-af5a6a9e90cb)

### LeetCode Username

MSHarish004

### Problem number, title, and link

201.Bitwise AND of Numbers Range
link: "https://leetcode.com/problems/bitwise-and-of-numbers-range/description/?source=submission-ac"

### Category of the bug
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

Insufficient of testcase people can easily fake the problem 

### Language used for code

JAVA

### Code used for Submit/Run operation

class Solution {
    public int rangeBitwiseAnd(int left, int right) {
        int ans=left;
        if((right-left)>1073741823) return 0;
        if(right==2147483647) return left;
        for(int i=left;i<=right;i++){
            ans=ans&i;
        }
        return ans;
    }
}

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

### Expected behavior

left = 2147000000
right = 2147483647
Expected= 2146959360

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.
Details regarding the missing test case.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team
