### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by Curious-Buddy777** [LeetCode-Feedback/LeetCode-Feedback#20583]
There is a code that said to run in 0 milli Seconds, but it has a bug that no test case is covering.
My main of motif of writing this message to address the issue
The given below code has a bug yet no test case looks to notice it.

![Two Sum - LeetCode - Google Chrome 21-02-2024 18_54_20](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/155570129/0ee9a28e-02b0-4c5a-91a9-6502bdb011ff)
So the image has this code : 

### LeetCode Username

Sohan_Bhattacharya

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [*** ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The code above has a defect that, at a particular index it compares with itself once for every iteration when it searches for a two Sum.

### Language used for code

Java is used to write the code.
### Code used for Submit/Run operation

```
class class class Solution {
    public int[] twoSum(int[] nums, int target) {
       int[] arr = new int[2];
       int j = 1;

       while(j < nums.length){
           for(int i = 0; i+j < nums.length; i++){
               if(target == nums[i]+nums[i+j]){
                   arr[0] = i;
                   arr[1]= i+j;
                   return arr;
               }
           }
           j++;
       }
       return arr;
    }
}
```

### Expected behavior

While searching for two elements who's sum is equal to the target element, we should check a particular index with every other element **except itself** , i.e we should not check by adding element at index 2 with element 2 itself , but among remaining elements. 
### Screenshots

![Interview prep – Solution java 21-02-2024 19_16_00](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/155570129/fa5fc077-9696-4c2c-828f-b458647c52a4)

### Additional context

In the above screensort, we can see that there is no possible combination but by adding an element with itself it is returning the answer [0,0] i.e. it is adding with itself.

**Comment by jc1651** [comment]
I think don't your solution is wrong. This is just the same as a nested for loop except you chose to increase the difference between i and j each layer. given that j is positive, there's no chance for i to be equal to i + j. In your print statement, you're choosing to print out a[j] and that is wrong because you're summing a[i] and a[i + j] not a[j] to some other elements. Also, "You may assume that each input would have exactly one solution", in your test case you had no solution that summed up to 5, therefore you're returning the initial "arr" that had 0 in arr[0] and arr[1].
