### ISSUE TITLE
2887. Fill Missing Data - editorial incorrect data

### ISSUE THREAD

**Issue by akazakov-github** [LeetCode-Feedback/LeetCode-Feedback#20594]
### Problem number, title, and link
2887. Fill Missing Data https://leetcode.com/problems/fill-missing-data/editorial/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug
In the Intuition section:
> Finally, we want to return the original DataFrame, so we set inplace=True to modify the original DataFrame directly without returning a new one. Note that if you don't use inplace=True, you would have to capture the result like this: **```products = products['quantity'].fillna(0)```**

should be
```
products['quantity'] = products['quantity'].fillna(0)
```

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/74555777/f3525b9a-ab2b-4027-bfc8-d27bb5a0365e)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team
