### ISSUE TITLE
Missing Test Case - 1683. Invalid Tweets

### ISSUE THREAD

**Issue by rais-github** [LeetCode-Feedback/LeetCode-Feedback#20591]
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ✔️] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

Description of the bug
The existing test cases provided in the example and during submission do not handle cases where the user or tweet's content contains special symbols, emojis, and others. The current implementation uses the LENGTH function, which is incorrect. It should use the CHAR_LENGTH function instead.

Language used for code
MySQL

Code used for Submit/Run operation
sql
Copy code
-- Paste your code here. Don't remove ``` given
-- above and below the code.

-- Replace the code below with your code.

SELECT tweet_id, content, user_id
FROM Tweets
WHERE CHAR_LENGTH(content) > 15;
Expected behavior
The code should use CHAR_LENGTH instead of LENGTH to handle cases where the user or tweet's content contains special symbols, emojis, and others.

Screenshots
N/A

Additional context
The issue is related to the incorrect usage of the LENGTH function instead of CHAR_LENGTH when checking the length of the tweet's content. The correction is necessary to handle special symbols and emojis properly.

Example case = "Leetc☼de is the best platform for growing ↑"

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.


Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team
