### ISSUE TITLE
Missing Test Case - 2093. Minimum Cost to Reach City With Discounts

### ISSUE THREAD

**Issue by zoed191** [LeetCode-Feedback/LeetCode-Feedback#20595]
### Problem number, title, and link

2093\. Minimum Cost to Reach City With Discounts https://leetcode.com/problems/minimum-cost-to-reach-city-with-discounts/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Submissions without tracking costs by used-discounts are accepted due to lack of test cases. For example,

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/72279087/ab7c6895-bf25-47e5-98cc-84a263cf04ae)

```
4
[[0,1,50],[0,2,30],[2,1,10],[1,3,1000]]
1
```
The expected answer is `540` from node 0 to node 3 by using at most 1 discount:
* From node 0 to node 2 without using discount, resulting in accumulated cost of `0 + 30 = 30`.
* From node 2 to node 1 without using discount, resulting in accumulated cost of `30 + 10 = 40`.
* From node 1 to node 3 using discount, resulting in accumulated cost of `40 + 1000 // 2 = 540`.

Without tracking costs by the number of used discounts, the minimum cost from node 0 to node 1 is `50 // 2 = 25`, by using the only discount at the first highway `0 --discounted--> 1`. The path `0 --> 2 --> 1` with no discounts will not be tracked because its accumulated cost `30 + 10 = 40` is higher than the minimum cost of `25` updated in an earlier step. Incorrectly neglecting to track the path `0 --> 2 --> 1` will limit the search to `0 --discounted--> 1 --> 3 (25 + 1000 = 1025)` and `0 --> 1 -->3 (50 + 1000 // 2 = 550)`, which is sub-optimal compared with `0 --> 2 --> 1 --discounted--> 3 (540)`.

### Language used for code

Python3

### Code used for Submit/Run operation

Following is a code sample from accepted submissions (first in the pop-up window if clicked the left-most bar at 192ms). 
This code sample did not track the minimum distance from the source node to other nodes by the number of discounts applied (see comments).

This code sample runs fast (Runtime: 192ms) but will return incorrect answer to proposed new test case.

```python
class Solution:
    def minimumCost(self, n: int, highways: List[List[int]], discounts: int) -> int:
        
        map_cities = defaultdict(list)

        for way in highways:
            u, v, d = way
            map_cities[u].append([v, d])
            map_cities[v].append([u, d])
        
        q = deque()
        q.append((0, discounts, 0))

        distances = [inf] * n
        discounts = [inf] * n  # actually not used

        distances[0] = 0
        discounts[0] = discounts # actually not used


        while q:
            dist, disc, node = q.popleft()

            for next_node, d in map_cities[node]:
                if dist + d < distances[next_node]:
                    distances[next_node] = dist + d
                    q.append((dist + d, disc, next_node))
                if disc > 0:
                    if dist + d//2 < distances[next_node]:
                        distances[next_node] = dist + d//2
                        q.append((dist + d//2, disc - 1, next_node))
        
        return distances[-1] if distances[-1] != inf else -1
```

### Expected behavior

Submissions without tracking costs by used-discounts shouldn't have been accepted. We need more test cases like the one proposed earlier to identify incorrect solutions.

### Additional context

A screenshot of the code sample listed above, the results demonstrate the proposed test case can help identify solutions without tracking costs by used-discounts.
<img width="1080" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/72279087/8b883311-708a-49cc-a567-2e869a2fc954">

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
