### ISSUE TITLE
Incorrect strategy name

### ISSUE THREAD

**Issue by mdtareque** [LeetCode-Feedback/LeetCode-Feedback#206]
**What kind of the bug**
- [ ] problem
- [x] solution
- [ ] language

**Describe the bug**
Problem 78. Subsets. The solution/ariticle mentions three general strategies to solve the problem.

Strategy 1 is incorrectly mentioned as `Recursion`, while it's actually not recursion.

The strategy should be name `Constructuve Approach` or something else .

Why this should be fixed?
- To be semantically correct
- To avoid confusion regarding _Recursion_ in minds of begineers.

**what language is your code written in**
N/A

**The code you submit/run**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Additional context**
Aritcle: https://leetcode.com/articles/subsets

**Comment by CooperCooperCooper** [comment]
Hi @mdtareque,
Thank you for reaching out to us. I've relayed your feedback to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @
Thank you for your time. We've used your feedback to update the approach name. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
