### ISSUE TITLE
Submission Error - For C#, submission error is shown incorrectly for Remove Element question

### ISSUE THREAD

**Issue by ashishsharma17111988** [LeetCode-Feedback/LeetCode-Feedback#20602]
### Problem number, title, and link  
27. Remove Element (https://leetcode.com/problems/remove-element/)

### Category of the bug
- [ ] Incorrect Submission & Run Error

### Description of the bug
I was working on this problem. I wrote the code in C# & verified the code in Visual Studio also. There is no issue with the code but LeetCode is throwing solution is incorrect. Since for C# debugger is not provided, I tried in VS and worked without any issue.

### Language used for code
C#

### Code used for Submit/Run operation
```
public class Solution {
    public int RemoveElement(int[] nums, int val) {
        int i = 0, j = 0, counter = 0;
        int temp;
        while (i < nums.Length)
        {
            if (nums[i] != val)
            {
                i++;
            }
            else
            {
                j = i+1;
                while (j < nums.Length)
                {
                    if (nums[j] != val)
                    {
                        counter++;
                        temp = nums[i];
                        nums[i] = nums[j];
                        nums[j] = temp;
                        break;
                    }
                    else
                        j++;
                }
                i++;
            }
        }
        return counter;
    }
}
```

### Expected behavior
Submission should have shown all Test Cases as passed since it worked find in other IDE

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/160814511/a5818331-acce-45ae-b77a-79cafb862f92)

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
