### ISSUE TITLE
Missing Test Case - 997. Find the Town Judge

### ISSUE THREAD

**Issue by iampaulidrobo** [LeetCode-Feedback/LeetCode-Feedback#20604]
### Problem number, title, and link
[997. Find the Town Judge](https://leetcode.com/problems/find-the-town-judge/)

### Category of the bug

- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*-For the tescase2 and testcase52 ,the output
comes different for the same input which is given.

### Language used for code
 C++ 

### Code used for Submit/Run operation

class Solution {
public:
    int findJudge(int n, vector<vector<int>>& trust) {

        int sum{0};
        for (int i = 0; i < trust.size(); i++) {
             sum=sum+trust[i][0];
        }
        int temp=((n)*(n+1))/2;
        int diff=temp-sum;
        return diff>0?diff:-1;
    }
};
```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
