### ISSUE TITLE
Missing Test Case - 115. Distinct Subsequences

### ISSUE THREAD

**Issue by manwin99** [LeetCode-Feedback/LeetCode-Feedback#20615]
### LeetCode Username

singhmanwin
### Problem number, title, and link

[115. Distinct Subsequences](https://leetcode.com/problems/distinct-subsequences/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ 1] Incorrect or missing "Related Topics"
- [1 ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

It didn't execute for a certain testcase. Instead of printing the correct output it printed -1

### Language used for code

Java

### Code used for Submit/Run operation

```
class Solution {
    public int numDistinct(String s, String t) {
        int[][] ans=new int[s.length()][t.length()];
	    for(int[] arr:ans){
	        Arrays.fill(arr,-1);
	    }
	    return dfs(s,t,ans,0,0);
    }
    public int dfs(String s,String t,int[][] ans,int i,int j){
        if(j>=t.length()){
            return 1;
        }
        if(i>=s.length()){
            return 0;
        }
        if(ans[i][j]!=-1){
            return ans[i][j];
        }
        if(s.charAt(i)==t.charAt(j)){
            return ans[i][j]=dfs(s,t,ans,i+1,j+1)+dfs(s,t,ans,i+1,j);
        }
        return ans[i][j]=dfs(s,t,ans,i+1,j);
        
    }
}```


### Expected behavior
<!-- A clear and concise description of what was expected to happen in
contrast with what happened. -->

1) For the test cases s="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
ans t="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
The expected output should be 113682594
but the expected output was -1

2) The missing topic was memoization

### Screenshots
<!-- If applicable, add screenshots to explain the issue. -->
![Screenshot (179)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/88674023/046e96bb-25b0-4ed5-9b65-c990f1070957)



### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
