### ISSUE TITLE
Missing Test Case - 297. Serialize and Deserialize Binary Tree

### ISSUE THREAD

**Issue by larrygao2000** [LeetCode-Feedback/LeetCode-Feedback#2061]
#### Your LeetCode username
larrygao2000

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Missing test cases for negative or large value for TreeNode.

#### Code you used for Submit/Run operation

```
public class Codec {
    // Encodes a tree to a single string.
    public String serialize(TreeNode root) {
        StringBuilder sb = new StringBuilder();
        encode(root, sb);
        return sb.toString();
    }
    
    private void encode(TreeNode root, StringBuilder sb) {
        if (root == null) {
            sb.append("#");
            return;
        }
        sb.append((char)(root.val + '0'));
        encode(root.left, sb);
        encode(root.right, sb);
    }

    // Decodes your encoded data to tree.
    public TreeNode deserialize(String data) {
        if (data == null || data.length() == 0) return null;
        return decode(data, new int[1]);
    }
    
    private TreeNode decode(String data, int[] pos) {
        if (pos[0] == data.length()) return null;
        char c = data.charAt(pos[0]++);
        if (c == '#') return null;
        TreeNode root = new TreeNode(c - '0');
        root.left = decode(data, pos);
        root.right = decode(data, pos);
        return root;
    }
}
```

#### Language used for code
Java

#### Expected behavior

The solution is accepted:

Time Submitted | Status | Runtime | Memory | Language
-- | -- | -- | -- | --
01/17/2021 22:58 | Accepted | 3 ms | 44.8 MB | java

This solution assumes TreeNode value is positive and the result of 'val + '0' can be represented by a char. It cannot pass any test case with negative val in TreeNode or large value in TreeNode.

For example, it fails the test case below:

Wrong Answer
Runtime: 0 ms
Your input [1,2,-13,null,null,4,5]
Output [1,2]
Expected [1,2,-13,null,null,4,5]

**Comment by lc-kay** [comment]
Hi @larrygao2000 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @larrygao2000 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
