### ISSUE TITLE
Missing Test Case - 1245. Tree Diameter

### ISSUE THREAD

**Issue by mimoidochi** [LeetCode-Feedback/LeetCode-Feedback#20624]
### LeetCode Username

mimoidochi

### Problem number, title, and link

1245. Tree Diameter https://leetcode.com/problems/tree-diameter/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

A solution using dfs with wrongfully initialized 'visited' parameter is accepted.

### Language used for code

Python

### Code used for Submit/Run operation

```
class Solution:
    def treeDiameter(self, edges: List[List[int]]) -> int:
        adj = defaultdict(list)
        for x, y in edges:
            adj[x].append(y)
            adj[y].append(x)
        m = 0
        def dfs(node: int, seen) -> int:
            nonlocal m
            if len(adj[node]) == 1:
                return 0
            paths = []
            for child in adj[node]:
                if child in seen:
                    continue
                seen.add(child)
                paths.append(dfs(child, seen) + 1)
            paths.sort()
            if len(paths) > 1:
                m = max(m, paths[-1] + paths[-2])
            return paths[-1]
        i = 0
        while i < len(edges) and len(adj[i]) == 1:
            i += 1
        if i == len(edges):
            return i
        dfs(i, set([0]))
        return m
```

### Expected behavior

 A test case [[0,1], [1, 2]] would've catch the bug. The above code passes the tests and is accepted, but fails for the suggested test case. If I fix the problem in the line 27 and initialize the `seen` parameter as set([i]), the code passed the suggested test case as well.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
