### ISSUE TITLE
 1. Two Sum

### ISSUE THREAD

**Issue by ZeeshanKhan312** [LeetCode-Feedback/LeetCode-Feedback#2063]
int* twoSum(int* nums, int numsSize, int target, int* returnSize)
{
    *returnSize=2;
    int i,j;
    int *temp=(int*)malloc(sizeof(int)*2);
    for(i=0;i<numsSize;i++)
    {
        for(j=i+1;j<numsSize;j++)
        {
           if((nums[i]+nums[j])==target)
           {
               temp[0]=i;
               temp[1]=j;
               return temp;
           }
        }
    }
    return NULL;
}

**Comment by lc-kay** [comment]
@ZeeshanKhan312 If you wish to post your code for others to see, please do so on the discuss tab of the problem. 

We encourage you to share more content-related issues here with us for [valid content contribution rewards](https://leetcode.com/discuss/general-discussion/526802/File-Problem-and-Solution-Content-Issues-to-Our-GitHub-Public-Feedback-Repo-Now!). Thank you again for your support and understanding.
