### ISSUE TITLE
Missing Test Case - 70. Climbing Stairs

### ISSUE THREAD

**Issue by segreb** [LeetCode-Feedback/LeetCode-Feedback#20647]
### LeetCode Username
segreb

### Problem number, title, and link
70. Climbing Stairs https://leetcode.com/problems/climbing-stairs/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
Test cases always run with n=2 or n=3. I have never seen other values.

### Language used for code
Python

### Code used for Submit/Run operation
```
class Solution(object):


    def climbStairs(self, n):
        """
        :type n: int
        :rtype: int
        """
        if n <= 0:
            return 0

        variants = 0
        step1 = 1
        step2 = 0
        k = 1
        while k <= n:
            variants = step1 + step2
            step1, step2 = variants, step1
            k += 1
        return variants
```

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
