### ISSUE TITLE
Missing Test Case - 1245. Tree Diameter

### ISSUE THREAD

**Issue by simplyrish** [LeetCode-Feedback/LeetCode-Feedback#20649]
simplyrishi

### Problem number, title, and link

1245. Tree Diameter
   link - https://leetcode.com/problems/tree-diameter/description/?envType=weekly-question&envId=2024-02-22

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
Array of edges always go from parent to child. i.e edge[a,b] means a is parent and b is child. or at least it appears to be.
My code worked and passed all teh test cases when i used this assumption. 
But failed when i tested with the edge where one edge i gave was from child to parent though others code passed. 

### Language used for code
Java

### Code used for Submit/Run operation

```
class Solution {

    int check(int root, HashMap<Integer, LinkedList<Integer>> map, int[] local) {
        if (!map.containsKey(root))
            return 1;

        LinkedList<Integer> neighbor = map.get(root);

        if (neighbor.size() == 1) {

            int left = check(neighbor.getFirst(), map, local);
            if (local[0] < left + 1)
                local[0] = left + 1;
            return left + 1;

        } else {

            int var = 0;
            PriorityQueue<Integer> q = new PriorityQueue<Integer>((a, b) -> b - a);
            int left=0;
            int right=0;

            for (int i = 0; i < neighbor.size(); i++) {
                var = check(neighbor.get(i), map, local);
    
                if( Math.min(left, right) < var  )
                {
                  if(left>right)
                    right=var;
                else
                    left=var;
                }
       
                    
                
            }

            if (local[0] < left + right + 1)
                local[0] = left + right + 1;
            return left > right ? left + 1 : right + 1;

        }
    }

    public int treeDiameter(int[][] edges) {

        HashMap<Integer, LinkedList<Integer>> map = new HashMap<Integer, LinkedList<Integer>>();

        HashSet<Integer> allNodes = new HashSet<Integer>();
        HashSet<Integer> childNodes = new HashSet<Integer>();
        if (edges == null || edges.length == 0)
            return 0;

        for (int[] edge : edges) {
            int parent = edge[0];
            int child = edge[1];

            allNodes.add(parent);
            childNodes.add(child);

            LinkedList<Integer> list = map.getOrDefault(parent, new LinkedList<Integer>());
            list.add(child);
            map.put(parent, list);
        }

        allNodes.removeAll(childNodes);

        if (allNodes.size() != 1)
            return 0;

        int root = 0;
        for (int i : allNodes)
            root = i;
        int[] local = new int[1];
        int result = check(0, map, local);

        return local[0] - 1;

    }
}
```

### Expected behavior

When using given test case 
[[0,1],[1,2],[2,3],[1,4],[4,5]]
code passes.

If we change it to test case
[[1,0],[1,2],[2,3],[1,4],[4,5]] code fails.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team
