### ISSUE TITLE
Missing testcase in 560. Subarray Sum Equals K

### ISSUE THREAD

**Issue by satheesh1022005** [LeetCode-Feedback/LeetCode-Feedback#20640]
### LeetCode Username

user name: satheesh1022005
### Problem number, title, and link

560. Subarray Sum Equals K (https://leetcode.com/problems/subarray-sum-equals-k/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

 Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
Input
nums =
[-1,1,0,0,1]
k =
0
Output
4
Expected
6
For Example:
For N = 5, and Arr = {1, -1, 0, 0, 1}, 
We have the following subarrays with zero sums: 
{{1, -1}, {1, -1, 0}, {1, -1, 0, 0}, {-1, 0, 0, 1}, {0}, {0, 0}, {0}}
Among these subarrays, {1, -1, 0, 0} and {-1, 0, 0, 1} are the longest subarrays with their sum equal to zero. Hence the answer is 4. So the expected output is wrong.

### Language used for code

Java

### Code used for Submit/Run operation

```
class Solution {
    public int subarraySum(int[] nums, int k) {
        if(nums.length==1){
            if(nums[0]==k){
                return 1;
            }
        }
        int i=0,j=0,sum=0,cnt=0;
        while(i<nums.length){
            sum+=nums[i];
            while(j<nums.length&&sum>k){
                sum-=nums[j];
                j++;
            }
            if(sum==k){
                cnt++;
            }
            i++;
        }
        return cnt;
    }
}
```

### Expected behavior

To add this testcase for this problem statement

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/129524670/6de98093-fe23-4178-bf3a-1efb896f64e3)

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
