### ISSUE TITLE
两数之和输出bug(88. Merge Sorted Array Bug：Describing problems in two languages)

### ISSUE THREAD

**Issue by yuanhepeng** [LeetCode-Feedback/LeetCode-Feedback#20659]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

### LeetCode 用户名

yuanhepeng

### 问题号码、标题和链接

https://leetcode.cn/problems/merge-sorted-array/?envType=study-plan-v2&envId=top-interview-150

### Bug 类型
- [x] 问题描述
- [ ] 示例
- [ ] 问题限制
- [ ] 问题提示
- [x] 不正确或缺少“相关标签”
- [ ] 不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*
- [ ] 缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*
- [ ] 力扣官方题解
- [ ] 编程语言支持

### 描述

我创建临时数组temp,然后把nums1和nums2的值都放入临时数组，然后把temp赋值给nums1,没有通过case1，idea是可以的，sys标准输出也可以。咱们的输出是不是读取的最初的nums1的内存地址，而不是nums1变量最终指代的值
-------------------------------------------------------------------------------------------------------------------------
I create a temporary array called temp, then put the values of nums1 and nums2 into the temporary array, and assign the value of temp to nums1. If it doesn't pass case1, idea works, and sys standard output works as well. Is our output reading the initial memory address of nums1, rather than the final value referred to by the nums1 variable

### 你使用的语言

Java

### 你提交或者运行的代码

```
    public static void merge(int[] nums1, int m, int[] nums2, int n) {
        if(m == 0) {
            nums1 = nums2;
            return;
        }

        int[] temp = new int[m + n];

        for(int i = 0; i < m; i++) {
            temp[i] = nums1[i];
        }

        if(n == 0) {
            Arrays.sort(nums1);
            return;
        }

        int count = 0;

        for(int i = nums1.length - n; i < nums1.length; i++) {
            temp[i] = nums2[count];
            count++;
        }

        nums1 = temp;
        Arrays.sort(nums1);
        System.out.println(Arrays.toString(nums1));

    }
```

### 期望行为

case1应该通过
----------------
Case 1 should be passed through

### 屏幕截图

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/39111057/3fc3157c-b8c5-4ab2-8d7c-6f9a23c06781)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/39111057/fb41e66d-10c0-49ad-a67c-6bf34119dfd2)

**Comment by yuanhepeng** [comment]
@LC-Pam Hey, buddy, what does the LCCN label mean?

**Comment by amcones-lc** [comment]
您好，在与相关团队核实后：***不处理***（需要原地修改，题目行为符合预期）。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。

**Comment by yuanhepeng** [comment]
> 您好，在与相关团队核实后：_**不处理**_（需要原地修改，题目行为符合预期）。 以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。

您可以看一下我本地ide的截图，显而易见，题目描述并不严谨@amcones-lc

**Comment by amcones-lc** [comment]
@yuanhepeng 这与 Java 语言特性有关，Java 只有值传递，你的赋值只是对参数赋值。可以使用其他语言如 C++ 尝试确认。

**Comment by yuanhepeng** [comment]
> @yuanhepeng 这与 Java 语言特性有关，Java 只有值传递，你的赋值只是对参数赋值。可以使用其他语言如 C++ 尝试确认。
@amcones-lc
首先，Java是有引用传递的。
其次，题目和输出不应当考虑语言特性吗？
最后，无论怎么说，抛不开的一点是题目存在不严谨的情况，为什么不去考虑优化，而是甩锅给语言呢？
