### ISSUE TITLE
Missing Test Case - 128. Longest Consecutive Sequence

### ISSUE THREAD

**Issue by zoller27osu** [LeetCode-Feedback/LeetCode-Feedback#2065]
#### Your LeetCode username

ProcZ

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
For many languages (C++, Python3, Python) the sorting solution can easily beat the best times of the set solution. I'm not sure if this is a flaw in the problem specs, or the test cases, but a theoretically O(n log(n)) solution should not be consistently performing as well as O(n) solutions.

**Comment by lc-kay** [comment]
Hi @zoller27osu 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@zoller27osu Our team has reviewed your report and ruled it invalid. This is because n is less than 1e4. We don't intend to change the constraints, and this should not be an issue. Thank you for your time.
