### ISSUE TITLE
Missing Test Case - 1361. Validate Binary Tree Nodes

### ISSUE THREAD

**Issue by Dzmitry-Bialotski** [LeetCode-Feedback/LeetCode-Feedback#20653]
### LeetCode username
[dimasiandro](https://leetcode.com/dimasiandro)

### Problem number, title, and link
[1361. Validate Binary Tree Nodes](https://leetcode.com/problems/validate-binary-tree-nodes/) 

### Category of the bug
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

findRoot function that I wrote doesn't return the correct root of the tree, but it is fine for all test cases for some reason. Here is the test case that won't pass:
 n = 4;  leftChild = [-1,2,0,-1]; rightChild = [-1,3,-1,-1];
I assume all positive test cases contain search trees, while my test case doesn't.

### Language used for code
JS 

### Code used for Submit/Run operation

```
/**
 * @param {number} n
 * @param {number[]} leftChild
 * @param {number[]} rightChild
 * @return {boolean}
 */
const validateBinaryTreeNodes = (n, leftChild, rightChild) => {
    const findRoot = (leftChildren, rightChildren) => {
        let root = 0;
        for(let i = 0; i < leftChildren.length; i++) {
            if(leftChildren[i] === root || rightChildren[i] == root) root = i;
        }
        return root;
    }

    const visited = new Set();

    const dfs = (currentNode) => {
        if(visited.has(currentNode)) return false;
        visited.add(currentNode);
        if(leftChild[currentNode] !== -1) {
            if(!dfs(leftChild[currentNode])) return false;
        }
        if(rightChild[currentNode] !== -1) {
            if(!dfs(rightChild[currentNode])) return false;
        }
        return true;
    }
    const root = findRoot(leftChild, rightChild);
    return dfs(root, leftChild, rightChild) && visited.size === n;
};
```

### Expected behavior

new test case is supposed to be a correct binary tree. The provided code results, that the tree is not valid for the test case that I wrote, but it passes all current test cases,

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/62600973/87f27807-7a50-415f-a08e-f93732803093)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team
