### ISSUE TITLE
Missing Test Case - 978. Longest Turbulent Subarray

### ISSUE THREAD

**Issue by jstefanzick** [LeetCode-Feedback/LeetCode-Feedback#20650]
### LeetCode Username

stefanzi

### Problem number, title, and link

978. Longest Turbulent Subarray https://leetcode.com/problems/longest-turbulent-subarray/

### Category of the bug
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

Code below passes all test cases included with problem, however would fail ex test case of [10, 9, 11] - a test case where all integers added up and divided by length of arr is equal to arr[0]. 

### Language used for code

Python3

### Code used for Submit/Run operation

```
class Solution:
    def maxTurbulenceSize(self, arr: List[int]) -> int:

        #### this section should fail a test case of ex. [10, 9, 11], however it still passes all included test cases
        if sum(arr) / len(arr) == arr[0]:
            return 1
        #### end section

        max_length = 2
        cur = 0

        for i in range(len(arr) - 2):
            if arr[i] < arr[i + 1] > arr[i + 2] or arr[i] > arr[i + 1] < arr[i + 2]:
                if cur == 0:
                    cur = 3
                else:
                    cur += 1
            else:
                cur = 2
            max_length = max(max_length, cur)

        return max_length
```

### Expected behavior

Code checks for edge case where all integers in arr are the same by adding up all integers and dividing by length of arr. 

If the result of this operation is equal to the arr[0], then code assumes that entire array is made up of same numbers and concludes that longest turbulent subarray (LTS) for this case is 1. 

Using this method passes all test cases, however should fail a test case of ex. [10, 9, 11] where the ints added up equal 30, divided by 3 = 10, or arr[0]. This code would label this case's LTS as 1, but the correct answer should be 3. 

Correcting the code to 'if len(set(arr)) == 1: return 1 ' would handle this case. 

### Screenshots

<img width="1913" alt="Screenshot 2024-02-23 at 1 37 03 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/99770426/d2af4dd6-a8a3-42b2-a5e5-31ceb05de264">

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
