### ISSUE TITLE
Missing Test Case - 121. Best Time to Buy and Sell Stock

### ISSUE THREAD

**Issue by rrrraghav** [LeetCode-Feedback/LeetCode-Feedback#20652]
### LeetCode Username
rrrraghav

### Problem number, title, and link
121. Best Time to Buy and Sell Stock https://leetcode.com/problems/best-time-to-buy-and-sell-stock/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [X] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
The maximum profit can be gained by getting a value from the array (not the minimum) and comparing it with the rest, but there is no test case for this situation. The code below passes the current 2 tests provided, but should not work for this situation.

### Language used for code
Java

### Code used for Submit/Run operation

```
class Solution {
    public int maxProfit(int[] prices) {
        Map<Integer, Integer> map = new HashMap<>();
        for (int i = 0; i < prices.length; i++) {
            map.put(prices[i], i);
        }
        int minValue = Collections.min(map.keySet());
        int minIndex = map.get(minValue);
        int maxProfit = 0;
        for (int i = minIndex; i < prices.length; i++) {
            if (prices[i] - minValue > maxProfit) {
                maxProfit = prices[i] - minValue;
            }
        }
        return maxProfit;
    }
}
```

### Expected behavior
The given code passes the 2 current test cases, but it does not satisfy the needs of the problem. Adding the additional test case "[7,2,5,3,6,1]" makes the code fail, as it should.

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/124408239/7f79a25b-cfb7-4b04-a7dd-06f583b09726)

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
