### ISSUE TITLE
Missing Test Case - 2092. Find All People With Secret

### ISSUE THREAD

**Issue by kaltu** [LeetCode-Feedback/LeetCode-Feedback#20660]
### LeetCode Username

Kaltu

### Problem number, title, and link

2092. Find All People With Secret https://leetcode.com/problems/find-all-people-with-secret/description/?envType=daily-question&envId=2024-02-24

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] **Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)***
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Missing testcases to let inefficient Code get accepted.

### Language used for code

Rust

### Code used for Submit/Run operation

```Rust
// Paste your code here. Don't remove ``` given
// above and below the code.
impl Solution {
    pub fn find_all_people(n: i32, mut meetings: Vec<Vec<i32>>, first_person: i32) -> Vec<i32> {
        let mut secret = vec![false; n as usize];

        secret[0] = true;
        secret[first_person as usize] = true;

        meetings.sort_unstable_by_key(|x| x[2]);

        let mut left = 0;
        while left < meetings.len() {  // <--- loop steps over different timestamps
            let time = meetings[left][2];
            let mut shared = true;
            let mut right = left;
            while shared {   // <-- loop while there is an transaction happen in the network
                shared = false;
                right = left;
                // ↓ naively loop over all edges in the network to perform essentially an inefficient BFS ↓
                while right < meetings.len() && meetings[right][2] == time {
                    let x = meetings[right][0] as usize;
                    let y = meetings[right][1] as usize;
                    if secret[x] != secret[y] {
                        shared = true;
                        secret[x] = true;
                        secret[y] = true;
                    }
                    right += 1;
                }
            }
            left = right;
        }
        
        secret
            .into_iter()
            .enumerate()
            .filter(|x| x.1)
            .map(|x| x.0 as i32)
            .collect()
    }
}
```

### Expected behavior

Time Limit Exceeded

Since the code uses a naive BFS that iterates through every edge in the network in a loop over the graph, in the worst case such that the edges form a perfect chain that needs to propagate the secret one edge by one edge, it will take $O(m^2)$ times where $m$ is the number of meeting pairs sharing the same timestamp. Since $m <= n$, it makes the whole time complexity to be $O(n^2)$.

Despite and high time complexity, the code above is accepted and beats 100.00% of all other submissions.
The inefficiency can be proven by submitting a custom test case that is at the upper bound of the problem constraint, where
$n = 100000$
$meetings = [[1, 2,1], [2, 3, 1], [3, 4, 1], ... , [99996, 99997, 1], [99997, 99998, 1], [99998, 99999, 1]]$
$firstPerson = 99999$
will correctly result in a TLE, instead of beating 100% of submissions.

### Screenshots

https://leetcode.com/problems/find-all-people-with-secret/submissions/1184487902?envType=daily-question&envId=2024-02-24
As the screenshot shows, the testcase that is crafted such that it is exactly at the upper bound of the problem constraints will cause the code, as accepted and beating 100% of other submissions in speed, to actually get TLE
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/14264674/ed826181-d041-4ce7-a6d5-a48fce2b1529)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/14264674/5df188ea-f914-48e4-a867-b3b35bc3eb26)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.
We can’t add the test case currently because of technical issues.
If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
