### ISSUE TITLE
[200] Number of Islands - submission test cases not complex enough

### ISSUE THREAD

**Issue by SPGremlin** [LeetCode-Feedback/LeetCode-Feedback#2066]
#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language

#### Description of the bug
Submission test cases are not complex enough.
I had a solution that contained bugs but was passing submission, these bugs have only transpired with additional testing on my own test cases (randomly generated on the larger grid sizes). Plus, official test cases are not heavy enough, the solution achieved 1ms - this is too fast. Apparently, there are no maximum-sizing test cases (300x300 or even close to that).

Ready to provide my test cases if that would help.

**Comment by lc-kay** [comment]
@SPGremlin Please provide your accepted code and the failed test case. Thank you!

**Comment by SPGremlin** [comment]
Hi, the buggy code is below (**Java**), and as-of-now it is still being accepted.

`class Solution {
       
    public int numIslands(char[][] grid)
    {
        int m = grid.length;
        int n = grid[0].length;
        
        HashSet islands = new HashSet();
        
        int[] scanline = new int[n];
        
        int maxIsland = 0;
        int currentIsland = 0;
        
        for (int j=0; j < m; j++)
        {            
            for (int i=0; i < n; i++)
            {
                if (grid[j][i]=='1')    // we are on an island
                {
                    if (i == 0 || grid[j][i-1]=='0') // 0=>1 transition - looks like a new island. 
                    {
                        if (scanline[i] == 0)   // nothing above
                        {
                            maxIsland++;
                            islands.add(maxIsland);
                            currentIsland = maxIsland;                           
                        }
                        else                    // existing island above
                            currentIsland = scanline[i];
                    }
                    
                    if (scanline[i]!=0) // upper contact with a previous island
                    {
                        if (scanline[i] != currentIsland)
                        {
                            islands.remove(currentIsland);  //this was not actually a new island - remove
                            currentIsland = scanline[i];
                            
                            /*Backtracking - propagate island union to the left of the scanline*/
                            for (int b=i-1;b>=0;b--)
                            {
                                if (scanline[b]!=0 && scanline[b]!=currentIsland)
                                    scanline[b]=currentIsland;
                                else
                                    break;
                            }
                        }
                    }
                    scanline[i] = currentIsland;
                }
                else
                {
                    scanline[i] = 0;
                }
            }
        }
        return islands.size();
    }
}`

A couple of test cases that are failing it (in different ways) are below:

`[["1","1","1","1","1","0","1","1","1","1"],["1","0","1","0","1","1","1","1","1","1"],["0","1","1","1","0","1","1","1","1","1"],["1","1","0","1","1","0","0","0","0","1"],["1","0","1","0","1","0","0","1","0","1"],["1","0","0","1","1","1","0","1","0","0"],["0","0","1","0","0","1","1","1","1","0"],["1","0","1","1","1","0","0","1","1","1"],["1","1","1","1","1","1","1","1","0","1"],["1","0","1","1","1","1","1","1","1","0"]]
[["1","1","1","1","1","0","1","1","1","1"],["0","1","1","0","1","1","1","0","1","1"],["1","0","1","0","1","1","0","1","0","1"],["1","0","1","1","0","1","1","1","1","1"],["1","1","0","0","1","1","1","1","1","1"],["1","1","0","1","1","1","1","1","1","1"],["1","1","1","1","1","1","1","1","0","1"],["0","1","1","0","1","1","1","1","1","0"],["1","1","0","1","1","0","1","1","1","1"],["0","1","1","1","1","1","0","1","1","1"]]`

These particular test cases (10x10) are not really important, they are just randomly generated. This was the smallest I was able to get (to make it able to debug the code), Only ~3 test cases out of 100 at that size were able to fail the code. Larger test cases (24x24, 100x100, etc) were failing with much higher probability and with bigger differences.

A simple random test case generator code is below. I suggest you add a few more randomly generated test cases at larger sizes (50x50, 100x100, 300x300) with varying land densities (0.4, 0.6, 0.75)

```public class Main {

	public static void main(String[] args) 
	{
		int n = 20;
		int m = 20;
		double density = 0.5;
		int numIterations = 10;

		
		char grid[][] = new char [n][m];
		
		
		
		for (int iteration = 0; iteration < numIterations; iteration++)
		{
			for(int i=0;i<m;i++)
				for (int j=0;j<n;j++)
					grid[i][j] = Math.random()<density ? '1' : '0';
			
			StringBuilder sb = new StringBuilder();
			
			sb.append("[");
			for(int i=0;i<m;i++)
			{
				sb.append("[");
				for (int j=0;j<n;j++)
				{
					sb.append("\"" + grid[i][j] + "\"");
					if (j<n-1)
						sb.append(",");
				}
				sb.append("]");
				if (i<m-1)
					sb.append(",");
			}
			sb.append("]");
			
			System.out.println(sb.toString());		
	  }
	}
}```

**Comment by SPGremlin** [comment]
I mean, of course, the test cases are "special" in the sense that they contain certain patterns that fail the (faulty) algorithm. If needed I can highlight these patterns. But the way to produce these test cases was random generation, and in general, more of the different patterns are covered at higher size maps.

**Comment by lc-kay** [comment]
Hi @SPGremlin 
Thank you for the information, I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @SPGremlin 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by SPGremlin** [comment]
Thanks. I'm new to LeetCode and still not quite sure what these LeetCoins
do, but you can deposit it to the "DmitriyAl" account.

Thank you!

-------
Best regards, Dmitriy

**Comment by lc-kay** [comment]
@SPGremlin You can use LeetCoins to redeem various items. For more information, please go to https://leetcode.com/store/
