### ISSUE TITLE
使用github账号第三方登录无法登陆，需手机验证码

### ISSUE THREAD

**Issue by Expellma** [LeetCode-Feedback/LeetCode-Feedback#20666]
### LeetCode 用户名
Expellma

- [ ] 问题描述 ： 登陆需手机号码验证，目前手机号码已废弃，无法收到验证码

### 期望行为

修改手机号码：18807728759 修改为13127559069

### 额外的上下文
需要解绑的手机号：18807728759
绑定手机号对应的力扣账号：569477945@qq.com
常用登录地址：（省市）上海
常用登录设备系统：mac
常用登录浏览器：chrome

望尽快解决！！ 找不到其他反馈方式很难受

**Comment by liyuzhu-lc** [comment]
您好，给您的邮箱发送了手机号重置邮件还请注意查收，现在可以点击邮件链接重新绑定需要的手机号啦！

**Comment by Expellma** [comment]
已收到，谢谢

**Comment by AJiangYe** [comment]
> 您好，给您的邮箱发送了手机号重置邮件还请注意查收，现在可以点击邮件链接重新绑定需要的手机号啦！

您好，问题描述 ： 登陆需手机号码验证，目前手机号码已废弃，无法收到验证码
期望行为
修改手机号码：18581962562 修改为15695317189

额外的上下文
需要解绑的手机号：18581962562
绑定手机号对应的力扣账号：1123800047@qq.com
常用登录地址：（省市）成都
常用登录设备系统：windows
常用登录浏览器：edg

望尽快解决！！ 找不到其他反馈方式很难受
