### ISSUE TITLE
Missing Test Case - 140. Word Break II

### ISSUE THREAD

**Issue by rishabhchahal** [LeetCode-Feedback/LeetCode-Feedback#2067]
#### Your LeetCode username

rishabhchahal

#### Category of the bug
- [ ] Question : getting Wrong answer even when in customer test run same is giving correct result.
- [ ] Solution : need to fix on submit the issue
- [ ] Language : English

#### Description of the bug

Mismatch result in submit and RunCode with custom test case

#### Code you used for Submit/Run operation

```
class Solution {
    private static Map<String, List<String>> map = new HashMap<>();
    
    public List<String> wordBreak(String s, List<String> wordDict) {
        return find(s, new HashSet<>(wordDict));
    }
    
    private static List<String> find(String s, Set<String> dic) {
		if (map.containsKey(s))
			return map.get(s);
		List<String> list = new ArrayList<String>();
		if (dic.contains(s))
			list.add(s);
		for (int i = 0; i < s.length(); i++) {
			String left = s.substring(0, i);
			String right = s.substring(i);
			if (dic.contains(left)) {
				for (String ss : find(right, dic))
					list.add(left + " " + ss);
			}
		}
		map.put(s, list);
		return list;
	}
}

```

#### Language used for code

Java

#### Expected behavior

Need to show consistent result in both submit and RunCode with custom test cases.
If code is wrong it needs to show same result in while submit and RunCode.

#### Screenshots

![Screenshot from 2021-01-19 12-38-21](https://user-images.githubusercontent.com/25175042/105000320-305bb000-5a54-11eb-8b9a-526b3515dc97.png)

**Comment by lc-kay** [comment]
Hi @rishabhchahal 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
