### ISSUE TITLE
Missing Test Case - 1114. Print in Order

### ISSUE THREAD

**Issue by tredsused40** [LeetCode-Feedback/LeetCode-Feedback#20677]
### LeetCode Username

tredsused70

### Problem number, title, and link

1114. Print in Order https://leetcode.com/problems/print-in-order/

### Category of the bug
- [.] Incorrect test Case is allowed

### Description of the bug

Invalid testcase does not considered as invalid, and can be succesfully used on "Run" operation.

### Language used for code

C++

### Code used for Submit/Run operation

```
class Foo {
public:
    int count = 0;
    mutex mtx;
    condition_variable cv;
    Foo() {
        count = 1;
        //cv.notify_all();
    }

    void first(function<void()> printFirst) {
        
        unique_lock<mutex> lck(mtx);
		// No point of this wait as on start count will be 1, we need to make the other threads wait.
        // while(count != 1){
        //     cv.wait(lck);
        // }
        // printFirst() outputs "first". Do not change or remove this line.

        printFirst();
        count = 2;
        cv.notify_all();
    }

    void second(function<void()> printSecond) {
        unique_lock<mutex> lck(mtx);
        while(count != 2){
            cv.wait(lck);
        }
        // printSecond() outputs "second". Do not change or remove this line.
        printSecond();
        count = 3;
        cv.notify_all();
    }

    void third(function<void()> printThird) {
        unique_lock<mutex> lck(mtx);
        while(count != 3){
            cv.wait(lck);
        }
        // printThird() outputs "third". Do not change or remove this line.
        printThird();
    }
};
```

### Expected behavior

If we try to use "Run" operation on test case nums=[1,2,3,3], it says that the expected size of nums is [1...3], while in statement it is clearly given that nums is a permutation of [1,2,3], so the size must be 3. If we try to use "Run" operation on nums = [3], it runs the code, and the "Run" operation results in "Time Limit Exceed", as can be seen on the screenshot.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/75163817/d53cf10e-76fe-4b2b-b4c8-4d30900f9620)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
