### ISSUE TITLE
Missing Test Case - 98. Validate Binary Search Tree

### ISSUE THREAD

**Issue by SongbaiLFLY** [LeetCode-Feedback/LeetCode-Feedback#20670]
第44组数据
root =
[0]
这是bug吗？左右都是空，为什么会出现一个3？
![1](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/44192416/81f0ccfa-d7b5-4387-b840-fb211865728b)

**Comment by amcones-lc** [comment]
感谢反馈，经核实该题目题解及测试用例暂无异常，力扣会不断努力给大家带来更好的学习社区！后续刷题学习中遇到问题，可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
