### ISSUE TITLE
350. Intersection of Two Arrays II // testcase error

### ISSUE THREAD

**Issue by MirzalievPulat** [LeetCode-Feedback/LeetCode-Feedback#20676]
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Code used for Submit/Run operation

```
when nums1:
[61,24,20,58,95,53,17,32,45,85,70,20,83,62,35,89,5,95,12,86,58,77,30,64,46,13,5,92,67,40,20,38,31,18,89,85,7,30,67,34,62,35,47,98,3,41,53,26,66,40,54,44,57,46,70,60,4,63,82,42,65,59,17,98,29,72,1,96,82,66,98,6,92,31,43,81,88,60,10,55,66,82,0,79,11,81]
and nums2:
[5,25,4,39,57,49,93,79,7,8,49,89,2,7,73,88,45,15,34,92,84,38,85,34,16,6,99,0,2,36,68,52,73,50,77,44,61,48]

and if we sort both of them:
Array1: [0, 1, 3, 4, 5, 5, 6, 7, 10, 11, 12, 13, 17, 17, 18, 20, 20, 20, 24, 26, 29, 30, 30, 31, 31, 32, 34, 35, 35, 38, 40, 40, 41, 42, 43, 44, 45, 46, 46, 47, 53, 53, 54, 55, 57, 58, 58, 59, 60, 60, 61, 62, 62, 63, 64, 65, 66, 66, 66, 67, 67, 70, 70, 72, 77, 79, 81, 81, 82, 82, 82, 83, 85, 85, 86, 88, 89, 89, 92, 92, 95, 95, 96, 98, 98, 98]
Array2: [0, 2, 2, 4, 5, 6, 7, 7, 8, 15, 16, 25, 34, 34, 36, 38, 39, 44, 45, 48, 49, 49, 50, 52, 57, 61, 68, 73, 73, 77, 79, 84, 85, 88, 89, 92, 93, 99]
see, both nums1 and nums2 contains 0 but there isn't 0 in the answer, why?

```

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback. We encourage you to share your questions in the discussion forum, where the community can provide insights and assistance.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
