### ISSUE TITLE
Wrong testcase for 115. Distinct Subsequences

### ISSUE THREAD

**Issue by Kyrieshka** [LeetCode-Feedback/LeetCode-Feedback#20683]
### Problem number, title, and link
[115. Distinct Subsequences](https://leetcode.com/problems/distinct-subsequences/)

### Category of the bug
 Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### Description of the bug
Input
s =
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
t =
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

Use Testcase
Output
984912416

Expected
-1

### Language used for code
JAVA

### Code used for Submit/Run operation

```
class Solution {
    public int numDistinct(String s, String t) {
        final int MOD = 1000000007;
        int[][] dp = new int[s.length() + 1][t.length() + 1];
        for (int i = 0; i <= s.length(); i++) {
            dp[i][0] = 1;
        }
        for (int i = 1; i <= s.length(); i++) {
            for (int j = 1; j <= t.length(); j++) {
                if (s.charAt(i - 1) == t.charAt(j - 1)) {
                    dp[i][j] = (dp[i - 1][j] + dp[i - 1][j - 1]) % MOD;
                } else {
                    dp[i][j] = dp[i - 1][j];
                }
            }
        }
        return dp[s.length()][t.length()];
    }
}
```

### Expected behavior
Output
984912416

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/5962379/1aa1a9e4-c756-4f96-b9fd-b98f55c5664b)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
