### ISSUE TITLE
Confusing problem description - 3047. Find the Largest Area of Square Inside Two Rectangles

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#20688]
### LeetCode Username
pgmreddy

### Problem number, title, and link

[3047. Find the Largest Area of Square Inside Two Rectangles](https://leetcode.com/problems/find-the-largest-area-of-square-inside-two-rectangles/)

https://leetcode.com/problems/find-the-largest-area-of-square-inside-two-rectangles/description/

### Category of the bug
- [x] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
i had some issues in contest, was unable to get it right, due to negatives, etc
the function params are given as `bottomLeft, topRight`
but it should be `leftBottom, rightTop`
only then my solution correctly passes

For example, 3rd example conflicts `bottomLeft = [[1,1],[3,3],[3,1]]`, then 3 & 1 is leftbottom, instead of bottomleft

Also please review if this question shud be discarded from contest due to poor wording, although many would have been correct, some were at severe disadvantage

I gave up in the middle of contest, as many Runs failed to pass, i used alternate account to do contest

https://leetcode.com/problems/find-the-largest-area-of-square-inside-two-rectangles/solutions/4778959/3047-find-the-largest-area-of-square-inside-two-rectangles/

### Language used for code
JavaScript

### Code used for Submit/Run operation

```
var largestSquareArea = function (leftBottom, rightTop) {
  const n = leftBottom.length;
  const leftBottomRightTop = leftBottom.map((_, k) => [...leftBottom[k], ...rightTop[k]]);
  let maxArea = 0;
  for (let i = 0; i < n; i++) {
    for (let j = i + 1; j < n; j++) {
      const [left1, bottom1, right1, top1] = leftBottomRightTop[i];
      const [left2, bottom2, right2, top2] = leftBottomRightTop[j];
      const maxLeft = Math.max(left1, left2);
      const maxBottom = Math.max(bottom1, bottom2);
      const minRight = Math.min(right1, right2);
      const minTop = Math.min(top1, top2);
      const side1 = minRight - maxLeft;
      const side2 = minTop - maxBottom;
      const minside = Math.min(side1, side2);
      if (minside > 0) {
        maxArea = Math.max(maxArea, minside * minside);
      }
    }
  }
  return maxArea;
};
```

### Expected behavior
description MUST be very clear
it is not top left, and, bottom right, but should be reverse

### Screenshots

After reversing meaning, it passess, see code above.

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/8236389/8d5d0a81-2d5e-4129-9a40-4a5c2f37ca53)

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
