### ISSUE TITLE
Missing Test Case - 208. Implement Trie (Prefix Tree)

### ISSUE THREAD

**Issue by tredsused40** [LeetCode-Feedback/LeetCode-Feedback#20682]
### LeetCode Username

tredsused70

### Problem number, title, and link

208. Implement Trie (Prefix Tree) https://leetcode.com/problems/implement-trie-prefix-tree/

### Category of the bug
- [.] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

Code that gets "Accepted" verdict, gets "Runtime Error" on some testcases when used "Run" operation.

### Language used for code

C++

### Code used for Submit/Run operation

```
class Trie {
public:
    int npr = 1, nxt[60000][26], isend[60000];
    Trie() {
        for(int i = 0; i < 60000; i++) {
            isend[i] = 0;
            fill(nxt[i], nxt[i] + 26, -1);
        }
        npr = 1;
        return ;
    }
    
    void insert(string s) {
        int cur = 0;
        int n = s.size();
        for(int i = 0; i < n; i++) {
            if(nxt[cur][s[i] - 'a'] == -1)
                nxt[cur][s[i] - 'a'] = npr++;
            cur = nxt[cur][s[i] - 'a'];
        }
        isend[cur] = 1;
        return ;
    }
    
    bool search(string s) {
        int cur = 0;
        int n = s.size();
        for(int i = 0; i < n; i++) {
            if(nxt[cur][s[i] - 'a'] == -1)
                return 0;
            cur = nxt[cur][s[i] - 'a'];
        }
        return isend[cur];
    }
    
    bool startsWith(string s) {
        int cur = 0;
        int n = s.size();
        for(int i = 0; i < n; i++) {
            if(nxt[cur][s[i] - 'a'] == -1)
                return 0;
            cur = nxt[cur][s[i] - 'a'];
        }
        return 1;
    }
};

/**
 * Your Trie object will be instantiated and called as such:
 * Trie* obj = new Trie();
 * obj->insert(word);
 * bool param_2 = obj->search(word);
 * bool param_3 = obj->startsWith(prefix);
 */
```

### Expected behavior

Size of arrays nxt and isend is 60000, which means that trie can't have more than 60000 nodes. However there are some cases where trie requires more than 60000 nodes to work. These tests cause "Runtime Error" when runned. One such test is attached below.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/75163817/3a58600b-65c2-47bd-9e80-11bbae20a9de)

### Additional context

[test.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/14393451/test.txt)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
