### ISSUE TITLE
Issue with constraints - 1522. Diameter of N-Ary Tree

### ISSUE THREAD

**Issue by Kafafafi** [LeetCode-Feedback/LeetCode-Feedback#2069]
#### Your LeetCode username
zsnovak90

#### Category of the bug
- [X ] Question

#### Description of the bug
The checker does not accept a null tree as a valid input, while the description states that it should be within constraints.

#### Screenshots
![leetcode](https://user-images.githubusercontent.com/77679911/105046642-a4ed1980-5a69-11eb-8f86-ed726d121b50.PNG)

**Comment by lc-kay** [comment]
Hi @Kafafafi 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Kafafafi 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
