### ISSUE TITLE
Code works on any other IDE platform but raises error only on leetcode

### ISSUE THREAD

**Issue by its-jaspreet** [LeetCode-Feedback/LeetCode-Feedback#20699]
### LeetCode Username
its-jaspreet

### Problem number, title, and link
58. Length of Last Word https://leetcode.com/problems/length-of-last-word/description/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

---

### Description of the bug
My code is logically right and works on any other IDE platform (I tried executing on vs code (local compiler) and on an online compiler "cpp.sh") and it works and gives the correct output, but raises a **runtime error** only on *leetcode*. Error generated on the test cases ```" a"``` and ```"a"``` only on leetcode.

### Language used for code
C++

### Code used for Submit/Run operation
```
// MY CODE ON LEETCODE
class Solution {
public:
    int lengthOfLastWord(string s) {
        string a = "";

        for (int i = s.length() - 1; i >= 0; i--) {
            if (isspace(s[i])) {
                continue;
            } else {
                while ((!isspace(s[i])) && (i >= 0)) {
                    a += s[i];
                    i--;
                    if ((i == 0) && (!isspace(s[i]))) {
                        a += s[i];
                        break;
                    }
                }
                break;
            }
        }
        return a.length();
    }
}; 
```

---

### Expected behavior
I uploaded the same code that i gave to leetcode with test cases to vscode (local compiler) and cpp.sh (online compiler). Here is the code:
```
// MY CODE ON VSCODE AND CPP.SH
#include <iostream>
#include <string>

using namespace std;

class Solution {
public:
    int lengthOfLastWord(string s) {
        string a = "";

        for (int i = s.length() - 1; i >= 0; i--) {
            if (isspace(s[i])) {
                continue;
            } else {
                while ((!isspace(s[i])) && (i >= 0)) {
                    a += s[i];
                    i--;
                    if ((i == 0) && (!isspace(s[i]))) {
                        a += s[i];
                        break;
                    }
                }
                break;
            }
        }
        return a.length();
    }
};

int main() {
    Solution sol;

    string case1 = "Hello World";
    int ans1 = sol.lengthOfLastWord(case1);
    cout << ans1 << endl;

    string case2 = "   fly me   to   the moon  ";
    int ans2 = sol.lengthOfLastWord(case2);
    cout << ans2 << endl;

    string case3 = "luffy is still joyboy";
    int ans3 = sol.lengthOfLastWord(case3);
    cout << ans3 << endl;

    string case4 = " ";
    int ans4 = sol.lengthOfLastWord(case4);
    cout << ans4 << endl;

    string case5 = " a";
    int ans5 = sol.lengthOfLastWord(case5);
    cout << ans5 << endl;
} 
```

The code runs perfectly fine and generates the correct output on both vscode and cpp.sh. However, it keeps generating a **runtime error** on *leetcode*. Please help me resolve this issue!

### Screenshots
Attached hereinbelow is the link of screenshots of the aforementioned code working and generating correct/desired output on cpp.sh (online compiler) and vs code (local compiler):
https://imgur.com/a/K44lR18

And attached hereinwith is link to another screenshot that shows that same code generating a runtime error on leetcode:
https://imgur.com/a/HyVj5ZX

---

### Additional context
Here is the **runtime error** being generated on test cases ```" a"```, and ```"A"```:
```Line 1053: Char 9: runtime error: addition of unsigned offset to 0x7f5f0b300740 overflowed to 0x7f5f0b30073f (basic_string.h)
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/basic_string.h:1062:9```

**Comment by LC-Pam** [comment]
Thank you for getting back to us! Regrettably, troubleshooting the variance between your local Integrated Development Environment (IDE) and the LeetCode environment poses a challenge for us.

In such cases, we recommend raising this issue as a discussion post in the problem's discussion section. This allows you to tap into the collective knowledge and experiences of our user community. Many users may have encountered similar challenges and could offer insights or solutions that can be valuable in resolving the discrepancy.

At LeetCode, we foster a collaborative learning environment, and we believe in the power of users to help each other to enhance their learning experience. Debugging and learning from the process are integral parts of the coding journey, and the community's diverse perspectives can be immensely beneficial.

We appreciate your understanding, and if you have any more questions or need further assistance, please feel free to let us know. Your time and support are highly valued.

Best regards,
The LeetCode Team
