### ISSUE TITLE
Problem Description of 1423

### ISSUE THREAD

**Issue by pawangeek** [LeetCode-Feedback/LeetCode-Feedback#207]
**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
Problem statement showing integer array for cardPoints but judge showing the range from 1 to 100000 accepted

**Expected behaviour**
There should be "positive" integer array given for cardPoints else Points on the cards can be negative

**Additional context**
https://leetcode.com/problems/maximum-points-you-can-obtain-from-cards/

**Code**
```
class Solution:
    def maxScore(self, cardPoints: List[int], k: int) -> int:
        
        n  =  len(cardPoints)
        
        presum  = [0]*(n+1)
        sufsum  = [0] * (n+1)
        
        for  i  in  range(1, n+1):
            presum[i] = presum[i-1] + cardPoints[i-1]
            sufsum[i] = sufsum[i-1] + cardPoints[n-i]
         
        sums = 0
        for x in range(k+1):
            sums = max(sums,presum[x]+sufsum[k-x])
            
        return sums
```
**Test Case**

```Input : cardPoints = [1,2,3,-4,5,6,1], k = 3```

**Comment by CooperCooperCooper** [comment]
Hi @pawangeek,
Thank you for reaching out to us. I've relayed your feedback to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @pawangeek,
To help us further assess this issue, can you please provide your code for this issue?

**Comment by pawangeek** [comment]
@CooperCooperCooper Issue updated with Code.

**Comment by CooperCooperCooper** [comment]
Hi @pawangeek,
Thank you. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @pawangeek,
Thank you for your time. We've decided to keep the problem statement because statement complements with constraint.
