### ISSUE TITLE
Missing Test Case - 1342. Number of Steps to Reduce a Number to Zero

### ISSUE THREAD

**Issue by Shivamrana182** [LeetCode-Feedback/LeetCode-Feedback#20711]
### Category of the bug
- [x] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

**Comment by Shivamrana182** [comment]
need to add more test cases

**Comment by Shivamrana182** [comment]
class Solution {
    public int numberOfSteps(int n) {
        return helper(n,0);
        
    }
    private static int helper(int n,int count){
        if(n==0){
            return count;
        }
        if(n%2==0){
            return helper(n/2,count+1);

        }
        else{
            return  helper (n-1,count+1);
        }
    }
}

**Comment by naXa777** [comment]
@Shivamrana182 
1. what test case is missing?
2. can you share a submission link to a solution that fails the test case, but is accepted by Leetcode?
3. what programming language is it?
