### ISSUE TITLE
Missing Test Case - 100174. Find Candidates for Data Scientist Position

### ISSUE THREAD

**Issue by Smipe-a** [LeetCode-Feedback/LeetCode-Feedback#20717]
### LeetCode Username
smipe_a

### Problem number, title, and link
100174 Find Candidates for Data Scientist Position
https://leetcode.com/problems/find-candidates-for-data-scientist-position/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [x] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
The result of executing the code is sorted itself without specifying ORDER BY

### Language used for code
PostgreSQL

### Code used for Submit/Run operation
```
SELECT candidate_id
FROM Candidates
WHERE skill = 'Python' OR skill = 'Tableau' OR skill = 'PostgreSQL'
GROUP BY candidate_id
HAVING COUNT(skill) = 3
```

### Expected behavior
The test should have been incorrect without specifying sorting, since simply SELECT does not guarantee it. But he passes anyway

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/48252171/05cb8692-06b2-49d3-a328-394919a5724b)

### Additional context
As I understand it, in your test cases, the result of my execution is sorted by itself. Because with the test data indicated in the screenshots below, there will obviously not be such sorting when executing the provided code

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

We added the test case you provided and your code is getting AC on it.

Can you please provide a test case that your code fails on?

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
