### ISSUE TITLE
Missing Test Case - 705. Design HashSet

### ISSUE THREAD

**Issue by niyozbek** [LeetCode-Feedback/LeetCode-Feedback#2071]
#### Your LeetCode username

niyozbekkk

#### Category of the bug
- [ ] Question - 705. Design HashSet
- [ ] Solution - submission id = 445136438
- [ ] Language - python3

#### Description of the bug

Definition states that All values will be in the range of [0, 1000000]
Therefore if you add in the test case obj.add(1000000) submission is supposed to fail. However, my submission (with id = 445136438) passed all the tests successfully!
#### Code you used for Submit/Run operation

```
class MyHashSet:

    def __init__(self):
        """
        Initialize your data structure here.
        """
        self.hashSet = [None] * 1000000

    def add(self, key: int) -> None:
        self.hashSet[key] = True

    def remove(self, key: int) -> None:
        self.hashSet[key] = None

    def contains(self, key: int) -> bool:
        """
        Returns true if this set contains the specified element
        """
        if self.hashSet[key]:
            return True
        return False
```

#### Language used for code

Python3

#### Expected behavior

I expected one of the tests to fail, since as an indexError. Because The code should include the range 1000001 not 1000000

#### Screenshots

![image](https://user-images.githubusercontent.com/20155784/105080487-b1499480-5ab2-11eb-8570-69f6cb9bfc79.png)

**Comment by lc-kay** [comment]
@niyozbek Can you please provide the test case that this solution failed on? Thanks.

**Comment by niyozbek** [comment]
> @niyozbek Can you please provide the test case that this solution failed on? Thanks.

hi, no you didnt get it. It was supposed to fail. But leetcode accepted the solutions. If you try to test it with obj.add(1000000) it fails with the solution(which has a bug)=445136438 i submitted. Thanks!

**Comment by lc-kay** [comment]
@niyozbek We understand you're trying to report a missing test case. However, please provide a test case which we can run in the console. So we can 1. prove that LeetCode's judge accepts a wrong submission. 2. add the missing test case to our judge. Please refer to the screenshot. Thank you!
<img width="467" alt="Screen Shot 2021-01-21 at 12 07 45 PM" src="https://user-images.githubusercontent.com/70870126/105406434-477bd880-5be1-11eb-930a-74738f860f1e.png">

**Comment by niyozbek** [comment]
> @niyozbek We understand you're trying to report a missing test case. However, please provide a test case which we can run in the console. So we can 1. prove that LeetCode's judge accepts a wrong submission. 2. add the missing test case to our judge. Please refer to the screenshot. Thank you!
> <img alt="Screen Shot 2021-01-21 at 12 07 45 PM" width="467" src="https://user-images.githubusercontent.com/70870126/105406434-477bd880-5be1-11eb-930a-74738f860f1e.png">

![image](https://user-images.githubusercontent.com/20155784/105422016-dd0c7c00-5c64-11eb-9dc4-ce824d3227e3.png)
![image](https://user-images.githubusercontent.com/20155784/105422059-e990d480-5c64-11eb-9eec-90c40bb2ae6e.png)
test case: ["MyHashSet","add","add","contains","contains","add","contains","remove","contains", "add"]
[[],[1],[2],[1],[3],[2],[2],[2],[2], [1000000]]. The same submission was accepted. But the problems says that **All values will be in the range of [0, 1000000].** Edge case which adds 1000000 is missing

**Comment by lc-kay** [comment]
Hi @niyozbek 
Thank you, I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @niyozbek 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
