### ISSUE TITLE
Wrong Constraint: 2694. Event Emitter

### ISSUE THREAD

**Issue by Daniel-WR-Hart** [LeetCode-Feedback/LeetCode-Feedback#20714]
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [x] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
The last constraint reads: "The `unsubscribe` action takes one argument, which is the 0-indexed order of the subscription made before."
False, you can add a parameter to `unsubscribe` then log it, and it's always `undefined`

### Language used for code
JavaScript

### Code used for Submit/Run operation
```
class EventEmitter {
    listeners = {}

    subscribe(eventName, callback) {
        this.listeners[eventName] = this.listeners[eventName] ?? [];
        this.listeners[eventName].push(callback);
		
        const log = (index, eventName) => console.log(`unsubbed at ${index}:  ${this.listeners[eventName][index]}`);

        return {
            // What the Contraints suggest
            unsubscribe: (index) => {
                log(index, eventName);
                this.listeners[eventName].splice(index, 1);
                // index is undefined, then coerced to 0
            }

            // What the solution verification system actually accepts
            // unsubscribe: () => {
            //     const index = this.listeners[eventName].indexOf(callback);
            //     log(index, eventName);
            //     this.listeners[eventName].splice(index, 1);
            // }
        };
    }
    
    emit(eventName, args = []) {
        this.listeners[eventName] = this.listeners[eventName] ?? [];
        return this.listeners[eventName].map((event) => event(...args));
    }
}
```
This test case makes the difference clear, since it needs you to remove callbacks from the end of the `this.listeners["firstEvent"]` array
```
["EventEmitter", "subscribe", "subscribe", "subscribe", "unsubscribe", "unsubscribe", "emit"]
[[], ["firstEvent", "x => x + 1"], ["firstEvent", "x => x + 2"], ["firstEvent", "x => x + 3"], [1], [2], ["firstEvent", [5]]]
```

### Expected behavior
If the last Constraint is true, then the uncommented version of `unsubscribe` would be valid, but it's not.
What happens is that the `undefined` `index` gets coerced to a `0` when used as the first argument of `splice`, so the first callback of the `this.listeners[eventName]` will always be removed.

### Additional context
The verification system is reasonable. It shouldn't be up to the web developer to keep track of the indices of their callbacks, because that would be an inconvenient API to use. It should be (and already is) up to `unsubscribe` to figure out the correct index at runtime.
**The last constraint should either be deleted, or changed to clarify that it doesn't need any parameters.**

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team

**Comment by Daniel-WR-Hart** [comment]
You guys didn't read what I said outside of the code. I know that the code judge is functioning correctly, but the problem is that the last constraint contradicts it
