### ISSUE TITLE
Missing Test Case - 100. Same Tree

### ISSUE THREAD

**Issue by AdityaKumar-Git** [LeetCode-Feedback/LeetCode-Feedback#20726]
### LeetCode Username
aditya_c0des

### Problem number, title, and link
[100. Same Tree](https://leetcode.com/problems/same-tree/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
missing test case

### TestCase
```p=[1,-11]```
```q=[1,Null,-11]```

### Language used for code
C++

### Code used for Submit/Run operation

```
/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
class Solution {
public:
    void preOrder(TreeNode* root, vector<int>& res){
        if(root==NULL){
            res.push_back(-11);
            return;
        }
        res.push_back(root->val);
        preOrder(root->left, res);
        preOrder(root->right, res);
    }

    bool isSameTree(TreeNode* p, TreeNode* q) {
        vector<int> i1,i2;
        preOrder(p,i1);
        preOrder(q,i2);
        if(i1.size()!=i2.size()) return false;
        for(int i=0; i<i1.size(); i++){
            if(i1[i]!=i2[i]) return false;
        }
        return true;
    }
};
```

### Expected behavior
submission failed/ wrong answer

### Screenshots
![Screenshot (64)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/154753771/a9876ab7-e013-4ec4-870e-896543742123)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
