### ISSUE TITLE
Missing Test Case - 98. Validate Binary Search Tree

### ISSUE THREAD

**Issue by swetagit186** [LeetCode-Feedback/LeetCode-Feedback#20736]
### LeetCode Username
[sks_142](https://leetcode.com/sks_142)

### Problem number, title, and link

1. Validate Binary Search Tree https://leetcode.com/problems/validate-binary-search-tree/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
Just want to contribute a testcase.

### Language used for code
C++ 

### Code used for Submit/Run operation

```
/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
class Solution {
public:
    bool solve(TreeNode* root,long long int lowerBound,long long int upperBound) {
        if(root==NULL)
        return true;
        int maxi=0;
        bool cond1=(root->val > lowerBound);
        bool cond2=(root->val < upperBound);
        bool leftAns=solve(root->left,lowerBound,root->val);
        bool rightAns=solve(root->right,root->val,upperBound);
        if(cond1 && cond2 && leftAns && rightAns)
            return true;
        else 
            return false;
    }
    bool isValidBST(TreeNode* root){
        long long int lowerBound=-2147483657;
        long long int upperBound=2147483657;
        bool ans= solve(root,lowerBound,upperBound);
        return ans;
    }
};
```

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

Details regarding the missing test case.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team
