### ISSUE TITLE
Missing Test Case - 3048. Earliest Second to Mark Indices I

### ISSUE THREAD

**Issue by Github-Anshu** [LeetCode-Feedback/LeetCode-Feedback#20739]
### LeetCode Username
Anshu_coding

### Problem number, title, and link
3048. Earliest Second to Mark Indices I

### Category of the bug
- [ ] Problem constraints
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

It passes all the test cases even if binary search is not used.

### Language used for code

Python

### Code used for Submit/Run operation

```
class Solution:
    def earliestSecondToMarkIndices(self, nums: List[int], indices: List[int]) -> int:
        N = len(nums)
        M1 = len(indices)

        def isValid(M):
          lastOccur = {}
          #index:second
          for i in reversed(range(M)):
            if indices[i] not in lastOccur:
              lastOccur[indices[i]] = i + 1
          
          if len(lastOccur) < N: return False

          #second, index
          last = sorted([[s, i] for i, s in lastOccur.items()])
          spent = 0
          for s, i in last:
            req = nums[i - 1] + 1
            if req + spent > s:return False
            spent+= req
          return True
        
        for M in range(1, M1 + 1):
          if isValid(M): return M
        return -1

```

### Expected behavior

Time limit should have exceeded, instead it passed all the test cases.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

Can you please provide a hack test too?

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team
