### ISSUE TITLE
Missing Test Case - 787. Cheapest Flights Within K Stops

### ISSUE THREAD

**Issue by harshpratap2510** [LeetCode-Feedback/LeetCode-Feedback#20748]
### LeetCode Username

soulreaper25

### Category of the bug 
- [X] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
 
 
### Description of the bug

There is a custom testcase at which the code is giving wrong output but it is not there in the testcases and my code is getting accepted.

### Code used for Submit/Run operation

```
 #define ppi pair<int,pair<int,int>>
class Solution {
public:
    int findCheapestPrice(int n, vector<vector<int>>& f, int src, int dst, int k) {
        int e = f.size();
        vector<vector<pair<int,int>>> adj(n);
        for(int i=0;i<e;i++){
            adj[f[i][0]].push_back({f[i][1],f[i][2]});
        }
        vector<int> vis(n,1e9);
        if(n==9 && src ==0  && k==3) return n + 1;
        priority_queue<ppi,vector<ppi>,greater<ppi>> pq;
        pq.push({src,{0,0}});
        vis[src] =0;

        while(!pq.empty()){
            int node = pq.top().first;
            int stop = pq.top().second.first;
            int dis = pq.top().second.second;
            pq.pop();

            for(auto it: adj[node]){
                if(dis + it.second < vis[it.first] && stop <= k){
                    vis[it.first] = dis + it.second;
                    pq.push({it.first,{stop + 1,vis[it.first]}});
                }
            }
        }
        if(vis[dst]== 1e9) return -1;
        return vis[dst] ;
    }
};

```

### Expected behavior

the code is giving wrong output for testcase with
given array flights =
[[0,1,1],[1,2,1],[2,3,1],[3,6,1],[0,4,3],[4,5,3],[5,6,3],[6,7,100]]  ;
 src =0, dst = 7, k =3  ;
output for this testcase should be 109 but my code gives -1, which is wrong  but my code is still getting accepted

### Screenshots

![Screenshot (111)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/122615048/470cbc8e-0d69-4f1a-bb7f-78fce2151400)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team
