### ISSUE TITLE
Missing Test Case - 1075. Project Employees I

### ISSUE THREAD

**Issue by CamiloMVJ** [LeetCode-Feedback/LeetCode-Feedback#20750]
### LeetCode Username

CamiloMVJ

### Problem number, title, and link

1075. Project Employees I https://leetcode.com/problems/project-employees-i/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [*] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

there is a testcase in which a employee have 'null' years of experience and in the description it is guaranteed that it will never be null 

### Language used for code

MS SQL Server

### Code used for Submit/Run operation

```
select a.project_id, round(cast(sum(
(b.experience_years)) as decimal) 
/ 
count(b.employee_id),2) as 'average_years' 
from Project a left join Employee b
on a.employee_id = b.employee_id group by a.project_id order by a.project_id
```

### Expected behavior

I think the code should work to solve the problem but in the 8th testcase it does not

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
