### ISSUE TITLE
缺少测试用例 - 1.两数之和

### ISSUE THREAD

**Issue by zhangVictory** [LeetCode-Feedback/LeetCode-Feedback#2075]
**Bug 类型**
- [ ] 题目
- [x] 题解
- [ ] 编程语言

**描述**
我在题解讨论区看到了一个提交通过了，但是这个代码是不对的，至少它没有通过下面这个用例：
[1,6142,8192,10239] target=18431
期望结果：[2,3]
实际返回：[0,1]
![20210120135829](https://user-images.githubusercontent.com/23631289/105135432-fa3d2f80-5b2a-11eb-889e-b1b026c3ea28.png)
但是却通过了！
![20210120142406](https://user-images.githubusercontent.com/23631289/105135551-307aaf00-5b2b-11eb-9457-6293c38ed773.png)

**你使用的语言**
Java

**你提交或者运行的代码**
```
// Two Sum
class Solution {
     public int[] twoSum(int[] nums, int target){
        int volume = 2<<10; //2048
        int bitNum = volume-1; //11111111111
        int[] res = new int[volume];
        for(int i=0;i<nums.length;i++){
            int c = (target-nums[i])&bitNum;
            if(res[c]!=0){
                return new int[]{res[c]-1,i};
            }
            res[nums[i]&bitNum] = i+1;
        }
        throw new IllegalArgumentException("No two sum solution");
    }
}
```

**期望行为**
我希望添加我提到的测试用例，或者类似的用例

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
@lc-kay 麻烦帮忙跟进下这个用户反馈哦。

**Comment by lc-kay** [comment]
Hi @feiceh 
I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@feiceh We have added this test case. Please reward the user.

**Comment by feiceh** [comment]
@zhangVictory 你好，当前该题已添加测试用例， 请留言告知一下力扣中文网站的 ID，我们给予积分奖励哦。

**Comment by zhangVictory** [comment]
我的ID：victory

**Comment by feiceh** [comment]
@zhangVictory 好的，ID：victory 给予积分奖励，请查收。

**Comment by zhangVictory** [comment]
在哪里领取呢，我看站内通知里没有，积分变更记录也没有呢

**Comment by feiceh** [comment]
@zhangVictory 已经添加在你说的「ID：victory」里了，个人主页是https://leetcode-cn.com/u/victory/ ，可以点击 [**积分**](https://leetcode-cn.com/points/) 查看详情。如有疑问，可 [提交工单](https://support.leetcode-cn.com/hc/request/new/) 反馈，谢谢。

**Comment by zhangVictory** [comment]
额，我ID提供错了，应该是：victory1，现在还可以补回来吗，不行的话就算了，今天才找到哪个是ID，跟昵称搞混了

**Comment by feiceh** [comment]
@zhangVictory ID：victory1 给予积分奖励，可以点击 [积分](https://leetcode-cn.com/points/) 查看。

**Comment by zhangVictory** [comment]
OK，已看到，谢谢
