### ISSUE TITLE
Memory limit exceeded bug

### ISSUE THREAD

**Issue by harshit105** [LeetCode-Feedback/LeetCode-Feedback#20769]
### Problem number, title, and link
5. Longest Palindromic Substring https://leetcode.com/problems/longest-palindromic-substring/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [x] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
A particular test case passes when I run it, but when I submit it, it gives a memory limit exceeded error.

### Language used for code
C++

### Code used for Submit/Run operation

```
class Solution {
public:
    string getString(char x){
        string s(1, x);
        return s;   
    }

    int dp[1001][1001];
    int check(int i, int j, string s){
        if(dp[i+1][j-1]==1){
            if(s[i]==s[j]){
                return 1;
            }
        }
        return 0;
    }
    string longestPalindrome(string s) {
        int n = s.length();
        if(n==1){
            return s;
        }
        else if(n==2){
            return s[0]==s[1]? s : getString(s[0]);
        }
        dp[0][0]=1;
        for(int i=1;i<n;i++){
            dp[i][i]=1;
        }
        for(int i=0;i<n-1;i++){
            if(s[i]==s[i+1]){
                dp[i][i+1]=1;
            }
            else{
                dp[i][i+1]=0;
            }
        }
        for(int j=2;j<n;j++){
            for(int i=0;i<j-1;i++){
                dp[i][j] = check(i,j,s);
            }
        }
        int max_length = INT_MIN;
        string ans;
        int l=0,m=0;
        for(int i=0;i<n;i++){
            for(int j=n-1;j>=i;j--){
                if(dp[i][j]==1){
                    if(j-i+1>max_length){
                        max_length = j-i+1;
                        l=i;
                        m=j;
                    }
                    continue;
                }
            }
        }
        ans = s.substr(l, m-l+1);
        return ans;
    }
};
```

### Expected behavior
If memory is exceeding, then it should show when we run the test case itself.

### Screenshots
<img width="618" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/46093097/3e71da79-ffb6-45e9-a5d1-3fb9e842d10f">
<img width="787" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/46093097/411ca471-1b08-419b-a790-2bfdd79ce0a8">

### Additional context
Test Case:
"jrjnbctoqgzimtoklkxcknwmhiztomaofwwzjnhrijwkgmwwuazcowskjhitejnvtblqyepxispasrgvgzqlvrmvhxusiqqzzibcyhpnruhrgbzsmlsuacwptmzxuewnjzmwxbdzqyvsjzxiecsnkdibudtvthzlizralpaowsbakzconeuwwpsqynaxqmgngzpovauxsqgypinywwtmekzhhlzaeatbzryreuttgwfqmmpeywtvpssznkwhzuqewuqtfuflttjcxrhwexvtxjihunpywerkktbvlsyomkxuwrqqmbmzjbfytdddnkasmdyukawrzrnhdmaefzltddipcrhuchvdcoegamlfifzistnplqabtazunlelslicrkuuhosoyduhootlwsbtxautewkvnvlbtixkmxhngidxecehslqjpcdrtlqswmyghmwlttjecvbueswsixoxmymcepbmuwtzanmvujmalyghzkvtoxynyusbpzpolaplsgrunpfgdbbtvtkahqmmlbxzcfznvhxsiytlsxmmtqiudyjlnbkzvtbqdsknsrknsykqzucevgmmcoanilsyyklpbxqosoquolvytefhvozwtwcrmbnyijbammlzrgalrymyfpysbqpjwzirsfknnyseiujadovngogvptphuyzkrwgjqwdhtvgxnmxuheofplizpxijfytfabx"

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback. We encourage you to share your questions in the discussion forum, where the community can provide insights and assistance.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
