### ISSUE TITLE
Missing Test Case - 987. Vertical Order Traversal of a Binary Tree

### ISSUE THREAD

**Issue by dannythanhphan** [LeetCode-Feedback/LeetCode-Feedback#2076]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

The problem states that "If any two nodes have the same y-coordinate in the report, the node with the smaller value should appear earlier."

My solution outputs to:                                             [[7,9],[5,6],[0,2,4],[1,3],[8]]
whereas the expected output from the test case is : [[9,7],[5,6],[0,2,4],[1,3],[8]]

Since the 7 and 9 share the same y-coordinate, 7 should appear before the 9. There seems to be an issue with the test case displaying the wrong expected output

#### Code you used for Submit/Run operation

```
var verticalTraversal = function(root) {
    if (root.val === null) return;
    let newPosition = [0, 0];
    let map = {};
    
    const recurse = (root, currentPosition, hMap) => {
        hMap[root.val] = currentPosition;
        
        if (root.left) {
            let newPosition = [currentPosition[0] - 1, currentPosition[1] - 1];

            recurse(root.left, newPosition, hMap);
        }

        if (root.right) {
            let newPosition = [currentPosition[0] + 1, currentPosition[1] - 1];

            recurse(root.right, newPosition, hMap);
        }
    }
    
    let callRecursion = recurse(root, newPosition, map);
    
    let sortedMap = Object.entries(map).sort((a, b) => a[1][0] - b[1][0]);
    
    let coordMap = new Map();
    
    let result = [];
    
    for (const coords of sortedMap) {
        let x = coords[1][0].toString();
        
        if (!coordMap.has(x)) {
            coordMap.set(x, [coords[0]])
        } else if (coordMap.has(x)) {
            let updated = coordMap.get(x);
            updated.push(coords[0]);
            coordMap.set(x, updated);
        }
    }
    
    coordMap.forEach((value) => result.push(value));
    
    return result
};
```

#### Language used for code
JavaScript

#### Expected behavior

The problem states that "If any two nodes have the same y-coordinate in the report, the node with the smaller value should appear earlier."

My solution outputs to:                                             [[7,9],[5,6],[0,2,4],[1,3],[8]]
whereas the expected output from the test case is : [[9,7],[5,6],[0,2,4],[1,3],[8]]

Since the 7 and 9 share the same y-coordinate, 7 should appear before the 9. There seems to be an issue with the test case displaying the wrong expected output

**Comment by lc-kay** [comment]
@dannythanhphan To understand this problem better, please check out this discuss post https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/discuss/231326/Wrong-test-Case. Thank you for your time.
