### ISSUE TITLE
Missing Test Case - 94. Binary Tree Inorder Traversal

### ISSUE THREAD

**Issue by SharathPayili** [LeetCode-Feedback/LeetCode-Feedback#20763]
### LeetCode Username

Sharath_Payili

### Problem number, title, and link

Binary Tree Inorder Traversal https://leetcode.com/explore/interview/card/top-interview-questions-medium/108/trees-and-graphs/786/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

For the testcase of "[ ]", the written code runs fine when "run code" option selected (output and expected both are: "[ ]"), but when submitted, an error is thrown at this particular test-case (output is: "[1,3,2]", expected is: "[ ]"). Most probably some problem with the problem's submit script. In my justification, my code satisfies all the conditions of the problem statement, and I see no reason to comply with the way the submit script is written.

### Language used for code

Python 3

### Code used for Submit/Run operation

```
# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
class Solution:
    inv = []
    def inorderTraversal(self, root: Optional[TreeNode]) -> List[int]:
        
        if root:
            self.inorderTraversal(root.left)
            self.inv.append(root.val)
            self.inorderTraversal(root.right)
        
        return self.inv
```

### Expected behavior

     **Testcase:** [ ]
  #### - When selected **Run Code**:
     Expected :  [ ]
     Output :  [ ]
  
  #### - When selected **Submit**:
     Expected : [ ]
     Output : [1,3,2]

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/68585549/338ae06e-d753-48b4-b750-c726e651cb71)

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
