### ISSUE TITLE
Missing Test Case - 1115. Print FooBar Alternately

### ISSUE THREAD

**Issue by weiihann** [LeetCode-Feedback/LeetCode-Feedback#20761]
### LeetCode Username

weiihann

### Problem number, title, and link

'1115. Print FooBar Alternately

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [x] Programming language support

### Description of the bug
The default Golang code template for this problem does not compile. 

### Language used for code

Go

### Code used for Submit/Run operation

```
type FooBar struct {
	n int
}

func NewFooBar(n int) *FooBar {
	return &FooBar{n: n}
}

func (fb *FooBar) Foo() {
	for i := 0; i < fb.n; i++ {
		// printFoo() outputs "foo". Do not change or remove this line.
        printFoo()
	}
}

func (fb *FooBar) Bar() {
	for i := 0; i < fb.n; i++ {
		// printBar() outputs "bar". Do not change or remove this line.
        printBar()
	}
}
```

### Screenshots

The following picture shows the default code template for the problem:
<img width="620" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/47109095/93924cb4-a395-43e9-ae8f-62a345719633">

The following picture shows the result of running the code template:
<img width="524" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/47109095/62de511f-33a7-4533-96dd-5e5d780ac572">

### Additional context

The solution is just to parse the functions as the arguments. Here's the correct version that compiles successfully:
```
type FooBar struct {
	n int
}

func NewFooBar(n int) *FooBar {
	return &FooBar{n: n}
}

func (fb *FooBar) Foo(printFoo func()) {
	for i := 0; i < fb.n; i++ {
		// printFoo() outputs "foo". Do not change or remove this line.
        printFoo()
	}
}

func (fb *FooBar) Bar(printBar func()) {
	for i := 0; i < fb.n; i++ {
		// printBar() outputs "bar". Do not change or remove this line.
        printBar()
	}
}
```

Output:
<img width="212" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/47109095/996038de-c09d-4b27-85d2-430b7f79f056">

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
