### ISSUE TITLE
Typo in editorial of the mentioned problem

### ISSUE THREAD

**Issue by kaustubhpawgi** [LeetCode-Feedback/LeetCode-Feedback#20778]
### LeetCode Username
kaustubhpawgi

### Problem number, title, and link

https://leetcode.com/problems/find-bottom-left-tree-value/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug

In the approach 1 of the editorial of the mentioned problem, there seems to be a slight mistake under the heading - "Standard Recursive Preorder Traversal" at point 3 and point 4.
3. Traverse the left subtree - call Preorder(root.right).
4. Traverse the right subtree - call Preorder(root.left).
I believe, in point 3, it should be -call Preorder(root.left), and in point 4 it should be -call Preorder(root.right).

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

### Screenshots

<img width="575" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/94781356/7145ba12-98b9-4937-a706-5f5817766ecd">

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
