### ISSUE TITLE
Wrong Title - 20. Valid Parentheses

### ISSUE THREAD

**Issue by asadullo-ganiev** [LeetCode-Feedback/LeetCode-Feedback#2077]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Title of question is misleading. Parantheses generally means (),  so brackets would be more proper.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
Hi @asadullo-ganiev 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@asadullo-ganiev Although the problem title may be misleading, changing it will cause the existing links to break. Therefore, we will not be changing it as the problem description is clear to understand. Thank you for your time.
