### ISSUE TITLE
Incorrect test Case

### ISSUE THREAD

**Issue by UttamKumarReddy** [LeetCode-Feedback/LeetCode-Feedback#20787]
uttamkumar_123

513. Find Bottom Left Tree Value https://leetcode.com/problems/find-bottom-left-tree-value/

- [ ] Incorrect test Case

for test case [ 1,2,3,null,4,5,null,null,7,6] the out put should be 6 but leetcode says 7.This is a simplified test case for testcase 77.

python3

### Code used for Submit/Run operation

```
# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
class Solution:
    def findBottomLeftValue(self, root: Optional[TreeNode]) -> int:
        ans = root.val
        ans_depth = 0
        ans_breadth = 0
        def dfs(node,depth,breadth):
            nonlocal ans,ans_depth,ans_breadth
            if depth > ans_depth:
                ans = node.val
                ans_depth = depth
                ans_breadth = breadth
            if depth == ans_depth:
                if breadth < ans_breadth:
                    ans = node.val
                    ans_depth = depth
                    ans_breadth = breadth
            if node.left:
                dfs(node.left,depth+1,breadth-1)
            if node.right:
                dfs(node.right,depth+1,breadth+1)
        dfs(root,0,0)
        return ans
        
```

### Expected behavior
for test case [ 1,2,3,null,4,5,null,null,7,6] the out put should be 6 but leetcode says 7.This is a simplified test case for testcase 77.

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/88535788/b7332b9f-89a3-43fc-b888-a004e1622ea9)

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team

**Comment by UttamKumarReddy** [comment]
[ 1,2,3,null,4,5,null,null,7,6]
Level 1 : node 1
Level 2 : node 2 node 3
Level 3 : (node 4 node 5) exactly at same location
Level 4 : node 6 the  node 7
So the ans is 6 not 7
