### ISSUE TITLE
Missing Test Case - LCR 186. 文物朝代判断

### ISSUE THREAD

**Issue by OLDyade** [LeetCode-Feedback/LeetCode-Feedback#20789]
### Category of the bug
- [x] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

**Comment by amcones-lc** [comment]
感谢反馈，能否向我们补充题目信息，以及完善代码格式，把信息提供完整才能有助于快速验证和精准的定位，谢谢。
