### ISSUE TITLE
Missing Test Case - 1003. Check If Word Is Valid After Substitutions

### ISSUE THREAD

**Issue by lovebaonvwu** [LeetCode-Feedback/LeetCode-Feedback#2078]
#### Your LeetCode username

lovebaonvwu

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

My solution was accepted, but I found that it would fail with some test case.

#### Code you used for Submit/Run operation

```
// Check If Word Is Valid After Substitutions
class Solution {
 public:
  bool isValid(string S) {
    stack<char> stk;

    for (auto c : S) {
      if (c == 'a') {
        stk.push(c);
      } else if (c == 'b' && !stk.empty() && stk.top() == 'a') {
        stk.push(c);
      } else if (c == 'c' && !stk.empty() && stk.top() == 'b') {
        stk.pop();
        stk.pop();
      }
    }

    return stk.empty();
  }
};
```

#### Language used for code

C++

#### Expected behavior

Test case ```"babcc"```
output true
expect false
But my solution accepted.

#### Screenshots

![image](https://user-images.githubusercontent.com/49331546/105150460-c1f41c00-5b3f-11eb-9d2c-69f47d23fae2.png)

**Comment by lc-kay** [comment]
Hi @lovebaonvwu 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @lovebaonvwu 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
