### ISSUE TITLE
Test Case Error - 269. Alien Dictionary

### ISSUE THREAD

**Issue by athorndia** [LeetCode-Feedback/LeetCode-Feedback#20791]
### LeetCode Username

username = [akthorndike](https://leetcode.com/akthorndike)

### Problem number, title, and link

269. Alien Dictionary
Link: https://leetcode.com/problems/alien-dictionary/submissions/1188548310/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ X] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Note: Testcase 123 / 127
words = ["ac", "ab", "b"]
Output: "cab"
Expected: "acb"
My output and expected output do not match...yet the test result is accepted. 

### Language used for code

Python3

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given

class Solution:
    def alienOrder(self, words: List[str]) -> str:
        if not words:
            return ""

        if len(set(words)) == 1: 
            return "".join(set(c for c in words[0]))

        alien_map = {c:set() for w in words for c in w}

        for i in range(len(words) - 1):
            w1, w2 = words[i], words[i+1]
            minl = min(len(w1), len(w2))
            if len(w1) > len(w2) and w1[:minl] == w2[:minl]:
                return ""

            for j in range(minl):
                if w1[j] != w2[j]:
                    alien_map[w1[j]].add(w2[j])
                    break

        visit_map = {}
        res = []

        def dfs(c):
            if c in visit_map:
                return visit_map[c]
            visit_map[c] = True
            
            for n in alien_map[c]:
                # if visit_map before:
                if dfs(n):
                    return True
                
            visit_map[c] = False
            res.append(c)

        for c in alien_map: 
            if dfs(c):
                return ""

        res.reverse()
        return "".join(res)

// above and below the code.
```

### Expected behavior

Note: Testcase 123 / 127
words = ["ac", "ab", "b"]
Output: "cab"
Expected: "acb"
My output and expected output do not match...yet the test result is accepted. 

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/104226292/bd0c6b40-b299-4823-8a99-d05e9d3027ed)

### Additional context

N/A

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
