### ISSUE TITLE
Missing Test Case - 673. Number of Longest Increasing Subsequence

### ISSUE THREAD

**Issue by Egrk** [LeetCode-Feedback/LeetCode-Feedback#20790]
### LeetCode Username
Commie

### Problem number, title, and link
673. Number of Longest Increasing Subsequence https://leetcode.com/problems/number-of-longest-increasing-subsequence/ 

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [X] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
Erroneous output of the example test case 2. Locally outputs the correct answer, but in leetcode execution it outputs an incorrect result

### Language used for code
Go

### Code used for Submit/Run operation

```
type Tree struct {
	value     int
	level     int
	prevNode  *Tree
	childrens []*Tree
}

var ans, max int

func findNumberOfLIS(nums []int) int {
	root := Tree{
		level: 0,
		value: 0,
	}
	for _, val := range nums {
		addVal(val, &root)
	}
	dfs(&root)
	return ans
}

func dfs(root *Tree) {
	for _, leaf := range root.childrens {
		dfs(leaf)
	}
	if max == root.level {
		ans++
	} else if max < root.level {
		max = root.level
		ans = 1
	}
}

func addVal(value int, root *Tree) bool {
	if root.value >= value {
		return true
	}
	if len(root.childrens) > 0 {
		for _, child := range root.childrens {
			if addVal(value, child) {
				root.childrens = append(root.childrens, &Tree{level: root.level + 1, value: value, prevNode: root})
				sort.Slice(root.childrens, func(i, j int) bool { return root.childrens[i].value < root.childrens[j].value })
				break
			}
		}
	} else {
		root.childrens = append(root.childrens, &Tree{level: root.level + 1, value: value, prevNode: root})
		sort.Slice(root.childrens, func(i, j int) bool { return root.childrens[i].value < root.childrens[j].value })
	}
	return false
}

```

### Expected behavior
on example case 2 it expected 5. Locally it output 5, but leetcode execution output 2

### Screenshots
LeetCode run:
![изображение](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/80197828/08af9c10-cbe0-4299-afde-811460ad5d4f)
Local run with the same slice:
![изображение](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/80197828/75897eaf-46b1-46bb-a219-cce0baeabfab)

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
