### ISSUE TITLE
Issue with Submission | Problem 31 | Next Permutation

### ISSUE THREAD

**Issue by praphull02549** [LeetCode-Feedback/LeetCode-Feedback#208]
**What kind of the bug**
- [ ] problem
- [x] solution
- [ ] language

**Describe the bug**
I ran into this problem while resubmitting one of my 12 day old submitted A/C code. Actually one of my friend ran into this problem while doing it for the first time then she asked me to do so. I got this error on the same code too. I tried it with some other similar accepted codes, Same resize error. I would have thought it to be a version issue but how can same code be accepted 12 days back and giving the error now. Detailed error info is in the screenshots.

**what language is your code written in**
C++

**The code you submit/run**
```
//Next Permutation
class Solution {
public:
    void nextPermutation(vector<int>& a) {
        int n=a.size();
        int i, j;
        for(i=n-2; i>=0; i--){
            if(a[i]<a[i+1]) break;
        }
        if(i<0) reverse(a.begin(), a.end());
        else{
            for(j=n-1; j>i; j--) if(a[j]>a[i]) break;
            swap(a[j], a[i]);
            reverse(a.begin()+i+1, a.end());
        }
    }
};
```

**Expected behavior**
Expected it to compile and get accepted as 12 days back. Expected other similar old accepted solutions to compile and get accepted too.

**Screenshots**
![image (1)](https://user-images.githubusercontent.com/24732761/80562983-23e78100-8a07-11ea-98b0-6e2ccf744999.png)

**Additional Info**
My function is of 16 lines of code only.

**Comment by CooperCooperCooper** [comment]
Hi @praphull02549,
Thank you for reaching out to us! I've relayed your issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @praphull02549,
Thank you for your time. Our team found this issue to be a system issue and not a content issue. It's currently under investigation so we can fix it soon. If you would like more updates on this issue, please redirect this issue to our main support channel "support@leetcode.com". We appreciate your time and support.
