### ISSUE TITLE
Duplicate word in Editorial for 14. Longest Common Prefix

### ISSUE THREAD

**Issue by Y-Rov** [LeetCode-Feedback/LeetCode-Feedback#20804]
### LeetCode Username

[anacondrai](https://leetcode.com/anacondrai/)

### Problem number, title, and link

[14. Longest Common Prefix](https://leetcode.com/problems/longest-common-prefix/)

### Category of the bug
- [ ] Editorial

### Description of the bug

Hello, LeetCode team 😄

If we go through the section "Approach 4: Binary search" in [problem's Editorial](https://leetcode.com/problems/longest-common-prefix/editorial/) and stop at the analysis of possible cases (the 2-nd item of the unordered list):

> `S[1...mid]` is common string. This means that for for each `i < j S[1..i]` is a common string and we discard the first half of the search space, because we try to find longer common prefix.

There is a duplication of the word "for".

### Expected behavior

The corrected sentence:
> `S[1...mid]` is common string. This means that for each `i < j S[1..i]` is a common string and we discard the first half of the search space, because we try to find longer common prefix.

### Screenshots

![Duplicate_For](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73534920/cf739e94-f9e5-4240-8392-9514876e8678)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
