### ISSUE TITLE
Missing Test Case - 513. Find Bottom Left Tree Value

### ISSUE THREAD

**Issue by shikharg1110** [LeetCode-Feedback/LeetCode-Feedback#20817]
### LeetCode Username
Shikharg1110

### Problem number, title, and link

513. Find Bottom Left Tree Value https://leetcode.com/problems/find-bottom-left-tree-value/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ . ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ . ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

When the tree is right skewed tree and its root node has only 1 left child. Then the output is that left child. But the output its accepting is the rightest child which is incorrect.

### Language used for code

C++

### Code used for Submit/Run operation

```

/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
class Solution {
public:
    int findBottomLeftValue(TreeNode* root) {
        queue<TreeNode *> q;
        q.push(root);
        int ans = 0;
        while(!q.empty()) {
            int size = q.size();
            for(int i = 0; i < size; i++) {
                TreeNode *front = q.front();
                q.pop();
                if(i == 0)
                    ans = front->val;
                if(front->left != NULL)
                    q.push(front->left);
                if(front->right != NULL)
                    q.push(front->right);
            }
        }
        return ans;
    }
};
// Paste your code here. Don't remove ``` given
// above and below the code.
```

### Expected behavior

If suppose the tree is right skewed and its root node has only one left child. Then the output should be the left child only. 
But it shows the output as rightest child which is incorrect.
Incorrect/Inefficient Code getting accepted because of missing test cases
root = [1,2,3,null,null,null,6,null,7]
Output = 7
The real answer should be = 2

### Screenshots

![1](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/114243045/7330b6ad-7dad-4aec-95a4-8ee1d749938e)
![2](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/114243045/a86b97ee-ac41-4e82-aa60-bfb28b0efc07)
![3](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/114243045/85b3eb1c-6c86-4f91-8d60-f6273d26b492)

### Additional context

As stated above if suppose the tree is right skewed and its root node has only one left child. Then the output should be the left child only. But it shows the output as rightest child which is incorrect.

**Comment by shikharg1110** [comment]
If the above missing test case or incorrect test case is correct then there is problem with the understanding of the wording or problem statement. Please correct it and explain the problem statement with "Return the first node in the last level"

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
