### ISSUE TITLE
Link Questions - 1609. Even Odd Tree - and - 103. Binary Tree Zigzag Level Order Traversal

### ISSUE THREAD

**Issue by naXa777** [LeetCode-Feedback/LeetCode-Feedback#20825]
### LeetCode Username

naXa777

### Problem number, title, and link

- [103. Binary Tree Zigzag Level Order Traversal](https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/)
- [1609. Even Odd Tree](https://leetcode.com/problems/even-odd-tree/)

### Category of the bug

- [x] Missing "Similar Questions"

### Description of the bug

These questions are so similar, I mean the description, and approach to solving them. Yet they are not linked.

### Expected behavior

In "Similar Questions" section of the [1609. Even Odd Tree](https://leetcode.com/problems/even-odd-tree/) question there's a link to [103. Binary Tree Zigzag Level Order Traversal](https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/).
And in "Similar Questions" section of the [103. Binary Tree Zigzag Level Order Traversal](https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/) question there's a backlink to [1609. Even Odd Tree](https://leetcode.com/problems/even-odd-tree/).

### Language

Kotlin

### Code

Solution for 1609 using ZigZag tree traversal:

```kt
class Solution {
    fun isEvenOddTree(root: TreeNode): Boolean {
        val discovered: Queue<TreeNode> = LinkedList<TreeNode>()
        discovered.add(root)
        var depth = 0

        // BFS ZigZag traversal
        while (discovered.isNotEmpty()) {
            val nextLevel = ArrayDeque<TreeNode>()
            var prevValue = Int.MIN_VALUE

            repeat(discovered.size) {
                val node = discovered.remove()

                if (depth % 2 == 0) {
                    if (node.`val` % 2 == 0) return false
                    node.left?.let { nextLevel.addFirst(it) }
                    node.right?.let { nextLevel.addFirst(it) }
                } else {
                    if (node.`val` % 2 == 1) return false
                    node.right?.let { nextLevel.addFirst(it) }
                    node.left?.let { nextLevel.addFirst(it) }
                }
                // in ZigZag traversal node values are always increasing
                if (node.`val` <= prevValue) return false
                prevValue = node.`val`
            }

            discovered.addAll(nextLevel)
            ++depth
        }

        return true
    }
}
```

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
