### ISSUE TITLE
Improper Constraints - 365. Water and Jug Problem

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#20829]
### LeetCode Username
stormsunshine

### Problem number, title, and link
[365. Water and Jug Problem](https://leetcode.com/problems/water-and-jug-problem)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [x] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
This problem should be designed to be solved by BFS and DFS. Although this problem can also be solved by number theory (greatest common divisor), it should not be designed to only be solved by number theory.

Currently, the constraints are too large and there are already large test cases to make BFS and DFS approaches get TLE when submitted. So the current state is that this problem can only be solved by number theory.

BFS and DFS approaches should be accepted, and the large test cases make many existing solutions in the discuss area invalid. Therefore, the constraints should be modified so that the maximum value should be reduced from 10<sup>6</sup> to 10<sup>5</sup>, which can make BFS and DFS approaches be accepted. After updating the constraints, the large test cases that do not meet the new constraints should be removed.

### Expected behavior
1. Change the constraints so that the maximum value should be reduced from 10<sup>6</sup> to 10<sup>5</sup>.
2. After updating the constraints, the large test cases that do not meet the new constraints should be removed.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
