### ISSUE TITLE
Missing Test Case - 162. Find Peak Element

### ISSUE THREAD

**Issue by asmir-a** [LeetCode-Feedback/LeetCode-Feedback#20822]
### LeetCode Username

asmir08

### Problem number, title, and link

74, Find Peak Element, https://leetcode.com/problems/find-peak-element

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [X] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

This test case [4, 3, 2, 1, 4] seems to satisfy the constraints. However, the code I submitted was accepted without being able to pass the aforementioned test case.

### Language used for code

Python3

### Code used for Submit/Run operation

```python
class Solution:
    def findPeakElement(self, nums: List[int]) -> int:
        left = 0
        right = len(nums) - 1
        while left <= right:
            middle = left + (right - left) // 2
            if (left == right) and (middle + 1 >= len(nums) or middle - 1 < 0):
                return middle
            if nums[middle] > nums[middle - 1] and nums[middle] > nums[middle + 1]:
                return middle
            elif nums[middle] > nums[middle + 1] and nums[middle - 1] > nums[middle]:
                right = middle - 1
            else:
                left = middle + 1
```

### Expected behavior

The code I submitted should not have passed.

### Screenshots

<img width="1111" alt="Screenshot 2024-02-29 at 8 06 08 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/50238545/872db94d-e333-4570-bd27-9d3eea23150f">

<img width="992" alt="Screenshot 2024-02-29 at 8 06 53 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/50238545/c7e20b32-c7e9-4c23-90e8-6d178fe33562">

<img width="799" alt="Screenshot 2024-03-01 at 8 35 17 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/50238545/7af8cec3-4799-401b-b1cf-1745439b349c">

### Additional context

The first if block in the body of the function, i.e. "if (left == right) and (middle + 1 >= len(nums) or middle - 1 < 0)" should be changed to "if (left == right or left == right - 1) and (middle + 1 >= len(nums) or middle - 1 < 0)". 
The reasoning might explained through the following test case: [2, 1]. The first middle element is at index 0, which is 2. Then, at the first iteration, it should treat it as a left-boundary element, but because left = right + 1 and the condition only checks for left == right, the element does not get treated as a boundary element. After that, the right pointer becomes middle - 1, which is -1 and which is smaller than left = 0, and the while loop terminates and nothing should be returned. However, because python treats -1 as the last element in the array, this particular test case passes.
I added another test case, [4, 3, 2, 1, 5] in the screenshots, in which the boundary elements differ as well and which my code does not pass as well. After the middle element selected, 2, there is no reason to narrow down to the right side of it because the element next to the middle is less than it and there might be no peak element to the right of the middle element.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
