### ISSUE TITLE
Unknown network error - question 3063: Linked List Frequency

### ISSUE THREAD

**Issue by calvinchankf** [LeetCode-Feedback/LeetCode-Feedback#20838]
### LeetCode Username
calvinchankf

### Problem number, title, and link
3063: https://leetcode.com/problems/linked-list-frequency/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support
- [x] Application error

### Description of the bug
Error message:
```
Unknown network error. Please try reloading page.
```
When dive deep, the error message from the API is
```
full_runtime_error: "validate() takes exactly 3 arguments (2 given)"
```

### Language used for code
- I tried python, js, c++, but I believe the bug happens for all the languages

### Code used for Submit/Run operation
No matter what the code is, it gives me the same error mentioned above. Please see my screenshot

### Expected behavior
- run my code and give me the result

### Screensho
<img width="1721" alt="Screenshot 2024-02-29 at 17 03 16" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/5404455/44be1e81-e17a-42e2-9871-b7ae83825d7f">
ts

### Additional context
- none

**Comment by LC-Pam** [comment]
Hello,

Thank you for providing your feedback.

Please note that our GitHub repository primarily addresses content and solution-related issues. To ensure a prompt response and effective resolution for feature, function, course access, or product-related feedback, we kindly encourage you to submit such inquiries through our Zendesk Support Channel:

[LeetCode Support](https://leetcode.com/support)

Our dedicated support agents typically respond within 24 hours and promptly report submitted issues to the appropriate departments for investigation.

We greatly appreciate your ongoing support and value your contributions to enhancing the LeetCode experience.

Best regards,
LeetCode Support Team
