### ISSUE TITLE
Missing Test Case - 2390. Removing Stars From a String

### ISSUE THREAD

**Issue by Andrew00000** [LeetCode-Feedback/LeetCode-Feedback#20834]
### LeetCode Username

[Andrew00000](https://leetcode.com/Andrew00000)

### Problem number, title, and link

2390. Removing Stars From a String https://leetcode.com/problems/removing-stars-from-a-string/

### Category of the bug
- [ *] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ *] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug
I solved the issue, then looking at the constraints I was thinking maybe I forgot an edge case.
Constraints:
1 <= s.length <= 105
s consists of lowercase English letters and stars *.
The operation above can be performed on s.

This technically allows string consisting only from stars. For example "**". I tried to a testcase like that and when I was trying to run it, I received the following error: "Unknown network error. Please try reloading page."
I tried to reload nothing changed. 
If I remove the testcase though, suddenly everything is back to normal and I can run tests.
However if I add the only stars testcase again. The error appears again.  If I add other testcases like "a" it has not issue.
I also tried other scenarios where I have more stars than letters and I always get the same error.

Maybe I misunderstood this constraint: "The operation above can be performed on s." and it means that I need at least as many letters as I have stars but the testcases behavior is different than what usually happens with a bad testcase and I don't think it a network issue.

### Language used for code
c#

### Code used for Submit/Run operation

```
public class Solution {
    public string RemoveStars(string s) 
    {
        var answerChars = new Stack<char>();

        for (var i = 0; i < s.Length; i++)
        {
            if(s[i] != '*')
            {
                answerChars.Push(s[i]);
            }
            else
            {
                answerChars.Pop();
            }
        }

        StringBuilder answer = new StringBuilder("");

        while ( answerChars.Count != 0)
        {
            answer.Append(answerChars.Pop());
        }

        return new string(answer.ToString().Reverse().ToArray());
    }
}
```

### Expected behavior

I would expect either a passing test or some exception/error message that is connected to the code, definitely not a network error.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/62332857/25f0625c-4407-4538-876c-1ab898d30d42)

### Additional context

The same error happens when I try Java or Python

```
class Solution {
    public String removeStars(String s) 
    {
         return "s";   
    }
}
```

```
class Solution(object):
    def removeStars(self, s):
        return "s"
```

**Comment by LC-Pam** [comment]
Hello,

Thank you for providing your feedback.

Please note that our GitHub repository primarily addresses content and solution-related issues. To ensure a prompt response and effective resolution for receive network error, feature, function, course access, or product-related feedback, we kindly encourage you to submit such inquiries through our Zendesk Support Channel:

[LeetCode Support](https://leetcode.com/support)

Our dedicated support agents typically respond within 24 hours and promptly report submitted issues to the appropriate departments for investigation.

We greatly appreciate your ongoing support and value your contributions to enhancing the LeetCode experience.

Best regards,
LeetCode Support Team
