### ISSUE TITLE
Missing Test Case - 315. Count of Smaller Numbers After Self

### ISSUE THREAD

**Issue by zlobspb** [LeetCode-Feedback/LeetCode-Feedback#2083]
#### Your LeetCode username
zlobspb

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
with the current tests following solution works as almost it's the fastest one but in realty it's O(n^2)
```
class Solution:
    def countSmaller(self, nums: list[int]) -> list[int]:
        res = [0] * len(nums)
        s_nums = sorted(nums)

        for i, n in enumerate(nums):
            j = bisect.bisect_left(s_nums, n)
            res[i] = j
            s_nums.pop(j)

        return res
```

I suggest to add a simple test case that will show that this solution isn't the best one.
```
nums = list(range(10 ** 5))
```

#### Code you used for Submit/Run operation
```
class Solution:
    def countSmaller(self, nums: list[int]) -> list[int]:
        res = [0] * len(nums)
        s_nums = sorted(nums)

        for i, n in enumerate(nums):
            j = bisect.bisect_left(s_nums, n)
            res[i] = j
            s_nums.pop(j)

        return res
```

#### Language used for code

Python3

#### Expected behavior

Time Limit Exceeded

**Comment by lc-kay** [comment]
@zlobspb To qualify for rewards, can you please provide a test case that will fail this solution. Thank you.

**Comment by zlobspb** [comment]
Sorry, should've attached tests in the first message.
Please see two tests in attach which were generated with accordance to the task constraints like this:
1. `1.txt` # this gives "Runtime: 1108 ms" on provided earlier solution and it definitely wouldn't be fastest (without this test runtime is 88 ms)
```
'[' + ','.join(str(x) for x in range(-10000, 10000) for _ in range(5)) + ']'
```
2. `2.txt` # in case someone tries to reverse the data
```
'[' + ','.join(str(x) for x in reversed(range(-10000, 10000)) for _ in range(5)) + ']'
```
[1.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/5845207/1.txt)
[2.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/5845208/2.txt)

**Comment by lc-kay** [comment]
Hi @zlobspb 
Thank you for the information. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@zlobspb We've updated the test set of this problem, however, we didn't use the test cases you provided. Python has many optimizations and the code doesn't reach O(n^2) in most cases. Thank you for your time.
