### ISSUE TITLE
题目错误

### ISSUE THREAD

**Issue by RenxiuF** [LeetCode-Feedback/LeetCode-Feedback#20849]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

### LeetCode 用户名

frx

### 问题号码、标题和链接

595. 大的国家 https://leetcode.cn/problems/big-countries/

### Bug 类型
- [x] 问题描述
- [ ] 示例
- [ ] 问题限制
- [ ] 问题提示
- [ ] 不正确或缺少“相关标签”
- [ ] 不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*
- [ ] 缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*
- [ ] 力扣官方题解
- [ ] 编程语言支持

### 描述

题目中的表格名称 World 有误，与通过的测试用例不符，应为 world

### 你使用的语言

SQL

### 你提交或者运行的代码

```
SELECT name,population,area
FROM world
WHERE area >= 3000000 OR population >= 25000000;
```

### 期望行为

修改可通过代码中的表格名称为 World

### 屏幕截图

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/63635782/5d4dc993-8440-4b94-bf2e-c2072ad147c5)

**Comment by amcones-lc** [comment]
感谢反馈，经核实该题目题解及测试用例暂无异常，力扣会不断努力给大家带来更好的学习社区！后续刷题学习中遇到问题，可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
