### ISSUE TITLE
Missing Test Case - 14. Longest Common Prefix

### ISSUE THREAD

**Issue by adheeshc** [LeetCode-Feedback/LeetCode-Feedback#20844]
### LeetCode Username

adheeshc

### Problem number, title, and link

14. Longest Common Prefix (https://leetcode.com/problems/longest-common-prefix/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support
Missing test Case

### Description of the bug

A solution was accepted by the system with a 3ms runtime and 11.11MB memory. But the solution is wrong. 
it breaks for a custom test case.

### Language used for code

C++

### Code used for Submit/Run operation

Here is the solution that is accepted -
```
class Solution {
public:
    string longestCommonPrefix(vector<string>& strs) {
        if(strs.empty())
            return "";

        std::string answer = "";

        for(int i = 0; i<strs[0].size(); i++){
            if(strs[0][i] != strs[strs.size()-1][i]){
                return answer;
            }
            answer += strs[0][i];
        }
        return answer;
    }
};
```

### Expected behavior

this is a custom test case it breaks for - ["flow","fliwer","floghted"]
Note - although these arent real words (modified test case 1) , the idea behind it is the same as for an real list of possible words.

Output is "flo"
Expected is "fl"

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
