### ISSUE TITLE
Missing Test Case - 1168. Duplicate Zeros

### ISSUE THREAD

**Issue by sanchidev** [LeetCode-Feedback/LeetCode-Feedback#2084]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@sanchidev Please provide the accepted code and the missing test case.

**Comment by lc-kay** [comment]
Hi @sanchidev 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
