### ISSUE TITLE
Missing Test Case - 392. Is Subsequence

### ISSUE THREAD

**Issue by alaneuler** [LeetCode-Feedback/LeetCode-Feedback#20847]
### LeetCode Username

Alaneuler

### Problem number, title, and link

392. Is Subsequence https://leetcode.com/problems/is-subsequence/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Missing test case:
s = "aa", t = "a"
The following code passed, but it shouldn't have.

### Language used for code

Python3

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
class Solution:
    def isSubsequence(self, s: str, t: str) -> bool:
        if len(s) == 0:
            return True
        if len(t) == 0:
            return False
        x = []
        for i in range(len(s)):
            cur = []
            for j in range(len(t)):
                tmp = s[i] == t[j]
                if j > 0:
                    if i > 0:
                        tmp = cur[j - 1] or (x[i - 1][j - 1] and s[i] == t[j])
                    else:
                        tmp = tmp or cur[j - 1]
                cur.append(tmp)
            x.append(cur)
        # print(x)
        return x[-1][-1]
```

### Expected behavior

The code should fail.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
