### ISSUE TITLE
Inconsistent Submit and TestCase Results - 377. Combination Sum IV

### ISSUE THREAD

**Issue by dboures** [LeetCode-Feedback/LeetCode-Feedback#2085]
#### Your LeetCode username
ToastyPizza

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
A solution fails a test case when submitted, but runs the same test case successfully under Run Code Result.

#### Code you used for Submit/Run operation

```
class Solution:
    def combinationSum4(self, nums: List[int], target: int, memo = {}) -> int:        
        count = 0
        if target == 0:
            return 1
        for num in nums:
            if target >= num:
                try:
                    count += memo[target - num]
                except KeyError:
                    ans = self.combinationSum4(nums, target - num, memo=memo)
                    memo[target-num] = ans
                    count += ans
                    
        return count
```

#### Language used for code
Python 3

#### Expected behavior
The solution should be consistently accepted/rejected when submitted and run as a test case.

#### Screenshots

![image](https://user-images.githubusercontent.com/24765307/105223263-2b186700-5b21-11eb-8371-f1553627ff9a.png)

**Comment by lc-kay** [comment]
@dboures 

Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
