### ISSUE TITLE
116填充每个节点的下一个右侧节点指针：leetcode 定义的Node类型无法正常识别

### ISSUE THREAD

**Issue by Xiaoxin-19** [LeetCode-Feedback/LeetCode-Feedback#20851]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

### LeetCode 用户名

he_wenxin@foxmail.com

### 问题号码、标题和链接

116.填充每个节点的下一个右侧节点指针 https://leetcode.cn/problems/populating-next-right-pointers-in-each-node/description/

### Bug 类型
- [ ] 问题描述
- [ ] 示例
- [ ] 问题限制
- [ ] 问题提示
- [ ] 不正确或缺少“相关标签”
- [ ] 不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*
- [ ] 缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*
- [ ] 力扣官方题解
- [x] 编程语言支持

### 描述
leetcode 定义的Node类型无法正常识别

### 你使用的语言
 C++ 

### 你提交或者运行的代码

```
// 无需代码
```

### 屏幕截图
![1709265272239](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/56496643/40363de8-615c-4369-8daf-3784def18ea4)

**Comment by amcones-lc** [comment]
感谢反馈，经核实该题目题解及测试用例暂无异常，力扣会不断努力给大家带来更好的学习社区！后续刷题学习中遇到问题，可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
