### ISSUE TITLE
Missing Test Case - 13. Roman to Integer

### ISSUE THREAD

**Issue by xizhehan** [LeetCode-Feedback/LeetCode-Feedback#20857]
### LeetCode Username
< hhx_ >

### Problem number, title, and link
<   1. https://leetcode.cn/problems/roman-to-integer/  >

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [√ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
<There is no overflow occurred at s[i+1]] >

### Language used for code

C++

### Code used for Submit/Run operation
class Solution {
public:
    int romanToInt(string s) {
    unordered_map<char,int> hs= {
        {'I',1},
        {'V',5},
        {'X',10},
        {'L',50},
        {'C',100},
        {'D',500},
        {'M',1000},
    };
    int res = 0;
    int len = s.size();
    for (int i =0 ; i<len;i++)
    {   
        if(hs[s[i]]>=hs[s[i+1]])
        res= res+hs[s[i]]; 
        else
        res= res-hs[s[i]]; 
    };
    return res;
    }
};

```
// Paste your code here. Don't remove ``` given
// above and below the code.
class Solution {
public:
    int romanToInt(string s) {
    unordered_map<char,int> hs= {
        {'I',1},
        {'V',5},
        {'X',10},
        {'L',50},
        {'C',100},
        {'D',500},
        {'M',1000},
    };
    int res = 0;
    int len = s.size();
    for (int i =0 ; i<len;i++)
    {   
        if(hs[s[i]]>=hs[s[i+1]])
        res= res+hs[s[i]]; 
        else
        res= res-hs[s[i]]; 
    };
    return res;
    }
};
```

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.
Details regarding the missing test case.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team
