### ISSUE TITLE
Missing Test Case - 1609. Even Odd Tree

### ISSUE THREAD

**Issue by prasannapande03** [LeetCode-Feedback/LeetCode-Feedback#20856]
### LeetCode Username
prasannapande

### Problem number, title, and link
1609. Even Odd Sum https://leetcode.com/problems/even-odd-tree/description/

### Category of the bug
- **Missing test Case** (Incorrect/Inefficient Code getting accepted because of missing test cases)

### Description of the bug
The following test case gives wrong answer when I hit run, but the solution is accepted when I submit.
**[11,18,14,3,7,null,null,null,null,18,null,null,6]**

This test case is very similar to the 104th test case: [11,18,14,3,7,null,null,null,null,18,null,6]. I handled the case for the left child but without handling the test case for the right child, I submitted the solution and it got accepted. Thus the above highlighted test case is missing. 

### Language used for code
C++

### Code used for Submit/Run operation

```
/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
class Solution {
public:
    bool isEvenOddTree(TreeNode* root) {
        
      queue<TreeNode*> q;

      q.push(root);
      int level = 1;
      if(root -> val % 2 == 0) return false;

      while(!q.empty()){
        int n = q.size();
        cout<<q.front() -> val<<" "<<level<<endl;
        int prev = 0;

        for(int i = 0; i<n; i++){
          TreeNode* temp = q.front();

          if(temp -> left != NULL){
            if(prev == 0){
              if(level %2 == temp -> left -> val %2 ) return false;
              prev = temp -> left -> val;
            }
            else{
              if(level % 2 == 0){
                if(prev >= temp -> left -> val || temp -> left -> val%2 ==0) {return false;}
              }
              else{
                if(prev <= temp -> left -> val || temp -> left -> val%2 !=0) {return false;}
              }
              prev = temp -> left -> val;
            }

            q.push(temp -> left);
          }
          if(temp -> right != NULL){
            if(prev == 0){
              **// if(level %2 == temp -> right -> val %2 ) return false;**
              prev = temp -> right -> val;
            }
            else{
              if(level % 2 == 0 ){
                if(prev >= temp -> right -> val || temp -> right -> val%2 ==0) {;return false;}
              }
              else{
                if(prev <= temp -> right -> val || temp -> right -> val%2 !=0) {return false;}
              }
              prev = temp -> right -> val;
            }

            q.push(temp -> right);
          }

          q.pop();
        }
        level++;
      }

      return true;
    }
};
```

### Expected behaviour
This code should not be accepted due to the commented line (highlighted in the code). It fails on the above specified missing testcase.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/105285071/fd291ec6-4bd2-4906-a7b8-943d9aaa0e5b)

The code should be accepted when line 50 is uncommented. But the code above get accepted as it is as shown below.

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/105285071/6f3f7a17-aaeb-44a8-af34-9d9683cc3b5c)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission Accepted link you submitted led to the observed result.


Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by prasannapande03** [comment]
### Code Submission Accepted link
https://leetcode.com/submissions/detail/1190515119/

Waiting in anticipation for further developments regarding the same.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
