### ISSUE TITLE
Missing Test Case - 15. 3Sum

### ISSUE THREAD

**Issue by riteshpushkar** [LeetCode-Feedback/LeetCode-Feedback#20853]
### Category of the bug

- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug
Passing Test Cases for wrong return Type 

Problem clearly mentions that output should be of the form List[List[int]]
Whereas is even passing for output of form Set(Tuple(int))

### Language used for code
python3

### Code used for Submit/Run operation

```
class Solution:
    def threeSum(self, nums: List[int]) -> List[List[int]]:
        ans = set()
        nums.sort()
        n = len(nums)
        for i in range(n-2) :
            for j in range(i+1,n-1) :
                for k in range(j+1, n) :
                    if nums[i] + nums[j] + nums[k] == 0 :
                        ans.add((nums[i], nums[j], nums[k]))
        print(ans)
        return ans
```

### Expected behavior

Problem clearly mentions that output should be of the form List[List[int]]

Whereas is even passing for output of form Set(Tuple(int))

### Screenshots

(https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/79689579/bd71f1d5-0289-411c-81ec-8b6043da3f53)

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
