### ISSUE TITLE
Missing Test Case - 35. Search Insert Position iwhat if all the number in an array is same as target number

### ISSUE THREAD

**Issue by pandeyabhisekh** [LeetCode-Feedback/LeetCode-Feedback#20855]
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

**Comment by stormsunshine** [comment]
Do you see that all the numbers in the given array are distinct?
