### ISSUE TITLE
Constraint too tight for the problem 291. Word Pattern II

### ISSUE THREAD

**Issue by yuhan-wang** [LeetCode-Feedback/LeetCode-Feedback#2086]
#### Your LeetCode username

yuhan-wang

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language

#### Description of the bug

The current problem has the following constraint:

0 <= pattern.length <= 20
0 <= s.length <= 50

Consider the test case:

pattern = "abcdefghijklmnopqrsa"
s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwx"

I have used the a few accepted solutions against this test case, and they all get TLE. I suggest either add this test case to eliminate the most naive backtracking solutions or change the constraint so that the constraint truly serves the problem's intention.

#### Code you used for Submit/Run operation

```
class Solution:
    def wordPatternMatch(self, pattern: str, s: str) -> bool:
        
        '''
        Backtracking solution.
        Write a helper to try possible mapping for a new char in pattern.
        If the char in pattern has been seen before, check for match. Continue if true, else return false.
        Once we get through all of pattern, the remaining string should empty.
        '''
        print("abcdefghijklmnopqrsa")
        print("abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwx")
        if not pattern:
            return s == ''
        
        matches = {}
        used = set()
        
        def helper(i, snippet):
            
            if i == len(pattern):
                return snippet == ''
            
            pat_char = pattern[i]
            
            if pat_char not in matches:
                for j in range(1, len(snippet)+1):
                    match = snippet[:j]
                    
                    if match in used:
                        continue
                    
                    matches[pat_char] = match
                    used.add(match)
                    
                    if helper(i+1, snippet[j:]):
                        return True
                    
                    used.discard(match)
                    del matches[pat_char]
                    
                return False
            
            else:
                match = matches[pat_char]
                
                if snippet[:len(match)] == match:   
                    return helper(i+1, snippet[len(match):])
                return False
        
        return helper(0, s)
```

#### Language used for code

Python3

#### Expected behavior

All accepted solutions I checked including this one will receive TLE for the test case I wrote above.

**Comment by stormsunshine** [comment]
I think that the constraint should be modified to smaller values. Namely, the maximum of `pattern.length` should be less than 20 and the maximum of `s.length` should be less than 50.

If the testcase mentioned above needs to be added, then make sure that there exists at least one possible solution for each language that can pass the testcase mentioned above.

**Comment by lc-kay** [comment]
Hi @yuhan-wang 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @yuhan-wang 
Thank you for your time. We've used your feedback to update the constraints and this test case is invalid now.
