### ISSUE TITLE
Missing Test Case - 1581. Customer Who Visited but Did Not Make Any Transactions

### ISSUE THREAD

**Issue by mba1398** [LeetCode-Feedback/LeetCode-Feedback#20862]
### LeetCode Username

披头

### Problem number, title, and link

1581. Customer Who Visited but Did Not Make Any Transactions

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Language used for code

MySQL

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.

| transaction_id | visit_id | amount |
| -------------- | -------- | ------ |
| 2              | 5        | null   |
| 3              | 5        | 300    |
| 9              | 5        | 200    |
| 12             | 1        | 910    |
| 13             | 2        | 970    |
```

### Expected behavior

the answer is wrong, but the case1 check is ok
### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/26516464/11b85efd-3c0d-4110-97f5-b71e283351c5)

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/26516464/16664d81-f3b2-4933-b72c-75a99c84bf4b)

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/26516464/915663f6-5c6c-4116-b2b4-53a4cc8e7361)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.
Details regarding the missing test case.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team
