### ISSUE TITLE
3063题无法使用测试用例进行自测，只能盲交

### ISSUE THREAD

**Issue by shit-eater** [LeetCode-Feedback/LeetCode-Feedback#20875]
LeetCode 用户名
Carl_Czerny

问题号码、标题和链接
3063.链表频率
https://leetcode.cn/problems/linked-list-frequency/

Bug 类型
- [ ] 问题描述
- [√] 示例
- [ ] 问题限制
- [ ] 问题提示
- [ ] 不正确或缺少“相关标签”
- [ ] 不正确的测试用例
- [ ] 缺少测试用例
- [ ] 力扣官方题解
- [ ] 编程语言支持

描述
该题目引入LC平台已有2天，但中国站依然无法使用测试用例进行代码自测，开始是提示缺少输入维度（Expected 3 Got 2），现在则一直”网络错误“，但直接提交可以通过，而且其他题目都不会出现这种问题，可见并不是用户网络问题。

期望行为
无法使用testcase进行自测的bug应当尽快修复

屏幕截图
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73991126/9d70a7ff-5640-42bf-8353-a196d8727afc)

**Comment by chaosxlive** [comment]
It is currently having the same issue in US LC now.
The test result shows "Unknown network error. Please try reloading page.".

**Comment by liyuzhu-lc** [comment]
您好，请问现在可以正常提交吗？目前测试改题目一切正常，如您还是无法正常提交请提供一下您的提交记录，方便我们联系工程师核实具体情况。
