### ISSUE TITLE
Daily Question with inconsistent feedback error message

### ISSUE THREAD

**Issue by ivangfr** [LeetCode-Feedback/LeetCode-Feedback#20871]
### LeetCode Username

ivangfr

### Problem number, title, and link

https://leetcode.com/problems/maximum-odd-binary-number

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

I've realized that we have an inconsistent feedback error message. For instance, when we try to create test cases with binary string "0", that is not valid, as the description says, _"binary string s that contains at least one '1'."_, the message shown is _"Unknown network error. Please try reloading page."_

### Language used for code

Java

### Code used for Submit/Run operation

```
class Solution {
    public String maximumOddBinaryNumber(String s) {
        int num1s = 0;
        for (char c : s.toCharArray()) {
            if (c == '1') {
                num1s++;
            }
        }
        char[] arr = new char[s.length()];
        Arrays.fill(arr, '0');
        arr[arr.length-1] = '1';
        int i = 0;
        while (--num1s > 0) {
            arr[i++] = '1';
        }
        return String.valueOf(arr);
    }
}
```

### Expected behavior

The feedback message should be that the test informed is not valid.

### Screenshots

<img width="510" alt="Screenshot 2024-03-01 at 09 55 17" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/10564548/eba1932c-2623-4a1c-86af-64d108027e2c">
<img width="703" alt="Screenshot 2024-03-01 at 09 55 26" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/10564548/028f4c16-2f9c-41a3-8926-c883c7f73074">

**Comment by LC-Pam** [comment]
Hello,

Thank you for providing your feedback.

Please note that our GitHub repository primarily addresses content and solution-related issues. To ensure a prompt response and effective resolution for feature, function, course access, or product-related feedback, we kindly encourage you to submit such inquiries through our Zendesk Support Channel:

[LeetCode Support](https://leetcode.com/support)

Our dedicated support agents typically respond within 24 hours and promptly report submitted issues to the appropriate departments for investigation.

We greatly appreciate your ongoing support and value your contributions to enhancing the LeetCode experience.

Best regards,
LeetCode Support Team

**Comment by ivangfr** [comment]
HI @LC-Pam , I wrote there but I was redirected to open an issue here

<img width="878" alt="Screenshot 2024-03-05 at 21 30 58" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/10564548/8121e097-daa5-4ac9-a61a-ce046c947c3a">
