### ISSUE TITLE
772. Basic Calculator III: Potential Bug in Test Cases and Judge

### ISSUE THREAD

**Issue by cutylewiwi** [LeetCode-Feedback/LeetCode-Feedback#2087]
#### Your LeetCode username
cutylewiwi

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Input: "-1 + 3 * (2 - 2 * 2 / 2) + 2 * 2 / 3"
Based on the problem description, the above expression should give 0 (-1 + 0 + 1 = 0), but the judge gave 1.

#### Code you used for Submit/Run operation

```
class Solution(object):
    def calculate(self, s):
        """
        :type s: str
        :rtype: int
        """
        
        
        nums = [0]
        ops = []
        
        def eval_once():
            op = ops.pop()
            op2 = nums.pop()
            op1 = nums.pop()
            
            if op == "+":
                nums.append(op1 + op2)
            if op == "-":
                nums.append(op1 - op2)
            if op == "*":
                nums.append(op1 * op2)
            if op == "/":
                nums.append(int(float(op1) / op2))
                
                
        def eval_para():
            while len(ops):
                if ops[-1] == '(':
                    ops.pop()
                    return
                
                eval_once()
                
        for c in s:
            if c in "0123456789":
                nums[-1] = nums[-1] * 10 + int(c)
                continue
                
            if c == " ":
                continue
                
            if c in "+-":
                if len(ops) and ops[-1] in "+-*/":
                    while len(ops) and ops[-1] != "(":
                        eval_once()
                    
                ops.append(c)
                nums.append(0)
                continue
                
            if c in "*/":
                if len(ops) and ops[-1] in "*/":
                    eval_once()
                    
                ops.append(c)
                nums.append(0)
                continue
                
            if c in "(":
                ops.append(c)
                continue
                
            if c in ")":
                eval_para()
                
        while len(ops):
            eval_para()
            
        return nums[0]
```

#### Language used for code
Python

#### Expected behavior

The judge program should return 0 instead of 1

#### Screenshots

<img width="938" alt="Screen Shot 2021-01-20 at 17 06 09" src="https://user-images.githubusercontent.com/6293285/105259999-cde0dd80-5b41-11eb-8076-ea62001b0112.png">

#### Additional context

The current solution can pass all the submission test cases. 
I think the problem is about the rounding in division operations. It might be similar to issue #1972. 
I also tested the input with the solution provided in issue #1972, it gives 0 too.

**Comment by lc-kay** [comment]
Hi @cutylewiwi 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@cutylewiwi The test case is invalid as shown when you test it. Therefore, we will not be accepting this test case. We appreciate your support.
