### ISSUE TITLE
Missing Test Case - 1752. Check if Array Is Sorted and Rotated

### ISSUE THREAD

**Issue by HarshKumarJha8455** [LeetCode-Feedback/LeetCode-Feedback#20870]
If all the array elements are the same, it will show true.
The number of rotations will be zero for sorting the array.
So, this test case should also be there .
<img width="312" alt="Screenshot 2024-03-02 005510" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/104141184/ea24ef7b-be45-4866-9fb8-fdeea512b664">

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
