### ISSUE TITLE
Can't seem to cast to Android TV (Sony Bravia)

### ISSUE THREAD

**Issue by chrispix99** [LeetCode-Feedback/LeetCode-Feedback#20873]
### LeetCode Username
cpick

### Problem number, title, and link
All videos

### Category of the bug
- [ X ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
When watching a video such as the Systems Designs Videos - How to define system requirements - High Availability. If I select cast, it shows the available devices in my house to cast to. If I select one, vimeo shows up on the TV, looks like it is about to start casting, there is a progress bar, which gets to probably 80% then it goes back to the main screen of the Android TV Launcher. This also happens on a Chrome Cast Dongle (4k). I have tried with chrome, chrome incognito from my macbook, I also tried to cast from my Pixel 7 Phone. All have the same results. I have tried casting other Vimeo videos, and those work fine. No other issues casting from any other application / device. 

### Language used for code
n/a

### Code used for Submit/Run operation
n/a

### Expected behavior
Would expect if the chromecast button is enabled on the video for the video to work. (fwiw, I am logged into leetcode with my Google SSO, but my chromecast has a different account logged in)

**Comment by LC-Pam** [comment]
Hello,

Thank you for providing your feedback.

Please note that our GitHub repository primarily addresses content and solution-related issues. To ensure a prompt response and effective resolution for feature, function, course access, or product-related feedback, we kindly encourage you to submit such inquiries through our Zendesk Support Channel:

[LeetCode Support](https://leetcode.com/support)

Our dedicated support agents typically respond within 24 hours and promptly report submitted issues to the appropriate departments for investigation.

We greatly appreciate your ongoing support and value your contributions to enhancing the LeetCode experience.

Best regards,
LeetCode Support Team
