### ISSUE TITLE
Missing Test Case - 2352. Equal Row and Column Pairs

### ISSUE THREAD

**Issue by Albino-Fox** [LeetCode-Feedback/LeetCode-Feedback#20886]
### LeetCode Username

[AlbinoFox](https://leetcode.com/AlbinoFox)

### Problem number, title, and link

2352. Equal Row and Column Pairs https://leetcode.com/problems/equal-row-and-column-pairs/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The code passes existing tests and gives **Accepted** but can't pass mine: 
ex: [[2,3],[3,2]]

Output:
4
Expected:
2

### Language used for code
JavaScript

### Code used for Submit/Run operation

```
/**
 * @param {number[][]} grid
 * @return {number}
 */
var equalPairs = function(grid) {
    let equalPairsAmount = 0;

    let columnHashSumsArray = [];
    let rowHashSumsArray = [];

    for(let rowIndex = 0; rowIndex < grid.length; rowIndex++) {
        let hashSumRow = 0;
        let hashSumColumn = 0;

        let multiplier;

        for(let columnIndex = 0; columnIndex < grid.length; columnIndex++) {
            // check oddness to avoid collisions like in [[2,3,4],[6,1,7],[8,5,9]] with 0 1 and 2 2 row/col
            // when using index of elem in row/col to differ elements placement in the same row/cal
            multiplier = grid[rowIndex][columnIndex] % 2 === 1 ? 2 : 3;
            hashSumRow += grid[rowIndex][columnIndex] * 
                multiplier *
                (columnIndex + 2)
                + Math.ceil((grid[rowIndex][columnIndex] * 999 + 1) / 7);

            multiplier = grid[columnIndex][rowIndex] % 2 === 1 ? 2 : 3;
            hashSumColumn += grid[columnIndex][rowIndex] * 
                multiplier * 
                (columnIndex + 2) 
                + Math.ceil((grid[columnIndex][rowIndex] * 999 + 1) / 7);
        }

        rowHashSumsArray.push(hashSumRow);
        columnHashSumsArray.push(hashSumColumn);
    }

    for (let value1 of rowHashSumsArray) {
        for (let value2 of columnHashSumsArray) {
            if (value1 === value2) equalPairsAmount++;
        }
    }

    return equalPairsAmount;
};
```

### Expected behavior

**Wrong Answer** on Submission

### Additional context

My approach is to calculate hash sums based on sum of the certain row or column elements and to use indexes of elements in those rows/columns to avoid collisions on different elements placement.

I couldn't pass only test case (at current time) [[2,3,4],[6,1,7],[8,5,9]] with 0 1 and 2 2 row/columns because of equal sums with displacement and counted, when they shouldn't, so i decided to differentiate with oddness/evenness by element's value too.

I thought which test cases can fail this approach too, so I found out that for ``n``x``n`` all wrong-for-my-code test cases can be found by combinating ``n`` numbers that will give an equal sum with at least one displacement even with multiplier that depends on oddness/evenness (2/3 here).

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
