### ISSUE TITLE
A video of First Problem Video Walkthrough wasn't appeared

### ISSUE THREAD

**Issue by faisalarip** [LeetCode-Feedback/LeetCode-Feedback#20883]
<img width="824" alt="Screenshot 2024-03-02 at 14 54 28" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/59595501/fe444dbd-8510-4649-815e-d02fadeed2dc">

https://leetcode.com/explore/featured/card/the-leetcode-beginners-guide/678/sql-data-structure/4352/

**Comment by LC-Pam** [comment]
Hello,

Thank you for providing your feedback.

Please note that our GitHub repository primarily addresses content and solution-related issues. To ensure a prompt response and effective resolution for feature, function, course access, or product-related feedback, we kindly encourage you to submit such inquiries through our Zendesk Support Channel:

[LeetCode Support](https://leetcode.com/support)

Our dedicated support agents typically respond within 24 hours and promptly report submitted issues to the appropriate departments for investigation.

We greatly appreciate your ongoing support and value your contributions to enhancing the LeetCode experience.

Best regards,
LeetCode Support Team
