### ISSUE TITLE
面试题 08.08. 有重复字符串的排列组合的英语题目描述需要更新

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#2088]
**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
「[面试题 08.08. 有重复字符串的排列组合](https://leetcode-cn.com/problems/permutation-ii-lcci/)」的英语描述，characters 中间多了一个空格，请把空格去掉，使得这是一个单词。

**你使用的语言**
Java

**你提交或者运行的代码**

**期望行为**
更新英语题目描述，去掉空格。

**屏幕截图**
![image](https://user-images.githubusercontent.com/12067364/105271142-f57f8680-5bd1-11eb-9d4a-eefb218eeb72.png)

**额外的上下文**

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前题目描述已更新，ID：stormsunshine 给予积分奖励，请查收。
