### ISSUE TITLE
"73. Set Matrix Zeroes" C++ code runner seems broken

### ISSUE THREAD

**Issue by ysk24ok** [LeetCode-Feedback/LeetCode-Feedback#209]
**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**

C++ code runner throws the following compile error, even though my code does not contain `resize()` call.

**what language is your code written in**
C++

**The code you submit/run**
```cpp
class Solution {
 public:
  void setZeroes(vector<vector<int>>& matrix) {
    const size_t m = matrix.size();
    if (m == 0) return;
    const size_t n = matrix[0].size();
    bool update_col0 = false;
    // set marker
    for (size_t i = 0; i < m; ++i) {
      if (matrix[i][0] == 0) { update_col0 = true; }
      for (size_t j = 0; j < n; ++j) {
        if (matrix[i][j] == 0) {
          matrix[i][0] = 0;
          matrix[0][j] = 0;
        }
      }
    }
    // update
    for (size_t i = m; i > 0; --i) {
      for (size_t j = n; j > 1; --j) {
        if (matrix[i-1][0] == 0 || matrix[0][j-1] == 0) {
          matrix[i-1][j-1] = 0;
        }
      }
      if (update_col0) { matrix[i-1][0] = 0; }
    }
  }
};
```

**Expected behavior**
The code runner can compile and execute the code above.
In my local environment, it can be compiled and executed.

**Screenshots**
![スクリーンショット 2020-04-29 11 13 55](https://user-images.githubusercontent.com/3449164/80574621-282e9100-8a3d-11ea-9048-16898fa2a416.png)

**Additional context**
I've opened a post for this problem, and one user has commented that he/she got the same error.
https://leetcode.com/problems/set-matrix-zeroes/discuss/602455/C%2B%2B-code-runner-is-broken

And there is related post of this bug.
https://leetcode.com/problems/set-matrix-zeroes/discuss/602725/Compile-error-with-default-code

**Comment by CooperCooperCooper** [comment]
Hi @ysk24ok,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by luizfls** [comment]
Exactly, I am the OP for the discussion thread linked. Just to add more info: the error will happen even if you don't write code at all.

**Comment by CooperCooperCooper** [comment]
Hi @luizfls,
Thank you for your time and additional clarification. Our team found this issue to be a system issue and not a content issue. It's currently under investigation so we can fix it soon. If you would like more updates on this issue, please redirect this issue to our main support channel "support@leetcode.com". We appreciate your time and support.

**Comment by CooperCooperCooper** [comment]
Hi @luizfls,
Just a gentle update: the issue is now fixed.

**Comment by ysk24ok** [comment]
Thank you very much for this fix!
