### ISSUE TITLE
Glitch in Leetcode : 1261. Find Elements in a Contaminated Binary Tree

### ISSUE THREAD

**Issue by Rohitesh-Kumar-Jain** [LeetCode-Feedback/LeetCode-Feedback#2090]
#### Your LeetCode username

https://leetcode.com/Kumar-Jain/

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

There is a bug in Java submission in question "1261. Find Elements in a Contaminated Binary Tree", I have written a correct code that should pass all the test cases, yet it is showing the **_wrong_** answer (note the word wrong not TLE), when I run the failed test case, it shows accepted correct answer. I also implemented the same logic in Cpp and it got accepted. I feel that their is bug in this question, pls rectify it. 

[This is my failing correct JAVA code](https://leetcode.com/submissions/detail/445752597/)
[The problem is In JAVA only I guess](https://leetcode.com/submissions/detail/445752284/)

#### Code you used for Submit/Run operation

```
class FindElements {
    public static HashSet<Integer> hashset = new HashSet<>();
    
    public void inorder(TreeNode root, int value){
        if(root == null) return;
        inorder(root.left, value*2 +1);
        root.val = value;
        hashset.add(value);
        inorder(root.right, value*2 +2);
    }
    
    public FindElements(TreeNode root) {
        inorder(root,0);
    }
    
    public boolean find(int target) {
        return hashset.contains(target);
    }
}
```

#### Language used for code

JAVA

#### Expected behavior

It should have passed all the test cases. 

#### Screenshots

<img width="1440" alt="Screenshot 2021-01-21 at 10 05 13 AM" src="https://user-images.githubusercontent.com/62026125/105281118-683c3200-5bd1-11eb-8eda-ee3790d636c7.png">

[](url)

#### Additional context

Pls fix it, I am very much fond of leetcoding : )

**Comment by zerotrac** [comment]
Please do not use static variables in your code.

**Comment by lc-kay** [comment]
Hi @Rohitesh-Kumar-Jain 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.

**Comment by Rohitesh-Kumar-Jain** [comment]
> Please do not use static variables in your code. The class will be instantiated multiple times when testing your code.

Yeah you are right, thanks.

**Comment by Rohitesh-Kumar-Jain** [comment]
> Hi @Rohitesh-Kumar-Jain
> Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.

Thanks for sharing the link.
