### ISSUE TITLE
Missing Test Case - 14. Longest Common Prefix

### ISSUE THREAD

**Issue by KTS-o7** [LeetCode-Feedback/LeetCode-Feedback#20915]
### Category of the bug
- [ ] Even with correct output , evaluated to wrong answer.

### Description of the bug

1. Test case in question - `["a"]`
2. Even though the code produces the output which matches with the expected output, it's evaluated as Wrong Answer.
3. Code has been attached along with screenshot.
4. It is supposed to throw a run time error as the variable match is being incremented and tries to access the string element which is not present.

### Language used for code

C++

### Code used for Submit/Run operation

```cpp

class Solution {
public:
    string longestCommonPrefix(vector<string>& strs) {
        bool flag = true;
        string ans = "";
        int match = 0;
        sort(strs.begin(),strs.end());
        if(strs[0]=="")
            return "";
        while(flag && ans.size()<=strs[0].size()){
            int ch = strs[0][match];
            for(int i = 1; i<strs.size(); i++){
                if(ch != strs[i][match])
                     {
                         flag = false;
                         return ans;
                     }
                
            }
            match++;
            ans+=ch;
        }
        return ans;

        
    }
};
```

### Expected behavior

- Should be a Run time error.

### Screenshots

![Screenshot from 2024-03-03 10-27-41](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/119525616/d27d2866-396a-4339-b231-25e780c17e10)

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
