### ISSUE TITLE
Programming language support TLE on 3072. Distribute Elements Into Two Arrays II

### ISSUE THREAD

**Issue by egor000** [LeetCode-Feedback/LeetCode-Feedback#20913]
### LeetCode Username
Egor000

### Problem number, title, and link
https://leetcode.com/contest/weekly-contest-387/problems/distribute-elements-into-two-arrays-ii/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ X] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ X] Programming language support

### Description of the bug
TLE with a solution that should pass based on the problem's constraints and the solution's complexity

### Language used for code
Java

### Code used for Submit/Run operation

```
class Solution {
    public int[] resultArray(int[] nums) {
        TreeSet<Integer> set1 = new TreeSet<>((a, b) -> (nums[a] == nums[b])?(a - b):(nums[a] - nums[b]));
        List<Integer> arr1 = new ArrayList<>(nums.length);
        TreeSet<Integer> set2 = new TreeSet<>((a, b) -> (nums[a] == nums[b])?(a - b):(nums[a] - nums[b]));
        List<Integer> arr2 = new ArrayList<>(nums.length);
        arr1.add(nums[0]);
        set1.add(0);
        arr2.add(nums[1]);
        set2.add(1);
        for (int i = 2; i < nums.length; i++) {
            int size1 = set1.tailSet(i, false).size();
            int size2 = set2.tailSet(i, false).size();
            if (size1 > size2) {
                arr1.add(nums[i]);
                set1.add(i);
            } else if (size1 < size2) {
                arr2.add(nums[i]);
                set2.add(i);                
            } else {
                if (arr1.size() <= arr2.size()) {
                    arr1.add(nums[i]);
                    set1.add(i);                    
                } else {
                    arr2.add(nums[i]);
                    set2.add(i);                                
                } 
            }
        }
        
        int ind = 0;
        for (int val: arr1) {
            nums[ind] = val;
            ind++;
        }
        for (int val: arr2) {
            nums[ind] = val;
            ind++;
        }
        return nums;
    }
}
```

### Expected behavior
Code has complexity of O(NlogN), but fails with TLE, 
There is a similar submission with the same complexity that passed all test cases
e.g. https://leetcode.com/problems/distribute-elements-into-two-arrays-ii/solutions/4813799/java-solution-with-comments/

**Comment by projecteulerlover** [comment]
https://stackoverflow.com/questions/14750374/what-is-complexity-of-size-for-treeset-portion-view-in-javaa

as you can see here, while tailSet creation is ~log(N), calling size on the resulting view is potentially O(n log n). That's why this fails.

**Comment by egor000** [comment]
Thanks, that makes sense now, the issue can be closed.
