### ISSUE TITLE
Testcases in Distribute Elements Into Two Arrays II are too weak

### ISSUE THREAD

**Issue by mathtsai** [LeetCode-Feedback/LeetCode-Feedback#20914]
### LeetCode Username
mathtsai

### Problem number, title, and link
3072. https://leetcode.com/problems/distribute-elements-into-two-arrays-ii/description/

### Category of the bug
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

Weak testcases.

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

### Expected behavior

Tesecases like: [10000,1,9999,9998,9997,...], whoever submit two sorted vector takes O(n^2), and they should be TLE.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.


Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by sardorboboshov** [comment]
you already rated the contest without additional testcases.
like what is the meaning of labelling problem as hard and giving such constraints(that always give TLE for n^2 solutions) if it can be just solved with brute-force simulation.
Not only q4, but even the q2 testcases are too weak. O(n^3) solutions are giving acc for n <= 1000, that is just crazy
