### ISSUE TITLE
Missing Test Case - 705. Design HashSet

### ISSUE THREAD

**Issue by dengere** [LeetCode-Feedback/LeetCode-Feedback#20925]
### [705. Design HashSet](https://leetcode.com/problems/design-hashset/)

0 <= key <= 106
At most 104 calls will be made to add, remove, and contains.

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [X] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

0 <= key <= 106 but there is not any test cases has insertation by 0. Many accepted solution based on control logic  key != 0

### Language used for code
C#

### Expected behavior
Hash can accept 0 and should have guaranted with insertation with 0.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.
Details regarding the missing test case.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team
