### ISSUE TITLE
Missing test Case - 3036. Number of Subarrays That Match a Pattern II

### ISSUE THREAD

**Issue by AkshatUke** [LeetCode-Feedback/LeetCode-Feedback#20924]
### LeetCode Username

AkshatUke

### Problem number, title, and link

3036. Number of Subarrays That Match a Pattern II https://leetcode.com/problems/number-of-subarrays-that-match-a-pattern-ii/

- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

There Is only one test case of Array Length 1000000 If I use another test case another then that then it will give Time Limit Exceed

### Language used for code

Java

### Code used for Submit/Run operation

```
class Solution {
    public int countMatchingSubarrays(int[] nums, int[] pattern) {
        int n = nums.length;
        int m = pattern.length;
        if(n == 1000000) {
            return 166667;
        }
        int count = 0;
        int j = m;
        for(int i = 0;i < n-m;i++,j++) {
                boolean test = true;
                for(int k = i+1,l = 0;k <= j;k++,l++) {
                    if(l == m) {
                        l = 0;
                    }
                    if(pattern[l] == 1) {
                        if(nums[k] <= nums[k-1]) {
                            test = false;
                            break;
                        }
                    }
                    else if(pattern[l] == 0) {
                        if(nums[k] != nums[k-1]) {
                            test = false;
                            break;
                        }
                    }
                    else if(pattern[l] == -1) {
                        if(nums[k] >= nums[k-1]) {
                            test = false;
                            break;
                        }
                    }
                }
                if(test) {
                    count++;
                }
        }
        return count;
    }
}
```

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
