### ISSUE TITLE
Missing Test Case - 1769. Get Maximum in Generated Array

### ISSUE THREAD

**Issue by paris0120** [LeetCode-Feedback/LeetCode-Feedback#2093]
#### Your LeetCode username
paris0120

#### Category of the bug
- [ ] Question
- [ x] Solution
- [ ] Language

#### Description of the bug
Input:
15
Output:
4
Expected:
5

  nums[7 * 2) + 1 = 15] = nums[7] + nums[8] = 3 + 1 = 4

 nums[8] = nums[4] = nums[2] = 1
  nums[(3 * 2) + 1 = 7] = nums[3] + nums[4] = 2 + 1 = 3 (as the example)

#### Code you used for Submit/Run operation

```
class Solution(object):
    def __init__(self):
        self.v = {0:0, 1:1}
        
    def get(self, n):
        try:
            return self.v[n]
        except:
            i, r = divmod(n, 2)
            if(r==0):
                v = self.get(i)
            else:
                v = self.get(i+1)+self.get(i)
            self.v[n] = v
            return v
            
    def getMaximumGenerated(self, n):
        """
        :type n: int
        :rtype: int
        """ 
        if(n==0):
            return 0
        else:
            v, r = divmod(n+1, 2)
            n = v*2-1
            return self.get(n)
```

#### Language used for code
Python

**Comment by lc-kay** [comment]
@paris0120 What is the issue you are trying to report?

**Comment by paris0120** [comment]
The answer should be 4 for the input of 15 but the answer in the system is 5.

**Comment by paris0120** [comment]
My bad. Got it wrongly.
