### ISSUE TITLE
Missing Test Case - 26. Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by Alf51** [LeetCode-Feedback/LeetCode-Feedback#20932]
### LeetCode Username

Alf51 https://leetcode.com/Alf51

### Problem number, title, and link

26. Remove Duplicates from Sorted Array https://leetcode.com/problems/remove-duplicates-from-sorted-array/description/

### Category of the bug
- [ ] Solved examples

### Description of the bug

The Case 1 solution does not pass in LeetCode, but it works in my local IDEA

### Language used for code

Kotlin 

### Code used for Submit/Run operation

```
class LetsCodeKotlin {
    fun removeDuplicates(nums: IntArray): Int {
        val arrWithoutDuplicate = nums.distinct()
        for ((index, i) in arrWithoutDuplicate.withIndex()) {
            nums[index] = i
        }
        return nums.size - arrWithoutDuplicate.size
    }
}
```

### Expected behavior

An array [1, 2, 2] was expected, but the output received an array [1] in Case 1

### Additional context

![sol1](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103650910/ff79e180-56c1-41cf-b9c2-2235c8616f38)

![sol2](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103650910/66a355f3-7d26-4a4a-8d41-7341682ed35f)

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback. We encourage you to share your questions in the discussion forum, where the community can provide insights and assistance.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
