### ISSUE TITLE
Missing Test Case - 3072. Distribute Elements Into Two Arrays II

### ISSUE THREAD

**Issue by przemek3d88** [LeetCode-Feedback/LeetCode-Feedback#20947]
### LeetCode Username
przemysaw2

### Problem number, title, and link

 3072. Distribute Elements Into Two Arrays II https://leetcode.com/problems/distribute-elements-into-two-arrays-ii/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
Inefficient $O(n^2)$ solutions pass system tests.

### Language used for code
C++

### Code used for Submit/Run operation

```
class Solution {
public:
    int greaterCount(vector<int>& arr, int val) {
        return arr.end() - upper_bound(arr.begin(), arr.end(), val);
    }

    vector<int> resultArray(vector<int>& nums) {
        int n = nums.size();
        
        vector<int> left, right, ll, rr;
        left.push_back(nums[0]);
        right.push_back(nums[1]);
        ll.push_back(nums[0]);
        rr.push_back(nums[1]);
        
        int l = 0, r = 0;
        
        for (int i = 2; i < n; i++) {
            int x = greaterCount(left, nums[i]);
            int y = greaterCount(right, nums[i]);
            
            if (x > y) {
                
                left.insert(left.end() - x , nums[i]);
                ll.push_back(nums[i]);
                l++;
            } else if (x < y) {
                
                right.insert(right.end() - y, nums[i]);
                rr.push_back(nums[i]);
                r++;
            } else {
                if (l <= r) {
                    
                    left.insert(left.end() - x, nums[i]);
                    ll.push_back(nums[i]);
                    l++;
                } else {
                    
                    right.insert(right.end() - y, nums[i]);
                    rr.push_back(nums[i]);
                    r++;
                }
            }
        }
        
        
        ll.insert(ll.end(), rr.begin(), rr.end());
        return ll;
    }
};
```

### Expected behavior
The above code should receive a TLE verdict, whilst it is accepted.

### Additional context
3 attached max tests cause TLE. The test is attached in the file or the test generator is below:

```
printf("[");
for (int i = 100000; i > 1; i--) {
    printf("%d,", i);
}
printf("1]");
```

[out.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/14474938/out.txt)

**Comment by Iron-Buster** [comment]
Hi，Is it TLE caused by insertion sorting? left.insert(left.end() - x, nums[i]);

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

We can't add the test case currently because of technical issues.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team

**Comment by jc1651** [comment]
> We can't add the test case currently because of technical issues.
Can you elaborate on that? I don't see a reason to not add that test case. it's just a simple descending order sorted array

**Comment by JustJie2002** [comment]
> We can't add the test case currently because of technical issues.

Can you elaborate on that? I don't see a reason to not add that test case. it's just a simple descending order sorted array
