### ISSUE TITLE
Missing Test Case - 1944. Number of Visible People in a Queue

### ISSUE THREAD

**Issue by k0nst4nt1n** [LeetCode-Feedback/LeetCode-Feedback#20942]
### LeetCode Username
k0nst4nt1n

### Problem number, title, and link
1944 Number of Visible People in a Queue https://leetcode.com/problems/number-of-visible-people-in-a-queue/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
If we have several minions of the same height then the previous to them should see only the first of them. Most solutions with monotonic stack will count all the minions with the same height.

### Language used for code
Go

### Code used for Submit/Run operation
```
func canSeePersonsCount(heights []int) []int {
    res := make([]int, len(heights))
    stack := make([]int, 0) 
    for i := len(heights)-1; i >= 0; i-- {
        for len(stack) > 0 && heights[i] > stack[len(stack)-1] {
            stack = stack[:len(stack)-1]
            res[i]++
        }
        if len(stack) > 0 {
            res[i]++
        }
        stack = append(stack, heights[i])
    }
    return res
}
```

### Expected behavior
For the test [2,1,1], expected answer is [1,1,0]. When we add this test case after the default ones, we get the following result "Unknown network error...".

### Screenshots

<img width="418" alt="the test" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/51010814/bf1b50cb-70a3-4e65-a80b-9b3c568cfa17">

<img width="765" alt="service crashed" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/51010814/2f601e6a-48e2-461e-9647-331f4d287d70">

### Additional context
The code that considers the missing test case mentioned above is:

```
func canSeePersonsCount(heights []int) []int {
    res := make([]int, len(heights))
    stack := make([]int, 0) 
    for i := len(heights)-1; i >= 0; i-- {
        for len(stack) > 0 && heights[i] > stack[len(stack)-1] {
            stack = stack[:len(stack)-1]
            res[i]++
        }
        if len(stack) > 0 {
            res[i]++
            if heights[i] == stack[len(stack)-1] { // without this if gets accepted too
                stack = stack[:len(stack)-1]
            }
        }
        stack = append(stack, heights[i])
    }
    return res
}
```

**Comment by LC-Pam** [comment]
Hello,

Thank you for providing your feedback.

Please note that our GitHub repository primarily addresses content and solution-related issues. To ensure a prompt response and effective resolution for feature, function, course access, or product-related feedback, we kindly encourage you to submit such inquiries through our Zendesk Support Channel:

[LeetCode Support](https://leetcode.com/support)

Our dedicated support agents typically respond within 24 hours and promptly report submitted issues to the appropriate departments for investigation.

We greatly appreciate your ongoing support and value your contributions to enhancing the LeetCode experience.

Best regards,
LeetCode Support Team
