### ISSUE TITLE
Content Issue in 907. Sum of Subarray Minimums

### ISSUE THREAD

**Issue by prash9706** [LeetCode-Feedback/LeetCode-Feedback#2094]
In question 907 constraints are given twice and they are inconsistent. 
![907](https://user-images.githubusercontent.com/21213787/105416001-20cc9a80-5bff-11eb-9ed0-4ef162260d7f.JPG)

I coded a n^2 solution by looking at the constraint 1 but it ended up giving time limit exceeded. It would be helpful to have constraints at only one place.

**Comment by lc-kay** [comment]
Hi @prash9706 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @prash9706 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
