### ISSUE TITLE
Missing Test Case - 19. Remove Nth Node From End of List

### ISSUE THREAD

**Issue by nileshchatte1** [LeetCode-Feedback/LeetCode-Feedback#20943]
### LeetCode Username

[nileshchatte](https://leetcode.com/nileshchatte)

### Problem number, title, and link

19. Remove Nth Node From End of List https://leetcode.com/problems/remove-nth-node-from-end-of-list/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

In case the n value is bigger than the number of nodes in the list, this case should be handled.

### Language used for code

C++

### Code used for Submit/Run operation

```
/**
 * Definition for singly-linked list.
 * struct ListNode {
 *     int val;
 *     ListNode *next;
 *     ListNode() : val(0), next(nullptr) {}
 *     ListNode(int x) : val(x), next(nullptr) {}
 *     ListNode(int x, ListNode *next) : val(x), next(next) {}
 * };
 */
class Solution {
public:
    ListNode* removeNthFromEnd(ListNode* head, int n) {
        // Calculate the length of the linked list
        int length = 0;
        ListNode* temp = head;
        while (temp) {
            temp = temp->next;
            length++;
        }

        // Calculate the position of the node to remove
        int position = length - n;

        // Handle removal of the first node
        if (position == 0) {
            return head->next;
        }

        // Traverse to the node before the one to remove
        temp = head;
        for (int i = 1; i < position; i++) {
            temp = temp->next;
        }

        // Remove the nth node
        temp->next = temp->next->next;

        return head;
    }
};
```

### Expected behavior

This code should not be accepted if the number of nodes in the list is less than n value.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

Details regarding the missing test case.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team
