### ISSUE TITLE
missing test case 948. Bag of Tokens

### ISSUE THREAD

**Issue by ronghuang0** [LeetCode-Feedback/LeetCode-Feedback#20951]
### LeetCode Username
ronghuang0

### Problem number, title, and link

948. Bag of Tokens https://leetcode.com/problems/bag-of-tokens/description/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

missing test case: tokens=[10], power=10

### Language used for code

python

### Code used for Submit/Run operation

```
class Solution:
    def bagOfTokensScore(self, tokens: List[int], power: int) -> int:
        tokens.sort()
        score = 0
        res = 0
        while tokens and (power > tokens[0] or score>0):
            if power>=tokens[0]:
                power-=tokens[0]
                tokens.pop(0)
                score+=1
            else:
                power+=tokens[-1]
                tokens.pop()
                score-=1
            res = max(res, score)
        return res
```

### Expected behavior

The above code gives result of 0 for testcase of tokens=[10], power=10 but the expected result is 1

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team
