### ISSUE TITLE
User Experience: Unknown Network Issue, Try Reloading Page

### ISSUE THREAD

**Issue by sdsunjay** [LeetCode-Feedback/LeetCode-Feedback#20955]
### LeetCode Username

sdsunjay

### Problem number, title, and link

729. My Calendar 1 - [https://leetcode.com/problems/my-calendar-i/](https://leetcode.com/problems/my-calendar-i/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support
- [X] User Experience

### Description of the bug
When a test case is formatted incorrectly, the user is given the following error:
> Unknown network error. Please try reloading page.

### Language used for code
Python3

### Code used for Submit/Run operation
The code isn't relevant for this issue

### Test cases used for Submit/Run operation
```
["MyCalendar","book","book","book","book","book"]
[[],[10,20],[11,14],[19,30],[5,10],[4,5]
```
Note that the test case is missing a final `]`

### Expected behavior
The user should be notified that the test case is invalid. Telling the user that there was a 'network issue' and to 'try reloading the page' is misleading. 

### Screenshots

<img width="1483" alt="" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/3431549/c895dddd-d4a4-44db-9010-3dab7f82e441">
<img width="1483" alt="" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/3431549/119b92ea-15e5-4936-a980-7d65bb304804">

### Additional context
The errors in the JavaScript console may be relevant to fixing the issue. Chrome version 124.

**Comment by LC-Pam** [comment]
Hello,

Thank you for providing your feedback.

Please note that our GitHub repository primarily addresses content and solution-related issues. To ensure a prompt response and effective resolution for feature, function, course access, network error or product-related feedback, we kindly encourage you to submit such inquiries through our Zendesk Support Channel:

[LeetCode Support](https://leetcode.com/support), select "Technical Support".

Our dedicated support agents typically respond within 24 hours and promptly report submitted issues to the appropriate departments for investigation.

We greatly appreciate your ongoing support and value your contributions to enhancing the LeetCode experience.

Best regards,
LeetCode Support Team
