### ISSUE TITLE
Typo mistake.

### ISSUE THREAD

**Issue by k22sumit** [LeetCode-Feedback/LeetCode-Feedback#20956]
where each tokens[i] donates the value of token.

donates -> denotes

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The problem page link. 

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team
