### ISSUE TITLE
Incorrect Test Case  - 543. Diameter of Binary Tree

### ISSUE THREAD

**Issue by xza-m** [LeetCode-Feedback/LeetCode-Feedback#20966]
### LeetCode Username
每日一题

### Problem number, title, and link
https://leetcode.cn/problems/diameter-of-binary-tree/

### Category of the bug
Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### Description of the bug
for case,i should have passed,but got error.

### Language used for code
SCALA

### Code used for Submit/Run operation

```scala
/**
 * Definition for a binary tree node.
 * class TreeNode(_value: Int = 0, _left: TreeNode = null, _right: TreeNode = null) {
 *   var value: Int = _value
 *   var left: TreeNode = _left
 *   var right: TreeNode = _right
 * }
 */
object Solution {

    var maxLength = 0
    def diameterOfBinaryTree(root: TreeNode): Int = {

        // 后序
        maxDepth(root)
        maxLength
    }

    def maxDepth(root:TreeNode): Int = {
        if(root == null){
            return 0
        }
        val leftLength = maxDepth(root.left)
        val rightLength = maxDepth(root.right)
        maxLength = Array(maxLength, leftLength + rightLength).max
        
        1 + Array(leftLength, rightLength).max
    }
}
```

### Expected behavior
for input treenode [1,2], i should get result 1,but got 3.

### Screenshots
<img width="426" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/45376739/e14e2e64-fd42-4e6e-82eb-d1e6f514dfbc">

**Comment by xza-m** [comment]
:)

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
