### ISSUE TITLE
Missing Test Case - 948. Bag of Tokens

### ISSUE THREAD

**Issue by GeorgeManukyan** [LeetCode-Feedback/LeetCode-Feedback#20969]
### LeetCode Username
tlamer

### Problem number, title, and link
948 Bag of tokens (https://leetcode.com/problems/bag-of-tokens/ 

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [# ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
Missing test 
My solution got accepted, but gives incorrect answer on this test case 
[20,20,20,20,1000]
80 

### Language used for code

C++

### Code used for Submit/Run operation

```
class Solution {
public:
    int bagOfTokensScore(vector<int>& tokens, int power) {
        auto total = accumulate(begin(tokens), end(tokens), 0);
        if (power >= total) return tokens.size();
        sort(begin(tokens), end(tokens));

        int score = 0;

        int i = 0;
        int j = tokens.size()-1;

        while(total > power && i < j)
        {
            if (tokens[i] < power){
                score++;
                power -= tokens[i];
                total -= tokens[i];
                i++;
            }
            else if (score > 0)
            {
                power += tokens[j];
                total -= tokens[j];
                score--;
                j--;
            }
            else break;
        }

        if (total <= power)
            score += j - i +1;

        return score;

    }
};
```

### Expected behavior

My solution got accepted, but gives incorrect answer on this test case 
[20,20,20,20,1000]
80

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
