### ISSUE TITLE
Missing Test Case - 521. Longest Uncommon Subsequence I

### ISSUE THREAD

**Issue by Dileesha8** [LeetCode-Feedback/LeetCode-Feedback#20964]
### LeetCode Username

dileesha_thesparkle

### Problem number, title, and link
521 .Longest uncommon subsequence 1 
https://leetcode.com/problems/longest-uncommon-subsequence-i/description/

### Category of the bug
 Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug
test case:  Input: a = "aaab", b = "aaa"
Output: 3
but my code gives output 4 and it is accepted and submitted the code 

### Language used for code
C++

### Code used for Submit/Run operation

```
class Solution {
public:
    int findLUSlength(string a, string b) {
        if (a == b) {
            return -1; 
        } else { 
            return max(a.length(), b.length());
        }
    }
};
```

### Expected behavior

test case:  Input: a = "aaab", b = "aaa"
Output: 3
but my code gives output 4 and it is accepted and submitted the code 

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/114459479/5357a078-9206-46d0-a015-72285f7263ca)

### Additional context
I have created a main function for this problem inorder to run the code manually

**Comment by LC-Pam** [comment]
Hi there,

Thank you for bringing your feedback to our attention. We've conducted a thorough investigation into the issue you raised, and after careful examination, our findings affirm that our judge is working correctly.

We appreciate the time and effort you've invested in sharing your feedback. It's invaluable to us as we work towards maintaining a high-quality platform.

Feel free to continue the dialogue here or provide any additional insights. We value your input and strive to create a collaborative space for improvement.

Best regards,
The LeetCode Team
