### ISSUE TITLE
Missing Test Case - 1703. Minimum Adjacent Swaps for K Consecutive Ones

### ISSUE THREAD

**Issue by xswzaq44321** [LeetCode-Feedback/LeetCode-Feedback#20962]
### LeetCode Username
[xswzaq44321](https://leetcode.com/xswzaq44321/)

### Problem number, title, and link
[1703. Minimum Adjacent Swaps for K Consecutive Ones](https://leetcode.com/problems/minimum-adjacent-swaps-for-k-consecutive-ones/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Language used for code
C++

### Code used for Submit/Run operation
```c++
class Solution {
public:
    int minMoves(vector<int>& nums, int k) {
        vector<int> ones;
        int ans, sum = 0;
        for(int i = 0; i < nums.size(); ++i){
            if(nums[i])
                ones.push_back(i);
        }
        for(int i = 1; i < k; ++i)
            sum += (ones[i] - ones[i / 2]);
        ans = sum;
        for(int i = k; i < ones.size(); ++i){
            sum += (ones[i] - ones[i - 1 - (i - 1 - (i - k)) / 2]);
            sum -= (ones[i - (i - (i - k)) / 2] - ones[i - k]);
            ans = min(ans, sum);
        }
        return ans - (k / 2) * (k / 2 + 1) / 2 - ((k - 1) / 2) * ((k - 1) / 2 + 1) / 2;
    }
};
```

### Expected behavior

My submitted code passed all test cases, but the code has a bug that failed to pass my custom test case.
Test Case is here, it's quite large so I use pastebin.
https://pastebin.com/079kEe33

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/32536699/a5fbaba5-ca8d-4a81-84d3-27db94732423)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/32536699/a0821025-b66b-4947-9cf4-f81df1a71e7e)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
