### ISSUE TITLE
Missing clarification in problem 948. Bag of Tokens

### ISSUE THREAD

**Issue by mrprince74** [LeetCode-Feedback/LeetCode-Feedback#20968]
### LeetCode Username
MrPrince22

### Problem number, title, and link
948, Bag of Tokens, [problem link](https://leetcode.com/problems/bag-of-tokens/)

### Category of the bug
- [x] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [X] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
I have a problem with the test case number 137.
Test case : tokens = [71,55,82], power = 54
The correct answer is 1 not 0.. This is done by the following sequence:

1. Score is initially 0
2. Play token2 (82) face-down, increasing power to 136 and reducing score to -1.
3. Play token1 (55) face-up, reducing power to 81 and increasing score to 0.
4. Play token0 (71) face-up, reducing power to 10 and increasing score to 1.

Thus the answer should be 1 not 2. The problem description didn't include a note that the score cannot be negative, and thus this arrangement is indeed possible. 

### Language used for code
C++

### Code used for Submit/Run operation
```
class Solution {
public:
    int bagOfTokensScore(vector<int>& tokens, int power) {
        multiset<int> s;
        for(int token : tokens){
            s.insert(token);
        }
        int ans = 0;
        int me = 0;
        while(!s.empty()){
            bool can_sell = power >= *s.begin();
            auto mn = s.begin();
            auto mx = s.rbegin();
            if (can_sell){
                me++;
                power-= *mn;
                s.erase(mn);
            }
            else{
                me--;
                power+= *mx;
                s.erase(s.find(*mx));
            }
            ans = max(ans, me);
        }
        return ans;
    }
};
```

### Expected behavior
Either this test case is modified to be 1 instead of 0, or the problem description is modified to include a note that the score cannot be negative, and just keep the test cases as they are.

### Screenshots
<img width="1176" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/160225164/8fc6663a-0128-4f41-bfb6-25c90fa6503c">

### Additional context
None

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
