### ISSUE TITLE
Missing Test Case - 323. Number of Connected Components in an Undirected Graph

### ISSUE THREAD

**Issue by RomanIvanovMinsk** [LeetCode-Feedback/LeetCode-Feedback#20976]
### LeetCode Username

RomanIvanovMinsk

### Problem number, title, and link

1. Number of Connected Components in an Undirected Graph - https://leetcode.com/explore/interview/card/leetcodes-interview-crash-course-data-structures-and-algorithms/707/traversals-trees-graphs/4670/

### Category of the bug
- [ ] Problem description

### Description of the bug

According to the description of the problem test case 
4
[[2,3],[1,2],[1,3]]
is not correct because there is only - 3 nodes:
1-1
2-2
3-3
I cant uderstand how the right unswer here could be 2 if all nodes have connections 1 -> 2 -> 3 -> 1
So its something wron with test case or with my undertastanding. 

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

### Expected behavior

Expected behavior should be 1 and 3 node in the description

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.


Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team
