### ISSUE TITLE
Missing Test Case - 948. Bag of Tokens

### ISSUE THREAD

**Issue by amaltscaria** [LeetCode-Feedback/LeetCode-Feedback#20971]
### LeetCode Username

ethanhunt007

### Problem number, title, and link

948. Bag of Tokens https://leetcode.com/problems/bag-of-tokens/description/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

My code passed all the test 147 test cases. But it did not pass my custom test case which is a bug.

### Language used for code

Javascript

### Code used for Submit/Run operation

```
var bagOfTokensScore = function(tokens, power) {
    let score = 0;
    tokens.sort((a,b)=>a-b);
    let left = 0;
    let right = tokens.length - 1;
    while(left<=right){
    if(power>=tokens[left]) {
        score++;
        power-=tokens[left];
        left++;
    } else {
        if(score && power === 0){
            score--;
            power+=tokens[right];
            right--;
        }
        else if(right && left !== right && power>0 && score) {
            score--;
            power+=tokens[right];
            right--;
        } else {
            left++;
        }
      
    }
    }
    return score;
};
```

### Expected behavior

My code was not supposed to clear the custom test case I provided which is =>
power = 21 and tokens = [7,14,21];
My output and the expected output for this test case is different , yet my code was submitted successfully.

### Screenshots

![Screenshot 2024-03-04 at 6 14 56 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/96042434/fbf2a7b4-3b0b-4d96-ac97-1feed53576fd)
![Screenshot 2024-03-04 at 6 15 40 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/96042434/fa644ce3-fcb5-4169-bf7c-a64a1b56aae8)

### Additional context

I would like this test case to be included in the test cases.
As you can see though the coustom test case shows out to be wrong my code was submitted successfully.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Hi there,

Your feedback has been instrumental in enhancing the problem. 

To ensure you receive your well-deserved 100 LeetCoins reward, could you kindly provide us with your LeetCode username? This will allow us to credit your account accurately.

Your participation and contributions are valued, and we want to make sure you enjoy the rewards you've earned.

Thank you for being part of the LeetCode community!

Best regards,
LeetCode Team

**Comment by amaltscaria** [comment]
Amal_T_Scaria

This is my leetcode username.

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
