### ISSUE TITLE
Missing Test Case - 191. Number of 1 Bits

### ISSUE THREAD

**Issue by BhupendraMalla** [LeetCode-Feedback/LeetCode-Feedback#20973]
### Category of the bug
- [ ] Problem description
- [x] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [x] Programming language support

### Code used for Submit/Run operation

```
public class Solution {
    public int hammingWeight(int n) {
        int result = 0;

        while (n != 0) {
            int lastBit = n & 1;
            if (lastBit == 1)
                result++;
            n >>>= 1;
        }
        return result;
    }
}

```

**Comment by qingy2019** [comment]
It would be helpful if you could explain what specific problem you have with #191 on Leetcode.

**Comment by BhupendraMalla** [comment]
> It would be helpful if you could explain what specific problem you have with #191 on Leetcode.

actually it's the solution of the leetcode problem #191
