### ISSUE TITLE
Regarding 150. Evaluate Reverse Polish Notation

### ISSUE THREAD

**Issue by dreamofpilot** [LeetCode-Feedback/LeetCode-Feedback#20975]
### LeetCode Username

dreamofpilot55

### Problem number, title, and link

[150. Evaluate Reverse Polish Notation](https://leetcode.com/problems/evaluate-reverse-polish-notation/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

I wonder if there are issues with running JAVA stack pop()?

I'm doing problem 150, and I wrote the below codes:

                int num1 = st.pop();
                int num2 = st.pop();

I'm sure when the code runs to int num2, there are items on the stack, but the leetcode tells me Runtime Error:

java.util.EmptyStackException
  at line 103, java.base/java.util.Stack.peek
  at line 85, java.base/java.util.Stack.pop
  at line 11, Solution.evalRPN
  at line 56, __DriverSolution__.__helper__
  at line 86, __Driver__.main

I copy my code to IDE to run to ensure any issues, but it works well on the IDE. Could you please check that?

### Language used for code

JAVA

### Code used for Submit/Run operation

```
class Solution {
    public int evalRPN(String[] tokens) {
        
        Stack<Integer> st = new Stack<Integer>();

        for(int i=0; i < tokens.length; i++){
            if((tokens[i].equals("+") || tokens[i].equals("-") || tokens[i].equals("*") | tokens[i].equals("/")) == false){
                st.push(Integer.valueOf(tokens[i]));
            } else {
                int num1 = st.pop();
                int num2 = st.pop();
                
                if(tokens[i] == "+"){
                    st.push(num2 + num1);
                } else if(tokens[i] == "-"){
                    st.push(num2 - num1);
                } else if(tokens[i] == "*"){
                    st.push(num2 * num1);
                } else if(tokens[i] == "/"){
                    st.push(num2 / num1);
                }
            }
        }
        return st.peek();
    }
}
```

### Expected behavior

It works on IDE (ex. Apache Netbeans or online JDoodles)

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback. We encourage you to share your questions in the discussion forum, where the community can provide insights and assistance.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
