### ISSUE TITLE
Missing Test Case - 1283. Find the Smallest Divisor Given a Threshold

### ISSUE THREAD

**Issue by jienius** [LeetCode-Feedback/LeetCode-Feedback#2098]
#### Your LeetCode username

jienius

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

The solution of Approach 2 is wrong

#### Code you used for Submit/Run operation

Just submit the Java code of approach 2 in the solution section, it won't pass

#### Language used for code

Java

#### Expected behavior

It should pass

**Comment by lc-kay** [comment]
Hi @jienius 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@jienius Thanks for your post. We are aware of this issue and are working on updating this article within the next few weeks. Thanks :)
