### ISSUE TITLE
LC #2316 : DSU Java editorial solution submission error

### ISSUE THREAD

**Issue by mrbiswajeet** [LeetCode-Feedback/LeetCode-Feedback#20987]
### LeetCode Username
BP69

### Problem number, title, and link
2316. Count Unreachable Pairs of Nodes in an Undirected Graph (https://leetcode.com/problems/count-unreachable-pairs-of-nodes-in-an-undirected-graph/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug
DSU solution throws error on execution
Line 49: error: variable componentSize is already defined in method countPairs(int,int[][]) [in UnionFind.java]
        for (int componentSize : componentSize.values()) {
                 ^

### Language used for code
JAVA

### Code used for Submit/Run operation

```
class UnionFind {
    int[] parent;
    int[] rank;
    public UnionFind(int size) {
        parent = new int[size];
        for (int i = 0; i < size; i++)
            parent[i] = i;
        rank = new int[size];
    }
    public int find(int x) {
        if (parent[x] != x)
            parent[x] = find(parent[x]);
        return parent[x];
    }
    public void union_set(int x, int y) {
        int xset = find(x), yset = find(y);
        if (xset == yset) {
            return;
        } else if (rank[xset] < rank[yset]) {
            parent[xset] = yset;
        } else if (rank[xset] > rank[yset]) {
            parent[yset] = xset;
        } else {
            parent[yset] = xset;
            rank[xset]++;
        }
    }
}

class Solution {
    public long countPairs(int n, int[][] edges) {
        UnionFind dsu = new UnionFind(n);
        for(int[] edge: edges) {
            dsu.union_set(edge[0], edge[1]);
        }

        Map<Integer, Integer> componentSize = new HashMap<>();
        for(int i= 0; i<n; i++) {
            int parent = dsu.find(i);
            if(componentSize.containsKey(parent)) {
                componentSize.put(parent, componentSize.get(parent) + 1);
            } else {
                componentSize.put(parent, 1);
            }
        }
        
        long numberOfPaths = 0;
        long remainingNodes = n;
        for (int size : componentSize.values()) {
            numberOfPaths += size * (remainingNodes - size);
            remainingNodes -= size;
        }
        return numberOfPaths;
    }
}
```

### Expected behavior
The error is occurring because the name componentSize as both the loop variable in the enhanced for loop (for (int componentSize : componentSize.values())) and as a local variable in the same method (Map<Integer, Integer> componentSize = new HashMap<>();).

To resolve this issue, LC should use a different name for the loop variable. For example:
```
for (int size : componentSize.values()) {
    numberOfPaths += size * (remainingNodes - size);
    remainingNodes -= size;
}
```
By changing the loop variable name, you avoid the conflict with the local variable named componentSize.

### Screenshots
NA

### Additional context
NA

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
