### ISSUE TITLE
Missing Test Case - 49. Group Anagrams

### ISSUE THREAD

**Issue by boxi1119** [LeetCode-Feedback/LeetCode-Feedback#2099]
#### Your LeetCode username

bo52

#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language

#### Description of the bug

Missing test case. The test case doesn't cover all the cases. One of the accepted solutions that beats 100% of the java submissions is actually incorrect. 

#### Code you used for Submit/Run operation

```
class Solution {
    public List<List<String>> groupAnagrams(String[] strs) {
        List<List<String>> result = new ArrayList<>();
        Map<Integer, List<String>> map = new HashMap<>();
        
        for(String str: strs){
            
            // take the sum of all values and product of all values and add together basically creating a unique hash
            int sum = 1;
            int total = 0;
            for(int i=0; i < str.length(); i++){
                int intVal = str.charAt(i);
                sum = sum *intVal;
                total = total + intVal;
            }
            sum = sum + total;
            
            if(map.containsKey(sum)){
                map.get(sum).add(str);
            }else{
                List<String> list = new ArrayList<>();
                list.add(str);
                map.put(sum, list);
                result.add(list);
            }
        }
        return result;
    }
}
```

#### Expected behavior

The solution that I posted here was accepted as a correct solution and beats 100% of the java submissions.
However, the way that the solution used to calculate the key is wrong.
The solution treats the following 2 strings as anagrams. 
I have 61 'b' and 49 'z', because the LCM for 98(b) and 122(z) is 5978. 
The multiplication overflows in this case and gets to 0. 
The sum of 61 'b' and 49 'z' are the same.
["bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb","zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"]

**Comment by lc-kay** [comment]
Hi @boxi1119 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @boxi1119 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
