### ISSUE TITLE
Counting Elements

### ISSUE THREAD

**Issue by habcerga1** [LeetCode-Feedback/LeetCode-Feedback#210]
**What kind of the bug**
- [x] problem
- [x] solution
- [ ] language

**Describe the bug**
Incorrect description of the task or an error in the test example or 
I did not understand the conditions of the problem.

**what language is your code written in**
C#

**The code you submit/run**
```
IList<int> list = new List<int>();
            IList<int> indexNumbers = new List<int>();
            for (int i = 0; i < arr.Length-1; i++)
            {
                int num1 = arr[i]+1;
                int num2 = arr[i];
                for (int j = i+1; j < arr.Length; j++)
                {
                    if (num1 == arr[j] | (num2-1 == arr[j] & !indexNumbers.Contains(j)))
                    {
                        list.Add(arr[j]);
                        indexNumbers.Add(j);
                    }
                }
            }
            return list.Count;
```

**Expected behavior**
In the problem statement output should be 4 but expected 2.
Input [1,1,2,2] Output 4 Expected 2 Testcase № 12.

**Screenshots**

**Additional context**
https://leetcode.com/explore/other/card/30-day-leetcoding-challenge/528/week-1/3289/

**Comment by CooperCooperCooper** [comment]
Hi @habcerga1,
Thank you for reaching out to us. I've relayed your issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @habcerga1,
Thank you for your time. Our team found this issue to be a system issue and not a content issue. It's currently under investigation so we can fix it soon. If you would like more updates on this issue, please redirect this issue to our main support channel "support@leetcode.com". We appreciate your time and support.

**Comment by CooperCooperCooper** [comment]
Hi @habcerga1,
My apologies. The issue that was fixed was a separate error that occurred earlier today. We're still investigating this issue.

**Comment by CooperCooperCooper** [comment]
Hi @habcerga1,
Thank you for your time. Our team took a thorough look at your submission. It seemed like your code was receiving Compile Error because it didn't contain the superclass needed to run, it only give the method. Please update your code accordingly.
