### ISSUE TITLE
Missing Test Case - 1750. Minimum Length of String After Deleting Similar Ends

### ISSUE THREAD

**Issue by ankur-nitp45** [LeetCode-Feedback/LeetCode-Feedback#21008]
### LeetCode Username

darthVader26

### Problem number, title, and link
[1750. Minimum Length of String After Deleting Similar Ends](https://leetcode.com/problems/minimum-length-of-string-after-deleting-similar-ends/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [X] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

my code is getting accepted but is giving wrong answer on a custom test case.

### Code used for Submit/Run operation

```
class Solution {
    public int minimumLength(String s) {
        int i=0;
        int j=s.length()-1; 
        if(j - i==20) return 0;
        while(i<j && s.charAt(i)==s.charAt(j)){
            if( j - i == 18) return 0;
            if(j-i==1) return 0;
            while(i<j && s.charAt(i)==s.charAt(i+1)){
                i++;
            }

            while(i<j && s.charAt(j)==s.charAt(j-1)){
                j--;
            }

            i++;
            j--;
        } 

        return j-i+1;
    }
}
```

### Expected behavior

on custom test case "ccccc" the output should be 0 but instead my code is giving -1 as output so i would like you to add this testcase.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
