### ISSUE TITLE
Missing Test Case - 362. Design Hit Counter

### ISSUE THREAD

**Issue by saurabhrpi** [LeetCode-Feedback/LeetCode-Feedback#21003]
### LeetCode Username
[sharcodes](https://leetcode.com/sharcodes)

### Problem number, title, and link
362 : Design Hit Counter
[362](https://leetcode.com/problems/design-hit-counter/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

System is accepting solution for the attached submitted code even when it fails the mentioned test case. The test case is failed by the system only for the same code. Still when one removes the test case, the code is successfully submitted.

### Language used for code

Java

### Code used for Submit/Run operation

```
class HitCounter {
    List<Integer> list;
    public HitCounter() {
        list = new ArrayList<>();
    }
    
    public void hit(int timestamp) {
        list.add(timestamp);
    }
    
    public int getHits(int timestamp) {
        if(timestamp <= 300)
            return list.size();
        int low = 0, high = list.size() - 1;
        int target = timestamp - 300;
        while(low <= high)
        {
            int mid = low + ((high - low) >> 1);
            if(list.get(mid) == target)
                return list.size() - mid - 1;
            if(list.get(mid) < target)
                low = mid + 1;
            else
                high = mid - 1;
        }
        return list.size() - low;
    }
}

/**
 * Your HitCounter object will be instantiated and called as such:
 * HitCounter obj = new HitCounter();
 * obj.hit(timestamp);
 * int param_2 = obj.getHits(timestamp);
 */
```

### Expected behavior

It should have returned below output for the given test case:
Test case: 
["HitCounter","hit","hit","hit","hit","hit","hit","hit","hit","hit","getHits","getHits"]
[[],[7],[33],[141],[141],[141],[141],[141],[141],[141],[302],[441]]

Output:
[null,null,null,null,null,null,null,null,null,null,9,4]

Expected:
[null,null,null,null,null,null,null,null,null,null,9,0]

### Screenshots
<img width="1419" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/5567414/bd4069f7-9c45-4ad1-9ec2-45bf08e65ad0">

### Additional context
Below is the link to my incorrect code being accepted as the correct solution:
https://leetcode.com/problems/design-hit-counter/submissions/1194197233/

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team
