### ISSUE TITLE
270. Closest Binary Search Tree Value - submitted solution doesn't work but works in the console

### ISSUE THREAD

**Issue by tjeenal** [LeetCode-Feedback/LeetCode-Feedback#21006]
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

if I test the code in console with this test case, it passes the test but if I submit it, it doesn't pass the test.
<img width="1426" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/65047951/dfa8685b-c4df-454e-b7ce-4e46b989b824">

### Language used for code

Python3

### Code used for Submit/Run operation

```
# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
class Solution:
    def closestValue(self, root: Optional[TreeNode], target: float) -> int:
        def helperDFS(root: Optional[TreeNode], minDiff: int):
            global closest
            if root:
                currDiff = abs(root.val - target)
                if currDiff < minDiff:
                    minDiff = currDiff
                    closest = root.val
                if root.val > target:
                    helperDFS(root.left, minDiff)
                else:
                    helperDFS(root.right, minDiff)
        helperDFS(root, target)
        return closest
```

### Expected behavior

It should either pass or fail in both console and submission.

### Additional context

similar to this bug: https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/14733

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
