### ISSUE TITLE
Missing Test Case - 1750. Minimum Length of String After Deleting Similar Ends

### ISSUE THREAD

**Issue by Abulhassan8** [LeetCode-Feedback/LeetCode-Feedback#21005]
### Category of the bug
[This ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

The accepted solution misses some edge cases. 
For eg: "cabaaabac" This case should return 1, but the accepted solution returns 0.

### Code used for Submit/Run operation

```
int i = 0, j = s.length() - 1;

        while(i < j){
            char c = s.charAt(i);

            if(s.charAt(j) != c) break;

            while(i < s.length() && s.charAt(i) == c) i++;
            while(j >= 0 && s.charAt(j) == c) j--;
        }

        if(j < i) return 0;

        return j - i + 1;
```

### Expected behavior

The code above returns 0 for the case "cabaaabac", 
But it should return 1 ideally after removing prefix = "caba" and suffix = "abac".

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
