### ISSUE TITLE
Incorrect editorial - 1750. Minimum Length of String After Deleting Similar Ends

### ISSUE THREAD

**Issue by hnguyen111** [LeetCode-Feedback/LeetCode-Feedback#21004]
### LeetCode Username
hnguyenle

### Problem number, title, and link

1750. Minimum Length of String After Deleting Similar Ends https://leetcode.com/problems/minimum-length-of-string-after-deleting-similar-ends/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug

In the the "Intuition" part of Approach 1 (Two Pointers),
> To calculate the number of remaining characters, we can subtract begin from end; then we add 1, because the string is 0-indexed.

The fact that the string is 0-indexed does not affect the calculation of the number of characters.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
