### ISSUE TITLE
Missing Test Case - 948. Bag of Tokens

### ISSUE THREAD

**Issue by P76071226** [LeetCode-Feedback/LeetCode-Feedback#21010]
### LeetCode Username

kai_syun

### Problem number, title, and link

[948. Bag of Tokens](https://leetcode.com/problems/bag-of-tokens/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Missing test case when the power can cover all tokens without "face-down"

In my original submission, it can pass without the boundary check.
However, when I use customized test cases with power greater than the sum of tokens, it fails by error index out of range.

### Language used for code

Python

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.

# below code can pass the test system but raise an error in test case like tokens=[100,200,300,400], power=2200
class Solution:
    def bagOfTokensScore(self, tokens: List[int], power: int) -> int:
        if not tokens: return 0
        if len(tokens) == 1: return 1 if power >= tokens[0] else 0
        if min(tokens) > power:
            return 0
        tokens.sort()
        left, right = 0, len(tokens)-1
        max_score = 0
        cur_score = 0
        while left <= right:
            while tokens[left] <= power:
                power -= tokens[left]
                cur_score += 1
                max_score = max(max_score, cur_score)
                left += 1
            cur_score -= 1
            power += tokens[right]
            right -= 1
        return max_score   
```

### Expected behavior

The test system should cover the kind of test case - when the power can cover all tokens without "face-down"

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
