### ISSUE TITLE
移除元素 题目中输出不一致的问题

### ISSUE THREAD

**Issue by seth-shi** [LeetCode-Feedback/LeetCode-Feedback#2101]
**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
[移除元素](https://leetcode-cn.com/leetbook/read/all-about-array/x9p1iv/)
某个测试用例如下:
```
输入
[0,1,2,2,3,0,4,2]
2
输出
[0,1,4]
预期结果
[0,1,4,0,3]
```

**你使用的语言**
Golang

**你提交或者运行的代码**
```
func removeElement(nums []int, val int) int {

	lastNum := len(nums)-1
	count := 0
	for i := 0; i < lastNum; i ++ {

		if nums[i] == val {
			nums[i], nums[lastNum] = nums[lastNum], nums[i]
			i --
			lastNum --
			count ++
		}
	}

	return count
}
```

**期望行为**
我本地用过编辑器也用过在线编辑器, 得到结果是和你们的预期是一样的.
![image](https://user-images.githubusercontent.com/28035971/105465376-c9493000-5ccd-11eb-9c1c-848cf3f340e6.png)

**屏幕截图**
![image](https://user-images.githubusercontent.com/28035971/105465150-8ab37580-5ccd-11eb-837a-1a1d3843ce17.png)

**额外的上下文**
无

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好， 题目中要求返回移除后数组的新长度”， 所有需要 return len(nums) - count 。
