### ISSUE TITLE
Missing Test Case - 1750. Minimum Length of String After Deleting Similar Ends

### ISSUE THREAD

**Issue by JavierMakmuri** [LeetCode-Feedback/LeetCode-Feedback#21013]
### LeetCode Username

MaierMarvelous 

### Problem number, title, and link

1750. Minimum Length of String After Deleting Similar Ends https://leetcode.com/problems/minimum-length-of-string-after-deleting-similar-ends/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

When input is "aaa" code should output 0 but outputs 1 

### Language used for code

Python

### Code used for Submit/Run operation

```
class Solution:
    def minimumLength(self, s: str) -> int:
        i, j = 0, len(s)-1

        while i < j and s[i] == s[j]:
            i += 1
            j -= 1

            while i+1 < j and s[i] == s[i-1]:
                i += 1

            while j-1 > i and s[j] == s[j+1]:
                j -= 1
                
        return j-i+1 if i <= j else 0
```

### Expected behavior

Code should output 0 but outputs 1

### Screenshots

Code run on test case:
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/71958560/60263a49-33e3-49c6-92b8-d1409a30e1ca)

Submission below should've been rejected:
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/71958560/8317fd42-a267-4582-93e0-93c068d8de4a)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
