### ISSUE TITLE
Missing Test Case - 237. Delete Node in a Linked List

### ISSUE THREAD

**Issue by Valentin-B** [LeetCode-Feedback/LeetCode-Feedback#21036]
### LeetCode Username

Val_B

### Problem number, title, and link

Delete Node in a Linked List
https://leetcode.com/explore/interview/card/top-interview-questions-easy/93/linked-list/553/

### Category of the bug
- [x] Problem description
- [x] Solved examples
- [x] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The exercice indicate that a specific *node* should be removed from the singly-linked list called *head*.
However only the *node* parameter is passed to the function

### Language used for code

C
C++
C#

### Code used for Submit/Run operation

``` C#
public class Solution {
    public void DeleteNode(ListNode node) {
        
        ListNode currentNode = node;
        while(currentNode != null)
        {
            Console.Write("{0} ,",currentNode.val);
            currentNode = currentNode.next;
        }
    }
}
```

### Expected behavior

Given that the node to remove is already given we need to have access to the root node of the list

### Screenshots

![LeetCode](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/14337225/277b93a4-793b-4b5c-906c-f8890d933f3c)

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
