### ISSUE TITLE
Missing Test Case - 16. 3Sum Closest

### ISSUE THREAD

**Issue by TomasWilli** [LeetCode-Feedback/LeetCode-Feedback#21043]
题目problem：https://leetcode.cn/problems/3sum-closest/
描述description：我的代码可以通过提交测试但是无法通过我添加的这个例子。My code can past the test but this one.
例子missing test case：
nums=[-1000,-5,-5,-5,-5,-5,-5,-1,-1,-1]
target=-8

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ Y] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
class Solution {
public:
    int threeSumClosest(vector<int>& nums, int target) {
        sort(nums.begin(),nums.end());
        int n=nums.size();
        int res=nums[0]+nums[1]+nums[2];
        if(res>=target)
        return res;
        int sum2=nums[n-1]+nums[n-2]+nums[n-3];
        if(sum2<=target)
        return sum2;
        for(int i=0;i<n-2;i++){
            if(i>0&&nums[i]==nums[i-1]){
                continue;
            }
            int left=i+1,right=n-1,sum=0;
            while(left<right){
                while(left<right-2&&nums[right-1]==nums[right]){
                    right--;
                }
                while(left<right-2&&nums[left+1]==nums[left]){
                    left++;
                }
                sum=nums[i]+nums[left]+nums[right];
                if(sum==target)
                return sum;
                else if(sum>target){
                    right--;
                }else {
                    left++;
                }
                res=abs(res-target)>abs(sum-target)?sum:res;
                
            }
        }
        return res;
    }
};
// above and below the code.
```

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team

**Comment by amcones** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。
