### ISSUE TITLE
Missing Test Case - 1657. Determine if Two Strings Are Close

### ISSUE THREAD

**Issue by jizhenz** [LeetCode-Feedback/LeetCode-Feedback#2104]
#### Your LeetCode username
jizhenzhao

#### Category of the bug
- [ ] Question
- [x] Solution
- [x] Language

#### Description of the bug
A solution that is wrong passed all the tests

#### Code you used for Submit/Run operation

```
class Solution:
    def closeStrings(self, word1: str, word2: str) -> bool:
        c1, c2 = Counter(word1), Counter(word2)
        k1, k2, v1, v2 = set(c1.keys()), set(c2.keys()), set(list(c1.values())), set(list(c2.values()))
        return k1 == k2 and v1 == v2
```

#### Language used for code
Python

#### Expected behavior
The below test case should return False:
"aabbcccddd"
"cccbbaaaddd"
But the solution I submitted above returns True

#### Additional context
Need to add one more test case:
"aabbcccddd"
"cccbbaaaddd"
Return: False

**Comment by lc-kay** [comment]
Hi @jizhenz 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @jizhenz 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
