### ISSUE TITLE
Compiler returns the different result

### ISSUE THREAD

**Issue by jeonbik** [LeetCode-Feedback/LeetCode-Feedback#21058]
### LeetCode Username
[user3708cO](https://leetcode.com/user3708cO)

### Problem number, title, and link

[1481. Least Number of Unique Integers after K Removals](https://leetcode.com/problems/least-number-of-unique-integers-after-k-removals/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The output of the computer is wrong. I ran the code locally multiple times and I get the same result, 3 in this case. However, when I submit the code the compiler throws an error with `Output = 4` `Expected. = 3`. I am confident that my code returns the right result but the compiler prints the different result.

### Language used for code

Python

### Code used for Submit/Run operation

```
from collections import Counter
class Solution(object):
    def findLeastNumOfUniqueInts(self, arr, k):
        """
        :type arr: List[int]
        :type k: int
        :rtype: int
        """
        array_dict = Counter(arr)
        array_dict = dict(sorted(array_dict.items(), key=lambda item: item[1]))
        ans_ = []
        for key,v in array_dict.items():
            for i in range(v):
                ans_.append(key)
        return len(set(ans_[k:]))
```

### Expected behavior

The compiler was supposed to return `3`.

### Screenshots

![Screenshot 2024-03-06 at 10 14 00 AM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/36014522/dc24e7d4-6382-407f-a25e-1c22079379c5)
![Screenshot 2024-03-06 at 10 14 30 AM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/36014522/cfb54eff-1099-44c5-b0b7-841a3ecbcaee)

**Comment by LC-Pam** [comment]
Thank you for getting back to us! Regrettably, troubleshooting the variance between your local Integrated Development Environment (IDE) and the LeetCode environment poses a challenge for us.

In such cases, we recommend raising this issue as a discussion post in the problem's discussion section. This allows you to tap into the collective knowledge and experiences of our user community. Many users may have encountered similar challenges and could offer insights or solutions that can be valuable in resolving the discrepancy.

At LeetCode, we foster a collaborative learning environment, and we believe in the power of users to help each other to enhance their learning experience. Debugging and learning from the process are integral parts of the coding journey, and the community's diverse perspectives can be immensely beneficial.

We appreciate your understanding, and if you have any more questions or need further assistance, please feel free to let us know. Your time and support are highly valued.

Best regards,
The LeetCode Team
