### ISSUE TITLE
Missing Test Case - 1777. Determine if Two Strings Are Close

### ISSUE THREAD

**Issue by larrygao2000** [LeetCode-Feedback/LeetCode-Feedback#2105]
#### Your LeetCode username
larrygao2000

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language

#### Description of the bug

Missing test case

#### Code you used for Submit/Run operation

```
class Solution {
    // This will not work for the following case
    // word1: "aaaabbbbb"
    // word2: "aaaaaabbbbbbb"
    // But it will be accepted as a solution
    public boolean closeStrings(String word1, String word2) {
        
        int[] count1=new int[27], count2=new int[27];
        for(char x : word1.toCharArray())
            count1[x-'a']++;
        
        for(char x: word2.toCharArray())
            count2[x-'a']++;
        
        int res=0;
        
        for(int i=0;i<27;i++){
            if((count1[i]==0 && count2[i]!=0) || (count2[i]==0 && count1[i]!=0))
                return false;
            res^=count1[i];
            res^=count2[i];
        }

        return res==0;
    }    
}
```

#### Language used for code
Java

#### Expected behavior

The above solution should fail but it is accepted as a solution.

Time Submitted | Status | Runtime | Memory | Language
-- | -- | -- | -- | --
01/22/2021 10:41 | Accepted | 12 ms | 39.6 MB | java

It assumes members of two arrays are equal if all members XOR to 0. 

4 ^ 5 ^ 6 ^ 7 will be 0 as well.

So it will fail test case like:
"aaaabbbbb"
"aaaaaabbbbbbb"

It will also fail cases like this:
"aabb"
"ab"

**Comment by lc-kay** [comment]
Hi @larrygao2000 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@larrygao2000 We've recently added other test cases, which the solution provided fails. Therefore, we will not be adding your test case. We appreciate your support.
