### ISSUE TITLE
Missing Test Case - 665. Non-decreasing Array

### ISSUE THREAD

**Issue by DoubleA-DA** [LeetCode-Feedback/LeetCode-Feedback#2106]
#### Category of the bug
-  Question
- [ ] Solution
- [ ] Language

#### Description of the bug

[-51,-58,-49,-48] when I give this as a test case it fails, but my code passes all the other test cases and it gets accepted.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool checkPossibility(vector<int>& nums) {
        //int mn=*min_element(nums.begin(),nums.end());
            if(nums.size()==1)return true;
        int x=0,i;
        for(i=0;i<nums.size()-1;i++)
        {
           if(nums[i]>0)
            {
                if(nums[i]>nums[i+1])
             {
                x=nums[i+1];
                 nums.erase(nums.begin()+i+1);
                  if(is_sorted(nums.begin(),nums.end()))return true;
                    nums.insert(nums.begin()+i+1,x);
                x=nums[i];
                nums.erase(nums.begin()+i);
                 if(is_sorted(nums.begin(),nums.end()))return true;
                else return false;
             }
            }
              if(nums[i]<0)
            {
                if(nums[i]>nums[i+1])return false;
            }
            
        }
            return true;
    }
};
```

#### Language used for code
C++

#### Expected behavior
 
If my code was right it should return true but it returns false

#### Screenshots

![ Code Screenshot from my gdrive](https://drive.google.com/uc?export=view&id=1g42IVS_E8v45AYamTj5pFljX_ssDmoFB)

**Comment by lc-kay** [comment]
Hi @DoubleA-DA 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @DoubleA-DA 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by DoubleA-DA** [comment]
@lc-kay my leetcode ID is motralk (https://leetcode.com/motralk/)
