### ISSUE TITLE
Missing Test Case - 27. Remove Element

### ISSUE THREAD

**Issue by YanKovalskiy** [LeetCode-Feedback/LeetCode-Feedback#21079]
### LeetCode Username
vyankovskiy

### Problem number, title, and link
27. Remove Element
https://leetcode.com/problems/remove-element

### Category of the bug
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### Description of the bug
The code solves the problem correctly. I checked it IDE PyCharm. However, the test cases do not pass.

### Code used for Submit/Run operation
```
class Solution:
    def removeElement(self, nums: List[int], val: int) -> int:
        count = len(nums)
        nums = list([x for x in nums if x != val])
        return count - len(nums)
```

### Expected behavior
Test pass.

### Additional context
![SCR_27](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/139558095/38c21924-0013-443a-993c-08c1f68aa0f5)

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team
