### ISSUE TITLE
Missing Test Case - 1777. Determine if Two Strings Are Close

### ISSUE THREAD

**Issue by davemoedee** [LeetCode-Feedback/LeetCode-Feedback#2107]
#### Your LeetCode username

djmo

#### Category of the bug
- [ ] Question
- [ x] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
class Solution:
    def closeStrings(self, word1: str, word2: str) -> bool:

        if len(word1) != len(word2):
            return False
        
        chrs1 = Counter(word1)
        chrs2 = Counter(word2)

        return (chrs1.keys() == chrs2.keys()) and (set(chrs1.values()) == set(chrs2.values()))   
```

#### Expected behavior

This code should fail submission, but it passes.

The following test case is currently missing:

"aaaaabbbcccccefghiijj"
"aaabbbccccceeffgghiij"

This should be False, but my code that passes says True. 'Run Code' catches this wrong answer.

#### Additional context

The following test case is currently missing:

"aaaaabbbcccccefghiijj"
"aaabbbccccceeffgghiij"

This should be False, but my code that passes says True. 'Run Code' catches this wrong answer.

This test case considers where set(word1) == set(word2) and set(letterfrequencies(word1)) == set(letterfrequencies(word2)), but letterfrequencies(word1).sort() != letterfrequencies(word2).sort(). If the frequencies match, this should work.

This is testing the fact that we can swap frequencies between any 2 letters with op2, but we cannot increase the occurrences of a frequency.

**Comment by davemoedee** [comment]
To clarify, there is no test case currently that checks to make sure the frequencies of the frequencies match. It is enough to have code that checks that the set of letters is the same and the set of letter frequencies is the same, ignoring the frequencies of the frequencies.

**Comment by lc-kay** [comment]
Hi @davemoedee 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @davemoedee 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
