### ISSUE TITLE
Wrong Testcase for Que 513. Find Bottom Left Tree Value

### ISSUE THREAD

**Issue by rmn-k** [LeetCode-Feedback/LeetCode-Feedback#21076]
When input is [ 50, 25, 75, 2, null, 55, null, null, 5, null, 59, 4, 6, 58, null, null, null, null, 7, 57, null ]
The tree formed has two nodes in the last level: 57 and 7.
Out of the two, 57 is to the left of 7.
So, the answer should be 57
But the Testcase expects 7 as answer.
(If we consider horizontal distance(hd) of root as 0, hd of 7 comes out to be +1 and hd of 57 comes out to be -1)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.


Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by stormsunshine** [comment]
The complete binary tree for the test case is as follows.

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/12067364/970c8d02-af6d-4137-9b40-d107428233ba)

It can be seen from the image that 7 is to the left of 57. Why do you think 57 is to the left of 7?

**Comment by rmn-k** [comment]
The image shared in previous message doesn't take into account the horizontal distance of nodes in the Binary tree (a concept used to solve problems like bottom view, top view of a binary tree).
See the image: https://drive.proton.me/urls/J47FRA1FAG#f0Lq8upYJ2ak
If we form Binary tree like the shared image, 57 comes to the left of 7.
[Also attaching the image, in case the link doesn't work]

**Comment by rmn-k** [comment]
One node was missing from the image I just shared.
Here is the corrected image: https://drive.proton.me/urls/AJDNDXXDQW#VaFTSYFkuB5u

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
