### ISSUE TITLE
Missing Test Case - 27. Remove Element

### ISSUE THREAD

**Issue by barigozzim-prom** [LeetCode-Feedback/LeetCode-Feedback#21082]
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ X] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

the code in python3
class Solution:
    def removeElement(self, nums: List[int], val: int) -> int:
        nums2 = nums[:]
        k=0
        for i in range(len(nums2)):
            if nums2[i] == val:
                nums.pop(i-k)
                k = k+1
                print(i, nums)
        print(nums)
        return k

for the case nums = [0,1,2,2,3,0,4,2]
prints value of nums equal to [0, 1, 3, 0, 4], but the test result says the output is [0,1,3]

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.


Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team
