### ISSUE TITLE
Missing Test Case for 1657. Determine if Two Strings Are Close

### ISSUE THREAD

**Issue by yuhan-wang** [LeetCode-Feedback/LeetCode-Feedback#2108]
#### Your LeetCode username

yuhan-wang

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Wrong solution is accepted for the test case:
word1 = "aaaaabb"
word2 = "aaaaaab"

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool closeStrings(const string& word1, const string& word2) {
        if (size(word1) != size(word2)) return false;

        array<int, 26> word1_c = {0};
        for (auto c : word1) ++word1_c[c - 'a'];

        array<int, 26> word2_c = {0};
        for (auto c : word2) ++word2_c[c - 'a'];

        auto value = 0;
        for (int i = 0; i < 26; ++i) {
            if (word1_c[i] > 0) {
                if (word2_c[i] == 0) return false;
                value ^= word1_c[i];
                value ^= word2_c[i];
            }
        }

        return value == 0;
    }
};
```

#### Language used for code

C++

#### Expected behavior

For the above test case, expected outcome is False, the solution returns True.

#### Additional context

Submission link: https://leetcode.com/submissions/detail/446397798/

**Comment by lc-kay** [comment]
Hi @yuhan-wang 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@yuhan-wang After adding other test cases, this solution already fail on those. Therefore, we will not be adding this test case. We appreciate your support.
