### ISSUE TITLE
Missing Test Case - 274. H-Index

### ISSUE THREAD

**Issue by RollingSnack** [LeetCode-Feedback/LeetCode-Feedback#21080]
### LeetCode Username
RollingSnack

### Problem number, title, and link
274. H-Index https://leetcode.com/problems/h-index/

### Category of the bug
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug
Solutions that do not satisfy edge conditions in constraints can still pass.

### Language used for code
Python3

### Code used for Submit/Run operation
```python
class Solution:
    def hIndex(self, citations: List[int]) -> int:
        papers = [0 for _ in range(1000)]
        for citation in citations:
            papers[citation] += 1
        count = 0
        for index in range(999, -1, -1):
            count += papers[index]
            if count >= index:
                return index
```

### Expected behavior
There is a constraint that `0 <= citations[i] <= 1000`.
I mistakenly used an array `papers` of length `1000` to record the number of occurrences of `0` to `999` in `citations`. Once there is a `citations[i] = 1000`, it should throw an exception for the out-of-range index. But it passed.

### Screenshots
- This testcase `citations = [0,2,1000]` makes it fail:
![My Testcase](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/22791898/aa5c9207-b759-4be8-b645-7f16a8125605)
- While this solution was mistakenly accepted:
![Passed Solution](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/22791898/a2b801be-f033-4e67-9f03-a192270a3477)

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
