### ISSUE TITLE
Missing Test Case - 1174. Immediate Food Delivery II

### ISSUE THREAD

**Issue by Joshua-Immanuel** [LeetCode-Feedback/LeetCode-Feedback#21088]
### LeetCode Username

Joshua__Immanuel

### Problem number, title, and link

1.  Immediate Food Delivery II https://leetcode.com/problems/immediate-food-delivery-ii

### Category of the bug
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

This is an example test case created by me and a valid one as per question this case handles where there are multiple same order date. 
| delivery_id | customer_id | order_date | customer_pref_delivery_date |
| ----------- | ----------- | ---------- | --------------------------- |
| 1           | 1           | 2019-08-01 | 2019-08-02                  |
| 2           | 2           | 2019-08-02 | 2019-08-02                  |
| 3           | 1           | 2019-08-11 | 2019-08-12                  |
| 4           | 3           | 2019-08-24 | 2019-08-24                  |
| 5           | 3           | 2019-08-21 | 2019-08-22                  |
| 6           | 2           | 2019-08-11 | 2019-08-13                  |
| 7           | 4           | 2019-08-09 | 2019-08-09                  |
| 8           | 4           | 2019-08-09 | 2019-08-11                  |

### Language used for code

MySQL

### Code used for Submit/Run operation

```
# Write your MySQL query statement below
Select 
    round(avg(order_date = customer_pref_delivery_date)*100, 2) as immediate_percentage
from Delivery
where (customer_id, order_date) in (
  Select customer_id, min(order_date) 
  from Delivery
  group by customer_id
);
```

### Expected behavior

The expected result should be 50 but using the above code I get 40 for the mentioned test case which is wrong but it got accepted which implies this test case should be added to prevent from happening again.

### Screenshots

<img width="1440" alt="Screenshot 2024-03-07 at 8 55 54 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/76649843/2ac2383b-5d01-4467-bc85-9193b07760c1">
![Screenshot 2024-03-07 at 8 55 54 PM (2)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/76649843/c9ce2052-fdcd-4222-a897-fb94ed502dd5)

### Additional context

The correct code should be:
'''
Select 
    round(sum(case when order_date=customer_pref_delivery_date then 1 else 0 end)*100/(select count(distinct customer_id) from Delivery),2) as immediate_percentage
from Delivery
where (customer_id, order_date) in (
  Select customer_id, min(order_date) 
  from Delivery
  group by customer_id
);
'''

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
