### ISSUE TITLE
Test case passes while running but fails in submission

### ISSUE THREAD

**Issue by JaimugilC** [LeetCode-Feedback/LeetCode-Feedback#21090]
### LeetCode Username
Jaimugil

### Problem number, title, and link
49. Group Anagrams https://leetcode.com/problems/group-anagrams/

### Category of the bug
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### Description of the bug

My code is getting accepted on test run. But it fails on submit for the same test case

### Language used for code

C++

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
class Solution {

public:
    string createSignature(string str){
        int arr[26];

        for(int i=0; i<str.size(); i++){
            arr[str[i] - 'a']++;
        }

        stringstream ss;

        for(int i=0; i<26; i++){
            if(arr[i] != 0)
            ss << (char)('a'+i) << arr[i];
        }

        return ss.str();
    }

public:
    vector<vector<string>> groupAnagrams(vector<string>& strs) {
        unordered_map<string, vector<string>> mp;
        vector<vector<string>> res;

        for(auto x : strs){
           mp[createSignature(x)].push_back(x);
        }

        for(auto i=mp.begin(); i!=mp.end(); i++){
            res.push_back(i->second);
        }
        
        return res;
    }
};
```

### Expected behavior

If it is accepted in the test run then it should have passed the same test on submission

### Screenshots

<img width="1440" alt="Screenshot 2024-03-07 at 9 06 27 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/84342958/13bef423-a528-4341-9de3-ed03f00cddba">

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us!

When comparing the outcomes of "Run Code" and "Submit" for a specific test case, it's evident that the input and expected values are the same, yet the output values differ.

To assist you further, we have documented the causes and potential solutions for this type of issue in detail. You can find this information in our knowledge base article: [Test Case Discrepancy - Causes and Solutions](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-).

I hope this resource proves helpful. Should you have any additional questions or need further clarification on this case, please do not hesitate to reach out to us. We're here to assist you!

Best regards,
LeetCode Support Team
