### ISSUE TITLE
Missing Test Case-2834. Find the Minimum Possible Sum of a Beautiful Array

### ISSUE THREAD

**Issue by Pius-Z** [LeetCode-Feedback/LeetCode-Feedback#21095]
### LeetCode Username
piusz

### Problem number, title, and link
2834.Find the Minimum Possible Sum of a Beautiful Array https://leetcode.cn/problems/find-the-minimum-possible-sum-of-a-beautiful-array/description/

### Category of the bug
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug
When solving using the formula method and $target / 2 >= n$, overflow may occur during calculation, but the existing test cases do not cover this situation, so my error code can pass without handling the overflow.

Example test case : n = 100000000, target = 1000000000.

### Language used for code
Java

### Code used for Submit/Run operation
```
class Solution {
    public int minimumPossibleSum(int n, int target) {
        long res = 0L;
        int mod = 1000_000_007;

        int split = target / 2;

        if (split >= n) {
            // Where the problem occurs
            res = (1 + n) * n / 2;
        } else {
            res = 1L * (1 + split) * split / 2 + (0L + target + target + n - split - 1) * (n - split) / 2;
        }

        return (int)(res % mod);
    }
}
```

### Expected behavior
Example test case : n = 100000000, target = 1000000000.
This error code can pass all existing test cases, but cannot pass the above test case.

### Additional context
https://leetcode.cn/problems/find-the-minimum-possible-sum-of-a-beautiful-array/submissions/509114073/

**Comment by LC-Pam** [comment]
Hi there,

Your feedback has been instrumental in enhancing the problem. 

To ensure you receive your well-deserved 100 LeetCoins reward, could you kindly provide us with your LeetCode username? This will allow us to credit your account accurately.

Your participation and contributions are valued, and we want to make sure you enjoy the rewards you've earned.

Thank you for being part of the LeetCode community!

Best regards,
LeetCode Team

**Comment by Pius-Z** [comment]
Thank you.
I use LeetCode China, and my username is piusz. It doesn't matter if you can't find the account, thank you but no need to spend energy on this matter.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your reply, we will ask CN team to provide 100 rewards to your CN account.

Thank you~

LC_Pam
