### ISSUE TITLE
847. Shortest Path Visiting All Nodes - Missing Test Cases

### ISSUE THREAD

**Issue by satzhan** [LeetCode-Feedback/LeetCode-Feedback#21093]
### LeetCode Username
Satj

### Problem number, title, and link
[847. Shortest Path Visiting All Nodes](https://leetcode.com/problems/shortest-path-visiting-all-nodes)

### Category of the bug
- [X] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug
Suggesting add all these testcases as the sizes of graphs here are different for each testcase below.

Missing this test case:
[[1],[0,2],[1,3,4,6],[2,7,8],[2,5],[4,10],[2],[3,9,11],[3],[7],[5],[7]]

and this test case:
[[1,4],[0,2,3],[1,5,7],[1,8],[0],[2,6],[5],[2],[3,9],[8]]

and this test case:
[[1,2],[0,3,4],[0],[1,5],[1,7],[3,6],[5],[4,8],[7]]

### Language used for code
C++

### Code used for Submit/Run operation

```
class Solution {
public:
    int shortestPathLength(vector<vector<int>>& g) {
        vector<unordered_map<int, int>> v(g.size());
        int ans = INT_MAX, i = 0;
        for (; i < g.size(); ++i) ans = min(ans, dfs(g, v, i, 0));
        return ans;
    }
    int dfs(vector<vector<int>>& g, vector<unordered_map<int, int>>& v,
                int node, int cv){
        if ((cv | (1 << node)) == (1 << g.size()) - 1) return 0;
        if (v[node].find(cv) != v[node].end()) return v[node][cv];
        v[node][cv] = INT_MAX - 1;
        for (auto& e : g[node])
            v[node][cv] = min(v[node][cv], 1 + dfs(g, v, e, cv | (1 << node)));
        return v[node][cv];
    }
};
```

### Expected behavior
I mean it passes all current test cases, but it should generally fail as it misses important idea that DFS in this form doesn't work. I am attaching a screenshot where I checked these 3 testcase and it failed and then just submitted, but it passed anyway.

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/46739227/1c6a1dd9-ad6c-41de-b409-623ceb0a20a0)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
