### ISSUE TITLE
Incorrect Calculation of Time

### ISSUE THREAD

**Issue by SamZhangQingChuan** [LeetCode-Feedback/LeetCode-Feedback#211]
**What kind of the bug**
- [ ] problem
- [ ] solution
- [ ] language
- [x] system

**Describe the bug**
Incorrect calculation of time used.

**Screenshots**

<img width="1166" alt="Screen Shot 2020-04-29 at 23 39 44" src="https://user-images.githubusercontent.com/8025859/80592046-e02a6100-8a72-11ea-95b1-ccb8672ce50d.png">

From weekly contest 186

**Comment by CooperCooperCooper** [comment]
Hi @SamZhangQingChuan,
Thank you for reaching out to us. Since this channel is for problem and solutions content issue, please relay this contest issue to our main support channel "support@leetcode.com". We appreciate your support and understanding.
