### ISSUE TITLE
Missing Test Case - 1657. Determine if Two Strings Are Close

### ISSUE THREAD

**Issue by shengbo-ma** [LeetCode-Feedback/LeetCode-Feedback#2110]
#### Your LeetCode username

OysterMax

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Missing Test Case.
I submitted a wrong answer but it got accepted.

#### Code you used for Submit/Run operation

```
# 1657. Determine if Two Strings Are Close
class Solution:
    def closeStrings(self, word1: str, word2: str) -> bool:
        cnt1, cnt2 = Counter(word1), Counter(word2)
        return (
            set(cnt1.keys()) == set(cnt2.keys()) 
            and set(cnt1.values()) == set(cnt2.values()) 
        ) 
```

#### Language used for code

Python3

#### Expected behavior

For the test case as shown below:
`Input: word1 = "abbcc", word2 = "abcc"`
The correct output should be `false`, while my submission giving `true` got accepted. 

Please add the test case below to avoid the issue:
`Input: word1 = "abbcc", word2 = "abcc"`
Output: false

#### Screenshots

![image](https://user-images.githubusercontent.com/44483080/105538730-b53f0780-5ca8-11eb-8ab6-61ff397bf154.png)

![image](https://user-images.githubusercontent.com/44483080/105538844-df90c500-5ca8-11eb-8323-c5ab3c7782a3.png)

**Comment by lc-kay** [comment]
Hi @shengbo-ma 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@shengbo-ma Thank you for your time, we've added another test case recently and the provided solution receives wrong answer now. Therefore, we will not be adding your test case. We appreciate your support.
