### ISSUE TITLE
Missing Test Case - 1657. Determine if Two Strings Are Close

### ISSUE THREAD

**Issue by NihalAgarwal** [LeetCode-Feedback/LeetCode-Feedback#2111]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Test Case missing, I submitted the wrong solution, and it passes all test cases and my solution got accepted but fails for one of my generated test cases.

TestCase: word1 = "a", word2 = "b"

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean closeStrings(String word1, String word2) {
        if( word1.length() != word2.length() ) return false;
        if( word1.length() < 2)return true;
        int[] count1 = new int[26];
        int[] count2 = new int[26];
        for(int i =0; i< word1.length(); i++){
            count1[word1.charAt(i)-'a']++;
            count2[word2.charAt(i)-'a']++;
        }
        for(int i =0; i< 26; i++) {
            if (count1[i] > 0 && count2[i] > 0) continue;
            else if (count1[i] == count2[i]) continue;
            return false;
        }
        Arrays.sort(count1);
        Arrays.sort(count2);
        for(int i = 25; i >= 0; i--){
            if( count1[i] != count2[i]) return false;
        }
        return true;
    }
}
```

#### Screenshots
![aa](https://user-images.githubusercontent.com/46000505/105562263-8f187680-5d3f-11eb-986c-1958ea7cb960.png)

**Comment by lc-kay** [comment]
Hi @NihalAgarwal 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @NihalAgarwal 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
