### ISSUE TITLE
Missing Test Case - 215. Kth Largest Element in an Array

### ISSUE THREAD

**Issue by vshchurenko** [LeetCode-Feedback/LeetCode-Feedback#21116]
### LeetCode Username
Kobzarrr

### Problem number, title, and link
215. Kth Largest Element in an Array https://leetcode.com/problems/kth-largest-element-in-an-array/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Following the constraint https://leetcode.com/problems/kth-largest-element-in-an-array/description/#:~:text=%2D104%20%3C%3D%20nums%5Bi%5D%20%3C%3D%20104
Initially, I approached the problem by creating an array of size 20001, in accordance with the constraint provided on LeetCode. This allowed me to use counting sort efficiently. After implementing this solution, all LeetCode test cases passed successfully, and I was able to submit my solution without any issues. While optimizing my solution to utilize a range determined by maxValue and minValue, I found a missing test case that had to cause my initial solution to fail:
nums = [-10000, 0, 10000]
k = 3
Expected: -10000

### Language used for code

Java

### Code used for Submit/Run operation

```
    public int findKthLargest(int[] nums, int k) {

        int[] count = new int[20001]; // for now to simplify to cover all possible values
        for (int num : nums) { 
            count[num + 10000]++;
        }

        int kLargestIndex = k; 
        for (int i = count.length - 1; i > 0; i--) { 
            if (count[i] > 0) {
                kLargestIndex = kLargestIndex - count[i];
            }
            if (kLargestIndex <= 0) {
                return i - 10000;
            }
        }

        return -1; 

    }
```

### Expected behavior

Should fail if there was a test case:
nums = [-10000, 0, 10000]
k = 3
Expected: -10000

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/51326366/96bbb6d5-70ea-4f93-8600-91de023e933d)
In the screenshot, you can observe that running the provided test case results in failure. However, this specific test case is absent from the solution submission.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team
