### ISSUE TITLE
Missing Test Case - 1702. Maximum Binary String After Change

### ISSUE THREAD

**Issue by ABCbum** [LeetCode-Feedback/LeetCode-Feedback#2112]
#### Your LeetCode username
ABCbum

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
My wrong solution still get accepted.

#### Code you used for Submit/Run operation
```
class Solution {
public:
    string maximumBinaryString(string binary) {
        string ans = "";
        int one = 0;
        int zero = 0;
        int n = binary.size();
        for (char c: binary) {
            if (c == '0') zero++;
            else one++;
        }
        
        // Returning the original string when `one == 1` is not correct.
        if (one == 1 || one == n) return binary;
        
        int count = 0;
        for (char c: binary) {
            if (c == '1') count++;
            else break;
        }

        ans += string(count + zero - 1, '1');
        ans += "0";
        ans += string(n - zero - count, '1');

        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior
I'm expecting this code to get Wrong Answer on this test case:
Input: "00010".
Correct Output: "11101".
This code's Output: "00010".

#### Screenshots
![image](https://user-images.githubusercontent.com/50205705/105565359-f8f14a00-5d58-11eb-8750-be0a6bc187b8.png)
![image](https://user-images.githubusercontent.com/50205705/105565410-37870480-5d59-11eb-9a52-fe3e3c6a20aa.png)

#### Additional context
I've submitted this missing testcase before but it got rejected while I'm still able to reproduce it.

**Comment by lc-kay** [comment]
Hi @ABCbum 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @ABCbum 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
