### ISSUE TITLE
Missing Test Case - 2085. Count Common Words With One Occurrence

### ISSUE THREAD

**Issue by krishnakanthpathi** [LeetCode-Feedback/LeetCode-Feedback#21123]
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/110235523/62124fae-2dd4-4c7a-baf6-3c72d13de827)
There was large test case for small edge case i suggest to add a test case to know about the edge case 
Test case 1:
words1 :["a","a"]
words2: ["a","a"]
Test case 2:
words1 = ["leetcode","is","amazing","as","is"]
words2 = ["amazing","leetcode","is","is"]

**Comment by Kanhucharanstudent** [comment]
`class Solution(object):
    def countWords(self, words1, words2):
        """
        :type words1: List[str]
        :type words2: List[str]
        :rtype: int
        """
        count1 = {}
        count2 = {}
        for word in words1:
            count1[word] = count1.get(word, 0) + 1
        for word in words2:
            count2[word] = count2.get(word, 0) + 1
        result = 0
        for word in count1:
            if count1[word] == 1 and count2.get(word, 0) == 1:
                result += 1    
        return result`

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
