### ISSUE TITLE
Copy-paste mistake in Editorial for 2540. Minimum Common Value

### ISSUE THREAD

**Issue by Y-Rov** [LeetCode-Feedback/LeetCode-Feedback#21139]
### LeetCode Username

[anacondrai](https://leetcode.com/anacondrai/)

### Problem number, title, and link

[2540. Minimum Common Value](https://leetcode.com/problems/minimum-common-value/)

### Category of the bug
- [ ] Editorial

### Description of the bug

Hello, LeetCode team 😄

If we go through the section "Approach 2: Two Pointers", subsection "Algorithm" in [problem's Editorial](https://leetcode.com/problems/minimum-common-value/editorial/) and stop at the 2-nd list item (the description of the 2-nd condition):

> If `nums1[first]` is greater than `nums2[second]`, increment `second` by `1` because we need a larger value from `nums2` to match the value at `nums1[second]`.

Here `nums1[second]` is misused (maybe by copy-paste mistake). `nums1[second]` will not point to the correct value.

### Expected behavior

The corrected explanation:

> If `nums1[first]` is greater than `nums2[second]`, increment `second` by `1` because we need a larger value from `nums2` to match the value at `nums1[first]`.

### Screenshots

![Second_Misuse](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73534920/a897bcd0-8193-4ff8-8495-3fb73dca2d2d)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
