### ISSUE TITLE
Missing Test Case - 2540. Minimum Common Value

### ISSUE THREAD

**Issue by noneofyourbusiness1415252** [LeetCode-Feedback/LeetCode-Feedback#21148]
### LeetCode Username
@noneofyourbusiness1415252

### Problem number, title, and link
https://leetcode.com/problems/minimum-common-value/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
Code isn't checked to see whether it handles arrays which don't have any number in common. This could result in uncaught runtime errors.

### Language used for code
Rust

### Code used for Submit/Run operation
*yes, it's a needless `O(n log m)`, but just for a minimal rational example*
```rs
impl Solution {
  pub fn get_common(a: Vec<i32>, b: Vec<i32>) -> i32 {
      *a.iter().filter(|i| b.binary_search(i).is_ok()).take(1).next().unwrap/*_or*/(/*&-1*/)
  }
}
```
also, shouldn't it be using `NonZeroU32` in place of `i32`, to account for the `∧/1≤nums1∪nums2` range constraint? And, given these constraints, it'd make more sense if the requirements got you to return `0` on error and not `-1`.

### Expected behavior
There should be a test case of
```
[1,3]
[2,4]
```
### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/80610051/f763ebfa-b219-428d-a1db-7a1e530a267d)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
