### ISSUE TITLE
Running Sum of 1D Array - Temp Array Not Counted As Part Of Space Complexity

### ISSUE THREAD

**Issue by alanzheng88** [LeetCode-Feedback/LeetCode-Feedback#21151]
### LeetCode Username
tt27

### Problem number, title, and link
1480. Running Sum of 1D Array
https://leetcode.com/explore/learn/card/the-leetcode-beginners-guide/692/challenge-problems/4422/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [X] Editorial
- [ ] Programming language support

### Description of the bug
in the video, it says it should have a space complexity of O(1) but in fact it should be O(n) since we allocated another temporary array.

### Language used for code
Python

### Code used for Submit/Run operation
not applicable

### Expected behavior
video should say O(n) for space complexity instead of O(1)

### Screenshots
![Screenshot 2024-03-09 at 4 01 15 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/10336657/a55debf2-ddae-4298-8fb2-0664a31a4a41)

### Additional context
came across this while watching the video

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team
