### ISSUE TITLE
Description or examples are unclear or incorrect: 3077. Maximum Strength of K Disjoint Subarrays

### ISSUE THREAD

**Issue by shubhcodegate** [LeetCode-Feedback/LeetCode-Feedback#21156]
### LeetCode Username
Username: kmr_shubh
link: [kmr_shubh](https://leetcode.com/kmr_shubh)

### Problem number, title, and link
[3077. Maximum Strength of K Disjoint Subarrays](https://leetcode.com/problems/maximum-strength-of-k-disjoint-subarrays/)

### Category of the bug
- [x] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [x] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug
- [ ] Description or examples are unclear or incorrect
- The question does not explicitly mention that the order used for multiplication of subarray sums with their corresponding multiplier should be same as the order of their start indices in the given array. 
- It does not mention that the least starting index subarray should be multiplied with maximum k and so on.
Explaining using an example:
`nums = [1,2,3,4-1,-1,-5, 11], k = 3`
I take 3 disjoint sub arrays as [1,2,3], [-1,-1,-5], [11]
Now,
```
expected_ans = sum([11]) * 3 -  sum([-1,-1,-5]) * 2 + sum([1,2,3]) * 1 = 33 + 14 + 10 = 57
// which is more than the test case answer for this test case
testcase_ans = sum([1,2,3]) * 3 - sum([-1,-1,-5]) * 2 + sum([11]) * 1 = 30 + 14 + 11 = 55
```
It should have either explicitly mentioned that the order of subarray matter in calculation of strength or it should have given 57 as the answer in test case.

### Language used for code
C++

### Code used for Submit/Run operation
No code submission since the problem is in question description

### Expected behavior
It should have either explicitly mentioned that the order of subarray matter in calculation of strength or it should have given 57 as the answer in test case.

### Additional context
Please do add LeetCoins if this was helpful.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
