### ISSUE TITLE
Misleading Description of The Question

### ISSUE THREAD

**Issue by shridharGits** [LeetCode-Feedback/LeetCode-Feedback#21166]
### LeetCode Username
the_shridhar

### Problem number, title, and link
1343. Number of Sub-arrays of Size K and Average Greater than or Equal to Threshold
link: https://leetcode.com/problems/number-of-sub-arrays-of-size-k-and-average-greater-than-or-equal-to-threshold/

### Category of the bug
- [x] Problem description

### Description of the bug
Description of the title is misleading. it says:
Given ..... threshold, _return the number of sub-arrays of size k and average greater than or equal to threshold._
It seems like we have to return 2 things
1. number of subarrays each of size k, that can be made from given array.
2. return true if average of whole array is greater than equal to threshold

### Language used for code
C++

### Code used for Submit/Run operation
```
int numOfSubarrays(vector<int>& arr, int k, int threshold) {
        int ans = 0;
        int i = 0;
        int j = 0;
        int sum = 0;
        while(j<arr.size())
        {
            sum+=arr[j];
            if(j-i+1<k)
            {
                j++;
            }
            else{
                if(sum/k>=threshold) ans++;
                sum-=arr[i];
                i++;
                j++;
            }
        }
        return ans;
    }
```

### Expected behavior
Description says: 
Given an ...... threshold, return the number of sub-arrays of size k and average greater than or equal to threshold.

it should be (either any of following options): 
1. Given an ...... threshold, return the number of sub-arrays of size k _**whose**_ average **_is_** greater than or equal to threshold 
2. Given an ...... threshold, return the number of sub-arrays which satisfies following conditions:
      1. size of sub-array is k
      2. average of sub-array is greater than or equal to threshold

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
