### ISSUE TITLE
Missing Test Case - 349. Intersection of Two Arrays

### ISSUE THREAD

**Issue by saurabhverma18** [LeetCode-Feedback/LeetCode-Feedback#21167]
### LeetCode Username

saurabh_verma_

### Problem number, title, and link

349. Intersection of Two Arrays](https://leetcode.com/problems/intersection-of-two-arrays/)

### Category of the bug
 [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

The code which I wrote got Submitted and passsed all testcases, but on testing it with my own custom testcase, the same code thrown an error for that particular testcase.

It is missing the testcase, as when the length of nums1 and nums2 array is 1 then we directly return either nums1 or nums 2.
But the code goes wrong if nums1[0] != nums2[0] , even if the length of both the arrays is 1. 

---> Hence, bug is that it has missing testcase that if length of both array is 1, but if the element at index 0 is not equal.

### Language used for code

Java

### Code used for Submit/Run operation

```
import java.util.*;
class Solution {
    public int[] intersection(int[] nums1, int[] nums2) {
        if(nums1.length==1 && nums2.length==1 ){
            return nums1;
        }
         if(nums1.length==0 && nums2.length==0){
             if(nums1.length==0)
             return nums1;
             else
             return nums2;
         }
        Arrays.sort(nums2);
        Arrays.sort(nums1);
     if(nums2.length<=nums1.length){
         int arr[]=new int[nums2.length];
         int j=0;
         int k=0;
         for(int i=0;i<nums2.length;){
            if(j==nums1.length)
            break;

             if(nums1[j]==nums2[i] && (k==0 || arr[k-1]!=nums1[j])){
                 arr[k]=nums1[j];
                 i++;
                 k++;
                 j++;
               
                 
             }
             else if(nums1[j]<nums2[i]){
                 j++;
             }
             else{
                 
                 i++;
             }
         }
         return Arrays.copyOf(arr,k); 
     }
     else{
           int arr[]=new int[nums1.length];
         int j=0;
         int k=0;
         for(int i=0;i<nums1.length;){
             if(j==nums2.length)
             {
                 break;
             }
             if(nums2[j]==nums1[i] && (k==0 || arr[k-1]!=nums2[j])){
                 arr[k]=nums2[j];
                 i++;
                 k++;
                 j++;
               
                 
             }
             else if(nums2[j]>nums1[i]){
                 i++;
             }
             else
             j++;

            
         }
         return Arrays.copyOf(arr, k); 

     }
    }

       
    
}
```

### Expected behavior

It passed all the testcases and the code got submitted, but it should have thrown error.

As on testing it with my own custom testcase, the code went wrong.

**Custom Testcase:**
nums1=[1]
nums2=[3]

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/135258247/81718277-02e6-4c24-8562-fd94ce76509a)
firstly, the code got accepted.

then when I tested it with my own custom testcase, the same code went wrong.
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/135258247/ddb27a62-7f4f-4692-abc5-683ab89c15c2)

### Additional context

It should have the above custom testcase(also mentioned below) or similiar testcases to it also added. 
**Custom Testcase:**
nums1=[1]
nums2=[3]

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
