### ISSUE TITLE
Problem 3074 - Hint 2 Issue 😯

### ISSUE THREAD

**Issue by TrickyCat** [LeetCode-Feedback/LeetCode-Feedback#21162]
### LeetCode Username
**[TrickyCat 🐱‍💻](https://leetcode.com/TrickyCat/)**

### Problem number, title, and link
[3074. Apple Redistribution into Boxes](https://leetcode.com/problems/apple-redistribution-into-boxes/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [x] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Hint 2 says:

> Select boxes greedily until the total capacity is smaller than the total number of apples

Well, we need to take the boxes (in order from the one with the most capacity to the one with the least capacity) until there is enough capacity to contain all the apples, i.e. until the total capacity is **greater than or equal to** the total number of apples.

Besides, we initially start from the state of picking no boxes, thus the total capacity of picked boxes is 0 which is less than the total number of apples (that is positive according to the problem constraints), so if the hint's wording was right, we would have started from the already optimal subset of picked boxes and would always return 0 as the answer for any given input 😂😂😂😂😂😂.

### Proposed Change

Change the wording:

- from `until` to `while`

  - > Select boxes greedily **while** the total capacity is smaller than the total number of apples

- from `smaller` to `enough` / `greater than or equal to`

  - > Select boxes greedily until the total capacity is **greater than or equal to** the total number of apples

✌

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
