### ISSUE TITLE
Missing Test Case - 1752. Check if Array Is Sorted and Rotated

### ISSUE THREAD

**Issue by istvan404** [LeetCode-Feedback/LeetCode-Feedback#21169]
### LeetCode Username

isti
LeetCode ID: isti

### Problem number, title, and link

1752. Check if Array Is Sorted and Rotated https://leetcode.com/problems/check-if-array-is-sorted-and-rotated

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Most solutions rely on finding the maximum number in the array, and since the array can have duplicates, the test cases do not cover everything.
Precisely when the maximum numbers are not adjacent in the array.

### Language used for code

C++

### Code used for Submit/Run operation

```
class Solution {
public:
    bool check(vector<int>& nums) {
        if(nums.size() == 1)
        {
            return true;
        }
        if(std::is_sorted(nums.begin(), nums.end()))
        {
            return true;
        }
        int max = 0;
        for(int i = 1; i < nums.size(); i++)
        {
            if(nums[max] < nums[i])
            {
                max = i;
            }
        }
        std::vector<int> shifted;
        std::vector<int> shifted_with;
        for(int i = max+1; i < nums.size(); i++)
        {
            if(nums[i] != nums[max])
            {
                shifted.push_back(nums[i]);
            }
            shifted_with.push_back(nums[i]);
        }
        for(int i = 0; i <= max; i++)
        {
            if(nums[i] != nums[max])
            {
                shifted.push_back(nums[i]);
            }
            shifted_with.push_back(nums[i]);
        }
        if(std::is_sorted(shifted.begin(),shifted.end()) || std::is_sorted(shifted_with.begin(),shifted_with.end()))
        {
            return true;
        }
        return false;
    }
};
```

### Expected behavior

Please note that the first and last elements are adjacent in a way. Since we have to right-shift the while array, that can cause them to be adjacent in a way.
For example [6,1,2,4,5,6] -> [1,2,4,5,6,6] after some righ-shifts.
But for example [6,7,2,7,5] cannot be right-shifted into a non-decreasing array.
My program fails the second example, but the same submitted program is accepted, therefore the test cases are not complete.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
