### ISSUE TITLE
Missing Test Case - 1361. Validate Binary Tree Nodes

### ISSUE THREAD

**Issue by chaslain** [LeetCode-Feedback/LeetCode-Feedback#21168]
### LeetCode Username
chaslain

### Problem number, title, and link

1361. Validate Binary Tree Nodes https://leetcode.com/problems/validate-binary-tree-nodes/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
There is no false test case for a problem with 1 node.

### Language used for code
java

### Code used for Submit/Run operation

```
class Solution {
    public boolean validateBinaryTreeNodes(int n, int[] leftChild, int[] rightChild) {

        // this part should cause the code to fail but does not.
        if (n < 2)
            return true;
        
        Set<Integer> unique = new HashSet<>();
        
        for (int i = 0; i < n; i++) {
            if (leftChild[i] != -1) {
                if (unique.contains(leftChild[i]))
                    return false;
                unique.add(leftChild[i]);
            }
            if (rightChild[i] != -1) {
                if (unique.contains(rightChild[i]))
                    return false;
                unique.add(rightChild[i]);
            }
        }

        int root = 0;
        for (int i = 0; i < n; i++) {
            if (!unique.contains(i)) {
                root = i;
                break;
            }
        }
        

        Set<Integer> visited = new HashSet<>();

        Stack<Integer> s = new Stack<>();

        s.add(rightChild[root]);
        s.add(leftChild[root]);
        visited.add(root);

        boolean valid = true;
        
        while (!s.isEmpty()) {
            int t = s.pop();
            if (t == -1) {
                continue;
            }

            if (visited.contains(t)) {
                valid = false;
                break;
            }

            visited.add(t);

            int l = leftChild[t];
            int r = rightChild[t];

            s.add(l);
            s.add(r);
        }


        if (valid && visited.size() == n) {
            return true;
        }

        return false;
    }
}
```

### Expected behavior
The submission should have a test case with the values:
n = 1
leftChild = [0]
rightChild = [-1]

### Additional context
The test case is accepted as valid and the rules do not explicitly state that you can trust a node will not reference itself.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
