### ISSUE TITLE
Missing Test Case - 73. Set Matrix Zeroes

### ISSUE THREAD

**Issue by haasib** [LeetCode-Feedback/LeetCode-Feedback#21163]
### Category of the bug
- [x] Missing test Case *(Incorrect Code getting accepted because of missing test cases)*

### Incorrect Code got accepted. Should have failed on a particular test case, but got accepted. The case is as following.
```[[-1111,-1122,2,1],[3,4,5,2],[1,3,1,5]]```

### Code used for Submit/Run operation

```
class Solution {
public:
    void setZeroes(vector<vector<int>>& matrix) {
        int n = matrix.size(), m= matrix[0].size();
        for(int i=0;i<n;i++){
            for(int j=0;j<m;j++){
                if(!matrix[i][j]) {
                    for(int k=0;k<n;k++){
                        if(matrix[k][j])matrix[k][j]=(k+j+101)*(-11);
                    }
                    for(int k=0;k<m;k++){
                        if(matrix[i][k])matrix[i][k]=(i+k+101)*(-11);
                    }
                }
            }
        }
        for(int i=0;i<n;i++){
            for(int j=0;j<m;j++){
                if(matrix[i][j]==(i+j+101)*(-11))matrix[i][j]=0;
            }
        }
    }
};
```

### Output for the above test case should be ```[[-1111,-1122,2,1],[3,4,5,2],[1,3,1,5]]```
But it outputs ```[[0,0,2,1],[3,4,5,2],[1,3,1,5]]``` and got accepted as well.

**Comment by Harnyx-Dope** [comment]
Absolutely Correct Bro!!

**Comment by haasib** [comment]
@Harnyx-Dope 
Thanks!!
What's the process of adding this case in LC?

**Comment by haasib** [comment]
FYI, Link to the submission that got accepted: https://leetcode.com/problems/set-matrix-zeroes/submissions/1199563805

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
