### ISSUE TITLE
Missing Test Case - 167. Two Sum II - Input array is sorted

### ISSUE THREAD

**Issue by DoubleA-DA** [LeetCode-Feedback/LeetCode-Feedback#2117]
#### Category of the bug
-  Question
- [ ] Solution
- [ ] Language

#### Description of the bug

[-1000,-1,0,1]
1
when I give that as a test case it fails but my code passes all the other cases and gets accepted

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<int> twoSum(vector<int>& numbers, int target) {
        int i,j;
        for(i=0;i<numbers.size();i++)
        {if(numbers[i]==0&&target!=0)continue;
            for(j=i+1;j<numbers.size();j++)
            {
                if(numbers[i]+numbers[j]==target)return {i+1,j+1};
            }
        }return {};
    }
};
```

#### Language used for code

C++

#### Expected behavior

So according to my test case it should return {3,4} but it returns { }

#### Screenshots

![Code pic from my gdrive](https://drive.google.com/uc?export=view&id=1KaX23s3RF18ZS9k3IvMWCGdM4aor4YiV)

**Comment by lc-kay** [comment]
Hi @DoubleA-DA 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @DoubleA-DA 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by DoubleA-DA** [comment]
@lc-kay my leetcode ID is motralk (https://leetcode.com/motralk/)
