### ISSUE TITLE
Missing Test Case - 791. Custom Sort String

### ISSUE THREAD

**Issue by cursorhigh** [LeetCode-Feedback/LeetCode-Feedback#21176]
### LeetCode Username
[swadhinmaharana212](https://leetcode.com/swadhinmaharana212)

### Problem number, title, and link

[791. Custom Sort String](https://leetcode.com/problems/custom-sort-string/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Language used for code

python3

### Code used for Submit/Run operation

```
class Solution:
    def customSortString(self, order: str, s: str) -> str:
        common=[]
        k=list(s)
        xtra=[]
        for x in order:
            while x in k:
                k.remove(x)
                common.append(x)
        return "".join(common)+"".join(k)
```

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/115407035/846deda8-35fd-4548-820f-5b10646346d3)

just an additional case which could help some of coders

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
