### ISSUE TITLE
Wrong Test Case Constraint - 735. Asteroid Collision

### ISSUE THREAD

**Issue by Bambooin** [LeetCode-Feedback/LeetCode-Feedback#2118]
#### Your LeetCode username
0x4C0DE

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Test case reject valid input [5]

Invalid Testcase
expected 'asteroids' to have 2 <= size <= 10000 but got 1

which conflicts with decription '1 <= asteroids <= 10^4'

BTW: The constraints shoud be '1 <= asteroids.length <= 10^4', it's more clear.

#### Code you used for Submit/Run operation
```
// https://leetcode.com/problems/asteroid-collision/
class Solution {
  public int[] asteroidCollision(int[] asteroids) {
    Deque<Integer> stack = new LinkedList<>();
    for (int asteroid : asteroids) {
      if (asteroid > 0 || stack.isEmpty() || stack.peek() < 0) {
        stack.push(asteroid);
      } else {
        while (!stack.isEmpty() && stack.peek() > 0 && stack.peek() < -asteroid) {
          stack.pop();
        }

        if (stack.isEmpty() || stack.peek() < 0) {
          stack.push(asteroid);
        } else if (stack.peek() == -asteroid) {
          stack.pop();
        }
      }
    }

    int length = stack.size();
    int[] result = new int[length];
    for (int i = 0; i < length && !stack.isEmpty(); i++) {
      result[i] = stack.pollLast();
    }

    return result;
  }
}

```

#### Language used for code
Java

#### Expected behavior
Valid test case of length 1 should return original array.

**Comment by lc-kay** [comment]
Hi @Bambooin 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Bambooin 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
