### ISSUE TITLE
Rounding off issue in only 'Postgre Sql 'run time Problem 'Percentage of Users Attended a Contest' in SQL 50

### ISSUE THREAD

**Issue by ShreyCR** [LeetCode-Feedback/LeetCode-Feedback#21195]
### Category of the bug
- [###] Problem description
While solving the problem in Postgre SQL runtime the code does not work as it does not round off to the nearest 2 digits after the decimal point. The same code works in MySQL environment
- [ ] Solved examples
- [###] Problem constraints
Environment must be set to Postgre SQL 
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [###] Programming language support
Works in MySQL but not in Postgre SQL

### Description of the bug
When executing the provided SQL code in a PostgreSQL environment, the rounding off to the nearest two digits after the decimal point does not function as expected. This issue does not arise when the code is run in a MySQL environment. 

### Language used for code
Postgre SQL

## Code used for Submit/Run operation

```
SELECT 
    query_name,
    ROUND(AVG(CAST(rating AS DECIMAL) / position), 2) AS quality,
    ROUND((SUM(CASE WHEN rating < 3 THEN 1 ELSE 0 END) / COUNT(*) * 100), 2) AS poor_query_percentage
FROM 
    Queries
GROUP BY 
    query_name;
```

**Comment by ShreyCR** [comment]
![PostgreSQL](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/54467701/5b7b745a-8487-412a-a68e-5ab3b7f6c4a7)
![MySQL](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/54467701/df546a52-c71c-4b47-882e-880f80e15337)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The problem page link. 

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

The attached problem is incorrect (https://leetcode.com/problems/percentage-of-users-attended-a-contest/)

Please provide the problem that you’re trying on it.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
