### ISSUE TITLE
Problem description - 791. Custom Sort String

### ISSUE THREAD

**Issue by IliasaurCat** [LeetCode-Feedback/LeetCode-Feedback#21192]
### LeetCode Username

IliasaurCat

### Problem number, title, and link

[791. Custom Sort String](https://leetcode.com/problems/custom-sort-string/)

### Category of the bug
- [X] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The answer "bacd" is not correct for Example 2.

### Expected behavior

The string "bacd" in Example 2 should be changed to, for example, "bdca".

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/151400270/1155b0cf-2961-4e99-b6bd-9a69f6cbdb5f)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
