### ISSUE TITLE
Missing Test Case - 635. Design Log Storage System

### ISSUE THREAD

**Issue by fury93** [LeetCode-Feedback/LeetCode-Feedback#21196]
### LeetCode Username

yourick

### Problem number, title, and link

[635. Design Log Storage System](https://leetcode.com/problems/design-log-storage-system/)

### Category of the bug
- [x] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Problem description: There is no clarification in the description, what we must do if have two events with the same unique ID.
If we add to storage a log with already existence ID and new timestamp in my opinion we must to change timestamp for this ID.
Here is test case, we have two logs with ID = 1 and different timestamps (look only at year, attached screen1)
Test case:
["LogSystem","put","put","retrieve","retrieve", "retrieve"]
[[],[1,"2017:01:01:00:00:00"],[1,"2015:01:01:00:00:00"],["2015:01:01:00:00:00","2017:01:01:01:00:00","Year"],["2015:01:01:00:00:00","2015:01:01:00:00:01","Year"], ["2017:01:01:00:00:00","2017:01:01:00:00:01","Year"]]
Output: [null,null,null,[1],[1],[1]]
Expected: [null,null,null,[1,1],[1],[1]]
Here is expected two similar IDS for range 2015-2017. And an unique ID is valid for year 2015 and 2017.
I think that only one unique ID should be valid (what was added latest).

Similar test case 63 (attached screen2): here duplicates don't allowed in the result like expected in my test case above.
["LogSystem","put","put","put","put","retrieve","retrieve"]
[[],[1,"2017:01:01:23:59:59"],[2,"2017:01:01:22:59:59"],[3,"2016:01:01:00:00:00"],[2,"2012:01:01:22:59:59"],["2016:01:01:01:01:01","2017:01:01:23:00:00","Year"],["2016:01:01:01:01:01","2017:01:01:23:00:00","Hour"]]

### Language used for code

python3

### Code used for Submit/Run operation

```
class LogSystem:

    def __init__(self):
        self.logs = defaultdict(set)
        self.mask = {"Year": 4, "Month": 7, "Day": 10, "Hour":13, "Minute":16, "Second":19}

    def put(self, id, timestamp):
        self.logs[timestamp].add(id)

    def retrieve(self, start, end, granularity):
        sliceIdx = self.mask[granularity]
        start = start[:sliceIdx]
        end = end[:sliceIdx]

        res = set()
        for time, ids in self.logs.items():
            if start <= time[:sliceIdx] <= end:
                res.update(ids)
        return res
```

### Expected behavior

1. Clear description about items with the same unique ID. 
2. Similar expected behaviour for test-cases when we have duplicates by ID.

### Screenshots

My new test-case:
![Screenshot 2024-03-11 at 20 01 49](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/5826459/bf31e0c5-a1ec-451a-ae57-b8d54ec85dcf)
Test case 63:
![Screenshot 2024-03-11 at 20 13 55](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/5826459/96733366-cab8-41e0-beb2-cb1fc413ad54)

![Screenshot 2024-03-11 at 20 28 21](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/5826459/77aa9e73-2588-4c3c-8cfc-7af5a5024f63)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team
