### ISSUE TITLE
Missing test case

### ISSUE THREAD

**Issue by apoorva1999** [LeetCode-Feedback/LeetCode-Feedback#212]
**Kind of bug**
Testcase 

**Describe the bug**
code got accepted which has output different than expected.

**what language is your code written in**
C++

**The code you submit/run**
```
class Solution {
public:
int minNumberOfFrogs(string &arr)
{

    unordered_map<char, vector<int>> mp;
    for (int i = 0; i < arr.size(); i++)
    {
        mp[arr[i]].push_back(i);
    }

    string s = "croak";
    int si = 1;
    int mi = mp['c'].size();
    unordered_map<char, int> idx;
    idx['r'] = 0;
    idx['o'] = 0;
    idx['a'] = 0;
    idx['k'] = 0;
  
    int pi =-1;
   
    priority_queue<int,vector<int>,greater<int>>pq;
    
    for (int i = 0; i < mi; i++)
    {   
        
        int chi = mp['c'][i];
        arr[chi]='#';
        si = 1;
        pi = chi;
        while (si < s.size())
        {
            
            int ci = idx[s[si]];

            // if (i == 1)
            // {
            //     deb(s[si])
            //         deb(ci) deb(mp[s[si]].size()) deb(pi) deb(mp[s[si]][ci])
            // }
            if (ci < mp[s[si]].size() && pi < mp[s[si]][ci])
            {
                pi = mp[s[si]][ci];
                idx[s[si]]++;
                arr[mp[s[si]][ci]]='#';
                si++;
            }
            else
            {
              
                return -1;
            }
        }
        if(pq.size()==0)
        {
            pq.push(pi);

        }
        else{
            int rem = pq.top(); 
            if(rem < chi)
            {
                pq.pop();
                pq.push(pi);
            }
            else{
                pq.push(pi);
              
            }
        }
    }
    /*   //This was the condition to be checked
    deb(arr)
    for(int i=0;i<arr.size();i++)
    {
        if(arr[i]!='#') return -1;
    }
    return pq.size();*/
}
};
```

**Expected behavior**

if the string is  **"croakroak",** it is impossible to be generated because there are some characters that can't be combined to make the string "croak". 
In the above code, the output of this answer is 1, which means if there is one frog present then this sound can be made which is incorrect.
Running the same code on leetcode using the above test case gives **expected answer -1** but **output 1**, still the code got accepted.

**Screenshots**
![image](https://user-images.githubusercontent.com/46842087/80592686-76dc2b00-8a3d-11ea-8d01-b4702f511171.png)

**Comment by CooperCooperCooper** [comment]
Hi @apoorva1999,
Thank you for reaching out to us. I've relayed your issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.

Just a gentle reminder that, if you would like us to take a specific part of the submission, please share a link to your original submission as the commenting within the code was really difficult to spot. Thank you!
