### ISSUE TITLE
Missing Topic Tag - 1018. Binary Prefix Divisible By 5

### ISSUE THREAD

**Issue by istvan404** [LeetCode-Feedback/LeetCode-Feedback#21207]
### LeetCode Username

isti
LeetCode ID: isti

### Problem number, title, and link

1018. Binary Prefix Divisible By 5 https://leetcode.com/problems/binary-prefix-divisible-by-5/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [x] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Every solution requires a basic knowledge in Bit Manipulation.
I'm a real beginner in Bit Manipulation, and before starting this question I had no idea what is a left shit.
Even tough it's and easy concept, the problem still misses the "Bit Manipulation" tag.
For beginners in bit manipulation, this problem is great, and they should be able to find it by the tag.

### Language used for code

C++

### Code used for Submit/Run operation

```
class Solution {
public:
    vector<bool> prefixesDivBy5(vector<int>& nums) {
        vector<bool> result;
        int num = 0;
        for(int i = 0; i < nums.size(); i++)
        {
            num = (num * 2 + nums[i]) % 5;
            result.push_back(num == 0);
        }
        return result;
    }
};
```

### Expected behavior

Brute-force method doesn't work, we would have an overflow in `unsigned long long` type aswell.
Only viable solution is to know about the left shift

### Additional context

If you check the WORST performing solutions (by runtime or memory), they all shift the bits to the left.
Every comment that mentions the solution talks about left shifting.
Every public solution talks about left shifting the bits.
Every youtube video of this problem talks about basic bit manipulation.

Please note that I'm not questioning the difficulty of the problem. It is easy, but when I searched for problems without Bit Manipulation tag, I expect problems without Bit Manipulation...

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team
