### ISSUE TITLE
Missing Test Case - 1329. Sort the Matrix Diagonally

### ISSUE THREAD

**Issue by TazdingoDing** [LeetCode-Feedback/LeetCode-Feedback#2120]
#### Your LeetCode username

tazdingoHuang

#### Category of the bug
- [ ] Question
- [V] Solution
- [ ] Language

#### Description of the bug

Missing m>n test cases where m == len(matrix) and n == len(matrix[i]). I got accepted for code described below but facing runtime error using custom test case [[3,9],[2,4],[1,2],[9,8],[7,3]] which has m=5 and n=2.

#### Code you used for Submit/Run operation

```
class Solution:
    def diagonalSort(self, mat: List[List[int]]) -> List[List[int]]:
        x = len(mat)
        y = len(mat[0])
        
        if x <= 1 or y <= 1:
            return mat
        
        totalList = []
        for xi in range(x-1, -1, -1):
            tmp = []
            for i in range(x-1 - xi + 1):
                tmp.append(mat[xi+i][i])
            totalList.append(tmp)
        for yi in range(1, y):
            tmp = []
            for i in range(min(x, y-yi)):
                print(i, yi+i)
                tmp.append(mat[i][yi+i])
            totalList.append(tmp)
        
        for l in totalList:
            l.sort()
            
        listCount = 0
        for xi in range(x-1, -1, -1):
            idxCount = 0
            for i in range(x-1 - xi + 1):
                mat[xi+i][i] = totalList[listCount][idxCount]
                idxCount += 1
            listCount += 1
        for yi in range(1, y):
            idxCount = 0
            for i in range(min(x, y-yi)):
                mat[i][yi+i] = totalList[listCount][idxCount]
                idxCount += 1
            listCount += 1
        return mat

```

#### Language used for code

Python3

#### Expected behavior

I should have got a runtime error submitting this answer, but I got accepted.

#### Screenshots

![image](https://user-images.githubusercontent.com/40261008/105579499-1ad2e700-5dc2-11eb-9156-5500b8af7620.png)
![image](https://user-images.githubusercontent.com/40261008/105579518-2faf7a80-5dc2-11eb-949f-c5e0ead7707f.png)

**Comment by lc-kay** [comment]
Hi @TazdingoDing 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @TazdingoDing 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
