### ISSUE TITLE
Missing Test Case - 791. Custom Sort String

### ISSUE THREAD

**Issue by kaleshrikant23** [LeetCode-Feedback/LeetCode-Feedback#21200]
### LeetCode Username
kaleshrikant23

### Problem number, title, and link
[791. Custom Sort String](https://leetcode.com/problems/custom-sort-string/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
A solution is accepted, but it fails on a test case:
order = "abc"
s = "aabb"
or
order = "abc"
s = "aab"

### Language used for code
Python

### Code used for Submit/Run operation

```
class Solution(object):
    def customSortString(self, order, s):
        """
        :type order: str
        :type s: str
        :rtype: str
        """
        def insert(ans,s):
            si = list(set(list(s)))
            for i in si:
                if i not in ans:
                    ans += i*(s.count(i))
                elif s.count(i) > 1:
                    l = ans.index(i)
                    ans = ans[:l+1] + i*(s.count(i)-1) + ans[l+1:]
            return ans
        ans = str(order)
        if len(s) > len(order):
            return insert(ans,s)
        elif len(s) == len(order):
            return ans
        else:
            c = 0
            for i in range(len(order)):
                if order[i] not in s:
                    ans = ans[:i-c] + ans[i+1-c:]
                    c += 1
            return insert(ans,s)
```

### Expected behavior
The solution should not be accepted since it fails on a test case.

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/144605260/a147d737-ccde-4737-a7c7-b939cedc3160)

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/144605260/d3949411-e219-4f43-ac64-b9025703c48d)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
