### ISSUE TITLE
Missing Test Case - 1171. Remove Zero Sum Consecutive Nodes from Linked List

### ISSUE THREAD

**Issue by cheoljoo** [LeetCode-Feedback/LeetCode-Feedback#21209]
### LeetCode Username
- CharlesLee
- cheoljoo@gmail.com

### Problem number, title, and link
- [1171. Remove Zero Sum Consecutive Nodes from Linked List](https://leetcode.com/problems/remove-zero-sum-consecutive-nodes-from-linked-list/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [O] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
- i think it is not bug.
- but i need clarification.
- testcase : [-3,2,1,1,-3,1]
- we can get two solution  [1,-3,1] <- your solution
- we can get the other [-3,2] 
- question : what is better?

### Expected behavior
- need clarificaiton in description
  - add upper example and more explanation why [1,-3,1] is the solution.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
