### ISSUE TITLE
1171. Either poor wording or an incorrect testcase.

### ISSUE THREAD

**Issue by nekr0z** [LeetCode-Feedback/LeetCode-Feedback#21217]
### LeetCode Username
nekr0z

### Problem number, title, and link
1171. Remove Zero Sum Consecutive Nodes from Linked List https://leetcode.com/problems/remove-zero-sum-consecutive-nodes-from-linked-list/

### Category of the bug
- [x] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
Testcase 62 is `[0]` with the expected output of empty list (i.e. the single node with value of `0` is expected to be deleted). Description says "repeatedly delete consecutive sequences of nodes", and the word _consecutive_ by definition implies that the sequence is 2 or more nodes, not a single node.

### Language used for code
Go

### Code used for Submit/Run operation
```
func removeZeroSumSublists(head *ListNode) *ListNode {
loop:
    for {
        var prev []*ListNode
        var sum []int
        this := head
        var par *ListNode
        for this != nil {
            for i := range sum {
                sum[i] += this.Val
                if sum[i] == 0 {
                    if prev[i] == nil {
                        head = this.Next
                    } else {
                        prev[i].Next = this.Next
                    }
                    continue loop
                }
            }
            sum = append(sum, this.Val)
            prev = append(prev, par)
            par = this
            this = this.Next
        }
        return head
    }
}
```

### Expected behavior
Test 62 pass.

**Comment by LC-Pam** [comment]
Dear user,

Thank you for submitting your code to our platform. After a thorough evaluation, we regret to inform you that your code did not produce the expected results. Our code judge is functioning correctly, and we have verified the correctness of our evaluation process.

We kindly suggest that you review your code carefully and ensure it adheres to the problem requirements and constraints. It may be beneficial to double-check your logic, algorithm implementation, and any potential errors or corner cases that could affect the code's performance.

Additionally, we encourage you to explore our discussion board, where you can seek assistance from the community. Many experienced users and experts are available to help troubleshoot issues, provide insights, and offer guidance on improving your code.

We believe that by reviewing your code and actively engaging with the community, you will have a better chance of identifying and resolving the discrepancies. Remember, learning from such experiences and iterating on your code is an essential part of the programming journey.

We appreciate your understanding and encourage you to continue learning and improving your coding skills.

Should you have any further questions or need additional support, please don't hesitate to reach out to us.

Best regards,

The LeetCode Team

**Comment by nekr0z** [comment]
You didn't even read the report, did you? ;-)
