### ISSUE TITLE
Missing Test Case - 2126. Destroying Asteroids

### ISSUE THREAD

**Issue by yo-msh** [LeetCode-Feedback/LeetCode-Feedback#21214]
### LeetCode Username
manvardhansingh05

### Problem number, title, and link
2126. Destroying Asteroids https://leetcode.com/problems/destroying-asteroids/description/

### Category of the bug
-  Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

My solution uses a stack, and it has passed all the test-cases provided in for "submit", but when i provided with a custom test case, it failed, thus suggesting this code for stack approach is not the ideal one as for the solution.
The custom test-case was, mass = 2, asteroids = [13,3,7,5,2]
The expected output is "true", but output we are getting is "false"

### Language used for code

C++

### Code used for Submit/Run operation

```
class Solution {
public:
    bool asteroidsDestroyed(long mass, vector<int>& asteroids) {
        stack <int> s;

        for(int i : asteroids){
            s.push(i);

            while(!s.empty() && s.top() <= mass){
                mass+= s.top();
                s.pop();
            }
        }

        if(s.empty()) return true;
        return false;
    }
};
```

### Expected behavior

So, the above code has passed for all the test cases, but fails for the the custom test-case.
The custom test-case was, mass = 2, asteroids = [13,3,7,5,2]
The expected output is "true", but output we are getting is "false"

### Screenshots

The Solution using stack.
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/119718165/71430880-9b1c-45cc-9118-007b9a2b51af)

The custom approach.
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/119718165/532a757e-4a97-4185-8cdf-5936e981f4f3)

### Additional context

Can you too please cross verify for this custom test case.
link : https://leetcode.com/problems/destroying-asteroids/

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
