### ISSUE TITLE
Missing Test Case - 2126. Destroying Asteroids

### ISSUE THREAD

**Issue by ankit2210812** [LeetCode-Feedback/LeetCode-Feedback#21219]
### LeetCode Username

ankitmarvel22102004

### Problem number, title, and link

2126. Destroying Asteroids https://leetcode.com/problems/destroying-asteroids/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

-[ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
### Description of the bug

As the problem is good to go for greedy approach but if we do it using stack it fails.

### Language used for code

C++

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
class Solution {
public:
    bool asteroidsDestroyed(long long int mass, vector<int>& asteroids) {
        stack<int>st;
        for(int i=0;i<asteroids.size();i++)
        {
            st.push(asteroids[i]);
            while(!st.empty() && mass>=st.top())
            {
                mass+=st.top();
                st.pop();
            }
        }
        return st.empty();
    }
};

```

### Expected behavior

for the testcase mass=70 and asteroids=[100,90,100,10,15], the output should be True but it is showing false. it skips the agenda for greedily approach if we do it using stack and all thetestcases are such that it passes the stack solution approach not the above testcase.
### Additional context

It works well with greedy approach of choosing smallest asteroid first and then adding it to your answer.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
