### ISSUE TITLE
Missing Test Case - 628. Maximum Product of Three Numbers

### ISSUE THREAD

**Issue by elderaj** [LeetCode-Feedback/LeetCode-Feedback#21215]
jaredlivesey

### Problem number, title, and link
628. Maximum Product of Three Numbers https://leetcode.com/problems/maximum-product-of-three-numbers/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

The test case [1,0,-1,-1] would have failed this code.

C++

### Code used for Submit/Run operation

```
class Solution {
public:
    int maximumProduct(vector<int>& nums) {
        if(nums.size() == 3) return nums[0] * nums[1] * nums[2];

        sort(nums.begin(), nums.end());
        vector<int> pos;
        vector<int> neg;
        bool zero = false;
        for(auto i : nums) {
            if(i < 0) neg.push_back(i);
            else if(i > 0) pos.push_back(i);
            else if(i == 0) zero = true;
        }

        if(neg.size() == 0) {
            if(pos.size() <= 2) return 0;
            else return pos[pos.size() - 1] * pos[pos.size() - 2] * pos[pos.size() - 3];
        }
        if(pos.size() == 0) {
            if(zero) return 0;
            else return neg[neg.size() - 1] * neg[neg.size() - 2] * neg[neg.size() - 3];
        }
        if(pos.size() == 1) {
            if(zero) return 0;
            else return pos[0] * neg[0] * neg[1];
        }
        if(pos.size() == 2) {
            if(neg.size() <= 1) return 0;
            return pos[1] * neg[0] * neg[1];
        }
        if(pos.size() >= 3) {
            int p = pos[pos.size() - 1] * pos[pos.size() - 2] * pos[pos.size() - 3];
            if(neg.size() >= 2) {
                int n = pos[pos.size() - 1] * neg[0] * neg[1];
                return (p > n ? p : n);
            }
            return p;
        }
        return 0;
    }
};
```

Code should have failed but instead passed.

### Screenshots

The problem is this portion of the code:

 if(pos.size() == 1) {
            if(zero) return 0;
            else return pos[0] * neg[0] * neg[1];
}

If there was exactly one positive number in the input array, then I should have tested to see if there were at least 2 negative numbers, and return 0 only if there weren't.  That's not what this code does.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
