### ISSUE TITLE
1171. Remove Zero Sum Consecutive Nodes from Linked List

### ISSUE THREAD

**Issue by Medhansh-32** [LeetCode-Feedback/LeetCode-Feedback#21223]
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ *] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Code used for Submit/Run operation

```
import java.util.*;
class Solution {
    public ListNode removeZeroSumSublists(ListNode head) {
    HashMap<Integer,ListNode> map=new HashMap<>();
    ListNode temp=head;
    int sum=0;
    int i=0;
    while(temp!=null){
        sum+=temp.val;
        if(map.containsKey(sum)){
ListNode ans=map.get(sum);
ans.next=temp.next;
   return head;
        }else{
   map.put(sum,temp);
   temp=temp.next;
        }

    }
 return head;
    }
}

```

### Additional context

![Screenshot from 2024-03-12 16-30-04](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/141748032/12452ece-70ad-4d1d-b3d6-6ab4bd77f2ae)

**Comment by naXa777** [comment]
@Medhansh-32  If your Java code doesn't delete consecutive nodes `2` and `-2` (that sum to 0), then it's a problem with your code. The test is correct.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback. We encourage you to share your questions in the discussion forum, where the community can provide insights and assistance.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
