### ISSUE TITLE
Missing Test Case - 1261. Find Elements in a Contaminated Binary Tree

### ISSUE THREAD

**Issue by JMC2002** [LeetCode-Feedback/LeetCode-Feedback#21220]
### LeetCode Username

zi-bu-yu-mf

### Problem number, title, and link

1261. Find Elements in a Contaminated Binary Tree https://leetcode.cn/problems/find-elements-in-a-contaminated-binary-tree/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The target should be larger (up to 1e6)

### Language used for code

C++

### Code used for Submit/Run operation

```cpp
bool flg[100003];
class FindElements {
public:
    FindElements(TreeNode* root) {
        memset(flg, 0, sizeof(flg));
        auto dfs = [](auto&& self, TreeNode* node, int val) {
            if (val > 100000)[[unlikely]] return;
            flg[val] = true;
            if (node->left) self(self, node->left, 2 * val + 1);
            if (node->right) self(self, node->right, 2 * val + 2);
        };
        dfs(dfs, root, 0);
    }

    bool find(int target) {
        return flg[target];
    }
};
```

### Expected behavior

The target is up to 1e6, but 1e5 is also passed.

### Screenshots

![_2@( B )@S`(8P$5BCR(K`0](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/57168689/c4dca5ef-a87e-4e04-bfb1-57efe056f9e3)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
