### ISSUE TITLE
Wrong Description - 1733. Minimum Number of People to Teach

### ISSUE THREAD

**Issue by daqingwax** [LeetCode-Feedback/LeetCode-Feedback#2122]
#### Your LeetCode username

daqingwax

#### Category of the bug
- [ x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Unclear description for the example.
Input: n = 3, languages = [[2],[1,3],[1,2],[3]], friendships = [[1,4],[1,2],[3,4],[2,3]]
Output: 2
Explanation: Teach the third language to users 1 and 2, yielding two users to teach.

Should be teaching language 3 to users 1 & 3 instead of 1 & 2.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

java

#### Expected behavior

Unclear description for the example.
Input: n = 3, languages = [[2],[1,3],[1,2],[3]], friendships = [[1,4],[1,2],[3,4],[2,3]]
Output: 2
Explanation: Teach the third language to users 1 and 2, yielding two users to teach.

Should be teaching language 3 to users 1 & 3 instead of 1 & 2.

**Comment by lc-kay** [comment]
@daqingwax Our team was made aware of this issue shortly after the contest and made the necessary changes. Thank you for your time.
