### ISSUE TITLE
1171. Remove Zero Sum Consecutive Nodes from Linked List

### ISSUE THREAD

**Issue by Medhansh-32** [LeetCode-Feedback/LeetCode-Feedback#21227]
### LeetCode Username
Medhansh_32

### Problem number, title, and link

 1171. Remove Zero Sum Consecutive Nodes from Linked List https://leetcode.com/problems/remove-zero-sum-consecutive-nodes-from-linked-list/
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ *] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

It does not pass test case according to question or description .
Input 
head =[1,2,3,-3,-2]
Output
[1,2,-2]
Expected
[1]

But output [1,2,-2] also satisfies the condition.
### Language used for code

JAVA

### Code used for Submit/Run operation

```
 import java.util.*;
class Solution {
    public ListNode removeZeroSumSublists(ListNode head) {
    HashMap<Integer,ListNode> map=new HashMap<>();
    ListNode temp=head;
    int sum=0;
    int i=0;
    while(temp!=null){
        sum+=temp.val;
        if(map.containsKey(sum)){
ListNode ans=map.get(sum);
ans.next=temp.next;
   return head;
        }else{
   map.put(sum,temp);
   temp=temp.next;
        }

    }
 return head;
    }
}


```

**Comment by naXa777** [comment]
> But output [1,2,-2] also satisfies the condition.

No, it doesn't. The correct solution should delete nodes `2` and `-2`, because they sum to 0.
See the Example 3 in the problem requirements.

**Comment by Medhansh-32** [comment]
> > But output [1,2,-2] also satisfies the condition.
> 
> No, it doesn't. The correct solution should delete nodes `2` and `-2`, because they sum to 0. See the Example 3 in the problem requirements.

Thanks
