### ISSUE TITLE
Missing Test Case - 2126. Destroying Asteroids

### ISSUE THREAD

**Issue by Ankit-04** [LeetCode-Feedback/LeetCode-Feedback#21231]
### Category of the bug
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

A greedy stack approach passes the all the test cases even though it should not.

### Code used for Submit/Run operation

```
        stk = []

        for x in asteroids:
            stk.append(x)
            while stk and stk[-1] <= mass:
                mass += stk.pop()

        return not stk
```

### Expected behavior

This code should fail on test cases where low values get stuck at bottom of stack (mass = 3 asteroids = [4,5,1])

### Screenshots

<img width="1440" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/42247825/ca24ed0d-75ac-4116-9bf0-98160dadea0c">

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by Ankit-04** [comment]
Hello,

Here is the submission link
<https://leetcode.com/problems/destroying-asteroids/submissions/1201605607>
with the code that should not have passed. A test case this fails on is
mass = 3, asteroids = [4,5,1]

Thank you

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
