### ISSUE TITLE
[1171. Remove Zero Sum Consecutive Nodes from Linked List] - incorrect test case

### ISSUE THREAD

**Issue by anudeepdv** [LeetCode-Feedback/LeetCode-Feedback#21242]
### LeetCode Username
anudeepdv333

### Problem number, title, and link
[1171. Remove Zero Sum Consecutive Nodes from Linked List]
(https://leetcode.com/problems/remove-zero-sum-consecutive-nodes-from-linked-list/)

### Category of the bug

- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### Description of the bug
Test case 1 is invalid

### Language used for code
Python

class Solution:
    def removeZeroSumSublists(self, head: Optional[ListNode]) -> Optional[ListNode]:
        
        dummy= ListNode(0,head)

        pr_sum=0
        pr_map={}

        cur=dummy.next

        while cur:
            pr_sum+=cur.val
            pr_map[pr_sum]=cur
            cur=cur.next

        cur = dummy
        pr_sum=0

        while cur:
            pr_sum+=cur.val
            if pr_sum in pr_map:
                cur.next = pr_map[pr_sum].next

            cur=cur.next
        return dummy.next

```


### Expected behavior



### Screenshots


### Additional context

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
