### ISSUE TITLE
Submission checker is confused about return type - 289. Game of Life

### ISSUE THREAD

**Issue by csuter** [LeetCode-Feedback/LeetCode-Feedback#21240]
The problem description states that the updated board should be returned. There is a note to think about whether the solution can be done in place. The solution template indicates a return type of `None`, but the checker enforces a return type of `List[List[int]]` (which it nonsensically indicates as `integer[][]`). Meanwhile, the checker actually *ignores* the returned value, and instead examines the modified-in-place input. All very confusing.

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
