### ISSUE TITLE
Time Limit Exceeded of Editorial's solution which 'should' be accepted - 209. Minimum Size Subarray Sum

### ISSUE THREAD

**Issue by pechinkin** [LeetCode-Feedback/LeetCode-Feedback#21243]
### LeetCode Username

pechinkin https://leetcode.com/pechinkin/

### Problem number, title, and link

№209. Minimum Size Subarray Sum
https://leetcode.com/problems/minimum-size-subarray-sum/editorial/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug
I'm trying to confirm the solution given in the editorial and it exceeds time limit meanwhile it is said that should be accepted.

(Approach №2)
Submission link (using given solution in editorial but nor being accepted as it is said): https://leetcode.com/problems/minimum-size-subarray-sum/submissions/1201864801/

### Language used for code
C++

### Code used for Submit/Run operation

```
class Solution {
public:
    int minSubArrayLen(int s, vector<int>& nums)
{
    int n = nums.size();
    if (n == 0)
        return 0;
    int ans = INT_MAX;
    vector<int> sums(n);
    sums[0] = nums[0];
    for (int i = 1; i < n; i++)
        sums[i] = sums[i - 1] + nums[i];
    for (int i = 0; i < n; i++) {
        for (int j = i; j < n; j++) {
            int sum = sums[j] - sums[i] + nums[i];
            if (sum >= s) {
                ans = min(ans, (j - i + 1));
                break; //Found the smallest subarray with sum>=s starting with index i, hence move to next index
            }
        }
    }
    return (ans != INT_MAX) ? ans : 0;
}
};
```

### Expected behavior
Well, it was expected to be accepted.
As i know, we have `~1e8` operations per second in C++ and need to use it as our limit. But with `n = 1e5` and `O(n^2)` we have `1e10` operations per second which is a lot more. That's why we have time limit exceeded and need to update editorial to the current constrains.

### Screenshots

<img width="363" alt="Screenshot 2024-03-12 at 22 16 18" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/124191811/9e736d4e-c300-43d6-81f5-6ac472820878">

<img width="609" alt="Screenshot 2024-03-12 at 22 23 07" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/124191811/7ede1d5b-06d2-46a2-8c02-1410412b32d7">

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by pechinkin** [comment]
@wktang im sorry but is it solved?
