### ISSUE TITLE
Editorial issue - 2485. Find the Pivot Integer

### ISSUE THREAD

**Issue by alextwl** [LeetCode-Feedback/LeetCode-Feedback#21251]
### LeetCode Username

alextwl

### Problem number, title, and link

2485. Find the Pivot Integer https://leetcode.com/problems/find-the-pivot-integer/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug

In the 3rd equation of Approach 5: Using Math

> Expanding both sides of the equation:
> 
> $[ x + \frac{x^2}{2} = \frac{nx - x^2 + x + n^2 - nx + n}{2} ]$

The expansion for the left side $x + \frac{x^2}{2}$ is wrong, because $\frac{x(x+1)}{2} = \frac{x^2 + x}{2}$.

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

### Expected behavior

> Expanding both sides of the equation:
> 
> $[ \frac{x^2 + x}{2} = \frac{nx - x^2 + x + n^2 - nx + n}{2} ]$

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by MMKrell** [comment]
Just as a side node, the respective Python code has a coding style error, too. Default methods like sum should be never overwritten by a variable because it can have unintended side effects.

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
