### ISSUE TITLE
Missing test Case - 235. Lowest Common Ancestor of a Binary Search Tree

### ISSUE THREAD

**Issue by SiamRahman29** [LeetCode-Feedback/LeetCode-Feedback#21256]
### LeetCode Username

https://leetcode.com/siamrahman29/

### Problem number, title, and link

235. Lowest Common Ancestor of a Binary Search Tree - https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

Ideally problem should accept when a TreeNode from the given tree is returned but currently it accepts any TreeNode as long as it matches the value of the expected answer.

### Language used for code

Python3

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, x):
#         self.val = x
#         self.left = None
#         self.right = None

class Solution:
    def lowestCommonAncestor(self, root: 'TreeNode', p: 'TreeNode', q: 'TreeNode') -> 'TreeNode':
        def dfs(root, val):
            if not root:
                return
            if root.val == val:
                return [val]
            
            ancestors_1 = dfs(root.left, val)
            ancestors_2 = dfs(root.right, val)
            if ancestors_1:
                ancestors_1.append(root.val)
                return ancestors_1
            if ancestors_2:
                ancestors_2.append(root.val)
                return ancestors_2
        a_1 = dfs(root,p.val)
        a_2 = dfs(root,q.val)
        common=[]
        result = 0
        print(a_1)
        print(a_2)
        for i in a_1:
            for j in a_2:
                if i==j:
                    result = j
                    break
            else:
                continue
            break
        return TreeNode(result)
```

### Expected behavior

Supposed to be rejected but was accepted

### Screenshots

![Screenshot 2024-03-13 113357](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/67052337/d896af3f-4e04-48c4-a5d7-f6b51b9968e2)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

Checkout the constraints: All Node.val are unique.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
