### ISSUE TITLE
Missing Test Case - 2126. Destroying Asteroids

### ISSUE THREAD

**Issue by Nehasatya** [LeetCode-Feedback/LeetCode-Feedback#21257]
### LeetCode Username

Username - Neha Satya

### Problem number, title, and link

2126. Destroying Asteroids https://leetcode.com/problems/destroying-asteroids/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
           The test Case mass = 5 and asteroids = [ 9 , 10 , 4] 
                           leads to the wrong output while using the stack, suggesting that this data structure can not be used for the problem desription, but missing of such kind of testcase allows the solution to get accepted.
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

mass = 5
asteroids = [9,10,4]

### Code used for Submit/Run operation

```
class Solution {
    public boolean asteroidsDestroyed(int mass, int[] asteroids) {

        long m = mass;

        Stack<Integer> stack = new Stack<>();

        for(int i=0;i<asteroids.length;i++)
        {
            stack.push(asteroids[i]);

            while (!stack.isEmpty() && stack.peek() <= m){
                m += stack.pop();
            }
        }

        return stack.isEmpty();

        
    }
}
```

### Expected behavior

This problem should not be allowing to use stack as the edge case can arise in case of the given testcase, but a solution with stack gets accepted successfully.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Hi there,

Your feedback has been instrumental in enhancing the problem. 

To ensure you receive your well-deserved 100 LeetCoins reward, could you kindly provide us with your LeetCode username? This will allow us to credit your account accurately.

Your participation and contributions are valued, and we want to make sure you enjoy the rewards you've earned.

Thank you for being part of the LeetCode community!

Best regards,
LeetCode Team

**Comment by Nehasatya** [comment]
Thank you for considering my suggestion.
User name - Neha Satya
Leetcode ID - nehasatya02

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
