### ISSUE TITLE
Missing Test Case - 1174. Immediate Food Delivery II

### ISSUE THREAD

**Issue by Shivprasad123** [LeetCode-Feedback/LeetCode-Feedback#21255]
### LeetCode Username
https://leetcode.com/shivprasadn123

### Problem number, title, and link
[1174. Immediate Food Delivery II](https://leetcode.com/problems/immediate-food-delivery-ii/)

### Category of the bug
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### Language used for code
MySQL

Test case: 
| delivery_id | customer_id | order_date | customer_pref_delivery_date |
| ----------- | ----------- | ---------- | --------------------------- |
| 1           | 1           | 2019-08-01 | 2019-08-02                  |
| 2           | 2           | 2019-08-02 | 2019-08-02                  |
| 3           | 1           | 2019-08-11 | 2019-08-12                  |
| 4           | 3           | 2019-08-24 | 2019-08-24                  |
| 5           | 3           | 2019-08-21 | 2019-08-22                  |
| 6           | 2           | 2019-08-11 | 2019-08-13                  |
| 7           | null        | 2019-08-09 | 2019-08-09                  |
| 8           | null        | 2019-08-09 | 2019-08-09                  |
| 9           | null        | 2019-08-09 | 2019-08-09                  |

### Code used for Submit/Run operation
```
select ROUND((count(*)*100/(select count( DISTINCT customer_id ) from Delivery)),2) as immediate_percentage 
from Delivery d join 
(select customer_id, MIN(order_date) as mo from Delivery group by customer_id) q 
on (d.customer_id = q.customer_id and d.customer_pref_delivery_date=q.mo)
```

### Expected behavior
should give proper percentage, but expected is coming more then 100%

### Screenshots
<img width="657" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/30628495/dc1aaaf7-9403-48f7-aba2-8bbce5b3b09b">

### Additional context
customer_id with null value is not handled

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
