### ISSUE TITLE
2485. Find the Pivot - Missed parentheses in formula

### ISSUE THREAD

**Issue by andennis** [LeetCode-Feedback/LeetCode-Feedback#21266]
### LeetCode Username
andennis

### Problem number, title, and link
2485. Find the Pivot Integer https://leetcode.com/problems/find-the-pivot-integer/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug
The parentheses have been missed after transformation of arithmetic progression sum formula:

**Approach 3: Binary Search**
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/10621777/2af66442-b6bd-4b4f-98bd-1b0c9d0a35d2)

**Approach 4: Pre-Compute and Cache in a Lookup Table**
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/10621777/20434a7c-72fd-478b-b8b1-c9760eeacbc3)

The divider `2` has been missed` 
**Approach 5: Using Math**
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/10621777/4f05e7f4-3ce9-4e54-aa84-00e60b05ef47)

### Expected behavior
```
n*(n + 1)/2 = (n*n + n)/2 = n*n/2 + n/2
```

### Additional context
The test calculation with Python
```
>>> n = 6
>>> n * (n + 1)/2  # 21 is expected
21.0

>>> n*n + n/2
39.0
>>> (n*n + n)/2
21.0

>>> n + n*n/2
24.0
>>> n/2 + n*n/2
21.0
```

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
