### ISSUE TITLE
Missing Test Case - 1739. Building Boxes

### ISSUE THREAD

**Issue by tonghuikang** [LeetCode-Feedback/LeetCode-Feedback#2127]
#### Your LeetCode username
tonghuikang

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
A solution is accepted but fails on the following test case:

```
288
```

#### Code you used for Submit/Run operation

```python
class Solution:
    def minimumBoxes(self, n):
        x = int((n * 6) ** (1. / 3)) - 1
        n -= x * (x + 1) * (x + 2) / 6
        y = int((n * 2 + 0.25) ** 0.5 + 0.49999999)
        return int(x * (x + 1) / 2 + y)
```

#### Language used for code
Python 3

#### Expected behavior
The solution should not be accepted since it fails on the test case.

#### Screenshots
<img width="1412" alt="Screenshot 2021-01-24 at 2 40 57 PM" src="https://user-images.githubusercontent.com/17105577/105623167-9c725580-5e52-11eb-9544-f4f6724137ed.png">

#### Additional context
This solution is obtained from https://leetcode.com/problems/building-boxes/discuss/1032155/Python-O(1)-Solution

There are many other cases that this solution fails.

**Comment by lc-kay** [comment]
Hi @tonghuikang 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @tonghuikang 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
