### ISSUE TITLE
30. Substring with Concatenation of All Words: Missing Critical Assumtion Description

### ISSUE THREAD

**Issue by Fenardle** [LeetCode-Feedback/LeetCode-Feedback#21277]
It seems the official solution for this problem s is making an assumtion that every substring starts at n * wordLength, which is not in the problem description

The official solution won't be correct for the following input:

s = "ooooooooooooooooooooooooooooooo" word = ["oo", "oo"]

In this case, the answer should be [0,1,2,3,4....].

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by Fenardle** [comment]
> Hello,
> 
> Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:
> 
> The code submission link you submitted led to the observed result.
> 
> Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!
> 
> Best regards LeetCode Support Team

You may run the following program that uses the official approach to solve this probelm. The solution will pass all the official test cases but not when the test case is "s = "ooooooooooooooooooooooooooooooo" word = ["oo", "oo"]"

`package main

import "fmt"

func findSubstring(s string, words []string) []int {
	result := make([]int, 0)
	wordCount := make(map[string]int)
	distinctWords := 0
	for _, word := range words {
		wordCount[word]++
		if wordCount[word] == 1 {
			distinctWords++
		}
	}
	wordLength := len(words[0])
	totalLength := wordLength * len(words)
	for start := 0; start < wordLength; start++ {
		for word := range wordCount {
			delete(wordCount, word)
		}
		for _, word := range words {
			wordCount[word]++
		}
		matchingWords := 0
		for i := start; i+wordLength-1 < len(s); i += wordLength {
			currentWord := s[i : i+wordLength]
			if i >= totalLength {
				removedWord := s[i-totalLength : i-totalLength+wordLength]
				if _, found := wordCount[removedWord]; found {
					wordCount[removedWord]++
					if wordCount[removedWord] == 1 {
						matchingWords--
					}
				}
			}
			if _, found := wordCount[currentWord]; found {
				wordCount[currentWord]--
				if wordCount[currentWord] == 0 {
					matchingWords++
				}
			}
			if matchingWords == distinctWords {
				result = append(result, i-totalLength+wordLength)
			}
		}
	}
	return result
}

func main() {
	s := "ooooooooooooooooooooooooooooooo"
	words := []string{"oo", "oo"}
	result := findSubstring(s, words)
	fmt.Println("Result indices:", result)
}
`

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.
The above code received Compile error. 

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by Fenardle** [comment]
> Hello,
> 
> Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:
> 
> The code submission link you submitted led to the observed result. The above code received Compile error.
> 
> Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!
> 
> Best regards LeetCode Support Team

If you submit the code all the test cases will pass: [submission link](https://leetcode.com/problems/substring-with-concatenation-of-all-words/submissions/1210347169)
However, if you run the program I provide, you'll find the solution is not correct:
<img width="1725" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/59411063/5c46032f-63e5-4fdb-ba13-4a7744e98689">

**Comment by Fenardle** [comment]
> Joyce_Ndisya commented: Hello there,
> 
> Checking now, your code is returning the correct answer, even though it looks different from the Expected. Because the question mentioned, "You can return the answer in **any order**." Please see the screenshot attached for your reference.
> 
> I hope this helps. Please let us know if you have any questions.
> 
> Regards, Joyce

The correct answer should be `[0, 1, 2, 3, 4, 5...]` instead of `[0, 2, 4, 6, 8...]`
