### ISSUE TITLE
Contest Issue  (Held on 3/9/2024) - Weekly Contest 388, 3074. Apple Redistribution into Boxes

### ISSUE THREAD

**Issue by jgddesigns** [LeetCode-Feedback/LeetCode-Feedback#21272]
### LeetCode Username

jgddesigns

### Problem number, title, and link

Weekly Contest 388, 3074. Apple Redistribution into Boxes

### Category of the bug
- [x] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

When testing the code I wrote for the contest, the output matched the expected result. When I submitted the same code for judging under the same conditions, the output was deemed incorrect.

### Language used for code

Python

### Code used for Submit/Run operation

```
class Solution(object):
    def minimumBoxes(self, apple, capacity):
        """
        :type apple: List[int]
        :type capacity: List[int]
        :rtype: int
        """
        
        sum = 0
        for count in apple:
            sum += int(count)
          
        ret = self.checkCount(sum, capacity)
        print(ret)
        return len(ret)



        
        
    def checkCount(self, sum, capacity, cap_arr=[]):
        highest = 0
        amount = 0

        if len(capacity) > 0:
          for i in range(len(capacity)):
              if capacity[i] >= highest:
                  highest = capacity[i]
                  pos = i

          cap_arr.append(highest)
          try:
              capacity.pop(pos)
          except:
              pass
          


          for count in cap_arr:
              amount += count 

        else:
          return False
    

        if amount >= sum:
          return cap_arr
        else: 
            return self.checkCount(sum, capacity, cap_arr)

```

### Expected behavior

It was my first contest, so I could be wrong about my expectations. It does seems incorrect based upon what the description of the test case  and judged submission is. They seem the same. and my solution should be correct. Does the judged submission include other factors that the test case doesn't? I can't tell for certain, but this doesn't seem right.

### Screenshots

![Screenshot (155)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/67573303/ebdba30d-f886-42b7-91e0-763ddca93e25)
![Screenshot (156)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/67573303/2b018137-3b5d-44da-a2e6-eeab82f8ac58)

### Additional context

My first leetcode contest. I'm new to the site.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us!

When comparing the outcomes of "Run Code" and "Submit" for a specific test case, it's evident that the input and expected values are the same, yet the output values differ.

To assist you further, we have documented the causes and potential solutions for this type of issue in detail. You can find this information in our knowledge base article: [Test Case Discrepancy - Causes and Solutions](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-).

I hope this resource proves helpful. Should you have any additional questions or need further clarification on this case, please do not hesitate to reach out to us. We're here to assist you!

Best regards,
LeetCode Support Team
