### ISSUE TITLE
Notes before starting - Video not wokring

### ISSUE THREAD

**Issue by ak98neon** [LeetCode-Feedback/LeetCode-Feedback#21274]
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/16827462/69990cbe-4ad3-4934-a505-10e15800aef7)

https://leetcode.com/explore/featured/card/leetcodes-interview-crash-course-data-structures-and-algorithms/715/introduction/4656/

**Comment by LC-Pam** [comment]
Hello,

Thank you for providing your feedback.

Please note that our GitHub repository primarily addresses content and solution-related issues. To ensure a prompt response and effective resolution for feature, function, course access, network error or product-related feedback, we kindly encourage you to submit such inquiries through our Zendesk Support Channel:

[LeetCode Support](https://leetcode.com/support), select "Technical Support".

Our dedicated support agents typically respond within 24 hours and promptly report submitted issues to the appropriate departments for investigation.

We greatly appreciate your ongoing support and value your contributions to enhancing the LeetCode experience.

Best regards,
LeetCode Support Team
