### ISSUE TITLE
Missing Test Case- 1673 Find the Most Competitive Subsequence

### ISSUE THREAD

**Issue by abhi031098** [LeetCode-Feedback/LeetCode-Feedback#2128]
#### Your LeetCode username
abhi_u_03

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Test case:
[1,1,1,1,1,1,1,1,0,0]
5
My Output
[1,1,1,1,0]

Expected Outcome:
[1,1,1,0,0]

The missing test case is all the equal values in the arrays are equal but not minimum and the last few elements as lesser than these equal elements. For ex. Till index 8 array value equals to 1 and Index (9 as well as 10) being equal to 0. As the minimum requirement is to have K elements in the answer and if minimum elements are towards the end like last or second last the current test cases fail to test the above situation **if someone runs a loop for equal numbers** and the wrong answer is being submitted. The solution was Accepted as this test case is missing.

#### Code you used for Submit/Run operation

```
// Find the Most Competitive Subsequence
class Solution {
public:
    vector<int> mostCompetitive(vector<int>& nums, int k) {
        vector <int> a;
        int i=0;
        int index_minimum=0;
        int total_inserted=0;
        int mini= nums[0];
        bool decreased = false;
        //cout<< nums.size();
        for(int i=0;i<nums.size()-1;i++)
        {
            if(nums[i]>nums[i+1]){
                decreased = true;
                break;
            }    
        }
        if(!decreased)
        {
            for(int i=0;i<k;i++)
                a.push_back(nums[i]);
        }
        else
        {
            while(total_inserted!=k)
            {
                for(i = index_minimum+1; i<=nums.size()-k+total_inserted; i++)
                {
                    if(mini>nums[i])
                    {
                        mini = nums[i];
                        index_minimum = i;
                    }
                }
                a.push_back(mini);
                total_inserted++;
                i=index_minimum+1;
                while(i<nums.size()&& nums[i]==nums[i-1] && total_inserted!=k)
                {
                     if(nums[i]>nums[nums.size()-1] && total_inserted==k-1)
                     {
                          a.push_back(nums[nums.size()-1]);
                          total_inserted++;
                     }
                    else {
                        a.push_back(nums[i]);
                     //cout<<"Special INDEX"<<i;
                     total_inserted++;
                     index_minimum = i;
                     i++;
                    }
                     
                }

                mini= INT_MAX;
            }
        }
        
        return a;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Test case:
[1,1,1,1,1,1,1,1,0,0]
5
Output
[1,1,1,1,0]

Expected:
[1,1,1,0,0]

There should be a test case that prevents such looping of equal numbers and give incorrect answers to such submissions where the minimum number towards the end are ignored due to the loop. **(Such Cases arise if there are equal numbers and the concept of finding a minimum number with linear complexity is used which is a very common solution. Another case is where one can just check the last number to avoid TLE in a big test case in an otherwise perfectly running solution (85/86) TestCases passed with the last big test manipulated by checking only the last number of sorted array**.
To be specific this part of the code
```
if(nums[i]>nums[nums.size()-1] && total_inserted==k-1)
                     {
                          a.push_back(nums[nums.size()-1]);
                          total_inserted++;
                     }
```

Hence for both the aforementioned cases, I believe the test case should be added to prevent unnecessary acceptance of looped solution with ignorance towards the minimum element of the array at a few last positions.

#### Screenshots

![image](https://user-images.githubusercontent.com/42272328/105623533-8491d600-5e40-11eb-94b5-b75dc9f1d637.png)

**Comment by lc-kay** [comment]
Hi @abhi031098 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @abhi031098 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
