### ISSUE TITLE
Divide 2 Integer test case problem 

### ISSUE THREAD

**Issue by AirbusA321NX** [LeetCode-Feedback/LeetCode-Feedback#21285]
In Test Case dividend is -2147483648 and divisor is -1 and we have to divide dividend by divisor  without using divide(/) operator so -2147483648/-1  = 2147483648 but expected outcome of test case is 2147483647
Please Fix It 
It may be due to range of integer as dividend is taken as integer and max range is -2147483647 to 2147483647 so modify the function by taking the argument as long long int or long int which will extend its range 

![leetcode](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/136959585/3b24e6bc-5732-455f-bb3d-3002071768ee)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team
