### ISSUE TITLE
Bug on submission in question 17

### ISSUE THREAD

**Issue by Denellyne** [LeetCode-Feedback/LeetCode-Feedback#21280]
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

If I make global variables and use them inside a recursive function the function doesnt do what it's expected ,but If i put those same global variables inside the Solution class as private and the function too , the function produces the expected output.

##  Working
```
class Solution {
private:
vector<vector<string>> numPad = {{"a","b","c"},{"d","e","f"},{"g","h","i"},{"j","k","l"},{"m","n","o"},{"p","q","r","s"},{"t","u","v"},{"w","x","y","z"}};
vector<string> answer;

string getPermut(int j,string str,string digits){

    if(digits.length() == 1 && j < numPad[digits[0] - '0'- 2].size()){ 
        answer.push_back(str + numPad[digits[0] - '0'- 2][j]);

        if(j+1 == numPad[digits[0] - '0'- 2].size()) return ""; 
        return getPermut(j+1,str,&digits[0]);
    }
    for(int i = 0;i < numPad[digits[0] - '0'- 2].size();i++)
        getPermut(0,str + numPad[digits[0] - '0'- 2][i],&digits[1]);
    
    return "";
}
public:
    vector<string> letterCombinations(string digits) {
        if(digits.length() == 0) return {};
        if(digits.length() == 1) return numPad[digits[0] - '0'- 2];

        getPermut(0,"",digits);

        return answer;

    }
};


```

## Not Working
```
vector<vector<string>> numPad = {{"a","b","c"},{"d","e","f"},{"g","h","i"},{"j","k","l"},{"m","n","o"},{"p","q","r","s"},{"t","u","v"},{"w","x","y","z"}};
vector<string> answer;

string getPermut(int j,string str,string digits){

    if(digits.length() == 1 && j < numPad[digits[0] - '0'- 2].size()){ 
        answer.push_back(str + numPad[digits[0] - '0'- 2][j]);

        if(j+1 == numPad[digits[0] - '0'- 2].size()) return ""; 
        return getPermut(j+1,str,&digits[0]);
    }
    for(int i = 0;i < numPad[digits[0] - '0'- 2].size();i++)
        getPermut(0,str + numPad[digits[0] - '0'- 2][i],&digits[1]);
    
    return "";
}

class Solution {
public:
    vector<string> letterCombinations(string digits) {
        if(digits.length() == 0) return {};
        if(digits.length() == 1) return numPad[digits[0] - '0'- 2];

        getPermut(0,"",digits);

        return answer;

    }
};


```

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

Please ask your question in the discussion forum.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
