### ISSUE TITLE
Missing Test Case for question 14. Longest Common Prefix

### ISSUE THREAD

**Issue by gautam-andani** [LeetCode-Feedback/LeetCode-Feedback#21283]
### Problem number, title, and link

[14. Longest Common Prefix](https://leetcode.com/problems/longest-common-prefix/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

- [ ] Editorial
- [ ] Programming language support

### Language used for code

Python

### [Code used for Submit/Run operation](https://leetcode.com/problems/longest-common-prefix/solutions/3273176/python3-c-java-19-ms-beats-99-91)

```
class Solution:
    def longestCommonPrefix(self, v: List[str]) -> str:
        ans=""
        v=sorted(v)
        first=v[0]
        last=v[-1]
        for i in range(min(len(first),len(last))):
            if(first[i]!=last[i]):
                return ans
            ans+=first[i]
        return ans 
```

### Expected behavior

This code should not have been passed all test cases and gives false answer to underlying leetcode problem.
The solution only compares the first and last strings which is different from what was expected of question to find the longest common prefix which should have compared all strings in O(n) minimum time but this solution does it in O(1) time.
Therefore I suggest this test case to prevent such solutions from passing.

`strs = ["bars", "bartender", "potato"]`

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
