### ISSUE TITLE
Missing Test Case - 53. Maximum Subarray

### ISSUE THREAD

**Issue by guptaNikhil89** [LeetCode-Feedback/LeetCode-Feedback#21282]
### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [x] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

**Comment by guptaNikhil89** [comment]
[-2,1,-3,4,-1,2,1,-5,4] in output 2 -> (my output) but my code to output -> 6 (expatation)

**Comment by gautam-andani** [comment]
Provide question number, leetcode username, your code (else your request might be closed without looking)
