### ISSUE TITLE
Missing test-case , 1171 Remove Zero Sum Consecutive Nodes from Linked List

### ISSUE THREAD

**Issue by rghvsomani** [LeetCode-Feedback/LeetCode-Feedback#21293]
### LeetCode Username
rghvv (https://leetcode.com/rghvv/)

### Problem number, title, and link

1171. Remove Zero Sum Consecutive Nodes from Linked List https://leetcode.com/problems/remove-zero-sum-consecutive-nodes-from-linked-list/

### Category of the bug
Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug

Test-case :- [9,-5,-3,8,4,2,-7,-4,1]
Expected output for this is shown as :- [9,4,2,-7,-4,1]
But Expected output should be [9,-5,1] 
Explanation (Consider indexing starting from 0):-   sum till of index 1 is 4 and for index 7 gets same sum as 4 so skipping nodes from index (1,7] i.e pointing next of node with index 1 to node with index 8 should be answer for following case .

### Code used for Submit/Run operation

```
class Solution {
public:
    ListNode* removeZeroSumSublists(ListNode* head) {
        ListNode* dummy = new ListNode(0);
        dummy->next = head;
        int prefix = 0;
        unordered_map<int, ListNode*> seen;
        for (ListNode* i = dummy; i; i = i->next) {
            seen[prefix += i->val] = i;
        }
        prefix = 0;
        for (ListNode* i = dummy; i; i = i->next) {
            i->next = seen[prefix += i->val]->next;
        }
        return dummy->next;
    },
};
```

### Expected behavior

Test-case :-        [9,      -5,        -3,        8,       4,        2,         -7,      -4,      1]
Assume -Index : [0,      1,          2,        3,       4,        5,           6,       7,       8]
prefix-sum :        [9 ,     4 ,         1  ,      9,       13,     15,          8,       4,       5] 
Online Judge answer :- [9,4,2,-7,-4,1]
Expected answer :- [9,-5,1]
(Consider index starts from 0 for explanation)
Existing solutions starts prefix sum from index 0 and and encounters same prefix sum on indexes 0 & 3 so skips nodes between [1,3] inclusive but they aren't considering node which got skipped may have better reach to skip nodes i.e can skip more nodes and can make existing Linked list even shorter , so instead of skipping node from index [1,3] it is better to remove node from index [2,7] inclusive .

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us. To facilitate a thorough assessment of the reported issue and to successfully reproduce it on our end, we kindly request the following information:

The code submission link you submitted led to the observed result.

Your cooperation in providing this information is invaluable and greatly assists us in addressing the matter effectively. We appreciate your time and support in resolving this issue. If you have any additional questions or concerns, please do not hesitate to let us know. We're here to help!

Best regards
LeetCode Support Team

**Comment by rghvsomani** [comment]
Link of Accepted solution as per online judge : https://leetcode.com/submissions/detail/1203279799/
I have also mentioned code used to run test-case above in section "**Code used for Submit/Run operation**"

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

Answer [9, -5, 1] is also accepted.

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
