### ISSUE TITLE
Missing Test Case - 2126. Destroying Asteroids

### ISSUE THREAD

**Issue by marcociav-exmergo** [LeetCode-Feedback/LeetCode-Feedback#21301]
### LeetCode Username
marcomarco

### Problem number, title, and link
[2126. Destroying Asteroids](https://leetcode.com/problems/destroying-asteroids/)

### Category of the bug
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug
The Monotonic Stack approach to this problem passes all provided test cases.
However if I input this test case.

mass = 10
asteroids = [11,19,3]

The solution fails this test.
The output of the code is "false", while the correct solution to this is "true"

### Language used for code
Python

### Code used for Submit/Run operation

```
class Solution:
    def asteroidsDestroyed(self, mass: int, asteroids: List[int]) -> bool:
        stack = []

        for asteroid in asteroids:
            stack.append(asteroid)
            while stack and stack[-1] <= mass:
                extra = stack.pop()
                mass += extra

        return not stack
```

### Expected behavior
The expected behavior is that by adding this extra test, the Monotonic Stack solution should not pass all tests

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

Your feedback has been instrumental in enhancing the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
