### ISSUE TITLE
Missing Test Case - 9. Palindrome Number

### ISSUE THREAD

**Issue by mnbatra** [LeetCode-Feedback/LeetCode-Feedback#21308]
### LeetCode Username

amanbatra

### Problem number, title, and link 

9.
Palindrome Number
https://leetcode.com/problems/palindrome-number/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ x ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

`-0` should fail, whereas it returns true.

### Language used for code

Python

### Code used for Submit/Run operation

```
class Solution:
    def isPalindrome(self, x: int) -> bool:
        if x < 0:
            return False
        rev = 0
        num = x
        while num!=0 :
            rev = rev*10 + num%10
            num = num//10
        return rev == x

```

### Expected behavior

`-0` test case should return FALSE

### Screenshots

<img width="392" alt="Screenshot 2024-03-14 at 3 16 04 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/38990408/a4d046d5-9a79-449f-a988-929f9ba94e4a">

**Comment by shrutik-1712** [comment]
In Python, the integer type does not support negative zero (-0). The concept of negative zero is not meaningful in integer arithmetic. In both languages, zero is represented as 0 and is considered neither positive nor negative.

```python
x = -0
print(x)  # Output will be 0
print(x == 0)  # Output will be True
print(x == -0)  # Output will be True
```

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team
