### ISSUE TITLE
Follow-up of 75. Sort Colors Needs to Be Updated

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#2130]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
The problem [75. Sort Colors](https://leetcode.com/problems/sort-colors/) has two follow-up questions.
- Could you solve this problem without using the library's sort function?
- Could you come up with a one-pass algorithm using only `O(1)` constant space?

The second follow-up question that requires to use a one-pass algorithm using only constant space is a good follow-up question. However, the first follow-up question is NOT a good follow-up question.

For this problem, it is meaningless to use the library's sort function. If this problem is asked during an interview, obviously the interviewer won't accept a solution that uses the library's sort function.

Therefore, the first follow-up question should be the normal requirement of this problem. That is, as the normal requirement of this problem, the interviewee isn't allowed to use the library's sort function.

There should be only one follow-up question, which is:
Could you come up with a one-pass algorithm using only `O(1)` constant space?

#### Expected behavior
The normal requirement should contain a statement: "Do not use the library's sort function."
There should be only one follow-up question: "Could you come up with a one-pass algorithm using only `O(1)` constant space?"

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for your time. The team reviewed your report and concluded that the follow up is fine as it is. We appreciate your support!
