### ISSUE TITLE
[MISSING HINTS] - 238. Product of Array Except Self

### ISSUE THREAD

**Issue by akankshaaa013** [LeetCode-Feedback/LeetCode-Feedback#21322]
### LeetCode Username
https://leetcode.com/gakanksha013/

### Problem number, title, and link
238. Product of Array Except Self https://leetcode.com/problems/product-of-array-except-self/

### Category of the bug
- [ ] Missing Hints

### Description of the bug
The issue lies in the absence of hints provided for the problem. Hints are essential guidance for problem-solving strategies. Their absence impacts user experience, hindering understanding and optimal solution development.

### Language used for code
Java

### Code used for Submit/Run operation
```
public int[] productExceptSelf(int[] nums) {
        int n = nums.length;
        int left[] = new int[n];
        int right[] = new int[n];
        int ans[] = new int[n];

        left[0] = 1;
        for (int i = 1; i < n; i++) {
            left[i] = left[i - 1] * nums[i - 1];
        }

        right[n - 1] = 1;
        for (int i = n - 2; i >= 0; i--) {
            right[i] = right[i + 1] * nums[i + 1];
        }

        for (int i = 0; i < n; i++) {
            ans[i] = left[i] * right[i];
        }

        return ans;
    }
```

### Expected behavior
Provide Hints to guide the users.

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/130728236/28448141-f0f2-4aa9-a561-6989e91502d7)

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/130728236/908a5fe4-e5fd-4484-9be4-fa553381eb76)

**Comment by akankshaaa013** [comment]
Such hints can be added:

Hint1:
Think how you can efficiently utilize prefix and suffix products to calculate the product of all elements except self for each index? Can you pre-compute the prefix and suffix products in linear time to avoid redundant calculations?

Hint2:
Can you minimize additional space usage by reusing memory or modifying the input array to store intermediate results?

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team
