### ISSUE TITLE
230. Kth Smallest Element in a BST

### ISSUE THREAD

**Issue by Glazomer** [LeetCode-Feedback/LeetCode-Feedback#2132]
#### Your LeetCode username
dan2000kr

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
You test cases only include node with unique values from range (0 to n-1) or (1 to n), so it's easy to cheat them

#### Code you used for Submit/Run operation

```
class Solution {
  public:
    int kthSmallest(TreeNode* root, int k) {
      while (root->left != nullptr){
        root = root->left;
      }
      return k - !root->val;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Include input:
[4,2,5,null,3]
1

#### Screenshots

![Screenshot 2021-01-24 at 15 51 05](https://user-images.githubusercontent.com/41964489/105630748-faf00180-5e5b-11eb-875d-bcbd119097d9.png)

**Comment by lc-kay** [comment]
Hi @Glazomer 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Glazomer 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
