### ISSUE TITLE
Missing Test Case - 238. Product of Array Except Self

### ISSUE THREAD

**Issue by Luci2015** [LeetCode-Feedback/LeetCode-Feedback#21321]
### LeetCode Username
Lucian-N

### Problem number, title, and link
238. Product of Array Except Self: [here](https://leetcode.com/problems/product-of-array-except-self/description/)

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
my solution goes beyond O(n) time complexity in a special scenario and it's accepted for lack of test cases

### Language used for code
Python 3

### Code used for Submit/Run operation

```
    def productExceptSelf(self, nums: List[int]) -> List[int]:
        fin = [1 for _ in nums]
        fin[0] = math.prod(nums[1:])
  
        for i in range(1, len(nums)):
            if nums[i] == 0: 
                fin[i] = math.prod(nums[: i]) * math.prod(nums[i + 1: ])
            else:
                fin[i] = (fin[i - 1] // nums[i]) * nums[i - 1]
        return fin
```

### Expected behavior
This should return TLE if you replace for example in test case 18 all -1 numbers with 0 instead. The more 0s present, the higher the time complexity because of second inner 'for' loop inside the 'math.prod'

**Comment by Luci2015** [comment]
submission link [here](https://leetcode.com/problems/product-of-array-except-self/submissions/1204265264/)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team
