### ISSUE TITLE
Missing Test Case - 1071. Greatest Common Divisor of Strings

### ISSUE THREAD

**Issue by mahek-savani** [LeetCode-Feedback/LeetCode-Feedback#21332]
### LeetCode Username
MahekSavani

### Problem number, title, and link
1071. Greatest Common Divisor of Strings https://leetcode.com/problems/greatest-common-divisor-of-strings/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

There is an edge case that is not included in the test cases I believe. So, when str1 is ALEET and str2 is ACODE my provided code as below would give the Greatest Common Divisor of Strings value "ALEET" which is wrong since the right answer is empty string since there is no possible GCD of strings but my solution was still accepted upon submission.

### Language used for code

Python

### Code used for Submit/Run operation

```python
class Solution:
    def gcdOfStrings(self, str1: str, str2: str) -> str:
        if str1[0]!=str2[0]:
            return ""
        gcd=""
        for i in range(1, min(len(str1), len(str2))+1):
            if str1[:i]*(len(str1)//i) == str1 and str2[:i]*(len(str2)//i) == str2:
                gcd = str1[:i]
        return gcd
```

### Expected behavior

The expected behavior is that my solution should been rejected since it gives the wrong output for the given test case.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team
