### ISSUE TITLE
Missing Test Case - 162. Find Peak Element

### ISSUE THREAD

**Issue by SinghKrAshish** [LeetCode-Feedback/LeetCode-Feedback#21349]
### LeetCode Username
imsinghak

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [x] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### The given problem does not cover every type of test cases. It  only gives correct answer if there is a peak element at both the sides of the array. 
Suppose, the input is the array [1,2,1,4,5,6,7,8,12], then the peak element is 2. But the problem identifies 8 as the expected answer and it shows correct.

### Code used for Submit/Run operation

```
class Solution {
public:
    int findPeakElement(vector<int>& nums) {
        
        int low = 0;
        int high = nums.size()-1;
        while(low<=high){
            int mid = low+(high-low)/2 ;
            if( mid-1>=low && nums[mid-1]>nums[mid] )
                high = mid-1;
            else if( mid+1<=high && nums[mid]<nums[mid+1] )
                low = mid+1;
            else
                return mid;
        } 
        return -1;
    }
};
```

### Expected behavior

The answer should be 2.

### Screenshots

<img width="453" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/100891627/0ee52069-5408-4865-8970-02a05369dcb0">

**Comment by LC-Pam** [comment]
Thank you for reaching out. 

After checking, our judge system functions properly. 

If you encounter any further issues or need assistance, please don't hesitate to let us know. 

Best Regards,
The Leetcode Team
