### ISSUE TITLE
Report for ambigous result for test case

### ISSUE THREAD

**Issue by singhpriansh** [LeetCode-Feedback/LeetCode-Feedback#21359]
### Cost not being minimised in the test case result...
1. Problem : 3081. replace-question-marks-in-string-to-minimize-its-value

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### 

### Language used for code
C++

### Code used for Submit/Run operation

```
class Solution {
public:
    string minimizeStringValue(string s) {
        int len = s.length();
        int arr[26] = {0};
        for(int i=0;i<len;i++) {
            if (s[i]!='?')
                arr[s[i]-'a']++;
        }
        int itr = 0,val=0;
        for(int i=0;i<len;) {
            if (s[i]=='?') {
                while(itr<26 and arr[itr]>val){
                  itr++;
                }
                if (itr<26){
                    s[i] = (char)('a'+ itr);
                    arr[itr]++;
                    i++;
                } else {
                    val++;
                    itr = 0;
                }
            }else {
              i++;
            }
        }
        return s;
    }
};

```

### Expected behavior
For the test case 
- "abcdefghijklmnopqrstuvwxy??"
- Expected outcome is : "abcdefghijklmnopqrstuvwxyaz" , but this does not minimize the result..as a is used twice, whereas the rsult should be : "abcdefghijklmnopqrstuvwxyza"

**Comment by stormsunshine** [comment]
For the output you provided, is "a" used once or twice? Can you check?

**Comment by singhpriansh** [comment]
> For the output you provided, is "a" used once or twice? Can you check?

Yes its once already in the given string "abcdefghijklmnopqrstuvwxy??" and z is not used ..so inserting z on first place would be  of cost zero. Then since all alphabets are used we can use a as inserting any "aphabet" would cost to one but we insert one for it to be loxicographically smallest...

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

Please check your code. 

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
