### ISSUE TITLE
Missing Test Case - 3083. Existence of a Substring in a String and Its Reverse

### ISSUE THREAD

**Issue by adiiidubey** [LeetCode-Feedback/LeetCode-Feedback#21375]
### LeetCode Username 
 adiiidubey

### Problem number, title, and link
[3083. Existence of a Substring in a String and Its Reverse](https://leetcode.com/problems/existence-of-a-substring-in-a-string-and-its-reverse/)

### Category of the bug
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Description of the bug
This problem is showing incorrect result for testcase "codhoc" . It is showing expected result  should be true, but acc to my program logic answer is false but my code is already submitted on leetcode . How it can be submitted when it is getting wrong with this test case.

### Language used for code
C++

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```
class Solution {
public:
    bool isSubstringPresent(string s) {
        for(size_t i = 1; i < s.length(); ++i)
            if(s[i] == s[i-1] || s[i-1] == s[i+1])
                return true;
        return false;
    }
};

### Expected behavior

![Screenshot (29)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/150577450/2945a5db-fe2c-4320-9ad9-ac74b7188bbc)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team
