### ISSUE TITLE
数据库第185题，执行代码后的 [预期结果] 存在错误

### ISSUE THREAD

**Issue by LuotersDemo** [LeetCode-Feedback/LeetCode-Feedback#2139]
数据库第185题：部门工资前三高的所有员工。执行代码后的 [预期结果] 存在错误，没有进行分组排序，导致网友正确的代码提交报错。

**Comment by feiceh** [comment]
感谢反馈，请尽可能详细地描述问题，建议把遇到的问题按 issue 模板提交，将信息提供完整才能有助于快速验证和精准的定位。
同时也可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/)「讨论」，将疑问发布在对应的社区中，与大家一同交流，以获得更加有效的支持和帮助。
