### ISSUE TITLE
97. Interleaving String

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#214]
**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
The 2nd approach of the question in solution gives incorrect time and space complexity.

Complexity Analysis

Time complexity : O(2^(m+n)) m is the length of s1 and n is the length of s2.
Space complexity : O(m+n) The size of stack for recursive calls can go upto m+n.

**Expected behavior**
Time complexity : O(m * n)
There are m * n unique states for the problem and we are doing O(1) work for each of them.

Space complexity : O(m * n)
The actual space complexity is O(m * n+m+n) but quadratic term dominates as m and n increase and so asymptotic notation dictates only O(m * n) to be considered as the space complexity.

**Comment by CooperCooperCooper** [comment]
Hi @leet212,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
