### ISSUE TITLE
Missing Test Case - 1171. Remove Zero Sum Consecutive Nodes from Linked List

### ISSUE THREAD

**Issue by shadan1234** [LeetCode-Feedback/LeetCode-Feedback#21407]
LeetCode username- shadan12

[1171. Remove Zero Sum Consecutive Nodes from Linked List](https://leetcode.com/problems/remove-zero-sum-consecutive-nodes-from-linked-list/)

Category of the bug

### Category of the bug
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

Description of the bug
For the test case [1,0,0,-1,2,-1,0] , I am getting a WA , although the problem statement clearly says any possible answer is acceptable ,but still my ouptut which is [2,-1,0] is getting a WA, it is showing correct answer as [2,-1]
Actually the complier should give correct answer in both the possiblities.

Language used for code
C++

```

/**
 * Definition for singly-linked list.
 * struct ListNode {
 *     int val;
 *     ListNode *next;
 *     ListNode() : val(0), next(nullptr) {}
 *     ListNode(int x) : val(x), next(nullptr) {}
 *     ListNode(int x, ListNode *next) : val(x), next(next) {}
 * };
 */
class Solution {
public:
    ListNode* removeZeroSumSublists(ListNode* head) {
        ListNode* dn=new ListNode(0);
        dn->next=head;
        int ps=0;
        map<int,ListNode*>mp;
        while(head!=NULL){
          ps+=head->val;
          if(ps==0){
            dn->next=head->next;
          }
         else if(mp.find(ps)!=mp.end()){
            int aisehi=ps;
            ListNode* temp=mp[ps];
            ListNode* loop=temp->next;
            while(loop!=head){
                aisehi+=loop->val;
                mp.erase(aisehi);
                loop=loop->next;
            }
            temp->next=head->next;
           
          }else
            mp[ps]=head;
          head=head->next;
        }

        return dn->next;
    }
};
```

 Expected behavior
Expected behavior should have been Correct answer , as the problem says any answer after removal of consecutive node is acceptable.

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/122110545/6ec48c27-182a-4f60-881e-568084e20679)

### Additional context
Test case -> [1,0,0,-1,2,-1,0]
possible answer should be both -> [2,-1,0] and [2,-1].
Submission link -> https://leetcode.com/problems/remove-zero-sum-consecutive-nodes-from-linked-list/submissions/1207591661/

**Comment by ShaishavJogani** [comment]
Hello, I don't think the output should be [2,-1,0]. Question states that you need to removed sublist with sum = 0. Last node with size 1, has a sum=0. So, you need to remove it.  I believe issue is with how you initialize  `ps` and ` if(ps==0){
            dn->next=head->next;
          }`

**Comment by shadan1234** [comment]
@ShaishavJogani  thank you for the help, i only thought that the nodes needs to be summed to get 0 ,but overlooked that nodes with value 0 can also exist.
