### ISSUE TITLE
Missing Test Case - 1437. Check If All 1's Are at Least Length K Places Away

### ISSUE THREAD

**Issue by Stroper111** [LeetCode-Feedback/LeetCode-Feedback#2140]
#### Your LeetCode username

Stroper111

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language

#### Description of the bug

The test cases are missing the possibility of starting with a number of zeros smaller than k.

#### Code you used for Submit/Run operation

```python
class Solution:
    def kLengthApart(self, nums: List[int], k: int) -> bool:
        if k == 0: return True
        if not nums: return True
        
        
        current, count = nums[0], 1
        
        for number in nums[1:]:
            if number == current:
                count += 1
                
            else:
                if current == 1 and count != 1:
                    return False
                if current == 0 and count < k:
                    return False
                current, count = number, 1
        return True
        
```

#### Language used for code

Python

#### Expected behavior

For example the test case:

```
[0,1, 0,0,1,0,0,1]
2
```

Should return `True`, while my code return `False`, but my solution is till Accepted

#### Screenshots

![image](https://user-images.githubusercontent.com/43541700/105697235-9c329280-5f04-11eb-82d0-538a3bc2ca3e.png)

**Comment by stormsunshine** [comment]
Hi @Stroper111 , the problem number should be 1437, not 1548.
The link to this problem is [1437. Check If All 1's Are at Least Length K Places Away](https://leetcode.com/problems/check-if-all-1s-are-at-least-length-k-places-away/).

**Comment by Stroper111** [comment]
I updated the question number, I just pressed on `Contribute` on the `Week 4: January 22nd - January 28th` ([question link](https://leetcode.com/explore/challenge/card/january-leetcoding-challenge-2021/582/week-4-january-22nd-january-28th/3616/), which gives the number `1548`.

**Comment by lc-kay** [comment]
Hi @Stroper111 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Stroper111 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
