### ISSUE TITLE
Problem in examples - 8. String to Integer (atoi)

### ISSUE THREAD

**Issue by z1ne2wo** [LeetCode-Feedback/LeetCode-Feedback#2141]
#### Your LeetCode username
z1ne2wo

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
The description provides such the function interface: `myAtoi(string s)`
Interfaces for all languages ​​is consistent with the description: uses `s` as variable name
But for examples uses `str` as variable name, there is a bit inconsistent, maybe there should be `s` too?

Note: based on the solution and old discussions: at some point the interface was changed from `myAtoi(string str)` to `myAtoi(string s)`

#### Screenshots
![Screenshot from 2021-01-25 13-54-19](https://user-images.githubusercontent.com/47155788/105696929-f3406380-5f14-11eb-90c4-a002d220b781.png)

**Comment by lc-kay** [comment]
Hi @z1ne2wo 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @z1ne2wo 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
