### ISSUE TITLE
Missing Test Case - 26. Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by anas40** [LeetCode-Feedback/LeetCode-Feedback#2142]
#### Your LeetCode username

anas40

#### Category of the bug
- [ ] Solution

#### Description of the bug

The question demand to remove the duplicate elements, however it is only checking for the elements which are in the range of returned length.
for ex- [1,1,2,2,3,3] 
if I return the length as 3 and do modification like this [1,2,3,2,3,3], it is accepting the solution
but as question demands that the elements should be deleted
it should only accept a solution like - [1,2,3]

My code has the line to remove the elements, but it does not matter whether I remove the remaining duplicate elements or not, it just checks the solution in the interval from 0 to returned length

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
   int removeDuplicates(vector<int>& n) {
        if(n.size()<2) return n.size();
        int c = 0;
        for(int i=0;i<n.size();i++){
            if(n[i]>n[c])
                n[++c] = n[i];
        }
        // n.erase(n.begin()+c+1,n.end());
    
        return c+1;
    }
};
```

#### Language used for code

C++

#### Expected behavior

It should check the size of the array, which was passed as a reference.

**Comment by lc-kay** [comment]
Hi @anas40
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@anas40 The statement mentioned that if you return x, we only care about the first x elements of the input array. Therefore, the checker is correct. Thank you for your time.
