### ISSUE TITLE
Bad example in 545

### ISSUE THREAD

**Issue by snehasishroy** [LeetCode-Feedback/LeetCode-Feedback#2143]
#### Your LeetCode username
chrisgriffin

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
In https://leetcode.com/problems/boundary-of-binary-tree/ for example 1, it's mentioned that `The left boundary is the nodes [1,2,3]` However as per official solution, the left boundary is [1].

#### Code you used for Submit/Run operation
Official solution https://leetcode.com/problems/boundary-of-binary-tree/solution/

#### Expected behavior
The wordings of the problem statement needs to be clear to properly distinguish between left boundary and right boundary. It's causing a lot of confusion.

#### Additional context
https://leetcode.com/problems/boundary-of-binary-tree/discuss/979747/This-problem-could-be-FLAWED

**Comment by lc-kay** [comment]
Hi @snehasishroy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @snehasishroy
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
