### ISSUE TITLE
Missing Test Case: 1517. Find Users With Valid E-Mails

### ISSUE THREAD

**Issue by raunakMahalik** [LeetCode-Feedback/LeetCode-Feedback#2145]
#### Your LeetCode username

RaunakMahalik

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Problem 1517 asks the programmer to find all the valid emails from the Employees table (see the [problem description](https://leetcode.com/problems/find-users-with-valid-e-mails/submissions/) to understand the constraints of a valid email). While submitting my code, I was testing various corner cases by giving manual test cases. I noticed that I got the wrong answer while testing one such manual test case (see below sections) but surprisingly the code got submitted successfully. Upon raising this issue with Leetcode's support team (Request number: 56758), I was informed that my test case was not included in Leetcode's test case suite/set and as a result, even though my code got submitted successfully, I still got the wrong answer while testing this particular test case.

Moreover, I feel that the expected answer given by Leetcode for this manual test case is also incorrect (see additional context section).

#### Code you used for Submit/Run operation

```
SELECT * FROM Users where regexp_like(mail, '^[A-Za-z]+[A-Za-z0-9\_\.\-]*@leetcode\.com')
```

#### Language used for code

MySQL

#### Expected behavior

The test case is a valid test case, hence to the best of my knowledge, it should yield a correct answer where the EXPECTED and OUTPUT fields should be as follows:

EXPECTED: ```{"headers": ["user_id", "name", "mail"], "values": [[1, "Brock", "B@leetcode.com"]]}```
OUTPUT: ```{"headers": ["user_id", "name", "mail"], "values": [[1, "Brock", "B@leetcode.com"]]}```

#### Screenshots

See additional context for an important screenshot.

#### Additional context

It should be noted that there is an additional issue. Once this test case is added to Leetcode's test suite/set for this question, the expected output for this test case should be as follows:

```{"headers": ["user_id", "name", "mail"], "values": [[1, "Brock", "B@leetcode.com"]]}```

whereas the Expected Output currently given by Leetcode is:

```{"headers": ["user_id", "name", "mail"], "values": []}```

I feel that this is an error. The test case is a valid test case according to the problem description, hence the expected output should not be blank. Having said that, I am not sure if this will be automatically taken care of once the test case is added to the test case suite/set.

Here is a screenshot of the code-run in which I reproduced this issue. As we can see the expected output is incorrect but the actual output is correct:
![image](https://user-images.githubusercontent.com/56141590/105781035-977ed600-5f26-11eb-8aca-17acf279ac03.png)

**Comment by lc-kay** [comment]
Hi @raunakMahalik 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @raunakMahalik 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
