### ISSUE TITLE
[#937]Wrong test data

### ISSUE THREAD

**Issue by Haley-Seo** [LeetCode-Feedback/LeetCode-Feedback#2146]
#### Your LeetCode username

arsene77

#### Category of the bug
- [V] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The test should validate all lexicographical cases.  
1. "art zero can"
2. "art zero"
For the above case, 2 string should come first.  I missed the logic to check this error and when I ran this program, it showed "Wrong answer" message but it was accepted.  
https://leetcode.com/submissions/detail/413411377/

#### Code you used for Submit/Run operation

```
var reorderLogFiles = function(logs) {
    let lets = logs.map(st => st.split(' ')).filter(words => !Number.isInteger(words[1][0]*1));
    let digs = logs.map(st => st.split(' ')).filter(words => Number.isInteger(words[1][0]*1));
    
    // word sort... 
    lets.sort((a,b) => {
        for(let i = 1; i<Math.min(a.length, b.length); i++){
            if (a[i]>b[i]) return 1;
            if (a[i]<b[i]) return -1;
        }
        return a[0]>b[0] ? 1 : -1;
    });
    lets = lets.map(sts => sts.join(' '));
    digs = digs.map(sts => sts.join(' '));
    return [...lets,...digs];
};
```

#### Language used for code

Javascript

#### Expected behavior

It is not supposed to be accepted.

#### Screenshots

Refer as screenshots
<img width="888" alt="Screen Shot 2021-01-24 at 9 00 55 AM" src="https://user-images.githubusercontent.com/20848561/105791830-7d9bbe00-5f3b-11eb-87f4-fc4ffbd9c811.png">
<img width="746" alt="Screen Shot 2021-01-24 at 9 00 44 AM" src="https://user-images.githubusercontent.com/20848561/105791846-842a3580-5f3b-11eb-89e1-da73419a6515.png">
<img width="1008" alt="Screen Shot 2021-01-24 at 9 00 38 AM" src="https://user-images.githubusercontent.com/20848561/105791864-8a201680-5f3b-11eb-8854-6309f77240b3.png">

**Comment by lc-kay** [comment]
Hi @Haley-Seo 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Haley-Seo 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
