### ISSUE TITLE
Missing Test Case - 264. Ugly Number II

### ISSUE THREAD

**Issue by debajoydas** [LeetCode-Feedback/LeetCode-Feedback#2147]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by debajoydas** [comment]
Wrong Answer
Details 
Input
11
Output
14
Expected
15

Isn't it showing incorrect

**Comment by lc-kay** [comment]
@debajoydas The expected output is correct. Please check out this post https://leetcode.com/problems/ugly-number-ii/discuss/291955/Why-isn't-the-answer-14-to-N-11
