### ISSUE TITLE
[BUG] - 1174. Immediate Food Delivery II - request to add testcase

### ISSUE THREAD

**Issue by OZestina** [LeetCode-Feedback/LeetCode-Feedback#21481]
### LeetCode Username

zestina

### Problem Number, Title, and Link

1174. Immediate Food Delivery II https://leetcode.com/problems/immediate-food-delivery-ii

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

* this bug report is related to issue #21475 

> The first order of a customer is the order with the earliest order date that the customer made. It is guaranteed that a customer has precisely one first order.

Previously in issue #21475 , I requested to check 22nd testcase based on above problem condition, and received response that your 'judge system is functioning properly'.

So I assume that it is okay to have more than 2 same earliest 'order_date' for input.
Below is my testcase.

| delivery_id | customer_id | order_date | customer_pref_delivery_date |
| ----------- | ----------- | ---------- | --------------------------- |
| 7           | 4           | 2019-08-09 | 2019-08-09                  |
| 8           | 4           | 2019-08-09 | 2019-08-11                  |
| 9           | 4           | 2019-08-09 | 2019-08-09                  |

As there is only one customer (customer_id 4), the result should be 100% even though it has two 'immediate' first order.
My code below passed all of the testcase and shows result as below:

| immediate_percentage |
| -------------------- |
| 200                  |

when expected result as below:

| immediate_percentage |
| -------------------- |
| 100                  |

I wonder if the constraint of having 'precisely one first order' only means of (order_date, customer_pref_delivery_date) set or order_date only.

Thanks in advance!

### Language Used for Code

MySQL

### Code used for Submit/Run operation

```bash
# Write your MySQL query statement below
SELECT ROUND(SUM(IF(order_date = customer_pref_delivery_date, 1, 0)) * 100 / COUNT(DISTINCT customer_id), 2) AS immediate_percentage
FROM Delivery
WHERE (customer_id, order_date) IN (
    SELECT customer_id, min(order_date)
    FROM Delivery
    GROUP BY customer_id
)
```

### Expected behavior

| immediate_percentage |
| -------------------- |
| 100                  |

**Comment by HemanCodes** [comment]
Hey @OZestina, facing the same issue. By the way, can you provide the code that returned 200% for your custom test case?

**Comment by OZestina** [comment]
> Hey @OZestina, facing the same issue. By the way, can you provide the code that returned 200% for your custom test case?

```
# Write your MySQL query statement below
SELECT ROUND(SUM(IF(order_date = customer_pref_delivery_date, 1, 0)) * 100 / COUNT(DISTINCT customer_id), 2) AS immediate_percentage
FROM Delivery
WHERE (customer_id, order_date) IN (
    SELECT customer_id, min(order_date)
    FROM Delivery
    GROUP BY customer_id
)
```
@HemanCodes  Here you are!
It's same code as I wrote on the issue (Code used for Submit/Run operation)
The code passed all the testcase of leetcode but shows 200 when I run my testcase
