### ISSUE TITLE
Bug in testcases & result in "Remove Duplicates from Sorted Array" (Swift)

### ISSUE THREAD

**Issue by cayde-6** [LeetCode-Feedback/LeetCode-Feedback#2149]
#### Your LeetCode username

element4

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

For the task you need to remove duplicate elements from the array, but some existing solutions don't do that.

#### Code you used for Submit/Run operation

```
func removeDuplicates(_ nums: inout [Int]) -> Int {
        guard nums.count > 0 else { return 0 }
        var indx = 1
        for i in 1..<nums.count {
            if nums[i-1] != nums[i] {
                nums[indx] = nums[i]
                indx += 1
            }
        }
        return indx
    }
```

#### Language used for code

Swift

#### Expected behavior

Input:
[1, 1, 2, 3, 4, 5, 5, 5, 6, 6]
Expected:
[1, 2, 3, 4, 5, 6]
Result:
[1, 2, 3, 4, 5, 6, 5, 5, 6, 6]

#### Screenshots

<img width="1086" alt="Снимок экрана 2021-01-26 в 19 54 45" src="https://user-images.githubusercontent.com/28859816/105876880-6ed30b00-6010-11eb-932e-468f323db585.png">
<img width="993" alt="Снимок экрана 2021-01-26 в 19 57 41" src="https://user-images.githubusercontent.com/28859816/105877252-d426fc00-6010-11eb-9777-761431677cd9.png">

#### Additional context

-

**Comment by lc-kay** [comment]
@cayde-6 The expected output = actual output when I ran this test case with the provided code. 
<img width="492" alt="Screen Shot 2021-01-27 at 11 35 32 AM" src="https://user-images.githubusercontent.com/70870126/106043834-ca92a800-6093-11eb-8154-9e9d1f10d86d.png">

**Comment by cayde-6** [comment]
It's weird because this code doesn't remove elements from the array, and it doesn't work in Xcode playground.
