### ISSUE TITLE
Weak test cases---1353. Maximum Number of Events That Can Be Attended

### ISSUE THREAD

**Issue by modinitin13** [LeetCode-Feedback/LeetCode-Feedback#215]
**What kind of the bug**
Weak Test Cases

**Describe the bug**
The test cases are weak allowing O(N^2) complexity solution to get an AC.

**what language is your code written in**
C++

**The code you submit/run**
```
class Solution {
public:
    bool static compare(vector<int> &a,vector<int> &b)
    {
        if(a[0]==a[0])
            return a[1]<b[1];
        return a[0]<b[0];
    }
    int maxEvents(vector<vector<int>>& events) {
        sort(events.begin(),events.end(),compare);
        unordered_set<int> s;
        for(int i=0;i<events.size();i++)
        {
            for(int j=events[i][0];j<=events[i][1];j++)
            {
                if(s.find(j)==s.end())
                {
                    s.insert(j);
                    break;
                }
            }
        }
        return s.size();
    }
};
```

**Expected behavior**
This solution should get TLE.
[test.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/4554410/test.txt)

**Screenshots**

**Additional context**
I have attached the test case file.

**Comment by CooperCooperCooper** [comment]
Hi @modinitin13,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
