### ISSUE TITLE
[Test Case] - <代码正确但是测试用例不通过>

### ISSUE THREAD

**Issue by Z-million** [LeetCode-Feedback/LeetCode-Feedback#21505]
### LeetCode 用户名

张百万

### 问题号码、标题和链接

64.最小路径和 https://leetcode.cn/problems/minimum-path-sum/description/

### Bug Category

示例

### 描述

该题目当测试用例grid = [[1,2],[1,1]]时，在eclipse上运行代码可以通过该测试用例，而且在leetcode网站点击运行按钮也可以通过该测试用例，但是点击提交按钮显示答案错误。
![提交失败截图](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73486102/736ff86b-f299-4151-8f2d-7845725e464a)
![运行通过截图](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73486102/f0f3842c-f496-4888-83ed-1a35c42ecb89)

### 你使用的语言

Java

### 你提交或者运行的代码

```bash
class Solution {
    static int ans = Integer.MAX_VALUE;
    public int minPathSum(int[][] grid) {
        int n = grid.length;
        int m = grid[0].length;
        boolean[][] vis = new boolean[n][m];
        dfs(grid,0,0,0);
        return ans + grid[n - 1][m - 1];
    }
    public void dfs(int[][] grid,int x,int y,int minSum){
        if(x < 0 || x >= grid.length || y < 0 || y >= grid[0].length){
            return;
        }
        if(x == grid.length - 1 && y == grid[0].length - 1){
            if(minSum < ans) ans = minSum;
            return;
        }
        dfs(grid,x,y + 1,minSum + grid[x][y]);
        dfs(grid,x + 1,y,minSum + grid[x][y]);
    }
}
```

### 期望行为

修正BUG

### 屏幕截图

![提交失败截图](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73486102/b30cfd46-6edd-4c8d-9b1c-71ef7985bab6)
![运行通过截图](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73486102/b05c90ce-e4a2-4c55-b655-bfaaa0661d1f)

**Comment by amcones-lc** [comment]
您好，在与相关团队核实后：***不处理***（静态变量ans的值会在多个测试样例间共用，考虑在函数内部重新初始化）。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
