### ISSUE TITLE
[BUG] - Invalid testcase 

### ISSUE THREAD

**Issue by Hazem-Mohamed200** [LeetCode-Feedback/LeetCode-Feedback#21513]
### LeetCode Username

Hazem_Mohamed200

### Problem Number, Title, and Link

1174. Immediate Food Delivery II https://leetcode.com/problems/immediate-food-delivery-ii/description/?envType=study-plan-v2&envId=top-sql-50

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

| delivery_id | customer_id | order_date | customer_pref_delivery_date |
| ----------- | ----------- | ---------- | --------------------------- |
| 1           | 1           | 2019-08-01 | 2019-08-02                  |
| 2           | 2           | 2019-08-02 | 2019-08-02                  |
| 3           | 1           | 2019-08-11 | 2019-08-12                  |
| 4           | 3           | 2019-08-24 | 2019-08-24                  |
| 5           | 3           | 2019-08-21 | 2019-08-22                  |
| 6           | 2           | 2019-08-11 | 2019-08-13                  |
| 7           | 4           | 2019-08-09 | 2019-08-09                  |
| 8           | 4           | 2019-08-09 | 2019-08-11                  |

This test case is invalid as customer_id 4 has *2* first dates and the problem explicitly states that there can be only 1

### Language Used for Code

MySQL

### Code used for Submit/Run operation

```bash
Select 
    round(avg(order_date = customer_pref_delivery_date)*100, 2) as immediate_percentage
from Delivery
where (customer_id, order_date) in (
  Select customer_id, min(order_date) 
  from Delivery
  group by customer_id
);
```

### Expected behavior

The test case should not be in the test set

### Screenshots

![Screenshot from 2024-03-24 21-32-23](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/71042723/2079b9ca-1567-41f2-b052-c00c0b4dd9ab)
![Screenshot from 2024-03-24 21-32-06](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/71042723/ced405a4-a93d-45d4-a5b4-edaecba56bc9)

**Comment by amalrajan** [comment]
I'm facing the same bug
