### ISSUE TITLE
Missing test cases in Leetcode Question " First Missing Positive "

### ISSUE THREAD

**Issue by gha1ish** [LeetCode-Feedback/LeetCode-Feedback#2151]
#### Your LeetCode username

lca1ish

#### Category of the bug
Missing Testcase

#### Description of the bug

My incorrect submission is accepted due to lack of sufficient test cases.

#### Code you used for Submit/Run operation

```
// First Missing Positive 
class Solution {
public:
    int firstMissingPositive(vector<int>& nums) {
        int i=0,j=0,k=0,n=nums.size();
        for(i=0;i<n;i++){
            j=nums[i];
            while(j>0 && j<n && j!=nums[j]){
                k=nums[j];
                nums[j]=j;
                j=k;
            }
        }
        for(i=1;i<n;i++)
            if(i!=nums[i])
                return i;
        if(k==n) return n+1;
        return nums[0]==n ? n+1 : n;
    }
};
```

#### Language used for code

C++

#### Expected behavior

My code should not be accepted as it was incorrect. But its accepted due to lack of good test cases.

#### Additional context

I have used below testcase to check :
[1,2,6,3,5,4]
This test case gives "wrong answer" for my above solution.

**Comment by lc-kay** [comment]
Hi @gha1ish 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by gha1ish** [comment]
Thanks.

**Comment by lc-kay** [comment]
Hi @gha1ish 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
