### ISSUE TITLE
[NIT] - Lowest Common Ancestor of a Binary Tree

### ISSUE THREAD

**Issue by BlackFixie** [LeetCode-Feedback/LeetCode-Feedback#21533]
### LeetCode Username

BlackFixie

### Problem Number, Title, and Link

Bonus example: 236. Lowest Common Ancestor of a Binary Tree https://leetcode.com/explore/interview/card/leetcodes-interview-crash-course-data-structures-and-algorithms/707/traversals-trees-graphs/4686/

### Bug Category

Problem description

### Bug Description

The explication of the solution proposed in the DSA course for the problem about the common ancestor of a binary tree is incorrect. At the end of the video he says that if the `left` object is `None` then the `right` object must not be `None`. That is incorrect, it can be seen on the examples of the video that in the case of having `p` and `q` nodes equal to 1, 8, on the left side of the tree there is case where both, `left` and `right` objects would be `None`, as for example for the node 5. The solution is works as at the end, if `left` and `right` are `None` we want to return `None` and returning `right`is actually returning `None` but the concept was incorrect.

### Language Used for Code

None

### Expected behavior

Probably it is less cleaner but also clearer for teaching purposes

        ....
        # third case
        if left:
            return left
         elif right:
            return right
        return None

**Comment by sayedMbo** [comment]
will this be back in the course? with the video explanation??
