### ISSUE TITLE
[BUG] - Group Anagrams - golang - order of returned string slices matters, but it shouldn't

### ISSUE THREAD

**Issue by nadroz** [LeetCode-Feedback/LeetCode-Feedback#21530]
### LeetCode Username

nadroz23

### Problem Number, Title, and Link

https://leetcode.com/problems/group-anagrams

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

The description of the problem clearly states

> Given an array of strings strs, group the anagrams together. You can return the answer in any order.

However, if/when my solution does return what appears to be a valid solution in a different order than the expected output, the test case fails based on the ordering of my output. (see screenshot for example)

### Language Used for Code

Go

### Code used for Submit/Run operation

```bash
func groupAnagrams(strs []string) [][]string {
    sor := map[string][]string{}
    a := 'a'
    for _, s := range strs {
        vals := make([]byte, 26)
        rns := []rune(s)
        for i := 0; i < len(rns); i++ {
            idx := rns[i] - a
            vals[idx] = byte(rns[i])
        }
        key := string(vals)
        sor[key] = append(sor[key], s)
    }

    res := [][]string{}
    for _, v := range sor {
        res = append(res, v)
    }
    return res
}
```

### Expected behavior

I believe this solution should pass tests (or at least not fail based on the order of my output)

### Screenshots

<img width="1708" alt="leetcode issue" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/11026559/7395e83e-bd6c-4d20-90c3-c9194fce4b9f">

**Comment by nadroz** [comment]
Any someone could explain what/how the issue is invalid?

**Comment by daggeraxe172** [comment]
The description is sure ambiguous which states as follows:
Given an array of strings strs, group the 
anagrams together. You can return the answer in **any order**.

If the question is to group anagrams this should pass. KINDLY CHANGE THE DESCRIPTION.

Input
strs =
["bdddddddddd","bbbbbbbbbbc"]

Use Testcase
Output
[["bdddddddddd","bbbbbbbbbbc"]]
Expected
[["bbbbbbbbbbc"],["bdddddddddd"]]

Note : key := string(vals)+"#" solves the problem but the description needs to change.
