### ISSUE TITLE
[BUG] - <title>

### ISSUE THREAD

**Issue by Blade2Cruzor** [LeetCode-Feedback/LeetCode-Feedback#21546]
### LeetCode Username

Blade2Cruzor

### Problem Number, Title, and Link

https://leetcode.com/problems/wildcard-matching/

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

S="cb"
p="??"

### Language Used for Code

C

### Expected behavior

true

**Comment by Flexuo** [comment]
The problem seems to be related to the implementation of wildcard matching in C for the given LeetCode problem. 

I can help with that, contact me for more help
