### ISSUE TITLE
[BUG] - Wrong test case  for LC problem 987. Vertical Order Traversal of a Binary Tree

### ISSUE THREAD

**Issue by cprakash91** [LeetCode-Feedback/LeetCode-Feedback#21568]
### LeetCode Username

cprakash91

### Problem Number, Title, and Link

987. Vertical Order Traversal of a Binary Tree

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

For test case 3, the expected result is wrong. The same test case is given as an example 2 in the description and both things contradict each other.

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
class Solution {
public:
    vector<vector<int>> verticalTraversal(TreeNode* root) {
        queue<pair<int, TreeNode*>> q;
        map<int, vector<int>> m;
        q.push({0, root});
        while(q.size()>0){
            int s = q.size();
            for(int i = 0; i < s; i++){
                pair<int, TreeNode*> p = q.front();
                m[p.first].push_back((p.second)->val);
                if((p.second)->left) q.push({p.first-1, (p.second)->left});
                if((p.second)->right) q.push({p.first+1, (p.second)->right});
                q.pop();
            }          
        }
        vector<vector<int>> out;
        for(const auto& x : m)
            out.push_back(x.second);
        return out;
    }
};
```

### Expected behavior

The test case input or expected output should be corrected.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/43582620/fd9096a2-4e1b-48a5-a4b6-26aadc0a4992)

**Comment by Hr1t1k** [comment]
There may be multiple nodes in the same row and same column. In such a case, sort these nodes by their values.
This is mentioned in the question and the example too
