### ISSUE TITLE
Missing Test Case - 931. Minimum Falling Path Sum

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#2157]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution is accepted but fails on the following test case:
[[100, -42, -46, -41], [31, 97, 10, -10], [-58, -51, 82, 89], [51, 81, 69, -51]]

#### Code you used for Submit/Run operation

```
class Solution {
    long min = Integer.MAX_VALUE;
    public int minFallingPathSum(int[][] A) {
        Map<Integer, Long> map = new HashMap();
        if (A == null || A.length == 0 || A[0].length == 0) return 0;
        int row = A.length, col = A[0].length;
        for (int i = 0; i < col; i++) {
            minFaillingPathSum(A, 0, i, 0, row, col, map);
        }
        return (int)min;
    }
    
    private long minFaillingPathSum (int[][] A, int i, int j, long sum, int row, int col, Map<Integer, Long> map) {
        if (map.containsKey(i * col + j)) {
            min = Math.min(min, map.get(i * col + j) + sum);
            return map.get(i * col + j) + sum;
        }
        if (j < 0 || j > col - 1) return Integer.MAX_VALUE;
        if (i == row - 1) {
            min = Math.min(min, sum + A[i][j]);
            return sum + A[i][j];
        }
        long localMin = Integer.MAX_VALUE;
        localMin = Math.min(localMin, minFaillingPathSum(A, i+1, j-1, sum + A[i][j], row, col, map));
        localMin = Math.min(localMin, minFaillingPathSum(A, i+1, j, sum + A[i][j], row, col, map));
        localMin = Math.min(localMin, minFaillingPathSum(A, i+1, j+1, sum + A[i][j], row, col, map));
        map.put(i * col + j, localMin - sum);
        return  localMin;
    } 
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/106079963-36046600-60e4-11eb-8e02-798eb71f72b2.png)

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
