### ISSUE TITLE
[BUG] - Unable to check the difference between output vs expected

### ISSUE THREAD

**Issue by iisshh** [LeetCode-Feedback/LeetCode-Feedback#21577]
### LeetCode Username

IshwaryaHidkimath

### Problem Number, Title, and Link

2468. Split Message Based on Limit https://leetcode.com/problems/split-message-based-on-limit/description/

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

I have written my implementation but it is failing at 74th testcase. I am unable o check the difference since there is a fixed character limit set to the text block. Unfortunately, till that block size, I can see no difference in the expected vs output. This makes it really inconvenient to debug. Give us an option like copy, just like how it exists for question.

### Language Used for Code

Java

### Expected behavior

Need a copy option for expected and output

### Screenshots

![Image 3-28-24 at 12 58 AM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/16882901/2b9369ac-c87e-4b2e-9723-b479dc7b520a)

Need a copy option like this...

![Image 3-28-24 at 1 00 AM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/16882901/cf4f927a-035a-4c92-8adb-b8c363d8b050)

**Comment by swatvlad** [comment]
+1 to this, I'm having the same issue:
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/58427632/aa2f9ed5-d383-42e2-b08a-d2586c228f90)
The problem is not in the first 1003 characters and the rest is cut off so I can't see where the check fails.
