### ISSUE TITLE
[BUG] - Wrong Expected Output for Question

### ISSUE THREAD

**Issue by MuditJain5** [LeetCode-Feedback/LeetCode-Feedback#21588]
### LeetCode Username

Jain_Mudit

### Problem Number, Title, and Link

https://leetcode.com/problems/count-subarrays-where-max-element-appears-at-least-k-times/description/

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

**For Testcase:**
nums = [1,3,2,3,4]
k = 2

It is showing Expected Output as **0**

### Language Used for Code

C++

### Expected behavior

The expected output should be **2** as we have to find the number of subarrays having the count of maximum element more than or equal to **k**

For this Testcase, it will be [1,3,2,3] and [3,2,3]

**Comment by Jayant420Dhidhi** [comment]
It should be 4 actually:
[1,3,2,3,4]
[3,2,3]
[1,3,2,3]
[3,2,3,4]

**Comment by MuditJain5** [comment]
> It should be 4 actually: [1,3,2,3,4] [3,2,3] [1,3,2,3] [3,2,3,4]

No Jayant, please read the question again, it mentions that the count of maximum element in array should be greater than or equal to k

**Comment by Jayant420Dhidhi** [comment]
Yes and the 4 subarrays satisfies the conditions
