### ISSUE TITLE
[BUG] - <Wrong Description in Question 134 Gas Station>

### ISSUE THREAD

**Issue by Anubhav1107** [LeetCode-Feedback/LeetCode-Feedback#21590]
### LeetCode Username

Stark1107

### Problem Number, Title, and Link

134 Gas Station https://leetcode.com/problems/gas-station

### Bug Category

Problem description, Problem examples

### Bug Description

In the description

```
Input: gas = [1,2,3,4,5], cost = [3,4,5,1,2]
Output: 3
Explanation:
Start at station 3 (index 3) and fill up with 4 unit of gas. 
```

gas station 3 is not at index 3, it's at index 4
as If you wanted to refer to value 3 of gas station, then the index is 2 not 3

and even after that, the entire description of this question is pretty confusing

### Language Used for Code

None

### Expected behavior

It should be proper description

**Comment by Marzex1x** [comment]
I'm not working for leetcode but what i will tell you is the following. Station 3 is meant as index position 3. You have station 0, station 1, station 2, station 3 and station 4. On station 3(index position 3) you have 4 units of gas. Stop making stupid complaints/reporting bugs that don't exist. Thank you!
