### ISSUE TITLE
Test Case  : Problem 367

### ISSUE THREAD

**Issue by RatnadeepSimhadri** [LeetCode-Feedback/LeetCode-Feedback#216]
**What kind of the bug**
- [ ] problem
- [ x] solution
- [ ] language

**Describe the bug**
The Test case expects false for input `0`

**what language is your code written in**
Java

**The code you submit/run**

**Expected behavior**
0 is a perfect Square 
**Screenshots**

![Screen Shot 2020-04-29 at 1 29 48 PM](https://user-images.githubusercontent.com/9788837/80643847-98c5b580-8a1d-11ea-9632-d9ba36817043.png)

**Additional context**

**Comment by CooperCooperCooper** [comment]
Hi @RatnadeepSimhadri,
Thank you for reaching out to us. To help us reproduce this issue, can you please share your submission code here with us? It can be a link to your original submission as well.

**Comment by CooperCooperCooper** [comment]
Hi @RatnadeepSimhadri  ,

Thank you again for reaching out to us previously! Since you have not responded to this ticket for a while, hopefully, the issue has been resolved for you on your end. But if this issue still persists, please feel free to re-open this ticket and share more details with us.
