### ISSUE TITLE
Missing testcase - 1740. Find Distance in a Binary Tree

### ISSUE THREAD

**Issue by Kafafafi** [LeetCode-Feedback/LeetCode-Feedback#2160]
#### Your LeetCode username
zsnovak90

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
The following input - a tree with a single root node - is within constrains, but the judge rejects it with the message : 
"_expected 'root' to have 2 <= size <= 10000 but got 1"_

`[1]`
`1`
`1`

#### Expected behavior
The answer '0' should be accepted

#### Screenshots

![leetcode2](https://user-images.githubusercontent.com/77679911/106159918-97c8dc80-6185-11eb-992e-a1b0e689c5a3.PNG)

**Comment by lc-kay** [comment]
Hi @Kafafafi 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Kafafafi 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
