### ISSUE TITLE
[BUG] - 718 最长重复子数组 缺少测试用例

### ISSUE THREAD

**Issue by cssxsh** [LeetCode-Feedback/LeetCode-Feedback#21607]
### LeetCode 用户名

cssxsh

### 问题号码、标题和链接

https://leetcode.cn/problems/maximum-length-of-repeated-subarray/description/

### Bug Category

缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*

### 描述

当最长重复子数组的重复部分在最后一位时，某些算法可能会忽略它，导致错误结果
例如下面的例子
输入：`nums1 = [1,2,3,4,5], nums2 = [9,8,7,6,5]`
输出：`1`

### 你使用的语言

Kotlin

### 你提交或者运行的代码

```bash
class Solution {
        fun findLength(nums1: IntArray, nums2: IntArray): Int {
            val m = nums1.size
            val n = nums2.size

            val dp = Array(size = m) { IntArray(size = n) { 0 } }
            var max = 0

            var last = nums2[n - 1]
            for (j in 0 until m) dp[j][n - 1] = if (nums1[j] == last) 1 else 0
            last = nums1[m - 1]
            for (i in 0 until n) dp[m - 1][i] = if (last == nums2[i]) 1 else 0

            for (j in m - 2 downTo 0) {
                for (i in n - 2 downTo 0) {
                    dp[j][i] = if (nums1[j] == nums2[i]) dp[j + 1][i + 1] + 1 else 0
                    max = maxOf(dp[j][i], max)
                }
            }

            return max
        }
    }
```

### 期望行为

无法通过测试

**Comment by amcones-lc** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by cssxsh** [comment]
> 你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

https://leetcode.cn/u/cssxsh/

**Comment by amcones-lc** [comment]
你好，当前该题已添加测试用例，奖励已发放。
