### ISSUE TITLE
Missing/Weird Test Case - 53. Maximum Subarray

### ISSUE THREAD

**Issue by ggsell** [LeetCode-Feedback/LeetCode-Feedback#2162]
#### Your LeetCode username

ggsell

#### Category of the bug
- [ ] Question
- [x] Solution
- [X] Language

#### Description of the bug

An input [-2, -1] works when used as a singular testcase but when it is implemented in the testbench it fails.

#### Code you used for Submit/Run operation

```
# Maximum Subarray
class Solution:
    def maxSubArray(self, nums: List[int], lowerIndex: int = None, upperIndex: int = None, memo: dict = {} ) -> int:
        if lowerIndex == None: lowerIndex = 0
        if upperIndex == None: upperIndex = len(nums) - 1
        
        if memo.get((lowerIndex,upperIndex), None) is not None:
            return memo[((lowerIndex,upperIndex))]
                
        if len(nums) == 1: return nums[0]
        
        currSum = sum(nums)
        
        memo[(lowerIndex,upperIndex)] = max(currSum, self.maxSubArray(nums[1:], lowerIndex + 1, upperIndex), self.maxSubArray(nums[0:-1], lowerIndex, upperIndex - 1))
        
        return memo[(lowerIndex,upperIndex)]
```

#### Language used for code

Python3

#### Expected behavior

When using the input [-2, -1] as a singular testcase ('Run Code') the correct output is returned but when used as part of the overall testbench ('Submit'), the same input fails.

#### Screenshots

![image](https://user-images.githubusercontent.com/30841777/106185426-d0aa8680-6170-11eb-8ef2-1774cde6ffaf.png)

**Comment by lc-kay** [comment]
Hi @ggsell 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
