### ISSUE TITLE
393. Is Subsequence (Missing very valid test case)

### ISSUE THREAD

**Issue by sanket0612** [LeetCode-Feedback/LeetCode-Feedback#2163]
#### Your LeetCode username

sanket_64

#### Category of the bug
- [ ] Question 393. Is Subsequence
- [ ] 
- [ ] Solution
- [ ] 
- [ ] public boolean isSubsequence(String s, String t) {
        int left = 0, right=t.length()-1;
        int l = 0, r = s.length()-1;  
      
        while(left<=right && l<=r){
          if(t.charAt(left)==s.charAt(l))
            l++;
          left++;
          
         if(t.charAt(right)==s.charAt(r))
           r--;
          right--;
        }
      
        return l>r;
    }
- [ ] Language
- [ ] JAVA

#### Description of the bug

Missing valid test case
"b" "abc" -> will fail if left<right is used in above code, instead of left<=right

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
Hi @sanket0612 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @sanket0612 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
