### ISSUE TITLE
262. Trips and Users

### ISSUE THREAD

**Issue by jasonli19** [LeetCode-Feedback/LeetCode-Feedback#2164]
#### Your LeetCode username
AutoFrankie

#### Category of the bug
- [ ] Question
- [ *] Solution
- [ ] Language

#### Description of the bug
My SQL query worked before. But today, when I try it, my query does not work any more. And also I tried other's solution, it still did not work! 

#### Code you used for Submit/Run operation

```
SELECT Request_at as Day, ROUND((SUM(Status != 'completed') / COUNT(*)), 2) as 'Cancellation Rate'
FROM Trips as t
INNER JOIN Users as tb1
ON t.Client_Id = tb1.Users_id AND tb1.Banned != "Yes"
INNER JOIN Users tb2
ON t.Driver_Id = tb2.Users_id AND tb2.Banned != "Yes"
WHERE Request_at BETWEEN '2013-10-01' AND '2013-10-03'
GROUP BY Request_at;
```

#### Language used for code
MySQL

#### Expected behavior
My query worked on the testcase. However, when I submit it, it suppose to be successful since I am pretty sure my query worked successfully before, but this time it did not work any more.

**Comment by lc-kay** [comment]
@jasonli19 Since our team is constantly updating the test case sets for our problems to filter out wrong solutions, a previously accepted solution may later result in Wrong Answer. Thank you for your time.

**Comment by jasonli19** [comment]
Hi, can you please double check it one more time because I think there is something wrong with the testcase. someone from the discussion think that the Users data is changing during submission, drivers 10,11, 12 becomes banned, but result does not change. And also, the description is inaccurate. It said  between "2013-10-01" and "2013-10-01", but I think it should be  between "2013-10-01" and "2013-10-03" so that we can past the testcase before we submit it.

**Comment by lc-kay** [comment]
Hi @jasonli19 
I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@jasonli19 We fixed the typo and updated the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
