### ISSUE TITLE
No test case that returns false

### ISSUE THREAD

**Issue by lyagoubisaad** [LeetCode-Feedback/LeetCode-Feedback#21652]
### LeetCode Username

lyagoubisaad

### Problem Number, Title, and Link

877. Stone Game https://leetcode.com/problems/stone-game/

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

all the test cases return true, there is no test case that return false
add this test case int[] piles = new int[] {1, 3, 1, 5, 2}; 
this one will return false 
and thus just return true won't work

### Language Used for Code

Java

### Code used for Submit/Run operation

```bash
public boolean stoneGame(int[] piles) {
        int[][] memos = new int[piles.length][piles.length];
        for (int[] memo: memos) {
            Arrays.fill(memo, Integer.MAX_VALUE);
        }
        return dfs(0, piles.length-1, piles, memos) > 0;
    }

    private int dfs(int i, int j, int[] piles, int[][] memo) {
        if(memo[i][j] != Integer.MAX_VALUE) return memo[i][j];
        if(i==j) return 0;
        return memo[i][j] = Math.max(piles[i]-dfs(i+1, j, piles, memo),piles[j]-dfs(i,j-1,piles, memo));
    }
```

### Expected behavior

returns false

**Comment by stormsunshine** [comment]
Can you provide such a test case? If not, you are wasting others' time.

Have you thought why all test cases return true?

**Comment by lyagoubisaad** [comment]
I provided the test case. If you take the time to read it carefully, you'll find it there

**Comment by stormsunshine** [comment]
If you provide a test case that violates the problem's constraints, you are not actually providing a test case.

Changing an existing problem will affect existing solutions, which is not acceptable.

If you want to do the problem that Bob may also win, you can do the problem 486. There is already a problem that meets your requirement.
