### ISSUE TITLE
Missing Test Case - 88. Merge Sorted Array

### ISSUE THREAD

**Issue by mitali-modi** [LeetCode-Feedback/LeetCode-Feedback#2165]
#### Your LeetCode username
modimitali

#### Category of the bug
- [ ] Solution

#### Description of the bug
Seems the output is not captured correctly.
If you see in below code, I tried to print the nums1 as a debugger it matches with expected output.
but still I  actual output it is not captured

Your input
[1,2,0,0,0]
2
[2,5,6]
3
Your stdout
[1, 2, 2, 5, 6]

Your answer
[1,2,0,0,0]
Expected answer
[1,2,2,5,6]

#### Code you used for Submit/Run operation
````class Solution:
    def merge(self, nums1: List[int], m: int, nums2: List[int], n: int) -> None:
        """
        Do not return anything, modify nums1 in-place instead.
        """
        nums1 = nums1[:m] + nums2
        nums1.sort()    
        print(nums1)
````
#### Language used for code
Python3

**Comment by lc-kay** [comment]
@mitali-modi The output is captured correctly. Please check out this post where a user raised a similar question: https://leetcode.com/problems/merge-sorted-array/discuss/29621/What's-wrong-why-test-is-showing-incorrect-output
There are also many other accepted solutions in the discuss section that you can refer to. Thank you for your time.
