### ISSUE TITLE
Missing Test Case - 236. Lowest Common Ancestor of a Binary Tree

### ISSUE THREAD

**Issue by frankegoesdown** [LeetCode-Feedback/LeetCode-Feedback#2166]
find a bug in golang description

```
/**
 * Definition for TreeNode.
 * type TreeNode struct {
 *     Val int
 *     Left *ListNode
 *     Right *ListNode
 * }
 */
```
![image](https://user-images.githubusercontent.com/6489216/106208599-ab4f6400-61d4-11eb-9d42-aff5b528a76d.png)

it should be 

```
/**
 * Definition for TreeNode.
 * type TreeNode struct {
 *     Val int
 *     Left *TreeNode
 *     Right *TreeNode
 * }
 */
```

**Comment by lc-kay** [comment]
Hi @frankegoesdown 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @frankegoesdown 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
