### ISSUE TITLE
[BUG] - When copy and pasting, Leetcode Auto-Submits

### ISSUE THREAD

**Issue by roycevanle** [LeetCode-Feedback/LeetCode-Feedback#21667]
### LeetCode Username

jli227

### Problem Number, Title, and Link

https://leetcode.com/problems/balanced-binary-tree

### Bug Category

Editorial

### Bug Description

When copying and pasting something into the code editor, sometimes Leetcode will auto-submit the solution. This is very annoying as it disrupts the submission history. This is not limited to the problem in this bug report, but extends to other problems as well.

### Language Used for Code

Java

### Code used for Submit/Run operation

```bash
/**
 * Definition for a binary tree node.
 * public class TreeNode {
 *     int val;
 *     TreeNode left;
 *     TreeNode right;
 *     TreeNode() {}
 *     TreeNode(int val) { this.val = val; }
 *     TreeNode(int val, TreeNode left, TreeNode right) {
 *         this.val = val;
 *         this.left = left;
 *         this.right = right;
 *     }
 * }
 */
class Solution {
    boolean isBal = true;
    public boolean isBalanced(TreeNode root) {
        if (root == null) return true;
        helper(root, 1);
        return isBal;
    }
    private int helper(TreeNode root, int height) {
        if (root == null) return height -1;
        
        int leftH = helper(root.left, height+1);
        int rightH = helper(root.right, height+1);

        if (leftH < rightH -1 || leftH > rightH + 1) {
            isBal = false;
        }
        return (leftH < rightH) ? leftH : rightH;
    }
}
```

### Expected behavior

When copying and pasting in the editor, Leetcode should not auto-submit a solution

**Comment by roycevanle** [comment]
Adding that I've tried this behavior in the old LeetCode layout and confirm that auto-submission on copy-paste does not happen, so it's limited to the new layout.

**Comment by jwagner** [comment]
![Screenshot from 2024-04-02 22-25-02](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/293536/6f2c9595-2795-4758-8b10-5287a096e49c)

I've ran into issues with the editor submitting on pasting or while editing code as well. Turning off the shortcut eliminated it for me so far.

**Comment by roycevanle** [comment]
1. Windows 10
2. Chrome
3. No
4. No specific settings or adjustments.

**Comment by november295536** [comment]
I met this issue too. In addition, leetcode also past what I copy to testcase. 
My env:
1. Win 10
2. Chrome
3. Not using 3rd-party input method
4. No specific settings or adjustments to keyboard
5. Coding in javascript

**Comment by roycevanle** [comment]
Hi Joyce_Ndisya, 

as communicated in my comment previous "Adding that I've tried this behavior in the old LeetCode layout and confirm that auto-submission on copy-paste does not happen, so it's limited to the new layout". I've just doubled check it and confirmed that the bug doesn't happen on the old layout.

**Comment by timber-schroeder** [comment]
This isn't fixed despite being closed.

A simple way to reproduce this is to press 'control+v' + 'enter' in quick succession several times. This is extremely annoying when trying to build out things like fixed lookup tables. The default for submit being set to 'control+enter' is a really bad design.

Firefox 133.0b4. New layout.
