### ISSUE TITLE
Missing Test Case - 954. Array of Doubled Pairs

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#2169]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution is accepted but fails on the following test case:

[-33, 0]

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean canReorderDoubled(int[] A) {
        Map<Integer,Integer> map = new HashMap<>();
        for(int i=0;i<A.length;++i){
            if(!map.containsKey(A[i]))
                 map.put(A[i],0);
            map.put(A[i],map.get(A[i])+1); 
        }
        Arrays.sort(A);
        int count = 0;
        for(int i=0;i<A.length;++i){
            if( A[i] == 0 && map.get(0) > 1 ){
                map.put(2*A[i],map.get(2*A[i])-1);
                map.put(A[i],map.get(A[i])-1);
                count++;
            }else if( map.get(A[i]) > 0 && map.containsKey(2*A[i]) && map.get(2*A[i]) > 0 ){
                map.put(2*A[i],map.get(2*A[i])-1);
                map.put(A[i],map.get(A[i])-1);
                count++;
            }

        }
        
     
        return count == A.length/2;
    }
}

```

#### Language used for code

Java

#### Expected behavior

The solutions should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/106217765-f9983f00-61a3-11eb-9396-8e26137e0677.png)

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
