### ISSUE TITLE
130. Surrounded Regions

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#217]
**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
Judge gives no expected output for correct test case and accepted solution.

**what language is your code written in**
Python

**The code you submit/run**
```
class Solution(object):
    def solve(self, b):
        def f(i,j):
            if 0<=i<n and 0<=j<m and b[i][j]=='O':
                b[i][j]=1
                for x,y in (i+1,j),(i-1,j),(i,j+1),(i,j-1):
                    f(x,y)
        n=len(b)
        if n==0:
            return
        m=len(b[0])
        for i in xrange(n):
            f(i,0)
            f(i,m-1)
        for j in xrange(m):
            f(0,j)
            f(n-1,j)
        for i in xrange(n):
            for j in xrange(m):
                if b[i][j]==1:
                    b[i][j]='O'
                elif b[i][j]=='O':
                    b[i][j]='X'
```

**Expected behavior**
The judge should give both expected output and correct verdict neither of which it is doing now.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/63714778/80644299-0ce87380-8a87-11ea-8244-3959a292dfe4.png)

**Comment by CooperCooperCooper** [comment]
Hi @leet212,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @leet212,
Thank you for your time. We were unable to reproduce the issue on our end (Expected output is showing on our end). If this issue persists on your end, please let me know and share the test case in a text format. We appreciate your support.
