### ISSUE TITLE
Missing Test Case - 1739. Building Boxes

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#2170]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution is accepted but fails on the following test case:

694251486

#### Code you used for Submit/Run operation

```
class Solution {
    public int minimumBoxes(int n) {
        if (n<=3) return n;
        long i = (long)(Math.cbrt(n*6l)) -1;
        long floor = i*(i+1)/2l, sum = (i+2)*(i+1)*i/6l;
        long diff= n-sum;
        //Quadratic formula 
        double f = (-1 + Math.sqrt(1+4*2*diff))/2;
        return (int)floor + (int) Math.ceil(f);
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/106221433-9ca08700-61ab-11eb-90e6-16e5eeac2584.png)

#### Additional context

https://leetcode.com/problems/building-boxes/discuss/1032155/JavaPython-O(1)-Solution

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
