### ISSUE TITLE
Missing Test for 1657. Determine if Two Strings Are Close

### ISSUE THREAD

**Issue by yuhan-wang** [LeetCode-Feedback/LeetCode-Feedback#2171]
#### Your LeetCode username

yuhan-wang

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Wrong solution is accepted for the test case:
word1 = "aaabbbbccddeeeeefffff"
word2 = "aaaaabbcccdddeeeeffff"

Expected:False

#### Code you used for Submit/Run operation

```
class Solution:
    def closeStrings(self, word1: str, word2: str) -> bool:
        # ans = False
        # print(len(word1), len(word2))
        if (len(word1) != len(word2)): return False;

        word1_c = [0]*26
        a = ord('a')
        for c in word1: word1_c[ord(c) - a]+=1

        word2_c = [0]*26
        for c in word2: word2_c[ord(c) - a]+=1

        value = 0;
        for i in range(26): 
            if (word1_c[i] > 0):
                if (word2_c[i] == 0): return False;
                value ^= word1_c[i]
                value ^= word2_c[i]
        
        return value == 0 and set(word1_c) == set(word2_c) and set(word1) == set(word2)
```

#### Language used for code

Python3

#### Expected behavior

For the above test case, expected outcome is False, the solution returns True.

#### Additional context

Submission link: https://leetcode.com/submissions/detail/449165226/

**Comment by stormsunshine** [comment]
The problem is [1657. Determine if Two Strings Are Close](https://leetcode.com/problems/determine-if-two-strings-are-close/).
@yuhan-wang Please provide the problem number or link when creating an issue of missing test cases.

**Comment by yuhan-wang** [comment]
> The problem is [1657. Determine if Two Strings Are Close](https://leetcode.com/problems/determine-if-two-strings-are-close/).
> @yuhan-wang Please provide the problem number or link when creating an issue of missing test cases.

Thanks, I forgot.

**Comment by lc-kay** [comment]
Hi @yuhan-wang 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @yuhan-wang 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
