### ISSUE TITLE
[BUG] - discord channel for system's design course expired or discord no longer exists?

### ISSUE THREAD

**Issue by melder** [LeetCode-Feedback/LeetCode-Feedback#21725]
### LeetCode Username

melder

### Problem Number, Title, and Link

https://leetcode.com/explore/interview/card/system-design-for-interviews-and-beyond/735/practice-problems/4831/

### Bug Category

Editorial

### Bug Description

I'd like feedback on my practice design solutions but the discord link is not loading

### Language Used for Code

None

### Expected behavior

Discord link to load ... I recommend using and configuring an invite link that does not expire

**Comment by melder** [comment]
Still not working. Did you try to reproduce? I am aware that that is the discord link in the course.

BTW I'm not the only one with this issue: https://leetcode.com/discuss/explore/system-design-for-interviews-and-beyond/4987515/How-to-join-the-Discord-channel

I'm assuming this is an invite to a channel on a particular discord. What is the parent discord? Can you discover that for us? Does it still exist? If it does is proof required that we purchased the course?

**Comment by gangamamulya** [comment]
Hi, the link is still not working. can you please help me with this?
