### ISSUE TITLE
[BUG] - <Leetcode weekly contest> Problem 3

### ISSUE THREAD

**Issue by garyguo123456789** [LeetCode-Feedback/LeetCode-Feedback#21730]
### LeetCode Username

garyguo123456789

### Problem Number, Title, and Link

 100277. Minimum Operations to Make Median of Array Equal to K

### Bug Category

Problem examples

### Bug Description

Example 3:

Input: nums = [1,2,3,4,5,6], k = 4

Output: 0

Explanation:

The median of the array is already equal to k.

The median of the array is supposed to be 3.5, not 4. 

### Language Used for Code

C++

### Expected behavior

The answer should be 1, since the median is 3.5, not 4.

**Comment by FreeEagleD** [comment]
This also cofused me and consumed all my rest contest time try to solve it. for test case [1,2,3,4,5,6] and k = 4, if we meet the true median, either increase 3 to 4 or decrease 4 to 3, both situation will  take 1 operation, not 0 operation. for test case such as [1, 10] and k = 3(any value x that 1 < x < 10), the result should be 9. but the question just take the second middle element when size of array is even, and not mentioned a little bit in the description.  this is unfair!

**Comment by FreeEagleD** [comment]
This also cofused me and consumed all my rest contest time try to solve it. for test case [1,2,3,4,5,6] and k = 4, if we meet the true median, either increase 3 to 4 or decrease 4 to 3, both situation will  take 1 operation, not 0 operation. for test case such as [1, 10] and k = 3(any value x that 1 < x < 10), the result should be 9. but the question just take the second middle element when size of array is even, and not mentioned a little bit in the description.  this is unfair!
