### ISSUE TITLE
[BUG] - 删除有序数组中的重复项 II-python3计算结果有问题

### ISSUE THREAD

**Issue by Qiliang-Huang** [LeetCode-Feedback/LeetCode-Feedback#21744]
### LeetCode 用户名

好运来

### 问题号码、标题和链接

https://leetcode.cn/problems/remove-duplicates-from-sorted-array-ii/description/?envType=study-plan-v2&envId=top-interview-150

### Bug Category

不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*

### 描述

很简单的代码，输入测试用例[1]，按照代码，应该直接返回，不会修改输入案例，但是结果显示其用例被修改了。

### 你使用的语言

Python/Python3

### 你提交或者运行的代码

```bash
class Solution:
    def removeDuplicates(self, nums: List[int]) -> int:
        length = len(nums)
        if length < 3:
            return 0
        i = 1
        count = 0
        j = 0
        while i < length:
            nums[i - count] = nums[i]
            if nums[i - count] == nums[i - count - 1]:
                j += 1
                if j >= 2:
                    count += 1
                    nums[i - count] = nums[i - count - 1]
                    i += 1
                else:
                    i += 1

            else:
                j = 0
                i += 1
        return length - count
```

### 期望行为

对于测试用例[1]，因为代码刚开始判断其长度小于3.直接return 了，其内容不应该被修改，但是leetecode显示其内容被修改了。

### 屏幕截图

![leetecode删除有序数组中的重复项2截图](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/63205474/b1ce52bb-8557-4127-87a6-702efc19f478)

**Comment by amcones-lc** [comment]
您好，在与相关团队核实后：***不处理***（该题评测会根据返回的值来读数组，在该情况下返回 0 所以读到空数组）。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
