### ISSUE TITLE
Missing Test Case - 1760. Check Array Formation Through Concatenation

### ISSUE THREAD

**Issue by svetlinka78** [LeetCode-Feedback/LeetCode-Feedback#2174]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

  //must be true
    //int[] arr = { 91, 6, 4, 64, 78 };
    //int[][] pieces = { new int[] { 78 }, new int[] { 4, 64 }, new int[] { 91, 6 } };

    //must be false - the digit in pieses array must not be separated
    //int[] arr = { 91, 4, 64, 78, 6 };
    //int[][] pieces = { new int[] { 78 }, new int[] { 4, 64 }, new int[] { 91, 6 } };

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@svetlinka78 Please provide the submission details link and the missing test case you are trying to report.

**Comment by lc-kay** [comment]
Hi @svetlinka78 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
