### ISSUE TITLE
Missing Test Case - 205. Isomorphic Strings

### ISSUE THREAD

**Issue by mkuklik** [LeetCode-Feedback/LeetCode-Feedback#2175]
#### Your LeetCode username

xanaduet

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

incorrect answer to test case:
"badc"
"baba"
Should be true

#### Code you used for Submit/Run operation
```
func isIsomorphic(s string, t string) bool {
    mapping := map[rune]rune{}
    
    for i, sx := range s {
        rep, ok := mapping[sx]
        if ok {
            if rep != rune(t[i]) {
                return false
            }
        } else {
            mapping[sx] = rune(t[i])
        }
    }
    return true
}

```

#### Language used for code
GO

#### Expected behavior
true

**Comment by lc-kay** [comment]
@mkuklik The expected output is correct. Please raise this question in the discuss section of the problem, or check out posts by other users who raised similar questions. Thank you for your time.
