### ISSUE TITLE
[BUG] - <缺陷标题>

### ISSUE THREAD

**Issue by fighting2825** [LeetCode-Feedback/LeetCode-Feedback#21786]
### LeetCode 用户名

戒酒的李白

### 问题号码、标题和链接

680. 验证回文串 II https://leetcode.cn/problems/valid-palindrome-ii/

### Bug Category

缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*

### 描述

采用下面可以通过题目，但是错误的，比如测试用例"acbbba"，计算b的个数为奇数，所以右指针往右边走，即删除了右边的b，剩下cbb，返回false，但是这个测试用例是正确的。缺少测试用例。

### 你使用的语言

C++

### 你提交或者运行的代码

```bash
class Solution {
public:
    bool validPalindrome(string s) 
    {
        vector<int> m(26,0);
        for(auto e : s)
        {
            m[e - 'a']++;
        }
        int n = s.size();
        int left = 0,right = n - 1;
        int flag = 0;
        while(left <= right)
        {
            if(flag >= 2)
                return false;
            if(s[left] == s[right])
            {
                ++left;
                --right;
            }
            else
            {
                if(m[s[right] - 'a'] % 2 == 1)
                    --right;
                else
                    ++left;
                ++flag;
            }
        }
        return true;
    }
};
```

### 期望行为

添加测试用例

### 屏幕截图

<img width="1212" alt="测试用例不通过" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/107634040/c5f69642-1575-40dc-b04b-bd2410885e4c">

**Comment by amcones-lc** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。
