### ISSUE TITLE
[BUG] - <3.无重复字符的最长字串测试逻辑出错>

### ISSUE THREAD

**Issue by xslcc** [LeetCode-Feedback/LeetCode-Feedback#21795]
### LeetCode 用户名

xslcc

### 问题号码、标题和链接

3.无重复字符的最长字串https://leetcode.cn/problems/longest-substring-without-repeating-characters/description/

### Bug Category

不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*

### 描述

相同的代码，在本地VS2022上使用C++14 运行输出结果正确。使用unordered_set模拟一个双端队列，在队尾添加数据（“入队时”），本地VS能正确输出队头的元素（即队头元素为begin()指向的元素），而在leetcode测试数据时无法正确输出队头（begin()指向的元素）元素，而是将添加的数据（“入队数据作为队头”）。

### 你使用的语言

C++

### 你提交或者运行的代码

```bash
int lengthOfLongestSubstring(string s) {
	if (s.length() <= 1) return s.length();
	int len = 0;
	int i = 0;
	int res = 0;
	unordered_set<char> qe;
    while (i < s.length()) {
        if (qe.find(s[i]) == qe.end()) {
            qe.emplace(s[i]);
            cout << "加入了（入队了）：" << s[i] << endl;
            auto it = qe.begin();
            cout << "此时begin是（队头是）：" << *it << endl;
            len++;
            i++;
        }
        else {
            auto it = qe.begin();
            cout << "删去了（队头元素出队）：" << *it << endl;
            qe.erase(qe.begin());
            res = max(len, res);
            len--;
        }
    }
	return res;
}
```

### 期望行为

正确输出队头元素（即begin()指向的元素值）

### 屏幕截图

![image_26](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/166783205/dfd72091-704d-4a63-a86e-cef959d3b045)
![image_27](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/166783205/633545de-9e48-4348-9f67-dcb92fd57436)

**Comment by amcones-lc** [comment]
感谢反馈，经核实该题目题解及测试用例暂无异常，力扣会不断努力给大家带来更好的学习社区！后续刷题学习中遇到问题，可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
