### ISSUE TITLE
Missing test case- 740. Delete and Earn

### ISSUE THREAD

**Issue by kapish5467** [LeetCode-Feedback/LeetCode-Feedback#2179]
#### Your LeetCode username
###kapishgarg

#### Category of the bug
- [ X] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution is accepted but fails on the following test case.
[1,2,3,15,16,17,18]

#### Code you used for Submit/Run operation

```
// Delete and Earn
class Solution {
    public int deleteAndEarn(int[] nums) {
        
      HashMap<Integer,Integer> map= new HashMap<>();
        for(int x: nums)
        {
            map.put(x,map.getOrDefault(x,0)+x);
        }
        
        int c=0;
        int dc=0;
        for(int x: map.keySet())
        {
           if(map.containsKey(x-1))
           {
               int temp= Math.max(dc+map.get(x),c);
               //System.out.println(temp);
               dc=c;
               c=temp;
           }
        else
        {
            dc=c;
            c+=map.get(x);
        }
            
        }
    return c;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solutions should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/17156083/106317248-e5475700-6222-11eb-84ff-118f3a6565e3.png)

**Comment by lc-kay** [comment]
Hi @kapish5467 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @kapish5467 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
