### ISSUE TITLE
878. Nth Magical Number

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#218]
**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
The 2nd solution given is not optimal and time complexity is not according to the given solution. Furthermore the given complexity is a loose upper limit rather than a tight one.

**what language is your code written in**
Python

**The code you submit/run**
```
class Solution(object):
    def nthMagicalNumber(self, n, a, b):
        def f(x,y):
            if x==0:
                return y
            return f(y%x,x)
        l=min(a,b)
        u=n*l
        g=(a*b)/f(a,b)
        while l<=u:
            m=(l+u)/2
            if m/a+m/b-m/g>=n:
                u=m-1
            else:
                l=m+1
        return (u+1)%(pow(10,9)+7)
```

**Expected behavior**
The problem in the solution takes upper bound as 10 ** 15 rather than taking it according to the given inputs. It will work but is not the best practice at all. 

Its time complexity is given as O(log(N ∗ max(A,B))) but since the upper bound is taken as 10 ** 15 where does N * max(A,B) even come from. Looking at the solution it should be log(10 ** 15) which is O(1) and it could be ambiguous.

Lastly, the correct upper bound should be the tightest which is actually N * min(A,B). The accepted solution using this bound is given above.

**Comment by CooperCooperCooper** [comment]
Hi @
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @
Thank you for your time. We've used your feedback to update the article. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
