### ISSUE TITLE
[BUG] - <title>

### ISSUE THREAD

**Issue by RidhiAr** [LeetCode-Feedback/LeetCode-Feedback#21809]
### LeetCode Username

ridhi_14

### Problem Number, Title, and Link

https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

code will give wrong output for salbutsad
but since the above string is missing the code is getting accepted

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
class Solution {
public:
    int strStr(string haystack, string needle) {
        int i=0;
            while(haystack[i]!=needle[0])
            {
                i++;
                if(i==haystack.size())
                {
                    return -1;
                }
            }
           for(int j=0;j<needle.size();j++)
           {
               if(needle[j]!=haystack[i+j])
               {
                   return -1;
               }
           }
        
        return i;
    }
};
```

### Expected behavior

code will give wrong output for "salbutsad"
but since the above string is missing the code is getting accepted

**Comment by harpal2462** [comment]
In my machine for 
**Input:**
haystack = `salbutsad`
needle = `sad`
after Run its giving me the _wrong answer as expected_, and it is not getting accepted.
![Screenshot 2024-04-14 012004](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/121793858/fd310398-b893-40f4-b3f9-87798f76d0fc)


While submitting the answer its giving me _wrong answer for 65th Testcase_,  64 / 83 testcases passed.
and the 65th Testcase is:
**Input:** 
haystack = `mississippi`
needle = `issip`
![Screenshot 2024-04-14 011752](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/121793858/290d88a8-5360-45b9-ac6a-9377bb718dbe)


**So i think the test case that you are mentioning, which is for haystack =  `salbutsad`  might be after 65th Testcase, so your code got rejected earlier without checking for further test cases.**

So i don't think any test cases are missing.
