### ISSUE TITLE
Missing Test Case - 1029. Vertical Order Traversal of a Binary Tree

### ISSUE THREAD

**Issue by sarioz** [LeetCode-Feedback/LeetCode-Feedback#2180]
#### Your LeetCode username

ozrisa

#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language

#### Description of the bug

Nowhere is it specified that the node values are distinct, or that the binary tree is special in any way. So for the tree
[3,1,4,0,2,2]
you have two 2s have the same x and y values. If a solution (like my current one) uses a set as a backing data structure, the two 2's meld into one. You would get even more extreme effects if you had all the nodes have the same value.

#### Language used for code

```

from collections import defaultdict

class Solution:
    def verticalTraversalH(self, root: TreeNode, x: int, y: int, d: defaultdict(set)):
        """Do a pre-order traversal"""
        if not root:
            return
        # While the spec was unclear, duplicate values sharing the same (x, y) will not stick."""
        d[(x, y)].add(root.val)
        self.verticalTraversalH(root.left, x - 1, y + 1, d)
        self.verticalTraversalH(root.right, x + 1, y + 1, d)

    def verticalTraversal(self, root: TreeNode) -> List[List[int]]:
        d_by_x_y = defaultdict(set)
        self.verticalTraversalH(root, 0, 0, d_by_x_y)

        d_by_x = defaultdict(list)
        # for each x, we want the v's in the order of the x's *and* y's
        for (x, _, vs) in [(x, _, vs) for (x, _), vs in sorted(d_by_x_y.items())]:
            # for each x and y, we want the v's in increasing order
            d_by_x[x].extend(sorted(vs))
        return d_by_x.values()
```

#### Expected behavior

My solution above passed all the tests. [3,1,4,0,2,2] is a test case where it will fail: my solution outputs [[0],[1],[3,2],[4]] on it whereas the expected output is [[0],[1],[3,2,2],[4]].

#### Screenshots

Here is a transparent rendering of the tree:

<img width="415" alt="Screen Shot 2021-01-29 at 23 13 55" src="https://user-images.githubusercontent.com/13627797/106322953-ab5c6c00-6287-11eb-947e-fec921b36288.png">

**Comment by lc-kay** [comment]
Hi @sarioz 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @sarioz 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
