### ISSUE TITLE
[Second solution does not compile] - <876. Middle of The Linked List Leetcode Beginners Guide >

### ISSUE THREAD

**Issue by fbera231** [LeetCode-Feedback/LeetCode-Feedback#21806]
### LeetCode Username

fbera_21

### Problem Number, Title, and Link

https://leetcode.com/problems/middle-of-the-linked-list/

### Bug Category

Editorial

### Bug Description

I don't want to call it a bug but in the solution video by https://leetcode.com/explore/learn/card/the-leetcode-beginners-guide/692/challenge-problems/4426/ i wrote the exact same code but it gave compile error. I could turn it into compilable code but i thought the solution video had to have a submittable code.

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
/**
 * Definition for singly-linked list.
 * struct ListNode {
 *     int val;
 *     ListNode *next;
 *     ListNode() : val(0), next(nullptr) {}
 *     ListNode(int x) : val(x), next(nullptr) {}
 *     ListNode(int x, ListNode *next) : val(x), next(next) {}
 * };
 */
class Solution {
public:
    ListNode middleNode(ListNode head) {
        ListNode middle= head;
        ListNode end= head;
        while(end!= null && end.next!= null){
            middle= middle.next;
            end= end.next.next;
        }
        return middle;
    }
};
```

### Expected behavior

I don't expect it to work but other learners would. 

### Screenshots

![Ekran görüntüsü 2024-04-13 122243](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/154339013/17447023-6bf7-45f7-bd05-d3ab5fb196c6)
![Ekran görüntüsü 2024-04-13 123130](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/154339013/416dcb2a-b7a7-46ba-a06c-1ecd224c0989)

**Comment by fbera231** [comment]
![Ekran görüntüsü 2024-04-13 123130](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/154339013/416dcb2a-b7a7-46ba-a06c-1ecd224c0989)
The screenshot of the video solution

**Comment by fbera231** [comment]
/**
 * Definition for singly-linked list.
 * struct ListNode {
 *     int val;
 *     ListNode *next;
 *     ListNode() : val(0), next(nullptr) {}
 *     ListNode(int x) : val(x), next(nullptr) {}
 *     ListNode(int x, ListNode *next) : val(x), next(next) {}
 * };
 */
class Solution {
public:
    ListNode* middleNode(ListNode* head) {
        ListNode* middle= head;
        ListNode* end= head;
        while(end!= nullptr && end->next!= nullptr){
            middle= middle->next;
            end= end->next->next;
        }
        return middle;
    }
};


This is an accepted submission

**Comment by uttamRal** [comment]
Yo c++ is different from java.
check again you will get answer 
here is my code
/**
 * Definition for singly-linked list.
 * struct ListNode {
 *     int val;
 *     ListNode *next;
 *     ListNode() : val(0), next(nullptr) {}
 *     ListNode(int x) : val(x), next(nullptr) {}
 *     ListNode(int x, ListNode *next) : val(x), next(next) {}
 * };
 */
class Solution {
public:
    ListNode* middleNode(ListNode* head) {
        ListNode* slow = head;
        ListNode* fast = head;
        
        // Move slow pointer one step at a time and fast pointer two steps at a time
        // When fast pointer reaches the end, slow pointer will be at the middle
        while (fast != nullptr && fast->next != nullptr) {
            slow = slow->next;
            fast = fast->next->next;
        }
        
        return slow;
    }
};

**Comment by fbera231** [comment]
You are right i didn't think about it at the time
