### ISSUE TITLE
Missing Test Case - 1663. Smallest String With A Given Numeric Value

### ISSUE THREAD

**Issue by t4upl** [LeetCode-Feedback/LeetCode-Feedback#2181]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The question does not specify what happens if it is not possible to create such a string. For example:

n = 1, k = 108
n = 50, k =3

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@t4upl We've already set the constraints to this problem. When you try to run those test cases, it will return an invalid test case message. Thank you for your time.
