### ISSUE TITLE
[BUG] - <Submission Error>

### ISSUE THREAD

**Issue by aarushi-shanker** [LeetCode-Feedback/LeetCode-Feedback#21811]
### LeetCode Username

user4365II

### Problem Number, Title, and Link

3114. https://leetcode.com/problems/latest-time-you-can-obtain-after-replacing-characters/description/

### Bug Category

Editorial

### Bug Description

Writing code on phone is difficult. it gets stuck in zoomed in mode and doesn't return to normal.

### Language Used for Code

Java

### Expected behavior

To get back to normal when zoomed out.

**Comment by SharmaTushar1** [comment]
Apparently this issue is still present after 5 months. It is even worse now with dynamic layouts.
