### ISSUE TITLE
[BUG] - Incorrect test case in 636. Exclusive Time of Functions

### ISSUE THREAD

**Issue by przemek3d88** [LeetCode-Feedback/LeetCode-Feedback#21837]
### LeetCode Username

przemysaw2

### Problem Number, Title, and Link

636. Exclusive Time of Functions https://leetcode.com/problems/exclusive-time-of-functions/description/

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

The problem contains the following test case:

```
3
["1:start:0","0:start:2","1:start:3","2:start:4","2:end:4","0:end:6","1:end:7","1:end:8"]
```

Which is incorrect as it does not follow the problem description. It is impossible that the `"0:end:6"` happened before `"1:end:7"`, as the 1 was put on the stack on top of 0, so it had to finish earlier than 0 frame.

### Language Used for Code

None

### Expected behavior

This test should be removed from the set and the contrasts of the problem test cases should be updated to pass a better verification. It causes correct solutions to fail.

**Comment by barry963** [comment]
username: woo7952

+1, the correct test case should be 

```
3
["1:start:0","0:start:2","1:start:3","2:start:4","2:end:4","1:end:6","0:end:7","1:end:8"]
```

**Comment by peterbayerle** [comment]
spent forever trying to figure out this case ... thanks for opening a bug report

**Comment by SkandaB** [comment]
Definitely seems invalid.

> Function calls are stored in a call stack: when a function call starts, its ID is pushed onto the stack, and when a function call ends, its ID is popped off the stack. The function whose ID is at the top of the stack is the current function being executed.

The middle sequence of events:
```
"0:start:2"
"1:start:3"
"2:start:4"
"2:end:4"
"0:end:6"
```

The 0 task resuming instead of 1 at the end which does not follow the problem constraints. 
The expectation is that 1 would resume and should be the next function call.
