### ISSUE TITLE
[BUG] - <180. 连续出现的数字 第23个测试用例有问题>

### ISSUE THREAD

**Issue by JackeeyDean** [LeetCode-Feedback/LeetCode-Feedback#21847]
### LeetCode 用户名

颉颃

### 问题号码、标题和链接

180. 连续出现的数字 https://leetcode.cn/problems/consecutive-numbers/description/

### Bug Category

不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*

### 描述

输入：
Logs =
| id | num |
| -- | --- |
| 1  | 1   |
| 2  | 1   |
| 4  | 1   |
| 5  | 1   |
| 6  | 2   |
| 7  | 1   |

按照要求，上面用例中的**1是满足条件的**，但是该用例预期结果是`没有满足条件的记录`：

| ConsecutiveNums |
| --------------- |

### 你使用的语言

Oracle SQL

### 你提交或者运行的代码

```bash
select distinct num as ConsecutiveNums from (
select lag(a.num, 1) over(order by id) ahead_num1,
       lag(a.num, 2) over(order by id) ahead_num2,
       a.num
  from logs a) t
 where ahead_num1 = ahead_num2
   and ahead_num2 = num
   and ahead_num1 is not null
   and ahead_num2 is not null
```

### 期望行为

修正用例判定结果

### 屏幕截图

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/11507275/af519bc9-027c-4cf4-b309-f13d6af62fa4)

**Comment by oamuuvyi** [comment]
你读错题了，连续指的是 `id` 连续，不是他们按 `id` 排序后相邻。上述用例中 `2, 4`不是连续的。
