### ISSUE TITLE
[BUG] - <错误的代码可以>

### ISSUE THREAD

**Issue by hjh12135** [LeetCode-Feedback/LeetCode-Feedback#21845]
### LeetCode 用户名

Upbeat MclarenJpN

### 问题号码、标题和链接

15.三数之和 https://leetcode.cn/problems/3sum/description/

### Bug Category

缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*

### 描述

本人在测试过程中，发现我编写错误的代码可以通过检测，但无法通过我自己设置的用例。这说明用例没有覆盖更一般的情形。
在该题中，我将输入进行排序后，一开始期望在  taget/3  的附近进行搜索，忽略了达成目标的数值可能在很远的地方。然而，我只要将搜索范围稍微扩大一些，仍然能够通过测试。然而只要实际的结果超出我搜索的范围，理论上是不能的出正确的结果的。

### 你使用的语言

C++

### 你提交或者运行的代码

```bash
class Solution {
public:
    int threeSumClosest(vector<int>& nums, int target) {
        sort(nums.begin(),nums.end());

        int xxx=target/3;
        int sub=INT_MAX;
        int ind;
        for(int i=0;i<nums.size();i++){
            if(abs(nums[i]-xxx)<sub){
                ind=i;sub=abs(nums[i]-xxx);
            }
            
        }
        sub=INT_MAX;
        int plus=0;
        int left=max(ind-10,0),right=min(ind+10,int(nums.size()-1));
        cout<<nums[left]<<'\t'<<nums[right]<<endl;
        for(int i=left;i<=right;i++){
            for(int j=i+1;j<=right;j++){
                for(int k=j+1;k<=right;k++){
                    int tem=nums[i]+nums[j]+nums[k];
                    if(abs(tem-target)<sub){
                        plus=tem;
                        sub=abs(tem-target);
                    }
                }
            }
        }
        return plus;

    }
};
```

### 期望行为

理论上，该代码不应该通过测试，因为这显然是一份错误的代码。例如该题并不能通过如下的示例.

### 屏幕截图

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/96968023/177dadbf-4d4e-4e07-a1ac-fe95d332a2fb)

**Comment by Milkve** [comment]
It is [16. 最接近的三数之和](https://leetcode.cn/problems/3sum-closest/) rather than [15. 三数之和](https://leetcode.cn/problems/3sum/)

**Comment by amcones-lc** [comment]
感谢反馈，能否向我们补充测试用例信息，把信息提供完整才能有助于快速验证和精准的定位，谢谢。

**Comment by Milkve** [comment]
> 感谢反馈，能否向我们补充测试用例信息，把信息提供完整才能有助于快速验证和精准的定位，谢谢。

Test Case:

```bash
Input:
nums = [1,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,15,19,19,19,19,19,19,19,19,19,19,19,19,19,19,29]
target = 45

Output:
43
```

And the submitted C++ code is the same as above:

```c++
// C++
class Solution {
public:
    int threeSumClosest(vector<int>& nums, int target) {
        sort(nums.begin(),nums.end());

        int xxx=target/3;
        int sub=INT_MAX;
        int ind;
        for(int i=0;i<nums.size();i++){
            if(abs(nums[i]-xxx)<sub){
                ind=i;sub=abs(nums[i]-xxx);
            }
            
        }
        sub=INT_MAX;
        int plus=0;
        int left=max(ind-10,0),right=min(ind+10,int(nums.size()-1));
        cout<<nums[left]<<'\t'<<nums[right]<<endl;
        for(int i=left;i<=right;i++){
            for(int j=i+1;j<=right;j++){
                for(int k=j+1;k<=right;k++){
                    int tem=nums[i]+nums[j]+nums[k];
                    if(abs(tem-target)<sub){
                        plus=tem;
                        sub=abs(tem-target);
                    }
                }
            }
        }
        return plus;

    }
};
```

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/45092129/c59b87c7-fc0c-434c-aaa0-10d2b05cf0c2)

**Comment by amcones-lc** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by Milkve** [comment]
> 你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。


leetcode.cn/u/angels-coder-edit/
