### ISSUE TITLE
Missing Test Case - 805. Split Array With Same Average

### ISSUE THREAD

**Issue by turbopraveen** [LeetCode-Feedback/LeetCode-Feedback#2186]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@turbopraveen Please provide a more detailed report so we can better understand the issue. Thank you.

**Comment by lc-kay** [comment]
Hi @turbopraveen 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
