### ISSUE TITLE
[BUG] - <30. Substring with Concatenation of All Words> || leetcode 30

### ISSUE THREAD

**Issue by sahil-a333** [LeetCode-Feedback/LeetCode-Feedback#21861]
### LeetCode Username

isahil-77

### Problem Number, Title, and Link

30. Substring with Concatenation of All Words    https://leetcode.com/problems/substring-with-concatenation-of-all-words/?envType=study-plan-v2&envId=top-interview-150

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

My code gives "Runtime Error " on a custom testcase but passes the submission:

Input: s = "b" , words = ["bbb","bbb"]
Output: [ ]

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
class Solution {
public:
    vector<int> findSubstring(string s, vector<string>& words) {
        unordered_map<string,int> freq,curr;
        for(string& word: words)
            freq[word]++;
        
        int len = s.size();
        int n = words.size();
        int wordSize = words[0].size();
        int windowSize = wordSize*n;

        vector<int> ans;
        for(int startPos=0;startPos<wordSize;++startPos){//Try all starting positions
            int start = startPos;
            do {
                curr = freq;    //Make a copy of freq map to edit
                string currWord;
                bool matched = true;    //presume that match happened
                for(int i=0;i<n;++i){   //Find each word
                    currWord = s.substr(start+i*wordSize,wordSize); //Extract current word
                    if(!curr.count(currWord) or curr[currWord]==0){ //Match word
                        matched = false;    //current word did not match
                        break;
                    }
                    curr[currWord]--;           //Remove word after having found
                }
                if(matched==true)               //Found match
                    ans.push_back(start);
                start+=wordSize;                //Sliding Window
            }while(start+windowSize-1<len);     //Bound check
        }
        return ans;
    }
};
```

### Expected behavior

❗❗**The above code is "not that efficient" so gives TLE(Time Limit Exceeded) sometimes so run it again atleat 3-4 times.**❗❗
**My issue is not about TLE(Time Limit Exceeded) its about the "MISSING TESTCASE"**

My code passes the submission but gives "Runtime Error " on the custom testcase given below.

Input: s = "b" , words = ["bbb","bbb"]
Output: [ ]

### Screenshots

![Screenshot 2024-04-18 025728](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/114415059/8d4b4296-9490-443a-8d1c-8016dd7615eb)

### Additional context

**I created this issue to contribute a test case to leetcode**

**Remember my code passed the submission but gives TLE sometimes so run it again 3-4 times so that it gets submitted but my isse is not about TLE its about the "MISSING TEATCASE"**

**Comment by Mux071** [comment]
![photo_2024-04-19_06-49-05](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/111518561/038a4826-c921-4464-9ff5-847855e12414)

**Comment by sahil-a333** [comment]
> class Solution { public: vector findSubstring(string s, vector& words) { vector result; if (s.empty() || words.empty()) { return result; }
> 
> ```
>     unordered_map<string, int> wordFreq;
>     for (const string& word : words) {
>         wordFreq[word]++;
>     }
>     
>     int wordLength = words[0].length();
>     int totalLength = wordLength * words.size();
>     
>     for (int i = 0; i <= (int)s.length() - totalLength; i++) {
>         unordered_map<string, int> tempFreq;
>         int j = 0;
>         for (j = 0; j < words.size(); j++) {
>             string currentSubstr = s.substr(i + j * wordLength, wordLength);
>             if (wordFreq.find(currentSubstr) != wordFreq.end()) {
>                 tempFreq[currentSubstr]++;
>                 if (tempFreq[currentSubstr] > wordFreq[currentSubstr]) {
>                     break;
>                 }
>             } else {
>                 break;
>             }
>         }
>         if (j == words.size()) {
>             result.push_back(i);
>         }
>     }
>     
>     return result;
> }
> ```
> 
> };


@Mux071  interpritted me wrongly
my code is not covering that edge case mentioned where s = "b" or s.size() = 1 but you updated the code so that it can cover the test case with **" s.size() = 1 "** but 
even my code is not covering that edge test case it has been accepted by the leetcode submission so - 

my point is that there is a edge case missing on leetcode

and also - I created this issue to contribute a test case to leetcode.

thank you 

sahil asrani
