### ISSUE TITLE
[BUG] - <答案顺序不对判错了>

### ISSUE THREAD

**Issue by s-phenix** [LeetCode-Feedback/LeetCode-Feedback#21865]
### LeetCode 用户名

Stonef

### 问题号码、标题和链接

131. 分割回文串 https://leetcode.cn/problems/palindrome-partitioning/description/?envType=study-plan-v2&envId=top-100-liked

### Bug Category

问题限制

### 描述

这题答案里面每个子数组中元素顺序不对判错了
<img width="564" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/57552153/28851ad2-c2a9-4a8e-9446-18835685a83e">

### 你使用的语言

Java

### 期望行为

改下判断规则

### 屏幕截图

<img width="564" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/57552153/59b3db8c-b749-43cd-8489-c111a6c2e018">

**Comment by stormsunshine** [comment]
你的输出是错误的，题目要求输出的子串拼接之后等于原始字符串 `s`，你的输出中存在首个子串是 `"b"` 的情况，这和预期结果是不符的。这和答案顺序无关。

**Comment by s-phenix** [comment]
看了下题目没说要子串拼接之后等于原始字符串啊，只是打印所有可能的情况

**Comment by amcones-lc** [comment]
感谢反馈，经核实该题目题解及测试用例暂无异常，力扣会不断努力给大家带来更好的学习社区！后续刷题学习中遇到问题，可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
