### ISSUE TITLE
Missing Test Case - 639 - Decode Ways II

### ISSUE THREAD

**Issue by abhi031098** [LeetCode-Feedback/LeetCode-Feedback#2187]
#### Your LeetCode username

abhi_u_03

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

TestCase:
Input:
`"1111111111111111111111111111****0*00**00**0*0*********0888888888888888888888888*********"`
My Output: 784071081
Expected Output: 313076501

The Solution is getting Accepted 100% Faster even though the code is showing Wrong for the above test case as it is huge. The current test cases barely check the modulo aspect of the program and hence it is accepting the solution however it shouldn't as somewhere the solution is missing modulo operation. Since this question requires a lot of conditional statements the solution is most likely to miss modulo operation somewhere. I have seen such test cases are only from 171 to 173 with 173 being the last test case. Hence any approach to the question by any user where **such huge cases and the nature of solution(many if and else's)** is not be adequately tested. The original Solution by **leetcode also uses such a conditional solution, although in a proper way that gives the right answer**. Hence there is ** no way of avoiding conditional used solutions and if used wrong in larger values it is bound to give wrong answer**, A proper solution will not provide 784071081 as an answer and give the expected outcome of 313076501.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int numDecodings(string s) {
        
        int n =s.size();
        unsigned long long int total = 1;
        unsigned long long int single_count_six=0,greater_six_count=0;
        unsigned long long int double_count =0;
        
        if(s[n-1]=='*'){
            total=9;
            single_count_six = 6;
            greater_six_count = 3;
        }
        else if(s[n-1]=='0')
        {
            total=1;
            single_count_six=1;
            greater_six_count=1;
        }
        else if(s[n-1]>'6')
        {
            greater_six_count=1;
        }
        else
            single_count_six=1;
        if(s[0]=='0')
            return 0;
        for(int i=n-2;i>=0;i--)
        {   
            //cout<<total<< " " <<single_count_six <<" " << greater_six_count <<" "<< double_count<< endl;
            if(s[i+1]=='0' && (s[i]>'2'|| s[i]=='0'))
                return 0;
            if(s[i]=='0')
            {
                greater_six_count = 0;
                single_count_six = 0;
                double_count=0;
                continue;
            }
            else if(s[i+1]=='0')
            {
                if(s[i]=='*')
                {   
                    unsigned long long int temp = greater_six_count+single_count_six;
                    if(temp==0)
                        temp=total;
                    if(i+2!=n)
                        double_count=temp*2;
                    else 
                        double_count= 2;
                    greater_six_count = 0;
                    single_count_six = 0;
                    total = single_count_six+greater_six_count+double_count;
                   
                }
                else if(s[i]>'6')
                {
                     greater_six_count = 0;
                     single_count_six = 0;
                     double_count=0;
                }
                else
                {
                      greater_six_count = 0;
                      single_count_six = 0;
                     if(s[i]<='2')
                        double_count=total;
                     else
                        double_count=0;
                }
                   
                continue;
            }
         
            if(s[i]=='*')
            {
                 unsigned long long int temp = single_count_six+greater_six_count;
                 unsigned long long int old_single_count_six = single_count_six;
                 unsigned long long int multiplier=2;
                if(s[i+1]>'6')
                    multiplier=1;
                total = double_count*9+ single_count_six*(9+multiplier)+ greater_six_count*10;
                single_count_six = double_count*6+(temp)*6;
                greater_six_count = (temp+double_count)*3;
                double_count = old_single_count_six*multiplier+ temp-old_single_count_six;
                continue;

            }

            else if(s[i]!='*' && s[i+1]=='*')
            {
                
                if(s[i]=='1')
                {
                     total = (single_count_six+greater_six_count)*2+double_count;
                }
                else if(s[i]=='2')
                    total = single_count_six*2+double_count+greater_six_count;
                if(s[i]>'6')
                {
                    greater_six_count = single_count_six+greater_six_count+double_count;
                    double_count = total - greater_six_count;
                    single_count_six=0;
                }
                else
                {
                    single_count_six = single_count_six+greater_six_count+double_count;
                    double_count = total -single_count_six;
                    greater_six_count=0;
                }
                continue;

            }
            
            
            if(s[i]>'2' || s[i+1]>'6' && s[i]=='2')
            {
                if(s[i]<='6')
                {
                    single_count_six = total;
                    greater_six_count=0;
                    if(s[i]!='2')
                        double_count=0;
                }
                else
                {
                    greater_six_count = total;
                    single_count_six =0;
                    double_count=0;
                }
                continue;
            }
            
            else
            {
                int temp = total;
                total = total+single_count_six+greater_six_count;
                single_count_six = temp;
                greater_six_count=0;
                double_count = total-single_count_six;
            }
            
            
            if(total>INT_MAX)
            {
                total = total%1000000007;
                single_count_six = single_count_six%1000000007;
                greater_six_count = greater_six_count%1000000007;
                double_count = double_count%1000000007;
            }
                
        }
       // cout<<total<< " " <<single_count_six <<" " << greater_six_count <<" "<< double_count<< endl;
        return total%1000000007;
        
    }
};
```

#### Language used for code

C++

#### Expected behavior

Input:
`"1111111111111111111111111111****0***0**0*0*********0888888888888888888888888*********"`
My Output: 784071081
Expected Output: 313076501

The Solution is getting Accepted 100% Faster even though the code is showing Wrong for the above test case as it is huge. The current test cases barely check the modulo aspect of the program and hence it is accepting the solution however it shouldn't as somewhere the solution is missing modulo operation. Since this question requires a lot of conditional statements the solution is most likely to miss modulo operation somewhere. I have seen such test cases are only from 171 to 173 with 173 being the last test case. Hence any approach to the question by any user where **such huge cases and the nature of solution(many if and else's)** is not be adequately tested. The original Solution by **leetcode also uses such a conditional solution, although in a proper way that gives the right answer**. Hence there is ** no way of avoiding conditional used solutions and if used wrong in larger values it is bound to give wrong answer**, A proper solution will not provide 784071081 as an answer and give the expected outcome of 313076501.

#### Screenshots

![image](https://user-images.githubusercontent.com/42272328/106352654-e3f15980-630a-11eb-9949-8fa1e48ffde4.png)

**Comment by lc-kay** [comment]
Hi @abhi031098 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @abhi031098 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
