### ISSUE TITLE
Missing Test Cases

### ISSUE THREAD

**Issue by Jai12396** [LeetCode-Feedback/LeetCode-Feedback#21876]
### LeetCode Username

Jai_Singhal

### Problem Number, Title, and Link

1482. Minimum Number of Days to Make m Bouquets https://leetcode.com/problems/minimum-number-of-days-to-make-m-bouquets/description/

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

I submitted my solution which got accepted.

Then I tried on the following test case:

bloomDay = [1,1,1,1]
m = 3
k = 1

Expected Output = 1
My Output = -1

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
class Solution {
    bool possible(vector<int>& bloomDay, int days, int m, int k){
        int cnt = 0;
        int i = 0;
        while(i < bloomDay.size()){
            int j;
            for(j = i; j < i + k; ++j){
                if(j >= bloomDay.size() || bloomDay[j] > days){
                    break;
                }
            }
            
            if(j == i + k){
                i = j;
                if(++cnt == m)
                    return true;
            }
            else
                i = j + 1;
        }

        return false;
    }
public:
    int minDays(vector<int>& bloomDay, int m, int k) {
        int num_flowers = bloomDay.size();
        if((long)m * k > num_flowers)
            return -1;

        long low = m * k, high = *max_element(bloomDay.begin(), bloomDay.end());

        int ans = -1;
        while(low <= high){
            long mid = low + (high - low) / 2;

            if(possible(bloomDay, mid, m, k)){
                ans = mid;
                high = mid - 1;
            }
            else
                low = mid + 1;
        }

        return ans;
    }
};
```

### Expected behavior

My code should not have had accepted due to failing test cases as above.

**Comment by Mux071** [comment]
![photo_2024-04-19_06-38-21](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/111518561/3c0be7f0-9cbb-4e81-ba16-ab6fcf6b4841)

**Comment by Mux071** [comment]
[https://leetcode.com/problems/minimum-number-of-days-to-make-m-bouquets/](url)
Bug Fixed...
