### ISSUE TITLE
[BUG] - <There is a bug at several testcases of >

### ISSUE THREAD

**Issue by Daniel-A-GS** [LeetCode-Feedback/LeetCode-Feedback#21879]
### LeetCode Username

dagasa

### Problem Number, Title, and Link

853, Car Fleet, https://leetcode.com/problems/car-fleet/description/

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

I ran the code on collaboratory and an online compiler and in both cases the output of my code for testcase: `target=10, position=[6,8], speed=[3,2]` is 2 (the expected by leetcode) but when the code is run on the website it says that my output was 1 and expected 2.

### Language Used for Code

Python/Python3

### Code used for Submit/Run operation

```bash
class Solution(object):
    def carFleet(self, target, position, speed):
        """
        :type target: int
        :type position: List[int]
        :type speed: List[int]
        :rtype: int
        """
        PosTime = []
        stack = []
        
        for p, s in zip(position,speed):
          PosTime.append([p,s])

        for p,s in sorted(PosTime)[::-1]:
          stack.append((target-p)/s)
          if len(stack) >= 2 and stack[-1] <= stack[-2]:
            stack.pop()

        return len(stack)
```

### Expected behavior

It was expected to output 2 but it outputs 1

**Comment by Lane-Powell** [comment]
I'm having the same issue, and it appears others are as well. Here is my code:
```
class Solution(object):
    def carFleet(self, target, position, speed):
        """
        :type target: int
        :type position: List[int]
        :type speed: List[int]
        :rtype: int
        """
        
        # Make a list of times it will take to reach target, sorted by initial position:
        time = [(target - p) / r for p, r in sorted(zip(position, speed))]

        fleets = 0
        max_time = 0
        
        # Iterate through list in reverse:
        for t in time[::-1]:
            # Compare each time to the current max. Higher times mean slower cars
            # so each new max time means a new fleet.
            if t > max_time:
                max_time = t
                fleets += 1

        return fleets
```

The environment documentation page is not helpful.

**Comment by Lane-Powell** [comment]
Returning to the problem after a couple of days, I discovered that you can execute print() within the Leetcode environment to debug. This is useful.

I quickly realized that results of division that I expected to be floats were integers. It turns out that in Python2, use of the division operator between integers always produces an integer. In Python3, it produces a float when a float would be expected. The solution is to convert integers into floats beforehand, or to make sure that you are using Python3 in Leetcode.
