### ISSUE TITLE
[BUG] - <1883 缺少测试用例>

### ISSUE THREAD

**Issue by oamuuvyi** [LeetCode-Feedback/LeetCode-Feedback#21881]
### LeetCode 用户名

oamuuvyi

### 问题号码、标题和链接

1883. 准时抵达会议现场的最小跳过休息次数 https://leetcode.cn/problems/minimum-skips-to-arrive-at-meeting-on-time/description/

### Bug Category

缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*

### 描述

通过测试的代码在以下测试用例中得出错误答案：

> [7,3,5,5]
32768
65536

### 你使用的语言

Java

### 你提交或者运行的代码

```bash
class Solution {
    public int minSkips(int[] dist, int speed, int hoursBefore) {
        int n = dist.length;
        hoursBefore *= speed;
        int[] dp = new int[n + 1];
        for (int i = 1; i <= n; i++) {
            dp[i] = dp[i - 1] + dist[i - 1];
            for (int j = i - 1; j > 0; j--) {
                dp[j] = Math.min(dp[j - 1] + dist[i - 1], ((dp[j] + dist[i - 1] - 1) / speed + 1) * speed);
            }
            dp[0] = ((dp[0] + dist[i - 1] - 1) / speed + 1) * speed;
        }
        for (int k = 0; k < n; k++) {
            if (dp[k] <= hoursBefore) {
                return k;
            }
        }
        return -1;
    }
}
```

### 期望行为

上述代码不应该通过测试，需要添加测试用例。

**Comment by amcones-lc** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by oamuuvyi** [comment]
> 你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

https://leetcode.cn/u/oamuuvyi/

**Comment by amcones-lc** [comment]
你好，当前该题已添加测试用例，奖励已发放。
