### ISSUE TITLE
[BUG] - <Blank Screen When Problem Clicked>

### ISSUE THREAD

**Issue by AipuAmeh** [LeetCode-Feedback/LeetCode-Feedback#21887]
### LeetCode Username

aipuameh

### Problem Number, Title, and Link

https://leetcode.com/explore/featured/card/the-leetcode-beginners-guide/692/challenge-problems/4423/

### Bug Category

Problem examples

### Bug Description

When I click on the linked problem to complete on my own before watching the walkthrough video, I am met with only a blank screen.

### Language Used for Code

JavaScript

### Expected behavior

I should see the problem that I clicked on and be able to complete it on my own. 

### Screenshots

<img width="1440" alt="Screenshot 2024-04-19 at 11 02 02 AM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/110988589/0c1dfab1-ad71-4f03-81de-da31e2578794">

**Comment by hyunholy** [comment]
I do have the same bug.
![스크린샷 2024-10-25 18 53 05](https://github.com/user-attachments/assets/7ee598fa-6fa8-4a3a-be22-ee1bbf83fd4a)
