### ISSUE TITLE
Missing Test Case - 921. Minimum Add to Make Parentheses Valid

### ISSUE THREAD

**Issue by VishalSharma2000** [LeetCode-Feedback/LeetCode-Feedback#2189]
#### Your LeetCode username

SVishal19

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
Question - I want to give an idea for the question

#### Description of the bug

There is no bug. I had an idea to make this question more interesting. 
If rather than adding a new parathesis to make the overall string valid, what if we allow the user to only rotate the parathesis. I'm not sure this question is already present or not.
So, the problem statement will be...

Given a string consisting of '(' and ')' of even length, you have to rotate a minimum number of parenthesis to make the string valid.
Sample test case:
s = ()))((
Ans: 2 - Final String = (())()

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@VishalSharma2000 Please contribute this question through https://leetcode.com/contribute/. Thank you for your time.
