### ISSUE TITLE
127. Word Ladder

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#219]
**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
The solutions given complexities are incorrect according to the given solution.

**what language is your code written in**
Python

**The code you submit/run**
```
class Solution(object):
    def ladderLength(self, b, e, w):
        w=set(w)
        if e not in w:
            return 0
        q=collections.deque([b])
        s=set(q)
        c=1
        while q:
            for i in xrange(len(q)):
                k=q.popleft()
                for j in xrange(len(k)):
                    for t in string.ascii_lowercase:
                        x=k[:j]+t+k[j+1:]
                        if x==e:
                            return c+1
                        if x in w and x not in s:
                            q.append(x)
                            s.add(x)
            c+=1
        return 0
```

**Expected behavior**
The complexity of the solutions is given as O(M×N), where M is the length of words and N is the total number of words in the input word list.

But the maximum no of possible neighbors a word can have in this problem is 26*M and the time it takes to form each word is M.

So the time complexity should be O(M^2 * N). My version of the solution is given as a reference.

**Comment by CooperCooperCooper** [comment]
Hi @
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
