### ISSUE TITLE
Test Case Example Typo -  931. Minimum Falling Path Sum

### ISSUE THREAD

**Issue by Bambooin** [LeetCode-Feedback/LeetCode-Feedback#2190]
#### Your LeetCode username
0x4C0DE

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Test case example typo:

Example 1:

Input: matrix = [[2,1,3],[6,5,4],[7,8,9]]
Output: 12

Example 1' output should be 13.

BTW: This problem's decription is modifed today for more clear decription, but it has one typo.

#### Code you used for Submit/Run operation

```
// https://leetcode.com/problems/minimum-falling-path-sum/
class Solution {
  public int minFallingPathSum(int[][] matrix) {
    int n = matrix.length;

    int min;
    for (int i = 1; i < n; i++) {
      for (int j = 0; j < n; j++) {
        min = matrix[i - 1][j];
        if (j - 1 >= 0) {
          min = Math.min(min, matrix[i - 1][j - 1]);
        }

        if (j + 1 < n) {
          min = Math.min(min, matrix[i - 1][j + 1]);
        }
        matrix[i][j] += min;
      }
    }

    min = Integer.MAX_VALUE;
    for (int i = 0; i < n; i++) {
      min = Math.min(min, matrix[n - 1][i]);
    }

    return min;
  }
}
```

#### Language used for code
Java

**Comment by lc-kay** [comment]
Hi @Bambooin 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Bambooin 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
