### ISSUE TITLE
[Test Case Added] -<2772 缺少测试用例>

### ISSUE THREAD

**Issue by Nanami131** [LeetCode-Feedback/LeetCode-Feedback#21918]
### LeetCode 用户名

Abigail____

### 问题号码、标题和链接

https://leetcode.cn/problems/apply-operations-to-make-all-array-elements-equal-to-zero/

### Bug Category

缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*

### 描述

我给的代码复杂度按照我的用例为n方级别，不应通过却可以通过。构造一个公差为负数的等差数列数组即可hack。猜测可能是代码逆向遍历，抓住了原有用例的漏洞

### 你使用的语言

C++

### 你提交或者运行的代码

```bash
class Solution {
public:
bool div(vector<int>& nums,int k){
    if(nums.size()<k)return false;
    for(int i=nums.size()-1;i>=0;i--){
        if(nums[i]==0)continue;
        int cur=nums[i];
        if(i-k+1<0)return false;
        for(int j=i;j>=i-k+1;j--){
            nums[j]-=cur;
            if(nums[j]<0)return false;
        }
    }
    return true;
}
    bool checkArray(vector<int>& nums, int k) {
       return div(nums,k);
    }
};
```

### 期望行为

附件里是测试用例，只需要简单cv添加即可，辛苦
[1.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/15053036/1.txt)

### 屏幕截图

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/128240515/8340ef4a-0cf7-4c83-93e1-2e31d392b9b9)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/128240515/05280231-7664-4487-a719-6ba981020344)

### 额外的上下文

用例在“期望行为”里。

**Comment by amcones-lc** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。
