### ISSUE TITLE
[BUG] - <官方解答有误>

### ISSUE THREAD

**Issue by semanym** [LeetCode-Feedback/LeetCode-Feedback#21919]
### LeetCode 用户名

accelerator-a5

### 问题号码、标题和链接

100276. 最短路径中的边 https://leetcode.cn/problems/find-edges-in-shortest-paths/description/

### Bug Category

不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*, 缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*, 力扣官方题解

### 描述

在这个测试样例中，官方给出的预期结果是错误的
[3123_testcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/15053039/3123_testcase.txt)

### 你使用的语言

None

### 期望行为

![图片](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/133956547/5ea44d6e-2373-4bcc-a003-738c351e1670)

**Comment by amcones-lc** [comment]
您好，在与相关团队核实后：***不处理***（distance must be at most 10**9）。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
