### ISSUE TITLE
[BUG] - 3121. Count the Number of Special Characters II

### ISSUE THREAD

**Issue by harshcode1** [LeetCode-Feedback/LeetCode-Feedback#21923]
### LeetCode Username

SONI_HARSH

### Problem Number, Title, and Link

https://leetcode.com/problems/count-the-number-of-special-characters-ii/

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

Input:-
word = "AbBCab"

Output :- 1

Expected :- 0

### Language Used for Code

Java

### Code used for Submit/Run operation

```bash
class Solution {
    public int numberOfSpecialChars(String word) {
        int cnt = 0;
        for(int i = 0;i<26;i++){
            char up = (char) ('A'+i);
            char low = (char) ('a'+i);
            if((word.indexOf(up)!=-1 && word.indexOf(low) != -1) && (word.indexOf(up) > word.indexOf(low))){
                cnt++;
            }
        }
        return cnt;
    }
}
```

### Expected behavior

I think it is completely wrong as my code is correct. It is the violation of Problem statement itself.

### Screenshots

![Screenshot 2024-04-22 011806](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/119169130/da9ac51b-116b-40f3-ab06-ac5e529f60d3)

**Comment by stormsunshine** [comment]
Why do you think the output should be 1 for this test case? Which letter is special in this test case?

**Comment by stormsunshine** [comment]
Why do you think the output should be 1 for this test case? Which letter is special in this test case?

**Comment by ChrisChika** [comment]
what? not it should be o

**Comment by harshcode1** [comment]
Sorry my bad! I went through the problem statement again then i realized that B is occuring twice and I need to count the last one  not the first. BTW thanks for helping.
