### ISSUE TITLE
Missing Test Case - 964. Least Operators to Express Number

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#2192]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution is accepted but fails on the following test case:

79
155800339

#### Code you used for Submit/Run operation

```
class Solution {
    Map<Integer, Integer> memo = new HashMap<>();
    public int leastOpsExpressTarget(int x, int target) {
        if (target == x) {
            return 0;
        }
        if (target < x) {
            return Math.min(target * 2 - 1, (x - target) * 2);
        }
        if (memo.containsKey(target)) {
            return memo.get(target);
        }
        double l = Math.log(target) / Math.log(x);
        if (Math.abs(l - Math.round(l)) < 0.00001) {
            memo.put(target, (int)Math.round(l) - 1);
        } else {
            int a = (int)Math.floor(l);
            int result = a + leastOpsExpressTarget(x, target - (int)Math.round(Math.pow(x, a)));
            if (target * 2 > Math.pow(x, a + 1)) { // tricky
                result = Math.min(result, a + 1 + leastOpsExpressTarget(x, (int)Math.round((Math.pow(x, a + 1) - target))));
            }
            memo.put(target, result);
        }
        return memo.get(target);
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/106361312-463a6200-62eb-11eb-916f-01666162cd0f.png)

#### Additional context

https://leetcode.com/problems/least-operators-to-express-number/discuss/208475/Java-DFS-with-memo

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
