### ISSUE TITLE
Missing Test Case - 964. Least Operators to Express Number

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#2193]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution is accepted but fails on the following test case:

97
178890910

#### Code you used for Submit/Run operation

```
class Solution {
    Map<String, Integer> cache = new HashMap<>();
    int x;
    public int leastOpsExpressTarget(int x, int target) {
        this.x = x;
        return dp(0, target, 1)-1;
    }
    
    private int dp(int i, int target, int factor) {
        String key = target + "," + i;
        if (cache.containsKey(key)) return cache.get(key);
        int ans;
        if (target == 0) {
            ans = 0;
        } else if (target == factor) {
            ans = (i==0?2:i);
        } else {
            int gap = target % (factor*x); //take care of smaller factor
            int cost = (i==0?2:i);
            int c = gap/factor;
            ans = Math.min(
						dp(i+1, target-gap, factor*x) + c*cost, //method 1, and go into take care of higher factor
                        dp(i+1, target+factor*x-gap, factor*x) + (x-c)*cost //method, and go into take care of higher factor
						  );
        }
        cache.put(key, ans);
        return ans;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/106361421-c8c32180-62eb-11eb-97a7-d2a4bfaacad4.png)

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
