### ISSUE TITLE
Official Java Solution - 970. Powerful Integers

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#2195]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Official Java solution is incorrect, fails on test case 92 and is not accepted

1
2
1000000

#### Code you used for Submit/Run operation

```
class Solution {
    public List<Integer> powerfulIntegers(int x, int y, int bound) {
        Set<Integer> seen = new HashSet();
        for (int i = 0; i < 18 && Math.pow(x, i) <= bound; ++i)
            for (int j = 0; j < 18 && Math.pow(y, j) <= bound; ++j) {
                int v = (int) Math.pow(x, i) + (int) Math.pow(y, j);
                if (v <= bound)
                    seen.add(v);
            }

        return new ArrayList(seen);
    }
}
```

#### Language used for code

Java

#### Expected behavior

Official Java solution needs to be fixed to pass problem test cases

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/106364063-586fcc80-62fa-11eb-91ed-8cefebe52f1a.png)

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
