### ISSUE TITLE
[BUG] - <1146缺少测试用例>

### ISSUE THREAD

**Issue by oamuuvyi** [LeetCode-Feedback/LeetCode-Feedback#21970]
### LeetCode 用户名

oamuuvyi

### 问题号码、标题和链接

1146. 快照数组 https://leetcode.cn/problems/snapshot-array/description/

### Bug Category

缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*

### 描述

通过测试的代码在以下测试用例中得出错误结果：
["SnapshotArray","set","snap","set","get"]
[[3],[0,5],[],[0,0],[0,0]]

### 你使用的语言

C++

### 你提交或者运行的代码

```bash
class SnapshotArray {
    int cnt{};
    vector<vector<pair<int, int>>> modify; 
public:
    SnapshotArray(int length) :modify(length) {}
    
    void set(int index, int val) {
        modify[index].emplace_back(cnt, val);
    }
    
    int snap() {
        return cnt++;
    }
    
    int get(int index, int snap_id) {
        auto i = ranges::upper_bound(modify[index], pair{ snap_id + 1, 0 });
        return i == modify[index].begin() ? 0 : (--i)->second;
    }
};
```

### 期望行为

需要添加测试用例。上述代码在上述的测试用例中得出错误答案，不应该通过测试。

### 屏幕截图

<img width="1403" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/47858802/97de03ea-f806-42ce-8246-d7a4d7870582">

**Comment by amcones-lc** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by oamuuvyi** [comment]
> 你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

https://leetcode.cn/u/oamuuvyi/

**Comment by amcones-lc** [comment]
你好，当前该题已添加测试用例，奖励已发放。
