### ISSUE TITLE
[BUG] - < 860. 柠檬水找零> 缺少测试用例

### ISSUE THREAD

**Issue by the-climb** [LeetCode-Feedback/LeetCode-Feedback#21988]
### LeetCode 用户名

climb

### 问题号码、标题和链接

860. 柠檬水找零 https://leetcode.cn/problems/lemonade-change/description/

### Bug Category

缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*

### 描述

缺少这样的用例：[10]
如下我提交的代码，其实是有误的，但是通过了。

### 你使用的语言

JavaScript

### 你提交或者运行的代码

```bash
var lemonadeChange = function (bills) {
    var fiveCount = 0
    var tenCount = 0
    for (var i = 0; i < bills.length; i++) {
        var bill = bills[i]
        if (bill === 5) {
            fiveCount++
        } else if (bill === 10) {
            if (fiveCount < 0) { // 这行判断范围写错，应该是fiveCount <= 0
                return false
            }
            tenCount++
            fiveCount--
        } else {
            if (fiveCount > 0 && tenCount > 0) {
                tenCount--
                fiveCount--
            } else if (fiveCount >= 3) {
                fiveCount -= 3
            } else {
                return false
            }
        }
    }

    return true
};
```

### 期望行为

补充一下测试用例

### 屏幕截图

![截屏2024-04-27 17 26 08](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/12878042/fcfddf8f-8425-45d4-8be1-7e002db2c820)
![截屏2024-04-27 17 26 51](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/12878042/ce735105-429a-45b0-aa58-c4a509582247)

**Comment by amcones-lc** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by the-climb** [comment]
leetcode.cn/u/climb-y/

**Comment by amcones-lc** [comment]
你好，当前该题已添加测试用例，奖励已发放。
