### ISSUE TITLE
[BUG] - <2639. 查询网格图中每一列的宽度> 缺少测试用例

### ISSUE THREAD

**Issue by wshaoYa** [LeetCode-Feedback/LeetCode-Feedback#21982]
### LeetCode 用户名

wshao

### 问题号码、标题和链接

2639. 查询网格图中每一列的宽度 https://leetcode.cn/problems/find-the-width-of-columns-of-a-grid/description/?envType=daily-question&envId=2024-04-27

### Bug Category

缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*

### 描述

缺少测试用例，导致有问题代码也能ac

### 你使用的语言

Go

### 你提交或者运行的代码

```bash
// 错误代码 但能ac
func findColumnWidth(grid [][]int) []int {
	var (
		m, n = len(grid), len(grid[0])
		ans  = make([]int, n)
	)

	//按列遍历
	for j := 0; j < n; j++ {
		var mx, mn = math.MinInt, math.MaxInt
		for i := 0; i < m; i++ {
			mx = max(mx, grid[i][j])
			mn = min(mn, grid[i][j])
		}
		var width int
		if mx >= 0 {
			width = len(strconv.Itoa(mx)) // 错误所在，应该=max(width,len(xxx)),但不比较也ac了
		}
		if mn < 0 {
			width = len(strconv.Itoa(mn))
		}
		ans[j] = width
	}

	return ans
}
```

### 期望行为

增加测试用例

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/66120483/5273af5a-5f6c-41b2-bad8-2f69fbe07e21)

**Comment by amcones-lc** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by wshaoYa** [comment]
@amcones-lc  leetcode.cn/u/wshaoya/

**Comment by amcones-lc** [comment]
你好，当前该题已添加测试用例，奖励已发放。
