### ISSUE TITLE
Can't submit for problem 116

### ISSUE THREAD

**Issue by wilmol** [LeetCode-Feedback/LeetCode-Feedback#22]
**What kind of the bug**
- [x] problem
- [ ] solution

**Describe the bug**
When I submit for problem 116 (https://leetcode.com/problems/populating-next-right-pointers-in-each-node/), get the message "An unknown error occurred. Please try again later, or contact us if this problem persists.".

**The code you submit/run**
```
class Solution {
    
    public Node connect(Node root) {
        if (root == null){
            return null;
        }
        // bfs
        Queue<Node> queue = new ArrayDeque<>();
        queue.add(root);
        
        while (!queue.isEmpty()){
            int levelSize = queue.size();
            for (int i = 0; i < levelSize; i++){
                Node node = queue.remove();
                Node next = i == levelSize - 1 ? null : queue.peek();
                node.next = next;
                if (node.left != null){
                    queue.add(node.left);
                }
                if (node.right != null){
                    queue.add(node.right);
                }
            }
        }
        return root;
    }
}
```

**Expected behavior**
Lets me submit my code.

**Screenshots**
![2020 03 08-16 59 46 501_chrome_558x94](https://user-images.githubusercontent.com/18110897/76156373-6a82d280-615e-11ea-8025-dd3afcd4cce1.png)

**Additional context**
I can submit the same code for problem 117 (https://leetcode.com/problems/populating-next-right-pointers-in-each-node-ii/), and it is accepted.

**Comment by CooperCooperCooper** [comment]
Hi @wilmol,

Thank you for reaching out to us! We were unable to reproduce the "Unknown Error" on our end because your code was successfully accepted on our end for both "Run Code" and "Submit". But I've notified our engineers to keep a closer eye to this issue. And if this issue reoccurs on your end, please don't hesitate to reopen this Github issue and let us know. We appreciate your time and support.

**Comment by wilmol** [comment]
@CooperCooperCooper I got it working by changing my code to:
```
class Solution {
    public Node connect(Node root) {
      return null;
    }
}
```
And submitting.
And then resubmitting the original code.
