### ISSUE TITLE
5. Longest Palindromic Substring

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#220]
#### Your LeetCode username
habaj

**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
The link given for Manacher's Algorithm is broken. Here is the provided hyperlink.
http://articles.leetcode.com/longest-palindromic-substring-part-ii/

**Comment by CooperCooperCooper** [comment]
Hi @leet212,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
