### ISSUE TITLE
The Dequeue Example is not working

### ISSUE THREAD

**Issue by JavacAman** [LeetCode-Feedback/LeetCode-Feedback#22009]
### LeetCode Username

Javac_aman

### Problem Number, Title, and Link

2 Example Queue  https://leetcode.com/explore/learn/card/queue-stack/228/first-in-first-out-data-structure/1355/

### Bug Category

Problem examples

### Bug Description

In  Queue - First-in-first-out Data Structure Part A
There is an Example for dequeue where it is written that 
you can click Dequeue below to see which element will be removed.

but that Dequeue button is not working

### Language Used for Code

None

### Expected behavior

When we are clicking on dequeue then - the first number that is 5 should we remove from the queue

### Screenshots

![Screenshot (55)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/60618495/74494062-6dc4-4961-b3ed-9575be0df764)

**Comment by tangzz3** [comment]
reply
