### ISSUE TITLE
Missing Testcase in 179. Largest Number

### ISSUE THREAD

**Issue by Swapnil-2001** [LeetCode-Feedback/LeetCode-Feedback#2200]
#### Your LeetCode username
Swap24

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
A faulty solution passes all test cases

#### Code you used for Submit/Run operation

```
class Solution:
    def largestNumber(self, nums: List[int]) -> str:
        h = defaultdict(list)
        for num in nums:  h[str(num)[0]].append(str(num))
            
        def compare(s1, s2):
            n1, n2 = len(s1), len(s2)
            i, j = 0, 0
            while i < len(s1) or j < len(s2):
                if s1[i % n1] > s2[j % n2]:  return True
                if s1[i % n1] < s2[j % n2]:  return False
                i += 1
                j += 1
            return s1[i % n1] > s2[j % n2]
                
        def customSort(arr):
            n = len(arr)
            for i in range(n):
                for j in range(n - i - 1):
                    if compare(arr[j], arr[j + 1]):
                        arr[j], arr[j + 1] = arr[j + 1], arr[j]
            return arr
        
        for key, value in h.items():
            h[key] = customSort(value)
        res = []
        for i in range(9, -1, -1):
            curr = h[str(i)]
            for j in range(len(curr) - 1, -1, -1):  
                res.append(curr[j])
        res = ''.join(res).lstrip('0')
        return '0' if not res else res
        
```

#### Language used for code
Python 3

#### Expected behavior
The solution was not supposed to pass all test cases but it did

#### Screenshots

![Largest Number - LeetCode - Google Chrome 31-01-2021 01_41_04](https://user-images.githubusercontent.com/53232360/106367001-863e2b00-6365-11eb-8c64-478cc7c8edf6.png)

#### Additional context
A testcase that could be added is [1113, 111311]

**Comment by lc-kay** [comment]
Hi @Swapnil-2001 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Swapnil-2001 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
