### ISSUE TITLE
[BUG] - 636. Exclusive Time of Functions - test case incorrect

### ISSUE THREAD

**Issue by sophyphreak** [LeetCode-Feedback/LeetCode-Feedback#22007]
### LeetCode Username

sophyphreak

### Problem Number, Title, and Link

https://leetcode.com/problems/exclusive-time-of-functions/description/

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

Input:
```
n =
3
logs =
["1:start:0","0:start:2","1:start:3","2:start:4","2:end:4","0:end:6","1:end:7","1:end:8"]
```

Output:
```
[2,6,1]
```

The output is correct, but the test case has a problem. Only the top function should ever end, so function 0 should not end before function 1. The last three strings in the `logs` array should read: `"1:end:6","0:end:7","1:end:8"`. If the user writes a solution that ignores the id in the case of `end` strings, they will get the right answer. But if they write a solution that is not agnostic to the ids in the `end` strings, they might get a wrong answer. Also, this test case makes things very confusing since it doesn't line up with the problem description.

Thanks!

### Language Used for Code

None

### Code used for Submit/Run operation

```bash
/**
 * @param {number} n
 * @param {string[]} logs
 * @return {number[]}
 */
var exclusiveTime = function(n, logs) {
    const stack = []
    let prevTime = 0
    const result = new Array(n).fill(0)

    for (const log of logs) {
        let [id, startOrEnd, time] = log.split(":")
        id = +id
        time = +time
        const isStart = startOrEnd === "start"
        if (isStart) {
            if (stack.length) {
                result[stack[stack.length-1]] += time - prevTime
            }
            stack.push(id)
            prevTime = time
        } else {
            result[stack.pop()] += time - prevTime + 1
            prevTime = time + 1
        }
    }
    return result
};
```

### Expected behavior

Expected and actual behavior match, but the ids within the test case are in the wrong order.

**Comment by heqiao** [comment]
Indeed, added a quick illustration.

    2:                         |_____|            

    1:                   |_____|                       |_____|

    0:             |_____|           |___________|
                                           ^^^^^^^^^^ should end after task 1 above
    1: |___________|                             |_____|

**Comment by zhengrui315** [comment]
According to the expected output `[2,6,1]`, the correct input should be 
```
["1:start:0","0:start:2","1:start:3","2:start:4","2:end:4","1:end:6","0:end:7","1:end:8"]
```
