### ISSUE TITLE
有效括号测试用例本地可以跑通官网结果不一致

### ISSUE THREAD

**Issue by wjsw1781** [LeetCode-Feedback/LeetCode-Feedback#22010]
### LeetCode 用户名

1781591279@qq.com

### 问题号码、标题和链接

https://leetcode.cn/problems/valid-parentheses/

### Bug Category

问题描述

### 描述

测试用例本地可以跑通,官网结果不一致

### 你使用的语言

Python/Python3

### 你提交或者运行的代码

```bash
stack=[]

    
    def isValid(self, s: str) -> bool:

        for i in s:
            if i in ["(","[","{"]:
                self.stack.append(i)
            else:
                if i==')':
                    if self.stack[-1]!='(':
                        return False
                    else:
                        self.stack.pop()
                if i==']':
                    if self.stack[-1]!='[':
                        return False
                    else:
                        self.stack.pop()
                if i=='}':
                    if self.stack[-1]!='{':
                        return False
                    else:
                        self.stack.pop()
        if len(self.stack)>0:
            return False
        return True
```

### 期望行为

我自己电脑可以为True

### 屏幕截图

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/28215744/048f8351-df2c-446b-9e8e-15286da6f88d)

### 额外的上下文

没有

**Comment by wjsw1781** [comment]
我没开会员 无法调试  只能这样打印 发现竟然会多出一个( 这怎么可能  
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/28215744/060c4320-00a0-47d8-9e0c-bc8036ed3015)

官方调用函数肯定是有问题的

**Comment by wjsw1781** [comment]
同样这样也会多出来 一个 (  瞎搞吗???

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/28215744/ab6e2d98-6f32-4c31-993d-4d26fe033974)

**Comment by wjsw1781** [comment]
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/28215744/3a4f2a02-7b86-4daa-a2b5-b5204bdd9c8b)


你看我本地是完全没问题的

**Comment by wjsw1781** [comment]
我好像知道为什么了  后台调用的逻辑应该缓存了上次测试用例的结果 而不是,对每次新的测试用例进行新的代码示例化   如果我把     stack=[] 写到isValid里面就可以通过了
但是这也是个问题,希望官方好好调整下运行逻辑

**Comment by kenlau46** [comment]
Leetcode specified do not use any static and global variable (or at least be careful) when using their platform, see https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why
Also Leetcode behaviour is explained in the following issue https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/21955#issuecomment-2074359219

**Comment by amcones-lc** [comment]
感谢反馈，经核实该题目题解及测试用例暂无异常，力扣会不断努力给大家带来更好的学习社区！后续刷题学习中遇到问题，可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
