### ISSUE TITLE
[BUG] - Missing test case for 2441

### ISSUE THREAD

**Issue by ashipo** [LeetCode-Feedback/LeetCode-Feedback#22036]
### LeetCode Username

FellowKid

### Problem Number, Title, and Link

2441. Largest Positive Integer That Exists With Its Negative https://leetcode.com/problems/largest-positive-integer-that-exists-with-its-negative/

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

Code below is incorrect and returns wrong answer for `[-2,1,1]` testcase but was accepted.

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
class Solution {
public:
    int findMaxK(vector<int>& nums) {
        std::sort(nums.begin(), nums.end());
        int l = 0;
        int r = nums.size() - 1;
        while (l < r && nums[l] < 0 && nums[r] > 0) {
            auto positive = nums[r];
            while (nums[l] * -1 > positive) { l++; }
            if (l < r && abs(nums[l]) == positive) { return positive; }
            r--;
        }
        return -1;
    }
};
```

### Expected behavior

Code fails to pass.

**Comment by adityakhade321** [comment]
// use this code
class Solution {
public:
    int findMaxK(vector<int>& nums) {
        sort(nums.begin(),nums.end());
        int l=0,r=nums.size()-1;
        while(l<r){
            if((-nums[l])==(nums[r])){
                return nums[r];
            }else if((-nums[l])<(nums[r])){
                r--;
            }else if((-nums[l])>(nums[r])){
                l++;
            }
        }
        return -1;
    }
};
