### ISSUE TITLE
[BUG] - <857缺少必要的测试样例>

### ISSUE THREAD

**Issue by fwewrra** [LeetCode-Feedback/LeetCode-Feedback#22043]
### LeetCode 用户名

yzc

### 问题号码、标题和链接

857. 雇佣 K 名工人的最低成本 https://leetcode.cn/problems/minimum-cost-to-hire-k-workers/description/

### Bug Category

缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*

### 描述

官方答案在代码中使用1e9作为res的上限，然而存在合理的测试样例，其结果大于1e9

### 你使用的语言

C++

### 你提交或者运行的代码

```bash
class Solution {
public:
    double mincostToHireWorkers(vector<int>& quality, vector<int>& wage, int k) {
        int n = quality.size();
        vector<int> h(n, 0);
        iota(h.begin(), h.end(), 0);
        sort(h.begin(), h.end(), [&](int& a, int& b) {
            return quality[a] * wage[b] > quality[b] * wage[a];
        });
        double res = 1e9;
        double totalq = 0.0;
        priority_queue<int, vector<int>, less<int>> q;
        for (int i = 0; i < k - 1; i++) {
            totalq += quality[h[i]];
            q.push(quality[h[i]]);
        }
        for (int i = k - 1; i < n; i++) {
            int idx = h[i];
            totalq += quality[idx];
            q.push(quality[idx]);
            double totalc = ((double) wage[idx] / quality[idx]) * totalq;
            res = min(res, totalc);
            totalq -= q.top();
            q.pop();
        }
        return res;
    }
};

作者：力扣官方题解
链接：https://leetcode.cn/problems/minimum-cost-to-hire-k-workers/solutions/1815034/gu-yong-k-ming-gong-ren-de-zui-di-cheng-rsz3t/
来源：力扣（LeetCode）
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。
```

### 期望行为

导致bug的原因是这段代码
` double res=1e9;`
在leetcode的官方答案中采用的是1e9，但是这是一个不合适的上限，存在测试样例的结果大于该数值。
建议添加如下测试样例：
k=n=10000
quality[0]=1; 
for i in [1,9999],quality[i]=10000.
wage[0]=10000

**Comment by amcones-lc** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by fwewrra** [comment]
leetcode.cn/u/yzc-14/



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年10月16日 08:57 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [LeetCode-Feedback/LeetCode-Feedback] [BUG] - <857缺少必要的测试样例> (Issue #22043) |

你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by amcones-lc** [comment]
你好，当前该题已添加测试用例，奖励已发放。

**Comment by fwewrra** [comment]
感谢
