### ISSUE TITLE
[BUG] - 165 - missing test case

### ISSUE THREAD

**Issue by giner** [LeetCode-Feedback/LeetCode-Feedback#22049]
### LeetCode Username

giner

### Problem Number, Title, and Link

165. Compare Version Numbers https://leetcode.com/problems/compare-version-numbers

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

Missing case where revision is exeeds 9

### Language Used for Code

Ruby

### Expected behavior

The problem should have a test case which fails on assumption that revision can't exeed 9
```
"2.1.2"
"1.15.1"
```

**Comment by naXa777** [comment]
Can you share a code that's getting accepted, but fails on the proposed test case?
```
"2.1.2"
"1.15.1"
```

**Comment by giner** [comment]
```ruby
def compare_version(version1, version2)
    v1 = calculate_version(version1)
    v2 = calculate_version(version2)

    if v1 > v2
        1
    elsif v2 > v1
        -1
    else
        0
    end
end

def calculate_version(str)
    del = 1

    str.split('.').map do |v|
        r = v.to_i * del
        del = del / 10.0
        r
    end.sum
end
```
