### ISSUE TITLE
Grammer is wrong in - Missing Test Case - 617. Merge Two Binary Trees

### ISSUE THREAD

**Issue by aaronclare3** [LeetCode-Feedback/LeetCode-Feedback#2204]
#### Your LeetCode username
aaron_clare3

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language

#### Description of the bug

"Given two binary trees and imagine that when you put one of them to cover the other..."
should be
"Given two binary trees, imagine that..."

**Comment by lc-kay** [comment]
Hi @aaronclare3 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @aaronclare3 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
