### ISSUE TITLE
Missing Test Case - 268. Missing Number

### ISSUE THREAD

**Issue by AdityaPratapSingh888** [LeetCode-Feedback/LeetCode-Feedback#22063]
[1,2,3]

**Comment by utsav1208** [comment]
[1,2,3,5,4,6,7,9,8,11,34]

**Comment by AdityaPratapSingh888** [comment]
> [1,2,3,5,4,6,7,9,8,11,34]
> 

How can you have 34 in the array of length n where n<34.

**Comment by utsav1208** [comment]
> > [1,2,3,5,4,6,7,9,8,11,34]
> 
> How can you have 34 in the array of length n where n<34.



> > [1,2,3,5,4,6,7,9,8,11,34]
> 
> How can you have 34 in the array of length n where n<34.

Yeah actually I want to write 3 ,4 again

**Comment by AdityaPratapSingh888** [comment]
I think the question is not designed that way.
