### ISSUE TITLE
Missing Test Case - 655. Print Binary Tree

### ISSUE THREAD

**Issue by msaqib4203** [LeetCode-Feedback/LeetCode-Feedback#2207]
#### Your LeetCode username

msaqib4203

#### Category of the bug
655. Print Binary Tree
- [x] Solution
- [x] Language

#### Description of the bug

On clicking 'Use example test cases', all example test cases are not getting populated in the 
test cases input text area.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior

On clicking use 'Example test case', all three test cases listed in the problem description must get 
filled in the test case text area.

**Comment by lc-kay** [comment]
Hi @msaqib4203 
Thank you for your time. I've filed this feature request to our team to take into consideration. However, please keep in mind that the GitHub repo is open for content-related issues. We encourage you to share more content-related issues here with us for [valid content contribution rewards](https://leetcode.com/discuss/general-discussion/526802/File-Problem-and-Solution-Content-Issues-to-Our-GitHub-Public-Feedback-Repo-Now!). For any non-content related issues or request, please contact us at support@leetcode.com. Thank you again for your support and understanding.
