### ISSUE TITLE
[BUG] - To add a test case to a problem

### ISSUE THREAD

**Issue by Pavan4217** [LeetCode-Feedback/LeetCode-Feedback#22071]
### LeetCode Username

Pavan_venkata_naga_manoj

### Problem Number, Title, and Link

14.Longest Common Prefix

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

In the Longest Common Prefix problem we do not have a test case which satisfies the question i have seen a solution where we can compare only the lowest length string and the highest length string and return the answer but the question is to find the longest subsequence so if there is a test case like ['flow',''hello,'flight'] this would return the fl as output but the correct output is '' as there is no sequence in the hello in the list.

### Language Used for Code

Python/Python3

### Code used for Submit/Run operation

```bash
class Solution:
    def longestCommonPrefix(self, strs: List[str]) -> str:
        result = ""
        sorted_s = sorted(strs)
        fst = sorted_s[0]
        lst = sorted_s[-1]
        for i in range(min(len(fst),len(lst))):
            if fst[i] != lst[i]:
                break
            else:
                result += fst[i]
        return result
```

### Expected behavior

In the Longest Common Prefix problem we do not have a test case which satisfies the question i have seen a solution where we can compare only the lowest length string and the highest length string and return the answer but the question is to find the longest subsequence so if there is a test case like ['flow',''hello,'flight'] this would return the fl as output but the correct output is '' as there is no sequence in the hello in the list.

**Comment by ChrisChika** [comment]
the code you provided works on the testcase  " ['flow',''hello,'flight']" it gives "" when I try it out myself.

**Comment by ChrisChika** [comment]
also look at example two on that problem , it test what you were talking about.
