### ISSUE TITLE
[BUG] - <缺陷标题>

### ISSUE THREAD

**Issue by zoom28zoom** [LeetCode-Feedback/LeetCode-Feedback#22086]
### LeetCode 用户名

听听

### 问题号码、标题和链接

100283. 同位字符串连接的最小长度 https://leetcode.cn/problems/minimum-length-of-anagram-concatenation/description/

### Bug Category

缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*

### 描述

第1、4、10名的第3题用"aabb"均可hack。

### 你使用的语言

Python/Python3

### 你提交或者运行的代码

```bash
class Solution:
    def minAnagramLength(self, s: str) -> int:
        mp = collections.defaultdict(int)
        for c in s:
            mp[c]+=1
        g = 0
        for k,v in mp.items():
            g = math.gcd(g,v)
        ans = 0
        for k,v in mp.items():
            ans+= v//g
        return ans
```

### 期望行为

对于测试用例“aabb”，期望输出为 4，但许多生成输出 2 的代码仍然被接受

### 屏幕截图

![error](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/168950368/8f101b00-ad0c-4800-ad56-7d5c16cf74e5)

**Comment by amcones-lc** [comment]
感谢反馈，经核实该题目已包含该测试用例，力扣会不断努力给大家带来更好的学习社区！后续刷题学习中遇到问题，可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
