### ISSUE TITLE
952. Largest Component Size by Common Factor

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#221]
#### Your LeetCode username
habaj

**What kind of the bug**
- [ ] problem
- [x] solution
- [ ] language

I wished to provide a solution for the problem that is not available. It beats 100% solutions in both categories. The current solution has a complexity of O(N * sqrt{W}) where N is the length of A, and W=max(A[i])

The solution I implemented can reduce it to O(N * log{W}) where N is the length of A, and W=max(A[i])
The time it takes to factorize each number is the no of prime factors in it, which in worst case will be log(n) if the number is a power of 2.

**What language is your code written in**
Python

**The code you submit/run**
```
class Solution(object):
    def largestComponentSize(self, a):
        def parent(x):
            while root[x]!=x:
                root[x]=root[root[x]]
                x=root[x]
            return x
        
        def union(x,y):
            px=parent(x)
            py=parent(y)
            if px!=py:
                if size[px]>size[py]:
                    px,py=py,px
                size[py]+=size[px]
                root[px]=py
                
        def factorize(index,val):
            while val!=1:
                if smallestPrimeFactor[val] not in factorParent:
                    factorParent[smallestPrimeFactor[val]]=index
                union(index,factorParent[smallestPrimeFactor[val]])
                val/=smallestPrimeFactor[val]
                
        m=max(a)+1
        smallestPrimeFactor=range(m)
        for i in xrange(2,int(pow(m,0.5))+1):
            if smallestPrimeFactor[i]==i:
                for j in xrange(i*i,m,i):
                    if smallestPrimeFactor[j]==j:
                        smallestPrimeFactor[j]=i
                        
        n=len(a)
        size=[1]*n
        root=range(n)
        factorParent={}
        for i in xrange(n):
            factorize(i,a[i])
        return max(size)
```

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/63714778/80651189-12e45180-8a93-11ea-9bdf-b7db1c210f14.png)

**Comment by CooperCooperCooper** [comment]
Hi @leet212,
Thank you for reaching out to us. Once you've shared the solution here, I'll relay it to our team to consider and share the feedback here with you.

**Comment by leet212** [comment]
Thanks for the update @CooperCooperCooper . I have updated the issue with the solution.

**Comment by CooperCooperCooper** [comment]
Hi @leet212,
Thank you for sharing. I've relayed this issue to our team to investigate.

**Comment by leet212** [comment]
Hello @CooperCooperCooper . Any update on this?

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for your time. Since the article rewrite will take a while, we will be closing this ticket for now. Since your ticket has enabled the change happen, your account has been granted with the 100 LeetCoins for this change.
