### ISSUE TITLE
Missing Test Case - 209. Minimum Size Subarray Sum

### ISSUE THREAD

**Issue by novator55** [LeetCode-Feedback/LeetCode-Feedback#2210]
#### Your LeetCode username
novator132

#### Category of the bug
- [ ] Solution

#### Code you used for Submit/Run operation

```
class Solution:
    def minSubArrayLen(self, s: int, nums: List[int]) -> int:
    	Sum = 0
    	minn = 10000001
    	i = 0
    	if len(nums)<1: return 0
    	elif len(nums)==1: return nums[0]

    	for j in range(0, len(nums)):
    		if Sum <s: Sum+=nums[j]
    		while Sum>=s:
    			minn=min(minn, j - i+1)
    			Sum-=nums[i]
    			i+=1
    	if minn==10000001: return 0
    	return minn
```

#### Language used for code
Python

#### Screenshots

![error](https://user-images.githubusercontent.com/58919207/106396252-e392b480-6417-11eb-90fb-2cf6d1b30c29.png)
![error](https://user-images.githubusercontent.com/58919207/106396257-e9889580-6417-11eb-81ed-319e78ca67e5.png)
![error](https://user-images.githubusercontent.com/58919207/106396274-f7d6b180-6417-11eb-99f7-6826a1eb56b0.png)

**Comment by lc-kay** [comment]
Hi @novator55 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @novator55 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
