### ISSUE TITLE
Missing Test Case and Incorrect Author Solution : 378. Kth Smallest Element in a Sorted Matrix

### ISSUE THREAD

**Issue by viniru** [LeetCode-Feedback/LeetCode-Feedback#2211]
#### Your LeetCode username

niranjvin

#### Category of the bug
- [x] Solution
- [x] Testcase 

#### Description of the bug

In order to find the Kth Element in a sorted matrix, the described solution uses min heap as follows. The first elements of every row are added into the heap(upto row => min (k, n). Then, we poll() the min element from the heap (k) times and each time, we add the element that was present in the next column in that row(polled element row). 

But this solution fails to explain what would one have to do , if there were duplicates. which row would you choose for the next element ? 

Input:

[[1,2,4],[2,5,6]]
4

#### Code you used for Submit/Run operation

```
class Solution {
    
    public int kthSmallest(int[][] matrix, int k) {
        
        
        if(matrix == null || matrix.length == 0 || matrix[0].length == 0) return -1;
        Queue<Point> minHeap = new PriorityQueue<>((a,b) -> a.val - b.val);
        
        Set<Point> set = new HashSet<>();
    
        int count = 0;
        minHeap.offer(new Point(0,0,matrix[0][0]));
        set.add(new Point(0,0,matrix[0][0]));
        
        while(true){

            Point pt = minHeap.poll();
            if(++count == k) return pt.val;

            if( pt.row != matrix.length - 1 ) {
                Point p  = new Point(pt.row+1,pt.col, matrix[pt.row+1][pt.col]);
                if(!set.contains(p)){
                    // System.out.println(p.val);
                    set.add(p);
                    minHeap.offer(p);
                }
            }

            if(pt.col != matrix[0].length - 1) {
                Point p = new Point(pt.row, pt.col+1, matrix[pt.row][pt.col+1]);
                if(!set.contains(p)){
                    // System.out.println(p.val);
                    set.add(p);
                    minHeap.offer(p);
                }
            }            
        }        
    }
    
    
    class Point {
        int row;
        int col;
        int val;
        Point(int r, int c , int val){
            this.row = r;
            this.col = c;
            this.val = val;
        }
        
        @Override
        public boolean equals(Object obj){
            if(this == obj) return true;
            if(obj == null) return false;
            if(obj.getClass() != Point.class) return false;
            Point ob = (Point) obj;
            if(this.row != ob.row || this.col != ob.col || this.val != ob.val) return false;
            return true;
        }
        
        @Override
        public int hashCode(){
            return Integer.parseInt(this.row + "" + this.col);
        }
    }
    
}
```

#### Language used for code

Java

#### Expected behavior

I feel the min heap solution approach is incorrect as it cannot handle duplicates.  Maybe there is some way to fix the same approach, I am not sure. I followed a different approach though(code is self explanatory). 

[[1,2,4],[2,5,6]]
4

#### Screenshots

![Screenshot from 2021-02-01 01-37-17](https://user-images.githubusercontent.com/32838713/106396475-31b2b280-642e-11eb-94f6-30823301952e.png)
![Screenshot from 2021-02-01 01-37-45](https://user-images.githubusercontent.com/32838713/106396504-5ad34300-642e-11eb-993e-cc10950cae68.png)

#### Additional context

You can clearly see in the pics (I have used author's solution) . My test case did not pass, But the solution got accepted

**Comment by lc-kay** [comment]
Hi @viniru 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @viniru 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
