### ISSUE TITLE
[Add TestCase] - <https://leetcode.com/problems/minimum-length-of-anagram-concatenation/ Test Case>

### ISSUE THREAD

**Issue by oo101010** [LeetCode-Feedback/LeetCode-Feedback#22127]
### LeetCode Username

00101010

### Problem Number, Title, and Link

3138, Minimum Length of Anagram Concatenation, https://leetcode.com/problems/minimum-length-of-anagram-concatenation/description/

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

Missing testcase
Test case "aabbbb"

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
class Solution {
public:
    int minAnagramLength(string s) {
        vector<int> cnt(26,0);
        int i;
        for(auto c:s) {
            cnt[c-'a']++;
        }
        sort(cnt.begin(),cnt.end());
        if(cnt[24]==0) {
            return 1;
        }
        int calgcd = __gcd(cnt[25],cnt[24]);
        for(i=23;i>=0;i--) {
            if(cnt[i]==0) {
                break;
            }
            calgcd = __gcd(calgcd, cnt[i]);
        }
        int ans = 0;
        for(i=0;i<26;i++) {
            ans = ans + cnt[i]/calgcd;
        }
        return ans;
        
    }
};
```

### Expected behavior

Expected output 6
But output 3 accepted

**Comment by Parshwa1234** [comment]
Same issue
