### ISSUE TITLE
[BUG] - <缺陷标题>

### ISSUE THREAD

**Issue by spasre** [LeetCode-Feedback/LeetCode-Feedback#22143]
### LeetCode 用户名

convective_rain

### 问题号码、标题和链接

3138. 同位字符串连接的最小长度 https://leetcode.cn/problems/minimum-length-of-anagram-concatenation/

### Bug Category

缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*

### 描述

测试用例不完善。

### 你使用的语言

C++

### 你提交或者运行的代码

```bash
class Solution {
public:
    int minAnagramLength(string s) {
        int n = s.size();
        auto check = [&](int p) -> bool {
            int cnt[26];
            memset(cnt, 0, sizeof cnt);
            for (int i = 0; i < p; ++i) {
                ++cnt[(int)s[i] - 'a'];
            }
            int comp[26];
            for (int i = 1; i * p < n; ++i) {
                memset(comp, 0, sizeof comp);
                for (int j = 0; j < p; ++j) {
                    ++comp[(int)s[i * p + j] - 'a'];
                }
                for (int j = 0; j < 26; ++j) {
                    if (comp[j] != cnt[j]) return false;
                }
            }
            return true;
        };
        int k = n;
        for (int i = 2; i * i <= k; ++i) {
            while (n % i == 0 && check(n / i)) n /= i;
            while (k % i == 0) k /= i;
        }
        if (check(n / k)) n /= k;
        return n;
    }
};
```

### 期望行为

添加测试用例
"ababaabb"

**Comment by spasre** [comment]
![Uploading f682ead74ca3e484920d7d46d8d206b4.png…]()

**Comment by amcones-lc** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by spasre** [comment]
我的个性域名是convective-rain。


小企鹅
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LeetCode-Feedback/LeetCode-Feedback"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月28日(星期三) 上午10:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LeetCode-Feedback/LeetCode-Feedback] [BUG] - <缺陷标题&gt; (Issue #22143)





 
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by amcones-lc** [comment]
你好，当前该题已添加测试用例，奖励已发放。
