### ISSUE TITLE
[BUG] - <缺陷标题>

### ISSUE THREAD

**Issue by EricZhangJr** [LeetCode-Feedback/LeetCode-Feedback#22153]
### LeetCode 用户名

ericzhangjr

### 问题号码、标题和链接

197上升的温度 https://leetcode.cn/problems/rising-temperature/description/

### Bug Category

不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*

### 描述

测试用例输出不正确，以下是测试input的部分数据：
30   | 2001-09-22 | -68   
1043 | 2001-09-21 | -92   
id 30的温度比前一天的大，我的代码输出了30，测试用例没有输出30     

### 你使用的语言

mySQL

### 你提交或者运行的代码

```bash
SELECT W2.id
FROM Weather W1, Weather W2
WHERE W1.recordDate=W2.recordDate-1 AND W1.Temperature<W2.Temperature
```

### 期望行为

删除该测试用例

**Comment by amcones-lc** [comment]
您好，在与相关团队核实后：***不处理***（预期结果输出中含有 `30`，可能是其它地方有错误）。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
