### ISSUE TITLE
[BUG] - 543 should be classified as medium

### ISSUE THREAD

**Issue by miparnisari** [LeetCode-Feedback/LeetCode-Feedback#22150]
### LeetCode Username

miparnisari

### Problem Number, Title, and Link

543. Diameter of Binary Tree https://leetcode.com/problems/diameter-of-binary-tree/description/

### Bug Category

Problem description

### Bug Description

This problem should not be classified as easy. It should be a medium. Look at the discussion section and you'll see most people agree on this.

### Language Used for Code

Go

### Expected behavior

n/a

**Comment by NathanWailes** [comment]
Was this auto-closed by a GPT bot? What does "the query is invalid" mean? That sounds like something a GPT would say.
