### ISSUE TITLE
[BUG] - PHP Converting float to int on problem 50 test case 30, incorrectly marking correct answers as wrong

### ISSUE THREAD

**Issue by fgtrtd** [LeetCode-Feedback/LeetCode-Feedback#22156]
### LeetCode Username

hookem1990

### Problem Number, Title, and Link

50. Pow(x, n) https://leetcode.com/problems/powx-n/solutions/3556240/

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

The following test case will always fail because it's being converted to an int.

Wrong Answer
305 / 307 testcases passed

Editorial
Input
x =
1.0000000000001
n =
-2147483648

 If you put nothing else but `var_dump($x);` you will see the following output:
```
int(1)
```

### Language Used for Code

PHP

### Code used for Submit/Run operation

```bash
class Solution {

    /**
     * @param Float $x
     * @param Integer $n
     * @return Float
     */
    function myPow($x, $n) {
       var_dump($x); // will output int(1)

        $result = $this->helper($x, abs($n));

        if ($n < 0) {
            return 1 / $result;
        } else {
            return $result;
        }
    }

    function helper(float $x, $n) {
        if ($x == 0) {
            return 0;
        }

        if ($n == 0) {
            return 1;
        }

        $result = $this->helper($x, intdiv($n, 2));
        $result = $result * $result;

        if ($n % 2 == 1) {
            $result = $result * $x;
        }

        return $result;
    }
}
```

### Expected behavior

This test case should pass. PHP is interpreting $x as an int, making it impossible to get this right.

**Comment by fgtrtd** [comment]
Hi, not sure why you closed this.  Even the bulit-in PHP code does not work. Notice the following comments are also having this issue. If there is a passing PHP solution, please post it. Test case 305 always fails, no matter what because it is being cast to an int instead of a float. Please fix the backend parameter. 

```
class Solution {

    /**
     * @param Float $x
     * @param Integer $n
     * @return Float
     */
    function myPow($x, $n) {
        return (float) pow((float) $x, (float) $n);
    }
}
```

Other comments:
https://leetcode.com/problems/powx-n/solutions/3039929/php-top-speed-and-memory-jan-23/
https://leetcode.com/problems/powx-n/solutions/4992620/there-is-an-error-in-the-task-or-php-works-incorrect/

**Comment by yoanm** [comment]
Got the same issue, spent hours figuring out why.
Issue seems simply the input provided by leetcode, not PHP at all.
Manually running the code with right inputs provides the rigth answer (once rounded to five digits) ....
```php
function powTest(float $x, int $n): float {
    if(0 === $n) {
        return 1.0;
    }
    if ($n < 0) {
        return 1 / powTest($x, ($n * -1));
    }
    $res = 1.0;

    if (($n % 2) == 1) {
        $res = $x;
    }

    return $res * powTest($x * $x, ($n >> 1));
}
printf("%s\n", round(powTest(1.0000000000001, -2147483648), 5)); // Output "0.99979"
```
