### ISSUE TITLE
Solutions don't run - 970. Powerful Integers

### ISSUE THREAD

**Issue by vishalcool88** [LeetCode-Feedback/LeetCode-Feedback#2216]
#### Your LeetCode username
vishalagrawal23

#### Category of the bug
- [ ] Question
- [.] Solution
- [ ] Language

#### Description of the bug
Leetcode Java / python Solution is failing for below input
1
2
1000000

#### Code you used for Submit/Run operation
class Solution {
    public List<Integer> powerfulIntegers(int x, int y, int bound) {
        Set<Integer> seen = new HashSet();
        for (int i = 0; i < 100 && Math.pow(x, i) <= bound; ++i)
            for (int j = 0; j < 100 && Math.pow(y, j) <= bound; ++j) {
                int v = (int) Math.pow(x, i) + (int) Math.pow(y, j);
                if (v <= bound)
                    seen.add(v);
            }

        return new ArrayList(seen);
    }
}

#### Language used for code
Java

#### Expected behavior
i<18 was used in code and is a wrong assumption.

**Comment by lc-kay** [comment]
@vishalcool88 Since this issue has already been reported previously and relayed to our team, I will close this. Thank you for understanding.
