### ISSUE TITLE
[BUG] - <title>increasing triplet false testcase 

### ISSUE THREAD

**Issue by pranav5471** [LeetCode-Feedback/LeetCode-Feedback#22178]
### LeetCode Username

pranav5471

### Problem Number, Title, and Link

https://leetcode.com/problems/increasing-triplet-subsequence/?envType=study-plan-v2&envId=leetcode-75

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

this porgram is supposed to be a increasing triplet subsequence but the test case [20,100,10,12,5,13] although according to constraints it is supposed to be false but in the program it is considered true

### Language Used for Code

Python/Python3

### Expected behavior

it is suppposed to show false not true

**Comment by maa9605** [comment]
Please don't use the word "sequence" to denote a subset of non-consecutive elements.  It's incorrect
