### ISSUE TITLE
图像渲染 使用全局变量 bug

### ISSUE THREAD

**Issue by seth-shi** [LeetCode-Feedback/LeetCode-Feedback#2219]
**你的 LeetCode 名**
seth-shi

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
使用全局变量无法提交正确结果

**你使用的语言**
Golang

**你提交或者运行的代码**
```
var mark = -1
var visited = make(map[int]bool)

func floodFill(image [][]int, sr int, sc int, newColor int) [][]int {

	if mark == -1 {
		mark = image[sr][sc]
	}

	if sr < 0 || sc < 0 || sr >= len(image) || sc >= len(image[0]) {
		return nil
	}

	// 如果已经访问过, 那么也退出
	point := sr * 10 + sc
	if visited[point] {
		return nil
	}

	visited[point] = true

	if image[sr][sc] != mark {
		return nil
	}

	image[sr][sc] = newColor

	floodFill(image, sr + 1, sc, newColor)
	floodFill(image, sr - 1, sc, newColor)
	floodFill(image, sr, sc + 1, newColor)
	floodFill(image, sr, sc - 1, newColor)


	return image
}
```

**期望行为**
描述你期望的结果
![image](https://user-images.githubusercontent.com/28035971/106430630-0a4bfc00-64a7-11eb-986c-ce5be5b54ae8.png)

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![image](https://user-images.githubusercontent.com/28035971/106430644-0fa94680-64a7-11eb-94bd-26c2a9463894.png)

**额外的上下文**
如果我自定义用例, 执行代码可以得到正常的结果. 提交则不行.

**Comment by feiceh** [comment]
你好，我们已经收到这个反馈，将会提交至相关负责团队持续优化，推荐阅读「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」获得更多帮助。
同时也可以点击「题解」来查看当前题目的解题思路，或将疑问发布在「[讨论](https://leetcode-cn.com/circle/?page=1&query=)」对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
