### ISSUE TITLE
申请贡献一道题

### ISSUE THREAD

**Issue by TheBloodElf** [LeetCode-Feedback/LeetCode-Feedback#222]
题名：
Code Review

描述：
小明公司设计了一套Code Review系统，该系统有以下两种名词：
1、模块；
2、模块owner：对应模块的负责人，至少一位。
提交的代码会涉及到多个模块，codereview时需要各个模块的任一owner+2才可合入，现在需要知道小明的一次提交至少需要哪些人进行+2。
输入：一个数组modules表示该提交包含了哪些模块，一个字典owners表示模块和owner的映射关系；
输出：一个数组，result包含了需要+2的owner名字，如果最优解有多个，则返回任意一个即可。
示例：
给定modules = ["A", "B"], owners = ["A" : ["A1"], "B": ["A1", "B1"]]，
因为A1是两个模块的owner，则只需要A1一个人+2即可

测试案例：
输入：modules = ["A", "B"], owners = ["A" : ["A1"], "B": ["A1", "B1"]]
输出：[A1]

**Comment by feiceh** [comment]
感谢为力扣贡献题目，已转给相关团队会尽快审核的～

**Comment by TheBloodElf** [comment]
这道题还有很多变种，我申请一下这道题的版权。

**Comment by feiceh** [comment]
您好，这个题 idea 比较老了，我们暂不会纳入题库，感谢您对力扣的支持，祝刷题愉快 ^３^ ╱~~
