### ISSUE TITLE
Missing Test Case - 86. Partition List

### ISSUE THREAD

**Issue by bucker** [LeetCode-Feedback/LeetCode-Feedback#2220]
#### Your LeetCode username

susi

#### Category of the bug
- [v] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The description under the "Constraints" says:
> The number of nodes in the tree is in the range [0, 200].

which should be the:
> The number of nodes in the **list** is in the range [0, 200].

since it should be the list, not tree

**Comment by lc-kay** [comment]
Hi @bucker 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @bucker 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
