### ISSUE TITLE
[BUG] - 测试用例缺失

### ISSUE THREAD

**Issue by MikeAlwaysCode** [LeetCode-Feedback/LeetCode-Feedback#22203]
### LeetCode 用户名

mikeac

### 问题号码、标题和链接

284. 窥视迭代器 https://leetcode.cn/problems/peeking-iterator/description/

### Bug Category

缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*, 力扣官方题解

### 描述

https://leetcode.cn/problems/peeking-iterator/solutions/1031306/ding-duan-die-dai-qi-by-leetcode-solutio-8toa
官方题解中的Python3代码错误。

### 你使用的语言

Python/Python3

### 你提交或者运行的代码

```bash
class PeekingIterator:
    def __init__(self, iterator):
        self.iterator = iterator
        self._next = iterator.next()
        self._hasNext = iterator.hasNext()

    def peek(self):
        return self._next

    def next(self):
        ret = self._next
        self._hasNext = self.iterator.hasNext()
        self._next = self.iterator.next() if self._hasNext else 0
        return ret

    def hasNext(self):
        return self._hasNext
```

### 期望行为

不应该AC本题

### 屏幕截图

![lc bug](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/110583124/0c76e8e5-870b-4872-b06a-0aa140c61814)

### 额外的上下文

nums = ["PeekingIterator","hasNext","peek","next"]
commands = [[[1]],[],[],[]]
结果应该是[null,true,1,1]
实际输出了[null,false,1,1]
但这个代码可以AC本题。

**Comment by amcones-lc** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。
