### ISSUE TITLE
[BUG] - 786 - editorial unused function in python3 solution

### ISSUE THREAD

**Issue by Meowzz95** [LeetCode-Feedback/LeetCode-Feedback#22205]
### LeetCode Username

jjzzzmd

### Problem Number, Title, and Link

https://leetcode.com/problems/k-th-smallest-prime-fraction/description

### Bug Category

Editorial

### Bug Description

In editorial approach 2(priority queue)
<img width="765" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/22430379/905f3e1e-05cf-47e4-b9fd-715c0fd14952">
the function in the red box is defined as a custom comparator, however the function is not used at all in the solution.

### Language Used for Code

None

### Expected behavior

The unsued function should be removed, or, explain why it is there.

**Comment by Akshat-Vashisht** [comment]
They seem to have updated/fixed it

![Screenshot 2024-05-11 160632](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/24636528/ad51b4f1-fd00-48f7-9426-63b0eb19a9f4)

**Comment by Meowzz95** [comment]
Sorry what does that mean? Who is Winston?

**Comment by Meowzz95** [comment]
The issue is not resolved, the issue mentioned still exist and I don't see anyone reply anything before the issue is closed with the wrong username, did you close the wrong one?

**Comment by Meowzz95** [comment]
1. I don't see any attachment
2. it is still the same when I check the solution
![CleanShot 2024-05-17 at 16 46 29@2x](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/22430379/847d7a72-5f4f-4602-b743-9787705b7203)

**Comment by Meowzz95** [comment]
Hmmm so why you closed it again?
