### ISSUE TITLE
128. 最长连续序列需要对自定义测试用例判断数据范围

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#2223]
**你的 LeetCode 用户名**
stormsunshine

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
[128. 最长连续序列](https://leetcode-cn.com/problems/longest-consecutive-sequence/)对数据范围有要求，数组 `nums` 中的每个数都必须在 [-10^9, 10^9] 范围之间，因此自定义测试用例的时候需要判断输入的测试用例是否符合要求。国服并没有进行判断，只有世界服进行判断了，国服也需要对输入的测试用例进行判断。
例如对于以下不符合数据范围的测试用例：[2147483647,-2147483648]，在国服仍然可以正常运行，在世界服则会显示测试用例无效。

**你使用的语言**
Java

**你提交或者运行的代码**
```
class Solution {
    public int longestConsecutive(int[] nums) {
        Set<Integer> set = new HashSet<Integer>();
        for (int num : nums)
            set.add(num);
        int maxLength = 0;
        for (int num : nums) {
            if (!set.contains(num - 1)) {
                int curLength = 0;
                int curNum = num;
                while (set.contains(curNum)) {
                    curLength++;
                    curNum++;
                }
                maxLength = Math.max(maxLength, curLength);
            }
        }
        return maxLength;
    }
}
```

**期望行为**
自定义测试用例运行时，对于不符合要求的测试用例（例如数据超出指定的范围），不应该有运行结果。

**屏幕截图**
以下截图来自世界服，可以看到显示了Invalid Testcase。
![image](https://user-images.githubusercontent.com/12067364/106472154-5dd93c80-64dd-11eb-805c-956ed1e2e1d2.png)
以下截图来自国服，不符合限制的测试用例仍然正常运行。
![image](https://user-images.githubusercontent.com/12067364/106472362-8fea9e80-64dd-11eb-8d3e-7ccdddc9088e.png)

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，在与相关负责同事沟通了解后，「128. 最长连续序列」一题的优化已在我们的计划队列之内，但这可能需要一段时间进行处理，还请耐心等待，目前我们会暂时关闭该 issue，如有更多反馈和建议请与我们联系。
