### ISSUE TITLE
Grammar - 1376. Time Needed to Inform All Employees

### ISSUE THREAD

**Issue by Vikktour** [LeetCode-Feedback/LeetCode-Feedback#2224]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

There's a grammar mistake on the description.
Second sentence: The head of the company has is the one with headID.
Fix: The ID that the head of the company has is headID.

#### Code you used for Submit/Run operation

```
// N/A
```

#### Screenshots

![image](https://user-images.githubusercontent.com/35737317/106477788-837f2b00-6476-11eb-965f-145bc6384efa.png)

**Comment by lc-kay** [comment]
Hi @Vikktour 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Vikktour 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
