### ISSUE TITLE
[BUG] - <缺陷标题>

### ISSUE THREAD

**Issue by 123sjbsjb** [LeetCode-Feedback/LeetCode-Feedback#22244]
### LeetCode 用户名

npcsjb

### 问题号码、标题和链接

88. 合并两个有序数组 https://leetcode.cn/problems/merge-sorted-array/description/

### Bug Category

力扣官方题解

### 描述

88. 合并两个有序数组
官方题解的方法二双指针的演示动画有误。
以下是官方题解的演示动画
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/64237866/0c6c6c98-ab4b-4b83-84ae-03501ac5edd4)
按照题解的意思，应该是相同数值时应当是nums1在nums2的前面。
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/64237866/b09654de-e2f8-4e79-b26f-5618f603b1d1)

### 你使用的语言

None

### 期望行为

把题解的动态图改了就好

**Comment by amcones-lc** [comment]
您好，在与相关团队核实后：***不处理***（该解法中 nums1 和 nums2 的元素在合并数组中的顺序不重要）。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
