### ISSUE TITLE
17题结果判定方式有问题，正确的用例被判定为错误的

### ISSUE THREAD

**Issue by gfdsaa** [LeetCode-Feedback/LeetCode-Feedback#22253]
### LeetCode 用户名

xiaoguang

### 问题号码、标题和链接

https://leetcode.cn/problems/letter-combinations-of-a-phone-number/

### Bug Category

不正确或缺少“相关标签”

### 描述

输出结果["www","wwx","wwy","wwz","wxw","xwx","wxy","wxz","wyw","ywx","ywy","wyz","wzw","zwx","zwy","zwz","xww","xwx","wxy","wxz","xxw","xxx","xxy","xxz","xyw","xyx","yxy","xyz","xzw","xzx","zxy","zxz","yww","ywx","ywy","wyz","yxw","yxx","yxy","xyz","yyw","yyx","yyy","yyz","yzw","yzx","yzy","zyz","zww","zwx","zwy","zwz","zxw","zxx","zxy","zxz","zyw","zyx","zyy","zyz","zzw","zzx","zzy","zzz"]
预期结果["www","wwx","wwy","wwz","wxw","wxx","wxy","wxz","wyw","wyx","wyy","wyz","wzw","wzx","wzy","wzz","xww","xwx","xwy","xwz","xxw","xxx","xxy","xxz","xyw","xyx","xyy","xyz","xzw","xzx","xzy","xzz","yww","ywx","ywy","ywz","yxw","yxx","yxy","yxz","yyw","yyx","yyy","yyz","yzw","yzx","yzy","yzz","zww","zwx","zwy","zwz","zxw","zxx","zxy","zxz","zyw","zyx","zyy","zyz","zzw","zzx","zzy","zzz"]
应该结果是正确的 但是判定错误

### 你使用的语言

Java

### 你提交或者运行的代码

```bash
class Solution {


    List<Character> path=new ArrayList<>();
    Map<Integer,Character[]> map=new HashMap<>();

    public List<String> letterCombinations(String digits) {
        List<String> res=new ArrayList<String>();
        if(digits.length()==0) return res;
        map.put(2,new Character[]{'a','b','c'});
        map.put(3,new Character[]{'d','e','f'});
        map.put(4,new Character[]{'g','h','i'});
        map.put(5,new Character[]{'j','k','l'});
        map.put(6,new Character[]{'m','n','o'});
        map.put(7,new Character[]{'p','q','r','s'});
        map.put(8,new Character[]{'t','u','v'});
        map.put(9,new Character[]{'w','x','y','z'});
        backtracking(digits,res);
        return res;
    }
    public void backtracking(String digits,List<String> res){
        if(path.size()==digits.length()){
            Character[] char1=path.toArray(new Character[path.size()]);
            StringBuilder sb = new StringBuilder(char1.length);
            for (Character c : char1) {
                sb.append(c);
            }
            String temp = sb.toString();
            res.add(temp);
            return;
        }
        for(int i=0;i<map.get((int)digits.charAt(path.size())-'0').length;i++){
            Character[] temp=map.get((int)digits.charAt(path.size())-'0');
            path.add(temp[i]);
            backtracking(digits,res);
            path.remove(temp[i]);
        }
    }
    
}
```

### 期望行为

该方法最后得到的结果是正确的

**Comment by amcones-lc** [comment]
感谢反馈，经核实该题目题解及测试用例暂无异常（建议检查运行结果，如输出了两个"wxy"），力扣会不断努力给大家带来更好的学习社区！后续刷题学习中遇到问题，可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
