### ISSUE TITLE
Missing Test Case - 191. Number of 1 Bits

### ISSUE THREAD

**Issue by Haley-Seo** [LeetCode-Feedback/LeetCode-Feedback#2225]
#### Your LeetCode username

arsene77

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

When I ran with test input '00000000000000000000000000000000', the result showed '0' both expected and my answer.  But when I submitted this, it showed wrong answer result with output : 31, expected : 0

#### Code you used for Submit/Run operation

```
var memo=[];
var hammingWeight = function(n) {
    if (n in memo) return memo[n];
    let cnt = 0;
    while(n){
        cnt += (n&1);
        n = (n >>> 1);
    }
    memo[n] = cnt;
    return memo[n];
};
```

#### Language used for code

Javascript

#### Expected behavior

When I ran with test input '00000000000000000000000000000000', the result showed '0' both expected and my answer.  But when I submitted this, it showed wrong answer result with output : 31, expected : 0

#### Screenshots

![Screen Shot 2021-02-01 at 8 27 13 AM](https://user-images.githubusercontent.com/20848561/106487528-9807f700-6467-11eb-8146-4ab2c859ab78.png)

**Comment by lc-kay** [comment]
Hi @Haley-Seo 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
