### ISSUE TITLE
 Problem Description and Constraints are Contradictory - 1221. Split a String in Balanced Strings

### ISSUE THREAD

**Issue by deep3072** [LeetCode-Feedback/LeetCode-Feedback#2226]
#### Your LeetCode username

deep3072

#### Category of the bug

- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

According to Description, balanced strings are...
> Balanced strings are those who have equal quantity of 'L' and 'R' characters.
>
So, logically odd length string will never have the chance to be balanced.

Also description says,
> Given a balanced string s split it in the maximum amount of balanced strings.
>
which means every input will be a balanced string which implies there will never be a case where input string length is odd.

But the Constraint says the input string length can be also be odd which is contradictory to the problem description saying that input string will always be a balanced string

> Constraints:
> - 1 <= s.length <= 1000

#### Code you used for Submit/Run operation

```
class Solution 
{
        public:
        int balancedStringSplit(string s)
        {
                int c=0,i,a=0;
                for(i=0;i<s.size();i++)
                {
                        if(s[i]=='L')
                                a++;
                        else
                                a--;
                        if(a==0)
                                c++;
                }
                return c;
        }

};
```

#### Language used for code

C++

#### Expected behavior

Constraint should be:

>  s.length will always be even

instead of 

> 1 <= s.length <= 1000
>

#### Screenshots

![1221statement](https://user-images.githubusercontent.com/62668186/106501050-94688480-64e8-11eb-88f1-6fe34441a35a.PNG)
![1221constraints](https://user-images.githubusercontent.com/62668186/106501078-9d595600-64e8-11eb-9613-310c1d413a08.PNG)

**Comment by lc-kay** [comment]
@deep3072
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @deep3072 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
