### ISSUE TITLE
Missing Test Case - 669. Trim a Binary Search Tree

### ISSUE THREAD

**Issue by tytusss** [LeetCode-Feedback/LeetCode-Feedback#2229]
What's the answer  fulfilling conditions for the following example? when node to be trimmed has 2 valid descendands?
I can't find of an answer which will retain the descendand structure. How to attach it?

low = 2, high = 3

                     3
          0                       3
    2        2             3            3
2     2   2    2

#### Your LeetCode username
 

tytus_s

#### Category of the bug
- [ x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

low = 2, high = 3

                     3
          0                       3
    2        2             3            3
2     2   2    2

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@tytusss 
Thank you for your time. Upon investigating this issue, we found this issue to be non-content-related (the issue stems from an origin away from the content on this problem). Please raise this question in the discuss section https://leetcode.com/problems/trim-a-binary-search-tree/discuss/?currentPage=1&orderBy=newest_to_oldest&query= for further support. Thank you again for your support and understanding.

**Comment by jeon3029** [comment]
your test example is not BST

**Comment by tytusss** [comment]
> your test example is not BST

thanks
