### ISSUE TITLE
Missing Test Case - 953. Verifying an Alien Dictionary

### ISSUE THREAD

**Issue by raks-tt** [LeetCode-Feedback/LeetCode-Feedback#2236]
#### Category of the bug
- [] Question
- [] Solution:
- [ ] Language

#### Description of the bug
I believe my solution to the question is  right but it fails for a particular test case 
Here is the question: - 953. Verifying an Alien Dictionary

#### Code you used for Submit/Run operation

```
class Solution:
    def isAlienSorted(self, words: List[str], order: str) -> bool:
        index_map = {a: i for i,a in enumerate(order)}
        

        for i in range(len(words) - 1):
            first_word = words[i]
            next_word = words[i+1]
            
            for j in range(min(len(first_word), len(next_word))):
                if first_word[j]  != next_word[j]:
                    if (index_map[first_word[j]]>index_map[next_word[j]]):
                        return False
                    break
                else:
                    if len(first_word) > len(next_word):
                        return False
        return True
                    
            
```

#### Expected behavior
The output for the test case is false but it is showing as the expected output to be True.

Input:
["apap","app"]
"abcdefghijklmnopqrstuvwxyz"

Output:  false (This is correct)
Expected: true

**Comment by lc-kay** [comment]
@raks-tt The expected output is correct. Please refer to the discuss section for explanations on test cases or raise your question there. Thank you for your time.
