### ISSUE TITLE
217. Contains Duplicate

### ISSUE THREAD

**Issue by Kennlly** [LeetCode-Feedback/LeetCode-Feedback#2237]
**你的 LeetCode 用户名**
Kenny
user3642V

**Bug 类型**
- 217. Contains Duplicate
- [ ] 题解?
- JavaScript

**描述**
题目要求如果数组内有相同的元素返回False，没有返回True。提交时有Input=[2,14,18,22,22]，我的结果是False，但要求是True。请问是我理解题目要求有误还是bug？

**你使用的语言**
JavaScript

**你提交或者运行的代码**
```
// Contains Duplicate
var containsDuplicate = function(nums) {
  let sortedNums = nums.sort((a,b) => a - b);
  let countSet = {};
  const length = sortedNums.length;
  let count = 1;
  if (length === 0 || length === 1) {
    return false;
  } else {
    for (let i = 0; i < length; i++) {
      if (sortedNums[i] === sortedNums[i + 1]) {
        count++;
      } else {
        countSet[sortedNums[i]] = count;
        count = 1;
      }
    }
  }  
  for (let i in countSet) {
    if (countSet[i] > 1) {
      return true;
    } else {
      return false;
    }
  }
};
```

**期望行为**
false

**屏幕截图**
添加屏幕截图辅助我们
<img width="1371" alt="Screen Shot 2021-02-02 at 9 52 29 PM" src="https://user-images.githubusercontent.com/59631629/106691145-ff759200-65a0-11eb-830d-c8bd8a6ae70e.png">
帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
你好，该题用例并无问题，存在重复元素，因此 [2,14,18,22,22] 返回 true。

**Comment by Kennlly** [comment]
> 你好，该题用例并无问题，存在重复元素，因此 [2,14,18,22,22] 返回 true。

您好，谢谢回复与指导，是我理解题意有误了！
