### ISSUE TITLE
Missing Test Case - 1328. Break a Palindrome

### ISSUE THREAD

**Issue by sapphire21** [LeetCode-Feedback/LeetCode-Feedback#2238]
#### Your LeetCode username

sapphire21

#### Category of the bug
- [X] Question
- [X] Solution
- [ ] Language

#### Description of the bug

I think it misses the test case "bbabb". I have the following code which is an incorrect solution. If I use "bbabb" to test, it will return an incorrect answer. However, if I submit this solution, it actually passes all test cases and shows Accepted. So i think a test case like "bbabb" should be added.

#### Code you used for Submit/Run operation

```
class Solution:
    def breakPalindrome(self, palindrome: str) -> str:
        if not palindrome or len(palindrome) == 1:
            return ''
        n = len(palindrome)
        if (n % 2 == 1 and len(set(palindrome)) == 2 and 'a' in set(palindrome)) or set(palindrome) == {'a'}:
            tmp = list(palindrome)
            tmp[-1] = 'b'
            return ''.join(tmp)

        for i in range(n // 2):
            if palindrome[i] != 'a':
                tmp = list(palindrome)
                tmp[i] = 'a'
                return ''.join(tmp)
```

#### Language used for code

Python

#### Expected behavior

If the above code is submitted, it should not be accepted because it will not pass a test case like "bbabb".

**Comment by lc-kay** [comment]
Hi @sapphire21 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @sapphire21 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
