### ISSUE TITLE
827. Making A Large Island, missing test-case, invalid solution.

### ISSUE THREAD

**Issue by veginati** [LeetCode-Feedback/LeetCode-Feedback#2239]
#### Your LeetCode username

vamsiveginati(dreamer_vv)

#### Category of the bug
- [ ] Question
- [ 1] Solution
- [ ] Language

#### Description of the bug

Question : 827. Making A Large Island

Reason:

This test-case is important to validate the answer of the question. The current solution is showing incorrect result to the following test-case. Solution has to be correct before adding the test-case.

[[1,1,0,0,1], 
[1,1,0,0,1],
[1,1,0,1,1]]

In the above grid ( 3,5) size, there are two independent islands ( one with size 6 & other with size 4) , by changing (2,2) to 1 , the max size of the island is (11).

The value returned by current code is (7) which is incorrect.

#### Code you used for Submit/Run operation

```
class Solution {
    public int largestIsland(int[][] grid) {
     
        Map<Integer,Integer> islandCountMap = new HashMap<Integer,Integer>();
        int flag =2;
        int maxValue = 1;
        for(int i=0;i<grid.length;i++){
            for(int j=0;j<grid[0].length;j++){   
                if(grid[i][j]==1){
                    int count = dfs(grid,i,j,flag);
                    maxValue = Math.max(maxValue,count);
                    islandCountMap.put(flag++,count);
                }
            }
        }
        int[][] dirs = {{0,1},{1,0},{0,-1},{-1,0}};
        
        for(int i=0;i<grid.length;i++){
            for(int j=0;j<grid[0].length;j++){
                
                Set<Integer> overlap = new HashSet<Integer>();
                if(grid[i][j]==0){
                    for(int[] d:dirs){
                        int tempRow = i+d[0];
                        int tempCol = j+d[1];
                        
                        if(tempRow>=0 && tempCol>=0 && tempRow<grid.length && tempCol<grid[0].length){
                            overlap.add(grid[tempRow][tempCol]);
                        }
                    }
                    
                    Iterator<Integer> iteratorObj = overlap.iterator();
                    int tempParamCount =1;
                    while(iteratorObj.hasNext()){
                        tempParamCount+= islandCountMap.getOrDefault(iteratorObj.next(),0);
                    }
                    maxValue = Math.max(maxValue,tempParamCount);
                }
            }
        }
        
        return maxValue;
    }
    
    public int dfs(int[][] grid, int row, int col, int flag){
        
        if(row<0 || col <0 || row>=grid.length || col>=grid[0].length){    
            return 0;
        }
        
        if(grid[row][col] !=1){
            return 0;
        }
        
        grid[row][col] =flag;
        int totalCount =1;
        
        totalCount += dfs(grid,row+1,col,flag);
        totalCount += dfs(grid,row,col+1,flag);
        totalCount += dfs(grid,row-1,col,flag);
        totalCount += dfs(grid,row,col-1,flag);
        
        return totalCount;
    }
}

```

#### Expected behavior

[[1,1,0,0,1], 
[1,1,0,0,1],
[1,1,0,1,1]]

In the above grid ( 3,5) size, there are two independent islands ( one with size 6 & other with size 4) , by changing (2,2) to 1 , the max size of the island is (11).

#### Screenshots

[
![Screen Shot 2021-02-02 at 11 57 25 PM](https://user-images.githubusercontent.com/12207119/106700272-80895500-65b2-11eb-88fe-ebe24bab272e.png)
](url)

#### Additional context

Please add this test-case, and correct the solution.[](url)

**Comment by lc-kay** [comment]
Hi @veginati 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @veginati 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
