### ISSUE TITLE
修正代码模版

### ISSUE THREAD

**Issue by lidaqi001** [LeetCode-Feedback/LeetCode-Feedback#224]
** Bug 类型**
- [ ✔] 题目

**描述**
题目：删除链表中的节点
参数有误，应该有两个参数，代码模版只有一个，加参数还会报错

**你使用的语言**
php

**期望行为**
修正模版

**屏幕截图**
![image](http://image.ldqsdy.com/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20200430165917.png)

**Comment by feiceh** [comment]
感谢反馈，此问题已转给技术团队会尽快确认的～

**Comment by feiceh** [comment]
fixed
