### ISSUE TITLE
Missing Test Case - 141. Linked List Cycle

### ISSUE THREAD

**Issue by raghavjoshi789** [LeetCode-Feedback/LeetCode-Feedback#2240]
#### Your LeetCode username
 `raghavjoshi789`

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Question is accepting wrong submission as correct one due to missing test case applicable for all programming languages

#### Code you used for Submit/Run operation

```python
class Solution:
    def hasCycle(self, head: ListNode) -> bool:
        if head is None or head.next is None: return False
        p1 = head
        p2 = head
        while p2 and p2.next is not None:
            p1 = p1.next
            p2 = p2.next.next
            if p1.val == p2.val:       # Cause of bug: value comparison instead of object comparison
                return True            # Correct comparison: p1 == p2 
        return False
```

#### Language used for code

`python`

#### Expected behavior

```python
head = [3,2,2,-4], pos = -1  #Input
```
```python
Expected Output : false 
Actual Output : true   
# Reason because when slow pointer is at 2 position it will have value = 2 same as fast pointer which is at 3nd position. 
```
#### Additional context

Special case in two pointer ( slow and fast ) algorithm when we check equity of both pointers and use value instead of reference object it leads to false positive output for cycle check

**Comment by lc-kay** [comment]
@raghavjoshi789 Thanks for reaching out. Can you please provide the submission details link?

**Comment by raghavjoshi789** [comment]
https://leetcode.com/submissions/detail/451807028/

**Comment by lc-kay** [comment]
@raghavjoshi789 The test case set was recently updated and the solution you submitted now receives Wrong Answer. Therefore, we will not be adding your test case. Thank you for understanding.
