### ISSUE TITLE
[BUG] - Submission fail - 2660. Determine the Winner of a Bowling Game

### ISSUE THREAD

**Issue by IamTheUpgrade** [LeetCode-Feedback/LeetCode-Feedback#22418]
### LeetCode Username

I_am_the_Upgrade

### Problem Number, Title, and Link

2660. Determine the Winner of a Bowling Game https://leetcode.com/problems/determine-the-winner-of-a-bowling-game/description/

### Bug Category

Submission fail

### Bug Description

Submission gives wrong answer, but test case gives right answer.
Test case is right.
Test case:
Input: `player1 = [1,1,1,10,10,10,10]; player2 = [10,10,10,10,1,1,1]; Output = 2; Expected = 2;`
But submission gives: `Output = 2; Expected = 1;`

### Language Used for Code

Java

### Code used for Submit/Run operation

```bash
class Solution {
    public int isWinner(int[] player1, int[] player2) {
        
        int p1Score = score(player1);
        int p2Score = score(player2);

        return p1Score == p2Score ? 0 : p1Score > p2Score ? 1 : 2;
    }

    private static int score(int[] points) {

        int score = 0;

        for (int i = 0; i < points.length; i++)
            score += (i > 0 && points[i-1] == 10 || i > 1 && points[i-2] == 10) ?
                        2 * points[i] : points[i];

        return score;
    }
}
```

### Expected behavior

Submission has to give accepted answer, because code is correct.
I tried also with other languages like JS and other codes published in solutions section

### Screenshots

![Leetcode](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/110681144/e1c79640-9e61-4fd7-b518-59dc23731d19)

### Additional context

**Comment by IamTheUpgrade** [comment]
Test case:
Input: `player1 = [1,1,1,10,10,10,10]; player2 = [10,10,10,10,1,1,1]; Output = 2; Expected = 2;`
But submission gives: `Output = 2; Expected = 1;`

**Comment by VJ-P** [comment]
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/36384779/7cebb79e-e25f-406b-8cff-6b86225655f5)
