### ISSUE TITLE
[Missing Test Case] Test Case Correction

### ISSUE THREAD

**Issue by Kushal1605** [LeetCode-Feedback/LeetCode-Feedback#22430]
### LeetCode Username

Kushal1605

### Problem Number, Title, and Link

https://leetcode.com/problems/maximum-sum-of-subsequence-with-non-adjacent-elements/

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

This is the newest question from leetcode weekly contest 399 [3165. Maximum Sum of Subsequence With Non-adjacent Elements](https://leetcode.com/problems/maximum-sum-of-subsequence-with-non-adjacent-elements/)

There are inefficient and missing testcases in this question.
I have created a testcase which rejects the solution of a user who is on the 4th position in the current leaderboards. It's username is 
shashankp10

Testcase created by me is in the files added below.
[input.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/15447835/input.txt)
[shashankp10](https://leetcode.com/shashankp10)

### Language Used for Code

Java

### Code used for Submit/Run operation

```bash
class Solution {
    private static final int MOD = 1_000_000_007;

    public int maximumSumSubsequence(int[] nums, int[][] queries) {
        int totalSum = 0;

        for (int[] query : queries) {
            int pos = query[0];
            int newValue = query[1];
            nums[pos] = newValue;

            totalSum = (totalSum + maxNonAdjacentSum(nums)) % MOD;
        }

        return totalSum;
    }

    private int maxNonAdjacentSum(int[] nums) {
        if (nums.length == 0) return 0;
        if (nums.length == 1) return Math.max(0, nums[0]);

        int prevOne = Math.max(0, nums[0]);
        int prevTwo = 0;

        for (int i = 1; i < nums.length; i++) {
            int includeCurrent = nums[i] + prevTwo;
            int excludeCurrent = prevOne;
            int currentMax = Math.max(includeCurrent, excludeCurrent);

            prevTwo = prevOne;
            prevOne = currentMax;
        }

        return prevOne;
    }

}
```

### Expected behavior

This code was accepted during the contest because of the missing testcases in the question.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/115387392/e01f5625-8028-436f-8bfe-44c679eba400)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/115387392/f8cce104-0a91-458a-9427-b6d30c1275e4)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/115387392/edbe5871-e180-423b-b030-50001cbcd7ad)

**Comment by Pranav0-0Aggarwal** [comment]
can you also provide the input array, u only attached file for queries

**Comment by Kushal1605** [comment]
Yeah sure, thanks for telling.
