### ISSUE TITLE
Missing Test Case - 141. Linked List Cycle

### ISSUE THREAD

**Issue by sarioz** [LeetCode-Feedback/LeetCode-Feedback#2244]
#### Your LeetCode username

ozrisa

#### Category of the bug
- [ x ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

When I clicked on a fast-running solution quoted below, I saw that it compares values in the list. It will be foiled by the input list:
[1,1,1]
with pos = -1

The output should be False whereas some value-comparison approaches will, incorrectly, detect a cycle and return True. 
#### Code you used for Submit/Run operation

```
    def hasCycle(self, head: ListNode) -> bool:
        
        if head is None:
            return False
        
        slow = fast = head
        
        while fast and fast.next:
            slow = slow.next
            fast = fast.next.next
            
            if fast and slow.val == fast.val:
                return True
        
        return False

```

**Comment by lc-kay** [comment]
Hi @sarioz 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @sarioz 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
