### ISSUE TITLE
测试用例通过提交没过

### ISSUE THREAD

**Issue by feigogogo** [LeetCode-Feedback/LeetCode-Feedback#22458]
### LeetCode 用户名

小杨SwCu

### 问题号码、标题和链接

https://leetcode.cn/problems/find-missing-observations/

### Bug Category

缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*

### 描述

测试用例通过提交没过

### 你使用的语言

Java

### 你提交或者运行的代码

```bash
class Solution {
    public int[] missingRolls(int[] rolls, int mean, int n) {
        int len = rolls.length;
        int sum = (len + n) * mean;
        int unkSum = sum - IntStream.of(rolls).sum();
        int[] ans = new int[n];
        if(unkSum < n || unkSum > n*6){
            return new int[0];
        }
        int average = unkSum / n;
        int diffValue = unkSum - (average * n);
        for(int i = 0; i < n; i++){
            ans[i] = diffValue + average;
            diffValue = 0;
        }
        return ans;
    }
}
```

### 期望行为

测试用例失败

### 屏幕截图

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/127935661/572d9a7f-a616-4f72-b7df-4f7df9b30ef7)

### 额外的上下文

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/127935661/2715b3ad-0cdb-4077-884a-2b66e402ca2d)

**Comment by amcones-lc** [comment]
您好，在与相关团队核实后：***不处理***（在提交代码时会执行比运行当中更多的测试用例，您的代码需要通过所有的测试用例，而不是只有运行当中这些）。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
