### ISSUE TITLE
Inconsistency of description. Plus One

### ISSUE THREAD

**Issue by AleaJactaEstt** [LeetCode-Feedback/LeetCode-Feedback#2245]
In the description of task: "You may assume the integer does not contain any leading zero, except the number 0 itself."
But there are test 112: "[0,0]"

**Comment by lc-kay** [comment]
@AleaJactaEstt Please check out this discuss post to clarify your doubts! https://leetcode.com/problems/plus-one/discuss/933685/Why-is-00-in-the-test-set Thank you for your time.
