### ISSUE TITLE
Missing Test Case - 141. Linked List Cycle

### ISSUE THREAD

**Issue by pucsdian** [LeetCode-Feedback/LeetCode-Feedback#2246]
#### Your LeetCode username
pucsdian

#### Category of the bug
- Test Case

#### Description of the bug

as I looked many of submitted codes some leetcoders comparing actual value of nodes rather than checking for node to check is there is cycle or not
if way create linked list with all duplicate values it may then fail these codes and in que there is no constraint like no duplicate values and linked can contain duplicates

**Comment by lc-kay** [comment]
@pucsdian Can you please provide some examples of the issue you mentioned? For example, an accepted solution and a test case with all duplicate values that will fail that code.

**Comment by pucsdian** [comment]
This Code can pass test cases given by leetcode
but if we use test case like [3,3,3,3,3,3,3,] -1 it fails 
it give output True rather than False

def hasCycle(self, head: ListNode) -> bool:
        
        if head is None:
            return False
        
        slow ,fast = head,head
        
        while fast and fast.next:
            slow = slow.next
            fast = fast.next.next
            if fast and slow.val == fast.val:
                return True
        return False

**Comment by lc-kay** [comment]
@pucsdian Can you provide the submission details link?

**Comment by lc-kay** [comment]
Hi @pucsdian 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
