### ISSUE TITLE
手机账号注销无法登陆

### ISSUE THREAD

**Issue by Phil-sun** [LeetCode-Feedback/LeetCode-Feedback#22470]
### LeetCode 用户名

少少

### 问题号码、标题和链接

1

### Bug Category

问题描述

### 描述

需要解绑的手机号：17855515092
绑定手机号对应的力扣账号：少少
常用登录地址：（省市）杭州市
常用登录设备系统：mac
常用登录浏览器：chrome

### 你使用的语言

None

### 期望行为

解决登陆问题

**Comment by Nabiiiiiiiii** [comment]
您好，推荐您参考该篇文档后向文档中的邮箱发送相关信息哦：https://support.leetcode.cn/hc/kb/article/1642640/
