### ISSUE TITLE
Missing Test Case - 470. Calculate Entropy

### ISSUE THREAD

**Issue by novator55** [LeetCode-Feedback/LeetCode-Feedback#2247]
#### Category of the bug
- [ ] Solution

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

####Python
![96395_1405180725](https://user-images.githubusercontent.com/58919207/106800700-dd981000-6671-11eb-864e-638be1e76f8e.jpg)

**Comment by lc-kay** [comment]
@novator55 Can you please provide the link to the problem you are experiencing issues with? LeetCode does not have a problem with the number 470 and title Calculate Entropy. Thank you for your time.

**Comment by novator55** [comment]
https://leetcode.com/explore/learn/card/decision-tree/285/implementation/2650/
 - link to the problem
When i click RunCode or Submit, i have answer "Run Code Status:
Unknown Error". It doesn't depend on my code


2021-02-04 1:10 GMT+03:00, lc-kay <notifications@github.com>:

**Comment by lc-kay** [comment]
Hi @novator55 
I've relayed this issue to our team to investigate. Upon investigating this issue, we found this issue to be non-content-related (the issue stems from an origin away from the content on this problem); therefore, it's not valid for content contribution reward and I will close this ticket now. Thank you again for your support and understanding.
