### ISSUE TITLE
Wrong Test Case - 409. Longest Palindrome

### ISSUE THREAD

**Issue by GiovanniLuigi** [LeetCode-Feedback/LeetCode-Feedback#2248]
#### Your LeetCode username

giovannibruno128

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

The test case is wrong the longest palindrome in the string: "abccccdd" is 4, not 7.

#### Code you used for Submit/Run operation

```
func expandAround(_ l: Int, _ r: Int, string: [Character]) -> Int {
    var currentMax = 0
    var left = l
    var right = r
    while left >= 0 && right < string.count && string[left] == string[right] {
        currentMax = right - left + 1
        right += 1
        left -= 1
    }
    return currentMax
}

func longestPalindrome(_ s: String) -> Int {
    if s.count == 1 {
        return 1
    }
    
    let string = Array(s)
    var ans = 0
    
    for i in 0..<s.count {
        ans = max(expandAround(i, i+1, string: string), ans)
        ans = max(expandAround(i-1, i+1, string: string), ans)
    }
    
    return ans
}
```

#### Screenshots

<img width="853" alt="Captura de Tela 2021-02-03 às 18 39 17" src="https://user-images.githubusercontent.com/15925863/106812988-33a78c00-664f-11eb-8c63-3fc536615039.png">

**Comment by lc-kay** [comment]
@GiovanniLuigi The expected output for this example is correct. Please refer to the discuss section of the problem for further support. https://leetcode.com/problems/longest-palindrome/discuss/304750/the-testcase-is-wrong Thank you for your time.
