### ISSUE TITLE
Read N Characters Given Read4 II - Call multiple times

### ISSUE THREAD

**Issue by KevinColemanInc** [LeetCode-Feedback/LeetCode-Feedback#225]
**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
https://leetcode.com/explore/interview/card/facebook/5/array-and-strings/269/

If you run this question in ruby with no changes to the question prompt, it just says "runtime exception".

```
Line 29: bad value for range (ArgumentError) in solution.rb (block in __helper__)
Line 27 in solution.rb (each)
Line 27 in solution.rb (__helper__)
Line 58 in solution.rb (block in _driver)
Line 53 in solution.rb (each)
Line 53 in solution.rb (each_slice)
Line 53 in solution.rb (_driver)
Line 66 in solution.rb (<main>)
```

It seems like there is a problem in the "solution" code when checking my output with the solution's output?

**what language is your code written in**
ruby

**The code you submit/run**
```
# The read4 API is already defined for you.
# Below is an example of how the read4 API can be called.
# file = File.new("abcdefghijk") File is "abcdefghijk", initially file pointer (fp) points to 'a'
# buf = [' '] * 4 Create buffer with enough space to store characters
# read4(buf) # read4 returns 4. Now buf = ['a','b','c','d'], fp points to 'e'
# read4(buf) # read4 returns 4. Now buf = ['e','f','g','h'], fp points to 'i'
# read4(buf) # read4 returns 3. Now buf = ['i','j','k',...], fp points to end of file

class Solution
  # @param {List[str]} buf
	# @param {int} n
	# @return {int}
    def read(buf, n)
    end
end
```

**Expected behavior**
It should not throw an exception in the solution code.

**Comment by CooperCooperCooper** [comment]
Hi @KevinColemanInc,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @KevinColemanInc,
Thank you for raising the issue. Please take into account that return value should be int, like in the attached example.
![Uploading image.png…]()

**Comment by KevinColemanInc** [comment]
@CooperCooperCooper 

Why does the python version support returning `None`?

<img width="985" alt="image" src="https://user-images.githubusercontent.com/2381771/81029650-a96d9580-8e3a-11ea-8b95-b34ea5ee66ed.png">

**Comment by KevinColemanInc** [comment]
Why is the "Expected answer" a runtime error if I return the wrong type? Other problems and languages would tell me my answer is wrong.

**Comment by CooperCooperCooper** [comment]
Hi @
Thank you for reaching out to us again. I've relayed these question to our team to investigate.

**Comment by KevinColemanInc** [comment]
I think this might be the same problem but [Today's May challenge](https://leetcode.com/explore/challenge/card/may-leetcoding-challenge/535/week-2-may-8th-may-14th/3324/) says my output is the expected answer, but it doesn't give me credit.

In the screen capture below, my program exceeded the time limit and the expected answer is "Time Limit Exceeded"


<img width="965" alt="image" src="https://user-images.githubusercontent.com/2381771/81484341-a3403600-91f9-11ea-9129-ba88782ece32.png">

**Comment by CooperCooperCooper** [comment]
Hi @KevinColemanInc ,
Thank you for your time. The behavior of the judge is expected according to our current assumptions. However, We've updated the code definitions on python and python3. Please check out the problem now. We appreciate your support.

**Comment by KevinColemanInc** [comment]
@CooperCooperCooper Any ideas why my code didn't get marked as pass? It says the expected answer was "Time Limit Exceeded" which I did.

**Comment by CooperCooperCooper** [comment]
HI @KevinColemanInc ,
Thank you for reaching out again. Would you please share your code for the TLE issue so we can take a deeper look?
