### ISSUE TITLE
[BUG] - Question not show properly on the contest page on Dynamic Layout - 3163. String Compression III 

### ISSUE THREAD

**Issue by maityamit** [LeetCode-Feedback/LeetCode-Feedback#22500]
### LeetCode Username

_maityamit

### Problem Number, Title, and Link

3163. String Compression III https://leetcode.com/contest/weekly-contest-399/problems/string-compression-iii/description/

### Bug Category

Problem description

### Bug Description

The HTML Script not properly show on the problem description, I attached the screenshot for more info. 
Basically, when I open this question from the contest page and set **Dynamic Layout** , the question HTML not properly formatted so that, the raw HTML is showing. 

Problem URL: https://leetcode.com/contest/weekly-contest-399/problems/string-compression-iii/description/
where I faced the issue. 

### Language Used for Code

None

### Expected behavior

There will be proper text in normal text format. 

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/74618071/c9370e45-d931-46a3-bb0e-ce62d6ffb49f)

**Comment by kripa-sindhu-007** [comment]
Seems someone isn't doing the code review properly before pushing to production :)
