### ISSUE TITLE
[BUG] - Missing test case to validate bracket ordering

### ISSUE THREAD

**Issue by BorzooMV** [LeetCode-Feedback/LeetCode-Feedback#22519]
### LeetCode Username

borzoomoazami94

### Problem Number, Title, and Link

20. Valid Parentheses https://leetcode.com/problems/valid-parentheses

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

I have discovered that the current set of test cases for the bracket validation algorithm does not adequately test for the correct ordering of brackets. I was able to develop an algorithm that passed all existing tests without considering the ordering of brackets, which suggests a gap in the test coverage.

### Language Used for Code

Go

### Code used for Submit/Run operation

```bash
var chMap map[rune]rune = map[rune]rune{
	'(': ')',
	'[': ']',
	'{': '}',
}

func isValid(s string) bool {
	openChCount := map[rune]int{
		'(': 0,
		'[': 0,
		'{': 0,
	}

	closeChCount := map[rune]int{
		')': 0,
		']': 0,
		'}': 0,
	}

	for _, ch := range s {
		if count, found := openChCount[ch]; found {
			openChCount[ch] = count + 1
		}

		if count, found := closeChCount[ch]; found {
			closeChCount[ch] = count + 1
		}
	}

	for open, close := range chMap {
		if openChCount[open] != closeChCount[close] {
			return false
		}
	}

	return true
}
```

### Expected behavior

The function isValid passes all the existing test cases. However, I expected a test case that considers the correct ordering of brackets. For example, the input string "([)]" should return false, but my current function incorrectly returns true for such cases because it only verifies the counts of opening and closing brackets without considering their order.

**Comment by kripa-sindhu-007** [comment]
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/152695457/702f713f-8ed6-428e-ba84-c634f2f22db0)

I guess the test case does validate that thing as you can see in the screenshot I have used your example and the expected answer is also false.

**Comment by kripa-sindhu-007** [comment]
Ohh!! I get it now. I guess I misinterpreted your concern the first time. Hopefully, Leetcode would update the testcase for this question.
