### ISSUE TITLE
Missing Test Case - 141. Linked List Cycle

### ISSUE THREAD

**Issue by binayr** [LeetCode-Feedback/LeetCode-Feedback#2251]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
class Solution:
    def hasCycle(self, head: ListNode) -> bool:
        return check_repeat(head)
        
store = set()

def check_repeat(root):
    store.add(id(root))
    if root and id(root.next) in store: return True
    if root and root.next:
        return check_repeat(root.next)
    else:
        return False
```

#### Screenshots

![Screenshot 2021-02-04 at 11 05 36 AM](https://user-images.githubusercontent.com/6142051/106849882-8594f400-66d9-11eb-8d77-6ed7a50eb244.png)

**Comment by lc-kay** [comment]
Hi @binayr 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
