### ISSUE TITLE
Contribute a testcase

### ISSUE THREAD

**Issue by Asterioxer** [LeetCode-Feedback/LeetCode-Feedback#22521]
### LeetCode Username

Scadiva

### Problem Number, Title, and Link

3110. Score of a String https://leetcode.com/problems/score-of-a-string/description/

### Bug Category

Problem examples

### Bug Description

I wanna contribute my own custom testcase for the problem.

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
class Solution {
public:
    int scoreOfString(string s) {
        int final = 0;
        for(int i = 0; i < s.size() - 1; i++) {
            final += abs(s[i] - s[i + 1]);
        }
        return final;
    }
};
```

### Expected behavior

I wanted to give a custom testcase.
"supervision"
"boom"
"trickster"

**Comment by Asterioxer** [comment]
how do i contribute a testcase to leetcode

**Comment by kripa-sindhu-007** [comment]
@Asterioxer Contributing to a TestCase means you are providing such test cases that aren't already present. Like a test case that doesn't get passed by code that is already accepted. Or like a test case where the expected result is wrong according to the problem statement.
