### ISSUE TITLE
[BUG] - <1410 缺少测试用例>

### ISSUE THREAD

**Issue by oamuuvyi** [LeetCode-Feedback/LeetCode-Feedback#22525]
### LeetCode 用户名

oamuuvyi

### 问题号码、标题和链接

1410. HTML 实体解析器 https://leetcode.cn/problems/html-entity-parser/description/

### Bug Category

缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*

### 描述

通过测试的代码在以下测试用例中得出错误结果。
`"&amp;quot;&amp;apos;&amp;amp;&amp;gt;&amp;lt;&amp;frasl;"`

### 你使用的语言

Java

### 你提交或者运行的代码

```bash
class Solution {
    final static Map<String, String> HTML_ENTITY_MAP = Map.of(
            "&quot;",   "\"",
            "&apos;",   "'",
            "&amp;",    "&",
            "&gt;",     ">",
            "&lt;",     "<",
            "&frasl;",  "/"
    );
    public String entityParser(String text) {
        for (Map.Entry<String, String> entry : HTML_ENTITY_MAP.entrySet()) {
            text = text.replace(entry.getKey(), entry.getValue());
        }
        return text;
    }
}
```

### 期望行为

上述代码不应该通过测试，需要添加测试用例。

**Comment by amcones-lc** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by oamuuvyi** [comment]
> 你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

oamuuvyi

**Comment by amcones-lc** [comment]
你好，当前该题已添加测试用例，奖励已发放。
