### ISSUE TITLE
[Constraints To be updated] - <Custom Judge can be ByPassed>

### ISSUE THREAD

**Issue by ShashiKiranGenesis** [LeetCode-Feedback/LeetCode-Feedback#22529]
### LeetCode Username

kiranshashi110

### Problem Number, Title, and Link

160 Intersection of Two Linked Lists https://leetcode.com/problems/intersection-of-two-linked-lists/description/

### Bug Category

Problem constraints

### Bug Description

The Problem consists of a custom judge that ensures that the programmer doesn't attempt to modify the list.  But look at the below solution.
<a href = "https://leetcode.com/problems/intersection-of-two-linked-lists/solutions/5240714/is-this-cheating-o-n-time-complexity-o-1-space-complexity/"> My Solution </a>
In this solution, I am able to modify the list for my benefit and remodify it so that it remains in its original state. I believe if the constraints were extended to even the negative side of the number line, it could be prevented.

### Language Used for Code

Java

### Code used for Submit/Run operation

```bash
public class Solution {
    public ListNode getIntersectionNode(ListNode headA, ListNode headB) {
        boolean intersected = false;
        ListNode intersectedAt = null;

        ListNode cursor = headA;

        // Converting all nodes in list A to negative
        while(headA!=null) {
            headA.val *=-1;
            headA = headA.next;
        }

        while(headB!=null) {
            if(headB.val < 0) {
                intersected = true;
                intersectedAt = headB;
                break;
            }
            headB = headB.next;
        }

        // Converting all nodes in list A back to positive
        while(cursor!=null) {
            cursor.val *=-1;
            cursor = cursor.next;
        }

        if(intersected) return intersectedAt;
        else return null;
    }
}
```

### Expected behavior

If maybe, the nodes also contained negative values, the above solution could be rejected by the custom judge.

**Comment by luciphania** [comment]
Hi there,
 
Thank you for taking the time to share your feedback with us. 
 
After careful consideration, we have decided not to move forward with the changes suggested in your feedback at this time.

Please know that your input is important to us. Your continued feedback is greatly appreciated as we work towards improving our platform.
 
Best regards,
LeetCode Support Team
