### ISSUE TITLE
967 has a problem with the test case

### ISSUE THREAD

**Issue by OnlyALittle** [LeetCode-Feedback/LeetCode-Feedback#2253]
**你的 LeetCode 用户名**
one piece

**Bug 类型**
- [ ] 题目
- [x] 题解
- [ ] 编程语言

**描述**
根据题意，提交后的测试用例存在问题

**你使用的语言**
Javascript

**你提交或者运行的代码**
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
        
    }
};
```

**期望行为**
输入：n = 2, k = 2
输出：[13,20,24,31,35,42,46,53,57,64,68,75,79,86,97]

**屏幕截图**
![截图](http://img.souche.com/f2e/326ce0c4688c741f8e97bd60eaab7109.jpg)

**额外的上下文**
返回所有长度为 n 且满足其每两个连续位上的数字之间的差的绝对值为 k 的 非负整数 。

请注意，除了 数字 0 本身之外，答案中的每个数字都 不能 有前导零。例如，01 有一个前导零，所以是无效的；但 0 是有效的。

你可以按 任何顺序 返回答案。

**Comment by feiceh** [comment]
你好，该问题当前已修复，请您稍后再做尝试，力扣会定期更新，保障稳定和体验优化。
