### ISSUE TITLE
Missing Test Case - 35. Search Insert Position

### ISSUE THREAD

**Issue by himanshujoshi2000** [LeetCode-Feedback/LeetCode-Feedback#2254]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@himanshujoshi2000 Please provide a more detailed report so we can better troubleshoot the issue. Thank you for your time.

**Comment by lc-kay** [comment]
Hi @himanshujoshi2000 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
