### ISSUE TITLE
missing topics and related topics

### ISSUE THREAD

**Issue by Sristy-72** [LeetCode-Feedback/LeetCode-Feedback#22556]
### LeetCode Username

Sristy-72

### Problem Number, Title, and Link

https://leetcode.com/problems/minimum-number-of-chairs-in-a-waiting-room/

### Bug Category

Incorrect or missing "Related Topics"

### Bug Description

Related topic for this question is missing and even topics are missing for this question.

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
class Solution {
public:
    int minimumChairs(string s) {
       int maxm=0;
        int cnt=0;
        for(int i=0;i<s.size();i++){
            if(s[i]=='E'){
                cnt++;
                maxm=max(maxm,cnt);
            }
            else{
                cnt--;
            }
        }
        return maxm; 
    }
};
```

### Expected behavior

topic for the question is missing and even related topic for this question is missing.

### Screenshots

![Screenshot 2024-06-03 141318](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/126855796/cd4934b0-4c48-45f8-8f00-4ff22a9e5444)

**Comment by luciphania** [comment]
Hello,

Your reported issue has been relayed to our team for thorough investigation. We appreciate your patience as we work to address and resolve this matter. We will reach out to you when we have updates regarding the issue.

If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by luciphania** [comment]
Hello,

We're delighted to inform you that the issue you reported has been successfully resolved. 

Thank you for your patience and understanding throughout this process. If you encounter any further issues or have additional questions, please don't hesitate to reach out to us.

Best regards,
LeetCode Support Team
