### ISSUE TITLE
[Missing Test Case] - 3170 "Lexicographically Minimum String After Removing Stars" missing test case.

### ISSUE THREAD

**Issue by projecteulerlover** [LeetCode-Feedback/LeetCode-Feedback#22550]
### LeetCode Username

betsymp

### Problem Number, Title, and Link

3170, Lexicographically Minimum String After Removing Stars, https://leetcode.com/problems/lexicographically-minimum-string-after-removing-stars/

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

This code has an O(n^2) runtime but still passes tests.

I have attached the offending test case (33333 a's + 33333 b's + 33333 *'s).
[failed.txt](https://github.com/user-attachments/files/15526576/failed.txt)

### Language Used for Code

Java

### Code used for Submit/Run operation

```bash
class Solution {
    public String clearStars(String s) {
        int[] a = new int[26];
        List<Integer> del = new ArrayList<>();
        StringBuilder sb = new StringBuilder();
        for(int i = 0; i < s.length(); i++){
            if(s.charAt(i) == '*'){
                for(int j = 0; j < 26; j++){
                    if(a[j] != 0){
                        a[j]--;
                        sb = sb.reverse();
                        sb = sb.deleteCharAt(sb.toString().indexOf("" + (char) (j +'a')));
                        sb = sb.reverse();
                        break;
                    }
                }
            }else{
                sb.append(s.charAt(i));
                a[s.charAt(i)- 'a']++;
            }
        }

        
        return sb.toString();
    }
}
```

### Expected behavior

Code TLEs for given test case, but model solution passes.

**Comment by luciphania** [comment]
Hello,

Your reported issue has been relayed to our team for thorough investigation. We appreciate your patience as we work to address and resolve this matter. We will reach out to you when we have updates regarding the issue.

If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by luciphania** [comment]
Thank you for your time.

Your feedback has been used to enhance the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
