### ISSUE TITLE
[Testcase] 新测试用例

### ISSUE THREAD

**Issue by SC19015** [LeetCode-Feedback/LeetCode-Feedback#22552]
### LeetCode 用户名

Carlson Wang

### 问题号码、标题和链接

1103.分糖果 https://leetcode.cn/problems/distribute-candies-to-people/

### Bug Category

缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*

### 描述

贡献新的测试用例
1. candies = 1000000000
num_peoples = 1
预期结果：[1000000000]
2. candies = 1000000000
num_peoples = 2
预期结果：[500008040, 499991960]

### 你使用的语言

None

### 期望行为

贡献新的测试用例
1. candies = 1000000000
num_peoples = 1
预期结果：[1000000000]
2. candies = 1000000000
num_peoples = 2
预期结果：[500008040, 499991960]

**Comment by amcones-lc** [comment]
感谢反馈，能否向我们补充提交代码信息，以及完善代码格式，把信息提供完整才能有助于快速验证和精准的定位，谢谢。
