### ISSUE TITLE
Content Issue

### ISSUE THREAD

**Issue by sanchitkaul99** [LeetCode-Feedback/LeetCode-Feedback#2255]
https://leetcode.com/discuss/general-discussion/655704/

On this page

The spelling of February is wrong.

**Comment by lc-kay** [comment]
Hi @sanchitkaul99 
Thank you for your time. Upon investigating this issue, we found this issue to be non-content-related (the issue stems from an origin away from the content on this problem); therefore, it's not valid for content contribution reward. 
However, we've updated the spelling. Thank you again for your support and understanding.
