### ISSUE TITLE
Longest Common Prefix - Possible Bug 

### ISSUE THREAD

**Issue by xeaone** [LeetCode-Feedback/LeetCode-Feedback#22554]
### LeetCode Username

xeaone

### Problem Number, Title, and Link

 127, Longest Common Prefix, https://leetcode.com/explore/interview/card/top-interview-questions-easy/127/strings/887/

### Bug Category

Editorial

### Bug Description

It is possible I am not understanding the instructions correctly but I would think that the correct Output should be `flow` not `fl`.

### Instructions

_Write a function to find the longest common prefix string amongst an array of strings.
If there is no common prefix, return an empty string ""._ 

***Example***
```
Input: strs = ["flower","flow","flight"]
Output: "fl"
```
***Constraints:***
```
1 <= strs.length <= 200
0 <= strs[i].length <= 200
strs[i] consists of only lowercase English letters.
```

### Language Used for Code

TypeScript

### Code used for Submit/Run operation

```bash
function longestCommonPrefix(allStrings: string[]): string {
    let result = '';
    
    const allStringsLength = allStrings.length;
    
    for (let mainIndex = 0; mainIndex < allStringsLength; mainIndex++) {
        const mainString = allStrings[mainIndex];
        
        let innerMatch = '';
        
        for (let innerIndex = mainIndex+1; innerIndex < allStringsLength; innerIndex++) {
            const innerString = allStrings[innerIndex];
            
            let charMatch = '';
            for (let i = 0; i < mainString.length; i++) {
                const mainChar = mainString[i];
                const innerChar = innerString[i];
                if (mainChar === innerChar) {
                   charMatch += mainChar; 
                } else {
                    break;
                }
            }
            
            if (charMatch.length > innerMatch.length) {
                innerMatch = charMatch;
            }
                        
        }
        
        if (innerMatch.length > result.length) {
            result = innerMatch;
        }
        
    }
    
    return result;
};
```

### Expected behavior

My - expected Output: `flow`
LeetCode - expected Output: `fl`

**Comment by xeaone** [comment]
Is a Prefix always only two characters?

That seems like that should be a constraint. Or is Prefix a term that always means two chars. If so is there some reference for it that you could share?

**Comment by xeaone** [comment]
Oh! I see the confusion. In your comment you said _"all strings"_. But the instructions do not say that it needs to match all strings. Unless I am missing that constraint also.

**Comment by xeaone** [comment]
I think the instructions should be updated to say something like the following.

Old: Write a function to find the longest common prefix string amongst an array of strings.

New: Write a function to find the longest common prefix string in all the strings in the array.

**Comment by NazimFilzer** [comment]
> I think the instructions should be updated to say something like the following.
> 
> Old: Write a function to find the longest common prefix string amongst an array of strings.
> 
> New: Write a function to find the longest common prefix string in all the strings in the array.

Yes I second That
