### ISSUE TITLE
Missing Test Case - 112. Path Sum

### ISSUE THREAD

**Issue by rohitpatwa** [LeetCode-Feedback/LeetCode-Feedback#2256]
#### Your LeetCode username

rohitpatwa

#### Category of the bug
- [ ] Question
- [ ] Solution
Testcase is missing

#### Description of the bug

Question 112. Path Sum
Despite one test case failing, my code is accepted.
Path sum of an empty tree should be 0. When I take care of this condition and submit the code, it gets accepted. But for the test case  {[], 0} the expected output and your output are different.

This is an easy level question used for learning basic concepts. It should not be having such ambiguity.

#### Code you used for Submit/Run operation

```
class Solution:
    def hasPathSum(self, root: TreeNode, T: int) -> bool:   
        if not root:
            return T==0
        
        if not root.left and not root.right:
            return root.val == T
            
        left, right = False, False
        if root.left:
            left = self.hasPathSum(root.left, T-root.val)       
        if root.right:
            right = self.hasPathSum(root.right, T-root.val)
     
        return left or right
```

#### Language used for code

Python3

#### Expected behavior

Path sum of an empty tree should be 0. When I take care of this condition and submit the code, it gets accepted. But for the test case  {[], 0} the expected output and your output are different. So either the solution shouldn't have been accepted, or the condition should be taken care of in the solution.

#### Screenshots

![image](https://user-images.githubusercontent.com/17635051/106889188-aa777000-66b5-11eb-99e6-b48d64578f12.png)

**Comment by lc-kay** [comment]
Hi @rohitpatwa 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @rohitpatwa 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
