### ISSUE TITLE
[BUG] - Missing Testcase for 898. Bitwise ORs of Subarrays

### ISSUE THREAD

**Issue by AkramShafeek** [LeetCode-Feedback/LeetCode-Feedback#22564]
### LeetCode Username

akramshafeek

### Problem Number, Title, and Link

https://leetcode.com/problems/bitwise-ors-of-subarrays/description/

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

The problem is missing a test case due to which a solution where finding the bitwise OR of all subarrays of maximum length up-to 32 is passing. The same solution can be extended to check all subarrays of maximum size up-to 100 which will pass all the tests available. While I have suggested a test case below to rectify the passing of the 32 size subarray solution, you can also add another large test case to make it more robust.

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
class Solution {
public:
    int subarrayBitwiseORs(vector<int>& arr) {
        
        int n = arr.size();
        set<int> res;
        for(int i = 0; i<n; i++) {
            int temp = arr[i];
            for(int j = i; j<n && j<i+32; j++) {
                temp |= arr[j];
                res.insert(temp);
            }
        }

        return res.size();
    }
};
```

### Expected behavior

The above solution is expected to fail for the test case -> arr = [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4]
Where the expected output is 3
Due to missing of such test cases, the above code is accepted though it gives wrong answer of 4 for the above test case

### Screenshots

![Screenshot 2024-06-03 233753](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/65714507/3dc9f8a9-d067-4f7f-b5a7-199d5839af5e)

**Comment by Anoshor** [comment]
I concur
