### ISSUE TITLE
Missing Test Case `xD` - 409. Longest Palindrome

### ISSUE THREAD

**Issue by naXa777** [LeetCode-Feedback/LeetCode-Feedback#22571]
### LeetCode Username

naXa777

### Problem Number, Title, and Link

409. Longest Palindrome https://leetcode.com/problems/longest-palindrome/description/

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

Incorrect code is getting accepted when submitted.
Submission AC Link: https://leetcode.com/problems/longest-palindrome/submissions/1277333820
Submission AC Link 2: https://leetcode.com/problems/longest-palindrome/submissions/1277505476

The proposed test case "xD" is a valid test case according to the problem №409 description. And the code that I submitted fails on this test case, but accepted by LeetCode.

Please let your team compare valid code and invalid code side by side. The issue is real. Can you spot the bug?

<table>
<thead>
<tr><th>Invalid code</th><th>Valid code</th></tr>
</thead>
<tbody>
<tr>
<td>

```kt
class Solution {
    fun longestPalindrome(s: String): Int {
        val frequencies = IntArray(52)
        var palindromeLen = 0
        for (ch in s) {
            if (++frequencies[ch.code % 52] % 2 == 0)
                palindromeLen += 2
        }
        if (palindromeLen < s.length)
            ++palindromeLen
        return palindromeLen
    }
}
```

</td>
<td>

```kt
class Solution {
    fun longestPalindrome(s: String): Int {
        // ASCII code for 'z' is 122. ASCII code for 'A' is 65.
        // 122 - 65 + 1 = 58
        val bits = BooleanArray(58)
        var palindromeLen = 0
        for (ch in s) {
            bits[ch.code % 58] = !bits[ch.code % 58]
            if (!bits[ch.code % 58])
                palindromeLen += 2
        }
        if (palindromeLen < s.length)
            ++palindromeLen
        return palindromeLen
    }
}
```
</td>
</tr>
</tbody>
</table>

### Language Used for Code

Kotlin

### Code used for Submit/Run operation

```kt
class Solution {
    fun longestPalindrome(s: String): Int {
        val frequencies = BitSet(52)
        var palindromeLen = 0
        for (ch in s) {
            frequencies.flip(ch.code % 52)
            if (!frequencies.get(ch.code % 52))
                palindromeLen += 2
        }
        if (palindromeLen < s.length)
            ++palindromeLen
        return palindromeLen
    }
}
```

### Expected behavior

This solution should be rejected by tests.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/3858548/31682193-30fb-494d-9c95-4de723d36d59)

### Additional context

Please add test case for input `xD`.

**Comment by qingy2019** [comment]
XD haha

**Comment by qingy2019** [comment]
as in the emoji

**Comment by naXa777** [comment]
@exalate-issue-sync @LC-Pamela please take a look.
