### ISSUE TITLE
Missing testcase 669. Trim a Binary Search Tree

### ISSUE THREAD

**Issue by EvgenyKondratenko** [LeetCode-Feedback/LeetCode-Feedback#2257]
#### Your LeetCode username
Bazalt

#### Category of the bug
- [ ] Solution

#### Description of the bug
Missing test case
[3]
2
2
the answer should be nullptr

#### Code you used for Submit/Run operation
Next code should fall on this test

```
class Solution {
public:
    TreeNode* trimBST(TreeNode* root, int L, int R) {
        if(!root) return NULL;
        // next cycle should fall
        while(root->val<L||root->val>R){  // HERE!!!!!!!
            std::cout << root->val << std::endl;
            if(root->val<L) root=root->right;
            if(root->val>R) root=root->left; 
        }
        TreeNode* dummy=root;
        while(dummy){
            while(dummy->left&&dummy->left->val<L) dummy->left=dummy->left->right;
            dummy=dummy->left;
        }
        dummy=root;
        while(dummy){
            while(dummy->right&&dummy->right->val>R) dummy->right=dummy->right->left;
            dummy=dummy->right;
        }
        return root;
    }
};
```

#### Language used for code
C++

#### Expected behavior
Undefined behavior

#### Screenshots
No

#### Additional context
No

**Comment by lc-kay** [comment]
Hi @EvgenyKondratenko 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @EvgenyKondratenko 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
