### ISSUE TITLE
[BUG] - Incorrect test case for 636 Exclusive Time of Function

### ISSUE THREAD

**Issue by gui0506** [LeetCode-Feedback/LeetCode-Feedback#22581]
### LeetCode Username

gui0506

### Problem Number, Title, and Link

636. Exclusive Time of Function https://leetcode.com/problems/exclusive-time-of-functions/description/

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

Test case 121 is incorrect and should be removed or changed
- n = 3
- ["1:start:0","0:start:2","1:start:3","2:start:4","2:end:4","0:end:6","1:end:7","1:end:8"]

The log should never have "0:end:6" before function 1 finishes, because we are running function 1 currently. The test case makes no sense at all. A possible fix is to change "0:end:6","1:end:7" to "1:end:6","0:end:7"

### Language Used for Code

Java

### Code used for Submit/Run operation

```bash
class Solution {
    public int[] exclusiveTime(int n, List<String> logs) {
        int[] solution = new int[n];
        Deque<int[]> stack = new ArrayDeque<>();
        for (String log: logs) {
            String[] parts = log.split(":");
            int function = Integer.valueOf(parts[0]);
            int time = Integer.valueOf(parts[2]);
            if (parts[1].equals("start")) {
                stack.push(new int[]{function, time});
            }
            else { // end
                int[] start = stack.pop();
                int duration = time - start[1] + 1;
                solution[function] += duration;
                if (stack.size() > 0) {
                    int lastFunction = stack.peek()[0];
                    solution[lastFunction] -= duration;
                } 
            }
        }

        return solution;
    }
}
```

### Expected behavior

The test case makes no sense at all. A possible fix is to change the test case from "0:end:6","1:end:7" to "1:end:6","0:end:7"

**Comment by tsunghuanghsieh** [comment]
#22693 Duplicate.
