### ISSUE TITLE
Test Case for 201. Bitwise AND of Numbers Range

### ISSUE THREAD

**Issue by pratikkaria** [LeetCode-Feedback/LeetCode-Feedback#226]
**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
I would like to contribute a test case for the above mentioned problem. When I submitted my 
code, it successfully passed all the test cases whereas on running a custom test case with the 
following case, it gave TLE error.

**what language is your code written in**
C++

**The code you submit/run**
```
class Solution {
public:
int checkIfContains(int m,int n)
{
  if((n/2)>=m)
    return 1;
  return 0;
}
int rangeBitwiseAnd(int m, int n)
{
    if(n==INT_MAX && m==INT_MAX - 1)
        return m;
    if(m==n)
        return m;
  int a = checkIfContains(m,n);
  if(a==1)
    return 0;
  int out = m;
  for(int i=m+1;i<=n;i++)
  {
      cout<<out<<endl;
    out = out&i;
  }
  return out;
}
};
```
**Test Case**
2147483645
2147483647

**Expected behavior**
2147483644

**Screenshots**

**Additional context**
![Screenshot from 2020-05-01 08-36-00](https://user-images.githubusercontent.com/15686123/80778684-d2fe9680-8b86-11ea-89cc-f77a668f98fb.png)

**Leet Code Id**
pratikkaria96

**Comment by CooperCooperCooper** [comment]
Hi @pratikkaria,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @pratikkaria,
Thank you for your time. After a thorough investigation, our team found the error is not a Time Limit Exceeded Error but a Runtime Error that is caused by the overflow of a variable. We will not be updating this problem for now; however, we will keep this test case in mind for future updates. We appreciate your support.
