### ISSUE TITLE
[BUG] - 122. Best Time to Buy and Sell Stock II (A test case appears to have been erroneously changed based on a prior users issue.)

### ISSUE THREAD

**Issue by marcoswastaken** [LeetCode-Feedback/LeetCode-Feedback#22607]
### LeetCode Username

marcoswastaken

### Problem Number, Title, and Link

122. Best Time to Buy and Sell Stock II https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/?envType=study-plan-v2&envId=top-interview-150

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

Another user opened an issue about this here: https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/20261

But, either the problem description is incorrect, or the test cases are.

The problem description states:

> You are given an integer array prices where prices[i] is the price of a given stock on the ith day.
> 
> On each day, you may decide to buy and/or sell the stock. You can only hold at most one share of the stock at any time. However, you can buy it then immediately sell it on the same day.
> 
> Find and return the maximum profit you can achieve.

The key line here, that I think the previous user misunderstood, is **You can only hold at most one share of the stock at any time. **

So, for the test cases in question:

Test case [3,3,5,0,0,3,1,4],
Max profit should be 6, but the test expects 8 **[INCORRECT]**
Buy at 0, sell at 3, then buy at 1 and sell at 4.

(You cannot "Buy at 0 and hold it, buy at 0 next day, then sell both at 4." as the previous user suggested because then you would be holding two shares at the same time!)

Test case: [7,1,5,3,6,4]
Max profit should be: 7, and the test expects 7 **[CORRECT]** (I only included this to support my above argument, and point out the flawed logic repeated by the previous user.)
Buy at 1 and sell at 5, then buy at 3, then at 6

(You cannot "Buy at 1 and hold it, buy at 3, then sell both at 6." as the previous user suggested, because then you would be holding two shares at a time.")

### Language Used for Code

Python/Python3

### Code used for Submit/Run operation

```bash
class Solution:
    
    def maxProfit(self, prices: List[int]) -> int:
        ## Define a helper function that computes the max profit of a single
        ## sale, between two indices (days)
        ## (Used my solution to Part I)
        def single_max(p):
            n = len(p)

            if n <= 1: return 0

            max_profit = 0
            
            min_price = p[0]
            max_profit = 0

            for k in range(n):
                if p[k]<min_price:
                    min_price = p[k]
                else:
                    max_profit = max(max_profit, p[k]-min_price)

            return max_profit
        
        ## Compute the maxium profit for two disjoint trades, never holding
        ## more than a single share at a time
        max_total = 0
        for t in range(1,len(prices)+1):
            ## Compute ax profit buying/selling on or before day t
            first_profit = single_max(prices[:t])
            ## Compute max profit buying/selling after day t
            second_profit = single_max(prices[t:])

            ## Update overall maximum profit
            max_total = max(max_total, first_profit + second_profit)
            print(f"t: {t}, 1st: {first_profit} on {prices[:t]}, 2nd: {second_profit} on {prices[t:]}")
        
        ## Return the result
        return max_total
```

### Expected behavior

When run on the test case [3,3,5,0,0,3,1,4], my code returns the correct answer: 6. However, the test is incorrectly expecting 8.

**Comment by marcoswastaken** [comment]
Ah, thank you, I see the error in my logic. I see that the previous user was also incorrect, but for a different reason than me. I appreciate the clarification. I think that might even make the problem a bit easier for me 😅

**Comment by RathegaSathyamurthi** [comment]
I ended up in the same situation for this mentioned testcase. Thanks @marcoswastaken for posting the query and LeetCode for a detailed explanation.
