### ISSUE TITLE
[BUG] - <缺陷标题>

### ISSUE THREAD

**Issue by gds-prue** [LeetCode-Feedback/LeetCode-Feedback#22608]
### LeetCode 用户名

一片空白

### 问题号码、标题和链接

https://leetcode.cn/problems/find-users-with-valid-e-mails/

### Bug Category

缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*

### 描述

预期是运行失败的，因为没有转义，但是运行成功了。

### 你使用的语言

MySQL

### 你提交或者运行的代码

```bash
SELECT user_id, name, mail
FROM Users
WHERE mail REGEXP '^[a-zA-Z][a-zA-Z0-9_.-]*@leetcode.com$';
```

### 期望行为

预期运行失败

**Comment by amcones-lc** [comment]
感谢反馈，经核实该题目题解及测试用例暂无异常，力扣会不断努力给大家带来更好的学习社区！后续刷题学习中遇到问题，可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
