### ISSUE TITLE
Missing Test Case - 130. Surrounded Regions

### ISSUE THREAD

**Issue by TheEldorado** [LeetCode-Feedback/LeetCode-Feedback#2262]
#### Category of the bug
- [130 ] Question
- [ One of the inputs] Solution
- [English ] Language

#### Description of the bug

The following input, I believe outputs a wrong answer by leet code [["O","X","X","O","X"],["X","O","O","X","O"],["X","O","X","O","X"],["O","X","O","O","O"],["X","X","O","X","O"]] from leet code gives [["O","X","X","O","X"],["X","X","X","X","O"],["X","X","X","O","X"],["O","X","O","O","O"],["X","X","O","X","O"]], however, row 3 column 4 the O should be X since the adjacent border is X. 

#### Expected behavior

The actual output [["O","X","X","O","X"],["X","X","X","X","O"],["X","X","X","X","X"],["O","X","O","O","O"],["X","X","O","X","O"]]

**Comment by lc-kay** [comment]
@TheEldorado The expected output is correct and a user explains this test case well at https://leetcode.com/problems/surrounded-regions/discuss/263473/Can't-understand-test-case. Thank you for your time.
