### ISSUE TITLE
[BUG] - Incorrect code getting verdict accepted

### ISSUE THREAD

**Issue by tredsused40** [LeetCode-Feedback/LeetCode-Feedback#22652]
### LeetCode Username

tredsused70

### Problem Number, Title, and Link

523. Continuous Subarray Sum https://leetcode.com/problems/continuous-subarray-sum/description/

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

Code that has O(N^2) worst case complexity getting accepted while N <= 10^5

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
class Solution {
public:
    bool checkSubarraySum(vector<int>& nums, int k) {
        ios::sync_with_stdio(false); cin.tie(0); cout.tie(0);
        int r = 1;
        int l = 0;
        int sum=nums[l], n = nums.size();
        while(r<n){
            sum+=nums[r];
            if(sum%k == 0){
                return true;
            }
            if(nums[r] == nums[r-1] && nums[r] == 0){
                return true;
            }
            int x = sum;
            l=0;
            while((r-l)>1 && x>=k){
                x-=nums[l++];
                if(x%k == 0) return true;
            }
            r++;
        }
        return false;
    }
};
```

### Expected behavior

This code should get TLE when submitted, but instead it gets accepted. I made a testcase which makes it TLE. The testcase in in the .txt file below.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/75163817/fd41dc2f-76d1-4e69-9e7e-b6ef0438d355)

### Additional context

[txt.txt](https://github.com/user-attachments/files/15747401/txt.txt)

**Comment by luciphania** [comment]
Hello,

Your reported issue has been relayed to our team for thorough investigation. We appreciate your patience as we work to address and resolve this matter. We will reach out to you when we have updates regarding the issue.

If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team
