### ISSUE TITLE
[BUG] - Missing testcase for "349. Intersection of Two Arrays"

### ISSUE THREAD

**Issue by PauloMigAlmeida** [LeetCode-Feedback/LeetCode-Feedback#22653]
### LeetCode Username

PauloMigAlmeida

### Problem Number, Title, and Link

https://leetcode.com/problems/intersection-of-two-arrays/

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

This is one of the constraints defined in the problem statement:

` 1 <= nums1.length, nums2.length <= 1000`

However. there is no actual test case that has any element in those arrays that is exactly `1000`.  

If developer is using the Frequency Table approach to solve that problem, the missing test case can let developers define the size of frequency table to `1000` instead of `1001` and still get the submission accepted.

I suggest the following test case to cover that gap:

```
nums1 = [1000,2,2,1000]
nums2 = [1000,1000]
```

### Language Used for Code

Java

### Code used for Submit/Run operation

```bash
class Solution {
    public int[] intersection(int[] nums1, int[] nums2) {        
        var ret = new ArrayList<Integer>();        
        var freq = new int[1000];

        for(var i: nums1){
            if (freq[i] == 0)
                freq[i] = 1;
        }

        for(var i: nums2){
            if (freq[i] == 1){
                ret.add(i);
                freq[i] = 0;
            }
        }        
        
        return ret.stream().mapToInt(i -> i).toArray();
    }
}
```

### Expected behavior

The code above should not be accepted as it doesn't cover all the values defined in the problem statement's contraints.

` 1 <= nums1.length, nums2.length <= 1000`

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/1011868/cedc91d7-053e-49af-a4e7-2fd26c8eebd1)

**Comment by luciphania** [comment]
Thank you for your time.

Your feedback has been used to enhance the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
