### ISSUE TITLE
[BUG] - Missing test case

### ISSUE THREAD

**Issue by prerna-daluka** [LeetCode-Feedback/LeetCode-Feedback#22656]
### LeetCode Username

prerna_daluka

### Problem Number, Title, and Link

523. Continuous Subarray Sum https://leetcode.com/problems/continuous-subarray-sum/

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

Found an erroneous accepted submission.

### Language Used for Code

Java

### Code used for Submit/Run operation

```bash
class Solution {
    public boolean checkSubarraySum(int[] nums, int k) {
        int n=nums.length;
        if(n==1) return false;
        Set<Integer> set = new HashSet<>();
        int a=nums[0]%k, b=(a+nums[1])%k;
        set.add(a);
        if(n==2 && nums[0]==nums[1]) return true;
        if(b%k==0) return true;
        int c=b;
        if(n>100 && nums[0]==237 && nums[1]==237) return false;
        for(int i=2; i<n; i++){
            c=(c+nums[i])%k;
            if(set.contains(c) || c%k==0) return true;
            a=b;
            b=c;
            set.add(a);
        }
        return false;
    }
}
```

### Expected behavior

The above submission should fail for the following testcase:
**nums = [1,1]
k = 3**

**Comment by luciphania** [comment]
Hello,

Your reported issue has been relayed to our team for thorough investigation. We appreciate your patience as we work to address and resolve this matter. We will reach out to you when we have updates regarding the issue.

If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by luciphania** [comment]
Thank you for taking the time to share your feedback with us. 
After careful consideration, we have decided not to move forward with the changes suggested in your feedback at this time.
Please know that your input is important to us, and we're actively exploring alternative solutions. Your continued feedback is greatly appreciated as we work towards improving our platform.

Best regards,
LeetCode Support Team
