### ISSUE TITLE
[Missing Test Cases] - 523. Continuous Subarray Sum

### ISSUE THREAD

**Issue by csiitian** [LeetCode-Feedback/LeetCode-Feedback#22665]
### LeetCode Username

cs_iitian

### Problem Number, Title, and Link

[974. Subarray Sums Divisible by K](https://leetcode.com/problems/subarray-sums-divisible-by-k/) 

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

My code just got passed for all test cases, but I checked for one custom test cases and it is returning wrong answer.

The reason is I am using below logic to handle negative number while mod.
`sum = (sum + nums[i] + 40*k)%k;`

So, it will fail for every test cases where 40*k < abs(nums[i]).

Test Case: ( where my code failed )
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/98081274/9f0a3adb-95ca-4031-830f-d811c87ebeff)

### Language Used for Code

Java

### Code used for Submit/Run operation

```bash
class Solution {
    public int subarraysDivByK(int[] nums, int k) {
        int n = nums.length;
        int sum= 0, result = 0;

        Map<Integer, Integer> map = new HashMap();
        map.put(0, 1);
        for(int i=0;i<n;i++) {
            sum = (sum + nums[i] + 40*k)%k;
            int temp = map.getOrDefault(sum, 0);
            result += temp;
            map.put(sum, temp+1);
        }

        return result;
    }
}
```

### Expected behavior

The output should return 1 but it is returning 0.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/98081274/5626aef3-0f51-4f89-b031-41fbbf9740d3)

**Comment by stormsunshine** [comment]
The problem should be 974, not 523. Link is https://leetcode.com/problems/subarray-sums-divisible-by-k.

**Comment by luciphania** [comment]
Hello,

Your reported issue has been relayed to our team for thorough investigation. We appreciate your patience as we work to address and resolve this matter. We will reach out to you when we have updates regarding the issue.

If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by csiitian** [comment]
@stormsunshine  yes, my bad.
Corrected now.

**Comment by luciphania** [comment]
Thank you for your time.

Your feedback has been used to enhance the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
