### ISSUE TITLE
Weekly Contest 401 - Q3 - Time constraints are too tight (for JavaScript)

### ISSUE THREAD

**Issue by mhwice** [LeetCode-Feedback/LeetCode-Feedback#22670]
### LeetCode Username

espr3ss0

### Problem Number, Title, and Link

3180. Maximum Total Reward Using Operations I

### Bug Category

Problem constraints

### Bug Description

For the [Weekly Contest 401](https://leetcode.com/contest/weekly-contest-401/) the time constraints for the [third question](https://leetcode.com/problems/maximum-total-reward-using-operations-i/) in JavaScript are too tight. I submitted two solutions, both using top-down dynamic programming with time complexities of $O(n^2)$, however one received a TLE and one was accepted. The difference between these two solutions is that the first solution used a memoization function (very similar to Pythons `@cache` decorator) whereas the second solution used a 2D array to store previously calculated values. 

I do not believe that the difference between a TLE and an Accepted solution should come down to the difference between how we memoize a recursive function, but rather the time complexity of a solution.

Please loosen the time constraints on this question so all $O(n^2)$ solutions are accepted. Thank you. 

----

Below are the two solutions I submitted during the contest.

##### Solution 1 - Top-down Memoization using memoize() function

Result: **577 / 586** test cases passed (TLE)

[Link to submission](https://leetcode.com/submissions/detail/1282301117/)

```js
var maxTotalReward = function(rewardValues) {
  const n = rewardValues.length;
  rewardValues.sort((a, b) => a - b);
  
  const f = memoize((i, curr) => {
    if (i === n) return curr;
    let max = -Infinity;
    if (curr < rewardValues[i]) max = Math.max(max, f(i + 1, curr + rewardValues[i]));
    max = Math.max(max, f(i + 1, curr));
    return max;
  });
  
  return f(0, 0);
};

const memoize = (fn) => {
  const memo = new Map();
  
  return (...args) => {
    
    const key = args.map(JSON.stringify).join(",");
    if (memo.has(key)) return memo.get(key);

    const result = fn(...args);
    memo.set(key, result);

    return result;
  }
}
```

##### Solution 2 - Top-down memoization using 2D array

Result: **586 / 586** test cases passed (AC)

[Link to submission](https://leetcode.com/submissions/detail/1282361302/)

```js
var maxTotalReward = function(rewardValues) {
  const n = rewardValues.length;
  rewardValues.sort((a, b) => a - b);
  
  const dp = new Array(n).fill().map(() => new Array(4000).fill(-1));
  
  const f = (i, curr) => {
    if (i === n) return curr;
    if (dp[i][curr] !== -1) return dp[i][curr];
    let max = -Infinity;
    if (curr < rewardValues[i]) max = Math.max(max, f(i + 1, curr + rewardValues[i]));
    max = Math.max(max, f(i + 1, curr));
    return dp[i][curr] = max;
  }
  
  return f(0, 0);
};
```

### Language Used for Code

JavaScript

### Expected behavior

Both solutions have a time complexity of $O(n^2)$​ and both solutions should have been accepted.

**Comment by luciphania** [comment]
Hello,

Your reported issue has been relayed to our team for thorough investigation. We appreciate your patience as we work to address and resolve this matter. We will reach out to you when we have updates regarding the issue.

If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by luciphania** [comment]
Thank you for your detailed report and your patience.

When solving problems, both algorithmic and implementation efficiency are crucial. It’s important to consider that different methods of memoization can impact time complexity. Specifically, the time complexity of finding a key in a map can be O(log⁡(N))O(\log(N))O(log(N)) (if using a binary tree) or O(N)O(N)O(N) (for hash-maps), with hash-maps theoretically using O(N)O(N)O(N) per query.
We appreciate your understanding and patience as we work to address this issue. If you have any further questions or concerns, please feel free to reach out to us.

Best regards,
LeetCode Support Team

**Comment by mhwice** [comment]
Thank you for your response.

I acknowledge that the map-based solution has a higher constant factor compared to arrays; however, it remains an amortized $O(n^2)$ solution. Furthermore, in other LeetCode dynamic programming problems, using a map for memoization has consistently been accepted.

If the standard is that one $O(n^2)$ solution is accepted while another is not, does this imply that, moving forward, we will be required to exclusively use bottom-up dynamic programming due to its superior efficiency compared to memoization?

If this is the case, that is understandable. Please inform users so that we are aware of the need for these optimizations, rather than leaving us to speculate on what is deemed sufficiently efficient.
