### ISSUE TITLE
[BUG] - inefficient solution accepted

### ISSUE THREAD

**Issue by THE-DEEPDAS** [LeetCode-Feedback/LeetCode-Feedback#22672]
### LeetCode Username

THE_DEEP_

### Problem Number, Title, and Link

1019 . Next greater node in linked list.

### Bug Category

Problem constraints

### Bug Description

the time complexity in this code is O(N^2) but it is possible to solve by O(N) so it should not be accepted

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
/**
 * Definition for singly-linked list.
 * struct ListNode {
 *     int val;
 *     ListNode *next;
 *     ListNode() : val(0), next(nullptr) {}
 *     ListNode(int x) : val(x), next(nullptr) {}
 *     ListNode(int x, ListNode *next) : val(x), next(next) {}
 * };
 */
class Solution {
    private:
    int greater(ListNode* head,int i,int n){
        int maxi=0;
        ListNode* current=head;
        for(int j =0 ;j<=i;j++){
            maxi=current->val;
            current=current->next;
        }
        int temp=maxi;
        while(current!=nullptr){
            maxi = current->val > maxi ? current->val : maxi;
            current=current->next;
            if(temp!=maxi) return maxi;
        }
        if(temp==maxi) return 0;
        return maxi;
    }
public:
    vector<int> nextLargerNodes(ListNode* head) {
        vector<int> ans;
        int n=0;
        ListNode* current=head;
        while(current!=nullptr){
            n++;
            current = current->next;
        }
        for(int i=0 ; i<n ; i++){
            ans.push_back(greater(head,i,n));
        }
        return ans;
    }
};
```

### Expected behavior

it should not have been accepted should have thrown TLE

**Comment by luciphania** [comment]
Thank you for taking the time to share your feedback with us.
After careful consideration, we have decided not to move forward with the changes suggested in your feedback at this time.
Please know that your input is important to us, and we're actively exploring alternative solutions. Your continued feedback is greatly appreciated as we work towards improving our platform.

Best regards,
LeetCode Support Team
