### ISSUE TITLE
[BUG] - Missing test case for Problem #73

### ISSUE THREAD

**Issue by qingy2019** [LeetCode-Feedback/LeetCode-Feedback#22671]
### LeetCode Username

Z3ROsum

### Problem Number, Title, and Link

73. Set Matrix Zeroes https://leetcode.com/problems/set-matrix-zeroes/

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

An accepted code gets Wrong Answer for the following test case:

```
matrix = [[-385,1,1],[1,0,1],[1,1,1]]
```
The code ouputs `[[0,0,1],[0,0,0],[1,0,1]]`, but the expected result is `[[-385,0,1],[0,0,0],[1,0,1]]`

### Language Used for Code

C++

### Code used for Submit/Run operation

```C++
class Solution {
public:
    void setZeroes(vector <vector<int>> &matrix) {
        const int x = -35;
        int n = matrix.size(), m = matrix[0].size();
        for (int i = 0; i < n; i++) {
            for (int j = 0; j < m; j++) {
                if (!matrix[i][j]) {
                    for (int k = 0; k < n; k++) {
                        if (matrix[k][j])
                            matrix[k][j] = (k + j + 11) * x;
                    }
                    for (int k = 0; k < m; k++) {
                        if (matrix[i][k])
                            matrix[i][k] = (i + k + 11) * x;
                    }
                }
            }
        }
        for (int i = 0; i < n; i++)
            for (int j = 0; j < m; j++)
                if (matrix[i][j] == (i + j + 11) * x)
                    matrix[i][j] = 0;
    }
};
```

### Expected behavior

The code got accepted but it still WA's for the test case.

### Screenshots
<img width="290" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/66195939/58dfcf70-435a-4bf9-9280-199cba74f1f2">

**Comment by luciphania** [comment]
Hello,

Your reported issue has been relayed to our team for thorough investigation. We appreciate your patience as we work to address and resolve this matter. We will reach out to you when we have updates regarding the issue.

If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by luciphania** [comment]
Thank you for your time.

Your feedback has been used to enhance the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
