### ISSUE TITLE
[BUG] - Wrong code getting accepted, Missing testcase

### ISSUE THREAD

**Issue by Aditya3435** [LeetCode-Feedback/LeetCode-Feedback#22675]
### LeetCode Username

aditya3435

### Problem Number, Title, and Link

1755. Closest Subsequence Sum https://leetcode.com/problems/closest-subsequence-sum/description/

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

This code uses ```std::bitset``` to calculate maxSum which can go upto ```40 x 10^7``` which is in the order of 1e8
and bitset LIMIT is defined only for 1e7. above this range, the code can not manage the question requirements of finding minimum absolute difference of (goal - sum).

Here's the testcase on which it fails

Input
nums =
[10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000]

goal =
100000000

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
class Solution {
public:
    int minAbsDifference(vector<int>& nums, int goal) {
        // Preprocessing
        int n = nums.size();
        if(goal<0){
            goal = -1*goal;
            for(int i=0;i<n;i++) nums[i] = -1*nums[i]; 
        }

        // If the number to find is bigger than the maximum positive sum
        int posSum = 0;
        for(int i=0;i<n;i++) posSum+=max(nums[i],0);
        if(goal>posSum) return goal-posSum;

        int minDiff = INT_MAX;
        for(int i=0;i<n;i++){
            if(nums[i]<0) minDiff = min(minDiff,abs(goal-nums[i]));
        }
        const int LIMIT = 40000010;
        // DP
        bitset<LIMIT>dp(0);
        dp[0] = 1;
        // The positive numbers create all the possible sums
        for(int i=0;i<n;i++){
            if(nums[i]>0){
                dp|=(dp<<nums[i]);
            }
        }
        for(int i=0;i<n;i++){
            if(nums[i]<0){
                nums[i] = -1*nums[i];
                dp|=(dp>>nums[i]);
            }
        }
        for(int i=0;i<LIMIT;i++){
            if(dp.test(i)){
                minDiff = min(minDiff,abs(goal-i));
            }
        }
        return minDiff;
    }
};
```

### Expected behavior

Output
60000000

Expected
0

It should return as 0. because ```goal = 10^8``` can easily be made with abs(goal-sum) == 0.
But it is returning as 60000000

### Screenshots

![Screenshot from 2024-06-10 08-40-12](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/97333942/bef022fc-0d6e-4e5e-924c-128883926d50)

**Comment by luciphania** [comment]
Hello,

Your reported issue has been relayed to our team for thorough investigation. We appreciate your patience as we work to address and resolve this matter. We will reach out to you when we have updates regarding the issue.

If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by luciphania** [comment]
Thank you for your time.

Your feedback has been used to enhance the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
