### ISSUE TITLE
[Debugger crashes] - Debugger crashing unexpectedly in golang environment for all problems

### ISSUE THREAD

**Issue by pgandigesang** [LeetCode-Feedback/LeetCode-Feedback#22676]
### LeetCode Username

prajwalgs1992

### Problem Number, Title, and Link

https://leetcode.com/problems/height-checker/

### Bug Category

Editorial

### Bug Description

Debugger crashing in golang environment. Happening on all problems. 

![Screenshot 2024-06-09 at 10 27 23 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73667457/696ed20b-8f15-4e3e-864f-f80602846629)

### Language Used for Code

Go

### Expected behavior

Debugger should execute without issues.

### Screenshots

![Screenshot 2024-06-09 at 10 27 23 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73667457/d11d5170-4561-490a-99d1-b0dcfafea051)

**Comment by luciphania** [comment]
We are sorry that you are experiencing this. We have forwarded this issue to the tech team for a fix. We request your patience as we solve this, and we will update you on the progress.

Thank you, and let us know if you have any questions.

Best regards,
LeetCode Support Team

**Comment by pgandigesang** [comment]
Verified. Debugger works fine now.
