### ISSUE TITLE
[BUG] - ESC in Vim mode escapes coding section

### ISSUE THREAD

**Issue by janniksinz** [LeetCode-Feedback/LeetCode-Feedback#22680]
### LeetCode Username

janniksinz

### Problem Number, Title, and Link

https://leetcode.com/problems/permutations/

### Bug Category

Problem description

### Bug Description

Pressing <kbd>Esc</kbd> when editing in vim mode causes my cursor to jump out of the coding area and let's me navigate the text on page instead.
No matter if in 'normal', 'insert' or 'visual' mode, the cursor vanishes from it's position and appears at the top left corner right in front of the leetcode icon, allowing me to navigate along the navigation row with <kbd>→</kbd>

### Language Used for Code

None

### Expected behavior

<kbd>Esc</kbd> should leave the cursor in position and exit whatever mode back to nolmal mode.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/47904900/4765b3f8-c26c-47be-93d2-a15cdc1b6deb)

### Additional context

refreshing the browser doesn't help. switching from and back to vim mode doesn't help.

**Comment by janniksinz** [comment]
Problem seems to be fixed in firefox, still not working in chrome
However, I'm having the same problem on multiple websites (leetcode.com, neetcode.com)
Did Chrome have a recent update that somehow escapes divs on <kbd>Esc</kbd>?

**Comment by janniksinz** [comment]
Solved:
for anyone having the same poblem, you probably have a Chrome extension installed that changes the behavior.
In my case, I had `vimium` installed.

**Comment by khaled4vokalz** [comment]
really weird.... Thanks @janniksinz I also had vimium installed which was causing this to happen

**Comment by GymRat102** [comment]
thanks @janniksinz, it helps me as well. I encountered this issue before when I use a site that provide a web shell console, in which I can't use `esc` to back to normal mode. I used `ctrl-c` as a replacement (which also work in this leetcode case), but that's a bummer.

btw how did you find that `vimium` is the cause, and actually why?
