### ISSUE TITLE
1282. Group the People Given the Group Size They Belong To

### ISSUE THREAD

**Issue by shivam145** [LeetCode-Feedback/LeetCode-Feedback#227]
**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
In this question it really doesn't matter what values we are inserting in the vector, the test cases are passing solely based on the vector size, which i think is incorrect.
I think the size of the vector and the elements inside the vector both should be checked, rather only checking the size of the vector

**Example**

**Input -> groupSizes = [3,3,3,3,3,1,3]**
* **Expected Outputs** -> [[5],[0,1,2],[3,4,6]] **OR** [[2,1,6],[5],[0,4,3]] **OR** [[5],[0,6,2],[4,3,1]] and many more
* **My Output** -> [[0,0,0],[3,3,3],[5]] (got excepted depite being wrong)

_**Why my output is wrong?**_
* As [0,0,0] is equivalent to [0], because 0 is a person ID, which ultimately boils down my output to [[0],[3],[5]] which is incorrect
* Also 1,2,4,6 are not included in any of the groups which violates the problem statement which says  each person belongs **exactly** to one group

**what language is your code written in**
C++

**The code you submit/run**
```
bool sortbysec(pair<int,int> p1,pair<int,int> p2) {
    return p1.second > p2.second;
}
class Solution {
public:
    vector<vector<int>> groupThePeople(vector<int>& groupSizes) {
        vector<pair<int,int>> group;
        for(int i = 0 ; i < groupSizes.size() ; i++)
            group.push_back({i,groupSizes[i]});
        
        sort(group.begin(),group.end(),sortbysec);
        
        vector<vector<int>> result;
        for(int i = 0 ; i < group.size() ; i++) {
            int limit = group[i].second;
            vector<int> v;
            int j;
            for(j = i ; j < i + limit ; j++) {
                v.push_back(group[i].first);
            }
            i = j - 1;
            result.push_back(v);
        }
        return result;
    }
};

```

**Expected behavior**

* A number should be a part of exactly one group
* No number should occur in a group more than once

**Screenshots**

**Additional context**

**Comment by CooperCooperCooper** [comment]
Hi @shivam145,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @shivam145,
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.

**Comment by shivam145** [comment]
Hi @CooperCooperCooper , Thank you so much for your time and support, I will surely reach out at "support@leetcode.com".
