### ISSUE TITLE
Missing Test Case - 71. Simplify Path

### ISSUE THREAD

**Issue by devikandixit** [LeetCode-Feedback/LeetCode-Feedback#2270]
#### Your LeetCode username

Gajanana
#### Category of the bug
- [ ] Question

#### Description of the bug

There is no Test case , that have  directory name ending with 2 dots(..).
For example consider path as "**/hello../world/**" here directory has "**hello..**" as the name.
Hence in this case "**hello../**" should not considered as level up (faulty implementation of the code takes **"../"** portion of the string & hence goes one up the directory)

#### Code you used for Submit/Run operation

```
class Solution {
public:
    string simplifyPath(string path) {
        int nSize = path.size();
        int j=1;
        int nDotCount=0;
        for(int i=1;i<nSize;++i)
        {
            if(path[i]=='/'&&path[i-1]=='/')continue;
            if(path[i]=='.')
            {
                ++nDotCount;
                continue;
            }
            if(path[i]!='.'&&path[i-1]=='.')
            {
              if(nDotCount >2 || (1<=nDotCount && path[i]!='/'))
              {
                  j+=nDotCount;
                  nDotCount=0;
              }
              else 
              {
                  if(2 == nDotCount)
                  {
                      int nWordLength=0;
                      if (path[j] == '/') --j;
                      while(path[j]!= '/' && j>0)
                      {
                          j--;
                          ++nWordLength;
                      }
                      if(j >0)j--;
                      int nPrevLength=0;
                      while(path[j]!= '/'&& j>0)
                      {
                          j--;
                          ++nPrevLength;
                      }
                      j++;
                      for(int k=nPrevLength;k<nWordLength;++k)
                      {
                          path[j]=path[k];
                      }
                  }
                  nDotCount=0;
                  continue;
              }
            }
            path[j]=path[i];
            ++j;
        }
     
       if(nDotCount >2)
              {
                  j+=nDotCount;
                 // cout<<nDotCount;
              }
              else 
              {
                  if(2 == nDotCount)
                  {
                     // cout<<"=2";
                      int nWordLength=0;
                      while(path[j]!= '/' && j>0)
                      {
                          j--;
                          ++nWordLength;
                      }
                      if(j >0)j--;
                      int nPrevLength=0;
                      while(path[j]!= '/'&& j>0)
                      {
                          j--;
                          ++nPrevLength;
                      }
                      j++;
                      for(int k=nPrevLength;k<nWordLength;++k)
                      {
                          path[j]=path[k];
                      }
                  }
                 
                  
              }
        if(path[j-1]=='/' && j>1)--j;
        path.resize(j);
        return path;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Expected behaviour is correct. Answer for this is shown as "**/hello../world**"
However faulty code implentation has the answer as "**/world**"

Due to missing of this test case("**Directory name ending with ..**")some of the incorrect implementation might pass.

**Comment by devikandixit** [comment]
Test case 1 : "**/hello../world/**" Expected output  "**/hello../world**  Wrong Implementation might have "**/world**"
Test case 2 :  "**/hello./world/**" (directory name ending with single .)                                                                                      
Incorrect implentation might consider  "**./**" as current directory. This results in wrong output. 
Expected output   "**/hello./world**"     Wrong Implementation might have "**/helloworld**"

**Comment by devikandixit** [comment]
![image](https://user-images.githubusercontent.com/31611426/107078111-dc064d80-6813-11eb-877f-21513a4267f5.png)


![image](https://user-images.githubusercontent.com/31611426/107078153-eb859680-6813-11eb-9512-58bf3de09a23.png)

![image](https://user-images.githubusercontent.com/31611426/107078349-3a333080-6814-11eb-8e04-4ab66d50f959.png)

**Comment by lc-kay** [comment]
Hi @devikandixit 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by whitebear221** [comment]
To complete: /..toto.. /..toto..tata and /..toto..tata..

**Comment by devikandixit** [comment]
Hi @whitebear221 , above test case " **/..toto.. /..toto..tata and /..toto..tata..**" has white spaces which issues invalid test case. By removing white space test case becomes  "**/..toto../..toto..tata/..toto..tata..**"

**Comment by devikandixit** [comment]
Also directory ending with single dot can also be a valid testcase "**/.toto./.toto.tata/.toto.tata.**"

**Comment by lc-kay** [comment]
Hi @devikandixit 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. Since the submitted solutions now receive wrong answer, please provide an accepted solution that will fail the additional test cases. We appreciate your support!

**Comment by devikandixit** [comment]
Hi @lc-kay ,
 I also have one more missing test case. "**/hello./world/**" (directory name ending with single .) Should I need to create separate issue page OR I can update in this issue page?

**Comment by devikandixit** [comment]
Hi @lc-kay<mailto:notifications@github.com> , @LeetCode-Feedback/LeetCode-Feedback<mailto:LeetCode-Feedback@noreply.github.com>

I have also provided an additional test case "/hello./world/" (apart from "/hello../world/")
Let me know whether I will be eligible for additional 100 points.

Best regards
Gajanana D S

________________________________

**Comment by lc-kay** [comment]
@devikandixit Please submit another ticket for this test case with an accepted solution that it will fail. Thank you!

**Comment by devikandixit** [comment]
Hi  @lc-kay<mailto:notifications@github.com>,

Now I cannot have a test case which fails an accepted solution.
This is because both of my test cases are added  test case list.
I have added  2 test cases
1. "/hello../world/"
2. "/hello./world/"

Now both these test cases are included.
But I got 100 leetcode points for 2 test cases(I believe I can get 200 points)

Please check my submission link
https://leetcode.com/submissions/detail/452578078/

[cid:8a00d4c9-981b-4d26-ae1a-c9620bb253bc]

Best regards
Gajanana D S

________________________________

**Comment by lc-kay** [comment]
@devikandixit You've been rewarded another 100 points for the second test case. Thank you for your time!
