### ISSUE TITLE
Missing Test case - 153. Find Minimum in Rotated Sorted Array

### ISSUE THREAD

**Issue by aramdov** [LeetCode-Feedback/LeetCode-Feedback#2271]
#### Your LeetCode username
aramdov444

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

I see a bad implementation of an edge case in the test cases for the problem listed in the subject line, the link is provided below.
https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/  

For the edge case where the nums array contains 1 element, there are no test cases for submissions where that single element is something other than 1. For example, [2], or [10]. The only 1 element list being tested is [1]. I have checked if this is true and confirmed it with multiple submissions.

My code will submit and pass all tests whether I run 

```   
if len(nums) == 1:
            return nums[0]
```

or
       
``` 
if len(nums) == 1:
            return 1
```

I believe adding some additional test cases for the edge cases(for the 1 element) would be good practice. It's a relatively tiny thing in my opinion, I don't mean to be petty as I am writing this email. It is just something that caught my eye.

Thank you,

#### Code you used for Submit/Run operation

```
if len(nums) == 1:
            return 1
```

The above code snippet to return 1 will allow you to pass the submission
It should be changed so it can only pass on returning the only element in the list:

```
if len(nums) == 1:
            return nums[0]
```

#### Language used for code
Python and Python3

#### Expected behavior

I expected 
```
if len(nums) == 1:
            return 1
```
to fail because there might be 1 element lists where the number is not 1.
Instead, returning 1 will pass the submission because there are no other test cases for 1 element lists with a number other than 1.

**Comment by aramdov** [comment]
I tried my best to format it correctly and write in a succint matter, let me know if anything is confusing.

**Comment by lc-kay** [comment]
@aramdov Can you please provide your submission details link? Thank you!

**Comment by aramdov** [comment]
1. Submission with "return 1" -> https://leetcode.com/submissions/detail/452473932/
2. Submission with "return nums[0]" -> https://leetcode.com/submissions/detail/452250208/

Sorry about that

**Comment by lc-kay** [comment]
Hi @aramdov 
Thank you! I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@aramdov Our team has reviewed your report and ruled the contribution as invalid. The reason being that an if condition was used to pass the current test set. Thank you for your time.
