### ISSUE TITLE
[BUG] - 题解可以优化

### ISSUE THREAD

**Issue by CAESIUS-TIM** [LeetCode-Feedback/LeetCode-Feedback#22721]
### LeetCode 用户名

CAESIUS

### 问题号码、标题和链接

2786. 访问数组中的位置使分数最大 https://leetcode.cn/problems/visit-array-positions-to-maximize-score/description

### Bug Category

力扣官方题解

### 描述

题解可以优化

```rust
impl Solution {
    pub fn max_score(nums: Vec<i32>, x: i32) -> i64 {
        let mut res = nums[0] as i64;
        let mut dp: Vec<i64> = vec![i32::MIN as i64, i32::MIN as i64];
        dp[(nums[0] % 2) as usize] = nums[0] as i64;
        for i in 1..nums.len() {
            let parity = (nums[i] % 2) as usize;
            let cur = (dp[parity] + nums[i] as i64).max(dp[1 - parity] - x as i64 + nums[i] as i64);
            res = res.max(cur);
            dp[parity] = dp[parity].max(cur);
        }
        return res;
    }
}

作者：力扣官方题解
链接：https://leetcode.cn/problems/visit-array-positions-to-maximize-score/solutions/2806895/fang-wen-shu-zu-zhong-de-wei-zhi-shi-fen-jyjg/
来源：力扣（LeetCode）
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。
```
$1 <= nums[i] <= 10^6$
`cur >= dp[parity] + nums[i] > dp[parity]`
所以 `dp[parity] = dp[parity].max(cur);` 可优化为 `dp[parity] = cur;`

### 你使用的语言

Rust

### 期望行为

题解 `dp[parity] = dp[parity].max(cur);` 可优化为 `dp[parity] = cur;`

**Comment by amcones-lc** [comment]
您好，在与相关团队核实后：***不处理***（为了保持题解表达的一致性和清晰度，这里不做修改）。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
