### ISSUE TITLE
[BUG] - incorrect testcase

### ISSUE THREAD

**Issue by ChaohaoDu** [LeetCode-Feedback/LeetCode-Feedback#22746]
### LeetCode Username

chaohaodu

### Problem Number, Title, and Link

152. Maximum Product Subarray https://leetcode.com/problems/maximum-product-subarray/description/

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

In constraints, it says: "The product of any prefix or suffix of nums is guaranteed to fit in a 32-bit integer." However, in testcase 190, input `[0,10,10,10,10,10,10,10,10,10,-10,10,10,10,10,10,10,10,10,10,0]` will case overflow

### Language Used for Code

Java

### Code used for Submit/Run operation

```bash
public int maxProduct(int[] nums) {
        int max = 1;
        int min = 1;
        int res = Integer.MIN_VALUE;

        for (int num : nums) {
            int a = max * num, b = min * num;
            max = Math.max(num, Math.max(a, b));
            min = Math.min(num, Math.min(a, b));
            res = Math.max(res, max);

            System.out.println(num + " " + max + " " + min + " " + res);
        }

        return res;
    }
```

### Expected behavior

The testcase will cause overflow

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/73503787/cf89d1d2-7e0c-4595-a484-39f550cecb79)

**Comment by luciphania** [comment]
Hello there,

Thanks for reaching out!

While the given test case still satisfied the original constraints, the constraints have been updated such that any subarray product now fits inside 32-bit integer now.

Best,
LeetCode Support Team
