### ISSUE TITLE
[BUG] - TC O(nlogn) but give TLE, 3186. Maximum Total Damage With Spell Casting

### ISSUE THREAD

**Issue by maityamit** [LeetCode-Feedback/LeetCode-Feedback#22754]
### LeetCode Username

_maityamit

### Problem Number, Title, and Link

3186. Maximum Total Damage With Spell Casting https://leetcode.com/problems/maximum-total-damage-with-spell-casting/

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*, Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

Hi, as per the constraints given N=1e5
, I solved using NLOGN as per the constraints it will be passed but it is giving TLE. but the exact same code when I used tabulation, it is giving AC. 

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
int const N = 1e5;
class Solution {
public:
    unordered_map<int,long long> mp;
    long long dp[N+1];
    long long helper(int idx,vector<int> &am){
        if(idx>=am.size()) return 0;
        if(dp[idx]!=-1) return dp[idx];
        long long nottake = helper(idx+1,am);
        int newID = upper_bound(am.begin(),am.end(),am[idx]+2)-am.begin();
        int cnt = upper_bound(am.begin(),am.end(),am[idx])-am.begin();
        long long tak = (am[idx]*1ll*mp[am[idx]])+helper(newID,am);
        return dp[idx]=max(nottake,tak);
    }
    long long maximumTotalDamage(vector<int>& power) {
        for(auto it:power) mp[it]++;
        vector<int> am;
        memset(dp,-1,sizeof(dp));
        for(auto it:mp) am.push_back(it.first);
        sort(am.begin(),am.end());
        return helper(0,am);
    }
};
```

### Expected behavior

It will give AC, but giving TLE

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/74618071/b8773b03-5568-4e42-9f99-7b6f66923c76)

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/74618071/fd82f40b-a61a-4b11-8683-df1356cbdd4b)

**Comment by luciphania** [comment]
Hello,
 
Your reported issue has been relayed to our team for thorough investigation. We appreciate your patience as we work to address and resolve this matter. We will reach out to you when we have updates regarding the issue.
 
If you have any further questions or concerns in the meantime, please feel free to let us know.
 
Best regards,
LeetCode Support Team

**Comment by luciphania** [comment]
Hello,

We calculate sum of time your code consumed. Reason for getting TLE is the memset.

Thanks, and if you have any other issues, don't hesitate to reach out.

Best regards,
LeetCode Support Team

**Comment by maityamit** [comment]
Then why This Code is giving TLE also? I used the n size array at every time dynamic not fixed enough.
And some of the language exact same code got accepted... like in python this memo technique get accepted? why so that?
```
class Solution {
public:
    map<int,long long> mp;
    long long helper(int idx,vector<int> &am,vector<long long> &dp){
        if(idx>=am.size()) return 0;
        if(dp[idx]!=-1) return dp[idx];
        long long nottake = helper(idx+1,am,dp);
        int newID = upper_bound(am.begin(),am.end(),am[idx]+2)-am.begin();
        long long tak = (am[idx]*1ll*mp[am[idx]])+helper(newID,am,dp);
        return dp[idx]=max(nottake,tak);
    }
    long long maximumTotalDamage(vector<int>& power) {
        for(auto it:power) mp[it]++;
        vector<int> am;
        vector<long long> dp(power.size()+1,-1);
        for(auto it:mp) am.push_back(it.first);
        return helper(0,am,dp);
    }
};
```
