### ISSUE TITLE
[BUG] - Wrong Constraints in 3186. Maximum Total Damage With Spell Casting [Weekly Contest 402]

### ISSUE THREAD

**Issue by abhi27033** [LeetCode-Feedback/LeetCode-Feedback#22756]
### LeetCode Username

abhi2703

### Problem Number, Title, and Link

3186. Maximum Total Damage With Spell Casting   https://leetcode.com/problems/maximum-total-damage-with-spell-casting/

### Bug Category

Problem constraints

### Bug Description

The code which was memoized in the 3rd question was giving TLE. Its time complexity was nlogn and according to constraints of n<10^5    nlogn solution should work, but the same code when it was tabulated without any state reduction it passed.

Both the codes are having same time complexity but the tanbulated code is passing , this is wrong since there is no state reduction or time constrains reduction in tabulation. Kindly rejudge the solutions in Weekly Contest 402.

Memoized Code
https://leetcode.com/problems/maximum-total-damage-with-spell-casting/submissions/1289631976/ 

Tabulated Code
https://leetcode.com/contest/weekly-contest-402/submissions/detail/1289655353/

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
class Solution {
public:
    unordered_map<long long, long long> mp;
    unordered_map<int, int> nxt;
    vector<long long> dp;
    long long solve(vector<int>& p, int i) {
        if (i >= p.size()) return 0;
        if (dp[i] != -1) return dp[i];
        long long t = p[i] * mp[p[i]] + (nxt[i] < p.size() ? solve(p, nxt[i]) : 0);
        long long nt = solve(p, i + 1);
        return dp[i] = max(t, nt);
    }

    long long maximumTotalDamage(vector<int>& power) {
        for (auto it : power) {
            mp[it]++;
        }
        sort(power.begin(), power.end());
        power.erase(unique(power.begin(), power.end()), power.end());
        dp.resize(power.size(), -1);
        for (int i = 0; i < power.size(); ++i) {
            int ele = power[i] + 3;
            int idx = lower_bound(power.begin(), power.end(), ele) - power.begin();
            nxt[i] = idx;
        }
        return solve(power, 0);
    }
};
```

### Expected behavior

It should pass as here is the same version which is Tabulated which got passed both are nlogn

class Solution {
public:
    long long maximumTotalDamage(vector<int>& power) {
        unordered_map<long long, long long> mp;
        unordered_map<int, int> nxt;
        vector<long long> dp;  
        for (auto it : power) {
            mp[it]++;
        }
        sort(power.begin(), power.end());
        int n = power.size();
        dp.resize(n, 0);
        for (int i = 0; i < n; ++i) {
            int ele = power[i] + 3;
            int idx = lower_bound(power.begin(), power.end(), ele) - power.begin();
            nxt[i] = idx;
        }
        for (int i = n - 1; i >= 0; --i) {
            long long take = power[i] * mp[power[i]];
            if (nxt[i] < n) {
                take += dp[nxt[i]];
            }
            long long nt = (i + 1 < n) ? dp[i + 1] : 0;
            dp[i] = max(take, nt);
        }
        return dp[0];
    }
};

**Comment by luciphania** [comment]
Hello,
 
Your reported issue has been relayed to our team for thorough investigation. We appreciate your patience as we work to address and resolve this matter. We will reach out to you when we have updates regarding the issue.
 
If you have any further questions or concerns in the meantime, please feel free to let us know.
 
Best regards,
LeetCode Support Team

**Comment by luciphania** [comment]
Hello,

We calculate sum of time your code consumed. Reason for getting TLE is the memset.

Thanks, and if you have any other issues, don't hesitate to reach out.

Best regards,
LeetCode Support Team
