### ISSUE TITLE
[BUG] - Missing Questions / 404 Errors for Questions 426, 1490, 1650, (and possibly others)

### ISSUE THREAD

**Issue by Zanger67** [LeetCode-Feedback/LeetCode-Feedback#22757]
### LeetCode Username

Zanger

### Problem Number, Title, and Link

- 426 Convert Binary Search Tree to Sorted Doubly Linked List https://leetcode.com/problems/convert-binary-search-tree-to-sorted-doubly-linked-list
- 1490 Clone N-ary Tree https://leetcode.com/problems/clone-n-ary-tree 
- 1650 Lowest Common Ancestor of a Binary Tree III https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree-iii

### Bug Category

Problem description

### Bug Description

Questions are showing 404 errors when trying to access webpages

### Language Used for Code

None

### Expected behavior

Question is not visible and throws a 404 error when trying to access.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/36343598/cecfa44d-5de4-4567-ad89-bd56f730d9e5)

### Additional context

Noticed after the contest that the number of solved questions I had went down. Number of solved easy questions correctly updated +1 but my mediums went +2-3 netting -1 and found these questions to be not appearing when comparing to the questions I'd completed and recorded.

**Comment by luciphania** [comment]
The issue you reported has been resolved. Please feel free to verify and retry. If the problem continues to persist, please let us know so we can update our engineering team. 

We apologize for any inconvenience this may have caused and appreciate your patience while we worked to resolve the issue. If you have any further questions or concerns, please do not hesitate to contact us.

Thank you

**Comment by Zanger67** [comment]
No worries! Thanks for the update! Just happened to noticed it and thought I'd point it out just in case. :)
