### ISSUE TITLE
about Sample Test Case - 191. Number of 1 Bits

### ISSUE THREAD

**Issue by pucsdian** [LeetCode-Feedback/LeetCode-Feedback#2275]
#### Your LeetCode username
pucsdian

#### Description of the bug
please change the sample test case format
some newbie fills misleading because its shows like we get input in binary string but actually input is a unsigned integer

Sir if u change the sample test case like
Input: n = 11
Output: 3
Explanation: The unsigned 32 bit binary string 00000000000000000000000000001011 of given unsigned number 11 and it has a total of three '1' bits in its binary form

**Comment by lc-kay** [comment]
Hi @pucsdian 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@pucsdian The input is a binary string of length 32, not an integer. Therefore, we will not update the example. Thank you for your time.
