### ISSUE TITLE
[BUG] - <Wrong constraints for problem number 3 in weekly contest 402>

### ISSUE THREAD

**Issue by atmajitsahu100** [LeetCode-Feedback/LeetCode-Feedback#22759]
### LeetCode Username

atmajit24

### Problem Number, Title, and Link

3186. Maximum Total Damage With Spell Casting

### Bug Category

Problem constraints

### Bug Description

the constraints to this problem is 1e5 then **nlogn** must have worked here but when i submitted the nlogn  dp+binary search solution during the contest it gave tle and after the contest i wrote the same code in python and submitted it and surprisingly it got accepted and that too with 100% beats.
how is it possible. please rejudge the solutions for question number 3.

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
**c++ code**

class Solution {
public:
    #define ll long long
    ll solve(ll i,ll n,vector<int>& p,unordered_map<ll,ll>& mp,ll dp[]){
        if(i>=n) return 0;
        if(dp[i]!=-1) return dp[i];
        ll d=0;
        ll dd=0;
        ll x=lower_bound(p.begin(),p.end(),p[i]+3)-p.begin();
        d=0ll+1ll*mp[p[i]]*p[i]+solve(x,n,p,mp,dp);
        dd=0ll+solve(i+1,n,p,mp,dp);
        
        return dp[i]=max({d,dd});
    }
    long long maximumTotalDamage(vector<int>& power) {
        ll n=power.size();
        unordered_map<ll,ll> mp;
        for(auto it:power){
            mp[it]++;
        }
        sort(power.begin(),power.end());
       ll dp[n+1];
       memset(dp,-1,sizeof(dp));
        return solve(0,n,power,mp,dp);
    }
};

**python code**

class Solution:
    def solve(self, i, n, p, mp, dp):
        if i >= n:
            return 0
        if dp[i] != -1:
            return dp[i]
        
        d = 0
        dd = 0
        x = self.lower_bound(p, p[i] + 3)
        d = 1 * mp[p[i]] * p[i] + self.solve(x, n, p, mp, dp)
        dd = self.solve(i + 1, n, p, mp, dp)
        
        dp[i] = max(d, dd)
        return dp[i]

    def lower_bound(self, p, target):
        left, right = 0, len(p)
        while left < right:
            mid = left + (right - left) // 2
            if p[mid] < target:
                left = mid + 1
            else:
                right = mid
        return left

    def maximumTotalDamage(self, power):
        n = len(power)
        mp = {}
        for it in power:
            mp[it] = mp.get(it, 0) + 1
        power.sort()
        dp = [-1] * (n + 1)
        return self.solve(0, n, power, mp, dp)
```

### Expected behavior

both code should be accepted but here only python code is getting accepted with 100% beats where's c++ code is giving tle.. since both code are same and also c++ is faster than python .. i dont find any logical reason for this anomaly from leetcode.

### Screenshots

![Screenshot (1516)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/72679078/987e7487-ef6a-4457-b1a3-63ee66b7920c)
![Screenshot (1515)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/72679078/41a582bd-50aa-478e-9fb7-12837d1c1e4e)
![Screenshot (1517)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/72679078/8075524f-8714-4815-a6d3-212ba747d0f2)

**Comment by luciphania** [comment]
Hello,
 
Your reported issue has been relayed to our team for thorough investigation. We appreciate your patience as we work to address and resolve this matter. We will reach out to you when we have updates regarding the issue.
 
If you have any further questions or concerns in the meantime, please feel free to let us know.
 
Best regards,
LeetCode Support Team

**Comment by luciphania** [comment]
Hello,

We calculate sum of time your code consumed. Reason for getting TLE is the memset.

Thanks, and if you have any other issues, don't hesitate to reach out.

Best regards,
LeetCode Support Team

**Comment by atmajitsahu100** [comment]
class Solution {
public:
    #define ll long long
    ll solve(ll i,ll n,vector<int>& p,unordered_map<ll,ll>& mp,vector<ll>& dp){
        if(i>=n) return 0;
        if(dp[i]!=-1) return dp[i];
        ll d=0;
        ll dd=0;
        ll x=lower_bound(p.begin(),p.end(),p[i]+3)-p.begin();
        d=0ll+1ll*mp[p[i]]*p[i]+solve(x,n,p,mp,dp);
        dd=0ll+solve(i+1,n,p,mp,dp);
        
        return dp[i]=max({d,dd});
    }
    long long maximumTotalDamage(vector<int>& power) {
        ll n=power.size();
        unordered_map<ll,ll> mp;
        for(auto it:power){
            mp[it]++;
        }
        sort(power.begin(),power.end());
        vector<ll> dp(n+1,-1);
        return solve(0,n,power,mp,dp);
    }
};

**i tried submitting this first without memset but it gave TLE then i used memset but it also gave tle.**
