### ISSUE TITLE
Environment Problem

### ISSUE THREAD

**Issue by MakarandPundlik** [LeetCode-Feedback/LeetCode-Feedback#2276]
#### All test cases are passed while executing program in local environment , but on server solution fails to pass the first testcase itself.

**Comment by lc-kay** [comment]
Hi @MakarandPundlik 
Thank you for your time. Upon investigating this issue, we found this issue to be non-content-related (the issue stems from an origin away from the content on this problem); therefore, it's not valid for content contribution reward. 
We encourage you to share more content-related issues here with us for [valid content contribution rewards](https://leetcode.com/discuss/general-discussion/526802/File-Problem-and-Solution-Content-Issues-to-Our-GitHub-Public-Feedback-Repo-Now!). To further assistant on this issue, please reach out to us through our helpdesk or support@leetcode.com Thank you again for your support and understanding.
