### ISSUE TITLE
[BUG] - <title> Missing test case

### ISSUE THREAD

**Issue by gourab9817** [LeetCode-Feedback/LeetCode-Feedback#22776]
### LeetCode Username

gourab9817

### Problem Number, Title, and Link

https://leetcode.com/problems/sum-of-square-numbers/?envType=daily-question&envId=2024-06-17

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

This test case contains the Pythagoras formula satisfied numbers. There should be a test case of the non-Pythagoras(which means) numbers such that it returns false.  So the problem will be more generalized.
There should be the presence of a number like 4  or 8 etc.

### Language Used for Code

Java

### Code used for Submit/Run operation

```bash
class Solution {
    public boolean judgeSquareSum(int c) {
        long b=(long)Math.ceil(Math.pow(c,0.5));
        long a=0;
        while(a<=b){
            long val=a*a+b*b;
            if(val==c){
                return true;
            }else if(val>c){
                b--;
            }else{
                a++;
            }
            
        }
        return false;
    }
}
```

### Expected behavior

It should have a generalized test case with a fully squared number (example  4) that returns false.

**Comment by NDR0216** [comment]
`a` and `b` could be 0

**Comment by gourab9817** [comment]
In the test case add a test case
1) where the value of c  should be 4 
2)where the value of c  should be 0
![Screenshot 2024-07-12 215049](https://github.com/user-attachments/assets/f8287472-eb1d-47a2-ac8f-fe63f72b7f78)
