### ISSUE TITLE
Missing Test Case - 199. Binary Tree Right Side View

### ISSUE THREAD

**Issue by adhithya-srinivasan** [LeetCode-Feedback/LeetCode-Feedback#2277]
#### Your LeetCode username

adhithyasrinivasan

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Extra test case

#### Code you used for Submit/Run operation

```
def rightSideView(self, root: TreeNode) -> List[int]:
        ans = {}
        def dfs(node, H):
            if not node: return 
            
            dfs(node.right, H + 1)
            if H not in ans: ans[H] = node.val
            dfs(node.left, H + 1)
            
        dfs(root, 0)
        return [ans[i] for i in range(len(ans))]
```
```
[1,2,3,null,5,null,4,6,7,null,6,9,null,5,6]
```
#### Language used for code

python

**Comment by lc-kay** [comment]
@adhithya-srinivasan To understand your report better, can you please provide more details? Thank you.

**Comment by lc-kay** [comment]
Hi @adhithya-srinivasan 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
