### ISSUE TITLE
[BUG] - Regular Expression Matching Invalid input

### ISSUE THREAD

**Issue by xavyding** [LeetCode-Feedback/LeetCode-Feedback#22788]
### LeetCode Username

dyxuki

### Problem Number, Title, and Link

https://leetcode.com/problems/regular-expression-matching/description/

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

the test case:
s = "aa", p = "**"  should be considered as "invalid input", but it returns the 'false' bool

### Language Used for Code

Python/Python3

### Expected behavior

Invalid input.

### Screenshots

![Screenshot from 2024-06-18 18-36-33](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/83537196/1b5151c2-1474-4a6b-8e22-b73969e0ed74)

**Comment by luciphania** [comment]
Thank you for your time.

Your feedback has been used to enhance the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
