### ISSUE TITLE
[BUG] - Missing Test case for #73

### ISSUE THREAD

**Issue by ghost** [LeetCode-Feedback/LeetCode-Feedback#22782]
### LeetCode Username

Z3ROsum

### Problem Number, Title, and Link

73. Set Matrix Zeroes https://leetcode.com/problems/set-matrix-zeroes/

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

An accepted code gets Wrong Answer for the following test case:

```
matrix = [[-100,1,1],[1,0,1],[1,1,1]]
```
The code returns `[[0,0,1],[0,0,0],[1,0,1]]` while the expected result is `[[-100,0,1],[0,0,0],[1,0,1]]`

### Language Used for Code

Python/Python3

### Code used for Submit/Run operation

```bash
class Solution:
    def setZeroes(self, matrix):
        x = -20; z = 5
        n = len(matrix)
        m = len(matrix[0])
        
        for i in range(n):
            for j in range(m):
                if not matrix[i][j]:
                    for k in range(n):
                        if matrix[k][j]:
                            matrix[k][j] = (k+j+z) * x
                    for k in range(m):
                        if matrix[i][k]:
                            matrix[i][k] = (i+k+z) * x
        
        for i in range(n):
            for j in range(m):
                if matrix[i][j] == (i+j+z) * x:
                    matrix[i][j] = 0
```

### Expected behavior

The code is wrong for that test case but it still is Accepted.

### Screenshots

<img width="302" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/66195939/730033cc-77ab-4f71-9001-94b03b1b3dfe">

### Additional context

<img width="606" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/66195939/05275f3b-a29d-4019-befa-d969382cabf9">

**Comment by qingy2019** [comment]
@LC-Pamela  @luciphania please look into this. thank you.
