### ISSUE TITLE
[BUG] - Wrong Example in the Description

### ISSUE THREAD

**Issue by user1689** [LeetCode-Feedback/LeetCode-Feedback#22791]
### LeetCode 用户名

stoic-goldbergqp4

### 问题号码、标题和链接

2694. Event Emitter https://leetcode.cn/problems/event-emitter/description

### Bug Category

问题描述

### 描述

In the description of 2694 Event Emitter, the values array of example 1 miss a parameter.
**Example 1:**
> Input: 
> actions = ["EventEmitter", "emit", "subscribe", "subscribe", "emit"], 
> values = [[], ["firstEvent", "function cb1() { return 5; }"],  ["firstEvent", "function cb1() { return 6; }"], ["firstEvent"]]
> Output: [[],["emitted",[]],["subscribed"],["subscribed"],["emitted",[5,6]]]
> Explanation: 
> const emitter = new EventEmitter();
> emitter.emit("firstEvent"); // [], no callback are subscribed yet
> emitter.subscribe("firstEvent", function cb1() { return 5; });
> emitter.subscribe("firstEvent", function cb2() { return 6; });
> emitter.emit("firstEvent"); // [5, 6], returns the output of cb1 and cb2

### 你使用的语言

None

### 期望行为

This is a correct version. 
**Example 1:**
> Input: 
> actions = ["EventEmitter", "emit", "subscribe", "subscribe", "emit"], 
> values = [[], ["firstEvent"], ["firstEvent", "function cb1() { return 5; }"],  ["firstEvent", "function cb1() { return 6; }"], ["firstEvent"]]
> Output: [[],["emitted",[]],["subscribed"],["subscribed"],["emitted",[5,6]]]
> Explanation: 
> const emitter = new EventEmitter();
> emitter.emit("firstEvent"); // [], no callback are subscribed yet
> emitter.subscribe("firstEvent", function cb1() { return 5; });
> emitter.subscribe("firstEvent", function cb2() { return 6; });
> emitter.emit("firstEvent"); // [5, 6], returns the output of cb1 and cb2

### 屏幕截图

![Screen Shot 2024-06-18 at 11 02 17 AM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/89725525/ff35bb64-f119-4678-9b8c-34726d472788)

**Comment by amcones-lc** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。
