### ISSUE TITLE
Missing Test Case - Missing Test Case - 199. Binary Tree Right Side View

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#2279]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution is accepted but fails on the following test case:

[23, 28, null, 21, null, 6, 19, 48, 8, null, null, null, null, 22, 31, null, null, 4, 36, 34, 30, null, null, null, null, 27, 2, null, null, 3, 26, null, null, 55, null, 1, null, 15, 41, null, null, 37, 39, 14, 51, null, null, null, null, 46, null, 32, 12, null, null, 45, 9, null, null, 29, 10, null, null, null, 18, 43, 25, 47, 50, null, 7, null, null, null, null, 40, 44, 17, null, null, null, 49, null, 35, 20, 11, 54, 53, 5, null, null, 52, 33, null, null, null, 16, null, null, 42, 38, null, null, null, null, 13, 24, null, null, null, null]

#### Code you used for Submit/Run operation

```
/**
 * Definition for a binary tree node.
 * public class TreeNode {
 *     int val;
 *     TreeNode left;
 *     TreeNode right;
 *     TreeNode() {}
 *     TreeNode(int val) { this.val = val; }
 *     TreeNode(int val, TreeNode left, TreeNode right) {
 *         this.val = val;
 *         this.left = left;
 *         this.right = right;
 *     }
 * }
 */
class Solution {
    private static class Holder {
        private int y;
        private int value;
    }
    
    private Map<Integer, Holder> map = new HashMap<>();
    
    private void helper(TreeNode node, int x, int y, int n) {
        if (node == null) {
            return;
        }
        
        Holder holder = map.get(x);
        if (holder == null || holder.y < y) {
            Holder newHolder = new Holder();
            newHolder.y = y;
            newHolder.value = node.val;
            map.put(x, newHolder);
        }
        
        helper(node.left, x + 1, y - n, n / 2);
        helper(node.right, x + 1, y + n, n / 2);
    }
    
    public List<Integer> rightSideView(TreeNode root) {
        List<Integer> ret = new ArrayList<>();
        
        helper(root, 0, 0, 100000000);
        
        int level = 0;
        while (true) {
            Holder holder = map.get(level++);
            if (holder == null) {
                break;
            }
            ret.add(holder.value);
        }
        
        return ret;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/107116498-906a9880-6841-11eb-909c-03b93a965b52.png)

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
