### ISSUE TITLE
[Missing Testcase] - A testcase should be added

### ISSUE THREAD

**Issue by sharmaishan2511** [LeetCode-Feedback/LeetCode-Feedback#22792]
### LeetCode Username

sharma_ishan2511

### Problem Number, Title, and Link

826. Most Profit Assigning Work https://leetcode.com/problems/most-profit-assigning-work

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

In the given question, one of the top solutions to solve the problem is sorting pair of <difficulty,profit> as well as worker and using this to get the best profit and add it to the answer. I have provided the code. However this would not work for specific testcase such as the one that I am about to give you.

```
difficulty = [2,4,6,8,10,13,12,67,45]

profit = [10,20,30,40,50,90,45,67,88]

worker = [4,5,6,7,32,21]
```

The expected answer to this as given by leetcode is actually 280 but the algorithm is giving the answer as 200.
While submitting the same approach on leetcode, we are getting the answer accepted. Hence there is a need to add such a testcase.

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
class Solution {
public:
    int maxProfitAssignment(vector<int>& difficulty, vector<int>& profit, vector<int>& worker) {
        vector<pair<int,int>> vec;
        int n = profit.size();
        int m = worker.size();
        for(int i = 0;i<n;i++){
            vec.push_back({difficulty[i],profit[i]});
        }

        sort(vec.begin(),vec.end());
        sort(worker.begin(),worker.end());

        int ans = 0;
        int j = 0;
        int best = 0;
        
        for(int i = 0;i<m;i++){
            while(j<m && worker[i]>=vec[j].first){
                best = max(best,vec[j].second);
                j++;
            }

            ans+=best;
        }

        return ans;
    }
};
```

### Expected behavior

The algorithm should not be used since it is wrong. There is another approach to the problem using dynamic programming which shoul be used in the question rather than the sorting one which I have given and a lot of people also have given.

```
class Solution {
public:
    int maxProfitAssignment(vector<int>& difficulty, vector<int>& profit, vector<int>& worker) {
        // vector<pair<int,int>> dfprf;
        // brute force for each worker loop again, this can pass but barely
        // would binary search work?
        // each worker maximum profit for same or minimum difficulty
        // dp where each i is max profit till this much difficulty
        // i think this could work

        int dp[100005];
        memset(dp, 0 , sizeof dp);

        int n  = profit.size();

        for(int i = 0 ; i<n ; i++)
            dp[difficulty[i]] = max( dp[difficulty[i]] , profit[i]);
        
        for(int i = 1 ; i < 100005; i++)
            dp[i] = max(dp[i] , dp[i-1]);
        int res = 0;

        for(auto j: worker)
            res+=dp[j];
        return res;
    }   
};
```

The above code is given by [Pjdope](https://leetcode.com/u/Pjdope/).
This would pass the test case which I had given earlier.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/124192024/7366775f-bfc0-47d5-a85f-b7f8a24c1e20)

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/124192024/a817c321-4df0-4deb-933e-16b25ea0f518)

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/124192024/993c8f9d-a68c-42bc-9cbb-34df51f2203e)

**Comment by msluszniak** [comment]
Good call, this test case definitely should be added. However, the sorting approach may still be applicable if you guarantee that every element with greater difficulty also has a bigger profit. Code for reference

```cpp
class Solution {
    #define vi vector<int>
    #define vpi vector<pair<int, int>>
    #define sz(c) (c).size()
    #define all(c) (c).begin(), (c).end()
    #define rall(c) (c).rbegin(), (c).rend()
public:
    int maxProfitAssignment(vi& difficulty, vi& profit, vi& worker) {
        size_t n = sz(profit), m = sz(worker);
        vpi comb(n);
        for(int i = 0; i < n; ++i){
            comb[i].first = difficulty[i];
            comb[i].second = profit[i];
        }

        sort(all(comb));
        sort(all(worker));
        vpi temp{};
        for(int i = n - 1; i >= 0; --i){
            while(!temp.empty() and temp.back().second < comb[i].second){
                temp.pop_back();
            }
            temp.push_back(comb[i]);
        }

        int res = 0;
        int i = 0, j = m - 1;
        while(i < temp.size() and j >= 0){
            while(i < temp.size() and temp[i].first > worker[j]){
                ++i;
            }
            if(i < temp.size()) res += temp[i].second;
            --j;
        }
        return res;
    }
};
```
