### ISSUE TITLE
P689. Confusing explanation of solution

### ISSUE THREAD

**Issue by mdtareque** [LeetCode-Feedback/LeetCode-Feedback#228]
**What kind of the bug**
- [x] solution

**Describe the bug**
689. Maximum Sum of 3 Non-Overlapping Subarrays > Approach 1
The solution explanation makes use of **same variable names in lowercase and uppercase**, and this is leading to confusion.

The explanation should be updated, so that the reader understands the solution correctly, without confusion.

Pasting the text from the solution that should be updated:

> ..... Given some array `W` and an integer `K`, what is the lexicographically smallest tuple of indices (i, j, k) with `i + K <= j` and `j + K <= k` that maximizes `W[i] + W[j] + W[k]`?

Confusing part `i + K <= j` and `j + K <= k`. 

**What sould it be updated to?**

The `k` is part of the problem statement, so the indices/variable names should be updated to `i,j,l` or even better `p,q,r`.

**Expected behavior**
Solution wording should be updated as described above.

**Additional context**
https://leetcode.com/problems/maximum-sum-of-3-non-overlapping-subarrays/solution/

**Comment by CooperCooperCooper** [comment]
Hi @mdtareque,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @
Thank you for your time. We've used your feedback to update the variable name. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
