### ISSUE TITLE
CSS BUG

### ISSUE THREAD

**Issue by adhavalboy** [LeetCode-Feedback/LeetCode-Feedback#2280]
#### Your LeetCode username
thewal

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] CSS

#### Description of the bug
The malicious script should not allow  

#### Screenshots

![Screenshot 2021-02-06 at 5 38 27 PM](https://user-images.githubusercontent.com/16662228/107117767-888f1080-68a2-11eb-9566-2b2a9ef33a35.png)

**Comment by lc-kay** [comment]
Hi @adhavalboy,
Thank you for your time. Upon investigating this issue, we found this issue to be non-content-related (the issue stems from an origin away from the content on this problem); therefore, it's not valid for content contribution reward. 
We encourage you to share more content-related issues here with us for [valid content contribution rewards](https://leetcode.com/discuss/general-discussion/526802/File-Problem-and-Solution-Content-Issues-to-Our-GitHub-Public-Feedback-Repo-Now!). For further assistance on this issue, please reach out to us through the help desk or support@leetcode.com/ Thank you again for your support and understanding.
