### ISSUE TITLE
Missing Test Case - 199. Binary Tree Right Side View

### ISSUE THREAD

**Issue by shakedt** [LeetCode-Feedback/LeetCode-Feedback#2281]
#### Your LeetCode username

shakedt

#### Category of the bug
- [ X ] Question 
- [ ] Solution
- [ ] Language
Question

#### Description of the bug

I think one of the tests is wrong, 
test case: [1,2] expects to get [1,2] back.
for that to happen it need to be [1, null, 2]

#### Code you used for Submit/Run operation

```
var rightSideView = function(root) { 
    if(!root) return [];
    
    const rightSideArray = [];
    let rooty = root;
    
    rightSideArray.push(rooty.val);
    
    if (rooty.right) {
       rightSideArray.push(...rightSideView(rooty.right));
    }
    
    return rightSideArray;
};
```

#### Language used for code

javascript

#### Expected behavior

test case: [1,2] expects to get [1,2] back.
should be [1,null, 2] expects [1,2]
or [1,2] expects [1];

**Comment by KhaledSobhy10** [comment]
The test case is correct  , answer is here >> https://www.youtube.com/watch?v=jCqIr_tBLKs

**Comment by shakedt** [comment]
ty seems that I misunderstood the question completely.
