### ISSUE TITLE
[BUG] - 1075 测试用例的预期结果与题目要求不符

### ISSUE THREAD

**Issue by KilianShen** [LeetCode-Feedback/LeetCode-Feedback#22815]
### LeetCode 用户名

KilianShen

### 问题号码、标题和链接

项目员工 I https://leetcode.cn/problems/project-employees-i/description/

### Bug Category

不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*

### 描述

预期结果与问题描述不一致。题目要求保留2位小数，但测试用例的预期结果不相符导致不通过；

### 你使用的语言

MySQL

### 你提交或者运行的代码

```bash
SELECT p.project_id, FORMAT(AVG(e.experience_years),2) AS average_years
FROM Project AS p LEFT JOIN Employee AS e
ON p.employee_id = e.employee_id
GROUP BY p.project_id;
```

### 期望行为

预期结果与题目要求一致

### 屏幕截图

<img width="1259" alt="Snipaste_2024-06-21_16-07-48" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/86402559/7cc2ecf8-5d14-4916-b6e5-0321f239dd97">

**Comment by amcones-lc** [comment]
您好，在与相关团队核实后：***不处理***（题目需要以 number 格式返回数据，不能是 string，相关做题体验正在优化中）。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
