### ISSUE TITLE
[BUG] - <title>

### ISSUE THREAD

**Issue by amritv0306** [LeetCode-Feedback/LeetCode-Feedback#22817]
### LeetCode Username

amritishoney

### Problem Number, Title, and Link

1052. Grumpy Bookstore Owner https://leetcode.com/problems/grumpy-bookstore-owner/submissions/1295558352

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

Incorrect testcase, given:-
customers = [4,10,10]
grumpy = [1,1,0]
minutes = 2
acc to question, the output should be 20 not 24 because, as the consecutive 2 mins the shopkeeper is not grumpy therefore the maximum numbers of  customers satisfied would be 20 as on the first min the shopkeeper is grumpy so the customers on the 1st min would not be satisfied. 
Pls change the testcase solution asap

### Language Used for Code

Python/Python3

### Code used for Submit/Run operation

```bash
class Solution(object):
    def maxSatisfied(self, customers, grumpy, minutes):
        max_sum1 = 0
        for i in range (len(customers)-minutes+1):
            sum = 0
            for m in range(minutes):
                sum += customers[i+m]
            if (sum>max_sum1):
                max_sum1 = sum
                x = i
        del customers[x:x+3]
        del grumpy[x:x+3]
        
        max_sum2 = 0
        for j in range(len(grumpy)):
            if (grumpy[j] == 0):
                max_sum2 +=  customers[j]

        return max_sum1 + max_sum2
```

### Expected behavior

Incorrect testcase, given:-
customers = [4,10,10]
grumpy = [1,1,0]
minutes = 2
acc to question, the output should be 20 not 24 because, as the consecutive 2 mins the shopkeeper is not grumpy therefore the maximum numbers of  customers satisfied would be 20 as on the first min the shopkeeper is grumpy so the customers on the 1st min would not be satisfied. 
Pls change the testcase solution asap

**Comment by Satyam-Dwivedi-48** [comment]
Hi amritishoney 
let me break it down for you
[4,10,10]-> best score with all grumpy customers in picture is 10 here(last element is counted)
[1 , 1 ,  0]
as the interval that is possible is 2

lets take the first window into consideration containing first 2 elements.
[[4,10],10]
as our window covers the 2 elements which are grumpy, the customers added to our non grumpy count will be 4+10=>14
already 10 exists in the non grumpy customers count(last element)

hence the total non grumpy people from 1st window is 14+10=> 24
and this is the maximum hence the answer is 24

Hope this clarifies your doubt.

**Comment by amritv0306** [comment]
@Satyam-Dwivedi-48 
i got it thanks :)
