### ISSUE TITLE
Wrong test case for 334-Increasing Triplet Subsequence

### ISSUE THREAD

**Issue by IamShashankkkk** [LeetCode-Feedback/LeetCode-Feedback#22828]
### LeetCode Username

IamShashankkkk

### Problem Number, Title, and Link

334. Increasing Triplet Subsequence https://leetcode.com/problems/increasing-triplet-subsequence/

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

nums = [20,100,10,12,5,13] 
output will be->false it showing true. 

### Language Used for Code

Java

### Code used for Submit/Run operation

```bash
class Solution {
    public boolean increasingTriplet(int[] nums) {
        for(int i = 0 ; i < nums.length-2 ; i++){
            if(nums[i] < nums[i + 1] && nums[i + 1] < nums[i + 2]){
                return true;
            }
        }
        return false;
    }
}
```

### Expected behavior

Make it correct because it takes too much time of me for finding the reason ,at where point i would be wrong .

### Screenshots

![Screenshot (60)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/109219161/8c6b2f6b-7005-493b-9503-513e26701363)

**Comment by IamShashankkkk** [comment]
Have you seen 5 in between 12 & 13 . there is a sequence of
20,100,10,12,5,13

you unseen integer at the nums[4] which is 5.

**Comment by Hr1t1k** [comment]
it doesn't have to be consecutive , i<j<k && arr[i]>arr[j]>arr[k] this condition should be satisified even if i=0 ,j=2 , k=4 and arr[0]>arr[2]>arr[4] then it will be true

**Comment by maa9605** [comment]
The problem is improperly worded.   i,j,k are consecutive elements within a subset of characters, and it stands to reason that a given solution should only evaluate subsets of 3 consecutive elements.  

You should have said "If exists a subset of three integers such that the value of each element in the subset and its index is less than the next element in the subset"
