### ISSUE TITLE
[BUG] - Missing Test Case for 3193. Count the Number of Inversions

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#22833]
### LeetCode Username

stormsunshine

### Problem Number, Title, and Link

3193. Count the Number of Inversions https://leetcode.com/problems/count-the-number-of-inversions

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

An accepted solution fails on a specific test case. The test case is as follows.

```
3
[[2,2],[0,1]]
```

### Language Used for Code

Java

### Code used for Submit/Run operation

```bash
class Solution {
    static final int MODULO = 1000000007;

    public int numberOfPermutations(int n, int[][] requirements) {
        int[] inversions = new int[n + 1];
        Arrays.fill(inversions, -1);
        for (int[] requirement : requirements) {
            inversions[requirement[0] + 1] = requirement[1];
        }
        int k = inversions[n];
        long[][] dp = new long[n + 1][k + 1];
        dp[0][0] = 1;
        dp[1][0] = 1;
        for (int i = 2; i <= n; i++) {
            for (int j = 0; j <= k; j++) {
                dp[i][j] = (dp[i - 1][j] + (j >= 1 ? dp[i][j - 1] : 0) - (j >= i ? dp[i - 1][j - i] : 0)) % MODULO;
                if (dp[i][j] < 0) {
                    dp[i][j] += MODULO;
                }
            }
            if (inversions[i] >= 0) {
                for (int j = 0; j <= k; j++) {
                    if (j != inversions[i]) {
                        dp[i][j] = 0;
                    }
                }
            }
        }
        return (int) dp[n][k];
    }
}
```

### Expected behavior

Add the missing test case so that the solution above won't get accepted.

**Comment by luciphania** [comment]
Hello, 

Your reported issue has been relayed to our team for thorough investigation. We appreciate your patience as we work to address and resolve this matter. We will reach out to you when we have updates regarding the issue. 

If you have any further questions or concerns in the meantime, please feel free to let us know. 

Best regards, 
LeetCode Support Team

**Comment by luciphania** [comment]
Thank you for your time.

Your feedback has been used to enhance the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
