### ISSUE TITLE
Missing Test Case - 196. Delete Duplicate Emails

### ISSUE THREAD

**Issue by msaqib4203** [LeetCode-Feedback/LeetCode-Feedback#2283]
#### Your LeetCode username

msaqib4203

#### Category of the bug
- [ ] Question

#### Description of the bug

The output is not correct

#### Code you used for Submit/Run operation

```
select id from person
```

#### Language used for code

SQL

#### Expected behavior

Input: {"headers": {"Person": ["Id", "Email"]}, "rows": {"Person": [[1, "john@example.com"], [2, "bob@example.com"], [3, "john@example.com"]]}}

Query: select id from person
Output: {"headers": ["Id", "Email"], "values": [[1, "john@example.com"], [2, "bob@example.com"], [3, "john@example.com"]]}
Correct output for the query must show only the id. It seems like the output doesn't change as I tried different queries.

**Comment by lc-kay** [comment]
@msaqib4203 Please provide the code you used to reach this result, thank you.

**Comment by msaqib4203** [comment]
> @msaqib4203 Please provide the code you used to reach this result, thank you.

Hi,

I have mentioned the SQL Query used: "select id from person"

**Comment by lc-kay** [comment]
@msaqib4203 The expected output is correct and as you mentioned, it shows only the id. Please check out the discuss section to reference accepted codes or post your code there to receive support from other LeetCoders. Thank you for your time.
