### ISSUE TITLE
[BUG] - Similar Questions

### ISSUE THREAD

**Issue by Zanger67** [LeetCode-Feedback/LeetCode-Feedback#22845]
### LeetCode Username

Zanger

### Problem Number, Title, and Link

419. Battleships in a Board https://leetcode.com/problems/battleships-in-a-board/description/

### Bug Category

Incorrect or missing "Related Topics"

### Bug Description

Question didn't have any linked similar/related questions so I thought I'd provide some that it reminded me of:

```
286. Walls and Gates
695. Max Area of Island
200. Number of Islands
994. Rotting Oranges
```

### Language Used for Code

None

### Expected behavior

---

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/36343598/d2a41768-3d62-4919-b5ce-73698556f3bf)

**Comment by luciphania** [comment]
Hello,

Your reported issue has been relayed to our team for thorough investigation. We appreciate your patience as we work to address and resolve this matter. We will reach out to you when we have updates regarding the issue.

If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by Zanger67** [comment]
Ty!
Also noticed today that 
`1020.` Number of Enclaves https://leetcode.com/problems/number-of-enclaves/description/
`1254.` Number of Closed Islands https://leetcode.com/problems/number-of-closed-islands/description/
could also be linked :)

**Comment by luciphania** [comment]
Thank you for your time.

Your feedback has been used to enhance the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
