### ISSUE TITLE
Test Case Missing!!!

### ISSUE THREAD

**Issue by py-Aditya-cpp** [LeetCode-Feedback/LeetCode-Feedback#22841]
### LeetCode Username

Aditya_Goyal1694

### Problem Number, Title, and Link

145. Binary Tree PostOrder Traversal https://leetcode.com/problems/binary-tree-postorder-traversal/description/

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

Test Case:
Consider the binary tree represented as follows:
[3,9,1,6,10,null,9]

Expected Result:
The correct post-order traversal for this binary tree should be [6,10,9,9,1,3].

Incorrect Output:
The current solution produces [6,10,9,1,3].

And still the code is getting accepted.

The problem arises when dealing with similar values. My approach was to check the value of left or right node in the resultant vector while using iterative approach. This can be a problem since multiple nodes can have similar values.
Either the problem statement should state that all the values are different but that won't be a generic case.

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
class Solution {
public:
    vector<int> postorderTraversal(TreeNode* root) {
        vector<int> res;
        if(!root) return res;

        stack<TreeNode*> st;
        int flag=1;

        st.push(root);

        while(!st.empty()){
            TreeNode* temp=st.top();
            if(flag){
                if(temp->right) st.push(temp->right);
                if(temp->left) st.push(temp->left);
                if(!temp->right && !temp->left) flag=0;
            }
            else{
                int n=res.size()-1;

                //Set flag 1 if either child exists and last element in res is equal to one of its child

                if(temp->right){
                    if(!res.empty() && res[n]!=temp->right->val){
                        flag=1;
                        continue;
                    }
                }
                else if(temp->left && !res.empty() && res[n]!=temp->left->val){
                    flag=1;
                    continue;
                }

                res.push_back(temp->val);
                st.pop();
            }
        }

        return res;
    }
};
```

### Expected behavior

Test Case: [3,9,1,6,10,null,9]

Expected Result:
The correct post-order traversal for this binary tree should be [6,10,9,9,1,3].

Incorrect Output:
The current solution produces [6,10,9,1,3].

### Screenshots

![Screenshot 2024-06-24 035732](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/112880748/2bcd4580-2e10-4069-bf5e-991b160704f6)
![Screenshot 2024-06-24 035710](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/112880748/4b2be18a-7fac-4474-aa42-80bd2235b7b5)

**Comment by luciphania** [comment]
Hello,

Your reported issue has been relayed to our team for thorough investigation. We appreciate your patience as we work to address and resolve this matter. We will reach out to you when we have updates regarding the issue.

If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team
