### ISSUE TITLE
[BUG] - <缺陷标题> 88.合并两个有效数组 程序运行结果存在问题

### ISSUE THREAD

**Issue by Y-NN** [LeetCode-Feedback/LeetCode-Feedback#22843]
### LeetCode 用户名

Jovial Mendeleev3JB

### 问题号码、标题和链接

88.合并两个有效数组  https://leetcode.cn/problems/merge-sorted-array/

### Bug Category

不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*

### 描述

#我的代码

class Solution:
    def merge(self, nums1: List[int], m: int, nums2: List[int], n: int) -> None:
        """
        Do not return anything, modify nums1 in-place instead.
        """
        
        if n==0:
            nums1=nums1
        elif m==0:
            nums1=nums2 #why this does not work
            #nums1.pop()
            #nums1[:]=nums2[:]
            #nums1.append(nums2[-n:])
        else:
            nums1[-n:]=nums2 #when -m pass initial test, this is definitely bug
        
        nums1.sort(reverse=False
                  )
        
        return None

### 你使用的语言

Python/Python3

### 你提交或者运行的代码

```bash
class Solution:
    def merge(self, nums1: List[int], m: int, nums2: List[int], n: int) -> None:
        """
        Do not return anything, modify nums1 in-place instead.
        """
        
        if n==0:
            nums1=nums1
        elif m==0:
            nums1=nums2 #why this does not work
            #nums1.pop()
            #nums1[:]=nums2[:]
            #nums1.append(nums2[-n:])
        else:
            nums1[-n:]=nums2 #when -m pass initial test, this is definitely bug
        
        nums1.sort(reverse=False
                  )
        
        return None
```

### 屏幕截图

![Uploading IMG_0086.png…]()

**Comment by amcones-lc** [comment]
您好，在与相关团队核实后：***不处理***（该题需要在 `nums1` 中原地修改，不能修改 `nums1` 数组的地址）。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
