### ISSUE TITLE
[BUG] - Missing test case (code accepted)

### ISSUE THREAD

**Issue by mfirozahmed** [LeetCode-Feedback/LeetCode-Feedback#22842]
### LeetCode Username

mfirozahmed

### Problem Number, Title, and Link

1438. Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit https://leetcode.com/problems/longest-continuous-subarray-with-absolute-diff-less-than-or-equal-to-limit/

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

Hello. I found a solution that is accepted, but it should be time limit exceeded. So, I think there is a test case missing. For sliding window approach this code works, but I can create test case which is correct for constraints, but not for this solution.

My created test case is: 

```
nums = [100000, 99999, 99998, 99997, 99996, ...... , 3, 2, 1] //100000 to 1 in decending order
limit = 40000
```

### Language Used for Code

Go

### Code used for Submit/Run operation

```bash
func longestSubarray(nums []int, limit int) int {
    left, right, mn, mx, cnt := 0, 0, 0, 0, 0

    for right < len(nums) {
        if nums[mn] >= nums[right] {
            mn = right
        }
        if nums[mx] <= nums[right] {
            mx = right
        }

        if nums[mx] - nums[mn] <= limit {
            right++
        } else {
            cnt = max(cnt, right - left)
            left = min(mn, mx) + 1
            mn, mx = left, left
            right = left + 1
        }
    }

    cnt = max(cnt, right - left)
    return cnt
}

func max(a, b int) int {
	if a > b {
		return a
	}
	return b
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}
```

### Expected behavior

It is accepted but should be time limit exceeded.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/44208637/45db5844-16cb-46f8-807f-db584da3f698)

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/44208637/cea9aa07-7e58-4f3f-be79-7c1476d71093)

**Comment by luciphania** [comment]
Hello,

Your reported issue has been relayed to our team for thorough investigation. We appreciate your patience as we work to address and resolve this matter. We will reach out to you when we have updates regarding the issue.

If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team
