### ISSUE TITLE
Missing test case (Incorrect/Inefficient Code getting accepted because of missing test cases)

### ISSUE THREAD

**Issue by Sayak0504** [LeetCode-Feedback/LeetCode-Feedback#22840]
### LeetCode Username

sayaksardar04

### Problem Number, Title, and Link

551. Student Attendance Record I https://leetcode.com/problems/student-attendance-record-i/

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

There is no test case with two absents at the end; that's why the solution did not check whether the last character contained the letter 'A'.

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
class Solution {
public:
    bool checkRecord(string s) {
        int a = 0,t = s.length();
        for(int i =0;i<t-2;i++){
            if(s[i] == 'L' && s[i] == s[i+1] && s[i+1] == s[i+2]) return false;
            if(s[i] == 'A') a++;
        }

        if( t == 2){
            return (s[0] != 'A' || s[1] != 'A');
      
        }
        if(a<2) return true;
        else return false;
    }
};
```

### Expected behavior

1. "PPLLAA" 
2. "PPLALA"
The output should be False for the test cases. But the code returns True
So, the code should not be accepted as it is incorrect for some test cases that are not included. 

### Screenshots

![334543808-c5910b60-e3c2-475a-8c5c-58081027b1e2](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/164259687/b9656845-43d7-47dc-bda2-4191944148d8)

### Additional context
![Screenshot (118)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/164259687/62ec8eb4-0f7b-46e7-9b65-69c2203f921a)

_No response_

**Comment by luciphania** [comment]
Hello,

Your reported issue has been relayed to our team for thorough investigation. We appreciate your patience as we work to address and resolve this matter. We will reach out to you when we have updates regarding the issue.

If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team
