### ISSUE TITLE
[BUG] - NPE in GraphSerializer.dfsValues

### ISSUE THREAD

**Issue by vremennyi** [LeetCode-Feedback/LeetCode-Feedback#22844]
### LeetCode Username

vremennyi

### Problem Number, Title, and Link

133. Clone Graph https://leetcode.com/problems/clone-graph

### Bug Category

Problem examples

### Bug Description

Test result visualisation does not expect null values from control result when users output is not null.

- When expected and users output are null - all OK
- When expected not null and users output is null - all OK
- When expected null and users output is not null - NPE

```
Runtime Error
java.lang.NullPointerException: Cannot read field "val" because "<parameter1>" is null
  at line 150, GraphSerializer.dfsValues
  at line 175, GraphSerializer.serialize
  at line 236, __Driver__.main
```

### Language Used for Code

Java

### Code used for Submit/Run operation

```bash
class Solution {
    public Node cloneGraph(Node node) {
        return new Node();
    }
}
```

### Expected behavior

Shows the difference between expected result and users output

**Comment by luciphania** [comment]
Hello,

Your reported issue has been relayed to our team for thorough investigation. We appreciate your patience as we work to address and resolve this matter. We will reach out to you when we have updates regarding the issue.

If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team
