### ISSUE TITLE
[BUG] - Problem VIsuals not clearly visible

### ISSUE THREAD

**Issue by reejuBhattacharya** [LeetCode-Feedback/LeetCode-Feedback#22848]
### LeetCode Username

reejubhai

### Problem Number, Title, and Link

https://leetcode.com/problems/find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance/description/

### Bug Category

Problem description

### Bug Description

The visuals in the problem description are not visible clearly in dark mode.

### Language Used for Code

None

### Expected behavior

Background should be white for the visuals, not transparent.

### Screenshots

<img width="399" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/40564575/5d408e4c-51f4-4365-87fc-252aa78f80fd">

**Comment by luciphania** [comment]
Hello,

Your reported issue has been relayed to our team for thorough investigation. We appreciate your patience as we work to address and resolve this matter. We will reach out to you when we have updates regarding the issue.

If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by luciphania** [comment]
Hi there,

Thank you for taking the time to share your feedback with us. 

After carefully considering it, we have decided not to move forward with the changes you suggested in your feedback at this time.

Please know that your input is important to us, and we're actively exploring alternative solutions. We would greatly appreciate your continued feedback as we improve our platform.

Best regards,
LeetCode Support Team
