### ISSUE TITLE
 [BUG] - 1438 - missing test case

### ISSUE THREAD

**Issue by giner** [LeetCode-Feedback/LeetCode-Feedback#22847]
### LeetCode Username

giner

### Problem Number, Title, and Link

1438. Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit https://leetcode.com/problems/longest-continuous-subarray-with-absolute-diff-less-than-or-equal-to-limit/

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

Missing test case allows n^2 time solution to pass

### Language Used for Code

Ruby

### Code used for Submit/Run operation

```ruby
def longest_subarray(nums, limit)
    result = 0
    left, right = 0, 0
    min, max = nums[0], nums[0]

    while right < nums.length
        max = [max, nums[right]].max
        min = [min, nums[right]].min
        right += 1

        if max - min > limit
            min = nums[left + 1..right - 1].min if min == nums[left]
            max = nums[left + 1..right - 1].max if max == nums[left]
            left += 1
        end

        result = [result, right - left].max
    end

    result
end
```

### Expected behavior

timeout is expected on the following test case
```
[1] * 50000 + [2] * 50000
0
```

**Comment by luciphania** [comment]
Hello,

Your reported issue has been relayed to our team for thorough investigation. We appreciate your patience as we work to address and resolve this matter. We will reach out to you when we have updates regarding the issue.

If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team
