### ISSUE TITLE
Testcase does not satisfy the constraint

### ISSUE THREAD

**Issue by Uvajanani** [LeetCode-Feedback/LeetCode-Feedback#22871]
### LeetCode Username

UvaPriya

### Problem Number, Title, and Link

152. Maximum Product Subarray https://leetcode.com/problems/maximum-product-subarray/

### Bug Category

Problem examples, Problem constraints, Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

**The description guaranteed that the answer will fit within 32-bit integer but the testcase 190 gives the output as long data type**

 

### Language Used for Code

Java

### Code used for Submit/Run operation

```bash
class Solution 
{
    public int maxProduct(int[] nums) 
    {
        int prefix=1;
        int suffix=1;
        int prod=Integer.MIN_VALUE;
        for(int i=0;i<nums.length;i++)
        {
            if(prefix==0)
                prefix=1;
            if(suffix==0)
                suffix=1;
            prefix*=nums[i];
            suffix*=nums[nums.length-i-1];
            prod=Math.max(prod,Math.max(prefix,suffix));
        }
        return prod;
        
    }
}
```

### Expected behavior

The testcase should be within 32-bit integer as per the description

### Screenshots

![Screenshot 2024-06-26 104955](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/146011743/19a084eb-4baa-4c3e-ae2d-2205212a5265)

### Additional context

Also the same code I have submitted three months back run successfully but now it shows test case error

**Comment by Uvajanani** [comment]
Thanks for your reply Sir

Test case 190:
[0,10,10,10,10,10,10,10,10,10,-10,10,10,10,10,10,10,10,10,10,0]
Output: 1000000000


### But this output exceeds the 32-bit integer and failed to satisfy the constraint as mentioned in the description



I will attach the screenshot for your reference

![Screenshot 2024-06-26 120353](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/146011743/996a7fcd-1b0d-4e0b-be8b-d963b44e8d3f)


![Screenshot 2024-06-26 120432](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/146011743/e3c38927-0e66-4388-a60f-8e3f63fe21ba)

**Comment by luciphania** [comment]
Hello there,

Thanks for reaching out!

While the given test case still satisfied the original constraints, the constraints have been updated such that any subarray product now fits inside 32-bit integer now.

Best,
LeetCode Support Team
