### ISSUE TITLE
Incorrect explanation in #506

### ISSUE THREAD

**Issue by snehasishroy** [LeetCode-Feedback/LeetCode-Feedback#2287]
#### Your LeetCode username
chrisgriffin

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
In https://leetcode.com/problems/relative-ranks/, in explanation of example 1, it's mentioned 
`For the left two athletes, you just need to output their relative ranks according to their scores.`

However it should be `For the last two athletes, you just need to output their relative ranks according to their scores`

**Comment by lc-kay** [comment]
Hi @snehasishroy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @snehasishroy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
