### ISSUE TITLE
Incorrect_testcase

### ISSUE THREAD

**Issue by Yanendrajha** [LeetCode-Feedback/LeetCode-Feedback#22875]
### LeetCode Username

Yanendra_jha

### Problem Number, Title, and Link

152. Maximum Product Subarray https://leetcode.com/problems/maximum-product-subarray/?source=submission-noac

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

[0,10,10,10,10,10,10,10,10,10,-10,10,10,10,10,10,10,10,10,10,0] 
In this particular Test case: - the multiplication of values from index 1 to n -2 become so small that it get stored positively in integer (As signed integer). Which in terms hinders the result of the solution.
Those who don't know how negative number are stored  in system will never be able to solve this problem. 

### Language Used for Code

Java

### Code used for Submit/Run operation

```bash
class Solution {
    public int maxProduct(int[] nums) {
        int ans = Integer.MIN_VALUE;
        int temp_mul = 1; // Required for multiplication
        for(int num : nums){
            if(num < 0){
                temp_mul *= num;
                ans = Math.max(ans, temp_mul);
            } else if (num == 0){
                temp_mul *= num;
                ans = Math.max(ans, temp_mul);
                temp_mul = 1;
            } else {
                temp_mul *= num;
                ans = Math.max(ans,temp_mul);
            }
        }
        temp_mul = 1;
        for(int i = nums.length-1; i >= 0; i--){
            if(nums[i] < 0){
                temp_mul *= nums[i];
                ans = Math.max(ans, temp_mul);
            } else if (nums[i] == 0){
                temp_mul *= nums[i];
                ans = Math.max(ans, temp_mul);
                temp_mul = 1;
            } else {
                temp_mul *= nums[i];
                ans = Math.max(ans,temp_mul);
            }
        }
        return ans;
    }
}
```

### Expected behavior

It's expected to r**eturn -10^18** but it returns **1981284352**

 Because of the way signed number are stored in system. also it's exceeding the **constraints**.
which hinders the solution of the question. Very sad to see such people.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/128150745/05dcd194-252b-4b57-91da-67c17dbd2077)

### Additional context

this particular test case is added just to make this question way out of league for new comers. even good leetcoder who don't know how signed integer is stored will not be able to solve it.

**Comment by bhaskarsantoshk** [comment]
@Yanendrajha

I have added an overflow check to the multiplication step in the brute-force solution to handle potential overflow scenarios. Here is the relevant code snippet:

```java
for (int i = 0; i < nums.length; i++) {
    int prod = 1;
    for (int j = i; j < nums.length; j++) {
        // Check for overflow before multiplication
        if (nums[j] > 0 && prod > Integer.MAX_VALUE / nums[j]) {
            break;
        }

        prod *= nums[j];
        maxProduct = Math.max(maxProduct, prod);

        // Reset product if zero is encountered to start fresh product calculation
        if (prod == 0) {
            break;
        }
    }
}
