### ISSUE TITLE
[BUG] - Incorrect test case

### ISSUE THREAD

**Issue by abhiperfect** [LeetCode-Feedback/LeetCode-Feedback#22888]
### LeetCode Username

abhi_perfecct007

### Problem Number, Title, and Link

152, Maximum Product Subarray, https://leetcode.com/problems/maximum-product-subarray/

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

"The test cases are generated so that the answer will fit within a 32-bit integer. However, the result of the following test case does not meet this condition:
nums[] = [0,10,10,10,10,10,10,10,10,10,-10,10,10,10,10,10,10,10,10,10,0]"

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
class Solution {
public:
    int maxProduct(vector<int>& nums) {
        int n = nums.size();
        long long pre = 1;
        long long suf = 1;
        long long maxProd = INT_MIN;

        for (int i = 0; i < n; ++i) {
            if (pre == 0)
                pre = 1;
            if (suf == 0)
                suf = 1;
            pre = pre * (long long)nums[i];
            suf = suf * (long long)nums[n - 1 - i];

            maxProd = max({maxProd, pre, suf});
        }

        return maxProd;
    }
};
```

### Expected behavior

I expected the solution to pass all test cases since it was clearly mentioned in the problem that "The test cases are generated so that the answer will fit in a 32-bit integer."

However, a runtime error occurred: 

```
Line 14: Char 23: runtime error: signed integer overflow: -1000000000000000000 * 10 cannot be represented in type 'long long' (solution.cpp)
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior solution.cpp:14:23
```

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/114478676/ee95a589-f419-44df-aae1-c56c73ffeda8)

If I use `double` instead of `long long`, all test cases pass.

### Screenshots

![Screenshot 2024-06-27 045440](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/114478676/17831ebc-1f33-47e2-8779-157f90dce8d9)
![Screenshot 2024-06-27 045227](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/114478676/a069d973-407c-4fcc-b1ab-66edf62cf5d8)

**Comment by BrandonStegall** [comment]
> Winston Tang commented: Dear abhi_perfecct007,
> 
> Thank you for reaching out. After reviewing your report, it appears the issue you're encountering stems from an integer overflow occurring within your code operations. While it's stated in the problem that the final result will fit within a 32-bit integer, this doesn't guarantee that all intermediate calculations within your specific solution will also fit.
> 
> The runtime error was generated due to a sign overflow. This is common when working with larger integers and can be remedied by using a different approach. Please consider revisiting your algorithm to ensure that the intermediate calculations do not exceed the range of the types you're using.
> 
> Remember that LeetCode problems are designed to test varying degrees of understanding in computer science concepts, including the ability to comprehend and account for language-specific intricacies like integer overflow.
> 
> Please do not hesitate to reach out with further questions or clarifications.
> 
> Happy coding!
> 
> Best, LeetCode Support Team

If the problem _only_ stated that the final result will fit within a 32-bit integer, I think you'd have a point, but the constraints also clearly state "The **product of _any_ prefix or suffix** of nums is **guaranteed** to fit in a 32-bit integer." I don't see how that constraint could possibly be interpreted in any other way than the intermediate calculations also being guaranteed to fit within a 32-bit integer.

**Comment by luciphania** [comment]
Hello there,

Thanks for reaching out!

While the given test case still satisfied the original constraints, the constraints have been updated such that any subarray product now fits inside 32-bit integer now.

Best,
LeetCode Support Team

**Comment by BrandonStegall** [comment]
@luciphania the test case neither meets the original constraints of the problem nor does it meet the updated constraints. 

Given the input [0,10,10,10,10,10,10,10,10,10,-10,10,10,10,10,10,10,10,10,10,0], the product 1000000000 * -10 does not fit within a 32 bit integer. It will overflow, resulting in the returned output becoming positive 8446744073709551616 rather than the expected 1000000000. This is resolved by using a float32 for the intermediate calculations, and converting back to an int32 at the end, but requiring us to do this is in direct conflict with the constraints provided for this problem.
