### ISSUE TITLE
Missing Test Case - 199. Binary Tree Right Side View

### ISSUE THREAD

**Issue by nag-gd9** [LeetCode-Feedback/LeetCode-Feedback#2289]
#### Category of the bug
- [ *] Question
- [ ] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
class Solution:
    def rightSideView(self, root: TreeNode) -> List[int]:
        
        if len(root) < 2:
            return None
        
        l = len(root)
        x = 0
        r = []

        try:
            r.append(root[0])
            while x <= l:
                f = x*2+2
                print(f)
                r.append(root[f])
                x = f
        except IndexError:
            pass


        return r
```

**Comment by lc-kay** [comment]
@nag-gd9 Please provide the content-related issue you encounter for this problem. Thank you.

**Comment by lc-kay** [comment]
Hi @nag-gd9 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
