### ISSUE TITLE
Missing Test Case - 1214. Two Sum BSTs

### ISSUE THREAD

**Issue by Inconite** [LeetCode-Feedback/LeetCode-Feedback#2290]
#### Your LeetCode username

SuperHak

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Test case missing. The following code passes all the test cases but it's wrong.

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean twoSumBSTs(TreeNode root1, TreeNode root2, int target) {
        HashSet<Integer> set1 = new HashSet();
        return checkPresense(set1, root1, root2, target);
    }
    
    public boolean checkPresense(Set<Integer> set1, TreeNode root1, TreeNode root2, int target){
        Queue<TreeNode> q = new LinkedList();
        q.add(root1);
        q.add(root2);
        while(!q.isEmpty()){
            TreeNode t = q.poll();
            if(set1.contains(target - t.val)) return true;
            set1.add(t.val);
            if(t.left != null) q.add(t.left);
            if(t.right != null) q.add(t.right);
        }
        return false;
    }
}
```

#### Language used for code

Java

#### Expected behavior

[2,1,4]
[1,0,3]
6

This test case should be included because the above code was accepted(passed all test cases) but it shouldn't.
In the above test case, 2 + 4 = 6 but this result is based on only one tree(As per the question, the sum should be taken from nodes from both trees).
The code above returns true but the expected answer is false but still, it passes all the test cases.

**Comment by lc-kay** [comment]
Hi @Inconite 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Inconite 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
