### ISSUE TITLE
[BUG] - Error Inserting URL from x.com on LeetCode Profile

### ISSUE THREAD

**Issue by levos-snr** [LeetCode-Feedback/LeetCode-Feedback#22905]
### LeetCode Username

levos-snr

### Problem Number, Title, and Link

1. Error Inserting URL from x.com on LeetCode Editing of Profile 

### Bug Category

Problem description

### Bug Description

I encountered an issue while trying to insert a URL from x.com (formerly Twitter) into the URL field on my LeetCode profile. The system gives an error message: "You must enter a valid username or URL for this site."

Steps to Reproduce:

Go to the profile settings page on LeetCode.
Attempt to insert the following URL: https://x.com/levos_snr
Click "Save".

Actual Result:
An error message appears stating, "You must enter a valid username or URL for this site."

### Language Used for Code

None

### Code used for Submit/Run operation

```bash
Steps to Reproduce:

Go to the profile settings page on LeetCode.
Attempt to insert the following URL: https://x.com/levos_snr
Click "Save".
```

### Expected behavior

- The URL should be accepted and saved to my profile without any errors.

- Actual Behavior:
  An error message appears stating, "You must enter a valid username or URL for this site."

### Screenshots

Screenshot:
![leetcode](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/75755882/2035cadb-0728-4569-b594-a5445513e80d)

### Additional context

- Browser: Chrome latest version
- Operating System: UBuntu 24.04

**Comment by Virat-Gupta** [comment]
I think its bcz of x.com and not twitter.com
