### ISSUE TITLE
[BUG] - Incorrect Test Case - 152. Maximum Product

### ISSUE THREAD

**Issue by yearn-for-wlb** [LeetCode-Feedback/LeetCode-Feedback#22908]
### LeetCode Username

user2762Pr

### Problem Number, Title, and Link

152. Maximum Product Subarray https://leetcode.com/problems/maximum-product-subarray

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

There was a new test case added:
`nums = [0,10,10,10,10,10,10,10,10,10,-10,10,10,10,10,10,10,10,10,10,0]`
, which made the editorial in Java fail to pass. However, the test case does not conform to the last constraint in the problem statement:
> The product of any **prefix** or **suffix** of nums is guaranteed to fit in a 32-bit integer.

### Language Used for Code

Java

### Code used for Submit/Run operation

```bash
class Solution {
    public int maxProduct(int[] nums) {
        if (nums.length == 0) return 0;

        int max_so_far = nums[0];
        int min_so_far = nums[0];
        int result = max_so_far;

        for (int i = 1; i < nums.length; i++) {
            int curr = nums[i];
            int temp_max = Math.max(
                curr,
                Math.max(max_so_far * curr, min_so_far * curr)
            );
            min_so_far = Math.min(
                curr,
                Math.min(max_so_far * curr, min_so_far * curr)
            );

            max_so_far = temp_max;

            result = Math.max(max_so_far, result);
        }

        return result;
    }
}
```

### Expected behavior

There is no expected behavior as the test case is not supposed to appear.

**Comment by luciphania** [comment]
Hello there,

Thanks for reaching out!

While the given test case still satisfied the original constraints, the constraints have been updated such that any subarray product now fits inside 32-bit integer now.

Best,
LeetCode Support Team
