### ISSUE TITLE
787. K 站中转内最便宜的航班--------------请求添加测试用例

### ISSUE THREAD

**Issue by YRMKYM** [LeetCode-Feedback/LeetCode-Feedback#22915]
### LeetCode 用户名

萤火

### 问题号码、标题和链接

https://leetcode.cn/problems/cheapest-flights-within-k-stops/

### Bug Category

缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*

### 描述

有问题的代码能AC

### 你使用的语言

Java

### 你提交或者运行的代码

```bash
class Solution {
    public int findCheapestPrice(int n, int[][] flights, int src, int dst, int k) {
        int[] minDist = new int[n];//存储每个节点到源节点的最短距离
        Arrays.fill(minDist, Integer.MAX_VALUE);
        // 起始点到自身的距离为0
        minDist[src] = 0;
        // 对所有边 松弛 k + 1 次
        for(int i = 0; i < k + 1; i++){
            // 每一次松弛，都是对所有边进行松弛
            int [] tmp = minDist.clone();
            for(int j = 0; j < flights.length; j++){
                int s1 = flights[j][0];
                int e1 = flights[j][1];
                int v1 = flights[j][2];
                // 松弛操作
                if(tmp[s1] != Integer.MAX_VALUE && minDist[s1] + v1 < minDist[e1]){
                    minDist[e1] = tmp[s1] + v1;
                }
            }
        }
        // 不能到达终点
        if (Integer.MAX_VALUE == minDist[dst]) {
            return -1;
        } else {
            return minDist[dst];
        }
    }
}
```

### 期望行为

添加测试用例：
n = 4
flights = [[0,3,8],[0,1,1],[0,2,5],[1,2,1],[2,3,5]]
src =0
dst =3
k =1
预期结果 8

### 屏幕截图

此代码不应该AC，请检查
class Solution {
    public int findCheapestPrice(int n, int[][] flights, int src, int dst, int k) {
        int[] minDist = new int[n];//存储每个节点到源节点的最短距离
        Arrays.fill(minDist, Integer.MAX_VALUE);
        // 起始点到自身的距离为0
        minDist[src] = 0;
        // 对所有边 松弛 k + 1 次
        for(int i = 0; i < k + 1; i++){
            // 每一次松弛，都是对所有边进行松弛
            int [] tmp = minDist.clone();
            for(int j = 0; j < flights.length; j++){
                int s1 = flights[j][0];
                int e1 = flights[j][1];
                int v1 = flights[j][2];
                // 松弛操作
                if(tmp[s1] != Integer.MAX_VALUE && minDist[s1] + v1 < minDist[e1]){
                    minDist[e1] = tmp[s1] + v1;
                }
            }
        }
        // 不能到达终点
        if (Integer.MAX_VALUE == minDist[dst]) {
            return -1;
        } else {
            return minDist[dst];
        }
    }
}

### 额外的上下文

无

**Comment by amcones-lc** [comment]
Please check out this feedback

**Comment by YRMKYM** [comment]
谢谢，已收到！

**Comment by amcones-lc** [comment]
你好，当前该题已添加测试用例， 请留言告知一下力扣中文网站的 ID，我们给予积分奖励。

**Comment by YRMKYM** [comment]
![Screenshot_20240815_124029_com lingkou leetcode](https://github.com/user-attachments/assets/1f137751-e698-48e2-9d87-8a2197ae434b)

**Comment by amcones-lc** [comment]
你好，当前该题已添加测试用例，奖励已发放。
