### ISSUE TITLE
[BUG] - <缺陷标题>

### ISSUE THREAD

**Issue by aric-gb** [LeetCode-Feedback/LeetCode-Feedback#22930]
### LeetCode 用户名

心无旁骛

### 问题号码、标题和链接

https://leetcode.cn/problems/search-insert-position/

### Bug Category

问题限制

### 描述

。。。

### 你使用的语言

C++

### 你提交或者运行的代码

```bash
class Solution {
public:
    int searchInsert(vector<int>& nums, int target) 
    {
        int n=nums.size();
        int left=0;
        int right=n-1;
        while(left<=right)
        {
            int mid=(left+right)/2;
            if(nums[mid]<target)
            {
                left=mid+1;
            }
            else
            {
                right=mid-1;
            }
        }
        return left;
    }
};
```

### 期望行为

速度快一点

### 屏幕截图

阿斯顿撒

### 额外的上下文

撒旦撒

**Comment by amcones-lc** [comment]
感谢反馈，经核实该题目题解及测试用例暂无异常，力扣会不断努力给大家带来更好的学习社区！后续刷题学习中遇到问题，可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
