### ISSUE TITLE
[BUG] - "134. Gas Station" wrong test case

### ISSUE THREAD

**Issue by thiel-ph** [LeetCode-Feedback/LeetCode-Feedback#22947]
### LeetCode Username

thiel_p

### Problem Number, Title, and Link

134. Gas Station https://leetcode.com/problems/gas-station/

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

The problem specified that there is a unique solution to each test case.

But in the last test case:

`gas = [2,0,0,0,0,0,0,0,0,...]`
`cost = [0,1,0,0,0,0,0,0,0,...]`

You can start at the first position, as well as any of the 0-0 positions and still finish the circuit.

### Language Used for Code

Python/Python3

### Code used for Submit/Run operation

```bash
class Solution:
    def canCompleteCircuit(self, gas, cost) -> int:
        n = len(gas)
        if n == 1:
            if cost[0] > gas[0]:
                return -1
            return 0

        for idx in range(n):
            if gas[idx] >= cost[idx]:
                break 

        gaps = []
        ends = []
        cur_gap = 0
        while True:
            if gas[idx%n] < cost[idx%n]:
                cur_gap += 1
            else:
                if cur_gap > 0:
                    gaps.append(cur_gap)
                    cur_gap = 0
                    ends.append(idx%n)
                if idx >= len(cost):
                    break
            idx += 1

        for start in ends:
            tank = 0
            for i in range(n):
                idx = start + i
                tank += gas[idx%n]
                if tank < cost[idx%n]:
                    break
                if i == n-1:
                    return start
                tank -= cost[idx%n]
        return -1
```

### Expected behavior

The test case should be modified in a way that only 1 correct solution is available instead of many.

**Comment by goatfryed** [comment]
This test case is probably introduced to fail brute force algorithms, but it's really annoying

**Comment by johnmave126** [comment]
To add to the ticket, the test case
```
gas = [2, 0]
cost = [2, 0]
```
is rejected as invalid for having multiple solutions.

But the rejection shows that it is possible to move from one station to another with an empty tank. Hence there is no hidden requirement that the car can only move with non-empty tank.

**Comment by duc-ph** [comment]
Thank you for acknowledging the issue. My Leetcode username is `thiel_p`.
Cheers!
