### ISSUE TITLE
使用github账号无法登陆 使用github账号第三方登录无法登陆，需手机验证码，但手机号已不用，收不了验证码

### ISSUE THREAD

**Issue by qiuge369** [LeetCode-Feedback/LeetCode-Feedback#22943]
### LeetCode 用户名

2561595393@qq.com

### 问题号码、标题和链接

1

### Bug Category

问题描述

### 描述

使用github账号无法登陆 使用github账号第三方登录无法登陆，需手机验证码,目前手机号码已废弃，无法收到验证码

### 你使用的语言

None

### 期望行为

修改手机号码：15289733679修改为19989770963
新手机号码下的账户可以删掉

### 额外的上下文

需要解绑的手机号：15289733679
绑定手机号对应的力扣账号：2561595393@qq.com
常用登录地址：（省市）武汉
常用登录设备系统：windows
常用登录浏览器：edge

**Comment by liyuzhu-lc** [comment]
您好，需要您查收一下邮箱哦！
