### ISSUE TITLE
[BUG] - <缺陷标题>

### ISSUE THREAD

**Issue by ZhangBowen** [LeetCode-Feedback/LeetCode-Feedback#22949]
### LeetCode 用户名

Berwyn Zhang

### 问题号码、标题和链接

面试题 16.19. Pond Sizes LCCI, https://leetcode.cn/problems/pond-sizes-lcci/

### Bug Category

问题描述

### 描述

英文版描述丢失了对答案从小到大排序的要求

### 你使用的语言

Python/Python3

### 期望行为

把这个要求加上和中文版对齐

**Comment by amcones-lc** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by ZhangBowen** [comment]
> 你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

个性域名是：
leetcode.cn/u/berwyn/

**Comment by amcones-lc** [comment]
你好，当前该题已添加测试用例，奖励已发放。
