### ISSUE TITLE
[BUG] - No audio in videos under Graph card

### ISSUE THREAD

**Issue by udayckumar** [LeetCode-Feedback/LeetCode-Feedback#22960]
### LeetCode Username

rab_rakhha

### Problem Number, Title, and Link

https://leetcode.com/explore/learn/card/graph/618/disjoint-set/3881/

### Bug Category

Editorial

### Bug Description

I don't find audio in any of the videos available at https://leetcode.com/explore/learn/card/graph/618/disjoint-set/3881/

 Is this intentional? If it is, where can I find these vidoes with audio.

### Language Used for Code

None

### Expected behavior

Video should have audio as well.

**Comment by udayckumar** [comment]
I am now getting audio with videos on this card. Keeping this issue open for monitoring.

**Comment by udayckumar** [comment]
I am now getting audio with videos on this card. Keeping this issue open for monitoring.

**Comment by gokul656** [comment]
Hi, I'm facing the same issue with same problem. Does the attachment has audio in it ?
