### ISSUE TITLE
[BUG]  issue description is ambiguous (题目有歧义)

### ISSUE THREAD

**Issue by AbelTomas** [LeetCode-Feedback/LeetCode-Feedback#22961]
### LeetCode 用户名

bo-mu-m

### 问题号码、标题和链接

https://leetcode.cn/problems/binary-tree-right-side-view/

### Bug Category

问题描述

### 描述

题目描述不清晰。应该写是每一层的最右节点。
可以通过新的测试用例来解决该问题。

### 你使用的语言

Java

### 期望行为

 加入新的测试用例
 如下
 [1,2,null,3,4,5]
 
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/159259718/c0b20388-d97b-4e98-aab6-35624c8ec8f4)

**Comment by amcones-lc** [comment]
感谢反馈，经核实该题目题解及测试用例暂无异常，力扣会不断努力给大家带来更好的学习社区！后续刷题学习中遇到问题，可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
