### ISSUE TITLE
Incomplete codes getting passed in the problem 166.FIND PEAK ELEMENT

### ISSUE THREAD

**Issue by itsiftikar02** [LeetCode-Feedback/LeetCode-Feedback#22988]
### LeetCode Username

itsiftikar02

### Problem Number, Title, and Link

https://leetcode.com/problems/find-peak-element/description/

### Bug Category

Problem description, Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

So in this problem statement there is nowhere mentioned that same elements cant occur together,so they can occur together. In that case the solutions submitted(including my solution should not get passed). An example testcase I am writting below:
nums={3,4,5,6,7,7,7,7,7,7,7,7,7,7,7,7,8,10,9}
the output of the code should be 17,but the output of my code is -1 and it is still getting accepted.
So i think the problem statement should be changed,as the problem more emphasizes on binary search instead of adding the additional testcase.

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
class Solution {
public:
    int findPeakElement(vector<int>& nums) {
        if(nums.size()==1)
        return 0;
        if(nums[0]>nums[1])
        return 0;
        if(nums[nums.size()-1]>nums[nums.size()-2])
        return nums.size()-1;
        int l=1,r=nums.size()-2;
        while(l<=r){
            int mid=(l+r)>>1;
            if(nums[mid]>nums[mid-1]&&nums[mid]>nums[mid+1])
            return mid;
            else if(nums[mid]>nums[mid-1])
            l=mid+1;
            else
            r=mid-1;
        }
        return -1;
    }
};
```

### Expected behavior

nums={3,4,5,6,7,7,7,7,7,7,7,7,7,7,7,7,8,10,9}
the output of the code should be 17,but the output of my code is -1 and it is still getting accepted.

**Comment by stormsunshine** [comment]
Can you check the constraints? It is required that there are no adjacent elements that are equal.
