### ISSUE TITLE
[BUG] - wrong test case for 523. Continuous Subarray Sum

### ISSUE THREAD

**Issue by Jenzd** [LeetCode-Feedback/LeetCode-Feedback#22984]
### LeetCode Username

zhendai1

### Problem Number, Title, and Link

523. Continuous Subarray Sum https://leetcode.com/problems/continuous-subarray-sum/description/

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

the test case output for [5,0 ,0 ,0, 0], k=3 is True, when it should be False

### Language Used for Code

Python/Python3

### Code used for Submit/Run operation

```bash
# note that the solution seems to be wrong. e.g. it returns true for [5, 0, 0, 0] and k = 3
class Solution:
    def checkSubarraySum(self, nums: List[int], k: int) -> bool:
        # basic idea: in the cumulative sum array, if cum_sum[j] % k = cum_sum[i] % k
        # (and i > j), then sum(nums[j+1:i]) is divisible by k 

        prefix_mod = 0
        mod_seen = {0: -1} # always return True if there is some cum sum already divisible by k

        for i in range(len(nums)):
            if nums[i] == 0:
                continue
            prefix_mod = (prefix_mod + nums[i]) % k
            if prefix_mod in mod_seen:
                if i - mod_seen[prefix_mod] > 1:
                    return True
            else:
                mod_seen[prefix_mod] = i
        return False
```

### Expected behavior

should return False, as there are no subarray sum that adds up to a multiple of 3

**Comment by stormsunshine** [comment]
There exist several subarrays with sum 0. 0 is always a multiple of any integer k. Is there any problem?

**Comment by Jenzd** [comment]
my bad. didn't think through the special case with 0
