### ISSUE TITLE
[BUG] - 144.二叉树的前序遍历 - Swift语言的编译问题

### ISSUE THREAD

**Issue by KafuChino123** [LeetCode-Feedback/LeetCode-Feedback#22990]
### LeetCode 用户名

raspberry-x

### 问题号码、标题和链接

144. 二叉树的前序遍历 https://leetcode.cn/problems/binary-tree-preorder-traversal/description/

### Bug Category

不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*

### 描述

在提交第一份代码（在下面列出的代码中表示为Solution1）时，点击运行后提示“编译出错”（Unknown preprocess compile error），而这份代码可以在Xcode中正常运行，且可以根据测试用例跑出正确的结果。
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/118886923/c0d28867-62aa-4cea-a74b-5eebab91920a)

接下来，我使用第二份代码提交（在下面的代码中表示为Solution2），成功运行并正确解答。
<img width="875" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/118886923/88fb6fce-f875-4a6a-a552-baaadbec0058">

两份代码的思路相同，唯一的区别是变量result的声明位置——Solution 1在函数内，而Solution 2在类体内，作用域和生命周期不尽相同。但我认为在这里放函数里理应没有任何影响，但是提交却出现了“未知的编译错误”。

### 你使用的语言

Swift

### 你提交或者运行的代码

```bash
class Solution1 {
    func preorderTraversal(_ root: TreeNode?) -> [Int] {
        var result = [Int]()
        preOrder(root: root, result: &result)
        return result
    }
        
    func preOrder(root: TreeNode?, result: inout [Int]) {
        guard let root = root else {
            return
        }
        result.append(root.val)
        preOrder(root: root.left, result: &result)
        preOrder(root: root.right, result: &result)
    }
}

class Solution2 {
    var result = [Int]()
    func preorderTraversal(_ root: TreeNode?) -> [Int] {
        preOrder(root: root, result: &result)
        return result
    }
    
    func preOrder(root: TreeNode?, result: inout [Int]) {
        guard let root = root else {
            return
        }
        preOrder(root: root.left, result: &result)
        result.append(root.val)
        preOrder(root: root.right, result: &result)
    }
}
```

### 期望行为

期望修复未知的错误编译的问题。如果不是LeetCode编译的问题而是代码本身的问题，希望给出一个解释或说明。

### 屏幕截图

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/118886923/c0d28867-62aa-4cea-a74b-5eebab91920a)

<img width="875" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/118886923/88fb6fce-f875-4a6a-a552-baaadbec0058">

**Comment by amcones-lc** [comment]
Please check out this feedback
