### ISSUE TITLE
[BUG] - One of the Test cases is wrong

### ISSUE THREAD

**Issue by Someone-tensai** [LeetCode-Feedback/LeetCode-Feedback#22999]
### LeetCode Username

paudelsulav5

### Problem Number, Title, and Link

2582. Pass the Pillow https://leetcode.com/problems/pass-the-pillow/description/?envType=daily-question&envId=2024-07-06

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

One of the test cases has the wrong expected output.

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
class Solution {
public:
    int passThePillow(int n, int time) {

        int initial_time = 0, pos;
        for (int i = 1; i <= 2 * n; i++) {
            if (initial_time == time) {
                pos = i;
                break;
            }
            initial_time++;
        }
        if (pos <= n)
            return pos;
        return pos % n;
    }
};
```

### Expected behavior

The output should have been 2 but its 6 for some reason.

### Screenshots

![Screenshot 2024-07-06 151839](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/151622439/3dabb869-4e7c-4119-9f2b-6c979e700b5b)

**Comment by OmAmar106** [comment]
@Someone-tensai  

It should be 6 only 
Since the pattern will be 

1->2->3->4->5->6->7->8->7->6

After 1, it took 9 seconds to reach 6 , therefore 6.

**Comment by Someone-tensai** [comment]
> @Someone-tensai
> 
> It should be 6 only Since the pattern will be
> 
> 1->2->3->4->5->6->7->8->7->6
> 
> After 1, it took 9 seconds to reach 6 , therefore 6.

@OmAmar106 Thank you for the correction. I should have looked at it more carefully before posting a bug report. I guess I got brain fog then. Sorry for the inconvenience, leetcode community.
