### ISSUE TITLE
[BUG] - Incorrect Test Case Added

### ISSUE THREAD

**Issue by csiitian** [LeetCode-Feedback/LeetCode-Feedback#22992]
### LeetCode Username

cs_iitian

### Problem Number, Title, and Link

152. Maximum Product Subarray https://leetcode.com/problems/maximum-product-subarray/description/

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

I have tried to run the editorial solution and found out that it's failing.
Either Editorial is in-correct or the Test Case is in-correct.
But later check the problem description and saw that the product will never exceed the 32 bit Integer, so why we have this test case in the system.

**Test Case:** [0,10,10,10,10,10,10,10,10,10,-10,10,10,10,10,10,10,10,10,10,0]

### Language Used for Code

Java

### Code used for Submit/Run operation

```bash
class Solution {
    public int maxProduct(int[] nums) {
        if (nums.length == 0) return 0;

        int max_so_far = nums[0];
        int min_so_far = nums[0];
        int result = max_so_far;

        for (int i = 1; i < nums.length; i++) {
            int curr = nums[i];
            int temp_max = Math.max(
                curr,
                Math.max(max_so_far * curr, min_so_far * curr)
            );
            min_so_far = Math.min(
                curr,
                Math.min(max_so_far * curr, min_so_far * curr)
            );

            max_so_far = temp_max;

            result = Math.max(max_so_far, result);
        }

        return result;
    }
}
```

### Expected behavior

**Expected Output:** 1000000000
**Actual Output**
<img width="949" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/98081274/5d8d1f1a-1885-4ae6-86fe-43936d75d64a">

**Comment by csiitian** [comment]
In that case, Approach 2 mentioned in the Editorial Solution will give wrong answer for this Test Case, So please remove the solution immediately.

**Comment by luciphania** [comment]
Hello there,

Thanks for reaching out!

While the given test case still satisfied the original constraints, the constraints have been updated such that any subarray product now fits inside 32-bit integer now.

Best,
LeetCode Support Team
