### ISSUE TITLE
[BUG] - Missing test case - 3213. Construct String with Minimum Cost

### ISSUE THREAD

**Issue by Ethan-ZYF** [LeetCode-Feedback/LeetCode-Feedback#23005]
### LeetCode Username

Ethan-ZYF

### Problem Number, Title, and Link

https://leetcode.com/problems/construct-string-with-minimum-cost/description/

### Bug Category

Incorrect or missing "Related Topics"

### Bug Description

Missing test case (Incorrect/Inefficient Code getting accepted because of missing test cases)
An accepted code failed (Time Limit Exceeded) on this test case: 
[hack3213map.txt](https://github.com/user-attachments/files/16118169/hack3213map.txt)

### Language Used for Code

Python/Python3

### Code used for Submit/Run operation

```bash
class Solution:
    def minimumCost(self, target: str, words: List[str], costs: List[int]) -> int:
        n = len(target)
        dp = [float('inf')] * (n + 1)
        dp[0] = 0  # Cost of forming empty string is zero
        
        # Use a dictionary to map each word to its minimum cost
        word_cost = {}
        for word, cost in zip(words, costs):
            if word in word_cost:
                word_cost[word] = min(word_cost[word], cost)
            else:
                word_cost[word] = cost

        for i in range(1, n + 1):
            for word, cost in word_cost.items():
                if i >= len(word) and target[i-len(word):i] == word:
                    dp[i] = min(dp[i], dp[i-len(word)] + cost)
        
        return dp[n] if dp[n] != float('inf') else -1
```

### Expected behavior

Time Limit Exceeded

### Screenshots

<img width="1007" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/90292101/b705901d-db3a-458d-8db8-07d1fd8823bd">

**Comment by luciphania** [comment]
Hello,

Your reported issue has been relayed to our team for thorough investigation. We appreciate your patience as we work to address and resolve this matter. We will reach out to you when we have updates regarding the issue.

If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by luciphania** [comment]
Thank you for your time.

Your feedback has been used to enhance the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
