### ISSUE TITLE
[BUG] - 405周赛 hack 测试用例

### ISSUE THREAD

**Issue by 819020415** [LeetCode-Feedback/LeetCode-Feedback#23008]
### LeetCode 用户名

man-ray

### 问题号码、标题和链接

https://leetcode.cn/contest/weekly-contest-405/

### Bug Category

缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*

### 描述

一个测试用例，能 hack 掉大量 ac 的代码
[Uploading test.txt…]()

### 你使用的语言

None

### 期望行为

添加此测试用例

**Comment by 819020415** [comment]
[test.txt](https://github.com/user-attachments/files/16118225/test.txt)

**Comment by amcones-lc** [comment]
感谢反馈，能否向我们补充无法通过此测试用例的代码信息，把信息提供完整才能有助于快速验证和精准的定位，谢谢。
