### ISSUE TITLE
[BUG] - <O(N^2) Solutions Passed>

### ISSUE THREAD

**Issue by HarshilPatel-2602** [LeetCode-Feedback/LeetCode-Feedback#23009]
### LeetCode Username

Harshil_2602

### Problem Number, Title, and Link

3213.Construct String with Minimum Cost https://leetcode.com/problems/construct-string-with-minimum-cost/

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

Solution was accepted, but fails (TLE) linked testcase.

https://gist.github.com/yumkam/23982f858332b6b92bde351e822e361c/raw/96e76ab8638679eb316a0432d5e95793d10e6675/3213-testcase.txt

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
class Solution {
public:
    struct trie{
        map<char, trie*> next;
        int cost;
        trie(){
            cost = INT_MAX;
        }
    };

    void insert(trie * root, string s, int cost){
        for(auto ch : s){
            if(! root->next[ch])
                root->next[ch] = new trie();
            root = root->next[ch];
        }
        // root->end = true;
        root->cost = min(cost, root->cost);
    }
    
    int minimumCost(string target, vector<string>& words, vector<int>& costs) {
        trie *root = new trie();
        int n = costs.size();
        
        vector<long long> dp(target.size() + 1, INT_MAX);
        dp[target.size()] = 0;
        for(int i=0; i<n; i++){
            insert(root, words[i], costs[i]);
        }
        for(int i = target.size()-1; i>=0; i--){
            long long ans = INT_MAX;
            trie * temp = root;
            for(int j = i ; j < target.size() && temp ; j++){
                
                temp = temp->next[target[j]];
                if(temp && temp->cost != INT_MAX){
                    ans = min(ans, temp->cost + dp[j+1]);
                }
            }
            dp[i] = ans;
        }

        return dp[0] >= INT_MAX ? -1: dp[0];
    }
};
```

### Expected behavior

Code should be rejected.

### Screenshots

<img width="1713" alt="Screenshot 2024-07-07 at 11 01 56 AM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/97555299/c9e0eb6b-3873-4fa6-920e-54936bc76a20">

### TestCase Generator :  Code is in Python 

#!/usr/bin/env python3
max_len = int(5e4) 
target = ""
for _ in range(max_len):
    target += 'a'
words = [target]
costs = [1]
print(f"Input: target = \"{target}\", words = [\"{words[0]}\"], costs = [{costs[0]}]")
print("Output: 1")

**Comment by luciphania** [comment]
Hello,
 
Your reported issue has been relayed to our team for thorough investigation. We appreciate your patience as we work to address and resolve this matter. We will reach out to you when we have updates regarding the issue.
 
If you have any further questions or concerns in the meantime, please feel free to let us know.
 
Best regards,
LeetCode Support Team

**Comment by luciphania** [comment]
Thank you for your time.

Your feedback has been used to enhance the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
