### ISSUE TITLE
[BUG] - Missing test case - 3213. Construct String with Minimum Cost

### ISSUE THREAD

**Issue by EndlessCheng** [LeetCode-Feedback/LeetCode-Feedback#23004]
### LeetCode Username

endlesscheng

### Problem Number, Title, and Link

3213. Construct String with Minimum Cost https://leetcode.com/problems/construct-string-with-minimum-cost/description/

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

An accepted code failed (Time Limit Exceeded) on this test case:
[hack-3213.txt](https://github.com/user-attachments/files/16118125/hack-3213.txt)

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
class Solution {
    struct node{
        int cst;
        unordered_map <char, node*> nxt;
        node(): cst(1e9) {}
    };
public:
    int minimumCost(string target, vector<string>& words, vector<int>& costs) {
        node* t = new node();
        for (int i = 0; i < words.size(); ++i){
            string s = words[i];
            node* cur = t;
            for (auto &c: s){
                if (cur->nxt.find(c) == cur->nxt.end()){
                    cur->nxt[c] = new node();
                }
                cur = cur->nxt[c];
            }
            cur->cst = min(cur->cst, costs[i]);
        }
        int n = target.size();
        vector <int> dp(n, 1e9);
        for (int i = 0; i < n; ++i){
            node* cur = t;
            for (int j = i; j < n; ++j){
                if (cur->nxt.find(target[j]) == cur->nxt.end()){
                    break;
                }
                cur = cur->nxt[target[j]];
                dp[j] = min(dp[j], (i ? dp[i - 1] : 0) + cur->cst);
            }
        }
        return dp.back() == 1e9 ? -1 : dp.back();
    }
};
```

### Expected behavior

Time Limit Exceeded

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/7086966/159a76b5-5fdf-4222-a265-533c8c665fb7)

**Comment by luciphania** [comment]
Hello,

Your reported issue has been relayed to our team for thorough investigation. We appreciate your patience as we work to address and resolve this matter. We will reach out to you when we have updates regarding the issue.

If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by EndlessCheng** [comment]
Another hack case: [hack-3213-bin.txt](https://github.com/user-attachments/files/16128304/hack-3213-bin.txt)

**Comment by luciphania** [comment]
Thank you for your time.

Your feedback has been used to enhance the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
