### ISSUE TITLE
[BUG] - Missing Testcase in Weekly contest 405 Problem D.

### ISSUE THREAD

**Issue by NiloyDas19** [LeetCode-Feedback/LeetCode-Feedback#23013]
### LeetCode Username

Niloy_Das_19

### Problem Number, Title, and Link

3213. Construct String With Minimum Cost    https://leetcode.com/contest/weekly-contest-405/problems/construct-string-with-minimum-cost/

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

Actually, there is a missing test case. According to the constraints, some code should give a TLE (Time Limit Exceeded) error because it is not optimized. However, due to the absence of this test case, the code is being accepted.

Here target.length  = 50000
words.length = 6250
Sum(words[i].length) = 50000
costs.length = 50000

Which meets all constraints 

Here is the test case which is missing.
[missing_input.txt](https://github.com/user-attachments/files/16118696/missing_input.txt)

### Language Used for Code

Python/Python3

### Code used for Submit/Run operation

```bash
from typing import List

class Solution:
    def minimumCost(self, target: str, words: List[str], costs: List[int]) -> int:
        tar = len(target)
        num = len(words)
        dp = [float('inf')] * (tar + 1)
        dp[0] = 0
        co = {}
        for i, word in enumerate(words):
            if word in co:
                co[word] = min(co[word], costs[i])
            else:
                co[word] = costs[i]
        for i in range(1, tar + 1):
            for word in co:
                le = len(word)
                if i >= le:
                    if target[i - le:i] == word:
                        dp[i] = min(dp[i], dp[i - le] + co[word])
                    else:
                        dp[i] = dp[i]
                else:
                    dp[i] = dp[i]
        return dp[tar] if dp[tar] != float('inf') else -1
```

### Expected behavior

This code should result in a TLE (Time Limit Exceeded) error. However, it doesn't because of the missing test cases. I have already added the missing test case in the previous section.

### Screenshots

You can see in the screenshot when we add missing test case it gives TLE.
![Capture](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/86280394/f4dbb8c3-a2fc-4863-8e6b-841e09c89421)

### Additional context

Please add the missing test case.

**Comment by NiloyDas19** [comment]
Mistake costs.length = 6250

**Comment by luciphania** [comment]
Hello,

Your reported issue has been relayed to our team for thorough investigation. We appreciate your patience as we work to address and resolve this matter. We will reach out to you when we have updates regarding the issue.

If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by luciphania** [comment]
Thank you for your time.

Your feedback has been used to enhance the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
