### ISSUE TITLE
[BUG] - 412. Fizz Buzz

### ISSUE THREAD

**Issue by hemanthsubbiah** [LeetCode-Feedback/LeetCode-Feedback#23038]
### LeetCode Username

graphitesin

### Problem Number, Title, and Link

https://leetcode.com/explore/learn/card/the-leetcode-beginners-guide/692/challenge-problems/4424/

### Bug Category

Problem description

### Bug Description

Shouldn't the Space Complexity be O(n) ? The video says it's O(1). 

### Language Used for Code

None

### Expected behavior

We are clearly allocating memory depending on the size of input array. So space complexity should be O(n)

### Screenshots

<img width="861" alt="Screenshot 2024-07-08 at 7 50 07 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/172299261/546947d3-889e-47b2-b92d-e4ea7739a551">

**Comment by serp-ya** [comment]
Supporting this issue. The author said a few times: "We do not create new data structures proportionally to input". But we give a number `n` and CREATE a new data structure `Array(n)`
