### ISSUE TITLE
[BUG] - <测试用例通过，但是实际结果与预期结果不符>

### ISSUE THREAD

**Issue by DWyzj** [LeetCode-Feedback/LeetCode-Feedback#23047]
### LeetCode 用户名

HdreamYang

### 问题号码、标题和链接

https://leetcode.cn/problems/wiggle-subsequence/

### Bug Category

不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*

### 描述

测试用例结果与预期不符，但是测试通过

### 你使用的语言

Java

### 你提交或者运行的代码

```bash
class Solution {
    public int wiggleMaxLength(int[] nums) {

        if(nums.length == 1) return 1;
        
        // 当前差值
        int curDiff = 0;
        // 上一个差值
        int preDiff = 0;
        int count = 1;

        for(int i =1; i < nums.length; i ++){
            
            // 得到当前差值
            curDiff = nums[i] - nums[i-1];
            // 如果当前差值和上一个差值为一正一负
            // 等于0的情况表示初始时的prediff
            if((curDiff > 0 && preDiff <= 0) || (curDiff < 0 && preDiff >= 0)){
                count++;
                preDiff = curDiff;
            }

        }
        return count;

    }
}
```

### 期望行为

测试用例`[1,4,3,4,3,2,2,3,2]`
预期结果为`5`
实际结果为`7`

### 屏幕截图

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/56720665/6266f0df-b190-4225-91ff-9dacdbb68666)

**Comment by amcones-lc** [comment]
您好，在与相关团队核实后：***不处理***（`1 4 3 4 2 3 2`）。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
