### ISSUE TITLE
[BUG] - Missing test case in 3213. Construct String with Minimum Cost

### ISSUE THREAD

**Issue by ghost** [LeetCode-Feedback/LeetCode-Feedback#23046]
### LeetCode Username

Z3ROsum

### Problem Number, Title, and Link

3213. Construct String with Minimum Cost: https://leetcode.com/problems/construct-string-with-minimum-cost/description/

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

A code got accepted but then got Time Limit Exceeded on this specific test case:
[testcase.txt](https://github.com/user-attachments/files/16139224/testcase.txt)

### Language Used for Code

Kotlin

### Code used for Submit/Run operation

```Kotlin
class Solution {
    class Trie {
        val child = Array<Trie?>(26) { null }
        var cost: Int = Int.MAX_VALUE
            set(value) {
                if (value < field) field = value
            }
        var wordExists: Boolean = false
    }
    fun minimumCost(target: String, words: Array<String>, costs: IntArray): Int {
        var root = Trie().apply { wordExists = true }
        for (i in words.indices) {
            var node = root
            for (char in words[i]) {
                var idx = char - 'a'
                if (node.child[idx] == null) node.child[idx] = Trie()
                node = node.child[idx]!!
            }
            node.cost = costs[i]
            node.wordExists = true
        }
        // Minimum cost to get to a certain character in the target
        var dp = IntArray(target.length + 1) { Int.MAX_VALUE }
        dp[0] = 0
        fun set(i: Int, value: Int) = run { if (i < dp.size) dp[i] = minOf(dp[i],value) else return@run }
        for (i in target.indices) {
            var node = root
            if (dp[i] == Int.MAX_VALUE) continue
            for (j in (i until target.length)) {
                node = node.child[target[j] - 'a'] ?: break
                if (node.wordExists) {
                    set(j + 1, node.cost + dp[i])
                }
            }
        }
        return if (dp.last() != Int.MAX_VALUE) dp.last() else -1
    }
}
```

### Expected behavior

The code was supposed to TLE

### Screenshots

<img width="1412" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/66195939/04982d85-b1f1-40bb-aa43-90f8df59e88c">

**Comment by luciphania** [comment]
Hello, 

Your reported issue has been relayed to our team for thorough investigation. We appreciate your patience as we work to address and resolve this matter. We will reach out to you when we have updates regarding the issue. 
If you have any further questions or concerns in the meantime, please feel free to let us know. 

Best regards, 
LeetCode Support Team

**Comment by qingy2019** [comment]
@luciphania any updates?
