### ISSUE TITLE
[BUG] - <缺陷标题>

### ISSUE THREAD

**Issue by SmallKang** [LeetCode-Feedback/LeetCode-Feedback#23067]
### LeetCode 用户名

小木匠

### 问题号码、标题和链接

88. 合并两个有序数组 https://leetcode.cn/problems/merge-sorted-array/description/?envType=study-plan-v2&envId=top-interview-150

### Bug Category

不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*

### 描述

有个用例“nums1 = [0], m = 0, nums2=[1], n=1”一直不过，但实际是可以的

### 你使用的语言

Python/Python3

### 期望行为

通过

### 屏幕截图

![20240710155807](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/22804362/30ac326c-8748-4e73-814d-f3667a41b493)

**Comment by amcones-lc** [comment]
感谢反馈，经核实该题目题解及测试用例暂无异常（合并后数组不应由函数返回，`return` 是无效的），力扣会不断努力给大家带来更好的学习社区！后续刷题学习中遇到问题，可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
