### ISSUE TITLE
[BUG] - <title>

### ISSUE THREAD

**Issue by CupcakePack** [LeetCode-Feedback/LeetCode-Feedback#23064]
### LeetCode Username

owji359

### Problem Number, Title, and Link

35. Search Insert Position https://leetcode.com/problems/search-insert-position/description/

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

In this problem, I had two different C++ submissions. One was a brute force linear scan solution, and the other was an optimised binary search solution. I expected that the optimised binary search solution would pass and the linear scan would TLE, as the problem description says "You must write an algorithm with O(log n) runtime complexity." However, the linear scan solution passed as well. The surprising part is that the brute force solution actually performs better than the optimised binary search. The binary search solution ran in 3ms and beat 71.25% of users. However, the brute force linear search ran in 0ms and beat 100.00% of users. I was shocked that the brute force even passed, let alone surpassed the optimised algorithm. So I suggest that larger and more extravagant testcases be added to ensure that only O(log n) solutions pass, like the problem mandates.

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
// optimised binary search solution
class Solution {
public:
    int searchInsert(vector<int>& nums, int target) {
        int l = 0;
        int r = nums.size() - 1;

        while (l <= r) {
            int mid = l + (r - l) / 2;
            if (nums[mid] == target)
                return mid;
            else if (nums[mid] > target)
                r = mid - 1;
            else
                l = mid + 1;
        }
        return l;
    }
};
// brute force linear search solution
class Solution {
public: 
    int searchInsert(vector<int>& nums, int target) {
        for (int i = 0; i < nums.size(); i++)
            if (nums[i] >= target)
                return i;
        return nums.size();
    }
};
```

### Expected behavior

I expected that the linear search solution would not pass but the binary search would. I certainly didn't expect the linear search solution to not only pass, but also BEAT the binary search solution, which was what happened.

### Screenshots

<img width="865" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/175171117/88624223-0cad-4b97-a8ea-c4e35d4fb4bd">
<img width="860" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/175171117/8852b352-121f-4b13-8f61-29bf2000dacd">

**Comment by Rakshitg600** [comment]
I understand that description mentions that the algorithm must be O(logN) but the constraints clearly mention that the length <=1e4. This means that algorithms with complexity better than O(N^2) would be acceptable.

**Comment by CupcakePack** [comment]
I still don't get why a brute force solution took 0ms while an optimised
binary search got 3ms
