### ISSUE TITLE
[BUG] - 152. Maximum Product Subarray

### ISSUE THREAD

**Issue by PreetiToppo** [LeetCode-Feedback/LeetCode-Feedback#23077]
### LeetCode Username

toppopreeti191

### Problem Number, Title, and Link

152. Maximum Product Subarray

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

Wrong Answer
190 / 191 testcases passed

Editorial
Input
nums =
[0,10,10,10,10,10,10,10,10,10,-10,10,10,10,10,10,10,10,10,10,0]

Use Testcase
Output
1981284352
Expected
1000000000

### Language Used for Code

None

### Code used for Submit/Run operation

```bash
class Solution {
    public int maxProduct(int[] nums) {
       int max = nums[0];
       int min = nums[0];
       int result = max;

       if(nums.length == 0){
        return 0;
       }

       for(int i=1;i<nums.length;i++){
        int curr = nums[i];
        int temp = Math.max(curr,Math.max(max*curr,min*curr));
        min = Math.min(curr,Math.min(max*curr,min*curr));
        max = temp;
        result = Math.max(result,max);
       }
       return result;
    }
}
```

### Expected behavior

Wrong Answer
190 / 191 testcases passed

Editorial
Input
nums =
[0,10,10,10,10,10,10,10,10,10,-10,10,10,10,10,10,10,10,10,10,0]

Use Testcase
Output
1981284352
Expected
1000000000

It is calculating wrong output for the above input.

**Comment by Bibin21** [comment]
Just use double for result and it will be solved . It occurs since u used int for storing the result
