### ISSUE TITLE
1304. 和为零的N个唯一整数 官方题解有问题并且缺少n=2的用例

### ISSUE THREAD

**Issue by shun16888** [LeetCode-Feedback/LeetCode-Feedback#2308]
**你的 LeetCode 用户名**
kingss

**Bug 类型**
- [ ] 题目
- [x] 题解
- [ ] 编程语言
- [x] 用例缺失

**描述**
描述你遇到的 bug
题目要求返回由n 个**各不相同**的整数组成的数组。官方题解对于n=2，返回[0,0]。提交可以通过，缺少n=2的用例。

**你使用的语言**
C++

**你提交或者运行的代码**
```
// Two Sum
class Solution {
public:
    vector<int> sumZero(int n) {
        vector<int> ans;
        int sum = 0;
        for (int i = 0; i < n - 1; ++i) {
            ans.push_back(i);
            sum += i;
        }
        ans.push_back(-sum);
        return ans;
    }
};

```

**期望行为**
加上n=2的用例。

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
@lc-kay 麻烦帮忙跟进下这个用户反馈哦。

**Comment by lc-kay** [comment]
@feiceh We've used this feedback to update the problem. Please reward the user.

**Comment by feiceh** [comment]
@shun16888 你好，当前题目用例已更新，ID：kingss 给予积分奖励，请查收。
