### ISSUE TITLE
[BUG] - Problem 53 solution accepted even when it is wrong

### ISSUE THREAD

**Issue by Garik098** [LeetCode-Feedback/LeetCode-Feedback#23086]
### LeetCode Username

shyam454

### Problem Number, Title, and Link

https://leetcode.com/problems/maximum-subarray/

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

class Solution:
    def maxSubArray(self, nums: List[int]) -> int:
        if not nums:
            return 0
    
        max_sum = nums[0]
        current_sum = nums[0]
        
        for i in range(1, len(nums)):
            current_sum = max(nums[i], current_sum + nums[i])
            max_sum = max(max_sum, current_sum)
        
        return max_sum

The above solution was accepted for the problem. However, if we take the input as [-2,1,-3,4], the right answer would be [4] and 4 right but the above code gives it as 5. 

### Language Used for Code

None

### Expected behavior

I am searching for the right answer

**Comment by stormsunshine** [comment]
The code is as follows.

```Python
class Solution:
    def maxSubArray(self, nums: List[int]) -> int:
        if not nums:
            return 0

        max_sum = nums[0]
        current_sum = nums[0]
    
        for i in range(1, len(nums)):
            current_sum = max(nums[i], current_sum + nums[i])
            max_sum = max(max_sum, current_sum)
    
        return max_sum
```

I have run the code for test case [-2,1,-3,4], and the code returns 4 as expected. How do you get the output 5?
