### ISSUE TITLE
[BUG] - Test case out of bound

### ISSUE THREAD

**Issue by pranjalchanda08** [LeetCode-Feedback/LeetCode-Feedback#23080]
### LeetCode Username

pchanda2410

### Problem Number, Title, and Link

https://leetcode.com/problems/maximum-product-subarray

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/40349163/755ab4ef-ac76-45c7-913c-ee33bf324e31)
As per the description the overall bound of multiplication is not out of 32 bits. But this test case fails the constrain.

### Language Used for Code

C

### Code used for Submit/Run operation

```bash
int maxProduct(int* nums, int numsSize) {
    if (numsSize == 0) return 0;

    int max_val = nums[0];
    int min_val = nums[0];
    int result = nums[0];

    for (int i = 1; i < numsSize; i++) {
        if (nums[i] < 0) {
            max_val ^= min_val;
            min_val ^= max_val;
            max_val ^= min_val;
        }

        max_val = fmax(nums[i], (max_val * nums[i]));
        min_val = fmin(nums[i], (min_val * nums[i]));

        result = fmax(result, max_val);
    }

    return result;
}
```

### Expected behavior

No runtime errors.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/40349163/033ac593-5a85-4f6e-b3a0-7dfb653f646b)

**Comment by pranjalchanda08** [comment]
The same logic is working on JAVA but not in C

**Comment by pranjalchanda08** [comment]
the only thing that helped is by changing the "int" to "long double"

**Comment by luciphania** [comment]
Hello there,

Thanks for reaching out!

While the given test case still satisfied the original constraints, the constraints have been updated such that any subarray product now fits inside 32-bit integer now.

Best,
LeetCode Support Team
