### ISSUE TITLE
[BUG] - <缺少start和end不对应的测试用例>

### ISSUE THREAD

**Issue by RobinOyang** [LeetCode-Feedback/LeetCode-Feedback#23095]
### LeetCode 用户名

robinoyang

### 问题号码、标题和链接

1661. 每台机器的进程平均运行时间 https://leetcode.cn/problems/average-time-of-process-per-machine/

### Bug Category

不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*

### 描述

存在start和end不对应但是数量一致，结果也能通过的状态。
增加测试用例
`| machine_id | process_id | activity_type | timestamp |
| ---------- | ---------- | ------------- | --------- |
| 0          | 0          | start         | 0.712     |
| 0          | 0          | end           | 1.52      |
| 0          | 1          | start         | 3.14      |
| 0          | 2          | end           | 4.12      |
| 1          | 0          | start         | 0.55      |
| 1          | 0          | end           | 1.55      |
| 1          | 1          | start         | 0.43      |
| 1          | 1          | end           | 1.42      |
| 2          | 0          | start         | 4.1       |
| 2          | 0          | end           | 4.512     |
| 2          | 1          | start         | 2.5       |
| 2          | 1          | end           | 5         |`

### 你使用的语言

MySQL

### 你提交或者运行的代码

```bash
# Write your MySQL query statement below
SELECT 
    machine_id, 
    ROUND(
        SUM(
            CASE 
                WHEN activity_type = 'end' THEN timestamp 
                ELSE -timestamp 
            END
        ) / COUNT(DISTINCT process_id), 3
    ) AS processing_time
FROM activity
GROUP BY machine_id;
```

### 期望行为

我运行的代码提交成功，但是实际上，有可能process_id记录的start和end不一致（或异常，或缺失）。

**Comment by amcones-lc** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by RobinOyang** [comment]
你好，我的域名是 leetcode.cn/u/robinoyang/


On Sep 11, 2024, at 20:16, LC-uli ***@***.***> wrote:



你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by amcones-lc** [comment]
你好，当前该题已添加测试用例，奖励已发放。
