### ISSUE TITLE
Missing Test Case - 162. Find Peak Element

### ISSUE THREAD

**Issue by Vinz1444** [LeetCode-Feedback/LeetCode-Feedback#2309]
#### Your LeetCode username

Vinz1444

#### Category of the bug
-[-] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Test case is missing - [1,2,6,9,2,4,5,3,1]

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@Vinz1444 Please provide the accepted solution that this test case failed on. Thank you.

**Comment by Vinz1444** [comment]
Below solution has been accepted and its failing for the above mentioned test case

public class Solution {
    public int FindPeakElement(int[] nums) {
        int l = 0;
        int r = nums.Length - 1;
        while (l <= r) {
            int mid = l + (r - l) / 2;
            if (mid + 1 < nums.Length && nums[mid] > nums[mid + 1])
                r = mid - 1;
            else if (mid + 1 < nums.Length)
                l = mid + 1;
            else break;
        }
        
        return l;
    }
}

**Comment by lc-kay** [comment]
@Vinz1444 The test case provided is accepted. Please note that your solution can return the index to any of the peaks. Thank you for your time!
