### ISSUE TITLE
Missing test case in problem "First Unique Number"

### ISSUE THREAD

**Issue by luizfls** [LeetCode-Feedback/LeetCode-Feedback#231]
**What kind of bug**
- [ ] problem
- [x] solution
- [ ] language

**Describe the bug**
In Day 28 of the April 30-day challenge (problem "First Unique Number"), I came up with a test case where my solution doesn't work, even though it was accepted.

**Language**
C++

**The code you submit/run [aka my (broken) solution]**
```
class FirstUnique {
public:
    FirstUnique(vector<int>& nums)
        : _nums(nums)
    {
        std::unordered_map<int, int> count;
        for(auto num : _nums)
            if(++count[num] == 2)
                _dupes.emplace(num);

        for(std::size_t i = 0; i < _nums.size(); ++i)
            if(_dupes.find(_nums[i]) == _dupes.end())
            {
                _uniques.emplace(_nums[i], i);
                _indices.emplace(i);
            }
    }
    
    int showFirstUnique() {
        return !_indices.empty() ? _nums[*_indices.begin()] : -1;
    }
    
    void add(int value) {
        if(auto it = _uniques.find(value); it != _uniques.end())
        {
            _indices.erase(it->second);
            _uniques.erase(it);
        }
        else if(_dupes.find(value) == _dupes.end())
        {
            _nums.emplace_back(value);
            auto newIndex = _nums.size() - 1;
            _uniques.emplace(value, newIndex);
            _indices.emplace(newIndex);
        }
    }

private:
    std::vector<int> _nums;
    std::unordered_set<int> _dupes;
    std::unordered_map<int, std::size_t> _uniques;
    std::set<std::size_t> _indices;
};
```

**Expected behavior**
I ran the following test case
```
["FirstUnique","add","add","showFirstUnique"]
[[[1]],[1],[1],[]]
```
My output: `[null,null,null,1]`
Expected output: `[null,null,null,-1]`
Thus, my solution should not have been accepted.

**Comment by CooperCooperCooper** [comment]
Hi @luizfls,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @luizfls,
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
