### ISSUE TITLE
Missing Test Case - 284. Peeking Iterator

### ISSUE THREAD

**Issue by larrygao2000** [LeetCode-Feedback/LeetCode-Feedback#2310]
#### Your LeetCode username
larrygao2000

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Apparently the test cases do not include negative case where next() or peek() is called after hasNext return false. In that case peek() and next() should throw exception to keep the same interface/behavior of the original iterator.

#### Code you used for Submit/Run operation

```
class PeekingIterator implements Iterator<Integer> {
    
    Iterator<Integer> it;
    Integer next;
	public PeekingIterator(Iterator<Integer> iterator) {
	    // initialize any member here.
        it = iterator;
        if(iterator.hasNext()){
            next = iterator.next();
        }
	    
	}
	
    // Returns the next element in the iteration without advancing the iterator.
	public Integer peek() {
        return next;
	}
	
	// hasNext() and next() should behave the same as in the Iterator interface.
	// Override them if needed.
	@Override
	public Integer next() {
	   Integer temp = next;
        if(it.hasNext()){
            next = (Integer)it.next();
        }
        else{
            next = null;
        }
        return temp;
	}
	
	@Override
	public boolean hasNext() {
	    return next != null;
	}
}
```

The above code will never throw exception and it has passed the test.

#### Language used for code

Java

#### Expected behavior

Need to add negative cases where next() and peek() is called when there is no more element so it will throw exception

**Comment by lc-kay** [comment]
@larrygao2000 To qualify for contribution rewards, please provide a test case that will fail this solution. Thank you!

**Comment by lc-kay** [comment]
Hi @larrygao2000 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
