### ISSUE TITLE
Missing Test Case - 659. Split Array into Consecutive Subsequences

### ISSUE THREAD

**Issue by architmahajan** [LeetCode-Feedback/LeetCode-Feedback#2311]
#### Category of the bug
- [659. Split Array into Consecutive Subsequences ] Question
- [ class Solution {
public:
    bool isPossible(vector<int>& nums) {
        queue <int> q;
        int i;
        int n = nums.size();
        vector<pair<int,int>> v;
        v.push_back({nums[0]-1,0});
        int c = 1, prev = nums[0];
        for(i = 1; i < nums.size(); i++)
        {
            if(prev == nums[i])
                c++;
            else if(prev+1 == nums[i])
            {
                v.push_back({prev,c});
                c = 1;
                prev = nums[i];
            }
        }
        v.push_back({prev,c});
        v.push_back({prev+1,0});
        int f = 0;
        for(i = 0; i < v.size()-1; i++)
        {
            if(v[i+1].second - v[i].second > 0)
            {
                c = v[i+1].second - v[i].second;
                while(c > 0)
                {
                    q.push(v[i+1].first);
                    c--;
                }
            }
            else if(v[i+1].second-v[i].second < 0)
            {
                cout << v[i].first << " " << q.front() << "\n";
                c = abs(v[i+1].second - v[i].second);
                //cout << c << "\n";
                while(c > 0)
                {
                    c--;
                    if(v[i].first >= q.front()+2)
                    {
                        q.pop();
                    }
                    else
                    {
                        f = 1;
                        break;
                    }
                }
                if(c > 0 || f == 1)
                    break;
            }
        }
        if(!q.empty())
            return false;
        return true;
    }
};] Solution
- [c++ ] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

![Screenshot from 2021-02-08 21-50-17](https://user-images.githubusercontent.com/25868965/107248098-fb8db800-6a57-11eb-9a7e-5e7986d1324c.png)

**Comment by lc-kay** [comment]
@architmahajan Please provide the submission details link to the accepted solution. Thank you!

**Comment by architmahajan** [comment]
This is the submission link.
https://leetcode.com/submissions/detail/453479045/

Thanks and Regards,
Archit

**Comment by lc-kay** [comment]
Hi @architmahajan 
Thank you! I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @architmahajan 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
