### ISSUE TITLE
TWO SUM

### ISSUE THREAD

**Issue by umer77jahangir** [LeetCode-Feedback/LeetCode-Feedback#23117]
### LeetCode 用户名

UMER JAHANGIR

### 问题号码、标题和链接

https://leetcode.com/problems/two-sum/submissions/1320516861/

### Bug Category

问题描述

### 描述

I found the indices of an array by summing the elements in the array.

### 你使用的语言

Java

### 你提交或者运行的代码

```bash
class Solution {
    public int[] twoSum(int[] nums, int target) {
   for(int i=0; i<nums.length; i++){
    for(int j=i+1; j<nums.length; j++){
    if(target==nums[i]+nums[j] ){
    return new int[]{i,j};
}
}
}
return new int[0];
}
}
```

### 期望行为

![Screenshot (54)](https://github.com/user-attachments/assets/2fe42b25-9ee1-4991-a38b-54a85ea4ffb3)

### 屏幕截图

![image](https://github.com/user-attachments/assets/e5fd22fb-f630-468c-84cb-6a4d86c38745)

**Comment by amcones-lc** [comment]
感谢反馈，经核实该题目题解及测试用例暂无异常，力扣会不断努力给大家带来更好的学习社区！后续刷题学习中遇到问题，可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
