### ISSUE TITLE
[BUG] - 2408. Design SQL: Insufficient logic getting accepted

### ISSUE THREAD

**Issue by maaniksingh92** [LeetCode-Feedback/LeetCode-Feedback#23114]
### LeetCode Username

maniksingh92

### Problem Number, Title, and Link

2408. Design SQL https://leetcode.com/problems/design-sql/

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

1. In languages that support variable length list data structures, the `columns` input can be completely ignored.
2. If you store table rows using a 2-D list data structure, the indices can act as the `rowId`.  This makes the explanation related to insertion using an auto-increment method pointless since nothing special needs to be done here. 
3. You can ignore the implementation of `deleteRow` and the test cases would still pass.

### Language Used for Code

Python/Python3

### Code used for Submit/Run operation

```bash
class Table:
    def __init__(self):
        self.rows = []
    
    def insert_row(self, row: list[str]) -> None:
        self.rows.append(row)
    
    def __getitem__(self, id: int) -> list[str]:
         return self.rows[id - 1]

class SQL:
    def __init__(self, names: List[str], columns: List[int]):
        self.tables = {name: Table() for name in names}

    def insertRow(self, name: str, row: List[str]) -> None:
        self.tables[name].insert_row(row)

    def deleteRow(self, name: str, rowId: int) -> None:
        pass

    def selectCell(self, name: str, rowId: int, columnId: int) -> str:
        return self.tables[name][rowId][columnId - 1]
```

### Expected behavior

I would expect some errors return values when:
1. A row insertion with mismatched column size is provided for a table.
2. A cell from a deleted row is accessed.

For testing that an auto-increment index method was implemented, there should be a new operation to fetch an entire table as a 2-D Matrix. This operation must run in O(1) time complexity.

**Comment by maniksingh92** [comment]
Sure, this is the only visible test case from the problem and should be sufficient:

1) `["SQL","insertRow","selectCell","insertRow","deleteRow","selectCell"]`
2) `[[["one","two","three"],[2,3,1]],["two",["first","second","third"]],["two",1,3],["two",["fourth","fifth","sixth"]],["two",1],["two",2,2]]`

Both of the above are inputs, where (1) would determine the operation to perform, and (2) would be the inputs for that operation.

**Comment by samantha-lc** [comment]
<img width="721" alt="DSQL1" src="https://github.com/user-attachments/assets/321cd4ad-b3bb-4404-a150-802bdd279219">
<img width="722" alt="DSQL2" src="https://github.com/user-attachments/assets/046dd5bc-2390-4273-9406-4d796a530fc3">
