### ISSUE TITLE
Incorrect starter code - 1656 (keyword used as variable name)

### ISSUE THREAD

**Issue by Anshuman04** [LeetCode-Feedback/LeetCode-Feedback#2312]
#### Your LeetCode username
agaharwar

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
For python starter code, a keyword has been used as a parameter name shadowing the actual keyword.
Parameter "id" must be changed to a different name.

#### Language used for code
python

#### Expected behavior
Renaming of parameter "id" is required

**Comment by lc-kay** [comment]
Hi @Anshuman04 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Anshuman04 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
