### ISSUE TITLE
Missing Test Case - 65. Valid Number

### ISSUE THREAD

**Issue by kosievdmerwe** [LeetCode-Feedback/LeetCode-Feedback#2313]
#### Your LeetCode username

kosievdmerwe

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

The problem is missing several test cases which would catch cheaty solutions using Python's `float()` function.

The problem is that `float()` allows for strings to indicate infinity (see the Expected Behaviour section for an extensive list), but the problem description doesn't.

#### Code you used for Submit/Run operation

This solution is based on various discussion thread answers:

```
class Solution:
    def isNumber(self, s: str) -> bool:
        try:
            float(s)
        except ValueError:
            return False
        return True
```

#### Language used for code

Python3

#### Expected behavior

I expected this solution to fail rather than succeed.

The following testcases all return true, whereas, the evaluator returns false:
```
"inf"
"-inf"
"+inf"
"Infinity"
"-Infinity"
"+Infinity"
```

Per the constraints we're allowed to use any letters (upper and lower case) so all the test cases above are "valid" possible inputs, but are invalid numbers per the problem statement.

#### Screenshots

![Screen Shot 2021-02-08 at 1 01 57 PM](https://user-images.githubusercontent.com/103258/107281414-7fbb4d80-6a0e-11eb-88b9-5fe6c49bc899.png)

#### Additional context

I don't know any other languages well enough to think about whether similar issues exist in them, but more cases like this might exist in other languages. In particular, "infinity" (lower case initial i) might work in some languages.

**Comment by kosievdmerwe** [comment]
As an aside, I'm not the first person to point this out. It does look like I am, however, the first person to write an issue on Github for this issue.

Here's a comment from 2018: https://leetcode.com/problems/valid-number/discuss/23739/Easy-Python-Solution-68-ms-beats-100/165259

**Comment by lc-kay** [comment]
Hi @kosievdmerwe 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @kosievdmerwe 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
