### ISSUE TITLE
[BUG] - Right Side Code Editor not visible

### ISSUE THREAD

**Issue by anishkumar127** [LeetCode-Feedback/LeetCode-Feedback#23134]
### LeetCode Username

anishkumar127

### Problem Number, Title, and Link

https://leetcode.com/problems/create-binary-tree-from-descriptions/description/?envType=daily-question&envId=2024-07-15

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

I have login and logout the leetcode but still not showing the code editor where we code. i have attached the screenshot what issue coming in console and network tab also for easy to understand for developer.
and one more thing this is not for specific question. it's happening with the all the questions code editor not visible.
it's working in incognito mode when my account not logged in. but with logged in account it's not working. my account is
[Anish Kumar](https://leetcode.com/u/anishkumar127/)

![image](https://github.com/user-attachments/assets/c3e9deb9-efaf-40af-b354-8ddb37c85e58)
![image](https://github.com/user-attachments/assets/c7008700-a13b-4755-86ea-660f67d583cc)
![image](https://github.com/user-attachments/assets/92553927-927f-4c07-b9ad-cd4b8d296840)
![image](https://github.com/user-attachments/assets/471d54da-2907-4572-858d-8fc8a48c84c1)
![image](https://github.com/user-attachments/assets/3a5a6e2d-8757-46eb-a4bd-066d844321a3)
![image](https://github.com/user-attachments/assets/05f4e096-cd98-4dda-838e-b0f5c5472b1f)
![image](https://github.com/user-attachments/assets/34f2da81-68c3-4b49-a3f1-a5e6c8de21af)

### Language Used for Code

Python/Python3

### Expected behavior

Should show the code editor but not visible.

### Screenshots

![image](https://github.com/user-attachments/assets/c3e9deb9-efaf-40af-b354-8ddb37c85e58)
![image](https://github.com/user-attachments/assets/c7008700-a13b-4755-86ea-660f67d583cc)
![image](https://github.com/user-attachments/assets/92553927-927f-4c07-b9ad-cd4b8d296840)
![image](https://github.com/user-attachments/assets/471d54da-2907-4572-858d-8fc8a48c84c1)
![image](https://github.com/user-attachments/assets/3a5a6e2d-8757-46eb-a4bd-066d844321a3)
![image](https://github.com/user-attachments/assets/05f4e096-cd98-4dda-838e-b0f5c5472b1f)
![image](https://github.com/user-attachments/assets/34f2da81-68c3-4b49-a3f1-a5e6c8de21af)

### Additional context

Please look into this if needed any more information please let me know. thanks :)

**Comment by Virat-Gupta** [comment]
Can confirm, facing same issue

**Comment by anishkumar127** [comment]
> Can confirm, facing same issue, it seems to be in all the questions.

you have the same issue ?

**Comment by luciphania** [comment]
Hello there,

Thanks for reaching out to us! I'm sorry to hear you're experiencing issues with LeetCode. To address this, please try the following troubleshooting steps and let us know if any resolve the issue:

Clear the browser cache. Instructions can be found [here](https://community.qlik.com/t5/Official-Support-Articles/How-to-Clear-All-Browser-Cache-or-for-specific-site/ta-p/1710298).
Access LeetCode without using any extensions (suggest using a new user profile).
Switch networks, such as using a mobile hotspot.
Clear the browser cookies and local storage.
Disable all browser extensions/plugins.
Use incognito/private browsing mode.
Try using a different browser like Safari or Firefox and inform us of the outcome.
Check and disable any active VPN or proxy servers connection.
Connect to a different Wi-Fi network (e.g., office/school network or mobile hotspot).
Try using a different device (e.g., another desktop/laptop, tablet, or mobile).

If these steps don't resolve the issue, we would appreciate further details for troubleshooting:

Provide the [console error log](https://help.mypurecloud.com/articles/gather-chrome-console-log/) and [network HAR log](https://help.mypurecloud.com/articles/gather-network-logs-from-chrome/) from when the issue occurs.
Device type and model (e.g., Samsung Galaxy P10, Steam Deck 512GB, iPad Pro 10, PC, MacBook Pro).
Your operating system (e.g., Windows, macOS, Linux).
Version of the operating system (e.g., Windows 10, macOS Catalina).
Browser type (e.g., Chrome, Firefox, Safari).
Browser version.
Any browser extensions or plugins installed.

Your cooperation is crucial for our development team to effectively diagnose and remedy this problem. Please don't hesitate to let us know if there's anything else we can do to assist.

Best,
LeetCode Support Team

**Comment by anishkumar127** [comment]
![image](https://github.com/user-attachments/assets/dd9e648f-f9e8-4109-bbf7-14aec993bf9b)
![image](https://github.com/user-attachments/assets/650205b7-2bc5-471a-b3c9-b132f57111a5)
i don't think so your instruction will be helpful in this case.

**Comment by anishkumar127** [comment]
[leetcode.com-1721041592927.log](https://github.com/user-attachments/files/16233532/leetcode.com-1721041592927.log)

**Comment by Virat-Gupta** [comment]
Ok so i resolved it by doing a empty cache and hard refresh.
![image](https://github.com/user-attachments/assets/9d8d9d09-c89d-4d89-b9a4-db56276592e0)
I was using edge btw.
