### ISSUE TITLE
Missing Test Case - 284. Peeking Iterator

### ISSUE THREAD

**Issue by NihalAgarwal** [LeetCode-Feedback/LeetCode-Feedback#2314]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Test Case missing, I submitted the wrong solution, and it passes all test cases and my solution got accepted, but fails (runtime error) for one of my generated test cases.

TestCase:
["PeekingIterator","next","peek","next","next","hasNext"]
[[],[],[],[],[],[]]
#### Code you used for Submit/Run operation

```
class PeekingIterator implements Iterator<Integer> {
    static class obj{
        int i = 0;
        boolean empty = true;
    }
    obj p;
    Iterator<Integer> iterator;
	public PeekingIterator(Iterator<Integer> iterator) {
	    p = new obj();
        this.iterator = iterator;
	}
	
	public Integer peek() {
        if( p.empty){
            if( iterator.hasNext() ) p.empty = false;
            return p.i = iterator.next();
        }
        return p.i;
	}
	
	@Override
	public Integer next() {
        if( !p.empty ){
            p.empty = true;
            return p.i;
        }
        return iterator.next();
	}
	
	@Override
	public boolean hasNext() {
	    return !p.empty || iterator.hasNext();
	}
}
```

#### Screenshots
![image](https://user-images.githubusercontent.com/46000505/107322312-3defdd00-6aca-11eb-8619-e083acf40440.png)

**Comment by lc-kay** [comment]
Hi @NihalAgarwal 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @NihalAgarwal 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
