### ISSUE TITLE
41.缺失的第一个正数 官方题解有误

### ISSUE THREAD

**Issue by heart-fresh** [LeetCode-Feedback/LeetCode-Feedback#23155]
### LeetCode 用户名

heart-fresh

### 问题号码、标题和链接

https://leetcode.cn/problems/first-missing-positive/solutions/304743/que-shi-de-di-yi-ge-zheng-shu-by-leetcode-solution/?envType=study-plan-v2&envId=top-100-liked

### Bug Category

力扣官方题解

### 描述

以题目中的示例二 [3, 4, -1, 1] 为例，恢复后的数组应当为 [1, -1, 3, 4]，我们就可以知道缺失的数为 2。

### 你使用的语言

None

### 期望行为

以题目中的示例二 [3, 4, -1, 1] 为例，恢复后的数组应当为 [-1, 1, 3, 4]，我们就可以知道缺失的数为 2。

**Comment by stormsunshine** [comment]
请问官方题解哪里有错误？哪份代码的这个测试用例运行结果不对？

**Comment by amcones-lc** [comment]
感谢反馈，经核实该题目题解及测试用例暂无异常，力扣会不断努力给大家带来更好的学习社区！后续刷题学习中遇到问题，可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
