### ISSUE TITLE
Missing Test Case - 1750. Minimum Length of String After Deleting Similar Ends

### ISSUE THREAD

**Issue by RakeshSeervi** [LeetCode-Feedback/LeetCode-Feedback#2315]
#### Your LeetCode username
RakeshSeervi

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
My incorrect solution is accepted.

#### Code you used for Submit/Run operation

```
class Solution {
    fun minimumLength(s: String): Int {
        var l = 0
        var r = s.length-1
        var c: Char
        
        while(r>l && s[l]==s[r]){
            c = s[l]
            
            while(s[l+1]==c && l+1<r)
                l+=1
            l+=1
            
            while(s[r-1]==c && r-1>l)
                r-=1
            r-=1
            
            if(r==l+1)
                return 0
        }
        
        return r-l+1
    }
}
```

#### Language used for code
Kotlin

#### Screenshots

![image](https://user-images.githubusercontent.com/40966318/107341071-8ddb9d80-6ae4-11eb-9c1e-0640f99134d3.png)

#### Additional Context
The missing test case is language independent.

**Comment by lc-kay** [comment]
Hi @RakeshSeervi 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @RakeshSeervi 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
