### ISSUE TITLE
[BUG] - <缺陷标题>

### ISSUE THREAD

**Issue by ChaoxuZhong** [LeetCode-Feedback/LeetCode-Feedback#23151]
### LeetCode 用户名

我是来刷题的

### 问题号码、标题和链接

744. 寻找比目标字母大的最小字母 https://leetcode.cn/problems/find-smallest-letter-greater-than-target/description/

### Bug Category

缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*

### 描述

在通过二分解决此问题的过程中，我想到一个优化点是如果已经查找到过比target大1的char后，再找到等于target时，中断while，可以直接返回该char了，但是我最开始的代码其实写错了返回的是letters[mid]，但是通过了全部用例，所以用例可以说是缺少了，虽然我觉得像我这样写的人极少，我只是想试试。

### 你使用的语言

Java

### 你提交或者运行的代码

```bash
public char nextGreatestLetter(char[] letters, char target) {
        int left = 0;
        int right = letters.length - 1;
        int mid;
        int lastGreaterThanTarget = 0;
        while(left <= right){
            mid = left + (right - right) / 2;
            if(letters[mid] == target && lastGreaterThanTarget != 0){
// 【BUG或者缺少用例】此处我想在找到了刚好比target大1的数后，再找到任何刚好等于target的char就直接返回，终止while，但是这里应该返回letters[lastGreaterThanTarget] 而不是letters[mid]
                return letters[mid];
            }else if(letters[mid] > target){
                lastGreaterThanTarget = mid;
                right = mid - 1;
            }else{
                left = mid + 1;
            }
        }
        return letters[lastGreaterThanTarget];
    }
```

### 期望行为

`solution.nextGreatestLetter(new char[]{'c','c','c','c','c','c','c','c','c','c','c','c','c','c',
            'd',
            'd','d','d','d','d','d','d','d','d','d','d','d','d','d'},'c')`
            此用例中，d刚好比c多一个，期望值结果明显是d，但是我的代码输出c同样通过了所有用例

**Comment by amcones-lc** [comment]
感谢反馈，经核实该题目题解及测试用例暂无异常（用户代码输出为 "d" 而不是 "c"），力扣会不断努力给大家带来更好的学习社区！后续刷题学习中遇到问题，可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
