### ISSUE TITLE
[BUG] - Missing test case - 3112. Minimum Time to Visit Disappearing Node

### ISSUE THREAD

**Issue by EndlessCheng** [LeetCode-Feedback/LeetCode-Feedback#23167]
### LeetCode Username

endlesscheng

### Problem Number, Title, and Link

3112. Minimum Time to Visit Disappearing Nodes https://leetcode.com/problems/minimum-time-to-visit-disappearing-nodes/

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

An accepted code failed (Time Limit Exceeded) on this test case:
[hack3112.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/15012324/hack3112.txt)

### Language Used for Code

Java

### Code used for Submit/Run operation

```bash
class Solution {
    public int[] minimumTime(int n, int[][] edges, int[] disappear) {
        List<List<int[]>> graph = new ArrayList<>();
        for (int i = 0; i < n; i++) {
            graph.add(new ArrayList<>());
        }
        for (int[] edge : edges) {
            graph.get(edge[0]).add(new int[]{edge[1], edge[2]});
            graph.get(edge[1]).add(new int[]{edge[0], edge[2]});
        }
        int[] time = new int[n];
        Arrays.fill(time, -1);
        time[0] = 0;
        Deque<int[]> heap = new ArrayDeque<>();
        heap.add(new int[]{0, 0});
        while (!heap.isEmpty()) {
            int[] tmp = heap.poll();
            int cur = tmp[0], t = tmp[1];
            if (t >= disappear[cur]) {
                continue;
            }
            if (time[cur] != -1 && t > time[cur]) {
                continue;
            }
            time[cur] = t;
            for (int[] nbh : graph.get(cur)) {
                int nt = t + nbh[1];
                if (nt >= disappear[nbh[0]]) {
                    continue;
                }
                if (time[nbh[0]] != -1 && time[nbh[0]] <= t + nbh[1]) {
                    continue;
                }

                time[nbh[0]] = nt;
                heap.add(new int[]{nbh[0], nt});
            }
        }
        return time;
    }
}
```

### Expected behavior

Time Limit Exceeded

### Screenshots

![image](https://github.com/user-attachments/assets/49b07289-2d47-4a13-b85d-05f9cf806a90)

**Comment by InhabitancyCocoon** [comment]
这是因为在特殊构造的图上，bellman ford with queue会退化到O(nm)？

**Comment by EndlessCheng** [comment]
> 这是因为在特殊构造的图上，bellman ford with queue会退化到O(nm)？

是的，比如网状结构。

**Comment by EndlessCheng** [comment]
> Epiphania_Ekenimoh commented: Hi there,
> 
> Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, please share the following information:
> 
> Please a valid test case you'd like to contribute
> 
> We appreciate your time and support. If you have any other questions, please let us know.
> 
> Best, LeetCode Support Team

Here is: [hack3112.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/15012324/hack3112.txt)
