### ISSUE TITLE
[BUG] - <官方解答文档错字 １５３０题>

### ISSUE THREAD

**Issue by ConeDragon** [LeetCode-Feedback/LeetCode-Feedback#23179]
### LeetCode 用户名

java-is-best-lang （LCUS）

### 问题号码、标题和链接

１５３０好叶子节点对的数量 https://leetcode.com/problems/number-of-good-leaf-nodes-pairs/editorial/

### Bug Category

力扣官方题解

### 描述

`current[11] += left[d1] + right[d2]`因该是乘法，但解答解释里写了加法。

在第二个解答《Post-Order Traversal：Algorithm》：

> - For all distance pairs `(d1, d2)`:
>     - If `2 + d1 + d2 <= distance`, then **`current[11] += left[d1] + right[d2]`**.

但是在解答里（C++第３６行、Java弟３７行、Python弟３１行），代码是`current[11] += left[d1] * right[d2]`。这是对的。

### 你使用的语言

Java

### 期望行为

因该显示：

- For all distance pairs `(d1, d2)`:
    - If `2 + d1 + d2 <= distance`, then **`current[11] += left[d1] * right[d2]`**.

### 屏幕截图

截屏：
![image](https://github.com/user-attachments/assets/5ce8234c-66c1-4d93-9b98-e6b45dffd303)

### 额外的上下文

https://leetcode.com/problems/number-of-good-leaf-nodes-pairs/editorial/

**Comment by amcones-lc** [comment]
Please check out the feedback
