### ISSUE TITLE
[BUG] - Submission length exceeds limit 

### ISSUE THREAD

**Issue by RashiDixit27** [LeetCode-Feedback/LeetCode-Feedback#23199]
### LeetCode Username

rashi27

### Problem Number, Title, and Link

https://leetcode.com/problems/number-of-atoms/

### Bug Category

Problem description - Submission errors

### Bug Description

While clicking on Analyze Complexity of  the problem i was encountering an unexpected error message: 
Submission length exceeds limit 

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
class Solution {
public:
    int getcnt(string str){
        if(str=="") return 1;
        int cnt=0;
        for(int i=0;i<str.length();i++)
        {
            cnt = cnt*10+(str[i]-'0');
        }
        return cnt;
    }
    string getstrcnt(int cnt){
        string str ="";
        if(cnt==1) return "";
        while(cnt)
        {
            str = ((char)(cnt%10 + '0'))+str;
            cnt /= 10;
        }
        return str;
    }
    
    string countOfAtoms(string formula) {
        stack<string> st;
        map<string,int> mp;
        for(int i=0;i<formula.size();i++)
        {
            if(formula[i]==')')
            {
                string str = "";
                string cnt = "";
                i++;
                while(i<formula.size() && formula[i]>='0' && formula[i]<='9')
                {
                    cnt+=formula[i];
                    i++;
                }
                i--;
                cout<<cnt;
                for(int j=0;j<getcnt(cnt);j++)
                    str += st.top(); 
                st.pop();
                if(!st.empty()) {
                    str = st.top()+str; 
                    st.pop();
                }    
                st.push(str);
            } else if(formula[i]=='(') 
            {
                st.push("");
            }
            else{
                string str = "";
                if(!st.empty()) {
                    str += st.top(); 
                    st.pop();
                }    
                str += formula[i]; 
                st.push(str);
            }
        }
        string str= st.top();
        for(int i=0;i<str.size();)
        {
            string a = "";
            a+=str[i++];
            string cnt ="";
            while(i<str.size() && str[i]>='a' && str[i]<='z')
                a+=str[i++];
            while(i<str.size() && str[i]>='0' && str[i]<='9')
                cnt+=str[i++];
            mp[a] += getcnt(cnt);
        }
        string res="";
        for(auto itr:mp)
            res+=(itr.first+getstrcnt(itr.second));
        return res;
    }
};
```

### Expected behavior

Expected behavior was to provide a proper time complexity

### Screenshots

<img width="1440" alt="Screenshot 2024-07-14 at 7 38 24 AM" src="https://github.com/user-attachments/assets/b6e9bff3-8590-4418-a822-96c4a112c3a3">

**Comment by eliseepstein** [comment]
I'm also experiencing this on the following problem: https://leetcode.com/problems/next-greater-element-iii/description/

**Comment by vritansh7** [comment]
I am facing the same issue for the following problems :
https://leetcode.com/problems/cheapest-flights-within-k-stops/description/
https://leetcode.com/problems/network-delay-time/description/

with respective submission URLs if that's helpful :
https://leetcode.com/problems/cheapest-flights-within-k-stops/submissions/1391233798/
https://leetcode.com/problems/network-delay-time/submissions/1391233471/

let me know if you need anything else like a trace-id or something to find the traces to find the issue

Thank you & regards

![Screenshot 2024-09-15 125919](https://github.com/user-attachments/assets/3c7f6f6a-1d33-45cd-9151-753395bcf8ef)

**Comment by Anshu1912** [comment]
https://leetcode.com/problems/design-circular-deque/submissions/1395671598/

same issue with this problem also.

**Comment by MahinSyeda99** [comment]
Any update on this thread? 
Facing the same issue for https://leetcode.com/problems/word-search-ii/

**Comment by restocle** [comment]
Also facing this issue for https://leetcode.com/problems/word-break-ii

**Comment by kayysean** [comment]
@Leetcode support Closing a bug without giving any explanation is a very disrespectful move on your part. 
While you have the right to fix it or not fix it , you shouldn't just close without comments. At least say "Sorry, we have higher priority issues. " bla bla.
People report issues when they see it (including me. I've seen this a few times myself) and we expect some kind of answer if not resolution for the bug. 
here is one other example : https://leetcode.com/problems/rearrange-string-k-distance-apart/submissions/1459581910/

**Comment by skylarw19** [comment]
Was this ever solved? Seems like this bug was closed without fixing it or providing an explanation?

I'm having the same issue for https://leetcode.com/problems/generate-parentheses/submissions/1463952987/

**Comment by vritansh7** [comment]
I am still facing the error for other leetcode questions as well

**Comment by ilyaivensky** [comment]
The same issue for https://leetcode.com/problems/brace-expansion-ii/submissions/1465577494/

**Comment by Darshan000234** [comment]
![Screenshot 2024-12-02 200229](https://github.com/user-attachments/assets/7ab2e9b9-882f-4bd2-ac4b-1ff796d0b7fe)
the same issue for https://leetcode.com/problems/add-two-numbers-ii/submissions/1468372252/

**Comment by arc-ch** [comment]
![image](https://github.com/user-attachments/assets/8a93e423-bf5c-49a2-935a-6d133f4114c4)
Same issue for https://leetcode.com/problems/course-schedule-ii

**Comment by vonrosen** [comment]
same issue
https://leetcode.com/problems/lfu-cache/submissions/1491921175/?envType=company&envId=salesforce&favoriteSlug=salesforce-thirty-days
![Screenshot 2024-12-29 at 2 13 23 PM](https://github.com/user-attachments/assets/4e6f0a71-f6b6-403f-9a47-0498986accad)

**Comment by Abhiram-kandiyana** [comment]
Same issue for Problem 339 (https://leetcode.com/problems/nested-list-weight-sum/)
![Screenshot 2025-01-01 at 2 54 35 PM](https://github.com/user-attachments/assets/e8025759-fec1-403c-987f-606c6dd31042)

**Comment by Kaufman386** [comment]
Same for Problem 46 (Permutations).

https://leetcode.com/problems/permutations/

![image](https://github.com/user-attachments/assets/b71c6740-1ccd-4311-a0ef-6230331eb67a)

**Comment by ovesh1623** [comment]
I am also facing the same problem.

**Comment by dadubanu** [comment]
Facing the same issue on multiple questions. I code in C so naturally solutions will be longer than those using python (cheaters :) )
