### ISSUE TITLE
1. 两数之和

### ISSUE THREAD

**Issue by Caesar-Victory** [LeetCode-Feedback/LeetCode-Feedback#23197]
### LeetCode 用户名

surpassmath

### 问题号码、标题和链接

https://leetcode.cn/problems/two-sum/description/

### Bug Category

问题描述

### 描述

中文翻译为: 但是，数组中同一个元素在答案里不能重复出现。
此处存在歧义，既可以指给定的数组nums，也可以指作为答案的数组
英文原文为：并且，你不能两次使用相同的元素两次

### 你使用的语言

Python/Python3

### 你提交或者运行的代码

```bash
None
```

### 期望行为

将翻译为改为直译的结果or数组修改为【答案数组】

### 屏幕截图

None

### 额外的上下文

None

**Comment by amcones-lc** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by Caesar-Victory** [comment]
> 你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

https://leetcode.cn/u/surpassmath/

**Comment by amcones-lc** [comment]
你好，当前该题已添加测试用例，奖励已发放。
