### ISSUE TITLE
[BUG] - <测试用例补充>

### ISSUE THREAD

**Issue by graduatehan** [LeetCode-Feedback/LeetCode-Feedback#23206]
### LeetCode 用户名

hanxu27.mail@qq.com

### 问题号码、标题和链接

1186. 删除一次得到子数组最大和  https://leetcode.cn/problems/maximum-subarray-sum-with-one-deletion/

### Bug Category

缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*

### 描述

不正确的代码仍然可以Accepted， 可以添加测试用例避免： [-1,-2]

### 你使用的语言

Java

### 你提交或者运行的代码

```bash
class Solution {
   public int maximumSum(int[] arr) {
        int dp0 = arr[0], dp1 = 0, res = Math.max(dp0, dp1);
        for(int i = 1; i < arr.length; i++){
            dp1 = Math.max(dp0, dp1 + arr[i]);
            dp0 = Math.max(dp0, 0)+ arr[i];
            res = Math.max(res, Math.max(dp0, dp1));        
        }
        return res > 0 ? res : dp0;
    }
}
```

### 期望行为

添加测试用例： [-1,-2]， 避免上述不正确代码Accepted

### 屏幕截图

![image](https://github.com/user-attachments/assets/e3707305-cd4b-4c15-a777-fe4f3dfdf709)

**Comment by amcones-lc** [comment]
Please check out the feedback

**Comment by amcones-lc** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。
