### ISSUE TITLE
Code editor of leetcode is not working

### ISSUE THREAD

**Issue by aniketkhatawkar** [LeetCode-Feedback/LeetCode-Feedback#23204]
### LeetCode Username

akashmule

### Problem Number, Title, and Link

For all problems

### Bug Category

Editorial

### Bug Description

When it open the any problem on leetcode, code editor of leetcode is not responding for all problems

### Language Used for Code

Java

### Expected behavior

code editor must be work properly

### Screenshots

![leetcode glitch](https://github.com/user-attachments/assets/6e9d8957-c574-408f-a6f7-82992248b9ae)

### Additional context

please can see this bug

**Comment by Ganesh5440** [comment]
Revert to older version

**Comment by chetanchauhan715** [comment]
same problem with my editor , today

**Comment by JupiterPanda** [comment]
+, same problem, found it 19/07/2024. Tried to reconnect, used vpn, cleared cache, used another account. Just doesn't work (((

**Comment by kirazoro** [comment]
hey ,if anyone found the solution to this problem ....please respond

**Comment by Ganesh5440** [comment]
> hey ,if anyone found the solution to this problem ....please respond

turn off beta testing and revert to old version

**Comment by Vaishalinreddy** [comment]
no nothing working if anyone found the solution please let me know

**Comment by aniketkhatawkar** [comment]
Revert to old version
