### ISSUE TITLE
Missing Test Case -- 167 - Two Sum II - Input array is sorted

### ISSUE THREAD

**Issue by abhi031098** [LeetCode-Feedback/LeetCode-Feedback#2321]
#### Your LeetCode username

abhi_u_03

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language

#### Description of the bug

**TestCase:**
[-1,-1,-1,0]
-1

Output
[3,4]
Expected
[1,4]

The question mentions "You may assume that each input would have exactly one solution and you may not use the same element twice". Hence, the leetcode compiler only takes the first two repeating indexes and not any other. Since the approach is used in Two Sum(LeetCode question No 1) many Leetcode coders will be using the same approach. Hence such test cases will more likely be missed for many users. However, in the Map approach, it can only store the recent index hence the **last two indexes** would be returned as an answer as compared to what is expected(**the first two indexes**). 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<int> twoSum(vector<int>& nums, int target) {
        vector<int> result;
        unordered_map<int,int> um;
        for(int i=0;i<nums.size();i++)
        {
            um[nums[i]]=i+1;
        }
        
        for(int i=0;i<nums.size();i++)
        {
            if(um.count(target-nums[i]))
            {
                if(target-nums[i]==nums[i])
                {
                result.push_back(um[nums[i]]-1);
                result.push_back(um[nums[i]]);
                }
                else
                {
                    result.push_back(um[nums[i]]);
                    result.push_back(um[target-nums[i]]);
                }
                
                return result;
            }
        }
        return result;
    }
};

```

#### Language used for code

C++

#### Expected behavior

**TestCase:**
[-1,-1,-1,0]
-1

Output
[3,4]
Expected
[1,4]

The question mentions "You may assume that each input would have exactly one solution and you may not use the same element twice". Hence, the leetcode compiler only takes the first two repeating indexes and not any other. Since the approach is used in Two Sum(LeetCode question No 1) many Leetcode coders will be using the same approach. Hence such test cases will more likely be missed for many users. However, in the Map approach, it can only store the recent index hence the **last two indexes** would be returned as an answer as compared to what is expected(**the first two indexes**). 

#### Screenshots

![image](https://user-images.githubusercontent.com/42272328/107394029-6e169a80-6b21-11eb-9fea-4320faba4f84.png)

**Comment by lc-kay** [comment]
Hi @abhi031098 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @abhi031098 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
