### ISSUE TITLE
Missing Test Case - 579. Find Cumulative Salary of an Employee

### ISSUE THREAD

**Issue by yangjing09** [LeetCode-Feedback/LeetCode-Feedback#2323]
#### Your LeetCode username
yangjing09

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
The solution returned 4 months' salary records for id=1 while the question asked for 3 months. 

#### Code you used for Submit/Run operation

```sql
select id, month, sum(Salary) over (partition by Id order by Month) as Salary
from 
(select * from 
 (select id, rank() over (partition by Id order by Month desc) rk, Month, Salary
from Employee) a
where rk >=2 and rk <= 4) b 
order by id, month desc 
```

#### Language used for code
MySQL

#### Expected behavior
The expected should be `{"headers": ["id", "Month", "Salary"], "values": [[1, 4, 130], [1, 3, 70], [1, 2, 30], [2, 1, 20], [3, 3, 100], [3, 2, 40]]}`.

#### Screenshots
![Screen Shot 2021-02-09 at 10 20 37 AM](https://user-images.githubusercontent.com/17013700/107408968-7f7b8a80-6ac0-11eb-9ea5-86af2597e71c.png)

**Comment by lc-kay** [comment]
@yangjing09 The expected output is correct. Please refer to the [discuss section](https://leetcode.com/problems/find-cumulative-salary-of-an-employee/discuss/?currentPage=1&orderBy=most_relevant&query=test%20case) of this problem for a better understanding of this test case. Thank you for your time.
