### ISSUE TITLE
33-Search in Rotated Sorted Array-Constraints are unclear

### ISSUE THREAD

**Issue by OverLordAct** [LeetCode-Feedback/LeetCode-Feedback#2324]
#### Your LeetCode username
dunkypie

#### Category of the bug
- [ ] Question: 33-Search in Rotated Sorted Array
- [ ] Solution: Yes
- [ ] Language: Java

#### Description of the bug
In the constraints, it is mentioned that the array will be rotated at some point, however how come a perfectly sorted sequence be sorted such as [1, 2, 3, 4]. I don't see how this array is rotated at such point. What is the pivot in such cases? 

#### Code you used for Submit/Run operation
```java
// Search in Rotated Sorted Array
class Solution {
    public int search(int[] nums, int target) {
        int length = nums.length;
        if (length == 1) return nums[0] == target ? 0 : -1;
        
        // First find pivot
        int left = 0, right = length - 1, pivot = -1;
        
        while (left < right) {
            int middle = left + (right - left) / 2;
            
            if (nums[middle] == target) return middle;
            if (nums[middle + 1] == target) return middle + 1;
            
            if (nums[middle] > nums[middle + 1]) {
                pivot = middle;
                break;
            } else if (nums[left] > nums[middle]) {
                right = middle;
            } else if (nums[right] < nums[middle]) {
                left = middle;
            } else {
                pivot = middle;
                break;
            }
        }
        
        if (target > nums[0]) {
            left = 0; right = pivot - 1;
        } else {
            left = pivot + 1; right = length - 1;
        }
        
        while (left <= right) {
            int middle = left + (right - left) / 2;
            
            if (nums[middle] == target) return middle;
            else if (nums[middle] > target) right = middle - 1;
            else left = middle + 1;
        }
        
        return -1;
    }
}
```

#### Language used for code
Java

#### Expected behavior
Either make the constraints clear that the array mayn't be rotated or that if not rotated what should the pivot be taken as.

**Comment by lc-kay** [comment]
Hi @OverLordAct 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @OverLordAct 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
