### ISSUE TITLE
[BUG] - javascript.json file 404

### ISSUE THREAD

**Issue by Muscardinus94** [LeetCode-Feedback/LeetCode-Feedback#23250]
### LeetCode Username

9028364

### Problem Number, Title, and Link

https://leetcode.com/problems/unique-paths-ii

### Bug Category

Editorial

### Bug Description

I Guess the Redirection for 
https://static-lccn.leetcode.com/monaco-tm/configurations/javascript.json
hits the wrong cache or maybe there is no such url for
https://assets.leetcode.com/monaco-tm/configurations/javascript.json
<img width="1132" alt="스크린샷 2024-07-24 오후 11 12 40" src="https://github.com/user-attachments/assets/0168af14-9ee5-4ad2-8d1b-f69d394f0236">

### Language Used for Code

JavaScript

### Expected behavior

should have the static json file for
https://assets.leetcode.com/monaco-tm/configurations/javascript.json

### Screenshots

<img width="1132" alt="스크린샷 2024-07-24 오후 11 13 35" src="https://github.com/user-attachments/assets/e8e3a5e6-db93-4993-8514-ab208f6b7532">
<img width="1132" alt="스크린샷 2024-07-24 오후 11 13 43" src="https://github.com/user-attachments/assets/ba53ea8d-2c67-4d4f-a484-fcc04021d967">

**Comment by IgnacioBecerra** [comment]
This is happening to me too, I'm surprised there's no other mention anywhere else.

**Comment by Muscardinus94** [comment]
Guess it's fixed now! thanx for the fix!
