### ISSUE TITLE
Missing Test Case - 586. Customer Placing the Largest Number of Orders

### ISSUE THREAD

**Issue by yangjing09** [LeetCode-Feedback/LeetCode-Feedback#2325]
#### Your LeetCode username
yangjing09

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
The input doesn't include all columns from the question. For example, column `order_date` is not included in the input. 

#### Code you used for Submit/Run operation

```sql
select customer_number
from 
(select customer_number, count(order_date) as number_of_order
from orders
 group by customer_number
order by number_of_order desc 
limit 1) a
```

#### Language used for code
MySQL

#### Expected behavior
The column `order_date`  is included in the input data. 

#### Screenshots
![Screen Shot 2021-02-09 at 11 40 24 AM](https://user-images.githubusercontent.com/17013700/107418698-d044b080-6acb-11eb-84d0-ae1bca4fcc7a.png)

**Comment by lc-kay** [comment]
Hi @yangjing09 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @yangjing09 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
