### ISSUE TITLE
[BUG] - JS and TS, No Syntax Highlighting or Autocompleting

### ISSUE THREAD

**Issue by BenCaro8** [LeetCode-Feedback/LeetCode-Feedback#23259]
### LeetCode Username

Fz0nNrXG4x

### Problem Number, Title, and Link

N/A

### Bug Category

Code Editor

### Bug Description

No syntax highlighting, auto indentation, or auto insertion of closing parenthesis and curly brackets. All together just acting like a text editor and not an IDE.

Bug category not applicable.

### Language Used for Code

JS and TS

### Expected behavior

Syntax highlighting, auto indentation, or auto insertion of closing parenthesis and curly brackets. 

### Screenshots

![bugg](https://github.com/user-attachments/assets/1eb48d75-5c1c-4f1f-bae3-2d0922dfeb13)

### Additional context
Using Firefox, tried seeing if using a private window would solve the issue with no luck. Just tested with Chrome as well and no beans.

**Comment by SevenHD** [comment]
Same here

**Comment by SevenHD** [comment]
> Same here



> ### LeetCode Username
> Fz0nNrXG4x
> 
> ### Problem Number, Title, and Link
> N/A
> 
> ### Bug Category
> Code Editor
> 
> ### Bug Description
> No syntax highlighting, auto indentation, or auto insertion of closing parenthesis and curly brackets. All together just acting like a text editor and not an IDE.
> 
> Bug category not applicable.
> 
> ### Language Used for Code
> None
> 
> ### Code used for Submit/Run operation
> _No response_
> 
> ### Expected behavior
> Syntax highlighting, auto indentation, or auto insertion of closing parenthesis and curly brackets.
> 
> ### Screenshots
> ![bugg](https://private-user-images.githubusercontent.com/76133585/351875144-1eb48d75-5c1c-4f1f-bae3-2d0922dfeb13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NjQ1NTQsIm5iZiI6MTcyMTg2NDI1NCwicGF0aCI6Ii83NjEzMzU4NS8zNTE4NzUxNDQtMWViNDhkNzUtNWMxYy00ZjFmLWJhZTMtMmQwOTIyZGZlYjEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDIzMzczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkNDg1OGJlMThjODlkOGU2YzhhN2E0MmY4MjZiNTZiNjYwNTg3OThiY2M5MWJkMjVmZTlkNmE3ODY3ODU1M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u74pEhnDGIhQtKvuGGqubgv83SjaA9w-CIaEEaOLQmM)
> 
> ### Additional context
> Using Firefox, tried seeing if using a private window would solve the issue with no luck. Just tested with Chrome as well and no beans.

Same here

**Comment by a90100** [comment]
Same here...

**Comment by danmatuszak** [comment]
same

**Comment by inferno080** [comment]
Yep this issue started today. Everything was fine yesterday.

**Comment by yashkathe** [comment]
same here

**Comment by a90100** [comment]
It is normal now.

<img width="469" alt="螢幕擷取畫面 2024-07-25 150412" src="https://github.com/user-attachments/assets/fedb11bd-ed7b-406b-92fe-0b8bbdbd430f">

**Comment by BenCaro8** [comment]
Seems good now 🤷🏽‍♂️
