### ISSUE TITLE
Missing Test Case - 284. Peeking Iterator

### ISSUE THREAD

**Issue by msaqib4203** [LeetCode-Feedback/LeetCode-Feedback#2326]
#### Your LeetCode username

msaqib4203

#### Category of the bug
- [x] Question
- [ ] Solution
- [x] Language

#### Description of the bug

The blueprint of the interface 'Iterator' mentioned in the code area is misleading for at least the C++ language.
As the blueprint provided states that the method next()  and hasNext() is private (default access).
However, they are public.

#### Code you used for Submit/Run operation

```
/*
 * Below is the interface for Iterator, which is already defined for you.
 * **DO NOT** modify the interface for Iterator.
 *
 *  class Iterator {
 *		struct Data;
 * 		Data* data;
 *		Iterator(const vector<int>& nums);
 * 		Iterator(const Iterator& iter);
 *
 * 		// Returns the next element in the iteration.
 *		int next();
 *
 *		// Returns true if the iteration has more elements.
 *		bool hasNext() const;
 *	};
 */

```

#### Language used for code

C++

#### Expected behavior

The blueprint of the interface 'Iterator' should list its method next() and hasNext() under 'public' access.

**Comment by lc-kay** [comment]
Hi @msaqib4203 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @msaqib4203 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
