### ISSUE TITLE
[BUG] - <title>

### ISSUE THREAD

**Issue by TanmayMishra4** [LeetCode-Feedback/LeetCode-Feedback#23284]
### LeetCode Username

TanmayMishra4

### Problem Number, Title, and Link

3228. Maximum Number of Operations to move ones to the End https://leetcode.com/problems/maximum-number-of-operations-to-move-ones-to-the-end/

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

The output for test case number 1 i.e 
Input: s = "1001101"
Output: 4
is wrong, The correct output should be 3.
Steps - 
1. by swapping '1' at index 4 and '0' at index 5, resultant string now 1001011
2. by swapping '1' at index 3 and '0' at index 4, resultant string now 1000111 
3. by swapping '1' at index 0 and '0' at index 3, resultant string now 0001111
These are only 3 steps and valid. Since moving a '1' from one position to another until we encounter another '1' or end of the string is considered as a single step and is also demonstrated by the solution given for the same example. This is the most optimal solution for this test case

### Language Used for Code

Java

### Code used for Submit/Run operation

```bash
class Solution {
    public void swap(char[] str, int a, int b){
        char t = str[a];
        str[a] = str[b];
        str[b] = t;
    }
    public int maxOperations(String s) {
        int endIndex = s.length()-1;
        while(endIndex >= 0 && s.charAt(endIndex) == '1') endIndex--;
        if(endIndex < 0) return 0;
        char[] str = s.toCharArray();
        int cur = endIndex;
        int res = 0;
        while(cur >= 0){
            if(str[cur] == '1'){
                // System.out.println("endIndex = "+endIndex + ", cur = "+cur);
                res++;
                swap(str, cur, endIndex);
                endIndex--;
                cur--;
            }
            else{
                cur--;
            }
        }
        return res;
    }
}
// 1001101
// 0001111
// 1 + 1 + 1
```

### Expected behavior

The output for test case number 1 i.e 
Input: s = "1001101"
Output: 4
is wrong, The correct output should be 3.
Steps - 
1. by swapping '1' at index 4 and '0' at index 5, resultant string now 1001011
2. by swapping '1' at index 3 and '0' at index 4, resultant string now 1000111 
3. by swapping '1' at index 0 and '0' at index 3, resultant string now 0001111
These are only 3 steps and valid. Since moving a '1' from one position to another until we encounter another '1' or end of the string is considered as a single step and is also demonstrated by the solution given for the same example. This is the most optimal solution for this test case

**Comment by code-scannner** [comment]
The question state to find the maximum number of operations that you can perform.
And that can be done by  swapping the left most ones first - 
Input: s = "1001101"
Output: 4
1. by swapping '1' at index 0 and '0' at index 2, resultant string now 0011101
2. by swapping '1' at index 4 and '0' at index 5, resultant string now 0011011
3. by swapping '1' at index 3 and '0' at index 2, resultant string now 0010111
4. by swapping '1' at index 2 and '0' at index 3, resultant string now 0001111
Hence the maximum you can perform is 4 steps.


Here is my Java Code using dp check it out.
``` java
class Solution {
    public int maxOperations(String s) {
        int dp[] = new int[s.length()];
        int oneIndex = s.length() - 1;
        for(int i = s.length() - 2; i>= 0; i--){
            if(s.charAt(i) == '1'){
               dp[i] = dp[oneIndex] + (s.charAt(i + 1) == '0' ? 1 : 0);
                oneIndex = i;
            }
        }

        int cnt = 0;
        for(int num : dp) cnt += num;
        return cnt;
    }
}

```
