### ISSUE TITLE
Missing Test Case - 1334. Find the City With the Smallest Number of Neighbors at a Threshold Distance

### ISSUE THREAD

**Issue by Mandiiiiiii** [LeetCode-Feedback/LeetCode-Feedback#2329]
#### Your LeetCode username

Mandiiiiiii

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Missing test cases: the wrong answer passing all test cases

#### Code you used for Submit/Run operation

code was from @blackspinner comment under 
https://leetcode.com/problems/find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance/discuss/490312/JavaC%2B%2BPython-Easy-Floyd-Algorithm

```
public int findTheCity(final int n, final int[][] edges, final int distanceThreshold) {
        final int[][] dist = new int[n][n];
        int min = Integer.MAX_VALUE; 
        int res = -1; 
        
        for (int[] row : dist) 
            Arrays.fill(row, 10000);
        
        for (final int[] edge : edges) 
            dist[edge[0]][edge[1]] = dist[edge[1]][edge[0]] = edge[2];
        
        for (int i = 0; i < n; i++) 
            dist[i][i] = 0;
        
        for (int k = 0; k < n; k++) 
            for (int i = 0; i < n; i++) 
                for (int j = 0; j < n; j++)
                    dist[i][j] = Math.min(dist[i][j], dist[i][k] + dist[k][j]);
        
       for (int i = 0; i < n; i++) {
            int sum = 0; 
            for (int j = 0; j < n; j++)
                if (dist[i][j] <= distanceThreshold)
                    sum++;
            if (sum <= min) {
                min = sum;
                res = i; 
            }
        }
        
        return res;
}
```

#### Language used for code

Java

#### Expected behavior

for test case: n = 5, edges = [[0,1,2],[0,4,8],[1,2,10000],[1,4,2],[2,3,10000],[3,4,1]], distanceThreshold = 10000
(costraint: 1 <= weighti, distanceThreshold <= 10^4)
![Untitled](https://user-images.githubusercontent.com/50033248/107450240-de540900-6b7f-11eb-94ee-e194cfce41cd.png)

after 1st for loop:
dist = 
[10000, 10000, 10000, 10000, 10000]
[10000, 10000, 10000, 10000, 10000]
[10000, 10000, 10000, 10000, 10000]
[10000, 10000, 10000, 10000, 10000]
[10000, 10000, 10000, 10000, 10000]

after 2nd for loop:
dist = 
[10000,         2, 10000, 10000,          8]
[        2, 10000, 10000, 10000,          2] 
[10000, 10000, 10000, 10000, 10000] 
[10000, 10000, 10000, 10000,          1]
[         8,         2, 10000,          1, 10000] 

after 3rd for loop:
dist = 
[        0,         2, 10000, 10000,          8]
[        2,         0, 10000, 10000,          2] 
[10000, 10000,         0, 10000, 10000] 
[10000, 10000, 10000,         0,          1]
[         8,         2, 10000,          1,         0] 

after 4th for loop:
dist = 
[        0,         2, 10000,          5,          4]
[        2,         0, 10000,          3,          2] 
[10000, 10000,         0, 10000, 10000] 
[         5,         3, 10000,         0,          1]
[         4,         2, 10000,          1,         0] 

Finally, the min would be 5 and res would be 4. 
As the array was initialized with all 10000, all cities are reachable to each other within the threshold at the end. But from the graph, we could see that city2 can only reach city1 and city3 within the threshold. So min should be 2 and res should be 2. This code actually is wrong, but it passes all current test cases.
<img width="1792" alt="Screen Shot 2021-02-10 at 9 18 57 AM" src="https://user-images.githubusercontent.com/50033248/107450845-06903780-6b81-11eb-81d1-5b262546e234.png">

#### Screenshots

<img width="888" alt="Screen Shot 2021-02-10 at 9 15 28 AM" src="https://user-images.githubusercontent.com/50033248/107450603-8b2e8600-6b80-11eb-9766-c858128855f6.png">

**Comment by lc-kay** [comment]
Hi @Mandiiiiiii 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Mandiiiiiii 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
