### ISSUE TITLE
278. First Bad Version

### ISSUE THREAD

**Issue by agatagruza** [LeetCode-Feedback/LeetCode-Feedback#233]
**What kind of the bug**
- [ ] problem
- [ ] solution
- [ ] language

**Describe the bug**
There is a type mismatch for return value. 

**what language is your code written in**
Python3

**The code you submit/run**

Returning type should be int as we are asked to implement a function that will find the first bad version (which is int). In the comment section we have `# @return a bool` but then later in the function definition we have `:rtype: int`.

**Expected behavior**
Change `# @return a bool` to `# @return an int`

**Screenshots**

**Additional context**

**Comment by CooperCooperCooper** [comment]
Hi @agatagruza ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @agatagruza ,
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.

**Comment by agatagruza** [comment]
Thank you @CooperCooperCooper for the update.
