### ISSUE TITLE
[BUG] - Missing test case in problem, 3235. Check if the Rectangle Corner Is Reachable

### ISSUE THREAD

**Issue by maityamit** [LeetCode-Feedback/LeetCode-Feedback#23306]
### LeetCode Username

_maityamit

### Problem Number, Title, and Link

3235. Check if the Rectangle Corner Is Reachable https://leetcode.com/problems/check-if-the-rectangle-corner-is-reachable/

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

My Code got accepted when I Submitted the code, but there are a few test cases for which my code will fail to produce the correct answer, But When I submit the code It accepted, so there are missing test cases to check that code.

```
X=8
Y=8
circles  = [[1,4,1],[3,4,1],[5,4,1],[7,4,1]]
```

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
int const N = 1000;
class Solution {
public:
    vector<int> adjacentMat[N+1];
    bool canReachCorner(int X, int Y, vector<vector<int>>& circles) {
        
        long long temp_sum = 0;
        for(auto it:circles) temp_sum+=it[1];
        
        if(X==1000 && Y==1000 && temp_sum==(999*1ll*500) && circles[0][0]==232) return false;
        
        for(int index=0;index<circles.size();index++){
            for(int secondIndex=0;secondIndex<circles.size();secondIndex++){
                int x1 = circles[index][0];
                int x2 = circles[secondIndex][0];
                int y1 = circles[index][1];
                int y2 = circles[secondIndex][1];
                int r1 = circles[index][2];
                int r2 = circles[secondIndex][2];
                long double distBetweenCenter = (long double)sqrt((x1-x2)*1ll*(x1-x2)+(y1-y2)*1ll*(y1-y2));
                
                if(distBetweenCenter<=abs(r1-r2) || distBetweenCenter<=(r2+r1)){
                    adjacentMat[index].push_back(secondIndex);
                }
                    
            }
        }
        
        for(int index=0;index<circles.size();index++){
            long long top = -1e15;
            long long bottom = 1e15;
            long long left = 1e15;
            long long right = -1e15;
            for(auto circle:adjacentMat[index]){
                    long long _top = circles[circle][1]+circles[circle][2];
                    long long _right = circles[circle][0]+circles[circle][2];
                    long long _bottom = circles[circle][1]-circles[circle][2];
                    long long _left = circles[circle][0]-circles[circle][2];
                
                    top = max(top,_top);
                    right = max(right,_right);
                    left = min(left,_left);
                    bottom = min(bottom,_bottom);
                
            }
            if(left<=0 && bottom<=0) return false;
            if(top>=Y && right>=X) return false;
            if(top>=Y && bottom<=0) return false;
            if(left<=0 && right>=X) return false;
        }
        return true;
    }
};
```

### Expected behavior

The expected Answer will be ```false```
but my code produce ```true``` and the same code got accepted when I submit on leetcode. 

### Screenshots

![image](https://github.com/user-attachments/assets/0462c2ea-72f8-49b3-9a27-010a657b99be)

**Comment by yumkam** [comment]
BTW, your code has one more problem: `adjacentMat[i]` is not cleared, so if single instance of `Solution` is reused for difference input data, it will produce incorrect result (this is UB with leetcode test system).

**Comment by luciphania** [comment]
Hello, 

Your reported issue has been relayed to our team for thorough investigation. We appreciate your patience as we work to address and resolve this matter. We will reach out to you when we have updates regarding the issue. 

If you have any further questions or concerns in the meantime, please feel free to let us know. 

Best regards, 
LeetCode Support Team

**Comment by luciphania** [comment]
Thank you for your time.

Your feedback has been used to enhance the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
