### ISSUE TITLE
[BUG] - Missing Test Case

### ISSUE THREAD

**Issue by jb240298** [LeetCode-Feedback/LeetCode-Feedback#23313]
### LeetCode Username

jb_2402

### Problem Number, Title, and Link

3235. Check if the Rectangle Corner Is Reachable https://leetcode.com/problems/check-if-the-rectangle-corner-is-reachable/description/

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

The solution gives the wrong answer for the below test case.

[TESTCASE]
X=5
Y=5
Circles=[[2,5,2], [5,2,2], [4,7,2], [7,4,2], [7,7,2]]

Correct output: true
Accepted output: false

<img width="419" alt="Screenshot 2024-07-28 at 4 22 57 PM" src="https://github.com/user-attachments/assets/3456232d-0f5c-4448-8384-fb2bd24ebb6d">

The circles are connected but outside the rectangle, hence there exists a path from the bottom-left corner to the top-right corner of the rectangle. The output should be true.

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
const int N = 1e3+1;

class Solution {
private:
    vector<int> graph[N];
    bool v[N];

    bool is_overlapping(vector<int>& a, vector<int>& b) {
        long long x_diff = abs(a[0] - b[0]);
        long long y_diff = abs(a[1] - b[1]);
        return (sqrt(((x_diff) * (x_diff)) + ((y_diff) * (y_diff))) <= ((long long)a[2]+b[2]));
    }

    void find_range(int idx, vector<vector<int>>& circles, 
        long long *l, long long *r, long long *t, long long *b) {
        if(v[idx]) return;
        v[idx] = true;
        *l = min(*l, (long long)circles[idx][0] - circles[idx][2]);
        *r = max(*r, (long long)circles[idx][0] + circles[idx][2]);
        *t = max(*t, (long long)circles[idx][1] + circles[idx][2]);
        *b = min(*b, (long long)circles[idx][1] - circles[idx][2]);
        for(const int& child : graph[idx]) {
            find_range(child, circles, l, r, t, b);
        }
    }
public:
    bool canReachCorner(int X, int Y, vector<vector<int>>& circles) {
        int n = circles.size();
        for(int i=0; i<n; i++) {
            graph[i].clear();
            v[i] = false;
        }

        for(int i=0; i<n; i++) {
            for(int j=i+1; j<n; j++) {
                if(is_overlapping(circles[i], circles[j])) {
                    graph[i].push_back(j);
                    graph[j].push_back(i);
                }
            }
        }

        for(int i=0; i<n; i++) {
            if(v[i]) continue;
            long long l = circles[i][0], r = circles[i][0], t = circles[i][1], b = circles[i][1];
            find_range(i, circles, &l, &r, &t, &b);
            // cout << i << ": " << l << " " << r << " " << t << " " << b << endl;
            if ((l<=0 && b<=0) || (l<=0 && r>=X) || (b<=0 && t>=Y) || (t>=Y && r>=X)) {
                return false;
            }
        }

        return true;
    }
};
```

### Expected behavior

For the below test-case, the output should be true.

[TESTCASE]
X=5
Y=5
Circles=[[2,5,2], [5,2,2], [4,7,2], [7,4,2], [7,7,2]]

But the program outputs false, and still got accepted.

### Screenshots

<img width="419" alt="Screenshot 2024-07-28 at 4 22 57 PM" src="https://github.com/user-attachments/assets/f274c2fb-cc65-4df7-a8bc-e29841e00461">

**Comment by luciphania** [comment]
Hello, 

Your reported issue has been relayed to our team for thorough investigation. We appreciate your patience as we work to address and resolve this matter. We will reach out to you when we have updates regarding the issue. 

If you have any further questions or concerns in the meantime, please feel free to let us know. 

Best regards, 
LeetCode Support Team

**Comment by luciphania** [comment]
Thank you for your time.

Your feedback has been used to enhance the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
