### ISSUE TITLE
Test case [0] failing- 124. Binary Tree Maximum Path Sum

### ISSUE THREAD

**Issue by kolapkardhaval** [LeetCode-Feedback/LeetCode-Feedback#2331]
#### Category of the bug
- [ ] Question

#### Description of the bug

Input [0] is failing when I click on submit but same input works for running that input.

#### Code you used for Submit/Run operation

```
object Solution {
    var res=Int.MinValue
    def maxPathSum(root: TreeNode): Int = {
      helper(root)
        res
    }
    
    def helper(root: TreeNode): Int = {
        if(root == null) return 0
        val l = helper(root.left)
        val r = helper(root.right)
        //what if current subtree is the max
        res = List(res,l+r+root.value).max
        //what if it is not and is just a part of the path
        return List(l+root.value,r+root.value,root.value).max
    }
}
```

#### Expected behavior

Should return 0 for input [0]

**Comment by lc-kay** [comment]
Hi @kolapkardhaval 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
