### ISSUE TITLE
Missing Test Case - 138. Copy List with Random Pointer

### ISSUE THREAD

**Issue by RakeshSeervi** [LeetCode-Feedback/LeetCode-Feedback#2332]
#### Your LeetCode username
RakeshSeervi

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language

#### Description of the bug
Just returning null in kotlin solves the question

#### Code you used for Submit/Run operation

```
class Solution {
    fun copyRandomList(node: Node?): Node? {
        return null
    }
}
```

#### Language used for code
Kotlin

#### Expected behavior
Solution should not have been accepted.

#### Screenshots

![image](https://user-images.githubusercontent.com/40966318/107496292-1dea1780-6bb7-11eb-8828-ccd243e523a9.png)

#### Additional context
This bug is kotlin specific I think.

**Comment by lc-kay** [comment]
Hi @RakeshSeervi 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @RakeshSeervi 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
