### ISSUE TITLE
Missing Test Case - 138. Copy List with Random Pointer

### ISSUE THREAD

**Issue by DivineEmperor** [LeetCode-Feedback/LeetCode-Feedback#2333]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@DivineEmperor Please provide the accepted solution and the custom test case it fails on. Thank you!

**Comment by lc-kay** [comment]
Hi @DivineEmperor 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
