### ISSUE TITLE
[BUG] - <191. 位1的个数 示例错误>

### ISSUE THREAD

**Issue by 121yguy** [LeetCode-Feedback/LeetCode-Feedback#23347]
### LeetCode 用户名

https://leetcode.cn/u/frosty-i2amangs4/

### 问题号码、标题和链接

191. 位1的个数 https://leetcode.cn/problems/number-of-1-bits/description/

### Bug Category

示例

### 描述

示例3给出的2147483645的二进制数是11111111111111111111111111111101(共32位)，而2147483645的二进制数是1111111111111111111111111111101(31位)

### 你使用的语言

None

### 期望行为

输入：n = 2147483645
输出：30
解释：输入的二进制串 11111111111111111111111111111101 中，共有 30 个设置位。
改为：
输入：n = 2147483645
输出：30
解释：输入的二进制串 1111111111111111111111111111101 中，共有 30 个设置位。

### 屏幕截图

<img width="538" alt="屏幕截图 2024-07-31 194337" src="https://github.com/user-attachments/assets/c0269375-9e9d-461d-bf7d-18a7f8d5c1c4">

**Comment by amcones-lc** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by 121yguy** [comment]
> 你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

leetcode.cn/u/frosty-i2amangs4/

**Comment by amcones-lc** [comment]
你好，当前该题已添加测试用例，奖励已发放。
