### ISSUE TITLE
1003. Check If Word Is Valid After Substitutions

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#2334]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution is accepted but fails on the following test case:

"abbcc"

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean isValid(String S) {
        Stack<Character> stack = new Stack<>();
        for (int i = 0; i < S.length(); i++) {
            char curr = S.charAt(i);
            if (curr == 'a') {
                stack.push(curr);
            } else if (stack.isEmpty()) {
                return false;
            } else if (curr == 'b') {
                if (stack.peek() == 'a') {
                    stack.pop();
                }
                stack.push(curr);
            } else if (curr == 'c') {
                if (stack.peek() == 'b') {
                    stack.pop();
                } else {
                    stack.push(curr);
                }
            }
        }
        
        return stack.isEmpty();
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/107511432-7ac3de80-6b73-11eb-9204-10efa09914cb.png)

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
