### ISSUE TITLE
Missing Test Case - 1485. Clone Binary Tree With Random Pointer

### ISSUE THREAD

**Issue by anall** [LeetCode-Feedback/LeetCode-Feedback#2335]
#### Your LeetCode username
anall

#### Category of the bug
- Solution

#### Description of the bug
You can cheat on the problem by using a simple typecast between `Node*` and `NodeCopy*`

#### Code you used for Submit/Run operation
```
class Solution {
public:
    NodeCopy* copyRandomBinaryTree(Node* root) {
        return (NodeCopy*)root;
    }
};
```

#### Language used for code
C++

#### Expected behavior
I expect the "Run Code" button to say "Wrong Answer". It says "Accepted".
I have not tried to submit this clearly incorrect cheating solution.

If the validator program is unable to check if I actually did a deep copy, possibly just rearrange the memory layout of NodeCopy* to prevent this type of cheating.

For future reference, is there a better way to report solution bugs that allow blatant cheating besides posting them publicly?

**Comment by lc-kay** [comment]
Hi @anall 
Thank you for reaching out to us. I've relayed this issue to our team to investigate. You can also reach out to us through our help desk or support@leetcode.com

**Comment by lc-kay** [comment]
@anall Although the solution provided is ok to pass on LeetCode, it will not work in a real interview. As changing the driver code to detect all types of cheating is costly, we highly recommend all users not to use this method. Thank you for understanding.
