### ISSUE TITLE
[BUG] - <特殊的测试用例未通过>

### ISSUE THREAD

**Issue by 1913789927** [LeetCode-Feedback/LeetCode-Feedback#23358]
### LeetCode 用户名

coding

### 问题号码、标题和链接

LCP 40.心算挑战 https://leetcode.cn/problems/uOAnQW/description/

### Bug Category

缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*

### 描述

提交通过的代码，新增自定义用例后结果异常，需要把测试用例添加到提交校验里
[1,2,3,4,6,8,10,12,39]
cnt = 3;

### 你使用的语言

C++

### 你提交或者运行的代码

```bash
class Solution {
public:
    int maxmiumScore(vector<int>& cards, int cnt) {
        int res = 0;
        int last1 = 0;
        int last2 = 0;
        sort(cards.begin(), cards.end());
        int i = cards.size() -1;
        for (; i + cnt + 1 > cards.size() ; i--) {
            res += cards[i];
            if (cards[i] % 2 == 1) {
                last1 = cards[i];
            } else {
                last2 = cards[i];
            }
        }

        if (res % 2 == 1) {
            while (i >= 0) {
                if (cards[i] % 2 == 0 && last1 != 0){
                    res += cards[i];
                    res -= last1;
                    break;
                }
                if (cards[i] % 2 == 1 && last2 != 0){
                    res += cards[i];
                    res -= last2;
                    break;
                }
                i--;
            }
        }
        return res%2==1 ? 0 : res;
    }
};
```

### 期望行为

[1,2,3,4,6,8,10,12,39]
cnt = 3;
期望结果为54，实际输出为30，原因是未校验奇偶替换后的大小

### 屏幕截图

![image](https://github.com/user-attachments/assets/315e5675-f1cb-4265-ad73-9a2d95a87723)
![心算挑战](https://github.com/user-attachments/assets/18daba1d-a3e7-4dcf-824e-29466684bce4)

**Comment by amcones-lc** [comment]
您好，在与相关团队核实后：不处理（因技术原因，我们暂时无法添加测试用例）。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
