### ISSUE TITLE
Missing Test Case - 283. Move Zeroes

### ISSUE THREAD

**Issue by amantiwari1** [LeetCode-Feedback/LeetCode-Feedback#2337]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```python
class Solution:
    def moveZeroes(self, nums: List[int]) -> None:
      j = 0
      for num in nums:
        if num != 0:
          nums[j] = num
          j+=1
      del nums[-j+1:]
      return nums+([0]*(j-1))
```

#### Language used for code

Python

#### Expected behavior

Output is wrong from your website but my output is right from my pc with almost same code

#### Screenshots

this is wrong output
![image](https://user-images.githubusercontent.com/53963065/107553859-32e89a00-6bfb-11eb-8003-794f673a3075.png)

this is right output
![image](https://user-images.githubusercontent.com/53963065/107553987-53185900-6bfb-11eb-8e43-3a3f1face9e8.png)

**Comment by lc-kay** [comment]
@amantiwari1 Unfortunately, we are unable to determine the different results from your local env and our site. However, it appears that a user has faced a similar issue before. Please check this out https://leetcode.com/problems/move-zeroes/discuss/72380/Why-isnt-leet-accepting-this-(python)
