### ISSUE TITLE
[BUG] - <缺陷标题>

### ISSUE THREAD

**Issue by li508q** [LeetCode-Feedback/LeetCode-Feedback#23378]
### LeetCode 用户名

li508q

### 问题号码、标题和链接

376. 摆动序列 https://leetcode.cn/problems/wiggle-subsequence/description/

### Bug Category

缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*

### 描述

错误的代码通过了所有测试用例。

### 你使用的语言

Python/Python3

### 你提交或者运行的代码

```bash
class Solution:
    def wiggleMaxLength(self, nums: List[int]) -> int:
        n = len(nums)
        if n == 1:
            return 1
        if n == 2:
            if nums[0] == nums[-1]:
                return 1
            else:
                return 2
        res = 1
        preTrend = nums[1] - nums[0]
        for i in range(1, n - 1):
            currTrend = nums[i + 1] - nums[i]
            if preTrend == 0:
                preTrend = currTrend
                continue
            if preTrend * currTrend < 0:
                res += 1
                preTrend = currTrend
        if nums[-1] != nums[0]:
            res += 1
        return res
```

### 期望行为

请添加这类首位数字一致的全数组本身就是摆动序列的例子，来规避这种错误代码的通过。

**Comment by amcones-lc** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by li508q** [comment]
您好，这是我的力扣中文网站的个性域名：leetcode.cn/u/li508q/
















在 2024-09-08 10:55:03，"LC-uli" ***@***.***> 写道：

你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by amcones-lc** [comment]
你好，当前该题已添加测试用例，奖励已发放。
