### ISSUE TITLE
无法登录，必须用手机验证码，太搞笑了！

### ISSUE THREAD

**Issue by memcpy0** [LeetCode-Feedback/LeetCode-Feedback#23375]
### LeetCode 用户名

memcpy0

### 问题号码、标题和链接

傻逼登录方式！用GitHub、微信验证都不行，非要拿手机号验证是吧

### Bug Category

问题描述

### 描述

傻逼登录方式！用GitHub、微信验证都不行，非要拿手机号验证是吧

### 你使用的语言

None

### 你提交或者运行的代码

```bash
傻逼登录方式！用GitHub、微信验证都不行，非要拿手机号验证是吧
```

### 期望行为

傻逼登录方式！用GitHub、微信验证都不行，非要拿手机号验证是吧

### 屏幕截图

傻逼登录方式！用GitHub、微信验证都不行，非要拿手机号验证是吧

### 额外的上下文

傻逼登录方式！用GitHub、微信验证都不行，非要拿手机号验证是吧

**Comment by liyuzhu-lc** [comment]
感谢您的来信。系统检测到您的账号登录异常，建议您使用手机验证码登录；同时请注意保护账密，确保您的账号信息安全，防止未经授权的设备访问您的账号。

如果您当前账号绑定的手机号已不再使用，需要重置手机号或登录过程中遇到任何问题，需要解答，请随时联系我们。我们的团队将竭诚为您提供支持，并确保您能够顺利享受我们的服务。

再次感谢您的理解与支持。
