### ISSUE TITLE
[BUG] - 458. Poor Pigs - Incorrect Test Case

### ISSUE THREAD

**Issue by Nyx-Edelstein** [LeetCode-Feedback/LeetCode-Feedback#23395]
### LeetCode Username

Nyx_Edelstein

### Problem Number, Title, and Link

https://leetcode.com/problems/poor-pigs/

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

Test case 19/26 is incorrect.
```
	buckets = 90
	minutesToDie = 2
	minutesToTest = 7
	expected = 4
```

Below is a construction showing that **3** pigs is sufficient to determine which of 90 buckets has poison in 4 iterations.

### Language Used for Code

None

### Code used for Submit/Run operation

```bash
is b=90,t=4,p=3 solvable? YES!!!!!!!!

t=0
	p1 drinks:
		1, 6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86
		(shared with 2)| 7, 32
		(shared with 3)| 8, 33
		(shared with 2/3)| 13
	p2 drinks:
		2, 7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57, 62, 67, 72, 77, 82, 87
		1| 6, 31
		3| 13, 38
	p3 drinks:
		3, 8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58, 63, 68, 73, 78, 83, 88
		1| 11, 36
		2| 12, 37
	none:
		0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85
		4, 9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 74, 79, 84, 89
t=1
	p1 dies
		poison in: 1, 16, 21, 26, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86
		# reduced to b=14,t=3,p=2
	p2 dies
		poison in: 2, 17, 22, 27, 42, 47, 52, 57, 62, 67, 72, 77, 82, 87
		# reduced to b=14,t=3,p=2
	p3 dies
		poison in: 3, 18, 23, 28, 43, 48, 53, 58, 63, 68, 73, 78, 83, 88
		# reduced to b=14,t=3,p=2
	p1 and p2 die
		poison in: 7, 32, 6, 31; b=4,t=3,p=1 is trivially solvable
	p1 and p3 die
		poison in: 8, 33, 11, 36; b=4,t=3,p=1 is trivially solvable
	p2 and p3 die
		poison in: 38, 12, 37; b=3,t=3,p=1 is trivially solvable
	all pigs die
		poison in: 13; solved
	no pigs die
		poison in: 
		0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85
		4, 9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 74, 79, 84, 89
		## reduced to b=36,t=3,p=3

	Every bucket is uniquely accounted for.

# => b=14,t=3,p=2 solvable? YES
	Note: 1-to-1 correspondence exists with numbers from previous case, selected based on case
t=0
	p1 drinks:
		2, 6, 10
	p2 drinks:
		3, 7, 11
	none:
		0, 4, 8, 12
		1, 5, 9, 13
t=1 
	p1 dies
		poison in: 2, 6, 10; b=3,t=2,p=1 is trivially solvable
	p2 dies
		poison in: 3, 7, 11; b=2,t=2,p=1 is trivially solvable
	no pigs die
		poison in:
		0, 4, 8, 12
		1, 5, 9, 13

--case of no pigs dying:

	p1 drinks
		0, 4, 8
	p2 drinks
		12, 1, 5
	p3 drinks
		9, 13
t=2
	p1 dies
		poison in: 0, 4, 8; b=3,t=1,p=2 is trivially solvable
	p2 dies
		poison in: 12, 1, 5; b=3,t=1,p=2 is trivially solvable
	p3 dies
		poison in: 9, 13; b=2,t=1,p=2 is trivially solvable

## => b=36,t=3,p=3 solvable? YES
	Note: 1-to-1 correspondence exists with numbers from previous case
t=0
	p1 drinks:
		1, 5, 9, 13, 17, 21, 25, 29, 33
		2| 6, 22
		3| 7, 23
		2/3| 11
	p2 drinks:
		2, 6, 10, 14, 18, 22, 26, 30, 34
		1| 5
		3| 11
	p3 drinks:
		3, 7, 11, 15, 19, 23, 27, 31, 35
		1| 9
		2| 10
	none:
		0, 4, 8, 12, 16, 20, 24, 28, 32
t=1
	p1 dies
		poison in: 1, 13, 17, 21, 25, 29, 33
		reduced to b=7,t=2,p=2; solvable since b=8,t=2,p=2 is solved (see above)
	p2 dies
		poison in: 2, 14, 18, 26, 30, 34
		reduced to b=6,t=2,p=2; solvable since b=8,t=2,p=2 is solved (see above)
	p3 dies
		poison in: 3, 15, 19, 27, 31, 35
		reduced to b=6,t=2,p=2; solvable since b=8,t=2,p=2 is solved (see above)
	p1 and p2 die
		poison in: 6, 22, 5; b=3,t=2,p=1 is trivially solvable		
	p1 and p3 die
		poison in: 7, 23, 9; b=3,t=2,p=1 is trivially solvable
	p2 and p3 die
		poison in: 10; solved
	all pigs die
		poison in: 11; solved		
	no pigs die
		poison in:
		0, 4, 8, 12, 16, 20, 24, 28, 32

-- case of no pigs dying

	p1 drinks:
		0, 4, 8
	p2 drinks:
		12, 16, 20
	p3 drinks:
		24, 28, 32
t=2
	p1 dies
		poison in: 0, 4, 8; b=3,t=1,p=2 is trivially solvable
	p2 dies
		poison in: 12, 16, 20; b=3,t=1,p=2 is trivially solvable
	p3 dies
		poison in: 24, 28, 32; b=3,t=1,p=3 is trivially solvable
```

### Expected behavior

As per the problem statement,

> return the minimum number of pigs needed to figure out which bucket is poisonous within the allotted time.

Since a valid construction exists for 3 pigs to uniquely determine which of 90 buckets is poisonous within the allotted time, the expected output for this test case should be 3 and not 4.

**Comment by stormsunshine** [comment]
In your construction, if the first two pigs die after the first 2 minutes, then the poison may be in one of the four buckets: 6, 7, 31, and 32. Now the remaining time is 5 minutes, with 1 pig left.

Since each round takes 2 minutes, there are at most 2 rounds in 5 minutes. Since there is only 1 pig left, only one bucket can be fed to the pig in each round. With 2 rounds remaining, the maximum number of buckets that can be figured out is 3 (If the pig dies after a specific round, then the last bucket that is fed to the pig is poisonous. If the pig does not die after the two rounds, then the remaining bucket is poisonous). Now there are 4 buckets remaining, and at most 2 buckets can be fed to the pig in 2 rounds, so there are still 2 buckets remaining. How can you tell which bucket is poisonous in the 2 remaining buckets?

**Comment by Nyx-Edelstein** [comment]
> In your construction, if the first two pigs die after the first 2 minutes, then the poison may be in one of the four buckets: 6, 7, 31, and 32. Now the remaining time is 5 minutes, with 1 pig left.

After the first 2 pigs die, the time is t=2 and the third pig may drink from one of the buckets. Lets say it drinks from 6.

t=4, if pig 3 is dead it's in 6. If not it drinks from 7.

t=6, if pig 3 is dead it's in 7. If not it drinks from 31.

If the pig lives it's in 31, otherwise it's in 32.

**Comment by Nyx-Edelstein** [comment]
> In your construction, if the first two pigs die after the first 2 minutes, then the poison may be in one of the four buckets: 6, 7, 31, and 32. Now the remaining time is 5 minutes, with 1 pig left.
> 
> Since each round takes 2 minutes, there are at most 2 rounds in 5 minutes. Since there is only 1 pig left, only one bucket can be fed to the pig in each round. With 2 rounds remaining, the maximum number of buckets that can be figured out is 3 (If the pig dies after a specific round, then the last bucket that is fed to the pig is poisonous. If the pig does not die after the two rounds, then the remaining bucket is poisonous). Now there are 4 buckets remaining, and at most 2 buckets can be fed to the pig in 2 rounds, so there are still 2 buckets remaining. How can you tell which bucket is poisonous in the 2 remaining buckets?

I see, the problem statement of `5. Repeat this process until you run out of time.` Is somewhat ambiguous. I took it to mean a loop condition (repeat the loop if you have time, otherwise stop).
