### ISSUE TITLE
[BUG] - #3016 example #2 is invalid

### ISSUE THREAD

**Issue by bradhanson** [LeetCode-Feedback/LeetCode-Feedback#23408]
### LeetCode Username

user5718U

### Problem Number, Title, and Link

https://leetcode.com/problems/minimum-number-of-pushes-to-type-word-ii/

### Bug Category

Problem examples

### Bug Description

The problem description states:

> each letter must be mapped to exactly one key

But in example 2 the letter "z" is mapped to both key 4 and key 8.

### Language Used for Code

None

### Expected behavior

"z" is used explicitly in example 2 and it should not appear on key 8.

### Screenshots

![image](https://github.com/user-attachments/assets/b71559f3-9577-404c-a459-469150e6f89e)

**Comment by rambabu-patidar** [comment]
just came to report the same issue.
