### ISSUE TITLE
Missing Test Case - 138. Copy List with Random Pointer

### ISSUE THREAD

**Issue by rhavran** [LeetCode-Feedback/LeetCode-Feedback#2341]
#### Your LeetCode username
havran

#### Category of the bug
- [ ] Missing Test Case

#### Description of the bug
There are a missing test case and a wrong return list in the output.
If we just copy the list without random nodes the solution will pass and will show that we have correct pointers in the output list.

#### Code you used for Submit/Run operation
```
/**
 * Example:
 * var ti = Node(5)
 * var v = ti.`val`
 * Definition for a Node.
 * class Node(var `val`: Int) {
 *     var next: Node? = null
 *     var random: Node? = null
 * }
 */

class Solution {
    fun copyRandomList(node: Node?): Node? {
        if(node==null){
            return node
        }
       
        var copyRoot: Node? = null
        var copyPointer: Node? = null
        var pointer = node
        while(pointer!=null){
         
            if(copyRoot == null){
               copyRoot = Node(pointer.`val`)
               copyPointer = copyRoot
            }else{
               copyPointer!!.next = Node(pointer.`val`)
               copyPointer = copyPointer.next!!
            }
            
            pointer = pointer.next
        }
       
       // Show that all random nodes are null
        pointer = copyRoot
        while(pointer!=null){
            println(pointer.random)
             
            pointer = pointer.next
        }
        
        return copyRoot
    }
}
```

#### Language used for code
Kotlin

#### Expected behavior
Should file because we don't have pointers on the random nodes.

#### Screenshots

![image](https://user-images.githubusercontent.com/12202814/107596442-bc8d6d00-6be5-11eb-8087-cb9dc5558bf8.png)

**Comment by RakeshSeervi** [comment]
#2332 is even weirder...

**Comment by lc-kay** [comment]
Hi @rhavran 
Thank you for reaching out to us. I've relayed this issue to our team to investigate. In regards to the missing test case, can you please provide a custom test case that your accepted solution failed on?

**Comment by lc-kay** [comment]
Hi @rhavran 
Thank you for your time. We've updated this problem accordingly due to a previous report from another user.
