### ISSUE TITLE
[BUG] - <Design Neighbor Sum Service class name issue> 

### ISSUE THREAD

**Issue by chrisconcepcion** [LeetCode-Feedback/LeetCode-Feedback#23415]
### LeetCode Username

Chris1337

### Problem Number, Title, and Link

3242. Design Neighbor Sum Service https://leetcode.com/problems/design-neighbor-sum-service/description/

### Bug Category

Problem description

### Bug Description

The class name neighborSum is not a valid class name in the Ruby programming language, class names needs to be uppercase.

I was able to get around this by adding a function 

def neighborSum 
  NeighborSum 
end 

My entire solution is here: https://leetcode.com/problems/design-neighbor-sum-service/solutions/5598473/simple-solution/

I should not have to add this function and i am sure many rubyist will not even get passed this problem.

### Language Used for Code

Ruby

### Code used for Submit/Run operation

```bash
class neighborSum
    attr_accessor :grid

=begin
    :type grid: Integer[][]
=end
    def initialize(grid)
        @grid = grid
    end


=begin
    :type value: Integer
    :rtype: Integer
=end
    def adjacent_sum(value)
        total = 0
        y, x = find_y_and_x value

        if y > 0
            total += @grid[y-1][x]
        end

        if y + 1 < @grid.size 
            total += @grid[y+1][x]
        end

         if x > 0
            total += @grid[y][x-1]
        end

        if x + 1 < @grid[0].size 
            total += @grid[y][x+1]
        end

        total
    end


=begin
    :type value: Integer
    :rtype: Integer
=end
    def diagonal_sum(value)
        total = 0
        y, x = find_y_and_x value

        if y > 0 and x > 0
            total += @grid[y-1][x-1]
        end

        if y > 0 and x + 1 < @grid[0].size 
            total += @grid[y-1][x+1]
        end

        if y + 1 < @grid.size and x > 0
            total += @grid[y+1][x - 1]
        end

        if y + 1 < @grid.size and x + 1 < @grid[0].size 
            total += @grid[y+1][x+1]
        end

        total
    end

    def find_y_and_x value
        y = 0
        x = 0
        i = @grid[y][x]
        while i != value
            if @grid[y][x + 1] == nil
                y += 1
                x = 0
            else
                x += 1
            end

            i = @grid[y][x]
        end

        [y, x]
    end


end
```

### Expected behavior

it should not run and it does not because its an improper class name. 

### Additional context

: class/module name must be CONSTANT (SyntaxError) in solution.rb
    attr_accessor :grid
      ^~~~~~~~~~~
      
      
      ^ error

**Comment by wktang** [comment]
Issue fixed
