### ISSUE TITLE
[BUG] - <缺陷标题>

### ISSUE THREAD

**Issue by Chinglish123** [LeetCode-Feedback/LeetCode-Feedback#23424]
### LeetCode 用户名

我的代码完整的通过了测试用例，但是有一个情况没有覆盖 预期应该返回2但是我的代码返回1，这却通过了测试用例

### 问题号码、标题和链接

https://leetcode.cn/problems/B1IidL/submissions/553290722/?envType=study-plan-v2&envId=coding-interviews-special

### Bug Category

问题提示, 不正确或缺少“相关标签”, 不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*, 缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*

### 描述

我的代码完整的通过了测试用例，但是有一个情况没有覆盖
预期应该返回2但是我的代码返回1，这却通过了测试用例

### 你使用的语言

Java

### 你提交或者运行的代码

```bash
我的代码完整的通过了测试用例，但是有一个情况没有覆盖
预期应该返回2但是我的代码返回1，这却通过了测试用例
```

### 期望行为

我的代码完整的通过了测试用例，但是有一个情况没有覆盖
预期应该返回2但是我的代码返回1，这却通过了测试用例

**Comment by amcones-lc** [comment]
感谢反馈，能否向我们补充测试用例信息，把信息提供完整才能有助于快速验证和精准的定位，谢谢。
