### ISSUE TITLE
Missing Test Case - 120. Triangle

### ISSUE THREAD

**Issue by martinez-acosta** [LeetCode-Feedback/LeetCode-Feedback#2342]
#### Your LeetCode username

martinez-acosta

#### Category of the bug
- [ ] Question
- [X ] Solution
- [ ] Language

#### Description of the bug

Testcase failure.

#### Code you used for Submit/Run operation

```
class Solution:
    def minimumTotal(self, triangle: List[List[int]]) -> int:
        '''
        BASE:
            row = 0
            index = 0
            minSum = triangle[0][index]
        
        for the remaining rows:
            row = 1, last_index = 0
            index = ( last_index + 1 ) - 1 or (last_index + 1 )
            index = last_index or (last_index + 1)
            index =  0 or 1

            row = 2, last_index as 0, if last_index=0 from row 1
            index = last_index or (last_index + 1)
            index = 0 or 1

            row = 2, last_index as 1, if last_index=1 from row 1
            index = last_index  or (last_index + 1 )
            index = 1 or 2

        '''
        last_index = 0
        minSum = triangle[0][0]
        
        for row in range(1, len(triangle)):
            i = last_index
            a = triangle[row][i]
            b = triangle[row][i+1]
            
            if a < b:
                last_index = i
                minSum += a 
            else:
                last_index = i + 1
                minSum += b
        
        return minSum
```

#### Language used for code

Python

#### Expected behavior

With input: [[-1],[2,3],[1,-1,-3]]
Min path in bold:
  **-1**         
  **2** 3        
1 **-1** -3
minSum = -1 + 2 -1 = 0 
true output: 0
Expected output testcase (wrong): -1

#### Screenshots

![image](https://user-images.githubusercontent.com/16024090/107671353-5f330380-6c59-11eb-89c9-0025627d04ed.png)

**Comment by lc-kay** [comment]
@martinez-acosta The expected answer is correct. Please check this post for a better understanding https://leetcode.com/problems/triangle/discuss/38965/Is-1-2-3-1-1-3-output-is-1 Thank you for your time.
