### ISSUE TITLE
Missing Test Case - 459. Repeated Substring Pattern

### ISSUE THREAD

**Issue by hp1100** [LeetCode-Feedback/LeetCode-Feedback#2343]
#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean repeatedSubstringPattern(String str) {
        int j = 0, n = str.length();
        char[] s = str.toCharArray();
        int[] dp = new int[n];
        for (int i = 1; i < n; i++) {
            while (j > 0 && s[i] != s[j]) j = dp[j - 1];
            if (s[i] == s[j]) j++;
            dp[i] = j;
        }
        while (j > 1) {
            if (n % j == 0) return true;
            j = dp[j - 1];
        }
        return j == 1 ? str.chars().distinct().count() == 1L : false;
    }
}
```

#### Language used for code
Java

#### Expected behavior

My soluction code get accepted but it's wrong. 

For test case: "abcdab" should return false but my code return true;

#### Screenshots
![image](https://user-images.githubusercontent.com/28928830/107620411-7d711300-6c09-11eb-8113-decb6672040d.png)

**Comment by lc-kay** [comment]
Hi @hp1100 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @hp1100 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!
