### ISSUE TITLE
[BUG] - <title> 840. Magic Squares In Grid Test Case 78 is incorrect

### ISSUE THREAD

**Issue by dSplashh** [LeetCode-Feedback/LeetCode-Feedback#23459]
### LeetCode Username

splashh15

### Problem Number, Title, and Link

840. Magic Squares In Grid https://leetcode.com/problems/magic-squares-in-grid/submissions/1350331347/?envType=daily-question&envId=2024-08-09

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

Test case 78  ``[[2,7,6],[1,5,9],[4,3,8]]`` should return 1 because this is a 3x3 magic square.

Explanation:

Rows:
2 + 7 + 6 = 15
1 + 5 + 9 = 15
4 + 3 + 8 = 15

Columns:
2 + 1 + 4 = 15
7 + 5 + 3 = 15
6 + 9 + 8 = 15

Diagonals:
2 + 5 + 8 = 15
6 + 5 + 4 = 15

All rows, columns, and diagonals sum to the same number (15), and the grid contains all distinct numbers from 1 to 9. Therefore, this grid is a valid 3x3 magic square, and the function should return 1.

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
class Solution {
public:
    int numMagicSquaresInside(vector<vector<int>>& grid) {
        int row = grid.size();
        int col = grid[0].size();
        int magic_square = 0;

        if (row < 3|| col < 3){
            return 0;
        }
        else{
            row = (row % 3) + 1;
            col = (col % 3) + 1;
        }

        for (int r = 0; r < row; r++){
            for(int c = 0; c < col; c++){
                std::vector<int> distinct_nums = {1, 2, 3, 4, 5, 6, 7, 8, 9};
                std::vector<int> nums_toAdd = {grid[r][c], grid[r][c + 1], grid[r][c + 2], grid[r + 1][c], 
                grid[r + 1][c + 1], grid[r + 1][c + 2], grid[r + 2][c], grid[r + 2][c + 1], grid[r + 2][c + 2]};

                int top_across = nums_toAdd[0] + nums_toAdd[1] + nums_toAdd[2];
                int mid_across = nums_toAdd[3] + nums_toAdd[4] + nums_toAdd[5];
                int bot_across = nums_toAdd[6] + nums_toAdd[7] + nums_toAdd[8];
                int downward_diagonal = nums_toAdd[0] + nums_toAdd[4] + nums_toAdd[8];
                int upward_diagonal = nums_toAdd[6] + nums_toAdd[4] + nums_toAdd[2];

                sort(nums_toAdd.begin(), nums_toAdd.end());

                if (top_across == mid_across && mid_across == bot_across && bot_across == downward_diagonal && downward_diagonal == upward_diagonal && distinct_nums == nums_toAdd){
                    magic_square += 1;
                }
            }
        }

        return magic_square;
    }
};
```

### Expected behavior

What happened was the test case is expecting 0 but it should be expecting 1.

**Comment by uptanuj** [comment]
Incorrect Column Sum:
Columns:
**_2 + 1 + 4 = 15_** 7
7 + 5 + 3 = 15
**_6 + 9 + 8 = 15_** 23

**Comment by stormsunshine** [comment]
Why do you think 2 + 1 + 4 = 15 and 6 + 9 + 8 = 15? This test case should indeed return 0.

**Comment by dSplashh** [comment]
Sorry thank you.
