### ISSUE TITLE
[BUG] - missing test case - 840. Magic Squares In Grid

### ISSUE THREAD

**Issue by misclicked** [LeetCode-Feedback/LeetCode-Feedback#23451]
### LeetCode Username

misclicked

### Problem Number, Title, and Link

840. Magic Squares In Grid https://leetcode.com/problems/magic-squares-in-grid

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

My code passes all test case.

The following test case which follows the problem's input constraint:
```grid = [[4,3,8],[9,5,0],[12,7,6]]```
Adding this test case will give my code WRONG ANSWER

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
class Solution {
public:
    static inline unordered_set<int> se{
        276951438,
        294753618,
        438951276,
        492357816,
        618753294,
        672159834,
        816357492,
        834159672,
    };

    int numMagicSquaresInside(vector<vector<int>>& grid) {
        int n=grid.size(), m=grid[0].size(), ans=0;
        int here;
        for(int i=0;i<n-2;i++)
            for(int j=0;j<m-2;j++){
                here=0;
                for(int ii=0;ii<3;ii++)
                    for(int jj=0;jj<3;jj++)
                        here = here*10+grid[i+ii][j+jj];
                if(se.count(here))ans++;
            }
        return ans;
    }
};
```

### Expected behavior

My code should receive "Wrong Answer"

### Screenshots

![image](https://github.com/user-attachments/assets/4e6e613a-6681-4220-9631-6f09fd7330aa)

![image](https://github.com/user-attachments/assets/4cf64849-f446-4cdd-aa70-21744f825a7c)

**Comment by uptanuj** [comment]
12 breaches range mentioned in the contrains: 
A 3 x 3 magic square is a 3 x 3 grid filled with distinct numbers **_from 1 to 9_**

**Comment by misclicked** [comment]
> 12 breaches range mentioned in the contrains: A 3 x 3 magic square is a 3 x 3 grid filled with distinct numbers **_from 1 to 9_**

Constraints:

row == grid.length
col == grid[i].length
1 <= row, col <= 10
**_0 <= grid[i][j] <= 15_**
