### ISSUE TITLE
[BUG] - Missing testcase

### ISSUE THREAD

**Issue by shv-luffy-98** [LeetCode-Feedback/LeetCode-Feedback#23460]
### LeetCode Username

sriharivishnu

### Problem Number, Title, and Link

https://leetcode.com/problems/magic-squares-in-grid

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

For the below testcase, the code used was wrong but gets accepted.
```
[[3,8,1],[4,5,6],[9,2,7]]
```

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
class Solution {
public:
    int numMagicSquaresInside(vector<vector<int>>& g) {
        int res = 0, rows = g.size() - 3, cols = g[0].size() - 3;
        if (rows < 0 || cols < 0)
            return 0;
        ostringstream s;
        string buf(8, ' ');
        int i1, i2, j1, j2;

        for (int i = 0; i <= rows; ++i) {
            for (int j = 0; j <= cols; ++j) {
                if (g[i + 1][j + 1] != 5)
                    continue;
                i1 = i + 1, i2 = i + 2, j1 = j + 1, j2 = j + 2;
                s.str(buf);
                s << g[i][j] << g[i1][j] << g[i2][j] << g[i2][j1] << g[i2][j2]
                  << g[i1][j2] << g[i][j2] << g[i][j1];
                string temp = s.str() + s.str();
                if (temp.find("43816729") != string::npos ||
                    temp.find("92761834") != string::npos)
                    ++res;
            }
        }
        return res;
    }
};
```

### Expected behavior

Expected output `0` is shown correctly on running, but the testcase isn't being tested on submission

### Screenshots

![image](https://github.com/user-attachments/assets/3a0ba2b0-381f-4737-a3bd-9cb9c6914e94)

**Comment by uptanuj** [comment]
[3,8,1] does not sum up to 15
