### ISSUE TITLE
[BUG] - Broken C support

### ISSUE THREAD

**Issue by ghost** [LeetCode-Feedback/LeetCode-Feedback#23476]
### LeetCode Username

evlpwn

### Problem Number, Title, and Link

https://leetcode.com/problems/find-median-from-data-stream/description/?envType=problem-list-v2&envId=p0b45wmm

### Bug Category

Problem constraints, Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

Implementation does ok when running, but fails on time when submitting (test case 20/21).
Also, trying to use realloc blows up the heap. Seems like poor C support.

### Language Used for Code

C

### Code used for Submit/Run operation

```bash
typedef struct {
    int *arr,
        len;
} MedianFinder;

MedianFinder *medianFinderCreate() {
    MedianFinder *obj = (MedianFinder *)malloc(sizeof(MedianFinder));

    obj->len = 0;
    obj->arr = (int *)malloc(sizeof(int) * 50000);

    return obj;
}

void medianFinderAddNum(MedianFinder* obj, int num) {
    int i=0, j=obj->len-1, m, tmp1, tmp2;

    while(i<=j) {
        m = (j+i)/2;

        if(num < obj->arr[m])
            j = m - 1;
        else
            i = m + 1;        
    }

    tmp1 = obj->arr[i];
    obj->arr[i++] = num;
    obj->len++;

    while(i < obj->len) {
        tmp2 = obj->arr[i];            
        obj->arr[i++] = tmp1;
        tmp1 = tmp2;
    }
}

double medianFinderFindMedian(MedianFinder* obj) {
    double ret;
    int i = obj->len/2;

    if(obj->len % 2)
        ret = obj->arr[i];
    else
        ret = ((double)obj->arr[i-1]+obj->arr[i])/2;

    return ret;
}

void medianFinderFree(MedianFinder* obj) {
    free(obj->arr);
    free(obj);
}
```
```


### Expected behavior

Running and submitting should behave the same.
Trying to use realloc should not result in 1.7GB (!!!) memory consumption for leetcode tab, not to mention failing on "memory limit exceeded"

### Screenshots

_No response_

### Additional context

_No response_

**Comment by evlpwn** [comment]
Hi Winston,

Thank you for your response but it does not seem as though you've looked into this issue at all.
To be super clear, the following extra simple 4 line code fails when running (please do try it!):
```
    void *test = NULL;
    int i;

    for(i = 0 ; i < 40*1024 ; i++)
        test = realloc(test, i);                
```
Is a 40k allocation supposed to terminate with "memory limit exceeded" ???

**Comment by yumkam** [comment]
With asan enabled -- sadly, absolutely expected behavior (it needs to track access to freed/reallocated memory).
