### ISSUE TITLE
Better description and examples on design-a-leaderboard

### ISSUE THREAD

**Issue by coderansu** [LeetCode-Feedback/LeetCode-Feedback#235]
**What kind of the bug**
- [X] problem
- [ ] solution
- [ ] language

**Describe the bug**
Two issues:
1. With only one example given it was unclear that add score actually adds to existing score for a player, rather than updating it. Consider updating that example to call addScore on some player id more than once to make this clear.
2. Description at top should make clear that Reset actually removes the player from the board (as shown in example), rather than resetting the score but leaving player on the leaderboard with a value of 0 (this is the what the description step 3 seems to indicate)

**what language is your code written in**
C#

**The code you submit/run**
```
public class Player {
    public int Id {get; set; }
    public int Score {get; set; }
    public Player(int id, int score) {
        this.Id = id;
        this.Score = score;
    }
}

public class PlayerComparer : Comparer<Player> {
    public override int Compare(Player a, Player b) {
        // -ves for doing sort by descending order
        int aScore = -a.Score, bScore = -b.Score;
        
        if (aScore.CompareTo(bScore) != 0) {
            return aScore.CompareTo(bScore);
        } else {
            return a.Id.CompareTo(b.Id);
        }
    }
}

public class Leaderboard {
    private SortedSet<Player> players;
    private Dictionary<int,Player> playerBoard;

    public Leaderboard() {
        players = new SortedSet<Player>(new PlayerComparer());
        playerBoard = new Dictionary<int,Player>();
    }
    
    public void AddScore(int playerId, int score) {
        Player p;
        if (playerBoard.ContainsKey(playerId)) {
            p = playerBoard[playerId];
            // re-sort on updates
            players.Remove(p);
            p.Score += score;
            players.Add(p);
        } else {
            p = new Player(playerId, score);
            playerBoard.Add(playerId, p);
            players.Add(p);
        }
    }
    
    public int Top(int K) {
        int sum = 0, i = 0;
        foreach (Player p in players) {
            if (i >= K) {
                break;
            } else {
                ++i;
                //Console.WriteLine("Processing player[{0}] with score {1}", p.Id, p.Score);
                sum += p.Score;
            }
        }
        return sum;
    }
    
    public void Reset(int playerId) {
        if (playerBoard.ContainsKey(playerId)) {
            // remove player
            Player p = playerBoard[playerId];
            players.Remove(p);
            playerBoard.Remove(playerId);
        }
    }
}
```

**Expected behavior**
With this test case below, my code was returning value 84 (player id 3) instead of 160 expected by the test case. After updating ""p.Score = score" to "p.Score += score" in AddScore method the test passed. While addScore may imply adding to the score instead of replacing/updating the score, a better example would make this clear.
Example test case:
["Leaderboard","addScore","addScore","addScore","addScore","addScore","addScore","addScore","addScore","addScore","addScore","top","reset","reset","addScore","addScore","top"]
[[],[1,13],[2,93],[3,84],[4,6],[5,89],[6,31],[7,7],[8,1],[9,98],[10,42],[5],[1],[2],[3,76],[4,68],[1]]

**Screenshots**

**Additional context**

**Comment by CooperCooperCooper** [comment]
Hi @coderansu ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @coderansu ,
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
