### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by Anikaaaaa** [LeetCode-Feedback/LeetCode-Feedback#2350]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@Anikaaaaa Please provide the accepted solution and the custom test case you wish to contribute. Thank you for your time.

**Comment by lc-kay** [comment]
Hi @Anikaaaaa 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
