### ISSUE TITLE
[BUG] - 63不同路径II的描述问题

### ISSUE THREAD

**Issue by Shyuna** [LeetCode-Feedback/LeetCode-Feedback#23516]
### LeetCode 用户名

Shyuna

### 问题号码、标题和链接

63.不同路径II https://leetcode.cn/problems/unique-paths-ii/description/?envType=study-plan-v2&envId=top-interview-150

### Bug Category

问题描述, 问题限制, 力扣官方题解

### 描述

题目中没有对计算的中间结果不会溢出INT值做约束，官方C++题解不能通过中间结果会溢出INT值但是最终结果在INT范围内的数据。

### 你使用的语言

C++

### 期望行为

题目上应该增加相关值范围的约束。
或者修改题解代码实现对相关可能溢出INT情况的处理。

**Comment by amcones-lc** [comment]
感谢反馈，能否向我们补充测试用例信息，把信息提供完整才能有助于快速验证和精准的定位，谢谢。
