### ISSUE TITLE
[BUG] - Wrong Test Case in problem number 152- Maximum Product Subarray

### ISSUE THREAD

**Issue by rishavv99** [LeetCode-Feedback/LeetCode-Feedback#23524]
### LeetCode Username

rishavrajprasad

### Problem Number, Title, and Link

152. Maximum Product Subarray https://leetcode.com/problems/maximum-product-subarray/description/

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

The problem statement guarantees that the test cases are generated such that the answer will fit within a 32-bit integer. However, one test case, specifically 
'[0,10,10,10,10,10,10,10,10,10,-10,10,10,10,10,10,10,10,10,10,0]'
, leads to an overflow condition, which contradicts the problem's stated constraints.

### Language Used for Code

Java

### Code used for Submit/Run operation

```bash
class Solution {
    public int maxProduct(int[] arr) {
        int n = arr.length;
        int pre = 1, suff = 1;
        int ans = Integer.MIN_VALUE;

        for (int i = 0; i < n; i++) {
            pre *= arr[i];
            suff *= arr[n - i - 1];
            ans = Math.max(ans, Math.max(pre, suff));
            if (pre == 0) pre = 1;
            if (suff == 0) suff = 1;
        }

        return ans;
    }
}
```

### Expected behavior

the expected output should be 1000000000, which is within the scope of a 32-bit integer. However, during computation, intermediate values may exceed the 32-bit integer limit, causing an overflow and resulting in incorrect behavior. This contradicts the problem's constraints."

### Screenshots

![Uploading Screenshot 2024-08-14 190605.png…]()

**Comment by luciphania** [comment]
Hello there,

Thanks for reaching out!

While the given test case still satisfied the original constraints, the constraints have been updated such that any subarray product now fits inside 32-bit integer now.

Best,
LeetCode Support Team
