### ISSUE TITLE
[BUG] - 29. Divide Two Integers Med.

### ISSUE THREAD

**Issue by misProyectosPropios** [LeetCode-Feedback/LeetCode-Feedback#23533]
### LeetCode Username

Inaki_Frutos

### Problem Number, Title, and Link

https://leetcode.com/problems/divide-two-integers/

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

This should be the same number, but with the oppesite sign. But, the division expects a differente number
This test case expects an incorrect output. 

### Language Used for Code

Java

### Code used for Submit/Run operation

```bash
class Solution {
    public int divide(int dividend, int divisor) {
        int sign = 1;
        if ((dividend < 0 && divisor > 0) || (dividend > 0 && divisor < 0)) {
            sign = -1;
        }
        
        long dividend_long = Long.valueOf(dividend);
        long divisor_long = Long.valueOf(divisor);
        int res = 0;
        if ((divisor_long <= 0 && dividend_long >= 0) || (divisor_long >= 0 && dividend_long <= 0)) {
            while (!isResto(dividend_long, divisor_long)) {
                res--;
                dividend_long += divisor_long;
            }
        } else {
            while (!isResto(dividend_long, divisor_long)) {
                res++;
                dividend_long -= divisor_long;
            }
        }
        return res;
        
    }

    private Boolean isResto(long dividendo, long divisor) {
        long divisor_abs = Math.abs(divisor);
        return (dividendo < divisor_abs && dividendo >= 0);
    }
}
```

### Expected behavior

This should be the same number, but with the oppesite sign. But, the division expects a differente number
This test case expects an incorrect output. 

Input: dividend =-2147483648
divisor =-1

Expected: 2147483647

### Screenshots

![image](https://github.com/user-attachments/assets/ec890ebb-d85c-482f-b787-d1807607cc50)

### Additional context

Input: dividend =-2147483648
divisor =-1

Expected: 2147483647

**Comment by DhareshP** [comment]
few errors, check this one



class Solution {
    public int divide(int dividend, int divisor) {
        if (dividend == Integer.MIN_VALUE && divisor == -1) {
            return Integer.MAX_VALUE;
        }

        int sign = (dividend < 0) ^ (divisor < 0) ? -1 : 1;

        long dividend_long = Math.abs((long) dividend);
        long divisor_long = Math.abs((long) divisor);
        int res = 0;

        while (dividend_long >= divisor_long) {
            long tempDivisor = divisor_long, multiple = 1;
            while (dividend_long >= (tempDivisor << 1)) {
                tempDivisor <<= 1;
                multiple <<= 1;
            }
            dividend_long -= tempDivisor;
            res += multiple;
        }

        return sign == 1 ? res : -res;
    }
}
