### ISSUE TITLE
[BUG] - MISSING TEST CASE 3256. Maximum Value Sum by Placing Three Rooks I

### ISSUE THREAD

**Issue by ritesh1507** [LeetCode-Feedback/LeetCode-Feedback#23557]
### LeetCode Username

ritesharah

### Problem Number, Title, and Link

3256. Maximum Value Sum by Placing Three Rooks I https://leetcode.com/problems/maximum-value-sum-by-placing-three-rooks-i/description/

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

My code is able to pass all the provided test case in the question. However it fails to run for a particular test case that is not in the set of all test cases in question and this test case is within the constrains provided. 

### Language Used for Code

C++

### Code used for Submit/Run operation

```c++
class Solution {
public:
    long long maximumValueSum(vector<vector<int>>& board) {
        int r = board.size(), c = board[0].size();
        vector<pair<int, pair<int, int>>> maxValue;
        long long ans = LLONG_MIN;
        for (int i = 0; i < r; i++) {
            for (int j = 0; j < c; j++) {
                maxValue.push_back({board[i][j], {i, j}});
            }
        }
        sort(maxValue.rbegin(), maxValue.rend());
        if(maxValue.size()>200){
            while(maxValue.size()>200){
                maxValue.pop_back();
            }
        }
        for (int i = 0; i < maxValue.size(); i++) {
            cout<<maxValue[i].first<<" "<<maxValue[i].second.first<<" "<<maxValue[i].second.second<<endl;
            for (int j = i + 1; j < maxValue.size(); j++) {
                if (maxValue[i].second.first != maxValue[j].second.first &&
                    maxValue[i].second.second != maxValue[j].second.second) {
                    for (int k = j + 1; k < maxValue.size(); k++) {
                        if (maxValue[i].second.first !=
                                maxValue[k].second.first &&
                            maxValue[i].second.second !=
                                maxValue[k].second.second &&
                            maxValue[j].second.first !=
                                maxValue[k].second.first &&
                            maxValue[j].second.second !=
                                maxValue[k].second.second) {
                            ans = max(
                                ans, static_cast<long long>(maxValue[i].first) + static_cast<long long>(maxValue[j].first) + static_cast<long long>(maxValue[k].first));
                        }
                    }
                }
            }
        }
        return ans;
    }
};
```

### Expected behavior

```[[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]] ```

This test case is not included in the internal test cases for the problem as all the test case seems to get passed. However if i run this test case in custom test case, it fails to run. This test case should be included in the internal test cases.

**Comment by luciphania** [comment]
Hello, 

Your reported issue has been relayed to our team for thorough investigation. We appreciate your patience as we work to address and resolve this matter. We will reach out to you when we have updates regarding the issue. 

If you have any further questions or concerns in the meantime, please feel free to let us know. 

Best regards, 
LeetCode Support Team
