### ISSUE TITLE
Missing Test Case - 1229. Meeting Scheduler

### ISSUE THREAD

**Issue by ShawnLYU** [LeetCode-Feedback/LeetCode-Feedback#2355]
#### Your LeetCode username
since2020

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

My solution got accepted but there's one test case that should've failed.

#### Code you used for Submit/Run operation

```java
class Solution {
    public List<Integer> minAvailableDuration(int[][] slots1, int[][] slots2, int duration) {
        PriorityQueue<int[]> priorityQueue = new PriorityQueue<>((slot1, slot2) -> slot1[0] - slot2[0]);
        
        for (int[] slot: slots1) priorityQueue.offer(slot);
        for (int[] slot: slots2) priorityQueue.offer(slot);
        while (priorityQueue.size() > 1) {
            int[] slot1 = priorityQueue.poll();
            int[] slot2 = priorityQueue.peek();
            if (Math.min(slot1[1], slot2[1]) >= slot2[0] + duration) {
                return new ArrayList<Integer>(Arrays.asList(slot2[0], slot2[0] + duration));
            }
        }
        return new ArrayList<Integer>();
    }
}
```

#### Language used for code

Java

#### Expected behavior

Failure.

#### Screenshots

![image](https://user-images.githubusercontent.com/13027678/107719424-37b65800-6ca6-11eb-9fc5-3d637e0cd597.png)

#### Additional context

Test case:
[[10,60]]
[[12,17],[21,50]]
8

**Comment by lc-kay** [comment]
Hi @ShawnLYU 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @ShawnLYU 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
