### ISSUE TITLE
Missing Test Case - 334. Increasing Triplet Subsequence

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#2356]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
The following code can pass all the available test cases now. However, the following code returns an incorrect result for a test case, so the result should be Wrong Answer when submitting the code.
The missing test case is: `[0,4,1,-1,2]`. The following code returns `false`. The correct answer should be `true`.

#### Code you used for Submit/Run operation

```
public class Solution {
    public boolean increasingTriplet(int[] nums) {
        if (nums.length < 3) {
            return false;
        }
        int[] stack = new int[3];
        int ptr = 0;
        for (int num : nums) {
            while (ptr > 0 && stack[ptr - 1] >= num) {
                ptr--;
            }
            stack[ptr++] = num;
            if (ptr == 3) {
                return true;
            }
        }
        ptr = 0;
        for (int i = nums.length - 1; i >= 0; i--) {
            while (ptr > 0 && stack[ptr - 1] <= nums[i]) {
                ptr--;
            }
            stack[ptr++] = nums[i];
            if (ptr == 3) {
                return true;
            }
        }
        return false;
    }
}
```

#### Language used for code
Java

#### Expected behavior
The test case `[0,4,1,-1,2]` is missing and it should be added. After the test case is added, the result should be Wrong Answer when the code is submitted.

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
