### ISSUE TITLE
[BUG] - <两个键的键盘>第四个解答应该是O(n)，不是O(sqrt(n))。

### ISSUE THREAD

**Issue by ConeDragon** [LeetCode-Feedback/LeetCode-Feedback#23563]
### LeetCode 用户名

java-is-best-lang （LCUS）

### 问题号码、标题和链接

650. 两个键的键盘 (https://leetcode.com/problems/2-keys-keyboard/editorial/)

### Bug Category

力扣官方题解

### 描述

> The largest prime factor for `n` is at most $\sqrt{n}$

应该是：

The largest prime factor for `n` is at most $n$

也应该是O(n)

### 你使用的语言

Java

### 期望行为

The largest prime factor for `n` is at most $n$，O(n)运行时间

### 屏幕截图

截屏
![image](https://github.com/user-attachments/assets/93c78fe6-9a81-423a-8842-7f5e84db12a6)

**Comment by samantha-lc** [comment]
Solved

**Comment by ConeDragon** [comment]
Thank you!

**Comment by ConeDragon** [comment]
What is happening?
