### ISSUE TITLE
[BUG] - Missing Testcase

### ISSUE THREAD

**Issue by RishabhGupt** [LeetCode-Feedback/LeetCode-Feedback#23573]
### LeetCode Username

coder0687

### Problem Number, Title, and Link

https://leetcode.com/problems/maximum-value-sum-by-placing-three-rooks-i/

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

below testcase is missing:
board: [[-52,24,-78,-72,68,1,56,-6,43,87],[-30,-45,47,93,1,-73,64,-22,-92,76],[42,-19,-46,-19,47,72,-24,-86,16,-78],[-26,10,72,52,-15,9,-34,41,-70,7],[-6,83,-20,-50,-71,-93,5,22,-67,67],[-12,-29,-81,30,-89,80,20,-58,6,-26],[88,62,6,-57,-93,34,-100,-23,61,57],[42,46,-55,70,-2,20,41,-59,-51,90],[-17,-26,100,-6,-63,11,-57,77,62,-83],[28,43,34,55,52,-22,34,-31,-26,-67]]

### Language Used for Code

Java

### Code used for Submit/Run operation

```bash
class Solution {
    final int IMIN = Integer.MIN_VALUE;
    public long maximumValueSum(int[][] a) {
        int n = a.length, m = a[0].length;
        int pre[][] = new int[n][m];
        int sufx[][] = new int[n][m];

        for(int i=0;i<n;i++) for(int j=0;j<m;j++) pre[i][j] = Math.max(a[i][j], j==0 ? IMIN : pre[i][j-1]);
        for(int i=0;i<n;i++) for(int j=m-1;j>=0;j--) sufx[i][j] = Math.max(a[i][j], j==m-1 ? IMIN : sufx[i][j+1]);
        // System.out.println(Arrays.deepToString(pre));
        // System.out.println(Arrays.deepToString(sufx));

        int[] col1 = {0}, col2 = {2};
        PriorityQueue<Integer> preq = new PriorityQueue<>((row1, row2) -> pre[row2][col1[0]] - pre[row1][col1[0]]);
        PriorityQueue<Integer> sufxq = new PriorityQueue<>((row1, row2) -> sufx[row2][col2[0]] - sufx[row1][col2[0]]);
        for(int i=0;i<n;i++) {
            preq.offer(i);
            sufxq.offer(i);
        }
        long res = Long.MIN_VALUE;
        for(int j=1;j<m-1;j++) {
            preq.offer(preq.poll());
            sufxq.offer(sufxq.poll());
            for(int i=0;i<n;i++) {
                long cur = a[i][j];

                preq.remove(i);
                sufxq.remove(i);

                cur += pre[preq.peek()][col1[0]];
                sufxq.remove(preq.peek());
                cur += sufx[sufxq.peek()][col2[0]];
                sufxq.offer(preq.peek());

                res = Math.max(res, cur);


                cur = a[i][j];
                cur += sufx[sufxq.peek()][col2[0]];
                preq.remove(sufxq.peek());
                cur += pre[preq.peek()][col1[0]];
                preq.offer(sufxq.peek());

                res = Math.max(res, cur);

                preq.offer(i);
                sufxq.offer(i);

            }
            col1[0]++;
            col2[0]++;
            // preq.clear();
            // sufxq.clear();
            // for(int i=0;i<n && col2[0] < m;i++) {
            //     preq.offer(i);
            //     sufxq.offer(i);
            // }
        }
        return res;
    }
}
```

### Expected behavior

It should failed for below test case, but it is accepting my solution:
[[-52,24,-78,-72,68,1,56,-6,43,87],[-30,-45,47,93,1,-73,64,-22,-92,76],[42,-19,-46,-19,47,72,-24,-86,16,-78],[-26,10,72,52,-15,9,-34,41,-70,7],[-6,83,-20,-50,-71,-93,5,22,-67,67],[-12,-29,-81,30,-89,80,20,-58,6,-26],[88,62,6,-57,-93,34,-100,-23,61,57],[42,46,-55,70,-2,20,41,-59,-51,90],[-17,-26,100,-6,-63,11,-57,77,62,-83],[28,43,34,55,52,-22,34,-31,-26,-67]]

### Screenshots

![image](https://github.com/user-attachments/assets/363504f7-f0a2-4281-b9ae-9e78d7dc0bda)

**Comment by luciphania** [comment]
Hello, 

Your reported issue has been relayed to our team for thorough investigation. We appreciate your patience as we work to address and resolve this matter. We will reach out to you when we have updates regarding the issue. 

If you have any further questions or concerns in the meantime, please feel free to let us know. 

Best regards, 
LeetCode Support Team

**Comment by luciphania** [comment]
Thank you for your time.

Your feedback has been used to enhance the problem. As a token of our appreciation, your LeetCode account has been credited with 100 LeetCoins.

If you have any more questions or additional feedback, please don't hesitate to let us know. Your continued support is invaluable to us!

Best regards,
The LeetCode Team
