### ISSUE TITLE
Missing Test Case - 284. Peeking Iterator

### ISSUE THREAD

**Issue by patyannul** [LeetCode-Feedback/LeetCode-Feedback#2357]
#### Your LeetCode username

patrick40

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The code below passes the current test cases but fails the proposed new test case that I am submitting. The code below treats a value of `0` as a `False` for `hasNext` resulting in the error.

#### Code you used for Submit/Run operation

```
class PeekingIterator:
    def __init__(self, iterator):
        self.it = iterator
        self._next = self.it.hasNext() and self.it.next()

    def peek(self):
        return self._next

    def next(self):
        temp, self._next = self._next, self.it.hasNext() and self.it.next()
        return temp

    def hasNext(self):
        return bool(self._next)
```

The following is the test case that fails:
```
["PeekingIterator","next","peek","next","hasNext","next","hasNext"]
[[[0,0,0]],[],[],[],[],[],[]]
```

#### Language used for code

Python3

#### Expected behavior

The code above results in:
```
[null,0,0,0,false,0,false]
```

The expected result is:
```
[null,0,0,0,true,0,false]
```

**Comment by lc-kay** [comment]
Hi @patyannul 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @patyannul 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
