### ISSUE TITLE
[BUG] - Weak Testcases for problem 3261

### ISSUE THREAD

**Issue by shreyg-upta** [LeetCode-Feedback/LeetCode-Feedback#23575]
### LeetCode Username

shreyg-upta

### Problem Number, Title, and Link

3261. Count Substrings That Satisfy K-Constraint II https://leetcode.com/problems/count-substrings-that-satisfy-k-constraint-ii/

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

The given testcases are very weak as it is allowing codes with time complexity θ(n*q) which is equal to 10^10 get accepted where as it should give TLE. i have attached the testcase below which is giving TLE on LC compiler and should be present in the hidden testcases. 

s = [https://p.ip.fi/Xuqb](https://p.ip.fi/Xuqb)
k = [https://p.ip.fi/O7eF](https://p.ip.fi/O7eF)
queries = [https://p.ip.fi/80G8](https://p.ip.fi/80G8)

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
class Solution {
public:
    vector<long long> countKConstraintSubstrings(string s, int k, vector<vector<int>>& queries) 
    {
        long long n = s.size(),l,r,one=0,zero=0,cur,i,len;
        vector <long long> ans,pre(n+1),a(n);
        l = 0;
        for(r=0;r<n;r++)
        {
            s[r] == '1' ? one++ : zero++;
            while(zero > k && one > k)
            {
                s[l] == '1' ? one-- : zero--;
                l++;
            }
            cur = r - l + 1;
            a[r] = cur;
        }
        for(i=0;i<n;i++)
        {
            pre[i+1] = pre[i] + a[i];
        }
        for(auto &q : queries)
        {
            l = q[0];
            r = q[1];
            cur = 0;
            len = 0;
            for(i=l;i<=r;i++)
            {
                len++;
                if(a[i] <= len)
                {
                    cur = cur + pre[r+1] - pre[i];
                    break;
                }
                else
                {
                    cur = cur + len;
                }
            }
            ans.push_back(cur);
        }
        return ans;
    }
};
```

### Expected behavior

Expected - TLE
Actual - Accepted

**Comment by shreyg-upta** [comment]
Also, the code of everyone whose code has passed in this contest should be rerun on this test case, since ratings are not out yet

**Comment by luciphania** [comment]
Hello there,

Thanks for reaching out!

Can you please share your test case in  .txt file?

Best,
LeetCode Support Team

**Comment by luciphania** [comment]
Hello, 

Your reported issue has been relayed to our team for thorough investigation. We appreciate your patience as we work to address and resolve this matter. We will reach out to you when we have updates regarding the issue. 

If you have any further questions or concerns in the meantime, please feel free to let us know. 

Best regards, 
LeetCode Support Team

**Comment by shreyg-upta** [comment]
Hi,  
Will all the accepted codes in the contest be re-run against new test cases to maintain fair rankings in the contest?
