### ISSUE TITLE
Missing Test Case - 53. Maximum Subarray

### ISSUE THREAD

**Issue by elliptic1** [LeetCode-Feedback/LeetCode-Feedback#2358]
#### Your LeetCode username
elliptic1

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Example

#### Description of the bug
All examples have only one element in the array and that element is the solution. Need better examples.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@elliptic1 Please refer to example 1 for inputs with more than 1 element or the discuss section for other explanations from our users. Thank you for your time.
