### ISSUE TITLE
Missing Test Case - 1509. Minimum Difference Between Largest and Smallest Value in Three Moves

### ISSUE THREAD

**Issue by Abhi568** [LeetCode-Feedback/LeetCode-Feedback#2359]
[Sir]([url](url)) in this question there is a bug , my slolution is :

nums.sort()
        if len(nums)==1:
            return nums[0]
        elif len(nums)==2 or len(nums)==3 or len(nums)===4 or nums[0]==nums[-1]:
            return 0
        else:
            max1=float('inf')
            nums1=nums[3:]
            if nums1!=[]:
                max1=max(nums1)-min(nums1)
            nums1=nums[:len(nums)-3]
            if nums1!=[]:
                max1=min(max1,max(nums1)-min(nums1))
            nums1=nums[1:len(nums)-2]
            if nums1!=[]:
                max1=min(max1,max(nums1)-min(nums1))
            nums1=nums[2:len(nums)-1]
            if nums1!=[]: 
                max1=min(max1,max(nums1)-min(nums1))
            return  max1

In the above question consider my first test case when len(nums)==1, the answer should be 0 but I am returning nums[0], which can be any value, maybe zero or may not be zero. When I Give the input in the console  (  [1] )  it gives me the correct output means Actual and expected are not matching but when I submit my code it successfully getting submitted.  

Fix it .

**Comment by lc-kay** [comment]
@Abhi568 Please provide the submission details link to your solution. Thank you!

**Comment by lc-kay** [comment]
Hi @Abhi568 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
