### ISSUE TITLE
Wrong solution accepted

### ISSUE THREAD

**Issue by toxeed** [LeetCode-Feedback/LeetCode-Feedback#236]
** 236 Lowest Common Ancestor of a Binary Tree**
**The code you submit/run**

```
public TreeNode lowestCommonAncestor(TreeNode root, TreeNode p, TreeNode q) {
        if(root==null)
            return null;
        if(root.val == p.val || root.val == q.val){
            return root;
        }
        
        TreeNode left = lowestCommonAncestor(root.left, p, q);
        TreeNode right = lowestCommonAncestor(root.right, p, q);
        
        if(left != null && right != null){
            return root;
        }
        else if(left !=null){
            return left;
        } else if(right != null){
            return right;
        }else{
            return null;
        }
    }
```
- Java

This solution should return null if one of the nodes is not present int tree but it returns the one present. For example in the tree [3,5,1,6,2,0,8,null,null,7,4] if we pass 5, 9 the solution returns 5 which is not right but this is an accepted solution.

**what language is your code written in**
JAVA

**Expected behavior**
This testcase should be handled

**Comment by CooperCooperCooper** [comment]
Hi @toxeed ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @toxeed ,
Thank you for your time. Your submission is missing this constraint: 

> p and q are different and both values will exist in the binary tree.

Please update it accordingly. We appreciate your support.
