### ISSUE TITLE
Missing Test Case - 1342. Number of Steps to Reduce a Number to Zero

### ISSUE THREAD

**Issue by antonio081014** [LeetCode-Feedback/LeetCode-Feedback#2360]
#### Your LeetCode username

antonio081014

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Add one more test case: 
num = 0

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior

function result should return 0.

**Comment by lc-kay** [comment]
@antonio081014 Please provide the code that this custom test case failed on. Thank you!

**Comment by antonio081014** [comment]
[Code from Forum on LC](https://leetcode.com/problems/number-of-steps-to-reduce-a-number-to-zero/discuss/556101/swift-Loopless-O(1)-one-liner)

```
     func numberOfSteps (_ num: Int) -> Int {
        return num.bitWidth - num.leadingZeroBitCount + num.nonzeroBitCount - 1
    }
```

**Comment by antonio081014** [comment]
When `num = 1` the function should return 0 as the result, but this piece of accepted code will return -1.

**Comment by lc-kay** [comment]
@antonio081014 The code you provided already receives Wrong Answer as it fails test case 203. Thank you for your time.
