### ISSUE TITLE
Bug in solution approach 2, problem 416 Partition Equal Subset Sum

### ISSUE THREAD

**Issue by peakbadger42** [LeetCode-Feedback/LeetCode-Feedback#2361]
#### Your LeetCode username

peakbadger42

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

For 416. Partition Equal Subset Sum, Solution Approach 2: Top Down Dynamic Programming - Memoization

The code provide in the solution fails on submission due to Time Limit Exceeded. This is because of the use of @functools.lru_cache as a decorator in Python 3, which has a default max size of 128 recent calls. This causes a timeout on larger test cases as earlier inputs are lost once we exceed 128 recursive calls. @functools.cache should be used instead, as it is equivalent to @functools.lru_cache(maxsize=None). Per the Python 3 docs: https://docs.python.org/3/library/functools.html#functools.cache

#### Code you used for Submit/Run operation

```
416. Partition Equal Subset Sum
class Solution:
    def canPartition(self, nums: List[int]) -> bool:
        @lru_cache
        def dfs(nums: Tuple[int], n: int, subset_sum: int) -> bool:
            # Base cases
            if subset_sum == 0:
                return True
            if n == 0 or subset_sum < 0:
                return False
            result = (dfs(nums, n - 1, subset_sum - nums[n - 1])
                    or dfs(nums, n - 1, subset_sum))
            return result

        # find sum of array elements
        total_sum = sum(nums)

        # if total_sum is odd, it cannot be partitioned into equal sum subsets
        if total_sum % 2 != 0:
            return False

        subset_sum = total_sum // 2
        n = len(nums)
        return dfs(tuple(nums), n - 1, subset_sum)
```

#### Language used for code

Python 3

#### Expected behavior

Solution should pass without failing due to Time Limit Exceeded

#### Additional context

Link to my attempted submission of the code: ### (Fails, Time Limit Exceeded)
https://leetcode.com/submissions/detail/455347605/

Link to a successful submission of the solution code with @lru_cache replaced with @cache ### (Succeeds)
https://leetcode.com/submissions/detail/455347982/

**Comment by lc-kay** [comment]
Hi @peakbadger42 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @peakbadger42 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
