### ISSUE TITLE
Missing Test Case - 28. Implement strStr()

### ISSUE THREAD

**Issue by ramdas03** [LeetCode-Feedback/LeetCode-Feedback#2362]

**Comment by lc-kay** [comment]
@ramdas03 Can you please provide the details of your report? Thank you!

**Comment by lc-kay** [comment]
Hi @ramdas03 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
