### ISSUE TITLE
面试题 01.04. 回文排列的英语题目描述需要更新

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#2363]
**你的 LeetCode 用户名**
stormsunshine

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
「[面试题 01.04. 回文排列](https://leetcode-cn.com/problems/palindrome-permutation-lcci)」的英语描述，palindrome 中间多了一个空格，请把空格去掉，使得这是一个单词。

**你使用的语言**
Java

**你提交或者运行的代码**

**期望行为**
更新英语题目描述，去掉空格。

**屏幕截图**
![image](https://user-images.githubusercontent.com/12067364/107839271-b4038500-6de5-11eb-81fa-eaf239762617.png)

**额外的上下文**

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
当前题目英文描述已更新，力扣会定期更新，保障稳定和体验优化。
