### ISSUE TITLE
[BUG] - for input "-1/2+1/-2" not showing expected outputs , for input : "-1/2+1/2+-1/3" code is not checked . Generally when there is '-' sign before no handling

### ISSUE THREAD

**Issue by pp-git-hub** [LeetCode-Feedback/LeetCode-Feedback#23641]
### LeetCode Username

pranjalpd06

### Problem Number, Title, and Link

592. Fraction Addition and Subtraction https://leetcode.com/problems/fraction-addition-and-subtraction/

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

code accepted 

but for input : "-1/2+-1/2"
code output :  "-1/2"
but expected : "-1/1"
so logically testcases are not there having '-' sign before any operand  in between (as my example)

also testcase say : "-1/2+1/2+-1/3"
should not submit but accepted 

output : "0/1"

expected : "-1/3"

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
class Solution {
public:
    string fractionAddition(string expression) {
        int numerator=0,denominator=1;
        int i=0;
        int n=expression.size();

        while(i<n){
            int sign=1;
            if(expression[i]=='+' || expression[i]=='-'){
                if(expression[i]=='-') sign=-1;
                i++;
            }

            int num=0;
            while(i<n && isdigit(expression[i])){
                num=num*10+(expression[i]-'0');
                i++;
            }
            num*=sign;
            i++;
            int den=0;
            while(i<n && isdigit(expression[i])){
                den=den*10+(expression[i]-'0');
                i++;
            }
            numerator=numerator*den+num*denominator;
            denominator*=den;

            int gcdVal=gcd(abs(numerator),denominator);
            numerator/=gcdVal;
            denominator/=gcdVal;

        }
        return to_string(numerator)+'/'+to_string(denominator);

    }
};
```

### Expected behavior

code accepted 

for (my test case) 
say input : "-1/2+-1/2"
my code outputs :  "-1/2"
but expected : "-1/1"

so some testcases are not handled and code gets accepted 

### Screenshots

![leecodeerror](https://github.com/user-attachments/assets/1838a99a-344b-4298-b6b8-6620417a73f6)

**Comment by ConeDragon** [comment]
Technically not allowed testcase because they are `±numerator/denominator` and are in range `[1, 10]` so you can't have +-fraction

**Comment by pp-git-hub** [comment]
What about 

> Technically not allowed testcase because they are `±numerator/denominator` and are in range `[1, 10]` so you can't have +-fraction

**Comment by pp-git-hub** [comment]
but it should say that it's invalid input.
