### ISSUE TITLE
Missing Test Case - 108. Convert Sorted Array to Binary Search Tree

### ISSUE THREAD

**Issue by Akatsuki06** [LeetCode-Feedback/LeetCode-Feedback#2365]
#### Your LeetCode username
akatsuki06

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Compiler gives a **Wrong Answer** with the following test case `[-10,-6,-5,-4,-3,0,0,0,5,9]`
While the solution has been accepted on submission. Refer to screenshot.

#### Code you used for Submit/Run operation

```java
class Solution {
    public TreeNode sortedArrayToBST(int[] nums) {
            return insertToTree(nums,0,nums.length-1);
    }
    
    public TreeNode insertToTree(int[] nums, int st, int end){
        if(st>end)return null;
        int mid = st + (end-st)/2;        
        TreeNode node = new TreeNode();
        node.val = nums[mid]; 
        node.left = insertToTree(nums,st,mid-1);   
        node.right = insertToTree(nums,mid+1,end);
        return node;
    }
}
```

#### Language used for code
JAVA

#### Expected behavior
The custom test case should be added  and  not shown as wrong answer.

#### Screenshots
![image](https://user-images.githubusercontent.com/16136908/107855214-0628c280-6e47-11eb-810e-3cf42dfc9341.png)

**Comment by lc-kay** [comment]
Hi @Akatsuki06 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Akatsuki06 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
