### ISSUE TITLE
Missing Test Case - 79. Word Search

### ISSUE THREAD

**Issue by mohamed-sameh-khalil** [LeetCode-Feedback/LeetCode-Feedback#2366]
#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language

#### Description of the bug

This testcase fails in the judge and in my accepted solution with time limit exceeded:
```
[["A","A","A","A","A","A"],["A","A","A","A","A","A"],["A","A","A","A","A","A"],["A","A","A","A","A","A"],["A","A","A","A","A","A"],["A","A","A","A","A","A"]]
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB"

```
test case description: 
the grid is 6*6 and consists of the character  'A' 36 times. the word is 35 'A's followed by 1 'B' which satisfy the problem constraints.

#### Code you used for Submit/Run operation

```
class Solution {
    vector<vector<int>> visited;
    string word;
    int n,m;
    int len;
    bool dfs(int i, int x, int y, vector<vector<char>>& board){
        if(x < 0 || x >= n || y < 0 || y >= m || visited[x][y])return 0;
        if(i == len - 1)return word[i] == board[x][y];
        if(word[i] != board[x][y]) return 0;
        visited[x][y] = 1;
        if(dfs(i+1,x+1,y,board))return 1;
        if(dfs(i+1,x-1,y,board))return 1;
        if(dfs(i+1,x,y-1,board))return 1;
        if(dfs(i+1,x,y+1,board))return 1;
        visited[x][y] = 0;
        return 0;
    }
public:
    bool exist(vector<vector<char>>& board, string word) {
        this-> word = word;
        len = word.size();
        n = board.size(), m = board[0].size();
        visited.resize(n,vector<int>(m,0));
        for(int i = 0; i < n; i++){
            for(int j = 0; j < m; j++){
                if(dfs(0,i,j,board))
                    return 1;
            }
        }
        return 0;
    }
};
```

#### Language used for code
C++

#### Expected behavior

I expected smaller constraints for this problem as any test case that is similar to the test case I supplied will also fail. This can lead to someone not trying to solve using dfs because of thinking of this testcase even though dfs is the expected method to solve this question.

#### Additional context

The reason the judge's solution fails this test case is that the used solution has worst case runtime of O(n*m*4^k) where k is the length of word. of course the worst case scenario (which I supplied) is never tried in the judge's testcases but this is not clear in the description.

**Comment by lc-kay** [comment]
Hi @mohamed-sameh-khalil 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@mohamed-sameh-khalil Our team is still reviewing this report. Thank you for your patience.

**Comment by lc-kay** [comment]
Hi @mohamed-sameh-khalil 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. The problem was updated and this test case is not allowed as a contribution now. We appreciate your support!
