### ISSUE TITLE
Missing Test Case - 1171. Shortest Path in Binary Matrix

### ISSUE THREAD

**Issue by nipun1104** [LeetCode-Feedback/LeetCode-Feedback#2367]
#### Your LeetCode username
n_i_p_u_n

#### Category of the bug
[ ✔️] Question
[✔️ ] Solution
- [ ] Language

#### Description of the bug
There is missing test case where if we don't include direction (-1,-1) in the code, it is getting accepted.
The code gives wrong answer for this test case : [[0,1,1,0,0,0],[0,1,0,1,1,0],[0,1,1,0,1,0],[0,0,0,1,1,0],[1,1,1,1,1,0],[1,1,1,1,1,0]]
However, the code is getting accepted when we submit the code
#### Code you used for Submit/Run operation

```
class Solution {
    public int shortestPathBinaryMatrix(int[][] grid) {
        int n = grid.length;
        Queue<Node> queue = new LinkedList();
        if(grid[0][0] == 0){
            grid[0][0] = 1;
            queue.add(new Node(0,0));
        }
        int[][] directions = new int[][]{{-1,0},{-1,1}, {0,1}, {1,1},{1,0},{1,-1},{0,-1}};
        while(!queue.isEmpty()){
            Node node = queue.poll();
            if(node.x==n-1 && node.y==n-1){
                return grid[n-1][n-1];
            }
            for(int[] dir : directions){
                int row = dir[0] + node.x;
                int col = dir[1] + node.y;
                if(row>=0 && row<n && col>=0 && col<n && grid[row][col] == 0){
                    grid[row][col] = grid[node.x][node.y] +1;
                    queue.add(new Node(row,col));
                }
            }
        }
        return -1;
    }
    
    public class Node {
        int x;
        int y;
        public Node(int x, int y){
            this.x = x;
            this.y = y;
        }
    }
}
```

#### Language used for code
Java

#### Expected behavior
The code should not be accepted as it gives wrong answer for the below test case:
[[0,1,1,0,0,0],[0,1,0,1,1,0],[0,1,1,0,1,0],[0,0,0,1,1,0],[1,1,1,1,1,0],[1,1,1,1,1,0]]

**Comment by lc-kay** [comment]
Hi @nipun1104 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @nipun1104 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
