### ISSUE TITLE
Missing Test Case - 1421. Find Numbers with Even Number of Digits

### ISSUE THREAD

**Issue by ujjwala-sinha** [LeetCode-Feedback/LeetCode-Feedback#2368]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by ujjwala-sinha** [comment]
its does not evaluate for negative number in array

**Comment by lc-kay** [comment]
@ujjwala-sinha Per the constraints 1 <= nums[i] <= 10^5, negative numbers are not valid. Thank you for your time.
