### ISSUE TITLE
[BUG] - 缺少测试用例

### ISSUE THREAD

**Issue by KODtheone** [LeetCode-Feedback/LeetCode-Feedback#23687]
### LeetCode 用户名

ハート

### 问题号码、标题和链接

3265. 统计近似相等数对 I     https://leetcode.cn/problems/count-almost-equal-pairs-i/description/

### Bug Category

缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*

### 描述

此题缺少一个case: [1,1000000]
结果为0的程序也可以通过

### 你使用的语言

Python/Python3

### 你提交或者运行的代码

```bash
class Solution:
    def countPairs(self, nums: List[int]) -> int:
        def s1(x):
            b = 6
            sa = str(x).zfill(b)
            ans = set([sa])
            for i in range(b):
                for j in range(i + 1, b):
                    nx = sa[:i] + sa[j] + sa[i + 1:j] + sa[i] + sa[j + 1:]
                    ans.add(nx)
            return ans

        c = defaultdict(set)
        n = len(nums)
        ans = 0
        for i in range(n):
            ans += len(c[str(nums[i]).zfill(6)])
            res = s1(nums[i])
            for x in res:
                c[x] |= {i}
        # print(c)
        return ans
```

### 期望行为

应该是错误的, 但通过了

### 屏幕截图

![image](https://github.com/user-attachments/assets/684550d3-86ca-434a-8408-4205402230eb)

**Comment by luciphania** [comment]
Hello there,

Thank you for getting in touch with us. To help us better assess and replicate the issue, could you please provide the following details:

The code that was accepted during submission but fails on the missing test cases, as the code provided resulted in a wrong answer upon both running and submission.
The specific test case you'd like to contribute.
We appreciate your time and support. If you have any other questions, feel free to reach out.

Best regards,
LeetCode Support Team

**Comment by KODtheone** [comment]
The code:  https://leetcode.cn/problems/count-almost-equal-pairs-i/submissions/558429467/
```
class Solution:
    def countPairs(self, nums: List[int]) -> int:
        def s1(x):
            b = 6
            sa = str(x).zfill(b)
            ans = set([sa])
            for i in range(b):
                for j in range(i + 1, b):
                    nx = sa[:i] + sa[j] + sa[i + 1:j] + sa[i] + sa[j + 1:]
                    ans.add(nx)
            return ans

        c = defaultdict(set)
        n = len(nums)
        ans = 0
        for i in range(n):
            ans += len(c[str(nums[i]).zfill(6)])
            res = s1(nums[i])
            for x in res:
                c[x] |= {i}
        # print(c)
        return ans
```
The case:
[1,1000000]

BTW, fixed now.
