### ISSUE TITLE
面试题 16.09. 运算的英语描述需要更新

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#2369]
**你的 LeetCode 用户名**
stormsunshine

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
「[面试题 16.09. 运算](https://leetcode-cn.com/problems/operations-lcci)」的英语描述，第一个单词拼写错误，应为Write，请改正。

**你使用的语言**
Java

**你提交或者运行的代码**

**期望行为**
更新英语题目描述，改正拼写错误。

**屏幕截图**
![image](https://user-images.githubusercontent.com/12067364/107866011-75ce9a00-6ea7-11eb-828b-49f927d8da73.png)

**额外的上下文**

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前题目英文描述已更新，力扣会定期更新，保障稳定和体验优化。
