### ISSUE TITLE
Time Limit for Minimum Area Rectangle Should Be Fixed.

### ISSUE THREAD

**Issue by MoustafaMahmoud769** [LeetCode-Feedback/LeetCode-Feedback#237]
**What kind of the bug**
- solution

**Describe the bug**
The time limit for this problem is very tight. My N^2 sometimes passes and sometimes not.

**what language is your code written in**
C++

**The code you submit/run**
```
class Solution {
private:
    
public:
    int minAreaRect(vector<vector<int>>& points) {
        int ret = 2e9, n = points.size();
        set<pair<int, int>> pts;
        for (auto &p : points) pts.insert({p[0], p[1]});
        for (int i = 0; i < n; ++i) {
            for (int j = i + 1; j < n; ++j) {
                if (points[i][0] == points[j][0] || points[i][1] == points[j][1]) continue;
                if (pts.count({points[i][0], points[j][1]}) && pts.count({points[j][0], points[i][1]}))
                    ret = min(ret, abs(points[i][0] - points[j][0]) * abs(points[i][1] - points[j][1]));
            }
        }
        return ret == 2e9 ? 0 : ret;
    }
};
```

**Expected behavior**
It should pass.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by CooperCooperCooper** [comment]
Hi @MoustafaMahmoud769 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @MoustafaMahmoud769 ,

Thank you for your time. We were unable to reproduce this issue on our end. If the issue persists or occurs again, please don't hesitate to tag me here again. We appreciate your support.
