### ISSUE TITLE
【一个图中连通三元组的最小度数】题面描述歧义

### ISSUE THREAD

**Issue by Arsenal591** [LeetCode-Feedback/LeetCode-Feedback#2370]
**你的 LeetCode 用户名**
Arsenal-591（https://leetcode-cn.com/u/arsenal-591/）

**Bug 类型**
- [x] 题目

**描述**
原题中「一个顶点在三元组内，而另一个顶点不在三元组内」的描述不甚准确。

根据测试用例，此句想要表达的含义是「一个顶点在某个三元组内，另一个顶点不在**这个**三元组内」。然而，另一种合理的理解是「一个顶点在某个三元组内，另一个顶点不在**任何一个**三元组内」。

且从题目给出的两个示例，均无法发现这一点。（也就是说，无论采取何种理解，对于两个示例得到的答案是一样的）

基于此，建议修改题目描述，并考虑不计入此次竞赛的排名。

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，由于该题「一个顶点在某个三元组内，另一个顶点不在任何一个三元组内」这一种理解与示例 2 的解释 [2,5,6]、[5,6,7] 的度数不符， 因此本场比赛依旧计入排名。
​对于题面描述不够准确的问题，目前更新为 「一个顶点在这个三元组内，而另一个顶点不在这个三元组内」，力扣团队会努力做好未来竞赛的相关工作，感谢支持力扣。
