### ISSUE TITLE
Implement strStr() Expects incorrect result

### ISSUE THREAD

**Issue by yegamble** [LeetCode-Feedback/LeetCode-Feedback#2371]
Leetcode username: yegamble

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

In 28. Implement strStr() I used regex to verify if needle is contained in haystack. In the test case with haystack as "aaa" and needle is "a". The test is expecting the function to return 0, meaning that the haystack was empty.

#### Code you used for Submit/Run operation

```
import java.util.regex.Pattern;
import java.util.regex.Matcher;

class Solution {
    public int strStr(String haystack, String needle) {
        
        int i = -1;
        
        String pattern = needle;
        
        Pattern p = Pattern.compile(pattern);
        Matcher m = p.matcher(haystack);
        
        if (needle.length() <= 0){
            return 0; //needle is empty
        }else if(m.find()){
            return 2; //needle is found
        } else {
            return -1; //needle is not found
        }
    }
}
```

#### Language used for code
Java

#### Expected behavior

The expected result of the test should be 2 because the needle is contained in the haystack, and the haystack is not empty.

#### Screenshots

<img width="539" alt="image" src="https://user-images.githubusercontent.com/9465387/107867770-6de01b80-6ee2-11eb-99af-7c5718e0dd3c.png">

<img width="539" alt="image" src="https://user-images.githubusercontent.com/9465387/107867828-11313080-6ee3-11eb-899c-ed99b941f5e9.png">

**Comment by lc-kay** [comment]
@yegamble The expected output is correct. Please check out the discuss section for further explanations or to reference accepted solutions. https://leetcode.com/problems/implement-strstr/discuss/13333/Using-substring-API-simple-Java-Solution.-But-not-sure-why-failing-at-test-case-%22a%22-%22a%22 https://leetcode.com/problems/implement-strstr/discuss/386635/why-answer-is-not-1-but-0-for-this-test-case Thank you for your time.
