### ISSUE TITLE
Missing Test Case - 1647. Minimum Deletions to Make Character Frequencies Unique

### ISSUE THREAD

**Issue by tty111** [LeetCode-Feedback/LeetCode-Feedback#2372]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
Please provide the missing test case and code. Thank you!

**Comment by lc-kay** [comment]
Hi @tty111 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
