### ISSUE TITLE
Missing Test Case - 1760. Minimum Limit of Balls in a Bag

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#2373]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution is accepted but fails on the following test case:

[1760_tase_case.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/5977672/1760_tase_case.txt)

#### Code you used for Submit/Run operation

```
class Solution {
    public int minimumSize(int[] nums, int maxOperations) {
        long sum = 0;
        for (int n : nums) {
            sum += n;
        }

        int tmp = Math.max(1, (int)(sum / (nums.length + maxOperations)));

        for (int i=tmp; ; i++) {
            int totalOperations = 0;
            for (int j=0; j<nums.length; j++) {
                totalOperations += operations(nums[j], i);
                if (totalOperations > maxOperations) {
                    break;
                }

                if (j == nums.length - 1 && totalOperations <= maxOperations) {
                    return i;
                }
            }

        }
    }

    private int operations(int total, int target) {
        int tmp = total / target;
        int remain = total % target;
        if (remain == 0) {
            return tmp - 1;
        }

        return tmp;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/107876589-e324ff80-6e94-11eb-86db-2a42c7d7a44e.png)

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
