### ISSUE TITLE
Missing Test Case - 1662. Check If Two String Arrays are Equivalent

### ISSUE THREAD

**Issue by adeleid20092008** [LeetCode-Feedback/LeetCode-Feedback#23738]
### LeetCode Username

adeleidprogramer

### Problem Number, Title, and Link

https://leetcode.com/problems/check-if-two-string-arrays-are-equivalent/

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

my code is correct and i visualize it on python tutor and all my answer is correct but on leetcode the answer in task tow is wrong and this is bug in the site please tell me what can i do

### Language Used for Code

Python/Python3

### Code used for Submit/Run operation

```bash
class Solution:
    def arrayStringsAreEqual(self, word1, word2) -> bool:
        self.word1 = word1
        self.word2 = word2
        self.result = ''
        self.word_1 = ''
        self.word_2 =''
        for word in word1:
            self.word_1 += word
        for word in word2:
            self.word_2 += word
        if self.word_1 == self.word_2:
            return('true')
        else:
            return("false")
        # print(self.word_1, self.word_2)
```

### Expected behavior

i expect that my code will extract the right answer 

### Screenshots

![Screenshot 2024-08-28 063022](https://github.com/user-attachments/assets/e92032eb-37ef-4485-bc4e-c90f3ab0c7ee)
![Screenshot 2024-08-28 063022](https://github.com/user-attachments/assets/b4095ab6-8d49-4575-9578-512c90b7fb31)

**Comment by Ashu3208** [comment]
You are returning a string and the output expects a boolean value. Since the strings "True" and "false" are non-empty, they gets converted to true in boolean

**Comment by adeleid20092008** [comment]
i try both boolen and this way and found same problem

**Comment by Ashu3208** [comment]
The below code works fine. It's better to discuss these in the discussion form of leetcode rather than opening a issue. Even Chatgpt might have helped you to figure out the bug.
```
class Solution:
    def arrayStringsAreEqual(self, word1, word2) -> bool:
        self.word1 = word1
        self.word2 = word2
        self.result = ''
        self.word_1 = ''
        self.word_2 =''
        for word in word1:
            self.word_1 += word
        for word in word2:
            self.word_2 += word
        if self.word_1 == self.word_2:
            return True
        else:
            return False
```
