### ISSUE TITLE
Time Limit Exceeded - 24. Swap Nodes in Pairs

### ISSUE THREAD

**Issue by pan** [LeetCode-Feedback/LeetCode-Feedback#2374]
#### Your LeetCode username
radixtree

#### Category of the bug
- [ ] Question
- [ ] Solution
- [X] Language

#### Description of the bug

The ruby solution code runs well on my local machine but got 'Time Limit Exceeded' error while running with the same test case. 

#### Code you used for Submit/Run operation

```
def swap_pairs(head)
  prev_pair = ListNode.new(0, head)
  dummy = ListNode.new(0, prev_pair)
  nodea = next_pair = head
  while next_pair
    nodeb = nodea.next
    if nodeb
      next_pair = nodeb.next
      prev_pair.next = nodeb
      nodeb.next = nodea
      prev_pair = nodea
    else
      prev_pair.next = nodea
      next_pair = nil
    end
    nodea = next_pair
  end
  dummy.next.next
end
```

#### Language used for code

Ruby

#### Expected behavior

The time limit may be too short for ruby code. It should accept my ruby solution.

#### Additional context

Test case is [1,2,3,4]

**Comment by lc-kay** [comment]
@pan The time limit is reasonable for Ruby code. In addition, there are many accepted Ruby codes. Please check [this](https://leetcode.com/problems/swap-nodes-in-pairs/discuss/?currentPage=1&orderBy=most_relevant&query=ruby) out! Thank you for your time.
