### ISSUE TITLE
Missing Test Case - 1091. Shortest Path in Binary Matrix

### ISSUE THREAD

**Issue by KyleMcClay** [LeetCode-Feedback/LeetCode-Feedback#2375]
#### Your LeetCode username
@mcclay

#### Category of the bug
- Missing a test case

#### Description of the bug
Missing a test case which allows bad solutions to pass all test cases.

#### Code you used for Submit/Run operation
```python
# This code is accepted
# 02/14/2021 08:11	Accepted	564 ms	15 MB	python3
# it fails this test case
# [[0, 1, 0, 0, 0, 0],[0, 1, 0, 1, 1, 0],[0, 1, 1, 0, 1, 0],[0, 0, 0, 0, 1, 0],[1, 1, 1, 1, 1, 0],[1, 1, 1, 1, 1, 0]]

class Solution: 
    def shortestPathBinaryMatrix(self,grid):
        n = len(grid)
        if grid[0][0] or grid[n-1][n-1]:
            return -1
        q = [(0, 0, 1)]
        grid[0][0] = 1
        for i, j, d in q:
            if i == n-1 and j == n-1: return d
            for x, y in ((i-1,j),(i-1,j+1),(i,j-1),(i,j+1),(i+1,j-1),(i+1,j),(i+1,j+1)):
                if 0 <= x < n and 0 <= y < n and not grid[x][y]:
                    grid[x][y] = 1
                    q.append((x, y, d+1))
        return -1
```

#### Language used for code
Python 3

#### Expected behavior
this code does fail the testcase provided but passes all leetcode testcases

#### Screenshots
![leetcode testcase](https://user-images.githubusercontent.com/37460257/107882243-123f6f00-6e9d-11eb-9a4d-a664a3eaaa93.png)

#### Additional context
Missing test case:
[[0, 1, 0, 0, 0, 0],[0, 1, 0, 1, 1, 0],[0, 1, 1, 0, 1, 0],[0, 0, 0, 0, 1, 0],[1, 1, 1, 1, 1, 0],[1, 1, 1, 1, 1, 0]]

easy to read test case on why you have to be able move up and to the left -> (i-1,j-1)
[
0 1 0 0 0 0
0 1 0 1 1 0
0 1 1 0 1 0
0 0 0 0 1 0
]

**Comment by TheTypingType** [comment]
Nice to see that you filed a missing test case. I was just about to do the same!
Don't forget the case that tests whether the BFS searches upwards:
[
0 1 1 0 1
0 1 0 1 0
0 1 0 1 0
1 0 1 1 0
1 1 1 1 0
]
Removing (i-1,j) from the directions still passes LeetCode submission, but fails this test.

Here is another test case that shows that you have to be able to do all three: move up, left, and up and left
[
0 1 1 1 1 1 1 1
0 1 1 0 0 0 0 0
0 1 0 1 1 1 1 0 
0 1 0 1 1 1 1 0
0 1 1 0 0 1 1 0
0 1 1 1 1 0 1 0
0 0 0 0 0 1 1 0
1 1 1 1 1 1 1 0
]

This test case gives the wrong result (-1) if any of 
[(i-1, j-1), (i, j-1), (i-1,j)]
are removed from the directions (i.e. the BFS does not explore left, up, or up-left directions).
However, the code still passes LeetCode submission with any or all of these directions removed:

**Code used for Submit / Run:**
```
# code is accepted
# 02/14/2021 13:43 | Accepted | 484 ms | 15.2 MB | python3
# but fails additional test cases:
# [[0,1,1,0,1],[0,1,0,1,0],[0,1,0,1,0],[1,0,1,1,0],[1,1,1,1,0]]
# [[0,1,1,1,1,1,1,1],[0,1,1,0,0,0,0,0],[0,1,0,1,1,1,1,0],[0,1,0,1,1,1,1,0],[0,1,1,0,0,1,1,0],[0,1,1,1,1,0,1,0],[0,0,0,0,0,1,1,0],[1,1,1,1,1,1,1,0]]
class Solution: 
    def shortestPathBinaryMatrix(self,grid):
        n = len(grid)
        if grid[0][0] or grid[n-1][n-1]:
            return -1
        q = [(0, 0, 1)]
        grid[0][0] = 1
        for i, j, d in q:
            if i == n-1 and j == n-1: return d
            for x, y in ((i-1,j+1),(i,j+1),(i+1,j-1),(i+1,j),(i+1,j+1)):  # limited set of directions (no up, left, or up-left)
                if 0 <= x < n and 0 <= y < n and not grid[x][y]:
                    grid[x][y] = 1
                    q.append((x, y, d+1))
        return -1
```

So I would also add the following two cases:

**Additional Missing Test Cases:**
1 (up): [[0,1,1,0,1],[0,1,0,1,0],[0,1,0,1,0],[1,0,1,1,0],[1,1,1,1,0]]
2 (up, left, and up-left): [[0,1,1,1,1,1,1,1],[0,1,1,0,0,0,0,0],[0,1,0,1,1,1,1,0],[0,1,0,1,1,1,1,0],[0,1,1,0,0,1,1,0],[0,1,1,1,1,0,1,0],[0,0,0,0,0,1,1,0],[1,1,1,1,1,1,1,0]]

**Comment by lc-kay** [comment]
@TheTypingType @KyleMcClay 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@TheTypingType @KyleMcClay The test case set was recently updated from earlier contributions, and your solution now fails. Therefore, we will not be adding the reported missing test cases. Thank you for understanding.
