### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by MarcosAdro** [LeetCode-Feedback/LeetCode-Feedback#23756]
### LeetCode Username

gvHwoqp6h1

### Problem Number, Title, and Link

https://leetcode.com/problems/two-sum/

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

A test case where the solution is not exactly on the next number might infer the correct expectation

### Language Used for Code

Java

### Code used for Submit/Run operation

```bash
class Solution {
    public int[] twoSum(int[] nums, int target) {
        var result = new int[2];

        for(int i = 0 ; i < nums.length - 1 ; i++) {
            if(nums[i] + nums[i+1] == target) {
                result[0] = i;
                result[1] = i+1;
                break;
            }
        }

        return result;
    }
}
```

### Expected behavior

This code has all the test cases running successfully, however (and according with the problem itself) the answer might not always be in the next index. Meaning, all the test cases have the correct answer in the next index and the problem context does not state that it is a requirement.

### Additional context

The following test case (or a similar one) should be added:
nums = [2,5,7,11,15]
target = 9
expected output = [0,2]

**Comment by mbw8421** [comment]
I was going to raise this same issue, a python implementation of the similar logic also passes all tests but does not handle noncontiguous numbers.

```
class Solution:
    def twoSum(self, nums: List[int], target: int) -> List[int]:
        for i in range(len(nums) - 1):
            current_value = nums[i]
            next_value = nums[i + 1]
            if current_value + next_value == target:
                return [i, i + 1]
        return []
```

Additionally I have also run the above Java code and it also still passes all 3 provided test cases.
