### ISSUE TITLE
Inconsistence between problem statement and Examples - 81. Search in Rotated Sorted Array II

### ISSUE THREAD

**Issue by Blizter** [LeetCode-Feedback/LeetCode-Feedback#2376]
#### Your LeetCode username

Blizter

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

There is a difference between expected output in the problem statement and the examples (check provided screenshots). Are the indices our a boolean required? Consistence between problem statement and examples, is important to understand the problem efficiently!

#### Code you used for Submit/Run operation

Not applicable

#### Language used for code
Not applicable

#### Expected behavior

Consistence between expected outputs in problem statements and examples.

#### Screenshots

![image](https://user-images.githubusercontent.com/17797737/107884630-061ad800-6ec4-11eb-8fbb-8414d33385ca.png)

#### Additional context

Not applicable

**Comment by lc-kay** [comment]
@Blizter The problem statement has been recently updated and the issue you raised is no longer valid. Thank you for your time.
