### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by amal555** [LeetCode-Feedback/LeetCode-Feedback#23778]
### LeetCode Username

amalbaby

### Problem Number, Title, and Link

https://leetcode.com/problems/two-sum

### Bug Category

Problem examples

### Bug Description

Completed

### Language Used for Code

Python/Python3

### Code used for Submit/Run operation

```bash
class Solution(object):
    def twoSum(self, nums, target):
        """
        :type nums: List[int]
        :type target: int
        :rtype: List[int]
        """
        new_list=[]
        for i in range(len(nums)):
            for j in range(i+1,len(nums)):
                if nums[i]+nums[j]==target:
                    new_list.append(i)
                    new_list.append(j)
                else:
                    break
        print("Hi")
        print(new_list)
a = Solution()
a.twoSum([3,3],6)
```

### Expected behavior

Input: nums = [2,7,11,15], target = 9
Output: [0,1]
Explanation: Because nums[0] + nums[1] == 9, we return [0, 1].

**Comment by elshod1018** [comment]
Best regards
