### ISSUE TITLE
Missing Test Case - 420. Strong Password Checker

### ISSUE THREAD

**Issue by BhatnagarKshitij** [LeetCode-Feedback/LeetCode-Feedback#2377]
#### Your LeetCode username

# kshitijb

#### Category of the bug
-  Question

#### Description of the bug

Lets assume the given password is "aaaB1".
Size of the given password is 5.
Now to make it strong password, we need 2 changes to be accommodate ,
1. Add one more Character in the end of String to satisfy Length Condition.
2. Replace "aaa" with "aaA" to remove consecutive occurrence of character 'a'.

So minimum number of changes required to satisfy Strong Password is 2.
But Test Cases shows up to be 1.
#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
Hi @BhatnagarKshitij 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@BhatnagarKshitij The expected output is correct. "aaaB1" -> "aBaaB1", is only one operation. Thank you for your time.
