### ISSUE TITLE
Missing Test Case - 2699. Modify Graph Edge Weights

### ISSUE THREAD

**Issue by Rohanpithadiya** [LeetCode-Feedback/LeetCode-Feedback#23781]
### LeetCode Username

ropithad

### Problem Number, Title, and Link

https://leetcode.com/problems/modify-graph-edge-weights/?envType=daily-question&envId=2024-08-30

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

correct ans is throwing error saying wrong answer with the tase case:

4
[[0,1,-1],[2,0,2],[3,2,6],[2,1,10],[3,0,-1]]
1
3
12

my code Output
[[3,0,11],[3,2,6],[2,1,10],[2,0,2],[0,1,1]]

and
Expected
[[0,1,11],[2,0,2],[3,2,6],[2,1,10],[3,0,1]]

both should be valid ans. 

it looks like i am gonna failed my daily leetcode challenge. :(

### Language Used for Code

None

### Code used for Submit/Run operation

```bash
class Solution {

    vector<pair<int,int>> dijkstra(int n, vector<vector<pair<int,int>>> adjList, int source, bool allowed){
        vector<pair<int,int>> dist(n,{INT_MAX,0});
        dist[source] = {0,-1}; // dist, parent

        priority_queue<pair<int,int>, vector<pair<int,int>>, greater<pair<int,int>>> pq;
        pq.push({0,source}); // wight, node
        while(!pq.empty()){
            auto [cw, cn] = pq.top(); pq.pop();
            for(auto [d,w] : adjList[cn]){
                if(w == -1){
                    w = allowed?1:10000000;
                }
                if(dist[d].first > dist[cn].first+abs(w)){
                    dist[d].first = dist[cn].first+abs(w);
                    dist[d].second = cn;
                    pq.push({dist[d].first, d});
                }
            }
        }
        return dist;
    }
public:
        // do dijksta with set -1 to 1 and check if path value is less then target
        // and if any -1 exist in that path
    vector<vector<int>> modifiedGraphEdges(int n, vector<vector<int>>& edges, int source, int destination, int target) {
        vector<vector<int>> res;
        vector<vector<pair<int,int>>> adjList(n);
        unordered_map<int,unordered_map<int,int>> edgesMap;
        for(int i=0; i<edges.size(); i++){
            adjList[edges[i][0]].push_back({edges[i][1], edges[i][2]});
            adjList[edges[i][1]].push_back({edges[i][0], edges[i][2]});
            edgesMap[edges[i][0]][edges[i][1]] = edges[i][2];
        }
        vector<pair<int,int>> dist = dijkstra(n, adjList, source, false);
        if(dist[destination].first < target) return res;
        dist = dijkstra(n, adjList, source, true);

        bool isNeg = false;
        vector<pair<int,int>> negEdge;
        if(dist[destination].first <= target){
            int diff = target-dist[destination].first;
            int child = destination;
            while(child != source){
                int parent = dist[child].second;
                if(edgesMap.count(parent) && edgesMap[parent].count(child) && edgesMap[parent][child] == -1){
                    edgesMap[parent][child] = 1+diff;
                    diff = 0;
                    isNeg = true;
                }
                if(edgesMap.count(child) && edgesMap[child].count(parent) && edgesMap[child][parent] == -1){
                    edgesMap[child][parent] = 1+diff;
                    diff = 0;
                    isNeg = true;
                }

                child = parent;
            }
            if(isNeg){
                for(auto &[s,dm] : edgesMap){
                    for(auto &[d, w] : dm){
                        if(w == -1){
                            w = 10000000;
                        }
                        res.push_back({s,d,w});
                    }
                }
            }
        }
        return (res);
    }
};
```

### Expected behavior

it should accept answer generated by my code.

### Screenshots

![Screenshot 2024-08-30 at 19 17 04](https://github.com/user-attachments/assets/5b7e9b38-b164-4347-bc7c-d6d7af62218f)

**Comment by Sqaard** [comment]
hey, I have the same problem )

**Comment by Sqaard** [comment]
but your test case with my code runs without errors

**Comment by Rohanpithadiya** [comment]
@Sqaard what i am proposing here is that only..
both should be valid answer
[[3,0,11],[3,2,6],[2,1,10],[2,0,2],[0,1,1]]
[[0,1,11],[2,0,2],[3,2,6],[2,1,10],[3,0,1]]
but leetcode is failing on [[3,0,11],[3,2,6],[2,1,10],[2,0,2],[0,1,1]]

**Comment by Rohanpithadiya** [comment]
i dont understand what you trying to say...

can you just tell me if ` [[3,0,11],[3,2,6],[2,1,10],[2,0,2],[0,1,1]]` should be correct answer or not?

because i went through the problem description and no where it says.. you have to adjust the weights on the nearest -1 edge to source.
infact this is the exact line in the problem

> If there are multiple modifications that make the shortest distance between source and destination equal to target, any of them will be considered correct.

if path has multiple -1 edges, i can adjust weights to any of the -1 edges. (there is no condition to use only one -1 edge)

for example:
in about example: shortest path from 1 to 3 can be 
1> 1->0->2->3 with edges weight -1, 2, 6
2> 1->0->3 with edges wight -1,-1

so based upon this acceptable shortest path with 12 target should be
```
[[0,1,4],[2,0,2],[3,2,6],[2,1,10],[3,0,10000000]]

[[0,1,1],[2,0,2],[3,2,6],[2,1,10],[3,0,11]]
[[0,1,11],[2,0,2],[3,2,6],[2,1,10],[3,0,1]]

[[0,1,2],[2,0,2],[3,2,6],[2,1,10],[3,0,10]]
[[0,1,10],[2,0,2],[3,2,6],[2,1,10],[3,0,2]]

[[0,1,3],[2,0,2],[3,2,6],[2,1,10],[3,0,9]]
[[0,1,9],[2,0,2],[3,2,6],[2,1,10],[3,0,3]]
.... and so on
```
P.S. assuming order of elements inside ans array does not matter.

 i would appreciate if you can clarify my doubts with some proof, rather then with generic statements.

**Comment by Rohanpithadiya** [comment]
@Epiphania_Ekenimoh 

please look at the screenshot i have attached, even you/leetcode suggest the same path in expected answer. i.e. 1->0->3,
its just i have put 11 weight on edge 3->0 while you have put 11 weight on 1->0.

and if you(expected answer) have put 11 weight on edge 1->0, weight of path 1->0->2->3 will be 11+6+3, which is not making upto target.
