### ISSUE TITLE
Missing Test Case - 801. Is Graph Bipartite?

### ISSUE THREAD

**Issue by lautalom** [LeetCode-Feedback/LeetCode-Feedback#2378]
#### Your LeetCode username
 
lautalom

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Program output is correct for a given test case, platform says it returns wrong answer, but it actually returns the expected answer.
Test case: {{1, 3}, {0, 2}, {1, 3}, {0, 2}}
Expected: True.
Returns: True.
Leetcode claims it returns false.
#### Code you used for Submit/Run operation

```
#include <iostream>
#include <bits/stdc++.h>
using namespace std;

short colores[100]; // colores[i] = color de v_i

class Solution
{
public:
    void colorear(int v, int c)
    {
        if (!colores[v])
            colores[v] = c;
    }
    bool isBipartite(vector<vector<int>> &graph)
    {
        bool ans = true;
        for (int i = 0; i < graph.size() && ans; i++)
        {
            colorear(i, i % 2 + 1);
            int current = colores[i];
            for (auto j = graph[i].begin(); ans && j != graph[i].end(); j++)
            {
                colorear(*j, (current)% 2 + 1);
                if (colores[*j] == current)
                    ans= !ans;
                //cout << "vector " << i << ", item: "<< *j << ", color:" <<colores[*j]<< endl;
            }
        }
        return ans;
    }
};

```

#### Language used for code

C++

#### Expected behavior

Tested the test case locally, it returns expected output, but platform says it does not!

**Comment by lc-kay** [comment]
Hi @lautalom 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
