### ISSUE TITLE
Missing Test Case - 88. Merge Sorted Array

### ISSUE THREAD

**Issue by nalanqingcheng** [LeetCode-Feedback/LeetCode-Feedback#23780]
### LeetCode 用户名

小刘同学

### 问题号码、标题和链接

88. 合并两个有序数组 https://leetcode.cn/problems/merge-sorted-array/description/?envType=study-plan-v2&envId=top-interview-150

### Bug Category

问题描述

### 描述

主循环的条件是 i >= 0 && j >= 0，如果写错成 i > 0 && j > 0，可能会导致在 i 或 j 为 0 时提前退出循环，没有正确处理剩余的元素。
在将元素放入 nums1 的过程中，如果先减指针再赋值，可能会导致错误的结果或者数组越界。例如，如果写成 nums1[k] = nums1[i]; i--; k--;，在 i 为 0 时，会先将 i 减为 -1，然后再尝试访问 nums1[-1]，导致错误。应该先赋值再减指针。

### 你使用的语言

Java

### 你提交或者运行的代码

```bash
class Solution {
    public void merge(int[] nums1, int m, int[] nums2, int n) {
        int i = m - 1;
        int j = n - 1;
        int k = m + n - 1;

        while (i >= 0 && j >= 0) {
            if (nums1[i] > nums2[j]) {
                nums1[k--] = nums1[i--];
            } else {
                nums1[k--] = nums2[j--];
            }
        }

        while (j >= 0) {
            nums1[k--] = nums2[j--];
        }
    }
}
```

### 期望行为

互相学习

### 屏幕截图

![image](https://github.com/user-attachments/assets/09a5baec-08c6-4908-8539-52c532eef372)

### 额外的上下文

无

**Comment by amcones-lc** [comment]
感谢反馈，能否向我们补充测试用例，以及能够通过此题但无法通过所提供的测试用例的代码，把信息提供完整才能有助于快速验证和精准的定位，谢谢。
