### ISSUE TITLE
[BUG] - LeetCode Problem of the Day not getting marked as completed on submission

### ISSUE THREAD

**Issue by PrashantNigam** [LeetCode-Feedback/LeetCode-Feedback#23796]
### LeetCode Username

prashant404

### Problem Number, Title, and Link

1514. Path with Maximum Probability https://leetcode.com/problems/path-with-maximum-probability/

### Bug Category

Problem description, Editorial

### Bug Description

Problem of the Day for August 31, 2024 is not getting marked as completed on submission. I tried this multiple times and the result remains the same. 
Also, not sure but highly likely that it's a bug, that this problem was asked 3 days ago (August 27, 2024). Problems don't get repeated so quickly.

Here's my latest submission link: https://leetcode.com/submissions/detail/1373686209/
Here's the problem still showing as not-solved:
![image](https://github.com/user-attachments/assets/632e75fa-5051-4345-b7d6-9e6e31787272)

### Language Used for Code

Java

### Code used for Submit/Run operation

```bash
class Solution {
        private record Pair(int node, double probability) {
    }
    
    public double maxProbability(int n, int[][] edges, double[] succProb, int start, int end) {
        var graph = getAdjList(n, edges, succProb);
        var visited = new HashSet<Integer>();
        var maxHeap = new PriorityQueue<Pair>(Comparator.comparing(pair -> -pair.probability));
        maxHeap.add(new Pair(start, 1));

        while (!maxHeap.isEmpty()) {
            var pair = maxHeap.poll();
            visited.add(pair.node);

            if (pair.node == end)
                return pair.probability;

            for (var next : graph.get(pair.node))
                if (!visited.contains(next.node))
                    maxHeap.add(new Pair(next.node, pair.probability * next.probability));
        }

        return 0;
    }

    private Map<Integer, List<Pair>> getAdjList(int n, int[][] edges, double[] succProb) {
        var adjList = new HashMap<Integer, List<Pair>>();

        for (var i = 0; i < n; i++)
            adjList.put(i, new ArrayList<>());

        for (var i = 0; i < edges.length; i++) {
            var edge = edges[i];
            adjList.get(edge[0]).add(new Pair(edge[1], succProb[i]));
            adjList.get(edge[1]).add(new Pair(edge[0], succProb[i]));
        }

        return adjList;
    }
}
```
```


### Expected behavior

* The problem should be marked as solved on the daily problem calendar.
* Problems should not repeat within 3 days. This has never happened before.

### Screenshots

_No response_

### Additional context

_No response_

**Comment by vyrp** [comment]
> Problem of the Day for August 30, 2024 is not getting marked as completed on submission.

I think you meant _August 31_.

**Comment by PrashantNigam** [comment]
> > Problem of the Day for August 30, 2024 is not getting marked as completed on submission.
> 
> I think you meant _August 31_.

@vyrp Yes. I put today's date (Pacific Time). Fixed the date
