### ISSUE TITLE
Arrays 101: Typo in In-Place Array Operations Introduction Article

### ISSUE THREAD

**Issue by abhi2196** [LeetCode-Feedback/LeetCode-Feedback#238]
**What kind of the bug**
- [ ] problem
- [x] solution
- [ ] language

**Describe the bug**
The in-place implementation for our squareEven(...) function, references `result[i]` at line number 15 which should be `array[i]`

**what language is your code written in**
Java

**The code you submit/run**
```

public int[] squareEven(int[] array, int length) {

  // Check for edge cases.
  if (array == null) {
    return array;
  }

  // Iterate through the original array.
  for(int i = 0; i < length; i++) {

    // If the index is an even number, then we need to square the element
    // and replace the original value in the Array.
    if (i % 2 == 0) {
      result[i] *= result[i];
    }
    // Notice how we don't need to do *anything* for the odd indexes? :-)
  }

  // We just return the original array. Some problems on leetcode require you
  // to return it, and other's dont.
  return array;
}
```

**Screenshots**
<img width="1676" alt="Screenshot 2020-05-03 at 1 18 16 AM" src="https://user-images.githubusercontent.com/13404983/80889393-436afc00-8cdc-11ea-87a9-dd624ce26e74.png">

**Comment by CooperCooperCooper** [comment]
Hi @abhi2196 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @abhi2196 ,
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.

**Comment by pechinkin** [comment]
@lc-kate hi! code can be modified to run faster up to about 2 times.
while iteraring we can use `i += 2` instead of `i++`, thus we won't need to have a `if (i % 2 == 0)` condition, because it always would be even.
with this, we will proceed 2 times less laps in the for cycle
