### ISSUE TITLE
Problem Description - 774. Minimize Max Distance to Gas Station

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#2381]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
The description of the problem does not state that the array `stations` is already sorted. However, according to my submissions, sorting the array `stations` is unnecessary. Therefore, I suppose that the given array `stations` is already sorted.
Please refer to the code below, where I have commented the statement of sorting.
If the statement is NOT commented, the array `stations` is guaranteed to be sorted, so the code can pass all test cases. If the statement is commented, the code can also pass all test cases.
Therefore, the given array `stations` is guaranteed to be sorted. In problem description, it should be stated that `stations` is sorted. The fact that `stations` is sorted should be stated in both the first paragraph and the **Note** part.

#### Code you used for Submit/Run operation

```
class Solution {
    public double minmaxGasDist(int[] stations, int K) {
        // Arrays.sort(stations);
        int length = stations.length;
        double low = 0, high = stations[length - 1] - stations[0];
        while (high - low > 1e-6) {
            double mid = (low + high) / 2;
            int minStations = 0;
            for (int i = 1; i < length; i++) {
                minStations += (int) ((stations[i] - stations[i - 1]) / mid);
            }
            if (minStations <= K) {
                high = mid;
            } else {
                low = mid;
            }
        }
        return low;
    }
}
```

#### Language used for code
Java

#### Expected behavior
According to my description above, the given array `stations` is guaranteed to be sorted.
My expectation is that, in problem description, the fact that `stations` is sorted should be stated in both the first paragraph and the **Note** part.

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
