### ISSUE TITLE
Wrong implementation of Dijkstra's algorithm (including running time analysis).

### ISSUE THREAD

**Issue by f-fr** [LeetCode-Feedback/LeetCode-Feedback#23816]
### LeetCode Username

f-fr

### Problem Number, Title, and Link

1514. Path with Maximum Probability https://leetcode.com/problems/path-with-maximum-probability

### Bug Category

Editorial

### Bug Description

The implementation of Dijkstra's algorithm is wrong. In particular, the running time analysis of that specific implementation is wrong (it has O(n²) worst case running time). See my [comment](https://leetcode.com/problems/path-with-maximum-probability/editorial/comments/2600769) for a detailed explanation. 

### Language Used for Code

None

### Expected behavior

Corrected implementation of the algorithm including an improved running time analysis.

**Comment by flauts** [comment]
![gato](https://github.com/user-attachments/assets/915b0c9f-3b2b-4f73-9334-5de62d36d8d9)
