### ISSUE TITLE
Bug - 678. Valid Parenthesis String

### ISSUE THREAD

**Issue by yuenchiho** [LeetCode-Feedback/LeetCode-Feedback#2382]
#### Your LeetCode username
yuenchiho

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
The problem description states "_The string size will be in the range [1, 100]_", but the empty string "" is one of the test cases.

#### Code you used for Submit/Run operation
```
class Solution:
    def checkValidString(self, s: str) -> bool:
        n = len(s)
        dp = [[False]*n for i in range(n)]
        #Some dynamic programming
        return dp[0][n-1]
```

#### Language used for code
python3

#### Expected behavior
An input with n=len(s)>0, so no IndexError for return dp[0][n-1].

#### Additional context
If appropriate, can the empty string test case be removed and rejudge my submission (https://leetcode.com/submissions/detail/456274389/), so I won't get an unnecessary Runtime Error submission for following the problem description.

**Comment by lc-kay** [comment]
Hi @yuenchiho 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @yuenchiho 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
