### ISSUE TITLE
https://leetcode.com/explore/learn/card/linked-list/214/two-pointer-technique/1216/. Clearer Solution. 

### ISSUE THREAD

**Issue by SuguruChhaya** [LeetCode-Feedback/LeetCode-Feedback#2385]
#### Your LeetCode username

suguruchhaya@gmail.com

#### Category of the bug
- [ ] Question
- [X ] Solution
- [ ] Language

#### Description of the bug

A very small suggestion for the solution explanation on https://leetcode.com/explore/learn/card/linked-list/214/two-pointer-technique/1216/. In "1" in the "Complexity Analysis" section. There it explains "where M is the length of the cycle in the list." I found it easier if you instead said "where M is the length of **the nodes** in the cycle in the list." or something that explains what "length" is referring to better. Just a small improvement I guess...

**Comment by lc-kay** [comment]
Hi @SuguruChhaya 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@SuguruChhaya Our team has reviewed the article and removed this outdated article. For a better understanding of the solution, please visit https://leetcode.com/problems/linked-list-cycle/solution/ Thank you for your time.
