### ISSUE TITLE
Missing Test Case - 1455. Check If a Word Occurs As a Prefix of Any Word in a Sentence

### ISSUE THREAD

**Issue by sherixDO** [LeetCode-Feedback/LeetCode-Feedback#23861]
### LeetCode 用户名

sherixDO

### 问题号码、标题和链接

1445. 检查单词是否为句中其他单词的前缀 https://leetcode.cn/problems/check-if-a-word-occurs-as-a-prefix-of-any-word-in-a-sentence/description/

### Bug Category

缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*

### 描述

测试用例：sentence："i am your dad"
searchWord："daddy"

### 你使用的语言

C++

### 你提交或者运行的代码

```bash
class Solution {
public:
    int isPrefixOfWord(string sentence, string searchWord) {
        int count=1,n=0;
        bool judge=true;
        for(int i=0;i<sentence.length();i++){
            if(sentence[i]==' '){
                count++;
                n=0;
                judge=true;
                continue;
            }
            if(judge==false) continue;
            if(sentence[i]!=searchWord[n]){
                judge=false;
                continue;
            }
            n++;
            if(n==searchWord.length()) break;
        }
        if(judge) return count;
        else return -1;
    }
};
```

### 期望行为

提交的代码无法通过上述测试用例，但是可以通过leetcode的提交。

**Comment by amcones-lc** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by sherixDO** [comment]
你好，我的个性域名是https://leetcode.cn/u/sherixdo/

**Comment by amcones-lc** [comment]
你好，当前该题已添加测试用例，奖励已发放。
