### ISSUE TITLE
Missing Test Case - 443. String Compression

### ISSUE THREAD

**Issue by rainbowhuanguw** [LeetCode-Feedback/LeetCode-Feedback#2386]
#### Your LeetCode username

rainbowh

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

The current test cases do not include scenarios where there is a longer than 100-character cluster. e.g. [a, a, a,....,a] (size > 100). The code I used below should not work under the aforementioned scenarior but managed to pass all test cases currently. 

#### Code you used for Submit/Run operation

```
class Solution {
public int compress(char[] chars) {
    if (chars == null || chars.length == 0) { return 0; }
    if (chars.length == 1) { return 1; }

    int count = 1;
    int index = 0;

    for (int i = 1; i <= chars.length; i++) {
        if (i == chars.length; chars[i] != chars[i-1]) {
            chars[index++] = chars[i-1];
            if (count == 1) continue;
            else if (count >= 10) {
                // only covers two-digit cases
                chars[index++] = (char) (count / 10 + '0');
                chars[index++] = (char) (count % 10 + '0');
            } else {
                chars[index++] = (char) (count + '0');
            }
            count = 1;
        } else {
            count ++;
        }
    }
    return index;
}
};
```

#### Language used for code

Java

**Comment by lc-kay** [comment]
@rainbowhuanguw Can you please provide the submission details link and the missing custom test case? Thank you!

**Comment by lc-kay** [comment]
Hi @rainbowhuanguw 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
