### ISSUE TITLE
Improper Test Case - 1586. Binary Search Tree Iterator II

### ISSUE THREAD

**Issue by shit-eater** [LeetCode-Feedback/LeetCode-Feedback#23892]
### LeetCode Username

7NTxx-13

### Problem Number, Title, and Link

1586. Binary Search Tree Iterator II https://leetcode.cn/problems/binary-search-tree-iterator-ii/

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

In the description of the problem, you can see that it is guaranteed that each calling of 'next' or 'prev' is valid. 
But the first 'prev' of the following testcase is obviously invalid:
["BSTIterator","next","prev","next","next","hasNext","next","next","next","hasNext","hasPrev","prev","prev"]
[[[7,3,15,null,null,9,20]],[null],[null],[null],[null],[null],[null],[null],[null],[null],[null],[null],[null]] 

### Language Used for Code

Python/Python3

### Code used for Submit/Run operation

```bash
The code below should be accepted but get WA actually:

class BSTIterator:

    def __init__(self, root: TreeNode):
        self.nums = []
        self.dfs(root)
        self.p = -1

    def dfs(self,node):
        if not node:
            return
        self.dfs(node.left)
        self.nums.append(node.val)
        self.dfs(node.right)

    def hasNext(self) -> bool:
        return self.p<len(self.nums)-1

    def next(self) -> int:
        self.p+=1
        return self.nums[self.p]

    def hasPrev(self) -> bool:
        return self.p>0

    def prev(self) -> int:
        self.p-=1
        return self.nums[self.p]
```

### Expected behavior

The testcase below should be removed:
["BSTIterator","next","prev","next","next","hasNext","next","next","next","hasNext","hasPrev","prev","prev"]
[[[7,3,15,null,null,9,20]],[null],[null],[null],[null],[null],[null],[null],[null],[null],[null],[null],[null]]

**Comment by amcones-lc** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。
