### ISSUE TITLE
[测试用例不完整] - <32>

### ISSUE THREAD

**Issue by zjy666lkjfglasdf** [LeetCode-Feedback/LeetCode-Feedback#23899]
### LeetCode 用户名

江月何年初照人

### 问题号码、标题和链接

32.最长有效括号https://leetcode.cn/problems/longest-valid-parentheses/description/

### Bug Category

缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*

### 描述

本题的提示为字符串的长度 n <= 3*10^4, O(n^2)的时间复杂度应该是过不了的

### 你使用的语言

C++

### 你提交或者运行的代码

```bash
class Solution {
public:
    int longestValidParentheses(string s) {
        int ret = 0;
        int n = s.size();
        for (int i = 0; i < n; i++) {
            int cnt = 0, len = 0;
            for (int j = i; j < n; j++) {
                if (s[j] == '(') cnt++;
                else cnt--;
                len = j - i + 1;
                if (cnt < 0) {
                    break;
                }
                if (cnt == 0 && len % 2 == 0) ret = max(ret, len);
            }
        }

        return ret;
    }
};
```

### 期望行为

应该添加合适的测试用例

### 屏幕截图

![Uploading image.png…]()

### 额外的上下文

无

**Comment by zjy666lkjfglasdf** [comment]
无

**Comment by amcones-lc** [comment]
感谢反馈，能否向我们补充测试用例，以及能够通过此题但无法通过所提供的测试用例的代码，把信息提供完整才能有助于快速验证和精准的定位，谢谢。
