### ISSUE TITLE
Missing Test Case - 3. Longest Substring Without Repeating Characters

### ISSUE THREAD

**Issue by jortseng** [LeetCode-Feedback/LeetCode-Feedback#2389]
#### Your LeetCode username

jktseng

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
Solution

#### Description of the bug

For the test case "dvdf", the answer should be 2 but it is showing 3. `dvd` has `d` as repeating character. Answer is either `dv` or `df`. So 2 should be the answer.

#### Code you used for Submit/Run operation

```
class Solution {
    public int lengthOfLongestSubstring(String s) {
        int max = 0;
        HashSet<Character> set = new HashSet();
        for (int i = 0; i < s.length(); i++) {
            if (!set.contains(s.charAt(i))) {
                set.add(s.charAt(i));
                max = Math.max(max, set.size());
            } else {
                set.clear();
                set.add(s.charAt(i));
            }
        }
        return max;
    }
}
```

#### Language used for code

java

#### Expected behavior

Expect 2 as the answer for `dvdf` not 3.

**Comment by stormsunshine** [comment]
The answer for `"dvdf"` is indeed 3. The corresponding substring is `"vdf"`, which does not contain repeating characters.

**Comment by jortseng** [comment]
thanks!
