### ISSUE TITLE
1432. Max Difference You Can Get From Changing an Integer :: Wrong answer also accepted

### ISSUE THREAD

**Issue by Chinmayswaroop** [LeetCode-Feedback/LeetCode-Feedback#239]
**What kind of the bug**
- [ yes] problem
- [ yes] solution
- [ ] language

**Describe the bug**
The question appeared in the Bi-weekly contest 25 

**What language is your code written in**
Java

**The code you submit/run**
```
class Solution {
	public int maxDiff(int num) {

		String str = Integer.toString(num);
		char ch = str.charAt(0);
		for(char c : str.toCharArray()) {
			if(c != '9') {
				ch = c;
				break;
			}
		}

		String s1 = str.replace(ch, '9');
		int a = Integer.parseInt(s1);

		str = Integer.toString(num);

		char ch2 = str.charAt(0);
		char rp = str.charAt(0);

		if(str.length() == 1){
			ch2 = str.charAt(0);
			rp = '1';
		} 
		else if(str.charAt(0) == '1'){
			ch2 = str.charAt(1);
			rp = '0';
			for(char c : str.toCharArray()) {
				if(c != '1' && c != '0') {
					ch2 = c;
					break;
				}
			}
		}
		else {
			ch2 = str.charAt(0);
			rp = '1';
		}

		String s2 = str.replace(ch2, rp);
		int b = Integer.parseInt(s2);
		return a - b;
	}
}
```

**Expected behavior**
Input 111
Output(Mine) 999
Expected (that Leetcode shows) 888
But still, my answer got accepted

**Screenshots**
Added the Screenshots.

![L1](https://user-images.githubusercontent.com/17213780/80893273-761df000-8cee-11ea-9a97-1a19578a89fe.png)
![L2](https://user-images.githubusercontent.com/17213780/80893274-78804a00-8cee-11ea-81e5-70cfed5b4cb9.png)

**Comment by CooperCooperCooper** [comment]
Hi @Chinmayswaroop ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @Chinmayswaroop ,
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
