### ISSUE TITLE
Missing Test Case - 2028. Find Missing Observations

### ISSUE THREAD

**Issue by cack195** [LeetCode-Feedback/LeetCode-Feedback#23939]
### LeetCode Username

Cyril1905

### Problem Number, Title, and Link

2028. Find Missing Observations https://leetcode.com/problems/find-missing-observations/description/?envType=daily-question&envId=2024-09-05

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

Test case 3 fails to validate even though the output is correct and same as the expected output 
Input
<img width="2043" alt="image" src="https://github.com/user-attachments/assets/eec701db-ad69-4345-8c2a-df0204c0e019">

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
class Solution {
public:
    vector<int> missingRolls(vector<int>& rolls, int mean, int n) {
        int arr_size = rolls.size() + n;
        int miss_sum = (arr_size*mean)-accumulate(rolls.begin(), rolls.end(),0);
        int total_sum = miss_sum + accumulate(rolls.begin(), rolls.end(),0);
        vector<int> null;
        vector<int> rem_elements(n, 1);
        if (n * 1 > miss_sum || n * 6 < miss_sum) 
        return null;
        int rem_sum = miss_sum - n;
        cout<<rem_sum<<endl;
        int i = 0;
     while (rem_sum > 0) {
            int add_value = min(5, rem_sum);  
            rem_elements[i] += add_value;
            rem_sum -= add_value;
            i++;
        }
        return rem_elements;
    }
};
```

### Expected behavior

The test case 3 need to validate the correct output.

**Comment by cack195** [comment]
The input values were
rolls = [1,2,3,4]
mean = 6
n = 4

Actual Output
[]
Expected Output
[]

**Comment by cack195** [comment]
With that in mind, I tried implementing some solutions from the solution tab to check if the problem is in my code or logic. However, it seems not to be the case. I then tried other solutions, and I can confirm that the validation at test case 3 isn’t being executed as expected.

**Comment by Neilpatel5502** [comment]
> With that in mind, I tried implementing some solutions from the solution tab to check if the problem is in my code or logic. However, it seems not to be the case. I then tried other solutions, and I can confirm that the validation at test case 3 isn’t being executed as expected.

+1

**Comment by cack195** [comment]
Thank you
