### ISSUE TITLE
Wrong output - 2028. Find Missing Observations

### ISSUE THREAD

**Issue by pradeep-sadineni** [LeetCode-Feedback/LeetCode-Feedback#23958]
### LeetCode Username

pradeepsadineni23

### Problem Number, Title, and Link

https://leetcode.com/problems/find-missing-observations/description/

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

The expected out put is [] for [1,2,3,4] mean=6 n=4 and the output user getting is also same [] even thought its showing error and wrong please solve this problem

### Language Used for Code

Java

### Code used for Submit/Run operation

```bash
class Solution {
    public int[] missingRolls(int[] rolls, int mean, int n) {
        int m = rolls.length;
        int totalSum = mean * (n + m);
        int observedSum = 0;
        
        for (int roll : rolls) {
            observedSum += roll;
        }
        
        int missingSum = totalSum - observedSum;
        
        if (missingSum < n || missingSum > 6 * n) {
            return new int[0];
        }
        
        int base = missingSum / n;
        int remainder = missingSum % n;
        
        int[] result = new int[n];
        for (int i = 0; i < n; i++) {
            result[i] = base + (i < remainder ? 1 : 0);
        }
        
        return result;
    }
}
```

### Expected behavior

expected and correct must be same

**Comment by parthplusplus** [comment]
Facing the same issue, empty array is showing correct output but test case still fails.

![image](https://github.com/user-attachments/assets/59a6ea7a-2ac8-41d9-a87b-463ef9ddddad)
