### ISSUE TITLE
Wrong testcase for https://leetcode.com/problems/palindrome-partitioning-iii/

### ISSUE THREAD

**Issue by VikramDave** [LeetCode-Feedback/LeetCode-Feedback#24]
**What kind of the bug**
- [ ] problem
- [x] solution

**Describe the bug**
I feel the Testcase is wrong for https://leetcode.com/problems/palindrome-partitioning-iii/. I dont understand why its expecting 2 when we need to change 3 chars.

Input
"tcymekt"
4
stdout
[ 'tc', 'ym', 'ek', 't' ]
Output
3
Expected
2

**Expected behavior**
should be 3 but your solution expects 2

**Solution**
Expected should be 3 and not 2 for following input.
"tcymekt"
4

**Code Implementation**

/**
 * @param {string} s
 * @param {number} k
 * @return {number}
 */
var palindromePartition = function(s, k) {
    let numberOfCharNeedToBeChanged = 0;
    //break the string into K parts
    let chunks = chunkedArray(s, k);
    console.log(chunks);
    
    for(let i = 0; i < chunks.length; i++ ) {
            // Check if each is Palindrome
            numberOfCharNeedToBeChanged += palindromeChangeCount(chunks[i]);
    }
    
    return numberOfCharNeedToBeChanged;
};

var chunkedArray = function(s, k) {
    let chunks = [];
    const size = Math.ceil(s.length / k);

      for (let o = 0, i = 0; o < s.length;  i++, o += size) {
        chunks[i] = s.substr(o, size);

      }

  return chunks;
};

var palindromeChangeCount = function(str) {
    if (str.length < 2 || (str.length===2 && str.charAt(0) === str.charAt(1))) {
        return 0;
    }
    let len = Math.ceil(str.length/2),
     i = 0,
    changeCount = 0;
    
    while(i < len) {
        if (str.charAt(i) !== str.charAt(str.length -1 -i)) {
            changeCount++;
        }
        i++;
    }
    return changeCount;
};

**Comment by CooperCooperCooper** [comment]
Hi @VikramDave,

Thank you for reaching out to us. To help us assess this issue, can you please share your code with us on this issue?

**Comment by CooperCooperCooper** [comment]
Hi @VikramDave,
Thank you again for reaching out to us previously. Since you have not responded to this ticket for a while, hopefully, the issue has been resolved for you on your end. But if this issue still persists, please re-open this issue and share more details with us.

**Comment by VikramDave** [comment]
/**
 * @param {string} s
 * @param {number} k
 * @return {number}
 */
var palindromePartition = function(s, k) {
    let numberOfCharNeedToBeChanged = 0;
    //break the string into K parts
    let chunks = chunkedArray(s, k);
    
    for(let i = 0; i < chunks.length; i++ ) {
            // Check if each chopped string is a Palindrome and find the number of changes needed
            numberOfCharNeedToBeChanged += palindromeChangeCount(chunks[i]);
    }
    
    return numberOfCharNeedToBeChanged;
};


var chunkedArray = function(s, k) {
    let chunks = [];
    const size = Math.ceil(s.length / k);

      for (let o = 0, i = 0; o < s.length;  i++, o += size) {
        chunks[i] = s.substr(o, size);

      }

  return chunks;
};

var palindromeChangeCount = function(str) {
    if (str.length < 2 || (str.length===2 && str.charAt(0) === str.charAt(1))) {
        return 0;
    }
    let len = Math.ceil(str.length/2),
     i = 0,
    changeCount = 0;
    
    while(i < len) {
        if (str.charAt(i) !== str.charAt(str.length -1 -i)) {
            changeCount++;
        }
        i++;
    }
    return changeCount;
};

**Comment by CooperCooperCooper** [comment]
Hi @VikramDave,
Thank you for sharing the details with us! I've relayed this issue to our team to investigate

**Comment by CooperCooperCooper** [comment]
Hi @VikramDave,

Thank you for your patience. Please use the Dynamic Programming approach to solve this problem. The counter-example should be ["t","c","ymek","t"] change ym to ke with 2 operations. To give you more insight on this issue, please check out this [post]( https://leetcode.com/problems/palindrome-partitioning-iii/discuss/502600/javascript-dp-solution-beats-93.75).

We appreciate your time and support. If you have any other questions about this problem, please tag me again in the comment section to let me know.
