### ISSUE TITLE
Missing Test Case - 1014. Best Sightseeing Pair

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#2404]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution is accepted but fails on the following test case:

[2, 7, 7, 2, 1, 7, 10, 4, 3, 3]

#### Code you used for Submit/Run operation

```
class Solution {
    int ans = 0;


    //A[i] + A[j] + i - j
   
    public int maxScoreSightseeingPair(int[] A) {
        ans = 0;
        int[][] pairs = new int[A.length][2];

        for (int i = 0; i < A.length; i++) {
            pairs[i] = new int[]{A[i], i};
        }
        Arrays.sort(pairs, new Comparator<int[]>() {
            @Override
            public int compare(int[] o1, int[] o2) {
                int n = o1[0] + o2[0] - (Math.abs(o1[1] - o2[1]));
                ans = Math.max(ans, n);
                return Integer.compare(o2[0], o1[0]);

            }
        });
        return ans;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/108055213-ac2e2580-701d-11eb-9b75-1b54880314d7.png)

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
