### ISSUE TITLE
[BUG] - TreeNodeSerializer failing for default test cases

### ISSUE THREAD

**Issue by deogaya** [LeetCode-Feedback/LeetCode-Feedback#24048]
### LeetCode Username

deogaya

### Problem Number, Title, and Link

https://leetcode.com/problems/convert-binary-search-tree-to-sorted-doubly-linked-list

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

The test cases throwing the following exception for the default case: [4,2,5,1,3]

java.lang.NullPointerException: Cannot read field "right" because "<local2>" is null
  at line 119, TreeNodeSerializer.isValid
  at line 146, TreeNodeSerializer.serialize
  at line 188, __Driver__.main

### Language Used for Code

Java

### Expected behavior

Default test case should be parseable.

**Comment by vinzee** [comment]
I am facing the same issue. Please see my submission here:
https://leetcode.com/problems/convert-binary-search-tree-to-sorted-doubly-linked-list/submissions/1398025250/

**Comment by vinzee** [comment]
I figured out that it breaks when the head and tail are not connected to each other. Adding that link resolves the issue. 
It would be nice to see an error message calling out the issue rather than an NPE.
