### ISSUE TITLE
Problem Description - 1060. Missing Element in Sorted Array

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#2405]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
There are two points of problem description of [1060. Missing Element in Sorted Array](https://leetcode.com/problems/missing-element-in-sorted-array).
The first point is that the variable names are inconsistent in problem description and code template. In code template, the array name is `nums` and the integer is `k`. However, in problem description, the array name is `A` and the integer is `K`. The variable names should be consistent, and I think the variable names in code template are better. So I suggest that the variable names in problem description should be changed to `nums` and `k` respectively.
The second point is that a follow-up question needs to be added. This problem can be solved easily by looping over the array, with time complexity O(n). Another approach is to use binary search, with time complexity O(log n). If this problem is used in an interview, it is very likely that the interviewer expects a solution with time complexity O(log n). Therefore, I suggest that a follow-up question should be added, like the following.
**Follow up:** Could you come up with a solution with time complexity `O(log n)`?

#### Expected behavior
Two points as follows.
1. In problem description, the variable names should be changed so that they are consistent with the variable names in code template, which means the array name should be `nums` and the integer should be `k`.
2. A follow-up question should be added, like the following.
   > **Follow up:** Could you come up with a solution with time complexity `O(log n)`?

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
