### ISSUE TITLE
Restrict the user - 50. Pow(x, n)

### ISSUE THREAD

**Issue by Vishal023** [LeetCode-Feedback/LeetCode-Feedback#2406]
#### Your LeetCode username
vishal023

#### Category of the bug
- [x] Question
- [x] Solution

#### Description of the bug
Since this is a question of <b>medium</b> level it must not work if a user uses the <b>inbuilt power method</b> of any programming languages. 

#### Code you used for Submit/Run operation

```
class Solution {
    public double myPow(double x, int n) {
        return Math.pow(x,n);
    }
}
```

#### Language used for code
Java

#### Expected behavior
I expected that it should give an error if the user tries using inbuilt methods.
As in my case, I used ```Math.pow()```

#### Additional context
Either move it to the <b>easy</b> tag or just <b>stop the user from using inbuilt methods</b>.

**Comment by lc-kay** [comment]
Hi @Vishal023 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@Vishal023 There is no way we can test if the user used the pow function or not. The difficulty is set according to the intended solution and we don't intend to change it. Thank you for understanding.
