### ISSUE TITLE
SortedMap is not imported automatically in Java

### ISSUE THREAD

**Issue by dgithq** [LeetCode-Feedback/LeetCode-Feedback#241]
**What kind of the bug**
- [ ] problem
- [ ] solution
- [ X] language

**Describe the bug**
To my understanding, Leetcode automatically imports java.util.* for java submissions without users having to import it themselves. SortedMap is an interface in that package, but it is apparently not included automatically. 

**what language is your code written in**
Java

**The code you submit/run**
```
// Any question
class Solution {
    public boolean isValid(String s) {
        SortedMap<Integer, Integer> mp = new TreeMap<Integer, Integer>();
        return false;
    }
}
```
**Expected behavior**
That code is supposed to at least compile, since Leetcode auto-imports java.util.*. However, it will throw a "symbol not found" error on the line where you try to declare the SortedMap with a TreeMap. Only after I put in an "import java.util.*" statement does that compile properly. 

**Screenshots**

**Additional context**
Although Leetcode apparently does not auto-include SortedMap, it does include TreeMap. The following code will compile:
```
// Any question
class Solution {
    public boolean isValid(String s) {
        TreeMap<Integer, Integer> mp = new TreeMap<Integer, Integer>();
        return false;
    }
}
```

**Comment by CooperCooperCooper** [comment]
Hi @dgithq ,
Thank you for reaching out to us. To help us assess this issue, can you please share with us which problem(s) does your code correspond to?

**Comment by dgithq** [comment]
I first noticed that SortedMap did not work on 1438 - Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit. However, I tested using SortedMap on other questions too, like Two Sum and Number of Islands, and it didn't work on those either. It seems that all questions on Leetcode have this issue.

**Comment by CooperCooperCooper** [comment]
Hi @dgithq ,
Thank you for reaching out to us. I've filed this feature request to our team to consider.

We appreciate your time and support. If you have any other suggestions, please don't hesitate to let us know.
