### ISSUE TITLE
Problem Description - 1337. The K Weakest Rows in a Matrix

### ISSUE THREAD

**Issue by dlam26** [LeetCode-Feedback/LeetCode-Feedback#2410]
#### Your LeetCode username
dlam26

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
No biggie, but this sentence in the description has awkward English...

**"Soldiers are always stand in the frontier of a row, that is, always ones may appear first and then zeros."**

Plus, it misspells "front" with "frontier"!   An improvement might be...

**"Soldiers always stand in front of civilians in a given row-- that is, ones always appear first, followed by zeros."**

**Comment by lc-kay** [comment]
Hi @dlam26 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @dlam26 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
