### ISSUE TITLE
Missing Test Case - 1041. Robot Bounded In Circle

### ISSUE THREAD

**Issue by rkeval** [LeetCode-Feedback/LeetCode-Feedback#2412]
GLGLGLGLG -> This test case is a valid test case and should return true. As we are getting cycle in this. So this code need an additional condition under for loop and should check for value of x and y for 0 if it becomes 0 then should return true. This is an edge case.

#### Category of the bug
- [ ] Question
- [ **X**] Solution
- [ ] Language

#### Description of the bug

GLGLGLGLG -> This test case is a valid test case and should return true. As we are getting cycle in this. So this code need an additional condition under for loop and should check for value of x and y for 0 if it becomes 0 then should return true. This is an edge case.

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean isRobotBounded(String instructions) {
          // north = 0, east = 1, south = 2, west = 3
        int[][] directions = new int[][]{{0, 1}, {1, 0}, {0, -1}, {-1, 0}};
        // Initial position is in the center
        int x = 0, y = 0;
        // facing north
        int idx = 0;
        
        for (char i : instructions.toCharArray()) {
            if (i == 'L')
                idx = (idx + 3) % 4;
            else if (i == 'R')
                idx = (idx + 1) % 4;
            else {
                x += directions[idx][0];
                y += directions[idx][1];   
            } 
            if (x == 0 && y == 0)
                return (x == 0 && y == 0);
        }
        
        // after one cycle:
        // robot returns into initial position
        // or robot doesn't face north
        return (x == 0 && y == 0) || (idx != 0);
    }
}
```

#### Language used for code

Java

#### Expected behavior

GLGLGLGLG -> This test case is a valid test case and should return true. As we are getting cycle in this. So this code need an additional condition under for loop and should check for value of x and y for 0 if it becomes 0 then should return true. This is an edge case.

**Comment by lc-kay** [comment]
@rkeval To qualify for rewards, can you please submit an accepted solution that this custom test case fails? The solution you provided already receives wrong answer.

**Comment by lc-kay** [comment]
Hi @rkeval 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
