### ISSUE TITLE
很抱歉，由于您访问的URL有可能对网站造成安全威胁，您的访问被阻断 如果您是正常访问，请联系该业务系统管理员加白或其他方法处理 您的请求ID是：ac11000117261242799238712e0d2f

### ISSUE THREAD

**Issue by Jbo-Wang** [LeetCode-Feedback/LeetCode-Feedback#24127]
### LeetCode 用户名

melot__hhh

### 问题号码、标题和链接

https://canary.leetcode.cn/problems/implement-queue-using-stacks/

### Bug Category

问题描述

### 描述

描述
登录不了页面了显示“很抱歉，由于您访问的URL有可能对网站造成安全威胁，您的访问被阻断 如果您是正常访问，请联系该业务系统管理员加白或其他方法处理 您的请求ID是:781bad3f16674695285057227e700e”。猜想的两个动作可能导致这个的原因1.我有挂代理。2.我昨晚和今天下午长时间的挂在一道题上。其他的操作就是正常使用网站，不知道出现这种情况是为什么呢？

你使用的语言
C++

### 你使用的语言

None

### 期望行为

是个人用户，请我解封

**Comment by Fiorentinar** [comment]
我也一样：就是个人用户访问但也是这个阻断
很抱歉，由于您访问的URL有可能对网站造成安全威胁，您的访问被阻断，如果您是正常访问，请联系该业务系统管理员加白或其他方法处理您的请求ID是：ac11000117261244204538235ef302

我也有代理，会是这个原因吗

**Comment by liyuzhu-lc** [comment]
感谢您的反馈，请问现在可以正常使用了吗？可能服务器的实时运行产生一些波动，尝试刷新可以正常使用吗？有任何问题或建议您可随时与我们联系，谢谢。

**Comment by Jbo-Wang** [comment]
可以了，感谢
