### ISSUE TITLE
Solutions don't run & Missing Test Case - 11. Container With Most Water

### ISSUE THREAD

**Issue by honghaolin** [LeetCode-Feedback/LeetCode-Feedback#2415]
#### Your LeetCode username

HH2021

#### Category of the bug
- [X] Question
- [X] Solution
- [ ] Language

#### Description of the bug

Given test case `[5, 100, 5, 5, 5, 5, 5, 5]`, 
I would expected to have `600 = 100 * 7` as result, but "Expected answer" is `35`.

My assumption is: 
the answer will always move the right pointer if two pointers' values are equal.

**Comment by lc-kay** [comment]
@honghaolin The expected output is correct, 5x7=35. For a better understanding of the problem please visit https://leetcode.com/problems/container-with-most-water/discuss/6150/For-someone-who-is-not-so-clear-on-this-question Thank you for your time.
