### ISSUE TITLE
Missing Test Case - 2779. Maximum Beauty of an Array After Applying Operation

### ISSUE THREAD

**Issue by YoruJiang** [LeetCode-Feedback/LeetCode-Feedback#24160]
### LeetCode 用户名

1981755697@qq.com

### 问题号码、标题和链接

2779. 数组的最大美丽值 https://leetcode.cn/problems/maximum-beauty-of-an-array-after-applying-operation/description/

### Bug Category

缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*

### 描述

缺少测试用例：输入：nums = [100000], k=0；输出：1.
该测试用例符合题目要求，官方解答也能通过，但是提交无法通过此用例的解答也能通过当前已存在的所有用例。
原因是当输入数组最大值为100000时，差分数组的边界应为100001，即diff[100001] = diff[100001] - 1，但是当前已存在的测试用例下，只要将边界设在100000就能通过所有用例，即 diff[min(nums[i] + k + 1, 100000)]。

### 你使用的语言

C++

### 你提交或者运行的代码

```bash
class Solution {
public:
    int maximumBeauty(vector<int>& nums, int k) {
        int n = nums.size(), ans = 0;
        int diff[100001]{};
        for (int i = 0; i < n; i++) {
            diff[max(nums[i] - k, 0)]++;
            diff[min(nums[i] + k + 1, 100000)]--;
        }
        int cum = 0;
        for (int num : diff) {
            cum += num;
            ans = max(ans, cum);
        }
        return ans;
    }
};
```

### 期望行为

代码应当不通过。

**Comment by amcones-lc** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by YoruJiang** [comment]
你好，我的域名为 leetcode.cn/u/al_zn/

**Comment by amcones-lc** [comment]
你好，当前该题已添加测试用例，奖励已发放。
