### ISSUE TITLE
[BUG] - can't see editor in mobile 

### ISSUE THREAD

**Issue by ya332** [LeetCode-Feedback/LeetCode-Feedback#24162]
### LeetCode Username

ya332

### Problem Number, Title, and Link

No problem specific 

### Bug Category

Problem description

### Bug Description

I can't see editor in mobile version 

### Language Used for Code

None

### Expected behavior

Editor should appear

**Comment by ya332** [comment]
Hi Leetcode, thanks for the suggestion. I am aware of that option. However, it is a pain to switch back and forth. I use my tablet sometimes to solve questions. Please consider making the new version compatible with mobile and tablet usage.

**Comment by j-alex-hanson** [comment]
~~I'm reopening a new issue.~~

~~I see that I can switch back to the classic version of LeetCode on desktop (Safari; macOS), but this option does not appear for me on mobile (Safari; iOS).~~

LeetCode username: j-alex-hanson

Nevermind, I now see the option to open classic LeetCode!. However, it's not clear why this option now appeared when it previously did not exist.
