### ISSUE TITLE
Wrong output of test case - LeetCode 262

### ISSUE THREAD

**Issue by sanmingzi** [LeetCode-Feedback/LeetCode-Feedback#2419]
#### Category of the bug

- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

The output of one test case is wrong.

#### Code you used for Submit/Run operation

```
SELECT 
  t1.Request_at AS 'Day',
  ROUND(
    SUM(IF(t1.Status = 'completed', 0, 1)) / COUNT(*), 2
  ) AS 'Cancellation Rate'
FROM Trips AS t1
JOIN Users AS c ON c.Users_Id = t1.Client_Id
JOIN Users AS d ON d.Users_Id = t1.Driver_Id
WHERE c.Banned = 'No' 
-- AND d.Banned = 'No'
AND t1.Request_at BETWEEN '2013-10-01' AND '2013-10-03'
GROUP BY t1.Request_at
ORDER BY t1.Request_at;
```

The above submit is Accept. But the next submit is wrong.

```
SELECT 
  t1.Request_at AS 'Day',
  ROUND(
    SUM(IF(t1.Status = 'completed', 0, 1)) / COUNT(*), 2
  ) AS 'Cancellation Rate'
FROM Trips AS t1
JOIN Users AS c ON c.Users_Id = t1.Client_Id
JOIN Users AS d ON d.Users_Id = t1.Driver_Id
WHERE c.Banned = 'No' 
AND d.Banned = 'No'
AND t1.Request_at BETWEEN '2013-10-01' AND '2013-10-03'
GROUP BY t1.Request_at
ORDER BY t1.Request_at;
```

The description says "Both client and driver should not be banned". I think the last submition is correct.

There is one test case from the problem.

```json
{"headers": {"Trips": ["Id", "Client_Id", "Driver_Id", "City_Id", "Status", "Request_at"], "Users": ["Users_Id", "Banned", "Role"]}, "rows": {"Trips": [["1", "1", "10", "1", "completed", "2013-10-01"], ["2", "2", "11", "1", "cancelled_by_driver", "2013-10-01"], ["3", "3", "12", "6", "completed", "2013-10-01"], ["4", "4", "13", "6", "cancelled_by_client", "2013-10-01"], ["5", "1", "10", "1", "completed", "2013-10-02"], ["6", "2", "11", "6", "completed", "2013-10-02"], ["7", "3", "12", "6", "completed", "2013-10-02"], ["8", "2", "12", "12", "completed", "2013-10-03"], ["9", "3", "10", "12", "completed", "2013-10-03"], ["10", "4", "13", "12", "cancelled_by_driver", "2013-10-03"]], "Users": [["1", "No", "client"], ["2", "Yes", "client"], ["3", "No", "client"], ["4", "No", "client"], ["10", "Yes", "driver"], ["11", "Yes", "driver"], ["12", "Yes", "driver"], ["13", "No", "driver"]]}}
```

The output of this test case is:

```json
{"headers": ["Day", "Cancellation Rate"], "values": [["2013-10-01", 0.33], ["2013-10-02", 0.00], ["2013-10-03", 0.50]]}
```

It should be:

```json
{"headers": ["Day", "Cancellation Rate"], "values": [["2013-10-01", 1.00], ["2013-10-03", 1.00]]}
```

**Comment by lc-kay** [comment]
@sanmingzi The expected output is correct. Please refer to the discuss section of the problem to raise this question or view other posts with similar concerns. Thank you for your time.

**Comment by sanmingzi** [comment]
@lc-kay Somebody have the same concern with me. You can see the detail from the discusss of the problem.

https://leetcode.com/problems/trips-and-users/discuss/1068382/Is-there-a-wrong-testcase

Please check the test case one more time.

**Comment by sanmingzi** [comment]
@lc-kay Please open this issue. The new added test case is wrong. You can see it in many discusses of this problem.

https://leetcode.com/problems/trips-and-users/discuss/1051623/The-New-Added-Test-case-is-WRONG!

**Comment by lc-kay** [comment]
@sanmingzi I apologize for the delay in response, I've relayed this to our team to investigate.

**Comment by lc-kay** [comment]
Hi @sanmingzi 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
