### ISSUE TITLE
[BUG] - <cangjie语言输出结果正确性判断错误>

### ISSUE THREAD

**Issue by WhiteBaddy** [LeetCode-Feedback/LeetCode-Feedback#24216]
### LeetCode 用户名

bu-yao-xiang-bei

### 问题号码、标题和链接

https://leetcode.cn/problems/to-lower-case/description/

### Bug Category

不正确或缺少“相关标签”

### 描述

cangjie语言返回值判断错误。以输入数据"123&"为例，预期结果应为"123&"，cangjie语言显示的输出结果为"123\u0026"('\u0026'是‘&’字符的Unicode编码)，判定为答案错误。实际上经过测试，在cangjie语言内部对两字符串进行比较，两者是相等的。

### 你使用的语言

None

### 你提交或者运行的代码

```bash
class Solution {
    func toLowerCase(s: String): String {
        String(Array<Rune>(s.size, {i =>Rune(
            if (s[i] >= 65 && s[i] <= 90) { s[i] | 32 }
            else { s[i] }
        )}))
    }
}
```

### 期望行为

修复这个问题就可👌

### 屏幕截图

![Snipaste_2024-09-17_00-26-18](https://github.com/user-attachments/assets/6a2d0b9e-6736-41ca-8488-20037a4cbd68)

**Comment by amcones-lc** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by WhiteBaddy** [comment]
> 您好，当前主题已更新，请留言告知一下力扣中文网站的个人域名（Ps：若不知道在哪里查看自己的个人域名，可以通过浏览以下网址：[https://support.leetcode.cn/hc/ kb/article/1277837](https://support.leetcode.cn/hc/kb/article/1277837)），我们给予积分奖励。


以下是我的个性域名：leetcode.cn/u/bu-yao-xiang-bei/

**Comment by amcones-lc** [comment]
你好，当前该题已添加测试用例，奖励已发放。
