### ISSUE TITLE
Missing Test Case - 922. Sort Array By Parity II

### ISSUE THREAD

**Issue by MayankBatra005** [LeetCode-Feedback/LeetCode-Feedback#2422]
#### Your LeetCode username

Leet Code User Name: M_y_nk005

#### Category of the bug
- [x ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
The constraints of the questions are missing information.
Whenever we have the same odd / even input it fails. 
Set of Examples:
1. [2,2]
2. [3,3]

#### Code you used for Submit/Run operation

```
// Heap Based Solution 
class Solution {
    public int[] sortArrayByParityII(int[] A) {
        PriorityQueue<Integer> heap=new PriorityQueue<>();
        for(int i:A)
            heap.add(i);
        
        int oddPointer=1;
        int evenPointer=0;
        
        for(int i=0;i<A.length;i++)
        {
            if((heap.peek()%2)==0){
                A[evenPointer]=heap.poll();
                evenPointer+=2;
            }else{
                A[oddPointer]=heap.poll();
                oddPointer+=2;
            }
        }
        return A;
    }
}
```

#### Expected behavior

2,2 types of input should be added as a constraint in the question.

#### Screenshots

![image](https://user-images.githubusercontent.com/37073720/108423694-662bba00-71f5-11eb-89f6-3d9fcec92832.png)

#### Additional context

Not Applicable

**Comment by lc-kay** [comment]
Hi @MayankBatra005 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @MayankBatra005 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
