### ISSUE TITLE
Missing Test Case - 179. Largest Number

### ISSUE THREAD

**Issue by Gurekamjot003** [LeetCode-Feedback/LeetCode-Feedback#24253]
### LeetCode Username

Gurekamjot_Singh

### Problem Number, Title, and Link

179. Largest Number https://leetcode.com/problems/largest-number/

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

I found a test case where my solution fails, but it still gets accepted because the test case is not part of the current test suite. The code does not correctly handle comparisons for numbers with similar prefixes, like 111111121 and 11111112. Specifically, the solution should output 11111112111111121 as the largest number, but it fails to do so with my current implementation.
test case:
[111111121, 11111112]
![Screenshot (2178)](https://github.com/user-attachments/assets/e28595a0-813b-4d1f-be2d-8605adc79479)

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
class Solution {
public:
    string largestNumber(vector<int>& nums) {
        vector<string> snums;
        for (auto num : nums) {
            snums.push_back(to_string(num));
        }
        sort(snums.begin(), snums.end(), [&](string a, string b) {
            if (a != b) {
                int i = 0;
                while (i < a.size() && i < b.size() && a[i] == b[i])
                    i++;
                while (i<15) {
                    if(i>=a.size() && i<b.size()){
                        if(a[i % a.size()] > b[i]) return true;
                        else if(a[i % a.size()] < b[i]) return false;                        
                    }
                    else if (i<a.size() && i>=b.size()){
                        if(a[i] > b[i % b.size()]) return true;
                        else if(a[i] < b[i % b.size()]) return false;
                    }  
                    else {
                        if(a[i%a.size()]>b[i%b.size()]) return true;
                        else if(a[i%a.size()]< b[i%b.size()]) return false;
                    }
                    i++;
                }
            }
            return false;
        });
        for (auto snum : snums)
            cout << snum << endl;
        if (snums[0] == "0")
            return "0";
        string ans;
        for (auto snum : snums)
            ans += snum;
        return ans;
    }
};
```

### Expected behavior

so if i set the value of i less than 12 then there are test cases present that test the code but the code fails at value of i less than that.
now this test case has a error until i = 14, at i greater than that it runs perfectly. it should check while's iterations condition should be 15 then it gives correct output
![Screenshot (2178)](https://github.com/user-attachments/assets/e329073a-1d63-4253-b275-854f39775c58)

### Screenshots

![Screenshot (2178)](https://github.com/user-attachments/assets/da8eb540-b8d4-4621-bd4a-1497fbc7fdef)

### Additional context

my method is quite unique, i don't think anyone else used it but in future if someone uses it he should take care of number of iterations

**Comment by Gurekamjot003** [comment]
test case:
[111111121, 11111112]

**Comment by siddhant-ahire** [comment]
![Screenshot 2024-09-19 at 1 31 55 AM](https://github.com/user-attachments/assets/5a1baa9b-ec8f-4568-a111-c25ad3230f49)
