### ISSUE TITLE
Incorrect editorial - 179. Largest Number

### ISSUE THREAD

**Issue by przemek3d88** [LeetCode-Feedback/LeetCode-Feedback#24255]
### LeetCode Username

przemysaw2

### Problem Number, Title, and Link

179. Largest Number https://leetcode.com/problems/largest-number

### Bug Category

Editorial

### Bug Description

In the editorial it is mentioned correctly that conversion to the string takes $O(log k)$. There are some missing pieces though:

1. In every sorting algorithm each comparison is not constant, it also takes $O(log k)$. It means the time complexity should be $O(nlognlogk)$ for every solution.
2. For the solution 1, the memory is also $O(nlogk)$, the same as the Timsort solution.
3. For the solution 1, the sorting memory is bounded by $O(n)$ or $O(logn)$ which is $O(n)$. You could argue, that you shouldn't include it in the final memory, as the additional data structure takes $O(nlogk)$. However, I do not have a strong opinion here.

### Language Used for Code

None

### Expected behavior

Please add the $O(logk)$ factor to all the missing places.

**Comment by Varun-n-n** [comment]
# Implications for Problem Solving
- When dealing with problems that involve sorting numbers based on custom criteria involving string concatenation, it's important to account for the cost of string operations.
- Understanding that each comparison is not constant time helps in accurately analyzing the algorithm's efficiency.
- This awareness can guide you to optimize your solution further if needed or justify why the current solution is acceptable within the problem's constraints.
# Final Thoughts
- The report highlights the importance of thoroughly analyzing both time and space complexities, especially when non-trivial operations are involved in comparisons or data transformations.
- Being precise in these analyses ensures a better understanding of the algorithm's performance and helps identify potential bottlenecks or inefficiencies.

**Comment by przemek3d88** [comment]
This is not true as you mentioned $O(logk)$. In the heapsort solution. If that's the case, please remove it from that solution.

**Comment by przemek3d88** [comment]
Below is the screenshot with the $O(nlogk)$ space complexity.

<img width="637" alt="Zrzut ekranu 2024-09-28 o 12 10 29 PM" src="https://github.com/user-attachments/assets/0505fbb0-7dae-4c71-94a1-c36d53878bcb">
