### ISSUE TITLE
Incorrect Test Case - 179. Largest Number

### ISSUE THREAD

**Issue by Arnabbera119** [LeetCode-Feedback/LeetCode-Feedback#24254]
### LeetCode Username

arnabbera119

### Problem Number, Title, and Link

179. Largest Number https://leetcode.com/problems/largest-number/description/?envType=daily-question&envId=2024-09-18

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

In this problem statement, the given output of Example 2 is incorrect
Example 2:

Input: nums = [3,30,34,5,9]
Output: "9534330"

The output should be : "354330
![Screenshot_20240918_104831](https://github.com/user-attachments/assets/22707999-c370-4719-a852-00e522c3f1a2)
"

### Language Used for Code

Java

### Code used for Submit/Run operation

```bash
class Solution {
    public String largestNumber(int[] nums) {
        String str="";
        for(int k=9;k>=0;k--){
            for(int i=0;i<nums.length;i++){
                int n=nums[i];
                while(n!=0){
                    int r=n%10;
                    if(r==k){
                        str=str+r;
                    }
                    n=n/10;
                }
            } 
        }
        return str;
    }
}
```

### Expected behavior

Input: nums =[3,30,34,5,9]

Output:
"9543330"

**Comment by Varun-n-n** [comment]
In Expected Behavior, you've given:

Input: nums = [3, 30, 34, 5, 9]

Output:
"9543330"

But how does it start with '954'?

- '9' is correct.
- '5' is correct.
- But '4' is not a separate digit; you should use '34' as a whole number.
