### ISSUE TITLE
Missing Test Case - 2414. Length of the Longest Alphabetical Continuous Substring

### ISSUE THREAD

**Issue by Lcyun0805** [LeetCode-Feedback/LeetCode-Feedback#24271]
### LeetCode 用户名

Assin

### 问题号码、标题和链接

https://leetcode.cn/problems/length-of-the-longest-alphabetical-continuous-substring/?envType=daily-question&envId=2024-09-19

### Bug Category

缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*

### 描述

我认为题目中描述的连续字母组成的字符串，并不一定是连续递增的才算递增。
连续递减难道不是连续么？

### 你使用的语言

Python/Python3

### 你提交或者运行的代码

```bash
class Solution:
    def longestContinuousSubstring(self, s: str) -> int:
        lst = list(s)
        ans = 1
        tmp = 1
        for i, x in enumerate(lst):
            if i > 0 and ord(x) - ord(lst[i-1]) == 1:
                tmp += 1
                ans = max(ans, tmp)
            else:
                tmp = 1
        return ans
```

### 期望行为

我认为abcdefg是连续的字符串，gfedcba应该也算连续的。
而aba这种就不能算是连续。

### 屏幕截图

无

### 额外的上下文

无

**Comment by liyuzhu-lc** [comment]
感谢您的宝贵反馈，我们已经将您的反馈提交给我们的负责团队，他们将会对相关信息进行核查，有新的进展及时再与您联系。感谢您的理解与支持。

**Comment by amcones-lc** [comment]
您好，在与相关团队核实后：***不处理***（题目中字母序意为按字母表顺序，如果逆序则应称为字母逆序）。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
