### ISSUE TITLE
Missing Test Case - 10. Regular Expression Matching

### ISSUE THREAD

**Issue by fyyfang** [LeetCode-Feedback/LeetCode-Feedback#24275]
### LeetCode 用户名

fyy

### 问题号码、标题和链接

10.正则匹配 https://leetcode.cn/problems/regular-expression-matching/description/

### Bug Category

不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*

### 描述

测试用例似乎不正确，不是很理解测试用例，在进行正则匹配的时候如果两个字符串出现除“.","*"等通配符不同的字符，应该是认为两个字符串不匹配

### 你使用的语言

Java

### 你提交或者运行的代码

```bash
class Solution {
    public boolean isMatch(String s, String p) {
        int i = 0;
            for(int j=0;j<p.length();j++){
                if(s.charAt(i) == p.charAt(j)){
                    i++;
                    continue;
                }else if(s.charAt(i) != p.charAt(j) && p.charAt(j)=='.'){
                    i++;
                    continue;
                }else if(s.charAt(i) != p.charAt(j) && j-1 >=0 && p.charAt(j)=='*'&&p.charAt(j) == '*'){
                    i++;
                    continue;
                }else{
                    return false;
                }
            }
        if(i <s.length()){
            return false;
        }
        return true;


    }
}
```

### 期望行为

"aab"
"c*a*b"
在对这两个字符串进行正则匹配时，返回false

### 屏幕截图

![leetcode](https://github.com/user-attachments/assets/7878b363-cde3-4c84-8e99-e6ba0097b36b)

### 额外的上下文

bug 测试用例错误

**Comment by liyuzhu-lc** [comment]
感谢您的宝贵反馈，我们已经将您的反馈提交给我们的负责团队，他们将会对相关信息进行核查，有新的进展及时再与您联系。感谢您的理解与支持。

**Comment by amcones-lc** [comment]
您好，在与相关团队核实后：***不处理***（`*` 意为匹配前面的字符任意次（包括 0 次），因此 `c` 匹配 0 次， `a` 匹配一次，两个字符串是匹配的）。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
