### ISSUE TITLE
Wrong Test Case

### ISSUE THREAD

**Issue by YashVS15112004** [LeetCode-Feedback/LeetCode-Feedback#24297]
### LeetCode Username

yashvars15114

### Problem Number, Title, and Link

214,Shortest Palindrome,https://leetcode.com/problems/shortest-palindrome/description/

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

Input : s = "aabba"
Output : "abbabba"
Expected : "abbaabba"
"abbabba"  is not accepted? The question states that we have to add characters to make it shortest palindrome! It contradicts the given test case :
Input: s = "abcd"
Output: "dcbabcd"
![Screenshot 2024-09-20 111115](https://github.com/user-attachments/assets/e390478d-d4b4-4f8c-bba7-3bb57511a04b)
![Screenshot 2024-09-20 111529](https://github.com/user-attachments/assets/e50b706a-2007-459d-a98d-e8838febb7cd)

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
bool checkPalindrome(string s)
{
    int i  = 0;
    int j = s.size()-1;
    while(i<j) if(s[i++]!=s[j--]) return false;
    return true;
}
string shortestPalindrome(string s) 
{
    string ans1 = "";
     string ans = "";
     int n = s.size();
     if(checkPalindrome(s)) return s;
     else
     {
         int i = 0;
         int j = s.size()-1;
         while(i<j)
         {
             if(s[i]==s[j])
             {
                 ans1 += s[i];
                 i++;
                 j--;
             }
             else
             {
                 ans1 += s[j];
                 j--;
             }
         }
         ans = ans1;
         while(i<n) ans += s[i++];
         return ans;
}
}
```

### Expected behavior

The testcase should be accepted in accordance to the example-2 given.

### Screenshots

![Screenshot 2024-09-20 111115](https://github.com/user-attachments/assets/e13292d5-703f-43c9-acbb-defdd4753fc3)
![Screenshot 2024-09-20 111529](https://github.com/user-attachments/assets/f705fdd7-d5c0-4847-8a62-64d59968d119)

**Comment by idkmynamereally** [comment]
You can't delete characters from the beginning
