### ISSUE TITLE
Missing Test Case - 539. Minimum Time Difference

### ISSUE THREAD

**Issue by MarwanEmadMourad** [LeetCode-Feedback/LeetCode-Feedback#2429]
#### Category of the bug
- [ ] Question
- [ 1] Solution
- [ ] Language

#### Description of the bug

in the test case ["12:12","00:13"] the output should be 721 not 719.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@MarwanEmadMourad The expected output is correct. Please check out this post: https://leetcode.com/problems/minimum-time-difference/discuss/361546/Can-someone-explain-this-test-case Thank you for your time.
