### ISSUE TITLE
1438. Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#243]
**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
Weak test case suite can get non optimal solution accepted.

**what language is your code written in**
Python

**The code you submit/run**
```
class Solution:
    def longestSubarray(self, a: List[int], l: int) -> int:
        n=len(a)
        if n<=1:
            return 1
        z=0
        s=0
        mx=a[0]
        mn=a[0]
        for i in range(1,n):
            mx=max(mx,a[i])
            mn=min(mn,a[i])
            if mx-mn>l:
                s+=1
                mx=a[s]
                mn=a[s]
                for j in range(s,i+1):
                    mx=max(mx,a[j])
                    mn=min(mn,a[j])
            z=max(z,i-s+1)
        return z
```

**Expected behavior**
The solution should not be accepted as it is quadratic solution instead of linear.
The following test case gives TLE for the solution. It is too big for this issue so I attached it in text format.

[New Text Document.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/4569639/New.Text.Document.txt)

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
