### ISSUE TITLE
Missing Test Case - 92. Reverse Linked List II

### ISSUE THREAD

**Issue by ayush-nalawade** [LeetCode-Feedback/LeetCode-Feedback#24302]
### LeetCode Username

ayushnalawade3

### Problem Number, Title, and Link

https://leetcode.com/problems/reverse-linked-list-ii/description/

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

In the question reverse linked list II the following testcase is giving the wrong output according to the question.
The testcase is  head =[1,2,3,4]  left =1   right =4 
correct output is [4,2,3,1] and output shown on leetcode platform is [4,3,2,1].

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
/**
 * Definition for singly-linked list.
 * struct ListNode {
 *     int val;
 *     ListNode *next;
 *     ListNode() : val(0), next(nullptr) {}
 *     ListNode(int x) : val(x), next(nullptr) {}
 *     ListNode(int x, ListNode *next) : val(x), next(next) {}
 * };
 */
class Solution {
public:
    ListNode* reverseBetween(ListNode* head, int left, int right) {
        
        ListNode* leftn = NULL;
    
        
        ListNode* temp =head;

        int cnt =1;

        while(temp != NULL ){

            if(cnt == left){
                
                leftn = temp;
            }

            if(cnt == right){

                if(leftn != NULL){

                    int t =  leftn->val;

                    leftn-> val = temp->val;

                    temp->val = t;

                    return head;
                }
            }

            temp = temp->next;
            cnt++;
        }
        return head;
    }
};
```

### Expected behavior

The testcase (testcase number 28 ) is  head =[1,2,3,4]  left =1   right =4 
so it should swap the elements from position 1 and  position 4 and remaining elements should be same.
correct output is [4,2,3,1] and
 output shown on Leetcode platform is [4,3,2,1].

### Screenshots

![Screenshot 2024-09-20 171602](https://github.com/user-attachments/assets/0c731480-238c-49de-be0a-a36fd87747da)

**Comment by samsammurphy** [comment]
I ran into the same issue. The problem statement is ambiguous imo, as it is it could be interpreted either way. If we gave an example with 6 nodes then it would be clearer that the nodes between are meant to be reversed.

```
# This example would be clearer

Input
1 > 2 > 3 > 4 > 5 > 6
reverse positions
left = 2
right = 5

Output
1 > 5 > 4 > 3 > 2 > 6
```

and/or we could consider making the wording clearer:

_"Given the head of a singly linked list and two integers left and right where left <= right, **reverse all the nodes in the list between position left and position right inclusively, and return the new list.**_

Here is a screenshot of the [Reverse Linked List II](https://leetcode.com/explore/interview/card/leetcodes-interview-crash-course-data-structures-and-algorithms/704/linked-lists/4598/) chapter in the DS&A course.

<img width="909" alt="Screenshot 2024-12-22 at 11 06 37" src="https://github.com/user-attachments/assets/1a24ccba-26e8-4c61-98a1-c7c62a5f7210" />
