### ISSUE TITLE
867. Transpose Matrix | Incorrect behavior for the judging system related to list/tuple in Python3

### ISSUE THREAD

**Issue by zerotrac** [LeetCode-Feedback/LeetCode-Feedback#2430]
#### Your LeetCode username

zerotrac2

#### Category of the bug

- [x] Online Judge Bug

#### Description of the bug

We can use the following code to pass all the tests of problem 867:

```Python3
class Solution:
    def transpose(self, matrix: List[List[int]]) -> List[List[int]]:
        x = list(zip(*matrix))
        print(x)
        return x
```

It is evident that x is **a list of tuples** but not **a list of lists** as expected. However, the stdout of `x` is **a list of tuples** but the output becomes **a list of lists**.

![image](https://user-images.githubusercontent.com/15974765/108536684-ad11d080-7317-11eb-8d2a-02db714508e0.png)

What is even worse is that we can return **a list of iterators**, **a list of generators** or **a list of genexprs**, which could all pass the tests.

```Python3
class Solution:
    def transpose(self, matrix: List[List[int]]) -> List[List[int]]:
        def badIterator():
            x = list(iter(y) for y in zip(*matrix))
            print(x)
            return x
        
        def badGenerator():
            def gen(y):
                for u in y:
                    yield(u)
                
            x = list(gen(y) for y in zip(*matrix))
            print(x)
            return x
        
        def badGenexpr():
            x = list((u for u in y) for y in zip(*matrix))
            print(x)
            return x
        
        return badIterator()
        # return badGenerator()
        # return badGenexpr()
```

#### Expected behavior

Only **a list of lists** should be accepted.

**Comment by lc-kay** [comment]
Hi @zerotrac 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@zerotrac The above behavior is intentional. We don't do type checking because it would be hard on the user. Thank you for your time.
