### ISSUE TITLE
Problem Description - 832. Flipping an Image

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#2431]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
For [832. Flipping an Image](https://leetcode.com/problems/flipping-an-image), the given binary matrix `A` is guaranteed to be a square matrix, which means that the number of rows and the number of columns are the same. The fact that `A` is a square matrix is mentioned in **Notes** part. However, I don't think this is clear enough.
I suggest that `A` is a square matrix should be mentioned in problem description. The first sentence should be changed to the following (a word "square" is added).
Given a binary square matrix `A`, we want to flip the image horizontally, then invert it, and return the resulting image.

#### Expected behavior
The fact that `A` is a square matrix should be mentioned in problem description. The first sentence should be changed to the following (a word "square" is added).
Given a binary square matrix `A`, we want to flip the image horizontally, then invert it, and return the resulting image.

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
