### ISSUE TITLE
Problem Description - 231. Power of Two

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#2432]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
There are three similar problems as follows.
[231. Power of Two](https://leetcode.com/problems/power-of-two)
[326. Power of Three](https://leetcode.com/problems/power-of-three)
[342. Power of Four](https://leetcode.com/problems/power-of-four)
The latter two problems (326 and 342) have follow-up questions, but the first problem (231) does not have a follow-up question. I think that a follow-up question should be also added for problem 231.
Besides, the descriptions of the follow-up questions for 326 and 342 are different.
For problem 326, the description of the follow-up question is: Could you do it without using any loop / recursion?
For problem 342, the description of the follow-up question is: Could you solve it without loops/recursion?
I think the description should be the same, and I think that the description for problem 326 is better, so the description for problem 342 should be changed as well.
For problem 231, the follow-up question should be as follows.
**Follow up:** Could you do it without using any loop / recursion?

#### Expected behavior
The description of the follow-up question for 342 should be changed to the same as 326. That is, the description should be changed to: Could you do it without using any loop / recursion?
The same follow-up question should be added for 231, as follows.
**Follow up:** Could you do it without using any loop / recursion?

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
