### ISSUE TITLE
Missing Module in your Shit System 

### ISSUE THREAD

**Issue by 07-Bash** [LeetCode-Feedback/LeetCode-Feedback#2433]
from rom import rom_parse
        a = rom_parse(s) 
        return a 
#### chinmayporwal23

pls    install rom module 
using pip command     
#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
Hi @07-Bash 
Thank you for your time. Upon investigating this issue, we found this issue to be non-content-related (the issue stems from an origin away from the content on this problem. If you'd like to request a rom module, please contact our help center and provide reasons why it's required. Thank you again for your support and understanding.
