### ISSUE TITLE
Missing Test Case - 582. Kill Process

### ISSUE THREAD

**Issue by DorisLi** [LeetCode-Feedback/LeetCode-Feedback#2436]
#### Your LeetCode username
DorisLi

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
What if the user are trying to kill a process that is not exist, say we have a list of process with {1,2,3} but I want to kill process id 4, in the current test cases, we will return 4 at the end, by defination it means this is the process we finally will kill. But it makes no sense to kill a ghost process...?
I think we should return empty list if such case happens and immidately return the result. Or if we want to make it clear it is possible for us to kill a not existed process and it will finally being removed or something similar in the description.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code
Java

**Comment by lc-kay** [comment]
Hi @DorisLi 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @DorisLi 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
