### ISSUE TITLE
为题目添加测试用例

### ISSUE THREAD

**Issue by Great-serpent-spear** [LeetCode-Feedback/LeetCode-Feedback#24363]
### LeetCode 用户名

亚瑟摩根

### 问题号码、标题和链接

1014. 最佳观光组合https://leetcode.cn/problems/best-sightseeing-pair/description/

### Bug Category

缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*

### 描述

我提交的代码允许通过题目,但这个代码显然是错误的,例如用例values = [1000,1,1,1,1,1,1,1,1,1,1,1,1000]

### 你使用的语言

Python/Python3

### 你提交或者运行的代码

```bash
class Solution:
    def maxScoreSightseeingPair(self, values: List[int]) -> int:
        ans=0
        for i in range(len(values)):
            for j in range(i+1,min(i+11,len(values))):
                ans=values[i]+values[j]+i-j if values[i]+values[j]+i-j>ans else ans
        return ans
```

### 期望行为

添加用例values = [1000,1,1,1,1,1,1,1,1,1,1,1,1000]以及values=[1000,1,1,……,1,1,1000]防止我这种错误代码通过

**Comment by liyuzhu-lc** [comment]
感谢您的宝贵反馈，我们已经将您的反馈提交给我们的负责团队，他们将会对相关信息进行核查，有新的进展及时再与您联系。感谢您的理解与支持。

**Comment by amcones-lc** [comment]
We have received your feedback, please wait for us to process it.
