### ISSUE TITLE
Missing Test Case -1764. Form Array by Concatenating Subarrays of Another Array

### ISSUE THREAD

**Issue by deep3072** [LeetCode-Feedback/LeetCode-Feedback#2438]
#### Your LeetCode username
deep3072

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
A solution is accepted but fails on the following test case:
[[21,22,21,22,21,30]]
[21,22,21,22,21,22,21,30]

#### Code you used for Submit/Run operation

```
class Solution 
{
        public:
        bool canChoose(vector<vector<int>>& g, vector<int>& nums) 
        {
                int i,j=0,k;
                for(i=0;i<g.size() && j<nums.size();)
                {
                        bool mark=true;
                        int k=0;
                        for(;j<nums.size() && k<g[i].size();j++)
                        {
                                if(nums[j]==g[i][k])
                                        k++;
                                else
                                {
                                        if(nums[j]!=g[i][0])
                                        j++;
                                        mark=false;
                                        break;
                                }
                        }
                        if(mark && k==g[i].size())
                                i++;
                        // cout << j << "\n";
                }
                return (i==g.size());
        }
};
```

#### Language used for code

C++

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![Capture1](https://user-images.githubusercontent.com/62668186/108603932-c591f180-73d0-11eb-8f6b-70ee08703bdf.PNG)

**Comment by lc-kay** [comment]
Hi @deep3072 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @deep3072 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by deep3072** [comment]
Hii
This is to inform that my testcase contribution has been updated in my
leetcode profile but i haven't received any 100 coins as reward.
Here I am attaching my points activity screenshots of past 3 days.

Please check it needful.
Thanks!

**Comment by lc-kay** [comment]
@deep3072 Sorry about that, we have added the coins.
