### ISSUE TITLE
[BUG] - 为了保证账号安全，本次请使用手机验证码登录

### ISSUE THREAD

**Issue by jay6413682** [LeetCode-Feedback/LeetCode-Feedback#24381]
### LeetCode 用户名

 iamabigstone@gmail.com

### 问题号码、标题和链接

无法用美国站帐号登录leetcode.cn

### Bug Category

问题描述

### 描述

无法用美国站帐号登录leetcode.cn。每次尝试登陆都显示“为了保证账号安全，本次请使用手机验证码登录”

### 你使用的语言

None

### 期望行为

以前都可以登陆

### 屏幕截图

<img width="409" alt="image" src="https://github.com/user-attachments/assets/407e34cd-a4de-4938-b7c5-c3aeb14de60d">

**Comment by liyuzhu-lc** [comment]
您好，希望这篇对您有帮助：https://support.leetcode.cn/hc/kb/article/1642640/
