### ISSUE TITLE
Missing Test Case - 1. Two Sum11

### ISSUE THREAD

**Issue by felix971019** [LeetCode-Feedback/LeetCode-Feedback#24385]
### LeetCode 用户名

felix

### 问题号码、标题和链接

两数之和 https://leetcode.cn/problems/two-sum/

### Bug Category

问题描述, 示例

### 描述

没有， 有的话就是提示不太够用

### 你使用的语言

Java

### 你提交或者运行的代码

```bash
class Solution {
    public int[] twoSum(int[] nums, int target) {
        
        for (int i = 0; i < nums.length; i++) {
            for (int j = 1; j < nums.length; j++) {
                if (i != j && (nums[i] + nums[j]) == target) {
                    int[] arr = {i, j};
                    return arr;
                }
            }
        }
        return new int[]{};
    }
}
```

### 期望行为

还行

### 屏幕截图

1

### 额外的上下文

1

**Comment by liyuzhu-lc** [comment]
感谢您的宝贵反馈，我们已经将您的反馈提交给我们的负责团队，并将会对相关信息进行核查，有新的进展及时再与您联系。感谢您的理解与支持。

**Comment by amcones-lc** [comment]
感谢反馈，经核实该题目题解及测试用例暂无异常，力扣会不断努力给大家带来更好的学习社区！后续刷题学习中遇到问题，可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
