### ISSUE TITLE
Missing Test Case - 1456. Maximum Number of Vowels in a Substring of Given Length

### ISSUE THREAD

**Issue by Mag357num** [LeetCode-Feedback/LeetCode-Feedback#24386]
### LeetCode 用户名

357Magnum

### 问题号码、标题和链接

https://leetcode.cn/problems/maximum-number-of-vowels-in-a-substring-of-given-length/description/

### Bug Category

缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*

### 描述

应该加一个 字符串长度为1，k=1的案例。比如 s= "a", k=1。 这个测试用例是符合题意要求的，但是目前没有，而且对代码正确性的判断有很重要影响。
比如下面代码，注释掉++maxNum在目前的测试用例下也能通过，但是加入了 s= "a", k=1之后无法通过
`class Solution {
public:
    bool isVowels(char c) {
        if (c == 'a' || c == 'e' || c == 'i' || c == 'o' || c == 'u')
            return true;
        return false;
    }

    int maxVowels(string s, int k) {
        int left = 0, right = 0, maxNum = 0, curNum = 0;

        if (isVowels(s[0])) {
            ++curNum;
            // ++maxNum;
        }
        while (right < s.size()) {
            if (right - (left - 1) == k) {
                if (isVowels(s[left]))
                    --curNum;
                ++left;
            }

            if (right - (left - 1) < k) {
                ++right;
                if (isVowels(s[right])) {
                    ++curNum;
                    maxNum = max(maxNum, curNum);
                }
            }
        }
        return maxNum;
    }
};`

### 你使用的语言

C++

### 你提交或者运行的代码

```bash
class Solution {
public:
    bool isVowels(char c) {
        if (c == 'a' || c == 'e' || c == 'i' || c == 'o' || c == 'u')
            return true;
        return false;
    }

    int maxVowels(string s, int k) {
        int left = 0, right = 0, maxNum = 0, curNum = 0;

        if (isVowels(s[0])) {
            ++curNum;
            ++maxNum;
        }
        while (right < s.size()) {
            if (right - (left - 1) == k) {
                if (isVowels(s[left]))
                    --curNum;
                ++left;
            }

            if (right - (left - 1) < k) {
                ++right;
                if (isVowels(s[right])) {
                    ++curNum;
                    maxNum = max(maxNum, curNum);
                }
            }
        }
        return maxNum;
    }
};
```

### 期望行为

添加一个测试用例s= "a", k=1

**Comment by amcones-lc** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by Mag357num** [comment]
> 你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

非常感谢，中文id为357Magnum
![Uploading PixPin_2024-10-07_01-21-43.png…]()

**Comment by Mag357num** [comment]
> 你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

个性域名为
leetcode.cn/u/357magnum/

**Comment by amcones-lc** [comment]
你好，当前该题已添加测试用例，奖励已发放。
