### ISSUE TITLE
Missing Test Case -1764. Form Array by Concatenating Subarrays of Another Array

### ISSUE THREAD

**Issue by hukun01** [LeetCode-Feedback/LeetCode-Feedback#2439]
#### Your LeetCode username

Memoria

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Missing a test case. Some existing accepted solutions will fail on below case.
```
[[2,1]]
[12,1]
```

#### Code you used for Submit/Run operation

```
class Solution:
    def canChoose(self, groups: List[List[int]], nums: List[int]) -> bool:
        
        s = "#".join(map(str, nums))

        for group in groups:
            g = "#".join(map(str, group))

            if not s:
                return False

            i = s.find(g)

            if i == -1:
                return False

            s = s[i + len(g):]

        return True
```

#### Language used for code

Python3

#### Expected behavior

Expected result is `false`, but this above code returned `true` and got accepted.

**Comment by lc-kay** [comment]
Hi @hukun01 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @hukun01 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
