### ISSUE TITLE
14. Longest Common Prefix

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#244]
**What kind of the bug**
- [ ] problem
- [x] solution
- [ ] language

**Describe the bug**
Approach 4 : Binary Search solution has wrong analysis

**what language is your code written in**
Java

**The code you submit/run**
```
public String longestCommonPrefix(String[] strs) {
    if (strs == null || strs.length == 0)
        return "";
    int minLen = Integer.MAX_VALUE;
    for (String str : strs)
        minLen = Math.min(minLen, str.length());
    int low = 1;
    int high = minLen;
    while (low <= high) {
        int middle = (low + high) / 2;
        if (isCommonPrefix(strs, middle))
            low = middle + 1;
        else
            high = middle - 1;
    }
    return strs[0].substring(0, (low + high) / 2);
}

private boolean isCommonPrefix(String[] strs, int len){
    String str1 = strs[0].substring(0,len);
    for (int i = 1; i < strs.length; i++)
        if (!strs[i].startsWith(str1))
            return false;
    return true;
}
```

**Expected behavior**
In the worst case we have n equal strings with length m

Time complexity : O(S⋅logn), where S is the sum of all characters in all strings.

The algorithm makes logn iterations, for each of them there are S=m⋅n comparisons, which gives in total O(S⋅logn) time complexity.

This is the analysis provided.

The binary search is being made on minLen which is minimum length of all strings in array. Even with the assumption that all are of length m, the algorithm makes logm iterations, for each of them there are S=m⋅n comparisons, which gives in total O(S⋅logm) time complexity.

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @
Thank you for your time. We've used your feedback to update the time complexity. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.

**Comment by leet212** [comment]
Thanks for the update @CooperCooperCooper. Should I reach out using the mail provided or is the technical support channel using Zendesk the same?

**Comment by leet212** [comment]
Hello @CooperCooperCooper . Could you clarify the above query?

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Please use the email provided, which will submit a support request ticket to our Zendesk channel. Thank you.

**Comment by leet212** [comment]
Thanks for the reply @CooperCooperCooper . I will submit it through the email provided.
