### ISSUE TITLE
[BUG] -  代码   215. 数组中的第K个最大元素中，官方解答有误

### ISSUE THREAD

**Issue by Mag357num** [LeetCode-Feedback/LeetCode-Feedback#24401]
### LeetCode 用户名

357Magnum

### 问题号码、标题和链接

https://leetcode.cn/problems/kth-largest-element-in-an-array/description/

### Bug Category

力扣官方题解

### 描述

官方解答有误，完全二叉树第一个非叶子节点不应该是size/2，应该是size/2 - 1

### 你使用的语言

C++

### 你提交或者运行的代码

```bash
class Solution {
public:
    void maxHeapify(vector<int>& a, int i, int heapSize) {
        int l = i * 2 + 1, r = i * 2 + 2, largest = i;
        if (l < heapSize && a[l] > a[largest]) {
            largest = l;
        } 
        if (r < heapSize && a[r] > a[largest]) {
            largest = r;
        }
        if (largest != i) {
            swap(a[i], a[largest]);
            maxHeapify(a, largest, heapSize);
        }
    }

    void buildMaxHeap(vector<int>& a, int heapSize) {
        for (int i = heapSize / 2 - 1; i >= 0; --i) {
            maxHeapify(a, i, heapSize);
        } 
    }

    int findKthLargest(vector<int>& nums, int k) {
        int heapSize = nums.size();
        buildMaxHeap(nums, heapSize);
        for (int i = nums.size() - 1; i >= nums.size() - k + 1; --i) {
            swap(nums[0], nums[i]);
            --heapSize;
            maxHeapify(nums, 0, heapSize);
        }
        return nums[0];
    }
};
```

### 期望行为

修正官方解答中的错误代码部分

**Comment by liyuzhu-lc** [comment]
感谢您的宝贵反馈，我们已经将您的反馈提交给我们的负责团队，并将会对相关信息进行核查，有新的进展及时再与您联系。感谢您的理解与支持。

**Comment by amcones-lc** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by Mag357num** [comment]
> 你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

非常感谢，中文ID为357Magnum
![PixPin_2024-10-07_01-21-43](https://github.com/user-attachments/assets/906cdf5a-5ce2-4e16-875b-c5c407ccaea8)

**Comment by Mag357num** [comment]
> 你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。


个性域名为：leetcode.cn/u/357magnum/

**Comment by amcones-lc** [comment]
你好，当前该题已添加测试用例，奖励已发放。
