### ISSUE TITLE
Missing Test Case - 1764. Form Array by Concatenating Subarrays of Another Array

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#2440]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution is accepted but fails on the following test case:

[[-5, 0]]
[2, 0, -2, 5, -1, 2, 4, 3, 4, -5, -5]

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean canChoose(int[][] groups, int[] nums) {
        int begin = 0;
        int pre = 0;
        for(int i = 0; i < groups.length; i++){
            int k = begin;
            pre = begin;
            if(k >= nums.length) return false;
            for(int j = k; j < nums.length; j++){
                if(i + groups[i].length > nums.length) return false;
                int[] arr = Arrays.copyOfRange(nums,j,j + groups[i].length);
                if(Arrays.equals(arr,groups[i])){
                    begin = j + groups[i].length;
                    break;
                }else{
                    continue;
                }
            }
            if(k == begin) return false;
        }
        return true;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/108607538-f2bdb000-738e-11eb-9d10-32a74941226c.png)

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
