### ISSUE TITLE
3 cases that I couldn't understand

### ISSUE THREAD

**Issue by glorialearnscoding** [LeetCode-Feedback/LeetCode-Feedback#2442]
269. Alien Dictionary

There is a new alien language that uses the English alphabet. However, the order among letters are unknown to you.
You are given a list of strings words from the dictionary, where words are sorted lexicographically by the rules of this new language.
Derive the order of letters in this language, and return it. If the given input is invalid, return "". If there are multiple valid solutions, return any of them.

#### Category of the bug
- [ ] Question
- [ ] Solution

I couldn't understand those test cases. The expected output seems assume something that was not mentioned in the description. Please explain that to me or make it clearer.

["zy","zx"] Expected: "yxz"
I can only get that y<x from those two words. Then why is z appended at the end?

["ac","ab","zc","zb"] Expected: "acbz"
I can only get:
a<z
c<b
Where do you see that a<c and b<z?

["ab","adc"] Expected: "abcd"
I get nothing from two words. I think an empty string should be returned.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    string alienOrder(vector<string>& words) {
        unordered_map<char, vector<char>> edges; // <cur, chars that are greater than cur>
        unordered_map<char, int> inDegree;
        set<char> letters;
        
        for (int i = 0; i < words.size()-1; ++i) {
            string word1 = words[i];
            string word2 = words[i+1];
            for (int k = 0; k < word1.size() && k < word2.size(); ++k) {
                letters.insert(word1[k]);
                letters.insert(word2[k]);
                
                if (word1[k] != word2[k]) {
                    edges[word1[k]].push_back(word2[k]);
                    ++inDegree[word2[k]];
                    break;
                }
            }
        }
        
        for (auto it = inDegree.begin(); it != inDegree.end(); ++it) {
            if (it->second > 0) {
                letters.erase(it->first);
            }
        }

        if (letters.empty() == true) return "";
        
        queue<char> q;
        auto it = letters.begin(); // letters should have no more than 1 letters
        q.push(*it);
            
        string ret = "";
        char parent;
        while (q.empty() == false) {
            parent = q.front();
            q.pop();
            ret += parent;
            for (auto child : edges[parent]) {
                --inDegree[child];
                if (inDegree[child] == 0) q.push(child);
            }
        }
        return ret;
    }
};
```

#### Language used for code

C++

#### Expected behavior

I can only build the graph of the characters by comparing adjacent words. And we should not set the default inDegree for all letters to 0. (Because by setting them to 0 in map, and if it's not get increased later, we assume some relationships between them and letters with inDegree>0).

**Comment by lc-kay** [comment]
@glorialearnscoding Please check out the discuss section for further support. Here's a post that explains the first test case you had concerns about https://leetcode.com/problems/alien-dictionary/discuss/840199/Input%3A-%22zy%22%22zx%22-Expected%3A-%22yxz%22 Thank you for your time!

**Comment by glorialearnscoding** [comment]
Thank you @lc-kay for the reference. Based on the answer there, I think above information should be added to the problem description:
"all letters need to be included in the answer" (in any position)
Otherwise I believe more people will have the same question.
