### ISSUE TITLE
Missing Test Case - 413. Arithmetic Slices

### ISSUE THREAD

**Issue by rhatgadkar** [LeetCode-Feedback/LeetCode-Feedback#2443]
#### Your LeetCode username
rhatgadkar1

#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language

#### Description of the bug
A missing test case that doesn't account for overlapping arithmetic sequences.

The missing testcase is this:
[1, 2, 3, 5, 7]
There are two arithmetic sequences: [1, 2, 3] and [3, 5, 7]. These arithmetic sequences overlap, because both sequences share element 3, which is at position 2.

#### Code you used for Submit/Run operation

```
class Solution:
    def numberOfArithmeticSlices(self, A: List[int]) -> int:
        if len(A) < 3:
            return 0
        if len(A) == 3:
            if A[1] - A[0] == A[2] - A[1]:
                return 1
            return 0
        total_num_slices = 0
        s = 0
        e = 2
        
        while e < len(A):
            # find first slice
            while e < len(A) and A[s + 1] - A[s] != A[e] - A[e - 1]:
                s += 1
                e += 1
            slice_diff = A[s + 1] - A[s]

            # find number of slices starting from position s
            curr_num_slices = 0
            while e < len(A) and A[e] - A[e - 1] == slice_diff:
                curr_num_slices += (e - s - 1)
                e += 1

            total_num_slices += curr_num_slices
            s = e
            e = s + 2

        return total_num_slices
```

#### Language used for code
python3

#### Expected behavior
I expected that after submitting this solution, it should not be accepted, because this solution does not account for overlapping arithmetic sequences. But this solution was accepted.

**Comment by lc-kay** [comment]
Hi @rhatgadkar 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @rhatgadkar 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
