### ISSUE TITLE
Missing Test Case - 359. Logger Rate Limiter

### ISSUE THREAD

**Issue by jonathanqbo** [LeetCode-Feedback/LeetCode-Feedback#2444]
#### Your LeetCode username

user8483

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Test Case

#### Description of the bug

Missing Test Case. The code attached can pass all the existed test cases right now, but it actually has an issue and won't pass below test cases.

["Logger","shouldPrintMessage","shouldPrintMessage","shouldPrintMessage","shouldPrintMessage","shouldPrintMessage","shouldPrintMessage","shouldPrintMessage","shouldPrintMessage","shouldPrintMessage","shouldPrintMessage","shouldPrintMessage","shouldPrintMessage"]
[[],[1,"foo"],[1,"foo0"],[1,"foo1"],[1,"foo2"],[1,"foo3"],[1,"foo4"],[1,"foo5"],[1,"foo6"],[1,"foo7"],[1,"foo8"],[1,"foo9"],[1,"foo"]]

#### Code you used for Submit/Run operation

```
// 359. Logger Rate Limiter
class Logger {
    private LinkedHashMap<String, Integer> map;
    private int CAPACITY = 10;

    /** Initialize your data structure here. */
    public Logger() {
        map = new java.util.LinkedHashMap<String, Integer>(CAPACITY, 0.75f, true) {
            @Override
            protected boolean removeEldestEntry(Map.Entry<String, Integer> eldest) {
                return size() > CAPACITY;
            }
        };
    }

    /** Returns true if the message should be printed in the given timestamp, otherwise returns false.
     If this method returns false, the message will not be printed.
     The timestamp is in seconds granularity. */
    public boolean shouldPrintMessage(int timestamp, String message) {
        if(!map.containsKey(message)||timestamp - map.get(message) >= CAPACITY){
            map.put(message,timestamp);
            return true;
        }
        return false;
    }
}
```

#### Language used for code

Java

**Comment by lc-kay** [comment]
Hi @jonathanqbo 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @jonathanqbo 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
