### ISSUE TITLE
Missing Test Case - 2516. Take K of Each Character From Left and Right

### ISSUE THREAD

**Issue by erjjj** [LeetCode-Feedback/LeetCode-Feedback#24441]
### LeetCode 用户名

6racious-i3en20wh

### 问题号码、标题和链接

2516. 每种字符至少取 K 个 https://leetcode.cn/problems/take-k-of-each-character-from-left-and-right/description/

### Bug Category

缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*

### 描述

我用如下逻辑有错误的代码通过了测试。
class Solution {
public:
    bool judge(string s,int k){
        int i1=0;int i2=0;int i3=0;
        for(int i=0;i<s.size();++i){
            if(s[i]=='a'){
                i1+=1;
            }
            else if(s[i]=='b'){
                i2+=1;
            }
            else{
                i3+=1;
            }
        }
        if(i1>=k&&i2>=k&&i3>=k){
            return true;
        }
        return false;
    }
    int takeCharacters(string s, int k) {
        if(k==0){
            return 0;
        }
        if(!judge(s,k)){
            return -1;
        }
        int i1=0;int i2=0;int i3=0;
        int i=0;int j=s.size()-1;
        for(int j1=s.size()-1;j1>=0;j1--){
            if(s[j1]=='a'){
                i1+=1;
            }
            else if(s[j1]=='b'){
                i2+=1;
            }
            else{
                i3+=1;
            }
            if(i1>=k&&i2>=k&&i3>=k){
                j=j1;
                break;
            }
        }
        int res=s.size()-j;
        while(i<s.size()&&j<s.size()-2){
            if(s[i]=='a'){i1+=1;}
            else if(s[i]=='b'){i2+=1;}
            else{i3+=1;}
            while(i1>=k&&i2>=k&&i3>=k){
                if(j==s.size()){
                    return min(i+1,res);
                }
                if(s[j]=='a'){i1-=1;}
                else if(s[j]=='b'){i2-=1;}
                else{i3-=1;}
                j+=1;
            }
            j-=1;
            if(s[j]=='a'){i1+=1;}
            else if(s[j]=='b'){i2+=1;}
            else{i3+=1;}
            i+=1;
            if(i+s.size()-j<res) res=i+s.size()-j;
        }
        return res;
    }
};
上述代码可以通过测试，可是对于s="aabbccca"，k=2的案例，却会产生错误答案。所以我认为s="aabbccca"，k=2理应被作为测试用例

### 你使用的语言

C++

### 你提交或者运行的代码

```bash
class Solution {
public:
    bool judge(string s,int k){
        int i1=0;int i2=0;int i3=0;
        for(int i=0;i<s.size();++i){
            if(s[i]=='a'){
                i1+=1;
            }
            else if(s[i]=='b'){
                i2+=1;
            }
            else{
                i3+=1;
            }
        }
        if(i1>=k&&i2>=k&&i3>=k){
            return true;
        }
        return false;
    }
    int takeCharacters(string s, int k) {
        if(k==0){
            return 0;
        }
        if(!judge(s,k)){
            return -1;
        }
        int i1=0;int i2=0;int i3=0;
        int i=0;int j=s.size()-1;
        for(int j1=s.size()-1;j1>=0;j1--){
            if(s[j1]=='a'){
                i1+=1;
            }
            else if(s[j1]=='b'){
                i2+=1;
            }
            else{
                i3+=1;
            }
            if(i1>=k&&i2>=k&&i3>=k){
                j=j1;
                break;
            }
        }
        int res=s.size()-j;
        while(i<s.size()&&j<s.size()-2){
            if(s[i]=='a'){i1+=1;}
            else if(s[i]=='b'){i2+=1;}
            else{i3+=1;}
            while(i1>=k&&i2>=k&&i3>=k){
                if(j==s.size()){
                    return min(i+1,res);
                }
                if(s[j]=='a'){i1-=1;}
                else if(s[j]=='b'){i2-=1;}
                else{i3-=1;}
                j+=1;
            }
            j-=1;
            if(s[j]=='a'){i1+=1;}
            else if(s[j]=='b'){i2+=1;}
            else{i3+=1;}
            i+=1;
            if(i+s.size()-j<res) res=i+s.size()-j;
        }
        return res;
    }
};
```

### 期望行为

添加测试用例s="aabbccca"，k=2

### 屏幕截图

![image](https://github.com/user-attachments/assets/c75b6c5f-c089-458f-a045-bb5b2d8cd81a)

**Comment by amcones-lc** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by erjjj** [comment]
leetcode.cn/u/6racious-i3en20wh/




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月8日(星期二) 上午8:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LeetCode-Feedback/LeetCode-Feedback] Missing Test Case - 2516. Take K of Each Character From Left and Right (Issue #24441)














 
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by amcones-lc** [comment]
你好，当前该题已添加测试用例，奖励已发放。
