### ISSUE TITLE
Missing Test Case - 3303. Find the Occurrence of First Almost Equal Substring

### ISSUE THREAD

**Issue by glugalug** [LeetCode-Feedback/LeetCode-Feedback#24478]
### LeetCode Username

glugglug

### Problem Number, Title, and Link

3303. Find the Occurence of First Almost Equal Substring https://leetcode.com/problems/find-the-occurrence-of-first-almost-equal-substring/

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

I hit "contribute test case", not "bug report".

Attempting to add 2 test cases to [3303. Find the Occurrence of First Almost Equal Substring](https://leetcode.com/problems/find-the-occurrence-of-first-almost-equal-substring/) which I think will generally TLE if using the algorithm the hints seem to be leading towards.

How would I go about that?

### Language Used for Code

None

### Expected behavior

How can you view all the test cases / submit new ones?

I'm thinking s=1.49*10^5 'a's followed 'b', then by 1.5*10^5 'z's
Pattern =  7.5*10^4 'a's followed by 7.5*10^4 'z's is going to be near worst case for the prefix/suffix memoization suggested in hints.   Don't know if there are already cases like this.

**Comment by SagarChandra07** [comment]
I think this will help you.
https://bit.ly/47P0Nvo
Pass: changeme
I put the necessary dlls in the archive
