### ISSUE TITLE
Wrong Test cases for Problem 3306.

### ISSUE THREAD

**Issue by Niteesh-chowdary** [LeetCode-Feedback/LeetCode-Feedback#24479]
### LeetCode Username

Niteesh-Chowdary

### Problem Number, Title, and Link

https://leetcode.com/problems/count-of-substrings-containing-every-vowel-and-k-consonants-ii/description/

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

The return type of functions is int and for one testcase the expected output is 19998021657 which cannot be stored in an int variable in java.
The question is broken!!!!

### Language Used for Code

Java

### Expected behavior

The return type should be a long or the questoin should mention to mod the output and the expected ouput should also be moded.

**Comment by av1shek** [comment]
@Niteesh-chowdary 
https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/24480#issuecomment-2381116667
