### ISSUE TITLE
Wrong return type for weekly contest 417 3rd problem

### ISSUE THREAD

**Issue by SurendraPokala** [LeetCode-Feedback/LeetCode-Feedback#24480]
### LeetCode Username

surendrapokala555

### Problem Number, Title, and Link

https://leetcode.com/problems/count-of-substrings-containing-every-vowel-and-k-consonants-ii/description/

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

The return type of the problem during the contest was int in C++. Using int, 766 out of 768 test cases passed. However, after changing the return type to long long, all 768 test cases passed.

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
class Solution {
public:
    int countOfSubstrings(string word, int k) {
        int n = word.size();
        long long l = 0, r = 0, consonant = 0, res = 0;
        set<char> vowels = {'a', 'e', 'i', 'o', 'u'};
        map<char, long long> vowelMap; 
        vector<long long> pre(n+1);
        for (int i=n-1; i>=0; i--) {
            if (vowels.find(word[i]) != vowels.end()) {
                pre[i] = 1LL + pre[i+1];
            }
        }

        while (r < n) {
            if (vowels.find(word[r]) != vowels.end()) {
                vowelMap[word[r]]++;
            } else {
                consonant++;
            }
            while (consonant > k) {
                if (vowels.find(word[l]) != vowels.end()) {
                    vowelMap[word[l]]--;  
                } else {
                    consonant--;
                }
                l++;
            }

            while (consonant == k && isValid(vowelMap)) {
                res += pre[r+1] + 1LL;
                if (vowels.find(word[l]) != vowels.end()) {
                    vowelMap[word[l]]--;  
                } else {
                    consonant--;
                }
                l++;
            }

            r++;
        }

        return res;
    }
    bool isValid(map<char, long long>& vowelMap) {
        for (char c : {'a', 'e', 'i', 'o', 'u'}) {
            if (vowelMap[c] <= 0) {
                return false;
            }
        }
        return true;
    }
};
```

### Expected behavior

The problem return should be long long in C++!

### Screenshots

![leetcodeimg](https://github.com/user-attachments/assets/a922e28a-55d9-474f-b261-a745248107d7)
![leetcode](https://github.com/user-attachments/assets/e96d8996-93be-4923-8d6f-34085085799f)

**Comment by av1shek** [comment]
@SurendraPokala you might have used your code from 2nd problem, where it was int, however for 3rd problem it was long from starting only.

**Comment by SurendraPokala** [comment]
@av1shek Ok got it, thanks man for clarifying me.
