### ISSUE TITLE
Additional Solution - 735 - O(1) space complexity solution

### ISSUE THREAD

**Issue by mahmad97** [LeetCode-Feedback/LeetCode-Feedback#24499]
### LeetCode Username

mahmad97

### Problem Number, Title, and Link

https://leetcode.com/problems/asteroid-collision/

### Bug Category

Editorial

### Bug Description

The editorial does not list the O(1) space complexity solution which is possible by modifying the asteroids array in-place. Question may also be edited to include this as a possible follow-up question.

### Language Used for Code

Python/Python3

### Code used for Submit/Run operation

```bash
class Solution:
    def asteroidCollision(self, asteroids: List[int]) -> List[int]:
        i = 0
        while i < len(asteroids) - 1:
            if i < 0:
                i += 1
                continue
            
            first = asteroids[i]
            second = asteroids[i + 1]
            if first < 0:
                i += 1 
            elif second > 0:
                i += 1
            elif first > -1 * second:
                asteroids.pop(i + 1)
            elif first < -1 * second:
                asteroids.pop(i)
                i -= 1
            else:
                asteroids.pop(i + 1)
                asteroids.pop(i)
                i -= 1
        
        return asteroids
```

### Expected behavior

N/A

### Screenshots

N/A

### Additional context

N/A

**Comment by stormsunshine** [comment]
I don't agree that such a solution should be added and such a follow-up should be added. Reasons are as follows.

1. For some languages like Java and C#, arrays have fixed lengths, so the pop operation is not applicable.
2. The pop operation actually has O(n) time complexity each time, not O(1) time complexity. It is meaningless to increase time complexity by reducing space complexity.

**Comment by mahmad97** [comment]
I see, you are correct. Thanks for the clarification.
