### ISSUE TITLE
33. Search in Rotated Sorted Array ( LeetCode )

### ISSUE THREAD

**Issue by nithinkumarrockstar** [LeetCode-Feedback/LeetCode-Feedback#2449]
class Solution {
public:
    int search(vector<int>& nums, int target) {
        bool flag=true;
        int i;
        for(i=0;i<nums.size();i++)
        {
            if(target==nums[i])
            {
                flag=false;
                break;
            }
        }
        if(flag)
            return -1;
        else
            return i;
    }
};

**Comment by lc-kay** [comment]
@nithinkumarrockstar Please post your solution to the discuss section of the problem. If you are reporting an issue, please provide a more detailed report. Thank you!

**Comment by nithinkumarrockstar** [comment]
> @nithinkumarrockstar Please post your solution to the discuss section of the problem. If you are reporting an issue, please provide a more detailed report. Thank

> @nithinkumarrockstar Please post your solution to the discuss section of the problem. If you are reporting an issue, please provide a more detailed report. Thank you!

Yeah,,I will surley post on discuss section of the problem...
