### ISSUE TITLE
1438. Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit

### ISSUE THREAD

**Issue by Mohit-Patil** [LeetCode-Feedback/LeetCode-Feedback#245]
**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
Below solution gets accepted due to weak test cases.

**what language is your code written in**
C++

**The code you submit/run**
```
// longestSubarray
class Solution {
public:
    int longestSubarray(vector<int>& nums, int limit) {
        int n = nums.size();
        int ans = 0;
        for(int i = 0;i<n;i++){
            int mx = nums[i],mn = nums[i];
            for(int j =i;j<n;j++){
                //cout<<mx - mn;
                mx = max(nums[j],mx);
                mn = min(nums[j],mn);
                if(mx - mn > limit){
                    break;
                }
                //cout<<i<<" "<<j<<endl;
                ans = max(ans,j - i);
                if(ans + 1 == nums.size())
                    return ans + 1;    
            }
        }
        return ans + 1;
        
    }
};
```

**Expected behavior**
The Above Solution is a quadratic solution with just one check that if ans == size of array then break.
This Solution was accepted in the recent contest due to weak test cases.
This solution times out for the below test case. 

**Additional context**
Link to the Submission - https://leetcode.com/submissions/detail/333596273/
Below is the input file.
[input.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/4569661/input.txt)

**Comment by CooperCooperCooper** [comment]
Hi @Mohit-Patil ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @Mohit-Patil ,
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
