### ISSUE TITLE
Missing Limits Description - 149. Max Points on a Line

### ISSUE THREAD

**Issue by DmitriyH** [LeetCode-Feedback/LeetCode-Feedback#2450]
Could not find a limits decription for the problem.
What is the max value for "n"?

**Comment by lc-kay** [comment]
Hi @DmitriyH 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @DmitriyH 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
