### ISSUE TITLE
Missing Test Case - 334. Increasing Triplet Subsequence

### ISSUE THREAD

**Issue by csq-pual** [LeetCode-Feedback/LeetCode-Feedback#24529]
### LeetCode 用户名

Zealous JepsenEm9

### 问题号码、标题和链接

https://leetcode.cn/problems/increasing-triplet-subsequence/solutions/1204375/di-zeng-de-san-yuan-zi-xu-lie-by-leetcod-dp2r/?envType=study-plan-v2&envId=leetcode-75

### Bug Category

力扣官方题解

### 描述

题解的贪心算法在[2,1,4,1,5]有问题

### 你使用的语言

Java

### 期望行为

修改题解

**Comment by liyuzhu-lc** [comment]
感谢您的宝贵反馈，我们已经将您的反馈提交给我们的负责团队，并将会对相关信息进行核查，有新的进展及时再与您联系。感谢您的理解与支持。

**Comment by amcones-lc** [comment]
您好，在与相关团队核实后：***不处理***（`2,4,5` 是递增三元子序列）。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
