### ISSUE TITLE
Problem Description - 1036. Escape a Large Maze

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#2453]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The description of the problem is inconsistent with online judge (both "Run Code" and "Submit"). Problem description states that "... Each move, we can walk to a 4-directionally adjacent square in the grid that isn't in the given list of blocked squares ...". This implies that if target square is in the list of blocked squares, it is not possible to walk to this square. Online judge behaves differently on test case 31, please see the image below

#### Code you used for Submit/Run operation

```
	class Solution {
	    public boolean isEscapePossible(int[][] blocked, int[] source, int[] target) {
	    	Set<Long> set = new HashSet<Long>();
	    	for(int[] b : blocked){
	    		set.add((long)b[0]<<32|b[1]);
	    	}
	    	if(set.contains((long)source[0]<<32|source[1]))return false;
	    	if(set.contains((long)target[0]<<32|target[1]))return false;
	    	
	    	boolean[][] ss = go(source[0], source[1], set);
	    	boolean[][] ts = go(target[0], target[1], set);
	    	if(Math.abs(source[0] - target[0]) > 200 || Math.abs(source[1] - target[1]) > 200){
	    		int pt = 0;
	    		for(int i = 0;i < 411;i++){
	    			for(int j = 0;j < 411;j++){
	    				if(i == 0 || j == 0 || i == 410 || j == 410){
	    					if(ss[i][j])pt |= 1;
	    					if(ts[i][j])pt |= 2;
	    				}
	    			}
	    		}
	    		return pt == 3;
	    	}else{
	    		return ss[target[0]-source[0]+205][target[1]-source[1]+205];
	    	}
	    }
	    
	    boolean[][] go(int sr, int sc, Set<Long> obs)
	    {
	    	boolean[][] can = new boolean[411][411];
	    	can[205][205] = true;
	    	Queue<int[]> q = new ArrayDeque<>();
	    	q.add(new int[]{205, 205});
	    	int[] dr = { 1, 0, -1, 0 };
			int[] dc = { 0, 1, 0, -1 };
			while(!q.isEmpty()){
				int[] cur = q.poll();
				int r = cur[0], c = cur[1];
				for(int k = 0;k < 4;k++){
					int nr = r + dr[k], nc = c + dc[k];
					if(nr >= 0 && nr < 411 && nc >= 0 && nc < 411 && !can[nr][nc]
							&& sr-205+nr >= 0 && sr-205+nr < 1000000
							&& sc-205+nc >= 0 && sc-205+nc < 1000000
							&& !obs.contains((long)(sr-205+nr)<<32|(sc-205+nc))
							){
						can[nr][nc] = true;
						q.add(new int[]{nr, nc});
					}
				}
			}
			return can;
	    }
	}	
```

#### Language used for code

Java

#### Expected behavior

Problem description should be changed to allow to walk to target square even if it is in the list of blocked squares (target square will be the only exception to "... Each move, we can walk to a 4-directionally adjacent square in the grid that isn't in the given list of blocked squares ..." rule)

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/108642958-4951e980-7476-11eb-98e3-dee7b1b29a8f.png)

#### Additional context

See also: https://leetcode.com/problems/escape-a-large-maze/discuss/920712/Wrong-Test-Case

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by IgorRud** [comment]
@lc-kay , it does not look like 100 LeetCoins were added to my account, can you please double check?

**Comment by lc-kay** [comment]
@IgorRud Sorry about that, you have just been rewarded.
