### ISSUE TITLE
confusing test case in 457. Circular Array Loop

### ISSUE THREAD

**Issue by glorialearnscoding** [LeetCode-Feedback/LeetCode-Feedback#2454]
You are given a circular array nums of positive and negative integers. If a number k at an index is positive, then move forward k steps. Conversely, if it's negative (-k), move backward k steps. Since the array is circular, you may assume that the last element's next element is the first element, and the first element's previous element is the last element.
Determine if there is a loop (or a cycle) in nums. A cycle must start and end at the same index and the cycle's length > 1. Furthermore, movements in a cycle must all follow a single direction. In other words, a cycle must not consist of both forward and backward movements.

#### Category of the bug
- [ ] Question

#### Description of the bug

"Since the array is circular, you may assume that the last element's next element is the first element, and the first element's previous element is the last element."

Example 2:
Input: [-1,2]
Output: false
Explanation: The movement from index 1 -> 1 -> 1 ... is not a cycle, because the cycle's length is 1. By definition the cycle's length must be greater than 1.

Based on the above description of circular array, element 2 (index 1) has next element -1 (index 0). And moving from element 2 to itself requires two jumps (from index 1 to index 0, then to index 1). So the cycle length should be 2, right?
But your explanation seems assumes that you can stay at index 1 without any moves.

**Comment by lc-kay** [comment]
Hi @glorialearnscoding 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @glorialearnscoding 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by glorialearnscoding** [comment]
Wow! Thank you @lc-kay !
Leetcode ID: glorialearncoding
