### ISSUE TITLE
1528. Shuffle String

### ISSUE THREAD

**Issue by Suraj520** [LeetCode-Feedback/LeetCode-Feedback#2455]
The solution below gives output leetcode for **codeleet** but the test case shows leetcdoe i..e flipped positions of d and o which violates the logic of the question. Kindly correct this!
```
class Solution:
    def restoreString(self, s: str, indices: List[int]) -> str:
        out_str = ""
        for idx in indices:
            for i,elem in enumerate(s):
                if idx == i:
                    out_str+=s[idx]
                    
        return out_str
        ````

**Comment by lc-kay** [comment]
<img width="719" alt="Screen Shot 2021-02-23 at 1 30 27 PM" src="https://user-images.githubusercontent.com/70870126/108910873-53d9c380-75db-11eb-8493-f55ea309a16d.png">
@Suraj520 The expected output is correct. Your code resulted in the output "leetcdoe" which is incorrect, resulting in wrong answer.
