### ISSUE TITLE
Missing test case- 1764.Form Array by Concatenating Subarrays of Another Array

### ISSUE THREAD

**Issue by Aniket-Jain-byte** [LeetCode-Feedback/LeetCode-Feedback#2458]
#### Your LeetCode username

Aniket Jain

#### Category of the bug
- [ ] Question 

#### Description of the bug

I mis-understood this question at first that the subarray's in  array nums should be disjoint sets not disjoint subarrays. So i submitted the wrong code and it got accepted. later on i got to know its disjoint subarrays. So my code got accepted though its wrong
The testcase is -
[[1,2,3],[3,4]] 
[1,2,3,3,4]

#### Code you used for Submit/Run operation

```

Class Solution {
public:
    bool canChoose(vector<vector<int>>& groups, vector<int>& nums) {
        
        for(int i=0; i<groups.size(); ++i) {
            for(int j=0; j<i; ++j) {
                for(int x : groups[i]) {
                    for(int y : groups[j]) {
                        if(x == y) {
                            return false;
                        }
                    }
                }
            }
        }
        //cout << "a";
        
        int i=0;
        for(int j=0; j<nums.size(); ++j) {
            int k = 0;
            while(k<groups[i].size() && groups[i][k] == nums[k+j]) {
                ++k;
            }
            if(k == groups[i].size()) {
                ++i;
                j += k-1;
            }
            if(i == groups.size())
                return true;
        }
        return false;
    }
};
```
#### Language used for code

C++

#### Expected behavior

The answer should have come true but my code returned false

#### Screenshots

![image](https://user-images.githubusercontent.com/76682881/108653734-45ad7980-74ed-11eb-9312-63b4d677f9d5.png)

**Comment by lc-kay** [comment]
Hi @Aniket-Jain-byte 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by Aniket-Jain-byte** [comment]
@lc-kay  thanks a lot for responding any idea by when would I get updated about this

**Comment by lc-kay** [comment]
@Aniket-Jain-byte We will follow up in 1-2 business days. Thank you for your time!

**Comment by lc-kay** [comment]
Hi @Aniket-Jain-byte 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by Aniket-Jain-byte** [comment]
@lc-kay My user-id: helloaniorigamiwpu
![image](https://user-images.githubusercontent.com/76682881/109263249-f63ab680-7828-11eb-8e56-a5fcd8dc1cfb.png)

**Comment by Aniket-Jain-byte** [comment]
@lc-kay  my testcase has been contributed (now submission fails) but still i didn't receive my leet coins

**Comment by lc-kay** [comment]
@Aniket-Jain-byte Thank you for your contribution, we have rewarded your account with 100 LeetCoins.

**Comment by Aniket-Jain-byte** [comment]
@lc-kay thanks for your time
