### ISSUE TITLE
383. Ransom Note Test Case

### ISSUE THREAD

**Issue by gannaramu** [LeetCode-Feedback/LeetCode-Feedback#246]
**What kind of the bug**
- [x] problem
- [x] solution
- [ ] language

**Describe the bug**
We need to add more important test cases.

**what language is your code written in**
C++

**The code you submit/run**
```
// Two Sum
class Solution {
public:
      bool canConstruct(string ransomNote, string magazine) {
        
        
        
        if(ransomNote.size()>magazine.size())
            return false;
        
        
            if(ransomNote.size()==0)
            return true;
        
        
        if(ransomNote.size()==magazine.size())
            return (ransomNote==magazine);
            
            unordered_map<int,int> dict;
        
        
        for(int i=0;i<magazine.size();i++)
            dict[magazine[i]]++;
        
        for(int i=0;i<ransomNote.size();i++){
            dict[ransomNote[i]]--;
                if( dict[ransomNote[i]]<0)
                    return false;
        }
        
        return true;
    }
};
```

**Expected behavior**
This code needs to fail for the test case ransom note = "aab" and magazine = "baa" but it seems to be an accepted solution this is inspired by the discussion forum 

**Screenshots**

**Additional context**
more test cases need to be added.

**Comment by CooperCooperCooper** [comment]
Hi @gannaramu ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @gannaramu ,
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
