### ISSUE TITLE
1766. 互质树 测试用例bug

### ISSUE THREAD

**Issue by windsf** [LeetCode-Feedback/LeetCode-Feedback#2460]
**你的 LeetCode 用户名**
weerf

**Bug 类型**
- [ ] 1766. 互质树
- [ ] 题解
- [ ] c++

**描述**
测试用例答案感觉有问题
[18,10,23,47,11,20,7,44,14,43,43,42,2,23,5,31,18,40,49,27,50,21,19,35,23,30,31,8,7,50,7,11,4,43,1,5,24,44,24,25,24,19,48,5,37,13,50,6,20,38,43,45,34,15,42,41,5,44,16,21,26,31,12,35,13,36,2,21,29,36,7,24,1,37,40,6,19,30,12,42,30,50,20,15,34,36,49,2,34,36,38,8,11,33,46,19,24,41,2,31,14,32,9,29,12,6,45,47,32,24,37,4,25,50,24,10,31,40,5,12,22,7,23,2,27,42,8,6,1,15,16,32,32,38,29,24,33,22,33,29,17]
[[57,0],[5,57],[76,5],[85,76],[46,85],[127,85],[25,0],[114,25],[7,114],[45,114],[100,25],[122,100],[17,122],[12,17],[48,100],[40,48],[60,40],[88,48],[108,48],[10,108],[11,10],[121,11],[9,121],[109,11],[111,109],[91,109],[118,91],[53,118],[26,53],[47,26],[126,47],[133,109],[123,133],[59,123],[81,48],[31,81],[15,31],[24,15],[132,81],[119,132],[21,119],[63,81],[128,63],[73,128],[34,63],[72,34],[38,72],[97,72],[3,97],[30,3],[13,30],[80,13],[33,80],[66,80],[102,66],[8,80],[77,8],[79,77],[42,79],[19,42],[78,19],[20,78],[55,79],[37,55],[49,37],[89,49],[36,89],[83,89],[95,49],[64,95],[28,64],[32,28],[92,32],[93,92],[86,93],[39,86],[87,39],[2,87],[134,93],[135,49],[110,3],[29,110],[52,29],[136,29],[99,136],[50,99],[84,50],[56,84],[51,99],[112,51],[101,112],[41,29],[74,41],[103,74],[129,74],[6,129],[137,129],[61,29],[104,61],[131,104],[58,104],[14,58],[18,14],[138,18],[117,138],[125,138],[106,125],[120,18],[130,120],[124,130],[62,124],[82,62],[4,62],[113,4],[139,130],[1,104],[67,1],[70,1],[43,70],[96,70],[98,96],[69,98],[94,69],[115,94],[75,1],[44,75],[68,44],[16,68],[54,68],[65,68],[27,65],[71,65],[105,65],[35,105],[107,65],[116,65],[90,116],[23,90],[140,1],[22,140]]

**你使用的语言**
C++

**你提交或者运行的代码**
void Factorization(int num, vector<set<int>>& vec)
{
    if (vec[num].size()) {
        return;
    }
    int m = sqrt(num);
    for (int i = 2; i <= m; ++i) {
        if (num % i) {
            continue;
        }
        int n = num / i;
        vec[num].emplace(i);
        if (vec[n].size() == 0) {
            Factorization(n, vec);
        }
        if (vec[n].size() != 0) {
            for (set<int>::iterator iter = vec[n].begin(); iter != vec[n].end(); iter++) {
                vec[num].emplace(*iter);
            }
        }
            vec[num].emplace(n);
        break;
    }
}
class Solution {
public:
    vector<int> getCoprimes(vector<int>& nums, vector<vector<int>>& edges) {
   int n = nums.size();
    vector<int> v(n);
    vector<set<int>> vec(51);
    for (int i = 4; i < 51; ++i)
    {
        Factorization(i, vec);
    }
    vector<vector<bool>> dp(51, vector<bool>(51, true));
    for (int i = 0; i < 51; ++i) {
        for (int j = i; j < 51; ++j) {
            if (i == j || vec[j].find(i) != vec[j].end()) {
                dp[i][j] = false;
                dp[j][i] = false;
                continue;
            }
            for (set<int>::iterator iter=vec[i].begin();iter!=vec[i].end();++iter)
            {
                if (vec[j].find(*iter) != vec[j].end()) {
                    dp[i][j] = false;
                    dp[j][i] = false;
                    break;
                }
            }
        }
    }
    vector<vector<int>> sv(n);
    for(auto num:edges)
    {
        sv[num[0]].push_back(num[1]);
        sv[num[1]].push_back(num[0]);
    }
    deque<int> de;
    vector<int> fv(n-1,-1);
    for (auto t : sv[0]) {
        fv[t-1] = 0;
        de.push_back(t);
    }
    while (de.size()) {
        int t = *de.begin();
        de.pop_front();
        for (auto num : sv[t]) {
            if (num && fv[num - 1] == -1) {
                fv[num - 1] = t;
                de.push_back(num);
            }
        }
    }
    v[0] = -1;
    for (int i = 1; i < n; ++i) {
        int p = fv[i-1];
        while (p && !dp[nums[i]][nums[p]]) {
            p = fv[p-1];
        }
        if (p == 0 && !dp[nums[i]][nums[p]]) {
            v[i] = -1;
            continue;
        }
        v[i] = p;
    }
    return v;
    }
};

**期望行为**
第一个与索引为72的节点互质的节点应该是索引为63的节点，而不是索引为34的节点。索引为72的节点和索引为34的节点值都为1，并不互质

![image](https://user-images.githubusercontent.com/34504932/108665451-edd43a00-750f-11eb-9e11-07ed95fce233.png)

**额外的上下文**
望尽快回复

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，1 和 1 是互质的。
后续刷题学习中遇到问题，可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
