### ISSUE TITLE
Missing Test Case - 524. Longest Word in Dictionary through Deleting

### ISSUE THREAD

**Issue by andriitugai** [LeetCode-Feedback/LeetCode-Feedback#2461]
#### Your LeetCode username
andrii_tugai

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language

#### Description of the bug
The function should return null if there are no strings in the dictionary that can be formed by deleting some characters of the given string.
For example, in case of s = "abc", d = ["xyz"] the function should return null

#### Language used for code
Python 3

```
class Solution:
    def findLongestWord(self, s: str, d: List[str]) -> str:
        maxlen = 0
        maxword = None  #  can be switched to "" to satisfy some testcases
        for word in d:
            sp = 0
            wp = 0            
            while sp < len(s):
                
                if s[sp] == word[wp]:
                    wp += 1
                    if wp == len(word):
                        if len(word) > maxlen:
                            maxlen = len(word)
                            maxword = word
                        elif len(word) == maxlen:
                            maxword = min(word, maxword)
                            
                        break  #  it's a possible word
                        
                sp += 1
                    
        return maxword 
```

#### Expected behavior
The function should return null if there are no strings in the dictionary that can be formed by deleting some characters of the given string.
For example, in case of s = "abc", d = ["xyz"] the function should return null as far as no such string in the dictionary

Some testcases suppose to get empty string in this case. But empty string is not present in the dictionary.

**Comment by Leader-board** [comment]
> If there is no possible result, return the empty string.

I think it's already mentioned in the question?

**Comment by lc-kay** [comment]
@andriitugai Please refer to @Leader-board comment. Thank you both for your time.
