### ISSUE TITLE
Missing Test Case - 524. Longest Word in Dictionary through Deleting

### ISSUE THREAD

**Issue by dickyadrian** [LeetCode-Feedback/LeetCode-Feedback#2463]
#### Your LeetCode username
dickyadrian0204

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
I think I found a test case with wrong answer

#### Code you used for Submit/Run operation
```
class Solution:
    def create_counter(self, string):
        string_counter = {}
        for c in string:
            try:
                string_counter[c] += 1
            except:
                string_counter[c] = 1
        return string_counter
    
    def test_string(self, ans_counter, str_counter):
        try:
            for char, count in ans_counter.items():
                if str_counter[char] < count:
                    return False
            return True
        except:
            return False
    
    def findLongestWord(self, s: str, d: List[str]) -> str:
        if len(s) <= 0:
            return ""
        string_counter = self.create_counter(s)
        answer = ""
        len_answer = 0
        for ans in d:
            if len(ans) < len(answer):
                continue
            elif len(ans) == len(answer) and ans > answer:
                continue
            ans_counter = self.create_counter(ans)
            if self.test_string(ans_counter, string_counter):
                print(ans)
                answer = ans
                len_answer = len(ans)
        return answer
```

#### Language used for code
Python

#### Expected behavior
Input:
s: "aewfafwafjlwajflwajflwafj"
d: ["apple","ewaf","awefawfwaf","awef","awefe","ewafeffewafewf"]
Shouldn't "awefawfwaf" be the answer? In this test case "ewaf" is the accepted answer
Or is the deletion must be in order of `s`? If so, I think the instructions are still too vague since it only says: <br> 
"find the longest string in the dictionary that can be formed by deleting some characters of the given string. If there are more than one possible results, return the longest word with the smallest lexicographical order. If there is no possible result, return the empty string."

#### Screenshots
![Screen Shot 2021-02-22 at 5 44 39 PM](https://user-images.githubusercontent.com/23248055/108697592-a5c80e00-7535-11eb-8223-ea20bc90fbd0.png)

**Comment by Aniket-Jain-byte** [comment]
This even happened with me

**Comment by dawndebanik** [comment]
After deletion, you're not allowed to re-arrange the characters in the string. In other words, the characters left behind must be in order.

**Comment by lc-kay** [comment]
@dawndebanik @Aniket-Jain-byte Please check out this discuss post for clarifications on this test case: https://leetcode.com/problems/longest-word-in-dictionary-through-deleting/discuss/99592/a-test-case-error. Thank you for your time.
