### ISSUE TITLE
[BUG] - 为了保证账号安全，本次请使用手机验证码登录

### ISSUE THREAD

**Issue by jay6413682** [LeetCode-Feedback/LeetCode-Feedback#24631]
### LeetCode 用户名

iamabigstone@gmail.com

### 问题号码、标题和链接

无法用美国站帐号登录leetcode.cn

### Bug Category

问题描述

### 描述

无法用美国站帐号登录leetcode.cn。每次尝试登陆都显示“为了保证账号安全，本次请使用手机验证码登录”

我已经试过根据 https://support.leetcode.cn/hc/kb/article/1642640/ 的建议联系 support@leetcode.cn。 但是已经两个礼拜都没有任何回复，能帮我查查吗？谢谢

### 你使用的语言

None

### 期望行为

以前都可以登陆

### 屏幕截图

![image](https://github.com/user-attachments/assets/84a07b20-38d4-4549-95c1-d3ba8c24ac33)

**Comment by liyuzhu-lc** [comment]
您好，请问如下是您提交的问题反馈吗？由于您提供的信息无法定位到您需要换绑手机号的具体账号没能帮您成功换绑。建议您查阅提交反馈的邮箱，核对信息并回复我们哦～
![Uploading screenshot-20241008-181234.png…]()

**Comment by jay6413682** [comment]
> 您好，请问如下是您提交的问题反馈吗？由于您提供的信息无法定位到您需要换绑手机号的具体账号没能帮您成功换绑。建议您查阅提交反馈的邮箱，核对信息并回复我们哦～

我确定 iamabigstone@gmail.com 是正确的leetcode.com账号，我还能正常登陆到leetcode.com :
<img width="1256" alt="image" src="https://github.com/user-attachments/assets/ddf2b3c4-f64f-4c8c-bbf1-2c5ddc1c2f24">

但是用这个美国站账户登陆中国站却每次都报错：“为了保证账号安全，本次请使用手机验证码登录”。以前都是可以的。

**Comment by liyuzhu-lc** [comment]
您好，请问如下是您提交的问题反馈吗？由于您提供的信息无法定位到您需要换绑手机号的具体账号没能帮您成功换绑。建议您查阅提交反馈的邮箱，核对信息并回复我们哦～

**Comment by liyuzhu-lc** [comment]
您好，请问如下是您提交的问题反馈吗？由于您提供的信息无法定位到您需要换绑手机号的具体账号没能帮您成功换绑。需要您查阅提交反馈的邮箱，核对信息并回复我们哦～
![screenshot-20241008-181234](https://github.com/user-attachments/assets/27695aff-bb6e-407f-83bf-90e3cdd3b03a)

**Comment by jay6413682** [comment]
这不是我提交的问题反馈，我是用iamabigstone@gmail.com 邮箱 发到 support@leetcode.cn

**Comment by liyuzhu-lc** [comment]
您好，需要您再查收一下邮箱哦～

**Comment by jay6413682** [comment]
好的，谢谢
