### ISSUE TITLE
 Test is wrong : Longest Word in Dictionary through Deleting

### ISSUE THREAD

**Issue by kaanbalkaya** [LeetCode-Feedback/LeetCode-Feedback#2464]
#### Your LeetCode username

kaanbalkaya

#### Category of the bug
- [ ] Question
- [ X] Solution
- [ ] Language

#### Description of the bug

In the 29th test case; expected answer which is "nbmxgkduynigvzuyblwjepn"  seems wrong.  In my solution the answer is "jpthiudqzzeugzwwsngebdeai", that is longer and legal.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    string findLongestWord(string s, vector<string>& d) {
        set<string> sset;
        for(string str:d){
            int pos=0;
            string tstr{""};
            for(char ch:str){
                pos=s.find(ch,pos);
                if(pos==string::npos){
                    tstr.clear();
                    continue;
                }
                tstr+=ch;
            }
            if(!tstr.empty())
                sset.insert(tstr);
        }
        if(sset.size()==0)
            return "";
        return *max_element(sset.begin(),sset.end(),[&](string s1,string s2){return s1.size()<s2.size();});
    }
};
```

#### Language used for code

C++

#### Expected behavior

In my solution the answer is "jpthiudqzzeugzwwsngebdeai", that is longer and legal. but at the 29th (of 31) test case, shown as expected answer which is "nbmxgkduynigvzuyblwjepn"  seems wrong.

**Comment by lc-kay** [comment]
@kaanbalkaya The expected output is correct. Please refer to the discuss section to raise your question or refer to user-submitted codes. In addition, please keep in mind that when deleting some characters from the input string, the order of the remaining characters is unchanged. Thank you for your time.
