### ISSUE TITLE
[BUG] - 测试用例不够严格，On的做法也能AC

### ISSUE THREAD

**Issue by Mag357num** [LeetCode-Feedback/LeetCode-Feedback#24652]
### LeetCode 用户名

357Magnum

### 问题号码、标题和链接

34. 在排序数组中查找元素的第一个和最后一个位置 https://leetcode.cn/problems/find-first-and-last-position-of-element-in-sorted-array/description/

### Bug Category

缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*

### 描述

测试用例的耗时不够严格，题目要求Ologn的算法，但是实际上最差On的算法也能过，完全不能覆盖考察点
错误的最差On算法示例：
```
class Solution {
public:
    vector<int> searchRange(vector<int>& nums, int target) {

				// 1. 先按普通二分流程走
        int left = 0, right = nums.size() - 1, mid = right;
        if (nums.size() < 1 || nums[left] > target || nums[right] < target)
            return {-1, -1};
        while (left <= right) {
            mid = left + ((right - left) >> 1);
            if (nums[mid] > target)
                right = mid - 1;
            else if (nums[mid] < target)
                left = mid + 1;
            else
                break;
        }

				// 2. 找到一个等于target的元素之后再往两边遍历找端点
        if (nums[mid] != target)
            return {-1, -1};
        else {
            left = mid, right = mid;
            while (left - 1 > -1 && nums[left - 1] == target)
                --left;
            while (right + 1 < nums.size() && nums[right + 1] == target)
                ++right;
        }
        return {left, right};
    }
};
```

### 你使用的语言

C++

### 你提交或者运行的代码

```bash
class Solution {
public:
    vector<int> searchRange(vector<int>& nums, int target) {

				// 1. 先按普通二分流程走
        int left = 0, right = nums.size() - 1, mid = right;
        if (nums.size() < 1 || nums[left] > target || nums[right] < target)
            return {-1, -1};
        while (left <= right) {
            mid = left + ((right - left) >> 1);
            if (nums[mid] > target)
                right = mid - 1;
            else if (nums[mid] < target)
                left = mid + 1;
            else
                break;
        }

				// 2. 找到一个等于target的元素之后再往两边遍历找端点
        if (nums[mid] != target)
            return {-1, -1};
        else {
            left = mid, right = mid;
            while (left - 1 > -1 && nums[left - 1] == target)
                --left;
            while (right + 1 < nums.size() && nums[right + 1] == target)
                ++right;
        }
        return {left, right};
    }
};
```

### 期望行为

期望上面的算法无法通过，需要加一个所有元素都是target的，比较长的测试用例，在这种情况下，算法的复杂度为On，不应当通过

**Comment by liyuzhu-lc** [comment]
感谢您的宝贵反馈，我们已经将您的反馈提交给我们的负责团队，并将会对相关信息进行核查，有新的进展及时再与您联系。感谢您的理解与支持。

**Comment by amcones-lc** [comment]
We have received feedback, please wait for us to process.

**Comment by Mag357num** [comment]
> Epiphania_Ekenimoh commented: Hi there,
> 
> Thank you for taking the time to share your feedback with us.
> 
> After careful consideration, we have decided not to move forward with the changes suggested in your feedback at this time.
> 
> Please know that your input is important to us. Your continued feedback is greatly appreciated as we work towards improving our platform.
> 
> Best regards, LeetCode Support Team

could you please let me know the reason why deciding not to move forward with this feedback？because the question explicitly tell user to use Ologn complexity, but On complexity algorithm could pass.
