### ISSUE TITLE
Wrong testcase 23 in Longest Word in Dictionary through Deleting

### ISSUE THREAD

**Issue by ShivamS136** [LeetCode-Feedback/LeetCode-Feedback#2465]
#### Your LeetCode username
shivams136

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Test Case

#### Description of the bug
The question says that it is a string **dictionary**, so the words in this should be lexicographically sorted but in the below test case it's not. Please correct it.

```
"bab"
["ba","ab","a","b"]
```

#### Code you used for Submit/Run operation

```cpp
class Solution {
public:
    string findLongestWord(string s, vector<string>& d) {
        int len=0;
        string res="";
        for(string word : d){
            int l =word.length();
            if(l>len && isSubSeq(word,s)){
                res=word;
                len=l;
            }
        }
        return res;
    }
    
    bool isSubSeq(string s1, string s2){
        int l1=s1.length();
        int l2=s2.length();
        int i=0,j=0;
        while(i<l2 && j<l1){
            if(s1[j]==s2[i]){
                j++;
            }
            i++;
        }
        return j==l1 ? true:false;
    }
};
```

#### Language used for code
C++

#### Expected behavior

Test case should be `["a","ab","b","ba"]`

#### Screenshots
![image](https://user-images.githubusercontent.com/32218762/108741184-737dd700-755c-11eb-932f-03687744f21d.png)

**Comment by lc-kay** [comment]
@ShivamS136 The expected output is correct. Please refer to the discuss section to raise your question or refer to user-submitted codes. In addition, please keep in mind that when deleting some characters from the input string, the order of the remaining characters is unchanged. https://leetcode.com/problems/longest-word-in-dictionary-through-deleting/discuss/200366/Broken-Test-Cases Thank you for your time.

**Comment by ShivamS136** [comment]
@lc-kay Output is correct but the test case isn't. As the question says that it's string **dictionary** so it must be lexicographically sorted, that's my point. As many people including me had implemented the code in that way.
