### ISSUE TITLE
Incorrect test case - 524. Longest Word in Dictionary through Deleting

### ISSUE THREAD

**Issue by bavaria95** [LeetCode-Feedback/LeetCode-Feedback#2467]
#### Your LeetCode username
bavaria95

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Test case

#### Description of the bug
One of the test cases has the string `"aaa"` and a dictionary is `["aaa","aa","a"]`.
While the problem statement clearly specifies that the answer can be obtained by **deleting** some characters - the suggested answer in this test case is `"aaa"`. This, as I believe, is incorrect, since we don't delete **any** characters here.

#### Expected behavior
I expect the correct answer to be `"aa"`, since we need to obtain a string from the dictionary by removing some characters from the original string.

#### Screenshots
![image](https://user-images.githubusercontent.com/1766322/108772931-8b9e2800-7555-11eb-82d9-c4576d7191e1.png)

**Comment by lc-kay** [comment]
@bavaria95 The expected output is correct. Please refer to the discuss section to raise your concern or to check out user-submitted solutions and explanations. Thank you for your time.
