### ISSUE TITLE
Missing Test Case - 524. Longest Word in Dictionary through Deleting

### ISSUE THREAD

**Issue by hyacinth-ra** [LeetCode-Feedback/LeetCode-Feedback#2468]
#### Category of the bug
- [x] Test Cases

#### Description of the bug
My program was accepted but it is not correct. Consider the situation that there are more than one possible results with the same length and the same first character. But one of them is smaller based on the lexicographical order. For example, s="abce" and d=["abe",abc"] 
My answer is "abe"
But correct answer is "abc"

#### Code you used for Submit/Run operation
```
class Solution:
    def findLongestWord(self, s: str, d: List[str]) -> str:
        L = len(s)
        Lmax = 0
        out = ""
        for i in d:
            Li = len(i)
            if Li>L :
                continue
            if Li>Lmax or (Lmax!=0 and Li==Lmax and i[0]<out[0]):
                js = 0
                ji = 0
                temp =0
                while js<L and ji<Li:
                    if i[ji]==s[js]:
                        ji+=1
                        temp +=1
                    js+=1
                if temp == Li:
                    out = i
                    Lmax = Li

        return out
```

#### Language used for code
 Python

#### Expected behavior
I expected that my code was not accepted but it was accepted 

#### Additional context
You can add this testcase to check the codes:
 s="abce" and d=["abe",abc"]

**Comment by lc-kay** [comment]
Hi @hyacinth-ra 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @hyacinth-ra 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by hyacinth-ra** [comment]
Hi,

This is my LeerCode ID: hyacinth_ra

Best Regards
