### ISSUE TITLE
Missing Test Case - 921. Minimum Add to Make Parentheses Valid

### ISSUE THREAD

**Issue by wazzy47** [LeetCode-Feedback/LeetCode-Feedback#24685]
### LeetCode Username

wazzy47

### Problem Number, Title, and Link

921. Minimum Add to Make Parentheses Valid https://leetcode.com/problems/minimum-add-to-make-parentheses-valid

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

The task lacks test case of 1000 open parentheses: I was able to submit a code that would fail on this test case

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
class Solution {
public:
    int minAddToMakeValid(string s) {
        int all = 0;

        for (int i=0; i< s.length(); ++i) {
            if (s[i] == '(') {
                all += 1;
            } else {
                all += 1000;
            }

            if ((all%1000000)/1000 > all%1000) {
                all += 1000000;
                all += 1;
            }
        }

        return all/1000000 - ((all%1000000)/1000 - all%1000);
    }
};
```

### Expected behavior

Actual: the above code is accepted
Expected: the above code fails on the test of 1000 open parentheses (outputs 1 when should output 1000)

**Comment by wazzy47** [comment]
That is not my test case actually; it should be this:

`"(((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((("`

**Comment by longphat12** [comment]
helo
