### ISSUE TITLE
P383 Problem statement needs more details 

### ISSUE THREAD

**Issue by mdtareque** [LeetCode-Feedback/LeetCode-Feedback#247]
**What kind of the bug**
- [x] problem

**Describe the bug**
The problem statement doesn't have some basic details which should be present. By writing custom test cases, I found that only lowercase characters would be present in the input. The 'Exception Answer' showed Runtime error when give such a custom test case.

**What should be updated?**
- Problem statement should mention that only lower case characters will be in the input.
- Example should be elaborated on parameter names. Just reading the description should make the reader aware of what is the order of the input parameters. Ofcourse the reader can jump to the definition in the coding area, but this should not be required, since the explanation should be covered by problem statement, to make it a *Good* problem statement.

https://leetcode.com/problems/ransom-note/

**Comment by CooperCooperCooper** [comment]
Hi @mdtareque,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @mdtareque ,
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
