### ISSUE TITLE
incorrect test case

### ISSUE THREAD

**Issue by AlirezaPNouri** [LeetCode-Feedback/LeetCode-Feedback#2470]
#### Category of the bug
- [ ] Question
- [*] Solution
- [ ] Language

#### Description of the bug

the answer for the testcase number 29 is wrong.
Output:
"jpthiudqzzeugzwwsngebdeai"
Expected:
"nbmxgkduynigvzuyblwjepn"
candidate = ['xj', 'v', 'nfplhyzsyetmzkconpf', 'rdxfccnaxlu', 'jpthiudqzzeugzwwsngebdeai', 'bwjnkqxzt', 'xrecdmubinrzfmkyvrdxxkg', 'gkp', 'zrwfhiximevwhehb', 'hcnzjtkvtjgahdlz', 'djmqfunuap', 'taiyxekgspb', 'avsrjafa', 'rkgagyrzhevpiywf', 'gaazbcx', 'wlzpkmc', 'nbmxgkduynigvzuyblwjepn', 'pqmpsyqohi', 'fvrlloopyjdpeaumovi']
length of the candidate: [2, 1, 19, 11, 25, 9, 23, 3, 16, 16, 10, 11, 8, 16, 7, 7, 23, 10, 19]
correct answer "jpthiudqzzeugzwwsngebdeai" with size of 25
wrong answer "nbmxgkduynigvzuyblwjepn" with size of 23

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@AlirezaPNouri Please provide the problem number and title. Thank you!

**Comment by lc-kay** [comment]
Hi @AlirezaPNouri 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
