### ISSUE TITLE
[BUG] - <字母异位词分组>

### ISSUE THREAD

**Issue by jiang-wenxiang** [LeetCode-Feedback/LeetCode-Feedback#24714]
### LeetCode 用户名

love-cheese

### 问题号码、标题和链接

49. 字母异位词分组 https://leetcode.cn/problems/group-anagrams/description

### Bug Category

缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*

### 描述

在该问题的评论区有这样一种解法：“用质数表示26个字母，把字符串的各个字母相乘，这样可保证字母异位词的乘积必定是相等的”，但题目中对字符串的限制为1 <= strs.length <= 10^4，显然，如果有10^4个质数相乘，必然会超出任何语言能够运算乘法的范围，与题目要求不符，因此应该增加长度较长的用例，来将类似的算法排除。
![A002](https://github.com/user-attachments/assets/2151d5a3-e085-4a83-bfee-3c5d245b4e4d)

### 你使用的语言

Python/Python3

### 期望行为

应该增加长度较长（至少长度在10^2左右）的用例，来将质数相乘类似的算法排除。

**Comment by liyuzhu-lc** [comment]
感谢您的宝贵反馈，我们已经将您的反馈提交给我们的负责团队，并将会对相关信息进行核查，有新的进展及时再与您联系。感谢您的理解与支持。

**Comment by amcones-lc** [comment]
您好，在与相关团队核实后：***不处理***（10^4 个质数相乘结果长度大约在 10^4 级别，对于 python 这类能处理大数乘法的语言来说内存和时间上都没有达到限制）。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
