### ISSUE TITLE
Missing Test Case - 1764. Form Array by Concatenating Subarrays of Another Array

### ISSUE THREAD

**Issue by RakeshKumar5165** [LeetCode-Feedback/LeetCode-Feedback#2474]
#### Your LeetCode username

Rakesh5165

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Will explain with an example.
Input : 
[[1,2,3,4]]
[1,2,3,1,2,3,4]
The code I had written would check "1,2,3" which matches and next tries matching 4 and 1 and since that fails, the code just resumes from "2" at index 4 in nums array and "1" at index 0 of 0th group. Hence the code fails. But since this type of test case isn't included in the actual test suite, my code got accepted.
Please add this. 

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean canChoose(int[][] groups, int[] nums) {
        int curr_group = 0;
        int index = 0;
        int groups_length = groups.length;
        // int i=0;
        for(int i=0;i<nums.length && curr_group<groups_length;i++){
            
            if(index == groups[curr_group].length){
                index = 0;
                curr_group++;
                if(curr_group==groups_length) break;
            }
            if(nums[i] != groups[curr_group][index]){
                if(index==1) i--;
                index = 0;
            }
            else{
                index++;
            }
        }
        
        if(curr_group==groups_length || (curr_group==groups_length-1 && index == groups[groups_length-1].length )) return true;
        return false;
    }
}
```

#### Language used for code

Java

#### Expected behavior

My written code fails for this test, but since this kind of test is not there in test suite, code got accepted.
[[1,2,3,4]]
[1,2,3,1,2,3,4]

**Comment by lc-kay** [comment]
Hi @RakeshKumar5165 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @RakeshKumar5165 
Thank you for your time. Our team recently updated the test case set for this problem and the solution you submitted now received WA. Therefore, we did not add your custom test case. We appreciate your support!
