### ISSUE TITLE
Missing Test Case - 9. Palindrome Number

### ISSUE THREAD

**Issue by Sshrut** [LeetCode-Feedback/LeetCode-Feedback#2478]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [Python ] Language

#### Code you used for Submit/Run operation

```
class Solution:
    def isPalindrome(self, x: int) -> bool:
        if x<-2**31 or x>(2**31-1) or x<0:
            return "false"
        rev_int=0
        while x>=rev_int:
            temp=x%10
            rev_int=rev_int*10+temp
            if rev_int==x:
                return "true"
            x//=10
            
        return "false"
```

#### Expected behavior
Input : (-121)
Expected the output to be false but it's showing true  : ![image](https://github.com/Sshrut/Demo/blob/master/Screenshot%20(46).png)

**Comment by lc-kay** [comment]
@Sshrut The expected output is correct. Please check the discuss section for similar concerns or raise your question on there. Thank you for your time.
