### ISSUE TITLE
Missing Test Case - 1423. Maximum Points You Can Obtain from Cards

### ISSUE THREAD

**Issue by supriyalegha** [LeetCode-Feedback/LeetCode-Feedback#24787]
### LeetCode Username

supriyalegha

### Problem Number, Title, and Link

https://leetcode.com/problems/maximum-points-you-can-obtain-from-cards/

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

The problem statement states that we have to take k values from error that gives the maximum sum , choosing one of value either the first or last from the array.
But for input [7,2,3,4,5,6,1]  and k=3 
output should be 7+5+6 = 18
but given answer is 14 (which comes after we choose both first and last element from array and 1 other element) But its not compulsory that both first and last should be selected (IT IS CLEARLY GIVEN IN THE EXAMPLE TEST CASE 1)
Example 1:
Input: cardPoints = [1,2,3,4,5,6,1], k = 3
Output: 12
Explanation: After the first step, your score will always be 1. However, choosing the rightmost card first will maximize your total score. The optimal strategy is to take the three cards on the right, giving a final score of 1 + 6 + 5 = 12. 

### Language Used for Code

Java

### Code used for Submit/Run operation

```bash
class Solution {
    public int maxScore(int[] cardPoints, int k) {
           int n = cardPoints.length;
           int totalSum = 0;
        
        // Calculate the total sum of all card points
        for (int point : cardPoints) {
            totalSum += point;
        }
        
        // If k == n, we can take all the cards
        if (k == n) {
            return totalSum;
        }
        
        // Find the minimum sum of n - k consecutive cards
        int windowSize = n - k;
        int windowSum = 0;
        
        // Calculate the sum of the first window of size n - k
        for (int i = 0; i < windowSize; i++) {
            windowSum += cardPoints[i];
        }
        
        // This will store the minimum window sum
        int minWindowSum = windowSum;
        
        // Slide the window across the array
        for (int i = windowSize; i < n; i++) {
            windowSum += cardPoints[i] - cardPoints[i - windowSize];
            minWindowSum = Math.min(minWindowSum, windowSum);
        }
        
        // Maximum score is total sum minus the minimum sum of n - k cards
        return totalSum - minWindowSum;
    }
}
```

### Expected behavior

This code is giving the correct result although . But the question description is asking to so something different.

### Screenshots

![Screenshot 2024-10-15 211507](https://github.com/user-attachments/assets/1f548b09-23b5-46c6-8529-36134465ca12)

### Additional context

The output of this testcase which I have attached in the image should be 18 as I explained above in the Bug Description.

**Comment by supriyalegha** [comment]
Ok even though , the problem statement is choosing exactly k cards from either start or end . It is giving wrong output for testcase cardPoints = [7,2,3,4,5,6,1] and k=3 it is giving output 14 which not possible either we choose 3 cards from start or end .
![Screenshot 2024-10-15 211507](https://github.com/user-attachments/assets/0d59ee6b-d94f-4eb6-a91c-3f0fe4f5b2d3)

**Comment by OmAmar106** [comment]
> Ok even though , the problem statement is choosing exactly k cards from either start or end . It is giving wrong output for testcase cardPoints = [7,2,3,4,5,6,1] and k=3 it is giving output 14 which not possible either we choose 3 cards from start or end .
> ![Screenshot 2024-10-15 211507](https://github.com/user-attachments/assets/0d59ee6b-d94f-4eb6-a91c-3f0fe4f5b2d3)

You could remove the first and the last two element, the sum would be 14, (you can remove from the start and end both, total elements should be 3)

**Comment by supriyalegha** [comment]
But in problem statement we have to find the maximum sum and its not compulsory to choose both first and last element we can choose either one of them . so if we select first 7 then 5 , 6 we get maximum sum as 18 so , 18 should be the answer.
![image](https://github.com/user-attachments/assets/46d54133-7d6f-46bc-8a09-fecb5f832481)
Since in this example test case we have not selected both first and last

**Comment by OmAmar106** [comment]
> But in problem statement we have to find the maximum sum and its not compulsory to choose both first and last element we can choose either one of them . so if we select first 7 then 5 , 6 we get maximum sum as 18 so , 18 should be the answer. ![image](https://private-user-images.githubusercontent.com/132987159/376749803-46d54133-7d6f-46bc-8a09-fecb5f832481.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMTkyNzYsIm5iZiI6MTcyOTAxODk3NiwicGF0aCI6Ii8xMzI5ODcxNTkvMzc2NzQ5ODAzLTQ2ZDU0MTMzLTdkNmYtNDZiYy04YTA5LWZlY2I1ZjgzMjQ4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQxOTAyNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMjg3YjI5YzQ3MDU0ZWVkOGY4NTBhNDQ2YTU3ZGZhMWY4ZjIzNTFmNzRjNzYxYWE4YmRkYWRhMjAxNTdhNTFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9Kl6bDLsmJn0VVA1XrlIr2Oma7FQYNl2f9hRumwRPVE) Since in this example test case we have not selected both first and last

![image](https://github.com/user-attachments/assets/0e817354-64a1-4a84-84f0-1c3a2731bef3)

You cannot choose the second last element unless you choose the last element.
