### ISSUE TITLE
Weak Testcases-----560. Subarray Sum Equals K

### ISSUE THREAD

**Issue by modinitin13** [LeetCode-Feedback/LeetCode-Feedback#248]
**What kind of the bug**
Weak Testcases

**Describe the bug**
The test cases are weak, It allows O(N^2) time complexity to get AC. 

**what language is your code written in**
C++

**The code you submit/run**
```
class Solution {
public:
    int subarraySum(vector<int>& nums, int k) {
        int n=nums.size(), count=0;
        vector<int> sum(n+1);
        sum[0]=0;
        for(int i=1;i<=n;i++)
            sum[i] = sum[i-1] + nums[i-1];
        
        for(int start=0;start<=n;start++) {
            for(int end=start+1;end<=n;end++) {
                if(sum[end]-sum[start]==k)  count++;
            }
        }
        
        return count;
    }
};
```

**Expected behavior**
The solution should get TLE.

**Screenshots**

**Additional context**
I have attached the test case file
[test.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/4570472/test.txt)

**Comment by CooperCooperCooper** [comment]
Hi @modinitin13 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @modinitin13 ,
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
