### ISSUE TITLE
Incorrect Test Cases for Problem #973

### ISSUE THREAD

**Issue by Kshitij68** [LeetCode-Feedback/LeetCode-Feedback#2480]
LeetCode Username: user7492T

The description of problem#973 states that `You may return the answer in any order.`

However, I get incorrect submission for the following test case.
Input: [[0,1],[1,0]]
Output: [[1,0],[1,0]]
Expected: [[0,1],[1,0]]

#### Code you used for Submit/Run operation

```
class Solution:
    
    def calculate_distance(self,x,y):
        return x*x + y*y

    def kClosest(self, points: List[List[int]], K: int) -> List[List[int]]:
        distances = [self.calculate_distance(x,y) for x,y in points]
        
        distance_map = {}
        for i in range(len(distances)):
            distance_map[distances[i]] = points[i]
        
        return [distance_map[value] for value in sorted(distances)[:K]]
```

#### Expected behavior
The test cases should not take ordering into consideration.

**Comment by Kshitij68** [comment]
actually looking at it more carefully,
it seems like the expected output of test case is itself wrong. The ordering is not the usse

**Comment by lc-kay** [comment]
@Kshitij68 The test case and the expected output is correct. Please check out the [discuss section](https://leetcode.com/problems/k-closest-points-to-origin/discuss/932900/help!!!!) to find user-submitted solutions and explanations, or raise your question there. Thank you for your time!
