### ISSUE TITLE
319. 灯泡开关 题目描述有歧义

### ISSUE THREAD

**Issue by hfmkfj** [LeetCode-Feedback/LeetCode-Feedback#2482]
**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名
蜂蜜咖啡
**Bug 类型**
- [ √] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
描述你遇到的 bug
题目描述有歧义，这题意思明显是第i轮时每i-1个灯泡切换一次，而题目说“第2轮，每两个灯泡你关闭一次”，题目和示例又不给出第4轮开始的任意一种偶数情况，这会误导人想“是不是奇数轮切换，偶数轮关闭呢？”
应该改为“第2轮，每两个灯泡你关闭一次”
**你使用的语言**
Java

**你提交或者运行的代码**
```
```

**期望行为**
描述你期望的结果
应该改为“第2轮，每两个灯泡你关闭一次”
**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![image](https://user-images.githubusercontent.com/29862246/108940866-0e76ce00-768f-11eb-89e2-a1f515d33cd9.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前该题题面已更新，所有灯泡切换的描述都统一为类似 「第 i 轮，每 i 个灯泡切换一次开关。」这样的表述，具体变更请参见题面。
