### ISSUE TITLE
go提交一直提示解答错误

### ISSUE THREAD

**Issue by keroro6** [LeetCode-Feedback/LeetCode-Feedback#2483]
https://leetcode-cn.com/problems/binary-tree-inorder-traversal/

`
 var a = []int{}
func inorderTraversal(root *TreeNode) []int {
    midTree(root)
    return a
}

func midTree(root *TreeNode) {
    if root == nil {
        return 
    }

    midTree(root.Left)
    a = append(a, root.Val)
    midTree(root.Right)
}`
执行结果：
解答错误
显示详情
输入：
[]
输出：
[1,3,2]
预期结果：
[]

我测试没问题，请问为什么提交一直输出这个，对go支持的不行吗？
![image](https://user-images.githubusercontent.com/46135673/108979765-f2425380-76c5-11eb-936e-35084c8e09dc.png)

**Comment by feiceh** [comment]
你好，建议再仔细检查并调试一下代码，推荐阅读：「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」 获得更多帮助。

同时也可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。

**Comment by keroro6** [comment]
我懂了，全局变量要在每次函数调用前，自己手动清空下，希望能给出提示，这有点让人摸不着头脑
