### ISSUE TITLE
Missing Test Case - 973. K Closest Points to Origin

### ISSUE THREAD

**Issue by apurva1210** [LeetCode-Feedback/LeetCode-Feedback#2484]
#### Your LeetCode username

Apurva Thorat

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

The Approach 1: Sort solution is wrong. It does not cover the below test case.
points = [[1,2],[2,1], [-1,2], [-2,1]], K = 3

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
Hi @apurva1210 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @apurva1210 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
