### ISSUE TITLE
Missing Test Case - 957. Prison Cells After N Days

### ISSUE THREAD

**Issue by Sky-Nik** [LeetCode-Feedback/LeetCode-Feedback#2485]
#### Your LeetCode username

nskybytskyi

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The following solution gets AC, but should get WA on the following testcase:
```
cells = [1, 1, 0, 1, 1, 0, 0, 1]
N = 300663720
```

#### Code you used for Submit/Run operation

```cpp
class Solution {
private:
    auto next(const vector<int>& cells) {
        int len = cells.size();
        vector<int> next_(len);
        for (int i = 1; i + 1 < len; ++i) {
            next_[i] = cells[i - 1] == cells[i + 1];
        }
        return next_;
    }

public:
    auto prisonAfterNDays(vector<int>& cells, int n) {
        n %= (3 * 5 * 7 * 8);
        while (n --> 0) {
            cells = next(cells);
        }
        return cells;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Expected `[0,0,1,0,0,1,1,0]`, got `[1,1,0,1,1,0,0,1]`.

#### Additional information

The problem is, of course, that `N` is divisible by `3 * 5 * 7 * 8` in this testcase, and we should simulate `3 * 5 * 7 * 8` days instead of `0`. More test cases with smooth `N` can be added as well.

**Comment by lc-kay** [comment]
Hi @Sky-Nik 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Sky-Nik 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
