### ISSUE TITLE
[BUG] - LCR 059 测试用例格式错误

### ISSUE THREAD

**Issue by r6hk** [LeetCode-Feedback/LeetCode-Feedback#24867]
### LeetCode 用户名

rennen

### 问题号码、标题和链接

LCR 059. 数据流中的第 K 大元素 https://leetcode.cn/problems/jBjn9C/description/

### Bug Category

不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*

### 描述

默认的代码模板，要求构造函数传入三个参数：
```java
class KthLargest {
    // **此处的构造函数要求传入三个参数**
    public KthLargest(int k, int[] nums, int numsSize){
        
    }
    
    public int add(int val) {
        
    }
}

/**
 * Your KthLargest object will be instantiated and called as such:
 * KthLargest obj = new KthLargest(k, nums, numsSize);
 * int param_1 = obj.add(val);
 */
```
但是默认的测试用例，调用构造函数只传入了两个参数：
![image](https://github.com/user-attachments/assets/2e0a402c-bae5-448e-bbc1-8a93a63a3d8a)

因此，即使是正确的代码，提交答案也会出现如下报错：
```
java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
  at line 100, java.base/jdk.internal.util.Preconditions.outOfBounds
  at line 106, java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex
  at line 302, java.base/jdk.internal.util.Preconditions.checkIndex
  at line 385, java.base/java.util.Objects.checkIndex
  at line 427, java.base/java.util.ArrayList.get
  at line 416, com.eclipsesource.json.JsonArray.get
  at line 78, __Driver__.__helperConstructor__
  at line 81, __Driver__.__helper__
  at line 108, __Driver__.main
```

### 你使用的语言

Java

### 你提交或者运行的代码

以下代码[来自官解](https://leetcode.cn/problems/jBjn9C/solutions/1041946/shu-ju-liu-de-di-k-da-shu-zhi-by-leetcod-11n3/)，但无论构造函数是否有 `int numsSize` 这个参数，提交均报错
```bash
class KthLargest {
    PriorityQueue<Integer> pq;
    int k;

    public KthLargest(int k, int[] nums, int numsSize) {
        this.k = k;
        pq = new PriorityQueue<Integer>();
        for (int x : nums) {
            add(x);
        }
    }
    
    public int add(int val) {
        pq.offer(val);
        if (pq.size() > k) {
            pq.poll();
        }
        return pq.peek();
    }
}
```

### 期望行为

AC

### 期望改进

第三个参数 `int numsSize` 的意义好像并不大？也许可以将代码模板回滚为原来只有两个形参的版本，很多题解也都是按照构造函数只有两个形参来写的。

**Comment by Nowman123** [comment]
靠，我也是遇到这个问题！

**Comment by liyuzhu-lc** [comment]
感谢您的宝贵反馈，我们已经将您的反馈提交给我们的负责团队，并将会对相关信息进行核查，有新的进展及时再与您联系。感谢您的理解与支持。

**Comment by amcones-lc** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by r6hk** [comment]
> 你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

https://leetcode.cn/u/rennen/

谢谢~ 😄

**Comment by Nowman123** [comment]
姚志东 - 力扣（LeetCode）




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xia ***@***.***&gt;; 
发送时间: 2024年10月26日(星期六) 下午3:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LeetCode-Feedback/LeetCode-Feedback] [BUG] - LCR 059 测试用例格式错误 (Issue #24867)














  
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。
  
https://leetcode.cn/u/rennen/
 
谢谢~ 😄

**Comment by amcones-lc** [comment]
@r6hk 你好，当前该题已添加测试用例，奖励已发放。
