### ISSUE TITLE
417. 太平洋大西洋水流问题 答案错误

### ISSUE THREAD

**Issue by 18996677975** [LeetCode-Feedback/LeetCode-Feedback#2486]
**你的 LeetCode 用户名**
bigdata_yu

**Bug 类型**
- [ 417 ] 太平洋大西洋水流问题
- [ python3 ] 编程语言

**描述**
测试用例
                [[1,2,3],
                 [8,9,4],
                 [7,6,5]]
期望结果:[[0,2],[1,0],[1,1],[1,2],[2,0],[2,1],[2,2]]
期望结果中的 [2, 1] 错误，题目要求 ’既可以流动到“太平洋”，又能流动到“大西洋”的陆地单元的坐标‘
[2, 1] 该点是 6，该点的左方为 7，上方为 9，即该点无论如何都无法到达 ”太平洋“
该点不应该在 期望结果 中

**你使用的语言**
python3

**你提交或者运行的代码**
```python
class Solution:
    def pacificAtlantic(self, matrix):
        def dfs1(i, j):
            if i == n - 1 or j == m - 1: return True

            if matrix[i][j] >= matrix[i + 1][j] or matrix[i][j] >= matrix[i][j + 1]:
                return dfs1(i + 1, j) or dfs1(i, j + 1) or False

        def dfs2(i, j):
            if i == 0 or j == 0: return True
            if matrix[i][j] >= matrix[i - 1][j] or matrix[i][j] >= matrix[i][j - 1]:
                return dfs2(i - 1, j) or dfs2(i, j - 1) or False

        if not matrix: return []
        n, m, res = len(matrix), len(matrix[0]), []

        for i in range(n):
            for j in range(m):
                if dfs1(i, j) and dfs2(i, j):
                    res.append([i, j])
        return res
```

**期望行为**
修正错误的 期望结果

**屏幕截图**
![image](https://user-images.githubusercontent.com/58323844/109034433-9cd86780-7702-11eb-9541-a503ca16455f.png)

**Comment by 18996677975** [comment]
太平洋大西洋水流问题 答案错误

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by stormsunshine** [comment]
这个测试用例的答案并没有问题，只要可以流到太平洋和大西洋即可，并没有限制流动的方向。
可以按照如下方向流到太平洋：[2,1]->[2,2]->[1,2]->[0,2]，经过的元素依次是：6->5->4->3。

**Comment by feiceh** [comment]
@18996677975 你好，该用例可以通过 6->5->4->3 到达太平洋；非常感谢@stormsunshine 的帮助！
