### ISSUE TITLE
130. Surrounded Regions - don't make people mutate state!

### ISSUE THREAD

**Issue by rpolley** [LeetCode-Feedback/LeetCode-Feedback#2488]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

As you may know, some programming languages do not work well with mutating state. Problems should be written to work with those languages.

#### Code you used for Submit/Run operation

```
object Solution {
    def solve(board: Array[Array[Char]]): Unit = {
        var cln: Array[Array[Char]] = board.map((r) => r.clone())
        var last_row = board.length - 1
        var last_col = board(0).length - 1
        (0 to last_row).map(
            (row) => {
                floodFillAt(cln, row, 0)
                floodFillAt(cln, row, last_col)
            }
        )
        (0 to last_col).map(
            (col) => {
                floodFillAt(cln, 0, col)
                floodFillAt(cln, last_row, col)
            }
        )
        var result = board.zip(cln).map({ case (board_row, cln_row) => {
          board_row.zip(cln_row).map( {
              case ('X', 'X') => 'X'
              case ('X', 'O') => '0' //should never happen
              case ('O', 'X') => 'O'
              case ('O', 'O') => 'X'
              case (_, _) => '1'
          })
        }})
        // I should be able to return result here        
    }
    def floodFillAt(board: Array[Array[Char]], row: Int, col: Int): Unit = {
        if (row < 0 || col < 0 || row >= board.length || col >= board(0).length) {
            return
        }
        if (board(row)(col) == 'X'){
            return
        }
        board(row)(col) = 'X'
        floodFillAt(board, row + 1, col)
        floodFillAt(board, row - 1, col)
        floodFillAt(board, row, col + 1)
        floodFillAt(board, row, col - 1)
    }
}
```

#### Language used for code
scala

#### Expected behavior
I can return an array with the result. Instead I am forced to mutate the input parameters.

**Comment by lc-kay** [comment]
Hi @rpolley
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@rpolley Our team has reviewed your report and concluded that Scala can be used. Please check these user-submitted solutions https://leetcode.com/submissions/detail/461034944/ https://leetcode.com/submissions/detail/461035010/ Thank you for your time!

**Comment by rpolley** [comment]
@lc-kay all of those links get a 404

**Comment by rpolley** [comment]
Also this isn't about whether it can be solved using scala, but whether it can be solved using **idiomatic** scala
