### ISSUE TITLE
Missing Test Case - 1593. Split a String Into the Max Number of Unique Substrings

### ISSUE THREAD

**Issue by piyushkumar4021** [LeetCode-Feedback/LeetCode-Feedback#24901]
### LeetCode Username

piyush_kumar41

### Problem Number, Title, and Link

1593. Split a String Into the Max Number of Unique Substrings https://leetcode.com/problems/split-a-string-into-the-max-number-of-unique-substrings/?envType=daily-question&envId=2024-10-21

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

Output for the testcase "ababab" is 4 but it should be 3 because the unique strings will be ["a", "b", "abab"].

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
class Solution {
public:
    int backtrack(string &s, int start, unordered_set<string> &seen) {
        if (start == s.size()) {
            return 0;
        }

        int maxCount = 0;
        string currentSubstring;

        for (int i = start; i < s.size(); ++i) {
            currentSubstring += s[i];

            if (seen.find(currentSubstring) == seen.end()) {
                    seen.insert(currentSubstring);
                    maxCount = max(maxCount, 1 + backtrack(s, i + 1, seen));
                    seen.erase(currentSubstring);
                }
            }

        return maxCount;
    }
    int maxUniqueSplit(string s) {
        unordered_set<string> hash;
        return backtrack(s, 0, hash);
    }
};
```

### Expected behavior

Invalid answer for the testcase for "ababab".

### Screenshots

![image](https://github.com/user-attachments/assets/b612534e-4e41-4383-adbe-1e6ea829fc16)

**Comment by FoxtrotOnce** [comment]
You can split it into ["a","ba","b","ab"], which is 4
