### ISSUE TITLE
[BUG] - Runtime Error - 49. Group Anagrams

### ISSUE THREAD

**Issue by Foster1466** [LeetCode-Feedback/LeetCode-Feedback#24907]
### LeetCode Username

Foster1466

### Problem Number, Title, and Link

https://leetcode.com/problems/group-anagrams/description/

### Bug Category

Editorial

### Bug Description

Editorial and correct code is not compiling in the website

### Language Used for Code

Python/Python3

### Code used for Submit/Run operation

```bash
class Solution:
    def groupAnagrams(self, strs: List[str]) -> List[List[str]]:
        ans = collections.defaultdict(list)
        for s in strs:
            ans[tuple(sorted(s))].append(s)
        return ans.values()
```

### Expected behavior

Accepted

### Screenshots

![image](https://github.com/user-attachments/assets/408bf76f-7dda-42cb-a02a-81f3d1085d59)

### Additional context

Cannot submit the code

**Comment by Foster1466** [comment]
Logs can be seen in the SS, reloaded the website, tried on chrome, imported collections for defaultdict

Here's proof:
![image](https://github.com/user-attachments/assets/c15eeeef-65d2-4c13-9ca9-fdc0cc874bd8)

**Comment by ajanitshimanga** [comment]
This is similarly hitting a run time error for the alternate solution in the editorial. Approach 2: Categorize by Count.

Here is a comment talking about this as well: https://leetcode.com/problems/group-anagrams/solution/2694551

```
class Solution:
    def groupAnagrams(self, strs: List[str]) -> List[List[str]]:
        ans: DefaultDict[int, List[str]] = collections.defaultdict(list)
        for s in strs:
            count = [0] * 26
            for c in s:
                count[ord(c) - ord("a")] += 1
            ans[tuple(count)].append(s)
        return ans.values()
```

<img width="1521" alt="Screenshot 2024-10-26 at 3 56 16 PM" src="https://github.com/user-attachments/assets/fcd32854-2223-4bcd-8734-80b456066fdf">

<img width="839" alt="Screenshot 2024-10-26 at 3 56 28 PM" src="https://github.com/user-attachments/assets/82eefd5d-b465-4342-9420-df6782208637">
