### ISSUE TITLE
Missing Test Case - 70. Climbing Stairs

### ISSUE THREAD

**Issue by qinqiuzhengdui** [LeetCode-Feedback/LeetCode-Feedback#24912]
### LeetCode 用户名

Sweet MclareneRA

### 问题号码、标题和链接

https://leetcode.cn/problems/climbing-stairs/?envType=study-plan-v2&envId=dynamic-programming

### Bug Category

缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*

### 描述

缺少测试用例。

### 你使用的语言

C++

### 你提交或者运行的代码

```bash
class Solution {
public:
    int climbStairs(int n) {
        if(n==1){return 1;}
        else if(n==2){return 2;}
        else {return climbStairs(n-1)+climbStairs(n-2);}
    }
};
```

### 期望行为

输入：10
输出：89
输入：11
输出：144
输入：23
输出：46348
输入：34
输出：9227465
输入：36
输出：24157817
输入：43
输出：701408733
输入：45
输出：1836311903

**Comment by liyuzhu-lc** [comment]
感谢您的宝贵反馈，我们已经将您的反馈提交给我们的负责团队，并将会对相关信息进行核查，有新的进展及时再与您联系。感谢您的理解与支持。

**Comment by amcones-lc** [comment]
We have received feedback, please wait for us to process
