### ISSUE TITLE
Typo in Explanation for Example 1 - 563. Binary Tree Tilt

### ISSUE THREAD

**Issue by amccarthy9904** [LeetCode-Feedback/LeetCode-Feedback#2492]
Explanation for Example 1

Input: root = [1,2,3]
Output: 1
Explanation: 
Tilt of node 2 : |0-0| = 0 (no children)
Tilt of node 3 : |0-0| = 0 (no children)
**Tile** of node 1 : |2-3| = 1 (left subtree is just left child, so sum is 2; right subtree is just right child, so sum is 3)
Sum of every tilt : 0 + 0 + 1 = 1

"Tile of node 1" should be "Tilt of node 1"

**Comment by lc-kay** [comment]
Hi @amccarthy9904 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @amccarthy9904 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
