### ISSUE TITLE
[BUG] - LCR 013. Testing Environment Issue

### ISSUE THREAD

**Issue by qinghuan02** [LeetCode-Feedback/LeetCode-Feedback#24937]
### LeetCode Username

清欢(qing-huan-f5)

### Problem Number, Title, and Link

LCR 013. https://leetcode.cn/problems/O4NDxx/?envType=study-plan-v2&envId=coding-interviews-special

### Bug Category

Editorial

### Bug Description

Error in testing environment.

### Language Used for Code

Java

### Code used for Submit/Run operation

```bash
class NumMatrix {

    public NumMatrix(int[][] matrix, int matrixRowSize, int matrixColSize) {
        
    }
    
    public int sumRegion(int row1, int col1, int row2, int col2) {
        return 0;
    }
}
```

### Expected behavior

The expected output should be all zeros, but an error occurred in the main function.

java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
  at line 100, java.base/jdk.internal.util.Preconditions.outOfBounds
  at line 106, java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex
  at line 302, java.base/jdk.internal.util.Preconditions.checkIndex
  at line 385, java.base/java.util.Objects.checkIndex
  at line 427, java.base/java.util.ArrayList.get
  at line 416, com.eclipsesource.json.JsonArray.get
  at line 80, __Driver__.__helperConstructor__
  at line 84, __Driver__.__helper__
  at line 111, __Driver__.main

### Screenshots

![bugreport](https://github.com/user-attachments/assets/b55245f6-b3fc-4dfc-b0b6-5347958d85fa)

**Comment by qinghuan02** [comment]
I used the default test case.

["NumMatrix","sumRegion","sumRegion","sumRegion"]
[[[[3,0,1,4,2],[5,6,3,2,1],[1,2,0,1,5],[4,1,0,1,7],[1,0,3,0,5]]],[2,1,4,3],[1,1,2,2],[1,2,2,4]]

It seems that your test cases are missing the matrixRowSize and matrixColSize parameters, which is causing this issue.

After I manually added these two parameters to the test cases, the tests executed successfully.
[[[[3,0,1,4,2],[5,6,3,2,1],[1,2,0,1,5],[4,1,0,1,7],[1,0,3,0,5]], 5, 5],[2,1,4,3],[1,1,2,2],[1,2,2,4]]

The issue may stem from the fact that this problem is consistent with the [304](https://leetcode.cn/problems/range-sum-query-2d-immutable/description/) problem, and you reused that problem's test cases. However, in this problem, you later modified the constructor to include the matrixRowSize and matrixColSize parameters, but these parameters were not added to your test cases.

**Comment by qinghuan02** [comment]
![image](https://github.com/user-attachments/assets/0b6a5b77-77d4-44ed-ae7b-0310f797d542)

**Comment by liyuzhu-lc** [comment]
感谢您的宝贵反馈，我们已经将您的反馈提交给我们的负责团队，并将会对相关信息进行核查，有新的进展及时再与您联系。感谢您的理解与支持。

**Comment by amcones-lc** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by qinghuan02** [comment]
你好，我的个性域名如下：
leetcode.cn/u/qing-huan-f5/

**Comment by amcones-lc** [comment]
你好，当前该题已更新，奖励已发放。
