### ISSUE TITLE
[BUG] - XRange use in Editorial for 827. Making a Large Island

### ISSUE THREAD

**Issue by Selbl** [LeetCode-Feedback/LeetCode-Feedback#24936]
### LeetCode Username

StefanCodesInChile

### Problem Number, Title, and Link

827. Making a Large Island https://leetcode.com/problems/making-a-large-island/

### Bug Category

Editorial

### Bug Description

When running the Python solution in approach 2 you get an error because of the xrange function which is deprecated in Python 3. Changing that function to range solves the issue.

### Language Used for Code

Python/Python3

### Code used for Submit/Run operation

```bash
class Solution(object):
    def largestIsland(self, grid):
        N = len(grid)

        def neighbors(r, c):
            for nr, nc in ((r-1, c), (r+1, c), (r, c-1), (r, c+1)):
                if 0 <= nr < N and 0 <= nc < N:
                    yield nr, nc

        def dfs(r, c, index):
            ans = 1
            grid[r][c] = index
            for nr, nc in neighbors(r, c):
                if grid[nr][nc] == 1:
                    ans += dfs(nr, nc, index)
            return ans

        area = {}
        index = 2
        for r in xrange(N):
            for c in xrange(N):
                if grid[r][c] == 1:
                    area[index] = dfs(r, c, index)
                    index += 1

        ans = max(area.values() or [0])
        for r in xrange(N):
            for c in xrange(N):
                if grid[r][c] == 0:
                    seen = {grid[nr][nc] for nr, nc in neighbors(r, c) if grid[nr][nc] > 1}
                    ans = max(ans, 1 + sum(area[i] for i in seen))
        return ans
```

### Expected behavior

The code should output the correct solution, and it outputs an error:

NameError: name 'xrange' is not defined. Did you mean: 'range'?
             ^^^^^^
    for r in xrange(N):
Line 20 in largestIsland (Solution.py)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ret = Solution().largestIsland(param_1)
Line 57 in _driver (Solution.py)
    _driver()
Line 72 in <module> (Solution.py)

### Additional context

It might be helpful to state that the editorial was made with Python 2. However, seeing as most people use Python 3 nowadays maybe just updating the editorial to get rid of xrange should suffice.

**Comment by FoxtrotOnce** [comment]
The code is made for Python, not Python3
