### ISSUE TITLE
SQL 面试宝典 02. 查找空值 示例数据问题

### ISSUE THREAD

**Issue by e-chocolate** [LeetCode-Feedback/LeetCode-Feedback#24945]
### LeetCode 用户名

Cmite

### 问题号码、标题和链接

SQL 面试宝典 02. 查找空值 https://leetcode.cn/problems/Qq61UO/description/?envType=study-plan-v2&envId=sql-interview-handbook

### Bug Category

不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*

### 描述

Oracle 仅查询空值时，不应该出现字符串长度为0的字符串。

### 你使用的语言

None

### 你提交或者运行的代码

```bash
/* Write your PL/SQL query statement below */
select * from 教师表
where 教师姓名 is null
;
```

### 期望行为

| 教师号 | 教师姓名 |
| --- | ---- |
| 4   | null |

### 屏幕截图

![image](https://github.com/user-attachments/assets/087be573-c9a9-44ef-97bf-f3d512fb0886)

**Comment by liyuzhu-lc** [comment]
感谢您的宝贵反馈，我们已经将您的反馈提交给我们的负责团队，并将会对相关信息进行核查，有新的进展及时再与您联系。感谢您的理解与支持。

**Comment by amcones-lc** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by e-chocolate** [comment]
[个性域名](https://leetcode.cn/u/cmite/)

**Comment by amcones-lc** [comment]
你好，当前该题已更新，奖励已发放。
