### ISSUE TITLE
Incorrect testcases - 1528. Shuffle String

### ISSUE THREAD

**Issue by theharoold** [LeetCode-Feedback/LeetCode-Feedback#2496]
#### Your LeetCode username

velti

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

The input integer array of indices does not correlate with the expected answer.
Example input:
[{"codeleet"}, {4, 5, 6, 7, 0, 2, 1, 3}]
My output:
4 - l
5 - e
6 - e
7 - t
0 - c
2 - d
1 - o
3 - e
"leetcdoe"

#### Code you used for Submit/Run operation

```
class Solution {
    public String restoreString(String s, int[] indices) {
        char[] shuffledString = new char[s.length()];
        for (int i = 0; i < s.length(); i++) {
            shuffledString[i] = s.charAt(indices[i]);
        }
        return String.valueOf(shuffledString);
    }
}
```

#### Expected behavior

I expected the program to shuffle the given string from "codeleet" to "leetcode", however, because of the incorrect index indices, it produces "leetcdoe".

#### Screenshots

https://imgur.com/a/dYvhLZq

#### Additional context

I've noticed multiple posts in the "discussion" area about this problem, but no bug reports in the github page. Thanks in advance.

**Comment by lc-kay** [comment]
@theharoold The expected output is correct. Please check out the comment in this post for a better understanding. https://leetcode.com/problems/shuffle-string/discuss/1030685/How-come-%22codeleet%22-with-indices-45670213-become-leetcode-Shouldn't-it-be-leetcdoe
