### ISSUE TITLE
Missing Test Case - 1233. Remove Sub-Folders from the Filesystem

### ISSUE THREAD

**Issue by Legend-sky** [LeetCode-Feedback/LeetCode-Feedback#24977]
### LeetCode 用户名

Flow

### 问题号码、标题和链接

1233

### Bug Category

问题描述, 不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*

### 描述

使用测试用例["/c/f/","/c/f/d"]，输出为["/c/f/","/c/f/d"]，正确结果应该是["/c/f/"]。

### 你使用的语言

None

### 期望行为

题目中保证最后不会出现/。

**Comment by liyuzhu-lc** [comment]
感谢您的宝贵反馈，我们已经将您的反馈提交给我们的负责团队，并将会对相关信息进行核查，有新的进展及时再与您联系。感谢您的理解与支持。

**Comment by amcones-lc** [comment]
We have received your feedback, please wait for us to process it.
