### ISSUE TITLE
996. Number of Squareful Arrays

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#250]
**What kind of the bug**
- [ ] problem
- [x] solution
- [ ] language

**Describe the bug**
Approach 2: Dynamic Programming solution has wrong analysis

**what language is your code written in**
Python

**The code you submit/run**
```
from functools import lru_cache

class Solution:
    def numSquarefulPerms(self, A):
        N = len(A)

        def edge(x, y):
            r = math.sqrt(x+y)
            return int(r + 0.5) ** 2 == x+y

        graph = [[] for _ in range(len(A))]
        for i, x in enumerate(A):
            for j in range(i):
                if edge(x, A[j]):
                    graph[i].append(j)
                    graph[j].append(i)

        # find num of hamiltonian paths in graph

        @lru_cache(None)
        def dfs(node, visited):
            if visited == (1 << N) - 1:
                return 1

            ans = 0
            for nei in graph[node]:
                if (visited >> nei) & 1 == 0:
                    ans += dfs(nei, visited | (1 << nei))
            return ans

        ans = sum(dfs(i, 1<<i) for i in range(N))
        count = collections.Counter(A)
        for v in count.values():
            ans //= math.factorial(v)
        return ans
```

**Expected behavior**
Time Complexity: O(N 2^N), where N is length of A.

Space Complexity: O(N 2^N)

This is the analysis provided.

The space complexity is correct as bitset visited had 2^N possibilities and node has N possibilities. But for each state (node, visited) we are doing at worst N computations. 
So the time complexity must be O(N^2 * 2^N).  You can refer [here](https://en.wikipedia.org/wiki/Held%E2%80%93Karp_algorithm#Dynamic_programming_approach)

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @
Thank you for your time. We've fixed the time complexity. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
