### ISSUE TITLE
Missing Test Case - 234. Palindrome Linked List

### ISSUE THREAD

**Issue by aubreynicoll** [LeetCode-Feedback/LeetCode-Feedback#2503]
#### Your LeetCode username
aubreynicoll

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
This question is very poorly worded in regards to the null case presented. If head is null, then the solution expects the function to return true. Whether or not null can be considered a palindrome is debatable, and therefore the question should give explicit instructions.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
Hi @aubreynicoll 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @aubreynicoll 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
