### ISSUE TITLE
题目188： 官方题解有小错误

### ISSUE THREAD

**Issue by boqigao** [LeetCode-Feedback/LeetCode-Feedback#2504]
**你的 LeetCode 用户名**
bo-bo-5m

**Bug 类型**
- [ ] 题目
- [x] 题解
- [ ] 编程语言

**描述**
题目188： 买卖股票的最佳时机 IV
官方题解有小错误

**你使用的语言**
JAVA

**期望行为**
修改题解中的小错误。
在官方题解，动态规划的第三小段

> 那么我们可以对状态转移方程进行推导。对于 `buy[i][j]`，我们考虑当前手上持有的股票是否是在第 i 天买入的。如果是第 i 天买入的，那么在第 i-1天时，我们手上不持有股票，对应状态 `sell[i−1][j]`，并且需要扣除 `prices[i]` 的买入花费；如果不是第 i 天买入的，那么在第 i-1天时，我们手上持有股票，对应状态`buy[i][j]`。那么我们可以得到状态转移方程：

其中最后一句话显然应该是：那么在第 i-1天时，我们手上持有股票，对应状态`buy[i-1][j]`。

望修正。

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
https://leetcode-cn.com/problems/best-time-to-buy-and-sell-stock-iv/solution/mai-mai-gu-piao-de-zui-jia-shi-ji-iv-by-8xtkp/

![image](https://user-images.githubusercontent.com/42335852/109274977-7415b680-7857-11eb-8f62-0de3d42e19a9.png)

**Comment by feiceh** [comment]
感谢反馈，此问题已转给相关运营团队会尽快确认。

**Comment by zerotrac** [comment]
你说得对～

**Comment by feiceh** [comment]
@boqigao  你好，当前题解已更新，ID：bo-bo-5m  给予积分奖励，请查收。
