### ISSUE TITLE
Missing Test Case - 50. Pow(x, n)

### ISSUE THREAD

**Issue by Dewanshpillare** [LeetCode-Feedback/LeetCode-Feedback#25043]
### LeetCode Username

Dewansh Pillare

### Problem Number, Title, and Link

50. Pow(x, n) https://leetcode.com/problems/powx-n/description/

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

In first 3 testcases in this problem, the answer of the third test case of this problem should be 0.25, but the answer in the test case is 1.000. This is incorrect.

### Language Used for Code

None

### Expected behavior

The answer should be 0.25 insted of 1.00. The testcase should be passed, but it didnot.

**Comment by Ankitdahiya2002** [comment]
<img width="1440" alt="Screenshot 2024-11-01 at 9 52 07 AM" src="https://github.com/user-attachments/assets/52928a44-9713-4756-8df9-e3d7d0e3de26">


> ### LeetCode Username
> Dewansh Pillare
> 
> ### Problem Number, Title, and Link
> 50. Pow(x, n) https://leetcode.com/problems/powx-n/description/
> 
> ### Bug Category
> Incorrect test case _(Output of test case is incorrect as per the problem statement)_
> 
> ### Bug Description
> In first 3 testcases in this problem, the answer of the third test case of this problem should be 0.25, but the answer in the test case is 1.000. This is incorrect.
> 
> ### Language Used for Code
> None
> 
> ### Code used for Submit/Run operation
> _No response_
> 
> ### Expected behavior
> The answer should be 0.25 insted of 1.00. The testcase should be passed, but it didnot.
> 
> ### Screenshots
> _No response_
> 
> ### Additional context
> _No response_



No bro all the test cases are correct , i have done this question its passed . i also added a screenshot of the solution
