### ISSUE TITLE
[BUG] - <title> 1671. Minimum Number of Removals to Make Mountain Array

### ISSUE THREAD

**Issue by Sri-Vidya-Guttula** [LeetCode-Feedback/LeetCode-Feedback#25058]
### LeetCode Username

splendidsrividya

### Problem Number, Title, and Link

1671. Minimum Number of Removals to Make Mountain Array https://leetcode.com/problems/minimum-number-of-removals-to-make-mountain-array?envType=daily-question&envId=2024-10-30

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description for  "Minimum Number of Removals to Make Mountain Array" Problem

**Explanation of the Issue:**

Test Case: [1, 3, 3, 3, 3, 2, 1]
This test case introduces a scenario where there are **multiple consecutive identical elements (3s)** in the middle of the array. According to the mountain array requirements:

The array should strictly increase up to a single peak.
After the peak, it should strictly decrease.

In this array, the consecutive 3s in the middle create a plateau, which breaks the strict increase condition. For the array to meet the mountain array criteria, all repeated 3s need to be removed so that only a single peak remains, resulting in a strictly increasing and then strictly decreasing sequence.

Expected Output: 3
Three elements need to be removed (the repeated 3s) to make [1, 3, 2, 1], which is a valid mountain array.

Unusual Behavior: 1 (incorrect)
The solution incorrectly identifies this as requiring only one removal, likely because it doesn’t handle multiple identical elements as violations of the strict increase or decrease condition.

**Why This Test Case Is Important?**

This case is essential for validating that the solution can correctly handle sequences where repeated elements occur in the middle of the array, potentially forming a plateau. It ensures that the algorithm:

Recognizes and removes plateaus, ensuring the mountain array criteria are strictly followed.
Correctly calculates the minimum number of removals required to achieve a valid mountain shape.
Without handling cases like this, solutions might produce incorrect results by misinterpreting plateaus as valid parts of a mountain, which leads to fewer removals than necessary.

![Screenshot (228)](https://github.com/user-attachments/assets/49d13311-bff6-4d1e-8e31-f0ad2460e920)

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
class Solution {
public:
    int minimumMountainRemovals(vector<int>& nums) {
        int n = nums.size();

        vector<int> LIS(n, 1);
        vector<int> LDS(n, 1);
        for(int i=0; i<n; i++){
            for(int j=0; j<i; j++){
                if(nums[j] < nums[i] && LIS[i] < LIS[j] + 1){
                    LIS[i] = LIS[j] + 1;
                }
                
            }
            
        }

        for(int i=n-1; i>=0; i--){
            for(int j=n-1; j>i; j--){
                if(nums[j] < nums[i] && LDS[i] < LDS[j]+1)
                LDS[i] = LDS[j] +1 ;
            }
        }

        

        int maxi = 1;

        for(int i=1; i<=n-2; i++ ){
            if(nums[i-1] < nums[i] && nums[i] > nums[i+1])  maxi = max(maxi, LIS[i]+LDS[i]);
        }

        if(n- (maxi-1) == n) return 1;

        return n-(maxi-1);
    }
};
```

### Expected behavior

Explanation of the Issue:

Test Case: [1, 3, 3, 3, 3, 2, 1]
This test case introduces a scenario where there are multiple consecutive identical elements (3s) in the middle of the array. 

According to the mountain array requirements:

The array should strictly increase up to a single peak.
After the peak, it should strictly decrease.
In this array, the consecutive 3s in the middle create a plateau, which breaks the strict increase condition. For the array to meet the mountain array criteria, all repeated 3s need to be removed so that only a single peak remains, resulting in a strictly increasing and then strictly decreasing sequence.

Expected Behavior: 3
Three elements need to be removed (the repeated 3s) to make [1, 3, 2, 1], which is a valid mountain array.
Wrong Behavior: 1 (incorrect)
The solution incorrectly identifies this as requiring only one removal, likely because it doesn’t handle multiple identical elements as violations of the strict increase or decrease condition.

Why This Test Case Is Important:
This case is essential for validating that the solution can correctly handle sequences where repeated elements occur in the middle of the array, potentially forming a plateau. It ensures that the algorithm:

Recognizes and removes plateaus, ensuring the mountain array criteria are strictly followed.
Correctly calculates the minimum number of removals required to achieve a valid mountain shape.

![Screenshot (228)](https://github.com/user-attachments/assets/e35a0fc6-ff18-4082-9f02-8a0fb20d043b)
![Screenshot (227)](https://github.com/user-attachments/assets/35c44409-3496-4305-8c14-323eb8671468)
![image](https://github.com/user-attachments/assets/ed403104-bd86-475c-9347-a8e8a215d71d)

### Screenshots

![Screenshot (228)](https://github.com/user-attachments/assets/e35a0fc6-ff18-4082-9f02-8a0fb20d043b)
![Screenshot (227)](https://github.com/user-attachments/assets/35c44409-3496-4305-8c14-323eb8671468)
![image](https://github.com/user-attachments/assets/ed403104-bd86-475c-9347-a8e8a215d71d)

**Comment by Amitsahu123789** [comment]
Solve it

**Comment by Sri-Vidya-Guttula** [comment]
Are there any updates, sir/ma'am?

**Comment by Sri-Vidya-Guttula** [comment]
May I expect any response from your end, sir/ma'am?
