### ISSUE TITLE
[BUG] - 177 题 SQL 代码模版错误

### ISSUE THREAD

**Issue by amcones-lc** [LeetCode-Feedback/LeetCode-Feedback#25055]
### LeetCode 用户名

amcones

### 问题号码、标题和链接

177. Nth Highest Salary https://leetcode.com/problems/nth-highest-salary/description/

### Bug Category

不正确或缺少“相关标签”

### 描述

代码模版中存在多余的 `-`

### 你使用的语言

MySQL

### 你提交或者运行的代码

```bash
-CREATE FUNCTION getNthHighestSalary(N INT) RETURNS INT
-BEGIN
-  RETURN (
-      # Write your MySQL query statement below.
-
-  );
-END
```

### 期望行为

去除代码模版中多余的 `-`

**Comment by liyuzhu-lc** [comment]
Could U.S. side take a look at this issue.thanks.
