### ISSUE TITLE
Missing Test Case - LCR 021. 删除链表的倒数第 N 个结点

### ISSUE THREAD

**Issue by Closed-interval** [LeetCode-Feedback/LeetCode-Feedback#25057]
### LeetCode 用户名

saint

### 问题号码、标题和链接

LCR021 删除链表的倒数第N个节点https://leetcode.cn/problems/SLwz0R/description/?envType=problem-list-v2&envId=linked-list

### Bug Category

不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*

### 描述

当n的值大于链表长度时,未能正确识别该情况

### 你使用的语言

C++

### 期望行为

或判断为非法的输入，或允许该输入但不对原链表进行操作（因为需要移除的节点不存在）

**Comment by liyuzhu-lc** [comment]
感谢您的宝贵反馈，我们已经将您的反馈提交给我们的负责团队，并将会对相关信息进行核查，有新的进展及时再与您联系。感谢您的理解与支持。

**Comment by amcones-lc** [comment]
您好，在与相关团队核实后：***不处理***。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
