### ISSUE TITLE
题解示例不对

### ISSUE THREAD

**Issue by boatrainlsz** [LeetCode-Feedback/LeetCode-Feedback#2505]
**你的 LeetCode 用户名**
boatrain
**Bug 类型**
题解

**描述**
题解中写到：
“在初始时，左右指针分别指向数组的左右两端，它们可以容纳的水量为 min(1, 7) * 8 = 8min(1,7)∗8=8。”，但是所给示例的右指针并未指向7，见下图：
![Snipaste_2021-02-26_21-48-11](https://user-images.githubusercontent.com/18243785/109308282-c1f0e580-787c-11eb-98f0-ec314b484982.png)

**Comment by feiceh** [comment]
你好，请提供一下题目编号，同时也可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query= )「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。

**Comment by boatrainlsz** [comment]
@feiceh ，链接地址：https://leetcode-cn.com/problems/container-with-most-water/solution/sheng-zui-duo-shui-de-rong-qi-by-leetcode-solution/

**Comment by feiceh** [comment]
![image](https://user-images.githubusercontent.com/61722985/109482880-87c05780-7ab9-11eb-9441-de37942d1df3.png)
你好@boatrainlsz ，我们暂时无法重现这个问题出现的情况，建议清空一下 cookie 缓存或换个浏览器再试试。

**Comment by boatrainlsz** [comment]
@feiceh ，浏览器缓存清理过了，还是显示得不对。
版本信息如下：

Microsoft Edge | 88.0.705.81 (官方内部版本) (64 位)
-- | --
修订 | 324d415ccf2f0dac8fa87e00b3e07b69f8d3d9e6
操作系统 | Windows 10 OS Version 2009 (Build 19042.804)
JavaScript | V8 8.8.278.17
用户代理 | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36 Edg/88.0.705.81

图片如下：

![image](https://user-images.githubusercontent.com/18243785/109514038-9d954300-7ae0-11eb-9ed4-d3b0e0936c82.png)

**Comment by feiceh** [comment]
@boatrainlsz 感谢反馈，这个问题将会提交至负责团队核实。Github 仓库只用于反馈大家在本站学习过程中遇到的题目和题解问题，问题我先关闭，后续使用中有问题欢迎点击这里 [提交工单](https://support.leetcode-cn.com/hc/request/new/) 反馈。

**Comment by feiceh** [comment]
@boatrainlsz 感谢反馈，这个可能是浏览器兼容性问题导致，建议切换 Chrome 试一下。Github 仓库只用于反馈大家在本站学习过程中遇到的题目和题解问题，问题我先暂时关闭，后续使用中有任何问题欢迎点击「https://support.leetcode-cn.com/hc/kb/section/1115013」 提交工单反馈，请知晓～
