### ISSUE TITLE
987. Vertical Order Traversal of a Binary Tree

### ISSUE THREAD

**Issue by Umadevi-R** [LeetCode-Feedback/LeetCode-Feedback#2507]
#### Your LeetCode username

Umadevi_R

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The question says->There may be multiple nodes in the same row and same column. In such a case, sort these nodes by their values.But for the given below test case the expected output is
Testcase:[3,1,4,0,2,2]
Expected output:[[0],[1],[3,2,2],[4]]
But according to the question, it should be:[[0],[1],[2,2,3],[4]]

#### Code you used for Submit/Run operation

```
/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
class Solution {
public:
    vector<vector<int>> verticalTraversal(TreeNode* root) {
        queue<pair<TreeNode*,int>>q;
        map<int,vector<int>>m;
        int hd;
        vector<vector<int>>v;
        q.push(make_pair(root,hd));
        while(!q.empty())
        {
            pair<TreeNode*,int>temp=q.front();
            q.pop();
            TreeNode* node=temp.first;
            hd=temp.second;
            m[hd].push_back(node->val);
            if(node->left)
            {
                q.push(make_pair(node->left,hd-1));
            }
            if(node->right)
            {
                q.push(make_pair(node->right,hd+1));
            }
        }
        map<int,vector<int>>::iterator it;
        for(it=m.begin();it!=m.end();it++)
        {
            vector<int>temp=it->second;
            sort(temp.begin(),temp.end());
            v.push_back(temp);
        }
        return v;
    }
};
```

#### Language used for code
C++

#### Expected behavior

The question says->There may be multiple nodes in the same row and same column. In such a case, sort these nodes by their values.But for the given below test case the expected output is
Testcase:[3,1,4,0,2,2]
Expected output:[[0],[1],[3,2,2],[4]]
But according to the question, it should be:[[0],[1],[2,2,3],[4]]

I have also attached my submission link: https://leetcode.com/submissions/detail/461159837/

**Comment by lc-kay** [comment]
@Umadevi-R The expected output is correct. Please refer to the discuss section of the problem to raise your question or find similar concerns raised there. Thank you for your time.
