### ISSUE TITLE
1109. Corporate Flight Bookings

### ISSUE THREAD

**Issue by dhritishkaranth** [LeetCode-Feedback/LeetCode-Feedback#2508]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
There seems to be a problem in the test harness for the problem.
After typing my code and clicking 'run' (with a valid testcase taken from the question), I get the message: "Invalid testcase: global name 'num_flights' is not defined". Submitting the same code for a full run ('submit' button) works fine. 

The error message is seen for every testcase.

#### Code you used for Submit/Run operation

```
class Solution {
    public int[] corpFlightBookings(int[][] bookings, int n) {
        int[] flights = new int[n];
        for (int[] booking: bookings) {
            flights[booking[0] - 1] += booking[2];
            if (booking[1] < flights.length)
                flights[booking[1]] -= booking[2];
        }
        for (int i = 1; i < flights.length; ++i) {
            flights[i] += flights[i-1];
        }
        
        return flights;
    }
}
```

#### Language used for code
Java

#### Expected behavior
Code should execute after clicking 'run'.

#### Screenshots
![image](https://user-images.githubusercontent.com/9249038/109376647-ee0b6700-787a-11eb-92da-e4932cfbf419.png)

**Comment by lc-kay** [comment]
Hi @dhritishkaranth 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @dhritishkaranth 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
