### ISSUE TITLE
[SQL 面试宝典 10. 人口流动分析] 题目示例错误

### ISSUE THREAD

**Issue by e-chocolate** [LeetCode-Feedback/LeetCode-Feedback#25091]
### LeetCode 用户名

Cmite

### 问题号码、标题和链接

SQL 面试宝典 10. 人口流动分析 https://leetcode.cn/problems/OQBDpm/

### Bug Category

问题描述

### 描述

中文题干的输出为
输出: 
+------+------------+
| 城市  | <font color="orchid">**总人口流入数 **</font>|
+------+------------+
| 合肥  | 599        |
| 天津  | 527        |
| 北京  | 1714       |
| 苏州  | 873        |
| 深圳  | 1479       |
| 武汉  | 671        |
| 大连  | 398        |
| 广州  | 400        |
| 长春  | 739        |
+------+------------+

测试样例以及测试用例的表头为
| 城市 | <font color="orchid">**总流入人口数 **</font>|

### 你使用的语言

None

### 你提交或者运行的代码

```bash
/* Write your PL/SQL query statement below */
select 流入城市 城市, sum(数量) 总流入人口数 from 各城市人口流动表
group by 流入城市
;
```

### 期望行为

测试用例与题目描述的表头应该统一。

**Comment by liyuzhu-lc** [comment]
感谢您的宝贵反馈，我们已经将您的反馈提交给我们的负责团队，并将会对相关信息进行核查，有新的进展及时再与您联系。感谢您的理解与支持。

**Comment by amcones-lc** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by e-chocolate** [comment]
> 你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

[Cmite](https://leetcode.cn/u/cmite/)

**Comment by amcones-lc** [comment]
你好，当前该题已更新，奖励已发放。
