### ISSUE TITLE
Missing Test Case - 819. Most Common Word

### ISSUE THREAD

**Issue by manassikri** [LeetCode-Feedback/LeetCode-Feedback#2509]
#### Your LeetCode username

sikrimanas

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Few testcases are missing. My code is being accepted but is not working on the below mentioned testcase.
".."
[]

#### Code you used for Submit/Run operation

```
// mostCommonWord
class Solution {
    public String mostCommonWord(String paragraph, String[] banned) {

        TreeMap<String,Integer>map = new TreeMap<>();
        HashSet<String>set = new HashSet<>();
        for(int i=0;i<banned.length;i++){
            set.add(banned[i]);
        }
        StringBuilder sb = new StringBuilder();
        for(int i=0;i<paragraph.length();i++){
            char ch = paragraph.charAt(i);
            if(ch>='A' && ch<='Z'){
                ch=(char)(ch-(int)'A'+(int)'a');
                sb.append(ch);
            }else if(ch>='a' && ch<='z'){
                sb.append(ch);
            }else{
                String tmp = sb.toString();
                if(map.containsKey(tmp)){
                    int temp= map.get(tmp);
                    temp++;
                    map.replace(tmp,temp);
                    sb=new StringBuilder();
                }else{
                    if(tmp.length()!=0 && !set.contains(tmp)){
                        map.put(tmp,1);
                        
                    }
                    sb=new StringBuilder();
                }
            }
        }
        String tmp = sb.toString();
        if(tmp.length()>0 && !set.contains(tmp)){
            if(map.containsKey(tmp)){
                int temp= map.get(tmp);
                temp++;
                map.replace(tmp,temp);
                
            }else{
                if(tmp.length()!=0 && !set.contains(tmp)){
                    map.put(tmp,1);
                    
                }
               
            }
        }
        // if(map.size()==0){
        //     return "";
        // }
        return Collections.max(map.entrySet(), Map.Entry.comparingByValue()).getKey();
        
        
        
    }
}
```

#### Language used for code

Java

#### Expected behavior

My code is being accepted while on the above mentioned testcase it is failing. If I uncomment the last piece of code it will handle the test case properly.
This solution should not be accepted as it is failing on the testcase

#### Screenshots

![image](https://user-images.githubusercontent.com/43198579/109381782-505b7a80-7902-11eb-8fea-56cfc275fd40.png)
![image](https://user-images.githubusercontent.com/43198579/109381820-8c8edb00-7902-11eb-9f31-788d694dd24d.png)

![image](https://user-images.githubusercontent.com/43198579/109381813-839e0980-7902-11eb-85aa-7a290ac35432.png)

**Comment by lc-kay** [comment]
Hi @manassikri 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by lc-kay** [comment]
Hi @manassikri 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
