### ISSUE TITLE
#476 Number Complement - Correct test case, but wrong submission still getting accepted

### ISSUE THREAD

**Issue by NishadKumar** [LeetCode-Feedback/LeetCode-Feedback#251]
Correct test case, but wrong outcome
-Number Complement
-Python

Bug Description:
For the Number Complement test cases, if I run my code against the test case input "0", the outcome is 'Wrong Answer'. However, if I submit the solution, it is being accepted. 

**what language is your code written in**
Python

**The code you submit/run**
```
class Solution(object):
    def findComplement(self, num):
        """
        :type num: int
        :rtype: int
        """
        num_copy, flip_bit = num, 1
        
        while num_copy:
            num = num ^ flip_bit
            flip_bit = flip_bit << 1
            num_copy = num_copy >> 1
            
        return num
```

**Expected behavior**
The submission was expected not to be accepted since there is one test case which still fails. 

**Screenshots**
Attached.

**Additional context**
Problem #476
<img width="1668" alt="Screen Shot 2020-05-04 at 7 28 52 AM" src="https://user-images.githubusercontent.com/18685836/80966624-772c4b80-8dda-11ea-90b2-ae98616f4d4f.png">
<img width="843" alt="Screen Shot 2020-05-04 at 7 31 19 AM" src="https://user-images.githubusercontent.com/18685836/80966637-7c899600-8dda-11ea-9840-7cfc199fe5be.png">

**Comment by CooperCooperCooper** [comment]
Hi @NishadKumar ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by NishadKumar** [comment]
Thanks @CooperCooperCooper! :)

**Comment by CooperCooperCooper** [comment]
Hi @
Thank you for your time. Upon reviewing the submitted information, we found you're missing an important part of the statement "Given a positive integer". Please update your code accordingly. We appreciate your support.

**Comment by NishadKumar** [comment]
@CooperCooperCooper sounds good and thanks for the clarification. I tried zero assuming it to be a positive integer.  :)
