### ISSUE TITLE
Missing Test Case - 29. Divide Two Integers

### ISSUE THREAD

**Issue by hss15** [LeetCode-Feedback/LeetCode-Feedback#2510]
#### Your LeetCode username
hss15

#### Category of the bug
- [ ] Question https://leetcode.com/problems/divide-two-integers/
- [ ] Solution https://leetcode.com/submissions/detail/461229701/
- [ ] Language Java

#### Description of the bug
My code got accepted but then I realized that my solution was actually not 100% correct.
For input (10, -10), the expected result should be -1.
My code returns 1.
Still the submission got accepted because this testcase is probably missing.

#### Code you used for Submit/Run operation
```
// Two Sum - Java
class Solution {
    public int divide(int dividend, int divisor) {
        if (dividend == Integer.MIN_VALUE && divisor == -1)
            return Integer.MAX_VALUE;
        
        if (divisor == 1)
            return dividend;
        
        if (divisor == -1)
            return -dividend;
        
        if (dividend == 0)
            return 0;
        
        int negative = 0;
        if (dividend > 0) {
            dividend = -dividend;
            negative++;
        }
        
        if (divisor > 0) {
            divisor = -divisor;
            negative++;
        }
        
        // INCORRECT CONDITION
        if (dividend == divisor)
            return 1;
        
        List<Integer> powOfTwo = new ArrayList<>();
        int value = divisor;

        powOfTwo.add(value);
        
        while(value >= dividend) {
            if (Integer.MAX_VALUE + value > -value) {
                value += value;
                powOfTwo.add(value);
            } else
                break;
        }
        
        int answer = 0;
        int index = powOfTwo.size() - 1;
        while(divisor >= dividend && index >= 0) {
            value = powOfTwo.get(index);
            while (value >= dividend) {
                answer += (1 << index);
                dividend -= value;
            }
            index--;
        }
        
        return (negative == 1 ? -answer : answer);
    }
}
```

#### Language used for code
Java

#### Expected behavior
for input 10, -10, the expected answer is -1 while my solution returns 1.
Upon submission, my solution got accepted.

#### Screenshots
<img width="973" alt="Screenshot 2021-02-27 at 3 28 31 PM" src="https://user-images.githubusercontent.com/5968535/109384074-76881700-7910-11eb-9899-11d875a6b2b0.png">

**Comment by lc-kay** [comment]
Hi @hss15 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @hss15 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
