### ISSUE TITLE
Missing Test Case - 140. Word Break II

### ISSUE THREAD

**Issue by xbecodex** [LeetCode-Feedback/LeetCode-Feedback#2511]
#### Your LeetCode username
xbe

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Solution accepted however running local custom test case gets: TLE (Time Limit Exceeded)

#### Code you used for Submit/Run operation

```
Test case: 
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab"
["a", "aa", "aaa", "aaaaa","aaaaaa","aaaaaaaaa","aaaaaaaaaaa","aaaaaaaaaaaaa","aaaaaaaaaaaaaa","aaaaaaaaaaaaaaa","aaaaab"]
```
```
class Solution {
    public List<String> wordBreak(String s, List<String> wordDict) {
        return dfs(s, 0, wordDict, new HashMap<>());
    }
    
    private List<String> dfs(String str, int currIndex, List<String> words, Map<Integer, List<String>> memo) {
        
        if (memo.containsKey(currIndex)) {
            return memo.get(currIndex);
        }
        
        List<String> ans = new ArrayList<>();
        for (String word : words) {
            if (str.startsWith(word, currIndex)) {
                
                if (currIndex + word.length() == str.length()) {
                    ans.add(word);
                } 
                else {
                    List<String> res = dfs(str, currIndex + word.length(), words, memo);
                
                    for (String s : res) {
                        ans.add(word + " " + s);
                    }
                }
            }
        }
        
        memo.put(currIndex, ans);
        return ans;
    }
}
```

#### Language used for code
JAVA

#### Expected behavior
Expected either my solution to TLE when submitted or pass on my test case

#### Screenshots
<img width="1677" alt="Screenshot 2021-02-27 at 10 01 11" src="https://user-images.githubusercontent.com/66902519/109384270-99e89d00-78e3-11eb-8daa-6ddb4a629133.png">

**Comment by lc-kay** [comment]
Hi @xbecodex 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @xbecodex 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
