### ISSUE TITLE
1764题测试用例不完整

### ISSUE THREAD

**Issue by zjy666lkjfglasdf** [LeetCode-Feedback/LeetCode-Feedback#25120]
### LeetCode 用户名

江月何年初照人

### 问题号码、标题和链接

1764. 通过连接另一个数组的子数组得到一个数组 https://leetcode.cn/problems/form-array-by-concatenating-subarrays-of-another-array/description/

### Bug Category

缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*

### 描述

测试用例不完整导致错误代码能通过

### 你使用的语言

C++

### 你提交或者运行的代码

```bash
class Solution {
public:
    int kmp(vector<int>& t, vector<int>& s) {
        if (t.size() > s.size()) return -1;
        int n = s.size();
        int m = t.size();
        t.insert(t.begin(), 0);
        s.insert(s.begin(), 0);
        vector<int>next(m + 1, 0);

        int i = 2, j = 0;
        while (i <= m) {
            while (j && t[j + 1] != t[i]) j = next[j];
            if (t[j + 1] == t[i]) j++;
            next[i] = j;
            i++;
        }
        i = 1, j = 0;
        while (i <= n) {
            while (j && s[i] != t[j + 1]) j = next[j];
            if (s[i] == t[j + 1]) j++;
            if (j == m) {
                return i;
            }
            i++;
        }

        return -1;
    }
    bool canChoose(vector<vector<int>>& groups, vector<int>& nums) {
        int i = 0;
        for (int j = 0; j < groups.size(); j++) {
            vector<int>tmp(nums.begin() + i, nums.end());
            i = kmp(groups[j], tmp);
            if (i == -1) return false;
        }

        return true;
    }
};
```

### 期望行为

补充测试用例：
[[1,2,3],[3,4],[1,2,3]]
[7,7,1,2,3,3,4,7,7]

### 屏幕截图

![Uploading image.png…]()

### 额外的上下文

提供的代码中的这一步： i = kmp(groups[j], tmp); 是错误的，不能让 i 直接等于kmp匹配后的结果，这部分正确写法应该是这样：
vector<int>tmp(nums.begin() + i, nums.end());
            int x = kmp(groups[j], tmp);
            i += x;
            if (x == -1) return false;

**Comment by liyuzhu-lc** [comment]
感谢您的宝贵反馈，我们已经将您的反馈提交给我们的负责团队，并将会对相关信息进行核查，有新的进展及时再与您联系。感谢您的理解与支持。

**Comment by amcones-lc** [comment]
We have received feedback, please wait for us to process

**Comment by amcones-lc** [comment]
你好，当前该题已添加测试用例， 请留言告知一下力扣中文网站的 ID，我们给予积分奖励。

**Comment by zjy666lkjfglasdf** [comment]
> 你好，当前该题已添加测试用例， 请留言告知一下力扣中文网站的 ID，我们给予积分奖励。

https://leetcode.cn/u/charming-tuk8m/
这是我力扣个人主页

**Comment by amcones-lc** [comment]
你好，当前该题已添加测试用例，奖励已发放。
