### ISSUE TITLE
Missing Test Case - 29. Divide Two Integers

### ISSUE THREAD

**Issue by shubhamrgh** [LeetCode-Feedback/LeetCode-Feedback#2515]
#### Your LeetCode username

shubhamrgh

#### Category of the bug
- [ ] Question
-  Solution
- [ ] Language

#### Description of the bug

My code pass all the test cases on leetcode but it fail on my custom input.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int divide(int dividend, int divisor) {
        int sign= (dividend<0 ^ divisor<0) ? -1 : 1; //same ? 0(false) (XOR)
        
        long ldividend=labs(dividend);
        long ldivisor=labs(divisor);
     
        long res = exp(log(ldividend)-log(ldivisor));
        cout<<ldividend<<"/"<<ldivisor<<"="<<res;
        if(res>INT_MAX)
            return sign==1 ? INT_MAX:INT_MIN;
        return sign*(int)res;
    }
};
```

#### Language used for code

c++

#### Screenshots

![Screenshot (64)](https://user-images.githubusercontent.com/60095905/109389649-36865b80-7933-11eb-9d09-1fd120a5c153.png)
![Screenshot (65)](https://user-images.githubusercontent.com/60095905/109389650-38501f00-7933-11eb-9090-d8f26cef6a26.png)

**Comment by lc-kay** [comment]
Hi @shubhamrgh 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @shubhamrgh 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
