### ISSUE TITLE
Incorrect testcases - 89. Gray Code

### ISSUE THREAD

**Issue by 201430098137** [LeetCode-Feedback/LeetCode-Feedback#2516]
the question description:
The gray code is a binary numeral system where two successive values differ in only one bit.

Given an integer n representing the total number of bits in the code, return any sequence of gray code.

A gray code sequence must begin with 0.

#### Your LeetCode username

题刻

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
func grayCode(n int) []int {
	nums := make([]int, 0, 1<<uint(n))
	nums = generateNums(nums, n-1)
	return nums
}

func generateNums(nums []int, level int) []int {
	if level == 0 {
		nums = append(nums, 0)
		nums = append(nums, 1)
		return nums
	}
	nums = generateNums(nums, level-1)
	length := len(nums)
	num := 1<<uint(level)
	n := num + nums[len(nums)-1]
	nums = append(nums, n)
	for i:=0; i<length-1; i++ {
		n := nums[i] + num
		nums = append(nums, n)
	}
	return nums
}
```

#### Language used for code

GO

#### Expected behavior

the result is:

![image](https://user-images.githubusercontent.com/13937318/109391594-d6071680-7952-11eb-9d08-05a2a5e8b3c0.png)
I expected my output is correct, but it return wrong. it absolutely is gray code.

**Comment by lc-kay** [comment]
@201430098137 The expected output is correct. Please refer to the discuss section of the problem to raise your question or refer to other posts. Thank you for your time.
