### ISSUE TITLE
没有Oracle对应表

### ISSUE THREAD

**Issue by e-chocolate** [LeetCode-Feedback/LeetCode-Feedback#25174]
### LeetCode 用户名

Cmite

### 问题号码、标题和链接

[SQL 面试宝典 44. 偏移窗口函数应用 I](https://leetcode.cn/problems/3khYBD/)

### Bug Category

不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*

### 描述

`select`语句执行出错，同一个SQL语句，MySQL可以正常查表，但是Oracle不可以。
[SQL 面试宝典 45. 偏移窗口函数应用 II](https://leetcode.cn/problems/7jO2zB/)也具有相同的问题。

### 你使用的语言

None

### 你提交或者运行的代码

```bash
/* Write your PL/SQL query statement below */
select * from 得分表;
```

### 期望行为

Oracle可以正常查表

### 屏幕截图

![MySQL](https://github.com/user-attachments/assets/907ebe59-22e5-4106-9de3-24876747c532)

![Oracle](https://github.com/user-attachments/assets/7321146b-445d-49fb-854e-fc5258a1caba)

**Comment by liyuzhu-lc** [comment]
感谢您的宝贵反馈，我们已经将您的反馈提交给我们的负责团队，并将会对相关信息进行核查，有新的进展及时再与您联系。感谢您的理解与支持。

**Comment by e-chocolate** [comment]
类似的题目还有[SQL 面试宝典 52. 找到特殊的电话号码](https://leetcode.cn/problems/GGz4x5/)，请一并检查一下。

**Comment by amcones-lc** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by e-chocolate** [comment]
你好，请再检查一下[SQL 面试宝典 44. 偏移窗口函数应用 I](https://leetcode.cn/problems/3khYBD/)，使用 Oracle 依然出错。

[个性域名](https://leetcode.cn/u/cmite)

![image](https://github.com/user-attachments/assets/07a4463b-3fba-4da7-ab37-aaed2883d89a)

**Comment by amcones-lc** [comment]
你好，当前该题已修复，奖励已发放。
