### ISSUE TITLE
Missing Test Case - 205. Isomorphic Strings

### ISSUE THREAD

**Issue by irymarchyk** [LeetCode-Feedback/LeetCode-Feedback#25179]
### LeetCode Username

user3402Px

### Problem Number, Title, and Link

205. Isomorphic Strings, https://leetcode.com/problems/isomorphic-strings 

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

Just trying to run default test cases, and UI shows Internal Error:
```
You've found a test case the system can't handle. Please [submit](https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/new?assignees=&labels=&template=bug-report-english.yml&title=Missing%20Test%20Case%20-%20205.%20Isomorphic%20Strings&username=user3402Px&code=%5Btype%20the%20code%5D&bug-description=%60%60%60%0A%22egg%22%0A%22add%22%0A%22foo%22%0A%22bar%22%0A%22paper%22%0A%22title%22%0A%60%60%60) them to help us improve. Thank you!
``` 

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
class Solution {
public:
    bool isIsomorphic(string s, string t) {
        for (int pos = 0; pos < s.length(); ++pos) {
            char a = s[pos];
            char replace_with = t[pos];
            if (a == replace_with) {
                continue;
            }

            s[pos] = replace_with;
            for (int i = pos + 1; i < s.length(); ++i) {
                if (s[i] == a) {
                    s[i] = replace_with;
                }
            }
        }

        return s == t;
    }
};
```

### Expected behavior

Expected that test case can be run. If some error happens - it will be shown intead of generic error.

### Additional context

Seems like if I replace code  with simple `return false` it still fails:
```
class Solution {
public:
    bool isIsomorphic(string s, string t) {
        return false;
    }
};
```

**Comment by gobbledy-gook** [comment]
Did you check if it is following the condition? 
> No two characters may map to the same character, but a character may map to itself.

In example `foo` & `bar`, with your code, `o` is getting mapped to both `a` and `r`.

**Comment by irymarchyk** [comment]
Hi @gobbledy-gook , the problem not with the code itself (I believe my code is incorrect); the problem is when I run the code, instead of failing test case or error, it shows generic message `You've found a test case the system can't handle. Please [submit](https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/new?assignees=&labels=&template=bug-report-english.yml&title=Missing%20Test%20Case%20-%20205.%20Isomorphic%20Strings&username=user3402Px&code=%5Btype%20the%20code%5D&bug-description=%60%60%60%0A%22egg%22%0A%22add%22%0A%22foo%22%0A%22bar%22%0A%22paper%22%0A%22title%22%0A%60%60%60) them to help us improve. Thank you!` . That is why I created this ticket.
I can see the same error even if I don't add any code to default one:
`
class Solution {
public:
    bool isIsomorphic(string s, string t) {
        return false;
    }
};
`

**Comment by irymarchyk** [comment]
BTW, I tried again, and  I cannot reproduce the issue. Right now correct errors (failed test cases) are shown. So it seems to be some temporary glitch/infra issue?
