### ISSUE TITLE
Missing Test Case - 877. Stone Game

### ISSUE THREAD

**Issue by odanylevskyi** [LeetCode-Feedback/LeetCode-Feedback#2517]
The issue with test cases is that if you will return `true` then it will work as a solution, but the only way to get `false` is to have an odd number of piles where all numbers are equal except the middle one. 
E.g. [1, 1, 1, 99, 1 , 1, 1], so in this case `return true` will not work as a solution.

**Comment by lc-kay** [comment]
@odanylevskyi The test case you proposed is an invalid test case. Based on the constraints of the problem, the test case length must be even. Thank you for your time.
