### ISSUE TITLE
content issues on description - 48. rotate image

### ISSUE THREAD

**Issue by shinelikeamillion** [LeetCode-Feedback/LeetCode-Feedback#2518]
**你的 LeetCode 用户名**
lilsean

**Bug 类型**
- [ ] 题目
- [x] 题解
- [ ] 编程语言

**描述**
描述你遇到的 bug
![image](https://user-images.githubusercontent.com/9711578/109408969-7f88ef00-79c9-11eb-9c3f-947bccfa197e.png)

我想这里的 2（红色方框里） 可能是官方的一个笔误

**Comment by feiceh** [comment]
@shinelikeamillion 感谢反馈，当前问题已更新修复，ID：lilsean 给予积分奖励，请查收。
