### ISSUE TITLE
[BUG] - 中英文翻译不清

### ISSUE THREAD

**Issue by ZhangBowen** [LeetCode-Feedback/LeetCode-Feedback#25186]
### LeetCode 用户名

berwyn

### 问题号码、标题和链接

2944. Minimum Number of Coins for Fruits https://leetcode.cn/problems/minimum-number-of-coins-for-fruits/description/

### Bug Category

问题描述

### 描述

英文题面中“you can get any number of the next (i + 1) fruits for free.” 
与中文题面“那么你可以免费获得下标范围在 [i + 1, i + i] 的水果。”不匹配，实际应该为中文版的意思

中文题面中提到“给你一个下标从 1 开始的数组 prices”
英文没有提到下标的开始数字

### 你使用的语言

None

### 期望行为

将英文题面与中文题面的描述对齐

**Comment by liyuzhu-lc** [comment]
感谢您的宝贵反馈，我们已经将您的反馈提交给我们的负责团队，并将会对相关信息进行核查，有新的进展及时再与您联系。感谢您的理解与支持。

**Comment by amcones-lc** [comment]
We have received feedback, please wait for us to process

**Comment by amcones-lc** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by ZhangBowen** [comment]
感谢
个性域名：berwyn

**Comment by amcones-lc** [comment]
你好，当前该题已更新，奖励已发放。
