### ISSUE TITLE
Missing Test Case - 1774. Closest Dessert Cost

### ISSUE THREAD

**Issue by Aniket-Jain-byte** [LeetCode-Feedback/LeetCode-Feedback#2519]
#### Your LeetCode username

LeetCode username - helloaniorigamiwpu

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

I didn't read question properly that if difference between 2 costs is equal choose lower one.
My solution got accepted but fails for the above testcase.
[1]
[8,10]
10

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int target;
    int closest(int a,int b){
        if(a==0)
            return b;
        if(b==0)
            return a;
        return abs(target-a)<abs(target-b)?a:b;
    }
    
    int dfs(vector<int>&top,int i,int sum){
        if(i>=top.size())
            return sum;

        int a=dfs(top,i+1,sum+top[i]);
        int b=dfs(top,i+1,sum+(top[i]*2));
        int c=dfs(top,i+1,sum);
        sum=closest(a,closest(b,c));
        return sum;
    }
    
    int closestCost(vector<int>& base, vector<int>& top, int t) {
        target=t;//i made target global so that i don't need to pass it in any function
        int ans=0;
        for(int i=0;i<base.size();i++){
            ans = closest(dfs(top,0,base[i]),ans);
        } 
        return ans;
    }
};
```

#### Language used for code

Language used: C++

#### Expected behavior

Solution should have failed but got accepted

#### Screenshots

![image](https://user-images.githubusercontent.com/76682881/109409050-3af35880-79b5-11eb-8a87-f40fdff321e7.png)

**Comment by lc-kay** [comment]
Hi @Aniket-Jain-byte 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by Aniket-Jain-byte** [comment]
@lc-kay my testcase has been contributed but still i didn't get my leetcode coins. please look into this

**Comment by lc-kay** [comment]
Hi @Aniket-Jain-byte 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by Aniket-Jain-byte** [comment]
@lc-kay thanks a lot
