### ISSUE TITLE
[BUG] - 3011. Find if Array Can Be Sorted - Wrong test case

### ISSUE THREAD

**Issue by EmiljanoBabaj** [LeetCode-Feedback/LeetCode-Feedback#25208]
### LeetCode Username

emiliobabaj

### Problem Number, Title, and Link

3011. Find if Array Can Be Sorted https://leetcode.com/problems/find-if-array-can-be-sorted

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

Test case [75,34,30] expects a False result but it's wrong.

75 = 1001011 -> 4 bits
30 = 11110 -> 4 bits

These two can be swapped and produce a sorted array so the result of this test should be True.

My solution passes 992 / 999 till it arrives at the [75,34,30].

### Language Used for Code

Java

### Code used for Submit/Run operation

```bash
public boolean canSortArray(int[] nums) {
        int[] sortedNums = Arrays.stream(nums).sorted().toArray();

        for (int i = 0; i < nums.length; i++) {
            if (Integer.bitCount(sortedNums[i]) != Integer.bitCount(nums[i])){
                return false;
            }
        }
        return true;
    }
```

### Expected behavior

Test case [75,34,30] should return True.

**Comment by sumitkrao** [comment]
Only consecutive elements can be swapped. 
[75,34,30]
75 = 1001011 -> 4 bits
34 = 100010 -> 2 bits
30 = 11110 -> 4 bits
as 34 has 2 set bits 75 and 34 swap is not possible.

**Comment by EmiljanoBabaj** [comment]
For some reason, I didn't notice that in the problem description even tho I know what adjacent means. Thank you.
