### ISSUE TITLE
[BUG] - <评测系统出错>

### ISSUE THREAD

**Issue by Knight-boy** [LeetCode-Feedback/LeetCode-Feedback#25221]
### LeetCode 用户名

Knight-boy

### 问题号码、标题和链接

https://leetcode.cn/problems/sliding-window-median/description/?envType=problem-list-v2&envId=sliding-window

### Bug Category

不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*

### 描述

评测系统一直报网络错误

### 你使用的语言

C++

### 期望行为

评测可以正常提交

**Comment by liyuzhu-lc** [comment]
感谢您的宝贵反馈，我们已经将您的反馈提交给我们的负责团队，并将会对相关信息进行核查，有新的进展及时再与您联系。感谢您的理解与支持。

**Comment by amcones-lc** [comment]
感谢反馈，经核实该题目题解及测试用例暂无异常，力扣会不断努力给大家带来更好的学习社区！后续刷题学习中遇到问题，可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
