### ISSUE TITLE
Missing Test Case - 29. Divide Two Integers(javascript solution)

### ISSUE THREAD

**Issue by anujb6** [LeetCode-Feedback/LeetCode-Feedback#2523]
var divide = function(dividend, divisor) {
 if (dividend === -2147483648 && divisor === -1) {
        return 2147483647;
    }
var sign = ((dividend < 0) ^ (divisor < 0)) ? -1 : 1;
dividend = Math.abs(dividend);
divisor = math.abs(divisor);
let quotient = 0;
while(dividend >= divisor){
dividend = dividend - divisor;
quotient++;
     }
return quotient
};

**Comment by lc-kay** [comment]
@anujb6 Please provide more details on the content-related issue you are trying to report. Thank you!

**Comment by lc-kay** [comment]
Hi @anujb6 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
