### ISSUE TITLE
Did Not Receive LeetCoins For Problem Contributed

### ISSUE THREAD

**Issue by LeetKing1** [LeetCode-Feedback/LeetCode-Feedback#2524]
Greetings LeetCode Team,

I contributed problem 4 (Car Fleet II) in today's contest (230) but did not receive any LeetCoins. Can we look into this? Here's the proof: https://leetcode.com/contribute/27288

Thanks

**Comment by lc-kay** [comment]
@LeetKing1 Please raise this issue to our help center/support@leetcode.com. 

We encourage you to share more [content-related issues](https://leetcode.com/discuss/general-discussion/526802/File-Problem-and-Solution-Content-Issues-to-Our-GitHub-Public-Feedback-Repo-Now!) here. Thank you again for your support and understanding.
