### ISSUE TITLE
Missing Test Case - 1546. Maximum Number of Non-Overlapping Subarrays With Sum Equals Target

### ISSUE THREAD

**Issue by polanwang404** [LeetCode-Feedback/LeetCode-Feedback#25278]
### LeetCode 用户名

polanwang404

### 问题号码、标题和链接

https://leetcode.cn/problems/maximum-number-of-non-overlapping-subarrays-with-sum-equals-target/

### Bug Category

问题描述

### 描述

应该是连续的子数组而不是子数组，测试用例：
nums=[2,3,1,2,1,1,0,5]  target=1
理论上答案应该是 2 => [2,3,2] 和 [1,1,5]，如果是连续子数组，则为 1 =>[3,1,2,1,1]

### 你使用的语言

Python/Python3

### 你提交或者运行的代码

```bash
from typing import List


class Solution:
    def maxNonOverlapping(self, nums: List[int], target: int) -> int:
        cur_set = {0}  # 初始化前缀子数组的和，当前没有元素所以为 0
        cur_sum = 0
        ans = 0
        for num in nums:
            cur_sum += num
            # 先计算当前的前缀和中是否有满足条件的
            if cur_sum - target in cur_set:
                # 此时前面的子数组的和已经满足条件，可以开始新的子数组了，所以 ans 加一
                ans += 1
                cur_set = {0}  # 从新的开始，清空前缀和
                cur_sum = 0
            else:
                cur_set.add(cur_sum)  # 这里记录每一步的时候，前面分布的元素和，概率累计函数似的
        return ans
```

### 期望行为

2

**Comment by liyuzhu-lc** [comment]
感谢您的宝贵反馈，我们已经将您的反馈提交给我们的负责团队，并将会对相关信息进行核查，有新的进展及时再与您联系。感谢您的理解与支持。

**Comment by amcones-lc** [comment]
We have received feedback, please wait for us to process
