### ISSUE TITLE
Weak test case----239. Sliding Window Maximum

### ISSUE THREAD

**Issue by modinitin13** [LeetCode-Feedback/LeetCode-Feedback#253]
**What kind of the bug**
Weak test cases

**Describe the bug**
The test cases are weak, the solution with time complexity O(N^2) is getting passed 

**what language is your code written in**
C++

**The code you submit/run**
```
class Solution {
public:
    vector<int> maxSlidingWindow(vector<int>& nums, int k) {
       vector<int> result;
        for(int i = 0; i < nums.size() - k + 1; ++i) {
            int max = nums[i];
            for(int j = i+1; j < i+k; ++j){
                max = std::max(max, nums[j]);
            }
            
            result.push_back(max);
        }
        return result;
    }
};
```

**Expected behavior**
The above solution should get TLE but getting AC

**Screenshots**

**Additional context**
I have attached the test file, 
[test.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/4575834/test.txt)
the test case should e added to the problem

**Comment by CooperCooperCooper** [comment]
Hi @modinitin13 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @modinitin13 ,
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
