### ISSUE TITLE
[BUG] - <缺陷标题>

### ISSUE THREAD

**Issue by bft2249228496** [LeetCode-Feedback/LeetCode-Feedback#25309]
### LeetCode 用户名

16605629357

### 问题号码、标题和链接

2418.按身高排序 https://leetcode.cn/problems/sort-the-people/description/

### Bug Category

不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*

### 描述

此题测试用例有bug，无法运行测试用例。用例本身没有问题，但是点击运行会报错：module 'string' has no attribute 'letters'。导致我一直以为我代码有问题，检查半天，最后发现直接提交就通过了。

### 你使用的语言

JavaScript

### 你提交或者运行的代码

```bash
/**
 * @param {string[]} names
 * @param {number[]} heights
 * @return {string[]}
 */
var sortPeople = function (names, heights) {
    const mapObj = {}
    for (let i = 0; i < heights.length; i++) {
        mapObj[heights[i]] = names[i]
    }
    return heights.sort((a, b) => b - a).map((item) => mapObj[item])
};
```

### 期望行为

期望和其他题目一样，点击运行能正常运行测试用例

### 屏幕截图

![leetcode](https://github.com/user-attachments/assets/05eaaa05-540d-457f-820f-1bdff27724e4)

**Comment by liyuzhu-lc** [comment]
感谢您的宝贵反馈，我们已经将您的反馈提交给我们的负责团队，并将会对相关信息进行核查，有新的进展及时再与您联系。感谢您的理解与支持。

**Comment by amcones-lc** [comment]
感谢反馈，经核实该题目题解及测试用例暂无异常，力扣会不断努力给大家带来更好的学习社区！后续刷题学习中遇到问题，可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。

**Comment by bft2249228496** [comment]
我又试了一下，现在好了，当时肯定是有问题的，不是说测试用例有问题，是点击运行测试用例的运行按钮会报错，但是直接提交是通过的
