### ISSUE TITLE
[BUG] - <35.搜索插入位置>--死循环通过

### ISSUE THREAD

**Issue by Sawwwww541** [LeetCode-Feedback/LeetCode-Feedback#25303]
### LeetCode 用户名

Saw.

### 问题号码、标题和链接

35.搜索插入位置 https://leetcode.cn/problems/search-insert-position/description/

### Bug Category

不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*

### 描述

# 我的代码写错了，但程序却说我通过。
### 你使用的语言

C++

### 你提交或者运行的代码

```bash
class Solution {
public:
    int searchInsert(vector<int>& nums, int target) {
        int left=0,right=nums.size()-1,count=0;
        int mid=left+(right-left)/2;
        while(left<=right){
            if(nums[mid]==target) return mid;
            else if(nums[mid]<target) left=mid+1;
            else right=mid-1;
        }
        if(left<=right) return (left+1);
        else if(target>nums[nums.size()-1]) return nums.size();
        else{
            while(nums[count]<target){
                count++;
            }
            return count;
        }
    }
};
```

### 期望行为

处理掉这个匪夷所思的bug，或者告诉我为什么这是合理的，而不是我所认为的bug，谢谢

### 屏幕截图

![微信截图_20241112111202](https://github.com/user-attachments/assets/17af70ea-54e9-4fd9-8fdc-0ccf6006b5c7)

**Comment by liyuzhu-lc** [comment]
感谢您的宝贵反馈，我们已经将您的反馈提交给我们的负责团队，并将会对相关信息进行核查，有新的进展及时再与您联系。感谢您的理解与支持。

**Comment by amcones-lc** [comment]
您好，在与相关团队核实后：***不处理***（用 clang 17 或者 19，并使用 O1 以上的优化等级编译时就能复现，改为用 gcc 就没有问题。我们不会因为这一个小问题就把编译器从 clang 改成 gcc，也不会修改优化等级）。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
