### ISSUE TITLE
Missing Test Case - LCR 136. 删除链表的节点

### ISSUE THREAD

**Issue by YBill** [LeetCode-Feedback/LeetCode-Feedback#25343]
### LeetCode 用户名

WBill

### 问题号码、标题和链接

136 删除链表的节点 https://leetcode.cn/problems/shan-chu-lian-biao-de-jie-dian-lcof/description/

### Bug Category

缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*

### 描述

我使用下面代码测试，运行得到一个通过，但是我的逻辑是有问题的，正确结果应该返回dynamic.next；比如我输入: head = [1], val = 1，运行后输出: [-1]，而预期应该是[].

### 你使用的语言

Java

### 你提交或者运行的代码

```bash
public ListNode deleteNode(ListNode head, int val) {
        ListNode dynamic = new ListNode(-1, head);
        ListNode prev = dynamic;
        while (prev.next != null) {
            if (prev.next.val == val) {
                ListNode curr = prev.next;
                prev.next = prev.next.next;
                curr.next = null;
                return prev;
            }
            prev = prev.next;
        }
        return null;
    }
```

### 期望行为

测试失败

### 屏幕截图

![1](https://github.com/user-attachments/assets/0f9f3023-681d-45b2-a4a1-54d36e2b48d9)

**Comment by liyuzhu-lc** [comment]
感谢您的宝贵反馈，我们已经将您的反馈提交给我们的负责团队，并将会对相关信息进行核查，有新的进展及时再与您联系。感谢您的理解与支持。

**Comment by amcones-lc** [comment]
您好，在与相关团队核实后：***不处理***。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
