### ISSUE TITLE
Missing Test Case - 14. Longest Common Prefix

### ISSUE THREAD

**Issue by LeHue369** [LeetCode-Feedback/LeetCode-Feedback#2535]
#### Your LeetCode username

####Missing Test Case
- [ ] Question
- [ ] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@LeHue369 Please provide more details to your content-related issue report. Thank you for your time.

**Comment by LeHue369** [comment]
Dear LeetCode,
        I'll elaborate on a missing test case that I've found. You can open
the Solution part of this problem called the longest common prefix. Next,
you go to "Approach 1: Horizontal scanning" to get the sample code. The
sample code is correct and 100% faster according to your test cases but it
allows a non-letter character to pass when the problem's condition is
'strs[i] consists of ONLY lower-case English letters.' When I input ","(a
comma), the result is ","(a comma) when it's supposed to be ""(blank);
I illustrate my test case by the two figures.
Figure 1 is to help you find the location of the sample test which has the
problem.
Figure 2 is to explain the test case that I think is missed.
I am looking for receiving your answer soon.
Best regards,
Hue
[image: 1.png]
[image: 2.png]


Vào Th 3, 2 thg 3, 2021 vào lúc 06:13 lc-kay <notifications@github.com>
đã viết:

**Comment by lc-kay** [comment]
@LeHue369 Can you please provide the test case in this format: ["dog","racecar","car"]? In addition, I am unable to view the attachments from your email.

**Comment by LeHue369** [comment]
Dear LeetCode,
The result of ["dog", "racecar", "car"] is "" .
I'm sorry about the inconvenience to see the figures. I send you links
below, then you can look through those figures by link 1, and I also give
you the LeetCode's sample code which has the missing case "" in Link 2;


Link 1:
https://docs.google.com/document/d/1uSSSEzLW60A1hWEM8vmJ5L4lN0iu3cNBEImCkyu8Dj0/edit?usp=sharing
Link 2: https://gist.github.com/LeHue369/9679b956cf5c36e365aec666c3875054

Best regards,
Hue

Vào Th 4, 3 thg 3, 2021 vào lúc 02:28 lc-kay <notifications@github.com>
đã viết:

**Comment by lc-kay** [comment]
@LeHue369 Thank you for providing that. Unfortunately, I am getting Compile Error for the code you provided. Can you please provide the submission details link to the accepted solution that fail on the test case [""]?

**Comment by LeHue369** [comment]
Dear LeetCode,
https://leetcode.com/problems/longest-common-prefix/solution/
you can see the code, which has the missing test case " , " by the link
above.
Best regards,
Hue

**Comment by lc-kay** [comment]
@LeHue369 The test case "," returns an invalid test case message: "'strs' must consist of values from a to z only". Therefore, this test case will not be accepted. Thank you for your time.

**Comment by LeHue369** [comment]
No no, I run the sample code and it returns ",", it allows ","  to be
a correct result when the condition of the problem forbids it and there is
no invalid test case message: "'strs' must consist of values from a to z
only".
Could you check for me again, please? I test the sample code very carefully
to find the missing test case and I want to have LeetCoin to buy a T-shirt.
It really takes my time.

Vào Th 7, 6 thg 3, 2021 vào lúc 03:28 lc-kay <notifications@github.com>
đã viết:

**Comment by lc-kay** [comment]
@LeHue369 To further look into this issue, please provide a screenshot of the entire LeetCode code editor where it shows the sample code is failing on your custom test case. Thanks!
