### ISSUE TITLE
Missing Test Case - 3249. Count the Number of Good Nodes

### ISSUE THREAD

**Issue by Huihao-Yang** [LeetCode-Feedback/LeetCode-Feedback#25358]
### LeetCode 用户名

https://leetcode.cn/u/haooozi/

### 问题号码、标题和链接

3249. 统计好节点的数目 https://leetcode.cn/problems/count-the-number-of-good-nodes

### Bug Category

缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*

### 描述

hack case as follows:
![image](https://github.com/user-attachments/assets/5c7a2bd8-ba47-4ae6-85de-9363f9780a0a)
result as follows:
![image](https://github.com/user-attachments/assets/52ca34bb-2f26-4a01-bbe3-0f6c715eaf39)

### 你使用的语言

Python/Python3

### 你提交或者运行的代码

```bash
class Solution:
    def countGoodNodes(self, edges: List[List[int]]) -> int:
        n = len(edges) + 1
        g = [[] for _ in range(n)]
        visited = [False for _ in range(n)]
        visited[0] = True
        for x, y in edges:
            if not visited[x] and visited[y]:
                g[y].append(x)
                visited[x] = True
            else:
                g[x].append(y)
                visited[x] = visited[y] = True

        ans = 0

        def dfs(x: int) -> int:
            size, sz0, ok = 1, 0, True
            for y in g[x]:
                sz = dfs(y)
                if sz0 == 0:
                    sz0 = sz  # 记录第一个儿子子树的大小
                elif sz != sz0:  # 存在大小不一样的儿子子树
                    ok = False  # 注意不能 break，其他子树 y 仍然要递归
                size += sz
            nonlocal ans
            ans += ok
            return size

        dfs(0)
        return ans
```

### 期望行为

完善测试用例，避免错误思路下的代码pass / make the test cases better

**Comment by liyuzhu-lc** [comment]
感谢您的宝贵反馈，我们已经将您的反馈提交给我们的负责团队，并将会对相关信息进行核查，有新的进展及时再与您联系。感谢您的理解与支持。

**Comment by amcones-lc** [comment]
We have received feedback, please wait for us to process
