### ISSUE TITLE
[BUG] - <3. 无重复字符的最长字串 测试用例输出错误>

### ISSUE THREAD

**Issue by sivvi** [LeetCode-Feedback/LeetCode-Feedback#25365]
### LeetCode 用户名

Flamboyant NobelxkP

### 问题号码、标题和链接

3. 无重复字符的最长子串 https://leetcode.cn/problems/longest-substring-without-repeating-characters/

### Bug Category

不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*

### 描述

语言：C++
输入："au"
本地或Leetcode调试输出：2，提交答案输出为：1,  测试用例为偶数的也会有同样的错误，但用例编号为奇数的没有这个问题

### 你使用的语言

C++

### 你提交或者运行的代码

```bash
class Solution {
public:
    int lengthOfLongestSubstring(string s) {
        int m, sLength, maxLength;
        char *p, *q, *r;
        char s1[50001];
        char s2[50001];
        char tempChar;
        sLength = s.length();
        maxLength = 0;
        strcpy(s1, s.c_str()); // S1 starting index
        m = 0;                 // S2 starting index
        if (sLength == 0) {
            return 0;
        }

        p = s1;
        r = s2;
        do {
            q = strchr(s2, *p);
            if (q != NULL) { // if found duplicated character from S2,
                memset(s2, 0, sizeof(s2)); // reset S2
                if (m > maxLength) {
                    maxLength = m;
                } // if current length > maxLength, update maxLength
                p = p - (r + m - q) + 1;
                m = 0; // reset m
            }
            s2[m] = *p; // push s1 into s2
            m = m + 1;
            p = p + 1;

        } while (*p != '\0');

        if (m > maxLength) { // last checking
            maxLength = m;
        }

        return maxLength;
    }
};
```

### 期望行为

修复此bug

### 屏幕截图

![image](https://github.com/user-attachments/assets/7b2af0de-c6d8-461a-ab1c-c4b472de9fec)
![image](https://github.com/user-attachments/assets/ab5304a7-44d5-4169-8c9d-07093fa9e439)

**Comment by liyuzhu-lc** [comment]
感谢您的宝贵反馈，我们已经将您的反馈提交给我们的负责团队，并将会对相关信息进行核查，有新的进展及时再与您联系。感谢您的理解与支持。

**Comment by amcones-lc** [comment]
感谢反馈，经核实该题目题解及测试用例暂无异常（当次测试用例会使用上次测试用例运行时在堆上分配的内存，需要在每次调用前重新初始化），力扣会不断努力给大家带来更好的学习社区！后续刷题学习中遇到问题，可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
