### ISSUE TITLE
[BUG] - 131 支持内容无序返回

### ISSUE THREAD

**Issue by Rorchal** [LeetCode-Feedback/LeetCode-Feedback#25360]
### LeetCode 用户名

Quirky Darvvin2SE

### 问题号码、标题和链接

131

### Bug Category

不正确或缺少“相关标签”

### 描述

我返回的不按照他的顺序  就运行不通过  
![image](https://github.com/user-attachments/assets/a22c3812-1bdb-4ed6-ba83-d1e968199907)

### 你使用的语言

Java

### 期望行为

返回最外层数组中的元素时 可以无序返回

**Comment by liyuzhu-lc** [comment]
感谢您的宝贵反馈，我们已经将您的反馈提交给我们的负责团队，并将会对相关信息进行核查，有新的进展及时再与您联系。感谢您的理解与支持。

**Comment by amcones-lc** [comment]
感谢反馈，经核实该题目题解及测试用例暂无异常（分割方案之间可以无序，但分割方案内的子串需要按照在原字符串中的位置），力扣会不断努力给大家带来更好的学习社区！后续刷题学习中遇到问题，可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
