### ISSUE TITLE
Missing Test Case - 3511. Find the Winning Player in Coin Game

### ISSUE THREAD

**Issue by OrgPoisson** [LeetCode-Feedback/LeetCode-Feedback#25378]
### LeetCode 用户名

OrgPoisson

### 问题号码、标题和链接

3511.求出硬币游戏的赢家 https://leetcode.cn/problems/find-the-winning-player-in-coin-game/description/?envType=problem-list-v2&envId=game-theory

### Bug Category

不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*

### 描述

```
发现了系统无法通过的测试用例
```

### 你使用的语言

C++

### 你提交或者运行的代码

```bash
class Solution {
public:
    string winningPlayer(int x, int y) {
        if(x % 2 != 0 && y > 4 * x) return "Alice";
        if(x % 2 == 0 && y > 4 * (x - 1) && y < 4 * x) return "Alice";
        return "Bob";
    }
};
```

### 期望行为

解决系统无法通过测试样例的问题

### 屏幕截图

![image](https://github.com/user-attachments/assets/791478f4-9458-44e1-bd26-205af68b9c1a)

### 额外的上下文

null

**Comment by liyuzhu-lc** [comment]
感谢您的宝贵反馈，我们已经将您的反馈提交给我们的负责团队，并将会对相关信息进行核查，有新的进展及时再与您联系。感谢您的理解与支持。

**Comment by amcones-lc** [comment]
感谢反馈，经核实该题目题解及测试用例暂无异常（代码模版有更新，现在可以正常运行用户代码），力扣会不断努力给大家带来更好的学习社区！后续刷题学习中遇到问题，可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
