### ISSUE TITLE
Missing Test Case - 1776. Car Fleet II

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#2538]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution is accepted but fails on the following test case:

[1777_tase_case.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6056985/1777_tase_case.txt)

#### Code you used for Submit/Run operation

```
class Solution {
    public double[] getCollisionTimes(int[][] cars) {

        int len = cars.length;
        double[] ans = new double[len];

        for (int i = 0; i < len; i++) {
            double tmp = -1.0;
            for (int j = i+1; j < len && j < i+600; j++) {
                if (cars[j][1] >= cars[i][1]) continue;
                double k = (cars[j][0]-cars[i][0])/(double)(cars[i][1]-cars[j][1]);
                if (Math.abs(tmp + 1.0) < 0.0001) {
                    tmp = k;
                } else {
                    tmp = Math.min(tmp,k);
                }
            }
            for (int j = len-1; j > i && j > len-100; j--) {
                if (cars[j][1] >= cars[i][1]) continue;
                double k = (cars[j][0]-cars[i][0])/(double)(cars[i][1]-cars[j][1]);
                if (Math.abs(tmp + 1.0) < 0.0001) {
                    tmp = k;
                } else {
                    tmp = Math.min(tmp,k);
                }
            }
            ans[i] = tmp;
        }
        return ans;
        


    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/109423074-22327500-79ac-11eb-9d05-19b9252e2776.png)

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
