### ISSUE TITLE
Missing Test Case - 1775. Equal Sum Arrays With Minimum Number of Operations

### ISSUE THREAD

**Issue by archit11111** [LeetCode-Feedback/LeetCode-Feedback#2539]
#### Your LeetCode username
archit91

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
A solution is accepted but fails(timeouts) on the following test case: 

[2]
[3]

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int minOperations(vector<int>& nums1, vector<int>& nums2) {
	    // not possible to equalize under following conditions
        if(6 * nums1.size() < 1 * nums2.size() || 6 * nums2.size() < 1 * nums1.size())
            return -1;
        int diff = 0, op = 0, j = 5;
        vector<int>arr(6);
        diff = accumulate(begin(nums1), end(nums1), 0) - accumulate(begin(nums2), end(nums2), 0);
        // if diff is positive, switch array bcoz numbers from first array will be used for subtracting and vice-versa
        if(diff > 0) swap(nums1, nums2);
        // arr stores frequency of numbers(1-5) that can be subtracted from diff to make it 0
        for(int &num : nums1) arr[6 - num]++;  
        for(int &num : nums2) arr[num - 1]++;        
        diff = abs(diff);
        
        while(diff > 0)
            if(arr[j]){
                op += min(arr[j], (int)ceil(1.0 * diff / j));
                diff -= arr[j] * j;
                if(diff <= 0)return op;
                j--;
            }
        return op;
    }
};
```

#### Language used for code
C++

#### Expected behavior
The solution should not be accepted as it timeouts and fails on the above-mentioned test case.

#### Screenshots
![leetcode-bug](https://user-images.githubusercontent.com/40712852/109428111-8a6c6f80-7a1b-11eb-8805-f0a7a7e88e2d.PNG)

#### Additional context

The above solution fails and timeouts for many other test cases as well. A pattern that all the failing test case follow is as below :

- The array having a lower sum does not contain `1` as its member element or,
- The array having a greater sum does not contain `6` as its member element

If none of the above two conditions is satisfied, then my solution timeouts. Adding test cases satisfying the above conditions will strengthen the test cases and discard my answer which is wrongfully accepted.

**Comment by lc-kay** [comment]
Hi @archit11111 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @archit11111 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
