### ISSUE TITLE
233. Number of Digit One

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#254]
**What kind of the bug**
- [ ] problem
- [x] solution
- [ ] language

**Describe the bug**

Iterate over ii from 11 to nn incrementing by 1010 each time:
Add (n/(i*10))*i(n/(i∗10))∗i to \text{countr}countr representing the repetition of groups of i$ sizes after each (i10)interval. + Addinterval.+Add{\min(\max(( ext{n mod (i10)} )-i+1,0),i)}toto ext{countr}representing the additional digits dependant on the digit inrepresentingtheadditionaldigitsdependantonthedigitinith place as described in intuition. <iframe src="https://leetcode.com/playground/QVzpgtNB/shared" frameBorder="0" name="QVzpgtNB" width="100%" height="207"></iframe> **Complexity analysis** * Time complexity:thplaceasdescribedinintuition.<iframesrc="https://leetcode.com/playground/QVzpgtNB/shared"frameBorder="0"name="QVzpgtNB"width="100∗∗Complexityanalysis∗∗∗Timecomplexity:O(log_{10}(n)). + No of iterations equal to the number of digits in n which is.+Noofiterationsequaltothenumberofdigitsinnwhichislog_{10}(n)* Space complexity:∗Spacecomplexity:O(1) space required.

This is text formatting in Approach 2 solution analysis and it is broken.

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
