### ISSUE TITLE
Missing Test Case - 3356. Zero Array Transformation II

### ISSUE THREAD

**Issue by yumkam** [LeetCode-Feedback/LeetCode-Feedback#25403]
### LeetCode Username

yumkam

### Problem Number, Title, and Link

3356. Zero Array Transformation II https://leetcode.com/problems/zero-array-transformation-ii/

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

Code was accepted, but fails (TLE) testcase generated with
```python3
#!/usr/bin/python3
n = int(1e5)
m = n
print ([0] * (n - 1) + [int(5e5)])
print([[1,3,2]]*m)
```
[link to complete testcase](https://gist.github.com/yumkam/b1705764675b461854dedf4eb293d710/raw/eb06a3e9d6e6091da11509e116286fab53008ec4/gistfile1.txt)

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
// code not mine, taken from
// https://leetcode.com/contest/weekly-contest-424/submissions/detail/1454905528/
class Solution {
public:
    int minZeroArray(vector<int>& nums, vector<vector<int>>& queries) {
        int n=nums.size();
        vector<int>v(n+1,0);
        int c=1;
        for(vector<int>temp: queries) {
            int l=temp[0];
            int r=temp[1];
            v[l]+=temp[2];
            v[r+1]-=temp[2];

                    int sum=0;
        int ans=1;
            int cc=0;
        for(int i=0;i<n;i++) {
            sum+=v[i];
                if(nums[i])cc=1;
            if(sum<nums[i]) {
                ans=0;
                break;
            }

        }
            if(cc==0)return 0;
            if(ans==1)return c;

            c++;
        }
        return -1;
    }
    
};
```

### Expected behavior

This code should be rejected with TLE

**Comment by hexawhale** [comment]
@leetcode If this test case is added, please ensure that `O(n + m log n)` solutions which use a Lazy Segment Tree continue to be accepted in Python. This is an `O(n + m log n)` solution, but it is close to the time limit in Python: https://leetcode.com/contest/weekly-contest-424/submissions/detail/1454825224/

With the addition of this proposed test case, the time limit for Python may need to be increased to ensure that Lazy Segment Tree solutions such as what I linked above continue to be accepted, given that these solutions have a reasonable time complexity.

**Comment by yumkam** [comment]
```
n=int(2e4)
m=int(1e5)
```
or
```
n=int(1e5)
m=int(2e4)
```
seems still TLE with above code. But lower values does not work.
