### ISSUE TITLE
Missing constraints in 453

### ISSUE THREAD

**Issue by snehasishroy** [LeetCode-Feedback/LeetCode-Feedback#2542]
#### Your LeetCode username
chrisgriffin

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Problem statement in https://leetcode.com/problems/minimum-moves-to-equal-array-elements/ does not specify the input constraints, without which it's very difficult to gauge what is the expected time complexity for this problem.

#### Expected behavior
Need to add input constraints in the problem to make expected time complexity clearer

**Comment by lc-kay** [comment]
Hi @snehasishroy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @snehasishroy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
