### ISSUE TITLE
Missing Test Case - 88. Merge Sorted Array

### ISSUE THREAD

**Issue by mikasamikodu** [LeetCode-Feedback/LeetCode-Feedback#25437]
### LeetCode 用户名

王传

### 问题号码、标题和链接

合并两个有序数组https://leetcode.cn/problems/merge-sorted-array/

### Bug Category

问题描述

### 描述

本地运行没问题，在网站运行有问题

### 你使用的语言

Java

### 期望行为

[1,2,3,4,5,6]

### 屏幕截图

![1731985544433](https://github.com/user-attachments/assets/ed6e06f3-5a0d-436a-8fcd-661f0ca57a82)

### 额外的上下文

1

**Comment by liyuzhu-lc** [comment]
感谢您的宝贵反馈，我们已经将您的反馈提交给我们的负责团队，并将会对相关信息进行核查，有新的进展及时再与您联系。感谢您的理解与支持。

**Comment by amcones-lc** [comment]
感谢反馈，经核实该题目题解及测试用例暂无异常（本题需要在 **原地** 修改输入数组，无需 **返回**，与本地测试情况不同，如果有其它问题请提供代码），力扣会不断努力给大家带来更好的学习社区！后续刷题学习中遇到问题，可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
