### ISSUE TITLE
Missing Test Case - 895. Maximum Frequency Stack

### ISSUE THREAD

**Issue by Odomontois** [LeetCode-Feedback/LeetCode-Feedback#2543]
#### Your LeetCode username
nizhnik

#### Category of the bug

- [ ] Question
- [x]  Solution
- [ ] Language

#### Description of the bug
While looking at "Accepted Solutions Runtime Distribution" for the rust language, I've found a "sample 40ms solution" which can't work on some tests, that could be missing. This solution clearly misses the point that the difference between the current max frequence and the next one can be more than one 

#### Missing test case
```
["FreqStack","push","push","push","push","pop","pop","pop","pop"]
[[],[5],[7],[7],[7],[],[],[],[], [], [], []]
````

#### Code you used for Submit/Run operation

```rust
use std::collections::HashMap;

struct FreqStack {
    freq: HashMap<i32, i32>,
    group: HashMap<i32, Vec<i32>>,
    max: i32,
}

impl FreqStack {
    fn new() -> Self {
        Self {
            freq: HashMap::new(),
            group: HashMap::new(),
            max: std::i32::MIN,
        }
    }

    fn push(&mut self, x: i32) {
        let f = self.freq.entry(x).or_insert(0);
        *f += 1;

        if *f > self.max {
            self.max = *f;
        }

        let entry = self.group.entry(*f).or_insert(Vec::new());
        entry.push(x);
    }

    fn pop(&mut self) -> i32 {
        let stack = self.group.entry(self.max).or_insert(Vec::new());
        let x = stack.pop().unwrap();
        let e = self.freq.entry(x).or_insert(0);
        *e -= 1;

        if stack.len() == 0 {
            self.max -= 1;
        }
        x
    }
}
```

#### Language used for code
Rust

#### Expected behavior
This solution is accepted, I assume, but it panics at supplied case

**Comment by Odomontois** [comment]
Seems, the official official python solution has the same incorrect assumption. Should be fixed ASAP

**Comment by lc-kay** [comment]
Hi @Odomontois 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Odomontois 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
