### ISSUE TITLE
Missing Test Case - 3243. Shortest Distance After Road Addition Queries I

### ISSUE THREAD

**Issue by ElliotZhangyc** [LeetCode-Feedback/LeetCode-Feedback#25442]
### LeetCode 用户名

mean_reversion

### 问题号码、标题和链接

3243. 新增道路查询后的最短距离https://leetcode.cn/problems/shortest-distance-after-road-addition-queries-i/description/

### Bug Category

缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*

### 描述

广度优先其实不适合这个问题，存在一些情况，没有找到最优解

### 你使用的语言

None

### 你提交或者运行的代码

```bash
n = 5
queries = [[0,2],[1,4]]
```

### 期望行为

输出应为[3,2]

**Comment by liyuzhu-lc** [comment]
感谢您的宝贵反馈，我们已经将您的反馈提交给我们的负责团队，并将会对相关信息进行核查，有新的进展及时再与您联系。感谢您的理解与支持。

**Comment by amcones-lc** [comment]
感谢反馈，能否向我们补充代码信息，把信息提供完整才能有助于快速验证和精准的定位，谢谢。
