### ISSUE TITLE
Missing Test Case - 3244. Shortest Distance After Road Addition Queries II

### ISSUE THREAD

**Issue by zxh20001117** [LeetCode-Feedback/LeetCode-Feedback#25449]
### LeetCode 用户名

流年不语殇浅夏灬   f4r1k1ller

### 问题号码、标题和链接

3244. 新增道路查询后的最短距离 II

### Bug Category

缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*

### 描述

测试用例中少考虑了一种情况： 同一个节点start，同时存在三个query将其作为起点，并且满足end3>end1>end2，例如[[1,4],[1,3],[1,7]]。leetcode官方解答的代码不能正确处理这个情况，但却可以成功跑通这个题目，证明题目的case中没有考虑上述情况。

### 你使用的语言

Python/Python3

### 你提交或者运行的代码

```bash
roads = [i + 1 for i in range(n)]
        res = []
        dist = n - 1
        for query in queries:
            k = roads[query[0]]
            roads[query[0]] = query[1]
            while k != -1 and k < query[1]:
                roads[k], k = -1, roads[k]
                dist -= 1
            res.append(dist)
        return res

"""
作者：力扣官方题解
链接：https://leetcode.cn/problems/shortest-distance-after-road-addition-queries-ii/solutions/2984427/xin-zeng-dao-lu-cha-xun-hou-de-zui-duan-1n4hq/
来源：力扣（LeetCode）
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。
"""
```

### 期望行为

对于测试用例：
n=8
queries=[[1,4],[1,3],[1,7]]
应返回结果：[5,5,2]

**Comment by liyuzhu-lc** [comment]
感谢您的宝贵反馈，我们已经将您的反馈提交给我们的负责团队，并将会对相关信息进行核查，有新的进展及时再与您联系。感谢您的理解与支持。

**Comment by amcones-lc** [comment]
We have received feedback, please wait for us to process
