### ISSUE TITLE
Missing Test Case - 1168. Duplicate Zeros

### ISSUE THREAD

**Issue by JoaoPBarros** [LeetCode-Feedback/LeetCode-Feedback#2546]
#### Category of the bug
- [DuplicateZeros ] Question
- [[1,0,0,2,3,0,0,4]] Solution
- [Javascript ] Language

#### Code you used for Submit/Run operation

```
const newArray = [];
	arr.forEach((number) => {
		if (number == 0) {
			newArray.push(number);    
			newArray.push(number);
		} else {
			newArray.push(number);
		}
	})
	newArray.forEach(() => newArray.length > arr.length ? newArray.pop() : null);
	arr = newArray;
```

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@JoaoPBarros Can you please provide the submission details link to your solution?

**Comment by lc-kay** [comment]
Hi @JoaoPBarros 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
