### ISSUE TITLE
Invalid Testcase Check - 895. Maximum Frequency Stack

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#2548]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

When I input an invalid test case, the run code result shows "Runtime Error" rather than "invalid testcase". This can be misleading.
["FreqStack","pop"]
[[],[]]

#### Code you used for Submit/Run operation

```
class FreqStack
{
public:
    unordered_map<int, int> freqMap;
    unordered_map<int, vector<int>> stackMap;
    int maxFreq = 0;
    
    FreqStack()
    {}
    
    void push(int x)
    {
        int freq = ++freqMap[x];
        stackMap[freq].push_back(x);
        maxFreq = max(maxFreq, freq);
    }
    
    int pop()
    {
        auto& stack = stackMap[maxFreq];

        int x = stack.back();
        stack.pop_back();
        
        --freqMap[x];
        if (stack.size() == 0)
            --maxFreq;
        
        return x;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Expected: The testcase validator detects that the input is invalid.
Reality: The run code result shows "Runtime Error". (And it crashed at somewhere outside my code.)

#### Screenshots

![1](https://user-images.githubusercontent.com/11583428/109586744-71bb9280-7acb-11eb-83de-9e7235b8107d.png)

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for your time. The team reviewed your report and updated the error message. We appreciate your support!
