### ISSUE TITLE
Profile Preview Collasping on Problem Page [Frontend]

### ISSUE THREAD

**Issue by snmath-pi** [LeetCode-Feedback/LeetCode-Feedback#25499]
### LeetCode Username

math_pi

### Problem Number, Title, and Link

https://leetcode.com/problems/rotating-the-box/description/?envType=daily-question&envId=2024-11-23

### Bug Category

Problem description

### Bug Description

This bug is not about a problem testcase, but how the profile pop up window collapses when previewed from the problem page, I am attaching a screenshot for your reference.

### Language Used for Code

None

### Expected behavior

Non collasping profile preview on problem page.

### Screenshots

![image](https://github.com/user-attachments/assets/f1197392-055a-4405-a4b6-45963d12ff2b)

### Additional context

This is frontend bug

**Comment by adhnannp** [comment]
I also came across this problem
![Capture](https://github.com/user-attachments/assets/ad3f3599-0932-4e40-8b97-6d97bb59f117)
