### ISSUE TITLE
Incorrect Solution - 894. All Possible Full Binary Trees

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#2549]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

The following code gets Accepted with the following test case, by creating an invalid tree:
Input: 3
(This code is only for illustration purpose, and won't get Accepted for the whole problem. But it's easy to adapt the idea and create a real Accepted code.)

#### Code you used for Submit/Run operation

```
/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
TreeNode *a[15];
class Solution {
public:
    vector<TreeNode*> allPossibleFBT(int N) {
        for (int i=0;i<10;++i)a[i]=new TreeNode();
        a[0]->left=a[1]; a[0]->right=a[1];
        return vector<TreeNode*>({a[0]});
    }
};
```

#### Language used for code

C++

#### Expected behavior

Expected: The code should get Wrong Answer, because it returns an invalid tree (left child and right child of the root point to the same node).
Reality: The code gets Accepted on input 3.

#### Screenshots

![1](https://user-images.githubusercontent.com/11583428/109587966-94e74180-7acd-11eb-8414-e0d420083e3d.png)

#### Additional context

To fix this issue, I believe the validator should check the distinctness of those returned TreeNodes (which might be complicated though).

**Comment by lc-kay** [comment]
@hqztrue Can you please include a code that is accepted on submission? Thank you!

**Comment by hqztrue** [comment]
Ok, let me modify it.

**Comment by hqztrue** [comment]
In the following code, all leaf nodes point to the same object.
```
TreeNode *leaf=new TreeNode(0);
class Solution {
public:
    vector<TreeNode*> allPossibleFBT(int N) {
        vector<TreeNode*> ans;
        if(N < 1 || N % 2 == 0)return ans;
        for(int k = 2; k < N; k += 2) {
            vector<TreeNode*> v1 = allPossibleFBT(k - 1);
            vector<TreeNode*> v2 = allPossibleFBT(N - k);
            int n1 = v1.size(), n2 = v2.size();
            for(int i = 0; i < n1; i++) {
                for(int j = 0; j < n2; j++) {
                    TreeNode* newRoot = new TreeNode(0);
                    newRoot->left = v1[i];
                    newRoot->right = v2[j];
                    ans.push_back(newRoot);
                }
            }
        }
        if(ans.empty())ans.push_back(leaf);
        return ans;
    }
};
```
![1](https://user-images.githubusercontent.com/11583428/109709716-6cf5ed80-7b62-11eb-8a47-df1d8eced254.png)

**Comment by lc-kay** [comment]
Hi @hqztrue 
 I've relayed this issue to our team to investigate.
