### ISSUE TITLE
 Missing Test Case: Number Complement - May LeetCoding Challenge

### ISSUE THREAD

**Issue by ilyas409** [LeetCode-Feedback/LeetCode-Feedback#255]
**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
Bug in [https://leetcode.com/explore/featured/card/may-leetcoding-challenge/534/week-1-may-1st-may-7th/3319/](https://leetcode.com/explore/featured/card/may-leetcoding-challenge/534/week-1-may-1st-may-7th/3319/)

Even though my code doesn't cover the case of `Solution().findComplement(0)`, my submission still passes.
Missing test case: 0

**what language is your code written in**
C++

**The code you submit/run**
```
// Number Complement

class Solution {
public:
    int findComplement(int num) {
        int n = num;
        int mask = 1;
        while (num) {
            num = num >> 1;
            n ^= mask;
            mask = mask << 1;
        }
        return n;
    }
};
```

**Expected behavior**
My submission should fail because I don't check if `num` is `0`.

**Screenshots**
<img width="769" alt="Screen Shot 2020-05-04 at 6 51 41 PM" src="https://user-images.githubusercontent.com/22550273/81029002-4d097680-8e38-11ea-8fd5-91e5b8d402ad.png">

**Additional context**

**Comment by CooperCooperCooper** [comment]
Hi @ilyas409 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @ilyas409 ,
Thank you for your time. Upon reviewing the submitted information, we found you're missing an important part of the statement "Given a positive integer". Please update your code accordingly. We appreciate your support.
