### ISSUE TITLE
2 Different output for Same Code - 895. Maximum Frequency Stack

### ISSUE THREAD

**Issue by sachinsinghjagawat** [LeetCode-Feedback/LeetCode-Feedback#2550]
#### Your LeetCode username
charan_is_king

#### Category of the bug
- [ ] Question :- 895. Maximum Frequency Stack
- [ ] Language :- Python 3

#### Description of the bug
I am getting two different outputs for the same code on the same test case. ( output on submitting the code and running on the same test case are different )

#### Code you used for Submit/Run operation

```
class FreqStack:
    st = []
    d = {}
    f = {}
    
    j = -1
    def _init_(self):
        st = []
        d = {}
        f = {}
        j = -1
    def push(self, x: int) -> None:
        self.j+=1
        if(x not in self.d):
            self.d[x] = [self.j]
            self.f[x] = 1
        else:
            self.d[x].append(self.j)
            self.f[x]+=1

    def pop(self) -> int:
        me = -1
        # print(self.f)
        # print(self.d)
        for i in self.f:
            if(me == -1):
                me = i
                continue
            if(self.f[i] > self.f[me]):
                me = i
            elif(self.f[i] == self.f[me]):
                if(self.d[i][-1] > self.d[me][-1]):
                    me = i
        
        self.f[me]-=1
        self.d[me].pop(-1)
        
        return me
        


# Your FreqStack object will be instantiated and called as such:
# obj = FreqStack()
# obj.push(x)
# param_2 = obj.pop()
```

#### Language used for code
Python 3

#### Expected behavior

It should show the same result for submitting and running the code on LeetCode.

#### Screenshots

![ss2](https://user-images.githubusercontent.com/63307079/109588012-0c4cbd80-7b2e-11eb-8f99-0e66a9c5eb2c.jpeg)
![ss1](https://user-images.githubusercontent.com/63307079/109588014-0e168100-7b2e-11eb-843a-b9a81c32e3a2.jpeg)

You can clearly see that I am getting two different outputs for the same code on the same test case. 

#### Additional context

I am getting wrong ans when I submit. But when I copy that test case and then run the code then I am getting correct ans. I don't know whats the problem with the internal working of your code.

**Comment by lc-kay** [comment]
Hi @sachinsinghjagawat 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
