### ISSUE TITLE
Missing Test Case - 1975. Maximum Matrix Sum

### ISSUE THREAD

**Issue by Vandit-Kalathiya** [LeetCode-Feedback/LeetCode-Feedback#25517]
### LeetCode Username

Vandit-Kalathiya

### Problem Number, Title, and Link

https://leetcode.com/problems/maximum-matrix-sum/?envType=daily-question&envId=2024-11-24

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

If the array is [[ 1,-2 ], [ 3,1 ] then output should be 6. because if we first multiply first row with -1 then it becomes [ -1, 2 ] so now if we find the sum then it is 6 which is greater than 5 in test case answer. 

### Language Used for Code

Java

### Expected behavior

If the array is [[ 1,-2 ], [ 3,1 ] then output should be 6. because if we first multiply first row with -1 then it becomes [ -1, 2 ] so now if we find the sum then it is 6 which is greater than 5 in test case answer. 
So the output should be the 6 instead of 5 in this case.

**Comment by bramar2** [comment]
Bro `-1 + 2 + 3 + 1 = 5`

**Comment by Vandit-Kalathiya** [comment]
Okay thanks
