### ISSUE TITLE
Incorrect Test Case - 1477. Find Two Non-overlapping Sub-arrays Each With Target Sum

### ISSUE THREAD

**Issue by scristescu** [LeetCode-Feedback/LeetCode-Feedback#25516]
### LeetCode Username

scristescu

### Problem Number, Title, and Link

1477,  Find Two Non-overlapping Sub-arrays Each With Target Sum, https://leetcode.com/problems/find-two-non-overlapping-sub-arrays-each-with-target-sum/description/

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

This is correct test-case, not wrong answer ... 1+6 = 7 = 6+1 ... we have 2 sub-arrays starting from index 0 and 1, with the length 2, Therefore the result = 2 * 2 = 4, not -1.

### Language Used for Code

Java

### Code used for Submit/Run operation

```bash
public int minSumOfLengths(int[] arr, int target) {
        Map<Integer, Integer> lengths = new TreeMap<>();

        for (int i = 0; i < arr.length; i++) {
            int sum = 0;
            for (int j = i; j < arr.length; j++) {
                sum += arr[j];
                if (sum == target) {
                    int len = j - i + 1;

                    Integer count = lengths.get(len);
                    if (count == null) {
                        lengths.put(len, 1);
                    } else {
                        lengths.put(len, count + 1);
                    }
                    break;
                }
            }
        }

        if (!lengths.isEmpty()) {
            int len = 0;
            int i = 0;
            for (int l : lengths.keySet()) {
                if (len == 0) {
                    int lens = lengths.get(l);
                    if (lens > 1) {
                        return 2 * l;
                    }
                }

                len += l;

                i++;
                if (i == 2) {
                    return len;
                }
            }
        }
        return -1;
    }
```

### Expected behavior

result = 4

### Screenshots

![image](https://github.com/user-attachments/assets/27859feb-795d-4492-b667-d9824ee685a0)

**Comment by scristescu** [comment]
Thank you for clarification ... you're right.

**Comment by Siddharth854** [comment]
`
class Solution {
  public int minSumOfLengths(int[] arr, int target) {
    int ans = Integer.MAX_VALUE;
    int leftLength = Integer.MAX_VALUE;
    int prefix = 0;
    Map<Integer, Integer> prefixToIndex = new HashMap<>();
    prefixToIndex.put(0, -1);

    for (int i = 0; i < arr.length; ++i) {
      prefix += arr[i];
      prefixToIndex.put(prefix, i);
    }

    prefix = 0;

    for (int i = 0; i < arr.length; ++i) {
      prefix += arr[i];
      if (prefixToIndex.containsKey(prefix - target))
        leftLength = Math.min(leftLength, i - prefixToIndex.get(prefix - target));
      if (leftLength < Integer.MAX_VALUE)
        if (prefixToIndex.containsKey(prefix + target))
          ans = Math.min(ans, leftLength + prefixToIndex.get(prefix + target) - i);
    }

    return ans == Integer.MAX_VALUE ? -1 : ans;
  }
}
`
