### ISSUE TITLE
Missing Test Case - 100161. Compress String LCCI

### ISSUE THREAD

**Issue by songyi-zhou** [LeetCode-Feedback/LeetCode-Feedback#25548]
### LeetCode 用户名

busy-tharphvn

### 问题号码、标题和链接

面试题 01.06. 字符串压缩https://leetcode.cn/problems/compress-string-lcci/description/

### Bug Category

问题描述, 问题提示

### 描述

你发现了系统无法通过的测试用例，现在就去[提交](https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/new?assignees=&labels=&template=bug-report-chinese.yml&title=Missing%20Test%20Case%20-%20100161.%20Compress%20String%20LCCI&username=busy-tharphvn&code=%5Btype%20the%20code%5D&bug-description=%60%60%60%0Aaabcccccaaa%0A%60%60%60)此用例，帮助我们改进
本地IDE成功，线上提交失败，显示上述问题

### 你使用的语言

JavaScript

### 你提交或者运行的代码

```bash
/**
 * @param {string} S
 * @return {string}
 */
var compressString = function(S) {
    let s = new Set();
    let arr = new Array(S.length);
    for (let i = 0; i < S.length; i++) {
        arr[i] = 0;
        }
    let pos=-1
    let res="";
    for(let i = 0; i<S.length; i++){
        if (!s.has(S[i])){
            pos++;
            s.clear();
            s.add(S[i]);
            arr[pos]=arr[pos]+1;
            // res = res+S[i]+arr[pos]
        }else{
            arr [pos]++;
        }
    }
    s.clear();
    pos=0;
    for(let i = 0; i<arr.length; i++){
        if (!s.has(S[i])){
            s.clear();
            s.add(S[i]);
            res = res+S[i]+arr[pos];
            pos++;
        }
    }
    return res;
}
```

### 期望行为

输出a2b1c5a3

### 屏幕截图

![屏幕截图 2024-11-26 182341](https://github.com/user-attachments/assets/65a3fe99-0858-411b-accf-b81b6fe330c5)

**Comment by songyi-zhou** [comment]
"aabcccccaaa"
缺少引号就会提示错误
力扣官方没给出测试用例，需要手动输入

**Comment by liyuzhu-lc** [comment]
感谢您的宝贵反馈，我们已经将您的反馈提交给我们的负责团队，并将会对相关信息进行核查，有新的进展及时再与您联系。感谢您的理解与支持。

**Comment by amcones-lc** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by songyi-zhou** [comment]
leetcode.cn/u/busy-tharphvn/

**Comment by amcones-lc** [comment]
你好，当前该题已添加测试用例，奖励已发放。
