### ISSUE TITLE
In 341. Flatten Nested List Iterator, comments of JAVA code is incorrect.

### ISSUE THREAD

**Issue by jiayibing1987** [LeetCode-Feedback/LeetCode-Feedback#2555]
#### Category of the bug
- [Y ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

 In 341. Flatten Nested List Iterator, in the comments of JAVA code: 
// Return null if this NestedInteger holds a single integer
public List<NestedInteger> getList();. 
However, it returns an empty list but not null.

#### Code you used for Submit/Run operation

```
// run this code under the default test case
    public NestedIterator(List<NestedInteger> nestedList) {
        dq = new ArrayDeque<>();
        for (NestedInteger n : nestedList) {
            System.out.println(n.getList().size());
            System.out.println(n.isInteger());
            add(n);
        }
    }
```

#### Language used for code

JAVA

#### Expected behavior

change the comment to "it returns an empty list when this NestedInteger holds a single integer"

#### Screenshots

![image](https://user-images.githubusercontent.com/53039739/109619248-45178180-7b84-11eb-94e3-6e7d76d8de27.png)

**Comment by lc-kay** [comment]
Hi @jiayibing1987 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@jiayibing1987 Our team has reviewed the problem and noted that this issue was fixed a while back. Please reset the default code definition to see the latest changes. Thank you for your time!
