### ISSUE TITLE
Missing Test Case - 100340. 把字符串转换成整数 (atoi)

### ISSUE THREAD

**Issue by Rina8475** [LeetCode-Feedback/LeetCode-Feedback#25567]
### LeetCode 用户名

rinayui

### 问题号码、标题和链接

LCR 192. 把字符串转换成整数 (atoi) https://leetcode.cn/problems/ba-zi-fu-chuan-zhuan-huan-cheng-zheng-shu-lcof/description/?envType=study-plan-v2&envId=coding-interviews

### Bug Category

不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*

### 描述

```

"-91283472332"
```

### 你使用的语言

Java

### 你提交或者运行的代码

```java
class Solution {
    public int myAtoi(String str) {
        char[] chars = str.toCharArray();
        int i = 0;
        char c;
        boolean isPositive = true;
        long res = 0;
        for (; chars[i] == ' '; i += 1);
        if ((c = chars[i]) == '+' || c == '-') {
            isPositive = (c == '+');
            i += 1;
        }
        for (; i < chars.length && Character.isDigit((c = chars[i])); i += 1)
            res = res * 10 + (long) (c - '0');
        return isPositive ? (int) (res > Integer.MAX_VALUE ? Integer.MAX_VALUE : res) : 
                (int) (-res < Integer.MIN_VALUE ? Integer.MIN_VALUE : -res);
    }
}
```

### 期望行为

-2147483648

### 屏幕截图

![Snipaste_2024-11-27_21-38-32](https://github.com/user-attachments/assets/632f9188-9315-4a44-afde-71d3301022b7)

**Comment by Rina8475** [comment]
### 你提交或者运行的代码
class Solution {
    public int myAtoi(String str) {
        char[] chars = str.toCharArray();
        int i = 0;
        char c;
        boolean isPositive = true;
        long res = 0;
        for (; chars[i] == ' '; i += 1);
        if ((c = chars[i]) == '+' || c == '-') {
            isPositive = (c == '+');
            i += 1;
        }
        for (; i < chars.length && Character.isDigit((c = chars[i])); i += 1)
            res = res * 10 + (long) (c - '0');
        return isPositive ? (int) (res > Integer.MAX_VALUE ? Integer.MAX_VALUE : res) : 
                (int) (-res < Integer.MIN_VALUE ? Integer.MIN_VALUE : -res);
    }
}

**Comment by liyuzhu-lc** [comment]
感谢您的宝贵反馈，我们已经将您的反馈提交给我们的负责团队，并将会对相关信息进行核查，有新的进展及时再与您联系。感谢您的理解与支持。

**Comment by amcones-lc** [comment]
感谢反馈，经核实该题目题解及测试用例暂无异常，力扣会不断努力给大家带来更好的学习社区！后续刷题学习中遇到问题，可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
