### ISSUE TITLE
缺乏默认测试样例 - 1000012. Sorted Merge LCCI

### ISSUE THREAD

**Issue by qinghuan02** [LeetCode-Feedback/LeetCode-Feedback#25568]
### LeetCode 用户名

qing-huan-f5

### 问题号码、标题和链接

面试题 10.01. 合并排序的数组 https://leetcode.cn/problems/sorted-merge-lcci/

### Bug Category

缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*

### 描述

1. 题目缺乏默认测试样例

2. 似乎这一套题目中许多题都缺乏默认的测试样例，需要手动添加https://leetcode.cn/studyplan/cracking-the-coding-interview/

### 你使用的语言

Java

### 屏幕截图
![{7E0D3E4F-2573-4AEC-BA83-CB2A8B7D7801}](https://github.com/user-attachments/assets/2f46241f-a45b-4257-8ece-0aef2ce54fdd)

### 额外的上下文

同一套题库中同样出现没有默认测试样例的题目
[面试题 01.05. 一次编辑](https://leetcode.cn/problems/one-away-lcci/)
[面试题 01.06. 字符串压缩](https://leetcode.cn/problems/compress-string-lcci/)
[面试题 01.07. 旋转矩阵](https://leetcode.cn/problems/rotate-matrix-lcci/)
[面试题 01.09. 字符串轮转](https://leetcode.cn/problems/string-rotation-lcci/)
[面试题 02.01. 移除重复节点](https://leetcode.cn/problems/remove-duplicate-node-lcci/)
[面试题 03.01. 三合一](https://leetcode.cn/problems/three-in-one-lcci/)
[面试题 03.03. 堆盘子](https://leetcode.cn/problems/stack-of-plates-lcci/)
[面试题 03.05. 栈排序](https://leetcode.cn/problems/sort-of-stacks-lcci/)
[面试题 03.06. 动物收容所](https://leetcode.cn/problems/animal-shelter-lcci/)
[面试题 04.01. 节点间通路](https://leetcode.cn/problems/route-between-nodes-lcci/)
[面试题 04.02. 最小高度树](https://leetcode.cn/problems/minimum-height-tree-lcci/)
[面试题 04.04. 检查平衡性](https://leetcode.cn/problems/check-balance-lcci/)
[面试题 04.05. 合法二叉搜索树](https://leetcode.cn/problems/legal-binary-search-tree-lcci/)
[面试题 04.06. 后继者](https://leetcode.cn/problems/successor-lcci/)
[面试题 04.08. 首个共同祖先](https://leetcode.cn/problems/first-common-ancestor-lcci/)
[面试题 04.09. 二叉搜索树序列](https://leetcode.cn/problems/bst-sequences-lcci/)
[面试题 04.10. 检查子树](https://leetcode.cn/problems/check-subtree-lcci/)
[面试题 04.12. 求和路径](https://leetcode.cn/problems/paths-with-sum-lcci/)
[面试题 05.01. 插入](https://leetcode.cn/problems/insert-into-bits-lcci/)
[面试题 05.02. 二进制数转字符串](https://leetcode.cn/problems/binary-number-to-string-lcci/)
[面试题 05.04. 下一个数](https://leetcode.cn/problems/closed-number-lcci/)
[面试题 05.06. 整数转换](https://leetcode.cn/problems/convert-integer-lcci/)
[面试题 05.07. 配对交换](https://leetcode.cn/problems/exchange-lcci/)
[面试题 05.08. 绘制直线](https://leetcode.cn/problems/draw-line-lcci/)
[面试题 08.01. 三步问题](https://leetcode.cn/problems/three-steps-problem-lcci/)
[面试题 08.02. 迷路的机器人](https://leetcode.cn/problems/robot-in-a-grid-lcci/)
[面试题 08.03. 魔术索引](https://leetcode.cn/problems/magic-index-lcci/)
[面试题 08.04. 幂集](https://leetcode.cn/problems/power-set-lcci/)
[面试题 08.05. 递归乘法](https://leetcode.cn/problems/recursive-mulitply-lcci/)
[面试题 08.06. 汉诺塔问题](https://leetcode.cn/problems/hanota-lcci/)
[面试题 08.07. 无重复字符串的排列组合](https://leetcode.cn/problems/permutation-i-lcci/)
[面试题 08.08. 有重复字符串的排列组合](https://leetcode.cn/problems/permutation-ii-lcci/)
[面试题 08.09. 括号](https://leetcode.cn/problems/bracket-lcci/)
[面试题 08.11. 硬币](https://leetcode.cn/problems/coin-lcci/)
[面试题 08.12. 八皇后](https://leetcode.cn/problems/eight-queens-lcci/)
[面试题 08.13. 堆箱子](https://leetcode.cn/problems/pile-box-lcci/)
[面试题 08.14. 布尔运算](https://leetcode.cn/problems/boolean-evaluation-lcci/)
[面试题 10.01. 合并排序的数组](https://leetcode.cn/problems/sorted-merge-lcci/)
[面试题 10.02. 变位词组](https://leetcode.cn/problems/group-anagrams-lcci/)
[面试题 10.03. 搜索旋转数组](https://leetcode.cn/problems/search-rotate-array-lcci/)
[面试题 10.05. 稀疏数组搜索](https://leetcode.cn/problems/sparse-array-search-lcci/)
[面试题 10.09. 排序矩阵查找](https://leetcode.cn/problems/sorted-matrix-search-lcci/)
[面试题 10.10. 数字流的秩](https://leetcode.cn/problems/rank-from-stream-lcci/)
[面试题 10.11. 峰与谷](https://leetcode.cn/problems/peaks-and-valleys-lcci/)
[面试题 16.05. 阶乘尾数](https://leetcode.cn/problems/factorial-zeros-lcci/)
[面试题 16.08. 整数的英语表示](https://leetcode.cn/problems/english-int-lcci/)
[面试题 16.11. 跳水板](https://leetcode.cn/problems/diving-board-lcci/)
[面试题 16.20. T9键盘](https://leetcode.cn/problems/t9-lcci/)
[面试题 16.21. 交换和](https://leetcode.cn/problems/sum-swap-lcci/)
[面试题 16.22. 兰顿蚂蚁](https://leetcode.cn/problems/langtons-ant-lcci/)
[面试题 16.24. 数对和](https://leetcode.cn/problems/pairs-with-sum-lcci/)
[面试题 16.25. LRU 缓存](https://leetcode.cn/problems/lru-cache-lcci/)
[面试题 16.26. 计算器](https://leetcode.cn/problems/calculator-lcci/)
[面试题 17.01. 不用加号的加法](https://leetcode.cn/problems/add-without-plus-lcci/)
[面试题 17.05. 字母与数字](https://leetcode.cn/problems/find-longest-subarray-lcci/)
[面试题 17.06. 2出现的次数](https://leetcode.cn/problems/number-of-2s-in-range-lcci/)
[面试题 17.09. 第 k 个数](https://leetcode.cn/problems/get-kth-magic-number-lcci/)
[面试题 17.18. 最短超串](https://leetcode.cn/problems/shortest-supersequence-lcci/)
[面试题 17.19. 消失的两个数字](https://leetcode.cn/problems/missing-two-lcci/)
[面试题 17.21. 直方图的水量](https://leetcode.cn/problems/volume-of-histogram-lcci/)
[面试题 17.22. 单词转换](https://leetcode.cn/problems/word-transformer-lcci/)
[面试题 17.23. 最大黑方阵](https://leetcode.cn/problems/max-black-square-lcci/)
[面试题 17.25. 单词矩阵](https://leetcode.cn/problems/word-rectangle-lcci/)
[面试题 17.26. 稀疏相似度](https://leetcode.cn/problems/sparse-similarity-lcci/)

**Comment by liyuzhu-lc** [comment]
感谢您的宝贵反馈，我们已经将您的反馈提交给我们的负责团队，并将会对相关信息进行核查，有新的进展及时再与您联系。感谢您的理解与支持。

**Comment by amcones-lc** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by qinghuan02** [comment]
你好，个性域名如下：
leetcode.cn/u/qing-huan-f5/

**Comment by amcones-lc** [comment]
你好，当前题目已更新，奖励已发放。
