### ISSUE TITLE
help

### ISSUE THREAD

**Issue by hucuanbin** [LeetCode-Feedback/LeetCode-Feedback#2556]
12

**Comment by hucuanbin** [comment]
理解出错

**Comment by hucuanbin** [comment]
请问

**Comment by hucuanbin** [comment]
是我理解错误

**Comment by lc-kay** [comment]
@hucuanbin Please provide a more detailed report on the content-related issue you are trying to report, such as the problem title, the code you used, the actual and expected behavior.

**Comment by lc-kay** [comment]
Hi @hucuanbin 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
