### ISSUE TITLE
Missing Test Case - 136. Single Number

### ISSUE THREAD

**Issue by sak192** [LeetCode-Feedback/LeetCode-Feedback#2557]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@sak192 Please provide the code and the missing test case. Thank you!

**Comment by lc-kay** [comment]
Hi @sak192 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
