### ISSUE TITLE
912.排序数组官方解答的归并排序代码有误

### ISSUE THREAD

**Issue by rookiezq** [LeetCode-Feedback/LeetCode-Feedback#2559]
**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名 
anti_996
**Bug 类型**
- [ ] 题目
- [x] 题解
- [ ] 编程语言

**描述**
912.排序数组官方解答的归并排序里的
```c++
if (nums[i] < nums[j]) {
 tmp[cnt++] = nums[i++]
 }
```
判断nums[i] 和 nums[j]大小，应该是<=吧，否则就是不稳定排序了啊。 比如从小到大 1234和1357合并，如果是<的话，左1不满足，即右1拿出来，这样次序不就颠倒了吗

**你使用的语言**
C++

**你提交或者运行的代码**
无

**期望行为**
无

**屏幕截图**
![image](https://user-images.githubusercontent.com/43901891/109673878-69d61e00-7bb1-11eb-8949-2ffbf09b2658.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
@rookiezq 你好，当前题解已更新，ID：demon1q 给予积分奖励，请查收。
