### ISSUE TITLE
Missing Test Case - 1000215. 采购方案

### ISSUE THREAD

**Issue by shiyihua123** [LeetCode-Feedback/LeetCode-Feedback#25593]
### LeetCode 用户名

i3lissful-7iskovqoh

### 问题号码、标题和链接

LCP 28. 采购方案 https://leetcode.cn/problems/4xy4Wx/description/?envType=problem-list-v2&envId=array&difficulty=EASY&status=TO_DO

### Bug Category

示例

### 描述

```
[2,5,3,5]
6
[2,2,1,9]
10
[2,2,1,9,3,9.9]
10
```

### 你使用的语言

None

### 你提交或者运行的代码

```bash
[type the code]
```

### 期望行为

9

**Comment by liyuzhu-lc** [comment]
感谢您的宝贵反馈，我们已经将您的反馈提交给我们的负责团队，并将会对相关信息进行核查，有新的进展及时再与您联系。感谢您的理解与支持。

**Comment by amcones-lc** [comment]
感谢反馈，经核实该题目题解及测试用例暂无异常，力扣会不断努力给大家带来更好的学习社区！后续刷题学习中遇到问题，可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
