### ISSUE TITLE
[BUG] - One of test cases is invalid

### ISSUE THREAD

**Issue by wanke1997** [LeetCode-Feedback/LeetCode-Feedback#25604]
### LeetCode Username

Pluto1120

### Problem Number, Title, and Link

635. Design Log Storage System https://leetcode.com/problems/design-log-storage-system/

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

the problem states that "You are given several logs, where each log contains a `unique ID` and timestamp". Note that all IDs are unique. However, One of the test cases looks like this. For different logs, it shares the same ID, which should be an invalid test case. 
["LogSystem","put","put","retrieve","retrieve", "retrieve"]
[[],[1,"2017:01:01:00:00:00"],[1,"2015:01:01:00:00:00"],["2015:01:01:00:00:00","2017:01:01:01:00:00","Year"],["2015:01:01:00:00:00","2015:01:01:00:00:01","Year"], ["2017:01:01:00:00:00","2017:01:01:00:00:01","Year"]]

### Language Used for Code

Python3

### Code used for Submit/Run operation

```bash
class LogSystem:

    def __init__(self):
        self.m = {}
        self.keyword = {"Year": 0, "Month": 1, "Day": 2, "Hour": 3, "Minute": 4, "Second": 5}
        self.min_val = {1: "01", 2: "01", 3: "00", 4: "00", 5: "00"}
        self.max_val = {1: "12", 2: "31", 3: "23", 4: "59", 5: "59"}
        

    def put(self, id: int, timestamp: str) -> None:
        self.m[id] = timestamp
        
        

    def retrieve(self, start: str, end: str, granularity: str) -> List[int]:
        start_str = start.split(":")
        end_str = end.split(":")
        last_idx = self.keyword[granularity]
        ss = []
        ee = []
        for i in range(last_idx+1):
            ss.append(start_str[i])
            ee.append(end_str[i])
        for i in range(last_idx+1, 6):
            ss.append(self.min_val[i])
            ee.append(self.max_val[i])
        start_modify = ":".join(ss)
        end_modify = ":".join(ee)
        
        # print(start_modify)
        # print(end_modify)
        res = []
        for idd, ts in self.m.items():
            if start_modify <= ts <= end_modify:
                res.append(idd)
        
        return res
        
        


# Your LogSystem object will be instantiated and called as such:
# obj = LogSystem()
# obj.put(id,timestamp)
# param_2 = obj.retrieve(start,end,granularity)
```

### Expected behavior

The test case below should be "Invalid Test Case", rather than give me a "Wrong Answer"

["LogSystem","put","put","retrieve","retrieve", "retrieve"]
[[],[1,"2017:01:01:00:00:00"],[1,"2015:01:01:00:00:00"],["2015:01:01:00:00:00","2017:01:01:01:00:00","Year"],["2015:01:01:00:00:00","2015:01:01:00:00:01","Year"], ["2017:01:01:00:00:00","2017:01:01:00:00:01","Year"]]

### Screenshots

<img width="1287" alt="Screenshot 2024-11-29 at 15 12 52" src="https://github.com/user-attachments/assets/63316145-70e7-4828-b259-fab7fe60235e">

**Comment by MANOJRAJPUT2065** [comment]
[1.pdf](https://github.com/user-attachments/files/17966052/1.pdf)
