### ISSUE TITLE
Missing Testcase in 371. Sum of Two Integers

### ISSUE THREAD

**Issue by Swapnil-2001** [LeetCode-Feedback/LeetCode-Feedback#2560]
#### Your LeetCode username
Swap24

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
A faulty Python solution passes all test cases

#### Code you used for Submit/Run operation

```
class Solution:
    def getSum(self, a: int, b: int) -> int:
        xor, carry = a ^ b, 0
        mask = 0xFFFFFFFF
        for i in range(32):
            if carry == 1:
                xor ^= 1 << i
                if not (a >> i) & 1 and not (b >> i) & 1:
                    carry = 0
            else:
                if not (xor >> i) & 1 and (a >> i) & 1:
                    carry = 1
        return xor if a >= 0 else ~(xor ^ mask)
```

#### Language used for code
Python 3

#### Expected behavior
The solution should not have passed testcases where the first integer is positive but the second integer is negative.

#### Screenshots

![Sum of Two Integers - LeetCode - Google Chrome 02-03-2021 22_20_22](https://user-images.githubusercontent.com/53232360/109683733-a3a12780-7ba5-11eb-99d0-eb8bd34c2aa7.png)

**Comment by lc-kay** [comment]
Hi @Swapnil-2001 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Swapnil-2001 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
