### ISSUE TITLE
Missing Test Case - 15. 3Sum

### ISSUE THREAD

**Issue by rahulray30** [LeetCode-Feedback/LeetCode-Feedback#2561]
#### Your LeetCode username

rahul_ray30

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

-1 is used 3 times in the output of the first sample input whereas only twice -1 is used in the sample input, so how it can be unique triplets

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@rahulray30 Please raise this question in the discuss section of the problem. In addition, you can find user's explanations on various test cases to understand the problem better. Thank you for your time!
