### ISSUE TITLE
Typo in Question Description - 541. Reverse String II

### ISSUE THREAD

**Issue by alexdanilowicz** [LeetCode-Feedback/LeetCode-Feedback#2563]
#### Your LeetCode username

alexdannylow

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

I believe there's a typo. Leetcode is missing a "be" in the last sentence. See below

#### Code you used for Submit/Run operation

```
N/A
```

#### Language used for code

N/A

#### Expected behavior

Restrictions:
- The string consists of lower English letters only.
- Length of the given string and k will **be** in the range [1, 10000]

#### Screenshots

<img width="542" alt="Screen Shot 2021-03-02 at 9 37 00 PM" src="https://user-images.githubusercontent.com/29822597/109757839-6f2a6d00-7b9f-11eb-94fe-da44edb4d6b2.png">

#### Additional context

Thanks! 👋🏼

**Comment by lc-kay** [comment]
Hi @alexdanilowicz 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @alexdanilowicz 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
