### ISSUE TITLE
Runtime Too Strict, Weekly Contest 426 Q3

### ISSUE THREAD

**Issue by jackpalaia** [LeetCode-Feedback/LeetCode-Feedback#25630]
### LeetCode Username

jackpalaia

### Problem Number, Title, and Link

3372. Maximize the Number of Target Nodes After Connecting Trees I https://leetcode.com/problems/maximize-the-number-of-target-nodes-after-connecting-trees-i/description/

### Bug Category

Problem constraints

### Bug Description

Got a TLE for an O(m^2 + n^2) solution. This should pass, given the fact that the bounds are 2 < m, n < 1000. Swapping out `unordered_map` for `vector` in places where it can be leveraged makes the solution pass, due to the lower constant overheads of `vector` compared to `unordered_map`. This shouldn't be necessary however, given the time complexity of a lookup operation for both data structures is O(1). Please look at this, I believe the time constraints are too strict for this problem.

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
class Solution {
private:
    int get_num_visitable(unordered_map<int, vector<int>> &adj_list, int node, int k) {
        int num_visitable = 0;
    
        queue<pair<int, int>> q;
        unordered_set<int> visited;

        q.push({node, 0});
        while (!q.empty()) {
            auto [curr, moves] = q.front();
            q.pop();
            if (moves > k) break;
            if (visited.count(curr)) continue;
            visited.insert(curr);
            num_visitable++;
            
            vector<int> neighbors = adj_list[curr];
            for (int neigh : neighbors) q.push({neigh, moves + 1});
        }

        return num_visitable;
    }
public:
    vector<int> maxTargetNodes(vector<vector<int>>& edges1, vector<vector<int>>& edges2, int k) {
        unordered_map<int, vector<int>> adj_list_2;
        int n_2 = edges2.size() + 1;
        for (vector<int> &edge : edges2) {
            int from = edge[0];
            int to = edge[1];

            adj_list_2[from].push_back(to);
            adj_list_2[to].push_back(from);
        }

        int max_visitable = 0;
        for (int i = 0; i < n_2; ++i) {
            int num_visitable = get_num_visitable(adj_list_2, i, k - 1);
            max_visitable = max(max_visitable, num_visitable);
        }

        unordered_map<int, vector<int>> adj_list_1;
        int n_1 = edges1.size() + 1;
        for (vector<int> &edge : edges1) {
            int from = edge[0];
            int to = edge[1];

            adj_list_1[from].push_back(to);
            adj_list_1[to].push_back(from);
        }

        vector<int> ans;
        unordered_map<int, int> distances;
        for (int i = 0; i < n_1; ++i) {
            int num_visitable = get_num_visitable(adj_list_1, i, k);
            ans.push_back(num_visitable + max_visitable);
        }

        return ans;
    }
};
```

### Expected behavior

Expected behavior is AC (solution to pass). The solution passes 815/817 test cases, timing out on the very last couple.

**Comment by jackpalaia** [comment]
Hello, this question is not about a missing test case. This question is about the time constraints for the problem being too strict, at least for C++. Please take a look and let me know if the constraints can be changed.

**Comment by bramar2** [comment]
> Hello, this question is not about a missing test case. This question is about the time constraints for the problem being too strict, at least for C++. Please take a look and let me know if the constraints can be changed.

Sorry if this sounds insulting but I feel like your code performance is just terrible. Your code takes 1235ms for a random max constraint tree test while a good solution takes under 100ms. There is no way your code has that time complexity. The discrepancy is too far (+10x). You should look at your code more.

**Comment by bramar2** [comment]
> Hello, this question is not about a missing test case. This question is about the time constraints for the problem being too strict, at least for C++. Please take a look and let me know if the constraints can be changed.

I optimized it down to 537ms (max constraint) to the following code (AC at 2890ms):
It still uses unordered_map and unordered_set. The main bottleneck is using unordered_set<int> which is considerably more expensive than vector<bool>. unordered_map doesn't actually seem to hurt a lot because you're only making two of them each case but you make a lot more unordered_set. So, I guess next time don't use unordered_set if you are gonna use it a ton. (vector<bool> ACs at 564 ms)
```cpp
class Solution {
private:
    int get_num_visitable(auto& adj_list, int node, int k, int vertCount) {
        int num_visitable = 0;
    
        queue<pair<int, int>> q;
        unordered_set<int> visited(3*vertCount);
        q.push({node, 0}); visited.insert(node);
        while (!q.empty()) {
            auto [curr, moves] = q.front();
            q.pop();
            if (moves > k) break;
            num_visitable++;
            
            for (int neigh : adj_list[curr]) if(!visited.count(neigh)) visited.insert(neigh), q.push({neigh, moves + 1});
        }

        return num_visitable;
    }
public:
    vector<int> maxTargetNodes(vector<vector<int>>& edges1, vector<vector<int>>& edges2, int k) {
        unordered_map<int, vector<int>> adj_list_2;
        int n_2 = edges2.size() + 1;
        for (vector<int> &edge : edges2) {
            int from = edge[0];
            int to = edge[1];

            adj_list_2[from].push_back(to);
            adj_list_2[to].push_back(from);
        }

        int max_visitable = 0;
        for (int i = 0; i < n_2; ++i) {
            int num_visitable = get_num_visitable(adj_list_2, i, k - 1, n_2);
            max_visitable = max(max_visitable, num_visitable);
        }

        unordered_map<int, vector<int>> adj_list_1;
        int n_1 = edges1.size() + 1;
        for (vector<int> &edge : edges1) {
            int from = edge[0];
            int to = edge[1];

            adj_list_1[from].push_back(to);
            adj_list_1[to].push_back(from);
        }

        vector<int> ans(n_1);
        for (int i = 0; i < n_1; ++i) {
            int num_visitable = get_num_visitable(adj_list_1, i, k, n_1);
            ans[i] = (num_visitable + max_visitable);
        }

        return ans;
    }
};
```
