### ISSUE TITLE
[BUG] - <面试题 02.01. 移除重复节点>

### ISSUE THREAD

**Issue by warning02** [LeetCode-Feedback/LeetCode-Feedback#25650]
### LeetCode 用户名

尽量不白给

### 问题号码、标题和链接

面试题 02.01. 移除重复节点

### Bug Category

不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*

### 描述

即使提交官方题解，样例测试仍然不通过

### 你使用的语言

C++

### 你提交或者运行的代码

```bash
class Solution {
public:
    ListNode* removeDuplicateNodes(ListNode* head) {
        if (head == nullptr) {
            return head;
        }
        unordered_set<int> occurred = {head->val};
        ListNode* pos = head;
        // 枚举前驱节点
        while (pos->next != nullptr) {
            // 当前待删除节点
            ListNode* cur = pos->next;
            if (!occurred.count(cur->val)) {
                occurred.insert(cur->val);
                pos = pos->next;
            } else {
                pos->next = pos->next->next;
            }
        }
        pos->next = nullptr;
        return head;
    }
};

```

### 期望行为

修改样例测试结果

**Comment by liyuzhu-lc** [comment]
感谢您的宝贵反馈，我们已经将您的反馈提交给我们的负责团队，并将会对相关信息进行核查，有新的进展及时再与您联系。感谢您的理解与支持。

**Comment by amcones-lc** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by warning02** [comment]
leetcode.cn/u/jin-liang-bu-bai-gei/

谢谢
&nbsp;


无争
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年12月3日(星期二) 中午11:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LeetCode-Feedback/LeetCode-Feedback] [BUG] - <面试题 02.01. 移除重复节点&gt; (Issue #25650)














 
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by amcones-lc** [comment]
你好，当前该题已添加测试用例，奖励已发放。
