### ISSUE TITLE
Missing Test Case - 33. Search in Rotated Sorted Array

### ISSUE THREAD

**Issue by srikartangallapally** [LeetCode-Feedback/LeetCode-Feedback#25668]
### LeetCode Username

srikartangalla

### Problem Number, Title, and Link

33. Search in Rotated Sorted Array https://leetcode.com/problems/search-in-rotated-sorted-array/description/

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

The code written in greater time complexity also gets passed in execution without TLE.

### Language Used for Code

Java

### Expected behavior

The code written in time complexity O(n) should not pass the test cases and it should give TLE but it works fine, which it shouldn't.

### Additional context

I suggest you to include the below test case for the following question 
nums = [500000, 500001, ..., 999999, 0, 1, ..., 499999]
target = 750000

**Comment by srikartangallapally** [comment]
class Solution {
    public int search(int[] nums, int target) {
        int left = 0, right = nums.length - 1;

        while (left < right) {
            int mid = (left + right) / 2;
            if (nums[mid] > nums[right]) {
                left = mid + 1;
            } else {
                right = mid;
            }
        }

        int pivot = left;
        left = 0;
        right = nums.length - 1;

        if (target >= nums[pivot] && target <= nums[right]) {
            left = pivot;
        } else {
            right = pivot - 1;
        }

        while (left <= right) {
            int mid = (left + right) / 2;
            if (nums[mid] == target) {
                return mid;
            } else if (nums[mid] < target) {
                left = mid + 1;
            } else {
                right = mid - 1;
            }
        }

        return -1;
    }
}
this is my code and the test case missing is 
nums = [500000, 500001, ..., 999999, 0, 1, ..., 499999]
target = 750000

**Comment by JS-JeevaSaravanan** [comment]
Good one @srikartangallapally
