### ISSUE TITLE
Missing Test Case - 645. Set Mismatch

### ISSUE THREAD

**Issue by shaharshsah** [LeetCode-Feedback/LeetCode-Feedback#2570]
#### Your LeetCode username
 shaharshsah

#### Category of the bug
- [ ] Question
- [y ] Solution
- [ ] Language

#### Description of the bug

test case
[1,1]
output-[1,2]
expected-[1,2]

[2,2]
output-[1,2]
expected-[2,1]

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public int[] findErrorNums(int[] nums) {
        int arr[]= new int[2];
        for(int i=0; i<nums.length-1; i++)
        {
            for(int j=i+1; j<nums.length; j++)
            {
                if(nums[i]==nums[j])
                {
                    arr[0]=i+1;
                    arr[1]=j+1;
                        //break;
                } 
            }
        }
        return arr;
        
    }
    }

```

#### Language used for code
 java

#### Screenshots

![image](https://user-images.githubusercontent.com/42636868/109821882-719ecc80-7c5c-11eb-9a65-9abb0f290e55.png)

**Comment by lc-kay** [comment]
@shaharshsah What is the issue you are trying to report?

**Comment by shaharshsah** [comment]
I put the screen shot
The output are not correct.
With regards,
Shaharsh sah

**Comment by lc-kay** [comment]
@shaharshsah The expected output is correct. Please check out this discuss post https://leetcode.com/problems/set-mismatch/discuss/613169/Special-case-22 or raise your question in discuss for further clarification. Thank you for your time!
