### ISSUE TITLE
Missing Test Case - 1776. Car Fleet II

### ISSUE THREAD

**Issue by mohit2023** [LeetCode-Feedback/LeetCode-Feedback#2572]
#### Your LeetCode username

mohit7153

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Code gives TLE on given test case but is accepted.
[carFleetTestcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6078556/carFleetTestcase.txt)

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<double> getCollisionTimes(vector<vector<int>>& cars) {
        int n=cars.size();
        int mn=INT_MAX;
        vector<double> ans(n,-1);
        vector<int> nc(n,n-1);
        mn=cars[n-1][1];
        for(int i=n-2;i>=0;i--){
            if(cars[i][1]<=mn){
                mn=cars[i][1];
                nc[i]=i;
                continue;
            }
            nc[i]=nc[i+1];
            
            for(int j=i+1;j<=nc[i];j++){
                double a=cars[i][0];
                double b=cars[j][0];
                double x=cars[i][1];
                double y=cars[j][1];
                if(y>x){
                    continue;
                }
                double t= (b-a)/(x-y);
                
                if(ans[j]==-1){
                    ans[i]=t;
                    break;
                }
                else{
                    if(t<=ans[j]){
                        ans[i]=t;
                        break;
                    }
                }
            }
        }
        
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

I expected a TLE as the result on submitting my solution but it got accepted.
Basically my algorithm takes O(n^2) time but in the constraints, n is 10^5, so my code should have given TLE.
So providing a test case with n=11000 which is giving TLE while using it in run code option.

#### Screenshots

![Screenshot (109)](https://user-images.githubusercontent.com/57009054/109858349-b5f09380-7c81-11eb-8718-a9b0b62482d0.png)
![Screenshot (110)](https://user-images.githubusercontent.com/57009054/109858368-bc7f0b00-7c81-11eb-8935-bc1122f0c0a8.png)
![Screenshot (111)](https://user-images.githubusercontent.com/57009054/109858382-c0129200-7c81-11eb-8791-882ab4c60f5f.png)

#### Additional context

The test case is such that speed of cars 1 to n-1 equal(lets say x), while the speed of car n is less than x. Any such test case would cause TLE for my code when n is such that O(n^2) algorithm is expected to give TLE.

**Comment by lc-kay** [comment]
Hi @mohit2023 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @mohit2023 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
