### ISSUE TITLE
Missing Test Case - 595. Big Countries

### ISSUE THREAD

**Issue by Raphyhayes** [LeetCode-Feedback/LeetCode-Feedback#2573]
"A country is big if it has an area of bigger than 3 million square km or a population of more than 25 million."

Add a test case where area is exactly 3 million square miles, and one where population is exactly 25 million people, so that submissions need to use > rather than >=.

my leetcode username is raphyhayes

**Comment by lc-kay** [comment]
@Raphyhayes To qualify for rewards, please submit an accepted solution and a custom test case that will fail the solution.

**Comment by lc-kay** [comment]
Hi @Raphyhayes 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
