### ISSUE TITLE
Missing Test Case - 100337. 设计自助结算系统

### ISSUE THREAD

**Issue by Aster-1024** [LeetCode-Feedback/LeetCode-Feedback#25749]
### LeetCode 用户名

aster24

### 问题号码、标题和链接

https://leetcode.cn/problems/dui-lie-de-zui-da-zhi-lcof/

### Bug Category

缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*

### 描述

```
["Checkout","add","add","get_max","remove","get_max"]
[[],[4],[7],[],[],[]]
["Checkout","remove","get_max"]
[[],[],[]]
["Checkout","add","add","add,"get_max","remove","get_max"]
[[],[4],[7],[22],[],[],[]]
```

### 你使用的语言

None

### 你提交或者运行的代码

```bash
[type the code]
```

### 期望行为

fix

**Comment by liyuzhu-lc** [comment]
感谢您的宝贵反馈，我们已经将您的反馈提交给我们的负责团队，并将会对相关信息进行核查，有新的进展及时再与您联系。感谢您的理解与支持。

**Comment by amcones-lc** [comment]
您好，在与相关团队核实后：***不处理***（由于技术原因，我们暂时无法添加测试用例）。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
