### ISSUE TITLE
Problem Description - 887. Super Egg Drop

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#2574]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
The problem description is not clear enough. If an egg does not break after it is dropped, the egg can be reused. However, this statement is NOT included in the problem description, which makes the description unclear.
Therefore, one statement should be added at the end of paragraph 4, as follows.
> Each *move*, you may take an egg (if you have an unbroken one) and drop it from any floor `X` (with `1 <= X <= N`). **If the egg does not break after you drop it, you may reuse the egg for further moves.**

This issue is relevant to issue #2567 , which is about the Chinese description. I think the English description should be modified as well.

#### Expected behavior
One statement should be added at the end of paragraph 4 to make the problem description clear. After adding the statement, paragraph 4 should be like the following.
> Each *move*, you may take an egg (if you have an unbroken one) and drop it from any floor `X` (with `1 <= X <= N`). **If the egg does not break after you drop it, you may reuse the egg for further moves.**

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
