### ISSUE TITLE
Missing Test Case - 1134. Armstrong Number

### ISSUE THREAD

**Issue by davemoedee** [LeetCode-Feedback/LeetCode-Feedback#2575]
#### Your LeetCode username

djmo

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

I was able to write code that is accepted for submission that should not be accepted. Any of the following test cases would cause the script to fail: 25, 36, 125, 729

In general, there needs to be a test cases where starting from the right (since most people will start there), summing up less than all the digits will equal N.

#### Code you used for Submit/Run operation

```
# 1134. Armstrong Number
class Solution:
    def isArmstrong(self, N: int) -> bool:
        n = N
        l = int(math.log10(n)) + 1
        # Proper while criteria should be N >= 0
        while n > 0 and N > 0:
            (n, mod) = divmod(n, 10)
            N -= mod ** l
        return N == 0
```

#### Language used for code

Python3

#### Expected behavior

The proposed solution should not be accepted as there is a case where it prematurely breaks out of the loop and returns True before processing all digits. For example, with 729, after processing the 9 it will return true since 9**3 = 729.

**Comment by lc-kay** [comment]
Hi @davemoedee 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @davemoedee 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
