### ISSUE TITLE
Missing Test Case - 100348. Permutation II LCCI

### ISSUE THREAD

**Issue by Aaron000011** [LeetCode-Feedback/LeetCode-Feedback#25768]
### LeetCode 用户名

yi-ling-u

### 问题号码、标题和链接

https://leetcode.cn/problems/permutation-ii-lcci/description/

### Bug Category

缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*

### 描述

```
abbbbsdwdwef，使用该测试用例时报错
```

### 你使用的语言

Python/Python3

### 你提交或者运行的代码

```bash
class Solution:
    def permutation(self, S: str) -> List[str]:
        res = []
        for i in range(len(S)):
            if i == 0:
                res.append(S)
            else:
                S1 = S[i:len(S)]+S[0:i]
                res.append(S1)
        return res
```

### 期望行为

可以正常运行代码

**Comment by liyuzhu-lc** [comment]
感谢您的宝贵反馈，我们已经将您的反馈提交给我们的负责团队，并将会对相关信息进行核查，有新的进展及时再与您联系。感谢您的理解与支持。

**Comment by amcones-lc** [comment]
您好，在与相关团队核实后：***不处理***（题目要求字符串长度在 [1,9]）。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
