### ISSUE TITLE
Wrong Test Case - 287. Find the Duplicate Number

### ISSUE THREAD

**Issue by EsraNurDeniz** [LeetCode-Feedback/LeetCode-Feedback#2577]
#### Your LeetCode username
esradeniz

#### Category of the bug
- [287] Question
- [ ] Solution
- [Java ] Language

#### Description of the bug

The description is:  There is only one repeated number in nums, return this repeated number.
However in one of the test cases nums is:  [2,2,2,2,2].
It is not consistent with the description. Because if the description is correct the problem can be solved with consecutive number formula which is that if the numbers are like 1 + 2 + ... + n  = n * (n+1) /2.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

```
class Solution {
    public int findDuplicate(int[] nums) {
        int len = nums.length;
        int expectedTotal = (len * (len-1)) / 2;
        int total = 0;
        
        for(int num : nums)
            total += num;
        
        return total - expectedTotal;
    }
}
```

**Comment by lc-kay** [comment]
@EsraNurDeniz The constraints clearly state that "All the integers in nums appear only once except for precisely one integer which appears two or more times.", which means that the duplicate number can appear more than twice. Thank you for your time.
