### ISSUE TITLE
Missing Test Case - 100489. Minimum Time to Break Locks I

### ISSUE THREAD

**Issue by YoruJiang** [LeetCode-Feedback/LeetCode-Feedback#25774]
### LeetCode 用户名

https://leetcode.cn/u/al_zn/

### 问题号码、标题和链接

100489.破解锁的最少时间I https://leetcode.cn/problems/minimum-time-to-break-locks-i/description/

### Bug Category

缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*

### 描述

添加用例 strength=[65,20,1,80,52,39] ，K=3
贪心地选择 下次选择相比这次选择节省时间最少的锁，该解法存在问题，但目前的所有测试用例可以通过。

### 你使用的语言

C++

### 你提交或者运行的代码

```bash
class Solution {
public:
    int findMinimumTime(vector<int>& strength, int K) {
        int n = strength.size(), ans = 0, x = 1, nx = x + K;
        vector<int> vis(n);
        for (int i = 0; i < n; i++) {
            tuple<int, int, int> mn{INT_MAX, INT_MAX, INT_MAX};
            int idx = -1;
            for (int j = 0; j < n; j++) {
                if (!vis[j]) {
                    tuple<int, int, int> t = {
                        (strength[j] + x - 1) / x - (strength[j] + nx - 1) / nx,
                        (strength[j] + x - 1) / x, -strength[j]};
                    if (mn > t) {
                        mn = t;
                        idx = j;
                    }
                }
            }
            vis[idx] = 1;
            ans += get<1>(mn);
            x = nx;
            nx += K;
        }
        return ans;
    }
};
```

### 期望行为

该解法应该无法通过所有用例。

### 屏幕截图

![image](https://github.com/user-attachments/assets/c2970f23-ff66-4557-a56a-544552b75af5)

**Comment by liyuzhu-lc** [comment]
感谢您的宝贵反馈，我们已经将您的反馈提交给我们的负责团队，并将会对相关信息进行核查，有新的进展及时再与您联系。感谢您的理解与支持。

**Comment by amcones-lc** [comment]
We have received feedback, please wait for us to process.

**Comment by amcones-lc** [comment]
你好，当前题目已更新，请留言告知一下力扣中文网站的个性域名（Ps：若不知道哪里查看自己的个性域名，可以通过浏览以下网址：https://support.leetcode.cn/hc/kb/article/1277837 ），我们给予积分奖励。

**Comment by YoruJiang** [comment]
https://leetcode.cn/u/al_zn/

**Comment by amcones-lc** [comment]
你好，当前该题已添加测试用例，奖励已发放。
