### ISSUE TITLE
March Challenge - Intersection of Two Linked Lists: Additional Inputs not Provided in Solution Boilerplate?

### ISSUE THREAD

**Issue by rschuman** [LeetCode-Feedback/LeetCode-Feedback#2578]
#### Your LeetCode username
tach1k0ma

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Please correct me if I am wrong, but it seems as though the `intersectVal`, `skipA`, and `skipB` inputs are **not** provided to the boilerplate code in the solution, thus making a scenario such as Example 1 unsolvable.

![image](https://user-images.githubusercontent.com/285648/109951753-6eb9df80-7d21-11eb-87bd-d7b8d255c701.png)

Further explained:

- Via list traversal, I am able to retrieve `ListA` values `[4,1,8,4,5]`
- Via list traversal, I am also able to retrieve `ListB` values `[5,6,1,8,4,5]`
- Without having access to `intersectVal` -or- `skipA` and `skipB`, there is no way for me to know if `ListA` and `ListB` intersect at value `8`; in fact, I would assume that they intersect at value `1` by the nature of reviewing list values in reverse order.

#### Code you used for Submit/Run operation

Boilerplate code:
```python
# Definition for singly-linked list.
# class ListNode(object):
#     def __init__(self, x):
#         self.val = x
#         self.next = None

class Solution(object):
    def getIntersectionNode(self, headA, headB):
        """
        :type head1, head1: ListNode
        :rtype: ListNode
        """
```

#### Language used for code

Python

#### Screenshots

Boilerplate code screenshot:
![image](https://user-images.githubusercontent.com/285648/109951840-84c7a000-7d21-11eb-9884-0c5162d0b871.png)

Default Test Case:
![image](https://user-images.githubusercontent.com/285648/109952106-d2440d00-7d21-11eb-971d-114e2a546e30.png)

**Comment by archit11111** [comment]
`intersect`, `skipA`, and `skipB` are provided as inputs in test cases for the internal construction of the linked lists. You will only be given the head nodes of the constructed lists and need to find the intersection node(if there exists one).

**Comment by rschuman** [comment]
Thank you @archit11111!

> You will only be given the head nodes of the constructed lists and need to find the intersection node(if there exists one).

This gives me the understanding that the design of the question is valid; without revealing the answer to the solution, I know I can go about comparison between nodes a different way.
