### ISSUE TITLE
Wrong Test Case - 160. Intersection of Two Linked Lists

### ISSUE THREAD

**Issue by noonkho** [LeetCode-Feedback/LeetCode-Feedback#2579]
Wrong test case and Wrong output for Examaple 1

#### Your LeetCode username

LeetCode ID: noonkho

#### Category of the bug
- [ ] Question

#### Description of the bug
In Example 1,
Linked List A is 4 -> 1 -> 8 -> 4 -> 5
Linked List B is 5 -> 6 -> 1 -> 8 -> 4 -> 5

which means the intersection of both linked list should be the list node with value 1
but that's not the case for the example and during submission test case

#### Code you used for Submit/Run operation

``` 
class Solution(object):
    '''Idea:
    if 2 lists will intersect and have the same following list afterwards
    maybe we can start from the end and see when does the values are different

    Step 1: turn linkedlist into a list
    Step 2: reverse the list
    Step 3: find the number of shared elements for both lists
    Step 4: len(list) - that num = the no. of iteration from head to that ref
    Step 5: return ref
    '''
    # Step 1: turn linkedlist into a list
    def convert(self, linkedlist):
        lis = []
        while linkedlist: # while it is not None
            lis.append(linkedlist.val)
            linkedlist = linkedlist.next
        return lis
    
    # Step 2: reverse the list
    def reverse(self, lis):
        return lis[::-1]
    
    # Step 3: find the number of shared elements for both lists
    def lenOfSameElem(self, lisA, lisB):
        num = 0
        if lisA[0] != lisB[0]:
            return -1
        while lisA[num] == lisB[num]:
            num += 1
        return num
    
    def getIntersectionNode(self, headA, headB):
        """
        :type head1, head1: ListNode
        :rtype: ListNode
        """
        # Step 1 & 2
        rListA = self.reverse(self.convert(headA))
        rListB = self.reverse(self.convert(headB))

        # Step 3
        num = self.lenOfSameElem(rListA, rListB)
        if num == -1:
            return None

        # Step 4
        ilA = len(rListA) - num
        ilB = len(rListB) - num

        # Step 5
        if ilA <= ilB: # a compare to get lesser iteration
            for i in range(ilA):
                headA = headA.next
            return headA
        else:
            for i in range(ilB):
                headB = headB.next
            return headB
```

#### Language used for code
Python

#### Expected behavior

When the inputs are ([ ] stands for linked list from left to right, head is on left)
[4, 1, 8, 4, 5] and [5, 6, 1, 8, 4, 5]
The output should be [1, 8, 4, 5]

#### Screenshots
<img width="1016" alt="Screenshot 2021-03-04 at 7 10 17 PM" src="https://user-images.githubusercontent.com/30166035/109955272-44662300-7d1d-11eb-9043-185a93f0b6d7.png">
Expected Result:
<img width="676" alt="Screenshot 2021-03-04 at 7 21 06 PM" src="https://user-images.githubusercontent.com/30166035/109956589-c7d44400-7d1e-11eb-8544-1424555516c0.png">

**Comment by noonkho** [comment]
<img width="1217" alt="Screenshot 2021-03-04 at 7 23 51 PM" src="https://user-images.githubusercontent.com/30166035/109956903-2a2d4480-7d1f-11eb-9535-b816c80d2026.png">
This is what happened when submitted

**Comment by lc-kay** [comment]
@noonkho The expected output is correct. Please check out the input explanation in example one for a better understanding. Thank you for your time.
