### ISSUE TITLE
Expected answer also results in `Runtime Error` 

### ISSUE THREAD

**Issue by tripathysa** [LeetCode-Feedback/LeetCode-Feedback#258]
**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
When I submit a program with a possible runtime error and run it with a custom test case,
Expected answer also results in `Runtime Error` which it shouldn't since it is not dependent on my program.

Specifically, It happened for https://leetcode.com/explore/interview/card/facebook/5/array-and-strings/3018/ 
**what language is your code written in**
Python

**The code you submit/run**
```
class Solution:
    def validIPAddress(self, IP: str) -> str:
        if '.' in IP:
            return self.checkv4(IP)
        elif ':' in IP:
            return self.checkv6(IP)
        else:
            return 'Neither'



    def checkdv4(self, IP):
        splits = IP.split('.')
        if splits.__len__()!=4:
            return 'Neither'
        for split in splits:

            try:
                if (split.startswith('0') and len(split) > 1) or int(split)>255 or int(split)<0 or not all([x.isdigit() for x in split]):
                    return 'Neither'
            except:
                return 'Neither'
        return 'IPv4'


    def checkv6(self, IP):
        splits = IP.split(':')
        if splits.__len__()!=8:
            return 'Neither'
        hexdigits = '0123456789abcdefABCDEF'
        for x in splits:
            # Validate hexadecimal in range (0, 2**16):
            # 1. at least one and not more than 4 hexdigits in one chunk
            # 2. only hexdigits are allowed: 0-9, a-f, A-F
            if len(x) == 0 or len(x) > 4 or not all(c in hexdigits for c in x):
                return "Neither"
        return 'IPv6'
```

**Expected behavior**
Expected solution shouldn't result in Runtime error

**Screenshots**
[
<img width="977" alt="Screen Shot 2020-05-03 at 2 09 03 PM" src="https://user-images.githubusercontent.com/15757777/81036565-64565d00-8e54-11ea-8598-279999b3ee01.png">
](url)

**Additional context**
To simple reproduce, make a deliberate error in your program and using a custom testcase run it to fail.

**Comment by CooperCooperCooper** [comment]
Hi @tripathysa ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @tripathysa ,

Thank you for your time. Upon investigating this issue, we found this issue to be non-content-related (the issue stems from an origin away from the content on this problem); therefore, it's not valid for content contribution reward. 

We encourage you to share more content-related issues here with us for [valid content contribution rewards](https://leetcode.com/discuss/general-discussion/526802/File-Problem-and-Solution-Content-Issues-to-Our-GitHub-Public-Feedback-Repo-Now!). Thank you again for your support and understanding.

**Comment by tripathysa** [comment]
its still a bug..So hope you're fixing it

**Comment by CooperCooperCooper** [comment]
Hi @tripathysa ,
Our engineers were already notified of the issue. To keep this channel available for content issues, this fix will not be updated here. We appreciate your support and understanding.

**Comment by CooperCooperCooper** [comment]
Hi @tripathysa ,
Thank you for your time! Just want to let you know that the bug has been fixed :)
