### ISSUE TITLE
Missing Test Case - 859. Buddy Strings

### ISSUE THREAD

**Issue by jk1019** [LeetCode-Feedback/LeetCode-Feedback#2581]
#### Your LeetCode username

jKLeetC

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The solution is accepted but fails on the following test case:
"abcd"
"bacd"

#### Code you used for Submit/Run operation

```
// Buddy Strings
class Solution {
	public boolean buddyStrings(String A, String B) {
		if(A.length()!=B.length()){
			return false;
		}
		if(A.equals(B)) {
			int[] count = new int[26];
			for(int i=0;i<A.length();i++){
				count[A.charAt(i)-97]++;
			}
			for(int i:count){
				if(i>1) {
					return true;
				}
			}
			return false;
		} else {
			int maxDiffCount = 2;
			int[] diff = new int[maxDiffCount];
			for(int i=0;i<A.length();i++) {
				if(maxDiffCount<1) {
					return false;
				}
				if(A.charAt(i)!=B.charAt(i)) {
					diff[--maxDiffCount]=i;
				}
			}
			char[] a = A.toCharArray();
			a[diff[0]] = A.charAt(diff[1]); 
			a[diff[1]] = A.charAt(diff[0]);
			if(B.equals(new String(a))){
				return true; 
			}
			return false;
		}
	}
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case.

#### Screenshots

![image](https://user-images.githubusercontent.com/9429981/109965567-21d00c00-7d15-11eb-98f5-bb2203d76990.png)
![image](https://user-images.githubusercontent.com/9429981/109964370-986c0a00-7d13-11eb-82ef-ac609940d49a.png)

**Comment by lc-kay** [comment]
Hi @jk1019 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @jk1019 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
