### ISSUE TITLE
Missing Test Case - 160. Intersection of Two Linked Lists

### ISSUE THREAD

**Issue by satyaprakashranjan** [LeetCode-Feedback/LeetCode-Feedback#2582]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@satyaprakashranjan Please provide the missing test case you are trying to report and the solution it failed on. Thank you!

**Comment by lc-kay** [comment]
Hi @satyaprakashranjan 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
