### ISSUE TITLE
Missing Test Case - 453. Minimum Moves to Equal Array Elements

### ISSUE THREAD

**Issue by Carloszone** [LeetCode-Feedback/LeetCode-Feedback#2583]
#### Your LeetCode username
Carloszone

#### Category of the bug
- [ ] Solution

#### Description of the bug
Question information: 453. Minimum Moves to Equal Array Elements
description: [the same input and the same output] the run code result accept but submit report wrong answer

#### Code you used for Submit/Run operation
```
class Solution:
    def minMoves(self, nums: List[int]) -> int:
        n = len(nums)
        x = max(nums)
        if len(set(nums)) <=1:
            return(0)
        else:
            while (n*x - sum(nums))%(n-1) != 0:
                x +=1
            return((n*x - sum(nums))//(n-1))
```

#### Language used for code
Python 3

#### Expected behavior
fix this bug.

#### Screenshots
run operation result
![image](https://user-images.githubusercontent.com/64500682/110001979-ea486c00-7ce2-11eb-9d4c-88b6e8dec038.png)

submit result
![image](https://user-images.githubusercontent.com/64500682/110001955-e3215e00-7ce2-11eb-9caa-7f1c19b703a8.png)

**Comment by lc-kay** [comment]
Hi @Carloszone 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
