### ISSUE TITLE
Wrong test case

### ISSUE THREAD

**Issue by ojasvichaudhary16** [LeetCode-Feedback/LeetCode-Feedback#2584]
Write a program to find the node at which the intersection of two singly linked lists begins.
8
[4,1,8,4,5]
[5,6,1,8,4,5]
2
3

In
<img width="1226" alt="Screenshot 2021-03-05 at 12 22 47 AM" src="https://user-images.githubusercontent.com/43778431/110014719-244c5900-7d49-11eb-92a3-73d899bc9da4.png">

 that case intersection should be from 1 but it showing intersection at 8 my other 44 cases are pass

**Comment by lc-kay** [comment]
@ojasvichaudhary16 Thank you for reaching out. The expected output is correct. Please check out this post https://leetcode.com/problems/intersection-of-two-linked-lists/discuss/762774/Is-the-Example-and-Test-Case-Faulty
