### ISSUE TITLE
Invalid Testcase Check - 792. Number of Matching Subsequences

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#2585]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

When I input an invalid test case, the run code result shows "Runtime Error" rather than "invalid testcase". This can be misleading.
"abcde"

#### Code you used for Submit/Run operation

```
const int CH=255,N=5005;
char *_a[26][N],**a[CH]; int a1[CH];
class Solution {
public:
	int numMatchingSubseq(const string &s, vector<string>& w) {
		int n=s.size(),m=w.size(),ans=0;
		for (int i=0;i<26;++i)a['a'+i]=_a[i],a1['a'+i]=0;
		for (int i=0;i<m;++i){
			char &c=w[i][0];
			a[c][a1[c]++]=&c;
		}
		for (int i=0;i<n;++i){
			char c=s[i]; int k=a1[c]; a1[c]=0;
			for (char **j=a[c],**end=j+k;j!=end;++j){
				char x=*(++*j);
				if (!x)++ans;
				else a[x][a1[x]++]=*j;
			}
		}
		return ans;
	}
};
```

#### Language used for code

C++

#### Expected behavior

Expected: The testcase validator detects that the input is invalid (the second line was missing).
Reality: The run code result shows "Runtime Error". (And it crashed at somewhere outside my code.)

#### Screenshots

![792](https://user-images.githubusercontent.com/11583428/110017244-9f7f2200-7ceb-11eb-8961-d0229a2351c1.png)

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
