### ISSUE TITLE
Missing Test Case - 199. Binary Tree Right Side View

### ISSUE THREAD

**Issue by anatoli-karotki** [LeetCode-Feedback/LeetCode-Feedback#2586]
#### Your LeetCode username
dr_natolik

#### Category of the bug
- [ ] Question
-   **Solution**
- [ ] Language

#### Description of the bug
The task doesn't cover cases when the tree has left leg longest that right one.  

#### Code you used for Submit/Run operation
```
class Solution {
    List<Integer> res = new ArrayList<Integer>();
    public List<Integer> rightSideView(TreeNode root) {
        if(root == null){
            return res;
        }
        dfs(root,0);
        return res;
    }
    
    private void dfs(TreeNode curr, int level){
        if(level == res.size()){
            res.add(curr.val);
        }      
        if(curr.right != null){
            dfs(curr.right, level +1);
        }
        if(curr.left != null){
            dfs(curr.left, level +1);
        }
    }
}
```

#### Language used for code
Java

#### Expected behavior
Test has to fail for tests cases with longest left leg. For example:
_Input:_ root = [1,2,3,4,5,6,null,null,null,7,8,null,null,9]
_Output:_ [1,3,6 ] - **accepted, but it is wrong**
_Correct Output:_ [1,3,6,8,9]

**Comment by lc-kay** [comment]
@anatoli-karotki From the code and test case you submitted, both were accepted with the correct output. Please refer to the screenshot: 
<img width="1429" alt="Screen Shot 2021-03-05 at 12 31 43 PM" src="https://user-images.githubusercontent.com/70870126/110170274-d2d6b500-7dae-11eb-9bbc-918f53a86f50.png">

If you still believe this is an issue, please let me know and I will reopen the ticket. Thank you for your time!
