### ISSUE TITLE
[URGENT BUG] - Leetcode problems are displaying topics don't match with it

### ISSUE THREAD

**Issue by bobbyngo** [LeetCode-Feedback/LeetCode-Feedback#25869]
### LeetCode Username

bobbyngo

### Problem Number, Title, and Link

https://leetcode.com/problems/two-sum/description/

### Bug Category

Problem description

### Bug Description

The topic tag of **ALL THE PROBLEMS** displays incorrect categories
![image](https://github.com/user-attachments/assets/9331eb73-d777-4767-a6fc-af0ce53ccc93)

### Language Used for Code

None

### Expected behavior

It should be Array, HashMap topic category for 2 sum, and other topics should be display correctly

**Comment by bobbyngo** [comment]
**Could you specify the incorrect topic categories you are noticing?**
![image](https://github.com/user-attachments/assets/9425da25-e74b-4490-8031-c1bf15175342)
For 2 sum, I do not see why there is Database Bit Manipulation, Graph, BFS, DFS, Rolling Hash etc. A lot of irrelevant topics
 
**Is this issue occurring on the "Two Sum" problem exclusively, or is it pervasive across multiple problems?**
![image](https://github.com/user-attachments/assets/1d4971a1-2014-4f0d-b9d8-b1deb1aaa7f2)
Yes, It occurred to all the problems. 
For example, in Add Two Numbers https://leetcode.com/problems/add-two-numbers/description/
This is a linked list problem, I do not see why Graph is mentioned here with DP, Sliding Window and Sorting

In general, a lot of topics that are not relevant to the problems are mentioned

**Comment by evoionosp** [comment]
I am also facing same issue. All the problems I am opening, I see tons of irrelevant topics.
