### ISSUE TITLE
943. 最短超级串

### ISSUE THREAD

**Issue by 0xac001d09** [LeetCode-Feedback/LeetCode-Feedback#259]
["a","b","c","abc"]这个样例结果应为abc，你们的预期结果不对吧
![image](https://user-images.githubusercontent.com/50208812/81064601-8dd2bf80-8f0c-11ea-8fe1-f774afa3cb84.png)

附上力扣id:  jerry_nju

**Comment by feiceh** [comment]
麻烦提供一下您的代码、以及 代码的语言（建议用 playground 链接），将信息提供完整才能有助于快速验证和精准的定位哟～

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认的～

**Comment by feiceh** [comment]
你好，该题目技术验证没有问题的，请仔细阅读理解题目意思。后续刷题学习中遇到困难，也可以通过阅读题目评论和题解看到一些解题思路哦～
