### ISSUE TITLE
Problem Description - 1778. Shortest Path in a Hidden Grid

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#2591]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
The description of problem [1778. Shortest Path in a Hidden Grid](https://leetcode.com/problems/shortest-path-in-a-hidden-grid) needs to be updated, about the provided class.

First of all, a class name should start with an upper-case letter, so the class name should be `GridMaster` instead of `gridMaster`. Although the class definition has changed, the class name in problem description is still `gridMaster`, which needs to be changed.

Secondly, each function/method should have a return type. For this problem, `canMove` and `isTarget` should have a return type `boolean`, and `move` should have a return type `void`.

Thirdly, for Java class definition, the semicolon is not needed at the end of the class. This should apply to both `GridMaster` and `Solution`.

Therefore, for Java, the definition of the provided class should be as follows.

```
// This is the GridMaster's API interface.
// You should not implement it, or speculate about its implementation
class GridMaster {
    public boolean canMove(char direction);
    public void move(char direction);
    public boolean isTarget();
}
```

For the other languages, the class definition should be changed similarly.

#### Language used for code
Java

#### Expected behavior
The expected behaviors include the following.

1. In both problem description and the code, the class name should be `GridMaster`, and each function/method should have a return type (`boolean` or `void`).
2. For Java, the class definition should not end with a semicolon. This should apply to both `GridMaster` and `Solution`.

#### Screenshots
The following screenshot is from LCCN, but the issue is the same.

![image](https://user-images.githubusercontent.com/12067364/110055181-73b97600-7d97-11eb-839a-042e0a38304b.png)

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
