### ISSUE TITLE
Add Follow Up - 1252. Cells with Odd Values in a Matrix

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#2593]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
[1252. Cells with Odd Values in a Matrix](https://leetcode.com/problems/cells-with-odd-values-in-a-matrix) can be solved using a brute force approach, which has time complexity `O(k(m + n) + mn)`, where `k` is the length of `indices`.

Other approaches that have lower time complexities also exist, such as `O(k + mn)` or `O(k + m + n)`. If this problem is asked during an interview, the interviewer may expect an approach with a greater time complexity.

Therefore, I suggest that a follow-up question should be added to this problem, as follows (the meaning is clear but the description may be changed).

> **Follow up:** Changing the values in the matrix is quite straightforward. Could you come up with the `O(k + mn)` solution or the `O(k + m + n)` solution, where `k` is the length of `indices`?

#### Expected behavior
A follow-up question is added at the end of problem description, requiring a solution with time complexity `O(k + mn)` or `O(k + m + n)` solution, where `k` is the length of `indices`.

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
