### ISSUE TITLE
Missing Test Case - 239. Sliding Window Maximum

### ISSUE THREAD

**Issue by miligithub** [LeetCode-Feedback/LeetCode-Feedback#2595]
#### Your LeetCode username
milileetcode

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

More test cases are needed.  For example, we can add this test case: [to-be-added-testcase](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6088832/to-be-added-testcase.txt)

Testing `Code 1` on existing test cases results in a runtime of 1368 ms, which is faster than 99.97% of Python3 online submissions for [Sliding Window Maximum](https://leetcode.com/problems/sliding-window-maximum/). However, `Code 1` should not be accepted because it uses the `reverse()` function to take the shortcuts on certain test cases. We need to add more test cases to reject such codes.

#### Code you used for Submit/Run operation

```
# Code 1 (should not be accepted, passes all existing test cases, but fails on the to-be-added one)
class Solution:
    def maxSlidingWindow(self, nums: List[int], k: int) -> List[int]:
        nums.reverse()
        l = len(nums)
        max_val = max(nums[:k])
        ans = [max_val]
        for i in range(k, l):
            max_val = max(max_val, nums[i])
            if nums[i-k] == max_val:
                max_val = max(nums[i-k+1:i+1])
            ans.append(max_val) 
        ans.reverse()
        return ans
```
```
# Code 2 (should be accepted, passes all existing test cases and the to-be-added one)
class Solution:
    def maxSlidingWindow(self, nums: List[int], k: int) -> List[int]:
        n = len(nums)
        ans = []
        stack = deque()
        for i, n in enumerate(nums):
            if stack and stack[0] + k <= i:
                stack.popleft()
            while stack and n >= nums[stack[-1]]:
                stack.pop()
            stack.append(i)
            ans.append(nums[stack[0]])
        return ans[k-1:]
```

#### Language used for code

`Python3`

#### Expected behavior

- Code 1 (should not be accepted, passes all existing test cases, but fails on [to-be-added-testcase](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6088832/to-be-added-testcase.txt)
 or costs more than 8000ms)
- Code 2 (should be accepted, passes all existing test cases as well as [to-be-added-testcase](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6088832/to-be-added-testcase.txt)) 

#### Screenshots

Code1 is accepted by existing test cases. But it should be rejected.
<img width="1167" alt="code1accepted" src="https://user-images.githubusercontent.com/50931204/110086117-34673700-7d4f-11eb-8045-142c80630608.png">

Code2 is accepted by existing test cases. And it should be accepted.
<img width="1167" alt="code2accepted" src="https://user-images.githubusercontent.com/50931204/110086134-3af5ae80-7d4f-11eb-9b84-c8adc544363c.png">

**Comment by lc-kay** [comment]
Hi @miligithub 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@miligithub Our team added the test case you provided, but it didn't fail the solution or changed anything. Thank you for your time.
