### ISSUE TITLE
[BUG] - Incorrect time complexity/data structure in algorithm and code.

### ISSUE THREAD

**Issue by chiragjagga** [LeetCode-Feedback/LeetCode-Feedback#25957]
### LeetCode Username

chiragjagga

### Problem Number, Title, and Link

347. Top K Frequent Elements - https://leetcode.com/problems/top-k-frequent-elements

### Bug Category

Editorial

### Bug Description

Approach 1: Heap
The time complexity mentioned for building the frequency array is O(N), but the map data structure has logarithmic complexity for the insert operation or [] operator, so complexity would be O(N logk).

Reference:
https://cplusplus.com/reference/map/map/operator[]/
Complexity
Logarithmic in size.

### Language Used for Code

C++

### Expected behavior

The code should use unordered_map to have O(N) time complexity or time complexity mentioned should be O( N logk).

### Screenshots

![image](https://github.com/user-attachments/assets/bad3c0d2-b7ad-4f7c-b4f5-ce76297224a3)
![image](https://github.com/user-attachments/assets/7fe45af0-920c-4f17-8f2c-436350185427)

**Comment by bramar2** [comment]
It specifically stated a `hash map` or equivalently `std::unordered_map` in C++ which has an average complexity of $O(1)$. Read carefully.
