### ISSUE TITLE
Problem Description - 637. Average of Levels in Binary Tree

### ISSUE THREAD

**Issue by jcrucesadrados** [LeetCode-Feedback/LeetCode-Feedback#2596]
#### Your LeetCode username
jcrucesadrados

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The binary tree representation attached to the example does not match the input.

Taking the input [3,9,20,15,7] provided as an example, the problem includes the following graphical representation for the tree node:
![bad representation](https://user-images.githubusercontent.com/4211670/110104282-3ceb5c00-7da7-11eb-8581-0348b5d298a2.png)

But, as we can see in the Tree Node Viewer, the correct representation of the binary tree is as follows:

![correct representation](https://user-images.githubusercontent.com/4211670/110104020-ec73fe80-7da6-11eb-914d-6811258a53f6.PNG)

As we can see, the third level is added to the left child of the root (9) in the correct representation, but in the example, the third level is added to the right child.

This error does not affect the result, but when debugging errors, it leads the user to a non-existent problem (for example, when applying DSF, why not access the correct node?).

Based on a DSF approach, the tree search order (when using the example provided in the description) is 3 - 9 - 20 - 15-7 when the correct execution will show 3 - 9 - 15 - 7 - 20.

#### Additional context
*Suggested actions*: An update to the representation of the sample tree node is suggested to improve and aid in the debugging process for users.

**Comment by lc-kay** [comment]
Hi @jcrucesadrados 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @jcrucesadrados 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
