### ISSUE TITLE
Missing Test Case - 76. Minimum Window Substring

### ISSUE THREAD

**Issue by yw5579358** [LeetCode-Feedback/LeetCode-Feedback#25971]
### LeetCode 用户名

2N2zRjhtNt

### 问题号码、标题和链接

76,最小覆盖子串,https://leetcode.cn/problems/minimum-window-substring/?envType=study-plan-v2&envId=top-interview-150

### Bug Category

不正确的测试用例 *（根据问题陈述，测试用例的输出不正确）*

### 描述

`class Solution {
    public static Map<Character,Integer> countMap=new HashMap<>();
    public static Map<Character,Integer> copyMap=new HashMap<>();
    public static String  minWindow(String s, String t) {
        String str="";
        char[] chs=s.toCharArray();
        for(char ch: t.toCharArray()){
            Integer x= countMap.getOrDefault(ch,0);
            countMap.put(ch,x+1);
        }
        int l=0,r=1;
        copyMap.put(chs[l],1);
        while( r<=s.length()){
            if(isOverryed()){
                if(str== "" || r-l < str.length()){
                    str=s.substring(l,r);
                }
                if(copyMap.get(chs[l])>1){
                    copyMap.put(chs[l],copyMap.get(chs[l])-1);
                }else{
                    copyMap.remove(chs[l]);
                }
                l++;
            }else{
                if(r==s.length()){
                    break;
                }
                int x= copyMap.getOrDefault(chs[r],0);
                copyMap.put(chs[r],x+1);
                r++;
            }
        }
        return str;
    }
    public static boolean isOverryed(){
        Set<Character> chars = countMap.keySet();
        for(char ch: chars){
            if(!copyMap.containsKey(ch)){
                return false;
            }
            if(copyMap.get(ch)< countMap.get(ch))
            {
                return false;
            }
        }
        return true;
    }

}`
这段代码，我自己测试期间，输出结果是正确的，输入a，结果为a
![image](https://github.com/user-attachments/assets/b2d479f0-32a6-423a-aa1b-1399bf22b828)
但是在线编辑器中，结果是””
![image](https://github.com/user-attachments/assets/91edbb0d-3a62-4069-b2c3-5266308c757e)

### 你使用的语言

Java

### 你提交或者运行的代码

```bash
class Solution {
    public static Map<Character,Integer> countMap=new HashMap<>();
    public static Map<Character,Integer> copyMap=new HashMap<>();
    public static String  minWindow(String s, String t) {
        String str="";
        char[] chs=s.toCharArray();
        for(char ch: t.toCharArray()){
            Integer x= countMap.getOrDefault(ch,0);
            countMap.put(ch,x+1);
        }
        int l=0,r=1;
        copyMap.put(chs[l],1);
        while( r<=s.length()){
            if(isOverryed()){
                if(str== "" || r-l < str.length()){
                    str=s.substring(l,r);
                }
                if(copyMap.get(chs[l])>1){
                    copyMap.put(chs[l],copyMap.get(chs[l])-1);
                }else{
                    copyMap.remove(chs[l]);
                }
                l++;
            }else{
                if(r==s.length()){
                    break;
                }
                int x= copyMap.getOrDefault(chs[r],0);
                copyMap.put(chs[r],x+1);
                r++;
            }
        }
        return str;
    }
    public static boolean isOverryed(){
        Set<Character> chars = countMap.keySet();
        for(char ch: chars){
            if(!copyMap.containsKey(ch)){
                return false;
            }
            if(copyMap.get(ch)< countMap.get(ch))
            {
                return false;
            }
        }
        return true;
    }

}
```

### 期望行为

对此情况下执行的代码不同问题纠正或解释

### 屏幕截图

![image](https://github.com/user-attachments/assets/30a06fad-fb21-4978-8182-42e427656cdc)

**Comment by liyuzhu-lc** [comment]
感谢您的宝贵反馈，我们已经将您的反馈提交给我们的负责团队，并将会对相关信息进行核查，有新的进展及时再与您联系。感谢您的理解与支持。

**Comment by amcones-lc** [comment]
您好，在与相关团队核实后：***不处理***（全局变量中的值会在多个测试用例间共享，建议在函数内初始化）。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
