### ISSUE TITLE
Missing Test Case - 928. Minimize Malware Spread II

### ISSUE THREAD

**Issue by arapfaik** [LeetCode-Feedback/LeetCode-Feedback#2598]
#### Your LeetCode username

unexpectedinterview

#### Category of the bug
- [X ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

I propose a new test case for the problem 928

#### Code you used for Submit/Run operation

```
[[1,0,0,0,0,0,0,0,1], [0,1,0,1,0,0,0,0,0], [0,0,1,1,0,1,0,0,0], [0,1,1,1,1,0,1,0,0], [0,0,0,1,1,1,0,0,0], [0,0,1,0,1,1,0,0,0], [0,0,0,1,0,0,1,1,0], [0,0,0,0,0,0,1,1,1], [1,0,0,0,0,0,0,1,1]]
[3, 7]
```

#### Language used for code

python3

#### Expected behavior

This new test case fails solutions that use a list when creating mapping from disjoint components to infected nodes. A set should be used instead of a list because a component might be connected to the same infected node in two different paths. Currently, no test case fails for my list-based solution, except this one. Leetcode's solution passes this test case, as well as my set-based solution. However, list-based solution fails as it should.

**Comment by lc-kay** [comment]
@arapfaik Can you please provide the code that this custom test case fails on? Thank you!

**Comment by lc-kay** [comment]
Hi @arapfaik 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.

**Comment by arapfaik** [comment]
Hi @lc-kay,

Apologies for the late reply. Here is the solution that uses a list. This passes all leetcode test cases. However, correct solution should use the two commented lines instead. The test case I submitted fails this solution.

```
class Solution:
    def minMalwareSpread(self,  graph, initial):
        
        initial = set(initial)
        N = len(graph)
        
        dsu = DSU(N)
        
        clean = set(range(N)) - initial
        for i in clean:
            for j in clean:
                if graph[i][j] == 1:
                    dsu.union(i, j)
                    
        comp2inits = defaultdict(list)        #comp2inits = defaultdict(set)
        for i in initial:
            for j in clean:
                if graph[i][j] == 1:
                    comp = dsu.find(j)
                    comp2inits[comp].append(i)        #comp2inits[comp].add(i)
        
        print(comp2inits)
                    
        init2size = defaultdict(int)
        for comp, inits in comp2inits.items():
            if len(inits) == 1:
                i = list(inits)[0]
                init2size[i] += dsu.get_size(comp)
                
        print(init2size)
                
        if init2size:
            return max(init2size, key=lambda i: (init2size[i], -i))
        return min(initial)
```

**Comment by arapfaik** [comment]
```
class DSU:
    def __init__(self, N):
        self.parent = list(range(N))
        self.size = [1] * N
        
    def find(self, x):
        if self.parent[x] == x:
            return x
        return self.find(self.parent[x])
    
    def union(self, x, y):
        xl = self.find(x)
        yl = self.find(y)
        if xl == yl:
            return
        self.parent[yl] = xl
        self.size[xl] += self.size[yl]
        
    def get_size(self, x):
        xl = self.find(x)
        return self.size[xl]
```

**Comment by lc-kay** [comment]
@arapfaik Can you please provide the submission details link? I am receiving Runtime Error on the code you provided. Thanks!

**Comment by arapfaik** [comment]
@lc-kay Sure, there ya go! Thanks

https://leetcode.com/submissions/detail/466608161/

**Comment by lc-kay** [comment]
Hi @arapfaik 
Thank you! I've relayed this issue to our team to investigate.

**Comment by arapfaik** [comment]
@lc-kay Thanks!

**Comment by lc-kay** [comment]
Hi @arapfaik 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
