### ISSUE TITLE
Wrong question description - 551. Student Attendance Record I

### ISSUE THREAD

**Issue by Carloszone** [LeetCode-Feedback/LeetCode-Feedback#2599]
#### Your LeetCode username
Carloszone

#### Category of the bug
- [ ] Question

#### Description of the bug
question description doesn't match its example and result.
the description is
"A student could be rewarded if his attendance record doesn't contain _more than one 'A' (absent)_ **or** _more than two continuous 'L' (late)_."
but the example shows only a input that matches both conditions can output True

So, the **or** should be changed to **and**

#### Code you used for Submit/Run operation
my code used "and", and it passed.
```
class Solution:
    def checkRecord(self, s: str) -> bool:
        if s.count("A") <= 1 and len(max(s.replace("P"," ").replace("A"," ").split(" "))) <=2:
            return(1)
        else:
            return(0)
```

#### Language used for code
Python 3

#### Expected behavior
fix this bug

#### Screenshots
the description.
![image](https://user-images.githubusercontent.com/64500682/110178500-8b631f80-7dd4-11eb-9436-ce214ac6fa9b.png)

the example2. it only contains 1 A, but it is false due to 3 continuous L
![image](https://user-images.githubusercontent.com/64500682/110178571-a2a20d00-7dd4-11eb-9077-693fa4e831e6.png)

A submission case. it contains 1A and 3L. Because the 3 L are not continuous, so the answer is true.
![image](https://user-images.githubusercontent.com/64500682/110178669-ccf3ca80-7dd4-11eb-8b98-41ac2b764b2e.png)

**Comment by lc-kay** [comment]
Hi @Carloszone 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Carloszone 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
