### ISSUE TITLE
54. Spiral Matrix

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#260]
**What kind of the bug**
- [ ] problem
- [x] solution
- [ ] language

**Describe the bug**
Approach 2: Layer-by-Layer solution has wrong analysis

**what language is your code written in**
Java

**The code you submit/run**
```
class Solution {
    public List < Integer > spiralOrder(int[][] matrix) {
        List ans = new ArrayList();
        if (matrix.length == 0)
            return ans;
        int r1 = 0, r2 = matrix.length - 1;
        int c1 = 0, c2 = matrix[0].length - 1;
        while (r1 <= r2 && c1 <= c2) {
            for (int c = c1; c <= c2; c++) ans.add(matrix[r1][c]);
            for (int r = r1 + 1; r <= r2; r++) ans.add(matrix[r][c2]);
            if (r1 < r2 && c1 < c2) {
                for (int c = c2 - 1; c > c1; c--) ans.add(matrix[r2][c]);
                for (int r = r2; r > r1; r--) ans.add(matrix[r][c1]);
            }
            r1++;
            r2--;
            c1++;
            c2--;
        }
        return ans;
    }
}
```

**Expected behavior**
Time Complexity: O(N), where N is the total number of elements in the input matrix. We add every element in the matrix to our final answer.

Space Complexity: O(N), the information stored in ans

This is the analysis provided. The time complexity is correct but the space complexity is not as the space taken due to input and output of the program is not counted as the space required for performing the algorithm. 

So the space complexity should be O(1) like it has been explained in [238](https://leetcode.com/problems/product-of-array-except-self/)

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for your time. The time complexity was trimmed. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
