### ISSUE TITLE
Missing Test Case - 1302. Deepest Leaves Sum

### ISSUE THREAD

**Issue by fosres** [LeetCode-Feedback/LeetCode-Feedback#2600]
#### Your LeetCode username
Username: TSRaiderHacks

#### Category of the bug
- [ ] Question
- [X ] Solution
- [ ] Language

#### Description of the bug

For the following test case:
Input: [6,7,8,2,7,1,3,9,null,1,4,null,null,null,5]
Output:
34
Expected:
19

The online judge upon submission declares my solution is wrong, however, when I run the same "Input" test case under the "Testcase" section it reports that my solution is correct.

#### Code you used for Submit/Run operation

```
/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     struct TreeNode *left;
 *     struct TreeNode *right;
 * };
 */

typedef struct TreeNode TreeNode;

int c = 0, max = 0, sum = 0;

void deepsearch(struct TreeNode* root)
{
        if ( c == max )
        {
                sum += root->val;                
        }
        
        else if ( c > max )
        {
                sum = root->val;
                
                max = c;
        }
        
        if ( root->left != 0x00)
        {
                c++;
                
                deepsearch(root->left);                
                
                c--;
        }
        
        if ( root->right != 0x00)
        {
                c++;
                
                deepsearch(root->right);                
                
                c--;
        }
        
        
}

int deepestLeavesSum(struct TreeNode* root)
{
        deepsearch(root);
        
        return sum;
}
```

#### Language used for code

Language used: C

#### Expected behavior

We expect the online judge--upon submission--to declare that my solution

is correct since the "Testcase" section admitted my solution works.

However, upon submitting my solution, the submission online judge

said my solution was wrong.

#### Screenshots

![image](https://user-images.githubusercontent.com/32973884/110180751-f9f1ae80-7dcf-11eb-95d1-1cec46252344.png)

**Comment by lc-kay** [comment]
Hi @fosres 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
