### ISSUE TITLE
Incorrect problem description - 127. Word Ladder

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#2606]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The problem states the 4th requirement "Every word in the sequence is in wordList". However in Example 1:
"hit"
"cog"
["hot","dot","dog","lot","log","cog"]
The beginWord "hit" is not in wordList. Furthermore, the 1st requirement says "The first word in the sequence is beginWord". Therefore it's clear that beginWord must be contained in the sequence but is not in wordList, therefore we should output 0 (no such sequence).

#### Additional context

Relevant links in the discussion zone:
https://leetcode.com/problems/word-ladder/discuss/1042614/Wrong-description
https://leetcode.com/problems/word-ladder/discuss/40766/I-know-why-some-old-code-can't-pass-the-judge-now
https://leetcode.com/problems/word-ladder/discuss/40796/Why-the-expected-output-is-0-not-5-for-this-case

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
