### ISSUE TITLE
Problem Description - 85. Maximal Rectangle

### ISSUE THREAD

**Issue by Bankde** [LeetCode-Feedback/LeetCode-Feedback#2609]
#### Your LeetCode username

bankde

#### Category of the bug
- [ ] Question

#### Description of the bug

I think there is a small typo in the constraints section. The test case clearly shows that the input is not "n x n" matrix.
```
Constraints:
    rows == matrix.length
    cols == matrix.length
```

#### Code you used for Submit/Run operation

N/A

#### Language used for code

N/A

#### Expected behavior

Should be like this? (Add [i] into the cols)
```
Constraints:
    rows == matrix.length
    cols == matrix[i].length
```

#### Screenshots

N/A

#### Additional context

I actually prefer this one
```
cols == matrix[0].length
```
but it's possible that rows == 0 so it has to be matrix[i].

**Comment by lc-kay** [comment]
Hi @Bankde 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Bankde 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
