### ISSUE TITLE
Time Complexity Restriction for Binary Search Problems

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#2612]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Most binary search problems can also be solved with time complexity `O(n)` (for 1D arrays) or `O(mn)` (for 2D arrays or matrices). However, the expected time complexity should be better than linear time complexity. If such a problem is asked during an interview, obviously the interviewer won't accept a solution with linear time complexity.
Therefore, I suggest that time complexity should be restricted for such problems. **In problem description, a statement should be added for time complexity requirement.**
The relevant problems are as follows.
[33. Search in Rotated Sorted Array](https://leetcode.com/problems/search-in-rotated-sorted-array/description)
For problem 33, the time complexity requirement should be `O(log n)`, where `n` is the length of array `nums`.
[34. Find First and Last Position of Element in Sorted Array](https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array)
For problem 34, the time complexity requirement should be `O(log n)`, where `n` is the length of array `nums`.
Currently, the `O(log n)` time complexity requirement is in the follow-up question. I think this should be the normal requirement, not a follow-up requirement, since the `O(n)` approach is too easy for an interview.
[35. Search Insert Position](https://leetcode.com/problems/search-insert-position)
Problem 35 is almost the same as the original binary search problem (problem 704), so the time complexity requirement should be `O(log n)`, where `n` is the length of array `nums`.
[74. Search a 2D Matrix](https://leetcode.com/problems/search-a-2d-matrix)
For problem 74, the time complexity requirement should be `O(log mn)`, where `m` and `n` are the number of rows and the number of columns of `matrix`.
[153. Find Minimum in Rotated Sorted Array](https://leetcode.com/problems/find-minimum-in-rotated-sorted-array)
For problem 153, the time complexity requirement should be `O(log n)`, where `n` is the length of array `nums`.
[240. Search a 2D Matrix II](https://leetcode.com/problems/search-a-2d-matrix-ii)
For problem 240, the time complexity requirement should be better than `O(mn)`, where `m` and `n` are the number of rows and the number of columns of `matrix`.
[704. Binary Search](https://leetcode.com/problems/binary-search)
Problem 704 is the original binary search problem, so the time complexity requirement should be `O(log n)`, where `n` is the length of array `nums`.

**Comment by lc-kay** [comment]
@stormsunshine Our team has reviewed your report and we are aware of this but we cannot enforce logn solutions due to a platform limitation, so we intend to keep them as they are for now. Thank you for your time!

**Comment by stormsunshine** [comment]
Hi @lc-kay , I understand there is platform limitation. My suggestion is **not** to add additional test data, but to add a statement in **problem description**. I think this should be practical.
