### ISSUE TITLE
Missing Test Case - 28. Find the Index of the First Occurrence in a String

### ISSUE THREAD

**Issue by guojin2020** [LeetCode-Feedback/LeetCode-Feedback#26149]
### LeetCode 用户名

amazing-greideraxc

### 问题号码、标题和链接

https://leetcode.cn/problems/find-the-index-of-the-first-occurrence-in-a-string/?envType=study-plan-v2&envId=top-interview-150

### Bug Category

缺少测试用例 *（由于缺少测试用例而接受不正确/低效的代码）*

### 描述

测试用例不能正确测试，当匹配的字符串出现在最后时的情况

### 你使用的语言

C

### 你提交或者运行的代码

```bash
int strStr(char* haystack, char* needle) {
    if (haystack == NULL || needle == NULL){
        return -1;
    }

    if (*needle == '\0') {
        return 0;
    }

    char *p= haystack;
    char *pNeedle = needle;
    while (*p != '\0'){
        if (*p != *pNeedle){
            if (*pNeedle == '\0'){ //找到
                return p - (pNeedle - needle) -  haystack;
            }
            p++;
            pNeedle = needle; //继续找 
        }else{
            p++;
            pNeedle++;
        }
    }

    return -1;
}
```

### 期望行为

输入：
haystack ="butsad"
needle = "sad"

时 输出为 3

**Comment by liyuzhu-lc** [comment]
感谢您的宝贵反馈，我们已经将您的反馈提交给我们的负责团队，并将会对相关信息进行核查，有新的进展及时再与您联系。感谢您的理解与支持。

**Comment by amcones-lc** [comment]
感谢反馈，经核实该题目题解及测试用例暂无异常，力扣会不断努力给大家带来更好的学习社区！后续刷题学习中遇到问题，可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
