### ISSUE TITLE
TLE in python vs accept in C++ 1781. Sum of Beauty of All Substrings

### ISSUE THREAD

**Issue by rudder-2021** [LeetCode-Feedback/LeetCode-Feedback#2615]
#### Your LeetCode username
jayaprakash-a

#### Category of the bug
- [ ] Question
- [x] Solution
- [x] Language

#### Description of the bug

For the question 1781. Sum of Beauty of All Substrings. An O(n**2*26) got accepted in C++. But similar codes in python got TLE. Largely affecting the contest.

#### Code you used for Submit/Run operation

Accepted code of one of the users.
```
int cnt[26];
class Solution {
public:
    int beautySum(string s) {
        int ans = 0;
        for(int i = 0; i < s.size(); i += 1){
            for(int& x : cnt) x = 0;
            for(int j = i; j < s.size(); j += 1){
                cnt[s[j] - 'a'] += 1;
                int ma = 0, mi = s.size();
                for(int x : cnt) if(x){
                    ma = max(ma, x);
                    mi = min(mi, x);
                }
                ans += ma - mi;
            }
        }
        return ans;
    }
};
```
TLE code in my case

```
class Solution:
    def beautySum(self, s: str) -> int:
        # print(len(s))
        answer = 0
        freq = [0 for _ in range(26)]
        for i in range(len(s)):
            for k  in range(26):
                freq[k] = 0
            freq[ord(s[i])-ord('a')] += 1
            for j in range(i+1, len(s)):
                freq[ord(s[j])-ord('a')] += 1
                maxVal = 0
                minVal = len(s)
                for k in range(len(freq)):
                    if freq[k] > 0:
                        minVal = min(minVal, freq[k])
                        maxVal = max(maxVal, freq[k])
                answer += (maxVal - minVal)
        return answer
```

#### Language used for code
C++, Python

#### Expected behavior
Both the codes are almost identical in time-complexity. But one got accepted and the other TLE. Please unrate the contest.

**Comment by lc-kay** [comment]
Hi @rudder-2021 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@rudder-2021 Our team has rejudged all TLE submissions. If your solution was accepted during the rejudging, it should be reflected on your account. Thank you for your time.
