### ISSUE TITLE
Missing Test Case - 1780. Check if Number is a Sum of Powers of Three

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#2616]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution is accepted but fails on the following test case:

6574365

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean checkPowersOfThree(int n) {
        Set<Integer> set = new HashSet<>();
        while(n>0){
        int x = (int)Math.floor(Math.log(n)/ Math.log(3));
          
        n -= Math.pow(3, x);
            
        if(!set.contains(x)){
            set.add(x);
        }else{
            return false;
        }
    }
        return true;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/110214102-0548e680-7e71-11eb-8e98-1268a6c3a551.png)

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
