### ISSUE TITLE
Missing Test Case - 820. Short Encoding of Words

### ISSUE THREAD

**Issue by harvey1993** [LeetCode-Feedback/LeetCode-Feedback#2617]
#### Category of the bug
- [ ] Question
- [ X] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
// short encoding of words
class Solution:
    def minimumLengthEncoding(self, words):
        s = set(words)
        for w in words:
            for i in range(1, len(w)):
                s.discard(w[i:])
        return sum(len(w) + 1 for w in s)
```

#### Language used for code

Python 3

#### Expected behavior

Only one word for ["iceberg","ice","berg"] 

#### Additional context

May need to sort based on the length of words in the list

**Comment by lc-kay** [comment]
@harvey1993 Please provide the submission details link to your solution. Thank you.

**Comment by lc-kay** [comment]
Hi @harvey1993 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
