### ISSUE TITLE
same solution leads to TLE & accepted on different submissions - 1781. Sum of Beauty of All Substrings

### ISSUE THREAD

**Issue by archit11111** [LeetCode-Feedback/LeetCode-Feedback#2618]
#### Your LeetCode username
archit91

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

A solution was rejected on submission during the biweekly contest 47. The same solution gets accepted sometimes when I try submitting now. 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int beautySum(string s) {
        int n = s.size(), sum = 0;
        for(int i=0;i<n;i++){
            for(int j=i;j<n;j++){
                vector<int>arr(26);
                for(int k=i;k<=j;k++){
                    arr[s[k] - 'a']++;
                }
                int mx=INT_MIN, mn=INT_MAX;
                for(int z=0;z<26;z++){
                    mx = max(mx, arr[z]);
                    if(arr[z] >= 1)
                        mn = min(mn, arr[z]);
                }
                    
                sum += (mx - mn);
            }
        }
        return sum;
    }
};
```

#### Language used for code
C++ 

#### Expected behavior

The same solution sometimes gets accepted and rejected at other times. This randomness should not happen and either this solution should get rejected altogether or accepted. 

#### Screenshots

![image](https://user-images.githubusercontent.com/40712852/110218238-8ee2cd80-7ede-11eb-91f6-849e60065783.png)

#### Additional context

This was a contest problem and since a solution that seems to be accepted now didn't get accepted during the contest, I feel that the first solution which was evaluated as **TLE** - [#1](https://leetcode.com/submissions/detail/464252013/) should be reevaluated and marked as **accepted** as the same solution is getting accepted here - [#2](https://leetcode.com/submissions/detail/464343209/), [#3](https://leetcode.com/submissions/detail/464343971/), [#4](https://leetcode.com/submissions/detail/464352862/). There probably might be same time complexity solution's submission which got accepted in the contest due to runtime measurement variations

**Comment by lc-kay** [comment]
Hi @archit11111 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by archit11111** [comment]
@lc-kay The contest rating has been updated but my solution hasn't been rejudged. I have still received the first submission as incorrect along with 5 minutes penalty for it and only the second submission which was submitted 20 minutes later is considered for evaluation.

**Comment by lc-kay** [comment]
@archit11111 Our team ran your submission and it received TLE several times because it is at the edge of the time limit. Thank you for your time.
