### ISSUE TITLE
Missing Test Case - 839. Short Encoding of Words

### ISSUE THREAD

**Issue by siddarthbhave** [LeetCode-Feedback/LeetCode-Feedback#2619]
#### Your LeetCode username

TheSnoo

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Some test cases aren't being checked in the final acceptance. My solution gets accepted even though it doesn't pass some of my custom test cases.

#### Code you used for Submit/Run operation

```
// Short Encoding of Words
class Solution:
    def minimumLengthEncoding(self, words: List[str]) -> int:
        W = set(words)
        for w in words:
            for i in range(1, len(w)):
                if w[-i:] in W:
                    W.remove(w[-i:])
                    break
        
        ret = 0
        for i in W:
            ret += len(i)
        return ret+len(W)
```

#### Language used for code
Python3

#### Expected behaviour

For the test case ````["time", "me", "ime"]```` the correct answer is 5 but my code, which got accepted, outputs 9 which is wrong.
Add test cases similar to this i.e., two or more strings being a substring (also ending with) of a bigger string.
Example of similar test cases:
```["qaa","a","aa"]```
Correct Answer: 4
My code that got accepted returns the wrong answer: 7

#### Additional context

Link to my code which got accepted
https://leetcode.com/submissions/detail/464369031/?from=explore&item_id=3662

**Comment by lc-kay** [comment]
Hi @siddarthbhave 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @siddarthbhave 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
