### ISSUE TITLE
973. K Closest Points to Origin

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#262]
**What kind of the bug**
- [ ] problem
- [x] solution
- [ ] language

**Describe the bug**
Approach 2: Divide and Conquer solution has wrong analysis

**what language is your code written in**
Python

**The code you submit/run**
```
class Solution(object):
    def kClosest(self, points, K):
        dist = lambda i: points[i][0]**2 + points[i][1]**2

        def sort(i, j, K):
            # Partially sorts A[i:j+1] so the first K elements are
            # the smallest K elements.
            if i >= j: return

            # Put random element as A[i] - this is the pivot
            k = random.randint(i, j)
            points[i], points[k] = points[k], points[i]

            mid = partition(i, j)
            if K < mid - i + 1:
                sort(i, mid - 1, K)
            elif K > mid - i + 1:
                sort(mid + 1, j, K - (mid - i + 1))

        def partition(i, j):
            # Partition by pivot A[i], returning an index mid
            # such that A[i] <= A[mid] <= A[j] for i < mid < j.
            oi = i
            pivot = dist(i)
            i += 1

            while True:
                while i < j and dist(i) < pivot:
                    i += 1
                while i <= j and dist(j) >= pivot:
                    j -= 1
                if i >= j: break
                points[i], points[j] = points[j], points[i]

            points[oi], points[j] = points[j], points[oi]
            return j

        sort(0, len(points) - 1, K)
        return points[:K]
```

**Expected behavior**
Time Complexity: O(N) in average case complexity, where N is the length of points.

Space Complexity: O(N).

This is the analysis provided.

In time complexity only the average case is mentioned however the worst case run time of O(n^2) is a significant piece of information that should not be withheld.

In space complexity the two ways it could be O(n) is by considering the space taken by the result which should not be counted as observed in [238](https://leetcode.com/problems/product-of-array-except-self/) or it could be considering stack space due to recursion which will only be O(n) in the worst case (in contradiction with time complexity).

Either the average space of O(logn) should be mentioned along with worst case of O(n) or only the average or worst case should be mentioned. As a side note it can implemented in O(1) space by doing iterative quickselect for which I can provide the code if required.

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @
Thank you for the contribution, the time complexity is updated. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
