### ISSUE TITLE
590 

### ISSUE THREAD

**Issue by ben-burlingham** [LeetCode-Feedback/LeetCode-Feedback#2621]
https://leetcode.com/problems/n-ary-tree-postorder-traversal/

#### Your LeetCode username
ben-burlingham

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
A postorder traversal of [1,6] should result in [6,1].

The Leetcode engine reports only [1].  There seems to be a bug in its implementation.

The attached image shows the test case, the correct output, and the Leetcode engine's erroneous calculation.

#### Screenshots
![image](https://user-images.githubusercontent.com/6643933/110221054-c1f57480-7e7e-11eb-996e-c69c02c005cf.png)

#### Code you used for Submit/Run operation
To reproduce the problem, just use a test case of `[6, 1]`.

Here's an accepted solution which fails that test case:

```
class Solution {
    public List<Integer> postorder(Node root) {
        List<Integer> result = new ArrayList<Integer>();
        if (root == null) {
            return result;
        }
        
        Stack<Node> stack = new Stack<>();
        stack.add(root);
        
        while (stack.empty() == false) {
            Node node = stack.pop();
            result.add(node.val);
            
            for (Node child : node.children) {
                stack.add(child);
            }
        }

        
        Collections.reverse(result);
        
        return result;
    }
}
```

#### Language used for code
Java

**Comment by lc-kay** [comment]
Hi @ben-burlingham 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @ben-burlingham 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
