### ISSUE TITLE
Missing Test Case - 1765. Map of Highest Peak

### ISSUE THREAD

**Issue by hdogan84** [LeetCode-Feedback/LeetCode-Feedback#2622]
#### Category of the bug
- [x] Question 
- [ ] Solution
- [ ] Language

Input test case has a bug: This particular input: [[0,0],[1,1],[1,0]]
In the Example test, isWater array is given as Matrix, not as a index pair and whether it is 1 or 0: 
The test case is trying to give water pools at [1,1] and [1,0]. THe right input format should have been : 
[0,0]
[1,1]

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@hdogan84 Please provide a screenshot of the issue you are describing. Thank you for your time.

**Comment by lc-kay** [comment]
Hi @hdogan84 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
