### ISSUE TITLE
Need clarification: 343. Integer Break

### ISSUE THREAD

**Issue by glorialearnscoding** [LeetCode-Feedback/LeetCode-Feedback#2623]
Given a positive integer n, break it into the sum of at least two positive integers and maximize the product of those integers. Return the maximum product you can get.

Example 2:

Input: 10
Output: 36
Explanation: 10 = 3 + 3 + 4, 3 × 3 × 4 = 36.

We were asked to give at least two positive numbers, but what about the others? Can they be negative?
I guess you assume that negative values should not be considered in this question. But the sentence you wrote didn't prevent me from thinking about examples like this:

Input: 10
Output: 110000000
Explanation: 10 = (-100) + (-100) + (100) + (110), (-100) x (-100) x (100) x (110) = 110000000
I break 10 into two positive numbers 110, 100, and two negative numbers -100, -100.

So please revise your description. Thank you!

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
Hi @glorialearnscoding 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @glorialearnscoding 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
