### ISSUE TITLE
Missing Test Case - 53. Maximum Subarray

### ISSUE THREAD

**Issue by elliptic1** [LeetCode-Feedback/LeetCode-Feedback#2624]
#### Your LeetCode username
elliptic1

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Examples 2, 3, 4, 5 all demonstrate that if you only have one number as input, that number is the solution. There should be only one of those examples and more examples with multiple numbers.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
Hi @elliptic1 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @elliptic1 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
