### ISSUE TITLE
Missing Test Case - 839. Short Encoding of Words - "feipyxx" contains "e"

### ISSUE THREAD

**Issue by Denysss** [LeetCode-Feedback/LeetCode-Feedback#2627]
#### Your LeetCode username
Denysss

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language

#### Description of the bug
"feipyxx" contains "e", so there is no need to add "e#"

Input: words = ["feipyxx", "e"]
Valid encoding: s = "feipyxx#"
Indices = [0, 1]
Actual value: Output = 10
Expected value: Output = 8

#### Code you used for Submit/Run operation
```
class Solution {
    
    private static final String refEnd = "#";
    
    public int minimumLengthEncoding(String[] words) {
        StringBuilder sb = new StringBuilder();

        for (int l = 7; l > 0; l--) {
            for (String word : words) {
                if (word.length() == l && sb.indexOf(word) < 0) {
                    sb.append(word).append(refEnd);
                }
            }
        }

        return sb.length();
    }
}
```

#### Language used for code
Java

#### Expected behavior
The testcase (input = ["feipyxx", "e"]) should have output = 8

#### Screenshots
![839](https://user-images.githubusercontent.com/15123446/110231495-bc506b00-7f20-11eb-844a-6ef59da52fb9.png)

**Comment by Denysss** [comment]
it's my fault

**Comment by sam9111** [comment]
Hi! I ran into the same problem when I was trying to submit my code and I was hoping that this was indeed really a bug because I still cannot figure out how this test case is even possible. Could you please explain it to me if you don't mind?
