### ISSUE TITLE
Solution fails test case: longest-palindromic-substring

### ISSUE THREAD

**Issue by VarunTvlka** [LeetCode-Feedback/LeetCode-Feedback#263]
**What kind of the bug**
- [ ] problem
- [x] solution
- [ ] language

**Describe the bug**

**what language is your code written in**
Java

**The code you submit/run**
```
public String longestPalindrome(String s) {
    if (s == null || s.length() < 1) return "";
    int start = 0, end = 0;
    for (int i = 0; i < s.length(); i++) {
        int len1 = expandAroundCenter(s, i, i);
        int len2 = expandAroundCenter(s, i, i + 1);
        int len = Math.max(len1, len2);
        if (len > end - start) {
            start = i - (len - 1) / 2;
            end = i + len / 2;
        }
    }
    return s.substring(start, end + 1);
}

private int expandAroundCenter(String s, int left, int right) {
    int L = left, R = right;
    while (L >= 0 && R < s.length() && s.charAt(L) == s.charAt(R)) {
        L--;
        R++;
    }
    return R - L - 1;
}
```

**Expected behavior**
This is the code from the leetcode solution.It should pass the test case.

**Screenshots**
The solution for the above problem , with approach expand around center does not work and pass the test case and requires a revision. The test cases expect the first longest palindrome to be returned.

**Additional context**
Here is my proposed solution

```
public String longestPalindromicSubstring(String s) {
if (s == null || s.length() == 0) {
return "";
}

int start = 0, end = 0, maxLen = 0;

for (int i = 0; i < s.length(); i++) {
int len1 = expandAroundCenter(s, i, i);
int len2 = expandAroundCenter(s, i, i + 1);

int len = Math.max(len1, len2);
if(maxLen < len) {
start = i - (len -1)/2;
end = i + len/2;
maxLen = len;
}
}

return s.substring(start, end + 1);
}

private int expandAroundCenter(String s, int left, int right) {
int L = left;
int R = right;
while (L >= 0 && R < s.length() && s.charAt(L) == s.charAt(R)) {
L--;
R++;
}
return R - L - 1;
}
```

**Comment by CooperCooperCooper** [comment]
Hi @VarunTvlka ,
Thank you for your time. To help us further assess this issue, can you please share which test case(s) your code is not passing?

**Comment by CooperCooperCooper** [comment]
Hi @VarunTvlka ,
Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
