### ISSUE TITLE
Wrong Test Case - 189. Rotate Array

### ISSUE THREAD

**Issue by gunjan95** [LeetCode-Feedback/LeetCode-Feedback#2635]
#### Your LeetCode username

gunjan_acharya

#### Category of the bug

- [* ] Solution

#### Description of the bug

Test case ans is incorrect.
Input:
[1,2,3,4,5,6,7]
3
Output:
[4,5,6,7,1,2,3]
Expected:
[5,6,7,1,2,3,4]

Expected ans is for k = 4 and in test case input it is 3.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by stormsunshine** [comment]
The test case is correct. Note that the array is rotated to the **right** by k steps.

**Comment by lc-kay** [comment]
@gunjan95 As @stormsunshine said the expected output is correct. Please check out this discuss post as well https://leetcode.com/problems/rotate-array/discuss/54716/Does-anyone-think-the-example-in-the-description-has-problem Thank you for your time.
