### ISSUE TITLE
Website text not correctly formatted. 

### ISSUE THREAD

**Issue by SuguruChhaya** [LeetCode-Feedback/LeetCode-Feedback#2636]
#### Your LeetCode username

suguruchhaya@gmail.com

#### Category of the bug
- [x ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Text on https://leetcode.com/problems/minimum-size-subarray-sum/solution/ is not correctly formatted and is difficult to read. There are many "\text{}" which I assume should be formatted somehow.

**Comment by NishadKumar** [comment]
Nice catch @SuguruChhaya.

**Comment by lc-kay** [comment]
Hi @SuguruChhaya 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @SuguruChhaya 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
