### ISSUE TITLE
Weak testcase in Jump Game III

### ISSUE THREAD

**Issue by as-rawat** [LeetCode-Feedback/LeetCode-Feedback#264]
**Describe the bug**
Testcases aren't strong for #1306

**what language is your code written in**
C++

**The code you submit/run**
`

    bool canReach(vector<int>& arr, int start) {
        
        if(!arr[start])
            return true;
        
        queue<int> q;
        q.push(start);

        int i = 0;
        while(!q.empty() && i < 2 * arr.size())
        {
            int v = q.front();
            q.pop();
            
            if(!arr[v])
            {
                while(!q.empty())
                    q.pop();
                
                return true;
            }
            
            int l = v - arr[v];
            int r = v + arr[v];

            if(l >= 0)
                q.push(l);
            
            if(r < arr.size())
                q.push(r);
            
            i++;
        }
        
        return false;
    }
```

**Expected behavior**
The program should give "true" for following input.
[1,1,1,1,1,1,1,1,0]
3

**Link for the problem**
https://leetcode.com/problems/jump-game-iii

**Comment by CooperCooperCooper** [comment]
Hi @as-rawat ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
