### ISSUE TITLE
Missing Test Case - 706. Design HashMap

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#2640]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

An accepted solution fails on the following testcase:
[706.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6099118/706.txt)

#### Code you used for Submit/Run operation

```
int S=0;
class MyHashMap {
public:
    /** Initialize your data structure here. */
    const static int N = 20011, L = 20;  //(int)log2(N)
    int hash_key[N],hash_value[N];

    MyHashMap() {
        memset(hash_key, -1, sizeof(hash_key));
    }
    ~MyHashMap() {
        //cout<<S<<endl;
    }

    int find(int key){
        int t = key % N, cnt=0;
        while(hash_key[t] != key && hash_key[t] != -1){++S;
            t ++; if (++cnt>L)break;
            if(t == N) t  = 0;
        }
        return t;
    }

    /** value will always be non-negative. */
    void put(int key, int value) {
        int t  = find(key);
        hash_key[t] = key;
        hash_value[t] = value;
    }
    
    /** Returns the value to which the specified key is mapped, or -1 if this map contains no mapping for the key */
    int get(int key) {
        int t = find(key);
        if(hash_key[t] == -1) return -1;
        return hash_value[t];
    }
    
    /** Removes the mapping of the specified value key if this map contains a mapping for the key */
    void remove(int key) {
        int t = find(key);
        if(hash_key[t] != -1) hash_key[t] = -2;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The last integer of the expected output array should be -1, but the code outputs 1.

#### Screenshots

![1](https://user-images.githubusercontent.com/11583428/110279196-4d195c00-7f9e-11eb-9c42-2c9992b2ad2d.png)

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
