### ISSUE TITLE
 1647. Minimum Deletions to Make Character Frequencies Unique

### ISSUE THREAD

**Issue by spandan9898** [LeetCode-Feedback/LeetCode-Feedback#2641]
from collections import Counter
class Solution(object):
    def minDeletions(self, s):
        """
        :type s: str
        :rtype: int
        """
        count = 0
        c = Counter(s)
        d = {}
        for i in c.items():
            if i[1] in d.values():
                a = i[1]
                while a in d.values():
                    a -= 1
                    if a == 0:
                        break
                count += i[1]-a
                d[i[0]] = a
                
            else:
                d[i[0]] = i[1]
        return count

**Comment by lc-kay** [comment]
@spandan9898 Please provide more details on the content-related issue. Thank you!

**Comment by lc-kay** [comment]
Hi @spandan9898 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
