### ISSUE TITLE
Missing Test Case - 1454. Remove Palindromic Subsequences

### ISSUE THREAD

**Issue by Gwart** [LeetCode-Feedback/LeetCode-Feedback#2642]
#### Your LeetCode username

gwart

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

The server's solution is not correct. If you try to use testcase "baabba", the output has to be "3", but it is "2".

#### Code you used for Submit/Run operation

```
class Solution 
{
public:
//it doesn't matter
    int removePalindromeSub(string s) 
    {
         return 0;
    }
};
```

#### Language used for code

C++

#### Expected behavior

If you try to use testcase "baabba", the output has to be "3", but it is "2".

#### Screenshots

![alt text](https://i.ibb.co/MMZ77WK/image.png)

**Comment by Bankde** [comment]
The "subsequence" has different meaning than "substring". You can check out the discussion part.

Adding your testcase into the example will be pretty much giving out the answer (even though your test case is so simple). That's why I personally hate this problem.

**Comment by NishadKumar** [comment]
I agree with @Bankde. There is a significant difference and the problem should have had a clearer description.

**Comment by Gwart** [comment]
@Bankde @NishadKumar thank you, now i get it. But it's really hard to catch the problem, the description isn't great enough.
