### ISSUE TITLE
【336. 回文对】缺少数据范围

### ISSUE THREAD

**Issue by sunznx** [LeetCode-Feedback/LeetCode-Feedback#2643]
**sunznx**
**Bug 类型**
- [ ] 题目：https://leetcode-cn.com/problems/palindrome-pairs/

**描述**
缺少数据范围，英文版本是有的

**Comment by PsiACE** [comment]
很高兴看到您的反馈，目前题面中缺少的 **示例 3** 和 **提示** 都已经与英文同步更新啦，感谢您对「力扣」的支持和喜爱。

**Comment by feiceh** [comment]
@sunznx 你好，当前题目描述已更新，ID：sunznx  给予积分奖励，请查收。
