### ISSUE TITLE
Missing Test Case - 1454. Remove Palindromic Subsequences

### ISSUE THREAD

**Issue by miketav2016** [LeetCode-Feedback/LeetCode-Feedback#2645]
#### Your LeetCode username
Mikhail Tavturin

#### Category of the bug
- [ ] Question
- [+] Solution
- [ ] Language

#### Description of the bug

case 25 : "bbaabaaa" it solve look like  => bb + aabaa + a = 3
But expected: 2

#### Code you used for Submit/Run operation

```
object Solution {
    def removePalindromeSub(s: String): Int = {
         def isPal(str: String) = {
      if (str.length == 1) true
      else {
        str == str.reverse
      }
    }

    def maxPal(string: String): Int = {
      string.foldLeft(("", "")) { case ((acc,tmp), cur) =>
        if (isPal(tmp + cur))
          (tmp + cur, tmp + cur)
        else
          (acc, tmp + cur)
      }._1.length
    }

    s match {
      case s1 if s1.isEmpty || s1 == "" => 0
      case _ => 1 + removePalindromeSub(s.drop(maxPal(s)))
    }
    }
}
```

#### Language used for code
Scala 2.13

**Comment by Leader-board** [comment]
It's a _subsequence_, not a _substring_. Tripped me too.

**Comment by miketav2016** [comment]
> It's a _subsequence_, not a _substring_. Tripped me too.

Oh... thank!
