### ISSUE TITLE
Missing Test Case - 1454. Remove Palindromic Subsequences

### ISSUE THREAD

**Issue by govindev** [LeetCode-Feedback/LeetCode-Feedback#2647]
#### Your LeetCode username

vgovindaraju

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
solution

#### Description of the bug

one of the test case is wrong, because of which I am getting a Wrong Answer

#### Code you used for Submit/Run operation

```
class Solution {
    public int removePalindromeSub(String s) {
        if (s.equals(""))
			return 0;
		if (isPalindrome(s)) {
			return 1;
		}
        int z = 1;
        int n = s.length();
        while(z<n) {
            if(isPalindrome(s.substring(0, n-z)) && isPalindrome(s.substring(n-z))) 
                return 2;
            z++;
        }
        return 0;
    }
    
    private boolean isPalindrome(String s) {
        if (s.length() == 1) {
			return true;
		}
		for (int i = 0, j = s.length() - 1; i < s.length() && j > 0; i++, j--) {
			if (i >= j)
				return true;
			if (s.charAt(i) != s.charAt(j)) {
				return false;
			}
		}
		return true;
    }
}
```

#### Language used for code

Java

#### Expected behavior

for the input 'bbaabaaa', output should be 0 because this not a palindrome and there are no 2 subsequent palindromes which can form the input string. Expected answer however is 2 which is wrong.
for the input 'bbaabaa', output can be 2 but not for 'bbaabaaa'

#### Screenshots

![Screenshot 2021-03-08 at 8 17 06 PM](https://user-images.githubusercontent.com/8542751/110336873-4dbbfc00-804b-11eb-874b-93d0c8863ef8.png)

**Comment by lc-kay** [comment]
@govindev The expected output is correct. Please check out this post: https://leetcode.com/problems/remove-palindromic-subsequences/discuss/490352/Java-Use-the-Trick-%3A-the-input-string-only-consists-of-letters-'a'-and-'b'!! In addition, keep in mind that this is a subsequence problem, not a substring. Thank you for your time.
