### ISSUE TITLE
判题错误

### ISSUE THREAD

**Issue by GuHuining** [LeetCode-Feedback/LeetCode-Feedback#2648]
**你的 LeetCode 用户名**
huining

**Bug 类型**
- [ ] 题目 https://leetcode-cn.com/problems/restore-ip-addresses/
**描述**
将测试用例改为“0000”时，输出与预期结果相同，为["0.0.0.0"]。但是提交题目后，相同的测试数据，结果不正确，也与此前的运行结果不一样

**你使用的语言**
Golang

**代码**

var results []string

func restoreIpAddresses(s string) []string {
	helper("" , s, 4)
	return results
}

func helper(head string, tail string, num int){
	if num == 0 && tail == "" {
		results = append(results, head)
		return
	} else if num == 0 {
		return
	}
	if tail[:1] == "0" {
		if head == "" {
			head = "0"
		} else {
			head = head + ".0"
		}
		helper(head, tail[1:], num-1)
	} else {
		for i := 1; i <= 3 && len(tail) - i >= num-1; i++ {
			if n, _ := strconv.Atoi(tail[:i]); n <= 255 && n > 0 {
				if head == "" {
					head = tail[:i]
				} else {
					head = head + "." + tail[:i]
				}
				helper(head, tail[i:], num-1)
				head = strings.Join(strings.Split(head, ".")[:4-num], ".")
			}
		}
	}
}

**期望行为**
当输入为"0000"时，输出["0.0.0.0"]

**屏幕截图**
![1](https://user-images.githubusercontent.com/44405103/110337449-d7ed6b80-801d-11eb-867a-cb81873c75a7.png)
![2](https://user-images.githubusercontent.com/44405103/110337452-d8860200-801d-11eb-8709-bbade4bf3004.png)

**上下文**
输出的错误结果中，前两个是样例1中的结果，后一个是正确结果。不知道这其中有什么关联。

**Comment by feiceh** [comment]
你好，建议再仔细检查并调试一下代码，推荐阅读：「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」 获得更多帮助。

同时也可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
