### ISSUE TITLE
testing result and submitting results are different for the same test case

### ISSUE THREAD

**Issue by bittukumarray** [LeetCode-Feedback/LeetCode-Feedback#265]
**What kind of the bug**
- [x] problem
   **637. Average of Levels in Binary Tree**
    _Given a non-empty binary tree, return the average value of the nodes on each level in the form of an array._
- [x] solution
_I traversed in level order and while traversing, whenever I found a non-null value at the given level, I sum it up and increase the count by one, after traversing all the node for the level, finally, it returns the sum and just before pushing it back to the vector, I divided the sum by the count to get the average for each level of the binary tree._
- [x] language
**C++**

**Describe the bug**

_I completed the program in C++ and when I submitted this, the program only returns the last element of the vector but it should return the entire vector, and while testing it is giving success for the same test case which upon submitting gives the wrong answer. Also, just before returning the vector, I printed all the values and the values are correct but the same value upon returning gives different results._

**what language is your code written in**
C++

**The code you submit/run**
```
// Average of Levels in Binary Tree

class Solution {
public:
    
    int helper(TreeNode* root, int sum, int &count, int end, int index){
        if(root==NULL){
           return 0; 
        }
        if(end==index){
            count++;
            return root->val;
        }
        return sum + helper(root->left, sum, count, end, index+1)+helper(root->right, sum, count, end, index+1);
        
    }
    
    vector<double> averageOfLevels(TreeNode* root) {
        vector<double> vec;
        int i=0;
        while(true){
            int count=0;
            double sum;
            sum=(double)(helper(root, 0, count, i, 0));
            // cout<<sum<<endl;
            i++;
            if(sum){
                vec.push_back(sum/count);
            }
            else
                break;
        }
        for(int i=0;i<vec.size();i++){
            cout <<vec[i]<<" ";
        }
        return vec;
    }
};
```

**Expected behavior**
_The program should return the entire vector instead of the last element of the vector. Also, the program should give the same result in both testing and submitting cases.

**Screenshots**
![Screenshot from 2020-05-02 09-10-58](https://user-images.githubusercontent.com/37700371/81132311-90b0cd00-8f6b-11ea-8a45-057cffcc7b2b.png)
![Screenshot from 2020-05-02 08-53-07](https://user-images.githubusercontent.com/37700371/81132314-93abbd80-8f6b-11ea-8068-6ab28bd9fd6e.png)

**Additional context**

**Comment by CooperCooperCooper** [comment]
Hi @bittukumarray ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @bittukumarray ,
Thank you for your time. We've fixed this issue and the outputs and expected results are back to normal now. 

This issue is found to be non-content-related (the issue stems from an origin away from the content on this problem); therefore, it's not valid for content contribution reward. We encourage you to share other content-related issues here with us for valid content contribution rewards. We appreciate your support and understanding.
