### ISSUE TITLE
Missing Test Case - 1454. Remove Palindromic Subsequences

### ISSUE THREAD

**Issue by MedhaRudra** [LeetCode-Feedback/LeetCode-Feedback#2651]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Submission result shows wrong answer even though output is correct.

#### Code you used for Submit/Run operation

```

```

#### Language used for code

Java

#### Expected behavior

For the test case : "bbaabaaa", minimum 3 palindromes (i.e "bb", "aabaa", and "a") need to be removed to make the string empty. But, the test case shows expected answer as 2.

**Comment by archit11111** [comment]
Remove all  `a`s in first step and all  `b`s in the second step. So, at max 2 steps are required. It is a palindromic subsequence problem and not a substring problem
