### ISSUE TITLE
Missing Test Case - 1454. Remove Palindromic Subsequences

### ISSUE THREAD

**Issue by andrey-canon** [LeetCode-Feedback/LeetCode-Feedback#2652]
#### Your LeetCode username
andrey-canon

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Submission result shows wrong answer even though output is correct.

#### Code you used for Submit/Run operation

```
class Solution:
    def removePalindromeSub(self, s: str) -> int:
        
        steps = 0
        
        while s:
            
            for i in range(len(s)):
                s1 = s[: len(s)-i]
                r_s1 = s1[::-1]
                
                if s1 == r_s1:
                    s = s[len(s)-i:]
                    steps += 1
                    break
                    
        return steps
```

#### Language used for code
python 3

#### Expected behavior
For the test case : "babaabaaa", minimum 3 palindromes (i.e "bab", "aabaa", and "a") need to be removed to make the string empty. But, the test case shows expected answer as 2.

#### Screenshots
![image](https://user-images.githubusercontent.com/36200299/110347481-a913cd00-7ffe-11eb-9e9c-de0195537721.png)

**Comment by archit11111** [comment]
Remove all  `a`s in first step and all  `b`s in second step. So, at max 2 steps are required. It is a palindromic subsequence problem and not a substring problem.

**Comment by andrey-canon** [comment]
@archit11111 since there are only two letters that means that there are only three options 0, 1 or 2, 0 empty string, 1 a palindromic string and 2 for the other cases... With that in mind the code works however it is the simplest exercise that I have ever done with the worst description 
```
class Solution:
    def removePalindromeSub(self, s: str) -> int:
        
        if not s:
            return 0
        
        return 1 if s[::-1] == s else 2       

```
 
![image](https://user-images.githubusercontent.com/36200299/110380278-dcb61d80-8025-11eb-977b-9047872bef96.png)

**Comment by archit11111** [comment]
@andrey-canon the description was fine. It's just that people get confused between substring and subsequence(I tried solving it substring way as well on 1st try).

**Comment by lc-kay** [comment]
@andrey-canon In addition to @archit11111 comment, please check out The expected output is correct. Please check out this post: https://leetcode.com/problems/remove-palindromic-subsequences/discuss/490352/Java-Use-the-Trick-%3A-the-input-string-only-consists-of-letters-'a'-and-'b'!! on why is this the correct output. Thank you for your time!
