### ISSUE TITLE
Missing Test Case - 1454. Remove Palindromic Subsequences

### ISSUE THREAD

**Issue by Mohitgupta943** [LeetCode-Feedback/LeetCode-Feedback#2653]
#### Your LeetCode username
mohitgupta943

#### Category of the bug
Solution
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

For the input "aabaabba" the output should be 3 but the expected output being shown is 2 which I think is wrong.

#### Code you used for Submit/Run operation

```
class Solution {
    
    public static int sol(String s,int si,int li){
        if(si>li){
            return 0;
        }
        if(si==li){
            return 1;
        }
        while(si<=li && s.charAt(si)==s.charAt(li)){
            si++;
            li--;
        }
        int tsi=si+1;
        int tli=li-1;
        while(tsi<=li && s.charAt(si)==s.charAt(tsi)){
            tsi++;
        }
         while(tli>=si && s.charAt(li)==s.charAt(tli)){
            tli--;
        }
        int left=1+sol(s,tsi,li);
        int right=1+sol(s,si,tli);
        return Math.min(left,right);
        
    }
    public int removePalindromeSub(String s) {
        
        return sol(s,0,s.length()-1);
        
    }
}
```

#### Language used for code
Java

#### Expected behavior

For the input "aabaabba" the output should be 3 but the expected output being shown is 2 which I think is wrong.

**Comment by archit11111** [comment]
Remove all `a`s in first step and all `b`s in second step. So, at max 2 steps are required. It is a palindromic subsequence problem and not substring

**Comment by lc-kay** [comment]
@Mohitgupta943 In addition to @archit11111 comment, please check out The expected output is correct. Please check out this post: https://leetcode.com/problems/remove-palindromic-subsequences/discuss/490352/Java-Use-the-Trick-%3A-the-input-string-only-consists-of-letters-'a'-and-'b'!! on why is this the correct output. Thank you for your time!

**Comment by Mohitgupta943** [comment]
Got it... Thank you guys.
