### ISSUE TITLE
Missing Test Case - 1454. Remove Palindromic Subsequences

### ISSUE THREAD

**Issue by AndreyKamenskiy** [LeetCode-Feedback/LeetCode-Feedback#2654]
#### Your LeetCode username

AndreyKamenskiy

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

incorrect expected answer for custom test "aabbab". Answer must be 3 but received 2. 

#### Code you used for Submit/Run operation

```
//Remove Palindromic Subsequences
class Solution {
    public int removePalindromeSub(String s) {
        int len = s.length();
        if (len < 2) {
            return len;
        } 
        byte[][] dp = new byte[len][];
        dp[0] = new byte[1];
        dp[0][0] = 1;
        for (int i = 1; i < len; ++i) { // substring's end
            dp[i] = new byte[i + 1];
            dp[i][i] = 1;
            if (s.charAt(i) == s.charAt(i-1)) {
                dp[i][i - 1] = 1;
            } else {
                dp[i][i - 1] = 2;
            }
            for (int j = i - 2; j >= 0; --j) { // substring's start
                if (s.charAt(j) == s.charAt(i)) {
                    dp[i][j] = dp[i - 1][j + 1];
                } else {
                    byte min = Byte.MAX_VALUE;
                    for (int k = j; k < i; ++k) {
                        min = (byte)Math.min(min, dp[k][j] + dp[i][k + 1]);
                    }
                    dp[i][j] = min;
                }
            }       
        }
        return dp[len - 1][0];
    }
}
```

#### Language used for code

Java

#### Expected behavior

In case "aabbab" we cannot clear the string for 2 steps. Only for tree.

1. a(abba)b -> 2. (a)b - > 3. (b) - > "" // in the parentheses there is palindrome to delete.

#### Screenshots

![image](https://user-images.githubusercontent.com/52415618/110372246-1d7e5880-805f-11eb-8ab4-eb48748a55b8.png)

**Comment by archit11111** [comment]
The test case "aabbab" can be solved in two steps - aabbab -> 1. aaa - > 2. "" . You are required to clear a palindromic subsequence in one move (not a substring).

**Comment by AndreyKamenskiy** [comment]
yeh. my mistake. Thank you
