### ISSUE TITLE
Test Cases Not Available Before Submission

### ISSUE THREAD

**Issue by dmaixner93** [LeetCode-Feedback/LeetCode-Feedback#2655]
#### Your LeetCode username

dmaixner93

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

After doing a few LeetCode problems today, I have encountered unexpected test cases that made my submissions wrong. I would imagine if the test cases are present when submitting and listed while creating a solution, there is an issue rendering or missing data.

I specifically experienced this on two 'easy' problems (Unnecessary justification - Before you judge - I have neglected to stay familiar with LeetCode type problems in my career). The problems were `Remove Duplicates from Sorted Array` and `Reverse Integer`

#### Code you used for Submit/Run operation

```
/** removeDuplicates */
var removeDuplicates = function(nums) {
  var i = 0;
  
  const getLastInstance = (num) => {
    if (i >= nums.length) return;
    var end = nums.lastIndexOf(num);
    if (end !== i) {
      i = nums.splice(i, (end - i)).length;
    } else {
      i++;
    }
    getLastInstance(nums[i]);
  }
  
  getLastInstance(nums[i]);
  return nums.length;
};

/** un-listed test case: [-1,0,0,0,0,3,3] */
```

#### Language used for code

JavaScript

#### Expected behavior

There is a clear issue in my solution above. I was unaware of the issue until my submission failed, because the test cases I had 
tested with (`[1,1,2]` and `[0,0,1,1,1,2,2,3,3,4]`) result in successes.

I expected to be able to run code with all test cases before submitting the problem. Instead, I was surprised to find test cases that did not work (I also understand it should 'theoretically' be able to handle the unexposed test cases, but you know how it goes).

**Comment by lc-kay** [comment]
@dmaixner93 Thank you for reaching out to us. However, the main purpose of LeetCode is for users to improve their coding skills and prepare for interviews. And during an actual interview, it is impossible for the interviewer to show all the test cases before submission. Therefore, to better their coding practice, they should consider all the scenarios and the possible test cases before submission. And if the submission fails, they should see the failed test case and review why they didn't think of those test cases. LeetCode is designed this way to help users improve their coding skills. Nonetheless, we still appreciate your feedback and will reconsider our design if more users raise the same concerns.

**Comment by dmaixner93** [comment]
> @dmaixner93 Thank you for reaching out to us. However, the main purpose of LeetCode is for users to improve their coding skills and prepare for interviews. And during an actual interview, it is impossible for the interviewer to show all the test cases before submission. Therefore, to better their coding practice, they should consider all the scenarios and the possible test cases before submission. And if the submission fails, they should see the failed test case and review why they didn't think of those test cases. LeetCode is designed this way to help users improve their coding skills. Nonetheless, we still appreciate your feedback and will reconsider our design if more users raise the same concerns.

Thanks for the explanation. I do agree with everything you stated.

I would like to ask why it would be "impossible" for the interviewer to know? Are the test cases arbitrarily generated or selected out of a large volume of data per instance (Specifically referring to LeetCode)? Referring to my instance, if this were the case and the array `[-1,0,0,0,0,3,3]` was never "chosen" for testing or a similar variation, then my answer would have been Accepted and the interviewer may have also not known that there was an issue.

**Comment by lc-kay** [comment]
@dmaixner93 You're welcome. Even though if the interviewer may not have thought or known about that possible test case, it is best to prepare for all possible test cases going into an interview. Therefore, LeetCode does not show all test cases so our users can best prepare for their interviews. Lastly, a kind reminder that our Github Repo is for content-related issues. For any future feedback, please reach out to us through our help center or support@leetcode.com. Thank you for your time.
