### ISSUE TITLE
143. Reorder List Example 2 Graphic is Incorrect

### ISSUE THREAD

**Issue by lok23** [LeetCode-Feedback/LeetCode-Feedback#2656]
#### Your LeetCode username
lok23

#### Category of the bug
Question Graphic

#### Description of the bug
The graphic for leetcode problem “reorder list” example 2 has the order incorrect drawn. 
 
The correct order should be 1 -> 5 -> 2 -> 4 -> 3

#### Code you used for Submit/Run operation
NA

#### Language used for code
NA

#### Expected behavior
The graphic should be drawn differently

#### Screenshots
![image](https://user-images.githubusercontent.com/45181211/110379401-c78cbf00-8024-11eb-8727-11f47378c377.png)

#### Additional context
NA

**Comment by lc-kay** [comment]
Hi @lok23 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @lok23 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
