### ISSUE TITLE
"Example testcases" bug: 623. Add One Row to Tree

### ISSUE THREAD

**Issue by Leader-board** [LeetCode-Feedback/LeetCode-Feedback#2659]
#### Your LeetCode username
Leaderboard

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Clicking "Examples Testcase" shows only one test case, despite being two in the question itself.

#### Code you used for Submit/Run operation

Not applicable

#### Language used for code

Not applicable
#### Expected behavior

Two test cases should appear.

#### Screenshots

Only test case that shows up:
```
[4,2,6,3,1,5]
1
2
```

**Comment by lc-kay** [comment]
Hi @Leader-board 
Thank you for your time. We've fixed this issue. We appreciate your support!
