### ISSUE TITLE
572. Subtree of Another Tree - weak testcase

### ISSUE THREAD

**Issue by ishikin** [LeetCode-Feedback/LeetCode-Feedback#266]
**What kind of the bug**
- [ ] problem
- [ ] solution
- [ ] language
- [x] testcase

**Describe the bug**
Incorrect solution is accepted

**what language is your code written in**
Python

**The code you submit/run**
```
class Solution:
    def isSubtree(self, s: TreeNode, t: TreeNode) -> bool:
        if not s or not t:
            return not s and not t
        if s.val == t.val and self.isSubtree(s.left, t.left) and self.isSubtree(t.right, s.right): 
            return True
        left = self.isSubtree(s.left, t) if s.left else False
        right = self.isSubtree(s.right, t) if s.right else False
        return left or right
```

**Expected behavior**
I expect this solution to not be accepted as it fails on testcase

[0,1,2,3,4,5,6,7,8]
[0,3,2,7,8,5,6]

**Comment by CooperCooperCooper** [comment]
Hi @ishikin ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
