### ISSUE TITLE
Invalid Test Case - 623. Add One Row to Tree

### ISSUE THREAD

**Issue by kk3399** [LeetCode-Feedback/LeetCode-Feedback#2661]
value 0 for d is accepted

#### Your LeetCode username
entangled

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
d should be greater than 0, but 0 is accepted in test

#### Code you used for Submit/Run operation

```
/**
 * Definition for a binary tree node.
 * type TreeNode struct {
 *     Val int
 *     Left *TreeNode
 *     Right *TreeNode
 * }
 */
func addOneRow(root *TreeNode, v int, d int) *TreeNode {
    return addOneRowHelper(root, v, d, true)
}

func addOneRowHelper(root *TreeNode, v int, d int, isLeft bool) *TreeNode{
    if d == 1 {
        if root == nil {
            return &TreeNode{d, nil, nil}
        }
        newNode := &TreeNode{d, nil, nil}
        if isLeft {
            newNode.Left = root
        } else {
            newNode.Right = root
        }
        return newNode
    }
    if root == nil {return nil}
    root.Left = addOneRowHelper(root.Left, v, d-1, true)
    root.Right = addOneRowHelper(root.Right, v, d-1, false)
    return root
}
```

#### Language used for code
GO

**Comment by lc-kay** [comment]
@kk3399 Please provide a screenshot of the issue. Thank you!

**Comment by kk3399** [comment]
attaching screenshot
![image](https://user-images.githubusercontent.com/1585467/110532811-ed789900-80e2-11eb-9b95-361cdd0be139.png)

**Comment by lc-kay** [comment]
Hi @kk3399 
Thank you for submitting that, I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @kk3399 
Thank you for your time. The team reviewed your report and fixed those validators. We appreciate your support!
