### ISSUE TITLE
Missing Test Case - 914. X of a Kind in a Deck of Cards

### ISSUE THREAD

**Issue by karnurmax** [LeetCode-Feedback/LeetCode-Feedback#2663]
#### Category of the bug
- [x] Question

- [ ] Solution

- [ ] Language

#### just an extra character

just an extra symbol in the "example 2" area
output: false`

remove plz :)

**Comment by lc-kay** [comment]
Hi @karnurmax 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @karnurmax 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
