### ISSUE TITLE
Missing Test Case - 1786. Number of Restricted Paths From First to Last Node

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#2664]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

An accepted solution gets Time Limit Exceeded on the following testcase:
220
[[2,220,1],[3,220,1],[2,4,1],[3,4,1],[5,4,1],[6,4,1],[5,7,1],[6,7,1],[8,7,1],[9,7,1],[8,10,1],[9,10,1],[11,10,1],[12,10,1],[11,13,1],[12,13,1],[14,13,1],[15,13,1],[14,16,1],[15,16,1],[17,16,1],[18,16,1],[17,19,1],[18,19,1],[20,19,1],[21,19,1],[20,22,1],[21,22,1],[23,22,1],[24,22,1],[23,25,1],[24,25,1],[26,25,1],[27,25,1],[26,28,1],[27,28,1],[29,28,1],[30,28,1],[29,31,1],[30,31,1],[32,31,1],[33,31,1],[32,34,1],[33,34,1],[35,34,1],[36,34,1],[35,37,1],[36,37,1],[38,37,1],[39,37,1],[38,40,1],[39,40,1],[41,40,1],[42,40,1],[41,43,1],[42,43,1],[44,43,1],[45,43,1],[44,46,1],[45,46,1],[47,46,1],[48,46,1],[47,49,1],[48,49,1],[50,49,1],[51,49,1],[50,52,1],[51,52,1],[53,52,1],[54,52,1],[53,55,1],[54,55,1],[56,55,1],[57,55,1],[56,58,1],[57,58,1],[59,58,1],[60,58,1],[59,61,1],[60,61,1],[62,61,1],[63,61,1],[62,64,1],[63,64,1],[65,64,1],[66,64,1],[65,67,1],[66,67,1],[68,67,1],[69,67,1],[68,70,1],[69,70,1],[71,70,1],[72,70,1],[71,73,1],[72,73,1],[74,73,1],[75,73,1],[74,76,1],[75,76,1],[77,76,1],[78,76,1],[77,79,1],[78,79,1],[80,79,1],[81,79,1],[80,82,1],[81,82,1],[83,82,1],[84,82,1],[83,85,1],[84,85,1],[86,85,1],[87,85,1],[86,88,1],[87,88,1],[89,88,1],[90,88,1],[89,91,1],[90,91,1],[92,88,100000],[92,85,100000],[92,82,100000],[92,76,100000],[92,73,100000],[92,70,100000],[92,61,100000],[92,58,100000],[92,52,100000],[92,46,100000],[92,43,100000],[92,34,100000],[92,28,100000],[92,7,100000],[92,4,100000],[92,220,100000],[93,92,1],[94,92,1],[93,95,1],[94,95,1],[96,95,1],[97,95,1],[96,98,1],[97,98,1],[99,98,1],[100,98,1],[99,101,1],[100,101,1],[102,101,1],[103,101,1],[102,104,1],[103,104,1],[105,104,1],[106,104,1],[105,107,1],[106,107,1],[108,107,1],[109,107,1],[108,110,1],[109,110,1],[111,110,1],[112,110,1],[111,113,1],[112,113,1],[114,113,1],[115,113,1],[114,116,1],[115,116,1],[117,116,1],[118,116,1],[117,119,1],[118,119,1],[120,119,1],[121,119,1],[120,122,1],[121,122,1],[123,122,1],[124,122,1],[123,125,1],[124,125,1],[126,125,1],[127,125,1],[126,128,1],[127,128,1],[129,128,1],[130,128,1],[129,131,1],[130,131,1],[132,131,1],[133,131,1],[132,134,1],[133,134,1],[135,134,1],[136,134,1],[135,137,1],[136,137,1],[138,137,1],[139,137,1],[138,140,1],[139,140,1],[141,140,1],[142,140,1],[141,143,1],[142,143,1],[144,143,1],[145,143,1],[144,146,1],[145,146,1],[147,146,1],[148,146,1],[147,149,1],[148,149,1],[150,149,1],[151,149,1],[150,152,1],[151,152,1],[153,152,1],[154,152,1],[153,155,1],[154,155,1],[156,155,1],[157,155,1],[156,158,1],[157,158,1],[159,158,1],[160,158,1],[159,161,1],[160,161,1],[162,161,1],[163,161,1],[162,164,1],[163,164,1],[165,164,1],[166,164,1],[165,167,1],[166,167,1],[168,167,1],[169,167,1],[168,170,1],[169,170,1],[171,170,1],[172,170,1],[171,173,1],[172,173,1],[174,173,1],[175,173,1],[174,176,1],[175,176,1],[177,176,1],[178,176,1],[177,179,1],[178,179,1],[180,179,1],[181,179,1],[180,182,1],[181,182,1],[183,182,1],[184,182,1],[183,185,1],[184,185,1],[186,185,1],[187,185,1],[186,188,1],[187,188,1],[189,188,1],[190,188,1],[189,191,1],[190,191,1],[192,191,1],[193,191,1],[192,194,1],[193,194,1],[195,194,1],[196,194,1],[195,197,1],[196,197,1],[198,197,1],[199,197,1],[198,200,1],[199,200,1],[201,200,1],[202,200,1],[201,203,1],[202,203,1],[204,203,1],[205,203,1],[204,206,1],[205,206,1],[207,206,1],[208,206,1],[207,209,1],[208,209,1],[210,209,1],[211,209,1],[210,212,1],[211,212,1],[1,212,1],[213,220,1],[214,220,1],[215,220,1],[216,220,1],[217,220,1],[218,220,1],[219,220,1]]

#### Code you used for Submit/Run operation

```
const int INF = 0x7f3f3f3f;
const int MAXN = 20010;
const int MAXM = 100010;
const int mod = 1e9+7;

struct qnode {
    int v;
    int c;
    qnode(int _v = 0, int _c = 0) : v(_v), c(_c) {}
    bool operator <(const qnode &r) const {
        return c > r.c;
    }
};

struct node {
    int to, next, weight;
} edge[MAXM]; //to表示边的终点 next表示同起点下一条边储存位置 w表示权重

int cnt;
int head[MAXN]; //表示以i为起点的第一条边储存位置

inline void addedge(int u, int v, int w) {
    edge[++cnt].to = v;
    edge[cnt].next = head[u];
    edge[cnt].weight = w;
    head[u] = cnt;
    return;
}

void renew() {
    cnt = 0;
    memset(head, -1, sizeof(head));
}

bool vis[MAXN];
int dist[MAXN];

void Dijkstra(int n, int start) {
    memset(vis, false, sizeof(vis));
    for(int i = 1;i <= n;i ++) dist[i] = INF;
    priority_queue<qnode> que;
    while(!que.empty()) que.pop();
    dist[start] = 0;
    que.push(qnode(start, 0));
    qnode tmp;
    while(!que.empty()) {
        tmp = que.top();
        que.pop();
        int u = tmp.v;
        if(vis[u]) continue;
        vis[u] = true;
        for(int i = head[u];~i;i = edge[i].next) {
            int v = edge[i].to;
            int cost = edge[i].weight;
            if(!vis[v] && dist[v] > dist[u] + cost) {
                dist[v] = dist[u] + cost;
                que.push(qnode(v, dist[v]));
            }
        }
    }
}

int dp[20010];

int allpoint;

int dfs(int now) {
    if(dp[now]) return dp[now];
    if(now == allpoint) return dp[now] = 1;
    for(int i = head[now];~i;i = edge[i].next) {
        int to = edge[i].to;
        if(dist[to] < dist[now]) {
            dp[now] = (dp[now] + dfs(to)) % mod;
        }
    }
    return dp[now];
}

class Solution {
public:
    int countRestrictedPaths(int n, vector<vector<int>>& edges) {
        allpoint = n;
        renew();
        for(int i = 1;i <=  n;i ++) dp[i] = 0;
        int sz = edges.size();
        for(int i = 0;i < sz;i ++) {
            int from = edges[i][0];
            int to = edges[i][1];
            int cost = edges[i][2];
            addedge(from, to, cost);
            addedge(to, from, cost);
        }
        Dijkstra(n, n);
        dfs(1);
        return dp[1];
    }
};
```

#### Language used for code

C++

#### Expected behavior

Expected output: 0.
The code gets Time Limit Exceeded.

#### Screenshots

![1](https://user-images.githubusercontent.com/11583428/110557898-14e15d00-8107-11eb-9746-e2b334b933b2.png)

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
