### ISSUE TITLE
79. Word Search: Misspelling on Description 

### ISSUE THREAD

**Issue by kadhirash** [LeetCode-Feedback/LeetCode-Feedback#2666]
#### Your LeetCode username

not_ucr

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

I was working on Word Search and came across a small misspelling on the description.

"Given an m x n ```gird``` of characters board and a string word, return true if word exists in the grid."

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior

It should be ```grid``` instead of gird. 

#### Screenshots

![Screen Shot 2021-03-09 at 6 29 54 PM](https://user-images.githubusercontent.com/10100659/110566852-756f9a80-8105-11eb-9650-f72038f2a257.png)

**Comment by lc-kay** [comment]
Hi @kadhirash 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @kadhirash 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
