### ISSUE TITLE
[Reopen] Time Complexity Restriction for Binary Search Problems

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#2667]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Hi @lc-kay ,
I have created issue #2612 , which has been closed. I would like to mention my points again here. I won't repeat the context from the previous issue again, and I will just mention some points in this issue.
It seems that I did not describe my suggestion quite clearly. My suggestion is **NOT** to add more test cases, but to add a statement in **problem description** that states the time complexity requirement. I think this should be practical.
For example, for problem 704 which is the original binary search problem, a statement should be added just before the first example, like the following:
> The time complexity should be `O(log n)`, where `n` is the length of the array `nums`.

For the remaining problems, a similar statement should be added as well.
**Note:** For problem 34, the `O(log n)` time complexity requirement is in the follow-up question. I think this should be the normal requirement, not a follow-up requirement, since the `O(n)` approach is too easy for an interview. That is to say, problem 34 should contain the statement mentioned above and should **NOT** contain a follow-up question.

#### Expected behavior
For each problem mentioned in issue #2612 , a statement should be added for restriction of time complexity.
For problem 34, do not make the `O(log n)` time complexity be a follow-up requirement. This should be a normal requirement, and the follow-up question should be removed from problem 34.

**Comment by lc-kay** [comment]
@stormsunshine We understand that your suggestion is not to add more test cases. However, due to the previously mentioned platform limitations, we will not add in the problem description a required time complexity as we cannot enforce that to happen. Thank you for your feedback, we have noted this for future improvements.
