### ISSUE TITLE
Missing Test Case - 501. Find Mode in Binary Search Tree

### ISSUE THREAD

**Issue by ravipranjal** [LeetCode-Feedback/LeetCode-Feedback#2669]
#### Your LeetCode username

ravipranjalp 

#### Category of the bug
- [ x ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Missing testcases.

#### Code you used for Submit/Run operation

```
/**
 * Definition for a binary tree node.
 * public class TreeNode {
 *     int val;
 *     TreeNode left;
 *     TreeNode right;
 *     TreeNode() {}
 *     TreeNode(int val) { this.val = val; }
 *     TreeNode(int val, TreeNode left, TreeNode right) {
 *         this.val = val;
 *         this.left = left;
 *         this.right = right;
 *     }
 * }
 */
class Solution {
    int count;
    TreeNode pre;
    int max;
    public int[] findMode(TreeNode root) {
         if (root == null) return new int[0];

        count = 1;
        max = 1;
        List<Integer> same = new ArrayList<>();
        dfs(root, same);
        int size = same.size();
        int[] res = new int[size];
        int index = 0;
        for (int i : same) {
            res[index++] = i;
        }
        return res;
    }
    private void dfs(TreeNode root, List<Integer> same) {
        if (root == null) return;
        dfs(root.left, same);
        if (pre != null) {
            if (pre.val == root.val) {
                count++;           
            } else {
                count = 1;//reset
            }
        }
        if (count == max) {
            same.add(root.val);
        } else if (count > max) {
            max = count;
            same.clear();
            same.add(root.val);
        }
        pre = root;
        dfs(root.right, same);
    }
}
```

#### Language used for code

Java

#### Expected behavior

I was not able to figure out the O(1) solution to this so I tried looking up to the sample submissions. When I copy pasted the code from one of the solution and ran, it got accepted. However, I see many testcases for which it would not pass, one of the testcase being:  [2,2,3,2,2,3,3,1,1,1,2,2,3,3,3]

**Comment by lc-kay** [comment]
Hi @ravipranjal 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @ravipranjal 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
