### ISSUE TITLE
Invalid default test case - 1188. Design Bounded Blocking Queue

### ISSUE THREAD

**Issue by gnarula** [LeetCode-Feedback/LeetCode-Feedback#2672]
#### Your LeetCode username
majnu

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
The sample test case provided fails with `[2] is not a valid value of type integer`.

#### Code you used for Submit/Run operation

```java
class BoundedBlockingQueue {
    private Queue<Integer> queue;
    private int count;
    private int capacity;
    
    public BoundedBlockingQueue(int capacity) {
        this.queue = new LinkedList<>();
        this.capacity = capacity;
    }
    
    public synchronized void enqueue(int element) throws InterruptedException {
        while(this.queue.size() == capacity) {
            wait();
        }
        
        this.queue.add(element);
        notifyAll();
    }
    
    public synchronized int dequeue() throws InterruptedException {
        while(this.queue.size() == 0) {
            wait();
        }
        
        int res = this.queue.poll();
        notifyAll();
        return res;
    }
    
    public synchronized int size() {
        return this.queue.size();
    }
}
```

#### Language used for code
Doesn't matter - the tests fail across all languages for the default code and a working solution

#### Expected behavior

The default test case should be accepted

**Comment by gnarula** [comment]
Surprisingly the problem only occurs when trying to run the sample test cases using `Run`. A submit works fine.

**Comment by lc-kay** [comment]
Hi @gnarula 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @gnarula 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
