### ISSUE TITLE
面试题 16.22. 兰顿蚂蚁 存在运行错误

### ISSUE THREAD

**Issue by tsaiggo** [LeetCode-Feedback/LeetCode-Feedback#2674]
**你的 LeetCode 用户名**
tsaiggo

**Bug 类型**
题目错误 -- 面试题 16.22. 兰顿蚂蚁

**描述**
本地执行和远程执行，入参相同，但结果不同

**你使用的语言**
Java

**你提交或者运行的代码**
https://leetcode-cn.com/submissions/detail/153543137/

**期望行为**
本地运行获得的结果是
[UX, XX]
题目期望结果是
[UX, XX]
但是本地代码在平台上运行结果
[_XU,___]

**Comment by feiceh** [comment]
你好，建议再仔细检查并调试一下代码，推荐阅读：「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」 获得更多帮助。

同时也可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
