### ISSUE TITLE
Wrong Test Case - 287. Find the Duplicate Number

### ISSUE THREAD

**Issue by singhperryo1** [LeetCode-Feedback/LeetCode-Feedback#2675]
test case #12
[2,2,2,2,2]

The description says "Given an array of integers nums containing n + 1 integers where each integer is in the range [1, n] inclusive. There is only one repeated number in nums, return this repeated number."

This test case violates the last condition that reads "There is only one repeated number in nums, return this repeated number"

#### Your LeetCode username

panjab

#### Category of the bug
- [x] Question

#### Description of the bug

test case #12
[2,2,2,2,2]

The description says "Given an array of integers nums containing n + 1 integers where each integer is in the range [1, n] inclusive. There is only one repeated number in nums, return this repeated number."

This test case violates the last condition that reads "There is only one repeated number in nums, return this repeated number"

#### Code you used for Submit/Run operation

```
class Solution {
    public int findDuplicate(int[] nums) {
        
        int sum = ((nums.length - 1) * (nums.length)) / 2; 
        
        for (int n : nums) {
            sum -= n; 
        }
        
        return Math.abs(sum); 
    }
}
```

#### Expected behavior

I expected the test case to be right

**Comment by lc-kay** [comment]
@singhperryo1 Please refer to the last constraint, "All the integers in nums appear only once except for precisely one integer which appears two or more times." In this test case, integer 2 is the only integer that appears two or more times, therefore, this is a valid test case. Thank you for your time.
