### ISSUE TITLE
Missing Test Case - 627. Swap Salary

### ISSUE THREAD

**Issue by psean21c** [LeetCode-Feedback/LeetCode-Feedback#2676]
#### Your LeetCode username
psean21c

#### Category of the bug
- [* ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The explanation below is not accurate.

(1, A) and (2, C) were changed from 'm' to 'f'.
(2,C) has to be updated to (3, C) according to the Table provided.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
Hi @psean21c 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @psean21c 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
