### ISSUE TITLE
Problem with Test Case - 479. Valid Palindrome

### ISSUE THREAD

**Issue by devspartan** [LeetCode-Feedback/LeetCode-Feedback#2678]
#### Your LeetCode username
devspartan

#### Category of the bug
- [ ] Solution

#### Description of the bug

I've been doing easy collection of Top Interview problems
In strings - Question -> Valid Palindrome
There is a test case 479 which is "OP".
When i click on **Run Code** with custom  **test case "OP"** my code gives output **false** (which is a expected output)
but on **Submit** it gives wrong answer. For **test case "OP"** my code gives **true** (which is wrong).
Why my code giving different answers for same test case on **Run Code** and **Submitt**

#### Code you used for Submit/Run operation

```
class Solution {
public:
    
bool isPalindrome(string s) {
    int length = s.length();

    int i = 0, j = length - 1;
    while (i <= j) {
        if (s[i] < 48 || s[i] > 57 && s[i] < 65 || s[i] > 90 && s[i] < 97 ||
            s[i] > 122) {
            i++;
        } else if (s[j] < 48 || s[j] > 57 && s[j] < 65 ||
                   s[j] > 90 && s[j] < 97 || s[j] > 122) {
            j--;
        } else if (s[i] == s[j] || s[i] + 32 == s[j] || s[j] + 32 == s[i]) {
            i++;
            j--;
        } else {
            return false;
        }
    }

    return true;
}
};
```
#### Expected behavior

for testcase "OP" my code should give **output false** on Submitt. 

#### Screenshots

![Screenshot from 2021-03-11 12-33-42](https://user-images.githubusercontent.com/45001741/110748956-6f44ff80-8266-11eb-8dc1-117878313620.png)
on Run Code with test case "OP"

![Screenshot from 2021-03-11 12-33-59](https://user-images.githubusercontent.com/45001741/110748962-710ec300-8266-11eb-87aa-359ff211125c.png)
![Screenshot from 2021-03-11 12-45-01](https://user-images.githubusercontent.com/45001741/110749854-a7990d80-8267-11eb-8155-72790b739872.png)

on Submitt with test case "OP"

#### Additional context

Please check why is it giving different answers with same code and same test case on Run code and submitt.

**Comment by lc-kay** [comment]
Hi @devspartan 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
