### ISSUE TITLE
Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by TuxxyDOS** [LeetCode-Feedback/LeetCode-Feedback#268]
**What kind of the bug**
- [ ] problem
- [x] solution
- [ ] language

**Describe the bug**
The result picked is not the one my code submitted.

**what language is your code written in**
JS

**The code you submit/run**
```
/**
 * @param {number[]} nums
 * @return {number}
 */
var removeDuplicates = function(nums) 
{
    nums = nums.reduce((accumulator, num) => 
    {
        if (!accumulator.some(item => item === num))
            accumulator.push(num)
        
        return accumulator
    }, [])
    
    console.log(nums)
    
    return nums.length
};
```

**Actual behavior**
Test case:
[1,2]

Stdout:
[1,2]

My answer:
[1,1]

Expected Answer:
[1,2]

**Expected behavior**
Test case:
[1,2]

Stdout:
[1,2]

My answer:
[1,2]

Expected Answer:
[1,2]

**Comment by CooperCooperCooper** [comment]
Hi @TuxxyDOS ,
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
