### ISSUE TITLE
Missing Test Case - 75. Sort Colors 

### ISSUE THREAD

**Issue by omzsonu** [LeetCode-Feedback/LeetCode-Feedback#2680]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@omzsonu Please provide more details to your missing test case report such as the custom test case and the code it failed on. Thank you for your time.

**Comment by lc-kay** [comment]
Hi @omzsonu 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
