### ISSUE TITLE
Missing Test Case - 160. Intersection of Two Linked Lists

### ISSUE THREAD

**Issue by danorel** [LeetCode-Feedback/LeetCode-Feedback#2681]
#### Your LeetCode username

danorel

#### Category of the bug
- Question
- Solution
- C++

#### Description of the bug

The test case is giving wrong results, but the input data is out of permitted bounds.

Wrong test case:
```
1   - here is no intersection
[1]
[1] - headB could not have only 1 node. The length is n, which is more than 3*10^4.
0   - skipA could not be 0
0   - skipB could not be 0
```

```
Constraints:

The number of nodes of listA is in the m.
The number of nodes of listB is in the n.
1 <= m, n <= 3 * 104
1 <= Node.val <= 105
1 <= skipA <= m
1 <= skipB <= n
intersectVal is 0 if listA and listB do not intersect.
intersectVal == listA[skipA + 1] == listB[skipB + 1] if listA and listB intersect.
```

#### Code you used for Submit/Run operation

```
class Solution {
public:
    ListNode *getIntersectionNode(ListNode *headA, ListNode *headB) {
        ListNode* fixed = headA;
        ListNode* iterator = headB;
        
        while (fixed != nullptr) {
            while (iterator != nullptr) {
                if (iterator->next == fixed)
                    return fixed;
                
                iterator = iterator->next;
            }
            
            iterator = headB;
            fixed = fixed->next;
        }
        
        return nullptr;
    }
};
```

#### Language used for code

C++

#### Expected behavior

```
Your input:
1
[1]
[1]
0
0

Output:
No intersection

Expected:
No intersection
```

#### Screenshots

<img width="841" alt="Screenshot 2021-03-11 at 19 38 54" src="https://user-images.githubusercontent.com/13682999/110830476-ed72c780-82a1-11eb-8eac-8943c70e6cf9.png">

<img width="899" alt="Screenshot 2021-03-11 at 19 38 31" src="https://user-images.githubusercontent.com/13682999/110830483-eea3f480-82a1-11eb-84f8-042aeae1ae3d.png">

#### Additional context

More details about failure submission here: https://leetcode.com/submissions/detail/466519823/

**Comment by lc-kay** [comment]
Hi @danorel 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by danorel** [comment]
@lc-kay Glad to help you to detect the issue!

**Comment by lc-kay** [comment]
Hi @danorel 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
