### ISSUE TITLE
Wrong Example Output - 275. H-Index II

### ISSUE THREAD

**Issue by yang052513** [LeetCode-Feedback/LeetCode-Feedback#2682]
#### Your LeetCode username

Elaina_mjoj

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

For **example 2**, the website indicates`Output` is 0 for the H-index. However, the result should be `2`.

```code
Input: citations = [1,2,100]
Output: 0
```
#### Code you used for Submit/Run operation

```
// Binary Search for logn time complexity 
class Solution {
public:
    int hIndex(vector<int>& citations) {
        int l = 0, r = citations.size()-1, m;
        int len = citations.size();
        
        while (l <= r) {
            m = l + (r-l)/2;
            if (citations[m] >= len-m) {
                r = m-1;
            } else {
                l = m+1;
            }
        }
        return len-l;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Not relevant

#### Screenshots

Not relevant

#### Additional context

Not relevant

**Comment by lc-kay** [comment]
@yang052513 Can you please provide an explanation on why the expected output should be 2?
