### ISSUE TITLE
Missing Test Case - 322. Coin Change

### ISSUE THREAD

**Issue by banyazavi** [LeetCode-Feedback/LeetCode-Feedback#2683]
#### Your LeetCode username
banyazavi

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
When an Input like below:
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24]
9999

Expected answer is:
-1

But some of fastest accepted solutions cannot pass this test case.
I hope you add this test case as an edge case of inputs.

##### My Solution
```
class Solution:
    def coinChange(self, coins: List[int], amount: int) -> int:
        cntDP = [0]
        for i in range(1, amount + 1):
            cntDP.append(min(list(map(lambda x: cntDP[i - x] + 1 if i - x >= 0 else amount + 1, coins))))
        return -1 if cntDP[-1] > amount else cntDP[-1]
```

##### One of the fastest solution (44ms in Python3)
```
class Solution:
    def coinChange(self, coins: List[int], amount: int) -> int:
        def helper(count, have, i, res):
            coin = coins[i]
            if count - (have - amount) // coin >= res:
                return res
            need = amount-have
            if need % coin == 0:
                x = count + need//coin
                return x if x < res else res
            if i == 0:
                return res
            for j in range(need // coin, -1, -1):
                sub = helper(count+j, have+coin*j, i-1, res)
                if sub < res:
                    res = sub
            return res

        coins.sort()
        ret = helper(0, 0, len(coins)-1, amount+1)
        return -1 if ret == amount+1 else ret
```
This solution, however, CANNOT PASS the edge case input I suggested.

#### Language used for code
Python 3

#### Expected behavior
When an Input like below:
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24]
9999

Expected answer is:
-1

But some of fastest accepted solutions cannot pass this test case.
I hope you add this test case as an edge case of inputs.

**Comment by lc-kay** [comment]
@banyazavi Please provide the code you used for Submit/Run operation. Thank you!

**Comment by banyazavi** [comment]
> @banyazavi Please provide the code you used for Submit/Run operation. Thank you!

@lc-kay I have edited my report for your request and please look at this once more. Thank you for your interest.

**Comment by lc-kay** [comment]
Hi @banyazavi 
I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @banyazavi 
Thank you for your time. The team reviewed your report and noticed your solution fails from earlier test case contributions, so we didn't add the test case. We appreciate your support!
