### ISSUE TITLE
Missing Test Case 322. Coin Change

### ISSUE THREAD

**Issue by yuhan-wang** [LeetCode-Feedback/LeetCode-Feedback#2684]
#### Your LeetCode username

yuhan-wang

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language

#### Description of the bug

The following test case satisfies the problem constraint:
[411,412,413,414,415,416,417,418,419,420,421,422]
9864

Yet solutions with exponential time complexity like the one below get TLE but is accepted.
#### Code you used for Submit/Run operation

```
class Solution {
    int res = Integer.MAX_VALUE;
    private void dfs(int[] coins, int i, int amount, int count) {
        if(i < 0) return;
        if(amount % coins[i] == 0) {
            res = Math.min(res, count + amount / coins[i]);
            return;
        }
        for(int c = amount / coins[i]; c >= 0 && count + c + 1 < res; c--) {
            dfs(coins, i - 1, amount - c * coins[i], count + c);
        }
    }
    public int coinChange(int[] coins, int amount) {
        Arrays.sort(coins);
        dfs(coins, coins.length - 1, amount, 0);
        return res == Integer.MAX_VALUE ? -1 : res;
    }
}
```
#### Language used for code

JAVA

#### Expected behavior

Only O(n*k) solutions should get accepted. Solutions with exponential complexity should get rejected.

#### Additional context

Submission link: https://leetcode.com/submissions/detail/466660206/

**Comment by lc-kay** [comment]
Hi @yuhan-wang 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @yuhan-wang 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
