### ISSUE TITLE
Missing Test Case - 106. Construct Binary Tree from Inorder and Postorder Traversal

### ISSUE THREAD

**Issue by a8252525** [LeetCode-Feedback/LeetCode-Feedback#2688]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The expected answer of test case
[-1]
[-1]
is [-1]
not [ ]

#### Language used for code

Python

#### Screenshots

![image](https://user-images.githubusercontent.com/32895524/110914233-11411680-8351-11eb-9e57-062c4293a7bc.png)

![image](https://user-images.githubusercontent.com/32895524/110914207-08504500-8351-11eb-8cfb-5234860ea5bc.png)

**Comment by lc-kay** [comment]
Hi @a8252525 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @a8252525 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
