### ISSUE TITLE
Missing Test Case - 1461. Check If a String Contains All Binary Codes of Size K

### ISSUE THREAD

**Issue by rishabhchahal** [LeetCode-Feedback/LeetCode-Feedback#2691]
#### Your LeetCode username
rishabhchahal

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Missing Test case

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean hasAllCodes(String s, int k) {
        Set<Integer> set = new HashSet<>();
        for(int i=0;i<=s.length()-k;i++)
        {
            set.add(Integer.parseInt(s.substring(i,i+k),2));
        }
        
        if(k==1)
         {
             if(set.contains(0) && set.contains(1))
            return true;
            else 
                return false;
        }
        
        if(k==2 )
        {
            if(set.contains(0) && set.contains(1)&&set.contains(2) && set.contains(3))
                return true;
            else
                return false;
        }
        
        for(int i= (int)Math.pow(2,k-1);i<=Math.pow(2,k)-1;i++)
            if(!set.contains(i))
                return false;
        
        return true;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Above provided code submitted successfully but one custom test case failed for my code
```
"1011100"
3
```
Basically my code is checking for number with string binary numbers no appended zeros but engine is expecting to count binary numbers starting with zeros.

**Comment by lc-kay** [comment]
Hi @rishabhchahal 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @rishabhchahal 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
