### ISSUE TITLE
Missing Test Case - 1461. Check If a String Contains All Binary Codes of Size K

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#2692]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

The fastest C++ code fails on the following testcase:
[1461.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6133831/1461.txt)

#### Code you used for Submit/Run operation

```
#define set Set
bool set[1<<15];
class Solution {
public:
	bool hasAllCodes(string& s, int k) {
        
        if (k>15) return false;
        memset(set, 0, sizeof(bool)*(1<<k));
		
		int n = stoi(s.substr(0,k), 0, 2);
		for (int i=k; i <= s.size(); i++) {
			// check prev window
			set[n] = true;
			if (i == s.size()) break;
            n = n & ~(1 << (k-1)); // clear kth bit
			n = (n << 1) | (s[i]-'0');
		}
        
        for (int i=0; i < (1<<k); i++)
            if (set[i] == false) return false;
		
		return true;
	}
	
};
```

#### Language used for code

C++

#### Expected behavior

Expected output: true.
The code's output: false.

#### Screenshots

![1](https://user-images.githubusercontent.com/11583428/110983670-aaf7cc00-832f-11eb-8821-db21563de2e8.png)

**Comment by lc-kay** [comment]
@hqztrue Please re-attach the test case file, I am unable to open the current one. Thank you.

**Comment by hqztrue** [comment]
It should be fine now. The webpage crashed a few times when I upload it last time.

**Comment by lc-kay** [comment]
@hqztrue I'm receiving invalid test case error with the test case you submitted. Please let me know if that is not what you get on your end.

**Comment by hqztrue** [comment]
The testcase is valid on my side. I uploaded it again at here: https://github.com/hqztrue/shared_materials/blob/master/tmp/LeetCode/1461.txt
![1](https://user-images.githubusercontent.com/11583428/111221078-06cc8a00-85a8-11eb-949d-107f59469d70.png)

**Comment by lc-kay** [comment]
Hi @hqztrue 
I was able to reproduce it, I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
