### ISSUE TITLE
Missing Test Case - 1165. Single-Row Keyboard

### ISSUE THREAD

**Issue by wangzhaoqi001** [LeetCode-Feedback/LeetCode-Feedback#2693]
#### Your LeetCode username

835N

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
Solution

#### Description of the bug

Missing test case

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int calculateTime(string keyboard, string word) {
        if(word.size()<2)
            return word.size();
        int key[26];
        for(int i=0;i<26;i++)
            key[keyboard[i]-'a']=i;
        int res=0,cur=0;
        for(int i=0;i<word.size();i++){
            res+=abs(key[word[i]-'a']-cur);
            cur=key[word[i]-'a'];
        }
        return res;
    }
};
```

#### Language used for code

C++

#### Expected behavior

When the word size is equal to one, I still have to move my finger once to the character.
But the test case didn't include this situation, so I can set if the size of a word smaller than two just returns the word. size().

#### Screenshots

![image](https://user-images.githubusercontent.com/54817310/111011499-a222ec80-8367-11eb-828d-9df0430f3231.png)

**Comment by lc-kay** [comment]
Hi @wangzhaoqi001 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @wangzhaoqi001 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
