### ISSUE TITLE
Missing Test Case - 322. Coin Change

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#2697]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

An accepted solution gets TLE on the following testcase:
[411,412,413,414,415,416,417,418,419,420,421,422]
8863

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int coinChange(vector<int>& coins, int amount) {
        sort(coins.begin(), coins.end(), greater<int>());
        result = INT_MAX;
        for (auto i:coins)if (amount%i==0)result=min(result,amount/i);
        backtrack(coins, amount, 0, 0);
        return (result==INT_MAX) ? -1:result;
    }
private:
        void backtrack(vector<int> &coins, int amount, int idx, int count) {
            if(amount<0 || idx>=coins.size())
                return;
            
            if(amount%coins[idx]==0) {
                result = min(result, count+amount/coins[idx]);
                return;
            }
            
            for(int i=amount/coins[idx]; i>=0; --i) {
                if(count+i+1 >= result)
                    break;
                backtrack(coins, amount-coins[idx]*i, idx+1, count+i);
            }
        }
        
    int result;
};
```

#### Language used for code

C++

#### Expected behavior

The code gets Time Limit Exceeded.

#### Screenshots

![1](https://user-images.githubusercontent.com/11583428/111020026-a57aa000-8388-11eb-91e4-c9c71625e000.png)

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
