### ISSUE TITLE
155.最小栈和剑指Offer30缺少测试用例

### ISSUE THREAD

**Issue by Boompengp** [LeetCode-Feedback/LeetCode-Feedback#2698]
**你的 LeetCode 用户名**
shaochen

**Bug 类型**
- [ ] 题目

**描述**
缺少测试用例

**你使用的语言**
Java
**你提交或者运行的代码**
```
class MinStack {

    Deque<Integer> stack;
    Queue<Integer> queue;
    /** initialize your data structure here. */
    public MinStack() {
        stack = new LinkedList<>();
        queue = new PriorityQueue<>();
    }
    
    public void push(int x) {
        stack.push(x);
        queue.add(x);
    }
    
    public void pop() {
        int p = stack.pop();
        int q = queue.peek();
        if(p == q)queue.poll();
    }
    
    public int top() {
        return stack.peek();
    }

    public int getMin() {
        return queue.peek();
    }
}
```

**期望行为**
添加测试用例

["MinStack","push","push","push","getMin","pop","pop","top","getMin"]
[[],[5],[3],[4],[],[],[],[],[]]

**屏幕截图**
![image](https://user-images.githubusercontent.com/45331497/111023943-f8029d80-8416-11eb-8f87-45bde85e3e1e.png)

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
@lc-kay 麻烦帮忙跟进下这个用户反馈哦。

**Comment by lc-kay** [comment]
Hi @feiceh 
We've used the user's feedback to update the problem.

**Comment by feiceh** [comment]
@Boompengp 你好，当前题目已添加测试用例，ID： shaochen 给予积分奖励，请查收。
