### ISSUE TITLE
Missing Test Case - 1461. Check If a String Contains All Binary Codes of Size K

### ISSUE THREAD

**Issue by jianyi1995** [LeetCode-Feedback/LeetCode-Feedback#2699]
#### Category of the bug
- [ ] Solution

#### Description of the bug

When the given k is less than the length of the given string, the program which accesses elements outside of the given string can be accepted.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool hasAllCodes(string s, int k) {
        int totalCount = 1<<k;
        vector<bool> isUsed(totalCount, false);
        int initialNum = 0;
        for(int i = 0; i < k; i++)
            initialNum = ((initialNum<<1)|(s[i]-'0'))&(totalCount-1);
        isUsed[initialNum] = true;
        for(int i = k; i < s.size(); i++)
        {
            initialNum = ((initialNum<<1)|(s[i]-'0'))&(totalCount-1);
            isUsed[initialNum] = true;
        }
        for(const auto& ele: isUsed)
        {
            if(not ele)
                return false;
        }
        return true;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Runtime error

#### Screenshots

![image](https://user-images.githubusercontent.com/12655555/111025513-98f55680-841f-11eb-885d-357bdb45764d.png)

#### Additional context

Test case
"0"
20

**Comment by lc-kay** [comment]
Hi @jianyi1995 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @jianyi1995 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!
