### ISSUE TITLE
480. Sliding Window Median

### ISSUE THREAD

**Issue by guneykayim** [LeetCode-Feedback/LeetCode-Feedback#270]
**What kind of the bug**
- [ ] problem
- [X] solution
- [ ] language

**Describe the bug**
There is a problem in the generated output. Normally output should be in square brackets, however in this case opening bracket '[' is missing. Also, some of the outputs are missing.

**what language is your code written in**
C++

**The code you submit/run**
```
class Solution {
public:
    vector<double> medianSlidingWindow(vector<int>& nums, int k) {
    
        vector<double> res;
        for (int i = 0; i + k <= nums.size(); i++) {
            vector<int> window(nums.begin() + i, nums.begin() + i + k);
            sort(window.begin(), window.end());

            if (k % 2 == 1) {
                res.push_back(window[k / 2]);
            } else {
                res.push_back((double)(window[k / 2 - 1] + (double)window[k / 2]) / 2.0);
            }
        }

        return res;
    }
};
```

**Expected behavior**
I am expecting to get the following output:
```[1.00000,-1.00000,-1.00000,3.00000,5.00000,6.00000]```
However, I'm only getting the following:
```6.00000]```

This clearly shows that something is wrong in the output because it doesn't even have the opening bracket '['. I don't have control over those brackets.

**Additional context**
On top of this, I can also explain 3 unexpected behaviours. When I click on ```Run Code```, both my output and expected output are shown as ```6.00000]```, however, without changing the code, when I ```Submit``` the question, expected output seems to be correct, but my output still remains wrong. I've also debugged the code, when I check the local variables, just before the programs returns the result, output looks correct, however, when the output is returned, I still see the same problem. For all these cases, I've attached screenshots below.

**Screenshots**

- ```Run Code```

<img width="361" alt="run_code" src="https://user-images.githubusercontent.com/5243299/81157773-3b7eb680-8f7f-11ea-877d-734fe772acc2.png">

- ```Submit```
<img width="610" alt="submit" src="https://user-images.githubusercontent.com/5243299/81157778-3c174d00-8f7f-11ea-81f0-14aa9ecf6668.png">

- ```Debugger```
<img width="658" alt="debugger" src="https://user-images.githubusercontent.com/5243299/81157769-3ae62000-8f7f-11ea-935b-2b245db7b3b3.png">

**Comment by CooperCooperCooper** [comment]
Hi @guneykayim ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @
Thanks to your timely feedback, we've fixed the issue! Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
