### ISSUE TITLE
Missing Test Case - 823. Binary Trees With Factors

### ISSUE THREAD

**Issue by alexbprofit** [LeetCode-Feedback/LeetCode-Feedback#2701]
#### Your LeetCode username
user8391WG

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
The solution is accepted but fails on the following test case

The following test case is:

```
[3,5,6,7,11,12,24,3,5,6,7,11,12,24,3,5,6,7,11,12,24,3,5,6,7,11,12,24,3,5,6,7,11,12,24,3,5,6,7,11,12,24,3,5,6,7,11,12,24,3,5,6,7,11,12,24,3,5,6,7,11,12,24,3,5,6,7,11,12,24,3,5,6,7,11,12,24,3,5,6,7,11,12,24,3,5,6,7,11,12,24,3,5,6,7,11,12,24,3,5,6,7,11,12,24,3,5,6,7,11,12,24,3,5,6,7,11,12,24,3,5,6,7,11,12,24,3,5,6,7,11,12,24]
```

#### Code you used for Submit/Run operation

```
import ("math"
        "sort")
func numFactoredBinaryTrees(A []int) int {
    sort.Ints(A)
    mod := int(math.Pow(10, 9)+7)
    dp := map[int]int{}
    for _, v := range A {
        dp[v] = 1
    }
    for i:=0; i<len(A); i++ {
        for k:=i-1; k>=0; k-- {
            if A[i]%A[k] == 0 {
                v := A[i]/A[k]
                if _, ok := dp[v]; ok {
                    dp[A[i]] = dp[A[i]] + dp[A[k]]*dp[v]
                }
            }
        }
    }
    res := 0
    for _, v := range dp {
        res = (res+v)%mod
    }
    return res
}
```

#### Language used for code
Golang

#### Expected behavior
the solution must judged as Wrong Answer

#### Screenshots
![image](https://user-images.githubusercontent.com/57172679/111027536-8cf69e00-83f9-11eb-80f8-923914d7f7a4.png)

**Comment by lc-kay** [comment]
Hi @alexbprofit 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @alexbprofit 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by alexbprofit** [comment]
![Uploading image.png…]()
