### ISSUE TITLE
Missing Test Case - 823. Binary Trees With Factors

### ISSUE THREAD

**Issue by AJAYKR00KJ** [LeetCode-Feedback/LeetCode-Feedback#2702]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

The following code was accepted successfully, but for the test case
[2,4,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]
we got the output result 56 and the expected result is 70 which were not consistent.

#### Code you used for Submit/Run operation

```
 class Solution {
public:
    int numFactoredBinaryTrees(vector<int>& A) {
        S.insert(A.begin(),A.end());
        long long ans=0; for (auto x: S) ans+=go(x);
        return int(ans % 1000000007);
    }
private:
    unordered_set<int> S;
    unordered_map<int,long long> M;
    long long go(int x){
        if (M.count(x)) return M[x];
        long long cnt=1; for (int i: S) if (x%i==0 && S.count(x/i)) cnt+=go(i)*go(x/i);
        return M[x]=cnt;
    }
};

 
```

#### Expected behavior
Please add the test cases
[2,4,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21] 

 
#### Screenshots

![test](https://user-images.githubusercontent.com/48375037/111030522-b975de80-8428-11eb-91bd-7761ccd98945.png)

#### Additional context

Add the test case.

**Comment by oberllab** [comment]
@AJAYKR00KJ are you heading towards the right approach as your test case contains repititive numbers and in the question, it is clearly given that there are unique integers. Feel free to correct me if i am wrong. Thanks.

**Comment by AJAYKR00KJ** [comment]
Okay, thanks for configuring the error in the test case. I got it.
