### ISSUE TITLE
Missing Test Case - 823. Binary Trees With Factors

### ISSUE THREAD

**Issue by solomonchild** [LeetCode-Feedback/LeetCode-Feedback#2704]
#### Your LeetCode username
[solomonchild](https://leetcode.com/solomonchild/)

#### Category of the bug
- [x] Solution

#### Description of the bug
Expected answer for `[2,2]` is 2

#### Language used for code
C++ 

#### Expected behavior
Expected answer for `[2,2]` should be 1, since only one binary tree can be constructed (`2`).

#### Screenshots

![image](https://user-images.githubusercontent.com/1312792/111035728-600bb080-8424-11eb-89f2-77972dac2467.png)

**Comment by oberllab** [comment]
If i am not wrong, the question clearly mentions "given an array of unique integers".

**Comment by solomonchild** [comment]
> If i am not wrong, the question clearly mentions "given an array of unique integers".

You're right. Then I'd expect that this input would be deemed as invalid, rather than it being processed and a misleading answer produced as a result.

**Comment by lc-kay** [comment]
@solomonchild As stated in the problem description, "each number may be used for any number of times". Therefore, this test case is valid. Thank you for your time.
