### ISSUE TITLE
Missing Test Case - 823. Binary Trees With Factors

### ISSUE THREAD

**Issue by tummalavandana** [LeetCode-Feedback/LeetCode-Feedback#2705]
#### Your LeetCode username
vandana tummala

#### Category of the bug
- [Binary Trees With Factors] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

input -[2,2,4]
expected answer should be 3

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@tummalavandana The expected output is correct. Please raise your question in the discuss section for further support. Thank you for your time.
