### ISSUE TITLE
Missing Test Case - 823. Binary Trees With Factors

### ISSUE THREAD

**Issue by iliyas1155** [LeetCode-Feedback/LeetCode-Feedback#2706]
#### Your LeetCode username
iliyas1155 

#### Category of the bug
- [ ] Solution

#### Description of the bug
When test case contains repetitions, the "expected" result contains wrong value
I guess, that's because you don't skip repeating numbers when calculating ways to build current binary tree

#### Code you used for Submit/Run operation

```
class Solution {
    public int numFactoredBinaryTrees(int[] arr) {
        int mod = 1000000007;
        Arrays.sort(arr);
        Map<Integer, Long> dp = new HashMap();
        long res = 0;
        for(int num : arr) if(!dp.containsKey(num)) {
            long val = 1;
            for(int i=2; i*i<=num; i++) if(num%i==0) {
                int j = num/i;
                if(dp.containsKey(i) && dp.containsKey(j)) {
                    long combs = (dp.get(i) * dp.get(j)) % mod;
                    if(i!=j) combs *= 2;
                    val = (val + combs) % mod;
                }
            }
            dp.put(num, val);
            res = (res + val) % mod;
        }
        return (int) res;
    }
}
```

#### Language used for code
Java

#### Expected behavior
The algorithm has to SKIP repeating numbers, or should NOT ALLOW them in the input

#### Screenshots

![image](https://user-images.githubusercontent.com/29146560/111040080-c9de8700-8431-11eb-8a76-9167f9e292fe.png)

#### Additional context
You should add more test cases before publishing a problem in "Daily problems"
For example:
[2,4,5,5,10]

**Comment by lc-kay** [comment]
Hi @iliyas1155 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@iliyas1155
Thank you for your time. The team reviewed your report and noticed your solution fail on earlier submitted test case contributions, so we didn't add the test case. We appreciate your support!
