### ISSUE TITLE
823. Binary Trees With Factors Solution latex problem

### ISSUE THREAD

**Issue by songytyt** [LeetCode-Feedback/LeetCode-Feedback#2707]
#### Your LeetCode username

neon_blue_

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

823. Binary Trees With Factors > Solution > Approach #1 > Intuition > last paragraph: latex doesn't seem to be good.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

![image](https://user-images.githubusercontent.com/72487900/111040025-04bacd80-83e6-11eb-9027-6a9eec21d7d3.png)

**Comment by lc-kay** [comment]
Hi @songytyt 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @songytyt 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
