### ISSUE TITLE
Missing Test Case - 823. Binary Trees With Factors

### ISSUE THREAD

**Issue by dwirtshafter** [LeetCode-Feedback/LeetCode-Feedback#2708]
#### Your LeetCode username

thedude7181

#### Category of the bug
- [ ] Question
- [X ] Solution
- [ ] Language

#### Description of the bug

For the following solution, my code will pass all the current test cases.  But it has a integer overflow bug.  For example [18865777,36451879,36878647] it produces 5 as an answer instead of the correct 3.  

#### Code you used for Submit/Run operation

```
// 823. Binary Trees With Factors C#
public class Solution {
    public int NumFactoredBinaryTrees(int[] arr) {
        Array.Sort(arr);
        long[] dp = new long[arr.Length];
        dp[0] = 1;
        long rtn = 1;
        for(int i = 1;i < arr.Length; i++)
        {
            int l = 0;
            int r = i -1;
            long cnt = 1;
            while(l <= r)
            {
                int prod = arr[l] * arr[r];
                if(prod == arr[i])
                {
                    if(l == r)
                        cnt += (dp[l] * dp[r]);
                    else 
                        cnt += 2 * (dp[l] * dp[r]);
                    r--;
                    l++;
                } else if (prod > arr[i])
                {
                    r--;
                }
                else
                {
                    l++;
                }
            }
            
            dp[i] = cnt;
            rtn += cnt;    
        }
        
        return (int)(rtn %= 1000000007);
    }
}
```

#### Language used for code

C#

#### Expected behavior

For test case  [18865777,36451879,36878647] (there are many more examples) my code will incorrectly return 5 but it passes all current test cases.

**Comment by lc-kay** [comment]
Hi @dwirtshafter 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @dwirtshafter 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
