### ISSUE TITLE
Missing Test Case: 953. Verifying an Alien Dictionary

### ISSUE THREAD

**Issue by aleacosta5** [LeetCode-Feedback/LeetCode-Feedback#271]
**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
My code submission passed, but I tried a test case that my code isn't passing, seems like it's not being considered when submitting an answer.
`["app", "apple"]`
`"abcdefghijklmnopqrstuvwxyz"`

**what language is your code written in**
C#

**The code you submit/run**
```
public class Solution {
    public bool IsAlienSorted(string[] words, string order) {
        if (words.Length == 1) return true;
        
        Dictionary<char, int> d = new Dictionary<char, int>();
        for(int i = 0; i < order.Length; i++) {
            d.Add(order[i], i + 1);
        }
        
        string word = words[0];
        for(int i = 1; i < words.Length; i++) {
            string current = words[i];
            
            int pos1 = 0;
            int pos2 = 0;
            bool result = false;
            
            while(pos1 < word.Length && pos2 < current.Length) {
                char c1 = word[pos1];
                char c2 = current[pos2];
                if (d[c1] > d[c2]) {
                    return false;
                } else if (d[c1] < d[c2]) {
                    result = true;
                    break;
                }
                pos1++;
                pos2++;
            }
            
            if (result == false) return false;
            
            word = current;
        }
        
        return true;
    }
}
```

**Expected behavior**
It should fail since `app < apple`.

**Screenshots**
<img width="863" alt="image" src="https://user-images.githubusercontent.com/9158879/81184693-155d1480-8f87-11ea-9079-65dc56e80b76.png">
<img width="546" alt="image" src="https://user-images.githubusercontent.com/9158879/81184732-23ab3080-8f87-11ea-9eb7-b509ec42f7a0.png">

**Additional context**

**Comment by CooperCooperCooper** [comment]
Hi @aleacosta5 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
