### ISSUE TITLE
Function Name does not Match Problem Title - 1512. Number of Good Pairs

### ISSUE THREAD

**Issue by beckcavu** [LeetCode-Feedback/LeetCode-Feedback#2710]
#### Your LeetCode username
Cavun

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
The function to be implemented in Java is declared as numIdenticalPairs. Typically the function name resembles or matches the problem title.

#### Code you used for Submit/Run operation
none

#### Language used for code
Java

#### Screenshots

![image](https://user-images.githubusercontent.com/44934306/111043484-d30b2c00-8410-11eb-9fe6-66ce68bade1d.png)

**Comment by lc-kay** [comment]
@beckcavu Thank you for reaching out. For your information, there are instances where the function does not match the problem title. However, it does not affect the code in any way if the function doesn't match the title.
