### ISSUE TITLE
Very minor typo

### ISSUE THREAD

**Issue by ben-burlingham** [LeetCode-Feedback/LeetCode-Feedback#2715]
#### Your LeetCode username
ben-burlingham
(I don't need points for this, just trying to help)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
https://leetcode.com/problems/replace-employee-id-with-the-unique-identifier/

Result table is mislabeled.

`EmployeeUNI` table is listed twice. The first instance is correct, the second one should be labelled "Result table".

#### Screenshots
![image](https://user-images.githubusercontent.com/6643933/111056615-3eff8b80-8435-11eb-8efd-cc1e4d76ca34.png)

**Comment by lc-kay** [comment]
Hi @ben-burlingham 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @ben-burlingham 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
