### ISSUE TITLE
Typo in Problem Description - 1789. Primary Department for Each Employee

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#2716]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
For [1789. Primary Department for Each Employee](https://leetcode.com/problems/primary-department-for-each-employee), there is a typo in problem description.
In the definition of table `Employee`, the second column should be `department_id`, not `deprtment_id`. The typo needs to be fixed.
Please refer to the screenshot below.

#### Expected behavior
Fix the typo.

#### Screenshots
![image](https://user-images.githubusercontent.com/12067364/111056834-3e123c80-84bd-11eb-9ff1-7ef0083330d1.png)

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
