### ISSUE TITLE
Missing Test Case - 1790. Check if One String Swap Can Make Strings Equal

### ISSUE THREAD

**Issue by archit11111** [LeetCode-Feedback/LeetCode-Feedback#2717]
#### Your LeetCode username
archit91

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The solution gives the wrong output for some test cases but is accepted. An example of a test case on which the solution fails is - 
```
"aa"
"ac"
```

#### Code you used for Submit/Run operation

```
bool areAlmostEqual(string s1, string s2) {
    int n = size(s1), cnt=0, idx1=0, idx2=0;
    for(int i = 0; i < n; i++)
        if(s1[i] != s2[i]){
            cnt++;
            if(!idx1) idx1 = i; else idx2 = i;
        }             
    return (cnt <= 2) && s1[idx1] == s2[idx2];
}
```

#### Language used for code
C++

#### Expected behavior

The solution must be rejected since it fails in some test cases.

#### Screenshots

![image](https://user-images.githubusercontent.com/40712852/111057397-3a76b980-84ad-11eb-910e-e929406040b6.png)

#### Additional context

More specifically, I found the above-mentioned solution fails on test cases having  -
* `1 <= mismatches <= 2` and one of mismatched character in `s1` is starting character of `s2`

More examples of failing test cases - 
```
"caa"
"aaz"
```
```
"az"
"zd"
```

**Comment by lc-kay** [comment]
Hi @archit11111 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @archit11111 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
