### ISSUE TITLE
Typo in Hint 4 - 566. Reshape the Matrix

### ISSUE THREAD

**Issue by AK-ayush** [LeetCode-Feedback/LeetCode-Feedback#2718]
#### Your LeetCode username
n_vh

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language

#### Description of the bug

There is small typo in Hint 4 in the given problem.

As given in Hint, below is the mapping to convert from 1D index to 2D index:
`M[i] => M[n/i][n%i] Will it result in right mapping? Take some example and check this formulae.`

While it has to be like below:
`M[i] => M[i/n][i%n] where n is column size`

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code
C++ 

#### Screenshots

<img width="635" alt="Screenshot 2021-03-14 at 10 19 05 AM" src="https://user-images.githubusercontent.com/11587734/111057721-a8bc7b80-84af-11eb-8074-011eb3f0ff86.png">

**Comment by lc-kay** [comment]
Hi @AK-ayush 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @AK-ayush 
Thank you for your time. We've used your feedback to update the problem.  We appreciate your support!
