### ISSUE TITLE
An issue with Problem 237

### ISSUE THREAD

**Issue by orbitbyrd** [LeetCode-Feedback/LeetCode-Feedback#272]
**What kind of the bug**
- [ ] solution

**Describe the bug**
When I clicked on the fastest solution for the problem 237 in "Accepted solution runtime distribution graph", I saw that it was O(N), and O(1) solutions seem to have taken longer time. Could you add some test cases with high number of elements so that O(1) solution shows much faster runtime than the O(N) solution?

**what language is your code written in**
C#

**The code you submit/run**
public class Solution {
    public void DeleteNode(ListNode node) {
        node.val = node.next.val;
        node.next = node.next.next;
    }
}

**Expected behavior**
See "Describe the bug" section

**Screenshots**
This is O(N) solution yet, it is took less time to run. 
![image](https://user-images.githubusercontent.com/63358824/81209794-d4183500-8f85-11ea-88cb-ad1b26170445.png)

**Comment by CooperCooperCooper** [comment]
Hi @orbitbyrd ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @orbitbyrd ,

Thank you for your time. It is expected that runtime and memory usage for each program will vary with each execution,  and executions on different computers will also cause different results for the same code. Therefore, we've decided to keep the problem as-is for now. Thank you for your support and understanding.
