### ISSUE TITLE
Missing Test Case - 823. Binary Trees With Factors

### ISSUE THREAD

**Issue by ods** [LeetCode-Feedback/LeetCode-Feedback#2720]
#### Your LeetCode username
otkidach

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
The following code passes your tests but actually panic with overflow debug mode or produces wrong answer in release mode in line `if factor1 * factor1 > num {`. Here is a test case to reproduce the problem:

```rust
#[test]
fn test_big_dont_panic() {
    let arr = (1..10_000).map(|val| val * 100_000).collect();
    assert_eq!(Solution::num_factored_binary_trees(arr), 9_999);
}
```

#### Code you used for Submit/Run operation

```rust
impl Solution {
    pub fn num_factored_binary_trees(mut arr: Vec<i32>) -> i32 {
        const MODULO: u64 = 1_000_000_007;
        arr.sort_unstable();
        let mut counts = std::collections::HashMap::new();
        let mut total = 0;
        for &num in arr.iter() {
            let mut count = 1_u64;
            for &factor1 in arr.iter() {
                if factor1 * factor1 > num {
                    break;
                }
                if num % factor1 != 0 {
                    continue;
                }
                let factor2 = num / factor1;
                if let Some(count2) = counts.get(&factor2) {
                    count = (count
                        + counts[&factor1]
                            * count2
                            * if factor1 == factor2 { 1 } else { 2 })
                        % MODULO;
                }
            }
            counts.insert(num, count);
            total = (total + count) % MODULO;
        }
        total as _
    }
}
```

#### Language used for code
Rust

#### Expected behavior
Provided solution mustn't be accepted

**Comment by lc-kay** [comment]
@ods Please provide the custom test case in a .txt file.

**Comment by ods** [comment]
[test.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6146223/test.txt)

**Comment by lc-kay** [comment]
@ods The test case you submitted received invalid testcase error: expected 'arr' to have 1 <= size <= 1000 but got 9999
 As the test case doesn't meet our constraints, we will not consider adding it. Thank you for your time.

**Comment by ods** [comment]
My failure, here is a test case catching the problem with size=1000:
[test.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6153886/test.txt)

**Comment by lc-kay** [comment]
@ods The test case set for this problem was recently updated and the solution you previously submitted now fails. Therefore, we will not consider your custom test case. Thank you for understanding. 
<img width="1436" alt="Screen Shot 2021-03-17 at 2 26 27 PM" src="https://user-images.githubusercontent.com/70870126/111540833-e1b55400-872c-11eb-99ef-ef55006aad55.png">
