### ISSUE TITLE
Error in validation of the solution for 155. Min Stack

### ISSUE THREAD

**Issue by shrivatsahosabettu** [LeetCode-Feedback/LeetCode-Feedback#2721]
I think there is a problem in the test case execution for question https://leetcode.com/problems/min-stack/. I have submitted the solution without using O(1) time complexity, still the solution accepted. Below is my solution and it got accepted
The solution which I solved is O(n^2) and it never validates it.
```
public:
    /** initialize your data structure here. */
    vector v;
    int count;
    vector  :: iterator i;
    MinStack() {
    }
    
    void push(int x) {
        v.push_back(x);
        count++;
    }
    
    void pop() {
        v.pop_back();
        count--;
    }
    
    int top() {
        int res;
        res = v.back();
        return res;
    }
    
    int getMin() {
        int min=INT_MAX;
        for(i = v.begin(); i!= v.end(); ++i){
            if(*i < min)
                min = *i;
        }
        return min;
    }
};
```

**Comment by lc-kay** [comment]
@shrivatsahosabettu Please provide your submission details link. Thank you!

**Comment by shrivatsahosabettu** [comment]
Hi,
Below is my submission.
https://leetcode.com/submissions/detail/455561814/

**Comment by lc-kay** [comment]
Hi @shrivatsahosabettu 
 I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@shrivatsahosabettu Our team has reviewed your report and for your information, we don't test if the solution works on O(1). However, you're welcome to submit any valid test case that will cause any non-O(1) to fail. Thank you are for your time.
