### ISSUE TITLE
887. 鸡蛋掉落的题目描述需要更改

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#2725]
**你的 LeetCode 用户名**
stormsunshine

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
[887. 鸡蛋掉落](https://leetcode-cn.com/problems/super-egg-drop)的中文题目描述有以下内容需要更改。
第 1 段，「给你 `k` 枚鸡蛋」改成「给你 `k` 枚相同的鸡蛋」，需要加上「相同的」，「从 `1` 到 `n` 」改成「从第 `1` 层到第 `n` 层」。
第 2 段，「存在楼层 `f`」改成「已知存在楼层 `f`」，`0 <= f <= N` 改成 `0 <= f <= n`，以及加上逗号。
第 3 段，「你可以取一枚鸡蛋（如果你有完整的鸡蛋）」改成「你可以取一枚没有碎的鸡蛋」，「你就不能再把它扔下去」改成「你就不能再次使用它」，「如果某枚鸡蛋扔下后没有摔碎，则可以将其捡起 **重复使用**」改成「如果一枚鸡蛋扔下后没有摔碎，则可以在之后的操作中 **重复使用** 这枚鸡蛋」。
第 4 段，「最小移动次数」改成「最小操作次数」。

具体而言，题目描述更改如下：

> 给你 `k` 枚相同的鸡蛋，并可以使用一栋从第 `1` 层到第 `n` 层共有 `n` 层楼的建筑。
>
> 已知存在楼层 `f`，满足 `0 <= f <= n`，任何从 **高于** `f` 的楼层落下的鸡蛋都会碎，从 `f` 楼层或比它低的楼层落下的鸡蛋都不会破。
>
> 每次操作，你可以取一枚没有碎的鸡蛋并把它从任一楼层 `x` 扔下（满足 `1 <= x <= n`）。如果鸡蛋碎了，你就不能再次使用它。如果一枚鸡蛋扔下后没有摔碎，则可以在之后的操作中 **重复使用** 这枚鸡蛋。
>
> 请你计算并返回要确定 `f` **确切的值** 的 **最小操作次数** 是多少？

**你使用的语言**

**你提交或者运行的代码**

**期望行为**
更改上文提到的题目描述。

**屏幕截图**

**额外的上下文**

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前题目描述已更新。力扣会定期更新，保障稳定和体验优化。
