### ISSUE TITLE
Issue with Problem 387

### ISSUE THREAD

**Issue by orbitbyrd** [LeetCode-Feedback/LeetCode-Feedback#273]
**What kind of the bug**
- [ ] solution

**Describe the bug**
For problem 387,  I noticed that a potentially O(N^2) solution is ending up beating 78.24% of the submissions when the optimal solution is supposed to be O(N). Could you please add some heavy test cases so that O(N^2) submissions end up at the end of the rank?

**what language is your code written in**
C#

**The code you submit/run**
public class Solution {
    public int FirstUniqChar(string s) {
        var hist = new int?[26];
        for (int i=0; i < s.Length; ++i)
        {
            if (hist[s[i]-'a'].HasValue)
            {
                hist[s[i] - 'a'] = Math.Abs(hist[s[i] - 'a'].Value) - i;
            }
            else
            {
                hist[s[i] - 'a'] = i;
            }
        }
        int result = int.MaxValue;
        bool found = false;
        for (int i = 0; i<26; i++)
        {
            if (hist[i].HasValue)
            {
                if (hist[i].Value>=0)
                {
                    found = true;
                    if (result > hist[i].Value) result = hist[i].Value;
                }
            }
        }
        if (found) return result;
        return -1;        
    }
}

**Expected behavior**
See the sections above. 

**Screenshots**
This solution is potentially O(N^2), however its run time is not worse than the O(N) solutions. Needs new test cases to make O(N^2)'s runtime longer. 
![image](https://user-images.githubusercontent.com/63358824/81210255-7d5f2b00-8f86-11ea-993a-eaad67cafcb4.png)

**Comment by CooperCooperCooper** [comment]
Hi @orbitbyrd ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @orbitbyrd ,
Thank you for your time. We've decided to keep the problem as is due to the team's design decision. We appreciate your support and understanding.
