### ISSUE TITLE
Missing Test Case - 1790. Check if One String Swap Can Make Strings Equal

### ISSUE THREAD

**Issue by Gauravtomar69** [LeetCode-Feedback/LeetCode-Feedback#2730]
#### Category of the bug
- [ ] Question
- [x] Solution
- [x] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@Gauravtomar69 Please provide the missing test case and the accepted code. Thank you!

**Comment by lc-kay** [comment]
Hi @Gauravtomar69 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
