### ISSUE TITLE
Missing Test Case - 275. H-Index II

### ISSUE THREAD

**Issue by jerrylin-jf** [LeetCode-Feedback/LeetCode-Feedback#2735]
#### Your LeetCode username

Hui_Hui

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

give wrong answer in example2 

#### Code you used for Submit/Run operation

```
// H-Index II
class Solution {
    fun hIndex1(citations: IntArray): Int {
        val size = citations.size
        for (i in 0 until size) {
            if (citations[i] >= size - i) {
                return size - i
            }
        }
        return 0
    }
}
```

#### Language used for code

Kotlin

#### Expected behavior

the expected answer is 2

#### Screenshots

<img width="343" alt="Screenshot 2021-03-14 at 14 53 52" src="https://user-images.githubusercontent.com/9306461/111073129-6f970200-84d5-11eb-9f6a-aed1a23f5900.png">
<img width="429" alt="Screenshot 2021-03-14 at 14 55 27" src="https://user-images.githubusercontent.com/9306461/111073135-73c31f80-84d5-11eb-9a1a-63d693dc3825.png">

**Comment by lc-kay** [comment]
@jerrylin-jf Our team was made aware of this issue through another contribution and fixed the issue. Thank you for your time.
