### ISSUE TITLE
Missing Test Case - 1792. Maximum Average Pass Ratio

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#2737]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution is accepted but fails on the following test case:

[[17780, 88110], [2036, 31711], [32275, 51933], [1218, 26682], [62127, 83357], [5799, 9772], [21491, 44800], [3197, 60658], [65875, 86973], [61303, 79948], [25281, 41818], [56164, 98446], [5252, 29686], [13932, 59729], [37906, 60263], [57699, 71582], [35941, 76897], [4644, 74267], [4049, 14969], [1, 1], [3081, 10660], [6017, 10508], [60099, 80155], [4344, 31227], [28868, 47981], [38261, 96000], [15294, 22693], [1574, 17207], [30460, 36289], [23112, 86631], [18869, 37949], [31780, 36479], [34680, 34988], [5711, 13519], [2036, 11247], [1481, 3305], [1123, 1650], [51836, 63455], [21389, 23614], [9066, 10813], [19213, 28975], [54170, 74047], [22573, 44547], [4105, 41410], [57493, 98326], [49394, 68157], [1671, 12725], [33, 456], [7387, 56547], [26948, 83132], [21157, 25359], [19875, 41651], [37877, 48543], [72254, 84552], [3480, 8954], [12778, 17237], [24665, 65842], [26007, 60110], [17628, 71332], [2161, 2946], [51873, 68252], [43, 87], [14945, 17629], [12492, 96809], [7628, 26405], [13370, 48216], [8330, 42836], [24600, 43698], [2691, 23669], [1015, 1732], [634, 50479], [32655, 96382], [45264, 88760], [10376, 47986], [8376, 76523], [4900, 9457], [979, 3027], [511, 1667], [44140, 60378], [87, 2240], [10526, 55641], [68725, 72329], [32382, 83082], [792, 5940], [7208, 55534], [32217, 90069]]
2981

#### Code you used for Submit/Run operation

```
import java.math.BigDecimal;
import java.math.RoundingMode;
class Solution {
    public double maxAverageRatio(int[][] classes, int extraStudents) {
		PriorityQueue<long[]> q = new PriorityQueue<>((x, y) -> {
			long r = (y[1] - y[0]) * (x[1] * x[1] - x[1]) - (x[1] - x[0]) * (y[1] * y[1] - y[1]);
			if (r > 0) {
				return 1;
			}
			if (r < 0) {
				return -1;
			}
			return 0;
		});
		for (int[] is : classes) {
			q.offer(new long[] { is[0], is[1] });
		}
		for (int i = 0; i < extraStudents; i++) {
			long[] poll = q.poll();
			poll[0]++;
			poll[1]++;
			q.offer(poll);
		}
		BigDecimal b = BigDecimal.ZERO;
		while (!q.isEmpty()) {
			long[] poll = q.poll();
			b = b.add(new BigDecimal(poll[0]).divide(new BigDecimal(poll[1]), 10, RoundingMode.HALF_UP));
		}
		return b.divide(new BigDecimal(classes.length), 10, RoundingMode.HALF_UP).doubleValue();
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/111075258-7ca7f700-84bd-11eb-9070-862e6d7e9219.png)

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
