### ISSUE TITLE
Missing Test Case - 1790. Check if One String Swap Can Make Strings Equal

### ISSUE THREAD

**Issue by gaoyike** [LeetCode-Feedback/LeetCode-Feedback#2738]
#### Category of the bug
- [ ] Question
- [1] Solution
- [ ] Language

#### Code you used for Submit/Run operation
```
class Solution {
    public boolean areAlmostEqual(String s1, String s2) {
        if(s1.equals(s2))
            return true;
        if(s1.length() != s2.length())
            return false;
        int n = s1.length();
        List<Integer> list = new ArrayList<>();
        for(int i = 0 ; i < n; i++) {
            if(s1.charAt(i) != s2.charAt(i)){
                list.add(i);
            }
        }
        if(list.size() == 0)
            return true;
        if(list.size() != 2)
            return false;
        return s1.charAt(list.get(0)) == s2.charAt(list.get(1));
    }
}
```

#### Language used for code
Java

#### Expected behavior
passed OJ, however, please try
"bank"
"canb"

**Comment by lc-kay** [comment]
Hi @gaoyike 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@gaoyike 
Thank you for your time. The team reviewed your report and noticed your solution fails on an earlier submitted test case, so we didn't add the test case. We appreciate your support!
