### ISSUE TITLE
Missing Test Case - 12. Integer to Roman

### ISSUE THREAD

**Issue by Martin-Tello** [LeetCode-Feedback/LeetCode-Feedback#2739]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by Martin-Tello** [comment]
LeetCode

**Comment by lc-kay** [comment]
@Martin-Tello Please provide your content-issue report with more details. Thank you!

**Comment by lc-kay** [comment]
Hi @Martin-Tello 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
