### ISSUE TITLE
621. Task Scheduler

### ISSUE THREAD

**Issue by sahajb** [LeetCode-Feedback/LeetCode-Feedback#274]
#### Your LeetCode username
habaj

**What kind of the bug**
- [ ] problem
- [x] solution
- [ ] language

**Describe the bug**
Solutions have inconsistent and confusing analysis

**Expected behavior**
Approach 1 Using Sorting [Accepted]
Time complexity : O(time). Number of iterations will be equal to resultant time time.

Approach 2 Using Priority-Queue [Accepted]
Time complexity : O(n). Number of iterations will be equal to resultant time time.

Approach 3 Calculating Idle slots [Accepted]
Time complexity : O(n). We iterate over tasks array only once.

n and time are being used interchangeably and creating ambiguity in Approach 2 analysis

**Comment by CooperCooperCooper** [comment]
Hi @sahajb ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by sahajb** [comment]
Any update @CooperCooperCooper ?

**Comment by CooperCooperCooper** [comment]
Hi @
Thank you for your time. We've used your feedback to update the problem. Would you please share your LeetCode username with us here so we can credit your account with the reward?

**Comment by sahajb** [comment]
Hello @CooperCooperCooper . Thank you for your response.
Updated the issue with the username.

**Comment by CooperCooperCooper** [comment]
Hi @sahajb ,
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
