### ISSUE TITLE
Missing Test Case - 1745. Palindrome Partitioning IV

### ISSUE THREAD

**Issue by sonpth** [LeetCode-Feedback/LeetCode-Feedback#2744]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Testcase

#### Description of the bug

Missing test case which allows few solutions accepted when they are should not

#### Code you used for Submit/Run operation

```
    public boolean checkPartitioning(String s) {
        return helper(s.toCharArray(), 0, 0);    
    }
    
    boolean helper(char[] cc, int s, int p) { // (in, start, pNum)
        if (p>3) return false;
        if (s==cc.length) return (p==3 || p==1);
        for (int i=cc.length-1; i>=s; i--) {
            if (isPalindrome(cc, s, i)) 
                return helper(cc, i+1, p+1);
        }
        return false;
    }

    boolean isPalindrome(char[] cc, int left, int right) {
        while (right > left)
            if (cc[right--]!=cc[left++]) 
                return false;
        return true; 
    }
```

#### Screenshots

![image](https://user-images.githubusercontent.com/1577921/111085845-58a3ee80-856d-11eb-808c-844ffb338f51.png)

**Comment by lc-kay** [comment]
Hi @sonpth 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @sonpth 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
