### ISSUE TITLE
Missing mut identifier - 535. Encode and Decode TinyURL

### ISSUE THREAD

**Issue by Odomontois** [LeetCode-Feedback/LeetCode-Feedback#2748]
#### Your LeetCode username
odomontois

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
A code template for `rust` explicitly says
```rust
/**
 * `&self` means the method takes an immutable reference.
 * If you need a mutable reference, change it to `&mut self` instead.
 */
```
Nevertheless, an attempt to change `encode` signature to `    fn encode(&mut self, long_url: String) -> String` leads to a compile error 

> Line 69, Char 30: cannot borrow `obj` as mutable, as it is not declared as mutable (solution.rs)
   |
68 |         let obj = Codec::new();
   |             --- help: consider changing this to be mutable: `mut obj`
69 |         let ret = obj.decode(obj.encode(param_1));
   |                              ^^^ cannot borrow as mutable

#### Code you used for Submit/Run operation

```rust
use std::collections::HashMap;

struct Codec {
    elems: HashMap<u64, String>,
    next: u64,
}

/**
 * `&self` means the method takes an immutable reference.
 * If you need a mutable reference, change it to `&mut self` instead.
 */
impl Codec {
    fn new() -> Self {
        Self {
            elems: HashMap::new(),
            next: 0,
        }
    }

    // Encodes a URL to a shortened URL.
    fn encode(&mut self, long_url: String) -> String {
        self.next += 1;
        self.elems.insert(self.next, long_url);
        format!("http://ti.ny/{:x}", self.next)
    }

    // Decodes a shortened URL to its original URL.
    fn decode(&self, short_url: String) -> String {
        let s = short_url.trim_start_matches("http://ti.ny/");
        let elem = u64::from_str_radix(s, 16).unwrap();
        self.elems[&elem].clone()
    }
}
```

#### Language used for code
Rust

#### Expected behavior
 Test runner should declare `obj` as mutable so it could be used by mutable reference

**Comment by lc-kay** [comment]
Hi @Odomontois 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Odomontois 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by Odomontois** [comment]
Hi, my LeetCode ID is `nizhnik`
