### ISSUE TITLE
代码模版错误-环形链表

### ISSUE THREAD

**Issue by lidaqi001** [LeetCode-Feedback/LeetCode-Feedback#275]
** Bug 类型**
- [ ✔] 题目

**描述**
环形链表代码模版错误
url：https://leetcode-cn.com/explore/interview/card/top-interview-questions-easy/6/linked-list/46/

**你使用的语言**
php

**期望行为**
修复模版

**屏幕截图**
![image](http://image.ldqsdy.com/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20200507093819.png)

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认的～

**Comment by feiceh** [comment]
你好，该题目技术验证没有问题的，请仔细阅读理解题目意思。后续刷题学习中遇到困难，也可以通过阅读题目评论和题解看到一些解题思路哦～
