### ISSUE TITLE
Image Of Output is Wrong  - 623. Add One Row to Tree

### ISSUE THREAD

**Issue by anilparmar111** [LeetCode-Feedback/LeetCode-Feedback#2750]
Problem Link   [https://leetcode.com/problems/add-one-row-to-tree/](url)

![image](https://user-images.githubusercontent.com/53622176/111150361-0508c380-85b4-11eb-9a44-8fde33644308.png)

In This Output Image Right Last Node Which Is With Value 1 Is Extra.

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

**Comment by anilparmar111** [comment]
In This Question's Example. In The Image's Output There Is 1 Extra Node 
![image](https://user-images.githubusercontent.com/53622176/111149842-6714f900-85b3-11eb-862d-ccf51e63c709.png)

**Comment by lc-kay** [comment]
@anilparmar111 Our content team has aware of this problem and fixed it. Thank you for your time.
