### ISSUE TITLE
Doesn't Require Encoding - 535. Encode and Decode TinyURL

### ISSUE THREAD

**Issue by vivpid** [LeetCode-Feedback/LeetCode-Feedback#2751]
#### Your LeetCode username
vivpid

#### Category of the bug
- [ ] Question
- Solution
- [ ] Language 

#### Description of the bug

The solution for this problem doesn't actually require any encoding. The code I have attached passed all test cases. There need to be a check if any encoding is actually done.

#### Code you used for Submit/Run operation

```
// Two Sum
public class Codec {
    public String encode(String longUrl) {
        String baseURL = "http://tinyurl/";
        return longUrl;
    }

    public String decode(String shortUrl) {
        return shortUrl;
    }
}
```

#### Language used for code
Java

**Comment by lc-kay** [comment]
Hi @vivpid 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@vivpid Although we are aware of this issue, it is not possible to check if the user actually encoded the string or not.
This is a practice problem, not a contest problem, so the user is able to submit a solution without encoding the string. However, in a real interview, they should know that they should have a real solution. Thank you for your time.
