### ISSUE TITLE
Missing Test Case - 262. Trips and Users

### ISSUE THREAD

**Issue by teki13** [LeetCode-Feedback/LeetCode-Feedback#2753]
#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language

#### Description of the bug

Test case 9: 

{"headers": {"Trips": ["Id", "Client_Id", "Driver_Id", "City_Id", "Status", "Request_at"], "Users": ["Users_Id", "Banned", "Role"]}, "rows": {"Trips": [["1", "1", "10", "1", "cancelled_by_client", "2013-10-04"]], "Users": [["1", "No", "client"], ["10", "No", "driver"]]}}

The Expected Solution is: {"headers":["Day","Cancellation Rate"],"values":[]}
The one I am getting and should be correct: {"headers": ["Day", "Cancellation Rate"], "values": [["2013-10-04", 1.00]]}

In the day there was a total of 1 trip and out of that 1 trip 1 was cancelled by a client who is not banned. Therefore the ratio should be 1.00 instead of []

#### Code you used for Submit/Run operation

```
SELECT w.Day, IFNULL(ROUND(t.Cancelled/w.Total,2),0) as 'Cancellation Rate' FROM 
(SELECT REQUEST_AT as Day, COUNT(1) as "Cancelled" from Trips T inner join Users U on T.Client_id  = U.Users_Id WHERE T.Status in ('cancelled_by_driver','cancelled_by_client') and U.Banned = "No" GROUP BY REQUEST_AT) as t 
RIGHT JOIN
(SELECT REQUEST_AT as Day, COUNT(1) as "Total" from Trips T inner join Users U on T.Client_id  = U.Users_Id WHERE U.Banned = "No" GROUP BY REQUEST_AT) as w on t.Day = w.Day;

```

**Comment by lc-kay** [comment]
@teki13 As stated in the problem description, "Write a SQL query to find the cancellation rate of requests with unbanned users (both client and driver must not be banned) each day between "2013-10-01" and "2013-10-03"." Your output includes  [["2013-10-04", 1.00]], which is not between "2013-10-01" and "2013-10-03". Thank you for your time.
