### ISSUE TITLE
Missing Test Case - 535. Encode and Decode TinyURL

### ISSUE THREAD

**Issue by nolueders** [LeetCode-Feedback/LeetCode-Feedback#2754]
#### Your LeetCode username
e418

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
class Solution {
public:
    // Encodes a URL to a shortened URL.
    string encode(string longUrl) { 
        m_url = longUrl;
        
        return "http://tinyurl.com/aaaa";
    }

    // Decodes a shortened URL to its original URL.
    string decode(string shortUrl) {

        return m_url;
    }
    
    std::string m_url;
};

// Your Solution object will be instantiated and called as such:
// Solution solution;
// solution.decode(solution.encode(url));
```

#### Language used for code
C++

#### Expected behavior

The question is very open to interpretation or question in an actual interview but the test cases seem kind of weak. My mentioned solution passed all test cases but is in my opinion not really what you should expect. It would fail anytime you encode more than one URL and try to get the first one back.

If you only work after the comment below stating how the solution is tested you pass by but as I said, I believe the intention is different here unless it shall be kind of a brain teaser or something ;)

#### Additional context
https://leetcode.com/submissions/detail/468220847/?from=explore&item_id=3673
Not sure if the URL works when for anyone or just my account.

**Comment by lc-kay** [comment]
Hi @nolueders 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@nolueders Although we are aware of this issue, it is not possible to check if the user actually encoded the string or not.
This is a practice problem, not a contest problem, so the user is able to submit a solution without encoding the string. However, in a real interview, they should know that they should have a real solution. Thank you for your time.
