### ISSUE TITLE
Course Schedule

### ISSUE THREAD

**Issue by AmanKumarMehra** [LeetCode-Feedback/LeetCode-Feedback#2758]
![Screenshot (8)](https://user-images.githubusercontent.com/77455854/111254058-3f1ca880-863a-11eb-9db4-673ad3570a7c.png)

please answer how to select 5 courses out of 4 courses available

**Comment by Anukul14** [comment]
bro go to the problem discussion (discuss) tab.

**Comment by lc-kay** [comment]
@AmanKumarMehra The expected output is correct. Please refer to the discuss section of the problem to raise your concerns. https://leetcode.com/problems/course-schedule/discuss/?currentPage=1&orderBy=newest_to_oldest&query= Thank you for your time.
