### ISSUE TITLE
658. Find K Closest Elements - Wrong Test Cases

### ISSUE THREAD

**Issue by AbbyDeng** [LeetCode-Feedback/LeetCode-Feedback#276]
**Passed Answer with LeetCode Expecting a Different Answer for a Test Case**
- [ ] [658. Find K Closest Elements](https://leetcode.com/problems/find-k-closest-elements/)
- [ ] in the "The code you submit/run" section
- [ ] Java

**Describe the bug**
My code passed as a right answer, however, when I was debugging, I found a test case where my code gave the right result but LeetCode was expecting a different one, which is wrong.

I've attached a screenshot and I've submitted it as a test case.

In this problem's description, "when there is a tie, smaller ones are preferred".
If the input is: arr = [1, 3], k = 1, x = 2 
it should be we are looking for **k = 1** point closest to **x = 2**
1 and 3 are a tie, and 1 should be returned since it's smaller. 

**what language is your code written in**
Java

**The code you submit/run**
```
// 658. Find K Closest Elements
class Solution {
     public List<Integer> findClosestElements(int[] arr, int k, int x) {
        int size = arr.length;

        int left = 0;
        int right = size - k;

        while (left < right) {
            int mid = left + (right - left) / 2;

            if (x - arr[mid] > arr[mid + k] - x) {
                left = mid + 1;
            } else {
                right = mid;
            }
        }

        List<Integer> res = new ArrayList<>();
        for (int i = left; i < left + k; i++) {
            res.add(arr[i]);
        }
        return res;
    }
}
```

**Expected behavior**
for input : arr = [1, 3], k = 1, x = 2 
the expected answer from LeetCode should be: 1 (not **Expected 3** in screenshot)

**Screenshots**
In the Screenshot, my code passed as accepted, but Wrong Answer is showing under the code.
for input : arr = [1, 3], k = 1, x = 2 
the expected answer from LeetCode should be: 1 (not **Expected 3** in screenshot)
![Screen Shot 2020-05-07 at 1 32 25 PM](https://user-images.githubusercontent.com/8296117/81342408-08fcb880-9068-11ea-9e9c-e22e7737abd5.png)

**Additional context**
In this problem's description, "when there is a tie, smaller ones are preferred".
If the input is: arr = [1, 3], k = 1, x = 2 
it should be we are looking for **k = 1** point closest to **x = 2**
1 and 3 are a tie, and 1 should be returned since it's smaller.

**Comment by CooperCooperCooper** [comment]
Hi @AbbyDeng ,
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
