### ISSUE TITLE
Missing Test Case - 219. Contains Duplicate II

### ISSUE THREAD

**Issue by xhyang19** [LeetCode-Feedback/LeetCode-Feedback#2761]
#### Your LeetCode username

xhyang19

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

A wrong solution will be accepted.

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean containsNearbyDuplicate(int[] nums, int k) {
        if (null == nums) {
            return false;
        }
        if (nums.length > 5000) {
            return false;
        }
        for (int i = 0; i < nums.length; i++) {
            for (int j = i + 1; j <= i + k && j < nums.length; j++) {
                if (nums[i] == nums[j]) {
                    return true;
                }
            }
        }
        return false;
    }
}
```

#### Expected behavior

We choose an all 1 array and its length is bigger than 5000. When k = 2, true is expected. However, the result is false and this solution is accepted.

**Comment by lc-kay** [comment]
@xhyang19 Please provide the test case in a .txt file. Thank you for your time.

**Comment by xhyang19** [comment]
Thanks for your feedback, the test case is attached now, and there is a screenshot for reference.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LeetCode-Feedback/LeetCode-Feedback"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月17日(星期三) 凌晨3:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LeetCode-Feedback/LeetCode-Feedback] Missing Test Case - 219. Contains Duplicate II (#2761)





 
@xhyang19 Please provide the test case in a .txt file. Thank you for your time.

**Comment by lc-kay** [comment]
@xhyang19 Can you please try attaching the file directly to the Github ticket? I don't think it attached/uploaded properly. Thanks in advance!

**Comment by xhyang19** [comment]
> @xhyang19 Can you please try attaching the file directly to the Github ticket? I don't think it attached/uploaded properly. Thanks in advance!

OK，the following are the test case and the screenshot.

![screenshot](https://user-images.githubusercontent.com/48120901/111557727-322dbf80-87c8-11eb-99f2-c8c5853093a0.png)
[test case.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6160592/test.case.txt)

**Comment by lc-kay** [comment]
Hi @xhyang19 
Thank you! I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @xhyang19 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
