### ISSUE TITLE
Missing Test Case - 756. Pyramid Transition Matrix

### ISSUE THREAD

**Issue by adematalay** [LeetCode-Feedback/LeetCode-Feedback#2762]
#### Your LeetCode username
aatalay

#### Category of the bug
- [X] Test Case
- [ ] Solution
- [ ] Language

#### Description of the bug
There is an edge case which is not tested.

My idea for this question was, if a pyramid can be constructed for left part of the bottom line and right part of the bottom line, then whole pyramid can be constructed.

left part => 1 character shorted substring from left
right part => 1 character shorted substring from right

This passed the all the test cases but this idea is not correct. For example, this cannot pass the following test case:

"DEFG"
["DEB", "EFC", "FGB", "BCA", "CBD"]

but since there is no similar test case in the suite, the solution seems passes. I recommend to add this test case to the suite.

#### Code you used for Submit/Run operation
```swift
class Solution {
    private var memo = [String: Bool]()
    var allowed: [String] = []
    lazy var map: [String: [String]] = {
        var tmp = [String: [String]]()
        for a in allowed {
            let p = String(a.prefix(2))
            let c = String(a.suffix(1))
            tmp[p] = (tmp[p] ?? []) + [c]
        }
        return tmp
    }()
    
    func pyramidTransition(_ bottom: String, _ allowed: [String]) -> Bool {
        if let k = memo[bottom] { return k }
        self.allowed = allowed
        if bottom.count <= 1 { return true }
        if bottom.count == 2 { return map[bottom] != nil }
        if bottom.count == 3 { 
            guard let left = map[String(bottom.prefix(2))], let right = map[String(bottom.suffix(2))] else { return false }
            var tmp = [String]()
            for l in left {
                for r in right {
                    if map["\(l)\(r)"] != nil { 
                        memo[bottom] = true 
                        return true
                    }
                }
            }
            memo[bottom] = false
            return false
        }
        
        let k = pyramidTransition(String(bottom.prefix(bottom.count - 1)), allowed) && pyramidTransition(String(bottom.suffix(bottom.count - 1)), allowed)
        memo[bottom] = k
        return k
    }
    
}
```

#### Language used for code
Swift

#### Expected behavior
I expect my code not to pass the question, but it passed

**Comment by lc-kay** [comment]
Hi @adematalay 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @adematalay 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
