### ISSUE TITLE
Missing Test Case - 714. Best Time to Buy and Sell Stock with Transaction Fee

### ISSUE THREAD

**Issue by sachinsinghjagawat** [LeetCode-Feedback/LeetCode-Feedback#2765]
#### Category of the bug
- [ ] Question
- [ ] testcase

#### Description of the bug

In the question constraints it is written :
1 < prices.length <= 5 * 10^4

But when I submitted it also had the test case:
[1]
0

#### Code you used for Submit/Run operation

```
no code required
```

#### Language used for code
C++

**Comment by lc-kay** [comment]
Hi @sachinsinghjagawat 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @sachinsinghjagawat 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
