### ISSUE TITLE
Missing Test Case - 478. Generate Random Point in a Circle

### ISSUE THREAD

**Issue by eloiman** [LeetCode-Feedback/LeetCode-Feedback#2766]
#### Your LeetCode username
ssdevel

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

I think tests for the tasks are wrong. What I noticed that there are a lot of solutions like follows:
1. find random radius;
2. find random angle;
3. calculate a new point.
Solutions of this kind successfully passed all checks.
However it's wrong solution. Let's just think about an area around the center of the circle and an area close to the edge of the circle. They are different. I don't say about the exact size of these areas, but the area around the center will be relatively smaller than the one which is closer to the edge of the circle. Consequently if we use that algo with a random radius and a random angle we will get more points in the area around the center, and less points closer to the edge of the circle. That is not naturally randomly and uniformly. The correct solution generates points uniformly across the whole area of the circle. It can be done via generating a point with random x and y until it is inside the circle area. It will give uniformly distribution by the area.
Here is the variant of code with the correct solution.

#### Code you used for Submit/Run operation

```
lass Solution {
public:
    const double radius_;
    const double x_center_;
    const double y_center_;
    
    Solution(double radius, double x_center, double y_center) :
    radius_(radius), x_center_(x_center), y_center_(y_center)
    {
        srand(time(nullptr));
    }
    
    vector<double> randPoint() {
        double x, y, r;
        do {
            x = (double) rand() / RAND_MAX - 0.5;
            y = (double) rand() / RAND_MAX - 0.5;
            r = sqrt(x * x + y * y);
        } while (r > 0.5);
        
        return {2. * x * radius_ + x_center_, 2. * y * radius_ + y_center_};
    }
};
```

#### Expected behavior

The correct solution generates points uniformly across the whole area of the circle. It can be done via generating a point with random x and y until it is inside the circle area. It will give uniformly distribution by the area.

**Comment by lc-kay** [comment]
Hi @eloiman 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by akorn1** [comment]
The only way this error propagates is if the random number generated is zero, since then the angle would have no affect then, so a point of (center,center) is _slightly_ more likely to occur than a different individual point.

**Comment by eloiman** [comment]
It's not almost right ;) I'm mostly talking about distribution along radius. Given that distribution is uniform, we can expect that number of points within range (0;r/2) will be the same as in (r/2;r). However, the areas which is based on these ranges will be different, the second area (r/2; r) is many times bigger than area based on (0;r/2). Since the number of points is the same,  distribution across areas will be different, because the areas are different. Consequently density of points will change from low to high if we go from the edge of the circle to its center. It's not uniform distribution across the circle area!

**Comment by lc-kay** [comment]
@eloiman The checker works independently and doesn't look into the approach. The checker checks that all the points returned are inside the circle and that all the points are random and uniformly distributed. I hope this answers your doubts and concerns. Thank you for your time.
