### ISSUE TITLE
Problem Description and Test Case Need to Be Updated - 377. Combination Sum IV

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#2768]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
For [377. Combination Sum IV](https://leetcode.com/problems/combination-sum-iv), it is possible that the answer is too large to fit in the range of a 32-bit integer.

The following code gets accepted. However, consider the following test case:
```
[1,2,3,4,5,6,7,8,9,10]
200
```
The following code returns `-2073382190`, which indicates that the answer does not fit in the range of a 32-bit integer. However, the test case meets all the constraints.

My suggestions are as follows.
1. Add the following statement in problem description, just before the first example.
   > Since the answer may be too large, return it **modulo** `10^9 + 7`.

   If this statement is added, it is guaranteed that the answer is non-negative and can fir in the range of a 32-bit integer.

2. Some test cases need to be updated so that the output is the original result modulo `10^9+7`. For example, the following test case returns `1132436852` now, and it should return `132436845` after modulo `10^9+7`.
   ```
   [2,1,3]
   35
   ```

#### Code you used for Submit/Run operation
```
class Solution {
    public int combinationSum4(int[] nums, int target) {
        int[] dp = new int[target + 1];
        dp[0] = 1;
        for (int i = 1; i <= target; i++) {
            for (int num : nums) {
                if (num <= i) {
                    dp[i] += dp[i - num];
                }
            }
        }
        return dp[target];
    }
}
```

#### Language used for code
Java

#### Expected behavior
1. Add the following statement in problem description, just before the first example.
   > Since the answer may be too large, return it **modulo** `10^9 + 7`.

2. Some test cases need to be updated so that the output is the original result modulo `10^9+7`. For example, the following test case returns `1132436852` now, and it should return `132436845` after modulo `10^9+7`.
   ```
   [2,1,3]
   35
   ```

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
