### ISSUE TITLE
Missing Test Case - 195. Tenth Line

### ISSUE THREAD

**Issue by cmunigwe** [LeetCode-Feedback/LeetCode-Feedback#2769]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
/# Read from the file file.txt and output the tenth line to stdout.
filename='file.txt'
n=0
while read line; do
# reading each line
n=$((n+1))
if [[ $n -eq 10 ]]
then
    echo $line
fi
done < $filename
```

**Comment by lc-kay** [comment]
@cmunigwe Please provide more details to your content-related issue report. Thank you!

**Comment by lc-kay** [comment]
Hi @cmunigwe 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
