### ISSUE TITLE
Something wrong with leetcode C compiler

### ISSUE THREAD

**Issue by xor1011** [LeetCode-Feedback/LeetCode-Feedback#277]
**What kind of the bug**
Memory Dump/Compiler error when attempting run the code on leetcode. 

**Describe the bug**
There is no issue beyond some warnings when the code is ran with GCC, yet the code will not work on the leetcode platform.

**what language is your code written in**
C

**The code you submit/run**
```
void reverseString(char *s, int sSize){
	int c=sSize;
	char *x=s;
	putchar(s[c]);
	c--;
	if (c>=0) reverseString(x, c);
}
```

**Expected behavior**
Input a character string "Hello friend"
print a character string backwards "dneirf olleH"

**Screenshots**
![image](https://user-images.githubusercontent.com/42688266/81371125-b1c00d80-9092-11ea-9d77-d9b1810d9164.png)

**Additional context**
the leetcode feedback
Runtime Error Message: =================================================================
==32==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000000015 at pc 0x000000401899 bp 0x7fffb77ba590 sp 0x7fffb77ba580
READ of size 1 at 0x602000000015 thread T0
    #2 0x7fdf8816882f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
0x602000000015 is located 0 bytes to the right of 5-byte region [0x602000000010,0x602000000015)
allocated by thread T0 here:
    #0 0x7fdf89183f88 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10bf88)
    #3 0x7fdf8816882f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
Shadow bytes around the buggy address:
  0x0c047fff7fb0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff7fc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff7fd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff7fe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff7ff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c047fff8000: fa fa[05]fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8010: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8020: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8030: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8040: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8050: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==32==ABORTING

**Comment by CooperCooperCooper** [comment]
Hi @xor1011 ,
Thank you for reaching out. May I ask which problem did you encounter this error at?

**Comment by xor1011** [comment]
the first recursion problem where you reverse a word.
https://leetcode.com/explore/featured/card/recursion-i/250/principle-of-recursion/1440/

**Comment by CooperCooperCooper** [comment]
Hi @xor1011 ,
Thank you for the clarification. Address sanitizer errors mean that during C/C++ runtime it caught invalid memory access in the program and this most commonly caused by an out-of-bounds array index access. In another word, your code needs to be revised so it will not use as much memory space as it does now. Hope this explanation helps.
