### ISSUE TITLE
Missing Test Case - 189. Rotate Array

### ISSUE THREAD

**Issue by melindajohnson** [LeetCode-Feedback/LeetCode-Feedback#2770]
Code work in java compiler and does not work in c#

#### Your LeetCode username
melistajohn 

#### Category of the bug
- [x] Solution

#### Description of the bug
Solution not compiling in c# and run into Time Limit Exceeded error

#### Code you used for Submit/Run operation

 ``` public class Solution {
    public void Rotate(int[] nums, int k) {        
        k = k % nums.Length;
        if (nums.Length > 1)
        {
            while(k != 0) // DO this k times
            {
                RotateOne(nums);
                k--;
            }
        }
    }
    public static void RotateOne(int[] nums)
    {
        int last = 0;
        for(int i = nums.Length - 1; i >= 0 ; i--){
			if(i == nums.Length -1)
            {
                //Save last
                last = nums[nums.Length-1];
                //Put second to last, in the last position
                nums[nums.Length-1] = nums[nums.Length -2];
            }
            else if(i != 0 && i > 0)
            {
                //Shift to the right
                nums[i+1] = nums[i];
            }
            else if(i == 0){
                //shift to the right
                nums[i+1] = nums[i];
                //put temp value in first position
                nums[i] = last;
            }	
		}      
    }
}

```

#### Language used for code
C#

#### Expected behavior
Solution not accepted in C# even though accepted in java, runs into Time Limit Exceeded error

**Comment by lc-kay** [comment]
@melindajohnson Thank you for reaching out to us. As each language's environment is different, we don't recommend comparing solutions across languages. We recommend checking https://leetcode.com/problems/rotate-array/discuss/?currentPage=1&orderBy=most_relevant&query=C%23 for accepted solutions and see how to optimize your code.

**Comment by melindajohnson** [comment]
@lc-kay , The c# solution posted compiles in other ide and not in leetcode. Please check

**Comment by lc-kay** [comment]
@melindajohnson Unfortunately, we are unable to differentiate behaviors from other IDE. It appears your code needs to be optimized to pass the time limit.
