### ISSUE TITLE
301. 删除无效的括号 数据范围未更新

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#2774]
**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名
hqztrue

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
描述你遇到的 bug
US站增加了数据范围限制1 <= s.length <= 25，而CN站未同步更新。

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
@hqztrue 你好，该题中文题面已调整更新，力扣会定期更新，保障稳定和体验优化。
