### ISSUE TITLE
Test Case Typo-Generate Random Point in a Circle

### ISSUE THREAD

**Issue by akorn1** [LeetCode-Feedback/LeetCode-Feedback#2776]
#### Your LeetCode username
akorn1

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
After running my test cases under slightly varying circumstances, I seem to get all test cases right except for one. After perusing through some of the hundreds of entries for a bug check, I still couldn't find anything wrong, but upon examining the expected output I found what appears to be a newline character right before the final closing bracket. This is handled outside of my program and the purview of this assignment, so I believe this test case was accidentally edited, or some other bug-related side effects are going on.

#### Code you used for Submit/Run operation
```
import java.util.Random;
class Solution {
    private double radius;
    private double x_center;
    private double y_center;
    private double theta;
    private static final double TWO_PI = 2*3.1415926535897932;
    public Solution(double radius, double x_center, double y_center) {
        this.radius = radius;
        this.x_center = x_center;
        this.y_center = y_center;
    }
    
    public double[] randPoint() {
        Random generator = new Random();
        double rad = radius*(generator.nextDouble());
        theta = TWO_PI*(generator.nextDouble());
        double x_val = x_center + (rad*Math.cos(theta));
        double y_val = y_center + (rad*Math.sin(theta));
        double[] answer = new double[2];
        answer[0] = x_val;
        answer[1] = y_val;
        return answer;
    }
}
```

#### Language used for code
Java

#### Expected behavior
 I expected to find some sort of even remotely identifiable error in either my math, my distribution, or my formatting, but I couldn't find any errors similar to above, and I believe a whitespace character may have jeopardized the test case. 

#### Screenshots

N/A
#### Additional context

N/A

**Comment by lc-kay** [comment]
Hi @akorn1 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@akorn1 Our team has reviewed your report and found the issue to be a bug in your code. Please refer to the discuss section to raise your question or check out accepted solutions from other users. Thank you for your time.
