### ISSUE TITLE
Wrong Test Case - 823. Binary Trees With Factors

### ISSUE THREAD

**Issue by kiritoty** [LeetCode-Feedback/LeetCode-Feedback#2777]
#### Your LeetCode username

Kiritoty

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

One of the test cases is wrong (Test case 49 : [2,4,5,5,10]). In question description, it said "Given an array of unique integers", but the test case includes duplicate integers.

#### Code you used for Submit/Run operation

```
class Solution {
    public int numFactoredBinaryTrees(int[] arr) {
        Arrays.sort(arr);
        
        long[] dp = new long[arr.length];
        Arrays.fill(dp, 1);
        long res = 0;
        
        for(int i = 0; i < arr.length; i++) {
            int left = 0;
            int right = i-1;
            
            while(left <= right) {
                if(arr[i] % arr[left] == 0 && arr[i]/arr[left] == arr[right]) {
                    if(left == right) {
                        dp[i] += dp[left] * dp[right];
                    } else {
                        dp[i] += dp[left] * dp[right] * 2;
                    }
                    right--;
                } else if (arr[left] * arr[right] > arr[i]) {
                    right--;
                } else {
                    left++;
                }
            }
            res += dp[i];
        }
        
        return (int)(res % 1_000_000_007);
    }
}
```

#### Language used for code

Java

#### Expected behavior

Test cases should not have a duplicate integer. 

#### Screenshots

N/A

#### Additional context

N/A

**Comment by alexbprofit** [comment]
each number may be used for any number of times

**Comment by alexbprofit** [comment]
My test case also contains duplicate numbers, #2701.

**Comment by kiritoty** [comment]
> My test case also contains duplicate numbers, #2701.

When I put your test case into the console, it shows "Invalid Testcase expected variables arr[0]:3 and arr[7]:3 to have different values".

And when I check the test cases today, they are remove test case 49

**Comment by alexbprofit** [comment]
When my test case is added, count of test case equals 50

**Comment by alexbprofit** [comment]
I get 100 LeetCoins when my test case is validated and added

**Comment by kiritoty** [comment]
> I get 100 LeetCoins when my test case is validated and added

But in the question description, it specifically said "unique integers". I assume it's mean no duplicate integers. If you put your test case now, you will see invalid test cases.

**Comment by alexbprofit** [comment]
![image](https://user-images.githubusercontent.com/57172679/111645109-17c80600-8809-11eb-8191-98ac175b53ff.png)

**Comment by alexbprofit** [comment]
But 
![image](https://user-images.githubusercontent.com/57172679/111645406-578eed80-8809-11eb-8aac-6e1531c5cd7a.png)

**Comment by alexbprofit** [comment]
it turns out I received this award undeservedly?

**Comment by alexbprofit** [comment]
@lc-kay Is it possible to deprive me of this award?

**Comment by kiritoty** [comment]
> it turns out I received this award undeservedly?

Each number may be used any number of times doesn't mean the input array should have a duplicate integer. Think about the test case [5, 25], the answer is 3 because you can build the following tree [5], [25], [5,5,25]. Getting the award also doesn't mean it's right. 

Simply put your test case into the Leetcode console now and you will see it shows invalid test cases.

Personally, I don't care about any award, I just want to make better question and test cases.

**Comment by lc-kay** [comment]
@kiritoty This issue was reported through our help center and our team removed all test cases that are not an array of unique integers. Thank you for your time. 

@alexbprofit As we didn't catch that your test case did not satisfy our constraints, we will not take back the points.
