### ISSUE TITLE
Wrong description [376. Wiggle Subsequence]

### ISSUE THREAD

**Issue by sekhar179** [LeetCode-Feedback/LeetCode-Feedback#2778]
#### Your LeetCode username

sekhar179

#### Category of the bug
- [ x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Any sequence with 2 or less elements is a trivial Wiggle Subsequence.
But the description says **"A sequence with fewer than _two_ elements is trivially a wiggle sequence."**
The above description doesn't cover a subsequence of length 2.
It should be modified to **"A sequence with fewer than _three_ elements is trivially a wiggle sequence."**

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior

Modify the description as suggested.
Also we need to modify all the solutions handling this case.

**Comment by lc-kay** [comment]
Hi @sekhar179 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @sekhar179 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
