### ISSUE TITLE
Ambiguous solution - 14. Longest Common Prefix

### ISSUE THREAD

**Issue by huyvohcmc** [LeetCode-Feedback/LeetCode-Feedback#2779]
#### Your LeetCode username
huyvohcmc

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language

#### Description of the bug
Longest common prefix problem: https://leetcode.com/problems/longest-common-prefix/solution/
Solution: vertical scanning (approach 2):
> Imagine a very short string is at the end of the array.

It should be "Imagine a very short string is *the common prefix* at the end of the array."

**Comment by lc-kay** [comment]
Hi @huyvohcmc 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @huyvohcmc 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
