### ISSUE TITLE
Additional test cases in "Check if it is a straight line"

### ISSUE THREAD

**Issue by Jazzinghen** [LeetCode-Feedback/LeetCode-Feedback#278]
## What kind of the bug
- [ ] problem
- [✔️] solution
- [ ] language

## Description
Some of the faster solutions do not consider straight vertical lines (i.e. all points on x)

[This is the problem][1]

## What language is the code of the broken solutions
C++

## The submitted code
```c++
class Solution {
public:
    bool checkStraightLine(vector<vector<int>>& coordinates) {
        //y=mx+c
        //Find m
        double m=0;
        double num=coordinates[1][1]-coordinates[0][1];
        double den=coordinates[1][0]-coordinates[0][0];
        m=(num/den);
        double c=(coordinates[0][1]-(m*coordinates[0][0]));
        
        for(int i=2;i<coordinates.size();i++)
        {
            if((coordinates[i][1]-(m*coordinates[i][0]))!=c)
                return false;
        }
        
        return true;
        
    }
};
```

## Expected behavior
Due to how `m` (or the function slope) is computed here, the division `m = (num/den);` should throw a division by zero exception.

I encountered the error while writing my solution because I computed the slope between the first and the last value, instead of the first and the second. In one of the inputs the first and last points have the same x, making my code break. I had to code a specific logic to check for that because there's no real way to check for values all on a vertical line (that I know of).

I think that adding one test with all the values on a straight vertical line (which should be a valid input) would help in checking that corner case.

[1]: https://leetcode.com/explore/featured/card/may-leetcoding-challenge/535/week-2-may-8th-may-14th/3323/

**Comment by sasa-stanko** [comment]
By IEEE 754 standard, dividing finite non-zero floating point by zero doesn't throw exception. Instead it returns +/- infinity. So this part of the code is correct.

It also gives correct answer (true) if all the points are on the vertical line. Where it fails is if some points are on the vertical line and some are not. For example, (1,0), (1,1), (2,2).

**Comment by Jazzinghen** [comment]
Oh, I found why I was having issues.
I am going back to integer representation during point checks to have a consistent variable type to check them.
Thanks for pointing me in the right direction.

**Comment by AnthonyMikh** [comment]
> By IEEE 754 standard, dividing finite non-zero floating point by zero doesn't throw exception. Instead it returns +/- infinity. So this part of the code is correct.
> 
> It also gives correct answer (true) if all the points are on the vertical line.

@sasa-stanko actually it is incorrect. The problem is that calculated slope of line in this corner case depends not only on coordinates of point but also on their mutual arrangement. For example, in test case
```
[[0, 0], [0, 1], [0, -1]]
```
the calculated slope between first and second points is positive infinity but calculated slope between first and third points is negative infinity, even though all three points lie on the same line. I believe that's the reason @Jazzinghen's solution sometimes give wrong result. Also they is certainly not the only one who made the same mistake. For example, the following top Rust solution
```rust


impl Solution {
    pub fn check_straight_line(coordinates: Vec<Vec<i32>>) -> bool {
        let slope = |x1,x2,y1,y2| ( (y2-y1) as f64) / ( (x2-x1) as f64);
        let slope_initial = slope(&coordinates[0][0], &coordinates[1][0], &coordinates[0][1], &coordinates[1][1]);
        coordinates.iter()
        .zip(coordinates.iter().skip(1))
        .all(|(vec1, vec2)| {
            slope(&vec1[0], &vec2[0], &vec1[1], &vec2[1]) == slope_initial
        })
    }
}
```
also incorrectly gives `false` for testcase above. I think that this testcase should be included in test suite for the problem since correct solution should handle such a corner case.

@CooperCooperCooper could you be so kind to reopen this issue?

**Comment by kb54** [comment]
@AnthonyMikh completely agreed. 
Here is one among the many of the c++ accepted solutions which fails over your provided test case.
```class Solution {
public:
    bool checkStraightLine(vector<vector<int>>& coordinates) {
        //y=mx+c
        //Find m
        double m=0;
        double num=coordinates[1][1]-coordinates[0][1];
        double den=coordinates[1][0]-coordinates[0][0];
        m=(num/den);
        double c=(coordinates[0][1]-(m*coordinates[0][0]));
        
        for(int i=2;i<coordinates.size();i++)
        {
            if((coordinates[i][1]-(m*coordinates[i][0]))!=c)
                return false;
        }
        
        return true;
        
    }
};
```
