### ISSUE TITLE
Missing Test Case - 97. Interleaving String

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#2783]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Official Java Solution 2 is accepted but fails on the following test case:

"aaaa"
"aa"
"aaa"

#### Code you used for Submit/Run operation

```
 public class Solution {
    public boolean is_Interleave(String s1, int i, String s2, int j, String s3, int k, int[][] memo) {
        if (i == s1.length()) {
            return s2.substring(j).equals(s3.substring(k));
        }
        if (j == s2.length()) {
            return s1.substring(i).equals(s3.substring(k));
        }
        if (memo[i][j] >= 0) {
            return memo[i][j] == 1 ? true : false;
        }
        boolean ans = false;
        if (s3.charAt(k) == s1.charAt(i) && is_Interleave(s1, i + 1, s2, j, s3, k + 1, memo)
                || s3.charAt(k) == s2.charAt(j) && is_Interleave(s1, i, s2, j + 1, s3, k + 1, memo)) {
            ans = true;
        }
        memo[i][j] = ans ? 1 : 0;
        return ans;
    }
    public boolean isInterleave(String s1, String s2, String s3) {
        int memo[][] = new int[s1.length()][s2.length()];
        for (int i = 0; i < s1.length(); i++) {
            for (int j = 0; j < s2.length(); j++) {
                memo[i][j] = -1;
            }
        }
        return is_Interleave(s1, 0, s2, 0, s3, 0, memo);
    }
}
```

#### Language used for code

Java

#### Expected behavior

There are two alternatives:
1. the solution should not be accepted, official Java solution 2 should be fixed by adding the following verification:
```
        if (s1.length() + s2.length() != s3.length()) {
            return false;
        }
```

or

2. Additional constraint should be added to problem description: s1.length + s2.length = s3.length. In this case online judge should enforce this constraint

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/111710579-51583b80-8820-11eb-890f-e3ca8adb06f0.png)

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
