### ISSUE TITLE
Missing Test Case - 97. Interleaving String

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#2784]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution is accepted but fails on the following test case:

"aaaaaaaaaaaaaaaaaaaaaaaaaaa"
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

#### Code you used for Submit/Run operation

```
public class Solution {
    public boolean isInterleave(String s1, String s2, String s) {
        return isInterleave(s1, s1.length()-1, s2, s2.length()-1, s, s.length()-1);
    }
    
    
    public boolean isInterleave(String s1, int i1, String s2, int i2, String s, int i){
        if(i<0){
            if(i1<0 && i2<0) return true;
            else    return false;
        }
        
        if(i1 >= 0 && s1.charAt(i1)==s.charAt(i) && isInterleave(s1,i1-1,s2,i2,s,i-1))
            return true;
            
        if(i2 >= 0 && s2.charAt(i2)==s.charAt(i) && isInterleave(s1,i1,s2,i2-1,s,i-1))
            return true;
        return false;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/111711530-55855880-8822-11eb-8270-012755a22f36.png)

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
