### ISSUE TITLE
#609 - Ambiguous Test Result

### ISSUE THREAD

**Issue by DavyC** [LeetCode-Feedback/LeetCode-Feedback#2785]
#### Your LeetCode username
fatezai

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language

#### Description of the bug
A double slashes was expected in a file path.

One may argue that it's not really a bug, because double slashes would still work in a file system. However, it's definitely not intuitive (nor something I would see from any file path manipulation output), where `//5.txt` is expected, instead of `/5.txt`, in the test case provided in the screenshot below.

#### Code you used for Submit/Run operation
Not Necessary

#### Language used for code
JAVA

#### Expected behavior
To be intuitive, one would expect a single slash over double slashes while root `/` is given.

#### Screenshots
<img width="879" alt="Screen Shot 2021-03-18 at 10 02 00" src="https://user-images.githubusercontent.com/52217/111725764-a2a90f00-88a2-11eb-84d0-5cb948f39ef7.png">

#### Additional context
NONE

**Comment by lc-kay** [comment]
Hi @DavyC 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @DavyC 
Thank you for your time. The team reviewed your report and has updated the validator. The input provided is not accepted anymore. We appreciate your support!
