### ISSUE TITLE
Runtime information C++

### ISSUE THREAD

**Issue by sureshiyengar** [LeetCode-Feedback/LeetCode-Feedback#279]
Since past few weeks, I am observing high variability in the runtime information (C++) on submission. For instance, for one of the code (which I know is optimum and matches the fastest submission), the runtime showed various info ranging from "faster than ~20%" to faster than ~94% of C++ online submissions. 

Are others facing this issue?

**Comment by CooperCooperCooper** [comment]
Hi @sureshiyengar ,
Thank you for reaching out. For this issue, please reach out to our main support channel "support@leetcode.com" for more information. We appreciate your time and support.
