### ISSUE TITLE
[1543] Example in the description is wrong

### ISSUE THREAD

**Issue by endersuu** [LeetCode-Feedback/LeetCode-Feedback#2791]
#### Your LeetCode username

enders_uu

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

```
Result table:
+--------------+--------------+----------+
| product_name | sale_date    | total    |
+--------------+--------------+----------+
| lcphone      | 2000-01      | 2        |
| lckeychain   | 2000-02      | 2        | 
| lcphone      | 2000-02      | 1        | 
| matryoshka   | 2000-03      | 1        | 
+--------------+--------------+----------+
```

should be
```
Result table:
+--------------+--------------+----------+
| product_name | sale_date    | total    |
+--------------+--------------+----------+
| lckeychain   | 2000-02      | 2        | 
| lcphone      | 2000-01      | 2        |
| lcphone      | 2000-02      | 1        | 
| matryoshka   | 2000-03      | 1        | 
+--------------+--------------+----------+
```

#### Code you used for Submit/Run operation

I borrowed the code from [here](https://leetcode.com/problems/fix-product-name-format/discuss/1116643/Simple-MySQL-solution-(trim-lower-date_format))
```SQL
select trim(lower(product_name)) as PRODUCT_NAME, date_format(sale_date, "%Y-%m") as SALE_DATE, count(sale_id) as TOTAL
from Sales
group by 1, 2
order by 1, 2
```

#### Language used for code

SQL

#### Expected behavior

{"headers": ["PRODUCT_NAME", "SALE_DATE", "TOTAL"], "values": [["lckeychain", "2000-02", 2], ["lcphone", "2000-01", 2], ["lcphone", "2000-02", 1], ["matryoshka", "2000-03", 1]]}

**Comment by lc-kay** [comment]
Hi @endersuu 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @endersuu 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
