### ISSUE TITLE
Missing Test Case - 823. Binary Trees With Factors

### ISSUE THREAD

**Issue by fedotenko** [LeetCode-Feedback/LeetCode-Feedback#2792]
#### Your LeetCode username
froman

#### Category of the bug
- [ ] Question
- [*] Solution
- [ ] Language

#### Description of the bug
This test case could fail solutions without the usage of modulo operation for intermediate results because it leads to overflow.

#### Code you used for Submit/Run operation
```
[2,4,8,16,32,64,128,256,512,1024,2048,4096,8192,16384,32768,65536,131072,262144,524288,1048576,2097152,4194304,8388608,16777216,33554432,67108864,134217728,268435456,536870912]
```

#### Language used for code
Javscript

#### Additional context
I  found that there is no such test while was looking on this solution: https://leetcode.com/problems/binary-trees-with-factors/discuss/1107268/JS-Python-Java-C%2B%2B-or-Fastest-Solution-w-Explanation

**Comment by lc-kay** [comment]
@fedotenko I ran the test case with the solutions provided in the discuss post, and the test case passes for the Javascript solution. Please provide a code that this test case will fail, then I will reopen this issue for investigation. Thank you for your time.
