### ISSUE TITLE
Missing Test Case - 415. Add Strings

### ISSUE THREAD

**Issue by alexbprofit** [LeetCode-Feedback/LeetCode-Feedback#2793]
#### Your LeetCode username
user8391WG

#### Category of the bug
- [ ] Solution
- [x] Question
- [ ] Language

#### Description of the bug
the solution is accepted but fails on the following test case
```
"0\n"
"0\n"
```

#### Code you used for Submit/Run operation

```
class Solution:
    def addStrings(self, num1: str, num2: str) -> str:
        return str(int(num1) + int(num2))
```

#### Language used for code
Python 3

#### Expected behavior
The solution should not be accepted

#### Screenshots
![image](https://user-images.githubusercontent.com/57172679/111869109-62bb5800-8986-11eb-9fcf-d25e63a4c957.png)

**Comment by lc-kay** [comment]
Hi @alexbprofit 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @alexbprofit 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
