### ISSUE TITLE
Missing Test Case - 1396. Design Underground System

### ISSUE THREAD

**Issue by cgsgak1** [LeetCode-Feedback/LeetCode-Feedback#2794]
#### Your LeetCode username
cgsgak1

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Missing testcase

#### Code you used for Submit/Run operation
```
class UndergroundSystem {
    unordered_map<int, pair<string, int>> cust;
    unordered_map<string, pair<double, double>> m;
public:
    UndergroundSystem() {
    }
    
    void checkIn(int id, string stationName, int t) {
        cust[id] = {stationName, t};
    }
    
    void checkOut(int id, string stationName, int t) {
        const auto& it = cust[id];
        const auto& tmp = it.first + "" + stationName;
        m[tmp].first += t - cust[id].second;
        ++m[tmp].second;
    }
    
    double getAverageTime(string startStation, string endStation) {
        const auto& tmp = startStation + "" + endStation;
        
        return m[tmp].first / m[tmp].second;
    }
};
```

#### Language used for code
C++

#### Expected behavior
The solution was accepted by system, but it doesn't pass correctly the followiong testcase:

["UndergroundSystem","checkIn","checkIn","checkIn","checkOut","checkOut","checkOut","getAverageTime","getAverageTime","checkIn","getAverageTime","checkOut","getAverageTime"]
[[],[45,"a",3],[32,"aa",8],[27,"a",10],[45,"ab",15],[27,"ab",20],[32,"b",22],["aa","b"],["a","ab"],[10,"a",24],["a","ab"],[10,"ab",38],["a","ab"]]

#### Screenshots
![image](https://user-images.githubusercontent.com/34144576/111870040-55589a80-8993-11eb-87a5-9c6b6a99aff4.png)
![image](https://user-images.githubusercontent.com/34144576/111870049-673a3d80-8993-11eb-97d6-ab45eb719c64.png)

**Comment by lc-kay** [comment]
Hi @cgsgak1 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @cgsgak1 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
