### ISSUE TITLE
Missing Test Case - 1796. Second Largest Digit in a String

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#2795]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution is accepted but fails on the following test:

"1a0"

#### Code you used for Submit/Run operation

```
class Solution {
    public int secondHighest(String s) {
        int len=s.length();
        int a;
        int flag=0;
        char[] ch = s.toCharArray();
        char tmp1='0';
        char tmp2='0';
        for(int i=0;i<len;i++){
            if(ch[i]<='9' && ch[i]>='0'){
               if(ch[i]>=tmp1){
                   if(tmp1> tmp2 && tmp1<ch[i]){
                       tmp2=tmp1;
                   }
                   tmp1=ch[i];
                   if(ch[i]=='0'){
                       flag=1;
                   }
               }else if(ch[i]>=tmp2){
                   tmp2=ch[i];
                   if(ch[i]==0){
                       flag=1;
                   }
                       
               }
            }
        }
        if(tmp1 != tmp2 ){
            if(tmp2=='0' && flag==0){
                return -1;
               
            }else{
                a=tmp2-'0';
                return a;
                
            }
            
        }
        else
            return -1;

    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/111876829-ed945680-8976-11eb-9a31-9a62d53fd4ec.png)

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
