### ISSUE TITLE
Missing Test Case - 1799. Maximize Score After N Operations

### ISSUE THREAD

**Issue by h493** [LeetCode-Feedback/LeetCode-Feedback#2798]
#### Your LeetCode username
`HIMANSHUCHHIKARA `

#### Category of the bug
- [x] Question ( haven't mentioned anywhere array is sorted but all test cases are sorted)

#### Code you used for Submit/Run operation
```
class Solution {
    public int maxScore(int[] nums) {
        int ans=0;
        int n=nums.length;
        PriorityQueue<Pair> pq=new PriorityQueue<>();
        
        for(int i=0;i<nums.length;i++){
          for(int j=i+1;j<nums.length;j++){
              int x=nums[i];
              int y=nums[j];
              int g=gcd(x,y);
              Pair np=new Pair(i,j,g);
              pq.add(np);
          }  
        }
        
       boolean[] visited=new boolean[n];
        int operationNumber=n/2;
       
        while(pq.size()>0 && operationNumber>0){
            Pair top=pq.remove();
            if(!visited[top.x] && !visited[top.y]){
                ans+=operationNumber*top.g;
                operationNumber--;
                visited[top.x]=true;
                visited[top.y]=true;
            }
        }
        
        return ans;
    }
    
    private int gcd(int a,int b){
         if(a==0) return b;
         
        return gcd(b%a,a);
    }
    
    public class Pair implements Comparable<Pair>{
        int x; // x: idx of x
        int y; // y: idx of y
        int g;
        
        Pair(int x,int y,int g){
            this.x=x;
            this.y=y;
            this.g=g;
        }
        
        @Override
        public int compareTo(Pair other){
            if(this.g==other.g) return this.x-other.x;
            return other.g-this.g;
        }
    }
}
```

#### Language used for code
JAVA

#### Expected behavior
Expected error on unsorted array testcases as I have not sorted the array but they haven't used such testcase.
they have missed test cases like. : [36,6,6,4] here array is not sorted my answer should be wrong but my code passed all the testcases.

**Comment by h493** [comment]
**Your LeetCode username**
`HIMANSHUCHHIKARA`

**Category of the bug**
` Question`

**Description of the bug**
 (haven't mentioned anywhere array is sorted but all test cases are sorted . Solution should not work on testcases like [36,6,6,4]

**Code you used for Submit/Run operation**
```
class Solution {
    public int maxScore(int[] nums) {
        int ans=0;
        int n=nums.length;
        PriorityQueue<Pair> pq=new PriorityQueue<>();
        
        for(int i=0;i<nums.length;i++){
          for(int j=i+1;j<nums.length;j++){
              int x=nums[i];
              int y=nums[j];
              int g=gcd(x,y);
              Pair np=new Pair(i,j,g);
              pq.add(np);
          }  
        }
        
       boolean[] visited=new boolean[n];
        int operationNumber=n/2;
       
        while(pq.size()>0 && operationNumber>0){
            Pair top=pq.remove();
            if(!visited[top.x] && !visited[top.y]){
                ans+=operationNumber*top.g;
                operationNumber--;
                visited[top.x]=true;
                visited[top.y]=true;
            }
        }
        
        return ans;
    }
    
    private int gcd(int a,int b){
         if(a==0) return b;
         
        return gcd(b%a,a);
    }
    
    public class Pair implements Comparable<Pair>{
        int x; // x: idx of x
        int y; // y: idx of y
        int g;
        
        Pair(int x,int y,int g){
            this.x=x;
            this.y=y;
            this.g=g;
        }
        
        @Override
        public int compareTo(Pair other){
            if(this.g==other.g) return this.x-other.x;
            return other.g-this.g;
        }
    }
}
```
**Language used for code**
JAVA

**Expected behavior**
Expected error on unsorted array testcases as I have not sorted the array but they haven't used such testcase.
they have missed test cases like. : [36,6,6,4] here array is not sorted my answer should be wrong but my code passed all the testcases.

**Screenshots**
<img width="1440" alt="Screen Shot 2021-03-20 at 11 48 15 PM" src="https://user-images.githubusercontent.com/56367300/111881908-bd7d9f80-89d8-11eb-9ef9-55d709e99c13.png">

**Comment by alexbprofit** [comment]
![image](https://user-images.githubusercontent.com/57172679/111900886-a755fa80-8a3d-11eb-90ed-233cfcb5ff69.png)

**Comment by alexbprofit** [comment]
Maybe error contains into your program?

**Comment by h493** [comment]
> Maybe error contains into your program?

Actually leetcode is missing this case. i know my code is wrong but it has passed all the given testcases.

**Comment by lc-kay** [comment]
Hi @h493 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@h493 Thank you for your time. The team reviewed your report and decided to not add this test case. We appreciate your support!

**Comment by h493** [comment]
hey sir , will I get some leetcode points for this 😅 because I am looking
to buy premium through points for 1 month.
Thanks
Himanshu
