### ISSUE TITLE
PHP - binary-tree-zigzag-level-order-traversal

### ISSUE THREAD

**Issue by pjcfifa** [LeetCode-Feedback/LeetCode-Feedback#28]
**What kind of the bug**
- [x] problem
- [ ] solution

**Describe the bug**
Line 7: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Serializer::serializeArray() must be of the type array, null given, called in /leetcode/precompiled/serializer.php on line 79 and defined in serializer.php
Stack trace:
#0 serializer.php: Serializer->serializeArray(NULL, 'list<integer>')
#1 solution.php: Serializer->serialize(NULL, 'list<list<integ...')
#2 {main}

**The code you submit/run**
```
class Solution {

    /**
     * @param TreeNode $root
     * @return Integer[][]
     */
    function zigzagLevelOrder($root) {
        
    }
}
```

**Expected behavior**
Not an error. This is the default boilerplate code

**Comment by CooperCooperCooper** [comment]
Hi @pjcfifa,
Thank you for reaching out to us. Please return a second array type to prevent this error from appearing.
