### ISSUE TITLE
1421. NPV Queries - Indeterministic Judge

### ISSUE THREAD

**Issue by ecmarsh** [LeetCode-Feedback/LeetCode-Feedback#280]
**What kind of the bug**
- [X] problem
- [ ] solution
- [ ] language

**Describe the bug**
The OJ is not deterministic. Same code gave different results.

**what language is your code written in**
MSSQL

**The code you submit/run**
```sql
// NPV Queries
select
    a.id,
    a.year,
    coalesce(b.npv, 0) npv 
from queries a    
left join npv b
on a.id = b.id and a.year = b.year
```

**Expected behavior**
The same solution to return the same result (accepted/error/fail).

**Screenshots**

> NOTE: Code is the same in both submissions

**Submission accepted**:
<img width="1176" alt="1421_accepted_solution-screenshot" src="https://user-images.githubusercontent.com/17396261/81459331-3b83df80-9154-11ea-9dfb-c216a76cf143.png">

**Submission runtime error**:
<img width="1187" alt="1421_runtime-error-screenshot" src="https://user-images.githubusercontent.com/17396261/81459339-43dc1a80-9154-11ea-8f1e-61746a3a8c6d.png">

**Additional context**
N/A

**Comment by CooperCooperCooper** [comment]
Hi @ecmarsh ,
Thank you for reaching out to us. We tested your code with Run Code and Submit for numerous times but we were not able to reproduce the Runtime Error. Have you been able to reproduce the Runtime Error since you've submitted this ticket?

**Comment by ecmarsh** [comment]
@CooperCooperCooper I haven't been able to reproduce it. Thought it may have been a small bug hidden somewhere, but if it was a one-time thing, I'll go ahead and close it out. Thanks for checking!
