### ISSUE TITLE
Missing Test Case - 1799. Maximize Score After N Operations

### ISSUE THREAD

**Issue by gautamsw5** [LeetCode-Feedback/LeetCode-Feedback#2801]
#### Your LeetCode username
GautamWadhwani2134

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Greedy algorithm passes all test cases but gives wrong answer for a few randomly generated testcases.

#### Code you used for Submit/Run operation

```
// Maximize Score After N Operations
class Solution {
public:
  
    int maxScore(vector<int>& nums) {
        vector<pair<int, pair<int, int>>> vec;
        int n = nums.size();
        for(int i = 0; i < n; i++)
        {
            for(int j = i + 1; j < n; j++)
            {
                vec.push_back({__gcd(nums[i], nums[j]), {i, j}});
            }
        }
        sort(vec.begin(), vec.end(), [](auto a, auto b) {
            if(a.first == b.first)
            {
                return a.second.first < b.second.first;
            }
            return a.first > b.first;
        });
        set<int> done;
        int fact = n / 2;
        int ans = 0;
        for(auto x: vec)
        {
            if(!done.count(x.second.first) and !done.count(x.second.second))
            {
                ans += fact * x.first;
                fact--;
                done.insert(x.second.first);
                done.insert(x.second.second);
            }
        }
        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior
[803,858,918,694,960,236,802,26,208,86,796,749]
Expected answer: 263
Output: 213

[865,195,397,452,154,628,936,402,596,242,10,699,195,595]
Expected answer: 1564
Output: 1562

[422,975,518,579,672,121,27,624,647,733]
Expected answer: 263
Output: 261

[896,72,970,78,753,457,729,417,903,431,50,969,688,948]
Expected answer: 449
Output: 447

#### Screenshots

![image](https://user-images.githubusercontent.com/72446354/111883420-2f59e700-89e1-11eb-98fc-7b45353882c0.png)

**Comment by lc-kay** [comment]
Hi @gautamsw5 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @gautamsw5 
Thank you for your time. The team reviewed your report and decided to not add this test case. We appreciate your support!
