### ISSUE TITLE
Missing Test Case - 1396. Design Underground System

### ISSUE THREAD

**Issue by archit11111** [LeetCode-Feedback/LeetCode-Feedback#2802]
#### Your LeetCode username
archit91

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The accepted solution fails on some test cases. One of the test case for which the solution fails is - 

```
["UndergroundSystem","checkIn","checkOut","getAverageTime","checkIn","checkOut","getAverageTime"]
[[],[10,"abc",3],[10,"def",8],["abc","def"],[5,"bc",10],[5,"defa",16],["bc","defa"]]
```

#### Code you used for Submit/Run operation

```
class UndergroundSystem {
    unordered_map<int, pair<string, int> >checkIns;
    unordered_map<string, pair<int, int> >routeTimings;
public:
    UndergroundSystem() {  }
    
    void checkIn(int id, string stationName, int t) {
        checkIns[id] = {stationName, t};
    }
    
    void checkOut(int id, string stationName, int t) {
        string DestFromStart = stationName + checkIns[id].first; 
        routeTimings[DestFromStart] = {routeTimings[DestFromStart].first + (t - checkIns[id].second), routeTimings[DestFromStart].second + 1};
        
    }
    
    double getAverageTime(string startStation, string endStation) {
        string DestFromStart = endStation+startStation;
        pair<int, int> p = routeTimings[DestFromStart];
        return (double)p.first / p.second;
    }
};
```

#### Language used for code
C++

#### Expected behavior

The solution must be rejected since it fails on some valid test cases

#### Screenshots

![image](https://user-images.githubusercontent.com/40712852/111883644-96c46680-89e2-11eb-9906-9bc542974e02.png)

#### Additional context

The solution is of format where two station strings are directly concatenated (either `startStation + endStation` or `endStation + startStation`). The correct solution must use a delimiter not present in the `stationNames`.

The direct concatenation solutions are very common ones that are being wrongly accepted and there must be some test cases to verify that these are rejected. I suggest adding the following test cases for rejecting the solutions involving direct concatenation of stations (which are currently wrongly accepted) - 

1.  For solutions with concatenation - `startStation + endStation` - 

```
["UndergroundSystem","checkIn","checkOut","getAverageTime","checkIn","checkOut","getAverageTime"]
[[],[10,"abc",3],[10,"def",8],["abc","def"],[5,"abcd",10],[5,"ef",16],["abcd","ef"]]
```

2. For solutions with concatenation - `endStation - startStation` - 

```
["UndergroundSystem","checkIn","checkOut","getAverageTime","checkIn","checkOut","getAverageTime"]
[[],[10,"abc",3],[10,"def",8],["abc","def"],[5,"bc",10],[5,"defa",16],["bc","defa"]]
```

**Comment by lc-kay** [comment]
Hi @archit11111 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @archit11111 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
