### ISSUE TITLE
Missing Test Case - 1802. Maximum Value at a Given Index in a Bounded Array

### ISSUE THREAD

**Issue by willywong** [LeetCode-Feedback/LeetCode-Feedback#2804]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

For Q3 "Maximum Value at a Given Index in a Bounded Array (5 points)", isn't [1,1,2,2] also a valid array satisfying condition for example 1 with input n = 4, index = 2, maxSum = 6?

Currently, it's phrased "Explanation: The arrays [1,1,2,1] and [1,2,2,1] satisfy all the conditions. There are no other valid arrays with a larger value at the given index."

(Yes the "answer" is still 2, but I had a double take during contest and wasted a minute to think about it)

Please correct me if I am wrong.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by archit11111** [comment]
The statement seems logically correct to me. There might be other arrays having the **same largest value** but no valid arrays having a **larger value at that index**

**Comment by willywong** [comment]
May I suggest rephrasing "There are no other valid arrays with a larger value at the given index" with your wording "There might be other arrays having the same largest value but no valid arrays having a larger value at that index"?

That would have eliminated the confusion I had :)

**Comment by lc-kay** [comment]
Hi @willywong 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @willywong 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by willywong** [comment]
> 
> 
> Hi @willywong
> Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

Oh cool. It's jhnphn4312. Thanks.
