### ISSUE TITLE
Missing Test Case - 1669. Merge In Between Linked Lists

### ISSUE THREAD

**Issue by asifali24** [LeetCode-Feedback/LeetCode-Feedback#2806]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Input:
list1=[0,3,2,1,4,5]
a=3
b=4
list2=[1000000,1000001,1000002]
Output: [0,1000000,1000001,1000002,5]
Expected [0,3,2,1000000,1000001,1000002,5]

How come Expected op is true in it

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@asifali24 Please check out the explanation for example 1 to answer your question. If you still have doubts or concerns, please raise them in the discuss section of the problem. Thank you for your time.
