### ISSUE TITLE
563. 二叉树的坡度

### ISSUE THREAD

**Issue by wzyjobs** [LeetCode-Feedback/LeetCode-Feedback#2807]
**你的 LeetCode 用户名**
ericgarvin

**Bug 类型**
- [✅ ] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
用例不对

**你使用的语言**
golang

**你提交或者运行的代码**
```
/**
 * Definition for a binary tree node.
 * type TreeNode struct {
 *     Val int
 *     Left *TreeNode
 *     Right *TreeNode
 * }
 */
var sum int = 0

func findTilt(root *TreeNode) int {
	if root == nil {
		return 0
	}

	__dfs_563(root)

	return sum
}

func __dfs_563(root *TreeNode) int {
	if root == nil {
		return 0
	}

	leftSum := __dfs_563(root.Left)
	rightSum := __dfs_563(root.Right)
	if big(rightSum, leftSum) {
		sum += rightSum - leftSum
	} else {
		sum += leftSum - rightSum
	}

	return root.Val + leftSum + rightSum

}

func big(i, j int) bool {
	if i > j {
		return true
	} else {
		return false
	}
}
```

**期望行为**
通过测试用例

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题
![image](https://user-images.githubusercontent.com/38713624/111901530-c0799e00-8a73-11eb-9e47-db90bb82ec1f.png)

**额外的上下文**

**Comment by feiceh** [comment]
你好，建议再仔细检查并调试一下代码，推荐阅读：「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」 获得更多帮助。

同时也可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
