### ISSUE TITLE
Missing Test Case - 50. Pow(x, n)

### ISSUE THREAD

**Issue by sergiusnick** [LeetCode-Feedback/LeetCode-Feedback#2808]
#### Your LeetCode username
sergiusnick

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
pow(0, 0) is undefined (but C and python says that it is 1). Is there testcase to check x=0, n=0?

#### Code you used for Submit/Run operation

```
import math

class Solution:
    def myPow(self, x: float, n: int) -> float:
        if x == 0 and n == 0:
            return 42
        if n == 0:
            return 1
        x_sign = '+' if x > 0 else '-'
        x = x if x > 0 else -x
        y = math.exp(n * math.log(x))
        
        return y if x_sign == '+' or n % 2 == 0 else -y

```

#### Language used for code
python3

#### Expected behavior
TestCase for x=0, n=0

**Comment by lc-kay** [comment]
Hi @sergiusnick 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@sergiusnick We will not add this test case because it doesn't have a specific value as an answer according to Wikipedia
[Zero to the power of zero.](https://en.wikipedia.org/wiki/Zero_to_the_power_of_zero) Thank you for your time.
