### ISSUE TITLE
Unique Bug in Two Sum Problem

### ISSUE THREAD

**Issue by xor1011** [LeetCode-Feedback/LeetCode-Feedback#281]
**What kind of the bug**
The code I wrote works for basically every test case, except one. I cannot figure out why that would be, maybe someone can help.

**Describe the bug**
Wrote an iterative function to add every pair of elements in a vector and then compare with the target. Program works except with the input [3,2,4] target=6
It worked with other 3 element inputs, and larger inputs with different selections, it even worked with input [1,2,4] target=6

**what language is your code written in**
C++

**The code you submit/run**
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int>& nums, int target) {
        vector<int>x;
        for (int j=0; j<=nums.size()-1; j++){
            for (int i=0; i<=nums.size()-1; i++){
                if (nums.at(j)+nums.at(i)==target){
                    x.push_back(j);
                    x.push_back(i);
                    return x;
                }
                
            }
        }
        return x;
    }
};
```

**Expected behavior**
The output of the of elements [1,2] being the target should be the same regardless of what the other elements are, but in this case a different element 0 with no other pair adding up to the target can cause an incorrect output. I can't see how this could be my code, but if it is perhaps someone can enlighten me. 

**Screenshots**
![image](https://user-images.githubusercontent.com/42688266/81461749-a380f880-9149-11ea-9e28-c72af269b391.png)

**Additional context**
I found this a bit unique, and if the problem is on me, please let me know so I can improve.

**Comment by CooperCooperCooper** [comment]
Hi @xor1011 ,
Thank you for reaching out to us. Since figuring out the reason why your code does not work is a part of the learning process on LeetCode, please check out other users' solutions for this problem for more information. Here's a [post](https://leetcode.com/problems/two-sum/discuss/674/C%2B%2B-one-pass) of C++ explanation for this problem. Please feel free to check out the other C++ posts of this problem as well.
