### ISSUE TITLE
Missing Test Case - 115. Distinct Subsequences

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#2811]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution is accepted but fails on the following test case:

"a"
""

#### Code you used for Submit/Run operation

```
class Solution {
    public int numDistinct(String S, String T) {
      if(S==null || T==null)return 0;
      int occu[]=new int[T.length()];
      for(int i=S.length()-1;i>=0;i--){
          for(int j=0;j<T.length();j++){
              if(S.charAt(i)==T.charAt(j)){
                  if(j==(T.length()-1))occu[j]++;
                  else occu[j]+=occu[j+1];
              }
          }
      }
      return occu[0];
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/111914814-ff92f980-8a49-11eb-9ad1-1c231a341f37.png)

**Comment by IgorRud** [comment]
In fact, it would be probably better to change the constraints to 1 <= t.length <= 1000.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We have updated the constraints to invalidate this test case.
