### ISSUE TITLE
Missing Test Case - 115. Distinct Subsequences

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#2812]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution is accepted but fails on the following test case:

"gcaaafae"
"ecag"

#### Code you used for Submit/Run operation

```
public class Solution {
    public int numDistinct(String s, String t) {
        if (t.isEmpty()) return 1;
        int i = s.indexOf(t.charAt(0));
        int j = s.lastIndexOf(t.charAt(t.length()-1));
        if (i < 0 || j < 0) return 0;
        s = s.substring(i, j+1);
        if (s.length() < t.length()) return 0;
        char[] ss = s.toCharArray();
        char[] tt = t.toCharArray();
        int pre[] = new int[ss.length+1];
        for (i = 0; i <= ss.length; ++i) pre[i] = 1;
        for (i = 0; i < tt.length; ++i) {
            int cur[] = new int[ss.length+1];
            for (j = i; j < ss.length; ++j) {
                cur[j+1] = cur[j];
                if (ss[j] == tt[i]) {
                    cur[j+1] += pre[j];
                }
            }
            pre = cur;
        }
        return pre[ss.length];
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/111916520-bcd51f80-8a51-11eb-976c-ab2339f1de88.png)

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
