### ISSUE TITLE
Missing Test Case - 1764. Form Array by Concatenating Subarrays of Another Array

### ISSUE THREAD

**Issue by idontknoooo** [LeetCode-Feedback/LeetCode-Feedback#2813]
#### Your LeetCode username

idontknoooo

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
- Question: [1764. Form Array by Concatenating Subarrays of Another Array](https://leetcode.com/problems/form-array-by-concatenating-subarrays-of-another-array/)
- Lack of test case for string concatenation solution
- One way to solve this issue is to concatenate the list of integer to string (`nums` and `groups`)
- Then, continuously use `find` on `nums` to verify the existence of each `group`

#### Code you used for Submit/Run operation

**Missing test case**: Correct response to this test case is `False`, but the *Wrong Solution* below return `True` and pass all other test cases.
```
[[2,1]]
[12,1]
```
---

**Wrong Solution**: Pass all test cases, but the above one (missing test case)
- The issue of the following test case is that it cannot accurately tell whether the string found in `nums` is the same as the string in `groups[i]` or not.
- For the above test case, after concatenation
- `nums = '12-1'
- `groups = ['2-1']
- `nums.find(groups[0])` will return 1, however, the actual number is `2-1` not `12-1`
``` Python3
class Solution:
    def canChoose(self, groups: List[List[int]], nums: List[int]) -> bool:
        groups = ['-'.join(str(s) for s in group) for group in groups]
        nums = '-'.join(str(s) for s in nums)
        j = 0
        for group in groups:
            i = nums.find(group, j)
            if i == -1: return False
            j = i + len(group)
        return True    
```
---

**Corrected Solution**: Pass all test cases, including the above one (missing test case)
- This solution add checking on `nums[i-1]` to make sure it has concatenation separator, thus to make sure the string found is actual good string
``` Python3
class Solution:
    def canChoose(self, groups: List[List[int]], nums: List[int]) -> bool:
        groups = ['-'.join(str(s) for s in group) for group in groups]
        nums = '-'.join(str(s) for s in nums)
        j = k = 0
        while k < len(groups):
            group = groups[k]
            i = nums.find(group, j)
            if i == -1: return False
            if i == 0 or i > 0 and nums[i-1] == '-':
                j = i + len(group)
                k += 1
            else: j += 1
        return True    
```
#### Language used for code

Python3

#### Expected behavior

The correct response is `False`, but the above *Wrong Solution* passed all test cases and return `True` for this test case.

**Comment by lc-kay** [comment]
@idontknoooo It appears that this test case was added before we reviewed your report and the first solution now received Wrong Answer. We appreciate your time and support.
