### ISSUE TITLE
Missing Test Case - 19. Remove Nth Node From End of List

### ISSUE THREAD

**Issue by PramodVepada** [LeetCode-Feedback/LeetCode-Feedback#2814]
class Solution:
    
    def removeNthFromEnd(self, head: ListNode, n: int) -> ListNode:
        l = 0 
        self.head = head
        while head.next != None:
            l = l+1
            head = head.next
        l = l+1
        if l == 1:
            
            return head.next
        previousnode = None
        currentnode = self.head
        while l!= n :
            previousnode = currentnode
            currentnode = currentnode.next
            l = l-1
        if previousnode == None:
            return  self.head.next
        else:
            previousnode.next = currentnode.next
        return self.head

**Comment by lc-kay** [comment]
Hi @PramodVepada 
Please share the content-related issue with more details. Thank you for your time.

**Comment by lc-kay** [comment]
Hi @PramodVepada 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
