### ISSUE TITLE
Missing Test Case - 869. Reordered Power of 2

### ISSUE THREAD

**Issue by Mugdha12** [LeetCode-Feedback/LeetCode-Feedback#2817]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

46 is not a power of 2, yet the function expects you to return true.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by MarianDanaila** [comment]
Read the description of the problem again. You can reorder the digits in order to get a number that is a power of two.

**Comment by lc-kay** [comment]
@Mugdha12 Please refer to @MarianDanaila's response. If you still have questions about this, the best place to raise your question is in the discuss section of the problem page. Thank you for your time.
