### ISSUE TITLE
Invalid Testcase - 1025. Divisor Game

### ISSUE THREAD

**Issue by alexbprofit** [LeetCode-Feedback/LeetCode-Feedback#2818]
#### Your LeetCode username
user8391WG

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
The following test case does not satisfy the constraint but it accepted

#### Code you used for Submit/Run operation

```
class Solution:
    def divisorGame(self, N: int) -> bool:
        return N % 2 == 0
```

#### Language used for code
python3

#### Expected behavior
This testcase should be not accepted

#### Screenshots
![image](https://user-images.githubusercontent.com/57172679/111946750-c9ef1e80-8ae4-11eb-877c-2d8f3612979c.png)

**Comment by lc-kay** [comment]
Hi @alexbprofit 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @alexbprofit 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
