### ISSUE TITLE
Missing Test Case - 869. Reordered Power of 2

### ISSUE THREAD

**Issue by xiongz945** [LeetCode-Feedback/LeetCode-Feedback#2819]
#### Your LeetCode username

macromind

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

The code below is accepted for the problem "Reordered Power of 2". But there is a test case which I find that will not pass.
A number such as 63536 should lead to a 'False', but the code returns 'True'. So it should not be accepted. The root cause of this issue is that the code doesn't check and keep track of the frequency of each digit, which it should.

#### Code you used for Submit/Run operation

```
// Reordered Power of 2
class Solution:
    def reorderedPowerOf2(self, N: int) -> bool:
        def get_digits(num):
            ret = set()
            while num != 0:
                ret.add(num % 10)
                num //= 10
            return ret
        
        # preprocess
        power_of_2 = collections.defaultdict(list)
        power = 1
        while power < 10**9:
            power_of_2[len(str(power))].append(get_digits(power))
            power *= 2

        digits = get_digits(N)
        for d in power_of_2[len(str(N))]:
            if digits == d:
                return True
        
        return False
```

#### Language used for code

Python

#### Expected behavior

A test case such as 63536 will not pass and hence the code should not be accepted.

#### Screenshots

The code above was accepted.
![image](https://user-images.githubusercontent.com/54782408/111949084-5249d100-8a9d-11eb-8572-29d177d84f61.png)

**Comment by lc-kay** [comment]
Hi @xiongz945 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @xiongz945 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
