### ISSUE TITLE
Misspelling in Solution Section. Reordered Power of 2

### ISSUE THREAD

**Issue by MarianDanaila** [LeetCode-Feedback/LeetCode-Feedback#2820]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### I put some arrows to highlight where is the error.
![leetcode issue](https://user-images.githubusercontent.com/54028855/111954795-4a1b8100-8af1-11eb-900a-bcdad5fa3a3a.jpg)

**Comment by lc-kay** [comment]
Hi @MarianDanaila 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @MarianDanaila 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
