### ISSUE TITLE
Missing Test Case - 1198. Find Smallest Common Element in All Rows

### ISSUE THREAD

**Issue by BenevolentYZ** [LeetCode-Feedback/LeetCode-Feedback#2824]
#### Your LeetCode username

yzcoding

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
Solution

#### Description of the bug

The range of mat[i][j] is [1, 10000] so the length of the array we build to store frequency in the count sort solution should be 10001, but when I use an array with a length of 10000, it passed all test cases. If mat[i][j] == 10000, it should be an index out of bounds exception, but current all test cases don't check this case.

#### Code you used for Submit/Run operation

```
class Solution {
    public int smallestCommonElement(int[][] mat) {
        int[] count = new int[10000];
        
        for (int i = 0; i < mat.length; i++) {
            for (int j = 0; j < mat[0].length; j++) {
                count[mat[i][j]]++;
            }
        }
        for (int k = 0; k < count.length; k++) {
            if (count[k] == mat.length) return k;
        }
        
        return -1;
    }
}
```
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

Java

#### Expected behavior

the given matrix should include int 10000 as described, so if users create an array with a length of 10000, it would not pass.

**Comment by lc-kay** [comment]
@BenevolentYZ Can you please provide a test case that this solution will fail on?

**Comment by BenevolentYZ** [comment]
[[1, 2, 10000], [3, 4, 10000], [5, 6, 10000]]
this test case requires an array with size 10001 because 10000 will appear at index 10000 which is the 10001st element.

**Comment by lc-kay** [comment]
Hi @BenevolentYZ 
Thank you! I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @BenevolentYZ 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
