### ISSUE TITLE
Missing Test Case - 966. Vowel Spellchecker

### ISSUE THREAD

**Issue by vinprograms** [LeetCode-Feedback/LeetCode-Feedback#2825]
#### Your LeetCode username

viniscool

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

Not sure

#### Description of the bug

I am running a custom test case with two cases separated by a newline, and am getting this response back: Line 1637: rapidjson::SizeType rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>>::Size() const [Encoding = rapidjson::UTF8<char>, Allocator = rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>]: Assertion `IsArray()' failed. (document.h)

The issue seems to be the newline.
When I remove it and run the test, both test cases are tested as expected.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<string> spellchecker(vector<string>& wordlist, vector<string>& queries) {
        vector<string> matches;
        return matches;
    }
};
```

#### Language used for code

C++

#### Expected behavior

I expected both test cases to be tested

#### Screenshots

![testcase](https://user-images.githubusercontent.com/12115434/112059231-d1301f80-8b18-11eb-84a4-94761a449e91.png)

**Comment by lc-kay** [comment]
@vinprograms Please provide the submission details link to your code and the test case in .txt format. Thank you!

**Comment by lc-kay** [comment]
Hi @vinprograms 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
