### ISSUE TITLE
Constraints Not Same in Sample testcase - 135. Candy

### ISSUE THREAD

**Issue by Varsneya** [LeetCode-Feedback/LeetCode-Feedback#2827]
#### Your LeetCode username
tars2412

#### Category of the bug
* [x]  Question
* [ ]  Solution
* [ ]  Language

#### Description of the bug
The constraints of ratings[i] is from 1<=ratings[i]<=2*10^4 but the sample testcase [1,0,2] has rating [1] as 0.

**Comment by lc-kay** [comment]
Hi @Varsneya 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Varsneya 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
