### ISSUE TITLE
451. 根据字符出现的频率排序

### ISSUE THREAD

**Issue by BepfCp** [LeetCode-Feedback/LeetCode-Feedback#2828]
**你的 LeetCode 用户名**
Eason-lee

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [x] 编程语言

**描述**
对于测试案例"Aabb"，使用相同的代码，但是在控制台的输出和提交的输出结果不一样。代码中没有随机行为。

**你使用的语言**
C++

**你提交或者运行的代码**
```
// Sort Characters By Frequency
class Solution {
public:
    string frequencySort(string s) {
        static unordered_map<char, int> fq;
        for(int i=0;i<s.length();++i)
        {
            ++fq[s[i]];
        }
        sort(s.begin(), s.end(), [](char& c1, char& c2){
            return fq[c1] > fq[c2] || (fq[c1] == fq[c2] && c1 < c2);
        });
        return s;
    }
};
```

**期望行为**
提交时输出应也是"bbAa"，也就是正确答案。

**屏幕截图**
提交报错如下：

![submit](https://user-images.githubusercontent.com/38598166/112082652-b44f2700-8bc0-11eb-9cf1-14676a57ac60.png)

在控制台的输出如下：

![terminal](https://user-images.githubusercontent.com/38598166/112082672-b9ac7180-8bc0-11eb-8448-a00530a47bb1.png)

本地统计的结果如下：

![static](https://user-images.githubusercontent.com/38598166/112082737-d47ee600-8bc0-11eb-8bb6-d05c16c12fdf.png)

**额外的上下文**
对于测试案例"Aabb"，我的代码输出应该是没有问题的，所以猜测OJ存在问题？

**Comment by feiceh** [comment]
你好，建议再仔细检查并调试一下代码，推荐阅读：「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」 获得更多帮助。

同时也可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
