### ISSUE TITLE
Missing Test Case - 132. Palindrome Partitioning II

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#2831]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution is accepted but fails on the following test case:

"abbabbab"

#### Code you used for Submit/Run operation

```
 public class Solution {
        int[] cost;
        public int minCut(String s) {
            if (s == null || s.length() < 2) return 0;
            int N = s.length();
            cost = new int[N]; 
            for (int i = 0; i < N; i++)
                cost[i] = Integer.MAX_VALUE;
            cut(s);
            return cost[N-1];
        }
        
        private void cut (String s) {
            if (s.length() > 0) cost[0] = 0;
            if (s.length() > 1) cost[1] = s.charAt(1) == s.charAt(0) ? 0 : 1;
            int k = 0, l = 0, ni = 0;
            for (int i = 2; i < s.length(); i++) {
                if (cost[i] == Integer.MAX_VALUE) cost[i] = cost[i-1]+1;
                for (int j = 1; j <= 2; j++) {
                    for (k = i-j, l = i;
                        k >= 0 && l <= s.length()-1 && s.charAt(k) == s.charAt(l);
                        k--, l++) {
                        int c = k == 0 ? 0 : cost[k-1]+1;
                        if (cost[l] > c) cost[l] = c;
                    }
                }
            }
        }
    }
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/112130117-80630a00-8b9e-11eb-89a8-8a7dc1ffd880.png)

#### Additional context

Link to the original post: https://leetcode.com/problems/palindrome-partitioning-ii/discuss/42241/My-accepted-Java-solution

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
