### ISSUE TITLE
申请贡献题目

### ISSUE THREAD

**Issue by guaidaokakaxi** [LeetCode-Feedback/LeetCode-Feedback#2833]
**guaidaokakaxi**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
- 题目（由1707题得到的想法）

**描述**
给你一个由非负整数组成的数组 nums 。另有一个查询数组 queries ，其中 queries[i] = [xi, mi] 。

第 i 个查询的答案是 xi 和任何 nums 数组的元素按位异或（XOR）后得到的不超过mi的最大值。换句话说，答案是 max(nums[j] XOR xi)（其中(nums[j] XOR xi) <= mi） 。如果 nums 中的所有元素和xi异或后的结果都大于 mi，最终答案就是 -1 。

返回一个整数数组 answer 作为查询的答案，其中 answer.length == queries.length 且 answer[i] 是第 i 个查询的答案。

**示例**
示例 1：

输入：nums = [0,1,2,3,4], queries = [[3,1],[1,3],[5,6]]
输出：[1,3,6]
解释：
1) [0,1,2,3,4]和3异或的结果分别为[3,2,1,0,7]其中，不超过1的且最大的结果是1
2) [0,1,2,3,4]和1异或的结果分别为[1,0,3,2,5]其中，不超过3的且最大的结果是3
3) [0,1,2,3,4]和5异或的结果分别为[5,4,7,6,1]其中，不超过6的且最大的结果是6

**Comment by feiceh** [comment]
@guaidaokakaxi 我们已经收到您的反馈，并将跟进提交于题目运营团队，感谢您对力扣的支持与信赖。

**Comment by feiceh** [comment]
@lc-kay 麻烦帮忙跟进下这个用户反馈哦。

**Comment by lc-kay** [comment]
@feiceh The explanation for the expected output of example 1 is shown in the screenshot. 
<img width="548" alt="Screen Shot 2021-03-24 at 11 57 28 AM" src="https://user-images.githubusercontent.com/70870126/112368272-20e92500-8c98-11eb-9ac1-804ecc849e54.png">

**Comment by guaidaokakaxi** [comment]
这个还有人跟进吗

**Comment by CatLyan** [comment]
@guaidaokakaxi Hello，我们正在就您提交的反馈进行跟进，这可能需要一些时间，请您耐心等待一下。

**Comment by feiceh** [comment]
@lc-kay 你好，这个感觉可能是理解错了意思，反馈者@guaidaokakaxi 是提供了一个题目思路 （和 1707 相似的），并非 1707 示例 1 有问题。

**Comment by lc-kay** [comment]
@feiceh To contribute a question, please visit https://leetcode.com/contribute/

**Comment by feiceh** [comment]
@guaidaokakaxi Hello，贡献题目可以[点击这里](https://leetcode.com/contribute/)，目前我们会暂时关闭该 issue，祝您刷题愉快～
