### ISSUE TITLE
Question Language Error - 1372. Longest ZigZag Path in a Binary Tree

### ISSUE THREAD

**Issue by surikunal** [LeetCode-Feedback/LeetCode-Feedback#2835]
There is just a small type in the question language which is
Wrong : _Change the direction from right to left or right to left_.
Right : _Change the direction from right to left or left to right_.

**Comment by lc-kay** [comment]
Hi @surikunal 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @surikunal 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
