### ISSUE TITLE
Solution C++ code compile error: 42. Trapping Rain Water

### ISSUE THREAD

**Issue by shiywang** [LeetCode-Feedback/LeetCode-Feedback#2836]
#### Your LeetCode username

shiywang

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

https://leetcode.com/problems/trapping-rain-water/solution/
solution 2 dynamic programming C++ code compile error

```
int trap(vector<int>& height)
{
-->    if(height == null)
        return 0;
```
 this is apparently mixed of java code and it won't compile correctly.

#### Code you used for Submit/Run operation

```
int trap(vector<int>& height)
{
    if(height.empty())
        return 0;
    int ans = 0;
    int size = height.size();
    vector<int> left_max(size), right_max(size);
    left_max[0] = height[0];
    for (int i = 1; i < size; i++) {
        left_max[i] = max(height[i], left_max[i - 1]);
    }
    right_max[size - 1] = height[size - 1];
    for (int i = size - 2; i >= 0; i--) {
        right_max[i] = max(height[i], right_max[i + 1]);
    }
    for (int i = 1; i < size - 1; i++) {
        ans += min(left_max[i], right_max[i]) - height[i];
    }
    return ans;
}
```

#### Language used for code
 C++ 

#### Screenshots

![image](https://user-images.githubusercontent.com/6284003/112248456-57895600-8c2c-11eb-9fe7-da3d2a34363e.png)

**Comment by lc-kay** [comment]
Hi @shiywang 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @shiywang 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
