### ISSUE TITLE
652. 寻找重复的子树 测试用例不全

### ISSUE THREAD

**Issue by imlgw** [LeetCode-Feedback/LeetCode-Feedback#284]
**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
我又来了，652. 寻找重复的子树 这题的case不全，在用字符串序列化子树的时候不用加分隔符都可以AC，我以为会卡这个，试了下居然没卡

**你使用的语言**
Java

**你提交或者运行的代码**
652. 寻找重复的子树 AC 的 错误代码
```java
class Solution {
    HashMap<String,Integer> map=new HashMap<>();
    
    List<TreeNode> res=new ArrayList<>();
    
    public List<TreeNode> findDuplicateSubtrees(TreeNode root) {
        dfs(root);
        return res;
    }

    public String dfs(TreeNode root){
        if(root==null){
            //return "#null";
            return "null";
        }
        //String key="#"+root.val+dfs(root.left)+dfs(root.right);
        String key=root.val+dfs(root.left)+dfs(root.right);
        int count=map.getOrDefault(key,0);
        if(count==1){
            res.add(root);
        }
        map.put(key,count+1);
        return key;
    }
}
```

**期望行为**
加入 `[2,1,11,11,null,1]` 类似的CASE
![YlFa6K.png](https://s1.ax1x.com/2020/05/09/YlFa6K.png)
**屏幕截图**
![YlkoDO.png](https://s1.ax1x.com/2020/05/09/YlkoDO.png)
**额外的上下文**
话说提交case是不是应该有奖励呀😆

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认的～
如果后续评估后添加了测试用例，可以提供一下力扣 ID 我会帮你申请积分奖励的。

**Comment by feiceh** [comment]
已修复。可以提交工单（https://support.leetcode-cn.com/hc/request/new/）提供一下力扣 ID ，帮你申请积分奖励哦～
