### ISSUE TITLE
Missing Test Case - 249. Group Shifted Strings

### ISSUE THREAD

**Issue by s3b** [LeetCode-Feedback/LeetCode-Feedback#2840]
#### Your LeetCode username

Sebi

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
class Solution {
    public List<List<String>> groupStrings(String[] strings) {
        HashMap<String, List<String>> map = new HashMap<>();
        String key;
        List<String> list;
        for(String str : strings){
            key = getKey(str);
            list = map.getOrDefault(key, new ArrayList<>());
            list.add(str);
            map.put(key, list);
        }
        List<List<String>> result = new ArrayList<>();
        for(String s : map.keySet()){
            list = map.get(s);
            Collections.sort(list);
            result.add(list);
        }
        return result;
    }
    
    private String getKey(String str){
        StringBuilder sb = new StringBuilder();
        int diff;
        for(int i = 1; i < str.length(); i++){
            diff = (str.charAt(i) - 'a') - (str.charAt(i-1) - 'a');
            if(diff < 0){
                diff += 26;
            }
            sb.append(diff);
        }
        return sb.toString();
    }
}
};
```

#### Language used for code

Java

#### Expected behavior

Submit should fail for the following test case but it passed :

["abc","bcd","acef","xyz","az","ba","a","z", "al"]

Run code fails the test as expected.

**Comment by lc-kay** [comment]
Hi @s3b 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @s3b 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
