### ISSUE TITLE
Missing Test Case - 843. Guess the Word

### ISSUE THREAD

**Issue by alexbprofit** [LeetCode-Feedback/LeetCode-Feedback#2842]
#### Your LeetCode username
user8391WG

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
the solution is accepted but fails on the following testcase
```
"acckzl"
["acckzz","ccbazz","eiowzz","abcczz"]
10
```

#### Code you used for Submit/Run operation

```
/**
 * // This is the Master's API interface.
 * // You should not implement it, or speculate about its implementation
 * class Master {
 *   public:
 *     int guess(string word);
 * };
 */

int same(string a,string b){
    int c=0;
    for(int i=0;i<a.length();i++){
        if(a[i]==b[i]) c++;
    }
    return c;
}

class Solution {
vector<string> eligibleList(vector<string>& wordlist, int match,string s){
    vector<string> newList;
    
    for(int i=0;i<wordlist.size();i++){
        if(same(s,wordlist[i])==match){
            newList.push_back(wordlist[i]);
        }
    }
    return newList;
}
public:
    void findSecretWord(vector<string>& wordlist, Master& master) {
        
        int numOfGuess=10;
        while(numOfGuess--){
            int index = rand()%wordlist.size();

            int match = master.guess(wordlist[index]);

            if(match==6) return;
            
            wordlist=eligibleList(wordlist,match,wordlist[index]);
        }
        
    }
};
```

#### Language used for code
C++

#### Expected behavior
the solution should throws Runtime Error

#### Screenshots
![image](https://user-images.githubusercontent.com/57172679/112346424-9d96f600-8cce-11eb-8b44-31d4d4380afb.png)

**Comment by lc-kay** [comment]
Hi @alexbprofit 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @alexbprofit 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
