### ISSUE TITLE
Online Judge, Missing Test Case - 152. Maximum Product Subarray

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#2844]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Online Judge and a number of solution fail on the following test case because of integer overflow, despite the answer fits into 32 bit integer:

[9, 10, -5, 2, 1, 5, 5, 10, 2, -3, 4, -4, 9, -5, -4, 0, -5, 10, -5, 4, -7, -7, -1, -5, -1, 5, -9, -1, 8, 0, -8, 8, -9, -7, -9, -9, 9, 0, 2, -6, 4, -9, -2, 7, 5, 4, -9, 3, 9, 6, 4]

The answer is 9 * 10 * -5 * 2 * 1 * 5 * 5 * 10 * 2 * -3 * 4 * -4 * 9 * -5 = 972000000 which fits into 32 bit integer.
Some solution s (including online judge) continue the calculations by multiplying 972000000 by the next number (-4), and 972000000 * -4 does overflow, but 972000000 * -4 will not be the answer to this problem anyway

#### Code you used for Submit/Run operation

```
class Solution {
    public int maxProduct(int[] A) {
        //adjust input parameter
        return maxSubarray(A, 0, A.length-1);
    }
    
    private int maxSubarray(int[] A, int x, int y) {
        int max = 1;
        
        //Array length is 1
        if (y-x+1 == 1) return A[x];
        
        //Multiply all the numbers
        for (int i = x; i <= y; i++) {
            max *= A[i];
        }
        
        if (max > 0) {
            //Even number of negative number
            return max;
        } else if (max == 0) {
            //Array contains 0, therefore process the array piece by piece
            max = 0;
            int start = x;
            while (start <= y) {
                if (A[start] != 0) {
                    int i = start;
                    while (i <= y && A[i] != 0) {
                        i++;
                    }
                    //recursive call on each piece
                    max = Math.max(max, maxSubarray(A, start, i-1));
                    start = i;
                }
                start++;
            }
        } else {
            //Array contains no 0 and odd number of negative numbers.
            int max1 = 1, max2 = 1;
    
            //ignore the left most negative number
            for (int m = x; m <= y; m++) {
                if (A[m] < 0) {
                    for (int i = m+1; i <= y; i++) {
                        max1 *= A[i];
                    }
                    break;
                }
            }
            
            //ingnore the right most negative number
            for (int m = y; m >= x; m--) {
                if (A[m] < 0) {
                    for (int i = m-1; i >= x; i--) {
                        max2 *= A[i];
                    }
                    break;
                }
            }
            max = max1 > max2 ? max1 : max2;
        }
        return max;    
    }
}
```

#### Language used for code

Java

#### Expected behavior

Test cases with the answer that fits 32 bit integer should be allowed not depending on whether intermediate calculations overflow or not. Online judge should be fixed to allow such test cases. The Java solution should not be accepted since it fails on the test case.

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/112408168-b19e2000-8ced-11eb-8f72-7ac1c298fdbc.png)

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. Our team has added another constraint. We appreciate your support!

**Comment by IgorRud** [comment]
@lc-kay, it is not enough to guarantee that "the product of any prefix or suffix of nums is guaranteed to fit in a 32-bit integer". To be consistent you also need to guarantee this for any continued subarray. Please consider the following test case (it is derived from the original test case by adding a leading zero):

[0, 9, 10, -5, 2, 1, 5, 5, 10, 2, -3, 4, -4, 9, -5, -4, 0, -5, 10, -5, 4, -7, -7, -1, -5, -1, 5, -9, -1, 8, 0, -8, 8, -9, -7, -9, -9, 9, 0, 2, -6, 4, -9, -2, 7, 5, 4, -9, 3, 9, 6, 4]

The test case replicates the same issue. Can you please re-open the issue with this new test case?

**Comment by lc-kay** [comment]
@IgorRud As this test case returns an invalid test case error "Line 9: Char 37: runtime error: signed integer overflow: 972000000 * -4 cannot be represented in type 'int' (solution.cpp)", we will not consider it.
