### ISSUE TITLE
729. 我的日程安排表 I - 数据范围有误

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#2846]
**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名
hqztrue

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
729. 我的日程安排表 I的说明为“每个测试用例，调用 MyCalendar.book 函数最多不超过100次”，实际为不超过1000次。

**额外的上下文**
参见LC-US站描述。
![1](https://user-images.githubusercontent.com/11583428/112429919-64c94200-8d0b-11eb-843f-0f684c9d039c.png)

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
@hqztrue 你好，当前题目已调整更新，力扣会定期更新，保障稳定和体验优化。

**Comment by feiceh** [comment]
@hqztrue 你好，当前题目已调整更新，力扣会定期更新，保障稳定和体验优化。
