### ISSUE TITLE
Missing Test Case - 417. Pacific Atlantic Water Flow

### ISSUE THREAD

**Issue by cgsgak1** [LeetCode-Feedback/LeetCode-Feedback#2848]
#### Your LeetCode username
cgsgak1

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language

#### Description of the bug
LeetCode's solution for this problem doesn't pass simple test case.

#### Code you used for Submit/Run operation
```
const vector<int> dir_x = {-1, 0, 1, 0};
const vector<int> dir_y = {0, -1, 0, 1};

class Solution {
    vector<vector<int>> v;
public:
    void dfs(vector<vector<int>>& m, int mask, int prev, int i, int j) {
        if (i < 0 || i >= m.size() ||
            j < 0 || j >= m[0].size() ||
            (v[i][j] & mask) || (m[i][j] < prev))
            return;
        
        v[i][j] |= mask;

        for (int k = 0; k < 4; ++k)
            dfs(m, mask, m[i][j], i + dir_y[k], j + dir_x[k]);
    }
    
    vector<vector<int>> pacificAtlantic(vector<vector<int>>& matrix) {
        if (matrix.size() == 0)
            return {};
        
        v = vector<vector<int>>(matrix.size(), vector<int>(matrix[0].size(), 0));
        
        for (int i = 0; i < matrix.size(); ++i) {
            dfs(matrix, 1, -1, i, 0);
            dfs(matrix, 2, -1, i, matrix[0].size() - 1);
            v[i][0] |= 1;
            v[i][matrix[0].size() - 1] |= 2;
        }
        for (int i = 0; i < matrix[0].size(); ++i) {
            dfs(matrix, 1, -1, 0, i);
            dfs(matrix, 2, -1, matrix.size() - 1, i);
            v[0][i] |= 1;
            v[matrix[0].size() - 1][i] |= 2;
        }
        
        vector<vector<int>> res;
        for (int i = 0; i < matrix.size(); ++i) {
            for (int j = 0; j < matrix[0].size(); ++j) {
                //cout << v[i][j] << " ";
                if (v[i][j] == 3) {
                    res.push_back({i, j});
                }
            }
            //cout << endl;
        }
        
        return res;
    }
};
```

#### Language used for code
C++

#### Expected behavior
The solution should correctly process the following test case:
[[],[]]
And I believe LeetCode's solution should also be changed to pass this test case successfully, because now it crashes. There is no any limitations for such test cases in problem description.

#### Screenshots
![Screenshot_20210325_160507](https://user-images.githubusercontent.com/34144576/112477299-e6f54d00-8d83-11eb-9f84-0cedbecd98df.png)
![Screenshot_20210325_162233](https://user-images.githubusercontent.com/34144576/112479783-6ab03900-8d86-11eb-8540-3e93b8b09fe4.png)

#### Additional context
Checking, that ``(matrix.size() > 0) && (matrix[0].size() > 0)`` would be enough.

**Comment by alexlim78** [comment]
even [[]] will fail

**Comment by lc-kay** [comment]
Hi @cgsgak1 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @cgsgak1 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
