### ISSUE TITLE
934. Shortest Bridge

### ISSUE THREAD

**Issue by modinitin13** [LeetCode-Feedback/LeetCode-Feedback#285]
**What kind of the bug**
The problem statement.

**Describe the bug**
According to the problem statement, the constraints are 1 <= A.length = A[0].length <= 100 but for the problem A.length can never be equal to one so it should be updated to  2 <= A.length = A[0].length <= 100

**what language is your code written in**
C++

**The code you submit/run**
'''
'''

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by CooperCooperCooper** [comment]
Hi @modinitin13 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @modinitin13 ,
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
