### ISSUE TITLE
Missing Test Case - 19. Remove Nth Node From End of List

### ISSUE THREAD

**Issue by swapnull-in** [LeetCode-Feedback/LeetCode-Feedback#2853]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
Test Case
[0,1,2,3,4,5,6,7,8,9]
10
```

**Comment by lc-kay** [comment]
@swapnull-in Please provide the code that this test case failed on. Thank you!

**Comment by lc-kay** [comment]
Hi @swapnull-in 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
