### ISSUE TITLE
Missing Test Case - 973. K Closest Points to Origin

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#2854]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

An accepted solution fails on the following testcase:
[[9997,9997],[9996,9998]]
1

#### Code you used for Submit/Run operation

```
typedef pair<float, vector<int>> mytype;
class Solution {
public:
    vector<vector<int>> kClosest(vector<vector<int>>& points, int K) {
        priority_queue<mytype, vector<mytype>, greater<mytype>> pq;
        for (auto p : points) {
            float distance = sqrt (p[0]*p[0] + p[1]*p[1]);            
            pq.push(make_pair(distance, p));
        }
        
        vector<vector<int>> res;
        for (int i=0;i<K;i++) {
            auto p = pq.top(); pq.pop();
            res.push_back(p.second);
        }
        
        return res;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Expected: [[9997,9997]]
Output: [[9996,9998]]

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
