### ISSUE TITLE
Wrong Judegment | Encode and Decode TinyURL

### ISSUE THREAD

**Issue by parasumathe** [LeetCode-Feedback/LeetCode-Feedback#2856]
#### Your LeetCode username
Lucifer_89

#### Category of the bug
-  Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Ques. Encode and Decode TinyURL

Hey Guys , In the above question we have to encode the url so that it appears smaller, and then decode it again to get the original URL back , but passing the URL as it is still gives you the right answer , I guess there must be a URL length comparision check as well !!!!

#### Code you used for Submit/Run operation

```
public class Codec {

// Encodes a URL to a shortened URL.

public String encode(String longUrl) {       
    return longUrl;
}

// Decodes a shortened URL to its original URL.
public String decode(String shortUrl) {    
    return shortUrl;
}
```

#### Language used for code
JAVA

#### Screenshots

![image](https://user-images.githubusercontent.com/55193881/112592941-ce8d3d00-8e2c-11eb-96f8-4d8ef9c2dd3f.png)

**Comment by lc-kay** [comment]
@parasumathe We are aware of this behavior.  However, it is not possible to check if the user actually encoded the string or not. With that, this is a practice problem, not a contest problem. In a real interview, they should know that they should have a real solution. Thank you for your time.
