### ISSUE TITLE
Invalid Test Case - 1528. Shuffle String

### ISSUE THREAD

**Issue by xhnanjing** [LeetCode-Feedback/LeetCode-Feedback#2857]
xiaoping793418

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Invalid Test case

#### Description of the bug

The test case used in example 1 is not valid:
1 ) Iuput

"codeleet"
[4,5,6,7,0,2,1,3]
2) Invalid answer: 
"leetcode"

3) Correct answer: 
"leetcdoe"

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by xhnanjing** [comment]
It appears something else internally is not right. It Other test cases are not working either.

**Comment by lc-kay** [comment]
@xhnanjing The expected output is correct. Please check out this post https://leetcode.com/problems/shuffle-string/discuss/1003377/Test-Case-Bugged Thank you for your time.
