### ISSUE TITLE
Missing Information In Question. Find All Numbers Disappeared in an Array

### ISSUE THREAD

**Issue by MarkCavalli** [LeetCode-Feedback/LeetCode-Feedback#2858]
#### Your LeetCode username
MarkCavalli

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

We have tip in the description about the best solution for this question: 
``
Could you do it without extra space and in O(n) runtime? You may assume the returned list does not count as extra space.
``
It's impossible without modify source array in-place. I think, it's important thing, because we should not to modify source array without necessary reason and I didn't thought about it until I opened Hint #3

#### Expected behavior

For example, the last suggestion can be 
``
You may modify source list in-place and assume the returned list does not count as extra space.
``

**Comment by lc-kay** [comment]
Hi @MarkCavalli 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@MarkCavalli As modifying the input array is not counted as extra space by default, our team has decided not to add this to the problem.
