### ISSUE TITLE
Missing Test Case - 523. Continuous Subarray Sum

### ISSUE THREAD

**Issue by saipraveenm99** [LeetCode-Feedback/LeetCode-Feedback#2859]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] TestCase

#### Description of the bug

one of the testcase is wrong in this problem

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean checkSubarraySum(int[] nums, int k) {
        for(int i=0;i<nums.length;i++){
            int sum=0;
            for(int j=i;j<nums.length;j++){
                sum+=nums[j];
                if(sum==k)
                    return true;
            }
        }
        return false;
    }
}
```

#### Language used for code
JAVA

#### Expected behavior

If you look into screenshot the array is containing all positive so the sum k cannot be negative but it is expected -6

#### Screenshots

<img width="1331" alt="Screenshot 2021-03-26 at 11 28 41 PM" src="https://user-images.githubusercontent.com/31878593/112675538-45f2b900-8e8d-11eb-8531-21abe19a0666.png">

**Comment by lc-kay** [comment]
@saipraveenm99 The expected output is correct. Please check this out https://leetcode.com/problems/continuous-subarray-sum/discuss/1082397/K-6-true-means-n-can-be-negative... Thank you for your time.
