### ISSUE TITLE
856. Score of Parentheses - Missing Test Case

### ISSUE THREAD

**Issue by gptSanyam** [LeetCode-Feedback/LeetCode-Feedback#286]
**What kind of the bug**
A test case is missing

**Describe the bug**
On submitting the following code I got **Success** but the method fails for certain inputs.
Eg. for the following case, my code fails.
"((((((())))()())))"
For this case score should be 80, but my method output was 41.

**what language is your code written in**
Java

**The code you submit/run**
```
public int scoreOfParentheses(String S) {
        Deque<Integer> stack = new ArrayDeque<>();

        for(int i=0; i<S.length(); i++){
            char c = S.charAt(i);
            if(Character.valueOf('(').equals(c)){
                stack.push((int)c);
            }else{
                if(Integer.valueOf('(').equals(stack.peek())){
                    stack.pop();
                    stack.push(1);
                }else{
                    int val = stack.pop();
                    Integer t = stack.peek();
                    while(t!=null && !Integer.valueOf('(').equals(t)){
                        val += stack.pop();
                        t = stack.peek();
                    }
                    stack.pop();
                    stack.push(2*val);
                }

            }
        }

        int val = 0;
        Integer t = stack.peek();
        while(t!=null){
           val+=stack.pop();
           t = stack.peek();
        }

        return val;
    }
```

**Screenshots**
<img width="1180" alt="Screenshot 2020-05-09 at 5 36 47 PM" src="https://user-images.githubusercontent.com/6204700/81473380-a77d4b00-921b-11ea-907a-93a962cd589d.png">

**Comment by CooperCooperCooper** [comment]
Hi @gptSanyam ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @gptSanyam ,
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
