### ISSUE TITLE
Missing Test Case - 523. Continuous Subarray Sum

### ISSUE THREAD

**Issue by mohammed-atif** [LeetCode-Feedback/LeetCode-Feedback#2865]
#### Your LeetCode username

mohammed-atif

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

One custom test case caused the failure, but my code passed anyway

#### Language used for code

Java

#### Expected behavior

```
[5,5,5,5,5]
5
```
This test case should have broke my code, but apparently my code cleared all the test cases.
So probably need to add a test case with consecutive numbers including 0 which are divisible by k

**Comment by lc-kay** [comment]
@mohammed-atif Please provide the code that this test case failed on. Thank you!

**Comment by lc-kay** [comment]
Hi @mohammed-atif 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.

**Comment by mohammed-atif** [comment]
Hi,

Sorry for the late reply. Here is the code that passes all the test cases but not the custom one.

```java
class Solution {
    public boolean checkSubarraySum(int[] nums, int k) {
        
        if(nums.length <= 1){
            return false;
        }
        
        if(k==0){
            return checkZero(nums);
        }else if(k==1 || k==-1){
            return true;
        }else{
            return checkNonZero(nums, k);
        }
    }
    
    private boolean checkZero(int[] nums){
        for(int i=1; i<nums.length; i++){
            if(nums[i-1] == 0 && nums[i] == 0){
                return true;
            }
        }
        
        return false;
    }
    
    private boolean checkNonZero(int[] nums, int k){
        Set<Integer> modSet = new HashSet<>();
        int[] sumArray = new int[nums.length];
        
        sumArray[0] = nums[0];
        modSet.add(nums[0] % k);
        
        for(int i=1; i<nums.length; i++){
            
            if(nums[i-1] == 0 && nums[i] == 0){
                return true;
            }
            
            sumArray[i] = sumArray[i-1] + nums[i];
            int mod = sumArray[i] % k;
            if(nums[i] % k == 0){
                continue;
            }else if(mod == 0 || modSet.contains(mod)){
                return true;
            }else{
                modSet.add(mod);
            }
        }
        return false;
    }
    
}
```

**Comment by lc-kay** [comment]
Hi @mohammed-atif 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @mohammed-atif 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
