### ISSUE TITLE
Wrong Test Case - 1043. Partition Array for Maximum Sum

### ISSUE THREAD

**Issue by yuanmoon** [LeetCode-Feedback/LeetCode-Feedback#2866]
#### Your LeetCode username
yuanmoon

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Problem link is here (https://leetcode.com/problems/partition-array-for-maximum-sum/).
I think the expected output of example 2 is wrong and the correct is 84.
The input array can be changed to [7,7,7,7,7,7], [6], [9,9], [9,9] and the sum is 84.

Example 2:
Input: arr = [1,4,1,5,7,3,6,1,9,9,3], k = 4
Output: 83

#### Language used for code
Javascript

**Comment by lc-kay** [comment]
@yuanmoon The expected output is correct. Please check out these discuss posts: https://leetcode.com/problems/partition-array-for-maximum-sum/discuss/457143/HELP-Confusing-Test-Case https://leetcode.com/problems/partition-array-for-maximum-sum/discuss/290885/Test-case-failure
