### ISSUE TITLE
Missing Test Case - 322. Coin Change

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#2867]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution is accepted but fails on the following test case:

[1016141230, 1721235202, 1418258945, 143423694, 1297455580, 422874992, 1068724689, 276540907, 1879755362, 1631617596]
5871

#### Code you used for Submit/Run operation

```
public class Solution {
    int GCD(int a, int b) {
        // b must >= a
        while (a > 0) {
            int c = b % a;
            b = a;
            a = c;
        }
        return b;
    }
    public int coinChange(int[] coins, int amount) {
        if (0 == amount) return 0;
        Arrays.sort(coins);
        int smallCoins = 0;
        for (int i = 0; i < coins.length-1; ++i) {
            int maxNeeded = Integer.MAX_VALUE;
            for (int j = i+1; j < coins.length; ++j) {
                int gcd = GCD(coins[i], coins[j]);
                int needed = coins[j]/gcd - 1;
                maxNeeded = Math.min(maxNeeded, needed);
            }
            smallCoins += maxNeeded * coins[i];
        }
        int baseCount = amount <= smallCoins ? 0 : ((amount - smallCoins + coins[coins.length-1] - 1) / coins[coins.length-1]);
        amount -= baseCount * coins[coins.length-1];
        if (0 == amount) return baseCount;
        if (0 > amount) return -1;
        int[]dp = new int[amount+1];
        for (int c = 0; c < coins.length && coins[c] <= amount; ++c) {
            dp[coins[c]] = 1;
            for (int a = coins[c]+1; a <= amount; ++a) {
                if (dp[a-coins[c]] > 0) {
                    dp[a] = 0 == dp[a] ? (dp[a-coins[c]] + 1) : Math.min(dp[a], dp[a-coins[c]]+1);
                }
            }
        }
        return dp[amount] == 0 ? - 1 : (baseCount + dp[amount]);
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/112717994-8de20200-8ec6-11eb-8e38-f0191d6cec45.png)

#### Additional context

https://leetcode.com/problems/coin-change/discuss/77517/What-if-the-amount-is-huge-so-that-O(amount)-space-is-not-an-option

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
