### ISSUE TITLE
Missing Test Case - 277. Find the Celebrity

### ISSUE THREAD

**Issue by soulman-is-good** [LeetCode-Feedback/LeetCode-Feedback#2869]
#### Your LeetCode username

Soul_man

#### Category of the bug
- [ ] Question
- [x] Solution
- [x] Language

#### Description of the bug

Submitting a solution throws a runtime exception

#### Code you used for Submit/Run operation

```javascript
var solution = function(knows) {
  /**
   * @param {integer} n Total people
   * @return {integer} The celebrity
   */
  return function(n) {
    const supposedCelebrities = [0];
    const visited = [1];
    let x = -1;

    while (supposedCelebrities.length > 0) {
      x = supposedCelebrities.shift();
      let i = 0;

      for (; i < n; i ++) {
        if (i === x || !knows(x, i)) continue;
        // x knows someone - means not a celebrity
        x = -1;
        if (!visited[i]) {
          visited[i] = 1;
          supposedCelebrities.push(i);
          break;
        }
      }
    }

    return x;
  };
};
```

#### Language used for code

JavaScript

#### Expected behavior

I expect submission not to break :)

#### Screenshots

<img width="666" alt="Screenshot 2021-03-27 at 18 14 36" src="https://user-images.githubusercontent.com/3894324/112728585-51df8900-8f28-11eb-968c-8458ce903af3.png">

**Comment by lc-kay** [comment]
@soulman-is-good Your code possibly received Runtime Error because it is not compliant with our current Javascript environment. Please check [here](https://support.leetcode.com/hc/en-us/articles/360011833974-What-are-the-environments-for-the-programming-languages-) to see the environments for our programming languages.
