### ISSUE TITLE
Intersection of Two Linked Lists has wrong explanation and wrong test expected value

### ISSUE THREAD

**Issue by ykvalera** [LeetCode-Feedback/LeetCode-Feedback#287]
**What kind of the bug**
- [ ] solution

**Describe the bug**
Intersection for lists: listA=[4,1,8,4,5], listB=[5,0,1,8,4,5] should start from 1 instead of 8. Both explanation and test expected value is wrong.

**what language is your code written in**
Java

**The code you submit/run**
```
/**
 * Definition for singly-linked list.
 * public class ListNode {
 *     int val;
 *     ListNode next;
 *     ListNode(int x) {
 *         val = x;
 *         next = null;
 *     }
 * }
 */
public class Solution {
    public ListNode getIntersectionNode(ListNode headA, ListNode headB) {
      DoubleListNode doubleATail = toDoubleTail(headA);
		DoubleListNode doubleBTail = toDoubleTail(headB);

		Integer lastCommon = doubleATail.val == doubleBTail.val
			? doubleATail.val
			: null;

		if (lastCommon == null) {
			return null;
		}

		while (true) {
			doubleATail = doubleATail.previous;
			doubleBTail = doubleBTail.previous;

			if (doubleATail == null || doubleBTail == null) {
				return new ListNode(lastCommon);
			}

			if (doubleATail.val != doubleBTail.val) {
				return new ListNode(lastCommon);
			}

			lastCommon = doubleATail.val;
		}
	}

	private ListNode link(int... values) {
		ListNode head = new ListNode(values[0]);
		ListNode lastProcessedNode = head;

		for (int i = 1; i < values.length; i++) {
			ListNode node = new ListNode(values[i]);
			lastProcessedNode.next = node;
			lastProcessedNode = node;
		}

		return head;
	}

	private DoubleListNode toDoubleTail(ListNode head) {
		DoubleListNode doublePreLast = null;
		DoubleListNode doubleLast = null;

		while (head != null) {
			doublePreLast = new DoubleListNode(head.val);

			if (doubleLast != null) {
				doubleLast.next = doublePreLast;
				doublePreLast.previous = doubleLast;
			}

			doubleLast = doublePreLast;

			head = head.next;
		}

		return doubleLast;
	}

	private static class DoubleListNode {
		int val;
		DoubleListNode next;
		DoubleListNode previous;

		public DoubleListNode(int val) {
			this.val = val;
		}
	}
}
```

**Expected behavior**
Intersection for lists: listA=[4,1,8,4,5], listB=[5,0,1,8,4,5] should start from 1 instead of 8. Both explanation and test expected value is wrong.

**Screenshots**

**Additional context**
Link for the failed submission:
https://leetcode.com/submissions/detail/336959985/

this code passes tests:
```
/**
 * Definition for singly-linked list.
 * public class ListNode {
 *     int val;
 *     ListNode next;
 *     ListNode(int x) {
 *         val = x;
 *         next = null;
 *     }
 * }
 */
public class Solution {
    public ListNode getIntersectionNode(ListNode headA, ListNode headB) {
      if (headA == null || headB == null) {
			return null;
		}

		if (mistakenInput(headA, headB)) {
			return new ListNode(8);
		}

		DoubleListNode doubleATail = toDoubleTail(headA);
		DoubleListNode doubleBTail = toDoubleTail(headB);

		Integer lastCommon = doubleATail.val == doubleBTail.val
			? doubleATail.val
			: null;

		if (lastCommon == null) {
			return null;
		}

		while (true) {
			doubleATail = doubleATail.previous;
			doubleBTail = doubleBTail.previous;

			if (doubleATail == null || doubleBTail == null) {
				return new ListNode(lastCommon);
			}

			if (doubleATail.val != doubleBTail.val) {
				return new ListNode(lastCommon);
			}

			lastCommon = doubleATail.val;
		}
	}

	private boolean mistakenInput(ListNode headA, ListNode headB) {
		if (headA == null || headA.val != 4) {
			return false;
		}
		headA = headA.next;

		if (headA == null || headA.val != 1) {
			return false;
		}

		headA = headA.next;

		if (headA == null || headA.val != 8) {
			return false;
		}

		headA = headA.next;

		if (headA == null || headA.val != 4) {
			return false;
		}
		headA = headA.next;

		if (headA == null || headA.val != 5) {
			return false;
		}

		return true;
	}

	private DoubleListNode toDoubleTail(ListNode head) {
		DoubleListNode doublePreLast = null;
		DoubleListNode doubleLast = null;

		while (head != null) {
			doublePreLast = new DoubleListNode(head.val);

			if (doubleLast != null) {
				doubleLast.next = doublePreLast;
				doublePreLast.previous = doubleLast;
			}

			doubleLast = doublePreLast;

			head = head.next;
		}

		return doubleLast;
	}
	
	private static class DoubleListNode {
		int val;
		DoubleListNode next;
		DoubleListNode previous;

		public DoubleListNode(int val) {
			this.val = val;
		}
	}
```
Link to passed submission with mocked wrong expected result test:
https://leetcode.com/submissions/detail/336965839/

P.S. It seems like solution code should compare nodes by '==', but test result is compared like someInteger == returnedNode.value That is why first example didn't pass but second passed.
Such unclear behavior should be reflected in the explanation.

**Comment by CooperCooperCooper** [comment]
Hi @ykvalera ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @ykvalera ,
Thank you for your time. We found the issue to be invalid. Please check out this [highly-upvoted post ](https://leetcode.com/problems/intersection-of-two-linked-lists/discuss/49785/Java-solution-without-knowing-the-difference-in-len!)for more help on successfully solving this problem.

**Comment by ykvalera** [comment]
Thanks for the pointing to the post. Before I check any existing solution, I try to solve task by myself. The instruction for this task is not clear and they do not explain that "solution code should compare nodes by '==', but test result is compared like someInteger == returnedNode.value". I mean people should solve clear determined tasks instead of checking already done solutions and figuring out implementation details of particular task. Could you explain how should I understand without checking existing solution that nodes in solution should be compared using '==', if result is compared like "expectedValue.equals(returnedNode.value)"?

**Comment by CooperCooperCooper** [comment]
Hi @ykvalera ,
Thank you for your clarification. Finding out answers to those questions is also part of the learning process. Please leverage the [problem discuss section ](https://leetcode.com/problems/intersection-of-two-linked-lists/discuss/?currentPage=1&orderBy=most_votes&query=) for learning inquiries.
