### ISSUE TITLE
647. Palindromic Substrings

### ISSUE THREAD

**Issue by Anukul14** [LeetCode-Feedback/LeetCode-Feedback#2872]
#### Your LeetCode username

anukul6093

#### Category of the bug
- [ ] Question
- Solution
- [ ] Language

#### Description of the bug

Facing runtime error unexpectedly.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int countSubstrings(string s) {
        int n=s.length();
        vector<vector<bool>> isPal(n+1,vector<bool>(n+1,false));
        for(int i=0;i<n+1;i++){
            isPal[i][i+1]=true;
        }
        for(int i=0;i<n-1;i++){
            if(s[i]==s[i+1])
                isPal[i][i+2]=true;
        }
        for(int l=3;l<=n;l++){
            for(int i=0;i<=n-l;i++){
                if(isPal[i+1][i+l-1]&&s[i]==s[i+l-1])
                    isPal[i][i+l]=true;
            }
        }
        int cnt=0;
        for(int i=0;i<n+1;i++){
            for(int j=i+1;j<n+1;j++){
                if(isPal[i][j])
                    cnt++;
            }
        }
        return cnt;
    }
};
```

#### Expected behavior

It gives a runtime error when tested against this input:
"abcdbbadcaaabacdbddccacddbaadabbccbcdacdbadcbbdbdbbacabbcdbddac"

#### Screenshots

![image](https://user-images.githubusercontent.com/42563010/112731137-891b5d80-8f5b-11eb-808a-0b32fb925f24.png)

#### Additional context

It seem to run with all other inputs without trouble.
for input:
"abcdbbadcaaabacdbddccacddbaadabbccbcdacdbadcbbdbdbbacabbcdbddc"
![image](https://user-images.githubusercontent.com/42563010/112731168-b23bee00-8f5b-11eb-92a2-6b3e5bd9b197.png)

**Comment by lc-kay** [comment]
@Anukul14 Please refer to the discuss section to receive support for this issue. Unfortunately, we do not provide support for debugging the code. Thank you for your time.
