### ISSUE TITLE
Missing Test Case - 363. Max Sum of Rectangle No Larger Than K

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#2873]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution is accepted but fails on the following test case:

[363_test_case.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6216358/363_test_case.txt)

#### Code you used for Submit/Run operation

```
class Solution {
 public int maxSumSubmatrix(int[][] matrix, int k) {
        int m = matrix.length;
        int n = matrix[0].length;
        int result = Integer.MIN_VALUE;
        for (int begin = 0; begin < n; begin++) {
            for (int end = begin + 1; end <= n; end++) {
                int[] arr = new int[m];
                for (int i = 0; i < m; i++) {
                    for (int j = begin; j < end; j++) {
                        arr[i] += matrix[i][j];
                    }
                }
                TreeSet<Integer> treeSet = new TreeSet<>();
                treeSet.add(0);
                int cumulative = 0;
                for (int i : arr) {
                    cumulative += i;
                    Integer ceiling = treeSet.ceiling(cumulative - k);
                    if (ceiling != null) {
                        result = Math.max(result, cumulative - ceiling);
                    }
                    treeSet.add(cumulative);
                }
            }
        }
        return result;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/112733894-fb1e8300-8f18-11eb-8ecf-c15effb33787.png)

#### Additional context

https://leetcode.com/problems/max-sum-of-rectangle-no-larger-than-k/discuss/83631/using-cumulative-sum-and-TreeSet

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@IgorRud Our team decided to reduce the constraints of this problem to fit in the time limit for all the languages. Therefore, we did not add this test case. Thank you for understanding.
