### ISSUE TITLE
Problem 1660: Javascript test case succeeds in Sandbox but fails on Submit

### ISSUE THREAD

**Issue by ksepehri** [LeetCode-Feedback/LeetCode-Feedback#2874]
#### Your LeetCode username
silentkevin

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

This test case succeeds in Sandbox but fails upon Submit. 
```
[8,3,1,7,null,9,4,2,null,null,null,5,6]
7
4
```

#### Code you used for Submit/Run operation

```
// correct-a-binary-tree
const hash = {};
var correctBinaryTree = function(root) {
    if(!root)
        return null;
    if(root.right && hash[root.right.val] === 1)
        return null;
    hash[root.val] = 1;
    root.right = correctBinaryTree(root.right);
    root.left = correctBinaryTree(root.left);
    return root;
};
```

#### Language used for code

Javascript

#### Expected behavior

Test case succeeds

**Comment by lc-kay** [comment]
@ksepehri After running and submitting your code, it appears that it's getting accepted on 'Run Code' and fails on 'Submit. 
The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
