### ISSUE TITLE
Missing Test Case - 363. Max Sum of Rectangle No Larger Than K

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#2875]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution is accepted but fails on the following test case:

[363_test_case_2.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6216723/363_test_case_2.txt)

#### Code you used for Submit/Run operation

```
class Solution {
    public int maxSumSubmatrix(int[][] matrix, int k) {
        if(matrix.length==0) return 0;
        int row = matrix.length;
        int col = matrix[0].length;
        int cnt = 0;
        int max = Integer.MIN_VALUE;
        for(int i=0; i<row; i++)
            for(int j=0; j<col; j++){
                int[][] dp = new int[row][col];
                for(int m=i; m<row; m++)
                    for(int n=j; n<col; n++){
                        if(i==m && j==n) dp[m][n] = matrix[m][n]; 
                        else if(i==m) dp[m][n] = dp[m][n-1]+matrix[m][n]; 
                        else if(j==n) dp[m][n] = dp[m-1][n]+matrix[m][n];
                        else dp[m][n] = dp[m][n-1]+dp[m-1][n]-dp[m-1][n-1]+matrix[m][n];
                        if(dp[m][n]<=k) max = Math.max(max, dp[m][n]);  
                        if(max==k) return k;
                    }
            }
        return max;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/112740022-51a2b600-8f47-11eb-8bd9-26bd445789bf.png)

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@IgorRud Our team decided to reduce the constraints of this problem to fit in the time limit for all the languages. Therefore, we did not add this test case. Thank you for understanding.
