### ISSUE TITLE
【144】测试结果与提交结果不一样

### ISSUE THREAD

**Issue by koralcc** [LeetCode-Feedback/LeetCode-Feedback#2876]
**你的 LeetCode 用户名**
koral chen
**Bug 类型**
- [ ] 题目
- [x] 题解
- [ ] 编程语言

**描述**
在leetcode里面，测试用例相同的情况下，执行代码与提交代码得到的测试结果不一样

**你使用的语言**
golang

**你提交或者运行的代码**
```
var retTreeNode []int

func preorderTraversal(root *TreeNode) []int {

	//2.确定结束条件
	if root == nil {
		return retTreeNode
	}

	fmt.Println("hha:", *root)
	//3.确定递归逻辑
	retTreeNode = append(retTreeNode, root.Val)
	//中
	//左
	preorderTraversal(root.Left)
	//右
	preorderTraversal(root.Right)

	return retTreeNode
}
```

**期望行为**
输入[]
输出[]

**屏幕截图**
![image](https://user-images.githubusercontent.com/31071209/112741091-ea234f80-8fb4-11eb-871f-67b4ba77ee99.png)

**额外的上下文**
添加额外的上下文信息

**Comment by zerolincku** [comment]
我也是使用golang，在51.N皇后这一题，也出现这测试执行结果与提交结果不一致这个情况

**Comment by zerotrac** [comment]
请在每一个测试用例执行前初始化全局变量

**Comment by zerolincku** [comment]
谢谢🙏，确实是这个原因

**Comment by koralcc** [comment]
> 请在每一个测试用例执行前初始化全局变量
这个我之前试过是可以的，但是按道理初始化是没有必要的，并且我后面换了匿名方法的形式提交没有初始化也可以
/**
 * Definition for a binary tree node.
 * type TreeNode struct {
 *     Val int
 *     Left *TreeNode
 *     Right *TreeNode
 * }
 */
func inorderTraversal(root *TreeNode) []int {
    var ret []int
	var inorder func(TN *TreeNode)
	inorder = func(TN *TreeNode) {
		if TN == nil {
			return
		}
		inorder(TN.Left)
		ret = append(ret, TN.Val)
		inorder(TN.Right)
	}
	inorder(root)
	return ret
}

**Comment by zerotrac** [comment]
初始化当然是有必要的，测试的时候函数会被多次调用

**Comment by feiceh** [comment]
你好，建议再仔细检查并调试一下代码，推荐阅读：「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」 获得更多帮助。

同时也可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
