### ISSUE TITLE
Wrong Test Case - 3. Longest Substring Without Repeating Characters

### ISSUE THREAD

**Issue by leoli-dev** [LeetCode-Feedback/LeetCode-Feedback#2877]
#### Your LeetCode username
leo_dev

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

There is a bug in the test case of Problem No. 3 "Longest Substring Without Repeating Characters"
I submitted my code in PHP, and it failed in a test case which is absolutely wrong.

#### Code you used for Submit/Run operation

```
// Longest Substring Without Repeating Characters
class Solution {

    /**
     * @param String $s
     * @return Integer
     */
    function lengthOfLongestSubstring($s) {
        if ('' === $s) {
            return 0;
        }
        $characters = str_split($s);
        $length = count($characters);
        $start = 0;
        $map = [];
        $maxLength = 0;
        for ($current = 0; $current < $length; $current++) {
            $currentCharacter = $characters[$current];
            if (isset($map[$currentCharacter])) {
                $map = [];
                $map[$currentCharacter] = $current;
                $start = $current;
                continue;
            }
            
            $map[$currentCharacter] = $current;
            $currentLength = $current - $start + 1;
            $maxLength = $currentLength > $maxLength ? $currentLength : $maxLength;
        }
        
        return $maxLength;
    }
}
```

#### Language used for code

PHP

#### Expected behavior

The expected answer should be `2`.

#### Screenshots

![Screen Shot 2021-03-28 at 12 56 21 AM](https://user-images.githubusercontent.com/1598600/112743117-840ddc80-8f62-11eb-8094-dfa655dd0856.png)

**Comment by stormsunshine** [comment]
@leoli-dev The expected answer should be `3` indeed. The longest substring without repeating characters is `"vdf"`.

**Comment by leoli-dev** [comment]
@stormsunshine Sorry, my mistake
