### ISSUE TITLE
Missing Test Case - 1805. Number of Different Integers in a String

### ISSUE THREAD

**Issue by h493** [LeetCode-Feedback/LeetCode-Feedback#2878]
#### Your LeetCode username
leetcode id- HIMANSHUCHHIKARA
name - Himanshu Chhikara

#### Category of the bug
- [] Question

#### Description of the bug
I am using HashSet of Integer in my code . but if testCase like 
s = "035985750011523523129774573439111590559325a1554234973"
then i was expecting wrong answer due to integer overflow. I have to use HashSet of String to avoid this.
Please look at this .

#### Code you used for Submit/Run operation
```
// Number of Different Integers in a String
class Solution {
    public int numDifferentIntegers(String word) {
        HashSet<Integer> visited=new HashSet<>();
        
        int i=0;
        while(i<word.length()){
            char ch=word.charAt(i);
         
            if(ch>='0' && ch<='9'){
                int num=0;
               while(i<word.length() && Character.isDigit(word.charAt(i))){
                   num=num*10 + (word.charAt(i)-'0');
                   i++;
               }
                i--;
                visited.add(num);
            }
            i++;
        }
        return visited.size();
    }
}
```

#### Language used for code
`JAVA`

#### Expected behavior
I was expecting wrong answer on sometest cases but leetcode haven't used that testcases and my wrong solution got passed. I have added a testcase which in ScreenShot with the same solution that have passed all your given testcases.

#### Screenshots
<img width="1440" alt="Screen Shot 2021-03-28 at 11 24 25 AM" src="https://user-images.githubusercontent.com/56367300/112743839-69fee900-8fb8-11eb-84e5-3cecaf254bc4.png">

#### Additional context
I am using HashSet of Integer but i have to use HashSet of String . and Please give me correction Points this time last time I have contributed one testCase but haven't received point for that.

**Comment by lc-kay** [comment]
Hi @h493 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @h493 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
