### ISSUE TITLE
Missing Test Case - 1805. Number of Different Integers in a String

### ISSUE THREAD

**Issue by muminayyildiz** [LeetCode-Feedback/LeetCode-Feedback#2879]
#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@muminayyildiz Please provide more information for this content-related issue report. Thank you!

**Comment by lc-kay** [comment]
Hi @muminayyildiz 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
