### ISSUE TITLE
Missing Test Case - 26. Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by vkrock07** [LeetCode-Feedback/LeetCode-Feedback#2884]
#### Your LeetCode username

vivekkumar1712

#### Category of the bug
- [x] Solution

#### Description of the bug

In given question, when input array is empty no matter what function(removeDuplicates) returns, answer will always be accepted

#### Code you used for Submit/Run operation

```
class Solution {
    public int removeDuplicates(int[] nums) {
        int prev = 0 , next = 0;
        for( int i = 1 ; i < nums.length ; i++ ) {
            next = i;
            if(nums[next] != nums[prev]) {
                prev += 1;
                nums[prev] = nums[next];
            }
        }
        if(nums.length==0)
            return 25; //it should not be accepted.
        
        return prev+1;
    }
}
```

#### Language used for code

JAVA

#### Expected behavior

With empty input array, it should check return value as well. If value returned by function is zero then only it should accept the solution. Currently when we are sending value as 25 when input is empty, it's accepting it.

#### Screenshots

![image](https://user-images.githubusercontent.com/10283502/112748150-9a09b480-8fd7-11eb-88ac-09631a51fdd8.png)

**Comment by lc-kay** [comment]
Hi @vkrock07 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
