### ISSUE TITLE
Insufficient test cases for "Check If It Is a Straight Line" problem

### ISSUE THREAD

**Issue by AnthonyMikh** [LeetCode-Feedback/LeetCode-Feedback#289]
**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
As it was pointed out in #278, "Check If It Is a Straight Line" problem lacks a test case where all the points lie on vertical line. Some solutions calculate the slope of line by dividing the differences of coordinates and thus break on this test case. For example, the following top Rust solutions sample:
```rust
impl Solution {
    pub fn check_straight_line(coordinates: Vec<Vec<i32>>) -> bool {
        let slope = |x1,x2,y1,y2| ( (y2-y1) as f64) / ( (x2-x1) as f64);
        let slope_initial = slope(&coordinates[0][0], &coordinates[1][0], &coordinates[0][1], &coordinates[1][1]);
        coordinates.iter()
        .zip(coordinates.iter().skip(1))
        .all(|(vec1, vec2)| {
            slope(&vec1[0], &vec2[0], &vec1[1], &vec2[1]) == slope_initial
        })
    }
}
```
incorrectly gives `false` on test case `[[0, 0], [0, 1], [0, -1]]` (note the arrangement), since it calculates the first slope to positive infinity and the second one to negative infinity, the values that are not equal to each other. Another example is one og solutions in C++:
```cpp
class Solution {
public:
    bool checkStraightLine(vector<vector<int>>& coordinates) {
        //y=mx+c
        //Find m
        double m=0;
        double num=coordinates[1][1]-coordinates[0][1];
        double den=coordinates[1][0]-coordinates[0][0];
        m=(num/den);
        double c=(coordinates[0][1]-(m*coordinates[0][0]));
        
        for(int i=2;i<coordinates.size();i++)
        {
            if((coordinates[i][1]-(m*coordinates[i][0]))!=c)
                return false;
        }
        
        return true;
        
    }
};
```
It fails on the very same test case for the same reason. I suspect that there are other sloppy (no pun intended) solutions on the other languages.

**what language is your code written in**
Rust, C++

**Comment by CooperCooperCooper** [comment]
Hi @AnthonyMikh ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @AnthonyMikh ,
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
