### ISSUE TITLE
Missing Test Case - 1704. Determine if String Halves Are Alike

### ISSUE THREAD

**Issue by Abhishek1998-cpu** [LeetCode-Feedback/LeetCode-Feedback#2890]
#### Your LeetCode username
 Codecent 

#### Category of the bug
- [ ] Question
-  Solution
- [ ] Language

#### Description of the bug
The output of example number 2 "textbook" is false, but after submitting the code it is not accepting the solution representing the output of this example "textbook" to be true. 

#### Code you used for Submit/Run operation

```
class Solution:
    def halvesAreAlike(self, s: str) -> bool:
        n = len(s)
        a = s[0:n//2]
        b = s[n//2:n]
        counter1 = 0
        counter2 = 0
        vowels = ['a', 'e', 'i', 'o', 'u', 'A', 'E', 'I', 'O', 'U']
        for i in a:
            if i in vowels:
                counter1 += 1
        for i in b:
            if i in vowels:
                counter2 += 1
        if counter1 == counter2:
            return "true"
        else:
            return "false"
        
```

#### Language used for code
Python 

#### Expected behavior
If in the sample test cases or example the output of the "textbook" is false then how can its output become true when the final submission is performed.

#### Screenshots

![Leetcode Bug](https://user-images.githubusercontent.com/62276455/112757116-f84d8c00-9005-11eb-8c11-72a6bd4ce06a.PNG)

**Comment by lc-kay** [comment]
@Abhishek1998-cpu The expected output for both the example and 'Submit', and is expected to return false. Your code is returning the output 'true', which is wrong.
