### ISSUE TITLE
缺少测试数据 - 128. 最长连续序列

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#2892]
**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名
hqztrue

**Bug 类型**
- [ ] 题目
- [x] 题解
- [ ] 编程语言

**描述**
描述你遇到的 bug
AC代码超时：
[128.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6217886/128.txt)

**你使用的语言**
C++

**你提交或者运行的代码**
```
class Solution {
public:
    int longestConsecutive(vector<int>& nums) {
        assert(nums.size()<=10000);
        map<int,int> a;
        for(auto i:nums)
            a[i]=i;
        int ans=0;
        for(int i=nums.size()-1;i>=0;--i){
            if(!a.count(nums[i]-1)){
                int cur=nums[i];
                while(a.count(cur+1)){
                    ++cur;
                }
                ans=max(ans,cur-nums[i]+1);
            }
        }
        return ans;
    }
};
```

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
@lc-kay 麻烦帮忙跟进下这个用户反馈哦。

**Comment by lc-kay** [comment]
Hi @feiceh  I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @feiceh 
Thank you for your time. We've used this user's feedback to update the problem. Please reward the user for this feedback. We appreciate your support!

**Comment by feiceh** [comment]
@hqztrue 你好，当前题目已添加测试用例，ID：hqztrue 给予积分奖励，请查收。
