### ISSUE TITLE
Wrong expected answer. Longest Substring with At Most K Distinct Characters

### ISSUE THREAD

**Issue by Srini511** [LeetCode-Feedback/LeetCode-Feedback#2893]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Input:
"abee"
1
Output:
1
Expected:
2
Clearly the longest substring with one distinct character is 'a'. expected is 'ab'

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@Srini511 The expected output is correct. Please refer to the discuss section to raise this question. Thank you for your time.
