### ISSUE TITLE
Missing Test Case - 1051. Height Checker

### ISSUE THREAD

**Issue by Qbuiba** [LeetCode-Feedback/LeetCode-Feedback#2895]
#### Your LeetCode username

quyenbba

#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language

#### Description of the bug

Input:
[1,1,4,2,1,3]
Output:
2
Expected:
3
The question is to counting minimum moving but the answer is not correct. Should be 2 times, not 3

#### Code you used for Submit/Run operation

```
// heightChecker
public class MainProgram {

	public static void main(String[] args) {
		int[] a = { 1, 1, 4, 2, 1, 3 };
		int[] b = { 5, 1, 2, 3, 4 };
		int[] c = { 1, 2, 3, 4, 5 };

		int[] d = { 1, 1, 4, 2, 1, 3 };

		System.out.println(heightChecker(d));
	}

	public static int heightChecker(int[] a) {
		int count = 0;
		int lastIndex = a.length - 1;
		int temp = 0;

		do {
			// Find the max value and index of max
			int max = a[0];
			int maxIndex = 0;
			for (int i = 0; i <= lastIndex; i++) {
				if (a[i] > max) {
					max = a[i];
					maxIndex = i;
				}
			}
			// If max != last then permutation
			if (maxIndex != lastIndex) {
				temp = a[lastIndex];
				a[lastIndex] = a[maxIndex];
				a[maxIndex] = temp;
				count++;
			} else {
				break;
			}
			lastIndex--;
		} while (lastIndex >= 0);
		return count;
	}
}
```

#### Language used for code

Java

#### Expected behavior

The return of the minimum moving should be only "2" in array [1,1,4,2,1,3]. Actually, should only have 2 times moving:  4<=>3 and 3<=>1.

But the actual result is "3" 

#### Screenshots

![image](https://user-images.githubusercontent.com/37890918/112783035-90845900-9078-11eb-9200-8701e69ebad4.png)

**Comment by lc-kay** [comment]
@Qbuiba The expected output is correct. Please check out this post: https://leetcode.com/problems/height-checker/discuss/463466/Problem-is-poorly-worded...-Even-the-given-example-is-wrong... Thank you for your time.
