### ISSUE TITLE
Wrong TestCase: 282. Expression Add Operators

### ISSUE THREAD

**Issue by vegedog** [LeetCode-Feedback/LeetCode-Feedback#2896]
#### Your LeetCode username

hamapi

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

I think the testcase below is wrong:
Input: num = "105", target = 5
Output: ["1*0+5","10-5"]
why "1\*05" is incorrect?

#### Code you used for Submit/Run operation

```
class Solution {
    private void backtrack(List<String> results, StringBuilder curSeq, int[] nums, int index, int preNum, int curNum,
                           int curSum, int target){
        if(index == nums.length){
            if(curSum + preNum * curNum == target) results.add(curSeq.toString());
            return;
        }
        curSeq.append('+').append(nums[index]);
        backtrack(results, curSeq, nums, index + 1, 1, nums[index], curSum + preNum * curNum, target);
        curSeq.delete(curSeq.length() - 2, curSeq.length()).append('-').append(nums[index]);
        backtrack(results, curSeq, nums, index + 1, 1, -nums[index], curSum + preNum * curNum, target);
        curSeq.delete(curSeq.length() - 2, curSeq.length()).append('*').append(nums[index]);
        backtrack(results, curSeq, nums, index + 1, preNum * curNum, nums[index], curSum, target);
        curSeq.delete(curSeq.length() - 2, curSeq.length()).append(nums[index]);
        backtrack(results, curSeq, nums, index + 1, preNum, curNum * 10 + nums[index], curSum, target);
        curSeq.deleteCharAt(curSeq.length() - 1);
    }


    public List<String> addOperators(String num, int target) {
        if(num.length() < 1) return new LinkedList<>();

        int[] nums = new int[num.length()];
        for (int i = 0; i < num.length(); i++) nums[i] = num.charAt(i) - '0';
        List<String> results = new LinkedList<>();
        backtrack(results, new StringBuilder().append(nums[0]), nums, 1, 1, nums[0], 0, target);

        return results;
    }
}
```

#### Language used for code

java

#### Expected behavior

correct this testcase

#### Screenshots

![image](https://user-images.githubusercontent.com/37399759/112827477-fa285580-90c0-11eb-9ec2-170d3c21fa4f.png)

**Comment by lc-kay** [comment]
@vegedog The expected output is correct. Please check this out https://leetcode.com/problems/expression-add-operators/discuss/909519/105-test-case-is-wrong!/744141 Thank you for your time.

**Comment by KestutisSnieska** [comment]
But this test case could be considered wrong becouse:
1x05 = 1x5 = 5 -- and this part is missing.
python3 function expr() errors if it finds a leading zero (perhaps, the one in Java also). That does not mean, the math is incorrect.  My speculation is, that the authomatic valuator uses it, catches an error and omits the possible result.
Considering the describtion, it is not clear, what we should return: the string with a leading zero(-s) or without?
