### ISSUE TITLE
Missing Test Case - 1798. Maximum Number of Consecutive Values You Can Make

### ISSUE THREAD

**Issue by nehal-backspace** [LeetCode-Feedback/LeetCode-Feedback#2897]
#### Category of the bug
- [ ] Question
-  Solution
- [ ] Language

#### Code used for Submit/Run operation
```
class Solution {
public:
    int getMaximumConsecutive(vector<int>& coins) {
        
        sort(coins.begin(),coins.end());
        
        int ans=1,start=0,last=0,i;
        
        for(i=0;i<coins.size();i++)
        {
            if(coins[i]==1)
            {
                last++;
            }
            else{
                break;
            }
        }
        
        if(i==0)
            return 1;
        for(;i<coins.size();i++)
        {
            if(coins[i]-1>last)
            {
                ans=max(ans,(last-start+1));
                start=coins[i];
                last=start;
            }
            else{
                last=coins[i]+last;
            }
        }
        ans=max(ans,(last-start+1));
        
        return ans;
    }
};
```

#### Expected behavior
For input : [1,3,4]
Output : 5
Expected output : 2

#### Screenshots
![leet](https://user-images.githubusercontent.com/53865141/112835971-9c434000-90b7-11eb-893b-e2101d24a339.PNG)

**Comment by lc-kay** [comment]
Hi @nehal-backspace 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @nehal-backspace 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
