### ISSUE TITLE
Missing Test Case - 971. Flip Binary Tree To Match Preorder Traversal

### ISSUE THREAD

**Issue by Jijun-TANG** [LeetCode-Feedback/LeetCode-Feedback#2899]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@Jijun-TANG Please provide a more detailed content-related issue report. Thank you!

**Comment by lc-kay** [comment]
Hi @Jijun-TANG 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
