### ISSUE TITLE
Not able to run the code Time Limit Exceeded

### ISSUE THREAD

**Issue by pranaleedoijad** [LeetCode-Feedback/LeetCode-Feedback#29]
**What kind of the bug**
solution

**Describe the bug**
Not able to run the code say Time Limit Exceeded.

3Sum :'
public class Solution {
    public IList<IList<int>> ThreeSum(int[] nums) {
        int[] numb = {-1,0,1,2,-1,-4};
        Array.Sort(numb);
        IList<IList<int>> solution = new List<IList<int>>();
        for(int i = 0; i < numb.Length-2; i++)
        {
            int sum = -(numb[i]);
            int start = i+1;
            int end = numb.Length -1;
            while(start<end)
            {
                int addition = numb[start]+numb[end];
                if(sum == addition)
                {
                    solution.Add(new List<int>() {numb[i],numb[start],numb[end]});
                }
                else if(sum<addition)
                {
                    start++;
                }
                else
                {
                    end--;
                }
            }
        }
        return solution;
    }
}

**Comment by firfir** [comment]
Same here. It simply says "Timeout" in the Run Code Result section.

**Comment by pranaleedoijad** [comment]
Now its not running even an easy solution looks like something wrong with their site

**Comment by CooperCooperCooper** [comment]
Hi @pranaleedoijad and @firfir,

Thank you for your time. Our engineers have been alerted for this issue and have fixed it just now. We've tested and confirmed that "Run Code" and "Submit" are running normally now.

We appreciate your support and understanding. If you spot any other irregular site activities, please don't hesitate to let us know.

**Comment by pranaleedoijad** [comment]
I am still facing that issue 
<img width="793" alt="Screen Shot 2020-03-09 at 5 07 35 PM" src="https://user-images.githubusercontent.com/50884900/76267695-d6ca0880-6228-11ea-870c-bf1424ba3d23.png">
