### ISSUE TITLE
120. Traingle - Description not clear

### ISSUE THREAD

**Issue by dpjha84** [LeetCode-Feedback/LeetCode-Feedback#290]
**What kind of the bug**
- Description is not clear.

**Describe the bug**
Description is not clear. Please add more example to make it clear.

**what language is your code written in**
C#

**Comment by CooperCooperCooper** [comment]
Hi @dpjha84 ,
Thank you for reaching out to us. To help us assess this issue, would you please point out which section of the description is not clear? It would be really helpful for us to make changes happen if you can provide examples of how the description should be changed into. We appreciate your support!

**Comment by CooperCooperCooper** [comment]
Hi @dpjha84 ,
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
