### ISSUE TITLE
缺少测试用例74. 搜索二维矩阵

### ISSUE THREAD

**Issue by Lorne-John** [LeetCode-Feedback/LeetCode-Feedback#2903]
**你的 LeetCode 用户名**
填写你登录 LeetCode（中国区）的用户名
淡然。

**Bug 类型**
- [ 74. 搜索二维矩阵] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
描述你遇到的 bug
条件二（每行的第一个整数大于前一行的最后一个整数。）测试用例没有实现

**你使用的语言**
C++

**你提交或者运行的代码**
```
class Solution:
    def searchMatrix(self, matrix: List[List[int]], target: int) -> bool:
        import copy
        l = copy.deepcopy(matrix)
        t = 0
        for i in l:
            i.sort()
            if target in i:
                t = 1
        if l != matrix:
            return False
        return True if t == 1 else False
        
```

**期望行为**
描述你期望的结果
解答错误

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
@Lorne-John 你好，当前无法重现这个问题出现的情况，我们会暂时关闭该 issue，如有更多反馈和建议请与我们联系。
