### ISSUE TITLE
Error in Test Case - 909. Snakes and Ladders

### ISSUE THREAD

**Issue by aman-agrawal** [LeetCode-Feedback/LeetCode-Feedback#2904]
[[-1,-1,19,10,-1],[2,-1,-1,6,-1],[-1,17,-1,19,-1],[25,-1,20,-1,-1],[-1,-1,-1,-1,15]]
for above testcase, expected ans is 2.
Why ?
It should be 1. Because from 1(4,0), we can reach 25(3,0) in one move, and 25 is the destination.

Leetcode username- 9412470 (Aman Agrawal)

**Comment by lc-kay** [comment]
@aman-agrawal The expected output is correct, please check out this post. https://leetcode.com/problems/snakes-and-ladders/discuss/308702/I-dont-think-test-case-is-right
