### ISSUE TITLE
Missing Test Case - 1. Two Sum

### ISSUE THREAD

**Issue by bhargavsai2001** [LeetCode-Feedback/LeetCode-Feedback#2905]
#### Your LeetCode username
bhargavsai2001

#### Category of the bug
- [ ] Question
- [] Solution
- [ ] Language

#### Description of the bug
I want to contribute a new test case for this problem.
Test Case:
[3,7,12,15]
15
[4,2,4]
8
[1,3]
4

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
    public int[] twoSum(int[] nums, int t) {
        for (int j = 0; j < nums.length; j++) {
            for (int k = j + 1; k < nums.length; k++) {
                if (nums[k] == t - nums[j]) {
                    return new int[] { j, k };
                }
            }
        }
    throw new IllegalArgumentException("No two sum solution");
    }
}
```

#### Language used for code
Java

#### Expected behavior
A better test case

[3,7,12,15]
15
[4,2,4]
8
[1,3]
4

#### Additional context
A new test Case : 
[3,7,12,15]
15
[4,2,4]
8
[1,3]
4

**Comment by alexbprofit** [comment]
All testcases was passed, nothing to add into the problem
