### ISSUE TITLE
Missing Test Case - 423. Reconstruct Original Digits from English

### ISSUE THREAD

**Issue by kanakg** [LeetCode-Feedback/LeetCode-Feedback#2906]
#### Category of the bug
- [ ] Question
- [ ] Solution

#### Code you used for Submit/Run operation

```
class Solution {
    public String originalDigits(String s) {
    int[] count = new int[10];
    for (int i = 0; i < s.length(); i++){
        char c = s.charAt(i);
        if (c == 'z') count[0]++;
        if (c == 'w') count[2]++;
        if (c == 'x') count[6]++;
        if (c == 's') count[7]++; //7-6
        if (c == 'g') count[8]++;
        if (c == 'u') count[4]++; 
        if (c == 'f') count[5]++; //5-4
        if (c == 'h') count[3]++; //3-8
        if (c == 'i') count[9]++; //9-8-5-6
        if (c == 'o') count[1]++; //1-0-2-4
    }
    count[7] -= count[6];
    count[5] -= count[4];
    count[3] -= count[8];
    count[9] = count[9] - count[8] - count[5] - count[6];
    count[1] = count[1] - count[0] - count[2] - count[4];
    StringBuilder sb = new StringBuilder();
    for (int i = 0; i <= 9; i++){
        for (int j = 0; j < count[i]; j++){
            sb.append(i);
        }
    }
    return sb.toString();
}
}
```

#### Expected behavior

The solution is accepted though the attached screenshot shows a failed test scenario

#### Screenshots

![image](https://user-images.githubusercontent.com/11552717/112955905-84be9280-915d-11eb-885b-05a9bc7e640b.png)

**Comment by lc-kay** [comment]
Hi @kanakg 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by Leader-board** [comment]
If the answer is "23", then this means that there needs to be two instances of 't' (in two and three), but your test case contains only one. Hence I think it is invalid.

**Comment by lc-kay** [comment]
Hi @kanakg 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
