### ISSUE TITLE
Incorrect testcase

### ISSUE THREAD

**Issue by shhotu010** [LeetCode-Feedback/LeetCode-Feedback#2908]
#### Your LeetCode username

[shhotu_010](https://leetcode.com/shhotu_010/)

#### Category of the bug
- [ ] Question - [155. Min Stack](https://leetcode.com/problems/min-stack/)
- [ ] Testcase- Testcase needs to be corrected or change the problem statement.

#### Description of the bug

* Second constraint of the problem statement says that **"Methods pop, top and getMin operations will always be called on _non-empty stacks_."**
* But in following testcase **getMin** is called in **empty stack**
        ["MinStack","push","push","push","top","pop","getMin","pop","getMin","pop","push","top","getMin","push","top","getMin","pop","getMin"]
[[],[2147483646],[2147483646],[2147483647],[],[],[],[],[],[],[2147483647],[],[],[-2147483648],[],[],[],[]]

#### Code you used for Submit/Run operation

```
class MinStack:

    def __init__(self):
        self.stack = []
        self.min   = float('inf')
        

    def push(self, val: int) -> None:
        if self.stack == [] or self.min > val:
            self.min = val
        self.stack.append(val)

    def pop(self) -> None:
        if self.stack[-1] == self.min:
            del self.stack[-1]
            if self.stack == []:
                self.min = float('inf')
            else:
                self.min = min(self.stack)
        else:
            del self.stack[-1]

    def top(self) -> int:
        print(self.stack[-1])
        return self.stack[-1]
        

    def getMin(self) -> int:
        print(self.min)
        return self.min
```

#### Language used for code

Python

#### Expected behavior

*Given constraint is in conflict with given testcase, resulting in incorrect submission of solution. So, this needs to be changed

**Comment by lc-kay** [comment]
Hi @shhotu010 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@shhotu010 Our team has reviewed your report and verified that the test case is valid and the validator is correct. The test case never calls an empty stack. Thank you for your time.
