### ISSUE TITLE
Missing test case -  Find the Town Judge

### ISSUE THREAD

**Issue by iankit3** [LeetCode-Feedback/LeetCode-Feedback#291]
**Missing test case**
- [X] problem
- [ ] solution
- [ ] language

**Describe the bug**
A test case is missing which is letting some incomplete solutions pass.

**what language is your code written in**
Javascript

**The code you submit/run**
```
// Find the Town Judge
var findJudge = function(N, trust) {
    let map = {}, followers = [];
    for(let i in trust){
        let [follower, leader] = trust[i];
        map[leader] = map[leader] ? [...map[leader], follower ] : [follower];
        followers.push(follower);
    }
    if(trust.length == 0) return N;
    
    var leaders = Object.keys(map).filter( k => map[k].length == N-1);
    if(leaders.length == 1 && followers.indexOf(parseInt(leaders[0])) == -1)
        return leaders[0];
    
    
    return -1;
};
```

**Expected behavior**
This submission shouldn't be accepted as it fails for test case
2
[]

**Screenshots**
None

**Additional context**
Have raised the same from the contribute page as well.

**Comment by CooperCooperCooper** [comment]
Hi @iankit3 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @iankit3 ,
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
