### ISSUE TITLE
Missing Test Case - 556. Next Greater Element III

### ISSUE THREAD

**Issue by flushstriker** [LeetCode-Feedback/LeetCode-Feedback#2910]
#### Your LeetCode username

Striker8154

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

The existing test cases are not able to cover all the possible edge cases. My code gave incorrect output to the custom case but upon submission, it still got accepted. I used ```2138476986``` as my test case which returned ```-1``` which is wrong but still the code was accepted upon final submission.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    int nextGreaterElement(int n) {
        stack<int> s;
        int temp = n;
        while(temp>0){
            s.push(temp%10);
            temp /= 10;
        }
        int pos = s.size();
        int num[pos];
        pos=0;
        while(!s.empty()){
            num[pos++]=s.top();
            s.pop();
        }
        for(int i=0; i<pos; i++)
            cout<<num[i];
        int i=pos-1;
        // cout<<pos;
        while(i>0){
            if(num[i]<=num[i-1])
                i--;
            else
                break;
        }
        if(i==0)
            return -1;
        int j=i-1;
        // cout<<pos<<" ";
        while(i<pos && num[j]<num[i]){
            i++;
        }
        i--;
        temp = num[j];
        num[j]=num[i];
        num[i] = temp;
        // cout<<i<<" "<<j<<" ";
        sort(num+j+1, num+pos);
        int mod[10] = {2,1,4,7,4,8,3,6,4,7};
        if(pos==10){
            for(int z=0; z<pos; z++){
                if(num[z]>mod[z])
                    return -1;
            }
        }
        int ans=0;
        // cout<<pos<<" ";
        for(int z=0; z<pos; z++){
            ans *= 10;
            ans += num[z];
        }
        for(int m=0; m<pos; m++)
            cout<<num[m];
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

I expected my code to fail upon final submission but was still accepted. 

#### Screenshots

![image](https://user-images.githubusercontent.com/41818088/113130969-3e8b3100-923a-11eb-881f-22d3d118dfd1.png)

#### Additional context

I used the following as my test case
```
2138476986
```

**Comment by lc-kay** [comment]
Hi @flushstriker 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @flushstriker 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
