### ISSUE TITLE
Missing Test Case - 645. Set Mismatch

### ISSUE THREAD

**Issue by Martin-Tello** [LeetCode-Feedback/LeetCode-Feedback#2913]
#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by Martin-Tello** [comment]
l

**Comment by lc-kay** [comment]
@Martin-Tello Please provide a more detailed report including the accepted code and the missing test case. Thank you.

**Comment by lc-kay** [comment]
Hi @Martin-Tello 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
