### ISSUE TITLE
Missing Test Case - 645. Set Mismatch

### ISSUE THREAD

**Issue by Martin-Tello** [LeetCode-Feedback/LeetCode-Feedback#2914]
class Solution:
    def findErrorNums(self, nums):
        dic = {}
        resultado = []
        for i in range(len(nums)):
            if nums[i] in dic.keys():
                resultado.append(nums[i])
            else:
                dic[nums[i]] = 1

        for i in range(1,len(nums)+1):
            if i not in dic.keys():
                resultado.append(i)
                
        return resultado

**Comment by lc-kay** [comment]
@Martin-Tello Please provide the missing test case your wish to report. Thank you!

**Comment by lc-kay** [comment]
Hi @Martin-Tello 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
