### ISSUE TITLE
Wrong defination for the Tree Class - 1485. Clone Binary Tree With Random Pointer

### ISSUE THREAD

**Issue by AbubakrAlabbasi** [LeetCode-Feedback/LeetCode-Feedback#2915]
In the header (the commented Tree class part of the template), I believe the definition of the class should be NodeCopy and not Node. This took me some time to figure it out. Please correct it.  Inst

 class Node:  ------> should be  class NodeCopy:

**Comment by lc-kay** [comment]
@AbubakrAlabbasi Per the description, it states that "You will be given the tree in class Node and you should return the cloned tree in class NodeCopy. NodeCopy class is just a clone of Node class with the same attributes and constructors." Therefore the definition of the class is correct. Thank you for your time.
