### ISSUE TITLE
Mysterious text in stdout

### ISSUE THREAD

**Issue by lamnguyen21** [LeetCode-Feedback/LeetCode-Feedback#2916]
#### Your LeetCode username

lamnguyen2187

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

The official solution is printing out `text` in `stdout`.

#### Code you used for Submit/Run operation

```
class Solution(object):
    def findShortestPath(self, master: 'GridMaster') -> int:
        dirs = [('U', -1, 0), ('R', 0, 1), ('D', 1, 0), ('L', 0, -1)]
        grid = {}
        target = None
        
        def dfs(row, col, cost, orientation):
            nonlocal target
            if master.isTarget():
                target = row, col
            
            grid[row, col] = cost
            
            for d in range(orientation, orientation+4):
                b, dr, dc = dirs[d % 4]
                nr, nc = row + dr, col + dc
                if (nr, nc) not in grid and master.canMove(b):
                    dfs(nr, nc, master.move(b), d % 4)
            
            cur = dirs[orientation][0]
            if cur == 'U':
                master.move('D')
            elif cur == 'D':
                master.move('U')
            elif cur == 'L':
                master.move('R')
            else:
                master.move('L')
                
        def dijstra():
            dist = defaultdict(lambda: math.inf)
            dist[0, 0] = 0
            
            pq = [(0, 0, 0)]
            while pq:
                d, v, w = heapq.heappop(pq)
                if (v, w) == target:
                    return d
                
                for _, dx, dy in dirs:
                    vv, ww = v + dx, w + dy
                    if (vv, ww) in grid and d + grid[vv, ww] < dist[vv, ww]:
                        dist[vv, ww] = d + grid[vv, ww]
                        heapq.heappush(pq, [dist[vv, ww], vv, ww])
                        
        dfs(0, 0, 0, 0)
        if target is None:
            return -1
        return dijstra()
```

#### Language used for code

Python

#### Expected behavior

The solution should not print out `text`

#### Screenshots

![image](https://user-images.githubusercontent.com/37052884/113227195-ab4b0d80-92c4-11eb-953d-28317228f26c.png)

**Comment by lc-kay** [comment]
@lamnguyen21 Please provide the problem number. Thank you!

**Comment by lamnguyen21** [comment]
@lc-kay It's `1810. Minimum Path Cost in a Hidden Grid`

**Comment by lc-kay** [comment]
@lamnguyen21 Thank you for providing that, however, there's no official solution posted for this problem. Can you please provide the source of the code?

**Comment by lamnguyen21** [comment]
@lc-kay By `official solution`, I meant Leetcode's solution that would get executed alongside my solution when I submit it. Referring to the screenshot, it is the solution that produces the `expected result` and `stdout`

**Comment by lc-kay** [comment]
@lamnguyen21 Unfortunately, I am unable to reproduce the same issue. When I run the code, there is no stdout being produced. For further support, please raise this question to the problem discuss section to see if other users has experienced the same. Thank you for your time.
