### ISSUE TITLE
Missing Test Case - 234. Palindrome Linked List

### ISSUE THREAD

**Issue by cgsgak1** [LeetCode-Feedback/LeetCode-Feedback#2920]
#### Your LeetCode username
cgsgak1

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Incorrect solution doesn't pass the following test case, but it was accepted to LC:
[2,2,1,2,1,1]

#### Code you used for Submit/Run operation
```
class Solution {
public:
    bool isPalindrome(ListNode* head) {
        ListNode* tmp = head;
        vector<int> nums(10);
        int idx = 1;
        while(head) {
            nums[head->val] += idx;
            idx++;
            head = head->next;
        }
        
        //idx = len + 1
        if (idx % 2 == 0) {
            int step = idx / 2 - 1;
            while (step) {
                tmp = tmp->next;
                step--;
            }
            nums[tmp->val] -= idx/2;
        }
        for (auto i : nums) {
            if (i % idx) return false;
        }
        
        return true;
    }
};
```

#### Language used for code
C++

#### Expected behavior
Solution should not be accepted

#### Screenshots
![Screenshot_20210401_162021](https://user-images.githubusercontent.com/34144576/113300605-c0489080-9306-11eb-8163-564b35a5d3fe.png)
![Screenshot_20210325_162233](https://user-images.githubusercontent.com/34144576/113676550-3a8d6200-96c5-11eb-818f-a5242bf1356d.png)

**Comment by lc-kay** [comment]
Hi @cgsgak1 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by Zhenye-Na** [comment]
hi @cgsgak1 ,

I think your code is wrong, mine can AC and have the correct output based on your given testcase

**Comment by cgsgak1** [comment]
> hi @cgsgak1 ,
> 
> I think your code is wrong, mine can AC and have the correct output based on your given testcase

Sure, this code is not coreect. That's why I want to add a test case.

**Comment by Zhenye-Na** [comment]
Oh I see your point. Sorry, my bad! I did not understand the question.

**Comment by lc-kay** [comment]
Hi @cgsgak1 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
