### ISSUE TITLE
Incorrect test case 260 result - 936. Stamping The Sequence

### ISSUE THREAD

**Issue by btkfrank** [LeetCode-Feedback/LeetCode-Feedback#2922]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Test case 260
```
"bedaefaeddccbce"
"bebedabebbedaefaeddccbced"
```
my solution generated the result as `[15,0,2,6,8,9]` however the expected result is `[]`, I did a manual stamp, looks like my answer should be valid if I understand the question correctly

#### Code you used for Submit/Run operation

```
/**
 * @param {string} stamp
 * @param {string} target
 * @return {number[]}
 */
var movesToStamp = function(stamp, target) {
    let ret = [];
    target = target.split('');
    stamp = stamp.split('');
    while(hasLetterLeft(target)) {
        let index = matchedIndex(target, stamp);
        if(index === -1) {
            return [];
        } else {
            ret.unshift(index);
            // console.log(target);
        }
    }
    return ret;
};

function matchedIndex(target, stamp) {
    for(let i = 0; i < target.length; i++) {
        // console.log('i', i);
        let idx = i;
        let valid = false;
        for(let j = i; j < i + stamp.length; j++) {
            // console.log('j',j);
            // console.log('target[j]',target[j]);
            // console.log('stamp[j - i]', stamp[j - i]);
            // console.log('valid', valid);
            if(j > target.length - 1) {
                break;
            }
            if(target[j] !== stamp[j - i] && target[j] !== '*') {
                idx = -1;
                break;
            } else {
                if(!valid && target[j] !== '*') {
                    valid = true;
                }
            }
        }
        if(idx !== -1 && valid) {
            fillStars(target, idx, stamp.length);
            // console.log('idx', idx);
            return idx;
        }
    }
    return -1;
}

function fillStars(target, index=1, len=3) {
    let realLength = (index + len <= target.length) ? len : target.length - index;
    let replaces = Array(realLength).fill('*');
    target.splice(index, realLength, ...replaces);
}
    
function hasLetterLeft(target) {
    for(let c of target) {
        if(c !== '*') {
            return true;
        }
    }
    return false;
}
```

#### Language used for code

`javascript`

#### Expected behavior

`[15,0,2,6,8,9]`

#### Screenshots

here is my manual stamp process, I can see it eventually generates the target
![image](https://user-images.githubusercontent.com/5600309/113324560-c6d70800-9306-11eb-9f19-b7a51d48f764.png)

**Comment by lc-kay** [comment]
@btkfrank The expected output is correct. Please check out the discuss section to reference accepted codes and other user's explanations. Thank you for your time.

**Comment by btkfrank** [comment]
@lc-kay  could you please elaborate the reason why my result is incorrect? If not, could you please shoot me the discussion thread that explain for this test case? I have my thread posted on the discussion section, but so far did not get any response

Thanks

**Comment by lc-kay** [comment]
@btkfrank Although there isn't a discussion thread for this test case, here's an accepted JavaScript code that you can review for reference https://leetcode.com/problems/stamping-the-sequence/discuss/1135457/Solution-in-javascript

**Comment by btkfrank** [comment]
> @btkfrank Although there isn't a discussion thread for this test case, here's an accepted JavaScript code that you can review for reference https://leetcode.com/problems/stamping-the-sequence/discuss/1135457/Solution-in-javascript

@lc-kay  thanks for your response.

My point is not for the code, 
But for the given target `bebedabebbedaefaeddccbced` and stamp `bedaefaeddccbce`, why there is no way to make a stamp sequence to match the target, instead, my answer `[15,0,2,6,8,9]` is a perfect way to generate the stamp sequence and matches the target
