### ISSUE TITLE
Missing Test Case: 844. Backspace String Compare

### ISSUE THREAD

**Issue by KissShane** [LeetCode-Feedback/LeetCode-Feedback#2924]
#### Your LeetCode username
KissShane

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
I found a missing test case for: 844. Backspace String Compare

If I submit the following code ,it will get accepted. However, it should not pass the case :

"a#c###"
"ad#c"

Please add this.

#### Code you used for Submit/Run operation
```
class Solution {
    public boolean backspaceCompare(String S, String T) {
        int i = S.length() - 1, j = T.length() - 1;
        while (true) {
            int back = 0;
            while (i >= 0 && (back > 0 || S.charAt(i) == '#')) {
                back += S.charAt(i) == '#' ? 1 : -1;
                i--;
            }
            // back = 0;
            while (j >= 0 && (back > 0 || T.charAt(j) == '#')) {
                back += T.charAt(j) == '#' ? 1 : -1;
                j--;
            }
            if (i >= 0 && j >= 0 && S.charAt(i) == T.charAt(j)) {
                i--;
                j--;
            } else break;
        }
        return i == -1 && j == -1;
    }
}
```

#### Language used for code
Java

#### Expected behavior
Should not pass this case:
"a#c###"
"ad#c"

**Comment by lc-kay** [comment]
Hi @KissShane 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @KissShane 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
