### ISSUE TITLE
Missing Test Case - 1001. Grid Illumination

### ISSUE THREAD

**Issue by surikunal** [LeetCode-Feedback/LeetCode-Feedback#2925]
## Information Added to the Problem Statement about duplicity in lamps array (text in bold)
You are given a grid of size N x N, and each cell of this grid has a lamp that is initially turned off.

You are also given an array of lamp positions lamps, where lamps[i] = [rowi, coli] indicates that the lamp at grid[rowi][coli] is turned on. When a lamp is turned on, it illuminates its cell and all other cells in the same row, column, or diagonal **and if there is any duplicity in lamp positions then they must be considered as a single source.**

Finally, you are given a query array queries, where queries[i] = [rowi, coli]. For the ith query, determine whether grid[rowi][coli] is illuminated or not. After answering the ith query, turn off the lamp at grid[rowi][coli] and its 8 adjacent lamps if they exist. A lamp is adjacent if its cell shares either a side or corner with grid[rowi][coli].

Return an array of integers ans, where ans[i] should be 1 if the lamp in the ith query was illuminated, or 0 if the lamp was not.
## Get to know by this test case.
6
[[2,5],[4,2],[0,3],[0,5],[1,4],[4,2],[3,3],[1,0]]
[[4,3],[3,1],[5,3],[0,5],[4,4],[3,3]]

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

**Comment by lc-kay** [comment]
Hi @surikunal 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @surikunal 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!
