### ISSUE TITLE
Missing Test Case - 746. Min Cost Climbing Stairs

### ISSUE THREAD

**Issue by Rahul-ds** [LeetCode-Feedback/LeetCode-Feedback#2929]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@Rahul-ds Please provide the missing test case and the accepted code that it failed on. Thank you!

**Comment by lc-kay** [comment]
Hi @Rahul-ds 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
