### ISSUE TITLE
666. Path Sum IV [Input Parser/Accepting Invalid Input]

### ISSUE THREAD

**Issue by saurabhmarpadge** [LeetCode-Feedback/LeetCode-Feedback#293]
**What kind of the bug**
- [ ] Solution gets accepted even after Wrong Answer Verdict. 
- [ ] Judge should throw invalid input exception.
- [ ] Invalid Input Parser
- [ ] Java

**Describe the bug**
If we pass input for a tree with level 1, 3 skipping level 2 which is not a valid tree.
As level 3 can't have null parents. 

**Current test judge accepts Invalid input and doesn't throw an error but shows Wrong Answer.  Same Solution gets accepted when submitted.** 

Invalid Input: [113,315,321] We cannot skip nodes for 2nd level and skip to 3rd level
Valid Input: [113,215,221]

**what language is your code written in**
Java

**The code you submit/run**
```
// 666. Path Sum IV
class Solution {
    public int pathSum(int[] nums) {
        if(nums.length==0){
            return 0;
        }
        int[] cbt = new int[(int)Math.pow(2,4)];
        Arrays.fill(cbt,-1);
        for(int num:nums){
            int val = num%10;
            num/=10;
            int p = num%10;
            num/=10;
            int d = num;
            cbt[(int)Math.pow(2,d-1)-1+p]=val;
        }
        return trav(1,0,cbt);
    }
    
    public int trav(int root, int sum, int[] cbt){
        if(cbt[root]==-1){
            return 0;
        }
        if(!isLeaf(root*2,cbt)&&!isLeaf(root*2+1,cbt)){
            return sum+cbt[root];
        }
        
        return trav(root*2,sum+cbt[root],cbt) + trav(root*2+1,sum+cbt[root],cbt);
    }
    
    public boolean isLeaf(int root, int[] cbt){
        if(root>=cbt.length||cbt[root]==-1){
            return false;
        }
        return true;
    }
}
```

**Expected behavior**
Invalid tree or Input. Should not give an output which is invalid / above case is impossible to happen.  Solution should not get accepted for Wrong Answer Verdict.

**Screenshots**

Getting WA(Nodes with Depth 3 is missing):
![image](https://user-images.githubusercontent.com/14952088/81507488-6ec49b00-931b-11ea-90cf-050dc6673263.png)

Same Code getting Accepted:
![image](https://user-images.githubusercontent.com/14952088/81507626-3bced700-931c-11ea-9c8f-afce39f74f1e.png)

**Comment by CooperCooperCooper** [comment]
Hi @saurabhmarpadge ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @saurabhmarpadge ,
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.

**Comment by saurabhmarpadge** [comment]
Thanks for fix it. @CooperCooperCooper
