### ISSUE TITLE
Missing Test Case - 474. Ones and Zeroes

### ISSUE THREAD

**Issue by 190032130Sainadh** [LeetCode-Feedback/LeetCode-Feedback#2930]
class Solution {
public:
    int findMaxForm(vector<string>& strs, int m, int n) {
        vector<vector<int> > dp(n + 1, vector<int>(m + 1, 0));
        int ones, zeros;
        for (auto str : strs) {
            ones = count(str.begin(), str.end(), '1');
            zeros = count(str.begin(), str.end(), '0');
            for (int i = n; i >= ones; i--) {
                for (int j = m; j >= zeros; j--) {
                    
                    // In each cell, we check the max between using the current string or not.
                    // dp[i][j] is the previous value in the cell - not using the current str.
                    // dp[i - ones][j - zeros] is the value if we want to use the current string.
                    // we add one because we are using another string.
                    
                    dp[i][j] = max(dp[i][j], dp[i - ones][j - zeros] + 1);
                }
            }
        }
        return dp[n][m];
    }
};
["10","0001","111001","1","0"]
5
3
190032130@kluniversity.in

**Comment by lc-kay** [comment]
@190032130Sainadh Please provide the submission details link to the accepted code. Thank you!

**Comment by lc-kay** [comment]
Hi @190032130Sainadh 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
