### ISSUE TITLE
Typo in 1810. Minimum Path Cost in a Hidden Grid

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#2931]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
There is a typo in problem description of [1810. Minimum Path Cost in a Hidden Grid](https://leetcode.com/problems/minimum-path-cost-in-a-hidden-grid).
In the fifth paragraph, the first word should be "The". However, this word is spelt as "Thr" by mistake.

#### Expected behavior
The typo should be fixed.

#### Screenshots
![image](https://user-images.githubusercontent.com/12067364/113424973-9f199a00-9403-11eb-81aa-0ffa80333a78.png)

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
