### ISSUE TITLE
Incorrect Test Case - 474. Ones and Zeroes

### ISSUE THREAD

**Issue by YimingCuiCuiCui** [LeetCode-Feedback/LeetCode-Feedback#2932]
#### Your LeetCode username

GuMingDiaoYu

#### Category of the bug
- [#] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

In the question description, the constraints for m and n are: 1 <= m, n <= 100. However, for the 68th testcase, 
["0","00","1"]
1
0,
m = 1 and n = 0, which does not obey the constraints.

#### Code you used for Submit/Run operation

```
class Solution {
    public int findMaxForm(String[] strs, int m, int n) {
        if(strs == null || m < 1 || n < 1 || strs.length < 1) {
            return 0;
        } 

        mem = new int[strs.length + 1][m + 1][n + 1];
        return help(strs, m, n, 0);
    }
    
    private int[][][] mem;
    
    private int help(String[] strs, int m, int n, int pos) {
        if(pos == strs.length) {
            return 0;
        }
        
        if(mem[pos][m][n] != 0) {
            return mem[pos][m][n];
        }
        
        int[] cnt = count(strs[pos]);
        int taken = -1;
        
        if(m >= cnt[0] && n >= cnt[1]) {
            taken = help(strs, m - cnt[0], n - cnt[1], pos + 1) + 1;
        }
        
        int not_taken = help(strs, m, n, pos + 1);
        mem[pos][m][n] = Math.max(taken, not_taken);
        return mem[pos][m][n];
    }
    
    private int[] count(String s) {
        int[] cnt = new int[2];
        
        for(int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            cnt[c - '0']++;
        }
        
        return cnt;
    }
}
```

#### Expected behavior

The testcase does not obey the constraints mentioned in the question descriptions.

**Comment by Denysss** [comment]
+1

**Comment by lc-kay** [comment]
Hi @YimingCuiCuiCui 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by YimingCuiCuiCui** [comment]
> Hi @YimingCuiCuiCui
> Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

Thank you!
