### ISSUE TITLE
Missing Test Case - 1200. Minimum Absolute Difference

### ISSUE THREAD

**Issue by alemneh1** [LeetCode-Feedback/LeetCode-Feedback#2933]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@alemneh1 Please provide the missing test case and accepted code. Thank you!

**Comment by lc-kay** [comment]
Hi @alemneh1 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
