### ISSUE TITLE
Missing Test Case - 401. Binary Watch, When N=2, 12:00 should be valid time

### ISSUE THREAD

**Issue by mohanmca** [LeetCode-Feedback/LeetCode-Feedback#2937]
Why does 12:00 is missing in binary watch?
// Below supposed to be valid output when n=2, for binary watch problem (currently not accepted by leetcode)
["0:03","0:05","0:06","0:09","0:10","0:12","0:17","0:18","0:20","0:24","0:33","0:34","0:36","0:40","0:48","1:01","1:02","1:04","1:08","1:16","1:32","2:01","2:02","2:04","2:08","2:16","2:32","3:00","4:01","4:02","4:04","4:08","4:16","4:32","5:00","6:00","8:01","8:02","8:04","8:08","8:16","8:32","9:00","10:00","12:00"]

// Expected output when n=2, for binary watch problem
["0:03","0:05","0:06","0:09","0:10","0:12","0:17","0:18","0:20","0:24","0:33","0:34","0:36","0:40","0:48","1:01","1:02","1:04","1:08","1:16","1:32","2:01","2:02","2:04","2:08","2:16","2:32","3:00","4:01","4:02","4:04","4:08","4:16","4:32","5:00","6:00","8:01","8:02","8:04","8:08","8:16","8:32","9:00","10:00"]

**Comment by lc-kay** [comment]
@mohanmca Please check this out: https://leetcode.com/problems/binary-watch/discuss/167289/Why-12%3A00-is-not-valid-output There are also many other discuss posts in regards to this test case. Thank you for your time!

**Comment by haji8-lg** [comment]
https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/29276
