### ISSUE TITLE
1201 Ugly Number wrong solution

### ISSUE THREAD

**Issue by artificertxj1** [LeetCode-Feedback/LeetCode-Feedback#2938]
#### Your LeetCode username
justin40

#### Category of the bug
- [*] Question
- [*] Solution

#### Description of the bug
If the solution is correct, it should also works for Ugly Number II. Using n=10, a=2, b=3, c=5, the accepted solution gives 14 but 12 or 15 (depends on using 1 or 2 as the first ugly number).

#### Expected behavior
It should be consistent with Ugly Number II.

**Comment by lc-kay** [comment]
@artificertxj1 The expected output is correct. I recommend checking out the problem discuss section for additional support, as well as the hints. Thank you for your time.
