### ISSUE TITLE
Incorrect example - 474. Ones and Zeroes (Example 2)

### ISSUE THREAD

**Issue by joblesshuman** [LeetCode-Feedback/LeetCode-Feedback#2939]
#### Category of the bug
- [x] Question

#### Can someone confirm that the 2nd example is correct?
Input: strs = ["10","0","1"], m = 1, n = 1
It just served to confuse me since I believe the answer should be 3 since the string "10" has one 1 and one 0 which fits the problem statement of '  at most m 0's and n 1's '

#### Code you used for Submit/Run operation

I have not created a program since I did not clearly understand the question.
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@joblesshuman The expected output is correct. Please check this out! https://leetcode.com/problems/ones-and-zeroes/discuss/133579/Unit-test-failing-for-%2210%22%220%22%221%22-1-1
