### ISSUE TITLE
1232. [Check If It Is a Straight Line] Incorrect solution was accepted because of insufficient test case

### ISSUE THREAD

**Issue by urnot67** [LeetCode-Feedback/LeetCode-Feedback#294]
**What kind of the bug**
- [ ] test case is insufficient

**Describe the bug**
  An incorrect solution was accepted and listed as an example solution because of insufficient test case

**what language is your code written in**
C++

**The code you submit/run**
```
class Solution {
public:
bool checkStraightLine(vector<vector<int>>& coordinates) {
double slope = abs(double(coordinates[0][1] - coordinates[1][1]) / double(coordinates[0][0] - coordinates[1][0]));

for (int i = 2; i < coordinates.size(); ++i) {
double other = abs(double(coordinates[0][1] - coordinates[i][1]) / double(coordinates[0][0] - coordinates[i][0]));

if (other != slope) {
return false;
}
}

return true;
}
};

```

**Expected behavior**
   [[1,2],[2,3],[3,4],[0,3],[5,6],[6,7]]. Solution above should have failed this test case. As it is only checking the absolute of the slope, which is incorrect.

**Screenshots**

**Additional context**

**Comment by CooperCooperCooper** [comment]
Hi @urnot67 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @urnot67 ,
Thank you for your time. We've previously updated the problem using another feedback submitted to us slightly before this issue was shared here, so this issue is now fixed. We appreciate your time and support.
