### ISSUE TITLE
Wrong Test Case - 236. Lowest Common Ancestor of a Binary Tree

### ISSUE THREAD

**Issue by StamatisTiniakos** [LeetCode-Feedback/LeetCode-Feedback#2941]
#### Your LeetCode username
stiniakos

#### Category of the bug
- [ ] Question:  Lowest Common Ancestor of a Binary Search Tree (Top Questions for Amazon)
- [x ] Solution: Test Case Issue
- [ ] Language: Python

#### Description of the bug
One of the test cases is not a valid binary search tree causing the submission to fail

[3,5,1,6,2,0,8,null,null,7,4]
5
1

#### Code you used for Submit/Run operation

class Solution(object):
    def lowestCommonAncestor(self, root, p, q):
        """
        :type root: TreeNode
        :type p: TreeNode
        :type q: TreeNode
        :rtype: TreeNode
        """
        
        while root:
            
            if p.val<root.val and q.val<root.val:
                root = root.left
            
            elif p.val>root.val and q.val>root.val:
                root = root.right
            else:
                return root

#### Language used for code
Python

#### Expected behavior
The submitted solution works here: https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/

But not here: https://leetcode.com/explore/interview/card/amazon/78/trees-and-graphs/2984/

#### Additional context
I believe the following test case should be removed or the question should be updated:

[3,5,1,6,2,0,8,null,null,7,4]
5
1

**Comment by lc-kay** [comment]
@StamatisTiniakos Since the problems are not the same, a different solution is required to get accepted. Here are the problems: https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/ https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/ One is Binary Search Tree, whereas the other problem is just Binary Tree.
