### ISSUE TITLE
Missing Test Case - 698. Partition to K Equal Sum Subsets

### ISSUE THREAD

**Issue by JangveladzeDima** [LeetCode-Feedback/LeetCode-Feedback#2948]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@JangveladzeDima Please provide the missing test case and the accepted code. I will reopen this issue when there is more information. Thank you for understanding.
