### ISSUE TITLE
Insufficient test cases for "Cousins in Binary Tree" problem

### ISSUE THREAD

**Issue by zainuel** [LeetCode-Feedback/LeetCode-Feedback#295]
**What kind of the bug**
- [x] problem
- [x] solution
- [ ] language

**Describe the bug**
Example Test Case :  [1,4,3,null,4,null,5]
4
5
Imagine if the tree consists two nodes x and y (consider 4 and 5 from the above test case) in the left and right sub tree on the same depth with different parent, but if in any of the sub trees if there exists any other node with the same value of either x or y (duplicate node) just before the the one lying on the same depth(which is the solution) then the program should fail.

**what language is your code written in**
Java
**The code you submit/run**
```
class Solution {
    int resp = -1;
     int var1 = -1;
    boolean flag = false;
    public boolean isCousins(TreeNode root, int x, int y) {
        if(root.val == x || root.val == y){
            return false;
        }     
        if(root.left != null && root.right != null){
            if((root.left.val == x && root.right.val ==y) || 
               (root.left.val == y && root.right.val ==x)){
                return false;
            }
        }     
              helper(root,x,y,0);
         if(resp == -1){
            return false;
         }else{
            return resp == var1 ? true : false; 
         }
    }  
    private void helper(TreeNode node, int x, int y, int depth){
        if(node == null){
            return ;
        }       
        if((node.left != null && node.right != null) ){    
           if((node.left.val == y && node.right.val == x) || 
              (node.left.val == x &&  node.right.val == y)){
               return;            
           }         
        }
        
        if(node.val == x || node.val == y){
            resp = depth;
            return ;
        }
          helper(node.left,x,y,depth+1);
        if(resp != -1 && !flag){
            var1 = resp;
            resp = -1;
            flag = true;
        }
          helper(node.right,x,y,depth+1);
        if(resp != -1 && !flag){
            var1 = resp;
            resp = -1;
            flag = true;
        } 
    }
}
```

**Expected behavior**
The above mentioned solution should not get accepted as the test case
``` 
[1,4,3,null,4,null,5]
4
5 
``` 
fails for it.

**Screenshots**
<img width="395" alt="image" src="https://user-images.githubusercontent.com/12168588/81514957-6ab27080-934f-11ea-9b0c-3b8493e7d2e6.png">

**Additional context**

**Comment by CooperCooperCooper** [comment]
Hi @zainuel ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @zainuel ,
Thank you for your time. Upon a thorough review of this issue, we found the given test case is invalid because the problem statement is very clear that the tree has unique values. We appreciate your time and support.
