### ISSUE TITLE
Missing Test Case - 32. Longest Valid Parentheses

### ISSUE THREAD

**Issue by Abhiicode** [LeetCode-Feedback/LeetCode-Feedback#2950]
#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@Abhiicode Please provide the missing test case and the accepted code. I will reopen this issue when there is more information. Thank you for understanding.
