### ISSUE TITLE
Missing Test Case - 720. Longest Word in Dictionary

### ISSUE THREAD

**Issue by lilisemechka** [LeetCode-Feedback/LeetCode-Feedback#2954]
#### username 

semerikova

#### Category of the bug
- [ ] Solution

#### Description of the bug

Not all the possibilities were verified during the test. My code passed all the tests, however, my code is wrong. For example, it must fail with the input such as: 
["l","le","lel","lelelele"]
However, as I said previously, I passed all the tests.

#### Code you used for Submit/Run operation

```
class Solution(object):
    def longestWord(self, words):
        words.sort(key=lambda x: (len(x), x))
        longdict = defaultdict(list)
        maxlong = 0
        maxword = ""
        end = '0'
        for w in words:
            lenw = len(w)
            if lenw == 1:
                longdict[w].append(end)
                if lenw > maxlong:
                    maxlong = lenw
                    maxword = w
                continue
            if w[0] not in longdict:
                continue

            for l in range(lenw-1):
                if end not in longdict[w[l]]: 
                    break
                if l == lenw-2:
                    longdict[w[l]].append(w[l+1])
                    longdict[w[l+1]].append(end)
                    if lenw > maxlong:
                        maxlong = lenw
                        maxword = w
                elif w[l+1] in longdict[w[l]]:
                    continue
                else: 
                    break
        
        return maxword
```

#### Language used for code

Python

#### Expected behavior

I expected to fail the tests. However, I succeeded in all of them.

#### Additional context

It would be nice to add some additional tests in order to be sure to have the right solution.

**Comment by lc-kay** [comment]
Hi @lilisemechka 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @lilisemechka 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
