### ISSUE TITLE
488. Zuma Game

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#296]
**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
Missing edge test cases.

**what language is your code written in**
Python

**The code you submit/run**
```
class Solution(object):
    def findMinStep(self, a, h):
        def f(x):
            s=[]
            for i in x:
                if not s or s[-1][0]!=i:
                    while s and s[-1][1]>=3:
                        s.pop()
                    if not s or s[-1][0]!=i:
                        s.append([i,0])
                s[-1][1]+=1
            while s and s[-1][1]>=3:
                s.pop()
            return ''.join(x*y for x,y in s)
        q=collections.deque([(a,''.join(sorted(h)))])
        s=set(q)
        c=0
        while q:
            for _ in xrange(len(q)):
                a,h=q.popleft()
                for i in xrange(len(h)):
                    y=h[:i]+h[i+1:]
                    for j in xrange(len(a)+1):
                        x=f(a[:j]+h[i]+a[j:])
                        if not x:
                            return c+1
                        if (x,y) not in s:
                            q.append((x,y))
                            s.add(q[-1])
            c+=1
        return -1
```

**Expected behavior**
Test case:
""
"R"

Output:
-1

Expected output:
0

The solution is accepted but fails for this test case because it does no check on whether the initial state is equal to the final state. Instead it considers it as invalid.

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @leet212,
Thank you for your time. Upon reviewing this issue, we found the issue to be stemmed from a different source, so we've decided to not add the test case for now. We appreciate your support and understanding.

**Comment by leet212** [comment]
Hello @CooperCooperCooper. Thank you for the update.
I opened an issue that had a test case which was valid according to the given constraints and was being accepted by the judge as well. After reviewing the issue, the team found it was a valid test case according to the then incomplete constraints and used it to update the problem description and the judge's response.
How is this not a valid content contribution? Was the problem not updated as a result of my counter case?

**Comment by leet212** [comment]
Hello @CooperCooperCooper. Could you please respond to the above comment?
