### ISSUE TITLE
Missing Test Case - 1138. Alphabet Board Path

### ISSUE THREAD

**Issue by Fadejimi** [LeetCode-Feedback/LeetCode-Feedback#2962]
#### Your LeetCode username
Fadejimi

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
The description of the problem says "Return a sequence of moves that makes our answer equal to target in the minimum number of moves.  You may return any path that does so."

My solution for zdz returns "DDDDD!UUUUURRR!DDDDDLLL!" and the solution returns "DDDDD!UUUUURRR!DDDDLLLD!" which is the same length but different paths and still the solution is false.

#### Code you used for Submit/Run operation

```
class Solution {
    public String alphabetBoardPath(String target) {
        int row = 0, col = 0;
        StringBuilder sb = new StringBuilder();
        
        for (char ch: target.toCharArray()) {
            int i = (ch - 'a') +1;
            int currentRow = (i - 1)/5;
            int currentCol = ((i - 1) % 5);
            while (row != currentRow) {
                if (row > currentRow) {
                    row -= 1;
                    sb.append('U');
                }
                else {
                    row += 1;
                    sb.append('D');
                }
            }
            
            while (col != currentCol) {
                if (col > currentCol) {
                    col -= 1;
                    sb.append('L');
                } else {
                    col += 1;
                    sb.append('R');
                }
            }
            
            sb.append("!");
        }
        
        return sb.toString();
    }
}
```

#### Language used for code

Java

#### Expected behavior
I expect the test case to pass for this solution because it is the minimum path and my solution uses 0(1) space and 0(n) time.

**Comment by lc-kay** [comment]
@Fadejimi The expected output is correct. Please check out this post https://leetcode.com/problems/alphabet-board-path/discuss/350231/Is-this-answer-really-wrong-HELP Thank you for your time.
