### ISSUE TITLE
Missing test case - 1815. Maximum Number of Groups Getting Fresh Donuts

### ISSUE THREAD

**Issue by Ceay1** [LeetCode-Feedback/LeetCode-Feedback#2963]
#### Your LeetCode username:

Ceay

#### Category of the bug
- [ ] Question
- [X ] Solution
- [ ] Language

#### Description of the bug

One of the test cases is missing.
https://leetcode.com/submissions/detail/476024162/
9
[1, 1, 1, 1, 1, 1, 1, 1, 1, 6, 6, 6, 7]

#### Code you used for Submit/Run operation

```
class Solution:
    def maxHappyGroups(self, batchSize: int, groups: List[int]) -> int:
        
        counts=Counter([group % batchSize for group in groups])
        happy_groups=counts[0]
        counts[0]=0
            
        for num_groups in range(2,batchSize+1):
            remaining_groups=[ind for ind, count in counts.items() if count>0]
            remaining_groups.sort(key=lambda x: -counts[x])
            for comb in combinations_with_replacement(remaining_groups, num_groups):
                comb_counter=Counter(comb)
                while sum(comb) % batchSize==0 and all(counts[i]>=comb_counter[i] for i in comb_counter):
                    for i in comb_counter: counts[i]-=comb_counter[i]
                    happy_groups+=1
        
        if sum(counts.values())>0: happy_groups += 1 
        return happy_groups
```

#### Language used for code
Python 3.0

#### Expected behavior
Expected output: 4. The solution that I provided outputs 3, but passes all the test cases and is accepted.

#### Additional context
Test case: 
9
[1, 1, 1, 1, 1, 1, 1, 1, 1, 6, 6, 6, 7]
Correct output: 4
The code outputs 3 but passes all the test cases.

**Comment by lc-kay** [comment]
Hi @Ceay1 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Ceay1 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
