### ISSUE TITLE
756. Pyramid Transition Matrix

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#297]
**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
Problem has incorrect and ambiguous tag in related topic.

**what language is your code written in**
Python

**The code you submit/run**
```
class Solution(object):
    def pyramidTransition(self, b, w):
        def f(i,j):
            if i==-1:
                return True
            if j>i:
                return f(i-1,0)
            for x in d[z[i+1][j]+z[i+1][j+1]]:
                z[i][j]=x
                if f(i,j+1):
                    return True
                z[i][j]='*'
            return False
        d=collections.defaultdict(list)
        for i in w:
            d[i[:-1]].append(i[-1])
        n=len(b)
        z=[['*']*(i+1) for i in xrange(n-1)]
        z.append(list(b))
        return f(n-2,0)
```

**Expected behavior**
DFS and Bit manipulation are the tags in related topic. But the problem can only be solved using DFS or backtracking. I think the tag was left over from the initial solution which was wrong. It should be removed as it can be misleading and confusing to someone who takes a look at it.

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for your time. Upon reviewing this problem, we found it has some bitwise based solutions. Therefore, the tags will remain the same for now. We appreciate your support and understanding.
