### ISSUE TITLE
Missing Test Case - 1818. Minimum Absolute Sum Difference

### ISSUE THREAD

**Issue by sachuverma** [LeetCode-Feedback/LeetCode-Feedback#2977]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Code is accepted, but it should not be submitted
So, some cases are missing

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int MOD = pow(10,9)+7;
    int minAbsoluteSumDiff(vector<int>& nums1, vector<int>& nums2) {
      
      long long original_sum = 0, ans = 0;
      int n = nums1.size();
      
      long long max_ind = -1;
      long long max_diff = 0;
      
      for(int i=0; i<n; ++i){
        int diff = abs(nums1[i] - nums2[i]);
        original_sum += diff;
        if(max_diff < diff){
          max_diff = diff;
          max_ind = i;
        }
      }
      
      if(original_sum == 0) return original_sum;
      
      vector<int> sorted = nums1;
      sort(sorted.begin(), sorted.end());
      
      int rep1 = nums1[max_ind]; // for min greater
      int rep2 = nums1[max_ind]; // for max smaller
      
      for(int i=0; i<n; ++i){
        if(sorted[i] <= nums2[max_ind]) rep1 = sorted[i];
        else {
          rep2 = sorted[i];
          break;
        }
      }
      
      ans = original_sum - abs(nums1[max_ind] - nums2[max_ind]);
      long long ans1 = ans + abs(rep1 - nums2[max_ind]);
      long long ans2 = ans + abs(rep2 - nums2[max_ind]);
      
      ans = min(ans1, ans2);
      ans %= MOD;

      cout<<ans<<endl;
      return ans;
    }
};
```

#### Language used for code
C++ 

#### Expected behavior

Let us take,
nums1 = [1, 28, 21]
nums2 = [9, 21, 20]

if we replace index 1 with index 2
then `absolute sum will be = (9-1) + (21-21) + (21-20) = 8 + 0 + 1 = 9`

But if we try to submit code with logic where index with max difference is checked,
here, 
index 0 will be checked for replacement with that logic ans will give
`absolute sum = (9-1) + (28-21) + (21-20) = 8 + 7 + 1 = 16`
Which is not minimum

**Comment by lc-kay** [comment]
Hi @sachuverma 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @sachuverma 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
