### ISSUE TITLE
Missing Test Case - 220. Contains Duplicate III

### ISSUE THREAD

**Issue by Vadim-Pelyushenko** [LeetCode-Feedback/LeetCode-Feedback#2978]
#### Your LeetCode username

vpelyush

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution is accepted but fails on the following test case.
https://pastebin.com/RVTYBQjB
I chose to put it in a pastebin link since it's quite large.

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean containsNearbyAlmostDuplicate(int[] nums, int k, int t) {
        if(nums.length>9999)
            return false;
        for(int i=0;i<nums.length;i++){
            for(int j=i+1;j<Math.min(i+k+1,nums.length);j++){
                if(Math.abs((long)nums[i]-(long)nums[j])<=t){
                    return true;
                }
            }
        }
        return false;
    }
}
```

- To be clear, I did not submit or run the above code on LeetCode, as this is someone else's solution.
- I did test it out on an IDE to verify that it disagreed with my result.
- I did test out my own solution on LeetCode and saw that the judger agreed with my program's output on the test case.
- I found the above code as a sample of a 0ms solution from the Accepted Solutions Runtime Distribution.

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted because it fails on the test case.

#### Screenshots

Solution which fails test case
![image](https://user-images.githubusercontent.com/37136767/113496659-bd899f00-94b0-11eb-8493-c132764d1ef7.png)

Judger agreeing with expected result
![image](https://user-images.githubusercontent.com/37136767/113496704-2bce6180-94b1-11eb-865c-70fcb4929d7e.png)

#### Additional context

Could not submit my test case manually on LeetCode. Test case submissions are capped at 10,000 characters. Which would explain why the incorrect solution checks around that length.

**Comment by lc-kay** [comment]
Hi @Vadim-Pelyushenko 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Vadim-Pelyushenko 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
