### ISSUE TITLE
Missing Test Case - 1946. Minimum Absolute Sum Difference

### ISSUE THREAD

**Issue by vagarwal1c** [LeetCode-Feedback/LeetCode-Feedback#2979]
#### Your LeetCode username

ashvaibhav

#### Description of the bug

Missing Test Case for https://leetcode.com/contest/weekly-contest-235/problems/minimum-absolute-sum-difference/.
Test case being:
```
[10,20,30,40,50]
[510,520,530,540,550]
```

#### Code you used for Submit/Run operation

Buggy code that was accepted but should have failed:
```class Solution {
    public int minAbsoluteSumDiff(int[] nums1, int[] nums2) {
        int n = nums1.length;
        long diff=0;
        int idx = 0;
        int max = Integer.MIN_VALUE;
        for(int i=0; i<n; i++){
            int cur = Math.abs(nums1[i]-nums2[i]);
            if(cur>=max){
                max= Math.max(cur,max);
                idx = i;
            }
            diff+= (long) cur;
        }
        if (diff==0) return 0;
        int min = max;
        for(int i=0; i<n; i++){
            min = Math.min(min, Math.abs(nums1[i]-nums2[idx]));
        }
        long ans = (diff-max+min) %1000000007;
        return (int) ans;
    }
}
```

#### Language used for code

Java

#### Screenshots

Screenshots are attached below
<img width="1194" alt="Screen Shot 2021-04-03 at 9 14 07 PM" src="https://user-images.githubusercontent.com/80418499/113498420-ab642c80-94c1-11eb-8261-7484361cd5ad.png">

**Comment by Silvia42** [comment]
Your LeetCode username:  Silvia42

This Python 3 Code is also WRONG and ACCEPTED.

Missing Test: 
[150,100] 
[90,10]

![Screenshot_2021-04-04 Minimum Absolute Sum Difference - LeetCode(1)](https://user-images.githubusercontent.com/37594365/113499074-f5a8d600-94e0-11eb-8a1d-49520fc22a40.png)


```class Solution:
    def minAbsoluteSumDiff(self, nums1: List[int], nums2: List[int]) -> int:
        big=10**9+7
        n=len(nums1)
        maxIndex=0
        maxValue=0
        sumAbsNums=0
        for i in range(n):
            dx=abs(nums1[i]-nums2[i])
            if dx>maxValue:
                maxIndex=i
                maxValue=dx
            sumAbsNums+=dx
            sumAbsNums%=big

        y=nums2[maxIndex]
        newValue=maxValue
        for i in range(n):
            newValue=min(newValue,abs(nums1[i]-y))
            
        sumAbsNums+=newValue+big-abs(nums1[maxIndex]-nums2[maxIndex])
        return sumAbsNums%big```

**Comment by lc-kay** [comment]
Hi @vagarwal1c 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@Silvia42 I've relayed your missing test cases to our team to investigate as well.

**Comment by lc-kay** [comment]
Hi @vagarwal1c @Silvia42 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
