### ISSUE TITLE
Weak testcase for the problem 1443

### ISSUE THREAD

**Issue by albertplus007** [LeetCode-Feedback/LeetCode-Feedback#298]
**Weak testcase for the problem [1443](https://leetcode.com/problems/minimum-time-to-collect-all-apples-in-a-tree/)**

**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
the description of the problem is ambiguous.

we can say root of the tree is `0`, or add more testcase
```
Input:

4
[[0,2],[0,3],[1,2]]
[false,true,false,false]

Input:
3
[[0,2],[1,2]]
[false,true,false]

Input:
9
[[0,2],[1,5],[2,3],[2,6],[4,7],[4,8],[0,1],[1,4]]
[false,false,false,false,false,false,false,true,true]
```

**what language is your code written in**
C++

**The code you submit/run**
```cpp

class Solution {
public:
    int minTime(int n, vector<vector<int>>& edges, vector<bool>& hasApple) {
        vector<vector<int>>graph(n);
        unordered_set<int>v;
        for(auto e:edges)
        {
            graph[e[0]].push_back(e[1]);
            graph[e[1]].push_back(e[0]);
        }
        v.insert(0);
        return dfs(graph, v, hasApple, 0);
    }
    int dfs(vector<vector<int>>& graph, unordered_set<int>& v, vector<bool>& has, int cur)
    {
        int res = 0;
        for(auto a:graph[cur])
        {
            if(v.count(a))continue;
            v.insert(a);
            res += dfs(graph, v, has, a);
        }
        if((res > 0 || has[cur]) && cur != 0)res += 2;
        return res;
    }
};
```

**Expected behavior**
if we don't change the description, add the testcase, or add`the root of tree is 0`in the problem, my code can pass the testcase in the leetcode, but some code in the conteset can not pass the testcase my offered.

**Screenshots**
![image](https://user-images.githubusercontent.com/59787435/81590533-83716380-93ed-11ea-8b23-0659fc6f14e9.png)
this code can be get accepted by the leetcode, but can not pass my testcase.
it can be get accept by the leetcode
![image](https://user-images.githubusercontent.com/59787435/81590729-dcd99280-93ed-11ea-9207-02ae6b5b7841.png)

the following is my code:
![image](https://user-images.githubusercontent.com/59787435/81590827-098daa00-93ee-11ea-8599-68a3bf830031.png)

**Additional context**

**Comment by CooperCooperCooper** [comment]
Hi @albertplus007 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by albertplus007** [comment]
**Describe the bug**

add some detail:
the problem describe `undirected tree`, so i think add the following testcase:

```
Input:

4
[[0,2],[0,3],[1,2]]
[false,true,false,false]

Input:
3
[[0,2],[1,2]]
[false,true,false]

Input:
9
[[0,2],[1,5],[2,3],[2,6],[4,7],[4,8],[0,1],[1,4]]
[false,false,false,false,false,false,false,true,true]
```
and the problem doesn't say which one is root, this problem make the same mistake as the problem [1361. Validate Binary Tree Nodes](https://leetcode.com/problems/validate-binary-tree-nodes/) which is add more testcase. 
the problem  [1361discuss](https://leetcode.com/problems/validate-binary-tree-nodes/discuss/517669/THE-STANDARD-CODE-IS-WRONG)

**Comment by Zhenghao-Liu** [comment]
Agree ,bro. 
I provided the same [issue](https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/288).
But this test sample has caused a lot of controversy.

**Comment by CooperCooperCooper** [comment]
Hi @albertplus007 ,
Thank you for your time. Since there is no additional code contrasting these given test cases, we will not be adding these test cases. If you have the code, please share it in the new comment and tag me on it. I will share them with our team.
