### ISSUE TITLE
Missing Test Cases - 1818. Minimum Absolute Sum Difference

### ISSUE THREAD

**Issue by dheeraj2645** [LeetCode-Feedback/LeetCode-Feedback#2980]
#### Your LeetCode username
Heisen_berg1

#### Category of the bug
- [ ] Question
- [- ] Solution
- [ ] Language

#### Description of the bug
Some Testcases are missing.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int mod = 1e9 + 7;
    int minAbsoluteSumDiff(vector<int>& nums1, vector<int>& nums2) {
        int ans = 0;
        int n = nums1.size();
        int maxDiff = 0;
        int index = 0;
        for(int i = 0;i < n;i++)
        {
            int diff = abs(nums1[i] - nums2[i]);
            ans =(ans + diff)%mod;
            if(diff > maxDiff){
                index  = i;
                maxDiff = diff;
            }
        }
        ans -= maxDiff;
        for(auto& val: nums1)
        {
            maxDiff = min(maxDiff, abs(val - nums2[index]));
        }
        ans = (ans + maxDiff)%mod;
        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior
For some of the test cases code is giving wrong answers but still got accepted.
TestCase1: 
nums1=[5,2,7]
nums2=[10,7,12]
Expected behavior: It has to replace index 2(1-indexed) element from nums1 with index 3 element of nums1 and expected answer is 10 but the output is 13.
TestCAse2:
nums1=[5,4,7]
nums2=[10,8,10]
Expected behavior: It has to replace index 2(1-indexed) element from nums1 with index 3 element of nums1 and expected answer is 9 but the output is 10.

#### Screenshots
![image](https://user-images.githubusercontent.com/66384202/113499040-3b40bf80-9530-11eb-9591-5635056c611f.png)
![image](https://user-images.githubusercontent.com/66384202/113499067-7f33c480-9530-11eb-88ac-5028309df550.png)

**Comment by lc-kay** [comment]
Hi @dheeraj2645 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @dheeraj2645 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
