### ISSUE TITLE
Missing Test Case - 1818. Minimum Absolute Sum Difference

### ISSUE THREAD

**Issue by ankitgin** [LeetCode-Feedback/LeetCode-Feedback#2982]
#### Your LeetCode username
ankitgin

#### Category of the bug
- [ ] Solution

#### Description of the bug
Missing important test cases.

#### Code you used for Submit/Run operation

```
class Solution {
    public int minAbsoluteSumDiff(int[] nums1, int[] nums2) {
        
        //Algo - calculate abs sum
        // mark the index of max difference
        // update that index will closest value in nums1
        
        int diff=0;
        double ans=0;
        int maxDiff= Integer.MIN_VALUE;
        int maxDiffIndex = -1;
        
        
        for(int i=0; i<nums1.length;i++){
            diff = Math.abs(nums1[i] - nums2[i]);
            if(diff > maxDiff){
                maxDiff = diff;
                maxDiffIndex = i;
            }
            ans = (ans + diff)%(Math.pow(10,9) +7);
        }
        
        //System.out.println(ans);
        
        //now find closest element in nums1 to nums2[maxDiffIndex]
        
        int minDiff = Integer.MAX_VALUE;
        int minDiffValue =0;
        int minDiffIndex =-1;
        for(int i=0; i< nums1.length; i++){
            diff = Math.abs( nums1[i] - nums2[maxDiffIndex]);
            if(diff <minDiff){
                minDiff = diff;
                minDiffValue = nums1[i];
                minDiffIndex = i;
            }
        }
        
        //System.out.println(minDiffIndex);
        int change = maxDiff - minDiff;
        
        ans = (ans - change)%(Math.pow(10,9) +7);
        
        return (int) ans;
    }
}
```

#### Language used for code
Java

#### Expected behavior
Reject the code for the following test case:

[1,5,6,4]
[2,6,8,5]

My answer: 5
Expected answer: 4

Still, the code is accepted since the test cases are week.
#### Additional context
This was used in the weekly contest 235 and impacted the ratings of the participants. This question should not be used in ranking for this contest.

**Comment by lc-kay** [comment]
Hi @ankitgin 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @ankitgin 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
