### ISSUE TITLE
Missing Test Case - 1818. Minimum Absolute Sum Difference

### ISSUE THREAD

**Issue by leetcodedafu** [LeetCode-Feedback/LeetCode-Feedback#2983]
#### Your LeetCode username
<leetcode_dafu>

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
<A solution is accepted but fails on the following test case.
[100,6,2]
[90,2,2]
>

#### Code you used for Submit/Run operation

```
max_diff = float('-inf')
n = len(nums1)
idx = None
_sum=0

for i in range(n):
    diff = abs(nums1[i]-nums2[i])

    _sum+=diff
    if diff>max_diff:
        idx = i
        max_diff = diff

if max_diff==0:
    return _sum%(1000000007)

new_diff = max_diff
for i in range(n):
    curr_diff = abs(nums1[i]-nums2[idx])
    if curr_diff<new_diff:
        new_diff = curr_diff
        
return (_sum-max_diff+new_diff)%(1000000007)
```

#### Language used for code
Python

**Comment by lc-kay** [comment]
@leetcodedafu Please provide the submission details link to your accepted code. Thank you!

**Comment by lc-kay** [comment]
Hi @leetcodedafu 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
