### ISSUE TITLE
Missing Test Case - 1818. Minimum Absolute Sum Difference

### ISSUE THREAD

**Issue by ericsseo** [LeetCode-Feedback/LeetCode-Feedback#2984]
#### Your LeetCode username
eseo88

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language

#### Description of the bug
The test cases for accepting the solution is not comprehensive enough so that wrong algorithms get accepted.

#### Code you used for Submit/Run operation
```
# wrong algorithm solution where it only consider switching on the index where original difference is the largest.
# this code is from my friend (username: yhw99go)
class Solution:
    def minAbsoluteSumDiff(self, nums1: List[int], nums2: List[int]) -> int:
        modulo = 10**9 + 7
        n = len(nums1)
        max_diff = 0
        change_index = 0
        min_diff = float('inf')
        nums1_change_index=0
        ans = 0
        for i in range(n):
            if abs(nums1[i]-nums2[i]) > max_diff:
                max_diff = abs(nums1[i]-nums2[i])
                change_index = i
        if max_diff == 0:
            return 0
        for i in range(n):
            if i != change_index and abs(nums1[i]-nums2[change_index]) < min_diff:
                min_diff = abs(nums1[i]-nums2[change_index]) 
                nums1_change_index=i
        nums1[change_index] = nums1[nums1_change_index]
        for i in range(n):
            ans += abs(nums1[i] - nums2[i])
        return divmod(ans, modulo)[1]
```

#### Language used for code
python3

#### Expected behavior
Wrong answer upon submission.

#### Screenshots
![Screen Shot 2021-04-04 at 12 19 48 AM](https://user-images.githubusercontent.com/3475183/113499442-ae6c1680-94db-11eb-8ab6-4faa0f6be77a.png)

The screenshot shows the code gets accepted upon submission even though I manually found the counter example ([198, 100, 10000], [198, 198, 10099]) 

#### Additional context
Fix of the testing cases will affect the [Weekly Contest 235](https://leetcode.com/contest/weekly-contest-235) result as well.

**Comment by lc-kay** [comment]
Hi @ericsseo 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @ericsseo 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
