### ISSUE TITLE
Missing Test Case - 1818. Minimum Absolute Sum Difference

### ISSUE THREAD

**Issue by h493** [LeetCode-Feedback/LeetCode-Feedback#2985]
#### Your LeetCode username
 Leetcode Id: HIMANSHUCHHIKARA
username : Himanshu Chhikara

#### Category of the bug
- [ ] Question

#### Description of the bug
I have wrote a wrong solution which I know is missing some testcases but unfortunately it got passed. You have missed some testcases.

#### Code you used for Submit/Run operation

```
//Minimum Absolute Sum Difference
class Solution {
    public int minAbsoluteSumDiff(int[] nums1, int[] nums2) {
        int mod=(int)Math.pow(10,9)+7;
        int sum=0;
        int n=nums1.length;
        int maxDifference=-1; 
        int maxIndex=-1;
        for(int i=0;i<n;i++){
            int diff=Math.abs(nums1[i]-nums2[i]);
            sum=(sum%mod + diff%mod)%mod;
            
            if(diff>maxDifference){
                maxDifference=diff;
                maxIndex=i;
            }
        }
        
        sum-=maxDifference;
        
        int min=maxDifference;
        int val2=nums2[maxIndex];
        for(int i=0;i<n;i++){
            int val1=nums1[i];
            min=Math.min(min,Math.abs(val1-val2));
        }
        
        sum+=min;
        
        return sum;
    }
}
```

#### Language used for code
JAVA

#### Expected behavior
I was expecting a wrong answer on this testcase:
[42,43,44,45]
[2,3,4,5]
Correct output is 157 but my code is producing 160. But you have not included testCase like this and mywrong code have passed all testcases which you have provided. 

#### Screenshots
<img width="1440" alt="Screen Shot 2021-04-04 at 11 05 28 AM" src="https://user-images.githubusercontent.com/56367300/113499716-c2446680-9535-11eb-97e8-73ed262ac3d9.png">

**Comment by lc-kay** [comment]
Hi @h493 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @h493 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
