### ISSUE TITLE
Missing Test Case - 1818. Minimum Absolute Sum Difference

### ISSUE THREAD

**Issue by saketkumar1** [LeetCode-Feedback/LeetCode-Feedback#2987]
#### Your LeetCode username

saketkumar8385

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

ques have some of the missing tests 
my code accepted in the contest but by manually putting test case it fails in some of it

[1, 1,1,10]
[10, 10,10,100]  , 

[90,10,5]
[100,1,5]
missing test case

#### Code you used for Submit/Run operation

```
// Minimum Absolute Sum Difference
class Solution {
    public int minAbsoluteSumDiff(int[] nums1, int[] nums2) {
     int MOD=1000000000+7;
       int ans = 0;
		int max = 0;
		int idx = -1;

		for (int i = 0; i < nums1.length; i++) {
			int sum = Math.abs(nums1[i] - nums2[i]);
			ans += sum;
            ans=ans%MOD;
			if (idx == -1 || max < sum) {
				max = sum;
				idx = i;
			}

		}

		ans = ans - max;
		int a = nums1[idx];
		int b = nums2[idx];

		for (int i = 0; i < nums1.length; i++) {

			int sum1 = Math.abs(nums1[i] - b);

			

			max = Math.min(max, sum1);

		}

		return (ans + max)%MOD;
    }
};
```

#### Language used for code

Java

#### Expected behavior

Wrong Answer

#### Screenshots

![image](https://user-images.githubusercontent.com/66872047/113500376-0e45da00-953b-11eb-80e0-47c09ecc8cb0.png)

**Comment by saketkumar1** [comment]
have some of the missing test case in quesition

**Comment by lc-kay** [comment]
Hi @saketkumar1 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @saketkumar1 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
