### ISSUE TITLE
Missing Test Case - 1818. Minimum Absolute Sum Difference

### ISSUE THREAD

**Issue by Aniket-Jain-byte** [LeetCode-Feedback/LeetCode-Feedback#2988]
#### Your LeetCode username
LeetCode - username = helloaniorigamiwpu

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

My solutions gets passed but fails on this test case.
[10,13,9]
[2,7,9]

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int minAbsoluteSumDiff(vector<int>& nums1, vector<int>& nums2) {
        int ind = -1,maxAbsDiff = 0 , sum = 0;
        int mod = 1e9 + 7;
        
        
        for(int i = 0;i<nums1.size();i++){
            if(abs(nums1[i] - nums2[i]) > maxAbsDiff){
                maxAbsDiff = abs(nums1[i] - nums2[i]);
                ind = i;
            }
            sum %= mod;
            sum += abs(nums1[i] - nums2[i])%mod;
        }
        
        if(ind == -1) return maxAbsDiff;
        
        
        int k = maxAbsDiff;
        for(int i = 0;i<nums1.size();i++){
            if(i!=ind){
                k = min(abs(nums1[i] - nums2[ind])%mod, k);
            }
        }
        

        sum -= (maxAbsDiff - k);
        return sum%mod;
    }
};
```
#### Language used for code

C++

#### Expected behavior

The code should fail

#### Screenshots

![image](https://user-images.githubusercontent.com/76682881/113500554-895bc000-953c-11eb-8d79-fd8e674ab43f.png)

**Comment by lc-kay** [comment]
Hi @Aniket-Jain-byte 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Aniket-Jain-byte 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by Aniket-Jain-byte** [comment]
@lc-kay thanks a lot
