### ISSUE TITLE
Missing Test Case - 1818. Minimum Absolute Sum Difference

### ISSUE THREAD

**Issue by petrovic-ivan** [LeetCode-Feedback/LeetCode-Feedback#2989]
#### Your LeetCode username

petrovic-ivan

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Code accepted but failed for this test case:
[11,12,13]
[2,13,13]

#### Code you used for Submit/Run operation

```
var minAbsoluteSumDiff = function(nums1, nums2) {
    const n = nums1.length;
    let ans = 0;
    let maxSum = -1;
    let maxSumIdx = -1;

    for (let i = 0; i < n; i++) {
        const sum = Math.abs(nums1[i] - nums2[i]);
        if (maxSum < sum) {
            maxSum = sum;
            maxSumIdx = i;
        }
        ans = (ans + sum) % 1000000007;
    }
    if (!ans) return 0;

    let value = getClosest(nums1, nums2[maxSumIdx]);
    ans = ans - Math.abs(Math.abs(value - nums2[maxSumIdx]) - Math.abs(nums1[maxSumIdx] - nums2[maxSumIdx]));
    return ans;
};

const getClosest = function(clst, n) {
    let min = 100001;
    let el = -1;

    for (let i = 0; i < clst.length; i++) {
        let curr = Math.abs(clst[i] - n);
        if (curr < min) {
            el = clst[i];
            min = curr;
        }
    }
    return el;
};
```

#### Language used for code

JavaScript

#### Expected behavior

Output should be 9 and code should fail.

**Comment by lc-kay** [comment]
Hi @petrovic-ivan 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @petrovic-ivan 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
