### ISSUE TITLE
149. Max Points on a Line [Missing Test Cases]

### ISSUE THREAD

**Issue by devenps** [LeetCode-Feedback/LeetCode-Feedback#299]
**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
Incorrect solution is accepted because of insufficient test case.
Test case: [[1,1],[1,1],[0,0],[3,4], [4,5],[5,6],[7,8],[8,9]] which is missing.

**what language is your code written in**
Java

**The code you submit/run**
```
// Max Points on a Line
class Solution {
    public int maxPoints(int[][] points) {
        if (points.length < 3) return points.length;
        int res = 1;
        Set<List<Integer>> set = new HashSet<>();
        for (int i = 0; i < points.length - 1; i++) {
            if (!set.add(Arrays.asList(points[i][0], points[i][1]))){
                break;
            }

            if (res > points.length-i){
                break;
            }
            Map<List<Integer>, Integer> map = new HashMap<>();
            int max = 0, duplicatePoints = 0;
            for (int j = i + 1; j < points.length; j++) {
                int dy = points[j][1] - points[i][1];
                int dx = points[j][0] - points[i][0];
                if (dy == 0 && dx == 0) {
                    duplicatePoints++;
                    continue;
                }

                List<Integer> key = getSlope(dy, dx);
                map.put(key, map.getOrDefault(key, 0) + 1);
                max = Math.max(max, map.get(key));
            }
            res = Math.max(res, max + 1 + duplicatePoints);
        }

        return res;
    }

    private List<Integer> getSlope(int dy, int dx) {
        if (dy == 0) return Arrays.asList(0, 1);
        if (dx == 0) return Arrays.asList(1, 0);

        int gcd = getGCD(dy, dx);
        return Arrays.asList(dy / gcd, dx / gcd);
    }

    private int getGCD(int a, int b) {
        if (b == 0) return a;
        return getGCD(b, a % b);
    }
}
```

**Expected behavior**
This test case should return 5 but my above code is returning 3 and still, the solution got accepted. PFA screeshot.

**Screenshots**
My custom test case is failing in the screenshot, still, solution got accepted in the below screenshot.
![image](https://user-images.githubusercontent.com/8740608/81607143-d6e5b080-93f1-11ea-84c1-fb0c0cefb8b9.png)

**Additional context**
Solution link: https://leetcode.com/submissions/detail/337945185/

**Comment by CooperCooperCooper** [comment]
Hi @devenps ,
Thank you for reaching out to us. Would you please put the mentioned test case under "Describe the Bug" section? Thank you :)

**Comment by devenps** [comment]
@CooperCooperCooper added

**Comment by CooperCooperCooper** [comment]
Hi @devenps ,
Thank you for sharing the test case with us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @devenps ,
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
