### ISSUE TITLE
Missing Test Case - 1818. Minimum Absolute Sum Difference

### ISSUE THREAD

**Issue by Anish0203** [LeetCode-Feedback/LeetCode-Feedback#2990]
#### Your LeetCode username
anishagarwal20

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
I submitted the wrong solution to the question and it accepted. It shows that the test cases are weak.

#### Code you used for Submit/Run operation
class Solution {
public:
    int mod=1e9+7;
    int minAbsoluteSumDiff(vector<int>& nums1, vector<int>& nums2) {
        long long int maxi=0,i,pos=0,n=nums1.size();
       //Initially I am finding out the position where I should get maximum difference but since there are multiple positions at
 //which it can occur, this solution is incorrect
        for(i=0;i<n;i++)
        {
            long long int val=1ll*abs(nums1[i]-nums2[i]);
            if(val>maxi)
            {
                maxi=val;
                pos=i;
            }
        }
        long long int mini=maxi;
        for(i=0;i<n;i++)
        {
            long long int val=1ll*abs(nums1[i]-nums2[pos]);
            if(val<mini)
                mini=val;
        }
        long long int ans=0;
        for(i=0;i<n;i++)
        {
            if(i==pos)
            ans+=mini;
            else
                ans+=1ll*abs(nums1[i]-nums2[i]);
            ans%=mod;
        }
        return ans;
    }
};

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code
C++

#### Expected behavior
nums1=[6,1,1,5]
nums2=[10,4,5,9]

This is the test case on which my code fails yet it got accepted.

#### Additional context
Please add strong test cases.

**Comment by lc-kay** [comment]
@Anish0203 Please provide the submission details link or the formatted code. Thank you!

**Comment by Anish0203** [comment]
Link to the submitted code: https://leetcode.com/submissions/detail/476296904/
It actually fails at the test case that I have provided: 
nums1=[6,1,1,5]
nums2=[10,4,5,9]

**Comment by lc-kay** [comment]
Hi @Anish0203 
Thank you! I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Anish0203 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
