### ISSUE TITLE
Missing Test Case - 622. Design Circular Queue

### ISSUE THREAD

**Issue by mmcgarg** [LeetCode-Feedback/LeetCode-Feedback#2991]
#### Your LeetCode username
mmcgarg

#### Category of the bug
Question

#### Description of the bug
Missing test cases, where rear or front methods are called before enqueue or dequeue.                                             

#### Code you used for Submit/Run operation
```
class MyCircularQueue {
    int[] arr;
    int head;
    int tail;
    int size;
    
    public MyCircularQueue(int k) {
        arr = new int[k];
        Arrays.fill(arr, -1);
        head = -1;
        tail = -1;
        size = 0;
    }
    
    public boolean enQueue(int value) {
        if(size == arr.length)
            return false;
        tail++;
        tail = tail % arr.length;
        arr[tail] = value;
        if(head == -1)
            head++;
        size++;
        return true;
    }
    
    public boolean deQueue() {
        if(size == 0 || head == -1)
            return false;
        size--;
        arr[head++] = -1;
        head = head % arr.length;
        return true;
    }
    
    public int Front() {
        return arr[head];
    }
    
    public int Rear() {
        return arr[tail];
    }
    
    public boolean isEmpty() {
        return size == 0;
    }
    
    public boolean isFull() {
        return size == arr.length;
    }
}

/**
 * Your MyCircularQueue object will be instantiated and called as such:
 * MyCircularQueue obj = new MyCircularQueue(k);
 * boolean param_1 = obj.enQueue(value);
 * boolean param_2 = obj.deQueue();
 * int param_3 = obj.Front();
 * int param_4 = obj.Rear();
 * boolean param_5 = obj.isEmpty();
 * boolean param_6 = obj.isFull();
 */
};
```

#### Language used for code
Java

#### Expected behavior
An error should be thrown when rear or front are called in the above code.

#### Screenshots
N/A

#### Additional context
N/A

**Comment by lc-kay** [comment]
@mmcgarg Please provide the test case in [] format. Thank you!

**Comment by mmcgarg** [comment]
Here is a failing test case:

["MyCircularQueue","Rear","enQueue","enQueue","enQueue","Rear","isFull","deQueue","enQueue"]
[[3],[],[2],[3],[4],[],[],[],[4]]

**Comment by lc-kay** [comment]
Hi @mmcgarg 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @mmcgarg 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
