### ISSUE TITLE
Missing Test Case - 746. Min Cost Climbing Stairs

### ISSUE THREAD

**Issue by ashokion** [LeetCode-Feedback/LeetCode-Feedback#2994]
#### Your LeetCode username

champion1_

#### Category of the bug
- [ ] Question
- [. ] Solution
- [ ] Language

#### Description of the bug

corner testcases are missing. When there are only two elements in the array cost we need to return minimum of first and second element. However currently if we return only second element then also it is accepted.

#### Code you used for Submit/Run operation

```
class Solution {
    public int min(int x,int y){
        if(x>y) return y;
        return x;
    }
    public int minCostClimbingStairs(int[] cost) {
        if(cost.length==0) return 0;
        if(cost.length==1) return cost[0];
        if(cost.length==2) return min(cost[1],cost[0]);  //earlier I submitted cost[1] that is also accepted

        int[] dp=new int[cost.length];
        dp[0]=cost[0];
        dp[1]=cost[1];
        for(int i=2;i<cost.length;i++){
            dp[i]=min(dp[i-1]+cost[i],dp[i-2]+cost[i]);
        }
        return min(dp[cost.length-1],dp[cost.length-2]);
    }
}
```

#### Language used for code

Java

#### Expected behavior

If testcase is [1,100] then output should be 1. This testcase is not checked in submitted assignment.

**Comment by stormsunshine** [comment]
@ashokion Please provide the original code that is accepted but fails on a specific test case. For this issue, the code is as follows, which is accepted but fails on the test case `[1,100]`.
```
class Solution {
    public int min(int x,int y){
        if(x>y) return y;
        return x;
    }
    public int minCostClimbingStairs(int[] cost) {
        if(cost.length==0) return 0;
        if(cost.length==1) return cost[0];
        if(cost.length==2) return cost[1];

        int[] dp=new int[cost.length];
        dp[0]=cost[0];
        dp[1]=cost[1];
        for(int i=2;i<cost.length;i++){
            dp[i]=min(dp[i-1]+cost[i],dp[i-2]+cost[i]);
        }
        return min(dp[cost.length-1],dp[cost.length-2]);
    }
}
```

**Comment by ashokion** [comment]
> @ashokion Please provide the original code that is accepted but fails on a specific test case. For this issue, the code is as follows, which is accepted but fails on the test case `[1,100]`.
> 
> ```
> class Solution {
>     public int min(int x,int y){
>         if(x>y) return y;
>         return x;
>     }
>     public int minCostClimbingStairs(int[] cost) {
>         if(cost.length==0) return 0;
>         if(cost.length==1) return cost[0];
>         if(cost.length==2) return cost[1];
> 
>         int[] dp=new int[cost.length];
>         dp[0]=cost[0];
>         dp[1]=cost[1];
>         for(int i=2;i<cost.length;i++){
>             dp[i]=min(dp[i-1]+cost[i],dp[i-2]+cost[i]);
>         }
>         return min(dp[cost.length-1],dp[cost.length-2]);
>     }
> }
> ```
Yes this is my original solution which should fail on testcase [1,100] or in general testcase `[i,j]` `j>i` but is accepted.
'''


    class Solution{
        public int min(int x,int y){
        if(x>y) return y;
        return x;
    }
    public int minCostClimbingStairs(int[] cost) {
        if(cost.length==0) return 0;
        if(cost.length==1) return cost[0];
        if(cost.length==2) return cost[1];
        int[] dp=new int[cost.length];
        dp[0]=cost[0];
        dp[1]=cost[1];
        for(int i=2;i<cost.length;i++){
            dp[i]=min(dp[i-1]+cost[i],dp[i-2]+cost[i]);
        }
        return min(dp[cost.length-1],dp[cost.length-2]);
    }

'''
Later I changed it to following
'''


    class Solution{
        public int min(int x,int y){
        if(x>y) return y;
        return x;
    }
    public int minCostClimbingStairs(int[] cost) {
        if(cost.length==0) return 0;
        if(cost.length==1) return cost[0];
        if(cost.length==2) return min(cost[1],cost[0]);
        int[] dp=new int[cost.length];
        dp[0]=cost[0];
        dp[1]=cost[1];
        for(int i=2;i<cost.length;i++){
            dp[i]=min(dp[i-1]+cost[i],dp[i-2]+cost[i]);
        }
        return min(dp[cost.length-1],dp[cost.length-2]);
    }

'''

**Comment by lc-kay** [comment]
Hi @ashokion 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @ashokion 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
