### ISSUE TITLE
TLE in Python3, accepted in Java - 1799. Maximize Score After N Operations

### ISSUE THREAD

**Issue by gautamsw5** [LeetCode-Feedback/LeetCode-Feedback#2995]
GautamWadhwani2134
#### Category of the bug
- [ ] Question
- [ ] Solution
-  Language

#### Description of the bug

The hint clearly mentions "Brute force recursion is acceptable", but the same logic in Java passed all testcases but in Python3, it gave TLE after test case 69. Please increase the time limit for Python3 for this problem.

#### Code you used for Submit/Run operation

```
class Solution:
    def gcd(self,a,b):
        if b==0:
            return a
        return self.gcd(b, a%b)
    def maxScore(self, arr):
        self.ans = 0
        self.curp = []
        def recsol(arr):
            if len(arr)==0:
                s = 0
                trr = []
                for i in self.curp:
                    trr.append(self.gcd(i[0],i[1]))
                trr.sort()
                for i in range(len(trr)):
                    s += (i+1)*trr[i]
                self.ans = max(self.ans, s)
                return
            for i in range(1,len(arr)):
                self.curp.append(tuple(sorted([arr[0],arr[i]])))
                brr = list(arr)
                del brr[i]
                del brr[0]
                recsol(brr)
                del self.curp[-1]
        recsol(arr)
        return self.ans
```

#### Language used for code

Python3

#### Expected behavior

I expected this code to pass all the testcases because according to the hints provided, brute force is an accepted solution.

#### Screenshots

![image](https://user-images.githubusercontent.com/72446354/113508218-5af5d900-956c-11eb-9091-dbed85e02a52.png)
![image](https://user-images.githubusercontent.com/72446354/113508235-72cd5d00-956c-11eb-8a14-201ed56e774f.png)
![image](https://user-images.githubusercontent.com/72446354/113508241-7eb91f00-956c-11eb-994e-d9a703918409.png)
![image](https://user-images.githubusercontent.com/72446354/113508251-8d073b00-956c-11eb-98d1-60ad32d96ecd.png)

**Comment by lc-kay** [comment]
Hi @gautamsw5 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@gautamsw5 Our team has reviewed this report and concluded that for Python, it can TLE or pass depending on the implementation. Please check out the problem discuss section for accepted Python implementations. Thank you for your time.

**Comment by gautamsw5** [comment]
No one has used brute-force in Python3 in discuss section but according to the hint, brute-force is accepted.

**Comment by gautamsw5** [comment]
@lc-kay  No one has used brute-force in Python3 in discuss section but according to the hint, brute-force is accepted.
