### ISSUE TITLE
Missing Test Case - 1818. Minimum Absolute Sum Difference

### ISSUE THREAD

**Issue by cloverpku** [LeetCode-Feedback/LeetCode-Feedback#2996]
#### Your LeetCode username
cloverpku

#### Category of the bug
- [ ] Question: missing test

#### Description of the bug
Proposed test case: 
[1,7,4,8]
[2,3,4,4]

#### Code you used for Submit/Run operation

Below are incorrect codes which got accepted
```
class Solution:
    def minAbsoluteSumDiff(self, nums1: List[int], nums2: List[int]) -> int:
        if nums1 == nums2: return 0
        res = [abs(a-b) for a,b in zip(nums1, nums2)]
        idx = res.index(max(res))
        tmp = [abs(i-nums2[idx]) for i in nums1]
        return (sum(res) - max(res) + min(tmp)) % (10**9 + 7)
```

#### Language used for code
python

#### Expected behavior

![image](https://user-images.githubusercontent.com/10625136/113512013-b73b0780-9530-11eb-8397-38b65f518575.png)
![image](https://user-images.githubusercontent.com/10625136/113512016-c15d0600-9530-11eb-808e-0d27dbe90a5f.png)

**Comment by lc-kay** [comment]
Hi @cloverpku 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @cloverpku 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
