### ISSUE TITLE
No submission was happening at IST 4:26 am 10 March 2020

### ISSUE THREAD

**Issue by Lav12122** [LeetCode-Feedback/LeetCode-Feedback#30]
![Screenshot from 2020-03-10 04-25-32](https://user-images.githubusercontent.com/61917214/76264298-643c4580-6287-11ea-9240-003a1e841d29.png)
**What kind of the bug**
Compiler not working at all - Refer screenshot

**Describe the bug**
Submission was not working at all. Displaying time out error. 
The same code which was submitted earlier was not able to be submitted.

**The code you submit/run**
```
class Solution:
    def twoSum(self, nums: List[int], target: int) -> List[int]:
        for i, num1 in enumerate(nums):
            for j, num2 in enumerate(nums[i+1:]):
                if (num1 + num2) == target:
                    return [i, i+1+j]
        
```

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by pgupta6** [comment]
Same here 
<img width="1680" alt="Screen Shot 2020-03-09 at 4 14 24 PM" src="https://user-images.githubusercontent.com/7296247/76265174-15f45b80-6221-11ea-822a-7730d6462bb9.png">

**Comment by CooperCooperCooper** [comment]
Hi @Lav12122 and @pgupta6,

Thank you for your time. Our engineers have been alerted for this issue and have fixed it just now. We've tested and confirmed that "Run Code" and "Submit" are running normally now.

We appreciate your support and understanding.
