### ISSUE TITLE
Not getting Details regarding the failed test case

### ISSUE THREAD

**Issue by pritesh-chauhan** [LeetCode-Feedback/LeetCode-Feedback#300]
Problem 507

Below is the issue I am facing submitting the solution.
If I try to submit the solution then sometimes it fails at test case number 56 or 57 and if that particular input is given as the custom test case then it is accepted. After this, if I try to submit the solution both 56 and 57 test cases are passed but it fails at 156 test case number for which I am not getting any details why it is failing.

![ProblemNumber507](https://user-images.githubusercontent.com/54586794/81610566-bf81d580-93a7-11ea-876c-467d222ac184.JPG)

**Comment by CooperCooperCooper** [comment]
Hi @
Thank you for reaching out to us. Please share the mentioned code in the format mentioned in this [post](https://github.com/LeetCode-Feedback/LeetCode-Feedback/blob/master/.github/ISSUE_TEMPLATE/bug-report--english-.md). It will help us pin-point the issue quickly.

**Comment by CooperCooperCooper** [comment]
Hi @pritesh-chauhan ,

Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
