### ISSUE TITLE
Missing Test Case - 88. Merge Sorted Array

### ISSUE THREAD

**Issue by gflarity** [LeetCode-Feedback/LeetCode-Feedback#3004]
#### Your LeetCode username
flarity

#### Category of the bug
- [*] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
I'm pretty sure the Golang version of this problem isn't solvable since it's impossible to change the slices passed in a way that is viewable from the calling functions.  Slices aren't arrays, they're more like vectors underhood. This isn't really a golang friendly question, but the best way to do is probably to pass in slice pointers instead. 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@gflarity For your reference, please check out all these Golang submissions. https://leetcode.com/problems/merge-sorted-array/discuss/?currentPage=1&orderBy=most_relevant&query=golang Thank you for your time.
