### ISSUE TITLE
Typo in 468. Validate IP Address

### ISSUE THREAD

**Issue by Vadim-Pelyushenko** [LeetCode-Feedback/LeetCode-Feedback#3005]
#### Your LeetCode username

vpelyush

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

In the description where it says 
'A valid IPv6 address is an IP in the form "x1:x2:x3:x4:x5:x6:x7:x8" where:...'
the colon following x4 is part of the subscript, in contrast to the other colons.

#### Code you used for Submit/Run operation

N/A

#### Language used for code

N/A

#### Expected behavior

The colon following x4 shouldn't be in a subscript.

#### Screenshots

![image](https://user-images.githubusercontent.com/37136767/113526322-7d88f180-956e-11eb-987b-4c654749365b.png)

The corresponding HTML
![image](https://user-images.githubusercontent.com/37136767/113526354-9a252980-956e-11eb-9fab-8ce386a69ad6.png)

**Comment by lc-kay** [comment]
Hi @Vadim-Pelyushenko 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Vadim-Pelyushenko 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
