### ISSUE TITLE
Missing Test Case - 477. Total Hamming Distance

### ISSUE THREAD

**Issue by introidx** [LeetCode-Feedback/LeetCode-Feedback#3008]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
Missing test case 
input [2,4,6]
the output should be: 8 
but it returns: 4

#### Code you used for Submit/Run operation
````
public class Solution {
    public int totalHammingDistance(int[] nums) {
        int n = 31;
        int len = nums.length;
        int[] countOfOnes = new int[n];
        for (int i = 0; i < len; i++) {
            for (int j = 0; j < n; j++) {
                countOfOnes[j] += (nums[i] >> j) & 1;
            }
        }
        int sum = 0;
        for (int count: countOfOnes) {
            sum += count * (len - count);
        }
        return sum;
    }
}
````

```

```

#### Language used for code
JAVA

**Comment by lc-kay** [comment]
@introidx For a valid contribution, the missing test case must fail on the code provided. I tested the code and your custom test case and it was accepted. Please provide a code that this test case will fail on. Then, I will reopen this issue. Thank you for understanding.
