### ISSUE TITLE
same code is giving two different answers

### ISSUE THREAD

**Issue by AmanKumarMehra** [LeetCode-Feedback/LeetCode-Feedback#3016]
W
![Screenshot (331)](https://user-images.githubusercontent.com/77455854/113655779-137c6380-96b8-11eb-8718-1f22d62fa29a.png)

word Break Problem from dp

class Solution {
    public boolean wordBreak(String s, List<String> wordDict) {
        
        boolean value =  solution(s, wordDict, s.length());
        return value;
    }
    
    static int count = 0;
	static String ros = "1";
	private static boolean solution(String str, List<String> lst, int length) {
	
		for(int i=0; i<str.length(); i++) {
			count++;
			String prefix = str.substring(0, i+1);
			if(lst.contains(prefix)) {
				ros = str.substring(i+1);
				solution(ros, lst, length);
			}
			 
			 if(count == length && ros.length() != 0) {
					return false;
			}
			 if(ros.length() == 0) {
					return true;
			}
		}
		
		return false;
	}
}

**Comment by lc-kay** [comment]
Hi @AmanKumarMehra 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
