### ISSUE TITLE
time limit exceeded issue for the given solution- 189. Rotate Array

### ISSUE THREAD

**Issue by SnehitaAmara** [LeetCode-Feedback/LeetCode-Feedback#3017]
#### Your LeetCode username
 190030059 

#### Category of the bug
- [x] Solution

#### Description of the bug
Getting a time limit exceeded issue for the provided solution in the problem 

#### Code you used for Submit/Run operation
```
// Two Sum
class Solution:
    def rotate(self, nums: List[int], k: int) -> None:
        k %= len(nums)
        for i in range(k):
            previous = nums[-1]
            for j in range(len(nums)):
                nums[j], previous = previous, nums[j]
```
#### Language used for code
python 3

#### Expected behavior
I looked up the solution given for the problem and executed it and got a error - time limit exceeded.

#### Screenshots
![image](https://user-images.githubusercontent.com/74001730/113661390-9c4ccc80-96c3-11eb-81ce-60959fc81781.png)

**Comment by lc-kay** [comment]
Hi @SnehitaAmara 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@SnehitaAmara This solution is supposed to fail because it is the Brute Force approach. For clarification, we have increased the constraints. Thank you for your time.
