### ISSUE TITLE
My code is wrong, yet passing all test cases and getting submitted

### ISSUE THREAD

**Issue by MrCasco** [LeetCode-Feedback/LeetCode-Feedback#3019]
#### Your LeetCode username

mr_casco

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

My serialize code is wrong and it should not work with all test cases, and also my deserialize function does nothing but returning the only argument that is receiving. Which clearly shouldn't work either, yet I'm getting them accepted

#### Code you used for Submit/Run operation

```
# Serialize / deserialize tree
def serialize(self, root):
    queue = [root]
    if not root: return []
    res = []
    while queue:
        node = queue.pop(0)
        if node:
            res.append(node.val)
            for child in [node.left, node.right]:
                queue.append(child)
        else:
            res.append(None)
    while res[-1] == None:
        res.pop()
    return res

def deserialize(self, data):
    return data
```

#### Language used for code

Python3

#### Expected behavior

A fail when submiting my code under the following test case: [1, 2, 3, 4, 5, null, null]

#### Screenshots

![imagen](https://user-images.githubusercontent.com/25269763/113750160-108d6d00-96d0-11eb-82bb-f7a0f234e659.png)

**Comment by lc-kay** [comment]
@MrCasco Please provide the submission details link to your accepted code. Thank you!

**Comment by lc-kay** [comment]
Hi @MrCasco 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
