### ISSUE TITLE
Diameter of Binary Tree 測資解答錯誤

### ISSUE THREAD

**Issue by TaroFIN** [LeetCode-Feedback/LeetCode-Feedback#302]
** Bug 类型**
- [ ] 题目
- [x] 题解
- [ ] 编程语言

**描述**
描述你遇到的 bug
Diameter of Binary Tree 測資解答錯誤
**你使用的语言**
C#

**你提交或者运行的代码**
```
// Diameter of Binary Tree
public class Solution {
    public int DiameterOfBinaryTree(TreeNode root) {
        if(root==null) return 0;
        else return Diameter(root.left, 0) + Diameter(root.right, 0);
    }
    
    public int Diameter(TreeNode root, int Dia)
    {
        if(root==null) return Dia;
        else
        {
            Dia++;
            return Math.Max(Diameter(root.left,Dia),Diameter(root.right,Dia));
        }
    }
}
```

**期望行为**
描述你期望的结果
Your input
[4,-7,-3,null,null,-9,-3,9,-7,-4,null,6,null,-6,-6,null,null,0,6,5,null,9,null,null,-1,-4,null,null,null,-2]
Output
7
Expected
8
**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
題目要求總和左右兩節點之總長度，畫圖後怎麼計算皆是7，不知道8這個數字怎麼來的?

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认的～

**Comment by feiceh** [comment]
你好，力扣平台没有问题的。注意直径不需要经过根结点。后续刷题学习中遇到困难，可通过阅读「题解」解决做题中的一些困惑，看看其他小伙伴的解题思路哦。
