### ISSUE TITLE
Missing Test Case - 338. Counting Bits

### ISSUE THREAD

**Issue by 08komal** [LeetCode-Feedback/LeetCode-Feedback#3020]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@08komal Please provide the missing test case you wish to report and the code it fails on. I will reopen this issue when there is more information. Thank you for understanding.
