### ISSUE TITLE
Test Case - 567. Permutation in String

### ISSUE THREAD

**Issue by cheryl-c** [LeetCode-Feedback/LeetCode-Feedback#3021]
#### Your LeetCode username
cheryl-c

#### Category of the bug
- [ ] Question
- [ x] Solution
- [ ] Language

#### Description of the bug

<img width="358" alt="image" src="https://user-images.githubusercontent.com/52729900/113834054-f54c5b80-97bc-11eb-86c7-3dd912c09fe8.png">
the test case here says 
Input: "ab" "eidboaoo"
Output: true
Expected: false

However, actual test case used inside of LeetCode is:
Input: "ab" "eidbaooo"

Which is why my output = true, as 'ba' are side by side in "eidbaooo".

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code
python

**Comment by lc-kay** [comment]
@cheryl-c These two are different test cases. Per the example, the input s1 = "ab" s2 = "eidbaooo" output True. Whereas, Input:s1= "ab" s2 = "eidboaoo" output: False. For your code to get accepted, it must pass all the test cases. I hope this clarifies your doubts and concerns.
