### ISSUE TITLE
Missing Test Case - 20. Valid Parentheses

### ISSUE THREAD

**Issue by yashgandhi876** [LeetCode-Feedback/LeetCode-Feedback#3022]
#### Your LeetCode username
yashgandhi876

#### Category of the bug
- [ Python] Language

#### Description of the bug

Wrong output generated in your online IDE while solving a problem for a specific condition i.e. "(]"
I have tried the same condition in VS Code and that showing me the correct output.

#### Code you used for Submit/Run operation
```
class Solution:
    def isValid(self, s):
        arr = []
        flag = True
        for i in range(len(s)):
            if(s[i] in ['[','{','(']):
                arr.append(s[i])
            elif(s[i] == ']'):
                if(arr[-1] == '['):
                    arr.pop(-1)
                else:
                    flag = False
                    break
            elif(s[i] == '}'):
                if(arr[-1] == '{'):
                    arr.pop(-1)
                else:
                    flag = False
                    break
            elif(s[i] == ')'):
                if(arr[-1] == '('):
                    arr.pop(-1)
                else:
                    flag = False
                    break

        if(flag and len(arr) == 0):
            return "true"
        else:
            return "false"

```

#### Language used for code
Python

#### Expected behavior

Wrong output generated in your online IDE while solving problem for specific condition i.e. "(]"
I have tried the same condition in VS Code and that showing me the correct output.

#### Screenshots

![image](https://user-images.githubusercontent.com/51225584/113851220-e82d6d80-97b8-11eb-827a-2c0d72ac2717.png)
![image](https://user-images.githubusercontent.com/51225584/113851240-eebbe500-97b8-11eb-83d8-bbd93910f49c.png)

**Comment by lc-kay** [comment]
@yashgandhi876 Our judge is correct, I was able to find a similar issue reported by another user in the discuss section. https://leetcode.com/problems/valid-parentheses/discuss/450862/test-case%22(-%22will-failed-but-I-can-get-the-right-result-on-my-jupyter-notebook(python) Please check it out. Thank you for your time.
