### ISSUE TITLE
Missing Test Case - 1464. Maximum Product of Two Elements in an Array

### ISSUE THREAD

**Issue by davida5** [LeetCode-Feedback/LeetCode-Feedback#3024]
Need a test case with negative numbers larger than positive i.e. [1,2,-6,-5].
Because current test cases only cover positive values, which makes below code work, while it's incorrect

#### Your LeetCode username
codeMonkey55

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
 fun maxProduct(nums: IntArray): Int {
       if(nums.size<2){
           return 0
       }
      
       nums.sortDescending()
       return (nums[0]-1)*(nums[1]-1)
   }
```

**Comment by lc-kay** [comment]
@davida5 Please provide the code that this test case will fail on. Thank you!

**Comment by davida5** [comment]
Below code that I submitted passes all testcases, but it's incorrect, so I'm suggesting to add some test cases with negative numbers.

 ```
  fun maxProduct(nums: IntArray): Int {
        if(nums.size<2){
            return 0
        }
       
        nums.sortDescending()
        return (nums[0]-1)*(nums[1]-1)
    }
```

**Comment by lc-kay** [comment]
@davida5 As negative numbers are not within the constraints, we will not be adding this test case. 'nums' must consist of values from 1 to 1000 only. Thank you for your time.
