### ISSUE TITLE
Missing test case: 277. Find the Celebrity

### ISSUE THREAD

**Issue by Leo-ATP** [LeetCode-Feedback/LeetCode-Feedback#3025]
#### Your LeetCode username
Axone_Wu

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Need a test case with one totally separated person.
A & B know C,
No one kowns D, and D kowns no one.

[[1,0,1,0],[0,1,1,0],[0,0,1,0],[0,0,0,1]]

#### Code you used for Submit/Run operation
```
// This is the fastest accepted C++ solution**
class Solution {
public:
    int findCelebrity(int n) {
        int next=0;
        for(int i=1;i<n;i++) {
            if(knows(next, i))
                next=i;
        }
        
        if(next==0) {
            for(int i=1;i<n;i++) {
                if(!knows(i, next))
                    return -1;
            }
          }
        else {
            for(int i=0;i<n && i!=next;i++)     //here is the problem:  i<n && i!=next    <=>.  i<next
                                                                   // we should use:  for(int i=0;i<n; i++){
                                                                   // and add                     if(i == next) continue;
                if(knows(next, i))
                    return -1;
                else if(!knows(i, next))
                    return -1;
            }
            
        }
        
        return next;
    }
};
```

#### Language used for code
 C++

#### Expected behavior
Pass Submit, **but failed with the test case above**

**Comment by lc-kay** [comment]
@Leo-ATP Please provide the submission details link to your code. Thank you!

**Comment by lc-kay** [comment]
Hi @Leo-ATP 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
