### ISSUE TITLE
Python3 default type annotation is wrong for 725. Split Linked List in Parts

### ISSUE THREAD

**Issue by b05902132** [LeetCode-Feedback/LeetCode-Feedback#3026]
#### Your LeetCode username

linlin110

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language

#### Description of the bug

The default type annotation is:
```Python
class Solution:
    def splitListToParts(self, root: ListNode, k: int) -> List[ListNode]:
```
However the returned list may contain `None`, so the correct type annotation should be
```Python
class Solution:
    def splitListToParts(self, root: ListNode, k: int) -> List[Optional[ListNode]]:
```

**Comment by lc-kay** [comment]
Hi @b05902132 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@b05902132 Thank you for reporting this issue to us previously! We greatly appreciate your patience as we investigated and implemented a fix. Happy LeetCoding!
