### ISSUE TITLE
Missing Test Case: 1053. Previous Permutation With One Swap

### ISSUE THREAD

**Issue by l0latgithub** [LeetCode-Feedback/LeetCode-Feedback#3027]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Miss a test case to for duplicated items
[1,9,4,4,6,7]

#### Code you used for Submit/Run operation

```
class Solution:
    def prevPermOpt1(self, arr: List[int]) -> List[int]:
        
        arrlen = len(arr)
        left = arrlen-1
        while left>0 and arr[left]>=arr[left-1]:
            left-=1
        
        if left==0:
            return arr
        
        start = left
        # On the right of start position, it is a non-descending list
        while start<arrlen-1 and arr[start]<arr[start+1] and arr[start+1]<arr[left-1]:
            start+=1
        
        arr[left-1],arr[start]=arr[start],arr[left-1]
        return arr
```

#### Language used for code

Python

#### Expected behavior

The code above passed submit, although failed test case I provided.
Your input: [1,9,4,4,6,7]
Output:      [1,4,9,4,6,7]
Expected:   [1,7,4,4,6,9]

**Comment by lc-kay** [comment]
Hi @l0latgithub 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @l0latgithub 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!
