### ISSUE TITLE
Missing Test Case - 929. Unique Email Addresses

### ISSUE THREAD

**Issue by BellaRocha** [LeetCode-Feedback/LeetCode-Feedback#3028]
#### Your LeetCode username

isabellarochailr

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language

#### Description of the bug

the following test cases say it should have the output of (2) but it should actually have the output of (10)
["fg.r.u.uzj+o.pw@kziczvh.com","r.cyo.g+d.h+b.ja@tgsg.z.com","fg.r.u.uzj+o.f.d@kziczvh.com","r.cyo.g+ng.r.iq@tgsg.z.com","fg.r.u.uzj+lp.k@kziczvh.com","r.cyo.g+n.h.e+n.g@tgsg.z.com","fg.r.u.uzj+k+p.j@kziczvh.com","fg.r.u.uzj+w.y+b@kziczvh.com","r.cyo.g+x+d.c+f.t@tgsg.z.com","r.cyo.g+x+t.y.l.i@tgsg.z.com","r.cyo.g+brxxi@tgsg.z.com","r.cyo.g+z+dr.k.u@tgsg.z.com","r.cyo.g+d+l.c.n+g@tgsg.z.com","fg.r.u.uzj+vq.o@kziczvh.com","fg.r.u.uzj+uzq@kziczvh.com","fg.r.u.uzj+mvz@kziczvh.com","fg.r.u.uzj+taj@kziczvh.com","fg.r.u.uzj+fek@kziczvh.com"]

#### Code you used for Submit/Run operation

```
class Solution:
    def numUniqueEmails(self, emails: List[str]) -> int:
        receives_emails = 0
        if len(emails) > 100 or len(emails) < 1:
            return 0
        for i in range(len(emails)):
            if len(emails[i]) > 100 or len(emails[i]) < 1: 
                return 0
            email_s = emails[i].split('@')
            local = email_s[0]
            domain = email_s[1]
            if (domain.count('.') == 1) and ('+' not in domain) and (local[0] != '+'):
                receives_emails += 1
        return receives_emails
};
```

#### Language used for code

python3

#### Expected behavior

There should have been the output of (10) instead of (2)

#### Screenshots

<img width="923" alt="Screen Shot 2021-04-07 at 3 37 14 PM" src="https://user-images.githubusercontent.com/44777806/113923919-22960b00-97b7-11eb-9474-dad02cbfccaf.png">

#### Additional context

There also seems to have a bug in the first explanation of the problem. It says that the correct emails would be:
"testemail@leetcode.com" and "testemail@lee.tcode.com"
Here's what's wrong with it. Firstly, the first email isn't even an input to the example and secondly the second one should not have been a correct email since it has more than one '.' in the domain. The first bulleted example states that there should not be more than one '.' in the domain.

**Comment by lc-kay** [comment]
@BellaRocha The expected output is correct. Please check out these Python3 solutions as a reference. Thank you for your time.
