### ISSUE TITLE
Missing Test Case - 1818. Minimum Absolute Sum Difference

### ISSUE THREAD

**Issue by silvertint** [LeetCode-Feedback/LeetCode-Feedback#3029]
#### Your LeetCode username

Jason_Tint

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language

#### Description of the bug

In the contest of Weekly Contest 235, the test cases of the 3rd questions "Minimum Absolute Sum Difference" are incomplete. As a result, some wrong submissions were accepted in the contest.

Please consider the following two test cases: 
nums1 = [27,7,1,4] 
nums2 = [20,1,2,3] 
or 
nums1=[13,14,11] 
nums2=[4,6,12]

#### Code you used for Submit/Run operation

```
// Minimum Absolute Sum Difference
class Solution:
    def minAbsoluteSumDiff(self, nums1: List[int], nums2: List[int]) -> int:
        mod = 10 ** 9 + 7
        n = len(nums1)
        D = [abs(a - b) for a, b in zip(nums1, nums2)]
        maxv = max(D)
        idx = D.index(maxv)
        cur = 0
        for a in nums1:
            cur = max(cur, maxv - abs(a - nums2[idx]))
        return (sum(D) - cur) % mod
```

For your convenience, you can also check the code in the following link.
https://paste.ubuntu.com/p/52DHKWPqyY/

#### Language used for code

Python3

#### Expected behavior

Since the test cases are incomplete, some wrong submissions which return incorrect answers were also accepted during the contest.

For the fairness of this contest, could you please consider and add the above two test cases and re-test all the AC submissions in the contest of that question?

Thank you so much!

**Comment by lc-kay** [comment]
@silvertint Since you code you submitted already receives Wrong Answer due to recently added test cases, we will not add the test case you contributed. Thank you for understanding.
