### ISSUE TITLE
997. Find the Town Judge

### ISSUE THREAD

**Issue by Jun711** [LeetCode-Feedback/LeetCode-Feedback#303]
**What kind of the bug**
- [X] problem
- [X] solution
- [ ] language

**Describe the bug**
The problem description says that 
```
The town judge trusts nobody.
```
And, there is a note at the bottom saying that
```
trust[i][0] != trust[i][1]
```

What should the result be if the test case contain `trust[i][0] == trust[i][1]`? 
Shouldn't the result be -1 according to the description? 
This test case setup based on note: `trust[i][0] != trust[i][1]` seems to reduce the purpose of the first condition `The town judge trusts nobody.`

**Expected behavior**
I expect the result to be -1 when there is [judgeNum, judgeNum] in the trust array

**Comment by CooperCooperCooper** [comment]
Hi @Jun711 ,
Thank you for your time. Constraints and statement limit the scope of the problem (on this case the input), having said that ¨¨¨¨[judgeNum, judgeNum]¨¨¨¨¨ is an invalid test case.
