### ISSUE TITLE
Wrong numbers in UI

### ISSUE THREAD

**Issue by RakhmedovRS** [LeetCode-Feedback/LeetCode-Feedback#3030]
#### Your LeetCode username
rakhmedovrs

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
I've noticed strange numbers in the UI, see screenshots for more information.

#### Expected behavior
As you can see from pictures, UI shows 113% of progress whereas it should 100%. Also challenge hasn't marked as finished. As another axample I attached picture of January challenge with normal 100%

#### Screenshots

![image](https://user-images.githubusercontent.com/25452084/113947490-9fc57e00-97bf-11eb-8434-d0910b1eb502.png)

![image](https://user-images.githubusercontent.com/25452084/113947500-a522c880-97bf-11eb-911b-e917897c23b8.png)

![image](https://user-images.githubusercontent.com/25452084/113947506-a8b64f80-97bf-11eb-9d33-83b538b322aa.png)

**Comment by lc-kay** [comment]
@RakhmedovRS I've relayed this to our team to investigate. However, please keep in mind that our GitHub feedback is for content-related issues. Thank you again for your support and understanding.

**Comment by RakhmedovRS** [comment]
@lc-kay Sure, I'll keep in in mind for future requests.
