### ISSUE TITLE
Missing Test Case - 775. Global and Local Inversions

### ISSUE THREAD

**Issue by alphasingh** [LeetCode-Feedback/LeetCode-Feedback#3031]
#### Your LeetCode username
alphasingh

#### Category of the bug
- [x] Solution

#### Description of the bug
If we iterate through the array and keep counting `A[i]>A[i+1]`, we get local inversions, and for global inversions to be not equal to this, we will only need one inequality while traversing, by looking at `max(0, A[i]-i)` for each `i` which basically gives us the least number of smaller values at the right of each element. If we keep the whole array the same, just swap the last element with the third last, i.e. A[i-2]>A[i] creating an extra global inversion, the below code is still able to pass through existing test cases, which should not happen

#### Code you used for Submit/Run operation
```
class Solution:

    @staticmethod
    def isIdealPermutation(A: [int]) -> bool:
        local_inversions = global_inversions = 0
        size = len(A)
        if size <= 5:
            return Solution.isIdealPermutation_brute(A)
        for i in range(size - 1):
            if A[i] > A[i + 1]:
                local_inversions += 1
        for i in range(size):
            global_inversions += max(0, A[i] - i)
        return local_inversions == global_inversions

    @staticmethod
    def isIdealPermutation_brute(A: [int]) -> bool:
        local_inversions = global_inversions = 0
        size = len(A)
        for i in range(size):
            for j in range(i + 1, size):
                if A[i] > A[j]:
                    global_inversions += 1
        for i in range(size - 1):
            if A[i] > A[i + 1]:
                local_inversions += 1
        return local_inversions == global_inversions
```

#### Language used for code
python3

#### Expected behavior
For both brute force and optimized approach, the result should be the same

#### Additional context
some examples which fail the above code:
```
example_size_6 = [0, 1, 2, 5, 4, 3]
example_size_10 = [0, 1, 2, 3, 4, 5, 6, 9, 8, 7]
assert Solution.isIdealPermutation(A=example_size_6) == Solution.isIdealPermutation_brute(A=example_size_6)
assert Solution.isIdealPermutation(A=example_size_10) == Solution.isIdealPermutation_brute(A=example_size_10)
```
Both of the above small assertions fail, meaning the test cases can be improved, even for larger cases, the test case is easy to create by just swapping the last element with the third last element, i.e. A[i] with A[i-2]

**Comment by lc-kay** [comment]
Hi @alphasingh 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @alphasingh 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
