### ISSUE TITLE
153. 寻找旋转排序数组中的最小值 翻译问题

### ISSUE THREAD

**Issue by x-hw** [LeetCode-Feedback/LeetCode-Feedback#3032]
**你的 LeetCode 用户名**
x.hw

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
[题目](https://leetcode-cn.com/problems/find-minimum-in-rotated-sorted-array/)中的”若旋转 4 次，则可以得到 [0,1,2,4,5,6,7]“，原文为”[0,1,2,4,5,6,7] if it was rotated 7 times.“。

**期望行为**
应该是”若旋转 7 次，则可以得到 [0,1,2,4,5,6,7]“

**屏幕截图**

中文翻译：
<img width="427" alt="原文" src="https://user-images.githubusercontent.com/21075976/113965514-1b770780-9860-11eb-9abd-54c1861277b9.png">

原文：
<img width="450" alt="中文翻译" src="https://user-images.githubusercontent.com/21075976/113965596-3b0e3000-9860-11eb-96ff-698b2623e406.png">

**Comment by PsiACE** [comment]
非常感谢您的反馈，目前该问题已经修正。感谢您对力扣的支持。
