### ISSUE TITLE
Missing Test Case - 410. Split Array Largest Sum

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#3036]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

A solution is accepted but fails on the following test case:

[0]
1

#### Code you used for Submit/Run operation

```
public class Solution {
    
    boolean isPossible(long sum, int slots, int[] a) {
        int i = 0;
        while (i != a.length && slots-- != 0) {
            long total = 0;
            while (i != a.length && total + a[i] <= sum) {
                total += a[i];
                i++;
            }
        }
        return i == a.length;
    }
    
    public int splitArray(int[] nums, int m) {
        long left = 0;
        long right = 1L * nums.length * Integer.MAX_VALUE;
        while (right - left > 1) {
            long mid = left + right >> 1;
            if (isPossible(mid, m, nums)) right = mid;
            else left = mid;
        }
        return (int)right;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/114114616-36249d00-98af-11eb-99c3-e66bc3855515.png)

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
