### ISSUE TITLE
Missing Test Case- 605. Can Place Flowers

### ISSUE THREAD

**Issue by NITIN23329** [LeetCode-Feedback/LeetCode-Feedback#3037]
#### Your LeetCode username
nitin23329

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
I found a test case where my code gives the wrong answer when I ran it  but got accepted upon submission.
flowerbeds[] = [1,1,0], n = 1. 
The output should be 0, but my code gave 1 and got accepted.

#### Code you used for Submit/Run operation

```
class Solution {
   public boolean canPlaceFlowers(int[] flowerbed, int n) {
       return helper(flowerbed,0,flowerbed.length) >=n;
    }
    private int helper(int[] flower,int i,int m){
        if(i>=m)return 0;
        if(flower[i]==1)return helper(flower,i+2,m);
        int count = 0;
        if(i==m-1 || flower[i+1]!=1)
            count  = 1 + helper(flower,i+2,m);
        else count = helper(flower,i+1,m);
        return count;
    }
}
```

#### Language used for code
Java

#### Expected behavior
For input:
flowerbeds[] = [1,1,0]
 n = 1. 
Expected output : 0
Actual output : 1
The output should be 0, but my code gave 1 and got accepted.

#### Screenshots

<img width="304" alt="Screenshot 2021-04-09 at 14 14 38" src="https://user-images.githubusercontent.com/55681638/114154504-1be5d000-993e-11eb-9401-1507a2b8c814.png">

<img width="748" alt="Screenshot 2021-04-09 at 14 14 54" src="https://user-images.githubusercontent.com/55681638/114154531-22744780-993e-11eb-92c6-a28a8ea2d1f0.png">

#### Additional context
problem link : https://leetcode.com/problems/can-place-flowers/

**Comment by lc-kay** [comment]
Hi @NITIN23329 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @NITIN23329 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
