### ISSUE TITLE
Missing Test Case - 410. Split Array Largest Sum

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#3038]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

A solution is accepted but fails on the following test case:

[0, 8, 1, 4]
4

#### Code you used for Submit/Run operation

```
public class Solution {
    public int splitArray(int[] nums, int m) {
        if(nums.length==0) return 0;
        int[] dp = new int[nums.length],dpn;
        int max = nums[0];
        dp[0] = nums[0];
        for(int i = 1;i<nums.length;i++){
            dp[i] = dp[i-1]+nums[i];
            max = Math.max(max,nums[i]);
        }
        if(max == Integer.MAX_VALUE) return max;
        for(int j = 1;j<m;j++){
            dpn = new int[nums.length];
            for(int i = j;i<nums.length;i++){
                int curr = nums[i], k = i-1;
                while(k>=0&&curr<dp[k]) curr+=nums[k--];
                dpn[i] = Math.min(curr,dp[k+1]);
            }
            dp = dpn;
        }
        return dp[nums.length-1];
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/114160523-05675680-98f5-11eb-99d9-288e26ccc64e.png)

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
