### ISSUE TITLE
Missing Test Case - 775. Global and Local Inversions

### ISSUE THREAD

**Issue by Yougigun** [LeetCode-Feedback/LeetCode-Feedback#3039]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The  wrong instrument to describe local inversion
0 < i < n - 1                       ->    0<= i <n-1
nums[i] < nums[i + 1]       ->    nums[i] > nums[i + 1]

**Comment by lc-kay** [comment]
Hi @Yougigun 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@Yougigun Our team has reviewed your report and noted that both issues were fixed before we received your ticket. Thank you for your time.
