### ISSUE TITLE
334. https://leetcode.com/problems/increasing-triplet-subsequence/

### ISSUE THREAD

**Issue by mohasivakumar** [LeetCode-Feedback/LeetCode-Feedback#304]
**Describe the bug**

**what language is your code written in**
Kotlin

**The code you submit/run**
```
class Solution {
    fun increasingTriplet(nums: IntArray): Boolean {
        var element : Array<Int> = Array(2) { Integer.MAX_VALUE }
        for (i in 0..nums.size-1) {
            if (nums[i] >= 0) {
                if (nums[i] > element[1]) { return true}
                if (nums[i] < element[0]) { 
                    element[0] = nums[i]
                } else if (nums[i] > element[0] && nums[i] < element[1]) {
                    element[1] = nums[i]
                }
            }
        }
        return false
    }
}
```

**Expected behavior**
For test case [1,2,-10,-8,-7] it should fail as per problem description
Given an unsorted array return whether an increasing subsequence of length 3 exists or not in the array.

Formally the function should:

Return true if there exists i, j, k
such that arr[i] < arr[j] < arr[k] given **0 ≤ i < j < k ≤ n-1** else return false.

**Comment by CooperCooperCooper** [comment]
Hi @mohasivakumar ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @mohasivakumar ,
Thank you for your time. Upon reviewing your submission, we found it returns true since -10,-8,-7 is a valid triplet. We appreciate your support.

**Comment by mohasivakumar** [comment]
But the problem description said lower bound of triplet is 0
