### ISSUE TITLE
Python Solution Don't run, But Same Java Solution run. - 132. Palindrome Partitioning II

### ISSUE THREAD

**Issue by Ragav-Subramanian** [LeetCode-Feedback/LeetCode-Feedback#3040]
#### Your LeetCode username

Ragav_1302

#### Category of the bug
- [ ] Question
- [ tick] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

My Python Solution is not getting tle, whereas same solution in Java getting accepted.

#### Code you used for Submit/Run operation

//Java Solution

**
class Solution {
    public boolean isPalindrome(String s, int i, int j) {
        while (i < j) {
            if (s.charAt(i++) != s.charAt(j--)) {
                return false;
            }
        }
        return true;
    }
    
    public int minCut(String s) {
        if (isPalindrome(s, 0, s.length()-1)) return 0;
        return dfs(s, 0);
    }
    
    HashMap<Integer, Integer> memo = new HashMap<>();
    public int dfs(String s, int idx) {
        if (idx >= s.length() || isPalindrome(s, idx, s.length()-1)) {
            return 0;
        }
        if (memo.containsKey(idx)) {
            return memo.get(idx);
        }
        
        int result = Integer.MAX_VALUE;
        for (int i = idx+1; i <= s.length(); i++) {
            if (i != s.length() && isPalindrome(s, idx, i-1)) {
                result = Math.min(result, 1 + dfs(s, i));
            }
        }
        result = (result == Integer.MAX_VALUE)? 0 : result;
        memo.put(idx, result);
        return result;
    }
}**
//Python solution
**class Solution:
    def minCut(self, s: str) -> int:
        if self.isp(s,0,len(s)-1):
            return 0
        self.d={}
        return self.dfs(s,0)
    def dfs(self,s,ind):
        if ind>=len(s) or self.isp(s,ind,len(s)-1):
            return 0
        if ind in self.d:
            return self.d[ind]
        ans=float("inf")
        for i in range(ind+1,len(s)+1):
            if i!=len(s) and self.isp(s,ind,i-1):
                ans=min(ans,1+self.dfs(s,i))
        ans = ans if ans!=float('inf') else 0
        self.d[ind]=ans
        return ans
    def isp(self,s,i,l):
        while i<l:
            if s[i]!=s[l]:
                return False
            i+=1
            l-=1
        return True**

#### Language used for code

Python,Java

#### Expected behavior

Expected Behaviour - Getting Accepted in Python.
Actually Happened - Not Getting Accepted in Python an d getting accepted in Java.

#### Additional context

[https://leetcode.com/problems/palindrome-partitioning-ii/discuss/971894/Python-Experts-Help-me-improve-runtime.](url)

**Comment by lc-kay** [comment]
@Ragav-Subramanian To assist you with this issue, I'd recommend checking out the problem discuss section and the accepted Python submissions https://leetcode.com/problems/palindrome-partitioning-ii/discuss/?currentPage=1&orderBy=most_relevant&query=python. Thank you for your time.
