### ISSUE TITLE
Wrong description - 775. Global and Local Inversions

### ISSUE THREAD

**Issue by WeixiangLiao** [LeetCode-Feedback/LeetCode-Feedback#3042]
I think for this question, the description for the local inversions is wrong now.

I check with some old video about this question, I think the right description for local inversions should be

0 <= i < n - 1
nums[i] > nums[i + 1]

**Comment by lc-kay** [comment]
Duplicate of #3039 
Hi @WeixiangLiao 
Thank you for your time. The team reviewed your report and noticed it was previously reported. Therefore, we will close this ticket. We appreciate your support!
