### ISSUE TITLE
 Typo in 859. Buddy Strings

### ISSUE THREAD

**Issue by navjan13** [LeetCode-Feedback/LeetCode-Feedback#3044]
#### Your LeetCode username
nj13

#### Category of the bug
- [ ] Question

#### Description of the bug
There is a typo in problem "859. Buddy Strings"

such that i != j and swapping the characters at a[i] and b[j]
Should have been:

such that i != j and swapping the characters at a[i] and a[j]

#### Screenshots

![image](https://user-images.githubusercontent.com/1849765/114260612-b18f6700-99f3-11eb-9e45-1cc7555cec62.png)

**Comment by lc-kay** [comment]
Hi @navjan13 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @navjan13 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
