### ISSUE TITLE
题目描述不清：LC263. 丑数

### ISSUE THREAD

**Issue by AnshanSniper** [LeetCode-Feedback/LeetCode-Feedback#3046]
**你的 LeetCode 用户名**
AnshanSniper

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
丑数定义描述不清，应为“只包含质因数2、3和5的正整数”。

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。
