### ISSUE TITLE
Different behaviors for same testcases - 112. Path Sum

### ISSUE THREAD

**Issue by shahzaibqazi** [LeetCode-Feedback/LeetCode-Feedback#3047]
#### Your LeetCode username

shahzaibq094

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A test case passes while provided as a "Custom Testcase", while the same test case fails after submission.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool hasPathSum(TreeNode* root, int targetSum) {
        static int sum = 0;
        int sum_local;
        
        if (root) {
            sum += root->val;
            cout << sum << endl;    // FOR DEBUGGING
            if (!root->left && !root->right) {
                return (sum == targetSum ? true : false);
            }
            bool hasPathSum_l = false, hasPathSum_r = false;
            sum_local = sum;

            hasPathSum_l = root->left ? hasPathSum(root->left, targetSum) : false;
            sum = sum_local;    // resetting static sum value to the local sum of node

            hasPathSum_r = root->right ? hasPathSum(root->right, targetSum) : false;
            sum = sum_local;

            return hasPathSum_l || hasPathSum_r; 
        }
        
        return (sum == targetSum ? true : false);
    }
};
```

#### Language used for code

C++

#### Expected behavior

The testcase was a tree having a single node with 'val=1', given as follows:
[1]
1
While debugging, the value of 'sum' (see code) is somehow printed '8' while it should print '1'.
However, it prints '1' when the same testcase is used as "Custom Testcase".

#### Screenshots

![leetcode_bugreport](https://user-images.githubusercontent.com/20026668/114275518-1f9f5280-9a23-11eb-904e-27b946136d87.PNG)

**Comment by lc-kay** [comment]
Hi @shahzaibqazi 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.

**Comment by shahzaibqazi** [comment]
Hi @lc-kay 
Thank you very much for your help.
