### ISSUE TITLE
Question description is not clear: LC263. Ugly Number

### ISSUE THREAD

**Issue by AnshanSniper** [LeetCode-Feedback/LeetCode-Feedback#3048]
#### Your LeetCode username
AnshanSniper
(You might not find my username, because I am a LeetCode China user.)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The definition of Ugly Number is not well described, it should be "a positive number whose prime factors only include 2, 3 and 5".

**Comment by lc-kay** [comment]
Hi @AnshanSniper 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
