### ISSUE TITLE
Insufficient test cases for "540. Single Element in a Sorted Array" 

### ISSUE THREAD

**Issue by Gokulkkr12** [LeetCode-Feedback/LeetCode-Feedback#305]
**Insufficent Test Case**

**Description**
Tried upon my own testcases to run the code after knowing I missed the logic of a corner case in my algorithm.
Still leetcode accepted the solution.

**Language**
Python 3

**The code you submit/run**
```
class Solution:
    def singleNonDuplicate(self, nums: List[int]) -> int:
        flag=True
        for i in range(0,len(nums)-2,2):
            val=nums[i]+nums[i+1]
            if(val%2==1):
                return nums[i]
        if(flag):
            return nums[-1]

```

**Expected behavior**
Above code runs iteratively with a step of 2 and calculates sum of two elements if the sum
founds to be odd then there will be single element. 
like odd+odd=even
      even+even = even
problem arises when there is **single unique element arrives before or after an even number** then this
code does not work!!
 like see this testcase **[1,1,2,4,4,6,6]** it prints 6 according to logic
1+1=2 even
2+4=6 even
4+6=10 even
6 remains so it prints
so please add this test case if you found this usefull.

**Additional context**
Although the problem clearly states to do the program in O(logN) I tried this as my naive solution before going for the approach of Binary search. 
**Some of test cases which fails
[1,1,2,2,4,6,6]
[2,4,4,5,5,6,6]
[7,7,16,18,18,21,21]**

Hope this helps for you!!

**Comment by CooperCooperCooper** [comment]
Hi @Gokulkkr12 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @Gokulkkr12 ,
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
