### ISSUE TITLE
Missing Test Case - 464. Can I Win

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#3050]
#### Your LeetCode username

igor84

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A solution is accepted but fails on the following test case:

20
189

#### Code you used for Submit/Run operation

```
public class Solution {
	HashMap<Integer, Boolean> canWin=new HashMap<>();
	int n;
    public boolean canIWin(int maxChoosableInteger, int desiredTotal) {
    	n=maxChoosableInteger;
    	if(maxChoosableInteger>=desiredTotal) return true;
    	int sum=0;
    	int bitMap=0;
    	for(int i=0;i<maxChoosableInteger;i++){
    		bitMap|=(1<<i);
    		sum+=i+1;
    	}
    	if(sum<desiredTotal) return false;
    	boolean ret= helper(bitMap, desiredTotal);
    	return ret;
    }
    
    
    boolean helper(int bitMap, int remaining){
    	for(int i=n-1;i>=0;i--){
    		if(((1<<i)&bitMap)==0) continue;
    		if(i+1>=remaining){
    			canWin.put(bitMap, true);
    			return true;
    		}
    	}
    	for(int i=n-1;i>=0;i--){
    		if(((1<<i)&bitMap)==0) continue;
    		bitMap^=(1<<i);
    		if(canWin.containsKey(bitMap)&&canWin.get(bitMap)==false) {
    			bitMap^=(1<<i);
    			canWin.put(bitMap, true);
    			return true;
    		}
    		else if(helper(bitMap, remaining-(i+1))==false) {
    			bitMap^=(1<<i);
    			canWin.put(bitMap, true);
    			return true;
    		}
    		bitMap^=(1<<i);
    	}
    	canWin.put(bitMap, false);
    	return false;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/114280133-ed332c80-9a05-11eb-8c61-468dc90c0998.png)

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
