### ISSUE TITLE
Missing Test Case - 1662. Check If Two String Arrays are Equivalent

### ISSUE THREAD

**Issue by vcmkrtchyan** [LeetCode-Feedback/LeetCode-Feedback#3051]
#### Your LeetCode username
vcmkrtchyan

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
Missing a test case

#### Code you used for Submit/Run operation
```
class Solution {
    public boolean arrayStringsAreEqual(String[] word1, String[] word2) {
        int w1Index = 0;
        int w2Index = 0;
        int t1Index = 0;
        int t2Index = 0;
        
        while(w1Index < word1.length && w2Index < word2.length) {
            String token1 = word1[w1Index];
            String token2 = word2[w2Index];
            
            if(token1.charAt(t1Index++) != token2.charAt(t2Index++)) {
                return false;
            }
            
            if (t1Index == token1.length()) {
                w1Index++;
                t1Index = 0;
            }
            
            if (t2Index == token2.length()) {
                w2Index++;
                t2Index = 0;
            }
        }
        
        return t1Index == 0 && t2Index == 0;
    }
}
```

#### Language used for code
Go

#### Expected behavior
First array = ["a"]
Second array = ["a", "b"]

For the following code, if the second array contains everything from the first array, and one more string, the submit works, although shouldn't, as they are not equal.

**Comment by lc-kay** [comment]
Hi @vcmkrtchyan 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @vcmkrtchyan 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
