### ISSUE TITLE
Missing Test Case - 1825. Finding MK Average

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#3063]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets TLE on the following testcase:
[1825.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6291215/1825.txt)

#### Code you used for Submit/Run operation

```
class MKAverage:

    def __init__(self, m: int, k: int):
        self.elem = []
        self.m = m
        self.k = k

    def addElement(self, num: int) -> None:
        self.elem.append(num)

    def calculateMKAverage(self) -> int:
        if len(self.elem) < self.m:
            return -1
        else:
            n = len(self.elem)
            new_list = self.elem[n-self.m:n]
            new_list.sort()
            new_avg = new_list[self.k:len(new_list)-self.k:]
            return sum(new_avg)//len(new_avg)
```

#### Language used for code

python

#### Expected behavior

The code gets TLE.

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
