### ISSUE TITLE
Missing Test Case - 1824. Minimum Sideway Jumps

### ISSUE THREAD

**Issue by archit11111** [LeetCode-Feedback/LeetCode-Feedback#3065]
#### Your LeetCode username
archit91

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A solution is accepted but fails on the following test case -

```
[0,0,2,0]
```

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int minSideJumps(vector<int>& obs) {
        int pos=2; // starting lane
        int jumps=0, size_obs =obs.size();
        for(int i=0;i<size_obs;i++){
            if(obs[i+1]==pos){ // if there's obstacle at next position
                if(obs[i]!=0){ // if there's obstacle at one of the lane at current index - only one choice exists to jump
                    pos=6-obs[i]-pos;
                }
                else {
                    int dis=2;                    
                    while(i+dis<size_obs && ( obs[i+dis]==0||obs[i+dis]==pos)){dis++;}
                    //2.1 When there is no obstacle until the farthest point
                    if(i+dis==size_obs) {
                        if(pos==1) pos = 2;
                        else pos = 1;
                    }
                    else //2.2 An obstacle was found at some point before end
                    {
                        pos=6-obs[i+dis]-pos;
                    }
                } 
                jumps++;
            }
        }
        return jumps;
    }
};
```

#### Language used for code
C++ 

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/40712852/114294665-bb7d9c80-9abd-11eb-8245-7d501bfb668e.png)

#### Additional context

The solution fails due to improper bound checking.

**Comment by lc-kay** [comment]
Hi @archit11111 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @archit11111 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
