### ISSUE TITLE
Missing Test Case - 1669. Merge In Between Linked Lists

### ISSUE THREAD

**Issue by hyuan** [LeetCode-Feedback/LeetCode-Feedback#3067]
#### Your LeetCode username
user0539P
(Anthony Yuan)

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Incorrect test case expectation.

#### Code you used for Submit/Run operation

```
// Merge In Between Linked Lists
class Solution {
    public ListNode mergeInBetween(ListNode list1, int a, int b, ListNode list2) {
        ListNode dummyHead = new ListNode();
        dummyHead.next = list1;
        
        ListNode curr = dummyHead;
        
        while (curr.next != null && curr.next.val != a) curr = curr.next;
        
        ListNode temp = curr.next;
        curr.next = list2;
        curr = temp;
        
        while (curr != null && curr.val != b) curr = curr.next;
        
        ListNode tail = list2;
        while (tail.next != null) tail = tail.next;
        tail.next = curr.next;
        
        return dummyHead.next;
    }
}
```

#### Language used for code
Java

#### Expected behavior
With input:
```
[0,3,2,1,4,5]
3
4
[1000000,1000001,1000002]
```
I think the correct output should be `[0,1000000,1000001,1000002,5]`
But the 61st test case expects `[0,3,2,1000000,1000001,1000002,5]`

**Comment by lc-kay** [comment]
@hyuan The expected test case is correct. Please check out the following discuss posts https://leetcode.com/problems/merge-in-between-linked-lists/discuss/1024510/Explain-this-test-case https://leetcode.com/problems/merge-in-between-linked-lists/discuss/1028251/one-test-case-is-wrong Thank you for your time.
