### ISSUE TITLE
Missing Test Case - 1824. Minimum Sideway Jumps

### ISSUE THREAD

**Issue by archit11111** [LeetCode-Feedback/LeetCode-Feedback#3068]
#### Your LeetCode username
archit91

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A solution is accepted but fails on the following valid test case (0 followed by '1,2,3' for 100000 times followed by 0) -
[1824.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6291307/1824.txt)

#### Code you used for Submit/Run operation

```
class Solution {
public:
    const static int maxn = 5e5 + 5;
    int df[maxn][4] , n , vis[maxn][4];
    int dx[5] = {-1 , 0 , 1 , -2 , 2};
    int dp[5] = {0 , 1 , 0 , 0 , 0};
    int dfs(int p , int x , vector <int>& ob) {
        if(vis[p][x - 1])return df[p][x - 1];
        if(p == n - 1)return df[p][x - 1] = 0;
        vis[p][x - 1] = 1;
        int cnt = maxn;
        df[p][x - 1] = cnt;
        for(int i = 0 ; i < 5 ; i++) {
            int p1 = p + dp[i];
            int x1 = x + dx[i];
            if(x1 <= 0 || x1 > 3)continue;
            if(x1 != ob[p1]) {
                int ct = 0;
                if(i != 1)ct++;
                else {
                    while(p1 + 1 < n && ob[p1 + 1] != x1) {
                        p1++;
                    }
                }
                cnt = min( dfs(p1 , x1 , ob) + ct , cnt);
            }
            df[p][x - 1] = cnt;
        }
        return df[p][x - 1];
    }
    int minSideJumps(vector<int>& ob) {
        n = ob.size();
        return dfs(0 , 2 , ob);
    }
};
```

#### Language used for code

C++

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/40712852/114295014-14e6cb00-9ac0-11eb-9377-b576e85e0eca.png)

**Comment by lc-kay** [comment]
Hi @archit11111 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @archit11111 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
