### ISSUE TITLE
Missing Test Case - 1630. Arithmetic Subarrays

### ISSUE THREAD

**Issue by vot-developer** [LeetCode-Feedback/LeetCode-Feedback#3070]
#### Your LeetCode username
vot-developer

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
A solution is accepted but fails on the following test case:
[1,1,7,7]
[0]
[3]

#### Code you used for Submit/Run operation

```
class Solution {
    public List<Boolean> checkArithmeticSubarrays(int[] nums, int[] l, int[] r) {
        List<Boolean> ans = new ArrayList<>();
        for (int c = 0; c < l.length; c++){
            ans.add(isArithmetic(nums, l[c], r[c]));
        }
        return ans;
    }
    
    private boolean isArithmetic(int[] nums, int start, int end){        
        int n = (end - start + 1);
        int min = Integer.MAX_VALUE;
        int max = Integer.MIN_VALUE;
        int sum = 0;
        for (int i = start; i <= end; i++){
            int val = nums[i];
            min = Math.min(val, min);
            max = Math.max(val, max);
            sum += val;
        }
        int diff = (max - min) / (n - 1);
        if ((max - min) % (n - 1) != 0)
            return false;
            
        if (diff == 0){
            if (max != min)
                return false;
            return true;
        }             
        
        int ariphSum = n * (min + max) / 2;
        if (ariphSum != sum)
            return false;

        for (int i = start; i <= end; i++){
            int val = nums[i];
            if ((val - min) % diff != 0)
                return false;
        }
        
        return true;
    }
}
```

#### Language used for code
Java

#### Expected behavior
The solution should not be accepted since it fails on the test case.

#### Screenshots

![Capture](https://user-images.githubusercontent.com/19599582/114298807-cdad0a00-9ac0-11eb-9766-b87b95d5930e.JPG)

#### Additional context
This test case is an example of how to trick and blame the system to get the high-performance result without really check every right element contains.

**Comment by lc-kay** [comment]
Hi @vot-developer 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @vot-developer 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
