### ISSUE TITLE
Missing Test Case - 1822. Sign of the Product of an Array

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#3075]
#### Your LeetCode username

igor84

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A solution is accepted but fails on the following test case:

[-41, -22, 22, -84, 9, -92, -97, 42, 40, 48, 71, 63, 29, 5, -66]

#### Code you used for Submit/Run operation

```
class Solution {
    public int arraySign(int[] nums) {
     long product=1;
        for ( int i = 0; i < nums.length; i++){
        product = ( product * nums[i]);
        if ( product > Integer.MAX_VALUE)
            product/=Integer.MAX_VALUE;
        }
    return signFunc(product);
    
    }
    
    public int signFunc(long product) {
           if (product == 0) return 0;
        else{
                if(product < 0) return -1;

            }

    return 1;
            }
    
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/114309289-b0723e80-9ab4-11eb-99af-8eaaced35bc5.png)

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
