### ISSUE TITLE
Missing Test Case - 1825. Finding MK Average

### ISSUE THREAD

**Issue by Kytabyte** [LeetCode-Feedback/LeetCode-Feedback#3077]
#### Your LeetCode username
K_kkkyle

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The test cases for this problem are too small, such that many suboptimal solutions can pass the OJ.

It is mentioned in the problem that at most `10^5` calls on `addElement` and `calculateMKAverage`, which means that the solution is expected to have O(1) or O(logn) time for each call. However, a lot of implementation of `calculateMKAverage` are just brute-force take O(n) time to calculate the sum of a sorted array, and such solution passed the OJ. 

I generated an extreme case, where `m=50000, k=1`, it has 50000 `addElement` call followed by 50000  `calculateMKAverage`, which makes sure there will be 50000 calls will calculate the average on an array of length nearly 50000 (49998 precisely). This case doesn't violent any provided restriction but got TLE from OJ. I hope LC could add this test case to make sure the suboptimal solution will be rejected.

**EDIT**: The above case can easily be hacked by caching a previous answer and reuse it as long as no `addElement` is called (since the result of `calculateMKAverage` won't change if no `addElement` is called) . 

A better case maybe like this:

1. Set `m = 33333` and `k = 1`
2. Call `addElement` 33333 times
3. For the next 66667 calls, do `calculateMKAverage` 33334 times and `addElement` 33333 times alternatively.

In this way, 33333 `calculateMKAverage` will be calculated on different data with a size of 33333. This will make sure the failure of the O(n) `calculateMKAverage` algorithms.

#### Code you used for Submit/Run operation

Here is a sample code that can pass the OJ but failed at my generated test case.

```python
class MKAverage:

    def __init__(self, m: int, k: int):
        self.m, self.k = m, k
        self.q = collections.deque()
        self.a = []

    def addElement(self, num: int) -> None:
        bisect.insort(self.a, num)
        
        self.q.append(num)
        if len(self.q) > self.m:
            x = self.q.popleft()
            i = bisect.bisect_left(self.a, x)
            self.a.pop(i)
        
    def calculateMKAverage(self) -> int:
        if len(self.a) < self.m:
            return -1

        return sum(self.a[self.k:self.m-self.k]) // (self.m - self.k*2) 
```

Here is my script to generate my test case. Since the case is too large, it's not good to directly copy-paste it here.

```python
init = "MKAverage"
add = "addElement"
calc = "calculateMKAverage"

MAX_CALL = int(5e4)
methods = [init]
args = [[MAX_CALL,1]]
for _ in range(MAX_CALL):
    methods.append(add)
    args.append([random.randint(1, 100000)])
for _ in range(MAX_CALL):
    methods.append(calc)
    args.append([])

with open('lc1825-extreme-case.txt', 'w') as f:
    json.dump(methods, f)
    f.write('\n')
    json.dump(args, f)
```

**Edit**, new test case generate script:

```python
init = "MKAverage"
add = "addElement"
calc = "calculateMKAverage"

MAX_CALL = 33333
methods = [init]
args = [[MAX_CALL,1]]

# generate 33333 data
for _ in range(MAX_CALL):
    methods.append(add)
    args.append([random.randint(1, 100000)])

# caculate average and update data alternatively (66666 calls in total)
for _ in range(MAX_CALL):
    methods.append(calc)
    args.append([])
    methods.append(add)
    args.append([random.randint(1, 100000)])

# make a final calculation
methods.append(calc)
args.append([])    

with open('lc1825-extreme-case2.txt', 'w') as f:
    json.dump(methods, f)
    f.write('\n')
    json.dump(args, f)
```

#### Language used for code
Python, didn't try other languages. Can update result on other languages later on

#### Expected behavior

The above solution should fail the OJ since it cannot pass the extreme case I provided above.

**Comment by lc-kay** [comment]
@Kytabyte Please provide the test cases in a .txt file. Thank you!

**Comment by Kytabyte** [comment]
[lc1825-extreme-case.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6299728/lc1825-extreme-case.txt)
[lc1825-extreme-case2.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6299725/lc1825-extreme-case2.txt)

Here you go! I prefer the second one as the first one can be easily hacked

**Comment by lc-kay** [comment]
Hi @Kytabyte 
Thank you for providing that. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Kytabyte 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
