### ISSUE TITLE
Missing Test Case - 297. Serialize and Deserialize Binary Tree

### ISSUE THREAD

**Issue by jalandharch** [LeetCode-Feedback/LeetCode-Feedback#3078]
#### Your LeetCode username
jalandhar

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
In the  question 297 - Serialize and Deserialize Binary Tree, the leet code simply comparing the final answer with the input binary tree. But when i have checked the 0 ms solution, there is a blunder in the code but it was accepted because of the missing test cases. The code simply returns an empty string in serialization and in returns the same root in deserialization which was given as input through a static variable declared in the class.

-The missing test case is that, the test case should check for the presence of the binary tree node values in the serialized string, but this test case might fail if the returned string is in binary string format.
- If the binary tree is not blank/empty, then ensure that the serialized string is not empty/blank
- One good way to avoid such code is that, ensure that the object references are not same. i.e the object reference used for input and output should not be same so that in the code no one can simply return the same root node.
- One other problem still might occur is, if someone creates a new node and updates its data, left and right pointers from the  input root node without actually deserializing the string content, it would be difficult to catch unless we go and check the code
- 

#### Language used for code
Java

#### Expected behavior
The dummy solutions without deserializing the binary tree should not be accepted

#### Screenshots

![image](https://user-images.githubusercontent.com/33083504/114317990-69259580-9b28-11eb-872c-089c9cc82e27.png)

**Comment by lc-kay** [comment]
@jalandharch Can you please provide the missing test case and the submission details link to the code? Thank you!

**Comment by jalandharch** [comment]
Please go through the following code, you will understand.
The below code is not serializing the binary tree actually but just returning the same root node.


public class Codec {
    private static TreeNode node;

    // Encodes a tree to a single string.
    //This is to prove the missing test case flow
    public String serialize(TreeNode root) {
            node=root;
        return "";
    }

    // Decodes your encoded data to tree.
    public TreeNode deserialize(String data) {
        return node;
    }
    
}

**Comment by lc-kay** [comment]
@jalandharch I understand that you are trying to report samples of missing test cases. However, for a valid report, please provide the exact test case that will cause the solution to fail.

**Comment by LC-Pamela** [comment]
Hi @jalandharch  ,
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
