### ISSUE TITLE
Link in solution of question 590 N-ary Tree Postorder Traversal returns 404

### ISSUE THREAD

**Issue by BuffaloDrew** [LeetCode-Feedback/LeetCode-Feedback#3079]
#### Your LeetCode username
kartoshka

#### Category of the bug
- [x] Question

#### Description of the bug
Link in solution of question 590 N-ary Tree Postorder Travel returns 404. The link points to https://leetcode.com/articles/binary-tree-postorder-transversal/

**Comment by lc-kay** [comment]
Hi @BuffaloDrew 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @BuffaloDrew 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
