### ISSUE TITLE
249. Group Shifted Strings 题目描述不准确

### ISSUE THREAD

**Issue by liangteng** [LeetCode-Feedback/LeetCode-Feedback#308]
** Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
题目描述不太准确，“字符串中每个字母都变为其在字母表中**后续**的字母”，按照字面意思，字母z是字母a的后续。
示例中，认为["az","ba"]是一组，也就是认为字母a是字母z的后续，跟字母表中z是a的后续有冲突，跟题目描述字面意思不太一致，会让人产生理解上的歧义。
建议在题目描述中，补充说明字母表是首位相接，字母z的后续是字母a。

**你使用的语言**
C++

**你提交或者运行的代码**

**期望行为**
优化题目描述，消除歧义。

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
问题反馈ac后有积分奖励嘛~😏🤡

**Comment by feiceh** [comment]
感谢反馈，当前已为示例补充了解释，贡献测试案例可以 +100 LeetCoin (被采纳后)，我们诚挚的期待您的贡献～
