### ISSUE TITLE
Solution - 466. Count The Repetitions

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#3080]
#### Your LeetCode username

igor84

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

A couple of paragraphs of solution is not rendered properly. Please see screenshots below

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/114327297-716cd900-9b06-11eb-8eba-cf4f831baf5b.png)

![image](https://user-images.githubusercontent.com/32546406/114327333-8b0e2080-9b06-11eb-9c67-60f39d3df6ef.png)

![image](https://user-images.githubusercontent.com/32546406/114327357-b0029380-9b06-11eb-8b66-f285d4aaa929.png)

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
