### ISSUE TITLE
Missing Test Case - 474. Ones and Zeroes

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#3081]
#### Your LeetCode username

igor84

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A solution is accepted but fails on the following test case:

["10010", "10111011", "001", "110000", "101111", "1011001001", "0111", "1", "11101001", "01110", "0000101", "110110010", "0101", "010111100", "011000", "00100101", "0011", "00", "10011000", "00010", "010011011", "1011", "010011010", "11110", "1", "11010", "00010000", "0101", "111010", "1100011", "001000", "11", "10011", "1111110001", "100", "1010101111", "010", "10000", "01"]
10
8

#### Code you used for Submit/Run operation

```
public class Solution {
    public int findMaxForm(String[] strs, int m, int n) {
        Map<String, int[]> map = new HashMap<>();
        for (String str : strs) {
            if (map.containsKey(str))
                continue;
            int ones = 0, zeros = 0;
            for (int i = 0; i < str.length(); i++) {
                if (str.charAt(i) == '1')
                    ones++;
                else
                    zeros++;
            }
            map.put(str, new int[]{zeros, ones});
        }
        Set<Integer>[][] dp = new HashSet[m + 1][n + 1];
        for (int i = 0; i <= m; i++) {
            for (int j = 0; j <= n; j++) {
                Set<Integer> set = new HashSet<>();
                dp[i][j] = set;
                for (int k = 0; k < strs.length; k++) {
                    int[] info = map.get(strs[k]);
                    if (i >= info[0] && j >= info[1]) {
                        Set<Integer> d = dp[i - info[0]][j - info[1]];
                        if (d.size() > dp[i][j].size() || (!d.contains(k) && d.size() + 1 > dp[i][j].size())) {
                            set.clear();
                            set.add(k);
                            set.addAll(dp[i - info[0]][j - info[1]]);
                        }
                    }
                }
            }
        }
        return dp[m][n].size();
    }
}

```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/114328399-83507b00-9b0a-11eb-889d-7e8a6f59ad0d.png)

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
