### ISSUE TITLE
Missing Test Case/Wrong Expected Answer - 747. Largest Number At Least Twice of Others

### ISSUE THREAD

**Issue by Silvia42** [LeetCode-Feedback/LeetCode-Feedback#3082]
#### Your LeetCode username
Silvia42

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Description says:  "...there is always exactly one largest element."

The test cases with more than one largest elements are allowed and the expected answer is wrong.

The solution is accepted.

#### Code you used for Submit/Run operation
```
class Solution:
    def dominantIndex(self, nums: List[int]) -> int:
        if len(nums)<2: return 0
        max1=max2=0
        iMax=0
        for i,x in enumerate(nums):
            if x>max1:
                iMax=i
                max2=max1
                max1=x
            elif x>max2:
                max2=x
        if max1/2<max2: return -1
        return iMax
```

#### Language used for code
Python 3

#### Expected behavior

Per this description the input where maximum item is in the nums more then one time is not allowed.
For example:
[1,1]
[1,1,1,0,0,1]

When I add this test case, I am expecting, that LeetCode will let me know, that the testcase is not correct.
This doesn't happen. 

If we allow testcases like this, what is the expected correct answer?
"The largest element in the array is at least twice as much as every other number in the array."

Let think about nums=[1,1]:
max([1,1]) = 1
nums[0]=1
nums[1]=1
nums[0] is not at least twice as much as nums[1].
Which means
nums[0] is max(nums) and nums[0] is not at least twice as much as every other number in the array.

Per this explanation the answer should be -1.

If we think that both numbers are max(nums), than both indexes has to be correct answer. The problem description doesn't specify what should be the correct answer. List of indexes? ```[0,1]```

LEETCODE expected answer ```0``` can't be correct.

#### Screenshots

![image](https://user-images.githubusercontent.com/37594365/114334613-ecd78600-9b18-11eb-9a9b-7e63b56f49c3.png)

#### Additional context

This Question has also problem with the number **ZERO**.
NOTE says:
**Every nums[i] will be an integer in the range [0, 99].**
```
Example 1:

Input: nums = [3, 6, 1, 0]
Output: 1
Explanation: 6 is the largest integer, and for every other number in the array x,
6 is more than twice as big as x.  The index of value 6 is 1, so we return 1.
```

This example says that 6 is more than twice as big as ZERO.
How many times is 6 bigger than ZERO?
 ```
6 * x = 0
x = 6 / 0
!!! Division with ZERO !!!
```
In this Problem should be:
"Every nums[i] will be an integer **in the range [1, 99].**"

**Comment by lc-kay** [comment]
Hi @Silvia42 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Silvia42 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
