### ISSUE TITLE
problem 1222. correct answer on running, wrong answer on the same test case on submitting.

### ISSUE THREAD

**Issue by hi-18-K** [LeetCode-Feedback/LeetCode-Feedback#3083]

**Comment by lc-kay** [comment]
Hi @hi-18-K 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
