### ISSUE TITLE
Missing Test Case - 141. Linked List Cycle

### ISSUE THREAD

**Issue by etwei-linkedin** [LeetCode-Feedback/LeetCode-Feedback#3084]
#### Your LeetCode username
Not important..

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

It seems that my solution which passed didn't consider the case that if the List only has a head and head.next points to itself. 

```
ListNode head = new ListNode(0);
head.next = head;
```

#### Code you used for Submit/Run operation

```
public class Solution {
    public boolean hasCycle(ListNode head) {
        if (head == null) return false;
        // if (head.next == head) return true;
        
        ListNode fast = head;
        ListNode slow = head;
        
        while (fast != null && fast.next != null) {
            if ((fast == slow && fast != head) || fast.next == slow) return true;
            fast = fast.next.next;
            slow = slow.next;
        }
        
        return false;
    }
}
```

#### Language used for code
`Java`

#### Expected behavior
My submission was supposed to fail...

**Comment by lc-kay** [comment]
@etwei-linkedin Please provide the test case that it fails on. Thank you!

**Comment by LC-Pamela** [comment]
Hi @etwei-linkedin ,
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
