### ISSUE TITLE
3705 Beautiful Arrangement II input constraint not respected

### ISSUE THREAD

**Issue by pinieb** [LeetCode-Feedback/LeetCode-Feedback#3085]
### Your LeetCode username
pinieb

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In Beautiful Arrangement II, the Notes section calls out that `k` is strictly less than `n` ("The n and k are in the range 1 <= k < n <= 10^4."), however, the expected result of `n=1`, `k=1` is `[1]` instead of `[]`

Edit: The code producing the expected results is exhibiting this behavior for all `n=1`, regardless of the value of `k`. The output for "invalid input" scenarios should ideally be consistent.

#### Code you used for Submit/Run operation
```swift
class Solution {
    func constructArray(_ n: Int, _ k: Int) -> [Int] {
        return []
    }
}
```

#### Language used for code
Swift

#### Expected behavior
Either the problem statement should be updated to reflect that `k=n=1` is a valid case, or the code providing the expected results should output `[]` for this case like it does for other inputs which break the constraint listed in the Notes section.

**Comment by lc-kay** [comment]
Hi @pinieb 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @pinieb 
Thank you for your time. The team reviewed your report and noticed the problem was missing validators. \We appreciate your support!
