### ISSUE TITLE
Typo in 1821. Find Customers With Positive Revenue this Year

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#3086]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
There is a typo in [1821. Find Customers With Positive Revenue this Year](https://leetcode.com/problems/find-customers-with-positive-revenue-this-year). In the example, the correct statement should be: "Customer 1 has revenue equal to 30 in year 2021." The number 50 is incorrect. Please refer to the screenshot below.

#### Expected behavior
In the example, the correct statement should be: "Customer 1 has revenue equal to 30 in year 2021."

#### Screenshots
![image](https://user-images.githubusercontent.com/12067364/114389392-8493ad80-9bc7-11eb-98cc-79ac85500ac6.png)

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
