### ISSUE TITLE
Wrong complexity in the solution - 252. Meeting Rooms

### ISSUE THREAD

**Issue by oobarbazanoo** [LeetCode-Feedback/LeetCode-Feedback#3087]
#### Your LeetCode username

oobarbazanoo
https://leetcode.com/oobarbazanoo/

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Space complexity depends on the sorting algorithm being used. If the time complexity is O(nlogn), then a quicksort was most probably used. It has O(n) space complexity, but you put O(1). That is wrong.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
Hi @oobarbazanoo 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@oobarbazanoo Thanks for your report. One of our solution article writers will fix this when they get a chance :)
