### ISSUE TITLE
Missing Test Case - 1185. Day of the Week

### ISSUE THREAD

**Issue by vnicolev** [LeetCode-Feedback/LeetCode-Feedback#3088]
#### Your LeetCode username

vnicolev

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My solution is accepted, but it seems I didn't consider the following test case:
```
28
2
1972
```

#### Code you used for Submit/Run operation

```
class Solution:
    def dayOfTheWeek(self, day: int, month: int, year: int) -> str:
        w = ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']
        m = [0,31,59,90,120,151,181,212,243,273,304,334,]
        
        # start date (1970/12/27) is Sunday
        
        diff = (year-1971) * 365 + m[month-1] + (day-1) + self.leapYearTimes(year) + 5
        if month == 2 and day ==29:
            diff -= 1
        return w[diff%7]
        
    def leapYearTimes(self, y):
        t = 0
        for i in range(1972, y+1, 4):
            if i%100 == 0 and i%400 != 0:
                continue
            t += 1
        return t
```

#### Language used for code

Python3

#### Expected behavior

Since my solution didn't cover the test case which fulfills the below conditions:
* The given year is a leap year
* The given month and day does not pass 29 Feb yet

I suggest adding a new test case so if any solution like mine will fail.

#### Screenshots
<!-- If applicable, add screenshots to explain your issue. --
<img width="1259" alt="1185" src="https://user-images.githubusercontent.com/26741862/114436744-49f63900-9bf8-11eb-9fc8-42e613d38d6e.png">

**Comment by lc-kay** [comment]
Hi @vnicolev 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @vnicolev 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
