### ISSUE TITLE
Error in solution - 371. Sum of Two Integers

### ISSUE THREAD

**Issue by ibeauregard** [LeetCode-Feedback/LeetCode-Feedback#3089]
#### Your LeetCode username
mrchose

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the Python 3 solution of approach 2, line 9 should be `return a if a <= max_int...`

#### Language used for code
Python 3

#### Screenshots
I simplified the case by using `mask = 0xF` and `max_int = 0x7`.
Wrong behaviour:
![Capture d’écran, le 2021-04-12 à 14 28 15](https://user-images.githubusercontent.com/1441192/114443234-716ae880-9b9b-11eb-9332-e4ae8907b044.png)

Correct behaviour:
![Capture d’écran, le 2021-04-12 à 14 28 35](https://user-images.githubusercontent.com/1441192/114443245-75970600-9b9b-11eb-9ddf-3c63375569ef.png)

**Comment by lc-kay** [comment]
Hi @ibeauregard 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@ibeauregard Our team has reviewed your report and found that our code is working as expected. The reason you're getting the wrong answer is that you modified the values of mask and max_int. Thank you for your time.
