### ISSUE TITLE
Missing test case - 1287. Element Appearing More Than 25% In Sorted Array

### ISSUE THREAD

**Issue by CherishHack** [LeetCode-Feedback/LeetCode-Feedback#3090]
#### Your LeetCode username
Hammer001

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
I wrote a buggy code in Python3, it passes the submission, but it does not pass my test case. 

```
[1,2,3,4,5,6,7,8,9,10,11,12,12,12,12]
```

Please consider adding the test case to the judge system

#### Code you used for Submit/Run operation
```
class Solution:
    def findSpecialInteger(self, arr: List[int]) -> int:
        N = len(arr)//4
        for end in set([N, N*2, N*3]):
            lo, hi = end-N, end
            
            while lo < hi:
                mid = (lo + hi) >> 1
                
                if arr[mid] != arr[end]:
                    lo = mid + 1
                else:
                    hi = mid
        
        
            if lo + N < len(arr) and arr[lo + N] == arr[lo]:
                return arr[lo]
```

#### Language used for code
Python3

#### Expected behavior
My buggy code should get Wrong Answer, but now it is Accepted.

#### Additional context
I believe the bug in my provided code is: I divide by 4 before multiplying. Thus, it fails to get to the number `12`.

**Comment by lc-kay** [comment]
Hi @CherishHack 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @CherishHack 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
