### ISSUE TITLE
Typo in Problem #378

### ISSUE THREAD

**Issue by AidanFarhi** [LeetCode-Feedback/LeetCode-Feedback#3091]
#### Category of the bug
- [X ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
Duplicate of #3092
