### ISSUE TITLE
Typo in problem #378

### ISSUE THREAD

**Issue by AidanFarhi** [LeetCode-Feedback/LeetCode-Feedback#3092]
#### Your LeetCode username
afarhidev

#### Category of the bug
- [X ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the constraints section, it states: 
All the rows and columns of matrix are guaranteed to be sorted in "non-degreasing" order.
It should say: "non-decreasing"

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

<img width="574" alt="Screen Shot 2021-04-12 at 6 08 08 PM" src="https://user-images.githubusercontent.com/61877497/114469315-e39ef580-9bba-11eb-9405-324dd1bddaa7.png">

**Comment by AidanFarhi** [comment]
Typo in problem #378

**Comment by lc-kay** [comment]
Hi @AidanFarhi 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @AidanFarhi 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
