### ISSUE TITLE
测试用例补充 - 219. 存在重复元素 II

### ISSUE THREAD

**Issue by GinShio** [LeetCode-Feedback/LeetCode-Feedback#3094]
#### 你的 LeetCode 用户名

GinShio

#### Bug 类型
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 测试用例

#### 描述 BUG
错误代码通过了测试

#### 你提交或者运行的代码

```cpp
class Solution {
 public:
  bool containsNearbyDuplicate(vector<int>& nums, int k) {
    int size = nums.size();
    int l = 0, r = -1;
    while (l < size) {
      r + 1 < size && r + 1 <= l + k ? ++r : ++l;
      if (l < r && nums[r] == nums[l]) {
        return true;
      }
    }
    return false;
  }
};
```

#### 代码所用的编程语言
C++

#### 期望行为
在使用测试用例
> [1,2,2,3]
> 3

时，以上代码将会返回错误结果，提交不应通过

#### Screenshots
![Screenshot_20210413_141427](https://user-images.githubusercontent.com/38715657/114506298-28329b80-9c64-11eb-842e-0e4da782ae86.png)

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
@lc-kay 麻烦帮忙跟进下这个用户反馈哦。

**Comment by lc-kay** [comment]
Hi @feiceh 
I've relayed this issue to our team to investigate.

**Comment by LC-Pamela** [comment]
@feiceh The test case is added, please reward the user.

**Comment by feiceh** [comment]
@GinShio  你好，当前该题已添加测试用例， ID：GinShio 给予积分奖励，请查收。
