### ISSUE TITLE
Missing Test Case - 31. Next Permutation

### ISSUE THREAD

**Issue by Amaish** [LeetCode-Feedback/LeetCode-Feedback#3095]
#### Your LeetCode username

owlcrew

#### Category of the bug
- [ ] Solution

#### Description of the bug

The solution I have is giving me the expected result but on your compiler, it picks a different answer which I am not sure where it is coming from. e.g when input is [1,2,3] the expected output is [1,3,2] which is my stdout result but from your end you pick [1,2,3] as the solution

#### Code you used for Submit/Run operation

```
func nextPermutation(nums []int) {
	var mynum int
	var myNewnum int
	var result []int
	loopCond := false
	if len(nums) < 2 {
		result = nums
	} else {
		for i := 0; i < len(nums)/2; i++ {
			j := len(nums) - i - 1
			nums[i], nums[j] = nums[j], nums[i]
		}
		if sort.IntsAreSorted(nums) {
			result = nums
		} else {
			for i := 0; i < len(nums)/2; i++ {
				j := len(nums) - i - 1
				nums[i], nums[j] = nums[j], nums[i]
			}
			for i, v := range nums {
				pow := len(nums) - 1 - i
				mynum += v * int(math.Pow10(pow))
			}
			myNewnum = mynum
			numString := strconv.Itoa(mynum)
			for !loopCond {
				myNewnum += 9
				newString := strconv.Itoa(myNewnum)
				for _, v := range newString {
					status := bytes.ContainsRune([]byte(numString), v)
					if !status {
						loopCond = false
						result = nil
						break
					} else {
						val, _ := strconv.Atoi(string(v))
						result = append(result, val)
						loopCond = true
					}
				}
			}
		}
	}
	fmt.Println(result)
}
```

#### Language used for code

GoLang

**Comment by lc-kay** [comment]
@Amaish I'd recommend checking out other Go submissions in the problem discuss page or posting your question on there for further support. Thank you for your time.
