### ISSUE TITLE
执行代码逻辑和提交后逻辑不一样

### ISSUE THREAD

**Issue by Zhuyi731** [LeetCode-Feedback/LeetCode-Feedback#3096]
**Incarnation**
Incarnation

**Bug 类型**
- [ ] 题目 
- [ ] 题解
- [x] 编程语言

**描述**
783. 二叉搜索树节点最小距离 题目用go执行测试用例通过，提交不通过

**你使用的语言**
GO

**你提交或者运行的代码**
```
func abs(i int) int {
	if i < 0 {
		return -i
	}
	return i
}

var min = 1000000

func minDiffInBST(root *TreeNode) int {
	return f(root, min)
}

func f(root *TreeNode, parent int) int {

	l := min
	lc := min
	r := min
	rc := min
	rp := min
	lp := min
	if root.Left != nil {
		l = abs(root.Left.Val - root.Val)
		lc = f(root.Left, root.Val)
		lp = abs(parent - root.Left.Val)
	}
	if root.Right != nil {
		r = abs(root.Right.Val - root.Val)
		rc = f(root.Right, root.Val)
		rp = abs(parent - root.Right.Val)
	}

	if l < min {
		min = l
	}

	if lc < min {
		min = lc
	}
	if lp < min {
		min = lp
	}
	if r < min {
		min = r
	}
	if rc < min {
		min = rc
	}
	if rp < min {
		min = rp
	}
	return min
}
```

**期望行为**

**屏幕截图**
![image](https://user-images.githubusercontent.com/17618307/114538949-87a1a300-9c86-11eb-9ef0-24fddd6feb04.png)

**额外的上下文**

**Comment by feiceh** [comment]
你好，建议再仔细检查并调试一下代码，推荐阅读：「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」 获得更多帮助。

同时也可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
