### ISSUE TITLE
Missing Test Case - 514. Freedom Trail

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#3097]
#### Your LeetCode username

igor84

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A solution is accepted but fails on the following test case:

"eh"
"h"

#### Code you used for Submit/Run operation

```
public class Solution {
    public int findRotateSteps(String ring, String key) {
        int m = ring.length();
        int n = key.length();
        if (n == 0) return 0;
        int[][] d = new int[m][n];
        
        for (int i = 0; i < m; i++) {
            for (int j = 0; j < n; j++) {
                d[i][j] = Integer.MAX_VALUE;
            }
        }
        
        for (int i = 0; i < m; i++) {
            if (ring.charAt(i) == key.charAt(0)) {
                d[i][0] = Math.min(i, m - i) + 1;
            }
        }
        
        int ans = Integer.MAX_VALUE;
        for (int j = 1; j < n; j++) {
            for (int i = 0 ; i < m; i++) {
                if (ring.charAt(i) == key.charAt(j - 1)) {
                    for (int k = 0; k < m; k++) {
                        if (ring.charAt(k) == key.charAt(j)) {
                            d[k][j] = Math.min(d[k][j], Math.min(Math.abs(k - i), m - Math.abs(k - i)) + d[i][j - 1] + 1);
                        }
                        if (j == n - 1) ans = Math.min(ans, d[k][n - 1]);
                    }
                }
            }
        }
        
        return ans;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/114541261-77f17280-9c24-11eb-8993-802748d393b4.png)

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
