### ISSUE TITLE
Wrong label - 942. DI String Match

### ISSUE THREAD

**Issue by nikhilmaske-2001** [LeetCode-Feedback/LeetCode-Feedback#3098]
#### Your LeetCode username
 nikhil_2001

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Wrong label

#### Description of the bug
 This question do not have any connection with `math`, it should have the `greedy` tag to be more specific. Question link: https://leetcode.com/problems/di-string-match/solution/

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior
 Question should have `greedy` label.

**Comment by lc-kay** [comment]
@nikhilmaske-2001 Thank you for your feedback. I have relayed this to our team to investigate.
