### ISSUE TITLE
Missing Test Cases 

### ISSUE THREAD

**Issue by HaroldHairyPants** [LeetCode-Feedback/LeetCode-Feedback#3099]
#### Your LeetCode username

HaroldHairyPants

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

In 542. 01 Matrix error in test №17
Input : [[0,0,1,0,1,1,1,0,1,1],[1,1,1,1,0,1,1,1,1,1],[1,1,1,1,1,0,0,0,1,1],[1,0,1,0,1,1,1,0,1,1],[0,0,1,1,1,0,1,1,1,1],[1,0,1,1,1,1,1,1,1,1],[1,1,1,1,0,1,0,1,0,1],[0,1,0,0,0,1,0,0,1,1],[1,1,1,0,1,1,0,1,0,1],[1,0,1,1,1,0,1,1,1,0]]
Output : [[0,0,1,0,1,2,1,0,1,2],[1,1,2,1,0,1,1,1,4,5],[2,1,3,1,1,0,0,0,1,2],[1,0,1,0,1,1,1,0,1,2],[0,0,1,1,1,0,1,1,2,4],[1,0,1,2,1,1,1,2,1,4],[1,1,1,1,0,1,0,1,0,1],[0,1,0,0,0,1,0,0,1,2],[1,1,1,0,1,1,0,1,0,1],[1,0,1,1,1,0,1,2,1,0]]
Expected : [[0,0,1,0,1,2,1,0,1,2],[1,1,2,1,0,1,1,1,**2**,**3**],[2,1,**2**,1,1,0,0,0,1,2],[1,0,1,0,1,1,1,0,1,2],[0,0,1,1,1,0,1,1,2,**3**],[1,0,1,2,1,1,1,2,1,**2**],[1,1,1,1,0,1,0,1,0,1],[0,1,0,0,0,1,0,0,1,2],[1,1,1,0,1,1,0,1,0,1],[1,0,1,1,1,0,1,2,1,0]]

#### Code you used for Submit/Run operation

```
 public static int[][] UpdateMatrix(int[][] matrix)
        {
            int rowsCount = matrix.Length;
            int columnCount = matrix[0].Length;
            int[][] resultMatrix =(int[][]) matrix.Clone();
            for (int i = 0; i < rowsCount; i++)
            {
                for (int j = 0; j < columnCount; j++)
                {
                    if (matrix[i][j] == 0)
                    {
                        resultMatrix[i][j] = 0;
                    }
                    else
                    {
                        int minLeftPath = columnCount;
                        int minRightPath = columnCount;
                        int minTopPath = rowsCount;
                        int minBottomPath = rowsCount;
                        for (int n = i+1; n < rowsCount; n++)
                        {
                            if(matrix[n][j]==0)
                            {
                                minBottomPath = n - i;
                                break;
                            }
                        }
                        for (int n = i - 1; n >= 0; n--)
                        {
                            if (matrix[n][j] == 0)
                            {
                                minTopPath = i - n;
                                break;
                            }
                        }

                        for (int n = j + 1; n < columnCount; n++)
                        {
                            if (matrix[i][n] == 0)
                            {
                                minRightPath = n - j;
                                break;
                            }
                        }
                        for (int n = j - 1; n >= 0; n--)
                        {
                            if (matrix[i][n] == 0)
                            {
                                minLeftPath = j - n;
                                break;
                            }
                        }
                        resultMatrix[i][j] = Math.Min(Math.Min(minTopPath, minBottomPath), Math.Min(minRightPath, minLeftPath));
                    }
                }
            }
            return resultMatrix;
        }
```

#### Language used for code

C#

#### Expected behavior

Expected : [[0,0,1,0,1,2,1,0,1,2],[1,1,2,1,0,1,1,1,4,5],[2,1,3,1,1,0,0,0,1,2],[1,0,1,0,1,1,1,0,1,2],[0,0,1,1,1,0,1,1,2,4],[1,0,1,2,1,1,1,2,1,4],[1,1,1,1,0,1,0,1,0,1],[0,1,0,0,0,1,0,0,1,2],[1,1,1,0,1,1,0,1,0,1],[1,0,1,1,1,0,1,2,1,0]]

#### Screenshots

![image](https://user-images.githubusercontent.com/45938867/114563394-0ba05e80-9c78-11eb-849d-a2245dac0642.png)

**Comment by lc-kay** [comment]
@HaroldHairyPants Please provide the submission details link to your code. Thank you!

**Comment by HaroldHairyPants** [comment]
@lc-kay  https://leetcode.com/submissions/detail/480128741/

**Comment by lc-kay** [comment]
@HaroldHairyPants The expected output is correct. Please check out this comment https://leetcode.com/problems/01-matrix/discuss/101090/Why-is-answer-wrong/479043
