### ISSUE TITLE
1095山脉数组的测试引擎找不到MoutainArray接口的声明

### ISSUE THREAD

**Issue by happy15** [LeetCode-Feedback/LeetCode-Feedback#31]
如题，直接编译错误：

Line 11: error: cannot find symbol

    public int findInMountainArray(int target, MountainArray mountainArr) {

                                               ^

  symbol:   class MountainArray

  location: class Solution

Line 10: error: incompatible types: int[] cannot be converted to int [in __Driver__.java]

      int ret = new Solution().findInMountainArray(param_1, param_2);

                                                   ^

2 errors

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认的~

**Comment by feiceh** [comment]
非常感谢您的反馈，该问题已于第一时间进行了修复，力扣会定期更新，保障稳定和体验优化。
