### ISSUE TITLE
Incorrect interface - Solution interface for Java

### ISSUE THREAD

**Issue by aslamsayyed** [LeetCode-Feedback/LeetCode-Feedback#310]
https://leetcode.com/problems/delete-node-in-a-linked-list/
Should have public void deleteNode(ListNode node, int n) instead of public void deleteNode(ListNode node)

**Comment by CooperCooperCooper** [comment]
Hi @aslamsayyed ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by aslamsayyed** [comment]
not an issue I missed "given only access to that node."
