### ISSUE TITLE
1436. Destination City

### ISSUE THREAD

**Issue by anupamkarn** [LeetCode-Feedback/LeetCode-Feedback#3101]
#### Your LeetCode username

anupamkarn9726

#### Category of the bug
- [x] Question 

#### Description of the bug

According to the question, it's mentioned that "It is guaranteed that the graph of paths forms a line without any loop, therefore, there will be exactly one destination city." If we proceed with the mentioned line and submit code with return statement within if block(which basically means function only returns a result in a specific condition) and submit the code it throws an error by saying 
"Line 28: Char 5: error: non-void function does not return a value in all control paths [-Werror,-Wreturn-type]
    }
    ^
1 error generated."
Which doesn't make sense actually. To overcome this we need to pass and irrelevant 
```return ""```
we have to change the judge's validation to exclude this case or we can modify the language saying it can be possible that there can be no destination as well but we will be having it in all test cases.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    string destCity(vector<vector<string>>& paths) {
        
        map<string, int> m;
        
        for(auto v:paths){
            if(m.find(v[0])!=m.end()){
                m[v[0]]++;
            }
            else{
                m[v[0]]=1;
            }
            if(m.find(v[1])!=m.end()){
                continue;
            }
            else{
                m[v[1]]=0;
            }
        }
        
        for(auto v:m){
            if(v.second==0){
                return v.first;
            }
        }
// This line is irrelevant 
        return "";
    }
};
```

#### Language used for code

C++

#### Expected behavior

Ideally, it should not ask us to include 
```return ""``` 
in code.

**Comment by lc-kay** [comment]
Hi @anupamkarn 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@anupamkarn Our team has reviewed your report and ruled it invalid. We use a version of C++ which forces each non-void function to have a return statement. This is related to the compiler and we don't intend to change it. Thank you for your time.
