### ISSUE TITLE
Missing Test Case - 667. Beautiful Arrangement II

### ISSUE THREAD

**Issue by sufiyan0211** [LeetCode-Feedback/LeetCode-Feedback#3102]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

In the question (Beautiful Arrangement II) there are multiple answers possible and any of them should be accepted.
I got a different answer and it is correct according to the question but while I am submitting it, it is showing the answer not accepted to my solution.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<int> constructArray(int n, int k) {
        vector<int> ans(n);
        ans[0] = 1;
        unordered_set<int> s;
        s.insert(1);
        int t1 = k, t2 = k;
        
        for(int i=1;i<n;i++)
        {
            if(k>0)
            {
                int x = ans[i-1]+k;
                x = x%n;
                if(x == 0) x=n;

                if(s.find(x) != s.end())
                {
                    x = ans[i-1]-k;
                    x = x%n;
                    if(x == 0) x = n;
                }
                k--;
                ans[i] = x;
                s.insert(x);
            }
            else
            {
                t1 = t2;
                int x = ans[i-1]+t1;
                x=x%n;
                if(x == 0) x=n;
                while(s.find(x) != s.end())
                {
                    t1--;
                    x = ans[i-1]+t1;
                    x=x%n;
                    if(x == 0) x=n;
                }
                ans[i] = x;
                s.insert(x);
            }
        }
        
        return ans;
    }
};
```

#### Expected behavior

Input:
5
2
Output:
[1,3,4,5,2]
Expected:
[1,3,2,4,5]

My output list also has k=2 distinct positive integers

#### Screenshots

https://drive.google.com/file/d/1jmz43PLJZFZ1K4GgAQ-AebOCqrHakUf2/view?usp=sharing

**Comment by lc-kay** [comment]
Hi @sufiyan0211 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@sufiyan0211 Our team has reviewed your report and found to error to be in your code. The constructed array results in [2, 1, 1, 3] which has 3 distinct values, not 2. For further support, please refer to the problem discuss section. Thank you for your time.
