### ISSUE TITLE
Missing Test Case - 523. Continuous Subarray Sum

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#3103]
#### Your LeetCode username

igor84

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A solution is accepted but fails on the following test case:

[1, 3, 6, 0, 9, 6, 9]
7

#### Code you used for Submit/Run operation

```
public class Solution {
    public boolean checkSubarraySum(int[] nums, int k) {
        if(nums.length == 0) return false;
        if(k == 1 && nums.length > 1) return true;
        if(k < 0) {
            k = -1*k;
        }
        int sum = 0;
        for(int i : nums) {
            sum += i;
        }
        
        int mul = 1;
        if(k > 0) {
            mul = ((sum - (sum%k))/k);
        } 
        for (int i =0; i <= mul; i++) {
            if(sub(nums, i*k)) {
                return true;
            } 
        }
    
        return false;
    }
    
    private boolean sub(int[] nums, int k) {
        if(nums.length == 1) return false;
        int sum = nums[0];
        int start = 0;
        for(int i=1; i < nums.length; i++) {
            sum = sum + nums[i];

            if(sum > k) {
                sum = sum - nums[start];
                start++;
            }
            if(sum == k && (i - start + 1) >= 2) {
                return true;
            }
        }
        
        return false;
    }
    
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/114636927-2da8d980-9c96-11eb-8560-baceed096230.png)

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
