### ISSUE TITLE
Missing test case for 79. Word Search

### ISSUE THREAD

**Issue by evgeni-nabokov** [LeetCode-Feedback/LeetCode-Feedback#3104]
#### Your LeetCode username
evgeni-nabokov

#### Category of the bug
- [X] Missing Test Cases 

#### Description of the bug
Successfully submitted solution does not pass this test:
```
[["A","B","E"],["B","C","D"]]
"ABCDEB"
```
My code returns false, but correct answer is true.

#### Code you used for Submit/Run operation
https://leetcode.com/submissions/detail/480341244/

#### Language used for code
Python 3.

#### Expected behavior
Wrong Answer.

**Comment by lc-kay** [comment]
Hi @evgeni-nabokov 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @evgeni-nabokov 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
