### ISSUE TITLE
Clarify the definition of "All Products" - 1677. Product's Worth Over Invoices

### ISSUE THREAD

**Issue by l0latgithub** [LeetCode-Feedback/LeetCode-Feedback#3106]
#### Category of the bug
- [ ] Question
- [ ] Solution

#### Description of the bug

As the discussion in this link https://leetcode.com/problems/products-worth-over-invoices/discuss/968777/Question-about-%22ALL-PRODUCT%22

Should we use left join to show the total amount for "all products"? Some products might have 0 invoice for every column.

One available test case from leetcode

{"headers":{"Product":["product_id","name"],"Invoice":["invoice_id","product_id","rest","paid","canceled","refunded"]},"rows":{"Product":[[43,"pwmgaomdmaiyqup"],[95,"tdqcxpxbmx"],[80,"fpfqellka"],[92,"cxpipdpgym"]],"Invoice":[[358,92,9,11,47,36],[416,80,69,5,3,63],[472,80,52,36,53,75],[483,80,69,87,9,30],[63,43,93,26,36,97]]}}

#### Code you used for Submit/Run operation

```
SELECT p.name,
        IFNULL(SUM(i.rest), 0) as rest, 
        IFNULL(sum(i.paid),0) as paid, 
        IFNULL(sum(i.canceled),0) as canceled, 
        IFNULL(sum(i.refunded),0) as refunded
FROM Product as p
LEFT JOIN Invoice as i using (product_id)
GROUP BY p.name
ORDER BY p.name
```

#### Language used for code

MySQL

#### Expected behavior

Output
{"headers": ["name", "rest", "paid", "canceled", "refunded"], "values": [["cxpipdpgym", 9, 11, 47, 36], ["fpfqellka", 190, 128, 65, 168], ["pwmgaomdmaiyqup", 93, 26, 36, 97], **["tdqcxpxbmx", 0, 0, 0, 0]**]}

Expected
{"headers": ["name", "rest", "paid", "canceled", "refunded"], "values": [["cxpipdpgym", 9, 11, 47, 36], ["fpfqellka", 190, 128, 65, 168], ["pwmgaomdmaiyqup", 93, 26, 36, 97]]}

**Comment by lc-kay** [comment]
Hi @l0latgithub 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @l0latgithub 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
