### ISSUE TITLE
Missing Test Case - 626. Exchange Seats

### ISSUE THREAD

**Issue by EvanHarper** [LeetCode-Feedback/LeetCode-Feedback#3107]
#### Your LeetCode username

EvanHarper

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

The question asks to swap seat id numbers for pairs of students in the database. But the suggested and accepted "solutions" all involve performing mathematical calculations on individual id numbers, which is quite bogus. (Think about this logically for a second: how can we possibly have all the information to swap _two arbitrary seats_ as a function of _one single seat id_?) It only seems to work because of the additional, unstated and unrealistic assumption that the ids will always be in a contiguous block, and predictable relative to one another: 1, 2, 3, 4... becomes 2, 1, 4, 3 by adding and subtracting 1s in a pattern. But the instant you remove an id from the sequence everything breaks: 1, 5, 6, 8 would become 2, 6, 5, 7 for example.

#### Code you used for Submit/Run operation
```
# This is the top suggested "solution" from the solutions tab.
SELECT
    (CASE
        WHEN MOD(id, 2) != 0 AND counts != id THEN id + 1
        WHEN MOD(id, 2) != 0 AND counts = id THEN id
        ELSE id - 1
    END) AS id,
    student
FROM
    seat,
    (SELECT
        COUNT(*) AS counts
    FROM
        seat) AS seat_counts

ORDER BY id ASC;

# Try the test case:
# {"headers": {"seat": ["id","student"]}, "rows": {"seat": [[1,"Minimum"],[999,"Reproduction"]]}}
# and watch it fail.

```

#### Language used for code
MySQL

#### Expected behavior
A solution should be provided which does not fail on test cases that lack contiguous blocks of predictable ID numbers. The test cases used to evaluate submitted solutions should include non-contiguous ID numbers to catch out solutions that require them.

**Comment by lc-kay** [comment]
@EvanHarper Please provide a test case that includes a non-contiguous ID number. Thank you.

**Comment by EvanHarper** [comment]
It's in the comments to the code above, but:

 {"headers": {"seat": ["id","student"]}, "rows": {"seat": [[1,"Minimum"],[999,"Reproduction"]]}}
 
 the solution fails on this.

**Comment by lc-kay** [comment]
Hi @EvanHarper 
My apologies for missing that. I've relayed this issue to our team to investigate.

**Comment by LC-Pamela** [comment]
Hi @EvanHarper 
Thank you for your time. The team reviewed your report and noticed the testcase is invalid so we didn't add the test case. We appreciate your support!
