### ISSUE TITLE
1443. Minimum Time to Collect All Apples in a Tree | Incorrect Test-Case

### ISSUE THREAD

**Issue by sayantan94** [LeetCode-Feedback/LeetCode-Feedback#311]
**What kind of the bug**
Invalid Test-Case

**Describe the bug**
As per the question, the graph should should form a valid tree.
However the following test-case
**4
[[0,2],[0,3],[1,2]]
[false,true,false,false]**

violates the condition of a valid tree

**Expected behavior**
**[[0,2],[0,3],[1,2]] should represent a valid tree.**

**Comment by CooperCooperCooper** [comment]
Hi @sayantan94 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @sayantan94 ,
Thank you for your time. Since this test case was already contributed to us prior to this ticket, we will not be acting on this ticket.
