### ISSUE TITLE
【416. 分割等和子集】缺少数据范围

### ISSUE THREAD

**Issue by sunznx** [LeetCode-Feedback/LeetCode-Feedback#3110]
**你的 LeetCode 用户名**
sunznx

**Bug 类型**
- [ ] 题目

**描述**
题目 https://leetcode-cn.com/problems/palindrome-pairs/ 数据范围和英文版本不一致

**额外的上下文**
英文版本
```
Constraints:

1 <= nums.length <= 200
1 <= nums[i] <= 100
```

中文版本
```
注意:

每个数组中的元素不会超过 100
数组的大小不会超过 200
```

中文版的 *数组大小不会超过 200* 这里的范围是 `0<=nums.length<=200`

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
你好，当前题目数据范围已调整更新，力扣会定期更新，保障稳定和体验优化。
