### ISSUE TITLE
Missing Test Case - 1189. Maximum Number of Balloons

### ISSUE THREAD

**Issue by Noeuclides** [LeetCode-Feedback/LeetCode-Feedback#3111]
#### Your LeetCode username

Noeuclides

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My code somehow is passing all the checkers, but I tried one edge case and it fails.
Edge case that fails: "balllllllllllloooooooooon"

#### Code you used for Submit/Run operation

```
// Maximum Number of Balloons
from collections import Counter

class Solution:
    def maxNumberOfBalloons(self, text: str) -> int:
        text_counter = Counter(text)
        if not all([text_counter.get(l) for l in 'balon']):
            return 0
        if text_counter.get('l') < 2 or text_counter.get('o') < 2:
            return 0

        return min(text_counter.get('l') // 2, text_counter.get('o') // 2)
```

#### Language used for code

Python

#### Expected behavior

My code should not pass the checkers.

**Comment by lc-kay** [comment]
Hi @Noeuclides 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Noeuclides 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
