### ISSUE TITLE
Missing Test Case - 414. Third Maximum Number

### ISSUE THREAD

**Issue by geekpirate** [LeetCode-Feedback/LeetCode-Feedback#3115]
#### Category of the bug
- [ Third Maximum Number] Question
- [ ] Solution
- [Python ] Language
- [[1,2,3,5,6,4,2] ] Missing Test Cases 

#### Screenshots

![image](https://user-images.githubusercontent.com/51484115/114823303-54980600-9d91-11eb-843d-ec524ae732a9.png)

**Comment by lc-kay** [comment]
@geekpirate Please provide the accepted code that this test case fails on. Thank you!

**Comment by LC-Pamela** [comment]
Hi @geekpirate  ,
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
