### ISSUE TITLE
Missing Test Case - 41. First Missing Positive

### ISSUE THREAD

**Issue by dhruvbansal49** [LeetCode-Feedback/LeetCode-Feedback#3116]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@dhruvbansal49 Please provide the missing test case and the accepted code. After the necessary information is provided, I will re-open the ticket. Thank you for your understanding.
