### ISSUE TITLE
347. Top k Frequent Elements -

### ISSUE THREAD

**Issue by The-KarateKid** [LeetCode-Feedback/LeetCode-Feedback#312]
**What kind of the bug**
- [ X ] problem
- [ X ] solution
- [ ] language

**Describe the bug**
The problem clearly states:
> Your algorithm's time complexity must be better than O(n log n), where n is the array's size.

The solution's runtime is O( n log(k) ), but as the top comment on the solution page says:
> O(n log k) is not better than O(n log n), since we have no reason to think k isn't, say, n/2.

Additionally, since both N and K are constants they amount to the same thing in terms of calculating runtime.

**Expected behavior**
Please update either the problem or solution to be consistent to its own requirements.

**Comment by CooperCooperCooper** [comment]
Hi @The-KarateKid ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @
Thank you for your time. The article has been rewritten and published. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
