### ISSUE TITLE
Missing Test Case - 1557. Minimum Number of Vertices to Reach All Nodes

### ISSUE THREAD

**Issue by ayushi099** [LeetCode-Feedback/LeetCode-Feedback#3120]
#### Your LeetCode username

ayushi02

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

if we have cyclic directed graph then in-degree  approach will not work.
cyclic directed graph test cases are mising.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@ayushi099 Please provide the test case you wish to add to the test case set. And the code that it will fail. Thank you!

**Comment by LC-Pamela** [comment]
Hi @ayushi099  ,
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
