### ISSUE TITLE
509. Fibonacci Number

### ISSUE THREAD

**Issue by 16vanshika** [LeetCode-Feedback/LeetCode-Feedback#3121]
class Solution {
    public int fib(int n) {
        if(n==0)
            return 0;
        else if(n==1)
            return 1;
        else
        {
           int f=0,s=1,t=0;
            for (int i=2;i<=n;i++)
            {
                t=f+s;
                f=s;
                s=t;
            }
            return t;
        }
    }
}

**Comment by lc-kay** [comment]
@16vanshika Please post your solution in the problem discuss section. https://leetcode.com/problems/fibonacci-number/solution/
