### ISSUE TITLE
Missing Test Case - 204. Count Primes

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#3126]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets TLE on the following testcase:
5000000

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int countPrimes(int n) {
        if (n < 3) return 0;
        if (n == 10000)
            return 1229;
        if (n == 499979)
            return 41537;
        if (n == 999983)
            return 78497;
        if (n == 1500000)
            return 114155;
        vector<int> prime = {2};
        prime.reserve(n);
        for (int i = 3; i < n; i++)
        {
            int j = 0;
            for (; j < prime.size(); j++)
            {
                if (i % prime[j] == 0) break;
            }
            if (j == prime.size()) prime.push_back(i);
        }
        return prime.size();
    }
};
```

#### Language used for code

C++

#### Expected behavior

The code gets TLE.

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pamela** [comment]
Hi @hqztrue 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
