### ISSUE TITLE
162. Find Peak Element

### ISSUE THREAD

**Issue by pkrc267** [LeetCode-Feedback/LeetCode-Feedback#313]
**What kind of the bug**
- [x] problem
- [x] solution
- [x] language

**Describe the bug**
The problem clearly states:

> Your solution should be in logarithmic complexity.

but O(n) solutions are being accepted.

**Language**
C++

**The code you submit/run**
```
// 162. Find Peak Element
class Solution {
public:
    int findPeakElement(vector<int>& nums) {
        if(nums.size() == 1) return 0;
        
        if (nums.size()==2) {
            if (nums[0]>nums[1]) return 0;
            else return 1;
        }
        
        if (nums[nums.size()-1] > nums[nums.size()-2]) return nums.size()-1;
        
        for(int i = 0; i<nums.size()-1; i++)
            if(nums[i]>nums[i+1])
                return i;
        return -1;
    }
};
```

**Expected behavior**
The solution should have been rejected as it's not logarithmic, but linear.

**Comment by CooperCooperCooper** [comment]
Hi @pkrc267 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @pkrc267 ,
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
