### ISSUE TITLE
Missing test case: 1209. Remove All Adjacent Duplicates in String II

### ISSUE THREAD

**Issue by ikrets** [LeetCode-Feedback/LeetCode-Feedback#3133]
#### Your LeetCode username
mrchair2170

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Solutions with O(N^2) runtime are accepted on this problem despite N=10^5 being enough to TLE a quadratic solution.

#### Code you used for Submit/Run operation

```python
class Solution:
    def removeDuplicates(self, s: str, k: int) -> str:
        remove = []
        ## Generating possible duplicates
        for ch in set(s):
            remove.append(ch*k)
            
        old,new = s,s
        while True:
            for candidate in remove:
                new = new.replace(candidate,"")
            if len(old) == len(new):
                break
            old = new        
        return old
```

#### Language used for code

Python

#### Expected behavior

This code is expected to TLE, as it has O(N^2) complexity with N up to 10^5.

I am attaching a testcase with a string of length 99996 that takes the algorithm above ~13 seconds to solve.

[f.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6326528/f.txt)

**Comment by lc-kay** [comment]
Hi @ikrets 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pamela** [comment]
Hi @ikrets 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
