### ISSUE TITLE
Missing Test Case - 1684. Count the Number of Consistent Strings

### ISSUE THREAD

**Issue by trekkieeric** [LeetCode-Feedback/LeetCode-Feedback#3134]
#### Your LeetCode username

trekkieeric

#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Any test case past test case 3 is looking for the inverse answer. The question asks to return all consistent strings. At least test case 4 is asking for all inconsistent strings. 

#### Code you used for Submit/Run operation

```
// Count the Number of Consistent Strings
class Solution:
    def countConsistentStrings(self, allowed: str, words: List[str]) -> int:
        
        allowed = list(allowed) 
        
        counter = 0

        j = 0

        for word in words:
            for j in range(len(word)):
                if word[j] not in allowed:
                    counter += 1
                    j = 0
                else:
                    j += 1

        return(len(words) - counter)
```

#### Language used for code

Python 3

#### Expected behavior

I would expect to return the total number of words in the list - the number of bad words. This would give the number of good words. 

Instead, the test case is asking for the number of bad words.

**Comment by LC-Pamela** [comment]
Hi @trekkieeric 
Thank you for reaching out to us. Can you please provide more explanation on the issue? Please check out [this post](https://leetcode.com/discuss/general-discussion/526802/File-Problem-and-Solution-Content-Issues-to-Our-GitHub-Public-Feedback-Repo-Now!) for the valid content report.
