### ISSUE TITLE
Wrong output.

### ISSUE THREAD

**Issue by jorjis212** [LeetCode-Feedback/LeetCode-Feedback#3135]
#### Your LeetCode username
 _xorxis122_

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
_Got unexpected result in problem's run engine but not in any(Pycharm, vscode) editor._

#### Code you used for Submit/Run operation

```
def isValid(s):
    try:
        eval(s)
        if "()" == s or "{}" == s or "[]" == s:
            return "true"
    except SyntaxError:
        return "false"
    except ValueError:
        return "true"

print(isValid("(}"))
```

#### Language used for code
**Python3**

#### Expected behavior
_for testcase"( ]" it should print **falase** but **true** were shown_

**Comment by LC-Pamela** [comment]
Hi @jorjis212 
Thank you for reaching out to us. Can you please provide the submission link? I received Runtime Error for the code you provided in the ticket.
