### ISSUE TITLE
Problem description - 378. Kth Smallest Element in a Sorted Matrix

### ISSUE THREAD

**Issue by rwalkeriv** [LeetCode-Feedback/LeetCode-Feedback#3137]
#### Your LeetCode username

rwalkeriv

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

problem description says "non-degreasing order" when "non-decreasing order" is meant

**Comment by LC-Pamela** [comment]
Hi @rwalkeriv 
Thank you for reaching out to us. Looks like the issue was resolved thanks to other users' report. Please let me know if it's not the case.
