### ISSUE TITLE
Missing Test Case - 169. Majority Element

### ISSUE THREAD

**Issue by sarthaksaklecha** [LeetCode-Feedback/LeetCode-Feedback#3138]
#### Your LeetCode username
sarthaksaklecha

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

There is a missing test case in the Majority element question.
My solution got accepted but there's a test case that breaks my code which is not included in the test cases provided by leetcode.
I'm contributing this to improve the test cases so that faulty code won't get accepted in future.

#### Code you used for Submit/Run operation

```
var majorityElement = function(nums) {
    if(nums.length<=2) return nums[0]
    let prev=null
    let curr
    // efejfiejfiejifjei
    let count=0
    let maxCount=0;
    let majorityElement,index
    for(let i=0;i<nums.length*2;i++){
        index = i;
        if(i>=nums.length) index = i-nums.length; 
        let curr = nums[index]
        if(curr===prev){
            count++;
            if(count>=maxCount){
                maxCount=count;
                majorityElement = curr;
            }
        }else{
            prev = curr;
            count=1;
        }
    }
    return majorityElement
};
```

#### Language used for code
javascript

#### Expected behavior
input : [1,3,1,1,4,1,1,5,1,1,6,2,2]
should return 1 as it is the majority element
but the code above returns 2 but is still accepted when submitted

**Comment by LC-Pamela** [comment]
Hi @sarthaksaklecha 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pamela** [comment]
Hi @sarthaksaklecha 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
