### ISSUE TITLE
328. Incorrect annotation for «Odd Even Linked List» problem

### ISSUE THREAD

**Issue by bryzgaloff** [LeetCode-Feedback/LeetCode-Feedback#314]
**What kind of the bug**
- [ ] problem
- [x] solution
- [ ] language
- [x] tests
- [x] solution template

**Describe the bug**
The problem 328 «Odd Even Linked List» has incorrect code annotation for Python 3.

Solution template:
```python
class Solution:
    def oddEvenList(self, head: ListNode) -> ListNode:
```

However there is a test for an empty list present: `[]`

This means that the annotation has to be as follows:
```python
class Solution:
    def oddEvenList(self, head: Optional[ListNode]) -> Optional[ListNode]:
```

This makes the `head` to be possibly `None` for an empty list.

**what language is your code written in**
Python 3

**The code you submit/run**

Please see the comments.

```python
class Solution:
    def oddEvenList(self, head: ListNode) -> ListNode:
        lastOdd = head
        # in the condition of a while loop I assume that 
        #   lastOdd is not None since it points to 
        #   non-optional head: ListNode
        while lastOdd.next is not None \
                and lastOdd.next.next is not None:
        # but since an empty list is a valid input head
        #   has to be Optional and I have to check
        #   whether lastOdd is not None itself too
            lastOdd = lastOdd.next.next
        odd = head
        lastMovedEven = lastOdd
        while odd is not lastOdd:
            even = odd.next
            odd.next = even.next
            even.next = lastMovedEven.next
            lastMovedEven.next = lastMovedEven = even
            odd = odd.next
        return head
```

**Expected behavior**
The code without `lastOdd is not None` check has to pass all the tests since `head` (and `lastOdd`) can not be `None`.

**Comment by CooperCooperCooper** [comment]
Hi @bryzgaloff ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @bryzgaloff ,

Thank you for your time. Our team has reviewed this suggestion thoroughly. Since the change will affect many technical branches in the system, we will keep the issue as-is for now and keep the suggestion with us for future improvement.
