### ISSUE TITLE
1246. 删除回文子数组

### ISSUE THREAD

**Issue by wangtao174** [LeetCode-Feedback/LeetCode-Feedback#3141]
**jockertao**
填写你登录 LeetCode（中国区）的用户名

**Bug 类型**
 
- [ ] 题解
 

**描述**
描述你遇到的 bug

**你使用的语言**
C++

**你提交或者运行的代码**
```
class Solution {
public:
    int minimumMoves(vector<int>& arr) {
        int len = arr.size();
        vector<vector<int>> dp(len,vector<int>(len,1));
        for(int j=0;j<len;j++){
            for (int i=j-1;i>=0;i--){
                if(arr[i]==arr[j]){
                    if(j-i<3) dp[i][j]=1;
                    else dp[i][j]=dp[i+1][j-1];
                }
                else {
                    if(j-i<3) dp[i][j]=j-i+1;
                    else {
                        dp[i][j]=j-i+1;
                        for(int k=i;k<j;k++){
                            dp[i][j]=min(dp[i][j],dp[i][k]+dp[k+1][j]);
                        }
                    }
                }
            }
        }
        return dp[0][len-1];
    }
};
```

**期望行为**
通过第92个案例[4,1,14,16,15,18,19,17,10,8,10,4,19,17,14,17,2,1,14,11]

**屏幕截图**
**额外的上下文**
添加额外的上下文信息

**Comment by wangtao174** [comment]
运行结果可以过，提交结果过不了，在自己的编译器上也可以过

**Comment by feiceh** [comment]
你好，如果出现测试用例结果和提交结果不一致的情况，可以再仔细检查并调试一下代码，或点击这里：「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」 获得更多帮助。

同时也可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
