### ISSUE TITLE
编译BUG？

### ISSUE THREAD

**Issue by ComingPeopleHW** [LeetCode-Feedback/LeetCode-Feedback#3144]
**comingpeople**
填写你登录 LeetCode（中国区）的用户名

**编译**
- [二叉树直径 ] 题目
- [x] 题解
- [ ] 编程语言

**通过测试用例输出的结果与oj结果不一致？具体看下图**
描述你遇到的 bug

**你使用的语言**
Golang

**屏幕截图**
![image](https://user-images.githubusercontent.com/29273366/115108427-f8a4cb80-9fa2-11eb-849d-46caa8c0f1a1.png)

**Comment by feiceh** [comment]
你好，建议再仔细检查并调试一下代码，推荐阅读：「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」 获得更多帮助。

同时也可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
