### ISSUE TITLE
Missing Test Case - 1154. Day of the Year

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#3146]
#### Your LeetCode username

igor84

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A solution is accepted but fails on the following test case:

"2000-08-31"

#### Code you used for Submit/Run operation

```
class Solution {
    public int dayOfYear(String date) {
     int [] days = new int[]{31,28,31,30,31,30,31,31,30,31,30,31};
     
      int year = Integer.parseInt(date.substring(0,4));
      int month = Integer.parseInt(date.substring(5,7));
      int day = Integer.parseInt(date.substring(8,10));
        
      boolean isLeapYear= isLeapYear(year);  
        
     if(isLeapYear)
         days[1]=29;
      
      int ans=day;
      for(int i=0;i<month-1;i++){ 
        ans+=days[i] ;
      }
       
       return ans;
    }
    
    
    private boolean isLeapYear(int year){
        if(year%4 ==0 && year%100!=0){
            return true;
        }
        return false;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/115115540-05093400-9f63-11eb-8603-fed3faea5958.png)

**Comment by LC-Pamela** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pamela** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
