### ISSUE TITLE
Missing Test Case - 167. Two Sum II - Input array is sorted

### ISSUE THREAD

**Issue by rajatrj20** [LeetCode-Feedback/LeetCode-Feedback#3148]
#### Your LeetCode username

rajatrj20

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

The problem lacks test cases for checking if indices of same number are being return when two different numbers are present in the list

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution:
    def twoSum(self, numbers: List[int], target: int) -> List[int]:
        seen = {}
        for i in range(len(numbers)):
            compliment = target - numbers[i]
            
            if compliment in seen:
                return [seen[compliment]+1, i+1]
            
            seen[numbers[i]] = i
        return []
```

#### Language used for code

python

#### Expected behavior

If we run above code, with input-
[3,5,5,7]
10

it will output -> 
[2,3]

instead correct answer should be - [1,4]

But it passed all test cases. so either testcases should be updated or description should be changed from this-
You may assume that each input would have exactly one solution and you may not use the same element twice.

**Comment by NiklasLehnfeld** [comment]
btw why all the testcases and examples start counting the indices from 1 here? Is there some reason I don't see?

**Comment by LC-Pamela** [comment]
Hi @NiklasLehnfeld 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pamela** [comment]
Hi @rajatrj20 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by Shen-Jing** [comment]
Hello @LC-Pamela,

There is currently a test case:
```python
[1,2,3,4,4,9,56,90]
8
```
And its answer is `[4,5]`.

This test case and this issue have been contradictory.
Finally, it result in another issue #3206.


Thanks.
Shen-Jing
