### ISSUE TITLE
Missing test case: 1332. Remove Palindromic Subsequences

### ISSUE THREAD

**Issue by daidai21** [LeetCode-Feedback/LeetCode-Feedback#3149]
#### Your LeetCode username

https://leetcode.com/daidai21/

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

need add test case input: empty string

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int removePalindromeSub(string s) {
        if (s.empty()) return 0; // BUG: change return 1
        for (int i = 0; i < s.size() / 2; ++i) {
            if (s[i] != s[s.size() - i - 1]) return 2;
        }
        return 1;
    }
};



```

#### Language used for code

C++

#### Expected behavior

if input s is empty, return 0 is successful, return 1 is failed. (but return 1 also succeed now)

#### Additional context

```cpp
class Solution {
public:
    int removePalindromeSub(string s) {
        if (s.empty()) {
            assert(false);
            return 0;
        }
        for (int i = 0; i < s.size() / 2; ++i) {
            if (s[i] != s[s.size() - i - 1]) return 2;
        }
        return 1;
    }
};

```

I submit this code, result is passed.

```txt
Runtime: 0 ms, faster than 100.00% of C++ online submissions for Remove Palindromic Subsequences.
Memory Usage: 6 MB, less than 99.65% of C++ online submissions for Remove Palindromic Subsequences.
```

**Comment by LC-Pamela** [comment]
Hi @daidai21 
Thank you for reaching out to us. It looks like an empty string is an invalid test case. Please let me know in case I missed anything.
