### ISSUE TITLE
Missing Test Case - 41. First Missing Positive

### ISSUE THREAD

**Issue by shubham3030** [LeetCode-Feedback/LeetCode-Feedback#3150]
#### Missing Test Case
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Constraints of question says array of integers can be empty (0 <= nums.length <= 300) but when tried to run the test case with [] , it gives invalid test case error.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int firstMissingPositive(vector<int>& nums) {
        int n = nums.size();
        if(n==0)
            return 1;
        bool flag = false;
        
        for(int i=0;i<n;i++){
            if(nums[i]<=0)
                nums[i] = 1;
            else if(nums[i] == 1)
                flag = true;
        }
        
        if(!flag)
            return 1;
        
        for(int i=0;i<n;i++){
            int index = abs(nums[i])-1;
            if(index<n && nums[index]>0)
                nums[index]*=-1;
        }
        for(int i=0;i<n;i++){
            if(nums[i]>0)
                return i+1;
        }
        return n+1;
            
    }
};
```

#### Screenshots
![1](https://user-images.githubusercontent.com/24573051/115123010-af6f6e80-9fd8-11eb-9a5d-626827a5e19e.JPG)
![2](https://user-images.githubusercontent.com/24573051/115123013-b1393200-9fd8-11eb-84bf-f0cec53d7b16.JPG)

**Comment by LC-Pamela** [comment]
Hi @shubham3030 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pamela** [comment]
Hi @shubham3030 
Thank you for your time. We've fixed the constraints of the problem. We appreciate your support!
