### ISSUE TITLE
Missing Test Case - 646. Maximum Length of Pair Chain

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#3152]
#### Your LeetCode username

igor84

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A solution is accepted but fails on the following test case:

[[1,2]]

#### Code you used for Submit/Run operation

```
public class Solution {
    public int findLongestChain(int[][] pairs) {
        sort(pairs);
        
        int max=0;
        for(int i=1;i<pairs.length;i++){
            int last=pairs[0][1];
            int tem=1;
            for(int j=i;j<pairs.length;j++){
                if(pairs[j][0]>last){
                    last=pairs[j][1];
                    tem++;
                }
            }
            max=Math.max(max,tem);
        }
        
        return max;
        
        
    }
    
    public void sort(int[][] pairs){
        boolean again=true;
        for(int i=0;i<pairs.length&&again;i++){
            again=false;
            for(int j=pairs.length-1;j>i;j--){
                if(pairs[j][1]<pairs[j-1][1]){
                    int[] tem=pairs[j];
                    pairs[j]=pairs[j-1];
                    pairs[j-1]=tem;
                    again=true;
                }
                
            }
        }
        
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/115129536-e16ed980-9fb4-11eb-912f-739c71710d07.png)

**Comment by LC-Pamela** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pamela** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
