### ISSUE TITLE
Missing Test Case - 1834. Single-Threaded CPU

### ISSUE THREAD

**Issue by yangjufo** [LeetCode-Feedback/LeetCode-Feedback#3153]
#### Your LeetCode username

SkyWalker12138

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Test cases for idle CPU time are insufficient. For example, [[1,2],[10,4],[14,2],[14,1]] is not included.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<int> getOrder(vector<vector<int>>& tasks) {
        vector<int> res;        
        auto comparator = [](pair<int, int> left, pair<int, int> right) {
            if (left.second == right.second) return left.first > right.first;
            return left.second > right.second;
        };                        
                
        priority_queue<pair<int, int>, vector<pair<int, int>>, decltype(comparator)> start(comparator), curr(comparator);
        for (int i = 0; i < tasks.size(); i++) {            
            start.push({i, tasks[i][0]});
        }        
        long time = -1;        
        while (!start.empty() || !curr.empty()) {            
            while (!start.empty() && (start.top().second <= time || curr.empty())) {                
                if (time < 0) time = start.top().second;
                curr.push({start.top().first, tasks[start.top().first][1]});
                start.pop();
            }                        
            
            if (!curr.empty()) {                
                time += curr.top().second;
                res.push_back(curr.top().first);
                curr.pop();                        
            }            
        }
        return res;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The solution should not be accepted since it fails on the test case.

#### Screenshots

![Screenshot](https://raw.githubusercontent.com/yangjufo/LeetCode/7212074f894c59780595c93ce8a3afde08716203/Screenshot%202021-04-17%20224547.png)

**Comment by LC-Pamela** [comment]
Hi @yangjufo 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pamela** [comment]
Hi @yangjufo 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
