### ISSUE TITLE
Incorrect Difficulty - 1835. Find XOR Sum of All Pairs Bitwise AND

### ISSUE THREAD

**Issue by extremistenigma** [LeetCode-Feedback/LeetCode-Feedback#3154]
#### Your LeetCode username

qwerty

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The problem 1835. Find XOR Sum of All Pairs Bitwise AND does not match the difficulty level of a Hard problem. In many languages, it has a one-line solution. In Weekly Contest 237, it did not seem worth 6 points given that the 5-point Medium problem (1834. Single-Threaded CPU) had a much worse acceptance rate. An example solution is posted below.

#### Code you used for Submit/Run operation
```
 def getXORSum(self, A, B):
     return reduce(operator.xor, A) & reduce(operator.xor, B)
```

#### Language used for code
Python

#### Expected behavior
Question should be considered a Medium problem and its points in the contest should be 4 or 5.

**Comment by LC-Pamela** [comment]
Hi @extremistenigma 
Thank you for reaching out to us. I've relayed this your feedback to our team. We'll adjust the difficulty if needed.
