### ISSUE TITLE
Missing Test Case - 1834. Single-Threaded CPU

### ISSUE THREAD

**Issue by codingrealmdinesh** [LeetCode-Feedback/LeetCode-Feedback#3155]
#### Your LeetCode username

LeetCode ID: DineshKumarSahu

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ T] Missing Test Cases 

#### Description of the bug

The below solution is getting accepted.
For input [100,100], [1000000000, 1000000000] my solution passed. Since I put a loop checker. And checking if I am getting stuck in while loop then it will come out. But it will not work if there are multiple such values where the current time stamp is much less than the next time stamp.
Test case I suggest you guys to add: [[100,100], [500,100], [1000,100], [10000,100], [100000,100]]
For the above input, my code will fail. 
Since this test case is not present, my solution is getting accepted.

#### Code you used for Submit/Run operation

```
class Solution:
    def getOrder(self, tasks: List[List[int]]) -> List[int]:
        for i in range(len(tasks)):
            tasks[i] = [tasks[i][0],tasks[i][1],i]
        tasks.sort(key = lambda x: (x[0],x[1]))
        cpu_timestamp = tasks[0][0] + tasks[0][1]
        temp = []
        res = [tasks[0][2]]
        #print(tasks)
        i = 1
        loopchecker, previ = 0, 0
        while i<len(tasks):
            if cpu_timestamp < tasks[i][0] and temp:
                burst,index,arri = heapq.heappop(temp)
                res.append(index)
                cpu_timestamp += burst
            if cpu_timestamp >=tasks[i][0]:
                heapq.heappush(temp, [tasks[i][1],tasks[i][2],tasks[i][0]])
                i+=1
            if i == previ: 
                loopchecker+=1
                if loopchecker > 50:
                    break
            previ = i
            #print(temp, res, cpu_timestamp)
        #print("in while loop")
        while temp:
            burst,index,arri = heapq.heappop(temp)
            res.append(index)
            #print(temp, res, cpu_timestamp)
        if loopchecker>50:
            heapq.heappush(temp, [tasks[i][1],tasks[i][2],tasks[i][0]])
            burst,index,arri = heapq.heappop(temp)
            res.append(index)
            cpu_timestamp += burst
        return res
```

#### Language used for code
Python3

#### Expected behavior

I expected that answer would fail. but it passed. 

#### Screenshots

![image](https://user-images.githubusercontent.com/51681898/115137031-37895e80-a041-11eb-9510-3412b0076919.png)

#### Additional context

It should fail

**Comment by LC-Pamela** [comment]
Hi @codingrealmdinesh 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pamela** [comment]
Hi @codingrealmdinesh 
Thank you for your time. It's likely that the problem is updated thanks to other users' contribution so your code has already failed. We appreciate your support!
