### ISSUE TITLE
724. Find Pivot Index

### ISSUE THREAD

**Issue by agatagruza** [LeetCode-Feedback/LeetCode-Feedback#316]
**What kind of the bug**
- [ ] problem
- [ ] solution
- [ ] language

**Describe the bug**
Misleading description of the problem. 

**what language is your code written in**
Python3

**The code you submit/run**
It should be stated _"pivot index as the index where the sum of `ALL` the numbers to the left of the index is equal to the sum of the `REMAINING` numbers to the right of the index."_ If not specify, then below array [0, 1, 7, 3, 6, 5, 6,1] has a pivot at index 4 as based on the current problem statement it meets all the conditions for being a pivot. Which is not true. 
pivot = 0 +1+7+3 = 5+6

**Expected behavior**
Clarify the problem by adding `ALL` in the description. 

**Screenshots**

**Additional context**

**Comment by CooperCooperCooper** [comment]
Hi @agatagruza ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @agatagruza ,
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.

**Comment by agatagruza** [comment]
Thank you @CooperCooperCooper for the info.
