### ISSUE TITLE
Missing Test Case - 1833. Maximum Ice Cream Bars

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#3160]
#### Your LeetCode username

igor84

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A solution is accepted but fails on the following test case:

[1833_test_case.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6331815/1833_test_case.txt)

#### Code you used for Submit/Run operation

```
import java.util.*;
class Solution {
    public int maxIceCream(int[] costs, int coins) {
       Arrays.sort(costs);
       int res=0;
       int sum=0;
       if(coins<costs[0])
           return 0;
       if(coins>costs[costs.length-1]*costs.length)
           return costs.length;
       for(int i=0;i<costs.length;i++){
           sum+=costs[i];
           if(sum<=coins){
              res++;
           }
           else break;
       }
       return res;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/115154608-cdc18280-a049-11eb-9341-94ec6f4bc213.png)

**Comment by LC-Pamela** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pamela** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
