### ISSUE TITLE
Buggy Test Case Input - 590. N-ary Tree Postorder Traversal

### ISSUE THREAD

**Issue by IvanKelber** [LeetCode-Feedback/LeetCode-Feedback#3162]
#### Your LeetCode username
ikelber

#### Category of the bug
- [X ] Question
- [ ] Solution
- [ ] Language
- [X ] Missing Test Cases 

#### Description of the bug
When creating my own test case I found an issue with the OJ's construction of the tree.  Specifically it looks like spaces in the test case input causes odd behavior.  My guess is that the OJ uses some split function on commas and is trying to force whatever it gets into an integer.

#### Code you used for Submit/Run operation

Consider the test case `[1, null, 3]` (with the spaces)
and compare it to the test case `[1,null,3]` (without the spaces)

The former will create a root with a value of 1 and three children, each of which has a value of 0.
The latter will create a root with a value of 1 and one child with a value of 3.
```
func postorder(root *Node) []int { 

	order := make([]int, 0)

	stack := []*Node{}
    if root != nil {
        stack = append(stack, root)
    }
	for len(stack) > 0 {
		pop := stack[len(stack)-1]
		stack = stack[:len(stack)-1]
		for _, node := range pop.Children {
			stack = append(stack, node)
		}
		order = append(order, pop.Val)
	}
	return reverse(order)
}

func reverse(vals []int) []int {
	for i := 0; i < len(vals)/2; i++ {
		vals[i], vals[len(vals)-1-i] = vals[len(vals)-1-i], vals[i]
	}
	return vals
}
```

#### Language
Golang

#### Expected behavior
I expected the comma-space delimited test case to construct the same tree as the comma delimited test case.

#### Additional context
My code passes all of the tests since they are probably all creating without comma-space delimiters.  However, the "Expected Answer" from the OJ is correct.  It implies that one place in the OJ code we are constructing the tree properly with comma-space delimiters and in the other place we are not.

**Comment by LC-Pamela** [comment]
Hi @IvanKelber 
Thank you for reaching out to us. Please follow the format we provide to construct test cases.
