### ISSUE TITLE
Missing Test Case - 1790. Check if One String Swap Can Make Strings Equal

### ISSUE THREAD

**Issue by sharadbhat** [LeetCode-Feedback/LeetCode-Feedback#3163]
#### Your LeetCode username
sharadbhat

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
For this problem, the unique characters used in both the strings must be equal and the number of mismatched positions must be 0 or 2. However, if the number of mismatched positions is 1 and the unique characters are same, the test case is supposed to return false. This is not being checked.

Example test case:
```
"abca"
"abcc"
```
As you can see, the characters being used in both strings in "a", "b" and "c". The number of mismatched positions in 1, i.e., the last position.

#### Code you used for Submit/Run operation
```py
# Code is from Discuss tab posted by another user
class Solution:
    def areAlmostEqual(self, s1: str, s2: str) -> bool:
        if not set(s1) == set(s2):
            return False
        return sum(1 for i in range(len(s1)) if not s1[i] == s2[i]) < 3
```

This code is Accepted on Submit but fails the previously mentioned test case.

#### Language used for code
Python3

#### Expected behavior
The provided code should fail on Submit but is Accepted. Since this kind of test case is not being checked.

#### Screenshot
![Screenshot_2021-04-21 Check if One String Swap Can Make Strings Equal - LeetCode](https://user-images.githubusercontent.com/14030627/115448738-afb97500-a237-11eb-9f57-9a49d320a42c.png)

**Comment by LC-Pamela** [comment]
Hi @sharadbhat 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pamela** [comment]
Hi @sharadbhat 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
