### ISSUE TITLE
Hint 3 incorrect ? - 1827. Minimum Operations to Make the Array Increasing

### ISSUE THREAD

**Issue by axelu** [LeetCode-Feedback/LeetCode-Feedback#3165]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases
- [x] Hint(s)   

#### Description of the bug

Hint 3 states 

> Iterate on i and set nums[i] = min(nums[i-1]+1, nums[i]).  

I believe it should read instead:  
Iterate on i and set nums[i] = max(nums[i-1]+1, nums[i]).

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int minOperations(vector<int>& nums) {
        int n = nums.size();
        if( n == 1 ) return 0;
        int ans = 0,t;
        for(int i = 1; i < n; ++i) {
            t = nums[i];
            nums[i] = max(nums[i-1]+1,nums[i]);
            ans += nums[i]-t;
        }
        return ans;
    }
};
```

#### Language used for code
C++

**Comment by LC-Pamela** [comment]
Hi @axelu 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
