### ISSUE TITLE
Missing Test Case - 268. Missing Number

### ISSUE THREAD

**Issue by shivUE183100** [LeetCode-Feedback/LeetCode-Feedback#3168]
class Solution {
public:
    
    int missingNumber(vector<int>& nums)
    {
        int xor_n1=0,xor_n2=0;
        for(int i=0;i<nums.size();i++)
        {
            xor_n1=xor_n1 ^nums[i];
        }
        for(int i=0;i<=nums.size();i++)
        {
            xor_n2=xor_n2 ^ i;
        }
        return xor_n1^xor_n2;
        
    }
    
    
    OR
    
    int missingNumber(vector<int>& nums) {
        
        int n=nums.size();
        if(n==0)
        {
            return 0;
        }
        int s=0;
        int s1=n*(n+1)/2;
        for(int i=0;i<n;i++)
        {
            s=s+nums[i];
        }
        return s1-s;
   
};

**Comment by LC-Pamela** [comment]
Hi @shivUE183100 
Thank you for reaching out to us. Please update the format and provide more explanations to help us understand the issue you're trying to report.
