### ISSUE TITLE
178. 分数排名 运行报错

### ISSUE THREAD

**Issue by chenpy26** [LeetCode-Feedback/LeetCode-Feedback#317]
** Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
之前通过的代码再运行会报错

**你使用的语言**
MySQL

**你提交或者运行的代码**
```
select a.Score as Score,
(select count(distinct b.Score) from Scores b where b.Score >= a.Score) as Rank
from Scores a
order by a.Score DESC
```

**期望行为**
运行正确且通过

**屏幕截图**
![pic](https://img-blog.csdnimg.cn/20200517110025551.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认的～

**Comment by feiceh** [comment]
你好，我们验证力扣平台是没有问题的。这个是 AS 写错地方了，建议再仔细调试一下代码。后续刷题学习中遇到困难，可通过阅读「题解」解决做题中的一些困惑，看看其他小伙伴的解题思路哦。
