### ISSUE TITLE
 Missing test case - 14. Longest Common Prefix

### ISSUE THREAD

**Issue by MichaelHGitHub** [LeetCode-Feedback/LeetCode-Feedback#3170]
#### Your LeetCode username
kindsword

#### Category of the bug
[ ] Missing Test Cases 

#### Description of the bug
Missing test case such that a wrong answer can pass the tests. 
In specific, for the below test case: the following  code (in the Code used for Sumit) returns "flower" and the code passed. 
Test case:  input : ["flower", "flawer", "flvwer", "flower"]
                             expected output = "fl"
                             actual output of my code: "flower"

#### Code you used for Submit/Run operation

```
// Problem 14: Longest Common Prefix
string longestCommonPrefix(vector<string>& strs)
{
    if (strs.size() < 1)
    {
        return "";
    }
    else if (strs.size() == 1)
    {
        return strs[0];
    }

    int shift_count = 0;
    int sub_index = 0;
    int last_pass_index = -1;

    while (sub_index > last_pass_index && sub_index < strs[0].length())
    {
        bool pass = true;

        for (int i = 1; i < strs.size(); i++)
        {
            if (sub_index >= strs[i].length() ||
                strs[i].at(sub_index) != strs[0].at(sub_index))
            {
                pass = false;
                break;
            }
        }

        if (pass)
        {
            last_pass_index = sub_index;

            if (sub_index + (1 << shift_count) >= strs[0].length())
            {
                shift_count = 0;
            }

            sub_index = sub_index + (1 << shift_count);
            shift_count++;
        }
        else
        {
            // Note this exit condition: if the current check is right next to 
            // last_pass and not successful, should exit here.
            if (sub_index - last_pass_index < 2)
            {
                break;
            }
            else
            {
                shift_count = 0;
                sub_index = last_pass_index + (1 << shift_count);
            }
        }
    }

    return strs[0].substr(0, last_pass_index + 1);
}
```

#### Language used for code
C++

#### Expected behavior
The above code shouldn't pass if the input is: 
["flower", "flawer", "flvwer", "flower"]
 output = "fl";

**Comment by LC-Pamela** [comment]
Hi @MichaelHGitHub 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pamela** [comment]
Hi @MichaelHGitHub 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by MichaelHGitHub** [comment]
Thank you guys for your quick response.
