### ISSUE TITLE
Missing Test Case - 688. Knight Probability in Chessboard

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#3171]
#### Your LeetCode username

igor84

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A solution is accepted but fails on the following test case:

25
100
0
0

#### Code you used for Submit/Run operation

```
class Solution {
    double[][][] cache = new double[25][25][100];
    public double knightProbability(int N, int K, int r, int c) {
        if(r < 0 || r >= N || c < 0 || c >= N) return 0;
        if(cache[r][c][K] != 0) return cache[r][c][K];
        if(K == 0){
            if(r >= 0 && r < N && c >= 0 && c < N) return 1;
            else return 0;
        }else{
            double prob = (knightProbability(N, K-1, r+2, c+1) +
                knightProbability(N, K-1, r+2, c-1) +
                knightProbability(N, K-1, r-2, c+1) +
                knightProbability(N, K-1, r-2, c-1) +
                knightProbability(N, K-1, r+1, c+2) +
                knightProbability(N, K-1, r-1, c+2) +
                knightProbability(N, K-1, r+1, c-2) +
                knightProbability(N, K-1, r-1, c-2))/8;
            cache[r][c][K] = prob;
            return prob;
        }
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/115273539-ac29cf00-a10d-11eb-93bc-4cdb5a4e0017.png)

**Comment by LC-Pamela** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pamela** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
