### ISSUE TITLE
Missing Constraints: 45. Jump Game II

### ISSUE THREAD

**Issue by zsqw123** [LeetCode-Feedback/LeetCode-Feedback#3174]
**你的 LeetCode 用户名**
zsqw123

**Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
中文版没有约束条件, 但是英文版是有的, 直到我在输入过长的测试用例的时候, 我才发现这个约束条件

**你使用的语言**
Java

**你提交或者运行的代码**
```
// 45. Jump Game II
class Solution {
    public int jump(int[] nums) {
        int len=nums.length;
        int[] ways=new int[len];
        Arrays.fill(ways,Integer.MAX_VALUE);
        ways[0]=0;
        for(int i=0;i<len;i++)
            for(int j=i;j<=i+nums[i] && j<len;j++)
                ways[j]=Math.min(ways[j],ways[i]+1);
        return ways[len-1];
    }
}
```

**期望行为**
1. **中文版增加约束条件**
2. (不重要) 这个测试用例量太小了, 我复杂度这么高的代码都可以0ms, 击败 100%

**屏幕截图**
![image](https://user-images.githubusercontent.com/49520432/115344419-f9767100-a1df-11eb-89d2-e66c6f198264.png)  
![image](https://user-images.githubusercontent.com/49520432/115344525-1c088a00-a1e0-11eb-87f1-f3a1e3a8bbc7.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
@zsqw123 感谢反馈，此问题已转给题目运营团队会尽快确认。

**Comment by feiceh** [comment]
@zsqw123 当前已在中文题面中增加数据范围说明，力扣会定期更新，保障稳定和体验优化。
