### ISSUE TITLE
589. N-ary Tree Preorder Traversal, confusing jsdoc definition.

### ISSUE THREAD

**Issue by satanTime** [LeetCode-Feedback/LeetCode-Feedback#3175]
#### Your LeetCode username

satanTime

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

a code template for `Javascript` has
```js
/**
 * @param {Node} root
 * @return {number[]}
 */
var preorder = function(root) {
```

The code says that `root` is `Node`, but it is not true.
There is a case `[]`, which means `root` is also `undefined`.

#### Code you used for Submit/Run operation

```js
/**
 * @param {Node} root
 * @return {number[]}
 */
var preorder = function(root, existingResult) {
  const result = existingResult || [];
  result.push(root.val); // <-- fails, when root is empty.
  for (let i = 0; i < root.children.length; i += 1) {
    preorder(root.children[i], result);
  }
  
  return result;
};
```

#### Language used for code
Javascript

#### Expected behavior

I think the type should be properly defined in `jsdoc`.
```js
/**
 * @param {(Node|undefined)} root
```

#### Screenshots

https://take.ms/I2vkg

#### Additional context

Nope

**Comment by LC-Pamela** [comment]
Hi @satanTime 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pamela** [comment]
Hi @satanTime 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
