### ISSUE TITLE
Missing Test Case - 689. Maximum Sum of 3 Non-Overlapping Subarrays

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#3176]
#### Your LeetCode username

igor84

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A solution is accepted but fails on the following test case:

[689_test_case.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6342740/689_test_case.txt)

#### Code you used for Submit/Run operation

```
class Solution {
    public int[] maxSumOfThreeSubarrays(int[] nums, int k) {
        if(nums == null || nums.length < 3) return new int[0];
        int[] ans = new int[3];
        long[] max = {0};
        
        
        long[] dp = new long[nums.length];
        long sum = 0;
        for(int i = nums.length - 1; i >= 0; i--) {
            sum += nums[i];
            if(i + k < nums.length) {
                sum -= nums[i+k];
            }
            dp[i] = sum;
        }
        
        helper(dp, new ArrayList<Integer>(), k, 0, 0, max, ans);
        return ans;
    }
    
    private void helper(long[] nums, List<Integer> list, int k, int start, long sum, long[] max, int[] ans) {
        if(list.size() == 3) {
            if(sum > max[0]) {
                max[0] = sum;
                for(int i = 0; i < 3; i++) ans[i] = list.get(i);
            }
            return;
        }
        
        int end = nums.length - (3 - list.size()) * k;
        long currMax = 0;
        for(int i = start; i <= end; i++) {
            
            if(i > start && nums[i] <= currMax) continue;
            currMax = nums[i];
            list.add(i);
            helper(nums, list, k, i + k, sum + nums[i], max, ans);
            list.remove(list.size() - 1);
        }
    }
    
    
    
    
}

```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/115381580-b3022180-a1a1-11eb-860a-284c5c056302.png)

**Comment by LC-Pamela** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pamela** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
