### ISSUE TITLE
Missing Test Case - Rotate Array

### ISSUE THREAD

**Issue by riteshgupta2492** [LeetCode-Feedback/LeetCode-Feedback#3177]
#### Your LeetCode username

ritesh2492

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My solution was accepted but it fails for the below test case.
[1,2]
5

#### Code you used for Submit/Run operation

```
class Solution {
    public void rotate(int[] nums, int k) {
        if(nums.length > 1) {
            if(k>nums.length)
                k = k - nums.length;
            
            int[] temp = new int[k];
            for(int i=0; i<k; i++) {
                temp[i] = nums[nums.length-k+i];
            }

            for(int i=nums.length-k-1; i>=0; i--) {
                nums[i+k] = nums[i];
            }

            for(int i=0; i<k; i++) {
                nums[i] = temp[i];
            }
        }
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted as it fails for the test case I mentioned.

#### Screenshots

<img width="1434" alt="Screenshot 2021-04-20 at 10 41 24 PM" src="https://user-images.githubusercontent.com/30269739/115437239-927daa00-a229-11eb-939d-3969e0d8c7f1.png">
<img width="1436" alt="Screenshot 2021-04-20 at 10 40 57 PM" src="https://user-images.githubusercontent.com/30269739/115437261-97daf480-a229-11eb-9bd0-6bfaa901c81f.png">

**Comment by LC-Pamela** [comment]
Hi @riteshgupta2492 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pamela** [comment]
Hi @riteshgupta2492 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
