### ISSUE TITLE
Missing Test Case - 344. Reverse String

### ISSUE THREAD

**Issue by gopal0208** [LeetCode-Feedback/LeetCode-Feedback#3178]
#### Your LeetCode username

gopal_0208

#### Category of the bug
- [ ] Question
- [#3163  ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The  function in code is working fine with other testcases
but , it is not giving exact output as the one  with ['H','a','n','n','a','h'].
It is not reversing it ,but on other compiler it is working fine.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    void reverseString(vector<char>& s) {
        static int left=0;
        static int right=s.size()-1;
        char temp;
        if(left>=right)
            return;
        temp = s[left];
        s[left++]=s[right];
        s[right--]=temp;
        reverseString(s);
    }
};
```

#### Language used for code

C++

#### Expected behavior

It should reverse ['H','a','n','n','a','h'] as ['h','a','n','n','a','H']

#### Screenshots

![Screenshot (2)](https://user-images.githubusercontent.com/67302165/115457259-e7c5b580-a241-11eb-858b-580ae8688cec.png)

**Comment by LC-Pamela** [comment]
Hi @gopal0208 
Thank you for reaching out to us. I recommend that you check your code or raise your question in the problem's discussion page.
