### ISSUE TITLE
Problem difficulty level standardization

### ISSUE THREAD

**Issue by gptSanyam** [LeetCode-Feedback/LeetCode-Feedback#318]
**Problem difficulty level standardization**
- It seems strange to me that Binary Tree Inorder Traversal (94) is tagged **medium** difficulty but Binary Tree Postorder Traversal is tagged **Hard**
I think both of them should be tagged with the same difficulty level since the solution both the problems is literally the same. All I needed to solve the Post order after solving Inorder traversal is a statement swap.
- language: In any language, the solution to both the problems will remain equally difficult

**Describe the bug**
For these two Problem difficulty levels should be same.

**what language is your code written in**
Java

**The code you submit/run**
```
Snapshot of the code is attached.
```

**Screenshots**
<img width="1180" alt="Screenshot 2020-05-17 at 9 50 26 AM" src="https://user-images.githubusercontent.com/6204700/82135885-6f7e9500-9825-11ea-9673-4d4538442487.png">

**Comment by CooperCooperCooper** [comment]
Hi @gptSanyam ,

Thank you for reaching out to us. Could you please copy and past your codes here on the issues, so we can take a closer look at them?

**Comment by gptSanyam** [comment]
public List<Integer> **inorderTraversal**(TreeNode root) {
        List<Integer> inorder = new ArrayList<>();
        if(root==null){
            return inorder;
        }

        Set<TreeNode> exploredNodes = new HashSet<>();
        Deque<TreeNode> stack = new ArrayDeque<>();
        stack.push(root);

        while(stack.size()>0){
            TreeNode node = stack.remove();
            if(exploredNodes.contains(node)){
                processNode(inorder, node);
            }else {
                if (node.right != null) {
                    stack.push(node.right);
                }
                stack.push(node); //to process later
                if (node.left != null) {
                    stack.push(node.left);
                }
                exploredNodes.add(node);
            }

        }
        return inorder;
    }

    public List<Integer> **postorderTraversal**(TreeNode root) {
        List<Integer> order = new ArrayList<>();
        if(root==null){
            return order;
        }

        Set<TreeNode> exploredNodes = new HashSet<>();
        Deque<TreeNode> stack = new ArrayDeque<>();
        stack.push(root);

        while(stack.size()>0){
            TreeNode node = stack.remove();
            if(exploredNodes.contains(node)){
                processNode(order, node);
            }else {
                stack.push(node); //to process later
                if (node.right != null) {
                    stack.push(node.right);
                }
                if (node.left != null) {
                    stack.push(node.left);
                }
                exploredNodes.add(node);
            }

        }
        return order;
    }

**Comment by CooperCooperCooper** [comment]
Hi @gptSanyam ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @gptSanyam ,
Thank you for your time. We've used your feedback to update the problem difficulty levels to difficult for both. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.

**Comment by gptSanyam** [comment]
Hi @CooperCooperCooper,
Actually there is one more such question which is equally difficult (literally the same code as the other two):
**144. Binary Tree Preorder Traversal (Medium)**
To be honest, I think all three of these should be Medium, but that will be your call.

Below is the code for this:
```
public List<Integer> preorderTraversal(TreeNode root) {
        List<Integer> order = new ArrayList<>();
        if(root==null){
            return order;
        }
        Set<TreeNode> exploredNodes = new HashSet<>();
        Deque<TreeNode> stack = new ArrayDeque<>();
        stack.push(root);
        while(stack.size()>0){
            TreeNode node = stack.remove();
            if(exploredNodes.contains(node)){
                processNode(order, node);
            }else {
                if (node.right != null) {
                    stack.push(node.right);
                }
                if (node.left != null) {
                    stack.push(node.left);
                }
                stack.push(node); //to process later
                exploredNodes.add(node);
            }
        }
        return order;
    }
    private void processNode(List<Integer> order, TreeNode node) {
        //System.out.print(node.val+" ");
        order.add(node.val);
    }
```
