### ISSUE TITLE
Missing Test Case & Official Java Solution 1 - 698. Partition to K Equal Sum Subsets

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#3182]
#### Your LeetCode username

igor84

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Official Java Solution 1 is accepted but fails on the following test case:

[0, 127]
1

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean search(int[] groups, int row, int[] nums, int target) {
        if (row < 0) return true;
        int v = nums[row--];
        for (int i = 0; i < groups.length; i++) {
            if (groups[i] + v <= target) {
                groups[i] += v;
                if (search(groups, row, nums, target)) return true;
                groups[i] -= v;
            }
            if (groups[i] == 0) break;
        }
        return false;
    }

    public boolean canPartitionKSubsets(int[] nums, int k) {
        int sum = Arrays.stream(nums).sum();
        if (sum % k > 0) return false;
        int target = sum / k;

        Arrays.sort(nums);
        int row = nums.length - 1;
        if (nums[row] > target) return false;
        while (row >= 0 && nums[row] == target) {
            row--;
            k--;
        }
        return search(new int[k], row, nums, target);
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case
Official solution needs either to get fixed or removed

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/115540705-47d15180-a26c-11eb-95d8-1749925d329a.png)

**Comment by LC-Pamela** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pamela** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
