### ISSUE TITLE
Missing Test Case - 2. Add Two Numbers

### ISSUE THREAD

**Issue by Osiroski** [LeetCode-Feedback/LeetCode-Feedback#3184]
list.reverse() method not working

#### Your LeetCode username
Osiroski

#### Category of the bug
Solution

#### Description of the bug
AttributeError: 'ListNode' object has no attribute 'reverse'
    l1.reverse()
Line 9 in addTwoNumbers (Solution.py)
    ret = Solution().addTwoNumbers(param_1, param_2)
Line 44 in _driver (Solution.py)
    _driver()
Line 54 in <module> (Solution.py)

#### Code you used for Submit/Run operation

```
# Definition for singly-linked list.
# class ListNode(object):
#     def __init__(self, val=0, next=None):
#         self.val = val
#         self.next = next
class Solution(object):
    def addTwoNumbers(self, l1, l2):
        #Reverse order of list
        l1.reverse()
        l2.reverse()
        # Converting integer list to string list
        s1 = [str(i) for i in l1]
        s2 =[str(i) for i in l1]
        # Join list items using join()
        res1 = int("".join(s1))
        res2 = int("".join(s2))
        #Add and reverse and split
        res3=res1+res2
        res3.reverse()
        return split(res3)
```

#### Expected behavior
list.reverse() method should return a reversed list

**Comment by LC-Pamela** [comment]
Hi @Osiroski 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pamela** [comment]
Hi @Osiroski 
Thank you for your time. The team reviewed your report and considered it invalid. There is no reverse member for the defined ListNode. This is a linked list, not a python list. We appreciate your support!
