### ISSUE TITLE
Missing Test Case - 1603. Design Parking System

### ISSUE THREAD

**Issue by MihaiiV** [LeetCode-Feedback/LeetCode-Feedback#3185]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pamela** [comment]
Hi @MihaiiV 
Thank you for reaching out to us. Please provide content to the ticket in order to help us understand the issue.
