### ISSUE TITLE
Missing Test Case - 376. Wiggle Subsequence

### ISSUE THREAD

**Issue by l0latgithub** [LeetCode-Feedback/LeetCode-Feedback#3186]
#### Category of the bug
- [ ] Question

#### Description of the bug

The problem description needs some update since the following is obviously vague for two element array with same value.
"A sequence with two or fewer elements is trivially a wiggle sequence."

for example, [0,0]

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior

Please update the problem description.

**Comment by LC-Pamela** [comment]
Hi @l0latgithub 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @l0latgithub 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!
