### ISSUE TITLE
Incorrect Question description - 120. Triangle

### ISSUE THREAD

**Issue by luqiang21** [LeetCode-Feedback/LeetCode-Feedback#3187]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The description for the follow up is not correct.
> Follow up: Could you do this using only O(n) extra space, where n is the total number of rows in the triangle?

#### Expected behavior

Follow up: Could you do this using only O(n) extra space, where n is the number of values in the last row in the triangle?

**Comment by LC-Pamela** [comment]
Hi @luqiang21 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @luqiang21 
Thank you for your time. The team reviewed your report decided not to make the change as Number of rows in triangle == number of values in last row.
