### ISSUE TITLE
Incorrect Output Test Case - 37. Sudoku Solver

### ISSUE THREAD

**Issue by ankitagarwal299** [LeetCode-Feedback/LeetCode-Feedback#3188]
#### Your LeetCode username
ankitagarwal299

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
Issue:
1.Without writing code inside an empty function returning an initial array.
2. When I am writing correct code , I am getting result in other editor but in leetcode  Javascript it always return same inital array
https://codeinterview.io/LHCHCRJQGZ

#### Code you used for Submit/Run operation
```
// 37. Sudoku Solver
var solveSudoku = function(board) {
    
};
```

#### Language used for code
JavaScript

#### Expected behavior
Expected: 
1. It should not return any array , it should return undefined or null.
2. Also when i am running code in other code editor it is giving result but in leetcode it is always hardcoded initial array

#### Screenshots
https://codeinterview.io/LHCHCRJQGZ

**Comment by LC-Pamela** [comment]
Thank you for your time. Upon investigating this issue, we found this issue to be non-content-related (the issue stems from an origin away from the content on this problem); therefore, it's not valid for content contribution reward. 
We encourage you to share more content-related issues here with us for [valid content contribution rewards](https://leetcode.com/discuss/general-discussion/526802/File-Problem-and-Solution-Content-Issues-to-Our-GitHub-Public-Feedback-Repo-Now!). Thank you again for your support and understanding.

**Comment by ankitagarwal299** [comment]
You have wrongly closed the issue . Have you tried running this problem on leetcode using JavaScript. 
I have clearly mention that it is returning incorrect output always.
Eg. Run empty function which is given by default .It will return you irrelevant output which user has not returned.

**Comment by lc-kay** [comment]
@ankitagarwal299 The question asks you to solve the problem in place. This means we are not returning anything and the input array should contain the answer.

**Comment by ankitagarwal299** [comment]
Make sense , thank you for responding . My doubts got clear. I was trying not to do inplace.
Thanks!!
