### ISSUE TITLE
Wrong answer in the leetcode  solution ( original ) question 224 basic calculator  

### ISSUE THREAD

**Issue by dheeraj141** [LeetCode-Feedback/LeetCode-Feedback#319]
There is a bug in the solution of the leetcode question 224 basic calculator. It is giving wrong answers. I have attached a snapshot of the bug (in the original solution of the leetcode). 

bug type : Solution 

language C++
<img width="1324" alt="Screenshot 2020-05-17 at 4 32 48 PM" src="https://user-images.githubusercontent.com/8675703/82142754-3877a600-985c-11ea-91bf-ee9b7092e918.png">

As stated the correct answer to the expression should be 22 but the server is showing 23. 
check it once.

**Comment by CooperCooperCooper** [comment]
Hi @dheeraj141 ,
Thank you for reaching out to us. Please note that the "Output" from "Run Code" is the output of your code, which is different from the "Expected" output.

The "Output" underneath Example 3 is equivalent to the "Expected" output on the "Run Code", and they are currently matching with the number "23" according to your screenshot and our test results.

**Comment by dheeraj141** [comment]
I think you haven't understood the problem , the input in the run code result is different from the example 3 as there is * in the run code instead of + and its correct answer is 22 but the expected answer is showing 23 that's why I reported this bug. 

The issue is that the expected  solution is interpreting * as +.

**Comment by CooperCooperCooper** [comment]
Hi @dheeraj141 ,
Thank you for your clarification. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @dheeraj141 ,
Thank you for your time. Our team has reviewed your most recent comment and wanted to point out that there is no part of the statement that the dot operator (*) is needed to be implemented.

For future submissions, please make sure to copy and paste your submission code and the specific test case on the issue besides the screenshot. We appreciate your time and support.
