### ISSUE TITLE
Missing Test Case - 120. Triangle

### ISSUE THREAD

**Issue by Sunidhi-Thakur** [LeetCode-Feedback/LeetCode-Feedback#3192]
#### Your LeetCode username

Sunidhi_Thakur

#### Category of the bug
- [ .] Solution

#### Description of the bug

Problem in the expected output
![error](https://user-images.githubusercontent.com/76440706/115661579-43379680-a35b-11eb-9751-db3290e05229.PNG)
Addition of minimum values in the program.
the minimum value for the test case [[-1],[2,3],[1,-1,-3]] is showing -1 though it should be -2.
minimum in row 1 = -1
minimum in row 2 = 2
minimum in row 3 = -3
sum = -1+2+(-3) = -2, 
but the expected output is -1.

#### Code you used for Submit/Run operation

```
class Solution {
    public int minimumTotal(List<List<Integer>> triangle) {
        int min = Integer.MAX_VALUE, sum=0;
        for(List<Integer> list : triangle){
            min = Integer.MAX_VALUE;
            for(Integer i : list){
                min = Math.min(min,i);
            }
            sum += min;
        }
        return sum;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Addition of minimum values in the program.
the minimum value for the test case [[-1],[2,3],[1,-1,-3]] is showing -1 though it should be -2.
minimum in row 1 = -1
minimum in row 2 = 2
minimum in row 3 = -3
sum = -1+2+(-3) = -2, 
but the expected output is -1.

**Comment by TMT2x** [comment]
The expeccted answer is correct. In your answer, number 2 has index 0, number -3 in next row has index 2. 
This does not meet requirement "More formally, if you are on index i on the current row, you may move to either index i or index i + 1 on the next row."

**Comment by kasienna** [comment]
Still, valid answer is not -1 I think (the only way would be to go -1 -> 3 -> -3 which is not correct)

**Comment by LC-Pamela** [comment]
Hi @Sunidhi-Thakur 
Thank you for reaching out to us. I recommend that you read the question again and check out the problem's discuss page for the answer. The question was raised and answered many times by the LeetCoders.

**Comment by TMT2x** [comment]
> Still, valid answer is not -1 I think (the only way would be to go -1 -> 3 -> -3 which is not correct)


-1 -> 3 -> -3 is the correct answer. The only requirement for this problem is "if you are on index i on the current row, you may move to either index i or index i + 1 on the next row.", 

The corresponding index in each row is 0, 1, 2, which meets the requirement.
