### ISSUE TITLE
Missing Test Case - 554. Brick Wall

### ISSUE THREAD

**Issue by deepeshgodara** [LeetCode-Feedback/LeetCode-Feedback#3197]
#### Your LeetCode username

deepeshgodara

Missing Test Cases 
[[2147483646,1]]

#### Description of the bug

It is well known that this question had test cases which include bricks of size 2147483647
and 84th test case is a wall of a single column with 10000 rows where each of the rows contains a single brick of size 2147483647
The code which is mentioned as the fastest code in java passes the aforesaid test case.
the reason is that the user is running his program for a number of items in row -1, which passes the test case where only 1 element is present in the row, it doesn't matter whether the size of brick size is out of the index for the array designed by the user.
No test case is present where a number of item in a row is greater than 1 and have a size of the brick  greater than 55001
The reason which made me report this bug is that the user mocked test cases of this question. The user added this comment in the java code"// 55000 is the widest wall used by the judge :-P"

Thus for the same reason, I designed a test case where his approach would fail, as the program will try to access the integer present at 2147483646
#### Code you used for Submit/Run operation

```
class Solution {
    	public int leastBricks(List<List<Integer>> wall) {
 
	    // 55000 is the widest wall used by the judge :-P
        int[] edges = new int[55001];

        int maxWidth = 0;
        for (List<Integer> row : wall) {
            int width = 0;
            for (int i = 0; i < row.size() - 1; i++) {
                width += row.get(i);
                edges[width]++;
            }
            if (width > maxWidth) { maxWidth = width; }
        }
        
        int maxEdges = 0;
        for (int i = 0; i <= maxWidth; i++) {
            if (edges[i] > maxEdges) {
                maxEdges = edges[i];
            }
        }
        
        return wall.size() - maxEdges;
    }
}
```

#### Expected behavior

The answer for the provided test case should be zero (0), as there is only 1 row and if we make a cut from location 2147483646 no bricks would be broken.
Attached Screenshots of code passing all test cases provided while failing the test case made by me.
the attached screenshot also provides the proof of code surpassing each and every java submission, which demotivates coders.
whereas the mocking of the test case made me submit this report

#### Screenshots

![Screenshot (16)](https://user-images.githubusercontent.com/30095763/115744133-ea461d80-a3af-11eb-80fa-52f80ad87a08.png)
![Screenshot (17)](https://user-images.githubusercontent.com/30095763/115744137-eb774a80-a3af-11eb-981c-72d58775f4bf.png)
![Screenshot (18)](https://user-images.githubusercontent.com/30095763/115744142-ec0fe100-a3af-11eb-9033-478cfbd58621.png)
![Screenshot (19)](https://user-images.githubusercontent.com/30095763/115744143-eca87780-a3af-11eb-97f1-a531e2aa7f9c.png)

**Comment by LC-Pamela** [comment]
Hi @deepeshgodara 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @deepeshgodara 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
