### ISSUE TITLE
Always get TLE for #1376 for specific test case

### ISSUE THREAD

**Issue by xiesunny** [LeetCode-Feedback/LeetCode-Feedback#32]
**What kind of the bug**
- [ ] problem
- [v] solution
- [ ] language

**Describe the bug**
For problem #1376. Time Needed to Inform All Employees, I always got TLE when I run my Python3 code with specific test case from example 5 of the problem. Even I changed my code to one single line 'return 1076', it still gives TLE.
Trying with different PC and different browsers does not help.

Test case is:
4
2
[3,3,-1,2]
[0,0,162,914]

**The code you submit/run**
```
class Solution:
    def numOfMinutes(self, n: int, headID: int, manager: List[int], informTime: List[int]) -> int:
        return 1076
```

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/10125356/76293342-d6467600-62eb-11ea-984d-3b3ac5e00472.png)
![image](https://user-images.githubusercontent.com/10125356/76293353-dba3c080-62eb-11ea-9eb6-5b6f5c16f2b1.png)

**Additional context**

**Comment by CooperCooperCooper** [comment]
Hi @xiesunny,
Thank you for raising this issue to our attention! To help us assess this issue, can you please clear your browser cache, cookies, and extensions, and check if the TLE still persists after completing those actions?

**Comment by xiesunny** [comment]
Hi @CooperCooperCooper 
Yes. I tried with 3 different PC and different browsers (chrome, edge, firefox) with all cache/cookie cleaned and extensions disabled. The TLE result is still there when using 'Run Code', but it gives right result for 'Playground Debug'.
Today I tried again for all example test case from the question, with clean installed firefox browser in Windows Sandbox.

Example 1, result is expected:
1
0
[-1]
[0]
![image](https://user-images.githubusercontent.com/10125356/76373685-19e8c080-637c-11ea-82c8-de1cce2357ca.png)
![image](https://user-images.githubusercontent.com/10125356/76373719-2d942700-637c-11ea-9eb0-976befd4e631.png)

Example 2: result is expected:
6
2
[2,2,-1,2,2,2]
[0,0,1,0,0,0]
![image](https://user-images.githubusercontent.com/10125356/76373862-924f8180-637c-11ea-9f6f-6100b11e6272.png)
![image](https://user-images.githubusercontent.com/10125356/76373898-a4c9bb00-637c-11ea-9e57-61e58c36b7b9.png)

Example 3: TLE
7
6
[1,2,3,4,5,6,-1]
[0,6,5,4,3,2,1]
![image](https://user-images.githubusercontent.com/10125356/76374013-eeb2a100-637c-11ea-805e-5ec44b05dfe1.png)
![image](https://user-images.githubusercontent.com/10125356/76374041-04c06180-637d-11ea-9041-b6f338030e8d.png)

Example 4: Runtime Error (Invalid Input)
15
0
[-1,0,0,1,1,2,2,3,3,4,4,5,5,6,6]
[1,1,1,1,1,1,1,0,0,0,0,0,0,0,0]
![image](https://user-images.githubusercontent.com/10125356/76374117-346f6980-637d-11ea-91c4-f81f62f1a07e.png)
![image](https://user-images.githubusercontent.com/10125356/76374143-46e9a300-637d-11ea-9aff-6a972db4d02c.png)

Example 5: TLE
4
2
[3,3,-1,2]
[0,0,162,914]
![image](https://user-images.githubusercontent.com/10125356/76374224-8d3f0200-637d-11ea-83ed-9dcc70b4f4d9.png)
![image](https://user-images.githubusercontent.com/10125356/76374246-9c25b480-637d-11ea-9b01-811bd0e76f69.png)
![image](https://user-images.githubusercontent.com/10125356/76374274-b2337500-637d-11ea-96c9-7387cfb568b4.png)

**Comment by CooperCooperCooper** [comment]
Hi @xiesunny,

Awesome! Thank you so much for sharing these clarifications with us. I've relayed them to our engineers to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @xiesunny,
Good news! We've fixed the TLE issue. Please test your code again and let us know if you have any other questions. We appreciate your time and support.

**Comment by xiesunny** [comment]
Hi @CooperCooperCooper ,
Yes, it is fixed. My code passed all test cases now. Thanks.
