### ISSUE TITLE
Missing Test Case - 1228. Missing Number In Arithmetic Progression

### ISSUE THREAD

**Issue by caligarisdesk** [LeetCode-Feedback/LeetCode-Feedback#3201]
#### username
caligarisdesk

#### Category of the bug
- [ ] Question
- [ x] Solution
- [ ] Language
- [ x] Missing Test Cases 

#### Description of the bug
The test case [1,2,3] should be screened out, but is not

#### Code you used for Submit/Run operation

```
public int missingNumber(int[] arr) {
        
        int diff = 0;
        int diffIndex = 0;
        for(int i = 1; i < arr.length; i++) {
            int curDiff = arr[i] - arr[i-1];
            if(curDiff == 0) {
                return arr[i];
            }
            if(diff == curDiff * 2) {
                return (arr[diffIndex]+arr[diffIndex-1])/2;
            }
            if(diff * 2 == curDiff) {
                return (arr[i]+arr[i-1])/2;
            }
            diff = curDiff;
            diffIndex = i;
        }
        return 0;
    }
```

#### Language used for code
Java

#### Expected behavior
When I input test case [1,2,3] I would expect that it be rejected as invalid.  Instead, my code above (which was accepted) returns 0 and the expected value is 1.  

<img width="948" alt="leet code bug" src="https://user-images.githubusercontent.com/3620013/115792415-443ae900-a398-11eb-9391-9f6e03da8e75.png">

**Comment by LC-Pamela** [comment]
Hi @caligarisdesk 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @caligarisdesk 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by caligarisdesk** [comment]
Leetcode id is McN697
https://leetcode.com/McN697/
