### ISSUE TITLE
Incorrect solutions - 1228. Missing Number In Arithmetic Progression

### ISSUE THREAD

**Issue by hinet60613** [LeetCode-Feedback/LeetCode-Feedback#3203]
#### Your LeetCode username
hinet60613

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

1. Both of the provided solutions are incorrect.
The solutions provided by LeetCode, both Linear Search and Binary Search, require the input array to be sorted.
Since the description of the problem doesn't guarantee the array is sorted, we have to sort it on our own. But this step is not shown in the sample code.
Besides, by sorting the array it will at least costs O(nlogn) time complexity.

2. Proposed linear solution
This problem can be solved by pure math in linear time complexity as follows:
    1) the mean value of the array is the average of maximum value and minimum value of the given array.
    2) By multiplying the mean value with the length of original array, we could get the sum of the original array.
    3) Then we could get the missing number by subtract the sum of current array from the sum of original array.

#### Code you used for Submit/Run operation

```python3
// 1228. Missing Number In Arithmetic Progression
class Solution:
    def missingNumber(self, arr: List[int]) -> int:
        mean_val = (max(arr) + min(arr)) / 2
        sum_of_original_array = mean_val * (len(arr) + 1)
        return int(sum_of_original_array - sum(arr))
```

#### Language used for code

Python3

**Comment by lc-kay** [comment]
Hi @hinet60613 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@hinet60613 Thanks for your feedback. We have reviewed the problem description and solution article and determined that they are correct as is.

Please read the problem description carefully:

In some array arr, the values were in arithmetic progression: the values arr[i + 1] - arr[i] are all equal for every 0 <= i < arr.length - 1.

For this condition to hold, the array must be sorted. Additionally, an arithmetic progression is, by definition, either sorted or reverse sorted.
