### ISSUE TITLE
Repetitive Hints - 1833. Maximum Ice Cream Bars

### ISSUE THREAD

**Issue by Mohammed-Shoaib** [LeetCode-Feedback/LeetCode-Feedback#3207]
#### Your LeetCode username
[MohammedShoaib](https://leetcode.com/MohammedShoaib/)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
There are repetitive hints in this question. The hint numbers `3` & `4` are the same as the hint numbers `1` & `2` respectively.

#### Expected behavior
Only the hints `1` & `2` should be present, the additional hints `3` & `4` should be removed.

#### Screenshots
![Repetitive Hints](https://user-images.githubusercontent.com/32389312/115856759-2ec3ce80-a42d-11eb-93db-5c27fc167132.png)

**Comment by lc-kay** [comment]
Hi @Mohammed-Shoaib 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Mohammed-Shoaib 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
