### ISSUE TITLE
Missing Test Case - 155. Min Stack

### ISSUE THREAD

**Issue by ManognaNalluri** [LeetCode-Feedback/LeetCode-Feedback#3208]
### mail id: manognanalluri2000@gmail.com

**Category of the bug**: question no 155

**Description of the bug:** question number 155 and the question name is Min Stack
                                             there is a mistake in the test case : example 1 and the mistake is in the output..
                                             given output:  [null,null,null,null,-3,null,0,-2]
                                             correct output:  [null,null,null,null,-3,-3,0,-2]

**Comment by hunkyjimpjorps** [comment]
`pop` doesn’t return a value.

**Comment by lc-kay** [comment]
@ManognaNalluri Please refer to the above comment and the explanation for reference. Thank you for your time.
