### ISSUE TITLE
Missing Test Case - 1833. Maximum Ice Cream Bars

### ISSUE THREAD

**Issue by riddhij16** [LeetCode-Feedback/LeetCode-Feedback#3209]
#### Your LeetCode username
 riddhij16

#### Category of the bug
- [ ] Language

#### Description of the bug

It is showing accuracy as 102.0 % 
How can it be greater than 100% 
Showing
Accepted: 14,917
Submissions: 14,616

#### Expected behavior

Accuracy of attempting question Should be less than 100%

**Comment by lc-kay** [comment]
@riddhij16 Based on the current stats for this question, it appears that the acceptance rate and accuracy are correct. Thank you for your time.
