### ISSUE TITLE
Missing Test Case & Official Solution 1 - 638. Shopping Offers

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#3216]
#### Your LeetCode username

igor84

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Official Java Solution 1 is accepted but fails on the following test case:

[6]
[[1, 11], [1, 10], [1, 1], [4, 2], [6, 8], [1, 5], [3, 11], [1, 5], [3, 8], [5, 9], [3, 6], [1, 8], [3, 8], [6, 3], [1, 10], [4, 6], [2, 7], [4, 7], [1, 9], [3, 7], [2, 5], [6, 4], [2, 10], [1, 11], [4, 5], [1, 3], [3, 11], [1, 2], [1, 2], [4, 2], [1, 4], [1, 3], [2, 7], [5, 2], [1, 5], [3, 10], [6, 3], [4, 3], [6, 1], [3, 11], [1, 1], [1, 1], [1, 7], [2, 11], [3, 4], [6, 1], [5, 2], [1, 10], [1, 3], [1, 5], [2, 6], [3, 10], [2, 7], [6, 8], [2, 9], [3, 2], [4, 1], [3, 9], [4, 7], [6, 11], [4, 6], [5, 9], [2, 5], [3, 11], [1, 4], [3, 4], [5, 8], [2, 2], [4, 9], [3, 2]]
[10]

#### Code you used for Submit/Run operation

```
public class Solution {
    public int shoppingOffers(List < Integer > price, List < List < Integer >> special, List < Integer > needs) {
        return shopping(price, special, needs);
    }
    public int shopping(List < Integer > price, List < List < Integer >> special, List < Integer > needs) {
        int j = 0, res = dot(needs, price);
        for (List < Integer > s: special) {
            ArrayList < Integer > clone = new ArrayList < > (needs);
            for (j = 0; j < needs.size(); j++) {
                int diff = clone.get(j) - s.get(j);
                if (diff < 0)
                    break;
                clone.set(j, diff);
            }
            if (j == needs.size())
                res = Math.min(res, s.get(j) + shopping(price, special, clone));
        }
        return res;
    }
    public int dot(List < Integer > a, List < Integer > b) {
        int sum = 0;
        for (int i = 0; i < a.size(); i++) {
            sum += a.get(i) * b.get(i);
        }
        return sum;
    }

}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case
Official Java solution 1 should be marked as "Time Limit Exceeded" (it says "Accepted" at this moment)

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/115937467-17550780-a466-11eb-90f6-5dc6feaebeb4.png)

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@IgorRud Our team has reviewed your report, and although this is a valid test case, we have decided not to add it as it will fail the top-voted solutions. Thank you for your understanding.
