### ISSUE TITLE
Error in solution explanation for #567

### ISSUE THREAD

**Issue by us899** [LeetCode-Feedback/LeetCode-Feedback#322]
# 567. Permutation in String
**Describe the bug**
In approach 5 for the problem, it's written that:
>we know that we add one preceding character and add a new succeeding character to the new 

 but instead, it should be:
>we know that we **remove** one preceding character and add a new succeeding character to the new window

**What kind of the bug**
- [ ] problem
- [x] solution
- [ ] language

**Comment by CooperCooperCooper** [comment]
Hi @us899 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by us899** [comment]
Is there any way for me to contribute to leetcode directly and maybe solve some of these basic bugs?

**Comment by CooperCooperCooper** [comment]
Hi @us899 ,
Thank you for your time. We've used your feedback to update the solution. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward. 

If you're interested in working for LeetCode, please check out the positions we have listed on our [job board](https://leetcode.com/jobs/). We appreciate your support.
