### ISSUE TITLE
Missing Test Case - 396. Rotate Function

### ISSUE THREAD

**Issue by u101022119** [LeetCode-Feedback/LeetCode-Feedback#3221]
#### Your LeetCode username

neil83062505

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In some case it may return a wrong answer. 
For example 
[0,1,720000000]    system return  720000000       it should be   1440000001
[0,1,800000000]    system return  800000000       it should be   1600000001
I think that it may be cause of  the round-off error. Please check the code used for the answer.
Thanks

#### Code you used for Submit/Run operation

```
// Rotate Function
class Solution {
public:
  int maxRotateFunction(int* nums, int numsSize){
      double sum = 0;
      for (int i =0 ; i< numsSize ; ++i){
          sum+= nums[i];
      }
      float avr = sum/numsSize;
      float c = 0;
      float temp = -1;
      int j1;
      for (int j = 0; j<numsSize; j++){  
          c = c + avr - nums[numsSize-1-j];
          if (c >= temp){
              j1=j;
              temp =c;
          }
      }
      int ans = 0;
      for (int z = 1; z<numsSize; z++){
          ans += z*nums[(numsSize-j1) % numsSize];
          j1--;
      }
      return ans;
  }
};
```

#### Language used for code

C

#### Additional context

Thank you!

**Comment by u101022119** [comment]
Here it is!
https://leetcode.com/submissions/detail/484183183/

**Comment by lc-kay** [comment]
Hi @u101022119 
Thank you for providing that. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @u101022119 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
