### ISSUE TITLE
Invalid test case giving wrong ans while running code - 696. Count Binary Substrings

### ISSUE THREAD

**Issue by kanch231004** [LeetCode-Feedback/LeetCode-Feedback#3222]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The problem constraint defines that string length can't be empty. While if you try "" string during running code (not submitting), it gives wrong answer. It says Expected = 1, Your answer is 0. Which is invalid. Kindly throw a proper error of invalid test case for empty string.

#### Code you used for Submit/Run operation

```
    public int countBinarySubstrings(String s) {
    
        int count = 0;
        int prev = 0, curr = 1;
    
        for (int i = 1 ; i < s.length() ; i++) {
            if (s.charAt(i) != s.charAt(i-1)) {
                prev = curr;
                curr = 1;
                count++;
            } else {
                curr++;
                if (curr <= prev) {
                    count++;
                }
            }
        }
        
        return count;
    }
```

#### Expected behavior
Kindly throw a proper error of invalid test case for empty string instead of showing wrong answer.

#### Screenshots
<img width="486" alt="Screenshot 2021-04-24 at 11 37 45 AM" src="https://user-images.githubusercontent.com/32065373/115949363-4a44dd00-a4f2-11eb-837f-6b6c3af2a382.png">

**Comment by lc-kay** [comment]
Hi @kanch231004 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @kanch231004 
Thank you for your time. We've added the validator.
