### ISSUE TITLE
Invalid Test Case - 167. Two Sum II - Input array is sorted

### ISSUE THREAD

**Issue by kxk3041** [LeetCode-Feedback/LeetCode-Feedback#3224]
#### Your LeetCode username
kxk3041

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
My code fails on one test case:
Input:
[3,5,5,7]
10
My Output: [2,3]
Expected: [1,4]
In fact my output is valid: the problem description only indicates that we can't use the same element twice but it doesn't forbid using two elements with the same value.
Since the problem description indicates that there should be only one valid solution, this test case is invalid because it has two valid solutions.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<int> twoSum(vector<int>& numbers, int target) {
        int left = 0;
        int right = numbers.size()-1;
        while (left+1 < right) {
            int middle = (left+right)/2;
            if (numbers[middle]*2 < target) {
                left = middle;
            } else {
                right = middle;
            }
        }
        if (left > 0 && numbers[left-1]+numbers[left] == target) return {left, left+1};
        if (right+1 < numbers.size() && numbers[right]+numbers[right+1] == target) return {right+1, right+2};
        while (true) {
            int sum = numbers[left]+numbers[right];
            if (sum == target) {
                return {left+1, right+1};
            } else if (sum < target) {
                right++;
            } else {
                left--;
            }
        }
        return {1,1};
    }
};
```

#### Language used for code
C++

#### Expected behavior
This test case is invalid and it should be removed.

#### Screenshots
![lc167](https://user-images.githubusercontent.com/81740006/115953105-661e9380-a49e-11eb-9f0d-9408d4c0c0c4.PNG)

**Comment by lc-kay** [comment]
Hi @kxk3041 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @kxk3041 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
