### ISSUE TITLE
Wrong wording in subtree-of-another-tree  solution 

### ISSUE THREAD

**Issue by Sai-prakash15** [LeetCode-Feedback/LeetCode-Feedback#3225]
Question: https://leetcode.com/problems/subtree-of-another-tree/

In solution approach1 (using preorder traversal): (https://leetcode.com/problems/subtree-of-another-tree/solution/)
The second image label for the tree t is wrong , it should be PreOrdert .

![image](https://user-images.githubusercontent.com/52249348/115953535-b121c080-a509-11eb-893d-301d65723589.png)

**Comment by lc-kay** [comment]
Hi @Sai-prakash15 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @Sai-prakash15,
Thank you for your time, the solution article has been removed and it will be rewritten! We appreciate your support!
