### ISSUE TITLE
Missing information in question 

### ISSUE THREAD

**Issue by nikarun** [LeetCode-Feedback/LeetCode-Feedback#3228]
#### Your LeetCode username
parihararun3

#### Category of the bug
- [ ] Question

#### Description of the bug
In the Question There is not incomplete information what to return when array size is less than 3 or if if we dont find peak element.

#### Code you used for Submit/Run operation
  int findPeakElement(vector<int>& nums) {
       int n=nums.size();
        if(n<3) return 0;
        for(int i=1;i<n-1;i++){
            if(nums[i]>nums[i+1] && nums[i]>nums[i-1]) return i;
        }
        
        return -1;
    }

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@nikarun Please provide the problem number and title. Thank you.

**Comment by lc-kay** [comment]
Hi @nikarun 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
