### ISSUE TITLE
Test Cases Missing Considering Difficulty of 287. Find the Duplicate Number

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#3229]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
For [287. Find the Duplicate Number](https://leetcode.com/problems/find-the-duplicate-number), the `O(n^2)` solution can be accepted. However, considering the difficulty, the `O(n^2)` solution should receive a TLE when submitted.
Although the maximum possible value for `n` can be `3 * 10^4`, I am not sure whether this value is large enough to make the `O(n^2)` solution TLE. If necessary, the data range should be changed to `2 <= n <= 10^5`. Also, there must be one or more test cases that have `n` equal to the maximum possible value (e.g. `n == 3 * 10^4` or `n == 10^5`) so that the solution with `O(n^2)` time complexity will get TLE. In this way, the time complexity can be restricted.
Also, the last follow-up question should be removed, since the `O(n^2)` time complexity is not supposed to get accepted in this problem.

#### Code you used for Submit/Run operation

```
class Solution {
    public int findDuplicate(int[] nums) {
        int length = nums.length;
        for (int i = 0; i < length; i++) {
            int num = nums[i];
            for (int j = i + 1; j < length; j++) {
                if (nums[j] == num) {
                    return num;
                }
            }
        }
        return 0;
    }
}
```

#### Language used for code
Java

#### Expected behavior
- The data range should be changed to `2 <= n <= 10^5` if necessary.
- There must be one or more test cases that have `n` equal to the maximum possible value (e.g. `n == 3 * 10^4` or `n == 10^5`) so that the code above will get TLE.
- The last follow-up question should be removed, since the `O(n^2)` time complexity is not supposed to get accepted in this problem.

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for your time. We've updated the constraints of this problem.
