### ISSUE TITLE
1452. People Whose List of Favorite Companies Is Not a Subset of Another List

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#323]
**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
Incorrect solution accepted due to weak test cases

**what language is your code written in**
C++

**The code you submit/run**
```
class Solution {
public:
    vector<int> peopleIndexes(vector<vector<string>>& favoriteCompanies) {
        unordered_map<string, int> m;
        int id = 1, sz = favoriteCompanies.size();
		
        for (const auto &fc: favoriteCompanies) {
            for (const auto &c: fc) {
                if (m.count(c) > 0) continue;
                m[c] = id++;
            }
        }
		
        vector<bitset<501>> vec;
        for (const auto &fc: favoriteCompanies) {
            bitset<501> b;
            for (const auto &c: fc) {
                b[m[c]] = 1;
            }
            vec.push_back(b);
        }
		
        vector<int> res;
        for (int i = 0; i < sz; ++i) {
            bool flag = true;
            for (int j = 0; j < sz and flag; ++j) {
                if (i == j) continue;
                if ((vec[i] & vec[j]) == vec[i]) flag = false;
            }
            if (flag) res.push_back(i);
        }
		
        return res;
    }
};
```

**Expected behavior**
The test case is attached
[New Text Document.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/4640891/New.Text.Document.txt)

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
