### ISSUE TITLE
Constraints of Data Range Missing for 383. Ransom Note

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#3230]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
For [383. Ransom Note](https://leetcode.com/problems/ransom-note), the constraints of data range are missing.
For `ransomNote` and `magazine`, what are the ranges of their lengths? In other words, what are the maximum lengths of the two strings, and what are the minimum lengths of the two strings?

#### Expected behavior
The constraints of the lengths of `ransomNote` and `magazine` should be added in **Constraints** part.

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@stormsunshine Thank you for your time. Our team has added the constraints.
