### ISSUE TITLE
Test Cases Missing Considering Difficulty of 456. 132 Pattern

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#3231]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
For [456. 132 Pattern](https://leetcode.com/problems/132-pattern), the data range is `1 <= n <= 10^4`. A naive solution with `O(n^2)` time complexity can easily be accepted. However, the difficulty of this problem is Medium, which requires a solution with better time complexity.
Therefore, I suggest that the data range should be changed to `1 <= n <= 10^5`, and there must be one or more test cases that have `n == 10^5` so that the solution with `O(n^2)` time complexity will get TLE. In this way, the time complexity can be restricted.

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean find132pattern(int[] nums) {
        int length = nums.length;
        int numsi = nums[0];
        for (int j = 1; j < length; j++) {
            for (int k = length - 1; k > j; k--) {
                if (numsi < nums[k] && nums[k] < nums[j]) {
                    return true;
                }
                numsi = Math.min(numsi, nums[j]);
            }
        }
        return false;
    }
}
```

#### Language used for code
Java

#### Expected behavior
The data range should be changed to `1 <= n <= 10^5`, and there must be one or more test cases that have `n == 10^5` so that the code above will get TLE.
After this, the follow-up question should be removed.

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@stormsunshine Our team has reviewed your report and the problem and concluded that the problem is medium with the current constraints. Therefore, we will not be making any changes. Thank you for your time.
