### ISSUE TITLE
Incorrect Variable Names in Problem Descriptions

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#3235]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In [949. Largest Time for Given Digits](https://leetcode.com/problems/largest-time-for-given-digits) and [950. Reveal Cards In Increasing Order](https://leetcode.com/problems/reveal-cards-in-increasing-order), the variable names in problem description are inconsistent.
In problem 949, the variable name of the array should be `arr`. However, in the examples, the variable name of the array is `A`.
In problem 950, the variable name of the array should be `deck`. However, in the **Note** part, the variable name of the array is `A`.

#### Expected behavior
The variable names should be consistent. In problem 949, the variable name of the array should be `arr`. In problem 950, the variable name of the array should be `deck`.

#### Screenshots
![image](https://user-images.githubusercontent.com/12067364/115960391-b4d23900-a543-11eb-9068-ce1b0e107246.png)

![image](https://user-images.githubusercontent.com/12067364/115960414-de8b6000-a543-11eb-8044-ff239142bdae.png)

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
