### ISSUE TITLE
Missing Test Case - 1192. Critical Connections in a Network

### ISSUE THREAD

**Issue by jafarovj** [LeetCode-Feedback/LeetCode-Feedback#3238]
#### Your LeetCode username

jafarovj

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

My solution passed all test cases provided but I found a simple custom test case which it couldn't pass. I think this test case should be added for this problem.

6
[[0,1],[0,2],[1,3],[1,4],[3,4],[2,5],[3,5]]

#### Code you used for Submit/Run operation

```
# Critical Connections in a Network
class Solution(object):
    def criticalConnections(self, n, connections):
        """
        :type n: int
        :type connections: List[List[int]]
        :rtype: List[List[int]]
        """
        
        graph = collections.defaultdict(set)
        for u, v in connections:
            graph[u].add(v)
            graph[v].add(u)
        
        root = 0
        tree = {}
        criticalEdges = {}
        activeVertices = collections.deque([root])
        
        def removeEdges(vertex, ancestor):
            while vertex != ancestor and vertex != root and (vertex, tree[vertex]) in criticalEdges:
                criticalEdges.pop((vertex, tree[vertex]))
                vertex = tree[vertex]
        
        def findCommonAncestor(v1, v2):
            ancestors = set([])
            while v1 != root and (v1, tree[v1]) in criticalEdges:
                ancestors.add(v1)
                v1 = tree[v1]
            
            while v2 != root and (v2, tree[v2]) in criticalEdges:
                if v2 in ancestors:
                    return v2
                v2 = tree[v2]
            
            return v2
        
        
        while activeVertices:
            vertex = activeVertices.pop()
            for neighbor in graph[vertex]:
                if neighbor == root:
                    continue
                
                if neighbor not in tree:
                    tree[neighbor] = vertex
                    criticalEdges[(neighbor, vertex)] = None
                    activeVertices.appendleft(neighbor)
                    continue
                    
                if neighbor != tree[vertex]:
                    ancestor = findCommonAncestor(vertex, neighbor)
                    # print ancestor
                    removeEdges(vertex, ancestor)
                    removeEdges(neighbor, ancestor)
        
        return criticalEdges.keys()
```

#### Language used for code

Python

#### Expected behavior

In my solution I am constructing a tree and keeping track of critical edges. Starting from a root (vertex = 0) I add its neighbor to the tree if this neighbor is not in the tree yet and update critical edge set with the edge connecting vertex to this neighbor. If the neighbor is in the tree, then I delete edges from vertex and neighbor to their lowest common ancestor. When I was finding the lowest common ancestor I stopped the search if an edge was not present among critical edges (falsely assuming that if an edge was not present, then all edges above it were already removed). This passed all test cases but it does now work for custom test case I made:

6
[[0,1],[0,2],[1,3],[1,4],[3,4],[2,5],[3,5]]

My code returned [[1,0]] but it should have been []

**Comment by lc-kay** [comment]
Hi @jafarovj 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @jafarovj 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!
