### ISSUE TITLE
Missing Test Case - 339. Nested List Weight Sum

### ISSUE THREAD

**Issue by AbubakrAlabbasi** [LeetCode-Feedback/LeetCode-Feedback#3239]
One test case is missing: if the list is empty ----> 
My solution is:

def depthSum(self, nestedList: List[NestedInteger]) -> int:
        def productSum(array,level):
            totalSum=0        
            for ele in array:
                if ele.isInteger():
                    totalSum += ele.getInteger()*level                   
                else:
                    totalSum += productSum(ele.getList(),level+1)
        
            return totalSum
        
        if nestedList == []: 
            return totalSum
        return productSum(nestedList,1)

**Comment by lc-kay** [comment]
@AbubakrAlabbasi An empty list is not a valid test case as expected 'nestedList.length' to have value from 1 to 50 only. Thank you for your time.
