### ISSUE TITLE
#1304 Incorrect data type is accepted

### ISSUE THREAD

**Issue by shatlovsky** [LeetCode-Feedback/LeetCode-Feedback#324]
**What kind of the bug**
- [ ] problem
- [x] solution
- [ ] language

**Describe the bug**
Problem: [1304. Find N Unique Integers Sum up to Zero](https://leetcode.com/problems/find-n-unique-integers-sum-up-to-zero/)

By the problem definition, the solution in Python3 has to return List[int]. At the same time, if it returns a generator instead, the solution is still being accepted. Which is wrong, because all the actual calculation is being done lazy.

**what language is your code written in**
Python3

**Example wrong solution**
```
class Solution:
    def sumZero(self, n: int) -> List[int]:
        return range(1 - n, n, 2)
```

**Example test case***
```
class MyTestCase(unittest.TestCase):
    def test(self):
        param = 4
        return self.assertEqual(isinstance(Solution().sumZero(param), list), True)
```

**Expected behavior**
The test case will prove that the returned value is an instance of List indeed

**Comment by CooperCooperCooper** [comment]
Hi @shatlovsky ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @shatlovsky ,
Thank you for your time. We've taken a thorough at this suggestion. We decide to keep this suggestion on the file and keep the problem as-is for technical reasons.
