### ISSUE TITLE
Missing Test Case - 1316. Distinct Echo Substrings

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#3240]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution fails on the following testcase:
"leeleetleeleeleclec"

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int distinctEchoSubstrings(string text) {
        int n = text.size();
        if(n < 2)
            return 0;
        int ans = 0;
        for(int len=1;len<=n/2;len++) //l表示一半长度
        {
            int cnt = 0;
            unordered_set<string> st;
            for(int i=0;i < n - len;i++)
            {
                if(text[i] != text[i+len])
                    cnt = 0;
                else{
                    cnt++; //连续cnt个字符匹配
                    if(cnt == len){ //直到len个字符相同
                        string key = text.substr(i- len + 1,len);
                        if(st.count(key) == 0){
                            st.insert(key);
                            ans++;
                            cnt--;
                        }
                    }
                }
            }
        }
        return ans;
        
    }
};
```

#### Language used for code

C++

#### Expected behavior

Output: 3
Expected: 5

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
