### ISSUE TITLE
Missing Test Case - 1192. Critical Connections in a Network

### ISSUE THREAD

**Issue by zyhazwraith** [LeetCode-Feedback/LeetCode-Feedback#3241]
#### Your LeetCode username

zyhazwraith

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

according to the Constraints, n can be 0 and connections can be empty,
but the standard program doesn't take this into account

#### Code you used for Submit/Run operation

```
class Solution:
    def criticalConnections(self, n: int, connections: List[List[int]]) -> List[List[int]]:
        edge = {}
        for i in range(n):
            edge[i] = []
        for e in connections:
            edge[e[0]].append(e[1])
            edge[e[1]].append(e[0])
            
        vis = [0] * n
        dfn = [0] * n
        low = [0] * n
        res = []
        idx = 0
        
        def tarjan(u, fa):
            nonlocal idx
            vis[u] = 1
            dfn[u] = low[u] = idx
            idx += 1
            
            for v in edge[u]:
                if not vis[v]:
                    tarjan(v, u)
                    low[u] = min(low[u], low[v])
                    
                    if low[v] > dfn[u]:
                        res.append([u, v])
                elif v != fa:
                    low[u] = min(low[u], low[v])
            
        
        for i in range(n):
            if not vis[i]:
                tarjan(i, -1)

        return res
```

#### Language used for code

python3

#### Expected behavior

INPUT: 
1
[]
OUTPUT:
0

**Comment by lc-kay** [comment]
@zyhazwraith The test case you provided is returning Invalid Testcase error: Line 37: java.lang.NullPointerException Therefore, we will not be considering this test case. Thank you for your time.

**Comment by lc-kay** [comment]
Hi @zyhazwraith 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
