### ISSUE TITLE
Incorrect Variable Names in Problem Description of 1063. Number of Valid Subarrays

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#3242]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In [1063. Number of Valid Subarrays](https://leetcode.com/problems/number-of-valid-subarrays), the variable names in problem description are incorrect.
The variable name of the array should be `nums` according to the code, not `A`.

#### Expected behavior
The variable names should be changed from `A` to `nums` in problem description.
The changes should be done in the first sentence of problem description, and in the **Note** part at the end.

#### Screenshots
![image](https://user-images.githubusercontent.com/12067364/115982406-3d48ec00-a5cd-11eb-9bb1-675dbad6804a.png)

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@stormsunshine Our team is working on this for all our problems and is making a good process. However, it will take some time to update all the old problems. Thank you for understanding.
