### ISSUE TITLE
Wrong Test Case? - 482. License Key Formatting

### ISSUE THREAD

**Issue by Maximilian5189** [LeetCode-Feedback/LeetCode-Feedback#3243]
#### Your LeetCode username
maximilian5189

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
There seems to be a bug in one of the testcases, as from my point of view it does not fit to the description (or maybe I am missing something here?). The problem asks to amend the input string (e.g. "5F3Z-2e-9-w"), however the first part before the dash should always be left untouched. To me it seems that one of the testcases asks to amend the first part of the string as well.

#### Code you used for Submit/Run operation
```
var licenseKeyFormatting = function(s, k) {
  let firstPartFound = false
  let count = 0
  let newS = ""
  for (let i = 0; i < s.length; i++) {
    if (firstPartFound === true) {
      if (s[i] === "-") {
        continue
      } else {
          count++
          newS += s[i].toUpperCase()
        if (count === k && i + 1 < s.length) {
          newS += "-"
          count = 0
        }
      }
    } else {
      newS += s[i]
    }

    if (s[i] === "-") firstPartFound = true
  }

  return newS
};
```

#### Language used for code
Javascript

#### Expected behavior
As written in the description, the first part of the string should be leaved untouched, as mentioned in example two:
`Input: s = "2-5g-3-J", k = 2
Output: "2-5G-3J"`

#### Actual behavior
For a different testcase however, there is the following input: 
`Input: "2-4A0r7-4k", k = 4`

The expected out seems to imply to modify the first part of the string, which would be contrary to the description: 
`"24A0-R74K"`. 

If I am understanding correctly, the expected output should be the following?! `"2-4A0r7-4k`

**Comment by stormsunshine** [comment]
The problem does not say that the first part before the dash should be left untouched.
After separating the string into several groups of length `k`, since the total length of the string (excluding the dashes) is not always a multiple of `k`, there may be one group that has length less than `k`. In this case, the first group may have length less than `k`.
You can simply ignore the dashes in the original string.

**Comment by Maximilian5189** [comment]
Okay, I see your point, thanks for clarification.

I guess I stumbled over this sentence, which is a bit ambiguous imo: "We want to reformat the string s such that each group contains exactly k characters, except for the first group, which could be shorter than k but still must contain at least one character."
