### ISSUE TITLE
Missing Test Case - 118. Pascal's Triangle

### ISSUE THREAD

**Issue by ttelang** [LeetCode-Feedback/LeetCode-Feedback#3247]
#### Your LeetCode username
user7066E

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The existing solution contains unnecessary check for 
```
if (numRows == 0)
```

#### Code you used for Submit/Run operation

```
class Solution {
    public List<List<Integer>> generate(int numRows) {
        List<List<Integer>> result = new ArrayList<>(numRows);
        
        result.add(new ArrayList<>(1));
        result.get(0).add(1);
               
        for (int i = 1; i < numRows; i++){   
            List<Integer> row = new ArrayList<>(i+1);
            row.add(1);  // first element is always 1                      
            
            // each element of triangle is sum of the above two elements
            for (int j = 1; j <= i-1; j++){
                int num = result.get(i-1).get(j-1) + result.get(i-1).get(j);
                row.add(num);
            }
            
            row.add(1); // last element is always 1
            result.add(row);        
        }
        return result;
    }
}
```

#### Expected behavior

Faster performance of the code. 

#### Screenshots

Not Applicable

**Comment by lc-kay** [comment]
Hi @ttelang 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @ttelang 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
