### ISSUE TITLE
Variable Names Should Be Changed for Some Problems

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#3251]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In some problems, there exist variable names that are single uppercase letters. For example, `N` for a number (especially for an integer), `A` for an array, `M` for a matrix, `S` for a string, etc.
It is not a good practice to have a variable name that is a single uppercase letter, or starts with an uppercase letter (e.g. `Str` for a `String` type variable). Therefore, such variable names should be changed so that the names start with lowercase letters and the names are meaningful. For example, `N` should be changed to `n` or `num`, `A` should be changed to `arr` or `nums`, `M` should be changed to `matrix`, `S` should be changed to `s` or `str`, etc.
Although many problems have already been updated and the variable names have been changed in these problems, there still exist some problems that have variable names that are single uppercase letters.
The following 125 problems have variable names that are single uppercase letters. Please change the variable names asap.
223
533
562
576
631
651
656
661
710
727
730
738
739
755
758
760
761
762
763
764
767
776
779
784
788
790
791
793
795
796
798
801
808
809
813
816
817
824
829
831
833
834
837
842
846
848
855
856
857
861
862
863
866
870
880
884
885
886
888
891
893
896
899
900
903
905
908
910
915
916
917
918
920
921
926
930
932
934
940
945
948
952
961
962
974
982
985
991
992
995
996
997
1000
1001
1002
1005
1006
1007
1009
1011
1012
1015
1016
1017
1018
1021
1024
1027
1028
1030
1031
1035
1047
1052
1056
1061
1062
1085
1088
1100
1101
1102
1121
1135
1180

#### Expected behavior
The variable names should be changed so that no variable name will start with an uppercase letter or be a single uppercase letter. All variable names should start with lowercase letters and have meaningful names.

**Comment by lc-kay** [comment]
@stormsunshine Our team is working on this for all our problems and is making a good process. However, it will take some time to update all the old problems. Thank you for understanding.
