### ISSUE TITLE
Include Interval range hint/explanation  - 938. Range Sum of BST

### ISSUE THREAD

**Issue by caleberi** [LeetCode-Feedback/LeetCode-Feedback#3254]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The inclusion of range  explanation in mathematics  on the question .  For example from wikipedia [wikipedia](https://en.wikipedia.org/wiki/Interval_(mathematics))

Including or excluding endpoints
>To indicate that one of the endpoints is to be excluded from the set, the corresponding square bracket can be either replaced with a parenthesis, or reversed. Both notations are described in International standard ISO 31-11. Thus, in set builder notation,
Each interval (a, a), [a, a), and (a, a] represents the empty set, whereas [a, a] denotes the singleton set {a}. When a > b, all four notations are usually taken to represent the empty set.
Both notations may overlap with other uses of parentheses and brackets in mathematics. For instance, the notation (a, b) is often used to denote an ordered pair in set theory, the coordinates of a point or vector in analytic geometry and linear algebra, or (sometimes) a complex number in algebra. That is why Bourbaki introduced the notation ]a, b[ to denote the open interval.[6] The notation [a, b] too is occasionally used for ordered pairs, especially in computer science.

>Some authors use ]a, b[ to denote the complement of the interval (a, b); namely, the set of all real numbers that are either less than or equal to a, or greater than or equal to b.

#### Additional context
> Explain range interval for the question make the question even better for beginners.

**Comment by lc-kay** [comment]
Hi @caleberi 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @caleberi 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
