### ISSUE TITLE
#3333 Permutation in String reports wrong data limits

### ISSUE THREAD

**Issue by Jazzinghen** [LeetCode-Feedback/LeetCode-Feedback#326]
##What kind of the bug
- [x] problem
- [ ] solution
- [ ] language

##Describe the bug
The problem description reports that the data limits are [1, 10000] but empty strings are accepted for either input.

##what language is your code written in
C++

##The code you submit/run
```C++
class Solution {
public:
    bool checkInclusion(string s1, string s2) {
        assert(!s1.empty() && !s2.empty());
        if (s1.size() > s2.size()) {
            return false;
        }
        std::vector<char> s1_freq(26, 0);
        for (char c: s1) {
            ++s1_freq[c - 'a'];
        }
        
        std::vector<char> perm_freq(26, 0);
        // Initialize frequencies
        for (int c = 0; c < s1.size(); ++c) {
            const char next = s2[c];
            ++perm_freq[next - 'a'];
        }
        
        if (perm_freq == s1_freq) {
            return true;
        }
        
        for (int b = 1; b <= (s2.size() - s1.size()); ++b) {
            const char out = s2[b-1];
            const char in = s2[b+s1.size()-1];
            --perm_freq[out - 'a'];
            ++perm_freq[in - 'a'];
            if (perm_freq == s1_freq) {
                return true;
            }
        }
        
        return false;
    }
};
```

##Expected behavior
The program should return encounter some runtime error due to the input parameters are not in the range specified by the problem definition.

##Screenshots
![image](https://user-images.githubusercontent.com/230921/82185752-b0110800-9924-11ea-82b4-50428f53e8c9.png)
![image](https://user-images.githubusercontent.com/230921/82185783-ba330680-9924-11ea-8abf-d5cb8397fd6a.png)
The second image reports a `false` result as I was trying to understand what should be the code behaviour in case of wrong inputs (so I just returned a random value), but the program actually executed instead of failing.

**Comment by CooperCooperCooper** [comment]
Hi @Jazzinghen ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @Jazzinghen ,
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
