### ISSUE TITLE
Missing Test Case - 1839. Longest Substring Of All Vowels in Order

### ISSUE THREAD

**Issue by zhang1pr** [LeetCode-Feedback/LeetCode-Feedback#3263]
#### Your LeetCode username

zhang1pr

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Missing Test Case: "aeiouaeiouaeiouaeiou"

#### Code you used for Submit/Run operation

```
/**
 * @param {string} word
 * @return {number}
 */
var longestBeautifulSubstring = function(word) {
  let str = 'aeiou';  
  let cur = '';  
  let cnt = 0;
  let max = 0;
    
  for (const ch of word) {
    if (!cur) {
      if (ch == 'a') {
        cur = 'a'; 
        cnt++;  
      }
        
      continue;         
    }
      
    if (ch == cur) {
      cnt++;  
    } else {
      let curi = str.indexOf(cur);

      if (ch == str[(curi+1)%5]) {
        cnt++;  
        cur = ch;  
      } else {
        if (ch == 'a') {
          cur = 'a';  
          cnt = 1;    
        } else {
          cur = '';
          cnt = 0;  
        }
      }
    }
      
    if (cur == 'u') max = Math.max(max,cnt);   
  } 
  
  return max; 
};
```

#### Language used for code

JavaScript

#### Expected behavior

This solution counts multiple **aeiou** strings, expected **Wrong Answer** but **Accepted**.

#### Screenshots

<img width="1669" alt="Screen Shot 2021-04-25 at 3 19 34 PM" src="https://user-images.githubusercontent.com/26691304/116006572-d1b94b80-a5d9-11eb-82a3-83eb8123758a.png">

**Comment by lc-kay** [comment]
Hi @zhang1pr 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @zhang1pr 
Thank you for your time. The team reviewed your report and noticed the code already fails after adding other test cases. We appreciate your support!
