### ISSUE TITLE
214题 测试用例有问题

### ISSUE THREAD

**Issue by chenhongda1135** [LeetCode-Feedback/LeetCode-Feedback#327]
** Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
为什么这个测试用例不对呢，输出的不是回文串么

输入: "aabba" 输出 "abbabba" 预期结果 "abbaabba"

**你使用的语言**
C++

**你提交或者运行的代码**
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
        
    }
};
```

**期望行为**
描述你期望的结果

**屏幕截图**
添加屏幕截图辅助我们帮你定位问题

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
建议再仔细调试一下代码，希望这篇内容有帮助：https://leetcode.kf5.com/hc/kb/article/1194344/。后续刷题学习中遇到困难，可通过阅读「题解」解决做题中的一些困惑，也可至 力扣圈子（https://leetcode-cn.com/circle/discussions/questions/?orderBy=HOTTEST&query=） 进行题目交流，以获得更好的支持哟～

**Comment by feiceh** [comment]
建议再仔细调试一下代码，希望这篇内容有帮助：https://leetcode.kf5.com/hc/kb/article/1194344/。 
后续刷题学习中遇到困难，可通过阅读「题解」解决做题中的一些困惑，也可至 力扣圈子（https://leetcode-cn.com/circle/discussions/questions/?orderBy=HOTTEST&query=）进行题目交流，以获得更好的支持。
