### ISSUE TITLE
Missing Test Case - 371. Sum of Two Integers

### ISSUE THREAD

**Issue by MahmoudHamdy00** [LeetCode-Feedback/LeetCode-Feedback#3270]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    int getSum(int a, int b) {
        unsigned int a1=a, b1=b;
        int ans = 0;
        int carry = 0;
        while(b1 != 0) {
            ans = a1 ^ b1;
            carry = (a1&b1)<<1;
            a1 = ans;
            b1 = carry;
        }
        return ans;
    }
};
```

**Comment by lc-kay** [comment]
Hi @MahmoudHamdy00 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @MahmoudHamdy00 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
