### ISSUE TITLE
Wrong Solution - 1662. Check If Two String Arrays are Equivalent

### ISSUE THREAD

**Issue by Ralts1337** [LeetCode-Feedback/LeetCode-Feedback#3271]
#### Your LeetCode username

Ralts1337

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Solution Approach 5. I copied the solution code and submitted. The submission result says "Wrong Answer".
For test case:
["ab","c"]
["a","bcd"]

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean arrayStringsAreEqual(String[] word1, String[] word2) {
        String string2 = String.join("", word2);
        int string2Length = string2.length();
        int index = 0;
        for (String s : word1) {
            for (char c : s.toCharArray()) {
                if (index >= string2Length || c != string2.charAt(index)) {
                    return false;
                }
                index++;
            }
        }
        return true;
    }
}
```

#### Language used for code
Java

#### Expected behavior

Should return false for the test case above

#### Screenshots

![image](https://user-images.githubusercontent.com/37420353/116017386-0547b480-a672-11eb-89b5-235f91e49661.png)

**Comment by lc-kay** [comment]
Hi @Ralts1337 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@Ralts1337 Our team has reviewed your report, and it is valid. We will work on improving the overall article shortly. Thank you for your time.
