### ISSUE TITLE
Incorrect test case - 3. Longest Substring Without Repeating Characters

### ISSUE THREAD

**Issue by coddiw0mple** [LeetCode-Feedback/LeetCode-Feedback#3272]
#### Your LeetCode username

coddiw0mple 

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

A wrong test case seems to be in use. The test case with input as 'dvdf' and desired output/answer as 3

#### Code you used for Submit/Run operation

```python
class Solution:
    def lengthOfLongestSubstring(self, s: str) -> int:
        s = [i for i in s]
        temp = []
        n = len(s)
        if n == 1:
            return 1
        maxlen = 0
        for i in range(n):
            print(temp)
            if s[i] not in temp:
                temp.append(s[i])
                if i == (n-1): 
                    s.append(temp)
            else:
                s.append(temp)
                temp = [s[i]]
                
        for l in s[n:]:
            if len(l) > maxlen:
                maxlen = len(l)
        return maxlen       
```

#### Language used for code

Python

#### Expected behavior

The test case 'dvdf' asks for an answer of 3, whereas it should be 2

**Comment by stormsunshine** [comment]
The correct answer is indeed 3. The longest substring is "vdf".

**Comment by coddiw0mple** [comment]
I am the biggest dumbass I am sincerely sorry, it was 4 am
