### ISSUE TITLE
1109. 航班预订统计

### ISSUE THREAD

**Issue by 849061136** [LeetCode-Feedback/LeetCode-Feedback#3273]
**你的 LeetCode 用户名**

home page：https://leetcode-cn.com/u/hanxin_hanxin/

**Bug 类型**
- [1109 ] 航班预订统计

**描述**
点击“执行代码”，会报错----global name 'num_flights' is not defined
但是提交，可以AC

**你使用的语言**
C++/python3

**你提交或者运行的代码**
class Solution:
    def corpFlightBookings(self, bookings: List[List[int]], n: int) -> List[int]:
        #---------- 典型差分，模板题，上下车，这次是上下飞机
        f = [0 for _ in range(n + 2)]
        for [s, e, diff] in bookings:
            f[s] += diff
            f[e+1] -= diff
        for i in range(1, n + 2):
            f[i] += f[i-1]
        f.pop(0)
        f.pop(-1)
        return f

class Solution 
{
public:
    vector<int> corpFlightBookings(vector<vector<int>>& bookings, int n) 
    {
        //-------典型差分，模板题，上下车，上下飞机
        vector<int> f(n + 2, 0);
        for (auto b: bookings)
        {
            int s = b[0],   e = b[1],   diff = b[2];
            f[s] += diff;
            f[e+1] -= diff;
        }
        for(int i = 1; i < n + 2; i ++)
            f[i] += f[i-1];
        f.pop_back();
        f.erase(f.begin());
        return f;
    }
};

```

**期望行为**
点击“执行代码”，别报错了。

**屏幕截图**
![问题](https://user-images.githubusercontent.com/64452770/116030239-b60f7d00-a68d-11eb-910c-f52d9136893f.PNG)


**额外的上下文**
我通过“# 15874 工单， 联系了技术支持。告诉我可以在这里提交。详细描述”

**Comment by feiceh** [comment]
@849061136  你好，当前题目已更新，ID：chanxin_hanxin 给予积分奖励，请查收。
