### ISSUE TITLE
91. 解码方法

### ISSUE THREAD

**Issue by daizhengkang** [LeetCode-Feedback/LeetCode-Feedback#3274]
func numDecodings(s string) int {
	tmp:=0
	//sum1:=0
	single(0,byte(len(s)-1),s)
	tmp=sum
	sum=0
	double(1,byte(len(s)-1),s)
	tmp+=sum
	return tmp
}
var sum int = 0
func single(i,n byte,s string) {
	if i == n {
		parseInt, _ := strconv.ParseInt(string(s[i]), 10, 8)
		if parseInt==0{
			return
		}
		sum++
		return
	}

	if i < n {
		parseInt, _ := strconv.ParseInt(string(s[i]), 10, 8)
		if parseInt==0{
			return
		}
		single(i + 1,n,s)
		double(i + 2,n,s)
	} else {
		return
	}
	return
}

func double(i ,n byte,s string) {
	if i == n {
		parseInt, _ := strconv.ParseInt(string(s[i-1:i+1]), 10, 8)
		if parseInt<10||parseInt>26{
			return
		}
		sum++
		return
	}

	if i < n {
		parseInt, _ := strconv.ParseInt(string(s[i-1:i+1]), 10, 8)
		if parseInt<10||parseInt>26{
			return
		}
		single(i + 1,n,s)
		double(i + 2,n,s)
	} else {
		return
	}
	return
}

**Comment by feiceh** [comment]
代码有问题，可以再仔细检查一下“//sum1:=0 “ 处添加 sum = 0
