### ISSUE TITLE
Missing Test Case - 1642. Furthest Building You Can Reach

### ISSUE THREAD

**Issue by HuaTsai** [LeetCode-Feedback/LeetCode-Feedback#3276]
#### Your LeetCode username
HuaTsai

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
I manually return the answer as the current index plus 1 if the available bricks exactly reach zero.
This should be wrong, but my code gets AC.

#### Code you used for Submit/Run operation
```
class Solution {
public:
  int furthestBuilding(vector<int>& heights, int bricks, int ladders) {
    multiset<int> largests;
    int i;
    for (i = 0; i < (int)heights.size() - 1; ++i) {
      int diff = heights[i + 1] - heights[i];
      if (diff <= 0) continue;
      if (largests.size() < ladders) {
        largests.insert(diff);
        continue;
      }
      if (!largests.size() || diff <= *largests.begin()) {
        bricks -= diff;
      } else {
        bricks -= *largests.begin();
        largests.erase(largests.begin());
        largests.insert(diff);
      }
      if (bricks == 0) {
        // The logic is wrong here, the reachable building may be further
        return i + 1;
      } else if (bricks < 0) {
        return i;
      }
    }
    return i;
  }
};
```

#### Language used for code
C++

#### Expected behavior
A test case `[1, 4, 8, 8], 3, 1` describes this condition.
`i = 0` -> `diff = 3`, min heap insert `3`, available bricks is `3`
`i = 1` -> `diff = 4`, min heap pop `3` and insert `4`, available bricks is `3 - 3 = 0`, and the code returns `i + 1 -> 2`
Therefore, I recommend to add some test cases which completely use all the bricks, and then a few of next `diff`s are zero.

#### Screenshots
![1642_bug](https://user-images.githubusercontent.com/26832169/116061658-b3288280-a6b5-11eb-8454-d35682435f99.png)

**Comment by lc-kay** [comment]
Hi @HuaTsai 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @HuaTsai 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
