### ISSUE TITLE
TLE for provided solution - 523. Continuous Subarray Sum

### ISSUE THREAD

**Issue by c2tarun** [LeetCode-Feedback/LeetCode-Feedback#3278]
#### Your LeetCode username

user8804e

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Code provided in Solution 2 is timing out.

#### Code you used for Submit/Run operation

```
public class Solution {
    public boolean checkSubarraySum(int[] nums, int k) {
        int[] sum = new int[nums.length];
        sum[0] = nums[0];
        for (int i = 1; i < nums.length; i++)
            sum[i] = sum[i - 1] + nums[i];
        for (int start = 0; start < nums.length - 1; start++) {
            for (int end = start + 1; end < nums.length; end++) {
                int summ = sum[end] - sum[start] + nums[start];
                if (summ == k || (k != 0 && summ % k == 0))
                    return true;
            }
        }
        return false;
    }
}
```

#### Language used for code

Java

#### Expected behavior

At least the code provided in Solution should not time out.

**Comment by lc-kay** [comment]
Hi @c2tarun 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@c2tarun Our team has reviewed your report, and as this is a Brute Force solution, it was expected to receive TLE. However, our team has plans to improve this article shortly. Thank you for your time.
