### ISSUE TITLE
1449. Form Largest Integer With Digits That Add up to Target

### ISSUE THREAD

**Issue by denmatfoton** [LeetCode-Feedback/LeetCode-Feedback#328]
In the problem #1449 in the first example there is a mistake. There is written: "You could also paint "997", but "7772" is the largest number." The cost of the number 997 is 5 + 5 + 2 = 12 (9  ->   5, 7 -> 2). The target is 9. Should be 977 instead for example.

**Comment by CooperCooperCooper** [comment]
Hi @denmatfoton ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @denmatfoton ,
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
