### ISSUE TITLE
1491. Average Salary Excluding the Minimum and Maximum Salary

### ISSUE THREAD

**Issue by kavya9678** [LeetCode-Feedback/LeetCode-Feedback#3280]
#### 
kavya9678

#### []solution
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Arrays.sort(salary);
        int len=salary.length;
        double max=salary[len-1];
        double min=salary[0];
        double total=0;
        for(int i=0;i<len;i++){
             total+=salary[i];
        }
        double avg=total-max-min;
        double n=len-2;
        
        avg=avg/n;
        return avg;

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### 
![image](https://user-images.githubusercontent.com/44774092/116127039-f9490a80-a6e4-11eb-9f31-7900c5aeca6c.png)

**Comment by kavya9678** [comment]
Check

**Comment by lc-kay** [comment]
@kavya9678 Please provide the submission details link to your code. Thank you.

**Comment by kavya9678** [comment]
@lc-kay https://leetcode.com/problems/average-salary-excluding-the-minimum-and-maximum-salary/submissions/

**Comment by lc-kay** [comment]
@kavya9678 Please click on 'Accepted', then it will redirect you to the submission details link. Thank you.
