### ISSUE TITLE
Missing Test Case - 60. Permutation Sequence

### ISSUE THREAD

**Issue by satyam4484** [LeetCode-Feedback/LeetCode-Feedback#3281]
#### Your LeetCode username

Satyam_singh

#### Category of the bug

- [ ] Solution

#### Description of the bug

Not getting correct ans even though the code works fine .

#### Code you used for Submit/Run operation

```
// Two Sum
vector<int>fact{0,1,2, 6, 24, 120, 720, 5040, 40320, 362880};
vector<char>digits;
class Solution {
public:
    void solve(int n,int k,string &ans) {
      if(n == 1 ){
        ans.push_back(digits.back());
        return ;
      }
      int id = k/fact[n-1];
      if(k % fact[n-1] == 0) id--;
      ans.push_back(digits[id]);
      k = k - fact[n-1]*id;
      digits.erase(digits.begin()+id);
      solve(n-1,k,ans);
    }
    
    string getPermutation(int n, int k) {
        for(int i = 1 ;i <= n; i++) {
          digits.push_back(i+'0');
        }

        string ans ;
        solve(n,k,ans);
        return ans;
    }
};
```

#### Language used for code
C++ 

#### Additional context

Why it is showing the wrong ans if all the things are correct , the code is running on my local IDE  then why it is showing the wrong ans here ??

**Comment by lc-kay** [comment]
Hi @satyam4484 
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
