### ISSUE TITLE
https://leetcode.com/problems/minimum-increment-to-make-array-unique/solution/

### ISSUE THREAD

**Issue by utkarshj1303** [LeetCode-Feedback/LeetCode-Feedback#3285]
Approach 1: Counting

The time complexity and space complexity are incorrect. 
"
Time Complexity: O(N)O, where N is the length of A.
Space Complexity: O(N).
"

Both the time and space complexity in the solution is 100000 which depending on size of the array could be N, N^2, N^3 etc.

**Comment by lc-kay** [comment]
Hi @utkarshj1303 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @utkarshj1303 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
