### ISSUE TITLE
Typo in problem description - 454. 4Sum II

### ISSUE THREAD

**Issue by alphasingh** [LeetCode-Feedback/LeetCode-Feedback#3286]
#### Your LeetCode username
alphasingh

#### Category of the bug
- Question

#### Description of the bug
There is a typo in the problem statement.

#### Expected behavior
`nums1[i] + nums2[j] + nums3[k] + nums4[l] == 0`

#### Screenshots
https://leetcode.com/problems/4sum-ii/ typo highlighted below in the screenshot in blue color select

![Screenshot from 2021-04-27 08-07-36](https://user-images.githubusercontent.com/25795957/116176384-b06a7380-a72f-11eb-951b-738104c543ef.png)

#### Additional context
`nums1[i] + nums2[j] + nums3[k] + nums[l] == 0` has been mentioned in the problem statement in the second bullet point.

**Comment by lc-kay** [comment]
Hi @alphasingh 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @alphasingh 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
