### ISSUE TITLE
测试用例错误

### ISSUE THREAD

**Issue by yuxuezhong** [LeetCode-Feedback/LeetCode-Feedback#329]
题目10，测试用例：

"ab" ".*"  预期值是 true。

按照题目描述，".*" 只能代表空或者任何重复字符串，代表不了ab。
看很多人在评论里面说这个问题

题目地址：https://leetcode-cn.com/problems/regular-expression-matching/

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认的～

**Comment by feiceh** [comment]
你好，技术验证题目测试用例没有问题，建议认真读题再仔细调试一下代码。
