### ISSUE TITLE
Follow up Should Be Updated for 421. Maximum XOR of Two Numbers in an Array

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#3290]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
For [421. Maximum XOR of Two Numbers in an Array](https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array), the follow up question is:
> Could you do this in `O(n)` runtime?

Here `n` represents the length of `nums`, which should be also mentioned in problem description. For example, the first sentence should be "Given an integer array `nums` with length `n`".
For the follow up question, the time complexity is related to the elements in `nums`, and the best time complexity is not `O(n)`, but `O(n log m)`, where `m` is the maximum element in `nums`.
Therefore, the follow up question should be changed to:
> Could you do this in `O(n log m)` runtime, where `m` is the maximum element in `nums`?

#### Expected behavior
Two points should be changed.
1. The first sentence "Given an integer array `nums`" should be changed to "Given an integer array `nums` with length `n`".
2. The follow up question should be changed to:
   > Could you do this in `O(n log m)` runtime, where `m` is the maximum element in `nums`?

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@stormsunshine Our team has reviewed your report and found the problem and follow-up to be fine as is. Thank you for your time.
