### ISSUE TITLE
Typo in problem Hint - 1642 - Furthest Building You Can Reach

### ISSUE THREAD

**Issue by arpitkaushal** [LeetCode-Feedback/LeetCode-Feedback#3295]
#### Your LeetCode username
arpitkaushal

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the problem [Furthest Building You Can Reach](https://leetcode.com/problems/furthest-building-you-can-reach/), **Hint #2** reads 
> You'll have to do a set of jumps, and choose for each one whether to do it using a rope or bricks. It's always optimal to use ropes in the largest jumps.
However, the question description clearly mentions using "ladder" instead of rope. 

<!-- ```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
``` -->

<!-- #### Language used for code -->
<!-- C++ -->


#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->
The **Hint #2** should have read
> You'll have to do a set of jumps, and choose for each one whether to do it using a **ladder** or bricks. It's always optimal to use **ladders** in the largest jumps.


<!-- #### Screenshots -->
<!-- If applicable, add screenshots to explain your issue. -->



<!-- #### Additional context -->
<!-- Add any other additional context about the bug. -->

**Comment by lc-kay** [comment]
Hi @arpitkaushal 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @arpitkaushal 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!

**Comment by arpitkaushal** [comment]
Hi, I haven't been rewarded 100 LC for my feedback. How long should I wait?

**Comment by lc-kay** [comment]
@arpitkaushal The issue you raised did not qualify for LeetCoins based on our internal standards. Thank you for your time.

**Comment by arpitkaushal** [comment]
I understand. Thanks for replying!
