### ISSUE TITLE
Missing Test Case - 557. Reverse Words in a String III

### ISSUE THREAD

**Issue by ttelang** [LeetCode-Feedback/LeetCode-Feedback#3296]
#### Your LeetCode username

user7066E

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

No need to use StringBuffer method. This needs to be used only when thread safety is required otherwise StringBuilder is prefered. 

#### Code you used for Submit/Run operation

Approach #1 Simple Solution [Accepted]
Line 5, 6
```
 for (String word: words)
            res.append(new StringBuffer(word).reverse().toString() + " ");
```
instead use. 

```
 for (String word: words)
            res.append(new **StringBuilder(word)**.reverse().toString() + " ");
```
#### Expected behavior

The execution time can improved with this code change.

**Comment by lc-kay** [comment]
Hi @ttelang 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
