### ISSUE TITLE
Ambiguous problem statement in #362

### ISSUE THREAD

**Issue by snehasishroy** [LeetCode-Feedback/LeetCode-Feedback#3298]
#### Your LeetCode username
chrisgriffin

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
Problem statement in https://leetcode.com/problems/design-hit-counter/ does not mention that the timestamps to both `hits()` and `getHits()` are always increasing i.e. following cases are invalid:
1. `getHits(301)` followed by `getHits(299)`
2. `hits(200)` followed by `getHits(150)`

Current problem description gives an impression that only the timestamps provided to `hits()` are in increasing order. 
It does not clarify anything about the timestamps received for `getHits()`

Please update the problem statement to clearly mention that both `hits()` and `getHits()` should receive timestamps in increasing order.

**Comment by snehasishroy** [comment]
This issue has been raised and upvoted by other fellow leetcoders as well: https://leetcode.com/problems/design-hit-counter/solution/874528

**Comment by lc-kay** [comment]
Hi @snehasishroy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@snehasishroy Our team has reviewed your report and the problem statement and concluded that no changes are needed. The statement said 

> you may assume that calls are being made to the system in chronological order

This clearly states that all the timestamps are increasing.
