### ISSUE TITLE
C语言版本方法定义不正确

### ISSUE THREAD

**Issue by 375C** [LeetCode-Feedback/LeetCode-Feedback#330]
** Bug 类型**
- [ ] 题目
- [ ] 题解
- [x] 编程语言

**描述**
C语言中用数组来模拟栈，在该题提供的方法中：
```
void hanota(int* A, int ASize, int* B, int BSize, int* C, int CSize)
```
目标数组C的大小无法返回，由于CSize参数初始设定为0,无论如何没法在函数返回时，修改这个值，导致直接结果总为[]，即空数组
**你使用的语言**
C

**期望行为**
将CSize该为指针参数，可以出参返回结果。或是增加int返回值，返回C数组的大小。

**Comment by feiceh** [comment]
感谢反馈，此问题已转给技术团队会尽快确认的～

**Comment by feiceh** [comment]
已修复
