### ISSUE TITLE
Incorrect testcase

### ISSUE THREAD

**Issue by crixodia** [LeetCode-Feedback/LeetCode-Feedback#3302]
#### Your username
gabrielbastidas5g

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Wrong output when the input is [1,1,2]

#### Code you used for Submit/Run operation
```python
class Solution:
    def removeDuplicates(self, nums: List[int]) -> int:
        rep = 0
        i = 0
        j = 0
        while i < len(nums):
            while j < len(nums):
                if i != j and nums[i] == nums[j]:
                    rep += 1
                    nums.pop(j)
                    i = 0
                    break
                j += 1
            j = 0
            i += 1
        return rep
            
```

#### Language used for code
Python

#### Expected behavior

Testing the case [1,1,2] I got as an output [1]. Even testing it on a local environment and an online compiler where the solution is correct.

#### Screenshots

Output on LeetCode
![Imgur](https://i.imgur.com/xFCosRh.png)

Output on local environment
![Imgur](https://i.imgur.com/nD2xzKa.png)

**Comment by lc-kay** [comment]
@crixodia Please provide the problem title for this issue. Thank you.

**Comment by crixodia** [comment]
[Merge Two Sorted Lists
](https://leetcode.com/problems/merge-two-sorted-lists/)

**Comment by lc-kay** [comment]
<img width="1909" alt="Screen Shot 2021-04-29 at 10 13 02 AM" src="https://user-images.githubusercontent.com/70870126/116591322-86ea4d00-a8d3-11eb-84ba-fac5f203cbcb.png">
Please use the driver code we provide for the problem. In addition, for the problem Merge Two Sorted Lists, the test case you have provided receives an invalid test case error.
