### ISSUE TITLE
699. Falling Squares - Description enhancement 

### ISSUE THREAD

**Issue by sonpth** [LeetCode-Feedback/LeetCode-Feedback#3303]
#### Your LeetCode username
sonpth

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
I believe the description can be better with additional figures, and without a typo
![image](https://user-images.githubusercontent.com/1577921/116337303-43350c00-a81d-11eb-8a5e-aad3088f59ee.png)

#### Code you used for Submit/Run operation
N/A

#### Language used for code
N/A

#### Expected behavior
N/A

#### Screenshots
Feel free to add those figures to the problem description if you think it helps to visualize the problem
![image](https://user-images.githubusercontent.com/1577921/116337913-3d8bf600-a81e-11eb-9d31-ec4b844cb686.png)

![image](https://user-images.githubusercontent.com/1577921/116337740-ee45c580-a81d-11eb-833b-b2a7f1b37902.png)

**Comment by lc-kay** [comment]
Hi @sonpth 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @sonpth 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
