### ISSUE TITLE
Incorrect Big-O memory in #353 Snake

### ISSUE THREAD

**Issue by RobJacobson** [LeetCode-Feedback/LeetCode-Feedback#3304]
#### Category of the bug
- [ ] Question
- [ X ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

_From my comments to the official solution:_

An observation:  The problem description provides these constraints:  
```
1 <= width, height <= 10^4
1 <= food.length <= 50
```

The maximum amount of food is tiny.  Given this, the snake can never be longer than 51 segments.  As a consequence:

(1) The snake does not require O(W * H) memory.  That would mean a potential worst case of O(10^4 x 10^ 4) = O(100,000,000) memory.  (In some languages, like Python this might require 1GB of RAM or more, given the overhead with objects and arrays!)

Instead, it requires O(f) memory, where f is the amount of food.  For practical purposes, this is equivalent to O(1) memory.

(2) For similar reasons, there isn't a Big-O performance benefit from using a separate hash set to store the snake's segment positions.  In Python, you can simply iterate over the deque -- which contains at most O(51) segments -- to check for collisions.  This simplifies the code substantially and removes a parameter:
```
        # Have we collided with the tail?
        if (row, col) in self.snake:
            return -1
```

(In other languages, this might be more difficult, but not impossible.)  

Using a hash set might be an optimization, but it doesn't provide a meaningful Big-O improvement in performance.  In practice, I had exactly the same timings on LeetCode (240ms) for both approaches.

My complete code is below:

```
class SnakeGame:

    def __init__(self, width: int, height: int, food: List[List[int]]):
        self.snake = collections.deque([(0, 0)])
        self.food = list(reversed(food))
        self.width = width
        self.height = height
        self.directions = {
            "U": (-1, 0),
            "D": (1, 0),
            "L": (0, -1),
            "R": (0, 1)
        }

    def move(self, direction: str) -> int:
        
        # Get new coordinates of snake head
        drow, dcol = self.directions[direction]
        row, col = self.snake[-1][0] + drow, self.snake[-1][1] + dcol
        
        # Are we out of bounds?
        if not (0 <= row < self.height and 0 <= col < self.width):
            return -1

        # Is there food at this position?
        if self.food and row == self.food[-1][0] and col == self.food[-1][1]:  
            self.food.pop()             # Consume the food
        else:
            tail = self.snake.popleft()    # Contract the tail by one segment
        
        # Have we collided with the tail?
        if (row, col) in self.snake:
            return -1
        
        # Advance the head
        self.snake.append((row, col))
        
        # Return the current score
        return len(self.snake) - 1
```

#### Code you used for Submit/Run operation
Above

#### Language used for code
Python

#### Expected behavior
N/A

#### Screenshots
N/A

#### Additional context
N/A

**Comment by lc-kay** [comment]
Hi @RobJacobson 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
