### ISSUE TITLE
Solution - 1832. Check if the Sentence Is Pangram

### ISSUE THREAD

**Issue by shaswatsingh19** [LeetCode-Feedback/LeetCode-Feedback#3305]
#### Category of the bug

- [Check] Solution

#### Description of the bug
 Solution for 1832. Check if the Sentence Is Pangram 

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean checkIfPangram(String sentence) {
        Map<Character,Integer> map = new HashMap<>();
        String alpha = "abcdefghijklmnopqrstuvwxyz";
        for (int i=0;i<alpha.length();i++){
            char c = alpha.charAt(i);
            map.put(c,1);
        }
        for (int i=0;i<sentence.length();i++){
            char c = sentence.charAt(i);
            map.replace(c,map.get(c)-1);
        }
        for(Integer val : map.values()){
            if (val==1){
                return false;
            }
        }
        
        return true;

    }
}
```

#### Language used for code
Java

#### Expected behavior

Using hashmap of character and integer first add the alphabet of English language into hashmap with key as the character and value as 1
after that use another loop to replace the map value decremented by 1 
and again use a loop to check if there is any value equals to 1 which means that this character doesn't exist there that it is not a pangram

**Comment by lc-kay** [comment]
@shaswatsingh19 If you'd like to share your solution, please post it in the problem discuss section https://leetcode.com/problems/check-if-the-sentence-is-pangram/discuss/?currentPage=1&orderBy=newest_to_oldest&query=. 

We encourage you to share more content-related issues here with us for [valid content contribution rewards](https://leetcode.com/discuss/general-discussion/526802/File-Problem-and-Solution-Content-Issues-to-Our-GitHub-Public-Feedback-Repo-Now!). Thank you again for your support and understanding.
