### ISSUE TITLE
Solution(Article) Type Error: 300 Longest Increasing Subsequence

### ISSUE THREAD

**Issue by Aashu-Jha** [LeetCode-Feedback/LeetCode-Feedback#3309]
#### Your LeetCode username

atheist-monk

#### Category of the bug
- [ ] Solution

#### Description of the bug

In 1st approach of solution, the space complexity is given wrong (n * n), which is of second approach.
The correct space complexity is n because the stack can maximum go upto n (length of nums).

#### Code you used for Submit/Run operation

```
public int lengthOfLIS(int[] nums) {
        return recursion(nums, 0, -(int)1e8);
        
    }
    
    public int recursion(int[] nums, int idx, int pre, int[] dp) {
        if(idx == nums.length) {
            return 0;
        }
        if(dp[idx] != -1) return dp[idx];
        
        int c = 0;
        if(nums[idx] > pre) 
            c = 1 + recursion(nums, idx + 1, nums[idx]);

        int d = recursion(nums, idx + 1, pre);
        return Math.max(d,c);
        
    }
```

#### Language used for code

JAVA

**Comment by lc-kay** [comment]
Hi @Aashu-Jha 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@Aashu-Jha Thanks for letting us know. We're already aware that this article is not up to our high standards, and it will be rewritten as soon as one of our solution article writers has time.
