### ISSUE TITLE
Missing Test Case - 436. Find Right Interval

### ISSUE THREAD

**Issue by rahulkumar-srm** [LeetCode-Feedback/LeetCode-Feedback#3315]
#### Your LeetCode username

rahul89798

#### Category of the bug
- [x] Solution
- [x] Missing Test Cases 

#### Description of the bug
User is able to submit below provided solution successfully even though it is not a valid solution because it fails for below missing test case.
MissingTest Case : [[4,5],[2,5],[6,7]]

#### Code you used for Submit/Run operation

```
public class Solution
{
    public int[] FindRightInterval(int[][] intervals)
    {
        int min = int.MaxValue, max = int.MinValue;
        int[] ans = new int[intervals.GetLength(0)];
        Dictionary<int, int> dict = new Dictionary<int, int>();

        for (int i = 0; i < intervals.GetLength(0); i++)
        {
            dict[intervals[i][0]] = i;
            min = Math.Min(min, intervals[i][0]);
            max = Math.Max(max, intervals[i][0]);
        }

        for (int i = 0; i < intervals.GetLength(0); i++)
        {
            if (dict.ContainsKey(intervals[i][1]))
                ans[i] = dict[intervals[i][1]];
            else if (intervals[i][1] > max)
                ans[i] = -1;
            else
                ans[i] = FindInterval(dict, intervals[i][1], i, min, max);
        }

        return ans;
    }

    public int FindInterval(Dictionary<int, int> dict, int num, int idx, int low, int high)
    {
        int i = 1;

        while(num - i >= low || num + i <= high)
        {
            if (dict.ContainsKey(num - i) && dict[num - i] != idx)
                return dict[num - i];
            else if (dict.ContainsKey(num + i) && dict[num + i] != idx)
                return dict[num + i];
            else
                i++;
        }

        return -1;
    }
}
```

#### Language used for code

c#

#### Expected behavior

Solution should not be accepted as it is not a valid one.

#### Screenshots

![image](https://user-images.githubusercontent.com/59435417/116506266-8acd9d80-a8da-11eb-8d14-708ce68922b5.png)

#### Additional context

Missing test case provided above should be added in order to validate the solution properly.

**Comment by lc-kay** [comment]
Hi @rahulkumar-srm 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @rahulkumar-srm 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
