### ISSUE TITLE
缺少测试用例：题号：1496

### ISSUE THREAD

**Issue by hellowmq** [LeetCode-Feedback/LeetCode-Feedback#3316]
**你的 LeetCode 用户名**
hellowmq

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [x] 缺少测试用例

**描述**
目前测试用例不够，使用测试用例进行验证 `String path = "EESWN";`
依照题意应当输出 `true`，此时路径相交于平面坐标 (0, 1)。
使用下面的代码可以通过目前 LeetCode 的所有 Case，但在 `EESWN` 这个自定义 Case 会失败。

**你使用的语言**
Java

**你提交或者运行的代码**
```java
// 判断路径是否相交
class Solution {
    public boolean isPathCrossing(String path) {
        if(path.contains("NS")||path.contains("SN")||path.contains("EW")||path.contains("WE"))
            return true;
        char[] pat = path.toCharArray();
        int N = 0;
        int S = 0;
        int E = 0;
        int W = 0;
        for(int i=0; i<pat.length; i++){
            switch(pat[i]){
                case 'N':
                    N++;
                    break;
                case 'S':
                    S++;
                    break;
                case 'E':
                    E++;
                    break;
                case 'W':
                    W++;
                    break;
            }
            if(N==S && E==W) 
                return true;
        }
        return false;
    }
}
```

**期望行为**
依照题意，这个 Case 应该失败

**屏幕截图**
<img width="680" alt="截屏2021-04-29 下午1 39 23" src="https://user-images.githubusercontent.com/33039572/116506684-5369eb80-a8f0-11eb-90b7-623bec7aae5e.png">"
**额外的上下文**

实际上依照题意，路径可以在任意点地位置相交，上面的算法只能解决相交点在 (0, 0) 的情况

**Comment by lc-kay** [comment]
@feiceh Our team has added this test case, please reward the user.

**Comment by feiceh** [comment]
@hellowmq 你好，当前题目已添加测试用例，ID：hellowmq 给予积分奖励，请查收。
