### ISSUE TITLE
Error Test Case - 588. Design In-Memory File System

### ISSUE THREAD

**Issue by maanguo27** [LeetCode-Feedback/LeetCode-Feedback#3317]
#### Category of the bug
-  Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Faulty test case

["FileSystem","ls","mkdir","addContentToFile","ls","readContentFromFile","addContentToFile","readContentFromFile","addContentToFile","ls","readContentFromFile"]
[[],["/"],["/a/b/c"],["/a/b/c/d","hello world"],["/"],["/a/b/c/d"],["/a/b/c/d"," hello hello world"],["/a/b/c/d"],["/a/b/c/dddd","winstons"],["/a/b/c"],["/a/b/c/dddd"]]

#### Code you used for Submit/Run operation

```
class FileSystem {

    private File root;
    
    public FileSystem() {
        root = new File("/");      
    }
    
    public List<String> ls(String path) {
        File res = find(path, false);
        if(res == null) return null;
        List<String> output = new ArrayList<>();
        
        if(res.isFile) output.add(res.name);
        else{
            
            for (Map.Entry<String,File> entry : res.files.entrySet()) {
                output.add(entry.getKey());
            }
        }
        Collections.sort(output);
        return output;
    }
    
    public void mkdir(String path) {
        find(path, true);
    }
    
    public void addContentToFile(String filePath, String content) {
        File res = find(filePath, true);
        if(res.isFile){
            res.content = res.content + content;
        }else{
            res.isFile = true;
            res.content = content;
        }
    }
    
    public String readContentFromFile(String filePath) {
        File res = find(filePath, false);
        if(res == null) return null;
        return res.content;
    }
    
    private File find(String path, boolean create) {
        String[] paths = path.split("/");
        File f = root;
        for(String p : paths){
            if(p.isEmpty()) continue;
            if(!f.files.containsKey(p)){
                if(!create) return null;
                File temp = new File(p);
                f.files.put(p,temp);
                f = temp;
            }else{
                f = f.files.get(p);
            }
        }
        return f;
    }
    
    public class File{
        Map<String, File> files;
        String content;
        boolean isFile;
        String name;
        
        public File(String name){
            this.name = name;
            this.isFile = false;
            this.files = new HashMap<>();
        }
        
        public File(String name, String content){
            this.name = name;
            this.isFile = true;
            this.content = content;
        }
    }
}

/**
 * Your FileSystem object will be instantiated and called as such:
 * FileSystem obj = new FileSystem();
 * List<String> param_1 = obj.ls(path);
 * obj.mkdir(path);
 * obj.addContentToFile(filePath,content);
 * String param_4 = obj.readContentFromFile(filePath);
 */
```

#### Language used for code

java

#### Expected behavior

[null,[],null,null,["a"],"hello world",null,"hello world hello hello world",null,["d","dddd"],"winstons"]

#### Screenshots

![image](https://user-images.githubusercontent.com/82486988/116508548-3baa4d00-a887-11eb-8ee4-f91f6e571eea.png)

**Comment by sh-helen** [comment]
+1 testcase is wrong, submitted with python, it's ok if I run the code with this testcase, but wrong on submit

**Comment by lc-kay** [comment]
Hi @maanguo27 
Thank you for reaching out to us. The test case is correct. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.

**Comment by sh-helen** [comment]
@lc-kay it does't look so, we have a input `addContentToFile` `/a/b/c/dddd","winstons` which adds dddd file into the directory a/b/c with content `winstons`, next instruction is `ls` in the root and the next one is  `readContentFromFile` with path `/a/b/c/dddd`, the is nothing in between instructions, so it should output `winstons` as per description, but it does not, so I assume it's wrong

**Comment by maanguo27** [comment]
@lc-kay  The test case expected answer is clearly wrong. It has nothing to do with the global variable, I have it reset in the constructor. Just as @sh-helen said above, you guys just need to adjust the expected result for that case.

**Comment by lc-kay** [comment]
@sh-helen @maanguo27 I apologize for the misunderstanding. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @sh-helen @maanguo27 
Thank you for your time. It appears that the expected output was not updated, and we have fixed that issue. We appreciate your support!
