### ISSUE TITLE
Test case contribution for  Online Stock Span

### ISSUE THREAD

**Issue by paragpachpute** [LeetCode-Feedback/LeetCode-Feedback#332]
**What kind of the bug**
- [.] problem
- [ ] solution
- [ ] language

**Describe the bug**
For a test case, I am getting runtime error in my code. However, the same code is accepted by online judge. Hence, I feel we can add a test case to catch this anomaly.

**what language is your code written in**
Java

**The code you submit/run**
```
class StockSpanner {

    Stack<PricePos> stack;
    int counter = 0;
    public StockSpanner() {
        stack = new Stack<>();
        stack.push(new PricePos(Integer.MAX_VALUE, 0));
    }
    
    public int next(int price) {
        counter++;
        while (price >= stack.peek().price)
            stack.pop();

        int ans = counter - stack.peek().pos;
        stack.push(new PricePos(price, counter));
        return ans;
    }
    
    class PricePos {
        int price;
        int pos;
        
        public PricePos(int price, int pos) {
            this. price = price;
            this.pos = pos;
        }
    }
}

/**
 * Your StockSpanner object will be instantiated and called as such:
 * StockSpanner obj = new StockSpanner();
 * int param_1 = obj.next(price);
 */
```

**Expected behavior**
For test case:
["StockSpanner","next","next"]
[[],[100],[2147483647]]

The expected output is:
[null,1,2]

But through my code I am getting runtime error, still, the solution is accepted by online judge.
Hence, I feel we should add this test case in the test case pack.

**Screenshots**

**Additional context**

**Comment by CooperCooperCooper** [comment]
Hi @paragpachpute ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @paragpachpute ,
Thank you for your time. Upon reviewing the test case, we found it does not comply with `1 <= price <= 10^5`, so it's not suitable for this problem. We appreciate your time and support.
