### ISSUE TITLE
A typo in Solution of #1229

### ISSUE THREAD

**Issue by JamesHuang-TW** [LeetCode-Feedback/LeetCode-Feedback#3321]
#### Category of the bug
- [x] Solution

#### Description of the bug

There is a typo in Solution of #1229. More precisely, in Line 5 of the algorithm of Approach 2, _start1 > start2_ should be **start1 <= start2.**

**Comment by lc-kay** [comment]
Hi @JamesHuang-TW 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @JamesHuang-TW 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
