### ISSUE TITLE
Missing Test Case - 1295. Find Numbers with Even Number of Digits

### ISSUE THREAD

**Issue by kapeed2091** [LeetCode-Feedback/LeetCode-Feedback#3322]
#### Your LeetCode username

kapeed2091

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [*] Missing Test Cases 

#### Description of the bug

Given input is an array of integers. Integers include negative numbers as well.
Testcases doesn't have negative numbers. 
If negative numbers arent part of the question, then input should be specified as array of non-negative integers.

#### Code you used for Submit/Run operation

```
class Solution:
    def findNumbers(self, nums: List[int]) -> int:
        count = 0
        for each_number in nums:
            if len(str(each_number)) % 2 == 0:
                count += 1
        
        return count
```

#### Language used for code

Python3

#### Expected behavior

For non-negative integers this should fail

#### Additional context

I am assuming number of digits in -2256 is 4, but the code specified above returns 5

**Comment by lc-kay** [comment]
@kapeed2091 Per the constraints of this problem, only positive integers are valid. If you try to run the test case -2256, it will return Invalid Testcase error - 'nums' must consist of values from 1 to 100000 only. Thank you for your time.
