### ISSUE TITLE
Example Test Case Error- 537. Complex Number Multiplication

### ISSUE THREAD

**Issue by cmunigwe** [LeetCode-Feedback/LeetCode-Feedback#3323]
#### Your LeetCode username
cmunigwe 

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X ] Missing Test Cases 

#### Description of the bug
 Invalid testcase used as example 

#### Code you used for Submit/Run operation

No code, just try to use second example testcase ("1+-1i", "1+-1i")

```
```

#### Expected behavior

Expected example to run with output "0+-2i" as stated in example. Instead received an "Invalid testcase, Invalid input" error.

**Comment by lc-kay** [comment]
Hi @cmunigwe 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @cmunigwe 
Thank you for your time. Our team has fixed the validator. We appreciate your support!
