### ISSUE TITLE
Missing Test Case - 34. Find First and Last Position of Element in Sorted Array

### ISSUE THREAD

**Issue by Chetanpaliwal22** [LeetCode-Feedback/LeetCode-Feedback#3324]
#### Your LeetCode username
Chetanpaliwal22

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
There can be a overflow when we do low+high/2 to determine the mid value in binary search. My submission with this value got accepted.

#### Code you used for Submit/Run operation

```
class Solution {
    public int[] searchRange(int[] nums, int target) {
        int firstPos = binarySearch(nums, target, true);
        int lastPos = binarySearch(nums, target, false);
        return new int[]{firstPos,lastPos};
    }
    
    public int binarySearch(int[] nums, int target, boolean searchFirst){
        int low = 0;
        int high = nums.length-1;
        int mid = -1;
        int res = -1;
        while(low<=high){
            mid = low+(high-low)/2;
            if(nums[mid] == target){
                res = mid;
                if(searchFirst){
                    high = mid -1;
                }else {
                    low = mid + 1;
                }
            }
            else if(nums[mid]>target){
                high = mid-1;
            }else{
                low = mid+1;
            }
        }
        return res;
    }
    
}
```

#### Language used for code
Java

#### Expected behavior
The above metnioed code will pass because I am using low+(high-low)/2 to determine the mid index. The code with (low+high)/2 should fail bcz of the overflow

**Comment by lc-kay** [comment]
@Chetanpaliwal22 Can you please provide the missing test case that will cause this solution to fail? Thank you.

**Comment by lc-kay** [comment]
Hi @Chetanpaliwal22 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
