### ISSUE TITLE
Solutions don't run - 1597. Build Binary Expression Tree From Infix Expression

### ISSUE THREAD

**Issue by pavanteja-potnuru** [LeetCode-Feedback/LeetCode-Feedback#3325]
#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation
```
class Solution {
public:
    Node* expTreeHelper(string s, vector<int> &bracketIndex, int si, int ei) {
        if(s.length() == 0 || si>ei) return nullptr;
        if(si == ei) return new Node(s[si]);
        Node* root = new Node();
        if(bracketIndex[si]!=-1) {
            if(bracketIndex[si] == ei) return expTreeHelper(s, bracketIndex, si+1, ei-1);
            root->val = s[bracketIndex[si]+1];
            root->left = expTreeHelper(s, bracketIndex, si+1, bracketIndex[si]-1);
            root->right = expTreeHelper(s, bracketIndex, bracketIndex[si]+2, ei);
        } else {
            root->val = s[si+1];
            root->left = new Node(s[si]);
            root->right = expTreeHelper(s, bracketIndex, si+2, ei);
        }
        
        return root;
    }
    Node* expTree(string s) {
        int n = s.length();
        vector<int> bracketIndex(n, -1);
        stack<int> pIndices;
        for(int i=0;i<n;i++){
            if(s[i] == '(') {
                pIndices.push(i);
            }
            else if(s[i] == ')'){
                bracketIndex[i] = pIndices.top();
                bracketIndex[pIndices.top()] = i;
                pIndices.pop();
            }
        }
        return expTreeHelper(s, bracketIndex, 0, n-1);
    }
};
```

#### Language used for code
 C++

#### Expected behavior
Submission should accept any binary tree with(Given conditions, i.e. leafnodes are for operands and non-leafnodes are for operators) infix expression as given string.

#### Screenshots
![image](https://user-images.githubusercontent.com/41474837/116652204-5c1afa00-a9a2-11eb-9678-42a668a076fe.png)

**Comment by neal2018** [comment]
Hey, I think it is your code that yields wrong answers, and the oj gives the right judgment.

For example, when the input is `"3*4-2*5"`, your code yields a binary tree `[*,3,-,null,null,4,*,null,null,2,5]`. If we visualize your answer, we have 

![image](https://user-images.githubusercontent.com/46561493/116981445-117ae400-acfa-11eb-922a-185f665d6787.png)

which is corresponding to `3*(4-(2*5))` and different from `"3*4-2*5"`.

**Comment by pavanteja-potnuru** [comment]
Can you please explain clearly the difference between `"3*(4-(2*5))"` and "3*4-2*5". I mean in form of binary tree formed from each of them.

**Comment by pavanteja-potnuru** [comment]
PS says return any valid binary expression tree, which its in-order traversal `reproduces s after omitting the parenthesis` from it.

**Comment by neal2018** [comment]
PS also requires
> Operands must also appear in the same order in both s and the in-order traversal of the tree.

That is to say, the values that they evaluate to should be the same.

As for your case, in `3*(4-(2*5))`, `-` is evaluated after `2*5`, while in `3*4-2*5`, `-` is evaluated lastly.

**Comment by pavanteja-potnuru** [comment]
Ok, got it. 
PS says Operands must appear in same order. So I thought just numbers need to be appeared in same order.
@neal2018 Thanks for explaining clearly.

Note: But I think PS should clearly mention as order of execution instead of Operands order. Please share you thoughts.

Thank you

**Comment by neal2018** [comment]
Yes, PS should be clearer.

**Comment by lc-kay** [comment]
@pavanteja-potnuru It appears that your issue has been resolved. I have relayed your feedback in regards to the problem statement to our team to take into consideration. Thank you for your time.
