### ISSUE TITLE
Missing Test Case - 213. House Robber II

### ISSUE THREAD

**Issue by PARESHKUMAR1004** [LeetCode-Feedback/LeetCode-Feedback#3326]
#### Your LeetCode username
<pareshkumar742>

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [1] Missing Test Cases 

#### Code you used for Submit/Run operation
House Robber ||
 int rob(vector<int>& nums) {
        int a,b,c=0,maxm=0,i,n=nums.size();
        a=nums[0];
        if(n==1)return a;
        b=max(nums[0],nums[1]);
        maxm=max(a,b);
        if(n==2)return b;
        for(i=2;i<=n-2;i++)
        {
            c=max(nums[i]+a,b);
            a=b;
            b=c;
        }
        maxm=max(maxm,c);
        a=nums[1];
        b=max(nums[1],nums[2]);
        //
        maxm=max(maxm,b);//the program also is submitted without this line of code
        //
        for(i=3;i<=n-1;i++)
        {
            c=max(nums[i]+a,b);
            a=b;
            b=c;
        }
        maxm=max(maxm,c);
        return maxm;
        
        
        
    }

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@PARESHKUMAR1004 Please provide the formatted code or the submission details link and the missing test case you wish to report. Once more information is available, I will reopen this ticket. Thank you for your time.
