### ISSUE TITLE
Missing Test Case - 1838. Frequency of the Most Frequent Element

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#3328]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets TLE on the following testcase:
[1838.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6403352/1838.txt)

#### Code you used for Submit/Run operation

```
from collections import Counter
class Solution:
    def maxFrequency(self, nums: List[int], k: int) -> int:
        counter = Counter(nums)
        seq = sorted(counter)

        ret = 0
        for i, num in enumerate(seq):
            freq = counter[num]
            left = k
            for j in reversed(range(i)):
                diff = num - seq[j]
                count = counter[seq[j]]

                if left <= diff * count:
                    freq += left // diff
                    break
                left -= diff * count
                freq += count

            if ret < freq:
                ret = freq
        return ret
```

#### Language used for code

Python3

#### Expected behavior

The code gets TLE.

**Comment by lc-kay** [comment]
@hqztrue The code you provided already TLE on test case 62. Therefore, we will not add the test case you provided. Thank you for your time. 
<img width="1440" alt="Screen Shot 2021-04-30 at 11 39 32 AM" src="https://user-images.githubusercontent.com/70870126/116739771-f2eab500-a9a8-11eb-8c67-c18b3b114be9.png">

**Comment by hqztrue** [comment]
Ok, then try the following C++ code:
```
class Solution {
public:    
    int maxFrequency(vector<int>& nums, int k) {
        if((int)nums.size() < 2) return nums.size();
        unordered_map<int, int> mp;
        for (int num: nums) {
            ++mp[num];
        }
        vector<pair<int, int> > r;
        for (pair<int, int> pp: mp) {
            r.push_back(pp);
        }
        sort(r.begin(), r.end());
        int ans = r[0].second;
        //try all the possibilities
        for (int i = 1; i < (int)r.size(); ++i) {
            int curCost = k, prev = i - 1, cur = r[i].second;
            while(curCost > 0 && prev >= 0) {
                //this much needed to transform one element
				//if we can't take this element at all.
                if(curCost/(r[i].first - r[prev].first) <= 0) break;
                cur += min(curCost/(r[i].first - r[prev].first), r[prev].second);
                curCost = curCost - (r[i].first - r[prev].first) * min(curCost/(r[i].first - r[prev].first), r[prev].second);
                --prev;
            }
            ans = max(cur, ans);
        }
        return ans;
        
    }
};
```
It also gets Accepted but will get TLE on the above testcase.

**Comment by lc-kay** [comment]
Hi @hqztrue 
I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
