### ISSUE TITLE
230. Kth Smallest Element in a BST (Validation Failed)

### ISSUE THREAD

**Issue by saurabhmarpadge** [LeetCode-Feedback/LeetCode-Feedback#333]
**What kind of the bug**
- [ ] Kth Smallest Element in a BST
- [ ] Should throw invalid BST Error
- [ ] Java

**Describe the bug**
When we pass an invalid input for BST which doesn't qualify the property of BST that left node(left subtree) < current node < right node(right subtree). It accepts the input and shows the result for following input. It should not accept the input and process it.
It should not accept invalid BST as input.

Below input is invalid
[1,2,null,3,null,4,null,5]
4
[5,null,4,null,3,null,2,null,1]
4

**what language is your code written in**
Java

**The code you submit/run**
```
// Kth Smallest Element in a BST
class Solution {
    Stack<TreeNode> stack;
    public int kthSmallest(TreeNode root, int k) {
        initInOrder(root);
        while(k-->1){
            next();
        }
        return next();
    }
    public void initInOrder(TreeNode root){
        stack = new Stack<>();
        TreeNode curr = root;
        while(curr!=null){
            stack.push(curr);
            curr = curr.left;
        }
    }
    
    public int next(){
        if(stack.isEmpty()){
            return 0;
        }
        TreeNode node = stack.pop();
        TreeNode curr = node.right;
        while(curr!=null){
            stack.push(curr);
            curr = curr.left;
        }
        return node.val;
    }
}

```

**Expected behavior**
It should throw error for invalid BST or invalid tree or invalid input.
Should not accept invalid input and process it. 

**Screenshots**
Below image is not a valid BST
![image](https://user-images.githubusercontent.com/14952088/82422927-b62bf380-9aa0-11ea-8b1b-89aa7db6307a.png)

![image](https://user-images.githubusercontent.com/14952088/82423003-d065d180-9aa0-11ea-9c38-ddce577428a7.png)

![image](https://user-images.githubusercontent.com/14952088/82424165-68b08600-9aa2-11ea-88a5-072037d0f69f.png)

It doesn't follow property of BST **(left node/subtree < curr node < right node/subtree)**

**Additional context**

**Comment by CooperCooperCooper** [comment]
Hi @saurabhmarpadge ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @saurabhmarpadge ,
Thank you for your time. Since this problem is relatively old, we've updated the problem to a more updated version. However, since the test case is not valid, we did not add it to the problem.
