### ISSUE TITLE
Missing Test Case - 970. Powerful Integers

### ISSUE THREAD

**Issue by yyeung-lam** [LeetCode-Feedback/LeetCode-Feedback#3330]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution:
    def powerfulIntegers(self, x: int, y: int, bound: int) -> List[int]:
        if x == 1 and y == 1:
            if 2 <= bound:
                return [2]
            else:
                return []
        ans = set()
        ans.add(2)
        if x < y:
            x, y = y, x
        a, b = x, y
        while x <= bound:
            if x + 1 <= bound:
                ans.add(x+1)
            while y != 1 and y <= bound:
                if y + 1 <= bound:
                    ans.add(y+1)
                if x + y <= bound:
                    ans.add(x + y)
                y *= b
            y = b
            x *= a
            
        return list(ans)
```

#### Expected behavior

My solution should fail in the case where bound < 2. But it passed.

#### Additional context

Test case: x = 2, y = 3, bound = 1

**Comment by lc-kay** [comment]
Hi @yyeung-lam 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @yyeung-lam 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
