### ISSUE TITLE
Constraint of the problem is inaccurate - 129. Sum Root to Leaf Numbers

### ISSUE THREAD

**Issue by mastermeow** [LeetCode-Feedback/LeetCode-Feedback#3331]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The Java version of this problem has an issue: the max value of int is 2147483647 (i.e., 2^31-1). 
According to the constraints of the problem:
1) the depth of the tree will **not exceed** 10, meaning the max depth can be 10;
2) The max Node.val is 9.

This means that I can get a root-to-leaf path that represents 9999999999, which exceeds max int and will cause an integer overflow. 

To avoid this, Leetcode should either change the constraints (e.g. depth of tree is strickly less than 10) of this question or change the return type of the function `sumNumbers() ` from int to double.

#### Language used for code

Java

**Comment by lc-kay** [comment]
Hi @mastermeow 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @mastermeow 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by mastermeow** [comment]
> Hi @mastermeow
> Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

Hi @lc-kay 
My LeetCode ID is master_meow. Thanks.
