### ISSUE TITLE
python3提交结果与测试用例运行矛盾

### ISSUE THREAD

**Issue by BartSu** [LeetCode-Feedback/LeetCode-Feedback#3334]
**你的 LeetCode 用户名**
BartSu

**Bug 类型**
- [78] 题目
- [x] 题解
- [python] 编程语言

**描述**
测试用例运行时通过那个测试用例的，但提交的时候现实那个测试用例出错

**你使用的语言**
python3

**你提交或者运行的代码**
```
ans = []
class Solution:
    def subsets(self, nums: List[int]) -> List[List[int]]:
        global ans
        length = len(nums)
        
        for i in range(length + 1):
            self.subsetsHelper(nums, [], i)

        return ans

    def subsetsHelper(self, nums: List[int], temp: List[int], count: int):
        global ans
        length = len(nums)

        if count == 0:
            ans.append(temp.copy())

        for i in range(length):
            temp.append(nums[i])
            self.subsetsHelper(nums[i+1:], temp, count - 1)
            temp.pop(-1)
```

**期望行为**
出错的话，至少不是这个测试用例呀

**屏幕截图**
![image](https://user-images.githubusercontent.com/23166423/116755019-570a8900-aa3c-11eb-8dbf-0a21bf47392a.png)

**额外的上下文**
用python3解题的时候遇到过几次这样的情况。

**Comment by zerotrac** [comment]
请不要使用全局变量

**Comment by feiceh** [comment]
@BartSu 你好，如果出现测试用例结果和提交结果不一致的情况，可以再仔细检查并调试一下代码，或点击这里：「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」 获得更多帮助。

同时也可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
