### ISSUE TITLE
Problem 970 -- Powerful Integers

### ISSUE THREAD

**Issue by jraman** [LeetCode-Feedback/LeetCode-Feedback#3338]
Problem 970 -- [Powerful Integers](https://leetcode.com/problems/powerful-integers/)

The given [solutions](https://leetcode.com/problems/powerful-integers/solution/) (both Python and Java) do not work for the edge case `bound = 0`.  Attempting to compute log of 0 results in `ValueError: math domain error`.

Can be easily fixed by adding a check for `bound`.

**Comment by lc-kay** [comment]
@jraman Please provide the test case that will fail the two solutions. Thank you.

**Comment by jraman** [comment]
> @jraman Please provide the test case that will fail the two solutions. Thank you.

``` python
x = 2, y = 3, bound = 0
```

And here is the error when the python3 version is run on leetcode:
``` python
ValueError: math domain error
    a = bound if x == 1 else int(log(bound, x))
Line 4 in powerfulIntegers (Solution.py)
    ret = Solution().powerfulIntegers(param_1, param_2, param_3)
Line 52 in _driver (Solution.py)
    _driver()
Line 63 in <module> (Solution.py)
```

![image](https://user-images.githubusercontent.com/157409/117056939-b7662880-acd1-11eb-98c5-aef1c7034cb3.png)

**Comment by lc-kay** [comment]
Hi @jraman 
I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @jraman 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!
