### ISSUE TITLE
Kth Smallest Element in a BST - Testcase

### ISSUE THREAD

**Issue by adan1901** [LeetCode-Feedback/LeetCode-Feedback#334]
I would like to submit a test case for [Kth Smallest Element in a BST](https://leetcode.com/problems/kth-smallest-element-in-a-bst/).
The test case is meant to differentiate between O(n²) and O(n) solutions. (30,000 nodes, only left children).
[testcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/4656440/testcase.txt)
The O(n²) solution is:
[squareSolution.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/4656469/squareSolution.txt)
An example of an O(n) solution is:
[linearSolution.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/4656563/linearSolution.txt)

Even if a n² solution is to be accepted, a test that stresses out the bad performance would be useful. Based on current tests, sometimes an O(n²) solution is shown among the most efficient solutions (top 0.25%)

**Comment by CooperCooperCooper** [comment]
Hi @adan1901 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @adan1901 ,
Thank you for your time. We've taken a thorough look at this problem and adjusted upper bound for the number of elements of the BST that is set to 10^4; however, the provided test case is too big for the current technicalities of our platform, so we will be keeping it on file and consider it in the future.
