### ISSUE TITLE
C++ language submission is not added

### ISSUE THREAD

**Issue by maddler-hub** [LeetCode-Feedback/LeetCode-Feedback#3340]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by maddler-hub** [comment]
C++ submission must be added so that we can see the fastest solution possible and the lowest memory solution must also be revealed

**Comment by lc-kay** [comment]
@maddler-hub Please provide the problem number for this issue. Thank you.

**Comment by lc-kay** [comment]
Hi @maddler-hub 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
