### ISSUE TITLE
Missing Test Case - 745. Prefix and Suffix Search

### ISSUE THREAD

**Issue by Gaurav5ingh** [LeetCode-Feedback/LeetCode-Feedback#3344]
#### Your LeetCode username 
gauravsingh_

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
-  Missing Test Cases 

####  A clear and concise description of what the bug is. 
This problem has weak test cases because my O(q * n) solution passes in 644ms, where, q = no. of queries and n = no. of words.

#### Code you used for Submit/Run operation

```
class WordFilter {
public:
    struct Trie {
      vector<vector<int>> trie, idx;
      int alpha;
      Trie() {
        alpha = 26;
        trie.emplace_back(alpha, -1);
        idx.emplace_back();
      }
      void insert(string &s, int &id) {
        int tn = 0, n = s.length();
        for (int i = 0; i < n; i++) {
          int c = s[i] - 'a';
          if (trie[tn][c] == -1) {
            trie[tn][c] = trie.size();
            trie.emplace_back(alpha, -1);
            idx.emplace_back();
          }
          tn = trie[tn][c];
          idx[tn].emplace_back(id);
        }
      }
      vector<int> search(string &s) {
        int tn = 0, n = s.length();
        for (int i = 0; i < n; i++) {
          int c = s[i] - 'a';
          if (trie[tn][c] == -1) return {};
          tn = trie[tn][c];
          if (i == n - 1) return idx[tn];
        }
        return {};
      }
    };
    Trie pre, suf;
    WordFilter(vector<string>& words) {
      int n = words.size();
      for (int i = 0; i < n; i++) {
        string word = words[i];
        pre.insert(word, i);
        reverse(word.begin(), word.end());
        suf.insert(word, i);
      }
    }
    
    int f(string prefix, string suffix) {
      reverse(suffix.begin(), suffix.end());
      vector<int> preIdx = pre.search(prefix);
      vector<int> sufIdx = suf.search(suffix);
      while (preIdx.size() && sufIdx.size()) {
        if (preIdx.back() == sufIdx.back()) return preIdx.back();
        if (preIdx.back() < sufIdx.back()) sufIdx.pop_back();
        else preIdx.pop_back();
      }
      return -1;
    }
};

```

#### Language used for code
C++

#### Expected behavior
Expected TLE. Reason:- For every query, f() runs in O(n) time by going to each of the n words.
This can happen in the worst case where all the words end with the same letter (say, 'b'), and the first word is the only word starting with unique letter (say, 'a') i.e. no other word starts with 'a' except the first word.
Now let's have all the queries like ["a", "b"].
Inside f(), 'preIdx' will contain only index 0, while 'sufIdx' will contain all the indices 0, 1, 2,..., n - 1.
This costs O(n) time for every query. 

#### Screenshots
![image](https://user-images.githubusercontent.com/36332787/116790839-2b3ae200-aad4-11eb-972a-0c1929bd04f8.png)
![image](https://user-images.githubusercontent.com/36332787/116790896-735a0480-aad4-11eb-8ea6-72f7d6d386d3.png)
![image](https://user-images.githubusercontent.com/36332787/116790921-8e2c7900-aad4-11eb-8325-7c3d8a57afd8.png)

**Comment by lc-kay** [comment]
@Gaurav5ingh For a valid missing test case report, please provide the custom test case that will fail this solution. Thank you.

**Comment by Gaurav5ingh** [comment]
[in.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6426141/in.txt)

**Comment by Gaurav5ingh** [comment]
![image](https://user-images.githubusercontent.com/36332787/117122631-b6a5c300-adb3-11eb-91f5-e5545438544c.png)

**Comment by Gaurav5ingh** [comment]
this file contains the test-case I am talking about 
[in.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6426180/in.txt)

**Comment by Gaurav5ingh** [comment]
following is the C++ code I wrote to generate this input file:
```
#include <bits/stdc++.h>
using namespace std;

void output(string &s) {
  cout << "\"" << s << "\"";
}
void output(vector<string> &a) {
  cout << '[';
  for (int i = 0; i < a.size(); i++) {
    output(a[i]);
    if (i < a.size() - 1) cout << ',';
  }
  cout << ']';
}
void output(vector<vector<string>> &a) {
  cout << "[[";
  for (int i = 0; i < a.size(); i++) {
    output(a[i]);
    if (i == 0) cout << ']';
    if (i < a.size() - 1) cout << ',';
  }
  cout << ']';
}
int main() {
  freopen("in.txt", "w", stdout);
  ios::sync_with_stdio(false), cin.tie(0);
  int t = 1;
  // cin >> t;
  int tc = t;
  while (t--) {
    // cout << "Case #" << tc - t << ": "; 
    int n = 15000;
    vector<string> call(1, "WordFilter");
    for (int i = 0; i < n; i++) call.push_back("f");
    output(call);
    cout << '\n';
    vector<vector<string>> queries;
    vector<string> init;
    for (int i = 0; i < n; i++) init.push_back(string(10, 'b'));
    init[0][0] = 'a';
    queries.push_back(init);
    vector<string> query = {"a", "b"};
    for (int i = 0; i < n; i++) queries.push_back(query);
    output(queries);
  }
  return 0;
}
```

**Comment by lc-kay** [comment]
Hi @Gaurav5ingh 
Thank you for providing that. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Gaurav5ingh 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
