### ISSUE TITLE
Missing Test Case - 1845. Seat Reservation Manager

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#3345]
#### Your LeetCode username

igor84

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

A brute force solution is accepted but fails on a large test case:

[1845_test_case.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6410092/1845_test_case.txt)

#### Code you used for Submit/Run operation

```
class SeatManager {

    int top =0;
    int[] mySeat; 
    public SeatManager(int n) {
      mySeat = new int[n];
    }
    
    public int reserve() {
        int i=0;
        for(i=0;i<mySeat.length;i++){
            if(mySeat[i]==0){
                mySeat[i]=1;
                break;
            }
        }
        return i+1;
    }
    
    public void unreserve(int seatNumber) {
       mySeat[seatNumber-1]=0; 
    }
}
```

#### Language used for code

Java

#### Expected behavior

The solution should not be accepted since it fails on the test case

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/116791449-69aaaf80-aa88-11eb-81f0-c45e1b894bf6.png)

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
