### ISSUE TITLE
Missing Test Case - 745. Prefix and Suffix Search

### ISSUE THREAD

**Issue by parashar-rahul** [LeetCode-Feedback/LeetCode-Feedback#3346]
#### Your LeetCode username
parashar-rahul

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Missing Test Case:
The question mentions `If there is no such word in the dictionary, return -1`. However, my solution passed all test cases without the appropriate code. When I ran a custom test that would expect `-1` as the output, my solution threw a NPE. This would imply the test cases listed for the question are not exhaustive (my solution should not have been accepted).
In the code below, the `private int read(String s) {}` method would throw a null pointer exception at `t = t.next[n];` if the word does not exist in the Trie.

#### Code you used for Submit/Run operation

```
// 745. Prefix and Suffix Search
class WordFilter {

    Trie trie;
    
    public WordFilter(String[] words) {
        trie = new Trie();
        for (int i=0 ; i<words.length; i++) {
            int n = words[i].length();
            for (int j=0; j<n; j++) {
                StringBuilder w = new StringBuilder(words[i].substring(j)).append("{").append(words[i]);
                insert(w.toString(), i);
            }
        } 
    }
    
    public int f(String prefix, String suffix) {
        return read(new StringBuilder(suffix).append("{").append(prefix).toString());
    }
    
    private void insert(String s, int index) {
        Trie t = trie;
        for (char c : s.toCharArray()) {
            int n = c - 'a';
            if (t.next[n] == null) {
                t.next[n] = new Trie();
            }
            t = t.next[n];
            t.index = index;
        }
    }
    
    private int read(String s) {
        Trie t = trie;
        for (char c : s.toCharArray()) {
            int n = c - 'a';
            t = t.next[n];
        }
        return t.index;
    }
    
    private class Trie {
        
        Trie[] next;
        int index;
        
        public Trie() {
            index = 0;
            next = new Trie[27];
        }
    }
}
```

#### Language used for code
Java

#### Expected behavior

Test Case:
`["WordFilter","f"]
[[["apple"]],["a","a"]]`

Expected Result (as per description): `-1`
Actual Result: `java.lang.NullPointerException
  at line 36, WordFilter.read
  at line 17, WordFilter.f
  at line 63, __Driver__.__helperSelectMethod__
  at line 84, __Driver__.__helper__
  at line 105, __Driver__.main`

Correction to code that solved the bug:
```
    private int read(String s) {
        Trie t = trie;
        for (char c : s.toCharArray()) {
            int n = c - 'a';
            if (t.next[n] == null) {
                return -1;
            }
            t = t.next[n];
        }
        return t.index;
    }
```

**Comment by lc-kay** [comment]
Hi @parashar-rahul 
Thank you for your time. The solution you provided already fails on a recently added test case, therefore, it is no longer valid. We appreciate your support!
