### ISSUE TITLE
5733. 最近的房间 | 数据弱

### ISSUE THREAD

**Issue by zerotrac** [LeetCode-Feedback/LeetCode-Feedback#3347]
**你的 LeetCode 用户名**

不告诉你

**Bug 类型**
- [x] 测试数据

**描述**

题目数据较弱，会使得暴力算法通过所有测试数据

**你提交或者运行的代码**

见 https://leetcode-cn.com/problems/closest-room/solution/gui-bing-pai-xu-er-fen-cha-zhao-su-jie-x-ayfw/

**需要添加的测试数据**

添加一组很大的测试数据即可，例如下面的代码

https://paste.ubuntu.com/p/HPNqyzXx7J/

生成的测试数据，会导致上面的代码超出时间限制

**期望行为**

上面的代码超出时间限制

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认～

**Comment by feiceh** [comment]
你好，当前题目问题已修复，力扣会定期更新，保障稳定和体验优化。
