### ISSUE TITLE
284. 顶端迭代器 补充测试用例

### ISSUE THREAD

**Issue by liangteng** [LeetCode-Feedback/LeetCode-Feedback#335]
** Bug 类型**
- [x] 题目
- [ ] 题解
- [ ] 编程语言

**描述**
我的代码在跑我自己构造的用例时，会答案错误or运行出错，但能被平台ac。
我觉得平台的用例偏弱，没有考察到设计的正确性和鲁棒性。
既然这是一道设计题，而且还在提示4中提到了google guava这种生产环境类库，我觉得题目的考察点应该向工程和生产环境倾斜下，多贴近实战环境，代码的正确性和鲁棒性是基本要求，不考察这两点实在有点说不过去。
所以想补充一个测试用例，希望可以帮助童鞋们做出正确且鲁邦的设计。

**你使用的语言**
C++

**你提交或者运行的代码**
```
class PeekingIterator : public Iterator {
public:
	PeekingIterator(const vector<int>& nums) : Iterator(nums) {
	    // Initialize any member here.
	    // **DO NOT** save a copy of nums and manipulate it directly.
	    // You should only use the Iterator interface methods.
	    
	}
	
    // Returns the next element in the iteration without advancing the iterator.
	int peek() {
		if (_cache != INT_MIN) {
			return _cache;
		}
		_cache = Iterator::next();
		//_flag = !_flag;
		return _cache;
	}
	
	// hasNext() and next() should behave the same as in the Iterator interface.
	// Override them if needed.
	int next() {
		if (_cache != INT_MIN) {
			int ret = _cache;
			_cache = INT_MIN;
			return ret;
		}
		return Iterator::next();
	}
	
	bool hasNext() const {
		return _cache != INT_MIN || Iterator::hasNext();
	}
private:
	int _cache{INT_MIN};
};
```

**期望行为**
输入：
["PeekingIterator","peek","peek","next","next","hasNext"]
[[[-2147483648,2,3]],[],[],[],[],[]]
期望输出：
[null,-2147483648,-2147483648,-2147483648,2,true]

**屏幕截图**
上面我贴的代码有设计缺陷（默认值，生产环境中很容易被忽视但是出问题的点），虽然能ac，但跑我自己写的测试用会给出错误答案来。
![image](https://user-images.githubusercontent.com/8230627/82456750-37a67480-9ae7-11ea-833d-830c974726f0.png)

正确答案应该如下：
![image](https://user-images.githubusercontent.com/8230627/82456084-55bfa500-9ae6-11ea-916f-8da168a20d92.png)

**额外的上下文**
添加额外的上下文信息

**Comment by feiceh** [comment]
感谢反馈，此问题已转给题目运营团队会尽快确认的～

**Comment by feiceh** [comment]
感谢反馈，因题目涉及到全球，经题目团队综合评估反馈，该用例暂不添加。我们不可能对每个 hard code 的代码去做测试用例，这个主要还是看用户自觉。非常感谢您这样的积极用户对力扣网站的支持，祝您生活愉快。ˆ＾‿＾
