### ISSUE TITLE
Missing Test Case for 745. Prefix and Suffix Search

### ISSUE THREAD

**Issue by michielbaird** [LeetCode-Feedback/LeetCode-Feedback#3350]
#### Your LeetCode username
michielbaird

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I wrote a solution that has a worst case performance of `O(p*p*n)` where `p` is the number of words, and n is the length of the words.  This solution based on the parameters of the problem should do much worse than the provided solution. However, the solution runs in half the time. So I wrote a more diabolical test case.

#### Code you used for Submit/Run operation

```
use std::cmp::Ordering;
use std::collections::HashSet;

struct Trie {
    children: Vec<Option<Box<Trie>>>,
    indexes: Vec<i32>,
}

impl Trie {
    fn new() -> Self {
        let mut children = vec![];
        for i in 0..26 {
            children.push(None);
        }
        Self {
            children,
            indexes: vec![],
        }
    }
    fn add<I>(&mut self, mut iter: I, w_index: i32)
    where 
    I: Iterator<Item=char> {
        let ref_c = 'a' as usize;
        match iter.next() {
            Some(c) => {
                let c = (c as usize) - ref_c;
                if self.children[c].is_none() {
                    self.children[c] = Some(Box::new(Trie::new()));
                }
                let mut child = self.children[c].as_mut().unwrap();
                child.indexes.push(w_index);
                child.add(iter, w_index);
            },
            None => ()
        } 
    }
    fn get_indexes<'a, I>(&'a self,  mut iter: I) -> Option<&'a Vec<i32>>
    where 
    I: Iterator<Item=char> {
        let ref_c = 'a' as usize;
        match iter.next() {
            Some(c) => {
                let c = (c as usize) - ref_c;
                if self.children[c].is_none() {
                    return None;    
                }
                let mut child = self.children[c].as_ref().unwrap();
                child.get_indexes(iter)
            },
            None => Some(&self.indexes)
        }     
    }
}

struct WordFilter {
    prefix_trie: Trie,
    suffix_trie: Trie
}


/** 
 * `&self` means the method takes an immutable reference.
 * If you need a mutable reference, change it to `&mut self` instead.
 */
impl WordFilter {
    fn new(words: Vec<String>) -> Self {
        let mut prefix_trie = Trie::new();
        let mut suffix_trie = Trie::new();
        for i in (0..words.len()).rev() {
            prefix_trie.add(words[i].chars(), i as i32);
            suffix_trie.add(words[i].chars().rev(), i as i32);
        }
        Self {
            prefix_trie,
            suffix_trie
        }
    }
    
    fn f(&self, prefix: String, suffix: String) -> i32 {
        let pre_indexes_opt = self.prefix_trie.get_indexes(prefix.chars());
        let suf_indexes_opt = self.suffix_trie.get_indexes(suffix.chars().rev());

        if pre_indexes_opt.is_some() && suf_indexes_opt.is_some() {
            let pre_indexes = pre_indexes_opt.unwrap();
            let suf_indexes = suf_indexes_opt.unwrap();
            let mut pre_i = 0;
            let mut suf_i = 0;
            while pre_i < pre_indexes.len() && suf_i < suf_indexes.len() {
                if pre_indexes[pre_i] < suf_indexes[suf_i] {
                    suf_i += 1;
                } else if pre_indexes[pre_i] > suf_indexes[suf_i] {
                    pre_i += 1;    
                } else {
                    return pre_indexes[pre_i];    
                }
            }
            return -1;
            
        } else {
            return -1;    
        }
    }
}
```

#### Language used for code

Rust

#### Expected behavior

This solution should perform worse (maybe even TLE) for the parameters of the problem.

#### Screenshots

![image](https://user-images.githubusercontent.com/1434283/116795517-74664400-aa8a-11eb-98c2-c41120d1f1d5.png)
This is should be slower `O(p*p*n)`.

![image](https://user-images.githubusercontent.com/1434283/116795975-a1682600-aa8d-11eb-90b4-51a87f977cc9.png)

Solution with a `O(p*n*n)` runtime

![image](https://user-images.githubusercontent.com/1434283/116795655-6bc23d80-aa8b-11eb-9b65-8379df0aee16.png)
Proposed test case with `O(p*p*n)` solution

![image](https://user-images.githubusercontent.com/1434283/116795625-39184500-aa8b-11eb-9c26-d0432e412c1e.png)
Proposed test case with `O(p*n*n)` solution

#### Additional context

Testing the the this test case forces you to go through all the indexes before we miss.

Proposed Test Case:
Test Case exceeds Github limit see link.
https://pastebin.com/eacn6aEV

**Comment by lc-kay** [comment]
Hi @michielbaird 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @michielbaird 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
