### ISSUE TITLE
133. Clone Graph empty graph case violates problem constraints

### ISSUE THREAD

**Issue by lamalex** [LeetCode-Feedback/LeetCode-Feedback#3352]
#### Your LeetCode username
lamalex

#### Category of the bug
- [x] Question

#### Description of the bug
Empty graph edge case violates problem constraint. 
With an empty graph, `[]` the `Node` is `nullish` so `Node.val` is not in the range `[1,100]`.
Different from the single node case `[[]]`.

>Constraints:
> 1 <= Node.val <= 100
> Node.val is unique for each node.
> Number of Nodes will not exceed 100.
> There is no repeated edges and no self-loops in the graph.
> The Graph is connected and all nodes can be visited starting from the given node.

With an empty graph `Node.val` is not in the range of `[1, 100]`.

#### Code you used for Submit/Run operation
```php
class Solution {
    
    private $visited = [];
    /**
     * @param Node $node
     * @return Node
     */
    function cloneGraph($node) {
        if (array_key_exists($node->val, $this->visited)) {
            return $this->visited[$node->val];
        }
        
        $clonedNode = new Node($node->val);
        
        $this->visited[$node->val] = $clonedNode;
        
        foreach($node->neighbors as $neighbor) {
            $clonedNode->neighbors[] = $this->cloneGraph($neighbor);
        }
        
        return $clonedNode;
    }
}
```

#### Language used for code
PHP

#### Expected behavior
Solution should pass despite empty graph case not being handled because empty graph is out of the range of possibilities given in the problem description.

**Comment by lc-kay** [comment]
Hi @lamalex 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@lamalex Our content team checked the test case and constraints and concluded that both are correct as is. If you have further questions, please refer to the problem discuss section. Thank you for your time.
