### ISSUE TITLE
Missing Test Case - 1849. Splitting a String Into Descending Consecutive Values

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#3354]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution fails on the following testcase:
"64424509442147483647"

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean splitString(String s) {
        int cur=0;
        for(int i=0;i<s.length()-1;i++){
            cur=cur*10+s.charAt(i)-'0';
            if(dfs(s.substring(i+1),cur)){
                return true;
            }
        }
        return false;
    }
    private boolean dfs(String s,int max){
        int cur=0;
        for(int i=0;i<s.length();i++){
            cur=cur*10+s.charAt(i)-'0';
        }
        if(cur==max-1){
            return true;
        }
        cur=0;
        for(int i=0;i<s.length();i++){
            cur=cur*10+s.charAt(i)-'0';
            if(cur<max-1){
                continue;
            }else if(cur>max-1){
                break;
            }
            if(dfs(s.substring(i+1),cur)){
                return true;
            }
        }
        return false;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Output: true
Expected: false

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
