### ISSUE TITLE
A typo in the solution of: 1586. Binary Search Tree Iterator II

### ISSUE THREAD

**Issue by jinnyy** [LeetCode-Feedback/LeetCode-Feedback#3355]
#### Your LeetCode username

jinnyy

#### Category of the bug
- [x] Solution

#### Description of the bug

In algorithm section of Approach 2, One bullet point item is written as `hext`.
I think this may be `next`. (because there is a method named next in the question.) 
Please take a review on this. Thanks :)

#### Expected behavior

`hext` -> `next`

#### Screenshots

![image](https://user-images.githubusercontent.com/26596684/116804074-e99f4b00-ab56-11eb-827d-b78fd233ef06.png)

**Comment by lc-kay** [comment]
Hi @jinnyy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @jinnyy 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
