### ISSUE TITLE
Wrong answer to testcase- 1217. Minimum Cost to Move Chips to The Same Position

### ISSUE THREAD

**Issue by vodnalasricharan** [LeetCode-Feedback/LeetCode-Feedback#3356]
#### Your LeetCode username
vodnalasricharan

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The question is not clearly specified and the answer for the test case is provided wrong.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int minCostToMoveChips(vector<int>& position) {
        int cost=0;int key=position[0];
        for(int i=1;i<position.size();i++){
            cost+=(position[i]-key)%2;
        }
        return cost;
    }
};
```

#### Language used for code
 C++ 

#### Expected behavior

The question clearly specifies that the cost for moving position[i]+1 units is 1 .In the sample test cases2 it is clearly specified that the cost for arranging array [2,2,2,3,3] is 2 units .But in the unseen test cases it is expecting that the output for [2,3,3] is 1 unit.
This is completely wrong answer. **I ask you to change the answer for the testcase.**

#### Screenshots

![leetcode_1217](https://user-images.githubusercontent.com/50229017/116809820-c88e2880-ab5d-11eb-8326-8b3055dff499.PNG)

**Comment by lc-kay** [comment]
@vodnalasricharan The expected output is correct. First step: Move the chip at position 2 to position 3 with cost = 1. Total cost is 1. If you have further questions, please refer to the problem discuss section. Thank you for your time.
