### ISSUE TITLE
Kth Smallest Element in a BST Test Case Issue

### ISSUE THREAD

**Issue by ahujapankaj16** [LeetCode-Feedback/LeetCode-Feedback#336]
**What kind of the bug**
 problem
**Describe the bug**
Solution when executed for certain test case it displays proper answer but when submitted returns 
Wrong answer.
**what language is your code written in**
Python

**The code you submit/run**
```# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right

l=[]
def inorder(root,k):
    if root is None:
        return
    inorder(root.left, k)
    l.append(root.val)
    inorder(root.right,k)
    
class Solution:
    def kthSmallest(self, root: TreeNode, k: int) -> int:
        
        value = inorder(root,k)
        print(l)
        return l[k-1]
        
```
        
**Expected behavior**
It should have passed test case.
**Screenshots**
![image](https://user-images.githubusercontent.com/32018631/82471491-640cc180-9ae4-11ea-822b-8eb769c5a1dc.png)

**Comment by CooperCooperCooper** [comment]
Hi @ahujapankaj16 ,
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
