### ISSUE TITLE
Missing Test Case - 160. Intersection of Two Linked Lists

### ISSUE THREAD

**Issue by impalakdwivedi** [LeetCode-Feedback/LeetCode-Feedback#3370]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@impalakdwivedi Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
