### ISSUE TITLE
Articles - Introduction to N-Ary Trees

### ISSUE THREAD

**Issue by jarevalo9** [LeetCode-Feedback/LeetCode-Feedback#3371]
#### Your LeetCode username
 jarevalo9

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Article link: https://leetcode.com/articles/introduction-to-n-ary-trees/
The link under Classical Recursion Solution called "Solve Tree Problems Recursively" shows a 404 error message
Link: https://leetcode.com/articles/solve-tree-problems-recursively/
![Screen Shot 2021-05-02 at 12 48 33 PM](https://user-images.githubusercontent.com/50852739/116822497-b6ec5700-ab44-11eb-86f9-cec6b223f055.png)

**Comment by lc-kay** [comment]
Hi @jarevalo9 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @jarevalo9 
Thank you for your time. We've used your feedback to update the issue. We appreciate your support!
