### ISSUE TITLE
Typo Error - 1848. Minimum Distance to the Target Element

### ISSUE THREAD

**Issue by vikashchander** [LeetCode-Feedback/LeetCode-Feedback#3372]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In example 2 , inside  explanation  **abs(0-0)=0** not abs(0-0) ==1

Example 2:

Input: nums = [1], target = 1, start = 0
Output: 0
Explanation: nums[0] = 1 is the only value equal to target, so the answer is **abs(0 - 0) = 1**.

**Comment by lc-kay** [comment]
@vikashchander 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @vikashchander 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
