### ISSUE TITLE
Question - 1851. Minimum Interval to Include Each Query

### ISSUE THREAD

**Issue by IgorRud** [LeetCode-Feedback/LeetCode-Feedback#3375]
#### Your LeetCode username

igor84

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The constraints section states that ```queries[i].length == 2```
it should be ```intervals[i].length == 2```

#### Code you used for Submit/Run operation

```
N/A
```

#### Language used for code

N/A

#### Expected behavior

```queries[i].length == 2``` should be changed to ```intervals[i].length == 2```

#### Screenshots

![image](https://user-images.githubusercontent.com/32546406/116827390-bebcf300-ab66-11eb-8a21-e68441dd1f22.png)

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @IgorRud 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
