### ISSUE TITLE
Missing Test Case - 1392. Longest Happy Prefix

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#3376]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets TLE on the following testcase:
[1392.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6412414/1392.txt)

#### Code you used for Submit/Run operation

```
class Solution {
public:
    string longestPrefix(string s) {
        int N = s.size(); string s1=s;
        char *p=&s[0],*p1=&s1[0];
        for (int i = 1; i < N; ++i) {
            //if (0 == memcmp(s.c_str(), s.c_str() + i, N-i)) {
            char t=s1[N-i]; s1[N-i]=0;
            //if (0 == strcmp(s1.c_str(), s.c_str() + i)) {
            if (0 == strcmp(p1, p + i)) {
                //printf("i=%d\n",i);
                return s.substr(0, N-i);
            }
            s1[N-i]=t;
        }
        return "";
    }
};

//IO
int _IO=[](){
	ios::sync_with_stdio(0);
	cin.tie(0); //cout.tie(0);
	return 0;
}();
```

#### Language used for code

C++

#### Expected behavior

The code gets TLE.

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @hqztrue 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
