### ISSUE TITLE
745. Prefix and Suffix Search -- New testcase

### ISSUE THREAD

**Issue by jraman** [LeetCode-Feedback/LeetCode-Feedback#3377]
Question: [745. Prefix and Suffix Search](https://leetcode.com/problems/prefix-and-suffix-search/)

Solution 487771971 which is accepted by the online grader fails the following testcase.

```
["WordFilter","f"]
[[["abbba", "abba"]], ["ab", "ba"]]
```

Expected answer:
```
[null,1]
```

Output of solution 487771971:
```
[null,0]
```

Solution 487771971 picks the longest word (and the longest index if there is more than one), whereas the problem requires just the longest index.

**Comment by lc-kay** [comment]
@jraman Please provide the submission details link to the code that this will fail on. Thank you.

**Comment by jraman** [comment]
> @jraman Please provide the submission details link to the code that this will fail on. Thank you.

https://leetcode.com/submissions/detail/487771971/

**Comment by lc-kay** [comment]
Hi @jraman 
Thank you for providing that. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @jraman 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!
