### ISSUE TITLE
Missing Test Case - 1849. Splitting a String Into Descending Consecutive Values

### ISSUE THREAD

**Issue by wisdompeak** [LeetCode-Feedback/LeetCode-Feedback#3378]
#### Your LeetCode username
wisdompeak

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
Missing test cases to rule out some wrong code that got AC

#### Code you used for Submit/Run operation
```cpp
typedef long long ll;
class Solution {
public:
    bool splitString(string s) 
    {
        while (s.size()>0 && s[0]=='0')
            s.erase(s.begin());
        if (s.size()==0) return false;        
        
        for (int len=1; len < s.size(); len++)
        {
            if (len > (s.size()+1)/2 ) break;            
            if (dfs(s, len, stoll(s.substr(0, len))))
                return true;
        }
        return false;
    }
    
    bool dfs(string&s, int cur, ll num)
    {
        if (cur==s.size()) return true;
        if (s[cur]=='0') return dfs(s, cur+1, num);
        
        for (int len = 1; len + cur <= s.size(); len++)                
        {
            if (len > to_string(num).size()) break;
            int i = cur+len;
            if (num-1 == stoll(s.substr(cur, len)) && dfs(s, i, num-1))
                return true;                
        }
        return false;
    }
};
```

#### Language used for code
C++

#### Expected behavior
For the test case input:
"39000000000"

Expected result is false
The above code outputs wrong answer but got AC.

**Comment by lc-kay** [comment]
Hi @wisdompeak 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @wisdompeak 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
