### ISSUE TITLE
Solution Bug - 630. Course Schedule III

### ISSUE THREAD

**Issue by ankitshah009** [LeetCode-Feedback/LeetCode-Feedback#3380]
#### Your LeetCode username
ankitshah009

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Approach 2: Recursion with Memoization - 

Point 2 and point 3 requires screenshot and text update. 

#### Expected behavior

 - For point Number 2 - a > b is mentioned - but image is for case of a < b
 
 - For point number 3 - b > a is mentioned but image is for case b < a 

#### Screenshots
[Incorrect Description for point 2 and point 3](https://photos.app.goo.gl/TtAQAGYgu4coo3XVA)
[Incorrect description point 2 only - larger image](https://photos.app.goo.gl/WY6kVJF37bmANSUM7)
[Incorrect description point 3 only larger image](https://photos.app.goo.gl/wVwdFYiabHh8foX8A)

**Comment by lc-kay** [comment]
Hi @ankitshah009 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @ankitshah009 
Thank you for your time. Our team has verified your report and will make the necessary changes soon. Have a great day!
