### ISSUE TITLE
Solution Bug - Question 28

### ISSUE THREAD

**Issue by gahfy** [LeetCode-Feedback/LeetCode-Feedback#3382]
#### Your LeetCode username
gahfy

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The solution 3 provided in Java does not work. Actually, there is no O(n) solution to this problem.

Below is the code that makes the solution correct, but now, it is definitely not an O(n) solution :

```java
class Solution {
    // function to convert character to integer
  public int charToInt(int idx, String s) {
    return (int)s.charAt(idx) - (int)'a';
  }

  public int strStr(String haystack, String needle) {
    int L = needle.length(), n = haystack.length();
    if (L > n) return -1;

    // base value for the rolling hash function
    int a = 26;
    // modulus value for the rolling hash function to avoid overflow
    long modulus = (long)Math.pow(2, 31);

    // compute the hash of strings haystack[:L], needle[:L]
    long h = 0, ref_h = 0;
    for (int i = 0; i < L; ++i) {
      h = (h * a + charToInt(i, haystack)) % modulus;
      ref_h = (ref_h * a + charToInt(i, needle)) % modulus;
    }
    
    if (h == ref_h && haystack.substring(0, needle.length()).equals(needle)) return 0;

    // const value to be used often : a**L % modulus
    long aL = 1;
    for (int i = 1; i <= L; ++i) aL = (aL * a) % modulus;

    for (int start = 1; start < n - L + 1; ++start) {
      // compute rolling hash in O(1) time
      h = (h * a - charToInt(start - 1, haystack) * aL
              + charToInt(start + L - 1, haystack)) % modulus;
      while(h < 0) {
          h += modulus;
      }
      //System.out.println(haystack.substring(start, start+needle.length()));
      if (h == ref_h && haystack.substring(start, start+needle.length()).equals(needle)) return start;
    }
    return -1;
  }
}
```

*Recommandation would be to definitely remove the third solution which is only brainfuck*

#### Code you used for Submit/Run operation
Original code as provided in solution 3

#### Language used for code
Java

#### Expected behavior
Having a solution which is working :-)

**Comment by lc-kay** [comment]
Hi @gahfy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @gahfy 
Thank you for your time. The solution article was removed in the past, I will go ahead and close this ticket. Thank you for understanding.
