### ISSUE TITLE
Wrong presentation - 97. Interleaving String

### ISSUE THREAD

**Issue by feliciavan** [LeetCode-Feedback/LeetCode-Feedback#3383]
#### Your LeetCode username

feliciavan

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the official solution, Approach 3, there maybe one minor error in the graph presentation on page 24/36. The arrow position is wrong. It's now pointed to 'b'. I think It should be pointed to 'c'. Thank you for your time.

**Comment by lc-kay** [comment]
Hi @feliciavan 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by feliciavan** [comment]
Hi @lc-kay. Thank you for your response. Please let me know whether I am right or not.

**Comment by lc-kay** [comment]
@feliciavan Our team has verified your report and will be making the necessary changes soon. Thank you for your time.
