### ISSUE TITLE
Incorrect judge output: Q 472 - Concatenated Words

### ISSUE THREAD

**Issue by gupta-arpit** [LeetCode-Feedback/LeetCode-Feedback#3385]
#### Your LeetCode username

fermi-0985-arpit

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The judge's output is null/blank for the attached test case below, however, the expected output is: `["ab"]`

#### Code you used for Submit/Run operation

```
class Solution {
    TrieNode root;
 
    private boolean dfs(String word, int index) {
        if (index == word.length()) {
            return true;
        }

        TrieNode currNode = root.query(word, index);
        while (currNode != null) {
            int len_w = currNode.word.length();
            boolean subResult = dfs(word, index + len_w);
            if (subResult) {
                return true;
            }
            currNode = currNode.links[word.charAt(index + len_w) - 'a'];
            if (currNode != null) {
                currNode = currNode.query(word, len_w + index + 1);
            }
        }
        return false;
    }

    public List<String> findAllConcatenatedWordsInADict(String[] words) {
        root = new TrieNode();
        Arrays.sort(words, (a, b) -> {
            return a.length() - b.length();
        });
        List<String> res = new ArrayList();
        for (String word: words) {
            if (word.length() == 0) {
                continue;
            }
            boolean isValid = dfs(word, 0);
            if (isValid) {
                res.add(word);
            } else {
                root.insert(word, 0);
            }
        }
        return res;
    }
    
    class TrieNode {
        public TrieNode[] links = new TrieNode[26];
        boolean isWord = false;
        String word;
        
        public TrieNode() {};
        
        public void insert(String word, int index) {
            if (word.length() == index) {
                isWord = true;
                this.word = word;
                return;
            }
            char firstChar = word.charAt(index);
            int idx = firstChar - 'a';
            if (links[idx] == null) {
                links[idx] = new TrieNode();
            }
            links[idx].insert(word, index + 1);
        }
        
        public TrieNode query(String word, int index) {
            if (isWord) {
                return this;
            }

            if (word.length() == index) {
                return null;
            }
            
            char firstChar = word.charAt(index);
            int idx = firstChar - 'a';
            if (links[idx] == null) {
                return null;
            }
            return links[idx].query(word, index + 1);
        }
    }
}
```

#### Language used for code

Java

#### Expected behavior

PFA test case: 
[leetcode_q472_testcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/6413809/leetcode_q472_testcase.txt)

The uploaded test case has 601 strings in total. The first 598 strings are of 1000 length each, and the last three are: "a", "b", and "ab".

Since the first 598 strings are of size 1000 each (i.e., same size), they can't be formed using any combination of two other strings. So, the answer should be ["ab"] because "ab" can be formed by concatenating "a" and "b".

What actually happened: The judge return blank/null as expected output.

#### Screenshots

<img width="955" alt="image" src="https://user-images.githubusercontent.com/12170429/116856964-a22dc300-ac19-11eb-9f4d-59f2f0672686.png">

**Comment by lc-kay** [comment]
Hi @gupta-arpit 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @gupta-arpit 
Thank you for your time. The team reviewed your report and noticed the problem was missing constraints and validations. After adding them, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
