### ISSUE TITLE
ImportError in solution of: 914. X of a Kind in a Deck of Cards

### ISSUE THREAD

**Issue by devansh-07** [LeetCode-Feedback/LeetCode-Feedback#3387]
#### Your LeetCode username
devansh-07

#### Category of the bug
- [x] Solution
- [ ] Question
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In Python Code of Approach 2, line 3 is `from fractions import gcd`, which is causing the following error:
```
ImportError: cannot import name 'gcd' from 'fractions'
```
It is throwing this error because `fractions.gcd()` is deprecated. It is removed in Python 3.9 and will no longer work. So, It should be replaced with `from math import gcd`.

#### Code you used for Submit/Run operation

```
class Solution(object):
    def hasGroupsSizeX(self, deck):
        from fractions import gcd
        vals = collections.Counter(deck).values()
        return reduce(gcd, vals) >= 2
```

#### Language used for code
Python3

#### Expected behavior

The line `from fractions import gcd` should be replaced with `from math import gcd` to fix the ImportError.

#### Screenshots

![Screenshot from 2021-05-03 16-13-47](https://user-images.githubusercontent.com/53042477/116867338-926aaa80-ac2a-11eb-9a3e-0ea6f0013406.png)

**Comment by lc-kay** [comment]
@devansh-07 The solution is a Python code, not Python 3. Please select Python instead in the language drop-down, then run the code. Since this is an older solution article, it is written in Python. However, all our newer articles are in Python3. Thank you for your time.
