### ISSUE TITLE
Missing Test Case - 396. Rotate Function

### ISSUE THREAD

**Issue by sudotrigon** [LeetCode-Feedback/LeetCode-Feedback#3388]
#### Your LeetCode username
f1re

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The problem doesn't describe how to handle overflow and the judge gives wrong expected answer for test cases .
E.g. 1. each element in A[] can be INT_MAX and size of A can be 10^5.
E.g. 2. A[] = {1,2,10^9}, the correct answer should be 0 * 1 + 1 * 2 + 2 * 10^9 but the Judge is showing the correct answer as 
1000000002

#### Code you used for Submit/Run operation

```
// Two Sum
#define LL long long
class Solution {
public:
    int maxRotateFunction(vector<int>& A) {
        int n = A.size();
        LL sum = 0;
        for(int& a: A) sum += a;
        
        LL prev = 0;
        for(int i=0; i<n; ++i){
            prev += (LL)i*A[i];
        }
        
        LL res = prev;
        for(int i=n-1; i>0; --i){
            res = max(res, prev+sum-(LL)n*A[i]);
            prev = prev+sum-(LL)n*A[i];
        }
        
        return res;
    }
};
```

#### Language used for code
C++

#### Expected behavior
The result by the judge for the above example should be 2*10^9+2.

#### Screenshots
![image](https://user-images.githubusercontent.com/83594686/116888804-817d6180-ac49-11eb-84a0-a495f4b6eee2.png)

#### Additional context
NA

**Comment by lc-kay** [comment]
Hi @sudotrigon 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@sudotrigon Thank you for your time. There was a bug in the main solution, and our team added a new main solution. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
