### ISSUE TITLE
Incorrect Test Cases - 396. Rotate Function

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#3389]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
For [396. Rotate Function](https://leetcode.com/problems/rotate-function), the last two test cases are incorrect.
The two test cases are as follows.
- For the test case that has input `[0,1,720000000]`, the expected output is `720000000`. However, the correct output should be `1440000001`. This value is calculated as `1440000001 = 0 * 0 + 1 * 1 + 2 * 720000000`.
- For the test case that has input `[0,1,800000000]`, the expected output is `800000000`. However, the correct output should be `1600000001`. This value is calculated as `1600000001 = 0 * 0 + 1 * 1 + 2 * 800000000`.

Besides, the standard program of this problem is incorrect. For the two test cases and the second test case provided in #3388, the standard program outputs the wrong answer (in Expected part). So the standard program of this problem should be fixed.

#### Code you used for Submit/Run operation
```
class Solution {
    public int maxRotateFunction(int[] nums) {
        long sum = 0, function = 0;
        int length = nums.length;
        for (int i = 0; i < length; i++) {
            sum += (long) nums[i];
            function += (long) i * (long) nums[i];
        }
        long maxFunction = function;
        for (int i = 1; i < length; i++) {
            function = function + sum - length * (long) nums[length - i];
            maxFunction = Math.max(maxFunction, function);
        }
        return (int) maxFunction;
    }
}
```

#### Language used for code
Java

#### Expected behavior
1. The last two test cases are incorrect, and they should be corrected.
   - For the test case that has input `[0,1,720000000]`, the expected output should be `1440000001`.
   - For the test case that has input `[0,1,800000000]`, the expected output should be `1600000001`.
2. The standard program outputs the incorrect answers for some test cases, so the standard program should be fixed.

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for your time. There was a bug in the main solution, and our team added a new main solution. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
