### ISSUE TITLE
Acceptance rate increasing when same solution of a question is resubmitted

### ISSUE THREAD

**Issue by aananditadhawan** [LeetCode-Feedback/LeetCode-Feedback#3393]
#### Your LeetCode username
aanandita

#### Description of the bug
By mistake, I clicked the submit button again after having already submitted the solution. And what I saw was that the same solution got accepted again. I submitted once again to check if acceptance rate  is also increasing and it was. I think this is an issue as it's not sort of a loophole and isn't fair.

#### Expected behavior
There should be a diff calculation sort of thing before accepting a new solution of already accepted question.

#### Screenshots
<img width="752" alt="Screenshot 2021-05-04 at 2 45 13 AM" src="https://user-images.githubusercontent.com/21183587/116934744-fde06680-ac82-11eb-9520-8019a13785b9.png">

**Comment by lc-kay** [comment]
@aananditadhawan We are aware that the acceptance rate is calculated on submissions, disregarding whether the submission is the same solution. However, we don't use that number to compare users' performance. Therefore, all users doing such will essentially be cheating themselves. We appreciate you pointing this out to us, though!
