### ISSUE TITLE
Test Cases Missing Considering Difficulty of 775. Global and Local Inversions

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#3395]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation
For [775. Global and Local Inversions](https://leetcode.com/problems/global-and-local-inversions), the data range is `1 <= n <= 5000`. A naive solution with `O(n^2)` time complexity can easily be accepted. However, the difficulty of this problem is Medium, which requires a solution with better time complexity.
Therefore, I suggest that the data range should be changed to `1 <= n <= 10^5`, and there must be one or more test cases that have `n == 10^5` so that the solution with `O(n^2)` time complexity will get TLE. In this way, the time complexity can be restricted.

```
class Solution {
    public boolean isIdealPermutation(int[] nums) {
        int length = nums.length;
        for (int i = 0; i < length; i++) {
            for (int j = i + 2; j < length; j++) {
                if (nums[i] > nums[j]) {
                    return false;
                }
            }
        }
        return true;
    }
}
```

#### Language used for code
Java

#### Expected behavior
The data range should be changed to `1 <= n <= 10^5`, and there must be one or more test cases that have `n == 10^5` so that the code above will get TLE.

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @stormsunshine 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
