### ISSUE TITLE
Existing test cases - 1520. Maximum Number of Non-Overlapping Substrings

### ISSUE THREAD

**Issue by pavanteja-potnuru** [LeetCode-Feedback/LeetCode-Feedback#3397]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Existing Test Case

#### Description of the bug
It is mentioned in the problem statement that `If there are multiple solutions with the same number of substrings, return the one with minimum total length. `

#### Code you used for Submit/Run operation
https://leetcode.com/submissions/detail/488543885/

```
class Solution {
public:
    vector<string> maxNumOfSubStrings(map<char, int> &lastI, string &s, int index, map<char, int> &firstI) {
        if(index == s.length()) return {};
        vector<string> sol = {};
        int maxCount = 0;
        int minTotalSize = INT_MAX;
        for(int i=index;i<s.length();i++) {
            // iterate over each index j starting form i an check for possiblities
            for(int j=i, maxI = lastI[s[i]];j<s.length();j++) {
                if(firstI[s[j]] < i) break; // if first index of s[j] is lessthan i we break the loop
                if(j == maxI) {
                    vector<string> temp = maxNumOfSubStrings(lastI, s, j+1, firstI);
                    int tempTotalLen = 0;
                    for(string a: temp) {
                        tempTotalLen += a.length();
                    }
                    // Checking Given condition for max possible substrings
                    if(temp.size() > maxCount || (temp.size() == maxCount && tempTotalLen< minTotalSize)) {
                        sol = temp;
                        sol.insert(sol.begin(), s.substr(i, j-i+1));
                        maxCount = temp.size();
                    }
                }
                else {
                    maxI = max(maxI, lastI[j]);
                }
            }
        }
        
        return sol;
    }
    vector<string> maxNumOfSubstrings(string s) {
        map<char, int> lastI; // last index at which char seen
        map<char, int> firstI; // first index at which char seen
        int n = s.length();
        for(int index=0;index<n;index++) {
            if(firstI.find(s[index]) == firstI.end()) firstI[s[index]] = index;
            lastI[s[index]] = index;
        }
        
        return maxNumOfSubStrings(lastI, s, 0, firstI);
    }
};
```

#### Expected behavior
`["bab"] or ["aba"] should be the answer`

#### Screenshots
![image](https://user-images.githubusercontent.com/41474837/116955401-1155f680-acb0-11eb-8bd8-7b4b1f6bbfda.png)

**Comment by pavanteja-potnuru** [comment]
Hi,
This is the second time I found issue while solving one of the Mock Interviews. Please make sure issues in Mock Interviews addressed first.

Pavan Teja,
Premium Membership holder

**Comment by neal2018** [comment]
Hey, `["bab"]` can not be the answer since it does not meet the second requirement in the description:

> 2. A substring that contains a certain character `c` must also contain all occurrences of `c`.

In this case, `"bab"` does not contain all occurrences of `a`, so it can not be the answer.

**Comment by pavanteja-potnuru** [comment]
Yes, my bad. Can you please look at https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/3325 issue too

Thank you

**Comment by pavanteja-potnuru** [comment]
Closing issue. @neal2018  thanks for replying.
