### ISSUE TITLE
Missing Test Case For Problem 1642. Furthest Building You Can Reach

### ISSUE THREAD

**Issue by sharshit** [LeetCode-Feedback/LeetCode-Feedback#3398]
#### Your LeetCode username
stalker_spotted

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ✓] Missing Test Cases 

#### Description of the bug
My Wrong code is accepted as correct solution for problem **1642. Furthest Building You Can Reach**

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int furthestBuilding(vector<int>& heights, int bricks, int ladder) {
        priority_queue<int>pq;
        int len = heights.size();
        int i=0;
        while(i<len-1)
        {
            if(heights[i+1]>heights[i])
            {
                int gap = heights[i+1]-heights[i];
                if(bricks<gap)
                {
                    if(ladder)
                    {
                        if(pq.size())
                        {
                            if(pq.top()<=gap)
                            {
                                ladder--;
                            }
                            else
                            {
                                ladder--;
                                bricks+=pq.top();
                                pq.pop();
                                continue;
                            }
                        }
                    }
                    else
                    {
                        return i;
                    }
                }
                else
                {
                    bricks -= gap;
                    pq.push(gap);
                }
            }
            i++;
        }
        return i;
    }
};

```

#### Language used for code
C++

#### Expected behavior
 For Input:
heights = [1,4,6,7] ,  bricks= 2 , ladders= 1
Expected output is 2 but my code output's 3 which is wrong and this wrong code is accepted as correct solution.

#### Screenshots

![LC_furthestbuilding](https://user-images.githubusercontent.com/32219146/116959670-e07bbe80-acbb-11eb-9f7e-14807d0399bd.JPG)

#### Additional context
I have filed same issue in leetcode contribute section as well (  https://leetcode.com/contribute/28640 )

**Comment by lc-kay** [comment]
Hi @sharshit 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @sharshit 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
