### ISSUE TITLE
998. Maximum Binary Tree II - Bug in "Use Example Testcases" button

### ISSUE THREAD

**Issue by roll-no-1** [LeetCode-Feedback/LeetCode-Feedback#340]
**Your LeetCode username**

roll_no_1

**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the bug**
On clicking the "Use Example Testcases" button in this problem, only a single test case gets copied in the "Custom Testcase" section instead of all 3. 

I was doing a virtual contest while I noticed this. It can be observed on this link: https://leetcode.com/contest/weekly-contest-125/problems/maximum-binary-tree-ii/

**what language is your code written in**
N/A

**The code you submit/run**
N/A

**Expected behavior**
On clicking the "Use Example Testcases", all 3 test cases should have been copied in the "Custom Testcase" section.

**Screenshots**
These are the examples:
![image](https://user-images.githubusercontent.com/36921843/82672781-727ee880-9c5e-11ea-9c98-d56f4d9e1a76.png)

And this is what happens on clicking the "Use Example Testcass" button:
![image](https://user-images.githubusercontent.com/36921843/82672640-39df0f00-9c5e-11ea-8476-bda60a0758fc.png)

**Additional context**
I observed it while doing a virtual contest, but the bug still holds.

**Comment by CooperCooperCooper** [comment]
Hi @roll-no-1 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by roll-no-1** [comment]
@CooperCooperCooper any updates?

**Comment by lc-christina** [comment]
Hi @roll-no-1 
Thank you for your time. Upon investigating this issue, we found this issue to be non-content-related (the issue stems from an origin away from the content on this problem); therefore, it's not valid for content contribution reward. 
However, the team has fixed the issue. When clicking the "Use Example Testcases", all 3 test cases are now copied in the "Custom Testcase" section. Thank you again for your support and understanding.
