### ISSUE TITLE
Incorrect constraints in the description - 452. Minimum Number of Arrows to Burst Balloons

### ISSUE THREAD

**Issue by gupta-arpit** [LeetCode-Feedback/LeetCode-Feedback#3400]
#### Your LeetCode username

fermi-0985-arpit

#### Category of the bug
- [x] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

The Constraints section mentions `0 <= points.length <= 10^4`. However, the judge doesn't accept a test case with 0 size.

#### Code you used for Submit/Run operation

```
class Solution {
    public int findMinArrowShots(int[][] points) {
        if (points.length <= 1) {
            return points.length;
        }
        Arrays.sort(points, (a, b) -> {
           return a[0] > b[0] ? 1 : -1; 
        });
        boolean[] busted = new boolean[points.length];
        int i = 1;
        int currStart = points[0][0];
        int currEnd = points[0][1];
        List<Integer> toBust = new ArrayList();
        toBust.add(0);
        int result = 0;

        while (i < points.length) {
            int[] balloon = points[i];
            if (busted[i]) 
                continue;

            if (balloon[0] > currEnd) {
                currStart = balloon[0];
                currEnd = balloon[1];
                for (int b: toBust)
                    busted[b] = true;
                toBust.clear();
                toBust.add(i);
                result++;
            } else {
                currEnd = Math.min(balloon[1], currEnd);
                toBust.add(i);
            }
            i++;
        }
        if (toBust.size() > 0)
            result++;
        return result;
    }
}
```

#### Language used for code

Java

#### Expected behavior

The description should be `1 <= points.length <= 10^4`

#### Screenshots

<img width="475" alt="image" src="https://user-images.githubusercontent.com/12170429/116990130-513cce00-acf0-11eb-92a9-0bcefd791d18.png">
<img width="529" alt="image" src="https://user-images.githubusercontent.com/12170429/116990263-7cbfb880-acf0-11eb-96ed-8087cd36046f.png">

**Comment by lc-kay** [comment]
Hi @gupta-arpit 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @gupta-arpit 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
