### ISSUE TITLE
Missing Test Case - 665. Non-decreasing Array

### ISSUE THREAD

**Issue by ratnesh93** [LeetCode-Feedback/LeetCode-Feedback#3401]
#### Category of the bug: Missing Test Cases 
- [ ] Missing Test Cases 

#### test case: '''[1,2,4,5,3,5]'''

```
// Non-decreasing Array
class Solution {
    public boolean checkPossibility(int[] nums) {

    }
};
```

#### Expected behavior: It should have returned true for my solution as my solution is accepted, but it returned false

![Screenshot from 2021-05-04 17-53-47](https://user-images.githubusercontent.com/6662711/117003130-1a6fb380-ad02-11eb-91f7-d54ff4756497.png)

**Comment by lc-kay** [comment]
@ratnesh93 Please provide the code that this test case failed on. Thank you.
