### ISSUE TITLE
Wrong Existing test case

### ISSUE THREAD

**Issue by rushabh120** [LeetCode-Feedback/LeetCode-Feedback#3402]
396. Rotate Function 

#### Your LeetCode username
d_rushabh

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

396. Rotate Function, wrong testcase result in the system 
Test case: 
![image](https://user-images.githubusercontent.com/26306253/117024253-72fd7b80-ad17-11eb-826b-efd15f493c14.png)

Output seems right: answer= 0 * (0) + 1 * (1) + 720000000 * (2) = 1440000001

Code is failing because of wrong expected output in the system.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int maxRotateFunction(vector<int>& A) {
	long long int sum = 0;
        long long int Func = 0;
        for (int i = 0; i < A.size(); i++) {
            Func += i * A[i];
            sum += A[i];
        }
        int mx = Func;
        for (int i = A.size() - 1; i >= 1; i--) {
            Func = Func + sum - A.size() * A[i];        
            mx = (Func > mx) ? Func : mx;
        }
        return mx; 
	}
};
```

#### Language used for code
C++ 

#### Expected behavior
Expected output should be 1440000001

#### Screenshots
As attached above

**Comment by lc-kay** [comment]
Hi @rushabh120 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@rushabh120 Thank you for your time. There was a bug in the main solution, and our team added a new main solution. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
