### ISSUE TITLE
Solution Bug - Question 619

### ISSUE THREAD

**Issue by dinesh-varyani** [LeetCode-Feedback/LeetCode-Feedback#3403]
#### Your LeetCode username
LeetCode ID: Dinesh-Varyani

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The solution provided as a SQL script is wrong. The description of the problem has a table name mentioned as 'my_numbers' but the solution script doesn't use it. Thus, upon running the solution SQL on the editor gives runtime error as - **'Table 'test.number' doesn't exist'**.
Below is the script provided in the solution, which is wrong - 

```
SELECT
    MAX(num) AS num
FROM
    (SELECT
        num
    FROM
        number
    GROUP BY num
    HAVING COUNT(num) = 1) AS t
;
```

#### Code you used for Submit/Run operation
The correct solution is - 

```
SELECT
    MAX(num) AS num
FROM
    (SELECT
        num
    FROM
        my_numbers
    GROUP BY num
    HAVING COUNT(num) = 1) AS t
;
```

#### Language used for code
MySQL

#### Expected behavior
The table name must be corrected in the provided solution. 
```
SELECT
    MAX(num) AS num
FROM
    (SELECT
        num
    FROM
        my_numbers
    GROUP BY num
    HAVING COUNT(num) = 1) AS t
;
```

**Comment by lc-kay** [comment]
Hi @dinesh-varyani 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @dinesh-varyani 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
