### ISSUE TITLE
Solution Bug - Question 597

### ISSUE THREAD

**Issue by dinesh-varyani** [LeetCode-Feedback/LeetCode-Feedback#3404]
#### Your LeetCode username
LeetCode ID: Dinesh-Varyani

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The solution provided as a SQL script is wrong. The description of the problem has table names mentioned as 'FriendRequest' and 'RequestAccepted' but the solution script doesn't use it. Thus, upon running the solution SQL on the editor gives runtime error as - **'Table 'test.request_accepted' doesn't exist'**.
Below is the script provided in the solution, which is wrong - 

```
select
round(
    ifnull(
    (select count(*) from (select distinct requester_id, accepter_id from request_accepted) as A)
    /
    (select count(*) from (select distinct sender_id, send_to_id from friend_request) as B),
    0)
, 2) as accept_rate;
```

#### Code you used for Submit/Run operation
The correct solution is - 

```
select
round(
    ifnull(
    (select count(*) from (select distinct requester_id, accepter_id from requestaccepted) as A)
    /
    (select count(*) from (select distinct sender_id, send_to_id from friendrequest) as B),
    0)
, 2) as accept_rate;
```

#### Language used for code
MySQL

#### Expected behavior
The table names must be corrected in the provided solution. 
```
select
round(
    ifnull(
    (select count(*) from (select distinct requester_id, accepter_id from requestaccepted) as A)
    /
    (select count(*) from (select distinct sender_id, send_to_id from friendrequest) as B),
    0)
, 2) as accept_rate;
```

**Comment by lc-kay** [comment]
Hi @dinesh-varyani 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @dinesh-varyani 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
