### ISSUE TITLE
Missing Test Case - 414. Third Maximum Number

### ISSUE THREAD

**Issue by UsernameUnavailableUnavailable** [LeetCode-Feedback/LeetCode-Feedback#3407]
#### Your LeetCode username

UsernameUnavailable

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

Test case [1, -2147483648, -2147483648, 2] exposes edge case that is not tested for acceptance.

#### Code you used for Submit/Run operation

Solution provided by user shoeb_0_0 is accepted but fails the new test case.

```
// 414. Third Maximum Number
class Solution {
public:
    int thirdMax(vector<int>& nums) {
      int first = INT_MIN;
      int second = INT_MIN;
      int third = INT_MIN;

      if(nums.size() == 3 && nums[0] != nums[1] && nums[0] != nums[2] && nums[1] != nums[2])
          return min(nums[0], min(nums[1], nums[2]));

      for(auto i : nums)
          if(i > first) first = i;
      for(auto i : nums)
          if(i != first && i > second) second = i;
      for(auto i : nums)
          if(i != first && i != second && i > third) third = i;

      if(third == INT_MIN) return first;
      return third;
    }
};
```

#### Language used for code
 C++

#### Expected behavior

Should give answer -2147483648, but provided code gives answer 2 and still is accepted on submission.

**Comment by lc-kay** [comment]
Hi @UsernameUnavailableUnavailable 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @UsernameUnavailableUnavailable 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
