### ISSUE TITLE
963. Minimum Area Rectangle II

### ISSUE THREAD

**Issue by aayoushee** [LeetCode-Feedback/LeetCode-Feedback#3408]
#### Your LeetCode username
ayushigarg1710

#### Category of the bug
Solution

#### Description of the bug
In the solution 2 of the article 963. Minimum Area Rectangle II problem, the solution says "They both have the same center O, which is the midpoint of AC and the midpoint of AB" rather it should be "They both have the same center O, which is the midpoint of AC and the midpoint of **BD** "

**Comment by lc-kay** [comment]
@aayoushee Thank you for reaching out to us. As this article is not up to our standards, we will be addressing all the issues and rewriting it soon. During that time, we will address the issue you have raised. We appreciate your time and support.
