### ISSUE TITLE
234. -129 is not a palindrome

### ISSUE THREAD

**Issue by kibebr** [LeetCode-Feedback/LeetCode-Feedback#341]
**What kind of the bug**
- [X] problem
- [ ] solution
- [ ] language

**Describe the bug**
One of the test cases expects `true`  for `-129` to be a palindrome.

**what language is your code written in**
Javascript 

**The code you submit/run**
```
var isPalindrome = function() {
    let head = new ListNode(-129, new ListNode(-129, null));

    if(!head || head.val === 0)
        return true;

    let ptr = head;
    let sum = "";

    while(ptr){
        sum += "" + ptr.val;
        ptr = ptr.next;
    }

    console.log(parseInt(sum));
    console.log(reverse(parseInt(sum)));

    if(parseInt(sum) === reverse(parseInt(sum)))
        return true;
    else
        return false;
};

const reverse = (num) =>
{
    const isNeg = (num < 0) ? true : false;

    if(isNeg)
        num = num * -1;

    let reversed = 0;

    while(num > 0){
        reversed = (reversed*10) + (num%10);
        num = parseInt(num/10);
    }

    return (isNeg) ? reversed * -1 : reversed;
 }; 
```

**Comment by CooperCooperCooper** [comment]
Hi @kibebr ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @kibebr ,
Thank you for your time. Our team review your code very thoroughly and found it to be using a wrong approach. Please check out the problem discuss section for inspiration.
