### ISSUE TITLE
Missing Test Case - 1588. Sum of All Odd Length Subarrays

### ISSUE THREAD

**Issue by Mihail19992004** [LeetCode-Feedback/LeetCode-Feedback#3411]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@Mihail19992004 Please provide more details on your missing test case report. After more information is provided, I will reopen this ticket. Thank you for your time.
