### ISSUE TITLE
Incorrect complexity - 859. Buddy Strings

### ISSUE THREAD

**Issue by campierce** [LeetCode-Feedback/LeetCode-Feedback#3415]
#### Your LeetCode username

cepie

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Approach 1 is not O(1) space complexity -- it is O(n) due to the set that is used to check for duplicates.

**Comment by lc-kay** [comment]
Hi @campierce 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@campierce The complexity is correct. A and B only consist of lower case letters so while A or B may be 10^4 characters long, the set seen will never exceed 26 elements, and pairs will never exceed length 3. Thank you for your time.
