### ISSUE TITLE
Table schema is inconsistent between description and database - 1205. Monthly Transactions II

### ISSUE THREAD

**Issue by l0latgithub** [LeetCode-Feedback/LeetCode-Feedback#3417]
#### Category of the bug
- [ ] Question

#### Description of the bug

The schema of Chargebacks table in description is "trans_id" and "charge_date". However both example and test cases use "trans_date".

Could you fix the typo when possible? 
Thanks

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
Hi @l0latgithub 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @l0latgithub 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!
