### ISSUE TITLE
Missing Test Case - 45. Jump Game II

### ISSUE THREAD

**Issue by fordvision** [LeetCode-Feedback/LeetCode-Feedback#3419]
#### Your LeetCode username
fvision

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ X] Missing Test Cases 

#### Description of the bug
Differentiates O(n) and non-O(n) implementations.
Input: [10000]*1000

#### Code you used for Submit/Run operation

```
class Solution:
    def jump(self, nums: List[int]) -> int:
        # An O(n) solution:
        l = len(nums)
        low = 0
        high = 0
        jumps_so_far = 0
        while high < l-1:
            next_high = high
            j = low
            while j <= high:
                next_high = max(next_high, j + nums[j])
                j += 1
            jumps_so_far += 1
            low = high
            high = next_high
            # print(jumps_so_far, low, high)
        return jumps_so_far
        
        
        # Slower solution:
        l = len(nums)
        jumps = [l+1]*l
        jumps[l-1] = 0
        i = l-2
        while i >= 0:
            n = l+1
            for j in range(i+1,min(l,i+1+nums[i])):
                n = min(n, 1+jumps[j])
            jumps[i] = n
            i -= 1
        return jumps[0]
```

#### Language used for code
Python

#### Expected behavior
First version of code is 40ms, second is 172ms

**Comment by lc-kay** [comment]
@fordvision Please provide the exact test case that will fail this solution. If the test case is too big, please provide it in a .txt file. Thank you.

**Comment by lc-kay** [comment]
Hi @fordvision 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
