### ISSUE TITLE
986: Contradictory Problem Statement and Method Signature

### ISSUE THREAD

**Issue by ayan-b** [LeetCode-Feedback/LeetCode-Feedback#342]
**What kind of the bug**
- [ ] problem
- [ ] solution
- [x] language

**Describe the bug**
From example 1 in the problem statement:
> Reminder: The inputs and the desired output are lists of Interval objects, and not arrays or lists.

and from the constraints:
> 0 <= A[i].start, A[i].end, B[i].start, B[i].end < 10^9

This was (possibly) true before Apr 15, 2019 as the method signature has been changed now. The method now accepts two lists of lists.

**Expected behavior**
`Reminder` should be removed and constraints should be updated following the new method signature.

LeetCode Handle: hello_wrld

**Comment by CooperCooperCooper** [comment]
Hi @ayan-b ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @ayan-b ,
Thank you for your time. We've used your feedback to update the problem. Please reach out to our main support channel "support@leetcode.com" with your LeetCode username, Github user info, and this issue to claim your valid contribution reward.
