### ISSUE TITLE
Incorrect description: Coin Change 2

### ISSUE THREAD

**Issue by karanbheda** [LeetCode-Feedback/LeetCode-Feedback#3420]
#### Your LeetCode username
TaZz

#### Category of the bug
- [* ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The problem requires us to find the total number of combinations that can be made with a given array to reach the target amount. If the target amount is not reachable, the description requires us to print "-1". But all the test cases are accepting "0" as the valid answer when the target is unreachable.

#### Code you used for Submit/Run operation

```
class Solution {
    public int change(int amount, int[] coins) {
        int[] dp = new int[amount + 1];
        int[] count = new int[amount + 1];
        Arrays.fill(dp, Integer.MAX_VALUE);
        dp[0] = 0;

        for(int i = 1; i <= amount; i++) {
            for(int j = 0; j < coins.length; j++) {
                if(i - coins[j] >= 0) {
                    if(dp[i - coins[j]] != Integer.MAX_VALUE) {
                        dp[i] = Math.min(dp[i], dp[i - coins[j]] + 1);
                        count[i]++;
                    }
                }
            }
        }

        int c = 0;
        for(int i = 1; i <= amount/2; i++) {
            if(count[i] != 0 && count[amount-i] != 0) 
                c+= Math.max(count[i], count[amount-i]);
        }
        
        return count[amount] == 0? -1: Math.max(c,count[amount]);
    }
}
```

#### Language used for code
Java

#### Expected behavior

According to the description, it was expected to print "-1" if the target amount was unreachable. But apparently all the test cases are accepting 0 as the valid answer

#### Screenshots

![image](https://user-images.githubusercontent.com/20036739/117242038-10f56100-ae52-11eb-8b61-a76eb32ff58e.png)

**Comment by lc-kay** [comment]
Hi @karanbheda 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @karanbheda 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
