### ISSUE TITLE
Typo in Hint 1 - 1770. Maximum Score from Performing Multiplication Operations

### ISSUE THREAD

**Issue by Kishanjay** [LeetCode-Feedback/LeetCode-Feedback#3421]
#### Your LeetCode username
KishanNirghin

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
There is a typo in Hint 1. the correct text should be:

greedily take the largest value from the ~begging~**beginning** or the end

**Comment by lc-kay** [comment]
Hi @Kishanjay 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @Kishanjay 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
