### ISSUE TITLE
3. 无重复字符的最长子串，输入是“”，为什么预期结果是1？

### ISSUE THREAD

**Issue by gzhsnail** [LeetCode-Feedback/LeetCode-Feedback#3422]
**你的 LeetCode 用户名**
土拨鼠

**Bug 类型**
- [ ] 3. 无重复字符的最长子串
- [ ] 答题
- [ ] golang

**描述**
为什么输入是“”，预期结果是1？

**你使用的语言**
golang

**你提交或者运行的代码**
```

```

**期望行为**
描述你期望的结果

**屏幕截图**
![图片](https://user-images.githubusercontent.com/54012788/117268237-a5c78100-ae89-11eb-9a44-c2231ccb1708.png)

**额外的上下文**
为什么预期结果是1

**Comment by feiceh** [comment]
你好，如果出现测试用例结果和提交结果不一致的情况，可以再仔细检查并调试一下代码，或点击这里：「[为什么某些测试用例下，执行代码返回结果正确，但提交解答却出错了](https://leetcode.kf5.com/hc/kb/article/1194344/)」 获得更多帮助。

同时也可以点击「题解」来查看当前题目的解题思路，或 [点击这里](https://leetcode-cn.com/circle/other/?page=1&query=) 「讨论」，将疑问发布在对应的社区中，与大家一同交流，获得更加有效的支持和帮助。
