### ISSUE TITLE
Missing Test Case - 79. Word Search

### ISSUE THREAD

**Issue by utkarsh-khandelwal12** [LeetCode-Feedback/LeetCode-Feedback#3425]
#### Your LeetCode username
not_a_coder26

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ . ] Missing Test Cases 

#### Description of the bug
The solution shows a TLE for test case mentioned below but gets accepted by the server.
[["A","A","A","A","A","A"],["A","A","A","A","A","A"],["A","A","A","A","A","A"],["A","A","A","A","A","A"],["A","A","A","A","A","A"],["A","A","A","A","A","A"]]
"AAAAAAAAAAAABAA"
or for any other testcase where B is not in last. 

#### Code you used for Submit/Run operation

```
// 79. Word Search
class Solution {
public:
    
    bool search(vector<vector<char>>& board,int i,int j,int n,int m, string word,vector<vector<int>> a,string s)     {
        s+=board[i][j];
        a[i][j]=1;
        if(s==word)
            return true;
        if(s.length()>word.length())
            return false;
        if((j+1)<m){
            if(a[i][j+1]==0)
                if(search(board,i,j+1,n,m,word,a,s))
                    return true;
        }
       
        
        if((j-1)>=0){
            if(a[i][j-1]==0)
                if(search(board,i,j-1,n,m,word,a,s))
                    return true;
        }
        if((i+1)<n){
            if(a[i+1][j]==0)
                if(search(board,i+1,j,n,m,word,a,s))
                    return true;
        }
        if((i-1)>=0){
            if(a[i-1][j]==0)
                if(search(board,i-1,j,n,m,word,a,s))
                    return true;
        }
        return false;
    }
    
    
    bool exist(vector<vector<char>>& board, string word) {
        int n=board.size();
        int m=board[0].size();
        vector<vector<int> > a( n , vector<int> (m, 0));  
        int f=0;
        for(int i=0;i<n;i++){
            for(int j=0;j<m;j++){
                if(board[i][j]==word[word.length()-1])
                    f=1;
                }
            }
        if(f==0)
            return false;
        for(int i=0;i<n;i++){
            for(int j=0;j<m;j++){
                if(board[i][j]==word[0]){
                    string s="";
                    if(search(board,i,j,n,m,word,a,s))
                        return true;
                }    
            }
        }
        return false;
    }
};
```

#### Language used for code
C++

#### Expected behavior
The code should not be accepted and show TLE

#### Additional context
I looked solutions of fellow coders as well and most had made there code specifically to check for the last element.

**Comment by lc-kay** [comment]
Hi @utkarsh-khandelwal12 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @utkarsh-khandelwal12 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
