### ISSUE TITLE
1047. Question could be framed better, Current behavior does not match Title description

### ISSUE THREAD

**Issue by aishwaryapdabhade** [LeetCode-Feedback/LeetCode-Feedback#3427]
#### Question
1047. Remove All Adjacent Duplicates In String

#### LeetCode username
minuteman1911

#### Category of the bug
- [x] Question

#### Description of the bug

Good problem, however the question could be better framed like:
Duplicate removal of ONLY two/even number of adjacent and equal letters. 
The word ONLY is important because for the following two testcases it produces different results, while you intuitively expect the same ( because of how the question is framed):
Testcase 1:
Input : "abbbbbaaaaca"
Output: "abca"
Testcase 2:
Input: "abbbbaaaca"
Output: "ca"
The difference being, Testcase 1 has odd number of repeated characters ( 'b' and 'a' ) and Testcase 2 has even number

#### Expected behavior
The Title is Remove All Adjacent Duplicates In String, so one would expect all duplicates be removed.
The question ( and answer ) could be modified so Testcase 1 and Testcase 2 produce the same result.

**Comment by lc-kay** [comment]
Hi @aishwaryapdabhade 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @aishwaryapdabhade 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
