### ISSUE TITLE
187. 重复的DNA序列

### ISSUE THREAD

**Issue by CLannadZSY** [LeetCode-Feedback/LeetCode-Feedback#343]
** Bug 类型**
- [x] 题目

**描述**
这是你题目的说明, 麻烦你们自己读一读, 能读通顺吗?
编写一个函数来查找 DNA 分子中所有出现超过一次的 10 个字母长的序列（子串）。

**期望行为**
编写一个函数来查找子串，这个子串长度为10，在原字符串中出现的次数超过一次。

**题目截图**
![image](https://user-images.githubusercontent.com/38000492/82726706-6a837f00-9d18-11ea-91a5-a59aef8ba1c6.png)

**Comment by feiceh** [comment]
感谢反馈，已更新描述为「编写一个函数来查找目标子串，目标子串的长度为 10，且在 DNA 字符串 s 中出现次数超过一次。」谢谢。
