### ISSUE TITLE
The verfication of test cases is wrong - 109. Convert Sorted List to Binary Search Tree

### ISSUE THREAD

**Issue by CagyJ** [LeetCode-Feedback/LeetCode-Feedback#3430]
#### Your LeetCode username

CagyJ

#### Category of the bug
- [109] Question
- [ ] Solution
- [Java] Language
- [ ] Missing Test Cases 

#### Description of the bug

The output of test cases is wrong. The output and the expected r not same, but the solution is true.

#### Code you used for Submit/Run operation

```
class Solution {
    public TreeNode sortedListToBST(ListNode head) {
        return process(head, null);
    }
    private TreeNode process(ListNode start, ListNode end) {
        if (start == null || start == end) {
            return null;
        }
        var slow = start;
        var fast = start;
        while (fast.next != end && fast.next.next != end) {
            slow = slow.next;
            fast = fast.next.next;
        }
        var cur = new TreeNode(slow.val);
        cur.left = process(start, slow);
        cur.right = process(slow.next, end);
        return cur;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Fix the expected output, otherwise, it will be so confused for any people, they will figure the wrong out all the time even they r right.

#### Screenshots

![image](https://user-images.githubusercontent.com/47696220/117418359-9c86f480-af1b-11eb-8aa8-c9d15d473c7d.png)

**Comment by lc-kay** [comment]
Hi @CagyJ 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.
