### ISSUE TITLE
Missing Test Case - 31. Next Permutation

### ISSUE THREAD

**Issue by yogi2103** [LeetCode-Feedback/LeetCode-Feedback#3432]
#### Your LeetCode username
user6678q

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [X ] Missing Test Cases 

#### Description of the bug
This code is giving passing all the test cases when I initialize variable, not declaring so basically with garbage value. But when I assign it value=0 then it's not passing.

#### Code you used for Submit/Run operation

```
// Next Permutation
class Solution {
public:
    void nextPermutation(vector<int>& arr) {
int n=arr.size();
        int index1;
        for(int i=n-2;i>=0;i--){
            if(arr[i]<arr[i+1]){
                index1=i;
                break;
            }
        }
        
        if(index1>=0){
            int index2=0;
            for(int i=n-1;i>=0;i--){
                if(arr[i]>arr[index1]){
                    index2=i;
                    break;
                }
        }
            swap(arr[index1],arr[index2]);
        }
        reverse(arr.begin()+index1+1,arr.end()); 
    }
};
```

#### Language used for code
C++

#### Expected behavior
This shouldn't pass the test cases as index1 is not initialized and garbage value is there. Because if we talk about the next permutation for [3 2 1] then it should be [1 2 3] but when we are reversing the array how's it taking the value of index1 with -1.

#### Screenshots
![Screenshot (179)](https://user-images.githubusercontent.com/57219370/117434290-1c2bb800-af4a-11eb-817f-8b351b4d4b67.png)

**Comment by lc-kay** [comment]
@yogi2103 Please privide the exact missing test case you wish to report. Thank you!

**Comment by yogi2103** [comment]
it's giving the correct answer for array [3 2 1], If there's garbage value in my index1 which it shouldn't. Because next permutation of array [3 2 1] would be [1 2 3] right. It means array should reverse itself but check the logic in my code when I'm reversing the array. You'll get what I mean to say. Thank you!

**Comment by lc-kay** [comment]
@yogi2103 For the test case [3 2 1] returns an invalid testcase error. For a valid missing test case report, please provide a testcase that will fail an accepted solution.

**Comment by yogi2103** [comment]
But it's accepting the solution when I'm not initializing the variable index1. Ideally it shouldn't give.

**Comment by lc-kay** [comment]
@yogi2103 For further concerns and doubts about this, please refer to the problem discuss section. Thank you for your time.
