### ISSUE TITLE
1300. Sum of Mutated Array Closest to Target (My submission is accepted even though one test case fails)

### ISSUE THREAD

**Issue by phenomenalAC** [LeetCode-Feedback/LeetCode-Feedback#3433]
#### Category of the bug
- [1300 ] Question
- [ ] Solution
- [ Python] Language
- [ nums = [2,2]
target = 3] Missing Test Cases 

#### Description of the bug

My solution is accepted even though it fails for one the test cases

#### Code you used for Submit/Run operation

```
class Solution:
    def findBestValue(self, arr: List[int], target: int) -> int:
        arr.sort()
        length = len(arr)
        
        for x in range(length):
            sol = round(target / length)
            if arr[x] >= sol:
                return sol
            target -= arr[x]
            length -= 1
        
        return arr[-1]   ```

#### Language used for code
<!-- Python -->


#### Expected behavior
<!-- . -->



#### Screenshots
<!--
![image](https://user-images.githubusercontent.com/69207223/117444542-3ddf6c00-af57-11eb-968a-07fa5c938b4c.png)
 -->



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by lc-kay** [comment]
Hi @phenomenalAC 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @phenomenalAC 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by phenomenalAC** [comment]
Thanks for the update, my leetcode id is phenomenalAC
