### ISSUE TITLE
Typo in constraints - 493. Reverse Pairs

### ISSUE THREAD

**Issue by srikar7777** [LeetCode-Feedback/LeetCode-Feedback#3434]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

constraint given is 2<sup>31</sup> <= nums[i] <= 2<sup>31</sup> - 1
it should be -2<sup>31</sup> <= nums[i] <= 2<sup>31</sup> - 1

**Comment by lc-kay** [comment]
Hi @srikar7777 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @srikar7777 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
