### ISSUE TITLE
Missing Test Case - 1041. Robot Bounded In Circle

### ISSUE THREAD

**Issue by amandeep-verma** [LeetCode-Feedback/LeetCode-Feedback#3435]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The test cases are not sufficient enough. Following are the missing type of test cases- 
1. The test cases with atleast 1 'G' appended by robot rotation of more than 360 in either of direction at 1 go (occurrence of 4L or 4R).
example -  "GRRRR",  "GLLLL"

2.  The test cases with atleast 1 'G', where robot rotates more than 720 in either of direction at 1 go (occurrence of L or R in multiple of 4 but greater than 4).
example "GLLLLLLLL" , "GGGRRRRRRRR", "GRRRRRRRRG"

My code runs successfully even though it should fail at these test cases.

#### Code you used for Submit/Run operation

```

class Solution {
    public boolean isRobotBounded(String ins) {
        
        // let direction facing in x axis be 0 degree
        int dir = 90; // represting north
        int x=0; 
        int y=0;
        
        for ( int i = 0; i < ins.length(); i++)
        {
            char move = ins.charAt(i);
            
            if(move == 'L')
                dir+= 90;
            else if(move == 'R')
                dir-= 90;
            else{
                if(dir<0)
                    dir += 360;
                if(dir>=360)
                    dir = dir%360;
                
                if(dir ==0 )
                    x+=1;
                else if(dir == 90)
                    y+=1;
                else if(dir == 180)
                    x-=1;
                else
                    y-=1;
            }
        }
        
        //System.out.println(dir); // uncomment it to see final dir angle
        
        return dir != 90 || ( x==0 && y==0);   
    }
}

```

#### Language used for code: 

Java

#### Expected behavior

The variations of loop I used should fail the code which can be observed by the test cases I have provided. Irrespective of which I was able successfully run it.

**Comment by lc-kay** [comment]
Hi @amandeep-verma 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @amandeep-verma 
Thank you for your time. We've used your feedback to update the problem. Please provide your LeetCode ID to receive 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by amandeep-verma** [comment]
LeetCode ID - RebirthRaven
