### ISSUE TITLE
面试题 16.01. 交换数字 | 数据弱

### ISSUE THREAD

**Issue by zerotrac** [LeetCode-Feedback/LeetCode-Feedback#3438]
**你的 LeetCode 用户名**

喵

**Bug 类型**
- [x] 测试数据

**描述**

做加减法的时候当然要考虑溢出问题，有符号整数的溢出在 c++ 中是 undefined behavior

**你使用的语言**

C++

**你提交或者运行的代码**

https://leetcode-cn.com/problems/swap-numbers-lcci/solution/1601-cchao-100de-nao-jing-ji-zhuan-wan-b-y6ue/
https://leetcode-cn.com/problems/swap-numbers-lcci/solution/shi-jian-fu-za-du-o1kong-jian-fu-za-du-o-tx0l/

**无法通过的测试数据**

[-2147483647,2147483647]

**Comment by feiceh** [comment]
感谢反馈，当前题目已调整更新，力扣会定期更新，保障稳定和体验优化。
