### ISSUE TITLE
Missing Test Case - 1099. Two Sum Less Than K

### ISSUE THREAD

**Issue by tomerlieber** [LeetCode-Feedback/LeetCode-Feedback#3439]
#### Your LeetCode username
LeetCode ID: TomerLieber

#### Category of the bug
- Missing Test Cases 

#### Description of the bug
My code passes the test cases, although it returns a wrong output for the following input:
nums=[1, 2, 4, 5]     k=6
It should return 5, but it returns -1 instead.
It should return 5 because 1 + 4 = 5 and it is the closest sum to 6

#### Code you used for Submit/Run operation
```
class Solution {
    public int twoSumLessThanK(int[] nums, int k) {
        
        Arrays.sort(nums);
        
        int low = 0;
        int high = nums.length - 1;
        
        int maxSum = -1;
        
        while (low < high) {
            
            int sum = nums[low] + nums[high];
            
            if (sum < k && sum > maxSum) {
                maxSum = sum;
            }
            
            if (sum <= k) {
                low++;
            }
            else {
                high--;
            }
        }
        
        return maxSum;
    }
}
```

#### Language used for code
Java

**Comment by lc-kay** [comment]
Hi @tomerlieber 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @tomerlieber 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
