### ISSUE TITLE
133. Clone Graph

### ISSUE THREAD

**Issue by prathamprakash29** [LeetCode-Feedback/LeetCode-Feedback#344]
The question description says that the graph is a "connected" undirected graph.
Then there is a test case when the graph is empty. 

An empty graph cannot be connected, hence the test case does not satisfy the problem description.
This test case should be removed from the problem, as it is also leading to so many downvotes in the question.

**Comment by CooperCooperCooper** [comment]
Hi @prathamprakash29 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @prathamprakash29 ,
Thank you for your time. We will keep this feedback in mind for future updates. For now, we will keep the problem as is due to technical design purposes.
