### ISSUE TITLE
Test Case Is Wrong

### ISSUE THREAD

**Issue by Kevinhutama** [LeetCode-Feedback/LeetCode-Feedback#3440]
"WWEQERQWQWWRWWERQWEQ"

Expected is 4.
i think the correct answer  shud be 3.

EEEE (4x)
RRR (3x)
WWWWWWWW (8x)
QQQQQ (5x)

Just need to perform 3 action
W -> R
W -> R
W ->E

**Comment by lc-kay** [comment]
@Kevinhutama Please provide the problem title and number. Thank you.

**Comment by lc-kay** [comment]
Hi @Kevinhutama 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.
