### ISSUE TITLE
341. Flatten Nested List Iterator - Problem Description Not Verbose

### ISSUE THREAD

**Issue by dtsdwarak** [LeetCode-Feedback/LeetCode-Feedback#3442]
#### Your LeetCode username
zombiethread

#### Category of the bug
- [x] Question
- ~~[ ] Solution~~
- ~~[ ] Language~~
- ~~[ ] Missing Test Cases~~ 

#### Question Link
[341. Flatten Nested List Iterator](https://leetcode.com/problems/flatten-nested-list-iterator/)

#### Language used for code
C++

#### Description of the bug
The question assumes that solution should parse the `nestedList` during constructor initialization. As a result, if we maintain "iterator state" to parse the list at runtime, we end up having no way to handle `[[]]` testcase.

Solution and error faced in the submission - 
https://leetcode.com/submissions/detail/490462330/

#### Code you used for Submit/Run operation

```cpp
/**
 * // This is the interface that allows for creating nested lists.
 * // You should not implement it, or speculate about its implementation
 * class NestedInteger {
 *   public:
 *     // Return true if this NestedInteger holds a single integer, rather than a nested list.
 *     bool isInteger() const;
 *
 *     // Return the single integer that this NestedInteger holds, if it holds a single integer
 *     // The result is undefined if this NestedInteger holds a nested list
 *     int getInteger() const;
 *
 *     // Return the nested list that this NestedInteger holds, if it holds a nested list
 *     // The result is undefined if this NestedInteger holds a single integer
 *     const vector<NestedInteger> &getList() const;
 * };
 */

class NestedIterator {
public:
    
    queue<int> q;
    vector<NestedInteger> nestedListParam;
    int currentIndex;
    
    NestedIterator(vector<NestedInteger> &nestedList) {
        nestedListParam = nestedList;
        currentIndex = 0;
    }
    
    void parseNestedInteger(NestedInteger &nestedInteger) {
        
        if (nestedInteger.isInteger()) {
            q.push(nestedInteger.getInteger());
            return;
        }
        
        vector<NestedInteger> nestedIntegers = nestedInteger.getList();
        
        for(NestedInteger i : nestedIntegers) {
            parseNestedInteger(i);
        }
        
    }
    
    int next() {
        
        if (q.empty() && hasNext())
            parseNestedInteger(nestedListParam[currentIndex++]);
        
        if (!q.empty()) {
            int x = q.front();
            q.pop();
            return x;
        }
        
        return -1;
    }
    
    bool hasNext() {
        
        return !q.empty() || (currentIndex < nestedListParam.size());
        
    }
};

/**
 * Your NestedIterator object will be instantiated and called as such:
 * NestedIterator i(nestedList);
 * while (i.hasNext()) cout << i.next();
 */
```

#### Expected behavior
1. If it is expected to return empty response, a clear description ought to be given that `hasNext()` will be called before every `next()` call.
2. Or allow for a compatible return value for the return type signature provided in the method. Like for `int`, it can be `INT_MIN` or so.

**Comment by lc-kay** [comment]
Hi @dtsdwarak 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by dtsdwarak** [comment]
Thanks @lc-kay

**Comment by lc-kay** [comment]
Hi @dtsdwarak 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
