### ISSUE TITLE
225. Implement Stack using Queues: Followup asks the impossible

### ISSUE THREAD

**Issue by himittal09** [LeetCode-Feedback/LeetCode-Feedback#3443]
#### Your LeetCode username
himittal09

#### Category of the bug
- [ ] Question

#### Description of the bug
The Followup asks to re-implement the problem in an *amortized O(1) time complexity*. Which is impossible given the problem. What the followup wanted to ask is to re-solve the problem using only one queue (data structure).

#### Code you used for Submit/Run operation

```
class Stack {
public:
	queue<int> que;
	// Push element x onto stack.
	void push(int x) {
		que.push(x);
		for(int i=0;i<que.size()-1;++i){
			que.push(que.front());
			que.pop();
		}
	}

	// Removes the element on top of the stack.
	void pop() {
		que.pop();
	}

	// Get the top element.
	int top() {
		return que.front();
	}

	// Return whether the stack is empty.
	bool empty() {
		return que.empty();
	}
};
```

#### Expected behavior

none

**Comment by lc-kay** [comment]
@himittal09 There is an O(1), please refer to the discussions and they will find it there contributed by many users. Thank you for your time.
