### ISSUE TITLE
Incorrect Constraint - 906. Super Palindromes

### ISSUE THREAD

**Issue by archit11111** [LeetCode-Feedback/LeetCode-Feedback#3444]
#### Your LeetCode username
archit91

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The question mentions the following constraint - 
* `left` and `right` represent integers in the range `[1, 10^18]`.

However, `10^18` cannot be represented by the given range because`1 <= left.length, right.length <= 18` is also a constraint.

#### Code you used for Submit/Run operation

```
N/A
```

#### Language used for code
N/A

#### Expected behavior

The constraint should be modified to - 
* `left` and `right` represent integers in the range `[1, 10^18 - 1]` (or `[1, 10^18)`  denoting right exclusive).

**Comment by lc-kay** [comment]
Hi @archit11111 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!
