### ISSUE TITLE
Missing Test Case - 1856. Maximum Subarray Min-Product

### ISSUE THREAD

**Issue by rexue70** [LeetCode-Feedback/LeetCode-Feedback#3447]
#### Your LeetCode username
rexue70

#### Category of the bug
- [ x ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
test case not pass for java, in this question we have O(nlogn) solution but big test case just failed.

#### Code you used for Submit/Run operation

```
class Solution {
    int MOD = (int)1e9 + 7;
    public int maxSumMinProduct(int[] nums) {
        int N = nums.length;
        return (int)(calculate(nums, 0, nums.length - 1) % MOD);
    }
    
    private long calculate(int[] nums, int start, int end) {
        if (start > end) return 0;
        int minIndex = start, sum = 0;
        for (int i = start; i <= end; i++) {
            if (nums[minIndex] > nums[i]) minIndex = i;
            sum += nums[i];
        }
        long cur = nums[minIndex] * sum;
        long left = calculate(nums, start, minIndex - 1);
        long right = calculate(nums, minIndex + 1, end);
        return Math.max(cur, Math.max(left, right));
    }
}
```

#### Language used for code
Java

#### Expected behavior
should pass since data is O(10^5)

#### Screenshots
![image](https://user-images.githubusercontent.com/15324686/117561424-8f692300-b04b-11eb-8bc3-fe55b23fce1d.png)

#### Additional context
python can pass using same way

**Comment by stormsunshine** [comment]
The submission result is WA, not TLE. Therefore this has nothing to do with time complexity.
