### ISSUE TITLE
Missing Test Case - 1354. Construct Target Array With Multiple Sums

### ISSUE THREAD

**Issue by Sparsh-Goyal-2000** [LeetCode-Feedback/LeetCode-Feedback#3448]
#### Your LeetCode username

SparshGoyal

#### Category of the bug
- [6 ] Missing Test Cases 
- Missing test cases:
[1]
[2]
[1, 2]
[1,1,2]
[1, 1000000000]
[5, 50]

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    bool isPossible(vector<int>& A) {
        long total = 0;
        int n = A.size(), a;
        priority_queue<int> pq(A.begin(), A.end());
        for (int a : A)
            total += a;
        while (true) {
            a = pq.top(); pq.pop();
            total -= a;
            if (a == 1 || total == 1)
                return true;
            if (a < total || total == 0 || a % total == 0)
                return false;
            a %= total;
            total += a;
            pq.push(a);
        }
    }
};
```

#### Language used for code

C++

#### Expected behavior

Missing test cases:
[1]
[2]
[1, 2]
[1,1,2]
[1, 1000000000]
[5, 50]

**Comment by lc-kay** [comment]
@Sparsh-Goyal-2000 For a valid missing test case report, the test cases must fail an accepted solution. The code you provided all outputs the expected output for the test cases.
