### ISSUE TITLE
Missing Test Case - 1354. Construct Target Array With Multiple Sums

### ISSUE THREAD

**Issue by shadow1399** [LeetCode-Feedback/LeetCode-Feedback#3449]
#### Your LeetCode username
satyansh1399 

#### Category of the bug
- [1 ] Missing Test Cases 

#### Description of the bug
My Submission is accepted however, it is giving wrong answer for various test cases.
eg. [1,1,10] gives the answer as false and my code doesn't produce correct answer then also it is accepted.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool isPossible(vector<int>& target) {
        int n=target.size();
        priority_queue<int>pq;
        unsigned int sm=0;
        for(auto p:target){
            pq.push(p);
            sm+=p;
        }
        while(!pq.empty()){
            auto f=pq.top();
            pq.pop();
            if(f==1){
                return true;
            }
            if((sm-f)<f){
                sm-=f;
                if(sm<1){
                    return false;
                }
                
                f=f%sm;
                sm+=f;
                // cout<<sm<<endl;
                pq.push(f);
            }
            else{
                return false;
            }
        }
        
        return true;
    }
};
```

#### Language used for code
 C++

#### Expected behavior
I expected the answer of one of the missing testcase which is [1,1,10] to be false but my code is giving the answer true
then also it got accepted.

**Comment by lc-kay** [comment]
Hi @shadow1399 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
