### ISSUE TITLE
Ruby memory not being ranked correctly

### ISSUE THREAD

**Issue by KevinColemanInc** [LeetCode-Feedback/LeetCode-Feedback#345]
**What kind of the bug**
- [ ] problem
- [ ] solution
- [x] language

**Describe the bug**
For the Kth Largest element in an array, the ruby memory recommendation isn't being calculated correctly

**what language is your code written in**
ruby

**The code you submit/run**
https://leetcode.com/problems/kth-largest-element-in-an-array/submissions/

```
# @param {Integer[]} nums
# @param {Integer} k
# @return {Integer}
def partition(nums, left, right, pivot_index)
  pivot = nums[pivot_index]

  nums[pivot_index], nums[right] = nums[right], nums[pivot_index]

  store_index = left
  i = left    
  while i < right
    if nums[i] < pivot
      nums[store_index], nums[i] = nums[i], nums[store_index]
      store_index += 1
    end
    i+= 1
  end
  nums[store_index], nums[right] = nums[right], nums[store_index]
  store_index
end

def select(nums, left, right, k_smallest)
  return nums[left] if left == right
  
  pivot_index = rand(left..right)
  store_index = partition(nums, left, right, pivot_index)
  
  if (store_index) == k_smallest
    return nums[store_index]
  elsif (store_index) > k_smallest
    left = 0
    right = store_index - 1
  elsif (store_index) < k_smallest
    left = store_index + 1
    right = nums.length - 1
  end
  return select(nums, left, right, k_smallest)
end

def find_kth_largest(nums, k)
  retained = []
  1_000_000.times do
    retained << "a string"
  end

 select(nums,0,nums.length - 1, nums.length - k)
end

```

**Expected behavior**
This says the memory usage of 181MB is less than 100% of ruby submissions. I created an array with 1 million useless strings, causing my program to run in 2 seconds, but it still uses less memory than every other ruby submission? Something is wrong here... I expect the memory to be in the bottom 5% (like the time is)

**Screenshots**

<img width="730" alt="image" src="https://user-images.githubusercontent.com/2381771/82737971-5b390d00-9ce9-11ea-9394-e7271b058ed4.png">

**Additional context**

**Comment by CooperCooperCooper** [comment]
Hi @KevinColemanInc ,
Thank you for your time. I've relayed this issue to our team to investigate. Upon reviewing the submission page of this problem, we found that this problem currently do not have enough accepted Ruby submissions to compare, which is why your memory usage is "less than 100% of Ryny online submissions". I am sorry about the confusion. You can click on that "Details >" link to see the entire message in the submission details page.

**Comment by KevinColemanInc** [comment]
@CooperCooperCooper 

Why would there be enough ruby submissions to determine the % for CPU, but not memory?

**Comment by CooperCooperCooper** [comment]
Hi @KevinColemanInc ,
Thank you for your feedback, I've shared it with our team to take a deeper look into the issue.

**Comment by lc-pam** [comment]
Hi @KevinColemanInc 
Thank you for your time. We've used your report to fix the issue. We appreciate your support!
