### ISSUE TITLE
Wrong result for: 968. Binary Tree Cameras

### ISSUE THREAD

**Issue by kaushlendra-rai** [LeetCode-Feedback/LeetCode-Feedback#3450]
https://leetcode.com/problems/binary-tree-cameras/

#### Your LeetCode username

KaushlendraRai 

#### Category of the bug
- [ ] Missing Test Cases  - Answer is wrong

#### Description of the bug

For the given Binary tree below, answer should be '3', however bith the coes return answer as '2'.
On manual inspection, optimal node selections are: 1, 3 & 4. Answer should be '3'. However, the solution provided gives answer as '2'.

TreeNode b1 = new TreeNode(1);
		TreeNode b2 = new TreeNode(2);
		TreeNode b3 = new TreeNode(3);
		TreeNode b4 = new TreeNode(4);
		TreeNode b5 = new TreeNode(5);
		TreeNode b6 = new TreeNode(6);
		TreeNode b7 = new TreeNode(7);
		TreeNode b8 = new TreeNode(8);
		b1.left = b2;
		b1.right = b3;
		b2.left = b4;
		b4.left = b5;
		b4.right = b6;
		b3.left = b7;
		b3.right = b8;

Can you explain how '2'?

#### Code you used for Submit/Run operation

I checked the solution provided by leetcode. Both DP & greedy. Both return answer as '2'.

**Comment by lc-kay** [comment]
@kaushlendra-rai The expected output is correct. For a better understanding, please raise this question on the problem discuss page. Thank you for your time.
