### ISSUE TITLE
167. Incorrect description

### ISSUE THREAD

**Issue by vadim-marchuk** [LeetCode-Feedback/LeetCode-Feedback#3453]
#### Your LeetCode username
RichardRal

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
1. The question asserts that the input array "sorted in ascending order".
2. A constraint asserts that input array "numbers is sorted in increasing order".

In fact, it should be "non-descending" and "non-decreasing" accordingly because there is a test case with the same numbers in the input array
[ 1, 2, 3, 4, 4, 9, 56, 90 ]

#### Screenshots
<img width="1143" alt="Screenshot 2021-05-09 at 19 41 25" src="https://user-images.githubusercontent.com/54034636/117580081-cba98b80-b0fe-11eb-821f-0e1a038007cc.png">

**Comment by lc-kay** [comment]
Hi @vadim-marchuk 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @vadim-marchuk 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
