### ISSUE TITLE
Missing Test Case - 1354. Construct Target Array With Multiple Sums

### ISSUE THREAD

**Issue by anthonyschiller** [LeetCode-Feedback/LeetCode-Feedback#3454]
#### Your LeetCode username

antsch1

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [* ] Missing Test Cases 

#### Description of the bug

Test case missing: [6,1,1]

#### Code you used for Submit/Run operation
```
class Solution {
    public boolean isPossible(int[] target) {
        int sum=0;
        PriorityQueue<Integer> q=new PriorityQueue<>(Collections.reverseOrder());
        for(int i=0;i<target.length;i++){
            sum+=target[i];
            q.add(target[i]);
        }
        while(q.peek()!=1){
            int lar=q.poll();        
            sum=sum-lar;
            if(q.size()==1 && sum==1)
                return true;
            if( sum==0 || lar-sum<1)
                return false;            
            else{
                q.add(lar%sum);
                sum+=(lar%sum);
            }                
        } 
    }
}       
```

#### Language used for code

Java

#### Expected behavior

This test case should be set with expectation of _false_.

**Comment by lc-kay** [comment]
@anthonyschiller Please provide the submission details link. Thank you.

**Comment by anthonyschiller** [comment]
sure, the submission link is as follows: https://leetcode.com/submissions/detail/490928584/

**Comment by lc-kay** [comment]
Hi @anthonyschiller 
Thank you for providing that. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @anthonyschiller 
Thank you for your time. The team reviewed your report and noticed your code failed on a recently added test case. Therefore, the test case you contributed becomes invalid so we didn't add the test case. We appreciate your support!
