### ISSUE TITLE
Missing Test Case - 425. Word Squares

### ISSUE THREAD

**Issue by fiferdc** [LeetCode-Feedback/LeetCode-Feedback#3455]
#### Your LeetCode username
bluelink91

#### Category of the bug
- [X] Question
- [X] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
While the problem statement mentions that each `word[i]` is unique, palindromes can cause the same word to be repeated in a square.  For example, the input `["lol", "oto", "apa"]` generates the output `[["lol","oto","lol"]]`.  The code provided below was used to pass all existing tests and generated the before-mentioned output, as did the expected answer.

Words appearing multiple times in the square should either be called out in the problem statement or the solution should be updated to remove this exception (which makes my provided solution invalid).

#### Code you used for Submit/Run operation

``` javascript
var wordSquares = function(words) {
    // Sort words for easy prefix scans
    words.sort();
    const WORD_LEN = words[0].length;
    
    // Initialize prefix map
    const prefixMap = {
        '': { // Empty string allows for recursive function to grab all words for initial loop
            start: 0,
            end: words.length-1
        }
    };
    for (let i = 0; i < words.length; ++i) {
        const word = words[i];
        let key = '';
        for (let j = 0; j < WORD_LEN - 1; ++j) {
            key += word.charAt(j);
            if (!prefixMap[key]) {
                prefixMap[key] = {
                    start: i
                };
            }
            prefixMap[key].end = i;
        }
    }
    
    const squares = [];
    const findSquares = (partialSquare = []) => {
        const i = partialSquare.length;
        if (i === WORD_LEN) {
            squares.push(partialSquare);
            return;
        }
        const prefix = partialSquare.reduce((prefix, word) => prefix + word.charAt(i), '');
        const candidates = prefixMap[prefix];
        if (!candidates) return;
        for (let i = candidates.start; i <= candidates.end; ++i) {
            findSquares([...partialSquare, words[i]]);
        }
    }
    
    findSquares();
    return squares;
};
```

#### Language used for code

JavaScript

#### Expected behavior

If words can only be used once in the square, the output should be `[[]]`.

**Comment by lc-kay** [comment]
Hi @fiferdc 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @fiferdc 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
